### ISSUE TITLE
beta8: web.config exception when deploying to IIS

### ISSUE THREAD

**Issue by YehudahA** [aspnet/Home#1000]
Hello. i'm beginner with asp.net vNext.

I have VS2015, and I installed the new beta8. I created new API project, and make to changes:
1. I added "Microsoft.AspNet.Server.IIS": "1.0.0-beta7" dependency.
2. I changed "solution DNX SDK version" to beta8.

The project can running locally without any problem.

Now, I published the project to local file system, and copied the output to remote IIS server[2012].
On the iis, I created a new site, and set the physical path to wwwroot directory.

Now, in IE I test the site, but I get an error: "HTTP Error 500.19 - Internal Server Error
 The requested page cannot be accessed because the related configuration data for the page is invalid.

Thanks for any help.

**Comment by davidfowl** [comment]
Can you make a new project and try using that and seeing if it works?

**Comment by YehudahA** [comment]
David, I used VS template as is, with two changes have detailed above.

UPDATE:
After reading [this post](https://azure.microsoft.com/en-us/blog/announcing-the-release-of-the-httpplatformhandler-module-for-iis-8/), I realized that I have to install HttpPlatformHandler on the target IIS.
I did it and installed HttpPlatformHandler  x64 version.

Now, I get another error:
HTTP Error 502.3 - Bad Gateway
Most likely causes:
•The CGI application did not return a valid set of HTTP errors.
•A server acting as a proxy or gateway was unable to process the request due to an error in a parent gateway.

Detailed Error Information:
Module
   httpPlatformHandler 

Notification
   ExecuteRequestHandler 

Handler
   httpplatformhandler 

Error Code
   0x8007053d 


Thanks again for any help.

**Comment by davidfowl** [comment]
@YehudahA Try reading this post http://blogs.msdn.com/b/webdev/archive/2015/10/15/announcing-availability-of-asp-net-5-beta8.aspx

**Comment by YehudahA** [comment]
Devid, I've read that article and also this https://docs.asp.net/..servers.htmlhighlight=commands#servers-and-commands and more.

But I did not understand what I need to do and how configure the project.json.

I tried also using the Empty template provided by VS, the same problem occurs.
I googled and read a lot of articles, but it's hard to know which is updated.

**Comment by GuardRex** [comment]
@YehudahA Check this list of steps against what you've done thus far: https://github.com/aspnet/Hosting/issues/364#issuecomment-148567294

**Comment by YehudahA** [comment]
@GuardRex, I am in total despair. I did EXCACTLY those steps. nothing help.
This is my project.json content:
```
{
  "webroot": "wwwroot",
  "version": "1.0.0-*",

  "dependencies": {
    "Microsoft.AspNet.IISPlatformHandler": "1.0.0-beta8",
    "Microsoft.AspNet.Mvc": "6.0.0-beta8",
    "Microsoft.AspNet.Server.Kestrel": "1.0.0-beta8",
    "Microsoft.AspNet.StaticFiles": "1.0.0-beta8",
    "Microsoft.Framework.Logging": "1.0.0-beta8",
    "Microsoft.Framework.Logging.Console": "1.0.0-beta8",
    "Microsoft.Framework.Logging.Debug": "1.0.0-beta8",
    "Microsoft.AspNet.Hosting": "1.0.0-beta8"
  },

  "commands": {
    "web": "Microsoft.AspNet.Hosting --server Microsoft.AspNet.Server.Kestrel"
  },

  "frameworks": {
    "dnx451": { },
    "dnxcore50": { }
  },

  "exclude": [
    "wwwroot",
    "node_modules"
  ],
  "publishExclude": [
    "**.user",
    "**.vspscc"
  ]
}
```

This is global.json content:
```
{
  "projects": [ "src", "test" ],
  "sdk": {
    "version": "1.0.0-beta8"
  }
}
```

This is Startup.cs content
``` csharp
    public class Startup
    {
        public Startup(IHostingEnvironment env)
        {
        }

        public void ConfigureServices(IServiceCollection services)
        {
            services.AddMvc();
        }

        public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
        {
            loggerFactory.MinimumLevel = LogLevel.Information;
            loggerFactory.AddConsole();
            loggerFactory.AddDebug();

            app.UseIISPlatformHandler();
            app.UseStaticFiles();
            app.UseMvc();
        }
    }
```

And this is the pubxml content:
``` xml
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <WebPublishMethod>FileSystem</WebPublishMethod>
    <LastUsedBuildConfiguration>Release</LastUsedBuildConfiguration>
    <LastUsedPlatform>Any CPU</LastUsedPlatform>
    <SiteUrlToLaunchAfterPublish />
    <LaunchSiteAfterPublish>True</LaunchSiteAfterPublish>
    <ExcludeApp_Data>False</ExcludeApp_Data>
    <CompileSource>False</CompileSource>
    <UsePowerShell>True</UsePowerShell>
    <IISCommand>web</IISCommand>
    <WebRoot>wwwroot</WebRoot>
    <WwwRootOut>wwwroot</WwwRootOut>
    <IncludeSymbols>False</IncludeSymbols>
    <Native>False</Native>
    <IgnoreDNXRuntime>False</IgnoreDNXRuntime>
    <publishUrl>..\..\artifacts\bin\Api100\Release\PublishOutput</publishUrl>
    <DeleteExistingFiles>False</DeleteExistingFiles>
    <PublishDNXVersion>dnx-clr-win-x64.1.0.0-beta8</PublishDNXVersion>
  </PropertyGroup>
</Project>
```

**Comment by GuardRex** [comment]
@YehudahA You've done a server restart since the installation, correct? Did you turn on the `HttpPlatformHander` log in `web.config`?
```
<httpPlatform 
  processPath="%DNX_PATH%"
  arguments="%DNX_ARGS%"
  stdoutLogEnabled="true" 
  stdoutLogFile="..\logs\httpplatform-stdout"
  startupTimeLimit="3600"/>
```
... and check for the presence of the log and its contents if it is there. Note that I have a `logs` folder in my project to receive logs; but if you leave out the `stdoutLogFile`, it will write the log files to your `wwwroot`. Because I use that path, my logs end up way down in a package folder ...
```
F:\<app_folder>\approot\packages\<app_name>\1.0.0\root\logs
```
Without supplying a path, the logs on the server are written to a `logs` folder created for you in the project physical directory (same place as your `approot` and `wwwroot` folders). Then, of course, check Event Viewer and see if anything is popping up there. btw -- Post your full `web.config`.

If the log isn't even appearing, check the IIS Modules and make sure you see `httpPlatformHandler` in the list. Check IIS Handler Mappings for the app and make sure it appears there and is "Enabled."

The only diff between what you've posted thus far and my test app is that I'm `dnxcore50` only, so my `Global.json` calls out for the x64 coreclr SDK explicitly and there is no `dnx451` framework in my `project.json`, but this diff shouldn't be a problem.

If you don't get much further with it, put up a repo of the project, and I'll put it on my VM and see if I can get it to run here. But keep in mind that this is The Walking Dead night, so I'll be half-drunk :beers: and yelling at the TV screen in a few hours. I can test your project here later this evening.

**Comment by luchen1021** [comment]
Get the same error HTTP Error 502.3 - Bad Gateway with following event log.  The ..\logs\stdout.log is created but always empty.  This happens even with DNXCore50 beta 8.  Windows Server 2012 R2 and IIS 8.5.  HttpPlatformHandler is installed and enabled in the IIS Handler Mapping.

<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
	<System>
	  <Provider Name="HttpPlatformHandler" /> 
	  <EventID Qualifiers="0">1000</EventID> 
	  <Level>2</Level> 
	  <Task>0</Task> 
	  <Keywords>0x80000000000000</Keywords> 
	  <TimeCreated SystemTime="2015-10-19T01:42:37.000000000Z" /> 
	  <EventRecordID>21095</EventRecordID> 
	  <Channel>Application</Channel> 
	  <Computer>*****</Computer> 
	  <Security /> 
	</System>
	<EventData>
	<Data>Process '0' failed to start. Port = 1145, Error Code = '-2147024894'.</Data> 
	</EventData>
</Event>

**Comment by GuardRex** [comment]
@luchen1021 Check out: 

https://github.com/aspnet/Hosting/issues/364#issuecomment-142517221
https://github.com/aspnet/Hosting/issues/364#issuecomment-144003845

... feels like the wrong version of `HttpPlatformHandler`. Look at Control Panel > Programs and see if v1.2 shows up as the one installed on the server. If not, get rid of whatever is there and go with:

x64 version: http://go.microsoft.com/fwlink/?LinkId=690721

**Comment by YehudahA** [comment]
@luchen1021 Thank you! You've solved my problem!
Please note that there links to the old version, you might want to fix them. https://azure.microsoft.com/en-us/blog/announcing-the-release-of-the-httpplatformhandler-module-for-iis-8/

I thank you very much and I hope that from now on things will go easily and not difficulty. 
Thanks also to the rest of the members who helped and contributed.

**Comment by GuardRex** [comment]
@YehudahA Yes, both the Microsoft Download Center at http://www.iis.net/downloads/microsoft/httpplatformhandler and WebPI still have v1.0.

**Comment by pragmat1c** [comment]
I have the exact same issue as luchen1021:

Windows Server 2012R2/IIS 8.5

When browsing to the site:

HTTP Error 502.3 - Bad Gateway
There was a connection error while trying to route the request.

Application Event Log:
Process '0' failed to start. Port = 20313, Error Code = '-2147024894'.

I followed the instruction here:
https://github.com/aspnet/Hosting/issues/364#issuecomment-148567294

I have v1.2 of the HttpPlatformHandler installed.

My web.config:

<configuration>
  <system.webServer>
    <handlers>
      <add name="httpplatformhandler" path="*" verb="*" modules="httpPlatformHandler" resourceType="Unspecified" />
    </handlers>
    <httpPlatform processPath="%DNX_PATH%" arguments="%DNX_ARGS%" stdoutLogEnabled="true" stdoutLogFile="..\logs\stdout.log" startupTimeLimit="3600" forwardWindowsAuthToken="false"></httpPlatform>
  </system.webServer>
</configuration>

Any thoughts on what to try?

**Comment by GuardRex** [comment]
@pragmat1c That's most likely caused by having the wrong version of the HttpPlatformHandler installed on your server. Go to Control Panels > Programs > Programs and Features and see what version you have installed. It should say v1.2.

**Comment by pragmat1c** [comment]
@GuardRex, Yes I've check (and double and triple checked) the version. it is v1.2.

```xml
<configuration>
  <system.webServer>
    <handlers>
      <add name="httpplatformhandler" path="*" verb="*" modules="httpPlatformHandler" 

resourceType="Unspecified" />
    </handlers>
    <httpPlatform processPath="..\approot\web.cmd" arguments="" stdoutLogEnabled="true" 

stdoutLogFile="..\logs\stdout.log" startupTimeLimit="3600" 

forwardWindowsAuthToken="false"></httpPlatform>
  </system.webServer>
</configuration>
```

**I changed my web.config back to the "deployed" version above and now I get a 404 when browsing to my app.**

In my log I get:
warning : [Microsoft.Framework.DependencyInjection.DataProtectionServices] Neither user profile nor HKLM registry available. Using an ephemeral key repository. Protected data will be unavailable when application exits.
warning : [Microsoft.AspNet.DataProtection.Repositories.EphemeralXmlRepository] Using an in-memory repository. Keys will not be persisted to storage.
Hosting environment: Production
Now listening on: http://localhost:24750
Application started. Press Ctrl+C to shut down.

The contents of my ..\approot\web.cmd file:

```batch

@echo off
SET DNX_FOLDER=dnx-clr-win-x64.1.0.0-beta8
SET "LOCAL_DNX=%~dp0runtimes\%DNX_FOLDER%\bin\dnx.exe"

IF EXIST %LOCAL_DNX% (
  SET "DNX_PATH=%LOCAL_DNX%"
)

for %%a in (%DNX_HOME%) do (
    IF EXIST %%a\runtimes\%DNX_FOLDER%\bin\dnx.exe (
        SET "HOME_DNX=%%a\runtimes\%DNX_FOLDER%\bin\dnx.exe"
        goto :continue
    )
)

:continue

IF "%HOME_DNX%" NEQ "" (
  SET "DNX_PATH=%HOME_DNX%"
)

IF "%DNX_PATH%" == "" (
  SET "DNX_PATH=dnx.exe"
)

@"%DNX_PATH%" --project "%~dp0packages\WebTotal\1.0.0\root" --configuration Release web %*

```

**Comment by GuardRex** [comment]
@pragmat1c Check this out: https://github.com/aspnet/Hosting/issues/412

**Comment by pragmat1c** [comment]
@GuardRex, I'm sorry, but I don't see how that issue is relevant to mine?

**Comment by GuardRex** [comment]
@pragmat1c My bad ... I was confused on who was on Azure Web Apps. They were having an issue with the `processPath`. Since it seems it is finding the command, I don't think it matters that I'm using `processPath="%DNX_PATH%"` and `arguments="%DNX_ARGS%"`. Try with my settings just to make sure.

I also have a different "web" command ...
```
"web": "Microsoft.AspNet.Hosting --server Microsoft.AspNet.Server.Kestrel"
```
... but I've seen other posters using the one you have and haven't heard issues on it. I'd try that, too, just to make sure. You have the `Microsoft.AspNet.Hosting` package, correct?

How is the 404 being thrown? ... Is a view of your's, or is it an empty response body with a status code of 404?

Since you have the log enabled, dump any log files in that folder on the server, make a request to the app and get your 404. Check to see if a log was generated and has a proper looking entry ... e.g.,...
```
Process Id: 14428
Waiting for the debugger to attach...
Debugger attached.
Hosting environment: Development
Now listening on: http://localhost:2949
Application started. Press Ctrl+C to shut down.
```
Do a static file test: Put a `test.htm` file in your `wwwroot` folder (of course, you need `"Microsoft.AspNet.StaticFiles": "1.0.0-beta8",` and `app.UseStaticFiles();`) and make sure that the module can at least return a static html file to the browser. If it can, then it feels like an MVC issue. If it can't, it feels like a module config issue.

**Comment by pragmat1c** [comment]
@GuardRex any static file also returns a 404 with an empty response body. (For instance any request for a css or js file in my app).

I've also tried: 
```json
"web": "Microsoft.AspNet.Hosting --server Microsoft.AspNet.Server.Kestrel"
```

No luck.

If i browse directly to http://localhost:24750 (the url in the logs) the site is loaded.

My hunch is the httpPlatformHandler is not working properly.  But again, see my previous answer where I have version 1.2 installed.

**Comment by GuardRex** [comment]
@pragmat1c That's a good sign that you can hit it at localhost. How are your bindings setup for the app? Can you delete whatever binding you have for the app and re-add it? I'd look in the logs, too, to make sure IIS is seeing the requests: `C:\inetpub\logs\LogFiles`

**Comment by pragmat1c** [comment]
@GuardRex,
Could you elaborate on the "bindings"? I'm not quite following you.
Thanks!

**Comment by GuardRex** [comment]
@pragmat1c 

![capture](https://cloud.githubusercontent.com/assets/1622880/10643796/64ae3794-77ea-11e5-9b89-3c8df06db553.PNG)

**Comment by pragmat1c** [comment]
@GuardRex,
This is an application running under the "Default Web Site". The Bindings are fine, I can get to the default web site.

Yes, IIS is logging the requests.
```
#Software: Microsoft Internet Information Services 8.5
#Version: 1.0
#Date: 2015-10-21 18:58:18
#Fields: date time s-ip cs-method cs-uri-stem cs-uri-query s-port cs-username c-ip cs(User-Agent) cs(Referer) sc-status sc-substatus sc-win32-status time-taken
2015-10-21 18:58:18 10.10.4.44 GET /MyApp/css/site.css - 80 - 10.10.16.17 Mozilla/5.0+(Windows+NT+10.0;+WOW64)+AppleWebKit/537.36+(KHTML,+like+Gecko)+Chrome/46.0.2490.71+Safari/537.36 - 404 0 0 3016
```

**Comment by pragmat1c** [comment]
@GuardRex,
Turnds out it was this issue:
https://github.com/aspnet/Hosting/issues/416#issuecomment-149046552

I had to do that app.Map fix in the Startup.cs Configure method.
```C#
app.Map("/MyApp", (app1) => this.Configure1(app1, env, loggerFactory));
```
My app is now working.

**Comment by Sharpiro** [comment]
I was receiving the bad web.config and the bad gateway error when try trying to deploy to IIS prior to installing the correct* http platform handler.

However, I am still getting a related issue when deploying to Azure with beta 8.  The deployment succeeds, but when the page opens all i get is a 500 error and the message:
```
The specified CGI application encountered an error and the server terminated the process.
```

**Comment by GuardRex** [comment]
@pragmat1c Cool. I added that reference to my guidance.

@Sharpiro That one has mostly been associated with the DNX_PATH. See https://github.com/aspnet/Hosting/issues/412

**Comment by cda-1** [comment]
I get this error in beta8 when I try to get entities with circular dependencies (oops) using EF7. For example if I want a student with all enrolledcourses, and student specifies a collection of courses and enrollments specifies a studentId, I get the bad gateway error. Totally my fault but it seems like a weird error to get.

**Comment by GuardRex** [comment]
@cda-1 Was the app working before? The bad gateway exception is most often linked to having the wrong version of the HttpPlatformHandler installed. You're right ... that's not the correct exception to expect for an EF problem AFAIK.

**Comment by cda-1** [comment]
I have 1.2 installed. Is HttpPlatformHandler relevant for IIS Express? I get the error in both IISExpress and IIS proper on Windows 10.

If I do a GET against my API that returns an entity without a circular dependency, it comes right up. If I GET one with a circular dependency, I see:

HTTP Error 502.3 - Bad Gateway
The specified CGI application encountered an error and the server terminated the process.

But then I can go right back to requesting the good entity and it's fine. There's no lag whatsoever, so it's not restarting the process or anything.

**Comment by GuardRex** [comment]
Yes, it's relevant. Ah ... so it is an app/EF issue. If you're getting a response (even a static file), the HttpPlatformHandler is doing its thing.

Have you tried to configure the app with the exception page: 
```
"Microsoft.AspNet.Diagnostics": "1.0.0-rc1-final",
```
and 
```
app.UseDeveloperExceptionPage();
```

**Comment by cda-1** [comment]
Mine only goes up to beta8 -- is rc1 released? I do use UseDeveloperExceptionPage though. That page works very well (and is beautiful, by the way) for every other error I have encountered.

**Comment by GuardRex** [comment]
Yes, it's released. Perhaps, try the upgrade first, then see if it clears with all of the new bits they put into RC1. You'll need the installer here: https://get.asp.net/OtherDownloads

**Comment by cda-1** [comment]
options.SerializerSettings.ReferenceLoopHandling = Newtonsoft.Json.ReferenceLoopHandling.Ignore in Startup.cs fixes the issue, but I will go ahead and un-fix it  and try RC1

**Comment by GuardRex** [comment]
Wow. Good catch. Maybe the EF cats know more. Post here to see what they say: https://github.com/aspnet/EntityFramework/issues

**Comment by cda-1** [comment]
Updated to rc1 and the same error happens. I reported it to the EntityFramework repo as you suggested.

**Comment by GuardRex** [comment]
@cda-1 issue moved to https://github.com/aspnet/EntityFramework/issues/3818

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
