### ISSUE TITLE
Beta8 incorrect package version configuration

### ISSUE THREAD

**Issue by ForkBug** [aspnet/Home#1001]
Create a class project with the following project.json:

```
{
  "version": "1.0.0-*",
  "description": "ClassLibrary1 Class Library",
  "authors": [ "fu" ],
  "tags": [ "" ],
  "projectUrl": "",
  "licenseUrl": "",
  "dependencies": {    
    "Microsoft.AspNet.Http.Abstractions": "1.0.0-beta8",
    "Microsoft.AspNet.Http.Extensions": "1.0.0-beta8"
  },

  "frameworks": {
    "dnx451": { },
    "dnxcore50": {
      "dependencies": {
        "Microsoft.CSharp": "4.0.1-beta-23409",
        "System.Collections": "4.0.11-beta-23409",
        "System.Linq": "4.0.1-beta-23409",
        "System.Runtime": "4.0.21-beta-23409",
        "System.Threading": "4.0.11-beta-23409"
      }
    }
  }
}
```

When we build it, we'll get:
DNX Core 5.0 error NU1002: The dependency System.IO.FileSystem.Primitives 4.0.0 in project ClassLibrary1 does not support framework DNXCore,Version=v5.0.

For persons encounter same problem, adding

```
  "frameworks": {
    "dnx451": { },
    "dnxcore50": {
      "dependencies": {
        "System.IO.FileSystem.Primitives": "4.0.1-beta-23409"
      }
    }
```

to tell dependency resolution using correct version, will fix this error.

And could you guys from Microsoft share more document about project.json, especially about spec of version string? And global.json. 
Obviously some dxncore developers don't quiet know this well also.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
