### ISSUE TITLE
I can't get a https request on IISExpress in Visual Studio after beta8 upgrade

### ISSUE THREAD

**Issue by Rinsen** [aspnet/Home#1003]
When i call the included repo app via http or https i always get context.Request.IsHttps = false in my class HttpsRedirectMiddleware included in the repo

https://github.com/Rinsen/HttpsProblemWithKestrel

In Visual Studio I have the check box with Enable SSL checked and a valid URL(https://localhost:44300/) as i always have done earlier but now it does not work any more, any ideas on what is wrong?

The browser of course gives me a ERR_TOO_MANY_REDIRECTS when I try to run this code.

**Comment by Tratcher** [comment]
You need the `app.UseIISPlatformHandler();` to forward the scheme as described here: https://github.com/aspnet/Hosting/issues/364

**Comment by Rinsen** [comment]
Thanks!

That thread was so huge that I have missed that part...
