### ISSUE TITLE
IHttpUpgradeFeature "IsUpgradableRequest" is never true in IIS Express

### ISSUE THREAD

**Issue by Sharpiro** [aspnet/Home#1005]
IHttpUpgradeFeature "IsUpgradableRequest" is never true in IIS Express profile, but works when running from kestrel via default "web" profile.  Likely an issue with: ```"Microsoft.AspNet.IISPlatformHandler": "1.0.0-beta8"```

Repro:

Create an empty web application from the asp.net 5 templates.  Add the following lines of code inside ```app.Run``` inside Startup.cs:
```
var temp = context.Features.Get<IHttpUpgradeFeature>().IsUpgradableRequest;
var upgradeFeature = context.Features.Get<IHttpUpgradeFeature>();
```

Send the following line of code via a web browser:
```
var socket = new WebSocket("ws://localhost:---your port here---");
```

I am able to achieve a "true" value from "temp" when running from kestrel "web" profile only.  The "temp" value is always false when running form IIS Express.

**Comment by Tratcher** [comment]
This issue was moved to aspnet/IISIntegration#19
