### ISSUE TITLE
dnu/dnx fail silently on OS X 10.11

### ISSUE THREAD

**Issue by RadarBee** [aspnet/Home#1006]
Not sure if this is happening on other platforms, but, on OS X 10.11 both dnu and dnx fail (silently) to execute at all with 1.0.0-beta8. beta7 still works fine. Has anyone else experienced this and found a remedy?

**Comment by tushargupta51** [comment]
This is because 'icu4c' is needed for the System.Globalization in beta8 on OS X. Try 'brew install icu4c'. I am not sure if we have the updated docs for beta8 out yet.

**Comment by PureKrome** [comment]
Doc's mention this step. (2nd brew step. i know cause i did it last night and googled what the hell did `icu4c` mean. i thought it was made up `person-randonly-hitting-the-keyboard` or a github commit hash :)

**Comment by ellismg** [comment]
FWIW, this requirement (on OSX) will be removed for RC1.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
