### ISSUE TITLE
The beta8 sample console app has an invalid version number

### ISSUE THREAD

**Issue by Tragetaschen** [aspnet/Home#1008]
[`"System.Console": "4.0.0-beta-beta8"`](https://github.com/aspnet/Home/blob/dev/samples/1.0.0-beta8/ConsoleApp/project.json#L12) doesn't look right and doesn't restore properly

@glennc

**Comment by andrewm1986** [comment]
Pull request #1048 fixes this

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
