### ISSUE TITLE
Setting localization cookie based on provider results

### ISSUE THREAD

**Issue by karl-sjogren** [aspnet/Home#1009]
What would be the most appropriate way to set a cookie for CookieRequestCultureProvider based the value returned by the RequestProviders? If I chose a culture by appending it to the querystring I would like this to be persisted so I don't have to reuse that querystring all the time but I haven't figured out when that cookie should be created. I'm leaning against adding another middleware for it just after the localization stuff but it feels a bit hacky to put this outside of the localization pipline.

There is a nice helper method, CookieRequestCultureProvider.MakeCookieValue, that I could use but it isn't used in any samples. Any suggestions on this?

**Comment by Eilon** [comment]
@karl-sjogren can you post this question in https://github.com/aspnet/Localization/issues/? There's where the loc experts hang out.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
