### ISSUE TITLE
Bootstrapper project for common packages

### ISSUE THREAD

**Issue by lazarofrancoe** [aspnet/Home#1010]
Hi.

Would it be possible (in beta8+) to have a bootstrapper project which has installed all packages required by the entire project, **without** having to reference the bootstrapper project from the others projects? (if I add the references, Entity Framework, for example, would be available in my Web project, which is not desirable).

Thank you
### Added

I also noticed that it is not possible to have a Bootstrapper project and inject dependencies from a Repository project, since it would mean a circular reference: from bootstrapper to repo for inject dependencies, from repo to bootstrapper for making use of Entity Framework DbContext. I do not know if there is another way of doing this.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
