### ISSUE TITLE
The dependency AspNet.Security.OpenIdConnect.Server >= 1.0.0-beta3 could not be resolved

### ISSUE THREAD

**Issue by jojo-jose** [aspnet/Home#1011]
I can not get the package  AspNet.Security.OpenIdConnect.Server beta3.

In my visual studio, the latest one I can see is latest prerelease 1.0.0-beta2.

I have contacted the author, he informed me that he has uploaded the latest build beta3 to https://www.nuget.org/packages/AspNet.Security.OpenIdConnect.Server/1.0.0-beta3 on 2015-10-16 and I can see that. But my visual studio can not find that!

![visualstudioabout](https://cloud.githubusercontent.com/assets/14935747/10622838/aec594f4-77d5-11e5-9ef6-8727a41e7801.png)
![openiderrormessages](https://cloud.githubusercontent.com/assets/14935747/10622837/aebe62e2-77d5-11e5-8510-792df5d0e4a6.png)
![openidvisualstudio](https://cloud.githubusercontent.com/assets/14935747/10622839/aec9e0c2-77d5-11e5-99f7-e63642980551.png)

**Comment by Eilon** [comment]
@yishaigalatzer seems related to NuGet?

**Comment by jojo-jose** [comment]
yes. I can see beta 2, but not beta3...

**Comment by yishaigalatzer** [comment]
What is your project type and target framework?

**Comment by jojo-jose** [comment]
asp.net web application, 1.0.0-beta8

**Comment by yishaigalatzer** [comment]
Does it work if you change the source to https://www.nuget.org/api/v2 ?

**Comment by jojo-jose** [comment]
Yes, there I can see beta3. Can I use this?

**Comment by maartenba** [comment]
Seems this package wasn't properly indexed. Can you give it another try?

**Comment by PinpointTownes** [comment]
@jojo-jose glad you finally sorted it out! :smile:

@maartenba interesting. Is there something I can do to fix/avoid that?

**Comment by maartenba** [comment]
We're looking into how this happened.

**Comment by PinpointTownes** [comment]
Okay, thanks! :clap:

FYI, I changed my push script: unlike the first releases, the new packages have been uploaded concurrently. Could that be a concurrency issue?

**Comment by maartenba** [comment]
It shouldn't be an issue, but it's a great pointer for our research. May be a good thing to not push in parallel for a while.

**Comment by jojo-jose** [comment]
Now I can see beta3 from api.nuget.org. Thanks very much for all your support
