### ISSUE TITLE
Beta 8: default web api projects, 404 issue

### ISSUE THREAD

**Issue by petrhaus** [aspnet/Home#1013]
Create the default web api project.

Open Postman and issue a GET /api/values -> 200 OK
Then issue a DEL /api/values/1 -> 200 OK
Now issue a GET /api/values -> 200 OK
Again GET /api/values -> **404 NOT FOUND**
Again GET /api/values -> 200 OK and so on for all subsequent requests

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
