### ISSUE TITLE
Issue while referencing external DLL after upgarding to Beta 8

### ISSUE THREAD

**Issue by ankitvijay** [aspnet/Home#1014]
Hi, I'm getting runtime exception in my project on external DLL reference after upgrading the project to beta 8 from beta 7. Below are the details:
-- Class Library (Package) has reference to an external library
       -- Console (Package) refers the above Class Library and tries to call a method defined in Class Library. It also has reference to the same external library.

Before Upgrade: The application the compiled successfully and worked as expected
After Upgrade: The application compiles successfully, however at runtime it throws an exception.

**Comment by Zahid-Ashiq** [comment]
Hi, i am also facing the same issue and also i am facing the following error with dnvm beta 8
"Could not load file or assembly 'Microsoft.Dnx.Host.Clr' or one of its dependencies. The system cannot find the file specified."

**Comment by NeelBhatt** [comment]
Can you show your  global.json file?

**Comment by Zahid-Ashiq** [comment]
Below is the my global.json file setting:

{
    "projects": [ "" ],
    "sdk": {
        "architecture": "x86",
        "runtime": "clr",
        "version": "1.0.0-beta8"
    }
}

**Comment by NeelBhatt** [comment]
looks fine to me. I have found something similar. If you can relate here:

https://github.com/aspnet/dnx/issues/2392

**Comment by davidfowl** [comment]
Please read the blog post, release  notes and annoucements for beta8 http://blogs.msdn.com/b/webdev/archive/2015/10/15/announcing-availability-of-asp-net-5-beta8.aspx

**Comment by ankitvijay** [comment]
Hi David, I have gone through the blog post, one point that was relevant to this case was "Explicitly target dependencies at packages or projects". I tried to explicitly define target but it didn't help. Is there anything specific I need to look into? My global.json is:
{
  "projects": [
    "src",
    "test",
    "wrap"
  ],
  "sdk": {
    "version": "1.0.0-beta8"
  }
}

**Comment by Zahid-Ashiq** [comment]
Hi ankitvijay, i have been solved the "DLL reference after upgrading the project to beta 8" issue after restore the nuget packages. Means that Go into package manager console window and run the command "dnx restore" without quotes. Second, also additional thing is that you can install the "WebToolsExtensionsVS14". You can read the below post and good for migrations:

http://www.brandonmartinez.com/2015/09/08/migration-notes-asp-net-5-mvc-6-beta-6-to-beta-7/

**Comment by ankitvijay** [comment]
Hi Zahid, "dnu restore" didn't help me. The DLL if referred as traditional Class Library and traditional Console works fine. But, not when you refer as Package.

**Comment by Zahid-Ashiq** [comment]
Hi ankit, yes i am also talking about dll if referred as package. if you are using package manager console then you will do just run the "dnu restore" command for all application layer for example if you are using bussiness location dll in database layer then you will do select the database layer in package manager console and then run the command and so on for others. i did implement this method and it was help for me :)

**Comment by Zahid-Ashiq** [comment]
Hi everyone, i did found very simple step if everyone have been tired after migration "dnvm". Step is just download the "webtoolextenstion" for beta 8 and then install. link is:

http://www.microsoft.com/en-us/download/details.aspx?id=49442

 After that, create new project and then import all older project file into the new. Because "webtoolextenstion" will do automatically fixed the issues like "Could not load file or assembly 'Microsoft.Dnx.Host.Clr'" and other class library issues. Mean Reason is that in Beta8 version has been many changes about IIS & EF7 etc. Futher, can read below links: 

http://jakzaprogramowac.pl/pytanie/5348,running-mvc6-beta8-app-on-iis-express
http://www.elanderson.net/2015/10/migration-from-asp-net-5-beta-7-to-beta-8/

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
