### ISSUE TITLE
Log correlation by request Id on Web applications

### ISSUE THREAD

**Issue by tugberkugurlu** [aspnet/Home#1015]
I am trying to see how I can correlate the logs based on a request id. It seems like this [`LoggerMessage.DefineScope`](https://github.com/aspnet/Logging/blob/718ac11d11dc8b3fd0a96c4d866d164f073ef23b/samples/SampleApp/LoggerExtensions.cs#L19-L22) is the proper way of doing it but I am not sure how it would play with for the rest of the application where I am not injecting an `ILogger` but injecting an `ILoggerFactory`.

Any thoughts or samples on this?

**Comment by tugberkugurlu** [comment]
Looking at the beta8 and the below is my poor attempt:

```csharp
        public void Configure(IApplicationBuilder app, ILoggerFactory loggerFactory)
		{
			loggerFactory.AddConsole(minLevel: LogLevel.Verbose);
			
			app.Use(async (ctx, next) => 
			{
				var logger = loggerFactory.CreateLogger("temp");
				using(logger.BeginScope(Guid.NewGuid().ToString()))
				{
					await next();	
				}
			});
			
			app.UseMvc();
		}
```

Which got me nowhere.

**Comment by Tratcher** [comment]
Hosting handles this now. See https://github.com/aspnet/Hosting/blob/dev/src/Microsoft.AspNet.Hosting/Internal/HostingEngine.cs#L97-L110
Note there are a few outstanding PRs to clean it up a little more.

**Comment by tugberkugurlu** [comment]
@Tratcher this is very good. One question: how can I get a hold of RequestId so that I can send it through response header? I can see this: https://github.com/aspnet/Mvc/blob/9342cb0ab78add8c527edcbc4c0988edc96f01e3/test/WebSites/RequestServicesWebSite/RequestIdMiddleware.cs but I didn't quite understand how [`RequestIdService`](https://github.com/aspnet/Mvc/blob/9342cb0ab78add8c527edcbc4c0988edc96f01e3/test/WebSites/RequestServicesWebSite/RequestIdService.cs) gets the `RequestId`.

**Comment by Tratcher** [comment]
RequestIdService is just something they made up for their test app. You can just get it from HttpContext.TraceIdentifier https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.AspNet.Http.Abstractions/HttpContext.cs#L77

**Comment by tugberkugurlu** [comment]
@Tratcher thanks! That's very useful, I tried to capture all this info here: http://www.tugberkugurlu.com/archive/asp-net-5-and-log-correlation-by-request-id

**Comment by rynowak** [comment]
That's a really good writeup! Thanks for sharing.
