### ISSUE TITLE
Next update on MyGet Feed?

### ISSUE THREAD

**Issue by jruckert** [aspnet/Home#1016]
Just wondering when the next build will be avaliable on http://myget.org/gallery/aspnetvnext, it has not been updated for a week or so.

**Comment by pranavkm** [comment]
cc @muratg - let's try and get a Coherence-Signed build out by tomorrow.

**Comment by muratg** [comment]
Agreed!

**Comment by jruckert** [comment]
Thank you!

**Comment by Kagamine** [comment]
aspnetcidev feed always missing some packages, such as Microsoft.Extensions.Logging.Console, others are v1.0.0-rc1-15727, but this just is v1.0.0-rc1-15724. This problem makes lots of things cannot be compiled, such as the mvc. https://ci.appveyor.com/project/aspnetci/mvc/branch/dev
/cc @muratg  @Eilon

**Comment by jruckert** [comment]
No luck on this? I'm keen to try out some fixes on EF7.

**Comment by pranavkm** [comment]
Sorry @jruckert, we've had a whole slew of changes and it's taking some time for us to sort through it. We're close to getting a rc1 bit, so getting a set of signed bits out is a top priority.

**Comment by pranavkm** [comment]
@jruckert we've updated the packages on aspnetvnext.
