### ISSUE TITLE
Can't publish asp.net 5 application after update to beta8 - the dependency … could not be resolved

### ISSUE THREAD

**Issue by juri33** [aspnet/Home#1017]
i've already asked the qjuestion on stackoverflow, but got no answers

http://stackoverflow.com/questions/33175017/cant-publish-asp-net-5-application-after-update-to-beta8-the-dependency-c?noredirect=1#comment54171739_33175017

---

I have updated a webApi asp.net5 application to beta8 and can't publish to the file system any more.

The build seems to work, i can debug and run the app, but if i try to publish i get errors like this...

C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\Web\Microsoft.DNX.Publishing.targets(156,5): Error : Build failed.
C:\Projekte\Workfolders\software\trunk\wrap\LibInternal.Database\project.json(11,20): Error NU1001: The dependency AntiXSS >= 4.2.1 could not be resolved.
C:\Projekte\Workfolders\software\trunk\wrap\LibInternal.Database\project.json(12,24): Error NU1001: The dependency Devshed.Csv >= 1.3.8 could not be resolved.
C:\Projekte\Workfolders\software\trunk\wrap\LibInternal.Database\project.json(13,27): Error NU1001: The dependency Devshed.Shared >= 1.3.7 could not be resolved.
C:\Projekte\Workfolders\software\trunk\wrap\LibInternal.Database\project.json(14,22): Error NU1001: The dependency DotNetZip >= 1.9.2 could not be resolved.
C:\Projekte\Workfolders\software\trunk\wrap\LibInternal.Database\project.json(15,29): Error NU1001: The dependency Iesi.Collections >= 3.2.0.4000 could not be resolved.
C:\Projekte\Workfolders\software\trunk\wrap\LibInternal.Database\project.json(16,25): Error NU1001: The dependency MongoDB.Bson >= 2.0.0 could not be resolved.
C:\Projekte\Workfolders\software\trunk\wrap\LibInternal.Database\project.json(17,27): Error NU1001: The dependency MongoDB.Driver >= 2.0.0 could not be resolved.
C:\Projekte\Workfolders\software\trunk\wrap\LibInternal.Database\project.json(18,32): Error NU1001: The dependency MongoDB.Driver.Core >= 2.0.0 could not be resolved.
C:\Projekte\Workfolders\software\trunk\wrap\LibInternal.Database\project.json(19,23): Error NU1001: The dependency NHibernate >= 3.3.4.4000 could not be resolved.
C:\Projekte\Workfolders\software\trunk\wrap\LibInternal.Database\project.json(20,17): Error NU1001: The dependency NLog >= 4.1.2 could not be resolved.
C:\Projekte\Workfolders\software\trunk\wrap\LibInternal.Database\project.json(21,24): Error NU1001: The dependency NLog.Config >= 4.1.2 could not be resolved.
C:\Projekte\Workfolders\software\trunk\wrap\LibInternal.Database\project.json(22,24): Error NU1001: The dependency NLog.Schema >= 4.0.1 could not be resolved.
C:\Projekte\Workfolders\software\trunk\wrap\LibInternal.Database\project.json(23,31): Error NU1001: The dependency System.Data.SQLite >= 1.0.90 could not be resolved.
C:\Projekte\Workfolders\software\trunk\wrap\LibInternal.Database\project.json(24,24): Error NU1001: The dependency LibInternal >= 1.0.0-\* could not be resolved.
C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\Web\Microsoft.DNX.Publishing.targets(156,5): Error : Build failed.

3>Publish failed due to build errors. Check the error list for more details.
========== Build: 2 succeeded, 0 failed, 1 up-to-date, 0 skipped ==========
========== Publish: 0 succeeded, 1 failed, 0 skipped ==========
Here is the Project.json file:

{
  "webroot": "wwwroot",
  "version": "1.0.0-*",

  "dependencies": {
    "Microsoft.AspNet.Cors": "6.0.0-beta8",
    "Microsoft.AspNet.Hosting": "1.0.0-beta8",
    "Microsoft.AspNet.IISPlatformHandler": "1.0.0-beta8",
    "Microsoft.AspNet.Mvc": "6.0.0-beta8",
    "Microsoft.AspNet.Server.Kestrel": "1.0.0-beta8",
    "Microsoft.AspNet.Server.WebListener": "1.0.0-beta8",
    "Microsoft.AspNet.StaticFiles": "1.0.0-beta8",
    "MongoDB.Driver": "2.0.1"
  },

  "commands": {
    "web": "Microsoft.AspNet.Server.Kestrel"
  },

  "frameworks": {
    "dnx451": {
      "dependencies": {
        "LibInternal.Database": "1.0.0-*"
      }
    }
  },

  "exclude": [
    "wwwroot",
    "node_modules",
    "bower_components"
  ],
  "publishExclude": [
    "node_modules",
    "bower_components",
    "**.xproj",
    "**.user",
    "**.vspscc"
  ]
}
LibInternal.Database is a .NET Framework 4.5 Project.

Here is packages.config from LibInternal.Database:

<packages>
  <package id="AntiXSS" version="4.2.1" targetFramework="net45" />
  <package id="Devshed.Csv" version="1.3.8" targetFramework="net45" />
  <package id="Devshed.Shared" version="1.3.7" targetFramework="net45" />
  <package id="DotNetZip" version="1.9.2" targetFramework="net45" />
  <package id="Iesi.Collections" version="3.2.0.4000" targetFramework="net45" />
  <package id="MongoDB.Bson" version="2.0.0" targetFramework="net45" />
  <package id="MongoDB.Driver" version="2.0.0" targetFramework="net45" />
  <package id="MongoDB.Driver.Core" version="2.0.0" targetFramework="net45" />
  <package id="NHibernate" version="3.3.4.4000" targetFramework="net45" />
  <package id="NLog" version="4.1.2" targetFramework="net45" />
  <package id="NLog.Config" version="4.1.2" targetFramework="net45" />
  <package id="NLog.Schema" version="4.0.1" targetFramework="net45" />
  <package id="System.Data.SQLite" version="1.0.90.0" targetFramework="net45" />
</packages>
Somebody any ideas?

**Comment by Kagamine** [comment]
Hi @juri33 , which target did you selected?

**Comment by juri33** [comment]
Hi @Kagamine,

did that, but it didnt help... :-(

  GET https://www.nuget.org/api/v2/
  OK https://www.nuget.org/api/v2/ 893ms
Restoring packages for C:\Projekte\Workfolders\software\trunk\ServicePlatform\WebAPI\project.json
  GET https://www.nuget.org/api/v2/FindPackagesById()?id='System.Data.SQLite'
  OK https://www.nuget.org/api/v2/FindPackagesById()?id='System.Data.SQLite' 633ms
Writing lock file C:\Projekte\Workfolders\software\trunk\ServicePlatform\WebAPI\project.lock.json
Restore complete, 2854ms elapsed

**Comment by Kagamine** [comment]
Where is your source code?

**Comment by juri33** [comment]
@Kagamine my source code is in C:\Projekte\Workfolders\software\trunk\ServicePlatform\WebAPI

powershell script: i have tried both, but it doesn't change anything. i got always same errors.

**Comment by Kagamine** [comment]
Can you publish an empty project？ maybe you have to visit jabbr.com and enter into aspnet vnext room to tell your problem to @davidfowl

**Comment by jessejohnston** [comment]
I have the same issue.  In my case, *dnx publish* with no parameters works just fine, but if I use *dnx publish --runtime active* (or *--runtime dnx-clr-win-x86.1.0.0-beta8*) many dependencies will fail to resolve.

**Comment by Kagamine** [comment]
@jessejohnston you can visit https://jabbr.net to call davidfowl

**Comment by juri33** [comment]
After a couple of hours of research and chat with @davidfowl i can say that is a bug.

This is a known issue by Microsoft team and hopefully it will be fixed in the next beta. I could fix this with this two steps:

In the solution folder should be a sub-folder named "wrap". In this folder are sub-folders with project.json files. In this file i had to change "net45" to "dnx451".

I had to change the name of the sub-folder in the bin folder:

\project\wrap{LibraryName}\bin\Release\net45 => \project\wrap{LibraryName}\bin\Release\dnx451

After that i could publish to filesystem.

**Comment by davidfowl** [comment]
The new cproj should fix this
