### ISSUE TITLE
visual studio 2015- beta8 issue: how can solve

### ISSUE THREAD

**Issue by NiyazShoukath** [aspnet/Home#1018]
![error](https://cloud.githubusercontent.com/assets/14939784/10664357/73a1ddf0-78cb-11e5-8753-c6965ae56d00.png)

**Comment by unt1tled** [comment]
try running dnx update

**Comment by NiyazShoukath** [comment]
@unt1tled  i  am already update dnx  to  beta 8 
vs 2015 : beta 8 
DNX  version : 1.0.0-beta8-15858

OS windows 10

stil same error?

**Comment by TheMadKow** [comment]
It may be silly, but have you restarted the VS ?

**Comment by NiyazShoukath** [comment]
yes , i have restart my laptop also

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
