### ISSUE TITLE
Better Outputs on errors.

### ISSUE THREAD

**Issue by TheMadKow** [aspnet/Home#1019]
Hi,
Don't know if issue already discussed here, to my understanding it hasn't.
1. Using dnx beta-8 x86 instead of x64, created general server errors (500, 502, etc) on running the IIS Express.  Never did it mentioned that it might be related to wrong run-time version. (httpHandler is x64).
   This issue occurred both on my current project and on creating new asp.net template.
2. Currently - Upgrading from beta7 to beta8, i'm using the old "options" parameter, 
   For the example, I've used : AppSettings.Options.SupportEmail instead of AppSettings.Value.SupportEmail. The error message is rather general and doesn't reflect the real line, but some inner exception.

'''
An error occurred during the compilation of a resource required to process this request. Please review the following specific error details and modify your source code appropriately.

Generated Code

'IOptions<AppSettings>' does not contain a definition for 'Options' and no extension method 'Options' accepting a first argument of type 'IOptions<AppSettings>' could be found (are you missing a using directive or an assembly reference?)
                EndContext();
            }
            , StartTagHelperWritingScope, EndTagHelperWritingScope);
            __Microsoft_AspNet_Mvc_Razor_TagHelpers_UrlResolutionTagHelper = CreateTagHelper<Microsoft.AspNet.Mvc.Razor.TagHelpers.UrlResolutionTagHelper>();
            __tagHelperExecutionContext.Add(__Microsoft_AspNet_Mvc_Razor_TagHelpers_UrlResolutionTagHelper);
            AddHtmlAttributeValues("href", __tagHelperExecutionContext, Tuple.Create(Tuple.Create("", 2646), Tuple.Create("mailto:", 2646), true), 
            Tuple.Create(Tuple.Create("", 2653), Tuple.Create<System.Object, System.Int32>(AppSettings.Options.SupportEmail, 2653), false));
            __tagHelperExecutionContext.Output = await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
            BeginContext(2637, 115, false);
            await WriteTagHelperAsync(__tagHelperExecutionContext);
            EndContext();
            __tagHelperExecutionContext = __tagHelperScopeManager.End();
            BeginContext(2752, 50, true);
'''

Thanks :)

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
