### ISSUE TITLE
 vNext on Windows Server IIS Not Works

### ISSUE THREAD

**Issue by Sm1le291** [aspnet/Home#1020]
Hi! I have problem when deploy vnext project to IIS on Server both Server 2008R2 or 2012.
I install all updates include new from beta 8 tools. Install DNX! I show runtimes in Profile folder and in ProgramData. I show vars in Environment tab. And VS installed too.  In log I have this message 
'"dnx.exe"' is not recognized as an internal or external command,
operable program or batch file.
I try in two machine(2008r2 and 2012). In Windows 7 and 8.1 works fine.
p.s. When I copy content of .dnx/runtime all works!!!

**Comment by GuardRex** [comment]
@Sm1le291 Compare what you've done to my notes and see if you hit all of the major points: https://github.com/aspnet/Hosting/issues/364#issuecomment-148567294

**Comment by Sm1le291** [comment]
Wow!!! GuardRex, I read quickly and I think you thread helps me. I try tomorrow and write result.

**Comment by Sm1le291** [comment]
Thanks)

**Comment by GuardRex** [comment]
@Sm1le291 Sure thing. Post back if you get stuck, and MS and community people will try to help.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
