### ISSUE TITLE
Search asp.net-5 information.

### ISSUE THREAD

**Issue by Anderman** [aspnet/Home#1023]
I create a CSE for searching information about ASP.NET-5. 
Maybe you can add such link in de home repository or somewhere else for people to find all relevant asp.net-5 information. 

I think this will lead to less questions and less duplicate issues.

https://cse.google.com/cse/publicurl?cx=011164928887811869310:ceyqgj-kmyq

I used this setup
![image](https://cloud.githubusercontent.com/assets/1858745/10688404/66e88f74-7974-11e5-9a7c-4001f3417054.png)

![image](https://cloud.githubusercontent.com/assets/1858745/10688485/d49d0964-7974-11e5-842b-0db6867efba5.png)

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
