### ISSUE TITLE
Setup documenation like laracast

### ISSUE THREAD

**Issue by Anderman** [aspnet/Home#1024]
There is a lot of documentation about asp and c# on channel 9 but not like laracast. This is an excelent source if you use php and larrafile. 

I think is would be great to have something like this for c#, asp.net-5 mvc-6 and EF7

The current video's on channel 9 or microsoftvirtualacademy are too long. Scott Handselmann has some nice video's about a single subject and a lot of stackoverflow question could/should have a video explaning an solution

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
