### ISSUE TITLE
Tag Helpers and label asp-for not showing the label

### ISSUE THREAD

**Issue by rhires** [aspnet/Home#1025]
Hello...so I have this code, straight from ef.readthedocs.org, in the [aspnet5 section](https://github.com/aspnet/EntityFramework.Docs/blob/master/docs/getting-started/aspnet5/sample/src/EFGetStarted.AspNet5/Views/Blogs/Create.cshtml)  (unzipped the example, navigated down to the proper level, ran dnu restore, then dnx web)...and for some reason or other, it doesn't show the label in the rendered view for the "create" section. I know that the inputs are correct, it's just the labels that are invisible. The question is: do I have to update the POCOs in the model to have display attributes to be able to see the label? Actually, to answer my question, no, updating the POCO with the [Display] attribute didn't change anything. 

I'm running beta8, on Yosemite. Unfortunately, there isn't that much regarding tag helpers, and I haven't seen this one anywhere.

**Comment by dougbu** [comment]
@rhires please upload the screenshot mentioned in your original description? Need either the generated HTML or that screenshot to understand what you're seeing.

**Comment by rhires** [comment]
Hmmm..sending this from email, since when I attempted to include a screen shot in .png github wouldn’t include it.


And the html -
<h2>New Blog</h2>

<form method="post <>" class="form-horizontal <>" role="form <>" action="/Blogs/Create <view-source:http://localhost:5000/Blogs/Create>">
    <div class="form-horizontal <>">
        <div class="text-danger validation-summary-valid <>" data-valmsg-summary="true <>" />
        <div class="form-group <>">
            <label class="col-md-2 control-label <>" for="Url <>" />
            <div class="col-md-10 <>">
                <input class="form-control <>" type="text <>" id="Url <>" name="Url <>" value=" <>" />
                <span class="text-danger field-validation-valid <>" data-valmsg-for="Url <>" data-valmsg-replace="true <>" />
            </div>
        </div>
        <div class="form-group <>">
            <div class="col-md-offset-2 col-md-10 <>">
                <input type="submit <>" value="Create <>" class="btn btn-default <>" />
            </div>
        </div>
    </div>
<input name="__RequestVerificationToken <>" type="hidden <>" value="CfDJ8OfM4W1Gc_FFiXyZS_4N7LfyKtHILcT9SwLD-oyakioK_4Zaw7tGlyhrlM08-UyTP7fkC_RhcXoWzFGjTMEM03ffOgV6IimveM54txWoklMTpmKseBSbwjHDxHwKVCdMD_-iNY_MJ3t3zdxo37WCiPQ <>" /></form>

**Comment by dougbu** [comment]
This is a defect in the `Create.cshtml` file. I'll move the issue to the [aspnet/EntityFramework.Docs](https://github.com/aspnet/EntityFramework.Docs/issues) repo. Quick fix is to add the missing `</label>` end tag -- that element should not be self-closing.

###### details
The MVC tag helpers do not overrule the `.cshtml` author. If the file contains `<label/>` or `<input>something</input>`, so will the generated HTML. This is true whether or not an MVC tag helper targets the element.

In this case the `LabelTagHelper` updated the `<label>`'s attributes and content. The new content is not visible because the file uses a self-closing tag.

**Comment by dougbu** [comment]
This issue was moved to aspnet/EntityFramework.Docs#49
