### ISSUE TITLE
ASP.NET 5 on IIS 7.5

### ISSUE THREAD

**Issue by saluce65** [aspnet/Home#1026]
I understand that Beta8 changed over to use the HttpPlatformHandler module when running under IIS.  Unfortunately, it appears that the module is only supported on IIS 8+, so officially ASP.NET 5 only works on those versions of IIS.  I've tested locally on a dev machine using IIS 7.5 and the module appears to work, but I haven't done any extensive testing.  Will the module be officially supported on IIS 7.5 or lower, or how would be use ASP.NET 5 on IIS machines that are not supported by the HttpPlatformHandler module?

**Comment by GuardRex** [comment]
@saluce65 The min supported version is Windows 2008 R2, which is IIS 7.5. https://github.com/aspnet/Hosting/issues/364#issuecomment-150293300

**Comment by ddotlic** [comment]
I can confirm that it is working fine on IIS 7.5, but you need to have platform handler 1.2 installed (see @GuardRex comments for links).
