### ISSUE TITLE
"dnu restore -s" with multiple sources

### ISSUE THREAD

**Issue by joshuaaa** [aspnet/Home#1027]
The only example I could find online was from beta 4, and the example apparently doesn't work with beta 7/8.

Basically I need to call dnu restore with 2 source (the generic source and a company source).

I have tried both of these but they don't work:
dnu restore -s https://mycompanysource -s https://www.nuget.org/api/v2
dnu restore -s https://mycompanysource -f https://www.nuget.org/api/v2

The documentation says that -s supports a list of sources, but I can't find an example.

What am I doing wrong?

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
