### ISSUE TITLE
dnu restore fails with System.UnauthorizedAccessException: Access to the path 'C:\Windows\system32\LogFiles\WMI\RtBackup' is denied

### ISSUE THREAD

**Issue by steve-warwick** [aspnet/Home#1028]
With beta 8 when I run "dnu restore" I get the following:

C:\Windows\system32>dnu restore
Microsoft .NET Development Utility Clr-x86-1.0.0-beta8-15858

----------
System.UnauthorizedAccessException: Access to the path 'C:\Windows\system32\LogFiles\WMI\RtBackup' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.AddSearchableDirsToStack(SearchData localSearchData)
   at System.IO.FileSystemEnumerableIterator`1.MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at Microsoft.Dnx.Tooling.RestoreCommand.<Execute>d__68.MoveNext()
----------
Restore failed
Access to the path 'C:\Windows\system32\LogFiles\WMI\RtBackup' is denied.

C:\Windows\system32>dnvm update-self
Updating dnvm from https://raw.githubusercontent.com/aspnet/Home/dev/dnvm.ps1

**Comment by davidfowl** [comment]
Why would you restore the windows directory?

**Comment by steve-warwick** [comment]
My apologies. I'm new to this framework. I'm still figuring out how this whole process works. I'm running into any issue when a WebApp deployed as service fabric service keeps restarting with an error "The program '[8596] dnx.exe' has exited with code 1 (0x1)." I did some searches one result recommended running this command. I'll enter this as a separate issue. Sorry for wasting your time.
