### ISSUE TITLE
Exclude files from compilation depending on environment/configuration

### ISSUE THREAD

**Issue by wmekal** [aspnet/Home#1029]
Hi, 

I like to organize my projects using per-feature approach, so instead of having structure like:

/Controllers
/Views
/...

I have:

/Features
  /Customers
    /Controller.cs
    /View.cshtml
  /Orders
  /...

I also like to keep tests (unit/functional) together with the features, so next to Controller.cs there might be ControllerTests.cs.
Thanks to that, I have all code and tests related to given functionality together, which for me is really nice.

What I want to achieve now, is to exclude tests from the production build.
All project.json's exclude properties seems to describe general exclusion rules, but I need to exclude files depending on the environment for which I'm making the build.

Is there any way to do it, currently?

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
