### ISSUE TITLE
beta8 dnu/dnx produce output on ubuntu 15.04, but not 15.10

### ISSUE THREAD

**Issue by colemickens** [aspnet/Home#1030]
This Dockerfile, combined with an ASP.NET project will allow you to use `dnu` and `dnx` and see output as you might expect:
https://github.com/colemickens/polykube/blob/c30d0c36bfeb22367a02ab3ce9908efd1c76c28c/dotnet/Dockerfile.dotnet.dev

However, if you just change the base image to 15.10 and then `libicu52` to `libicu55`, you will no longer get any output from `dnu` or `dnx`.

**Comment by Codenator81** [comment]
Have the same issue when installed Ubuntu 15.10 on machine

**Comment by colemickens** [comment]
Same behavior with 1.0.0-rc1-16048 coreclr on Arch. No output.

**Comment by Codenator81** [comment]
@colemickens 
When I downgrade to Ubuntu 14.04 no problem. For now recommended work on Ubuntu 14.04.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
