### ISSUE TITLE
Beta-8 web tools cause visual studio 2015 restarts when edit package.json

### ISSUE THREAD

**Issue by singlewind** [aspnet/Home#1031]
As described in the title, every time when I edit the package.json to add a new package. The visual studio crashes and restarts itself. The node package has been installed correctly after restarts. Don't know why it crashes.

Also, the ASP.NET template doesn't allow add new resource file. The new items allowed to create in visual studio is limited to DNX.

**Comment by Eilon** [comment]
@singlewind sorry you're running into those issues! Can you post this in https://github.com/aspnet/Tooling/issues/ ? That's where the tooling experts hang out.

**Comment by YuePan** [comment]
I met the similar issue. I'm using VS 2015 enterprise and it crashes when restore packages. It seems some node package caused it.After that, I can not restart VS 2015 and also can't delete node_modules folder.

**Comment by Eilon** [comment]
@barrytang

**Comment by barrytang** [comment]
I know we fixed some issues in the node tooling scenarios. @jodavis?

**Comment by singlewind** [comment]
Don't think it is applicable any more. So, close it.
