### ISSUE TITLE
strange issue with routing

### ISSUE THREAD

**Issue by lucamorelli** [aspnet/Home#1032]
I'm trying to write an aurelia app with asp.net 5 (beta 8) web api controller as backend I found this thing:
I wrote this action in the controller, skipping the route attribute because I didn't know if was mandatory.

```
        [HttpGet]
        public IEnumerable<TipoAttivita> TipiAttivita() {
            var tipiAttivita = db.TipiAttivita
                .OrderBy(cli => cli.Descrizione)
                .ToList();

            return tipiAttivita;

        }
```

Calling it from Aurealia, the method is not invoked, but I receive and HttpResult 200 and the string "value" as result.
Adding the attribute **[Route("TipiAttivita")]** solved the problem.

Is this normal?

**Comment by rynowak** [comment]
> skipping the route attribute because I didn't know if was mandatory

There are two schemes for routing: conventional routing, and attribute routing.

Conventional routing uses route information defined in the global route table, inside your call to `.AddMvc(...)`.

Attribute routing is defined for controllers and actions using `[Route(...)]` or `[HttpGet(<some route>)]`. Conventional routes do not apply to actions and controllers with attribute routes.

You can really set this up however you want, there's no requirement that you do one thing or another, though I'd strongly recommend using attribute routing for APIs.

**Comment by lucamorelli** [comment]
The problem is that if I configure incorrectly the route, I expect a not found error, not a OK 200 with a string result that is unrelated to my request

**Comment by rynowak** [comment]
> The problem is that if I configure incorrectly the route, I expect a not found error, not a OK 200 with a string result that is unrelated to my request

If there's a 200, then I'd expect something in your app is serving it. If you have a public repo available, I can take a look.

**Comment by lucamorelli** [comment]
I think I finally understood what's happened. the scaffolded controller by default contains 
```        
[HttpGet("{id}")]
public string Get(int id)
{
  return "value";
}
```
and this is the action is called when I don't add the route. Try to convert to an int and call it passing 0.
Adding a constraint to the param {id:int} returns 404.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
