### ISSUE TITLE
Nuget cannot find newer dependency

### ISSUE THREAD

**Issue by gisek** [aspnet/Home#1033]
I'm not sure if this is the right place to report this bug, but look what I found.

I've just created a new project in ASP 5 MVC 6 beta8 and a compatible class library for tests. The problem occurs in this new "Web Class Library" project that I intended to use for tests. I also created a normal Class Library, installed the dependencies above with and gave it a try. Normal Class Library project built fine.

Here you've got a sample (ClassLibrary1 build fails, ClassLibrary2 build succeeds)
https://github.com/gisek/NugetBug

And here is a SO question I asked at first.
http://stackoverflow.com/questions/33324660/nuget-cannot-find-newer-dependency

**Comment by asik** [comment]
I encountered the exact same issue. Any thoughts about this?

**Comment by gisek** [comment]
http://stackoverflow.com/a/34579963/672018

This is the temporary solution. It may help in fixing the bug.

**Comment by davidpeden3** [comment]
This problem is painful. Was hard to find and even worse to fix (with the workaround above). Any update on this?

**Comment by davidpeden3** [comment]
Not sure if this is a problem with `AutoFixture.AutoMoq` or `dnu restore/build`. Cross referencing the issues:

https://github.com/AutoFixture/AutoFixture/issues/541

**Comment by davidpeden3** [comment]
Pretty sure this issue can be closed. I believe the problem was in the `.nuspec` file of AutoFixture. The learning here is that dependencies in `project.json` are case-sensitive.

**Comment by MaximRouiller** [comment]
@davidpeden3 If it's case-sensitive... it should tell you that the package cannot be found. 

If it's not case-sensitive, it should take the package anyway. 

My thought is that since the Gallery isn't accepting package with the same name (but different case), then it's case insensitive and should be handled properly. It should install the package.

/cc @Eilon

**Comment by Eilon** [comment]
The package names are effectively case sensitive, but there are parts of NuGet that sometimes relax some of the rules.

@yishaigalatzer would know better the current behavior.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
