### ISSUE TITLE
missing 'Microsoft.AspNet.Server.WebListener' dependency on project.json file of HelloWeb of beta8

### ISSUE THREAD

**Issue by zhengchun** [aspnet/Home#1035]
[missing 'Microsoft.AspNet.Server.WebListener' in the `dependencies` elements in dev branch](https://github.com/aspnet/Home/blob/dev/samples/1.0.0-beta8/HelloWeb/project.json#L12)

```js
"dependencies": {
        ......
        "Microsoft.AspNet.Server.WebListener":"1.0.0-beta8"
    }
```

**Comment by Tratcher** [comment]
@glennc WebListener is not listed as a dependency, but the command is still there.

**Comment by Kagamine** [comment]
@Tratcher  I opened a pull request to fix it and made the latest up to date.
@zhengchun  在https://github.com/aspnet/Home/issues/1056 修复了你提出的这个问题

**Comment by Kagamine** [comment]
@Tratcher Is this should be 2-Working? #1056
