### ISSUE TITLE
FromServicesAttribute not working for viewcomponent:

### ISSUE THREAD

**Issue by kennywangjin** [aspnet/Home#1036]
for DI, constructor injection is always working. but FromServicesAttribute is working only for Controller, not for ViewComponent.
when I use this attribute to get a injected service in ViewComponent, it is null when I debug it. Is that a bug or some design? beta-8

**Comment by rynowak** [comment]
This is by design. `[FromServices]` is a model binding feature, and there's no model binding in view components

**Comment by kennywangjin** [comment]
Got it. Thanks.
