### ISSUE TITLE
What happen for aspnetvnext feed on Myget?1

### ISSUE THREAD

**Issue by mikeandersun** [aspnet/Home#1037]
The feed not update from 2 week ago. Is it changed?

**Comment by Tratcher** [comment]
There have been a lot of breaks and build issues recently... It should be updated any day now.

**Comment by rbarbe** [comment]
aspnetvnext feed has been updated an hour ago but some packages are missing like : Microsoft.Extensions.Logging or System.Diagnostics.DiagnosticSource

**Comment by pranavkm** [comment]
This should get fixed soon.

**Comment by pranavkm** [comment]
aspnetvnext has been updated. We're working out a plan to ensure a repeat of what we had these past few weeks doesn't happen.
