### ISSUE TITLE
css cant find assets that are listed at wwwroot

### ISSUE THREAD

**Issue by miker1423** [aspnet/Home#1038]
I have a little project where I have a cshtml that needs a css and the css need two svg, the css is saved at wwwroot/css/stylesheet.css, the svg are at wwwroot/Images/myimage.svg.
In my css I have the property background as this, background: url(../Images/myimage.svg), and in my cshtml I import the css as <link rel="stylesheet" href="~/css/stylesheet.css" />. when I run the site, it returns and error saying that it wasn't able to find the resources. Any idea of what could be happening??

**Comment by GuardRex** [comment]
You have ...
```
"Microsoft.AspNet.StaticFiles": "1.0.0-beta8"
```
... and ...
```
app.UseStaticFiles();
```
... correct?

**Comment by miker1423** [comment]
haha forgot about that... still new with asp.net 5, it's hard to remember everything haha thank you so much!
