### ISSUE TITLE
Request.Scheme is wrong when hosted in Azure (Beta8)

### ISSUE THREAD

**Issue by halkor** [aspnet/Home#1039]
Request.Scheme returns "http" even if you use https in Azure Web Apps. This breaks Microsoft Account authentication, and probably a lot of other things.

**Comment by Tratcher** [comment]
https://github.com/aspnet/Hosting/issues/364
Because we're now using the IIS native module HttpPlatformHandler, you need the `app.UseIISPlatformHandler()` middleware from `Microsoft.AspNet.IISPlatformHandler` in your app. It will update the scheme from forwarded headers.

**Comment by halkor** [comment]
Strange thing. I just redeployed the exact same code as I used previously, and now it works.
