### ISSUE TITLE
Relying on ILoggerFactory or ILogger

### ISSUE THREAD

**Issue by tugberkugurlu** [aspnet/Home#1042]
AFAIK, it's most suitable to rely on `ILoggerFactory` (get it injected in) rather than directly relying on `ILogger`. I can also see this in a few samples:
- [`RouterMiddleware`](https://github.com/aspnet/Routing/blob/a5727dc932aa2a147fa908feeea861502f0e7e44/src/Microsoft.AspNet.Routing/RouterMiddleware.cs#L22)
- [`AuthenticationMiddleware`](https://github.com/aspnet/Security/blob/409b50269a9d85618a31f84a3ffc2868abb3eeea/src/Microsoft.AspNet.Authentication/AuthenticationMiddleware.cs#L20)

However, [Identity components directly relies on `ILogger`](https://github.com/aspnet/Identity/pull/348) (e.g. [`RoleManager`](https://github.com/aspnet/Identity/blob/4ce3efd28fb33bc40f63bc150ff12182543b3a07/src/Microsoft.AspNet.Identity/RoleManager.cs#L40)).

What is the recommended approach here and are there any specific reasons on why Identity library chose a different approach than the rest of the stack?

**Comment by rynowak** [comment]
Injecting an `ILogger<T>` is a shorthand for injecting `ILoggerFactory` and calling `Create<T>`. 

Use whatever makes you happy :+1: 


Personally, there are some cases where I've found that injecting the `ILoggerFactory` is simpler because our test logger stubs don't have a definition for `ILogger<T>` - https://github.com/aspnet/Logging/tree/dev/src/Microsoft.Extensions.Logging.Testing . 

On the other hand if you're using a library like Moq, it would be easier to use `ILogger<T>` which wouldn't require you to mock the 'ILoggerFactory.Create`.

Keep in mind, a lot of code was also written before `ILogger<T>` was added and could be simplified.

**Comment by ashmind** [comment]
I might be missing previous context, but why does this have to be aa generic ILogger?

In the world pre-AspNet5 I just had an Autofac module that identified logger type by whatever type requested it.

Having to explicitly specify logger type feels unnecessary.

**Comment by rynowak** [comment]
> In the world pre-AspNet5 I just had an Autofac module that identified logger type by whatever type requested it. Having to explicitly specify logger type feels unnecessary.

There's no reason why you can't have the same setup. Our infrastructure has to work with all DI containers and configurations, so we can't rely on that.

**Comment by tugberkugurlu** [comment]
To be honest, generic `ILogger` seems prety weird to me, too. I assume the only purpose of the generic parameter is to figure out the logger name.

**Comment by tugberkugurlu** [comment]
ILoggerFactory adds some boilerplate code to be written over and over but it can be handled by an abstract class which gets an ILoggerFactory and sets a logger for the implementation class to use.

**Comment by ashmind** [comment]
@rynowak 
> Our infrastructure has to work with all DI containers and configurations, so we can't rely on that.

I do see your point, but let me have another take for a moment.

Your infrastructure already relies on container to support open generics (that's how `ILogger<>` is registered). It also requires container to [support delegate factories](https://github.com/aspnet/DependencyInjection/blob/dev/src/Microsoft.Extensions.DependencyInjection.Abstractions/ServiceDescriptor.cs#L69).

What if the factory received some context (e.g. `ServiceContext { Type RequestingType { get; } }`)? That would be enough to support the logger scenario and might unlock new similar scenarios -- basically resolution based on requestor.

**Comment by rynowak** [comment]
> That would be enough to support the logger scenario and might unlock new similar scenarios -- basically resolution based on requestor.

That would only work if there's a suitable piece of code providing the `RequestingType`. In the general case there is not.

Also, there's nothing canonical about using types to relate to logger categories. It's a convention we use across the framework because our names should be hierarchical. 

Feel free to ignore `Logger<T>` and implement logging in your app in a manner of your choosing.

**Comment by mkArtak** [comment]
Hi.

I'm looking for ways to extend the ILogger capabilities. Here is the full scenario I'm seeking support for.

I have an ILogger implementation for AppInsights TelemetryClient. The ILogger.Log<TState> method implementation calls into the TrackTrace method of the underlying TelemetryClient instance. **Beside that, I also want to have a mechanism to expose the telemetryClient.LogMetric API**.

My proposal is to change the ILoggerFactory.CreateLogger(string categoryName) method to be generic, maybe like the below one:
    **`T CreateLogger<T>(string categoryName) where T : ILogger;`**

I understand this would require some internal changes in the LoggerFactory class, but this would enable custom interface based telemetry support. In other words, I would be able to define a new interface:

```
    public interface IExtendedLogger : ILogger
    {
        void LogMetric(string metricName, double value);
    }
```
and get an instance for that still using the ILoggerFactory as usual.
The TelemetryClient wrapping logger would then implement this interface instead, and would allow me to properly expose both LogMetric and Log methods.

So the classes using ILogger, which need to also be able to use the new API will need to be updated to use IExtendedLogger instead. But with that only change (on the consumer/client side) my existing logging code would just work as is, plus I would be able to also use the new LogMetric API wherever I need to.

Anyway, bringing this up for discussion - would be glad to hear your feedback on this.

**Comment by mkArtak** [comment]
Hi.

I'm looking for ways to extend the ILogger capabilities. Here is the full scenario I'm seeking support for.

I have an ILogger implementation for AppInsights TelemetryClient. The ILogger.Log<TState> method implementation calls into the TrackTrace method of the underlying TelemetryClient instance. **Beside that, I also want to have a mechanism to expose the telemetryClient.LogMetric API**.

My proposal is to change the ILoggerFactory.CreateLogger(string categoryName) method to be generic, maybe like the below one:
    **`T CreateLogger<T>(string categoryName) where T : ILogger;`**

I understand this would require some internal changes in the LoggerFactory class, but this would enable custom interface based telemetry support. In other words, I would be able to define a new interface:

```
    public interface IExtendedLogger : ILogger
    {
        void LogMetric(string metricName, double value);
    }
```
and get an instance for that still using the ILoggerFactory as usual.
The TelemetryClient wrapping logger would then implement this interface instead, and would allow me to properly expose both LogMetric and Log methods.

So the classes using ILogger, which need to also be able to use the new API will need to be updated to use IExtendedLogger instead. But with that only change (on the consumer/client side) my existing logging code would just work as is, plus I would be able to also use the new LogMetric API wherever I need to.

Anyway, bringing this up for discussion - would be glad to hear your feedback on this.

**Comment by Eilon** [comment]
Closing because no further action is planned for this issue.
