### ISSUE TITLE
RC1 Discussion: New versioning for major releases

### ISSUE THREAD

**Issue by dougbu** [aspnet/Home#1046]
Starting with RC1, our pre-release packages will have versions such as `1.0.0-rc1-final`, `2.0.0-rc2-final`, ... This should avoid some issues for those who have been following our volatile feeds.

The RTM release packages will have versions such as `2.0.0`, `3.0.0`, ...

**Comment by NeelBhatt** [comment]
fair enough :+1:

**Comment by paulalves** [comment]
great! =)

**Comment by alexmg** [comment]
Awesome! :thumbsup:

**Comment by jasonwilliams200OK** [comment]
Compliance with semver! Way to go. :+1: 
BTW, you guys can safely say that "Starting with MVC6, we are [semver](http://semver.org/)-compliant". The community endorse it even more!

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
