### ISSUE TITLE
No intellisense on taghelpers with "src".

### ISSUE THREAD

**Issue by Bartmax** [aspnet/Home#1049]
Not sure if this should be on tooling, mvc or taghelpers, hence home repo :)

when using script taghelper like this: 

```
<script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.1.4.min.js"
            asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
            asp-fallback-test="window.jQuery">
</script>
```

you get intellisense for the src part, but not for the asp-fallback-src. I understand that there's no way visual studio understands that variable is a file path. maybe visual studio should have an exception rule for tags that have src in it's name ?

**Comment by NTaylorMullen** [comment]
When you say no IntelliSense for `asp-fallback-src` I assume you mean for the URL value; as in you don't get this drop down for `asp-fallback-src`:
![image](https://cloud.githubusercontent.com/assets/2008729/10852633/f68f68ee-7eee-11e5-8a99-2f0f0eb393fb.png)

In the future it'd definitely start out as a tooling issue (then a runtime issue would spawn from it etc.).We do have a similar issue for the runtime side of things that was backlogged a while back [here](https://github.com/aspnet/Razor/issues/429). If you feel strongly about the feature feel free to voice your concerns there. For the interim i'm going to close this as a duplicate.

**Comment by Bartmax** [comment]
:+1: not feeling strongly :)
