### ISSUE TITLE
kvm install 0.1-... Has CHMOD Error on Ubuntu 14.04

### ISSUE THREAD

**Issue by jeffa00** [aspnet/Home#105]
Installing on Ubuntu 14.04.

Built mono 3.6.1.

curl-ed kvm.

Ran kvm install 0.1-alpha-build-0446

Result:

kvm install 0.1-alpha-build-0446
Downloading KRE-mono45-x86.0.1-alpha-build-0446 from https://www.myget.org/F/aspnetvnext/api/v2
Installing to /home/jeffa/.kre/packages/KRE-mono45-x86.0.1-alpha-build-0446
chmod: missing operand after ‘775’
Try 'chmod --help' for more information.
Adding /home/jeffa/.kre/packages/KRE-mono45-x86.0.1-alpha-build-0446/bin to process PATH

Key bit: chmod: missing operand after ‘775’

Not sure what it was trying to chmod, but I'm guessing the bin directory contents since they are all rw-rw-r--.

**Comment by danroth27** [comment]
@jeffa00 Let us know if you are still seeing issues with this. Our latest instructions on how to run on Linux can be found at https://github.com/aspnet/home. We expect to invest more in the Linux experience as cross-platform support for .NET Core becomes available.
