### ISSUE TITLE
Commandline `dnu restore` and Visual Studio package restore interfere with each other

### ISSUE THREAD

**Issue by aggieben** [aspnet/Home#1050]
Since upgrading to the beta8 runtimes, I've noticed that if I have Visual Studio open and run `dnu restore` in a console, I often (always?) encounter an error like this (with DNX_TRACE on...) when executing `dnx`:

```
λ with-env -vars DNX_TRACE=1 { dnx kestrel }
The default servicing root does not exist.
Loaded module: dnx.clr.dll
Found export: CallApplicationMain
Information: [DomainManager] Using Desktop CLR v4.5.1
Information: [Bootstrapper] Runtime Framework: DNX,Version=v4.5.1
Warning: [ApplicationHostContext] Lock File Target is Runtime-agnostic! This is generally not good.
Information: [ApplicationHostContext] Using Lock File Target: DNX,Version=v4.5.1/
Error: . Please run "dnu restore" to generate a new lock file.
```

What I think it happening is that Visual Studio detects that the lockfile has changed and proceeds to do its own restore - which is somehow incompatible with a manual invocation of `dnx`.  

The simple workaround is to close Visual Studio - but hopefully it's apparent how annoying this is...

**Comment by davidfowl** [comment]
Looks like your project and command line are using different ask versions.

**Comment by aggieben** [comment]
Ah - yeah, I checked the restore output in visual studio and you're right, it's using beta7.  But why?  DNVM says beta8 is the default, and hasn't that always been what Visual Studio uses if a specific runtime isn't configured?


Here's the output of `dnvm list`:

```
λ dnvm list

Active Version     Runtime Architecture OperatingSystem Alias
------ -------     ------- ------------ --------------- -----
       1.0.0-beta7 clr     x64          win
       1.0.0-beta7 clr     x86          win
       1.0.0-beta7 coreclr x64          win
       1.0.0-beta7 coreclr x86          win
       1.0.0-beta7 mono    x86/x64      linux/osx       mono-beta7
       1.0.0-beta8 clr     x64          win
  *    1.0.0-beta8 clr     x86          win             default
       1.0.0-beta8 coreclr x64          win
       1.0.0-beta8 coreclr x86          win
       1.0.0-beta8 mono    x86/x64      linux/osx
```

Here are my project settings:

![image](https://cloud.githubusercontent.com/assets/1321/10851234/efafae86-7ef7-11e5-9804-5bd93f03f125.png)

It looks to me like VS should be picking up `default`.

**Comment by davidfowl** [comment]
Global.json

**Comment by aggieben** [comment]
Yep, that was it.  Would it maybe be worthwhile to have dnu/dnx emit a warning if the currently-invoked version doesn't match what's in `global.json`?  Anyway, thanks for your help.  Closing this.
