### ISSUE TITLE
dnu restore does not work on Ubuntu 15.10

### ISSUE THREAD

**Issue by saranshkataria** [aspnet/Home#1051]
dnu is not working correctly on Ubuntu 15.10. I installed DNVM, DNX prerequisites, .net core clr and 
then cloned the repository at https://github.com/aspnet/Home. On doing a dnu restore, it doesn't work on Ubuntu 15.10 whereas trying it on Ubuntu 14.04 works

**Comment by NullVoxPopuli** [comment]
I have this issue too :-\

happens with both runtimes
```
$ dnvm list

Active Version              Runtime Architecture OperatingSystem Alias
------ -------              ------- ------------ --------------- -----
       1.0.0-rc1-final      coreclr x64          linux           
  *    1.0.0-rc1-final      mono                 linux/osx       default
```

**Comment by BrennanConroy** [comment]
https://github.com/aspnet/dnx/blob/ed98b4c687cf0785650d59e7b7a65a371bc5332f/src/Microsoft.Dnx.Tooling/Restore/ImplicitPackagesWalkProvider.cs#L96

**Comment by NullVoxPopuli** [comment]
well, until they make it compatible, here is how you downgrade
```
wget http://security.ubuntu.com/ubuntu/pool/main/i/icu/libicu52_52.1-8ubuntu0.2_amd64.deb
sudo dpkg -i libicu52_52.1-8ubuntu0.2_amd64.deb
```

**Comment by THuffam** [comment]
I have the same problem on Ubuntu 15.10.   Just tried a fresh install of all .Net components based on various instructions on Microsoft/ASP.Net sites.  
dnu restore runs, but with not output at the terminal at all. 
I have tried the most simple app based on this article: https://docs.asp.net/en/latest/dnx/console.html and in VS Code - most of the code is underlined with errors -eg the "using System;" line says: 
The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?) [dnxcore50]
Unnecessary using directive. [dnxcore50]
System

I was evaluating .Net on ubuntu as a legit platform for web development.  Obviously a long way from ready.  Shame.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
