### ISSUE TITLE
Runing in DNX Web or Kestrel runtime errors are sometimes not displayed

### ISSUE THREAD

**Issue by TJSoftware** [aspnet/Home#1053]
### Summary
My runtime errors are not displayed, instead I only see a blank page.

### Functional Impact
This makes debugging a great deal more difficult.

### Reproducing the issue and what I expect
I have been following [this .Net 5 video](https://channel9.msdn.com/Events/dotnetConf/2015/ASPNET-5-Deep-Dive) most recently to learn about the new changes to .Net.  One of the issues that I am facing is that when I make a mistake with my code I do not receive a runtime error.  Here is my most recent example, [you can also download my code](https://github.com/TJSoftware/DotNet5Testing).

//Below I have a {1} that should be {0}.  During this test I was attempting to retrieve data from an Interface.  The error should be 'Index out of range' or something to that effect, however my page was blank
return string.Format("Hello DotNet5Testing MVC Controller.  Class2 txt: {1}",  textFromMyLib2);

### Another example
I was able to get all of my code working even without errors.  Moving back from a working site, I tested removing the registration of the service.  In the video Louis and Damian demonstrated how if you do not have your service registered you will receive a very nice error message.  They received "Unable to resolve service for type 'MyLibrary.MySiteCultureService while attempting ..."  If I comment out the service registration I receive a blank page.

        public void ConfigureServices(IServiceCollection services)
        {
            services.AddMvc();

            //This is required to use the Class Library.
            //This is how to register the service(library)
            //services.AddSingleton<Class1>();

            //services.AddSingleton<IClass2, Class2>();
        }

When I do see an error message it tends to be a 500 error without any other information and I am not sure where to get the logs for that.  Right now it is not too big of a deal as I am just following a tutorial, however, in a real world example I would need to be able to get to run time errors.  Is there something that I can change to bubble up a more descriptive error at runtime?

### Tech details
I am testing in primarily dnx web, but sometimes I run dnx kestrel when I run into issues just to see if I have different results, so far they seem to produce the same results.  I am currently not using IIS because I am on runtime 1.0.0-beta8, it is currently waiting to be fixed [per this](https://github.com/aspnet/Announcements/issues/70).

I am using DNVM 1.0.0-rc2-15538
I have used the runtimes
1.0.0-beta8 clr (both x64, x86) win
I am on a win 10 machine using vs 2015 enterprise.

**Comment by rambocoder** [comment]
You need to add ```"Microsoft.AspNet.Diagnostics": "1.0.0-beta8"``` to ```dependencies``` of your project.json and before this line https://github.com/TJSoftware/DotNet5Testing/blob/master/src/DotNet5Testing/Startup.cs#L24 you need to add ```app.UseDeveloperExceptionPage()``` middleware. Do not use that middleware in production.

**Comment by TJSoftware** [comment]
Thank you, that did the trick.  I know I ran across the dependencies before, I do not think I recall the `app.UseDeveloperExceptionPage()` though.  

Note for others, I had to place `app.UserDeveloperExceptionPage()' before `app.UseMvc()`.  @rambocoder, do you know if there is a dependency on the load order of what is placed in configure?

**Comment by rambocoder** [comment]
@TJSoftware jump on https://jabbr.net/#/rooms/AspNetvNext and we can answer all your questions. It's a great group of helpful people. I am not exactly sure which middleware must go before the other ones, yet.
