### ISSUE TITLE
dnu restore fails on Linux VM when building a docker image

### ISSUE THREAD

**Issue by stefanrahnev** [aspnet/Home#1059]
I encounter NameResolutionFailure error when trying to restore the following NuGet packages when building a docker image on a Linux VM:

GET https://www.nuget.org/api/v3/index.json
Restoring packages for /app/project.json

GET https://www.nuget.org/api/v3/FindPackagesById()?Id='Microsoft.AspNet.Mvc'.
GET https://www.nuget.org/api/v3/FindPackagesById()?Id='Microsoft.AspNet.Server.Kestrel'.
GET https://www.nuget.org/api/v3/FindPackagesById()?Id='Microsoft.AspNet.IISPlatformHandler'.
GET https://www.nuget.org/api/v3/FindPackagesById()?Id='Microsoft.AspNet.StaticFiles'.
Warning: FindPackagesById: Microsoft.Aspnet.Mvc
Error: NameResolutionFailure
Warning: FindPackagesById: Microsoft.Aspnet.Server.Kestrel
Error: NameResolutionFailure
Warning: FindPackagesById: Microsoft.Aspnet.IISPlatformHandler
Error: NameResolutionFailure
Warning: FindPackagesById: Microsoft.Aspnet.StaticFiles
Error: NameResolutionFailure

Restore failed.
A task was cancelled.

Feed used:
https://www.nuget.org/api/v3/index.json
The command 'dnu restore' returned a non-zero code: 1

nuget.org seems to be up and running. Can you advise, @davidfowl? Thanks.

**Comment by pranavkm** [comment]
Your NuGet endpoint needs to be `https://api.nuget.org/v3/index.json`

**Comment by stefanrahnev** [comment]
I actually did a mistake when pasting the urls. Actually I use the endpoint you specified when getting these errors, i.e.:

GET https://api.nuget.org/v3/index.FindPackagesById()?Id='Microsoft.AspNet.Mvc'.
GET https://api.nuget.org/v3/index.FindPackagesById()?Id='Microsoft.AspNet.Server.Kestrel'.
GET https://api.nuget.org/v3/index.FindPackagesById()?Id='Microsoft.AspNet.IISPlatformHandler'.
GET https://api.nuget.org/v3/index.FindPackagesById()?Id='Microsoft.AspNet.StaticFiles'.

Please advise.

**Comment by vladimirivanoviliev** [comment]
The strange thing is that on the same machine, same project restore packages is successful when calling "dnu restore". It fails only when start building the docker image. Could this be related to the network or some certificates?

**Comment by pranavkm** [comment]
If it's an issue with certs, you could try hitting the HTTP endpoint to diagnose the issue. Also hitting the endpoint with curl might help with determing if this is a network issue. 

Another alternative might be to restore this ahead of time on a machine that doesn't run into these issues and copy the `~/.dnx` directory in to your images.

**Comment by vladimirivanoviliev** [comment]
Thanks for the suggestions. I just tried to run the VM on different network and the restore start working as expected.

**Comment by vladimirivanoviliev** [comment]
By the way you might hit another issue after successfully restoring the packages. The issue is that the default settings of the "project.json" / "Dockerfile" provided by the aspnet examples will lead to that the container web server is not accessible from the host. Here are the fixes:

Project.json (make sure you add last parameter):
"commands": {
        "kestrel": "Microsoft.AspNet.Hosting --server Microsoft.AspNet.Server.Kestrel --server.urls http://*:5004"
    },

Dockerfile:
FROM microsoft/aspnet:1.0.0-beta8-coreclr
...
EXPOSE 5004

**Comment by stefanrahnev** [comment]
Thanks for the responses, @vladimirivanoviliev and @pranavkm.

**Comment by muratg** [comment]
:+1:
