### ISSUE TITLE
ASP.NET 5 and EF6 results in connection timeout

### ISSUE THREAD

**Issue by damienpontifex** [aspnet/Home#1062]
I am looking at utilising entity framework 6 in a asp.net 5 application, and setup the connection string to be passed to the DbContext constructor in configure services in startup. But when connecting I get an exception of 'SqlException: A network-related or instance-specific error occurred while establishing a connection to SQL Server'. The connection string is formatted straight from a new project template and looks like so (escaped back slash due to json):
```
Server=(localdb)\\mssqllocaldb;Database=database_name;Trusted_Connection=True;MultipleActiveResultSets=true
```

The database is also being used from a .NET4 WebJob, and works fine, plus I can connect to the server from Management Studio. Leading me to believe it's something about the way asp.net is passing the connection string through? 

Any assistance on where to look would be greatly appreciated.

**Comment by Eilon** [comment]
@divega can someone on your team take a look?

**Comment by pgrudzien12** [comment]
Hi @damienpontifex I'm not sure if it will help you but I recently made fairly deep investigation on EF6 and ASP.NET5. You might look also if there is any inner exception. I had problems with beta8 and migrations due to resource loading bug. This scenario gave me the exact same exception except inner errors.

Again this may help or not but at least may give you some resource to look at: http://bleedingnedge.com/2015/11/01/entity-framework-6-with-asp-net-5/

**Comment by malickf** [comment]
@damienpontifex  I faced a similar problem and the problem cames from the fact that i was sending the Id to the database which make bug the database. See this post http://stackoverflow.com/questions/14617420/dbupdateexception-when-adding-and-saving-record-to-dbcontext-in-asp-net-mvc/14627812#comment54950306_14627812 .. So can you check precisely when the exception is raise ? in my case it was at the saveChanges() moment.

**Comment by damienpontifex** [comment]
@pgrudzien12 that was exactly it! I thought it must have been something around that configuration, but didn't find anything until you linked that article.

I also had the issue mentioned in the article with the resource file and automatic migrations.

**Comment by divega** [comment]
Thanks @damienpontifex for bringing this up and @pgrudzien12 for documenting your findings. 

@rowanmiller @danroth27 http://bleedingnedge.com/2015/11/01/entity-framework-6-with-asp-net-5/ is a good read. are we going to have documentation on how to setup things to use EF6 with ASP.NET5?

**Comment by damienpontifex** [comment]
@divega I'd be happy to contribute to a docs article. I assume best place may be alongside here https://docs.asp.net/en/latest/data/entity-framework.html

Maybe something under Working with Data titled 'Building Web Applications With Entity Framework 6'

Would that be the most appropriate place to start something?

**Comment by divega** [comment]
@damienpontifex that sounds great to me, but I will defer to @danroth27 on what is the right place for it in the ASP.NET 5 docs.

**Comment by danroth27** [comment]
> Maybe something under Working with Data titled 'Building Web Applications With Entity Framework 6'

Sounds reasonable to me. We would welcome a contribution.

**Comment by pgrudzien12** [comment]
Sounds great. I'd like to join as well. We could use some of the content from my blog.

**Comment by damienpontifex** [comment]
@pgrudzien12 I added you as a collaborator to my fork DamienPontifex/Docs@048bead and am working on a branch titled 'ef6-article' would be very happy to work together
