### ISSUE TITLE
Bitdefender removed all rc2-* runtimes as malware

### ISSUE THREAD

**Issue by davezych** [aspnet/Home#1064]
Bitdefender has recently removed all of my `rc2-*` dnx runtimes as `Gen:Variant.Mikey.27510`:

>File C:\Users\david.zych\.dnx\runtimes\dnx-clr-win-x86.1.0.0-rc2-16086\bin\dnx.exe is malware of type Gen:Variant.Mikey.27510. The file was deleted.

I had a few rc2 runtimes installed last week and they were okay, however this morning all of them have been removed. Also, if I attempt to install any new rc2 runtime Bitdefender deletes `dnx.exe` out of the `.dnx\runtimes\temp\bin` directory as the same malware type. 

It's also worth noting that any other non rc2 runtimes (`rc1` and any `beta*`) are fine and have been left alone.

**Comment by Eilon** [comment]
We do virus-scan all our components prior to publishing. I'll look into this.

**Comment by Eilon** [comment]
I can reproduce this with Bitdefender and that build of DNX. Will report back when I found out more.

**Comment by Eilon** [comment]
This is passing all internal virus scans, so I suspect this is a false positive from that particular scanner.

@blowdart FYI.
