### ISSUE TITLE
CORS doesn't work after update to beta8

### ISSUE THREAD

**Issue by TomGroeneboer** [aspnet/Home#1066]
Hi guys,

I just updated my project from beta5 to beta8, but since I did that I can't get CORS to work anymore... I changed my configuration to 
```
services.AddCors( options => options.AddPolicy( "mypolicy", builder =>
			{
				builder.AllowAnyHeader();
				builder.AllowAnyMethod();
				builder.AllowAnyOrigin();
				builder.AllowCredentials();
			}
			) );
```
but when I perform a request to the address, it simply says  `No 'Access-Control-Allow-Origin' header is present on the requested resource.`

All my packages in project.json are beta8. 

Does anyone know why this thing isn't working anymore?

Thanks in advance!

**Comment by damienbod** [comment]
I'm using CORS in beta8 and its working.

In the startup
 //Add Cors support to the service
            services.AddCors();

            var policy = new Microsoft.AspNet.Cors.Core.CorsPolicy();

            policy.Headers.Add("*");
            policy.Methods.Add("*");
            policy.Origins.Add("*");
            policy.SupportsCredentials = true;

            services.AddCors(x => x.AddPolicy("corsGlobalPolicy", policy));
---
app.UseCors("corsGlobalPolicy");
---
https://github.com/damienbod/AspNet5IdentityServerAngularImplicitFlow/blob/master/src/ResourceServer/Startup.cs
----
 "Microsoft.AspNet.Cors": "6.0.0-beta8",

Greetings Damien
And the project.json

**Comment by kichalla** [comment]
@TomGroeneboer I am unable to repro this. Could you share a simple repro?

**Comment by TomGroeneboer** [comment]
Hi guys, 

I've figured out what the problem is... In beta5 I was running on IIS, but this is not supported anymore. So I use the `web` thing now. `"web": "Microsoft.AspNet.Hosting --server Microsoft.AspNet.Server.WebListener`. I've got it up and running again :) I think the CORS error comes from my React application, if I use Postman it gives me a 404 not found when I try to access the webservice.

Thanks for your help guys!

**Comment by garora** [comment]
Its good to know that you found the solution.
Just a thought it'd be a problematic if its not supported. What happened if
earlier someone hosted on Linux and now moving to Windows, any thoughts?

On Wed, Nov 11, 2015 at 2:50 PM, Tom <notifications@github.com> wrote:

> Hi guys,
>
> I've figured out what the problem is... In beta5 I was running on IIS, but
> this is not supported anymore. So I use the web thing now. "web":
> "Microsoft.AspNet.Hosting --server Microsoft.AspNet.Server.WebListener.
> I've got it up and running again :) I think the CORS error comes from my
> React application, if I use Postman it gives me a 404 not found when I try
> to access the webservice.
>
> Thanks for your help guys!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aspnet/Home/issues/1066#issuecomment-155711916>.
>



-- 
Thanks & Regards,
Gaurav Arora
