### ISSUE TITLE
HttpPlatformHandler failing to load with x64 IISExpress

### ISSUE THREAD

**Issue by frourke** [aspnet/Home#1067]
I updated from beta5 to beta8 and when launching x64 sites I get the following error.

The Module DLL 'C:\Program Files (x86)\Microsoft Web Tools\HttpPlatformHandler\HttpPlatformHandler.dll' could not be loaded due to a configuration problem. The current configuration only supports loading images built for a AMD64 processor architecture. 

I have installed version 1.2 of the x64 HttpPlatformHandler.

Local IIS works fine.

Any ideas?

Here is the output from IISExpress.exe
Starting IIS Express ...
Initializing the W3 Server Started CTC = 5894328 
W3 Server initializing WinSock.  CTC = 5894343 
W3 Server WinSock initialized.  CTC = 5894343 
W3 Server ThreadPool initialized (ipm has signalled).  CTC = 5894343 
Failed processing with hr = 800700c1
Error loading global modules.  hr = 800700c1
Terminating W3_SERVER object
Start listenerChannel http:0
Initializing the W3 Server Started CTC = 5895453 
W3 Server initializing WinSock.  CTC = 5895468 
W3 Server WinSock initialized.  CTC = 5895468 
W3 Server ThreadPool initialized (ipm has signalled).  CTC = 5895468 
Failed processing with hr = 800700c1
Error loading global modules.  hr = 800700c1
Terminating W3_SERVER object
InitComplete event signalled
Process Model Shutdown called
Unable to start iisexpress.

For more information about the error, run iisexpress.exe with the tracing switch enabled (/trace:error).

**Comment by GuardRex** [comment]
@frourke To confirm the correct HttpPlatformHandler (because some of the links out there are still v1.0), take a look in `Control Panel > Programs > Programs and Features` and confirm "v1.2" is in the name of the entry. It will say "v1.2" if the right one is installed.

**Comment by frourke** [comment]
I have rolled back my machine but it certainly was v1.2 in Web Platform Installer - did not look in Programs and Features.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
