### ISSUE TITLE
DNX Runtime releases and SemVer

### ISSUE THREAD

**Issue by tugberkugurlu** [aspnet/Home#1068]
Are DNX Runtime packages going to apply SemVer? What I am trying to understand is this: when I rely on DNX runtime 1.0.0 for my library or application, can I assume that it will always work on any runtime releases whose major version is 1 and may not work for any with major version of 2 or higher?

**Comment by Eilon** [comment]
SemVer agrees with the first part of your statement, but not the second.

SemVer says that as long as you stay within 1.x, there will be no breaking changes.

SemVer says that when 1.x changes to 2.x, there are breaking changes. However, that doesn't *necessarily* mean that a particular library won't work on 2.x. If the library just uses `string` or `int` then it is quite safe to assume no breaking changes would happen in *that* part of the system.

**Comment by tugberkugurlu** [comment]
@Eilon thanks! Yes, true but you cannot assume that your library written against 1.x will work on runtime 2.x. So, my questions is: what is the plan for DNX runtimes? Is SemVer is going to be applied for them as it's explained [here](http://semver.org/)? Can I always assume that my app/library will survive upgrades within the same major version?

**Comment by Eilon** [comment]
The idea is to apply SemVer to all packages. So yes, you can safely assume that.

**Comment by tugberkugurlu** [comment]
@Eilon thx!
