### ISSUE TITLE
WebListener webroot problem

### ISSUE THREAD

**Issue by Kagamine** [aspnet/Home#1070]
if you set the webroot in project.json like this `../../../wwwroot` with weblistener

`wwwroot` is okay, relative path is not works

It will miss all of the static files

**Comment by Kagamine** [comment]
So, When you publish with weblistener, the vs will put the wwwroot into `../../../wwwroot`, it should be also put it into `wwwroot` if it ignore the webroot.

**Comment by Tratcher** [comment]
What versions of the tooling, dnx, and Microsoft.AspNet.Hosting are you using? There were breaking changes here in the RC1 milestone. https://github.com/aspnet/Announcements/issues/94
