### ISSUE TITLE
Binding to a complex type parameter without FromBody attribute

### ISSUE THREAD

**Issue by tugberkugurlu** [aspnet/Home#1075]
I have the following action inside my MVC 6 controller (6.0.0-beta8):

```csharp
        [HttpPost]
        public IActionResult Post(TripCreationModel creationModel)
        {
            Console.WriteLine("foo:" + creationModel.Name);
            return new HttpStatusCodeResult(202);
        }
```

When I post valid JSON to it, it doesn't bind. However, when I send apply `[FromBody]`, it binds successfully. This is a bit different from current Web API. What is the easiest way to get rid of `FromBody` attribute?

**Comment by dougbu** [comment]
1. Suggest asking MVC-specific questions in the MVC repo.
2. You can't get rid of the `[FromBody]` requirement because MVC 6 defaults to form data model binding. That is, you must opt into input formatting.
