### ISSUE TITLE
Is it possible to add a VNext Class Library to a UAP project?

### ISSUE THREAD

**Issue by AdamDotNet** [aspnet/Home#1076]
I have ASP.NET Beta 8 installed on Visual Studio 2015 Update 1 RC. The UAP tools are 1.2 RC.

My project structure is VNext Library of models, VNext WebApi, and UAP. I want to share Models between the server and the client app.

My VNext library has the following framework declarations:
``` json
"frameworks":
  {
    "uap10.0":
    {
      "dependencies":
      {
        "Microsoft.CSharp": "4.0.1-beta-23409",
        "System.Collections": "4.0.11-beta-23409",
        "System.Linq": "4.0.1-beta-23409",
        "System.Runtime": "4.0.21-beta-23409",
        "System.Threading": "4.0.11-beta-23409"
      }
    },
    "dnxcore50":
    {
      "dependencies":
      {
        "Microsoft.CSharp": "4.0.1-beta-23409",
        "System.Collections": "4.0.11-beta-23409",
        "System.Linq": "4.0.1-beta-23409",
        "System.Runtime": "4.0.21-beta-23409",
        "System.Threading": "4.0.11-beta-23409"
      }
    }
  }
```

However, when I try to add a reference of the VNext library to the UAP project, Visual Studio's Add Reference -> Projects dialog errors with the message:

---------------------------
Microsoft Visual Studio
---------------------------
A reference to 'FoosballTracker.Models' could not be added. The method or operation is not implemented.
---------------------------
OK   
---------------------------

Is this expected to work in the future? Am I running "too beta" with the RC of the IDE and the beta tools? Just give it some time (possible RC of the ASP.NET tools next week)?

Thanks!

**Comment by davidfowl** [comment]
> Is this expected to work in the future?

Yes. This doesn't work as yet. It will work before ASP.NET 5 RTM.

**Comment by AdamDotNet** [comment]
Sounds fine. Thanks!
