### ISSUE TITLE
 FileLoadException: A strongly-named assembly is required. Error

### ISSUE THREAD

**Issue by kspearrin** [aspnet/Home#1077]
Please see the following repository to reproduce the issue: https://github.com/kspearrin/StrongNameErrorBase32Package

ref: https://github.com/kspearrin/StrongNameErrorBase32Package/blob/master/src/StrongNameErrorBase32Package/Controllers/ValuesController.cs

```csharp
using System;
using System.Collections.Generic;
using Base32;
using Microsoft.AspNet.Mvc;
using OtpSharp;

namespace StrongNameErrorBase32Package.Controllers
{
    [Route("api/[controller]")]
    public class ValuesController : Controller
    {
        // GET: api/values/fails
        [HttpGet("fails")]
        public IEnumerable<string> GetFails()
        {
            var key = KeyGeneration.GenerateRandomKey(20);
            var qrData = KeyUrl.GetTotpUrl(key, "me");
            return new string[] { "value1", "value2", qrData };
        }

        // GET: api/values/works
        [HttpGet("works")]
        public IEnumerable<string> GetWorks()
        {
            var key = KeyGeneration.GenerateRandomKey(20);
            var b32String = Base32Encoder.Encode(key);
            return new string[] { "value1", "value2", b32String };
        }
    }
}
```

I am trying to use a package, [OtpSharp](https://bitbucket.org/devinmartin/otp-sharp/wiki/Home) in a WebAPI project and am getting the following exception:

> An exception of type 'System.IO.FileLoadException' occurred in OtpSharp.dll but was not handled in user code
> 
> Additional information: Could not load file or assembly 'Base32, Version=1.0.0.26, Culture=neutral, PublicKeyToken=3427d4dc8cee30c6' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)

Interestingly enough, if I use the [Base32](https://bitbucket.org/devinmartin/base32) dependency directly, it works fine.

Any idea whats going on here? I've tried deleting `project.lock.json` and all packages from `.dnx/packages` with a restore but that did not help.

**Comment by davidfowl** [comment]
@kspearrin beta8 dnx right?

**Comment by kspearrin** [comment]
Yes.

**Comment by davidfowl** [comment]
I tried the solution and the OtpSharp package is just generally broken. The error you get in a regular csproj is more accurate:

```
Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'Base32, Version=1.0.0.26, Culture=neutral, PublicKeyToken=3427d4dc8cee30c6' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at OtpSharp.KeyUrl.GetBaseKeyUrl(Byte[] key, String user, OtpType otpType, Int32 size)
   at OtpSharp.KeyUrl.GetTotpUrl(Byte[] key, String user, Int32 step, OtpHashMode mode, Int32 totpSize)
   at ConsoleApplication1.Program.Main(String[] args) in C:\dev\git\StrongNameErrorBase32Package\ConsoleApplication1\Program.cs:line 15
```

OtpSharp is compiled against `// Base32, Version=1.0.0.26, Culture=neutral, PublicKeyToken=3427d4dc8cee30c6` but the package and assembly has no strong name:

```
// C:\Users\davifowl\.dnx\packages\Base32\1.0.0.12\lib\net40\Base32.dll
// Base32, Version=1.0.0.12, Culture=neutral, PublicKeyToken=null
```

**Comment by davidfowl** [comment]
To fix it just add a reference to a newer versions of Base32:

```
    "Base32": "1.0.0.26"
```

Then complain to the package author of OtpSharp :smile:

**Comment by kspearrin** [comment]
Just to follow up, this issue was resolved by the OtpSharp author: https://bitbucket.org/devinmartin/otp-sharp/issues/14/aspnet-5-fileloadexception-a-strongly

**Comment by davidfowl** [comment]
Very nice :smile:
