### ISSUE TITLE
Injecting ClaimsPrincipal in service layer

### ISSUE THREAD

**Issue by Muchiachio** [aspnet/Home#1078]
Is there a clean way to get `ClaimPrincipal` or `IIdentity` from DI? So it can be used in service layers.
This was ugly, but possible with the "good old" `HttpContext.Current.User` :smile:

**Comment by davidfowl** [comment]
You can use the `IHttpContextAccessor` in your services.

**Comment by Muchiachio** [comment]
Ye, I guess that's doable, thx.
