### ISSUE TITLE
DevEnv with Kestrel & HttpPlatformHandler

### ISSUE THREAD

**Issue by IsaacSee** [aspnet/Home#1080]
Hello, 

After the hosting infrastructure migration to Kestrel + HttpPlatformHandler we are wondering what is the recommended way to go for the following use cases.
- How to setup/run a website with dnx-watch so that source code changes triggers a restart of the local website ? Using project.json commands would be great.
- How to setup/run/debug a website locally using IIS without having to publish it before ? We need this to be able to test/debug the website through the new HttpPlatformHandler.

**Comment by poke** [comment]
Just set up the normal `web` command with Kestrel. And then run `dnx-watch web` from the project root.

As for IIS, you should know that the HttpPlatformHandler does nothing else under the hood than run the web command too. So you should get almost the same experience from running Kestrel separately and running it through (unmanaged) IIS.

Other than that, I guess publishing it is the only real alternative.

**Comment by GuardRex** [comment]
RE: IIS scenario: You could use a PS script to recycle the AppPool on the server that you can trigger locally whenever/however you need. There is a `Restart-WebAppPool` command. See https://technet.microsoft.com/en-us/library/ee790580.aspx. For tips/ideas on how that might be used, see my publish with PS example at https://github.com/GuardRex/net5-iis-ps-publish.

**Comment by IsaacSee** [comment]
Hello, thanks for your answers.

About `dnx-watch` when we need to watch we run `dnx-watch web' from a cmd window, but I wanted to know if there was a way to run it directly from visual studio. Creating a command like `web-watch` in the project.json. My research brought me there : https://github.com/aspnet/dnx-watch/issues/26.

About running the website through IIS/HttpPlatformHandler. The need originate in issues in the HttpPlatformHandler, even if it just run the web command, there are some difference concerning the transfert of certain headers (like the client ip) with are not fully ready right now.

Thanks GuardRex, we'll give it a try.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
