### ISSUE TITLE
ASP.Net 5 Build and Deploy to Azure Web Site, best approche?

### ISSUE THREAD

**Issue by Eneuman** [aspnet/Home#1081]
Hi!
I have been scavaging the net for information about how deployment of ASP.Net 5 to Azure WebSite  will work in the future but no one seems to know. So after 3 days of research I turn to the source for information :)

I have read every blog post there is about this and every piece of information that google dug up for me and I still havn't found what I'm looking for, to quote a great artist.

First the setup:
I have a project (solution) that is using the onion/hexagon architecture, where each layer is in its own project file.
The solution is hosted in Visual Studio Online.
I want to use Release.Next to manage my releases so I can decide what, when and where each release is deployed. Build and deployment should be done using Hosted Agents.

To do this, I need to first build my project using VSO Build. This works great using a PreBuild.ps1 script and then the build in "Visual Studio Build" task. However, the build only produces .dll files.
I need the build to package my website into a package (.zip file perhaps) that later can be deployed using the Azure Web App Deployment Task. 

Old ASP could be package into a Web Deployment package but this does not seem to be the case with ASP.Net 5 and todays tools. 

So my questions are theese:
Has there been any decisions made on what will be the "default" solution when working with ASP.Net 5 Web Sites and Enterprise deployment scenarios (CI -> Dev -> QA -> Prod with full Release.Next support)?
Is there going to be supported VSO Build Tasks for this or is its going to be custom PS scripts?
Is there today a way to package a ASP.Net 5  web into a supported format (like Web Deploy Package) and deploy it using existing  Azure Web App Deployment Task?

I'm just trying to figure out how deployment will work in the not so far away future :)

(Any answers are greatly welcome but please do not post links to any of the blog posts out there since I have read them all and none of them are applicable in a enterprise scenario)

//Per

**Comment by Eneuman** [comment]
Noone?

**Comment by aelking** [comment]
I have been trying to achieve exactly the same thing. Been working on it all weekend, but nothing helps.
The prebuild script works fine, but is a little bit slow (>5 minutes to complete).

This appeared to be demo'd at Connect, but cannot see anything to help out how, and none of the documentation found works.

**Comment by GuardRex** [comment]
@aelking I keep a list of the known issues for Azure Apps in my comment at: https://github.com/aspnet/Hosting/issues/364#issuecomment-148567294

However, some of the info is probably stale for RC2. I'll be updating those comments again within a week or two.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
