### ISSUE TITLE
When will ADAL be supported in ASP.NET 5?

### ISSUE THREAD

**Issue by mdraganza** [aspnet/Home#1082]
Does anyone know when ADAL (Azure AD Authentication Library) will be supported in ASP.NET 5? When will there be samples for it? Or is this a question for the Active Directory team.

**Comment by GuardRex** [comment]
@mdraganza I think it is under an alpha release ...
```
"Microsoft.IdentityModel.Clients.ActiveDirectory":  "3.5.208051316-alpha",
```
https://www.nuget.org/packages/Microsoft.IdentityModel.Clients.ActiveDirectory/3.5.208051316-alpha

**Comment by Eilon** [comment]
@tushargupta51 @brentschmaltz can you guys comment?

**Comment by tushargupta51** [comment]
@kpanwar do we have ADAL samples for asp.net 5?

**Comment by tushargupta51** [comment]
@mdraganza as @GuardRex  pointed, https://github.com/Azure-Samples/active-directory-dotnet-webapp-openidconnect-aspnet5 might help.

**Comment by GuardRex** [comment]
@mdraganza That OpenIdConnect one is a beta6 sample, but you can upgrade it to beta8. I have a beta7 version (that also have a Graph API piece for authorization) that I can put up for you to see (let me know), but @dstrockis is "The Man" when it comes to the samples on that stuff. You'd be a lot better off following his lead than looking at my test app. He's always kicking out great stuff to look at.

**Comment by mdraganza** [comment]
Thanks for the info. We are building an Azure multi-tenant application with ASP.NET 5 MVC 6. For that we need ADAL and I don't see any  samples for that scenario. It looks like ADAL isn't fully supported for ASP.NET 5 yet.

**Comment by GuardRex** [comment]
@mdraganza I think the multi-tenant bit is delayed a little. If I recall correctly, they said "not yet ... we're working on it" on that one (but I can't find the issue where that was stated explicitly). Try these and see if any of them help:

https://github.com/aspnet/Home/issues/973
http://forums.dotnetfoundation.org/t/official-support-for-multi-tenancy/1193
http://blog.maartenballiauw.be/post/2015/02/17/Domain-Routing-and-resolving-current-tenant-with-ASPNET-MVC-6-ASPNET-5.aspx
https://nocture.dk/2015/02/12/subdomain-based-multitenancy-asp-net-mvc-5/

**Comment by dstrockis** [comment]
Thanks Luke :)

@mdraganza we do have a sample using our preview version of ADAL that supports .NET 5, see here: https://github.com/Azure-Samples/active-directory-dotnet-webapp-webapi-openidconnect-aspnet5.  But Luke is right, it's woefully out of date.  We're trying to find some time to update it.  However, the patterns used in that sample will hold if you want to give it a shot yourself with the up-to-date libraries.

**Comment by GuardRex** [comment]
@dstrockis Sure thing. @mdraganza If you want to see that test app I did with beta7 and Graph API on that, let me know. I can have it up in a few hours.

**Comment by mdraganza** [comment]
I would. Thanks, Luke.

**Comment by GuardRex** [comment]
@mdraganza Ok. I'll have it up in a few hours. I'll ping you back here.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
