### ISSUE TITLE
DNVM 1.0.0-rc2-15542 breaks when user name contains spaces

### ISSUE THREAD

**Issue by alexthissen** [aspnet/Home#1084]
Reported previously in various other issues (e.g. https://github.com/aspnet/dnvm/issues/190). Still running into this issue with RC2-15542 on Windows 10 Pro x64.
<img width="514" alt="dnvm" src="https://cloud.githubusercontent.com/assets/5504642/11238388/75c8fa26-8de5-11e5-861f-d51d3c935399.png">

**Comment by alexthissen** [comment]
Accidentally put this in wrong place (should have been aspnet/dnvm). :$ Feel free to move.

**Comment by Eilon** [comment]
@alexthissen can you log it in the DNVM repo then? No easy way to move bugs in GitHub.
