### ISSUE TITLE
Wrong url in RC1 announcement

### ISSUE THREAD

**Issue by opiants** [aspnet/Home#1087]
The breaking change url points to beta-8 breaking changes. Should point to https://github.com/aspnet/announcements/issues?utf8=%E2%9C%93&q=is%3Aissue+milestone%3A1.0.0-rc1

**Comment by victorhurdugaci** [comment]
Where's that url?

**Comment by opiants** [comment]
Breaking Change section in https://github.com/aspnet/Home/releases/tag/v1.0.0-rc1

**Comment by victorhurdugaci** [comment]
@danroth27

**Comment by danroth27** [comment]
Should be fixed now. Thanks for letting us know!
