### ISSUE TITLE
Microsoft.Framework.SecretManager not updated for RC

### ISSUE THREAD

**Issue by bitcrazed** [aspnet/Home#1088]
Looks like `Microsoft.Framework.SecretManager` isn't being built and published in-sync with the rest of the DNX frameworks and tooling. [Nuget  is still listing `1.0.0-beta8` as the latest version](http://www.nuget.org/packages/Microsoft.Framework.SecretManager/).

**Comment by BrennanConroy** [comment]
That's because it is Microsoft.Extensions.SecretManager now
https://www.nuget.org/packages/Microsoft.Extensions.SecretManager/1.0.0-rc1-final

**Comment by bitcrazed** [comment]
Gah! Thanks.
