### ISSUE TITLE
Upgrade ASP.NET RC 1

### ISSUE THREAD

**Issue by lokinfey** [aspnet/Home#1089]
When I upgrade my asp.net RC1 today . I change the project.json
    "Microsoft.AspNet.IISPlatformHandler": "1.0.0-rc1-final",
    "Microsoft.AspNet.Mvc": "6.0.0-rc1-final",
    "Microsoft.AspNet.Server.Kestrel": "1.0.0-rc1-final",
    "Microsoft.AspNet.StaticFiles": "1.0.0-rc1-final",
    "Microsoft.Framework.Configuration.Json": "1.0.0-*"

When I dnu build It give me some errors :+1: 
/Users/lujianhui/Desktop/NetDemo/Startup.cs(4,27): DNX,Version=v4.5.1 error CS0234: The type or namespace name 'DependencyInjection' does not exist in the namespace 'Microsoft.Framework' (are you missing an assembly reference?)
/Users/lujianhui/Desktop/NetDemo/Startup.cs(25,39): DNX,Version=v4.5.1 error CS0246: The type or namespace name 'IServiceCollection' could not be found (are you missing a using directive or an assembly reference?)
/Users/lujianhui/Desktop/NetDemo/BuyAppDataContext.cs(12,18): DNX,Version=v4.5.1 error CS1061: 'IConfiguration' does not contain a definition for 'Get' and no extension method 'Get' accepting a first argument of type 'IConfiguration' could be found (are you missing a using directive or an assembly reference?)
/Users/lujianhui/Desktop/NetDemo/Startup.cs(16,6): DNX,Version=v4.5.1 error CS1061: 'IConfigurationBuilder' does not contain a definition for 'AddEnvironmentVariables' and no extension method 'AddEnvironmentVariables' accepting a first argument of type 'IConfigurationBuilder' could be found (are you missing a using directive or an assembly reference?)

But I can run it beta 8 and upgrade all . Can you help me ?

**Comment by joeaudette** [comment]
You need to read the announcements repo to learn about breaking changes. In this case you need to rename Microsoft.Framework.* as Microsoft.Extensions.* in project .json and anywhere in code where you use the namespace that was renamed

**Comment by chrilith** [comment]
Same problem for me, but it was creating a new Empty Application using yeoman right after ugrading everything. Changing "Framework" to "Extensions" fixed the error.

**Comment by zhshqzyc** [comment]
I have the same issue in the code 
` public static string Username = Startup.Configuration.Get("elasticEmail:userName");`
My project json file is:
```
{
  "webroot": "wwwroot",
  "version": "1.0.0-rc1-update",
  "dependencies": {
    "Microsoft.AspNet.Server.Kestrel": "1.0.0-rc1-final",
    "Microsoft.AspNet.IISPlatformHandler": "1.0.0-rc1-final",
    "Microsoft.AspNet.Diagnostics": "1.0.0-rc1-final",
    "Microsoft.AspNet.Mvc": "6.0.0-rc1-final",
    "Microsoft.Extensions.Logging.Console": "1.0.0-rc1-final",
    "Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.0.0-rc1-final",
    "Microsoft.AspNet.StaticFiles": "1.0.0-rc1-final",
    "Microsoft.Extensions.Configuration": "1.0.0-rc1-final",
    "EntityFramework": "6.1.3",
    "jqGridWebApi": "1.1.4",
    "EnyimMemcached": "2.13.0",
    "xunit": "2.2.0-beta1-build3239",
    "Moq": "4.2.1510.2205",
    "NLog": "2.1.0",
    "CryptSharpOfficial": "2.1.0",
    "System.Linq.Dynamic": "1.0.4"
  },
  "commands": {
    "web": "Microsoft.AspNet.Hosting --server Microsoft.AspNet.Server.WebListener --server.urls http://localhost:5001",
    "kestrel": "Microsoft.AspNet.Hosting --server Kestrel --server.urls http://localhost:5005",
    "ef": "EntityFramework.Commands"
  },
  "frameworks": {
    "dnx451": {
      "frameworkAssemblies": {
        "System.configuration": "4.0.0.0",
        "System.Data": "4.0.0.0"
      },
      "dnxcore50": { }
    }
  },
  "exclude": [
    "wwwroot",
    "node_modules",
    "bower_components"
  ],
  "publishExclude": [
    "node_modules",
    "bower_components",
    "**.xproj",
    "**.user",
    "**.vspscc"
  ],
  "scripts": {
    "prepublish": [ "npm install", "bower install", "gulp clean", "gulp min" ]
  },
  "configurations": {
    "Staging": { }
  }
}
```
Anybody can help me out?

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
