### ISSUE TITLE
Upgraded to rc1 ... and lost my IIS Express!

### ISSUE THREAD

**Issue by GuardRex** [aspnet/Home#1091]
I upgraded an app to `rc1-final`. My `IIS Express` option in VS disappeared. I added `http://localhost:5000` to the Launch Url for `web` (my command to launch Kestrel). That works. Is this the new preferred way to run locally? ... or is my IIS Express MIA not good?

**Comment by DamianEdwards** [comment]
Can you try the following:
1. Right-mouse click on the project in Solution Explorer and select "Properties" to open the property pages
1. Click the "Debug" tab on the left
1. Drop down the "Profile" select box and tell us what you see there
1. Click "New..", type in a profile name, then drop down the "Launch" select box and tell us what you see there

**Comment by GuardRex** [comment]
There is only one profile in the box ... `web` ... the command I specify in `project.json` for Kestrel.

When I add a profile, it gives me options for "Executable" and "Command".

**Comment by DamianEdwards** [comment]
@GuardRex strange

Is this in a brand new app or an existing app?

**Comment by GuardRex** [comment]
Existing app ... upgraded to rc1 this evening. All other apps showing IIS Express as usual. As soon as I upgraded, I lost the IIS Express option and it's only happening in this one app.

**Comment by DamianEdwards** [comment]
@GuardRex OK so it's likely something in your app that needs to change. Can you compare your project.json, startup.cs and wwwroot/web.config to those in a File -> New app?

**Comment by GuardRex** [comment]
App runs fine ... locally and on the server (well ... except for https://github.com/dotnet/corefx/issues/4533 and https://github.com/dotnet/corefx/issues/3927 ... we're stuck over there with System.Net.Security not resolving on the server)

**Comment by GuardRex** [comment]
@DamianEdwards Will do. I'll ping back.

**Comment by GuardRex** [comment]
@DamianEdwards Are you on the internal-only update to VS for rc1? I don't have it, so my new project gives me the template with ...
```
    "Microsoft.AspNet.IISPlatformHandler": "1.0.0-beta8",
    "Microsoft.AspNet.Server.Kestrel": "1.0.0-beta8"
```

**Comment by davidfowl** [comment]
https://get.asp.net/OtherDownloads

**Comment by DamianEdwards** [comment]
@GuardRex no I'm on public RC1 bits

**Comment by GuardRex** [comment]
Ah! I thought that was internal. Cool. I'll do that now. It will probably clear this up for me.

**Comment by GuardRex** [comment]
I did the install from https://get.asp.net/ ... it perhaps didn't install the bits at https://get.asp.net/OtherDownloads. It's confusing fyi.

**Comment by davidfowl** [comment]
Either works TBH, I'm on OSX tho

**Comment by GuardRex** [comment]
Well ... maybe nothing will happen. I ran the one at  https://get.asp.net/, then I made sure my dnvm was updated manually, then I manually put all runtime flavors on the box manually.

Strange thing now is that the installer seems hung. We'll see ...

**Comment by GuardRex** [comment]
I see what happened. The "Install" button at http://get.asp.net just redirects you to https://docs.asp.net/en/latest/getting-started/installing-on-windows.html ... it doesn't actually download the installer. You have to go to https://get.asp.net/OtherDownloads to get it. That isn't actually stated anywhere AFAIK.

Suggestion: The link to https://get.asp.net/OtherDownloads could be placed at:

https://github.com/aspnet/Home/releases/tag/v1.0.0-rc1
http://blogs.msdn.com/b/webdev/archive/2015/11/18/announcing-asp-net-5-release-candidate-1.aspx
In the ASP.NET 5 RC1 section of https://github.com/aspnet/Tooling/blob/master/known-issues.md

**Comment by GuardRex** [comment]
OH! ... and thanks again for your help. I'm looking forward to having my IIS Express back! :beers:

**Comment by GuardRex** [comment]
/cc: @danroth27 ... on the placement of that link in the Announcement for RC1

**Comment by danroth27** [comment]
The instructions at https://docs.asp.net/en/latest/getting-started/installing-on-windows.html already have the direct link for getting the ASP.NET 5 RC1 tooling update, so you shouldn't need to go to https://get.asp.net/OtherDownloads.

**Comment by GuardRex** [comment]
@danroth27 It wasn't clear to me that if you're upgrading that you should click that link.

The heading is "Install ASP.NET 5 with Visual Studio"
The first line starts "The easiest way to get started ..."
The steps ...
Step 1. Install Visual Studio 2015
Step 2. Install ASP.NET 5.

It sounds like the language and steps you would follow for an install if you didn't have anything previously installed. Since I had VS 2015 and .NET beta8, I just skipped it. I figured that all I needed to do was `dnvm update` and pull down RC1 runtime flavors and go.

Perhaps a section entitled "Upgrading ASP.NET and Visual Studio" with the same link? If it's just me, ok, but I was looking for something pertaining to "upgrading" ... it led to not getting the bits I needed ... then led to wasting @davidfowl and @DamianEdwards time.
