### ISSUE TITLE
RC1 new Web Project's bower.json and package.json are missing from VS 2015 Pro IDE

### ISSUE THREAD

**Issue by developer1998** [aspnet/Home#1092]
When creating new project in Visual Studio 2015, bower.json and package.json are missing from VS 2015 Pro IDE. They are actually there in the folder, so have to be added explicitly. 
Just to let you know... Thank you for RC1:)

**Comment by developer1998** [comment]
I just noticed that when you come back to the solution, those files are gone from IDE again, so they have to be explicitly added again, then they dissappear yet again. Something is not right.

**Comment by joeaudette** [comment]
those files are hidden on purpose by design now in the VS 2015 IDE, if you want to show them you need to click the icon to show all files in solution explorer. I think I saw this mentioned in Scott Hunter's video yesterday https://channel9.msdn.com/Events/Visual-Studio/Connect-event-2015/100  There is a new gui tool for managing bower components similar to nuget so I guess they hide the bower file to encourage use of the gui but you can show it if you want by clicking th show all files icon in solution explorer

**Comment by developer1998** [comment]
@joeaudette thank you for the clarification

**Comment by Lejdholt** [comment]
They should not be hidden. If you want us to use npm and bower please let us use it as the rest of the community does. Hiding them makes as much sense as if project.json was hidden.

**Comment by developer1998** [comment]
They are back, got the most recent VS 2015 Pro Update 1 and both config files have returned. Thank you.

**Comment by developer1998** [comment]
@joeaudette Thank you. I was able to see the functionality for bower packages and show/hide files. Question, is there a Node Package Manager interface. Cannot find it. Thanks

**Comment by tsdaemon** [comment]
@Lejdholt is right, please encourage users by good ui instead of hiding functionality

**Comment by BrainCrumbz** [comment]
@developer1998 there is a [NPM Scripts Task Runner](https://visualstudiogallery.msdn.microsoft.com/8f2f2cbc-4da5-43ba-9de2-c9d08ade4941) VS extension, by Mads Kristensen, that is able to detect scripts command from within `package.json` and show them in VS *Task Runner* pane, but if I'm not wrong it needs you to right-click on file, so if file is not visibile we're back at square 1.

BTW: `package.json` (and `bower.json`) are **really** bread & butter of everyday client dev work. Anyone creating a web project *ought to* know what they are and *ought to* know how to work with them. Especially with the former, that's really unavoidable. 

We strongly suggest to show them back *by default*. Or do as with VS Code, where you can hide single specific file & patterns in a custom way.

**Comment by Igmat** [comment]
@developer1998 to return npm and bower files in Solution Explorer, just remove `<DnxInvisibleContent Include="bower.json" />` and `<DnxInvisibleContent Include="package.json" />` from `YourAwesomeProject.xproj`

**Comment by IAMtheIAM** [comment]
@Igmat Thanks! That was exactly what I needed to know! Perfect solution.

**Comment by Otshepeng** [comment]
Please click there u will find it

![olg9a](https://cloud.githubusercontent.com/assets/16879817/19338981/d9a5bcf2-9120-11e6-851a-7779b85e7970.png)
