### ISSUE TITLE
First time using OS X aspnet fail

### ISSUE THREAD

**Issue by simonmurdock** [aspnet/Home#1094]
So I followed the instructions as best as I could:

Downloaded and installed the RC1 package
Got the latest samples 

Ran `dnu restore` in the consoleApp and got the following output, saying its denied access to its own .dnx directory?:

simons-MBP:ConsoleApp simon$ dnu restore
Microsoft .NET Development Utility CoreClr-x64-1.0.0-rc1-16202

  GET https://nuget.org/api/v2/
  OK https://nuget.org/api/v2/ 2219ms
  GET https://www.myget.org/F/aspnetrc1/api/v2/
  OK https://www.myget.org/F/aspnetrc1/api/v2/ 814ms
Restoring packages for /Users/simon/Desktop/samples/1.0.0-rc1-final/ConsoleApp/project.json
  GET https://nuget.org/api/v2/FindPackagesById()?id='System.Console'
  GET https://www.myget.org/F/aspnetrc1/api/v2/FindPackagesById()?id='System.Console'
  OK https://www.myget.org/F/aspnetrc1/api/v2/FindPackagesById()?id='System.Console' 114ms
  GET https://www.myget.org/F/aspnetrc1/api/v2/package/System.Console/4.0.0-beta-23516
  OK https://www.myget.org/F/aspnetrc1/api/v2/package/System.Console/4.0.0-beta-23516 1093ms
  GET https://nuget.org/api/v2/FindPackagesById()?id='System.Runtime'
  GET https://www.myget.org/F/aspnetrc1/api/v2/FindPackagesById()?id='System.Runtime'
  GET https://nuget.org/api/v2/FindPackagesById()?id='System.IO'
  GET https://www.myget.org/F/aspnetrc1/api/v2/FindPackagesById()?id='System.IO'
  OK https://nuget.org/api/v2/FindPackagesById()?id='System.Console' 1427ms
  OK https://www.myget.org/F/aspnetrc1/api/v2/FindPackagesById()?id='System.Runtime' 112ms
  OK https://nuget.org/api/v2/FindPackagesById()?id='System.Runtime' 296ms
  GET https://www.nuget.org/api/v2/package/System.Runtime/4.0.0
  OK https://www.myget.org/F/aspnetrc1/api/v2/FindPackagesById()?id='System.IO' 347ms
  OK https://nuget.org/api/v2/FindPackagesById()?id='System.IO' 908ms
  GET https://www.nuget.org/api/v2/package/System.IO/4.0.0
  OK https://www.nuget.org/api/v2/package/System.Runtime/4.0.0 851ms
  OK https://www.nuget.org/api/v2/package/System.IO/4.0.0 430ms
  GET https://nuget.org/api/v2/FindPackagesById()?id='System.Text.Encoding'
  GET https://www.myget.org/F/aspnetrc1/api/v2/FindPackagesById()?id='System.Text.Encoding'
  GET https://nuget.org/api/v2/FindPackagesById()?id='System.Threading.Tasks'
  GET https://www.myget.org/F/aspnetrc1/api/v2/FindPackagesById()?id='System.Threading.Tasks'
  OK https://www.myget.org/F/aspnetrc1/api/v2/FindPackagesById()?id='System.Threading.Tasks' 178ms
  OK https://www.myget.org/F/aspnetrc1/api/v2/FindPackagesById()?id='System.Text.Encoding' 235ms
  OK https://nuget.org/api/v2/FindPackagesById()?id='System.Threading.Tasks' 1382ms
  GET https://www.nuget.org/api/v2/package/System.Threading.Tasks/4.0.0
  OK https://nuget.org/api/v2/FindPackagesById()?id='System.Text.Encoding' 1420ms
  GET https://www.nuget.org/api/v2/package/System.Text.Encoding/4.0.0
  OK https://www.nuget.org/api/v2/package/System.Text.Encoding/4.0.0 385ms
  OK https://www.nuget.org/api/v2/package/System.Threading.Tasks/4.0.0 447ms
  GET https://nuget.org/api/v2/FindPackagesById()?id='runtime.unix.System.Console'
  GET https://www.myget.org/F/aspnetrc1/api/v2/FindPackagesById()?id='runtime.unix.System.Console'
  OK https://www.myget.org/F/aspnetrc1/api/v2/FindPackagesById()?id='runtime.unix.System.Console' 300ms
  GET https://www.myget.org/F/aspnetrc1/api/v2/package/runtime.unix.System.Console/4.0.0-beta-23516
  OK https://www.myget.org/F/aspnetrc1/api/v2/package/runtime.unix.System.Console/4.0.0-beta-23516 318ms
  GET https://nuget.org/api/v2/FindPackagesById()?id='System.Runtime.InteropServices'
  GET https://www.myget.org/F/aspnetrc1/api/v2/FindPackagesById()?id='System.Runtime.InteropServices'
  GET https://nuget.org/api/v2/FindPackagesById()?id='System.Resources.ResourceManager'
  GET https://www.myget.org/F/aspnetrc1/api/v2/FindPackagesById()?id='System.Resources.ResourceManager'
  GET https://nuget.org/api/v2/FindPackagesById()?id='System.Runtime.Handles'
  GET https://www.myget.org/F/aspnetrc1/api/v2/FindPackagesById()?id='System.Runtime.Handles'
  GET https://nuget.org/api/v2/FindPackagesById()?id='System.IO.FileSystem.Primitives'
  GET https://www.myget.org/F/aspnetrc1/api/v2/FindPackagesById()?id='System.IO.FileSystem.Primitives'
  GET https://nuget.org/api/v2/FindPackagesById()?id='System.Linq'
  GET https://www.myget.org/F/aspnetrc1/api/v2/FindPackagesById()?id='System.Linq'
  GET https://www.nuget.org/api/v2/package/System.Threading.Tasks/4.0.10
  GET https://www.nuget.org/api/v2/package/System.Text.Encoding/4.0.10
  GET https://nuget.org/api/v2/FindPackagesById()?id='System.Collections'
  GET https://www.myget.org/F/aspnetrc1/api/v2/FindPackagesById()?id='System.Collections'
  GET https://nuget.org/api/v2/FindPackagesById()?id='System.Threading'
  GET https://www.myget.org/F/aspnetrc1/api/v2/FindPackagesById()?id='System.Threading'
  GET https://nuget.org/api/v2/FindPackagesById()?id='System.Text.Encoding.Extensions'
  GET https://www.myget.org/F/aspnetrc1/api/v2/FindPackagesById()?id='System.Text.Encoding.Extensions'
  GET https://nuget.org/api/v2/FindPackagesById()?id='System.Runtime.Extensions'
  GET https://www.myget.org/F/aspnetrc1/api/v2/FindPackagesById()?id='System.Runtime.Extensions'
  OK https://www.myget.org/F/aspnetrc1/api/v2/FindPackagesById()?id='System.Runtime.InteropServices' 155ms
  OK https://www.myget.org/F/aspnetrc1/api/v2/FindPackagesById()?id='System.Threading' 259ms
  OK https://www.myget.org/F/aspnetrc1/api/v2/FindPackagesById()?id='System.IO.FileSystem.Primitives' 302ms
  OK https://www.myget.org/F/aspnetrc1/api/v2/FindPackagesById()?id='System.Text.Encoding.Extensions' 302ms
  OK https://www.myget.org/F/aspnetrc1/api/v2/FindPackagesById()?id='System.Collections' 307ms
  OK https://www.myget.org/F/aspnetrc1/api/v2/FindPackagesById()?id='System.Runtime.Handles' 335ms
  OK https://www.myget.org/F/aspnetrc1/api/v2/FindPackagesById()?id='System.Resources.ResourceManager' 337ms
  OK https://www.myget.org/F/aspnetrc1/api/v2/FindPackagesById()?id='System.Runtime.Extensions' 342ms
  OK https://www.myget.org/F/aspnetrc1/api/v2/FindPackagesById()?id='System.Linq' 355ms
  OK https://nuget.org/api/v2/FindPackagesById()?id='System.Threading' 865ms
  GET https://www.nuget.org/api/v2/package/System.Threading/4.0.10
  OK https://nuget.org/api/v2/FindPackagesById()?id='runtime.unix.System.Console' 1508ms
  OK https://nuget.org/api/v2/FindPackagesById()?id='System.Runtime.InteropServices' 890ms
  GET https://www.nuget.org/api/v2/package/System.Runtime.InteropServices/4.0.20
  OK https://www.nuget.org/api/v2/package/System.Text.Encoding/4.0.10 930ms
  OK https://www.nuget.org/api/v2/package/System.Threading.Tasks/4.0.10 1013ms
  OK https://www.nuget.org/api/v2/package/System.Threading/4.0.10 276ms
  OK https://www.nuget.org/api/v2/package/System.Runtime.InteropServices/4.0.20 308ms
  GET https://nuget.org/api/v2/FindPackagesById()?id='System.Reflection'
  GET https://www.myget.org/F/aspnetrc1/api/v2/FindPackagesById()?id='System.Reflection'
  GET https://nuget.org/api/v2/FindPackagesById()?id='System.Reflection.Primitives'
  GET https://www.myget.org/F/aspnetrc1/api/v2/FindPackagesById()?id='System.Reflection.Primitives'
  OK https://nuget.org/api/v2/FindPackagesById()?id='System.Runtime.Handles' 1363ms
  GET https://www.nuget.org/api/v2/package/System.Runtime.Handles/4.0.0
  OK https://nuget.org/api/v2/FindPackagesById()?id='System.Resources.ResourceManager' 1395ms
  GET https://www.nuget.org/api/v2/package/System.Resources.ResourceManager/4.0.0
  OK https://nuget.org/api/v2/FindPackagesById()?id='System.IO.FileSystem.Primitives' 1434ms
  GET https://www.nuget.org/api/v2/package/System.IO.FileSystem.Primitives/4.0.0
  OK https://nuget.org/api/v2/FindPackagesById()?id='System.Collections' 1434ms
  GET https://www.nuget.org/api/v2/package/System.Collections/4.0.10
  OK https://nuget.org/api/v2/FindPackagesById()?id='System.Linq' 1439ms
  GET https://www.nuget.org/api/v2/package/System.Linq/4.0.0
  OK https://www.myget.org/F/aspnetrc1/api/v2/FindPackagesById()?id='System.Reflection' 277ms
  OK https://nuget.org/api/v2/FindPackagesById()?id='System.Reflection.Primitives' 278ms
  OK https://nuget.org/api/v2/FindPackagesById()?id='System.Runtime.Extensions' 1475ms
  OK https://nuget.org/api/v2/FindPackagesById()?id='System.Text.Encoding.Extensions' 1477ms
  GET https://www.nuget.org/api/v2/package/System.Reflection.Primitives/4.0.0
  GET https://www.nuget.org/api/v2/package/System.Runtime.Extensions/4.0.10
  GET https://www.nuget.org/api/v2/package/System.Text.Encoding.Extensions/4.0.10
  OK https://nuget.org/api/v2/FindPackagesById()?id='System.Reflection' 285ms
  GET https://www.nuget.org/api/v2/package/System.Reflection/4.0.0
  OK https://www.myget.org/F/aspnetrc1/api/v2/FindPackagesById()?id='System.Reflection.Primitives' 290ms
  OK https://www.nuget.org/api/v2/package/System.Runtime.Handles/4.0.0 176ms
  OK https://www.nuget.org/api/v2/package/System.Resources.ResourceManager/4.0.0 199ms
  GET https://nuget.org/api/v2/FindPackagesById()?id='System.Globalization'
  GET https://www.myget.org/F/aspnetrc1/api/v2/FindPackagesById()?id='System.Globalization'
  OK https://www.nuget.org/api/v2/package/System.Linq/4.0.0 231ms
  GET https://nuget.org/api/v2/FindPackagesById()?id='System.Diagnostics.Debug'
  GET https://www.myget.org/F/aspnetrc1/api/v2/FindPackagesById()?id='System.Diagnostics.Debug'
  OK https://www.nuget.org/api/v2/package/System.Collections/4.0.10 296ms
  OK https://www.nuget.org/api/v2/package/System.IO.FileSystem.Primitives/4.0.0 387ms
  OK https://www.myget.org/F/aspnetrc1/api/v2/FindPackagesById()?id='System.Globalization' 267ms
  OK https://nuget.org/api/v2/FindPackagesById()?id='System.Globalization' 292ms
  GET https://www.nuget.org/api/v2/package/System.Globalization/4.0.0
  OK https://www.nuget.org/api/v2/package/System.Text.Encoding.Extensions/4.0.10 453ms
  OK https://nuget.org/api/v2/FindPackagesById()?id='System.Diagnostics.Debug' 279ms
  GET https://www.nuget.org/api/v2/package/System.Diagnostics.Debug/4.0.10
  OK https://www.nuget.org/api/v2/package/System.Reflection.Primitives/4.0.0 487ms
  OK https://www.myget.org/F/aspnetrc1/api/v2/FindPackagesById()?id='System.Diagnostics.Debug' 344ms
  OK https://www.nuget.org/api/v2/package/System.Reflection/4.0.0 570ms
  OK https://www.nuget.org/api/v2/package/System.Runtime.Extensions/4.0.10 576ms
  OK https://www.nuget.org/api/v2/package/System.Diagnostics.Debug/4.0.10 184ms
  OK https://www.nuget.org/api/v2/package/System.Globalization/4.0.0 303ms
Installing System.Console.4.0.0-beta-23516
----------
System.UnauthorizedAccessException: Access to the path '/Users/simon/.dnx/packages/System.Console/4.0.0-beta-23516' is denied.
   at System.IO.UnixFileSystem.CreateDirectory(String fullPath)
   at System.IO.Directory.CreateDirectory(String path)
   at Microsoft.Dnx.Tooling.NuGetPackageUtils.<>c__DisplayClass0_0.<<InstallFromStream>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Dnx.Runtime.Internal.ConcurrencyUtilities.<ExecuteWithFileLocked>d__2`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Dnx.Tooling.NuGetPackageUtils.<InstallFromStream>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.Dnx.Tooling.RestoreCommand.<InstallPackageCore>d__77.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.Dnx.Tooling.RestoreCommand.<InstallPackages>d__76.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.Dnx.Tooling.RestoreCommand.<RestoreForProject>d__69.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Dnx.Tooling.RestoreCommand.<>c__DisplayClass68_0.<<Execute>b__2>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.Dnx.Tooling.RestoreCommand.<Execute>d__68.MoveNext()
----------
Restore failed
Access to the path '/Users/simon/.dnx/packages/System.Console/4.0.0-beta-23516' is denied.

NuGet Config files used:
    /Users/simon/Desktop/samples/1.0.0-rc1-final/nuget.config

Feeds used:
    https://nuget.org/api/v2/
    https://www.myget.org/F/aspnetrc1/api/v2/

------

additionally running `dnvm upgrade` anywhere results in:

simons-MBP:ConsoleApp simon$ dnvm upgrade
Determining latest version
Latest version is 1.0.0-rc1-final 
dnx-mono.1.0.0-rc1-final already installed in /usr/local/lib/dnx
Adding /usr/local/lib/dnx/runtimes/dnx-mono.1.0.0-rc1-final/bin to process PATH
Updating alias 'default' to 'dnx-mono.1.0.0-rc1-final'
-bash: /Users/simon/.dnx/alias/default.alias: Permission denied

-----
and in case its any use :+1: 
simons-MBP:ConsoleApp simon$ mono --version
Mono JIT compiler version 4.2.1 (explicit/6dd2d0d Fri Nov  6 12:25:19 EST 2015)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           normal
	SIGSEGV:       altstack
	Notification:  kqueue
	Architecture:  x86
	Disabled:      none
	Misc:          softdebug 
	LLVM:          yes(3.6.0svn-mono-(detached/a173357)
	GC:            sgen

**Comment by BrennanConroy** [comment]
What are the file permissions for the .dnx folder? What instructions did you follow?

**Comment by muratg** [comment]
Not totally related to your issue, but `aspnetrc1` is a test feed that we've been using internally to verify RC1 and you should remove it from your `nuget.config`.

**Comment by simonmurdock** [comment]
https://docs.asp.net/en/latest/getting-started/installing-on-mac.html 

That 2 step process. 

The permissions are like this for .dnx:
drwxr-xr-x   4 root   staff    136 19 Nov 13:46 .dnx

@muratg  I'm not even sure how to do that, but I'll give it a go. I'm reporting to help anyone else who might get stuck on such a simple thing.

**Comment by BrennanConroy** [comment]
Did you use sudo to install? root is the only one that has write permission to that folder

**Comment by simonmurdock** [comment]
No, I just double clicked the installer. It asked for root permissions to install.

**Comment by simonmurdock** [comment]
deleted the .dnx folder and reinstalled using DNX-1.0.0-rc1-final.pkg from https://go.microsoft.com/fwlink/?LinkId=703940 

It is still showing with these permissions:
drwxr-xr-x   4 root   staff    136 19 Nov 17:48 .dnx

**Comment by BrennanConroy** [comment]
Looks like you found a bug in the installer.

Workaround:
cd ~/.dnx
chown -R simon:group .

We have filed an internal bug to track this

**Comment by simonmurdock** [comment]
Ah great! Glad I wasn't just being a Muppet :)

**Comment by ardacetinkaya** [comment]
I was getting the same permission denied error for "dnu restore", than I started to use with sudo and got used to it.
Hope to be fixed in next releases

**Comment by amansingh36** [comment]
@ardacetinkaya, what sudo command you ran because we are getting error with sudo:

COMMAND: sudo dnvm upgrade
ERROR: sudo: dnvm: command not found

COMMAND: dnvm upgrade
ERROR: -bash: /Users/username/.dnx/alias/default.alias: Permission denied

Reply As Soon As Possible.

**Comment by ardacetinkaya** [comment]
@amansingh36  You may also do @simonmurdock 's solution which also solves the problem. 
Be sure that the owner of .dnx folder has permissions.

My problems was with "dnu restore", so I just doing it with "sudo dnu restore" which is not necessary after permissions are set correctly for .dnx folder.

**Comment by amansingh36** [comment]
@ardacetinkaya, The problem was solved, but thanks for the reply.

COMMAND: yo aspnet
ERROR: Error aspnet 

You don't seem to have a generator with the name aspnet installed.
You can see available generators with npm search yeoman-generator and then install them with npm install [name].
To see the 0 registered generators run yo with the `--help` option.

Reply soon. Thanks

**Comment by BrennanConroy** [comment]
PKG Fixed with Update1
