### ISSUE TITLE
class library project

### ISSUE THREAD

**Issue by himadrinath** [aspnet/Home#1098]
In my class library project using <b>rc1-final</b> when i added  <b>"EntityFramework.Commands": "7.0.0-rc1-final"</b>, dependency in my project i getting an error saying this dependency does not support framework .NETPlatform,Version=v5.4.

Image
![entityframework commands](https://cloud.githubusercontent.com/assets/12247490/11282554/f5a026de-8f25-11e5-87ff-6559525ec77f.png)

**Comment by Eilon** [comment]
@divega @bricelam

**Comment by joeaudette** [comment]
I encountered this error also and the only way to get around it that I found was to change the target from dotnet5.4 to dnxcore50 in my class library projects. Maybe there is a better solution.

**Comment by bricelam** [comment]
Interesting. We target `dnxcore50` and `netcore50`. @davidfowl @anurse Does DNX support the NuGet 3 `ref` stuff? We probably need to author a package that looks something like this to make it work:

* lib/
    * dnxcore50/
    * netcore50/
* ref/
    * dotnet5.4/

**Comment by himadrinath** [comment]
@joeaudette i tried that way but when i running <b>dnx ef</b> command also getting an error in their.

![dnx_ef](https://cloud.githubusercontent.com/assets/12247490/11293216/e9baec0c-8f7d-11e5-8295-a9cd4446ae29.png)

**Comment by bricelam** [comment]
@himadrinath as a workaround, you should be able to add `dnxcore50` to your class library's list of frameworks.

**Comment by himadrinath** [comment]
@joeaudette i did as u say i changed dotnet5.4 to dnxcore50 in my project.json.

![class library ef](https://cloud.githubusercontent.com/assets/12247490/11316968/852e6992-9042-11e5-87dc-ac4627040258.png)

but after that when i run <b>dnx ef</b> command i got a another error.

please guide me through this problem. still not able to fix it and not able to run migration in my project.

**Comment by bricelam** [comment]
You'll either need to add `dnx541` to the frameworks, or run this before invoking `dnx ef`:
```cmd
dnvm use default -r coreclr
```

**Comment by davidfowl** [comment]
Is EntityFramework.Commands a library or exe?

**Comment by himadrinath** [comment]
@bricelam i changed the run time into <b>coreclr</b>  and then run the <b>dnx ef</b> command and another problem arrive

![1 0 0-rc1-final](https://cloud.githubusercontent.com/assets/12247490/11322337/d78d642a-910c-11e5-8603-998254ba4130.png)

**Comment by bricelam** [comment]
@davidfowl ...a dll with a static Main entry point at the moment.  The architecture will change a bit for RC 2.

**Comment by tmarinov** [comment]
Any news about this problem?
I am following this doc:
http://docs.efproject.net/en/latest/getting-started/aspnet5/existing-db.html

and when try to install the EF into a separate class library (package) - I am getting the error described above.

**Comment by bricelam** [comment]
@tmarinov The workaround should still work. Add `dnx451` or `dnxcore50` to your target frameworks.

**Comment by bricelam** [comment]
@davidfowl @glennc Any updates on how to author a package with a `ref` assembly using `project.json`?

**Comment by davidfowl** [comment]
That's not going to be first class anytime soon. First class support for bait and switch is not being worked on.

**Comment by bricelam** [comment]
Nuts. More nupkg patching it is...
