### ISSUE TITLE
Can't reference a '.NET Framework 4.6 + ASP.NET Core 5.0' PCL from a 'Console application (Package)' project

### ISSUE THREAD

**Issue by HellBrick** [aspnet/Home#1099]
#### Repro
- VS 2015.
- ASP.NET RC 1.
- Add a Console application (package project) to a solution, I'll call it `NetCoreApp` from now on.
- Remove `"dnx451"` from `project.json/"frameworks"` (not necessary, but let's simplify things a bit).
- Add a PCL library that targets .NET Framework 4.6 and ASP.NET Core 5.0 to a solution. I'll call it `PortableLibrary46` from now on.
- Try to add a reference from `NetCoreApp` to `PortableLibrary46`.

The package restore will fail with the following written to the output:

```
Microsoft .NET Development Utility Clr-x86-1.0.0-rc1-16202
Wrapping project 'PortableLibrary46' for '.NETPortable,Version=v5.0'
  Source F:\Software\NetCoreRC\PortableLibrary46\PortableLibrary46.csproj
  Target F:\Software\NetCoreRC\PortableLibrary46\project.json
Error: Value cannot be null.
Parameter name: profileValue
PATH=.\node_modules\.bin;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Web Tools\External;%PATH%;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Web Tools\External\git
C:\Users\HellBrick\.dnx\runtimes\dnx-clr-win-x86.1.0.0-rc1-final\bin\dnx.exe "C:\Users\HellBrick\.dnx\runtimes\dnx-clr-win-x86.1.0.0-rc1-final\bin\lib\Microsoft.Dnx.Tooling\Microsoft.Dnx.Tooling.dll" restore "F:\Software\NetCoreRC\src\NetCoreApp" -f "C:\Program Files (x86)\Microsoft Web Tools\DNU"
Microsoft .NET Development Utility Clr-x86-1.0.0-rc1-16202
  CACHE https://www.nuget.org/api/v2/
  CACHE https://www.myget.org/F/hellbrick/
  CACHE https://www.myget.org/F/aspnetvnext/api/v2/
Restoring packages for F:\Software\NetCoreRC\src\NetCoreApp\project.json
  CACHE https://www.nuget.org/api/v2/FindPackagesById()?id='PortableLibrary46'
  CACHE https://www.myget.org/F/hellbrick/FindPackagesById()?id='PortableLibrary46'
  CACHE https://www.myget.org/F/aspnetvnext/api/v2/FindPackagesById()?id='PortableLibrary46'
Unable to locate Dependency PortableLibrary46 >= 1.0.0-*
Writing lock file F:\Software\NetCoreRC\src\NetCoreApp\project.lock.json
Restore complete, 287ms elapsed
Errors in F:\Software\NetCoreRC\src\NetCoreApp\project.json
    Unable to locate Dependency PortableLibrary46 >= 1.0.0-*
NuGet Config files used:
    C:\Users\HellBrick\AppData\Roaming\NuGet\nuget.config
Feeds used:
    https://www.nuget.org/api/v2/
    https://www.myget.org/F/hellbrick/
    https://www.myget.org/F/aspnetvnext/api/v2/
    F:\Software\~nuget
    C:\Program Files (x86)\Microsoft Web Tools\DNU
```
#### Background

I'm exploring porting some parts of a big .NET 4.6 solution to .NET Core + DNX to use them in a cross-platform way. In order to do that I need to figure out how to share class libraries between .NET 4.6 apps and .NET Core apps (porting _everything_ simultaneously is not an option). Is there an alternative way to do that? So far I've managed to kinda sorta make it work by downgrading class libraries to 4.5.1 PCLs, but it would be nice to keep using 4.6 API if possible.

**Comment by sjdixon** [comment]
I'm no expert on this subject, but where are you trying to reference PortableLibrary46 from? It kind of looks like the package restore is looking for a Nuget package when it perhaps should be looking somewhere else.

**Comment by HellBrick** [comment]
This happens when I'm trying to reference `PortableLibrary46` from any modern ASP.NET 5 project, whether it's a console app, a class library or a website. `dnu wrap` fails and everything goes wrong from that moment on.

**Comment by JeremiahSanders** [comment]
I'm experiencing the same issue. Our primary, cross-application domain logic is contained in PCLs so they can be used in ASP.NET applications, mobile applications and Windows Universal. This is a blocker for ASP.NET 5 adoption.

I can easily reproduce the issue by creating a new ASP.NET 5 Web Application solution, adding a new PCL class library targeting .NET 4.6 + ASP.NET Core 5 + Windows Universal 10 to the solution's `.\src` directory, then finally adding a reference within the web project targeting the PCL.

Any known workarounds or anticipated resolutions?

**Comment by taori** [comment]
Any updates on this? Just tried to do it in a similar fashion as JeremiahSanders suggests and i've got the same problem with rc1

**Comment by HellBrick** [comment]
I guess we have to wait until dnu retires and proper support for both xproj > csproj and csproj > xproj references on top for the dotnet cli is shipped.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
