### ISSUE TITLE
ClaimsPrincipal Returns null on sequential calls with RC1-Final

### ISSUE THREAD

**Issue by TheMadKow** [aspnet/Home#1100]
Hi,
I got a partial code ControllerBase (Abstract Class) where i get the current user's ID and such.
The first call on the session goes well, but after some calls for the same/other controller, the ClaimsPrincipal is null. I'm using this code to search the full ApplicationUser object on the database from it's ID. 

For Exapmle:
User.IsSignedIn() will return true on first call and false afterwards.
User.GetUserId() will return the GUID on the first call and null afterwards.

The issue arose on changing from BETA8 to RC1-Final.
Thanks

Technical:
- Using Windows 10.
- Using Latest VS Tooling for RC1.
- Using x64 system.
- Using 'StaticFiles' on startup.

**Comment by Eilon** [comment]
@HaoK @Tratcher any ideas on this?

@TheMadKow can you upload an app to GitHub that shows this issue?

**Comment by TheMadKow** [comment]
@Eilon I'll try to do my best as soon as possible, but it may take couple of days now. 
Regardless, it's not browser specific (or cookie handling issue) because it happens both on Chrome and Edge on my tests.

**Comment by Eilon** [comment]
@TheMadKow yeah I'm not thinking it's browser or cookie related at all - this is all server code stuff. I'm just wondering if there's anything interesting in the startup, controller, project.json, etc.

**Comment by TheMadKow** [comment]
Hi @Eilon,
This the the repository link - https://github.com/TheMadKow/ToDoLo-Git/tree/master/src/ToDoLo
Thanks for helping me out, this could easily be something I've missed while upgrading.

The function in question is called 'AppUser()', at the moment on Controller Base -
https://github.com/TheMadKow/ToDoLo-Git/blob/master/src/ToDoLo/Controllers/RepositoryControllerBase.cs

Please also do no judge too harshly poor code, refactoring is still needed there ;-)

**Comment by Eilon** [comment]
@TheMadKow thanks for uploading the app. I can't see anything obviously wrong there.

Would it be possible to simplify the app by removing stuff and see what happens?

BTW just from a quick glance, none of the `lock` statements in that file are needed: a new controller instance is created for every request, so there's no shared state to protect.

**Comment by TheMadKow** [comment]
@Eilon, Tried to re-create the issue with new application . 
I've did a work-around the issue, where only the first call gets the data from the DB, shouldn't have worked, but it did. still doesn't explain why multiple calls to User.GetUserId() would return nulls here and there... :construction_worker:

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
