### ISSUE TITLE
aspnet 5 core console app current directory

### ISSUE THREAD

**Issue by tparnell8** [aspnet/Home#1101]
How can I get the full path for the current directory in an asp.net 5 core console app

**Comment by mishfit** [comment]
```bash
dnu install System.IO.FileSystem
```

```csharp
using System.IO;
...
Directory.GetCurrentDirectory();
```

_This is for CoreCLR and is for the current directory not the base of the console app_

**Comment by tparnell8** [comment]
:+1:  yup thats what I'm looking for...I think in the past I used System.Environment.CurrentDirectory but I noticed it was unavailable in coreclr. 

and yes I'm looking for the current directory not the base of the console app (since this will be in the path and we will be looking for files in the current directory) thanks again @mishfit
