### ISSUE TITLE
New web projects do not have IIS Express profile

### ISSUE THREAD

**Issue by TJSoftware** [aspnet/Home#1102]
### Summary
I followed the steps on the [windows install](http://docs.asp.net/en/latest/getting-started/installing-on-windows.html) to upgradew to RC1, I was previously on beta8.  After running `dnvm update-self` and `dnvm upgrade` I created a new web project.  I did not see the IIS Express profile in the new project.  When I run web, the console just closes immeadeatly.  Running web from console I see the following error...

```
System.MissingMethodException: Method not found: 'System.Collections.Generic.IDictionary`2<System.String,Microsoft.Framework.Primitives.StringValues> Microsoft.AspNet.Http.Features.IHttpRequestFeature.get_Headers()'.
```

### Functional Impact
I am unable to test new projects made after RC1 upgrade.  Project created during beta8 work still so I am certain that it is a project setting, I just do not know what.

### Reproduce the Issue
After upgrading to RC1 create a new web project (either empty or Web Application).  I left the auth as default.

I also see a few errors during a new project creation.

###### Errors during project creation
![image](https://cloud.githubusercontent.com/assets/4823412/11304065/85477714-8f63-11e5-8f6c-4f6b7000b1c8.png)
![image](https://cloud.githubusercontent.com/assets/4823412/11304070/8b0691da-8f63-11e5-8b8b-9fd7a0b1a308.png)
###### Missing profile
![image](https://cloud.githubusercontent.com/assets/4823412/11304098/af65cda2-8f63-11e5-917a-2664f45f09d5.png)
This shows that a DNX version has not been selected by default, I selected beta8 here.
![image](https://cloud.githubusercontent.com/assets/4823412/11304106/b2d24574-8f63-11e5-91c7-edd517f0b9b3.png)
![image](https://cloud.githubusercontent.com/assets/4823412/11304108/b74b556e-8f63-11e5-953c-3a9765664ccd.png)

First I tried to create a new profile, however, I was unable to add the web server settings.

If I unload the project and add a DevelopmentServerPort to the following property group I see the IIS Express profile (see code below).  I am able to run using IIS Express but not web at that point.  However, I only see a server connection refused error in the browser.
```
  <PropertyGroup>
    <SchemaVersion>2.0</SchemaVersion>
    <DevelopmentServerPort>42066</DevelopmentServerPort>
  </PropertyGroup>
```
###### Connection Refused Err
![image](https://cloud.githubusercontent.com/assets/4823412/11304124/cb9da648-8f63-11e5-961a-ea5b94f1660b.png)

### My Question(s)
When I upgraded to beta8 there was a [VS upgrade](https://www.microsoft.com/en-us/download/details.aspx?id=49442).  I assumed that the [windows install](http://docs.asp.net/en/latest/getting-started/installing-on-windows.html)  during the RC1 upgrade  contained a similar link with step two.  Is that the correct assumption?  Should I do something else to properly upgrade to RC1 from Beta8?

   
### Tech Details
I am using .NET Version Manager v1.0.0-rc2-15545

Here are my runtimes (I have run `dnvm use TJsBuild`, `dnvm use rc1`, and `dnvm use 1.0.0-rc1` for testing)
```
Active Version         Runtime Architecture OperatingSystem Alias
------ -------         ------- ------------ --------------- -----
                       rc1     rc1          rc1             1.0.0-rc1-final (missing)
       1.0.0-beta4     clr     x86          win             beta4
       1.0.0-beta5     clr     x64          win
       1.0.0-beta5     clr     x86          win
       1.0.0-beta5     coreclr x64          win
       1.0.0-beta5     coreclr x86          win
       1.0.0-beta8     clr     x64          win             TJsBuild
       1.0.0-beta8     clr     x86          win             default
       1.0.0-beta8     coreclr x64          win
       1.0.0-beta8     coreclr x86          win             TJsCoreBuild
       1.0.0-rc1-final clr     x64          win             rc1
       1.0.0-rc1-final clr     x86          win             1.0.0-rc1
       1.0.0-rc1-final coreclr x64          win
       1.0.0-rc1-final coreclr x86          win
```

I am on a win 10 machine using VS 2015 enterprise.

**Comment by Kagamine** [comment]
What's your global.json

**Comment by TJSoftware** [comment]
When I create a new project without doing anything else the global json is ...

```
{
  "projects": [ "src", "test" ],
  "sdk": {
    "version": "1.0.0-rc1-final"
  }
}
```

After I set the beta8/rc1 version in the project application properties dropdown (seem image below), it appropriately updates the version to either  `"version": "1.0.0-beta8"` or `"version": "1.0.0-rc1-final"`.

[I uploaded what I have.](https://github.com/TJSoftware/WebApplication3)

![image](https://cloud.githubusercontent.com/assets/4823412/11340504/61e9e6bc-91bb-11e5-99a2-fe0bd0871982.png)

**Comment by GuardRex** [comment]
@TJSoftware You did this one, right? https://get.asp.net/OtherDownloads

**Comment by TJSoftware** [comment]
@GuardRex I actually followed the steps on http://docs.asp.net/en/latest/getting-started/installing-on-windows.html, it contains the same commands.

**Comment by GuardRex** [comment]
@TJSoftware Cool. Just making sure b/c one symptom of not running the installer is that IIS Express will not show up. The installer includes a VS upgrade.

**Comment by GuardRex** [comment]
@TJSoftware If you want to make sure on the version, check the About VS dialog and look for "ASP.NET and Web Tools 2015 (RC) 14.1.11116.0" in the list (at least that's what I show here).

**Comment by TJSoftware** [comment]
I ran yours just in case and that did the trick.  I took a closer look at the commands and there is a difference.

###### What I ran
@powershell -NoProfile -ExecutionPolicy unrestricted -Command "&{$Branch='dev';iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.ps1'))}"

###### Your link
@powershell -NoProfile -ExecutionPolicy unrestricted -Command "&{iex ((new-object net.webclient).DownloadString('https://dist.asp.net/dnvm/dnvminstall.ps1'))}"

**Comment by GuardRex** [comment]
For anyone else finding this issue, the installer for RC1 can be found here:

https://go.microsoft.com/fwlink/?LinkId=627627

**Comment by TJSoftware** [comment]
I ran the exe from your link and now my new projects do not have the IIS Express option again.  I tried running the new powershell command and going through all the upgrade options.  I am still back at the start where I first described my issue.

**Comment by GuardRex** [comment]
@TJSoftware I don't see an active runtime there.
```
dnvm use {runtime_here} -r {<core>clr} -arch {x64/x86} -p
```
... then you can update the default if you need to. I don't know if that's the only issue here.

**Comment by TJSoftware** [comment]
@GuardRex I removed the astrix for github formatting.

**Comment by GuardRex** [comment]
@TJSoftware Ah, I see. I sort of think that part of the problem was that you followed PS steps but the installer handles the complete install. I still think there should be a section that states explicitly "Upgrading from prior versions of .NET 5" to keep folks on the right path. MS team will step in now; but if it were me, I'd scrap VS and .dnx and perform a clean install. However, I'm fairly certain they'll have a less drastic approach to get things going again.

**Comment by TJSoftware** [comment]
I GOT IT!!!.   I needed to run `dnvm use rc1 -p` to make the environment persistant.

**Comment by GuardRex** [comment]
@TJSoftware Cool!!!!

"Oh! My horoscope said I'd be useful to somebody today." - Organon (Geoffrey Bayldon), Dr. Who: [The Creature from the Pit](https://en.wikipedia.org/wiki/The_Creature_from_the_Pit), 1979

**Comment by TJSoftware** [comment]
Mine would have to be ...

http://paisleychick.org/fun/32.html

Chewbacca is a dependable creature but he can tend to be stubborn. He likes material possessions and loves to win at games. He tends to hate being bossed around or losing and he may succomb to his physical strength when upset.

That fits every Taurus I know.

**Comment by TJSoftware** [comment]
I think my original issue may have stemmed from me playing with the alias settings and not from upgrading to RC1.  If you see something similar to what I saw, where you have a runtime "missing", you may have mucked up an alias.  In my case I think VS may have been defaulting to the alias that I did not have a runtime associated for, as well as not having a persisted environment.

Here are two ways to delete your alias.
1.  Delete the text file from `C:\Users\{your profile}\.dnx\alias`
2. `dnvm alias -d {aliasnamehere}`
