### ISSUE TITLE
How to replace AppDomain.CurrentDomain.BaseDirectory with Core CLR

### ISSUE THREAD

**Issue by scottaddie** [aspnet/Home#1107]
I'm working on porting an ASP.NET MVC 5 application over to MVC 6. I'd like this to run on Core CLR; however, I'm not finding a replacement for the `AppDomain.CurrentDomain.BaseDirectory` property I had access to in .NET 4.5. I know that IHostingEnvironment's `WebRootPath` property gives me the web root folder's path; however, I want the folder path level above that. Any ideas?

**Comment by davidfowl** [comment]
IApplicationEnvironment.ApplicationBasePath

**Comment by smbecker** [comment]
@scottaddie, use IApplicationEnvironment.ApplicationBasePath

https://github.com/aspnet/dnx/blob/dev/src/Microsoft.Extensions.PlatformAbstractions/IApplicationEnvironment.cs#L26

**Comment by scottaddie** [comment]
Thank you for the quick response! Closing this now.

**Comment by kriscoleman** [comment]
FYI, IApplicationEnvironment is gone now 

https://github.com/aspnet/Home/issues/1107

**Comment by smbecker** [comment]
I've come to discover a more direct replacement in [AppContext.BaseDirectory](https://msdn.microsoft.com/en-us/library/system.appcontext.basedirectory(v=vs.110).aspx).

**Comment by kriscoleman** [comment]
Yea, that works for just about everything except for when I try to find the root directory from inside a .netcore web project

**Comment by smbecker** [comment]
For that you can use [IHostingEnvironment](microsoft.aspnetcore.hosting.ihostingenvironment)
