### ISSUE TITLE
Better feedback for unresolved dependencies

### ISSUE THREAD

**Issue by atrauzzi** [aspnet/Home#1108]
Just trying to get a project working and as soon as I added my first dependency, even though vscode was able to infer it, `dnu list` tells me that the dependency is unresolved.  Unfortunately, at no point does it fail or say why.

It might be nice to have somewhere to get a summary of why certain packages didn't install.  Moreover, wouldn't it make more sense if a package failed to install, that `dnu restore` itself would fail?

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
