### ISSUE TITLE
RC1 OmniSharp cannot find runtime

### ISSUE THREAD

**Issue by epignosisx** [aspnet/Home#1109]
I'm trying to install ASP.NET 5 RC1 in a clean upgrade of El Capital. I installed VS Code latest (0.10.1), installed ASP.NET from get.asp.net, installed latest mono (4.2.1.102), installed the ASP.NET yo generator.

After creating a console app with the aspnet generator and opening the project with VS Code I'm getting the following error from OmniSharp:

![screen shot 2015-11-21 at 8 08 37 pm](https://cloud.githubusercontent.com/assets/697377/11321393/cf30a1ba-908b-11e5-8e12-3e0e86f5fea2.png)

Effectively if I go to the paths Omnisharp is searching they are empty:

![screen shot 2015-11-21 at 8 13 29 pm](https://cloud.githubusercontent.com/assets/697377/11321404/5eff8c20-908c-11e5-9143-30f683adf965.png)

dnvm list output:

![screen shot 2015-11-21 at 8 08 59 pm](https://cloud.githubusercontent.com/assets/697377/11321394/e4883f0a-908b-11e5-9edf-a2b0af06fdaf.png)

This is what I have in PATH:

![screen shot 2015-11-21 at 8 14 58 pm](https://cloud.githubusercontent.com/assets/697377/11321413/a6010658-908c-11e5-8b82-62dee6930f4e.png)

When I go to that location I see the runtimes:

![screen shot 2015-11-21 at 8 17 53 pm](https://cloud.githubusercontent.com/assets/697377/11321427/04998d70-908d-11e5-851c-250dfbe1e5a7.png)

What's going on with my installation?

**Comment by rhires** [comment]
Hmmm...no access to `./packages` huh? Are the permissions for each of the directories the same? `ls -l $HOME/.dnx` should show the directories' permissions, and they ought to be the same `drwxr-xr-x` (at least, this is what I've gone on my Mac). It's been a while since I did a fresh install.

**Comment by BrennanConroy** [comment]
See https://github.com/aspnet/Home/issues/1094

**Comment by epignosisx** [comment]
@BrennanConroy Just like that issue my user's .dnx folder had root:

![screen shot 2015-11-22 at 1 06 44 am](https://cloud.githubusercontent.com/assets/697377/11322400/90b49eec-90b7-11e5-89e3-699d733aa848.png)

after updating it, I'm able to run:

    dnu restore
    dnu build
    dnx HelloWorld

and the program executes, however I keep getting the same OmniSharp error.

**Comment by BrennanConroy** [comment]
Looks like OmniSharp doesn't know about the global dnx install location. You should file a bug on https://github.com/OmniSharp/omnisharp-roslyn
You can solve it by putting runtimes in the ~/.dnx/runtimes folder for now

**Comment by epignosisx** [comment]
Thanks @BrennanConroy I'll do that.
