### ISSUE TITLE
Microsoft.Net.Http.Server.WebListenerException: Invalid access to memory location (Windows IOT)

### ISSUE THREAD

**Issue by matizk144** [aspnet/Home#1110]
I compiled and run "empty" ASP.NET project on my RP2 (Windows IOT) - Hello World using Weblistener.
Unfortunatelly on some HTTP GET weblistener throw exception:

```
fail: Microsoft.Net.Http.Server.WebListener[0]
      GetContextAsync
      Microsoft.Net.Http.Server.WebListenerException: Invalid access to memory location
         at Microsoft.Net.Http.Server.WebListener.GetContextAsync()
fail: Microsoft.AspNet.Server.WebListener.MessagePump[0]
      ListenForNextRequestAsync
      Microsoft.Net.Http.Server.WebListenerException: Invalid access to memory location
         at Microsoft.Net.Http.Server.WebListener.GetContextAsync()
         at Microsoft.AspNet.Server.WebListener.MessagePump.<ProcessRequestsWorker>d__22.MoveNext()
```

After that, dnx proces still working, but weblistener no response on next requests,

Situation appers after few correct GETs.

**Comment by Eilon** [comment]
@Tratcher any ideas?

**Comment by Tratcher** [comment]
@moozzyk also saw this: https://github.com/aspnet/WebListener/issues/126 (private). We haven't tried to debug it yet.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
