### ISSUE TITLE
Suggest: The "Template" property of RouteAttribute has default value [String.Empty]

### ISSUE THREAD

**Issue by Tiscs** [aspnet/Home#1112]
That's useful when Developers want to define root controller or default action like sample codes below.

```CSharp
[Route("")] // [Route] is much better.
public class HomeController : Controller
{
    [Route("")] // [Route] is much better, or [HttpGet]
    public IActionResult Index()
    {
        return View();
    }
}
```

**Comment by Eilon** [comment]
The idea of requiring an explicit template for the `Route` attribute is that it's needed 99.999% of the time (seriously!). With rare exceptions, there can be only one action in the whole app that can use the empty `""` route. So the idea here is that for the sake of usability, forcing specifying a route (even if it's empty) will lead to fewer errors and mistakes.

In other words, only the one "empty" route in the whole app will be "ugly", and all other routes will look fine. And the API requirements lead you to success in all cases.

Thoughts?

**Comment by Tiscs** [comment]
@Eilon Thanks for your response and I'm agree that, most of ``` [Route] ``` attribute will use NOTEMPTY template.
Thanks.
