### ISSUE TITLE
Can't publish ASP.NET 5 project with external library reference

### ISSUE THREAD

**Issue by vivanov1410** [aspnet/Home#1113]
I have included an external reference of Moneris library eSELECTplus_dotNet_API.dll to my ASP.NET 5 RC1 project. It wrapped it alright and I can build project and run it using Kestrel. But when I publish it from VS or command line I got following error:

```
The package ID 'eSELECTplus_dotNet_API' contains invalid characters. Examples of valid package IDs include 'MyPackage' and 'MyPackage.Sample'.
```

I tried to rename library to a better name to fit nuget specs and it worked so I can publish it. But now when I run my project I got runtime error saying following:

```
System.IO.FileNotFoundException : Could not load file or assembly 'eSELECTplus_dotNet_API, Version=2.5.3.0, Culture=neutral, PublicKeyToken=8cb9cd598f87e276' or one of its dependencies. The system cannot find the file specified.
```

When I renamed wrap project folder to "eSELECTplus.dotNet" my file name was still "eSELECTplus_dotNet_API.dll"

**Comment by marwa-ahmad** [comment]
I had the same problem, I've solved it by installing  a nuget package: 
eSELECTplus_dotNet_API
eSELECTplus_dotNet_API-US

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
