### ISSUE TITLE
Class library for ASP.NET 5

### ISSUE THREAD

**Issue by pantonis** [aspnet/Home#1114]
Hi,

How do I add a class library project reference into my ASP.NET 5 web app?
The reason that I need this is that I have infrastructure libraries that are being used by windows services as well  and I would like to use them in ASP.NET project

Thanks

**Comment by Eilon** [comment]
@pantonis you can use the `Class Library (Package)` project type to create a project.json-based project. But either way, you can right-click on the `References` node in your project and add a project reference to any other project you want and VS should just do the right thing.

**Comment by pantonis** [comment]
As I have mentioned these libraries are being used in several windows services (.Net 4.6) so I want be able to use them there if I create Class Library (package)
I have tried adding the .net 4.6 library reference to the ASP.NET 5 project but I get an error

**Comment by Eilon** [comment]
Can you show the error you're getting?

BTW Class Library (Package) can be used from any other project type because it generates NuGet packages, and all other project types can use NuGet packages.

**Comment by pantonis** [comment]
![image](https://cloud.githubusercontent.com/assets/3295086/11330342/aea88886-91b2-11e5-8a21-52efc9bbe4db.png)

**Comment by pantonis** [comment]
I have also tried the other thing that you suggested. Created a windows Service and a Class library (Package). Tried to reference the Class library (Package) project into the windows service and I get:

![image](https://cloud.githubusercontent.com/assets/3295086/11330375/233f5aee-91b3-11e5-9262-9b66ed89c35e.png)

**Comment by davidfowl** [comment]
If your project is dnx451 then it can't references net46 project. Can you show a sample repository or project layout

**Comment by pantonis** [comment]
It is dnx4.6. If it cannot they what is the solution to have shared class libraries with a window service?

**Comment by pantonis** [comment]
You were right. project was dnx451.Changed it to dnx46. Don't know why though because I selected .NET 4.6 while I was creating it.
