### ISSUE TITLE
RC1 - Dnu Publish fails, 'npm' is not recognized as an internal or external command.

### ISSUE THREAD

**Issue by dazinator** [aspnet/Home#1117]
I have installed VS2015 Community, included `NodeJS` in the installation options, and also installed ASP.NET 5 RC 1.

After the VS install, I noticed that the following was added to my `PATH`: C:\Users[username]\AppData\Roaming\npm

This npm folder doesn't actually exist on disk though.

I opened VS and created a new empty ASP.NET 5 project. I then opened a command prompt in the project directory and did a `dnu publish` - and it fails with the following:

```
Microsoft .NET Development Utility Clr-x86-1.0.0-rc1-16202

Executing script 'prepublish' in project.json
'npm' is not recognized as an internal or external command,
operable program or batch file.
The 'prepublish' script failed with status code 1.
```

My issue is, I would expect `dnu publish` to work for a new ASP.NET 5 project, following a clean installation. NPM seems to have been installed to C:\Program Files\nodejs\ but not added to the path. Shouldn't it be added?

~~Also a clarification over why`C:\Users\[username]\AppData\Roaming\npm` is added to the PATH (i.e what is that folder used for?) would be really helpful!~~

Thanks

**Comment by Jeffiy** [comment]
Try add `C:\Program Files\nodejs\`(the npm install path) to your `PATH`.

**Comment by dazinator** [comment]
@Jeffiy - as per what I mentioned before:

> NPM seems to have been installed to C:\Program Files\nodejs\ but not added to the path. Shouldn't it be added?

Adding it to the PATH does solve the problem - but my issue really is that shouldn't the installation of NodeJs (as part of the VS install) do this for you?

**Comment by dazinator** [comment]
Ok - I have figured out that `C:\Users[username]\AppData\Roaming\npm` is added to the path because this is where global `npm` packages are placed - i.e `npm install [packagename] -g`

This makes sense as I am guessing many global packages are often command line tools. However it doesn't make sense to me that NPM itself is not added to the PATH is this is a requirement to install those in the first place so you would definately also want that on the PATH too..

**Comment by idg10** [comment]
What's weird is that I encountered this problem when publishing to a *2nd* website. The first went fine, but when I added a second, I started seeing this error.

Of course, I can't say for certain that something else in my environment didn't change between the time when publishing to the 1st Azure Web app worked, and publishing to the 2nd didn't. (Around a week elapsed.)

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
