### ISSUE TITLE
ASP.NET Class Library (package) - content support

### ISSUE THREAD

**Issue by lszomoru** [aspnet/Home#1118]
Does the ASP.NET class library support content as I have some static files (images, Views, JavaScript files, etc.) that I would like to include in my package? I have tried both "content", and "contentFiles" in the project.json but the files are not being included in the package that is being generated by the build. Am I missing something obvious? Thanks!

**Comment by Jeffiy** [comment]
You can put them in "wwwroot" folder. follow this [static files](https://docs.asp.net/en/latest/fundamentals/static-files.html)

**Comment by lszomoru** [comment]
Thanks! Are you saying that I should create a wwwroot directory in the class library and put my static files in there? Does this mean that when I reference the class library from an ASP.NET website the contents of the wwwroot from the class library will be copied to the wwwroot folder of the ASP.NET website?

**Comment by Jeffiy** [comment]
I'm not sure about that, oops, I just thought you said ASP.NET website.

**Comment by lszomoru** [comment]
No worries. I am closing this issue as duplicate of https://github.com/aspnet/Home/issues/651.
