### ISSUE TITLE
Servers Wiki Page Recommends Deprecated Technology Without Qualifying It

### ISSUE THREAD

**Issue by sjdixon** [aspnet/Home#1119]
The Servers Wiki page says that the Microsoft team uses Microsoft.AspNet.Loader.IIS (Helios) for hosting ASP.Net 5 applications on IIS.

However, announcement 69 says that the team is discontinuing the Helios IIS host as of beta 8. 

A wiki page should be careful when suggesting that people rely on a deprecated module. Perhaps some ideas could be added to that page to tell people using beta8 not to use Microsoft.AspNet.Loader.IIS, and suggest a different approach (assuming that is what we're supposed to do now)? 

Servers Wiki Page:
https://github.com/aspnet/Home/wiki/Servers

Announcement 69:
https://github.com/aspnet/Announcements/issues/69

**Comment by GuardRex** [comment]
@sjdixon This was just due to an overworked (!!!!) documentation staff. cc: @Rick-Anderson

**Comment by Rick-Anderson** [comment]
@Eilon what's the process to update https://github.com/aspnet/Home/wiki/Servers?

**Comment by Eilon** [comment]
@Tratcher can you update the wiki?

**Comment by Tratcher** [comment]
Updated.

**Comment by sjdixon** [comment]
Thanks, you guys rule!
