### ISSUE TITLE
Incorrect instructions on DNX page

### ISSUE THREAD

**Issue by bob-devereux-zocdoc** [aspnet/Home#1120]
At the bottom of this page

https://github.com/aspnet/Home/wiki/DNX-utility

it reads

"...Use "dnu help [command]" for more..."

it should read 

"Use "dnu [command] --help" for more"

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
