### ISSUE TITLE
Latest version of MVC6 not available

### ISSUE THREAD

**Issue by justsayno** [aspnet/Home#1121]
Hi I just upgraded to the Update 1 version of Visual Studio 2015 and I notice that in your samples you have the new RC1 version of MV6 but the template still builds with all the beta5 packages... Do I just manually copy what you have in your samples for HelloMVC or am I doing something wrong?

Just getting started on a project and would like to start with RC1 rather than the betas.

**Comment by Chrissx** [comment]
Hi,
I needs to install new RC1 template package. Follow the instructions:

https://docs.asp.net/en/latest/getting-started/installing-on-windows.html#install-asp-net-5-with-visual-studio

**Comment by justsayno** [comment]
Thank you! I knew I was just missing something but my google foo did not get me to those articles.
