### ISSUE TITLE
RC1 installer for Mac overrides ~/.profile with ~/.bash_profile

### ISSUE THREAD

**Issue by SteveSandersonMS** [aspnet/Home#1123]
_Apologies if this is posted in the wrong place - not sure which repo relates to the Mac installer package._

Just installed ASP.NET 5 RC1 on a Mac and accepted the default option to configure itself in `~/.bash_profile`. Unfortunately, the presence of a `~/.bash_profile`, at least on Yosemite, means that `Terminal.app` no longer loads the `~/.profile` file, which meant I lost all my other terminal config.

The manual fix is easy enough (move the line from `~/.bash_profile` into `~/.profile`, then delete `~/.bash_profile`) but it would be nice if the installer could avoid creating `~/.bash_profile` if it doesn't exist, and instead register itself in `~/.profile`.

It looks like `dnvminstall.sh` already accounts for this, and it's just `DNX-1.0.0-rc1-final.pkg` that does not.

**Comment by Eilon** [comment]
@BrennanConroy @glennc ?

**Comment by miguellira** [comment]
@SteveSandersonMS Ran into similar issue with `~/.bashrc`.

According to the bash manual the order of preference is: `~/.bash_profile` then `~/.bash_login` then `~/.profile`.

My solution was to source one from the other. You can add this to your `~/bash_profile`:

```console
source ~/.profile
```

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
