### ISSUE TITLE
Two web hosting threads started when debugging default web application

### ISSUE THREAD

**Issue by SaphuA** [aspnet/Home#1124]
Issue started after upgrading tooling, dnvm and dnx to ASP.NET RC1. I'm using VS2015 without the RC of update 1.

**How to reproduce**
- File > New > Project... > ASP.NET Web Application > Web Application
- Modify the Index method of the HomeController:
  
  ```
  public IActionResult Index()
  {
      Debug.WriteLine("Foo");
      return View();
  }
  ```
- Start debugging in IIS Express
- **'Foo' is printed twice!**

**The cause / a temporary fix**
- Project Properties > Debug > Deselect **'Launch URL'**

**Comment by Tratcher** [comment]
This is a known tooling behavior. When you press F5 it needs to send a DEBUG request to start the web site and attach to it. We're investigating how to best prevent that request from getting into user code.  You won't see this happen with ctl+F5.
cc: @BillHiebert.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
