### ISSUE TITLE
docfx?

### ISSUE THREAD

**Issue by simonmurdock** [aspnet/Home#1125]
hi

I have been searching for days to find a nice documentation solution and eventually stumbled across docfx. I didn't even know of it's existence. It's never talked about.

Are there any plans to have this highlighted, or to improve the help pages for its github/open up the repo to see some examples of how to implement a structure like you guys have done?

Having a bit of a nightmare getting much sense out of it so far.

.net apps are struggling for documentation that looks awesome, and this tool does a great job.

**Comment by Eilon** [comment]
@danroth27 @chenkennt

**Comment by chenkennt** [comment]
docfx is a new tool we're developing as the documentation solution for .NET world. Currently [.NET Core documentation](http://dotnet.github.io) is generated by docfx. You can get some tutorials for docfx at our [official site](http://aspnet.github.io/docfx). The source code of docfx is going to open source soon, you should be able to get more information by then.

**Comment by simonmurdock** [comment]
Yea that would be great, there are however two confusing things:

What's the difference between the "projects" & "metadata" collections in docfx.json?

Do I need a TOC.yaml at multiple places in my hierarchy of articles, or just one at the root?

**Comment by simonmurdock** [comment]
Spent another half day trying to figure out which version is the correct one to use, the downloaded one from the site or the one from nuget, both have different formats and produce different results.

**Comment by chenkennt** [comment]
Sorry docfx is still under a development phase and not really ready for public use. But if you want to try it out, I'd recommend you to use:
1. For exe version, download he one from our [site](http://aspnet.github.io/docfx/tutorial/artifacts/docfx.zip).
2. For dnx version, install from [nuget](https://www.nuget.org/packages/docfx/1.0.0).

We have created a sample [site](https://github.com/docascode/docfx-seed) to help you get started.

**Comment by simonmurdock** [comment]
brilliant, thank you
