### ISSUE TITLE
Nuget and DNU not working properly with Asp5-Mvc6

### ISSUE THREAD

**Issue by hknielsen** [aspnet/Home#1127]
http://stackoverflow.com/questions/33919834/nuget-not-working-properly-with-asp5-mvc6

Cant fint any issue creater for Nuget

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
