### ISSUE TITLE
(rc1/rc2-16237) DNX/DNU not working on RHEL 7.1

### ISSUE THREAD

**Issue by nguyenm100** [aspnet/Home#1128]
Am able to install components through DNVM but DNX/DNU goes dark.

running: export DNX_TRACE=1&&dnx

produces: 
Loaded module: dnx.coreclr.so
Found export: CallApplicationMain

Unhandled Exception: 
   Cannot print exception string because Exception.ToString() failed.
Aborted

---

Please produce a Redhat version.  Larger companies (enterprise) will want to use a linux that is commercially supported.

**Comment by moozzyk** [comment]
Unfortunately Redhat based distros are not supported in RC1 (this particular error occurs because the version of libicu CoreClr was compiled against was not found.). As per this [comment](https://github.com/aspnet/Docs/pull/642#issuecomment-157175418) Redhat should be enabled in a future release.

**Comment by nguyenm100** [comment]
fwiw:

if I run dnx in unprivilege mode, I get error code 134
if I run dnx under sudo, error code is 0

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
