### ISSUE TITLE
ASP.NET 5 RC1 DNU Restore Fail 

### ISSUE THREAD

**Issue by lokinfey** [aspnet/Home#1129]
I try to use dnu restore for my project . I know they go to nuget , but failed !!

![Uploading 无标题.jpg…]()

I don't know why ?

**Comment by Jeffiy** [comment]
The image didn't upload successfully, just put the errors here if possible.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
