### ISSUE TITLE
Thank you for your hard work on .NET 5

### ISSUE THREAD

**Issue by developer1998** [aspnet/Home#1130]
On this Thanksgiving, I want to thank you guys for your hard work on .NET 5 and to all the contributors. Thank you for re-writing it from ground up, for making it open source and cross platform, all the features, and for the great support right on github.
You are much appreciated.

All the best, happy coding:)

**Comment by rhires** [comment]
I would like to echo this sentiment. I’m having a lot of fun doing all of this, using this really wonderful technology.

Cheers!

**Comment by joeaudette** [comment]
I second that emotion. Happy Thanksgiving to all the people working on ASP.NET 5 and related frameworks and tooling!

I am Thankful for all the great work you guys are doing and this great new framework and the possibilities it brings. Having it all open source and developed in public has been great and amazing to watch the process unfold. I feel like my own code is improving as I learn new paradigms and techniques from the framework code.

Hope you are all enjoying time off with your friends and families today!

**Comment by GuardRex** [comment]
:chicken: :poultry_leg: :chicken: :poultry_leg: :chicken: :poultry_leg: :chicken: :poultry_leg: :chicken: :poultry_leg: :chicken: :poultry_leg: :chicken: :poultry_leg: :chicken: :poultry_leg: :chicken: :poultry_leg: :chicken: :poultry_leg: :chicken:

Happy T-Bird Day to the .NET 5 teams! **_Thank you for making .NET GREAT!_**

:chicken: :poultry_leg: :chicken: :poultry_leg: :chicken: :poultry_leg: :chicken: :poultry_leg: :chicken: :poultry_leg: :chicken: :poultry_leg: :chicken: :poultry_leg: :chicken: :poultry_leg: :chicken: :poultry_leg: :chicken: :poultry_leg: :chicken:

**Comment by Schlurcher** [comment]
A big thanks from me also! I really love the way you guys embraced open source to push ASP.NET to other platforms. Helps a lot with my learning efforts, too.

**Comment by abhiongithub** [comment]
Big Thanks Guys..

**Comment by klaygomes** [comment]
I' so pride to be an early adopter of yours tremendous work, you are great guys many thanks keep going :)

**Comment by Eilon** [comment]
It's the great feedback that we get from you, the community, that helps us shape this project. And lots of great pull requests, issues, and discussions. And perf fixes, and documentation, and blog posts. And videos, presentations, and so much more!

We have a hard-working group of people here at Microsoft: the ASP.NET, CLR, .NET, Roslyn, Identity, Application Insights, and so many other teams.

So here's an official **Thank You** from Microsoft to everyone in the ASP.NET community!
