### ISSUE TITLE
My logs will get filled over the top soon with logs from framework components after RC1 upgrade

### ISSUE THREAD

**Issue by Rinsen** [aspnet/Home#1131]
Hi!

I have followed your directions when I implemented my logging and when I now updated to RC1 I get a lot of logs coming from the framework parts when I filter on Information level.

Examples:
Microsoft.AspNet.Mvc.Infrastructure.MvcRouteHandler Executed action "Rinsen.Web.Areas.Controllers.Example.GetLatestLogs" in 0.0093ms
Microsoft.AspNet.Hosting.Internal.HostingEngine Request finished in 0,014ms 200 application/json; charset=utf-8
Microsoft.AspNet.Hosting.Internal.HostingEngine Request starting HTTP/1.1 GET https://localhost:44319/webapi/GetLatest
And so on...

Information level
"Track the general flow of the application using logs at the Information level. These logs should have value in the long term."
https://github.com/aspnet/Logging/wiki/Guidelines

This will not give me any value at all in the long term and should probably be on debug level?

And if not the guidelines is really wrong :)

**Comment by rynowak** [comment]
Logging statements like the request starting/ending and what MVC action was invoked really do have value in the long term. Without that data how would you put any other log entries into context?

**Comment by Rinsen** [comment]
I may have the wrong idea about what the purpose of this logging is.

In Production I use this logging to log all errors and important events that happens in the system and some of these events I have added on Information level because I have done so earlier.

I do not log any information related to any "normal" requests because that does not give me any more value then the logs I already get from IIS request logging.
Similar to the information logging example in the guidelines
"examples: user JohnDoe created an account, an entry was added to the User database"
https://github.com/aspnet/Logging/wiki/Guidelines

And when things go bad and I log an error I add this type of information to one log item so I do not need to look in multiple log items to understand what did go wrong and why and I do not have the need to find the relations between log items. I also have this logs in a database store to make it easy to Query and analyze all logs without having to build a complicated log file analyzer. But it will get very expensive very fast to log on this detailed level on every request to a database.

The story is of course different when I do development, testing or try to do some investigation. In these cases I change the log level to Debug or Verbose to get the more information in the console or a text file or to my database store if it is in production.

I could of course fix this with a more advanced filter in my logger or start log all my production logging at a higher level or build my own log for important but not dangerous events if I have misused this log. 

So I need some guidance to find the right direction of my future work and investments :)

**Comment by Eilon** [comment]
Ah, interesting. One thing to think about logging is that "everything is fine until all of a sudden it isn't." So the "noisy" log messages aren't deemed as noise if the request fails half way through - they could provide important information about what things happened just prior to the failure. Sometimes the failure has enough self-contained info to figure out what was wrong, but certainly not always.

Does that change your view on what to log?

**Comment by Rinsen** [comment]
I absolutely agree that the logs will provide valuable and important information when things go bad, and that will for sure happen at times! But I have a hard time to see the value in logging information from all my requests, most of them will be json based api requests gathering some data for use in apps and will have a very low fail rate but there can of course be some strange cache misses or what do I know going on :)

In a dream world I would like to gather all this information in the request context in some way and then be able to send it for logging when things go bad and not before that so I get them when I need them and not at any other point. The memory that would consume on each request would not be a problem for me at least now.

But is there any easy way in the current implementation to trace all logs in a single request with some Id? Because it will be really hard to know what logs are related when you have a lot of requests to different APIs at the same time.

I had a quick look at scopes earlier but got a bit scared of them from the documentation so I did not try to implement anything based on that but I guess that is some kind of request id trace thing.

"Scopes are not required, and should be used sparingly, if at all. They’re best used for operations that have a distinct beginning and end, such as a transaction involving multiple resources."
http://docs.asp.net/en/latest/fundamentals/logging.html

Today I am using a global ExceptionFilterAttibute with the following implementation that gather user information and some request information when needed for logging. I have only good experiences with this kind of logging in the past in MVC3-5. It is very simple and gives a lot of concentrated information. But is this considered bad in some way from your point? 

Sorry for including a big chunk of code.
```
public class AppExceptionFilter : ExceptionFilterAttribute
{
    public override void OnException(ExceptionContext context)
    {
    var logger = (ILogger<AppExceptionFilter>)context.HttpContext.ApplicationServices.GetService(typeof(ILogger<AppExceptionFilter>));
    if (context.ActionDescriptor.ReturnTypeIsIJsonStatus())
    {
        var jsonStatusForExceptions = new JsonStatusForExceptions();
        jsonStatusForExceptions.Status = Status.UnhandledException;
        context.Result = new JsonResult(jsonStatusForExceptions);
    }
    else
    {
        context.Result = new RedirectToActionResult("Index", "Error", new Dictionary<string, object>() { { "Message", "Unhandled exception" } });
    }
    var requestInfoBuilder = new StringBuilder();
    if (context.HttpContext.User.Identity.IsAuthenticated)
    {
        if (context.HttpContext.User.HasClaim(m => m.Type == "UserId"))
                    requestInfoBuilder.AppendFormat("UserId: {0},", context.HttpContext.User.Claims.First(m => m.Type == "UserId").Value);
    }
    else
    {
        requestInfoBuilder.Append("Anonymous user,");
    }
    if (context.RouteData.Values.Any(m => m.Key == "controller"))
    {
        requestInfoBuilder.Append(context.RouteData.Values.First(m => m.Key == "controller"));
    }
    if (context.RouteData.Values.Any(m => m.Key == "action"))
    {
        requestInfoBuilder.Append(context.RouteData.Values.First(m => m.Key == "action"));
    }
    logger.LogError(requestInfoBuilder.ToString(), context.Exception);
    }
}
```
And thanks for all the good feedback, it is appreciated!

**Comment by Eilon** [comment]
The per-request scope has the request correlation id on it - you could probably use that.

You could probably prototype something to try it out. Build a custom `ILoggerProvider` and ultimately delegates all its logging information to a "real" logger. But what this custom logging system would do is defer writing the logs for a scope until the scope ends (its scope is disposed) and write the logs out only if there was a Critical/Error/Warning log entry within that scope. Not sure how well that would actually work but it seems like it might.

Another thing to consider is that any reasonably advanced logging system will dump all its logs to some central store, and then presumably archive or delete any "uninteresting" log entries. For example, it could use the same correlation information to bulk delete all successful requests that took place >7 days ago or something like that.

**Comment by Rinsen** [comment]
That`s a very interesting idea, that could actually work pretty good :) I will do some prototyping and see how it works out.

And yes, that is very much needed, my prototype have already run out of storage some times because of logging... :) But at this point it is a prototype with very limited space that has no real users... except me that gets a bit annoyed and that`s the reason for this issue :) 

I will close this issue and with some good luck the scope logger could work out just fine, and if not I will write a fancy filter that gives me what I want :)

Thanks for an awesome upgrade from MVC 5, it is a pleasure to work with when comparing :)
