### ISSUE TITLE
Dependency fx/System.Net.Http.Formatting could not be resolved

### ISSUE THREAD

**Issue by damienpontifex** [aspnet/Home#1132]
When including the IoT SDK package Microsoft.Azure.Devices which has dependencies on Microsoft.AspNet.WebApi.Client (≥ 5.2.3)
Microsoft.AspNet.WebApi.Core (≥ 5.2.3)

Building from VS2015 and in VSO and using 1.0.0-rc1-final I get the error:

"error NU1001: The dependency fx/System.Net.Http.Formatting could not be resolved."

What is the fx/System.Net.Http package?

Could this be something to do with including WebAPI packages as above in aspnet 5 project? Or another problem...?

**Comment by nikolaschou** [comment]
I have the same error.

**Comment by damienpontifex** [comment]
We are again having this issue on a new developer's machine. Any insights from the Azure devices team?

**Comment by davidfowl** [comment]
The package appears to be authored incorrectly. It works in csproj because adding references that already exist no-op (it's a fluke). The package has a framework assembly reference on **System.Net.Http.Formatting** but that assembly is not a framework assembly so it can't be resolved in a DNX project.

Here's the nuspec:

```XML
<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd">
  <metadata>
    <id>Microsoft.Azure.Devices</id>
    <version>1.0.4</version>
    <title>Microsoft Azure IoT Service SDK</title>
    <requireLicenseAcceptance>true</requireLicenseAcceptance>
    <authors>Microsoft</authors>
    <owners>Microsoft</owners>
    <licenseUrl>https://github.com/Azure/azure-iot-sdks/blob/master/LICENSE</licenseUrl>
    <iconUrl>http://go.microsoft.com/fwlink/?LinkID=288890</iconUrl>
    <description>Service SDK for Azure IoT Devices</description>
    <language>en-US</language>
    <dependencies>
      <dependency id="Microsoft.AspNet.WebApi.Client" version="5.2.3" />
      <dependency id="Microsoft.AspNet.WebApi.Core" version="5.2.3" />
      <dependency id="Microsoft.Azure.Amqp" version="1.0.0" />
    </dependencies>
    <frameworkAssemblies>
      <frameworkAssembly assemblyName="System.Core" targetFramework=".NETFramework4.5.1" />
      <frameworkAssembly assemblyName="System.Net.Http" targetFramework=".NETFramework4.5.1" />
      <frameworkAssembly assemblyName="System.Net.Http.Formatting" targetFramework=".NETFramework4.5.1" />
      <frameworkAssembly assemblyName="System.Runtime.Serialization" targetFramework=".NETFramework4.5.1" />
      <frameworkAssembly assemblyName="System" targetFramework=".NETFramework4.5.1" />
    </frameworkAssemblies>
  </metadata>
</package>
```

This should be removed

```XML
      <frameworkAssembly assemblyName="System.Net.Http.Formatting" targetFramework=".NETFramework4.5.1" />
```

Contact the owner of the package on NuGet.org and point them at this issue.

**Comment by damienpontifex** [comment]
Magic, thank you. You're a wizard @davidfowl :)

Sent them a message via NuGet.org and hopefully can test if this resolves the issue shortly.

**Comment by damienpontifex** [comment]
Resolved with Microsoft.Azure.Devices 1.0.5
