### ISSUE TITLE
Kestrel connection limits on Windows?

### ISSUE THREAD

**Issue by marce155** [aspnet/Home#1133]
I'd like to test drive a .NET 4.6 application on Kestrel (so Linux doesn't work afaik) including some load testing. 
I was able to grab a potent enough machine but no server OS and am now worried if Kestrel suffers from the same "10 concurrent requests" disease IIS has on client Windows?

If necessary I could install a Server 2012 trial just for the test, but it would be good to know in general.

**Comment by Eilon** [comment]
Please log this in https://github.com/aspnet/KestrelHttpServer/issues/.
