### ISSUE TITLE
References not resolving properly when targeting the new .NET Platform Standard monikers

### ISSUE THREAD

**Issue by Ruhrpottpatriot** [aspnet/Home#1134]
Note: This was first asked on [StackOverflow](http://stackoverflow.com/questions/33922762/asp-net-5-test-libraries-do-not-discover-main-code).

However after digging around a bit more I found this to be a likely bug. If this is not the correct place to report this, please redirect me to it.

Without further ado, here are the new information:
- The code from the StackOverflow question is still valid and hasn't changed.
- However, navigating to the code in question from the unit tests via F12 in VS2015 Update1 RC works.
- Running unit tests works, too.
- Visual Studio still reports a "Symbol not found", below is a screenshot of the code window. As you can see, IntelliSense can resolve the dependency and the error tab isn't giving any errors either
  ![vs2015 error](https://cloud.githubusercontent.com/assets/6794359/11446401/aaa24312-9536-11e5-8246-52aaa340d105.png)
- When changing the monikers back to the old monikers, i.e. reverting https://github.com/aspnet/Announcements/issues/98 the code window doesn't produce any errors

**Comment by davidfowl** [comment]
@Ruhrpottpatriot Can you provide a solution that reproduces your problem (preferably on github) with repro steps? This definitely works for all of our class libraries so it'll be good to narrow down the differences.

**Comment by erikstrandberg** [comment]
I believe the error message is generated by ReSharper, not Visual Studio. I have the same issue and my guess is that ReSharper does not handle references between projects targeting different, but compatible, framework monikers. Try disabling ReSharper to see if the error message disappears.

**Comment by Ruhrpottpatriot** [comment]
@davidfowl @erikstrandberg 
Yeah, it was a  R# problem ,(even with the latest version). When disabling R# the problem goes away. I'll report this to Jetbrains and hope for a fix in the near future.

This can be closed :)

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
