### ISSUE TITLE
Build multiple projects from command line

### ISSUE THREAD

**Issue by ChristopherHaws** [aspnet/Home#1135]
I was wondering if there is a reason that "dnu restore" is able to look for project.json files recursive but "dnu build" and "dnu pack" can't. It would be nice to be able to call "dnu build" from the solution directory to build all of the projects in the directory.

**Comment by davidfowl** [comment]
dnu pack and build support globbing patterns:

```
dnu pack src/*
dnu pack src/**
```

etc

**Comment by ChristopherHaws** [comment]
You sir rock! Thanks! :+1:

**Comment by lycon2014** [comment]
How do i run that

**Comment by ChristopherHaws** [comment]
@lycon2014 From the command line, navigate to the solution directory and type `dnu pack src/**`. This will tell dnu pack to search for project.json files under the src directory and build them.
