### ISSUE TITLE
Provide a full sample solution

### ISSUE THREAD

**Issue by marce155** [aspnet/Home#1136]
The samples provided are rather simple projects.
I'd like to see a "full" solution consisting of the MVC main project, "new" ClassLibrary projects, "old" ClassLibrary projects (assuming the target is dnx451 or dnx46 here, not core) and a unit test project.
There doesn't have to be a lot of business logic, just a sample how all those bits come together.

Especially the unit test part is important for me since I couldn't figure it out yet :)

Since you reached RC and we can start doing production work I think it's important to extend the samples to reflect a real world project/solution instead of dummy-single-project-solutions used during testing.

**Comment by GuardRex** [comment]
Others have asked about this, and the team has responded that the Music Store sample is a kind of flagship sample that has a bit of everything in it: https://github.com/aspnet/MusicStore ... which even includes tests: https://github.com/aspnet/MusicStore/tree/master/test/MusicStore.Test

For xUnit, you may have seen these, but in case not, check out: http://xunit.github.io/docs/getting-started-dnx.html and the official doc at https://docs.asp.net/en/latest/testing/unit-testing.html

I'm not sure on the "flagship" class library project. Actually, the official docs don't seem to even have a placeholder specifically for them. There is a lot of discussion on aspects: Search repos (open and closed issues) for "class library" and helpful issues come back.

**Comment by marce155** [comment]
Ah, completely missed that… helpful indeed. 
Is this the right place to ask if we are all doing xUnit tests now? I thought I read something about MSTest support coming in VS 2015, so since I’m now on 2015 I tried to set it up that way and failed.

**Comment by GuardRex** [comment]
Yes ... it's cross-plat, so I think that was one of the key reasons things went xUnit. I've gotten into xUnit myself, and I think it's awesome. It's very easy to setup and use. The xUnit repo has a lot of good issues raised and answered by the team.

For your question about MSTest, ask it over in that repo ... you'll find that the experts and key MS folks in each area monitor repos in their own areas most closely, so xUnit questions go best in the xUnit repo issues, and you'll probably get a quick answer ... sometimes 10 seconds after you post!

**Comment by davidfowl** [comment]
There's this but it hasn't been updated for RC1 https://www.nuget.org/packages/MSTest.Runner.Dnx/1.0.0-alpha8

**Comment by marce155** [comment]
Ah, of course, cross-plat. Sometimes I'm so amazed all my stuff runs on Linux I subconsciously expect really ALL my stuff running everywhere by vNext magic ;)

@davidfowl thanks and hope you'll be on the next standup again
