### ISSUE TITLE
Error installing rc1

### ISSUE THREAD

**Issue by tparnell8** [aspnet/Home#1137]
I'm getting a failed message when trying to install rc1 "The hash value is incorrect"

![failure](https://cloud.githubusercontent.com/assets/3459800/11458906/f2c47892-9697-11e5-83c2-f0ce505c47a0.PNG)

[Here is the log file](https://github.com/aspnet/Home/files/46685/failure.txt)

**Comment by tparnell8** [comment]
I got the installer from this page. I clicked on [ASP.NET 5](https://go.microsoft.com/fwlink/?LinkId=627627) where it says Install ASP.NET 5

https://docs.asp.net/en/latest/getting-started/installing-on-windows.html#install-asp-net-5-with-visual-studio

**Comment by GuardRex** [comment]
Make sure you run the installer from a folder with no other installers present (but this may have been fixed ... I know they were working on a fix). The installer is also here: https://get.asp.net/OtherDownloads

**Comment by GuardRex** [comment]
Looks like that one is still open ... https://github.com/aspnet/Tooling/issues/302

**Comment by tparnell8** [comment]
I moved it into an empty directory and it seems to be running now :white_check_mark:
