### ISSUE TITLE
Hosting ASP.NET 5 

### ISSUE THREAD

**Issue by miker1423** [aspnet/Home#1139]
I have a contract with hostgator, but i used to have some PHP code in there so i know it is Linux, can I host my new ASP.NET 5 web site in that kind of hosting? I really don't know if they support ASP.NET...

**Comment by Eilon** [comment]
Yes, ASP.NET 5 runs on Windows, Linux, and MacOS. Here's how to get started on Linux: https://docs.asp.net/en/latest/getting-started/installing-on-linux.html

BTW PHP also runs on all those platforms, so just because there's PHP doesn't necessarily mean it's Linux (though it's likely).
