### ISSUE TITLE
Modular web applications with ASP.NET 5 and DNX

### ISSUE THREAD

**Issue by jupdidu** [aspnet/Home#1140]
In the past days I was trying to create a modular web application with ASP.NET 5 and DNX. However I have some problems to figure out a good solution, which covers all our requirements.

Maybe you can help me a little bit to go into the right direction. I do not expect full tutorials or code examples, but some general hints woul be very awesome.

**Here is a list of the requirements that we have in mind:**
1. There should be one main application which functions as the host for the modules and contains an administrative backend to configure the available modules.
2. Each module should be discovered at runtime.
3. It would be nice if the modules could be installed/updated while the main application keeps running without the need of a restart.
4. Each module has its own project in VS and should be debuggable whithin the main application.
5. Different modules should not use controllers from other modules and it should be possible to use the same controller names in different modules.
6. Each module has its own space in the main application. This includes:
   * URL path prefix (e.g. /modules/example, /modules/example2)
   * Services / dependency injection (so each module should be able to define a ServiceCollection or ServiceProvider and use methods like services.AddMvc() for the module only).
   * Configuration (same idea as with the services, each module should be able to configure its own request pipeline like app.UseMvc(). However if a service could not be found in the specific services for the module the application should also consider the services of the main application so that common services like logging etc. do not have to be duplicated for each module)

The target framework is dnxcore - atleast if it is possible.

I can also provide some examples what I have tried up to now, but the text is so long already that I do not want to include it in one post. The general idea however was to have one project running a kestrel server which then loads the module assemblies into separate LoadContexts and delegates the http requests to a pipeline per module similar to app.Map().

**Comment by Eilon** [comment]
@sebastienros sounds like Orchard could have some stuff to offer here?

**Comment by sebastienros** [comment]
@jupdidu Everything you have listed is what Orchard is: https://github.com/OrchardCMS/Orchard. And we have already started developing it on dotnet core here: https://github.com/OrchardCMS/Orchard2. 

I would suggest you use Orchard2 instead of trying to create something new, and maybe work with us on it if you are interested. You can already look at how we solved the features you have listed. Some things will change in the near future like dynamic module loading but it's a good start. There might also be some features you don't need or decisions you don't agree with (theming, data access, conventions, ...) then feel free to copy what we have done.

**Comment by sebastienros** [comment]
Feel free to ask more question on the gitter chat https://gitter.im/OrchardCMS/Orchard2

**Comment by jupdidu** [comment]
Thank you very much for the information!
We will take a closer look at Orchard2. I think even features like theming and data access would be very nice for us because most of our modules would need data from a central database where most of our business data is stored.

@sebastienros You may be hearing from us again in the near future ;)
