### ISSUE TITLE
Bringing back/forward ASP.NET App Suspend?

### ISSUE THREAD

**Issue by csrakowski** [aspnet/Home#1143]
During today's ASP.NET community stand-up, I asked how the new HttpPlatformHandler/Kestrel hosting scenario would work with ASP.NET's App Suspend feature.
Damian Edwards answered by saying that it doesn't work at this time and explains a bit why that is. ([Full answer here](https://youtu.be/YYlWMZTPKyA?t=38m8s))

I created this issue because I actually really like the feature and would love to be able to keep using it in the future. I would like to see how other people feel about it and discuss some pro's and con's, and whether or not people think this would still provide a lot of value (going forward).

Now, the most obvious Pro is the reason the feature was created in the first place: it allows people to host more applications on the same server and make apps more responsive after a time out. ([Announcement blog post](http://blogs.msdn.com/b/dotnet/archive/2013/10/09/asp-net-app-suspend-responsive-shared-net-web-hosting.aspx))
The main Con, as Damian also mentioned in part of his answer, is that memory is a lot cheaper these days and that is especially true for people hosting in the cloud, making it typically a non-issue for them.
This last part is also where he really got me thinking.

I personally work for a company where we don't (yet) host everything in the cloud, so for us the memory constraint of the physical machines still matters and we would love to be able to keep taking advantage of this awesome solution.
On the other hand, eventually we will have to upgrade our hosting environment and the new hardware will come with more memory, thus solving the issue (for a while, since applications will, probably, get larger over time), or we could decide to work off technical debt on our end and work on moving to the cloud, also solving the memory issue.

I know you always have to weigh the cost of building, maintaining and supporting a feature against the return you will get from it. Keeping the hardware (r)evolutions in mind, this return is really hard to define/predict, but it's going to be crucial in deciding whether or not it would be worth the investment.

Any thoughts on the matter?

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
