### ISSUE TITLE
Add @if (ViewBag.UnitializedVar) in Razor view - 404

### ISSUE THREAD

**Issue by alvipeo** [aspnet/Home#1144]
Nice one, hard to find - add @if (ViewBag.UnitializedVar) to a razor view and when you visit this page it's just simply returns 404. Same in production (when published to Azure and in Release). Shouldn't it throw an error?

Here's a little output:

```
Microsoft.AspNet.Diagnostics.ExceptionHandlerMiddleware: Error: An unhandled exception has occurred: Cannot convert null to "bool" because it is a non-nullable value type
Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: Cannot convert null to "bool" because it is a non-nullable value type
   в CallSite.Target(Closure , CallSite , Object )
   в System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   в Asp.ASPV__Views_Home_zapis_cshtml.<ExecuteAsync>d__26.MoveNext() в /Views/Home/theview.cshtml:line 13
```
I guess this is because line number :)

**Comment by davidfowl** [comment]
Do you have the error page middleware setup in the pipeline?

**Comment by davidfowl** [comment]
> Same in production (when published to Azure and in Release). Shouldn't it throw an error?

In production (not release) there should only be logging no error page (that would be terrible :smile: ). You can show enable errors to show up on the remove with a setting.

**Comment by alvipeo** [comment]
ok, just created a public method in controller that throws exception for testing purposes. Same 404, so I guess I'm missing something. But I do have this:

    app.UseExceptionHandler("/Home/Error");

in Startup. Hm...

**Comment by alvipeo** [comment]
Double checked - my bad. The problem was with the routing.
