### ISSUE TITLE
Unable to Deploy to Azure RC-1 

### ISSUE THREAD

**Issue by ArieJones** [aspnet/Home#1147]
We are currently working on a web application and up until RC-1 we were able to deploy it successfully to Azure. 
The project now has been updated to RC-1. Runs successfully locally when we debug it on IIS Express... but when we deploy to Azure all we get is a very long pause and then eventually a 502 error from the browser... 

If we look at the event log about the only thing we see is the following entry for the below....

Is there a way in which we can get what EXACTLY is going on?

``` XML
<Event>
<System>
<ProviderName="HttpPlatformHandler"/><EventID>1000</EventID><Level>0</Level><Task>0</Task><Keywords>Keywords</Keywords><TimeCreated SystemTime="2015-12-02T23:07:48Z"/>
<EventRecordID>812457593</EventRecordID><Channel>Application</Channel>
<Computer>RD00155D857487</Computer><Security/></System><EventData>
<Data>Process '7016' failed to start. Port = 29376, Error Code = '-2147023829'.</Data></EventData>
</Event>
```

**Comment by muratg** [comment]
@victorhurdugaci 

How does your web.config look like?

**Comment by ArieJones** [comment]
Sadly it is basically the default one .... except for the log = true entry which we just switched on... 

<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <system.webServer>
    <handlers>
      <add name="httpPlatformHandler" path="*" verb="*" modules="httpPlatformHandler" resourceType="Unspecified"/>
    </handlers>
    <httpPlatform processPath="%DNX_PATH%" arguments="%DNX_ARGS%" stdoutLogEnabled="true" startupTimeLimit="3600"/>
  </system.webServer>
</configuration>

**Comment by GuardRex** [comment]
@ArieJones I list the known Azure Apps issues at the top of the "Application" section (this has been updated for RC1): https://github.com/aspnet/Hosting/issues/364#issuecomment-148567294

**Comment by GuardRex** [comment]
@ArieJones Try ...
```
processPath="%home%\site\approot\web.cmd"
```

**Comment by ArieJones** [comment]
Sorry @GuardRex I was actually following that discussion earlier today trying to determine what is up. 
The change above with the procesPath  gets me no joy unfortunately. 

I think I am leaning towards the possibility that RC-1 possibly broke something in regards to the solution file being grouped in with the global.json file.... (sigh)....but it would appear that the only way I can really rectify that is to create another new project and then move everything over...

**Comment by GuardRex** [comment]
@ArieJones Yes, I think there was an issue on exactly that point. I don't recall the repo where it was reported.

**Comment by GuardRex** [comment]
@ArieJones ... but I think it was more along the lines of the `global.json` file being mixed in with the project files. I'll dig around and see if I can find that issue.

**Comment by ArieJones** [comment]
It was on this particular thread.... https://github.com/aspnet/Hosting/issues/364#issuecomment-156365450

**Comment by GuardRex** [comment]
@ArieJones Yeah, that's it.

Do you have diagnostic logs turned on in the Azure portal? That was a problem recently for someone.

**Comment by victorhurdugaci** [comment]
@ArieJones a few questions to help us narrow down the issue:

1. How do you deploy?
2. What DNX runtime & architecture do you use? Is is the same when you run locally and publish to Azure?
3. Is there a body in the 502 response?

**Comment by ArieJones** [comment]
@GuardRex  no diagnostics 

@victorhurdugaci  
1. Through visual studio using the normal MSdelpoy template which worked up until now. 
2. we are using the Rc1 x86
3. Nope

**Comment by ArieJones** [comment]
So after going in and creating a new solution last night... moving everything over... and then getting source control in line... 

deployment works as expected... 

When I get some time I will try to look into the whole global.json file residing in the same level as the project thing to see if that somehow helps the situation at all but right now I am short on time. I think in the long run it may help some people out whom are like me , migrating their project up through the various stages, and running into major hurdles when it comes RC time.  

One note though is that it seems we are overcompensating everything with a .json file. Right now as I look at my project I have 
global.json 
bower.json
config.json 
package.json 
project.json 
tsconfig.json 
tsd.json 

I mean at some point is there going to be some sort of consolidation of these or is this our newest form of 'Dll Hell' ... 2.0 of course...

**Comment by GuardRex** [comment]
@ArieJones I'm glad it worked out for you. I'm adding a note to my comment. I'll say tentatively that this might be due to the `global.json` thing. I'll also run a test and see what happens when the file is placed alongside the project files. I want to see if the process failure is the same outcome.

**Comment by GuardRex** [comment]
@davidfowl @anurse @ArieJones Yep ... it broke. Starting with this layout ...
```
.vs
src
    - artifacts
    - MyApp
        - bin
        - Controllers
        - Models
        - Views
        - wwwroot
        - MyApp.xproj
        - MyApp.xproj.user
        - project.json
        - Startup.cs
MyApp.sln
global.json
```
... and merely moving the `global.json` to this layout ...
```
.vs
src
    - artifacts
    - MyApp
        - bin
        - Controllers
        - Models
        - Views
        - wwwroot
        - MyApp.xproj
        - MyApp.xproj.user
        - project.json
        - Startup.cs
        - global.json
MyApp.sln
```
... results in a project that will run locally in IIS Express but breaks on the server. The app is unresponsive. The log shows ...
```
System.IO.DirectoryNotFoundException: The system cannot find the path specified. (Exception from HRESULT: 0x80070003)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at Microsoft.Dnx.Runtime.Loader.PackageAssemblyLoader.Load(AssemblyName assemblyName, IAssemblyLoadContext loadContext)
   at Microsoft.Dnx.Host.LoaderContainer.Load(AssemblyName assemblyName)
   at Microsoft.Dnx.Runtime.Loader.AssemblyLoaderCache.GetOrAdd(AssemblyName name, Func`2 factory)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyName(AssemblyName assemblyName)
   at Microsoft.Dnx.ApplicationHost.DefaultHost.GetEntryPoint(String applicationName)
   at Microsoft.Dnx.ApplicationHost.Program.ExecuteMain(DefaultHost host, String applicationName, String[] args)
   at Microsoft.Dnx.ApplicationHost.Program.Main(String[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Dnx.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider serviceProvider)
   at Microsoft.Dnx.Host.Bootstrapper.RunAsync(List`1 args, IRuntimeEnvironment env, String appBase, FrameworkName targetFramework)
   at Microsoft.Dnx.Host.RuntimeBootstrapper.ExecuteAsync(String[] args, BootstrapperContext bootstrapperContext)
   at Microsoft.Dnx.Host.RuntimeBootstrapper.Execute(String[] args, BootstrapperContext bootstrapperContext)
```
... and I wouldn't be surprised if you said 'that's by design.' However, let me know if you want me to create a fresh issue for this, and I'll move it (to dnx?).

**Comment by davidfowl** [comment]
Where's the bug?

**Comment by GuardRex** [comment]
What? If it's by-design, no problem here.

**Comment by GuardRex** [comment]
Confused by your ? ... Are you saying you want/need more than the stack trace, or are you saying this is by-design?

**Comment by davidfowl** [comment]
Are you moving the preprocessed `global.json` into another folder and expecting it to work? I'm not sure I understand the repro steps. Is that the published layout or source layout?

**Comment by GuardRex** [comment]
That's the source layout. I run the VS publish, then shoot the bits to the server (MSDeploy).

**Comment by GuardRex** [comment]
I can get the server layout if you need it.

**Comment by davidfowl** [comment]
Can you do a file system publish.

**Comment by GuardRex** [comment]
Well ... yes ... that's what I meant. I just VS publish to an output folder, then MSDeploy from the output folder to the server. Let me check the output folder and see what it's shooting up there. brb

**Comment by GuardRex** [comment]
Ok ... so it gets a new `global.json` on publish (this is the right spot, right?) ...

![capture](https://cloud.githubusercontent.com/assets/1622880/11568698/7c114082-99a2-11e5-8ec3-ed57cbc585c5.PNG)

... but the moved `global.json` (i.e., I move it manually with VS closed ... then open VS ... publish and MSDeploy) ... it ends up with that file here ...

![capture2](https://cloud.githubusercontent.com/assets/1622880/11568713/95c11b56-99a2-11e5-9c71-7c6625256bd6.PNG)

**Comment by GuardRex** [comment]
The new one that it creates has this ...
```
{
  "projects": [
    "src"
  ],
  "sdk": {
    "architecture": "x64",
    "runtime": "coreclr",
    "version": "1.0.0-rc1-final"
  },
  "packages": "packages"
}
```
The one that I move and lands in `root` has this ...
```
{
  "projects": [
    "src"
  ],
  "sdk": {
    "architecture": "x64",
    "runtime": "coreclr",
    "version": "1.0.0-rc1-update1"
  }
}
```

**Comment by GuardRex** [comment]
Ok, good, that screw up with the runtime wasn't a problem. So ... the new `global.json` has this ...
```
{
  "projects": [
    "src"
  ],
  "sdk": {
    "architecture": "x64",
    "runtime": "coreclr",
    "version": "1.0.0-rc1-update1"
  },
  "packages": "packages"
}
```
... and the original that shows up in `root` has this ...
```
{
  "projects": [
    "src"
  ],
  "sdk": {
    "architecture": "x64",
    "runtime": "coreclr",
    "version": "1.0.0-rc1-update1"
  }
}
```
... so having that one in the project files (`root`) breaks it (apparently).

**Comment by GuardRex** [comment]
I have an issue for the DNX repo ready if you want this open over there.

**Comment by GuardRex** [comment]
... and btw ... my runtime problem was forgetting the `-p` when I set the `dmvm active` ... orf!

**Comment by GuardRex** [comment]
@davidfowl Should I drop this? ... not important? ... I just want to close my browser tab where I have an unpublished issue waiting for the DNX repo one way or the other.

**Comment by GuardRex** [comment]
Opened at https://github.com/aspnet/dnx/issues/3229 ... sorry ... my OCD must be kick'in today.

**Comment by champi0ne** [comment]
FWIW - I have the same exact issue after upgrading a Beta8 application to RC-1 on Azure.  I use git push - all appears fine with the deployment - but app just spins and spins.

Did you resolve your problem?

**Comment by Zoltu** [comment]
Is there a fix or workaround for this?  I have the exact same symptoms as the OP, but I'm not clear if there is a fix in this thread.  The issue is still open so I'm guessing this is still a problem with Azure / RC1 but I would like to get something working while I wait for the ideal solution (whatever that is).

Since everyone seems to be posting project layouts, I am running with everything in the root (no `src` folder).  I do have some code nested inside folders, but they are dangling right off the root.  I also have a `Properties/launchSettings.json` and a `wwwroot/web.config`.

**Comment by GuardRex** [comment]
@Zoltu Do you have a `global.json` in the root with the rest of your app's files and folders published output? If so, then you need to add `global.json` to the `publishExclude` section of `project.json`. 

Otherwise if that's not a problem, there are many reasons why an app would be unresponsive on Azure. My [old post on RC1 conversions](https://github.com/aspnet/Hosting/issues/364#issuecomment-148567294) is still somewhat relevant, so you can run down that list to see if anything rings a bell.

**Comment by Zoltu** [comment]
Adding `global.json` to `publishExclude` changed my error to 500 from 502, so that appears to have done something.  I'm guessing I have some new problem to deal with now.  Thanks!

**Comment by GuardRex** [comment]
@Zoltu Given the number of potential causes for an unresponsive app, you'll probably need to put up a repro of the project. One quick question though to narrow it down: If you have static file middleware in the app, can you get a static file served to the browser from the app in Azure (e.g., a CSS or script from your `wwwroot` folder)? That's a quick and dirty way to at least figure out if the HPH-IIS-side is working as expected.

**Comment by Zoltu** [comment]
No, it is an ApiApp, no static files except for the `web.config` which I'm pretty sure Azure won't let you download directly.  I'll keep digging, at the least my symptoms no longer align with this GitHub issue.  https://github.com/Zoltu/BagsMiddleware

**Comment by GuardRex** [comment]
@Zoltu Try changing the `processPath` and `arguments` to explicit values in `web.config`:
```
processPath="..\approot\web.cmd" arguments=""
```
... also, enable the stdout log and see if you get anything in there.

**Comment by Zoltu** [comment]
Giving it a try, though [this](https://github.com/Zoltu/Templates.ApiApp) app deployed fine with GitHub deploy and it was used as the scaffold for [this](https://github.com/Zoltu/BagsMiddleware) project.  I did add the Visual Studio files to the second, the first is only the `project.json`.  Both have the same `web.config`.

**Comment by Zoltu** [comment]
Ah, the first project linked above actually doesn't target `coreclr`.  I'm guessing that it ended up deployed to Azure as a `clr` app which is perhaps why it worked.

**Comment by GuardRex** [comment]
Did you try setting `stdoutLogEnabled="false"` to `true` and see if the log on the failing app has anything interesting in it?

**Comment by Zoltu** [comment]
It looks like the removal of environment variables from the `processPath` and `arguments` resolved the issue, my app just took a lot longer to start then I expected for such a simple app.

**Comment by Zoltu** [comment]
So everything was working on Azure, but when I went to test locally it doesn't work.  Apparently in order for local IIS Express debugging to work the `%DNX_PATH%` and `%DNX_ARGS%` need to be present.

Is there a workaround that will allow me to run in both Azure and IIS Express locally?  If not, is this slated to be fixed before launch?
