### ISSUE TITLE
CORS not adding 'access-control-allow-origin' response to options preflight request

### ISSUE THREAD

**Issue by jamesla** [aspnet/Home#1148]
I'm getting the following error in chrome:

Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:9000' is therefore not allowed access.

```c#
 app.UseCors(policy => policy
            .WithOrigins("http://localhost:9000")
            .AllowAnyMethod()
            .WithHeaders("Access-Control-Allow-Origin, Content-Type, x-xsrf-token, Authorization")
            .AllowCredentials());
```

According to chrome there is not a single header being added to the response. 

What is the correct way to add the "access-control-allow-origin" header to a options response in aspnet5?

**Comment by Eilon** [comment]
@kichalla can you take a look?

**Comment by jamesla** [comment]
FYI I've also tried installing Microsoft.AspNet.Cors package and configuring with:

 services.AddCors(options =>
            {
                options.AddPolicy("DefaultPolicy", builder => builder.WithHeaders("Access-Control-Allow-Origin"));
                options.DefaultPolicyName = "DefaultPolicy";
            });

Which hasn't made any difference

**Comment by kichalla** [comment]
- Can you share how your preflight request looks like?

- The signature of the method `WithHeaders` is `public CorsPolicyBuilder WithHeaders(params string[] headers)`, so it accepts a params array...you had all the headers in one string

BTW you need not supply `Access-Control-Allow-Origin` as part of the headers list. You can try with a basic scenario where you use `AllowAnyHeader` and see if everything works fine and then restrict the headers.

**Comment by kichalla** [comment]
@jamesla I cannot repro the issue that you are seeing. Feel free to re-open this issue with a repro.
