### ISSUE TITLE
"Hosting" ASP.NET project in Console project

### ISSUE THREAD

**Issue by sebitsi** [aspnet/Home#1149]
For hosting ASP.NET 5 project in Console project i use

```
if (args == null) {args = new string[] { }; }
var mergedArgs = new[] { "--server", "Microsoft.AspNet.Server.Kestrel",
                                          "--server.urls", "http://localhost:50000",
                                          "--hosting:application", "TestMVCRC1"
                                        }.Concat(args).ToArray();
WebApplication.Run(mergedArgs);
```

When code is started, listener is started on port 50000, but application path is set to console 
project not MVC project. 
HostEnvironment is set to ..../console/views/home... Not .../TestMVCRC1/views/home.

Are there any configuration settings i missed ?
Or the only way is copy wwwroot and views folder to console project ? I hope not.

Thanks for advance.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
