### ISSUE TITLE
Install dnvm into custom directory

### ISSUE THREAD

**Issue by tparnell8** [aspnet/Home#1150]
is it possible to have dnvm install into a custom place that is not ~/.dnx

**Comment by Eilon** [comment]
@glennc @BrennanConroy ?

**Comment by BrennanConroy** [comment]
You could put it where ever you want, but you'll have to do it yourself, also make sure to add ```source <path>/dnvm.sh``` to your bash_profile or zschrc or whatever terminal you use.

**Comment by tparnell8** [comment]
sounds good thanks
