### ISSUE TITLE
.NET Framework vs .NET Core

### ISSUE THREAD

**Issue by papercity4** [aspnet/Home#1152]
Am I correct that the .NET Core is a replacement for the .NET Framework? I know that it's a subset right now, but the ultimate goal is that the .NET Core will have the same features(minus Win Forms etc.). 

I can't imagine the .NET Framework will get new features for that long considering the .NET Framework is 15 years old. Is .NET Framework close to the end? I am trying to understand the future roadmap. We plan on building all new application's in .NET Core but I want to make sure I basing my decision with the right information.

**Comment by miguellira** [comment]
@papercity4 No. .NET Core is not a replacement. The .NET Framework is not going anywhere any time soon. I suggest you read this year old [post](http://www.hanselman.com/blog/AnnouncingNET2015NETAsOpenSourceNETOnMacAndLinuxAndVisualStudioCommunity.aspx) by Scott Hanselman and work your way up to his [post](http://www.hanselman.com/blog/ASPNET5AndNETCoreRC1InContextPlusAllTheConnect2015News.aspx) from the recent Connect 2015 conference.

If it appears that your new application's dependencies are covered by what .NET Core currently offers then go for it. Just know that you'll run into plenty of gaps along the way.

**Comment by stevedesmond-ca** [comment]
Note that you can target your app against both the .NET CLR as well as the new Core CLR (and I believe it actually does this by default) so it's not necessary to pick one or the other out-of-the-gate, unless you're looking for cross-platform, in which case you'd need .NET Core (or Mono, but that's a different story).

**Comment by Eilon** [comment]
@richlander do you have a recommended doc you can point people to?

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
