### ISSUE TITLE
samples/latest/HelloWeb inconsistent Dockerfile

### ISSUE THREAD

**Issue by sfilatov** [aspnet/Home#1155]
### Latest samples contains inconsistent Dockerfile

`samples/latests/HelloWeb` contains inconsistent `Dockerfile`
latest folder contains 1.0.0-rc1 instead of 1.0.0-rc1-update1
### Functional impact

`samples/latest/HelloWeb` docker container fail to start
### Minimal repro steps

```
cd samples/latest/HelloWeb
docker build -t aspnet-home-helloweb .
docker run -it -p 80:5004 aspnet-home-helloweb
```
### Expected result

Container should start kester server
### Actual result

Container started but dnx fail to run `kestrel` command.
`Error: Unable to load application or execute command 'kestrel'. Available commands: web.`
### Further technical details

Looks like `samples/latest` should be switched to `1.0.0-rc1-update1` or deleted.

**Comment by linquize** [comment]
me too

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
