### ISSUE TITLE
'ILoggerFactory' does not contain a definition for 'AddConsole'

### ISSUE THREAD

**Issue by miguellira** [aspnet/Home#1158]
Enjoying `1.0.0-rc1-update1` but figured I'd take a stab at the latest bits and immediately ran into errors.

Pulled down the latest HelloMvc sample and ran it against `1.0.0-rc2-16249` and somehow the extension method is no longer found in `Microsoft.Framework.Logging.Console`.

There was work done recently in this space (https://github.com/aspnet/Announcements/issues/122) but the method is clearly still in the [source](https://github.com/aspnet/Logging/blob/5748f5d09f84796432afc1d997630c56d315cc6a/src/Microsoft.Extensions.Logging.Console/ConsoleLoggerFactoryExtensions.cs#L15).

I tried running `dnu restore --no-cache` and am currently targeting the following Feeds:
```console
Feeds used:
    https://www.myget.org/F/aspnetvnext/api/v2/
    https://nuget.org/api/v2/
```
I'm sure it's user error but wondering if I'm alone.

**Comment by davidfowl** [comment]
Microsoft.Framework.Logging.Console is the wrong package name. It's Microsoft.Extensions.Logging.Console

**Comment by miguellira** [comment]
@davidfowl Ugh. Can't believe I didn't see that or why the "latest" folder is anything but ;) Thanks!

**Comment by Eilon** [comment]
@miguellira BTW you can follow most breaking changes and announcements by subscribing to notifications on the [Announcements](https://github.com/aspnet/Announcements/) repo. For example, this breaking change was noted here: https://github.com/aspnet/Announcements/issues/77

**Comment by miguellira** [comment]
@Eilon Thanks. I do follow the Announcements repo was aware of this change (since I've been developing against RC1). However, before I take stab at the latest bits I try to run the basic HelloMvc from the samples folder and the _**"latest"**_ folder has not incorporated this change and I simply missed it.

Would be great if those sample apps stay in step with all the breaking changes but I'm sure you guys have bigger fish to fry.

**Comment by level6ascend** [comment]
got here because i've got the same problem while making a program. Thanks davidfoul
