### ISSUE TITLE
Updating nuget package for Newtonsoft.Json breaks the application

### ISSUE THREAD

**Issue by turowicz** [aspnet/Home#1160]
Conditions: ASP.NET 5 RC1 Update 1 app running on Service Fabric

Project: 
- One class library depends explicitly on Newtonsoft.Json 7.0.1
- ASP.NET 5 app secretly depends on Newtonsoft.Json 6.0.6

Result: The application doesn't start.

Exception log:

System.IO.FileNotFoundException: Could not load file or assembly 'Newtonsoft.Jso
n, Version=6.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of
its dependencies. The system cannot find the file specified.
File name: 'Newtonsoft.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=30
ad4fe6b2a6aeed'
   at Microsoft.Extensions.Configuration.Json.JsonConfigurationProvider.Load(Str
eam stream)
   at Microsoft.Extensions.Configuration.Json.JsonConfigurationProvider.Load()
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Add(IConfiguration
Provider provider)
   at Microsoft.Extensions.Configuration.JsonConfigurationExtensions.AddJsonFile
(IConfigurationBuilder configurationBuilder, String path, Boolean optional)
   at Microsoft.AspNet.Hosting.WebApplication.Run(Type startupType, String[] arg
s)
   at Microsoft.AspNet.Server.Kestrel.Program.Main(String[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Dnx.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly,
 String[] args, IServiceProvider serviceProvider)
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\M
icrosoft\Fusion!EnableLog](DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure lo
gging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fus
ion!EnableLog].

**Comment by davidfowl** [comment]
Hmm, that should be fine. Can you reproduce this outside of service fabric?

**Comment by turowicz** [comment]
not really... It might be a fabric issue, even after replacing Newtonsoft with Jil in my custom library the problem remains.

**Comment by turowicz** [comment]
I've enabled fusion log - it is looking for the dlls in GAC and DNX runtimes - both of which are wrong places.

**Comment by davidfowl** [comment]
Those are fine, as they are default search locations. DNX hooks assembly resolve and handles the resolution (normally).

**Comment by turowicz** [comment]
I've got few more leads to follow, SF related, will report back.

**Comment by turowicz** [comment]
Found out what was the issue. I needed to replace Newtonsoft with Jil in the library project, and delete dnx's "wrap" and "artifacts" folders. Looks like if there is a clash of dependencies then dnx on SF is having trouble finding right version. It also doesn't help that the referenced Newtonsoft 7.0.1 apperas as 1.0.0 in the "wrap" folder.

**Comment by turowicz** [comment]
@davidfolw I'm closing this - not sure if this is something you guys, SF or DNX team should address.

**Comment by janpieterz** [comment]
I think I just had something very similar happening without Service Fabric being involved. 

Running it from within Visual Studio works fine, publishing it to file system and running the web command from there (or deployed in IIS) gives the following exception.

I deleted the wrap and artifacts folders, re-wrapped the projects, but I can't replace NewtonSoft with Jil so a bit stuck there.

@davidfowl not sure if this is closed.

```
web
System.IO.FileNotFoundException: Could not load file or assembly 'Newtonsoft.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified.
File name: 'Newtonsoft.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'
   at Microsoft.Extensions.Configuration.Json.JsonConfigurationProvider.Load(Stream stream)
   at Microsoft.Extensions.Configuration.Json.JsonConfigurationProvider.Load()
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Add(IConfigurationProvider provider)
   at Microsoft.Extensions.Configuration.JsonConfigurationExtensions.AddJsonFile(IConfigurationBuilder configurationBuilder, String path, Boolean optional)
   at Microsoft.AspNet.Hosting.WebApplication.Run(Type startupType, String[] args)
   at Microsoft.AspNet.Server.Kestrel.Program.Main(String[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Dnx.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider serviceProvider)
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].
```

**Comment by janpieterz** [comment]
Just tried to make a small repro (which so far works) and noticed a difference that seems to have something to with it since @turowicz also mentioned something about it:
Newtonsoft.Json in the not-working project is in the packages folder with version 1.0.0 while in the working project it is referenced with 7.0.1.

**Comment by turowicz** [comment]
reopening since I also think it's a viable issue.

cc @davidfowl

**Comment by janpieterz** [comment]
I actually just 'solved' mine by removing the Azure Key Vault package from one of the libraries. Re-wrapped everything and then it 'magically' included 7.0.1 instead of naming it 1.0.0.

Very odd!

**Comment by davidfowl** [comment]
If you could provide a sample with the broken application in a github repository then I can take a look.

**Comment by janpieterz** [comment]
Been trying for a while now to replicate this for you in a clean repro, but am failing. The relevant package that 'somehow' fixed mine was Microsoft.Azure.KeyVault.Core, although  I have a feeling it has more something to do with the wrapping on a Publish, since it worked fine without publishing.

Perhaps relevant recent changes:

My ASP.NET (rc1-update1) references 4 DLL's (normal .net) which reference a DLL (normal.net) which references all Azure Storage dll's and stuff.
Recently had a thorough restructuring of the project where this storage wrapper was moved to a folder (Dependencies). Also most projects had renames (both project folder and project name), plus I had some different versions of Newtonsoft (and other libraries) used so I consolidated them all to version 7.0.1.

Besides trying my repro to get to display the behavior I tried re-introducing the behavior in the old project which doesn't work either, it keeps nicely producing 7.0.1 in the packages folder when I publish.

These things are currently the best input I can give on what happened more or less the last day, structure wise to my project, I know it's not really anything usable, sorry!

**Comment by tom-tgr** [comment]
Is there any solution for this issue?

**Comment by davidfowl** [comment]
@tom-tgr do you have a repro project?

**Comment by tom-tgr** [comment]
Sorry, could not replicate this issue. But I found workaround, just changed version number from 1.0.0-* to 7.0.1-* for wrapped Newtonsoft.Json project.

**Comment by fjiangb** [comment]
Can anyone post an "official" solution for this issue? I ran into this issue today.
