### ISSUE TITLE
What are the plans on WebApiCompatShim?

### ISSUE THREAD

**Issue by tugberkugurlu** [aspnet/Home#1163]
I am about to start using WebApiCompatShim on a project but I wanted to make sure what the plans are for this. Is it the plan to continue supporting this and ship as part of stable 1.0.0 release?

**Comment by Eilon** [comment]
Yes! It's a supported feature in ASP.NET 5. Having said that, we strongly recommend porting Web API apps to ASP.NET MVC 6 because that's where the future innovation will be.
