### ISSUE TITLE
Recommended approach to enforcing HTTPS throughout a site

### ISSUE THREAD

**Issue by bitcrazed** [aspnet/Home#1164]
What's the recommended approach to forcing all areas of a site to have to use HTTPS? Request Rewriting? Other?

**Comment by GuardRex** [comment]
See https://github.com/aspnet/Home/issues/895

**Comment by lycon2014** [comment]
Why

**Comment by muratg** [comment]
Specifically https://github.com/aspnet/Home/issues/895#issuecomment-138040980

**Comment by Galilyou** [comment]
>(If you're using IIS via HttpPlatformHandler)

The middleware piece is a better solution, no need to add a dependency on IIS.

**Comment by GuardRex** [comment]
It's not adding a dependency on IIS ... It's configuring IIS to handle the redirect. IIS gets first crack at the request. I wildly guess it would be faster and cheaper (i.e., request processing by the app and GC) ... but who of us really has time to perf test the two options. :smile:

**Comment by Galilyou** [comment]
@GuardRex  I wrote this in a totally wrong way. I meant this will only work for IIS. If you want a more portable solution, then your only option is the middleware piece, I guess.

**Comment by GuardRex** [comment]
@Galilyou Ah, yes, sorry. My bad. I was happy to see that middleware option, too, because I had the same feeling about it.

**Comment by JGrzybowski** [comment]
I tried to use @Sharpiro template referenced in #895 but with no luck.
No matter which implementation I found in web I used, it always loops infinitely redirecting http to https and then again getting http request.
Should Middleware forcing https be used after authentication? I ask 'cause my other Middleware for logging user's activity receives https requests properly even thou it looks like they are recognized as http earlier.

**Comment by kirkone** [comment]
@JGrzybowski I can confirm this behavior with `context.Request.IsHttps`only is true after authentication.

Is this the way it should work and if yes, why?

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
