### ISSUE TITLE
web.config appsettings expected by old 3rd party dlls

### ISSUE THREAD

**Issue by pearsonw** [aspnet/Home#1166]
Api's from, for example, Paypal and Cybersource expect certain appsettings in a configuration file, and don't seem to have write access to all the required properties on their objects.  I haven't had any success providing those values in the web.config under wwwroot using iisexpress.  Nor have I had any success providing those values in an appsettings.json file.

**Comment by davidfowl** [comment]
Assuming you are using .NET 4.x (aka dnx45x) then you can put those settings in app.config at the root of the project. This won't work on CoreCLR (obviously).

**Comment by pearsonw** [comment]
Thank you David. Yes I am using .Net 4.x.  I tried that and it did not seem to work for Cybersource, but I did discover they have a configuration object that I can set the required properties on.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
