### ISSUE TITLE
Create a gitter room, part deux

### ISSUE THREAD

**Issue by atrauzzi** [aspnet/Home#1167]
I know there was a ticket for this a while back - #416 - and the response to it was *"Nah, we use jabbr"*.

Although I'm wondering if there's any merit in reconsidering:

 - Someone created a Q&A item during the last ASP.NET community standup suggesting something other than jabbr
 - It structures nicely around github repositories
 - Rather than running in a browser tab, Gitter has apps: https://gitter.im/apps
 - Because gitter has apps, it's more performant and convenient to use on my phone
 - Because gitter has apps, I can get notifications
 - You can add nice gitter badges to `readme.md` files which are becoming ubiquitous as a "go here to chat about this project" cue

*(Just so nobody gets the wrong idea, I don't have any particular dislike for jabbr, just that it's being outpaced.)*

**Comment by davidfowl** [comment]
There's already a gitter room https://gitter.im/aspnet. But nobody hangs out there. But I do hang out in jabbr :smile:

**Comment by atrauzzi** [comment]
@davidfowl Haha, I do suppose where you are is most beneficial to me ;)

Although I should mention: The link you shared doesn't appear to be a room, but an index of rooms under the aspnet github slug.  Of which there is only one that I can see: "PlatformAbstractions".

![image](https://cloud.githubusercontent.com/assets/115199/11811555/caefe4d0-a2fb-11e5-802d-087911badb00.png)

I have a feeling if you made an actual room for the home repository, it would start filling up.

**Comment by Jeffiy** [comment]
@atrauzzi this https://gitter.im/dotnet/home ?

**Comment by atrauzzi** [comment]
I should think it's significant that it's `dotnet` vs `aspnet`, no?

**Comment by daveaglick** [comment]
+1 for a proper Gitter room. I've got nothing against Jabbr (other than that it's yet *another* chat window to remember to open), but I agree that with it's apps (both mobile and desktop), tight GitHub integration, and overall feature range, Gitter is an all-around more complete offering.

That probably isn't enough to warrant opening up a new Gitter room (and monitoring it). I do think the more important aspect here is one of community. Jabbr isn't all that well-known and I've talked to more than one developer who feels like it's mainly for "the cool kids." If the new ASP.NET, running on top of the new .NET stack, is supposed to appeal to the widest range of developers and recapture some of the folks who've been lost to Node, etc. then I think it makes sense to build community around the most accepted and comfortable tools for the broadest range of people. Gitter has quickly gained steam as the de-facto source-centric chat alternative to more general and business-oriented tools like Slack. Roslyn is active on Gitter. Corefx is active on Gitter. Several community projects have active Gitter rooms.

And that's not saying it would need to or should replace the Jabbr room. I would suggest opening a Gitter room and lightly monitoring it for a few months just to see if and how active it actually gets.

**Comment by davidfowl** [comment]
The gitter room already exists like I said earlier. It *cannot* be per repository because we have too many. Start with https://gitter.im/aspnet

**Comment by RehanSaeed** [comment]
Frustratingly, Gitter has no support for Windows Phone except a community app that is **super** basic. The cool kids use Slack these days.

**Comment by atrauzzi** [comment]
@RehanSaeed Sadly, that doesn't put it ahead of or behind Jabbr, which is in a similar position.
Although, I do think there should be something for every platform.  If you point me to any feedback tickets or posts for Gitter on Windows Phone, I'll gladly throw my vote behind anything you care to mention.  I'm sure it's just a matter of time before they come up with something.

Slack is not ideal for FOSS projects FWIW, as one ends up with many.  Having gotten into a few already, it gets quite cluttered, quite quickly.
