### ISSUE TITLE
Request for renaming asp-control to asp-controller

### ISSUE THREAD

**Issue by mariocatch** [aspnet/Home#1168]
I think the attributes for `asp-x` are great in markup. I think one improvement to the semantics of the `asp-control` could be to rename it to `asp-controller`.

`asp-action` is expressive and exact, so I feel that `asp-control` should be as well.

**Comment by scrapcode** [comment]
@mariocatch It is currently `asp-controller`. Where are seeing the usage of `asp-control`?

**Comment by Eilon** [comment]
No such thing as `asp-controller` as far as I know. Can you show us where you're seeing that?

**Comment by scrapcode** [comment]
Maybe I'm confused, but I assumed that mariocatch was talking about [MVC 6's TagHelpers](https://github.com/aspnet/Mvc/search?utf8=%E2%9C%93&q=asp-controller).

**Comment by EvAlex** [comment]
It is asp-controller currently.
