### ISSUE TITLE
Xunit not working with ASP.NET 5.0?

### ISSUE THREAD

**Issue by mdraganza** [aspnet/Home#1173]
I created 2 new class libraries using VS 2015 based on ASP.NET 5.0 1.0.0-rc1-final. One accesses data in MongoDB. The other contains Xunit unit tests. I cannot get the unit tests to work. Initially, there was a compiler error:
Severity	Code	Description	Project	File	Line	Suppression State

Error	CS0012	The type 'Attribute' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.	MongoTests..NET Framework 4.5.1	C:\Users\mdraganza\Documents\Visual Studio 2015\Projects\Mongo\MongoTests\MongoRemoteProbeTests.cs	23	Active

So I added a reference to System.Runtime located at C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.1\Facades. The compiler error went away, but now my unit tests don't show up in the Test Explorer and don't execute when I click on Run All. Has anyone else run into this?

**Comment by victorhurdugaci** [comment]
@vijayrkn

**Comment by vijayrkn** [comment]
Can you set this env variable : DNX_TESTHOST_TRACE=1, restart VS and provide us the log from output window (test)?

**Comment by vijayrkn** [comment]
Also, Please make sure you are using the right xunit.runner.dnx package for rc1. 
https://xunit.github.io/docs/getting-started-dnx.html

**Comment by mdraganza** [comment]
Once I followed that article you referenced and added
"commands": {
       "test": "xunit.runner.dnx"
}

all my tests showed up. Thank you very much.
