### ISSUE TITLE
Proposal: ASP.NET Startup class should implement IStartup interface

### ISSUE THREAD

**Issue by SetTrend** [aspnet/Home#1174]
Currently an ASP.NET 5 `Startup` class doesn't derive from a base class nor does it implement an interface. Yet, the runtime requires this class to provide certain member functions.

Currently there is no hint on which member functions to implement. Nor is intellisense provided. Implementing this class renders runtime errors instead of compile time errors, which is fairly error prone and should not be the design intention of a stable framework.

So I suggest to ...
 * either create an abstract `Startup__` base class with virtual members to override in `Startup.cs`
 * or to create an `IStartup` interface required by the `Startup.cs` to implement.

**Comment by Tratcher** [comment]
https://github.com/aspnet/Hosting/issues/386#issuecomment-145582237
