### ISSUE TITLE
XmlReader

### ISSUE THREAD

**Issue by rohitshrivastava04** [aspnet/Home#1175]
Hi

I am using XmlReader to read string into XElement in aspnet 5 web application and trying to host it in docker container.
It runs fine from visual studio hosted in Kestral. howvere as soon as I host it docker container application startup complains couldn't find XmlReader missing assembly references.

Then I added frameworkasssemblies into project.json

 "dnx451": {
      "frameworkAssemblies": {
        "System.Xml.ReaderWriter": "4.0.0.0",
        "System.Xml.XDocument": "4.0.0.0",
        "System.Xml": "4.0.0.0",
        "System.Xml.Linq": "4.0.0.0"
      }
    }

Now I don't see any error while application start but now my api controller (rest api) hangs and I dont see any response or no error, it just keeps waiting.

I am exposing the port using Expose and mapping to docker port 80 using -p  80:7600

Can anyone tell me what am I missing here?

Regards
Rohit

**Comment by muratg** [comment]
@rohitshrivastava04 Are you using Linux or Windows?  What's the docker image you're using?

cc @glennc

**Comment by rohitshrivastava04** [comment]
Sorry, it was my bad. A small typo in System.XML xml was all caps. Though it was in a class library which I was referring in main web application.

On a side note, it should fail stating could not found System.XML. Anyway thanks.

FYI: I am developing on windows 7 and using microsoft/aspnet:1.0.0-rc1-final
