### ISSUE TITLE
Dynamic cookie authentication LoginPath

### ISSUE THREAD

**Issue by Muchiachio** [aspnet/Home#1176]
Is there a way to make cookie authentication `LoginPath` dynamic? Because I'm always losing all the routing data from which unauthenticated request was called. E.x., given `LoginPath = "accounts/login"`:
`http://localhost:8547/private-section/b/items/1` redirects to `http://localhost:8547/accounts/login`
I would like to get `http://localhost:8547/private-section/b/accounts/login`
or
`http://localhost:8547/public-section/promotion` redirects to `http://localhost:8547/accounts/login`
I would like to get `http://localhost:8547/public-section/accounts/login`

**Comment by Muchiachio** [comment]
The lonely bump :3

**Comment by blowdart** [comment]
Add an issue in the security repo where the cookie pieces live. Home issues don't really get noticed.
