### ISSUE TITLE
TFS integration

### ISSUE THREAD

**Issue by rosieks** [aspnet/Home#1178]
I'm trying to setup TFS build and it looks like it miss a lot of tasks like:
- bower/tsd/jspm install
- dnvm install
- publish to azure

Right know I have to use a lot of powershell/command line tasks in TFS to do that. And more annoying is that I have to do that for each project in solution. Are you going to simplify this experience before RTM?

**Comment by tuespetre** [comment]
I would imagine so. I only found out about the dotnet CLI a few days ago. There is a lot changing yet between RC1 and RTM, and the TFS team have stated that they are going to wait to smooth things out.

Now a step could be written for Bower regardless; why not submit one to the VsoAgentTasks repo for us? :)

**Comment by GuardRex** [comment]
Hey @tuespetre whaz up. I can see the wait there. When you think about how the command structure is going to change for dotnet CLI, I don't blame them for waiting just a sec. That's actually "in design" really. They're still working out the details. It's worth the wait. https://github.com/dotnet/cli

TFS ... I have VSO issues https://github.com/aspnet/Tooling/issues/271, too, under investigation ... ugh! MS Marketing ... you could kill them ... sorry .... I meant ... what? VSTS ... "Visual Studio Team Services" ... good grief. btw- Tell MS Marketing that I'm still using "SQL Azure," and I'm not changing that. :smile:

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
