### ISSUE TITLE
MVC DefaultActionSelector.SelectBestActions() question.

### ISSUE THREAD

**Issue by MarkPflug** [aspnet/Home#1179]
Not sure if this is the right place to ask question about MVC, or if I should ask it in the MVC project.

I'm trying to support allowing modules to be hosted in an application and allow them to use MVC, but this would result in AmbiguousActionException when they have conflicting controller names. I want to disambiguate this conflict based on information about the request, and the assembly that contains the controller. I'm not sure the best way to to do this, but I was digging through the MVC source trying to find the best place to inject things. IActionSelector seems to be the right place, but ideally I don't want to fully implement it when the DefaultActionSelector does most of the work that I want, I just want to tweak its behavior. Indeed, it even has a method "SelectBestActions" that sounds like exactly the hook that I want.

SelectBestActions takes a list of candidate ActionDescriptor, and returns a filtered list of candidates. However, the current Request/RouteContext is not available, so there seems to be no way to actually filter the list based on the current request. Is the intent that this method can only use "static" context that is injected into the CustomActionSelector? Or would it make sense to also change the signature of SelectBestActions to also receive the RouteContext?

**Comment by rynowak** [comment]
I would start by writing an `IActionConstraint` that expresses your criteria and applying that to the actions/controllers in question.

Replacing/overriding the action selector is a big hammer, and you can only do it once. You can have arbitrarily many separate concerns handled be separate action constraints.

Here's an example of using `IActionConstraint` to implement versioning: https://github.com/aspnet/Mvc/tree/dev/test/WebSites/VersioningWebSite (look at the attribute classes first)

**Comment by MarkPflug** [comment]
Thanks @rynowak. I think I can make that work for what I'm trying to accomplish.
Follow up question:
I want to apply this action constraint to all actions, and I'd like to not have to apply an attribute to all my controllers and/or actions, or a derive from a special controller base. Is the correct way to do something like that via an `IApplicationModelConvention`? In the `Apply` method I can then enumerate all controllers and add the constraint to the ActionConstraints. Is that how the IApplicationModelConvention is intended to be used?

**Comment by rynowak** [comment]
>  In the Apply method I can then enumerate all controllers and add the constraint to the ActionConstraints. Is that how the IApplicationModelConvention is intended to be used?

Yes, that's exactly right!

**Comment by MarkPflug** [comment]
@rynowak Rad, thanks!
