### ISSUE TITLE
myget.org policy violation?

### ISSUE THREAD

**Issue by nguyenm100** [aspnet/Home#1180]
Noticed:  https://www.myget.org/policies/terms#title0

Subscription. Each user of Services offered by MyGet, through the Web Site at www.myget.org or other URLs, must be allocated an individual Subscription, whether they access the service directly or indirectly.

It won't be tenable for many companies to abide by this policy.  Can this also be published on NuGet?

**Comment by Eilon** [comment]
I'm following up on this with the MyGet people.

**Comment by Eilon** [comment]
But BTW we do publish official releases on NuGet.org, e.g. https://www.nuget.org/packages/Microsoft.AspNet.Mvc

On there you'll see the alphas, betas, RCs, and RTM builds of the product.

We use MyGet only for the daily/nightly builds.

**Comment by xavierdecoster** [comment]
The clause is intended to apply only to secured feeds, requiring authentication. The MyGet ToS will be updated to reflect that and make it more clear. In other words, I can confirm you are *not* violating the MyGet ToS.

**Comment by nguyenm100** [comment]
Hey thanks guys.  @Eilon, should https://github.com/aspnet/Home/wiki/Configuring-the-feed-used-by-dnu-to-restore-packages clarify the publishing to both feeds (it just casually mentions dnu uses nuget but the vnext is on myget)?

**Comment by davidfowl** [comment]
official releases are on nuget.org, ci builds are on myget.
