### ISSUE TITLE
dnu restore using old version of Newtonsoft.Json.Dll

### ISSUE THREAD

**Issue by ArryMatt** [aspnet/Home#1182]
When doing a dnu restore I get the following error:

System.MissingMethodException: Method not found: 'Newtonsoft.Json.Linq.JValue Newtonsoft.Json.Linq.JValue.CreateNull()'.

Reading up on this I've found that older versions of Newtonsoft.Json do not have the method CreateNull().  

I had v6.0.0.0 in my GAC, which I have removed and added v7.0.0.0.  This did not help.

I found a couple of old versions in Native Image directories in my GAC, which I have removed, still no help.

Searching my machine finds a lot of copies of this.  So, how can I find out where it's getting the bad one from and either remove it or tell it to use a different one?

**Comment by davidfowl** [comment]
You can't tell it to use a different one. You could try to use something like process explorer to see where it's loading that dll from.

**Comment by ArryMatt** [comment]
Many thanks, process explorer found the dodgy version and once deleted it now works.
