### ISSUE TITLE
Issues of VS's integration with client side code building tools

### ISSUE THREAD

**Issue by johnx7271** [aspnet/Home#1183]
There are some tool sets for client side code building, e.g.  r.js, webpack, and Fis3. Among these, I found Fis3 the most comprehensive and powerful one: https://github.com/fex-team/fis3. Briefly, Fis3 can do the following:  uglify and/or merge js/css resources external or inline, csssprite  and merge,  compact html, inline resources (like small images, templates etc).  With these capability, client side code can be optimized greatly.
The issue here is that, Fis3 aggressively modify the html files ( and the aspx, and cshtml files likewise), so its integration with vs build is an issue. .Net 5 and DNX have a separate www folder under the project root, this step can be helpful to incorporate Fis3 into vs build flow, but a more closer and careful study is needed for better and smooth integration of client side build tool into VS build.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
