### ISSUE TITLE
Split function not working in RC1

### ISSUE THREAD

**Issue by nrkarthick** [aspnet/Home#1184]
var temp = "123456-12569";
var test = temp.Split('-').Last();

After upgrading to RC1, split function gives the following error.

'StringValues' does not contain a definition for 'Split' and no extension method 'Split' accepting a first argument of type 'StringValues' could be found (are you missing a using directive or an assembly reference?)

**Comment by Tratcher** [comment]
That's not enough context to reproduce the issue. Can you share a complete method that reproduces this issue?

StringValues has an implicit converter for string, but it shouldn't happen unless `temp` or `test` is passed into or returned from an API that uses StringValues.

**Comment by nrkarthick** [comment]
var temp = "123456-12569";
     var test = temp.Split('-').Last();
     return test;

From above function, I got result as `'12569'` in `Beta7` but after the upgrade to RC1, it gives error as mentioned in my issue.

**Comment by davidfowl** [comment]
@nrkarthick Make a sample project put it on github with instructions on how to reproduce the problem.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
