### ISSUE TITLE
Suggestion: Utility to ease IIS deployments

### ISSUE THREAD

**Issue by johnnyreilly** [aspnet/Home#1185]
I don't know if you're aware of @filipw's post on getting ASP.Net 5 up and running with IIS:

http://www.strathweb.com/2015/12/running-asp-net-5-website-on-iis/

It's great that he wrote the post but unfortunate that he felt the need to.  In enterprise situations it's common practice (still) for developers to be kept at arms length from production machines. This makes easing that initial deployment kind of a necessity. 

Speaking as someone who's very keen to get ASP.Net 5 into production it would help if there was some kind of utility to handle the points raised by Filip's post.  

Do you have any plans to put something like this together?

**Comment by GuardRex** [comment]
@johnnyreilly 

The official doc is here: https://docs.asp.net/en/latest/publishing/iis.html
My very unofficial notes with issues is here: https://github.com/aspnet/Hosting/issues/364#issuecomment-148567294
I have a related suggestion here for a doc dealing with IIS hosting scenarios: https://github.com/aspnet/Docs/issues/786

I think the blog post you mention has a couple of factual inaccuracies and some other minor problems:

1. Using the default application pool identity with pass-through authentication does not require a permissions change on the `wwwroot` folder (it requires a change if a non-administrator account identity is used AFAIK as reported by others). 
2. The `stdoutLogFile` should not have a file extension (it's added with a timestamp automatically).
3. I believe the default output path is not `bin\output` (I think its in `artifacts`).
4. The HttpPlatformHandler page has historically not been kept up to date with the release of the module. This won't be a problem later; but for now, I'd recommend folks get it from Announcements, Release Notes, or the official docs.
5. The section regarding an unresponsive application contains incorrect information and bad advice. If problems develop, I hope people go to the official doc first, then check the issues I link in my comment. Next, they should just ask on Disqus or here.
6. Several of the points are going to change when dotnet CLI hits, so this blog is going to become stale soon.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
