### ISSUE TITLE
dnvminstall.sh should check for ~/.bashrc first

### ISSUE THREAD

**Issue by fsoikin** [aspnet/Home#1186]
As it is currently coded, `dnvminstall.sh` first [tries to add its hooks to](https://github.com/aspnet/Home/blob/dev/dnvminstall.sh#L49) `~/.bash_profile`, and only if that doesn't exist, goes for `~/.bashrc`. This behavior essentially [prevents the hooks from working in non-login terminals](https://www.gnu.org/software/bash/manual/bashref.html#Bash-Startup-Files-1) (such as Gnome-started graphical one), which source `~/.bashrc`, but not `~/.bash_profile`.

Doing it the other way around would be beneficial, and not harmful, because `~/.bashrc` should normally be sourced from `~/.bash_profile`, and indeed, it is usually the default.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
