### ISSUE TITLE
ASP.NET 5 beta8 IIS publish static content doesn't work

### ISSUE THREAD

**Issue by alekoo73** [aspnet/Home#1187]
have very simple ASP.NET 5 app , just one page with static content and js. after upgrading to beta 8, somehow I managed to run my app ,except that all static files requests return 302 (redirect) status.

Page itself is rendered without any problem , only static files don't return form IIS.

I installed HttpPlatformHandler v1.2 also I have app.UseStaticFiles(); in my startup.cs configured everything properly. Before upgrade everything was working OK , and also in IIS Express my app runs smoothly. I tried to google , read all discussions in GitHub.But there seems no solution to the problem.

**Comment by GuardRex** [comment]
@alekoo73 I'd recommend moving up from beta8. The most stable current release is rc1-update1/rc1-final. Lots of things changed.

Where are your static files ... in `wwwroot`? Can you show your `Configure` method in `Startup.cs`? Can you show your dependencies in `project.json`?

**Comment by alekoo73** [comment]
Yes they are in wwwroot . Just one page app wityh single view and single layout page.I don't have any virtual directories

This is my startup method

```

            var builder = new ConfigurationBuilder()
           .SetBasePath(appEnv.ApplicationBasePath)
           .AddJsonFile("config.json")
           .AddEnvironmentVariables();

            if (env.IsDevelopment())
            {

            }
            builder.AddEnvironmentVariables();
            Configuration = builder.Build();

```

and that one is project.json

```
{
  "webroot": "wwwroot",
  "userSecretsId": "aspnet5-MyTest.Front-8886551f-7c7e-4ac8-b076-c8791ad27c85",
  "version": "1.0.0-*",

  "dependencies": {
    "Microsoft.AspNet.Mvc": "6.0.0-beta8",
    "Microsoft.AspNet.StaticFiles": "1.0.0-beta8",
    "Microsoft.Framework.Configuration.Json": "1.0.0-beta8",
    "Microsoft.AspNet.IISPlatformHandler": "1.0.0-beta8",
    "Microsoft.AspNet.Server.Kestrel": "1.0.0-beta8",
    "Microsoft.AspNet.Diagnostics":"1.0.0-beta8"
  },

  "commands": {
    "web": "Microsoft.AspNet.Server.Kestrel"
  },

  "frameworks": {
    "dnx451": {
      "dependencies": {
      }
    },
    "dnxcore50": { }
  },

  "exclude": [
    "wwwroot",
    "node_modules",
    "bower_components"
  ],
  "publishExclude": [
    "node_modules",
    "bower_components",
    "**.xproj",
    "**.user",
    "**.vspscc"
  ],
  "scripts": {
    "prepublish": [ "npm install", "bower install", "grunt uglify" ]
  }
}
```


I tried to move to rc1-update1 ,but meet some problem .Not all assemblies are published to nuget.

**Comment by GuardRex** [comment]
... what about your Configure method in Startup.vs? What do you have there?

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
