### ISSUE TITLE
If using nightly builds, are we about to break with the move to dotnet CLI?

### ISSUE THREAD

**Issue by GuardRex** [aspnet/Home#1191]
@davidfowl The changes coming soon for dotnet CLI look like they will break us, perhaps in VS, perhaps on the server (i.e., HttpPlatformHandler), or both. What's the outlook for those of us using nightly builds and dotnet CLI?

I wonder if at some point I should get off of nightly builds and freeze my runtime version and packages at their current versions and ride out all the following changes until `rc2-final` hits. Sound good? If so, could you cats fire out an Announcement "Freeze!" to signal when we should do that?

**Comment by Tratcher** [comment]
Yes there will be breaks, but they should be gradual. You saw the recent hosting changes. Now that there's just one command and it points to your app assembly it should be easy enough to transition from `dnx web` to `dotnet MyApp`, or just `MyApp.exe`.  If you're concerned about breaks you can snapshot your dependency versions and increment them manually as needed.

**Comment by GuardRex** [comment]
I made the hosting changes ... works great here, so I should be ready.

Sounds like you're suggesting that `processPath="%DNX_PATH%"` will automatically take care of that final transition with runtime/package changes that are coming soon for `dotnet`. If so, I'm good.
