### ISSUE TITLE
Configuring custom config section in RC2 (latest dev build)

### ISSUE THREAD

**Issue by rohitshrivastava04** [aspnet/Home#1193]
Hi

I had a running configuration with RC1 but as soon as I upgraded to RC2, there is a compile time error at

    public void ConfigureServices(IServiceCollection services)
    {
          services.Configure<RefDataConfigs>(Configuration.GetSection(REF_DATA_CONFIG_KEY));
    }

Seems like IServiceCollection.Configure started taking Action whereas it used to take IConfigurationSection.

    Error   CS1503  Argument 2: cannot convert from 'Microsoft.Extensions.Configuration.IConfigurationSection' to 'System.Action<MyCustomTyppe>'    
Is there any easy way to fix this or I have to write a function which will convert IConfigurationSection to my custom type?

**Comment by pranavkm** [comment]
The `Configure` method got moved to a different package. Add a reference to the `Microsoft.Extensions.Options.ConfigurationExtensions` package and add a `using Microsoft.Extensions.DependencyInjection;` if you aren't already doing so.

**Comment by rohitshrivastava04** [comment]
Thanks worked.

**Comment by nukuuk** [comment]
+1 Thanks worked for me too!

**Comment by Blackbaud-SteveBrush** [comment]
Works for me as well. After 10 hours of research, stumbled on this issue. Is this documented anywhere?

**Comment by pranavkm** [comment]
@Blackbaud-SteveBrush we usually post breaking changes like these to the Announcements repo (https://github.com/aspnet/Announcements/issues). But I can't tell if this change was ever documented.

**Comment by jozefizso** [comment]
@pranavkm can you add this change to the Announcements issues? This change is very hard to resolve as no blogpost mentions change to Options configuration when upgrading from RC1 to RC2, nor the Options repository mentions this.

**Comment by RonCass** [comment]
This just helped me out as well, thanks.

**Comment by pranavkm** [comment]
@HaoK - was there an announcement for this change?

**Comment by taspeotis** [comment]
I think this should be included in the [migration guide](https://docs.asp.net/en/latest/migration/rc1-to-rc2.html).

**Comment by xShivan** [comment]
I agree with @taspeotis. I had a hard time upgrading my application because of this.

**Comment by HaoK** [comment]
No, doesn't look like there was, I will file one now

**Comment by pranavkm** [comment]
Thanks @HaoK . Here's the announcement for the change - https://github.com/aspnet/Announcements/issues/180

**Comment by ASBrattsev** [comment]
It work for me after rewrite dependencie: 
"Microsoft.Extensions.Options.ConfigurationExtensions": "1.0.1" to "1.0.0" version.
Thanks!
