### ISSUE TITLE
How to disable Edit and Continue??

### ISSUE THREAD

**Issue by muratg** [aspnet/Home#1196]
_From @MrAndMrsK on December 23, 2015 18:36_

When I'm working on client-side code I don't need the debugger actually engaged and I want to be able to edit my html/js/ts/css/whatever and just refresh my browser and see the updates.  But I can't edit when I'm debugging and IIS Express quits when I can edit.  In ASP.NET vBefore the first thing to do was disable Edit and Continue so that IIS Express would stay running and available.  I cannot find that option in the Project properties anymore.

Is there a way to achieve it in ASP.NET 5?

Thanks!

_Copied from original issue: aspnet/Universe#340_

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
