### ISSUE TITLE
Running the HelloMvc sample as per Readme.md does not work

### ISSUE THREAD

**Issue by markmnl** [aspnet/Home#1201]
Diligently following the Readme instructions today:

> ...
> 3.Run  dnu restore  to restore the packages required by that sample.
> 4.You should see a bunch of output as all the dependencies of the app are downloaded from MyGet.
> 5.Run the sample using the appropriate DNX command: 
>    ◦For the console app run  dnx run .
>    ◦For the web apps run  dnx kestrel 
> ...

produces:

```
...
Restore complete, 132922ms elapsed

NuGet Config files used:
    C:\Users\markm\AppData\Roaming\NuGet\nuget.config
    H:\Dev\aspnet\home\samples\latest\nuget.config

Feeds used:
    https://www.myget.org/F/aspnetvnext/api/v2/
    https://nuget.org/api/v2/

Installed:
    215 package(s) to C:\Users\markm\.dnx\packages

H:\Dev\aspnet\home\samples\latest\HelloMvc>dnx run
Error: H:\Dev\aspnet\home\samples\latest\HelloMvc\Startup.cs(16,27): DNX,Version
=v4.5.1 error CS1061: 'ILoggerFactory' does not contain a definition for 'AddCon
sole' and no extension method 'AddConsole' accepting a first argument of type 'I
LoggerFactory' could be found (are you missing a using directive or an assembly
reference?)

H:\Dev\aspnet\home\samples\latest\HelloMvc>dnx kestrel
Error: Unable to load application or execute command 'kestrel'. Available comman
ds: web.

H:\Dev\aspnet\home\samples\latest\HelloMvc>dnx web
'Microsoft.AspNet.Server.Kestrel' does not contain a 'Program' type suitable for
 an entry point
```

:(

**Comment by Jeffiy** [comment]
Could you run `dnvm list` and type here? I guess you use the RC1 of dnx, but you should use RC2 for the latest HelloMvc sample.

**Comment by markmnl** [comment]
H:\Dev\aspnet\home\samples\latest\HelloMvc>dnvm list

    Active Version         Runtime Architecture Location                     Alias
    ------ -------         ------- ------------ --------                     -----
      *    1.0.0-rc2-16351 clr     x86          C:\Users\markm\.dnx\runtimes def...

**Comment by Jeffiy** [comment]
Oops, I looked the latest HelloMvc sample, it passable didn't update to RC2, you can try to use RC1. `dnvm upgrade`

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
