### ISSUE TITLE
Kestrel stuck with MVC app on Debian

### ISSUE THREAD

**Issue by brewerof** [aspnet/Home#1204]
I tried to run HelloMvc app from asp.net 5 samples on my debian machine, it worked well, after this I created very simple asp.net 5 mvc app in visual studio with rc1 update and copied src folder on debian.
I made "dnu restore", then "dnx web", but nothing happened, there was no response from kestrel.
After this I tried to run HelloMvc app again, but it stuck too. Anyway, HelloWeb app running fine, and 
my another test app, that I created in VS, with WebApi template, running fine too.

As I see in log, looks like some problems with Microsoft.AspNet.Razor.Runtime

So, what can I do with this?

HelloMvc log is below.

Information: [Bootstrapper] Runtime Framework: DNX,Version=v4.5.1
Information: [ApplicationHostContext] Using Lock File Target: DNX,Version=v4.5.1/debian.8-x64
Information: [DefaultHost]: Project path: /home/brewer/Documents/samples/home/samples/1.0.0-rc1-update1/HelloMvc
Information: [DefaultHost]: Project root: /home/brewer/Documents/samples/home/samples/1.0.0-rc1-update1/HelloMvc
Information: [DefaultHost]: Project configuration: Debug
Information: [DefaultHost]: Packages path: /root/.dnx/packages
Information: [Breadcrumbs] Breadcrumbs for servicing will not be written because the breadcrumbs folder () does not exist.
Information: [LoaderContainer]: Load name=Microsoft.AspNet.Server.Kestrel
Information: [PackageAssemblyLoader]: Loaded name=Microsoft.AspNet.Server.Kestrel in 4ms
Information: [LoaderContainer]: Load name=Microsoft.AspNet.Hosting, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
Information: [PackageAssemblyLoader]: Loaded name=Microsoft.AspNet.Hosting, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60 in 0ms
Information: [LoaderContainer]: Load name=Microsoft.AspNet.Hosting.Abstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
Information: [PackageAssemblyLoader]: Loaded name=Microsoft.AspNet.Hosting.Abstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60 in 0ms
Information: [LoaderContainer]: Load name=Microsoft.AspNet.Hosting.Server.Abstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
Information: [PackageAssemblyLoader]: Loaded name=Microsoft.AspNet.Hosting.Server.Abstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60 in 0ms
Information: [LoaderContainer]: Load name=Microsoft.Extensions.Configuration, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
Information: [PackageAssemblyLoader]: Loaded name=Microsoft.Extensions.Configuration, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60 in 0ms
Information: [LoaderContainer]: Load name=Microsoft.Extensions.Configuration.Abstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
Information: [PackageAssemblyLoader]: Loaded name=Microsoft.Extensions.Configuration.Abstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60 in 0ms
Information: [LoaderContainer]: Load name=Microsoft.Extensions.Configuration.CommandLine, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
Information: [PackageAssemblyLoader]: Loaded name=Microsoft.Extensions.Configuration.CommandLine, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60 in 0ms
Information: [LoaderContainer]: Load name=Microsoft.Extensions.Configuration.Json, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
Information: [PackageAssemblyLoader]: Loaded name=Microsoft.Extensions.Configuration.Json, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60 in 0ms
Information: [LoaderContainer]: Load name=Microsoft.Extensions.Configuration.EnvironmentVariables, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
Information: [PackageAssemblyLoader]: Loaded name=Microsoft.Extensions.Configuration.EnvironmentVariables, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60 in 0ms
Information: [LoaderContainer]: Load name=Microsoft.Extensions.Logging.Abstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
Information: [PackageAssemblyLoader]: Loaded name=Microsoft.Extensions.Logging.Abstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60 in 0ms
Information: [LoaderContainer]: Load name=Microsoft.Extensions.DependencyInjection.Abstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
Information: [PackageAssemblyLoader]: Loaded name=Microsoft.Extensions.DependencyInjection.Abstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60 in 0ms
Information: [LoaderContainer]: Load name=Microsoft.AspNet.Http.Features, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
Information: [PackageAssemblyLoader]: Loaded name=Microsoft.AspNet.Http.Features, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60 in 0ms
Information: [LoaderContainer]: Load name=Microsoft.Extensions.Primitives, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
Information: [PackageAssemblyLoader]: Loaded name=Microsoft.Extensions.Primitives, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60 in 0ms
Information: [LoaderContainer]: Load name=Microsoft.Extensions.Configuration.FileExtensions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
Information: [PackageAssemblyLoader]: Loaded name=Microsoft.Extensions.Configuration.FileExtensions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60 in 0ms
Information: [LoaderContainer]: Load name=Microsoft.AspNet.FileProviders.Abstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
Information: [PackageAssemblyLoader]: Loaded name=Microsoft.AspNet.FileProviders.Abstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60 in 0ms
Information: [LoaderContainer]: Load name=Microsoft.Extensions.Logging, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
Information: [PackageAssemblyLoader]: Loaded name=Microsoft.Extensions.Logging, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60 in 0ms
Information: [LoaderContainer]: Load name=Microsoft.Extensions.DependencyInjection, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
Information: [PackageAssemblyLoader]: Loaded name=Microsoft.Extensions.DependencyInjection, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60 in 0ms
Information: [LoaderContainer]: Load name=System.Diagnostics.DiagnosticSource, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
Information: [PackageAssemblyLoader]: Loaded name=System.Diagnostics.DiagnosticSource, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a in 0ms
Information: [LoaderContainer]: Load name=Microsoft.AspNet.Http.Abstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
Information: [PackageAssemblyLoader]: Loaded name=Microsoft.AspNet.Http.Abstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60 in 0ms
Information: [LoaderContainer]: Load name=Microsoft.AspNet.Http, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
Information: [PackageAssemblyLoader]: Loaded name=Microsoft.AspNet.Http, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60 in 0ms
Information: [LoaderContainer]: Load name=Microsoft.AspNet.FileProviders.Physical, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
Information: [PackageAssemblyLoader]: Loaded name=Microsoft.AspNet.FileProviders.Physical, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60 in 0ms
Information: [LoaderContainer]: Load name=HelloMvc
Warning: [ApplicationHostContext] Lock File Target is Runtime-agnostic! This is generally not good.
Information: [ApplicationHostContext] Using Lock File Target: DNX,Version=v4.5.1/
Information: [LibraryExporter]: ExportProject(HelloMvc, , DNX,Version=v4.5.1, Debug)
Warning: [ApplicationHostContext] Lock File Target is Runtime-agnostic! This is generally not good.
Information: [ApplicationHostContext] Using Lock File Target: DNX,Version=v4.5.1/
Information: [LibraryExporter]: GetProjectReference(Microsoft.Dnx.Compilation.CSharp.RoslynProjectCompiler, HelloMvc, DNX,Version=v4.5.1, )
Information: [LibraryExporter]: Resolving references for 'HelloMvc' 
Information: [LibraryExporter]: Resolved 87 references for 'HelloMvc' in 22ms
Information: [RoslynCompiler]: Compiling 'HelloMvc'
Information: [LoaderContainer]: Load name=System.Security.Cryptography.Algorithms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
Information: [LoaderContainer]: Load name=System.Security.Cryptography.Primitives, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
Information: [LoaderContainer]: Load name=System.IO.FileSystem, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null
Information: [RoslynCompiler]: Compiled 'HelloMvc' in 624ms
Information: [CompilationContext]: Generating resources for HelloMvc
Information: [CompilationContext]: Generated resources for HelloMvc in 6ms
Information: [RoslynProjectReference]: Emitting assembly for HelloMvc
Information: [RoslynProjectReference]: Emitted HelloMvc in 1299ms
Information: [ProjectAssemblyLoader]: Loaded name=HelloMvc in 2252ms
Information: [LoaderContainer]: Load name=Microsoft.AspNet.Mvc, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
Information: [PackageAssemblyLoader]: Loaded name=Microsoft.AspNet.Mvc, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60 in 0ms
Information: [LoaderContainer]: Load name=Microsoft.AspNet.Mvc.Core, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
Information: [PackageAssemblyLoader]: Loaded name=Microsoft.AspNet.Mvc.Core, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60 in 0ms
Information: [LoaderContainer]: Load name=Microsoft.AspNet.Mvc.ApiExplorer, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
Information: [PackageAssemblyLoader]: Loaded name=Microsoft.AspNet.Mvc.ApiExplorer, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60 in 0ms
Information: [LoaderContainer]: Load name=Microsoft.AspNet.Mvc.ViewFeatures, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
Information: [PackageAssemblyLoader]: Loaded name=Microsoft.AspNet.Mvc.ViewFeatures, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60 in 0ms
Information: [LoaderContainer]: Load name=Microsoft.AspNet.Mvc.Razor, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
Information: [PackageAssemblyLoader]: Loaded name=Microsoft.AspNet.Mvc.Razor, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60 in 0ms
Information: [LoaderContainer]: Load name=Microsoft.AspNet.Mvc.DataAnnotations, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
Information: [PackageAssemblyLoader]: Loaded name=Microsoft.AspNet.Mvc.DataAnnotations, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60 in 0ms
Information: [LoaderContainer]: Load name=Microsoft.AspNet.Mvc.Formatters.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
Information: [PackageAssemblyLoader]: Loaded name=Microsoft.AspNet.Mvc.Formatters.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60 in 0ms
Information: [LoaderContainer]: Load name=Microsoft.AspNet.Mvc.Cors, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
Information: [PackageAssemblyLoader]: Loaded name=Microsoft.AspNet.Mvc.Cors, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60 in 0ms
Information: [LoaderContainer]: Load name=Microsoft.Extensions.OptionsModel, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
Information: [PackageAssemblyLoader]: Loaded name=Microsoft.Extensions.OptionsModel, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60 in 0ms
Information: [LoaderContainer]: Load name=Microsoft.AspNet.Routing, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
Information: [PackageAssemblyLoader]: Loaded name=Microsoft.AspNet.Routing, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60 in 0ms
Information: [LoaderContainer]: Load name=Microsoft.AspNet.Mvc.Abstractions, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
Information: [PackageAssemblyLoader]: Loaded name=Microsoft.AspNet.Mvc.Abstractions, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60 in 0ms
Information: [LoaderContainer]: Load name=Microsoft.Extensions.MemoryPool, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
Information: [PackageAssemblyLoader]: Loaded name=Microsoft.Extensions.MemoryPool, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60 in 0ms
Information: [LoaderContainer]: Load name=Microsoft.AspNet.Authorization, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
Information: [PackageAssemblyLoader]: Loaded name=Microsoft.AspNet.Authorization, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60 in 0ms
Information: [LoaderContainer]: Load name=Microsoft.AspNet.DataProtection, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
Information: [PackageAssemblyLoader]: Loaded name=Microsoft.AspNet.DataProtection, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60 in 0ms
Information: [LoaderContainer]: Load name=Microsoft.AspNet.Antiforgery, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
Information: [PackageAssemblyLoader]: Loaded name=Microsoft.AspNet.Antiforgery, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60 in 0ms
Information: [LoaderContainer]: Load name=Microsoft.Extensions.WebEncoders, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
Information: [PackageAssemblyLoader]: Loaded name=Microsoft.Extensions.WebEncoders, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60 in 0ms
Information: [LoaderContainer]: Load name=Microsoft.Extensions.WebEncoders.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
Information: [PackageAssemblyLoader]: Loaded name=Microsoft.Extensions.WebEncoders.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60 in 0ms
Information: [LoaderContainer]: Load name=Microsoft.AspNet.Html.Abstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
Information: [PackageAssemblyLoader]: Loaded name=Microsoft.AspNet.Html.Abstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60 in 0ms
Information: [LoaderContainer]: Load name=Microsoft.AspNet.Cryptography.Internal, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
Information: [PackageAssemblyLoader]: Loaded name=Microsoft.AspNet.Cryptography.Internal, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60 in 0ms
Information: [LoaderContainer]: Load name=Microsoft.AspNet.DataProtection.Abstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
Information: [PackageAssemblyLoader]: Loaded name=Microsoft.AspNet.DataProtection.Abstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60 in 0ms
Information: [LoaderContainer]: Load name=Microsoft.AspNet.Mvc.Razor.Host, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
Information: [PackageAssemblyLoader]: Loaded name=Microsoft.AspNet.Mvc.Razor.Host, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60 in 0ms
Information: [LoaderContainer]: Load name=Microsoft.AspNet.Razor, Version=4.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
Information: [PackageAssemblyLoader]: Loaded name=Microsoft.AspNet.Razor, Version=4.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60 in 0ms
Information: [LoaderContainer]: Load name=Microsoft.Extensions.Caching.Abstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
Information: [PackageAssemblyLoader]: Loaded name=Microsoft.Extensions.Caching.Abstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60 in 0ms
Information: [LoaderContainer]: Load name=Microsoft.Extensions.Caching.Memory, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
Information: [PackageAssemblyLoader]: Loaded name=Microsoft.Extensions.Caching.Memory, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60 in 0ms
Information: [LoaderContainer]: Load name=Microsoft.AspNet.Cors, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
Information: [PackageAssemblyLoader]: Loaded name=Microsoft.AspNet.Cors, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60 in 0ms
Information: [LoaderContainer]: Load name=Microsoft.Extensions.Logging.Console, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
Information: [PackageAssemblyLoader]: Loaded name=Microsoft.Extensions.Logging.Console, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60 in 0ms
Information: [LoaderContainer]: Load name=Microsoft.AspNet.IISPlatformHandler, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
Information: [PackageAssemblyLoader]: Loaded name=Microsoft.AspNet.IISPlatformHandler, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60 in 0ms
Information: [LoaderContainer]: Load name=Microsoft.AspNet.Diagnostics, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
Information: [PackageAssemblyLoader]: Loaded name=Microsoft.AspNet.Diagnostics, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60 in 0ms
[37mverb[39m[37m: Microsoft.AspNet.Hosting.Internal.HostingEngine[4][39m
[97m      Hosting starting[39m
[37mverb[39m[37m: Microsoft.AspNet.Hosting.Internal.HostingEngine[5][39m
[97m      Hosting started[39m
Hosting environment: Production
Now listening on: http://*:5004
Application started. Press Ctrl+C to shut down.
Information: [LoaderContainer]: Load name=System.Numerics.Vectors, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
Information: [PackageAssemblyLoader]: Loaded name=System.Numerics.Vectors, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a in 0ms
[32minfo[39m[37m: Microsoft.AspNet.Hosting.Internal.HostingEngine[1][39m
[97m      Request starting HTTP/1.1 GET http://localhost:5004/  [39m
Information: [LoaderContainer]: Load name=Microsoft.AspNet.Http.Extensions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
Information: [PackageAssemblyLoader]: Loaded name=Microsoft.AspNet.Http.Extensions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60 in 0ms
Information: [LoaderContainer]: Load name=Microsoft.Net.Http.Headers, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
Information: [PackageAssemblyLoader]: Loaded name=Microsoft.Net.Http.Headers, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60 in 0ms
Information: [LoaderContainer]: Load name=Microsoft.Extensions.Localization.Abstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
Information: [PackageAssemblyLoader]: Loaded name=Microsoft.Extensions.Localization.Abstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60 in 0ms
Information: [LoaderContainer]: Load name=Newtonsoft.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed
Information: [PackageAssemblyLoader]: Loaded name=Newtonsoft.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed in 0ms
Information: [ApplicationHostContext] Using Lock File Target: DNX,Version=v4.5.1/debian.8-x64
[37mverb[39m[37m: Microsoft.AspNet.Routing.Template.TemplateRoute[0][39m
[97m      Request successfully matched the route with name 'default' and template '{controller=Home}/{action=Index}/{id?}'.[39m
[37mverb[39m[37m: Microsoft.AspNet.Mvc.Infrastructure.MvcRouteHandler[1][39m
[97m      Executing action MvcSample.Web.HomeController.Index[39m
Information: [LoaderContainer]: Load name=Microsoft.AspNet.WebUtilities, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
Information: [PackageAssemblyLoader]: Loaded name=Microsoft.AspNet.WebUtilities, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60 in 0ms
[32minfo[39m[37m: Microsoft.AspNet.Mvc.Controllers.ControllerActionInvoker[1][39m
[97m      Executing action method MvcSample.Web.HomeController.Index with arguments () - ModelState is Valid'[39m
[37mverb[39m[37m: Microsoft.AspNet.Mvc.Controllers.ControllerActionInvoker[2][39m
[97m      Executed action method MvcSample.Web.HomeController.Index, returned result Microsoft.AspNet.Mvc.ViewResult.'[39m
Information: [LoaderContainer]: Load name=Microsoft.AspNet.Razor.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
Information: [PackageAssemblyLoader]: Loaded name=Microsoft.AspNet.Razor.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60 in 0ms

**Comment by davidfowl** [comment]
What version of mono?

**Comment by brewerof** [comment]
Mono JIT compiler version 4.2.1 (Stable 4.2.1.102/6dd2d0d Thu Nov 12 09:52:44 UTC 2015)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	LLVM:          supported, not enabled.
	GC:            sgen

**Comment by brewerof** [comment]
I tried do the same but with CoreCLR instead Mono, and all working well. So something wrong with Mono
