### ISSUE TITLE
How to filter log messages being passed to a logging provider?

### ISSUE THREAD

**Issue by girishjjain** [aspnet/Home#1205]
It appears to me that a logging provider gets all log messages including ones generated by aspnet framework. Is there a way to filter that? For example, I added a logging provider as follows:

	loggerFactory.AddTraceSource(
		new SourceSwitch("SystemSwitch", "Verbose"),
		new TextWriterTraceListener("ServiceLog.txt", "SystemTrace"));

And I see whole lot of information in the ServiceLog.txt file, as follows:

	Microsoft.AspNet.Hosting.Internal.HostingEngine Verbose: 4 : Hosting starting
	Microsoft.AspNet.Hosting.Internal.HostingEngine Verbose: 5 : Hosting started
	Microsoft.AspNet.Hosting.Internal.HostingEngine Information: 1 : Request starting HTTP/1.1 DEBUG http://localhost:50193/ text/html 
	Microsoft.AspNet.Hosting.Internal.HostingEngine Information: 1 : Request starting HTTP/1.1 GET http://localhost:50193/api/values  
	..
	SystemTrace Verbose: 0 : 12/29/2015 22:02:18: Invoking method UserRepository::GetUser

But I want to use this logging provider only for service specific log entries i.e. the last log entry above which is logged by my service code. So currently, I see log entries for framework events too. How do I filter it for a certain logging provider? Or what would be the recommended approach to achieve this?

**Comment by girishjjain** [comment]
Can someone confirm whether following understanding is correct? - A logging provider added to loggerFactory instance would receive all events including aspnet framework events.

This would help me confirm the behavior I am seeing and then I can work on some another solution for application specific event logging. Thanks.

**Comment by davidfowl** [comment]
> Can someone confirm whether following understanding is correct? - A logging provider added to loggerFactory instance would receive all events including aspnet framework events.

Yes, all logging providers get all messages. Filtering that provider is based on the implementation of that specific provider. All of the events that come from ASP.NET are `Microsoft.AspNet.*` so you should be able to filter either based on that or by only including events from your application.

**Comment by girishjjain** [comment]
Thanks David for responding. I figured that out after going through source code in https://github.com/aspnet/Logging project. 

Most likely people would like to see filtered events/trace/log messages being logged. It took a bit of learning to figure out how to achieve the same when using tracing provider, especially with most people using tracing in ASP.NET 4.x projects would be achieving the same by using system.diagnostics configuration in web.config file, which makes it super easy to use. There are some new things to learn when using trace listeners with ASP.NET 5 logging.

For the benefit of other developers trying to use tracing with ASP.NET 5 projects, I've written a post for how to filter using trace listeners and also learn about things to watch for when using certain trace listeners.

http://girishjjain.com/blog/post/ASPNET-5-Logging-using-TraceSource-and-How-to-Filter-Log-Entries.aspx
