### ISSUE TITLE
SN issues with current System.Diagnostics.DiagnosticSource

### ISSUE THREAD

**Issue by benaadams** [aspnet/Home#1207]
![Diagnositics](http://aoa.blob.core.windows.net/aspnet/diag.png)

> System.IO.FileLoadException : Could not load file or assembly 'System.Diagnostics.DiagnosticSource, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. Strong name validation failed. (Exception from HRESULT: 0x8013141A)
      ---- System.Security.SecurityException : Strong name validation failed. (Exception from HRESULT: 0x8013141A)
      Stack Trace:
           at Microsoft.AspNet.Hosting.WebApplicationBuilder.BuildHostingServices()
           at Microsoft.AspNet.Hosting.WebApplicationBuilder.Build()
        I:\Work\GitHub\KestrelHttpServer\test\Microsoft.AspNet.Server.Kestrel.FunctionalTests\PathBaseTests.cs(97,0): at Microsoft.AspNet.Server.Kestrel.FunctionalTests.PathBaseTests.<TestPathBase>d__5.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

**Comment by pranavkm** [comment]
This will get fixed in tomorrow's build of CoreCLR. For now, you might want to consider using `sn -Vr` to turn off strong name verification for this assembly. `System.Text.Encodings.Web` has a similar issue.

**Comment by benaadams** [comment]
This is resolved now.

**Comment by jruckert** [comment]
Same issue again 
![image](https://cloud.githubusercontent.com/assets/4064588/12131833/072d043e-b466-11e5-8c58-f1eba4bbb180.png)

**Comment by benaadams** [comment]
Yep; CI is failing again

**Comment by Eilon** [comment]
I think this should now be fixed again... We added more checks for this prior to publishing so hopefully this doesn't return...

**Comment by kscott5** [comment]
@davidfowl  Why change entry point of Web Hosted Applications on rc2? It now requires a void Main(...) method in Startup.cs but throws the following error:
![capture2](https://cloud.githubusercontent.com/assets/132991/12432536/76ae0f50-bec1-11e5-97a4-0a631bdeccb1.PNG)

My environment information is listed below:

![capture](https://cloud.githubusercontent.com/assets/132991/12432552/91ac1e96-bec1-11e5-8e58-36d2b4a631b5.PNG)

Help me understanding these changes!

**Comment by davidfowl** [comment]
That has nothing to do with this issue, please open something on ASP.NET home.

**Comment by kscott5** [comment]
Yes, your correct. The image listed the version numbers only which was a bit misleading. I took it as if the assembly version was the CLR/Core CLR version.

Could you explain why now Main as entry point for execution?

 I will open something on home if I can't resolve this issue.

Sent from my T-Mobile 4G LTE Device


-------- Original message --------
From: David Fowler
Date:01/19/2016 3:37 PM (GMT-06:00)
To: aspnet/Home
Cc: Karega Scott
Subject: Re: [Home] SN issues with current System.Diagnostics.DiagnosticSource (#1207)


That has nothing to do with this issue, please open something on ASP.NET home.
