### ISSUE TITLE
Setting Kestrel port from environment variable

### ISSUE THREAD

**Issue by jocull** [aspnet/Home#1208]
I'm using Dokku (like Heroku) to deploy an ASP.NET 5 Docker image, but I'm having trouble getting it to map the port properly.

1. Dokku configures Nginx for you
2. Dokku assigns a randomized web port that the Docker container should speak to
3. The port to use is environment variable PORT = [randomized]

You can't set it manually, so there's no way to lock it to port 5000 (the default).

I tried changing the `ENTRYPOINT` in the Dockerfile to use substitution, but the ENTRYPOINT is not configured at runtime, so that is not possible.

I tried making a startup script instead:

```
#/bin/bash

dnx -p project.json web --server.urls http://0.0.0.0:${PORT}
```

Then in Dockerfile....

```
ENTRYPOINT ["/bin/bash", "./launch"]
```

However the port is STILL coming through as 5000. I have no idea why. How can I work around this?

**Comment by davidfowl** [comment]
What's in the web command entry in `project.json`

**Comment by jocull** [comment]
Just the defaults from Yeoman.

**Comment by jocull** [comment]
I keep trying this, but something else appears to be wrong. The connection is going through, but then 404's after about 60 seconds. I can't tell if it's just something weird in the Kestrel server or if something else is going on.

Apparently 5000 is the expected port. Dokku generates a random *host* port and then links it to container port 5000 (and sets the PORT env variable).

There is a host system Nginx config that then handles the upstream on this and maps it to an appropriate external port. I can verify that all this is working. Could the Kestrel server be rejecting requests because the domain doesn't match the "server.urls" section?

**Comment by jocull** [comment]
Attached the whole project. Feel free to reproduce.

[MyApiApp.zip](https://github.com/aspnet/Home/files/76135/MyApiApp.zip)

**Comment by jocull** [comment]
This has to have something going on with the Nginx (proxy?) configuration. I am able to start the image and expose the port manually and everything is fine. Perhaps gzip or something in the proxy headers?

Nginx config is attached. There is nothing in the include folder, so this is all of it.

```
server {
  listen      [::]:5000;
  listen      5000;
  access_log  /var/log/nginx/aspnet-test-access.log;
  error_log   /var/log/nginx/aspnet-test-error.log;

  location    / {

    gzip on;
    gzip_min_length  1100;
    gzip_buffers  4 32k;
    gzip_types    text/css text/javascript text/xml text/plain text/x-component application/javascript application/x-javascript application/json application/xml  application/rss+xml font/truetype application/x-font-ttf font/opentype application/vnd.ms-fontobject image/svg+xml;
    gzip_vary on;
    gzip_comp_level  6;

    proxy_pass  http://aspnet-test;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection upgrade;
    proxy_set_header Host $http_host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_set_header X-Forwarded-Port $server_port;
    proxy_set_header X-Request-Start $msec;
  }
  include /home/dokku/aspnet-test/nginx.conf.d/*.conf;
}
```

**Comment by jocull** [comment]
Found it -- https://github.com/aspnet/KestrelHttpServer/issues/341
