### ISSUE TITLE
Developer Exception Page is blank if added to IApplicationBuilder after MVC

### ISSUE THREAD

**Issue by NikolaiSamteladze** [aspnet/Home#1209]
Developer Exception Page (`app.UseDeveloperExceptionPage()`) is blank if added to `IApplicationBuilder` after MVC (`app.UseMvc()`) in `Startup.cs` `Configure` method.

![image](https://cloud.githubusercontent.com/assets/1781634/12072373/8626658e-b0a9-11e5-8c24-dd44c2e8d90c.png)

Developer Exception Page works fine if added before MVC.

![image](https://cloud.githubusercontent.com/assets/1781634/12072406/d25a0f0e-b0aa-11e5-9d55-14f7d537f199.png)

Is this behavior intentional?

* Visual Studio Code 0.10.6 on Mac
* Microsoft.AspNet.Diagnostics 1.0.0-rc1-final
* Microsoft.AspNet.Mvc 6.0.0-rc1-final
* DNX Mono 1.0.0-rc1-update1

**Comment by davidfowl** [comment]
Yes, middleware is an ordered pipeline. If you put it after Mvc it won't be able to see errors that get thrown from MVC. Read more here https://docs.asp.net/en/latest/fundamentals/middleware.html

**Comment by NikolaiSamteladze** [comment]
@davidfowl Got it. Thanks. Closing the issue.
