### ISSUE TITLE
Enable Cross Domain in asp.net vNext api

### ISSUE THREAD

**Issue by anilsrv** [aspnet/Home#121]
How to enable Access-Control-Allow-Origin:"*" in vnext api.
in Webapi 2 we can do this by

 public void Configuration(IAppBuilder app)
        {
            // This must come first to intercept the /Token requests
            app.UseCors(CorsOptions.AllowAll);
         }

But not able to find any method in new vnext api

public void Configure(IBuilder app)
        {
        app.  ????

}

**Comment by danroth27** [comment]
Work on CORS support is now in progress: https://github.com/aspnet/cors
