### ISSUE TITLE
Allow Map* functions to continue executing.

### ISSUE THREAD

**Issue by atrauzzi** [aspnet/Home#1210]
I was looking at the sample project for the OpenIdConnect library and noticed he had created a `UseWhen` extension method.

After inquiring about why he made it instead of using `Map` and/or `MapWhen`:  https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Samples/issues/7

Would it be worthwhile to enable this subtle difference in functionality within ASP.NET?

**Comment by davidfowl** [comment]
Here's the bug for that one https://github.com/aspnet/HttpAbstractions/issues/351

**Comment by atrauzzi** [comment]
Subscribed!  Thanks :)
