### ISSUE TITLE
custom data files in aspnet

### ISSUE THREAD

**Issue by nguyenm100** [aspnet/Home#1211]
I have a somedata.dat file I need in my app and use File.OpenText("data/somedata.dat") file to access it.  On Windows the "data" directory is expected in the wwwroot/ directory but on linux it's expected to be in the approot/ directory.  I assume the former is correct but is this a bug on linux or do I need to access the file in a different manner?

using: rc1-final

**Comment by davidfowl** [comment]
This statement is confusing:

> On Windows the "data" directory is expected in the wwwroot/ directory but on linux it's expected to be in the approot/ directory.

What do you mean expected to be?

To help the situation, can you make a sample application and push it to github with instructions on what you did? That way we can both run the application without too many assumptions.

**Comment by nguyenm100** [comment]
I mean File.OpenText("data/somedata.dat") tries to look for it in wwwroot/data/somedata.dat when running under windows but approot/data/somedata.data when running the same code under linux.  

I'll work on a sample.

**Comment by nguyenm100** [comment]
To further clarify my less then stellar (initial) description.

1) I create an empty mvc app in visual studio on Windows
2) add the following lines to startup.cs -- Configure() method
            try
            {
                System.IO.File.OpenText("data/somedata.txt");
            }
            catch(Exception ex)
            {
                Console.WriteLine(ex.Message);
            }
3) Created a folder in wwwroot called data
4) Created a txt file in wwwroot/data called somedata.txt with some added text
5) Ran app IN visual studio w/o incident
6) Drop to DOS
7) Run dnu publish
8) go to myapp/src
9) Run dnu restore
10) go to src/myapp/bin/approot (where project.json is)
11) run dnx web
12) Receive exception that bin/output/approot/data/somedata.txt cannot be found

To me:

1) There's a mismatch btwn visual studio layout and "publish" layout (there is no "approot" in vs)
2) While I get that running dnx web from approot will set approot to be the "running" directory, aspnet must know enough to pull the js/css/image from wwwroot?

Invariably, 1) where is the correct place to store local files that will be accessed at runtime by my app and 2) what's the proper procedure to access them via pathing.

**Comment by davidfowl** [comment]
Use IApplicationEnvironment.ApplicationBasePath to find config files in the project root. The inconsistency between File.Open is basically relying on the working directory to be the same between the 2 OS's and it just isn't. When running under IIS and the platform handler the working DIR is wwwroot. So it's better to use physical paths rooted on ApplicatonBase rather than relative paths

**Comment by nguyenm100** [comment]
cool tx
