### ISSUE TITLE
SN issues with current System.Diagnostics.DiagnosticSource

### ISSUE THREAD

**Issue by jruckert** [aspnet/Home#1215]
As per #1207, this has occurred again.

![image](https://cloud.githubusercontent.com/assets/4064588/12131912/9a0abde6-b466-11e5-9753-ef347bc192af.png)

**Comment by jburger** [comment]
Workaround available: http://blogs.msdn.com/b/securitytools/archive/2009/12/30/how-to-turn-off-strong-name-validation.aspx

**Comment by jruckert** [comment]
Fixed.
