### ISSUE TITLE
DNU Restore fails if it can't reach custom package sources

### ISSUE THREAD

**Issue by DOTang** [aspnet/Home#1216]
I used the lightbulb feature to add Newtonsoft JsonConvert after typing JsonConvert. Upon trying to run my MVC app it said to run dnu restore to generate a new project.json.lock. I tried doing this and it would fail every time. This ended up being because one of the sources for my job's internal package feed was not accessible since I wasn't on VPN. So it couldn't reach a custom package source.

Is this intended? It seems strange because 1) The package feed source was listed under the default MS one, so presumably the first one would be run against, and 2) Nothing in this project was using anything from my job's internal package feed, so not even sure why it was being checked.

If anything I would expect it to run and restore what it could and notify me of any individual failures. Instead it just doesn't work at all. I was able to resolve this by removing the custom package feed from the package sources and then it worked no problem, but then I had to re-add it since I do need that for other projects.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
