### ISSUE TITLE
how to remove headers

### ISSUE THREAD

**Issue by Varorbc** [aspnet/Home#1217]
how to remove headers in mvc6 .for example X-Powered-By

**Comment by GuardRex** [comment]
@Varorbc There is a backlog item for allowing you to switch it off at https://github.com/aspnet/Hosting/issues/327#issuecomment-142499723. However, I'm on rc2, and that header isn't part of the responses. Check in IIS and see if (at the server level ... click on the server) if it's showing up under HTTP Response Headers. Kill it there, and see if you have any luck. :four_leaf_clover: 

![capture](https://cloud.githubusercontent.com/assets/1622880/12148031/ff12f5ac-b450-11e5-98d3-c88024384d20.PNG)

As a side note: If it's present and you want to remove the Server header, you can use middleware ...
```c#
app.Use((context, next) =>
{
    context.Response.Headers.Remove("Server");
    return next();
});
```

**Comment by Varorbc** [comment]
@GuardRex There is a problem, how to output to a log file by loggerFactory

**Comment by GuardRex** [comment]
@Varorbc Sure thing ... try the official doc ... https://docs.asp.net/en/latest/fundamentals/logging.html?highlight=logging
