### ISSUE TITLE
Project.json for .Net 4 Framework Apps

### ISSUE THREAD

**Issue by ndglover** [aspnet/Home#1218]
Hi,

I've been playing with dnx and project.json and successfully migrated a number of class libraries to use it. Albeit the process is a bit hacky.

To complete the story I'd like to use project.json for my WPF usercontrols and WPF applications. It doesn't look like these project types will work correctly with project.json. The visual studio designer doesn't work and the code behind generated by visual studio is not created so methods like InitializeComponent are not created/found.

It would be really advantageous to use project.json instead of packages.config for these project types. The ability to define the top level dependencies, avoid merge conflicts and swap out packages for source code would really help.

Is this possible or on any development roadmap right now? Can we get it added to the roadmap?

Thanks in advance.

**Comment by davidfowl** [comment]
There's no plan to move existing application models over to xproj (the VS support for `project.json` only based projects). 

> It would be really advantageous to use project.json instead of packages.config for these project types. The ability to define the top level dependencies, avoid merge conflicts and swap out packages for source code would really help.

There is a variant of `project.json` that *does* work with csproj/vbproj/fsproj that you can use. It's currently only *supported* in UWP projects but support will grow for some of the other project systems. Most notably the nuget dependencies will be external to the csproj. See https://docs.nuget.org/consume/projectjson-format.

**Comment by tomkuijsten** [comment]
Is there any progression on this matter? Are there additionally projects supported in say VS 2017 RC?

**Comment by tomkuijsten** [comment]
Already found the answer here:

https://github.com/NuGet/Home/issues/4007

Thanks @davidfowl
