### ISSUE TITLE
Resources (resx) files not working in ASP.NET 5 MVC 6 project

### ISSUE THREAD

**Issue by balivo** [aspnet/Home#1219]
Hi guys!

I have a Class Library (Portable) project in my solution with a Resources.resx file and a ASP.NET 5 MVC 6 (with DNX 4.5.1 framework).

I add a reference to portable project in ASP project, ok... So, when I execute ASP project a Internal Server Error (500) occurs...

System.IO.FileNotFoundException

My "resources" not found...

If I use in MVC 5 project... Everything work's fine.

Any ideas?

**Comment by Eilon** [comment]
Did you run the project from VS? That is currently broken and will be fixed in the next update.

If you run the app from the command line then it should work.

**Comment by balivo** [comment]
Yep @Eilon ... When I run the app in CLR or NOT-DNX projects... Everything Works fine!

**Comment by Eilon** [comment]
The main bug is here: https://github.com/aspnet/dnx/issues/3047

And we plan to have this fixed for the next release, which will be RC2.
