### ISSUE TITLE
Published app 'root' package in `ILibraryManager.GetReferencingLibraries()`

### ISSUE THREAD

**Issue by henkmollema** [aspnet/Home#1223]
When I publish an app and compile it to NuGet packages, it creates a folder **'root'**:
```
approot\packages\ConsoleApp2\1.0.0\root\
```

This causes the `ILibraryManager.GetReferencingLibraries()` to resolve a project called 'root' and it tries to load it. Which in turn fails with this exception: 
> Could not load file or assembly **'root'** or one of its dependencies. General Exception (Exception from HRESULT: 0x80131500)

DNX version: 1.0.0-rc1-update1

Repro:
https://github.com/henkmollema/AssemblyLoadRootRepro

1. Clone repo (`git clone https://github.com/henkmollema/AssemblyLoadRootRepro.git`)
2. `cd AssemblyLoadRootRepro`
3. `dnu publish -o c:\publish --no-source`
4. `cd c:\publish\approot`
5. `ConsoleApp2.cmd`
6. :boom:

Is this expected behavior?

**Comment by davidfowl** [comment]
The TypeFinder is implemented incorrectly. You're supposed to use info.Assemblies not the name of the library. Libraries represent packages, projects or assemblies, to get the loadable things you need to get the library's assemblies properties

**Comment by henkmollema** [comment]
That seems to work, thanks! :+1:

For reference, an implementation example:
```csharp
public IEnumerable<Assembly> GetLoadedAssemblies()
{
    return _libraryManager.GetReferencingLibraries("SomeCoreAssembly")
                            .SelectMany(info => info.Assemblies)
                            .Select(info => Assembly.Load(new AssemblyName(info.Name)));
}
```
