### ISSUE TITLE
Using Localization in a console application

### ISSUE THREAD

**Issue by alexbocharov** [aspnet/Home#1226]
How can we use localization in the console application?

**Comment by Eilon** [comment]
@DamianEdwards

**Comment by davidfowl** [comment]
@alexbocharov Can you be more specific

**Comment by alexbocharov** [comment]
@davidfowl It can be used for localization of console applications?  Is there a working example?

**Comment by davidfowl** [comment]
I still don't know what you mean. Our repository has localization middleware. Middleware is for ASP.NET specifically. What features are you looking for that would apply to the console application? What exactly are you trying to localize?

**Comment by alexbocharov** [comment]
I'm doing a console client to work with SignalR. I want to localize the message output

**Comment by DamianEdwards** [comment]
You can just normal .NET localization (e.g. `ResourceManager` and/or resx files with generated static classes). If you like the new `IStringLocalizer` abstraction, you could choose to use that, but it's really intended to work better when using ASP.NET's DI system.
