### ISSUE TITLE
Breakpoint not hit

### ISSUE THREAD

**Issue by dneimke** [aspnet/Home#1228]
Hi, over the past day I have had a recurring problem where I am unable to step into code.  This problem is captured in the following video: https://youtu.be/lX4u_SwwpCw

FWIW, a colleague has no issue stepping into that piece of code on his machine.

**Comment by dneimke** [comment]
Possible workaround... I fired up VS as an Administrator and can now step through

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
