### ISSUE TITLE
System.TypeLoadException: Kestrel.ServerInformation

### ISSUE THREAD

**Issue by lavire** [aspnet/Home#1229]
After hours of research finally managed to build my docker container. Running it results in the following exception though:
System.TypeLoadException: Could not load type 'Kestrel.ServerInformation' from assembly 'Krestel, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.

I am running CentOS 7, by the way. dnx is on 1.0.0-rc1-16231, Kestrel appears to be on 1.0.0-beta6 as it should be according to the project.json.

My Dockerfile and project.json (changed to project.txt for upload) are attached.
[Dockerfile.txt](https://github.com/aspnet/Home/files/86686/Dockerfile.txt)

[project.txt](https://github.com/aspnet/Home/files/86687/project.txt)

**Comment by davidfowl** [comment]
Most things look good here except for `    "Kestrel": "1.0.0-beta6",`, that dependency is hella old. The package has been renamed to Microsoft.AspNet.Server.Kestrel. I'd recommend generating a new template with the latest rc1 update and comparing.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
