### ISSUE TITLE
Razor Pages Repo / Roadmap Details

### ISSUE THREAD

**Issue by villanus** [aspnet/Home#1230]
I know web pages (web matrix/ razor / unsearchable name) is going to be released in late 2016, yet I cant find anything on the subject.

Yesterday I watched @damienedwards discuss his ideas for the stack, and nearly had a heart attack when he said Microsoft had considered MVC only.

MVC is great for larger teams but for small 1-5 dev projects its too heavy and slows you down.  The MVC learning curve is high for beginners or those transitioning from other scripting back end stacks. Almost all other web languagessupport coding without mvc which works for many devs.  During the talk somone said dont build a c# php clone, which web pages is not!  The ability to target .net core or full net and have c#, nuget, ef, all makes sense in a full page model and would make it a powerful option for new projects or migrations.  Having razor pages and mvc live side by side would be great too, same way a classic asp script or php can now all run in the same iis app.

Please start a repo for razor pages so developers like myself who love it, can participate.  Even if its just a placeholder repo for discussing features, it would be nice for Microsoft to get input from guys who use webpages, or the single page model (versus mvc guys who are married to mvc)

Thanks!

**Comment by villanus** [comment]
Here is a link to Damiens talk
http://youtu.be/8QcD2hF3m0I

**Comment by davidfowl** [comment]
> Please start a repo for razor pages so developers like myself who love it, can participate. even if its just discussing features, it would be nice for msft to get input from guys who use webpages, or the single page model.

When we start, we'll create the repository. We're extremely busy finishing the 1.0 release.

**Comment by villanus** [comment]
Thanks David.  
You guys are the best.

any more talk about razor pages in blogs, stand ups, or anywhere I can get it would be so appreciated.    Btw the way you and damian had the pseudo code marked up in the nov talk on razor pages was perfect!  all the power of mvc without seperation of concerns.   kind of like the good cozy days of classic asp with include files, except on steroids 

and I completely agree that razor pages should not only be for small sites, but perhaps full sites / apps but just with a different approach.  You guys nailed it by saying that.

**Comment by rhires** [comment]
Hello…

There’s this: https://github.com/aspnet/Razor - but I don’t know how this is similar/different to/from what you’re looking for. Maybe you can steer the direction of that project as it matures?

**Comment by villanus** [comment]
Hi @rhires,
That is not exactly what we are discussing.

Right now (before MVC 6 and Core CLR), there are 3 stacks to build asp.net apps on.
Stack 1 = Web Form (Does not Use Razor)
Stack 2 = MVC (Razor by Default)
Stack 3 = Asp.net Web Pages (Razor .cshmlt pages).

Most people dont even know about web pages. 
This is because of a few reasons which include:
- Calling it Web Pages is bad branding and impossible to search
- Only 3-4 Published books on the subject (Usually titled WebMatrix)
- Microsoft has put a lot of its power behind MVC because when MVC was launched Rails / Django (mvc frameworks) were all the rage. 

To learn more about what I am asking look at this link:
http://www.asp.net/web-pages



The problem is, MVC is a seperation of concerns which is too steep for beginners and small projects.   I would really suggest you view the video that Damian and David did.   From the video it seems like there is no clear roadmap (public) for the Web Pages stack, and they are looking for community feedback on how to proceed.    My Personal view is the presentation and ideas from the MSFT guys were a step in the right direction, but am hoping that Web Pages (what we call Razor Pages) will not be abandoned.

**Comment by rhires** [comment]
@villanus Thank you for alerting me to this. I had no idea this was available.

**Comment by villanus** [comment]
@rhires , No Problem. 
Most people do not know it exists.  Its just poorly named, and not really marketed as well as MVC. 
I guess you are not a serious programmer if you dont use MVC =)

**Comment by villanus** [comment]
Any movement on web pages?

**Comment by villanus** [comment]
Never any talk about web pages.  =(  
Its sad.   No wonder people still use PHP

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
