### ISSUE TITLE
Proposal: Task runner should have built-in access to VS 2015 build configuration name

### ISSUE THREAD

**Issue by SetTrend** [aspnet/Home#1231]
In some of the organizations I have been working for, TFS created a number of builds targetting different scenarios (e.g. CI/QA).

Moreover, when I'm building on my personal development machine (BYOD) I'm choosing different targets, too (e.g. Development, Release).

Can we have task runners be able to read the VS 2015 build configuration name so we can take decisions in our task runner scripts on whether we want to uglify/bundle etc.?

I'd like to suggest to create a Visual Studio Node C++ addon reading the current solution file which we then can require:

``` javascript
let Solution = require("vssolution");

let solution = new Solution("MyVsSolution.sln");  // deserializes the current solution file
let isDebug = /DEBUG/i.test(solution.buildConfig.name)
```

/cc #724

**Comment by jonantoine** [comment]
Here is my hacking workaround for this until someone comes up with a better one.
I create a json file in which glup can read in:

1. Add a pre-build event in the project with the gulpfile.js
![2016-02-09_7-48-42](https://cloud.githubusercontent.com/assets/2699833/12927692/18a1374c-cf2f-11e5-9ec4-5904e577a147.png)
This creates a config.json file with the configuration name at the same level of my gulpfile.js.

2. I read in the json file into the gulpfile.js
```javascript
var gulp = require("gulp"),
    fs = require('fs');

var json = fs.readFileSync("./config.json", "utf8");
var host = JSON.parse(json.replace(/^\uFEFF/, ''));
host.isDebug = host.config != "Debug";
...
```
Initial results seem to be working pretty well.
Hope this helps someone else.

**Comment by SetTrend** [comment]
Very good comment! Excellent approach.

I'll use that for now. Yet, I still believe this should become built-in.

**Comment by samirageb** [comment]
@jonantoine Much thanks for this. Although I found 1 line to be counter intuitive. I believe this line:

```javascript
host.isDebug = host.config != "Debug";
```
should be: 
```javascript
host.isDebug = host.config == "Debug";
```
In order to get **host.isDebug** returning _true_ when host.config is set to 'Debug'. Please let me know if I'm missing something.

**Comment by ljani** [comment]
Here's what I'm doing:
`project.json`:

```
{
  "scripts": {
    "prebuild": [ "npm run gulp -- default --configuration=%build:Configuration%" ],
    "postrestore": [ "npm install" ],
    "prepare": [ "npm run gulp -- clean --configuration=%build:Configuration%" ],
    "prepublish": [ "npm run gulp -- default --configuration=%build:Configuration%" ]
  }
}
```

`gulpfile.babel.js`:

```
import minimist from "minimist";

const argv = minimist(process.argv.slice(2));
const production = "release" === (argv.configuration || "debug").toLowerCase();
```

But I agree that there should be an environment variable, which would do all this for me.

**Comment by roydukkey** [comment]
@ljani How is this possible since RTM?

**Comment by ljani** [comment]
@roydukkey The principle of delivering the configuration name is still the same, although the script keys have changed with rc2/preview1 and thus with rtm/preview2 too (eg. `prebuild` -> `precompile` etc)

**Comment by roydukkey** [comment]
@ljani Yes, but did `%build:Configuration%` change to something else? It's not being replaced by rtm/preview2.

**Comment by ljani** [comment]
@roydukkey Sorry, I should've been more explicit, the name `build` has been replaced with `compile` everywhere, including `%build:Configuration%`. Ie this is working fine for me:

```
{
  "scripts": {
    "precompile": [ "npm run gulp -- default --configuration=%compile:Configuration%" ],
  }
}
```

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
