### ISSUE TITLE
aspnet 5 (MVC6) Windows Auth + roles + Authorize attribute

### ISSUE THREAD

**Issue by tparnell8** [aspnet/Home#1232]
I have an app that uses Windows Auth on aspnet 5 MVC 6 (obv using IIS + IISPlatformHandler)

How can I restrict access to controller actions by AD group?

I have tried doing something like the following, but it won't work :( When I look at my user claims I see many groups and claims that look like SID's ex. {S-1-5-4}

```csharp

[Authorize(Roles = "DOMAIN\\GROUP")
public class myController : Controller{...}

```

**Comment by brockallen** [comment]
Use claims transformation to change those SIDs into group names.

**Comment by blowdart** [comment]
There's no way to access directory services in core yet. This would be a bug for the platform handler to provide the information in a better way. I'll talk to them about it.

**Comment by blowdart** [comment]
We found where the bug lies. Hopefully will be fixed for RC2. 

I'm going to close this issue. You can follow the bug at https://github.com/aspnet/Common/issues/85
