### ISSUE TITLE
Entity Framework 6 - System.IO.FileNotFoundException in DatabaseFirst approach

### ISSUE THREAD

**Issue by datoml** [aspnet/Home#1233]
### Update: Solution for this at the end

I have two projects in my solution.
The first is an asp.net 5 WebApi Project, the second one is a .net 4.5.2 Class Library.

The second project is referenced with the output dll in the webapi project.
![pic01](https://cloud.githubusercontent.com/assets/10552487/12328851/a1ce8986-badd-11e5-9249-9d70997153a4.png)

When I start the webapi and the db call is about to happen, I get this error:
"Die Datei "EntityFramework.resources" konnte nicht gefunden werden."
Translated:
"The file "EntityFramework.resources" couldn't be found."
![pic02](https://cloud.githubusercontent.com/assets/10552487/12328884/cd487cf2-badd-11e5-8e3b-6e610ba10a6c.png)

Is this a known bug?
Thank you in advance.

### Update:
I found a solution on stackoverflow.
http://stackoverflow.com/questions/34532188/why-cant-i-use-class-library-with-ef-6-1-3-from-asp-net-5-mvc-6-project

Don't forget to add the System.Data.SqlClient to you asp.net 5 references.

**Comment by Eilon** [comment]
@divega

**Comment by divega** [comment]
As stated in the StackOverflow thread this is due to bug https://github.com/aspnet/dnx/issues/3047. @anurse @davidfowl any idea if accessing resources in non-English cultures will work correctly with .NET CLI?

**Comment by anurse** [comment]
They will, but do not currently.

**Comment by Eilon** [comment]
Closing as a dup of https://github.com/aspnet/dnx/issues/3047.
