### ISSUE TITLE
ASP.NET 5 RC2, Azure: "The specified CGI application encountered an error and the server terminated the process."

### ISSUE THREAD

**Issue by joshcomley** [aspnet/Home#1235]
When I publish to Azure using the latest RC2 I receive the following error message to the browser after an extremely long load time:

    The specified CGI application encountered an error and the server terminated the process.

I have ensured I am publishing with the exact correct clr version.

The app sometimes runs after the initial error message, but extremely slowly.

Does anybody have any suggestions?

**Comment by hiraldesai** [comment]
Did you get any resolution to this? I'm having the same issue with latest RC2.
