### ISSUE TITLE
Issue with dnvm use with parameter "-g" in 1.0.0-rc2-15546

### ISSUE THREAD

**Issue by aredfox** [aspnet/Home#1238]
I currently have dnvm version 1.0.0-rc2-15546. The parameter "-g|-global" has been dropped when using the command "use" with dnvm in that version. Can this either be changed in the documenation at [ https://github.com/aspnet/Home/wiki/Version-Manager ], or can this be included again in the next release? Is there a reason why it has been dropped, as I found this very useful to rapidly configure certain dev machines.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
