### ISSUE TITLE
[Question] How to get project version when using "1.0.0-*"

### ISSUE THREAD

**Issue by Kukkimonsuta** [aspnet/Home#1239]
When version with `*` is used, `IApplicationEnvironment.ApplicationVersion` returns only the part without `*` even after `dnu publish` with `DNX_BUILD_VERSION`. Is there a way to get version including the string in `DNX_BUILD_VERSION` at runtime?

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
