### ISSUE TITLE
Microsoft.WITDataStore32.dll not found

### ISSUE THREAD

**Issue by Ghkuijer** [aspnet/Home#1240]
I am having a problem where a native library is not found from the Microsoft.TeamFoundationServer.ExtendedClient. The library is originally located in the "/lib/native/x86" folder. As this is not the current convention I copied the dll to the "/runtimes/{runtime}/native" folder. I added a dll for every runtime thinkable. 
This solution however did not work.

The only way in which I could get this to work is to copy the dll to the "lib/net45" folder, which I think is a little bit hacky.

I am using only dnx451. 
Is this a common problem, am I doing something totally wrong or is this a bug that should be solved somewhere?

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
