### ISSUE TITLE
[Question] - ASP.NET 5 - Modular application - How to load an assembly

### ISSUE THREAD

**Issue by dazinator** [aspnet/Home#1241]
In my experimental solution, I have:

1. ASP.NET 5 Web application project (Dnx 4.5.1 and DnxCore50).
2. Class Library project (Dnx 4.5.1 and DnxCore50).

I want my ASP.NET 5 web application to dynamically "discover" this class library assembly at runtime, on startup. 

There is no project reference in place between them.

I want this to work when:

1. I run the solution within Visual Studio
2. The application is actually deployed and running under Dnx.

My initial attempt was to put in some code on startup to scan a folder for the assembly, but when running in VS - there is no assembly output for my class library due to Roslyn in memory compilation.

I then thought i'd tick the  "Produce outputs on build" checkbox for my class library project. But this outputs a NuGet package to an artifacts folder. It also seems to output the assemblies to that artifacts location, so I am thinking this might be the route to go - as in I scan that folder for the assembly when my application is running on a Development environment, and when the application is deployed to production I could configure this path differently (as there will be no artifacts directory  on production)

However this made me think, perhaps I am missing some more clever mechanisms for resolving packages at runtime that I should be leveraging.. and with that in mind..

1. Should I be attempting to use the `IAssemblyLoader`'s to load my assembly from packages at runtime - perhaps with a  `PackageAssemblyLoader` or `ProjectAssemblyLoader` ? Dnx seems to set up these but they only contain the packages and projects strongly referenced by the application - is there any way for me to add another package (from a directory) or another project at runtime?
2. Should I be attempting to dynamically "add" a package to the `ILibraryManager` ? Or implementing my own?

All in all, I would prefer to drop a NuGet package somewhere containing my Class Library, and then my application would be load the assembly from that at runtime if possible, but I don't want to re-invent the wheel.

**Comment by dazinator** [comment]
I decided not to delve too much into the framework in the end, and just rolled my own solution to the problem.

I use the `NuGet.Core` library to install the NuGet package containing my assembly to a folder within the application. I then copy those assemblies into a shadow directory before loading them into the app domain through MEF into a catalog. Non of this attempts to use `IAssemblyLoader` or `ILibraryManager`or anything like that.

**Comment by leo9223** [comment]
Ill recommend you to see this framework 

github.com/extcore
