### ISSUE TITLE
[Question/Request] LDAP support for On-Premise AD in .Net 5 Core support?

### ISSUE THREAD

**Issue by Eaglef90** [aspnet/Home#1242]
I have looked around the web and asked both on asp.net and stackoverflow with no success. As far as I can tell, right now, there is no support for ability to query an on-premise Active Directory server using LDAP to get information about users/authenticate users. What are the plans to support LDAP in .Net Core 5? If this is better of asked somewhere else please let me know where and I can ask there. I was pointed here from SO, also I have found a few things that thought on Azure AD but I am not using Azure.

**Comment by smbecker** [comment]
Probably more appropriate in dotnet/corefx#2089

**Comment by soeron** [comment]
Take a look here:
https://github.com/jesblit/ASPNET5-FormAuthenticationLDAP
With some changes managed to authenticate against AD. This will work on the full .NET profile only! But could fill the gap while a complete solution is provided.

**Comment by Eaglef90** [comment]
Thanks but I am not just looking for authentication but also querying.

**Comment by davidfowl** [comment]
Then the issue mentioned by @smbecker is the thing to comment on and follow. This isn't an ASP.NET specific issue.
