### ISSUE TITLE
VS Error. Cannot access a disposed object. Object name: 'Microsoft.VisualStudio.ProjectSystem.UnconfiguredProjectImpl'

### ISSUE THREAD

**Issue by dazinator** [aspnet/Home#1244]
I left a visual studio solution containing an ASP.NET 5 project and class library project open when I left the office yesterday. I came in to today, and clicked the "play" button to start the website running, and got this error:

![image](https://cloud.githubusercontent.com/assets/3176632/12448812/83d30e24-bf70-11e5-9a1a-e77d41c65ea6.png)

**Comment by Gert-Cominotto** [comment]
Having the same problem when using a asp.net dnxcore50 web project referencing a dnxcore50 class library. And also having this issue when using an asp.net dnxcore50 console project referencing the same dnxcore50 class library.

**Comment by Eilon** [comment]
Can you log this tooling issue in https://github.com/aspnet/Tooling/issues/? Thanks!

**Comment by dazinator** [comment]
@Eilon - have logged under tooling as requested aspnet/Tooling#427

**Comment by rclabo** [comment]
I just received the same error when when trying to create a new web project.  As soon as the dialog for picking what type of project came up the error dialog came up on top of that.  I'm running VS2015 Update 2 on Windows 7.  

![screen](https://cloud.githubusercontent.com/assets/6945499/14333580/6cb57d6e-fc1d-11e5-900f-dc73ee0ab6ee.png)

**Comment by Eilon** [comment]
@rclabo this issue is closed - if you'd like to add a comment, please add to https://github.com/aspnet/Tooling/issues/427. Thanks!
