### ISSUE TITLE
Consider an RC3 schedule extension

### ISSUE THREAD

**Issue by ColinDabritz** [aspnet/Home#1246]
Thank you for the wonderful open source project, and especially the opportunity to watch it happen, and even participate. I really appreciate the changing attitudes and commitments Microsoft continues to deliver on a broad front.

I would like to ask that the appropriate parties who make schedule and release decisions for ASP.NET Core consider a change in schedule to allow time for a full RC3, which I understand is not currently the plan. I'm sure this is already being discussed internally, but I would like to provide an outside perspective.

I would also mention that the ASP.NET team on the live standup respectfully discussed this issue based on submitted questions, and did not ask for community involvement explicitly. I appreciate the opportunity to provide feedback on this project.

I believe this project would benefit from an additional RC for a variety of reasons:
* This project covers three platforms for the first time, which adds significant challenges. It is an “ambassador” for Microsoft and .NET on these platforms. Complexity takes time, and getting it right up front has higher than usual value.
* This project is reliant upon and is coordinating with several other cross platform projects now under the “core” banner. These projects are also new, and coordination adds complexity.
* The rename is deep, and is being carried across packages. Other projects are renaming as well.
* Infrastructure has shifted significantly since RC1, DNX -> dotnet CLI and similar.
* This is (now more clearly) a new 1.0 product, which will ship APIs, interfaces, names, and other forms of contracts that will need to be respected carefully moving forward. Issues with these are inevitable, you never get everything right, but because errors here will potentially be felt for years or even decades, it is worth an extra RC for these to settle as much as possible, especially considering the platform and renaming impacts.

Some cons:
* There may be events on the schedule that want to show off ASP.NET Core 1.0
* This is your vocal early adopter community, which may not represent many mainstream developers
* People like new things, regular releases are healthy
* The project will benefit greatly from feedback that only a full release will bring, especially on Mac and Linux

I believe several factors make delaying a release more appropriate than usual
* This is no longer “ASP.NET 5” e.g. “What’s taking you so long with the next version?” it’s been renamed as “ASP.NET Core” a new 1.0 product. This more clearly reflects how it has always been.
* This project is open source, and people can get the bits any time they like. The RCs have “go live” licensing available with support from Microsoft. People are not being completely forced to wait for a release.
* This project is open source, and has been excellent about communicating status and involving the community. This means outside observers understand the status of the project better, and can more clearly see why another RC might be beneficial. They can also understand that the bits for RC3 would be similar to bits in an RTM, and can choose to use those bits now if they like.

In my opinion as a developer, the balance of these factors make an RC3 schedule change worth while.

I also do not currently have any explicit stake on ASP.NET Core RTM, which could significantly change my perspective. I'm a fan of the project, and I'll pitch it at work for web use down the road, but I don't have any projects relying on it right now. I would like to hear from anyone who is explicitly waiting for RTM for a current project!

I understand that there are many complicated factors in deciding release timelines, not all of which are public, and only ask that this feedback be considered. You’ve earned my trust and respect for any decision made, including sticking to the current schedule.

I would love to hear others reasons and thoughts for or against adding an RC3.

**Comment by DamianEdwards** [comment]
Thank you very much for such a considered post. I can't argue with any of your logic (as it's, you know, logical) but for now the team is focused solely on delivering a quality RC2 release. Once that's under our belt we'll circle back to the question of the releases that follow.
