### ISSUE TITLE
MVC6 application wont run on IIS10

### ISSUE THREAD

**Issue by wgrs** [aspnet/Home#1247]
I am trying to host a MVC6 application on IIS10. I have followed all the documentation I can find but no luck so far. **I am getting a 500 error. (500 0 0 from IIS logs)**

I have installed the PlatformHandler v1.2. x64
I have unlocked the handler in IIS and set the web.config to produce the stdoutLogFile and created the path to the directory. No dnx logs are produced. 
I have checked the IIS logs - no information of any use is produced.
I disabled an re-enabled IIS to set it back to default.
I checked the Windows Process Activation Service is running.
I have hard coded the environment variables for the DNX settings (as per another article) for the actual website in IIS. 
I have made sure the applicationpool user has read rights on the .dnx folder.
I made sure that the IIS_IUSR account has permissions on the project folder. 
I have tried all the other possible accounts ( as well as my admin user account) on the application pools. 

This is the IIS log : #Date: 2016-01-20 20:32:59
# Fields: date time s-ip cs-method cs-uri-stem cs-uri-query s-port cs-username c-ip cs(User-Agent) cs(Referer) sc-status sc-substatus sc-win32-status time-taken

2016-01-20 20:32:59 ::1 GET /MyApartment - 80 - ::1 Mozilla/5.0+(Windows+NT+10.0;+WOW64)+AppleWebKit/537.36+(KHTML,+like+Gecko)+Chrome/47.0.2526.111+Safari/537.36 - 500 0 0 17579

This is the dnx list:
Active Version           Runtime Architecture Location                    Alias

---

```
     1.0.0-rc1-final   clr     x86          C:\Users\Greg\.dnx\runtimes
  *  1.0.0-rc1-update1 clr     x64          C:\Users\Greg\.dnx\runtimes default
     1.0.0-rc1-update1 clr     x86          C:\Users\Greg\.dnx\runtimes
     1.0.0-rc1-update1 coreclr x64          C:\Users\Greg\.dnx\runtimes
     1.0.0-rc1-update1 coreclr x86          C:\Users\Greg\.dnx\runtimes
```

Another error that is coming up is - **An error occurred attempting to determine the process id of the DNX process hosting your application**

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
