### ISSUE TITLE
List of dnvm versions 

### ISSUE THREAD

**Issue by russcam** [aspnet/Home#1248]
Is there a definitive list of DNVM versions along with release dates for each somewhere?

**Comment by BrennanConroy** [comment]
We have this page: https://github.com/aspnet/Home/releases

**Comment by russcam** [comment]
Thanks - that's got some of what I was hoping to find but I wondered if there was a table like the following

| Version | Runtime | Release Date |
|-----------| ------------|------------------|
| 1.0.0-rc-update1 | clr | 2016-01-01 (made up) |
| 1.0.0-rc-final | clr | 2015-12-14 (made up) |

etc.

The observation that prompted the question was that I did `dnvm upgrade` on a new machine and it installed `1.0.0-rc-update1` as the latest, but I thought that was earlier than `1.0.0-rc-final` (I'm reading into the naming here :smile: )

**Comment by BrennanConroy** [comment]
update1 was after final

**Comment by russcam** [comment]
thank you for the clarification, maybe a list/table would be helpful to the wider audience?

**Comment by BrennanConroy** [comment]
Well since we are getting rid of `dnvm` in favor of the `dotnet cli` I don't think we will be doing that :)

**Comment by russcam** [comment]
I appreciate it's usefulness right now would be limited to the next 2-6 weeks, just thought it might be useful for current and historical context.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
