### ISSUE TITLE
[Question] - Route to a controller in an external assembly loaded on startup.

### ISSUE THREAD

**Issue by dazinator** [aspnet/Home#1249]
There is a folder inside my application, where I can "drop" assemblies. (This actually comes about by installing a NuGet package via using NuGet.Core)

Inside said assembly is an MVC 6 Controller, and Razor Views.

On application startup, i'm using MEF to load this assembly into the app domain.

How do I go about informing MVC of this controller, and adding a route for it, on startup?

**Comment by dazinator** [comment]
I just stumbled upon this blog post which explains how to go about this. http://www.strathweb.com/2015/04/asp-net-mvc-6-discovers-controllers/
I'll give that a go.

**Comment by marcobarbero** [comment]
In the Startup.cs of the ClientProject:

public IServiceProvider ConfigureServices(IServiceCollection services) 
{
    // Add external reference to MVC controller
    services.AddMvc().AddApplicationPart(
        typeof(MyController).GetTypeInfo().Assembly)
        .AddControllersAsServices();
}
This post from:
https://expertcodeblog.wordpress.com/2018/01/10/asp-net-core-2-0-mvc-how-to-use-a-controller-of-an-external-assembly/
