### ISSUE TITLE
System.EntryPointNotFoundException with UseStaticFiles and UseMvcWithDefaultRoute

### ISSUE THREAD

**Issue by DannyvanderKraan** [aspnet/Home#1250]
This is about release candidate 1. I started with an empty ASP.NET 5 solution.

1) Startup.cs looks like:

```
  public void ConfigureServices(IServiceCollection services)
    {
        services.AddMvc();
    }

    public void Configure(IApplicationBuilder app)
    {
        app.UseIISPlatformHandler();

        app.UseMvcWithDefaultRoute();

        app.UseStaticFiles(new StaticFileOptions()
        {
            OnPrepareResponse = (context) =>
            {
                var headers = context.Context.Response.GetTypedHeaders();
                headers.CacheControl = new CacheControlHeaderValue()
                {
                    MaxAge = TimeSpan.FromDays(1)
                };
            }
        });           

    }

    public static void Main(string[] args) => WebApplication.Run<Startup>(args);
```
- Only added MVC 6 and StaticFiles basically.

2) HomeController.cs looks like:

```
    public IActionResult Index()
    {
        return View();
    }
```
- Kept it default as you can see. 

3) Added the necessary Views folder, added Home folder in Views, added Index.cshtml which contains nothing but <h1>Hello!</h1>

4) When I run this it crashes with error:

 Exception thrown: 'System.EntryPointNotFoundException' in System.Reflection.Metadata.dll

Additional information: Unable to find an entry point named 'ReadFile' in DLL 'api-ms-win-core-file-l1-2-0.dll'.

5) Removed everything related to UseStaticFiles including the dependency in project.json.

6) Run it and the app still crashes with the same error.

7) Removed everything that had to do with MVC 6,  put everything back for UseStaticFiles and added the following code to Configure in Startup.cs beneath UseStaticFiles...:

 app.Run(async (context) =>
            {
                await context.Response.WriteAsync("Hello World!");
            });

8) Run it and I see Hello World! in browser.

9) Got everything back that had to do with MVC 6 and removed everything that had to do with UseStaticFiles. Cleaned solution. Restored packages. Restarted Visual Studio. And so on. Can't get MVC to work again.

Can anyone else reproduce this problem and perhaps (even beter) provide a solution? If more information is needed please let me know.

**Comment by davidfowl** [comment]
@DannyvanderKraan Put a repro project on github and I can take a look.

**Comment by DannyvanderKraan** [comment]
@davidfowl I've uploaded a repro project. Thank you in advance for taking a look.

[StaticFilesPlusMvc6Problem.zip](https://github.com/aspnet/Home/files/102890/StaticFilesPlusMvc6Problem.zip)

**Comment by davidfowl** [comment]
@DannyvanderKraan can you make that a github repo?

**Comment by GuardRex** [comment]
@DannyvanderKraan Did you try moving the 
```
app.UseMvcWithDefaultRoute();
```
... below the `app.UseStaticFiles(...)`?

**Comment by DannyvanderKraan** [comment]
Sure: https://github.com/DannyvanderKraan/StaticFilesAndMvc6Problem.git

**Comment by DannyvanderKraan** [comment]
Hey Luke,

Thanks for your reply. Yes I did. No luck unfortunatly.

**Comment by Jeffiy** [comment]
I can run it, but I use `1.0.0-rc1-update1`

**Comment by DannyvanderKraan** [comment]
I thought I did too. My global.json file says  "version": "1.0.0-rc1-update1"

But that is strange. So it must be something on my machine then?

**Comment by antmdvs** [comment]
I'm experiencing this issue as well, running on Windows 7 SP1. @DannyvanderKraan, were you able to resolve this?

Module Version: 4.06.24027.0
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\1.0.0-rc2-3002702\System.Reflection.Metadata.dll

**Comment by davidfowl** [comment]
If it still repros you can re-open a new issue
