### ISSUE TITLE
Availability of types when building for dotnet5.4

### ISSUE THREAD

**Issue by bryanjhogan** [aspnet/Home#1251]
I have a simple class like - 

    using System;
    using System.ComponentModel;
    using System.Reflection;
    
    namespace Common
    {
        public static class ExtensionMethods
        {
            public static string Description(this Enum value)
            {
                FieldInfo fi = value.GetType().GetField(value.ToString());
    
                DescriptionAttribute[] attributes =
                    (DescriptionAttribute[])fi.GetCustomAttributes(
                    typeof(DescriptionAttribute),
                    false);
    
                if (attributes.Length > 0)
                {
                    return attributes[0].Description;
                }
    
                return value.ToString();
            }
        }
    }

But I'm getting this compile error - 

> Severity	Code	Description	Project	File	Line	Suppression State
> Error	CS0246	The type or namespace name 'DescriptionAttribute' could
> not be found (are you missing a using directive or an assembly
> reference?)	Fund.FundEntitlement.Common..NET Platform
> 5.4	C:\dev\Repos\Finomial.InternalServices\Fund.FundEntitlement\Fund.FundEntitlement.Common\ExtensionMethods.cs	13	Active

My project.json is 

    {
      "version": "1.0.0-*",
      "description": "Common Class Library",
      "authors": [ "bryan" ],
      "tags": [ "" ],
      "projectUrl": "",
      "licenseUrl": "",
    
      "frameworks": {
        "net451": { },
        "dotnet5.4": {
          "dependencies": {
            "Microsoft.CSharp": "4.0.1-beta-23516",
            "System.Collections": "4.0.11-beta-23516",
            "System.Linq": "4.0.1-beta-23516",
            "System.Runtime": "4.0.21-beta-23516",
            "System.Threading": "4.0.11-beta-23516"
          }
        }
      }
    }

What am I doing wrong?

**Comment by davidfowl** [comment]
What is `DescriptionAttribute`? I'm not sure where the entire list of API for a specific dotnet/netstandard version is.

/cc @terrajobst @ericstj

**Comment by bryanjhogan** [comment]
`DescriptionAttribute` is part of `System.ComponentModel`.

Please let me know if the question I'm asking is not being clear. I have used `DescriptionAttribute`  with some MVC 4 and 5 applications and want to make use of it again.

**Comment by davidfowl** [comment]
I'm pretty sure it's not part of .NET Core.

**Comment by bryanjhogan** [comment]
But what if I'm targeting "dotnet5.4"?

**Comment by davidfowl** [comment]
Then you still don't get it. AFAIK that attribute no longer exists.

**Comment by bryanjhogan** [comment]
What we're struggling with is knowing if something is available.

I had another similar problem which I wrote to you about on twitter (https://stackoverflow.com/questions/34823723/the-type-ienumerable-is-defined-in-an-assembly-that-is-not-referenced-syste) and with some guess work changes to the project.json I got it working. 

But this is very time consuming for us and we're trying to get the first part of an enterprise application built. 
How can I tell if something is available for asp.net 5?

**Comment by davidfowl** [comment]
> How can I tell if something is available for asp.net 5?

That statement in itself doesn't mean much. I know what you're asking and we don't have an uber list of the APIs available in .NET Core by version that I'm aware of. It's one of the reasons we made http://packagesearch.azurewebsites.net. You should be able to use that to find whatever class you need, if you don't see a match then it's not available in any package. If you need an alternative then try asking here or on **dotnet/corefx**. If you don't care about running on .NET Core then remove the target framework from your `project.json` and continue using .NET Framework.

**Comment by bryanjhogan** [comment]
Thanks David

**Comment by dougbu** [comment]
@bryanjhogan if you do want to use .NET Core, switch from `[Description("...")]` to `[Display(Description="...")]`. The `System.ComponentModel.DataAnnotations` attributes are available.

**Comment by bryanjhogan** [comment]
Thanks Doug.
