### ISSUE TITLE
Official recomendation on legacy Soap services

### ISSUE THREAD

**Issue by Centurys** [aspnet/Home#1256]
Hello,

I was wondering is there any official recommended scenarios for hosting legacy soap services?
By that I mean - there are many business side services which are  build on top of WCF hosted soap web services and many businesses are needed to support them for a backward compatibility. So if we developers for those systems if we want to upgrade our systems to new AspnetCore framework and new project system what our choices, what is official story/answer/suggestion from Microsoft or Aspnet team?
Does that mean soap services is thing of a past? Or for soap use Aspnet 4.6 and forget AspnetCore? Or is there some kind of recommended hybrid scenario?

Related issue about technical part of the question was answered here https://github.com/aspnet/Hosting/issues/558

Thanks

**Comment by davidfowl** [comment]
>  Or for soap use Aspnet 4.6 and forget AspnetCore?

The recommendation would be to keep those services hosted in a .NET Framework 4.x ASP.NET/WCF site. 

> Or is there some kind of recommended hybrid scenario?

A hybrid would mean that you broke your app architecture into different sites then you can use ASP.NET for soap and ASP.NET Core for everything else.  You can't do it in the same process/project/app.

**Comment by Centurys** [comment]
Thanks for the answer.
