### ISSUE TITLE
Where is code for Microsoft.IdentityModel.Protocols.OpenIdConnect?

### ISSUE THREAD

**Issue by treynash** [aspnet/Home#1258]
Does anyone know where the code implementing types in [Microsoft.IdentityModel.Protocols.OpenIdConnect](https://www.nuget.org/packages/Microsoft.IdentityModel.Protocols.OpenIdConnect/) might live on github?  I'm having the hardest time finding it for some reason and am starting to think it is not available.

Thanks!

**Comment by blowdart** [comment]
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet
