### ISSUE TITLE
Question: How to I get the Assembly from a Type when targeting .net-core 'dotnet5.4'?

### ISSUE THREAD

**Issue by dburriss** [aspnet/Home#1259]
I asked the question on SO but apparently its a bad question although I am not sure why.
http://stackoverflow.com/questions/35001621/how-to-i-get-the-assembly-from-a-type-when-targeting-net-core-dotnet5-4

I have a method like this in a class library which works fine but when wanting to swap DNXCORE50 to DOTNET5_4 I can't find the correct API for finding the assembly by containing Type.  
The `.Assembly` and `.GetTypeInfo().Assembly` are not available and looking through the aspnet source code has not yielded any answers so far.

    private static System.Reflection.Assembly[] GetAssemblies()
    {
        #if DNX46
        return new Assembly[] { typeof(SomeClass).Assembly };
        #endif
        #if DNXCORE50
         return new System.Reflection.Assembly[] { typeof(SomeClass).GetTypeInfo().Assembly };
        #endif
    }

How to I get the Assembly from a Type using dotnet5.4 api surface?

    #if DOTNET5_4
    // what goes here to duplicate the functionality above?
    #endif

https://github.com/aspnet/Announcements/issues/98  
The project is obviously targeting RC 1 for now.

**Comment by pranavkm** [comment]
```C#
using System.Reflection;
....
`typeof(SomeClass).GetTypeInfo().Assembly`. Most of the `Type` API surface`has moved to `TypeInfo`.

**Comment by dburriss** [comment]
Hmmm. Seems it was a VS glitch. I was just about to say that is what I had but a restart of VS and the build error went away. Thanks.
