### ISSUE TITLE
ASP.net 5 404 error when hosting as an application inside website

### ISSUE THREAD

**Issue by raymak23** [aspnet/Home#1260]
Hello,

There appears to be an issue hosting asp.net 5 mvc 6 application when hosting an application as an application inside website. 

Below is screenshot contains my hosting environment. I have a `ps` application inside `Admin` website. When I browse `http://localhost:8084/ps`, I get 404 page in the browser.

![image](https://cloud.githubusercontent.com/assets/10405119/12588540/1550e3ca-c427-11e5-8e6a-96a8bbb16942.png)

Then I setup a new website called `ps` with port 8085 and configured it to point to application wwwroot path, and when I browse the URL `http://localhost:8085/` I am able to see the landing page of the application.

**Comment by Tratcher** [comment]
See https://github.com/aspnet/IISIntegration/issues/14

**Comment by javiercn** [comment]
@Tratcher Can this be related to https://github.com/aspnet/Mvc/issues/3769?

**Comment by Tratcher** [comment]
@javiercn not for a normal browser request to the home page. It's probably aspnet/IISIntegration#14.

**Comment by raymak23** [comment]
Thanks guys, I will give it a try.

**Comment by raymak23** [comment]
So I followed along with comments and I found something that I thought would work. I added environment variable in web.config that is in `wwwroot` folder. Please see below config settings:

```
<httpPlatform processPath="..\approot\web.cmd" arguments="" stdoutLogEnabled="true" stdoutLogFile="..\logs\stdout.log" startupTimeLimit="3600">
		<environmentVariables>
			<environmentVariable name="HTTP_PLATFORM_APPL_PATH" value="ps" />
		</environmentVariables>
</httpPlatform>
```

Then I recycled the app pool and performed IISREST, and when I browse the application `localhost:8084/ps` I still get 404 error.

In stdout.log file I see below log created:

```
Hosting environment: Production
Now listening on: http://localhost:19684
Application started. Press Ctrl+C to shut down.
```

I also checked httpPlatform

![image](https://cloud.githubusercontent.com/assets/10405119/12626519/09b1290e-c507-11e5-800c-443e2f12aab0.png)

**Comment by Tratcher** [comment]
Are you using the current RC2 packages described here? https://github.com/aspnet/IISIntegration/issues/52#issuecomment-171444840

**Comment by raymak23** [comment]
Nope, I am using RC1. Please see below dependencies from project.json file.

```
"dependencies": {
    "Microsoft.AspNet.Mvc": "6.0.0-rc1-final",
    "Microsoft.AspNet.Mvc.Core": "6.0.0-rc1-final",
    "Microsoft.AspNet.Server.Kestrel": "1.0.0-rc1-final",
    "Microsoft.AspNet.StaticFiles": "1.0.0-rc1-final",
    "Microsoft.Extensions.Logging.Debug": "1.0.0-rc1-final",
    "Microsoft.AspNet.Mvc.TagHelpers": "6.0.0-rc1-final",
    "Microsoft.Net.Http.Server": "1.0.0-beta5",
    "dnx-clr-win-x64": "1.0.0-rc1-update1",
    "Microsoft.AspNet.IISPlatformHandler": "1.0.0-rc1-final"
  }
```

**Comment by Tratcher** [comment]
The web.config workaround only applies to the latest RC2 packages. For RC1 you need to use the Map workaround: https://github.com/aspnet/IISIntegration/issues/14#issuecomment-150716529

**Comment by raymak23** [comment]
Thanks @Tratcher. Since RC2 is not production ready yet. I will continue to use RC1. So I applied below settings in `startup.cs` file and now I am getting 500 error.

```
public void Configure(IApplicationBuilder app, ILoggerFactory LoggerFactory, IHostingEnvironment env)
        {
			app.Map("/ps", (app1) => this.Configure1(app1, env, LoggerFactory));
            LoggerFactory.AddDebug(LogLevel.Warning);
            app.UseIISPlatformHandler();
            app.UseStaticFiles();

            app.UseMvc(config =>
            {
                config.MapRoute(
                    name: "Default",
                    template: "{controller}/{action}/{id?}",
                    defaults: new { controller = "App", Action = "Index" }
                    );
            }); // Use MVC from Dependency.
        }

        private void Configure1(IApplicationBuilder app1, IHostingEnvironment env, ILoggerFactory loggerFactory)
        {
            
        }
        } 
```

I also tried this as well:
```
public void Configure(IApplicationBuilder app, ILoggerFactory LoggerFactory, IHostingEnvironment 
env)
        {
			app.Map("/ps", (app1) => this.Configure(app1, env, LoggerFactory));
            LoggerFactory.AddDebug(LogLevel.Warning);
            app.UseIISPlatformHandler();
            app.UseStaticFiles();

            app.UseMvc(config =>
            {
                config.MapRoute(
                    name: "Default",
                    template: "{controller}/{action}/{id?}",
                    defaults: new { controller = "App", Action = "Index" }
                    );
            }); // Use MVC from Dependency.
        }
```

**Comment by Tratcher** [comment]
```
        public void Configure(IApplicationBuilder app, ILoggerFactory LoggerFactory, IHostingEnvironment env)
        {
            app.Map("/ps", (app1) => this.Configure1(app1, env, LoggerFactory));
        }

        private void Configure1(IApplicationBuilder app1, IHostingEnvironment env, ILoggerFactory loggerFactory)
        {
            LoggerFactory.AddDebug(LogLevel.Warning);
            app.UseIISPlatformHandler();
            app.UseStaticFiles();

            app.UseMvc(config =>
            {
                config.MapRoute(
                    name: "Default",
                    template: "{controller}/{action}/{id?}",
                    defaults: new { controller = "App", Action = "Index" }
                    );
            }); // Use MVC from Dependency.
        }
```
