### ISSUE TITLE
Long names not supported by file system issue

### ISSUE THREAD

**Issue by npongracic** [aspnet/Home#1262]
Hello, 
I believe this is an issue that could be easily fixed but its annoying as hell.
Perhaps I'm doing something wrong but when i end up with:
D:\TFS\Settings\Settings.Web\node_modules\gulp\node_modules\gulp-util\node_modules\dateformat\node_modules\meow\node_modules\normalize-package-data\node_modules\validate-npm-package-license\node_modules\spdx-expression-parse\node_modules\spdx-license-ids\spdx-license-ids.json and get a "filename longer than supported by file system error" and can't publish, copy or delete stuff i get upset.

Please fix (how many node_modules subfolders do you need?)

Thanks,
Nebojša

EDIT:
Forgot to include my setup, Windows 10, ASP.NET 5 RC1, Visual Studio 2015 Community Edition with latest updates installed

**Comment by tlk** [comment]
You might want to switch to a superior platform until Microsoft decides to improve their products. 

Quote from http://visualstudio.uservoice.com/forums/121579-visual-studio/suggestions/2156195-fix-260-character-file-name-length-limitation
> In the interest of delivering the most value to our customers we sometimes have to make very difficult cuts, and this is one of them

Absurd, and hilarious unless you are deeply invested in their platform.

**Comment by MaximRouiller** [comment]
From what I understood... this can't be a "Visual Studio fix". It needs to
come from the OS itself and from what I heard... there's ton of hardcoded
"260" everywhere from Windows to SharePoint to customer applications.

So ... yeah....

**Comment by npongracic** [comment]
:)

But i'm not really asking to fix the 260 limit, only the absurd folder structure for dependencies.
Is it really necessary to have:
var folder = "node_modules\";
while(true) {
  folder += "{component_name}" + "\node_modules";
}

// Not sure if i have enough node_modules in filePath, lets add some more
folder += "\node_modules";

**Comment by tlk** [comment]
Yeah.... :)

The stable nodejs v5.x release from https://nodejs.org comes with npm v3 which should be [less addicted to nested "node_modules"](http://www.felixrieseberg.com/npm-v3-is-out-and-its-a-really-big-deal-for-windows/#flatmoduleinstallation) folder structures than its predecessors. You might find http://scottaddie.com/2015/08/16/npm-vs-windows-max_path-limitation/ and http://www.nikola-breznjak.com/blog/nodejs/how-to-delete-node_modules-folder-on-windows-machine/ useful.

FWIW: I use package.json and bower.json to populate the node_modules and bower_components folders. Then I use a script to copy selected files from bower_components into a project folder and keep only those selected files under version control (plus package.json, bower.json and the copy-script). I think of node_modules and bower_components as a scrapyard where anything can happen and I only go there once in a while to pick up new things or updates to things I already use.
This approach is a bit more cumbersome (but also more robust) than some of the other approaches I have heard of, such as 1) have nothing else but package.json and bower.json under version control (sad when [github is down](https://twitter.com/search?q=github%20is%20down)) or 2) have everything under version control (sad when node_modules triggers MAX_PATH issues).

**Comment by Eilon** [comment]
Check out `npm dedupe`: https://docs.npmjs.com/cli/dedupe

> Searches the local package tree and attempts to simplify the overall structure by moving dependencies further up the tree, where they can be more effectively shared by multiple dependent packages

I've used it in my own projects and it helped immensely with long path problems.

**Comment by npongracic** [comment]
Thank you all for your help.

The reason I've opened this issue because it's present out of the box with the VS 2015 asp.net 5 webapp template. 
The result is that in 99% of the use cases you can't publish your app because it complains about long file name issues (which oddly isn't a problem when npm creates the file structure on your disk).

Perhaps it could be fixed with upgrading to npm3 as tlk said (when it's done) or including the npm dedupe module and running it as a postbuild task or something in the template?

**Comment by Eilon** [comment]
@DamianEdwards @sayedihashimi @madskristensen do we have any updates in the project templates that make the deep `node_modules` hierarchy be less problematic?

**Comment by MattKunze** [comment]
Is there an option to use an updated version of node? This has been fixed for a while with npm v3 - dependencies are now stored flat in node_modules, which avoids the long path name issues on Windows. npm 3 is the default with Node 5

**Comment by Kaelum** [comment]
FYI, this IS a .NET issue, and once fixed, applications like VS and TFS will also be fixed.  I believe that it is currently being coded, but I can't find the issue that it is tied to.  However, here is the [.NET API PROPOSAL]()

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
