### ISSUE TITLE
dnvm.sh does not works on system startup in Linux Mint (Ubuntu based)

### ISSUE THREAD

**Issue by nosuchip** [aspnet/Home#1266]
Your `dnvm.sh` which pollutes my `~/.profile` file only compatible with `bash` because it contains contructions like `[[ "$_DNVM_BUILDNUMBER" = {{* ]] && _DNVM_BUILDNUMBER="HEAD"` i.e. with double square brackets. Looks like developer who wrote this code forgot that `[[` is _bash keyword_, not standard *nix utility. While X session is started and `~/profile` executed `dnvm.sh` failed because runned by `sh`, not `bash`.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
