### ISSUE TITLE
Create Visual Studio Template

### ISSUE THREAD

**Issue by senj** [aspnet/Home#1267]
I'm trying to create a Visual Studio Template out of my ASP.NET Core app.
My created *zip has everything it needs, opening the solution inside works finde.

But if I try to create via Visual Studio I only get an empty solution with nothing in it.
Any ideas?

Greetings..

**Comment by Eilon** [comment]
@senj is this the same as https://github.com/aspnet/Tooling/issues/306?

**Comment by senj** [comment]
Indeed, thanks
