### ISSUE TITLE
Is csproj dead for library authors?

### ISSUE THREAD

**Issue by kevinkuszyk** [aspnet/Home#1268]
I am in the process of adding ~~MVC 6~~ MVC Core 1 support to [Fluent Assertions for MVC](https://github.com/kevinkuszyk/FluentAssertions.MVC) ([see this PR](https://github.com/kevinkuszyk/FluentAssertions.MVC/pull/26)).

Whilst we obviously need an `.xproj` / `project.json` project for MVC Core 1, would you recommend porting the the legacy MVC 3, 4, and 5 projects over to `.xproj` / `project.json` too?

And taking this a step further, for someone creating a new library, would you recommend starting on `.xproj` / `project.json` even if the intent is to only support `net45` or `net46` at this stage?

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
