### ISSUE TITLE
Support ending for the .NET Framework 4.5.1

### ISSUE THREAD

**Issue by ycrumeyrolle** [aspnet/Home#1269]
As annonced [here](http://blogs.msdn.com/b/dotnet/archive/2015/12/09/support-ending-for-the-net-framework-4-4-5-and-4-5-1.aspx), .Net Framework 4.5.1 is no longer supported. 
Target framework in _all_ project.json shouldn't be net452 instead of net451 ?

**Comment by davidfowl** [comment]
Our libraries can run down level and that's important because of things like mono. However we'll only **support** applications running on .NET >= 4.5.2.

**Comment by sslsunvi** [comment]
I don't understand

**Comment by MaximRouiller** [comment]
Their librairies are backward compatible. No issue with the code.

What is ending is **support**. Not backward compatibility.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
