### ISSUE TITLE
vector4.clamp does not work with dnx451

### ISSUE THREAD

**Issue by Coohack** [aspnet/Home#1270]
error message: must add library "system.runtime"

**Comment by MaximRouiller** [comment]
Sample code? Project.json? Full stack trace? At runtime? at compile time

Basically... how can we reproduce?

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
