### ISSUE TITLE
Server Garbage Collection in ASP.NET Core

### ISSUE THREAD

**Issue by MJomaa** [aspnet/Home#1271]
I'm actually not quite sure what I'm asking here.
TIL that there is a different type of garbage collection for servers available.

**Screenshot:**
![image](https://cloud.githubusercontent.com/assets/9029497/12770454/dcb5dc1e-ca20-11e5-8956-ea21a3c90cd8.png)

**So my question:** Can you use the server gc in ASP.NET Core?

**Comment by moozzyk** [comment]
As per [this](https://github.com/dotnet/cli/blob/e013deadd4d7ad19934fd0831c9574a32a2ef4cf/src/corehost/cli/hostpolicy.cpp#L120) you should be the COREHOST_SERVER_GC environment variable.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
