### ISSUE TITLE
Azure website DNX Request limits

### ISSUE THREAD

**Issue by BernhardGlueck** [aspnet/Home#1272]
Hi !

I am running with ASP.NET Core 1.0 RC1 in an Azure Website 
( 64 bit , 3

We need to support quite large uploads ( api use case ) and locally using Kestrel etc this works just fine.
However in azure website hosting, we run into its request size limits. 

I have now tried to reconfigure the generated web.config during dnu publish to increase those request limits:

```
<configuration>
  <system.webServer>
   <security>
    <requestFiltering>
      <requestLimits  maxAllowedContentLength="300000000"/>
    </requestFiltering>
  </security>
    <handlers>
      <add name="httpplatformhandler" path="*" verb="*" modules="httpPlatformHandler" resourceType="Unspecified" />
    </handlers>
    <httpPlatform processPath="..\approot\web.cmd" arguments="" stdoutLogEnabled="true" stdoutLogFile="..\logs\stdout.log">
    </httpPlatform>
  </system.webServer>
</configuration>
```

But the request limits are still there... 
Any clues on how to achieve this ?

**Comment by Eilon** [comment]
@Tratcher any idea on what limits might be in place on Azure Web Sites?

**Comment by BernhardGlueck** [comment]
Its very weird, before i thought that it is the default value of 30 MB, but we're getting from time to time request errors on even 12 MB of data... so it seems ... inconsistent

**Comment by Tratcher** [comment]
Not off hand. A quick search turned up 
http://stackoverflow.com/questions/26565850/node-js-running-on-azure-website-max-file-upload
which recommends switching to chunked uploads.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
