### ISSUE TITLE
Space in path breaks dnvm use

### ISSUE THREAD

**Issue by Angeland** [aspnet/Home#1274]
The dnvm cannot do its job in cmd if the username has a space in it

```
C:\Users\username with space\Repo\TechNews\src>dnvm use 1.0.0-rc1-final -p
Adding C:\Users\username with space\.dnx\runtimes\dnx-clr-win-x86.1.0.0-rc1-final\bin to process PATH
Adding C:\Users\username with space\.dnx\runtimes\dnx-clr-win-x86.1.0.0-rc1-final\bin to user PATH
'C:\Users\username' is not recognized as an internal or external command,
operable program or batch file.
The system cannot find the path specified.
```

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
