### ISSUE TITLE
Question - How do I add references to DNX projects in the same solution

### ISSUE THREAD

**Issue by marono** [aspnet/Home#1275]
Hi,

I've got a solution which contains multiple DNX projects - class libraries. How do I add a 'project reference' to one of those? As an example:

``projectA``
```
{
  "name": "SharedLib",
  "version": "0.0.1"
}
```

``entrypoint``

```
{
  "name": "Entrypoint",
  "dependencies": {
    "SharedLib": "version???"
  }
}
```

If the SharedLib gets published, how do I make sure the entry point always references the local version all the time and doesn't try to pull a specific version from Nuget?

Ideally, I don't want to update the dependency version each time I change projectA's version. It requires more work for our build scripts.

**Comment by davidfowl** [comment]
The name property doesn't work the way you expect it to. You need to reference projects by folder name

**Comment by marono** [comment]
That's cool, what if the package being published has he same name as the folder? How does the compiler know to pick the local project and not the nuget package?

**Comment by MaximRouiller** [comment]
If I remember correctly, Local > Remote.

If local is present, there's no search for external components. That allows you to `git clone` seamlessly and drop in debug on any projects.

**Comment by marono** [comment]
Thanks @MaximRouiller 

So, say I've got version 0.0.1-alpha0 in Nuget and the local version for ``SharedLib`` is 0.0.1-alpha1
Do I need to change ``entrypoint``'s dependency version to 0.0.1-alpha1.

I'm asking because versions are generated automatically on our build machine. Do I need to script the updating of the local dependencies to avoid pulling the wrong version from Nuget?

Thanks!

**Comment by MaximRouiller** [comment]
Or maybe just depend on ` 0.0.1-alpha*` (haven't tested if this work)? Just beware... I think this last part of the string (alpha1) will comparer characters. So... `alpha2` > `alpha10`.

**Comment by marono** [comment]
Yes, but then when going to 2.0.0 I still need to remember to update the dependency version. I'm still hopping there's an easier way...

**Comment by MaximRouiller** [comment]
If those are internal projects, just put `*` and it will take the latest version. 

When you need a specific version it's where you put in the `2.0.*` or anything along those lines. 

See it that way... you are declaring a dependency. You are telling .NET: 

> My application need version `X` of this dependency to run. 

Whether it's the latest (`*`), a specific version (`2.0.2`) or the latest major version (`2.*`)... you are in charge of choosing the right version.

**Comment by marono** [comment]
Ok, thanks for the clarification.
