### ISSUE TITLE
What is the best way to return a response in gzip?

### ISSUE THREAD

**Issue by muratg** [aspnet/Home#1276]
_From @mwalterXML on February 4, 2016 13:9_

Hello 

We are using kestrel server to run differens Web APIs, 
We need to return the json response compress in gzip.

Is posible using only Kestrel?

Thanks
Best regards,
Mitchell

_Copied from original issue: aspnet/KestrelHttpServer#613_

**Comment by muratg** [comment]
_From @davidfowl on February 4, 2016 16:20_

> Is posible using only Kestrel?

This has nothing to do with kestrel. You can just write a middleware that does gzipping. You can even do it in MVC if you want to.

**Comment by muratg** [comment]
_From @GuardRex on February 4, 2016 16:29_

@mwalterXML You can see the `System.IO.Compression` tests here: https://github.com/dotnet/corefx/blob/master/src/System.IO.Compression/tests/GZipStreamTests.cs

**Comment by davidfowl** [comment]
We now have a response compression middleware that can do this https://github.com/aspnet/BasicMiddleware/tree/dev/src/Microsoft.AspNetCore.ResponseCompression
