### ISSUE TITLE
Conditional Project References - is this possible?

### ISSUE THREAD

**Issue by dazinator** [aspnet/Home#1278]
In the old style msbuild project files, you could add a conditional reference (to an assembly or project) based upon the current build configuration.

Can this be done in project.json?

For example, I need to add a dependency to another project in the solution  but only when in "Debug" mode. 

```

"dependencies": {   
   // I only want this when in Debug build configuration!
    "MyModuleProject": "1.0.0-*"
  },
```

The reason for this is because my Application is Modular, and in release mode, these projects actually get installed as seperate extensions at runtime, however in Debug mode, its useful for them to be project references so that they are all loaded up by the application automatically and you get a nice familiar debugging experience, without having to go through a module install process.

**Comment by MaximRouiller** [comment]
I only see this issue in your very specific scenario of loading plugins/dlls after the first project load.

I would check into having custom script that drops your plugins at the right place. 

Before this can be considered a feature, is there other scenarios where this would work? What happens when (while developing) somebody uses a class from that module (it doesn't compile in "release" anymore)? 

That brings a whole lot more of complexity to a simple build.

For your scenario, I would think about creating a gulp/grunt task that will copy your files at the right place and it would work beautifully.

**Comment by tugberkugurlu** [comment]
You can do this with a compile module. I am not sure if complie modules will stick around after the dotnet CLI replacement though.

**Comment by dazinator** [comment]
@tugberkugurlu  - that sounds good but I have not heard of a Compile Module before. Any chance you could point me towards some docs?

**Comment by dazinator** [comment]
@tugberkugurlu - So I have a simple Compile Module and I am guessing what I need to do, `BeforeCompile` add the additional project references, when the Current Configuration is Debug.

I have browsed through the public API but I am struggling to figure out how to add a project reference to the "BeforeCompileContext".

Can anyone suggest whether that is possible, and how to do so?

```

public class CompileModule : ICompileModule
    {
        public void BeforeCompile(BeforeCompileContext context)
        {          
            var config = context.ProjectContext.Configuration;
            if (config.ToLowerInvariant() == "debug")
            {
                var currentProjectDir = context.ProjectContext.ProjectDirectory;
               
                // In order to add a project reference, I am not sure whether I need a path to the dll, the nupkg, or the project.json file of th other project?
                var otherProjectPath = System.IO.Path.Combine(currentProjectDir, "..\\MyOtherProject\\MyOtherProject.json");
                context.Compilation.?? // how to add?            
              
            }      

        }

        public void AfterCompile(AfterCompileContext context)
        {


        }
    }
```

**Comment by dazinator** [comment]
@MaximRouiller - I have considered the custom script that drops the plugin assemblies in the right location but that would be problematic from a debugging perspective, as I think you will loose "edit and continue" whilst debugging. For example, with a project reference, you can directly edit the code whilst debugging, and use the edit and continue functionality. With the custom script approach, I'd have to run the script after every change to the code and wait for it to copy the assembly over, and then have logic to "restart" my application - in order to reload the new assembly which is problematic as that will terminate the debugging session also. This can all be avoided if we could have a conditional project reference.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
