### ISSUE TITLE
Mention Azure+Docker images in Linux/Docker section of the getting started docs

### ISSUE THREAD

**Issue by mjrousos** [aspnet/Home#1279]
In the getting started docs related to hosting in a [Docker container](https://docs.asp.net/en/latest/getting-started/installing-on-linux.html#using-docker), we should mention that Azure has Ubuntu images with Docker pre-installed (as described [here](https://azure.microsoft.com/en-us/documentation/articles/virtual-machines-docker-ubuntu-quickstart/)). For customers just trying out Docker+ASP.NET for the first time, that can be a convenient way to get started quickly.

**Comment by Eilon** [comment]
@glennc ?
