### ISSUE TITLE
‘dev’ branch compilation issues

### ISSUE THREAD

**Issue by victorhurdugaci** [aspnet/Home#1280]
Discussions for https://github.com/aspnet/Announcements/issues/150

**Comment by ivaylokenov** [comment]
@victorhurdugaci Are you going to update the myget feed with latest developer versions before the transition to the CLI. They have not been updated for a month currently and it will really help people like me who are building ASP.NET packages and using a lot of the framework's infrastructure classes and interfaces. Thank you for your answer in advance.

**Comment by muratg** [comment]
@ivaylokenov Converting ASP.NET and EF packages to use dotnet CLI has been disruptive as called out in the announcement post, and we are working through several issues, including build and test failures. This is the main reason why aspnetvnext feed has not been updated in a while.  

If you're willing to play with the bleeding edge, you can try the packages from [our dev feed (aspnetcidev)](https://www.myget.org/gallery/aspnetcidev). Be warned though, these packages are unsigned, and also they are not tested at all. So things may or may not work.

**Comment by ErikEJ** [comment]
@muratg Sadly, that (the cidev) feed seems to be stuck in time as well

**Comment by muratg** [comment]
@ericstj Last set of packages are 5 days old, I think that's recent enough for if you really want to play with the latest bits.  The packages in aspnetcidev feed are considered "coherent", meaning that we at least know the packages have matching versions and their dependencies between themselves are correct.

For more details about our feed details, please see @victorhurdugaci's notes [here](https://github.com/aspnet/Home/wiki/NuGet-feeds).

**Comment by ivaylokenov** [comment]
@muratg Thanks, will take a look at the cidev feed!

**Comment by GuardRex** [comment]
@muratg I'm on the CI feed with `dotnet cli` projects. Talking about "dev branches" isn't very specific. Is this Announcement primarily referring to changes with the `aspnetvnext` feed? ... or should those of us on the CI feed also be freezing package references for a bit?

**Comment by muratg** [comment]
@GuardRex This announcement is about the stability issues in `dev` feeds across all aspnet repos. These issues prevent us from creating tested and signed packages to feed into `aspnetvnext` feed.

If you've been using `asnetcidev` feed for development, you're already on the bleeding edge. The packages there are not tested or signed.

As soon as we're unblocked with these changes, `aspnetvnext` would have tested/signed packages that you can move to.

For more information about the feeds and how they're used, feel free to check out this: https://github.com/aspnet/Home/wiki/NuGet-feeds

**Comment by benaadams** [comment]
Whoop! Its alive...

**Comment by GuardRex** [comment]
:tada: Congrats to the team! :tada:

**Comment by MaximRouiller** [comment]
:fireworks: Congrats! :tada:

**Comment by MaximRouiller** [comment]
Now to have a date for the actual RC2. :wink:

**Comment by tuespetre** [comment]
:clap: :confetti_ball: :tada:

**Comment by mikehaas763** [comment]
Anyone have repro steps to build? I've cloned the Home repo and tried running `dotnet restore` with `dotnet run` with no luck in `samples/latest/{HelloMvc,HelloWeb}`.

Just for science.

**Comment by victorhurdugaci** [comment]
@mikehaas763 we didn't update the samples in the Home repo yet. Sorry. Try the ones in entropy

**Comment by davidfowl** [comment]
https://github.com/aspnet/cli-samples

**Comment by moozzyk** [comment]
:+1: to what @davidfowl says. I have been keeping cli-samples in the working state.
