### ISSUE TITLE
What is the status of the ASP.NET Web API Help Page system?

### ISSUE THREAD

**Issue by ghost** [aspnet/Home#1281]
The last release was [Microsoft ASP.NET Web API 2.2 Help Page 5.2.3](http://www.nuget.org/packages/Microsoft.AspNet.WebApi.HelpPage), which was released on 2/9/2015.  ASP.NET Core 1.0 is a completely different animal, and the existing Help Page system doesn't work in a self host environment.  Has this project been abandoned?  If not, is it on the road map?

**Comment by Eilon** [comment]
In ASP.NET Core MVC we're promoting using API description standards such as Swagger/Swashbuckle, which MVC helps enable using its new ApiExplorer API. We have a [sample site](https://github.com/aspnet/Mvc/tree/dev/test/WebSites/ApiExplorerWebSite) that shows a few things you can do with ApiExplorer. And also check out https://github.com/domaindrivendev/Ahoy for a project that uses ASP.NET Core MVC to produce API metadata descriptions.

cc @rynowak

**Comment by Kaelum** [comment]
Hey Eilon,

That's AWESOME news!  I'll take a look at it.  If it is somewhat similar to the auto-generated legacy web service information pages, or a hybrid of them with the Web API Help Pages, I'd really be ecstatic.

Again, Thank you very much for the quick response...

**Comment by Eilon** [comment]
@Kaelum I'd wager it's a bit fancier in the sense that it targets an established standard, so there is more opportunity for a bright future and various clients to consume the data and produce a rich UI.

**Comment by jholovacs** [comment]
Swagger/ Swashbuckle is a large step backwards IMO.

- The UI is much heavier and more difficult to style
- It requires unnecessary decorations (and will literally fail your entire application if one isn't where it's expected) in the endpoints
- It's a pain in the butt to customize with app-specific features (like authorization roles/ policies, or special notes)
- Object drilldown support is poor
- XML documentation support is poor (only the basic summary and params, ignores _seealso_ references

How difficult would it be to retrofit the original help pages to .NET Core?

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
