### ISSUE TITLE
DNVM Upgrade "Access Denied"

### ISSUE THREAD

**Issue by brentarias** [aspnet/Home#1283]
After installing DNVM, I ran "dnvm upgrade" and received the following error message:

```
Installing to C:\Users\baria\.dnx\runtimes\dnx-clr-win-x86.1.0.0-rc1-update1
Move-Item : Access to the path 'C:\Users\baria\.dnx\runtimes\temp\' is denied.
At C:\Users\baria\.dnx\bin\dnvm.ps1:1472 char:21
+                     Move-Item $UnpackFolder $RuntimeFolder -Force
+                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (C:\Users\baria\.dnx\runtimes\temp\:DirectoryInfo) [
   Move-Item], IOException
    + FullyQualifiedErrorId : MoveDirectoryItemIOError,Microsoft.PowerShell.Commands.MoveItemC
   ommand

Cannot find dnx-clr-win-x86.1.0.0-rc1-update1, do you need to run 'dnvm install
1.0.0-rc1-update1'?
At C:\Users\baria\.dnx\bin\dnvm.ps1:1667 char:9
+         throw "Cannot find $runtimeFullName, do you need to run '$Com ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Cannot find dnx...0-rc1-update1'?:String) [],
    RuntimeException
    + FullyQualifiedErrorId : Cannot find dnx-clr-win-x86.1.0.0-rc1-update1, do you need to ru
   n 'dnvm install 1.0.0-rc1-update1'?
```

The command was executed in an elevated cmd prompt.

This appears to be the same issue as [described here](http://www.c-sharpcorner.com/UploadFile/efa3cf/resolving-Asp-Net-5-dnvm-upgrade-issue-and-changing-dnx-vers/).  Unfortunately, the recommended fix provided in that link is not working for me.  That is, I tried deleting the `%userprofile%\.dnx\bin` folder, and then running this:

> @powershell -NoProfile -ExecutionPolicy unrestricted -Command "&{$Branch='dev';iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.ps1'))}"

This problem occurred on a fresh install of Windows 10 Home.  I had followed the ASP.NET 5 installation instructions [found here](https://docs.asp.net/en/latest/getting-started/installing-on-windows.html).  That is, I installed Visual Studio 2015 Update 1 with the `Microsoft Web Developer Tools` option selected, and then I installed ASP.NET 5 separately.

About a week earlier, I had also installed ASP.NET 5 on a fresh Windows 10 Professional box.  I followed the same installation instructions and it worked correctly.  I don't see why I should have any trouble the second time around.  Presumably the different Windows 10 editions (Home / Professional) is irrelevant?

**Comment by softgandhi** [comment]
+1. I am also facing the same issue.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
