### ISSUE TITLE
No kestrel command in the project.json file for HelloWeb

### ISSUE THREAD

**Issue by kraades** [aspnet/Home#1284]
There is no kestrel command in the project.json file for HelloWeb.
This is needed to run it on Linux.

**Comment by davidfowl** [comment]
It's not, use the web command:

https://github.com/aspnet/Home/blob/dev/samples/1.0.0-rc1-update1/HelloWeb/project.json#L21

**Comment by kraades** [comment]
Right, I didn't realize that the web command was pointing to kestrel...

But if you look at the Dockerfile the command kestrel is used.
https://github.com/aspnet/Home/blob/dev/samples/latest/HelloWeb/Dockerfile#L38
Resulting in the following error:
`Error: Unable to load application or execute command 'kestrel'. Available commands: web.`

But if you change the Dockerfile into:
`ENTRYPOINT ["dnx", "kestrel"]`
You again will get an error:
`Microsoft.AspNet.Server.Kestrel' does not contain a 'Program' type suitable for an entry point`

**Comment by davidfowl** [comment]
The docker file needs an update to say web instead of kestrel.

**Comment by kraades** [comment]
Agreed. But...

Sorry, I made a mistake in the previous post. It should read:
(notice the "web" instead of "kestrel")

But if you change the Dockerfile into:
`ENTRYPOINT ["dnx", "web"]`
You again will get an error:
`Microsoft.AspNet.Server.Kestrel' does not contain a 'Program' type suitable for an entry point`

**Comment by davidfowl** [comment]
Are you using RC1 or RC2?

**Comment by kraades** [comment]
Latest.

**Comment by Tratcher** [comment]
HelloWeb has not be updated for RC2. You need do more than just update the command.

The web command should be:
`"web": "HelloWeb --server=Microsoft.AspNetCore.Server.Kestrel --server.urls http://*:5004"`

Then you need to add a Program.Main like this:
https://github.com/aspnet/Hosting/blob/dev/samples/SampleStartups/StartupHelloWorld.cs#L28

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
