### ISSUE TITLE
How to consume mixed mode assembly in Asp.net 5?

### ISSUE THREAD

**Issue by leo9223** [aspnet/Home#1285]
how can I use mixed mode assembly in Asp.net 5?

**Comment by Eilon** [comment]
@leo9223 I would imagine you use it the same as any other assembly. Did you try something and it didn't work?

**Comment by leo9223** [comment]
I have tried. Mixed mode assembly is not working asp.net 5. But its working in old asp frameworks.

**Comment by Eilon** [comment]
Can you provide more details on what isn't working? You get an error?

**Comment by leo9223** [comment]
Yes it gives error at runtime. I didn't remember the exact error right now but that's about mixed mode assembly. Ill provide more details soon.

**Comment by Eilon** [comment]
Any details you have on the exact error would be very helpful, thanks!

**Comment by leo9223** [comment]
- In Asp.net5 is FileNotFoundException, dll is referenced in an ordinary way
[http://s12.postimg.org/vbns5b4m5/img1.png](url)
[http://s12.postimg.org/ctjfl2mu5/img2.png](url)


- In Asp.net4 it works like a charm


- In console application it gives error of Mixed Mode assembly but works if we enable useLegacyV2RuntimeActivationPolicy="true" in <startup> tag in app.config file

**Comment by MaximRouiller** [comment]
Just rehosting the images. :smile: 

![image](https://cloud.githubusercontent.com/assets/209384/13220696/7c3af336-d945-11e5-911c-5df4ea26ebed.png)
![image](https://cloud.githubusercontent.com/assets/209384/13220698/7e3c808c-d945-11e5-86d4-25536e1a4507.png)

**Comment by Eilon** [comment]
@leo9223 yeah that's weird. So it's a single mixed-mode assembly, or is it a managed assembly that calls into a separate native DLL? Any chance you could try this with dotnet-cli (https://github.com/dotnet/cli/)? That is replacing DNX (but still uses project.json, etc.) so if there's a fix, it would go in there.

cc @davidfowl in case you have any thoughts on this.

**Comment by leo9223** [comment]
@MaximRouiller Thank you !


@Eilon Sir its a single mixed mode assembly written in 2003. 

is dotnet cli is coming with RC2 ?

How can we do useLegacyV2RuntimeActivationPolicy="true" in Asp.net5? I did this in wwwroot folder in web.config with no success !!

**Comment by davidfowl** [comment]
> is dotnet cli is coming with RC2 ?

Yes

> How can we do useLegacyV2RuntimeActivationPolicy="true" in Asp.net5? I did this in wwwroot folder in web.config with no success !!

@leo9223 `app.config` in the root should apply to ASP.NET Core 1.0 projects running on .NET Framework.

**Comment by leo9223** [comment]
@davidfowl ThankYou Sir, Ill give it a try

**Comment by santos222** [comment]
@davidfowl Did you manage to resolve this? I have the same issue and that entry in the web.config isn't resolving it, nor does creating an app.config file in wwwroot.

**Comment by leo9223** [comment]
@Eilon 
@davidfowl 

I have tried in RC2 with net461 now it gives error at runtime "could not load file or assembly"

**Comment by Eilon** [comment]
@leo9223 if you're still having an issue with RC2, please file a new issue at https://github.com/dotnet/cli/issues/ with the necessary information to reproduce the information. All the assembly loading logic has moved from DNX to the new .NET CLI, so hopefully the team working on that can help you out.
