### ISSUE TITLE
where is SHA512Managed in .NET CORE?

### ISSUE THREAD

**Issue by giancarloa** [aspnet/Home#1287]
hello... I am trying to convert some code over to .NET CORE and am having trouble converting the code below... is basically hashes a password using SHA512Managed... can anyone please assist???? on the internet all I have been able to find is old conflicting information, and I guess that makes sense with all of this changing so much and constantly... thank you

using (SHA512 shaM = new SHA512Managed())
                {
                    userPassword.Password = shaM.ComputeHash(Encoding.UTF8.GetBytes(saltedPassword));
                }

**Comment by pranavkm** [comment]
`var sha512 = SHA512.Create()` should be equivalent to what you have.

**Comment by giancarloa** [comment]
thanks @pranavkm ... but do you know which package???? that's the most confusing part of trying to convert to .net core... and that is figuring out which packages are needed since now everything is spread all over the place... thanks

**Comment by GuardRex** [comment]
@giancarloa Try the Reverse Package Search ... http://packagesearch.azurewebsites.net/

**Comment by pranavkm** [comment]
@GuardRex, it doesn't seem to list the type (just other references to `SHA512`). Perhaps it hasn't been updated in a while. 
@giancarloa it's located in https://www.nuget.org/packages/System.Security.Cryptography.Algorithms/4.0.0-beta-23516

**Comment by blowdart** [comment]
As this isn't an ASP.NET issue, and it's been answered, I'm closing and locking this.

For .NET Core issues their repo is right over there -> https://github.com/dotnet/corefx
