### ISSUE TITLE
ASP.NET 5 windows authentication integration

### ISSUE THREAD

**Issue by raymak23** [aspnet/Home#1288]
Hello,

I am creating an intranet application with windows authentication enabled. I enabled windows authentication in IIS and I am able to access the application with logged in user to windows. Now what I am trying to do is to restrict some controller and only allow specific users and roles access to that content. 

I looked at several documents online which are for ASP.NET 4 or older version and most of them are using this `[Authorize(Users = @"CONTOSO\Rick, CONTOSO\Keith, CONTOSO\Mike")]` as an example. In my application I tried `[Authorize(Roles = @"DOMAIN\GROUP_NAME")]`, and I get 403 forbidden error. I also checked the official asp.net 5 [documentation](https://docs.asp.net/en/latest/) but I dont see any document on windows authentication with user / role base access. 

I also posted this issue at [stackoverflow](http://stackoverflow.com/questions/35271807/how-to-authorize-using-windows-authentication-in-asp-net-5), but I am not sure if the community can help me much.

Any suggestion is really appreciated. :)

**Comment by blowdart** [comment]
There is a bug in RC1 where this doesn't work. It will be fixed in RC2.

**Comment by raymak23** [comment]
Gotcha thank you. Looking forward for it. :+1:
