### ISSUE TITLE
Using a generic list in tag helpers

### ISSUE THREAD

**Issue by muqeet-khan** [aspnet/Home#1291]
Is there a way to:

```
    public class ScCollectionContainsTagHelper : TagHelper
    {
        public List<T> Source { get; set; }
        public T item { get; set; }

        public override async Task ProcessAsync(TagHelperContext context, TagHelperOutput output)
        {
...
        }
    }
```

As of now, I am able to get away with: 

```
    public class ScCollectionContainsTagHelper : TagHelper
    {
        public List<object> Source { get; set; }
        public object item { get; set; }

        public override async Task ProcessAsync(TagHelperContext context, TagHelperOutput output)
        {
...
        }
    }
```

I would like to take a generic list as source and run a contains method on it to append HTML content for true.

**Comment by dougbu** [comment]
Tag helpers are actually designed to avoid requiring generics. MVC's  [`ModelExplorer`](https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.ViewFeatures/ViewFeatures/ModelExplorer.cs) fills a similar purpose, exposing the model or a model expression to tag helpers. [`RazorPage<T>`](https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Razor/RazorPageOfT.cs) does the heavy lifting, with some help from the Razor code gen extensions in MVC. Have a look at how any of the `asp-for` attributes in most of the [MVC tag helpers](https://github.com/aspnet/Mvc/tree/dev/src/Microsoft.AspNetCore.Mvc.TagHelpers) are used.

If `ModelExplorer` doesn't provide everything you need, please describe more about your scenario.

**Comment by FilipZamec** [comment]
Sorry to open up an old question, but what about this:
```csharp
@(Html.Kendo().Grid<Kendo.Mvc.Examples.Models.CustomerViewModel>()
        .Name("grid")
        .Columns(columns =>
        {
            columns.Bound(c => c.ContactName)
            .ClientTemplate(
                @"<div class='customer-photo' 
                    style='background-image: url(" + @Url.Content("~/content/web/Customers/#:data.CustomerID#.jpg") + ");'></div><div class='customer-name'>#: ContactName #</div>")
              .Width(240);
            columns.Bound(c => c.ContactTitle);
            columns.Bound(c => c.CompanyName);
            columns.Bound(c => c.Country).Width(150);
        })
        ....
)
```
(taken from Telerik controls: https://demos.telerik.com/aspnet-mvc/grid)

It's easy to implement columns in HtmlHelper (because it's generic), but how can we do it in TagHelper?

Thanks

**Comment by Eilon** [comment]
This issue was moved to aspnet/Razor#1923
