### ISSUE TITLE
dnu restore using cached pre-release package versions

### ISSUE THREAD

**Issue by colin-young** [aspnet/Home#1292]
I am restoring on my build server in a powershell script like so:

`& dnu restore --no-cache -f http://{my local NuGet server} ("""" + $DirectoryName + """"); if($LASTEXITCODE -ne 0) { exit 1 }`

Unfortunately I have dependencies on local pre-release packages. We have a NuGet server internally that hosts them. The issue is I depend on e.g. `MyPackage-1.0.0-*`. 
- Previously I had a build that was `MyPackage-1.0.0-beta-9` and now I am at `MyPackage-1.0.0-beta-16`
- the NuGet server no longer has any releases < 10, i.e. the `beta-9` one is gone (as are 8, 7, 6, 5, 4, 3, 2 and 1)

I have deleted the `project.lock.json` file and run `dnu clear-http-cache` in addition, but no matter what I do, I keep getting a dependency on `MyPackage-1.0.0-beta-9` (8 on my dev machine).

I understand that SemVer treats the pre-release as text and is sorted as-such, therefore `beta-9` is "newer" than `beta-`6`, but if my NuGet server no longer has`beta-9` and the lock file is deleted, where is it getting that version from and how do I get rid of it?

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
