### ISSUE TITLE
How do i debug against the source?

### ISSUE THREAD

**Issue by TheoAndersen** [aspnet/Home#1293]
I've been trying to figure out how to run/debug against the source and have not found any information that seems to be working.

I have found this old blog entry (https://blogs.msdn.microsoft.com/webdev/2015/02/06/debugging-asp-net-5-framework-code-using-visual-studio-2015/).
But it dosen't seem to work. Sources is now called Projects in global.json it seems, but nothing changes when i enter a local src in there.

Is there any better resource on how to debug/run against the sources?

Thanks
/Theo

**Comment by pranavkm** [comment]
Could you add what your global.json looks like? Also, have you tried restoring after you've updated global.json?

**Comment by TheoAndersen** [comment]
I think ill just create a reference github project next, so you can see what I'm doing.

But first, what are the steps to debug against the source? Is it as stated in the article i mentioned, that you add the project into a solution, with a global.json with the source/projects property pointing at an array of paths?

Is there anything else one needs to do or setup?
Or is this described anyplace?

**Comment by pranavkm** [comment]
That sounds about right. Once you restore, you should see VS include projects referenced as source in your solution.

**Comment by TheoAndersen** [comment]
I just upgraded to Rc1-Update1 - and when scaffolding a new web application and adding source reference to the "projects" attribute of the global.json - it worked. Suddently the core source code i had added the source to, was added to the solution

But i tried to add a solution to my existing aspnetcore project along with the global.json - and this didnt work - nothing happened.

How do i find out what is going wrong here? I cant seem to find anything in the restore logs. Is there any way to introspect what the "Restore" does with this to find errors like this?
It does seem rather magical what happens, and it dosen't really seem described anywhere - other than that old blogpost that is outdates (mentions "sources" and not "projects").

Is there another way of debugging against the "sources" that is not quite as 'magical'?

And why the solution dependency? i thought that the old solutions and projects was entirely out of the picture here? How does this work on mac/linux?

I would really love to be able to run against the sources on this. It seems the general documentation of aspnetcore is still a bit sparse, so its great to be able to look at the source too see whats happening behind the covers (and see why I'm using the api's wrongly) - but much better would be if i could do this in my dev environment (fx in Visual Studio) and be able to debug though it all.

If this isn't easy to do I'm a fraid a lot of people will have a hard time contributing to aspnetcore.

/Theo

**Comment by pranavkm** [comment]
> But i tried to add a solution to my existing aspnetcore project along with the global.json - and this didnt work - nothing happened.

Sorry, I don't follow what this means.

If you run `dnu restore` or look in the Output window in VS, you should see the output from dnu. Most restore errors should show up as errors in the References node under the project (they would have an exclamation symbol). It doesn't seem particularly magical - you tell the restore here are additional locations to look for sources in. When resolving dependencies, it prefers source projects to NuGet packages and builds against the source. An alternative to using `global.json` would be to `dnu pack` the external dependency and get your application to reference this package.

Solutions are simply VS's way of keeping track of project. They don't affect what gets built or how things are resolved.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
