### ISSUE TITLE
Support on CentOS 7.1

### ISSUE THREAD

**Issue by rohitshrivastava04** [aspnet/Home#1294]
In our organization, we are planning to develop our next big project on .Net Core and deploy on Linux. As of now its supported only on ubuntu. One thing which I am keen to know is when is the target to support core clr on CentOS.

Can anyone tell me where is the CentOS support on the roadmap?

**Comment by MaximRouiller** [comment]
I don't know for support but it seems to be in the "runtimes".

https://github.com/dotnet/corefx/blob/master/pkg/Microsoft.NETCore.Platforms/runtime.json

If you are looking for support for .NET Core on other platforms, I think it would make more sense to ask in dotnet/corefx than in ASP.NET. 

Correct me if I'm wrong and of course... it's just my 2 cents.

**Comment by davidfowl** [comment]
+1 to @MaximRouiller better to ask in dotnet/corefx

**Comment by rohitshrivastava04** [comment]
as of now I am not able to install coreclr on centos. And below link has a note regarding this.

https://docs.asp.net/en/latest/getting-started/installing-on-linux.html#installing-on-centos-7

@davidfowl corefx or coreclr?

**Comment by davidfowl** [comment]
Either really.

**Comment by rohitshrivastava04** [comment]
Opened in coreclr 
https://github.com/dotnet/coreclr/issues/3129
