### ISSUE TITLE
What is dotnet5.4 and the framework property in project.json

### ISSUE THREAD

**Issue by gdoron** [aspnet/Home#1296]
I thought `framework` property in `project.json` is the runtime version the DNX should be using when executing the project.

But when I create a new ASP.NET 5 project, I have this `global.json` file:

    {
      "version": "1.0.0-*",
      "compilationOptions": {
        "emitEntryPoint": true
      },
    
      "dependencies": {
        "Microsoft.AspNet.IISPlatformHandler": "1.0.0-rc1-final",
        "Microsoft.AspNet.Server.Kestrel": "1.0.0-rc1-final"
      },
    
      "commands": {
        "web": "Microsoft.AspNet.Server.Kestrel"
      },
    
      "frameworks": {
        "dnx451": { },
        "dnxcore50": { }
      },
    
      "exclude": [
        "wwwroot",
        "node_modules"
      ],
      "publishExclude": [
        "**.user",
        "**.vspscc"
      ]
    }

Which seems OK since it means it can run both on the full CLR version 4.5.1 and on core CLR version 5.0

So far seems reasonable, but when I create a *Package Class Library* project, the global.json is:

    {
      "version": "1.0.0-*",
      "description": "Test Class Library",
      "authors": [ "Doron Grinzaig" ],
      "tags": [ "" ],
      "projectUrl": "",
      "licenseUrl": "",
    
      "frameworks": {
        "net451": { },
        "dotnet5.4": {
          "dependencies": {
            "Microsoft.CSharp": "4.0.1-beta-23516",
            "System.Collections": "4.0.11-beta-23516",
            "System.Linq": "4.0.1-beta-23516",
            "System.Runtime": "4.0.21-beta-23516",
            "System.Threading": "4.0.11-beta-23516"
          }
        }
      }
    }

Unless I was asleep for several months, there's no CLR version **5.4**, and why one framework says `netxxx` and the other one says `dotnetxxx`.
Also, trying to add `"EntityFramework.Commands": "7.0.0-rc1-final",` as a dependency fails with the error:

> Error	NU1002	The dependency EntityFramework.Commands 7.0.0-rc1-final in project Test does not support framework .NETPlatform,Version=v5.4.

Is it a bug or I simply don't understand what `framework` is in ASP.NET 5?

[Visual studio version info](http://pastebin.com/gNhjEmxx)

**Comment by gdoron** [comment]
I just saw this [announcement](https://github.com/aspnet/Announcements/issues/98).
I still don't get why dnxcore50 is dotnet5.4 (where did 5.4 come from?), and I think the naming (net vs dotnet) are really confusing but at least I understand what each is.

If you think the naming is good enough you can close the issue.
Thanks.

**Comment by 304NotModified** [comment]
I'm also curious why it's called 5.4

**Comment by gdoron** [comment]
@304NotModified I think it's just minor version 4 of the dotnet core framework which was (badly) name _dotnet5_.
Since I read they're going to change the name in RC2 to _netstandard_, the naming was already fixed.
I'm closing the issue.

**Comment by 304NotModified** [comment]
no it's not a minor version

> NET Platform 5.0, 5.1, 5.2, 5.3, 5.4, and 5.5 exist all of a sudden, all at once: there already exist multiple "levels" of .NET Platform that need to be described in this new uniform way.

> To read the full story about this, check out this far more detailed spec: https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/standard-platform.md
