### ISSUE TITLE
Documentation uses defunct monikers (e.g "dotnet50" should be "dotnet5.4")

### ISSUE THREAD

**Issue by Emyr42** [aspnet/Home#1297]
https://github.com/aspnet/Home/wiki/Project.json-file
This wiki page has not been updated as per the announcement on 2015-10-31: https://github.com/aspnet/Announcements/issues/98

**Comment by Emyr42** [comment]
The latest samples also contain old monikers:
https://github.com/aspnet/Home/search?utf8=%E2%9C%93&q=dnxcore50

**Comment by GuardRex** [comment]
The announcement pertains to class libraries.

**Comment by Emyr42** [comment]
Ok, it isn't at all confusing that monikers that are valid in the "frameworks" part depends on the project type.

**Comment by GuardRex** [comment]
This may help clarify ... 

https://github.com/aspnet/Home/issues/1047

but yeah ... I'm very much looking forward to maybe two weeks from now, when RC2 (nightly) will get the .NET Platform Standard ...

https://github.com/dotnet/corefx/blob/master/Documentation/architecture/net-platform-standard.md

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
