### ISSUE TITLE
config file cross reference value from another key. 

### ISSUE THREAD

**Issue by singlewind** [aspnet/Home#1298]
![image_thumb_5](https://cloud.githubusercontent.com/assets/7637/12998893/94fdffac-d194-11e5-90bc-1502f47972f7.png)

This image I got from ScottGu's blog. I thought it is global feature. I think I was wrong, it is EntityFramework feature. Anyone knows how this get implemented. I didn't get any luck by search in EntityFramework source code.

**Comment by Tratcher** [comment]
At a guess:
`Config[Config["EntityFramework:ApplicationDbContext:ConnectionStringKey"]]`

**Comment by singlewind** [comment]
At the end, I think I discard the idea, change to "name=key" if the connectionstring is "name=key", it will look one more level deep search for value.

**Comment by Eilon** [comment]
@rowanmiller was wanting a feature like this at some point but in the end we decided not to do it. See https://github.com/aspnet/Configuration/issues/129
