### ISSUE TITLE
Docker image size (dnu restore)

### ISSUE THREAD

**Issue by ArkadyB** [aspnet/Home#1299]
Hi,

Im curious about "dnu restore" command functionality.
Having 1.0.0-rc1-update1-coreclr image size of 357 mb`s, a build image with "hello world" WEB API app becomes 913 mb`s after "dnu restore". Is there some workaround to make it smaller? Or to have restore command to not download everything possible?

**Comment by peterblazejewicz** [comment]
@ArkadyB
Follow the last link on our Docker section:
https://github.com/omnisharp/generator-aspnet#dockerfile
The talk discusses different ways of optimizing Dockerfile for use with ASP.NET Core

**Comment by lgreenlee** [comment]
@ArkadyB I looked into this. Most of the "bloat" is from the NuGet packages and basic system dependencies. You can use du -h --maxdepth=1 to identify large directories in your image after it is built.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
