### ISSUE TITLE
Cannot run Home\samples\latest\HelloMvc sample

### ISSUE THREAD

**Issue by jannavarro** [aspnet/Home#1300]
Went into Home\samples\latest\HelloMvc.

Run dnu restore.
Run dnx web.

Error: 'Microsoft.AspNet.Server.Kestrel' does not contain a static 'Main' method suitable for an entry point

**Comment by PowerCodX** [comment]
I have same problem.

**Comment by Tratcher** [comment]
https://github.com/aspnet/Home/pulls

**Comment by Tratcher** [comment]
https://github.com/aspnet/Home/pull/1277

**Comment by jannavarro** [comment]
@Tratcher I'm a little bit new in mvc so I got confused whether the issue you mentioned means that I should install the dotnet cli in order to run the samples?

Also I looked at [Startup.cs](https://github.com/aspnet/Home/blob/dev/samples/latest/HelloMvc/Startup.cs) of the sample and it only has a Configure method and no main method. Is this new in aspnet core?

**Comment by PowerCodX** [comment]
@jannavarro Look at this sample: [CLI Samples - HelloMVC](https://github.com/aspnet/cli-samples/tree/master/HelloMvc). This example contains Program.cs file that contains the entry point of this application.

For aforementioned sample you need to install .Net Core which you download from [https://dotnet.github.io/getting-started/](https://dotnet.github.io/getting-started/)

**Comment by GarageWeb** [comment]
I was able to get these to work from the command line with kestrel. Is there anyway to launch these in iisexpress etc. from visual studio 2015 yet?

**Comment by oblomingo** [comment]
I have same problem.

**Comment by jannavarro** [comment]
@oblomingo use the one powercodx mentioned. It worked for me

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
