### ISSUE TITLE
Visual Studio CLR Type (Profile)

### ISSUE THREAD

**Issue by cataquil** [aspnet/Home#1301]
VS is defaulting to runtime: clr arch:x86 

I have created a global.json file in the solution

but aspnet still loads clr-x86-rc1-update1, unless I specifically set it to coreclr
in project properties or CLR Types.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
