### ISSUE TITLE
Select dropdown list will fail if the Select is closed with />

### ISSUE THREAD

**Issue by grantnilsson** [aspnet/Home#1302]
Is it expected that a <Select... dropdown list will not work if you close it with /> 
versus closing with ></select>, even if there are no options?

I created an enum list and coded the Select as below 
`<select asp-for="FinancialStartMonth"  asp-items="Html.GetEnumSelectList<CalendarMonth>()" class="form-control" />`
and the select list (even when populated with correct data refused to show data and it absorbed the next tag as well (even though it was ooutside the current <DIV> block

the only way it work was to close using ></select>

I figured this was a bug? comments?

**Comment by dougbu** [comment]
@grantnilsson this is the current design but we have a few issues (open and closed) on the behaviour:
- aspnet/Mvc#3964
- aspnet/Mvc#4058
- aspnet/Tooling#398

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
