### ISSUE TITLE
Dnx Library Project, How to exclude source code from NuGet package that is produced on build

### ISSUE THREAD

**Issue by dazinator** [aspnet/Home#1303]
I have a dnx based library project.

When it's built, it produces a NuGet package - that't nice.

The NuGet package contains the source code.. That's not so nice for me..

How do I prevent the source code from being included in the NuGet package? I have tried adding this to my project.json file but it doesn't appear to have any effect:

```js
{
 "publishExclude": [ "**/**.cs" ],
"packExclude": ["**/**.cs"]
}

```

**Comment by Eilon** [comment]
Not sure why the CS files would show up there in the first place. But, either way, I recommend using https://github.com/dotnet/cli/ as that's the replacement for DNX, because DNX is going away.

**Comment by dazinator** [comment]
Thanks @Eilon. This turned out to be me being stupid, I had some quirky build logic that was giving me the symbols NuGet package rather than the "normal" NuGet package.. and there was me wondering why source code was always included in it.. that't kind of the purpose of symbols nuget packages! :)

**Comment by dazinator** [comment]
@Eilon  - sorry quick question about this CLI stuff, will their also be a CLI based Visual Studio Project system still, similar to the Dnx based one I use today? For example, I am just interested in creating a VS project, with a project.json and it building to a NuGet package. As I understand it the project systems use Dnx at the present, but when you say Dnx is being superceded by CLI - does this mean the VS project systems will switch over also?

**Comment by Eilon** [comment]
@dazinator xproj and project.json aren't going away, but DNX itself is being replaced by NuGet + dotnet-cli. The next update of VS will have full proper support for this switch.

**Comment by dazinator** [comment]
@Eilon thats great thanks! And a relief!
