### ISSUE TITLE
水一个，等你等的心都碎了

### ISSUE THREAD

**Issue by fej121** [aspnet/Home#1304]
RT

**Comment by BrennanConroy** [comment]
?

**Comment by MaximRouiller** [comment]
Well it did make me laugh.

![image](https://cloud.githubusercontent.com/assets/209384/13080646/9bc69ac8-d497-11e5-9bd1-7e3d300836f6.png)

**Comment by Jeffiy** [comment]
He means that he can't wait for it anymore.
