### ISSUE TITLE
Feature request: allow valid JSON in JSON files. (e.g. project.json)

### ISSUE THREAD

**Issue by 304NotModified** [aspnet/Home#1305]
Project.json is a JSON file (and has a [JSON schema](http://json.schemastore.org/project)). 

There are claims this is a file with JSON content:

> There are two mandatory conditions for a project. The project.json file must contain valid json,

http://docs.asp.net/en/latest/dnx/projects.html

Still, valid JSON with
1. Comments in the form of // ... and /\* ... */
2. Trailing commas after the last member of objects and arrays

will cause issues, as discussed https://github.com/aspnet/Announcements/issues/24 and https://github.com/aspnet/Home/issues/691. 

At least trailing commas are allowed in the JSON specs ([ECMA-404](http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf))

So this is bug - valid JSON should never give issues. You can't name it JSON and then just ignores the specs. 

If this won't be fixed, that it's (IMO) even better to rename the file extension and don't claim this is JSON.

**Comment by Eilon** [comment]
@304NotModified I recommend filing this in https://github.com/dotnet/cli/ and/or https://github.com/NuGet/Home because those are the new places where `project.json` is parsed. DNX is going away so fixing it there won't help much :smile:

**Comment by 304NotModified** [comment]
But this is aspnet home and not dnx? :confused:

In which repository is now the parser code?  Thanks!

**Comment by Eilon** [comment]
There's not gonna be a DNX anymore - it's being replaced by dotnet-cli. There will be no code in ASP.NET that parses `project.json` files - it'll all be either NuGet or dotnet-cli.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
