### ISSUE TITLE
Is there a way to create a class library for .NET Core and the normal .NET

### ISSUE THREAD

**Issue by paule96** [aspnet/Home#1308]
Hi everyone,

I need a way to build a library that I can use in a WPF-Application and in a .NET Core Web-API. Is there any way to do this?

Paule

**Comment by Eilon** [comment]
Sure - create an xproj/project.json, target whichever framework(s) you want, and cross-compile to those frameworks. E.g. target `dnxcore50` and `net451`. In WPF you'd consume the `net451` build, and in .NET Core you'd use the `dnxcore50` target (note that this target is in the process of being changed, but if you use it right now you'll be well-prepared for the future).

**Comment by paule96** [comment]
Okay thx :)
