### ISSUE TITLE
dnu publish to filesystem with web.config in subfolder generates bad paths in web.config

### ISSUE THREAD

**Issue by galmok** [aspnet/Home#1309]
I have a controller created with vs2015 (rc1-final, using rc1-update1 tools), and am trying to make it publish it in a subfolder to wwwroot. I have this used this dnu line:

`dnu publish --out C:\Q --runtime active --no-source --wwwroot wwwroot --iis-command MyService --wwwroot-out wwwroot/MyService`

In project.json, I have changed the default command from web to MyService to avoid conflicts in approot. Once the command has completed, it has created 3 folders in C:\Q, one is wwwroot. In wwwroot, it has created the MyService folder and place a web.config file in it, i.e. wwwroot/MyService/web.config. The content of that web.config is:

```
<configuration>
  <system.webServer>
    <handlers>
      <add name="httpplatformhandler" path="*" verb="*" modules="httpPlatformHandler" resourceType="Unspecified" />
    </handlers>
    <httpPlatform processPath="..\approot\MyService.cmd" arguments="" stdoutLogEnabled="false" stdoutLogFile="..\logs\stdout.log" startupTimeLimit="3600"></httpPlatform>
  </system.webServer>
</configuration>
```

In approot, there is a MyService.cmd file.

The issue is that processPath references MyService.cmd in wwwroot/approot/MyService.cmd as it lacks an additional "..\". The same issue occurs with stdoutLogFile path. Once that is added, the Controller runs. The Controller itself also needs a fix, in that the Route must have MyService prefixed (full url, not relative): 

`[Route("MyService/api/[controller]")]`

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
