### ISSUE TITLE
access to publish temp folder in project.json:postpublish script

### ISSUE THREAD

**Issue by galmok** [aspnet/Home#1310]
Wouldn't it make sense for a postpublish script to have access to the publish folder before it is being deployed?

Currently, only these appear to be defined:

%project:Directory% - The project directory
%project:Name% - The project name
%project:Version% - The project version

**Comment by moozzyk** [comment]
After moving to dotnet you can use [the following variables](https://github.com/dotnet/cli/blob/8645031db8b6a62a10071578f4949b7094293bdc/src/dotnet/commands/dotnet-publish/PublishCommand.cs#L95-L102) in postpublish scripts

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
