### ISSUE TITLE
WEB API - entityframework 6 works locally, but not when deployed.

### ISSUE THREAD

**Issue by Phylum123** [aspnet/Home#1311]
have a Web API I created in ASP 5 MVC 6 (FULL CLR). The web API references a standard .net class library, which has the entity framework 6 NUGET package installed. If I launch the web api locally (IIS express) and then try to run a method which contacts the database, everything works fine.

When I deploy the web API to my DEV server (Windows Server 2012) and try to contact the same method, but on the server, I get the following exception:

{"$id":"1","ClassName":"System.IO.FileNotFoundException","Message":"Could not load file or assembly 'EntityFramework, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies. The system cannot find the file specified.","Data":null,"InnerException":null,"HelpURL":null,"StackTraceString":" at CMAllocation.Web.Data.InvestorRulesRepository..ctor()\r\n at CMAllocation.Web.CMAllocationWebApi.Controllers.InvestorRulesController.GetInvestors() in E:\CMAllocation\WebServices\CMAllocationWebApi\Debug\approot\src\CMAllocation.Web.CMAllocationWebApi\Controllers\InvestorRulesController.cs:line 45","RemoteStackTraceString":null,"RemoteStackIndex":0,"ExceptionMethod":"1\n.ctor\nCMAllocation.Web.Data, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null\nCMAllocation.Web.Data.InvestorRulesRepository\nVoid .ctor()","HResult":-2147024894,"Source":"CMAllocation.Web.Data","WatsonBuckets":null,"FileNotFound_FileName":"EntityFramework, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089","FileNotFound_FusionLog":"WRN: Assembly binding logging is turned OFF.\r\nTo enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog](DWORD) to 1.\r\nNote: There is some performance penalty associated with assembly bind failure logging.\r\nTo turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].\r\n"}

Any help would be appreciated.

**Comment by Eilon** [comment]
@divega @rowanmiller ?

**Comment by rowanmiller** [comment]
My guess is that this is probably related to deploy/publish and possibly a result of the EF6 package not following the standards that most of our new packages do. Can you check if EntityFramework.dll and EntityFramework.SqlServer.dll are being included in the publish output?

**Comment by Phylum123** [comment]
Yes, they are being published. below is an image of the package folder:

![cmallocation_packages](https://cloud.githubusercontent.com/assets/16786358/13224138/26f0ba7c-d955-11e5-8f69-52cd1e9fde56.png)

**Comment by Phylum123** [comment]
NLog may also have the same issue, however it fails in the configure method in Startup.cs, so I can't really see the exception. My nlog.config file is put in the wwwroot (in the project and it deploys to wwwroot on the server), which could also be the problem. Here is the code that fails in the configure method:

            loggerFactory.AddNLog();
            env.ConfigureNLog("nlog.config");

**Comment by Eilon** [comment]
Hmm I wouldn't put a config file in wwwroot. Why isn't it in the app root?

**Comment by Phylum123** [comment]
I tried in the project as well as the wwwroot folder. Neither seemed to work. I abandoned work on it until the entityframework issue was resolved, hoping they were the same issue.

**Comment by Phylum123** [comment]
@divega @rowanmiller ?

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
