### ISSUE TITLE
When is 0 != 0?

### ISSUE THREAD

**Issue by rhires** [aspnet/Home#1314]
This was a subtle problem to work out: (and stripped down for clarity)

```
public class ModelClass
    { 
        int prop1 { get; set; }
        string prop2 { get; set; }
        List<ModelClass> ExistingModel { get; set; }
    }
```

My form (strongly typed):

```
@for (int i = 0; i < Model.ExistingModel.Count; i++) //10 groups of items
{
@if (Model.ExistingModel[i].prop1 != 0) //for this example, let's say half these are 0, the other half are 5
    {    
    @Html.DisplayFor(m => m.ExistingModel[i].prop1)
    @Html.HiddenFor(m => m.ExistingModel[i].prop1) 
    
    @Html.DisplayFor(m => m.ExistingModel[i].prop2)
    @Html.HiddenFor(m => m.ExistingModel[i].prop2)
    }
}
```

My controller:

```
public IActionResult AddModel(ModelClass model)
{
    foreach (item in model.ExistingModel) //model.ExistingModel is empty 
}
```

This code should submit 5 items to the controller, but it doesn't, and leaves my list empty. If I set the condition above to (prop1 != 5), then it will submit 5 items to the controller, and my controller will see the model items I sent from my view. In either case, the view condition does properly only display the items I want to see, and filters out the rest. 

I'm running on Yosemite, 
`dnvm list`  shows 
`*    1.0.0-rc1-final      mono         ~/.dnx/runtimes      default` and I'm happy to provide any other information required...
Edit: also, using EF7 and SQLite.

**Comment by dougbu** [comment]
Do the symptoms occur if you strip EF and SQLite out?

BTW is the generated HTML the same in the two cases (modulo a few attribute values)? Without further information, it's hard to tell if the problem occurs while generating the form or while model binding the submitted response.

**Comment by rhires** [comment]
Hmmm...it seems like model binding because the data is there if I access it through the request: `Request.Form` tells me that it's all there. I changed my runtime and still get the error. I realize I didn't include the stacktrace, so that's below. Html is the same, except that the array starts at a different number, depending on whether I'm checking for zero or not. I have not yet checked to see whether it's EF and/or SQLite, but it doesn't seem like it, since everything else seems to work. Unfortunately I'm unable to debug/step through the code since (as far as I know) debugging on Mac for .NET isn't yet supported by VSCode/Omnisharp. If I'm wrong about that, I'd like to know!


```
InvalidOperationException: Sequence contains no elements

    System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
    WereWolves2.Controllers.Model.Controller.AddModel(ModelClass model)
    --- End of stack trace from previous location where exception was thrown ---
    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    Microsoft.AspNet.Mvc.Controllers.ControllerActionExecutor.ExecuteAsync(MethodInfo actionMethodInfo, Object instance, Object[] orderedActionArguments)
    Microsoft.AspNet.Mvc.Controllers.ControllerActionInvoker.<InvokeActionAsync>d__6.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
    System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    Microsoft.AspNet.Mvc.Controllers.FilterActionInvoker.<InvokeActionFilterAsync>d__53.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
    Microsoft.AspNet.Mvc.Controllers.FilterActionInvoker.<InvokeAsync>d__44.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
    System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    Microsoft.AspNet.Mvc.Infrastructure.MvcRouteHandler.<RouteAsync>d__6.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
    System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    Microsoft.AspNet.Routing.Template.TemplateRoute.<RouteAsync>d__27.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
    System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
    Microsoft.AspNet.Routing.RouteCollection.<RouteAsync>d__9.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
    System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    Microsoft.AspNet.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
    System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    Microsoft.AspNet.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()


```

**Comment by miguellira** [comment]
@rhires From your last post it sounds like you're tripping on this: http://haacked.com/archive/2008/10/23/model-binding-to-a-list.aspx/

You'll need some sort of sequential index.

**Comment by dougbu** [comment]
@rhires it appears @miguellira's response should resolve your concern. Any objection to closing this issue?

**Comment by rhires** [comment]
Yeah, I'm going to attempt to bring the MVC2 (!) solution up to .NET Core and implement it using Tag Helpers ... not sure if/when I get the solution implemented where to share it. But good for closing this for now. Thank you.
