### ISSUE TITLE
Invalid name on package.json (does not pass Regex)

### ISSUE THREAD

**Issue by brunolm** [aspnet/Home#1315]
I created a new project (File > New Project > ...) and by default the package.json came with "ASP.NET" uppercase in the name, but that is invalid, the name should be lowercase

![package.json name](http://i.imgur.com/SG9AG0J.png)

From npm:

> Some rules:
> 
> * The name must be less than or equal to 214 characters. This includes the scope for scoped packages.
> * The name can't start with a dot or an underscore.
> * New packages **must not have uppercase letters in the name**.
> * The name ends up being part of a URL, an argument on the command line, and a folder name. Therefore, the name can't contain any non-URL-safe characters.

**Comment by Eilon** [comment]
I think this is a dup of https://github.com/aspnet/Templates/issues/369

Thanks for the report!
