### ISSUE TITLE
Error: Unable to load application or execute command 'kestrel'. Available commands: web.

### ISSUE THREAD

**Issue by Loongle** [aspnet/Home#1321]
I use the latest version, according to the tutorial

Tutorial url: https://github.com/aspnet/Home/blob/dev/GettingStartedDeb.md

But in "docker run" when met this error:
Error: Unable to load application or execute command 'kestrel'. Available commands: web.

There is no problem "docker builde" process

**Comment by MaximRouiller** [comment]
Obviously the `kestrel` command was discontinued a while ago. The RC1 shouldn't use this command anymore. 

Which version of the docker file are you using?
What's the `project.json` of the application you are trying to deploy on Docker?

Thanks,

**Comment by xielongjiang** [comment]
@MaximRouiller 
I use docker version is 1.10.1
I use projec.json file contents and tutorials provide is the same, is according to the tutorial.Now is the official the Deme

**Comment by xielongjiang** [comment]
@MaximRouiller Sorry,Forget to tell you , I use the Demo version 1.0.0 rc1 -- update1 。
Thanks

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
