### ISSUE TITLE
How do I get the whole route collection in an Action Filter?

### ISSUE THREAD

**Issue by brainwipe** [aspnet/Home#1323]
I am working on a [.NET core implementation](https://github.com/brainwipe/NJsonApi) of the hypermedia [JSONApi ](http://jsonapi.org/) standard. I need to generate the hypermedia links, for which I need the route dictionary (to use old terms). 

A custom `ActionFilterAttribute` is added as a global service, and performs the custom transform on `OnActionExecuted`. I want to hand the custom transformer a route collection so that it can work out the URIs to the actions it needs. These actions could be in other controllers not part of the request.

I believe that this will be done by dependency injecting a service (or Application Model?) into the constructor but I cannot find the relevant service to inject.

How do I get the route collection in the action filter?

Thank you!

**Comment by brainwipe** [comment]
I'm stuck without the route collection. Is it possible to get a hint or a pointer in the right direction?

**Comment by rynowak** [comment]
You can get at the route collection in an action filter through `context.RouteData.Routers[0]`, but I'm not sure that will do what you want. 

If this is for APIs you might want to start by looking at `IApiDescriptionGroupCollectionProvider` in the api explorer package.

**Comment by brainwipe** [comment]
Thank you! I'll get digging.

I very much appreciate the help.

**Comment by rynowak** [comment]
I'm going to close this bug since I answered your original question. If you run into trouble or need more answers please open issues on aspnet/Mvc

**Comment by brainwipe** [comment]
For anyone else stopping by looking for the route collection, thanks to @rynowak I found my answers on this test Mvc Website:

https://github.com/aspnet/Mvc/tree/dev/test/WebSites/ApiExplorerWebSite

The steps are:

- Ensure your API controllers are marked either by `[ApiExplorerSettings(GroupName = "NameOfYourGroup")]` or by making a [convention to register them all](https://github.com/aspnet/Mvc/blob/dev/test/WebSites/ApiExplorerWebSite/ApiExplorerVisibilityEnabledConvention.cs) and adding the convention to your `.AddMvc()` options in Startup.cs.
- In your custom action filter, add `IApiDescriptionGroupCollectionProvider` to your constructor and assign to an internal member variable. 
- That member variable will then contain all the controllers/actions/methods/everything you need inside `ApiDescriptionGroups`.
