### ISSUE TITLE
No response received from API running on DNX RC1-Update1 with Mono on RHEL 7.2

### ISSUE THREAD

**Issue by b-deepak** [aspnet/Home#1324]
Web API hosted in kestrel returns no response on curl. Running on RHEL 7.2 with Mono 4.0.5.

> **dnx --version**
> Microsoft .NET Execution environment
>  Version:      1.0.0-rc1-16231
>  Type:         Mono
>  Architecture: x64
>  OS Name:      Linux
>  OS Version:   rhel 7.2
>  Runtime Id:   rhel.7.2-x64
> 
> **dnu --version**
> Microsoft .NET Development Utility
>  Version:      1.0.0-rc1-16231
>  Type:         Mono
>  Architecture: x64
>  OS Name:      Linux
>  OS Version:   rhel 7.2
>  Runtime Id:   rhel.7.2-x64
> 
> **dnvm --version**
> 1.0.0-rc2-15546
> 
> **mono --version**
> Mono JIT compiler version 4.0.5 (Stable 4.0.5.1/1d8d582 Tue Nov 10 09:40:05 EST 2015)
> Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
>         TLS:           __thread
>         SIGSEGV:       altstack
>         Notifications: epoll
>         Architecture:  amd64
>         Disabled:      none
>         Misc:          softdebug
>         LLVM:          supported, not enabled.
>         GC:            sgen

After setting DNX_TRACE=1, I see the following output for a curl request 

> 'curl -X GET http://localhost:8080/customers/contact/1'
> 
> 2016-02-24 10:13:43 [Information] Started processing Http request to URL: "/customers/contact/1"
> 2016-02-24 10:13:43 [Information] Executing in .NetFramework/Mono runtime
> Information: [LoaderContainer]: Load name=Microsoft.AspNet.WebUtilities, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
> Information: [PackageAssemblyLoader]: Loaded name=Microsoft.AspNet.WebUtilities, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60 in 0ms
> Information: [LoaderContainer]: Load name=System.Interactive.Async, Version=1.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
> Information: [PackageAssemblyLoader]: Loaded name=System.Interactive.Async, Version=1.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 in 0ms

That's it..no response! Appreciate any help!

**Comment by davidfowl** [comment]
Mono isn't supported. There have been various issues with mono issues mostly hangs like this one.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
