### ISSUE TITLE
QUESTION: Migration path from Owin to ASP.NET core

### ISSUE THREAD

**Issue by kasajian** [aspnet/Home#1325]
Is there a good guide on how to take an existing self-hosted Owin app that runs only on Windows and migrate it over to asp.net core?

Our application is currently relying on the following components:
```Microsoft.Owin.3.0.1\lib\net45\Microsoft.Owin.dll
Microsoft.Owin.FileSystems.3.0.1\lib\net45\Microsoft.Owin.FileSystems.dll
Microsoft.Owin.Host.HttpListener.3.0.1\lib\net45\Microsoft.Owin.Host.HttpListener.dll
Microsoft.Owin.Hosting.3.0.1\lib\net45\Microsoft.Owin.Hosting.dll
Microsoft.Owin.StaticFiles.3.0.1\lib\net45\Microsoft.Owin.StaticFiles.dll
Owin.1.0\lib\net40\Owin.dll
Owin.WebSocket.1.5.0\lib\net45\Owin.WebSocket.dll
```

**Comment by davidfowl** [comment]
We don't have a formal guide but the names are pretty close:

```
Microsoft.Owin.FileSystems -> Microsoft.Extensions.FileProviders
Microsoft.Owin.Host.HttpListener -> Microsoft.AspNetCore.Server.WebListener OR Microsoft.AspNetCore.Server.Kestrel
Microsoft.Owin.Hosting -> Microsoft.AspNetCore.Hosting
Owin.WebSocket -> Microsoft.AspNetCore.WebSockets.Server
```

/cc @danroth27 @Tratcher

**Comment by kasajian** [comment]
thank you

**Comment by Tratcher** [comment]
http://katanaproject.codeplex.com/wikipage?title=roadmap&referringTitle=Home

**Comment by smarts** [comment]
Is there any blog post that explains the relationship between ASP.NET Core and OWIN? Is Core built on top of OWIN, or is Core meant to replace OWIN?

**Comment by davidfowl** [comment]
https://blogs.msdn.microsoft.com/webdev/2014/11/14/katana-asp-net-5-and-bridging-the-gap/

**Comment by danroth27** [comment]
https://docs.asp.net/en/latest/fundamentals/owin.html

**Comment by kasajian** [comment]
I think this is sufficient information.   Thank you very much to everyone.
