### ISSUE TITLE
Trouble Registering an ASP.NET Core Console App as a Global Command When Using Project-Level References

### ISSUE THREAD

**Issue by mylifeandcode** [aspnet/Home#1327]
Hi! I've run into a situation when trying to register an ASP.NET Core Console Application as a global command.

First I run the following commands:
**dnu build
dnu pack
dnu publish**

This works without a problem. 

Then I try to register the application as a global command via either of the following:
**dnu commands install (package filename)**
or
**dnu commands install (package name) --source (feed)**

However, both of these attempts fail because my project references 2 other projects in the same solution, and when I attempt to register the application as a command it attempts to download those other projects as if they were NuGet packages. But they're not -- they're simply 2 class library projects that exist in the same solution as my console application and are referenced by it.

Is there a way I can register my console application as a global command without the need to package up the 2 projects it references as NuGet packages and place them in an internal NuGet feed? Thanks in advance for the help!

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
