### ISSUE TITLE
RC2: invalid ApplicationBasePath when target net451

### ISSUE THREAD

**Issue by anfomin** [aspnet/Home#1329]
I've upgraded to latest RC2 bits from MyGet/aspnetvnext and using dotnet CLI.

Startup.cs:

``` C#
public class Startup
{
    public Startup(IApplicationEnvironment appEnv, IHostingEnvironment env)
    {
        Console.WriteLine("Applicaiton base path: " + appEnv.ApplicationBasePath);
    }

    public void ConfigureServices(IServiceCollection services)
    {
    }

    public void Configure(IApplicationBuilder app)
    {
        app.UseDeveloperExceptionPage();
        app.UseWelcomePage();
    }

    public static void Main(string[] args)
    {
        var application = new WebHostBuilder()
            .UseDefaultConfiguration(args)
            .UseIISPlatformHandlerUrl()
            .UseServer("Microsoft.AspNetCore.Server.Kestrel")
            .UseStartup<Startup>()
            .Build();
        application.Run();
    }
}
```

`IApplicationEnvironment.ApplicationBasePath` contains invalid path when I target net451:
![2016-02-26 17 56 28](https://cloud.githubusercontent.com/assets/1905503/13352893/499ef0c4-dcb2-11e5-884e-c5c3d0327253.png)

It should be `C:\Developer\WebApplication1\src\WebApplication1\`.

**Comment by anfomin** [comment]
I took a glance at HelloMVC sample here: https://github.com/aspnet/cli-samples/tree/master/HelloMvc

There is `content` section in project.json so all views are copied to `bin\...\Views` on `dotnet build`. Then `ApplicationBasePath` is correct and Razor works.

Will VS2015 tools rebuild project on every change to copy my views to this temp directory?

**Comment by moozzyk** [comment]
I believe the content section is for publish. This line https://github.com/aspnet/cli-samples/blob/master/HelloMvc/Program.cs#L13 should make it possible to use views without having to copy them to bin.

**Comment by anfomin** [comment]
@moozzyk I've missed this line :disappointed: . May be this should be the default behavior?

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
