### ISSUE TITLE
Nuget Packaging - importing content files to dnx proj (xproj)

### ISSUE THREAD

**Issue by vijaynrm** [aspnet/Home#1332]
I am trying to package .net library to Nuget and use it asp.net 5 web project (dnx). I am able to get the content files into the nuget package, but not able to get it imported to web project. I tried different options are content & contentFiles folder, nuspec etc. didn't work.. not sure if I am missing something.. any help on this much appreciated. 

I need to copy/import few .json files from my package to the asp.net web project.

**Comment by MaximRouiller** [comment]
Not supported.

nupkg are now for assemblies. If you need to move content files around, you have to find another way.

At least that's what I heard and unless they bring this back somehow... it's not going to change soon.

**Comment by michaelherndon** [comment]
http://blog.nuget.org/20160126/nuget-contentFiles-demystified.html

Look like this is being addressed.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
