### ISSUE TITLE
Dnx project start up error - dnx design time process. No connection could be made

### ISSUE THREAD

**Issue by ar27111994** [aspnet/Home#1335]
![dnx error](https://cloud.githubusercontent.com/assets/13036687/13398848/10704d6c-df22-11e5-9442-61e22d6de245.PNG)

Ok i've tried everything including:
- **dnvm upgrade** or  **dnvm update-self**
- Repaired Asp.Net 5 RC1 Update 1
- Deleted all nuget packages from .dnx folder.

But all invain. Although initially **dnvm upgrade** and **dnvm update-self** worked temporarily but after they lost their effectiveness, I tried the other two options but they also didn't work. Is their a genuine fix for this or Should I revert to previous versions for my current web app. Please help!

P.S. I really want to use cross platform capabilities on my ubuntu & VS code.

**Comment by MaximRouiller** [comment]
Could you please give us a screenshot/stack trace/complete error message?

**Comment by ar27111994** [comment]
Updated @MaximRouiller (see above) Thanks!

**Comment by ar27111994** [comment]
Ok, After changing **global.json** from:
```
{
  "projects": [ "src", "test" ],
  "sdk": {
    "version": "1.0.0-rc1-update1"
  }
}
```

to:

```
{
  "projects": [ "src", "test" ],
  "sdk": {
    "architecture": "x64",
    "runtime": "coreclr",
    "version": "1.0.0-rc1-update1"
  }
}
```
vs project opens perfectly well.

P.S.:- I've only opened the project a couple of times.

**Comment by ar27111994** [comment]
3rd time no luck :'(

**Comment by ar27111994** [comment]
Hello Anyone here?! @MaximRouiller @davidfowl  @BillHiebert

**Comment by MaximRouiller** [comment]
We are here. Still thinking.

**Comment by ar27111994** [comment]
@MaximRouiller Any solution yet? :'(

**Comment by MaximRouiller** [comment]
Have you tried clearing your `.dnx` folder and reinstalling it? 

What about repairing your WebTools installation?

What else have you tried?

**Comment by ar27111994** [comment]
i've tried the following:

•dnvm upgrade or dnvm update-self


•Repaired Asp.Net 5 RC1 Update 1(Web Tools?)



•Deleted all packages from .dnx folder.
Right now re-install dnx as per your advice.

**Comment by ar27111994** [comment]
Re-installing dnx and web tooling repair also didn't work. @MaximRouiller

**Comment by ar27111994** [comment]
Any Luck?! @MaximRouiller @davidfowl @BillHiebert

**Comment by MaximRouiller** [comment]
No luck on my end. I would rely on the team to help debug this. I haven't encountered this issue nor have been able to reproduce.

**Comment by ar27111994** [comment]
Argh! Its annoying as I've to restart Visual Studio every time. But, thank god that the error now disappears after restarting visual studio.

**Comment by ar27111994** [comment]
Occurs in .Net Core preview 1.0.0 too. Just for the info.
