### ISSUE TITLE
HttpPlatformHandler logging error when hosting on IIS

### ISSUE THREAD

**Issue by stephenstroud** [aspnet/Home#1336]
I've updated to ASPNETCORE from aspnet and no logs are occurring and can't get the project hosted on IIS, if I roll back to aspnet project the logs write successfully and the app runs fine.  I've repaired HttpPlatformHandler but no luck. The eventviewer gives me this.

The following information was included with the event: 

The description for Event ID 1004 from source HttpPlatformHandler cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.

If the event originated on another computer, the display information had to be saved with the event.

Warning: Could not create stdoutLogFile \\?\C:\inetpub\logs\stdout.log_4668_201631164353.log, ErrorCode = -2147024891.

**Comment by moozzyk** [comment]
Can you show your web.config file?

**Comment by stephenstroud** [comment]
Figured it out, I was missing       .UseIISPlatformHandlerUrl(), however, under ASPNET was working fine.

   public static void Main(string[] args)
        {
            var application = new WebHostBuilder()
                .UseDefaultConfiguration(args)
                .UseIISPlatformHandlerUrl()                 
                 .UseStartup<Startup>()
               .Build();

            application.Run();
        }

Thanks!
