### ISSUE TITLE
Can't find correct dependency for XmlSerializer and dnx451

### ISSUE THREAD

**Issue by skyflyer** [aspnet/Home#1337]
Using VS2015 with ASP.NET RC1 Update 1. Create a simple ASP.NET 5 Console project and try to use `XmlSerializer`. I fail to find the right combination of dependencies to resolve this matter. Visual Studio offers dependency `"System.Xml.XmlSerializer": "4.0.11-beta-23516"`, which does not help with building the project. The project file:

```
{
  "version": "1.0.0-*",
  "description": "Useit Console Application",
  "authors": [ "miha" ],
  "tags": [ "" ],
  "projectUrl": "",
  "licenseUrl": "",

  "compilationOptions": {
    "emitEntryPoint": true
  },

  "dependencies": {
    "System.Xml.XmlSerializer": "4.0.11-beta-23516"
  },

  "commands": {
    "Useit": "Useit"
  },

  "frameworks": {
    "dnx451": {
      "dependencies": {
      },
      "frameworkAssemblies": {
      }
    },

  }
}
```

There are several error messages:

```
1>C:\work\vnext\Useit\src\Useit\Program.cs(15,21,15,32): DNX 4.5.1 error CS0246: The type or namespace name 'ElementName'
1> could not be found (are you missing a using directive or an assembly reference?)
1>C:\work\vnext\Useit\src\Useit\Program.cs(23,38,23,51): DNX 4.5.1 error CS0246: The type or namespace name 'XmlSerialize
1>r' could not be found (are you missing a using directive or an assembly reference?)
```

I've noticed, that I can compile it OK if I add framework assemblies, so the question is: which is the right way to go? Adding framework assemblies or adding specific assemblies for that VS/Nuget recommend?

In the near future, I'd like to support `dnxcore50` framework, but one step at a time.

For reference, a working `project.json`:

```
{
  "version": "1.0.0-*",
  "description": "Useit Console Application",
  "authors": [ "miha" ],
  "tags": [ "" ],
  "projectUrl": "",
  "licenseUrl": "",

  "compilationOptions": {
    "emitEntryPoint": true
  },

  "commands": {
    "Useit": "Useit"
  },

  "frameworks": {
    "dnx451": {
      "frameworkAssemblies": {
        "System.Xml":  "4.0.0.0",
        "System.Xml.Serialization": "4.0.0.0"
      }
    }
  }
}
```

**Comment by Eilon** [comment]
@ericstj ?

**Comment by ericstj** [comment]
`frameworkAssemblies` is correct for desktop based frameworks like DNX when you are trying to use API that is in the framework.

**Comment by skyflyer** [comment]
So I guess this is a tooling issue at the moment (since VS2015 suggests a Nuget package System.Xml.XmlSerializer version 4.0.11-beta-23516)?

Feel free to close this issue if this is "by design".

**Comment by skyflyer** [comment]
Closing as it is not relevant anymore.
