### ISSUE TITLE
StreamSocketListener-based Server

### ISSUE THREAD

**Issue by bricelam** [aspnet/Home#1338]
I know we have WebListener which appears to work fine on Windows IoT Core (see [DamianEdwards/PiDnx](https://github.com/DamianEdwards/PiDnx)), but would there be any value in having a server implemented over the top of WinRT's [Windows.Networking.Sockets.StreamSocketListener](https://msdn.microsoft.com/en-us/library/windows/apps/windows.networking.sockets.streamsocketlistener.aspx) API?

Will WebListener work work in a [Windows IoT Core Background Application](https://visualstudiogallery.msdn.microsoft.com/55b357e1-a533-43ad-82a5-a88ac4b01dec) project?

cc @DamianEdwards @Tratcher

**Comment by Tratcher** [comment]
No idea on either account. Could make for some interesting experiments.

**Comment by moozzyk** [comment]
Weblistener actually does not really work on Windows IoT Core. After handling a few requests (I think it was 6 or so) no more requests are being handled...

**Comment by DamianEdwards** [comment]
Kestrel works on Windows IoT Core as we now include a version of libuv compiled for Windows OneCore ARM.

We haven't locked down the plan for 1.0 RTM but we're still hoping to get a non-supported build of the .NET Core CLI & redist made for Windows 10 IoT Core in that timeframe to enable interested parties to hack away. Kestrel should work fine for that.

**Comment by DamianEdwards** [comment]
Oh btw that, that template you link to is for a C# UWP app, which ASP.NET Core doesn't work in right now, as we need stuff not available in the UWP sandbox.

**Comment by stefan2410** [comment]
Is there any plan / road map to self host an asp.net core API with kestrel in UWP Apps ?
If not we will go the other way like  GitHub desktop and/or React Native.
UWP, Edge, Store  excluded.

**Comment by Tratcher** [comment]
There has been some talk of making WebListener work in UWP, but that's blocked at the moment.

**Comment by JeffMarqMetrix** [comment]
Vote for it...
[https://aspnet.uservoice.com/forums/41199-general-asp-net/suggestions/32626766-support-for-asp-net-core-running-on-uwp-as-windows](https://aspnet.uservoice.com/forums/41199-general-asp-net/suggestions/32626766-support-for-asp-net-core-running-on-uwp-as-windows)

**Comment by Eilon** [comment]
@muratg / @davidfowl - any idea where this issue should go? Close it?

**Comment by davidfowl** [comment]
Close it. We have no plans to write another webserver.
