### ISSUE TITLE
ASPNETCORE update issue from ASPNET

### ISSUE THREAD

**Issue by stephenstroud** [aspnet/Home#1339]
I'm getting a MissingMethodExpection thrown on the latest libraries when adding Services.AddMVC()

An exception of type 'System.MissingMethodException' occurred in Microsoft.AspNetCore.Mvc.ViewFeatures.dll but was not handled in user code

Method not found: 'Microsoft.Extensions.DependencyInjection.IServiceCollection Microsoft.Extensions.DependencyInjection.EncoderServiceCollectionExtensions.AddWebEncoders(Microsoft.Extensions.DependencyInjection.IServiceCollection)'."}

Using  "Microsoft.AspNetCore.Mvc": "1.0.0-17116"

Having a dependency on ViewFeatures 1.0.0.rc2-17116

**Comment by MaximRouiller** [comment]
Is is related to aspnet/Announcements/issues/154?

**Comment by stephenstroud** [comment]
@MaximRouiller Amazing - This fixed it. Thank you!

**Comment by MaximRouiller** [comment]
My pleasure. I love fixing bugs without opening an IDE. :+1:
