### ISSUE TITLE
Upgrading dependencies (from beta3)

### ISSUE THREAD

**Issue by wisien92** [aspnet/Home#1340]
I did not update my vNext application in a while ... and now I have huge problem with using some functionalities.

What should I add in project.json or what usings to use:

-Timers
- SslStream (with RemoteCertificateValidationCallback)
-  [Serializable]
- AesManaged

There have been so many changes in rc1-final that it's giving me a headache.

**Comment by MaximRouiller** [comment]
If you are starting from `beta3`, I would highly recommend starting from the new templates and just importing your code and fixing it as you go along. 

You are 6-ish release behind. 

Here are the breaking changes for you:

* [Beta3 -> Beta4 (11 breaking changes)](https://github.com/aspnet/Announcements/issues?q=is%3Aopen+label%3A%22Breaking+change%22+milestone%3A1.0.0-beta4)
* [Beta4 -> Beta5 (18 breaking changes)](https://github.com/aspnet/Announcements/issues?q=is%3Aopen+label%3A%22Breaking+change%22+milestone%3A1.0.0-beta5)
* [Beta5 -> Beta6 (5 breaking changes)](https://github.com/aspnet/Announcements/issues?q=is%3Aopen+label%3A%22Breaking+change%22+milestone%3A1.0.0-beta6)
* [Beta6 -> Beta7 (10 breaking changes)](https://github.com/aspnet/Announcements/issues?q=is%3Aopen+label%3A%22Breaking+change%22+milestone%3A1.0.0-beta7)
* [Beta7 -> Beta8 (15 breaking changes)](https://github.com/aspnet/Announcements/issues?q=is%3Aopen+label%3A%22Breaking+change%22+milestone%3A1.0.0-beta8)
* [Beta8 -> RC1 (18 breaking changes)](https://github.com/aspnet/Announcements/issues?q=is%3Aopen+label%3A%22Breaking+change%22+milestone%3A1.0.0-rc1)

And here is what you'll need to fix once RC2 is launched.

* [RC1 -> RC2 (31 breaking changes)](https://github.com/aspnet/Announcements/issues?q=is%3Aopen+label%3A%22Breaking+change%22+milestone%3A1.0.0-rc2)

There's no manual. It's the cost of working with beta sadly. :disappointed:

**Comment by wisien92** [comment]
Ok - but now thank's to you I'll know what has changed and where to look for solution. :)

I didn't know that there was RC2 but first I'll do changes up to RC1 then probably up to RC2.

**Comment by wisien92** [comment]
I'll reopen if there will be more questions/issues regarding this topic.
