### ISSUE TITLE
Package Restore

### ISSUE THREAD

**Issue by chrisbradburyUP** [aspnet/Home#1341]
Updated to the ASPNET Core and since updating, cannot resolve any dependancies as package restore is failing by ID. 

Tried via Visual Studio, and also via 'dotnet restore' from the command line. Both ways, it doesn't seem to be able to connect to server. 

If I go to the links directly, it does download without any problem.

**Comment by Eilon** [comment]
Which version of everything are you using? What's the error?

**Comment by chrisbradburyUP** [comment]
Resolved the issue by deleting the NuGet.config file from ..\AppData\Roaming\NuGet and also clearing all of the data from ..\AppData\Local\Microsoft\VisualStudio
