### ISSUE TITLE
HTTP Error 400. The size of the request headers is too long.

### ISSUE THREAD

**Issue by henkmollema** [aspnet/Home#1342]
I encounter this error when sending fairly large JSON Web Tokens through HTTP headers:
> HTTP Error 400. The size of the request headers is too long.

 I tried configuring the header limit in the `web.config`, without luck:
```xml
<security>
  <requestFiltering>
    <requestLimits maxAllowedContentLength="1073741824">
      <headerLimits>
        <add header="X-My-Header" sizeLimit="1073741824" />
      </headerLimits>
    </requestLimits>
  </requestFiltering>
</security>
```

The application is in fact a Web API and I am using CORS.

Is there any other way to configure the limits? I'm open for another solution of sending those headers too.

Environment:
- DNX: v1.0.0-rc1-update1
- Server: Kestrel v1.0.0-rc1-final
- Running environment: Development
- Dev server: IIS Express

**Comment by Eilon** [comment]
@Tratcher ?

**Comment by Tratcher** [comment]
http://stackoverflow.com/questions/35749180/do-web-config-header-size-limits-override-http-sys-limits-in-the-registry

**Comment by henkmollema** [comment]
So every developer has to configure this on their machine..

Does Linux have similar issues?

**Comment by Tratcher** [comment]
This is an IIS/Express/Http.Sys configuration issue. Kestrel itself does not have this setting (yet). I don't know about similar settings on Linux, it depends on the server.

I will say that this is not a commonly reported issue. Why are your JWTs so large? You may need to re-evaluate them.

**Comment by sandersaares** [comment]
Many web servers have a fixed-size buffer that everything up to and including the double-newline signaling end of HTTP headers must fit into. I assume you are running into this limit. I would suggest you keep the total size of your headers to below 8 KB to work well with most web servers.

Putting more data into HTTP headers would be quite a questionable design decision with regard to whatever app you are developing. Possibly the request body is a more suitable place for large amounts of data.

**Comment by henkmollema** [comment]
I am building some kind of wizard form where I persist the user input in an JWT across the steps of the wizard. It acts as a 'stateless' replacement for session state. In the meantime I've managed to slim down the size a fair amount and I might move it to the request body when it causes trouble again.
