### ISSUE TITLE
SerialPort cannot receive anything

### ISSUE THREAD

**Issue by derwish-pro** [aspnet/Home#1343]
I use SerialPort class from the System.IO.Ports in the web server. Everything works fine under Windows. But there is a problem under Linux. SerialPort works only for transmission, but cannot receive anything. DataReceived event is not called.

**Comment by Eilon** [comment]
@derwish-pro for issues with System.IO.Ports please file an issue here: https://github.com/dotnet/corefx/issues

Thanks!
