### ISSUE TITLE
Could not get remote ip address in RC1 on Windows 7

### ISSUE THREAD

**Issue by HalfLegend** [aspnet/Home#1347]
the Connection property in HttpContext is null and if I try to get the IHttpConnectionFeature, it will return null on Windows 7.
I tried the same thing on Windows 10, and it is working fine, but the remote ip address is IPv6, which I don't want it to be like this.
I also tried it on RC2, and the ip address is correctly returned. Since there is still a lot of bugs in RC2, I have to use RC1.
Please solve the bug as soon as possible. I have stucked in the issue for a long time.

**Comment by Tratcher** [comment]
You are using IIS (HttpPlatformHandler) & Kestrel, correct? Yes there was a known issue in RC1 where it failed if the forwarded header included the remote port.  https://github.com/aspnet/IISIntegration/issues/17#issuecomment-148868528. This has been fixed in RC2.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
