### ISSUE TITLE
Using WebImage in asp.net core razor mvc

### ISSUE THREAD

**Issue by jannavarro** [aspnet/Home#1351]
Sorry for posting a question here but I cannot seem to get an answer in [SO](http://stackoverflow.com/questions/35532913/using-webimage-in-asp-net-core-razor-mvc) so I am duplicating the question here in case someone can help me find the right direction.

I'm following this [sample](http://www.asp.net/web-pages/overview/ui-layouts-and-themes/9-working-with-images) for working with WebImage. However I'm using asp-net core mvc in vs code.

Since there is no System.Web.Helpers where should I reference WebImage from? I tried searching and there are no explanation in aspnet mvc github wiki.

**Comment by Eilon** [comment]
The WebImage library was designed to be used with ASP.NET 4.x, and not with ASP.NET Core. You *might* be able to add a reference to the System.Web.Helpers NuGet package if your web project targets `dnx451`, and the code might work, but there's no guarantee.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.

**Comment by MaqSaid** [comment]
I am getting the same issue. Do we have better way of handing image upload from a mobile device.
