### ISSUE TITLE
No service for type 'Microsoft.Extensions.PlatformAbstractions.IApplicationEnvironment

### ISSUE THREAD

**Issue by vintem** [aspnet/Home#1352]
Hi, I'm trying a new mvc application that I generated using yeoman

When I run dotnet restore I have the following errors:

log  : Restoring packages for C:\Users\vintem\Documents\projects\TestMvc6\project.json...
error: Unable to resolve Microsoft.AspNet.Diagnostics (>= 1.0.0-rc1) for DNX,Version=v4.5.1.
error: Unable to resolve Microsoft.AspNet.IISPlatformHandler (>= 1.0.0-rc1) for DNX,Version=v4.5.1.
error: Unable to resolve Microsoft.AspNet.Mvc (>= 6.0.0-rc1) for DNX,Version=v4.5.1.
error: Unable to resolve Microsoft.AspNet.Mvc.TagHelpers (>= 6.0.0-rc1) for DNX,Version=v4.5.1.
error: Unable to resolve Microsoft.AspNet.Server.Kestrel (>= 1.0.0-rc1) for DNX,Version=v4.5.1.
error: Unable to resolve Microsoft.AspNet.StaticFiles (>= 1.0.0-rc1) for DNX,Version=v4.5.1.
error: Unable to resolve Microsoft.AspNet.Tooling.Razor (>= 1.0.0-rc1) for DNX,Version=v4.5.1.
error: Unable to resolve Microsoft.Extensions.Configuration.FileProviderExtensions (>= 1.0.0-rc1) for DNX,Version=v4.5.1.
error: Unable to resolve Microsoft.Extensions.Configuration.Json (>= 1.0.0-rc1) for DNX,Version=v4.5.1.
error: Unable to resolve Microsoft.Extensions.Logging (>= 1.0.0-rc1) for DNX,Version=v4.5.1.
error: Unable to resolve Microsoft.Extensions.Logging.Console (>= 1.0.0-rc1) for DNX,Version=v4.5.1.
error: Unable to resolve Microsoft.Extensions.Logging.Debug (>= 1.0.0-rc1) for DNX,Version=v4.5.1.
info : Committing restore...
log  : Restore failed in 296ms.

Errors in C:\Users\vintem\Documents\projects\TestMvc6\project.json
    Unable to resolve Microsoft.AspNet.Diagnostics (>= 1.0.0-rc1) for DNX,Version=v4.5.1.
    Unable to resolve Microsoft.AspNet.IISPlatformHandler (>= 1.0.0-rc1) for DNX,Version=v4.5.1.
    Unable to resolve Microsoft.AspNet.Mvc (>= 6.0.0-rc1) for DNX,Version=v4.5.1.
    Unable to resolve Microsoft.AspNet.Mvc.TagHelpers (>= 6.0.0-rc1) for DNX,Version=v4.5.1.
    Unable to resolve Microsoft.AspNet.Server.Kestrel (>= 1.0.0-rc1) for DNX,Version=v4.5.1.
    Unable to resolve Microsoft.AspNet.StaticFiles (>= 1.0.0-rc1) for DNX,Version=v4.5.1.
    Unable to resolve Microsoft.AspNet.Tooling.Razor (>= 1.0.0-rc1) for DNX,Version=v4.5.1.
    Unable to resolve Microsoft.Extensions.Configuration.FileProviderExtensions (>= 1.0.0-rc1) for DNX,Version=v4.5.1.
    Unable to resolve Microsoft.Extensions.Configuration.Json (>= 1.0.0-rc1) for DNX,Version=v4.5.1.
    Unable to resolve Microsoft.Extensions.Logging (>= 1.0.0-rc1) for DNX,Version=v4.5.1.
    Unable to resolve Microsoft.Extensions.Logging.Console (>= 1.0.0-rc1) for DNX,Version=v4.5.1.
    Unable to resolve Microsoft.Extensions.Logging.Debug (>= 1.0.0-rc1) for DNX,Version=v4.5.1.

NuGet Config files used:
    C:\Users\vintem\AppData\Roaming\NuGet\NuGet.Config

But when I open the application using Visual Studio Code, it is able to restore the packages.

After the packages are restored using Code, I ran dotnet run and got the following error: 

Unhandled Exception: System.InvalidOperationException: No service for type 'Microsoft.Extensions.PlatformAbstractions.IApplicationEnvironment' has been registered.
   at Microsoft.Extensions.DependencyInjection.ServiceProviderExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.AspNet.Hosting.WebHostBuilder.Build()
   at Microsoft.AspNet.Hosting.WebApplication.Run(Type startupType, String[] args)
   at TestMvc6.Startup.Main(String[] args) in C:\Users\vintem\Documents\projects\TestMvc6\Startup.cs:line 61

I'm using:
.NET Version Manager v1.0.0-rc2-15546
1.0.0-rc2-16595   clr     x86          win
.NET Command Line Tools (1.0.0-beta-001598)

Any help?
Thanks

**Comment by victorhurdugaci** [comment]
1. What feeds do you have in `NuGet.config`?
2. What's in your `project.json` file?

**Comment by vintem** [comment]
This is my project.json file:

```
{
  "version": "1.0.0-*",
  "compilationOptions": {
    "emitEntryPoint": true
  },
  "tooling": {
    "defaultNamespace": "TestMvc6"
  },

  "dependencies": {
    "Microsoft.AspNet.Diagnostics": "1.0.0-rc1",
    "Microsoft.AspNet.IISPlatformHandler": "1.0.0-rc1",
    "Microsoft.AspNet.Mvc": "6.0.0-rc1",
    "Microsoft.AspNet.Mvc.TagHelpers": "6.0.0-rc1",
    "Microsoft.AspNet.Server.Kestrel": "1.0.0-rc1",
    "Microsoft.AspNet.StaticFiles": "1.0.0-rc1",
    "Microsoft.AspNet.Tooling.Razor": "1.0.0-rc1",
    "Microsoft.Extensions.Configuration.FileProviderExtensions" : "1.0.0-rc1",
    "Microsoft.Extensions.Configuration.Json": "1.0.0-rc1",
    "Microsoft.Extensions.Logging": "1.0.0-rc1",
    "Microsoft.Extensions.Logging.Console": "1.0.0-rc1",
    "Microsoft.Extensions.Logging.Debug": "1.0.0-rc1"
  },

  "commands": {
    "web": "Microsoft.AspNet.Server.Kestrel"
  },

  "frameworks": {
    "dnx451": {}
  },

  "exclude": [
    "wwwroot",
    "node_modules"
  ],
  "publishExclude": [
    "node_modules",
    "**.xproj",
    "**.user",
    "**.vspscc"
  ],
  "scripts": {
    "prepublish": [
      "npm install",
      "bower install",
      "gulp clean",
      "gulp min"
    ]
  }
}
```

And this is the Nuget.config that is in my AppData\Roaming\Nuget

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <activePackageSource>
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" />
  </activePackageSource>
</configuration>
```

**Comment by GuardRex** [comment]
@vintem Change your package references to `1.0.0-rc1-final`

**Comment by vintem** [comment]
@GuardRex they were like this before, and it didn't work either.

**Comment by GuardRex** [comment]
The runtime should also be on-par with an rc1 project, so I suggest ... `dnx-clr-win-x86.1.0.0-rc1-update1`.

Regarding the use of `dotnet cli`, use `dnu restore` for an rc1 project. `dotnet restore` is an rc2 thing.

**Comment by vintem** [comment]
The runtime I'm using is:
1.0.0-rc1-update1 clr     x86          win

I ran dnu restore then dnx run and I got the following error:

```
System.InvalidOperationException: IHostingBuilder.UseServer() is required for Start()
   at Microsoft.AspNet.Hosting.Internal.HostingEngine.EnsureServer()
   at Microsoft.AspNet.Hosting.Internal.HostingEngine.BuildApplication()
   at Microsoft.AspNet.Hosting.Internal.HostingEngine.Start()
   at Microsoft.AspNet.Hosting.WebApplication.Run(Type startupType, String[] args)
   at Microsoft.AspNet.Hosting.WebApplication.Run[TStartup](String[] args)
   at TestMvc6.Startup.Main(String[] args) in C:\Users\vintem\Documents\projects\TestMvc6\Startup.cs:line 61
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Dnx.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider serviceProvider)
   at Microsoft.Dnx.ApplicationHost.Program.<>c__DisplayClass3_0.<ExecuteMain>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
```

**Comment by GuardRex** [comment]
@vintem Well, progress, right? :smile:

mmm ... `.UseServer()` is also for rc2. @victorhurdugaci correct me if I'm wrong, I think that came along in rc2 even after we were using `.UseServerFactory(...)` in rc2.

I'd suggest you start by clearing the package cache (.dnx packages folder and any packages cached in the project). Restore the project again fresh, which will pull them back down from the feeds. ... and speaking of feeds, I always had the Nuget.org feed as you have, but I also had the vNext one in my rc1-final days ...
```
<add key="AspNetvNext" value="https://www.myget.org/F/aspnetvnext/api/v3/index.json" />
```
... it might not matter, but it is a difference between some older projects I have here and your project.

**Comment by davidfowl** [comment]
Hold on, if we're talking about using released stable rc1 bits then there's no reason to add a feed. Everything is on nuget.org.

**Comment by GuardRex** [comment]
@davidfowl ... fair enough. I was just identifying a delta between his proj and one of my old ones that had both.

**Comment by vintem** [comment]
@GuardRex I've cleaned the packages folder, and my bin/obj folders also removed the .lock.json file and it still doesn't work.

I'm trying to find something on the releases about the startup file specifically but could not find anything.

**Comment by GuardRex** [comment]
@vintem It would still be documented in the official docs for "latest," since that's still the latest stable release. You should see good startup info at ... https://docs.asp.net/en/latest/fundamentals/startup.html?highlight=startup#the-startup-class ... and ... https://github.com/aspnet/Home/blob/dev/samples/1.0.0-rc1-final/HelloMvc/Startup.cs

**Comment by vintem** [comment]
I don't think it's the Startup. I've just created a Mvc6 App using Visual Studio Community Edition and the application works if I start it using VS.

If I try to start the same application using dnx I got the same error as before.

**Comment by Tratcher** [comment]
Note your `UseServer` error is cause by calling `dnx run` when you should call `dnx web` instead.

**Comment by vintem** [comment]
@Tratcher when I run dnx web this is the error I have in response

λ dnx web
System.MissingMethodException: Method not found: 'Microsoft.Extensions.PlatformAbstractions.IAssemblyLoadContextAccessor Microsoft.Extensions.PlatformAbstractions.PlatformServices.get_AssemblyLoadContextAccessor()'.
   at Microsoft.AspNet.Hosting.WebHostBuilder.BuildHostingServices()
   at Microsoft.AspNet.Hosting.WebHostBuilder.Build()
   at Microsoft.AspNet.Hosting.WebApplication.Run(Type startupType, String[] args)
   at Microsoft.AspNet.Server.Kestrel.Program.Main(String[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Dnx.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider serviceProvider)
   at Microsoft.Dnx.ApplicationHost.Program.<>c__DisplayClass3_0.<ExecuteMain>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

**Comment by Tratcher** [comment]
If it works in VS and fails on the command line then you most likely have a different DNX selected on the command line. VS uses the DNX specified in the global.json, console does not. Try `dnvm list` to verify what dnx is active (`*`).

**Comment by tidyui** [comment]
I'm getting this same error on OSX after upgrading to runtime `1.0.0-rc2-20221`. The reason for doing this is that SqlClient isn't working in rc1 so I wanted to try if I could get it to run on OSX with rc2.

**Comment by kwaazaar** [comment]
Experiencing same problem as vintern: MissingMethodException: Method not found: 'Microsoft.Extensions.PlatformAbstractions.IAssemblyLoadContextAccessor Microsoft.Extensions.PlatformAbstractions.PlatformServices.get_AssemblyLoadContextAccessor() when running dnx web. I already did a dnu restore and a dnx build, which both ran without errors.

Btw: I am trying to run in Linux (Ubuntu 14), using coreclr rc2. I don't have a global.json (only project source).

**Comment by NoneGiven** [comment]
I have the same problem as @vintem above with `dnx-coreclr-win-arm 1.0.0-rc2-20221`. Publishing with `1.0.0-rc2-16595` instead fixed the problem. All the dependcy versions are the same, `1.0.0-rc1-final` (`6.0.0` for MVC); it's just the runtime version that makes this difference.

@tidyui 
>Note that everything runs smoothly on Windows.

Windows 10 IoT on ARM still displays the issue. The x86/x64 versions of rc2-20221 seem to be fine.

**Comment by Bartmax** [comment]
had the same problem. that was because I have a rc2 version as default. i switched back to rc1 and everything works as normal.

```
dnvm use 1.0.0-rc1-update1 -r coreclr -p
```

**Comment by redpanda321** [comment]
use 1.0.0-rc1-update1 

 depend:

"Microsoft.Framework.Runtime.Interfaces": "1.0.0-beta4"

**Comment by TechSharp** [comment]
@tidyui Did you figure out how to fix it? @Bartmax switching back to rc1 will give you another error if you are trying to use Entity Framework with SQL client as @tidyui mentioned. I had rc1 with SQL client and kept getting Security 4.0.0 File not found exception.

**Comment by sharpninja** [comment]
I am receiving this error after installing ASP.net Core RC2-Final via the installer from Microsoft.  I'm running an RC1 application.  I cannot upgrade the app to RC2 because I have dependencies on MongoDB and Newtonsoft.Json, both of which don't support the new runtime.

**Comment by Bartmax** [comment]
Newtonsoft.Json definitely supports rc2. Pretty sure mongo too.

**Comment by sharpninja** [comment]
Package MongoDB.Driver 2.2.3 is not compatible with netcoreapp1.5 (.NETCoreApp,Version=v1.5). Package MongoDB.Driver 2.2.3 supports: net45 (.NETFramework,Version=v4.5)

**Comment by Bartmax** [comment]
@sharpninja you can try to use ` imports ["net45"]`  is that doesn't work, then you need to wait for Mongo.

**Comment by sharpninja** [comment]
Got the Newtonsoft and MongoDB drivers fixed, but now I'm getting errors on Microsoft.Extensions.Configuration.

![error](https://cloud.githubusercontent.com/assets/16146732/15338379/47c37c16-1c45-11e6-9b00-ace19c09bdb3.png)

**Comment by sharpninja** [comment]
Here's my project.json

{
  "version": "1.0.0-*",

  "dependencies": {
    "Microsoft.Extensions.Configuration": "1.0.0-rc2-final",
    "Microsoft.Extensions.Configuration.Abstractions": "1.0.0-rc2-final",
    "Microsoft.Extensions.Configuration.Json": "1.0.0-rc2-final",
    "MongoDB.Driver": "2.2.3",
    "NETStandard.Library": "1.5.0-rc2-24027"
  },

  "frameworks": {
    "netstandard1.5": {
      "imports": [ "net45" ]
    }
  }
}

**Comment by Bartmax** [comment]
change your imports to this: 
``` 
 "imports": [
        "dotnet5.6",
        "dnxcore50",
        "portable-net45+win8"
      ],
```

**Comment by sharpninja** [comment]
The error persists.

**Comment by Bartmax** [comment]
not sure what's going on. I tried adding netstandard1.5 on my webapp just to see what you are seeing but everything looks fine.


![image](https://cloud.githubusercontent.com/assets/3386797/15338604/037755ca-1c57-11e6-8e74-db2ed6fb34f3.png)

maybe someone else can spot what's the problem.

**Comment by sharpninja** [comment]
Why is my solution explorer still showing DNX 4.5.1 under references instead of .NETStandard,Version=v1.5

**Comment by Bartmax** [comment]
@sharpninja your `global.json`  is wrong then.

**Comment by Bartmax** [comment]
use this:

```json
{
  "projects": [ "src", "test" ],
  "sdk": {
    "version": "1.0.0-preview1-002702"
  }
}
```

**Comment by Bartmax** [comment]
or you don't have the tooling updated.

**Comment by sharpninja** [comment]
OK, changing global.json got the correct framework (Yay!), but now MongoDB.Driver is unhappy again (Boo!)

Can you try adding MongoDB.Driver 2.2.3 to your web project?

**Comment by Bartmax** [comment]
using this imports makes mongodb.driver happy
```
      "imports": [
        "dotnet5.6",
        "dnxcore50",
        "portable-net45+win8",
        "net45"
      ],
```

but take in mind that it might as well explode at runtime.

**Comment by sharpninja** [comment]
One step forward...
![error](https://cloud.githubusercontent.com/assets/16146732/15339012/fda9588c-1c47-11e6-85b3-a0e867ffb0c6.png)

**Comment by sharpninja** [comment]
Bartmax thanks for the help.  It is really appreciated.  I still haven't figured out how to overcome this error since VS won't allow me to import anything other than Nuget packages and the NETStandard.Library.

**Comment by sharpninja** [comment]
I tried importing Microsoft.NETCore.Runtime.CoreCLR-x86 because it supposedly has the types from mscorlib, but now it complains about a naming collision on System.Collections between it and Microsoft.Extensions.Configuration.Json.

**Comment by sharpninja** [comment]
Errors in C:\DGApplications\Common\Shared.NoSQLDataProxy\Dev\Direct.Shared.NoSqlDataProxy.DotNetCoreLibrary\Direct.Shared.NoSqlDataProxy.DotNetCoreLibrary.xproj
    Version conflict detected for System.Collections.
     Direct.Shared.NoSqlDataProxy.DotNetCoreLibrary (>= 1.0.0) -> Microsoft.Extensions.Configuration.Json (>= 1.0.0-rc2-final) -> Microsoft.Extensions.Configuration.FileExtensions (>= 1.0.0-rc2-final) -> Microsoft.Extensions.FileProviders.Physical (>= 1.0.0-rc2-final) -> Microsoft.Extensions.FileSystemGlobbing (>= 1.0.0-rc2-final) -> System.Collections (>= 4.0.11-rc2-24027)
     Direct.Shared.NoSqlDataProxy.DotNetCoreLibrary (>= 1.0.0) -> Microsoft.NETCore.Runtime.CoreCLR-x86 (>= 1.0.1-beta-23225) -> System.Collections (= 4.0.11-beta-23225).

**Comment by sharpninja** [comment]
Using Microsoft.NETCore.Runtime.CoreCLR fixed the naming collision.
