### ISSUE TITLE
"Add Shared Project Reference" missing

### ISSUE THREAD

**Issue by Cybrosys** [aspnet/Home#1353]
How do you add a reference to a .shproj (Shared Project) project, the add reference dialog does not list shared projects?

Update:
I found I could use the "compile" in projects.json to include my shared project's folder for compilation.

**Comment by Eilon** [comment]
@Cybrosys can you log this tooling issue at https://github.com/aspnet/Tooling/issues/? Thanks!

**Comment by Cybrosys** [comment]
@Eilon Of ourse, logged at [#426](https://github.com/aspnet/Tooling/issues/426)
