### ISSUE TITLE
Could not get cors work on simple asp.net 5 website

### ISSUE THREAD

**Issue by singlewind** [aspnet/Home#1357]
I follow the instruction at (http://docs.asp.net/en/latest/security/cors.html) to enable cors. I have tried IIS Express, Kestrel and IIS to host the app. It doesn't return any cors headers. I have attached the request as well when I test the site on Azure. 
![screenshot 2016-03-16 16 46 15](https://cloud.githubusercontent.com/assets/7637/13804491/1b9283bc-eb99-11e5-8d19-c31267676272.png)

This is what the project file looks like
  "dependencies": {
    "EntityFramework.Commands": "7.0.0-rc1-final",
    "EntityFramework.MicrosoftSqlServer": "7.0.0-rc1-final",
    "Microsoft.ApplicationInsights.AspNet": "1.0.0-rc1",
    "Microsoft.AspNet.Authentication.Cookies": "1.0.0-rc1-final",
    "Microsoft.AspNet.Diagnostics.Entity": "7.0.0-rc1-final",
    "Microsoft.AspNet.Identity.EntityFramework": "3.0.0-rc1-final",
    "Microsoft.AspNet.IISPlatformHandler": "1.0.0-rc1-final",
    "Microsoft.AspNet.Mvc": "6.0.0-rc1-final",
    "Microsoft.AspNet.Mvc.TagHelpers": "6.0.0-rc1-final",
    "Microsoft.AspNet.Server.Kestrel": "1.0.0-rc1-final",
    "Microsoft.AspNet.StaticFiles": "1.0.0-rc1-final",
    "Microsoft.AspNet.Tooling.Razor": "1.0.0-rc1-final",
    "Microsoft.AspNet.Cors": "6.0.0-rc1-final",
    "Microsoft.Extensions.CodeGenerators.Mvc": "1.0.0-rc1-final",
    "Microsoft.Extensions.Configuration.FileProviderExtensions" : "1.0.0-rc1-final",
    "Microsoft.Extensions.Configuration.Json": "1.0.0-rc1-final",
    "Microsoft.Extensions.Configuration.UserSecrets": "1.0.0-rc1-final",
    "Microsoft.Extensions.Logging": "1.0.0-rc1-final",
    "Microsoft.Extensions.Logging.Console": "1.0.0-rc1-final",
    "Microsoft.Extensions.Logging.Debug": "1.0.0-rc1-final",
    "Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.0.0-rc1-final"
  },

  "commands": {
    "web": "Microsoft.AspNet.Server.Kestrel",
    "ef": "EntityFramework.Commands"
  },

**Comment by simonmurdock** [comment]
make sure CORS is loaded first in your setup

**Comment by singlewind** [comment]
@simonmurdock I use services.AddCors() and app.UseCors(). Is there more we need to load Cors? I will dump source code to debug this anyway.

**Comment by singlewind** [comment]
@simonmurdock After debug the source code, looks like Kestrel removes cors headers

**Comment by singlewind** [comment]
I have found the issue, the header has been removed by the reverse proxy.
