### ISSUE TITLE
Q: System.Configuration.Provider namespace & system

### ISSUE THREAD

**Issue by Kaelum** [aspnet/Home#1359]
I'm not sure if this is the correct repository for this, as I can't load use VS 2015 post RC1, but I was wondering if this system is still going to be available in .NET Core or the framework?  And if there is a new system that may be favored over it as a replacement?

I've been heavily using this system for 14 years now, and it works really well, but most people don't even know it exists, or how to use it.  It works great when creating abstracted interfaces for plug-n-play systems where one consumer may use SQL Server, another may use Oracle, and another may use web services.  By simply making changes to the application configuration, the consumer can use any of the supported systems, selecting the system that works best for them.

If this is the wrong repository, please move it to the correct one.

**Comment by davidfowl** [comment]
It exists as it always has on .NET Framework, as for .NET Core, there are no plans to port it or bring it back. The new configuration system developed as part of ASP.NET core is completely different and much more light weight. 

The corefx repository would be the place to ask these kinds of questions about porting the existing .NET Framework based systems. 

Another thing to realize is that if it is ported, it will likely only be used by user code, the .NET Core framework does not have any internal dependencies on the configuration system anymore.

**Comment by Kaelum** [comment]
Thanks, I'll ask a slightly different question over there.
