### ISSUE TITLE
The docker images make a copy to an 'app' folder, that will give trouble with functionality relying on 'assembly name'.

### ISSUE THREAD

**Issue by paulvanbladel** [aspnet/Home#1360]
Sorry for the cryptic title, but following issue with taghelpers demonstrates better what I mean:

https://github.com/aspnet/Mvc/issues/4306

The fact that Dockerfile copies the sources in an folder with arbitrary name 'app' is not ok, it should be the  name of the original parent folder, otherwise you get very annoying and difficult to trace issues like the above.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.

**Comment by paulvanbladel** [comment]
Solved by json to csproj conversion.
