### ISSUE TITLE
ASP.Net Core RC1 published to Windows Server 2008 R2 IIS 7.5 routing issues.

### ISSUE THREAD

**Issue by omnoms** [aspnet/Home#1361]
I've installed the httpPlatform module so that the 500.19 error disappeared.
I've installed asp.net 5(/core) on the machine

A new site is pointed to the wwwroot folder, it runs on an app-pool which is configured for "No managed code" for the .NET CLR

So the static files are presented properly, but not the WebAPI I've built that is under approot.
So basically nothing that is supposed to route under the /api/\* paths are available. What can I do? The articles I've found claims that IIS 7.5 this should work out of the box.

**Comment by Tratcher** [comment]
Are you using nested web applications? https://github.com/aspnet/IISIntegration/issues/14

Otherwise I'd guess you didn't have HttpPlatformHandler enabled in your web.config and IIS was serving the static files itself using the native module.

**Comment by razblack** [comment]
I actually have the exact "opposite" problem.. webapi works great, but no static files at all.

I just get 404 errors.

I have followed closely all requirements in https://docs.asp.net/en/latest/publishing/iis.html#iis-server-configuration, unfortuantely I still seem to have this problem.

Any MVC pages or REST data is available (using EF 7 via localDB) i have no problems when I enter those routes.

I added app.UseDirectoryBrowser(); 'after' my .UseStaticFiles(); statement, and low and behold...  the "root" directory is provided..  that seems strange!  it lists all of my json files for the app (bower, config, hosting, project) and shows the Views and Properties directories... very odd.

![dirbrowse](https://cloud.githubusercontent.com/assets/18149815/14579438/f8e19a5e-036e-11e6-935f-e42ffca9f36a.png)


could this be some type of routing issue?

basis of Startup.cs Configure:

```
public async void Configure(IApplicationBuilder app, IServiceProvider provider, IHostingEnvironment env)
        {
            app.UseIISPlatformHandler(options => options.AuthenticationDescriptions.Clear());
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            app.UseRuntimeInfoPage("/serverinfo");  //route change for details
            app.UseDefaultFiles(); 
            app.UseStaticFiles();
            app.UseDirectoryBrowser();

            app.UseMvc(ConfigureRoutes);
        }

        private void ConfigureRoutes(IRouteBuilder routeBuilder)
        {
            routeBuilder.MapRoute(
                    name: "Default",
                    template: "{controller}/{action}/{id?}",
                    defaults: new { controller = "App", action = "Index" }
                    );

            routeBuilder.MapRoute(
                    name: "DefaultApi",
                    template: "api/{controller}/{action}/{id?}"
                    );
        }
		
....
```
here is the hosting.json:
`{
    "webroot": "../../../../../wwwroot"
}`

web.config:
```

<configuration>
  <system.webServer>
    <handlers>
      <add name="httpplatformhandler" path="*" verb="*" modules="httpPlatformHandler" resourceType="Unspecified" />
    </handlers>
    <httpPlatform processPath="..\approot\web.cmd" arguments="" stdoutLogEnabled="true" stdoutLogFile="..\logs\stdout.log" startupTimeLimit="3600"></httpPlatform>
  </system.webServer>
</configuration>
```
I've checked file permissions, everything under the wwwroot directory does have IIS_USR read permissions.

basic directory structure is like:
```

C:\iis\server\
           .\approot
           .\logs
           .\wwwroot
```

IIS only has this setup as a new website, with the physical path pointing to wwwroot.  

I'm at a complete loss... been looking at this for hours now.

**Comment by razblack** [comment]
ok, since it was so odd that when i had .UseDirectoryBrower(); and it was showing me the contents of "root", i though that perhaps i have something configured incorrectly.. however, if I copy the "wwwroot" folder into root.. it works.

eventhough IIS is pointing to C:\iis\server\wwwroot  I had to put a copy of it into C:\iis\server\approot\\packages\appnamegoeshere\1.0.0\root

could this have anything to do with my project.json?
```

{
  "version": "1.0.0-*",
  "compilationOptions": {
    "emitEntryPoint": true
  },

  "dependencies": {
    "Microsoft.AspNet.IISPlatformHandler": "1.0.0-rc1-final",
    "Microsoft.AspNet.Server.Kestrel": "1.0.0-rc1-final",
    "Microsoft.AspNet.Mvc": "6.0.0-rc1-final",
    "Microsoft.AspNet.StaticFiles": "1.0.0-rc1-final",
    "Microsoft.AspNet.Mvc.TagHelpers": "6.0.0-rc1-final",
    "Microsoft.AspNet.Diagnostics": "1.0.0-rc1-final",
    "Microsoft.Extensions.Configuration": "1.0.0-rc1-final",
    "Microsoft.Extensions.PlatformAbstractions": "1.0.0-rc1-final",
    "Microsoft.Extensions.Logging.Debug": "1.0.0-rc1-final",
    "Newtonsoft.Json": "8.0.3",
    "Microsoft.AspNet.Tooling.Razor": "1.0.0-rc1-final",
    "System.Net.Http": "4.0.1-beta-23516",
    "Microsoft.AspNet.Mvc.WebApiCompatShim": "6.0.0-rc1-final",
    "EntityFramework.Core": "7.0.0-rc1-final",
    "EntityFramework.MicrosoftSqlServer": "7.0.0-rc1-final",
    "EntityFramework.Commands": "7.0.0-rc1-final",
    "AutoMapper": "4.2.1"
  },

  "commands": {
    "ef": "EntityFramework.Commands",
    "web": "Microsoft.AspNet.Server.Kestrel --config server.json"
  },

  "frameworks": {
    "dnx451": { }
  },

  "exclude": [
    "wwwroot",
    "node_modules"
  ],
  "publishExclude": [
    "**.user",
    "**.vspscc"
  ]
}

```

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
