### ISSUE TITLE
why isn't package.json visible in asp.net core project in VS 2015?

### ISSUE THREAD

**Issue by giancarloa** [aspnet/Home#1364]
Hello...

Why isn't the package.json file visible in VS 2015 in ASP.NET core project? I have to "show all files" in order to see it... is there a way to make it visible? thanks

**Comment by MaximRouiller** [comment]
Open the xproj file in Notepad. There's a node called `DnxInvisible...` or something. Remove that line and it will show up. 

I don't remember why it's hidden but it must have to do with user experience.

**Comment by giancarloa** [comment]
@MaximRouiller ... thank you!!!! that worked...

I'd be OK with not showing the file but how else would I manage it???? When I right click on the project or the "Dependencies" node I see options for "manage nuget packages" and "manage bower packages"... but nothing along the lines of "manage npm packages"... oh well... thanks again

**Comment by MaximRouiller** [comment]
The "normal" workflow is either to edit the file manually or use `npm` with the `--save-dev`/`--save` flag to add it to the `package.json` file. 

I agree with you that it should have been kept shown. As the adoption rate increase, I believe that it's going to be a friction point. Good news, if you start with an empty template and add the file through [SideWaffle](http://sidewaffle.com/), it will be kept up.

Another file you might be interested in "un-hiding"  is `.bowerrc`. This file tell bower where to install its library. So if you want to change the `libs` folder, it's where it would be done.
