### ISSUE TITLE
Issue with executing of 'dnu pack' in Visual Studio post build event command line

### ISSUE THREAD

**Issue by ddobric** [aspnet/Home#1365]
When using 'dnu pack' in Visual Studio post build events, no any post build command (macro) can be executed after it.
For example:
cd cd $(ProjectDir)
dnu pack
copy x y

The last executed command in the sequence above will be dnu pack. Whatever is used after it, will simply be ignored.

Not sure if this is a VS or dnu issue.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
