### ISSUE TITLE
Immidiate window not work for method local variable

### ISSUE THREAD

**Issue by MohammadAkbari** [aspnet/Home#1367]
immidiate window and other debugging tools in visual studio work correctly before I upgrade visual studio update 2 rc, after upgrade immidiate window raise error this error
error CS0103: The name 'name' does not exist in the current context
when evaluate local variable that define in method, but method params correctly work.

![immidiate window](https://cloud.githubusercontent.com/assets/18085318/14104735/f4f6aca6-f5bb-11e5-8ca3-1e6df72beb67.PNG)

**Comment by Eilon** [comment]
@MohammadAkbari can you log this in https://github.com/aspnet/Tooling/issues/? That's where the VS tooling people track their bugs. Thanks!
