### ISSUE TITLE
Running ASP.NET in IISExpress from command line

### ISSUE THREAD

**Issue by chris-eaton** [aspnet/Home#1368]
I am having trouble running my ASP.NET5 from command line under IISExpress.

Having browsed questions in here and on StackOverflow I thought I had made progress, but alas I haven't.

My current command line setup (thanks to [this answer](http://stackoverflow.com/questions/33295622/iis-express-command-line-asp-net-mvc-6-beta-8/33309714#33309714) on SO) looks like so

> iisexpress.exe /config:"[project_dir].vs\config\applicationhost.config" /site:"WebUI" /apppool:"Clr4IntegratedAppPool"

When I run this, IISExpress starts up, it even finds the correct port it should run under.  The main problem is every request returns a 502.3.

Looking at the contents of IISExpress\TraceLogFiles I see this error

> ModuleName: httpPlatformHandler 
> Notification: EXECUTE_REQUEST_HANDLER 
> HttpStatus: 502 
> HttpReason: Bad Gateway 
> HttpSubStatus: 3 
> ErrorCode: The server is currently disabled. (0x8007053d) 

What is causing this? Why can't I get this to run!?

**Comment by MaximRouiller** [comment]
From what I understood, no Application pool is used by ASP.NET 5 / ASP.NET Core 1.0. They have their own process. However, I haven't played particularly with IISExpress with this scenario.

What IIS (not sure about IIS Express) does at the moment is do a reverse proxy on the process being launched. Nothing is "hosted" in IIS. It just forwards the request. Even then it needs the HTTP Platform Handler plugin.

What are you trying to do? Are you hosting it through IIS Express? Is the "F5" experience not working in Visual Studio?

**Comment by chris-eaton** [comment]
Hi Maxim, thanks for your response.

I thought that too, but when using "F5" in VS2015 everything just works.  When running in this way (under IISExpress still) I used Task Manager to grab the command line used to run the app which is how I ended up with the one I originally posted.

What I'm trying to do it get automated integration tests working.  We had them under the previous ASP.NET and im porting our code to ASP.NET5.  These integration tests run the website and all other services via command line then run using the C# Fluid API with Selenium.

**Comment by MaximRouiller** [comment]
If you are running integration tests, you should run them as close as possible to how they would be run in production. That means behind IIS itself. IISExpress was made for the good old development workflow.

If you are just testing stuff like routing, view generation, api calls... I would use a self-host.

If you are testing certificates, Windows Auth and other IIS dependent scenario, then I would go with a proper IIS.

**Comment by Tratcher** [comment]
Here's a test using our infrastructure for launching IIS Express: https://github.com/aspnet/IISIntegration/blob/dev/test/Microsoft.AspNetCore.Server.IISIntegration.FunctionalTests/HelloWorldTest.cs

**Comment by RemyArmstro** [comment]
I am still interested in a solution to this.  I am trying to run multiple asp.net projects locally through IIS Express using command line. See related issue #1012.

**Comment by efvincent** [comment]
Any progress on this? I need to run IISExpress at the command line because we're using JWT Bearer Authentication that doesn't work with the self hosted approach. We're using F# (at Jet.com), and the Visual Studio tooling for F# under with ASP.NET Core is a mess. Best bet is VS Code + CLI, but IISExpress is an issue... thoughts?

**Comment by Tratcher** [comment]
JWT Bearer should work fine for self-host. Please open a bug in Security to investigate that.

**Comment by efvincent** [comment]
@Tratcher thanks for adjusting my focus - problem solved getting JWT Authentication working in the self-host, it was my bad. For me this obviates my need to run IISExpress from the command line. Though I still think it should be doable, and I assume from your response that it isn't yet. I'll keep my eye out for a solution...

**Comment by Tratcher** [comment]
It's possible, we do it in our functional tests, it's just not pretty. See https://github.com/aspnet/Hosting/blob/dev/src/Microsoft.AspNetCore.Server.Testing/Deployers/IISExpressDeployer.cs#L53

**Comment by efvincent** [comment]
You're right. That's not pretty - but you've done the leg work, so I may just steal that. Thanks!

**Comment by amehdi** [comment]
@Tratcher that link was broken. Here is the working one:
https://github.com/aspnet/Hosting/blob/dev/src/Microsoft.AspNetCore.Server.IntegrationTesting/Deployers/IISExpressDeployer.cs

**Comment by stanleychen** [comment]
Amehdi, Thanks for sharing. How do I use the IISExpressDeployer? I have many different applications in my solution and I don't want to open all my applications when I am doing the development testing. So I am looking for a way to start the IIS EXPRESS from the command line. 

I tried "C:\Program Files\IIS Express\iisexpress" /config:C:\VS_TFS\InvestorPortal\Main\Source\.vs\config\applicationhost.config /site:IP.IdentityServer but the application didn't work when I launch it from the browser.

**Comment by Eilon** [comment]
Closing because no further action is planned for this issue.
