### ISSUE TITLE
ASP.NET Core 1.0 - FTP upload files

### ISSUE THREAD

**Issue by ge6a93** [aspnet/Home#1372]
Hi, I'm trying to upload files to a FTP server. I've tried using old piece of code I've used ASP.NET MVC 5 but DNX Core does not see to provide `FtpWebRequest` class for FTP manipulation. One workaround has come to my mind to use `HttpClient` with external Web service (WebAPI 2) which will upload my files, but I would have to maintain two applications and I don't like this approach... So is there any other approach I could use and I'm apparently missing? Thanks!

![ftp](https://cloud.githubusercontent.com/assets/5251112/14211513/2f78bd1a-f837-11e5-9520-c36c88de4d89.png)

**Comment by davidfowl** [comment]
There's no support for FtpWebRequest in .NET Core AFAIK. You'll want to file an issue on github.com/dotnet/corefx

**Comment by ge6a93** [comment]
Ok, thanks
