### ISSUE TITLE
ASP.NET Core publishing to IIS 7.5 Blank Loading Screen

### ISSUE THREAD

**Issue by beeterry** [aspnet/Home#1374]
After I publish my app using Visual Studio 2015 to IIS 7.5, I get nothing but a continuous loading screen. I used to get an error, then I downloaded httpPlatformHandler v1.2, and I get the blank loading screen now. I've declared the handler in my web.config file:
```
<system.webServer>
    <handlers>
      <add name="httpPlatformHandler" path="*" verb="*" modules="httpPlatformHandler" resourceType="Unspecified" />
    </handlers>

    <httpPlatform processPath="%DNX_PATH%" arguments="%DNX_ARGS%" stdoutLogEnabled="true" stdoutLogFile="../logs/httpplatform" startupTimeLimit="3600" forwardWindowsAuthToken="true" />
  </system.webServer>
```

And here's my Startup.cs file:.
```
public void Configure(IApplicationBuilder app, ILoggerFactory loggerFactory)
        {

            app.UseIISPlatformHandler();
            app.UseDefaultFiles();
            app.UseStaticFiles();
            app.UseMvc();
        }
```

I have unlocked my handlers in IIS and set the Physical path to the wwwroot folder that Visual Studio produced during publishing. I've also set the application pool to No Managed Code. What is left to do to solve this issue?

**Comment by GuardRex** [comment]
@beeterry What does the HttpPlatformHandler log say?

And you may need to remove this `forwardWindowsAuthToken="true"`

And you might want to run down my old post on rc1-final and see if anything jumps out. It's a bit old, but most of that still applies to rc1-final ... https://github.com/aspnet/Hosting/issues/364#issuecomment-148567294

**Comment by beeterry** [comment]
ahh, unfortunately that didn't work either. I'm just needing to load an index.html page from within the wwwroot folder. Do you think that the app.UseMVC() from the Startup.cs file is messing it up @ runtime? It's just weird that it runs correct in IIS Express.

**Comment by fletchsod-developer** [comment]
I see this bug under VS2015 Update 2.  Under VS2015 Update 1, internal exception error was present.  At least, it's a progress.   Are you saying the log file now works under Update 2  (It was never started under Update 1 as exception error occurred earlier before the instantation of the log file api in Startup.cs)

**Comment by beeterry** [comment]
I don't have anything in my logs folder that VS produced during the publish. I just tried to use the app.UseStaticFiles() and the app.UseWelcomePage() middleware in the Configure method and it still doesn't work outside of VS's IIS Express.

**Comment by beeterry** [comment]
Alright, I've changed something minor in the Configure method of my startup.cs class and I've restructured the project to mirror MVC structure (Controllers, Views, etc). Now it loads a blank screen and the console returns a 404. Anymore suggestions? 

```
public void Configure(IApplicationBuilder app, ILoggerFactory loggerFactory)
        {
            app.UseIISPlatformHandler();
            //app.UseDefaultFiles();
            app.UseFileServer(true);
            app.UseMvc(routes => 
            {
            routes.MapRoute(
                name: "default",
                template: "{controller=Home}/{action=Index}");
            });
        }
```

**Comment by fletchsod-developer** [comment]
Why is this bug report closed?

**Comment by MaximRouiller** [comment]
@fletchsod-developer closed by the same person who opened it. Must have solved his problem somehow.

**Comment by beeterry** [comment]
I did. I had to use the app.map() workaround. Finally figured it out. Here's my solution

```
public void Configure1(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
        {
            app.UseIISPlatformHandler();
            app.UseDefaultFiles();
            app.UseStaticFiles();
            app.UseFileServer(true);
            app.UseMvc();
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
        {
            app.Map("/appRoot", (app1) => this.Configure1(app1, env, loggerFactory));

        }
```

**Comment by fletchsod-developer** [comment]
Thank you for providing the solution.  That surely will help me and everyone else here having this same issues.

Thanks again.

**Comment by tokamalain** [comment]
@fletchsod-developer, so there is no need to change the "appRoot" name for the project path?
