### ISSUE TITLE
Question: how to dnx-watch on RC2?

### ISSUE THREAD

**Issue by Bartmax** [aspnet/Home#1375]
On RC1 I used `dnx-watch web` for save and refresh development.

how can I achieve that with RC2 ?

**Comment by joaomello** [comment]
I think will be something like https://github.com/aspnet/dotnet-watch

**Comment by Bartmax** [comment]
not working at the moment, right?

**Comment by joaomello** [comment]
Maybe not because build is failing =/

**Comment by victorhurdugaci** [comment]
We're in the process of updating the tools to work with the very latest CLI. So, right now it's pretty hard to get it working. But that should be solved this week.

After that, to use `dotnet-watch`, add it to the tools section of `project.json` and then follow the examples [here](https://github.com/aspnet/dotnet-watch/blob/dev/README.md)

**Comment by victorhurdugaci** [comment]
Btw, you cannot use `dnx-watch` with RC2, you must use `dotnet-watch`

**Comment by Bartmax** [comment]
i'll wait for the update of the tooling. Thanks!
