### ISSUE TITLE
Restore does not find some packages in "aspnetvnext" repo

### ISSUE THREAD

**Issue by anfomin** [aspnet/Home#1376]
I'm trying to restore packages with latest DNU 1.0.0-rc2-20221. But some packages are missing from aspnetvnext repo:

![2016-04-06 9 49 42](https://cloud.githubusercontent.com/assets/1905503/14306133/cb69b434-fbe5-11e5-9b8b-84621284ddd1.png)

There is only libraries with version 1.0.0-rc2-20221.

**Comment by Eilon** [comment]
To use RC2 at this point you need to use .NET CLI. Many packages are no longer compatible with DNU.
