### ISSUE TITLE
Cannot run project

### ISSUE THREAD

**Issue by aayushkapoor206** [aspnet/Home#1377]
Error:
```bash
System.DllNotFoundException: Unable to load DLL 'libuv': The specified module could not be found.
(Exception from HRESULT: 0x8007007E)
   at Microsoft.AspNet.Server.Kestrel.Networking.Libuv.NativeMethods.uv_loop_size()
   at Microsoft.AspNet.Server.Kestrel.Networking.UvLoopHandle.Init(Libuv uv)
   at Microsoft.AspNet.Server.Kestrel.KestrelThread.ThreadStart(Object parameter)
```

OS: Ubuntu 14.04
Runtime: CoreCLR

**Comment by chrisbradburyUP** [comment]
@aayushkapoor206 I had the same issue yesterday on Windows when updating to the latest packages. It seems the libuv.dll is in the runtimes folder of the Microsoft.AspNetCore.Server.Kestrel package but not lib folder.
 
Assuming its the same to fix on Ubuntu, go to your packages folder, find ..\Microsoft.AspNetCore.Server.Kestrel\ and copy the dll from the relevent runtimes folder to the lib folder everywhere where your Microsoft.AspNetCore.Server.Kestrel.dll exists. Hopefully that will get you up and running again.

**Comment by halter73** [comment]
If you're using rc1 packages you actually need to install libuv yourself.

    sudo apt-get install make automake libtool curl
    curl -sSL https://github.com/libuv/libuv/archive/v1.8.0.tar.gz | sudo tar zxfv - -C /usr/local/src
    cd /usr/local/src/libuv-1.8.0
    sudo sh autogen.sh
    sudo ./configure
    sudo make
    sudo make install
    sudo rm -rf /usr/local/src/libuv-1.8.0 && cd ~/
    sudo ldconfig

https://docs.asp.net/en/latest/getting-started/installing-on-linux.html?highlight=libuv#install-libuv

It's definitely a pain. RC2 will be shipping with libuv.so.
