### ISSUE TITLE
IHttpActionResult Missing from WebApiCompatShim

### ISSUE THREAD

**Issue by tonysneed** [aspnet/Home#1379]
I was wondering why IHttpActionResult is now missing from WebApiCompatShim? Was there an announcement about it being dropped?

**Comment by rynowak** [comment]
`IHttpActionResult` was never part of the shim. It and `IActionResult` are virtually same. The shim is a porting support library, and doesn't attempt to be 100% compatible with legacy WebAPI where the MVC concept is interchangeable.

**Comment by tonysneed** [comment]
Thanks, that answers my question. I thought I saw IHttpActionResult present in an early beta of the shim, so I was wondering about it. But it shouldn't be a big deal to change it to IActionResult.
