### ISSUE TITLE
Question on plans for RC3

### ISSUE THREAD

**Issue by alexbocharov** [aspnet/Home#1383]
What changes are planned in RC3? When will debugging tools in Visual Studio for RC2? Any details...

**Comment by davidfowl** [comment]
> What changes are planned in RC3? 

There is no real RC3 yet, we produce RC3 packages because 3 > 2. We have branched for RC2 so that we can make changes for the next milestone.

> When will debugging tools in Visual Studio for RC2? Any details...

We'll update the roadmap as soon as we know more. The community standup has regular status updates https://live.asp.net/

**Comment by alexbocharov** [comment]
@davidfowl What can you recommend for debugging cli in Visual Studio dotnet 2015 Update 2? This is for Orchard 2

**Comment by davidfowl** [comment]
> What can you recommend for debugging dotnet cli in Visual Studio dotnet 2015 Update 2? 

Nothing exists at the moment. You should be able to attach but there's no Visual Studio .NET CLI experience as yet. Watch the latest community stand up and you should be able to get VS code working.

**Comment by alexbocharov** [comment]
There is a problem with loading extensions. It is a difficult without debugging tools.

**Comment by alexbocharov** [comment]
Thanks, @davidfowl

**Comment by MaximRouiller** [comment]
You guys have to watch the latest Community Stand up. Watched it last night and it's awesome what you guys managed to pull off!

kudos to the team!

**Comment by cwe1ss** [comment]
if we are using the aspnetvnext nuget feed, should we keep targeting RC2-* or will those packages get removed over time and we should switch to RC3-*?

**Comment by MaximRouiller** [comment]
If what @davidfowl said about *we produce RC3 packages because 3 > 2*, then RC3 might not exist in the future. It might jump to an RC.

I would personally target RC2.
