### ISSUE TITLE
.Net Core Should have a Logo 

### ISSUE THREAD

**Issue by mohsinmuzawar** [aspnet/Home#1385]
I guess its time !! .Net Core should have its own logo. Plzzz ... :smile:

**Comment by heathyates** [comment]
I second @mohsinmuzawar.

**Comment by GuardRex** [comment]
I was both loved :heart: and vilified :facepunch: for opening https://github.com/dotnet/cli/issues/1519 ... to get rid of the little robot dude. sry ... I had nightmares of that thing chasing me :runner: :hocho: !!!

If a new logo for .NET Core would be considered, I hope MS will allow community submissions and voting for it.

**Comment by MartinJohns** [comment]
I vote for this dude:
![Image of the .NET Core robot](https://cloud.githubusercontent.com/assets/1622880/13226970/1e2ef50e-d949-11e5-9d81-1ef8c5a6172e.PNG)

**Comment by mohsinmuzawar** [comment]
@GuardRex I hope that happens bro !! :smiling_imp:

**Comment by lycon2014** [comment]
Net Core should infact have its own logo i agree

**Comment by MaximRouiller** [comment]
Let's just make sure it doesn't undergo another name change. :stuck_out_tongue_winking_eye: 

Just kidding of course. But beside the +1 comments... having a logo/image/something to help us recognize it.

If they are going the "open source" road. Logos helps people identify with it. Easier to create shirts, mugs, stickers... May not be useful for Enterprise clients but it's not the people you are targeting. 

Javascript and nodejs project all have logos that can be identified without any context. In fact, I could probably give you a framework name and the first thing that pops in your head is the logo.

Bower? Grunt? Gulp? Ember? jQuery? Angular? Handlebar? Ionic? React? Backbone?

My pleasure for the image kaleidoscope.

**Comment by samrueby** [comment]
I think we might be bike-shedding ☺

**Comment by cybertanz** [comment]
I think .NET CORE should have catchy LOGO along with a new  cleaner,minimal and lean documentation website.

**Comment by Eilon** [comment]
Hi all, at this point there are no plans for a new logo for .NET or ASP.NET. There is already an amazing logo that we use 😄 

<img src="http://go.microsoft.com/fwlink/?LinkID=288859" />
