### ISSUE TITLE
Project.json and large text fields

### ISSUE THREAD

**Issue by michaelherndon** [aspnet/Home#1387]
It would be beneficial if users could supply a path to a txt or md file for fields like the description or releaseNotes metadata fields. 

I like the new json format, it's just a pain for long text fields. 

I added the request to this repo since the project.json format resides in this wiki.
https://github.com/aspnet/Home/wiki/Project.json-file

**Comment by davidfowl** [comment]
File a bug here https://github.com/dotnet/cli

**Comment by michaelherndon** [comment]
done: https://github.com/dotnet/cli/issues/2466
