### ISSUE TITLE
Wiki page lists obsolete architecture arguments for dnvm install command

### ISSUE THREAD

**Issue by TheBeardedLlama** [aspnet/Home#1388]
### Title
Wiki page lists obsolete architecture arguments for dnvm install command

### Functional impact
N/A

### Minimal repro steps
[read](https://github.com/aspnet/Home/wiki/Version-Manager) ;)

### Expected result
* `dnvm install <semver>|<alias>|<nupkg>|latest [-arch x86|x64] [-svr50][-svrc50] [-a|-alias <alias>] [-g|-global] [-f|-force]`
  - **<semver>|<alias>**  install requested DNX from feed
  - **<nupkg>**           install requested DNX from package on local filesystem
  - **latest**            install latest DNX from feed
  - add DNX bin to path of current command line
  - **-p|-persistent**    add DNX bin to PATH environment variables persistently
  - **-a|-alias <alias>** set alias <alias> for requested DNX on install
  - **-g|-global**        install to machine-wide location
  - **-f|-force**         install even if specified version is already installed

### Actual result
* `dnvm install <semver>|<alias>|<nupkg>|latest [-x86][-x64] [-svr50][-svrc50] [-a|-alias <alias>] [-g|-global] [-f|-force]`
  - **<semver>|<alias>**  install requested DNX from feed
  - **<nupkg>**           install requested DNX from package on local filesystem
  - **latest**            install latest DNX from feed
  - add DNX bin to path of current command line
  - **-p|-persistent**    add DNX bin to PATH environment variables persistently
  - **-a|-alias <alias>** set alias <alias> for requested DNX on install
  - **-g|-global**        install to machine-wide location
  - **-f|-force**         install even if specified version is already installed

### Further technical details
wiki's don't support forking so can't do a pull request :(

**Comment by sandorfr** [comment]
Hopefully, it does not really matters since dnvm is going away.

**Comment by TheBeardedLlama** [comment]
well it does, because I ended up wasting time thinking I had done something wrong as opposed to the instructions being wrong

if and when it goes away, then remove the reference altogether

until then it does matter for those of us trying to figure out how to do things ;)

**Comment by sandorfr** [comment]
You're right, and I guess we all lost time because of those kind of documentation issues. However, I'd rather see the team ship RC2 as soon as possible rather than spending their limited time and resources on RC1 documentation.

**Comment by TheBeardedLlama** [comment]
It's dead Dave
