### ISSUE TITLE
System.MissingMethodException: Method not found: 'Microsoft.Extensions.PlatformAbstractions.IAssemblyLoadContextAccessor

### ISSUE THREAD

**Issue by ziombo** [aspnet/Home#1391]
I'm trying to run my asp.net 5 web app on ubuntu 14.04 and after running dnu restore and trying to run dnx command to host it I get this error:

> System.MissingMethodException: Method not found: 'Microsoft.Extensions.PlatformAbstractions.IAssemblyLoadContextAccessor Microsoft.Extensions.PlatformAbstractions.PlatformServices.get_AssemblyLoadContextAccessor()'.
>    at Microsoft.AspNet.Hosting.WebHostBuilder.BuildHostingServices()
>    at Microsoft.AspNet.Hosting.WebHostBuilder.Build()
>    at Microsoft.AspNet.Hosting.WebApplication.Run(Type startupType, String[] args)
>    at Microsoft.AspNet.Hosting.Program.Main(String[] args)
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at Microsoft.Dnx.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider serviceProvider)
>    at Microsoft.Dnx.ApplicationHost.Program.<>c__DisplayClass3_0.<ExecuteMain>b__0()
>    at System.Threading.Tasks.Task`1.InnerInvoke()
>    at System.Threading.Tasks.Task.Execute()

**Comment by davidfowl** [comment]
Are you using RC1 packages?

**Comment by ziombo** [comment]
I think I wasnt so after changing I got even scarier error:

> Application startup exception: System.IO.FileLoadException: Could not load file or assembly 'kis, Culture=neutral, PublicKeyToken=null' or one of its dependencies. General Exception (Exception from HRESULT: 0x80131500)
File name: 'kis, Culture=neutral, PublicKeyToken=null' ---> Microsoft.Dnx.Compilation.CSharp.RoslynCompilationException: /var/www/kis/src/KeepItSolved/Startup.cs(17,15): DNXCore,Version=v5.0 error CS0101: The namespace 'KeepItSolved' already contains a definition for 'Startup'
/var/www/kis/Models/SolvedRepository.cs(7,15): DNXCore,Version=v5.0 error CS0101: The namespace 'KeepItSolved.Models' already contains a definition for 'SolvedRepository'
/var/www/kis/Models/Flashcard.cs(3,15): DNXCore,Version=v5.0 error CS0101: The namespace 'KeepItSolved.Models' already contains a definition for 'Flashcard'
/var/www/kis/Models/ISolvedRepository.cs(5,19): DNXCore,Version=v5.0 error CS0101: The namespace 'KeepItSolved.Models' already contains a definition for 'ISolvedRepository'
/var/www/kis/Models/SolvedContext.cs(6,15): DNXCore,Version=v5.0 error CS0101: The namespace 'KeepItSolved.Models' already contains a definition for 'SolvedContext'
/var/www/kis/ViewModels/FlashcardViewModel.cs(5,15): DNXCore,Version=v5.0 error CS0101: The namespace 'KeepItSolved.ViewModels' already contains a definition for 'FlashcardViewModel'
/var/www/kis/ViewModels/LoginViewModel.cs(5,15): DNXCore,Version=v5.0 error CS0101: The namespace 'KeepItSolved.ViewModels' already contains a definition for 'LoginViewModel'
/var/www/kis/ViewModels/RegisterViewModel.cs(5,15): DNXCore,Version=v5.0 error CS0101: The namespace 'KeepItSolved.ViewModels' already contains a definition for 'RegisterViewModel'
/var/www/kis/src/KeepItSolved/Startup.cs(21,10): DNXCore,Version=v5.0 error CS0111: Type 'Startup' already defines a member called '.ctor' with the same parameter types
/var/www/kis/src/KeepItSolved/Startup.cs(32,15): DNXCore,Version=v5.0 error CS0111: Type 'Startup' already defines a member called 'ConfigureServices' with the same parameter types
/var/www/kis/src/KeepItSolved/Startup.cs(75,21): DNXCore,Version=v5.0 error CS0111: Type 'Startup' already defines a member called 'Configure' with the same parameter types
/var/www/kis/src/KeepItSolved/Startup.cs(97,28): DNXCore,Version=v5.0 error CS0111: Type 'Startup' already defines a member called 'Main' with the same parameter types
/var/www/kis/src/KeepItSolved/Controllers/Api/CardController.cs(14,18): DNXCore,Version=v5.0 error CS0101: The namespace 'KeepItSolved.Controllers.Api' already contains a definition for 'CardController'
/var/www/kis/src/KeepItSolved/Controllers/Api/CardController.cs(18,10): DNXCore,Version=v5.0 error CS0111: Type 'CardController' already defines a member called '.ctor' with the same parameter types
/var/www/kis/src/KeepItSolved/Controllers/Api/CardController.cs(24,21): DNXCore,Version=v5.0 error CS0111: Type 'CardController' already defines a member called 'Get' with the same parameter types
/var/www/kis/src/KeepItSolved/Controllers/Api/CardController.cs(33,21): DNXCore,Version=v5.0 error CS0111: Type 'CardController' already defines a member called 'Post' with the same parameter types
/var/www/kis/src/KeepItSolved/Controllers/Web/AppController.cs(11,15): DNXCore,Version=v5.0 error CS0101: The namespace 'KeepItSolved.Controllers.Web' already contains a definition for 'AppController'
/var/www/kis/src/KeepItSolved/Controllers/Web/AppController.cs(17,10): DNXCore,Version=v5.0 error CS0111: Type 'AppController' already defines a member called '.ctor' with the same parameter types
/var/www/kis/src/KeepItSolved/Controllers/Web/AppController.cs(27,30): DNXCore,Version=v5.0 error CS0111: Type 'AppController' already defines a member called 'Index' with the same parameter types
/var/www/kis/src/KeepItSolved/Controllers/Web/AppController.cs(38,36): DNXCore,Version=v5.0 error CS0111: Type 'AppController' already defines a member called 'Index' with the same parameter types
/var/www/kis/src/KeepItSolved/Controllers/Web/AppController.cs(61,24): DNXCore,Version=v5.0 error CS0111: Type 'AppController' already defines a member called 'Cards' with the same parameter types
/var/www/kis/src/KeepItSolved/Controllers/Web/AppController.cs(68,24): DNXCore,Version=v5.0 error CS0111: Type 'AppController' already defines a member called 'Register' with the same parameter types
/var/www/kis/src/KeepItSolved/Controllers/Web/AppController.cs(74,36): DNXCore,Version=v5.0 error CS0111: Type 'AppController' already defines a member called 'Register' with the same parameter types
/var/www/kis/src/KeepItSolved/Controllers/Web/AppController.cs(98,36): DNXCore,Version=v5.0 error CS0111: Type 'AppController' already defines a member called 'Logout' with the same parameter types
/var/www/kis/Models/SolvedRepository.cs(11,10): DNXCore,Version=v5.0 error CS0111: Type 'SolvedRepository' already defines a member called '.ctor' with the same parameter types
/var/www/kis/Models/SolvedRepository.cs(16,15): DNXCore,Version=v5.0 error CS0111: Type 'SolvedRepository' already defines a member called 'AddCard' with the same parameter types
/var/www/kis/Models/SolvedRepository.cs(21,33): DNXCore,Version=v5.0 error CS0111: Type 'SolvedRepository' already defines a member called 'GetAllFlashcards' with the same parameter types
/var/www/kis/Models/SolvedRepository.cs(26,33): DNXCore,Version=v5.0 error CS0111: Type 'SolvedRepository' already defines a member called 'GetUserFlashcards' with the same parameter types
/var/www/kis/Models/SolvedRepository.cs(40,15): DNXCore,Version=v5.0 error CS0111: Type 'SolvedRepository' already defines a member called 'SaveAll' with the same parameter types
/var/www/kis/Models/ISolvedRepository.cs(7,26): DNXCore,Version=v5.0 error CS0111: Type 'ISolvedRepository' already defines a member called 'GetAllFlashcards' with the same parameter types
/var/www/kis/Models/ISolvedRepository.cs(8,8): DNXCore,Version=v5.0 error CS0111: Type 'ISolvedRepository' already defines a member called 'AddCard' with the same parameter types
/var/www/kis/Models/ISolvedRepository.cs(9,8): DNXCore,Version=v5.0 error CS0111: Type 'ISolvedRepository' already defines a member called 'SaveAll' with the same parameter types
/var/www/kis/Models/ISolvedRepository.cs(10,26): DNXCore,Version=v5.0 error CS0111: Type 'ISolvedRepository' already defines a member called 'GetUserFlashcards' with the same parameter types
/var/www/kis/Models/SolvedContext.cs(8,10): DNXCore,Version=v5.0 error CS0111: Type 'SolvedContext' already defines a member called '.ctor' with the same parameter types
/var/www/kis/Models/SolvedContext.cs(15,27): DNXCore,Version=v5.0 error CS0111: Type 'SolvedContext' already defines a member called 'OnConfiguring' with the same parameter types
/var/www/kis/Migrations/SolvedContextModelSnapshot.cs(10,6): DNXCore,Version=v5.0 error CS0579: Duplicate 'DbContext' attribute
/var/www/kis/Migrations/SolvedContextModelSnapshot.cs(13,33): DNXCore,Version=v5.0 error CS0111: Type 'SolvedContextModelSnapshot' already defines a member called 'BuildModel' with the same parameter types
/var/www/kis/Migrations/20160414215220_InitialMigration.Designer.cs(10,6): DNXCore,Version=v5.0 error CS0579: Duplicate 'DbContext' attribute
/var/www/kis/Migrations/20160414215220_InitialMigration.Designer.cs(11,6): DNXCore,Version=v5.0 error CS0579: Duplicate 'Migration' attribute
/var/www/kis/Migrations/20160414215220_InitialMigration.cs(10,33): DNXCore,Version=v5.0 error CS0111: Type 'InitialMigration' already defines a member called 'Up' with the same parameter types
/var/www/kis/Migrations/20160414215220_InitialMigration.cs(160,33): DNXCore,Version=v5.0 error CS0111: Type 'InitialMigration' already defines a member called 'Down' with the same parameter types
/var/www/kis/Migrations/20160414215220_InitialMigration.Designer.cs(14,33): DNXCore,Version=v5.0 error CS0111: Type 'InitialMigration' already defines a member called 'BuildTargetModel' with the same parameter types
/var/www/kis/Startup.cs(28,4): DNXCore,Version=v5.0 error CS0229: Ambiguity between 'Startup.Configuration' and 'Startup.Configuration'
/var/www/kis/src/KeepItSolved/Models/SolvedContext.cs(17,29): DNXCore,Version=v5.0 error CS0229: Ambiguity between 'Startup.Configuration' and 'Startup.Configuration'
/var/www/kis/Models/SolvedContext.cs(17,29): DNXCore,Version=v5.0 error CS0229: Ambiguity between 'Startup.Configuration' and 'Startup.Configuration'
/var/www/kis/src/KeepItSolved/Models/SolvedRepository.cs(13,4): DNXCore,Version=v5.0 error CS0229: Ambiguity between 'SolvedRepository._context' and 'SolvedRepository._context'
/var/www/kis/src/KeepItSolved/Models/SolvedRepository.cs(18,4): DNXCore,Version=v5.0 error CS0229: Ambiguity between 'SolvedRepository._context' and 'SolvedRepository._context'
/var/www/kis/src/KeepItSolved/Models/SolvedRepository.cs(23,11): DNXCore,Version=v5.0 error CS0229: Ambiguity between 'SolvedRepository._context' and 'SolvedRepository._context'
/var/www/kis/src/KeepItSolved/Startup.cs(28,4): DNXCore,Version=v5.0 error CS0229: Ambiguity between 'Startup.Configuration' and 'Startup.Configuration'
/var/www/kis/Controllers/Web/AppController.cs(21,4): DNXCore,Version=v5.0 error CS0229: Ambiguity between 'AppController._repository' and 'AppController._repository'
/var/www/kis/Controllers/Web/AppController.cs(22,4): DNXCore,Version=v5.0 error CS0229: Ambiguity between 'AppController._userManager' and 'AppController._userManager'
/var/www/kis/Controllers/Web/AppController.cs(23,4): DNXCore,Version=v5.0 error CS0229: Ambiguity between 'AppController._signInManager' and 'AppController._signInManager'
/var/www/kis/Controllers/Web/AppController.cs(33,37): DNXCore,Version=v5.0 error CS0229: Ambiguity between 'LoginViewModel.ReturnUrl' and 'LoginViewModel.ReturnUrl'
/var/www/kis/src/KeepItSolved/Models/SolvedRepository.cs(30,12): DNXCore,Version=v5.0 error CS0229: Ambiguity between 'SolvedRepository._context' and 'SolvedRepository._context'
/var/www/kis/src/KeepItSolved/Models/SolvedRepository.cs(42,11): DNXCore,Version=v5.0 error CS0229: Ambiguity between 'SolvedRepository._context' and 'SolvedRepository._context'
/var/www/kis/Models/SolvedRepository.cs(13,4): DNXCore,Version=v5.0 error CS0229: Ambiguity between 'SolvedRepository._context' and 'SolvedRepository._context'
/var/www/kis/Models/SolvedRepository.cs(18,4): DNXCore,Version=v5.0 error CS0229: Ambiguity between 'SolvedRepository._context' and 'SolvedRepository._context'
/var/www/kis/Models/SolvedRepository.cs(23,11): DNXCore,Version=v5.0 error CS0229: Ambiguity between 'SolvedRepository._context' and 'SolvedRepository._context'
/var/www/kis/Models/SolvedRepository.cs(30,12): DNXCore,Version=v5.0 error CS0229: Ambiguity between 'SolvedRepository._context' and 'SolvedRepository._context'
/var/www/kis/Models/SolvedRepository.cs(42,11): DNXCore,Version=v5.0 error CS0229: Ambiguity between 'SolvedRepository._context' and 'SolvedRepository._context'
/var/www/kis/Controllers/Api/CardController.cs(20,4): DNXCore,Version=v5.0 error CS0229: Ambiguity between 'CardController._repository' and 'CardController._repository'
/var/www/kis/Controllers/Api/CardController.cs(26,16): DNXCore,Version=v5.0 error CS0229: Ambiguity between 'CardController._repository' and 'CardController._repository'
/var/www/kis/Controllers/Api/CardController.cs(40,14): DNXCore,Version=v5.0 error CS0229: Ambiguity between 'Flashcard.UserName' and 'Flashcard.UserName'
/var/www/kis/Controllers/Api/CardController.cs(43,6): DNXCore,Version=v5.0 error CS0229: Ambiguity between 'CardController._repository' and 'CardController._repository'
/var/www/kis/Controllers/Api/CardController.cs(45,10): DNXCore,Version=v5.0 error CS0229: Ambiguity between 'CardController._repository' and 'CardController._repository'
/var/www/kis/src/KeepItSolved/Controllers/Api/CardController.cs(20,4): DNXCore,Version=v5.0 error CS0229: Ambiguity between 'CardController._repository' and 'CardController._repository'
/var/www/kis/src/KeepItSolved/Controllers/Api/CardController.cs(26,16): DNXCore,Version=v5.0 error CS0229: Ambiguity between 'CardController._repository' and 'CardController._repository'
/var/www/kis/src/KeepItSolved/Controllers/Api/CardController.cs(40,14): DNXCore,Version=v5.0 error CS0229: Ambiguity between 'Flashcard.UserName' and 'Flashcard.UserName'
/var/www/kis/src/KeepItSolved/Controllers/Api/CardController.cs(43,6): DNXCore,Version=v5.0 error CS0229: Ambiguity between 'CardController._repository' and 'CardController._repository'
/var/www/kis/src/KeepItSolved/Controllers/Api/CardController.cs(45,10): DNXCore,Version=v5.0 error CS0229: Ambiguity between 'CardController._repository' and 'CardController._repository'
/var/www/kis/Controllers/Web/AppController.cs(42,65): DNXCore,Version=v5.0 error CS0229: Ambiguity between 'LoginViewModel.Login' and 'LoginViewModel.Login'
/var/www/kis/Controllers/Web/AppController.cs(42,78): DNXCore,Version=v5.0 error CS0229: Ambiguity between 'LoginViewModel.Password' and 'LoginViewModel.Password'
/var/www/kis/Controllers/Web/AppController.cs(42,24): DNXCore,Version=v5.0 error CS0229: Ambiguity between 'AppController._signInManager' and 'AppController._signInManager'
/var/www/kis/Controllers/Web/AppController.cs(45,38): DNXCore,Version=v5.0 error CS0229: Ambiguity between 'LoginViewModel.ReturnUrl' and 'LoginViewModel.ReturnUrl'
/var/www/kis/Controllers/Web/AppController.cs(45,73): DNXCore,Version=v5.0 error CS0229: Ambiguity between 'LoginViewModel.ReturnUrl' and 'LoginViewModel.ReturnUrl'
/var/www/kis/Controllers/Web/AppController.cs(47,29): DNXCore,Version=v5.0 error CS0229: Ambiguity between 'LoginViewModel.ReturnUrl' and 'LoginViewModel.ReturnUrl'
/var/www/kis/Controllers/Web/AppController.cs(63,16): DNXCore,Version=v5.0 error CS0229: Ambiguity between 'AppController._repository' and 'AppController._repository'
/var/www/kis/Controllers/Web/AppController.cs(78,52): DNXCore,Version=v5.0 error CS0229: Ambiguity between 'RegisterViewModel.Login' and 'RegisterViewModel.Login'
/var/www/kis/Controllers/Web/AppController.cs(78,73): DNXCore,Version=v5.0 error CS0229: Ambiguity between 'RegisterViewModel.Email' and 'RegisterViewModel.Email'
/var/www/kis/Controllers/Web/AppController.cs(79,61): DNXCore,Version=v5.0 error CS0229: Ambiguity between 'RegisterViewModel.Password' and 'RegisterViewModel.Password'
/var/www/kis/Controllers/Web/AppController.cs(79,24): DNXCore,Version=v5.0 error CS0229: Ambiguity between 'AppController._userManager' and 'AppController._userManager'
/var/www/kis/Controllers/Web/AppController.cs(82,12): DNXCore,Version=v5.0 error CS0229: Ambiguity between 'AppController._signInManager' and 'AppController._signInManager'
/var/www/kis/Controllers/Web/AppController.cs(100,10): DNXCore,Version=v5.0 error CS0229: Ambiguity between 'AppController._signInManager' and 'AppController._signInManager'
/var/www/kis/src/KeepItSolved/Controllers/Web/AppController.cs(21,4): DNXCore,Version=v5.0 error CS0229: Ambiguity between 'AppController._repository' and 'AppController._repository'
/var/www/kis/src/KeepItSolved/Controllers/Web/AppController.cs(22,4): DNXCore,Version=v5.0 error CS0229: Ambiguity between 'AppController._userManager' and 'AppController._userManager'
/var/www/kis/src/KeepItSolved/Controllers/Web/AppController.cs(23,4): DNXCore,Version=v5.0 error CS0229: Ambiguity between 'AppController._signInManager' and 'AppController._signInManager'
/var/www/kis/src/KeepItSolved/Controllers/Web/AppController.cs(33,37): DNXCore,Version=v5.0 error CS0229: Ambiguity between 'LoginViewModel.ReturnUrl' and 'LoginViewModel.ReturnUrl'
/var/www/kis/src/KeepItSolved/Controllers/Web/AppController.cs(42,65): DNXCore,Version=v5.0 error CS0229: Ambiguity between 'LoginViewModel.Login' and 'LoginViewModel.Login'
/var/www/kis/src/KeepItSolved/Controllers/Web/AppController.cs(42,78): DNXCore,Version=v5.0 error CS0229: Ambiguity between 'LoginViewModel.Password' and 'LoginViewModel.Password'
/var/www/kis/src/KeepItSolved/Controllers/Web/AppController.cs(42,24): DNXCore,Version=v5.0 error CS0229: Ambiguity between 'AppController._signInManager' and 'AppController._signInManager'
/var/www/kis/src/KeepItSolved/Controllers/Web/AppController.cs(45,38): DNXCore,Version=v5.0 error CS0229: Ambiguity between 'LoginViewModel.ReturnUrl' and 'LoginViewModel.ReturnUrl'
/var/www/kis/src/KeepItSolved/Controllers/Web/AppController.cs(45,73): DNXCore,Version=v5.0 error CS0229: Ambiguity between 'LoginViewModel.ReturnUrl' and 'LoginViewModel.ReturnUrl'
/var/www/kis/src/KeepItSolved/Controllers/Web/AppController.cs(47,29): DNXCore,Version=v5.0 error CS0229: Ambiguity between 'LoginViewModel.ReturnUrl' and 'LoginViewModel.ReturnUrl'
/var/www/kis/src/KeepItSolved/Controllers/Web/AppController.cs(63,16): DNXCore,Version=v5.0 error CS0229: Ambiguity between 'AppController._repository' and 'AppController._repository'
/var/www/kis/src/KeepItSolved/Controllers/Web/AppController.cs(78,52): DNXCore,Version=v5.0 error CS0229: Ambiguity between 'RegisterViewModel.Login' and 'RegisterViewModel.Login'
/var/www/kis/src/KeepItSolved/Controllers/Web/AppController.cs(78,73): DNXCore,Version=v5.0 error CS0229: Ambiguity between 'RegisterViewModel.Email' and 'RegisterViewModel.Email'
/var/www/kis/src/KeepItSolved/Controllers/Web/AppController.cs(79,61): DNXCore,Version=v5.0 error CS0229: Ambiguity between 'RegisterViewModel.Password' and 'RegisterViewModel.Password'
/var/www/kis/src/KeepItSolved/Controllers/Web/AppController.cs(79,24): DNXCore,Version=v5.0 error CS0229: Ambiguity between 'AppController._userManager' and 'AppController._userManager'
/var/www/kis/src/KeepItSolved/Controllers/Web/AppController.cs(82,12): DNXCore,Version=v5.0 error CS0229: Ambiguity between 'AppController._signInManager' and 'AppController._signInManager'
/var/www/kis/src/KeepItSolved/Controllers/Web/AppController.cs(100,10): DNXCore,Version=v5.0 error CS0229: Ambiguity between 'AppController._signInManager' and 'AppController._signInManager'
/var/www/kis/Controllers/Api/CardController.cs(16,29): DNXCore,Version=v5.0 warning CS0169: The field 'CardController._repository' is never used
/var/www/kis/src/KeepItSolved/Controllers/Web/AppController.cs(14,37): DNXCore,Version=v5.0 warning CS0169: The field 'AppController._userManager' is never used
/var/www/kis/Controllers/Web/AppController.cs(14,37): DNXCore,Version=v5.0 warning CS0169: The field 'AppController._userManager' is never used
/var/www/kis/src/KeepItSolved/Controllers/Api/CardController.cs(16,29): DNXCore,Version=v5.0 warning CS0169: The field 'CardController._repository' is never used
/var/www/kis/Controllers/Web/AppController.cs(13,29): DNXCore,Version=v5.0 warning CS0169: The field 'AppController._repository' is never used
/var/www/kis/src/KeepItSolved/Controllers/Web/AppController.cs(15,39): DNXCore,Version=v5.0 warning CS0169: The field 'AppController._signInManager' is never used
/var/www/kis/Controllers/Web/AppController.cs(15,39): DNXCore,Version=v5.0 warning CS0169: The field 'AppController._signInManager' is never used
/var/www/kis/src/KeepItSolved/Models/SolvedRepository.cs(9,25): DNXCore,Version=v5.0 warning CS0169: The field 'SolvedRepository._context' is never used
/var/www/kis/src/KeepItSolved/Controllers/Web/AppController.cs(13,29): DNXCore,Version=v5.0 warning CS0169: The field 'AppController._repository' is never used
/var/www/kis/Models/SolvedRepository.cs(9,25): DNXCore,Version=v5.0 warning CS0169: The field 'SolvedRepository._context' is never used
/var/www/kis/Startup.cs(97,28): DNXCore,Version=v5.0 error CS0017: Program has more than one entry point defined. Compile with /main to specify the type that contains the entry point.
   at Microsoft.Dnx.Compilation.CSharp.RoslynProjectReference.Load(AssemblyName assemblyName, IAssemblyLoadContext loadContext)
   at Microsoft.Dnx.Compilation.CompilationEngine.LoadProject(Project project, FrameworkName targetFramework, String aspect, IAssemblyLoadContext loadContext, AssemblyName assemblyName)
   at Microsoft.Dnx.Runtime.Loader.ProjectAssemblyLoader.Load(AssemblyName assemblyName, IAssemblyLoadContext loadContext)
   at Microsoft.Dnx.Runtime.Loader.ProjectAssemblyLoader.Load(AssemblyName assemblyName)
   at Microsoft.Dnx.Host.LoaderContainer.Load(AssemblyName assemblyName)
   at Microsoft.Dnx.Host.DefaultLoadContext.LoadAssembly(AssemblyName assemblyName)
   at Microsoft.Dnx.Runtime.Loader.AssemblyLoaderCache.GetOrAdd(AssemblyName name, Func`2 factory)
   at Microsoft.Dnx.Runtime.Loader.LoadContext.Load(AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyName(AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.Resolve(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName)
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at Microsoft.AspNet.Hosting.Startup.StartupLoader.FindStartupType(String startupAssemblyName, IList`1 diagnosticMessages)
   at Microsoft.AspNet.Hosting.Internal.HostingEngine.EnsureStartup()
   at Microsoft.AspNet.Hosting.Internal.HostingEngine.EnsureApplicationServices()
   at Microsoft.AspNet.Hosting.Internal.HostingEngine.BuildApplication()

**Comment by davidfowl** [comment]
@ziombo Can you put the repro project on github with instructions? My guess is you updated something to rc2 and broke yourself.

**Comment by ziombo** [comment]
https://github.com/ziombo/KeepItSolved here is my project. So far I've managed to make almost everything work. I end up running dnx kestrel (for public access) or dnx web (for local) but nothing loads when I go to the site. I tried using curl localhost:5000 (thats the address for dnx web) but I get nothing.There is lierally 0 html being loaded. I don't understand what You mean by "with instructions". Also, is it possible that things go south because my webapp is using sql server and I don't have one on my server (I thought I'll get an error at least because of that)?  I also have this repository https://github.com/ziombo/KISDNU where I have my project published, but I believe I messed up something so I was using the non-published one lately.

**Comment by davidfowl** [comment]
First issue so far:

https://github.com/ziombo/KeepItSolved/blob/master/src/KeepItSolved/project.json#L15 You have a beta7 reference, get rid of that thing.

**Comment by ziombo** [comment]
From what I see, this is the latest version. Should I delete it or what? https://www.nuget.org/packages/Microsoft.AspNet.Server.IIS/

**Comment by davidfowl** [comment]
@ziombo https://github.com/aspnet/Announcements/issues/69, great!

Whenever you're confused about which things you need to reference because you updated, you should make a new project and see what that does.

**Comment by ziombo** [comment]
Well, this doesn't really change much as my app still doesnt load. Nothing, blank page.

**Comment by davidfowl** [comment]
I sent a pull request, https://github.com/ziombo/KeepItSolved/pull/1. Try it out. The error I got was that the database connection was failing.

**Comment by ziombo** [comment]
Thanks for all the help so far but right now I am still very confused as I am new to all these things. Could You tell me what should I work on right now to make my app work? To my understanding I should add a sql server and connect my web app to it?

**Comment by ziombo** [comment]
I got an update here. I tried to use this tutorial to add a sql db on my server and make my app use it. I changed whole configuration locally (I can do it on other branch on my repository if needed) but I get an error after running  

`dnu build --quiet`

(actually its alot of errors for dnx 4.5.1 but for dnxcore 5.0 its only 1)


> Building KeepItSolved for DNXCore,Version=v5.0
> /var/www/kis/src/KeepItSolved/Models/SolvedContext.cs(21,19): DNXCore,Version=v5.0 error CS1061: 'DbContextOptionsBuilder' does not contain a definition for 'UseSqlite' and no extension method 'UseSqlite' accepting a first argument of type 'DbContextOptionsBuilder' could be found (are you missing a using directive or an assembly reference?)

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
