### ISSUE TITLE
Unable to resolve 'Libuv (>= 1.9.0-rc2-20581)' for '.NETFramework,Version=v4.5.1' on aspnetrelease-feed

### ISSUE THREAD

**Issue by cwe1ss** [aspnet/Home#1392]
Hi,
Eilon [mentioned](https://github.com/aspnet/Mvc/issues/4495#issuecomment-211483592) the aspnetrelease feed for stable RC2 packages, so I just switched to it for one of my projects.

However, on dotnet restore, I get the following error:

`Unable to resolve 'Libuv (>= 1.9.0-rc2-20581)' for '.NETFramework,Version=v4.5.1'`

Is there anything missing on this feed or am I doing something wrong?

here's the full build log: https://ci.appveyor.com/project/cwe1ss/servicefabric-httpservicegateway

and here's the code: https://github.com/c3-ls/ServiceFabric-Http

thx for your help!

**Comment by EricABC** [comment]
Check out aspnetcirelease instead of aspnetrelease.  Its at 20607 with Libuv on it at the time of this.

**Comment by mikes-gh** [comment]
Could someone explain difference between aspnetcirelease and aspnetrelease feeds (apart from ci is nightly ci builds).
Wondering what the process for aespcirelease -> aspnetrelease is.

**Comment by davidfowl** [comment]
We branch from dev to release when we're slowing down developing and closing down a milestone. The latest RC2 bits are on cirelease now, and dev is opened up for RTM checkins, or whatever we call the next release (now called rc3 in the package versions).

**Comment by mikes-gh** [comment]
@davidfowl sorry the above still doesn't make it clear to me what aspnetrelease feed is for.  I was using aspnetcirelease (working fine) on your advice to track rc2 but aspnetrelease is the feed that is being recommened by others.

**Comment by davidfowl** [comment]
Ah my bad I misread that. aspnetrelease is tested bits, aspnetcirelease is compiled bits 😄

**Comment by mikes-gh** [comment]
Ok but it looks like in this case libuv is missing from aspnetrelease . Just wondering how that happened and what 'Tested' means.

**Comment by davidfowl** [comment]
> Ok but it looks like in this case libuv is missing from aspnetrelease. Just wondering how that happened

Somethings stuff goes wrong.

/cc @pranavkm about the missing packages.

> and what 'Tested' means.

Tested literally means, we ran tests, both unit tests and functional tests. Compiled means we ran build but didn't run tests.

**Comment by mikes-gh** [comment]
Ah ok thanks.  So you have other tests aside from the build tests? Last post promise.

**Comment by cwe1ss** [comment]
I just moved to the "aspnetcirelease" feed and no longer get this error. So I guess it's either a temporal issue until a new build gets pushed to "aspnetrelease" or some package is missing there
