### ISSUE TITLE
License files

### ISSUE THREAD

**Issue by nojaf** [aspnet/Home#1396]
Apologies if this is more or less a broad question but I was wondering what the story of license files is.

So it is my understanding that if you ship an application to production you need to include the license files of every package you use. Whether it is ASP NET Core, EF, bootstrap, some javascript library, ... any third party piece of software.

How will this be tackled in the new ASP NET world? Will new scaffolded projects contain a license folder with everything it uses?

Should a license be shipped with nuget, bower, npm and is the only thing we need a job/script/tool to collect all the files?

Or is there an easy way to do all this today and will we be able to re-use that?

**Comment by Eilon** [comment]
Hi @nojaf , sorry for the delay responding to you. Ultimately this is a question that only an attorney who knows the applicable laws governing your particular situation would be able to answer.

Some things to consider are whether you are *redistributing* components, *using* components, or creating *derivative* components. A great place to seek general information is on http://opensource.stackexchange.com/, where you might find questions and answers that will help guide you to a solution.

Unfortunately we cannot give specific legal advice. But the good news is that the licenses we use on the various software components are extremely common licenses, so finding information on them should be fairly easy.

**Comment by nojaf** [comment]
Thanks
