### ISSUE TITLE
Question re asp-validation-summary tag helper

### ISSUE THREAD

**Issue by eriksendc** [aspnet/Home#1399]
Hi All,

Was wondering if there's some additional attribute or something that enables the headertext property of a validation summary? I'm using the basic validation summary tag helper:

`<div asp-validation-summary="ValidationSummary.All" class="text-danger"></div>`

I'd like to have "Please correct the following and try again:" be rendered as a paragraph before the bulleted list produced by the validation summary. The previous encarnations had an attribute called headertext that let you accomplish this.

I tried finding the appropriate repo for posting this and couldn't figure out where to put this. Sorry in advance if I've put this issue in the wrong place.

Thanks,
-Brian Eriksen

**Comment by dougbu** [comment]
Anything already in the `<div>` element is left alone. E.g.
``` html
<div asp-validation-summary="@ValidationSummary.All" style="color:blue" id="validation_day" class="form-group">
    <span style="color:red">This is my message</span>
</div>
```

results in the following when everything on the page is valid
``` html
 <div style="color:blue" id="validation_day" class="form-group validation-summary-valid" data-valmsg-summary="true">
    <span style="color:red">This is my message</span>
    <ul><li style="display:none"></li>
</ul></div>
```

If you prefer the message not be visible when the page is valid, change the `validation-summary-valid` style to hide the `<div>` or make your content hidden by default.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
