### ISSUE TITLE
Using dnvm to set an alias breaks my start menu

### ISSUE THREAD

**Issue by bytesoftly** [aspnet/Home#1400]
Having installed a new DNX runtime I attempted to set it to the default alias under Windows 10 using the following as admin on the command line:
`dnvm alias default 1.0.0-rc1-update2 -x64`
The following then immediately shows when attempting to open the start menu:
![1b15f4337efb3f76e4dc9464c8157aad86d96a222e111a14ede573170702fd21_win10_critical_error_-_start_menu](https://cloud.githubusercontent.com/assets/16628563/14728461/dc2ac7e2-082c-11e6-8876-ded9c766aa4a.JPG)
1. How can I fix my start menu (since signing out doesn't solve it)?
2. Setting the `default` alias didn't work with the command I used (`dnvm list` shows another runtime is still default) so guessing that's a bug too or am I using it wrongly?

This has now broken my start menu on two Win10 x64 machines!

**Comment by GuardRex** [comment]
@bytesoftly I can't say much about a broken start menu, but I can tell you that DNX is basically :skull: dead :skull: at this point. `dotnet cli` is replacing it for the RC2 release, which is within a few weeks away. If you're getting into this for the first time now, checkout https://github.com/dotnet/cli/tree/rel/1.0.0 and https://github.com/aspnet/cli-samples.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
