### ISSUE TITLE
How to delete the "Dependencies" in asp.net core template project.

### ISSUE THREAD

**Issue by liamwang** [aspnet/Home#1401]
![image](https://cloud.githubusercontent.com/assets/5000396/14730397/9a547588-0878-11e6-9613-fc9bd388d177.png)

How to delete the "Dependencies"? Sometimes we don't need npm and bower.

By the way, the arrow icon before the "Dependencies" is ugly. I really hope that it can be replaced.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
