### ISSUE TITLE
Should code be aware of all environments

### ISSUE THREAD

**Issue by WimVergouwe** [aspnet/Home#1402]
When looking at [_Layout.cshml](https://github.com/aspnet/Templates/blob/dev/src/BaseTemplates/StarterWeb/Views/Shared/_Layout.cshtml) in Templates the MVC app seems to be aware of all environments. When using release tools such as release management, this can become quite unpractical. In such cases we typically want a package that is unaware of the specific environments, so that we can deploy the same package to any environment we like.

Wouldn't it be better to allow for something like:

``` xml
<environment names-in="Development">
    <!-- Any content... -->
</environment>
<environment names-not-in="Local,Development">
    <!-- Any content... -->
</environment>
```

I would be more than willing to try to create a pull request for this, although we probably need two, one for MVC and one for the templates, right?

What do guys you think?

**Comment by simonmurdock** [comment]
Isn't that the idea, that the "Development" environment name comes from a machine-specific environment variable or something? Meaning you can deploy it anywhere that has the environment variable?

**Comment by WimVergouwe** [comment]
@simonmurdock, of course we could use any environment name we like. But still, as far as I understand it, you still need to know them **all** in code. While you basically just want to do something specific for the development environment and something else for **all** other environments. 
Does this make sense?

**Comment by shanselman** [comment]
Interesting idea. @danroth27 ?

**Comment by danroth27** [comment]
@DamianEdwards Thoughts on this?

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
