### ISSUE TITLE
asp.net core pre-release for visual studio 2015

### ISSUE THREAD

**Issue by Varorbc** [aspnet/Home#1404]
asp.net core tool can be released in order to be able to develop in studio visual 2015?

**Comment by ryzewu** [comment]
same issue.
i am really looking forward to asp.net core rc2 tool for visual studio too.

**Comment by imranbaloch** [comment]
I think in short there should be a way to get/test pre-release tools(that the team @shanselman @davidfowl showed in community standup). If we can get rc2 unstable source bits then why we can't get unstable tooling bits? I believe dev can test and submit early feedback before it actually shipped? But this question belong to Tooling repo?

**Comment by davidfowl** [comment]
> If we can get rc2 unstable source bits then why we can't get unstable tooling bits?

What happens if you get unstable tooling bits and it destroys your machine? What happens if you can't do anything else in Visual Studio because of unstable tooling? Would you be ok with that? What if we told you to run it in a Virtual Machine just in case?

**Comment by damienbod** [comment]
@davidfowl sounds good

**Comment by imranbaloch** [comment]
@davidebbo Thanks :) I got it but there are still lot of dev/authors/teachers willing to check/test/play with the bleeding edge stuffs even if the stuff make their VS/OS unstable (they can re-install). I believe there are certain different types of dev/managers/authors/teachers, some of them include,

1) who waits the for it to become mature before they use it (at-least 1 years after the RTM).
2) who only use it when it released/RTM.
3) who uses only officials releases (even if it is in alpha, beta, RC, etc.)
4) who wanna to be in bleeding edge even if unstable bits make their machine in a state where reset/repair will be required :)

**Comment by Varorbc** [comment]
@davidfowl We are waiting for a good hard.Why is there a beta version of the rc1?

**Comment by davidfowl** [comment]
@imranbaloch NuGet packages don't affect much. They are isolated and can only affect a simple application. Compare that to Visual Studio which you probably use for every day development of other things. If installing a prerelease version of something damages your VS install, you'd be pretty upset. I know I would be. So the bar is higher than packages because the potential impact is larger.

@Varorbc I dunno what you mean

**Comment by imranbaloch** [comment]
@davidfowl for users who wanna test bleeding edge stuffs, can't we add a disclaimer, _The use of pre-release tools may harm your VS/System, use it on your own risk_  :wink:

**Comment by John0King** [comment]
@davidfowl   How about publish a unstable tools here on github? And only ship  stable version on VS marketplace

**Comment by ryzewu** [comment]
@John0King I couldn’t agree more.

**Comment by Boglen** [comment]
Agree. We using a insider version of win10, RC of VS2015 before RTM. I think we could use pre-release of dotnet tools for vs without any upset)

**Comment by davidfowl** [comment]
When the bits are less-unstable, we may consider sharing them. 

/cc @DamianEdwards

**Comment by freemsly** [comment]
How Can I debug a asp net core RC2 sloution? I  run it based only all framework( net451).  where Can I find the latest Microsoft ASP.NET and Web Tools for studio visual 2015?

**Comment by Boglen** [comment]
Nowhere, yet

**Comment by GuardRex** [comment]
@freemsly You can use [VS Code](https://code.visualstudio.com/) right now prior to an updated VS arriving, which will be released when RC2 releases within probably 3-6 weeks according to the last [Community Standup](https://www.youtube.com/watch?v=hfJgGHqVcLI&list=PL0M0zPgJ3HSftTAAHttA3JQU4vOjXFquF&index=0). VS Code is capable of debugging RC2-nightly applications.
