### ISSUE TITLE
Multi Select Dropdown List Data Type

### ISSUE THREAD

**Issue by jazzyhacker** [aspnet/Home#1405]
Hi, I'd like to know, is there any data type that match multi select drop-down list? Can I use List<T>? Will the model convert:
`<input asp-for="MultiSelectModel" />` to HTML compatible control for Multi Select Dropdown list?

Actually for just a suggestion, it will be great if ASP.NET 5/ASP.NET Core 1.0 enrich the Data Type (Two Options, Multiple Options, etc.) and Web Control (Entity Reference Picker, Form View and Edit) like Microsoft Dynamics CRM.

**Comment by dougbu** [comment]
@jazzyhacker the `<input/>` tag helper _always_ generates an `<input/>` element. However the `<select>` tag helper uses the expression type to determine whether `multiple="multiple"` is needed. With that tag helper e.g. `<select asp-for="MultiSelectModel" asp-items="selectList"></select>`, any `IEnumerable` implementation (except `string`) results in a multi-select drop-down.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
