### ISSUE TITLE
Can't debug in IE for Angular2 TS aspnetcore application

### ISSUE THREAD

**Issue by Sharpiro** [aspnet/Home#1406]
https://github.com/Sharpiro/InterviewPrep/tree/issues/noDebug

above is the simple solution to provide an example for the issue.

You will see that source maps are being generated, and I can even debug in chrome appropriately.  However when using IE/IISExpress I cannot get VS to load symbols, and the breakpoints are all colored white.

I am using Visual Studio 2015 Update 2.

Edit: Confirmed also exists in VS 2015 Update 1

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
