### ISSUE TITLE
Reporting Framework

### ISSUE THREAD

**Issue by ProH4Ck** [aspnet/Home#1409]
I'm developing a new project and cusotmer asked me to implement a simple report to show data manipulated by web application. Any suggestion compatible with the new ASP.NET Core?

**Comment by GuardRex** [comment]
@ProH4Ck If you're asking about charts for reports and you want something quick and easy that you can render in the browser (and thus eliminate any issues with Core compatability), [Google Charts](https://developers.google.com/chart/) is a possibility.

**Comment by MaximRouiller** [comment]
Or Chartist. Or Chart.js. Or nvd3 or pure d3.js.... there's so many of them.

Just look for "javascript" and "charting".

**Comment by ProH4Ck** [comment]
Nice... I didn't think to a js solution. I'll proceed on this way. Thanks guys! @GuardRex @MaximRouiller

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
