### ISSUE TITLE
MVC 5 Web App Project Load Failed in VS 2015

### ISSUE THREAD

**Issue by tysonnero** [aspnet/Home#1410]
Up until yesterday, I was able to open and create ASP.NET MVC 5 web application in VS 2015 Update 2. Since then, I can no longer open existing MVC 5 projects of create new ones. I did not manually update VS 2015.

Here are some example errors I am getting:

C:\Projects\Samples\xxxx\xxxx.xproj : error : Import "Microsoft.VisualStudio.Web.ProjectSystem.UnconfiguredWebProject.IdleScheduler" could not be satisfied.

C:\Projects\Samples\xxxx\xxxx.xproj : error : Instantiated part(s) threw exception(s) from IDisposable.Dispose().

Any ideas on the cause and solution?

**Comment by tysonnero** [comment]
The culprit was an extension called Productivity Power Tools 2015. Once disabled, I was able to load my projects.

**Comment by MaximRouiller** [comment]
It would be interesting to have better extension handling in Visual Studio. Yes. **Extension** handling.

I mean... extension memory usage, exceptions that are thrown or degradated Visual Studio performance/experience.
