### ISSUE TITLE
Discussion for: Packages containing tools are being renamed

### ISSUE THREAD

**Issue by moozzyk** [aspnet/Home#1411]
Discussion for https://github.com/aspnet/Announcements/issues/172

**Comment by Bartmax** [comment]
What exactly razor tools does? and when/why I could need it?

**Comment by natemcmaster** [comment]
https://github.com/aspnet/RazorTooling is part of what provides the IntelliSense for Razor files (*.cshtml) in Visual Studio.

**Comment by Bartmax** [comment]
is this a visual studio only thing? shouldn't be part of visual studio instead of some tool package? Even if it's not only for VS, I don't see how an IDE feature has a place on `project.json`

**Comment by 304NotModified** [comment]
A table would be more readable than an list (at least on mobile)

**Comment by MaximRouiller** [comment]
`otnet-razor-tooling`? :stuck_out_tongue_winking_eye:

**Comment by mikes-gh** [comment]
@natemcmaster  @Bartmax 
I think dotnet-razor-tooling is for Razor intellisense for TagHelpers to be precise.

@NTaylorMullen 
>FYI:  dotnet-razor-tooling  is only for  TagHelper  IntelliSense.

It would be good to clarify that on readme.md for razor tooling

Its also a bit behind on this rename and currently broken on ci build.

**Comment by moozzyk** [comment]
The table contains status of the rename. `dotnet-razor-tooling` and `dotnet-aspnet-codegenerator` renames are still in progress.

**Comment by MaximRouiller** [comment]
@moozzyk I was more highlighting the typo. :smiley:

**Comment by moozzyk** [comment]
@MaximRouiller - I commented on @mikes-gh response and fixed the typo you pointed out to.

**Comment by mikes-gh** [comment]
@moozzyk  sorry saw that now hidden on iPad layout.  I guess tables aren't responsive github

**Comment by dodyg** [comment]
I got this error

```tools must specify a version range```

for this

```
"tools": {
  "Microsoft.EntityFrameworkCore.Tools": {
    "version": "1.0.0-*",
    "imports": "portable-net451+win8"
  }
},
"dependencies": {
  "Microsoft.EntityFrameworkCore.Tools": {
    "version": "1.0.0-*",
    "type": "build"
  }
}

```

**Comment by MaximRouiller** [comment]
Related? https://github.com/dotnet/coreclr/issues/3776

**Comment by moozzyk** [comment]
@dodyg - haven't seen this. Can you provide more context? When/Where does this error happen? Is it during restore? Also what version of dotnet are you using?

**Comment by dodyg** [comment]
Year it was during ```dotnet restore```. The problem goes away now. I don't really know what happened.

I am using 

```
.NET Command Line Tools (1.0.0-rc2-002498)

Product Information:
 Version:     1.0.0-rc2-002498
 Commit Sha:  55e561bfb3

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by moozzyk** [comment]
This https://github.com/NuGet/NuGet.Client/blob/d74b04c1bdd3a6bb14b0ba6edd319e9c839c6eae/test/NuGet.Core.Tests/NuGet.ProjectModel.Test/PackageSpecReaderTests.cs#L203-L212 tells me that you in your project.json the tool did not have `version`. It wouldn't get away on its own though. If you see this again show your project.json file and I will try to repro.

**Comment by Bartmax** [comment]
@moozzyk as I understand (may be wrong), the IIS-publish-tool does not publish the app but it just generates/transform de web.config. (or any configuration needed for that matter).

Since you are already renaming, maybe you can think of a better name that better describe the tool intention, I read on jabbr people trying to use that to actually publish and got quite confused when they use the `iis-publish-tool` to create a web.config and then using `dotnet publish` for the actual publish. 

The current name also indicates that I must have this tool to publish to iis, which is not true and if the name was `iis-configuration` or iis-config-manager` will be much clear.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
