### ISSUE TITLE
Error running from Docker: Project app does not have a lock file

### ISSUE THREAD

**Issue by tonysneed** [aspnet/Home#1412]
I've created a dockerfile based on microsoft/dotnet-preview which runs `dotnet restore` to generate a _project.lock.json_ file.  But running the container results in an error: **Project app does not have a lock file**.

As a workaround, I can change the ownership of _project.lock.json_, but the side-effect is that I am unable to mount a host volume, because doing so invalidates the `chown` command. Here is my [Dockerfile](https://github.com/tonysneed/Demo.DotNetCoreDocker/blob/master/Dockerfile#L1-2).

I appreciate if anyone is able to shed light on why this error may be taking place.

**Comment by tonysneed** [comment]
FYI, I posted a question regarding this issue on the [docker hub page](https://hub.docker.com/r/microsoft/dotnet-preview/) for the *microsoft/dotnet-preview* image.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
