### ISSUE TITLE
Configuration and TFM as variable for scripts in project.json

### ISSUE THREAD

**Issue by Tasteful** [aspnet/Home#1413]
Hi.

I have some scripts as a process before the nupkg is created. Is there some way to provide the `configuration` (Debug/Release) and `TFM` as variable into script?

My script today is calling a powershell script that handling authenticode signing and to be able to only trigger the script if the build is in `Release` configuration.

Using DNX for compilation, maybe this is fixed in dotnet-cli
```
  "scripts": {
    "postbuild": [
      "powershell -ExecutionPolicy unrestricted -Command %project:Directory%\\..\\sign.ps1 -ProjectName %project:Name% -ProjectVersion %Project:Version% "
    ]
  }
```

**Comment by moozzyk** [comment]
In dotnet cli the `precompile` and `postcompile` scripts take these parameters: https://github.com/dotnet/cli/blob/563f6497fd0842d150cd717a47089ba4e0944b19/src/dotnet/commands/dotnet-compile/ManagedCompiler.cs#L163-L168 . You either want `compile:TargetFramework` or `compile:TargetFullFramework`

**Comment by Tasteful** [comment]
@moozzyk, Do you know if this environment will change name to have `_` instead of the `:`?

@DamianEdwards was talking about change like that between RC1 and RC2; example the https://github.com/aspnet/live.asp.net/compare/rc2#diff-c2b1efdb2ad80c688e082eb2292002b9L16

**Comment by moozzyk** [comment]
You can as in the https://github.com/dotnet/cli repo but my guess is it won't change.
