### ISSUE TITLE
Anyone able to debug MVC 6 published to Azure

### ISSUE THREAD

**Issue by Tgueth** [aspnet/Home#1415]
I have finished most of the work converting a MVC 5 app to MVC 6 RC1 (although I suspect from reading that I am looking at a lot of work to get to RC2).  I published the app to Azure but am having issues with the startup (runs but doesn't appear to get correct data). I need to debug the app but have tried everything found via google and Bing and am unable to debug the app on Azure via VS2015.  

I have created just a basic ASP.NET 5 MVC 6 app without login capability and published it to Azure with same issue.  Basically, I get a DCOM error when I attempt to attach manually.  And I use the right-click to attach and debug, the source code (I assume the PDB) is apparently not found as the red dots change red outlined circle with white center, usually significantly a wrong version or missing code.

I have checked and I can debug the MVC5 version noted above on Azure, just not MVC 6.

So questions are:

1) Is there a documented step by step process that works?  All links I have found all fail.

2) Or do I have to revert to adding more logging to the log file to attempt to identify the cause of the problem?

**Comment by plouveau** [comment]
I published recently a landing page for my company using MVC6 RC1 (If you want to see it live : [https://pickapack.fr](https://pickapack.fr)). First, I deploy to Azure using the publish wizard and then, I simply attach the debugger with the cloud explorer (in VS2015) by selecting the target web application and then click debug. 
I'm using the same method to debug web jobs and it's works perfectly.
