### ISSUE TITLE
AspNet.Mvc in dotnet5.4 class library

### ISSUE THREAD

**Issue by Sebosek** [aspnet/Home#1416]
Hello,

I've created class library where I have extension methods for `ILoggerFactory`, `IApplicationBuilder` and `IServiceCollection`, so I need to add package `"Microsoft.AspNet.Mvc": "6.0.0-rc1-final"` in my `project.json`.
But when I try to run `dotnet restore` I got error:

```
error: Newtonsoft.Json 6.0.6 is not compatible with .NETPlatform,Version=v5.4.
error: Microsoft.CodeAnalysis.CSharp 1.1.0-rc1-20151109-01 is not compatible with .NETPlatform,Version=v5.4.
error: Microsoft.CodeAnalysis.Common 1.1.0-rc1-20151109-01 is not compatible with .NETPlatform,Version=v5.4.
error: Some packages are not compatible with .NETPlatform,Version=v5.4.
```

Is there any workaround or how can I fix this?

Here is my project.json

```
{
  "version": "1.0.0-*",
  "description": "Logger Class Library",
  "authors": [ "Sebastian Bušek" ],
  "tags": [ ],
  "projectUrl": "",
  "licenseUrl": "",

  "dependencies": {
  },

  "frameworks": {
    "dotnet5.4": {
      "compilationOptions": {
        "define": [ "DOTNET5_4" ]
      },
      "dependencies": {
        "CommonTools": "1.0.16118.80",
        "Microsoft.NETCore.Platforms": "1.0.0",
        "Microsoft.Extensions.Logging.Abstractions": "1.0.0-rc1-final",
        "Microsoft.AspNet.Mvc": "6.0.0-rc1-final",
        "NLog": "4.4.0-beta4",
        "System.Collections": "4.0.11-beta-23516",
        "System.IO": "4.0.11-beta-23516",
        "System.Linq": "4.0.1-beta-23516",
        "System.Runtime": "4.0.21-beta-23516",
        "System.Runtime.Extensions": "4.0.11-beta-23516",
        "System.Threading": "4.0.11-beta-23516"
      }
    }
  }
}
```

**Comment by Sebosek** [comment]
Nobody faced to same problem?

**Comment by GuardRex** [comment]
@Sebosek You're mixing RC1 and RC2 packages ... and it looks like you have a number of RC1 packages in there. Go for packages on the RC2 stabilization feed, which is the CI Release feed: https://www.myget.org/gallery/aspnetcirelease and use a `NuGet.config` with that feed ...
```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <clear />
    <add key="AspNetCI" value="https://www.myget.org/F/aspnetcirelease/api/v3/index.json" />
    <add key="NuGet.org" value="https://api.nuget.org/v3/index.json" />
  </packageSources>
</configuration>
```
Also, `compilationOptions` is `buildOptions` now. See: https://github.com/aspnet/Announcements/issues/175

**Comment by Sebosek** [comment]
@GuardRex Thank you for reply; our primary release is RC1 (update2), so let me ask: is there any kind of list, where can I find what version is for given release? Or should I try -> run and hope for best? :)

**Comment by GuardRex** [comment]
@Sebosek In that case, you'll have to stick with DNX. `dotnet cli` is a purely RC2-ish thingy. It's completely incompat with DNX (RC1 bits). There is no list, per se. However, most of the packages you have are presumably DNX/RC1-friendly, since you were probably just compiling that lib with DNX.

It's the `Microsoft.NETCore.Platforms` that you'll need to drop AFAICT. Ignore what I said about `compilationOptions`, as that is the correct name for RC1. Then, stick with `rc1-update2` DNX runtimes, `dnu`, and `dnvm` until you are ready to make the move to RC2.

After you go RC2, all that DNX stuff is :skull: dead :skull:.

There will be a migration doc to help when you're updating for RC2, and you'll have the Announcements for RC2 to rundown: https://github.com/aspnet/Announcements/issues?q=is%3Aopen+is%3Aissue+milestone%3A1.0.0-rc2

**Comment by rynowak** [comment]
> I've created class library where I have extension methods for ILoggerFactory, IApplicationBuilder and IServiceCollection, so I need to add package "Microsoft.AspNet.Mvc": "6.0.0-rc1-final" in my project.json.

None of these types are defined by MVC - you should be able to get by with references to Http DI and Logging Abstractions packages

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
