### ISSUE TITLE
Expose http.sys functionality via WebListener

### ISSUE THREAD

**Issue by pavel12345** [aspnet/Home#1417]
There are two features of the http.sys driver that may help in a self-hosted setup: 

1 - Manually set the http.sys queue name for the application. This helps detect potential application-level problems by monitoring the queue-length counter.

2 - Ability to write http.sys logs for all requests. (Available via the PHTTP_LOG_DATA parameter in the HttpSendHttpResponse of the HTTP Server API.)

Are either of these use-cases supported? Will they be?

**Comment by Tratcher** [comment]
These features aren't supported at the moment. I'll move this request to the WebListener repo and we can triage it there. Note we aren't doing significant feature work for WebListener until after v1.0
