### ISSUE TITLE
Can we have one chat channel?

### ISSUE THREAD

**Issue by tugberkugurlu** [aspnet/Home#1420]
Today, we have Jabbr, Slack and Gitter chat channels for ASP.NET Core. Can we have only one? Home repo has gitter on its readme but it's spreaded to multiple places now. Would be really good to have an effort to unify this. We only had jabbr before and it was very straight forward.

My vote would be for Slack that @spboyer organized as its mobile client, search and integrations are really good.

**Comment by justinhhorner** [comment]
+1 for a single chat channel using Slack.

**Comment by spboyer** [comment]
Here is the post with the info and sign up: http://tattoocoder.com/asp-net-core-slack-community/

**Comment by spboyer** [comment]
Official signup page for the channel - http://tattoocoder.com/aspnet-slack-sign-up/

**Comment by GuardRex** [comment]
@tugberkugurlu It's nice to have different forums that have different features, but I hear you on the idea of one being the sort of "official" chat.

There are aspects of both Gitter and Slack that are both better and worse than JabbR IMO; and after using all three, I still like JabbR the best.

JabbR is on life support :hospital: right now, but there is a discussion among community members on coming together on a JabbR v2 initiative to replace it that would be community-maintained. I'd just like to see that play out before the :pray: server gods :pray: pull the plug.

**Comment by Eilon** [comment]
A lot of good ideas and discussions here - we'd hopefully like to focus most discussions in a more limited number of channels. Right now we have GitHub, Gitter, JabbR, Slack, even StackOverflow, and no doubt other places.

**Comment by GuardRex** [comment]
There's a low-level discussion among devs regarding JabbR v2, probably because some of us feel JabbR is a superior chat experience. It needs a little more cowbell (e.g., room reference link lists, pinned items, shared files), but the JabbR UI ... the layout and features there ... that's **pure genius**. Of course, it's badly broken right now, but that stuff can be fixed.

The discussion for JabbR v2 will start this evening at the JabbR repo in an issue that I'm going to open; hopefully, other devs will chime in on it. I'll post the link back here later today. If the :pray: server gods :pray: make a ruling against it, then please just tell us so that we don't waste our time discussing it further.

cc/ @PinpointTownes

**Comment by benaadams** [comment]
GitHub and SO itself are different beasts as they are more focused in their purpose than community/chat. 

SO does have their C# chat http://chat.stackoverflow.com/rooms/info/7/cv
Jabbr is painful atm with 3min+ to post a message and broken history.
Gitter on aspnet/home 370 users atm; but is repo split
Slack has 1010 users atm, and has more flexibility than per repo

**Comment by tugberkugurlu** [comment]
As long as I have web and mobile client (iPhone), can have a link for a message to refer to it, can have an advanced search accross channels (and with filters), can manage notifications in a good way, private message to people, open up new channels, I am all OK with any option.

However, Slack already does these and is widely used. So, lots of ppl would have muscle memory while using it. On my mobile client, I have three slack teams today and I can switch between them in an amazingly simple way. 

I just assume that Slack would save a lot of time and effort.

**Comment by PinpointTownes** [comment]
I agree with @GuardRex: JabbR offers a much better experience than the other options, despite its recent issues (specially the terrible lags). Slack is not fundamentally bad, but it feels "less interactive" than JabbR, and switching between teams (#aspnet-core and #JabbR) is a real PITA.

My 2 cents: don't kill JabbR before discovering what's causing the recent lags. It's a great realtime chat and an incredible showcase for SignalR.
