### ISSUE TITLE
Project.json's "copyToOutput" isn't transitive

### ISSUE THREAD

**Issue by DavidObando** [aspnet/Home#1423]
Is this by design?

### Repro
Have `ProjectA` which defines a `"copyToOutput"` element within its `"buildOptions"` section in `project.json`. When compiled, the file or files in the `"include"` section will be copied to the output, along with `ProjectA.dll`.
**ProjectA**
project.json _("include": ["ProgramA.cs"] is just as an example)_
```
{
  "version": "1.0.0-*",
  "buildOptions": {
    "emitEntryPoint": true,
    "copyToOutput": {
      "include": ["ProgramA.cs"]
    }
  },
  "dependencies": {
    "Microsoft.NETCore.App": {
      "type": "platform",
      "version": "1.0.0-*"
    }
  },
  "frameworks": {
    "netcoreapp1.0": {
      "imports": "dnxcore50"
    }
  }
}
```
ProgramA.cs
```C#
using System;
namespace ProjectA
{
    public class ClassFromProjectA
    {
        public int Value { get; set; } = 3;
    }
}
```

Now, have `ProjectB` which includes `ProjectA` as a reference. When compiled, it will produce `ProjectB.dll` as well as `ProjectA.dll` in the output directory.
**ProjectB**
project.json
```
{
  "version": "1.0.0-*",
  "buildOptions": {
    "emitEntryPoint": true
  },
  "dependencies": {
    "ProjectA": "1.0.0-*",
    "Microsoft.NETCore.App": {
      "type": "platform",
      "version": "1.0.0-*"
    }
  },
  "frameworks": {
    "netcoreapp1.0": {
      "imports": "dnxcore50"
    }
  }
}
```
ProgramB.cs
```C#
using System;
using ProjectA;
namespace ProjectB
{
    public class ProgramB
    {
        public static void Main(string[] args)
        {
            var r = new ClassFromProjectA();
            Console.WriteLine($"Value from ProjectA {r.Value}");
        }
    }
}
```

### Observed
The files included by the `"copyToOutput"` element of `ProjectA` will not be copied to the output of `ProjectB`. The files will only be copied to the output when the root project is the one specifying the `"copyToOutput"` element, and it will only work on the files included by the root project.

### Expected
The files specified by the `"copyToOutput"` element of `ProjectA` show up in the output directory of `ProjectB`.

**Comment by davidfowl** [comment]
Not by design. File this issue on the cli.

**Comment by DavidObando** [comment]
Meant to do that, not sure why I didn't haha.

**Comment by DavidObando** [comment]
dotnet/cli#2902
