### ISSUE TITLE
Templates not installing correctly rc1 update 1

### ISSUE THREAD

**Issue by acd3m4** [aspnet/Home#1424]
I cannot get the core 1.0 templates to load correctly both in a new solution and when I try to open a sample core 1.0 solution. I currently have Microsoft ASP.Net 5 RC1 Update 1 installed. I am using Visual Studio 2015 Enterprise edition Update 2 with pretty much all the features installed. I have tried repairing visual studio, and also tried reinstalling visual studio with just Visual Studio Community Edition. When I try to add an ASP.Net 5 Core 1.0 project to a .Net solution I get the following error:

"The template specified cannot be found. Please check that the full path is correct."

When I try to open a solution with an ASP.Net 5 project inside of it I get the following error: "Incompatible"

Finally, if I try to remove the project and re-add it through add existing project I get the error message:
"The project system has encountered an error.  There is no project properties provider for "Persistence = DnxDynamic".  A diagnostic log has been written to the following location: " 

See attached stack trace.

[VsProjectFault_a4d89b87-7ab4-4c05-b610-aa32f7e43397.failure.txt](https://github.com/aspnet/Home/files/250560/VsProjectFault_a4d89b87-7ab4-4c05-b610-aa32f7e43397.failure.txt)

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
