### ISSUE TITLE
FileExtensionContentTypeProvider

### ISSUE THREAD

**Issue by Bartmax** [aspnet/Home#1425]
It feels weird that the [FileExtensionContentTypeProvider](https://github.com/aspnet/StaticFiles/blob/dev/src/Microsoft.AspNetCore.StaticFiles/FileExtensionContentTypeProvider.cs) is on the StaticFiles middleware.

Shouldn't be somewhere more accesible ?
I think there are multiple situations where one may want to work with that provider outside of static files.

Just a thought.

**Comment by Tratcher** [comment]
What examples did you have in mind?

**Comment by Bartmax** [comment]
File uploads and detect content-type. (not particular involved in serving them)

A middleware that does something based on content type, for example a middleware FileServer-like on a subset of content-types(images) that Resize based on request query string/params 

An app that copy files from storage services (like azure blog storage). So you can use the FECTP to save the correct content type.

If tomorrow, a ByteHeaderContentTypeProvider is created and used on other middleware, like the FileUploadExtensionBlocker, does it make sense to make it on that middleware?

I don't know, content-type mapping is way separate from a static files middleware from my pov. It doesn't feel (gut-feeling) like a good place. I just wanted to let you know, maybe it IS the right thing.

**Comment by Tratcher** [comment]
Those are some interesting ideas, but none of them are on our roadmap. There's also no obvious alternative home for it right now. We can move it later and type-redirect if we need to.

**Comment by smbecker** [comment]
I would think the obvious home to be [aspnet/FileSystem](https://github.com/aspnet/FileSystem). I can certainly see the value of having this type available outside of StaticFiles.

**Comment by Tratcher** [comment]
FileSystem doesn't know anything about mime-types, or HTTP for that matter.

**Comment by Bartmax** [comment]
@Tratcher isn't usefull that FileSystem knows about mime-types? just asking.

**Comment by Tratcher** [comment]
Mime types are a HTTP concept (more or less), where Microsoft.Extensions.FileProviders is a much lower level component that operates independent of the HTTP stack.

**Comment by NenessNC** [comment]
I think [aspnet/HttpAbstractions](https://github.com/aspnet/HttpAbstractions) would be a good place since it is more global HTTP concern.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
