### ISSUE TITLE
Consider adding back an explicit net45 TFM in the Microsoft.Extensions projects to make them compatible with Visual Studio 2013

### ISSUE THREAD

**Issue by PinpointTownes** [aspnet/Home#1427]
With the introduction of the new .NET Standard platform, many of the `Microsoft.Extensions` projects have been re-targeted to use `netstandard1.0`/`netstandard1.1`/`netstandard1.2` instead of `dotnet` + `net45`/`net451`.

Sadly, this major change seems to break the Visual Studio 2013 users relying directly or indirectly on these packages, as NuGet 2.x doesn't support the new TFMs (yet?).

![image](https://cloud.githubusercontent.com/assets/6998306/15064401/380e4fb6-1354-11e6-9997-0d995d8b4e09.png)

/cc @davidfowl @Eilon @muratg 

FYI @bricelam @natemcmaster, as this change will likely make EF Core RC2 unusable with <VS 2015.

**Comment by muratg** [comment]
cc @divega

**Comment by divega** [comment]
@davidfowl says in the conversation that the TFM and compatibility rules will be added in NuGet 2.8. Isn't that what is needed for the new packages to work in downlevel VS? What am I missing?

**Comment by divega** [comment]
I guess the question is whether the packages not working in downlevel VS for the RC2 timeframe is an acceptable compromise. I think it is not ideal but given how deep the changes would need to go in the packages to fix this for RC2, I am not sure we have another option.

cc @rowanmiller @yishaigalatzer

**Comment by PinpointTownes** [comment]
> I guess the question is whether the packages not working in downlevel VS for the RC2 timeframe is an acceptable compromise.

Yep, that's the real question. FWIW, I've started warning ASOS users (https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server) that they wouldn't be able to use the OWIN/Katana version with <VS 2015 due to this change and recommended to keep using the current version.

> I think it is not ideal but given how deep the changes would need to go in the packages to fix this for RC2

While bringing back `net45`/`net451` would affect a few repositories (https://github.com/search?q=Target+minimal+TFM+user%3Aaspnet&type=Issues&utf8=%E2%9C%93), the change itself is quite simple, and a similar one was already taken to make them work on `netcore50`.

I guess it would help if we had a more precise idea on when the `netstandard` support is going to be backported to NuGet 2.x.

**Comment by yishaigalatzer** [comment]
We are working in supporting netstandard in 2013/2012 now. Work is starting to show up in pull requests. We expect to release nuget 2 with netstandard support hopefully in June, but we will drop privates before on the issues tracking it as part of the 2.12 milestone

**Comment by PinpointTownes** [comment]
In this case, it's probably not worth updating the `Microsoft.Extensions` packages at this point. Thanks for the details :clap:

**Comment by Eilon** [comment]
Parking this in the 1.0.0 milestone for now. Unfortunately it's pretty much too late for RC2 at this point unless it's a critical ship-stopper.

**Comment by Eilon** [comment]
Oh wait this is Home repo, no milestones here. Well then we'll just sit on it for a while then.

**Comment by PinpointTownes** [comment]
@Eilon yeah, since this "change" would potentially impact multiple repos, I thought "Home" was a good place for that :smile:

**Comment by Eilon** [comment]
Yeah Home is a good place for this 😄

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
