### ISSUE TITLE
Add System.Runtime.CompilerServices.Unsafe to feed

### ISSUE THREAD

**Issue by benaadams** [aspnet/Home#1428]
Isn't currently present in `https://www.myget.org/gallery/aspnetcidev` feed

Has improvements https://github.com/aspnet/KestrelHttpServer/pull/804#issuecomment-217526770

**Comment by pranavkm** [comment]
@benaadams might take a bit. They don't have a rc3 \ preview2 build of the CLI \ shared platform as yet so we have been putting off picking up RC3 corefx packages for a bit.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
