### ISSUE TITLE
project.json documentation is outdated

### ISSUE THREAD

**Issue by mixerp** [aspnet/Home#1430]
Dear All,

The documentation

https://github.com/aspnet/Home/wiki/Project.json-file

is no longer correct. It appears top in search results and creates confusion for beginners.

BTW, I was looking for a way to exclude an entire directory from being compiled, but no avail!

**Comment by GuardRex** [comment]
@mixerp You want `compile > exclude`. See https://github.com/aspnet/Announcements/issues/175

**Comment by PinpointTownes** [comment]
@Eilon on a related note, @davidfowl said there was a magic script helping with the  migrating of `project.json` to the new schema. Is this a tool you can publicly share? :smile:

**Comment by Eilon** [comment]
@PinpointTownes hmm first I've heard of this tool.

@ajaybhargavb / @davidfowl ?

**Comment by ajaybhargavb** [comment]
@pranavkm ?

**Comment by pranavkm** [comment]
I can try cleaning up the script I ran on the AspNet repos.

**Comment by PinpointTownes** [comment]
@pranavkm that would be great, thanks! :smile: 

Don't worry if it's "quick and dirty" quality. It will still be better manually editing all the aspnet-contrib projects :smile:

**Comment by pranavkm** [comment]
@PinpointTownes here - https://github.com/pranavkm/FixProjectJsonWarnings. It misses a few options (`excludes` I think was one of them) but should cover most warnings.

**Comment by PinpointTownes** [comment]
@pranavkm thanks for the precious tool, it was really helpful :clap:

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
