### ISSUE TITLE
dnvm and dnu command not found in git bash 

### ISSUE THREAD

**Issue by hingsir** [aspnet/Home#1434]

**Comment by GuardRex** [comment]
@hingsir DNX, dnvm, dnu :skull: dead and buried :skull:. Everything is `dotnet cli` now, and RC2 is due to release in the coming days. See the cli repo to get started, but RC2 docs won't hit until RC2 comes out. https://github.com/dotnet/cli/tree/rel/1.0.0

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
