### ISSUE TITLE
Is there any way to configure "compileExclude" or "exclude" for a target framework in project.json

### ISSUE THREAD

**Issue by nhathongly** [aspnet/Home#1435]
My project has some target frameworks, but there are some files that can't be built for CoreCLR. So I want to exclude those files from compilation once the target is dotnet5.5 or dnxcore50. Is there is any to accomplish it. 
Adding

`"buildOptions": {
        "compile": {
          "exclude": "XmlConfiguration/*.*"
        }
      }`
to dotnet5.5 and dnxcore50 seems not working

**Comment by davidfowl** [comment]
It's not supported

**Comment by moozzyk** [comment]
You can probably #ifdef out the entire file content.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
