### ISSUE TITLE
Help required for building MVC project in VS 2015

### ISSUE THREAD

**Issue by codingonHP** [aspnet/Home#1437]
I have downloaded the MVC project and tried building it using VS 2015. It always fails to restore the packages and doesn't build.
Is there any specific way to build it. Is there any article or resouce that can help me build ?

**Comment by GuardRex** [comment]
@codingonHP The updated tooling to make VS work with RC2 isn't out yet. We are expecting RC2 to release next week with updated tooling. Until then, use the command line or use VS Code. You can get more info at the cli repo (besides the ReadMe, checkout the Docs folder) ... https://github.com/dotnet/cli/tree/rel/1.0.0, and I posted some links to help devs with RC2 issues and RC1-to-RC2 conversions at https://github.com/dotnet/cli/issues/2135#issuecomment-212692267. If you run into problems, hit up the devs on one of the chats: Gitter at https://gitter.im/dotnet/home, Slack at https://aspnetcoreslack.herokuapp.com/, or Slack at http://jabbr-slack.azurewebsites.net/.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
