### ISSUE TITLE
High CPU usage from dnx.exe

### ISSUE THREAD

**Issue by ptodorov** [aspnet/Home#1438]
I'm running a ASP.NET website in IIS 10 using DNX version 1.0.0-rc1-update1 clr. I'm constantly getting high CPU usage, often reaching 100% for dnx.exe process even without making any requests to the server. I don't have any other background tasks running, so I assume the only work it does is listening for requests. Any idea what might cause that abnormal CPU usage?

**Comment by cwe1ss** [comment]
RC2 will be released in a few days and dnx will no longer be used there - so it might not be worth digging into this now. I'd suggest you do the update and check if this issue still exists in RC2.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
