### ISSUE TITLE
Where will the RC2 annoucement be placed?

### ISSUE THREAD

**Issue by rhires** [aspnet/Home#1439]
Knowing that it's "mid-May" but not an exact date, what page(s) should I watch for when RC2 becomes generally available? Where will the official announcement be?

**Comment by davidfowl** [comment]
Always here https://blogs.msdn.microsoft.com/webdev/

**Comment by rhires** [comment]
Thanks!

**Comment by MaximRouiller** [comment]
This week is RC2 week. Smells like freshly cooked bits. 

Just like mama used to make. Now let's get this out of the oven. We're starving. ;-)

**Comment by rhires** [comment]
Actually, I was wondering - why doesn't it also show up in the "Announcements" repo? Other, "smaller" things do, like breaking changes, but why not "it's official - RC2 is out!" ?? I don't monitor the blogs as much as the repos, and I certainly would see that one... :-)
