### ISSUE TITLE
How to in ASP.NET Core 1.0: /system.webServer/security/requestFiltering/requestLimits@maxQueryString 

### ISSUE THREAD

**Issue by aubergemediale** [aspnet/Home#1441]
How can request filtering be configured now, e.g. how to change the max query string length?

**Comment by imranbaloch** [comment]
AFAIK, If you host on IIS then it will work. Tested on Rc2.

**Comment by aubergemediale** [comment]
it should be configurable somehow within the project assets, so that it is included when you deploy it to some server, e.g. Azure. Will it still pull settings from a web.config file when deployed to IIS, e.g. the system.webserver settings? On IIS Express on localhost the web.config is ignored.

**Comment by imranbaloch** [comment]
If you create a Project the web.config will auto included. When you publish it will include your web.config changes in publish folder. You can think of it any IIS app but has a http handler that take the request from IIS https://github.com/aspnet/Mvc/blob/dev/samples/MvcSandbox/web.config#L5-L7

For detail check https://channel9.msdn.com/Events/Build/2016/B811

**Comment by GuardRex** [comment]
Yes, that's a slightly older file tho. The IISIntegration sample is kept a bit more up-to-date in regard to `web.config`. https://github.com/aspnet/IISIntegration/blob/dev/samples/IISSample/web.config

I did have the desire (and make the suggestion) to use Hidden Segments to protect app assets if the `web.config` file was ever accidentally renamed or removed from the deployment. That will be mentioned in the upcoming `Publishing to IIS` doc. However, here is an example for Hidden Segments from one of my self-contained test apps produced by my own flavor of the `publish-iis` tooling, and your mods to your `web.config` for Request Filtering will be similarly handled ...
```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <system.webServer>
    <handlers>
      <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModule" resourceType="Unspecified" />
    </handlers>
    <aspNetCore processPath=".\teststandalone.exe" stdoutLogEnabled="true" stdoutLogFile=".\logs\teststandalone" />
    <security>
      <requestFiltering>
        <hiddenSegments>
          <add segment="teststandalone.xml" />
          <add segment="teststandalone.deps.json" />
          <add segment="teststandalone.runtimeconfig.json" />
        </hiddenSegments>
      </requestFiltering>
    </security>
  </system.webServer>
</configuration>
```

**Comment by blowdart** [comment]
https://github.com/aspnet/KestrelHttpServer/issues/475

**Comment by gdoron** [comment]
@blowdart 
I tried configure the web.config, but it didn't help:

	<?xml version="1.0" encoding="utf-8"?>
	<configuration>
	  <system.webServer>
	    <security>
	      <requestFiltering>
	        <requestLimits>
	          <headerLimits>
	            <add header="maxQueryString" sizeLimit="20480" />
	          </headerLimits>
	        </requestLimits>
	      </requestFiltering>
	    </security>
	    <handlers>
	      <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModule" resourceType="Unspecified"/>
	    </handlers>
	    <aspNetCore processPath="%LAUNCHER_PATH%" arguments="%LAUNCHER_ARGS%" stdoutLogEnabled="false" stdoutLogFile=".\logs\stdout" forwardWindowsAuthToken="false"/>
	  </system.webServer>
	</configuration>

Am I doing something wrong?
How can I increase the limit for maxQueryString?

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
