### ISSUE TITLE
Gulp tasks seen as error on VS.

### ISSUE THREAD

**Issue by Bartmax** [aspnet/Home#1443]
those gulp task are not an error, but VS show as errors and also (when publishing) it says on status bar: published failed, but app was published successfully 

![image](https://cloud.githubusercontent.com/assets/3386797/15289432/7aa4a090-1b48-11e6-9781-46bb938fde94.png)

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
