### ISSUE TITLE
Error on debugging my website

### ISSUE THREAD

**Issue by kermitfrosch** [aspnet/Home#1445]
Hallo,

when i debug my Website and set a breakpoint i can't watch my variables.
I got the error: 
error CS0103: The name 'model' does not exist in the current context    

See Picture attached.

How can i fix this.
thx

Jens
![error](https://cloud.githubusercontent.com/assets/5372968/15293468/5a0134b2-1b88-11e6-894c-27a7fb0568a0.png)

**Comment by Tratcher** [comment]
Is the code running as Release / optimized? Local variables like this may be removed by optimizations. Try running under Debug instead.

**Comment by moozzyk** [comment]
I think this is a bug in VS - see: http://stackoverflow.com/questions/36284093/visual-studio-2015-update-2-rtm-and-rc-debugging-context-not-available

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
