### ISSUE TITLE
Error AddMVC RC2

### ISSUE THREAD

**Issue by ngonzalezromero** [aspnet/Home#1452]
I have this error

The call is ambiguous between the following methods or properties: 

'Microsoft.Extensions.DependencyInjection.MvcServiceCollectionExtensions.AddMvc(Microsoft.Extensions.DependencyInjection.IServiceCollection)' and 'Microsoft.Extensions.DependencyInjection.MvcServiceCollectionExtensions.AddMvc(Microsoft.Extensions.DependencyInjection.IServiceCollection)'

in this line
```C#
          public void ConfigureServices(IServiceCollection services)
          {
            services.AddMvc();
        }
```

my project.json

```JSON
 {
    "configurations": {
        "Debug": {
            "buildOptions": {
                "define": [
                    "DEBUG"
                ]
            }
        },
        "Release": {
            "buildOptions": {
                "define": [
                    "RELEASE"
                ],
                "optimize": true
            }
        }
    },
    "version": "1.0.0-*",
    "buildOptions": {
        "emitEntryPoint": true,
        "preserveCompilationContext": true
    },
    "dependencies": {
        "Microsoft.NETCore.App": {
            "version": "1.0.0-rc2-*",
            "type": "platform"
        },
        "Microsoft.AspNetCore.Authentication.Cookies": "1.0.0-rc2-final",
        "Microsoft.AspNetCore.Mvc": "1.0.0-rc2-final",
        "Microsoft.AspNetCore.Mvc.TagHelpers": "1.0.0-rc2-final",
        "Microsoft.AspNetCore.Server.Kestrel": "1.0.0-rc2-final",
        "Microsoft.AspNetCore.StaticFiles": "1.0.0-rc2-final",
        "Microsoft.Extensions.Configuration.Json": "1.0.0-rc2-final",
        "Microsoft.Extensions.Logging": "1.0.0-rc2-final",
        "Microsoft.Extensions.Logging.Console": "1.0.0-rc2-final",
        "Microsoft.Extensions.Logging.Debug": "1.0.0-rc2-final",
        "Management.Domain": "1.0.0-*",
        "Management.Infrastructure": "1.0.0-*",
        "Management.Service": "1.0.0-*",
        "Ngonzalez.Util": "1.2.1",
        "Microsoft.AspNetCore.Razor.Tools": {
            "version": "1.0.0-preview1-final",
            "type": "build"
        }
    },
    "commands": {
        "kestrel": "Microsoft.AspNet.Hosting --server Microsoft.AspNet.Server.Kestrel --server.urls http://*:56056    --ASPNET_ENV PRODUCTION",
        "devkestrel": "Microsoft.AspNet.Hosting --server Microsoft.AspNet.Server.Kestrel --server.urls http://*:56057 --ASPNET_ENV DEVELOPMENT"
    },
    "frameworks": {
        "netcoreapp1.0": {
            "imports": [
                "dotnet5.6",
                "dnxcore50",
                "portable-net45+win8"
            ]
        }
    },
    "runtimeOptions": {
        "gcServer": true
    }
   
    
}
```

Regards

**Comment by davidfowl** [comment]
Do you have anything pulling in older RC1 packages?

**Comment by ngonzalezromero** [comment]
@davidfowl  yes, I have a own dll ("Ngonzalez.Util": "1.2.1") which target to RC1.
i'm trying to migrate to RC2, but i have several problems. in the framework section, which is the way to target to both framework (.net and .net core)?
I have this
`
    "dependencies": { 
    "Microsoft.Extensions.Logging": "1.0.0-rc2-final",
    "Microsoft.Extensions.Caching.Memory": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Hosting": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Mvc": "1.0.0-rc2-final",
    "Ngonzalez.HtmlAgilityPack": "1.0.0"
    },

 "frameworks": {
    "netstandard1.5": {
      "imports": "dnxcore50,dotnet5.6"
    }
  }
`


but the compiler throw the follow message
The dependency Newtonsoft.Json 8.0.3 does not support framework .NETStandard,Version=v1.5.	Ngonzalez.Util	Z:\Documentos\Proyectos\ngonzalez.util\Ngonzalez.Util\project.json

**Comment by pranavkm** [comment]
@ngonzalezromero the `imports` node is either a single valued string or an array of strings. Your `imports` node needs to look like: `"imports": [ "dnxcore50", "dotnet5.6"]`

**Comment by ngonzalezromero** [comment]
@pranavkm  Thank you .. works fine..
please the last question... i have the follow method

            public string Decrypt(string encryptStr)
             {
             byte[] bKey = Encoding.UTF8.GetBytes(PrivateKey);
             byte[] bIV = Encoding.UTF8.GetBytes(IV);
             byte[] byteArray = Convert.FromBase64String(encryptStr);

            string decrypt = null;

            #if dnxcore50
              var aes = System.Security.Cryptography.Aes.Create();
            #else
             var aes = Rijndael.Create();
            #endif
            try
            {
                using (MemoryStream mStream = new MemoryStream())
                {
                    using (CryptoStream cStream = new CryptoStream(mStream, aes.CreateDecryptor(bKey, bIV), CryptoStreamMode.Write))
                    {
                        cStream.Write(byteArray, 0, byteArray.Length);
                        cStream.FlushFinalBlock();
                        decrypt = Encoding.UTF8.GetString(mStream.ToArray(), 0, mStream.ToArray().Count());
                    }
                }
            }
            catch { }
            #if !DNXCORE50
              aes.Clear();
            #endif

            return decrypt;
        }


but this line

 `var aes = Rijndael.Create();`

throws the follow error 
`	The name 'Rijndael' does not exist in the current context	Ngonzalez.Util..NETStandard,Version=v1.5	
`
 Regards

**Comment by pranavkm** [comment]
Your `#ifdef needs to change:

```
#if dnxcore50
  var aes = System.Security.Cryptography.Aes.Create();
#else
 var aes = Rijndael.Create();
#endif
```

-> 

`var aes = System.Security.Cryptography.Aes.Create();` since you only have one target framework in your project.json

**Comment by ngonzalezromero** [comment]
but how can i target to both framework (full and net core)?
because in RC1 i had the follows imports
`
        "frameworks": {
            "dnx451": {
            "frameworkAssemblies": {
           "System.Net.Http": "4.0.0.0"
           }
        },

    "dnxcore50": {
      "dependencies": {
        "Microsoft.CSharp": "4.0.1-*",
        "System.Collections": "4.0.11-*",
        "System.Linq": "4.0.1-*",
        "System.Runtime": "4.0.21-*",
        "System.Threading": "4.0.11-*",
        "System.Threading.Thread": "4.0.0-*",
        "System.Security.Cryptography.RandomNumberGenerator": "4.0.0-*",
        "System.Net.Http": "4.0.0-*"
      }
    }
`
and works perfectly.
Please let me know how can i migrate my RC1 imports to RC2

**Comment by pranavkm** [comment]
@ngonzalezromero the project.json you pasted in your comment listed one TFM (`netstandard1.5`). If you're cross compiling for `netstandard1.5` and `net451`, your `#ifdef` would 
have to change to reflect the TFMs you're currently compiling:

```
#if NETSTANDARD1_5
  var aes = System.Security.Cryptography.Aes.Create();
#else
 var aes = Rijndael.Create();
#endif
```

**Comment by ngonzalezromero** [comment]
@pranavkm  so this import is correct

 `   
  "frameworks": {
    "netcoreapp1.0": {
      "imports": [ "dnxcore50", "dotnet5.6" ],
      "dependencies": {
       
      }
    },
    "net451": {
      "imports": [ "dotnet5.6" ],
      "dependencies": {
      }
    }
  }
`

**Comment by pranavkm** [comment]
Reformatted your comment - https://github.com/aspnet/Home/issues/1452#issuecomment-219870769. `net451` should not have any imports.

**Comment by ngonzalezromero** [comment]
ok.. finally my project compile

`
"frameworks": {
    "net451": {
      "frameworkAssemblies": {
        "System.Xml": ""
      },
      "dependencies": {
        "System.Runtime": "4.1.0-rc2-24027"
      }
    },
    "netcoreapp1.0": {
      "dependencies": {
        "NETStandard.Library": "1.5.0-rc2-24027",
        "Microsoft.CSharp": "4.0.1-rc2-24027",
        "System.Xml.XPath.XDocument": "4.0.1-rc2-24027",
        "System.Xml.XmlDocument": "4.0.1-rc2-24027",
        "System.Xml.XDocument": "4.0.11-rc2-24027",
        "System.Xml.ReaderWriter": "4.0.11-rc2-24027",
        "System.Xml.XPath.XmlDocument": "4.0.1-rc2-23629",
        "System.Xml.XPath": "4.0.1-rc2-24027",
        "System.Xml.XmlSerializer": "4.0.11-rc2-24027",
        "System.Linq": "4.1.0-rc2-24027",
        "System.Collections": "4.0.11-rc2-24027",
        "System.Threading": "4.0.11-rc2-24027"
      },
      "imports": "dnxcore50"
    }
  }`

Thank you very much

**Comment by lopezleandro03** [comment]
Hi All,
I am facing same issue:

The call is ambiguous between the following methods or properties:

'Microsoft.Extensions.DependencyInjection.MvcServiceCollectionExtensions.AddMvc(Microsoft.Extensions.DependencyInjection.IServiceCollection)' and 'Microsoft.Extensions.DependencyInjection.MvcServiceCollectionExtensions.AddMvc(Microsoft.Extensions.DependencyInjection.IServiceCollection)'

Cannot identified which could be the reference causing this...
Can you please help me? This is my project.json:

{
  "dependencies": {
    "EntityFramework": "6.0.0",
    "Microsoft.AspNetCore.Diagnostics": "1.0.0",
    "Microsoft.AspNetCore.Mvc": "1.0.0",
    "Microsoft.AspNetCore.Razor.Tools": {
      "version": "1.0.0-preview2-final",
      "type": "build"
    },
    "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0",
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.0",
    "Microsoft.AspNetCore.StaticFiles": "1.0.0",
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.0.0",
    "Microsoft.Extensions.Configuration.Json": "1.0.0",
    "Microsoft.Extensions.Logging": "1.0.0",
    "Microsoft.Extensions.Logging.Console": "1.0.0",
    "Microsoft.Extensions.Logging.Debug": "1.0.0",
    "Microsoft.Extensions.Options.ConfigurationExtensions": "1.0.0",
    "Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.0.0"
  },

  "tools": {
    "BundlerMinifier.Core": "2.0.238",
    "Microsoft.AspNetCore.Razor.Tools": "1.0.0-preview2-final",
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.0.0-preview2-final"
  },

  "frameworks": {
    "net461": {
      "dependencies": {
        "EstudioCapra.Backend": {
          "target": "project"
        },
        "EstudioCapra.Entity": {
          "target": "project"
        },
        "EstudioCapra.Model": {
          "target": "project"
        }
      }
    }
  },

  "buildOptions": {
    "emitEntryPoint": true,
    "preserveCompilationContext": true
  },

  "publishOptions": {
    "include": [
      "wwwroot",
      "Views",
      "Areas/**/Views",
      "appsettings.json",
      "web.config"
    ]
  },

  "scripts": {
    "prepublish": [ "bower install", "dotnet bundle" ],
    "postpublish": [ "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%" ]
  }
}


Many thanks!

**Comment by davidfowl** [comment]
Look at your project dependencies, make sure they aren't referencing RC2 versions of things
