### ISSUE TITLE
ASP.NET Core Module download link

### ISSUE THREAD

**Issue by nil4** [aspnet/Home#1454]
The [RC2 VS tooling](https://blogs.msdn.microsoft.com/visualstudio/2016/05/16/announcing-updated-web-development-tools-for-asp-net-core-rc2/) installs ASP.NET Core Module v0.9.1965, while the download links in the [Announcements post](https://github.com/aspnet/IISIntegration/issues/105) still point to v0.8. 

Where can I find the installer for the latest ASP.NET Core Module to deploy to my server?

<hr/>

**Update**: after installing Preview 2 VS tooling, the ANCM MSI package can be found at _C:\Documents and Settings\All Users\Package Cache\{4ADC4F4A-2D55-442A-8655-FBF619F94A69}v1.0.1967\packages\aspnetcoremodule_x64_en_rc2_39.msi_. 

However, an official download link is still missing.

**Comment by joeloff** [comment]
The one that comes with the RC2 tooling is the latest. That being said, we do have a separate installer specifically for servers that only includes the .NET Core runtime and ASP.NET Core module

You can find the server install [here](https://go.microsoft.com/fwlink/?LinkId=798480)

**Comment by nil4** [comment]
Thank you @joeloff! I found that installer on the docs page but I don't want to install any of the .NET Core bits on my servers for now (I am targeting `net46`). I was looking for a standalone installer for ASP.NET Core Module only. 

In the meantime I found the `aspnetcoremodule_x64_en_rc2_14.msi` in my Package Cache folder and will use it to test further.

**Comment by muratg** [comment]
You can also download the server MSI from: https://www.microsoft.com/net/download.  Search for "**Windows (Server Hosting)**".

**Comment by GuardRex** [comment]
@nil4 I'm in a similar situation to you: All of my apps will be self-contained Core CLR apps, so I don't want the full hosting bundle. There is no standalone installer for ANCM. However, I've been told that they are thinking about offering such an installer just for the module and also that the ANCM is targeted for OSS; therefore, we will be able to compile our own module even if there is no ANCM-only installer.

As a workaround, you can move the module and schema manually to the server and make changes to `applicationHost.config` (manually or via PS). Not ideal, right? :smile: ... but it will work.

**Comment by nil4** [comment]
Definitely not ideal. There's a perfectly good installer for just the module already (search for `aspnetcoremodule_x64_en_rc2_14.msi` after you install the Preview1 tooling). It installs exactly what's needed: the IIS module and the schema. It's just bundled together with the .NET Core bits and it takes a bit of effort to fish it out. 

Would be nice to offer it as a separate download, and perhaps also update the Announcements issue to prevent people from downloading v0.8 by mistake (like I did) and wonder why it doesn't quite work.

**Comment by GuardRex** [comment]
> There's a perfectly good installer for just the module already (search for aspnetcoremodule_x64_en_rc2_14.msi

Great tip! Thanks for that. :smile: Does it mod the `applicationHost.config` as well?

**Comment by nil4** [comment]
Looks like it does. :clap:

**Comment by nil4** [comment]
Update: after installing Preview 2 VS tooling, the ANCM MSI package can be found at *C:\Documents and Settings\All Users\Package Cache\\{4ADC4F4A-2D55-442A-8655-FBF619F94A69}v1.0.1967\packages\aspnetcoremodule_x64_en_rc2_39.msi*

**Comment by GuardRex** [comment]
According to comments on the [Community Standup (7/5, 50:26)](http://www.youtube.com/watch?v=i4pLgQw6bRA&t=50m26s) there is a switch that can be provided to the hosting bundle installer on the command line that will result in only the ANCM module being installed. Unfortunately, @shanselman and @DamianEdwards didn't actually say what the switch was. :smile:

**Comment by joeloff** [comment]
When you download the EXE, you can run it from the commandline and pass OPT_INSTALL_REDIST=0. That will disable the .NET redist and only install ANCM

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
