### ISSUE TITLE
Cannot Create ASP.NET Core RC 2 web project in VS 2015

### ISSUE THREAD

**Issue by saurabhnandu** [aspnet/Home#1455]
Hi,

I just downloaded and installed the preview RC2 bits for ASP.NET Core on Visual Studio 2015 Community Edition. When I try to create a new ASP.NET Core web project I am getting the following error "The system cannot find the specified file" and the project is not created. I tried to repair the ASP.NET RC2 installer and still facing the same issue. I did not have RC1 bits installed on this machine. Not sure what to do to fix this. Thanks

![image](https://cloud.githubusercontent.com/assets/13586676/15322250/344742d0-1c59-11e6-9771-ac990213ddc2.png)

**Comment by muratg** [comment]
cc @sayedihashimi

**Comment by sayedihashimi** [comment]
Can you copy info from Help About in VS (there is a copy button on the dialog) and paste it here?

**Comment by joeloff** [comment]
Also, can you try the following:

1. Open a Visual Studio 2015 Developer Command Prompt
2. Run: devenv /log
3. Once the IDE is up an running, close VS and grab the ActivityLog.xml from %appdata%\Microsoft\VisualStudio\14.0\ActivityLog.xml and share that

**Comment by saurabhnandu** [comment]
The VS Help About Copy Below

Microsoft Visual Studio Community 2015
Version 14.0.25123.00 Update 2
Microsoft .NET Framework
Version 4.6.01569

Installed Version: Community

Visual Basic 2015   00322-20000-00000-AA571
Microsoft Visual Basic 2015

Visual C# 2015   00322-20000-00000-AA571
Microsoft Visual C# 2015

Visual C++ 2015   00322-20000-00000-AA571
Microsoft Visual C++ 2015

Application Insights Tools for Visual Studio Package   5.2.60328.3
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2015.1   14.1.20512.0
ASP.NET and Web Tools 2015.1

ASP.NET Web Frameworks and Tools 2012.2   4.1.41102.0
For additional information, visit http://go.microsoft.com/fwlink/?LinkID=309563

ASP.NET Web Frameworks and Tools 2013   5.2.40314.0
For additional information, visit http://www.asp.net/

Azure App Service Tools v2.8.1   14.0.11123.0
Azure App Service Tools v2.8.1

Common Azure Tools   1.7
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

Microsoft Azure HDInsight HQL Service   2.0.2600.0
Language service for Hive query

Microsoft Azure HDInsight Tools for Visual Studio   2.0.2600.0
An integrated development environment for HDInsight application development.

Microsoft Azure Mobile Services Tools   1.4
Microsoft Azure Mobile Services Tools

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2015 - v2.9.40323.3

Microsoft Azure Tools   2.8
Microsoft Azure Tools for Microsoft Visual Studio 2015 - v2.8.31121.1

Node.js Tools   1.1.40329.04
Adds support for developing and debugging Node.js apps in Visual Studio

Node.js Tools - Profiling   1.1.40329.04
Profiling support for Node.js projects.

NuGet Package Manager   3.5.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

PreEmptive Analytics Visualizer   1.2
Microsoft Visual Studio extension to visualize aggregated summaries from the PreEmptive Analytics product.

SQL Server Data Tools   14.0.60311.1
Microsoft SQL Server Data Tools

TypeScript   1.8.31.0
TypeScript tools for Visual Studio

Umbraco ModelsBuilder Custom Tool   1.0
Umbraco Visual Studio Custom Tool for generating strongly typed IPublishedContent models.

Visual Studio Tools for Apache Cordova   Update 9
Visual Studio Tools for Apache Cordova

Xamarin   4.0.3.214 (0dd817c)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin.Android   6.0.3.5 (a94a03b)
Visual Studio plugin to enable development for Xamarin.Android.

Xamarin.iOS   9.6.1.8 (3a25bf1)
Visual Studio extension to enable development for Xamarin.iOS.

**Comment by saurabhnandu** [comment]
I have uploaded the log file as instructed. Thanks for the quick help
[ActivityLog.zip](https://github.com/aspnet/Home/files/268730/ActivityLog.zip)

**Comment by joeloff** [comment]
I see the latest Web Tools from RC2 (ASP.NET and Web Tools 14.1.20512.0), but I don't see the .NET Core Tools in the list.

Could you perhaps share the logs from the RC2 install? They should be located in your %temp% folder (all the files that start with dd_DotNetCoreTools)

**Comment by saurabhnandu** [comment]
[Temp.zip](https://github.com/aspnet/Home/files/268745/Temp.zip)

This is the exe [  DotNetCore.1.0.0.RC2-VS2015Tools.Preview1.exe ] that i executed to install the templates. I thought it would also install .NET Core. Should that be installed separately?

**Comment by joeloff** [comment]
No, the RC2 bundle carries all the necessary items. The logs show that it was installed.

You can confirm this on your machine by looking for C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\DotNet\

The ActivityLog also shows that it loaded the extension
_Successfully loaded extension...
          C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\COMMON7\IDE\EXTENSIONS\MICROSOFT\DOTNET\_

But according to the Help/About it's not loaded.

I do see a warning about an error loading Microsoft.VisualStudio.Editor.Implementation.EditorPackage.

Did you previously (before installing RC2) see any warnings when you start the IDE about packages not loading correctly. You can suppress these message and if you do, VS won't report the errors in the future.

A few things you could try:
1. Close VS, delete %appdata%\local\Microsoft\VisualStudio\14.0\ComponentModelCache and restart the IDE
2. Start the IDE from a developer prompt with: devenv /resetskippkgs (this will force VS to report package load failures of packages that were previously suppressed).

**Comment by saurabhnandu** [comment]
1) I can see a bunch of files installed in the [  C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\DotNet\ ] folder 

2) Deleted the ComponentModelCache folder and restarted.

**Comment by joeloff** [comment]
Before creating a new project. Can you open the Error List and Output Windows (you can open them from the View menu in the IDE) and see if any errors are logged there about missing files? I noticed that the initial screenshot didn't show those windows

Does this only happen with a new Web project for ASP.NET Core or does this repro for things like Class/Console (.NET Core) as well?

**Comment by saurabhnandu** [comment]
The error and output windows remain empty. If I create a DNX Console application I get the following error. Although I am not sure what I should reinstall to ensure dot net core installs correctly. 

![image](https://cloud.githubusercontent.com/assets/13586676/15344343/c1e9c58a-1cc3-11e6-97b2-58c0a1802da3.png)

**Comment by joeloff** [comment]
According to the logs the wizard DLL was installed:

MSI (s) (BC:B8) [15:25:23:695]: Executing op: FileCopy(SourceName=i4oix2at.dll|Microsoft.VisualStudio.ProjectSystem.DotNet.Wizard.dll,SourceCabKey=Microsoft.VisualStudio.ProjectSystem.DotNet.Wizard.dll,DestName=Microsoft.VisualStudio.ProjectSystem.DotNet.Wizard.dll,Attributes=512,FileSize=31984,PerTick=65536,,VerifyMedia=1,,,,,CheckCRC=0,Version=14.1.20512.0,Language=0,InstallMode=58982400,,,,,,,)

It definitely looks like VS is not loading up the extension (since nothing shows in Help/About for the .NET Core Tools)

The only other thing I can think of suggesting is closing VS, opening a developer command prompt (Run as Admin), and then run devenv /setup

**Comment by saurabhnandu** [comment]
I did devenv /setup - no difference. 

Today I uninstalled ASP.NET Core RC2 and .NET Core RC2 SDK. And reinstalled from the installer. Same results - so I think I will have to either try reinstalling VS 2015 again. or wait for the next release.

**Comment by Successful** [comment]
Experiencing the same issue as @saurabhnandu

**Comment by Kemaletdin** [comment]
I have been getting the same error as @saurabhnandu 
And I uninstalled the VS 2015 and reinstalled it from ISO file and repaired the 
DotNetCore.1.0.0.RC2-VS2015Tools.Preview1.exe
And still getting the same error.

**Comment by saukun** [comment]
Had same issue as @saurabhnandu. After several install/uninstall I found path that seems worked for me:
At least yesterday ISO of VS 2015 Community with Updates seems still contained Web tools (Beta 8)?  
1. So uninstalled VS, deleted VS directories.
2. Installed VS, selecting Custom Install and unchecking Web Tools.
3. Installed DotNetCore.1.0.0.RC2-VS2015Tools.Preview1.exe.
4. Started VS install from Web and selected Modify, checked on Web Tools.
5. If there will be issues i.e. I had editor not highlighting C# syntax, do VS Respire.

Hope this will help someone.

**Comment by joeloff** [comment]
We're still investigating

@saurabhnandu Do you have any other versions of Visual Studio installed on the machine, e.g. VS 2010?

**Comment by Kemaletdin** [comment]
I noticed that sdk install locations are different: 

C:\Program Files\dotnet\sdk\1.0.0-preview1-002702
AND
C:\Program Files\dotnet\bin\sdk

and VS2105 is not finding the first one.
I don't know if this has anything to do with it but I have seen the error.
I was trying to convert an existing project and no matter what I put in global.json
it could not find the sdk. It keeps looking for the x86 version.

**Comment by saurabhnandu** [comment]
No, just vs 2015 update 2. But I am using Windows 10 Insider build (latest
one) could that be an issue?

I had previously installed VS 15 preview but it was installed long back.

Regards,
Saurabh

**Comment by joeloff** [comment]
Don't think so. We were following up with another team about one of the errors I saw in the ActivityLog you shared yesterday. They mentioned that they've seen isolated cases with older versions of VS such as 2010 when they are installed SxS with 2015.

If you can get the registry entries to me that would be a great help. At the moment it looks like the pkgdef files for the extensions are not being merged by VS, but the registry keys should be able to shed some light on that.

**Comment by saurabhnandu** [comment]
@joeloff which exact registry keys do you want? Please let me know, so that I can extract and send them over.

**Comment by DjoleGit** [comment]
Any updates?

**Comment by saurabhnandu** [comment]
@joeloff still waiting to know what exact reg keys you want and I will send them over.

**Comment by joeloff** [comment]
@saurabhnandu For the registry keys, could you perhaps export HKEY_CURRENT_USER\Software\Microsoft\VisualStudio\14.0_Config\RuntimeConfiguration and attach that file, then I can verify whether VS merged all the package registration information

**Comment by saurabhnandu** [comment]
@joeloff  Please find the reg file attached.

 I should also mention that I am on the Windows Insider build and recently the build got updated to the latest fast ring version. But even after the Windows Version upgrade, there has been no change in the issue. 

[VS 14 RegConfig.zip](https://github.com/aspnet/Home/files/294829/VS.14.RegConfig.zip)

**Comment by DjoleGit** [comment]
If you want to have another example, here is my exported RuntimeConfig.
Windows 10, VS 2015 Prof Update2
[RuntimeConfig.zip](https://github.com/aspnet/Home/files/296139/RuntimeConfig.zip)

**Comment by olegburov** [comment]
I am having the same issue as @saurabhnandu reported. I tried all of the above and nothing helped.

In my case the `Microsoft .NET Core Tools` is not loaded either when checking in Visual Studio 2015 => Help => About.

When running VS2015 the very first time after it was completely reinstalling, I got the following error:

![dnxprojectsystemerror](https://cloud.githubusercontent.com/assets/2487951/16065317/84f3d016-325e-11e6-9cd2-a2d86cb9c4c9.png)

In the 'C:\Users\<UserName>\AppData\Roaming\Microsoft\VisualStudio\14.0\ActivityLog.xml' file, I can see the following errors:

```
<entry>
    <record>478</record>
    <time>2016/06/13 22:51:21.416</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>LegacySitePackage failed for package [DNX Project System]Source: &apos;System.ComponentModel.Composition&apos; Description: No exports were found that match the constraint: &#x000A;&#x0009;ContractName&#x0009;Microsoft.VisualStudio.Web.ProjectSystem.Telemetry.ITelemetryProvider&#x000A;&#x0009;RequiredTypeIdentity&#x0009;Microsoft.VisualStudio.Web.ProjectSystem.Telemetry.ITelemetryProvider&#x000D;&#x000A;</description>
    <guid>{98F77210-A364-4168-BAE6-4D46FA7E19FE}</guid>
    <hr>80131500</hr>
    <errorinfo></errorinfo>
  </entry>
  <entry>
    <record>479</record>
    <time>2016/06/13 22:51:21.998</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>SetSite failed for package [DNX Project System](null)</description>
    <guid>{98F77210-A364-4168-BAE6-4D46FA7E19FE}</guid>
    <hr>80131500</hr>
    <errorinfo></errorinfo>
  </entry>
  <entry>
    <record>480</record>
    <time>2016/06/13 22:51:22.003</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>End package load [DNX Project System]</description>
    <guid>{98F77210-A364-4168-BAE6-4D46FA7E19FE}</guid>
    <hr>80131500</hr>
    <errorinfo></errorinfo>
  </entry>
```

Installing Azure SDK 2.9 didn't help to fix it either.

**Comment by joeloff** [comment]
Could you try the following: Close VS, delete %localappdata%\Microsoft\VisualStudio\14.0\devenv.exe.config and then restart VS

The devenv.exe.config contains some probing paths and VS creates that on startup

**Comment by olegburov** [comment]
I deleted the `%localappdata%\Microsoft\VisualStudio\14.0\devenv.exe.config` and restarted VS2015. Still getting the same error `The system cannot find the file specified. (Exception from HRESULT: 0x80070002)`.

Deleted, then repaired the `DotNetCore.1.0.0.RC2-VS2015Tools.Preview1.exe` installation and restarted VS2015. Still the same.

My VS2015 doesn't want to load .NET Core Tools for some reason.

```
Microsoft Visual Studio Enterprise 2015
Version 14.0.25402.00 Update 3 RC
Microsoft .NET Framework
Version 4.6.01038

Installed Version: Enterprise

Architecture and Modeling Tools   00322-80000-00000-AA798
Microsoft Architecture and Modeling Tools
    
UML® and Unified Modeling Language™ are trademarks or registered trademarks of the Object Management Group, Inc. in the United States and other countries.

Visual Basic 2015   00322-80000-00000-AA798
Microsoft Visual Basic 2015

Visual C# 2015   00322-80000-00000-AA798
Microsoft Visual C# 2015

Visual C++ 2015   00322-80000-00000-AA798
Microsoft Visual C++ 2015

Application Insights Tools for Visual Studio Package   7.0.10527.1
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2015.1 (Canary - May 9)   14.1.20512.0
ASP.NET and Web Tools 2015.1 (Canary - May 9)

ASP.NET Web Frameworks and Tools 2012.2   4.1.41102.0
For additional information, visit http://go.microsoft.com/fwlink/?LinkID=309563

ASP.NET Web Frameworks and Tools 2013   5.2.40314.0
For additional information, visit http://www.asp.net/

Azure App Service Tools v2.9.1   14.0.20519.0
Azure App Service Tools v2.9.1

Azure Data Lake Node   1.0
This package contains the Data Lake integration nodes for Server Explorer.

Azure Data Lake Tools for Visual Studio   2.0.6000.0
Microsoft Azure Data Lake Tools for Visual Studio

Common Azure Tools   1.8
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

Microsoft Azure HDInsight HQL Service   2.0.6000.0
Language service for Hive query

Microsoft Azure HDInsight Tools for Visual Studio   2.0.6000.0
An integrated development environment for HDInsight application development.

Microsoft Azure Mobile Services Tools   1.4
Microsoft Azure Mobile Services Tools

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2015 - v2.9.40518.2

NuGet Package Manager   3.5.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

PreEmptive Analytics Visualizer   1.2
Microsoft Visual Studio extension to visualize aggregated summaries from the PreEmptive Analytics product.

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript   1.8.32.0
TypeScript tools for Visual Studio
```

**Comment by DjoleGit** [comment]
I uninstalled VS already twice. Didn't help at all. I also used the TotalUninstall tool.

**Comment by Tameshiwari** [comment]
For those it may interest... regarding **ASP.NET Core RC 2.** + **VS 2015 Update 3 RC**..

After installing **Visual Studio 2015 Enterprise Update 3 RC** a few days ago, I noticed **Asp.Net 5.0 RC** Templates were missing.
I then opted to reinstall the templates through .**NET Core 1.0.0 RC2 - VS 2015 Tooling Preview1**, though I encountered the following error:

_0x80070666 - Another version of this product is already installed. Installation of this version cannot continue. To configure or remove the existing version of the product, use Add/Remove Programs on the Control Panel. This is due to a setup issue resulting in VC++ 2015 Update 3 RC Redistributable registry keys being incorrectly removed during Update 3 RC setup._

Following workaround worked for me. In **Control Panel>Add/Remove Programs**:
1)Select "**Microsoft Visual C++ 2015 Redistributable (x64) - 14.0.24123**" and then click "**Change**"
  In the **Visual C++ 2015 redistributable dialog**, select "**Repair**"
2)Select "**Microsoft Visual C++ 2015 Redistributable (x86) - 14.0.24123**" and then click "**Change**"
  In the **Visual C++ 2015 redistributable dialog**, select "**Repair**" 

I then proceeded with reinstalling **.NET Core 1.0.0 RC2 - VS 2015 Tooling Preview1**. Reinstallation process then took a few minutes... to successfully complete. 

Templates are now back in and everything seems to be working well. [At least for now... ;) ]

**Comment by olegburov** [comment]
@Tameshiwari Thank you for the details. The issue you reported is a known issue for VS2015 Update-3 RC. It is documented in the [Readme.md](https://github.com/aspnet/Tooling/blob/master/README.md) file at [https://github.com/aspnet/tooling](https://github.com/aspnet/tooling) repo.

**Comment by Tameshiwari** [comment]
@olegburov Great.  Guess I missed the Readme.md  :)

**Comment by olegburov** [comment]
Today I gave it another try.

1. Removed VS 2015 Enterprise.
2. Removed SQL Server 2016 Management Studio, since it's based on a new VS 2015 Shell.
3. Cleaned it up using the [VisualStudioUninstaller](https://github.com/Microsoft/VisualStudioUninstaller/releases).
4. Installed VS 2015 2015 Enterprise. This time I didn't get the `DNX Project System` package error I reported before.  
5. Installed the `DotNetCore.1.0.0.RC2-VS2015Tools.Preview1.exe`.

Didn't help :(

Repeated the above steps, but using VS 2015 Community Edition. VS 2015 still throwing the same issue.

My best hope is the next Monday when `VS2015Tools.Preview2` comes out. If VS2015 with `Preview2` continues throwing the same error that would be very disappointing, since I can't think of anything else rather than installing Win10 from scratch and then VS 2015.

**Comment by babarqb** [comment]
@saurabhnandu same error i face tooo could you share how to solve it. i uninstall vs /force and then install update2 then this error came. i just remove  .dnx folder manual    confuse confuse

**Comment by olegburov** [comment]
The same error as @saurabhnandu reported, but using VS2015 Update-3 + `DotNetCore.1.0.0-VS2015Tools.Preview2.exe`.

Is there any chance MS team will invest into this issue?

**Comment by saurabhnandu** [comment]
just updated to Visual Studio 2015 Update 3 and DotNetCore.1.0.0-VS2015Tools.Preview2.exe and the same issue!  Cant test out .NET Core 1.0! There has to be some way to fix this.

**Comment by DjoleGit** [comment]
I guess the only way to fix it is to reinstall windows. But this is not happening

**Comment by GRTRao** [comment]
I have the same issue. I have updated to VS 2015 update 3 and  DotNetCore.1.0.0-VS2015Tools.Preview2.exe.  I tried TotalUninstall a couple of times. I am using windows 7.  I removed all versions of VS and SQL Server completely. The only thing remaining is reinstalling windows !!!.

**Comment by bernharde** [comment]
I had the same problem and finally was able to fix it. The problem relys in the devenv.exe.config. I missed the following entry and so VS was not able to find the wizard.dll
<dependentAssembly>
				<assemblyIdentity name="Microsoft.VisualStudio.ProjectSystem.DotNet.Wizard" publicKeyToken="b03f5f7f11d50a3a" culture="neutral"/>
				<codeBase version="14.0.0.0" href="C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\DotNet\ProjectSystem\Microsoft.VisualStudio.ProjectSystem.DotNet.Wizard.dll"/>
			</dependentAssembly>

Good luck, Bernhard

**Comment by joeloff** [comment]
@bernharde, thanks for sharing. VS is supposed to regenerate the devenv.exe.config file when you run /setup which didn't seem to work for people when we suggested it. I'll follow up with the VS team to see whether there are any issues why this entry won't be created.

**Comment by olegburov** [comment]
@bernharde believe it or not, but it fixed the issue!

I checked the `C:\Users\<user>\AppData\Local\Microsoft\VisualStudio\14.0\devenv.exe.config` file and it didn't include the `<assemblyIdentity name="Microsoft.VisualStudio.ProjectSystem.DotNet.Wizard" ... />`. I double-checked the `devenv /

setup` command one more time. It regenerated the `devenv.exe.config` file, but it still didn't have the above node. After I added it manfully, the issue has gone and I can finally use VS 2015 Update-3 with .NET Core and ASP.NET Core 1.0.

My [devenv.exe.config.zip](https://github.com/aspnet/Home/files/337657/devenv.exe.zip) is attached.

**Comment by DjoleGit** [comment]
Nice! At least I can create a project now. But I still get "The DNX Project System" package did not load correctly.

<entry>
    <record>737</record>
    <time>2016/06/28 17:47:51.199</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>LegacySitePackage failed for package [DNX Project System]Source: &apos;System.ComponentModel.Composition&apos; Description: No exports were found that match the constraint: &#x000A;&#x0009;ContractName&#x0009;Microsoft.VisualStudio.Web.ProjectSystem.Telemetry.ITelemetryProvider&#x000A;&#x0009;RequiredTypeIdentity&#x0009;Microsoft.VisualStudio.Web.ProjectSystem.Telemetry.ITelemetryProvider&#x000D;&#x000A;</description>
    <guid>{98F77210-A364-4168-BAE6-4D46FA7E19FE}</guid>
    <hr>80131500</hr>
    <errorinfo></errorinfo>
  </entry>
  <entry>
    <record>738</record>
    <time>2016/06/28 17:47:51.209</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>SetSite failed for package [DNX Project System](null)</description>
    <guid>{98F77210-A364-4168-BAE6-4D46FA7E19FE}</guid>
    <hr>80131500</hr>
    <errorinfo></errorinfo>
  </entry>
  <entry>
    <record>739</record>
    <time>2016/06/28 17:47:51.212</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>End package load [DNX Project System]</description>
    <guid>{98F77210-A364-4168-BAE6-4D46FA7E19FE}</guid>
    <hr>80131500</hr>
    <errorinfo></errorinfo>
  </entry>

Any ideas?

**Comment by olegburov** [comment]
@DjoleGit, @bernharde, @joeloff, @saurabhnandu and others here is how to fix it completely:

1. Delete the entire `C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Web Tools\DNX` directory. (As far as I understand, it belongs to the old version of ASP.NET Core RC1, which for some reason is still shipped even with VS2015 Update-3).
2. Delete the `C:\Users\<user>\AppData\Local\Microsoft\VisualStudio\14.0\devenv.exe.config` file.
3. Run the `Developer Command Prompt for VS2015` as Administrator. The new `devenv.exe.config` file is generated. This time there are many assemblies that refer to the `C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\DotNet` directory.
4. Run the VS 2015 and check that it shows the `Microsoft .NET Core Tools (Preview 2)   14.1.20624.0` in the `Help` => `About Microsoft Visual Studio` menu.
   
The correct [devenv.exe.config.zip](https://github.com/aspnet/Home/files/337808/devenv.exe.config.zip) is attached.

**Comment by hheexx** [comment]
@olegburov 
I have a problem also and it does not work for me.

Starting command prompt for vs2015 does not generate new .config file for me.
Or should I copy the file you provided?

Both ways it does not work. With your .config file VS freezes when loading project

**Comment by olegburov** [comment]
@hheexx You must execute the `devenv /setup` command using the `Developer Command Prompt for VS2015`. Sorry, I missed this detail first time (Updated step 3).

> With your .config file VS freezes when loading project

That's because my has references to Azure Tools and SQL Server extensions, which most likely are not installed on top of your VS2015.

**Comment by hheexx** [comment]
Thanks, I fixed it in meantime.
Here's how:

1) Deleted C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Web Tools\DNX folder.
2) Deleted devenv.exe.config
3) Started VS to regenerate the .config file.
4) Deleted all dependencies in devenv.exe.config that contain DNX in path.
5) Added dependency to Microsoft.VisualStudio.ProjectSystem.DotNet.Wizard.dll from few posts above
6) Repaied Microsoft .NET Core 1.0.0 - VS 2015 Tooling Preview 2 in Programs and Features.

**Comment by bernharde** [comment]
Thank you for posting the old DNX folder. Adding the entry to the devenv.exe.config manually is a workaround that just works, but every time VS is regenerating the file again it will stop working. 

So, this is how I got VS generating a correct devenv.config.exe
1. Delete the folder C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Web Tools\DNX - this is just a cleanup you can skip
2. Delete every reg key that contains that path C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Web Tools\DNX . I did not deleted the Keys from Windows Installer only the Visual Studio node. HKLM, HKCU, HKCU (DefaultUser) etc...
3. Open Program Features click Repair to "Microsoft .NET Core 1.0.0 - VS 2105 Tooling Preview 2"
4. Delete the old devenv.exe.config
C:\Users\<user>\AppData\Local\Microsoft\VisualStudio\14.0\devenv.exe.config

= Final fix

Good luck, Bernhard

**Comment by arjun-g** [comment]
Thanks @olegburov Have been facing this problem for sometime. Now its fixed after following your steps.

**Comment by Yuanyang** [comment]
Thanks @olegburov 
I fixed my visual studio by following your instructions. Now it can create new web projects smoothly.

**Comment by fabiomargarito** [comment]
The steps fixed my Visual Studio. Thanks

**Comment by Seany84** [comment]
I've tried both @olegburov  and @bernharde solutions and neither have worked for me.

**Comment by amicalrahul** [comment]
I am also facing the same issue. I have installed VS2015 update 2.
I tried to follow the above steps but strangely the below directory is empty
C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\DotNet

Even there is no dnx folder at below path
**:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Web Tools\DNX **

I've run RC1 installation successfully and even repaired it many time. But somehow there is nothing installed in the dotnet folder at **C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\DotNet** path

@bernharde @olegburov or anyone - Can you please suggest something else to solve this problem.

I even repaired 
VS2015 installation. 
deleted dev.exe.config file
ran devenv /setup in vs2015 command prompt (as administrator)

I guess the root problem is nothing is installed in dotnet folder in programfiles and no dnx folder is created.

Need help urgently.

**Comment by xperiandri** [comment]
In my case Team Explorer pane in Blend crashed.
So I uninstalled everything related to ASP.NET Core and .NET Core, all versions. And then installed Preview 2 tools again.

**Comment by louellen** [comment]
I just installed today and got the same issue.  Olegburov's solution worked for me.

1,  Delete the entire C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Web Tools\DNX directory. (As far as I understand, it belongs to the old version of ASP.NET Core RC1, which for some reason is still shipped even with VS2015 Update-3).
2,  Delete the C:\Users\<user>\AppData\Local\Microsoft\VisualStudio\14.0\devenv.exe.config file.
3,  Run the Developer Command Prompt for VS2015 as the Administrator, and execute the devenv /setup command. The new devenv.exe.config file is generated. This time there are many assemblies that refer to the C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\DotNet directory.
4.  Run the VS 2015 and check that it shows the Microsoft .NET Core Tools (Preview 2) 14.1.20624.0 in the Help => About Microsoft Visual Studio menu.

**Comment by OneBlueCubeDev** [comment]
I just did a fresh install and I am getting this error?  I tried Olegburov's  fix and I am still getting the issue.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
