### ISSUE TITLE
asp.net RC2 RemoteIpAddress always "127.0.0.1" on Azure

### ISSUE THREAD

**Issue by joaomello** [aspnet/Home#1456]
I had this code on the controller:
```
public IActionResult Ip()
{
  return Ok(new { Ip = HttpContext.Connection.RemoteIpAddress?.ToString() });
}
```

but azure always returning:
`{"Ip":"127.0.0.1"}`

I am using with .net 4.6. I have add:
```
services.Configure<ForwardedHeadersOptions>(options =>
{
  options.ForwardedHeaders = Microsoft.AspNetCore.HttpOverrides.ForwardedHeaders.All;
});
```

Like @davidfowl said to me, but continues same ipaddress. Any idea?

**Comment by Tratcher** [comment]
This looks like the same issue as https://github.com/aspnet/IISIntegration/issues/140. Try Microsoft.AspNetCore.HttpOverrides.ForwardedHeaders.XForwardedFor;

**Comment by joaomello** [comment]
You are right @Tratcher, works now. But I used `Microsoft.AspNetCore.HttpOverrides.ForwardedHeaders.All` shouldn't be worked with it too?

**Comment by Tratcher** [comment]
It should, but it's broken on Azure right now.

**Comment by joaomello** [comment]
Thanks @Tratcher!
