### ISSUE TITLE
Discussion for: .NET Core RC2, ASP.NET Core RC2, and Entity Framework Core RC2 are released!

### ISSUE THREAD

**Issue by Eilon** [aspnet/Home#1457]
Discussion for: https://github.com/aspnet/Announcements/issues/177

---

Check out the announcement posts:
- [Announcing .NET Core RC2 and .NET Core SDK Preview 1](https://blogs.msdn.microsoft.com/dotnet/2016/05/16/announcing-net-core-rc2/)
- [Announcing ASP.NET Core RC2](https://blogs.msdn.microsoft.com/webdev/2016/05/16/announcing-asp-net-core-rc2/)
- [Announcing Entity Framework Core RC2](https://blogs.msdn.microsoft.com/dotnet/2016/05/16/announcing-entity-framework-core-rc2/)

All the downloads are available at the [.NET Downloads](https://www.microsoft.com/net/download) page.

And finally, some of the key documents that can help with this release:
- [Migrating from DNX to .NET Core CLI](http://dotnet.github.io/docs/core-concepts/dnx-migration.html)
- [Migrating from ASP.NET 5 R1 to ASP.NET Core](https://docs.asp.net/en/latest/migration/rc1-to-rc2.html)
- [Upgrading Entity Framework from RC1 to RC2](https://docs.efproject.net/en/latest/miscellaneous/rc1-rc2-upgrade.html)

**Comment by Kurira** [comment]
What's the new way to create a project to be used as a "tool" (previously as a command)?
I can't get console application to inject default `IServiceProvider`, `IApplicationEnvironment` instances anymore, is there a way to get them?

What's with all the new monikers?
is `dnx451` = `net451` and `dnxcore50` = `netstandard1.5`? Because I see console app using `netcoreapp1.0` and `Microsoft.NETCore.App` all over the place. What should be used for windows only and cross plat configurations? I'm confused :confused:

**Comment by moozzyk** [comment]
Tools are now just netcoreapp1.0 apps whose name start with `dotnet-`. In the project you want to use the tool you would add a reference to the tool's package in the "tools" section in the project.json. If you are looking for an example take a look at the publish iis tool: https://github.com/aspnet/IISIntegration/tree/dev/src/Microsoft.AspNetCore.Server.IISIntegration.Tools. Here: https://github.com/aspnet/cli-samples/blob/master/HelloMvc/project.json#L33-L41 you can find how to register the tool in your project and how to invoke it (in this particular example it's being invoked as postpublish script but you can also run it from command line using `dotnet publish-iis`. Note that the tool dll name is `dotnet-mytool` but when you want to invoke it you use `dotnet mytool` (i.e. you skip the `dotnet-` prefix)).

**Comment by NTaylorMullen** [comment]
@Kurira to get the `ApplicationEnvironment` in a tool utilize [this](https://github.com/aspnet/PlatformAbstractions/blob/0c0e990682f26b651edfe5b890b9a2a14ddb76f1/src/Microsoft.Extensions.PlatformAbstractions/PlatformServices.cs).

> What should be used for windows only and cross plat configurations?

Tools target `netcoreapp1.0`. You'll see some tools target `net451` like RazorTooling and EF below but they're initial entry point is always invoked via the `netcoreapp1.0` tfm

As for an example of a new-dotnet based tool take a look at any of the following:
- [dotnet publish-iis](https://github.com/aspnet/IISIntegration/tree/dev/src/Microsoft.AspNetCore.Server.IISIntegration.Tool)
- [dotnet-watch](https://github.com/aspnet/dotnet-watch/tree/dev/src/Microsoft.DotNet.Watcher.Tools)

And finally some more complex tools that rely on user code:
- [dotnet razor-tooling](https://github.com/aspnet/RazorTooling/tree/dev/src/Microsoft.AspNetCore.Razor.Tools)
- [dotnet ef](https://github.com/aspnet/EntityFramework/tree/dev/src/Microsoft.EntityFrameworkCore.Tools)



This isn't all the tools that we ship, just a starting point :smile:. Hope this helps!

**Comment by Jupakabra** [comment]
Hello,

Thanks for release.
Is there a difference between installing x86 or x64 .NET Core?
Current templates don't include either of those in `global.json`, I'm guessing that x86 is used by default?

**Comment by Kurira** [comment]
So `netcoreapp1.0` is for tools, but how do we know if that tools runs on `net` or on `core`? Or is it both by default?

**Comment by NTaylorMullen** [comment]
@Kurira It always initially runs on core. In the later tool examples I provided (`razor-tooling`/`ef`) they re-invoke themselves in the users build output in the case that a users project only targets a net TFM.

That's why in `watch`/`publish--is` they only target `netcoreapp1.0` because they don't need to do anything with user code; running only in core is sufficient for them.

**Comment by keith-vikode** [comment]
Has the ability to deploy source code gone for good along with DNX? It's not a deal breaker, but I did find it very handy for finding out just what code was deployed (as well as for adding emergency logging statements!)

Also, and with no evidence to back this up other than gut feeling, the time taken to recompile the app after making a code change when running in VS seems longer using the CLI vs DNX. The short cycle between making changes and F5'ing to see them was, for me, the most awesome feature of VNext - really hope I'm imagining it!

**Comment by mrahhal** [comment]
@NTaylorMullen how exactly does the `ef` tooling re-invoke itself? I have a dnx command that runs only on `net` that needs to access user's code as before (that I want to port to RC2 naturally) but till now I have found zero info on the subject. How does it all work?

If someone from the team can explain this tool (formerly command) builders will be grateful (I'm not sure if docs are coming, but for now searching about this yields nothing).

**Comment by NTaylorMullen** [comment]
@mrahhal So i'll use razor-tooling as an example since I have more context. With tools that need to run user code you currently need the following criteria: https://github.com/aspnet/Tooling/issues/484#issuecomment-219807702

Now, when you type `dotnet razor-tooling` at the command line, `dotnet` always tries to invoke the `netcoreapp1.0` **tools** version of your tool (remember, it exists in the `tools` and `dependencies` sections of your `project.json`). So it boots the `razor-tooling` tool and the tool determines based on the command line input what it should do. It has 3 paths.

1. Command line arguments do not result in any sort of user code work. Do all the work in the current process, don't do any re-invocation.
1. Command line arguments warrant user code work **and** I'm the tool instance that was referenced in the `tools` section (I'm the dispatcher). Re-invoke myself in the users build output. [Example](https://github.com/aspnet/RazorTooling/blob/c998cee9caf321bc611b979f94d749b030571e3a/src/Microsoft.AspNetCore.Razor.Tools/Program.cs#L30-L39) showing how the tool determines if it is the dispatcher. [Example](https://github.com/aspnet/RazorTooling/blob/c998cee9caf321bc611b979f94d749b030571e3a/src/Microsoft.AspNetCore.Razor.Tools/Internal/ResolveTagHelpersDispatchCommand.cs#L74-L88) showing how to dispatch.
1. Command line arguments warrant user code work **and** I'm the tool instance that was referenced in the `dependencies` section (I'm the worker). Perform work on user code. [Example](https://github.com/aspnet/RazorTooling/blob/c998cee9caf321bc611b979f94d749b030571e3a/src/Microsoft.AspNetCore.Razor.Tools/Internal/ResolveTagHelpersRunCommand.cs#L35-L49) showing the `razor-tooling` could inspecting the users projects for TagHelpers.

One thing to keep in mind with the new `tool` system is that it's not a port of DNX commands into the new CLI world. Treat it as a completely new system. Now, that being said it has some rough edges that we're aware of and we'll be working through those in the coming tool releases.

Hope this helps!

**Comment by mrahhal** [comment]
@NTaylorMullen great explanation. Very close, but I'm having trouble with creating the dispatch command: `CommandUnknownException: No executable found matching command "dotnet-foo"`. I made sure to follow the criteria, so the dependencies section does have a reference to my tool.

I'm getting the project file through `ProjectReader.GetProject("")` so maybe this is the problem?
Would you mind explain what arguments are required for the `DotnetToolDispatcher.CreateDispatchCommand` method call (I suspect this call also)?

**Comment by Muchiachio** [comment]
You can debug just about everything by using `System.Diagnostics.Debugger.Launch();`.

**Comment by mrahhal** [comment]
Thanks for the tip, but exceptions from dotnet.exe were occurring whenever I try to debug.

So, it's like the tool entry in the `dependencies` is non existent. This is what I'm doing in a project that's using the tool:

```
"dependencies": {
  "SomeTool": {
      "version": "1.0.0-*",
      "imports": "build"
    }
},

"tools": {
    "SomeTool": {
      "version": "1.0.0-*",
      "imports": "portable-net45+win8+dnxcore50"
    }
  },

"frameworks": {
    "net451": {
    }
  }
```
The tool is running, but the `DotnetToolDispatcher.CreateDispatchCommand` call is raising `CommandUnknownException: No executable found matching command "dotnet-some"`.

**Comment by mrahhal** [comment]
OK, managed to get it working. The problem was the `buildBasePath` argument. It should have been null instead of an empty string. @NTaylorMullen great explanation and thanks a lot.

**Comment by GuardRex** [comment]
@NTaylorMullen Your link to `publish-iis` tooling above ...https://github.com/aspnet/Home/issues/1457#issuecomment-219797002 ... It's missing the "s" (i.e., "Tools" at the end.

**Comment by mrahhal** [comment]
@NTaylorMullen I have a sample in the same solution that uses my tool. It used to work with commands, but right now It seems I'm not able to reference the tool through the `tools` section without installing the package and making it available through a nuget feed (restore says it can'f din it). Is this true or is there a way to use tools in the same solution?

**Comment by moozzyk** [comment]
@mrahhal - unfortunately project to project references don't work with tools: https://github.com/dotnet/cli/issues/1215

**Comment by mrahhal** [comment]
:grimacing: Too bad.
Alright, thanks for all the help. I got it all working following @NTaylorMullen's explanation. I'll be referencing people to this explanation until the docs get done.

**Comment by Villason** [comment]
I find the project.json and the dependency web extremely confusing.

I don't to even want to understand the difference between dnxcore50 (why is there still a "dnx"), netstandard1.5, portable-net45+win8, NETStandard.Library, Microsoft.NETCore.App, netcoreapp1.0, dotnet5.6, etc, etc. All the names means nothing to the user. Why should he care?

I am struggling to migrate my RC1 solution to RC2 (it is just a web app + class libraries).

**Comment by mrahhal** [comment]
@Villason completely agree but I guess working in the open and getting to try all the new bits as they come out will naturally lead to this kind of situation.

Maybe we can help? You can try asking a question on stackoverflow and putting the link here. I think that's a better place for this.

**Comment by GuardRex** [comment]
@Villason I wouldn't go SO ... that's not "chatty" enough for Q&A. You prob can find a free dev on Slack and get many of your questions answered. Signup at http://tattoocoder.com/aspnet-slack-sign-up/.

**Comment by GuardRex** [comment]
... and in addition to the official conversion doc at docs.asp.net, I have some links here that might help: https://github.com/dotnet/cli/issues/2135#issuecomment-212692267

**Comment by Villason** [comment]
I dunno I thought this was a discussion so I thought I could be in verbose mode. My first issue was just the first package I added to project.json:

    "HtmlAgilityPack": "1.4.9"

C:\Program Files\dotnet\dotnet.exe restore "E:\Repositories\MyProject\.vs\restore.dg"
Error:  Package dependencies must specify a version range. WAT?

I guess I will go back to RC1. (I wanted to go to RC2 to avoid a RC1 bug that was slowing me down)

**Comment by GuardRex** [comment]
@Villason I just mentioned it b/c a lot of rapid-fire Q&A on general .NET Core topics creates quite a stream here. If you have specific issues, of course, that makes perfect sense to discuss them here.

I can tell you that the devs at Slack (and JabbR) all day (and all night for that matter! ... Europe, Asia, Australia, Africa!) are happy to explain aspects on a variety of topics.

**Comment by Villason** [comment]
@GuardRex 

> [EDIT] Here is the official one: https://docs.asp.net/en/latest/migration/rc1-to-rc2.html

My issue is with the new project.jsons and library references. I guess I am not alone. My approach was to create a new solution with a web project + class library projects and start moving things from the old project. Then I was "overwhelmed" with all the interchangeable names things get and confused with Intellisense suggestions (like Microsoft.AspNetCore.Mvc.ViewFeature 1.0.0-rc2-final or Microsoft.AspNet.Mvc.ViewFeatures 6.0.0-rc2-16927. WAT?).

Ok, I will stop whining here and skip this Preview1 altogether. It looks like @davidfowl called the MS police :)

**Comment by abpiskunov** [comment]
@villason create two separate issues please and specify precise repro steps and add me and emgarten there.
1. Restore error: when you do restore for that project get whole restore output
2. Intelligence suggestions: you mean Ctrl+. Suggestions to add package? For what symbol you had those intelligence messages?

**Comment by GuardRex** [comment]
@Villason Here's a little context: What happened was that a lot of design changes occurred between RC1 and RC2. It wasn't bad for those following along with nightly builds. We just slowly massaged things into RC2 over a period of several months. For those who were sitting tight RC1-final ... then coming into RC2-final ... :boom: ... that's a lot of deltas to run into all at once.

What many have been doing at Slack is helping people "walk" their RC1 app into RC2 form. Usually, we'll say, "Paste your WebHostBuilder in here." ... "Ok .. do this ... do that." Paste your `project.json` in here." ... "Ok ...do this ... do that." ... and just massage the app into good RC2 form. In the midst of those app changes, other questions occur and get answered along the way.

The docs are all updated now for RC2, and the main official conversion doc is really great. That was done by @rachelappel and hits all the main points. If your app is still not quite right, I'd suggest hitting up Slack :cat:'s for final touches. There are a lot of happy endings over there (as there are here). :smile:

**Comment by Villason** [comment]
@abpiskunov here we go:

```
Installing NuGet package Microsoft.AspNetCore.Mvc.ViewFeatures.1.0.0-rc2-final.
Successfully installed 'Microsoft.AspNetCore.Mvc.ViewFeatures 1.0.0-rc2-final' to MySolution.Utils
========== Finished ==========
PATH=%PATH%;.\node_modules\.bin;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Web\External;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Web\External\git
C:\Program Files\dotnet\dotnet.exe restore "E:\Repositories\MySolution\.vs\restore.dg"
error: Error reading 'E:\Repositories\MySolution\src\MySolution.Core\project.json' at line 5 column 26 : Package dependencies must specify a version range.
error:   Package dependencies must specify a version range.

```

project.json is very simple at the moment (class library project):

```
{
  "dependencies": {
    "Microsoft.AspNetCore.Mvc.ViewFeatures": "1.0.0-rc2-final",
    "NETStandard.Library": "1.5.0-rc2-24027",
    "System.Linq": "4.1.0-rc2-24027",
    "System.Linq.Expressions": "4.0.11-rc2-24027"
  },
  "frameworks": {
    "netstandard1.5": {
      "imports": [
        "dnxcore50",
        "portable-net45+win8"
      ]
    }
  },
  "version": "1.0.0-*"
}

```

**Comment by emgarten** [comment]
@Villason if you hit it again please open an issue. Usually this error happens when a project.json file has something like ``"mypackage": ""`` and no version given. DNU treated this as floating, but dotnet restore requires a value here.

**Comment by Jupakabra** [comment]
Hi again, I have a tool witch targets `netcoreapp1.0` and `net451`, do I have to create another project for my tool logic (like EF and other tools who rely on user code do) or having all the logic in one project is ok?

**Comment by mrahhal** [comment]
@Jupakabra my take: if the tool is not overly complex (for example, on par with EF core tool) then one project is more than enough. I maintain a tool that relies on user code and it's in one project.

**Comment by Jupakabra** [comment]
Great, I kind of followed EF and other tool examples by creating dispatcher and tool code projects. And I spend 2 full days ripping my hair out, because I needed to create nuget packages for both, tool code and dispatcher projects, not just dispatcher one :smiley:

**Comment by mrahhal** [comment]
You can also check mine [here](https://github.com/mrahhal/Migrator.EF6). It's simple enough and to the point.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
