### ISSUE TITLE
RC2 Upgrade - "Unable to locate project.json"

### ISSUE THREAD

**Issue by kspearrin** [aspnet/Home#1458]
I'm not sure if this is the best repo for this issue. If not, please redirect me.

I have updated a large RC1 project to RC2. When trying to launch the application I get the following error on startup from Program main:

> Unable to locate 'project.json' at '...\bin\Debug\net461\win7-x64\'

Screenshot: http://puu.sh/oVhaP/8923e3f573.png

To get around this issue, I added `project.json` to my "copyToOutput" section in `project.json`.

```
"buildOptions": {
    ...
    "copyToOutput": [
        "appsettings.json",
        "appsettings.Staging.json",
        "appsettings.Production.json",
        "project.json"
    ]
    ...
},
```

As you can see, I also had to do this with `appsettings.*.json` files as well or else I get a similar error. I can understand this somewhat with `appsettings.json` since I am reading from it in my application (though I didn't have to do this before), but is this really necessary for `project.json`? Something doesn't seem right here to me.

Creating a new test app from scratch on RC2 seems to run just fine without specifying `project.json` in the "copyToOutput".

**Comment by Bartmax** [comment]
try deleting obj and bin folders.

**Comment by kspearrin** [comment]
> try deleting obj and bin folders.

I've done this along with `project.lock.json`, and `.vs` folder.

**Comment by SimonOrdo** [comment]
Same problem, same error message. Cleaning project output didn't help.  Thanks for the workaround.

**Comment by glennc** [comment]
Can you show me the Startup.cs? This can be caused by UserSecrets as it needs a project.json. Usually because the base paths are miss-configured. If you look at the app that is working you will see differences.

**Comment by kspearrin** [comment]
@glennc, Yep, that was it. I was missing `.SetBasePath( env.ContentRootPath )` on my `ConfigurationBuilder` in `Startup.cs`. Working great now. Thanks.

Before (RC1):

        public Startup( IHostingEnvironment env )
        {
            var builder = new ConfigurationBuilder()
                .AddJsonFile( "appsettings.json" )
                .AddJsonFile( $"appsettings.{env.EnvironmentName}.json", optional: true );

            if( env.IsDevelopment() )
            {
                builder.AddUserSecrets();
                builder.AddApplicationInsightsSettings( developerMode: true );
            }

            builder.AddEnvironmentVariables();
            Configuration = builder.Build();
        }

After (RC2):

        public Startup( IHostingEnvironment env )
        {
            var builder = new ConfigurationBuilder()
                .SetBasePath( env.ContentRootPath )
                .AddJsonFile( "appsettings.json" )
                .AddJsonFile( $"appsettings.{env.EnvironmentName}.json", optional: true );

            if( env.IsDevelopment() )
            {
                builder.AddUserSecrets();
                builder.AddApplicationInsightsSettings( developerMode: true );
            }

            builder.AddEnvironmentVariables();
            Configuration = builder.Build();
        }

**Comment by madmunsterdaddy** [comment]
So are we supposed to deploy project.json or no to fix this issue?

Consider that I have an Azure deployment slot for Development and Staging. Development doesn't work because it tanks without project.json. This wasn't the case with RC1.
