### ISSUE TITLE
ConfigureRouting Service is missing in RC2

### ISSUE THREAD

**Issue by zenixgrace** [aspnet/Home#1459]
Hi Teams,

is ConfigureRouting service missing / deprecate in RC2?
I can't find any doc about this change.

I need to use AppendTrailingSlash option and LowercaseUrls option.
it's available in RC1 #

**Comment by Muchiachio** [comment]
You can use `Configure` method on `IServiceCollection` to change routing configuration.
```C#
services.Configure<RouteOptions>(options =>
    {
        options.AppendTrailingSlash = true;
        options.LowercaseUrls = true;
    });
```

**Comment by zenixgrace** [comment]
@Muchiachio  nice.. big thanks

**Comment by rynowak** [comment]
In addition all of the various `AddXyz(...)` methods now take an `Action<TOptions>` where there's something to do. So `AddRouting(options => ...)` works as well
