### ISSUE TITLE
Type/Member Identification in RC2 Core Packages

### ISSUE THREAD

**Issue by jsacapdev** [aspnet/Home#1460]
Can we update something like https://packagesearch.azurewebsites.net/ with rc2 packages? If not, what would be an alternative to to identify in which package(s) a RC2 type/member exists if not using Visual Studio?

**Comment by GuardRex** [comment]
cc/ @glennc (maintains that app and said recently it might get a feeds update in Slack chat)

**Comment by glennc** [comment]
Yeah, I haven't updated PackageSearch to RC2 yet. But I intend to do it in the next couple of days.

**Comment by jsacapdev** [comment]
Thank you. That would be much appreciated. There is no urgency and so I will close this down, and check the site myself for the RC2 packages.
