### ISSUE TITLE
RC2 can't run / debug using IIS

### ISSUE THREAD

**Issue by zenixgrace** [aspnet/Home#1461]
Hi Team,

Is anyone have problem when running aspnet 5 RC2 code using IISExpress ?
When running use IISExpress server, the application alway load but if i change to kestrel the application run perfectly.

**Comment by SimonOrdo** [comment]
I can't attach debugger or run IIS Express.  HOw do you change to Kestrel for debugging?

**Comment by glennc** [comment]
@shirhatti problems with ANCM?

**Comment by moozzyk** [comment]
@SimonOrdo  - did you port your application from RC1 to RC2?

**Comment by moozzyk** [comment]
@SimonOrdo  - in your web.config file enable logging (set the following attributes as follows `stdoutLogEnabled="false" stdoutLogFile=".\logs\stdout"`) and create the `logs` folder in the application folder. When you start your application now a log file should be created in the logs folder which should tell you what happened.

**Comment by SimonOrdo** [comment]
The log file is created, but is blank with 0 bytes.

**Comment by leontyr** [comment]
I'm having the same problem. Here is my Output:
```
Exception thrown: 'System.AggregateException' in Microsoft.AspNetCore.Server.Kestrel.dll
The program '[16252] dotnet.exe' has exited with code -1073741819 (0xc0000005) 'Access violation'.
The program '[7888] iisexpress.exe' has exited with code 0 (0x0).
```

Log created by stdoutLogEnabled:
```
[Node] ts-loader: Using typescript@1.8.10 and D:\Documents\Visual Studio 2015\Projects\AbcCore\src\Web\tsconfig.json
```

**Comment by moozzyk** [comment]
Actually the AV might be an issue with dotnet itself. @leontyr - any interesting entries in the event log?

**Comment by leontyr** [comment]
Only got this warning in my Windows Appliccation logs:
```
The directory specified for caching compressed content C:\Users\Leon\AppData\Local\Temp\iisexpress\IIS Temporary Compressed Files\Clr4IntegratedAppPool is invalid.  Static compression is being disabled.
```

**Comment by halter73** [comment]
I would expect there to be a stack trace for an AccessViolationException written to stderr if there was an AV from kestrel.

@leontyr @SimonOrdo Can you add `Console.WriteLine("Hello world!");` or similar to your `Main` method to see if it shows up in the stdoutLogFile you configured? If so it might help to set up [trace level console logging](https://github.com/aspnet/KestrelHttpServer/blob/8c8ee150f79d0ed16a14ece21d05e3736dbb83e9/samples/SampleApp/Startup.cs#L17) if you haven't already.

**Comment by leontyr** [comment]
This is what I've got after adding the trace level console logging:
```
dbug: Microsoft.AspNetCore.Hosting.Internal.WebHost[3]
      Hosting starting
[Node] ts-loader: Using typescript@1.8.10 and D:\Documents\Visual Studio 2015\Projects\AbcCore\src\Web\tsconfig.json

```

**Comment by zenixgrace** [comment]
i'm not find any error message from the log file.

but i find weird thing the launch url is not same with the define in the property

info: Microsoft.Extensions.DependencyInjection.DataProtectionServices[0]
      User profile is available. Using 'C:\Users\Citra\AppData\Local\ASP.NET\DataProtection-Keys' as key repository and Windows DPAPI to encrypt keys at rest.
Hosting environment: Development
Content root path: D:\QuotationRepos\GTASS\src\APP
Now listening on: **http://localhost:32727HOST/APP**
Application started. Press Ctrl+C to shut down.

I set the run in port 6666 (IIS Express) but when I see the log the webserver port is 32727

Is any effect if the application only run in full .net framework instead of netcoreapp1.0 or netstandard1.5?

my porject.json file like this :
`{
  "dependencies": {
    "API": "1.0.0-*",
    "Common": "1.0.0-*",
    "Domain": "1.0.0-*",
    "Microsoft.AspNetCore.Authentication.Cookies": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Authentication.Facebook": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Authentication.Google": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Authentication.OpenIdConnect": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Diagnostics": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Identity.EntityFrameworkCore": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Mvc": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Razor.Tools": {
      "version": "1.0.0-preview1-final",
      "type": "build"
    },
    "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.StaticFiles": "1.0.0-rc2-final",
    "Microsoft.EntityFrameworkCore.SqlServer": "1.0.0-rc2-final",
    "Microsoft.EntityFrameworkCore.Tools": {
      "version": "1.0.0-preview1-final",
      "type": "build"
    },
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.0.0-rc2-final",
    "Microsoft.Extensions.Configuration.Json": "1.0.0-rc2-final",
    "Microsoft.Extensions.Logging": "1.0.0-rc2-final",
    "Microsoft.Extensions.Logging.Console": "1.0.0-rc2-final",
    "Microsoft.Extensions.Logging.Debug": "1.0.0-rc2-final",
    "Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.0.0-rc2-final",
    "Microsoft.VisualStudio.Web.CodeGeneration.Tools": {
      "version": "1.0.0-preview1-final",
      "type": "build"
    },
    "Microsoft.VisualStudio.Web.CodeGenerators.Mvc": {
      "version": "1.0.0-preview1-final",
      "type": "build"
    },
    "mongocsharpdriver": "2.2.3",
    "MongoDB.Bson": "2.2.3",
    "MongoDB.Driver": "2.2.3",
    "MongoDB.Driver.Core": "2.2.3",
    "WebGrease": "1.6.0",
    "WebMarkupMin.Core": "2.0.0-rc7"
  },

  "tools": {
    "Microsoft.AspNetCore.Razor.Tools": {
      "version": "1.0.0-preview1-final",
      "imports": "portable-net45+win8+dnxcore50"
    },
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": {
      "version": "1.0.0-preview1-final",
      "imports": "portable-net45+win8+dnxcore50"
    }
  },

  "frameworks": {
    "net46": { }
  },

  "buildOptions": {
    "emitEntryPoint": true,
    "preserveCompilationContext": true
  },

  "publishOptions": {
    "include": [
      "wwwroot",
      "Views",
      "appsettings.json",
      "web.config"
    ]
  },

  "scripts": {
    "prepublish": [ "npm install", "bower install", "gulp clean", "gulp min" ],
    "postpublish": [ "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%" ]
  }
}
`

**Comment by zenixgrace** [comment]
Hi Team,

Is the name of the web project impact when run IIS Express server ?
when I create default template aspnet 5 RC 2 site with the name of the project is "APP", I run the site with IIS Express and the site is always load.
But if I create the site with another name ex: "APS", it run smoothly using IIS Express 

Is anyone get same problem or just me?

**Comment by glennc** [comment]
This url thing could be the same issue as this: https://github.com/aspnet/IISIntegration/issues/176

The symptoms of the URL are the same at least.

**Comment by muratg** [comment]
@pan-wang Could you have a look?

**Comment by muratg** [comment]
@zenixgrace Any chance you could share your Startup.cs?   Also, what is your app project named?

**Comment by leontyr** [comment]
In my case, it's the namespace Web causing the problem.

**Comment by damienbod** [comment]
I had this problem when I was using the wrong web.config file, (Old RC1 version), Once I updated the web.config it worked. Old one was inside the wwwroot.

Greetings Damien

**Comment by zenixgrace** [comment]
@muratg I just created the ASPNET 5 RC2 site with the default web application template (No Changes) and the name of the project is "APP" and also the namespace is "APP".

I'm not sure if the "APP" site name is reserve by IIS or else.
But if I change the site name in applicationhost.config under .vs folder with the others name (ex: apps) it work. I change only the site name, and keep my project name and namespace to "APP"

The log that generate when run in IIS now don't have "HOST/APP" again (before : Now listening on: http://localhost:32727HOST/APP)

**Comment by mirhagk** [comment]
Just had this problem as well, brand new asp.net core (dotnetcore) site created through New Project wizard. Named it `web` and tried to debug IIS with access violation and aggregate exception. Saw this, went back doing the same thing but instead with `ProjectWeb` and it works fine. Definitely issues with projects named web (and app as well)

**Comment by doczoidberg** [comment]
I have the same problem with Stevens Sanderson's template. Project is not named app or web.

http://blog.stevensanderson.com/2016/05/02/angular2-react-knockout-apps-on-aspnet-core/

**Comment by muratg** [comment]
Hey folks, FYI: this bug is fixed in 1.0.0 (https://github.com/aspnet/IISIntegration/issues/176).  Once RTM version of AspNetCoreModule is released, this issue will go away.

**Comment by zenixgrace** [comment]
niceee...........

**Comment by glennc** [comment]
Closing. Re-open (presumably on the ANCM repo) if this is still an issue.
