### ISSUE TITLE
Why does "postbuild" not work?

### ISSUE THREAD

**Issue by frapid** [aspnet/Home#1463]
```
  "scripts": {
    "postbuild": [
      "xcopy /F /Y /I \"bin/Debug/netcoreapp1.0/*.*\" \"../../bin/Debug/netcoreapp1.0/\""
    ]
  }
```

and

```
dotnet build
```

Builds fine, without running the `postbuild` script. What's the missing piece of the puzzle?

**Comment by davidfowl** [comment]
It got renamed to `postcompile`

**Comment by frapid** [comment]
The tooling (Preview 1) proposes `postbuild`!???!

https://github.com/aspnet/Announcements/issues/175

The announcement does not mention the changes.

**Comment by GuardRex** [comment]
... and the schema? http://json.schemastore.org/project http://json.schemastore.org/project-1.0.0-rc2 ... still list `postbuild`.
