### ISSUE TITLE
How to exclude a directory on ASP.net Core RC2?

### ISSUE THREAD

**Issue by frapid** [aspnet/Home#1464]
I am not able to exclude a folder, namely `Areas`, from being compiled.

```
  "buildOptions": {
    "emitEntryPoint": true,
    "preserveCompilationContext": true,
    "compile": {
      "exclude": [ "Areas", "Areas/**", "Areas/*.cs" ]
    }
  },
```
I have gone through https://github.com/aspnet/Announcements/issues/175 several times and cannot figure out what's wrong in my configuration file.

**Comment by pranavkm** [comment]
cc @ajaybhargavb

**Comment by ajaybhargavb** [comment]
@frapid, to exclude `Areas` folder having just,
```JSON
"compile": {
  "exclude": "Areas/"
}
```
should suffice. I tried this and it works for me. It would be helpful if you could you push your repro somewhere and link it?

**Comment by frapid** [comment]
Thanks. I just uploaded the project.

https://github.com/frapid/frapid-core/tree/master/Frapid.Web

**Comment by ajaybhargavb** [comment]
I see you have other projects inside Areas. So I assume the files get included when those projects are built. We have a similar issue filed https://github.com/dotnet/cli/issues/2902. You could probably try excluding `*.cs` files in each of those projects.

**Comment by frapid** [comment]
What I did was this on each project:

`/Areas/<Project>/project.json`

```
  "buildOptions":{
	"compile":{
		"exclude": ["*.cs"]
	}
  },
```

and

```
  "buildOptions":{
	"compile":{
		"excludeFiles": ["*.cs"]
	}
  },
```

Both won't work. Could you please point to me to the right direction?

**Comment by ajaybhargavb** [comment]
Can you try this?
```JSON
"buildOptions":{
    "compile":{
        "exclude": ["**/*.cs"]
    }
  }
```

**Comment by frapid** [comment]
That does not work. Even if it did, why should I edit the file:

`/src/Areas/<Area>/project.json`

when I actually mean to edit:

`src/project.json`?

Makes no sense.

**Comment by pranavkm** [comment]
@frapid, a project.json at `/Areas/<Project>/project.json` doesn't make much sense. The snippet that @ajaybhargavb listed should be added to the `project.json` at the project root.

**Comment by frapid** [comment]
@pranavkm, why wouldn't it make sense? Why not? Cannot `Areas/<Project>` be an independent project?

**Comment by davidfowl** [comment]
You can't have nested projects.

**Comment by frapid** [comment]
@davidfowl, I see. That's why I want to hide the entire `Areas` directory from the root project.

**Comment by frapid** [comment]
@davidfowl, is this limitation by design? Is this going to be supported in the future? I think this limitation will be a roadblock for web applications porting from classic ASP.
