### ISSUE TITLE
Configuration build for .NET Framework

### ISSUE THREAD

**Issue by chrisdrobison** [aspnet/Home#1465]
We are using a beta build of Microsoft.Framework.ConfigurationModel.* and that has been changed to Microsoft.Extensions.Configuration.*. I notice on Nuget there are only packages for .NET Standard. Is there going to be a build for .NET Framework so that I don't have to bring down all those dependencies, most of which apparent to already exist in .NET Framework?

**Comment by chrisdrobison** [comment]
And maybe to make myself clearer, it appears that packages such as Microsoft.Extensions.Configuration.Json already have a 4.5.1 package option, but that depends on Microsoft.Extensions.Configuration which only has a .NET Standard 1.1 option.

**Comment by davidfowl** [comment]
Yea, those packages contribute nothing on .NET 4.x but it should still function. Are you seeing anything different or is this just a complaint that you have dependencies that you don't need on .NET Framework?

**Comment by chrisdrobison** [comment]
I guess I'm complaining there are more dependencies that are not needed, but I just tried downloading it and it doesn't add the extra references to the project. I suppose that's fine. I guess I just found it a little weird.
