### ISSUE TITLE
Workaround to use Azure SDK with RC2. (at least Storage)

### ISSUE THREAD

**Issue by Bartmax** [aspnet/Home#1469]
For people interested on using Azure SDK while there isn't a compatible version, I found a workaround. Is about using imports and bring a new version of the XmlSerializer as follows:

```
"dependencies":{
    "WindowsAzure.Storage": "7.0.1-preview",
    "System.Xml.XmlSerializer": "4.0.11-rc2-24027"
},
 "netcoreapp1.0": {
      "imports": [
        "dotnet5.6",
        "dnxcore50",
        "portable-net45+win8"
      ],
```

this works as standalone and portable in my _minor_ testing. I can upload and access files. That's it. Didn't try anything else, so no guarantees. **works on my machine &trade;**

**Comment by Pictuel** [comment]
Nice, do you know if we can do the same for all non compatible libraries aswell?

**Comment by davidfowl** [comment]
All? No, it depends on what frameworks a package supports?

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
