### ISSUE TITLE
Order for exception filters

### ISSUE THREAD

**Issue by msabransky** [aspnet/Home#1470]
Hi,

According to the docs filters that implement IOrderedFilter are executed in ascending order, but it seems that the exception filter with the highest order number is executed first.
Is this because the exception filter is an “after-stage” filter and therefore the order is descending?
Is there a bug in the docs? 
Is it ensured that “after-stage” filters will be executed in descending order?
Thanks,
Mike

**Comment by rynowak** [comment]
> Is this because the exception filter is an “after-stage” filter and therefore the order is descending? 

Yes

> Is it ensured that “after-stage” filters will be executed in descending order?

Yes

@danroth27 - maybe we should correct the docs. I've always liked the way the in-code docs phrase this https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Abstractions/Filters/IOrderedFilter.cs#L33

**Comment by msabransky** [comment]
Also async filters have their after method executed in descending order. That’s what puzzled me.

**Comment by danroth27** [comment]
https://github.com/aspnet/Docs/issues/1267

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
