### ISSUE TITLE
Bring back InMemory compilation.

### ISSUE THREAD

**Issue by Bartmax** [aspnet/Home#1471]
We know that InMemory compilation was removed from RC2.

What is the status of this?
Will it come back? If not, why not?

This was a critical feature for me and the experience was amazing. 
Added a lot of value to the product.
I really, really **really** miss that.

Please?

**Comment by ArieJones** [comment]
+1000

**Comment by chrisaut** [comment]
I'm getting really sad lately with asp.net core.....many of the cool things that were promised seem to silently get undone or removed (e.g project.json, this, anyone remember assembly neutral interfaces?)

Just....getting not very excited about this anymore :-(

**Comment by predragbabic** [comment]
+1k

**Comment by MaximRouiller** [comment]
Wait... it was removed?

**Comment by feliperochadev** [comment]
First project.json, now this?

asp.net core will born dead if keep this direction :/

**Comment by NatMarchand** [comment]
Have you tried the "Watch" experience ?

**Comment by Bartmax** [comment]
@NatMarchand yes I did, but it's too slow to be comparable of how it worked with in memory compilation. Also one must time the refresh if you want to avoid to see non-refreshed changes, errors, etc. Unfortunately is not a great experience.

I would love if In Memory Compilation can be used at least in some particular scenario (like when watching). Doesn't had to be a always thing.

**Comment by Bartmax** [comment]
related: https://github.com/dotnet/cli/issues/3609

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
