### ISSUE TITLE
WebHostBuilder.UseStartup<>() Must have a constraint for class type

### ISSUE THREAD

**Issue by xumix** [aspnet/Home#1472]
Something list this:

```
public static IWebHostBuilder UseStartup<TStartup>(this IWebHostBuilder hostBuilder) where TStartup : class, IAppStartup
```

Or even a base class with required constructor, so I know from the beginning what method must be implemented.

There is NO way for me at the moment to understand the Startup class methods and their signature w/o reading some examples and docs or launching the app.

**Comment by NatMarchand** [comment]
You can't have any constraint as those methods signatures are not always the same because of the dependency injection.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
