### ISSUE TITLE
Project.json and output path in ASP.net Core RC2

### ISSUE THREAD

**Issue by frapid** [aspnet/Home#1473]
How can I change the output path in project.json?

**Comment by zenixgrace** [comment]
maybe this [article](https://github.com/aspnet/Announcements/issues/175) can help

**Comment by frapid** [comment]
Maybe not

**Comment by davidfowl** [comment]
No you cant

**Comment by frapid** [comment]
@davidfowl, I know I can change output directory by passing a command argument to dotnet build. But what about dynamic compilation? How can I make sure assemblies are produced on correct folder?

**Comment by davidfowl** [comment]
I'm not sure what you mean about dynamic compilation? Do you mean Razor views?

**Comment by frapid** [comment]
I am referring to Roslyn auto compiler as Scott Hanselman has mentioned in this blog post:

http://www.hanselman.com/blog/IntroducingASPNETVNext.aspx

**Comment by davidfowl** [comment]
Dynamically compiled views are in memory.

**Comment by frapid** [comment]
I am not referring to Views.

From Scott Hanselman's blog:

> One of the great aspects of environments like node or rails is that they are "no compile." Just change some code and hit refresh. With the next version of ASP.NET you get the power and throughput of the .NET runtime plus the "Roslyn" compiler-as-a-service for a "no-compile compile." That means means during development time you can just change your C# classes and hit Refresh in the browser. It's the power of .NET with the dynamism of a refresh-and-go development experience.

**Comment by davidfowl** [comment]
Dynamic compilation is gone in RC2. It only exists for views now.

**Comment by frapid** [comment]
@davidfowl, I see. Everything is too confusing now. Could you point me to a documentation which mentions what's changed in RC2?

**Comment by tugberkugurlu** [comment]
@frapid see https://github.com/aspnet/Announcements/issues/177. There are some links there which mention what have been changed.

Also, somehow related to https://github.com/aspnet/Home/issues/1471

**Comment by frapid** [comment]
@davidfowl, @tugberkugurlu: Isn't it a good idea to configure the build output directory in `project.json`? This might be useful for cases when you build a project which triggers others (dependencies) and you wished it would be nice to have output directories configured for each of your projects separately.

My two cents.

**Comment by GuardRex** [comment]
@frapid Try these ...

https://github.com/aspnet/Announcements/issues?q=is%3Aopen+is%3Aissue+milestone%3A1.0.0-rc2
https://docs.asp.net/en/latest/migration/rc1-to-rc2.html
https://github.com/dotnet/cli/issues/2135#issuecomment-212692267

**Comment by jasselin** [comment]
@davidfowl Will dynamic compilation ever make a comeback for anything other dans views?

**Comment by davidfowl** [comment]
@jasselin There are no plans to bring it back.

**Comment by jasselin** [comment]
@davidfowl Just curious, why did you drop the feature and decide not to reimplement it?

**Comment by davidfowl** [comment]
Architectural challenges and changes require to implement it on both .NET Framework and .NET Core. We did it with dnx and there were some problems (like some things being completely broken with in memory assemblies) that we chose to just avoid.
