### ISSUE TITLE
'Could not be found error' when creating project called 'ASP.NET Core Web Application (.NET Framework)'

### ISSUE THREAD

**Issue by jculverwell** [aspnet/Home#1476]
I'm using RC2 with VIsual Studio 2015 update 2.

If a create a new project which targets the full .Net Framework and call the project 'ASP.NET Core Web Application (.NET Framework)' I get five errors, see below for an example:

c:\users\xxxx\documents\gihub\ASP.NET Core Web Application (.NET Framework)\src\ASP.NET Core Web Application (.NET Framework)\error CS2001: Source file 'c:\users\xxxx\documents\gihub\ASP.NET Core Web Application (.NET Framework)\src\ASP.NET Core Web Application (.NET Framework)\Core' could not be found.

If I then create a new project in the same solution, again targeting the full .Net Framework, but call the project something without spaces/brackets/periods like 'ASPNETCoreNetFramework' it works fine.

Leads to me think the projects with 'funky characters' in the project name are causing this issue.

**Comment by jculverwell** [comment]
I should add that I was creating a WebAPI project

**Comment by kenancasey** [comment]
I had this same error with RC2 with a project name with spaces in it.

**Comment by mlorbetske** [comment]
It looks like this may be related to this https://github.com/dotnet/cli/issues/3221

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
