### ISSUE TITLE
Expect required library hostpolicy.dll to be present in [path]

### ISSUE THREAD

**Issue by frapid** [aspnet/Home#1480]
Installed ASP.net RC2 and Preview1 tooling for Visual Studio. I created a new project from:

- File
- New Project
- ASP.NET Core Web Application (.NET Core)

Once the project is created
- Click on the Play button `IIS Express`.

A browser tab is displayed and debugging stops. When you "Browse With" or "Control + Shift + W", a new browser tab is displayed trying to show something indefinitely.

**On Command Prompt**
```
dotnet restore
dotnet build
dotnet run
```

will show this

```
Project WebApplication1 (.NETCoreApp,Version=v1.0) was previously compiled. Skipping compilation.
Expect required library hostpolicy.dll to be present in [......\WebApplication1\bin\Debug\netcoreapp1.0]
  - This may be because of an invalid .NET Core FX configuration in the directory.
```

**System Information**

`dotnet --version`
1.0.0-rc2-002476

**Operating System**
Windows 8.1

Visual Studio
```
Microsoft Visual Studio Community 2015
Version 14.0.25123.00 Update 2
Microsoft .NET Framework
Version 4.6.01055

Installed Version: Community

Visual Basic 2015   00322-20000-00000-AA198
Microsoft Visual Basic 2015

Visual C# 2015   00322-20000-00000-AA198
Microsoft Visual C# 2015

Visual C++ 2015   00322-20000-00000-AA198
Microsoft Visual C++ 2015

Application Insights Tools for Visual Studio Package   5.2.60328.3
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2015.1   14.1.20512.0
ASP.NET and Web Tools 2015.1

ASP.NET Web Frameworks and Tools 2012.2   4.1.41102.0
For additional information, visit http://go.microsoft.com/fwlink/?LinkID=309563

ASP.NET Web Frameworks and Tools 2013   5.2.40314.0
For additional information, visit http://www.asp.net/

Azure App Service Tools v2.8.1   14.0.11123.0
Azure App Service Tools v2.8.1

Common Azure Tools   1.7
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

JetBrains ReSharper Ultimate 10.0.2   Build 104.0.20151218.120627
JetBrains ReSharper Ultimate package for Microsoft Visual Studio. For more information about ReSharper Ultimate, visit http://www.jetbrains.com/resharper. Copyright © 2016 JetBrains, Inc.

Microsoft .NET Core Tools (Preview 1)   14.1.20512.0
Microsoft .NET Core Tools (Preview 1)

Microsoft Azure Mobile Services Tools   1.4
Microsoft Azure Mobile Services Tools

NuGet Package Manager   3.4.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

PreEmptive Analytics Visualizer   1.2
Microsoft Visual Studio extension to visualize aggregated summaries from the PreEmptive Analytics product.

SQL Server Data Tools   14.0.60311.1
Microsoft SQL Server Data Tools

TypeScript   1.8.31.0
TypeScript tools for Visual Studio

Web Compiler   1.11.312
Compiler for LESS, Sass and CoffeeScript files

Web Essentials 2015.2   2.0.214
Adds many useful features to Visual Studio for web developers. Requires Visual Studio 2015
```

**Comment by moozzyk** [comment]
Can you check this:
https://github.com/dotnet/cli/issues/2859 or this https://github.com/dotnet/cli/issues/2572?

**Comment by frapid** [comment]
Already landed on those pages through search engines.

I am doing nothing fancy, not even a single line of code is touched on what RC2 Preview 1 tooling generates for "ASP.NET Core Web Application".

**Comment by frapid** [comment]
Does a solution for this exist?

**Comment by moozzyk** [comment]
This is probably environmental because I tried and things work. The first thing to do is to check your dotnet. You list rc2 but the one that shipped as part of rc2 should be `1.0.0-preview1-002702` - so yours is ancient.

**Comment by moozzyk** [comment]
I know what it is! It's this: https://github.com/dotnet/cli/issues/2959 - clean old runtimes in your `%PROGRAMFILES%\dotnet`.

**Comment by frapid** [comment]
@moozzyk. Thank you for the info. What's the place I obtain RC2 from? I downloaded and installed RC2 on the very first day of release from:

https://www.microsoft.com/net/download

**Comment by frapid** [comment]
What does clean imply?

1. deleting `sdk/1.0.0-rc2-002476`
2. deleting `skd/1.0.0-rc2-002476/runtimes`

I just want to confirm. That's #1 for me.

**Comment by moozzyk** [comment]
@frapid the official guidance (https://www.microsoft.com/net/core#windows) is to use add/remove programs. If this does not work (and this is what I actually had to do) try removing all non preview1  folders from `dotnet\sdk` and all `shared\Microsoft.NETCore.App\*` that are older than `1.0.0-rc2-3002702` and possibly all `dotnet\swidtag` that match what you have removed.

**Comment by marchy** [comment]
I am getting this same message despite being on RC2 (version "1.0.0-preview1-002702") and having uninstalled RC1 prior to installing RC2.

I checked the folders above (%PROGRAMFILES%\dotnet) but there is only the 002702 version in there. What else could be causing this?

**Comment by kierenj** [comment]
I'm getting this issue, and I never installed RC1.  As with @marchy I only have 002702.

**Comment by jltrem** [comment]
I have the same issue as @marchy and @kierenj -- only 002702 is installed.  I did have RC1 installed but the VS Update 2 uninstalled that before installing RC2.  Is there another issue that is tracking this problem?

**Comment by kierenj** [comment]
@jltrem I tracked my issue down and created a new issue #3453 - is it the same for you?

**Comment by jltrem** [comment]
@kierenj I no longer have the issue -- it was solved by restarting Visual Studio.  Thanks.

**Comment by marchy** [comment]
Thank @kierenj, that didn't seem to be the issue for us though. We've had 'emitEntryPoint' in there since this is a MVC application, that's not it.

Team what else could this be? This is blocking us from pushing to Azure. Solution runs fine in Visual Studio locally.

**Comment by Jose-CF** [comment]
+1 ... any solution for this issue? terrible, cannot run anything.
