### ISSUE TITLE
I need RC1 version of ".NET Core Windows Server Hosting"

### ISSUE THREAD

**Issue by giancarloa** [aspnet/Home#1481]
hello there... i hope you are all doing well... first and foremost congrads on the rc2 release...

i have a problem... i don't have time at this moment to upgrade my asp.net core RC1 app to RC2 although i certainly plan to do so soon... but in the meantime i need to deploy for the first time my RC1 app to a windows server 2008... i am following the iis publishing instructions found here: https://docs.asp.net/en/latest/publishing/iis.html#install-the-net-core-windows-server-hosting-bundle ... but the problem is that the download link for the ".NET Core Windows Server Hosting bundle" has already been updated to RC2... but my app is still RC1 so i don't think that will work... can anyone please provide a link for the RC1 version of the ".NET Core Windows Server Hosting bundle"???? even if i did have time to update to RC2, the server we are using is windows 2008 yet the supported platforms for RC2 is 2012 and above... RC2 does not appear to support windows server 2008... again can anyone provide a link for the RC1  ".NET Core Windows Server Hosting bundle"???? thank you so much!!!!

**Comment by rdefreitas** [comment]
There is a switch in the lower right portion of the navbar that lets you switch versions of the docs.

https://docs.asp.net/en/1.0.0-rc1/publishing/iis.html

**Comment by giancarloa** [comment]
@rdefreitas ... thank you thank you

**Comment by GuardRex** [comment]
@giancarloa I'm not sure where you saw that. .NET Core is supported on WS 2008 R2 and above. However, it is true that the ASP.NET Core Module (in the server hosting bundle) does not support RC1-era applications. You are correct in that you do need the HTTP Platform Handler, as @rdefreitas pointed you to.

**Comment by giancarloa** [comment]
thanks @GuardRex ... in the rc1 version of the documentation it says windows 2008 r2 (https://docs.asp.net/en/1.0.0-rc1/publishing/iis.html#supported-operating-systems)... is it correct then to say that with rc2 windows 2008 r2 is NOT supported???? thanks

**Comment by GuardRex** [comment]
2008R2 has been continuously supported. The only major difference is that with rc1, you must use the `HTTP Platform Handler` (often called "HPH") (and it had a number of missing features), while on rc2, you must use the `ASP.NET Core Module` (often called "ANCM") (part of the Windows Server Hosting Bundle).

https://docs.asp.net/en/latest/publishing/iis.html

**Comment by johanskoldekrans** [comment]
What if you run the nightly builds 1.1.0-alpha*. Latest only gives me version 1.0.0 still. Is there a secret switch or will those links get updated when new versions are built?

**Comment by GuardRex** [comment]
We'll get the hosting bundle and ANCM as they are released. The next release will be 1.0.1 (soon ... https://blogs.msdn.microsoft.com/dotnet/2016/07/15/net-core-roadmap/ ), and I expect we'll get a new bundle/ANCM when that comes out if their pattern holds.

They're working on open-sourcing the ANCM. At that point, we should be able to keep up with module "nightly;" although, I get the impression that the module gets attention in spurts, so it probably won't be a "nightly" thing ... more of a "whenever they're working on it thing." :smile:
