### ISSUE TITLE
StaticFile not served by IIS

### ISSUE THREAD

**Issue by Pictuel** [aspnet/Home#1482]
my app is a port from rc1 to the last rc2, everything works well on IIS Express,
but when I publish to a local IIS on a new built staging environment static files respond by a 404 http error code even if they're on the good location.

I'm confused because local content like the logo, override css file... don't work while external links work.
I don't know what to do right now.

**Comment by cesarbs** [comment]
How are you publishing your app to IIS? Are you running `dotnet publish-iis` after `dotnet publish`?

**Comment by moozzyk** [comment]
or maybe you did not include the folder containing static files in publishOptions. Note that wwwroot is no longer included in publish output by default so you need to do have something like this in your project.json file:

```
  "publishOptions": {
    "include": [
      "wwwroot",
      "web.config"
    ]
  },
```

**Comment by GuardRex** [comment]
Side Note: Make sure the folders you list (`wwwroot` or `logs` or whatever) isn't empty. There's a known bug slated to be fixed by RTM, where a folder that is empty will not be moved to published output.

**Comment by Pictuel** [comment]
thanks for the answers, these led me to fix my issue, I was publishing with:

dotnet restore
dotnet publish --configuration Release --output ../../../approot

I wasn't including anything, I was moving them manually on a separate folder, I mean approot and wwwroot side by side. by doing a standard publish with these settings and linking iis to the approot made it.

My concern now is about security, is there any issue to make the domain root on the approot directly ?
Is there any advice to take care of, before publishing for real?

**Comment by GuardRex** [comment]
If you're porting to rc2, the concept of `approot` has gone away. I mean you can call the content root path folder that holds the app that if you want to, but the output is flat. `wwwroot` is actually published **inside** of your content root path (app base path) now. To see the layouts, check out https://github.com/dotnet/cli/issues/937#issuecomment-186737388.

If everything is going well for your port and you're headed to IIS, I have helpful links at https://github.com/dotnet/cli/issues/2135#issuecomment-212692267 and I also have a WIP doc at the #iis channel at Slack: http://tattoocoder.com/aspnet-slack-sign-up/

**Comment by Pictuel** [comment]
Thank you very much guys :)
