### ISSUE TITLE
Best way to pipe/proxy request?

### ISSUE THREAD

**Issue by timmydo** [aspnet/Home#1483]
I'm trying to figure out the best way I can emulate this sort of behavior that I can get in nodejs/express:

```
app.use('/api', function(req, res) {
  var url = 'http://localhost:5000/api' + req.url;
  req.pipe(request(url)).pipe(res);
});

app.listen(3000, function () {
  console.log('Example app listening on port 3000!');
});
```

Basically, requests come in on port 3000, if they have /api/xyz, I pass them to localhost:5000. I pass the response back verbatim.

I've started going down the path of 

```
            app.Run(async context =>
            {
                Console.WriteLine("Request: " + context.Request.Path);
                if (context.Request.Path.StartsWithSegments("/api"))
                {
                    Console.WriteLine("API Request: " + context.Request.Path);
                    await HandleApiRequestAsync(context);
                    return;
                }
                context.Response.ContentType = "text/html";
                var bytes = File.ReadAllBytes("wwwroot/index.html");
                await context.Response.Body.WriteAsync(bytes, 0, bytes.Length);
            });
```

but `HandleApiRequest` is turning out to be a pain because of the differences between the aspnet core and system.net.http (httpclient). Is there a better way?

Is there a better way to do this?

**Comment by pranavkm** [comment]
Have you looked at Proxy middleware - https://github.com/aspnet/Proxy/blob/dev/samples/Microsoft.AspNetCore.Proxy.Samples/Startup.cs?

**Comment by timmydo** [comment]
Just what I was looking for but couldn't find!
:+1:
