### ISSUE TITLE
web.Release.config not merging into web.config on publish

### ISSUE THREAD

**Issue by chassq** [aspnet/Home#1485]
Hey,
Trying to insert a rewrite rule into my web.config when the site is published in Release. So far no luck. Does RC2 support this in the publish process?

Thanks!

Files attached in next comment

**Comment by chassq** [comment]
[web.configs.zip](https://github.com/aspnet/Home/files/275818/web.configs.zip)

**Comment by Tratcher** [comment]
web.config transforms like web.release.config is not supported.

**Comment by GuardRex** [comment]
@chassq You could provide that logic in a homebrew tool that would make modifications to the `web.config` in published output as a `postpublish` operation. For example, I do this to enable logging and change the log filepath. https://github.com/GuardRex/GuardRex.AspNetCore.Server.IISIntegration.Tools

It's based on cloning the bits in @moozzyk `publish-iis` tooling: https://github.com/aspnet/IISIntegration/tree/dev/src/Microsoft.AspNetCore.Server.IISIntegration.Tools

**Comment by chassq** [comment]
Much thanks! Will check it out.
