### ISSUE TITLE
How to run SSL on RC2 from console?

### ISSUE THREAD

**Issue by dlebedynskyi** [aspnet/Home#1486]
## Intro

We need to run app on https for development since it integrates with other services that are https/wss only. 
in RC1 in project.json we had

```
"commands": {
"express": "Microsoft.AspNet.Hosting --server Microsoft.AspNet.Server.WebListener"
}
```

that allowed us to run command in console `dnx express -- server.urls https:\\localhost:43431\`. 
## Steps to reproduce

Current dotnet has run  method that launches on localhost:5000 and does not take any params.  
With new Visual Studio 2015 update 2 new project on RC2 you can get launchSettings.json that allows you to specify sslPort for IISExpress. 
So there is  way to run standard app on IIS express with ssl. 
But there is no way (at least documented) to do it from console. We would like to stay away from VS as far as possible and we need your help with this. 

Documentation is saying that 
`dnx command`    is N/A in `CLI command` and it is by design. 

So what is new design to do same:
1. how do launch WebListener/Kestrel with SSL form console now? 
2. How to pass custom port from command line or configure `dotnet run` to use lauchSettings.json? 
3. Is there a way to run it on mac/linux with ssl support? 

I know there is Kestrel.https now but example is very poor. Only example there is required hardcoding of port and certificate in program.cs. 
https://github.com/aspnet/KestrelHttpServer/blob/dev/samples/SampleApp/Startup.cs#L51

PS. was asked to open issue here by dotnetl/cli team  
https://github.com/dotnet/cli/issues/3072

**Comment by davidfowl** [comment]
You need to write code to do so, you can't do it from the command line.

**Comment by dlebedynskyi** [comment]
@davidfowl ok. 
But does this means that VS does this automatically every time on run? 
maybe there is a way to not put basically configuration code into app? I really don't want to put this into program.cs.

**Comment by Tratcher** [comment]
Try this sample:
https://github.com/aspnet/Security/blob/dev/samples/SocialSample/Program.cs
https://github.com/aspnet/Security/blob/dev/samples/SocialSample/Properties/launchSettings.json#L25

**Comment by dlebedynskyi** [comment]
@Tratcher Thanks will check it.
