### ISSUE TITLE
RC2 IP Address problem

### ISSUE THREAD

**Issue by Pictuel** [aspnet/Home#1487]
Hi, I'm using this method to get remote ip address from the clients that browse my app

public static string GetClientIPAddress(this HttpContext context) => context?.Connection?.RemoteIpAddress?.ToString();

but it only gives me 127.0.0.1 which seems to be local, I don't know if there is a better way to do get the IP used by the clients, but this method seems broken actually, I waited for RC2 wishing this feature to be ready but it seems it isn't the case for the moment.

**Comment by GuardRex** [comment]
Do they need to be forwarded? I'm doing something a little different here with my own code that reads it directly, but take a look at this: https://github.com/aspnet/BasicMiddleware/blob/dev/samples/HttpOverridesSample/Startup.cs#L13

**Comment by GuardRex** [comment]
Note that `.UseIISIntegration()` should do it automatically. https://github.com/aspnet/Announcements/issues/164

**Comment by Pictuel** [comment]
still nothing :|

**Comment by GuardRex** [comment]
:rat: Rats! :rat: Perhaps open this over in https://github.com/aspnet/BasicMiddleware/issues and @Tratcher is watching :eyes: and will say what the prob probably is.

**Comment by joaomello** [comment]
@Pictuel in Configure add:

``
app.UseForwardedHeaders(new ForwardedHeadersOptions
{
    ForwardedHeaders = ForwardedHeaders.XForwardedFor
 });``

**Comment by Tratcher** [comment]
Is this local or running in Azure? There's a known issue in Azure: https://github.com/aspnet/IISIntegration/issues/140

**Comment by joaomello** [comment]
I use that code on azure... and worked

**Comment by Pictuel** [comment]
Thank you very much @joaomello that works for me too on azure. That is actually confusing to register the option twice with different settings to get it working tho. I should take a closer look at it once I got the time. Many thanks!

**Comment by Tratcher** [comment]
You should only need:
```
services.Configure<ForwardedHeadersOptions>(options =>
{
  options.ForwardedHeaders = ForwardedHeaders.XForwardedFor;
});
```
Not the other one.

**Comment by Pictuel** [comment]
I'll try @Tratcher Thanks!
