### ISSUE TITLE
Q about the Frameworks piece of project.json

### ISSUE THREAD

**Issue by rhires** [aspnet/Home#1488]
Granted, this is likely going to change somewhere down the line, but I'm confused in the meantime:

`"imports": ["dnxcore50", "portable-net45+win8"]`

What do the `dnxcore50` and `portable-net45+win8` refer to? Even though the examples show that these are necessary, their names confuse me, and I wasn't able to find any explanation (easily) of what they do/mean...can someone take these apart so I can gain some understanding (and stop being confused)? :-) Thanks!

**Comment by GuardRex** [comment]
They refer to TFM's that packages may claim to support. `dnxcore50` is just an old moniker for Core CLR. The other one is for packages that support .NET 4.5 and Win8. These `imports` basically say, "Use packages that support these regardless of the TFM I'm specifying for this app ... I'm telling you they will work." Of course, that might not be the case. If it isn't true, the app will `dotnet restore` just fine and :boom: at runtime. The goal is for lib authors to support the correct TFM's and thus the goal is that your apps will not need `imports` in the future.

Docs are catching up, and you will eventually find more info on this at: http://dotnet.github.io/docs/
If you dig around at http://docs.nuget.org/consume/ProjectJson-Intro, you might find some more info there.

**Comment by rhires** [comment]
Thank you!
