### ISSUE TITLE
RC2 Localization throwing MissingManifestResourceException

### ISSUE THREAD

**Issue by GarageWeb** [aspnet/Home#1489]
I have created a simple console app here: https://github.com/GarageWeb/ResourceTest to demonstrate the issue. 

This worked previously.

**Comment by GarageWeb** [comment]
So, if I move the .resx files to the root of the project instead of in a sub-folder, it works as expected. I have tried every way to embed from a sub-folder and it no longer works. For now I will use this workaround, but I suspect this is a bug.

**Comment by Luca7993** [comment]
Same problem here...

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
