### ISSUE TITLE
Suggested flow to deploy RC2 to azure web app

### ISSUE THREAD

**Issue by bragma** [aspnet/Home#1493]
After converting my PR1 project to RC2, I need to update my azure web app with it. What's the suggested path? There are some references in the official RC2 announcement to "wait for Azure Blog for something to happen" but 7 days after, we are still waiting and I need to deploy now.
Thanks a lot!

**Comment by bragma** [comment]
I've managed to deploy on Azure manually. My target is "net461", probably targeting .NET Core would not work due to missing environment on Azure's servers. What follows may be useful to anyone with my same problems, but I am not implying it's be best way to deploy on Azure. In fact, I'd like to be corrected by someone with more experience than me and make the flow more streamlined.

It seems to me that the "dotnet publish" command is not doing what's needed to make things work on Azure. I've issued the command:

"dotnet deploy -c Release -o bin\approot"

This generated an approot folder with all needed stuff, but unsurprisingly files were not placed where needed.

My project.json contained the suggested:

```
	"publishOptions": {
		"include": [
			"wwwroot",
			"appsettings.json",
			"app.config",
			"web.config"
		]
	},
```

But this creates a structure where: approot contains executables, dlls, appsettings, app.config, web,config and wwwroot. Inside wwwroot there are files taken from the project's wwwroot folder.
Azure Web Apps expect 2 folders, all rooted on the same "site" folder: "site/approot" and "site/wwwroot".

My quick and dirty change is:

```
  "publishOptions": {
    "mappings": {
      "../wwwroot/appsettings.json": "appsettings.json",
      "../wwwroot/app.config": "app.config",
      "../wwwroot/web.config": "web.config"
    }
  }
```

This creates 2 folders on the same level: approot and wwwroot wherever I decide to output the deploy's results. Notice that the suggested "project.json" contains:

```
"scripts": {
	"postpublish": [ "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%" ]
}
```

This generates a web.config file that does not work (with my current setup). It expects the app executables to be in its same folder, while on Azure it is not (i.e. web.config is in wwwroot, while the app executable is in approot). I had to change the %publish:OutputPath% value manually with something like "../approot/<appexecutable>".
The generated approot and wwwroot folders can be copied manually to Azure's server (as an example through Kudu's interface).

**Comment by Pictuel** [comment]
I asked a question that led me to the right way to do, #1482 
First now the context of approot is gone, you can call it whatver you want, it'll be the root folder for your app to set in azure.
Secondly, let web.config and all the files required in your app base root, include wwwroot also.

When you'll do

dotnet restore
dotnet publish --configuration Release --output ./publish

from the package manager you'll see the folder is almost ready just be sure the web config is done with the config you wish.
And then you just have to upload to azure with ftp and you're done.

Hope it helps!

**Comment by bragma** [comment]
@pictuel thanks a lot! So if I understand correctly everything in the local "publish" folder needs to be copied in azure's site folder. I'll have to try it because I fear a bit of what will happen of the existing content (I.e. Webjobs in "App_Data" and other stuff created directly by azure.

**Comment by bragma** [comment]
Rethinking at what I wrote, can I keep the app content in a separate folder and set the folder anywhere in azure's panel?

**Comment by Pictuel** [comment]
you should try on a local iis server, therefor on azure dont delete anything if you're not sure, copy the folder below the site directory and then link your azure setting to the new folder just to test if it works as you wish. In case it dosen't just relink to the old folder.

**Comment by moozzyk** [comment]
web.config was moved to the approot and therefore publish-iis creates the web.config in the approot location. You can find more details in [this announcement](https://github.com/aspnet/Announcements/issues/173). If you want continue to have web.config in wwwroot you can find how to do this [here](https://github.com/aspnet/IISIntegration/issues/164).

If you install tooling for VS (preview1) you can deploy you application directly from VS.

You can deploy standalone apps to Azure for a while now and as of last week the rc2 runtime was installed and you can also publish portable apps.

**Comment by bragma** [comment]
Thank you all, tomorrow I'll make some tests. The new layout makes sense. I still don't like azure placing the webjobs in my application root, but that's another topic.

**Comment by bragma** [comment]
I did it! Thanks a lot! I've created an approot folder and set it as the application root in Azure, then deployed in it and now I have my webjobs nicely separated from my main app. The only hiccup I had was when using the existing deploy profile which needed to be updated.

**Comment by Pictuel** [comment]
congrats! :+1:
