### ISSUE TITLE
ApplicationParts with settings

### ISSUE THREAD

**Issue by lszomoru** [aspnet/Home#1496]
I have started looking at ApplicationParts to build a modular MVC application. As each of my application parts has a settings files I was wondering if there is any guidance on how to dynamically load the settings for all application parts in Startup.cs (similar to the pattern to load all assemblies for from Plugins folder documented [here](https://github.com/aspnet/Mvc/issues/4089). Thanks!

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
