### ISSUE TITLE
RC2 problems

### ISSUE THREAD

**Issue by Robelind** [aspnet/Home#1497]
I've installed the RC2 into Visual Studio 2015 update 2.
When I create a new ASP.NET Core Web Application and open Index.cshtml "ViewData" is in red and mouse hover says "Cannot resolve symbol 'ViewData'". If I add a model directive it's "Cannot resolve symbol 'model'", same for "@Html".
If I run the app everything works as expected, though.

**Comment by rwasef1830** [comment]
I see this too, seems to be a resharper issue. Shows all razor properties in red, but works fine.

**Comment by davidames** [comment]
Def a Resharper 2016.1.1 issue.  Resharper 2016.2 should take care of this.

In the mean-time to disable Resharper checking of cshtml files (and suppress the red) goto:

Rehsharper => Options => Code Inspection => Settings => Elements to Skip and add a *.cshtml file mask.

**Comment by JosephWoodward** [comment]
I can confirm that upgrading to Resharper 2016.2 does solve this. Thanks!

**Comment by psulek** [comment]
@JosephWoodward @davidames  Resharper 2016.2@Beta4 works for RC2 but it does **NOT** work for RC1. We have issues with upgrading RC1 -> RC2 (VS tooling issues) so we stick with RC1 until RTM.

**Comment by stevenlupo** [comment]
I installed ReSharper 2016.2 and I have VS 2015 Update 3 and still have this problem.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
