### ISSUE TITLE
.NET Core Plans to Drop project.json, realy?

### ISSUE THREAD

**Issue by apphost** [aspnet/Home#1498]
https://www.infoq.com/news/2016/05/project-json

Is that true?

**Comment by bragma** [comment]
It seems so. I saw a fight start because of this, and maybe we should not start another here. I'll just record my displeasure, I really liked the project.json.

**Comment by apphost** [comment]
I like project.json too  :(

**Comment by simonmurdock** [comment]
But this way you have the same format project file for all types of projects.

**Comment by bragma** [comment]
@simonmurdock there are pros and cons with the choice. What is evident is that people loved project.json for several good reasons and I hope that the lesson won't be ignored. I'll just say that all my new projects were in "NET Core" format even when targeting .NET 4.x due to the new project format. We'll miss it.

**Comment by bragma** [comment]
Btw, this is the proper place for discussing it. Whatever your opinion is, let yourself be heard here:

[https://github.com/aspnet/Home/issues/1433](https://github.com/aspnet/Home/issues/1433)

**Comment by MaximRouiller** [comment]
Already covered here: 

https://github.com/aspnet/Home/issues/1433

**Comment by VSG24** [comment]
You can't put comments in json file. That's enough for not using it for storing config files.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
