### ISSUE TITLE
debugging under mono in VS Code with dotnet CLI

### ISSUE THREAD

**Issue by tugberkugurlu** [aspnet/Home#1502]
Is debugging under mono in VS Code with dotnet CLI possible today?

**Comment by davidfowl** [comment]
The .NET CLI is a toolchain for everything but it's only a runtime for .NET Core. When you run apps on net4x on non windows you're using regular mono (as in, you can do `dotnet build`, `mono bin/Debug/net451/App.dll`). Newer versions of mono support portable pdb so in theory it should be workable using https://marketplace.visualstudio.com/items?itemName=ms-vscode.mono-debug
