### ISSUE TITLE
ASP.NET Core web application (targeting .NET 4.6.1) not able to reference a class library (targeting  .NET 4.6.1)

### ISSUE THREAD

**Issue by stevesiu** [aspnet/Home#1505]
I'm using Visual Studio 2015 Update 2 with Microsoft .NET Core Tools (Preview 1) and ASP.NET Core RC2.  I encountered the following issue.

ASP.NET Core web application (targeting .NET 4.6.1) is not able to reference a class library (targeting  .NET 4.6.1).  These are the steps to reproduce the issue:

1. Create a website project "WebApplication1" using the template "ASP.NET Core Web Appliction (.NET framework)" targeting .NET 4.6.1.
2. Create a class library project (targeting .NET 4.6.1) named "ClassLibrary1". Build it.
3. In "WebApplication1", add a reference to the "ClassLibrary1" project.
4. Add this line in "/Views/_ViewImports.cshtml":
`@using ClassLibrary1`
5. Launch the "webApplication1" and you will encounter the following error:

An error occurred during the compilation of a resource required to process this request. Please review the following specific error details and modify your source code appropriately.

`/Views/_ViewImports.cshtml`

The type or namespace name 'ClassLibrary1' could not be found (are you missing a using directive or an assembly reference?)
`@using ClassLibrary1`

IntelliSense could detect the existence of the ClassLibrary1 and allowed me to navigate to classes in the library.

If I create an ASP.NET core website targeting .NET core referencing a class library targeting .NET core, I won't have such issue.

I'm wondering if anyone encounters the same issue.

**Comment by pranavkm** [comment]
@stevesiu seems like you're running into https://github.com/aspnet/Razor/issues/755. https://github.com/aspnet/Razor/issues/755#issuecomment-220732700 has a possible workaround for this issue in RC2.

**Comment by stevesiu** [comment]
@pranavkm  Thank you very much for your prompt reply and pointing me to the workaround.  The issue was resolved after the following AddRazorOptions line was added to the ConfigureServices method in the Startup.cs file.

```
services.AddMvc()
                .AddRazorOptions(options =>
                {
                    var previous = options.CompilationCallback;
                    options.CompilationCallback = context =>
                    {
                        previous?.Invoke(context);

                        context.Compilation = context.Compilation.AddReferences(Microsoft.CodeAnalysis.MetadataReference.CreateFromFile(typeof(ClassLibrary1.Class1).Assembly.Location));
                    };
                });
```
