### ISSUE TITLE
HTTP Platform Handler for Apache

### ISSUE THREAD

**Issue by ygoe** [aspnet/Home#1506]
I'd like to have an equivalent of the HTTP Platform Handler (or whatever it's called today) for the Apache web server on Linux (Ubuntu). I know that I can set up a reverse proxy in Apache and start Kestrel on a local TCP port. But that requires manual work for starting the dotnet process, keeping it running (in case it ends), finding a free TCP port (or a free UNIX socket path if that's possible) and wiring it all together. All that is already automated for IIS on Windows servers, and I consider it an essential part of ASP.NET. Cross-platform isn't complete without tools to actually run things under production conditions.

Apache can run PHP through FastCGI and SuExec just fine (I'm using it for over 12 years). That makes Apache and PHP cross-platform. Unless ASP.NET Core provides the same level of support, I cannot use it anywhere.

I don't care too much about how this is technically done. FastCGI, UNIX sockets, TCP sockets and HTTP proxy, all is fine if it allows running the ASP.NET application under a specified system user account that is not used for the web server.

A nice and simple configuration might be a mapping of URL paths (of a certain virtual host) to application paths on disk, together with a user name to run it. The web server integration would then start the external process and find an appropriate way to communicate with it. Just like in IIS, the process might be terminated after some idle time or kept running all the time.

I've seen a web page about nginx integration recently but I can't find it anymore. Anyway, nginx is not the web server on my production server (and I can't change that) so that won't help me.

**Comment by moozzyk** [comment]
Have you tried nginx? Yes, you will have to configure it - @BrennanConroy has a [PR](https://github.com/aspnet/Entropy/pull/120/files) where he uses nginx in tests which should help you figure out how to configure things.

**Comment by dg9ngf** [comment]
I'm using Apache in an established shared hosting environment with all sorts of custom tools involved. No, I haven't tried to change all that.

**Comment by davidfowl** [comment]
https://httpd.apache.org/docs/current/mod/mod_proxy.html

**Comment by dg9ngf** [comment]
Yes, that's what I said. But it doesn't do everything else that HTTP Platform Handler for IIS does, i.e. start processes, find where to proxy through to etc. With IIS you don't configure everything you need to configure with mod_proxy. That's the gap I'd like to see closed.

**Comment by davidfowl** [comment]
We're not going to be writing an apache module (at least not in the short term). If you *need* to use apache then you'll need to use mod_proxy, it's the equivalent of http platform handler for apache and likely battle tested. I'm not exactly sure what you're looking for. 

Can you be more specific? What exactly do you want?

**Comment by dg9ngf** [comment]
As I said before, mod_proxy alone doesn't proxy anywhere useful. There must be the web application process running at the other end. And as far as I understand it, HTTP Platform Handler also cares about starting the external process, keeping it running and writing stdout logs somewhere.

I believe I've seen an overview recently that listed HTTP Platform Handler for IIS, some software that I've forgotten for nginx, and nothing for Apache. I just can't find that web page anymore. So if I haven't just dreamt that, there would be that kind of thing I'm looking for – but for nginx only. Do you know what I mean?

**Comment by dg9ngf** [comment]
And I guess I'm looking for some tooling or support to allow updating an application. At least on IIS I currently have the problem that publishing only works while the ASP.NET application is *not* running, i.e. the site is offline, because otherwise the .dll is locked by dotnet.exe. Taking the site offline before publishing an update doesn't sound too nice. ASP.NET 4 on IIS did that without any problem. I expect running into the same trouble now on Linux.

**Comment by moozzyk** [comment]
@dg9ngf - to address locked files on IIS AspNetCoreModule added support for app_offline file (https://github.com/aspnet/IISIntegration/issues/81). Webdeploy included in preview1 does not use it when publishing locally (only when publishing for Azure) but I opened a bug against tooling team and they are considering fixing this in the next release. If you are not using WebDeploy/VS you can just drop a non-empty (https://github.com/aspnet/IISIntegration/issues/174) app_offline.htm before copying files to stop the application and unlock files.

**Comment by davidfowl** [comment]
@dg9ngf There's no apache support in our near future but it's good feedback.

**Comment by dg9ngf** [comment]
Alright, no Apache support available.

But tell me, have I dreamt about the nginx module or does it really exist? That might possibly serve as a basis for other web servers.

app_offline.htm support is built into HPH/AspNetCoreModule, according to the referenced issues. So that would also be something I'd have to build myself.

**Comment by BrennanConroy** [comment]
Are you thinking of https://docs.asp.net/en/latest/publishing/linuxproduction.html?highlight=nginx for nginx?

**Comment by dg9ngf** [comment]
@BrennanConroy Hm, no I remember the website more like "For IIS use AspNetCoreModule, for nginx use this XY module, for Apache do it all manually." But if you guys don't know of an AspNetCoreModule equivalent for other web servers, it probably doesn't exist. I might develop my own ASP.NET Core process manager that's integrated with my managed Apache configuration.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
