### ISSUE TITLE
HttpResponseMessage gives unexpected response

### ISSUE THREAD

**Issue by ljruiten** [aspnet/Home#1507]
I am currently working with ASP.NET Core RC2 and I am running into some strange results. So I have an MVC controller with the following function:

```
public HttpResponseMessage Tunnel() {
    var message = new HttpResponseMessage(HttpStatusCode.OK);
    message.Content = new StringContent("blablabla", Encoding.UTF8);
    message.Content.Headers.ContentType = new System.Net.Http.Headers.MediaTypeHeaderValue("text/plain");
    message.Headers.CacheControl = new System.Net.Http.Headers.CacheControlHeaderValue {
        NoCache = true
    };

    return message;
}
```

If I call this with postman with an Accept header set to text plain I get this response:

```
{
  "Version": {
    "Major": 1,
    "Minor": 1,
    "Build": -1,
    "Revision": -1,
    "MajorRevision": -1,
    "MinorRevision": -1
  },
  "Content": {
    "Headers": [
      {
        "Key": "Content-Type",
        "Value": [
          "text/plain"
        ]
      }
    ]
  },
  "StatusCode": 200,
  "ReasonPhrase": "OK",
  "Headers": [
    {
      "Key": "Cache-Control",
      "Value": [
        "no-cache"
      ]
    }
  ],
  "RequestMessage": null,
  "IsSuccessStatusCode": true
}
```

I really do not understand how this is the generated reponse to the above controller. It is basically a JSON serialization of the entire message itself and does in no way contain the "blablabla" I intended to send.

The only way I have gotten the desired result is by making my controller function return string instead of HttpResponse, but that way I am unable to set headers like CacheControl

**Comment by tugberkugurlu** [comment]
Seems like you are using `HttpResponseMessage` which was part of Web API. Unless you are also using [`Microsoft.AspNetCore.Mvc.WebApiCompatShim`](https://github.com/aspnet/Mvc/tree/dev/src/Microsoft.AspNetCore.Mvc.WebApiCompatShim), it will not work as you expect it to I assume. 

I don't thing there is a direct equivalent to that in the new world but you can work with `IActionResult` and its implementations instead.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
