### ISSUE TITLE
RC2 Files Being Published to Azure Into Wrong Locations

### ISSUE THREAD

**Issue by arthurspa** [aspnet/Home#1508]
### Steps to reproduce

1.  Create an empty ASP.NET Core Web Application (.NET Core) using Visual Studio 2015
2.  Publish it to azure using Visual Studio 2015 Publish option or continuous deployment through azure portal (both can reproduce). There is no error while publishing.
3.  Access the created app online

### The issue
I get an error when try to access the website. I checked the created directory structure and it diverges from what is seen [here](https://docs.asp.net/en/1.0.0-rc2/hosting/directory-structure.html).

After deploy, my directory structure looks like [this](http://prnt.sc/b8g7ul).

You can verify that everything from my compiled project is copied into `wwwroot` folder of azure portal, including the project's `wwwroot` folder, which is not correct.

I hadn't this issue with RC1 projects.

Snippet of publish options in my `project.json`:
```
"publishOptions": {
    "include": [
      "wwwroot",
      "Views",
      "appsettings.json",
      "web.config"
    ]
  },

  "scripts": {
    "prepublish": [ "npm install", "bower install", "gulp clean" ],
    "postpublish": [ "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%" ]
  }
```

Clearly the problem is that the files are not being placed in the right location when deploying. But I'm using the default values for everything, so it should work without problem.

What commands (publish options) should I use to generate the directory structure as found in [here](https://docs.asp.net/en/1.0.0-rc2/hosting/directory-structure.html)?

### Exception
[Image](http://prnt.sc/b8gawd)
```
Exception message: Unable to locate a project.json at 'D:\home\site\wwwroot\'.
Stack trace: System.InvalidOperationException: Unable to locate a project.json at 'D:\home\site\wwwroot\'.
   at Microsoft.Extensions.Configuration.UserSecrets.PathHelper.GetSecretsPath(IFileProvider provider)
   at Microsoft.Extensions.Configuration.ConfigurationExtensions.AddUserSecrets(IConfigurationBuilder configuration)
   at ScoreTracker.Startup..ctor(IHostingEnvironment env) in D:\home\site\repository\src\ScoreTracker\Startup.cs:line 37
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Extensions.Internal.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.Internal.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Microsoft.Extensions.Internal.ActivatorUtilities.GetServiceOrCreateInstance(IServiceProvider provider, Type type)
   at Microsoft.AspNetCore.Hosting.Startup.StartupLoader.LoadMethods(Type startupType, IList`1 diagnosticMessages)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureStartup()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
```

### Further technical details

Operating system: Windows 8.1
Microsoft Visual Studio Community 2015
Version 14.0.25123.00 Update 2
Microsoft .NET Framework
Version 4.6.01055

Installed Version: Community
ASP.NET and Web Tools 2015.1   14.1.20512.0
ASP.NET Web Frameworks and Tools 2012.2   4.1.41102.0
ASP.NET Web Frameworks and Tools 2013   5.2.40314.0
Azure App Service Tools v2.8.1   14.0.11123.0
Common Azure Tools   1.7
Microsoft .NET Core Tools (Preview 1)   14.1.20512.0
Microsoft Azure Mobile Services Tools   1.4

Other details about my project setup:

**Comment by davidfowl** [comment]
Files aren't being published to the wrong locations, that documentation is out of date /cc @danroth27.

User secrets should not be used in production because the code looks like this:

```C#
if (env.IsDevelopment())
{
    // For more details on using the user secret store see http://go.microsoft.com/fwlink/?LinkID=532709
    builder.AddUserSecrets();
}
```
so my question is, did you set the the environment on your site to be development? If so this particular library will fail.

**Comment by arthurspa** [comment]
Yes, in Azure portal I set `ASPNETCORE_ENVIRONMENT` to `Development`. I need it to be `Development` for now.

Didn't know the docs were out of date. It's showing `latest` at bottom left. 

@davidfowl , could you please show me how is the correct directory structure to RC2 version and how should I configure it to work with azure? 

Thanks

**Comment by danroth27** [comment]
Doc issue is being tracked by https://github.com/aspnet/Docs/issues/1305

**Comment by TechLifeMX** [comment]
So what if i need usersecrets?

**Comment by rdefreitas** [comment]
User secrets is a feature for the local machine and not designed for
production use.

You should be using the environment variables in Azure for that.
