### ISSUE TITLE
Question: how to Additional information: No service for type 'Microsoft.Extensions.PlatformAbstractions.IApplicationEnvironment' has been registered.

### ISSUE THREAD

**Issue by Bibo1978** [aspnet/Home#1509]
I have an application that was working fine before latest visual studio 2015 ASP.Net update and now I can't debug it on visual studio
I am getting this error

> An unhandled exception of type 'System.InvalidOperationException' occurred in Microsoft.Extensions.DependencyInjection.Abstractions.dll
> 
> Additional information: No service for type 'Microsoft.Extensions.PlatformAbstractions.IApplicationEnvironment' has been registered.

debug configuration

> ```
> "web": {
>   "commandName": "web",
>   "launchBrowser": true,
>   "launchUrl": "http://localhost:5000",
>   "environmentVariables": {
>     "Hosting:Environment": "Development"
>   },
>   "sdkVersion": "dnx-clr-win-x64.1.0.0-rc1-final"
> ```

i tried different sdkVersion and none works

added and removed global.json and also didn't work

how may I fix this issue

**Comment by davidfowl** [comment]
I recommend going through the list of changes here https://github.com/aspnet/Announcements/issues?q=is%3Aopen+is%3Aissue+milestone%3A1.0.0-rc2

**Comment by Bibo1978** [comment]
I am using clr not coreclr  I can't reference Microsoft.Extensions.Options.ConfigurationExtensions

**Comment by davidfowl** [comment]
Not sure what that means.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
