### ISSUE TITLE
Any chance to still Install RC1?

### ISSUE THREAD

**Issue by mgimeno** [aspnet/Home#1511]
I'm configuring a new visual studio and need to install RC1 as our project runs that version and can't upgrade to RC2 just now. However I can't seem to find the installer anywhere.
Thank you

**Comment by obraunsys** [comment]
You can find the links to the RC1 Update 1 installers [here](https://github.com/aspnet/Home/issues/1449#issuecomment-219578445)

**Comment by mgimeno** [comment]
@davidfowl , @obraunsys thank you! That worked!
