### ISSUE TITLE
RC1 --> RC2: Severe migrations issues

### ISSUE THREAD

**Issue by jkpindahbc** [aspnet/Home#1514]
Nuget Package Manager is now broken with upgrade to RC2.

![image](https://cloud.githubusercontent.com/assets/399519/15615431/27252c38-23f3-11e6-9602-5b0febc2c52a.png)

**Comment by muratg** [comment]
cc @rrelyea

**Comment by davidfowl** [comment]
@jkpindahbc can you move this to https://github.com/nuget/home

**Comment by jkpindahbc** [comment]
Will move to https://github.com/nuget/home
