### ISSUE TITLE
NuGet package for ASP.NET Core & ASP.NET 4.5

### ISSUE THREAD

**Issue by 304NotModified** [aspnet/Home#1515]
Is it possible to create 1 nuget package which supports ASP.NET Core & ASP.NET 4.5?

If users uses NETSTANDARD, we know it's .NET Core and with NET40 we know it's ASP.NET 4.5

But how about NET451? It could be Core or non-Core.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
