### ISSUE TITLE
statically access the IHostingEnvironment implementation

### ISSUE THREAD

**Issue by tugberkugurlu** [aspnet/Home#1516]
How can I statically access the `IHostingEnvironment` implementation? Based on [this](https://docs.asp.net/en/latest/migration/rc1-to-rc2.html#runtime-services-changes), `applicationEnvironment.ApplicationBasePath` doesn't map to root of the project dir anymore but I need to set this to pick up the hosting.json file on the static `Main` method.

I am currently doing this which is probably wrong:

````csharp
            var hostingConfig = new ConfigurationBuilder()
                .SetBasePath(Directory.GetCurrentDirectory())
                .AddJsonFile("hosting.json")
                .Build();
            
            var host = new WebHostBuilder()
                .UseKestrel()
                .UseConfiguration(hostingConfig)
                .UseContentRoot(Directory.GetCurrentDirectory())
                .UseStartup<Startup>()
                .Build();

            host.Run();
```

**Comment by davidfowl** [comment]
You can't statically access it. That code looks fine to me

**Comment by tugberkugurlu** [comment]
@davidfowl ah OK, so `Directory.GetCurrentDirectory()` will get me the correct place?

**Comment by brockallen** [comment]
We use PlatformServices.Default.Application.ApplicationBasePath in our tests to bootstrap stuff.

**Comment by davidfowl** [comment]
You're basically telling ASP.NET where to look for stuff, if you don't tell it anything it'll look at the application base path, if you do tell it where to look for stuff (as you are in the above code snippet), then you need to store that information.
