### ISSUE TITLE
How to reference netframework35 library from net451 project?

### ISSUE THREAD

**Issue by Daniel15** [aspnet/Home#1517]
Im trying to upgrade my site from ASP.NET 5 RC 1 to ASP.NET Core RC2. I'm encountering this error on one of the assemblies:

```
error: Package MarkdownDeep.NET 1.5.0 is not compatible with net451 (.NETFramework,Version=v4.5.1). Package MarkdownDeep.NET 1.5.0 supports: netframework35 (.NetFramework 3.5,Version=v0.0)
```

The `MarkdownDeep.NET` package only contains an assembly for `netframework35`. I tried adding `netframework35` to the `imports` section but that doesn't seem to have worked.

`project.json` file:
```
{
    "version": "1.0.0-*",
    "description": "Daniel15.BusinessLayer Class Library",

  "dependencies": {
    "Daniel15.Data": {
      "target": "project"
    },
    "MarkdownDeep.NET": "1.5.0",
    "Microsoft.AspNetCore.Http.Extensions": "1.0.0-rc2-final",
  },

    "frameworks": {
        "net451": {
          "frameworkAssemblies": {
            "System.Net": "4.0.0.0"
          },
          "imports": [
            "netframework35"
          ]
        }
    }
}
```

**Comment by davidfowl** [comment]
You don't need the imports, that should work without any issues.

/cc @emgarten @yishaigalatzer

**Comment by davidfowl** [comment]
I just noticed something bizzare in the error message:

```
supports: netframework35 (.NetFramework 3.5,Version=v0.0)
```
The package is busted. It's saying the framework name is .NETFramework 3.5 and the version is 0.0.

**Comment by davidfowl** [comment]
You can actually work around this by making this the import:

```JSON
"imports": [
        ".NetFramework 3.5,Version=v0.0"
      ]
```

You should notify the package author that the package is busted.

**Comment by davidfowl** [comment]
@emgarten Looks like a nuget bug where it can't parse the framework name. It works fine in `packages.config` based projects.

**Comment by Daniel15** [comment]
@davidfowl  - The package is basically abandoned (last updated 2012). I might fork it for my own uses.

However, I don't think the package itself is busted. This exact same package works fine in an ASP.NET 5 RC1 website, it only breaks once I switch to RC2.

**Comment by davidfowl** [comment]
Yea, it looks like a nuget bug to do with parsing the target framework.

**Comment by yishaigalatzer** [comment]
Please move the issue to the nuget repo.

**Comment by Daniel15** [comment]
This issue was moved to NuGet/Home#2859
