### ISSUE TITLE
How to publish "content" files from class library project with rc2 stack ?

### ISSUE THREAD

**Issue by IsaacSee** [aspnet/Home#1519]
Hello, 

Given a solution with the following projects : 
- Web.Public (website)
- Web.Admin (website)
- Web.Shared (class library)

Both Public and Admin websites references the Shared project.
The shared project contains common logic and static files (ie. configurations & client site assets).

**How can we publish theses static files contained in the Web.Shared project to be use on runtime by Public or Admin website ?**

With RC1 we were able to publish sources (including projects assets) to be accessible on runtime.

**Comment by joeaudette** [comment]
pretty much the same issue as this one: https://github.com/aspnet/Home/issues/1490

**Comment by IsaacSee** [comment]
Thanks for the cross-link. The solution is smart but we'd like to keep these file human readable/editable after the publication.

**Comment by IsaacSee** [comment]
For now (waiting for a better - more integrated - solution) we use Web.Public/Web.Admin project.json _postpublish_ hooks to manualy copy files we want to bundle on publish.

``` 
"scripts": {
      "postpublish": [
        "robocopy .\\..\\Web.Shared %publish:OutputPath%\\Web.Shared\\ /MIR",
        "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%"
      ]
    }
```

It works well but it creates annoyings path diffs between a **dev run** (IISExpress or `dotnet run` in project folder) and a **published run** (dotnet run from a published folder).

**Comment by moozzyk** [comment]
@IsaacSee - have you tried including the path to the files that you want to publish in publishOptions/include ?

**Comment by IsaacSee** [comment]
@moozzyk - yes i tried various publishOptions for website and class library projects, unsuccessfully. 

But I just discovered the `--native-subdirectories` of the `dotnet publish` command witch seems to temporary address this feature while nuget's contentFiles are getting ready.
See: https://github.com/dotnet/cli/issues/721

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
