### ISSUE TITLE
overthink removing db first

### ISSUE THREAD

**Issue by mbeckenbach** [aspnet/Home#152]
Just watched the latest comunity hangout. You said, db first will ne removed. I understand why, but:
In a real World scenario there are lots of applications that have to share one database. Sometimes this has historical reasons, sometimes its a limitation by your web hoster. I know, this is not as it should be. But often it is. 

With the old Code first migrations you ran into the Problem of having a model thats not in snych when you used reverse engineering and did not import all tables. 
Db first does not have these problems. 

Sure one could use ef6. But having db first and the benefits of ef7 would be the cooler thing as I think there might be some scenarios, where a part of my data comes from a SQL db first source shared by other apps. Another part comes from azure table and i want to use ef7. 

Maybe db first could be an optional nuget package, so you do not have to ship the whole big thing always? This would devs give the choice. 

An alternate way I'd say that would work for most devs would be to allow the side by side use of ef6 and ef7 in an application. Don't know if that would be possible.

**Comment by rowanmiller** [comment]
Closing as there hasn't been any recent discussion, feel free to re-open if you have further questions
