### ISSUE TITLE
ASP.NET Core Web API: Server fails to start due to invalid app.config file

### ISSUE THREAD

**Issue by pfedotovsky** [aspnet/Home#1520]
I want to consume WCF service within my ASP.NET Core Web API application. I've added needed endpoints and another configuration into the _app.config_ file, but when I run "_dotnet publish_" produced _<ServiceName>.exe.config_ file is incorrect, see below. So I can't run project until I fix the file manually and I can't run project inside Visual Studio due to this bug.

```
  </system.serviceModel>
</configuration>m.serviceModel>  

</configuration>
```

The last N symbols is duplicated for some reason - seems to be a bug in the **dotnet** command-line utility. 

I've created sample project to reproduce the problem: http://github.com/pfedotovsky/aspnet-tests
Just run **dotnet publish** and open _AppConfigIssue.exe.config_ in the output directory.

**Comment by davidfowl** [comment]
@pfedotovsky Can you move this to https://github.com/dotnet/cli

/cc @pakrym

**Comment by pfedotovsky** [comment]
@davidfowl Sure, https://github.com/dotnet/cli/issues/3292
