### ISSUE TITLE
ASPNET_ENV is obsolete, but...

### ISSUE THREAD

**Issue by rhires** [aspnet/Home#1521]
Running RC2, Yosemite, VSCode 1.1.1-insiders, used Yeoman for scaffolding. From the command line, `dotnet run` gives me the following message: 
`The environment variable 'ASPNET_ENV' is obsolete and has been replaced with 'ASPNETCORE_ENVIRONMENT'`
But as far as I can tell, I don't have `ASPNET_ENV` anywhere in my project. I looked in the various .json files, and did a search using my search tools, and it's just not there. So why would I get this message? And how do I make it go away?

**Comment by rhires** [comment]
Doing a bit more poking around, I look in my `.bash_profile`, where I keep my environment variable, and it says `ASPNET_ENV`. So that's the issue. Changing it to `ASPNETCORE_ENVIRONMENT` makes the message go away, and I'm good. Perhaps the error message could include, "update your bash environment variable"?

**Comment by MaximRouiller** [comment]
@rhires There's sadly no way to know where it was defined. So the message would need to be generic at best since bash is Linux and Command Prompt/Powershell is Windows.

Also, it does assume that developers knows how to set environment variables. :smiley:

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
