### ISSUE TITLE
Seperate ASP.NET Core from .Net Core

### ISSUE THREAD

**Issue by reader-man** [aspnet/Home#1522]
One of the very good ideas of .Net core, was separation of concerns at the very low level of the framework to be a modular/component framework.

but making ASP.NET Core integrated into .Net Core, did not adhere to the idea, and will make ASP.Net growth dependent on the .Net core growth, so there will not be a new version/fix for ASP.Net unless there is a new version of .Net Core, which will slow both.

And I did not see the EF 7 relation with .Net core, because if its the same as with ASP.Net core, then another non modular component is integrated into .Net core, and same issues apply.

**Comment by davidfowl** [comment]
It's already separate and modular. Can you be more specific?

**Comment by smbecker** [comment]
I'm guessing the OP is referring to the release train. Yes all of the components are modular but with how things are today, fixes in one won't be seen until the whole release train is done. The only alternative is to get on nightly builds.

**Comment by reader-man** [comment]
@smbecker, Thanks.


@davidfowl, Yes, I meant the release cycle.
As we understood that .Net Core is modular from the start, as if its Java 9, but years before it :).

So i thought that ASP.Net Core, and EF Core, will be separate nuget packages, that have different installation/releases than each other, so .Net Core is the main Package, and we can add to it EF or ASP.Net, or any new package like "XAML i hope very soon :)", but that doesn't look like that.

So when we install .Net core, we will have with it EF+ASP.NET weather we want or don't.

Which for me at least is not important, but the most important is the separation of the release, it would be very bad to couple their release too tight, that we can't see the new features of one of them, till all of them are ready to a new big release, and that was one of the very bad things of the behemoth .Net framework 1,2,3,4,.., and this is starting to have some of its bad properties.

I think that the release should be separated as you have almost done in Windows Server nano and the windows kernel.

**Comment by davidfowl** [comment]
> So i thought that ASP.Net Core, and EF Core, will be separate nuget packages, that have different installation/releases than each other, so .Net Core is the main Package, and we can add to it EF or ASP.Net, or any new package like "XAML i hope very soon :)", but that doesn't look like that.

That's how it works now. ASP.NET and EF are separate nuget packages. What exactly are you talking about?

> So when we install .Net core, we will have with it EF+ASP.NET weather we want or don't.

Are you talking about the project templates? The VS installer? Something else?

> Which for me at least is not important, but the most important is the separation of the release, it would be very bad to couple their release too tight, that we can't see the new features of one of them, till all of them are ready to a new big release, and that was one of the very bad things of the behemoth .Net framework 1,2,3,4,.., and this is starting to have some of its bad properties.

Once we ship 1.0 I'm sure we'll move to a more independent release schedule.

**Comment by reader-man** [comment]
@davidfowl, thanks for the clarification, then i misunderstood them.
