### ISSUE TITLE
dotnet publish contents

### ISSUE THREAD

**Issue by ShadowDancer** [aspnet/Home#1524]
After running dotnet publish I have soup of dlls, config files, chtmls, views and so on.

In rc1 we had approot and wwwroot directories. In my opinion it was step forward. Are there plans for changing publish output? For instance moving all *.dll, *.exe and so on to bin folder?

**Comment by davidfowl** [comment]
Nope

**Comment by ShadowDancer** [comment]
Is it good idea then to skip dotnet publish and implement my own way of publishing?
I have separate repositories for application (dll), and for content (views, scripts etc). Publish just mix everything toghter and doesn't really help (in my case).
