### ISSUE TITLE
Migrating from RC1 Packages to Correct RC2 packages (and related NuGet feed)

### ISSUE THREAD

**Issue by dazinator** [aspnet/Home#1525]
I'm writing an upgrade tool for upgrading RC1 projects to RC2, and part of that is dealing with upgrading nuget packages to RC2 versions. 

I am quite confused as to the migration path for the various Microsoft NuGet packages. I have read the various bloggs and github issues relating to upgrading but none seem to capture a comprehensive list of RC1 microsoft packages, and the what the upgrade process should be to go to RC2 (i.e the new RC2 package name and version, or whether the package can now be dropped).

1. Is there a place (perhaps on the documentation site) where this comprehensive NuGet package migration guide could be created / maintained? 

2. Which NuGet feed can we find stable RC2 packages on? NuGet.org? aspnetrelease? both? Does this differ per package / team ? 

[Shawns blog](https://wildermuth.com/2016/05/17/Converting-an-ASP-NET-Core-RC1-Project-to-RC2) has helped, but it's not comprehensive, and even mentions packages that don't exist like `Microsoft.AspNetCore.Server.IIS`.

**Comment by moozzyk** [comment]
Since RC2 has already shipped NuGet is the place to get RC2 packages. Some packages were renamed post RC1 - this includes the package that enables running your application with IIS. Here is the announcement of this breaking change https://github.com/aspnet/Announcements/issues/164

**Comment by dazinator** [comment]
> Some packages were renamed post RC1 - this includes the package that enables running your application with IIS

Yeah this is the thing. "Some packages were renamed" doesn't cut it - i'm after a comprehensive list of the packages that were renamed. Its not as simple as changing all "Microsoft.AspNet.*" packages to "Microsoft.AspNetCore." for example, because that rule doesn't apply to some packages like ` `Microsoft.AspNet.WebApi.Client`. There are also other non ASPNET related packages like EF, and various tooling packages that have changed names. Trying to pull this information from disparate sources like blog posts is a nightmare, I feel like there should be a central consolidated list somewhere.

**Comment by moozzyk** [comment]
I would recommend watching the https://github.com/aspnet/Announcements/ repo where we announce breaking changes. The initial round of renames for RC2 (which contains EF packages) was announced here: https://github.com/aspnet/Announcements/issues/144. There were a few more renames after that - e.g. [renaming tool packages](https://github.com/aspnet/Announcements/issues/172). I don't think we have a single list of RC1->RC2 package renames - sorry. I think, however, that after you change Microsoft.AspNet.* to Microsoft.AspNetCore.* and EntityFramework.* to Microsoft.EntityFrameworkCore.* you will end up having only a handful of packages that need more work. Btw. in the Announcement repo you can filter by milestone which makes it easier to see breaking changes for a specific release - e.g. here is the list for breaking changes between RC1 and RC2: https://github.com/aspnet/Announcements/milestones/1.0.0-rc2

**Comment by dazinator** [comment]
@moozzyk  thanks. The breaking changes list does help. I really do think this information needs consolidating to be more helpful for developers trying to migrate to RC2. This [asp.net docs section](https://docs.asp.net/en/latest/migration/rc1-to-rc2.html#namespace-and-package-id-changes) looks like the relevant place to do that I guess.

One question, I couldn't see any breaking change mentioning the `Microsoft.VisualStudio.Web.BrowserLink.Loader` but after reading https://github.com/aspnet/Home/issues/1381 I am left to believe that this package has been discontinued and should be removed? Any clarification around that would be much appreciated..

**Comment by moozzyk** [comment]
I can see the rc2 version of the BrowserLink package on NuGet - https://www.nuget.org/packages/Microsoft.VisualStudio.Web.BrowserLink.Loader/14.0.0-rc2-final

**Comment by dazinator** [comment]
@moozzyk - ok that's what I thought too, so it's odd that #1381 mentions dropping that package when migrating! Also I noticed that this package doesn't stick with the convention of all the other RC2 packages i.e it's not "1.0.0-rc2-final" it's version 14. I am sure there is a reason for that, but again, its just confusing coming across all these edge cases. I am sure everyone attempting to upgrade to RC2 at present will be experiencing the same frustrations unfortunately.
