### ISSUE TITLE
Whats the story with Microsoft.AspNet.IISPlatformHandler, RC1 --> RC2

### ISSUE THREAD

**Issue by dazinator** [aspnet/Home#1526]
We use VS2015 and are currently using the `Preview1` tooling (latest release).

I am upgrading our solution from RC1 to RC2, and I am wondering what the correct migration strategy is for the `Microsoft.AspNet.IISPlatformHandler` nuget package.

It looks like there is an RC2 version here:
http://myget.org/feed/aspnetcirelease/package/nuget/Microsoft.AspNetCore.IISPlatformHandler 

but I have also read the advice that this has changed to `Microsoft.AspNetCore.Server.IISIntegration` for RC2. 

Just wanted to confirm which one to use, and also wanted to be aware of any limitations that there might be in VS2015 (tooling preview 1) after upgrading from RC1 using the old package..

**Comment by MaximRouiller** [comment]
https://github.com/aspnet/announcements/issues?q=is%3Aissue+is%3Aopen+IISPlatformHandler+milestone%3A1.0.0-rc2

More specifically, 

https://github.com/aspnet/Announcements/issues/164
https://github.com/aspnet/Announcements/issues/139

**Comment by dazinator** [comment]
Thanks. In terms of migrating to `Microsoft.AspNetCore.Server.IISIntegration` - the [announcement](https://github.com/aspnet/Announcements/issues/164) states:

> There is no tooling support in Visual Studio yet (as of 3/25). In the meantime you'll need to use dotnet publish from the command line and run the application with full IIS. dotnet-publish-iis is also in the process of being updated so some manual web.config manipulation may be necessary.

Is this something that has now been addressed with the Preview1 tooling released for VS2015? I am hesitant to migrate if their are still issues in this area with VS2015.

**Comment by moozzyk** [comment]
When you install preview1 it will install AspNetCoreModule. The default web.config created by VS when you have preview1 tooling make IIS/IISExpress run your app with AspNetCoreModule. When you create a new project your project.json will have publish-iis tool wired as a postpublish script so that the application works after publishing.

**Comment by dazinator** [comment]
@moozzyk - ok so I think what we are saying is that this all should work fine in VS2015 preview 1. I'll close for now on that assumption.
