### ISSUE TITLE
DbGeography type support

### ISSUE THREAD

**Issue by takazm** [aspnet/Home#1527]
I am working on a project which requires saving GPS coordinates into my database. I ran the dotnet-ef.. command to scaffold my tables into c# entities and I got this message : `Could not find type mapping for column 'table1.GPSCoords' with data type 'geography'. Skipping column. `

Does this mean there is no support of the type yet  and if so when will it be supported?

**Comment by muratg** [comment]
cc @divega

**Comment by laskoviymishka** [comment]
@takazm you better addres this issue to entity framework team.
This stuff curently in backlog _https://github.com/aspnet/EntityFramework/issues/1100_ 
It not marked as `up for grabs` and not as RTM, so most probably it not appear in nearest time

**Comment by divega** [comment]
Closing so that we can follow up on the EF issue. It would be interesting to hear what type you are using to represent spatial values on the .NET side and why you choose it.
