### ISSUE TITLE
[Question] - project.json RC2 - tools and dependencies section

### ISSUE THREAD

**Issue by dazinator** [aspnet/Home#1529]
I have noticed that some tools are listed just in the tools section, and others are listed in the tools section and the dependencies section of the project.json file.

e.g - this is just in the tools section

```
"Microsoft.AspNetCore.Server.IISIntegration.Tools": {
      "version": "1.0.0-preview1-final",
      "imports": "portable-net45+win8+dnxcore50"
    },

```

Where as razor tools is in the tools and the dependencies section:

```
 "Microsoft.AspNetCore.Razor.Tools": {
      "version": "1.0.0-preview1-final",
      "imports": "portable-net45+win8+dnxcore50"
    },

```

and

```
 "Microsoft.AspNetCore.Razor.Tools": {
      "version": "1.0.0-preview1-final",
      "type": "build"
    },
```

I thought perhaps this was basically the difference between tooling that is used purely at development time (i.e just in the tools section), and tooling which is also distributed as a runtime dependency with your application (i.e in the dependencies section)?

However - I noticed the packages in the dependency section have a "type" set to "build" - which I am guessing is the indicator that it shouldn't be treated as a runtime dependency?

so - why are some tools packages present in both sections and others only in one?

**Comment by dougbu** [comment]
@dazinator it's more about whether a tool needs "special" handling during restore. If for example its dependencies aren't all aware of `netstandard1.x` TFMs, the tool must also be described in the `dependencies` section. A lot of this boilerplate will be removed as we move to the new `netstandard1.0` Json.NET version (`9.0.1-beta1`). But the capability of overriding a tool's dependencies will remain.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
