### ISSUE TITLE
Should I upgrade to RC2 from RC1 or just wait for RTM ?

### ISSUE THREAD

**Issue by Michal7** [aspnet/Home#1530]
Hi All,

Should I upgrade to RC2 now or is better to wait for RTM releate (Tools Preview 2) ?
I make assumption that RTM(Tools Preview 2) will be easy(less bugs) to use then Tool Preview 1.

**Comment by davidfowl** [comment]
That's really up to you to make that decision. If you want for Preview 3 there'll be less bugs than in preview 2 etc. 

We can only give you data to aid that decision making but it's ultimately up to you.

**Comment by MaximRouiller** [comment]
Do it when you have the time. No need to rush. You are supported after all. 

However, it's important to keep up to date to avoid having to do a massive upgrade all at once.

Like @davidfowl said, it's up to you but at some point, you'll need to update and the amount of work that will need to be done is what is going to be different.

**Comment by Michal7** [comment]
Thx all.
The app is still pretty simple, hope it switch to RTM before get really complex.
I will wait for RTM, only missing EF7 RC2. 

@davidfowl when we can expect another community stand up ?

**Comment by MaximRouiller** [comment]
@Michal7 There was one today.

**Comment by Michal7** [comment]
@MaximRouiller  Thx
Just watched one : https://www.youtube.com/watch?v=qvG5oaS3pSQ
:)
