### ISSUE TITLE
[Request(?)] RC2 for Windows IoT

### ISSUE THREAD

**Issue by glararan** [aspnet/Home#1531]
Hello,

RC2 switch from DNX to dotnet CLI. DNX was great for running ASP RC1 on Windows IoT. There was .exe file coming with "dnx publish" but with "dotnet publish" there only comes dlls.

Is ASP.NET core supposed to support Windows IoT platform anymore?
Any plans to future? I would like to stay on Windows IoT and not to switch back to Linux because I am not able to run ASP.NET on Raspberry Pi with Windows IoT.

Thanks

**Comment by davidfowl** [comment]
This isn't on the roadmap for 1.0 as for future plans I can't say for sure.

/cc @DamianEdwards @richlander

**Comment by fabiocbr75** [comment]
I don't understand. 
.Net core and asp.net core works on linux, docker, mac.... but not on windows iot ???
Ok to be open to other platform but windows should be the first platform.
If I understand correctly, for my project (based on raspberry pi3) is better to switch to linux if I want to use asp.net core but if i switch to linux the easy way to develop on raspberry is python.
I hope that windows iot platform will be supported by asp.net core.

Thanks

/cc @DamianEdwards @richlander

**Comment by LukaszDev** [comment]
>I hope that windows iot platform will be supported by asp.net core.

I hope too ;)

**Comment by davidfowl** [comment]
@fabiocbr75 What don't you understand? It's not supported right now but will be supported in the future.

**Comment by fabiocbr75** [comment]
I don't understand why for all windows platform are not ready a clear roadmap. 
future is very large amount of time for me to schedule activities with correct time to market.
I'm very happy of .net core and asp.net core and cross platform .net but i was hoping that the schedule was valid for all windows platform and after first RC1 the Windows iot was became less priority.
When the roadmap will be ready with support of windows iot?

Thanks.

**Comment by WURMiL** [comment]
RC1 was able to run on Windows 10 IoT, but RC2 not? So there is currently no way to execute RC2 code on Windows 10 IoT?

**Comment by DamianEdwards** [comment]
Yes, for now we don't have .NET Core builds for Windows 10 IoT Core (ARM) available. We had it in RC1 when we still based on DNX. We hope to get ARM builds produced again in the near future.

**Comment by WURMiL** [comment]
Thanks for the answer Damian. are you able to estimate the "near future"? It is in the scope of couple of weeks or rather couple of months? :)

**Comment by fabiocbr75** [comment]
@DamianEdwards  Any news about the roadmap for the asp.net core on windows iot?
Thanks

**Comment by LukaszDev** [comment]
Win10 IoT is mentioned in #1685  (1.1.0 Planning):

> WebListener server (for Service Fabric & public-facing ready self-host without reverse proxy and Windows 10 IoT/UWP support)

However I'm not sure what this mean ?

**Comment by EdiWang** [comment]
With .NET Core 1.0 RTM, it seems not installing on Raspbian Linux either. They only support x86, x64 based Linux systems. But back in the days when ASP.NET Core was ASP.NET 5, it can run on Raspbian. I wonder when will ASP.NET Core be supported on ARM based Linux systems such as Raspbian?

**Comment by tomkuijsten** [comment]
@DamianEdwards Any news about the roadmap for the asp.net core on windows iot? And if not, should I watch this issue to get notified when there is any news or another issue/blog?

**Comment by iissmart** [comment]
@tomkuijsten If it helps, ARM 32/64 is mentioned on the roadmap for Q4 2016 / Q1 2017 as seen here:

https://blogs.msdn.microsoft.com/dotnet/2016/07/15/net-core-roadmap/

But that was posted back in July; I can't find a more recent update.

**Comment by bigdnf** [comment]
I'm also interested in running ASP.NET Core on my raspberry Pi, especially for web API purpose. Please give some info when it will be available

**Comment by mne1991** [comment]
The same here +1 for implementing Asp.Net core for ARM, I could successfully start .Net core app, but not asp.net core app (if they really were different). I am interested in that for Web API purpose on my RPi3 too. Waiting for any news!

**Comment by DamianEdwards** [comment]
See https://stevedesmond.ca/blog/net-core-on-arm

**Comment by mne1991** [comment]
@DamianEdwards that doesn't include ASP.Net Core or? because I tried with a very simple web app with no success, here is the question:
http://stackoverflow.com/questions/42054399/error-in-running-asp-net-web-app-on-arm-processor-raspberry-pi-3-b-ubuntu-n

**Comment by moozzyk** [comment]
https://github.com/dotnet/coreclr/issues/9168

**Comment by ummarbhutta** [comment]
Any update about ASP.Net Core support on windows IoT? Why Windows IoT is not getting it? I don't understand purpose of ASP.Net Core if **Windows family** is not supporting it fully!

**Comment by tomkuijsten** [comment]
Take a look at [this conversation](https://github.com/dotnet/coreclr/issues/9168#issuecomment-278456641) about running .net core on Win10IoT.

**Comment by ummarbhutta** [comment]
Thanks @tomkuijsten It worked for very basic MVC application. But having said this, I am trying to find an answer that Is ASP.NET Core is production ready for Windows 10 IoT? My concerns are Specifically there is no Official release of .NET Core for ARM, and Generally there seems to be some API(s) which are not supported on ASP.NET Core, the one I found is SignalR, because I need it for my project (there must be others I doubt). If we can't rely on ASP.NET Core we are left with options like [RestUP](https://github.com/tomkuijsten/restup) and [IotWeb](https://github.com/ummarbhutta/iotweb/) if we are developing a web based solution on windows 10 IoT?

**Comment by davidfowl** [comment]
> Thanks @tomkuijsten It worked for very basic MVC application. But having said this, I am trying to find an answer that Is ASP.NET Core is production ready for Windows 10 IoT

Nope. For all the reasons you mention. We don't test on windows 10 IoT, at best it's a neat experiment right now. There are no serious efforts to have a production ready ASP.NET Core stack on Windows 10 IoT.

**Comment by tomkuijsten** [comment]
@davidfowl thanks for an official comment!

Is there no plan to support ASP.NET Core on Windows IoT?

@ummarbhutta you are correct that restup and IoTWeb are one of the few alternatives. As for restup (I'm the author), it's working pretty stable and issues are down to a few. We are using it in production (on a protected intranet environment), but it's on your own risk and I would not recommend it in any way to use it on the public web.

**Comment by davidfowl** [comment]
> Is there no plan to support ASP.NET Core on Windows IoT?

There is nothing on the roadmap.

/cc @DamianEdwards

**Comment by ummarbhutta** [comment]
@tomkuijsten Thanks for your comment, I have already used both Restup and IoTWeb, Just wondering if I can use a powerful framework on Windows IoT. But as per @davidfowl 

> There is nothing on the roadmap.

Looks like there is no hope in near future.

**Comment by mne91** [comment]
Apparently, most of users are interested in running .net core on Linux, not a lite version of windows (including me and everyone else I know), maybe therefore they are simply ignoring it.

**Comment by fabiocbr75** [comment]
@mne1991 "Apparently, most of users are interested in running .net core on Linux, not a lite version of windows"

I hope the future of WinIot will be different from that of windows phone but if the most relevant feature are avaiable before on linux that on winiot there is a problem.

**Comment by tomkuijsten** [comment]
I don't really understand the goal of Windows IoT and it's promotion to "the makers" community when there is no plan for a basic webserver. I find it hard to believe that ASP core will not make it to Win10IoT as .NET core is already being build for [Win10 ARM](https://github.com/dotnet/core-setup#daily-builds)

On the other hand, I'm not at all an expert on Microsoft's vision of the Win10IoT future and it's use. Maybe we're all thinking the wrong way on this topic.

@davidfowl could you elaborate on Microsoft's vision of Win10IoT, specific in regard to a webserver? To make it more challenging, a vision where Azure is not an option :)

**Comment by olivierHen** [comment]
Hi folks, 
it's been a while since this thread has been stopped ... 

But do you know if I can deploy an Asp.net core 2 app on my Rpi3 with Win10IoT now ? 

Or maybe this is planned on the roadmap ?

I would love to use my Rpi as a little web server ... 

Thank you !

**Comment by tomkuijsten** [comment]
@olivierHen yes you can, check out my blogpost [Running ASP.NET (https) on a Windows 10 IoT device](http://www.devvy.nl/?p=193)

**Comment by ummarbhutta** [comment]
What about official release of .NET core for ARM? (Windows IoT), is it available now or still we have to use some nightly build?

**Comment by gpeipman** [comment]
Hi!
Is there any way to host ASP.NET Core under under Windows 10 IoT Core background task? I got ASP.NET Core 2 application run independently on Windows 10 IoT Core (http://gunnarpeipman.com/2017/12/aspnet-core-windows-iot/) but I can't find out how to make it work in background task.

**Comment by JeffMarqMetrix** [comment]
Vote for it...
[https://aspnet.uservoice.com/forums/41199-general-asp-net/suggestions/32626766-support-for-asp-net-core-running-on-uwp-as-windows](https://aspnet.uservoice.com/forums/41199-general-asp-net/suggestions/32626766-support-for-asp-net-core-running-on-uwp-as-windows)

**Comment by gpeipman** [comment]
Those who want to build nice web UI-s for services running on Windows 10 IoT Core can start with this solution until things get better: [gpeipman/Windows10IoTWebControl](https://github.com/gpeipman/Windows10IoTWebControl)

**Comment by Eilon** [comment]
@DamianEdwards , can you provide any info on plans for IoT support?

**Comment by Eilon** [comment]
Also cc'ing @glennc in case you have any info/thoughts on this.

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
