### ISSUE TITLE
Routing Constraints under areas

### ISSUE THREAD

**Issue by Christos2015** [aspnet/Home#1532]
I've being working with ASP.NET Core and trying to figure out the new routing concepts and I came across scenarios where the conventional "constraints:" on action methods when areas are used, do not seem to work. 
Is this a known bug?

Thanks and I hope I did not violate and issue submission protocols :)

**Comment by Christos2015** [comment]
Sorry I should have mentioned the version:

 "Microsoft.NETCore.App": { "version": "1.0.0-rc2-3002702",     "type": "platform" }

**Comment by rynowak** [comment]
Please give us an example (with code) of what you're trying to do, and explain what you think is wrong in more detail. Thanks!

**Comment by Christos2015** [comment]
OK here it goes: I created a minimized version of what I am doing ....

A. I created **three** controllers. Two of them under **areas**. One area called _products_ and another called _Services_. 
- see attached image of "SolutionExplorer.png" file.
![solutionexplorer](https://cloud.githubusercontent.com/assets/16291651/15800098/638e3fac-2a79-11e6-84fb-2fcefbe5b70c.PNG)

B. In the **startup.cs** file I created **three** routes one for each controller. 
In the _Products_ route, I added a constraint in the template, on the _action_ segment. 
_"action:regex(List)._
- see the attached file with the Controller classes and Startup.cs source code "
[Controllers and Startup Source.txt](https://github.com/aspnet/Home/files/298865/Controllers.and.Startup.Source.txt)

C. The above constrained should have prevented matching a route to "Products/Home/**Index**", but as you can see in the third file below (the output of the browser), the URL was successfully routed.
![browseroutput](https://cloud.githubusercontent.com/assets/16291651/15800117/fe49f9fa-2a79-11e6-9106-738ffbbee8c7.png)

I hope this helps! If you need anything else please let me know.
 I would appreciate your feedback if any

**Comment by Christos2015** [comment]
My bad!! The extra controller was short circuiting the issue.... sorry!
