### ISSUE TITLE
[Question] - Microsoft.VisualStudio.Web.CodeGeneration.Tools

### ISSUE THREAD

**Issue by dazinator** [aspnet/Home#1533]
I am writing a tool to upgrade RC1 projects to RC2. 

I am trying to determine when it is appropriate for the new `Microsoft.VisualStudio.Web.CodeGeneration.Tools` tool to be added to the tools section of an RC2 project.json file. Is it for example only if the project is an MVC project?

It would be helpful if someone could clarify what this package actually does and when it is necessary!

Cheers

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
