### ISSUE TITLE
Service Locator Pattern / Dependency Injection

### ISSUE THREAD

**Issue by SimonOrdo** [aspnet/Home#1535]
I understand that DI is the way to go for most things, but I'm wondering if it's still possible to use the service locator (anti) pattern to resolve services?

How, for instance, would I resolve a DB context from an ad-hoc class without passing a reference from a DI enabled caller?

**Comment by gulbanana** [comment]
statics

**Comment by laskoviymishka** [comment]
You could initialize your service locator antipattern inside your `Startup` code
Here is simple sample
```

    public static class DoNotUseThisPattern
    {
        private static IServiceProvider _provider;

        public static void Init(IServiceProvider provider)
        {
            _provider = provider;
        }
        public static T Resolve<T>() => (T)_provider.GetService(typeof(T));
    }

    public class Startup
    {
        public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
        {
            using (var serviceScope = app.ApplicationServices.GetRequiredService<IServiceScopeFactory>().CreateScope())
            {
                DoNotUseThisPattern.Init(serviceScope.ServiceProvider);
            }
        }
    }
```

**Comment by Daniel15** [comment]
> How, for instance, would I resolve a DB context from an ad-hoc class without passing a reference from a DI enabled caller?

How are you instantiating the ad-hoc class? In an ideal case, everything uses constructor injection and thus the ad-hoc class would just take the DB context in its constructor.

**Comment by SimonOrdo** [comment]
Hmm.. how would do constructor injection on a class that's not a controller
or view?

**Comment by laskoviymishka** [comment]
How do you call such class? Provide code sample please.

**Comment by SimonOrdo** [comment]
```
class MyPoco
{
       public void PerformDBOperation()
       {
            // Some DBContext code
       }
}
```
Would be instantiated with

`var test = new MyPoco();`

**Comment by davidfowl** [comment]
If nobody is constructing your object then you have to use the service locator pattern. Ideally, you would have a single (or as little as possible) composite root (the root object where composition occurs).

```C#
public class MyCompositeRoot
{
   public MyCompositeRoot(IFoo foo, IService1 s1) { ... }
}
```

```C#
var root=serviceProvider.GetService<MyCompositeRoot>();
```

**Comment by laskoviymishka** [comment]
@SimonOrdo the question is: 
how you would instantiane this `MyPoco` and when.
If you will have it in some `Aspnet` context (tag helper, controller, view, component anything that instantianted by `Mvc` itself) then you be able to use proper way of DI.
If no, and you still builded web site, then probably something goes wrong with your code itself. 
But, for example, there is still couple legit sample of where you could have some troubles of contructor injection. Let me define an example.
Let's imagine you have some scheduled worker, which you run just in paralel thread of main `aspnet` app. So your main change a little bit:
```
static void Main(args)
{
    // web host build here
    var jobRunner = new JobRunner();
    jobRunner.Run();
}
```

Inside of job runner you want to setup a collection of job interfaces
```
private IList<IJob> _jobs = new List<IJob> { new Job1(),  new Job2() };
```
And then interate for them in foreach
```
foreach(var job in _jobs)
{
   job.DoStuff();
}
```

In this case your jobs instantiated in your root class (and runned outside of `Mvc` world). So you probably could use `ServiceLocator` here. But there is still a lot of options how you could improve your code, so it will work without any `Locator`. Just like @davidfowl mention, you could just resolve your composite root - `IJobRunner` from a service provider (which could be avaible inside of `Main` method, your entry point). So now your code become a lot more clear.

I still cannot find any `Real` legit sample of `ServiceLocator` pattern in aspnet core apps. May be i wrong, if so, i would really apreciate some code sample where this pattern would be really necessary.

Anyway this pattern is mostly legacy of old cruel world, when we have to use it becouse of some framework not allow us to extend it parts whith custom constructor (remember this WCF, WF and WCSF stuff :horse:). We had to jump around it and tried to inject our dependencies from some `ServiceLocators`, `BusinessDelegates` and many other foolish and not really usefull patterns. Just to mock simple contstructor injection

**Comment by SimonOrdo** [comment]
@davidfowl @laskoviymishka
Thanks for that!  That helped clear it up.  This was, in fact, in response to a requirement where jobs are instantiated as part of a background process.  

I understand now how to implement the service locator pattern, if necessary.

**Comment by laskoviymishka** [comment]
@SimonOrdo i have implement the very same requirement :sweat_smile:. I just register a lot of `IJob` classes in service container, and then inject an `IEnumerable<IJob>` into `IJobRunner`. Them from `IServiceProvider` i got the `IJobRunner` instance.
Here part of my `Startup.cs`:
```
public class Startup
    {
        private static IJobRunner jobRunner;
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddJobs(); // extension that register `IJob` instances and one `IJobRunner` root
        }

        public void Configure(IApplicationBuilder app, ILoggerFactory loggerFactory)
        {
             using (var serviceScope = app.ApplicationServices.GetRequiredService<IServiceScopeFactory>().CreateScope())
            {
                jobRunner = serviceScope.ServiceProvider.GetService<IJobRunner>();
            }
        }

        public static void Main(string[] args)
        {
            var host = new WebHostBuilder()
                .UseContentRoot(Directory.GetCurrentDirectory())
                .UseIISIntegration()
                .UseKestrel()
                .UseStartup<Startup>()
                .Build();

            jobRunner.Run(); // this run in parralel thread my jobs
            host.Run();
        }
    }
```
