### ISSUE TITLE
System.InvalidOperationException: Unknown error '3'.

### ISSUE THREAD

**Issue by nsankaranarayanan** [aspnet/Home#1536]
I am using the .NET Core SDK binaries (preview 1) in a windows server 2016 TP5 docker container. I am using the same in a CentOS 7.

My basic ASP.Net application works fine in the CentOS 7 docker container whereas the same application is giving the following error in the Windows Server 2016 TP5 docker container.
Interestingly a "Hello World" application works fine.

Here is the output from a sample application from https://docs.asp.net/en/1.0.0-rc2/getting-started.html

**Error Details
==========**
Project DockerTest2 (.NETCoreApp,Version=v1.0) will be compiled because expected outputs are missing
Compiling DockerTest2 for .NETCoreApp,Version=v1.0

Compilation succeeded.
    0 Warning(s)
    0 Error(s)

Time elapsed 00:00:03.3389819

```
Unhandled Exception: System.InvalidOperationException: Unknown error '3'.
   at System.StringNormalizationExtensions.IsNormalized(String value, NormalizationForm normalizationForm)
   at Microsoft.AspNetCore.Server.Kestrel.Http.PathNormalizer.NormalizeToNFC(String path)
   at Microsoft.AspNetCore.Server.Kestrel.ServerAddress.FromUrl(String url)
   at Microsoft.AspNetCore.Server.Kestrel.KestrelServer.Start[TContext](IHttpApplication`1 application)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.Start()
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host, CancellationToken token, String shutdownMessage)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host)
   at aspnetcoreapp.Program.Main(String[] args)
```

**Comment by Tratcher** [comment]
What URLs were you registering the server with?

I don't have an explanation, but I can say that PathNormalizer.NormalizeToNFC has been removed after rc2 so you should not see this exact issue in the future.

**Comment by nsankaranarayanan** [comment]
I am registering with the below URLs.
.UseUrls("http://0.0.0.0:5001", "http://0.0.0.0:5002")

The fact it works in Linux docker container makes me think that it should work with the Windows Server 2016 TP5 containers as well (Same runtime version).

**Comment by Tratcher** [comment]
This is most likely a https://github.com/dotnet/corefx issue. Try the following code:

```
            var test = "http://0.0.0.0:5001";
            if (!test.IsNormalized(NormalizationForm.FormC))
            {
                test = test.Normalize(NormalizationForm.FormC);
            }
```

**Comment by Tratcher** [comment]
Similar issue: https://github.com/aspnet/MusicStore/issues/586

**Comment by Tratcher** [comment]
Filed a new bug here: https://github.com/dotnet/corefx/issues/9253
