### ISSUE TITLE
RC2 Toolset - compile to NuGet option missing on Publish

### ISSUE THREAD

**Issue by mjeson** [aspnet/Home#1537]
In my RC1 solution, under Publish > Settings > File Publish Options, there is a checkbox for "Compiled source files into NuGet packages". Once I installed the RC2 toolset Preview 1, this checkbox is no longer there. This is breaking the deployment. Help.

Publish before installing RC2 Toolset Preview 1
![rc1-publish](https://cloud.githubusercontent.com/assets/12972146/15763008/df8d06d8-28d5-11e6-88ab-4cb761af707f.png)

Publish after installing RC2 Toolset Preview 1
![rc2toolsetpreview1-publish](https://cloud.githubusercontent.com/assets/12972146/15763035/197d9a06-28d6-11e6-8ab6-a051a934b346.PNG)

**Comment by davidfowl** [comment]
There's no more "publish as nuget packages" in RC2. By default, everything is compiled as dlls in the output folder (like a regular console application).

**Comment by davidfowl** [comment]
Oh, I just noticed this is an RC1 app published with RC2 tooling.

/cc @vijayrkn @sayedihashimi

**Comment by mjeson** [comment]
Yes it is. My project is entirely written in RC1. None of its source files changed nor migrated to RC2. The only thing changed is it is published with RC2 Toolset Preview 1. The solution no longer publish the same way because of this missing option.

**Comment by vijayrkn** [comment]
we removed this option ("Compile source files into NuGet packages") from the Publish dialog in rc2 tooling because this is not applicable for dotnet projects any more.

In order to publish an rc1 project with the –no-source option from VS, you can add this target to the pubxml (target needs to be inside the project and outside the propertygroup). 

```xml
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
<all your existing property group values>
  </PropertyGroup>

     <Target Name="DnuNoSourcePublish" AfterTargets="GatherAllFilesToPublish" Condition=" '$(CompileSource)' == 'true' ">
        <Exec
          Condition="Exists('$(PublishOutputPath)') and '$(PublishOutputPath)'!='' "
          Command="rmdir /S /Q &quot;$(PublishOutputPath)&quot;"
          WorkingDirectory="$(MSBuildProjectDirectory)" />

        <PropertyGroup>
          <DnuCommand>&quot;$(SDKToolingDirectory)\bin\dnu.cmd&quot; publish</DnuCommand>
          <RuntimeArgument Condition=" '$(FinalPublishVersion)' != '' " >--runtime $(FinalPublishVersion)</RuntimeArgument>
          <WwwRootArgument Condition=" '$(WebRoot)' != '' " >--wwwroot $(WebRoot)</WwwRootArgument>
          <WwwRootOutArgument Condition=" '$(WwwRootOut)' != '' " >--wwwroot-out $(WwwRootOut)</WwwRootOutArgument>
          <IISCommandArgument Condition =" '$(IISCommand)' != ''">--iis-command $(IISCommand)</IISCommandArgument>
          <NoSourceArgument Condition=" '$(CompileSource)' == 'true' ">--no-source</NoSourceArgument>
          <NativeArgument Condition="'$(NativeFlag)' == 'true'">--native</NativeArgument>
          <IncludeSymbolsArgument Condition=" '$(IncludeSymbolsFlag)' == 'true'">--include-symbols</IncludeSymbolsArgument>
          <QuietArgument Condition=" '$(QuietFlag)' == 'true'">--quiet</QuietArgument>
        </PropertyGroup>

        <Exec
          Command="SET PATH=$(ExternalToolsPath);@(DnuPublishEnvironmentVariables)
          $(DnuCommand) &quot;$(KPackWorkingDirectory)&quot; --out &quot;$(PublishOutputPathNoTrailingSlash)&quot; --configuration $(PublishConfiguration) $(RuntimeArgument) $(WwwRootArgument) $(WwwRootOutArgument) $(IISCommandArgument) $(NoSourceArgument) $(QuietArgument) $(NativeArgument) $(IncludeSymbolsArgument)"
          WorkingDirectory="$(KPackWorkingDirectory)"/>
      </Target>
</Project>```

Make sure your property group has this property set
 <CompileSource>true</CompileSource>

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
