### ISSUE TITLE
How to generate a picture verification code in .net Core?

### ISSUE THREAD

**Issue by John0King** [aspnet/Home#1539]
I can't find any samples about picture verification code in current .net Core RC2.

**Comment by Tratcher** [comment]
@HaoK @blowdart @divega

**Comment by blowdart** [comment]
That's because it is not a feature we offer. There are extension points where you could add it yourself though.

**Comment by baocang** [comment]
# ## ###

**Comment by Oger-Me** [comment]
can you recommand some extensions about build verification code?

**Comment by joeaudette** [comment]
why not use recaptcha? that is what most people use and it is very easy to integrate

**Comment by Oger-Me** [comment]
@joeaudette I'm in China. can't  access the google's services. Is there anything else do you recommand ?

**Comment by GuardRex** [comment]
http://www.yinxiangma.com/ is recommended in http://stackoverflow.com/a/24000429

**Comment by John0King** [comment]
@blowdart   even js can easyly generate  a picture with text . 
Is .net Core really powerless ?
