### ISSUE TITLE
Create an Ubuntu/Debian PPA/repo

### ISSUE THREAD

**Issue by atrauzzi** [aspnet/Home#154]
While it's very easy to get started playing around with vnext in Windows, if you're looking for feedback from other platforms, it really should be easier to install.  Not just for the sake of testing, but to also demonstrate a commitment to making vnext available for all non-Microsoft platforms.

To accomplish this, I think you should set up a PPA for the k runtime so that all of it's system-level dependencies in linux can be satisfied with considerably less effort from curious end users (would be adopters!).
It might just be a matter of creating a package that also adds (or suggests) the repository found here: http://www.mono-project.com/download/#download-lin -- and then installs KVM/KRE.

A significant number of linux users rely on this mechnism to obtain software and have come to expect it from reputable projects.  While vnext is still under development, I think it's important that this distribution mechanism be established while it's still early days.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
