### ISSUE TITLE
Dependency injection in console app

### ISSUE THREAD

**Issue by Daniel15** [aspnet/Home#1544]
Is there an "official" way to use the ASP.NET Core dependency injection framework in a console app, or do I just need to create my own `ServiceCollection` and populate it myself?

Also, is there a way to get the environment name (`IHostingEnvironment.EnvironmentName`) in a console app or do I just need to read an environment variable myself?

**Comment by cwe1ss** [comment]
AFAIK there's no official "template" for console applications that includes DI etc. You can just create your own `ServiceCollection` - just make sure you add core components like [Logging](https://github.com/aspnet/Logging) and [Options](https://github.com/aspnet/Options) in case you want to use them:
```c#
var services = new ServiceCollection();

services.AddLogging(); // requires "Microsoft.Extensions.Logging"
services.AddOptions(); // requires "Microsoft.Extensions.Options"

// ...add your own services...

var serviceProvider = services.BuildServiceProvider();

// now you can resolve services
var loggerFactory = serviceProvider.GetRequiredService<ILoggerFactory>();
```

`IHostingEnvironment` is a feature of [aspnet/Hosting](https://github.com/aspnet/Hosting), so this is web specific. You can easily read the variable yourself with `Environment.GetEnvironmentVariable("ASPNETCORE_ENVIRONMENT")` - that's also [how it's done in aspnet/Hosting](https://github.com/aspnet/Hosting/blob/dev/src/Microsoft.AspNetCore.Hosting/WebHostBuilder.cs#L44).

**Comment by Daniel15** [comment]
Thanks, good enough for me :+1:

**Comment by bragma** [comment]
Pardon me if I resume this from the dead and if the question is trivial, but is there any way to use DI in constructors without having to manually call serviceProvider.GetRequiredService()? Am I missing something?
Thanks!

**Comment by cwe1ss** [comment]
Yes, you should register your services in the DI framework and use constructor injection!

**Comment by bragma** [comment]
Thanks!

**Comment by billHaggerty** [comment]
I cant seem to find the class ServiceCollection. I got both nuget packages Microsoft.Extensions.DependencyInjection and Microsoft.Extensions.DependencyInjection.Abstractions. then I import the Microsoft.Extensions.DependencyInjection namespace. 

No ServiceCollection classes anywhere. What did you reference to get ServiceCollection?

**Comment by dungtm007** [comment]
Hi @billHaggerty  
Add this one, Microsoft.Extensions.DependencyInjection, from Nuget

It'll work.
