### ISSUE TITLE
Help running .net 4 dependent libraries in rc2

### ISSUE THREAD

**Issue by jamesla** [aspnet/Home#1545]
When running install-package docx to my aspnet core rc2 project I get the following error:

    Package DocX 1.0.0.19 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package DocX 1.0.0.19 supports: net40 (.NETFramework,Version=v4.0)
    One or more packages are incompatible with .NETCoreApp,Version=v1.0.

I understand that is because it is dependent on .net 4 so I added the net40 to my project.json file. 

    "frameworks": {
    "netcoreapp1.0": {
      "imports": [
        "dotnet5.6",
        "dnxcore50",
        "net40",
        "portable-net45+win8"
      ]
    }
  },

net40 installs correctly however the docx library still causes the same error.

How can I install a library that has a dependency on .net 4 in an aspnet core rc2 application?

(PS this works fine in my rc1 project).

**Comment by davidfowl** [comment]
You can't target netcoreapp1.0 and use a .NET 4.0 library. You'll need to pick the ASP.NET Core (.NET Framework) project template instead.

**Comment by jamesla** [comment]
Ah yes that was the problem wasn't aware of the seperation of .core and framework projects, thank you.
