### ISSUE TITLE
have a docker image for ASP.NET on dotnet CLI

### ISSUE THREAD

**Issue by tugberkugurlu** [aspnet/Home#1546]
because dotnet CLI image is not enough as ASP.NET Core has other dependencies e.g. libuv.

**Comment by davidfowl** [comment]
libuv comes as a nuget package since RC2. ASP.NET only depends on nuget packages at this point.

**Comment by tugberkugurlu** [comment]
is it only on coreclr? I got an error on mono complaining that it cannot locate libuv.

**Comment by davidfowl** [comment]
It's for everything. In RC2 a reference to Microsoft.NETCore.Platforms is needed. It won't be for RTM

**Comment by Daniel15** [comment]
> I got an error on mono complaining that it cannot locate libuv.

Make sure you publish using the right runtime identifier and it'll bundle the Linux version of libuv. Example command line:
```
dotnet publish MyApp -o c:\Temp\Publish -c Release -r debian-x64
```
It looks like there's `debian-x64` and `rhel-x64` available.

**Comment by davidfowl** [comment]
You don't need that if you have `"type": "platform"` only if you're trying to deploy the entire runtime with your application.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
