### ISSUE TITLE
RC2 - Preview Tooling, .NET Core Library template.

### ISSUE THREAD

**Issue by dazinator** [aspnet/Home#1548]
Created a new ASP.NET Core Library, by default creates this project.json:

```
{
  "version": "1.0.0-*",

  "dependencies": {
    "NETStandard.Library": "1.5.0-rc2-24027"
  },

  "frameworks": {   
    "netstandard1.5": {
      "imports": "dnxcore50"
    }
  }
}
```

That's great, but as soon as you try and multi target by adding another framework:

```
{
  "version": "1.0.0-*",

  "dependencies": {
    "NETStandard.Library": "1.5.0-rc2-24027"
  },

  "frameworks": {
    "net461" : { },
    "netstandard1.5": {
      "imports": "dnxcore50"
    }
  }
}

```

You get this - the `NETStandard.Library` cannot be resolved.

![image](https://cloud.githubusercontent.com/assets/3176632/15805941/b9076308-2b2f-11e6-8b12-3036e7524f5c.png)

(The null ref exception I have raised as a seperate issue: #1547 

Would it not make more sense to have the project.json file by default, list the `NETStandard.Library` dependency as a dependency of the `netstandard1.5` framework, rather than list it as a common dependency  - because it seems to be incompatible with most other frameworks. Or is this compatibility issue something that will be fixed by the final release of the tooling?

**Comment by svick** [comment]
Did you Restore Packages after making the change? (The tooling around this could certainly be improved.)

**Comment by dazinator** [comment]
ahhh crap - yeah that was it.. :(
