### ISSUE TITLE
RC2 adding/appending header in middleware throws exception

### ISSUE THREAD

**Issue by Sharpiro** [aspnet/Home#1549]
This line of code
```
context.Response.Headers.Add("TestHeader", "true");
```
in [this file](https://github.com/Sharpiro/DotnetCoreTools/blob/0efe7a7e374153dea0d7064a8caa1614ff4c54a6/DotnetCoreTools.WebTest/TestMiddleware.cs#L18) is throwing this exception:
```
Exception thrown: 'System.InvalidOperationException' in Microsoft.AspNetCore.Server.Kestrel.dll
```

[Simplified Example](https://github.com/Sharpiro/DotnetCoreTools/tree/issues/adding-headers)

**Comment by davidfowl** [comment]
Where is the real exception and the stack trace? You can't add to the headers after the response has been written to (that's the thing you're likely running into).

**Comment by Sharpiro** [comment]
Ahh, you are correct once again haha!

I guess I was a bit confused as this exact middleware works in the "old" stack, and I think it may have worked in older versions of dotnet core since [this guide](https://www.exceptionnotfound.net/writing-custom-middleware-in-asp-net-core-1-0/) writes essentially the same middleware and calls the ```await _next.Invoke(context)``` line in the same place as I was doing.

By moving the line ```await _next.Invoke(context)``` to _after_ the code where I update the headers, it now works.

My only concern is that now my middleware may not have "final say" as to what the header values are since it may not be the last to update them.

**Comment by davidfowl** [comment]
@Sharpiro you can work around this by handling OnStarting in your middleware: https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.AspNetCore.Http.Abstractions/HttpResponse.cs#L73.

That way you get a chance to handle it no matter when the response gets flushed. The cookie middleware uses this to set cookie headers at the "right" time (before the response is flushed).

ASP.NET 4.x used to buffer the entire response body and we don't do that anymore.

**Comment by Sharpiro** [comment]
thanks, this worked well.
