### ISSUE TITLE
Remove the requirement that projects specify what type of process they'll run in

### ISSUE THREAD

**Issue by atrauzzi** [aspnet/Home#155]
As per @davidfowl: https://github.com/aspnet/KRuntime/issues/691#issuecomment-57740872

Right now when I set up a project.json, I have to do this:

```
{
     "dependencies": {
        "Kestrel": "1.0.0-alpha3",
        "Microsoft.AspNet.Hosting": "1.0.0-*",
        "Microsoft.AspNet.Server.WebListener": "1.0.0-alpha3"
    },
    ...
}
```

Unfortunately, this guarantees that my project will always be distributing n-1 libraries that are not applicable to any target it is hosted via.

Instead, I should be able to specify none of these packages and have the server configuration ensure and select a library to bootstrap the project.

For situations where there is a feature or infrastructure required of a specific type of server (IIS), a special interface/binding package should be specified to clearly denote the dependency on that functionality. This would also have the benefit of allowing different implementations for those interfaces should someone so desire:

```
{
    "dependencies": {
        "Some.Feature.Common.To.IIS": "",
        "Some.Other.Feature.Common.To.IIS": "",
        "A.Different.Host.Feature": ""
    },
    ...
}
```

If this is already possible, then I'd love to either be pointed to or see documentation provided as my suggestion here is more customizable than forcing the app to know about what kind of server it's run on.

WSGI does not require the application to be aware of or alter it's behaviour based on the server it runs on and K hopefully strives for the same. You can imagine how boilerplatey these lists of servers could get if someone wanted to ensure their app could run on anything. It would basically be a static list of every server implementation under the sun.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
