### ISSUE TITLE
Updated VS Tool ASP.NET and Web Tools RC2 - CANT RUN WEB API

### ISSUE THREAD

**Issue by SepiaGroup** [aspnet/Home#1550]
I accidently updated the ASP.NET and Web Tools and now I get an error on 

// Entry point for the application.
public static void Main(string[] args) => WebApplication.Run<Startup>(args);

An unhandled exception of type 'System.InvalidOperationException' occurred in Microsoft.Extensions.DependencyInjection.Abstractions.dll

Additional information: No service for type 'Microsoft.Extensions.PlatformAbstractions.IApplicationEnvironment' has been registered.

Is there a way to uninstall this or fix this error? I am stuck until this is resolved.

my package json

{
  "commands": {
    "web": "Microsoft.AspNet.Server.Kestrel",
    "ef": "EntityFramework.Commands"
  },
  "buildOptions": {
    "emitEntryPoint": true
  },
  "configurations": {
    "Development": { },
    "Production": { }
  },
  "dependencies": {
    "Microsoft.AspNet.IISPlatformHandler": "1.0.0-rc1-final",
    "Microsoft.AspNet.Mvc": "6.0.0-rc1-final",
    "Microsoft.AspNet.Server.Kestrel": "1.0.0-rc1-final",
    "Microsoft.AspNet.StaticFiles": "1.0.0-rc1-final",
    "Microsoft.Extensions.Configuration.FileProviderExtensions": "1.0.0-rc1-final",
    "Microsoft.Extensions.Configuration.Json": "1.0.0-rc1-final",
    "Microsoft.Extensions.Logging": "1.0.0-rc1-final",
    "Microsoft.Extensions.Logging.Console": "1.0.0-rc1-final",
    "Microsoft.Extensions.Logging.Debug": "1.0.0-rc1-final",
    "Microsoft.AspNet.Authentication.Cookies": "1.0.0-rc1-final",
    "Microsoft.AspNet.Diagnostics.Entity": "7.0.0-rc1-final",
    "Microsoft.AspNet.Identity.EntityFramework": "3.0.0-rc1-final",
    "Microsoft.Extensions.CodeGenerators.Mvc": "1.0.0-rc1-final",
    "Microsoft.Extensions.Configuration.UserSecrets": "1.0.0-rc1-final",
    "Newtonsoft.Json": "8.0.3",
    "Tombstone.DataAccess": "1.0.0-*",
    "System.IdentityModel.Tokens": "5.0.0-rc1-211161024",
    "Microsoft.AspNet.Authentication.JwtBearer": "1.0.0-rc1-final",
    "Microsoft.Framework.ConfigurationModel.Json": "1.0.0-beta4",
    "Microsoft.AspNet.Cors": "6.0.0-rc1-final",
    "Microsoft.AspNet.Mvc.WebApiCompatShim": "6.0.0-rc1-final"
  },
  
  "exclude": [
    "wwwroot",
    "node_modules"
  ],

  "frameworks": {
    "dnx451": {

    }
  },
  "publishOptions": [
    "**.user",
    "**.vspscc"
  ],
  "userSecretsId": "aspnet5-sampleNet5-355b5a0f-5b40-4082-aad6-e54e6db9c223",
  "version": "1.0.0-*"
}

thanks

**Comment by davidfowl** [comment]
Is the question how you can downgrade back to RC1? Or do you want to run with RC2?

**Comment by SepiaGroup** [comment]
I wanted to go back to RC1 but I pushed ahead and got it to work on RC2. what not easy but it seems to work now.

my project.json is (i think i updated everything to rc2). 

{
  "buildOptions": {
    "emitEntryPoint": true
  },
  "commands": {
    "web": "Microsoft.AspNet.Server.Kestrel",
    "ef": "EntityFramework.Commands"
  },
  "configurations": {
    "Development": { },
    "Production": { }
  },
  "dependencies": {
    "Microsoft.NETCore.App": {
      "type": "platform",
      "version": "1.0.0-rc2-*"
    },
    "Microsoft.AspNetCore.Authentication.JwtBearer": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Identity.EntityFrameworkCore": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Authentication.Cookies": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Cors": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Mvc": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Mvc.WebApiCompatShim": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.StaticFiles": "1.0.0-rc2-final",
    "Microsoft.Extensions.CodeGenerators.Mvc": "1.0.0-rc1-final",
    "Microsoft.Extensions.Configuration.FileExtensions": "1.0.0-rc2-final",
    "Microsoft.Extensions.Configuration.Json": "1.0.0-rc2-final",
    "Microsoft.Extensions.Configuration.UserSecrets": "1.0.0-rc2-final",
    "Microsoft.Extensions.Logging": "1.0.0-rc2-final",
    "Microsoft.Extensions.Logging.Console": "1.0.0-rc2-final",
    "Microsoft.Extensions.Logging.Debug": "1.0.0-rc2-final",
    "Microsoft.Framework.ConfigurationModel.Json": "1.0.0-beta4",
    "Newtonsoft.Json": "8.0.3",
    "Microsoft.IdentityModel.Tokens": "5.0.0-rc2-305061149",
    "Tombstone.DataAccess": "1.0.0-*",
    "Microsoft.AspNetCore.Identity": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Diagnostics": "1.0.0-rc2-final",
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.0.0-rc2-final"
  },
  "exclude": [
    "wwwroot",
    "node_modules"
  ],
  "frameworks": {
    "netcoreapp1.0": {
      "imports": [ "dnxcore50", "portable-net45+win8" ]
    }
  },
  "publishOptions": [
    "**.user",
    "**.vspscc"
  ],
  "userSecretsId": "aspnet5-sampleNet5-355b5a0f-5b40-4082-aad6-e54e6db9c223",
  "version": "1.0.0-*"
}

**Comment by GuardRex** [comment]
@SepiaGroup Some links to help with conversions: https://github.com/dotnet/cli/issues/2135#issuecomment-212692267

- `commands` are :skull:
- `exclude` goes into `buildOptions > compile > exclude`
- `publishOptions` should `include` and `exclude` things

More details can be found in https://github.com/aspnet/Announcements/issues/175 and in the schema: http://json.schemastore.org/project

**Comment by cwe1ss** [comment]
You should also remove the dependency `"Microsoft.Framework.ConfigurationModel.Json": "1.0.0-beta4"` - this package was renamed to `Microsoft.Extensions.Configuration.Json` (which you already have in your dependency list)

And I think there's no "configurations" section in project.json

**Comment by GuardRex** [comment]
Good point: `configurations` is in `buildOptions`, but they didn't mark it in the root as depreciated in the schema. The schema is in need of a few updates; however, with the file going away soon, I guess 'what's the point?' is a possible feeling.
