### ISSUE TITLE
Path.GetFullPath in netstandard1.2 can not be builded

### ISSUE THREAD

**Issue by Sebosek** [aspnet/Home#1551]
Hi there,

I want to use Path.GetFullPath in class library targeting to netstandard1.2 but build ends up with: _'Path' does not contain a definition for 'GetFullPath'_.
By description at [nuget.org](https://www.nuget.org/packages/System.Runtime.Extensions/4.1.0-rc2-24027) I should use netstandard1.0, netstandard 1.3 or 1.5 (Why just odd versions?), So I decide to target at 1.0, but still build is ending with described error. What am I missing?
(One of application what this library should use is asp.net core webapi running at .net fw 4.5.1)

Here is my project.json

```
{
  "dependencies": {
    "NETStandard.Library": "1.0.0-rc2-24027",
    "System.Diagnostics.FileVersionInfo": "4.0.0-rc2-24027",
    "Microsoft.AspNetCore.Mvc": "1.0.0-rc2-final",
    "System.Runtime.Extensions": "4.1.0-rc2-24027",
    "System.Runtime": "4.1.0-rc2-24027"
  },

  "frameworks": {
    "netstandard1.0": {
      "imports": [
        "dnxcore50",
        "dnx451"
      ]
    }
  },

  "version": "1.0.0-*"
}
```

**Comment by Tratcher** [comment]
This is a question for https://github.com/dotnet/corefx or nuget.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
