### ISSUE TITLE
TargetFrameworkVersion in xproj

### ISSUE THREAD

**Issue by dazinator** [aspnet/Home#1552]
When updating an RC1 based xproj file, to the new RC2 based (preview tooling) format, I notice that the xproj file now has:

```
 <TargetFrameworkVersion>v4.5</TargetFrameworkVersion>
```

I am confused.. aren't the frameworks you are targeting declared in the `project.json` file still? (i.e for multi targeting) How does this msbuild property actually affect the build?

**Comment by tomakita** [comment]
I'm also confused about this, and haven't been able to find any documentation about this TargetFrameworkVersion element.  Does anyone know what this does?

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
