### ISSUE TITLE
Roadmap document is out of data

### ISSUE THREAD

**Issue by bitbonk** [aspnet/Home#1553]
Looks like the [document about the ASP.NET Core Roadmap](https://github.com/aspnet/Home/wiki/Roadmap) is out of date. RC2 has already been released. Is 1.0 still planned for June?

**Comment by LyalinDotCom** [comment]
The framework RTM dates is accurate in the roadmap, we announced shipping the Core RTM on 6/27 (this upcoming monday) and it will also include tooling Preview 2, as tooling is not going RTM at the same time, but later in the year.

You can see all our announcements here from .NET Conf: https://blogs.msdn.microsoft.com/dotnet/2016/06/09/thank-you-for-watching-dotnetconf-2016/

**Comment by bitbonk** [comment]
Yes, now there are. They weren't when I posted this. 
Can be closed.
