### ISSUE TITLE
Stuck converting some RC1 code to RC2 - `LibraryDescription`?

### ISSUE THREAD

**Issue by dazinator** [aspnet/Home#1554]
In RC1 we used to be able to get all assemblies referencing a particular assembly (for example, this assembly), and load those assemblies into a list like so:

```
ILibraryManager libraryManager = GetLibraryManager();
var thisAssemblyName = this.GetType().Assembly.GetName().Name;

IEnumerable<Library> librariesThatReferenceThisAssembly = libraryManager.GetReferencingLibraries(thisAssemblyName);

var assemblies = new List<Assembly>();
IAssemblyLoadContextAccessor assemblyLoadContextAccessor = GetAssemblyLoadContextAccessor();
foreach (var item in librariesThatReferenceThislIbrary)
                {
                    assemblies.AddRange(item.Assemblies.Select(assy =>
                    assemblyLoadContextAccessor.Default.Load(assy))
                    );
                }


```

In the RC2 world, `libraryManager.GetReferencingLibraries(thisAssemblyName)` now returns enumerable `LibraryDescription` as opposed to `Library`. How do you get the assemblies from an `LibraryDescription` in order to load them? The API looks drastically different.

I am aware that once I have the assemblies, I can replace calls to `IAssemblyLoadContextAccessor` with Assembly.Load* on desktop CLR and AssemblyLoadContext.Default.Load* on CoreCLR - but its getting the assembly names / paths in the first place that I am stuck on!

**Comment by davidfowl** [comment]
See https://github.com/aspnet/Announcements/issues/149

**Comment by dazinator** [comment]
Thanks @davidfowl but I had already read that announcement before raising this question!

The announcement shows how to list dependencies of an assembly, by getting a `DependencyContext` for that particular assembly.

What I want to do though, is get all Libraries that are referencing my library, and then get all of the assemblies from those libraries. 

Getting all the Libraries that are referencing my Library is relatively simple still, even though the return type is now `LibraryDescription` rather than `Library`. However once you have those, I can no longer seem to get at the `Assemblies` for that `LibraryDescription`.

I can't get a `DependencyContext` without first having an `Assembly` to load a `DependencyContext` for, so this doesn't help me discover the assemblies in those Libraries referencing mine..

Hopefully I am missing something simple, and If I am I humbly apologise!

**Comment by dazinator** [comment]
basically a short version of the same question, in RC1 I could do this:

```
_libraryManager.GetLibraries().SelectMany(l => l.Assemblies).Distinct().ToList();

```

How do I get the assemblies for a Library in RC2?

**Comment by dazinator** [comment]
Have also raised on stackoverflow here: http://stackoverflow.com/questions/37704742/stuck-converting-some-rc1-code-to-rc2

**Comment by davidfowl** [comment]
See how MVC does it https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Core/Internal/DefaultAssemblyPartDiscoveryProvider.cs#L55-L158

**Comment by dazinator** [comment]
Thanks @davidfowl
