### ISSUE TITLE
"Microsoft.Extensions.Caching.Memory": "1.0.0-rc2-final" doesn't support "services.AddCaching()"

### ISSUE THREAD

**Issue by Neurothustra** [aspnet/Home#1556]
reverting the dependency back to 1.0.0-rc1-final does provide the definition for services.AddCaching(), but then complains about three dependency conflicts expecting 1.0.0-rc2 but only getting rc1:
Microsoft.AspNetCore.Mvc
Microsoft.AspNetCore.Mvc.Razor.Host 
Microsoft.AspNetCore.Mvc.TagHelpers

**Comment by pranavkm** [comment]
Did you mean to use `services.AddMemoryCache()`?

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
