### ISSUE TITLE
QUESTION: How to implement the OAuth 2 server in ASP.NET Core web application(.net core)?

### ISSUE THREAD

**Issue by tedzhao** [aspnet/Home#1557]
How to implement the OAuth 2 server in ASP.NET Core web application(.net core)?

**Comment by davidfowl** [comment]
We don't have any Oauth2 server implementation in ASP.NET Core but you can use https://github.com/IdentityServer/IdentityServer4 or https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server or https://github.com/openiddict/openiddict-core

**Comment by geminiyellow** [comment]
need demo

**Comment by brockallen** [comment]
Lots of samples and walkthrus here: https://identityserver4.readthedocs.io/en/release/quickstarts/0_overview.html

**Comment by rontran** [comment]
Problem with IdentityServer4 is there are no examples for 1.0.0 to hookup up to mongodb.  Not everyone uses IF and sql server.

**Comment by brockallen** [comment]
Using Mongo or any other data store is just an exercise in implementing the store interface. Here are the 3 in-memory implementations you'd need to replicate with Mongo: https://github.com/IdentityServer/IdentityServer4/tree/dev/src/IdentityServer4/Stores/InMemory

**Comment by rontran** [comment]
and what about UserStore?  I see TestUserStore but it doesn't implement any interface.

**Comment by brockallen** [comment]
> and what about UserStore? I see TestUserStore but it doesn't implement any interface.

That's entirely up to your UI layer. Do whatever you need. If you want to use ASP.NET Identity, then you'd look to implement a mongo store for that.

**Comment by Rilton** [comment]
I know this an old post, but if you are still looking for a sample you may wish to take a look into this - https://github.com/Rilton/IdentityServer4.Samples.Mongo

**Comment by pjavan** [comment]
Thought I'd put this out there if anyone is still looking:  [https://bitbucket.org/easydynamics/edc.netcore.auth](https://bitbucket.org/easydynamics/edc.netcore.auth)

**Comment by yukund** [comment]
Hi ,
Will ASP.NET Core 2 implement Oauth2 server?  Is it on the ASP.NET Core 2.x road map.

Or we should use third party solutions suggested below.
Thanks
Y

> We don't have any Oauth2 server implementation in ASP.NET Core but you can use https://github.com/IdentityServer/IdentityServer4 or https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server or https://github.com/openiddict/openiddict-core

**Comment by jorgensigvardsson** [comment]
I think ASP.NET Core should not implement an oauth server of any kind. Why bloat ASP.NET Core? Just use third party NuGets...

**Comment by Eilon** [comment]
Closing this issue because there is already further discussion in https://github.com/aspnet/Identity/issues/503 and https://github.com/aspnet/Identity/issues/1460.

**Comment by BKlippel** [comment]
lame

**Comment by BKlippel** [comment]
typical microsoft, breath heavy and no follow through. one way or another, even by standalone package UseOAuthAuthorizationServer should have been ported for compatibility.
