### ISSUE TITLE
Could not load type 'Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing.DiagnosticsListener' from assembly 'Microsoft.ApplicationInsights, Version=2.1.0.0

### ISSUE THREAD

**Issue by sureshbandi** [aspnet/Home#1559]
I created a .NET Core web application and tried to run on ubuntu with the help of mono 4.4 target framework 4.5.1, I am facing following exception 

> Unhandled Exception:
> System.TypeLoadException: Could not load type 'Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing.DiagnosticsListener' from assembly 'Microsoft.ApplicationInsights, Version=2.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
>   at Microsoft.AspNetCore.Hosting.Internal.WebHost.Initialize () <0x40a768d0 + 0x0001f> in <filename unknown>:0 
>   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build () <0x40a5fee0 + 0x00167> in <filename unknown>:0 
>   at Socioboard.Program.Main (System.String[] args) [0x00001] in /home/glb-014/Documents/Socioboard/src/Socioboard/Program.cs:14 
> [ERROR] FATAL UNHANDLED EXCEPTION: System.TypeLoadException: Could not load type 'Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing.DiagnosticsListener' from assembly 'Microsoft.ApplicationInsights, Version=2.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
>   at Microsoft.AspNetCore.Hosting.Internal.WebHost.Initialize () <0x40a768d0 + 0x0001f> in <filename unknown>:0 
>   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build () <0x40a5fee0 + 0x00167> in <filename unknown>:0 

and here is my project.json

`{
  "dependencies": {
    "Microsoft.ApplicationInsights.AspNetCore": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Mvc": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.0-rc2-final",
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.0.0-rc2-final",
    "Microsoft.Extensions.Configuration.FileExtensions": "1.0.0-rc2-final",
    "Microsoft.Extensions.Configuration.Json": "1.0.0-rc2-final",
    "Microsoft.Extensions.Logging": "1.0.0-rc2-final",
    "Microsoft.Extensions.Logging.Console": "1.0.0-rc2-final",
    "Microsoft.Extensions.Logging.Debug": "1.0.0-rc2-final",
    "Serilog": "2.0.0-rc-598",
    "Serilog.Extensions.Logging": "1.0.0-rc2-10110",
    "Serilog.Sinks.ColoredConsole": "2.0.0-beta-700",
    "Serilog.Sinks.RollingFile": "2.0.0-rc-703",
    "Microsoft.Extensions.Options.ConfigurationExtensions": "1.0.0-rc2-final",
    "Microsoft.Extensions.Options": "1.0.0-rc2-final",
    "MongoDB.Bson": "2.2.4",
    "MongoDB.Driver": "2.2.4",
    "MySql.Data": "6.9.8",
    "MySql.Data.Entity": "6.9.8",
    "Newtonsoft.Json": "8.0.3",
    "NHibernate.Linq": "1.0.0",
    "StackExchange.Redis": "1.1.603",
    "Microsoft.AspNetCore.Cors": "1.0.0-rc2-final"
  },

  "tools": {
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": {
      "version": "1.0.0-preview1-final",
      "imports": "portable-net45+win8+dnxcore50"
    }
  },

  "frameworks": {
    "net451": {
      "frameworkAssemblies": {
        "System.Xml": "4.0.0.0"
      },
      "dependencies": {
        "NHibernate": "4.0.4.4000"
      }
    }
  },

  "buildOptions": {
    "emitEntryPoint": true,
    "preserveCompilationContext": true
  },

  "runtimeOptions": {
    "gcServer": true
  },

  "publishOptions": {
    "include": [
      "wwwroot",
      "Views",
      "appsettings.json",
      "web.config"
    ]
  },

  "scripts": {
    "postpublish": [ "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%" ]
  }
}
`

please help me to fix this issues.

**Comment by davidfowl** [comment]
If it works on .NET Framework and doesn't work on mono then I suggest filing a mono bug.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
