### ISSUE TITLE
Bundling and Minification workflow

### ISSUE THREAD

**Issue by hnkb** [aspnet/Home#156]
In a follow-up to https://github.com/aspnet/Home/issues/134 and https://github.com/aspnet/KRuntime/issues/238, I'm wondering how and when bundling and minification is going to be performed, if it's going to be handled by Grunt.

It doesn't make much sense to do bundling and minification in Visual Studio IDE, as it prevents editing script files outside IDE (bundles won't get updated automatically). Now that we have on-the-fly compiling in "Roslyn" and can just edit-save .NET source files without the need to rebuild, losing the same ability for CSS/JS files seems backwards.

On the other hand, if it's going to be outside the IDE, does it mean every project needs a running Node.js and Grunt installation to be able to use bundling and minification? Or maybe Grunt is going to be included as part of "bundling and minification" NuGet package?

**Comment by dpaquette** [comment]
I'm curious if there has been any movement on this? I have been replacing the runtime bundling & minification in my MVC 5 apps with Gulp tasks and linking that to build events using the Task Runner explorer. One of the interesting challenges I am facing is picking what plugins to use. There are so many options to choose from.

Is the team currently evaluating Gulp and/or Grunt plugins? If so, what requirements are you looking to cover in the File -> New Project experience?

**Comment by bdelaney** [comment]
@dpaquette, I was wondering the same thing. Meantime we may be coming up with all kinds of interesting recipes. Perhaps a combined Gist repo, something along the lines of what @tugberkugurlu has created above. But more of a clearinghouse, and not just one 'strongly opinionated' way of doing things.
It is confusing which gulp/grunt/bower packages to choose and then how to integrate them in your workflow.

**Comment by dpaquette** [comment]
@bdelaney, a combined Gist repo sounds like a great idea.

**Comment by obrienluk** [comment]
I originally wrote this reply here: https://github.com/aspnet/Home/issues/45
I currently use bundling to bundle XML files as JSON, I also have a project in my solution that bundles Javascript files extracted from a DLL using assembly.GetManifestResourceNames() and assembly.GetManifestResourceStream().
In both case I have extended the Bundle class (or ScriptBundle) and implemented the IBundleBuilder interface.
I don't think either of these tasks would be possible with OSS like Grunt or Gulp.

**Comment by pnewhook** [comment]
I hope whatever the final solution ties in transparently with the build configuration. I loved that debugging would leave the scripts uncompressed, then in Release mode files would be optimized.

**Comment by mcquiggd** [comment]
I second @dpaquette s comment regarding the difficulty in selection of Gulp (or Grunt) packages for client build tasks, even relatively simple ones. 

Currently there are issues with some packages being basically abandoned (with no way of knowing), some do not export main files correctly from their meta data, and this requires overrides. Many are duplicates with names that vary by the use of - or _ and it is difficult to select a package that is genuinely supported.

Many of the most used packages break MAX_PATH (uglify, img_min, anything that uses lo_dash etc), and break the current Git provider when trying to check in.

It's a lot more effort and maintenance than .Net bundling and minification, and so far I see little benefit.

**Comment by xtianus79** [comment]
@dpaquette and @bdelaney 

I have a grunt build I use for Foundation that is pretty robust.  To be honest I don't believe there is a way for Gulp to even handle such functionality.  With that said, if you look into the grunt file it will be a pretty good tutorial for the very best parts that Grunt has to offer and their configurations. 

the generator
https://github.com/xtianus79/generator-aspnet

the gruntfile
https://github.com/xtianus79/generator-aspnet/blob/master/templates/projects/foundation5/_gruntfile.js

the grunt configuration currently
https://github.com/xtianus79/generator-aspnet/blob/master/templates/projects/foundation5/_grunt_package.json

**Comment by dpaquette** [comment]
@xtianus79 What specifically do you think gulp can't do?

**Comment by xtianus79** [comment]
@dpaquette replicate this... and I will be a belieber.  https://github.com/xtianus79/generator-aspnet/blob/master/templates/projects/foundation5/_gruntfile.js

**Comment by dpaquette** [comment]
@xtianus79 At first glance, I don't see an individual piece of your gruntfile that could not be done using Gulp. I'm not going to replicate your huge script for you just to prove a point. I would be happy to help if there is something specific that you are unsure how to tackle with Gulp.

**Comment by xtianus79** [comment]
@dpaquette well replicating it would be a huge help actually.  I am not a gulp person but replicating it so that I could list it on my fork for foundation would be greatly appreciated.  

would you be interested in helping?

**Comment by WalkerCodeRanger** [comment]
Given the just announced [VS 2015 RTM planned for July 20](https://www.visualstudio.com/en-us/visualstudio-release-event-vs), do we have any clarification/guidance on the issues in this discussion?

**Comment by Shazwazza** [comment]
For anyone interested in runtime bundling/minification I created a project for this a while back: https://github.com/Shazwazza/smidge  I'd still recommend bundling/minification/etc... as a build step instead but in case you just want/need to do this at runtime, it's certainly an option you can use.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
