### ISSUE TITLE
Is NTLM supported on Linux?

### ISSUE THREAD

**Issue by mw007** [aspnet/Home#1561]
I'm running the MusicStore sample app (the 1.0.0-rc2 tag) on Linux and have set the `ASPNETCORE_ENV` environment variable to `NtlmAuthentication` to make it use the StartupNtlmAuthentication class.

I then added some console output to check what the ClaimsIdentity is populated with:
~~~csharp
var identity = (ClaimsIdentity)context.User.Identity;

Console.WriteLine($@"ClaimsIdentity
    Name: {identity.Name}
    Label: {identity.Label}
    AuthenticationType: {identity.AuthenticationType}
    IsAuthenticated: {identity.IsAuthenticated}
    NameClaimType: {identity.NameClaimType}
    RoleClaimType: {identity.RoleClaimType}
");
~~~

This is a sample of the output (notice everything is blank):
```
ClaimsIdentity
Name: 
Label: 
AuthenticationType: 
IsAuthenticated: False
NameClaimType: http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name
RoleClaimType: http://schemas.microsoft.com/ws/2008/06/identity/claims/role
```

I've connected my Linux machine to Active Directory using realmd, and it appears that I am authenticated. However, when I register then try to log in, it appears to fall back to regular ASP.NET Identity, which then fails with the following exception:

`System.InvalidOperationException: No authentication handler is configured to handle the scheme: Identity.Application`

Could someone confirm whether NTLM + Linux is supported?

**Comment by davidfowl** [comment]
It is not supported on Linux

**Comment by mw007** [comment]
Awesome, thank you much!
