### ISSUE TITLE
RC2 Visual Studio publish writes its own Web.Config

### ISSUE THREAD

**Issue by glent1** [aspnet/Home#1562]
I have a web.config in the root of my web project that has some application specific settings.  This is not the web.config that gets populated into the publish folder, which seems to be entirely dynamically created.  Is there any way to control this?

**Comment by ShadowDancer** [comment]
Are you sure? In my case variables like %LAUNCHER_PATH% are replaced, but custom settings like:
```
<customHeaders>
      <remove name="X-Powered-By" />
</customHeaders>
```
Are presisted into published config.

**Comment by glent1** [comment]
I'm positive - I lose an entire "security" section.

**Comment by moozzyk** [comment]
@glent1 - did you upgrade your application from RC1? If you comment out postpublish scripts does the web.config look fine after publishing?
If not, can you provide a repro/create a git repo with your app so that I can look at it and see what is happening?

**Comment by SimonOrdo** [comment]
Ad I understand it, the publish process does edit the web.config a bit to help IIS find/run the app.

Like @glent1 said, try removing this bit and see if it re-writes the config:

"postpublish": [ "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%" ]

**Comment by glent1** [comment]
I did indeed convert it from RC1.  And Beta8, Beta7 etc.  The suggestion to remove the postpublish script lead me to the real problem - I wasn't explicitly including the web.config in the publishOptions include list.  I had previously compared a clean project to mine and made the updates manually and had obviously missed this one.  Thanks for the help guys.

**Comment by moozzyk** [comment]
Yeah - that's why I asked. There are some gotchas when moving from RC1 to RC2. In this case publish-iis did not find web.config and create a new one for you. I think publish-iis actually prints a message when it happens. Found it: https://github.com/aspnet/IISIntegration/blob/dev/src/Microsoft.AspNetCore.Server.IISIntegration.Tools/PublishIISCommand.cs#L48
