### ISSUE TITLE
IIS Express leaves <head> empty and appends its content to the <body>

### ISSUE THREAD

**Issue by shadinamrouti** [aspnet/Home#1566]
Using IIS Express to debug or run an MVC Core RC2 project, will result in corrupted HTML structure at the <head> tag. The <head> tag is left empty and its content will be included in the <body> tag.
However, using Kestrel will load the web project normally and without the above bug.
![bug-with-iis-express](https://cloud.githubusercontent.com/assets/12829248/15984511/9e67e9a4-2fd6-11e6-9e76-1ab614e8c386.png)

**Comment by imranbaloch** [comment]
BrowserLink issue. See https://github.com/aspnet/Tooling/issues/520

**Comment by shadinamrouti** [comment]
It is a BrowserLink issue with Chrome. This issue is claimed to be solved in the .NET Core 1.0.0 - Visual Studio 2015 Tooling Preview 2 which was announced 3 days ago [here](https://github.com/aspnet/Announcements/issues/192).
Thanks @imranbaloch for the update.
