### ISSUE TITLE
The £ symbol doesn't render correctly when passed in from configuration

### ISSUE THREAD

**Issue by christianreddington** [aspnet/Home#1567]
I am currently making a Web API via ASP.Net Core. I tried passing in a connection string from a ConfigurationFile using the Configuration["Data:ConnectionString"]) approach, as part of the DBConext.

I struggled to understand why the user could not be authenticated against the SQL Database. Upon closer inspection, it appears as though the £ symbol is not rendered correctly from the configuration file. Please find an example below;

**Example Configuration Setup**
`
  "Data": {
    "ConnectionString": "£x4mple!" //Inject this in via the Azure Web App
  }
}`

**Example usage within startup.cs**

```
            string brokenExample = Configuration["Data:ConnectionString"];
            string workingExample = "£x4mple!";
```

**Example output from startup.cs**
brokenExample is outputted as "�x4mple!"
workingExample is outputted as "£x4mple!"

My work around was to use a database administrator password that does not contain the £ symbol, however, it would be great if this could be fixed.

**Comment by svick** [comment]
What is the encoding of the configuration file? It should work if it's UTF-8, but not work otherwise, because [the JSON configuration provider uses the `StreamReader(Stream)` constructor](https://github.com/aspnet/Configuration/blob/b4c6a63/src/Microsoft.Extensions.Configuration.Json/JsonConfigurationFileParser.cs#L24), [which uses the UTF-8 encoding](https://msdn.microsoft.com/en-us/library/yhfzs7at(v=vs.110).aspx#Anchor_2).

**Comment by reddobowen** [comment]
Looks as though the appsettings.json is West European (Windows) - Codepage 1252. Other files appear to be UTF-8.

I haven't made any file encoding changes, so would this have been set by Visual Studio when setting up a new ASP .NET Core Project?

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
