### ISSUE TITLE
Error in MVC Entity Framework scaffolding

### ISSUE THREAD

**Issue by OmegaSyrus** [aspnet/Home#1568]
I'm using the default ASP.NET Core template project.

When adding an "MVC controller with views, using Entity Framework" while using external login (facebook in this case), there's an error in the scaffolding process.

![image](https://cloud.githubusercontent.com/assets/6351493/16033374/7e3fbeea-31c0-11e6-93f5-31f42b2f1384.png)

After generating this, you get

![image](https://cloud.githubusercontent.com/assets/6351493/16033392/9d69cb62-31c0-11e6-8956-1fcc5c35750c.png)

This problem goes away if I delete specifically these lines:

```
        // Add external authentication middleware below. To configure them please see http://go.microsoft.com/fwlink/?LinkID=532715
        app.UseFacebookAuthentication(new FacebookOptions()
        {
            AppId = Configuration["FacebookAppId"],
            AppSecret = Configuration["FacebookAppSecret"]
        });
```

**Comment by wauters** [comment]
I experienced the same issue. When scaffolding the controller, Visual Studio uses the 'production'-environment thus ignoring the AddUserSecrets() method:

`if (env.IsDevelopment())
            {
                builder.AddUserSecrets();
            }`

As of now, I don't know an elegant solution to overcome this.

**Comment by divega** [comment]
@rynowak it looks like a scaffolding issue at first glance.

@prafullbhosale I am not sure but I suspect @wauters comment at https://github.com/aspnet/Home/issues/1568#issuecomment-244605226 might be the key. Is there a way to pass what configuration you want to use for scaffolding? Does scaffolding set anything by default?

**Comment by dotnetnoobie** [comment]
@divega @prafullbhosale @wauters @OmegaSyrus 

I also get this error in VS2017 RTM community edition, ASPNET Core 1.1 app

After a lot of wondering how this suddenly started to happen in projects which would scaffold controller and views with no problem and then suddenly I would start getting this error.  

After many many hours of searching for a solution and a lot of experimentation with controllers and data annotations etc etc...  I found while search google for an answer I found a person who also had the problem and offered a solution.

This persons solution did not solve the issue, but it lead me to realize why in my case the error was occurring.  The offered solution was to use the new controller dialog to make a new controller for the class I wanted to make the controller and views for.  while this did not work, it did offer a different error message which lead me to the answer of why I could no loner auto generate controllers and views.

What I found was in my web application was when I created a "Service" class which used the IMemoryCache in it to cache data I got this error.

For example I have a service class which creates the menu structure for parts of the website menu from information in the database, when I cached the menu structure as it does not change very often using the IMemoryCache in the service class I get the error.

Once I remove the caching of the menu service class I can use the controller dialog to generate Controller and Views again. 

Then I also notice in another service I have which caches news Items even just having the IMemoryCache setup on the service which is not even been used, I just created the news service class I had not even used it, it was just sitting in my project, this also made the above error occur when trying to generate a controller and it's views via the controllers dialog.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
