### ISSUE TITLE
The given key was not present in the dictionary

### ISSUE THREAD

**Issue by dvdobrovolskiy** [aspnet/Home#1572]
After adding an other ordinary Enum to model I had dotnet.exe crush and broken project after. 

Now I cannot restore Packages with error
Severity    Code    Description Project File    Line    Suppression State
Error       The given key was not present in the dictionary.    SwiftCourier.Web    C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Common.Targets  241 

at that line I have 
    <Dnx
      RuntimeExe="$(SDKToolingExe)"
      Condition="'$(_DesignTimeHostBuild)' != 'true'"
      ProjectFolder="$(MSBuildProjectDirectory)"
      Arguments="$(_BuildArguments)"
      />

**Comment by juabara** [comment]
+1

**Comment by teo-mateo** [comment]
I fixed this by running a manual "$> dotnet restore" command in the project folder.

**Comment by davidfowl** [comment]
Need more details. Can you provide the project?

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
