### ISSUE TITLE
Razor generated output is not processed by TagHelpers

### ISSUE THREAD

**Issue by ShadowDancer** [aspnet/Home#1575]
If one tag helper produces some output, let's say href attribute, this attribute is not processed by other tag helpers (no matter what order is set).

For instance let's say I want to make all hrefs absolute. With tag helper I can prepend url with my domain, however it fails if I have
`<a asp-route="default">...</a>`
I guess that's because (in cshtml) it doesn't have href attribute (this is my TagHelper: https://github.com/ShadowDancer/razor-tag-order/blob/master/src/RazorTagOrder/MyTagHelper.cs ).

This is intended behavior? If so any proposed workarounds other than creating tag helper for each exception?

PS. here is example project: https://github.com/ShadowDancer/razor-tag-order

**Comment by dougbu** [comment]
This is intended behaviour. [`MyTagHelper`](https://github.com/ShadowDancer/razor-tag-order/blob/master/src/RazorTagOrder/MyTagHelper.cs) explicitly says (at [line 5](https://github.com/ShadowDancer/razor-tag-order/blob/master/src/RazorTagOrder/MyTagHelper.cs#L5)) that it should only be associated with elements in .cshtml files that have `href` attributes.

Your `Href` property would also be bound to an `href` attribute value in a .cshtml file (if any). Must use `output.Attributes` to determine what HTML will generated or what other tag helpers have added.
