### ISSUE TITLE
Connect to Oracle Database with ASP .Net Core

### ISSUE THREAD

**Issue by somesortofapp** [aspnet/Home#1576]
Back in ASP.NET core RC1, the full .NET 4.5 framework was supported, and I have been using Oracle Managed Client to connect to Oracle Databases.

In RC2, and RTM, the full .NET framework is not supported, and instead only .NET standard is. This means that the Oracle Client is no longer compatible with .NET Core.

Are there any alternative options in connecting to Oracle databases?

**Comment by moozzyk** [comment]
Full .NET Framework is still supported.

**Comment by somesortofapp** [comment]
Oh. For some reason I thought it wasn't. So that mean things like Oracle client will still work?

**Comment by moozzyk** [comment]
I have not tried but if it worked in RC1 it should work in RC2 and RTM. This doc might be useful to you when migrating your application from RC1 to RC2: https://docs.asp.net/en/latest/migration/rc1-to-rc2.html as well as this issue: https://github.com/aspnet/Home/issues/1381. Also the tfm changed - if you had dnx451 you want to use net451,
