### ISSUE TITLE
HttpContext.Session.SetString

### ISSUE THREAD

**Issue by FourLeafClover** [aspnet/Home#1577]
AspNet core rc2
package:  Microsoft.AspNetCore.Session

<pre>
    HttpContext.Session.SetString(key,value)   error.
</pre>

I have  add code in the startUp.cs.

<pre>
        public void ConfigureServices(IServiceCollection services)
        {
            // Add framework services
            services.AddApplicationInsightsTelemetry(Configuration);
            services.AddAuthorization();
            services.AddSession(options =>
            {
                options.IdleTimeout = TimeSpan.FromDays(7);
                options.CookieName = ".FileSystem";
            });
            services.AddMvc();
        }
</pre> 

<pre>
         public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
        {
            #region

            loggerFactory.AddConsole(Configuration.GetSection("Logging"));
            loggerFactory.AddDebug();

            app.UseApplicationInsightsRequestTelemetry();

            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
                app.UseBrowserLink();
            }
            else
            {
                app.UseExceptionHandler("/Home/Error");
            }

            app.UseApplicationInsightsExceptionTelemetry();

            app.UseStaticFiles();

            app.UseMvc(routes =>
            {
                routes.MapRoute(
                    name: "default",
                    template: "{controller=Home}/{action=Index}/{id?}");
            });

            #endregion

            app.UseSession();
        }
    }
</pre>

*\*  Not working. HttpContext.session.setString()  
##      error:   Session has not been configured for this application or request.

I have read some blogs: asp.net core rc1.  
The blogs shows that i should  import the package: aspnet.session. 
but when i import this package,  the package can not support app.UseSession() function.

Help！ how can i use session in aspNet core RC2

**Comment by pranavkm** [comment]
Middlewares get added to the pipeline in the order in which they appear in your code. In this case, `UseSession` appears after `UseMvc`; consequently it isn't set up until after Mvc has executed. Add it at some point before your call to `UseMvc`. https://docs.asp.net/en/latest/fundamentals/middleware.html#creating-a-middleware-pipeline-with-iapplicationbuilder has pretty useful information as to how this works.

**Comment by FourLeafClover** [comment]
@pranavkm Thanks very much.

**Comment by murat1922** [comment]
useless
