### ISSUE TITLE
Web app project.lock.json is ignored and components get downgraded with prejudice

### ISSUE THREAD

**Issue by peterennis** [aspnet/Home#1578]
Redirected from here:

https://connect.microsoft.com/VisualStudio/feedback/details/2699876/web-app-project-lock-json-is-ignored-and-components-get-downgraded-with-prejudice

Rebuild the solution and the problem occurs. The title describes the problem. See attachment to show the result.

Which version of Visual Studio 2015 Update 2 is this?

Visual Studio 2015 Update 2 - 25123.00
Please provide us steps to help us reproduce your issue:

Create getting started web app. Make some change push to github. Make another change, rebuild and the project.lock.json is changed. I understand it is meant to be like a package manifest. Is there some "hidden" option forcing down grades without permission?
What is the impact of this issue?

Not sure. I keep a copy of the project.lock.json file but I am not sure if VS has already messed with the build.
Project is here: https://github.com/peterennisrda/ActiveDirectoryTools/tree/master/src/ADT07.WebADAAL

**Comment by GuardRex** [comment]
@peterennis Your project is a mix of bits among versions of RC1/RC2 approaches. You'll need to checkout conversion docs and Announcements or start over from a fresh RC2 template. I have a list of links that might help: https://github.com/dotnet/cli/issues/2135#issuecomment-212692267 and especially pay attention to the RC2 Announcements and official conversion doc:: https://github.com/aspnet/Announcements/issues?q=is%3Aopen+is%3Aissue+milestone%3A1.0.0-rc2 and https://docs.asp.net/en/latest/migration/rc1-to-rc2.html

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
