### ISSUE TITLE
DataProtection Keys folder doesn't sync on Azure Web Sites distribution slots

### ISSUE THREAD

**Issue by tmm360** [aspnet/Home#1582]
I'm running an Asp.Net Core RC2 application on Azure Web Sites, and I noted that every time that I switch staging and production environments, all users log off. So I've tried to test what happened, and I've discovered that on staging and production's "%HOME%\ASP.NET\DataProtection-Keys" folders the keys were different. Reading this page https://docs.asp.net/en/latest/security/data-protection/configuration/default-settings.html they should be synced.

I supposed that keys may be synced by slot, so when I switch slots the keys should keep under original environment. To test this I've created a new Azure web site with two new empty slots, but when I switch environments the "%HOME%\ASP.NET" folder follows its server. This implies that keys of staging are used under production, and keys of production are used under staging. I've discovered the origin of my issue.

Two options here: I didn't understand how DataProtection is synced between distribution slots, and in this case I'm asking you to tell me how I can solve this problem, or this is a bug and the sentence on documentation is wrong. What do you think? Thank you

**Comment by GuardRex** [comment]
@tmm360 This looks like a good issue (that fell through the cracks). I suggest you re-open this in the docs repo issues at https://github.com/aspnet/Docs/issues and ping [@]blowdart on it.
