### ISSUE TITLE
RC2: Environment Variable being ignored when deployed to IIS, defaulting to Development

### ISSUE THREAD

**Issue by peterorjeff** [aspnet/Home#1585]
### Background
I have recently upgraded my project from RC1 to RC2 and deployed it to IIS 8.5 on Windows Server 2012 R2.
I then went on to test different `appsettings.json` files for Staging and Production by setting the Environment Variable, however this had no effect and the project always default to "Development".

I have searched long and hard for a solution and read every upgrade guide and all the aspnet docs, but have not found a solution. 

I have set all of the following Environment variables to "Staging" (as I know that the name changed):

- ASPNET_ENV
- ASPNET_ENVIRONMENT
- ASPNETCORE_ENV
- ASPNETCORE_ENVIRONMENT

I've confirmed this via the set command, and also by write some test code to check 
`Environment.GetEnvironmentVariable("ASPNETCORE_ENVIRONMENT")`

### Expected Result
`appsetting.staging.json` would be used and that `env.IsDevelopment()` would return false. 

### Actual Result
`appsettings.development.json` is still being used and `env.IsDevelopment()` returns true.

### Further Info
I am including the `builder.AddEnvironmentVariables();` in my `Startup()` method.

When I run locally from Visual Studio and change the environment variable in the Project (ie `launchSettings.json`) it works fine, just not once I've deployed to IIS.

I'm not sure if there's something I'm missing in my deployment procedure, of if this is a bug.
Any help would be greatly appreciated, and please let me know if I need to post any of my code etc.

**Comment by victorhurdugaci** [comment]
Are you setting the environment variable for the correct user? Sometimes IIS runs under a different user account

**Comment by peterorjeff** [comment]
Currently I have User Variables set for my local user, as well as the System Variables.
_Side note: which is correct here, user or system?_

I'm not 100% on what user IIS is running under... 
IIS Manager (InetMgr.exe) is running under my local user.
IIS Manager Service (WMSvc.exe) is running under LOCAL SERVICE.

Within IIS the site is using ApplicationPoolIdentity.
I had to grant access to the "IIS APPPOOL\[SiteName]" virtual account in SQL, for example.

**Comment by moozzyk** [comment]
After you set a system wide env variables you need to iisreset for this change to be effective.

**Comment by peterorjeff** [comment]
@moozzyk Thank you, that solved it!
I had been Restarting IIS via IIS Manager at the Server level, didn't realize this was different to using iisreset.

**Comment by moozzyk** [comment]
@peterorjeff - I learnt it the hard way too...
