### ISSUE TITLE
RC1 to RC2 - Newtonsoft.Json version issue.

### ISSUE THREAD

**Issue by katsuragi545** [aspnet/Home#1586]
I'm currently upgrading an RC1 project to RC2. When building I get the following error:

`C:\Users\user\Documents\cwc_scaffold\project\error CS1705: Assembly 'Microsoft.AspNetCore.Mvc.Formatters.Json' with identity 'Microsoft.AspNetCore.Mvc.Formatters.Json, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' uses 'Newtonsoft.Json, Version=8.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' which has a higher version than referenced assembly 'Newtonsoft.Json' with identity 'Newtonsoft.Json, Version=4.5.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'	`

Prior to upgrading to RC2, I used the JToken method ToObject - it worked perfectly fine but now Visual Studio throws this error: 

`Error	CS0411	The type arguments for method 'JToken.ToObject<T>(JsonSerializer)' cannot be inferred from the usage. Try specifying the type arguments explicitly.`

Does anyone know what I need to do to fix this?

**Comment by davidfowl** [comment]
Do you have a project on github so we can see the problem?

**Comment by katsuragi545** [comment]
Unfortunately I don't - the project is fairly large and contains work code I'm not allowed to post. What can I post other than the project to better illustrate the problem? 

I commented out the JToken.ToObject line and Visual Studio tells me that Json identity issue is in the Microsoft.DotNet.Common.Targets file starting at this chunk:

```
    <Dnx
      RuntimeExe="$(SDKToolingExe)"
      Condition="'$(_DesignTimeHostBuild)' != 'true'"
      ProjectFolder="$(MSBuildProjectDirectory)"
      Arguments="$(_BuildArguments)"
      />
```

**Comment by katsuragi545** [comment]
Also, I have a separate simple Hello World application that uses the exact same project.json and project.json.lock file as the project above, and it runs perfectly fine, so it seems to be related to Visual Studio.

**Comment by katsuragi545** [comment]
The error seems to be related to my Startup.cs file - removing everything in it excluding the main function enables Visual Studio to build it without error (for now, I've removed the JToken.ToObject lines). This is the Startup.cs file:

`using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json.Serialization;
using Microsoft.AspNetCore.Hosting.WindowsServices;
using System.Diagnostics;
using System.IO;
using Serilog;
using System.Linq;

namespace COIN.Monitor
{
    public class Startup
    {

        public static void Main(string[] args)
        {
            var exePath = Process.GetCurrentProcess().MainModule.FileName;
            var directoryPath = Path.GetDirectoryName(exePath);



            if (Debugger.IsAttached || args.Contains("--debug"))
            {
                var host = new WebHostBuilder()
                   .UseKestrel()
                   .UseContentRoot(Directory.GetCurrentDirectory())
                   .UseStartup<Startup>()
                   .Build();
                host.Run();
            }
            else
            {
                var host = new WebHostBuilder()
                    .UseKestrel()
                    .UseContentRoot(directoryPath)
                    .UseStartup<Startup>()
                    .Build();
                host.RunAsService();
            }
        }
        public Startup(IHostingEnvironment env)
        {
            //Setup Logger
            Log.Logger = new LoggerConfiguration()
                .WriteTo.Trace()
                .MinimumLevel.Debug()
                .CreateLogger();
            // Set up configuration sources.
            var builder = new ConfigurationBuilder()
                .SetBasePath(env.ContentRootPath)
                .AddJsonFile("appsettings.json");
            //.AddEnvironmentVariables();
            Configuration = builder.Build();
        }

        public IConfigurationRoot Configuration { get; set; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddMvc().AddJsonOptions(options =>
                  {
                      options.SerializerSettings.ContractResolver =
                          new CamelCasePropertyNamesContractResolver();
                  });
        }



        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory, IApplicationLifetime lifetime)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            else
            {
                app.UseExceptionHandler("/Home/Error");
            }

            app.UseStaticFiles();

            app.UseMvc();

            lifetime.ApplicationStopping.Register(() =>
            {
                Log.Debug("Application Stopping. Do stuff.");
            });
        }
    }
}
`

**Comment by katsuragi545** [comment]
Okay, my ConfigureServices method seems to be throwing the error:

`        public void ConfigureServices(IServiceCollection services)
        {
            services.AddMvc().AddJsonOptions(options =>
            {
                options.SerializerSettings.ContractResolver =
                    new CamelCasePropertyNamesContractResolver();


            });
        }`

Any ideas?

**Comment by davidfowl** [comment]
Not without seeing the project.json or project.lock.json.
