### ISSUE TITLE
dotnet-test-xunit.exe.config contains old assembly bindings

### ISSUE THREAD

**Issue by Tasteful** [aspnet/Home#1589]
In my project I depend on EntityFrameworkCore and upgraded to myget version `1.0.0-rtm` from `1.0.0-rc2`. EntityFrameworkCore depend on `System.Collections.Immutable` and was updated from `1.1.38.0` to `1.2.0.0`. Somehow during the change assembly bindings was updated in `bin\Debug\net461\win7-x64\dotnet-test-xunit.exe.config` as below.
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" culture="neutral" />
        <bindingRedirect oldVersion="8.0.0.0" newVersion="9.0.0.0" />
        <bindingRedirect oldVersion="7.0.0.0" newVersion="9.0.0.0" />
        <bindingRedirect oldVersion="6.0.0.0" newVersion="9.0.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Collections.Immutable" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="1.2.0.0" newVersion="1.1.38.0" />
        <bindingRedirect oldVersion="1.1.37.0" newVersion="1.1.38.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
</configuration>
```

And then when xUnit was executed I got the following exception in tests
```
Could not load file or assembly 'System.Collections.Immutable, Version=1.1.38.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
Could not load file or assembly 'System.Collections.Immutable, Version=1.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
```

All projects was referencing the `1.2.0` version of `System.Collections.Immutable`so the assembly binding is old. 

Was trying to `Build clean` and `Rebuild solution` but the bad `dotnet-test-xunit.exe.config` was still present in output folder, after deleted the file tests runs succeed without exceptions.

**Comment by NTaylorMullen** [comment]
This issue should be in https://github.com/dotnet/cli. More specifically this issue looks to be associated with one I logged [here](https://github.com/dotnet/cli/issues/3415).

**Comment by Tasteful** [comment]
@NTaylorMullen Yes, it seems to be the same. I'm closing this one.
