### ISSUE TITLE
Is it possible to consistently use AssemblyLoadContext to implement dynamic loading plugins on desktop CLR?

### ISSUE THREAD

**Issue by joshua-mng** [aspnet/Home#1591]
Due to incomplete features of EF7, I'm trying to use asp.net core on desktop CLR with EF6. Along the way there is a need to load dynamic plugin assemblies from different folders (or arbitrary locations would be great).

As far as I know, .NET Core loads assemblies into neither context which allows to load assemblies from arbitrary locations. But as mentioned on MSDN, full .net framework (desktop CLR) by default loads assemblies into default context and it only considers assemblies under its probing path.

So under the hood, even if I use AssemblyLoadContext on desktop CLR, does it handle things internally consistently?

I appreciate if anyone had this problem.

Thanks

**Comment by davidfowl** [comment]
If you're using .NET Framework then you're using the regular loading rules (default context, load context, load from context and no context all apply depending on what API you use). .NET Core has an AssemblyLoadContext concept which is pretty different from what's available on .NET Framework and .NET Framework doesn't have support for AssemblyLoadContext.

So if you're using .NET Framework (which is sounds like you are) then keep doing the things you normally do (or were doing before) to load plugin assemblies.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
