### ISSUE TITLE
Asp Net Core RC2 Web API publish IIS

### ISSUE THREAD

**Issue by rcgratillo** [aspnet/Home#1592]
I'm developing a Web API using ASP.NET Core RC2 with full framework (4.5.2). I have published in IIS using AspNetCoreModule but I get a 404 error when I call any method. 
I checked that If I publish the API like "Application" under a WebSite It doesn't work but if I publish it like a "Web Site" it works. I need publish like "application" under a Web Site (port binding 80) for shared port with other applications.
How can I deploy the API in IIS like a application within a WebSite?

Regards

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
