### ISSUE TITLE
Is it possible to use Power-BI-Embedded-report with Asp.net core ?

### ISSUE THREAD

**Issue by Michal7** [aspnet/Home#1593]
Hi All,

Is it possible to use Power-BI-Embedded-report with asp.net core ?

BR
Michal

**Comment by Listbd** [comment]
I just tried and got stuck bringing in Microsoft.PowerBI.Core. Looks like it depends on System.IdentityModel.Tokens.Jwt.

**Comment by Cobalt140** [comment]
does anyone have a fix or know how to get around this issue? if not then i going to create a web api in another web app and call then when i need it. not pretty but the only way i can think of working around this issue.

**Comment by chspeck** [comment]
I struggled also with this task (November 2016). I ended up with two separate web applications. First our asp.net core application with a link to the PowerBi Report which is hosted in a dedicated asp.net web application.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
