### ISSUE TITLE
Exclude files from publishing

### ISSUE THREAD

**Issue by mpazdnikova** [aspnet/Home#1594]
I don't want some of my project files (like pdb files or some of the assemblies) to be copied to publish destination folder. 

In my `project.json` I add something like:
`"publishOptions": {
    "exclude": [
      "**/*.pdb"
    ]
  }`

And then do `dotnet publish` - and these excluded files are still in publish folder. Am I doing something wrong here?

**Comment by GuardRex** [comment]
cc/ @ajaybhargavb

**Comment by ajaybhargavb** [comment]
@mpazdnikova, How are they being included in the first place? `publish` won't include any extra files unless you explicitly include them.

**Comment by davidfowl** [comment]
Well pdbs are auto included and I don't think there's a way to disable them. Better to file this issue on dotnet/cli

**Comment by deathrowe** [comment]
I am seeing this issue as well. I went ahead and created https://github.com/dotnet/cli/issues/4004

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
