### ISSUE TITLE
Selecting a startup class based on conventions; is it still working in RC2??

### ISSUE THREAD

**Issue by Christos2015** [aspnet/Home#1595]
Before I start describing the workflow of what I did and did not do, and before stating that conventions do not work in RC2, I would simply like to ask the question first: 

Do conventions for selecting a startup class still work in RC2?
e.g. selecting "StartupDevelopment" over "Startup" under the Development environment?

**Comment by Tratcher** [comment]
Yes, that's still supported.

**Comment by Christos2015** [comment]
I must be missing something then, as I am not able to get it to work.

I setup a small example to verify this:
> I have two startup classes: "Startup" and "StartupDevelopment".
> The "launchSettings.json" file has the environment set to "Development"
> Nothing is done by the application except print a "hello" message and the "EnvironmentName".

The "Startup" class is always been used, even though there is the  "StartDevelopment" class and the environment is set to "Development".

What I am missing? is there a service I should have included in ConfigureServices? I did not find anything on this in any documentation.

I attach the project structure, the two startup classes, the project.json and lauchSettings.json files.

Please see the attached. 

![startup](https://cloud.githubusercontent.com/assets/16291651/16362103/090a0dd6-3bae-11e6-9baa-7bc2c7bc57d7.PNG)
![projectstructure](https://cloud.githubusercontent.com/assets/16291651/16362106/09193630-3bae-11e6-97ce-722ebed56a4d.PNG)
![project json](https://cloud.githubusercontent.com/assets/16291651/16362104/0910f4de-3bae-11e6-90a0-2d1ce1a054a5.PNG)
![launchsettings json](https://cloud.githubusercontent.com/assets/16291651/16362105/091538e6-3bae-11e6-821a-c4f1db8bdb40.PNG)
![startupdevelopment](https://cloud.githubusercontent.com/assets/16291651/16362107/091b014a-3bae-11e6-8363-3c38245d4441.PNG)

**Comment by Tratcher** [comment]
Do you have `.UseStartup<Startup>()` in Program.Main? If so remove that line, it overrides the detection feature you're trying to use.

**Comment by Christos2015** [comment]
I actually had to replace the startup Type with the assembly name and it work. Thanks

**Comment by tanushreepaul04** [comment]
it seems using only "Microsoft.AspNetCore.Builder" / "Microsoft.AspNetCore.Hosting" classes I will never be able to read environment from launchsettings.json. 
I do not have VS2015, I am running from Visual Studio Code with "dnxcore50". Could anyone suggest how I can code to read environment?

**Comment by Tratcher** [comment]
@troydai ?

**Comment by troydai** [comment]
@tanushreepaul04 to start your application in VS Code with specified environment, you need to update the launch.json. For the launch setting for web, in the "env" section, you can add customized environment variable.
```
        {
            "name": ".NET Core Launch (web)",
            "type": "coreclr",
            "request": "launch",
            "preLaunchTask": "build",
            "program": "${workspaceRoot}/bin/Debug/net451/OpenIdConnect.AzureAdSample.exe",
            "args": [],
            "cwd": "${workspaceRoot}",
            "stopAtEntry": false,
            "launchBrowser": {
                "enabled": true,
                "args": "${auto-detect-url}",
                "windows": {
                    "command": "cmd.exe",
                    "args": "/C start ${auto-detect-url}"
                },
                "osx": {
                    "command": "open"
                },
                "linux": {
                    "command": "xdg-open"
                }
            },
            "env": {
                "ASPNETCORE_ENVIRONMENT": "Development"
            }
        },
```
