### ISSUE TITLE
Best practices for authentication in Web API

### ISSUE THREAD

**Issue by robertsundstrom** [aspnet/Home#1598]
I am writing a Single Page Application (SPA) and I wonder what the best practice are for registering and signing in using Web API. There currently are no controllers for that scenario.

Are there any samples that show how to do it?

**Comment by arthurspa** [comment]
It would be interesting examples that consider using JWT for APIs authentication.

**Comment by robertsundstrom** [comment]
A particular scenario that I am interested in is, as I said, SPA:s, but I would also like to know how to combine it with external providers.

**Comment by blowdart** [comment]
As we don't have an OAuth server or JWT issuance, only JWT inbound middleware yet there only way to do it would be with third parties, such as identity server. And as it's 3rd party it's their best practices that matter, and we won't document that.

**Comment by brockallen** [comment]
Here's the repo for IdentityServer4: https://github.com/IdentityServer/IdentityServer4
And the docs: https://identityserver.github.io/Documentation/docsv2/

**Comment by danroth27** [comment]
You can also use our existing Azure services: https://github.com/azure-samples?utf8=%E2%9C%93&query=core

**Comment by robertsundstrom** [comment]
I found this: https://github.com/openiddict/openiddict-core (which is based on aspnet-contrib/AspNet.Security.OpenIdConnect.Server)

**Comment by xperiandri** [comment]
I use OpenIddict - really cool thing!

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
