### ISSUE TITLE
Announcement link for release of asp.net core 1.0.0 is broken.

### ISSUE THREAD

**Issue by garora** [aspnet/Home#1599]
@danroth27 - The announcement link: [Announcement](https://blogs.msdn.microsoft.com/webdev/2016/06/27/announcing-asp-net-core-1-0/)  is broken with release:[asp.net core 1.0]( https://github.com/aspnet/Home/releases/tag/1.0.0). Could you please provide correct link?

**Comment by imranbaloch** [comment]
I believe its not broken but instead un-published. Wait few minutes and try :)
