### ISSUE TITLE
Can't Visit http://localhost:5000 in Chrome/51.0.2704.106

### ISSUE THREAD

**Issue by yoker** [aspnet/Home#1600]
In chrome 51, I got `ERR_INCOMPLETE_CHUNKED_ENCODING` message. 

There is the last version 1.0.0 rc2.

**Comment by Tratcher** [comment]
That most likely means that an error/exception occurred part way through your response and it had to terminate the connection. Try running your application under the debugger or enabling logging to see what the error is.
