### ISSUE TITLE
Packages that are not compatible with .NET Core App 1.0

### ISSUE THREAD

**Issue by bdh0404** [aspnet/Home#1603]
Microsoft.AspNetCore.Mvc, Microsoft.AspNetCore.Mvc.Razor version 1.0.0 are not compatible with .NET Core App 1.0. RC2 version packages are not having this issue. There could be more incompatible packages maybe.

**Comment by davidfowl** [comment]
They're all compatible, you need to update everything to the RTM release, not just individual packages

**Comment by arlyon** [comment]
Having the same issue. What exactly needs to be updated?

```
Package Microsoft.AspNet.Mvc 5.2.3 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package Microsoft.AspNet.Mvc 5.2.3 supports: net45 (.NETFramework,Version=v4.5)
    Package Microsoft.AspNet.WebPages 3.2.3 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package Microsoft.AspNet.WebPages 3.2.3 supports: net45 (.NETFramework,Version=v4.5)
    Package Microsoft.AspNet.Razor 3.2.3 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package Microsoft.AspNet.Razor 3.2.3 supports: net45 (.NETFramework,Version=v4.5)
    Package Microsoft.Web.Infrastructure 1.0.0 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package Microsoft.Web.Infrastructure 1.0.0 supports: net40 (.NETFramework,Version=v4.0)
    One or more packages are incompatible with .NETCoreApp,Version=v1.0.
```

Thanks in advance.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
