### ISSUE TITLE
WebGrease in netcore

### ISSUE THREAD

**Issue by zenixgrace** [aspnet/Home#1604]
Dear Team,

Is WebGrease wiil be port in netcore at the future release ?

If not, what are is optional way to minify css / js by using code in netcore?
Because I have a scenario to minify js / css that I get from the DB

**Comment by ryanlin1986** [comment]
I think WebGrease is kind of old way to do this, for now days, you should use tools such as gulp to do this.

**Comment by zenixgrace** [comment]
but how can I minify the css /js progamatically in net core?

**Comment by Taritsyn** [comment]
@zenixgrace Use [NUglify](http://github.com/xoofx/NUglify) or [JSMin.NET](https://github.com/Taritsyn/JSMin.NET).

**Comment by zenixgrace** [comment]
@Taritsyn  thanks for the information, for additional information, I found out another way to minify html, xhtml, js, css , xml using  [WebMarkupMin.Core](https://www.nuget.org/packages/WebMarkupMin.Core/)

**Comment by Taritsyn** [comment]
@zenixgrace WebMarkupMin this is my project :-) But for minification of individual JS/CSS files is better to use another tool.

In your case, the more suitable the NUglify, because it's based on the [Microsoft Ajax Minifier](https://ajaxmin.codeplex.com/) (also as the WebGrease).

**Comment by zenixgrace** [comment]
@Taritsyn OMG. I didn't see the Author. :(

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
