### ISSUE TITLE
Make runtime selection available

### ISSUE THREAD

**Issue by sanchobear** [aspnet/Home#1611]
Using APP:NET core 1.0.0 it is not possible to select a runtime in VS2015. Only dotnet.exe has an option for build, but not for run or publish. In VS2015 configuration manager settings are ignored. Even worse: VS2015 Publish command has an disabled combobox saying "inferred runtime".
Please remove inferrence (actually taken from the sequence of environment PATH settings of "C:\Program Files\dotnet\" or "C:\Program Files (x86)\dotnet\" - which ever comes first wins the inferrence race!) and let the user decide for which runtime to devleop, run, debug and publish.

**Comment by moozzyk** [comment]
dotnet is different than dnx. With dotnet you select runtime by selecting the version of Microsoft.NETCore.App in your project.json file. If you have multiple copies of dotnet.exe you can use full path to run a specific copy. The important bit is that dotnet.exe essentially tries to find the runime in the shared/Microsoft.NetCore.App subfolder that matches what your application was build against and run your app using this runtime.

**Comment by sanchobear** [comment]
please provide sample project.json and other settings so that:
- I can build x86 and x64 target from VS2015
- I can debug x86 and x64 target from VS2015
- I can publish x86 and x64 target from VS2015

**Comment by sanchobear** [comment]
Please provide configuration sample that allows for x86 AND x64 
build/debug/publish.



Von:    Pawel Kadluczka <notifications@github.com>
An:     aspnet/Home <Home@noreply.github.com>
Kopie:  sanchobear <bodo.probst@esg.de>, Author 
<author@noreply.github.com>
Datum:  30.06.2016 18:43
Betreff:        Re: [aspnet/Home] Make runtime selection available (#1611)



dotnet is different than dnx. With dotnet you select runtime by selecting 
the version of Microsampl
Reply to this email directly, view it on GitHub, or mute the thread.

_____________________________________________________________________________________________________________________

ESG Elektroniksystem- und Logistik-GmbH
Rechtsform/Legal Form: Gesellschaft mit beschränkter Haftung
Sitz/Registered Office: München
Handelsregister/Commercial Register: Registergericht München, HRB 219422
Vorsitzender des Aufsichtsrats/Chairman of the Supervisory Board: 
Alexander Schemann
Geschäftsführer/CEO: Kai Horten
