### ISSUE TITLE
Unable To Add Reference dll

### ISSUE THREAD

**Issue by dotnetdeveloper786** [aspnet/Home#1612]
when i am trying to add reference dll in Asp.net core web application(.net framework) in 1.0.0 Version it gives me error 

**.Net Core Projects only support Referencing .Net Framework assemblies in this release To Reference other assemblies they need to be included in nuget package and reference that package**
![untitled23](https://cloud.githubusercontent.com/assets/20225008/16487805/978317f8-3eea-11e6-8360-7c3de7994db8.png)

**Comment by lilpug** [comment]
I am also having this issue which is stopping me from being able to migrate and build projects in dotnet core, i don't know which repo it should sit under to be honest.

**Comment by DaleMckeown** [comment]
I am also having this exact same issue in .NET Core.

Surely this isn't by design - losing the ability to have 'private' libraries  (Not in NuGet) in .NET Core is a huge problem.

**Comment by aL3891** [comment]
I think this is one of the reasons they are moving back to msbuild based builds, that's planned for VS.vnext that I think is due by the end of the year.
Having the build system being based on msbuild again will make it easier to implement direct assembly references among a bunch of other stuff (like referencing a native library for example)

You can still have a private nuget package just in a folder somewhere and reference that though, just add the folder(or share) as a package source under options. not ideal but atleast its possible

**Comment by strohhut** [comment]
I think [this issue](https://github.com/aspnet/Tooling/issues/565) shows how it can be done without NuGet, but then Intellisense is missing. I'm hoping for a real fix.

**Comment by lmxin123** [comment]
I am also having this issue

**Comment by PedroBatista** [comment]
If the bug itself is bad, the way it's being handled by Microsoft is pathetic.

Do these people even write real world projects? ( meaning outside MS bubble )

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
