### ISSUE TITLE
question: is possile to add an authorization policy to an area?

### ISSUE THREAD

**Issue by Bartmax** [aspnet/Home#1613]
Instead of having to set [Authorize] in all controllers inside an area, is it possible to configure the whole area in one place ?

**Comment by Tratcher** [comment]
@HaoK @blowdart @rynowak ?

**Comment by rynowak** [comment]
You can do this with a convention :+1: 

Start by implementing `IControllerModelConvention`
Look at each controller's route values for the area
Add a new AuthorizeAttribute to 'filters'
Add convention to `MvcOptions.Conventions` in startup

**Comment by anhphan** [comment]
You also can use authorization filter to archive your purpose: 

1. Create an authorization requirement
```
    public class CustomAuthorizationRequirement : IAuthorizationRequirement
    {
    }
```

1. Create a handler for that requirement
```
public class CustomAuthorizationHandler : AuthorizationHandler<CustomAuthorizationRequirement>
    {
        protected async override Task HandleRequirementAsync(AuthorizationHandlerContext context, CustomAuthorizationRequirement requirement)
        {
            if (context.Resource is AuthorizationFilterContext)
            {
                var ctx = (AuthorizationFilterContext)context.Resource;
                var area = ctx.RouteData.Values["area"] as string;

                // Expected Region
                if (area == "Expected area")
                {
                    if (context.User.Identity.IsAuthenticated)
                    {
                        // In the expected area, only allow pass this requirement
                        // if user is authenticated
                        context.Succeed(requirement);
                    }
                }
                else
                {
                    // Let other region alway pass this requirement
                    context.Succeed(requirement);
                }
            }

            await Task.Yield();
        }
    }
```
1. Register handler in service collection
`services.AddTransient<IAuthorizationHandler, CustomAuthorizationHandler>();`

1. Register AuthorizeFilter based on custom authorization requirement in MVC
```
            services.AddMvc(options =>
            {
                var policy = new AuthorizationPolicyBuilder()
                                .AddRequirements(new CustomAuthorizationRequirement())
                                .Build();

                options.Filters.Add(new AuthorizeFilter(policy));
            })
```

**Comment by Bartmax** [comment]
wow! @rynowak @anhphan ! Thanks! this will help a lot!
very appreciated!

**Comment by Bartmax** [comment]
Do you think a doc that explains Areas is a good place to add this kind of information ? or is better suited for a community blog post ?

**Comment by anhphan** [comment]
I think the docs currently is good for [Authorization](https://docs.asp.net/en/latest/security/authorization/index.html), only the missing section [Authorization Filters](https://docs.asp.net/en/latest/security/authorization/authorization-filters.html) need to complete.

I don't find the docs for convention anywhere and cannot find what we can do with the model (ControllerModel, ActionModel....)

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
