### ISSUE TITLE
New Project - SDK Preview 1

### ISSUE THREAD

**Issue by dazinator** [aspnet/Home#1615]
I have installed `update 3`, when I create a new web application it still creates it targeting RC1 packages and preview1 tooling (preview 1 sdk in global.json).. Where am I going wrong - I was expecting the templates to be updated for RTM?

![image](https://cloud.githubusercontent.com/assets/3176632/16495317/cfdfe46a-3ee4-11e6-9261-fe75b66558f7.png)

**Comment by muratg** [comment]
@dazinator Did you install .NET Core SDK?  Please follow the instructions on https://www.microsoft.com/net/core#windows if you haven't yet.

**Comment by dazinator** [comment]
I have done that:

![image](https://cloud.githubusercontent.com/assets/3176632/16495966/87c56116-3ee7-11e6-91ed-58ade873ed3e.png)

Should I have uninstalled the RC2 one first?

**Comment by muratg** [comment]
Not sure, but I'd try uninstalling the RC2 one, and creating a new project after.

@joeloff any thoughts on this?

**Comment by dazinator** [comment]
I just tried uninstalling the RC2 one, and its asking for the installer.exe which I have no idea where to get: 

![image](https://cloud.githubusercontent.com/assets/3176632/16496166/9bed3c62-3ee8-11e6-8975-77c349787e87.png)

**Comment by joeloff** [comment]
You should be able to find it here: https://download.microsoft.com/download/4/6/1/46116DFF-29F9-4FF8-94BF-F9BE05BE263B/DotNetCore.1.0.0.RC2-VS2015Tools.Preview1.exe

**Comment by dazinator** [comment]
Thanks will give that a go.

**Comment by dazinator** [comment]
After removing RC1, creating a new project yields: 

![image](https://cloud.githubusercontent.com/assets/3176632/16496338/63ee5642-3ee9-11e6-97fe-39cf4d09719a.png)

I will try and uninstall and re-isntall the sdk again.

**Comment by dazinator** [comment]
Attempting to uninstall the 1.0.0 sdk from add remove programs gives the following even though I dont have any installations in progress..

![image](https://cloud.githubusercontent.com/assets/3176632/16496392/92862a98-3ee9-11e6-95c5-21a3910738ed.png)

Will try a machine restart

**Comment by joeloff** [comment]
Did you install Preview 2 at all?

**Comment by dazinator** [comment]
I had preview 1 installed, then I followed the instructions on the dotnet website which installed the VS update 3 (assuming that installed preview 2 tooling?) and the net core 1.0.0 SDK.

Note: Trying to uninstall net core 1.0.0 sdk via add remove programs gives screenshot about, however if I run the installer and do a "Remove" this uninstalls it fine, so i am proceeding to remove everything and start again.

**Comment by dazinator** [comment]
I believe I must have missed this sentence :)

![image](https://cloud.githubusercontent.com/assets/3176632/16496566/866fbe4e-3eea-11e6-9371-d7c92121f522.png)

**Comment by joeloff** [comment]
Preview 2 tooling carries the .NET SDK, but it's not part of VS Update 3. You need to install Update 3 and then the Preview 2 tooling (which will then bring in the .NET SDK as well)

**Comment by dazinator** [comment]
> You need to install Update 3 and then the Preview 2 tooling (which will then bring in the .NET SDK as well)

This is what I did, but not removing RC2 first screwed things up. 

I have now uninstalled RC2, and re-installed dotnet core SDK 1.0.0. 
VS Update 3 has remained installed throughout this process.

I have just started VS and got this which is ominous:

![image](https://cloud.githubusercontent.com/assets/3176632/16496799/b7d81ea8-3eeb-11e6-954d-40c93f963d41.png)


Will proceed to create a new project

**Comment by dazinator** [comment]
and this

![image](https://cloud.githubusercontent.com/assets/3176632/16496816/cf63eb10-3eeb-11e6-9a95-eb7ba2e7d46a.png)

**Comment by dazinator** [comment]
Oh dear this is not looking good:

![image](https://cloud.githubusercontent.com/assets/3176632/16496825/dd84d470-3eeb-11e6-9969-b1b39a200057.png)

**Comment by dazinator** [comment]
VS looks messed up.

How do I re-install / repair update 3? 

![image](https://cloud.githubusercontent.com/assets/3176632/16496889/2c9aaeea-3eec-11e6-964b-91f6797d5379.png)

**Comment by joeloff** [comment]
In Add Remove programs, if you right click on Visual Studio there should be a menu with an option that says "Change"

**Comment by dazinator** [comment]
That yields:

![image](https://cloud.githubusercontent.com/assets/3176632/16496955/84635c94-3eec-11e6-94de-25a5e752e66c.png)

Seriously, are these new installers not finalising the installation properly becuase I keep seeing this and the only installers I am running are dot net core sdk ones.

**Comment by joeloff** [comment]
Open task manager and look for MSIEXEC processes.

If you see two, then something else is definitely running an install, perhaps Windows Update?

If you only one MSIXEXEC that's pretty much idle then it might be the backup copy. Windows typically keeps an idle copy around for about 10 minutes after you've installed something to speed up startup time in case you plan to install something else - just a weird optimization. Eventually that copy will be removed.

**Comment by dazinator** [comment]
@joeloff thanks for the info.

Doing a VS repair didn't fix it. My VS looks like this when I open a project:

![image](https://cloud.githubusercontent.com/assets/3176632/16560514/db7411ca-41eb-11e6-8f22-a215eb08bc66.png)

I'm going to try uninstalling / re-installing these two:

![image](https://cloud.githubusercontent.com/assets/3176632/16560605/66f14038-41ec-11e6-8576-9718f43d0286.png)

**Comment by dazinator** [comment]
Uninstalling both of those has fixed the issue with VS but now obviously I don't have preview2 tooling or asp.net core installed. Will now re-install them and fingers crossed if it works I can close this..

**Comment by dazinator** [comment]
Ok yep - uninstalling and reinstalling those seems to have fixed things.
