### ISSUE TITLE
Notes about my own experience migrating from RC2 to RTM

### ISSUE THREAD

**Issue by Bartmax** [aspnet/Home#1622]
Following the same series of: #1381  :smile: 

There's no much technically to said here, updated the tooling, downloaded the update, opened the project, change some things here and there (global.json/project.json and 2 lines of .cs) and everything worked.

**TL/DR:**
The experience with the product feels pretty solid, specially the runtime. There are some caveats in the tooling, but also some great improvements. It is a great release.

**What's different to RC2?**
Tooling is much more solid, stuff just works, like scaffolding, intellisense, restore, nuget, etc.
There are some issue still, and that's why is still preview, but no blocks and pretty stable. I was able to focus entirely on developing (user code) and not on configure/hacking stuff.

There was a change (or may I say addition) in the frontend optimization strategy that I like/support. I hope to see more work into this and make it available for others platform/languages as a community effort, specially with x-plat capabilities. As I see the scene right now, it's very disperse with no really good solutions. There is a lot that can be improved here (the whole community) and I like that microsoft is trying something else without locking users from other solutions.

runtime works very smooth and feels faster. the framework works as expected and there are extensibility/customization points everywhere! most are done very easily.
The footprint for my standalone web application for Win10 including the runtime is 50Mb (excluding images), that's pretty impressive and it is really easy to switch on and off standalone. :+1: 

the docs get a massive overdone and I'm impressed (good thing) about the quantity and mostly quality of it. I read lots of articles, mostly because find them very enjoyable. :clap: 

One measure I like to use to say that this release is more stable than RC2 is because feedback, problems, errors, issue people have/ask in slack. The day RC2 went out it was a massive and exhausting (yet very rewarding) work to help out people. Today issues are way lower than RC2 and solutions are mostly well known.

**The bad?**
Not much. Compilation is still very, very slow... this had huge negative impact on my productivity. AFAIK compilation is part of the preview tooling bits and I really hope that gets resolved. I hit this on RC2 when InMemory compilation was removed and I expected some improvements on RTM but there were none in compilation time.

The InMemory compilation was the second best feature for me so I really miss that one. (TagHelpers is the best feature, in case you were wondering, and that's rock solid)

Some mainstream packages are compatible already with dotnet core, but not all. Some may take a few days, others looks like more. I can say much, that the ones I'm using are already ported or had a way to make it work (imports, myget feeds, etc).

I tend to have some problems with discoverability on the extending points. The good thing is that I could find every answer i needed by looking at the source code or directly from the team via github issues (it's amazing how much one can learn just because of having the source right there). I also expect to see less of this as more docs and community blog posts will exist and I'm more used to the code.

Kudos to the whole dotnet team, I'm really enjoying this great product! Thanks! and congrats!

This was quite a long journey (I jumped in about beta4 times) that I enjoyed it a lot! 
I might even make a blog post about it :)

**Comment by dazinator** [comment]
I was faced with upgrading a large / modular MVC solution (20 projects), and so wanted to automate as much of the upgrade process (RC1 --> RC2 --> RTM) as possible. If anyone else finds themselves in a similar position, try this tool: https://github.com/dazinator/AspNetSolutionUpgradeTool

**Comment by wpostma** [comment]
Some additional notes for someone who jumped from RC1 to RTM:

* Outside the IDE, the tooling seems quite solid, but inside the IDE, glitches remain.

* Even with the latest update3 and later fixes, I get some strange behaviors in Visual Studio, during updating.

* The best practice I could find for porting was to move classes over one at a time, fix them, and then move classes over.  Once a project has lots of errors and lots of broken project.json dependencies, it's not very much fun to actually try to fix code when trying to move stuff up.

* There were a lot of common search/replace fixes, and I didn't find the experience that hard, once I learned a workable incremental approach (copy C# units of compilation over, one at a time).

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
