### ISSUE TITLE
Exception occur while Registiring a new User in .NetCoreApp 1.0

### ISSUE THREAD

**Issue by HassanSiddique** [aspnet/Home#1623]
### STACK
**OverflowException: Arithmetic operation resulted in an overflow.**

System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)

**Comment by moozzyk** [comment]
/cc @divega 
@HassanSiddique - can you file this in the https://github.com/aspnet/entityframework repo?

**Comment by HassanSiddique** [comment]
Sure, Thnkx for Guiding the exact place

**Comment by divega** [comment]
Actually this seems to be lower level than EF, likely Sql client specific . Please file an issue in http://github.com/dotnet/corefx/ and include the whole stack trace and as many repro details as possible.
