### ISSUE TITLE
Problems installing Dot Net Core 1.0.0 VS 2015 Tools Preview 2

### ISSUE THREAD

**Issue by Xipooo** [aspnet/Home#1626]
Each time I try to install the DotNetCore.1.0.0-VS2015Tools.Preview2.exe package I get an error saying the following:

_Setup Failed One or more issues caused the setup to fail. Please fix the issues and then retry setup. For more information see the log file. Setup has detected that Visual Studio 2015 Update 3 may not be completely installed. Please repair Visual Studio 2015 Update 3, then install this product again._

When I look into the log file, I find the following line which seems to be causing the error during install:

_Condition 'WixBundleInstalled OR NOT(((VS2015CommunityUpdateVersion <> VS2015UpdateVersion) AND (VS2015CommunityExists) AND (VS2015UpdateVersionExists)) OR ((VS2015ProfessionalUpdateVersion <> VS2015UpdateVersion) AND (VS2015ProfessionalExists) AND (VS2015UpdateVersionExists)) OR ((VS2015EnterpriseUpdateVersion <> VS2015UpdateVersion) AND (VS2015EnterpriseExists) AND (VS2015UpdateVersionExists)) OR ((VS2015WebExpressUpdateVersion <> VS2015UpdateVersion) AND (VS2015WebExpressExists) AND (VS2015UpdateVersionExists))) OR (SKIP_VSU_CHECK=1) OR (WixBundleAction=2)' evaluates to false._

A simple repair of Update 3 has not resolved the issue, so I was attempting to resort to an uninstall/reinstall of the update. When going through Control Panel > Programs and Features > View Installed updates to uninstall the update, it jumps right to the "Setup Completed" screen saying that all of the components have been uninstalled without any progress screen. Then when I attempt to run the Update 3 installer it says the Update is already installed.

I then tried using Revo Uninstaller but the same thing happens after cleaning out folders and registry items.

I even tried doing an /uninstall /force on the package but to no avail. It seems something is remaining stuck somewhere that keeps the update registered. Any suggestions?

**Comment by sbobkin** [comment]
You can try manually passing the SKIP_VSU_CHECK to get around that. I had to do it on one of our dev workstations. You can see a bit more info about it here: https://github.com/aspnet/Tooling#release-notes-and-known-issues -- although that's in reference to an older release.

**Comment by ps2goat** [comment]
Passing `SKIP_VSU_CHECK=1` worked for me, at least in bypassing the 'setup failed' message.  I assume the installer will complete successfully, otherwise I'll be back!

**Comment by bspitzer** [comment]
Passing SKIP_VSU_CHECK=1 worked for me as well.

**Comment by barriestewart** [comment]
My error was slightly different in that it would say _"This product requires Visual Studio 2015 Update 3 or later. Please install Visual Studio Update 3 or later, then install this product again."._ . `SKIP_VSU_CHECK=1` also fixed this error.

**Comment by DovydasNavickas** [comment]
Same was here after trying to reinstall the tooling. First installation worked properly, but when uninstalled and tried to install again, got the same error about repairing VS Update 3.
`SKIP_VSU_CHECK=1` helped :+1:

**Comment by lassipoint** [comment]
Step 1. Open Command Prompt
Step 2. Goto the folder path in command prompt where DorNetCore exe is located
for example 'cd D:\Softwares'
Step 3. Run following line in command prompt
'DotNetCore.1.0.0-VS2015Tools.Preview2.exe SKIP_VSU_CHECK=1'
Step 4. You should be able to install DotNetCore now.

Ref: https://docs.microsoft.com/en-us/dotnet/articles/core/windows-prerequisites#issues

**Comment by Lazdinger** [comment]
girl/dude... thank you so much for that!

**Comment by Samved-Thakkar** [comment]
It worked for me.
Step 1: open command prompt
Step 2; go to the folder where you the installer is located (for me it was in my downloads folder)
**E:\downloads\**
Step 3:  copy paste the installer filename with the skip like so;
**DotNetCore.1.0.0-VS2015Tools.Preview2.exe SKIP_VSU_CHECK=1**

This should allow you to download it without any issue.

**Comment by Xipooo** [comment]
Thank you everyone, the SKIP_VSU_CHECK=1 worked for me as well.

**Comment by dandamudi** [comment]
greatfull thanks to everyone, SKIP_VSU_CHECK=1 resolved my issue

**Comment by willaw79** [comment]
This is working for me as well. Thank you very much!

**Comment by ps2goat** [comment]
@Xipooo - should this issue remain open so they can fix the prerequisites check?  We shouldn't be forced to skip the check; it should do the proper check for update 3.

**Comment by jemartin80** [comment]
Thanks, the SKIP_VSU_CHECK=1 worked for me as well. @Xipooo IMO I agree with ps2goat this issue is not resolved, this is a work around. The issue should remain open until the prerequisite check works properly, otherwise why not remove the prerequisite check.

**Comment by jazzdelightsme** [comment]
+1: issue should not be resolved--there needs to be an actual fix.

**Comment by arktronic** [comment]
The latest [release](https://go.microsoft.com/fwlink/?LinkID=824849), named [DotNetCore.1.0.0-VS2015Tools.Preview2.0.1](https://download.microsoft.com/download/2/F/8/2F864C4E-6980-4AFC-B64E-0AC04837FD6C/DotNetCore.1.0.0-VS2015Tools.Preview2.0.1.exe), appears to have fixed the issue.

**Comment by balexandre** [comment]
@arktronic 

nop, I got the same issue as reported, by bypassing the validation with `SKIP_VSU_CHECK=1` still works :)

**Comment by arktronic** [comment]
Odd, I haven't experienced this issue with the new version. If it's still happening, then I agree that the issue should be reopened.

**Comment by LeeDumond** [comment]
Definitely still happening with Preview2.02 as well.

**Comment by federicorinaldi** [comment]
+1 still happening with Preview2.0.2

**Comment by markanthonyoconnor** [comment]
I ran that command from cmd and it opened the install but still failed

**Comment by vitalbsk** [comment]
@LeeChenelerJS thanks
SOLUTIONS:
Issue 1: Not thinking VS 2015 Update was properly installed
I think that something in the update 3 installer was blocked from properly installing because my laptop s security software randomly chooses to lock files in its process... so the "SKIP_VSU_CHECK=1" solution solved that.

Issue 2: Failed to install Microsoft NuGet during Core Tooling installer
The issue here was basically the same. I couldn't manually uninstall Nuget Package manager from within VS because a process was holding onto it. To combat this I had to manually delete its folder from "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions" then rerun the installer.
