### ISSUE TITLE
Embed resource: hyphen in directory name is replaced by underscore 

### ISSUE THREAD

**Issue by anhphan** [aspnet/Home#1628]
Not sure this is a bug or by design, but it happen with directory name but not file name.

I just embed jquery-validation and kendo ui library and see the name of jquery validation directory is "jquery_validation", but the localization file of kendo ui still keep hypen in the filename.

**Comment by BrennanConroy** [comment]
See https://github.com/aspnet/FileSystem/issues/184

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
