### ISSUE TITLE
Localize thread culture mismatch

### ISSUE THREAD

**Issue by sanchobear** [aspnet/Home#1630]
Localizing an Core Framework MVC app using the LanguageActionFilter (via HTTP::GET) I can change the thread cultures in the filter. The controller gets the modified culture and localizing inside the controller using the IStringLocalizer works as expected. However, the .cshtml is still rendered using the previous culture in System.Threading.Thread.CurrentThread.Current(UI)Culture and localizing using IViewLocalizer does not work correctly. Only after refreshing the page the .cshtml is correctly localized.

The Razor engine should use the modified culture, so that localization directly works.

**Comment by pranavkm** [comment]
If you're targeting desktop (`net4x`), you must target `net46` or higher. In addition, changing in the culture either in a middleware of in `IResourceFilter` should fix your issue. See https://github.com/aspnet/Mvc/issues/4692

**Comment by sanchobear** [comment]
net461 is already used. IResourceFilter did the job. Thanks for hint. 
Samples should be impoved ...



Von:    Pranav K <notifications@github.com>
An:     aspnet/Home <Home@noreply.github.com>
Kopie:  sanchobear <bodo.probst@esg.de>, Author 
<author@noreply.github.com>
Datum:  03.07.2016 20:44
Betreff:        Re: [aspnet/Home] Localize thread culture mismatch (#1630)



If you're targeting desktop (net4x), you must target net46 or higher. In 
addition, changing in the culture either in a middleware of in 
IResourceFilter should fix your issue. See aspnet/Mvc#4692
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.

_____________________________________________________________________________________________________________________

ESG Elektroniksystem- und Logistik-GmbH
Rechtsform/Legal Form: Gesellschaft mit beschränkter Haftung
Sitz/Registered Office: München
Handelsregister/Commercial Register: Registergericht München, HRB 219422
Vorsitzender des Aufsichtsrats/Chairman of the Supervisory Board: 
Alexander Schemann
Geschäftsführer/CEO: Kai Horten
