### ISSUE TITLE
UseRuntimeInfoPage()

### ISSUE THREAD

**Issue by dazinator** [aspnet/Home#1632]
Just upgrading an RC1 application to RTM, and I am left with a compile error:

![image](https://cloud.githubusercontent.com/assets/3176632/16567329/42b7d208-4215-11e6-97d3-c63f2972d173.png)

I queried the announcements looking for a breaking change but couldn't find one around UseRuntimeInfoPage() - perhaps I missed it - or perhaps I am making a mistake somewhere?

**Comment by victorhurdugaci** [comment]
It was removed but there was no announcement. Blame @kichalla for [that](https://github.com/aspnet/Diagnostics/commit/af19899927516718bdc05507612dcc17901fb937) :smiling_imp:  

If you still need that middleware you can get the code from the commit mentioned below and create your own version of it.

**Comment by dazinator** [comment]
Ah ok. Thanks - think I'll just remove it for now.
