### ISSUE TITLE
netcoreapp1.0 class library dependency failed. If re-add dependency - ok

### ISSUE THREAD

**Issue by ZOXEXIVO** [aspnet/Home#1633]
I use Console App with Class library (netcoreapp1.0).
It work fine at one PC, but when i go to another PC and pull changes - i catch error, that i can't access class defined in class library. When i clear dependencies (project json handwrite) and add it again - it work.

Steps to reproduce:
1) Create Console Application 

```
"frameworks": {
    "netcoreapp1.0": {
      "imports": "dnxcore50"
    }
  }

```

2) Create Class library with Class1.cs

```
"frameworks": {
    "netstandard1.6": {
      "imports": "dnxcore50"
    }
  }
```

3) Add class library as dependency to console library and use Class1 in Console app.
4) Push it and pull code to another computer. Try to build. It show error message, that Class1 not defined (dependency is alive)
5) Remove deps and add it again - all ok. And when i revert all changes - it work again. Why first build failed ?

I changes netstandard1.6 to netcoreapp1.0 and back and i think, that monikies not changes as expect (may be need reboot VS) ?

It's very nasty bug which makes me think that I'm doing something wrong

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
