### ISSUE TITLE
[Question]publishing with multiple environments

### ISSUE THREAD

**Issue by anobaka** [aspnet/Home#1634]
**Q1:** I published my websites to filesystem and remote IIS servers by vs2015, and I have to change environmentVariable in web.config before publishing my websites to different environment(e.g. Testing, Production), it's error-prone, and I'm also don't want to modify environment in IIS website in remote servers because there are plenty of servers and websites to configure.Is there a way to specify environment when using publish tools of vs2015?
**Q2:** There are 3 appsettings.json files in my project:
- **appsettings.json** //common settings, no diferences between multiple environments, e.g. business config
- **appsettings.testing.json** //specific settings of testing environment, e.g. db configuration of Testing
- **appsettings.production.json** //specific settings of production environment, e.g. db configuration of Production

and I always use 2 of them to configure my website(e.g. (appsettings.json + appsettings.testing.json) or (appsettings.json + appsettings.production.json)), can I combine them and ignore(dispublish) the other one when publishing? 

Thanks

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
