### ISSUE TITLE
net461 console cannot reference netstandard as project reference

### ISSUE THREAD

**Issue by damienbod** [aspnet/Home#1635]
If I have a console .NET app running with .NET 461 (csproj) and reference a netstandard 1.4 class library using the add project reference, the project does not compile.

If I add the same library using NuGet, it works fine.

**Comment by davidfowl** [comment]
Is the class library xproj? If so, that will not work.

**Comment by damienbod** [comment]
Yes, the class library is a xproj. So I need to update the existing csproj to a xproj, if I want to add the class library as a project reference, correct?

Why does it work when referencing the xproj through a NuGet package?

Greetings and thanks Damien

**Comment by bthomsons** [comment]
After updating to the latest version Asp.net +  tools, I was able to reference a standard .net 461 project reference after updating my global.json file with the following:

`{
  "projects": [ "src", "test" ],
  "sdk": {
    "version": "1.0.0-preview2-003121"
  }
}
`

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
