### ISSUE TITLE
Preview 2 - Rebuild issue - projects referencing other projects and multiple build passes

### ISSUE THREAD

**Issue by dazinator** [aspnet/Home#1637]
UPDATE: Doing a `Build` works, issue seems to appear only when doing `Rebuild`..

I have latest preview 2 tooling installed, and RTM 1.0.0.

I am currently hitting the following problem.
I have multiple projects in my solution. My project dependency diagram is non trivial - however I don't have any cyclic dependencies. 
When I delete all of the "bin" folders in my solution, and then do a Rebuild like so:
`"C:\Program Files (x86)\MSBuild\14.0\bin\MSBuild.exe" Gluon.sln /t:Rebuild /p:Configuration=Release`
- I get many of the following errors:

![image](https://cloud.githubusercontent.com/assets/3176632/16594337/daca8bfe-42e1-11e6-9f9a-8dcfe7c53841.png)

Note: I use `MsBuild` to build the solution file, because `dotnet build` can only build manually specified `project.json` files or project.json files that match a globbing pattern. I'd rather build using the solution file to make sure I build explicitly only the projects that are part of my solution.

Particular projects fail to build because referenced projects haven't built yet. This appears to be a timing thing, or things not being built in the correct order.

If I then do another Rebuild, the number of these errors is reduced as it now discovers some of the assemblies produced during the previous Rebuild:

![image](https://cloud.githubusercontent.com/assets/3176632/16594405/2e8fad14-42e2-11e6-98f9-3c9d299ff536.png)

Finally after 3 rebuilds, I get down to 1 error:

![image](https://cloud.githubusercontent.com/assets/3176632/16594546/de057292-42e2-11e6-8c41-fa41c6a3d241.png)

And then 4th Rebuild is success:

![image](https://cloud.githubusercontent.com/assets/3176632/16594655/42781950-42e3-11e6-8ac4-cbf70fd07d02.png)

It will now continue to build fine - unless I delete all of the bin folders again.

This hasn't been too much of a problem on my local development environment as I don't often clear all bin folders. However, I am now setting up a CI build (Team City). Code is checked out and the bin / output folders are cleared so that its in a clean state. When Team City builds it fails due to these errors.

Any ideas what the problem could be?

**Comment by dazinator** [comment]
And here is my project dependency diagram - it isn't trivial I am afraid:

![image](https://cloud.githubusercontent.com/assets/3176632/16618826/4c3a0f48-4383-11e6-9bd6-2acd112a5d27.png)

**Comment by dazinator** [comment]
And here is full MS build output log: https://gist.github.com/dazinator/318b9dbae0bba4b7683f677be7bb973d

**Comment by dazinator** [comment]
Update: Doing a `Build` rather than a `Rebuild` appears to work, i.e this works:  `"C:\Program Files (x86)\MSBuild\14.0\bin\MSBuild.exe" Gluon.sln /t:Build /p:Configuration=Release`

Still leaving this open because prettu sure Rebuild should also work!

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
