### ISSUE TITLE
Migrating to RTM from RC2 frameworkAssemblies not resolving

### ISSUE THREAD

**Issue by ElvisHalil** [aspnet/Home#1638]
My project.json used to look like this, everything was working and I was on RC2:

```
{
  "version": "1.0.0-*",
  "description": "TECH.Translator Console Application",
  "authors": [ "Elvis" ],

  "buildOptions": {
    "emitEntryPoint": true
  },

  "dependencies": {
    "SimpleInjector": "3.1.3",
    "SimpleInjector.Extensions.LifetimeScoping": "3.1.3",
    "TECH.Common": "1.0.0-*",
    "TECH.Repositories": "1.0.0-*"
  },

  "commands": {
    "TECH.Translator": "TECH.Translator"
  },

  "frameworks": {
    "net46": {
      "frameworkAssemblies": {
        "System.Configuration": "4.0.0.0",
        "System.Data": "4.0.0.0",
        "System.Data.DataSetExtensions": "4.0.0.0",
        "System.Xml": "4.0.0.0"
      }
    }
  }
}
```

Now I have migrated all my bits to RTM (VS + SDK), and I've done as suggested for project.json to add the Microsoft.NETCore.App dependency, and then the framework netcoreapp1.0 with the imports.  I don't fully understand how this works which is probably why I'm having issues. 

My new project.json file looks like so:

```
{
  "version": "1.0.0-*",
  "description": "TECH.Translator Console Application",
  "authors": [ "Elvis" ],

  "buildOptions": {
    "emitEntryPoint": true
  },

  "dependencies": {
    "Microsoft.NETCore.App": {
      "version": "1.0.0",
      "type": "platform"
    },
    "SimpleInjector": "3.1.3",
    "SimpleInjector.Extensions.LifetimeScoping": "3.1.3",
    "TECH.Common": "1.0.0-*",
    "TECH.Repositories": "1.0.0-*"
  },

  "commands": {
    "TECH.Translator": "TECH.Translator"
  },

  "frameworks": {
    "netcoreapp1.0": {
      "imports": [
        "dotnet5.6",
        "portable-net46+win8+wpa81"
      ],
      "frameworkAssemblies": {
        "System.Configuration": "4.0.0.0"
      }
    }
  }
}

```

The section with the frameworkAssemblies does not resolve.  System.Configuration 4.0.0.0 could not be resolved.   I'm missing a bunch of others that were included previously:

```
        "System.Configuration": "4.0.0.0",
        "System.Data": "4.0.0.0",
        "System.Data.DataSetExtensions": "4.0.0.0",
        "System.Xml": "4.0.0.0"
```

1. I'd like to know how to properly include these in RTM.  

2. Also my application will be hosted on azure so it does not need to be cross platform.  Did I do the correct changes by adding the netcoreapp1.0 framework reference and also the Microsoft.NetCore.App dependency?  
I did not include those before and it seemed to work.  Again, I do not intend to target a non-Windows server for this.  Can someone please clarify?

Thanks!

**Comment by davidfowl** [comment]
netcoreapp1.0 is the .NET Core Framework, you need to change it back to net46 to make that work. You should also remove the Microsoft.NetCore.App dependency.

**Comment by ElvisHalil** [comment]
Ok, I have done that and it's all working. Basically changed it back to how
it was on the top.

So correct me if I'm wrong here, what I've added is to be used for cross
platform applications aka .Net Core Framework.

Net46 is .Net Framework 4.6 (nothing to do with core?) which can be used
safely for Windows applications.

Is that correct?
