### ISSUE TITLE
BUG, BUG, BUG (?). Azure Deploy From Source: Github -> error with Views on Areas.

### ISSUE THREAD

**Issue by Bartmax** [aspnet/Home#1639]
When publising to an azure website using the azure portal / deploy from source:Github.

All files get in their corresponding folders **except** `Views` inside the `Areas` folder.

trying to hit an Area enpoint result in the following error:
```
An unhandled exception occurred while processing the request.

InvalidOperationException: The view 'Index' was not found. 
The following locations were searched:
/Areas/Admin/Views/Home/Index.cshtml
```

Looking at the filesystem i found the views are in folder: `C:\home\site\repository\src\****\Areas\Admin\Views\` but not in: `d:\home\site\wwwroot\Areas\Admin\Views`

so manually invoking this command fixes the problem:
```
xcopy C:\home\site\repository\src\****\Areas\Admin\Views\ 
           d:\home\site\wwwroot\Areas\Admin\Views /s
```
`project.json`:
   ```
  "publishOptions": {
    "include": [
      "wwwroot",
      "Views",
      "Areas/**/Views",
      "appsettings.json",
      "web.config"
    ]
  },
```

**Comment by ajaybhargavb** [comment]
@Bartmax, I investigated this and looks like there is some issue when this globbing pattern is used. The workaround is to specify the folders individually,

```JSON
"publishOptions": {
    "include": [
      "wwwroot",
      "Views",
      "Areas/Admin/Views",
      "Areas/SomethingElse/Views",
      "appsettings.json",
      "web.config"
    ]
  },
```

Please file an issue in https://github.com/dotnet/cli as the fix will need to go there.

**Comment by Bartmax** [comment]
thanks, opened an issue there!
