### ISSUE TITLE
Cannot change the name of output exe in ASP.net core application

### ISSUE THREAD

**Issue by bthomsons** [aspnet/Home#1641]
If I create a ASP.net core web application called 'Application1' it will produce an exe as it's output called 'Application1.exe'. However, if I want to change the name of that exe, there doesn't seem to be anywhere to do this. 

In the web.config under the aspNetCore element there's a property called processPath which is set to '%LAUNCHER_PATH%'. Where does this value come from? I'm guessing that is where the 'Application1' name is coming from.

**Comment by tsvetomir** [comment]
Have you tried setting `buildOptions.outputName`?

**Comment by bthomsons** [comment]
I have just tried this setting and it changes the output name but then I have to change this all over the place as this doesn't match the '%LAUNCHER_PATH%' which is used in web.config. By default, this and all other config are trying to look for 'Application1.exe'

**Comment by moozzyk** [comment]
web.config does not have too much to do with your project. It is only used by IIS to start your application after you published it. When you publish your app a tool called publish-iis is called and replaces %LAUNCHER_PATH% with the actual application name. Note that publish-iis did not support `outputName` in RC2/preview1 but it works in RTM/preview2. 
I am not sure what is the "all other config" that " are trying to look for 'Application1.exe'" - can you elaborate?

**Comment by bthomsons** [comment]
If I change my application name as @tsvetomir suggested, it will generate the exe with that application name. If I then run the program through 'start new instance' or the run through 'IIS Express' buttons in VS, IIS Express will error with 'Unable to start process.... the system cannot find the file specified' because it is still looking for 'Application1.exe' and not the updated name. 

By 'all other config' I'm referring to any config which I have to change to get the correct application name recognised as I'm not clear why IIS express is still looking for 'Application1.exe'. 

If, as you say, I do a dotnet publish, it will replace the '%LAUNCHER_PATH%' with the updated application name.

**Comment by moozzyk** [comment]
The first thing seems to be a problem with tooling. @BillHiebert - do you support this scenario (i.e. `outputName` for the executable is specified in the project.json - it seems that VS is not using this to replace %LAUNCHER_PATH%`)

For `all other config` - I still don't know what files exactly you have in your mind when you say `o any config which I have to change` but as far as I am aware the only config tooling touches is `web.config` (when you publish your app and when `publish-iis` is configured to run as a `postpublish` script). If you have any other config files you most likely created them manually and configured to be included in your code when creating a configuration. Since these are your config files you need to fix them on your own. 

As a side note - I am not sure if I understand why you want to use `outputName` for an executable - why not just change the project folder to match all your needs and be done with it?. The scenario `outputName` was added for was that it enables creating a NuGet package whose name was different from the dll it included. Currently it is used mostly for tools (e.g. the publish-iis is in the package called `Microsoft.AspNetCore.IISIntegration.Tools` and the name of the dll containing the tool is `dotnet-publish-iis`).

**Comment by bthomsons** [comment]
Thanks @moozzyk that makes sense. By 'all other config' I was referring to anything which I may have to change to get this working but if the '%LAUNCHER_PATH%' variable is replaced correctly for scenarios when you either publish or run through IIS express, then, as you rightly point out, there is no other config.

I ran into this issue because of the way we organise projects in our solution and a quirk of visual studio whereby you cannot add a new project and specify which folder it goes in. I renamed the project and namespaces but this would not rename the exe. 

We could get round this using a publish and run through IIS as the '%LAUNCHER_PATH%' would be replaced but it wouldn't run through IIS Express.

**Comment by Kemyke** [comment]
I am also facing this problem. I would like to rename the assembly with the "outputName" arguments in "buildOptions". Everything works fine but i cannot use the iis express to debug it. I tried to set the LAUNCHER_ARGS env variable manually but i cannot make it work. I got the exception: "An error occurred attempting to determine the process id of which is hosting your application".

Is there a working workaround to debug the application with iis express if the output name is differs from project name?

**Comment by bthomsons** [comment]
Hi @Kemyke we actually went back to using old ASP.net instead of ASP.net core because we were writing this for a production app and we didn't feel it quite ready for us to use. However, we got around the issue by using IIS instead of IIS express. I had to make the following change in our xproj file:

`<Target Name="Publish" AfterTargets="Build">
  <Exec Command="$(WinDir)\system32\inetsrv\appcmd stop apppool &quot;AspNetCore&quot;" IgnoreExitCode="true"></Exec>
  <Exec Command="$(WinDir)\system32\inetsrv\appcmd start apppool &quot;AspNetCore&quot;" IgnoreExitCode="true"></Exec>
  <Exec Command="dotnet publish $(MSBuildProjectDirectory)\project.json -o $(MSBuildProjectDirectory)\PublishedApp" Condition="$(PublishURL) == ''"></Exec>
  <Exec Command="dotnet publish $(MSBuildProjectDirectory)\project.json -o $(PublishURL)" Condition="$(PublishURL) != ''"></Exec>
</Target>`

The first two lines stop and start the app pool ‘AspNetCore’ (which we added as an app pool). The third line is for local builds and would publish to a standard \PublishedApp folder which you would point IIS to and the fourth is for deployments where a publish URL is specified – obviously you want to publish to a specified folder when it's specified.

This meant that when we built the project we didn't have to manually stop the process running the ASP.net core app. It wasn't perfect but at least you could debug by attaching through IIS.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
