### ISSUE TITLE
What the solution to avoid 404 error with angular2 & SPA application & core 1 ?

### ISSUE THREAD

**Issue by ybarbaria** [aspnet/Home#1642]
I try to avoid 404 error when i write url and let angular2 manage the redirection. 

Have you any solution?  

Thx

**Comment by laskoviymishka** [comment]
See _https://github.com/aspnet/JavaScriptServices_ this project. It made for SPA and angular 2

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
