### ISSUE TITLE
Create Chocolatey package for DotNetCore WindowsHostingModule

### ISSUE THREAD

**Issue by dazinator** [aspnet/Home#1644]
Any chance of getting the `WindowsHosting` exe distributed as a chocolatey package? It makes it much easier to provision new IIS servers. Will accept any other package manager also!

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
