### ISSUE TITLE
publish-iis - how to change processPath

### ISSUE THREAD

**Issue by dazinator** [aspnet/Home#1645]
Hello,

I have this in my project.json

```
 "postpublish": [
      "dotnet publish-iis --publish-folder %publish:OutputPath%/wwwroot --framework %publish:FullTargetFramework%"
    ]
```

This output's a web.config in my projects published `wwwroot` directory - with a line that looks like this: 

```
   <aspNetCore processPath=".\Gluon.WebApplication.exe" stdoutLogEnabled="false" stdoutLogFile=".\logs\stdout" />
```

This is because I point the IIS website's root directory at my `wwwroot` directory, which only contains static files, and the web.config to make kestrel work.

The problem is, the value set for the processPath always assumes that the exe is in the same directory (i.e in my case, the wwwroot dir). My .exe is one level back so I want it to be set like this: 

```
 <aspNetCore processPath="..\Gluon.WebApplication.exe" 
```

Note the extra dot.

Are there some args I can pass to `dotnet publish--iis` in order to achieve that? I couldn't see any docs for publish-iis tool anywhere.

Thanks

**Comment by dazinator** [comment]
What would be nicer is if the `publish-iis` tool evaluated where the `--publish-folder` was relative to the `OutputPath` (where the exe is) and populated a correct relative path as the `processPath`

**Comment by moozzyk** [comment]
Kind of what I commented on in this thread: https://github.com/aspnet/Performance/issues/153#issuecomment-227289025

**Comment by GuardRex** [comment]
Yeah ... it's really simple to take @moozzyk's **GREAT** tooling and hack it into an abomination before the :pray: server gods :pray: .... 

https://github.com/GuardRex/GuardRex.AspNetCore.Server.IISIntegration.Tools

 ... takes 15 minutes to make your own. It's avoiding the @moozzyk :skull: death squads :skull: that's the hard part. :smile:

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
