### ISSUE TITLE
oauth2 login through discordapp results in endless loop

### ISSUE THREAD

**Issue by mariocatch** [aspnet/Home#1646]
I have an asp core web app with the following snippet:

```
app.UseOAuthAuthentication(new OAuthOptions
{
    AuthenticationScheme = "Discord Login",
    DisplayName = "Discord Authentication",
    ClientId = Configuration["Authentication:Discord:AppId"],
    ClientSecret = Configuration["Authentication:Discord:AppSecret"],
    CallbackPath = new PathString("/Account/ExternalLoginCallback"),
    AuthorizationEndpoint = "https://discordapp.com/api/oauth2/authorize",
    TokenEndpoint = "https://discordapp.com/api/oauth2/token",
    Scope = { "email" }
});
```

On my profile page of discordapp, I have a redirect uri set as:

`https://localhost:44366/Account/ExternalLoginCallback`

After logging in with the external provider (discord), I'm sent through discord's auth step, redirected to the `/Account/ExternalLoginCallback` action on my app, and then thrown into a resulting 500 http error.

> An unhandled exception occurred while processing the request.

> Exception: The oauth state was missing or invalid.
> MoveNext

> AggregateException: Unhandled remote failure. (The oauth state was missing or invalid.)
> MoveNext

After receiving this, every subsequent time I click on the login with discord button, I am immediately thrown to the error above. Discord is responding with the fact that I am logged in I'm assuming, but ASP thinks I'm not logged in, and errors out. I have to clean my cookies in order to retry the login process.

Edit: Running version 1.0.0 of AspNetCore
Windows 10. Tested in Chrome and IE.

Tested in multiple starter apps as well as my "production" app. Occurs in all of them. Seems to only occur with Discord so far as an oauth provider. Works with Facebook.

**Comment by Tratcher** [comment]
It looks like you're using the wrong CallbackPath. `/Account/ExternalLoginCallback` usually refers to a controller in your application, but CallbackPath applies to an earlier step in the signin flow. We usually set this to something like `/signin-discord` and register `https://localhost:44366/signin-discord` with the identity provider. This endpoint is used to complete the OAuth handshake before redirecting to an application endpoint (e.g. where the initial challenge came from, or where was manually specified in the challenge like `/Account/ExternalLoginCallback`).  See https://github.com/aspnet/Security/blob/dev/samples/SocialSample/Startup.cs#L200
