### ISSUE TITLE
[RTM] postpack not executed 

### ISSUE THREAD

**Issue by dazinator** [aspnet/Home#1647]
In my project,json:

```
"scripts": {   
    "postpack":  "echo hello" 
  },

```

When I do a `dotnet pack` it doesn't seem to execute:

![image](https://cloud.githubusercontent.com/assets/3176632/16650587/dd0660fe-4436-11e6-81ed-1f4633d4ccb2.png)

**Comment by moozzyk** [comment]
I don't think prepack/postpack scripts exist anymore - https://github.com/dotnet/cli/blob/04f40f906dce2678d80fb9787e68de76ee6bf57e/src/Microsoft.DotNet.Cli.Utils/ScriptNames.cs#L10-L13. You could probably create a script yourself which invokes `dotnet pack` and then whatever you want to do after pack finishes.

**Comment by GuardRex** [comment]
I think the only working ones are `precompile`, `postcompile`, `prepublish`, `postpublish` ... that's it.

........ :cry: no `prerestore` for me :cry: .... until perhaps MSBuild/`csproj` hits.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
