### ISSUE TITLE
[RTM] - postpack variables doesn't include configuration

### ISSUE THREAD

**Issue by dazinator** [aspnet/Home#1648]
Many of the scripts in project.json such as `postcompile` don't include `configuration` as a variable which surprises me:

![image](https://cloud.githubusercontent.com/assets/3176632/16651107/c8fa4cb2-4439-11e6-94ad-45585616eae1.png)

My use case, is that I want my script to run a `dotnet pack` after a `Release` build is done. I don't want to do a `dotnet pack` for `debug` builds.

**Comment by moozzyk** [comment]
These variables seem to be all wrong. I think this is the correct list: 
https://github.com/dotnet/cli/blob/rel/1.0.0/src/dotnet/commands/dotnet-compile/ManagedCompiler.cs#L169-L174 https://github.com/dotnet/cli/blob/rel/1.0.0/src/dotnet/commands/dotnet-compile/ManagedCompiler.cs#L205

**Comment by moozzyk** [comment]
I filed an issue for this in the CLI repo: https://github.com/dotnet/cli/issues/3805 so closing this one.
