### ISSUE TITLE
[Preview 2] - Removing project from solution, something keeping access lock 

### ISSUE THREAD

**Issue by dazinator** [aspnet/Home#1649]
Preview 2 tooling.

I open the solution in VS, and add a new project to it. Realising I had giving it a crappy folder name, I remove it from the solution. I then attempt to rename the folder in windows explorer but can't because something is still keeping a lock:

![image](https://cloud.githubusercontent.com/assets/3176632/16652033/9cefb2f0-443f-11e6-884a-1f3130975100.png)

I wouldn't expect things to still be accessed after removing the project from the solution. Having to restart VS just to be able to rename a folder is not a nice experience!

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
