### ISSUE TITLE
[Preview 2] - dotnet cli tools only work from users nuget packages dir

### ISSUE THREAD

**Issue by dazinator** [aspnet/Home#1650]
I have project A and project B in my solution.

Project A is a `tool` similar to: https://github.com/aspnet/IISIntegration with an `output name`:  `dotnet-gluon-tool`

Project B  is an application that uses the tool - I have added a project reference to the tool project, and the `project.json` looks like this:

```

"dependencies": {
 "Gluon.Tool.Build": "1.0.0-*"
},

"tools": {
 "Gluon.Tool.Build": {
      "version": "1.0.0-*",
      "imports": [
        "portable-net45+win8+dnxcore50",
        "portable-net45+win8"
      ]
    }
}

```

Now if I `cd` into Project B's project directory and run `dotnet gluon-tool` I get this:

![image](https://cloud.githubusercontent.com/assets/3176632/16652614/970b4080-4443-11e6-8e3f-75c033538a17.png)

It seems `dotnet cli` only searches the nuget package directory?

**Comment by dazinator** [comment]
Have [raised this](https://github.com/dotnet/cli/issues/3802) in the `dotnet cli` repo instead

**Comment by victorhurdugaci** [comment]
Known issue: https://github.com/dotnet/cli/issues/1215
