### ISSUE TITLE
Unity support (question)

### ISSUE THREAD

**Issue by Legends** [aspnet/Home#1654]
When will ASP.NET Core v1.0 support Unity for DI?

I took a short look at Autofac, but it seems like their demo code for DI is outdated:

In my startup.cs the ConfigureServices method is void.
**DI using Autofac:**

```
public IServiceProvider ConfigureServices(IServiceCollection services)
  {
    // Add services to the collection.
    services.AddMvc();

    // Create the container builder.
    var builder = new ContainerBuilder();

    // Register dependencies, populate the services from
    // the collection, and build the container.
    builder.RegisterType<MyType>().As<IMyType>();
    builder.Populate(services);
    var container = builder.Build();

    // Return the IServiceProvider resolved from the container.
    return container.Resolve<IServiceProvider>();
  }
```

**Comment by davidfowl** [comment]
> When will ASP.NET Core v1.0 support Unity for DI?

That's a question for the unity team. We can see if they plan to add support.

> I took a short look at Autofac, but it seems like their demo code for DI is outdated:

It's been updated since then.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
