### ISSUE TITLE
The link to the CLI docs in the DNX utility page is incorrect

### ISSUE THREAD

**Issue by bobbyalex** [aspnet/Home#1655]
The URL mentioned at [https://github.com/aspnet/Home/wiki/DNX-utility](https://github.com/aspnet/Home/wiki/DNX-utility) for more information on the CLI is incorrect. The correct URL is https://docs.microsoft.com/en-us/dotnet/articles/core/tools/index

**Comment by GuardRex** [comment]
cc/ @blackdwarf

**Comment by moozzyk** [comment]
Updated.
