### ISSUE TITLE
Web brower cannot access ASP.NET Core application which hosted in Azure Cloud Service

### ISSUE THREAD

**Issue by micli** [aspnet/Home#1657]
I created a sample web application which can be found at http://www.github.com/micli/MuscleFellow. I created a Ubuntu 14.04 instance into Azure Cloud Service. And I mapped public endpoint 80 to Ubuntu private endpoint 5000. 
![untitled-0](https://cloud.githubusercontent.com/assets/2059006/16713321/df13d08c-46d6-11e6-8bca-4be2a00153e8.png)
Then I logged in Ubuntu VM and installed .NET Core SDK follow by instructions of dot.net website. After git clone I run dotnet restore and dotnet run to start MuscleFellow web Application. It seems succeeded.
![untitled-1](https://cloud.githubusercontent.com/assets/2059006/16713322/df14203c-46d6-11e6-9d5a-108eca0d753e.png)
Unfortunately, It cannot be access by the Cloud Service domain name http://testaspcore001.chinacloudapp.cn/
Can anybody help on this? Thanks!

**Comment by moozzyk** [comment]
Is it because you are listening on `localhost:5000`? Does it work if you listen on `*:5000`? As a side note - exposing Kestrel directly to the outside world is at this point not recommended (https://github.com/aspnet/KestrelHttpServer/issues/957).

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
