### ISSUE TITLE
Cross platform paths

### ISSUE THREAD

**Issue by nojaf** [aspnet/Home#1658]
What is the best strategy to use file paths in a cross platform way?
I had this on Windows
```csharp
await context.Response.WriteAsync(File.ReadAllText("wwwroot\\index.html"));
```

and the ```\\``` part didn't work on Linux. How do I tackle these kinds of problems?

**Comment by henkmollema** [comment]
Use a forward slash: `"wwwroot/index.html"`.

**Comment by nojaf** [comment]
Works indeed, thanks

**Comment by joeaudette** [comment]
for your code to be cross platform, ie so it can work on windows and linux and mac you should use:

    var filePath = Path.Combine("wwwroot", "index.html)

or

    var filePath = "wwwroot" + Path.DirectorySeparatorChar + "index.html";

    await context.Response.WriteAsync(File.ReadAllText(filePath));

**Comment by nojaf** [comment]
I see, thanks @joeaudette
