### ISSUE TITLE
Odd port issues with IIS Express port

### ISSUE THREAD

**Issue by nitro52** [aspnet/Home#1660]
I'm currently looking at migrating one of our sites to asp.net core. We currently run other sites using a Local IIS installation. I can get the asp.net core project running with the default configuration using http:\\localhost:8081 but our site has issues with CORS because localhost is not a trusted domain. 

In our local iis setup each site points with the web project directly, we setup bindings like https://www.mydomain.com and then in our hose file we ad a loopback for www.mydomain.com to 127.0.0.1

So it seems that Local IIS is no longer supported out of the box in asp.net core. so i'm trying to setup IIS express to use a different port number and a domain similar to the local IIS setup. 

If i go to Project Settings > Debug > and change the Launch URL and App URL to 
http://www.mydomain.com/:8081/ i can no longer start IIS Express. I get the error 

> An error occurred launching IIS Express. Port '80' is in use.

But port 80 isn't being used here? This seems to update lanuchSettings.json to thi
```
{
  "iisSettings": {
    "windowsAuthentication": false,
    "anonymousAuthentication": true,
    "iisExpress": {
      "applicationUrl": "http://www.mydomain.com/:8081/",
      "sslPort": 0
    }
  },
  "profiles": {
    "IIS Express": {
      "commandName": "IISExpress",
      "launchBrowser": true,
      "launchUrl": "http://www.mydomain.com/:8081/",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    },
    "qfxWeb": {
      "commandName": "Project",
      "launchBrowser": true,
      "launchUrl": "http://localhost:5000",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    }
  }
}


```

**Comment by moozzyk** [comment]
Shouldn't the url be: http://www.mydomain.com:8081/ and not  http://www.mydomain.com/:8081/? Because of the extra `/` you are trying to use the default port which is 80.

**Comment by nitro52** [comment]
I managed to get it working but not exactly sure what the problem was. i think there might have been a couple.

1. I think that was a type, i remmember seeing that and fixing it but at the time i don't think it solved the problem or there might of been another issue. 
2. first i had to manually update the bindings in {SolutionDir}\.vs\config\applicationhost.config. I would have thought updating the urls in lanuchSettings.ini would have done this. It seemed to have a couple of variations of attempts. 
3. After lots of digging around i found that you need to make sure Visual Studio is running as administrator, otherwise i was getting some access denied error showing in the express logs.

**Comment by moozzyk** [comment]
Registering non-localhost prefix requires Admin privileges.
