### ISSUE TITLE
Unable to Add Standard non-nuget .Net Framework dll in Asp.Net Core Web Application(.Net Framework)

### ISSUE THREAD

**Issue by dotnetdeveloper786** [aspnet/Home#1661]
I am not able to add standard .net framework  dll in Asp.Net Core Web Application(.Net Framework) by adding reference when i try to add reference dll it gives me error

![untitled23](https://cloud.githubusercontent.com/assets/20225008/16756828/5612d954-4825-11e6-9e4f-405a3352e594.png)

i have tried creating local nuget package and add reference of that package but still not able to add reference

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
