### ISSUE TITLE
return null instead of throwing exception if a class not injected when using [FromServices] or @Inject?

### ISSUE THREAD

**Issue by anobaka** [aspnet/Home#1662]
I'm new here of Dependency Injection, and there is something confusing me about DI.
For example, I want to get location of a user:
![qq 20160712181301](https://cloud.githubusercontent.com/assets/2888789/16763644/52d45d62-485c-11e6-83d1-6ded31d6b3eb.png)
And it throws an exception about '**IIpLocationService** is not registed', but I want the **IIpLocationService** to be optional.

In MVC, **HttpContext.RequestServices** solved my problem and it returns null, but what am I supposed to do when I'm not in MVC? Same thing happened when I use @inject in View.

why can't it just return **null** instead of throwing exception? Maybe something I missed, please help me figuring it out, thanks.

**Comment by bragma** [comment]
Have your tried adding a default null value (i.e. ipLocationService = nul)" value to the method definition?
I have a similar problem with TelemetryClient, which may/may not be registered in Startup.cs depending on configuration. What I do is to set it as default to null. When the controller constructor is called, it assumes the correct value if the class has been registered in DI, else it it set to null.

**Comment by anobaka** [comment]
thanks for your answer, I tried it and it still throws **InvalidOperationException: No service for type '\*\*\*' has been registered.**

**Comment by bragma** [comment]
@anobaka sorry I gave you the wrong info. I was using constructor injection so I didn't need the "FromServices" attribute. I didn't notice you are injecting into a method instead. My mistake.

**Comment by dougbu** [comment]
`[FromServices]` aside from switching to constructor injection, you could use
``` c#
public async Task<IActionResult> GetAddressByIp([FromServices] IEnumerable<IIpLocationService> ipLocationServices)
{
    // stuff
}
```

The `ipLocationServices` collection will be empty if the service isn't registered.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
