### ISSUE TITLE
Should we still add feature requests that would result in breaking changes?

### ISSUE THREAD

**Issue by cwe1ss** [aspnet/Home#1663]
Now that we have a released product, I'm wondering how we should deal with feature requests that would result in breaking changes. Is this something, that's no longer worth writing, because you have the requirement of everything being as backwards-compatible as possible or are you still open to breaking changes e.g. in future major releases? 

Are there some guidelines on when requests with breaking changes would be acceptable? (e.g. only security-related or also feature-related, size of impact, certain projects, etc)

**Comment by Tratcher** [comment]
It's still worth filing issues and describing your scenarios. There may be ways to address them that do not require breaking changes, or where the breaks can be sufficiently mitigated.

That said, if they truly require breaking changes then we will be fare less likely to accept them. @Eilon has some more specific guidelines.

**Comment by davidfowl** [comment]
Feel free to request anything you like. The product team has to figure out the cost. 

> That said, if they truly require breaking changes then we will be fare less likely to accept them. @Eilon has some more specific guidelines.

We'll look at them for later releases like the next minor or major.

**Comment by cwe1ss** [comment]
ok thanks!
