### ISSUE TITLE
Guidance needed on how to publish packages for core to nuget and myget

### ISSUE THREAD

**Issue by govin** [aspnet/Home#1667]
My company internally uses myget to manage .NET 4.0 and .NET 4.5 packages. I would like to get some guidance on how to publish .NET Core 1.0 packages to internal myget as well as how to publish .NET Core 1.0 packages to nuget. Thanks.

**Comment by pranavkm** [comment]
If you have a recent build of nuget.exe (https://dist.nuget.org/index.html), pushing to the MyGet feed should just work. (You need a new enough exe to understand the new target frameworks).

**Comment by govin** [comment]
@pranavkm thanks, can I do this from mac/linux?

**Comment by pranavkm** [comment]
You might be able to use Mono to run the exe. I'm not sure if they have public builds of an xplat nuget.exe available. https://github.com/NuGet/Home would be the place to ask.

**Comment by govin** [comment]
thank you, will ask in that forum.

**Comment by pranavkm** [comment]
The 2.0.0 SDK has support for `dotnet nuget push` which mirrors the behavior of `nuget.exe push`. We've been using this in our builds pretty successfully.
