### ISSUE TITLE
Cannot Create ASP.NET  web project in VS 2015 (NOT CORE)

### ISSUE THREAD

**Issue by allnnde** [aspnet/Home#1669]
![problem](https://cloud.githubusercontent.com/assets/8978118/16853882/d20785b2-49e4-11e6-8751-00a27bd70b39.png)

cuando trato de crear un proyecto asp web ya sea webform o MVC me salta el error.
He hecho lo que decía el en issue #1455  pero sigo sin solucionar el problema

When I try to create the United Nations web Project and ASP web form or MVC sea jumps me the error
I have done what was in the in issue # 1455 but still can not solve the problem

Sorry for my english.

**Comment by amicalrahul** [comment]
I am also facing the same issue. I have installed VS2015 update 2.
I tried to follow the above steps but strangely the below directory is empty
C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\DotNet

Even there is no dnx folder at below path
*:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Web Tools\DNX *

I've run RC1 installation successfully and even repaired it many time. But somehow there is nothing installed in the dotnet folder at C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\DotNet path

@bernharde @olegburov or anyone - Can you please suggest something else to solve this problem.

I even repaired 
VS2015 installation. 
deleted dev.exe.config file
ran devenv /setup in vs2015 command prompt (as administrator)

I guess the root problem is nothing is installed in dotnet folder in programfiles and no dnx folder is created.

Need help urgently.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
