### ISSUE TITLE
How to login with a particular external identity provider bypassing Login.cshtml?

### ISSUE THREAD

**Issue by xperiandri** [aspnet/Home#1670]
With regard to https://github.com/openiddict/openiddict-core/issues/143

How can I specify to ASP.NET infrastructure that I want to use particular identity provider and navigate directly to it's page but not a `Login.cshtml` first?
I want to send such a request. How to creates it?
Could you provide a sample code?

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
