### ISSUE TITLE
Unable to connect to web server 'IIS Express' when domain name specified

### ISSUE THREAD

**Issue by xperiandri** [aspnet/Home#1671]
After I entered `http://api.plamobi.com:3497/` instead of `http://localhost:3497/` into `App URL` field in project properties, I get Unable to connect to web server 'IIS Express'

**Comment by xperiandri** [comment]
Resolved by using the workaround from http://stackoverflow.com/questions/35675747/asp-net-5-mvc-unable-to-connect-to-web-server-iis-express/36801686

But it is weird, error is absolutely non informative.

**Comment by gyousefi** [comment]
I resolve this problem by changing port number of my ASP.Net Core app to something else in: 
Properties page of the project and in Debug tab in App URL: section I changed the conflicted port number to a free port number bigger than 1024 and something other than the current one!
http://overengineer.net/fixing-unable-to-connect-to-web-server-iis-express

**Comment by timothycoutlakis** [comment]
How do you connect to an IP address?

**Comment by xperiandri** [comment]
Yes, that works.
Now I run Visual Studio from admin so that it launch IIS Express from admin and it could bind IP or domain.

**Comment by xperiandri** [comment]
But Visual Studio behavior is very contra intuitive

**Comment by Tratcher** [comment]
@bill

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.

**Comment by xperiandri** [comment]
So was error message updated to more clear?

**Comment by lextm** [comment]
@xperiandri Visual Studio is smarter now (VS2017 15.7 Preview 2 at least) to force update `applicationHost.config` whenever `launchSettings.json` is changed. That should remedy most errors caused by their out-of-sync.

**Comment by CharlesOkwuagwu** [comment]
@lextm 

> Visual Studio is smarter now

No, no it is not. I'm using VS2019 ... and this problem still persists in 2019

**Comment by xperiandri** [comment]
I confirm about 2019

**Comment by tebeco** [comment]
@Tratcher any news on why it happen again ?
It is not working for both `IIS Express` AND `Console`

i tried to :
* `dotnet dev-certs http --clean`
* `dotnet dev-certs http --trust`
* delete `.vs/`
* change `launchSettings.json` to anything else
* removed `UseHttpsRedirection()`
* removed `UseHsts()`
* not working for IP / dns in the browser

Also i do not a new behavior is vs2019 when running chrome

![image](https://user-images.githubusercontent.com/2266487/55289271-a517b300-53c4-11e9-9109-0a16b1c2549e.png)

i beleive it has something to do with the way chrome is ran to be able to debug Front stuff, it was not doing that "previously" (can't really define that)

pretty sure all i did was update Vs2019, it was workign 2 weeks ago on the same SDK 
```
>dotnet --version
3.0.100-preview3-010431
```

```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="3.0.0-preview3-19153-02" />
  </ItemGroup>

</Project>
```

**Comment by Tratcher** [comment]
Comments on closed issues are not tracked, please open a new issue with the details for your scenario.
