### ISSUE TITLE
The directory name D:\home\site\wwwroot\Areas\Application\App\ is invalid on azure

### ISSUE THREAD

**Issue by bastienJS** [aspnet/Home#1673]
I am deploying a asp.net core website to azure.

After the deployment I get an 500 internal server error. 

In my kudu console i see this in the log files:
```
Application startup exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ArgumentException: The directory name D:\home\site\wwwroot\Areas\Application\App\ is invalid.
   at System.IO.FileSystemWatcher..ctor(String path, String filter)
```

In my Middleware I setup a directory to serve as the wwwroot for a SPA just designed for a MVC area.

```
   const string areaName = nameof(TGB.Web.Areas.Application);
            app.UseStaticFiles();
            app.UseStaticFiles(new StaticFileOptions
            {
                FileProvider =
                    new PhysicalFileProvider(Path.Combine(Directory.GetCurrentDirectory(), "Areas", areaName, "App")),
                RequestPath = new PathString($"/{areaName}") // when the url /Application is hit the SPA is served.
            });
```

When the /Application url is hit the SPA is served to the client via:

```
 [Authorize]
    [Area(nameof(TGB.Web.Areas.Application))]
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            string content = System.IO.File.ReadAllText("Areas/Application/App/Index.html");
            return base.Content(content, new MediaTypeHeaderValue("text/html"));
        }
    }
```

What is wrong with the application path? 

Is it the trailing slash?

Or is it a general problem with the .NET FileWatcher? => 

https://github.com/tomlokhorst/CoffeeSharp/issues/1

https://www.google.de/search?q=system.ArgumentException%3A+The+directory+name+is+invalid.+at+FileSystemWatcher+azure&oq=system.ArgumentException%3A+The+directory+name+is+invalid.+at+FileSystemWatcher+azure&aqs=chrome..69i57.30133j0j7&sourceid=chrome&ie=UTF-8#q=system.ArgumentException:+The+directory+name+is+invalid.+at+FileSystemWatcher

**If this is not the correct place to post this bug, please let me know where I should post this instead, thanks!**

**Comment by moozzyk** [comment]
I wonder if this can be this: https://github.com/dotnet/cli/issues/3795 ?

**Comment by bastienJS** [comment]
I just checked with azure kudu console what is deployed:

There is no Areas folder at all...

![image](https://cloud.githubusercontent.com/assets/5945955/16893849/cad00952-4b44-11e6-81a5-2934b603e52d.png)

**Comment by bastienJS** [comment]
I closed this issue because it was my error:

In the project.json default value for publish include is:

  "Areas/**/Views",

 I had to do this:

 "Areas",

because I have no default mvc structure in my areas, that means no views under my controllers as I serve a SPA means index.**html**.
