### ISSUE TITLE
Stream Request.Body is corrupted in Docker for Windows environment

### ISSUE THREAD

**Issue by kaatula** [aspnet/Home#1678]
I have a following code snippet in my ASP.NET Core Controller :
```c#
public IActionResult PostAction() {
    string result;
    using (var sr = new StreamReader(Request.Body)) {
        result = sr.ReadToEnd();
    }
    ...
}
```
In works just fine on stand-alone Kestrel on Win, Linux and docker under Linux (Ubuntu 14.04)

But the stream is somehow corrupted in Docker for Windows environment.
Sometimes there are redundant bytes/chars in the end of the stream
Sometime the stream is corrupted, somewhere about position 4096
I have not idea what it means, that is just my observation :)

There is a repo with simple sample demonstrating the problem
https://github.com/kaatula/aspnetcore-docker/releases/tag/0.1
You also pull my docker image and try it:

```powershell
docker run -p 5001:5001 -t kaatula/aspnetcore-docker:v0.1
```

My docker image is based on [latest preview2-sdk](https://github.com/dotnet/dotnet-docker/blob/master/1.0.0-preview2/debian/Dockerfile)

In my sample i POST some data to my controller action (about 20kb) and just send in back;
on the client side I verify that received data is not corrupted.
![image](https://cloud.githubusercontent.com/assets/939396/16952801/7589576e-4dd3-11e6-8246-7a66e5149619.png)

I also write to console the received string

**Comment by davidfowl** [comment]
You shouldn't be disposing the response body in your controller action (I'm not sure if that's the problem but it's incorrect anyways)

**Comment by kaatula** [comment]
@davidfowl thank you for pointing that out, I misread that this [overload](https://msdn.microsoft.com/en-us/library/system.io.streamreader.dispose(v=vs.110).aspx) closed underlying stream too
Unfortunately, it's still makes no difference...

**Comment by kaatula** [comment]
I have just found that things are a way worse than I thought.

Regular MVC Action parameter convertion fails too, in exactly the same way.

```c#
        public IActionResult PostActionWithParameter(string data) {
            Console.WriteLine(data);
            return Content(data);
        }
```

```javascript
function postWithParam() {
    var numberString = "",
        numbers = [],
        i;
    for (i = 0; i < 20000; i++) {
        numbers.push(i % 10);
    }


    $.post("/Home/PostActionWithParameter/", {
        data: numbers.join("")
    }).then(function success(result) {
        var i;
        var checkResult = "OK";
        for (i = 0; i < result.length; i++) {
            var digit = i % 10;
            if (result[i] !== digit.toString()) {
                checkResult = "Failed!!!!";
            }
        }

        alert(checkResult + "\n" + result);
    })
}
```

When data is more than 4K - data string is not correct.

Again, it happens in Docker for Windows only, base image ```microsoft/dotnet:1.0.0-preview2-sdk``` (I have not tried other base images yet, only official one)


Updated repo:
https://github.com/kaatula/aspnetcore-docker/releases/tag/0.2

Updated docker image:
```powershell
docker run -p 5001:5001 -t kaatula/aspnetcore-docker:v0.2
```

**Comment by mikeharder** [comment]
@kaatula: Thanks for reporting this issue.  We are able to reproduce and will investigate the root cause.

**Comment by tsv2013** [comment]
+1

**Comment by mikeharder** [comment]
We are continuing to investigate the issue with Docker for Windows Beta.  In our testing, this issue does not reproduce with [Docker Toolbox](https://www.docker.com/products/docker-toolbox), so you could use Docker Toolbox as a workaround for now.

**Comment by friism** [comment]
Hi, I work at Docker. We suspect that this is a bug in Docker for Windows and are investigating. I'll keep you posted on this issue.

Thanks for reporting!

**Comment by friism** [comment]
Also, using `docker` hostname (instead of `localhost`) will work as a temporary workaround - that hostname will be deprecated very soon though.

Relatedly, we've found the bug and a fix should be in the next release of Docker for Windows this out this week.

**Comment by friism** [comment]
This has been fixed in the latest beta and stable releases: https://blog.docker.com/2016/07/docker-for-mac-and-windows-production-ready/

Thanks again for reporting!

**Comment by kaatula** [comment]
Thank you, fix works just fine for me
