### ISSUE TITLE
Inserting on Table has Trigger

### ISSUE THREAD

**Issue by KerolosMalak** [aspnet/Home#1679]
I am working on ASP.NET Core app with
1- Asp.Net 5
2- EF 7 
3- .Net FrameWork 4.6 
when i insert on table and this table has triggers ,SQL reports the following error " **The target table of the DML statement cannot have any enabled triggers if the statement contains an OUTPUT clause without INTO clause** "
what is the workaround for this issue?

**Comment by simonmurdock** [comment]
http://stackoverflow.com/questions/13198476/cannot-use-update-with-output-clause-when-a-trigger-is-on-the-table

**Comment by KerolosMalak** [comment]
@simonmurdock  
sql statement generated automatically by entity framework 7 , i can't control on it .
and i can't find where this statment generated

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
