### ISSUE TITLE
Failed to start ASP.Net Core application from VS when custom output name is used

### ISSUE THREAD

**Issue by joperezr** [aspnet/Home#1680]
Following issue originally logged by @maxim-boligatov on dotnet/buildtools#886 and now redirected to this repo:

I am not sure if it is correct place for this issue. But I have not found more appropriate place. 
## Steps to reproduce
1. Create ASP.Net Core  web application (.Net Framework) with name Web.Site in VS
2. Use outputName property in buildOptions to specify custom name of assembly (for example "outputName": "MyCompany.Web.Site").
3. Try to start application from VS or try to run debug.
## Expected  behavior

Started application....
## Actual behavior

In case of Start without debugging: HTTP Error 502.5 - Process Failure 
In case of Start with debugging: window with message "Unable to start process [Name]. Process creation failed with the error: The system cannot find the file specified."
## Environment data

`dotnet --info` output:

.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64

So it looks that the image for execution is not found.

**Comment by joperezr** [comment]
FYI @maxim-boligatov

**Comment by maxim-boligatov** [comment]
It looks like other frameworks depend on it as well: https://github.com/xunit/xunit/issues/922

**Comment by vandrham** [comment]
You can workaround this issue by creating an alternative build configuration in Visual Studio and then use an alternative outputName in your project.json:

...

"buildOptions": {
    "debugType": "portable",
    "emitEntryPoint": true,
    "outputName": "MyNiceAssemblyName"
  },
"configurations": {
    "VSDebug": {
      "buildOptions": {
        "outputName": "name_of_project_folder"
      }
    }

**Comment by mattmorg55** [comment]
I'm pretty sure I just got an update for VS 2015 that broke this again. It was honoring the outputName setting in project.json, but trying to run locally today from VS, it assumes that project folder name is the same as the assembly name.
[VersionInfo.txt](https://github.com/aspnet/Home/files/720226/VersionInfo.txt)

**Comment by rjamesnw** [comment]
I don't know if this is related, but when I downloaded a 3rd party source, where the sub folder was "src", then reference it from my project, even thought I added 'buildOptions.outputName' for a different DLL name, it still shows as "src" under the references list of my project, which is not correct (but the DLL in my project's 'bin' folder is named correctly).  The reference in my project is not respecting the .json setting for the downloaded 3rd-party project, and pulling the name from the folder, and not the assemblies actual name specified in project.json - which I can only assume is a bug.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
