### ISSUE TITLE
Utilizing the Executable option in launchSettings.json

### ISSUE THREAD

**Issue by developer1998** [aspnet/Home#1681]
Thanks for the RTM. I am curious how to get the Executable option going in launchSettings.json.
Can you post a sample JSON, so I can edit, and try it on my end. Thank you

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
