### ISSUE TITLE
Using sub directory at launch url

### ISSUE THREAD

**Issue by techcap** [aspnet/Home#1682]
I used launch url like this in launchSettings.json.

```
      "launchUrl": "http://localhost:5000/ns",
```

When I  launch using kestrel, it says "the webpage cannot be found".

After changing MapRoute template like this, it works properly.

```
            app.UseMvc(routes =>
            {
                routes.MapRoute(
                    name: "default",
                    template: "ns/{controller=Home}/{action=Index}/{id?}");
            });
```

**Is it by design?**
**Is it any better idea avoiding using static string "ns/" in template?**

When I use iis express, it becomes worse.

After changing applicationUrl for iisexpress like this and modifying MapRoute template, it works properly.

```
    "iisExpress": {
      "applicationUrl": "http://localhost:1495/ns/",
      "sslPort": 0
    }
```

But iis express works on root "/" not "/ns".

I changed applicationHost.config in .vs/config application path "/" to "/ns" like this.

```
            <site name="WebApplication32" id="2">
                <application path="/ns" applicationPool="Clr4IntegratedAppPool">
                    <virtualDirectory path="/" physicalPath="d:\work\WebApplication32\src\WebApplication32" />
                </application>
                <bindings>
                    <binding protocol="http" bindingInformation="*:1495:localhost" />
                </bindings>
            </site>
```

After modifying the applicationHost.config, VS debugger shows the message box, "Unable to start process".

**Is there any method that running web in sub directory using iis express?**

**Comment by Tratcher** [comment]
The launchUrl is just where to open the browser, it does not directly configure the server. You can configure Kestrel to listen on http://localhost:5000/ns by setting the environment variable ASPNETCORE_URLS=http://localhost:5000/ns in launch settings. Then you can remove the routing change.

For IIS Express, have you tried launching it without the debugger? (ctl+f5)

**Comment by Tratcher** [comment]
@BillHiebert is this another scenario where the DEBUG request fails?

**Comment by techcap** [comment]
@Tratcher In the case of Kestrel, as followed your comment, it worked well. Thanks.
In the case of IIS Express, VS forced to set root virtual directory to the project which I want to use.

This is the reproducing steps.

I want to launch the web site http://localhost:9322/ns.
I modified launchSettings.json like below

```
{
  "iisSettings": {
    "windowsAuthentication": false,
    "anonymousAuthentication": true,
    "iisExpress": {
      "applicationUrl": "http://localhost:9322/ns",
      "sslPort": 0
    }
  },
  "profiles": {
    "IIS Express": {
      "commandName": "IISExpress",
      "launchBrowser": true,
      "launchUrl": "http://localhost:9322/ns",
      "environmentVariables": {
        "ASPNETCORE_URLS": "http://localhost:9322/ns",
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    },
    "NS.WebServer": {
      "commandName": "Project",
      "launchBrowser": true,
      "launchUrl": "http://localhost:9322/ns",
      "environmentVariables": {
        "ASPNETCORE_URLS": "http://localhost:9322/ns",
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    }
  }
}
```
If there's no root '/' virtual directory in applicationhost.config, iis express doesn't work with F5.
```
      <site name="NS.Web.ConfigurationManager-Site" id="4">
        <application path="/" applicationPool="Clr4IntegratedAppPool">
          <virtualDirectory path="/NSClient" physicalPath="C:\work\NS\NS" />
        </application>
        <application path="/ns" applicationPool="Clr4IntegratedAppPool">
          <virtualDirectory path="/" physicalPath="C:\work\NS\NS\NS.WebServer" />
        </application>
```
If I add one line about root '/' virtual directory, IIS Express works with F5.
```
      <site name="NS.Web.ConfigurationManager-Site" id="4">
        <application path="/" applicationPool="Clr4IntegratedAppPool">
          **<virtualDirectory path="/" physicalPath="C:\work\NS\NS" />**
          <virtualDirectory path="/NSClient" physicalPath="C:\work\NS\NS" />
        </application>
        <application path="/ns" applicationPool="Clr4IntegratedAppPool">
          <virtualDirectory path="/" physicalPath="C:\work\NS\NS\NS.WebServer" />
        </application>
```
But when I reopen VS and press F5, VS changed root virtual directory's physicalPath to "/ns"'s physicalPath like below
```
      <site name="NS.Web.ConfigurationManager-Site" id="4">
        <application path="/" applicationPool="Clr4IntegratedAppPool">
          <virtualDirectory path="/" physicalPath="**C:\work\NS\NS\NS.WebServer**" />
          <virtualDirectory path="/NSClient" physicalPath="C:\work\NS\NS" />
        </application>
        <application path="/ns" applicationPool="Clr4IntegratedAppPool">
          <virtualDirectory path="/" physicalPath="C:\work\NS\NS\NS.WebServer" />
        </application>
```

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
