### ISSUE TITLE
AmbiguousActionException for different return type of two action method

### ISSUE THREAD

**Issue by DevStarSJ** [aspnet/Home#1683]
One Controller have two [HttpGet] action mothods.
[HttpGet]
public IEnumerable<Entity> Get() { ... }

[HttpGet]
public Entity Get(int id) { ... }

It works on ASP.NET. but, In ASP.NET Core throws AmbiguousActionException.

I asked this problem in stackoverflow, and find one answer.

He said use [RouteParameterConstraint("id", RouteKeyHandling.DenyKey)] and [RouteParameterConstraint("id", RouteKeyHandling.CatchAll)].

But I can't find RouteParameterConstraint  in .net core.

How I can use two action method, without change route ?

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
