### ISSUE TITLE
1.1.0 Planning

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/Home#1685]
High level plans for the next minor update.
- Azure App Service integration
  - `WebHostBuilder.UseAzureAppService()`
    - Logging provider (aspnet/Logging#466)
    - Key Vault configuration provider (aspnet/Configuration#487)
    - Auto-enable IIS integration
  - Blob storage DataProtection key storage provider (aspnet/DataProtection#92)
  - B2C integration (Identity & Authn/z)
  - Kudu publish time improvements
- WebListener server (for Service Fabric & public-facing ready self-host without reverse proxy and Windows 10 IoT/UWP support)
- Startup time improvements
  - MVC startup time
  - MVC view pre-compilation
  - DI startup time (aspnet/DependencyInjection#372)
  - Reduction of JIT cost from startup via multi-core JIT and/or first-class CrossGen story
- Runtime performance
  - Improving all TechEmpower scenarios (beyond Plaintext)
  - Standard middleware overhead improvements
    - Security middleware
    - Buffering middleware
    - Static files middleware
- Dev experience improvements
  - Meta-packages & publish trimming (reduce dependencies version burden)
  - Improve developer experience compile & startup time
  - Templates improvement (dotnet new, etc.)
  - Improve Razor tooling design, e.g. not require a build to get Tag Helper IntelliSense to work
- Re-enabling missing features & scenarios
  - Dependency Injection adjustments for better alignment with 3rd party DI containers
  - SignalR for ASP.NET Core (may target a preview in 1.1 timeframe)
  - Page-based development model on MVC (aspnet/mvc#494)
  - MVC view pre-compilation
  - MVC View Component Tag Helpers
  - Response caching middleware (aspnet/ResponseCaching#10)
  - WebSockets middleware
  - URL rewriting middleware (with mod_rewrite & URL Rewrite import) (aspnet/BasicMiddleware#43)
- .NET Standard 2.0 alignment
- DataProtection key ring storage provider (e.g. Redis) (aspnet/DataProtection#169)

**Comment by GuardRex** [comment]
@DamianEdwards Will you consider taking one off of "Future" and giving it some kind of reasonable milestone? ... "Future" is probably the "Black Hole" milestone. :smile:

[Access to Service Control Manager / System.ServiceProcess.ServiceController](https://github.com/dotnet/corefx/issues/6024)

I need `ServiceBase` ported to Core to create a Windows Services app for Nano Server. Unless I get other/better guidance, I'm implementing my app as a GPO startup script hooking ...
```c#
[DllImport("Kernel32")]
private static extern bool SetConsoleCtrlHandler(EventHandler handler, bool add);
```
... which may work but is kind'a blah yuckola.

**Comment by i3arnon** [comment]
@GuardRex Your issue sounds like a .NET Core request and not an ASP.NET Core one and these plans seem to be ASP.NET specific.

**Comment by GuardRex** [comment]
Yes, it's CoreFX, but they won't answer. I'll withdraw the request for information here; however, I asked @DamianEdwards on the Standup if he would check on it, and he said he would ask since they won't respond on that issue.

**Comment by ikourfaln** [comment]
Thank you for infos.
What about EntityFramework 1.1.0 planning ?

**Comment by rowanmiller** [comment]
@ikourfaln take a look at https://blogs.msdn.microsoft.com/dotnet/2016/07/29/entity-framework-core-1-1-plans/

**Comment by ikourfaln** [comment]
@rowanmiller thank you for sharing

**Comment by tomkuijsten** [comment]
I'm really curious about the 

> WebListener server ... **Windows 10 IoT**/UWP support

Is there more info to share about this topic?

**Comment by muratg** [comment]
@tomkuijsten any particular question? It's currently preview. We're working on releasing an RTM version. This is a Windows-only web server that sits on top of http.sys.

**Comment by tomkuijsten** [comment]
@muratg well I'm working on a custom webserver for our [win10iot project](https://github.com/tomkuijsten/restup). But it feels like wasted time if you will support these kind of features out of the box any time soon.

**Comment by muratg** [comment]
@tomkuijsten Feel free to check out dev builds (https://dotnet.myget.org/feed/aspnetcore-dev/package/nuget/Microsoft.AspNetCore.Server.WebListener). Related repo will hopefully be OSS soon too.

**Comment by tomkuijsten** [comment]
Thanks @muratg

**Comment by Ponant** [comment]
Hi @DamianEdwards @rowanmiller , thanks a lot for providing more info; Would you include a refreshed Azure Mobile .NET Server SDK for the next release? I am currently building a .Net Core app but had to include the full .Net in order to communicate with the mobile SDK, and the code gets convoluted when mixing up EF Core and EF with ASP.NET Identity Core on top.

**Comment by muratg** [comment]
https://github.com/aspnet/Home/issues/1776

**Comment by Genae** [comment]
I really like where ASP.NET Core is going.
will
> SignalR for ASP.NET Core

include the SignalR Client as well as the server?

**Comment by Eilon** [comment]
@Genae we started work on updating SignalR, but it's not in 1.1.0.

**Comment by muratg** [comment]
Adding to @Eilon, there will be SignalR clients in addition to the server whenever we do release SignalR.

**Comment by Ponant** [comment]
@muratg @Eilon any news about the Azure Mobile SDK?

**Comment by Jonathan34** [comment]
I am not sure why but I was expecting to see an asp.net core 2.0 version to align with .net core/standard 2.0. It looks like it is done in the version 1.2 (so much versions, it is confusing!).
this seems to be the item `.NET Standard 2.0 alignment`. still expected in Q2? any release in Q3?

**Comment by Eilon** [comment]
@Jonathan34 the next version of ASP.NET Core will be 2.0, and is aligned with all the other "2.0" wave of releases. We just updated all our version numbers yesterday from 1.2 to 2.0, so you should see that in builds later this week.

**Comment by Jonathan34** [comment]
aaah, that makes more sense. Thanks!

**Comment by ddobric** [comment]
What is the status of UWP support? Any early prototype available?

**Comment by rynowak** [comment]
> What is the status of UWP support? Any early prototype available?

Can you specific about what you are asking for?
