### ISSUE TITLE
Problem with delete requests when publish on iis asp net core.

### ISSUE THREAD

**Issue by MarozauArtsiom** [aspnet/Home#1690]
I published my asp net core application on iis. Single page application with CORS make delete request and always had error, when I add to web.config section that remove WebDAV it start work normal like on iis express.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
