### ISSUE TITLE
Wrong date time format for Serbian culture

### ISSUE THREAD

**Issue by topguss** [aspnet/Home#1691]
When I define 'sr' (Serbian) as language, I got this format for date-time "27.7.2016. 10.36.43" which is wrong. For time separator we use ":" ! 

It should be like this "27.7.2016. 10:36:43".

Here is official Microsoft document with correct time format: https://www.google.ba/url?sa=t&rct=j&q=&esrc=s&source=web&cd=4&cad=rja&uact=8&ved=0ahUKEwievbKwn5POAhVrAZoKHfycAxwQFggrMAM&url=http%3A%2F%2Fdownload.microsoft.com%2Fdownload%2F6%2Fd%2F4%2F6d4a9f69-3554-49f5-979a-022fbad8a1d2%2Fscc-scg-StyleGuide.pdf&usg=AFQjCNGOftEZolgO6Z__cQFubA-x2TrNmw&sig2=4usyAiUEtQbbfepxVMe0dg&bvm=bv.128153897,d.bGs

See "Time"...

On the Internet you can find examples with Time Separator "." but is wrong.
E.g. the moment.js (http://momentjs.com/) use correct format.

**Comment by muratg** [comment]
@topguss could you move the bug to https://github.com/dotnet/corefx repo?

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
