### ISSUE TITLE
The name 'JsonRequestBehavior' does not exist in the current context

### ISSUE THREAD

**Issue by saf-itpro** [aspnet/Home#1692]
We have created an ASP.NET Core web project using `ASP.NET Core Web Application (.NET Framework) project template`. An action method in our controller class is getting the above error in the following code:

```
using Microsoft.AspNetCore.Mvc;
.....
List<string> userList = new List<string>();
//Code for populating list here
return Json(userList, JsonRequestBehavior.AllowGet);
```

We've installed Json.NET (aka newtonsoft.Json) package via NuGet but still the same error. How can we resolve this error or what are the alternatives to get the above Json in ASP.NET Core Web Application (.NET Framework) project?

**Comment by pranavkm** [comment]
Have you tried `return Json(userList);`

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
