### ISSUE TITLE
DataAnnotations [DisplayFormat(ConvertEmptyStringToNull = false)] RTM

### ISSUE THREAD

**Issue by dpedrelli** [aspnet/Home#1693]
Hi,

I am not sure where this should be posted; so, I am putting it here.  I, recently, upgraded from RC2 to RTM.  Since upgrading, [DisplayFormat(ConvertEmptyStringToNull = false)] on my models no longer works.  If the user submits a view with an empty <input> that maps to a string property, the value is set to NULL.  I have to write code to test each string property for NULL and set it to an empty string.

Thanks.

**Comment by pranavkm** [comment]
Could you file a bug with a repro app in https://github.com/aspnet/Mvc?

**Comment by dpedrelli** [comment]
Submitted.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
