### ISSUE TITLE
Package manager console looking in wrong location for project.json

### ISSUE THREAD

**Issue by GuerrillaCoder** [aspnet/Home#1694]
In VS2015 community I have created the defult asp.net core web app project.

In the package manager console `dotnet restore` works fine but `dotnet build` and `dotnet publish` both throw an error as they are looking for project.json one level up from where it was generated.

I am able to build project from menu and also run it by hitting the green play icon and it works fine, it is just these commands in the package manager console that do not work.

Is there a menu option to publish or a way to get these commands working in package manager?

Edit: I found the publish option in the context menu hen right clicking project which works fine.  It just seems some issue with typing the commands in package manager.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
