### ISSUE TITLE
Error with OneSignal initialization

### ISSUE THREAD

**Issue by deeplydippy** [aspnet/Home#1697]
I want initialize OneSignal on all pages of my web application as some js function in other file instead code on cshtml page.
When I try to use it as code on page, it's working. Here is code from _Layout.chtml in `<head></head> `tags (as in OneSignal Documentation):
```
<link rel="manifest" href="/manifest.json">
<script src="https://cdn.onesignal.com/sdks/OneSignalSDK.js" async></script>
    <script>
        var OneSignal = OneSignal || [];
        OneSignal.push(["init", {
            appId: " *** " ,
            autoRegister: true,
            notifyButton: {
                enable: false
            }
        }]);
    </script>
```
And now I editing code like this:
```
<link rel="manifest" href="/manifest.json">
<script src="https://cdn.onesignal.com/sdks/OneSignalSDK.js" async></script>
<script src="~/js/Push.js"></script>
  <script>
        OneSignalInit();
  </script>
```
Here is my Push.js:
```
function OneSignalInit() {
    $.getScript("https://cdn.onesignal.com/sdks/OneSignalSDK.js", function (data, textStatus, jqxhr) {
    });
    var OneSignal = OneSignal || [];
    OneSignal.push(["init", {
        appId: " *** ",
        autoRegister: true,
        notifyButton: {
            enable: false
        }
    }]);
};
```
But it doesn' work. Thank you for any help!

**Comment by muratg** [comment]
Are you sure if you filed this in the right place? :smile:

**Comment by deeplydippy** [comment]
Yup, of course, because its working when i place code in Layout.

**Comment by muratg** [comment]
@deeplydippy Your example is javascript code above, and you mention OneSignal. I don't understand how this is related to ASP.NET. Are you saying that this exact JS snippet works on a non ASP.NET app, and fails with ASP.NET?

**Comment by deeplydippy** [comment]
Probably, I incorrectly formulated my question. When I placing this JS snippet on  a ASP.NET app in cshtml page (_Layout.cshtml), it works. And now on the same ASP.NET app I create function `OneSignalInit()` in Push.js, which calling at the same place. And its not working. Thank for help!

**Comment by muratg** [comment]
@deeplydippy Sorry, I'm still confused (about how this is related to ASP.NET). What's not working exactly?  Looks like a JS issue to me. Could you use the browser developer tools to see if your JS file is loaded?

**Comment by jjones-pltnm** [comment]
@deeplydippy 

Your problem is likely here:
`$.getScript("https://cdn.onesignal.com/sdks/OneSignalSDK.js", function (data, textStatus, jqxhr) {
    });`

Your callback function contains no code.  Keep in mind that `$.getScript` is an asynchronous method, so it will return immediately *before* OneSignal has been loaded from the server.  You should move the contents of

``` js
var OneSignal = OneSignal || [];
    OneSignal.push(["init", {
        appId: " *** ",
        autoRegister: true,
        notifyButton: {
            enable: false
        }
    }]);
```

inside your callback method in `getScript`.  Also keep in mind that anything else on your page may have to wait for OneSignal to be loaded before they will be able to use it.

**Comment by deeplydippy** [comment]
Thank you!
