### ISSUE TITLE
How to refer our own local NuGet package in Ubuntu 15.10 command line configuration

### ISSUE THREAD

**Issue by manikandan05** [aspnet/Home#1700]
I have develop one project with "student" compile successfully also NuGet package also generated for my project. Now i deploy my project with ASP.NET Core 1.0 web application in Ubuntu OS. 

In my porject.json i have referred my own NuGet package like as

> "dependencies": {
    "Microsoft.NETCore.App": {
      "version": "1.0.0",
      "type": "platform"
    },
    "Microsoft.AspNetCore.Diagnostics": "1.0.0",
    "Microsoft.AspNetCore.Mvc": "1.0.0",
    "Microsoft.AspNetCore.Razor.Tools": {
      "version": "1.0.0-preview2-final",
      "type": "build"
    },
    "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0",
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.0",
    "Microsoft.AspNetCore.StaticFiles": "1.0.0",
    "Microsoft.Extensions.Logging.Debug": "1.0.0",
    "Microsoft.Extensions.Options.ConfigurationExtensions": "1.0.0",
    "Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.0.0",
    "Student.Logging": "1.0.12-preview2-final"
  },

While restore my project will throws the following error.

> log  : Restoring packages for /home/user1/Desktop/WebApplication5/src/WebApplication5/project.json...
error: Unable to resolve **_'Student.Logging (>= 1.0.12-preview2-final)'_** for '.NETCoreApp,Version=v1.0'.
log  : Restoring packages for tool 'BundlerMinifier.Core' in /home/user1/Desktop/WebApplication5/src/WebApplication5/project.json...
log  : Restoring packages for tool 'Microsoft.AspNetCore.Razor.Tools' in /home/user1/Desktop/WebApplication5/src/WebApplication5/project.json...
log  : Restoring packages for tool 'Microsoft.AspNetCore.Server.IISIntegration.Tools' in /home/user1/Desktop/WebApplication5/src/WebApplication5/project.json...
log  : Writing lock file to disk. Path: /home/user1/Desktop/WebApplication5/src/WebApplication5/project.lock.json
log  : /home/user1/Desktop/WebApplication5/src/WebApplication5/project.json
log  : Restore failed in 16655ms.
Errors in /home/user1/Desktop/WebApplication5/src/WebApplication5/project.json
    **_Unable to resolve 'Student.Logging (>= 1.0.12-preview2-final)' for '.NETCoreApp,Version=v1.0'._**

1. Can you please suggest how to refer our own local NuGet packages in Ubuntu. 
2. If there is any options exists? or may be i forgot something need to do in machine configurations.
3. Even i'm installing mono setup, but unfortunately the Nuget.config is not available even search in my entire machine. 

Regards,
M.Manikandan

**Comment by muratg** [comment]
Is your nuget package in a folder? Modify your nuget.config file to add the folder as another nuget source. Alternatively, instead of a local folder, you can create a myget.org feed, and push your package there (this would probably be a better choice if you'd like to access the package from more than one machine.)

**Comment by manikandan05** [comment]
Hi @muratg ,

Yes i have my NuGet in separate folder but i didn't find NuGet.config file in my machine to add my folder as another one nuget source.

Thanks for your suggestion in push my packages in myget.org feed. But i need only local NuGet references in my project.

**Comment by muratg** [comment]
@manikandan05 Go here: `~/.nuget/NuGet/NuGet.config`
