### ISSUE TITLE
How to set environmental variable ASPNETCORE_ENVIRONMENT  in IIS in the latest ASP.Net Core 1.0?

### ISSUE THREAD

**Issue by valcs007** [aspnet/Home#1701]
Hi,

We use VS publish option to deploy to multiple environments ( Dev, Preview and Prod), so i added below commands in project.json file to set ASPNETCORE_ENVIRONMENT value dynamically in the web server as part of publish script. (This was setting environmental variable located in appsettings part of my web.config on my website in IIS). I was doing this to avoid a manual job of setting this ASPNETCORE_ENVIRONMENT variable in each deployment server

Things were working fine with **RC2** libraries but it started failing with latest **1.0 libraries**. 
After analysis, i figured out that there was a **environmentalvariables** element in system.webServer/aspNetCore section of web.config in IIS (Accessed through ConfigurationEditor) and that was not set and hence our code was failing when we check Environment.IsDevelopemnt() function.

What is the command that i can use in project.json to set environmental variable (ASPNETCORE_Environment) in that path while publishing? 

![image](https://cloud.githubusercontent.com/assets/6827384/17411920/f7c96f9a-5a2e-11e6-956b-ad62b46a851a.png)

**Project.Json:** (Snippet)
```
 "publishOptions": {
    "include": [
      "wwwroot",
      "Views",
      "appsettings.json",
      "web.config"
    ]
  },

  "commands": {
    "Development": "Microsoft.AspNet.Server.Kestrel --ASPNETCORE_ENVIRONMENT Development",
    "Preview": "Microsoft.AspNet.Server.Kestrel --ASPNETCORE_ENVIRONMENT Preview",
    "Production": "Microsoft.AspNet.Server.Kestrel --ASPNETCORE_ENVIRONMENT Production"
  },

  "scripts": {
    "prepublish": [ "npm install", "bower install", "gulp clean", "gulp min" ],
    "postpublish": [ "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%" ]
  }
```
Thanks,

**Comment by Tratcher** [comment]
commands in project.json are obsolete. Environment is best managed in your runtime environment, not as part of your project.  E.g. here's how to set it in VS's launchSettings.json file for running your app from VS: https://github.com/aspnet/Templates/blob/dev/src/BaseTemplates/StarterWeb/Properties/launchSettings.json#L8
Similarly for something like Preview you would set it on the server after deployment.

**Comment by valcs007** [comment]
Thanks for your response Tratcher! Is it recommended to set the Special ASPNETCORE_Environment variable in the webconfig (System.Webserver part of config) or as general environmental variable in the web server?

**Comment by Tratcher** [comment]
The web.config flows with your app to different environments, so Environment should not be set there. Set it directly in your deployment environment instead.

**Comment by valcs007** [comment]
What i meant was setting environmental variable collections in web.config using Configuration Editor in the webserver for this website 
 VS
Setting ASPNETCORE_Environment  as System Environmental variable ?

**Comment by Tratcher** [comment]
using configuration editor changes your web.config, and those changes will be lost next time you deploy your app.

**Comment by valcs007** [comment]
I realized that. Thanks Tratcher!

**Comment by valcs007** [comment]
I realized that. Thanks Tratcher!

**Comment by Elrashid** [comment]
if some is scraping thru here , try the steps at [http://stackoverflow.com/a/36836533/4879683](http://goo.gl/fGR1Z6)

**Comment by oliverjanik** [comment]
This answer is completely unsatisfactory. Why are web.config transforms disabled for ASP.NET Core projects?

If I want to have have ASPNETCORE_ENVIRONMENT per site in IIS I have to do it in web.config right? How do I transform the config? Nope.

This dependency on a shared global env variable for every site that's deployed on a server is complete rubbish when it comes to IIS deployments. I understand you're trying to be platfor agnostic but the dev experience of deploying to IIS is utter confusion. 

For example: how do you suggest I add this rewrite rule for production? 

```xml
        <rewrite>
            <rules>
                <rule name="HTML5" stopProcessing="true">
                    <match url=".*" />
                    <conditions>
                        <add input="{REQUEST_FILENAME}" matchType="IsFile" negate="true" />
                        <add input="{REQUEST_FILENAME}" matchType="IsDirectory" negate="true" />
                    </conditions>
                    <action type="Rewrite" url="/" />
                </rule>
            </rules>
        </rewrite>
```

**Comment by nil4** [comment]
@oliverjanik try [dotnet-transform-xdt](https://github.com/nil4/dotnet-transform-xdt); an example for adding rewrite rules is described here: https://github.com/nil4/xdt-samples/#production-iis-config

**Comment by gitfortee** [comment]
Hello, does someone provide insight on how to do it for console applications such as windows services that are non-web applications.?

**Comment by Tratcher** [comment]
That depends entirely on your launching environment. For a windows service you could provide the same information as command line parameters.
