### ISSUE TITLE
Strongly Type Configuration with GetSection not working

### ISSUE THREAD

**Issue by zenixgrace** [aspnet/Home#1702]
Hi all,

Is anyone have a problem like me when configure the option using GetSection like the documentation show?

ex (try to implement the sample code but return error):
`services.Configure<MySubOptions>(Configuration.GetSection("subsection"));`

It's work when I configure the option 1 by 1 

```
services.Configure<MyOptions>(myOptions =>
    {
        myOptions.Option1 = "value1_from_action";
    });
```

**Comment by BurtonR** [comment]
I was having the exact same problem and scratching my head for a while. 

You'll need to add a dependency to your project.json file for the ConfigurationExtensions

`"Microsoft.Extensions.Options.ConfigurationExtensions": "1.0.0"`

**Comment by zenixgrace** [comment]
@BurtonR Microsoft.Extensions.Options.ConfigurationExtensions is not support with full .net framework

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
