### ISSUE TITLE
dotnet restore crashes

### ISSUE THREAD

**Issue by clockwisemusic** [aspnet/Home#1704]
Creating a new project and running "dotnet restore" throws a NullReferenceException:

![untitled](https://cloud.githubusercontent.com/assets/2829865/17466500/c1362cd8-5d54-11e6-965a-63221612918e.png)

I am guessing that the issue is because I'm behind a corporate firewall that needs authentication but I'm not sure.

If I can provide any more information to help troubleshoot please let me know.

**Comment by GuardRex** [comment]
@clockwisemusic That version is truly ancient. Grab fresh tooling from: https://github.com/dotnet/cli/tree/rel/1.0.0 ... Get the .NET Core SDK Installer (2nd column)

**Comment by clockwisemusic** [comment]
Thanks @GuardRex - I had installed a new version but it was still using older one - I uninstalled everything vaguely named "dotnet", installed the latest one, and now it works!! Thanks mate!

**Comment by GuardRex** [comment]
Cross reference (spots that old bits may hide): https://github.com/dotnet/cli/issues/2948
