### ISSUE TITLE
Startup directory related routing bug ASP.NET core targeting net461

### ISSUE THREAD

**Issue by erik-lundgren** [aspnet/Home#1705]
Hello, 

I hope this isn't the wrong place for this. If so, please point me to where I should post this. Thanks in advance!

I'm using `net461` (the bug seems to appear on `net451` for that matter) and having a test project with a `TestStartup` class that, internally, uses the original `Startup` class from the main project. However when I try to create a `TestServer` and use it's test client to access my controllers I keep getting 404 errors.

A small, reproducing repository example can be found at [https://github.com/erik-lundgren/net461-startup-repro](https://github.com/erik-lundgren/net461-startup-repro).

If I switch to `netcoreapp1.0` in the reproducing repository the issue goes away (try it yourself by switching to the `desired` branch. However, because I am dependent on several projects that don't target `netcoreapp1.0` I can't switch to it in my real project. 

If I move the `TestStartup` class to the main project it also works perfectly, but I don't want to pollute that project with my testing mocks and such, so it's not a good solution for me either.

If this is intended behaviour, how can I use a separate startup class for my test project (to mock out certain webservices or the like)?

**Comment by kichalla** [comment]
Check the following code which is used to do in-memory integration tests in MVC. I guess you might need to something like the highlighted line here? cc @javiercn 

https://github.com/aspnet/Mvc/blob/1.0.0/test/Microsoft.AspNetCore.Mvc.FunctionalTests/MvcTestFixture.cs#L65

**Comment by erik-lundgren** [comment]
That resolves the issue for me in my project, thanks a lot for the help. 

For reference I added these lines to my `TestStartup` `ConfigureServices` method, after `startUp.ConfigureServices(services);` (line 33):

    var startupAssembly = typeof(Startup).Assembly;

     // Inject a custom application part manager. Overrides AddMvcCore() because that uses TryAdd().
    var manager = new ApplicationPartManager();
    manager.ApplicationParts.Add(new AssemblyPart(startupAssembly));

    manager.FeatureProviders.Add(new ControllerFeatureProvider());

    services.AddSingleton(manager);

Still curious if it's intended that `netcoreapp1.0` behaves differently than `net461`. If so, you can close this.

Thanks for the help!

**Comment by mattbrooks2010** [comment]
It would be good to know why this is necessary and whether it is the most appropriate solution — thanks in advance.

**Comment by javiercn** [comment]
Hi,

I've put together a blog post and a sample on how to do this with test server.

The blog post is here:
https://blogs.msdn.microsoft.com/webdev/2017/12/07/testing-asp-net-core-mvc-web-apps-in-memory/

The sample is here:
https://github.com/aspnet/samples/tree/master/samples/aspnetcore/mvc/testing/TestingMVC

It's important to note that you need to run the tests using either Visual Studio or dotnet test. There are some issues that we are investigating regarding running the tests with dotnet xunit at the time.

If you still have problems after this, feel free to reopen the issue.
