### ISSUE TITLE
Unspecified error (Exception from HRESULT: 0X80004005 (E_FAIL)) 

### ISSUE THREAD

**Issue by dotnetdeveloper786** [aspnet/Home#1706]
when i create web application using .net framework 4.5 it gives me error in VS 2015

Unspecified error (Exception from HRESULT: 0X80004005 (E_FAIL))

**Comment by GuardRex** [comment]
They'll probably need more project particulars. Can you put up a minimal GH repro project to look at?

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
