### ISSUE TITLE
[Discussion]: Migrating AspNetCore feeds to dotnet.myget.org

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Home#1708]
The ASP.NET and EF Core MyGet feeds have moved from www.myget.org to dotnet.myget.org. There are automatic redirects from the old feeds to the new feeds so no _immediate_ change is needed. If you use the nightly feeds for packages, please move to the new feeds ASAP. The redirects will be available for at least a few weeks.

| https://www.myget.org/f/ (Before) | https://dotnet.myget.org/f/ (After) |
| --- | --- |
| aspnetvnext | aspnetcore-dev |
| aspnetrelease | aspnetcore-release |
| aspnetmaster | aspnetcore-master |
| aspnetcidev | aspnetcore-ci-dev |
| aspnetcirelease | aspnetcore-ci-release |

Please use https://github.com/aspnet/Home/issues/1708 for further discussion.

**Comment by maartenba** [comment]
From the [MyGet](https://www.myget.org) side: redirects have been applied.

**Comment by imranbaloch** [comment]
@pranavkm look like it should go to Announcement Repo. Isn't?

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
