### ISSUE TITLE
No service for type 'Microsoft.Extensions.PlatformAbstractions.IApplicationEnvironment' has been registered

### ISSUE THREAD

**Issue by Javietto** [aspnet/Home#1710]
Hello guys, I need some help making this work.

The objective:
Compile a .exe from my aspnetcore project so I can host it as guest executable on azure service fabric

The status:
My aspnetcore app runs fine when I use "dnx web ."
To build the exe I use "dotnet publish ASPNET5Demo"

My entry point:
`public static void Main(string[] args) => WebApplication.Run<Startup>(args);`

My project.json:
`{
  "userSecretsId": "aspnet5-*******************_",
  "version": "1.0.0-_",
  "compilationOptions": {
    "emitEntryPoint": true
  },

  "dependencies": {
    "EntityFramework.Commands": "7.0.0-rc1-final",
    "EntityFramework.MicrosoftSqlServer": "7.0.0-rc1-final",
    "Microsoft.AspNet.Authentication.Cookies": "1.0.0-rc1-final",
    "Microsoft.AspNet.Diagnostics.Entity": "7.0.0-rc1-final",
    "Microsoft.AspNet.Identity.EntityFramework": "3.0.0-rc1-final",
    "Microsoft.AspNet.IISPlatformHandler": "1.0.0-rc1-final",
    "Microsoft.AspNet.Mvc": "6.0.0-rc1-final",
    "Microsoft.AspNet.Mvc.TagHelpers": "6.0.0-rc1-final",
    "Microsoft.AspNet.Server.Kestrel": "1.0.0-rc1-final",
    "Microsoft.AspNet.StaticFiles": "1.0.0-rc1-final",
    "Microsoft.AspNet.Tooling.Razor": "1.0.0-rc1-final",
    "Microsoft.Extensions.CodeGenerators.Mvc": "1.0.0-rc1-final",
    "Microsoft.Extensions.Configuration.FileProviderExtensions" : "1.0.0-rc1-final",
    "Microsoft.Extensions.Configuration.Json": "1.0.0-rc1-final",
    "Microsoft.Extensions.Configuration.UserSecrets": "1.0.0-rc1-final",
    "Microsoft.Extensions.Logging": "1.0.0-rc1-final",
    "Microsoft.Extensions.Logging.Console": "1.0.0-rc1-final",
    "Microsoft.Extensions.Logging.Debug": "1.0.0-rc1-final",
    "Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.0.0-rc1-final"
  },

  "commands": {
    "web": "Microsoft.AspNet.Server.Kestrel",
    "ef": "EntityFramework.Commands"
  },

  "frameworks": {
    "dnx451": { },
    "dnxcore50": { }
  },

  "exclude": [
    "wwwroot",
    "node_modules"
  ],
  "publishExclude": [
    "**.user",
    "**.vspscc"
  ],
  "scripts": {
    "prepublish": [ "npm install", "bower install", "gulp clean", "gulp min" ]
  }
}
`

My dnvm list:
1.0.0-rc1-update1 clr     x86          win
1.0.0-rc1-update2 clr     x86          win             1.0.0-rc1-final, default, dnx-clr-win-x86.1.0.0-rc1-up...

And finally my error with the trace:
[http://i.imgur.com/DcewD4G.png](http://i.imgur.com/DcewD4G.png)

I'd appreciate any help/knowledge that you guys can give me because I'm pretty lost with this. I've seen some other users have reported the same error but I haven't been able to fix it myself following the same steps.

Thanks in advance.

**Comment by davidfowl** [comment]
DNX is long gone. You might watt to read this https://docs.asp.net/en/latest/migration/rc1-to-rtm.html

**Comment by Javietto** [comment]
Hello David,

Thanks for your answer. I read the article prior creating this issue. Unfortunately I dont think is possible for me to move to net451 because I have a dependency "Microsoft.Extensions.CodeGenerators.Mvc" that needs either dnx or dnxcore.

I'm doing all this because I want to be able to have a webapp hosted on service fabric that allows me to scaffold entity framework to quickly create admin sites for our databases.

Maybe I'm tackling this the wrong way, could you give me your advice? Thanks in advance.

**Comment by pranavkm** [comment]
The package was renamed in RC2. Use https://www.nuget.org/packages/Microsoft.VisualStudio.Web.CodeGenerators.Mvc instead.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
