### ISSUE TITLE
ASP.NET 5 - CookieHeaderValue.TryParse doesn't allow for non-standard System.Web.HttpServerUtility.FormatHttpCookieDateTime format

### ISSUE THREAD

**Issue by MerickOWA** [aspnet/Home#1711]
I understand this is for the ASP.NET 5 and not core, but I'm not sure where else to post this issue.  If someone knows a better location, please advise and i'll close and move it.

The format generated by System.Web.HttpCookie when formated is non-standard, a mix between RFC1123 and RFC850 (At least as of .NET Framework 4.6.1)

The exact format string used is `"ddd, dd-MMM-yyyy HH':'mm':'ss 'GMT'"` as seen [here](http://referencesource.microsoft.com/#System.Web/httpserverutility.cs,1526)

This doesn't quite match RFC1123 which is `"ddd, d MMM yyyy H:m:s 'GMT'"` as it uses dashes between the day, month, and year instead of spaces, but doesn't quite match RFC850 which is `"dddd, d'-'MMM'-'yy H:m:s 'GMT'"` as it uses a short day of the week instead of a longer form.

ASP.NET 5's CookieHeaderValue.TryParse has a list of allowable date formats when it calls DateTimeOffset.TryParseExact, however the one used by HttpCookie listed above isn't one of them.

dotnet core seems to avoid this issue by using an call to [DateTime.TryParse](https://github.com/dotnet/corefx/blob/bd1bac7f566cb5e9e984b0b67cdb55dcc1d91d94/src/System.Net.Primitives/src/System/Net/Cookie.cs#L1493) instead a TryParseExact.

It is interesting to note however that this format isn't listed in listed/supported by dotnet core's [HttpRuleParser.TryStringToDate](https://github.com/dotnet/corefx/blob/d0dc5fc099946adc1035b34a8b1f6042eddb0c75/src/System.Net.Http/src/System/Net/Http/HttpRuleParser.cs#L16-L35) either, but this isn't used by the Cookie class.

**Comment by Tratcher** [comment]
Asp.Net 5 is now called Asp.Net Core 1. I'll move this to the correct repo.

**Comment by Tratcher** [comment]
This issue was moved to aspnet/HttpAbstractions#687
