### ISSUE TITLE
Fatal Crash - Debugging Stops

### ISSUE THREAD

**Issue by MelbourneDeveloper** [aspnet/Home#1713]
I have spent the last few days porting our existing ASP .NET Core (.NET) REST service to ASP .NET Core (Core). I.e. I shared all of our .cs files in to the new xproj format and compiled all of our DLLs for the new platform. Most of the lower level DLLs (model assemblies) were compiled as portable .NET Standard 1.4 DLLs. I then NuGet packaged these DLLs up, and referenced it in my .NET Core solution.

My ASP .NET Core (Core) solution consists of 4 .NET Core class libraries and 1 ASP .NET Core project. Everything compiles fine. All of the code in the main ASP project is shared by two projects: the .NET Framework REST Service, and the .NET Core REST Service. 

I was really excited when I ran the service for the first time. I was even more excited when I saw the yellow arrow appear in my controller's method. That means that the server successfully started up, and my web browser successfully sent a request to my REST service which is compiled on .NET Core.

However, when I hit F10 on the first main line of code which is a simple property setter, the whole server crashes, and I lose debugging. No explanation is given.

This is the line:

```
    DataAccessLayer.ConnectionString = @"[CONNECTION STRING]";

    public static string ConnectionString
    {
        get
        {
            return DataWorker.DatabaseAdapter.ConnectionString;
        }
        set
        {
            DataWorker.DatabaseAdapter.ConnectionString = value;
        }
    }
```

The only piece of information I have is from the output window:

'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Users\ChristianFindlay.nuget\packages\XivicModelAssembliesStandard\1.0.0\lib\netstandard1.4\Adapt.Model.DataSchema.Portable.dll'. Symbols loaded.
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Users\ChristianFindlay.nuget\packages\System.Diagnostics.Contracts\4.0.1-rc2-24027\lib\netstandard1.0\System.Diagnostics.Contracts.dll'. Cannot find or open the PDB file.
The program '[14720] dotnet.exe' has exited with code -2146233022 (0x80131542).
The program '[7028] iisexpress.exe' has exited with code 0 (0x0).

What does this mean? Why does it need the pdb file?

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
