### ISSUE TITLE
Authenicating to 3rd party rest APIs / webservices

### ISSUE THREAD

**Issue by richardwindle** [aspnet/Home#1714]
Hi,

I'm uncertain as to what repo is more suited for this if its security or something else.

We are currently redoing an intranet site (using windows authentication), that includes a list of documents that the user has permission to in SharePoint 2013.  We are doing this via the rest api however we seem unable to pass the windows identity to SharePoint.

Is there currently a way in .Net Core to pass the windows authentication token to SharePoint? I found the "MS-ASPNETCORE-WINAUTHTOKEN" and  "MS-ASPNETCORE-TOKEN" which we have tried but with no success.

Thanks,

Richard

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
