### ISSUE TITLE
Custom TagHelper does not create AntiForgeryToken in HTML

### ISSUE THREAD

**Issue by NavjotSinghMinhas** [aspnet/Home#1715]
Here is the code i am using to customize the TagHelper:

```
[HtmlTargetElement("form", Attributes = "custom-tag-controller, custom-tag-action")]
public class FormTagHelper : TagHelper
{
    [HtmlAttributeName("custom-tag-controller")]
    public string controller { get; set; }

    [HtmlAttributeName("custom-tag-action")]
    public string action { get; set; }

    public override void Process(TagHelperContext context, TagHelperOutput output)
    {
        output.Attributes.Add("action", "//" + controller.ToLower() + "." + Startup.Configuration["Site:Name"] + "/" + action.ToLower());
    }
}
```

Here is the HTML:
`<form custom-tag-controller="Account" custom-tag-action="ExternalLogin"  method="post" class="form-horizontal" role="form">
        <button type="submit" class="btn btn-default" name="provider" value="Facebook" title="Log in using your account">Facebook</button>           
    </form>`

And **if i use the default TagHelper with my cutom TagHelper** by adding asp-route-returnurl then the action is added two times in the HTML, e.g: 
`<form id="form-login" method="post" class="p-t-15" role="form" action="" action="//account.example.com/login">`

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
