### ISSUE TITLE
Make Microsoft.Extensions.* CLS compliant

### ISSUE THREAD

**Issue by NKnusperer** [aspnet/Home#1716]
Is there any reason why they are not marked with `CLSCompliant(true)` ?
As far as I have looked through the projects non of theme are using suspicious types which are not compliant.

**Comment by Tratcher** [comment]
We're considering it for the v1.1 milestone.

**Comment by NKnusperer** [comment]
v1.1 is now out but looks like nothing has changed.

**Comment by jopabe** [comment]
Second this. We're starting to standardize on the Logging, DependencyInjection, Configuration and Options libraries for full .NET projects as well, but right now that requires marking all our software as `CLSCompliant(false)` (FxCop doesn't like omitting the attribute at all).
As these libraries support full .NET framework, it makes sense for them to comply with established standards/conventions as coded into static analysis tools where possible - especially here as there seems to be no downside.

Thanks for considering!

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
