### ISSUE TITLE
AspNetCore not getting POST data in web api controller [FromBody]

### ISSUE THREAD

**Issue by nanivijay** [aspnet/Home#1720]
we recently upgraded from asp.net 5 rc1 to core 1.0. we have a middle-ware whire we used enablerewind() to buffer the request body. 
**appBuilder.Use(next => context =>
            {
              context.Request.EnableRewind();
                return next(context);
            });**

after the above middleware we will access the body in web api controller post method using [FromBoy] model binder.

It used to work as expected in rc1 but after migration to core the [FromBody] parameter in the http post methos is null. When we see the errors in model below is the exception we are getting.

**{System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'FileBufferingReadStream'.
  at Microsoft.AspNetCore.WebUtilities.FileBufferingReadStream.ThrowIfDisposed()
  at Microsoft.AspNetCore.WebUtilities.FileBufferingReadStream.Read(Byte[] buffer, Int32 offset, Int32 count)
  at Microsoft.AspNetCore.WebUtilities.HttpRequestStreamReader.ReadIntoBuffer()
  at Microsoft.AspNetCore.WebUtilities.HttpRequestStreamReader.Read(Char[] buffer, Int32 index, Int32 count)
  at Newtonsoft.Json.JsonTextReader.ReadData(Boolean append, Int32 charsRequired)
  at Newtonsoft.Json.JsonTextReader.ParseValue()
  at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter)
  at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)}**

Please help me in resolving this issue

**Comment by pranavkm** [comment]
Seems similar to https://github.com/aspnet/Mvc/issues/4962. Could you try the workaround suggested in https://github.com/aspnet/Mvc/issues/4962#issuecomment-230501446?

**Comment by nanivijay** [comment]
@pranavkm the work around worked for me.

**Comment by Elringus** [comment]
I have a similar issue, but the workaround is not working for me. 

Here I’m adding a WebSocket middleware with the proposed workaround:

```
appBuilder.Use(async (httpContext, next) => {
    var initialBody = httpContext.Request.Body; 
    await BaseController.HandleWebSosketRequest(httpContext, next);
    httpContext.Request.Body = initialBody; 
});
```

However, I still receive null from the body:
```
[HttpPost]
public JToken HandleRequest ([FromBody]JToken data)
{
    // data is null here!
}
```

Am I missing something? Here is a full Configure method I’m using for the app:
```
public void Configure (IApplicationBuilder appBuilder, IHostingEnvironment env, ILoggerFactory loggerFactory)
{
	loggerFactory.AddConsole(Configuration.GetSection("Logging"));
	loggerFactory.AddDebug();
	Log.Logger = loggerFactory.CreateLogger("Application Log");

	if (env.IsDevelopment())
	{
		appBuilder.UseBrowserLink();
		appBuilder.UseDeveloperExceptionPage();
	}

	appBuilder.UseIISPlatformHandler();
	appBuilder.UseStaticFiles();
	appBuilder.UseWebSockets();
	appBuilder.Use(async (httpContext, next) => {
		var initialBody = httpContext.Request.Body; 
		await BaseController.HandleWebSosketRequest(httpContext, next);
		httpContext.Request.Body = initialBody; 
	});
	appBuilder.UseCookieAuthentication(options =>
	{
		options.AutomaticAuthenticate = true;
	});
	appBuilder.UseOpenIdConnectAuthentication(options =>
	{
		options.AutomaticChallenge = true;
		options.ClientId = Configuration["Authentication:AzureAd:ClientId"];
		options.Authority = Configuration["Authentication:AzureAd:AADInstance"] + Configuration["Authentication:AzureAd:TenantId"];
		options.PostLogoutRedirectUri = Configuration["Authentication:AzureAd:PostLogoutRedirectUri"];
		options.SignInScheme = CookieAuthenticationDefaults.AuthenticationScheme;
	});
	appBuilder.UseMvc(routes =>
	{
		routes.MapRoute(
			name: "editor",
			template: "editor/{controller=Home}/{action=Index}/{id?}");
	});
}
```

**Comment by nanivijay** [comment]
@Elringus  try adding httpContext.Request.EnableRewind(); return next(httpContext) after httpContext.Request.Body = initialBody;

**Comment by Elringus** [comment]
@nanivijay thanks for the suggestion, but it didn't work. 

One thing that’s really bugging me is why it’s working locally. Could it be that it uses an older DNX runtime on my machine, which didn’t have this bug? I thought it should use runtime version specified in the project.json, no matter the environment…
