### ISSUE TITLE
Not able to install dnvm using CMD

### ISSUE THREAD

**Issue by vivvicks** [aspnet/Home#1721]
C:\Users\VINAYAK'S PC>@powershell -NoProfile -ExecutionPolicy unrestricted -Command "&{$Branch=’dev’;iex ((new-object net.webclient).DownloadString(‘ https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.ps1‘))}"
Using temporary directory: C:\Users\VINAYA~1\AppData\Local\Temp\dnvminstall
Downloading DNVM.ps1 to C:\Users\VINAYA~1\AppData\Local\Temp\dnvminstall\dnvm.ps1
Downloading DNVM.cmd to C:\Users\VINAYA~1\AppData\Local\Temp\dnvminstall\dnvm.cmd
Installing DNVM
At line:1 char:157
- ... Thread.CurrentUICulture = '';$CmdPathFile='C:\Users\VINAYAK'S PC\AppD ...
-                                                                 ~
  Unexpected token 'S' in expression or statement.
  At line:1 char:258
- ... ';& 'C:\Users\VINAYA~1\AppData\Local\Temp\dnvminstall\dnvm.ps1' setup
-                                                                   ~~~~~~~
  The string is missing the terminator: '.
  - CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordEx
    ception
  - FullyQualifiedErrorId : UnexpectedToken

**Comment by BrennanConroy** [comment]
Looks like dnvm install script doesn't like `'` in folder names.

Why are you trying to install dnvm? It is old and deprecated. See https://github.com/aspnet/dnvm/blob/dev/README.md

**Comment by pranavkm** [comment]
https://docs.asp.net/en/latest/migration/rc1-to-rtm.html has documentation on what you would do migrate from RC1 (the last version that used DNX \ DNVM) to RTM which uses `dotnet`.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
