### ISSUE TITLE
Content Root same as Web Root after deploying to Azure Web App

### ISSUE THREAD

**Issue by ninety7** [aspnet/Home#1722]
I'm having issues after creating an app from the empty template. When run locally, there are no issues as *ContentRoot* is pointing to where the `appsettings.json` file is and *WebRoot* points to the wwwroot folder configured in `project.json`.

The problem happens when deploying the app to azure using VS2015. After deployment succeeds, opening the app in the browser throws a 500 server error. Looking at the logs, I see that the *ContentRoot* is pointing to the wwwroot folder and hence the error that some files that I deployed along with the `appsettings.json` file could not be found on the wwwroot folder.

I don't know if this is an issue with azure or with asp.net core, but this is the place where it was more logical to post the issue to. This is how my program.cs file builds the web host:

```csharp
var host = new WebHostBuilder()
                .UseKestrel()
                .UseContentRoot(Directory.GetCurrentDirectory())
                .UseIISIntegration()
                .UseStartup<Startup>()
                .Build();
```
Looks like `Directory.GetCurrentDirectory()` is returning wwwroot but I can't find out why?

Is this a bug?

**Comment by Tratcher** [comment]
Look at the full paths. There's some confusion deploying to azure because the deployment directory is called wwwroot, and within that you will have your own wwwroot directory for static files.

**Comment by ninety7** [comment]
Yeah. Actually I forgot to close this one yesterday. Closing now.

**Comment by ace26** [comment]
Oh don't close this just yet cause I am having the same issue at the moment.
Like the initial poster, I have deployed as an Azure app api and though it works well on my local machine, it points to the wwwroot folder on Azure and thus the file read operation fails with the same exception message like the poster's.
Is there any extra thing to do to read the file in the content root while it is deployed on azure?

**Comment by Tratcher** [comment]
@ace26 this issue was closed a long time ago. Please open a new one and provide repro steps.
