### ISSUE TITLE
How to precompile Mvc6 Aspnetcore 1.0 with Webdeploy ?

### ISSUE THREAD

**Issue by crydante** [aspnet/Home#1729]
Where is the option to precompile the project when publishing to IIS with WebDeploy ? .ps1 file ? .pubxml file ?

 There is no documentation about it and it's very difficult to find information.

Thnak you and sorry for my english.

**Comment by pranavkm** [comment]
@crydante are you talking of view precompilation? We are working on a tool for that we plan to release a preview for as part of the 1.1.0 release.

**Comment by crydante** [comment]
I'm not sure it's about precompilation view. The problem it's every time i publish on my IIS on production each page seems to compile the first time we are call it and it takes very long time. Is it possible to precompile the project to not have the "on-time" compilation ?

**Comment by davidfowl** [comment]
That's view pre-compilation.

**Comment by GuardRex** [comment]
Cross ref to the Razor issue: https://github.com/aspnet/Mvc/issues/3917 including a nice little ditty by @tuespetre at https://github.com/tuespetre/dotnet-precompile-views

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
