### ISSUE TITLE
Razor The type or namespace could not be found.

### ISSUE THREAD

**Issue by GAMP** [aspnet/Home#1731]
Hi.
I have an application (Service) targeting .NET 4.61 and trying to move to AspNetCore self host with WebListener.
I am trying to investigate the requirements by testing it out in a console application.
The project i crated is a normal Windows console application, i referenced all the required packages with nuget and created required Startup class and create and start the host with WebHostBuilder.
**I dont have any project.json files in my project and adding it didn't help.**

Application runs fine and i get Web Api calls and routing functioning correctly.
The only problem that i have is that when i try to access MVC web page the views are not created but i rather get an error page with dozen of errors such as 

The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)
Predefined type 'System.Object' is not defined or imported
The type or namespace name 'ViewFeatures' does not exist in the namespace 'Microsoft.AspNetCore.Mvc' (are you missing an assembly reference?)

Am i missing something ?

**Comment by pranavkm** [comment]
Mvc's runtime compilation relies on DependencyContext (deps file) to look up compilation references which is only produced when you compile using dotnet CLI. You would have to add compilation references as part of the application startup for view compilation to work. See https://github.com/aspnet/Mvc/issues/4818#issuecomment-237693694 for one way to go about doing this.

**Comment by GAMP** [comment]
Indeed this presents a workaround and fix the problem but will this be an official way to resolve or there will be an more elegant approach?

**Comment by pranavkm** [comment]
@GAMP the plan is to support it as part of the conversion to MsBuild based project system. Here's the roadmap for the tooling changes: https://blogs.msdn.microsoft.com/dotnet/2016/07/15/net-core-roadmap/

**Comment by dpedrelli** [comment]
I am having this issue with a .NET Core 2.0, MVC app and an xUnit test project created with the xUnit Test Project (.NET Core) template.  I am running on Windows.  Both projects were created with .NET Core 2.0 templates and use the csproj format.  I am using TestServer to instantiate the MVC app.  I get the namespace error, when MVC returns the Login.cshtml view.

The work around suggested in 4818 works, but that will cause problems running on another computer, or publishing to a deployment server.

```
services
  .AddMvc()
  .AddRazorOptions(options =>
  {
    var assemblyPaths = new [] { "<my dlls here>" };

    foreach (var path in assemblyPaths)
    {
        options.AdditionalCompilationReferences.Add(MetadataReference.CreateFromFile(path));
    }
  });
```

Is there another way to fix this issue?

**Comment by pranavkm** [comment]
@dpedrelli this issue is closed. Could you file a separate issue with details in https://github.com/aspnet/Mvc?

**Comment by masums** [comment]
Dear dpedrelli,
Your technique works for me. Thank for your post.
