### ISSUE TITLE
Cannot Run New Project

### ISSUE THREAD

**Issue by adamreed90** [aspnet/Home#1733]
When simply creating a new project for .NET Core (ASP.NET Core Web Application (.NET Core)), and attempting to run it, without any modifications to the starting template, via IIS is starts on https://localhost:6179/ where I receive an error of "This site can’t provide a secure connection".

When debugging via Kestrel, it start on http://localhost:5000/, which I receive an error of: 
info: Microsoft.AspNetCore.Server.Kestrel[17]
Connection id "0HKUKAV4I0LKI" bad request data: "Malformed request: MethodIncomplete"
Microsoft.AspNetCore.Server.Kestrel.BadHttpRequestException: Malformed request: MethodIncomplete
info: Microsoft.AspNetCore.Server.Kestrel[17]
Connection id "0HKUKAV4I0LKJ" bad request data: "Malformed request: MethodIncomplete"
Microsoft.AspNetCore.Server.Kestrel.BadHttpRequestException: Malformed request: MethodIncomplete

However, using the (ASP.NET Core Web Application (.NET Framework)) template I am able to run the website using IIS, but get the above error again when using Kestrel, also the Debug opens the site in https:// not http:// by default, when the Kestrel Server is opened bound to http://. 

My Setup:
Microsoft Visual Studio Enterprise 2015
Version 14.0.25425.01 Update 3
Microsoft .NET Framework
Version 4.6.01590

ASP.NET and Web Tools 2015.1 14.1.20810.0
ASP.NET and Web Tools 2015.1

ASP.NET Web Frameworks and Tools 2012.2 4.1.41102.0
For additional information, visit http://go.microsoft.com/fwlink/?LinkID=309563

ASP.NET Web Frameworks and Tools 2013 5.2.40314.0
For additional information, visit http://www.asp.net/

Bundler & Minifier 2.1.279
Adds support for bundling and minifying JavaScript, CSS and HTML files in any project.

Image Optimizer 3.6.93
Uses industry standard tools to optimize any JPEG, PNG and Gifs - including animated Gifs. Can do both lossy and lossless optimization.

Image Sprites 1.3.40
Boost your website's performance by creating image sprites to reduce the amount of HTTP requests needed.

Image Optimizer 3.6.93
Uses industry standard tools to optimize any JPEG, PNG and Gifs - including animated Gifs. Can do both lossy and lossless optimization.

Image Sprites 1.3.40
Boost your website's performance by creating image sprites to reduce the amount of HTTP requests needed.

Microsoft .NET Core Tools (Preview 2) 14.1.20810.0
Microsoft .NET Core Tools (Preview 2)

Microsoft Azure Tools 2.9
Microsoft Azure Tools for Microsoft Visual Studio 2015 - v2.9.40715.2

NuGet Package Manager 3.5.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

Visual Studio 2015 Tools for Docker - Preview 0.31
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a Docker Container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Web Compiler 1.11.319
Compiler for LESS, Sass and CoffeeScript files

Web Essentials 2015.3 3.0.235
Adds many useful features to Visual Studio for web developers. Requires Visual Studio 2015

**Comment by GuardRex** [comment]
For Kestrel (no ISS; no reverse-proxy) see: https://github.com/aspnet/KestrelHttpServer/issues/969

For IIS, do not configure Kestrel. Setup IIS for secure endpoints in the normal way. The reverse-proxy between IIS and Kestrel will run on an insecure random port picked by the IISIntegration middleware.

**Comment by adamreed90** [comment]
What I am saying is the default template, right out of the box in VS, cannot build/run. Simply creating a project with either template, and it will not run.

**Comment by GuardRex** [comment]
I see. There's a templates repo with issues at https://github.com/aspnet/Templates/issues <-- The devs monitoring that might not see this here in Home; so if you determine that the OOB template has a problem, you might want to move this issue over there, where more template dev :eyes: will see it.

**Comment by adamreed90** [comment]
Well, that didn't work :(. No responses.
