### ISSUE TITLE
Asp.Net Core Web app (.NET Core) compiler errors

### ISSUE THREAD

**Issue by karthicktv** [aspnet/Home#1734]
I've a asp.net core web app (.NET Core) Web API project that references a Class library that is built for the target framework 4.5 

I made changes to the project.json by including the "net45" in the frameworks array and when I attempt to build, I get this compiler error: Type or Namespace AspNetCore does not exists in namespace "Microsoft" . I tried ignoring the error and the Web API works fine even though there are compiler errors.

I don't see any squiggly lines in any of the code that is complaining about.

![image](https://cloud.githubusercontent.com/assets/8471776/18257267/c947d4a6-73b8-11e6-85d8-a37eaee03ca5.png)

Here is the info: 

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64

Any thoughts? Please help!

**Comment by janpieterz** [comment]
Could you post your project.json? And have you tried running restore packages from Visual Studio? Running `dotnet restore` from the command line can cause issues when referencing older class libraries, so restoring from Visual Studio is recommended.

**Comment by karthicktv** [comment]
Here is my project.json and yes, I tried restoring from within VS but on the output it says "1 succeed, 1 failed, 0 skipped" - not sure what this means?!

![image](https://cloud.githubusercontent.com/assets/8471776/18268656/a27ca57c-741c-11e6-9631-ba1505040dbd.png)

  {
  "tools": {
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.0.0-preview2-final"
  },
    "frameworks": {
      "netcoreapp1.0": {
        "imports": [
          "dotnet5.6",
          "portable-net45+win8"
        ],
        "dependencies": {
          "Microsoft.NETCore.App": {
            "version": "1.0.0",
            "type": "platform"
          },
          "Microsoft.ApplicationInsights.AspNetCore": "1.0.0",
          "Microsoft.AspNetCore.Mvc": "1.0.0",
          "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0",
          "Microsoft.AspNetCore.Server.Kestrel": "1.0.0",
          "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.0.0",
          "Microsoft.Extensions.Configuration.FileExtensions": "1.0.0",
          "Microsoft.Extensions.Configuration.Json": "1.0.0",
          "Microsoft.Extensions.Logging": "1.0.0",
          "Microsoft.Extensions.Logging.Console": "1.0.0",
          "Microsoft.Extensions.Logging.Debug": "1.0.0",
          "Microsoft.Extensions.Options.ConfigurationExtensions": "1.0.0"
        }
      },
      "net45": {
        "dependencies": {
          "HPFS.IDS.Common.VNext": {
            "target": "project"
          }
        }
      }
    },
  "buildOptions": {
    "emitEntryPoint": true,
    "preserveCompilationContext": true
  },
  "runtimeOptions": {
    "configProperties": {
      "System.GC.Server": true
    }
  },
  "publishOptions": {
    "include": [
      "wwwroot",
      "Views",
      "Areas/**/Views",
      "appsettings.json",
      "web.config"
    ]
  },
  "scripts": {
    "postpublish": [ "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%" ]
  },
  "dependencies": {
  }
}

**Comment by Tratcher** [comment]
All of your dependencies are nested under netcoreapp1.0, net45 doesn't have any. You either need to duplicate them or move them out of the frameworks node like this:
```
  {
  "tools": {
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.0.0-preview2-final"
  },
      "dependencies": {
          "Microsoft.ApplicationInsights.AspNetCore": "1.0.0",
          "Microsoft.AspNetCore.Mvc": "1.0.0",
          "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0",
          "Microsoft.AspNetCore.Server.Kestrel": "1.0.0",
          "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.0.0",
          "Microsoft.Extensions.Configuration.FileExtensions": "1.0.0",
          "Microsoft.Extensions.Configuration.Json": "1.0.0",
          "Microsoft.Extensions.Logging": "1.0.0",
          "Microsoft.Extensions.Logging.Console": "1.0.0",
          "Microsoft.Extensions.Logging.Debug": "1.0.0",
          "Microsoft.Extensions.Options.ConfigurationExtensions": "1.0.0"
        }
      },
    "frameworks": {
      "netcoreapp1.0": {
        "imports": [
          "dotnet5.6",
          "portable-net45+win8"
        ],
        "dependencies": {
          "Microsoft.NETCore.App": {
            "version": "1.0.0",
            "type": "platform"
          }
        }
      },
      "net45": {
        "dependencies": {
          "HPFS.IDS.Common.VNext": {
            "target": "project"
          }
        }
      }
    },
  "buildOptions": {
    "emitEntryPoint": true,
    "preserveCompilationContext": true
  },
  "runtimeOptions": {
    "configProperties": {
      "System.GC.Server": true
    }
  },
  "publishOptions": {
    "include": [
      "wwwroot",
      "Views",
      "Areas/**/Views",
      "appsettings.json",
      "web.config"
    ]
  },
  "scripts": {
    "postpublish": [ "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%" ]
  },
  "dependencies": {
  }
}
```

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
