### ISSUE TITLE
RedirectToAction use the same verb as request

### ISSUE THREAD

**Issue by Pzixel** [aspnet/Home#1735]
For example assume we have a controller with two methods on same URL but which uses different verbs (assuming we have single default route `{controller=Home}/{action=Index}/{id?}`) :

```
[HttpGet]
public async Task<IActionResult> Filter(int? id)
{
    // doing something
}

[HttpDelete]
public async Task<IActionResult> Filter(int id)
{
    await TaskHelper.CompletedTask;
    return RedirectToAction("Filter", (object) null);
}
```

Then we are calling a second method.

**Expected result:** client receive `302 GET` and get redirected to first method. [According to MSDN](https://msdn.microsoft.com/en-us/library/system.web.mvc.controller.redirecttoaction%28v=vs.118%29.aspx?f=255&MSPPError=-2147217396), `RedirectToAction` should return `302 GET`

**Actual result:** controller falls in infinite loop, becuase it always get redirected to itself. Sample screenshots:
![image](https://cloud.githubusercontent.com/assets/11201122/18279028/d1c98620-745c-11e6-905c-456773c0022e.png)
![image](https://cloud.githubusercontent.com/assets/11201122/18279058/f058b732-745c-11e6-88fb-e931ed9d57a7.png)

**Comment by Tratcher** [comment]
Http does not provide a way for redirects to specify which verb to use on the next request. Most redirects will use the same verb, except for some clients redirect POST to GET.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
