### ISSUE TITLE
Static Assets are not loading consistently

### ISSUE THREAD

**Issue by PeerMohamedMydeen** [aspnet/Home#1737]
Hi, 

I have hosted an ASP.NET Core application in IIS and facing a challenge while browsing the application after hosting.

Static assets (Styles , Java script files) are not loading and getting a 502 Bad Gateway. This occurs inconsistently and also occurs while making browser refresh. 

Any inputs would be highly appreciated. 

![kestrel](https://cloud.githubusercontent.com/assets/22055341/18315970/79fa9a4e-7536-11e6-9bda-1c892251cbdf.jpg)

**Comment by MaximRouiller** [comment]
Can you share your Startup.cs? Middlewares can impact requests.

**Comment by PeerMohamedMydeen** [comment]
`public class Startup
    {
        public Startup(IHostingEnvironment env)
        {
            var builder = new ConfigurationBuilder()
                .SetBasePath(env.ContentRootPath)
                .AddJsonFile("appsettings.json", optional: true, reloadOnChange: true)
                .AddJsonFile($"appsettings.{env.EnvironmentName}.json", optional: true)
                .AddEnvironmentVariables();
            Configuration = builder.Build();
        }

        

        public IConfigurationRoot Configuration { get; set;  }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            // Add framework services.
            services.AddMvc();
            services.AddSession();
            //services.AddSingleton<IConfiguration>(sp => { return Configuration; });

            services.Configure<AppSettings>(Configuration.GetSection("AppSettings"));



        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
        {
            app.UseStaticFiles();

            loggerFactory.AddConsole(Configuration.GetSection("Logging"));
            loggerFactory.AddDebug();

            app.UseDeveloperExceptionPage();

            app.UseSession();

            app.UseMvc(routes =>
            {
                routes.MapRoute(
                    name: "default",
                    template: "{controller=Home}/{action=Index}/{id?}");
            });

        }
    }`

**Comment by PeerMohamedMydeen** [comment]
Hi MaximRouiler, 

Here is my Startup.cs class. Does the order matter in the http request pipeline ? 

`public class Startup
    {
        public Startup(IHostingEnvironment env)
        {
            var builder = new ConfigurationBuilder()
                .SetBasePath(env.ContentRootPath)
                .AddJsonFile("appsettings.json", optional: true, reloadOnChange: true)
                .AddJsonFile($"appsettings.{env.EnvironmentName}.json", optional: true)
                .AddEnvironmentVariables();
            Configuration = builder.Build();
        }

        

        public IConfigurationRoot Configuration { get; set;  }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            // Add framework services.
            services.AddMvc();
            services.AddSession();
            //services.AddSingleton<IConfiguration>(sp => { return Configuration; });

            services.Configure<AppSettings>(Configuration.GetSection("AppSettings"));



        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
        {
            app.UseStaticFiles();

            loggerFactory.AddConsole(Configuration.GetSection("Logging"));
            loggerFactory.AddDebug();

            app.UseDeveloperExceptionPage();

            app.UseSession();

            app.UseMvc(routes =>
            {
                routes.MapRoute(
                    name: "default",
                    template: "{controller=Home}/{action=Index}/{id?}");
            });

        }
    }`

Main function of Program.CS class as below : 

var host = new WebHostBuilder()
                .UseKestrel()
                .UseContentRoot(Directory.GetCurrentDirectory())
                .UseIISIntegration()
                .UseStartup<Startup>()
                .Build();

            host.Run();


Thanks !

**Comment by MaximRouiller** [comment]
Order matters.

Middlewares are like Russian Dolls. They are chained together and if one requires another one and is not in the right order... it will fail.

On that matter, static files should work for you from what I'm seeing. Let me try it locally.

**Comment by MaximRouiller** [comment]
It does seem to work on my end.

What are your IIS settings?

**Comment by PeerMohamedMydeen** [comment]
Is there any specific IIS Setting you want to investigate ? Artifacts of Exported shared configuration (Adminitration & ApplicationHost) of IIS Server would be of any help for you ? 

Or Site level settings ?

**Comment by MaximRouiller** [comment]
What I'm looking for is how the static files are served. As you can see from your screenshots, the servers are being swapped.

If those are swapping on the same running instance, that means that some requests are being served directly by Kestrel and others go through IIS. 

So I'm talking about Directory Browsing and AppPool configurations. I've never encountered this issue but I'm trying to find something that is off. 😕

**Comment by PeerMohamedMydeen** [comment]
I believe all the requests will be routed to Kestrel through IIS as Kestrel is the raw WebServer for .NET Core and in this case IIS acts as a reverse proxy. Also IIS plays a role in security and infrastructure. So I am not really sure if the servers are being swapped. What I suspect is, the authentication between IIS And Kestrel fails intermittently. 

I tried forwardWindowsAuthToken="false" with windows Authentication disabled and forwardWindowsAuthToken="true" with Windows Authentication enabled  to check if the bad gateway was a result of windows authentication failure. 

Here is my IIS Settings : 

Directory Browsing : Disabled
Authentication : Only Anonymous Authentication enabled
SSL : No SSL. Just HTTP. 

AppPool : 

![apppool](https://cloud.githubusercontent.com/assets/22055341/18376460/099360d6-767d-11e6-9ba6-5b0e87ed0833.PNG)

Web.Config : 

`<aspNetCore processPath="dotnet" arguments=".\MyWeb.Web.dll" stdoutLogEnabled="true" stdoutLogFile=".\logs\stdout" forwardWindowsAuthToken="false" />
`

**Comment by PeerMohamedMydeen** [comment]
Also the Kestrel listens on the default port 5000. I didn't have any override to the default port. 

Do I need to explicitly add the commands to configure the Kestrel and WebListener as below in the project.json ? 

```
"commands": {
    "web": "Microsoft.AspNet.Hosting --server Microsoft.AspNet.Server.Kestrel --server.urls http://localhost:6001",
    "weblistener": "Microsoft.AspNet.Hosting --server WebListener --server.urls http://localhost:6001"
  }
```

**Comment by MaximRouiller** [comment]
We need an MS Employee. We're down the rabbit hole.
