### ISSUE TITLE
Error -4077 ECONNRESET connection reset by peer

### ISSUE THREAD

**Issue by anobaka** [aspnet/Home#1741]
**environment**: 
+ windows 2012 r2
+ IIS8
+ kestrel
+ .net452
+ web application
+ redis distributed cache
+ use session

**exception**:
```
info: Microsoft.AspNetCore.Server.Kestrel[14]
      Connection id "0HKUNP9IK98PK" communication error
      Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvException: Error -4077 ECONNRESET connection reset by peer
```

**<del>reproduction</del>**:
**what I've done and what happend**:
1. publish to production servers and configure the load balance.
2. configure domain forward to the ip of load balance.
3. use some **special** browser to access the website.
4. iis's 502 error page shows.

here's fail request log in iis:
```
MODULE_SET_RESPONSE_ERROR_STATUS

Warning
 ModuleName="AspNetCoreModule", Notification="EXECUTE_REQUEST_HANDLER", HttpStatus="502", HttpReason="Bad Gateway", HttpSubStatus="3", ErrorCode="2147954552", ConfigExceptionInfo="" 
```

It's very strange thing, the exception throwed only when all above conditions are met, and if one of them missed(eg. using local host settings instead of configuring the real domain forward to the ip of the lb, or using other browsers), the website can be accessed successfully.

Please help, some of our users are blocked by this.
Thanks.

**Comment by GuardRex** [comment]
@anobaka Move this over to https://github.com/aspnet/IISIntegration/issues to get more :eyes: on it and close it here.

**Comment by Tratcher** [comment]
Kestrel says IIS closed the connection (though it's unclear when in the request this happened). IIS says Kestrel failed to respond in a timely fashion, which may be why it closed the connection.  How long was the request running before this happened? What was the request trying to do?

**Comment by anobaka** [comment]
The response time is less than 1 second, even than 100 ms, it just responses immediately.
The request is just to access the homepage of website.

You can try this:
1. install `QQBrowser` in IOS 9.3.x.(Chinese version, called "QQ浏览器" in Chinese)
2. access http://ahstest.aihuishou.com in `QQBrowser`.
3. the 502 response shows.

I think there's something wired in the HTTP request. Maybe some **non-ascii characters** in user-agent or other fields. I tried using `urlrewrite` to urlencode user-agent if it's invalid, but it not works. 

I also tried capturing the http request sended by that browser, but when there's a proxy(for capturing the request) between `QQBrwoser` and our website, it accesses the website successfully.

I'm trying using `urlrewrite` to urlencode more http fields if it's invalid. 

Any idea? 
Thanks.

**Comment by Tratcher** [comment]
Use Microsoft Message Analyzer to trace the packets coming into the server and see what the raw header values are.
https://www.microsoft.com/en-us/download/details.aspx?id=44226

**Comment by anobaka** [comment]
[502.tar.gz](https://github.com/aspnet/Home/files/463167/502.tar.gz)
here's the packets.
MessageNumber 28868 & 808129 is the 502 responded request sended by some **special** browser..
MessageNumber 633002 is the 200 responded request sended by other browsers.

**Comment by Tratcher** [comment]
@anobaka glad you found it, is this good to close now?

**Comment by anobaka** [comment]
@Tratcher , of course, thanks for your help.
