### ISSUE TITLE
Discovering controllers

### ISSUE THREAD

**Issue by GAMP** [aspnet/Home#1742]
I am trying to find a way to discover controllers and their routes for creating an API help page.
In WEB Api 2 there was this 

```
var apiExplorer = this.Configuration.Services.GetApiExplorer();
var result = apiExplorer.
               ApiDescriptions.
                GroupBy(api => api.ActionDescriptor.ControllerDescriptor.ControllerName, api => api);
```

This is no longer possible with ASP NET Core. Can someone direct me on what route i should follow?

**Comment by rynowak** [comment]
Resolve the `IApiDescriptionGroupCollectionProvider` service from DI and start from there. The info that exposes is very similar to old API Explorer

https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.ApiExplorer/IApiDescriptionGroupCollectionProvider.cs

**Comment by GAMP** [comment]
Thanks DI did the trick.
