### ISSUE TITLE
The name model does not exist in the current context

### ISSUE THREAD

**Issue by GAMP** [aspnet/Home#1743]
I am trying to create an web page but cannot bind to the model.
Either when editing cshtml file or debugging i get "The name 'model' does not exist in the current context" error

Razor compilation fails once the model is accessed e.g   @foreach (var download in model.Downloads)

I am developing a windows service and hosting with web listener.
Am i missing any configuration in my app.config ?

**Comment by rynowak** [comment]
It's `Model` - notice the capital letter. The directive is `@model`, but the property is `Model`.

**Comment by GAMP** [comment]
Indeed that was clumsy , any reason for intellisence not working ?

**Comment by MaximRouiller** [comment]
@GAMP In which IDE?

**Comment by GAMP** [comment]
Visual Studio 2015.

**Comment by MaximRouiller** [comment]
If you installed ReSharper on another machine (on the same profile) and recently installed this Visual Studio without ReSharper, Intellisense could be disabled. 

Try resetting your settings by going to `Tools > Import and Export Settings...`. Select `Reset all settings` and follow the steps.

**Comment by GAMP** [comment]
I tried resetting but it had no effect. As i said i am working on Windows Service. I have noticed some people reporting a requirement for Razor configuration in Web.Config file. I dont have any Razor specific configuration in my app.config so could it be the case?

**Comment by MaximRouiller** [comment]
I wonder if @NTaylorMullen is aware of such a use case.

**Comment by NTaylorMullen** [comment]
We currently do not provide intellisense for Razor directives (`@model`). Currently have an [issue](https://github.com/aspnet/Tooling/issues/198) tracking that however.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
