### ISSUE TITLE
Wrong Symbol in one example

### ISSUE THREAD

**Issue by nwatley3** [aspnet/Home#1744]
On this page: http://www.asp.net/web-api/overview/advanced/calling-a-web-api-from-a-net-client

In the section titled: Getting a Resource (HTTP GET)
There is the line: Product product = await response.Content.ReadAsAsync>Product>();
It should instead be the line: Product product = await response.Content.ReadAsAsync<Product>();

The greater than sign should be a less than sign before Product.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
