### ISSUE TITLE
ASP.NET Core on .NET Framework 4.6.2 causes FileNotFoundException

### ISSUE THREAD

**Issue by yfakariya** [aspnet/Home#1745]
Hi, 

I found an issu when I tried to run asp.net core application in .NET Framework (desktop CLR).
### Summary

When I run asp.net core app in .NET Framework and uses .net platform standard 1.5 lib, the app fails with "Could not load file or assembly 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies."
### Functional impact

ASP.NET Core apps in .NET Framework 4.6.2 does not work as long as it depends on .NET Standard 1.5 libraries.
### Minimal repro steps
1. Create .net core class library for `netstandard1.5` without any dependencies without `System.Runtime : 4.1.0`.
2. Create "ASP.NET Core Web Application (.NET Framework)", then choose blank app in VS 2015, 
3. Refers the class library created step1 from the asp.net app .
4. In `StartUp.cs`, use any types in the class library.
5. Change `framework` in `project.json` from `net461` to `net462`.
6. Run asp.net app.
### Expected result

A welcome message is shown in the browser.
### Actual result

`FileNotFoundException` for `System.Runtime 4.1.0` is occurred.
### Further technical details

I found that I can avoid this issue when I do one of the following:
- Change the class library's framework from `netstandard1.5` to `netstandard1.4`.
- Or, change asp.net core app's framework from `net462` to `net461`.
- Or, add binding redirect to `app.config` as following:

``` xml
<assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
  <dependentAssembly>
    <assemblyIdentity name="System.Runtime"
                      publicKeyToken="b03f5f7f11d50a3a"
                      culture="neutral" />
    <bindingRedirect oldVersion="4.0.0.0-4.1.0.0"
                     newVersion="4.0.0.0"/>
  </dependentAssembly>
</assemblyBinding>
```

I guess `System.Runtime` is pure facade assembly for .NET Fx 4.6.2 at least, so the third one should work correctly. But I want to know the third is valid from asp.net or corefx people.

Thank you.

**Comment by buybackoff** [comment]
This is really annoying... I have added a dependency that uses `1.1` of `Microsoft.AspNetCore.Http.Features` (Aspnet.Websockets 1.0, BTW why it then uses 1.1 if it is 1.0!?) while another one uses `1.0` (Kestrel 1.0.1). Then this .NET Core project is used from a .NET 451 desktop app, and I need to go one by one over each assembly to fix redirects for all dependencies. Wasting more than an hour on this already, just to realize that I now have to manually check every version of every assembly and add a redirect to App.config of the .NET 451 project for every conflict. With `Microsoft.AspNetCore.Http.Features`  it worked, now more to fix...

Is there a way at least to quickly see all version conflicts and implicit redirects that .NET Core uses?

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
