### ISSUE TITLE
Sharing authentication cookie with subdomain

### ISSUE THREAD

**Issue by ge6a93** [aspnet/Home#1747]
Hi,

I have an ASP.NET Core website and for each registered user I provide a subdomain route: _user1.mysite.com_. The problem is that when the user goes to _mysite.com_ and logs in, they get redirected to _user1.mysite.com_ but it says that the user is not logged in - the authentication cookie is not shared across subdomains. I found this article - [https://docs.asp.net/en/latest/security/data-protection/compatibility/cookie-sharing.html](https://docs.asp.net/en/latest/security/data-protection/compatibility/cookie-sharing.html) but it didn't solve my problem. It shows how to share auth cookies between TWO applications but in my case I have only one application.  

Is there any solution to this problem? I believe I'm not the only one struggling with it. Thanks!

**Comment by Tratcher** [comment]
This issue was moved to aspnet/Security#993
