### ISSUE TITLE
Passsing post data to ExpandoObject partly working

### ISSUE THREAD

**Issue by dbol55** [aspnet/Home#1748]
When passing post data to ExpandoObject, I only recieve post variables name, and not its values (getting null).

```
public IActionResult Post(System.Dynamic.ExpandoObject post)
{
        ...
}
```

However I would strongly prefer if it altogheter would have worked with ordinary **dynamic** data type as in parameter.

**Comment by davidfowl** [comment]
incoming JSON? Form?

**Comment by dbol55** [comment]
Incoming from html form (as post data).

**Comment by davidfowl** [comment]
That's not supported right now. Any reason you need to use dynamic? You can post an `IFormCollection`

**Comment by dbol55** [comment]
Well mainly because I dont want to write a backing model in all scenarios. And also because the other way around (controller to view) already works excellent with dynamic.

Any plans for dynamic model binding in future? I think this would be a huge improvement and would be benifitial to a lot of developers in a lot of scenarios.

**Comment by dbol55** [comment]
FormCollection works great, but still involves to much manual labour and issues with associates ands lists etc.

**Comment by davidfowl** [comment]
> Well mainly because I dont want to write a backing model in all scenarios. And also because the other way around (controller to view) already works excellent with dynamic.

The other way around you basically tell us the shape and we don't have to do any magic to make it work. It's all C#. You returned an (anonymous?) object from the controller and consumed it as a dynamic so you don't need to do any type conversion etc. 

> Any plans for dynamic model binding in future? I think this would be a huge improvement and would be benifitial to a lot of developers in a lot of scenarios.

What do you think would be an improvement? Lets take an example:

```C#
public IActionResult Post(dynamic product)
{
    int product = product.Price;
}
```

Would you expect the following to work?

PS: The performance would also be pretty bad...

**Comment by dbol55** [comment]
I agree C# does the magic controll/view, whereas I would like the asp.net to do the magic view/controller. I also agree on that dynamic has its drawbacks (such as your example), but nowdays it is a part of .net and this is a general issue if not managed properly.

I would like to:
```
public IActionResult Post(var product)
{
    int price = product.Price;
}
```
However I can live with:
`var price = product.Price;`

Improvements?
Do more with less.
Get exact data that you need from a view, without have to handcraft a particular backing model.

Performence?
I have no idea, but I think it would not be that much difference to initiate a backing model from post data, compared to a anonymous type. However these would of course have to be investigated.

**Comment by davidfowl** [comment]
```
public IActionResult Post(var product)
{
    int price = product.Price;
}
```

That's the problem though, you would have to declare it as int and we would have to write code to do the conversion on the fly. When you have types the model binding system can do things like validation. Without those types you can't validate the input because anything is fair game. Is price an int/double/decimal/string? MVC has no idea.


> Improvements?
Do more with less.
Get exact data that you need from a view, without have to handcraft a particular backing model.

At the cost of performance and type safety.

> Performence?
I have no idea, but I think it would not be that much difference to initiate a backing model from post data, compared to a anonymous type. However these would of course have to be investigated.

Not really. It's more efficient to use strongly typed objects. If you want to see the difference, look at the generated code when you use dynamic in ILSpy or Reflector.

**Comment by dbol55** [comment]
Fair enoug, I am still convinced that this is the road ahed later on.

How about some kind of JSON model binding system?

**Comment by davidfowl** [comment]
JSON already works fine. If you're using JSON.NET you can use JObject. That can be used with dynamic.

**Comment by dbol55** [comment]
Ok....

Will the following work if I post a normal form?

```
public IActionResult Post(string json)
{
        //raw json
}
```

Or is it applied such as I have to send json to the controller?

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
