### ISSUE TITLE
Root element missing in creating .net core application using vs

### ISSUE THREAD

**Issue by kstanleyk** [aspnet/Home#1752]
I am unable to create a .net core application using visual studio 2013, update 3. I get an error message indicating that "The project file could not be created. root element missing " and then some path is appended to this error message.

![rem](https://cloud.githubusercontent.com/assets/18107778/18479560/5ee80d0e-79cd-11e6-8eae-53f12fff786c.png)

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
