### ISSUE TITLE
the "announce" link in new "ASP.NET Core 1.0.1 Release Notes" link not relevant to 1.0.1

### ISSUE THREAD

**Issue by arielcloud** [aspnet/Home#1753]
https://github.com/aspnet/Home/releases

link to https://blogs.msdn.microsoft.com/webdev/

where I cant see nothing about 1.0.1

**Comment by Chrissx** [comment]
Hi,

Maybe the article will publish when everything is ready. ( installers etc ) :)

**Comment by MaximRouiller** [comment]
As usual, please wait. There's nuget packages to push, blog post to publish, releases to... well... release. 

All of this on many platforms by many people.

Here's some situation that generates a bug report like this one:

* Nuget Packages are up, no [insert something]
* Release up, no [insert something]
* Blog post up, no [insert something]
* Tooling up to date, no [insert something]
* etc.

It's like this every time there is a release. The word of order is normally: "relax". Things are getting published, copied, deployed, reviewed and will be there soon enough.
