### ISSUE TITLE
Cannot Build RC1 with Visual Studio Team Services Anymore

### ISSUE THREAD

**Issue by eriksendc** [aspnet/Home#1757]
Hi All,

I can no longer build an ASP.NET RC1 project in Visual Studio Team Services. The following resource is no longer available: 

https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.ps1

Way back earlier in the year there used to be content out on the web that described how to build RC1 projects using Visual Studio Team Services (VSTS). The URL to that documentation was https://msdn.microsoft.com/en-us/library/vs/alm/build/azure/deploy-aspnet5 and was titled Build and Deploy your ASP.NET 5 Application to an Azure Web App. (Note that this URL now points to .net core related documentation.) The documentation gave an example for a powershell script that would get things installed so that a build could occur. I've included that script below.

I'm very aware that we could / should move to RTM, but due to the timing of the release of RTM .NET Core and our business goals we are still on RC1 and plan to upgrade in the next month or so. But suddenly being blown out of the water is putting our business at risk. We're supposed to go live in a week!!! Is there any way for things to be put back for a bit longer to keep things working for us?

Desperately seeking your help!

Regards,
Brian Eriksen
eriksendc@yahoo.com
https://getyourpet.com

	Write-Warning "Running Prebuild.ps1"

	# bootstrap DNVM into this session.
	&{$Branch='dev';iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.ps1'))}

	# load up the global.json so we can find the DNX version
	$globalJson = Get-Content -Path $PSScriptRoot\global.json -Raw -ErrorAction Ignore | ConvertFrom-Json -ErrorAction Ignore

	if($globalJson)
	{
		$dnxVersion = $globalJson.sdk.version
	}
	else
	{
		Write-Warning "Unable to locate global.json to determine using 'latest'"
		$dnxVersion = "latest"
	}

	# install DNX
	# only installs the default (x86, clr) runtime of the framework.
	# If you need additional architectures or runtimes you should add additional calls
	# ex: & $env:USERPROFILE\.dnx\bin\dnvm install $dnxVersion -r coreclr
	& $env:USERPROFILE\.dnx\bin\dnvm install $dnxVersion -Persistent

	 # run DNU restore on all project.json files in the src folder including 2>1 to redirect stderr to stdout for badly behaved tools
	Get-ChildItem -Path $PSScriptRoot\src -Filter project.json -Recurse | ForEach-Object { & dnu restore $_.FullName 2>1 }

**Comment by greefeet** [comment]
I have a same problem

**Comment by MaximRouiller** [comment]
Related to https://github.com/aspnet/Home/pull/1754.

**Comment by eriksendc** [comment]
Thanks @MaximRouiller !

**Comment by eriksendc** [comment]
I'll close this one in favor of #1754

**Comment by danroth27** [comment]
To give folks a bit more time to deal with this change I have temporarily added back the dnvm scripts: https://github.com/aspnet/Home/pull/1761

I've also posted an announcement to let folks know that we will remove the dnvm scripts on **Oct 31, 2016**: https://github.com/aspnet/Announcements/issues/205.

Please ensure that your infrastructure has been updated by that date to no longer depend on dnvm from the https://github.com/aspnet/Home repo. We strongly recommend updating to the latest supported release to ensure your applications are running on stable and secure bits.
