### ISSUE TITLE
IdentityOptions - multiple

### ISSUE THREAD

**Issue by dazinator** [aspnet/Home#1759]
My site can be accessed on the following url's:

one.foo.com
two.foo.com
one.bar.com
two.bar.com

I'd like to configure ASP.NET Identity so that a user can navigate from `one.foo.com` to `two.foo.com` and still remain signed in. 
The same goes for `one.bar.com` and `two.bar.com`.

But this means I need to configure multiple `IdentityOptions`, one with a sign in cookie that has a domain `.foo.com` and another with a sign in cookie that has a domain `.bar.com`.

How should I best achieve this?

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
