### ISSUE TITLE
Unable to find views when using convention based routing for areas 

### ISSUE THREAD

**Issue by revbones** [aspnet/Home#1762]
I created a folder named Areas then created a folder named Account inside it.  Then folders in \Areas\Account for Controllers, Models, Views.  Then created an AccountController in \Areas\Account\Controllers.  Then I created a folder named \Account in \Areas\Account\Views.  I then added LoginView.cshtml to \Areas\Account\Views\Account (previously I tried just \Areas\Account\Views)

In AccountController I have the following method:  

``` C#
public IActionResult DisplayLogin()
{
    return View("LoginView");
}
```

(also previously tried return View("LoginView.cshtml"); just to confirm)

In the Configure method of Startup.cs I have:  
  app.UseMvc(ConfigureRoutes);

which calls:

```
private void ConfigureRoutes(IRouteBuilder routeBuilder)
{
    routeBuilder.MapRoute("areaRoute", "{area:exists}/{controller}/{action}");
    routeBuilder.MapRoute("areaRouteWithId", "{area:exists}/{controller}/{action}/{id?}");
    routeBuilder.MapRoute("Default", "{controller=Home}/{action=Index}/{id?}");
}
```

The DisplayLogin method is correctly routed to (doesn't work if you add attribute based routing as well as convention based, but I want to only use convention based anyway).  I set a breakpoint and see DisplayLogin() is called in the AccountController class.  But the following is returned:

An unhandled exception occurred while processing the request.

InvalidOperationException: The view 'LoginView' was not found. The following locations were searched:
 /Views/Account/LoginView.cshtml
 /Views/Shared/LoginView.cshtml

**Comment by pranavkm** [comment]
Do you have a `[Area("Accounts")]` on your `AccountsController`? From the search paths, it looks like the view engine is treating the controller as a non-area controller.

**Comment by revbones** [comment]
I do not currently because as I mentioned I want to use convention based routing and not attribute based.  routing.  As mentioned though, I did try that as well just to check.  

The convention based routing works to the DisplayLogin method on the controller as expected.  It's only the searching for the view that causes the error - after the correct method on the controller is routed to...

**Comment by rynowak** [comment]
`[Area(...)]` is used for conventional routing, MVC needs some way to know what controllers are in which area.

**Comment by revbones** [comment]
So you're saying the attribute is used by both attribute and convention routing?  That's really weird.  If I leave that attribute off, then the DisplayLogin method is appropriately routed to and executed.  THe problem is NOT with the controller's method.  The area routing works without the [Area] attribute.  The problem is finding the view.

Adding that attribute breaks the routing to the DisplayLogin method and it is not executed.

**Comment by pranavkm** [comment]
>  If I leave that attribute off, then the DisplayLogin method is appropriately routed to and executed.

My guess is it's using the non-area route (the `Default` one) to get to your controller. With the `AreaAttribute` in place, it should get to your route via `/Accounts/Account/Home`

**Comment by revbones** [comment]
Restarted and renamed area/controller and things worked.

I will add that it's really weird to have to use attributes at all when using convention based area routing. It also opens up the potential for a rats-nest and difficulty in maintenance/support since you may be troubleshooting something the user is reporting at 

http://mysite.com/myarea/mycontroller/mymethod

but since the controller can have the area specified as an attribute and seem to be able to be located anywhere, whoever is troubleshooting could be pulling out their hair if the controller isn't located in the matching directory/file structure.  This is our problem with attribute based routing.  It sucks for support/maintenance.

**Comment by rynowak** [comment]
If you don't want to do it that way you can wire up your own convention for determining the area - I don't have a sample handy, but you'd want to implement `IControllerModelConvention` with your own class and then register it in `MvcOptions.Conventions`.

**Comment by liuyl1992** [comment]
I execute the dotnet .dll command in the publish file, everything works, but put the publish file on iis or linux jexus, the site is up and running, but some pages get an exception: "Views/XXX/xxx.cshtml" was not found

**Comment by Eilon** [comment]
Closing because this issue is so old that too many things have changed. If anyone is still running into any issues, please log a new issue with details.
