### ISSUE TITLE
Cert revoked of download.microsoft.com

### ISSUE THREAD

**Issue by kennywangjin** [aspnet/Home#1763]
Cert_Revoked when i try to download something from download.microsoft.com.
I can't even install visual studio tools for aspnet core since it has to online download some from the site above.
when i try to manual download components via ie or edge, they show me the error: NET::ERR_CERT_REVOKED.
btw. I am in CHINA. :(. if i disabled cert-check in internet options, it works!
Is it problem of microsoft's certificates or problem of our owns?

**Comment by blowdart** [comment]
This does sound somewhat like a proxy issue, and, given your location, that might be possible. 

The actual cert for download.microsoft.com was issued by the Symantec Class 3 Server Server CA - G4. It runs from 22 May 2016 to 23 May 2017, and has a SHA1 thumbprint of ‎5f 0b 37 e6 33 84 0c a0 24 68 55 2e a3 b1 19 7e 5e 11 8f 7b.

If the certificate you see when you try to browse doesn't match, then, yea, there's someone going on at your end I'm afraid.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
