### ISSUE TITLE
How to test asp.net core built-in Ilogger

### ISSUE THREAD

**Issue by arielcloud** [aspnet/Home#1765]
I want to verify some logs logged. I am using the asp.net core built-in ILogger, and inject it with the asp.net core built-in DI:   

    
private readonly ILogger<InvoiceApi> _logger;
    
    public InvoiceApi(ILogger<InvoiceApi> logger)
    {
        _logger = logger;
    }

then I use it like: `_logger.LogError("error));`

I tried to mock it (with moq) as usual by: 

    MockLogger = new Mock<ILogger<InvoiceApi>>();

and inject this in the service for test by: 
    
    new InvoiceApi(MockLogger.Object);

then tried verify:

    MockLogger.Verify(m => m.LogError(It.Is<string>(s => s.Contains("CreateInvoiceFailed"))));

but it throw: 

> Invalid verify on a non-virtual (overridable in VB) member: m => m.LogError

So, how can I verify this logs logged?

I asked this in SO and the [answer I got](http://stackoverflow.com/a/39606145/3202422) was that I need to wrap the ILogger in my own interface.

But I was sure that the main objective of ILogger is to be the wrapper for logs, so is not it'll be better to do it testable?

thanks

**Comment by pranavkm** [comment]
[`LogError`](https://github.com/aspnet/Logging/blob/1.0.0/src/Microsoft.Extensions.Logging.Abstractions/LoggerExtensions.cs#L273-L281) is an extension method on `ILogger`.  [`ILogger.Log`](https://github.com/aspnet/Logging/blob/1.0.0/src/Microsoft.Extensions.Logging.Abstractions/ILogger.cs#L22) is the method you want to mock.

**Comment by davidfowl** [comment]
Extension methods strike again!
