### ISSUE TITLE
FatalExecutionEngineError after Windows 10 Anniversary Update

### ISSUE THREAD

**Issue by dmarklein** [aspnet/Home#1766]
After installing the Windows 10 Anniversary Update (and re-installing IIS, since the update removed it), we are unable to run our local development websites in IIS 10. 

Now, whenever we attempt to access on our local dev websites through a browser, we see the following:
<img width="613" alt="screen shot 2016-09-22 at 11 14 17 am" src="https://cloud.githubusercontent.com/assets/4107107/18756497/ca4278de-80b5-11e6-83c9-2d0592427c97.png">

In the event log, we see corresponding errors like the following:

> Log Name:      Application
> Source:        Application Error
> Date:          9/22/16 10:57:46 AM
> Event ID:      1000
> Task Category: (100)
> Level:         Error
> Keywords:      Classic
> User:          N/A
> Computer:      DANIELKLEIN232E
> Description:
> Faulting application name: w3wp.exe, version: 10.0.14393.0, time stamp: 0x57899b8a
> Faulting module name: clr.dll, version: 4.6.1586.0, time stamp: 0x575a1507
> Exception code: 0xc0000005
> Fault offset: 0x0000000000099a99
> Faulting process id: 0x1270
> Faulting application start time: 0x01d214ea0ede0a43
> Faulting application path: c:\windows\system32\inetsrv\w3wp.exe
> Faulting module path: C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll
> Report Id: 2b14898a-5bcc-4fb6-a8aa-8fa9fe16f6d2
> Faulting package full name: 
> Faulting package-relative application ID: 
> Event Xml:

Furthermore, I have debugged one of the web sites -- watching in the debugger, we make it through the Application_Start just fine, but then immediately thereafter the exception is thrown. We originally thought this was related to #1583, so we tried installing/repairing .NET Core as well as repairing VS2015, to no avail.

We are at a complete loss -- any help and/or a workaround would be greatly appreciated. Until then, we are all going to roll back to prior to the Anniversary update.

**Comment by pranavkm** [comment]
> watching in the debugger, we make it through the Application_Start just fine

Is this a WebForms\ Mvc 5 application?

**Comment by dmarklein** [comment]
Yes -- our sits use WebForms and MVC5 in conjunction.

**Comment by pranavkm** [comment]
@DamianEdwards where should we track this issue?

**Comment by DamianEdwards** [comment]
Adding @csharpfritz 

Bugs in .NET Framework and ASP.NET can be reported via [MS Connect](https://connect.microsoft.com/). Business support is via [MS Support](https://support.microsoft.com/en-us/gp/contactus81?Audience=Commercial&SegNo=4) and community support (aka free support) is available on the [ASP.NET Forums](https://forums.asp.net/).

See [.NET Platform Support](https://www.microsoft.com/net/support) for more details.
