### ISSUE TITLE
WCF Service unable to .net461 

### ISSUE THREAD

**Issue by mowlali** [aspnet/Home#1767]
WCF Service unable to .net461  , showing .netstandard1.3 not supported in asp.net5

**Comment by davidfowl** [comment]
WCF is not part of .NET Standard nor is it available on .NET Core (the server that is).

**Comment by mowlali** [comment]
Default .net core application does WCF Service will support

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
