### ISSUE TITLE
Html.TextAreaFor validation not executing server-side

### ISSUE THREAD

**Issue by leodeuhh** [aspnet/Home#1768]
Hello,

in my application I use a TextArea that is data bound to a "required" property of my ViewModel.
`@Html.TextAreaFor(r => r.StringValue, new {id = controlId})`
`@Html.ValidationMessageFor(r => r.StringValue)`
The automatic jquery.unobtrusive validation works fine, however after I post a valid form, my ModelState is not valid because these TextArea controls have the ValidationStatus "unvalidated".
I assume this is a bug because I also have TextBoxFor(...) controls on my page, where the server side validation works just fine - it looks like validation is just "missing" these controls.

I would really appreciate a short comment on this issue.

Thanks in advance
Leonard

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
