### ISSUE TITLE
Dns.GetHostAddressesAsync() Error: "Device Not Configured"

### ISSUE THREAD

**Issue by RiZo313** [aspnet/Home#1769]
Hii,
I'm currently developing an ASP .NET Core Application on my mac using VS Code.
I'm trying to send an email using the MailKit and MimeKit packages but i keep receiving an error on GetHostAddressesAsync(), error message: Device not configured. I was told that this might be a bug on Stack Exchange or that i could get guidance here on the configuration steps i might have missed or need to take.

**Comment by Tratcher** [comment]
Please move this to https://github.com/dotnet/corefx
