### ISSUE TITLE
dnu restore fails on Linux VM when building a docker image

### ISSUE THREAD

**Issue by mmeliani** [aspnet/Home#1770]
Hi,
I have problem with starting  project on Linux VM with docker installed, and I'm having difficult time in building image for aspnet. 
here is my project.json : 
{
  "webroot": "wwwroot",
  "version": "1.0.0-*",

  "dependencies": {
    "Microsoft.AspNet.Server.IIS": "1.0.0-rc1-final",
    "Microsoft.AspNet.Server.WebListener": "1.0.0-rc1-final",
    "Microsoft.AspNet.Mvc": "6.0.0-rc1-final",
    "Microsoft.AspNet.Server.Kestrel": "1.0.0-rc1-final"
  },

  "commands": {
    "web": "Microsoft.AspNet.Hosting --server Microsoft.AspNet.Server.WebListener --server.urls http://localhost:5001",
    "kestrel" : "Microsoft.AspNet.Server.Kestrel --server Kestrel --server.urls http://localhost:5004"
  },

  "frameworks": {
    "dnx451": { },
    "dnxcore50": { }
  },

  "publishExclude": [
    "node_modules",
    "bower_components",
    "**.xproj",
    "**.user",
    "**.vspscc"
  ],
  "exclude": [
    "wwwroot",
    "node_modules",
    "bower_components"
  ]
}

And my Dockerfile : 
FROM microsoft/aspnet:1.0.0-rc1-final-coreclr
ADD /src /app
WORKDIR /app
RUN ["dnu", "restore"]
EXPOSE 5004
ENV LASTREFRESH 2015-06-02

the error i get when i start this command ( docker build -t aspnetbase . ) is  : 

Error: FindPackagesById: Microsoft.AspNet.Server.IIS
  HTTP request timed out. Exiting.
Restore failed
A task was canceled.

Feeds used:
    https://api.nuget.org/v3/index.json
The command 'dnu restore' returned a non-zero code: 1

help please !! 
@davidfowl

**Comment by GuardRex** [comment]
No longer supported, see https://github.com/aspnet/Announcements/issues/205.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
