### ISSUE TITLE
how do you bind https to a net core?

### ISSUE THREAD

**Issue by andytejima** [aspnet/Home#1772]
Hi,

Been trying to figure this out, I'm trying to bind https on iis8 to my net core app and i'll get a "404 not found" when I type in the address https://mysite, but it's fine when I just use http://mysite  

I'm hoping someone who ran into this can help.  Thanks so much!

**Comment by Tratcher** [comment]
There's nothing ASP.NET Core specific about IIS https binding.  https://www.digicert.com/util/ssl-certificate-configuration-iis-8.htm

If you turn on application logs do you see the request reaching your site?

**Comment by andytejima** [comment]
Hi,

Thanks for the response,  it's showing it request didn't reach my site base on the logs.  here's a screenshot of the https setting in IIS.

The server I'm using has sites using asp 4.5 with ssl on a shared IP.  Trying to do the same for the net core app.  Does net core need a dedicated ip for ssl to work?

<img width="309" alt="settingsnetcore" src="https://cloud.githubusercontent.com/assets/12262178/18972644/bc695356-8635-11e6-8b06-39e4c2ac97ec.png">

Thanks again!

**Comment by Tratcher** [comment]
Core does not have any special requirements for IIS bindings. If you're getting a 404 then the binding is likely not your issue, something in IIS is handling the request. What does the 404 page look like?

**Comment by andytejima** [comment]
Hi,

Here's the site with https and just http

https 404
<img width="505" alt="https" src="https://cloud.githubusercontent.com/assets/12262178/18973066/8330fae2-8637-11e6-9833-f46431b2da62.png">

http (working)
<img width="541" alt="http" src="https://cloud.githubusercontent.com/assets/12262178/18973074/897681b0-8637-11e6-99f6-10ab3dc04d84.png">

**Comment by Tratcher** [comment]
Ok, that looks like the default IIS 404 page for remote users. If you can access the page from the same machine, or change the custom error settings to return detailed errors you'll be able to see who generated the 404.

**Comment by andytejima** [comment]
Thanks so much Tratcher, I think i found the problem.  I guess I should never set up sites at 3am in the morning without coffee. the cause was the https ip is not the same used in my A record. 

Apologies for the noob error. and thanks so much for helping on this. gonna go sit in the corner for a bit.
