### ISSUE TITLE
hide source code ? 

### ISSUE THREAD

**Issue by Kirua88** [aspnet/Home#1773]
Hi

Is it possible to hide web application source code when we publish it for an install ?
Like we have a web application but it need to be install in every clients like with IIS and not in one server like normal website.
But all source code is visible.

**Comment by davidfowl** [comment]
What version of ASP.NET Core are you using?

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
