### ISSUE TITLE
Package restore fails in VS 2015 

### ISSUE THREAD

**Issue by codingonHP** [aspnet/Home#1775]
I created a brand new ASP NET Core project in VS 2015. The project got created successfully but after that Package restore failed and I am getting following error : 

PATH=.\node_modules.bin;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Web\External;%PATH%;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Web\External\git
C:\Program Files\dotnet\dotnet.exe restore "C:\Users\anandv4\Source\HelloCore.vs\restore.dg"
error: Error reading 'C:\Users\anandv4\Source\HelloCore.vs\restore.dg' at line 0 column 0 : Unexpected character encountered while parsing value: #. Path '', line 0, position 0.
error:   Unexpected character encountered while parsing value: #. Path '', line 0, position 0.

When I ran **dotnet restore** , all packages got restored successfully.
Can you tell me what is wrong in my system/configuration ?

My VS information : 
![image](https://cloud.githubusercontent.com/assets/7105293/19037097/2beac7f0-8992-11e6-883c-183986710396.png)

**Comment by sigmondzavion** [comment]
Same issue here

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
