### ISSUE TITLE
Dependencies node in Solution Explorer for VS2015 .csproj project

### ISSUE THREAD

**Issue by QuantumHive** [aspnet/Home#1780]
[See this unanwsered StackOverflow post.](http://stackoverflow.com/questions/32240365/show-dependencies-manager-in-solution-explorer-for-vs2015)

Is it even possible to enable/show the dependencies node in the Solution Explorer when creating an empty MVC 5 project in VS2015?

I have to note that in [this MSDN](https://msdn.microsoft.com/en-us/magazine/mt573714.aspx) article [Adam Tuliper](https://msdn.microsoft.com/en-us/magazine/mt149362?author=adam+tuliper) is showing us the Dependencies node in [Figure 8](https://i-msdn.sec.s-msft.com/dynimg/IC831374.png), stating:

> Figure 8 shows dependencies from bower.json in Solution Explorer, indicating how Bower is fully integrated into your Web projects and Visual Studio.

It is unclear that if this is a netcore feature only, or also possible for legacy projects.

**Comment by adamtuliper** [comment]
This should work in any Web project. Did you include your bower.json in your project? Is packages.json there?

**Comment by QuantumHive** [comment]
Yes, the `bower.json` and `package.json` are included in the project. Here is how to reproduce:

- Using Visual Studio 2015 Enterprise with Update 3.
- Create a new Project (**File** -> **New** -> **Project**)
- Choose C# - **ASP.NET Web Application (.NET Framework)** with _.NET Framework 4.6.1_ selected
- Press OK
- Add a _New Item_ on the project root and choose **Bower Configuration File** (Note that this only creates `bower.json` and not `.bowerrc` even though it says otherwise in the dialog window, see my [SO post here](http://stackoverflow.com/questions/39932989/visual-studio-2015-add-bower-configuration-file-bug))
- Add a New Item on the project root and choose **npm Configuration File**.
- Manually add a valid [`.bowerrc`](https://bower.io/docs/config/) file, since Visual Studio is not able to. Include it in the project.
- Save the project and restart Visual Studio.

Result:  
![Dependencies node missing] (http://i.imgur.com/V0099tx.png)

**Comment by corte** [comment]
Same problem here.
Just followed the instructions for Angular2 in the official docs and got the same issue:
https://angular.io/docs/ts/latest/cookbook/visual-studio-2015.html
![image](https://cloud.githubusercontent.com/assets/4606160/21177255/9bd56a6c-c1ea-11e6-8ca8-be530f2dfc01.png)

**Comment by thomascmost** [comment]
any further thoughts on this? It would be great to have client Dependencies clearly marked in an MVC app...

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
