### ISSUE TITLE
https exception when using UseBrowserLink extension

### ISSUE THREAD

**Issue by damienbod** [aspnet/Home#1781]
When I start an ASP.NET Core application using HTTPS (develop), I receive to following exception in the browser:

SEC7111: HTTPS security is compromised by http://localhost:28168/2d581390896c4191bba0e7f6b9141a8b/browserLink

The UseBrowserLink extension causes this exception.  Is it possible to use this with HTTPS?

```
if (env.IsDevelopment())
{
	app.UseDeveloperExceptionPage();
	app.UseDatabaseErrorPage();
	// Does not work with HTTPS, browser exception
	//app.UseBrowserLink();
}
```

Greetings Damien

**Comment by Eilon** [comment]
This issue was moved to aspnet/Tooling#830
