### ISSUE TITLE
ASP.NET Core 1.0.1 on Small Business Server 2008

### ISSUE THREAD

**Issue by nicolasr75** [aspnet/Home#1783]
I would like to run an ASP.NET Core 1.0.1 web application on an SBS 2008 SP2 under IIS.

Unfortunately I can't find any information whether this is supported.

I installed the .NET Core Windows Server Hosting package which did install without any error. But I noticed that AspNetCoreModule does not appear in the Modules section in IIS.
I also noticed that this system currently has only .NET 3.5 installed.

Is it possible to run my app on SBS at all and what are the prerequisites?
If it is possible, what would be the correct setting for the _frameworks_ section in project.json.

**Comment by moozzyk** [comment]
You need Windows 2008 R2/Windows 7 or newer. https://docs.asp.net/en/latest/publishing/iis.html?highlight=2008%20R2

**Comment by nicolasr75** [comment]
Thanks for the quick response. I followed exactly that documention but somehow overlooked the supported systems, sorry. What alternatives do I have? I am a little confused by the VS templates
1. ASP.NET Web Application (.NET Framework)
2. ASP.NET Core Web Application (.NET Core)
3. ASP.NET Core Web Application (.NET Framework)
My original plan was using option 2. So, does this mean that I'm stuck with ASP.NET 4?

**Comment by moozzyk** [comment]
I am afraid you will need either to stick with Asp.NET 4.x or move to Windows 2008 R2 or newer.

**Comment by nicolasr75** [comment]
Thanks. Given that SBS2008 support ends somewhere in 2017 and ASP.NET Core is such a nice technology, I would of course go for second option. If only I had to decide that ;-)
