### ISSUE TITLE
Question about Task.Run() 

### ISSUE THREAD

**Issue by hey-red** [aspnet/Home#1784]
Hello everyone!
I see new projects on ASP.NET Core is prefer to use async API(ex. ADO.NET), instead of sync implementations. 
I want to use Task.Run() in my lib(just wrap sync methods), but Task.Run() uses thread pool. 
It's bad for performance with kestrel host?

**Comment by davidfowl** [comment]
TL;DR yes. There's an entire blog post that explains why it's *usually* bad in general.

https://blogs.msdn.microsoft.com/pfxteam/2012/03/24/should-i-expose-asynchronous-wrappers-for-synchronous-methods/

**Comment by hey-red** [comment]
@davidfowl thx for u answer!
I have another little question: ASP.NET Core also uses thread pool for handling requests?

**Comment by halter73** [comment]
> I have another little question: ASP.NET <http://asp.net/> Core also uses
thread pool for handling requests?

Yes.
