### ISSUE TITLE
Using Identity without Migrations

### ISSUE THREAD

**Issue by lucamorelli** [aspnet/Home#1786]
Hi, I have an existing db. I have to add Identity to this db to create a web app, but the db structure will evolve in an indipendent way. 
I would like to use the Identity DbContext for all the app, but I don't find a way to disable migrations, this means I suppose that everytime someone will change the db I'll have problems with the differences, so I would like to disable migrations in this dbContext, creating manually the tables and aligning manually the entity classes when someone changes the db, otherwise I have to create 2 db context, one for Identity and one for all the other activities.
I suppose I cannot use the scaffold command because overwrite everything and I loose every changes I've done to the model classes.
Is it possible to use the `IdentityDbContext` class without Migrations enabled?

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
