### ISSUE TITLE
Output of Web Deploy is garbled

### ISSUE THREAD

**Issue by HADB** [aspnet/Home#1788]
![qq 20161014203913](https://cloud.githubusercontent.com/assets/1836701/19387677/578e24b4-924e-11e6-937d-2b193d626f54.png)

**Comment by vijayrkn** [comment]
This is an issue with Web Deploy (invoking mdeploy.exe on non enu machines). There is already an internal bug tracking this. In the next VS release, VS will be calling the msdeploy apis directly rather than exe, so this issue should be fixed.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
