### ISSUE TITLE
This  is not an issue - Asp.net core support for serve side Javascript for developing web APIs

### ISSUE THREAD

**Issue by smangalath** [aspnet/Home#1794]
Asp.net core support for server side Javascript for developing web APIs

Asp.net core is an awesome step forward from MS, however, it still remains incomplete with out making javascript as a first class language for writing web APi projects. Asp.net core to support it in the similar lines of nodejs-expressjs on the server side with out too much reinventing

Let me know if any additional details needed from my side.
Regards
Suresh Mangalath

**Comment by davidfowl** [comment]
Why not just use nodejs if you want sever side JavaScript?

**Comment by smangalath** [comment]
It is a good point asp.net core can use node engine

Making JavaScript at par with C# and other .Net languages in asp.net code is a good idea

**Comment by smangalath** [comment]
Ask is not for using nodejs but to make JavaScript as first class language like c# with asp.net core

**Comment by simonmurdock** [comment]
Looked at node services by Steve Sanderson?

**Comment by davidfowl** [comment]
@smangalath maybe you can use this https://github.com/paulbartrum/jurassic

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
