### ISSUE TITLE
webapi only return 1 record

### ISSUE THREAD

**Issue by juchunwei** [aspnet/Home#1795]
I don't know what's wrong.  I did the  http get method:

var chks = _context.CheckListForUsers.Include(c => c.CheckList).ToList();
return chks.

I can see there're 3 records, but only shows 1 if I open it with browser or on my client app. 

but if I remove Include(c => c.CheckList), I can get 3 records.

what's wrong?

Thanks,

**Comment by Tratcher** [comment]
If you turn on logging to you see any exceptions logged? This issue may be related: https://github.com/aspnet/Mvc/issues/5413

**Comment by juchunwei** [comment]
@Tratcher, thanks, but could you tell me how to turn on logging?

**Comment by Tratcher** [comment]
Add the console logger: https://docs.asp.net/en/latest/fundamentals/logging.html

Also, if you're using IIS/Express you'll need to enable stdoutLogEnabled in the web.config.
https://docs.asp.net/en/latest/hosting/aspnet-core-module.html
