### ISSUE TITLE
'libuv' not found when running kestrel inside a .net framework 4.5.2 library

### ISSUE THREAD

**Issue by barry-jones** [aspnet/Home#1798]
I have been attempting to start a web server from a .net class library to enable functional testing of a web site. While attempting this I can get the kestrel nuget package and build everything but when the tests run they all fail saying the libuv library can not be found (this is in VS2015 Update 3).

Nuget package is libuv 1.9.0 and Kestrel1.0.1.

I did notice that the libuv library is not copied to the bin directory on build, if I manually copy the file from the packages folder to the bin directory it works without issue. Is this expected or should the file be moved across as it is a requirement for kestrel?

**Comment by davidfowl** [comment]
Are you using a csproj? The existing infrastructure doesn't understand the newer package formats that can declare native (non managed) files in packages. So you have to switch to `project.json` to use it in a first class way. The next round of msbuild integration will work with these types of packages but if you can't change anything, you'll have to resort to copying things manually.

**Comment by barry-jones** [comment]
Hi yeah it's a csproj. Ok, no problem thanks for the confirmation.
