### ISSUE TITLE
Web deploy seems not support migration for Sqlite

### ISSUE THREAD

**Issue by HADB** [aspnet/Home#1799]
I'm using Sqlite and I can't update the database on my server.
I get an error "(Failed to get migration script)" when I click "Preview Migration" in the Web Deploy dialog.
![qq 20161027222252](https://cloud.githubusercontent.com/assets/1836701/19770990/f00a5dee-9c93-11e6-9faf-fa20f2f0609f.png)

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
