### ISSUE TITLE
Deserialize Dictionary using ConfigurationBinder

### ISSUE THREAD

**Issue by sam-wheat** [aspnet/Home#1800]
In json file shown below I need to deserialize Parameters to a dictionary property. Is this possible using ConfigurationBinder as shown in code?  Only first object is deserialized.  When parameters are removed from second object both are deserialized.

```
var endpoints = ConfigurationBinder.Bind<List<EndPointConfigurationTemplate>>(config.GetSection("EndPointConfigurations"));
```

appsettings.json

```
 "EndPointConfigurations": [
    {
      "IsActive": "true",
      "API_Name": "PMData",
      "EndPointType": "InProcess",
      "ConnectionString": "Data Source=...."
    },
    {
      "IsActive": "true",
      "API_Name": "PMData",
      "EndPointType": "REST",
      "ConnectionString": "http://localhost:51513/",
      "Parameters": [
        { "someKey1": "someValue1" },
        { "someKey2": "someValue2" },
        { "someKey3": "someValue3" }
      ]
    }
  ],
```

endpoint.cs

```
public abstract class EndPointConfiguration : IEndPointConfiguration
{
    public string API_Name { get; set; }
    public string ConnectionString { get; set; }
    public Dictionary<string, string> Parameters { get; set; }

    public EndPointConfiguration()
    {
        //Parameters = new Dictionary<string, string>();
    }
}




public class EndPointConfigurationTemplate : EndPointConfiguration
{
    public bool IsActive { get; set; }
    public EndPointType EndPointType { get; set; }
}
```

see also: http://stackoverflow.com/questions/1207731/how-can-i-deserialize-json-to-a-simple-dictionarystring-string-in-asp-net

**Comment by nil4** [comment]
For a similar use case I create the dictionary up-front; the binder then just populates its entries, e.g.:
```csharp
public abstract class EndPointConfiguration {
    public Dictionary<string, string> Parameters { get; } = new Dictionary<string, string();
}
```
This approach has the advantage that you can define the dictionary comparer, to support case insensitive key lookup (i.e. StringComparer.OrdinalIgnoreCase)

**Comment by sam-wheat** [comment]
In my original code created the dictionary in the class constructor.  As shown above I commented it out when I was troubleshooting.  

In both cases the dictionary is not populated.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
