### ISSUE TITLE
Launching a portable app, without command line

### ISSUE THREAD

**Issue by dazinator** [aspnet/Home#1801]
I'd like to build a portable app. This means my build outputs an assembly. If i want to distribute my portable app, my understanding is that it would currently require the end user to open a command line and run a `dotnet run` on the assembly in order to start the application. 

This is no doubt acceptable for end users of my application that are familiar with command line. But for the average commercial end user (non developer) who just wants to launch / run an application - they will expect a nicer way than that. For example, they will expect a shortcut that they can click on to launch the app.

So, for windows users, I'd like to provide this "shortcut" that the user can click on, or can be added to the users start menu, which will launch the portable application. 

1. Does this sound sensible?
2. Are there any examples of this?

I'm now thinking that I'd be better off just compiling per platform and producing the various exe's. Except I like the benefits of portable, compiling the app once is much more streamlined. 

It sounds like what dotnet cli needs to make this story complete, is a universal launcher application (works on all platforms) and a universal "shortcut" format. For example, if building a portable app, spit out not just the assembly, but also some kind of shortcut file (i.e "myapp.core") and then on each of the platforms there was installed, a .net core launcher application associated to open those file types, then the launcher could open the shortcut, and then do an appropriate `dotnet run` to launch the application.. Something like that!

**Comment by davidfowl** [comment]
Can you file this on github.com/dotnet/cli?

**Comment by dazinator** [comment]
Replaced by https://github.com/dotnet/cli/issues/4545
