### ISSUE TITLE
Continuing setting up the initial page causes exception

### ISSUE THREAD

**Issue by Luo-Liang** [aspnet/Home#1802]
I'm running with .net core on Visual Studio. I'm starting up Orchard.CMS.Web project.

When I get pass the setup page, an error in HomepageRoute.GetVirtualPath thrown. The reason is _token is null in : 

    foreach (var entry in _tokens)

I'm not sure why the _token is null.

Now restart the site, and try to continuing setting up again. There will be a different exception thrown. The UpdateShellDescriptorAsync code in ShellDescriptorManager throws.

            if (priorSerialNumber != serialNumber)
            {
                throw new InvalidOperationException("Invalid serial number for shell descriptor");
            }

This can be resolved by deleting the database tables, but then it throws the NullReferenceException in the first step.

When this happens, the httpContext points to home/display/{number}, where {number} increments each time I retry.

The following stacktrace captures this.All these can be 100% reproduced on my machine.

Kindly let me know if there is obvious mistake running it.

<img width="1016" alt="capture" src="https://cloud.githubusercontent.com/assets/1490925/19845152/4100177a-9ef1-11e6-8c8a-3e7fbc801806.PNG">

**Comment by Tratcher** [comment]
@sebastienros?

**Comment by sebastienros** [comment]
@Luo-Liang  Please file Orchard issues on the Orchard repository: https://github.com/OrchardCMS/Orchard2

Thanks

**Comment by Luo-Liang** [comment]
Ah sorry! Too many tabs!
