### ISSUE TITLE
Overwrite/add extra default handlers name in web.config

### ISSUE THREAD

**Issue by TheRealPiotrP** [aspnet/Home#1803]
## Steps to reproduce

Create a ASP.NET core project.
Open web.config.
Change the name of handlers name, in this case the name is changed to "aspNetCore_api":

```xml
<handlers>
      <add name="aspNetCore_api" path="*" verb="*" modules="AspNetCoreModule" resourceType="Unspecified"/>
    </handlers>
```

As this project will be added to IIS/Azure into a sub directory as it owns application, does the name need to be unique.

Run dotnet publish. The tool seems to look for the default name "aspNetCore" and doesn't find it and the it adds add new name for is on a second row. 

```xml
<handlers>
      <add name="aspNetCore_api" path="*" verb="*" modules="AspNetCoreModule" resourceType="Unspecified"/>
<add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModule" resourceType="Unspecified"/>
    </handlers>
```

Publish is done and uploaded to Azure and the website fail to load/run due to that the name "aspNetCore" is not unique.

## Expected  behavior

One would expect that the tool recognize that the name has been changed and doesn't add this second line. Or the tool has an option to opt this out.

## Actual behavior

The web.config should only contain the specified name and not add this extra line with the default name "aspNetCore".

## Environment data

`dotnet --info` output:

.NET Command Line Tools (1.0.0-preview2-003131)

Product Information:
 Version:            1.0.0-preview2-003131
 Commit SHA-1 hash:  635cf40e58

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64

**Comment by piotrpMSFT** [comment]
Moving from https://github.com/dotnet/cli/issues/4246 on behalf of @cjwik

**Comment by Tratcher** [comment]
@moozzyk
@natemcmaster what repo did/will publish IIS end up in?

**Comment by natemcmaster** [comment]
https://github.com/aspnet/websdk cc @vijayrkn

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
