### ISSUE TITLE
Consider disabling compression for tiny responses

### ISSUE THREAD

**Issue by joshlang** [aspnet/Home#1806]
Minor performance tweak...

A 1-byte response of type "text/plain" will get intercepted and gzip'ed. The overhead of compressing a tiny response takes up CPU and likely extra bandwidth.

Sample middleware:

```
app.Run(c =>
{
  c.Response.Headers["Content-Type"] = "text/plain";
  return c.Response.Body.WriteAsync(new byte[] { 65 }, 0, 1);
});
```

This gets transmitted as 'chunked' transfer encoding (even if I set c.Response.Headers["Content-Length"] = "1";) and it gets compressed using gzip

It doesn't happen if the content-type is "application/octet-stream".

Consider disabling compression for responses under a certain size (200 bytes, 500 bytes, 800 bytes, everyone seems to have a different recommendation)

(I first posted this in the corefx repo - oops!  I hope this is the proper place!)

**Comment by Tratcher** [comment]
Are you using the new response compression middleware (https://github.com/aspnet/BasicMiddleware/blob/dev/samples/ResponseCompressionSample/Startup.cs#L34) or just IIS/Express?

**Comment by joshlang** [comment]
IIS/Express - no middleware

**Comment by Tratcher** [comment]
@shirhatti ?

**Comment by joshlang** [comment]
For additional clarity, I'm using 1.0.1, Visual studio 2015, brand new asp.net core (.net core) project, and in Startup.cs:

```
// This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
{
    app.Run(c =>
    {
        c.Response.Headers["Content-Type"] = "text/plain";
        return c.Response.Body.WriteAsync(new byte[] { 65 }, 0, 1);
    });
}
```

And here's the raw response headers (followed by about 120 bytes of gzip data):
```
HTTP/1.1 200 OK
Transfer-Encoding: chunked
Content-Type: text/plain
Content-Encoding: gzip
Vary: Accept-Encoding
Server: Kestrel
X-SourceFiles: =?UTF-8?B?RDpcUHJvamVjdHNcV2ViQXBwbGljYXRpb24xXHNyY1xXZWJBcHBsaWNhdGlvbjE=?=
X-Powered-By: ASP.NET
Date: Wed, 02 Nov 2016 23:08:36 GMT
```

**Comment by Tratcher** [comment]
Yeah, this is unrelated to ASP.NET Core, it's an IIS/Express feature

**Comment by joshlang** [comment]
Ahh, my bad.
