### ISSUE TITLE
Question : Automatic test run on CI builds

### ISSUE THREAD

**Issue by Chrissx** [aspnet/Home#1807]
Hi,

Couple of these ago a tried to integrate my solution ( .NET Core ) with Travis-CI ( KoreBuild ). 
I saw dotnet repositories ( like MVC ) run XUnit tests automatically on builds and I don't any differences on xproj / .travis.yml / project.json side. 

My repository: https://github.com/Chrissx/DotnetCoreWithJavascriptServices

Travis.yml:

    language: csharp
    sudo: required
    dist: trusty
    addons:
    apt:
        packages:
        - gettext
        - libcurl4-openssl-dev
        - libicu-dev
        - libssl-dev
        - libunwind8
        - zlib1g
    env:
    global:
        - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
        - DOTNET_CLI_TELEMETRY_OPTOUT: 1
    mono:
    - 4.0.5
    os:
    - linux
    - osx
    osx_image: xcode7.1
    branches:
    only:
        - master
        - release
        - dev
        - /^(.*\/)?ci-.*$/
    before_install:
    - if test "$TRAVIS_OS_NAME" == "osx"; then brew update; brew install openssl; ln -s /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib /usr/local/lib/; ln -s /usr/local/opt/openssl/lib/libssl.1.0.0.dylib /usr/local/lib/; fi
    - chmod +x build.sh
    script:
    - ./build.sh --quiet verify

My test proj. project.json was:

```
{
  "version": "1.0.0-*",
  "buildOptions": {
    "warningsAsErrors": true
  },
  "dependencies": {
    "dotnet-test-xunit": "2.2.0-*",
    "Moq": "4.6.36-*",
    "xunit": "2.2.0-*"
  },
  "testRunner": "xunit",
  "frameworks": {
    "netcoreapp1.1": {
      "dependencies": {
        "Microsoft.NETCore.App": {
          "version": "1.0.0",
          "type": "platform"
        },
        "System.Diagnostics.TraceSource": "4.3.0-*"
      }
    },
    "net451": {}
  }
}
```

Could you please take a look ? Is there anything that I need to do to make tests discoverable on the build process?

**Comment by pranavkm** [comment]
KoreBuild assumes project to match a specific directory layout. In your case, you might want it to look like

```
/
  /src
    /DotnetCoreWithJavascriptService
    /DotnetCoreWithJavascriptServices.DataAccess
  /test
    /DotnetCoreWithJavascriptServices.DataAccess.Test
```

That said, I really don't recommend using KoreBuild to build your own repos. We very frequently change it to suite our build requirements and have plans to switch to alternate build systems at some point. In the short  term, I'd suggest you pin the version of KoreBuild to the 1.0.0 branch (https://github.com/aspnet/Mvc/blob/1.0.0/build.sh#L5). It's less likely to be modified in a way that'll leave your build broken.

**Comment by Chrissx** [comment]
Thanks the information. 
Is there any tools ( alternate build system ) that you can suggest ? I don't really want to write custom shell script for build/test ( with burnt in project names etc ).
Is this thing will be change when new csproj structure release?

**Comment by pranavkm** [comment]
> Is there any tools ( alternate build system ) that you can suggest ? 

I'm not aware of any tools. For small enough projects, you're probably better off just hammering out a shell script. You don't necessarily have to hardcode names - something like this: https://github.com/structuremap/StructureMap.Microsoft.DependencyInjection/blob/master/build.ps1.

**Comment by Chrissx** [comment]
Ah I see. Thanks!
I will try Cake first If it is not working I will create the script "magic".
