### ISSUE TITLE
String with special character returns "0" in Object type property

### ISSUE THREAD

**Issue by manikandan05** [aspnet/Home#1810]
Hi Folks,

In my project, i have my own component with set of properties. Recently i have updated my project into .NET core. But i got the result differs from MVC but both values were same. I explained my scenario in below.

1. I have the property named as **Value** for my component and its datatype as "**object**" (for receiving any type values)

`<cgf-stu id="12" **cgpa="8/10"** **percentage="80%"**></cgf-stu>`

2. Initially i set the value in a format like "6/12". Its working fine in MVC project but not in .NET Core project.
3. In .NET core it returns the value as "0".  In my case i want to process multiple type of values. 

In another one case, if i trying to set the value "50%" to object datatype property, my project was broken with error.

Could you suggest the solution in ASP.NET Core project, how to receive multiple types of data's in single datatype like as "Object" behavior in MVC project,.

**Comment by davidfowl** [comment]
Show the code

**Comment by manikandan05** [comment]
Hi @davidfowl ,

This is my code 

`<cgf:stu id="12"  cgpa="8/10"  percentage="80%"></cgf:stu>`

**Comment by manikandan05** [comment]
Hi,

i have attached my sample code for my control with property .

`using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Reflection;
using Microsoft.AspNetCore.Razor.TagHelpers;
using Microsoft.AspNetCore.Mvc.ViewFeatures;
using Microsoft.AspNetCore.Html;

namespace cgf.ug.records
{
    

    [HtmlTargetElement("cgf")]
    public class Records : TagHelper
    {
        #region Fields

        
        private object cgpa= null;

        private object percentage = null;        
       
        public override void Process(TagHelperContext context, TagHelperOutput output)
        {            

            base.Process(context, output);
        }

                        
        [DefaultValue(null)]
        [Bindable(true)]
        public Object Value
        {
            get { return this.value; }
            set
            {                
                    //returns the value as "0"  when set the value as "8/10"
                    this.value = value;
            }
        }
        
        [DefaultValue(null)]
        [Browsable(false)]
        public Object percentage
        {
            get { return this.percentage; }
            set { this.percentage = value; }
        }        

    }
}

`

**Comment by davidfowl** [comment]
I believe TagHelpers have special code generation for string properties. Why are you using object for the property types instead of string?

This snippet:

```
<cgf-stu id="12" cgpa="8/10" percentage="80%"></cgf-stu>
```

Basically gets translated into:

```C#
var th = new Records();
th["id"] = "12";
th.Percentage = 80%;   // This is a compilation error
```

If you make percentage a string property, the code generated would look like this:

```C#
var th = new Records();
th["id"] = "12";
th.Percentage = "80%"; // Notice the quotes
```

**Comment by manikandan05** [comment]
Hi @davidfowl ,

Thanks for your detailed information. 

In my application ran perfectly with previous MVC framework (even set integer, string, string with special character). Because in my application sometimes i passed data's from DataBase. I have restored the data's based on my previously working framework. So some data's have "80%" and some more data's define without **%** symbol. 

Finally i need some conclusion from your end. In .NET core framework the Object datatype property was not behave same as previous framework (MVC4, MVC5) version?

If its not supported means, again rollback to my application into MVC framework!

**Comment by davidfowl** [comment]
> In my application ran perfectly with previous MVC framework (even set integer, string, string with special character)

Can you be more specific? What are you comparing tag helpers with? How did it work before?

> Because in my application sometimes i passed data's from DataBase. I have restored the data's based on my previously working framework. So some data's have "80%" and some more data's define without % symbol.

But that's a string right?

> If its not supported means, again rollback to my application into MVC framework!

Not sure what you mean. Tag helpers are a new feature in ASP.NET Core and in this particular case using Object as the property (which is questionable to begin with) doesn't support what you are trying to do. What do you want to do though does work with a string, which is what you should be using.

**Comment by manikandan05** [comment]
Hi @davidfowl ,

Sorry.., for your misunderstanding. I'm a beginner for English language.

I just compared my application result with Razor syntax and Tag Helper syntax.
