### ISSUE TITLE
Ordering Middleware (Central Registry?)

### ISSUE THREAD

**Issue by dazinator** [aspnet/Home#1811]
When writing middleware, it often requires that it be registered at a particular point in the pipeline.

For example (taken from OpenIdDict):

> Add OpenIddict and the OAuth2 token validation middleware in your ASP.NET Core pipeline by calling app.UseOAuthValidation() and app.UseOpenIddict() after app.UseIdentity() and before app.UseMvc():

This is a pain, as if middleware is registered at the wrong location things will not work as expected, but without knowledge of what the middleware is doing it's hard to reason about where it should sit in your application - which means its difficult to treat middleware components as "black boxes of functionality" that you can just "plugin" to your application. Sometimes middleware will also have some complex interactions with other dependendent middleware in the pipeline, interactions that may not be intuitive.

For example, it's not going to be immediately obvious to a future developer reading the startup class, why  `app.UseOpenIddict()` has to go after `app.UseIdentity()` but before `app.UseMvc():`.

Further to this, if your application is extensible, then middleware can often be injected into the pipeline via classes that are outside the `startup` class. So instead of this:

```csharp
 public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
 {
           // register all middleware hear in startup..

           app.UseFoo();
           app.UseBar();
}

```

You end up with this sort of thing:

```csharp
 public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
 {
// dynamically discover middleware from extensions.
            var extensions = DiscoverExtensions();
            foreach (var extension in extensions)
            {
              extension.Configure(app, env, loggerFactory)
            }
}
```

Now the order of middleware is no longer determined at compile time, instead its determined at runtime. This makes it even harder to reason about the order of middleware.

This leads me to the main point.. Is there a way of solving this?

I was thinking what if there was some central "registry" where middleware authors could register their middleware component, including specifying things like:

1. Requirements about other middleware components that it should run "before" in the pipeline.
2. Requirements about other middleware components that it should run "after" in the pipeline.
3. Some sort of priority or rank?

I could then see a more intelligent pipeline, that could utilise this information to attempt to "automatically" order any middleware within it, as it's registered. Ofcourse, you'd never enforce an order (the developer has to be able to override any inferred order).

Just a pie in the sky idea, but thought I'd mention it because this area of asp.net core really grates on me.

**Comment by davidfowl** [comment]
This basically sounds like you're trying to re-invent the IIS pipeline with fixed events which is something that a closed system can do, but not something that we would bake into the framework.

**Comment by dazinator** [comment]
Well not really "fixed" events.. Just a way of allowing middleware to express where it "should ideally" sit relative to other middleware components that may be in the pipeline, not in terms of any fixed / named / known locations. But I take your point this could live outside the framework.. 

I'll have a go at this at some point. Would foresee it as something like:

```
// Registers a middleware component that will attempt to order middleware within it based on middleware preferences..

App.UseOrderedPipeline()

```

Then a custom API to register "ordered" middleware 

```
// If bar middleware is used, 
// Foo middleware be ordered before it.
App.Use<FooMiddleware>().Before<BarMiddleware>()

```


something like this anyway!

**Comment by ShadowDancer** [comment]
@dazinator The beauty of this solution is that you may create such middleware in 30 minutes ;) Go ahead and post on github!

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
