### ISSUE TITLE
dotnet build takes to much time

### ISSUE THREAD

**Issue by 1amirjalai** [aspnet/Home#1812]
after upgrading to asp.net core preview1 dotnet build takes to much time.

i can't find the reason.

**Comment by henkmollema** [comment]
Perhaps #1829 helps?

**Comment by 1amirjalai** [comment]
I removed sdk in global.json but the build time is still more that one minutes and less.

I also noticed while building i get the following dnx log. I'm currently using version 1.1 RTM.

why using dnx task from assembly?

```
Target "CoreCompile" in file "C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Common.Targets" from project "C:\Projects\xxx.xproj" (target "Compile" depends on it):
1>       Using "GetBuildOptions" task from assembly "C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Tasks.dll".
1>       Task "GetBuildOptions"
1>       Done executing task "GetBuildOptions".
1>       ## **Using "Dnx" task from assembly** "C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Tasks.dll".
1>       Task "Dnx"
1>         C:\Program Files\dotnet\dotnet.exe build "C:\Projects\xxxx" —configuration Debug —no-dependencies
1>         Project xxxx (.NETCoreApp,Version=v1.1) will be compiled because inputs were modified
1>         Compiling xxxx for .NETCoreApp,Version=v1.1
```

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
