### ISSUE TITLE
DNS client and custom DNS queries

### ISSUE THREAD

**Issue by MichaCo** [aspnet/Home#1815]
Hi,
I was looking for this for some time now and it seems either the feature is hiding pretty well or is missing.

System.Net has basic name resolution and network information now. But what about a DNS client which can query any kind of DNS server?

I'm currently trying to implement services with the new aspnet core stack. One common scenario with Microservices is service discovery. And one common solution for this is to use DNS.

An example would be to query the consul DNS endpoint for service discovery. And this is not really easily doable today.

There are certain implementations available for the .NET world, but those are pretty basic and mostly not maintained repositories and/or they are not supporting netstandart.

Any plans to add that? Or, if I'm just missing something, any hint? 
Thanks a lot!

:edit if this is not the right place to ask for those kind of features, let me know, too

**Comment by pranavkm** [comment]
https://github.com/dotnet/corefx would be a better place to make this request.
