### ISSUE TITLE
Export template from asp.next web api solution, then create a project use this template failed.

### ISSUE THREAD

**Issue by zongbingwang** [aspnet/Home#1817]
I found that project.json could not be copied to project folder.  So there some errors in References, Object reference not set to an instance of an object.
So, I want to know how could I  fix that issues.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
