### ISSUE TITLE
Error at DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)

### ISSUE THREAD

**Issue by john-luke-laue** [aspnet/Home#1821]
I'm getting an error with a very short stack trace. It occurs when I try to login to my .net core web application. Also, I can't seem to reproduce the error on my development environment. It only occurs on my staging environment. I'm having a hard time finding out where this error is coming from or why it's happening. Does anyone have an idea?

```
at Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)
at Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgery.GetCookieTokenDoesNotThrow(HttpContext httpContext)
```

Not doing anything special in my Login post.

        [AllowAnonymous]
        [HttpPost("/Login")]
        public async Task<IActionResult> Login(LoginModel lm, string returnUrl)
        {
            ViewBag.ReturnUrl = returnUrl;

            var loginResult = await _authManager.SignInAsync(lm.Username, lm.Password);
            if (loginResult.Result == LoginValidationResultType.Ok)
            {
                if (string.IsNullOrWhiteSpace(returnUrl))
                {
                    return Redirect("/ew/default.asp?GroupID=23");
                }
                else
                {
                    return Redirect(returnUrl);
                }
            }
            return View(lm);
        }

Here's my project.json:

```
  "buildOptions": {
    "emitEntryPoint": true,
    "preserveCompilationContext": true,
    "warningsAsErrors": true
  },
    "dependencies": {
      "MyApp.Services": "1.0.0-*",
      "Microsoft.AspNetCore.Diagnostics.Elm": "0.1.0",
      "Microsoft.AspNetCore.Authentication.Cookies": "1.0.0",
      "Microsoft.AspNetCore.Authorization": "1.0.0",
      "Microsoft.AspNetCore.Diagnostics": "1.0.0",
      "Microsoft.AspNetCore.Hosting": "1.0.0",
      "Microsoft.AspNetCore.Hosting.Abstractions": "1.0.0",
      "Microsoft.AspNetCore.Http.Extensions": "1.0.0",
      "Microsoft.AspNetCore.Localization": "1.0.0",
      "Microsoft.AspNetCore.Mvc": "1.0.0",
      "Microsoft.AspNetCore.Routing": "1.0.0",
      "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0",
      "Microsoft.AspNetCore.Server.Kestrel": "1.0.0",
      "Microsoft.AspNetCore.Session": "1.0.0",
      "Microsoft.AspNetCore.StaticFiles": "1.0.0",
      "Microsoft.Extensions.Caching.SqlServer": "1.0.0",
      "Microsoft.Extensions.Logging.Console": "1.0.0",
      "Microsoft.Extensions.Logging.Debug": "1.0.0",
      "Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.0.0",
      "Microsoft.AspNetCore.Razor.Tools": {
        "version": "1.0.0-preview2-final",
        "type": "build"
      },
      "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.0.0",
      "Microsoft.Extensions.Configuration.Json": "1.0.0",
      "Microsoft.Extensions.Logging": "1.0.0",
      "Microsoft.Extensions.Options.ConfigurationExtensions": "1.0.0",
      "Microsoft.DotNet.ProjectModel": "1.0.0-rc4-003206"
    },

  "frameworks": {
    "net461": {}
  },

  "runtimeOptions": {
    "configProperties": {
      "System.GC.Server": true
    }
  },

  "tools": {
    "BundlerMinifier.Core": "2.0.238",
    "Microsoft.AspNetCore.Razor.Tools": "1.0.0-preview2-final",
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.0.0-preview2-final"
  },

  "scripts": {
    "postpublish": "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%"
  }
```

**Comment by john-luke-laue** [comment]
I didn't have AntiForgeryValdiation setup. This seems to have resolved the issue.

```
services.AddMvc(options =>
{
    options.Filters.Add(new AutoValidateAntiforgeryTokenAttribute());
});
```

**Comment by john-luke-laue** [comment]
Actually, setting up AntiForgery did not fix the issue...

**Comment by john-luke-laue** [comment]
I was able to a get a little more information about the error:

HTTP Method: GET 
Exception Message: The antiforgery token could not be decrypted. 

This error was occurring even before I added the AutoValidateAntiforgeryTokenAttribute filter. 
Why would an anti-forgery token need validation on a GET?

**Comment by dougbu** [comment]
@john-luke-laue the `GetCookieTokenDoesNotThrow()` method catches (and logs) all exceptions. What is the impact of the exception you're seeing -- outside debugging sessions?

Separately the `AutoValidateAntiforgeryTokenAuthorizationFilter` is added by default these days. Your addition shouldn't have changed much.

**Comment by john-luke-laue** [comment]
@dougbu other than the log, there seems to be no impact. Seems to continue on gracefully and the /Login page is reached.

**Comment by dougbu** [comment]
The behaviour once we enter the Antiforgery system is as-designed.

But I'm not sure why it appears Antiforgery is used for a GET request. Since the action method quoted in the original description isn't relevant, I'm guessing invoked `Login()` method has an explicit `[ValidateAntiForgeryToken]`. Is that the case?

**Comment by john-luke-laue** [comment]
@dougbu Not the case for me. No `[ValidateAntiForgeryToken]`. Just `[AllowAnonymous]`.

```
[AllowAnonymous]
[HttpGet("/Login", Name = "Login")]
public IActionResult Login(string returnUrl)
{
   //...
}
```

If it's working as expected, and doesn't seem to have an impact, can I safely ignore this error?

**Comment by dougbu** [comment]
> If it's working as expected, and doesn't seem to have an impact, can I safely ignore this error?

Yes, it's safe to ignore catching a first-chance exception in `GetCookieTokenDoesNotThrow()`.

I forgot something earlier: Calling into the Antiforgery system would be normal for the Login view. Must check for existing tokens when generating / reusing tokens for the response.

**Comment by john-luke-laue** [comment]
@dougbu Does this mean that ASP.NET core automatically puts AntiForgery Validation on the Login view?

I'm using app.UseCookieAuthentication and I specify the LoginPath, so I guess that's how it knows where my login view is. Would that make sense?

**Comment by dougbu** [comment]
@john-luke-laue MVC includes antiforgery tokens in generated forms by default. That can be overridden but the templates do not do this.

I'm not sure what you mean in the remainder of your last comment. Suggest they are probably better answered on StackOverflow or through experimentation.

Closing this issue because your original questions are answered.
