### ISSUE TITLE
Issues shutting down site in IIS. An attempt was made to access an exiting process

### ISSUE THREAD

**Issue by mythjuha** [aspnet/Home#1823]
Taking the site down to do a publish causes the site's .exe process to stay hanging in a blocked state. Trying to kill the process with processhacker shows the error 'An attempt was made to access an exiting process'.

This error is discussed in the trouble shooting section of the asp.net core website, how to publish to IIS. But none of 2 reasons shown there are valid for my project

` 
var host = new WebHostBuilder()
.UseKestrel()
.UseContentRoot(Directory.GetCurrentDirectory())
.UseIISIntegration()
.UseStartup<Startup>()
.Build();
host.Run();
`

**Comment by GuardRex** [comment]
@mythjuha Recommend you move this over to the IISIntegration repo: https://github.com/aspnet/IISIntegration/issues

**Comment by mythjuha** [comment]
Made the issue there. This one can be closed.
