### ISSUE TITLE
UseCookieAuthentication bug after upgrading to 1.1

### ISSUE THREAD

**Issue by denisz1** [aspnet/Home#1825]
I've upgraded to the [latest ASP.NET Core 1.1](http://blogs.msdn.microsoft.com/webdev/2016/11/16/announcing-asp-net-core-1-1/). Logging in with cookie auth doesn't work properly.

I'm using attribute routing, so my config doesn't define `routes.MapAreaRoute` and `routes.MapRoute`:

      app.UseMvc();

If the user navigates to a secured action, it redirects to the login action, because of this:

    app.UseCookieAuthentication(new CookieAuthenticationOptions() {
        LoginPath = new PathString("/clients/login"),
        AutomaticChallenge = true,
        AutomaticAuthenticate = true
    });

And my `Account` controller's login action looks like this:

    [HttpGet]
    [AllowAnonymous]
    [Route("/clients/login")]
    public IActionResult Login(string returnUrl = null) { /* ... */ }

So, I expect a request to the secure `/bar` action to redirect to:

    /clients/login?returnUrl=%2Fbar

But it actually redirects to:

    /Account/Login?ReturnUrl=%2Fbar

...which doesn't exist, and so returns a 404.

If I manually navigate to `/clients/login` then it works, but it's supposed to be automatic. And besides, my users don't know to do that.

There is a bug somewhere in the new bits, or, there is a breaking change I don't know about. *Any guidance please?*

**Comment by Tratcher** [comment]
Sounds like you have multiple cookie auth middleware instances in your app. E.g. are you using Identity? That comes with at least two instances of cookie auth.

**Comment by denisz1** [comment]
@Tratcher Yes I am using Identity. This problem started immediately after the upgrade.

What do you think I should do?

**Comment by Tratcher** [comment]
Share your Startup code.

**Comment by denisz1** [comment]
@Tratcher Had to sanitise some of our stuff, so I hope there aren't any typos!



    public void ConfigureServices(IServiceCollection services) {
    
      services.AddOptions();

      services.AddDbContext<EfContext>(
        options => options.UseSqlite(_configuration.GetConnectionString("DefaultConnection")),
        ServiceLifetime.Scoped);

      services
        .AddIdentity<User, IdentityRole>()
        .AddEntityFrameworkStores<EfContext>()
        .AddDefaultTokenProviders();

      services.AddMvc(options => {
        options.Filters.Add(new AuthorizeFilter(new AuthorizationPolicyBuilder().RequireAuthenticatedUser().Build()));
        });

      services.AddRouting(options => options.LowercaseUrls = true);
      }


    public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory) {

      if (env.IsDevelopment()) {
        loggerFactory.AddConsole(Configuration.GetSection("Logging")).AddDebug(LogLevel.Warning);
        app.UseBrowserLink();
        app.UseDatabaseErrorPage();
        app.UseDeveloperExceptionPage();
        }
      else {
        app.UseExceptionHandler("/error");
        }
        
      app.UseStatusCodePagesWithReExecute("/error/{0}");
      app.UseStaticFiles();
      app.UseIdentity();
      
      app.UseCookieAuthentication(new CookieAuthenticationOptions() {
        LoginPath = new PathString("/clients/login"),
        AutomaticChallenge = true,
        AutomaticAuthenticate = true
        });

      app.UseMvc();
    }

**Comment by Tratcher** [comment]
Yeah, you shouldn't need that extra CookieAuth at all, use the one already built into UseIdentity. You can configure its Login path via IdentityOptions.Cookies.ApplicationCookie.LoginPath

https://github.com/aspnet/Templates/blob/dev/src/Rules/StarterWeb/IndividualAuth/Startup.cs

**Comment by denisz1** [comment]
@Tratcher Sorry I'm a little confused, the `app.UseIdentity()` method doesn't have any overloads that take an `IdentityOptions` argument?

**Comment by Tratcher** [comment]
https://github.com/aspnet/Identity/blob/dev/samples/IdentitySample.Mvc/Startup.cs#L50

**Comment by denisz1** [comment]
@Tratcher Okay I see now. I followed the old docs, I guess it changed.

So actually, this is not a bug, but rather a tightening down of something that I shouldn't have been able to do!

Thanks! The 1.1 release looks awesome by the way. Well done to you guys.
