### ISSUE TITLE
Can't load Microsoft.AspNetCore.Hosting 1.1.0.0

### ISSUE THREAD

**Issue by markolbert** [aspnet/Home#1826]
In the course of trying to help the EF Core team verify that a bug I'd run across was fixed in v1.1, I updated a functioning solution to both EF Core 1.1 and AspNet Core 1.1. 

And I really, really, wish I hadn't.

First off, my previously-functioning MVC6 site stopped working, complaining about a version mismatch on Microsoft.Logging.Abstractions (I think it involved not being able to find v1.0.0 of that assembly).

So I figured I'd just revert everything back to where it was before I did the test for the EF Core team. That should fix everything, right?

Wrong.

Now I'm getting the following:

> System.IO.FileLoadException was unhandled
> Message: An unhandled exception of type 'System.IO.FileLoadException' occurred in Unknown Module.
> Additional information: Could not load file or assembly 'Microsoft.AspNetCore.Hosting, Version=1.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
> 

Here's the project.json file for the MVC6 app:

```
{
  "userSecretsId": "aspnet-ConnellCampaigns-ddb1a50a-eba1-4870-91d4-4d26457f64ce",

  "dependencies": {
    "AutoMapper": "5.1.1",
    "BundlerMinifier.Core": "2.2.296",
    "ConnellData": "1.0.0-*",
    "ConnellDataCore": "1.0.0-*",
    "Microsoft.AspNetCore.Authentication.Cookies": "1.0.0",
    "Microsoft.AspNetCore.Diagnostics": "1.0.0",
    "Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore": "1.0.0",
    "Microsoft.AspNetCore.Identity.EntityFrameworkCore": "1.0.0",
    "Microsoft.AspNetCore.Mvc": "1.0.1",
    "Microsoft.AspNetCore.Razor.Tools": {
      "version": "1.0.0-preview2-final",
      "type": "build"
    },
    "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0",
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.1",
    "Microsoft.AspNetCore.StaticFiles": "1.0.0",
    "Microsoft.Azure.WebJobs": "1.1.2",
    "Microsoft.EntityFrameworkCore.SqlServer": "1.0.1",
    "Microsoft.EntityFrameworkCore.SqlServer.Design": "1.0.1",
    "Microsoft.EntityFrameworkCore.Tools": {
      "version": "1.0.0-preview2-final",
      "type": "build"
    },
    "Microsoft.Extensions.Caching.Memory": "1.0.0",
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.0.0",
    "Microsoft.Extensions.Configuration.Json": "1.0.0",
    "Microsoft.Extensions.Configuration.UserSecrets": "1.0.0",
    "Microsoft.Extensions.Logging": "1.0.0",
    "Microsoft.Extensions.Logging.Console": "1.0.0",
    "Microsoft.Extensions.Logging.Debug": "1.0.0",
    "Microsoft.Extensions.Options.ConfigurationExtensions": "1.0.0",
    "Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.0.0",
    "Microsoft.VisualStudio.Web.CodeGeneration.Tools": {
      "version": "1.0.0-preview2-final",
      "type": "build"
    },
    "Microsoft.VisualStudio.Web.CodeGenerators.Mvc": {
      "version": "1.0.0-preview2-final",
      "type": "build"
    },
    "Microsoft.WindowsAzure.ConfigurationManager": "3.2.3",
    "Serilog": "2.3.0",
    "Serilog.Extensions.Logging": "1.2.0",
    "Serilog.Sinks.Literate": "2.0.0",
    "Serilog.Sinks.RollingFile": "3.2.0",
    "UploadFramework": "1.0.0-*",
    "WindowsAzure.Storage": "7.2.1"
  },

  "tools": {
    "BundlerMinifier.Core": "2.0.238",
    "Microsoft.AspNetCore.Razor.Tools": "1.0.0-preview2-final",
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.0.0-preview2-final",
    "Microsoft.EntityFrameworkCore.Tools": "1.0.0-preview2-final",
    "Microsoft.Extensions.SecretManager.Tools": "1.0.0-preview2-final",
    "Microsoft.VisualStudio.Web.CodeGeneration.Tools": {
      "version": "1.0.0-preview2-final",
      "imports": [
        "portable-net45+win8"
      ]
    }
  },

  "frameworks": {
    "net46": {
      "frameworkAssemblies": {
        "System.IO.Compression": "4.0.0.0"
      },
      "dependencies": {
      }
    }
  },

  "buildOptions": {
    "emitEntryPoint": true,
    "preserveCompilationContext": true
  },

  "runtimeOptions": {
    "configProperties": {
      "System.GC.Server": true
    }
  },

  "publishOptions": {
    "include": [
      "wwwroot",
      "Views",
      "Areas/**/Views",
      "appsettings.json",
      "web.config"
    ]
  },

  "scripts": {
    "prepublish": [ "bower install", "dotnet bundle" ],
    "postpublish": [ "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%" ]
  }
}
```

I'd appreciate help in getting me back to my paying work :). Also advice on how to diagnose this kind of problem in the future (other than never, ever, ever offering to test things :)).

**Comment by BrennanConroy** [comment]
In the `bin/<configuration>/<framework>/` folder is a `*.deps.json` which shows the dependencies your project got from restoring and all the references it has. You can navigate that file to see where the 1.1.0 reference to hosting is coming from.

**Comment by pranavkm** [comment]
You might have stray binaries \ app.config in your bin directory. Does wiping the bin directory and rebuilding work?

**Comment by markolbert** [comment]
Thanx, Brennan and Prana, for the quick replies. Brennan, I didn't check out your suggestion because Prana's approach solved the problem. But I'll definitely keep it in mind for the future.

Clearing the bin directory did fix the problem. The app's config file had a lot of references to later versions of assemblies that it shouldn't have contained after I regressed the app. But what confuses me is that I did a "Clean Solution" and Rebuild before asking for help, because I've seen similar problems caused by cruft. I thought "Clean Solution" wiped out the contents of the bin directory...but it didn't in this case (I checked). I had to delete the directory contents manually. Apparently, the behavior of Clean changed somewhere along the way.

**Comment by nemenos** [comment]
I think this is similar to #1824, but for me wiping the bin folder or deleting nuget cache didn't solve the issue.

**Comment by larini** [comment]
Nothing works for me. I removed entire project, published again, but still receive the error: Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.AspNetCore.Hosting, Version=1.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.

**Comment by larini** [comment]
Solved. It was missing "Microsoft.AspNetCore.Server.Kestrel": "1.1.0", in my project.json file.
In 1.0.1 it was optional, but now it´s required.

**Comment by guybartal** [comment]
I have the same error when publishing to azure web apps, 


> Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'Microsoft.AspNetCore.Hosting, Version=1.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)


Is using "Microsoft.AspNetCore.Server.Kestrel": "1.1.0" package a good solution for asp.net core 1.0?

here's my project.json:

```
{
  "buildOptions": {
    "emitEntryPoint": true,
    "preserveCompilationContext": true
  },
  "dependencies": {
    "Microsoft.ApplicationInsights.AspNetCore": "1.0.2",
    "Microsoft.AspNetCore.Authentication.Cookies": "1.0.0",
    "Microsoft.AspNetCore.Authentication.OpenIdConnect": "1.0.0",
    "Microsoft.AspNetCore.Authorization": "1.0.0",
    "Microsoft.AspNetCore.Diagnostics": "1.0.0",
    "Microsoft.AspNetCore.Mvc": "1.0.1",
    "Microsoft.AspNetCore.Mvc.Core": "1.0.1",
    "Microsoft.AspNetCore.Mvc.TagHelpers": "1.0.1",
    "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0",
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.1",
    "Microsoft.AspNetCore.StaticFiles": "1.0.0",
    "Microsoft.EntityFrameworkCore.Design": "1.0.1",
    "Microsoft.EntityFrameworkCore.SqlServer": "1.0.1",
    "Microsoft.EntityFrameworkCore.Tools": "1.0.0-preview3-final",
    "Microsoft.Extensions.Configuration.Binder": "1.1.0",
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.1.0",
    "Microsoft.Extensions.Configuration.FileExtensions": "1.1.0",
    "Microsoft.Extensions.Configuration.Json": "1.0.0",
    "Microsoft.Extensions.Logging": "1.0.0",
    "Microsoft.Extensions.Logging.Console": "1.0.0",
    "Microsoft.Extensions.Logging.Debug": "1.0.0",
    "Microsoft.IdentityModel.Protocols.OpenIdConnect": "2.1.0",
    "Microsoft.NETCore.App": "1.0.1",
    "Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.1.0",
    "Newtonsoft.Json": "9.0.2-beta1",
    "WindowsAzure.Storage": "7.2.1"
  },
  "frameworks": {
    "netcoreapp1.0": {
      "imports": [
        "dotnet5.6",
        "portable-net45+win8"
      ]
    }
  },
  "publishOptions": {
    "include": [
      "wwwroot",
      "Views",
      "web.config",
      "appsettings.json",
      "appsettings.*.json",
      "LICENSE.txt"
    ]
  },
  "runtimeOptions": {
    "gcServer": true
  },
  "runtimes": {
    "win10-x64": {},
    "win7-x64": {}
  },
  "scripts": {
    //"prepublish": [ "npm install", "npm recompileapp" ],
    "postpublish": [ "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%" ]
  },
  "tools": {
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.0.0-preview2-final",
    "Microsoft.EntityFrameworkCore.Tools": {
      "version": "1.0.0-preview2-final",
      "type": "platform",
      "imports": [
        "portable-net45+win8+dnxcore50",
        "portable-net45+win8"
      ]

    }
  }
}

```

**Comment by Tratcher** [comment]
@guybartal don't mix 1.1 and 1.0 packages, update everything to 1.1.

**Comment by guybartal** [comment]
@Tratcher  I want to, but I need "WindowsAzure.Storage" which is not compatible with 1.1 yet. any recommendations?

why azure web app expecting Microsoft.AspNetCore.Hosting, Version=1.1.0.0 if all my packages are 1.0?

**Comment by Tratcher** [comment]
Downgrade your Microsoft.Extensions packages to 1.0 then. Microsoft.Extensions and Microsoft.AspNetCore version together.

**Comment by guybartal** [comment]
@Tratcher 
oops,  I missed that somehow, 
i've just tried downgrading Microsoft.Extensions packages to 1.0.1  and even 1.0.0 on all packages, but still got the same error (only on azure web app).
here's my current project.json, what am I missing now?:


```
{
  "buildOptions": {
    "emitEntryPoint": true,
    "preserveCompilationContext": true
  },
  "dependencies": {
    "Microsoft.ApplicationInsights.AspNetCore": "1.0.0",
    "Microsoft.AspNetCore.Authentication.Cookies": "1.0.0",
    "Microsoft.AspNetCore.Authentication.OpenIdConnect": "1.0.0",
    "Microsoft.AspNetCore.Authorization": "1.0.0",
    "Microsoft.AspNetCore.Diagnostics": "1.0.0",
    "Microsoft.AspNetCore.Mvc": "1.0.0",
    "Microsoft.AspNetCore.Mvc.Core": "1.0.0",
    "Microsoft.AspNetCore.Mvc.TagHelpers": "1.0.0",
    "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0",
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.0",
    "Microsoft.AspNetCore.StaticFiles": "1.0.0",
    "Microsoft.EntityFrameworkCore.SqlServer": "1.0.0",
    "Microsoft.Extensions.Configuration.Binder": "1.0.0",
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.0.0",
    "Microsoft.Extensions.Configuration.FileExtensions": "1.0.0",
    "Microsoft.Extensions.Configuration.Json": "1.0.0",
    "Microsoft.Extensions.Logging": "1.0.0",
    "Microsoft.Extensions.Logging.Console": "1.0.0",
    "Microsoft.Extensions.Logging.Debug": "1.0.0",
    "Microsoft.IdentityModel.Protocols.OpenIdConnect": "2.0.0",
    "Microsoft.NETCore.App": "1.0.0",
    "Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.1.0",
    "Newtonsoft.Json": "9.0.1",
    "WindowsAzure.Storage": "7.2.1"
  },
  "frameworks": {
    "netcoreapp1.0": {
      "imports": [
        "dotnet5.6",
        "portable-net45+win8"
      ]
    }
  },
  "publishOptions": {
    "include": [
      "wwwroot",
      "Views",
      "web.config",
      "appsettings.json",
      "appsettings.*.json",
      "LICENSE.txt"
    ]
  },
  "runtimeOptions": {
    "gcServer": true
  },
  "runtimes": {
    "win10-x64": {},
    "win7-x64": {}
  },
  "scripts": {
    //"prepublish": [ "npm install", "npm recompileapp" ],
    "postpublish": [ "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%" ]
  },
  "tools": {
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.0.0-preview2-final",
  }
}

```

**Comment by guybartal** [comment]
SOLVED!
created new asp.net core app and copy it's project.json missing parts,
I think what fixed it was missing "type": "platform" on "Microsoft.NETCore.App"
thank you for your time @Tratcher !

```
{

  "dependencies": {
    "Microsoft.NETCore.App": {
      "version": "1.0.1",
      "type": "platform"
    },
    "Microsoft.AspNetCore.Razor.Tools": {
      "version": "1.0.0-preview2-final",
      "type": "build"
    },
    "Microsoft.ApplicationInsights.AspNetCore": "1.0.0",
    "Microsoft.AspNetCore.Authentication.Cookies": "1.0.0",
    "Microsoft.AspNetCore.Authentication.OpenIdConnect": "1.0.0",
    "Microsoft.AspNetCore.Authorization": "1.0.0",
    "Microsoft.AspNetCore.Diagnostics": "1.0.0",
    "Microsoft.AspNetCore.Mvc": "1.0.0",
    "Microsoft.AspNetCore.Mvc.Core": "1.0.0",
    "Microsoft.AspNetCore.Mvc.TagHelpers": "1.0.0",
    "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0",
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.0",
    "Microsoft.AspNetCore.StaticFiles": "1.0.0",
    "Microsoft.EntityFrameworkCore.SqlServer": "1.0.0",
    "Microsoft.Extensions.Configuration.Binder": "1.0.0",
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.0.0",
    "Microsoft.Extensions.Configuration.FileExtensions": "1.0.0",
    "Microsoft.Extensions.Configuration.Json": "1.0.0",
    "Microsoft.Extensions.Logging": "1.0.0",
    "Microsoft.Extensions.Logging.Console": "1.0.0",
    "Microsoft.Extensions.Logging.Debug": "1.0.0",
    "Microsoft.IdentityModel.Protocols.OpenIdConnect": "2.0.0",
    "Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.0.0",
    "Newtonsoft.Json": "9.0.1",
    "WindowsAzure.Storage": "7.2.1"
  },
  "frameworks": {
    "netcoreapp1.0": {
      "imports": [
        "dotnet5.6",
        "portable-net45+win8"
      ]
    }
  },
  "publishOptions": {
    "include": [
      "wwwroot",
      "Views",
      "web.config",
      "appsettings.json",
      "appsettings.*.json",
      "LICENSE.txt"
    ]
  },
  "buildOptions": {
    "emitEntryPoint": true,
    "preserveCompilationContext": true
  },

  "runtimeOptions": {
    "configProperties": {
      "System.GC.Server": true
    }
  },
  "runtimes": {
    "win10-x64": {},
    "win7-x64": {}
  },
  "scripts": {
    //"prepublish": [ "npm install", "npm recompileapp" ],
    "postpublish": [ "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%" ]
  },
  "tools": {
    "BundlerMinifier.Core": "2.0.238",
    "Microsoft.AspNetCore.Razor.Tools": "1.0.0-preview2-final",
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.0.0-preview2-final"
  }
}

```

**Comment by hikalkan** [comment]
I had the similar problem for Microsoft.AspNetCore.Http.Features package and I fixed it by adding assembly redirect into app.config:

````xml
     <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
       <dependentAssembly>
         <assemblyIdentity name="Microsoft.AspNetCore.Http.Features" publicKeyToken="adb9793829ddae60" culture="neutral" />
         <bindingRedirect oldVersion="1.0.0.0" newVersion="1.1.0.0" />
       </dependentAssembly>
     </assemblyBinding>
````

**Comment by zarinbal** [comment]
Re: hikalkan 
I had the same issue with Microsoft.AspNetCore.Http.Features.
I resolved it by Microsoft.VisualStudio.Web.BrowserLink.Loader v14.1.0  with 
Microsoft.VisualStudio.Web.BrowserLink v1.0.0

I started using VS 2017 RC. The default template of ASP.NET MVC Core was working initially. This problem occurred to me after upgrading all packages to Core 1.1.0
It seems that the Web.BrowserLink.Loader v14.1.0 (May be other packages)  uses an old reference to old Features 1.0

**Comment by hikalkan** [comment]
@zarinbal 
It's interesting that there are two packages. And also https://www.nuget.org/packages/Microsoft.VisualStudio.Web.BrowserLink download count is just 131 :)
Does anyone know why there are two packages and which one we should use?

**Comment by F1oyd** [comment]
These steps helped me as well:
1. Clear `bin` folder
2. Remove `project.lock.json` file

**Comment by douglasncon** [comment]
For whom still getting the Microsoft.AspNetCore.Http.Features /  Microsoft.AspNetCore.Server.Kestrel[13] error below, on VS 2015. 

![image](https://cloud.githubusercontent.com/assets/20860629/22150755/f6c40026-df01-11e6-9c5a-b65f3e290476.png)

Try uncheck "Enable Browser Link" at visual studio and set UseBrowserLink() on Startup.cs. 

![image](https://cloud.githubusercontent.com/assets/20860629/22150790/2444e8e4-df02-11e6-808b-d8f984e61c80.png)


You will need also reference "Microsoft.VisualStudio.Web.BrowserLink.Loader" at project.json.

That's works for me, probably is a Visual Studio issue.

**Comment by jaider** [comment]
https://github.com/IdentityServer/IdentityServer4/issues/703
Comment out `app.AddBrowserLink()` works for me!

**Comment by sk29110** [comment]
I had similar issue but it started working by deleting bin folder.

But don't know why it started working. I have my app running initially but when I switched to different app and switch back to the app then it stopped working. Whenever I started debugging and it crashed with the exception at the program.cs said "Can't load Microsoft.AspNetCore.Hosting 1.1.0.0"

**Comment by imkheong** [comment]
I have a new web project created with full .NET framework in Visual Studio 2017 using the setup below:

1. ASP.NET Core Web Application (.NET Framework) - WebProject1
2. xUnit Test Project (.NET Core) - IntegrationTest1

Full project source code is available at [GitHub](https://github.com/imkheong/asp.net-core-web-integration-test).

Further configuration:
1. Modify XUnitTestProject1 to use net451 using Edit csproj.
2. Add TestHost.
3. Run integration test.
4. Test fail when initiating new TestServerFixture();

The error is as follow:
System.IO.FileLoadException: 'Could not load file or assembly 'Microsoft.AspNetCore.Hosting.Abstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)'

<img width="422" alt="devenv_2017-07-10_18-14-31" src="https://user-images.githubusercontent.com/6950029/28013554-00ca485c-659c-11e7-9ab4-8f1f9b48e946.png">

Anyone has an idea how can I fix it?

**Comment by jmatthewsr-ms** [comment]
@imkheong I had the same issue (targeting net46). I started a new core project, added a unit test project, change both projects to net46 and had to do the following to enable AspNetCore.TestHost: https://github.com/aspnet/Hosting/issues/926

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
