### ISSUE TITLE
IIS Express will not run after upgrade to v1.1

### ISSUE THREAD

**Issue by dstep2007** [aspnet/Home#1827]
I've upgraded my project.json to use the new v1.1 of asp.net core and now when I try to start IIS Express to debug, I get the following errors:

The program '[8784] dotnet.exe' has exited with code -2147450749 (0x80008083).
The program '[7352] iisexpress.exe' has exited with code 0 (0x0).

My upgraded project.json:

```
"dependencies": {
    "Microsoft.NETCore.App": {
      "version": "1.1.0",
      "type": "platform"
    },
    "Microsoft.ApplicationInsights.AspNetCore": "1.0.0",
    "Microsoft.AspNetCore.Mvc": "1.0.1",
    "Microsoft.AspNetCore.Routing": "1.0.1",
    "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0",
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.1",
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.0.0",
    "Microsoft.Extensions.Configuration.FileExtensions": "1.0.0",
    "Microsoft.Extensions.Configuration.Json": "1.0.0",
    "Microsoft.Extensions.Logging": "1.0.0",
    "Microsoft.Extensions.Logging.Console": "1.0.0",
    "Microsoft.Extensions.Logging.Debug": "1.0.0",
    "Microsoft.Extensions.Options.ConfigurationExtensions": "1.0.0",
    "Microsoft.IdentityModel.Tokens": "5.0.0",
    "Microsoft.AspNetCore.Authentication": "1.0.0",
    "Microsoft.AspNetCore.Authentication.JwtBearer": "1.0.0",
    "Microsoft.AspNetCore.Authentication.Cookies": "1.0.0",
    "Microsoft.AspNetCore.Identity.EntityFrameworkCore": "1.0.0",
    "Microsoft.EntityFrameworkCore": "1.1.0",
    "Microsoft.EntityFrameworkCore.Tools": "1.0.0-preview2-final",
    "SapientGuardian.EntityFrameworkCore.MySql": "7.1.10",
    "AutoMapper": "5.1.1"
  },

  "tools": {
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.0.0-preview2-final"
  },

  "frameworks": {
    "netcoreapp1.1": {
      "imports": [
        "dotnet5.6",
        "portable-net45+win8"
      ]
    }
  },
```

Maybe I am missing something in my project.json needed for the upgrade?  Or one of the packages is not cooperating with v1.1?  Any help is appreciated.

NOTE: When I change back to 1.0 everything runs fine.

**Comment by pranavkm** [comment]
Do you have the .NET Core 1.1.0 SDK installed - https://www.microsoft.com/net/download/core? Running it from the command line might tell what's wrong too. Run `dotnet run` to see what's causing dotnet to fail.

Also, you have a mix of LTS and 1.1.0 bits in your application (for instance `Microsoft.AspNetCore.Identity.EntityFrameworkCore` 1.0.0 and `Microsoft.EntityFrameworkCore` 1.1.0) which isn't something we test for as part of our verification. I'd recommend switching the lot to 1.1.0 if you do want to use our 1.1.0 bits. Gleaning off of our released packages, here's the Ids and versions that were released as part of Asp.Net Core 1.1.0:

|  Id                                        | Version |
| ------------------------------------------ | ----- |
| Microsoft.AspNet.Identity.AspNetCoreCompat | 0.2.0 |
| Microsoft.AspNetCore | 1.1.0 |
| Microsoft.AspNetCore.Antiforgery | 1.1.0 |
| Microsoft.AspNetCore.Authentication | 1.1.0 |
| Microsoft.AspNetCore.Authentication.Cookies | 1.1.0 |
| Microsoft.AspNetCore.Authentication.Facebook | 1.1.0 |
| Microsoft.AspNetCore.Authentication.Google | 1.1.0 |
| Microsoft.AspNetCore.Authentication.JwtBearer | 1.1.0 |
| Microsoft.AspNetCore.Authentication.MicrosoftAccount | 1.1.0 |
| Microsoft.AspNetCore.Authentication.OAuth | 1.1.0 |
| Microsoft.AspNetCore.Authentication.OpenIdConnect | 1.1.0 |
| Microsoft.AspNetCore.Authentication.Twitter | 1.1.0 |
| Microsoft.AspNetCore.Authorization | 1.1.0 |
| Microsoft.AspNetCore.AzureAppServicesIntegration | 1.0.0 |
| Microsoft.AspNetCore.Buffering | 0.2.0 |
| Microsoft.AspNetCore.CookiePolicy | 1.1.0 |
| Microsoft.AspNetCore.Cors | 1.1.0 |
| Microsoft.AspNetCore.Cryptography.Internal | 1.1.0 |
| Microsoft.AspNetCore.Cryptography.KeyDerivation | 1.1.0 |
| Microsoft.AspNetCore.DataProtection | 1.1.0 |
| Microsoft.AspNetCore.DataProtection.Abstractions | 1.1.0 |
| Microsoft.AspNetCore.DataProtection.AzureStorage | 1.0.0 |
| Microsoft.AspNetCore.DataProtection.Extensions | 1.1.0 |
| Microsoft.AspNetCore.DataProtection.Redis | 0.1.0 |
| Microsoft.AspNetCore.DataProtection.SystemWeb | 1.1.0 |
| Microsoft.AspNetCore.Diagnostics | 1.1.0 |
| Microsoft.AspNetCore.Diagnostics.Abstractions | 1.1.0 |
| Microsoft.AspNetCore.Diagnostics.Elm | 0.2.0 |
| Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore | 1.1.0 |
| Microsoft.AspNetCore.Hosting | 1.1.0 |
| Microsoft.AspNetCore.Hosting.Abstractions | 1.1.0 |
| Microsoft.AspNetCore.Hosting.Server.Abstractions | 1.1.0 |
| Microsoft.AspNetCore.Hosting.WindowsServices | 1.1.0 |
| Microsoft.AspNetCore.Html.Abstractions | 1.1.0 |
| Microsoft.AspNetCore.Http | 1.1.0 |
| Microsoft.AspNetCore.Http.Abstractions | 1.1.0 |
| Microsoft.AspNetCore.Http.Extensions | 1.1.0 |
| Microsoft.AspNetCore.Http.Features | 1.1.0 |
| Microsoft.AspNetCore.HttpOverrides | 1.1.0 |
| Microsoft.AspNetCore.Identity | 1.1.0 |
| Microsoft.AspNetCore.Identity.EntityFrameworkCore | 1.1.0 |
| Microsoft.AspNetCore.JsonPatch | 1.1.0 |
| Microsoft.AspNetCore.Localization | 1.1.0 |
| Microsoft.AspNetCore.Localization.Routing | 1.1.0 |
| Microsoft.AspNetCore.MiddlewareAnalysis | 1.1.0 |
| Microsoft.AspNetCore.Mvc | 1.1.0 |
| Microsoft.AspNetCore.Mvc.Abstractions | 1.1.0 |
| Microsoft.AspNetCore.Mvc.ApiExplorer | 1.1.0 |
| Microsoft.AspNetCore.Mvc.Core | 1.1.0 |
| Microsoft.AspNetCore.Mvc.Cors | 1.1.0 |
| Microsoft.AspNetCore.Mvc.DataAnnotations | 1.1.0 |
| Microsoft.AspNetCore.Mvc.Formatters.Json | 1.1.0 |
| Microsoft.AspNetCore.Mvc.Formatters.Xml | 1.1.0 |
| Microsoft.AspNetCore.Mvc.Localization | 1.1.0 |
| Microsoft.AspNetCore.Mvc.Razor | 1.1.0 |
| Microsoft.AspNetCore.Mvc.Razor.Host | 1.1.0 |
| Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.Design | 1.1.0-preview4-final |
| Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.Tools | 1.1.0-preview4-final |
| Microsoft.AspNetCore.Mvc.TagHelpers | 1.1.0 |
| Microsoft.AspNetCore.Mvc.ViewFeatures | 1.1.0 |
| Microsoft.AspNetCore.Mvc.WebApiCompatShim | 1.1.0 |
| Microsoft.AspNetCore.Owin | 1.1.0 |
| Microsoft.AspNetCore.Proxy | 0.2.0 |
| Microsoft.AspNetCore.Razor | 1.1.0 |
| Microsoft.AspNetCore.Razor.Design | 1.1.0-preview4-final |
| Microsoft.AspNetCore.Razor.Runtime | 1.1.0 |
| Microsoft.AspNetCore.Razor.Tools | 1.1.0-preview4-final |
| Microsoft.AspNetCore.ResponseCaching | 1.1.0 |
| Microsoft.AspNetCore.ResponseCaching.Abstractions | 1.1.0 |
| Microsoft.AspNetCore.ResponseCompression | 1.0.0 |
| Microsoft.AspNetCore.Rewrite | 1.0.0 |
| Microsoft.AspNetCore.Routing | 1.1.0 |
| Microsoft.AspNetCore.Routing.Abstractions | 1.1.0 |
| Microsoft.AspNetCore.Server.IISIntegration | 1.1.0 |
| Microsoft.AspNetCore.Server.IISIntegration.Tools | 1.1.0-preview4-final |
| Microsoft.AspNetCore.Server.Kestrel | 1.1.0 |
| Microsoft.AspNetCore.Server.Kestrel.Https | 1.1.0 |
| Microsoft.AspNetCore.Server.WebListener | 1.1.0 |
| Microsoft.AspNetCore.Session | 1.1.0 |
| Microsoft.AspNetCore.StaticFiles | 1.1.0 |
| Microsoft.AspNetCore.TestHost | 1.1.0 |
| Microsoft.AspNetCore.WebSockets | 1.0.0 |
| Microsoft.AspNetCore.WebUtilities | 1.1.0 |
| Microsoft.Data.Sqlite | 1.1.0 |
| Microsoft.DotNet.Watcher.Tools | 1.1.0-preview4-final |
| Microsoft.EntityFrameworkCore | 1.1.0 |
| Microsoft.EntityFrameworkCore.Design | 1.1.0 |
| Microsoft.EntityFrameworkCore.InMemory | 1.1.0 |
| Microsoft.EntityFrameworkCore.Relational | 1.1.0 |
| Microsoft.EntityFrameworkCore.Relational.Design | 1.1.0 |
| Microsoft.EntityFrameworkCore.Relational.Design.Specification.Tests | 1.1.0 |
| Microsoft.EntityFrameworkCore.Relational.Specification.Tests | 1.1.0 |
| Microsoft.EntityFrameworkCore.Specification.Tests | 1.1.0 |
| Microsoft.EntityFrameworkCore.Sqlite | 1.1.0 |
| Microsoft.EntityFrameworkCore.Sqlite.Design | 1.1.0 |
| Microsoft.EntityFrameworkCore.SqlServer | 1.1.0 |
| Microsoft.EntityFrameworkCore.SqlServer.Design | 1.1.0 |
| Microsoft.EntityFrameworkCore.Tools | 1.1.0-preview4-final |
| Microsoft.EntityFrameworkCore.Tools.DotNet | 1.1.0-preview4-final |
| Microsoft.Extensions.Caching.Abstractions | 1.1.0 |
| Microsoft.Extensions.Caching.Memory | 1.1.0 |
| Microsoft.Extensions.Caching.Redis | 1.1.0 |
| Microsoft.Extensions.Caching.SqlConfig.Tools | 1.1.0-preview4-final |
| Microsoft.Extensions.Caching.SqlServer | 1.1.0 |
| Microsoft.Extensions.CommandLineUtils | 1.1.0 |
| Microsoft.Extensions.Configuration | 1.1.0 |
| Microsoft.Extensions.Configuration.Abstractions | 1.1.0 |
| Microsoft.Extensions.Configuration.AzureKeyVault | 1.0.0 |
| Microsoft.Extensions.Configuration.Binder | 1.1.0 |
| Microsoft.Extensions.Configuration.CommandLine | 1.1.0 |
| Microsoft.Extensions.Configuration.EnvironmentVariables | 1.1.0 |
| Microsoft.Extensions.Configuration.FileExtensions | 1.1.0 |
| Microsoft.Extensions.Configuration.Ini | 1.1.0 |
| Microsoft.Extensions.Configuration.Json | 1.1.0 |
| Microsoft.Extensions.Configuration.UserSecrets | 1.1.0 |
| Microsoft.Extensions.Configuration.Xml | 1.1.0 |
| Microsoft.Extensions.DependencyInjection | 1.1.0 |
| Microsoft.Extensions.DependencyInjection.Abstractions | 1.1.0 |
| Microsoft.Extensions.DependencyInjection.Specification.Tests | 1.1.0 |
| Microsoft.Extensions.DiagnosticAdapter | 1.1.0 |
| Microsoft.Extensions.FileProviders.Abstractions | 1.1.0 |
| Microsoft.Extensions.FileProviders.Composite | 1.1.0 |
| Microsoft.Extensions.FileProviders.Embedded | 1.1.0 |
| Microsoft.Extensions.FileProviders.Physical | 1.1.0 |
| Microsoft.Extensions.FileSystemGlobbing | 1.1.0 |
| Microsoft.Extensions.Globalization.CultureInfoCache | 1.1.0 |
| Microsoft.Extensions.Localization | 1.1.0 |
| Microsoft.Extensions.Localization.Abstractions | 1.1.0 |
| Microsoft.Extensions.Logging | 1.1.0 |
| Microsoft.Extensions.Logging.Abstractions | 1.1.0 |
| Microsoft.Extensions.Logging.AzureAppServices | 1.0.0 |
| Microsoft.Extensions.Logging.Console | 1.1.0 |
| Microsoft.Extensions.Logging.Debug | 1.1.0 |
| Microsoft.Extensions.Logging.EventLog | 1.1.0 |
| Microsoft.Extensions.Logging.EventSource | 1.1.0 |
| Microsoft.Extensions.Logging.Filter | 1.1.0 |
| Microsoft.Extensions.Logging.TraceSource | 1.1.0 |
| Microsoft.Extensions.ObjectPool | 1.1.0 |
| Microsoft.Extensions.Options | 1.1.0 |
| Microsoft.Extensions.Options.ConfigurationExtensions | 1.1.0 |
| Microsoft.Extensions.PlatformAbstractions | 1.1.0 |
| Microsoft.Extensions.Primitives | 1.1.0 |
| Microsoft.Extensions.SecretManager.Tools | 1.1.0-preview4-final |
| Microsoft.Extensions.WebEncoders | 1.1.0 |
| Microsoft.Net.Http.Headers | 1.1.0 |
| Microsoft.Net.Http.Server | 1.1.0 |
| Microsoft.Owin.Security.Interop | 1.1.0 |
| Microsoft.VisualStudio.Web.BrowserLink | 1.0.0 |
| Microsoft.VisualStudio.Web.BrowserLink.Loader | 14.1.0 |
| Microsoft.VisualStudio.Web.CodeGeneration | 1.1.0-preview4-final |
| Microsoft.VisualStudio.Web.CodeGeneration.Core | 1.1.0-preview4-final |
| Microsoft.VisualStudio.Web.CodeGeneration.EntityFrameworkCore | 1.1.0-preview4-final |
| Microsoft.VisualStudio.Web.CodeGeneration.Templating | 1.1.0-preview4-final |
| Microsoft.VisualStudio.Web.CodeGeneration.Tools | 1.1.0-preview4-final |
| Microsoft.VisualStudio.Web.CodeGeneration.Utils | 1.1.0-preview4-final |
| Microsoft.VisualStudio.Web.CodeGenerators.Mvc | 1.1.0-preview4-final |

**Comment by dstep2007** [comment]
@pranavkm, I updated my project.json as you suggested with the table provided as well as installed the SDK and Runtime for v1.1.  Everything appears to be working properly now.  Thank you very much!

**Comment by clovisrod** [comment]
Hi

What SDK version should I use in global.json ?

Thanks

**Comment by paulcsiki** [comment]
@pranavkm Would you happen to have a list of NuGet package versions for the 1.0.3 LTS stable release?

**Comment by pranavkm** [comment]
### 1.0.3 release

| Id | Version |
| --- | --- |
|Microsoft.AspNet.Identity.AspNetCoreCompat | 0.1.1|
|Microsoft.AspNetCore | 1.0.3|
|Microsoft.AspNetCore.Antiforgery | 1.0.2|
|Microsoft.AspNetCore.Authentication | 1.0.1|
|Microsoft.AspNetCore.Authentication.Cookies | 1.0.1|
|Microsoft.AspNetCore.Authentication.Facebook | 1.0.1|
|Microsoft.AspNetCore.Authentication.Google | 1.0.1|
|Microsoft.AspNetCore.Authentication.JwtBearer | 1.0.1|
|Microsoft.AspNetCore.Authentication.MicrosoftAccount | 1.0.1|
|Microsoft.AspNetCore.Authentication.OAuth | 1.0.1|
|Microsoft.AspNetCore.Authentication.OpenIdConnect | 1.0.1|
|Microsoft.AspNetCore.Authentication.Twitter | 1.0.1|
|Microsoft.AspNetCore.Authorization | 1.0.1|
|Microsoft.AspNetCore.CookiePolicy | 1.0.1|
|Microsoft.AspNetCore.Cors | 1.0.1|
|Microsoft.AspNetCore.Cryptography.Internal | 1.0.1|
|Microsoft.AspNetCore.Cryptography.KeyDerivation | 1.0.1|
|Microsoft.AspNetCore.DataProtection | 1.0.1|
|Microsoft.AspNetCore.DataProtection.Abstractions | 1.0.1|
|Microsoft.AspNetCore.DataProtection.Extensions | 1.0.1|
|Microsoft.AspNetCore.DataProtection.SystemWeb | 1.0.1|
|Microsoft.AspNetCore.Diagnostics | 1.0.1|
|Microsoft.AspNetCore.Diagnostics.Abstractions | 1.0.1|
|Microsoft.AspNetCore.Diagnostics.Elm | 0.1.1|
|Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore | 1.0.1|
|Microsoft.AspNetCore.Hosting | 1.0.1|
|Microsoft.AspNetCore.Hosting.Abstractions | 1.0.1|
|Microsoft.AspNetCore.Hosting.Server.Abstractions | 1.0.1|
|Microsoft.AspNetCore.Hosting.WindowsServices | 1.0.1|
|Microsoft.AspNetCore.Html.Abstractions | 1.0.1|
|Microsoft.AspNetCore.Http | 1.0.1|
|Microsoft.AspNetCore.Http.Abstractions | 1.0.1|
|Microsoft.AspNetCore.Http.Extensions | 1.0.1|
|Microsoft.AspNetCore.Http.Features | 1.0.1|
|Microsoft.AspNetCore.HttpOverrides | 1.0.1|
|Microsoft.AspNetCore.Identity | 1.0.1|
|Microsoft.AspNetCore.Identity.EntityFrameworkCore | 1.0.1|
|Microsoft.AspNetCore.JsonPatch | 1.0.0|
|Microsoft.AspNetCore.Localization | 1.0.1|
|Microsoft.AspNetCore.MiddlewareAnalysis | 1.0.1|
|Microsoft.AspNetCore.Mvc | 1.0.2|
|Microsoft.AspNetCore.Mvc.Abstractions | 1.0.2|
|Microsoft.AspNetCore.Mvc.ApiExplorer | 1.0.2|
|Microsoft.AspNetCore.Mvc.Core | 1.0.2|
|Microsoft.AspNetCore.Mvc.Cors | 1.0.2|
|Microsoft.AspNetCore.Mvc.DataAnnotations | 1.0.2|
|Microsoft.AspNetCore.Mvc.Formatters.Json | 1.0.2|
|Microsoft.AspNetCore.Mvc.Formatters.Xml | 1.0.2|
|Microsoft.AspNetCore.Mvc.Localization | 1.0.2|
|Microsoft.AspNetCore.Mvc.Razor | 1.0.2|
|Microsoft.AspNetCore.Mvc.Razor.Host | 1.0.2|
|Microsoft.AspNetCore.Mvc.TagHelpers | 1.0.2|
|Microsoft.AspNetCore.Mvc.ViewFeatures | 1.0.2|
|Microsoft.AspNetCore.Mvc.WebApiCompatShim | 1.0.2|
|Microsoft.AspNetCore.Owin | 1.0.1|
|Microsoft.AspNetCore.Proxy | 0.1.1|
|Microsoft.AspNetCore.Razor | 1.0.1|
|Microsoft.AspNetCore.Razor.Runtime | 1.0.1|
|Microsoft.AspNetCore.Razor.Tools | 1.0.0-preview4-final|
|Microsoft.AspNetCore.ResponseCaching | 1.0.0|
|Microsoft.AspNetCore.ResponseCaching.Abstractions | 1.0.0|
|Microsoft.AspNetCore.Routing | 1.0.2|
|Microsoft.AspNetCore.Routing.Abstractions | 1.0.2|
|Microsoft.AspNetCore.Server.IISIntegration | 1.0.1|
|Microsoft.AspNetCore.Server.IISIntegration.Tools | 1.0.0-preview4-final|
|Microsoft.AspNetCore.Server.Kestrel | 1.0.2|
|Microsoft.AspNetCore.Server.Kestrel.Https | 1.0.2|
|Microsoft.AspNetCore.Server.WebListener | 1.0.1|
|Microsoft.AspNetCore.Session | 1.0.1|
|Microsoft.AspNetCore.StaticFiles | 1.0.1|
|Microsoft.AspNetCore.TestHost | 1.0.1|
|Microsoft.AspNetCore.WebSockets.Protocol | 0.1.1|
|Microsoft.AspNetCore.WebSockets.Server | 0.1.1|
|Microsoft.AspNetCore.WebUtilities | 1.0.1|
|Microsoft.Data.Sqlite | 1.0.1|
|Microsoft.DotNet.Watcher.Core | 1.0.0-preview4-final|
|Microsoft.DotNet.Watcher.Tools | 1.0.0-preview4-final|
|Microsoft.EntityFrameworkCore | 1.0.2|
|Microsoft.EntityFrameworkCore.Design | 1.0.2|
|Microsoft.EntityFrameworkCore.InMemory | 1.0.2|
|Microsoft.EntityFrameworkCore.Relational | 1.0.2|
|Microsoft.EntityFrameworkCore.Relational.Design | 1.0.2|
|Microsoft.EntityFrameworkCore.Relational.Design.Specification.Tests | 1.0.2|
|Microsoft.EntityFrameworkCore.Relational.Specification.Tests | 1.0.2|
|Microsoft.EntityFrameworkCore.Specification.Tests | 1.0.2|
|Microsoft.EntityFrameworkCore.Sqlite | 1.0.2|
|Microsoft.EntityFrameworkCore.Sqlite.Design | 1.0.2|
|Microsoft.EntityFrameworkCore.SqlServer | 1.0.2|
|Microsoft.EntityFrameworkCore.SqlServer.Design | 1.0.2|
|Microsoft.EntityFrameworkCore.Tools | 1.0.0-preview4-final|
|Microsoft.EntityFrameworkCore.Tools.DotNet | 1.0.0-preview4-final|
|Microsoft.Extensions.Caching.Abstractions | 1.0.1|
|Microsoft.Extensions.Caching.Memory | 1.0.1|
|Microsoft.Extensions.Caching.Redis | 1.0.1|
|Microsoft.Extensions.Caching.SqlConfig.Tools | 1.0.0-preview4-final|
|Microsoft.Extensions.Caching.SqlServer | 1.0.1|
|Microsoft.Extensions.CommandLineUtils | 1.0.1|
|Microsoft.Extensions.Configuration | 1.0.1|
|Microsoft.Extensions.Configuration.Abstractions | 1.0.1|
|Microsoft.Extensions.Configuration.Binder | 1.0.1|
|Microsoft.Extensions.Configuration.CommandLine | 1.0.1|
|Microsoft.Extensions.Configuration.EnvironmentVariables | 1.0.1|
|Microsoft.Extensions.Configuration.FileExtensions | 1.0.1|
|Microsoft.Extensions.Configuration.Ini | 1.0.1|
|Microsoft.Extensions.Configuration.Json | 1.0.1|
|Microsoft.Extensions.Configuration.UserSecrets | 1.0.1|
|Microsoft.Extensions.Configuration.Xml | 1.0.1|
|Microsoft.Extensions.DependencyInjection | 1.0.1|
|Microsoft.Extensions.DependencyInjection.Abstractions | 1.0.1|
|Microsoft.Extensions.DependencyInjection.Specification.Tests | 1.0.1|
|Microsoft.Extensions.DiagnosticAdapter | 1.0.1|
|Microsoft.Extensions.FileProviders.Abstractions | 1.0.1|
|Microsoft.Extensions.FileProviders.Composite | 1.0.1|
|Microsoft.Extensions.FileProviders.Embedded | 1.0.1|
|Microsoft.Extensions.FileProviders.Physical | 1.0.1|
|Microsoft.Extensions.FileSystemGlobbing | 1.0.1|
|Microsoft.Extensions.Globalization.CultureInfoCache | 1.0.1|
|Microsoft.Extensions.Localization | 1.0.1|
|Microsoft.Extensions.Localization.Abstractions | 1.0.1|
|Microsoft.Extensions.Logging | 1.0.1|
|Microsoft.Extensions.Logging.Abstractions | 1.0.1|
|Microsoft.Extensions.Logging.Console | 1.0.1|
|Microsoft.Extensions.Logging.Debug | 1.0.1|
|Microsoft.Extensions.Logging.EventLog | 1.0.1|
|Microsoft.Extensions.Logging.Filter | 1.0.1|
|Microsoft.Extensions.Logging.TraceSource | 1.0.1|
|Microsoft.Extensions.ObjectPool | 1.0.1|
|Microsoft.Extensions.Options | 1.0.1|
|Microsoft.Extensions.Options.ConfigurationExtensions | 1.0.1|
|Microsoft.Extensions.PlatformAbstractions | 1.0.0|
|Microsoft.Extensions.Primitives | 1.0.1|
|Microsoft.Extensions.SecretManager.Tools | 1.0.0-preview4-final|
|Microsoft.Extensions.WebEncoders | 1.0.1|
|Microsoft.Net.Http.Headers | 1.0.1|
|Microsoft.Net.Http.Server | 1.0.1|
|Microsoft.Owin.Security.Interop | 1.0.1|
|Microsoft.VisualStudio.Web.BrowserLink.Loader | 14.0.1|
|Microsoft.VisualStudio.Web.CodeGeneration | 1.0.0-preview4-final|
|Microsoft.VisualStudio.Web.CodeGeneration.Core | 1.0.0-preview4-final|
|Microsoft.VisualStudio.Web.CodeGeneration.EntityFrameworkCore | 1.0.0-preview4-final|
|Microsoft.VisualStudio.Web.CodeGeneration.Templating | 1.0.0-preview4-final|
|Microsoft.VisualStudio.Web.CodeGeneration.Tools | 1.0.0-preview4-final|
|Microsoft.VisualStudio.Web.CodeGeneration.Utils | 1.0.0-preview4-final|
|Microsoft.VisualStudio.Web.CodeGenerators.Mvc | 1.0.0-preview4-final|

**Comment by paulcsiki** [comment]
@pranavkm Thank you.
