### ISSUE TITLE
Debug in Visual Studio 2017 RC

### ISSUE THREAD

**Issue by bidolah** [aspnet/Home#1828]
I updated nuget package from "Microsoft.NETCore.App 1.0.1" to "1.1.0 Microsoft.NETCore.App" and now get this error when i run project:
The program '[20180] dotnet.exe' has exited with code -2147450749 (0x80008083).
The program '[20180] dotnet.exe: Program Trace' has exited with code 0 (0x0).
The program '[13884] chrome.exe: WebKit' has exited with code -1 (0xffffffff).
The program '[7616] iisexpress.exe: Program Trace' has exited with code 0 (0x0).
The program '[7616] iisexpress.exe' has exited with code 0 (0x0).

**Comment by moozzyk** [comment]
I wonder if this is this: https://github.com/dotnet/core/issues/305

**Comment by ComputingMastery** [comment]
Did you update all the other Core packages to match?

**Comment by bidolah** [comment]
I updated all nuget packages to latest version.  But I having problem only when updated to this package "1.1.0 Microsoft.NETCore.App"

**Comment by bidolah** [comment]
I have installed only this components:
![image](https://cloud.githubusercontent.com/assets/9832538/20461778/ade3edf6-af10-11e6-9ba7-f802d4b9826d.png)
I uninstall component on the photo higher and install this:
![image](https://cloud.githubusercontent.com/assets/9832538/20461782/e62acb8a-af10-11e6-8a18-4833fcd8098d.png)
Now all working done)
