### ISSUE TITLE
Huge build time increase for .NETCoreApp,Version v1.1

### ISSUE THREAD

**Issue by henkmollema** [aspnet/Home#1829]
I've updated my ASP.NET Core application to .NET Core 1.1 and ASP.NET Core 1.1 runtime packages. Using 1.0 building took ~5 seconds. After the update it's ~40 seconds.

When I set `"preserveCompilationContext": false` in the project.json, the build time goes down to ~1 sec.

My application is rather large and pulls in a fair amount of dependencies. It does not repro with a new project.

**Comment by henkmollema** [comment]
Guess I found it. I had left an older version of the .NET Core CLI in my global.json:
```json
{
  "projects": [ "src", "test" ],
  "sdk": {
    "version": "1.0.0-preview2-003131"
  }
}
```

The build runs successful, it's just terribly slow. Removing the `sdk` element fixed it.

**Comment by henkmollema** [comment]
Perhaps a warning from the CLI that the SDK version in global.json and the .NET Core version of the application do not match.

**Comment by ry8806** [comment]
What is the latest (for v1.1) SDK Version?

**Comment by henkmollema** [comment]
I just removed it. But the latest version is `1.0.0-preview2-1-003177`.

**Comment by acastaner** [comment]
I'm seeing a similar issue (build time went from a couple of seconds in 1.0 to more than a minute in 1.1) but I don't reference any SDK version in the global.json. Where else could this come from and how can I troubleshoot?

The project I build relies on libraries running .NET Standard 1.6, if that matters. Their compilation time is unchanged from before.

**Comment by drb-germany** [comment]
I also have a massive slowdown of build time after upgrading to 1.1.0.

Changing the framework to 1.1.0 and leaving all packages at 1.0.0 keeps building time low, but upgrading all packages in the nuget packet manager (or manually) will increase build time to >20 seconds.

I have the same issue with a brand new "blank" asp.net core template for a web application.

**Comment by alexchiraples** [comment]
@henkmollema I had the same problem. I've reduced the build time from 30 seconds to 3 seconds by updating the sdk version in `global.json`.

A warning from the CLI would help in this scenario.

**Comment by per3ian** [comment]
I updated sdk version in global.json to `"1.0.0-preview2-1-003177"` and build time reduced from 56 seconds to 2 seconds!

Thank you.

**Comment by daveronson** [comment]
As a VS 2015 user it took me a bit to find the correct SDK to download. In case it helps someone else here is the link to the archived 003177 SDK: https://github.com/dotnet/core/blob/master/release-notes/download-archives/1.1-preview2.1-download.md

**Comment by golubitsky** [comment]
I'm a VS 2015 user as well and recently began working on a project that had the following global.json file:
```{
    "projects": [ "src", "test" ],
    "sdk": {
        "version": "1.0.0-preview2-003131"
    }
}
```
I was getting untolerable ~1min build times. I had downloaded SDK 1.0.1, but I was unable to edit the global.json to use that version. 

I followed @daveronson 's suggestion above, downloaded the appropriate SDK and changed by global.json to read as follows, which resolved my build time issue.

```{
    "projects": [ "src", "test" ],
    "sdk": {
      "version": "1.0.0-preview2-1-003177"
    }
}
```
Could anyone please explain why I couldn't use `"version":"1.0.1"` even though it was installed? I'm pretty new to the dotnetcore world.

**Comment by vaindil** [comment]
I'm having this same problem, the only issue is that my project is using the csproj format. There's no global.json file anymore, so the workarounds above don't work.
