### ISSUE TITLE
Can't build rel/1.1 from source

### ISSUE THREAD

**Issue by dtillman** [aspnet/Home#1831]
When trying to build rel/1.1 from source, the build fails and I see several errors during the build while package restore for Common is performed: 

log  : Restoring packages for C:\Users\dtillman\workspace\aspnet\Universe\Common\test\Microsoft.Extensions.Primitives.Tests\project.json...
error: Package Microsoft.DotNet.Cli.Utils 1.0.0-preview3-004056 is not compatible with net451 (.NETFramework,Version=v4.5.1). Package Microsoft.DotNet.Cli.Utils 1.0.0-preview3-004056 supports:
error:   - net46 (.NETFramework,Version=v4.6)
error:   - netstandard1.5 (.NETStandard,Version=v1.5)
error: One or more packages are incompatible with .NETFramework,Version=v4.5.1.

**Comment by pranavkm** [comment]
I just updated the `rel/1.1.0` tag in all the repos to pin dependency versions. Could you try updating to it and let me know if it works:

```
> git pull --tags
> git checkout refs/tags/rel/1.1.0
```

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
