### ISSUE TITLE
How do you configure custom encryption for Session cookie?

### ISSUE THREAD

**Issue by john-luke-laue** [aspnet/Home#1832]
I have my app setup to use Session variables. By default this creates a cookie called .AspNetCore.Session and the value is encrypted. 

Is there anyway for me to override the encryption that occurs and replace it with some custom encryption? 

```
services.AddSession(c => { c.IdleTimeout = System.TimeSpan.FromMinutes(60); });
//...
app.UseSession();
```

**Comment by Tratcher** [comment]
Looks like you've found your answer on SO. http://stackoverflow.com/questions/40684357/decrypt-aspnetcore-session-cookie-in-asp-net-core

It's still not clear why you're decrypting the value manually.

**Comment by john-luke-laue** [comment]
Sorry thought I closed this ticket. Yup, I found a solution and posted it to SO. 

I'm trying to share the session between a classic ASP app and a .net core app. The classic ASP app needs to decrypt the .AspNetCore.Session cookie so it knows the Session ID to look-up in the database (I'm using sql storage for my session data).
