### ISSUE TITLE
Individual Authentication Libs not working with new Docker container tooling.

### ISSUE THREAD

**Issue by ComputingMastery** [aspnet/Home#1833]
When ASP.NET Core 1.1.0 app is containerized for Docker using the new tooling using the Authentication packages...

	    app.UseGoogleAuthentication(new GoogleOptions()
            {
                ClientId = Configuration["Authentication:GoogleAccount:ClientId"],
                ClientSecret = Configuration["Authentication:GoogleAccount:ClientSecret"]
            });

Throws the:

An unhandled exception of type 'System.ArgumentException' occurred in System.Private.CoreLib.ni.dll

In Main on the following call:

            var host = new WebHostBuilder()
                .UseKestrel()
                .UseContentRoot(Directory.GetCurrentDirectory())
                .UseIISIntegration()
                .UseStartup<Startup>()
                .Build();

Is this a bug that is going to be fixed or will these not work from inside the containers with ASP.NET Core going forward and should be avoided for greatest compatibility?

**Comment by Tratcher** [comment]
Stack trace?

**Comment by ComputingMastery** [comment]
That's the entirety of the error coming up.  No further information is present...  Just:

An unhandled exception of type 'System.ArgumentException' occurred in System.Private.CoreLib.ni.dll

**Comment by Tratcher** [comment]
@glennc?

**Comment by ComputingMastery** [comment]
After looking at @glennc 's commits, and doing some testing... I can confirm the issue is related to the User Secrets.  If I put the values directly in the code, I do not get the error.  Though, the error message could use some love perhaps.

**Comment by glennc** [comment]
How are you expecting to use UserSecrets here? UserSecrets is for when you are on your developer machine running directly. Inside the container you will not have anything that was in the user secrets configuration. I am not sure what is causing your exception off the top of my head, but it doesn't surprise me that user secrets doesn't work as this is not the scenario it was designed for.

Are you expecting Authentication:GoogleAccount:ClientId to come from user secrets inside the container?

**Comment by HarelM** [comment]
I'm not sure this is the right place, but I also get the following error:
```
An unhandled exception of type 'System.ArgumentException' occurred in System.Private.CoreLib.dll
The path is not of a legal form.`
```
This error totally crashes my iisexpress. it's probably not the same issue but maybe the same root cause?
I recently migrated to .net core 2.0 and added this User Secrets to my project so I'm not sure what started causing this.

Any thoughts?

**Comment by Eilon** [comment]
Unfortunately without a complete stack trace it's too hard to tell what is causing this exception - it's not even clear that it's related to User Secrets.

If anyone is still hitting this issue, please try to capture a full stack trace and log an issue so that we can investigate. Thanks!
