### ISSUE TITLE
How to deserialize bytes from Session table when using sql storage for session data?

### ISSUE THREAD

**Issue by john-luke-laue** [aspnet/Home#1836]
I am currently using SQL Storage for my session data. In the Sessions table, .NET Core creates a column called Value of type varbinary. This is where the session data/variables are stored. How do you read and deserialize this data? I need to share session data between my .net core app and a classic asp app. I need to know how to deserialize this data so I can read it in my classic asp app. 

Using framework net461.

```
services.AddDistributedSqlServerCache(o =>
{
    o.ConnectionString = Configuration["MyConnString"];
    o.TableName = "Sessions";
    o.SchemaName = "dbo"; 
});
```

**Comment by Tratcher** [comment]
See https://github.com/aspnet/Session/blob/dev/src/Microsoft.AspNetCore.Session/DistributedSession.cs#L277

**Comment by john-luke-laue** [comment]
@Tratcher 
Thanks! Is there any way I can inject ISession (with Distributed Session being the implementation) directly using DI? Or do you always have to retrieve the Session through HttpContext?

**Comment by Tratcher** [comment]
No, there is no DI support for ISession. The closest you can get is IHttpContextAccessor.

**Comment by john-luke-laue** [comment]
Darn. Thanks for the help!
