### ISSUE TITLE
System.IO.FileLoadException: System.Text.Encodings.Web

### ISSUE THREAD

**Issue by JeanCollas** [aspnet/Home#1838]
I saw several people had a similar issue with other dependencies. 
I have a AspNetCore1.1 website, if I publish it with Visual Studio, I get the following stacktrace, with a 502.5 answer:

	Application startup exception: System.IO.FileLoadException: Could not load file or assembly 'System.Text.Encodings.Web, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
	File name: 'System.Text.Encodings.Web, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
	   at Microsoft.Extensions.DependencyInjection.EncoderServiceCollectionExtensions.AddWebEncoders(IServiceCollection services)
	   at Microsoft.Extensions.DependencyInjection.AuthenticationServiceCollectionExtensions.AddAuthentication(IServiceCollection services)
	   at Microsoft.Extensions.DependencyInjection.IdentityServiceCollectionExtensions.AddIdentity[TUser,TRole](IServiceCollection services, Action`1 setupAction)
	   at MyWebsite.Startup.ConfigureServices(IServiceCollection services) in Z:\Prog\MyWebsiteFolder\MyWebsite\Startup.cs:line 83
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
	   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
	   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
	   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()

	Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'System.Text.Encodings.Web, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
	   at Microsoft.Extensions.RazorViews.BaseView..ctor()
	   at Microsoft.AspNetCore.Hosting.Views.ErrorPage..ctor(ErrorPageModel model)
	   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
	   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
	   at MyWebsite.Program.Main(String[] args) in Z:\Prog\MyWebsiteFolder\MyWebsite\Program.cs:line 14

However if I run the command line 

    dotnet.exe publish "z:\Prog\MyWebsiteFolder\MyWebsite" --framework netcoreapp1.1 --output "Z:\bin\WebsiteManual" --configuration Release

Everything works fine.
I get the same behavior on different platforms (2008R2 and 2012). Other websites (1.0) are running just fine.
It also works fine when debugging on VS via IIS Express (Debug and Release mode)

Here is the project.json:

    {
      "userSecretsId": "XXXXXXXX",
      "dependencies": {
        "Bower": "1.3.11",
        "BundlerMinifier.Core": "2.2.306",
        "ImageSharp": "1.0.0",
        "Libuv": "1.9.1",
        "MailKit": "1.10.0",
        "Microsoft.ApplicationInsights.AspNetCore": "1.0.2",
        "Microsoft.AspNetCore.Authentication.OAuth": "1.1.0",
        "Microsoft.AspNetCore.Mvc": "1.1.0",
        "Microsoft.AspNetCore.Razor.Tools": {
          "version": "1.0.0-preview2-final",
          "type": "build"
        },
        "Microsoft.AspNetCore.Server.Kestrel.Https": "1.1.0",
        "Microsoft.EntityFrameworkCore.Design.Core": "1.0.0-preview2-final",
        "Microsoft.EntityFrameworkCore.SqlServer": "1.1.0",
        "Microsoft.EntityFrameworkCore.SqlServer.Design": {
          "version": "1.1.0",
          "type": "build"
        },
        "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.1.0",
        "Microsoft.Extensions.Configuration.Json": "1.1.0",
        "Microsoft.Extensions.Configuration.UserSecrets": "1.1.0",
        "Microsoft.Extensions.Logging.Debug": "1.1.0",
        "Microsoft.Extensions.Options.ConfigurationExtensions": "1.1.0",
        "Microsoft.NETCore.App": {
          "version": "1.1.0",
          "type": "platform"
        },
        "Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.1.0",
        "Stripe.net": "6.11.1",
        "System.ServiceModel.Duplex": "4.3.0",
        "System.ServiceModel.Http": "4.3.0",
        "System.ServiceModel.NetTcp": "4.3.0",
        "System.ServiceModel.Security": "4.3.0",
        "System.Xml.XmlSerializer": "4.3.0",
        "Microsoft.EntityFrameworkCore": "1.1.0",
        "Microsoft.AspNetCore.Authentication": "1.1.0",
        "Microsoft.AspNetCore.Authentication.Cookies": "1.1.0",
        "Microsoft.AspNetCore.Authentication.Facebook": "1.1.0",
        "Microsoft.AspNetCore.Authentication.Google": "1.1.0",
        "Microsoft.AspNetCore.Authentication.MicrosoftAccount": "1.1.0",
        "Microsoft.AspNetCore.Diagnostics": "1.1.0",
        "Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore": "1.1.0",
        "Microsoft.AspNetCore.Server.IISIntegration": "1.1.0",
        "Microsoft.AspNetCore.Server.IISIntegration.Tools": {
          "version": "1.1.0-preview4-final",
          "type": "build"
        },
        "Microsoft.AspNetCore.Server.Kestrel": "1.1.0",
        "Microsoft.AspNetCore.StaticFiles": "1.1.0",
        "Microsoft.EntityFrameworkCore.Design": {
          "version": "1.1.0",
          "type": "build"
        },
        "Microsoft.EntityFrameworkCore.Relational": "1.1.0",
        "Microsoft.Extensions.Logging": "1.1.0",
        "Microsoft.Extensions.Logging.Console": "1.1.0",
        "Microsoft.EntityFrameworkCore.Tools": "1.1.0-preview4-final",
        "PayPalCore": "1.0.0-*",
        "OtherProject": "1.0.0-*",
        "Microsoft.AspNetCore.Identity.EntityFrameworkCore": "1.1.0",
        "Microsoft.AspNetCore.Identity": "1.1.0"
      },
      "tools": {
        "Microsoft.EntityFrameworkCore.Tools": "1.1.0-preview4-final",
        "Microsoft.AspNetCore.Razor.Tools": "1.0.0-preview2-final",
        "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.1.0-preview4-final",
        "Microsoft.Extensions.SecretManager.Tools": "1.0.0-preview2-final"
      },
      "frameworks": {
        "netcoreapp1.1": {
          "imports": [
            "dotnet5.6",
            "portable-net45+win8+wpa81"
          ],
          "dependencies": {
          }

        }
      },
      "buildOptions": {
        "emitEntryPoint": true,
        "preserveCompilationContext": true,
        "define": []
      },
      "runtimeOptions": {
        "configProperties": {
          "System.GC.Server": true
        }
      },
      "publishOptions": {
        "include": [
          "wwwroot",
          "Views",
          "Areas/**/Views",
          "appsettings.json",
          "web.config"
        ]
      },
      "scripts": {
        "prepublish": [
          "bower install",
          "dotnet bundle"
        ],
        "postpublish": [
          "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%"
        ]
      }
    }

And the other project one:

    {
      "dependencies": {
        "Microsoft.NETCore.App": {
          "version": "1.1.0",
          "type": "platform"
        },
        "Microsoft.AspNetCore.Diagnostics": "1.0.0",

        "Microsoft.AspNetCore.Server.IISIntegration": "1.1.0",
        "Microsoft.AspNetCore.Server.Kestrel": "1.1.0",
        "Microsoft.AspNetCore.Server.Kestrel.Https": "1.1.0",
        "Microsoft.Extensions.Logging.Console": "1.0.0",

        "Microsoft.AspNetCore.Authentication.OAuth": "1.1.0",
        "Microsoft.AspNetCore.Identity": "1.1.0",
        "Microsoft.AspNetCore.Identity.EntityFrameworkCore": "1.1.0",
        "Microsoft.AspNetCore.Mvc": "1.1.0",
        "Microsoft.EntityFrameworkCore.Design.Core": "1.0.0-preview2-final",
        "Microsoft.EntityFrameworkCore.SqlServer": "1.1.0",
        "Microsoft.EntityFrameworkCore.SqlServer.Design": {
          "version": "1.1.0",
          "type": "build"
        },
        "Microsoft.Extensions.Options.ConfigurationExtensions": "1.1.0",
        "Microsoft.EntityFrameworkCore": "1.1.0",
        "Microsoft.EntityFrameworkCore.Design": {
          "version": "1.1.0",
          "type": "build"
        },
        "Microsoft.EntityFrameworkCore.Tools": {
          "version": "1.1.0-preview4-final",
          "type": "build"
        },
        "Microsoft.EntityFrameworkCore.Relational": "1.1.0",

        "Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore": "1.1.0",
        "Microsoft.AspNetCore.Authentication": "1.1.0",
        "Microsoft.AspNetCore.Authentication.Cookies": "1.1.0",
        "Microsoft.AspNetCore.Authentication.Facebook": "1.1.0",
        "Microsoft.AspNetCore.Authentication.Google": "1.1.0",
        "Microsoft.AspNetCore.Authentication.MicrosoftAccount": "1.1.0",

        "AspNet.Security.OAuth.Validation": "1.0.0-alpha2-final",
        "OpenIddict": "1.0.0-*",
        "OpenIddict.Mvc": "1.0.0-*"

      },

      "tools": {
        "Microsoft.EntityFrameworkCore.Tools": "1.1.0-preview4-final",
        "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.0.0-preview2-final"
      },

      "frameworks": {
        "netcoreapp1.1": {
          "imports": [
            "dotnet5.6",
            "portable-net45+win8"
          ]
        }
      },

      "buildOptions": {
        "emitEntryPoint": true,
        "preserveCompilationContext": true
      },

      "runtimeOptions": {
        "configProperties": {
          "System.GC.Server": true
        }
      },

      "publishOptions": {
        "include": [
          "wwwroot",
          "web.config"
        ]
      },

      "scripts": {
        "postpublish": [ "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%" ]
      }
    }

I don't get any .config file besides the web.config, and the .deps.json does not mention this missing dependency.

**Comment by Tratcher** [comment]
System.Text.Encodings.Web, Version=4.0.1.0 is in package version 4.3.0.

What references to System.Text.Encodings.Web do you see in your project.lock.json?

**Comment by JeanCollas** [comment]
That is the weird part, nothing references this package, however, in project.lock.json there is a reference in targets??:
    "targets": {
        "Text.Encodings.Web": null,
        ".NETCoreApp,Version=v1.1": {
      ...
      ...
      }
    }

But seeing the call-stack of the exception, I guess it is linked to identity:

    at Microsoft.Extensions.DependencyInjection.EncoderServiceCollectionExtensions.**AddWebEncoders**(IServiceCollection services)
    at Microsoft.Extensions.DependencyInjection.AuthenticationServiceCollectionExtensions.AddAuthentication(IServiceCollection services)
    at Microsoft.Extensions.DependencyInjection.IdentityServiceCollectionExtensions.**AddIdentity**[TUser,TRole](IServiceCollection services, Action`1 setupAction)

**Comment by halter73** [comment]
Posting the gist of the entire project.lock.json could still be helpful. Also, generally speaking, it's not a good idea to mix 1.1.0 and 1.0.0 packages (e.g. Microsoft.AspNetCore.Diagnostics, Microsoft.Extensions.Logging.Console).

**Comment by JeanCollas** [comment]
This issue was annoying but not blocking, however I actually went back to 1.0 due to the following issue, waiting for a fix...
https://github.com/aspnet/Security/issues/1044

**Comment by kant2002** [comment]
Still and issue.

**Comment by gschuager** [comment]
I'm getting this issue after upgrading ASP.NET Core nugets from 1.1.1 to 1.1.2

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.

**Comment by StefanoChiodino** [comment]
I'm still having this issue. I just created a new project and used `QueryHelpers`.

To fix it, I had to install the `System.Text.Encodings.Web` package manually.

**Comment by Tratcher** [comment]
Comments on closed issues are not tracked, please open a new issue with the details for your scenario. What versions are you using?

**Comment by StefanoChiodino** [comment]
Not really ergonomic to close issues arbitrarily, is it?
