### ISSUE TITLE
Multiple ASP.NET Core websites sharing same backend

### ISSUE THREAD

**Issue by Wayne-Mather** [aspnet/Home#1840]
Hi,

I am having issues having multiple front ends (either via domain/subsite or subdomain.domain) all sharing the same sql server back-end. I am using the standard .NET Core template with authentication.

I believe the issue maybe related to how browsers treat the cookies. Is there a document that shows how to have multiple front ends (not a web farm environment - each site has an environment variable to make it unique) talking to the same back-end?

The reason for this is our production system is a replicated database to remote servers and we would also like a central head office hosting multiple front-ends without having to setup db instances and replication. 

Any information that can be provided would be helpful.

Update:  v1.0.1 data

**Comment by Wayne-Mather** [comment]
Just to paint a clear picture imagine a sales website and a different front-end for each store. This is how the software is setup. I would like to host each store on the same IIS/SQL instance without having cookie clashes [assuming it's actually a cookie issue - as the site runs, you just cannot authenticate]

**Comment by Tratcher** [comment]
You've outlined your architecture, but haven't actually explained your problem or symptoms. Something about not being able to authenticate? Is there an error? Logs? Network traces?

**Comment by Wayne-Mather** [comment]
Yes, I just keep getting the login page and unable to login to the application. I will look at how to turn output logging on so I can further investigate just what the problem is - cookies, routing, db access....

I just posted this here in-case there was something specific needed to be done to have multiple WFE using the same persistence storage layer.

**Comment by Wayne-Mather** [comment]
I decided to run a complete new environment in a virtual machine. Using this vanilla environment with the Web Application template and Authentication enabled.

I was able to successfully run two websites from different URL's pointing to the same backend. This means something in my project is causing an issue (or the Chrome Browser as this testing was on 2012 server with IE 10.

I consider this issue an environmental issues and not an ASP.NET Core issue.

 **NOTE**: These instructions assume familiarity with setting up an environment and SQL Server provisioning.

1. Create new solution in VS2015 for ASP.NET Core as Web Application and Local Account authentication enabled
2. Create folders Site1 and Site2 under c:\inetpub
2. Setup IIS to host 2 different domains as per the requirements
3. Edit appsettings.json and add the key Name:

```
{
  "ConnectionStrings": {
   "DefaultConnection": "Server=(local);Database=DemoApp;Trusted_Connection=True;MultipleActiveResultSets=true"
   }
  "Name": "Site 1",

```

4. Modify Startup.cs:

```
   Configuration = builder.Build();
   LocalEnv = Configuration["Name"];
}

public static string LocalName {get; private set;}
public static IConfigurationRoot Configuration {get; private set;}
```

4. Edit Views\_Layout.cshtml and modify navbar brand:

`<a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">@Startup.LocalName</a>`


5. Publish to local filesystem
6. Copy published files to both folders
7. Modify site2 appsettings.json and change name too site2
8. Open a browser and register in site1
9. Open another tab and login to site2 
10. Validate both websites show different names in the navbar
