### ISSUE TITLE
Update the Roadmap

### ISSUE THREAD

**Issue by MJomaa** [aspnet/Home#1841]
The Roadmap is out of sync.

https://github.com/aspnet/Home/wiki/Roadmap

1.0.3 and 1.0.4 are estimated to be released in Q4, but we have 1.1 already.

**Comment by Tratcher** [comment]
The roadmap is already current. 1.0.x will continue to receive patch updates even after 1.1 due to our long term support policy. Similarly 1.1.x may receive patch updates even after 1.2.

**Comment by Tratcher** [comment]
@DamianEdwards Where is the support policy documented?

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
