### ISSUE TITLE
DotNet Core 1.1.0 Project still referencing version 1.0.1

### ISSUE THREAD

**Issue by Chad-Hollenbeck** [aspnet/Home#1843]
I have a project referencing the correct version of dotnet core (1.1.0) in my project.json file:
<img width="131" alt="core-version" src="https://cloud.githubusercontent.com/assets/12432953/20566050/d0ed1fc2-b161-11e6-97a9-14870c3aeaa6.PNG">

I have both the 1.1.0 runtime and SDK installed. Version included below:
<img width="488" alt="version" src="https://cloud.githubusercontent.com/assets/12432953/20566901/c31b7378-b164-11e6-99ae-003d4152db11.PNG">

When run dotnet build, everything works fine:
<img width="489" alt="build" src="https://cloud.githubusercontent.com/assets/12432953/20566753/44c82020-b164-11e6-84fb-817b7d17bca4.PNG">

The dotnet command throws the following error:
<img width="490" alt="runtime err" src="https://cloud.githubusercontent.com/assets/12432953/20566783/53ca73a2-b164-11e6-9d3d-c6e62dffd90a.PNG">

**Comment by Chad-Hollenbeck** [comment]
Not sure what changed, but after uninstalling and reinstalling version 1.1.0 and updating the global.json sdk version from 1.0.0-preview2-003131 to 1.0.0-preview2-1-003177 everything is working fine.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
