### ISSUE TITLE
Web Deploy to IIS 8 prevented by locked process even when AppOffline rule handler is enabled

### ISSUE THREAD

**Issue by NameOfTheDragon** [aspnet/Home#1844]
When I use `MSDeploy` to deploy my Core 1.1.0 app targeting .NET Framework 4.6.2 to IIS8 on a remote server, the deploy fails with the following message:

> Error		More Information: Web Deploy cannot modify the file 'TA.MyMvcApp.exe' on the destination because it is locked by an external process.  In order to allow the publish operation to succeed, you may need to either restart your application to release the lock, or use the AppOffline rule handler for .Net applications on your next publish attempt.

During the deployment process, an `App_Offline.htm` file is created as expected. This does indeed bring down the app domain, as evidenced in the stdout log file, where I see the message `Application shutting down...`

However, the deployment still fails because the exe file remains locked (as evidenced in the event log). There would seem to be a race condition where MSDeploy is trying to overwrite the application .exe file before it has actually exited.

Once this error occurs, the `App_Offline.htm` file remains on the server so the web site is down until manual intervention occurs.

If the deploy operation is immediately re-tried, then the operation succeeds and the App_Offline.html file is removed. However, the operation should work first time every time.

**Comment by GuardRex** [comment]
Compare to https://github.com/aspnet/IISIntegration/issues/301 ... might be the same issue.

**Comment by Tratcher** [comment]
This issue was moved to aspnet/Tooling#885
