### ISSUE TITLE
Running .net core application as windows service

### ISSUE THREAD

**Issue by rpundlik** [aspnet/Home#1845]
Hello All,
I am trying to create and run the .net core application as windows service. While creating the service I am using `WebHostService` class where `OnStarted,OnStarting` etc such method are overridable.
So my question is in which method I should write my business logic(like getting data from db ett.) Started or Starting ?
Because previously we used to write in OnStart method but that is not available(it is sealed method)
Or do I need to use `ServiceBase` class to use OnStart method ?
Below is my class

```
public class SendMailHostService : WebHostService
    {
        private readonly EventLog _log = new EventLog("Application") { Source = "Application" };
        public SendMailHostService(IWebHost host) : base(host)
        {

        }
        protected override void OnStarted()
        {
//#if DEBUG
//            Thread.Sleep(30000);
//#endif
            Console.WriteLine("Asp.net service started.");
            Console.ReadLine();
            base.OnStarted();
        }
        protected override void OnStarting(string[] args)
        {
            //#if DEBUG
            //            Thread.Sleep(30000);
            //#endif

            Console.WriteLine("Asp.net service starting.");
            Console.ReadLine();
            base.OnStarting(args);
        }
}
```
Also when I run the service using net start command nothing is printed on the command prompt ? why is it so ?

Thanks for the help !

**Comment by GuardRex** [comment]
I don't think `ServiceBase` has been ported to Core yet. See: https://github.com/dotnet/corefx/issues/6024

**Comment by JanEggers** [comment]
you  can use Microsoft.AspNetCore.Hosting.WindowsServices

and then in Program.cs

if ( args == "-service" )
            {
                host.RunAsService();
            }
            else
            {
                host.Run();
            }

**Comment by PeterKottas** [comment]
Hi there, I think I have exactly what you are looking for. Check this out, hope it helps : https://github.com/PeterKottas/DotNetCore.WindowsService

**Comment by h3smith** [comment]
I know this won't help everyone, but the easiest solution for us was to drop a CLI application in Docker and tell Docker to restart it if it failed.

**Comment by PeterKottas** [comment]
Yep for docker that's probably the best solution.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
