### ISSUE TITLE
Route or controller problem in IIS publishing 

### ISSUE THREAD

**Issue by Kirua88** [aspnet/Home#1846]
Hi

2 weeks ago, publishing in IIS by files worked fine.
I have a BaseController to redirect in Login page or Home page at launch. working in debug and 2 weeks ago.
Now when I launch my webapp (localhost:80) i have 404 error. 
When I add /Login in url it works fine. But /Home do nothing.

It seems my BaseController not running.
What can be the problem ?

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
