### ISSUE TITLE
Sending SIGHUP signal terminates asp.net core app

### ISSUE THREAD

**Issue by Ozonni** [aspnet/Home#1848]
Hi there,

Seems like sending SIGHUP signal terminates the process. I didn't find any documentation how asp.net core handles signals but is it expected behavior?

Thanks.

**Comment by Ozonni** [comment]
According to this https://github.com/dotnet/coreclr/issues/3305

SIGHUP terminates the process.

**Comment by davidfowl** [comment]
That's a question to ask on that issue, not really an ASP.NET question.
