### ISSUE TITLE
Program Files\dotnet versions

### ISSUE THREAD

**Issue by grahamehorner** [aspnet/Home#1850]
The folders in which the SDKs are installed seem to be incorrect; and are causing confusions.
I have installed the SDKs using the MSI installers provided on the .../net/download/core page; yet the sdk directory structure only shows the :-
1.0.0-preview2-003131
1.0.0-preview2-003133

folders? no sign of versions 1.0.1 or 1.1.0 anywhere in the directory structure on the system; yet the installer claims it's installed ?

**Comment by pranavkm** [comment]
@grahamehorner the CLI versions don't line up with the release although the shared runtime that they shipped with (%ProgramFiles%\shared\Microsoft.NETCore.App) should specify the versions you're looking for. You might want to post in https://github.com/dotnet/cli/issues if you want further clarification about these versions.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
