### ISSUE TITLE
Any chance to announce the End of support to VB.Net?

### ISSUE THREAD

**Issue by ricardomlourenco** [aspnet/Home#1851]
1. Why does Microsoft still supports Vb.Net?
2. Is not that a strategy that slow down the asp and the .Net world?
3. Is not already time to give up on VB and move forward with C#? Just like you guys gave up on WebForms to move on with Mvc which is a much much better way to develop Web Apps on asp.net?
4. I'm not sure but the amount of work you guys spend trying to support VB on .Net could be used in order to create a tool to convert VB Projects to C#?

I'm saying that because we can see today people who still insists on VB.Net and usually they are tied to WebForms and all old technologies.

Isn't time to say goodbye to VB and concentrate all efforts on C# now?

Common excuse: Oh we support VB due to lots of customers still using it. But aren't they still using because you guys still supporting it?

Suggestion: Please create a nice tool to help on conversion of those projects to C# and LET'S MAKE .NET GREAT AGAIN!
=)

Actually there is a Telerik tool to convert VB to C# which is very good:
http://converter.telerik.com/

Knowing issues: if you have lots of arrays they aren't converted properly due to parenthesis.

Regards,
Ricardo Lourenco

**Comment by simonmurdock** [comment]
I think there are too many big old enterprise apps still using VB to drop it completely.

**Comment by ricardomlourenco** [comment]
Agree, but if they drop the support the Companies are forced to change just like they are doing with Mvc and it's being painful but it's bringing great results such as separation of concerns, best practices, unit tests, Dependency Injection etc.

**Comment by whiskeysauer** [comment]
Why are you so worried about it???? Don't like it? Don't use it. I can't imagine someone ACTUALLY creating a Github issue because they want a technology to go away - that they don't use.

"Force companies to change..." This is a good strategy??

**Comment by ricardomlourenco** [comment]
I appreciate your comments, please see my answers below:

"Why are you so worried about it?"
- Because if they keeping supporting this language it takes a lot of effort from Microsoft and they could use this effort to keep improving .Net

"Don't like it? Don't use it."
- Clearly, you've never worked for Big Companies with legacy systems. I have no option for "don't use it" since the Company is still using. It's just like Windows XP. Once they end the support for technologies, the company usually is forced to migrate the projects.
For my personal projects, I've never used VB or VB.net since 2002!

"I can't imagine someone ACTUALLY creating a Github issue because they want a technology to go away - that they don't use."
- Well,  it was just a way to communicate with Microsoft. Maybe it's not the best way. I'm opened to suggestions

"Force companies to change..." This is a good strategy??
- Another example that you have no clue about big companies with legacy system. 
- Look there's a lot of ways to do that. I think yes, it's a good strategy. Usually, non tech companies don't give a damn about technology! Since the system works (even poorly or with glitches) they usually keep the technology until Microsoft ends the support. 
Otherwise, you would see companies still using Windows NT or XP even today.

**Comment by whiskeysauer** [comment]
It's not a different technology. It's a different language. The binary that comes out of the clr is exactly the same. It's just two ways to talk to the compiler. If I'm looking for a dotnet library, I'm not searching for a c# or VB.net library. There's no such thing. The dll is the same at the end. If I want to tweak it a little, I can still do that by using the language it was written in (assuming I have the source). But whining that there are other languages to write code in? Really?

**Comment by hughesdo** [comment]
Seriously, VB.net is not going away.  I can program in both c# and vb.net but prefer vb.net.   Neither are newer or older. 

Anything c# can do,  vb.net can do and visa versa.  

I would also hate to tell this person COBOL is not going away either and there are NEW programs being written in COBOL everyday too.

**Comment by kieronmatthews** [comment]
The main point is that some companies are heavily invested in vb.net.
all our programmers and code libraries are written in it.
The cost of converting them and retraining our staff would run in to the 100's of thousands.
Like whiskeysauer said it is just a different syntax for the compiler to know.

The only extra work would be maintaining the complier and the templates!
