### ISSUE TITLE
Microsoft.NETCore.App 1.1.0 Console App can not be debugged.

### ISSUE THREAD

**Issue by barbarosalp** [aspnet/Home#1853]
Hello,

This is my **global.json**
```
{
  "projects": [ "src", "test" ],
  "sdk": {
    "version": "1.0.0-preview2-003131"
  }
}
```

and **project.json**
```
{
  "buildOptions": {
    "emitEntryPoint": true,
    "copyToOutput": [
      "appsettings.json"
    ]
  },
  "dependencies": {
    "Microsoft.Extensions.Configuration": "1.1.0",
    "Microsoft.Extensions.Configuration.Json": "1.1.0",
    "Microsoft.Extensions.DependencyInjection": "1.1.0"
  },
  "frameworks": {
    "netcoreapp1.1": {
      "dependencies": {
        "Microsoft.NETCore.App": {
          "version": "1.1.0",
          "type": "platform"
        }
      },
      "imports": "dnxcore50"
    }
  },
  "version": "1.0.0-*"
}
```

It's almost an empty .net core Console App. 
It builds successfuly but if I want to debug it some window is flashing and Visual Studio gets out of debug view immediately. No errors, no warnings...

What am I doing wrong?

Thanks.

**Comment by davidfowl** [comment]
Did you look at the debug output? Also, what happens when you run without debug?

**Comment by barbarosalp** [comment]
Here is the debug output:

```
The program '[17416] dotnet.exe' has exited with code -2147450749 (0x80008083).
The program '[17416] dotnet.exe: Program Trace' has exited with code 0 (0x0).
```

**Comment by barbarosalp** [comment]
I think I have found what it is all about. Yesterday I downloaded the "LTS" version. I have clicked the "Current" tab on the download page. I will get back here if this problem will be gone after the "Current" version which is 1.1.0.

**Comment by barbarosalp** [comment]
@davidfowl The issiue has gone after I download the "Current" version. We can close this.
Thanks for your help.

**Comment by alexdegroot** [comment]
The error message is horrible.
When you go to the websites related to .NET Core, you've to become an expert to understand where you can download it.
Turns out that 1.1 doesn't have Long Term Support. So once you click on 25 things you figure out that somewhere on the download page, somewhere in between another 25 links you have to download something. And luckily... then it works.....
