### ISSUE TITLE
Suggestion: Console Logger, use different color for SQL queries

### ISSUE THREAD

**Issue by VaclavElias** [aspnet/Home#1855]
I am using default Console Logging for analyzing my SQL queries.  Is there any easy way to color differently (whatever color you decide) SQL queries so it stands out from gibberish around it?

I would like to keep the other logs there but just see quickly where the SQL query starts and ends.

When you quickly look into the attached image (some text redacted), you see white gibberish and your brain must make an effort to find SQL query.  Imagine, of course the log is loooong. I wonder it would be nice to see quickly the SQL query without making your brain explode by simply making a color of SQL query different.

![image](https://cloud.githubusercontent.com/assets/4528464/20841864/4bcad886-b8ad-11e6-936e-397c276c64ae.png)

What is your say? Anybody likes this idea?

..not sure if it is possible and how easy it would be.

**Comment by h3smith** [comment]
I like!

**Comment by cwe1ss** [comment]
You could use [Serilog](https://github.com/serilog/serilog-extensions-logging) and its [Literate Console Sink](https://github.com/serilog/serilog-sinks-literate). Not sure if it colors exactly what you want but it probably gets you pretty close.

**Comment by Tratcher** [comment]
Please move this to the Logging repo

**Comment by VaclavElias** [comment]
Thanks @cwe1ss I will look into it as well :)

**Comment by VaclavElias** [comment]
Moved to https://github.com/aspnet/Logging/issues/530
