### ISSUE TITLE
File Nesting in ASP.NET Core projects

### ISSUE THREAD

**Issue by ciel** [aspnet/Home#1856]
I'm not sure this is the right place for this topic, as I'm a bit confused; I first went to the [ASP.NET Tooling](https://github.com/aspnet/Tooling) repository, and its [Contribution Guidelines](https://github.com/aspnet/Tooling/blob/master/CONTRIBUTING.md) pointed to the [aspnet/home repository](https://github.com/aspnet/Home/blob/dev/CONTRIBUTING.md), which pointed to this repository on the header about [**General Feedback and Suggestions**](https://github.com/aspnet/Home/issues)

So if this is the wrong place, I'm sorry.

In Visual Studio 2015, we had file nesting via this amazing [extension](https://marketplace.visualstudio.com/items?itemName=MadsKristensen.FileNesting)

However, in Visual Studio 2017 RC, that functionality no longer works outside of the built in file nesting for things like JavaScript/TypeScript.

This was a really valuable tool, and the author (@madskristensen) says that it can't be made to work in ASP.NET Core unless the tooling team makes changes. This was a very important part of my workflow for C# files, so I really hope the ASP.NET team will give this another look.

**Comment by Tratcher** [comment]
This issue was moved to aspnet/Tooling#894
