### ISSUE TITLE
HTTP Error 502.3 - Bad Gateway when timeout.

### ISSUE THREAD

**Issue by Bartmax** [aspnet/Home#1857]
Executing this code:
```
public async Task<IActionResult> Test()
{
    await Task.Delay(TimeSpan.FromMinutes(5)); // simulate some time consuming process.
    System.IO.File.WriteAllText("testfile.txt", "some content");
    return Content("done");
}
```
returns a 502.3 Bad Gateway error.
![image](https://cloud.githubusercontent.com/assets/3386797/20869163/33c32e6a-ba4b-11e6-9639-c73891ead2e2.png)

The file **DOES GET GENERATED/CREATED**

How can I change the timeout (or whatever settings) that can help me avoid this ?
Can the error be more friendlier ?

**Comment by Tratcher** [comment]
See requestTimeout in https://docs.microsoft.com/en-us/aspnet/core/hosting/aspnet-core-module

**Comment by Bartmax** [comment]
@Tratcher thanks, it would be great if the error was shown as "timeout" instead of Bad Gateway error talking about something called CGI that has nothing to do with the real issue.

**Comment by davidfowl** [comment]
@Bartmax welcome to IIS error pages 😄

**Comment by Tratcher** [comment]
@pan-wang @shirhatti some user feedback

**Comment by shirhatti** [comment]
This issue was moved to aspnet/AspNetCoreModule#48
