### ISSUE TITLE
IIS url rewrite with custom provider routing to Asp.Net core applications hosted by AspNetCoreModule

### ISSUE THREAD

**Issue by Matasx** [aspnet/Home#1858]
Hi,

I am facing following scenario:
- Business case: routing customer aliases specified in URL to correct application version, e.g.:
   - /customer1/request -> /1.0.0/request
   - /customer2/request -> /1.0.5/request
   - /customer3/request -> /1.0.0/request
- I am hosting multiple **Asp.Net Core** applications **side by side** via AspNetCoreModule on IIS (it uses pool 'No Managed Code')
   - Each application represents the same product on different version
- I need to be able to route requests to specific application based on entry url
- I **cannot expose rewrited url** back to the client (otherwise I could use redirect instead of rewrite, but it is not my case)
- Routing is done via **custom** url rewrite **provider**, because it resolves rules based on settings in database

I cannot make it work, because:
- IIS URL rewrite must run in the same App Pool as the target application
   - That means 'No Managed Code'
- I need to use custom url rewrite provider, but it can only run on pool with managed code

How am I supposed to route requests to multiple Asp.Net Core applications on IIS? 
Is there any way to achieve this?

**Comment by GuardRex** [comment]
@Matasx Move this over to IISIntegration repo issues: https://github.com/aspnet/IISIntegration/issues

**Comment by Matasx** [comment]
Moved to https://github.com/aspnet/IISIntegration/issues/309
