### ISSUE TITLE
EditorFor property returns empty

### ISSUE THREAD

**Issue by raime910** [aspnet/Home#1859]
I created a simple SingleSelectDropdownlist view model to avoid writing html and classes over and over again. This class has a property called Options (where options are stored for the dropdown) and SelectedValue (a string property to store selected value) and a Placeholder property.

```
@model SingleSelectDdl
@{
    var options = new SelectList(Model.Options, "Value", "Text", string.Empty);
}
<select asp-for="SelectedValue" asp-items="options" class="form-control" placeholder="@Model.Placeholder"></select>
<span asp-validation-for="SelectedValue"></span>
```

After upgrading to .NET Core 1.1.0 I noticed that the SelectedValue property doesn't return any value anymore, it just returns an empty string no matter what I do.

**Comment by Tratcher** [comment]
@rynowak @NTaylorMullen?

**Comment by dougbu** [comment]
@raime910 there's a lot of moving parts in your description but not much code. What is supposed to set `SelectedValue` in the model? When should it run? Have you debugged to see what of your code is or is not executing? Where is the `EditorFor()` call mentioned in the title?

**Comment by raime910** [comment]
@dougbu The selected value is set when the user changes it on the view. It's a simple form with input tags and selects (dropdownlists) within it. When I push the submit button and inspect the model that was returned from the view - the SelectedValue property returns an empty string. It should be the Id of the selected option on the dropdownlist. 

I rolled back my references of anything Microsoft.AspNetCore.* to 1.0.1 and it started working again. Can you point me to the code in aspnetcore where the mapping from posted model to the parameter of an action happens. I'll gladly investigate it myself.

**Comment by dougbu** [comment]
> I'll gladly investigate it myself.

That's a kind offer but model binding is done in a fair number of places. It's hard to point you in a single direction for this type of issue.

If code snapshots aren't a good idea for your company, feel free to contact me privately using my GitHub alias at microsoft dot com. If sharing the code is :ok:, I'd like to see at least your `project.json` file and `Startup` class. Ideal would be a repro project hosted in a public GitHub repository.

**Comment by raime910** [comment]
This was resolved by switching to Microsoft.AspNetCore.* to 1.0.1. Not sure if this is a valid fix but I am closing this.
