### ISSUE TITLE
aspnet mvc 1.1 and vs2015

### ISSUE THREAD

**Issue by dazinator** [aspnet/Home#1861]
Hello,

I would like to upgrade my MVC 6 website from 1.0.1 to 1.1.0.

My question is, there are various tooling packages that are at preview2 like:

```
 "Microsoft.AspNetCore.Razor.Tools": {
      "version": "1.0.0-preview2-final",
      "type": "build"
    },

```

I am using VS2015. 

Am I ok to upgrade these tools to `preview-3` or does the preview 3 tooling only work with VS 2017?

**Comment by pranavkm** [comment]
Here's the set of package versions that were released as part of the 1.1.0 release: https://github.com/aspnet/Home/issues/1827#issuecomment-261340789.

**Comment by dazinator** [comment]
Thank you. What is confusing me is this page:

![image](https://cloud.githubusercontent.com/assets/3176632/20933537/463497e2-bbd0-11e6-8f2f-b8e9b8934269.png)

I am struggling to see the link between:

Visual Studio 2015 Tools (Preview 2) *

and whether that means I should be sticking to preview2 tooling nuget packages. The nuget packages released with 1.1.0 are preview4 - does that correlate to a Visual Studio 2015 Tools version that I need also have installed?

**Comment by pranavkm** [comment]
For the time being, the versioning scheme for tools is that they match the version of the SDK. So 1.0.0-* are meant to work with the LTS (1.0.x) release and 1.1.0-* are meant to work with the Current 1.1.0 release.

**Comment by dazinator** [comment]
Ok got ya, thanks for the clarification!
