### ISSUE TITLE
Releases and Dependencies in 1.1

### ISSUE THREAD

**Issue by dazinator** [aspnet/Home#1862]
This is a general discussion about NuGet package versioning and releasing, and what I perceive to be an issue.

I am going to talk in the context of EF7 a lot here, but I don't think this is restricted to EF7 per say, I just want to use something concrete.

My current application is using `1.0.0` packages, including MVC 6 and EF 7 Core.

Here were the dependencies for EF7 Core 1.0.0

![image](https://cloud.githubusercontent.com/assets/3176632/20937326/696a3ba0-bbde-11e6-8fe2-97a635da7d15.png)

Recently we have discovered some issues in EF7 version 1.0.0. 
So naturally I wanted to see if there was a later version available to see if these issues were fixed by a new release.

So I check NuGet and see that version 1.1.0 of EF7 Core has been released and I see that version 1.1.0 is now available (I interpret version changes according to SemVer spec so this to me, signals a minor update - i.e new features, no major or breaking changes for my appliation),

However looking at the dependencies for EF7 1.1.0:

![image](https://cloud.githubusercontent.com/assets/3176632/20936469/9f9f2090-bbda-11e6-9816-7118aca463b5.png)

And this is only the EF7 core package, there is ofcourse the SQL provide package, and the InMemory stroe package each with similar dependency updates (i.e many dependencies have been moved from 1.0.0 to 1.1.0 versions)

So it turns out, that in order to adopt a minor update to EF7, I have to update huge swathes of my applications dependencies.
  
My concern (which is speculative at this point) is that I am being forced to update these dependencies within my application, not because EF7 actually requires these later versions of dependencies, i.e to fix any issues, but just because the release is being "aligned" for some reason, i.e some policy where Microsoft are essentially saying, we will release all the 1.1.0 bits, and they all must force 1.1.0 dependencies - not because those components necessarily need them to function, but just because we want it aligned that way.

This is making updating packages for my application a mammoth challenge, as to update just the data library in my application (EF 7) I end up having to update pretty much my entire project to be aligned with 1.1.0.

This is creating so much churn for my application, and what should be simple updates are anything but that.

IMHO, I believe  EF7 (and other packages) shouldn't force dependency updates because of any policy, but only because they are absolutely necessary to resolve issues with the functionality of that package.

For example, if EF7 1.1.0 had kept the same versions of dependencies in it's nuspec file as 1.1.0, then I could adopt EF7 1.1.0 - gain all its new functionality, with minimal churn. 

Perhaps someone could just clarify what the reasoning is behind this and whether my concern is warranted.

**Comment by pranavkm** [comment]
cc @DamianEdwards

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
