### ISSUE TITLE
Unable to use core 1.1 with ASP.NET Core Web Application (.Net Framework)

### ISSUE THREAD

**Issue by redowl3** [aspnet/Home#1865]
1. Create new ASP.NET Core Web Application (.Net Framework) 
2. Select Web Applications
3. Change Authentication to User Accounts
4. Update Nuget packages
5. Run from Visual Studio
6. Error - FileLoadException: Could not load file or assembly 'Microsoft.AspNetCore.Http.Features, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

I'm running Windows 10, VS2016 Update 3

**Comment by Tratcher** [comment]
See this thread: https://github.com/aspnet/Home/issues/1826

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
