### ISSUE TITLE
CompilationFailedException in ASP.NET Core (.Net Framework) in Visual Studio 2017 RC 

### ISSUE THREAD

**Issue by tedypranolo** [aspnet/Home#1866]
To repro this error. In Visual Studio 2017 RC create a new ASP.NET Core Web Application (.Net Framework) project. Add this code in Index.cshtml
```csharp
Dictionary<string, string> test = new Dictionary<string, string>();
var test2 = new string[] { "Test" };
Dictionary<string,string> test3 = test2.ToDictionary<string,string>(x => x);
```
The error is :
CompilationFailedException 
 The type 'Dictionary<,>' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Collections, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
![dicterror](https://cloud.githubusercontent.com/assets/3522930/20974328/c9060d98-bcd6-11e6-8f02-9c6aee893ed6.png)

The exception is caused by the ToDictionary() call. It complains about not knowing Dictionary<,> , but instantiating an empty dictionary as in the first line works just fine. Also, this will only happen in razor (cshtml) , the same code works in regular c# class.

**Comment by NTaylorMullen** [comment]
This is an SDK issue; I've pinged the team in a supposedly closed [issue](https://github.com/dotnet/sdk/issues/111) about this not being fixed.
