### ISSUE TITLE
Possible type equality bug using generics and the `==` operator after deserialization.

### ISSUE THREAD

**Issue by Carl-Hugo** [aspnet/Home#1867]
### Title
Possible type equality bug using generics and the `==` operator after deserialization.

### Scenario
I was implementing an `IEqualityComparer<T>` to simplify my life, and all my tests worked fine until I compared a deserialized version of the same objects.

### Functional impact
The `==` operator does not behave the same after deserialization as when no serialization is involved.

The comparison of two values using the `==` operator should be the same with or without serialization involved (consistency).

### Minimal repro steps
I created a full repro project here, including a workaround (under `MyClassEqualityComparer.AlternateEquals(...)`): 
https://github.com/Carl-Hugo/ReproGenericEqualityNetCoreBug

*Please note that, for simplicity sake, `MyClassEqualityComparer` does not implement `IEqualityComparer<T>` since it was not needed.*

The minimal repro steps are:
```CSharp
namespace ReproProject
{
    public class MyClass<T>
        where T : class
    {
        public MyClass() { }

        public MyClass(T value)
        {
            Value = value;
        }

        public virtual T Value { get; set; }
    }

    public class MyClassEqualityComparer<T>
        where T : class
    {
        public bool Equals(MyClass<T> x, MyClass<T> y)
        {
            var sameValue = x.Value == y.Value;
            return sameValue;
        }
    }
    public class Program
    {
        private static MyClassEqualityComparer<string> Comparer { get; } = new MyClassEqualityComparer<string>();

        public static void Main(string[] args)
        {
            var object1 = new MyClass<string>("My value 1");
            var object2 = new MyClass<string>("My value 1");

            var serializedObject1 = JsonConvert.SerializeObject(object1);
            var serializedObject2 = JsonConvert.SerializeObject(object2);

            var deserializedObject1 = JsonConvert.DeserializeObject<MyClass<string>>(serializedObject1);
            var deserializedObject2 = JsonConvert.DeserializeObject<MyClass<string>>(serializedObject2);

            var valuesAreEquals = Comparer.Equals(deserializedObject1, deserializedObject2); // this should be true since `"My value 1" == "My value 1"`
            Console.WriteLine($"Values ({deserializedObject1.Value}|{deserializedObject2.Value}), with serialization, should be equals: {valuesAreEquals}");
            Console.Read();
        }
    }
}
```

### Expected result
The method call `Comparer.Equals(...)` should return `true` since `"My value 1" == "My value 1"`, compared by the following: `x.Value == y.Value`.

### Actual result
The result is `false`.

### Conclusion
I hope this is the right place; it is a bit hard to figure out to what repo a general issue should be posted to.

If it is not, feel free to point me the right way :)

**Comment by davidfowl** [comment]
It's not, this isn't an ASP.NET problem (if it's a problem to begin with). File it on http://github.com/dotnet/corefx

**Comment by Carl-Hugo** [comment]
Thanks, makes sense, I posted it there: https://github.com/dotnet/corefx/issues/14904
