### ISSUE TITLE
NuGet package update results in error

### ISSUE THREAD

**Issue by wstaelens** [aspnet/Home#1868]
> Can not find runtime target for framework '.NETCoreApp,Version=v1.0' compatible with one of the target runtimes: 'win10-x64, win81-x64, win8-x64, win7-x64'.

created a new VS2015 asp.net core mvc application.
I could build.
Updated my NuGet packages --> error.
bug? 😕 

note: I was following this: https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/start-mvc

**Comment by Tratcher** [comment]
Can you share your project.json before and after? There was an issue with older versions of nuget where it would drop the "Platform" attribute from the Microsoft.NETCore.App dependency.

**Comment by wstaelens** [comment]
Some config from before:

```
{
  "userSecretsId": ";-)",

  "dependencies": {
    "Microsoft.NETCore.App": {
      "version": "1.0.1",
      "type": "platform"
    },
    "Microsoft.AspNetCore.Authentication.Cookies": "1.0.0",
    "Microsoft.AspNetCore.Diagnostics": "1.0.0",
    "Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore": "1.0.0",
    "Microsoft.AspNetCore.Identity.EntityFrameworkCore": "1.0.0",
    "Microsoft.AspNetCore.Mvc": "1.0.1",
    "Microsoft.AspNetCore.Razor.Tools": {
      "version": "1.0.0-preview2-final",
      "type": "build"
    },
    "Microsoft.AspNetCore.Routing": "1.0.1",
    "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0",
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.1",
    "Microsoft.AspNetCore.StaticFiles": "1.0.0",
    "Microsoft.EntityFrameworkCore.SqlServer": "1.0.1",
    "Microsoft.EntityFrameworkCore.SqlServer.Design": {
      "version": "1.0.1",
      "type": "build"
    },
    "Microsoft.EntityFrameworkCore.Tools": {
      "version": "1.0.0-preview2-final",
      "type": "build"
    },
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.0.0",
    "Microsoft.Extensions.Configuration.Json": "1.0.0",
    "Microsoft.Extensions.Configuration.UserSecrets": "1.0.0",
    "Microsoft.Extensions.Logging": "1.0.0",
    "Microsoft.Extensions.Logging.Console": "1.0.0",
    "Microsoft.Extensions.Logging.Debug": "1.0.0",
    "Microsoft.Extensions.Options.ConfigurationExtensions": "1.0.0",
    "Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.0.0",
    "Microsoft.VisualStudio.Web.CodeGeneration.Tools": {
      "version": "1.0.0-preview2-final",
      "type": "build"
    },
    "Microsoft.VisualStudio.Web.CodeGenerators.Mvc": {
      "version": "1.0.0-preview2-final",
      "type": "build"
    }
  },

  "tools": {
    "BundlerMinifier.Core": "2.0.238",
    "Microsoft.AspNetCore.Razor.Tools": "1.0.0-preview2-final",
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.0.0-preview2-final",
    "Microsoft.EntityFrameworkCore.Tools": "1.0.0-preview2-final",
    "Microsoft.Extensions.SecretManager.Tools": "1.0.0-preview2-final",
    "Microsoft.VisualStudio.Web.CodeGeneration.Tools": {
      "version": "1.0.0-preview2-final",
      "imports": [
        "portable-net45+win8"
      ]
    }
  },

  "frameworks": {
    "netcoreapp1.0": {
      "imports": [
        "dotnet5.6",
        "portable-net45+win8"
      ]
    }
  },

  "buildOptions": {
    "emitEntryPoint": true,
    "preserveCompilationContext": true
  },

  "runtimeOptions": {
    "configProperties": {
      "System.GC.Server": true
    }
  },

  "publishOptions": {
    "include": [
      "wwwroot",
      "**/*.cshtml",
      "appsettings.json",
      "web.config"
    ]
  },

  "scripts": {
    "prepublish": [ "bower install", "dotnet bundle" ],
    "postpublish": [ "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%" ]
  }
}
```

current config:

```
{
  "userSecretsId": ";-)",

  "dependencies": {
    "Microsoft.VisualStudio.Web.CodeGeneration.Tools": {
      "version": "1.0.0-preview2-final",
      "type": "build"
    },
    "Microsoft.VisualStudio.Web.CodeGenerators.Mvc": {
      "version": "1.0.0-preview2-final",
      "type": "build"
    },
    "BundlerMinifier.Core": "2.2.306",
    "Microsoft.AspNetCore.Authentication.Cookies": "1.1.0",
    "Microsoft.AspNetCore.Diagnostics": "1.1.0",
    "Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore": "1.1.0",
    "Microsoft.AspNetCore.Identity.EntityFrameworkCore": "1.1.0",
    "Microsoft.AspNetCore.Mvc": "1.1.0",
    "Microsoft.AspNetCore.Routing": "1.1.0",
    "Microsoft.AspNetCore.Server.IISIntegration": "1.1.0",
    "Microsoft.AspNetCore.Server.Kestrel": "1.1.0",
    "Microsoft.AspNetCore.StaticFiles": "1.1.0",
    "Microsoft.EntityFrameworkCore.SqlServer": "1.1.0",
    "Microsoft.EntityFrameworkCore.SqlServer.Design": "1.1.0",
    "Microsoft.EntityFrameworkCore.Tools": "1.0.0-preview2-final",
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.1.0",
    "Microsoft.Extensions.Configuration.Json": "1.1.0",
    "Microsoft.Extensions.Configuration.UserSecrets": "1.1.0",
    "Microsoft.Extensions.Logging": "1.1.0",
    "Microsoft.Extensions.Logging.Console": "1.1.0",
    "Microsoft.Extensions.Logging.Debug": "1.1.0",
    "Microsoft.Extensions.Options.ConfigurationExtensions": "1.1.0",
    "Microsoft.NETCore.App": "1.1.0",
    //"Microsoft.NETCore.App": { "version": "1.1.0", "type": "platform" },
    "Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.1.0"
  },

  "tools": {
    "Microsoft.VisualStudio.Web.CodeGeneration.Tools": {
      "version": "1.0.0-preview2-final",
      "imports": [
        "portable-net45+win8+dnxcore50",
        "portable-net45+win8"
      ]
    },
    "Microsoft.EntityFrameworkCore.Tools": {
      "version": "1.0.0-preview2-final",
      "imports": [
        "portable-net45+win8+dnxcore50",
        "portable-net45+win8"
      ]

    }

  },

  "frameworks": {
    "netcoreapp1.0": {
      "imports": [
        "dotnet5.6",
        "portable-net45+win8"
      ]
    }
  },

  "buildOptions": {
    "emitEntryPoint": true,
    "preserveCompilationContext": true
  },

  "runtimeOptions": {
    "configProperties": {
      "System.GC.Server": true
    }
  },

  "publishOptions": {
    "include": [
      "wwwroot",
      "**/*.cshtml",
      "appsettings.json",
      "web.config"
    ]
  },

  "scripts": {
    "prepublish": [ "bower install", "dotnet bundle" ],
    "postpublish": [ "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%" ]
  },

  // Added this also:
  "runtimes": {
    "win10-x64": {}
  }
}
```

New to it and I have no idea what everything means or why it works or doesn't work. Let alone know what the effects are of adding e.g. win10-x64 or portable-net45+win8+dnxcore50 and portable-net45+win8.

**Documentations could be improved for beginners!** I have asp.net mvc 5 experience, but new to asp.net core. Lost already 2 hours to make it build (nuget update broke everything and dotnet ef migrations command didn't work). Followin' a tutorial and my DbSet's are not being applied. My Tables in the database are not being created and I have no idea if it is because of the config file because after the nuget update everything broke.

**Comment by GuardRex** [comment]
You'll want framework `netcoreapp1.1` to match your 1.1 packages.

If you plan to publish this app as a framework-dependent app (also called a "portable" app) to run in an environment where the shared framework is installed, then drop the `runtimes` section. Use the package `Microsoft.NETCore.App` *with* the `"type": "platform"` on it. The `"type": "platform"` just means that the packages within this metapackage will be on the "platform," so they will not be published with the app. You will restore, then publish with `dotnet publish -c Release`.

If you plan to publish this app as a self-contained app to run in an environment where the shared framework is not installed, then keep the `runtimes` section. Use the package `Microsoft.NETCore.App` *without* the `"type": "platform"` on it. You will restore, then publish for the RID (Runtime IDentifier) `win10-x64` specified in the `runtimes` section with `dotnet publish -c Release -r win10-x64`.

Comments are not supported in JSON files, so you should remove the comments and don't use them ... results are unpredictable if you do.

You have the script call for `publish iis` tooling in `postpublish`, but you don't have the actual tool. Add this to the `tools` section ...
```
"Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.1.0-preview4-final"
```
Your other tools refs are likely stale. I think they should be `1.1.0-preview4-final`. Those are easy to check at NuGet.org to make sure you have the latest for 1.1. Check the `imports` you have on tools against recent samples. Those tools may not need `imports` at this point. I don't use the ones you have in particular, so you'll need to check and see if those `imports` are still required.

The `imports` you see for the framework allow the use of the package regardless of its compatibility with the framework, so packages that don't specify they are capable of working with .NET Standard will be allowed. Of course, if you use a package API that isn't compatible with the framework, it will :boom: at runtime.

The docs are WIP, of course, as all of the new bits roll out. I think from your OP that you're aware of their locations: The ASP.NET Core docs are at https://docs.microsoft.com/en-us/aspnet/core/. The .NET Core docs are at https://docs.microsoft.com/en-us/dotnet/articles/core/index. What I describe above, you'll find in the .NET Core docs. Specifically, the two that might help the most are ...

https://docs.microsoft.com/en-us/dotnet/articles/core/packages
https://docs.microsoft.com/en-us/dotnet/articles/core/deploying/

Final Tips: From time-to-time you may run into an incoherence issue with packages, particularly when upgrading a project. I'm sure you're aware of deleting the `bin`/`obj` as one sledgehammer technique. The other is to clear package caches on the machine by either clearing them manually or using `nuget locals all -clear` with `nuget.exe` available from the NuGet.org website. It can help right the ship sometimes to nuke everything and restore the app's packages fresh. If you're publishing to IIS, there is an extensive Common Errors section in that doc. If you need to chat with devs and get help, swing by Slack chat. You can signup at http://tattoocoder.com/aspnet-slack-sign-up/.

**Comment by wstaelens** [comment]
Thanks for the comments and detailed information! 

Which this information was added to the documentation, similar like the documentation from TypeScript: http://www.typescriptlang.org/docs/handbook/tsconfig-json.html 

Removing the comments, deleting the obj/bin folders and reinstalling all packages did the trick.
(also had to restart VS to get dotnet ef command working again).

**Comment by GuardRex** [comment]
Sure ... no problem ... I'm glad it had a happy ending. :smile:

You might be able to get some schema info for `project.json` at http://schemastore.org/json/ ... however ... with `project.json` going away soon with the move to MSBuild/`csproj`, I'm not sure if the schema there is updated fully ... but you can get a lot out of it even if it isn't 100% accurate.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
