### ISSUE TITLE
netTcp WCF clients fail with update to 1.1

### ISSUE THREAD

**Issue by MikeInBA** [aspnet/Home#1870]
I have an asp.net core controller that has a repo that uses a netTcp WCF client to call in to a WCF service.  I used SecurityMode.Transport and TcpClientCredentialType.Certificate.  For the client (that is hosted by the asp.net core controller), I read the certificate thumbprint out of my appsettings.json.

This setup worked fine when my Microsoft.NETCore.App version was 1.0.1, but as soon as I change my dependency in project.json to 1.1 all my WCF calls fail with:

> An unhandled exception of type 'System.ExecutionEngineException' occurred in System.Private.CoreLib.ni.dll

this only happens when the credential type is set to Certificate.  Windows and None security modes work without issue.

**Comment by Tratcher** [comment]
WCF is over here: https://github.com/dotnet/corefx
