### ISSUE TITLE
CookieAuthentication Middleware not rerouting requests on authentication failure IISExpress 

### ISSUE THREAD

**Issue by seand88** [aspnet/Home#1873]
### Title
When using the cookie authentication middleware in an asp.net core application running in visual studio 2017 RC1 under IIS Express an unauthorized request is not rerouted to the appropriate handler.

### Functional impact
*Does the bug result in any actual functional issue, if so, what?*  
Yes, the issue is that the application does not respond properly and finishes the request pipeline without executing the correct code.

### Minimal repro steps
*What is the smallest, simplest set of steps to reproduce the issue. If needed, provide a project that demonstrates the issue.*  

1. Install Visual Studio RC1
2. Create a new ASP.net Core MVC Project
3. Set up cookie authentication middleware 
4. Add the [authorize] attribute to a controller class
5. Set the default route to go to that controller class
6. Add a controller for cookie authentication notauthorized actions
7. Configure cookie auth to go to those actions such as account/notauthorized
8. Run the application
9. Blank page is shown with no content
10. Check dev tools, it shows request was sent in header with new location to not authorized controller action
11. No redirect occurs

### Expected result
The request should redirect to the not authorized controller action and show the appropriate content on that page.

### Actual result
It just shows a blank page, request is sent to browser with new location in header but no redirect occurs

### Further technical details
What is strange is that when I switch the run target from IIS Express to the project directly (so it just runs under kestrel in the command window) the code works exactly as expected with no changes. 

Here is some of the code I am using to set up cookie authentication

```
            app.UseCookieAuthentication(new CookieAuthenticationOptions()
            {
                AuthenticationScheme = CookieAuthenticationDefaults.AuthenticationScheme,
                LoginPath = new PathString("/Account/NotAuthorized"),
                AccessDeniedPath = new PathString("/Account/Forbidden"),
                AutomaticAuthenticate = true,
                AutomaticChallenge = true
            });
```

**Comment by Tratcher** [comment]
Please share your dependencies and versions. This resembles an issue caused by mixing 1.0 and 1.1 packages.

**Comment by seand88** [comment]
Now that you said that I noticed that I was using Microsoft.AspNetCore.Authentication.Cookies 1.1, i uninstalled and change it to 1.0 and the issue went away.

I wasnt aware 1.0 and 1.1 components couldn't be mixed.

**Comment by Tratcher** [comment]
VS is still getting their template versioning sorted out.
