### ISSUE TITLE
[question] Can I use the latest EF/MVC packages (1.1.0)  in  dotnet 1.0.1  ?

### ISSUE THREAD

**Issue by John0King** [aspnet/Home#1875]
Can I use the latest EF/MVC packages (1.1.0)  in  dotnet 1.0.1  ?
Microsfot.EntityFrameworkCore.Sqlite 1.0.1  have a `decimal` convert issue , so I decide to update to 1.1.0,
but my server is installed the 1.0.1 version of dotnet runtime , and I can not just install dotnet runtime 1.1.0 (Server reboot is required if i install that ), so Can I use  Microsfot.EntityFrameworkCore.Sqlite 1.1.0 on dotnet runtime 1.0.1 ?

**Comment by seand88** [comment]
i have had issues mixing dependencies with 1.0 and 1.1
I would recommend not mixing them

**Comment by John0King** [comment]
@seand88  you are right ,it seems I have to update dotnet runtime to 1.1
