### ISSUE TITLE
Unable to update Microsoft.AspNetCore.Server.IISIntegration.Tools

### ISSUE THREAD

**Issue by CamiloTerevinto** [aspnet/Home#1876]
Under an ASP.NET Core 1.1.0 application running under "net461", I am completely unable to get past version 1.0.0-preview2-final. Both 1.0.0-preview3-final and 1.1.0-preview4-final error out the NuGet installation claiming that the package is not compatible with net461. 
I also have the problem if I try to update Microsoft.AspNetCore.Razor.Tools from 1.0.0 preview2 to 1.1.0.

Is this correct? Why are these packages incompatible with .NET Framework 4.6.1?

**Comment by davidfowl** [comment]
Show your project.json and global.json files.

**Comment by CamiloTerevinto** [comment]
I couldn't find a global.json, but here is the project.json:

`{
  "dependencies": {
    "Microsoft.AspNetCore.Authentication.Cookies": "1.1.0",
    "Microsoft.AspNetCore.Diagnostics": "1.1.0",
    "Microsoft.AspNetCore.Identity": "1.1.0",
    "Microsoft.AspNetCore.Mvc": "1.1.0",
    "Microsoft.AspNetCore.Razor.Tools": {
      "version": "1.0.0-preview2-final",
      "type": "build"
    },
    "Microsoft.AspNetCore.Routing": "1.1.0",
    "Microsoft.AspNetCore.Server.IISIntegration": "1.1.0",
    "Microsoft.AspNetCore.Server.Kestrel": "1.1.0",
    "Microsoft.AspNetCore.StaticFiles": "1.1.0",
    "Microsoft.EntityFrameworkCore": "1.1.0",
    "Microsoft.EntityFrameworkCore.Relational": "1.1.0",
    "Microsoft.EntityFrameworkCore.SqlServer": "1.1.0",
    "Microsoft.EntityFrameworkCore.SqlServer.Design": "1.1.0",
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.1.0",
    "Microsoft.Extensions.Configuration.Json": "1.1.0",
    "Microsoft.Extensions.Configuration.UserSecrets": "1.1.0",
    "Microsoft.Extensions.Logging": "1.1.0",
    "Microsoft.Extensions.Logging.Console": "1.1.0",
    "Microsoft.Extensions.Logging.Debug": "1.1.0",
    "Microsoft.Extensions.Options.ConfigurationExtensions": "1.1.0",
    "Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.1.0",
    "Microsoft.VisualStudio.Web.CodeGeneration.Tools": "1.1.0-preview4-final",
    "Microsoft.VisualStudio.Web.CodeGenerators.Mvc": "1.1.0-preview4-final",
    "Sendgrid": "8.0.5",
    "SendGrid.CSharp.HTTP.Client": "3.0.0"
  },

  "tools": {
    "Microsoft.AspNetCore.Razor.Tools": "1.0.0-preview2-final",
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.0.0-preview2-final"
  },

  "frameworks": {
    "net461": {
    }
  },

  "buildOptions": {
    "emitEntryPoint": true,
    "preserveCompilationContext": true
  },

  "publishOptions": {
    "include": [
      "wwwroot",
      "**/*.cshtml",
      "appsettings.json",
      "web.config"
    ]
  },

  "scripts": {
    "postpublish": [ "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%" ]
  }
}
`

**Comment by GuardRex** [comment]
`Microsoft.AspNetCore.Razor.Tools` and `Microsoft.AspNetCore.Server.IISIntegration.Tools` should be `1.1.0-preview4-final`.

**Comment by CamiloTerevinto** [comment]
@GuardRex  that's exactly what does not work.

**Comment by Nyaoso** [comment]
I am having a similar issue with .net 4.6.2 (full framework webapi project). 
Microsoft.AspNetCore.Server.IISIntegration.Tools 1.1.0-preview4-final does not support .Netframework 4.6.2.

The contents of my project.json file are:

{
  "dependencies": {
    "Microsoft.AspNetCore.Mvc": "1.1.0",
    "Microsoft.AspNetCore.Routing": "1.1.0",
    "Microsoft.AspNetCore.Server.IISIntegration": "1.1.0",
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.1.0-preview4-final",
    "Microsoft.AspNetCore.Server.Kestrel": "1.1.0",
    "Microsoft.EntityFrameworkCore": "1.1.0",
    "Microsoft.EntityFrameworkCore.Tools": "1.1.0-preview4-final",
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.1.0",
    "Microsoft.Extensions.Configuration.FileExtensions": "1.1.0",
    "Microsoft.Extensions.Configuration.Json": "1.1.0",
    "Microsoft.Extensions.Logging": "1.1.0",
    "Microsoft.Extensions.Logging.Console": "1.1.0",
    "Microsoft.Extensions.Logging.Debug": "1.1.0",
    "Microsoft.Extensions.Options.ConfigurationExtensions": "1.1.0"
  },

  "tools": {
    "Microsoft.EntityFrameworkCore.Tools": "1.1.0-preview4-final"
  },

  "frameworks": {
    "net462": { }
  },

  "buildOptions": {
    "emitEntryPoint": true,
    "preserveCompilationContext": true
  },

  "publishOptions": {
    "include": [
      "wwwroot",
      "**/*.cshtml",
      "appsettings.json",
      "web.config"
    ]
  },

  "scripts": {
    "postpublish": [ "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%" ]
  }
}

**Comment by natemcmaster** [comment]
This error is caused by having the package in the 'dependencies' section of project.json. To install the 1.1.0-preview4-final tool, make sure it is in the 'tools' section of project.json instead.

```json
{
   "tools": {
      "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.1.0-preview4-final"
    }
}
```

See https://docs.microsoft.com/en-us/aspnet/core/publishing/iis#publish-iis-tool for more details.
