### ISSUE TITLE
IResponseCookies.Delete fails to work in Chrome but works in Edge and Firefox

### ISSUE THREAD

**Issue by dodyg** [aspnet/Home#1877]
This is the code to replicate this behavior [source](https://github.com/dodyg/practical-aspnetcore/blob/master/hello-world-with-cookies-2/src/Program.cs)

This is another person that replicate the problem [source](https://www.reddit.com/r/dotnet/comments/5hznok/how_do_you_delete_a_cookie_in_aspnet_core/db4syx4/)

`dotnet -version` is `1.0.0-preview2-1-003177`

**Comment by Tratcher** [comment]
This issue was moved to aspnet/HttpAbstractions#743
