### ISSUE TITLE
Cant upload Image and save it in the wwwroot folder

### ISSUE THREAD

**Issue by mister-giga** [aspnet/Home#1878]
I try to save Image in wwwrooot folder but I get message:
'UnauthorizedAccessException: Access to the path 'G:\.....\NetCoreWebApp\wwwroot' is denied.

        [HttpPost("UploadFiles")]
        public async Task<IActionResult> UploadFiles(IFormFile file)
        {
            var filePath = _appEnvironment.WebRootPath;
            using (var stream = new FileStream(filePath, FileMode.Create))
            {
                await file.CopyToAsync(stream);
            }
            return Ok(new { filePath });
        }

**Comment by davidfowl** [comment]
Is this under IIS?

**Comment by mister-giga** [comment]
yes

**Comment by davidfowl** [comment]
Does the user running under IIS have write permission to the wwwroot folder?

**Comment by mister-giga** [comment]
I am debugging on my own pc, what permission may I need?
Or how can I set up permissions?
