### ISSUE TITLE
Failed to install "DotNetCore.1.0.1-VS2015Tools.Preview2.0.3" to VS2015 Update3

### ISSUE THREAD

**Issue by Matt-yochung** [aspnet/Home#1881]
I have my VS2015 update 3 successfully installed but failed to install the latest Net Core 1.0.1 Tooling preview. I tried a couple of time to repair it but still have the same issue.

I looked into the log file and I found this:
[1F88:1A48][2016-12-17T21:34:04]e000: Error 0x80070642: Failed attempt to download URL: 'https://download.microsoft.com/download/F/6/E/F6ECBBCC-B02F-424E-8E03-D47E9FA631B7/packages/AspNetCoreLocalFeed_69.msi'

I copied this link to browser and it can be downloaded though. I have attached the log file here and I do hope someone could help me out!!!

[log.txt](https://github.com/aspnet/Home/files/658755/log.txt)
![untitled](https://cloud.githubusercontent.com/assets/22286699/21285580/7105cbf6-c4a1-11e6-851e-f0fa72b41efb.png)

**Comment by Tratcher** [comment]
@joeloff

**Comment by salomoms** [comment]
I have the same problem.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
