### ISSUE TITLE
Publishing core app on the windows server

### ISSUE THREAD

**Issue by mister-giga** [aspnet/Home#1882]
Where can I find a documentation of how can I publish/deploy .net core web app from my machine to the windows server 2012 VPS?

**Comment by davidfowl** [comment]
https://docs.microsoft.com/en-us/aspnet/core/publishing/iis

**Comment by GuardRex** [comment]
@mister-giga I help maintain that doc. If you get stuck, ping me or one of the devs at Slack. http://tattoocoder.com/aspnet-slack-sign-up/

**Comment by wstaelens** [comment]
does this also run on Windows 10 IoT Core ?

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
