### ISSUE TITLE
Failure to publish an ASP.NET Core app to Azure

### ISSUE THREAD

**Issue by dmytro-gokun** [aspnet/Home#1883]
Hi,

I have an ASP.NET Core 1.1 app built, targeting .NET Framework 4.6.2.
I've also created a WebApp on AzurePortal and imported the publish profile.
I'm using VS 2015, Update 3.

Now, if the WebApp does not have Always On set, publish looks to work fine.
But, after setting Always On I see VS hanging during the publish (never restores, I have to kill it), In "Log Stream" on Azure portal I can see errors like this: 

Microsoft.Web.Deployment.DeploymentDetailedClientServerException: Web Deploy cannot modify the file '*******.exe' on the destination because it is locked by an external process.  In order to allow the publish operation to succeed, you may need to either restart your application to release the lock, or use the AppOffline rule handler for .Net applications on your next publish attempt.  Learn more at: http://go.microsoft.com/fwlink/?LinkId=221672#ERROR_FILE_IN_USE.

So:
1) AppOffline rule handler is here. My .pubxml file contains <EnableMSDeployAppOffline>True</EnableMSDeployAppOffline>. I also can see that file is copied to the folder.

2) Some people on the web suggest setting MSDEPLOY_RENAME_LOCKED_FILES = 1. That does not help.

3) The only way to actually publish site is to stop it manually first. This is okay for my devel environment, but that does not work for the production, because I do not have access to the portal here, I've only got the publish profile.

Any help is appreciated.
Dmytro.

**Comment by GuardRex** [comment]
Probably a dup of https://github.com/aspnet/Home/issues/694

**Comment by dmytro-gokun** [comment]
@GuardRex You are right. But that issue is 1,5 years old, looks like it was "solved" by MSDEPLOY_RENAME_LOCKED_FILES , but now it's broken again.

**Comment by GuardRex** [comment]
> But that issue is 1,5 years old

Within two weeks, two of the top MS devs are discussing it with other devs, including @colkien, one of the top commuity devs. That's probably not the best place for their discussion tho ... I agree. If they need to move it over to IISIntegration or elsewhere, then [@]Tratcher will prob open a new issue to discuss it.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
