### ISSUE TITLE
.Net core WebAPI with OAuth on IIS

### ISSUE THREAD

**Issue by PiotrKowalski93** [aspnet/Home#1884]
Hello,

I am testing OAuth2 with .Net Core WebAPI. Scenario is like that:

1. I have ListService with some simple access to SQL Database.
2. I have AuthService with GetToken methods. Controller looks like this

       
       public class AuthorizationController : Controller
       {
        private readonly Logger _errorLogger = LogManager.GetLogger("ErrorLogger");
        private static Logger _auditLogger = LogManager.GetLogger("AuditLogger");

        private readonly SignInManager<User> _signInManager;
        private readonly UserManager<User> _userManager;
        private readonly RoleManager<Role> _roleManager;

        public AuthorizationController(
           SignInManager<User> signInManager,
           UserManager<User> userManager,
           RoleManager<Role> roleManager)
        {
                _signInManager = signInManager;
                _userManager = userManager;
                _roleManager = roleManager;
                     
        }

        [HttpPost("~/connect/token")]//, Produces("application/json")]
        public async Task<IActionResult> Token(OpenIdConnectRequest request)
        {
            // Stuff
        }

        [HttpGet]
        [Route("api/[controller]")]
        public IEnumerable<string> Get()
        {
            // Test Action
            return new string[] { "Token", "XXXXX-XXXXX-XXXXX-XXXXX" };
        }

        [HttpPost]
        [Route("api/[controller]")]
        public IEnumerable<string> Post()
        {
           // Test Action
            return new string[] { "Token", "XXXXX-XXXXX-XXXXX-XXXXX" };
        }
`

And my DI Container Configuration:

       public void ConfigureServices(IServiceCollection services)
        {
            // Add framework services.
            services.AddMvc();
          
            services.AddEntityFrameworkSqlServer()
        .AddDbContext<AuthSampleContext>(options =>
            options.UseSqlServer(Configuration["Data:DefaultConnection:ConnectionString"]));

            services.AddScoped<UserManager<User>, CustomUserManager>();
            services.AddScoped<SignInManager<User>, CustomSignInManager>();

            services.AddIdentity<User, Role>(o =>
                    {
                        o.Password.RequireDigit = false;
                        o.Password.RequireLowercase = false;
                        o.Password.RequireUppercase = false;
                        o.Password.RequireNonAlphanumeric = false;
                        o.Password.RequiredLength = 6;
                    }                                
                )
                .AddEntityFrameworkStores<AuthSampleContext>()
                .AddDefaultTokenProviders();
               
            services.AddOpenIddict<AuthSampleContext>()
              .AddMvcBinders()
              .EnableTokenEndpoint("/connect/token")
              .AllowPasswordFlow()
              .AllowRefreshTokenFlow()
              .DisableHttpsRequirement()
              .UseJsonWebTokens()
              .AddEphemeralSigningKey();
        }

3. I am using POSTMAN to see if my controller is working properly. If i run my AuthService on IIS Express form Visual Studio 2015 everything is fine, I got my token. I Published it on IIS via this command:

`dotnet publish -c release -r win10-x64`

Now when I try to get token I get 500 Internal Server Error. In the same time this service contains sample Values Controler and it works perfectly. I was debugging and logging a lot and what I know for sure that it is something wrong with Dependency Injection. When I commented code like this:

         
          public AuthorizationController()
           //SignInManager<User> signInManager)
           //UserManager<User> userManager)
           //,RoleManager<Role> roleManager)
           {
                // _signInManager = signInManager;
                //_userManager = userManager;
                //_roleManager = roleManager;        
           }

My controller is working fine. Of course only my "dummy"/test actions are working (due to lack of dependencies). 

What can be de Issue ? DI Configuration should be different for other IIS version than Express? Maybe there is some kind of bug? I am lack of ideas, I spend 3 days on this. Maybe it is something very easy and I just don't see it.

**Comment by Tratcher** [comment]
What was the DI error?

/cc: @HaoK

**Comment by HaoK** [comment]
Can you try using the AddSignInManager/UserManager helpers instead to see if that works?

https://github.com/aspnet/Identity/blob/dev/src/Microsoft.AspNetCore.Identity/IdentityBuilder.cs#L220

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
