### ISSUE TITLE
Setting href=“” of an anchor Tag to weblink from my model always adds the host

### ISSUE THREAD

**Issue by ralfbalzer** [aspnet/Home#1886]
I am trying to create a link to an external webiste. For this, I am using s string, which is passed from the Database via the Model to my View. 
In the View, I am trying to set the href="" of the anchor tag, but the result always adds the local host and home controller in front of the link. 

My code looks like this:
`<a href="@item.Offer.Infolink">@Localizer["MoreInfo"]</a>`

When I view the link via Chrome Developer Tools, the HTML shows like this:

`<a href="www.grimselwelt.ch/grimselerlebnis/">Weitere Informationen »</a>`

However, the helptext on the link and clicking on the link, result is this:

`http://localhost:5000/de/Home/www.grimselwelt.ch/grimselerlebnis/`

Even when I hardcode the link into the anchor tag, I am still getting the same result.

Is this a bug or am I missing something?

**Comment by Tratcher** [comment]
@NTaylorMullen?

**Comment by NTaylorMullen** [comment]
@ralfbalzer I think JavaScript might be intervening on your behalf. The only time we modify the results of an anchor tags href is if the value starts with `~/`.

**Comment by ralfbalzer** [comment]
@NTaylorMullen  I have just tested this in a new  web application created from the standard template and the same happens.
However, I have noticed, that if I use `<a href="http://google.com">Test</a>`, it actaully works. 
The link in the database is however stored as www.google.com.

**Comment by NTaylorMullen** [comment]
@ralfbalzer could you provide me a repro project?

**Comment by lvanegmond** [comment]
The link needs to start with a protocol otherwise it's considered a relative url. Add http:// or https://.

**Comment by ralfbalzer** [comment]
@lvanegmond in this case @NTaylorMullen comment " The only time we modify the results of an anchor tags href is if the value starts with ~/" is not accurate.
I have coded around it but this works fine in other platforms.
Thanks for your help though. :-)

**Comment by lvanegmond** [comment]
You're welcome. His comment might still be accurate because the issue you are having is actually not related to ASP.NET (Core) but rather how the browser handles the url. If you don't specify a protocol the browser has no way of knowing if the url is absolute or relative, so the browser prepends the value you put in the href with the url of the page you are on.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
