### ISSUE TITLE
Multiple publishes using msdeploy.exe causes directory repetition until file name is to long and crashes VS.

### ISSUE THREAD

**Issue by ewhance** [aspnet/Home#1888]
I'm using Visual Studio Enterprise 2015, version 14.0.25431.01 Update 3 and a .net core project. The SDK does not change the result.

Steps to reproduce:
1. Create new .net core project.
2. Create custom publish target.
3. Default target location.
4. Default settings.
5. Publish.
6. Observe the added directories after the msdeploy execution: '\bin\Release\PublishOutput\'.
7. Publish again.
8. Observe that the msdeploy execution has now created another set of directories inside the first: '\bin\Release\PublishOutput\bin\Release\PublishOutput'
9. Repeat publish until file name becomes to long and crashes VS.

I also have found that even if I manually delete all of the published output as well as the publish profiles, the next publish still results in the same behavior.

**Comment by Tratcher** [comment]
This issue was moved to aspnet/Tooling#927
