### ISSUE TITLE
Extension Libraries Dependency Changes In 1.1

### ISSUE THREAD

**Issue by gensisns** [aspnet/Home#1889]
We're using Configuration and DependencyInjection in a .NetFramework 4.6.1 project. All of the versions up to 1.0.1 worked just fine and didn't cause any problems. Version 1.1.0 has caused all lot of conflicts and problems in our project - after a lot of digging, we realized that the reason was the dependencies for all the extensions changed in 1.1 from depending on specific packages to depending on the NetStandard.Library.

Why was this change made for the extensions versus referencing the specific libraries the extensions need. The previous way allowed easy use in 4.6.1. Once the NetStandard.Library is included it pulls in System.Net.Http and lots and lots of other packages, which caused a lot of problems.

I'm wondering how this could be resolved / if the extensions could go back to referencing just the packages they need.

Thanks!

**Comment by Tratcher** [comment]
It wasn't just Extensions that did this, The AspNetCore packages did this too. I'm only aware of one issue this has caused (https://github.com/aspnet/Security/issues/1046, and yes it was with System.Net.Http). What other issues have you seen?

@muratg @pranavkm what was the reasoning for this change?

**Comment by gensisns** [comment]
This was the first one we hit:
https://github.com/dotnet/corefx/issues/11100

For a project not using the full netstandard library or .netcore, it was so much easier to have a references to the couple packages that the extensions were using and not have 50+ packages installed for the full standard library.

**Comment by pranavkm** [comment]
Past discussion on this topic - https://github.com/aspnet/WebListener/issues/268.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
