### ISSUE TITLE
Why can I not get the size/length of the response stream?

### ISSUE THREAD

**Issue by NimaAra** [aspnet/Home#1891]
I have a helper method `Serialize()` which serializes a given payload as _JSON_ and writes it to a given `Stream` in this case the `HttpContext.Response.Body`

```csharp
public void Serialize<T>(T payload, Stream output)
{
    using (var writer = new StreamWriter(output, Encoding.UTF8, 512, true))
    {
        var serializer = JsonSerializer.CreateDefault();
        serializer.Serialize(writer, payload, typeof(T));
    }
}
```
I want to be able to set the _Content-Length_ on the response header to indicate the size of _JSON_ written to the stream however accessing the `HttpContext.Response.Body` throws an exception stating the underlying stream is not seekable:

```csharp
var resp = context.Response;
Serialize(payload, resp.Body);

var length = resp.Body.Length; // Throws
resp.Headers[HttpResponseHeaders.ContentLength] = length.ToString();
resp.Headers[HttpResponseHeaders.ContentType] = "application/json";
```
I am therefore currently resorting to creating an intermediary `MemoryStream` as:

```csharp
using (var memStream = new MemoryStream())
{
    Serialize(payload, memStream);

    var length = memStream.Length;
    var resp = context.Response;
    resp.Headers[HttpResponseHeaders.ContentLength] = length.ToString();
    resp.Headers[HttpResponseHeaders.ContentType] = "application/json";

    memStream.Position = 0;
    memStream.CopyToAsync(resp.Body);
}
```

While the workaround works, I do not like having this extra allocation in what can potentially be a hot-path.

**Comment by davidfowl** [comment]
That's by design. You can't assume the underlying stream is buffering for you and will be able to give you the length of what was written. By default, Kestrel is writing to the network as fast as possible. If you want to specify the content length, you need to buffer manually.

**Comment by NimaAra** [comment]
That's fair enough, Thanks.
