### ISSUE TITLE
dotnet run fails to run every second time due to hostpolicy.dll

### ISSUE THREAD

**Issue by IsaackRasmussen** [aspnet/Home#1894]
I get this error just about every second time it builds from both my ASPNETCore API and MVC projects.

> A fatal error was encountered. The library 'hostpolicy.dll' required to execute the application was not found in '...\bin\Debug\netcoreapp1.1'.

Its when I run "dotnet run" and also when doing "dotnet watch run".
It also happens for netcoreapp1.0.

I have dotnet 1.0.0-preview 5, just upgraded from preview4.

I'm using Windows 10 x64 and running dotnet from cmd.
When saving from VSCode, I will virtually always get the error the first time I save, but saving a second time even without making any changes triggers watch to run again and it will work. 

Does anyone know why this happens?

**Comment by natemcmaster** [comment]
This looks similar to https://github.com/dotnet/sdk/issues/353. Can you share more details about how to reproduce the error?

**Comment by IsaackRasmussen** [comment]
I just discovered that with a another .NET Core MVC app I have, it never happens. I will try and figure out the differences.

I'll try and get more details for how to reproduce it.

**Comment by vorotech** [comment]
It is not likely to be related to dotnet/sdk#353. I have same issue, but in my project there is no other projects references. 

Steps to reproduce.
1. In VS2017RC Create New ASP.NET Core (.NET Core) project -> Web API
2. Make sure you have .NET Core 1.1 SDK and .NET Core 1.1 runtime installed
3. Update all solution nuget packages to latest available versions
4. Open Project settings and switch Target Framework to netcoreapp1.1
5. Open cmd in prject folder and execute `dotnet run`
>A fatal error was encountered. The library 'hostpolicy.dll' required to execute the application was not found in '...\bin\Debug\netcoreapp1.1'.

The app always runs if I compile two times in a row

**Comment by IsaackRasmussen** [comment]
My project only has one level of project reference and this may be the difference with the project that doesn't exhibit this, which doesn't reference any other projects.

**Comment by natemcmaster** [comment]
> I have dotnet 1.0.0-preview 5

@IsaackRasmussen have you tried upgrading to 'rc3'? The 'preview5' versions of .NET Core CLI are nightly bits that were never released in public VS2017 builds.

Also, this isn't the right place for this error. Your bug report will get proper attention if you open an issue on https://github.com/dotnet/sdk.

**Comment by GarageWeb** [comment]
I have the exact same issue. It takes two compiles to get it to run. This also started for me when I went to 1.1 on 2017rc. I updated yesterday to the nightly builds just to see if this has been addressed and the same error continues. I have ensured that I have the proper runtimes and sdks (I went as far as to remove everything but the proper runtime and SDK) and made sure all of my csproj and settings are correct.

**Comment by natemcmaster** [comment]
@GarageWeb sounds serious. Please open an issue on https://github.com/dotnet/sdk.

**Comment by GarageWeb** [comment]
@natemcmaster  filed here: [#672](https://github.com/dotnet/sdk/issues/672) Thanks

**Comment by IsaackRasmussen** [comment]
I just installed 1.0.0-rc4-004578 and it seems to have helped.

I'll close this ticket and continue in the one @GarageWeb started if I see the problem again.

**Comment by jstallm** [comment]
The solution for me was to literally just find an old build artifact which had hostpolicy.dll, and drop that into the requested location and run dotnet test again.
