### ISSUE TITLE
Add support for decimal in attribute parameters

### ISSUE THREAD

**Issue by davidgrupp** [aspnet/Home#1896]
[It's long been know that you cannot use decimal as in attribute parameters.](http://stackoverflow.com/questions/507528/use-decimal-values-as-attribute-params-in-c) Since only primitive constants or arrays of primitives can be used as attribute parameters you can't use decimal as a parameter. However, it's more and more being recommended to use decimal over double for many common uses which seems it would indicate that adding support for decimals as attribute parameters has become more important. I'd like to see the CLR restriction of only using primitive constants or arrays of primitives changed to adding and exemption for decimals as well.

**Comment by Tratcher** [comment]
Try asking over here: https://github.com/dotnet/coreclr

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
