### ISSUE TITLE
@section scripts doesn't work into partial view

### ISSUE THREAD

**Issue by valeravorobjev** [aspnet/Home#1897]
If add a section , example - section scripts into view and render it as a partial view, section doesn't show into result html!!!

**Comment by pranavkm** [comment]
Dup of https://github.com/aspnet/Razor/issues/79. The behavior is intentional - sections defined in partials will only get rendered by a Layout for the partial and will get silently ignored otherwise.

**Comment by pranavkm** [comment]
https://github.com/aspnet/Mvc/issues/1006 has a bit more details on why we decided to leave this behavior unchanged.
