### ISSUE TITLE
Is it possible to read System.Type from an appsettings.json file in a .net core application 

### ISSUE THREAD

**Issue by AnithaLingam** [aspnet/Home#1898]
In my project i need to read the System.Type setting from appsettings.jason..but not able to read please look in to this .

Here is my code:
appsettings.jason:
"LogKafkaFactoryConfiguration": {
"type": "SPGMI.Logging.NetCore.Kafka.Configuration.LogRdKafkaClientFactory, SPGMI.Logging.NetCore"
},

I want to read type and pass to below method..below code in .Net 452
_clientfactory = System.Activator.CreateInstance(LogConfiguration.GetInstance().Client.type) as IFactory;

Samething needs to be odne .net core..

**Comment by davidfowl** [comment]
What's the problem?

**Comment by AnithaLingam** [comment]
Hi,
My appsettings.jason has a setting like below..

  "LogKafkaFactoryConfiguration": {
      "type": "SPGMI.Logging.NetCore.Kafka.Configuration.LogRdKafkaClientFactory, SPGMI.Logging.NetCore"
    },

I need to read this type setting ..and my class looks like below but I am able to read the setting to string only.. but I want the ‘Type’ because I need to use System.Activator.CreateInstance(LogKafkaFactoryConfiguration.type) in parent class.


Public class LogKafkaFactoryConfiguration
    {
        public string type { get; set; }
    }

Please help.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
