### ISSUE TITLE
Bower-folder empty in VS 2015 Preview

### ISSUE THREAD

**Issue by olofd** [aspnet/Home#190]
Just for fun I was trying to convert a medium-sized web-project to vNext. 
I copied my bower.json-file and replaced the one that came with the VS-template and after that the
bower-folder under dependencies displays an empty folder. The bower.js-file is wellformated and I have successfully installed my deps with 'bower install'. I should add that I use a .bowerrc-file for getting the files installed to the wwwroot. Not using the default grunt-config for this.

![capture2](https://cloud.githubusercontent.com/assets/933408/5019191/870f7f54-6abd-11e4-811e-1eb553d1fc83.PNG)

**Comment by wangkanai** [comment]
i had the same issue

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
