### ISSUE TITLE
No way of creating keyless URL parameters cleanly

### ISSUE THREAD

**Issue by SoonDead** [aspnet/Home#1900]
Note that this started out as a [question on stackoverflow](http://stackoverflow.com/questions/41550055/how-to-create-keyless-url-parameters-in-asp-net) which was about MVC 5.

I have learned that `Request.Query` handles URL parameters without values. This means that an url like `http://example.url/path?param1&param2&param3=value` will have it's first too parameters available in the corresponding `Query` object.

    var values = this.Request.Query["param1"];

`values` is a collection with the only element of an empty string. This is usable, although interestingly the default model binder will not bind it to action parameters so in this case `string param1` will be null:

    public IActionResult About(string param1) { ... }

On the other side creating these kind of URLs is not easy.

In an MVC application one might want to use the convenient `@Url.Action()` helpers or something similar that includes routing. The problem with these is that if the `values` parameter have a property with a value of `string.Empty` or null the property is ignored and is not used as a query parameter.

I found that the HTML5 spec [has some support for this](https://www.w3.org/TR/html5/forms.html#naming-form-controls:-the-name-attribute) (look at the `isindex` attribute). So I could technically use a form with `method="get"`.

My workaround would be dirty string manipulation on an already created URL.

Is there any support for this I'm missing?

**Comment by Tratcher** [comment]
@rynowak

**Comment by rynowak** [comment]
Routing doesn't have any easy way of doing this.

I'd also mention that the *sweet spot* of model binding is flexibility of converting a .NET model into a range of different input types and back into a .NET data model that's coherent. It's fundamentally an abstraction layer over processing the forms of raw input that HTTP/Browsers support, and so some fidelity is sacrificed.

This means that model binding is *not* great at dealing with subtle differences like "key provided or absent" or "empty collection vs null" because it would be lost in translation between .NET -> HTTP -> .NET. Making a semantic distinction in your app about details that the model binding system ignores is often the path of pain unless you're willing to make the protocol details a first class property of your model. If details like this are important to you, diving down to the HTTP layer is one solution. Writing a custom model binder *might* be a solution for some of the drawbacks.

At a more abstract level what are you trying to accomplish? Everything you're saying is true, but why is it necessary?

**Comment by SoonDead** [comment]
So on a more abstract level:

Creating URLs like this provides a really clean way of representing flags. The parameter has no more that 2 distinct possible values: it's either present or not. Representing a boolean as `&all=1` (or the even more unnecessarily verbose - not to mention language dependent `&all=true`) inherently has more than 2 possible values and is always clunky.

Note that `bool` and `bool?` usually have really different meanings in URLs. `bool?` is yes-no-dontcare which is good for filtering (for example): I want results that have a specific attribute, I want results that does not have that specific attribute, or I want all of the results and I'm not filtering by that attribute. `bool` on the other hand means something specific is enabled for that request.

My argument is that representing `bool` (but not `bool?`) as `param=true` is clunky.

Also I'm not about changing the default ASP.NET behaviour (which is horrible IMHO for non-english speakers, but I see why programmers find it straigthforward), I only want a way to create such URLs without wrestling with the framework.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.

**Comment by davidalpert** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  spinthemoose@gmail.com
    Domain spinthemoose.com has exceeded the max emails per hour (249/200 (124%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o3.sgmail.github.com ([192.254.112.98]:35970)
	by cp1164.blacksun.ca with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89_1)
	(envelope-from <bounces+848413-6f87-david=spinthemoose.com@sgmail.github.com>)
	id 1eVQjq-0000gA-1o
	for david@spinthemoose.com; Sat, 30 Dec 2017 17:40:26 -0600
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=mza3q1OfvdiLw/8cd1P1saEpy0c=; b=s3pRzfIyqTBZHcN/
	fdB4uMpe1uiRPI1YAQYUBph440T7gxGyU9IrsEOQ3lRaKrQWJzshEyhMB+67KQbW
	kakO3wlOOYAuGUHfTNqRMXGXx1SDeTDFasqV2rkYTsakYzNN/n/Srs6rRi0HUB85
	o2CkJwJpTQmRulnfyXtIu6SJytM=
Received: by filter0238p1las1.sendgrid.net with SMTP id filter0238p1las1-29488-5A4823D5-12
        2017-12-30 23:40:05.370823396 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0002p1iad1.sendgrid.net (SG) with ESMTP id 94q1bmDxQhaZz8vs8RiJNQ
	for <david@spinthemoose.com>; Sat, 30 Dec 2017 23:40:05.418 +0000 (UTC)
Date: Sat, 30 Dec 2017 23:40:05 +0000 (UTC)

**Comment by davidalpert** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  spinthemoose@gmail.com
    Domain spinthemoose.com has exceeded the max emails per hour (248/200 (124%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o6.sgmail.github.com ([192.254.113.101]:6858)
	by cp1164.blacksun.ca with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89_1)
	(envelope-from <bounces+848413-6f87-david=spinthemoose.com@sgmail.github.com>)
	id 1eVQjm-0000bK-Hx
	for david@spinthemoose.com; Sat, 30 Dec 2017 17:40:22 -0600
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=X0ixi/MXFGmHgNsj70d1rfpGgaw=; b=FzpfsFKnyDHBRjLN
	aH6kDaxL1wsXalx8mPX10BgsGOYDQyT9j4qaMLWCxdjOHA4L5zqHYJV/3HWRriNv
	7gJjzvooo7hkVE1aRcHJ5GzKEa61LOJe0g+d3BnjeR7+wTtTHemPn5Us2+Q6LlE8
	uBvtZ5qRBrg6yDugVNGOU2OrqBg=
Received: by filter0691p1mdw1.sendgrid.net with SMTP id filter0691p1mdw1-18938-5A4823D2-4
        2017-12-30 23:40:02.075322032 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0011p1iad2.sendgrid.net (SG) with ESMTP id 3-shEaUbRHO1T-yo2JSacQ
	for <david@spinthemoose.com>; Sat, 30 Dec 2017 23:40:02.237 +0000 (UTC)
Date: Sat, 30 Dec 2017 23:40:02 +0000 (UTC)
