### ISSUE TITLE
Contrib projects

### ISSUE THREAD

**Issue by desjoerd** [aspnet/Home#1902]
Hello,

How should I name contrib projects for packages like  Microsoft.Extensions.Configuration.

I would like to share this with a NuGet package. Should I name this Microsoft.Extensions.Configuration.AppSettings or is it preferred to add a Contrib suffix or  not use the Microsoft namespace at all.

What is preferred?
1. Microsoft.Extensions.Configuration.AppSettings
2. Microsoft.Extensions.Configuration.Contrib.Appsettings
3. Microsoft.Contrib.Extensions.Configuration.AppSettings
4. DeSjoerd.Configuration.AppSettings

We use Microsoft.Extensions.Configuration for some System.Web projects because it gives the possibility to use multiple configuration sources 👍 . We have a simple ConfigurationManager provider which provides the settings in the <appsettings> for the new Configuration.

Thanks in advance,
Sjoerd

**Comment by Tratcher** [comment]
Have you looked at https://github.com/aspnet-contrib?

Please don't use `Microsoft` in your package names.

**Comment by desjoerd** [comment]
So we can use AspNet in our package name?

I will contact aspnet-contrib if it's possible to add the project to the aspnet-contrib org.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.

**Comment by davidalpert** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  spinthemoose@gmail.com
    Domain spinthemoose.com has exceeded the max emails per hour (246/200 (123%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o5.sgmail.github.com ([192.254.113.10]:23371)
	by cp1164.blacksun.ca with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89_1)
	(envelope-from <bounces+848413-6f87-david=spinthemoose.com@sgmail.github.com>)
	id 1eVQjc-0000aR-49
	for david@spinthemoose.com; Sat, 30 Dec 2017 17:40:12 -0600
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=XD9G6nrvbaLJP2gvxaTqQ5P3MeY=; b=DAvyR/+rgGW5b1lH
	6KdKmGWGBbEHkRhld63QD14WVeeH+BbJ4wI/KvbexoOvsWrFk/hbM+ykldrEnnwS
	EPAVNcmUqnrd7aJ2MzQH6xH/ER67k5oZQOheKdYBpxW6unmppKLOW2TG76Gj5Bga
	kNMVobpPOzWPqnHbXNTDhRpcXjk=
Received: by filter0811p1mdw1.sendgrid.net with SMTP id filter0811p1mdw1-13075-5A4823C7-18
        2017-12-30 23:39:51.958226975 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0022p1iad2.sendgrid.net (SG) with ESMTP id 5b5LXRJPSYeArD7M9O2Nag
	for <david@spinthemoose.com>; Sat, 30 Dec 2017 23:39:51.929 +0000 (UTC)
Date: Sat, 30 Dec 2017 23:39:52 +0000 (UTC)

**Comment by davidalpert** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  spinthemoose@gmail.com
    Domain spinthemoose.com has exceeded the max emails per hour (247/200 (123%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o5.sgmail.github.com ([192.254.113.10]:58937)
	by cp1164.blacksun.ca with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89_1)
	(envelope-from <bounces+848413-6f87-david=spinthemoose.com@sgmail.github.com>)
	id 1eVQje-0000ag-H2
	for david@spinthemoose.com; Sat, 30 Dec 2017 17:40:14 -0600
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=V9mS8TBIWezYSm0mSfWcqC3+rRg=; b=bKae1Hde+plZ342c
	ayUDot6ua+6PBtgcoUtnVfVjiOvNlzIj2Sy0bEoEZtkeNfnkzU49LQpUfmJD3pI9
	YB9JmP0sDqrsNEqt0+yvuRUOIxfd6Wtpc12wT0mQhJDs3iVO3+EdVsN/lvOsOr+T
	SRXDhLpWFXIzSU3qHMs/fWKTF8A=
Received: by filter0983p1mdw1.sendgrid.net with SMTP id filter0983p1mdw1-30814-5A4823CA-1F
        2017-12-30 23:39:54.722253241 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0004p1iad1.sendgrid.net (SG) with ESMTP id kl3MBBA_T1qwNlcdr14saw
	for <david@spinthemoose.com>; Sat, 30 Dec 2017 23:39:54.665 +0000 (UTC)
Date: Sat, 30 Dec 2017 23:39:54 +0000 (UTC)
