### ISSUE TITLE
Is RIO going to be Kestrel's default networking engine? 

### ISSUE THREAD

**Issue by mnns** [aspnet/Home#1903]
Is RIO going to be integrated into Kestrel anytime soon?
Why shouldn't it be the standard, instead of libuv? I mean, it is faster in most cases... isn't it?

**Comment by Tratcher** [comment]
@halter73

**Comment by halter73** [comment]
https://github.com/aspnet/KestrelHttpServer/issues/828 Is work that should help us enable that. There are some trade-offs with RIO, so we will probably have people opt in to using RIO and allow developers to configure RIO-specific settings.

**Comment by mnns** [comment]
What are the trade-offs with RIO? As far as I've seen in some tests, it works faster and better than plain socket and simple IOCP. We all want people to start talking about ASP.NET Core and .NET core in general. Performance is a great tool to get them started. If RIO still has some pitfalls (which I'm not yet aware of), I think MSFT should concentrate on making it flawless so they could market .NET Core as a fast, reliable, lean and cross platform (also cross ISA) framework.

BTW, if you ask developers why they switched to NodeJS (and many have) they will almost automatically shout the "Asynchronous Non Blocking I/O" as if its Node's slogan. Why shouldn't Microsoft attract developers with even a faster, leaner approach?

Kestrel can use netmap for Linux and RIO for Windows.

**Comment by halter73** [comment]
I'm not an expert on RIO, so the short answer to the new title is that I don't know if RIO will be made the default. We'll be able to make a more informed decision once we build the RIO transport.

@mnns Are aware of any other production HTTP server that uses RIO and/or netmap (which seems to be a kernel module you need to manually install on Linux)? If so, that could certainly help our investigation. It's interesting you bring up NodeJS which, as I'm sure you are aware, is what libuv was built for.

@benaadams worked on [an experimental RIO server](https://github.com/aspnet/benchmarks/pull/12) a while back that I've taken a quick look at. One big issue seems to be is that every connection needs to have a unique (as in not shared with other concurrent connections) buffer constantly registered. This could lead the RIO server to consume a lot more memory than the equivalent libuv/socket based server given a lot of idle connections.

Without knowing ahead of time whether or not a given connection would be saturated or idle, it could be difficult to determine the optimal size of the registered buffer in order not to waste too much memory on idle connections while maintaining perf for active ones.

It's entirely possible we could work around the memory usage with some smart heuristics, but I'm not able to commit to making RIO the default networking engine without further investigation.

**Comment by mnns** [comment]
@halter73 Yep, NodeJS is using _libuv_ and that's exactly why I think we should make ASP.NET Core **better and faster than NodeJS**, especially if we have the tools and technology (RIO), as we do right now.

Also, like you said, I'm sure that constantly registered connection buffers memory consumption can be easily mitigated with some simple heuristics. I'm no expert on RIO, but I've ran some tests and the numbers are extremely impressive, even unusual for a Windows machine. 

Imagine the market impact if MSFT would announce a cross platform, cross ISA, modular, easy to deploy, extremely fast web server that utilizes cutting edge networking methodologies, both on Linux and on Windows. Add some PHP/ASP-like simple scriptable HTML web pages and you've got the best server in the market (only then add the bloated MVC overhead as an option, but that's another issue).

**Comment by mnns** [comment]
Any thoughts guys?

**Comment by benaadams** [comment]
The transport refactoring has already happened to a degree https://github.com/aspnet/KestrelHttpServer/tree/dev/src
```
Kestrel.Transport.Abstractions
Kestrel.Transport.Sockets
Kestrel.Transport.Libuv
```
So RIO would become just another Transport https://github.com/aspnet/KestrelHttpServer/pull/1630

However there are bigger changes for the whole stack that means it will be easier for everyone to take advantage of these changes https://github.com/aspnet/KestrelHttpServer/issues/1980

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.

**Comment by davidalpert** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  spinthemoose@gmail.com
    Domain spinthemoose.com has exceeded the max emails per hour (244/200 (122%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext6.iad.github.net ([192.30.252.197]:57380 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by cp1164.blacksun.ca with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.89_1)
	(envelope-from <noreply@github.com>)
	id 1eVQjW-0000Zk-Lm
	for david@spinthemoose.com; Sat, 30 Dec 2017 17:40:06 -0600
Date: Sat, 30 Dec 2017 15:39:46 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1514677186;
	bh=2lPaGbLZA3ngd0g5gg33XgTk8n569OEgx8amgQoMi24=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=ym4ba8HEfhfmGz/pztUqknXqrLA4QF9s+XS1eK7juZXZVTMFLBh6gptgBDo5syut9
	 tMCwRhu4+pI1eT+uwFjtv/C2dPZFp6FEy5Xixj49inGsQOwDkjVu0Y8didwJdMwlkj
	 /O9iWoN9q7FuWu1jzzWD9cG+nUy12uVtRRKHNdmk=

**Comment by davidalpert** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  spinthemoose@gmail.com
    Domain spinthemoose.com has exceeded the max emails per hour (245/200 (122%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o1.sgmail.github.com ([192.254.114.176]:7067)
	by cp1164.blacksun.ca with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89_1)
	(envelope-from <bounces+848413-6f87-david=spinthemoose.com@sgmail.github.com>)
	id 1eVQjY-0000Zl-2B
	for david@spinthemoose.com; Sat, 30 Dec 2017 17:40:08 -0600
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=CU3EJPjU7P2Px0Dyv8ZwK0I4W1Q=; b=kliA1e64dBxZ+2q+
	d7DNq+vD05QZcx0Wlm8LEJY/J5F+wos+8MZTNjnZ2YHNNkvKTKd/YGsLdglU2BjF
	ECSelfvvJ/Kgaxor91B4rC22JTmSnC6HxJV8htRngYrMuIkSv5ukNQiYiwZ3oNRo
	DPgRSchmrAY4urquZqSz6Z+aoSY=
Received: by filter0114p1las1.sendgrid.net with SMTP id filter0114p1las1-5707-5A4823C2-28
        2017-12-30 23:39:46.962212382 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0008p1iad1.sendgrid.net (SG) with ESMTP id DPKVoy3nQie5cVf_fxG91Q
	for <david@spinthemoose.com>; Sat, 30 Dec 2017 23:39:46.811 +0000 (UTC)
Date: Sat, 30 Dec 2017 23:39:46 +0000 (UTC)
