### ISSUE TITLE
What happened to Web Pages? will there be an ASP/PHP like straigtforward no MVC overhead version of ASP.NET?

### ISSUE THREAD

**Issue by mnns** [aspnet/Home#1904]
I mean, some people simply don't want to deal with the huge overhead of MVC, especially in tiny websites or highly customized web sites. IMHO this is the basics of web sites and MVC should have been developed on top of it, rather than coming first. For some, MVC is an overhead, especially in code, file tree, simplicity, straightforwardness and also sometimes in performance, especially in highly tuned .NET web apps.

I would really want to see PHP/ASP like ability to code in ASP.NET Core, writing beautiful C# code and being able to run on any OS.

**Comment by qq1211178784** [comment]
It is a bad news for the beginner from php and linux!

**Comment by mnns** [comment]
This is exactly what I'm talking about. We desperately need new comers that will experience setting up a new web app in ASP.NET Core within 5 minutes top, just like NodeJS and other modern stacks. If you top NodeJS with better performance (using RIO/netmap), ease of use, straightforwardness, cross platform and cross ISA (x86/ARM), .NET Core will explode. And I'm guessing Microsoft didn't start .NET Core so it will fail or never become as popular as it could easily be.

That means starting from the basic ASP (or whatever you call it in .NET Core, "Web Pages"/"Razor Pages"), HTML, CSS & JS. Nothing more than that, no "Controller" folders, no "View" folders and nothing related to any extension or different methodology than the most basic scriptable web site.

If you want to use MVC, simply include it in your project.

**Comment by simonmurdock** [comment]
Hasn't this been discussed as an upcoming feature and been demonstrated in one of the weekly stand-ups?

**Comment by fgreinacher** [comment]
https://github.com/aspnet/Mvc/issues/494#issuecomment-232534742 -> https://github.com/aspnet/RazorPages

**Comment by mnns** [comment]
@simonmurdock IDK, but there's no updated roadmap stating anything about where **Web Pages** (as announced in Build) had gone to. New comers will never scrape the entire history of hour long stand-ups just to seek the whereabouts of the promised Web Pages. Microsoft is not clear about it (I suspect also internally). A blurred message from Microsoft regarding a technology stack means many companies (such as my own) will rush to use other technologies instead of waiting for Web Pages.

@fgreinacher Unfortunately, **Razor Pages is a part of MVC,** which has been stated in the issue you've quoted. This means as a new comer to ASP.NET Core, I still have to climb the not-that-small mountain of Microsoft's MVC technique (which is quite disputed by many developers) just to make me a tiny, simple "Hello World" website. Razor Pages will be committed to MVC repo and will expose many MVC objects and will finally be a "lightweight MVC", which is still a lot more than a simple scriptable website.

Instead of clicking "new project", having only 1 file that serves a simple lightweight website, immediately running it with F5, new comers will have to engage a huge file tree, out of scope terminology (with a lot of proprietary stuff) and will, unless they are instructed to by their boss, uninstall it quickly and rush to Node/PHP as many already have.

**Comment by jamiebvc** [comment]
@mnns :"I mean, some people simply don't want to deal with the huge overhead of MVC, especially in tiny websites or highly customized web sites"
I totally agree with you. I'm a beginner on web development but experienced on windows forms and c#. I 've started using asp.net web pages 2 years ago , i really enjoy it and i found it very easy as a framework. If my only option was mvc i don't think i would have been developing using asp.net right now

**Comment by fgreinacher** [comment]
If you look at the "Hello World" sample from https://github.com/aspnet/Mvc/issues/494#issuecomment-232534742 that's pretty much only one relevant file (excluding bootstrapping  and project file, which can be autogenerated)

**Comment by h3smith** [comment]
As someone who was unequivocally against doing MVC, due to having done pages since .NET inception, migrating to MVC for .NET Core - id now never go back. We had huge swaths of controls in .NET we've have to migrate as well. 

I think the issues I had were just understanding how things played together. Moving to MVC takes rethinking of how you've solved things before. There needs to be a better "MVC beginners" guide for pages veterans. 

It is easier to build and deploy MVC, once you know what you are doing. I'd never go back and it's been 3 months since migrating. It's more maintainable. Easier to test. I don't see any draw backs - other than those who don't want to relearn (which I gladly admit I was one of).

**Comment by mnns** [comment]
@h3smith I'm also into ASP.NET since its first release and into MVC for 4 years, both ASP.NET MVC and client side MVC frameworks. I'm also into PHP since around 2002/3. I'm sorry to say, IMHO MVC is an extreme overhead for many types of projects. Just think about beginners who I've seen with my own eyes give up quickly on .NET MVC just because of the huge distance from a simple scriptable website like PHP/ASP.

**Comment by fgreinacher** [comment]
Sorry, but how would this not be straightforward?

     > dotnet new -t web
     > echo @page > index.cshtml
     > echo Hello @Environment.UserName! >> Index.cshtml
     > dotnet run

**Comment by ctolkien** [comment]
@mns et. al.

The ideas behind "Web Pages" (that being a "simpler" model than MVC)  is coming back as "Razor Pages". I believe this is slated for a release this year.

**Comment by cyrusel** [comment]
@mnns 
im quite agree with you, msft will lose a lot of developers because removing webpages from .nor core. although they are working on something similar (razor pages) but its too complicated rather than webpages or php. also no clear message is available about the future of asp.net and current webpages. so while msft and .net core designers are wasting the time, a lot of developers have switched php and they are happy with it's simplicity and power.

**Comment by Matthew-Bonner** [comment]
Have you heard of T4? It works in a very similar way to PHP, unless mistaken it sounds like this is what you were hoping for, although it has been around for some time:
https://msdn.microsoft.com/en-us/library/bb126478.aspx

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.

**Comment by davidalpert** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  spinthemoose@gmail.com
    Domain spinthemoose.com has exceeded the max emails per hour (243/200 (121%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o7.sgmail.github.com ([167.89.101.198]:62526)
	by cp1164.blacksun.ca with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89_1)
	(envelope-from <bounces+848413-6f87-david=spinthemoose.com@sgmail.github.com>)
	id 1eVQjG-0000Xy-7p
	for david@spinthemoose.com; Sat, 30 Dec 2017 17:39:50 -0600
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=BSy69j23Kr0AuyKU75v2mnBmN8U=; b=Zn2UwWwT1es2Gm+5
	n7h34SxPmigsqyRVPxwqhVWmqAsE81EVlVcfESl9+ujEgwkEjd34WWS3V2grDhFU
	BD57qpPJpdkaq+lrPPJCheaczfnX+Xii7uG+LPv2NV70hJiV3VRa6wj13EPlwRuJ
	f0198uo6dmoFJyynJ6lKrxc+zGA=
Received: by filter0045p1las1.sendgrid.net with SMTP id filter0045p1las1-10143-5A4823B1-22
        2017-12-30 23:39:29.784517498 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0013p1iad2.sendgrid.net (SG) with ESMTP id 00gEqas0SXOkxbOlH7FKkA
	for <david@spinthemoose.com>; Sat, 30 Dec 2017 23:39:29.797 +0000 (UTC)
Date: Sat, 30 Dec 2017 23:39:29 +0000 (UTC)

**Comment by davidalpert** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  spinthemoose@gmail.com
    Domain spinthemoose.com has exceeded the max emails per hour (242/200 (121%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext1.iad.github.net ([192.30.252.192]:52246 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by cp1164.blacksun.ca with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.89_1)
	(envelope-from <noreply@github.com>)
	id 1eVQjF-0000Xw-41
	for david@spinthemoose.com; Sat, 30 Dec 2017 17:39:49 -0600
Date: Sat, 30 Dec 2017 15:39:29 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1514677169;
	bh=UXShNiuYqsMGilsCASmoCGplmu9iY1K2tLeD1G4ZSLc=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=zg7qMXnbLw4VE9aoKvp4rGyEDW3298WCUKPWVq/Lv+xZfcsC8htzgRI7DhmhFMmRr
	 59BQ371ROp9ax47p4+ghJlipWIwxXP4BzgW41hr96ckDN+eiWRKCIy8UVxrkPULGFC
	 1IhokUc3gZAaBnXFkiaFlWMQ/DtR2sj4OqjLk3MI=
