### ISSUE TITLE
When publishing Deploy package to zip file, zip file is not replaced anymore

### ISSUE THREAD

**Issue by themetis** [aspnet/Home#1906]
In my case, the deploy package contained a folder resulting of a deploy from my project before migrating to Core.  The first time I delployed with Core, my zip file contained both the old folder and the new one resulting in a zip double the size it shoulde be. The zip file used to be replace but now it looks like its just been updated with new the new files.  
What about removing the extra files not supposed to be there?

**Comment by Tratcher** [comment]
This issue was moved to aspnet/Tooling#964
