### ISSUE TITLE
Access to configuration without dependency injection

### ISSUE THREAD

**Issue by moraleslos** [aspnet/Home#1908]
I was wondering if there was a way to access Configuration (Microsoft.Extensions.Configuration) without the use of dependency injection. Only examples I see are through constructor injection (using IOptions or injecting Configuration directly) via Startup.

My dilemma is that I have a utility class-- not a service-- that has static methods to do things on the fly. In a few of those static methods I would like to retrieve a couple of properties from appsettings.json dynamically.  These properties contain values I don't want to hard code in the utility class and can be configured differently depending on the deployment.  Since this is strictly a utility class with no interface and such, I don't want have to inject this class into every other class that needs to use a method or two from the utility.

Any ideas on how to access the properties of appsettings.json without some sort of dependency injection.

FYI: using c# and .net core 1.1

**Comment by davidfowl** [comment]
You need to pass it. There is no static "current", "ambient" configuration object.

**Comment by wjzhou** [comment]
I use static variables, which is initialized in the Startup.Configure 

It's ugly but works.
It was to replace legacy code that used the ConfigurationManager.

**Comment by la-yumba** [comment]
@davidfowl without the need to have an ambient configuration object, which is obviously a bad idea, I still can't figure out how to get statically typed configuration values without any dependency injection framework, e.g. so-called poor man's DI:

```
    public static class Program
    {
        static void Main(string[] args)
        {
            var config = new ConfigurationBuilder()
                .SetBasePath(Directory.GetCurrentDirectory())
                .AddJsonFile("appsettings.json")
                .Build();
            
            MyComponentConfig stronglyTypedConf = config["MyComponent"].NowWhat("?");
            new MyComponent(stronglyTypedConf).DoStuff();
        }

        public class MyComponentConfig { /*...*/ }
   }
```

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.

**Comment by davidalpert** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  spinthemoose@gmail.com
    Domain spinthemoose.com has exceeded the max emails per hour (238/200 (119%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o3.sgmail.github.com ([192.254.112.98]:27786)
	by cp1164.blacksun.ca with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89_1)
	(envelope-from <bounces+848413-6f87-david=spinthemoose.com@sgmail.github.com>)
	id 1eVQij-0000TO-OQ
	for david@spinthemoose.com; Sat, 30 Dec 2017 17:39:17 -0600
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=lxnvfY9ysYiLUce9C7SI48WKkbg=; b=talWpFoXHqREtMhb
	TJSrDS6ShNAEhY6ZaIigDBMeNxwQPIC5RfgTpMukAx9C/Nk7mDHM2KEl7JhymfEJ
	Z/JC4w9C+QgIee+o1XTMNRiP+3Zka6sqp1xHcGXfSiy7JCz049ELJwJ4mwiL9VUG
	TxBzGcQgxLYL87Mwe0NmNrQ6PsQ=
Received: by filter0836p1mdw1.sendgrid.net with SMTP id filter0836p1mdw1-10857-5A482391-5
        2017-12-30 23:38:57.613771533 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0005p1iad2.sendgrid.net (SG) with ESMTP id 7sVcTk_NSRWjCsJpIJCp9g
	for <david@spinthemoose.com>; Sat, 30 Dec 2017 23:38:57.609 +0000 (UTC)
Date: Sat, 30 Dec 2017 23:38:57 +0000 (UTC)

**Comment by davidalpert** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  spinthemoose@gmail.com
    Domain spinthemoose.com has exceeded the max emails per hour (239/200 (119%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o3.sgmail.github.com ([192.254.112.98]:45193)
	by cp1164.blacksun.ca with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89_1)
	(envelope-from <bounces+848413-6f87-david=spinthemoose.com@sgmail.github.com>)
	id 1eVQin-0000Tr-9k
	for david@spinthemoose.com; Sat, 30 Dec 2017 17:39:21 -0600
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=RFjdfMdijiUTHFwM/fp5497n6rc=; b=wxc1Q/ZJpSIVlz2D
	AT2SUsxXm/tk2OVKZkX448fhYnaIA7XOQOqUUPnYFKyQv+ouGNXnDz7bABqShmQ0
	SUydM+qkmFqxMweZWBcIRKVzQD+ylLYPjuJDg6dsq+M2sKAeT9FmmvVxTWid7kuA
	tCDtyiWU1g9X5DPoRTYSvLNxdl8=
Received: by filter0901p1mdw1.sendgrid.net with SMTP id filter0901p1mdw1-24545-5A482395-1
        2017-12-30 23:39:01.031258107 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0018p1iad2.sendgrid.net (SG) with ESMTP id l29vrh9qSRWn7uWPFQoCJQ
	for <david@spinthemoose.com>; Sat, 30 Dec 2017 23:39:01.067 +0000 (UTC)
Date: Sat, 30 Dec 2017 23:39:01 +0000 (UTC)
