### ISSUE TITLE
Why is netstandard1.6 required?

### ISSUE THREAD

**Issue by Qowy** [aspnet/Home#1909]
Hi,
Why does asp.net core specify netstandard1.6 as a target framework? From some analysis of it's dependencies and running the compatibility analyzer on some assemblies I cannot (in this short analysis) find APIs that would require this.
The problem is that this makes asp.net core unusable in UWP applications (and parts of it like a https enabled rest server would be quite helpful in IoT UWP projects).

EntityFramework for example specifies netstandard1.3 and therefore works in UWP.

In addition, you do provide net451 as a targetframework which only supports netstandard1.2, so is there any reason netstandard1.6 can not be reduced to 1.2 as a target framework?

**Comment by davidfowl** [comment]
Can you be more specific? Which packages?

**Comment by Qowy** [comment]
Microsoft.AspNetCore.Mvc.Core for example
I have done some further research myself, and I think there is some reflection stuff or similar in there that net451 supports but netstandard1.2 does not.
However I have a hard time actually tracking down the supported apis by netstandard version

**Comment by davidfowl** [comment]
The packages that target higher netstandard versions do so because they are using an API that requires a higher netstandard version.

**Comment by Qowy** [comment]
Yes after some more research I found for example  System.AppContext.GetData() that is only usable in netstandard1.6 (in case anyone else is googling this :) ) but not required in net452.
