### ISSUE TITLE
Progressive Web Apps

### ISSUE THREAD

**Issue by scottkuhl** [aspnet/Home#1910]
Just an idea.  I would like to see the project templates for JavaScript Services also be setup or have an option for Progressive Web Apps.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.

**Comment by davidalpert** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  spinthemoose@gmail.com
    Domain spinthemoose.com has exceeded the max emails per hour (236/200 (118%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext2.iad.github.net ([192.30.252.193]:47913 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by cp1164.blacksun.ca with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.89_1)
	(envelope-from <noreply@github.com>)
	id 1eVQif-0000Sx-34
	for david@spinthemoose.com; Sat, 30 Dec 2017 17:39:13 -0600
Date: Sat, 30 Dec 2017 15:38:53 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1514677133;
	bh=DYjVWHSIwokL4dQ0l8a+Ta/QYYlU1XbUwdx65ZIe8LU=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=0oisajcZwFDiVu/IuHWNCNULcV6DIMZW8D+BKLAsx/Nnv122r6P1mFNVYsktS5ZjM
	 UiDWiFdQr4vzcwNrrcpVJ91jPnVaO0Fc1WNPe1/q9Y44XyZi4e9dgiHfFDH4Jsugd2
	 9HWtMHgQcwK26Jua2WT7ZzepC8jKQrpITodY+KSI=

**Comment by davidalpert** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  spinthemoose@gmail.com
    Domain spinthemoose.com has exceeded the max emails per hour (237/200 (118%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o7.sgmail.github.com ([167.89.101.198]:24055)
	by cp1164.blacksun.ca with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89_1)
	(envelope-from <bounces+848413-6f87-david=spinthemoose.com@sgmail.github.com>)
	id 1eVQif-0000Sz-P8
	for david@spinthemoose.com; Sat, 30 Dec 2017 17:39:13 -0600
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=ZhiufLW8GRkjjTOkhqzlAP7/iyw=; b=AUuZSx30l7wsv0IE
	DUtusoc4myukHJy5h4d3zm/4rn85CEjmTswhQNAfcEXZ7hnw/mBx+Cdy6IL5siiV
	GVh/eShlfYK/gxtIRsNPjU3YyN8HlbILYTTn5iIV6heVUfLmvTnYzpTSVxKB3cK/
	D4fGgIrLGptsjDcgofZpI5ronDE=
Received: by filter0152p1las1.sendgrid.net with SMTP id filter0152p1las1-14813-5A48238D-A
        2017-12-30 23:38:53.298177607 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0007p1iad1.sendgrid.net (SG) with ESMTP id qI9QdTGZTcqXwL8y7oqF2Q
	for <david@spinthemoose.com>; Sat, 30 Dec 2017 23:38:53.259 +0000 (UTC)
Date: Sat, 30 Dec 2017 23:38:53 +0000 (UTC)
