### ISSUE TITLE
UserId parameter in IdentitySample.Mvc ResetPassword method

### ISSUE THREAD

**Issue by PaulRReynolds** [aspnet/Home#1911]
I have a couple of questions regarding the sample AccountController included in the Identity repository:

1. The sample action: `ForgotPassword(ForgotPasswordViewModel model)` sends an email with a callbackUrl to `ResetPassword` which includes a parameter: `userId`. This parameter is never used, so it might be worth removing from the sample code? In the similar flow for Register/ConfirmEmail it _is_ used however.

1. The `ResetPassword` action identifies the user based on the Email address entered in the password change form. For reset, if we do make use of the `userId` parameter to identify the user, and then verify this identity through the token, is there any security impact from excluding the Email field from this form? The only benefit I can see would be if an attacker obtained a reset Url but had no knowledge of the matching email address.

Thanks,

Paul

**Comment by Tratcher** [comment]
@HaoK?

**Comment by HaoK** [comment]
cc @blowdart, perhaps the best thing to do is to ensure that the user with the userId has the email specified in the model before calling ResetPassword?

**Comment by blowdart** [comment]
Oh heavens yes.

**Comment by HaoK** [comment]
I'll move this issue over to Templates then

**Comment by HaoK** [comment]
Moved: https://github.com/aspnet/Templates/issues/804

**Comment by PaulRReynolds** [comment]
@Haok Thanks for looking into the `userId` parameter, I was sure there was a use for it after all! 
If the User ID combined with the supplied token verify the identity of the user making the request, would it be possible to exclude the Email field from the reset form completely? This would improve the user experience

**Comment by HaoK** [comment]
As you see, the app is control of what information you want in the flow, we suggested using the email as a simple confirmation that its the same person who requested the change
