### ISSUE TITLE
VB support for EF Migrations

### ISSUE THREAD

**Issue by InteXX** [aspnet/Home#1913]
Is there an anticipated schedule for VB support in Code First Migrations?

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.

**Comment by davidalpert** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  spinthemoose@gmail.com
    Domain spinthemoose.com has exceeded the max emails per hour (234/200 (117%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext1.iad.github.net ([192.30.252.192]:45007 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by cp1164.blacksun.ca with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.89_1)
	(envelope-from <noreply@github.com>)
	id 1eVQiX-0000Sj-Ll
	for david@spinthemoose.com; Sat, 30 Dec 2017 17:39:05 -0600
Date: Sat, 30 Dec 2017 15:38:45 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1514677125;
	bh=Q/V6T/fzAsv8DgZ2G5LREeoHHuFRmcKKAybA3NW8lhY=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=E94TtGZ2HnVrw4tqgWyIUea1NhZqGSXYOoxTg36ePJn+zIIPrf2TZjZf6m7+DK/Ec
	 eReYNeTApwgeCUlIxB5TDkIQTjlJ/h0XFA/D0n4r43t84wkJDUC7bSNP4V2BVTUW86
	 XZ5Mi1Oyz2bo0k1dg98kk/KczSLTpEueX6anktSU=

**Comment by davidalpert** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  spinthemoose@gmail.com
    Domain spinthemoose.com has exceeded the max emails per hour (235/200 (117%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext4.iad.github.net ([192.30.252.195]:45401 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by cp1164.blacksun.ca with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.89_1)
	(envelope-from <noreply@github.com>)
	id 1eVQia-0000Sp-MW
	for david@spinthemoose.com; Sat, 30 Dec 2017 17:39:08 -0600
Date: Sat, 30 Dec 2017 15:38:48 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1514677128;
	bh=tq1fF+/exiN/NqMDWCQF6xmxNTP+1bkc1we+nWtcX9I=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=yMGRfIzU01BVphO5neGdNsqWphD2qA7RcFWWxxAZ6v1aDP9ve0v6Egjfgsv60lLko
	 bjFKZ0grHK48ZqAMgIa5r5MBmTPXF1A9L0TzNOef7PKadxbhdaykyFqG6lNziDiZYO
	 kkdqjY+nFSh5ugJkAW6xYowkZwVWxogb+tA2dgaA=
