### ISSUE TITLE
IHttpContextAccessor returns null

### ISSUE THREAD

**Issue by cihadsevim** [aspnet/Home#1914]
Hi here,
I need to inject the base domain name in the Startup.cs to load resource files for domain based website.

I tried to inject the IHttpContextAccessor and registered the service however it didn't work.

http.HttpContext.Request.Host.Value returns null all the time.

`
        
        public IConfigurationRoot Configuration { get; }
        public static string siteUrl { get; set; }

        public Config config;
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddSingleton<IHttpContextAccessor, HttpContextAccessor>();
            services.AddMvc();
        }

        public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory, IHttpContextAccessor http)
        {
            config = new Config(http.HttpContext.Request.Host.Value);
            config.cacheResource();
            app.UseStaticFiles();

            app.UseMvc(routes =>
            {
                routes.MapRoute(
                    name: "default",
                    template: "{controller=Home}/{action=Index}/{id?}");
            });
        }`

**Comment by davidfowl** [comment]
That's because there is no http context during startup of the application. The `IHttpContextAccessor`'s `HttpContext` property is only valid during a request.

**Comment by cihadsevim** [comment]
How can I reach httpContext on Startup.cs?

**Comment by davidfowl** [comment]
You can't.

**Comment by Tratcher** [comment]
You have to get this information from config, not from requests

**Comment by cihadsevim** [comment]
The project is loading configuration from database for per domain. I was able to get the base url below code.


`
 app.Use(async (context, next) =>
            {
                siteUrl = context.Request.Host.Value;
                await next();
            });
`

**Comment by cihadsevim** [comment]
Okay this is interesting. I can print the current url on Configure method but I can not set it as a variable.


` app.Use(async (context, next) =>
            {
                await context.Response.WriteAsync(context.Request.Host.Value.ToString());
                await next();
            });
`

**Comment by davidfowl** [comment]
Some comments in the code might help you understand why this would never work:

```C#
void Configure(IApplicationBuilder app)
{ 
// We declare a siteUrl local variable in the Configure method
// This method runs during startup of the application so there is no http request
string siteUrl = null;
app.Use(async (context, next) =>
            {
                // When any http request runs, it updates the globally, shared singleton
                // siteUrl local variable declared in the startup class (it is a captured variable in the closure)
                siteUrl = context.Request.Host.Value.ToString();
                await next();
            });
      // Here we are back in the startup class using a variable that is null because no http request is running
     // The application was configured to overwrite the siteUrl variable with the host header, but
     // the request hasn't run yet so the variable is still null
      config = new Config(siteUrl);
     config.cacheResource(); 
}  
```

**Comment by cihadsevim** [comment]
` 
app.Use(async (context, next) =>
            {
                siteUrl = context.Request.Host.Value.ToString();
                if (siteUrl != null)
                {
                    config = new Config(siteUrl);
                    config.cacheResource();
                }
                await next();
            });
`

**Comment by davidfowl** [comment]
You may want to put that thing in a lock so that concurrent requests don't run things?
