### ISSUE TITLE
Default Visual Studio project appsettings.json not allowing the configuration of server.urls

### ISSUE THREAD

**Issue by jmessenger235** [aspnet/Home#1915]
Default Visual Studio project appsettings.json not allowing the configuration of server.urls

The functional impact of this is that applications that are hosted independently of IIS or tested in that context, require a separate additional configuration file must be added to the default web api project created in Visual Studio

In order to encounter this issue use visual studio 2015 and .net core 1.0.1 tools preview 2 and do the following:
Create a new ASP.NET core web application. (This can either target .net framework 4.6.1 or .net core as I tested both at one point but only verified these steps against the asp.net webapi project that targets the core)
Use the webapi sub-template.
Add: ","server.urls": "http://*:5005"" without the final open and closing double quotes before the final bracket of appsettings.json.
Start the application debugging in the non IIS option for starting and debugging.
Observer that the application binds to port 5000 rather than the specified port 5005

I would expect the default json configuration to allow the setting of server.urls and bind to port 5005. 

In actuality, the server.urls parameter in the default appsettings.json is being ignored and the app is starting up listening on port 5000

The problem seems to be in WebHostBuilder.UseStartup. If I add a separate file hosting.json to the program.cs then it loads the parameter correctly and binds to the specified port. The reason I say this is that the same file specified via a configuration builder and added via WebHostBuilder.UseConfiguration properly loads the file and binds to the specified port 5005.

**Comment by Tratcher** [comment]
For starters, "server.urls" is obsolete, it's just "urls" now.

Can you show your Program.Main code? You need to read config in Program.Main add assign it to WebHostBuilder if you want it to read hosting settings. The config in Startup is not applied to WebHostBuilder.

**Comment by jmessenger235** [comment]
> The config in Startup is not applied to WebHostBuilder.
I am aware of this but I see it as a bug in one or more of documentation, template or framework. The fact you mention was not particularly clear to me from the documentation. Reading it with that understanding now, I see how it was intended that way, but is not at all the way I understood it because of the flow of examples, how they were referenced and the vague nature of how that fact was explained. Additionally, if that is how it is intended, I would think the default template should have a config that adds the environment variables and a hosting.json to the web builder. As is, I am left asking why there is an adding of environment variables to config in startup in the template if it doesn't apply to the web host builder. Even better IMO would be to apply the config in startup to the hosting settings. This is primarily for the reason that you have the environment there as part of the IHostingEnvironment. You don't have that in Program.Main without going through additional code to pull it out of an environment variable. The other reason is it would seem to reduce a lot of duplicate code in terms of needing to specify configurations in multiple places for hosting and for other settings.

The Program.Main is whatever the default web API template has. If memory serves it should be:
```csharp
var host = new WebHostBuilder()
                .UseKestrel()
                .UseContentRoot(Directory.GetCurrentDirectory())
                .UseIISIntegration()
                .UseStartup<Startup>()
                .UseApplicationInsights()
                .Build();

host.Run();
```

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.

**Comment by davidalpert** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  spinthemoose@gmail.com
    Domain spinthemoose.com has exceeded the max emails per hour (232/200 (115%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext8.iad.github.net ([192.30.252.199]:44869 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by cp1164.blacksun.ca with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.89_1)
	(envelope-from <noreply@github.com>)
	id 1eVQiW-0000Sf-3z
	for david@spinthemoose.com; Sat, 30 Dec 2017 17:39:04 -0600
Date: Sat, 30 Dec 2017 15:38:44 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1514677124;
	bh=xyCd3kLy1PcOLFVb41TUaRXOZJtijRfb9U2oXcL10KY=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=fqON4/5zB6OXSA9pX3wDO+JpMaJIzS8k9Kks94wFwjOY8F41elp88+3iWqdf9oI6O
	 +WXvUXF3HA1LvKS4xqvkz+TazQFIID3khqv4V/TidjfX03+JXkUKwLcxOgptE1+52F
	 g+e1y6N9qZ/f69AN0IIbhCbFvPuoy0VBzbAj6Iuo=

**Comment by davidalpert** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  spinthemoose@gmail.com
    Domain spinthemoose.com has exceeded the max emails per hour (233/200 (116%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o6.sgmail.github.com ([192.254.113.101]:32286)
	by cp1164.blacksun.ca with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89_1)
	(envelope-from <bounces+848413-6f87-david=spinthemoose.com@sgmail.github.com>)
	id 1eVQiX-0000Si-1U
	for david@spinthemoose.com; Sat, 30 Dec 2017 17:39:05 -0600
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=xvG/43rvVkaJqXz4IR/uEiP1oxw=; b=iAlAeBR6z7fNd/G+
	ryDmlIhbzEK9Sujq6TI52D1HQ8pE7l2zFtd4/3EuEoULIbB/jVU5riwqOisdli9q
	iKezqE2bx0lZYKXlCbX6FyuNmQDbrtLXtVt2fRKQSYixcXc+RiSLt13jWGknOLPj
	tLzL9Xe1IOY3oAnXGTe1+UYd2ug=
Received: by filter0810p1mdw1.sendgrid.net with SMTP id filter0810p1mdw1-5138-5A482384-B
        2017-12-30 23:38:44.70789055 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0024p1iad2.sendgrid.net (SG) with ESMTP id 8ZsdbuuxRxS3plTNuqwFyw
	for <david@spinthemoose.com>; Sat, 30 Dec 2017 23:38:44.696 +0000 (UTC)
Date: Sat, 30 Dec 2017 23:38:44 +0000 (UTC)

**Comment by szogun1987** [comment]
This issue still occurs. Application ignores both 'urls' and 'server.urls' parameters no matter if I pass them via command line or place in .json file. environment variable ASPNETCORE_URLS works fine. 
I used ``publish --configuration Release --self-contained --runtime win-x64`` to build mine solution. I have debug mine app a little bit and figured out that host._config file doesn't contains reference to most of configuration
![image](https://user-images.githubusercontent.com/7465665/34640783-b68b595c-f2f9-11e7-84c6-14e7be0c2686.png)
But configuration is available later in app.

**Comment by szogun1987** [comment]
OK I figured out what was wrong. ConfigureAppConfiguration doesn't affect config used during app startup. It is used later.
