### ISSUE TITLE
Using 1.1.0 on net461 dependencies downgrade

### ISSUE THREAD

**Issue by gjsduarte** [aspnet/Home#1918]
After upgrading some of the packages to the latest 1.1.0  started having the issue that the System.Diagnostics.Tracing 4.3.0 library is not available for the net461 framework.

> warn : Detected package downgrade: System.Diagnostics.Tracing from 4.3.0 to 4.0.20 
> warn :  MyApp.Web (>= 2.6.20) -> MyApp.Data (>= 1.0.0) -> Microsoft.Extensions.Configuration.Abstractions (>= 1.1.0) -> NETStandard.Library (>= 1.6.1) -> System.Diagnostics.Tracing (>= 4.3.0) 
> warn :  MyApp.Web (>= 2.6.20) -> System.Diagnostics.Tracing (>= 4.0.20)

Could this package downgrade be something I should be worried about?

**Comment by davidfowl** [comment]
> Could this package downgrade be something I should be worried about?

You should always worry about downgrades unless that was your intention.

Why are you directly referencing `System.Diagnostics.Tracing (>= 4.0.20)` in your Web application?

**Comment by gjsduarte** [comment]
It was by mistake, forgot to take it out after some tests. 
But the downgrade warning message shows up anyway due to indirect dependencies on this package.

I just unzipped the system.diagnostics.tracing.4.3.0.nupkg and verified it is not targeting net461, only net462.

Not sure is this is intended, but for the moment I solved the problem by bumping my projects to net462.

**Comment by davidfowl** [comment]
> But the downgrade warning message shows up anyway due to indirect dependencies on this package.

It shows up because you are directly referencing `System.Diagnostics.Tracing 4.0.20` in your project file. Remove it and the downgrade warning will go away.

**Comment by gjsduarte** [comment]
No, the is no direct dependency on `System.Diagnostics.Tracing` on any of my projects now. It is nevertheless indirectly referenced by other libraries such as `Microsoft.Extensions.Configuration.Abstractions`.  
The issue seems to be definitely related with the fact that `System.Diagnostics.Tracing` is not available for net461.
By inspecting the the `System.Diagnostics.Tracing` NuGet package it is also visible that only the net462 folder is not empty.

**Comment by davidfowl** [comment]
Can you show me the warning again?

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.

**Comment by davidalpert** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  spinthemoose@gmail.com
    Domain spinthemoose.com has exceeded the max emails per hour (228/200 (113%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o4.sgmail.github.com ([192.254.112.99]:14649)
	by cp1164.blacksun.ca with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89_1)
	(envelope-from <bounces+848413-6f87-david=spinthemoose.com@sgmail.github.com>)
	id 1eVQgf-0000LD-Bv
	for david@spinthemoose.com; Sat, 30 Dec 2017 17:37:09 -0600
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=dgRqun/6jMqRExAKEG6hK9AK0D4=; b=NE2cGtun9kNSctZH
	kzJYAm5aVJe1FZgsQ9IOT5Bz1jv4m1eRJqTPUwF6yfawk7se9xd0xFANcIocEiFM
	ICMWeHgij+8SM17rK+mg1WPmPL8bdQam9Uk36v764ey2mZtOlFtYtlvJBzwQVMcW
	G+mTpZ4g8TvC3zmSWeFEcLyIrT8=
Received: by filter1111p1mdw1.sendgrid.net with SMTP id filter1111p1mdw1-7289-5A482311-23
        2017-12-30 23:36:49.643158987 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0010p1iad2.sendgrid.net (SG) with ESMTP id l71gH7UqRkS5NGaoc53pZw
	for <david@spinthemoose.com>; Sat, 30 Dec 2017 23:36:49.708 +0000 (UTC)
Date: Sat, 30 Dec 2017 23:36:49 +0000 (UTC)

**Comment by davidalpert** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  spinthemoose@gmail.com
    Domain spinthemoose.com has exceeded the max emails per hour (229/200 (114%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext5.iad.github.net ([192.30.252.196]:58892 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by cp1164.blacksun.ca with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.89_1)
	(envelope-from <noreply@github.com>)
	id 1eVQgh-0000M3-T2
	for david@spinthemoose.com; Sat, 30 Dec 2017 17:37:12 -0600
Date: Sat, 30 Dec 2017 15:36:52 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1514677012;
	bh=eQNN14qJKiKXXIX+hW8PKAznzcloGUSpoTnFqC0HWI4=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=FwsyZdfvUh1h0SE/lHPxM3WVs2RP08/Q7GN1WagTk1z2/deeFn9kZvNKRx91jlz67
	 mGssYt4u5IilQcZKzsqDDCHRVAvK5W10yMY06GhC2ANx9XDAyK6WQoiO/lLMQjOpLs
	 FjzG3ONKcthpbkEKnCKzqQXWnyacub8buGO0Mf7A=
