### ISSUE TITLE
Vote to restore Html.Action and Html.RenderAction

### ISSUE THREAD

**Issue by RickRockhold** [aspnet/Home#1919]
ViewComponents are great, but there are use cases to for Html.Action and Html.RenderAction that aren't fulfilled by ViewComponents.

We have a SPA website that has a hierarchy of partial pages. Each partial's container is decorated with the URL used to load the partial. During a partial page (ajax) request, this URL is used directly. During a full page load, these URLs are passed to Html.Action() to build the page hierarchy.

In ASP.NET Core, the situation is more complicated, and involves a bunch of extra code. We can still decorate the partials' containers with URLs, which wrap the ViewComponent used to render the partial. During a full page load, we have to use similar--but separate--logic to include the appropriate ViewComponent, and similar--but separate--logic to pass the correct parameters, etc.

ViewComponents are awesome, and I love the ability to call complex views without the overhead of re-entering the pipeline. However, there are still useful, legitimate cases for RenderAction().

Please, please give us the choice--speed and efficiency of ViewComponents when needed, cleanliness and Don't-Repeat-Yourself of RenderAction when we need that.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.

**Comment by davidalpert** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  spinthemoose@gmail.com
    Domain spinthemoose.com has exceeded the max emails per hour (226/200 (112%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o4.sgmail.github.com ([192.254.112.99]:1454)
	by cp1164.blacksun.ca with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89_1)
	(envelope-from <bounces+848413-6f87-david=spinthemoose.com@sgmail.github.com>)
	id 1eVQgb-0000Kh-6H
	for david@spinthemoose.com; Sat, 30 Dec 2017 17:37:05 -0600
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=c+FKXNS8zjdN3LHH8HAN9YG2tKk=; b=veUsTOWVKscBMbpV
	ypIHxtFTpSVQNu/ZK9JrHZ5jRNn/V521mxNthYX+8S+/Tp7t15u939t+rJua/FmB
	unSkQR9WKXIIQgvL8lvV12dlI80tY0BebKITyoiMwEMkOfjPnRZKv4Etdmm6Sa/0
	jTWK+BR65ifwMJTusoiu0ja74+k=
Received: by filter0628p1mdw1.sendgrid.net with SMTP id filter0628p1mdw1-4808-5A48230C-21
        2017-12-30 23:36:44.673087824 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0010p1iad1.sendgrid.net (SG) with ESMTP id ZbANGkmXQ92ab9YoX_5VLw
	for <david@spinthemoose.com>; Sat, 30 Dec 2017 23:36:44.658 +0000 (UTC)
Date: Sat, 30 Dec 2017 23:36:44 +0000 (UTC)

**Comment by davidalpert** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  spinthemoose@gmail.com
    Domain spinthemoose.com has exceeded the max emails per hour (227/200 (113%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o3.sgmail.github.com ([192.254.112.98]:25138)
	by cp1164.blacksun.ca with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89_1)
	(envelope-from <bounces+848413-6f87-david=spinthemoose.com@sgmail.github.com>)
	id 1eVQgb-0000Kk-Ee
	for david@spinthemoose.com; Sat, 30 Dec 2017 17:37:05 -0600
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=I4IxiAIVlgB1VXvyWDQa0K71ApA=; b=oj9Du5MMlYqyS5IA
	yB10dxwdOlmIauI2EfH5sw19aNbvIm5zVU34DDRwrUeBzHf6KBE5cN2JTgwNn0lf
	dhilFkc3pWr78ctDwB1xG16Y/DFDnwjOql8GRiiO9CujlDOZdb7ax9B3JH5+GLwG
	pmSsm4k4cSJeuyCr7e9ZK4AKCho=
Received: by filter0355p1las1.sendgrid.net with SMTP id filter0355p1las1-27517-5A48230D-4
        2017-12-30 23:36:45.094736228 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0015p1iad2.sendgrid.net (SG) with ESMTP id xGk_SZFMR7ezdW88rugIFA
	for <david@spinthemoose.com>; Sat, 30 Dec 2017 23:36:45.189 +0000 (UTC)
Date: Sat, 30 Dec 2017 23:36:45 +0000 (UTC)
