### ISSUE TITLE
The state of graphics in vNext

### ISSUE THREAD

**Issue by JimBobSquarePants** [aspnet/Home#192]
I'd like to start a discussion to determine what graphics manipulation namespaces will be available in vNext.

I currently run an open source project [ImageProcessor](https://github.com/JimBobSquarePants/ImageProcessor) which has become quite popular and is now used in the core Umbraco project. This uses `System.Drawing` for manipulation which as far as I am aware is not available to the [Cloud Optimized Framework](http://blogs.msdn.com/b/cesardelatorre/archive/2014/05/12/the-future-of-net-in-the-server-asp-net-vnext-optimized-for-cloud-and-server-workloads.aspx) and it is uncertain as to whether that will be supported in the main framework.

This obviously has me more than a little worried as I simply don't have the time or resources to switch to something else and I may have to give up the project. I'm already putting a feature freeze on the project until I know what is happening.

I have noticed however though that [System.Drawing (Mono)](http://www.dotnetfoundation.org/system.drawing) exists on the .Net Foundation page so I'm hoping that this indicates `System.Drawing` will stay.

Could anyone shed any light on this?

P.S I am fully aware of the warning against support on the [System.Drawing.Namespace](http://msdn.microsoft.com/en-us/library/system.drawing.aspx) documentation. I'm also aware of the explanation as to the proper meaning of the warning given by [Cheryl Simmons](http://blogs.msdn.com/b/winformsue/archive/2007/05/14/what-does-not-supported-mean.aspx) the woman who wrote it.

**Comment by JimBobSquarePants** [comment]
vNext is in beta now... What's the battle plan?

**Comment by atrauzzi** [comment]
I'm curious about the status of this situation as well.  Are there going to be any options for generating graphics server-side?

**Comment by nathanaeljones** [comment]
See https://github.com/dotnet/corefx/issues/2020

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
