### ISSUE TITLE
ASP.NET MVC Core Authentication against On-Perm ADFS

### ISSUE THREAD

**Issue by bharatmangal04** [aspnet/Home#1920]
Hi Team, 

Can you please suggest how we can configure the ASP.NET MVC Core application to use On-Perm Authentication using WSFed.

Regards,
Bharat

**Comment by Tratcher** [comment]
It's not available. See https://github.com/aspnet/Security/issues/43

**Comment by bharatmangal04** [comment]
Is there a way we can use On-Perm AD Authentication in ASP.NET MVC Core app

**Comment by Tratcher** [comment]
No. This is blocking many users migration to ASP.NET Core.

**Comment by Tratcher** [comment]
Well, you can use OpenIdConnect if your server is Windows 2016.

**Comment by bharatmangal04** [comment]
We are not using Windows server 2016. 👎. We also blocked because of this.

**Comment by libsamek** [comment]
Is there any progress on this?

**Comment by Tratcher** [comment]
This won't be available until at least 2.1.0

**Comment by libsamek** [comment]
Hi, is there middleware availabe for ADFS using OAuth 2.0?

**Comment by sagreer** [comment]
@libsamek I believe you can setup IdentityServer 4 middleware to solve the ADFS issue.  https://docs.microsoft.com/en-us/aspnet/core/security/authentication/community

**Comment by ashgadala** [comment]
Any update?

**Comment by ashgadala** [comment]
@Tratcher When do you think for time stand point?

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.

**Comment by davidalpert** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  spinthemoose@gmail.com
    Domain spinthemoose.com has exceeded the max emails per hour (225/200 (112%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext3.iad.github.net ([192.30.252.194]:57009 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by cp1164.blacksun.ca with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.89_1)
	(envelope-from <noreply@github.com>)
	id 1eVQgW-0000Ka-UD
	for david@spinthemoose.com; Sat, 30 Dec 2017 17:37:01 -0600
Date: Sat, 30 Dec 2017 15:36:41 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1514677001;
	bh=ghQYimdLqfi+c7vjBnot5OBrz4AymDviz+gh1gxXzVc=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=Vsz829+pqELqCQ1hG5u7qLZibXWPrqOP47StiLnhxQmaveMm4t4xvsFgrp0EuW814
	 TKksTYk5BKMjMkth/s0YIA7xLypFz7yUd2jW1hzxk0p/FpKOvqvG8kUzZXvniKB/5+
	 1gy3una1cfIvo+yah/4lDY1+c0XxkpPcYsCyGzSw=

**Comment by davidalpert** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  spinthemoose@gmail.com
    Domain spinthemoose.com has exceeded the max emails per hour (224/200 (112%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext6.iad.github.net ([192.30.252.197]:56888 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by cp1164.blacksun.ca with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.89_1)
	(envelope-from <noreply@github.com>)
	id 1eVQgW-0000KZ-LW
	for david@spinthemoose.com; Sat, 30 Dec 2017 17:37:00 -0600
Date: Sat, 30 Dec 2017 15:36:41 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1514677001;
	bh=BwqBRk0QVpjTpsUYnRIocxAvYvnSgysTm6CCwiqhqX4=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=ZddsqE1aiSNSe3PGsrOYOiwbB5W3K7BdJaVMdte14fHxI+BXtewPpI2RAeZBYviHt
	 ooBgb8LWP+pcwF+NSg78bvbDFyWzEBMQ3FCdiq848zvPyV23NqAW5cH2zTOY0OU5Cq
	 XdB2mlknRrTiHHKiY60RUMyY5pv5SF14wVrEZVE0=

**Comment by mukeshmuvva** [comment]
how can i  configure the ASP.NET MVC Core application to use On-Perm Authentication using WSFed.

**Comment by Tratcher** [comment]
Comments on closed issues are not tracked, please open a new issue with the details for your scenario.
