### ISSUE TITLE
Binding Redirects for newtonsoft

### ISSUE THREAD

**Issue by kapopken** [aspnet/Home#1922]
I am having an issue running my .net core project due to binding redirects.  If I look at my config file in the bin directory here is what is generated
`        <bindingRedirect oldVersion="0.0.0.0-9.0.0.0" newVersion="9.0.1" />
        <bindingRedirect oldVersion="9.0.0.0" newVersion="8.0.0.0" />
        <bindingRedirect oldVersion="6.0.0.0" newVersion="8.0.0.0" />`
I only show version 9.0.1 installed.

Here are the steps I have tried to resolved.
Deleted all my bin folders
Deleted all my obj folders
Deleted my .vs folder
Deleted all project.json files
Reinstalled newtonsoft.

Please help :)

**Comment by Tratcher** [comment]
A) What's the error you get?
B) Share a project with the issue.

**Comment by kapopken** [comment]
Here is the error I am receiving
An exception of type 'System.IO.FileLoadException' occurred in Microsoft.Extensions.Configuration.FileExtensions.dll and wasn't handled before a managed/native boundary

Additional information: Could not load file or assembly 'Newtonsoft.Json, Version=8.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

**Comment by kapopken** [comment]
For  more information the project is a .net core with the full 461 framework.  It references other projects which are all also .net core libraries with the full 461 framework

**Comment by kapopken** [comment]
![image](https://cloud.githubusercontent.com/assets/739819/22570467/09595fba-e961-11e6-937f-8aa945b7000e.png)

**Comment by kapopken** [comment]
So i figured out removing this library   "gmaps-api-net": "0.13.30",  fixed the issue.  Unfortunately, the amount of work troubleshooting this when a simple binding redirect should have worked highlights some serious issues with the tooling.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.

**Comment by davidalpert** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  spinthemoose@gmail.com
    Domain spinthemoose.com has exceeded the max emails per hour (222/200 (111%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext3.iad.github.net ([192.30.252.194]:52444 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by cp1164.blacksun.ca with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.89_1)
	(envelope-from <noreply@github.com>)
	id 1eVQgJ-0000J7-UU
	for david@spinthemoose.com; Sat, 30 Dec 2017 17:36:48 -0600
Date: Sat, 30 Dec 2017 15:36:28 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1514676988;
	bh=Z+X/ZpawuQVTA7uKEy3gYgHZ8RoUjH8RqHaKnkg2hOU=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=e0ivpiNGzsM1pP8W/GMpkpAxTryzRObna+ZqkbiuWVY0cFivOtizZYEySkBnhHX3f
	 I68pzak4jwQx8gUsqg5OL2kZ6KgykHzFx8p7sTovpuN3SvkVUcr3OZnw6yLcv45wrd
	 571Q/WGjyIFd7n3jKIMEyUc96U741TjA5oUOZ+Jw=

**Comment by davidalpert** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  spinthemoose@gmail.com
    Domain spinthemoose.com has exceeded the max emails per hour (223/200 (111%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o7.sgmail.github.com ([167.89.101.198]:3147)
	by cp1164.blacksun.ca with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89_1)
	(envelope-from <bounces+848413-6f87-david=spinthemoose.com@sgmail.github.com>)
	id 1eVQgM-0000JD-Jq
	for david@spinthemoose.com; Sat, 30 Dec 2017 17:36:50 -0600
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=JU0ZHIiCYvZdW7Xoc1OSnkd1a0c=; b=iZM5njG2D+T4IjsT
	VVE/ZMyr5aC1kR935OMYX27DaU5AuLPyshuAXgItwnlK+WnoSZKmDaKJcPK0Wufp
	N9huOks2ysNlhzThs0vPNtyLnhAJlL6c12wDNSa+mnWq4PPQKloQhYBby9d+Q61j
	HVBsxxYdViSEem9gCMtUdx3YrLg=
Received: by filter0154p1las1.sendgrid.net with SMTP id filter0154p1las1-18322-5A4822FC-25
        2017-12-30 23:36:28.564217853 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0002p1iad1.sendgrid.net (SG) with ESMTP id _rFhKTP-SpGxGM6HMvhDxw
	for <david@spinthemoose.com>; Sat, 30 Dec 2017 23:36:28.450 +0000 (UTC)
Date: Sat, 30 Dec 2017 23:36:28 +0000 (UTC)
