### ISSUE TITLE
Error when following one of the tutorials

### ISSUE THREAD

**Issue by jgoshi** [aspnet/Home#1923]
When I tried to follow this tutorial:
https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-model

At the part where I try to add the controller I get the following error (see screenshot).
![image](https://cloud.githubusercontent.com/assets/19478941/22573623/ec6711da-e94d-11e6-894c-1043cc370c04.png)

Note that I can build the project successfully. But cannot add the controller. Not sure if this is a user error, but if not it's a bad bug.

Microsoft Visual Studio Enterprise 2017 RC
Visual Studio/15.0.0-RC4+26129.0.d15rel

@danroth27 @mlorbetske

**Comment by Rick-Anderson** [comment]
@jgoshi  I've seen this error before. Can you try the following:

- Exit/restart VS17 and try to scaffold again.
- If above fails, create a new project with simple model and scaffold.

**Comment by prafullbhosale** [comment]
@jgoshi can you provide the contents of your csproj file? 
And also the log from the output window if possible?

**Comment by jgoshi** [comment]
Exit/restart VS17 and try again failed. Here are the contents from the output window.
D:\dotnetcli\artifacts\win10-x64\stage2\dotnet.exe aspnet-codegenerator --project "C:\Users\jgoshi\documents\visual studio 2017\Projects\MvcMovie\MvcMovie\MvcMovie.csproj" --no-build controller --force --controllerName MoviesController --model MvcMovie.Models.Movie --dataContext MvcMovie.Data.ApplicationDbContext --relativeFolderPath Controllers --referenceScriptLibraries --useDefaultLayout
Command Line: --project C:\Users\jgoshi\documents\visual studio 2017\Projects\MvcMovie\MvcMovie\MvcMovie.csproj --no-build controller --force --controllerName MoviesController --model MvcMovie.Models.Movie --dataContext MvcMovie.Data.ApplicationDbContext --relativeFolderPath Controllers --referenceScriptLibraries --useDefaultLayout
Microsoft (R) Build Engine version 15.1.539.38876
Copyright (C) Microsoft Corporation. All rights reserved.
Command Line: --no-dispatch --port-number 30855 --project C:\Users\jgoshi\documents\visual studio 2017\Projects\MvcMovie\MvcMovie\MvcMovie.csproj --no-build controller --force --controllerName MoviesController --model MvcMovie.Models.Movie --dataContext MvcMovie.Data.ApplicationDbContext --relativeFolderPath Controllers --referenceScriptLibraries --useDefaultLayout --dispatcher-version 1.0.0-msbuild3-final
Finding the generator 'controller'...
Running the generator 'controller'...
Attempting to compile the application in memory with the modified DbContext
Attempting to figure out the EntityFramework metadata for the model and DbContext: Movie
No parameterless constructor was found on 'ApplicationDbContext'. Either add a parameterless constructor to 'ApplicationDbContext' or add an implementation of 'IDbContextFactory<ApplicationDbContext>' in the same assembly as 'ApplicationDbContext'. StackTrace:
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.<>c__DisplayClass12_3.<FindContextTypes>b__13()
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(Func`1 factory)
No parameterless constructor defined for this object.   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)

   at Microsoft.VisualStudio.Web.CodeGeneration.EntityFrameworkCore.EntityFrameworkServices.TryCreateContextUsingAppCode(Type dbContextType, Type startupType)
No parameterless constructor defined for this object. StackTrace:
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at Microsoft.VisualStudio.Web.CodeGeneration.ActionInvoker.<BuildCommandLine>b__6_0()   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)

   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)   at System.Activator.CreateInstance(Type type, Boolean nonPublic)

   at Microsoft.VisualStudio.Web.CodeGeneration.CodeGenCommand.Execute(String[] args)   at System.Activator.CreateInstance(Type type)

   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.<>c__DisplayClass12_3.<FindContextTypes>b__13()
RunTime 00:00:06.29

**Comment by jgoshi** [comment]
And here is the csproj file:

[MvcMovie.zip](https://github.com/aspnet/Home/files/749309/MvcMovie.zip)

**Comment by prafullbhosale** [comment]
Worked with @jgoshi offline. The issue seemed to be a bad package in the local nuget cache. 
Clearing out the local nuget cache and retrying the scenario worked fine.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.

**Comment by davidalpert** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  spinthemoose@gmail.com
    Domain spinthemoose.com has exceeded the max emails per hour (220/200 (110%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext6.iad.github.net ([192.30.252.197]:48080 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by cp1164.blacksun.ca with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.89_1)
	(envelope-from <noreply@github.com>)
	id 1eVQg6-0000HM-TV
	for david@spinthemoose.com; Sat, 30 Dec 2017 17:36:35 -0600
Date: Sat, 30 Dec 2017 15:36:15 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1514676975;
	bh=PwPpJGvwAzW3MUvj20GBOY0E+jrE5bvzxI5xRB52+0Y=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=1MKpceCtARNWw7/dJJp7AHY8HKTuezFNsY31JpX1kFv4XPesVsZ4Gm7cQMR7NjVGw
	 K746Bag8uK526g4A5CgljCGJu1qq1dWLqnurFQR3n+hUamEeuesYtzKcqihtmmKV2a
	 Gr4IauExJ3288p34YFjXb9vCTIwCk50rH3ejAgSE=

**Comment by davidalpert** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  spinthemoose@gmail.com
    Domain spinthemoose.com has exceeded the max emails per hour (221/200 (110%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext7.iad.github.net ([192.30.252.198]:51758 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by cp1164.blacksun.ca with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.89_1)
	(envelope-from <noreply@github.com>)
	id 1eVQgA-0000Ha-Hf
	for david@spinthemoose.com; Sat, 30 Dec 2017 17:36:38 -0600
Date: Sat, 30 Dec 2017 15:36:18 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1514676978;
	bh=ghPtx3DWzaVt76pzpu1CuP5qcNn52gACd3ENKso9KS4=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=vatYwDOAp3ebUQwfOExf+C6AS4blUzgKIlaUvvJZVtwpcDRf102GUKyL4g/mbMHqX
	 J+ymsIyREuGPJiim2B9Ua3zzbTtqH2iF9X4RRO5QjTvX7xUMtnxlOGe/cvrd/H0j9O
	 3I/WrfOjWxK2/8b7ocvoQp6RvXCaXh03Kh51RW6w=
