### ISSUE TITLE
Example of the code that could cause a deadlock

### ISSUE THREAD

**Issue by ivanbuha** [aspnet/Home#1924]
Hi everyone,

There are examples of C# code at home page of  [https://www.microsoft.com/net](https://www.microsoft.com/net). One of them is the example of ASYNC code which could cause a deadlock (find attached image). Basically, Wait() shoundt be called on GetURL() method as its blocks the calling thread and the thread will never pick up the result of GetStringAsync(). Some conditions must apply, but overall, I feel like its a bad style of coding. 

You can find more information here:
[http://stackoverflow.com/questions/24623120/await-on-a-completed-task-same-as-task-result](http://stackoverflow.com/questions/24623120/await-on-a-completed-task-same-as-task-result)
[http://blog.stephencleary.com/2012/07/dont-block-on-async-code.html](http://blog.stephencleary.com/2012/07/dont-block-on-async-code.html)
![image](https://cloud.githubusercontent.com/assets/25520025/22577822/eca74174-e989-11e6-8823-4b547a020777.png)

**Comment by Tratcher** [comment]
@danroth27?

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.

**Comment by davidalpert** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  spinthemoose@gmail.com
    Domain spinthemoose.com has exceeded the max emails per hour (218/200 (109%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o10.sgmail.github.com ([167.89.101.201]:40935)
	by cp1164.blacksun.ca with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89_1)
	(envelope-from <bounces+848413-6f87-david=spinthemoose.com@sgmail.github.com>)
	id 1eVQg3-0000Gj-C2
	for david@spinthemoose.com; Sat, 30 Dec 2017 17:36:31 -0600
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=b6i0KCOEabQh08mPegPbNO3q2u4=; b=BBLoxHGIquHkgJXH
	qs4SIibb8IuZOUl+GWFnAgYT5JDaMYYzLVwkjvvcVstBl1Yqo61bRXiWILoOG6Vt
	FhrF/NdXDoxRqCgLi/nH/1e8F+OhDybL8g6AXY0Xwpa2LGHKG3IUvKExvQVQydNQ
	GXnGAtKCoQX1WaxM7Ne0hMTN3AY=
Received: by filter1189p1mdw1.sendgrid.net with SMTP id filter1189p1mdw1-11289-5A4822EA-34
        2017-12-30 23:36:10.931137394 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0010p1iad1.sendgrid.net (SG) with ESMTP id vWypPjkfQ_yKheqncqeBeQ
	for <david@spinthemoose.com>; Sat, 30 Dec 2017 23:36:10.979 +0000 (UTC)
Date: Sat, 30 Dec 2017 23:36:10 +0000 (UTC)

**Comment by davidalpert** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  spinthemoose@gmail.com
    Domain spinthemoose.com has exceeded the max emails per hour (219/200 (109%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o8.sgmail.github.com ([167.89.101.199]:58582)
	by cp1164.blacksun.ca with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89_1)
	(envelope-from <bounces+848413-6f87-david=spinthemoose.com@sgmail.github.com>)
	id 1eVQg4-0000H1-20
	for david@spinthemoose.com; Sat, 30 Dec 2017 17:36:32 -0600
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=r0DRyn0xHujGa/nhA23VQg4CljM=; b=hfI4H578X/+idJvw
	oRHfmt/3Odb/rfPcm6BCxeaSZVvR0+EV0oIllGbr1C1qCTh9ibtMuKgL4pzS7zM7
	c/62tesiYIY1FxdsxL1ZZsonfzO1pYmHj76IlIHlJQc5jSIrC5p4XajNMjfOtTsT
	zq83OEQ4gZLJTjhHmaC/6hTSHkw=
Received: by filter0811p1mdw1.sendgrid.net with SMTP id filter0811p1mdw1-13075-5A4822EB-2D
        2017-12-30 23:36:11.873574848 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0018p1iad2.sendgrid.net (SG) with ESMTP id XSljR1y0T1uEXgCIbdJPZQ
	for <david@spinthemoose.com>; Sat, 30 Dec 2017 23:36:11.887 +0000 (UTC)
Date: Sat, 30 Dec 2017 23:36:11 +0000 (UTC)
