### ISSUE TITLE
Asp.net core putting the same Guid for all empty Guid's

### ISSUE THREAD

**Issue by jonatanrinckus** [aspnet/Home#1926]
Hello, guys.

I'm going through a problem when using Guid as Id, when I have Entity like:

`
public class SubcategoryDto
    {
        public Guid Id { get; set; }

        public string Description { get; set; }

        public Guid CategoryId { get; set; }
    }`

and I have a Action in my controller with:

`public IActionResult Create(Guid id)
        {
            var dto = new SubcategoryDto()
            {
                CategoryId = id
            };
            return View(dto);
        }`

I expect in my View I receive the follow object:

{
"id": "00000000-0000-0000-0000-000000000000",
"description": "",
"categoryid": "dba6b8e4-fb16-4f88-290d-08d44abea368"
}

But I receive:

{
"id": "dba6b8e4-fb16-4f88-290d-08d44abea368",
"description": "",
"categoryid": "dba6b8e4-fb16-4f88-290d-08d44abea368"
}

So, is it a issue or I need to do some configuration?

**Comment by Tratcher** [comment]
@rynowak ?

**Comment by rynowak** [comment]
We don't have any magic around guids. I don't see anything in the code sample that sets the `Id` value thus it should always be empty. 

Do you have a more complete code sample including the view, and ideally what the request looks like?

**Comment by jonatanrinckus** [comment]
Here is a test repo:
https://github.com/jonatanrinckus/AspNetCoreGuidIssueTest

the HomeController has this action:

`public IActionResult Edit(Guid id)
        {
            var test = new Test()
            {
                AnotherGuidId = id
            };
            return View(test);
        }
`
if you go to /home/edit/4689d77b-a373-450d-a7e6-3394b557ce32
It you bring the Guid on both inputs, but this should me just on one.

And it just happens if the name of parameter is "id".

if I add a [Route("{id}"] attribute, the same happens.

If i chenge for another parameter name like "idt" and [Route("{idt}"], it works like expected.

**Comment by rynowak** [comment]
This happens because entries in the `ModelState` take precedence over the values in the model. This is needed because when you submit a form and are sent back to the form (because of validation errors) you want to see the inputs that you typed in, and not the values on the model. 

/cc @dougbu in case he wants to add more

When you successfully bind the `id` route value, it creates an entry in the `ModelState` for that value. If you don't want to see that on the form, just clear it.
```
        public IActionResult Edit(Guid id)
        {
            var test = new Test()
            {
                AnotherGuidId = id
            };

            ModelState.Remove("id");

            return View(test);
        }
```

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.

**Comment by davidalpert** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  spinthemoose@gmail.com
    Domain spinthemoose.com has exceeded the max emails per hour (216/200 (108%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext4.iad.github.net ([192.30.252.195]:48958 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by cp1164.blacksun.ca with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.89_1)
	(envelope-from <noreply@github.com>)
	id 1eVQfy-0000GU-EH
	for david@spinthemoose.com; Sat, 30 Dec 2017 17:36:26 -0600
Date: Sat, 30 Dec 2017 15:36:06 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1514676966;
	bh=uHhsz/F6s96V/iYVoAoWSyYq9MRA11ukl6m7uZa0+Nw=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=jYLzRFIgaqHsAePxrhmtoZyXgBFnu5uzCAUvSNxaIMXo6N2dsSMVVYzKIc9mC8oXl
	 I7GhV5+nutpaSwmTHNfSg2dxSixxudMwPa5iaqtyqvrP8pNols4RoTb905G9/FBslJ
	 qC2xkbzpvn2q/R/uEKv427Q5/RLQN5E+h74D8gak=

**Comment by davidalpert** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  spinthemoose@gmail.com
    Domain spinthemoose.com has exceeded the max emails per hour (217/200 (108%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o5.sgmail.github.com ([192.254.113.10]:33539)
	by cp1164.blacksun.ca with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89_1)
	(envelope-from <bounces+848413-6f87-david=spinthemoose.com@sgmail.github.com>)
	id 1eVQfz-0000GZ-0o
	for david@spinthemoose.com; Sat, 30 Dec 2017 17:36:27 -0600
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=NLXTiiz+aZmuLXorAXFe+qicUig=; b=FvYDakHGmQay9U2F
	lG9SBOAJXAz2DNSGimHpom6InaLOlehx7YSN1YwVbWbheVGqZOfqf6qgjfao6jmo
	vJGAzf+oAUK22ROigZaTcTQ8kkidLAZWLX5HorACBf4klSG7nCQ1U/xfoh/RVkRW
	UjUK1H032vMyQb5+DgYcLMYwMr4=
Received: by filter0553p1mdw1.sendgrid.net with SMTP id filter0553p1mdw1-7336-5A4822E6-2C
        2017-12-30 23:36:07.009897893 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0022p1iad2.sendgrid.net (SG) with ESMTP id dxDn7d29SiqHFoNiiy-Mdg
	for <david@spinthemoose.com>; Sat, 30 Dec 2017 23:36:07.018 +0000 (UTC)
Date: Sat, 30 Dec 2017 23:36:07 +0000 (UTC)
