### ISSUE TITLE
Configuration.GetSection destroys Configuration["YYY"]

### ISSUE THREAD

**Issue by Eneuman** [aspnet/Home#1928]
I have a web application with a startup.cs that looks something like this:

```
public Startup(IHostingEnvironment env)
    {
      var builder = new Microsoft.Extensions.Configuration.ConfigurationBuilder()
          .SetBasePath(env.ContentRootPath)
          .AddJsonFile("appsettings.json", optional: true, reloadOnChange: true)
          .AddJsonFile($"appsettings.{env.EnvironmentName}.json", optional: true)
          .AddEnvironmentVariables();

      if (env.IsDevelopment())
      {
        // This will push telemetry data through Application Insights pipeline faster, allowing you to view results immediately.
        builder.AddApplicationInsightsSettings(developerMode: true);
      }

      var config = builder.Build();

      // Add key vault configuration if not in local development mode
      if (!env.IsDevelopment())
      {
        builder.AddAzureKeyVault($"https://{config["KeyVault:Vault"]}.vault.azure.net/", config["KeyVault:ClientId"], config["KeyVault:ClientSecret"]);
      }

      Configuration = builder.Build();
    }

public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory, IServiceProvider serviceProvider)
    {

      loggerFactory.AddConsole(Configuration.GetSection("Logging"));
      loggerFactory.AddDebug();

      app.UseCors(policy =>
      {
        policy.WithOrigins(Configuration["AppSettings:CorsOrigins"]);
        policy.AllowAnyHeader();
        policy.AllowAnyMethod();
        policy.WithExposedHeaders("WWW-Authenticate");
      });
}
```

After publishing it to Azure, and restarting the site I noticed that Cors origins was not set correctly.
I added a IConfiguration to one of my MVC Controls and returned the value of Configuration["AppSettings:CorsOrigins"]. The value looked fine but CORS wasn't working.

I decided to hard code the domain in the WithOrigins option and publish again. Now everything was working fine. After removing the hard coded values and restore my configuration it stoped working again.

I decided to exclude any code that might interfere with the Configuration object and when I removed:

```
     loggerFactory.AddConsole(Configuration.GetSection("Logging"));
      loggerFactory.AddDebug();
```
everything started to work again. Somehow, Configuration.GetSection or the loggerFactory does something to the Configuration so it doesn't work as expected afterwards. But using IConfiguration later in a controller seems to work.

Am I missing something here or is this a bug?

(VS 2017 latest Tooling, .Net Core 1.1.0)

**Comment by Tratcher** [comment]
This issue was moved to aspnet/Configuration#592
