### ISSUE TITLE
fail to run asp dotnet core mvc application on heroku

### ISSUE THREAD

**Issue by AbhimanyuAryan** [aspnet/Home#1929]
Here's an [issue](https://github.com/friism/dotnet-buildpack/issues/4) I have created on ASP DotNetCore buildpack repo. I can't figure out why one app runs(generated by `dotnet new -t web`) & the other doesn't (yeoman generated app)

as suggested by halter73 its a razor [issue]( https://github.com/aspnet/KestrelHttpServer/issues/1357#issuecomment-279093599)

Please let me know what's the possible fix. What's causing this weird behavior. I have no idea if that's a problem with Razer, Yeoman template or Build-pack(if it would have been the build-pack why the other applications runs)

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.

**Comment by davidalpert** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  spinthemoose@gmail.com
    Domain spinthemoose.com has exceeded the max emails per hour (214/200 (107%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext2.iad.github.net ([192.30.252.193]:45413 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by cp1164.blacksun.ca with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.89_1)
	(envelope-from <noreply@github.com>)
	id 1eVQfw-0000GN-MT
	for david@spinthemoose.com; Sat, 30 Dec 2017 17:36:24 -0600
Date: Sat, 30 Dec 2017 15:36:05 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1514676965;
	bh=JgXYEKdwZ+ixfVt18nbCQJAmsdISCX7m5PpHPgVmNYQ=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=Eqbk3SHV/GvIIThkzCK9RnbwlJ+cy1elg+l0BTUJA/3RIfUJQsYkVvGEE5Lykr0aD
	 VQi1/IrkPvIprwsJXW8ob2TSUpQqvzdcv95G84eB813Lm6m87VSxcmgbRBPZ/8R24X
	 wChXIE1Td1NEqNAcLlTRnIuetRI7VdFApTfnRIj4=

**Comment by davidalpert** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  spinthemoose@gmail.com
    Domain spinthemoose.com has exceeded the max emails per hour (215/200 (107%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o3.sgmail.github.com ([192.254.112.98]:17102)
	by cp1164.blacksun.ca with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89_1)
	(envelope-from <bounces+848413-6f87-david=spinthemoose.com@sgmail.github.com>)
	id 1eVQfy-0000GP-BL
	for david@spinthemoose.com; Sat, 30 Dec 2017 17:36:26 -0600
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=xw9gZ4EQFjRpnQ75+fDLgo60+mM=; b=fih5nKKsxE2AFLX4
	d/N7TVRd1m8wZ0+uQiQP5YN7VfLrbhDaEVcqVdPjF/Jk/YQTkL40eROkSw0ZOjj3
	ubHYFdYUjiVBChZoMauRxhA5h94218+Db57jFHb0zGBmw+HLbQtPt+TRwD92XxFX
	gAdjSZPmp3a0jJHtRjWliSEickg=
Received: by filter0226p1las1.sendgrid.net with SMTP id filter0226p1las1-16867-5A4822E5-1A
        2017-12-30 23:36:05.638446545 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0001p1iad1.sendgrid.net (SG) with ESMTP id VllQV269SmyEjHvlmsfqhg
	for <david@spinthemoose.com>; Sat, 30 Dec 2017 23:36:05.658 +0000 (UTC)
Date: Sat, 30 Dec 2017 23:36:05 +0000 (UTC)
