### ISSUE TITLE
IIS cant host core app if there are Space's in the dll filename

### ISSUE THREAD

**Issue by MrSteinster** [aspnet/Home#1931]
When trying to host an application with spaces in the dll-name, the service wont start and returns an error because the dotnet command is executed without quotes around dll-filename.

Reason:
`dotnet <dll-filename> return error. (ex: dotnet my file.dll)`

Fix:
`dotnet "<dll-filename>" (ex: dotnet "my file.dll")`

**Comment by Tratcher** [comment]
Does this work in IIS Express / VS?
What does your published web.config look like?

**Comment by MrSteinster** [comment]
I created a project with the name Modern CORE 2017 and it runs locally just fine, so I guess it works in iis express. When moving to server (Windows Server 2012 R2) I couldnt open the site. I found an event in application logs where the message was that something like "dotnet Modern CORE 2017.dll" failed. So I ran the command dotnet "Modern CORE 2017.dll" and it worked (in command line). When I changed the output to Modern_CORE_2017.dll it worked on the first try, no problemos.

My web.config:
`<?xml version="1.0" encoding="utf-8"?>
<configuration>

  

  <system.webServer>
    <handlers>
      <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModule" resourceType="Unspecified"/>
    </handlers>
    <aspNetCore processPath="%LAUNCHER_PATH%" arguments="%LAUNCHER_ARGS%" stdoutLogEnabled="false" stdoutLogFile=".\logs\stdout" forwardWindowsAuthToken="false"/>
  </system.webServer>
</configuration>`

**Comment by MrSteinster** [comment]
I should mention I use VS 2017 RC

**Comment by Tratcher** [comment]
That's not the published web.config. The published one would have replaced %LAUNCHER_PATH%.

**Comment by MrSteinster** [comment]
then this must be! from the server:

`<?xml version="1.0" encoding="utf-8"?>
<configuration>
  
  <system.webServer>
    <handlers>
      <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModule" resourceType="Unspecified" />
    </handlers>
    <aspNetCore processPath="dotnet" arguments=".\Modern_CORE_2017.dll" stdoutLogEnabled="false" stdoutLogFile=".\logs\stdout" forwardWindowsAuthToken="false" />
  </system.webServer>
</configuration>`

**Comment by MrSteinster** [comment]
ok so please wait for web.config , I have to create the project again since I dont have the old config file.

**Comment by MrSteinster** [comment]
web.config:
``<?xml version="1.0" encoding="utf-8"?>
<configuration>
  
  <system.webServer>
    <handlers>
      <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModule" resourceType="Unspecified" />
    </handlers>
    <aspNetCore processPath="dotnet" arguments=".\Modern CORE 2017.dll" stdoutLogEnabled="false" stdoutLogFile=".\logs\stdout" forwardWindowsAuthToken="false" />
  </system.webServer>
</configuration>``

**Comment by Tratcher** [comment]
@shirhatti Should ANCM be able to handle this? Or should Publish generate quoted output?

**Comment by moozzyk** [comment]
Try changing arguments in the published config to (notice single quotes for the attribute value:
`arguments='".\Modern CORE 2017.dll"'`

**Comment by shirhatti** [comment]
This issue sounds vaguely familiar, but a cursory search found me no prior issues. @pan-wang?

**Comment by jbeckton** [comment]
It's an easy fix... don't put spaces in the file name! Who does this
anyways?

On Tue, Feb 14, 2017 at 2:40 PM, Sourabh Shirhatti <notifications@github.com

**Comment by MrSteinster** [comment]
great work around.
another work around is to rename the dll output name. 

Since Visual Studio supports project names with spaces, it should also handle this type of situation.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.

**Comment by davidalpert** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  spinthemoose@gmail.com
    Domain spinthemoose.com has exceeded the max emails per hour (212/200 (106%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o9.sgmail.github.com ([167.89.101.2]:32887)
	by cp1164.blacksun.ca with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89_1)
	(envelope-from <bounces+848413-6f87-david=spinthemoose.com@sgmail.github.com>)
	id 1eVQfq-0000FX-1E
	for david@spinthemoose.com; Sat, 30 Dec 2017 17:36:18 -0600
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=ha09xBN3LEEKyrV0/QsGJUduQFM=; b=Up/EAvYWhcYt7Rah
	IY3Lr2DMxCivmyH03baOaDHv6N239k3GdcHtLXw/axDlwArlmuNbYZwAEKbs+Klz
	uWUfjMkXoRMNil1LIfatxrZT4A5Q0WPO4guxC4QholUW2wZtL9iI1H9uGoLLj9G4
	IphRbpkIEk/PObjXiZOyDOuxveM=
Received: by filter0494p1las1.sendgrid.net with SMTP id filter0494p1las1-17801-5A4822DD-24
        2017-12-30 23:35:57.830317622 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0009p1iad2.sendgrid.net (SG) with ESMTP id jWv0MCXLT7a_kiibyeEL8A
	for <david@spinthemoose.com>; Sat, 30 Dec 2017 23:35:57.777 +0000 (UTC)
Date: Sat, 30 Dec 2017 23:35:57 +0000 (UTC)

**Comment by davidalpert** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  spinthemoose@gmail.com
    Domain spinthemoose.com has exceeded the max emails per hour (213/200 (106%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext7.iad.github.net ([192.30.252.198]:47297 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by cp1164.blacksun.ca with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.89_1)
	(envelope-from <noreply@github.com>)
	id 1eVQfq-0000FY-6g
	for david@spinthemoose.com; Sat, 30 Dec 2017 17:36:18 -0600
Date: Sat, 30 Dec 2017 15:35:58 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1514676958;
	bh=1geXOEi1WvZaeTg162keE4F+tFHapFwHfpggvysDO1U=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=J5AGuOKWf+pYxy1ce8lPxR/XSMaafycpFf0MxnvOrUyWPTMnKbyNx1oRD47rnE4S1
	 6eND63citQ2NzMhk5O/OJ03f/eTfnXKx/aTbCub5EsWNxgfqHKv4TbXIfTLo0ZZaaK
	 oXDDmFnlrS7PrjR3IfrXrZG1MacX1WfFDkHV/jrM=
