### ISSUE TITLE
ASP.NET cookie not persisted when Remember Me set using IISExpress Chrome

### ISSUE THREAD

**Issue by dotnetshadow** [aspnet/Home#1933]
While developing a couple of ASP.NET Core websites, when I try to **debug locally using IISExpress**
If I try to login using the **Chrome browser** with the **Remember Me** option, I **cannot login and no cookie** is generated. But if I use kestrel browser instead everything is fine.

**Setup**
Visual Studio 2015 Update 3
Running ASP.NET Core Mvc 1.1.0
Windows 10 x64
Chrome 56.0.2924.87 (64-bit)

**Steps to Reproduce**
Create a brand new asp.net core website with Individual User Accounts
Debug a site using IIS Express
Navigate to site in chrome browser i.e. http://localhost:12345
Create a user using Register
After creating the user logout
Try to Login and tick Remember me
FAIL

**Result**
Unable to login and no cookie is created in Chrome browser

**Further Tests**
*When remember me is ON*
kestrel firefox and chrome GOOD
IISExpress Firefox GOOD
IISExpress Chrome FAIL

*When remember me is OFF*
Every combination GOOD

**Comment by Tratcher** [comment]
@HaoK

**Comment by HaoK** [comment]
Closing since there's an identity issue now which we can use to track this
