### ISSUE TITLE
Asp.net core isn't rebuilt when folder name has changed

### ISSUE THREAD

**Issue by 777olexandr** [aspnet/Home#1935]
Hi guys. I;m trying now to work with core framework and I saw many bugs... I want to report the one I think is quite hidden to find - if I rename my folder and start building the visual studio 2015 says it's up to date. So for example if I create some folder for data and then rename it this change isn't visible I guess for build manager. I know that for namespaces it doesn't matter but for other types of folders like for storing data it;s critical.

**Comment by 777olexandr** [comment]
One more issue: nuget command for creating migrations in code first approach puts them right at the top of root, not in Data/Migrations folder that is created in visual studio sample. So to fix it I always have to write additional flag - "-o" to point right path.

**Comment by 777olexandr** [comment]
asp-validation-for doesn't catch up this type of error: "Email 'email...' is already taken.". Asp version 1.1

**Comment by Tratcher** [comment]
Note that the 2015 tooling is obsolete and has been replaced by 2017 RC. Can you still reproduce these with 2017?

**Comment by 777olexandr** [comment]
It's interesting but I'm developing a project in vs 2015 which as I know is the latest stable version of vs. Should I move to vs 2017 right now or can continue with old one? How to migrate application with user individual accounts to vs 2017?

**Comment by Tratcher** [comment]
You can use 2015 but we won't be addressing any ASP.NET tooling bugs for it. 2017 is releasing very soon and includes migration help.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.

**Comment by davidalpert** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  spinthemoose@gmail.com
    Domain spinthemoose.com has exceeded the max emails per hour (208/200 (104%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o5.sgmail.github.com ([192.254.113.10]:17589)
	by cp1164.blacksun.ca with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89_1)
	(envelope-from <bounces+848413-6f87-david=spinthemoose.com@sgmail.github.com>)
	id 1eVQfa-0000EY-Ts
	for david@spinthemoose.com; Sat, 30 Dec 2017 17:36:03 -0600
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=Oo1L06YZTAqCAffjt2DJUx21jv8=; b=wbR0vt5T6DHm7Dz9
	yVnSur5uHnpMidNmeJcqDpGsuPuah2KXo6hjsmf+LpV/R+u5bRdSs73TQmh4FH/H
	hdg/sZ7cEG23GtIpO4zBj6LUL2hrimw8iiTvsmNawTb1vwN+n0Hjwu3dzOCu07YG
	Kx+f0a8QF+4TzES2N3LYbaHphGI=
Received: by filter1147p1mdw1.sendgrid.net with SMTP id filter1147p1mdw1-18657-5A4822CF-2
        2017-12-30 23:35:43.120900687 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0012p1iad2.sendgrid.net (SG) with ESMTP id SLvsmVUIRlOckqS0x_9xqQ
	for <david@spinthemoose.com>; Sat, 30 Dec 2017 23:35:43.178 +0000 (UTC)
Date: Sat, 30 Dec 2017 23:35:43 +0000 (UTC)

**Comment by davidalpert** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  spinthemoose@gmail.com
    Domain spinthemoose.com has exceeded the max emails per hour (209/200 (104%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o9.sgmail.github.com ([167.89.101.2]:58732)
	by cp1164.blacksun.ca with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89_1)
	(envelope-from <bounces+848413-6f87-david=spinthemoose.com@sgmail.github.com>)
	id 1eVQfb-0000EX-15
	for david@spinthemoose.com; Sat, 30 Dec 2017 17:36:03 -0600
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=yzuaEqgyO7noqeeU/wRVhfdRd7c=; b=E3T2vzI6t9/73Mk7
	cMra1KSoXrgYpFKmOGXRNavwsiAIAUHz2uPeTXh070jkfUffATNZCypY+kPUKbrf
	L94xXw1KOld+U0i3BQHYhuPqNvvbOBvhFr6tiHcsXr9oJWu3yXLpbtQfHtvkcv8K
	BYBRnCgDmWcXsJYj4qyL89gF6Co=
Received: by filter0826p1mdw1.sendgrid.net with SMTP id filter0826p1mdw1-22238-5A4822CE-14
        2017-12-30 23:35:42.803586453 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0017p1iad2.sendgrid.net (SG) with ESMTP id mebGdLjeS7qAIIkxWD5gWw
	for <david@spinthemoose.com>; Sat, 30 Dec 2017 23:35:42.830 +0000 (UTC)
Date: Sat, 30 Dec 2017 23:35:42 +0000 (UTC)
