### ISSUE TITLE
UserManager.AddClaimAsync get an exception : Field 'Id' doesn't have a default value

### ISSUE THREAD

**Issue by xiaoxin01** [aspnet/Home#1937]
I wrote a test for AddClaimAsync like this:

```C#
            var user = userManager.Users.First();
            //await userManager.AddToRoleAsync(user, "role2");
            await userManager.AddClaimAsync(user, new Claim("employeenumber", "mtk12345"));
```

Then an exception throw:

> Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details. ---> MySql.Data.MySqlClient.MySqlException: Field 'Id' doesn't have a default value

Then I checked the migration file:

```
migrationBuilder.CreateTable(
                name: "AspNetUserClaims",
                columns: table => new
                {
                    Id = table.Column<int>(nullable: false)
                        .Annotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn),
                    ClaimType = table.Column<string>(nullable: true),
                    ClaimValue = table.Column<string>(nullable: true),
                    UserId = table.Column<string>(nullable: false)
                },
```

My database is mysql, So what can I do to change the Id column to auto incremental?

**Comment by Tratcher** [comment]
@HaoK

**Comment by HaoK** [comment]
In the default SqlServer implementation we don't set the Id, and just rely on it being generated for us.

@divega @ajcvickers do you guys have any ideas what might be going wrong here that would cause MySql not to be able to do the same?  

https://github.com/aspnet/Identity/blob/dev/src/Microsoft.AspNetCore.Identity.EntityFrameworkCore/IdentityUserClaim.cs

https://github.com/aspnet/Identity/blob/dev/src/Microsoft.AspNetCore.Identity.EntityFrameworkCore/IdentityDbContext.cs#L184

**Comment by xiaoxin01** [comment]
I found that the problem is MySql.Data.EntityFrameworkCore.

When I change the package to Pomelo.EntityFrameworkCore.MySql and run

```
dotnet ef migrations add initial
```

the package will change the migrationBuilder like this:

```C#
migrationBuilder.AlterColumn<string>(
                name: "Id",
                table: "AspNetRoles",
                nullable: false,
                oldClrType: typeof(string))
                .Annotation("MySql:ValueGeneratedOnAdd", true);
```

Every thing works file.

So not use MySql.Data.EntityFrameworkCore and use Pomelo.EntityFrameworkCore.MySql instead.

Thanks all, @HaoK @Tratcher
