### ISSUE TITLE
Question: Release date of next version of ASP.Net Core

### ISSUE THREAD

**Issue by garora** [aspnet/Home#1938]
I am intending to get started with a new project using version 2.0 of .Net Core. From  [roadmap](https://github.com/dotnet/core/blob/master/roadmap.md) I learnt that the expected release schedule is Q3 for the version 2.0 of .Net Core. In this context can you answer the following questions for me:

1. What is the expected release date for .Net Core 2.0 and .Net Standard 2.0?
2. What is the expected new version of asp.net core and date?

The reason I am asking for this information is that I don't want to get caught in the middle of my new project with the current version 2.0 of .Net Core when next version is released.

**Comment by GuardRex** [comment]
They can't provide specific release dates because they aren't able to predict precisely when the work will be complete. On a broader note, I don't think you should be too concerned about radical changes after the move to MSBuild/csproj is complete.

**Comment by natemcmaster** [comment]
ASP.NET Core 2.0 will ship along with .NET Core 2.0. As the [roadmap](https://github.com/dotnet/core/blob/master/roadmap.md) you found says, "Q3 2017". 

Feel free to ["dogfood" daily builds](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/dogfooding.md) in the meantime.
