### ISSUE TITLE
UseDeveloperExceptionPage doesn't work when follows UseMvcWithDefaultRoute

### ISSUE THREAD

**Issue by wapxmas** [aspnet/Home#1939]
Following code doesn't show any exception.
Only, if I put UseMvcWithDefaultRoute on line followed UseDeveloperExceptionPage block, it works as supposed to.
```
app.UseMvcWithDefaultRoute();

if (env.IsDevelopment())
{
  app.UseDeveloperExceptionPage();
}
```

**Comment by Tratcher** [comment]
By design, you're building an ordered pipeline. UseDeveloperExceptionPage needs to get into the pipeline before the exceptions you want to catch as exceptions are throw backwards up the stack/pipeline.

**Comment by GuardRex** [comment]
@wapxmas There's a lot of juicy info on middleware ordering here :point_right: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware#ordering
