### ISSUE TITLE
Any options to override the Custom TagHelper class with new Custom Class?

### ISSUE THREAD

**Issue by manikandan05** [aspnet/Home#1940]
Hi,

I have custom TagHelper class (**GradeA from ProjectA**) with set of properties, but some reasons i need to override my custom class to extend some set of new properties by another custom Tag Helper class in another one project (**GradeB from ProjectB**).

The **GradeA** class exists library, already have set of serialization to generate the Html element and script. So i need options to override my **GradeA** class with new **GradeB** class.

[HtmlTargetElement("cwd:Grade")]
public class GradeB : GradeA
{
//set of new properties
public override void Process(TagHelperContext context, TagHelperOutput output) {
//context - returns result from GradeA
//output - holds the result returns from GradeA
}
}
`

If there is any options exists for this way of override implementation? 

Thanks,

**Comment by NTaylorMullen** [comment]
If you want to override your own implementations you have two approaches:

1. Use `TagHelper`s from services (`services.AddMvc().AddTagHelpersAsServices()`)and then override the appropriate TagHelper type registration.
2. `@removeTagHelper OldTagHelperTypeName, OldTagHelperAssemblyName` and then `@addTagHelper NewTagHelperTypeName, NewTagHelperAssemblyName`
