### ISSUE TITLE
HTTP response code for Redirect not readily discoverable

### ISSUE THREAD

**Issue by breyed** [aspnet/Home#1941]
Pressing Ctrl+K, Ctrl+I (show intellisense) on a MVC `Redirect()` method doesn't display whether it uses HTTP 307 or 302. This important detail should be readily visible.

Likewise, pressing F12 on `Redirect` and then F12 on its return type `RedirectResult` shows the `RedirectResult` class definition with no documentation whatsoever. At a minimum the HTTP response code (based on whether a permanent redirect) should be shown in the XML documentation.

**Comment by pranavkm** [comment]
Moved to https://github.com/aspnet/Mvc/issues/5855.
