### ISSUE TITLE
ANCM only install doesn't add VS2015 C++ redistr

### ISSUE THREAD

**Issue by vbokashov** [aspnet/Home#1943]
I have, possibly expected, issue publishing ASP.NET Core self-containing site on just installed Windows 2012 R2 with IIS role.

Repro steps:
1. Windows 2012 R2 with IIS role and all important Windows updates installed. Nothing else is installed.
2. Install ANCM using "DotNetCore.1.0.3_1.1.0-WindowsHosting.exe OPT_INSTALL_LTS_REDIST=0 OPT_INSTALL_FTS_REDIST=0 /install /quiet /norestart", so no VS2015 C++ Redistributable was installed - not sure it is not by design.
3. Windows log errors:
-------------------------------------
Faulting application name: Web.UI.exe, version: 1.0.1.4500, time stamp: 0x576218d2
Faulting module name: i-ms-win-crt-runtime-l1-1-0.dll, version: 6.3.9600.18438, time stamp: 0x57ae642e
Exception code: 0xc0000135
Fault offset: 0x00000000000ecdd0
Faulting process id: 0x248
Faulting application start time: 0x01d291718d0ca28b
Faulting application path: C:\inetpub\wwwroot\NextWebUi\Web.UI.exe
Faulting module path: i-ms-win-crt-runtime-l1-1-0.dll
Report Id: cabbc4c4-fd64-11e6-80be-080027b2d08e
--------------------------------------
--------------------------------------
Application 'MACHINE/WEBROOT/APPHOST/DEFAULT WEB SITE/NEXTWEBUI' with physical root 'C:\inetpub\wwwroot\NextWebUi\' failed to start process with commandline '"C:\inetpub\wwwroot\NextWebUi\Web.UI.exe" ', ErrorCode = '0x80004005 : ff.
--------------------------------------

ANCM installation logs:
[ancmInstallation.zip](https://github.com/aspnet/Home/files/807568/ancmInstallation.zip)

4. If I install ANCM with ever LTS or FTS or both VS2015 C++ Redistributable was installed and Core app works as expected.

**Comment by Tratcher** [comment]
@shirhatti @joeloff

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.

**Comment by davidalpert** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  spinthemoose@gmail.com
    Domain spinthemoose.com has exceeded the max emails per hour (206/200 (103%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o7.sgmail.github.com ([167.89.101.198]:43648)
	by cp1164.blacksun.ca with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89_1)
	(envelope-from <bounces+848413-6f87-david=spinthemoose.com@sgmail.github.com>)
	id 1eVQfM-0000B3-BC
	for david@spinthemoose.com; Sat, 30 Dec 2017 17:35:48 -0600
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=ZEVd0q5OSzl20krJoI6qQXoD1ek=; b=cxduCQ9d+uLbYCMj
	re2zf8VpT7l09MJ/s8dIG8p8IYJw/HwD90snViMT1w9nQtupjULMrX807iE2psnk
	lx6Y8JdPvZwFD31aEETlr86AYRXzrc+YsF3gk9oe2Vqqstzppil2zjqFgYj+OWEr
	bK42mhWmrakvrj1NeanjO+tKnII=
Received: by filter0435p1mdw1.sendgrid.net with SMTP id filter0435p1mdw1-21665-5A4822C0-C
        2017-12-30 23:35:28.193809956 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0006p1iad1.sendgrid.net (SG) with ESMTP id 50KscOI4TmWi9tsYxksWPg
	for <david@spinthemoose.com>; Sat, 30 Dec 2017 23:35:28.204 +0000 (UTC)
Date: Sat, 30 Dec 2017 23:35:28 +0000 (UTC)

**Comment by davidalpert** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  spinthemoose@gmail.com
    Domain spinthemoose.com has exceeded the max emails per hour (207/200 (103%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o4.sgmail.github.com ([192.254.112.99]:32835)
	by cp1164.blacksun.ca with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89_1)
	(envelope-from <bounces+848413-6f87-david=spinthemoose.com@sgmail.github.com>)
	id 1eVQfQ-0000Bh-3P
	for david@spinthemoose.com; Sat, 30 Dec 2017 17:35:52 -0600
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=bQTB6yMZ/LT6rFZVFEiFeKAvYyk=; b=LV1cVQiIvhygGfUz
	0hk+QRjCfvHX8FpLXnLSP7pHEDJYVh2bLDkn9/2gZjvru7PcPPVapWELbUh5kkwO
	W/U2xDE+q1o5KwmqUzhim3jNiGQoDY7xGpfzV7GdGQhQhv4MmAN2PoS1EHmXLC3t
	Q0a8TjGQZD7c7ztv7Uwi3ld1Hbo=
Received: by filter0564p1las1.sendgrid.net with SMTP id filter0564p1las1-21023-5A4822C3-13
        2017-12-30 23:35:31.765739421 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0008p1iad1.sendgrid.net (SG) with ESMTP id zOqWLRC1Sfmsr-xmmcVZoA
	for <david@spinthemoose.com>; Sat, 30 Dec 2017 23:35:31.613 +0000 (UTC)
Date: Sat, 30 Dec 2017 23:35:31 +0000 (UTC)
