### ISSUE TITLE
Provide sources through SourceBrowser

### ISSUE THREAD

**Issue by tiesmaster** [aspnet/Home#1944]
It would be really awesome if ASP.NET Core would also be available through Kirill's [SourceBrowser](https://github.com/KirillOsenkov/SourceBrowser), [Roslyn, CoreFx, and .NET Framework](https://github.com/KirillOsenkov/SourceBrowser#sourcebrowser) are already available. I guess this one is kinda of missing online ;)

I've been learning ASP.NET Core, and going through the excellent [Fundamentals](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/) section, and being able to go through the sources makes it really easy to dive into the details, without having to clone every repo, and opening it in VS.

**Comment by davidfowl** [comment]
@natemcmaster you did something with this a while ago. Is it up anywhere?

**Comment by natemcmaster** [comment]
I created an unofficial source browser site last year for the 1.0.0 release. I haven't updated it since, but here you go:

https://github.com/natemcmaster/AspNetSourceBrowser
https://aspnetsource.azurewebsites.net/

**Comment by tiesmaster** [comment]
Awesome! That's really great, although, it's not completely up to date, it is really handy as reference.

Feel free to close the issue, if there are no plans to make this official or permanent (but I hope you guys do ;)

**Comment by natemcmaster** [comment]
We considered making it official but never got around to actually doing that. I'll use my internal Microsoft email powers to check again on doing something official.

**Comment by natemcmaster** [comment]
Looks like https://source.dot.net/ already exists for .NET Core. Until something official exists, https://aspnetsource.azurewebsites.net/ is the best place for ASP.NET Core.

**Comment by natemcmaster** [comment]
Btw, you can follow https://github.com/dotnet/source-indexer/issues/5 for progress on that.

**Comment by tiesmaster** [comment]
Yeah, I found https://source.dot.net/ through Kirill's readme.md (which now contains [yours](https://github.com/KirillOsenkov/SourceBrowser/pull/66) as well 😉 ), though, I noticed indeed that ASP.NET Core wasn't added. Thanks for making the issue on source-indexer 👍
