### ISSUE TITLE
Feature request - documentation generator for MSDoc comments

### ISSUE THREAD

**Issue by Dima4ka** [aspnet/Home#1946]
Dear developers,

I feel like ASP Core on Mac is as feature-rich and ready-for-production as it is on Windows, however there is one necessary component missing. **Doc generator**.

Every major language (and C# for Windows only) has some kind of documentation style and appropriate generator. Java has JDoc, javascript has JSDoc and so on. I know that C# has MSDoc (xml) comments like the following:

```
/// <summary>
/// Short summary here...
/// </summary>
/// <param name="metric">Metric to update data for.</param>
/// <returns>New Metric object with the data updated.</returns>
Task<Metric> CacheMetric(Metric metric);
```

But it lacks a tool which would read the comments and generate pretty html file(s) with documentation in, say, MSDN style.

Known workarounds:
* I can use SandCastle, but it is old, not maintained anymore, and the worst - Windows only.
* I can (and I do) use Doxygen, but this is a "universal" solution which does not understand all features of C# language and does not give outstandingly styled html.

**Actual feature request.** I want a cross platform open-source tool that consumes MSDoc documented files and produces HTML project that is an MSDN styled web-viewable documentation.

Is there any tool already released? Are there any plans to develop such a tool? What do people use instead?

**Comment by Dima4ka** [comment]
Please feel free to move it to another repo.
I honestly do not know the best repo for it.
Or, point me to the duplicate.

**Comment by davidfowl** [comment]
see https://github.com/dotnet/docfx

**Comment by Dima4ka** [comment]
Thanks, that works!
