### ISSUE TITLE
<link /> fallbacks cause Content Security Policy to report

### ISSUE THREAD

**Issue by aaron-bozit** [aspnet/Home#1951]
The following ASP code to provide a CDN fallback causes script-src CSP to block loading of the resource
`
		@*Font Awesome*@
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
			  asp-fallback-href="~/lib/font-awesome/css/font-awesome.min.css"
			  asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"/>
`

Which upon HTTP request produces;
`<meta name="x-stylesheet-fallback-test" content="" class="sr-only" /><script>!function(a,b,c,d){var e,f=document,g=f.getElementsByTagName("SCRIPT"),h=g[g.length-1].previousElementSibling,i=f.defaultView&&f.defaultView.getComputedStyle?f.defaultView.getComputedStyle(h):h.currentStyle;if(i&&i[a]!==b)for(e=0;e<c.length;e++)f.write('<link href="'+c[e]+'" '+d+"/>")}("position","absolute",["\/lib\/semantic\/dist\/font-awesome.min.css"], "rel=\u0022stylesheet\u0022 ");</script>`

The web browser console;
`Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src https://<somesubdomain>.azurewebsites.net https://cdnjs.cloudflare.com https://ajax.cloudflare.com https://ajax.aspnetcdn.com https://www.google-analytics.com”).  <PageName>:15`

Is there a way to include a nonce, or would the only work around for this be to add inline-unsafe?

Thanks.

Boz.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.

**Comment by davidalpert** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  spinthemoose@gmail.com
    Domain spinthemoose.com has exceeded the max emails per hour (203/200 (101%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o11.sgmail.github.com ([167.89.101.202]:33864)
	by cp1164.blacksun.ca with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89_1)
	(envelope-from <bounces+848413-6f87-david=spinthemoose.com@sgmail.github.com>)
	id 1eVQfD-0000AJ-Vi
	for david@spinthemoose.com; Sat, 30 Dec 2017 17:35:40 -0600
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=Xdn3reMAgva9p2wKZi2aUdQ88XA=; b=MkFH7TxSD041PScp
	Osmw2RGW2wsdt+VSE6HFp/XgdVq+BVnXl+Shh0FYsgmUslfk5MVTeLjh3glyFBTs
	gSfvO9xZ7EOs/yG39fGhFKz2oUFv+wzsUdqQMQLByDV3uMGXwRUtbccZRNrEPDY2
	npHiSi+0GNDuUMlzaJHPqK5DyS4=
Received: by filter0945p1mdw1.sendgrid.net with SMTP id filter0945p1mdw1-16289-5A4822B7-10
        2017-12-30 23:35:19.632122686 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0004p1iad1.sendgrid.net (SG) with ESMTP id 1lB25qFOSVSbT_hZ7XtwCQ
	for <david@spinthemoose.com>; Sat, 30 Dec 2017 23:35:19.598 +0000 (UTC)
Date: Sat, 30 Dec 2017 23:35:19 +0000 (UTC)

**Comment by davidalpert** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  spinthemoose@gmail.com
    Domain spinthemoose.com has exceeded the max emails per hour (202/200 (101%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext2.iad.github.net ([192.30.252.193]:36218 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by cp1164.blacksun.ca with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.89_1)
	(envelope-from <noreply@github.com>)
	id 1eVQfD-0000AI-9Y
	for david@spinthemoose.com; Sat, 30 Dec 2017 17:35:39 -0600
Date: Sat, 30 Dec 2017 15:35:19 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1514676919;
	bh=nLaudiXYF5SBY/AdfEtHVe/ZR1gz8YexpD2av7/158w=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=H03UoaPpLIf2zP4qamQNha4S5eRksAQvilUaWd9LzKSuBjZ3nukiUfn4I+Ne0e7Cc
	 ot95UfjqysnZ1k1DEvw/a6dNXoIbFgD1w2/tS7KiS68DLZrjErhjs/hIU5/7B3ZHCj
	 nqeXodLIa01dM3WhiLd14aILAfFKkx1XctN+Soso=
