### ISSUE TITLE
.net core app in docker container fails

### ISSUE THREAD

**Issue by syned** [aspnet/Home#1953]
dotnet --version
1.0.0-rc4-004771
---------------------------

Dockerfile
FROM microsoft/dotnet:runtime

COPY out .
ENTRYPOINT ["dotnet", "app.dll"]
---------------------------

docker build -t app .
docker run -it --rm app

Publish
dotnet publish -o out -r ubuntu.16.04-x64

Error:
Failed to load /libhostpolicy.so, error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required b
y /libhostpolicy.so)
An error occurred while loading required library libhostpolicy.so from []

RuntimeIdentifiers: ubuntu.16.04-x64

**Comment by natemcmaster** [comment]
This issue was moved to dotnet/dotnet-docker#216
