### ISSUE TITLE
502 From Redirects on WebAPI/MVC On Same IIS Server

### ISSUE THREAD

**Issue by RobertMcCoy** [aspnet/Home#1954]
For the past few days I've been trying to solve this issue, but I can't ever seem to nail down what the exact problem is...

I have an MVC application and a Web API application hosted on the same IIS Website on a server. I have RedirectToAction() calls within the MVC application that are throwing 502 errors:

502 - Web server received an invalid response while acting as a gateway or proxy server.
There is a problem with the page you are looking for, and it cannot be displayed. When the Web server (while acting as a gateway or proxy) contacted the upstream content server, it received an invalid response from the content server.

I have Integrated Windows Authentication enabled on the applications, and I am running WindowsIdentity.RunImpersonated() for all of the WebAPI calls so that the authentication is forwarded properly. I upgraded to 1.1.1 SDK today (I was using 1.1.0), as well as from VS17 RC2 -> VS17 Enterprise but that still hasn't fixed the problem.

The 502s are ONLY happening in my Create/Update actions on the MVC application (E.g. someone creates a new incident, and then is redirected to the view to see that specific incident, or that incident is updated and redisplayed). You can find code samples on my Stackoverflow thread [(here),](http://stackoverflow.com/questions/42630305/redirecttoaction-throws-502-bad-gateway/42635841) which has sadly died out and thus why I am here. I have exhausted all google searches to find issues not relevant to my specific case, or unrelated to IIS specifically.

I also can't even identify if this is a framework issue or an IIS issue, because the AspNetCore Module Logging says that the 302 Redirect goes through fine, and then a GET request to the view returns a 200 response. I have another 1.0.3 ASP.NET Core application running on the server that has never had this issue before.

If you need any more information please ask, this issue is driving me insane, and is the one thing holding this system back from going into production.

EDIT: I sat down and looked through the logs a bit closer and tracked an entire request from the Home/Index page all the way to the error. This is where I think the request is failing out. In a normal ControllerActionInvoker to the TIM.MVC.Controllers.IncidentsController.View, there is a ViewResultsExecutor that would execute ViewResults running at the View, but here after the 302 redirect, that doesn't seem to be happening. Any thoughts on why that may be?

```
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 POST http://snaptest.fwcs.k12.in.us/tim/Incidents/SaveIncident?incidentId=58 application/x-www-form-urlencoded 763
info: Microsoft.AspNetCore.Authorization.DefaultAuthorizationService[1]
      Authorization was successful for user: FWCS\mccora01.
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
      Executing action method TIM.MVC.Controllers.IncidentsController.SaveIncident (TIM.MVC) with arguments (58, TIM.API.Models.Incident) - ModelState is Valid
info: Microsoft.AspNetCore.Mvc.Internal.RedirectResultExecutor[1]
      Executing RedirectResult, redirecting to /tim/Incidents/View/58.
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
      Executed action TIM.MVC.Controllers.IncidentsController.SaveIncident (TIM.MVC) in 1397.8175ms
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 2097.562ms 302 
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://snaptest.fwcs.k12.in.us/tim/Incidents/View/58  
info: Microsoft.AspNetCore.Authorization.DefaultAuthorizationService[1]
      Authorization was successful for user: FWCS\mccora01.
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
      Executing action method TIM.MVC.Controllers.IncidentsController.View (TIM.MVC) with arguments (58) - ModelState is Valid

```

**Comment by RobertMcCoy** [comment]
I wanted to follow-up on this. I finally found the solution. I believe this is a bug within the framework. Local functions cannot be asynchronous if you use WindowsIdentity.RunImpersonated(). I converted my controller over to be 100% synchronous, and all issues went away with 502's.

@Tratcher Maybe you can confirm or deny if this is the case?

**Comment by Tratcher** [comment]
Yeah, RunImpersonated is not async aware. It kills the impersonation as soon as you return the first Tasks, complete or otherwise.

**Comment by romansp** [comment]
@Tratcher, so is there an opened issue that tracks this problem?

**Comment by Tratcher** [comment]
@romansp no, it's not a bug in the API, it's a mis-use of the API. https://msdn.microsoft.com/en-us/library/dn906219(v=vs.110).aspx

It accepts a `Func<T>` and returns you the resulting T. In @RobertMcCoy's case the T was an incomplete Task, but he'd left the impersonation scope by returning.

You can file a feature request in https://github.com/dotnet/corefx for `Task WindowsIdentity.RunImpersonatedAsync(SafeAccessTokenHandle, Func<Task>)` and `Task<T> WindowsIdentity.RunImpersonatedAsync<T>(SafeAccessTokenHandle, Func<Task<T>>)`

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.

**Comment by davidalpert** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  spinthemoose@gmail.com
    Domain spinthemoose.com has exceeded the max emails per hour (201/200 (100%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o8.sgmail.github.com ([167.89.101.199]:53137)
	by cp1164.blacksun.ca with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89_1)
	(envelope-from <bounces+848413-6f87-david=spinthemoose.com@sgmail.github.com>)
	id 1eVQf9-000096-Rn
	for david@spinthemoose.com; Sat, 30 Dec 2017 17:35:36 -0600
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=5vbIrDJIejH6mw3v9SxaPTgipMM=; b=nzvb4wvWvKt1bA3k
	P+if5HiDUIJqvCH5Rk84IGEEdeLCWuWzxOVAW9vHOXkK3NMPJVBz5TLRKra+iDTF
	we0L+QyNfaWKvC/FZpCnu78BTewD8WxajG+PYBAxp/0bmcSgkXFTq5cqoPEEBK/y
	Qn2sqCwiBLec/WfGHDkxvSR6E9Q=
Received: by filter0531p1las1.sendgrid.net with SMTP id filter0531p1las1-21040-5A4822B2-1A
        2017-12-30 23:35:15.049461957 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0008p1iad1.sendgrid.net (SG) with ESMTP id zZ3vgXxiTBOKTDoMW2wsng
	for <david@spinthemoose.com>; Sat, 30 Dec 2017 23:35:14.963 +0000 (UTC)
Date: Sat, 30 Dec 2017 23:35:15 +0000 (UTC)

**Comment by davidalpert** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  spinthemoose@gmail.com
    Domain spinthemoose.com has exceeded the max emails per hour (200/200 (100%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext4.iad.github.net ([192.30.252.195]:36716 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by cp1164.blacksun.ca with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.89_1)
	(envelope-from <noreply@github.com>)
	id 1eVQf9-00008o-6F
	for david@spinthemoose.com; Sat, 30 Dec 2017 17:35:35 -0600
Date: Sat, 30 Dec 2017 15:35:14 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1514676914;
	bh=Y9GydtFsNIm7UHxO5oSmoQBPxtB/ASHgbfSYf4MRFPg=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=Iya3wgFqeba+AtMDqX/4vODFnufXQyxCH5juU5JvWr6stfMh5PCS7H70kQOSUCz4C
	 la5aKlUwLH4adA+JudqqTx+XsnjwwGgkXC/KYL9lzo2gc9ZLERupMXZinJAi0qBsAV
	 F+GTUU8dUXte3Jb5eljhz/oo10RMqDD0J3s/sLC0=
