### ISSUE TITLE
Application Insights custom dependency tracking disconnected from request

### ISSUE THREAD

**Issue by jcsharp** [aspnet/Home#1955]
I am tracking custom dependency calls with Application Insights in a web API built with ASP.NET Core (v1.1.1, .NET Framework 4.6 and using the WebListener host).

The problem is that the dependency trace does not appear related to the request when I browse the traces in the portal. Also, the request duration is smaller than the dependency duration. 

I don't see this problem with non-Core ASP.NET web APIs, so I suspect there is something wrong with the ASP.NET Core implementation...

The operation implementation does not contain any asynchronous calls.

Request trace:
```json
{
  "name": "Microsoft.ApplicationInsights.Dev.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.Request",
  "time": "2017-03-08T14:21:50.1802621Z",
  "iKey": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
  "tags": {
    "ai.internal.sdkVersion": "aspnet5f:2.0.0",
    "ai.application.ver": "1.0.0.0",
    "ai.internal.nodeName": "jcsurf3.cid.dom",
    "ai.operation.id": "80000023-0003-ff00-b63f-84710c7967bb",
    "ai.location.ip": "::1",
    "ai.cloud.roleInstance": "jcsurf3.cid.dom",
    "ai.operation.name": "GET Assure/Get [id]"
  },
  "data": {
    "baseType": "RequestData",
    "baseData": {
      "ver": 2,
      "id": "oNSnkVbILw0=",
      "name": "GET Assure/Get [id]",
      "duration": "00:00:00.0166757",
      "success": true,
      "responseCode": "200",
      "url": "http://localhost:5508/Assure/42",
      "properties": {
        "AspNetCoreEnvironment": "Development",
        "httpMethod": "GET",
        "DeveloperMode": "true"
      }
    }
  }
}
```

Dependency trace:
```json
{
  "name": "Microsoft.ApplicationInsights.Dev.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.RemoteDependency",
  "time": "2017-03-08T14:21:50.1323509Z",
  "iKey": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
  "tags": {
    "ai.internal.sdkVersion": "dotnet:2.2.0-54037",
    "ai.application.ver": "1.0.0.0",
    "ai.internal.nodeName": "jcsurf3.cid.dom",
    "ai.operation.id": "oNSnkVbILw0=",
    "ai.location.ip": "::1",
    "ai.cloud.roleInstance": "jcsurf3.cid.dom",
    "ai.operation.name": "GET Assure/Get [id]"
  },
  "data": {
    "baseType": "RemoteDependencyData",
    "baseData": {
      "ver": 2,
      "name": "FakeAssureRepo",
      "id": "B16EXLDPLWU=",
      "data": "Read",
      "duration": "00:00:00.0542780",
      "success": true,
      "properties": {
        "AspNetCoreEnvironment": "Development",
        "DeveloperMode": "true"
      }
    }
  }
}
```

**Comment by davidfowl** [comment]
What version of the SDK are you using?

**Comment by jcsharp** [comment]
My project references the package Microsoft.ApplicationInsights.AspNetCore version 2.0.0, which has dependencies on other application insights packages version 2.2.0.

**Comment by pakrym** [comment]
@jcsharp where do you track a dependency? Can you share a repro code?

**Comment by jcsharp** [comment]
Here's a repro:

```c#
    [HttpGet]
    [Authorize(policy: "Viewer")]
    public string Get()
    {
        bool result = true;
        var startTime = DateTimeOffset.Now;
        var stopwatch = System.Diagnostics.Stopwatch.StartNew();
        try
        {
            Task.Delay(100).Wait();
            return "Hello";
        }
        catch (Exception)
        {
            result = false;
            throw;
        }
        finally
        {
            stopwatch.Stop();
            var telemetry = new Microsoft.ApplicationInsights.TelemetryClient();
            telemetry.TrackDependency("Dependency", "Test", startTime, stopwatch.Elapsed, result);
        }
    }
```

And the traces:

![image](https://cloud.githubusercontent.com/assets/2773390/24365796/65b37efa-1317-11e7-8238-6275fd575044.png)

Note how the request duration is much shorter than the dependency call.

**Comment by pakrym** [comment]
Try injecting `TelemetryClient` into constructor instead of creating new: https://github.com/Microsoft/ApplicationInsights-aspnetcore/blob/develop/test/MVCFramework45.FunctionalTests/Controllers/HomeController.cs#L13

**Comment by jcsharp** [comment]
Better. When I inject the `TelemetryClient` in the controller, the "all telemetry for this operation" link shows both the request and the dependency traces together. 

However, I still see a much shorter duration on the request than for the dependency.

![image](https://cloud.githubusercontent.com/assets/2773390/24366924/04d1ba76-131b-11e7-82ff-72bd18bc8587.png)

**Comment by jcsharp** [comment]
If I look at the traces on the Azure portal, I still don't see the dependency call on the request:

![image](https://cloud.githubusercontent.com/assets/2773390/24367041/794ba3c6-131b-11e7-865b-2d51f6e63244.png)

**Comment by pakrym** [comment]
Looks like a bug, filed https://github.com/Microsoft/ApplicationInsights-aspnetcore/issues/370

**Comment by davidfowl** [comment]
@jcsharp Let's move the discussion there.
