### ISSUE TITLE
Feature request: Common interface for background tasks

### ISSUE THREAD

**Issue by nth-commit** [aspnet/Home#1956]
This is much needed in my opinion.

There are many ways to run background tasks in various infrastructures for various purposes. It would be ideal if our core app code needn't worry about which background task implementation we are using. It would be fantastic if there was Microsoft-owned code that consolidated this for everyone, like what is done with DI, Logging, Caching etc. It should support at least queueing jobs, and possibly running tasks intermittently.

My personal use-case: I love using Hangfire with the new 1.0 framework. However, I know as my system grows there are much better alternatives for a distributed architecture. I have used Web Jobs a bit before as well. Both of these have vastly different interfaces, for essentially the same purpose, and it's easy for that library-specific logic to become entangled in your app code.

I would propose something like this:
```
public interface IJobQueue 
{
    Task QueueJobAsync<TInjectable, TJobArguments>(
        Func<TInjectable, TJobArguments, Task> jobAction,
        TJobArguments jobArgs,
        TimeSpan? waitTime = null);
}
```
The job would be queued asynchronously. This would be adding the job to your database or pushing it to job storage. The job would be activated with your chosen DI container, and given action invoked with your service (TInjectable that is registered with your DI container) and job arguments. Hangfire handles this by serializing the job expressions, and the job arguments, then rehydrating and combining both when the job is triggered.

A usage of this could be:
```
IJobQueue _jobQueue;

public async Task ScheduleEmailAsync(EmailMessage email)
{
    _jobQueue.QueueJob<IEmailService>(
        (emailService, email) => emailService.SendEmailAsync(email),
        email);
}
```

This of course is just a base level of functionality. There are numerous features that could be supported.

**Comment by Tratcher** [comment]
@davidfowl weren't you playing around with something like this for Hosting recently?

**Comment by davidfowl** [comment]
Yes, I'm not sure we want an abstraction here though.

/cc @glennc

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
