### ISSUE TITLE
Unable to load api-ms-win-core-libraryloader-l1-1-0 on Windows Vista

### ISSUE THREAD

**Issue by RedQueen87** [aspnet/Home#1957]
Hi. I am using Entity Framework Core with SQLite provider and WPF desktop application.
And I have exception like this "Unable to load DLL 'api-ms-win-core-libraryloader-l1-1-0" on Windows Vista only. I know also this api-ms-win-core-libraryloader-l1-1-0 was known issue on beta7 version thats why I came here. But it was related to Linux system and in my case it is Windows Vista.
I have tryied to find this DLL in System32 direcotry, but it doesnt exist.
I am using .NET 4.5.2 which suppose to be compatible with Vista.
Microsoft.Data.Sqlite - v1.1.0
Microsoft.EntityFrameworkCore - v1.1.1
Microsoft.EntityFrameworkCore.Sqlite - v1.1.1
SQLite - v.3.13.0
So is any chance it will work on Vista?
Can you give me some advice, workaround or anything?
Maybe some windows update?

**Comment by natemcmaster** [comment]
.NET Core does not support Windows Vista. It requires Windows 7 or newer.

See https://docs.microsoft.com/en-us/dotnet/articles/core/windows-prerequisites for more details.
