### ISSUE TITLE
Quick Action to Install missing packages is missing

### ISSUE THREAD

**Issue by ChuckkNorris** [aspnet/Home#1959]
When using the `Quick Action` hotkey ( CTRL+. ) in ASP.NET Core 1.0 with the project.json file, an option would be provided to install the missing package automatically.

For example, using the quick action on the following:
`app.UseStaticPackages()` 

would provide an option to install `Microsoft.AspNetCore.StaticFiles` which saved me a significant amount of time.

How do I enable this functionality again?

Using Visual Studio 2017 with ASP.NET Core 1.1.1

**Comment by natemcmaster** [comment]
This is a known issue of VS 2017. https://github.com/aspnet/Tooling/blob/master/known-issues-vs2017.md#no-suggestions-to-install-missing-packages

Closing as we're already tracking this issue.

Also, FYI, this GitHub project is not reviewed by the Visual Studio team. I'd recommend using https://developercommunity.visualstudio.com

**Comment by ChuckkNorris** [comment]
The whole migration path to csproj has been nothing but headaches and disappointment. 
Getting rid of `project.json` really killed my excitement for .NET Core - feel free to pass that on to the team.
