### ISSUE TITLE
Roslyn Analyzers and ASP.NET 5 Projects in Visual Studio 2015 Preview

### ISSUE THREAD

**Issue by tugberkugurlu** [aspnet/Home#196]
When you install [Microsoft.CodeAnalysis.CSharp.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.CSharp.FxCopAnalyzers) into a regular console project, it runs the following install.ps1 script to add the analyzer references:

```
param($installPath, $toolsPath, $package, $project)

$analyzersPath = join-path $toolsPath "analyzers"

foreach ($analyzerFilePath in Get-ChildItem -Recurse $analyzersPath)
{
    $project.Object.AnalyzerReferences.Add($analyzerFilePath.FullName)
}
```

It looks like this:

![image](https://cloud.githubusercontent.com/assets/328122/5058888/9846a45c-6d0e-11e4-89b4-4e0f9735eb37.png)

However, this doesn't work with ASP.NET 5 projects.

> Also, I can assume that this is also integrated into the build process through custom msbuild scripts. That's why I'm not sure how this would look like in ASP.NET 5 projects as MSBuild is not the only build tool.

**Comment by Kieranties** [comment]
@davidfowl with this being closed, does that mean a fix is incoming?

**Comment by davidfowl** [comment]
There's already a bug tracking the work in the dnx

**Comment by Kieranties** [comment]
Ah, https://github.com/aspnet/dnx/issues/2145
