### ISSUE TITLE
VS 2017 RTM interferes with VS 2015 and .NET Core

### ISSUE THREAD

**Issue by dcparsons** [aspnet/Home#1964]
This is similar to [#454](https://github.com/aspnet/JavaScriptServices/issues/454)  Basically, I downloaded Visual Studio 2017 last week to evaluate it for use on our team, however the install of 2017 breaks Visual Studio 2015s ability to open/build a .NET Core application correctly.  I uninstalled Visual Studio 2017, attempted to reinstall the .NET Core SDK, VS2015 Tooling, and so forth but nothing seemed to work.  After installing / uninstalling 2017 I ran into 3 problems:

- On opening the project in 2015 I receive the message ... "No executable found matching command "dotnet-projectmodel-server""

- Trying to build results in the error: Microsoft.DotNet.props could not be found.   I found this file in an MSBuild directory that was different than the one that was noted in VS.  I copied the directory that contained the .DotNet.props file to the location Visual Studio was looking.

-  MSB4184 - The expression "Registry:HKEY_LOCAL_MACHINE\Software\Microsoft\VisualStudio\14.0\Setup\EDev@StanDir" cannot be evaluated.  [{{Path to xproj}}]	{{Project Name}}	C:\Program Files\dotnet\sdk\1.0.1\Microsoft\VisualStudio\v14.0\CodeAnalysis\Microsoft.CodeAnalysis.targets	25	

I have read through a number of articles on SO as well as issues here on GitHub and everything that I have tried hasn't fixed the issue.  Any thoughts?

**Comment by joeaudette** [comment]
Do you have a global.json file in the vs2015 solution to declare the sdk version?

**Comment by dcparsons** [comment]
@joeaudette Thank you for that.  No I did not.  For anyone else that may stumble across this:

The versions of .NET Core on your windows system are in C:\Program Files\dotnet\sdk.  In my case I have

- 1.0.0

- 1.0.0-preview2-003131

- 1.0.1

In my situation I needed to add the following to my global.json file

```
{
  "sdk": {
    "version": "1.0.0-preview2-003131"
  }
}
```

**Comment by Kritner** [comment]
I have a project structure similar to this:

```
trunk/someProj/...
trunk/solutions/someProj/someProj.sln
```

where should this global.json go?  I have it under `trunk/solutions/someProj/`, but i'm still getting numerous errors:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB4062	The "GetTransitiveNonDotNetProjectDependencies" task could not be loaded from the assembly C:\Program Files\dotnet\sdk\1.0.3\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Tasks.dll. Could not load file or assembly 'Microsoft.Build.Utilities.v4.0, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. [Redact] C:\Program Files\dotnet\sdk\1.0.3\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Common.Targets	330	
```

**Comment by dcparsons** [comment]
My global.json file is in the root of my project folder.

**Comment by Kritner** [comment]
@dcparsons yeah, I eventually got it building in VS2015 again, but it seems like i had to put that global.json specifying the version to use, in *every* project folder.  With a large code base like the one I'm working in that was a lot of folders.  I guess there's no "inheriting" from a parent folder global.json in that regard?  It did not seem to work for me anyway.
