### ISSUE TITLE
Custom tuple variable names are not specified in API response

### ISSUE THREAD

**Issue by ChuckkNorris** [aspnet/Home#1967]
**Version Used**: 
.NET Core 1.1.1

**Steps to Reproduce**:

1. Create HTTP Get method in Controller returning a Tuple
```
[HttpGet]
public (string firstName, string lastName) Get() {
   return ("Tom", "Hanks");
}
```

2. Call Endpoint and view Result
`{ item1: "Tom", item2: "Hanks" }`

**Expected Behavior**:
Should return a json object with the keys named according to what was specified in the method.
`{ firstName: "Tom", lastName: "Hanks" }`

**Actual Behavior**:
`{ item1: "Tom", item2: "Hanks" }`

**Comment by Tratcher** [comment]
@rynowak?

**Comment by rynowak** [comment]
This issue was moved to aspnet/Mvc#5990
