### ISSUE TITLE
Web Api Core hangs when start it on IIS Express in Visual Studio 2017?

### ISSUE THREAD

**Issue by Mds92** [aspnet/Home#1968]
I just updated Visual Studio to final version of 2017.
I'm working on a WebApi core project.

![VS2017-WebApi](https://i.stack.imgur.com/uP2XW.png)

Whenever I start it with IIS Express, Google Chrome comes up and stay on loading in the following page without any responses.

![VS2017-WebApi-Chrome](https://i.stack.imgur.com/mv8oJ.png)

I disabled JavaScript debugging in Visual Studio options, but nothing changed.
What's wrong with it?

`It works without IIS Express`

**Comment by natemcmaster** [comment]
This doesn't appear on the [known issues](https://github.com/aspnet/Tooling/blob/master/known-issues-vs2017.md) list. Can you report to https://developercommunity.visualstudio.com/ instead? This issue won't get visibility here as the VS team doesn't check this issue tracker.

**Comment by softlogicaco** [comment]
Me too I'm having same behaviour on a Web Site project.
I must kill IIS express and reinit VS

Please help

**Comment by Mds92** [comment]
Enabling IISExpress on WebApi Core:

1. Enabling the IISIntegration components:
Install **Microsoft.AspNetCore.Server.IISIntegration** package.

2. Edit Program.cs in root of project:
```
 var host = new WebHostBuilder()
    .UseKestrel()
    .UseContentRoot(Directory.GetCurrentDirectory())
    .UseIISIntegration() // Add this line
    .UseStartup<Startup>()
    .Build();
```
Reference: http://stackoverflow.com/questions/42758165/web-api-core-hangs-when-start-it-on-iis-express-in-visual-studio-2017
