### ISSUE TITLE
How to debug ASP.NET Core framework code using Visual Studio

### ISSUE THREAD

**Issue by Jon12345** [aspnet/Home#1972]
Currently there's an old blog post: https://blogs.msdn.microsoft.com/webdev/2015/02/06/debugging-asp-net-5-framework-code-using-visual-studio-2015/ and a stackoverflow answer:
http://stackoverflow.com/questions/38448924/how-can-i-debug-the-source-code-of-net-core-or-the-base-class-libraries-corefx

Both are out of date because there's no global.json file. 

It'd be great if:
1) There was an up-to-date guide which was maintained.
2) There was a Source Server like https://referencesource.microsoft.com/ so that you don't have to clone and build each time the framework version changes.

**Comment by stevejgordon** [comment]
I'm very keen to find an option for this too.

**Comment by B-Esmaili** [comment]
Any improvement on this?

**Comment by arthurborisow** [comment]
Any updates on this?

**Comment by Edward-Zhou** [comment]
Any updates?

**Comment by tarurar** [comment]
Still nobody knows how to debug framework sources?

**Comment by B-Esmaili** [comment]
i am able to debug framework source by grabbing corresponding source from github and compiling and replacing the dll and pdb file in package folder with the one i have build.

**Comment by tarurar** [comment]
Maybe it would be better to make visual studio use your compelled sourced? The question is - how to do it.

**Comment by dhatrifork** [comment]
nuget symbols packages are being built alongside ordinary nuget packages, but they are not published. It would be **really** nice if the ASP.NET team would publish these symbols to enable debugging of the official nuget packages. Other ASP.NET symbols are published and available on symbolsource, just not ASP.NET Core. Have a look at the list on https://www.symbolsource.org/Public/Metadata/NuGet.

See also #906 -- this is a really old request!

Why no symbols? 🙁

**Comment by epot** [comment]
Any update on this?? It is supposed to be the brand new framework everyone should use, and it looks like debugging is impossible. On my side I cannot compile the source if I clone the repo and am completely stuck...

**Comment by rykr** [comment]
I want to chime in here too.  Would be really nice to be able to debug into the sources.

**Comment by dhatrifork** [comment]
FWIW, you can still compile the 20 or so github repos yourself, change your VS nuget server to local, clear the nuget cache so your project will restore nuget packages from the new local source, and point your symbols source to local too. So it IS possible to debug, it's just very very cumbersome.

But you feel stupid doing all this, because **the symbols for the official nuget packages are built, they exist, they are just not published**. Come on, team asp.net core! Share your cake!

**Comment by epot** [comment]
I tried doing what you suggested but I end up with cryptic pdb symbols loading errors. As you said, as the work is already done, it is just a mystery why it cannot be simply shared...

**Comment by guodf** [comment]
Please publish the symbols for asp.net core 2.0

**Comment by jabbera** [comment]
this is crazy town.

**Comment by davidfowl** [comment]
They were published a while ago. See https://www.stevejgordon.co.uk/debugging-asp-net-core-2-source

**Comment by febrynas** [comment]
How about debugging asp core & ef core by using vs code in mac?

I hope there is a good article for this
