### ISSUE TITLE
How to migrate customer htmlhelper from mvc 5 to asp net core

### ISSUE THREAD

**Issue by spaceman27** [aspnet/Home#1977]
I have a custom htmlhelper that sharing in 5 internal system and I am working a new internal system that must reuse the menu and footer site
I am searching for a ability if I can use .net core and reuse that code to keep consistent to other sites.
Is there any way to import / DI old library to render HTML for that?

**Comment by davidfowl** [comment]
You can't share the exact type you need to copy it.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
