### ISSUE TITLE
WebDeploy (Package) from Visual Studio 2015 doesn't generate correct website name, setparameters.xml and deploy.cmd files

### ISSUE THREAD

**Issue by MistyKuu** [aspnet/Home#1980]
I'm trying to publish my ASP.NET Core app (on top of .NET framework) into a .zip file.

Test.pubxml

```
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <WebPublishMethod>Package</WebPublishMethod>
    <LastUsedBuildConfiguration>Release</LastUsedBuildConfiguration>
    <LastUsedPlatform>Any CPU</LastUsedPlatform>
    <SiteUrlToLaunchAfterPublish />
    <LaunchSiteAfterPublish>True</LaunchSiteAfterPublish>
    <ExcludeApp_Data>False</ExcludeApp_Data>
    <PublishFramework>net452</PublishFramework>
    <UsePowerShell>True</UsePowerShell>
    <DesktopBuildPackageLocation>Test.zip</DesktopBuildPackageLocation>
    <PackageAsSingleFile>true</PackageAsSingleFile>
    <DeployIisAppPath>TestSite/TestApp</DeployIisAppPath>
  </PropertyGroup>
</Project>
```

When I use this profile to publish into a .zip file package I get the one directory and two files:
Content/website
archive.xml
systeminfo.xml

From what I read about webdeploy so far there are two unexpected things:

Where is *.deploy.cmd file?
Why my website is called 'website' instead of 'TestSite/TestApp'?
The repro is to create ASP.NET Web Api Net Core (.NET Framework) app from template and use this profile to publish.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
