### ISSUE TITLE
RunProxy Uses Default Timeout

### ISSUE THREAD

**Issue by AceCoderLaura** [aspnet/Home#1981]
When using a proxy to redirect calls from ASP to my WCF service, timeouts occur. I suspect that the proxy's HttpClient is using the default request timeout. There needs to be a way to set the timeout.

```
app.MapWhen(c => IsWCFCall(c), builder =>
{
    builder.RunProxy(new ProxyOptions { Scheme = "http", Host = "localhost", Port = XivicConfiguration.WCFPort.ToString() });
});
```

Apologies if this is the wrong repository.

**Comment by Tratcher** [comment]
This issue was moved to aspnet/Proxy#58
