### ISSUE TITLE
Data accessing logic in models?

### ISSUE THREAD

**Issue by rykr** [aspnet/Home#1984]
This is more of a question so feel free to bounce it somewhere more appropriate.  Just wondering if there is a good tutorial on best practices of writing data access code in models.   It doesn't seem right to DI my db context into all of my models but I would love to move alot of my linq queries into my models to fetech related data.  A lot of this code is needed in several places and I don't see the point of duplicating it in several controllers.

Thanks!

**Comment by stevejgordon** [comment]
@rykr - Perhaps my blog post will help? https://www.stevejgordon.co.uk/cqrs-using-mediatr-asp-net-core -  I use MediatR to separate data access into small reusable components.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
