### ISSUE TITLE
aspnetcore web.config requestTimeout Parameter Causes 500 error if minutes set to 60

### ISSUE THREAD

**Issue by crupak** [aspnet/Home#1986]
in Web.config, under the <system.webServer> tag, the requestTimeout attribute of the aspNetCore tag causes a server 500 error if the requestTimeout parameter is specified as 00:60:00 (i.e. 1 hour).  Note that specifying the parameter as 01:00:00 works correctly.

I realize this certainly is not high priority but it tripped me up by causing the evil server 500 fault in our server 2016 production server.  So, I've provided it here for reference purposes.

**Comment by Tratcher** [comment]
This issue was moved to aspnet/AspNetCoreModule#86
