### ISSUE TITLE
how to override controller name

### ISSUE THREAD

**Issue by QJesus** [aspnet/Home#1989]
[this article](https://docs.microsoft.com/en-us/aspnet/web-api/overview/web-api-routing-and-actions/routing-in-aspnet-web-api) shows how to override action name  

> You can override the action name by using the ActionName attribute.

but I didn't find any way to override the controller name.
please.

**Comment by scottsauber** [comment]
@QJesus  -Is this what you mean?

// Want the route to be /something but the controller to be name PublicController
[Route("something")]
public class PublicController : Controller

**Comment by QJesus** [comment]
NO. I want an attribute like that [override-controller-name-in-asp-net-core](http://stackoverflow.com/questions/42351575/override-controller-name-in-asp-net-core)  
will it be in the framework?

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
