### ISSUE TITLE
Problem installing from Homebrew on Mac

### ISSUE THREAD

**Issue by csterwa** [aspnet/Home#199]
I get the following error when installing kvm via Homebrew:

==> Installing kvm from aspnet/homebrew-k
==> Cloning https://github.com/aspnet/Home.git
Error: Failed to download resource "kvm"
Failure while executing: git clone --depth 1 --branch master https://github.com/aspnet/Home.git /Library/Caches/Homebrew/kvm--git

**Comment by danroth27** [comment]
@csterwa Let us know if you are seeing issues with the latest formula

**Comment by csterwa** [comment]
Seems to be working last few times I've done an update. Thanks!
