### ISSUE TITLE
Http client to call Soap service over https

### ISSUE THREAD

**Issue by AndreiFuse** [aspnet/Home#1990]
I'm trying to access existing SOAP webservice using `HttpClient`. Works fine on Windows 10, but fails in Linux Mint with `TaskCanceledException: A task was canceled.`, which masks a timeout. Is there a way to run it on Linux?

```
    [HttpGet("test")]
    public IActionResult Login()
    {
      HttpClientHandler clientHandler = new HttpClientHandler();
      clientHandler.ServerCertificateCustomValidationCallback = (message, cert, chain, errors) => { return true; };
      HttpClient client = new HttpClient(clientHandler);
      HttpRequestMessage request = CreateSoapWebRequest();
      HttpResponseMessage response = client.SendAsync(request).Result;
    }

    public HttpRequestMessage CreateSoapWebRequest()
    {
      string xmlString = String.Format(<my xml here>);
      HttpRequestMessage result = new HttpRequestMessage(new HttpMethod("POST"), myUrl);
      result.Content = new StringContent(xmlString, Encoding.UTF8, "text/xml");
      result.Headers.Add("SOAPAction","http://tempuri.org/IAuthorizationService/AuthorizeUser");
      return result;
    }
```

**Comment by Mike3010** [comment]
Some additional information to this problem (we work together)...

The request works fine with http and also with https when there are valid certificates.

To problem occurs when we are testing in our DEV environment with no valid https certificate available. 
The request seems to time out. Just before the `TaskCanceledException: A task was canceled` gets thrown the `ServerCertificateCustomValidationCallback` gets called (takes about 2 minutes). Returning true/false doesn't seem to make a difference, I think it's too late at this point. Shouldn't this callback be called in the very beginning?

Would appreciate everything that helps.

**Comment by Tratcher** [comment]
As this seems like an HttpClient issue, you'd be better off moving it to https://github.com/dotnet/corefx.
