### ISSUE TITLE
Is .Net Framework 4.5.1 required .Net Core Windows Hosting by force?

### ISSUE THREAD

**Issue by joeloff** [aspnet/Home#1991]
_From @tloo on March 8, 2017 21:8_

Is .Net Framework 4.5.1 required .Net Core Windows Hosting by force?

## Steps to reproduce
On Windows Server 2008, we have .Net Framework 4.5.5 installed.

## Expected  behavior
.Net Core Windows Hosting should be installed correctly.

## Actual behavior
![image](https://cloud.githubusercontent.com/assets/375419/23723943/0626ab68-0419-11e7-9999-7849ac8078e1.png)
The logs
[dd_DotNetCoreWinSvrHosting__20170308155829.log.txt](https://github.com/dotnet/core-setup/files/828962/dd_DotNetCoreWinSvrHosting__20170308155829.log.txt)

## Environment data

_Copied from original issue: dotnet/core-setup#1673_

**Comment by joeloff** [comment]
_From @gkhanna79 on March 8, 2017 21:53_

@glennc @DamianEdwards Can you please loop in the right folks? Also, is there a more appropriate repo to move this issue to?

CC @leecow

**Comment by joeloff** [comment]
_From @gkhanna79 on March 30, 2017 2:15_

@DamianEdwards Can you help move this to appropriate repo and assign to right folks?

**Comment by joeloff** [comment]
_From @glennc on April 10, 2017 16:9_

I think @joeloff is the right person for this, and can move it to where it should belong.

**Comment by joeloff** [comment]
Yup, you can assign to me. The requirement though is a minimum version

@tloo Can you share your setup logs? We specifically look at HKLM\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full and examine the Release value.

**Comment by joeloff** [comment]
_From @gkhanna79 on April 10, 2017 17:5_

@joeloff Is not on the assigned to list - @joeloff Can you please move this bug to appropriate repo?

**Comment by tloo** [comment]
@joeloff I have shared the setup logs. Please check the attachment.

**Comment by joeloff** [comment]
According to the logs, the version we detected is 378389, and the minimum version we're looking for is 378675.

[380C:6CD8][2017-03-08T15:58:29]i000: Setting string variable 'NetFx45Release' to value '378389'

378389 is .NET 4.5

You can find the full set of version numbers [here](https://msdn.microsoft.com/en-us/library/hh925568(v=vs.110).aspx)

**Comment by tloo** [comment]
So .Net 4.5 is required by force? I have another setup Windows Server 2008 which doesn't have .Net 4.5 installed. But it seems .Net Core runtime can be installed correctly.  We just just want to figure out the prerequisites for .Net Core runtime.

**Comment by joeloff** [comment]
@tloo The 4.5 requirement seems to be a leftover from when we shipped DNX and was probably never reviewed again. The only other component we have in the server bundle right now is the ASP.NET Core Module and that also doesn't require 4.5 AFAIK.

For now, the only way around is to either install .NET 4.5.1 or to temporarily change the value of the registry key to bypass the check.

**Comment by tloo** [comment]
@joeloff Changing the registry key might not be a good solution for us. Because we are planning to package .Net Core runtime in our installer and deploy on the customer's setup.  And installing .Net 4.5.1 might not be a good solution either. because it will increase our installer package size.
In fact, we have two Window Server 2008 setup, one is asking for .Net Framework 4.5, the other one doesn't.  I'm pretty sure that 378675 was not installed on both of them. So I'm thinking it should be a bug.

**Comment by joeloff** [comment]
@tloo Yes, the check should be removed, but until that happens and we ship a new bundle you're limited in what you can do to install the server bundle. Are you planning on packaging just .NET Core runtime or the server bundle (which contains the .NET Core runtime and ANCM)?

**Comment by tloo** [comment]
@joeloff The server bundle, this is the suggestion from the documentation:
https://docs.microsoft.com/en-us/aspnet/core/publishing/iis#deploy-the-application

**Comment by tloo** [comment]
@joeloff Any updates on this?

**Comment by joeloff** [comment]
@tloo This will get fixed for the preview2 version of the bundle.

**Comment by ChouhanSandeep** [comment]
I am getting same error while installing Windows (Server Hosting)(NET Core 1.0.5) installer  downloaded from 
https://github.com/dotnet/core/blob/master/release-notes/download-archives/1.1.2-download.md

![capture](https://user-images.githubusercontent.com/29221232/30853788-62103e64-a2cd-11e7-8374-67d3977ee832.JPG)

@joeloff : Could you please guide what is preview 2 version, will there be a new bundle for DotNetCore.1.0.5_1.1.2-WindowsHosting or will this issue get fixed only in Version 2.0.

**Comment by ChouhanSandeep** [comment]
@joeloff Any update on this? Is there any separate/new thread?

**Comment by joeloff** [comment]
@ChouhanSandeep This was fixed in Preview 2 of the 2.0 bundle.
