### ISSUE TITLE
Is there an intent for 3rd party tooling integration into .csproj after `scripts` section is gone?

### ISSUE THREAD

**Issue by peterblazejewicz** [aspnet/Home#1992]
With the migration from `project.json` to `.csproj` file completed the features offered by `scripts` section are nearly completely gone from Core platfrom.

I really miss a way to hook into `dotnet` build process. I could not hook a tool like `NPM` or `Yarn` into restore command, build, etc. Instead I need to know `MSBuild` internals with very non-idiomatic terms:
https://github.com/aspnet/JavaScriptServices/blob/dev/templates/VueSpa/VueSpa.csproj#L18-L22
and I'm forced to use the only tool that integrates nicely with `build` command:
https://docs.microsoft.com/en-us/aspnet/core/client-side/bundling-and-minification
but is not very configurable (I cannot plug into an external command when using bundler)

Is there an intent to provide back similar feature in near feature or should I make a deep dive into MSBuild internals

Thanks!

**Comment by natemcmaster** [comment]
MSBuild target chaining is the way to hook into `dotnet` build process. Here are some well-known targets you can chain off to insert your target into the build:

- Build
- Publish
- Clean
- Rebuild
- Pack
- CoreCompile 

Example:
```xml
<Target Name="RunNpm" BeforeTargets="Build">
<!-- ... -->
```

The target that remains most difficult to chain into is Restore. The "Restore" target is not executed in the project if the restore call started on a different project or a solution file. See https://github.com/NuGet/Home/issues/4928 and https://github.com/NuGet/Home/issues/4781. cc @emgarten 

Hunting through MSBuild internals is not ideal, but it's the best solution available at the moment. Personally, I use https://github.com/KirillOsenkov/MSBuildStructuredLog to visualize target chaining. Hopefully this helps you, too.

I'm going to close this issue for now, though feel free to continue discussion. If you have more questions about MSBuild target chaining, https://github.com/Microsoft/msbuild and https://github.com/dotnet/sdk are the better place to open issues.
