### ISSUE TITLE
Microsoft Webpage Oauth Library

### ISSUE THREAD

**Issue by arinray73** [aspnet/Home#1993]
I found a new version of this in myget. Desperately looking for an updated version of this since the version in Nuget was last updated in 2015 and it does not support Facebook API change,

Found a version in myget which I hope possibly takes care of the change but it gives installation error. Myget asked me to raise an issue here to contact the owner.

https://dotnet.myget.org/feed/aspnetwebstack-dev/package/nuget/Microsoft.AspNet.WebPages.OAuth

**Comment by Tratcher** [comment]
@NTaylorMullen @Eilon

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
