### ISSUE TITLE
Support modules

### ISSUE THREAD

**Issue by robertsundstrom** [aspnet/Home#1995]
Make it possible to create modules that can be integrated into web apps directly as projects and distributed as NuGet packages - like in OrchardCore.

**Comment by Tratcher** [comment]
@danroth27 @sebastienros

**Comment by danroth27** [comment]
Any particular reason to not just use what Orchard Core already offers? In general we want to support .NET community efforts rather than try to supersede them.

**Comment by robertsundstrom** [comment]
@danroth27 I just thought it seemed like a feature that should be supported by the framework (and tooling) itself, rather than having to depend on a third-party component. It would fullfill a common scenario. 

I do of course understand your concerns with the community, but maybe you should consider adopting Orchard's module middleware into the framework proper and make sure its extendible for third-parties. (which I already think it is)

**Comment by danroth27** [comment]
In the case of modularity I think we'd prefer to see the community work out what model they want. If we ship something in the framework we risk superseding that effort.

For tooling support I expect Orchard Core will provide templates and related tooling through the new [.NET Core Templating Engine](https://github.com/dotnet/templating), which we are integrating with VS.
