### ISSUE TITLE
increasing sqlhelper command timeout

### ISSUE THREAD

**Issue by devk80** [aspnet/Home#1996]
How to increase SqlHelper command timeout in c#. I am executing a SqlHelper.ExecuteNonQuery but it gives timeout error for large data. I want to increase the command timeout for this command.

**Comment by natemcmaster** [comment]
@devk80 are you using a third-party library? SqlHelper.ExecuteNonQuery is not an API provided by ASP.NET (I looked in https://docs.microsoft.com/en-us/dotnet/api/?term=SqlHelper and https://docs.microsoft.com/en-us/aspnet/core/api/)

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
