### ISSUE TITLE
Can't reference classes in other projects from .NET Core web app

### ISSUE THREAD

**Issue by Avalaxy** [aspnet/Home#2000]
I created a .NET Core web app and I'm trying to reference a .NET Core class library. Both are .NETCoreApp 1.1. For some reason, after I added this reference, I can't use any of the classes/namespaces of the library in my web app. Neither VS nor ReSharper recognizes the namespace, and build errors are being thrown.

This is what my web app looks like:

```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp1.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="wwwroot\" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.0.0" />
    <PackageReference Include="Microsoft.AspNetCore" Version="1.1.1" />
    <PackageReference Include="WindowsAzure.Storage" Version="8.1.1" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Commands\Commands.csproj" />
  </ItemGroup>

</Project>
```

And this is my class library:

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp1.1</TargetFramework>
  </PropertyGroup>

</Project>

```

**Comment by davidfowl** [comment]
> Neither VS nor ReSharper recognizes the namespace, and build errors are being thrown.

2 questions:

- Did you turn off nuget auto restore?
- Are you sure it isn't a resharper issue?

**Comment by Avalaxy** [comment]
@davidfowl agh, you are right, it turned out to be a ReSharper issue. I suspended ReSharper and now it works. I thought it wouldn't be a ReSharper issue because it also failed when I was doing a build/rebuild (I though that that was just plain VS doing the work).
