### ISSUE TITLE
Can't publish .net Core Console app - referencing Shared Project with conditional build symbols

### ISSUE THREAD

**Issue by Pinox** [aspnet/Home#2001]
Having problems publishing a .net core console app where I simply reference a Shared project using a conditional build symbol.  

In shared project I have the following reference that gives me an error.

#if (!CORE_APP)
      using SQLite.Net.Attributes;
#endif

This is my dotnet publish  error: "The type or namespace name 'SQLite' could not be found (are you missing a using directive or an assembly reference?)"

The above runs perfectly in VS2017 build I can't seem to publish the app. It picks up the reference that it shouldn't

Sample hello app that replicates error:
https://drive.google.com/open?id=0B0Gm-m-z_U84U1Z5XzFValNjaFU

Any suggestions would be appreciated.

**Comment by davidfowl** [comment]
This should be moved to dotnet/sdk

**Comment by Pinox** [comment]
Thanks, I created a ticket in dotnet/sdk
