### ISSUE TITLE
Microsoft ASP.NET 5 RC1 Update 1 - Uninstallation Failed

### ISSUE THREAD

**Issue by jozefizso** [aspnet/Home#2002]
I cannot uninstall Microsoft ASP.NET 5 RC1 Update 1 (1.0.11125.0 - most probably installed by Azure SDK 2.8).

Installation fails with error "0x80070001 - Incorrect function"

![image](https://cloud.githubusercontent.com/assets/287778/25044465/150d66dc-2127-11e7-91ac-e2b61b5d5eca.png)

Full installation log: 
https://gist.github.com/jozefizso/4d5d23a39ff5da9c4ea9134cc9091e2a

**Comment by natemcmaster** [comment]
Possible duplicate. See https://github.com/aspnet/Home/issues/1449#issuecomment-219578445

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
