### ISSUE TITLE
ASP.Net to be like Cordova, Ionic2, ReactXP

### ISSUE THREAD

**Issue by reader-man** [aspnet/Home#2003]
Hi,
 Thanks on the great ASP.Net Core product.

Currently there is no immediate desktop framework/technology on top of .Net Core, to be used in all OSes that .net Core support, so it would be great if there is a technology that is built on top of ASP.Net Core, to be used like Cordova/PhoneGap or ReactXP or Ionic2, so it will make the ASP.Net Core web app, behave as if its a native app, and benefit from the cross platform behavior of ASP.Net and its huge performance compared to other old techs.

and this will help in creating a new cross platform, shareable code base tech, with great native performance.

Regards.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
