### ISSUE TITLE
VS2017 - New WebAPI Controller Scaffolder Issue

### ISSUE THREAD

**Issue by ArcadeRenegade** [aspnet/Home#2004]
Hi,

My ASP.NET Core project is a WebAPI service so I do not have static files, views, css, or javascript.

When I make a new WebAPI controller using the scaffolder it generates unnecessary files every time including:

- Views/Shared
- Content
- Script
- ScaffolderReadMe.txt

Could these please be disabled? It is frustrating to have to manually remove these created files and folders every time I create a new WebAPI controller.

Thanks.

**Comment by ogarvey** [comment]
You should have a choice: 
![2017-05-04_12h36_35](https://cloud.githubusercontent.com/assets/994386/25701896/564ccc38-30c6-11e7-85c5-74819f810340.png)

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
