### ISSUE TITLE
ContentRoot is not correct on OSX

### ISSUE THREAD

**Issue by tidusjar** [aspnet/Home#2005]
Not sure where this belongs so please feel free to close and point me in the right direction.

So I have the following in Program.cs:

```
            Console.Title = "Ombi";
            var host = new WebHostBuilder()
                .UseKestrel()
                .UseContentRoot(Directory.GetCurrentDirectory())
                .UseIISIntegration()
                .UseStartup<Startup>()
                .Build();

            host.Run();
```

Now when publishing an osx runtime, when running I get an exception thrown because it cannot find the `appsettings.json` at `/users/TidusJar/`.

Now the application is not being run from inside `/users/TidusJar/` so I don't understand why it's trying to find the file in that directory.

Here is the startup.cs just for completion:
```
 public Startup(IHostingEnvironment env)
        {
            var builder = new ConfigurationBuilder()
                .SetBasePath(env.ContentRootPath)
                .AddJsonFile("appsettings.json", false, true)
                .AddJsonFile($"appsettings.{env.EnvironmentName}.json", true)
                .AddEnvironmentVariables();
            Configuration = builder.Build();

        }
```

**dotnet --info**
```
.NET Command Line Tools (1.0.1)

Product Information:
 Version:            1.0.1
 Commit SHA-1 hash:  005db40cd1

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.1
```

**Comment by natemcmaster** [comment]
@tidusjar `Directory.GetCurrentDirectory()` is determined by the location of your console. It should match the output of `pwd`. Are you running dotnet like this: `dotnet ~/some/path/to/MyApp.dll`?

**Comment by tidusjar** [comment]
I just ran the file that was outputted from the Published folder (after dotnet publish).  
So it was ran from /users/TidusJar/downloads/publish

The build is on AppVeyor and it's open source if you want me to link you to it. 

I just don't understand what is going on here.

**Comment by natemcmaster** [comment]
Can you share a minimal repro _with exact steps_ to cause the issue? It's hard to tell what is going on here from what you have described.

**Comment by tidusjar** [comment]
I can, i'll have to do it later tonight.

**Comment by tidusjar** [comment]
Sorry for the late reply. I cannot seem to reproduce this with a bare bones application... I still cannot figure out why it is happening for my app though

**Comment by tidusjar** [comment]
Update, after updating all the nuget packages to the latest including `Microsoft.AspNetCore` I can now reproduce it using a File>New project

Here is the repository:
https://github.com/tidusjar/DotNetPublishOSX

**Comment by natemcmaster** [comment]
In the screenshot, your current working directory is `~` aka /Users/TidusJar. This means Directory.GetCurrentDirectory() is not pointing to the folder that contains appsettings.json

Try this.
```
cd ~/Desktop/publish2/
./DotNetPublishOSXTest
```

**Comment by tidusjar** [comment]
Interesting, that now works.

Strange that before upgrading the `Microsoft.AspNetCore` package it was working fine.

The issue is now that it tells me it's running on port `5000` but I get 404 errors when navigating to it, that's possibly something else.

Thanks.
