### ISSUE TITLE
Can't automatically update a nuget package within .core app(VS 2015)

### ISSUE THREAD

**Issue by SergeyAlexeev** [aspnet/Home#2006]
I'm developing a project template based on standard .core StarterWeb app template. My project contains some additional nuget packages. I'd like to update these packages automatically. Well, I've created a custom project context menu item. Click on this item should update the related package. 

At first, I've tried to update it using the `IVsPackageInstaller.InstallPackage` method. Unfortunately, this approach hasn't been helpful.

Next, I've decided to update a package version within the `project.json` file manually. I've read the file and replaced the version like below:

    {
        "dependencies": {
            "my-package": "xx.xxx"
        }
        ....
    }

The expected behavior is "my-package" should be restored automatically after changing the `project.json` file. But it isn't. Instead, I have to restore packages by clicking on the 'Restore packages' context menu item.

Well, is there any way to achieve the behavior I described?

_Some additional details about my env:_

Microsoft Visual Studio Professional 2015
Version 14.0.25422.01 Update 3

dotnet --version -> 1.0.0-preview2-003131

**Comment by natemcmaster** [comment]
https://github.com/NuGet/Home is the better place to open this issue. :)

**Comment by SergeyAlexeev** [comment]
Thanks, I've moved it to https://github.com/NuGet/Home/issues/5098
