### ISSUE TITLE
Shared Hosting classic .NET and ASP.NET Core

### ISSUE THREAD

**Issue by llooz** [aspnet/Home#2008]
Is it possible to host an asp.net core project using a classic shared hosting that offers .net 4.5/4.6?
This without having the provider to install the AspNetCoreModule

**Comment by Tratcher** [comment]
No, there's no supported way to host ASP.NET Core in an IIS shared hoster without AspNetCoreModule.

**Comment by llooz** [comment]
If i want to the develop a rest api what are my options? 
I wanted to use the new asp.net mvc architecture. Is there no way to attach it on an owin katana pipeline?

**Comment by Tratcher** [comment]
ASP.NET WebApi is the recommended solution for those environments:
https://docs.microsoft.com/en-us/aspnet/web-api/overview/getting-started-with-aspnet-web-api/tutorial-your-first-web-api

**Comment by llooz** [comment]
I've used web api in the past but i wanted to develop on a macbook with vs code.
Is there no way to attach asp.net core mvc on an owin (katana) pipeline?
This way i can split and have a project host based on kestrel for developing and another one based on owin/katana to use only on a windows builder machine
Alternatively i was thinking to abstract all the controllers logic inside a library project and then have wrapper projects based on asp.net web api 2 and asp.net mvc but maybe it's an overkill

**Comment by davidfowl** [comment]
> Is there no way to attach asp.net core mvc on an owin (katana) pipeline?

With enough will you can do anything but we have no first class support in our stack. That's pretty far off the happy path.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
