### ISSUE TITLE
WinPE support

### ISSUE THREAD

**Issue by madhav5589** [aspnet/Home#2009]
Hello,

I have an windows application running on .NET 4.5.1 version. I am planning to migrate APIs to .NET core. Wonder if .NET core has any plan to support WinPE (Windows Pre-installed Environment) platform. I looked at the potential road map section but couldn't find anything specific to WInPE platform support.

Thanks.

**Comment by natemcmaster** [comment]
ASP.NET Core should run wherever .NET Core runs.

Closing in favor of keeping this conversation in your original issue: https://github.com/dotnet/core/issues/571.
