### ISSUE TITLE
IOptions<T> vs T for default injection

### ISSUE THREAD

**Issue by rhwilburn** [aspnet/Home#2010]
It strikes me that it is not always sensible to inject ` IOptions<T>`

 where as a consumer of Asp.net core I really intend T to be injected most of the time. This leads me to be unwrapping the IOptions instance to get intended type.

Example:

```
public class HomeController : Controller  
{
    private MySettings _settings;
    public HomeController(IOptions<MySettings> settings)
    {
        _settings = settings.Value
    }
}
```

Could become:

```
public class HomeController : Controller  
{
    private MySettings _settings;
    public HomeController(MySettings settings)
    {
        _settings = settings;
    }
}
```
Im sure that sometimes injecting all options makes sense sometimes, but most of the time the user probably is just interested in specific options. Honoring an injectable T into a controller constructor for example would make unit testing easier too and dependencies are more obvious.

Is this something that the community would be on-board me making a change set for? I have code that works for me in my local which is additive to the framework as a work around, but that code is additional to the default behavior of the framework and feels like it should/could be part of the framework.

I am interested in hearing pros and cons on this idea in the comments below. I imagine there were design considerations behind IOptions that I am not considering here with this suggestion?

**Comment by natemcmaster** [comment]
If you have problems with IOptions<T>, I recommend opening an issue on https://github.com/aspnet/options with the specific changes you need.

Here are some of the goals of the Options pattern to consider before you request framework changes. https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration#options-config-objects

**Comment by rhwilburn** [comment]
Thanks for the feedback, I am moving to here: https://github.com/aspnet/Options/issues/186 and closing this one out.

**Comment by Patrickkk** [comment]
What design goal required the IOptions interface? Why couldn't this be done with simple POCO's?

**Comment by davidfowl** [comment]
The main thing that breaks when injecting `T` vs `IOptions<T>` is the fact that there's an open generic added to the hosting container for `IOptions<T>`, so if your component depends on any `IOptions<T>`, nothing has to be registered or configured by default.

It means my component can consume `IOptions<Foo>` without having an add `Foo` to the container.

**Comment by rhwilburn** [comment]
Thanks for the explanation David but why not add both? You can have IOptions<Foo> added implicitly as stated, but also add Foo implicitly also because it would be registered explicitly by the user as something to bind to a section of the config.

The advantage of doing both would be supporting the typical user (who would want to directly use Foo) and also supporting the modular consumer user with IOptions<>. As an end user IOptions<Foo> seemed bizzare to me as I would never want it. Its not like I as a consumer would ever iterate through IOptions because I can create a hierarchical structure that makes sense to me. 

It feels like there are two use cases here with different ideal expectations. Even though my solution can be implemented by end users (by creating their own bindings); I think simplicity is key. What simplicity is however is debatable and perhaps my suggestion complicates things; but maybe it simplifies things to those who need the simplicity (ie joe blow end user as opposed to favoring module writers). I would argue they have an important use case but primarily users would be consumers, rather than module writers. (Note: Im not advocating to ignore module writers or their use case. I believe both can be obtained).

**Comment by davidfowl** [comment]
@rhwilburn `IOptions<T>` is added as an open generic, that's the advantage you can't add all objects. Also, adding each options means any component depending on an option now requires services. There's nothing preventing you from adding T to the container and taking it in your service but it can't be required by all components.

**Comment by davidfowl** [comment]
@rhwilburn Lets talk about what it means to add `T` as well as `IOptions<T>`:

- What happens if you add T to the container? It will override and your thing wouldn't work.
- Should it be opt in? Should there be a new overload of `ConfigureOptions`?

/cc @HaoK

**Comment by HaoK** [comment]
@rhwilburn is the issue that you still want to use `services.Configure<TOptions>` or some other options related functionality?

Because if MySettings is something that's only in your app, you can already configure it/inject it/consume it however you like...

**Comment by rhwilburn** [comment]
This is the line of code I must add to get what I want (I use Autofac for my DI):

`builder.Register(ctx => ctx.Resolve<IOptions<MySettings>>().Value);`

While that is fine that I add that, I have already expressed interest in my type here:

`services.Configure<MySettings>(Configuration.GetSection("MySettings"));`

As an end user of config bindings (where MySettings is bound to parts of the appsettings.json), it would be nicer if (and more convention based if), I could reference MySettings as opposed to IOptions<MySettings> for injection. The reason being that:

1. It leads to more readable code (in my opinion).
2. It makes unit testing better (in my opinion) because I don't need to reference ASP.net abstractions when I have no interest in them. It also tightens contracts rather than having a loose contract of IOptions<T>. 
3. It reduces the amount of code as opposed to unboxing MySettings each time I want to use it.
4. If i have a nested structure of complex structure, I can root that back to a single class for my app. It is true that other modules might have other options, but my code is not likely extending that; perhaps this is an example: if I was using Application Insights and using parts of appsettings.json it is highly unlikely that I want to look up application insights stuff. If I did, then I could resort to IOptions<ApplicationInsightsFoo> which is fine.

@HaoK You are correct, in that I can do what I want already, but what I am arguing is that for most users the possibilities with IOptions are non obvious are less preferable to keeping things simpler by default (ie defaultly hide but don't restrict the power of the framework). It felt really wrong to me that I must reference ASP.net extension libs to do unit testing on methods are that are so close to POCO (but because of IOptions are not quite there). I can live with things as they are, but I really think its non optimal forcing abstractions to the end user when they won't want them most of the time. Im equally not advocating getting rid of IOptions<> either, clearly there are usecases; I just believe both can be supported to ease learning of the framework (ie adding more value).

@davidfowl If you add T to the container, I can't see why it can't co-exist with IOptions<T> because T would point to IOptions<T>.Value and IOptions<T> would point to IOptions<T>. As for the second point, I believe it should be enabled by default to provide T and IOptions<T>. If its not on by default, then I think the value becomes highly questionable because its discovery would be harder/less-likely than coming to grips with using IOptions<>. I believe it should be opt out, to support the rare use case (but a possible one) that T creation should be controlled (to support use-cases perhaps like dynamic proxies or self managed class lifecycles (ie factories)). 

I hope that makes sense as to what I am suggesting.

**Comment by HaoK** [comment]
So this almost seems like a case of the sugar being too good, at the end of the day the options pattern is all about `IConfigureOptions` which is what `services.Configure` is adding underneath the covers and what `IOptions` depends on.  Also somewhat related, in 2.0 there's new additional concepts like named options and cache invalidation of options via `IOptionsSnapshot`/`IOptionsCache` that all build on top `Configure` overloads.  So I think just by using `services.Configure`, that's opting into also using/understanding the `IOptions[Snapshot]`.

At the end of the day, if they don't like the abstraction/don't find any benefit, they can just stop using `Configure` and register their settings directly 'services.AddSingleton(new MySettings())`

While we could add a new overload i.e. `services.Register<MySettings>(o => { })` which could do both the configure + add, this would still differ from the normal options usage where `Register` would be required unlike `IOptions` which does not require Configure to be called to work.
