### ISSUE TITLE
launchBrowser is not respected after dotnet migrate to MSBuild15/VS2017

### ISSUE THREAD

**Issue by am11** [aspnet/Home#2011]
Moved from https://github.com/aspnet/Configuration/issues/620

In launchSettings.json of ASP.NET MVC Core project, we have:

```json
    "SomeEnvName": {
      "commandName": "Project",
      "commandLineArgs": "--port=1234",
      "launchBrowser": true,   <-- carrot
      "launchUrl": "http://localhost:1234",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "SomeEnvName"
      }
    },
```

With .NET Core CLI v1.0.0-preview2.1, on running with `SomeEnvName` setting in VS2015, it launches the browser (while the app is still starting asynchronously).

After the `dotnet migrate` to CLI v1.0.0 RTM, running the project in VS2017 with same setting does not launch the browser.

I couldn't find any `aspnet/Announcement` about this, so thought this might be the bug for this repo. Please CMIIW or missed something during the migrate. :)

PS manually opening the browser and running the app works of course but defeats the purpose of `launchBrowser: true`.

**Comment by Tratcher** [comment]
@BillHiebert?

**Comment by BillHiebert** [comment]
This works fine with the latest tooling, VS will launch the webserver on port 5000 in this case. It doesn't read the command line --port argument so uses the default. To fix that set applicationUrl=1234. And you don't need to specify a launch url as by default VS launches the browser on the applicationUrl. 

    "SomeEnvName": {
      "commandName": "Project",
      "commandLineArgs": "--port=1234",
      "launchBrowser": true,
      "applicationUrl" : "http://localhost:1234",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "SomeEnvName"
      }
    }

**Comment by am11** [comment]
@BillHiebert, thanks a lot! Replacing `launchUrl` with `applicationUrl` did the trick. 👍
