### ISSUE TITLE
Controller's Ok/Json  serializer  [long] bug?

### ISSUE THREAD

**Issue by shuaqq2004** [aspnet/Home#2013]
my pc: windows10 x64  , VS2017  ,   .net core app 1.1

`public IActionResult ........{`
`     var u = userService.Login(user);`
`     return Ok(u); `
`}`
OK to return json:
{
  **"id": 20403579491848190,    // u.Id = 20403579491848193** last 3 into 0!!! wrong!!!
  "name": "string",
  "description": null,
  "role": 0,
  "sex": false,
  "birthday": null,
  "avatar": null,
  "createTime": "2017-04-26 16:52:56",
  "isDeleted": false
}

` var u = userService.Login(user);`
 `return Content(Newtonsoft.Json.JsonConvert.SerializeObject(u));`
return text:
{"Id":**20403579491848193**,"Name":"string","Description":null,"Role":0,"Sex":false,"Birthday":null,"Avatar":null,"CreateTime":"2017-04-26T16:52:56","IsDeleted":false}
this is right.

**Id : long**

**Comment by rynowak** [comment]
Hi @shuaqq2004 - MVC use [Json.NET](https://github.com/JamesNK/Newtonsoft.Json) for JSON serialization so I suggest taking a look at their docs to try and find a solution to your issue.

**Comment by shuaqq2004** [comment]
I do not know who this bug is generated, I use JSON.net alone serialization into a string and no problem. I only know that after I called **Json (user) or Ok(user)**, the wrong message was returned in the browser.

I do not know what the .net core is doing.

**Comment by ikourfaln** [comment]
@shuaqq2004 this is not a bug.
You are returning a ContentResult, and The default return type of a ContentResult is string, you need to specify a MIME type:

```
return Content(Newtonsoft.Json.JsonConvert.SerializeObject(u), new MediaTypeHeaderValue("application/json"));
```

But I don't know why are you using this approach !! MVC use Json.NET for serialization if you return an Object. I suggest using JSON ActionResult or OK ActionResult if you are requesting a JSON type.

**Comment by ikourfaln** [comment]
@shuaqq2004 
I see that you need some knowledge :wink: . Action Results are Explained Here:
http://hamidmosalla.com/2017/03/29/asp-net-core-action-results-explained
I highly recommend reading this article.

**Comment by rynowak** [comment]
Hi @shuaqq2004 

I think the issue you are seeing here is that JSON only has support for 64 bit **floating point numbers**, not 64 bit integers.

For instance if I try this:
```
        public IActionResult Json()
        {
            return Ok(new Foo() { Bleh = 20403579491848193L });
        }
```

The **text** sent to my browser is `{"bleh":20403579491848193}` - however if I try to interact with this number in javascript, I see the number `20403579491848190`. The reason for this is that the number `20403579491848193` is not representable as a 64bit floating point number. 

You can see this here: http://www.exploringbinary.com/floating-point-converter/ (select the 'raw hexidecimal' checkbox). If you plug in both of these numbers you'll see that they both are converted to 43521F3CA2F08400 in hex.

-----------------------------

I'd suggest following up with Json.NET's docs on how to solve this issue.

**Comment by shuaqq2004** [comment]
I know the reason is that javascript deal with bigint when there is a problem.
It seems that the database table key changed to varchar , or asp.net core output / input must be id: long into string
