### ISSUE TITLE
test cases can't show in Test explorer of VS2017

### ISSUE THREAD

**Issue by shirhatti** [aspnet/Home#2016]
_From @xuzhg on March 27, 2017 8:46_

I am using VS2017 Enterprise as below:

![image](https://cloud.githubusercontent.com/assets/9426627/24347780/16228c4c-130c-11e7-9a08-7c29de1bb337.png)

I can use VS2017 to open the `Configuration.sln` and it can load all test cases in the Test Explorer several days ago, But today it can't load test cases except for AzureKeyVault project as below as below:

![image](https://cloud.githubusercontent.com/assets/9426627/24347899/7ab57c00-130c-11e7-9804-3cb3271d2b64.png)

![image](https://cloud.githubusercontent.com/assets/9426627/24347938/96952006-130c-11e7-8c81-fe7e7472440d.png)

do I miss something?

Thanks.

_Copied from original issue: aspnet/Configuration#634_

**Comment by natemcmaster** [comment]
@xuzhg which branch are you on? If you are trying to use .NET Core 2.0, this has known issues with VS RTM. Preview VS builds are better.

**Comment by xuzhg** [comment]
dev branch and VS2017 Enterprise.

**Comment by natemcmaster** [comment]
@xuzhg try the 15.2 preview. I'm told it has better support for this. https://www.visualstudio.com/en-us/news/releasenotes/vs2017-preview-relnotes. Heads up, though: .NET Core 2.0 is not officially support in RTM VS. That will come later this year. In the meantime, you can workaround this by running tests from command line with `dotnet test`. See also https://github.com/aspnet/Announcements/issues/234

**Comment by moozzyk** [comment]
Hacky workaround - you can try copying a 2.0 runtime into `C:\Program Files\dotnet\shared\Microsoft.NETCore.App`

**Comment by natemcmaster** [comment]
Or get the runtime installer from https://github.com/dotnet/core-setup#daily-builds

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
