### ISSUE TITLE
VS2017 Publish issue

### ISSUE THREAD

**Issue by John0King** [aspnet/Home#2017]
I have a **Asp.Net Core** web project (.net 4.5.2), And I reference a few **COM dll** (`Microsoft.Office.Interop` ,word、Excel stuff) ,  the project can not build use `dotnet build ` but can build with visual studio 2017.  when I press `F5` or `ctrl + F5`  , the app  run fine as I expected , but when I use `publish`(folder base publish)  ,  the published app can run but always return a 500 error,  after I check the output , I find out the different between build folder and publish folder is the location of those com dlls.
**build folder:**
```
app.exe
<com>.dll
```
**publish folder**
```
refs/<com>.dll
app.exe
```

And I have a question about the publish folder,  what does `refs` folder do?  the app can run even when I delete the refs folder

**Comment by davidfowl** [comment]
refs are used for runtime compilation. We have this turned on by default in case you're using MVC razor views and runtime compilation. You can turn it off by setting `<PreserveCompilationContext>false<PreserveCompilationContext>` in your csproj

**Comment by John0King** [comment]
@davidfowl  Thanks for explain the use of `refs` folder ! 
Any ideas on how to config the `COM` dll to stay in root folder ?

**Comment by MaxFletcher** [comment]
I encountered the same issue in regards to COM references ending up in the refs directory. I am not sure if that is intended behaviour or not, but my application would not run under IIS until the Interop dlls have been copied into the root publish output directory. 

I solved this by adding the following to my .pubxml file:

```
<Target Name="AfterWebPublish" AfterTargets="Publish">
    <ItemGroup>
      <FilesToMove Include="$(publishDir)\refs\Interop.*.dll" />
    </ItemGroup>
    
    <Move SourceFiles="@(FilesToMove)" DestinationFolder="$(publishDir)" />
  </Target>
```

**Comment by John0King** [comment]
@davidfowl   Does this issue solved ? Should I close this issue?
I'm no long directly use those `COM` thing, I'm using `NetOffice` package now.

**Comment by Eilon** [comment]
I don't think there's any further action we can take on this issue here.

I recommend posting any further questions on one of these repos:
* MSBuild issues: https://github.com/microsoft/msbuild
* .NET CLI issues: https://github.com/dotnet/cli
* .NET Core SDK issues: https://github.com/dotnet/sdk
