### ISSUE TITLE
ASP.NET Core Support for WS-* 

### ISSUE THREAD

**Issue by jmolanofer** [aspnet/Home#2020]
Within the ASP.NET Core documentation, no reference to the WS-* specifications is found, this is vital to implement SOA correctly.
I would appreciate information regarding the use of these specifications in ASP.NET Core.

**Comment by davidfowl** [comment]
There is no support for SOAP or WS-* in ASP.NET Core.

**Comment by jmolanofer** [comment]
Well, thanks for your clear answer.
Changing the question, will not this technology be supported?

**Comment by davidfowl** [comment]
On .NET Framework yes there are no plans to bring WS-* to ASP.NET Core on .NET Core AFAIK.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
