### ISSUE TITLE
Improve generic to support IHttpActionResult<T>

### ISSUE THREAD

**Issue by uyhung** [aspnet/Home#2021]
Web API 2 does recommends to returns IHttpActionResult for all action methods, but it does not support IHttpActionResult. This make the action method's signature is less readable. After researching the internet I found out the reason is said that IHttpActionResult is not supported because it's not type-safe, but that reason is not reasonable to me.

I wonder if it's a limitation of C#'s generic implementation?

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
