### ISSUE TITLE
add migration mispelled 'using' in the generated migration file.

### ISSUE THREAD

**Issue by bwoodard007** [aspnet/Home#2025]
I added a department property in my ApplicationUser class for Identity, then I used the package manager console to add a new migration to update the database. 

The migration file that was generated included

uusing Sytem; 

on the first line.

First time I've seen this error, a misspelling.

```
uusing System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore.Migrations;

namespace LeadCore.Migrations
{
    public partial class department : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<string>(
                name: "Department",
                table: "AspNetUsers",
                nullable: true);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "Department",
                table: "AspNetUsers");
        }
    }
}
```

**Comment by Tratcher** [comment]
@bricelam This this EF or Scaffolding?

**Comment by bricelam** [comment]
EF

**Comment by bwoodard007** [comment]
EF

**Comment by bricelam** [comment]
But we have [tests for this](https://github.com/aspnet/EntityFramework/blob/dev/test/EFCore.Design.Tests/Migrations/Design/CSharpMigrationsGeneratorTest.cs#L67), so I'm pretty skeptical that it's actually on our end...

**Comment by bwoodard007** [comment]
I would be too, all I have is Resharper and Web Essentials installed using vs 2017.

It was the generated file so it's not like I fat fingered it or anything.

**Comment by bricelam** [comment]
Does it reproduce consistently? Could you submit an issue on [aspnet/EntityFramework](https://github.com/aspnet/EntityFramework) with as much information as you can provide about the environment and the project you're using?

**Comment by bwoodard007** [comment]
No, it's only happened once in the last 3 migrations.

**Comment by bricelam** [comment]
After the file is generated, it's opened in VS and the cursor is placed at the beginning for a fraction of a second before focus is returned to the Package Manager Console. Any chance you typed the *U* in `Update-Database` during this? That's my best theory...

**Comment by bwoodard007** [comment]
No chance that happened, it was the first thing I thought of also.

**Comment by bricelam** [comment]
Keep an eye on it, let us know if it happens again.

**Comment by bwoodard007** [comment]
Lag from console typing caused this issue, not a problem on your end.
