### ISSUE TITLE
Project migration from the 2016 RC1 to VS 2017 with Asp Core works locally perfectly and deploys, but the deployment now seems to not bring anything from azure table storage

### ISSUE THREAD

**Issue by livarcocc** [aspnet/Home#2027]
_From @RodrigoCC90 on May 10, 2017 15:29_

Background. This project was started with dotnet 1.0.0-preview2-003121 and am now in 1.0.3 

(1) First changes, I simply accepted the automatic visual studio migration. Debug worked on the first try perfectly as far as I could tell. My home page loaded with images and information that are all in azure table storage. 

(2) I then I decide to put this version on my already existing development web app that has hosted many different projects that I have been migrating. I open the page and it all looks good until I don't see any images loaded for different images that are brought from azure table storage. I bring the information from a "Pictures" table and the entry in the table has corresponding blob information stored. I originally think its razor, because I display the entries with an @foreach but I add a string using @Html.Raw and it appears in the deployment perfectly.

(3) At this point I open NuGet Package Manager for the solution and see that 1 of my 4 class libraries has a 1.6.0 for NetStandardLibrary and the others are 1.6.1. I try to update using the user interface but the version is blocked. From there, I Install-Package NETStandard.Library in the package manager console. Everything continuous to work locally but same problem in the deployment. Nothing else to consolidate. Important info: this specific class library is where is where I handle all the table storage things. 

(4) I then see 28 updates available for packages and decide to update table storage from 7.2.1 to 8.1.1. In the solution, the web application project and 2 class library projects were updated. The class libraries update well but the web project can't. It uninstalled the older packages and installed the new then reversed the process. Project works locally and the deployment has the same error, no images or info from the tables. After debugging I checked the package manager solution to see if I could uninstall windows storage from the web app project and the version appears to be 8.1.1.

(5) Updated from 1.1.2 to "Microsoft.AspNetCore.Mvc" Version="1.1.3". Same situation.

(6) Microsoft.NETCore.App isn't in the update list but in the installed list it has a blocked option to update to 1.1.2. I decide to go for the Install-Package Microsoft.NETCore.App -Version 1.1.2 in the NuGet Package Manager. Locally doesn't work due to 2 projects the having the same dependencies but different versions. Can't find any consolidation opportunities in the nuget package manager. 

Not sure what do to right now after I've touched the solution so much. Any suggestions? Im not even sure (6) is what I should have done. 

Suspicions as to what the problem could be:
-- Perhaps my appsettings.Development.json is not being accessed in the deployment due to a change in some package or maybe how launchsettings.json is accessed (where I declare which environment I'm using). 
-- I feel like the project NETStandardLibrary update being blocked intially by the web project meant that something important must have been relying on that previous version. But why would it work locally and not in the deployment?

Next tries: 
1. Reverting (6) and removing dependency of web app on windows azure package through some re-coding. 
2. Starting a new web app in my azure account and seeing if the issue could be on the azure side due to the web app having hosted projects with earlier dotnet versions.
3. Doing (6) and trying to make it build.

_Copied from original issue: dotnet/sdk#1196_

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
