### ISSUE TITLE
Announcement post link is broken

### ISSUE THREAD

**Issue by garora** [aspnet/Home#2028]
Recently @danroth27 added a [2.0.0-Preview release](https://github.com/aspnet/Home/releases/tag/2.0.0-preview1) with [announcement](https://blogs.msdn.microsoft.com/webdev/2017/05/09/aspnet-2-preview-1/) post. Unfortunately, the url is not working and leading a 'Page Not Found!'. Can anyone fix it?

**Comment by garora** [comment]
I found the correct link to announcement post [Announcing ASP.NET 2.0.0-Preview1 and Updates for .NET Web Developers](https://blogs.msdn.microsoft.com/webdev/2017/05/10/aspnet-2-preview-1/)

**Comment by danroth27** [comment]
Ugh! Sorry about that! Fixed now.
