### ISSUE TITLE
ADOMD.NET in ASP.NET Core 2.0.0

### ISSUE THREAD

**Issue by Kevenvz** [aspnet/Home#2029]
Since the removal of .NET Framework support, how am I supposed to use ADOMD.NET (SSAS) in future projects? Does this mean I have to stick to using ASP.NET Core 1.x.x?

**Comment by MaximRouiller** [comment]
Hi @Kevenvz 

This is only for the preview version. As mentioned in [this blog post](https://blogs.msdn.microsoft.com/webdev/2017/05/10/aspnet-2-preview-1/), the intention is to have ASP.NET Core 2.0 target .NET Standard 2.0.

Relevant quote: 

> ## Preview 1 Issues
> This preview version of ASP.NET Core 2.0 ships with support for the .NET Core 2.0 SDK only.  Our goal is to ship ASP.NET Core 2.0 on .NET Standard 2.0 so applications can run on .NET Core, Mono and .NET Framework.  As the team was working through the last of their issues before Build, it was uncovered that the preview of ASP.NET Core 2.0 utilized API’s that were outside of .NET Standard 2.0, preventing it from running on .NET Framework. Because of this we limited Preview 1 support .NET Core only so it would not break a developer upgrading an ASP.NET Core 1.x application to ASP.NET Core 2 preview on .NET Framework.

**Comment by Kevenvz** [comment]
I totally did not read that. Thanks!
