### ISSUE TITLE
Coupling of ASP.NET Core and .NET Core

### ISSUE THREAD

**Issue by dustinmoris** [aspnet/Home#2031]
Hi,

In [this session at the last Build event](https://channel9.msdn.com/Events/Build/2017/C9L18) Scott Hunter mentioned that ASP.NET Core 2.0 will be part of .NET Core 2.0, so that it is already included in the platform and when someone deploys an ASP.NET Core 2.0 web app to a hosting provider they only deploy their code.

Does that mean that ASP.NET Core and .NET Core will version together or still separately? If separately is it possible to deploy a newer ASP.NET Core on top of .NET Core 2.0 when deploying a web app? If not then I would be totally at the mercy of my hosting provider when and which version of .NET Core they deploy when I want to use ASP.NET Core.

For example if I'd want to run on a nightly build of ASP.NET Core 2.x would that be possible when ASP.NET Core 2.0 is baked into netcore2.0?

**Comment by MaximRouiller** [comment]
ASP.NET Core 2.0 will (out of preview) depend on `netstandard2.0`. 

Whatever runtime it needs, it will need to be `netstandard2.0` compatible (whatever the OS).

Right now, ASP.NET Core depends on .NET Core 2.0 which is just temporary for this preview.

That's what I got out of the announcement and following blog posts.

**Comment by DamianEdwards** [comment]
This is more of a product packaging thing. When you install the .NET Core SDK (using one of the installers) you get a bunch of sub-components including the `dotnet` executable, CLI, and ASP.NET Core packages & runtime store. The ASP.NET Core packages themselves (as @MaximRouiller points out) intend to target `netstandard` and of course still ship on nuget.org, such that you can use them on any platform and project system that supports the version of `netstandard` targeted. That said, we intend to ship ASP.NET Core in-step with .NET Core, such that their major and minor versions will (generally) align.

**Comment by dustinmoris** [comment]
Thanks for the clarification!

**Comment by davidfowl** [comment]
That said, I'm not sure we'll test newer versions of ASP.NET Core on older .NET Core versions.

**Comment by dustinmoris** [comment]
I would have expected that you'd test it at least on those which are still officially supported, but anyways, if ASP.NET Core 2.x targets a netstandard version and if a platform has been tested to work on that version or a higher version of the netstandard then I wouldn't expect any issues anyway...

On a side note, I really hope that .NET Core as a platform will really remain as little as possible, and everything else will be shipped as NuGet package on top of it. This is just a much more future proof model IMHO. It gives developers more power in being in control of dependencies, versions for backwards compatibility, etc.

If you let .NET Core platform bloat like netfx over time, then in 10 years we will need another .NET Core (not saying you do, but just want to say that I really really like that netcoreapp is small at the moment and things like ASP.NET or other platforms on top of it come as an opt-in package rather than a fixed asset).

**Comment by davidfowl** [comment]
> I would have expected that you'd test it at least on those which are still officially supported

That's something worth considering. /cc @DamianEdwards 

> if ASP.NET Core 2.x targets a netstandard version and if a platform has been tested against that version or a higher version then I wouldn't expect any issues anyway...

Unfortunately that doesn't reflect reality. You *really* need to test wherever you intend to run, just compiling for netstandard isn't good enough.
