### ISSUE TITLE
PlatformNotSupportedException creating the certificate

### ISSUE THREAD

**Issue by raffaeler** [aspnet/Home#2038]
asp.net core 2.0 Preview 1
I created a plain vanilla app using the VS2017.3 template (selecting username/pwd authn).
After a long work configurating the https stuff, on a Linux ARM device I get this error:

System.PlatformNotSupportedException: The FriendlyName value cannot be set on Unix.

I believe the problem is just a wrong option passed to openssl.
I will try to workaround the problem by manually crafting the certificate from bash.

**Comment by Tratcher** [comment]
@javiercn

**Comment by javiercn** [comment]
Does this happen when you try to create the signing certificate with the developer certificate middleware?

**Comment by raffaeler** [comment]
Yes.
I also tried to pre-generate the certificate as for [https://docs.microsoft.com/en-us/aspnet/core/security/https](https://docs.microsoft.com/en-us/aspnet/core/security/https) but at runtime the app continues asking to create the developer certificate.
The given link is definitely not complete and I just used the openssl parameters to create the identity cert in addition to the ssl one.
Some more detailed info would be appreciated as well.

**Comment by coldzone** [comment]
hello im in the same boat over here
i crreated an mvc app in ubuntu and followed instructions on the webpage to create certificate
then running the project the project shows me the page its not authenticated after bypass when going to login shows me the page to create certificate
its sems the certificate its missing something on creation or there is a missing step
i added certificates manually to firefox and chrome without result

**Comment by javiercn** [comment]
There is a bug in preview one when trying to create the certificate on Linux as an alternative, you can generate a certificate manually (a pfx file), load it in your app `new X509Certificate2(pfx,...)` and call `AddCertificate(cert)` after `AddIdentityService()`

**Comment by raffaeler** [comment]
Resolved in the 2.0 RTM
