### ISSUE TITLE
Replacement for `dnu commands install` in dotnet: dotnet add tool

### ISSUE THREAD

**Issue by peterblazejewicz** [aspnet/Home#2039]
I've a face palm moment today as I was using my keyboard muscle memory trying to add 'dotnet add package Microsoft.DotNet.Watcher.Tools` naively and using them after restore.
As kindly explained to me:
https://github.com/aspnet/DotNetTools/issues/297#issuecomment-303191445
I'm supposed to edit `.csproj` and insert relevant tooling information into separate group:
```xml
<ItemGroup>
    <DotNetCliToolReference Include="Microsoft.DotNet.Watcher.Tools" Version="1.0.0" />
    <DotNetCliToolReference Include="Microsoft.Extensions.SecretManager.Tools" Version="1.0.0" />
  </ItemGroup>
```
Could you please consider to adding back a nice, quick way to script dependency installation back to project file? (`dotnet add tool [.....]`?)
Thanks!

**Comment by natemcmaster** [comment]
This issue was moved to dotnet/cli#6661
