### ISSUE TITLE
 The Web Server Failed with status code 200, OK | Unable to start process dotnet.exe

### ISSUE THREAD

**Issue by HerrNiklasRaab** [aspnet/Home#2040]
Look at my StackOverFlow Post: 
https://stackoverflow.com/questions/44119158/the-web-server-failed-with-status-code-200-ok-unable-to-start-process-dotnet

How can i figure out more details, to provide you with better informations?

Update: Starting with this command in package manager works fine: dotnet run --p C:\Users\nikla\Source\Repos\StreamWorker\streamworker\streamworker.csproj 

Also i can attach debugger after starting.

**Comment by Tratcher** [comment]
@BillHiebert ?

**Comment by HerrNiklasRaab** [comment]
> How can i figure out more details, to provide you with better informations?

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
