### ISSUE TITLE
ASP.Net Web application start but localhost is currently unable to handle this request in Asp.net core 1.1 on visual studio 2017 

### ISSUE THREAD

**Issue by umerwaheed** [aspnet/Home#2041]
I have recently installed Visual studio 2017.I have a web application in Asp.net core MVC. When i start it, it runs fine but  "localhost is currently unable to handle this request" error comes. 
![httperror](https://cloud.githubusercontent.com/assets/11839875/26437589/878edd46-4137-11e7-909a-4590bd3485da.PNG)

I thought there is any run time exception in my code. I debugged the code from controller to view to layout page but there was no any error in my code. Then i saw my request using fiddler but i found nothing helpful.
![ab](https://cloud.githubusercontent.com/assets/11839875/26437717/2e614a14-4138-11e7-8587-a1c402daef0d.PNG)

I googled and tried many solutions but these solutions did not work for me. 
 My colleagues also have this project with same code but it is working fine on his machine. We both tried to figure out the difference and what we have found that on his machine, there is only visual studio 2017. But on my machine i have VS 2017 and VS 2015 as well.  I can't uninstall VS 2015 because i have to work on a legacy project which was built on VS2015. 

I did not find any issue related to my code. Is it a problem in VS 2017? Any solution for this issue?

**Comment by the-super-coder** [comment]
Reference: Umer and I tried to get help from this issue:
https://github.com/aspnet/Home/issues/1982

But did not work. He needs VS2015 and VS2017 both installed.

**Comment by DureSameen** [comment]
I had similar problem . I installed VS 2017 in a fresh virtual machine and then compared  installed its program on both machine. It seems the ASPNET Core 1.0 preview was shipped as separate program with visual studio 2015, prior to release of visual studio 2017.  These extra program installed cause problem and IIS does not run .. with visual studio 2017.

Please check installed program and uninstall all unwanted add on of ASPNET Core.

**Comment by umerwaheed** [comment]
@DureSameen i have uninstalled all program that contain .net core word. Still not working.

**Comment by umerwaheed** [comment]
After tried so many things i have resolved the issue. Issue was due to **BrowserLink**. If i disable the browser link then application works fine. Enabling **browserLink** causes the problem. I removed app.usebrowserlink() from the code and also disable **browserLink** from down arrow right after the IIS express debug button of visual studio.  This issue is already reported [https://github.com/aspnet/Tooling/issues/1015](url)

**Comment by the-super-coder** [comment]
Good Catch @umerwaheed. This issue costed us a lot of time and effort, and turned out to be a small glitch. I expect more visibility from .Net Core team regarding Known-Issues.

Btw, the issue's link you mentioned above is giving 404.

**Comment by wgutierrezr** [comment]
Hi
I got this problem and I did that @umerwaheed said and it works. Suddenly this problem appears when I was debugging with Chrome Version 60.0.3112.90 (I updated Chrome), but IE 11 works with BrowserLink enabled. I'm using ASP.Net Core 1.1.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.

**Comment by bsparihar** [comment]
- Go to the LAN settings (in Chrome : Tools-> Options-> Under the hood -> Change Proxy setting -> LAN Setting)
- 
- There will be a checkbox for "Bypass proxy server for local address"
- 
- Tick the checkbox.

**Comment by Song2017** [comment]
Run asp.net MVC core 1.1 project in vs2017 also get this error.     
Solved by upgrade all dll version 1.x to latest 2.x.

**Comment by chouhanaditya** [comment]
Please search for <DebugType>full</DebugType> in your csproj file. If you find one please change it to <DebugType>portable</DebugType>. 

.NET Core introduced a new symbol file (PDB) format - portable PDBs. Unlike traditional PDBs (existing 'full' mode) which were Windows-only, portable PDBs can be created and read on all the platforms.
Read about it more [here](https://github.com/dotnet/core/blob/e6049bb60307d987e044c39a106e0d6cf98857a3/Documentation/diagnostics/portable_pdb.md)

**Comment by sushil6451** [comment]
I have a web application in Asp.net core 2.2. Facing following issue.

This site can’t be reached

The webpage at https://localhost:44380/Distributor/IndexAsync might be temporarily down or it may have moved permanently to a new web address.

ERR_SPDY_PROTOCOL_ERROR
