### ISSUE TITLE
Bring Windows Template Studio to ASP.NET

### ISSUE THREAD

**Issue by Bartmax** [aspnet/Home#2042]
Is there any plan to bring Windows Template Studio to asp.net core framework. I think that is exactly what we customers want/needs.

https://github.com/Microsoft/WindowsTemplateStudio/

**Comment by davidfowl** [comment]
What? Are you talking about a sample LOB app that shows best practices?

**Comment by Bartmax** [comment]
I mean, Visual Studio new Project, Pick ASP.NET Core and then you present you with options for modular project type / patterns / frameworks. That will boilerplate the basics and connects stuff.

This may be a lot of work, i'm thinking in a lot of community effort here. (like the WTS)

not sure about which stuff makes most sense, but to drop some ideas of options:

Target Platform: [ ] Windows [ ] Linux [ ] MacOS (this will help choose the posible TFMs options and/or requirements)
Architecture: Microservice | DDD | whatever (creates the basics of the architecture)
Autentication : Local / Org / OpenId ->  B2C | OAuth | Idsrv. (imports libraries and create the Controllers/views/logic of auth.
Data: SQL | DocumentDB | Table Storage (brings the packages and creates the appropriate connection strings) it can actually get data from azure connected account to configure.
ORM: Entity framework | Dapper (provide the dbcontext, the libraries, the migration tools... )
Search: Azure search | Elastic search (include the libraries, service with api calls and configuration on json)
Backend : (configure controllers with area, policies, and user management) using identity (adds admin area with controller views, user CRUD and add policies to startup)
Client side Package Manager: Bower | NPM
Frontend framework: Angular | React | Knockout (add the dependencies and initial setup (app.js) for the chosen framework) Also if there's authentication it can include the basics to authenticate/register users.
Client side task runner : Bundle&Minif | Webpack | grunt | gulp 
Container : Docker (this may ask to include images of required services like SQL Server) ??

does it make sense?

**Comment by davidfowl** [comment]
Not really no.

**Comment by Bartmax** [comment]
> I still don't understand the goal (maybe because I'm not familiar with the windows template studio)

@davidfowl found a concrete example, it would be great if you can take a second look at this issue

This is what I image the "API" template could be:
https://github.com/ASP-NET-Core-Boilerplate/Templates/blob/master/MVC%206%20API.md

reopened, hope a concrete example makes it more clear to evaluate.

**Comment by davidfowl** [comment]
Why not just party on the ASP.NET Boilerplate as a community project? Why does it need to be in the box?

**Comment by Bartmax** [comment]
It doesn't *need*.
It will be great for discover ability and trust.
It allows to adhere to coding standards - guidelines, and goals/principles with a central place to discuss and/or make improvements. 

At this point I suggest you to take a look at **Principles** of Windows Template Studio readme section.

>Why does it need to be in the box?

Why wouldn't microsoft want/can provide a way for the community (or themselves) to provide rich templates for their platform ?

**Comment by MJomaa** [comment]
> Why not just party on the ASP.NET Boilerplate as a community project? Why does it need to be in the box?

The main reason is that there is no Microsoft™ in its name. It's much more encouraging to contribute to such a project if there is a company backing it up.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
