### ISSUE TITLE
how can get action's customer Attribute in Filter

### ISSUE THREAD

**Issue by dinjonya** [aspnet/Home#2043]
asp.net mvc4  
in myFilterAttribute class OnActionExecuting method
I can do it
```csharp
Object[] actionFilter = context.ActionDescriptor.GetCustomAttributes(typeof(NoFilterAttribute), false);
if (actionFilter.Length > 0)
{
        base.OnActionExecuting(filterContext);
        return;
}
```
but in asp.net core 1.1
context.ActionDescriptor has't GetCustomAttributes method. 
I want to get my action exists my customer FilterAttribute, 

I have a One CustomerFilterAttribute register in global. but my some class not  need this Filter
how can do it.
who can help me ? thks everybody

**Comment by rynowak** [comment]
I suggest making your attribute implement the `IFilterMetadata` attribute, then it will be present in `context.Filters`. 

If this is not possible you should downcast the action descriptor to `ControllerActionDescriptor` and then access the action `MethodInfo` that way.

**Comment by dinjonya** [comment]
I solved it。
public class ApiCallFilterAttribute : IActionFilter
    {
        public void OnActionExecuting(ActionExecutingContext context)
        {            
            foreach (var filterDescriptors in context.ActionDescriptor.FilterDescriptors)
            {
                if (filterDescriptors.Filter.GetType() == typeof(NoFilterAttribute))
                {
                    return;
                }
            }
      }
  }

**Comment by dandohotaru** [comment]
I stumbled upon a situation where i needed the produced output from any of the levels a `ProducesAttribute` can be defined and i ended up with something along these lines

```
var globalAttributes = context.ApiDescription.ActionDescriptor.FilterDescriptors.Select(p => p.Filter);
var controlerAttributes = context.MethodInfo?.DeclaringType?.GetCustomAttributes(true);
var methodAttributes = context.MethodInfo?.GetCustomAttributes(true);
var produceAttributes = globalAttributes
	.Union(controlerAttributes)
	.Union(methodAttributes)
	.OfType<ProducesAttribute>();
```
