### ISSUE TITLE
Unable to host asp core 2 on IIS 10 under virtual directory

### ISSUE THREAD

**Issue by rahuldhariya01** [aspnet/Home#2044]
I am trying to host a asp core 2 app on IIS 10 under a virtual directory but all root path and actions are redirecting to root path not the virtual dir.
Please help

**Comment by Tratcher** [comment]
ASP.NET Core does not support Virtual Directories. If you make it a sub application then it should work better.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
