### ISSUE TITLE
What tag/repo correlates to Identity.EF 2.2.0?

### ISSUE THREAD

**Issue by togakangaroo** [aspnet/Home#2046]
If I have a project reference to `Microsoft.AspNet.Identity.EntityFramework@2.2.0` what repo/tag correlates to this? I don't see a `v2.2.0` tag in [the identity repo](https://github.com/aspnet/Identity)

**Comment by Tratcher** [comment]
@haok

**Comment by HaoK** [comment]
https://aspnetidentity.codeplex.com/

**Comment by togakangaroo** [comment]
I've seen that. There's no 2.2.0 tag or branch?

**Comment by HaoK** [comment]
I don't think so

**Comment by togakangaroo** [comment]
So my original question - how do I find the source of the package at that version?

**Comment by HaoK** [comment]
So if you go to: https://aspnetidentity.codeplex.com/SourceControl/list/changesets

The changeset here should be 2.2.0 https://aspnetidentity.codeplex.com/SourceControl/changeset/9a81626ec4dff98731327c6b61348c45a98536f6

**Comment by togakangaroo** [comment]
I see, thank you.

It might be a good idea to put up a table of version to commit numbers for the time periods where tagging wasn't used (its especially confusing since sometimes tags or even branches *are* used or the tags are named something other than the version number)
