### ISSUE TITLE
Localization in a child Service

### ISSUE THREAD

**Issue by ranouf** [aspnet/Home#2049]
Hi,

Asp.Net Core 1.0 + Angular 4

I read this:
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization
https://andrewlock.net/adding-localisation-to-an-asp-net-core-application/
http://kennytordeur.be/blog/localization-of-an-asp-net-mvc-core-application/#comment-1214
And so many other websites.

... But all talk about the same things, localization and View/Controller.

In my case, I have 
- an ExternalEmailService in my Infrastrure Project sending email,
- a UserManager in my Core Project inviting users,
- a resource file (Resources/email.resx) in my Web Project

 from my ExternalEmailService, I want to get the email strings from the resource file.

How can I do that? Do you have an example?

Thank you

**Comment by ranouf** [comment]
From I understand:
```
services.AddLocalization(options => options.ResourcesPath = "Resources");

services.AddMvc()
  .AddViewLocalization(LanguageViewLocationExpanderFormat.Suffix)
  .AddDataAnnotationsLocalization();
```

> AddDataAnnotationsLocalization Adds support for localized DataAnnotations validation messages through IStringLocalizer abstractions.

**source**: https://docs.microsoft.com/en-US/aspnet/core/fundamentals/localization#working-with-resource-files

So In my startup.cs in my WebProject I have:
```
            //Localization
            services.AddLocalization(options => options.ResourcesPath = "Resources");

            // Add framework services.
            services.AddMvc()
                .AddViewLocalization(
                    LanguageViewLocationExpanderFormat.Suffix,
                    opts => { opts.ResourcesPath = "Resources"; })
                .AddDataAnnotationsLocalization();
```

In my ExternalEmailService in my Infrastructure project I have:
```
        private SendgridSettings _settings;
        private IStringLocalizer _localizer;

        public SendBirdEmailService(
            IOptions<SendgridSettings> settings,
            IStringLocalizer localizer
        )
        {
            _settings = settings.Value;
            _localizer = localizer;
        }
```

But, when I launch my App, I have this Error:

> 2017-06-07 11:53:21.123 -04:00 [Error] An unhandled exception has occurred while executing the request
> Autofac.Core.DependencyResolutionException: An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = UserManager (ReflectionActivator), Services = [WikikiBackend.Core.Users.UserManager], Lifetime = Autofac.Core.Lifetime.CurrentScopeLifetime, Sharing = Shared, Ownership = OwnedByLifetimeScope ---> An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = SendBirdEmailService (ReflectionActivator), Services = [WikikiBackend.Core.Email.IEmailService], Lifetime = Autofac.Core.Lifetime.CurrentScopeLifetime, Sharing = None, Ownership = OwnedByLifetimeScope ---> None of the constructors found with 'Autofac.Core.Activators.Reflection.DefaultConstructorFinder' on type 'WikikiBackend.Infrastructure.SendBird.SendBirdEmailService' can be invoked with the available services and parameters:
> Cannot resolve parameter 'Microsoft.Extensions.Localization.IStringLocalizer localizer' of constructor 'Void .ctor(Microsoft.Extensions.Options.IOptions`1[WikikiBackend.Core.Configuration.SendgridSettings], Microsoft.Extensions.Localization.IStringLocalizer)'. (See inner exception for details.) (See inner exception for details.) ---> Autofac.Core.DependencyResolutionException: An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = SendBirdEmailService (ReflectionActivator), Services = [WikikiBackend.Core.Email.IEmailService], Lifetime = Autofac.Core.Lifetime.CurrentScopeLifetime, Sharing = None, Ownership = OwnedByLifetimeScope ---> None of the constructors found with 'Autofac.Core.Activators.Reflection.DefaultConstructorFinder' on type 'WikikiBackend.Infrastructure.SendBird.SendBirdEmailService' can be invoked with the available services and parameters:
> Cannot resolve parameter 'Microsoft.Extensions.Localization.IStringLocalizer localizer' of constructor 'Void .ctor(Microsoft.Extensions.Options.IOptions`1[WikikiBackend.Core.Configuration.SendgridSettings], Microsoft.Extensions.Localization.IStringLocalizer)'. (See inner exception for details.) ---> Autofac.Core.DependencyResolutionException: None of the constructors found with 'Autofac.Core.Activators.Reflection.DefaultConstructorFinder' on type 'WikikiBackend.Infrastructure.SendBird.SendBirdEmailService' can be invoked with the available services and parameters:
> Cannot resolve parameter 'Microsoft.Extensions.Localization.IStringLocalizer localizer' of constructor 'Void .ctor(Microsoft.Extensions.Options.IOptions`1[WikikiBackend.Core.Configuration.SendgridSettings], Microsoft.Extensions.Localization.IStringLocalizer)'.

So from I understand, the injection is not correctly done, so "AddDataAnnotationsLocalization" added in startup.cs is not the way to make it work correctly.

How can I do it?

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
