### ISSUE TITLE
'ILoggerFactory' does not contain a definition for 'AddDebug()'

### ISSUE THREAD

**Issue by palhade** [aspnet/Home#2050]
Hi,

I am trying to add following lines of code in Configure() of Startup.cs of my ASP.bet Core WebAPI application.

loggerFactory.AddDebug();

but I am getting error = ILoggerFactory' does not contain a definition for 'AddDebug' and no extension method 'AddDebug' accepting a first argument of type 'ILoggerFactory' could be found (are you missing a using directive or an assembly reference?)

Is there any workaround.

Thanks
Map

**Comment by Tratcher** [comment]
What version are you using? There have been breaking changes for 2.0. E.g. https://github.com/aspnet/Announcements/issues/238

**Comment by palhade** [comment]
Thanks, this helps

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
