### ISSUE TITLE
High memory usage on Ubuntu 16

### ISSUE THREAD

**Issue by shravan2x** [aspnet/Home#2052]
I run a number of ASP .NET Core 1.1 servers on Ubuntu. This is the `htop` view of one of the processes:

![image](https://user-images.githubusercontent.com/4096676/27004803-bad831ac-4dd5-11e7-8bc0-e54871eaf91f.png)

The process appears to be using 20G of VIRT. I understand that this is not actually allocated memory, but is the highest among all processes running on the entire system. This is view of a number of apps:

![image](https://user-images.githubusercontent.com/4096676/27004820-0b96467e-4dd6-11e7-9d36-8e9d37e5f317.png)

Every one of the `20.xG` VIRTs is an ASP.NET Core app (and every other app in the 1000M range is `mono`). The actual ASP.NET server itself runs on Kestrel, is very simple and serves only static pages via MVC.

1. Is there a reason for such a high `VIRT`?
2. Why does an app that only serves static pages have 47M of _private_ memory? (I'm aware some other language like PHP or even plain HTML might be better suited for my use, but I use ASP since it is more customizable and fun to work with)

Please note that since this scenario lies on a production server, the version is 1.1. I apologize if it has already been resolved in another issue.

**Comment by shravan2x** [comment]
This issue still persists on .NET Core 2.0 and ASP.NET Core 2.0.

**Comment by Eilon** [comment]
Closing this issue because it appears that the two related issues above already have explanations.
