### ISSUE TITLE
Can I publish a ASP.NET Core application as a deb package on ubuntu 16.04

### ISSUE THREAD

**Issue by Jamesxql** [aspnet/Home#2054]
Can I publish a ASP.NET Core application as a deb package on ubuntu 16.04, if can, how should I do it? 

If not, do you have a plan to support this feature?

Thank you very much!

**Comment by natemcmaster** [comment]
This isn't a feature we currently supported, but you should be able to do this yourself by using the output of `dotnet publish`. If you publish as a "self-contained deployment", your debian package would only need to carry the published output and [dependencies](https://github.com/dotnet/core/blob/master/Documentation/prereqs.md#ubuntu) to Ubuntu's prerequisties. See [this doc](https://docs.microsoft.com/en-us/dotnet/core/deploying/index) for details deploying a .NET Core app.

If you wanted to do framework-dependency deployment, you'll need to ensure the shared framework is also listed in your package's [dependencies](https://www.debian.org/doc/debian-policy/ch-relationships.html). See https://www.microsoft.com/net/core#linuxubuntu for instructions on installing the apt feeds. To see a list of available packages, checkout https://apt-mo.trafficmanager.net/repos/dotnet-release/dists/xenial/main/binary-amd64/Packages. You'll likely only need `dotnet-sharedframework-microsoft.netcore.app-1.1.2`.

**Comment by Jamesxql** [comment]
Got it! Thank you very much.
