### ISSUE TITLE
Is it possible to precompile a web application programmatically?

### ISSUE THREAD

**Issue by ranuka2** [aspnet/Home#2055]
I'm developing a Visual Studio 2015 extension which need to to pre compile a selected web application project and emit the output to a target location. The compiled binary will be submitted to a service for analysis. I'm using Roslyn Microsoft.CodeAnalysis.MSBuild.MSBuildWorkspace to generate build artifacts from non web apllications (class libs etc.). Roslyn team mentioned that their API currently doesn't support pre-compilation of web applications. What are the options I have to programmatically build a web app and generate pre-compiled artifacts?

**Comment by davidfowl** [comment]
There's no API for precompilation but there is a tool you can run. See https://github.com/aspnet/MvcPrecompilation.

/cc @pranavkm

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
