### ISSUE TITLE
ASP.NET Core in IIS ignores user level environment variables

### ISSUE THREAD

**Issue by bgardner87** [aspnet/Home#2057]
I'm deploying a .NET Core application twice to the same server, once for QA, and once for Production. Currently I have each one of them using a different local user to run the IIS App Pool and have set the ASPNETCORE_ENVIRONMENT variables to "qa" and "production" accordingly.

This doesn't appear to work, both sites run the production configuration which I understand is the default.

Things I've looked at so far:

1. I can log in as each of the users, and the variables are set correctly.
2. There is no system level env var set, though the user level vars are supposed to override it if there was.
3. I can see the processes running as the correct users in the task manager.
4. I have restarted the entire system after setting the env vars
5. It just appears that .NET is ignoring the environment variable.
6. I can set ASPNETCORE_ENVIRONMENT at the system level, and both sites pick it up and run with it. Doing it without a system variable simply doesn't work and makes both sites default to production

Has anyone else managed to get user level env vars working with a .NET core deployment?

**Comment by Tratcher** [comment]
@shirhatti @pan-wang

**Comment by pan-wang** [comment]
How did you set up this ASPNETCORE_ENVIRONMENT variable and which version of IIS ASP.NET core module was used?

**Comment by bgardner87** [comment]
I set up the environment variable by logging into the respective users and adding the environment variables to each user.

This is still at 1.0.0 on the production server

**Comment by pan-wang** [comment]
Your method does not work as IIS worker process is a child process created by windows WAS service. If you are using IIS8 (i.e., Window8) and above, you can use the configuration solution stated in this post https://www.iis.net/configreference/system.applicationhost/applicationpools/add/environmentvariables. You just need to change configured env variable value at each deployment.

**Comment by Huntk23** [comment]
I thought if you want to use IIS with user level Environment Variables you have to set "Load User Profile" to true under the Application Pool Advanced Settings.
![image](https://user-images.githubusercontent.com/3951241/27493746-c236844c-57ff-11e7-9b87-a0734bbe2d90.png)

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
