### ISSUE TITLE
Accent and Special Characters

### ISSUE THREAD

**Issue by tarekgh** [aspnet/Home#2058]
This issue originally filed on corefx repro by @eflorespalma and I am moving it here 

https://github.com/dotnet/corefx/issues/20944

I have a problem with this code

```c#
            loggerFactory.AddConsole();

            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UseWelcomePage("/welcome");
            
            app.Run(async (context) =>
            {
                //var message = Configuration["Greeting"];
                await context.Response.WriteAsync("¿Cómo estas?");
            });
```

And when render the output show me this text Â¿CÃ³mo estas?

**Comment by Tratcher** [comment]
WriteAsync uses UTF-8. You need to set the content-type / charset for the bowser to correctly interpret it.
`context.Response.ContentType = "text/plain; charset=utf-8";`

**Comment by Tratcher** [comment]
@MaximRouiller there is no default content-type header, only a default status code (200).

**Comment by MaximRouiller** [comment]
The browser provides it through content sniffing. No?

**Comment by Tratcher** [comment]
That depends on the browser.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
