### ISSUE TITLE
Error CookieAuthenticationOptions upgrade asp.net core 1.1 to 2.0

### ISSUE THREAD

**Issue by balasratran** [aspnet/Home#2059]
I want to define area admin to set CookieAuthenticationOptions.
Please help me            
app.UseWhen(x => x.Request.Path.Value.StartsWith("/Admin"), p =>
            {
                p.UseCookieAuthentication(new CookieAuthenticationOptions()
                {
                    LoginPath = new PathString("/Admin/Account/Login/"),
                    AccessDeniedPath = new PathString("/Admin/Account/Forbidden/"),
                    AutomaticAuthenticate = true,
                    AutomaticChallenge = true
                });
            });

**Comment by Tratcher** [comment]
https://github.com/aspnet/Announcements/issues/232

**Comment by Tratcher** [comment]
https://github.com/aspnet/Security/issues/1190#issuecomment-302618448

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
