### ISSUE TITLE
System.Web.UI and System.Web.Scripts not available in .net core?

### ISSUE THREAD

**Issue by karelz** [aspnet/Home#2061]
_From @synckarthik on June 15, 2017 6:44_

![web ui](https://user-images.githubusercontent.com/23655474/27168570-dc92b82a-51c3-11e7-9dc0-a8f5593a6319.PNG)

In my project i have used **System.Web.UI** and **System.Web.Scripts**  classes. But when i upgrade to .net core it shows error .Please refer the image.

How to resolve this? Or is any alternative packages for this ?

_Copied from original issue: dotnet/core#694_

**Comment by davidfowl** [comment]
WebForms is not being ported to .NET Core.
