### ISSUE TITLE
Unnecessary using statements.

### ISSUE THREAD

**Issue by genifycom** [aspnet/Home#2062]
In ASP.NET Core when a class is created, the following are added at the top.

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

These are completely unnecessary and misleading. Please do not include ANY using statements. The Visual Studio compiler will pick up missing items and they can easily be added. There is no point assuming what will be used.

My biggest beef is having to remove using statements for items that are NOT referenced in the code.

The using statement should tell you upfront what IS being used not what ISN'T.

Thank you

**Comment by natemcmaster** [comment]
I'd recommend you open your suggestion here: https://developercommunity.visualstudio.com. This template is determined by Visual Studio.

[Hint](https://stackoverflow.com/a/2072717/2526265)

**Comment by andresmoschini** [comment]
I understand that you could prefer to remove them, but I am not sure if it is a good general approach, for example, it is very useful to have the default _usings_ for IntelliSense. Examples:

![ezgif com-video-to-gif 6](https://user-images.githubusercontent.com/1157864/27229399-d5f8e5ac-5281-11e7-9958-3e63d2ec8891.gif)

![ezgif com-video-to-gif 5](https://user-images.githubusercontent.com/1157864/27229398-d5ed5b56-5281-11e7-966a-fe482ad4293a.gif)

Thoughts?

**Comment by MaximRouiller** [comment]
Default `usings` are awesome for discoverability. 

Please keep them. Otherwise, I'm forced to `CTRL+.`  2-3 times instead of once to clean my using.

Also, this has been the default behavior to VS for a LONG time.

**Comment by markrendle** [comment]
@genifycom Don't assume everyone uses Visual Studio.

**Comment by MaximRouiller** [comment]
@markrendle

I did. I'm sorry. Most are but you do bring a good point. People who are not using VS are also to be considered.

**Comment by genifycom** [comment]
Yes, you are right. This needs to be raised on the VS forum. Apologies.

MaximRouiller, I would at least like a VS option that says include these using statement by default (or dont include any). Otherwise, who decides which ones are useful by default or not.

**Comment by MaximRouiller** [comment]
@genifycom So what you want is something a little like ReSharper where we can specify what should be kept and what should always be there? 

![image](https://user-images.githubusercontent.com/209384/27587843-f8b58eca-5b13-11e7-9000-419a0add280d.png)

Or rather than inspecting, we could go with a templating solution. I wonder how hard it is to override the `Add -> New File...` behavior of `.cs` files. I still think that we could create a custom Roslyn Analyzer that would help us fix that.

**Comment by genifycom** [comment]
Exactly. Sometimes I have my own libraries that I would like included for example.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
