### ISSUE TITLE
ASP.NET Core Webapp on Net Framework template fails to build 

### ISSUE THREAD

**Issue by mishra14** [aspnet/Home#2066]
## Problem
The ASP.NET core web app on framework  template does not build out of the box.

## Details
The ASP.NET core web app on framework  template references `NETStandard.Library.NETFramework` version `2.0.0-preview2-25405-01`. But the package does not exist on nuget.org or [dotnet-core feed
](https://dotnet.myget.org/feed/dotnet-core/package/nuget/NETStandard.Library.NETFramework).

As a result you cant build a new project.

## csproj file

```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net461</TargetFramework>
    <MvcRazorCompileOnPublish>true</MvcRazorCompileOnPublish>
    <AssetTargetFallback>$(AssetTargetFallback);portable-net45+win8+wp8+wpa81;</AssetTargetFallback>
    <UserSecretsId>aspnet-WebApplication3-2DA14627-6636-44B0-B49E-AC1545A2C132</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NETStandard.Library.NETFramework" Version="2.0.0-preview2-25405-01" />
    <PackageReference Include="Microsoft.AspNetCore" Version="2.0.0-preview2-final" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.0.0-preview2-final" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.ViewCompilation" Version="2.0.0-preview2-final" PrivateAssets="All" />
    <PackageReference Include="Microsoft.AspNetCore.StaticFiles" Version="2.0.0-preview2-final" />
    <PackageReference Include="Microsoft.VisualStudio.Web.BrowserLink" Version="2.0.0-preview2-final" />
  </ItemGroup>

  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="2.0.0-preview2-final" />
  </ItemGroup>

</Project>
```

## Data
VS: d15Rel/26618.0
NuGet: 4.3.0.4168
netcore sdk: 2.0.0-preview2

Please feel free to move this to another repo if this is not the best place for this.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
