### ISSUE TITLE
Injecting UserManager<> in class library

### ISSUE THREAD

**Issue by evindj** [aspnet/Home#2069]
Hi All,
I have defined a class library that is used by other components of the application. The library contains my model classes and all of them implement a persist method that create a database record or update an existing record in the database.   My User class extends the IdentityUser class the persist class add new users correctly but if the user already exist everything becomes trickier. I though of using the UpdateAsync Method of the UserManager class to update the user but I can't figure out a way to inject/ correctly create a UserManager inside my User c;lass.
Here is my services configuration `implementation:
```
`public void ConfigureServices(IServiceCollection services)
        {
            // Add framework services.
            services.AddApplicationInsightsTelemetry(Configuration);

            services.AddDbContext<ApplicationDbContext>(options =>
                options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")));

            services.AddIdentity<User, IdentityRole>(config =>
            {
                config.User.RequireUniqueEmail = true;
            } ).AddEntityFrameworkStores<ApplicationDbContext>()
                .AddDefaultTokenProviders();

            var builder = services.AddMvc();
            builder.AddMvcOptions(o => o.Filters.Add(new GlobalExceptionHandling()));
            // Add application services.
            services.AddTransient<IEmailSender, AuthMessageSender>();
            services.AddTransient<ISmsSender, AuthMessageSender>();
            services.AddScoped<IUserManager, CustomUserManager>();
            services.AddTransient<UserManager<User>>();
            services.AddTransient<User>();
            services.Configure<AuthMessageSenderOptions>(Configuration);
        }
```
I defined a constructor to help inject a user manager as I'll do within a controller class by that does not seem to work. Please do you guys have any points how i could handle this?

**Comment by Tratcher** [comment]
@HaoK

**Comment by HaoK** [comment]
You are trying to have a User ctor that takes a UserManager?

`User(UserManager<TUser> manager)`?  Why do you need the manager in your user?

**Comment by evindj** [comment]
I need a ```UserManager<User>``` so I can update(via the UpdateAsync method) an existing user in the database. ```context.User(this).State = Microsoft.EntityFrameworkCore.EntityState.Modified;``` followed by ```context.SaveChanges()``` threw an exception.
 I tried to inject the ```UserManager<User>``` via the ```User``` ctor but the constructor with one argument was never called I guess because I am doing something like ```User user = new User()```. before calling my persist method.

**Comment by markrendle** [comment]
@evindj Encapsulating persistence functionality within a model class is not a good approach. You'll find your application is much easier to maintain if you keep your models as simple as possible, and use a separate Manager (or just DbContext) to handle persistence.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
