### ISSUE TITLE
kvm list ends with error

### ISSUE THREAD

**Issue by twiernik** [aspnet/Home#207]
![kvmlist](https://cloud.githubusercontent.com/assets/1544483/5104636/4f142e98-6fe4-11e4-94cf-fbba3adaa5a0.png)

**Comment by camMCC** [comment]
This is fixed in the https://github.com/aspnet/kvm repo, but not fixed in the https://github.com/aspnet/Home repo.  Which means that its kinda still broken unless you take extra steps.

Extra steps are explained here: https://github.com/aspnet/kvm/issues/106

**Comment by Praburaj** [comment]
Updated `kvm` scripts in home repo just now. Pulling the latest will fix the issue.
