### ISSUE TITLE
Launching a Page within a page nav tab div tag

### ISSUE THREAD

**Issue by onyand** [aspnet/Home#2070]
I have a .NET Core project (Framework 4.6) which I have implemented bootstrap nav tabs on a page. I am unable to launch any of my existing views scaffolded based on data models when the tabs are clicked.  Example is below. What is wrong with this?

```HTML
<div class="container">
      <ul class="nav nav-tabs" style="background-color:#0072C6">
            <li role="button" class="active"><a data-toggle="tab" href="#Clients">@Localizer["lblClient"]</a></li>
            <li role="button"><a data-toggle="tab" href="#ClientCompanies">@Localizer["lblClientCompany"]</a></li>
        </ul>
        <div class="tab-content">
            <div id="Client" class="tab-pane fade in active">
            @Html.RenderPartialAsync("~/Views/Clients/Index.cshtml")
            </div>
            <div id="ClientCompanies" class="tab-pane fade">
                @Html.RenderPartialAsync("~/Views/Clients/Index.cshtml", Model)
            </div>
        </div>
    </div>
```

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
