### ISSUE TITLE
Execute code post-response

### ISSUE THREAD

**Issue by JeanCollas** [aspnet/Home#2071]
Is there any way to execute some code after that the response has been sent in ASP.Net Core? 
I am looking for something like an event/a "bag" of methods that should be executed once the answer has been sent.

As an example of usage, I feel like logging during the request is not efficient and should not penalize the user, so I would like to be executed after the request has been sent, but preserve the context that has been used while logging. 

If it does not exist, could this be an option for the future? ( response.ResponseSent event or something should not be a big deal to implement :) )

**Comment by smbecker** [comment]
Looks like you could use Response.OnCompleted for that very purpose. See [here](https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.AspNetCore.Http.Abstractions/HttpResponse.cs#L92)

**Comment by JeanCollas** [comment]
Indeed, looks what I am looking for. 
Any idea why there are no events implemented in `AspNetCore.Http` ?

**Comment by davidfowl** [comment]
@JeanCollas because they are implemented by the servers themselves.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
