### ISSUE TITLE
No service for type 'Microsoft.Extensions.PlatformAbstractions.IApplicationEnvironment' has been registered.

### ISSUE THREAD

**Issue by dvmahida** [aspnet/Home#2073]
When i try to run my application locally i am getting this error : 
An unhandled exception of type 'System.InvalidOperationException' occurred in Microsoft.Extensions.DependencyInjection.Abstractions.dll

Additional information: No service for type 'Microsoft.Extensions.PlatformAbstractions.IApplicationEnvironment' has been registered.

Here is my project.json
{
  "commands": {
    "web": "Microsoft.AspNet.Server.Kestrel"
  },
  "compilationOptions": {
    "emitEntryPoint": true
  },
  "dependencies": {
    "Microsoft.ApplicationInsights.AspNet": "1.0.0-rc1",
    "Microsoft.AspNet.IISPlatformHandler": "1.0.0-rc1-final",
    "Microsoft.AspNet.Mvc": "6.0.0-rc1-final",
    "Microsoft.AspNet.Server.Kestrel": "1.0.0-rc1-final",
    "Microsoft.AspNet.StaticFiles": "1.0.0-rc1-final",
    "Microsoft.Extensions.Configuration.FileProviderExtensions": "1.0.0-rc1-final",
    "Microsoft.Extensions.Configuration.Json": "1.0.0-rc1-final",
    "Microsoft.Extensions.Logging": "1.0.0-rc1-final",
    "Microsoft.Extensions.Logging.Console": "1.0.0-rc1-final",
    "Microsoft.Extensions.Logging.Debug": "1.0.0-rc1-final",
    "System.IdentityModel.Tokens.Jwt": "5.0.0",
    "WindowsAzure.ServiceBus": "3.2.2"
  },
  "exclude": [
    "wwwroot",
    "node_modules"
  ],
  "frameworks": {
    "dnx451": {
      "dependencies": {
        "Microsoft.Net.Http": "2.2.22",
        "WindowsAzure.Storage": "7.0.0"
      }
    }
  },
  "publishExclude": [
    "**.user",
    "**.vspscc"
  ],
  "version": "1.0.0-*"
}

**Comment by Tratcher** [comment]
Please move to the final 1.0.0 release. Or better yet 1.1.0.

**Comment by dvmahida** [comment]
I am using DNX 4.5.1.0. how do i move it to 1.0.0 release or 1.1.0 ?

**Comment by Tratcher** [comment]
DNX has been depreciated for over a year now. The easiest way to get started on the current versions is to use VS 2017.

**Comment by dvmahida** [comment]
I see. Is there a work around this problem ? OR only option i have is to migrate ? We have Web app which is written over year ago and its working fine in production. it just i am not able to run locally. Migrating might slow down my work, so for now i would just like to run it locally.

**Comment by Tratcher** [comment]
We don't have the bandwidth to debug applications running on deprecated versions, especially for areas we know have changed significantly like IApplicationEnvironment.

**Comment by dvmahida** [comment]
I understand. Can help me to migrate out of DNX 451. I am going though this document. https://docs.microsoft.com/en-us/dotnet/core/migration/from-dnx. is this right place to start ? which version of "netcoreappX.X" should i use ? 
Also i don't see global.json in our project. 

![image](https://user-images.githubusercontent.com/25217847/27563548-40e65aea-5a87-11e7-8dfd-f6c2484d540d.png)

**Comment by MaximRouiller** [comment]
@dvmahida You have a long way to go.... the best way might be to actually start a new project and reimport your code and see if it works.

The manual path is to go through all the announcements since the RC1 release and correct things that apply to you. It's hard and it would take longer than just migrating your code to a "New -> Project".

However, if you still want to read what changed, here's what you missed.

* [RC2](https://github.com/aspnet/announcements/issues?q=is%3Aopen+is%3Aissue+milestone%3A1.0.0-rc2)
* [1.0.0](https://github.com/aspnet/announcements/issues?q=is%3Aopen+is%3Aissue+milestone%3A1.0.0)
* [1.1.0](https://github.com/aspnet/announcements/issues?q=is%3Aopen+is%3Aissue+milestone%3A1.1.0)

**Comment by dvmahida** [comment]
@MaximRouiller @Tratcher Thanks guys for quick reply. We are using VS 2015. which project type should i migrate to (ASP.NET (.NET core) core or ASP.NET (.NET Framework ) )?

**Comment by MaximRouiller** [comment]
Because of your usage for `WindowsAzure.ServiceBus`, you'll need to go Full Framework.

That package isn't .NET Core compatible last I checked.

**Comment by dvmahida** [comment]
ok, i also see the option of ASP.NET CORE (.NET Framework ), should i use that ? or just ASP.NET (.NET Framework) ?

![image](https://user-images.githubusercontent.com/25217847/27607266-2b13ea6e-5b38-11e7-92e6-0ee0c898900c.png)

**Comment by parsicode** [comment]
use dotnet core for linux and windows.
dotnet framework for windows only.

**Comment by MaximRouiller** [comment]
You can go with `ASP.NET Core Web Application (.NET Framework)`. You can't use `ASP.NET Core Web Application (.NET Core)` with all packages yet.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
