### ISSUE TITLE
Discussion for ASP.NET Core 2.0.0 (final) high-level planning

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/Home#2076]
Discussion for aspnet/Announcements#253

**Comment by muqeet-khan** [comment]
In regards to STS, does this mean, at least in 2.0, identity and authentication will be configured just as we did in 1.x or is the removal only taking in terms of the token service?

I guess I am trying to understand if in 2.0 we will be using: 

1. `app.UseCookieAuthentication` in `Configure` route? Or
2. `services.AddCookieAuthentication();` in `ConfigureServices` route?

**Comment by DamianEdwards** [comment]
It's the removal of the token service. The other auth/security API changes remain.

**Comment by psibernetic** [comment]
Where can I find more information about the changes for STS?

**Comment by markrendle** [comment]
So regarding the convention-based configuration, does that mean none of the options will be used by the default setup in WebHostBuilder? Including the Logging configuration, for example?

**Comment by chikien276** [comment]
Sir, Will signalR be released in 2.0 ? It took me 2 weeks to persuade my team to choose .net core over Go

**Comment by BrennanConroy** [comment]
Nope, see the roadmap https://github.com/aspnet/Home/wiki/Roadmap#210-roadmap

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
