### ISSUE TITLE
Announcement of ASP.NET Core 2.0.0 Preview 2 link

### ISSUE THREAD

**Issue by garora** [aspnet/Home#2077]
@danroth27 - [Pre-release 2.0.0 Preview 2](https://github.com/aspnet/Home/releases/tag/2.0.0-preview2) contains announcement [link](https://blogs.msdn.microsoft.com/webdev/) that does not have any announcement details for Preview 2. Could you please update it with correct link?

**Comment by danroth27** [comment]
The announcement blog post isn't live yet but it will be shortly.

**Comment by danroth27** [comment]
https://blogs.msdn.microsoft.com/webdev/2017/06/28/introducing-asp-net-core-2-0-preview-2/
