### ISSUE TITLE
Bare new ASP.NET Core 2.0 application does not work on Azure

### ISSUE THREAD

**Issue by ssougnez** [aspnet/Home#2078]
Hello,

I'm creating a new "ASP.NET Core 2.0" web application via the "Empty" template of Visual Studio 2017 15.3 and then directly after, I publish it on Azure. When I access the site, I get a 502.5 error (it works locally).

Here is the web site in question: "http://dev-robot-war.azurewebsites.net/"

I also asked this question on SO (https://stackoverflow.com/questions/44550096/asp-net-core-2-0-on-azure-results-in-a-502-5) but did not get any answer.

Thanks

**Comment by IvanJosipovic** [comment]
See https://github.com/Azure/app-service-announcements/issues/14

**Comment by ssougnez** [comment]
I don't think that's the issue. If you have a look at the SO post, you'll notice that, thanks to someone who replied to my post, I noticed that the deployed DLL are actually in v 1.1.2 even though I just created the project and directly deployed it.

I'll check when I'm at my place to see if I did something wrong or if it is just Visual Studio/NuGet that have an issue.

**Comment by IvanJosipovic** [comment]
If you enable logging by setting stdoutLogEnabled="true" in the web.config. You will see the following error stating that the correct framework version is not installed.

![image](https://user-images.githubusercontent.com/9521987/27696868-9f3985d2-5ca7-11e7-8fe3-c5a021410bfc.png)

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
