### ISSUE TITLE
Including Xml documentation files from Nuget packages to the build output directory

### ISSUE THREAD

**Issue by samirski** [aspnet/Home#2079]
Is there a way to include xml documentation file from a NuGet package? My model files are build separately, so they can be shared between the projects. Now however when I publish my main project, the xml file from my model NuGet is not in the output directory...

**Comment by natemcmaster** [comment]
In the 2.0 release, there are new properties for publishing xmldocs. See https://github.com/dotnet/sdk/pull/1062

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
