### ISSUE TITLE
ASP.NET 2.0 Preview-3 - ServiceFabric

### ISSUE THREAD

**Issue by grahamehorner** [aspnet/Home#2080]
I'm trying to use ASP.NET Core 2.0 Preview-3 within ServiceFabric;  I'm getting the following error installing nugget packages ?

Attempting to gather dependency information for multiple packages with respect to project 'TenantResolver', targeting '.NETFramework,Version=v4.6.1'
Gathering dependency information took 2.94 ms
Attempting to resolve dependencies for multiple packages.
Resolving dependency information took 0 ms
Resolving actions install multiple packages
Resolution was successful but resulted in no action
There are no new updates available.
No package updates are available from the current package source for project 'TenantResolver'.
Package restore failed. Rolling back package changes for 'MultitenancyElectricityPortal'.
Time Elapsed: 00:00:02.7387361

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
