### ISSUE TITLE
Restore failed with preview2

### ISSUE THREAD

**Issue by yukozh** [aspnet/Home#2081]
![image](https://user-images.githubusercontent.com/2216750/27734885-816a7d9e-5dcf-11e7-90e5-a13b871eb731.png)

**Comment by natemcmaster** [comment]
Please share more details.

https://github.com/aspnet/Home/blob/dev/CONTRIBUTING.md#filing-issues

**Comment by Kagamine** [comment]
Clone pomelofoundation/pomelo.entityframeworkcore.mysql 
Execute dotnet restore
will show above error
.net core sdk 2.0.0 preview2
vs2017 preview 15.3
win10

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
