### ISSUE TITLE
Microsoft.AspNetCore.All 2.0.0-preview2-final doesn't restore correctly on no Windows machine

### ISSUE THREAD

**Issue by ttrunck** [aspnet/Home#2082]
This seems related to:
- https://github.com/aspnet/EntityFramework/pull/3689#issuecomment-158201904
- https://github.com/aspnet/Home/issues/1096

I replace (below is only the diff) my package reference from
```
    <PackageReference Include="Microsoft.AspNetCore" Version="2.0.0-preview2-final" />
    <PackageReference Include="Microsoft.AspNetCore.Cors" Version="2.0.0-preview2-final" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.0.0-preview2-final" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="2.0.0-preview2-final" />
    <PackageReference Include="StackExchange.Redis" Version="1.2.4" />
```

to

`
<PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.0-preview2-final" />
`

I have no issue when I run `dotnet build; dotnet run` on Windows 10.
But when I use docker (from microsoft/aspnetcore:2) each sql query raise the following exception:

```
web_1    | fail: Microsoft.AspNetCore.Server.Kestrel[13]
web_1    |       Connection id "0HL60K5KA5S3D", Request id "0HL60K5KA5S3D:00000002": An unhandled exception was thrown by the application.
web_1    | System.TypeInitializationException: The type initializer for 'System.Data.SqlClient.TdsParser' threw an exception. ---> System.IO.FileLoadException: Could not load file or assembly 'System.Text.Encoding.CodePages, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
web_1    |    at System.Data.SqlClient.TdsParser..cctor()
web_1    |    --- End of inner exception stack trace ---
```

Thanks

**Comment by davidfowl** [comment]
Is that your entire project file?

**Comment by ttrunck** [comment]
```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <ApplicationInsightsResourceId>Stuff</ApplicationInsightsResourceId>
    <ApplicationInsightsAnnotationResourceId>Stuff</ApplicationInsightsAnnotationResourceId>
    <UserSecretsId>Guid</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="1.50.2" />
    <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.0-preview2-final" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="1.0.0" />
    <PackageReference Include="System.ValueTuple" Version="4.4.0-preview2-25405-01" />
  </ItemGroup>

  <ItemGroup>
    <WCFMetadata Include="Connected Services" />
  </ItemGroup>

</Project>
```

**Comment by davidfowl** [comment]
It's likely an incompatibility with one of your other packages. I'd check dapper, since the error is complaining about SQL client.

**Comment by ttrunck** [comment]
You are right thanks for your help.
I tried a minimal exemple using System.Data.SqlClient directly instead of Dapper and I don't have the issue.
Still the whole experience is confusing. Would it be possible to see that the packages are incompatible before runtime? For this situation is the fix need to be done in the Dapper project? It seems to be a netstandard1.3 and I don't see any reference to `System.Text.Encoding.CodePages` so I'm no so sure about the next step.

If there isn't anything that need do be done here, feel free to close this issue.

**Comment by davidfowl** [comment]
Here's what I would do:
- figure out what version combination of SqlClient and Dapper are broken with netcoreapp2.0.
- Make a new console project targeting netcoreapp2.0 get a minimal repro
- open a big on corefx with that repro to see if it was intentional.

**Comment by markrendle** [comment]
@ttrunck If you publish the application that includes Dapper, is `System.Text.Encoding.CodePages.dll` included in the output, and if so, what version is it?

Check this post about publishing in a Docker container using multi-stage build: http://www.wintellect.com/devcenter/bstewart/multi-stage-builds-docker

**Comment by ttrunck** [comment]
I spend few hours trying to have a smaller repro without success. After reinstalling Docker and cloning my project into a fresh folder I cannot reproduce my issue. I'm closing this issue since it's very likely that it was a problem with my machine/build environment.

@markrendle Thanks for the link that will likely improve my build reproducibility.
