### ISSUE TITLE
Pull dependencies automatically, dependency not being read.

### ISSUE THREAD

**Issue by Finnegan353** [aspnet/Home#2084]
Hi, 

Is anyone aware of how to get dependencies automatically when running in Docker or how to do a "dot net restore" from a dockerfile?

Currently I have copied my app from Windows 7 VS2015 to a RHEL 7 machine and built a Docker image.
I have been manually copying over dependencies from my Windows machine which was fine up until:
`Error: assembly specified in the dependencies manifest was not found -- package: 'System.Net.WebSockets', version: '4.0.0', path: 'lib/netstandard1.3/System.Net.WebSockets.dll'`
I have copied this to 

> /Release/lib/netstandard1.0/

 as specified but the dependency is not being read.

Any help would be greatly appreciated if anyone else has resolved a similar issue.

**Comment by moozzyk** [comment]
Likely you published your application to use a shared runtime and you don't have it installed on the target machine. You either need to install the runtime or publish the application as standalone so that it contains all dependencies it needs.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
