### ISSUE TITLE
.net web api from vs2017 iisexpress localhost to android simulator like gennymotion

### ISSUE THREAD

**Issue by malathiputtaiah** [aspnet/Home#2087]
Can we get a detailed help for this scenario, as it is simply not solved. It is something got to do with iisexpress for sure. The solutions i have seen is on earlier versions of vs2017 or wamp or linux but not with iisepress .net core api vs2017. Test in this case and only then suggest please.

**Comment by Tratcher** [comment]
gennymotion Have you tried these?
https://stackoverflow.com/questions/20257266/how-to-access-localhost-from-a-genymotion-android-emulator
https://stackoverflow.com/questions/1261975/addressing-localhost-from-a-virtualbox-virtual-machine

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
