### ISSUE TITLE
MachineKey's are they gone or aren't they?

### ISSUE THREAD

**Issue by Shazwazza** [aspnet/Home#209]
Hi, i was under the impression that MachineKey's were going to be a thing of the past with ASP.Net 5... I was doing some research for a blog post I am writing and came across this comment:

https://github.com/aspnet/Security/blob/master/src/Microsoft.AspNet.Security.Cookies/CookieAuthenticationOptions.cs#L129 

which says that the ISecureDataFormat will be based on a machine key.

Can anyone explain how cookie (and passwords for that matter) will actually be encrypted/decrypted and work between multiple servers and whether the machine key is still a thing or not?

**Comment by davidfowl** [comment]
http://docs.asp.net/en/latest/security/data-protection/index.html
