### ISSUE TITLE
Facebook login with multiple scopes results in "The oauth state was missing or invalid" error

### ISSUE THREAD

**Issue by carol-braileanu** [aspnet/Home#2090]
Hello everyone,

We have the following login scenario: our public website needs to allow Facebook login using only the public_profile and email scopes. But our backend application also requires user_events and manage_pages scope. At application startup we register 2 providers:

```
                        app.UseFacebookAuthentication(new FacebookOptions
                        {
                            AuthenticationScheme = "Facebook::Web",
                            SignInScheme = "Identity.External", // this is the name of the cookie middleware registered by UseIdentity()
                            ClientId = ***,
                            ClientSecret = ***,
                            SaveTokens = true,
                            DisplayName = c.DisplayName,
                            
                        });
  app.UseFacebookAuthentication(new FacebookOptions
                        {
                            AuthenticationScheme = "Facebook::Admin",
                            SignInScheme = "Identity.External", // this is the name of the cookie middleware registered by UseIdentity()
                            ClientId = ***,
                            ClientSecret = ***,
                            SaveTokens = true,
                            Scope = { "user_events,manage_pages" },
                            DisplayName = c.DisplayName,
                            
                        });

```

When trying to login with the Facebook::Web client everything works fine, however, however, the Facebook::Admin client throws this:
`AggregateException: Unhandled remote failure. (The oauth state was missing or invalid.)`

Reading around I realized that this is probably caused by the fact that I add the same Facebook authentication middleware twice, so the first middleware probably interferes with the second one. 
I have also tried to find a way to modify the properties of the client before redirecting the user to the external login page (ie: change scope).

How can I handle this situation? Ideally there should only be a single Facebook middleware registered, and I should be able to alter the requested scopes at runtime in some way.

**Comment by Tratcher** [comment]
Shouldn't that be `Scope = { "user_events", "manage_pages" },`?

**Comment by Tratcher** [comment]
Make sure they're assigned unique callback paths:
https://github.com/aspnet/Security/blob/df325deaf355f99239c1319932bc28eb3a837372/src/Microsoft.AspNetCore.Authentication.Facebook/FacebookOptions.cs#L24

**Comment by Tratcher** [comment]
RE: https://github.com/aspnet/Security/issues/990 for future work here.

**Comment by carol-braileanu** [comment]
Thank you Chris, I'll give it a try right away.

**Comment by carol-braileanu** [comment]
That worked perfectly, thanks! 👍
