### ISSUE TITLE
Porting from VS2015 to VS2017 problem with Package Microsoft.TestPlatform.ObjectModel

### ISSUE THREAD

**Issue by moliveto** [aspnet/Home#2093]
TSeverity	Code	Description	Project	File	Line	Suppression State
Error	NU1202	Package Microsoft.TestPlatform.ObjectModel 11.0.0 is not compatible with netcoreapp1.1 (.NETCoreApp,Version=v1.1) / win8-x64. Package Microsoft.TestPlatform.ObjectModel 11.0.0 supports:

net35 (.NETFramework,Version=v3.5)
portable-net45+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile259) InfinitasHotelProvider	D:\eBookingV4\src\InfinitasHotelProvider\InfinitasHotelProvider.csproj	1

**Comment by davidfowl** [comment]
There are newer versions of Microsoft.TestPlatform.ObjectModel that support .NET Standard. If you're trying to preserve the *exact* version, then it looks like the import statements in your project.json weren't properly ported to csproj.

Do you have your project file before and after the conversion?

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
