### ISSUE TITLE
Shake the tree from unused assemblies especially from a full .NET core build

### ISSUE THREAD

**Issue by mwpowellhtx** [aspnet/Home#2094]
I do not know if this was entered as a separate issue, and I don't have the time to scan dozens of issues (i.e. not knowing what I don't know). What I do know is that Damien mentioned it in the stand up this week, and it sounded like a grand idea deserving of attention. Basically to shake the tree of dependencies that you don't need in order to deliver only that which you need into a test or production environment. Thanks! If it's already been mentioned feel free to paste that issue link here and close this one out.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
