### ISSUE TITLE
Add ability to isolate and contain the .NET version at different levels

### ISSUE THREAD

**Issue by mwpowellhtx** [aspnet/Home#2095]
Something else Damien mentioned this week, for which Scott H. has probably already drawn up some specs, is the ability to identify the .NET version.

I would say, generically, "yes", at any or all levels. I think of ReSharper as an analogous use case, whereby I can set R# settings at whatever level, be they development environment, solution, project, and so on. And the appropriate behavior occurs. At minimum, I would think of projects in non-Core .NET dependencies today (i.e. VS2015); this is at project level, I think, yes?

Obviously something as sensitive as one's .NET framework dependencies needs careful extremely consideration; i.e. would it really make that much sense to isolate to different projects in a solution? Perhaps, if those bits were delivered into a wholely different (sub-)system and were just happily being maintained in the same solution umbrella.

Just word pictures out loud there.

Thanks again!

**Comment by davidfowl** [comment]
I'm not completely sure what this is asking for. What are you trying to do? Load multiple versions of .NET in the same process?

**Comment by mwpowellhtx** [comment]
No, not at all. We're talking about solution/project settings. However those elements are decomposed at the solution/project level, should be consistently approached.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
