### ISSUE TITLE
Lack of description for the dotnet.exe 

### ISSUE THREAD

**Issue by Rovastar** [aspnet/Home#2096]
not sure where to post this so posting in multiple locations.

Can we have a description for the dotnet.exe (for Windows)?
Currently it just shows up in Task Manger when running with no description and just displaying the exe name "dotnet"
A more meaningful description would be useful mentioning that this is the Core version and probably the version number in there. 
".NET Core runtime" or something.

**Comment by BrennanConroy** [comment]
File it here https://github.com/dotnet/cli/issues

**Comment by Rovastar** [comment]
Thanks for moving it for me.
