### ISSUE TITLE
Security Updating for .net core under Windows

### ISSUE THREAD

**Issue by Rovastar** [aspnet/Home#2097]
Are there any plans to integrate the security into Windows Update?

I need to rewrite my security and compliance procedures for now adding (asp).net core (Under windows) and with asp.net x.x it was included in Windows Update. 

If there are no plans at this time. What is the best way of being informed of security updates with this.

I subscribe to the Microsoft security bulletins but I didn't see any mention of previous security issues with (asp).net core version although I found issues 
https://blogs.msdn.microsoft.com/dotnet/2017/05/09/net-core-may-2017-update/
 
Could it be added to there too?
Microsoft Technical Security Notifications
https://technet.microsoft.com/en-us/security/dd252948.aspx

Or is there some other place for now?

**Comment by Tratcher** [comment]
@blowdart

**Comment by blowdart** [comment]
ASP.NET Core releases advisories, which are listed on the [MSRC advisory page](https://technet.microsoft.com/en-us/library/security/dn631936.aspx). which is what you already refer to. They are also mentioned in the [web tools blog](https://blogs.msdn.microsoft.com/webdev/), but the advisory & bulletins pages are the canonical resource.

We haven't had an issue serious enough to use Microsoft Update yet.

**Comment by Rovastar** [comment]
Cool.
I see them now on the MSRC page.

I am confused by your windows update comment though. 
Are you saying that all serious vulnerabilities will/should be addressed in Windows Update and procedures are in place? 

And 

Was a DOS not classed as serious enough issue?

https://technet.microsoft.com/library/security/4010983

**Comment by blowdart** [comment]
Windows Update is only for Windows

Microsoft Update is for everything else.

As we've had no Microsoft Update pushes so far you can assume that management didn't consider any of the vulnerabilities serious enough to use that mechanism. If management decides something is serious enough to use Microsoft Update then it will be used.

**Comment by Rovastar** [comment]
Sorry my mistake I did mean to say Microsoft updates.

I would expect procedures to be in place first though *before* issues occur. I am surprised this has not been considered I would have thought it would be a requirement for something like this for coming out of beta.

If a DOS is not classed as serious and I am sure what is......it would be for any other web technology.

Sorry to sound curt but the security procedures in place currently do not fill me with confidence

**Comment by blowdart** [comment]
The procedure IS in place at our end, it's just we've not used it.

The choice to use it is up to management and operational decisions, which are decided on a per case basis.

**Comment by Rovastar** [comment]
OK fair enough. I wanted to make sure that it is in place. There is very little information out there about this and what is happening about this and working in the realm of security it is important to understand what is in place.
(worse some third party security sites
https://tools.cisco.com/security/center/viewAlert.x?alertId=52461
seem to think that it was included in the updates.)

I still disagree with the operational and management discussions though about the severity of such things like a DOS from a malformed URL. I am not sure any security person would agree with that.
