### ISSUE TITLE
The specified CGI application encountered an error and the server terminated the process

### ISSUE THREAD

**Issue by nicksav** [aspnet/Home#2100]
Guys, time to time having this issue. 
Asp.Net Core 2 preview 1. I even can't find anything in logs. AI doesn't show up anything.
Attached is only thing I have got

[error.txt](https://github.com/aspnet/Home/files/1146800/error.txt)

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
