### ISSUE TITLE
Return forbidden without any authentication.

### ISSUE THREAD

**Issue by PMExtra** [aspnet/Home#2101]
Sometimes, we want to return the `HTTP 403 Forbidden ` in anonymous  web site. But the ASP.NET MVC doesn't allow it.

A typical scene:

I have a Web API project that use to access the blog posts (May be used with some front-end framework like Angular or React), and the API is just used to browse the posts without any thing about accounts or users.

But the posts has a limit switch that used to determine whether the post is public. If someone access a non-public post, I want to return the forbidden.

Now, the problem arises, in this scene, we don't need any `Authentication Middleware` likes `Microsoft.AspNetCore.Authentication.Cookies`, but the `System.InvalidOperationException` was threw, that said:

>  No authentication handler is configured to handle the scheme: Automatic

It's seems like the MVC framework is must have an authentication handler to process the `ForbiddenResult`, so why not let it be optional?

**Comment by Tratcher** [comment]
https://github.com/aspnet/Mvc/issues/6418
Forbid is part of the authentication system. There's a proposal to add Forbidden if you want the explicit status code. Or you can just use StatusCode(403).

**Comment by MaximRouiller** [comment]
@PMExtra 

I would explicitly return the HTTP code from your action. That is supported and should work as intended. 

In the case of blog posts that aren't published yet, I would highly recommend that you don't use 403 for resources that shouldn't exist yet. If a blog post hasn't been published yet, it does not exist for read-only client hence a 404 being more appropriate.

I could throw Darrel Miller in here but it's all about semantics. Blog posts don't need authentications. They are read-only and don't require your authentication middleware.

Drafts however, do require authentication and proper authorization to modify/view/publish. 

So let's summarize... you have `/posts/my-first-post` that is visible and don't require authorization. You have `/drafts/my-second-post` to access/edit your blog post and you could even have `/drafts/my-second-post/preview` to visualize it in the context of your blog.

Does that make sense?

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
