### ISSUE TITLE
Question: Why do asp.net core 2.0 VS 2017 templates still include bower which is already obsolete?

### ISSUE THREAD

**Issue by OnurGumus** [aspnet/Home#2102]
I am surprised to see ASP.net templates for VS 2017 still makes use of bower. Perhaps it's time to clean up obsolete stuff.

**Comment by davidfowl** [comment]
See https://github.com/aspnet/Home/issues/2086

**Comment by OnurGumus** [comment]
Thanks. I know you have a release to deliver but please reconsider your decision to keep bower any longer. I think keeping it any further will make more people to depend on it. And it will be difficult for you to clean it up later. Now is the perfect time imho.
