### ISSUE TITLE
aspnet core web application not running in iis

### ISSUE THREAD

**Issue by afsalcodehack** [aspnet/Home#2109]
The program '[12244] dotnet.exe' has exited with code -2147450749 (0x80008083).
The program '[6304] iisexpress.exe' has exited with code 0 (0x0).
and browser showing 

cannot reach this pageTry thisThis website might be marked as work-related by your organisation. Try to access this link in a new Microsoft Edge window outside of Windows Defender Application Guard.Make sure that you’ve got the right web address:  http://localhost:33831

i did not make any change in project from the default template using visual studio community edition 2017

**Comment by Tratcher** [comment]
And if you run it under the debugger or enable logging, do you see an exception?

**Comment by afsalcodehack** [comment]
Not even debugging just exiting iis and same error as before

public class Startup
    {
        // This method gets called by the runtime. Use this method to add services to the container.
        // For more information on how to configure your application, visit https://go.microsoft.com/fwlink/?LinkID=398940
        public void ConfigureServices(IServiceCollection services)
        {
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
        {
            loggerFactory.AddConsole();

            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            //app.UseStaticFiles();

            app.Run(async (context) =>
            {
                await context.Response.WriteAsync("Hello World!");
            });
        }
    }


public class Program
    {
        public static void Main(string[] args)
        {
            var config = new ConfigurationBuilder()
                .Build();

            var builder = new WebHostBuilder()
                .UseContentRoot(Directory.GetCurrentDirectory())
                .UseConfiguration(config)
                .UseStartup<Startup>()
                .UseUrls("http://localhost:5001")
                .UseIISIntegration()
                .UseKestrel(options =>
                {
                    if (config["threadCount"] != null)
                    {
                        options.ThreadCount = int.Parse(config["threadCount"]);
                    }
                });

            var host = builder.Build();
            host.Run();

        }
    }

**Comment by Tratcher** [comment]
Then enable standard out logs: https://docs.microsoft.com/en-us/aspnet/core/hosting/aspnet-core-module

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
