### ISSUE TITLE
How can I provde a *.all package like Microsoft.AspNetCore.All

### ISSUE THREAD

**Issue by hughzzq** [aspnet/Home#2110]
Hi,

I notice Asp.Net Core 2.0 provides a veriy convenient feature that a Net Core project only need add one single package "Microsoft.AspNetCore.All".
I wonder is it possible and how that I create .all package for my packages like "Microsoft.AspNetCore.All".

**Comment by markrendle** [comment]
The source for that package is in [the MetaPackages repo](https://github.com/aspnet/MetaPackages/tree/dev/src/Microsoft.AspNetCore.All).

**Comment by natemcmaster** [comment]
This feature is called the "runtime store" and not exclusive to web stack (ASP.NET). You can use it with any .NET Core 2.0 application. The best doc I could find for this is in the design notes: https://github.com/dotnet/core-setup/blob/master/Documentation/design-docs/DotNetCore-SharedPackageStore.md.

I'm going to close as this repo isn't the right place for runtime store issues. I'd recommend https://github.com/dotnet/sdk instead if you have further questions.
