### ISSUE TITLE
Routing handling with '+' in content

### ISSUE THREAD

**Issue by JeanCollas** [aspnet/Home#2111]
I am facing a routing issue, I have a route defined like this:

``"/Test/{words}/{type:regex(^(AA|BB|CC)$)}/{search2}"``

with parameters of the function being (string[] words, string type, string search2)

Tested with different URLS:

* ``/Test/word1+word2/AA/blablabla`` => 404
* ``/Test/word1%20word2/AA/blablabla`` => Ok, words={"word1 word2"}
* ``/Test/word1,word2/AA/blablabla`` => Ok, words={"word1","word2"}

I don't understand the 404? I would either have expected a translation of the '+' into a space or kept the '+'.

I posted this on stackoverflow, but at it seems to me like a bug, I also posted here.
https://stackoverflow.com/questions/45278082/handling-in-asp-net-core-routes

**Comment by danilobreda** [comment]
As i answered your question on stackoverflow website... You must encode a space; it is correct to encode a space as +, but only in the query string; in the path you must use %20. For + you can use %2b. (Http 1.1)

**Comment by JeanCollas** [comment]
Ok, thanks for the clarifications, I understand better why sometimes I get + other %20. However is '+' not correct as an URL character? That is what I am concerned about :|

**Comment by danilobreda** [comment]
'+' is know as a reserved character, there are: ";" "/" "?" ":" "@" "&" "=" "+" "$" ","... this means that these characters are used in a URL, meaningful within a URL context, separating components from each other. Thats why it need to be URL-enconded.
If a part of a URL (such as a query parameter), is likely to contain one of these characters, it should be escaped before being included in the URL.

**Comment by JeanCollas** [comment]
Ok thanks for the clarification, my mistake then.
