### ISSUE TITLE
Cannot open TCP and UDP firewall ports on Azure for my NETCore server app.

### ISSUE THREAD

**Issue by netsfx** [aspnet/Home#2112]
It seems there is no option to host NETCore or asp.net Core apps that need to listen to TCP/UDP traffic on Azure. Deloyed as Azure App Service, clients cannot connect to private TCP/UDP ports like 55555.

Azure Cloud Service/Webrole seems not to be available for NETCore/asp.net Core.

So how can I deploy my asp.net Core app, that needs to be reached at http:80, https:/443, TCP:55556, UDP:55555 to Azure?

Has that been 'forgotten'?

**Comment by juho-hanhimaki** [comment]
You can run ASP.NET Core on full .NET Framework.

Alternatively you can install .NET Core to cloud services the same way you can install for example newer .NET Framework versions (requires some script I believe).

**Comment by davidfowl** [comment]
> You can run ASP.NET Core on full .NET Framework.

Running on .NET Framework won't help.

> Alternatively you can install .NET Core to Azure Cloud Services the same way you can install for example newer .NET Framework versions or other executables (requires some script I believe).

Right, you can't open random ports on Azure App Service. You need to use Virtual machines or another form of deployment to azure.

**Comment by juho-hanhimaki** [comment]
> Right, you can't open random ports on Azure App Service.

But he was also talking about Azure Cloud Services / web roles which support custom ports.

**Comment by davidfowl** [comment]
Ah, I see. WebRoles don't native support ASP.NET Core like @juho-hanhimaki was saying. You'd need to install the ASP.NET Core Module using the windows server hosting bundle here https://www.microsoft.com/net/download/core#/runtime

**Comment by davidfowl** [comment]
Alternatively, you can use a worker role instead.

**Comment by netsfx** [comment]
I ported the app from net45. There, the TCP/UDP server was running in a Cloud Service/ worker role.
<WorkerRole name="MyServer" vmsize="Small">
    <Endpoints>
      <InputEndpoint name="UDP55555" protocol="udp" port="55555" />
      <InputEndpoint name="TCP55556" protocol="tcp" port="55556" />
    </Endpoints>
  </WorkerRole>

I believe, I could  have used a web role as well, only the ports really need to be opened.

Now, I have used the VS 2017 default asp.net core website template and spin up the tcp/udp servers before host.Run().

It works wonderful locally, it also works on azure as an App Service, only problem is the TCP/UDP traffic doesn't reach the app.:-(

**Comment by netsfx** [comment]
@davidfowl the problem is, when you create a new Cloud Service with a Worker Role or Web Role in VS2017 it creates a .net45 project, not a NETCore project. Also, I'd frame this more as an Azure problem, not as a problem with the program itself. The program runs fine on any Windows or Linux or Max, being a UDP, TCP, and HTTP server with NETCore and asp.net Core.
It just doesn't work with Azure, because the ports are blocked.

Also, if it was just a plain NETCore TCP/UDP server (without the http server/aspnet Corepart), how would you deploy that to Azure?

**Comment by davidfowl** [comment]
A virtual machine? Or container?

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
