### ISSUE TITLE
On vs 2017 15.3 Preview 6 the global.json is preventing my ASPNET Core project to load

### ISSUE THREAD

**Issue by masterjs** [aspnet/Home#2113]
Hello,
I'm trying to load my .NET Core 1.1 solution into VS 2017 15.3 preview 6.0. My global.json has the following content:
```
{
  "sdk": {
    "version": "1.0.0"
  }
}
```
When the solution is loading in VS, I get errors that it cannot load all my ASPNET Core projects. When I manually "re-load" them, it says 
> The SDK 'Microsoft.NET.Sdk.Web' specified could not be found

Now I finally found that to fix this, I need to comment out the content of my global.json. Any reasons why?

thank you,
JS

**Comment by natemcmaster** [comment]
Looks similar to https://github.com/aspnet/Tooling/issues/1044. Can you verify which dotnet is on your PATH and that you have the dotnet 1.0.0 SDK installed? Normally, dotnet will be in C:\Program Files\dotnet. You can find the sdks in C:\Program Files\dotnet\sdk\\$(version)\

**Comment by masterjs** [comment]
@natemcmaster my PATH has `C:\Program Files\dotnet\`. 
I have the following versions in the SDK folder:
```
1.0.0
1.0.0-preview2-003131
1.0.0-preview2-1-003177
1.0.0-preview4-004233
1.0.0-rc3-004530
1.0.0-rc4-004771
1.0.2
1.0.3
1.0.4
1.1.0-preview1-005051
1.1.0-preview1-005077
1.1.0-preview1-005098
2.0.0-preview2-006497
```

**Comment by natemcmaster** [comment]
@masterjs just to confirm. dotnet.exe is resolving from C:\Program Files\dotnet? Normally this error happens when you have put something else in PATH ahead of C:\Program Files\dotnet

**Comment by masterjs** [comment]
@natemcmaster this is working very well when I use the same solution with VS 2017 15.2. Could it still be related to the PATH?

**Comment by natemcmaster** [comment]
cc @nguerrera @mlorbetske - is this a known issue with the CLI SdkResolver in 15.3 preview 6.0?

**Comment by nguerrera** [comment]
It is not known. The fact that it works in 15.2 does not mean that it isn't a PATH issue because 15.2 does not use the sdks via a resolver 

Can you please check that there isn't another dotnet.exe which does not have v1.0.0 earlier in the PATH?

**Comment by masterjs** [comment]
Here's my PATH:
```
%SystemRoot%\system32
%SystemRoot%
%SystemRoot%\System32\Wbem
%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\
C:\Program Files\Microsoft SQL Server\120\Tools\Binn\
C:\Program Files\Microsoft SQL Server\130\Tools\Binn\
C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\
C:\Program Files (x86)\Microsoft Emulator Manager\1.0\
C:\Users\dev-tougje\AppData\Roaming\npm
%TFSPowerToolDir%
C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\
C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\
C:\Program Files\Microsoft SQL Server\130\DTS\Binn\
C:\Program Files (x86)\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\
C:\Program Files (x86)\Microsoft SQL Server\130\DTS\Binn\
C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\ManagementStudio\
C:\Program Files\Redis\
C:\Program Files\Git\cmd
C:\Program Files\dotnet\
C:\Program Files\Microsoft\Web Platform Installer\
C:\Program Files (x86)\Yarn\bin
C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\
C:\Program Files (x86)\Microsoft SQL Server\140\DTS\Binn\
C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\ManagementStudio\
C:\Program Files\nodejs\
```

**Comment by masterjs** [comment]
Also, in case it could be an issue with the new VS... my global.json is in the ROOT folder and my ASPNET CORE 1.1 projects are under ROOT\NETCORE\[the project name]

**Comment by masterjs** [comment]
Now if I specify to use my SDK **1.0.4** instead of **1.0.0**, it seems to work.... Not sure if it can help!

**Comment by nguerrera** [comment]
That looks right. 

Please put back the global.json then:
* Open VS 15.3 developer command prompt 
* set COREHOST_TRACE=1
* cd (your project directory)
* msbuild 2> trace.txt

Share trace.txt.

**Comment by nguerrera** [comment]
Missed the part about 1.0.4 working. I think VS has issues with an sdk older than that, but this is not how I expect it to manifest. Cc @srivatsn

**Comment by nguerrera** [comment]
Ah yes, we fixed sdk-to-sdk imports in 1.0.x. and so 1.0.0 can't be used with 15.3 and this is how it would manifest. We need to doc the minimum version to use in global.json with 15.3. And we need better diagnostics.

**Comment by masterjs** [comment]
@nguerrera  Perfect! I like this answer! tks! I'll let you decide when to close this issue. 

thank you,
JS

**Comment by aKabirKhan** [comment]
@nguerrera I am having the same issue. Just Installed VS 15.3 Enterprise Preview 6 and tried to open my sln which was working in vs 15.2, I don't have the global.json so where is the sdk version specified? I am stuck since I need the code analysis and hence using the preview version, 15.3 Preview 2 is working in one of my colleague's computer so it is specifically in this version of the VS 2017 Preview.

**Comment by aKabirKhan** [comment]
Any update on this...

**Comment by nguerrera** [comment]
@aKabirKhan Sorry for the delay. I somehow missed your earlier reply in my inbox and was out of the office yesterday. Can you share the following.

1. You're full PATH environment variable
2. The list of directories with version numbers as names in (directory of dotnet.exe on PATH)\sdk). e.g. `dir c:\Program Files\dotnet\sdk`
3. Follow [this](https://github.com/aspnet/Home/issues/2113#issuecomment-318434411) (ignore global.json part) and share the trace.txt

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
