### ISSUE TITLE
Respone Status 400 when cookie has national characters.

### ISSUE THREAD

**Issue by sbatykov** [aspnet/Home#2114]
Hello

When I do request that has cookie with national characters
` Cookie: _test=фыва
`
Program immediately return status 400 before any controllers trigger. And after, a controller trigger and generate its response to nothing.

I think it not right behavior. I have no capabilities to control response.

With regards, Stepan

**Comment by Tratcher** [comment]
This isn't specific to cookies, all headers are restricted to ascii.

**Comment by Tratcher** [comment]
https://github.com/aspnet/KestrelHttpServer/issues/1144

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
