### ISSUE TITLE
Bind a value on action parameter through route data

### ISSUE THREAD

**Issue by helderboone** [aspnet/Home#2117]
I know there's is a way through route data insert a value
```
public class Filter
{
     public override void OnActionExecuting(ActionExecutingContext context)
        {
            context.RouteData.Values["foo"] = "foo";         

            base.OnActionExecuting(context);
        }
}
```
Get this value on action:
```
    [ServiceFilter(typeof(Filter))]
    public class FooController : Controller
    {
        [HttpPost]
        public string Create(string id)
        {
            var fooValue = this.RouteData.Values["foo"];
            return fooValue;
        }
    }
```
I would like to bind this value directly on action parameter using the filter  but without to access the route data and assign the value to a variable as on the action above. For example:
```
  [ServiceFilter(typeof(Filter))]
    public class FooController : Controller
    {
        [HttpPost]
        public string Create(string id, string foo)
        {
            return foo;
        }
    }
```
Any thoughts?

**Comment by rynowak** [comment]
Route data only will be used to bind things that are strings or convertable from strings. 

Your example should work.

However, you don't need to use route data, in an action filter you have access to `context.ActionArguments` - you can just set the argument directly.

**Comment by helderboone** [comment]
@rynowak Thank you very much!. It worked out.
