### ISSUE TITLE
Problematic generated namespace with spaces in-between

### ISSUE THREAD

**Issue by maroonedsia** [aspnet/Home#2120]
[I'm not sure if this is an ASP.NET Core or Visual Studio scaffolding problem]

**Environment:**
- Windows 10 64-bits
- Visual Studio 15.2 (26430.15) Release

**Procedure to recreate problem:**
1. Create a new "ASP.NET Core Web Application (.NET Core)"
2. Name it "aspnet core", (with the space).
3. Use "Individual Users" authentication.
4. After the files are generated, open "Startup.cs"
5. The generated namespace has a space in between, Instead of '_'.
6. The code doesn't get compiled unless the namespace problem is resolved in all files.

I have tried other names with space in between, and they worked fine, if "aspnet core" is a placeholder/keyword that should be avoided, the New Project wizard should not let me proceed at first place.

**Comment by Tratcher** [comment]
@danroth27 https://github.com/dotnet/templating?

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
