### ISSUE TITLE
Browser link issue with ajax upload

### ISSUE THREAD

**Issue by JulienM28** [aspnet/Home#2122]
Hello,

I was doing some tuff with Jquery around ajax uploading of multiple files.

I hade some sweird things: Le oage reloaded just after the file transfert completed.

After a lot of search to understand what was going wrong in my code, I undestood the issue was  Browser Link.
after a little comment on this:
`app.UseBrowserLink();`

Everything worked fine.

Here is my code:

```
 $form.on('submit', function (e) {

        console.log('Submit form ' + fileNumber);
        if ($form.hasClass('is-uploading')) return false;

        $form.addClass('is-uploading').removeClass('is-error');

        if (isAdvancedUpload) {
            e.preventDefault();
            e.stopPropagation();
            var ajaxData = new FormData($form.get(0));

            var $input = $form.find('input[type="file"]');


            if (fileToUpload) { ajaxData.append($input.attr('name'), fileToUpload); }
            console.log('FileTo Upload: ' + fileToUpload);

            $.ajax({
                url: $form.attr('action'),
                type: $form.attr('method'),
                data: ajaxData,
                dataType: 'json',
                xhr: function () {
                    var myXhr = new XMLHttpRequest();
                    myXhr.upload.addEventListener('progress', function (e) { e.preventDefault(); progress(e); }, false);
                    return myXhr;
                },
                cache: false,
                contentType: false,
                processData: false,
                complete: function (xhr, status) {
                    $form.removeClass('is-uploading');
                    fileNumber++;
                    fileToUpload = droppedFiles[fileNumber];
                    if (fileToUpload) { $form.submit(); }
                },
                success: function (data, status, xhr) {
                    $form.addClass(data.success === true ? 'is-success' : 'is-error');
                    if (!data.success) $errorMsg.text(data.error);
                },
                error: function (xhr, status, error) {
                    console.log('error : ' + xhr.responseText);
                }
            });
        }
    });
```
Bye.

**Comment by jodavis** [comment]
@JulienM28 Can you provide a repro project where this occurs? There are a few things in your code sample that make it hard to reproduce, like your FormData type or the progress function. 

Also, do you have Web Essentials installed? The [Browser Reload on Save](https://marketplace.visualstudio.com/items?itemName=MadsKristensen.BrowserReloadonSave) extension in Web Essentials will detect certain file changes on disk and trigger reloads. That can be configured to ignore certain paths.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.

**Comment by JulienM28** [comment]
Yes I use Web essentials.
It may come from that. I'll test.

Thanks
