### ISSUE TITLE
WCF ClientBase Close method is private

### ISSUE THREAD

**Issue by timClyburn** [aspnet/Home#2123]
I have an existing nuget package that contains some WCF DataContracts, ServiceContracts and proxy classes that I am now attempting to migrate for use in a dotnetcore project in VS2017 (15.2 - 26430.16 release version).
In the code there is a base proxy class that implements ClientBase and IDisposable. The dispose method calls Close() on the ClientBase. It seems now that in assembly System.ServiceModel.Primitives Version=4.1.1.0, which ins installed through the nuget package System.ServiceModel.Primatives 4.3.0 has this as a private method.
Am I missing something here? Is there something else I need to do or another package that I need?

Thanks
Tim

**Comment by Tratcher** [comment]
Please move this issue to https://github.com/dotnet/corefx

**Comment by timClyburn** [comment]
Recreated in the correct area [https://github.com/dotnet/corefx/issues/23206](url)
