### ISSUE TITLE
Question: CookieAuthenticationOptions and AddCookie() in 2.0

### ISSUE THREAD

**Issue by zygimantas** [aspnet/Home#2128]
Previously we had an option to keep more complex cookie authentication configuration in a separate file (CookieAuthenticationOptionsSetup class), which was registered for DI like this:

```
services.AddSingleton<IConfigureOptions<CookieAuthenticationOptions>, CookieAuthenticationOptionsSetup>();
```

Right now, [recommended ](https://docs.microsoft.com/en-us/aspnet/core/migration/1x-to-2x/identity-2x#cookie-based-authentication)AddCookie() method expects lambda and CookieAuthenticationOptions is not injected at all. Is that a bug or it should be used differently?

```CookieAuthenticationOptionsSetup : IConfigureOptions<CookieAuthenticationOptions>``` pattern was very convenient and allowed to remove a big chunk of configuration noise from startup.cs

**Comment by davidfowl** [comment]
> Previously we had an option to keep more complex cookie authentication configuration in a separate file (CookieAuthenticationOptionsSetup class), which was registered for DI like this:

I believe that still works. I also believe you can use `IConfigureNamedOptions` to target a particular authentication scheme.

> Right now, recommended AddCookie() method expects lambda and CookieAuthenticationOptions is not injected at all. Is that a bug or it should be used differently?

There are overloads that don't anything. I don't see any recommendations that's just the migration guide.

/cc @HaoK

**Comment by HaoK** [comment]
You can still register your own custom IConfigureOptions, but as @davidfowl says, in 2.0, cookie authentication uses named options, if you only implement `IConfigureOptions`, that will only be configuring the Options.DefaultName authenticationScheme, implement `IConfigureNamedOptions` to control which authentication scheme you are configuring.

`services.AddSingleton<IConfigureNamedOptions<CookieAuthenticationOptions, CookieAuthenticationOptionsSetup>` 

should still work.  The main difference you might be running into is that you no longer can specify the authentication scheme in the options lambda itself.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
