### ISSUE TITLE
[fixed] Getting "Duplicate 'content' items were included" error when updating from 1.1 to 2.0

### ISSUE THREAD

**Issue by gsandorx** [aspnet/Home#2132]
Getting "Duplicate 'content' items were included" error when updating from 1.1 to 2.0. 

Windows machine, with VS 2017 15.3

I noticed that my .csproj file had:

`<ItemGroup>
    <Content Include="wwwroot\js\add-subscriptions.js" />
    <Content Include="wwwroot\js\appusers-dt.js" />`

I fixed the issue by manually changing the back slashes to forward slashes. This shouldn't be something users would have to manually fix, IMO.

**Comment by natemcmaster** [comment]
You can probably remove those lines of code altogether. VS may have added them automatically for you, but they should be unnecessary. Projects using Microsoft.NET.Sdk.Web have everything in  wwwroot in "Contents" by default:

Cref: https://github.com/aspnet/websdk/blob/rel-2.0.0/src/ProjectSystem/Microsoft.NET.Sdk.Web.ProjectSystem.Targets/netstandard1.0/Microsoft.NET.Sdk.Web.ProjectSystem.props#L28

**Comment by gsandorx** [comment]
I did, but I thought I'd report this "issue" here so that you guys can either put a fix or notify the VS team to remove or stop adding those extra lines that cause more harm than benefit with these 1.1 to 2.0 upgrades.

**Comment by Tratcher** [comment]
VS bugs are best reported directly through the VS feedback tool.
