### ISSUE TITLE
Cannot resolve Symbol in web layer

### ISSUE THREAD

**Issue by doublnt** [aspnet/Home#2133]
After I Migrate to .NET-Core 2.0. All my Project display error in web layer and show Cannot resolve symbol 'XX'. I can't figure it out ? Is my Visual Studio fault or ? 

Visual Studio Version ： 15.3.26730.3
ReSharper Version: 2017.1.3

**Comment by davidfowl** [comment]
Could be a resharper bug.

**Comment by doublnt** [comment]
Maybe Reshaper is still remember .net core 1.2 😭
