### ISSUE TITLE
Deploy to apache tomcat

### ISSUE THREAD

**Issue by apis3445** [aspnet/Home#2136]
Hi! I have a windows machine with tomcat 8.5, I install .net core 2.0, how I can deploy an asp .net core web api to the apache tomcat in windows?

**Comment by natemcmaster** [comment]
ASP.NET Core runs its own in-process web server. Sites running nginx, IIS, Apache, and others can reverse proxy their requests to the ASP.NET Core app.

Admittedly, I'm not an expert on configuring Tomcat. I suggest starting with [this guide](https://docs.microsoft.com/en-us/aspnet/core/publishing/apache-proxy), replacing Apache instructions with the Tomcat equivalent.

**Comment by davidfowl** [comment]
@apis3445 is there any reason you wouldn't just use IIS on windows?

**Comment by apis3445** [comment]
because exists other java applications and I want to run in linux

**Comment by odin88** [comment]
if the sole aim is to run on linux, use apache + kestrel or nginx + kestrel is a good choice.
if you still want to use tomcat, you might want to study on how to do a reverse proxy using tomcat

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
