### ISSUE TITLE
[feature requests] .NET Core 3.0 Roadmap Update,I hope to support web form cross platform

### ISSUE THREAD

**Issue by ghd258** [aspnet/Home#2138]
I hope to support web form cross platform, in China, a lot of net programmers to Java, I hope the rapid development of net
aspx Pages in ASP.NET Core
Can support the current web from ASPX page and the current controls

**Comment by ghd258** [comment]
Can support the current web from ASPX page and the current Web from controls

**Comment by ghd258** [comment]
Can support the Web from controls

**Comment by ghd258** [comment]
Can support the ASP.NET server control

**Comment by ghd258** [comment]
Do you support these
AntiXss
patterns & practices–Enterprise Library  
patterns & practices -Unity

**Comment by kwilliams-laneautomotive** [comment]
Microsoft has made it [pretty clear in documentation](https://docs.microsoft.com/en-us/dotnet/standard/choosing-core-framework-server#a-need-to-use-net-technologies-not-available-for-net-core) that they don't intend to bring Web Forms to ASP.NET Core.

Based on the number of legacy libraries you want brought forward, you are best continuing to use the full .NET Framework.

**Comment by Eilon** [comment]
There are currently no plans to port Web Forms to ASP.NET Core, so I'm closing this issue.
