### ISSUE TITLE
Does .NET Core 2.0 Support Dynamic Recompilation?

### ISSUE THREAD

**Issue by appsaleslover** [aspnet/Home#2139]
I'm completely new to .NET. I'm excited about the future of .Net with .Net Core. It seems like it can 1-up J2EE in no time.

QUESTION:
I've been reading about ASP.NET Dynamic Recompilation: https://msdn.microsoft.com/en-us/library/ms366723.aspx

Is the same supported in ASP.NET Core 2.0? I could not find any documentation anywhere?
For the changes to reflect, do you have to STOP & RESTART Kestrel or IIS with every change?

**Comment by Matthew-Bonner** [comment]
Razor template do dyanmically recompile upon first access after a change.

**Comment by appsaleslover** [comment]
Class file changes do require a server restart for changes to take effect. Correct? Same as ASP.NET "behemoth" Framework?

**Comment by natemcmaster** [comment]
> Class file changes do require a server restart for changes to take effect. Correct? 

Correct. Changes to your \*.cs files are not automatically picked up by the currently running server. They have to be recompiled into a new \*.dll file, which means you have to kill and restart the server process.

Side note: we built a tool called "dotnet watch" to automatically restart your server when a \*.cs file changes. See https://docs.microsoft.com/en-us/aspnet/core/tutorials/dotnet-watch

**Comment by appsaleslover** [comment]
Thanks!
