### ISSUE TITLE
Implementing Individual user accounts in local database in asp.net core 2.0 web API 

### ISSUE THREAD

**Issue by docesam** [aspnet/Home#2144]
When you make a new project in asp.net core 2.0 (web API template) you have choice to add authentication as "individual user accounts" but contrary to the web application template there is no "store user accounts in app" option.
it would be nice if user accounts for APIs could be stored in the local database mainly for intranet APIs so that the authentication will work regardless of the availability of internet connection.

**Comment by Tratcher** [comment]
@blowdart @HaoK

**Comment by blowdart** [comment]
That's almost on the list, but not so as you would recognise it. We generally don't recommend cookies with APIs as an auth mechanism, and until we have a replacement for a token service we can't bring back that option in the template. That work is currently ongoing.

If you wanted to start now you could look at using something like Identity Server to issue you a JWT token from user accounts in a local database.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.

**Comment by murbanowicz** [comment]
Any updates on that @blowdart @Tratcher ?

**Comment by Tratcher** [comment]
No

**Comment by ruffin--** [comment]
@blowdart Why wouldn't using cookies with APIs be recommended? It's [certainly possible to use Identity with WebAPI in ASP.NET Core](https://shellmonger.com/2015/06/02/asp-net-mvc6-identity-part-2-webapi/)... but is that insecure in some especially heinous way that would preclude offering it as an option for a project by default?
