### ISSUE TITLE
References to my projects yellow-triangled after adding COMReference

### ISSUE THREAD

**Issue by sm-g** [aspnet/Home#2146]
Working on windows 7 x64 in VS 15.3.1 with installed Core 2.0.0, I have project:
```xml
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net461</TargetFramework>
    <RuntimeIdentifier>win7-x64</RuntimeIdentifier>
    <NoWarn>$(NoWarn);1591;1573</NoWarn>
    <AssemblyName>MyService</AssemblyName>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="wwwroot\**\*;node_modules\**\*" />
    <ProjectReference Include="..\MyProj\MyProj.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore" Version="2.0.0" />
    <PackageReference Include="SoapCore" Version="0.7.0" />
  </ItemGroup>

  <PropertyGroup>
    <ServerGarbageCollection>true</ServerGarbageCollection>
    <ConcurrentGarbageCollection>true</ConcurrentGarbageCollection>
  </PropertyGroup>

  <ItemGroup Condition=" '$(TargetFramework)' == 'net461' ">
    <Reference Include="System" />
    <Reference Include="Microsoft.CSharp" />
  </ItemGroup>
</Project>
```

Compiles, runs.

Then I add (via Add Reference... dialog):
```xml
  <ItemGroup>
    <COMReference Include="QBFC13Lib.dll">
      <Guid>0cb030a6-7b72-42ce-b92a-849b4a4a2cfb</Guid>
      <VersionMajor>1</VersionMajor>
      <VersionMinor>0</VersionMinor>
      <WrapperTool>tlbimp</WrapperTool>
      <Lcid>0</Lcid>
      <Isolated>false</Isolated>
    </COMReference>
  </ItemGroup>
```
Right after that, "Dependencies>Projects" in Solution explorer disappeares. After reloading solution, it appreas, but all my projects (simple net461 dlls) has yellow triangle, code not compiles, VS says that there is no reference to my projects. 
After I remove COMReference, everything instantly become fixed (except that I need to reference that COM library).

**Comment by natemcmaster** [comment]
https://developercommunity.visualstudio.com is a better place for issues with the Visual Studio and the project system.

**Comment by sm-g** [comment]
Isn't this is about failing build when using core? I'm porting project from WCF, where everything works.

**Comment by sm-g** [comment]
If I build with msbuild I got same error as in VS

`error CS0246: The type or namespace name 'DAL' could not be found (are you missing a using directive or an assembly reference?)`

like references to project was not added.

**Comment by sm-g** [comment]
This may be related: COM dll is x86, but core project was `<RuntimeIdentifier>win7-x64</RuntimeIdentifier>`

**Comment by Eilon** [comment]
If there is still an issue with this, please file a new issue using Visual Studio's built-in feedback reporting tool (the icon in the upper-right of the window). That will ensure the feedback gets sent to the Visual Studio team. Thanks!

**Comment by sm-g** [comment]
That is not VS issue, but I already find workaround - do not use Com from aspnet core projects.
