### ISSUE TITLE
CS0234	The type or namespace name 'DirectoryServices' does not exist in the namespace 'System' (are you missing an assembly reference?)

### ISSUE THREAD

**Issue by AndyCreigh** [aspnet/Home#2147]
Hi,

The new core 2 directory services are described here https://docs.microsoft.com/en-gb/dotnet/api/system.directoryservices?view=netcore-2.0. I have the Core 2 SDK and Visual Studio 2017 v15.3.1 installed but can't reference the newly added directory services, **how do I install these**?

Steps to reproduce:

- In VS2017
- File - New - Project - Web - ASP.Net Core Web Application
- Choose Web Application (MVC), wait for packages to resolve.
- Edit Controllers - HomeController -Add using System.DirectoryServices; and the error is shown.

Thanks,
Andy

**Comment by davidfowl** [comment]
https://www.nuget.org/packages/System.DirectoryServices/

**Comment by smbecker** [comment]
That's not the official version. See https://github.com/dotnet/corefx/issues/2089

**Comment by AndyCreigh** [comment]
@smbecker  Thanks for the steer, I'll try the preview version.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
