### ISSUE TITLE
Deploy using KESTREL server only instead of IIS on Windows.

### ISSUE THREAD

**Issue by appsaleslover** [aspnet/Home#2148]
One thing I love about the Visual Studio for Mac is the kestrel server. It starts up super quick. Speeds up development times a TON.

So far I have not found a way to NOT USE IIS on Windows. Is it possible to force Kestrel server only deployment on Windows with Visual Studio 2017 (Community edition)?

**Comment by jkotalik** [comment]
I'm assuming you would like to run your application through visual studio. In visual studio, you can change the target by clicking the dropdown next to IIS Express to the name of your application. This, by default, will run Kestrel stand alone. If you would like to remove IIS Express as a launch options, in your launchSettings.json file (under properties), you can remove the IIS Express profile.

**Comment by simonmurdock** [comment]
It is possible to use kestrel. I'm doing it. Just no idea how from the top of my head

**Comment by appsaleslover** [comment]
It's so amazing! Yes, it works. Finally no more IIS! Now onto brainstorming ideas for a world-changing web app with mass-appeal!
