### ISSUE TITLE
Be able to determine which profile a package has matched on

### ISSUE THREAD

**Issue by avanderhoorn** [aspnet/Home#215]
As a developer, when I add a new package, when that package is resolved, I would like to know which profile that match resolved on. 

For instance, I just added RX to my project expecting it not to work for AspNetCore50 (as they don't have that profile yet), but it did match. I'm guessing that one of the PCL profiles must have been a catch for it, but have no idea for sure.

_This issue was raised after a discussion with @davidfowl on jabbr._

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
