### ISSUE TITLE
Custom result with 304 fails after migration to Asp.Net Core 2.0

### ISSUE THREAD

**Issue by hardhub** [aspnet/Home#2151]
If I will uncomment lines below (status code 304) then server returns nothing to browser...
It does not mean content... it means nothing: no response header, no http status code... only request header in dev tools.
I am sure it worked in previous version of Net Core, but not in 2.0.

```C#
public class ImageResult : FileContentResult
{
    //... some internal things here...

    public override async Task ExecuteResultAsync(ActionContext context)
    {
        string parsed = context.HttpContext.Request.Headers["If-None-Match"];

        string actual = WebEncoders.Base64UrlEncode(this.Image.Hash);

        context.HttpContext.Response.Headers["ETag"] = actual;

        //if (parsed == actual)
        //    context.HttpContext.Response.StatusCode = StatusCodes.Status304NotModified;

        await base.ExecuteResultAsync(context);
    }
}
```

**Comment by Tratcher** [comment]
@jbagga

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.

**Comment by jbagga** [comment]
@hardhub Apologies for not responding sooner. I missed the notification for this!

Are you still running in to this problem? Feel free to reopen the issue if you are, I am happy to investigate it. A small repro sample will be appreciated if you have it.

**Comment by hardhub** [comment]
I have changed behavior and found workaround.
