### ISSUE TITLE
Azure WebApp Deployment - ASP.NET Core 2.0 failing

### ISSUE THREAD

**Issue by grahamehorner** [aspnet/Home#2154]
Is ASP.NET Core 2.0 supported by Azure WebApp using WebDeploy? deployment of a simple template built web app fails? If not supported at present what is the timeline for Azure supporting ASP.NET Core 2.0 WebApp deployments?

**Comment by Michal7** [comment]
Which Azure region are you using for you webapp ?

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
