### ISSUE TITLE
Change IConfigureNamedOptions<OpenIdConnectOptions> to IOptionsMonitor<OpenIdConnectOptions>

### ISSUE THREAD

**Issue by Edward-Zhou** [aspnet/Home#2155]
I am implementing AddAzureAd in Asp.Net Core 2.0, for built-in code, it is like below:
```
        public static AuthenticationBuilder AddAzureAd(this AuthenticationBuilder builder, Action<AzureAdOptions> configureOptions)
        {
            builder.Services.Configure(configureOptions);
            builder.Services.AddSingleton<IConfigureOptions<OpenIdConnectOptions>, ConfigureAzureOptions>();
            builder.AddOpenIdConnect();
            return builder;
        }

```
Now, I want to dynamic load the configuration from appsettings.json, and I tried it like below:
```
        public static AuthenticationBuilder AddAzureADOpenIDAuthentication(this AuthenticationBuilder builder, IConfiguration configuration)
        {
            builder.Services.Configure<AzureAdOptions>(configuration.GetSection("AzureAd"));
            //builder.Services.AddSingleton<IConfigureOptions<OpenIdConnectOptions>, ConfigureAzureOptions>();
            builder.Services.AddSingleton<IOptionsMonitor<OpenIdConnectOptions>, AzureADOpenIdConnectOptionsSetup>();
            builder.AddOpenIdConnect();
            return builder;
        }
```
        public class AzureADOpenIdConnectOptionsSetup : IOptionsMonitor<OpenIdConnectOptions>
        {
            public OpenIdConnectOptions CurrentValue { get; set; }

            public AzureADOpenIdConnectOptionsSetup(IOptionsMonitor<AzureAdOptions> azureADOptions)
            {
                CurrentValue = new OpenIdConnectOptions();

                CurrentValue.ClientId = azureADOptions.CurrentValue.ClientId;
                CurrentValue.Authority = $"{azureADOptions.CurrentValue.Instance}{azureADOptions.CurrentValue.TenantId}" ;
                CurrentValue.CallbackPath = azureADOptions.CurrentValue.CallbackPath;
                CurrentValue.UseTokenLifetime = true;
                CurrentValue.RequireHttpsMetadata = false;
            }

            public OpenIdConnectOptions Get(string name)
            {
                CurrentValue.ConfigurationManager = new ConfigurationManager<OpenIdConnectConfiguration>(
                metadataAddress: CurrentValue.Authority + "/.well-known/openid-configuration",
                configRetriever: new OpenIdConnectConfigurationRetriever(),
                docRetriever: new HttpDocumentRetriever() { RequireHttps = false });
                CurrentValue.Validate();
                return CurrentValue;
            }

            public IDisposable OnChange(Action<OpenIdConnectOptions, string> listener)
            {
                throw new NotImplementedException();
            }
        }
It will throw error `InvalidOperationException: Provide Authority, MetadataAddress, Configuration, or ConfigurationManager to OpenIdConnectOptions`. After checking depth implementation of Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectOptions, this error throws by below code
```
public override void Validate()
{
	base.Validate();
	if (string.IsNullOrEmpty(this.ClientId))
	{
		throw new ArgumentException("Options.ClientId must be provided", "ClientId");
	}
	if (!base.get_CallbackPath().get_HasValue())
	{
		throw new ArgumentException("Options.CallbackPath must be provided.", "CallbackPath");
	}
	if (this.ConfigurationManager == null)
	{
		throw new InvalidOperationException(string.Format("Provide {0}, {1}, ", "Authority", "MetadataAddress") + string.Format("{0}, or {1} to {2}", "Configuration", "ConfigurationManager", "OpenIdConnectOptions"));
	}
}

``` 
But, I do not know how to set ConfigurationManager for OpenIdConnectOptions. My current code did not work.
Any help would be appreciated.

**Comment by Tratcher** [comment]
@HaoK

**Comment by HaoK** [comment]
@Edward-Zhou have you tried debugging to make sure that your AzureADOpenIdConnectOptionsSetup.Get method is being hit?

**Comment by HaoK** [comment]
Oh I think I see what the issue might be, so we rely on a PostConfigureOptions to intialize the ConfigurationManager by default, since you are plugging in your own IOptionsMonitor this is no longer getting setup, so you might need to copy the logic here:

https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNetCore.Authentication.OpenIdConnect/OpenIdConnectPostConfigureOptions.cs#L71

**Comment by Edward-Zhou** [comment]
Thanks

**Comment by jayslife** [comment]
I am getting the same error as Edward: 
`Unhandled Exception: System.InvalidOperationException: Provide Authority, MetadataAddress, Configuration, or ConfigurationManager to OpenIdConnectOptions
   at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectMiddleware..ctor(RequestDelegate next, IDataProtectionProvider dataProtectionProvider, ILoggerFactory loggerFactory, UrlEncoder encoder, IServiceProvider services, IOptions`1 sharedOptions, IOptions`1 options, HtmlEncoder htmlEncoder)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Extensions.Internal.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.Internal.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass3_0.<UseMiddleware>b__0(RequestDelegate next)
   at Microsoft.AspNetCore.Builder.Internal.ApplicationBuilder.Build()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()`

But this only occurs when trying to run my site from the command line via dotnet run. I also don't have a custom IOptionsMonitor.

Here is my 
`app.UseOpenIdConnectAuthentication(new OpenIdConnectOptions
            {
                AuthenticationScheme = "oidc",
                SignInScheme = "Cookies",

                Authority = baseUrl,
                //should be true in prod!
                RequireHttpsMetadata = false,

                ClientId = "customclient",
                ClientSecret = "secretissafewithme",

                ResponseType = "code id_token",
                Scope = {"api1", "offline_access"},
                GetClaimsFromUserInfoEndpoint = true,

                SaveTokens = true,

                TokenValidationParameters = new Microsoft.IdentityModel.Tokens.TokenValidationParameters
                {
                    NameClaimType = JwtClaimTypes.Name,
                    RoleClaimType = JwtClaimTypes.Role,
                },
                //UseTokenLifetime = true,
                Events = new OpenIdConnectEvents
                {
                    // Called when authentication is completed. This is the last event, assuming that authentication succeeds. 
                    // After this event is handled, the user is signed into the app.
                    OnTicketReceived = async trc =>
                    {
                        await Task.Run(() =>
                        {
                            // store both tokens in the claims/cookie.
                            var identity = trc.Ticket.Principal.Identity as ClaimsIdentity;
                            identity.AddClaims(new[]
                            {
                                new Claim("access_token", trc.Ticket.Properties.GetTokenValue("access_token")),
                                new Claim("refresh_token", trc.Ticket.Properties.GetTokenValue("refresh_token")),
                                new Claim("expires_at", trc.Ticket.Properties.GetTokenValue("expires_at")),
                            });

                            // cookie is good for multiple requests
                            trc.Properties.IsPersistent = true;
                            // set 12h expiration
                            trc.Properties.ExpiresUtc = DateTimeOffset
                                .Parse(trc.Ticket.Properties.GetTokenValue("expires_at")).AddHours(12);
                        });
                    },
                },
            });`
