### ISSUE TITLE
GenerateChangePhoneNumberTokenAsync is not generating an SMS-friendly token in ASP.NET Core 2.0

### ISSUE THREAD

**Issue by leodip** [aspnet/Home#2158]
In **ASP.NET Core 1.1**, if you call:

`var code = _userManager.GenerateChangePhoneNumberTokenAsync(user, "(21) 92345-7154");`

... you get back a token that is SMS-friendly, for example: "293688"

In **ASP.NET Core 2.0**, the same call returns a token that looks like:

"CfDJ8NlUtDo9xLxKnOBUmUICyLsPm6IFT3Xdp9OIBPwggxd2XdFiJxW+3x4DZf4sGlHhyXC4oPMgMVLzq0la6Di+cfWIwopZvzfMFkwx0ThBEOF4xxTVab2xwHSeW54GMxvjiEv9XFDCqjegpw/5y7iR7WiqtB6UNoIk0Hc6VGNkMxwROOuiEDFHy97e7flTDlVwTm9CiovkN3JQC+UDtoOCG+NXnsJ7l+aQ6mzF50aYsWqt8eT2GXhP1sKpD6P9RKuhKiu4Y0m7BBYW8jfE5EKgH4I="

You can't ask the user to type the above token to verify his phone number, because it's too long and complicated.

Is this a known bug?

Thanks

**Comment by Tratcher** [comment]
This issue was moved to aspnet/Identity#1388
