### ISSUE TITLE
ASP.NET Core support for WCF pass through Windows Authentication 

### ISSUE THREAD

**Issue by talynone** [aspnet/Home#2159]
I have a .NET Core class library which consumes the Microsoft MDS (Master Data Services) WCF service and authenticates via a explicitly specified username/pass with basicHttpBinding over SSL. I also have a ASP.NET Core Web API project which consumes this class library and exposes the data returned as JSON data back to the client. This all works fine.

I'm currently hard coding the user/pass in the WCF client class library and would like to instead use Windows Authentication through IIS to pass through the authenticated user to the WCF service.

I've setup IIS for Windows Auth, and the ASP.NET solution / Web.config for Windows authentication according to the documentation.

startup.cs ConfigureServices override:
```
services.Configure<IISOptions>(options => {
                //options.AuthenticationDescriptions holds a list of allowed authentication schemes
                options.AutomaticAuthentication = true;
                options.ForwardClientCertificate = true;                
            });
```

Web.config:
`<aspNetCore processPath="%LAUNCHER_PATH%" arguments="%LAUNCHER_ARGS%" stdoutLogEnabled="false" stdoutLogFile=".\logs\stdout" forwardWindowsAuthToken="true" />`

I'm attempting to authenticate against the WCF service using the following statement:
`service.ClientCredentials.Windows.ClientCredential = System.Net.CredentialCache.DefaultNetworkCredentials;`

The problem is no matter what combination of settings I try it always returns access denied. It works fine if I manually plug in the same user's user/pass manually. I can output User.Identity correctly in my controller and I've even tried wrapping the entire WCF login in RunImpersonated call:

```
var winIdent = user.Identity as WindowsIdentity;
WindowsIdentity.RunImpersonated(winIdent.AccessToken, () => _mdsClient.Login(loginRequest));

``` 
The same behavior is experienced using .NET Core 1.1.2 and 2.0 release versions. Is this scenario not supported? How do I pass through the logged in user?

**Comment by Tratcher** [comment]
This should help: https://github.com/dotnet/corefx/issues/9996

**Comment by talynone** [comment]
Thinks @Tratcher but this scenario is a little different, I'm not trying to pass through a trusted SQL connection, but a to a WCF login, which is a little different. I tried every tip in that thread already except running on full stack .NET.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
