### ISSUE TITLE
ForSqlServerToTable Missing from ModelBuilder

### ISSUE THREAD

**Issue by clockwiseq** [aspnet/Home#2160]
Just created my first .NET Core 2.0 project and upon attempting to rename my tables via the `.ForSqlServerToTable` method, I noticed it's missing.  Any idea where it may have gone?  Was this excluded from 2.0?  My example is below:

```
protected override void OnModelCreating(ModelBuilder builder)
{
    base.OnModelCreating(builder);
    builder.Entity<MyCustomEntity>().ForSqlServerToTable("MyCustomTableName");
}
```

**Comment by ajcvickers** [comment]
@clockwiseq Usually just call .ToTable instead. See https://github.com/aspnet/EntityFrameworkCore/issues/8923#issuecomment-310242378 "EF Core relational metadata API changes" for more details.

**Comment by clockwiseq** [comment]
Thanks for the info @ajcvickers , the only problem I have with all of this is how in the world are developers supposed to know or be informed of these breaking changes?

**Comment by joeaudette** [comment]
@clockwiseq the announcements repo readme has a link for each released version and its breaking changes
https://github.com/aspnet/Announcements

**Comment by clockwiseq** [comment]
That's perfect!  Thanks so much @joeaudette and @ajcvickers
