### ISSUE TITLE
Oracle failed to connect

### ISSUE THREAD

**Issue by wahahaJack** [aspnet/Home#2167]
I downloaded Oracle.ManagedDataAccess's package in NuGet, but then quoted the yellow icon, compiled no error, and ran successfully. The application interrupt mode occurs when the method to open () is executed。--version .net core 2.0.0

**Comment by smbecker** [comment]
That package doesn't support .net core yet. I believe that won't be until end of the year.

**Comment by wahahaJack** [comment]
Do you support the call of SAP's RFC function?

**Comment by wahahaJack** [comment]
Do you support the call of SAP's RFC function?

**Comment by Eilon** [comment]
cc @ajcvickers @divega

**Comment by ajcvickers** [comment]
@wahahaJack I'm not aware of any work to specifically support this, but I don't know much about it. @divega?

**Comment by divega** [comment]
> Do you support the call of SAP's RFC function?

@wahahaJack can you provide more details about this? Is that a completely independent question from your original question on Oracle support? For Oracle, I can confirm what @smbecker said. Oracle has published the following document with their intentions for .NET Core support:

http://www.oracle.com/technetwork/topics/dotnet/tech-info/odpnet-dotnet-core-sod-3628981.pdf

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
