### ISSUE TITLE
Response.OnCompleted not fired AFTER the Response is sent

### ISSUE THREAD

**Issue by JeanCollas** [aspnet/Home#2170]
Using ASP.NET Core 2.0
A simple code like this shows the issue:

    public async Task<IActionResult> TestOnComplete()
    {
            Response.OnCompleted(async () =>
            {
                throw new Exception();
            });
    }

Response.OnCompleted is said to be invoked after the response is sent to the user, so the user should already have got the answer, whatever happens there.

https://github.com/aspnet/HttpAbstractions/blob/master/src/Microsoft.AspNetCore.Http.Abstractions/HttpResponse.cs#L75

>         /// <summary>
>         /// Adds a delegate to be invoked after the response has finished being sent to the client.
>         /// </summary>
>         /// <param name="callback">The delegate to invoke.</param>
>         /// <param name="state">A state object to capture and pass back to the delegate.</param>
>         public abstract void OnCompleted(Func<object, Task> callback, object state);

But this breaks the response. You can also set a breakpoint on the OnComplete action, the user will wait for the response until the breakpoint is passed.

This means that the OnCompleted is fired before the response is actually sent.

**Comment by Tratcher** [comment]
Which server? Kestrel? HttpSys? IIS/Express + Kestrel?

**Comment by JeanCollas** [comment]
IIS Express for the debugging, I haven't verified if it was the same on Full IIS+Kestrel.

            var host = new WebHostBuilder()
                .UseKestrel()
                .UseContentRoot(Directory.GetCurrentDirectory())
                .UseIISIntegration()
                .UseStartup<Startup>()
                .Build();

**Comment by Tratcher** [comment]
This issue was moved to aspnet/KestrelHttpServer#2035
