### ISSUE TITLE
Load custom assembly to ASP .NET Core 2.0 project

### ISSUE THREAD

**Issue by troncomputers** [aspnet/Home#2171]
Hi!
I'm trying to load custom assembly (nip24Library.dll). This is the C# API for finding companies by VAT Number in Poland. 
```
FileNotFoundException: Could not load file or assembly 'nip24Library, Version=1.3.1.0, Culture=neutral, PublicKeyToken=a3a1b0bb1b99a109'. Can not find the specified file.
```
VS added for me this entry to .csproj file
```
  <ItemGroup>
    <Reference Include="nip24Library">
      <HintPath>C:\OptimoKasiarz\OptimoKasiarz\bin\Debug\netcoreapp2.0\nip24Library.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>
```
It looks like the web app doesn't know where this file is. How can I solve this problem?

**Comment by Tratcher** [comment]
You should move this to https://github.com/dotnet/corefx.

**Comment by troncomputers** [comment]
This issue was moved to dotnet/corefx#23678
