### ISSUE TITLE
Core 2.0 SDK breaks InvokeAsync inheritance with "Could not find an 'Invoke' or 'InvokeAsync' method" error.

### ISSUE THREAD

**Issue by rjamesnw** [aspnet/Home#2172]
I always had this in my base View Component class:

```
        public virtual Task<IViewComponentResult> InvokeAsync()
        {
            ... etc ...
        }
```
That was all I needed to make things easier for me for my dozens of components.

Now in ALL my derived component classes, I'm being forced to do this:

```
        public override Task<IViewComponentResult> InvokeAsync()
        {
            return base.InvokeAsync();
        }

```
Now everything works as before.

This breaking change I don't see mentioned anywhere, so I assume someone just figured it best (faster?) to reflect on the top class without flattening the hierarchy?  Just want to confirm this is not an oversight. It complicates things now for me since I was creating a simple component framework where this was not required. I didn't want end users to have to think about this part (99.999% of the time it won't be needed in a derived class).

Thanks.

**Comment by Tratcher** [comment]
@rynowak

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
