### ISSUE TITLE
Rethink the 'fluent interface' API

### ISSUE THREAD

**Issue by Neme12** [aspnet/Home#2173]
All across ASP.NET Core, there are APIs that look like this:

```C#
WebHost.CreateDefaultBuilder(args).UseStartup<Startup>().UseEnvironment()...
app.UseDeveloperExceptionPage().UseBrowserLink().UseStaticFiles().UseMvc()
```

I was immediately surprised by this and wasn't sure whether these types are actually immutable or not, as that's the right thing to expect from these kind of APIs. It turns out they're not and these methods not only mutate the original object, but also return the same instance. This is by no means a good API design and I consider these methods really dishonest.

This style is usually used with immutable objects where methods don't modify the original instance but instead return a new one that has the changes I want, leaving the original one intact (like String, DateTime & ImmutableCollections). Returning an instance of the same type suggests that you need the new instance while the original one may be useless. I would never expect a method to return the same exact instance. And it is always a good idea to return void from a method that you only use for it's side-effects.

What exactly is the reasoning behind this decision? Is it just the saved semicolon? I would suggest that we don't borrow functional-like syntax without also borrowing functional semantics (especially in a language like C# where both paradigms are being used - for example Roslyn as a big example). It's misleading to say the least.

By the way, even though this feature saves you some characters in a few places, you still can't put everything on one line. It only gets you so far but after you need to do something a little more interesting, you have to fall back to regular statements anyway. You can't do conditional logic like this -
 you see this even in the default template because you want to make decisions about what to include based on the environment etc. But they still support this kind of style and it's often combined within the same method. That's beyond confusing.

I understand this may seem like a non-issue for someone who has always worked with mutable types, but that's not the only way C# is written today. It's really important to know the distinction and see what kind of thing you're dealing with just by looking at the code. This API may save you a few semicolons but is unintuitive and goes against some good general programming practises I know.

I would suggest that these methods return void (or making these config objects entirely immutable, which seems unlikely).

**Comment by chadwackerman2** [comment]
It's hipster API design gone amok. This was fashionable briefly, some people like it, as you may have noticed nobody can even figure out how to indent it.

And yes, if you spend any time thinking about it (as opposed to skimming over it in cutesy blog posts) it really doesn't make any sense. 

Trying to figure out what's gone wrong in the middle of a long chain of that nonsense when there's a helper method that's migrated between assemblies because the .NET Core kids are still playing hide-and-go seek with functionality, well, that's a real joy, too.

It ain't changing. Here's hoping they don't add more of it.

**Comment by kwilliams-laneautomotive** [comment]
> By the way, even though this feature saves you some characters in a few places, you still can't put everything on one line.

You aren't supposed to put it all on one line...the examples I see online all format each chained call onto a new line. This is from Microsoft's documentation on how to enable static file support:

`public static void Main(string[] args)
{
    var host = new WebHostBuilder()
        .UseKestrel()
        .UseContentRoot(Directory.GetCurrentDirectory())
        .UseIISIntegration()
        .UseStartup<Startup>()
        .Build();

    host.Run();
}`

That really isn't that bad. I remember what it was like before we had fluent code configuration for things like ORM mappings, ORM queries, project setup, and middleware. You might be right to complain, but just remember that the alternative before this was runtime parsed XML files. This isn't a step backwards, so the way to displace it is to suggest something better.

**Comment by Neme12** [comment]
It's not about formatting. It's not a step backwards but not forward either. It's a step that hasn't been thought out at all.

What's the alternative? This:

```C#
var host = new WebHostBuilder();
host.UseKestrel();
host.UseContentRoot(Directory.GetCurrentDirectory());
host.UseIISIntegration();
host.UseStartup<Startup>();
host.Build();

host.Run();
```

Is it really that bad just because you have to repeat 'host' a few times? Would you sacrifice good API design because of a few letters?

**Comment by davidfowl** [comment]
Thanks for the feedback. Realistically this isn't going to change, the good news is the pattern you suggest also works.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
