### ISSUE TITLE
Issue with encoded query string in URL

### ISSUE THREAD

**Issue by OWAProjects** [aspnet/Home#2174]
I'm having an issue with encoded ampersand (&) signs within a query string URL not being picked up by the MVC routing.

I have a URL sent via an email like so:

```
/Register/Confirm?userId=9ce93db9-9488-4bb3-975b-11bb9f44a43a%26code=zn0qHewNVpYQdQml50StPFrkUi5hu%2FuR7Nm2VvfFjdiLU7Go%2Ffp%2BHu7vQOMOhPqltYX2L%2Bi6sPk7JNsBxXvo2p0Fg4rDjTz9VRQRxE%2F9aL2drfjdru9QUhqaCL0YIZLsNsh0hb894N4kvC8n85ANfeopj9uYzwTtQFTM2WAi9tquUmpZ6vNQLzoMTxLxJoO%2B3
```
OR
```
/Register/Confirm?userId=9ce93db9-9488-4bb3-975b-11bb9f44a43a&amp;code=zn0qHewNVpYQdQml50StPFrkUi5hu%2FuR7Nm2VvfFjdiLU7Go%2Ffp%2BHu7vQOMOhPqltYX2L%2Bi6sPk7JNsBxXvo2p0Fg4rDjTz9VRQRxE%2F9aL2drfjdru9QUhqaCL0YIZLsNsh0hb894N4kvC8n85ANfeopj9uYzwTtQFTM2WAi9tquUmpZ6vNQLzoMTxLxJoO%2B3
```

Which both get recorded within the HTTP request log as:
```
/Register/Confirm?userId=9ce93db9-9488-4bb3-975b-11bb9f44a43a&code=zn0qHewNVpYQdQml50S
```

However with a controller route parameters like such OR a view model, it doesn't pick up the 'code' parameter.
```
[Route("/Register/Confirm")]
        public async Task<IActionResult> ConfirmEmail(string userId, string code)
```
I'd expect this to work however the entire value is dumped within userId and code is always empty. However if i use a url as such:

```
/Register/Confirm?userId=9ce93db9-9488-4bb3-975b-11bb9f44a43a&code=zn0qHewNVpYQdQml50S

```

as the direct request, no encoding on the ampersand (&) the request goes through fine, unfortunately this isn't do-able within an email link and I would expect the encoded version of this link to work fine as well..
What's going on here? This has only been happening since upgrading from AspNetCore RC 1 to Release 1.1.2.

**Comment by Tratcher** [comment]
Why are your ampersands escaped in the url? Escaped separators are supposed to be ignored when parsing, that's what allows them to be used in values.  The `&amp;` escaping doesn't make sense in a url, that's HTML escaping.

Are you showing the url as captured by a tool like fiddler?

**Comment by OWAProjects** [comment]
Hi Tratcher, I tried both URI escaping and HTML escaping but had the same result. I can see the capture from within Visual Studios debugging HTTP request however the encoding and ampersand is ignored and doesn't recognise the separate parameters. As I said before this used to work fine in RC so something has changed here? 

Originally we used to use the annotation of [FromUri] within the action parameters however I'm aware this has been removed in NetCore now and can no longer be used, this could be the source of change from my perspective.

How else am I suppose to handle URL strings coming via another source/email to pass parameters within my NetCore MVC project?

**Comment by Tratcher** [comment]
This is really a round trip problem. You need to send the url to the client as HTML, but get it back as a url. It's appropriate to use HTML escaping when you send it to the client. However, the client should be un-escaping that value and sending the raw `&` in the request url. Your real issue here is the client failing to un-html-escape the link text.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
