### ISSUE TITLE
Does not request meta api with https enabled

### ISSUE THREAD

**Issue by helderboone** [aspnet/Home#2180]
Hi guys!
I have asp.net core 1.1 with .net core 1.1 application.  I have deployed to ubuntu server 16.04 and set the following settings on `Startup.cs`
```
public void ConfigureServices(IServiceCollection services)
        {
            var mvc = services.AddMvc(opts =>
            {
                opts.Filters.Add(new RequireHttpsAttribute());
            });
        }
````
And
```
 public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
        {
            app.UseForwardedHeaders(new ForwardedHeadersOptions
            {
                ForwardedHeaders = ForwardedHeaders.XForwardedFor | ForwardedHeaders.XForwardedProto
            });
            var options = new RewriteOptions().AddRedirectToHttps();
            app.UseRewriter(options);
         }
```
It simply does not load the page but if i coment those lines:

`//opts.Filters.Add(new RequireHttpsAttribute());`
`//var options = new RewriteOptions().AddRedirectToHttps();`
`//app.UseRewriter(options);`

It loads correctly the page.
So i need those settings because i have a meta api controller:
```
    [ServiceFilter(typeof(ApiAuthFilter))]
    [Route("api/v1/[controller]")]
    [Produces("application/json")]
    public class MetaController : Controller
```
When i try to make a request it does not answer either https enabled or disabled.
Any help guys?

**Comment by Tratcher** [comment]
UseForwardedHeaders is likely not working for you. Can you share the request headers as received by the server? Wireshark should help you capture them.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
