### ISSUE TITLE
ASP .NET Core 2 MVC error NU1202 creating project on VS 2017 and NET CLI

### ISSUE THREAD

**Issue by macoratti** [aspnet/Home#2181]
To address your issues more quickly, please open the issue in the most appropriate repository. These are some of the most common repos:

Common ASP.NET and Entity Framework repos and projects:

 - Documentation: https://github.com/aspnet/Docs
 - MVC: https://github.com/aspnet/Mvc
 - Entity Framework Core: https://github.com/aspnet/EntityFramework
 - Entity Framework 6: https://github.com/aspnet/EntityFramework6
 - SignalR: https://github.com/aspnet/SignalR
 - ASP.NET Core in Docker: https://github.com/aspnet/aspnet-docker
 - Microsoft.NET.Sdk.Web: https://github.com/aspnet/websdk
 - Kestrel HTTP Server: https://github.com/aspnet/KestrelHttpServer
 - ASP.NET Katana: https://github.com/aspnet/AspNetKatana
 - and more! See a full list here: https://github.com/aspnet

Other common projects:

 - NuGet: https://github.com/NuGet/home
 - .NET Core CLI, SDK, or runtime: https://github.com/dotnet/core
 - Visual Studio: https://developercommunity.visualstudio.com
 - Visual Studio Code: https://github.com/microsoft/vscode
 - Omnisharp (C# support for VS Code): https://github.com/omnisharp/omnisharp-vscode

**Comment by macoratti** [comment]
I have installed VS2017 15.3.0 and .NET Core 2.0 and have created a  default Web MVC application on VS 2017 and I got the following errors:     
Error NU1202  Package System.Threading.Overlapped 4.0.1 is not   compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package   System.Threading.Overlapped 4.0.1 supports: netstandard1.3   (.NETStandard,Version=v1.3)                Error  NU1202  Package   System.IO.Compression 4.1.0 is not compatible with netcoreapp2.0   (.NETCoreApp,Version=v2.0). Package System.IO.Compression 4.1.0   supports:     - monoandroid10 (MonoAndroid,Version=v1.0)     - monotouch10 (MonoTouch,Version=v1.0)     - net45 (.NETFramework,Version=v4.5)     - netcore50 (.NETCore,Version=v5.0)     - netstandard1.1 (.NETStandard,Version=v1.1)     - netstandard1.3 (.NETStandard,Version=v1.3)     - portable-net45+win8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile111)     - win8 (Windows,Version=v8.0)     - wpa81 (WindowsPhoneApp,Version=v8.1)     - xamarinios10 (Xamarin.iOS,Version=v1.0)     - xamarinmac20 (Xamarin.Mac,Version=v2.0)     - xamarintvos10 (Xamarin.TVOS,Version=v1.0)     - xamarinwatchos10 (Xamarin.WatchOS,Version=v1.0)  

The same errors occours using NET CLI with the command: dotnet new mvc  

I've tried update nuget: Install-Package NuGet.CommandLine -Version 4.3.0   

But it doesn´t works.  

So I have dotnet core2 installed, with Visual Studio 2017 with update 15.3.0 and NuGet 4.3.0  

What am I missing here?

**Comment by hgrewa** [comment]
I am having the same issue on my installation for VS2017. Were you able to address it?

**Comment by mmunnis** [comment]
I am also having the same issue.

**Comment by hgrewa** [comment]
What worked for me was
- created an empty web .core project (nuget restore failed due to above issues)
- nuget manager -> removed Microsoft.AspNetCore.All (Note that I had issues removing it, I had to remvove, save project, close and restart VS. )
- nuget manager -> reinstall Microsoft.AspNetCore.All

That is all. It worked for me for this and all other core projects.

**Comment by lostllama** [comment]
@hgrewa Thank you so much! That solved my problem in an instant.

**Comment by nakinnubis** [comment]
thanks saved me too @hgrewa

**Comment by Eilon** [comment]
Closing because it doesn't look like any further action is required on this issue.

I also found a related post on StackOverflow with a proposed solution: https://stackoverflow.com/a/46876615/31668
