### ISSUE TITLE
Unhandled exception in vendor.js while lunching asp.net core 2.0 project with angular 4.0 UI template in VS 2017

### ISSUE THREAD

**Issue by KadjiO** [aspnet/Home#2184]
Hello,

I started a new ASP.NET core 2.0 project with angular 4.0 template. I'm getting the following exception in vendor.js when just trying to view the default home page. The error is below:

**Unhandled exception at line 33893, column 5 in http://localhost:2198/dist/vendor.js?v=9ctzbS0ikla4GoIO8m21qp805HAfs2-bXTOOGaEjQS0
0x800a138f - JavaScript runtime error: Unable to get property 'apply' of undefined or null reference occurred**

This is beeing the default scaffolded application, i would expect it to just work.
Any comment will be highly appreciated.

Best

kadji

**Comment by KadjiO** [comment]
Ignored for now

**Comment by ManfredLange** [comment]
If you run into this issue, this [link](http://kosmisch.net/Blog/DotNetEssential/Archive/2017/5/20/issue-unable-to-get-property-apply-of-undefined-or-null-reference-occurred-in-angular-4-vs2017-153-aspnet-core-20.html) (retrieved 16 Oct 2017) may be helpful.
