### ISSUE TITLE
Question : how to manually run aspnet core process ?

### ISSUE THREAD

**Issue by valeriob** [aspnet/Home#2185]
Hi,
i created an aspnetcore web app running on .net framework 4.6.
When i run it in Visual studio it correctly binds in the configured port, es "http://localhost:64762/" and all works. If i run the exe myself it binds on port 5000 and does not find any view : 
What magic is vs using to pass what to the process ? how can i do it manually ?
I tried with .UseUrls("http://localhost:64762/") and it now binds on the correct port, but i can't make it find any view even with  .UseWebRoot("./wwwroot")

Thanks

![image](https://user-images.githubusercontent.com/1522516/30027949-56b3f048-9183-11e7-8ff7-d4a61acfb2fd.png)

**Comment by davidfowl** [comment]
The content root is the project folder when you run visual studio. It defaults to the current working directory VS changes that to the project folder when you run it. When you double click the exe in the output folder, it can't find the views because they haven't been published.

**Comment by valeriob** [comment]
Thanks @davidfowl,
so if i run this from the project folder it works .\Bin\Debug\net461\OnRtls.Web.exe
