### ISSUE TITLE
Performance issue with .net core

### ISSUE THREAD

**Issue by chintan3100** [aspnet/Home#2186]
I am downloading 400 MB file on local machine with 7 MB/Second (.net core 2.0) same code run with .net framework 4.6 download speed 100 MB/Second.

  public IActionResult DownloadDocument(Guid documentUniqueId)
        {
            var bytes = System.IO.File.OpenRead(@"D:\home\site\wwwroot\file\Organizer01_2017-09-03 (14) (3).zip");
            return File(bytes, "application/octet-stream");

}
 File size 400 MB .  API on local system. FIle on local system

**Comment by Tratcher** [comment]
Which server setup are you using? Kestrel + IIS/Express? Kestrel? HttpSysServer?

When you say .NET 4.6, was that ASP.NET Core running on .NET 4.6, or ASP.NET 4?

**Comment by chintan3100** [comment]
I am using kestrel + IIS.
I run above code with .net core with kestrel + IIS it give me 7 mb / second download speed.

Then I created new api with asp.net 4 it give 100- 150 mb/ sec download speed.

Some issue with .net core

**Comment by Tratcher** [comment]
Can you try it with just Kestrel?

**Comment by chintan3100** [comment]
I have tried with Kestrel but same. It gives same speed 7-10 mb/second

**Comment by chintan3100** [comment]
@tratcher can please try to reproduce issue

**Comment by Tratcher** [comment]
This issue was moved to aspnet/KestrelHttpServer#2058
