### ISSUE TITLE
Unable to run Aspnetcore 2.0 in docker in linux web app

### ISSUE THREAD

**Issue by yadavvineet** [aspnet/Home#2187]
I have created a linux web app. My web app is based on dotnetcore 2.0
i am using the docker image microsoft/aspnetcore-build:2.0
and startup file: dotnet /home/site/wwwroot/MyTestLib.dll

i always get Service Unavailable message. On analysing logs, i found out that application is looking for appsetings.json in / (ie parent dir)
`2017-09-05T22:11:25.671475226Z Unhandled Exception: System.IO.FileNotFoundException: The configuration file 'appsettings.json' was not found and is not optional. The physical path is '/appsettings.json'.
`
i tried multiple options but no resort. 
My Startup file is:
`public Startup(IHostingEnvironment env)
        {
            var builder = new ConfigurationBuilder()
                .SetBasePath(env.ContentRootPath)
                .AddJsonFile("appsettings.json", optional: false, reloadOnChange: true)
                .AddJsonFile($"appsettings.{env.EnvironmentName}.json", optional: true);

            if (env.IsDevelopment())
            {
                // For more details on using the user secret store see https://go.microsoft.com/fwlink/?LinkID=532709
                builder.AddUserSecrets<Startup>();
            }

            builder.AddEnvironmentVariables();
            Configuration = builder.Build();
        }
}
`
and Program.cs
`  public static IWebHost BuildWebHost(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .UseContentRoot(Directory.GetCurrentDirectory())
                .UseStartup<Startup>()
                .Build();`

i tried replacing the `.SetBasePath(env.ContentRootPath)` with `.SetBasePath("/home/site/wwwroot/")`.
This passed the first steps, but thereafter all the views are also looked in /VIews/* rather then /home/site/wwwroot/Views.

This seems to be a bug, but i could be wrong as well. Please check and suggest.

**Comment by yadavvineet** [comment]
Not an issue, configuration was faulty

**Comment by yadavvineet** [comment]
Hi, 
I have corrected the confguration. Configuration looks like below.Still, none of the configuration or DI is working. I guess the issue is with docker in linux only.  Also, tried removing the configuration lambda below, same result.
```
ublic static void Main(string[] args)
        {
            BuildWebHost(args).Run();
        }

        public static IWebHost BuildWebHost(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .UseStartup<Startup>()
                .ConfigureAppConfiguration((hostingContext, config) =>
                {
                    var env = hostingContext.HostingEnvironment;

                    config.AddJsonFile("appsettings.json", optional: true, reloadOnChange: true)
                        .AddJsonFile($"appsettings.{env.EnvironmentName}.json", optional: true, reloadOnChange: true);
                    if (env.IsDevelopment())
                    {
                        var appAssembly = Assembly.Load(new AssemblyName(env.ApplicationName));
                        if (appAssembly != null)
                        {
                            config.AddUserSecrets(appAssembly, optional: true);
                        }
                    }

                    config.AddEnvironmentVariables();

                    if (args != null)
                    {
                        config.AddCommandLine(args);
                    }
                })
                .Build();
    }
```

**Comment by yadavvineet** [comment]
problem is with docker image and content root path. 
Have to manually set the path. It does not fetch it automatically like for normal host env.

**Comment by muratg** [comment]
@yadavvineet What did you do to fix it exactly? (i.e. what file did you update?)

**Comment by h3smith** [comment]
Haven't upgraded to 2.0 yet but in 1.1 with Docker we did a call to `SetBasePath` to fix (what maybe the same) problem...

```
var builder = new ConfigurationBuilder()
.SetBasePath(Directory.GetCurrentDirectory())
...
```

**Comment by muratg** [comment]
@h3smith Thanks!

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
