### ISSUE TITLE
Error MSB3073 when publishing - project builds successfully.

### ISSUE THREAD

**Issue by sam-wheat** [aspnet/Home#2189]
When I run "dotnet build" my project builds just fine.  Here is the output:
Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:03.30

When I run "dotnet publish" I get a ton of errors, all of them apparently related to .csproj files (see errors below).

I also get the same errors when I try to publish on VSTS (see errors below).
I also get the same errors when I try to publish on VSTS (see errors below).

I've researched error MSB3073 which I get on my local machine and also on VSTS and I dont see anything that addresses my particular case.  My project uses Angular and Typescript but I do not use node (I do have the latest version of node and npm installed and npm is in my path).

Related:
[https://stackoverflow.com/questions/45764501/angular-dot-net-core-2-0-build-issue](https://stackoverflow.com/questions/45764501/angular-dot-net-core-2-0-build-issue)
[https://github.com/angular/angular-cli/issues/5364](https://github.com/angular/angular-cli/issues/5364)

dotnet --info
.NET Command Line Tools (2.0.0)

Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d
  
  
.csproj
```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp2</TargetFramework>
    <TypeScriptToolsVersion>2.3</TypeScriptToolsVersion>
  </PropertyGroup>

  <PropertyGroup>
    <AssetTargetFallback>$(AssetTargetFallback);portable-net45+win8+wp8+wpa81;</AssetTargetFallback>
  </PropertyGroup>

  <PropertyGroup>
    <UserSecretsId></UserSecretsId>
    <ApplicationInsightsResourceId>/subscriptions/1e75a10f-52e9-465d-91bb-91c5e52595f3/resourcegroups/Web/providers/microsoft.insights/components/Web</ApplicationInsightsResourceId>
    <ApplicationInsightsAnnotationResourceId>/subscriptions/1e75a10f-52e9-465d-91bb-91c5e52595f3/resourceGroups/Web/providers/microsoft.insights/components/Web</ApplicationInsightsAnnotationResourceId>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.0" />
  </ItemGroup>
  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="2.0.0" />
    <DotNetCliToolReference Include="Microsoft.Extensions.SecretManager.Tools" Version="2.0.0" />
    <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="2.0.0" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="node_modules\**" />
    <Content Remove="node_modules\**" />
    <EmbeddedResource Remove="node_modules\**" />
    <None Remove="node_modules\**" />
  </ItemGroup>
  <ItemGroup>
    <WCFMetadata Include="Connected Services" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="wwwroot\images\" />
  </ItemGroup>

</Project>
```
  
  
  

\Views\Account\Login.cshtml(27,84): error CS0411: The type arguments for method 'IModelExpressionProvider.CreateModelExpression<TModel, TValue>(ViewDataDictionary<TModel>, Expression<Func<TModel, TValue>>)' cannot be inferred from the usage. Try specifying the type arguments explicitly. [\Web.csproj]

\Views\Account\Login.cshtml(29,84): error CS0411: The type arguments for method 'IModelExpressionProvider.CreateModelExpression<TModel, TValue>(ViewDataDictionary<TModel>, Expression<Func<TModel, TValue>>)' cannot be inferred from the usage. Try specifying the type arguments explicitly. [\Web.csproj]

\Views\Account\Login.cshtml(30,96): error CS0411: The type arguments for method 'IModelExpressionProvider.CreateModelExpression<TModel, TValue>(ViewDataDictionary<TModel>, Expression<Func<TModel, TValue>>)' cannot be inferred from the usage. Try specifying the type arguments explicitly. [\Web.csproj]

\Views\Account\Login.cshtml(62,52): error CS1061: 'SignInManager<ApplicationUser>' does not contain a definition for 'GetExternalAuthenticationSchemes' and no extension method 'GetExternalAuthenticationSchemes' accepting a first argument of type 'SignInManager<ApplicationUser>' could be found (are you missing a using directive or an assembly reference?) [\Web.csproj] 
                                                                                                                                                                       
\Views\Account\Login.cshtml(63,21): error CS0019: Operator '==' cannot be applied to operands of type 'method group' and 'int' [\Web.csproj]

\Views\Account\Login.cshtml(77,59): error CS1579: foreach statement cannot operate on variables of type '?' because '?' does not contain a public definition for 'GetEnumerator' [\Web.csproj]

C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.aspnetcore.mvc.razor.viewcompilation\2.0.0\build\netstandard2.0\Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.targets(60,5): error MSB3073: The command ""C:\Program Files\dotnet\dotnet.exe" exec --runtimeconfig "\bin\Debug\netcoreapp2\Web.runtimeconfig.json" --depsfile "\bin\Debug\netcoreapp2\Web.deps.json" "C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.aspnetcore.mvc.razor.viewcompilation\2.0.0\build\netstandard2.0\Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.dll" @"obj\Debug\netcoreapp2\microsoft.aspnetcore.mvc.razor.viewcompilation.rsp"" exited with code 1. [\Web.csproj]

---------------------------------------------
Errors from Visual Studio Team Services:
---------------------------------------------

2017-09-05T13:36:17.0299132Z d:\a\1\s\Web.\Views\Account\Login.cshtml(62,52): error CS1061: 'SignInManager<ApplicationUser>' does not contain a definition for 'GetExternalAuthenticationSchemes' and no extension method 'GetExternalAuthenticationSchemes' accepting a first argument of type 'SignInManager<ApplicationUser>' could be found (are you missing a using directive or an assembly reference?) [d:\a\1\s\Web.\Web.csproj]

2017-09-05T13:36:17.0299132Z d:\a\1\s\Web.\Views\Account\Login.cshtml(63,21): error CS0019: Operator '==' cannot be applied to operands of type 'method group' and 'int' [d:\a\1\s\Web.\Web.csproj]

2017-09-05T13:36:17.0299132Z d:\a\1\s\Web.\Views\Account\Login.cshtml(77,59): error CS1579: foreach statement cannot operate on variables of type '?' because '?' does not contain a public definition for 'GetEnumerator' [d:\a\1\s\Web.\Web.csproj]

2017-09-05T13:36:17.0309141Z C:\Users\buildguest\.nuget\packages\microsoft.aspnetcore.mvc.razor.viewcompilation\2.0.0\build\netstandard2.0\Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.targets(60,5): error MSB3073: The command ""d:\a\_tool\dncr\2.0.0\x64\dotnet.exe" exec --runtimeconfig "d:\a\1\s\Web.\bin\release\netcoreapp2\Web.runtimeconfig.json" --depsfile "d:\a\1\s\Web.\bin\release\netcoreapp2\Web.deps.json" "C:\Users\buildguest\.nuget\packages\microsoft.aspnetcore.mvc.razor.viewcompilation\2.0.0\build\netstandard2.0\Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.dll" @"obj\release\netcoreapp2\microsoft.aspnetcore.mvc.razor.viewcompilation.rsp"" exited with code 1. [d:\a\1\s\Web.\Web.csproj]
2017-09-05T13:36:17.0419275Z ##[error]Error: d:\a\_tool\dncr\2.0.0\x64\dotnet.exe failed with return code: 1

**Comment by Tratcher** [comment]
@pranavkm

**Comment by pranavkm** [comment]
@sam-wheat the API changed as part of Identity 2.0 migration. See other discussions: https://github.com/aspnet/Identity/issues/1176, https://github.com/aspnet/Announcements/issues/232

**Comment by sam-wheat** [comment]
@pakrym Thanks pranavkm.  I am aware of the auth changes and I believe I addressed them when I migrated to .net core 2 (I do not have access to my code at this moment).  I am interested to know why my code builds but fails to publish?  Note my project builds on my local machine and also on VSTS. Prior to implementing the new Identity API my code would not build.

**Comment by pranavkm** [comment]
@sam-wheat you would see the same error when you access the view. Publishing in 2.0.0 results in view precompilation which is why you are seeing this error.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
