### ISSUE TITLE
asp.net core 2.0 ExceptionHanlder is not able to catch all server errors (5xx)

### ISSUE THREAD

**Issue by cyrusel** [aspnet/Home#2190]
I've created a new RazorPages web application with .net core 2.0 and configured app.UseExceptionHandler("/Error") to handle server errors. It works perfectly when i add throw new Exception manually on the page and it redirects to Error page. But for example when i put a Form with post method to let AntiForgeryToken generate and modify it's value to get an error (on purpose) default ie error 500 pages appears and ExceptionHandler doesn't catch it. Am i missing something? what should i do to catch such exception globaly? 
thanks MVPs

**Comment by pranavkm** [comment]
The Antiforgery filters in Mvc convert the exception to a 400 Bad Request. Are you sure there's an actual uncaught exception you are trying to work with?

**Comment by cyrusel** [comment]
Yup, I add some characters to _AntyForgeryToken hidden field and it returns internal server error (500) on post but ExceptionHandler doesn't catch it.

**Comment by cyrusel** [comment]
@pranavkm, any idea?

**Comment by pranavkm** [comment]
Sorry, missed this one. @rynowak would you know what might be happening here off the top of your head?

**Comment by Bojanema** [comment]
@pranavkm @rynowak  I have the same problem happening, has there been any progress on this?

@cyrusel have you been able to solve this problem in any way?

**Comment by Tratcher** [comment]
What errors show up in the logs for this scenario?

**Comment by Bojanema** [comment]
There is also another issue on this opened here:

https://github.com/aspnet/Mvc/issues/6678#issuecomment-347278138

**Comment by Eilon** [comment]
Indeed, I think https://github.com/aspnet/Mvc/issues/6678 covers this scenario.
