### ISSUE TITLE
Permission denied error while reading aws credentials on Amazon Linux

### ISSUE THREAD

**Issue by goforgold** [aspnet/Home#2192]
I am trying to access objects from S3 bucket for which I've set AWS credentials here at `/root/.aws/credentials` on my AWS EC2 (Amazon Linux AMI).

My application runs from ec2-user with sudo.

I tried changing ownership from root to ec2-user and vice-versa. I also tried setting permission to `777` for the whole `.aws` directory. But my application just can't read it with error permission denied.

Complete error message is:  
`System.UnauthorizedAccessException: Access to the path '/root/.aws/credentials' is denied. ---> System.IO.IOException: Permission denied`

Current permission for `.aws` directory  
`drwxrwxrwx  2 root root 4096 Sep 10 07:31 .aws`

Current permission for `credentials` file inside `.aws` directory:  
`-rwxrwxrwx 1 root root  112 Sep 10 07:18 credentials`

The setup works perfectly on my local system (windows).

**Comment by Eilon** [comment]
@goforgold is this issue better suited for Amazon EC2 support? It sounds like an issue with reading a remote object, no? Or if you can share more details of the stack trace that might help shed more light.
