### ISSUE TITLE
No service for type 'Microsoft.AspNetCore.Hosting.IHostingEnvironment' has been registered

### ISSUE THREAD

**Issue by mohammad-hth** [aspnet/Home#2194]
I have a problem when I want to fire add-migration command for an ASP MVC Core 2 project.

> No service for type 'Microsoft.AspNetCore.Hosting.IHostingEnvironment' has been registered.

[You can see more information in stackoverflow](https://stackoverflow.com/questions/46150730/asp-net-core-2-no-service-for-type-microsoft-aspnetcore-hosting-ihostingenviron)

**Comment by bricelam** [comment]
Well, I tried to point you in the right direction, but my answer got deleted... Here's the exact code you can copy and paste into your application.
``` csharp
public class DesignTimeDbContextFactory : IDesignTimeDbContextFactory<SampleArchContext>
{    
    public SampleArchContext CreateDbContext(string[] args)
    {
        var host = new WebHostBuilder()
            .UseKestrel()
            .UseContentRoot(Directory.GetCurrentDirectory())
            .ConfigureAppConfiguration((hostingContext, config) =>
            {
                var env = hostingContext.HostingEnvironment;
                config.SetBasePath(env.ContentRootPath);
                config.AddInMemoryCollection(new[]
                       {
                         new KeyValuePair<string,string>("the-key", "the-value")
                       })
                       .AddJsonFile("appsettings.json", reloadOnChange: true, optional: false)
                       .AddJsonFile($"appsettings.{env}.json", optional: true)
                       .AddEnvironmentVariables();
            })
            .ConfigureLogging((hostingContext, logging) =>
            {
                logging.AddDebug();
                logging.AddConsole();
            })
            .UseIISIntegration()
            .UseDefaultServiceProvider((context, options) =>
            {
                options.ValidateScopes = context.HostingEnvironment.IsDevelopment();
            })
            .UseStartup<Startup>()
            .Build();
            
        return host.Services.CreateScope().ServiceProvider.GetRequiredService<SampleArchContext>();
    }
}
```
If you follow the [guidance](https://docs.microsoft.com/en-us/aspnet/core/migration/1x-to-2x/#update-main-method-in-programcs) I pointed to and split the top half of your `Program.Main()` into a `BuildWebHost()` method, EF will do the rest for you (i.e. you could remove the custom `IDesignTimeDbContextFactory` implementation).

To directly answer you're question, you can't inject services into `IDesignTimeDbContextFactory`. It is a static entry point into the application (like `Program.Main()`) and the service container must be configured from scratch.

**Comment by bricelam** [comment]
I used my omnipotent SO privileges to undelete my answer and expand it a bit.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
