### ISSUE TITLE
ASP NET Core 2 Could not load assembly of a class library project

### ISSUE THREAD

**Issue by mohammad-hth** [aspnet/Home#2199]
In my solution, I have two projects. One of them is `web` project and the other one is `Model` project. You can see my solution structure in below:

![sln](https://user-images.githubusercontent.com/25346731/30518501-d429a106-9b94-11e7-8570-ee466b51d03b.png)

Now when I wanna run `Add-Migration` command in `Model Project` I get the following error message:

> Could not load assembly 'ContosoUniversity.Model'. Ensure it is referenced by the startup project 'ContosoUniversity'.

I remove `ContosoUniversity.Model` reference from `ContosoUniversity` web project and add it again but I still get the same error.

I use ASP NET Core 2 and VS17.

Here is my `Startup.cs` class if you need it:

    public class Startup
    {
        public Startup(IConfiguration configuration, IHostingEnvironment env)
        {
            Configuration = configuration;

            var builder = new ConfigurationBuilder()
            .SetBasePath(env.ContentRootPath)
            .AddJsonFile("appsettings.json", optional: true, reloadOnChange: true)
            .AddJsonFile($"appsettings.{env.EnvironmentName}.json", optional: true);

            Configuration = builder.Build();
        }

        public IConfiguration Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddDbContext<SchoolContext>(option => 
                option.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")));
            services.AddMvc();

        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
                app.UseBrowserLink();
            }
            else
            {
                app.UseExceptionHandler("/Home/Error");
            }

            app.UseStaticFiles();

            app.UseMvc(routes =>
            {
                routes.MapRoute(
                    name: "default",
                    template: "{controller=Home}/{action=Index}/{id?}");
            });
        }
    }

[you can see this question in stackoverflow
](https://stackoverflow.com/questions/46261109/asp-net-core-2-could-not-load-assembly-of-a-class-library-project)

**Comment by davidfowl** [comment]
Why is it an assembly reference instead of a project reference?

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
