### ISSUE TITLE
kpm pack misses some package dependencies on osx/linux

### ISSUE THREAD

**Issue by bgourlie** [aspnet/Home#220]
I'm in the process of deploying my asp.net vNext site built on os x (laptop) and linux (travis-ci) to azure.  The process is as follows:

  # pack deployment
  kpm pack --out ./deploy --no-source --runtime ~/.kre/packages/KRE-Mono.1.0.0-beta1
  
  # deploy via ftp
  find ./deploy -type f -exec curl --fail --ftp-create-dirs -T {} -u user:pass ftp://azure-deploy-dir/{} \;

These two steps successfully packs and deploys my app via FTP.  Viewing on azure results in an error saying that it can't find `KRE-CLR-x86.1.0.0-beta1`, which is expected.  I've manually copied this over from a windows machine and the error went away.  However, I'll get the following missing dependencies, respectively, until manually copying them as well:

- `System.ComponentModel.Annotations`
- `System.ComponentModel`

After doing this, everything works!

So, is it a bug that kpm pack isn't packaging the two aforementioned dependencies?  Additionally, is there a way to install `KRE-CLR-x86.1.0.0-beta1` on os x/linux so that it can be deployed with it?

**Comment by glennc** [comment]
Closing this in favor of https://github.com/aspnet/XRE/issues/840 since it's closer to the code.
