### ISSUE TITLE
[Question] - Support Asp.net core 1 and asp.net core 2 in single package?

### ISSUE THREAD

**Issue by dazinator** [aspnet/Home#2200]
Am I correct in thinking it's not currently possible to build a nuget package, that scopes its dependencies to the version of asp.net core being consumed in an application? For example if the nuget package is installed into an asp.net core 1.0 application it carries one set of dependencies, if its being installed into an asp.net core 1.1 application it carries another?

I know you can target tfm's but this doesn't really equate to asp.net core versions. For example you can have an aspnet core 1.0 application that targets `net46`.

If that is correct, is there anything in the pipeline that could help enable this?

The scenario is you want to develop a package that supports asp.net core 1.0, 1.1 and 2.0 but you don't want to have to have `Foo.Package.AspNetCore1` `Foo.Package.AspNetCore11` and `Foo.Package.AspNetCore20` because this is pain for both developers and consumers (when consumers upgrade their projects accross asp.net versions they have to locate and consume entirely new packages).

**Comment by davidfowl** [comment]
Not really no, the only pivot you have is the target framework (TFM). The closest you can get is using netcoreapp.

**Comment by dazinator** [comment]
Hmm ok thanks. Do you / do you not see this as a worthwhile problem to address? targeting netcoreapp doesn't really work because an asp.net core app might be targeting full net framework rather than netcoreapp..

**Comment by davidfowl** [comment]
It's not something that has really ever been solved in packaging ecosystems. Dependencies based on arbitrary pivots is a hard nut to crack. It's not really an ASP.NET problem, this is a general problem people have with nuget packages. This problem shows up more anytime any components makes a breaking change. 

> Do you / do you not see this as a worthwhile problem to address?

I don't think it's worth solving no.

**Comment by dazinator** [comment]
> I don't think it's worth solving no.

Interesting. It's very beneficial for the asp.net core team that they don't have to develop and maintain packages that will run on asp.net core 1, 1,1 and 2.0. I wish I was in that position... :-)

> Dependencies based on arbitrary pivots is a hard nut to crack

I don't think this pivot is..arbitrary .. The pivot is based on which version of a package the target project is currently consuming. If consuming `Microsoft.AspNetCore.Mvc 1.0.0` pivot to X if it's  `Microsoft.AspNetCore.Mvc 1.1.1` Pivot to Y etc. I think this concept could be formailised if there was a desire. You could for example allow a nuget package to add a `capability` (something I just made up) - i.e `MVC1` and then allow nuget packages to pivot on these capabilities present. The concept of capabilities is used in the VS Project System so perhaps thats why that sprang to mind. I'll suggest over on nuget.

**Comment by davidfowl** [comment]
Sure it doesn't change my stance on the problem, I don't think it's tractable and that's why it hasn't been solved. It'll just make nuget more complex and slower. 

FWIW you're thinking about a single package. Multiply that by versions and target frameworks and each package in the dependency graph.

That's my 2c.

**Comment by dazinator** [comment]
Yeah I agree - it is probably a pipe dream.. thanks for sharing your perspective. I raised it anyway over on nuget: https://github.com/NuGet/Home/issues/5901

> FWIW you're thinking about a single package. Multiply that by versions and target frameworks and each package in the dependency graph.

Yeah you are right I was thinking about installing a single package - namely mine. In terms of the algorithm that nuget uses to build package an entire dependency tree - well, yes! Although I imagine it already walks that tree in its entirety - in which case - collecting and filtering based on `capabilties` discovered along the way should be possible but would of course be an extra step - I couldn't honestly speculate how much slower that would make nuget but I don't see why it should result in such a mammoth slow down, especially if this feature is only used for fairly surface level packages. I will close this for now as like you say this sits more with nuget and not aspnet core!

Cheers ;-)
