### ISSUE TITLE
dotnet xxx.dll --urls not work

### ISSUE THREAD

**Issue by ahdung** [aspnet/Home#2201]
Env: win2k8r2, VS2017, dotnet core 2.0
![1](https://user-images.githubusercontent.com/12094247/30528805-e84141d8-9c68-11e7-8b11-839c68106bab.png)

**Comment by Tratcher** [comment]
This is a known issue. See https://github.com/aspnet/KestrelHttpServer/issues/1998 for a workaround.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
