### ISSUE TITLE
Unable to resolve service when adding services dynamically through reflection

### ISSUE THREAD

**Issue by pavlospap** [aspnet/Home#2209]
Hello everybody...

I'm using version 2.0 and I'm stuck with a strange issue with DI in one of my projects. Long story short I'm trying to dynamically add services (such as repository services) in my app through reflection using a base generic class so I won't have to create all those repository classes (one for every entity) and add all those implementations in my ConfigureServices method.

The entities live in many assemblies so I'm collecting entities from any assembly in current folder (all the types that inherit the base entity class), creating generic interface and implementation types on the fly and adding them to my services.

You can download a small test project which reproduces the issue : [TestDI.zip](https://github.com/aspnet/Home/files/1320144/TestDI.zip)

There are four assemblies in the test project:

Lib.Data with the base entity class:

```
// EntityBase.cs
namespace Lib.Data
{
    public abstract class EntityBase
    {
    }
}
```

App.Data with the only entity class:

```
// School.cs
using Lib.Data;

namespace App.Data
{
    public class School : EntityBase
    {
    }
}
```

Lib witch is where entities are collected and the repository generic classes live:

```
// IServiceCollectionExtensions.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using Lib.Data;
using Lib.Services;
using Microsoft.Extensions.DependencyInjection;

namespace Lib
{
    public static class IServiceCollectionExtensions
    {
        public static IServiceCollection AddRepositories(this IServiceCollection services)
        {
            var location = Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location);
            var types = new List<Type>();
            foreach (string file in Directory.GetFiles(location, "*.dll"))
            {
                types.AddRange(Assembly.LoadFile(file).GetTypes());
            }

            var entityTypes = from entityType in types
                              where entityType.IsSubclassOf(typeof(EntityBase)) &&
                                    !entityType.GetTypeInfo().IsAbstract
                              select entityType;

            foreach (var entityType in entityTypes)
            {
                var interfaceType = typeof(IRepository<>).MakeGenericType(entityType);
                var implementationType = typeof(Repository<>).MakeGenericType(entityType);
                services.AddScoped(interfaceType, implementationType);
            }

            return services;
        }
    }
}
```

```
// Servcices/IRepository.cs
namespace Lib.Services
{
    public interface IRepository<T>
    {
    }
}
```

```
// Servcices/Repository.cs
namespace Lib.Services
{
    public class Repository<T> : IRepository<T>
    {
    }
}
```

And, finally, the App assembly with the Startup class and the Seeder service which uses the one and only repository:

```
// Startup.cs
using App.Services;
using Lib;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.DependencyInjection;

namespace App
{
    public class Startup
    {
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddRepositories();
            services.AddScoped<IDataSeeder, DataSeeder>();
        }

        public void Configure(IApplicationBuilder app, IHostingEnvironment env, IDataSeeder seeder)
        {
            seeder.Seed();

            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.Run(async (context) =>
            {
                await context.Response.WriteAsync("Hello World!");
            });
        }
    }
}
```

```
// IDataSeeder.cs
namespace App.Services
{
    public interface IDataSeeder
    {
        void Seed();
    }
}
```

```
// DataSeeder.cs
using App.Data;
using Lib.Services;

namespace App.Services
{
    public class DataSeeder : IDataSeeder
    {
        public DataSeeder(IRepository<School> rep)
        {
        }

        public void Seed()
        {
            // seed db
        }
    }
}
```

If I add the service like this
```
//services.AddRepositories();
services.AddScoped<IRepository<School>, Repository<School>>();
services.AddScoped<IDataSeeder, DataSeeder>();
```
everything works fine. But when I'm trying to dynamically add them like in the test project I can see (at the end of the ConfigureServices) that the service is there 

![testdi](https://user-images.githubusercontent.com/13450530/30681942-47c8e18a-9eb0-11e7-85e0-90d53e425bf2.png)

but when the Configure method is executed I get the following exception:
> InvalidOperationException: Unable to resolve service for type 'Lib.Services.IRepository`1[App.Data.School]' while attempting to activate 'App.Services.DataSeeder'.

Any ideas?

**Comment by davidfowl** [comment]
I took a look at it looks like it's to do with assembly loading behavior:

```C#
foreach (string file in Directory.GetFiles(location, "*.dll"))
{
    // var asm = Assembly.LoadFrom(file);
    // var asm = Assembly.Load(AssemblyName.GetAssemblyName(file));
    var asm = Assembly.LoadFile(file);
    types.AddRange(asm.GetTypes());
}
```

If you change `Assembly.LoadFile` to `Assembly.LoadFrom` or `Assembly.Load` it works. I am a bit perplexed about this behavior on .NET Core though.

Any thoughts @jkotas? I thought the load context was always the same on .NET Core.

**Comment by davidfowl** [comment]
Hmmm seems not https://github.com/dotnet/coreclr/blob/94d374d22c1bb2b4815a05b5049f39d9b78de9cd/src/mscorlib/src/System/Reflection/Assembly.CoreCLR.cs#L246. Did we change this for .NET Framework compatibility?

**Comment by jkotas** [comment]
`Assembly.LoadFile` is new in .NET Core 2.0 for .NET Standard 2.0. Yes, it is trying to emulate the .NET Framework behavior. It means it has own load context.

**Comment by davidfowl** [comment]
@jkotas thanks for the confirmation.

@pavlospap You need to use one of those alternatives I provided to get the correct behavior. I'd recommend  `Assembly.Load(AssemblyName.GetAssemblyName(file))`.

**Comment by jkotas** [comment]
> `Assembly.Load(AssemblyName.GetAssemblyName(file))`

It will work but it is likely slower than the other variants: It opens the file twice - first to get the assembly name, and then to actually load it.

**Comment by davidfowl** [comment]
I guess I should give some options:

- If you're ok coupling to .NET Core then use `AssemblyLoadContext.Default.LoadFromAssemblyPath(file)`
- Otherwise I'd use `Assembly.Load(AssemblyName.GetAssemblyName(file))` since it's the most semantically correct. 

Another option would be to use `DependencyContext.Default` to get the a list of runtime assembly names and load those instead of looking on disk but that's not as simple.

**Comment by pavlospap** [comment]
Hello again! First of all I want to thank everyone for your time!
I'm OK coupling to .Net Core @davidfowl so I'll go with the first suggestion which works fine...
`AssemblyLoadContext.Default.LoadFromAssemblyPath(file)`
Thanks again!
