### ISSUE TITLE
Why does not HttpClientHandler throw an exception when adding only public portion of client certificate?

### ISSUE THREAD

**Issue by rudeGit** [aspnet/Home#2211]
To attach a client certificate to the request one could write following code on the client side:

        var cert = //TODO - load certificate
        var requestHandler = new HttpClientHandler();
        requestHandler.SslProtocols = SslProtocols.Tls12;
        requestHandler.ClientCertificateOptions = ClientCertificateOption.Manual;
        requestHandler.ClientCertificates.Add(cert);

        HttpClient client = new HttpClient(requestHandler);

        HttpResponseMessage response = client.GetAsync("https://www.example.com/api/values").Result;
        response.EnsureSuccessStatusCode();

In asp.net core 2.0 server side, one could write following code to extract the certificate (typically in a middleware component):

        var cert = this.HttpContext.Connection.GetClientCertificateAsync().Result;

The above 'cert' variable will be non-null if client attached a certificate that has a private key in it (though private key portion is not transmitted to the server). However if the client attached only a public portion of the certificate to requestHandler.ClientCertificates.Add(cert) call, the server side will return null for the extracted certificate.

I would expect the code on the client side to report an error because only a public portion of client certificate was attached. But it does not. Is there a way to force that error to make it obvious to the consumers of the library? Or am I missing something?

**Comment by Eilon** [comment]
@Tratcher / @blowdart - any ideas?

**Comment by Tratcher** [comment]
Just because you attached the cert to HttpClientHandler doesn't mean it sent it. It looks through the list and picks the most appropriate cert to send. In your case it didn't find one so it never sent one. The server does not know you tried to provide a cert, it never got one.

**Comment by rudeGit** [comment]
If I added a client certificate to HttpClientHandler (and set it to Manual, which means no other certificate should be inspected for sending a client certificate), it is clear what my intent is. During the call execution, it should have thrown an error because I added a file that does not include a private key. Am I wrong to expect this behavior?

**Comment by Tratcher** [comment]
You can file an HttpClientHandler bug at https://github.com/dotnet/corefx.
