### ISSUE TITLE
Question about setting up authentication middleware

### ISSUE THREAD

**Issue by TomPallister** [aspnet/Home#2214]
Hi,

Sorry this is probably going to be an annoying question!

In asp.net core 1.1 I was able to pass IApplicationBuilder into a middleware through DI and then use that builder to add any kind of authentication I wanted during a request e.g..

```csharp
 builder.UseJwtBearerAuthentication(
                    new JwtBearerOptions()
                        {
                            Authority = "foo",
                            Audience = "bar"
                        });
```
or

```csharp
     builder.UseIdentityServerAuthentication(new IdentityServerAuthenticationOptions
                {
                    Authority = "foo",
                    ApiName = "foo",
                    ApiSecret = "bar"
                });
```

Now that we set up the Authentication middleware in ConfigureServices I can't do this anymore. Is there any way to replicate this functionality in asp.net core 2.0?

This is probably something that is considered hacky but I use it in my open source project to allow different URLs to have different authentication providers which is quite a good feature.

**Comment by Tratcher** [comment]
See https://github.com/aspnet/Security/blob/5abcfe7e3d78f777d45503b50de5cea17cf9aa5e/test/Microsoft.AspNetCore.Authentication.Test/DynamicSchemeTests.cs#L137-L143

**Comment by davidfowl** [comment]
> In asp.net core 1.1 I was able to pass IApplicationBuilder into a middleware through DI and then use that builder to add any kind of authentication I wanted during a request e.g..

You weren't doing it per request were you? I'm not sure how that would have worked. Do you mean adding different middleware based on some data at startup? That makes more sense as you can't modify the pipeline once it's built.

**Comment by TomPallister** [comment]
@Tratcher that looks like what I need..thanks!

@davidfowl I would end up with a RequestDelegate that had different authentication "stuff" and then invoke it with the HttpContext from the middleware. I'm not sure if it was ever a good idea but the tests passed...

Something like this..

```csharp
            var builder = app.New();

            if (authOptions.Provider.ToLower() == "jwt")
            {
                builder.UseJwtBearerAuthentication(
                    new JwtBearerOptions()
                        {
                            blah...
                        });
            }
            else
            {
                builder.UseIdentityServerAuthentication(new IdentityServerAuthenticationOptions
                {
                    blah...
                });
            }

            var authenticationNext = builder.Build();

            authenticationNext.Invoke(context);

            if (context.User.Identity.IsAuthenticated) { }

```

So the user could say I want this route to be authenticated with IdentityServer and I want this route to use Auth0...This is in the context of building an API gateway. If this is terrible please let me know because a few people are using this :(

**Comment by TomPallister** [comment]
By the way thanks for the help! Really appreciate it!

**Comment by Tratcher** [comment]
It's really inefficient, but it seems to work for you.

**Comment by TomPallister** [comment]
Yeh it is inefficient, I was going to change it to build them on init not per request but now 2.0 has dropped there is no point.
