### ISSUE TITLE
Response on created context keeps giving me NullStream

### ISSUE THREAD

**Issue by Joshlo** [aspnet/Home#2215]
I'm trying to write a middleware for batch requests i .net core 2.0.
So far the I have splitted the request, pipe each request on to the controllers.
The controllers return value, but for some reason the response on the created context that I parse to the controllers keeps giving me a NullStream in the body, so I think that there is something that I miss in my setup.

The code looks like this:

    var json = await streamHelper.StreamToJson(context.Request.Body);

    var requests = JsonConvert.DeserializeObject<IEnumerable<RequestModel>>(json);

    var responseBody = new List<ResponseModel>();

    foreach (var request in requests)
    {
        var newRequest = new HttpRequestFeature
        {
            Body = request.Body != null ? new MemoryStream(Encoding.ASCII.GetBytes(request.Body)) : null,
            Headers = context.Request.Headers,
            Method = request.Method,
            Path = request.RelativeUrl,
            PathBase = string.Empty,
            Protocol = context.Request.Protocol,
            Scheme = context.Request.Scheme,
            QueryString = context.Request.QueryString.Value
        };

        var newRespone = new HttpResponseFeature();
        var requestLifetimeFeature = new HttpRequestLifetimeFeature();

        var features = CreateDefaultFeatures(context.Features);
        features.Set<IHttpRequestFeature>(newRequest);
        features.Set<IHttpResponseFeature>(newRespone);
        features.Set<IHttpRequestLifetimeFeature>(requestLifetimeFeature);
                    
        var innerContext = _factory.Create(features);
        await _next(innerContext);
                    
        var responseJson = await streamHelper.StreamToJson(innerContext.Response.Body);

I'm not sure what it is I'm missing in the setup, since innerContext.Response.Body isn't set.

One of the endpoints that I use for testing and that gets hit looks like this

    [Route("api/[controller]")]
    public class ValuesController : Controller
    {
        // GET api/values
        [HttpGet]
        public IEnumerable<string> Get()
        {
            return new string[] { "value1", "value2" };
        }
    }

I have also played around with setting var newRespone = new HttpResponseFeature(); to var newRespone = new HttpResponseFeature{ Body = new MemoryStream() }; but then it's just empty

**Comment by Tratcher** [comment]
https://github.com/aspnet/HttpAbstractions/blob/835ba2218a2fada35045515d8ced49c3bafc2148/src/Microsoft.AspNetCore.Http/Features/HttpResponseFeature.cs#L16
You need to provide your own stream for the response body. A MemoryStream may work for your scenario.

What's the status code you get back for your inner context?

**Comment by Joshlo** [comment]
@Tratcher Thanks for a quick response.

I tried to change
`var newRespone = new HttpResponseFeature();`
to
`var newRespone = new HttpResponseFeature { Body = new MemoryStream(), StatusCode = 419 };`

and then set it to the IHttpResponseFeature. That results in the StatusCode being changed to 200, since the controller returns success, but the Body is just an empty MemoryStream and the Response.ContentLength is null

**Comment by Tratcher** [comment]
Check out this thread, someone else has been working on the same concept: https://github.com/aspnet/BasicMiddleware/issues/246

**Comment by Joshlo** [comment]
I found the problem..

Before I read the stream I have to do a `innerContext.Response.Body.Position = 0` or else the stream looks empty, since it starts at the end
