### ISSUE TITLE
When asp.net core sends a confirm email, it adds "amp;" string after the & sign inside a link

### ISSUE THREAD

**Issue by mlevinmail** [aspnet/Home#2217]
I am currently working with ASP.NET CORE 2.0 

When a user registers the server sends a confirmation link to the email, so that the user can confirm his/her email. 

Here is the link:

https://localhost:44388/Account/ConfirmEmail?userId=eb550f3a-a518-40ca-bcbc-954960f95ebe&amp;code=CfDJ8IqAQvtamy5FgGRftg8pggBe6UPvc1or%2BmGgA9Rps%2BL7CY14mur8s1o4oNN6etI%2BTBQ0e4gdas%2BrrCEageAtg63SdjcR%2FVzPy1GBMs5AEx47%2FQ%2F5bwSa5R%2FfuYMaOK3N%2FQPMHRjh7Ws%2FCUxNhjFypji10HktHwR2ztGwjSlkU2e7CCoornFwQ%2FjqS85mLrgNHOz88SnvM%2BUpJaQr2rwmN%2F80s54NJVNeFs9BiBVEN1cjV87uAEdt08t5mj97%2FcRN3A%3D%3D

It consist of the userID and the code. After the '&' sign there is "amp;", which prevents account controller class action to recognize the code;

Account controller action

public async Task<IActionResult> ConfirmEmail(string userId, string code)

This only happens on email confirmation, not forget password link. 

My workaround right is to do the following 

        public Task SendEmailAsync(string email, string subject, string message)
        {

            // glitch in asp.net core
            if (message.Contains("amp;"))
            {
                message = message.Replace("amp;", "");
            }

          ........

**Comment by joeaudette** [comment]
this issue is the same as https://github.com/aspnet/Home/issues/2152

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
