### ISSUE TITLE
Some Features are Disabled in online Demo Which i have seen earlier

### ISSUE THREAD

**Issue by amitsaini12345** [aspnet/Home#2220]
Hello everyOne,
                                  I have seenn today so many features in online demo Like customizing the website like menus,like english titles, name titles, many more, like manage categories  etc.

But now these are disabled. anyone please help me. please restore the previous build

**Comment by Tratcher** [comment]
Can you link to the demos for clarification?

**Comment by Eilon** [comment]
Hi. We're closing this issue as no response or updates have been provided in a timely manner and we have been unable to reproduce it. If you have more details and are encountering this issue please add a new reply and re-open the issue.
