### ISSUE TITLE
Microsoft.AspNetCore.Http.PathString.StartsWithSegments returns false unexpectedly

### ISSUE THREAD

**Issue by evil-shrike** [aspnet/Home#2221]
I encountered a strange behavior of `PathString.StartsWithSegments` method.
For the url "/api/_security/login_forms" `Path.StartsWithSegments("/api/")` return `false`.
I believe it's bug, please confirm. 

from Immediate Window (request is `HttpRequest`):
```
request.Path.Value
"/api/_security/login_forms"

request.Path.StartsWithSegments("/api/")
false

request.Path.Value.StartsWith("/api/")
true

request.Path.Value["/api/".Length]
95 '_'
```

**Comment by Tratcher** [comment]
StartsWithSegments matches whole segments only. A segment is defined as starting with a slash, having zero or more characters, and then ending before the next slash or end of the string. In your example you should be using `request.Path.StartsWithSegments("/api")`. `/api/` would match a path like `/api//foo`.
