### ISSUE TITLE
Separate bundleconfig.json for CSS and JS

### ISSUE THREAD

**Issue by shahidwani** [aspnet/Home#2222]
It would be nice to have separate bundleconfig json files for CSS and JS, maybe  something like bundleconfig.styles.json and bundleconfig.scripts.json.

**Comment by Eilon** [comment]
cc @madskristensen

**Comment by madskristensen** [comment]
The Bundler & Minifier extension/NuGet package doesn't currently support that. If you wish to see it supported, then please open a bug on their [issue tracker](https://github.com/madskristensen/bundlerminifier/issues)

**Comment by shahidwani** [comment]
Thanks i have opened this issue on their tracker. For reference, here the link
https://github.com/madskristensen/BundlerMinifier/issues/304
