### ISSUE TITLE
HttpCookie class is not present in .netCoreapp2.0

### ISSUE THREAD

**Issue by PriyaKuncham** [aspnet/Home#2224]
Hi ,
I am trying to upgrade ASPNET.MVC application .netcoreapp2.0. In this process I am unable to replace below code.
```C#
HttpCookie refresh_token = Request.Cookies["refresh_token"];
if (refresh_token != null)
{
TokenRefreshResponse authResponse = await TokenRefreshHelper.RefreshToken(clientId, refresh_token.Value);
if (authResponse.status == HttpStatusCode.OK)
{
SetCookieExpiration(new HttpCookie("access_token", authResponse.access_token), DateTime.UtcNow.AddSeconds(authResponse.expires_in));
SetCookieExpiration(new HttpCookie("refresh_token", authResponse.refresh_token), DateTime.UtcNow.AddSeconds(authResponse.refresh_token_expires_in));
                return Redirect(ConfigurationManager.AppSettings["ROOT_URL"] + "/Account/HandleAuthenticationResult?returnUrl=" + (String.IsNullOrEmpty(returnUrl) ? ConfigurationManager.AppSettings["ROOT_URL"] : returnUrl));
            }
            else
            {
                LogOff();
            }

        }

public ApplicationSignInManager SignInManager
{
get
{
return _signInManager ?? HttpContext.GetOwinContext().Get();
}
private set
{
_signInManager = value;
}
}
```

Can you give me how to replace this part of code .
@davidfowl , @terrajobst

**Comment by davidfowl** [comment]
You likely have to rewrite a bunch of this code when porting to ASP.NET Core. There *are* new versions of the components you are using but there are different enough that I'd need to see more of the code to recommend what changes you need to make.

What exactly are you trying to do?

**Comment by Priya-John** [comment]
using System;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using System.Web;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;
using FSI.PMProduct.Web.Models;
using System.Net.Http;
using System.Configuration;
using System.Net;
using System.Collections.Generic;
using Microsoft.Owin;
using Microsoft.Owin.Security.OAuth;
using FSI.DataAccess.Common.Contracts;
using FSI.PMProduct.BLL.Contracts;
using FSI.PMProduct.DataModel;
using FSI.Authentication.ClientTools.TokenDecryption;
using FSI.Authentication.ClientTools.Models;
using FSI.Authentication.ClientTools.Helpers;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;

namespace FSI.PMProduct.Web.Controllers
{
    public class AccountController : Controller
    {
        private ApplicationSignInManager _signInManager;
        private ApplicationUserManager _userManager;
        IUnitOfWork _unitOfWork;
        ICompanyBusiness _companyBusiness;

        public AccountController(IUnitOfWork unitOfWork, ICompanyBusiness companyBusiness)
        {
            _unitOfWork = unitOfWork;
            _unitOfWork.Context = new Project_Management_Entities();
            _companyBusiness = companyBusiness;
        }

        public ApplicationSignInManager SignInManager
        {
            get
            {
                return _signInManager ?? HttpContext.GetOwinContext().Get<ApplicationSignInManager>();
            }
            private set
            {
                _signInManager = value;
            }
        }

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        //
        // GET: /Account/Login
        [HttpGet]
        [AllowAnonymous]
        public async Task<ActionResult> ApiLogin(string returnUrl = null)
        {
            string clientId = ConfigurationManager.AppSettings["CLIENT_ID"];
            // First, do you have an active access_token?
            // Second, if not, do you have a refresh_token?
            HttpCookie refresh_token = Request.Cookies["refresh_token"];
            if (refresh_token != null)
            {
                TokenRefreshResponse authResponse = await TokenRefreshHelper.RefreshToken(clientId, refresh_token.Value);
                if (authResponse.status == HttpStatusCode.OK)
                {
                    SetCookieExpiration(new HttpCookie("access_token", authResponse.access_token), DateTime.UtcNow.AddSeconds(authResponse.expires_in));
                    SetCookieExpiration(new HttpCookie("refresh_token", authResponse.refresh_token), DateTime.UtcNow.AddSeconds(authResponse.refresh_token_expires_in));

                    return Redirect(ConfigurationManager.AppSettings["ROOT_URL"] + "/Account/HandleAuthenticationResult?returnUrl=" + (String.IsNullOrEmpty(returnUrl) ? ConfigurationManager.AppSettings["ROOT_URL"] : returnUrl));
                }
                else
                {
                    LogOff();
                }

            }
            // Clear the existing external cookie to ensure a clean login process
            AuthenticationManager.SignOut(DefaultAuthenticationTypes.ApplicationCookie);
            return Redirect(GenerateLoginRedirectUrl(clientId, returnUrl));
        }

        private string GenerateLoginRedirectUrl(string clientId, string returnUrl)
        {
            string rootUrl = ConfigurationManager.AppSettings["ROOT_URL"];
            string returnUrlString = HttpUtility.UrlEncode(rootUrl + (returnUrl == null ? "" : returnUrl));

            return ConfigurationManager.AppSettings["AUTHENTICATION_API_ROOT_URL"] + "/LoginUI/?clientId=" + clientId + "&returnUrl=" + returnUrlString;
        }


        [HttpGet]
        [AllowAnonymous]
        public async Task<ActionResult> HandleAuthenticationResult(string returnUrl)
        {
            HttpCookie access_token = Request.Cookies["access_token"];

            if (access_token != null)
            {
                AccessTokenDecryptor accessTokenDecryptor =
                new AccessTokenDecryptor(
                    typeof(OAuthBearerAuthenticationMiddleware).Namespace,
                    "Access_Token",
                    "v1");
                AuthenticationTicket ticket = accessTokenDecryptor.GetTicket(access_token.Value);


                List<Claim> appAccessClaim = ticket.Identity.Claims.Where(c => c.Type == ClaimTypes.Role && c.Value == ConfigurationManager.AppSettings["PRODUCT_NAME"]).ToList<Claim>();
                if (appAccessClaim != null && appAccessClaim.Count > 0)
                {
                    var appUser = await UserManager.FindByEmailAsync(ticket.Identity.Name);
                    if (appUser != null)
                    {
                        appUser.ClaimsFromAD = ticket.Identity.Claims;
                        await SignInManager.SignInAsync(appUser, false, false);
                        System.Web.HttpContext.Current.Session["currentUserId"] = getUserIdByEmail(ticket.Identity.Name); ;
                        return Redirect(returnUrl);
                    }
                }
            }
            ExpireCookies();
            return RedirectToAction("CannotAccessProduct", "Account");
        }

        private void ExpireCookies()
        {
            SetCookieExpiration(Request.Cookies["access_token"], DateTime.Now.AddDays(-1d));
            SetCookieExpiration(Request.Cookies["refresh_token"], DateTime.Now.AddDays(-1d));
        }

        private void SetCookieExpiration(HttpCookie cookie, DateTime expirationDateTime)
        {
            if (cookie != null)
            {
                cookie.Expires = expirationDateTime;
                Response.Cookies.Add(cookie);
            }
        }

        private static string getUserIdByEmail(string email)
        {
            OwinContext owinContext = (OwinContext)System.Web.HttpContext.Current.GetOwinContext();
            ApplicationUserManager userManager = owinContext.GetUserManager<ApplicationUserManager>();
            ApplicationUser user = userManager.FindByEmail<ApplicationUser, string>(email);
            return user.Id;
        }

        [HttpGet]
        [AllowAnonymous]
        public ActionResult CannotAccessProduct()
        {
            return View();
        }

        //
        // GET: /Account/Register
        [AllowAnonymous]
        public ActionResult Register()
        {
            return View();
        }

        //
        // POST: /Account/Register
        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Register(RegisterViewModel model)
        {
            if (ModelState.IsValid)
            {
                var company = _companyBusiness.GetCompanyByName(model.CompanyName);
                if (company == null)
                {
                    ModelState.AddModelError("", "Company does not exist");
                    return View(model);
                }
                var user = new ApplicationUser { UserName = model.Email, Email = model.Email, CompanyId = company.Id };
                var result = await UserManager.CreateAsync(user, model.Password);
                if (result.Succeeded)
                {
                    //TempData["registerSuccessMessage"] = "User successfully registered(display this message for now-later figure out where to go after register).";
                    //await SignInManager.SignInAsync(user, isPersistent: false, rememberBrowser: false);

                    // For more information on how to enable account confirmation and password reset please visit https://go.microsoft.com/fwlink/?LinkID=320771
                    // Send an email with this link
                    // string code = await UserManager.GenerateEmailConfirmationTokenAsync(user.Id);
                    // var callbackUrl = Url.Action("ConfirmEmail", "Account", new { userId = user.Id, code = code }, protocol: Request.Url.Scheme);
                    // await UserManager.SendEmailAsync(user.Id, "Confirm your account", "Please confirm your account by clicking <a href=\"" + callbackUrl + "\">here</a>");
                    ExpireCookies();
                    return RedirectToAction("ApiLogin", "Account");
                }
                AddErrors(result);
            }

            // If we got this far, something failed, redisplay form
            return View(model);
        }

        //
        // POST: /Account/LogOff
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult LogOff()
        {
            ISession.Abandon();
            AuthenticationManager.SignOut(DefaultAuthenticationTypes.ApplicationCookie);
            ExpireCookies();
            return RedirectToAction("Index", "Home");
        }



        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                if (_userManager != null)
                {
                    _userManager.Dispose();
                    _userManager = null;
                }

                if (_signInManager != null)
                {
                    _signInManager.Dispose();
                    _signInManager = null;
                }
            }

            base.Dispose(disposing);
        }

        #region Helpers

        private IAuthenticationManager AuthenticationManager
        {
            get
            {
                return HttpContext.GetOwinContext().Authentication;
            }
        }

        private void AddErrors(IdentityResult result)
        {
            foreach (var error in result.Errors)
            {
                ModelState.AddModelError("", error);
            }
        }

        private ActionResult RedirectToLocal(string returnUrl)
        {
            if (Url.IsLocalUrl(returnUrl))
            {
                return Redirect(returnUrl);
            }
            return RedirectToAction("Index", "Home");
        }
        #endregion
    }
}

This code was written in .netframework web application for authentication. Do I need to totally rewrite this authentication part 

@davidfowl

**Comment by Priya-John** [comment]
![image](https://user-images.githubusercontent.com/32129009/31233077-523b8e38-aa09-11e7-8452-298b493746e5.png)
GetOwinContext is not part of Httcontext then how to get OwinContext in aspnetcore

**Comment by davidfowl** [comment]
Are you porting code to ASP.NET Core?

**Comment by Tratcher** [comment]
@Priya-John there is no owin context in core. In 2.0 the authentication methods are extensions off of HttpContext directly.

**Comment by Priya-John** [comment]
Yes porting code to ASPNETCore2.0
