### ISSUE TITLE
How to publish self contained app

### ISSUE THREAD

**Issue by Saticmotion** [aspnet/Home#2228]
I've upgraded my app from ASP.NET Core 1 to 2, and I've been trying to publish my app with the following command:

    dotnet publish -o \bin\Release --self-contained --runtime win81-x64 --configuration "Release" --force

I got to this point with the following tutorial: https://docs.microsoft.com/en-us/dotnet/core/deploying/deploy-with-cli
I've followed the steps under "Self-contained deployment without third-party dependencies" and "Self-contained deployment with third-party dependencies"

This publishes some files (the exe, dll, pdb, and config files) but not my wwwroot (and thus css and js files), nor third party dlls.

Then I copy the files to the server folder where my .Net Core 1 app was. Then I restart the website. If I try to browse to my website I get 403 - Forbidden: Access is denied.

What am I doing wrong? The IIS website used to work for .Net Core 1

**Comment by Eilon** [comment]
@vijayrkn - where's the best place to report issues with publish?

**Comment by vijayrkn** [comment]
For issues related to ASP.NET core publish (non VS issues),  https://github.com/aspnet/websdk would be the right place.

**Comment by Eilon** [comment]
This issue was moved to aspnet/websdk#286
