### ISSUE TITLE
After creating new ASP.NET Core 2.0 project Nuget could not restore packages

### ISSUE THREAD

**Issue by Petermarcu** [aspnet/Home#2229]
@FireFighter92 reported this here: https://github.com/dotnet/core/issues/991

**My tools:**

> Microsoft Visual Studio Community 2017  Version 15.3.5
> ASP.NET and Web Tools 2017   15.0.30726.0
> ASP.NET Core Razor Language Services   1.0
> ASP.NET Template Engine 2017   15.0.30726.0
> NuGet Package Manager   4.3.1
> SQL Server Data Tools   15.1.61707.200
And of course I have the latest SDK and Runtime installed

Just downloaded VS 2017 and tried to build new ASP.NET Core 2.0 project and unfortunately got an error with the best impression :)

**Error:**

> NU1202: Package Microsoft.Extensions.SecretManager.Tools 2.0.0 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Microsoft.Extensions.SecretManager.Tools 2.0.0 supports: netcoreapp2.0 (.NETCoreApp,Version=v2.0)
> NU1202: Package Microsoft.EntityFrameworkCore.Tools.DotNet 2.0.0 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Microsoft.EntityFrameworkCore.Tools.DotNet 2.0.0 supports: netcoreapp2.0 (.NETCoreApp,Version=v2.0)
> NU1202: Package Microsoft.VisualStudio.Web.CodeGeneration.Tools 2.0.0 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Microsoft.VisualStudio.Web.CodeGeneration.Tools 2.0.0 supports: netcoreapp2.0 (.NETCoreApp,Version=v2.0)
> NU1202: Package Microsoft.VisualStudio.Web.CodeGeneration.Contracts 2.0.0 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Microsoft.VisualStudio.Web.CodeGeneration.Contracts 2.0.0 supports: netstandard2.0 (.NETStandard,Version=v2.0)
> NU1202: Package Microsoft.Build 15.3.409 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Microsoft.Build 15.3.409 supports:
>   - net46 (.NETFramework,Version=v4.6)
>   - netstandard1.5 (.NETStandard,Version=v1.5)
> NU1202: Package Microsoft.Build.Framework 15.3.409 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Microsoft.Build.Framework 15.3.409 supports:
>   - net46 (.NETFramework,Version=v4.6)
>   - netstandard1.3 (.NETStandard,Version=v1.3)
> NU1202: Package Microsoft.Build.Utilities.Core 15.3.409 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Microsoft.Build.Utilities.Core 15.3.409 supports:
>   - net46 (.NETFramework,Version=v4.6)
>   - netstandard1.3 (.NETStandard,Version=v1.3)

**Comment by danilobreda** [comment]
Possible Duplicated: https://github.com/aspnet/DotNetTools/issues/198

> The tool should be installed in the "tools" section of project.json. This should be independent of the frameworks you are using in your project. If you're trying to install via NuGet CLI or GUI, it's probably being put in "dependencies", which is #157 and will be resolved in the next release.

**Comment by Eilon** [comment]
Closing this issue because it isn't clear to me if there is an issue remaining. If you feel there's still an issue, please re-open this issue or log a new issue with complete details of the problem. Thanks!
