### ISSUE TITLE
Asp-controller and asp-action attributes order

### ISSUE THREAD

**Issue by Petermarcu** [aspnet/Home#2231]
@johanskoldekrans reported this issue here: https://github.com/dotnet/core/issues/899

If a make an a-tag in html on the view and put asp-* tags (for example asp-controller, asp-action and asp-route) after a @(some code)-section and a class-attribute it breaks the interpretation of the asp-* attributes.

Below example doesnt pick up the route-id:
`
<a asp-controller="Some" asp-action="Something" class="@(x == y ? "something" : "")" asp-route-id="1">Click me</a>
`
if I put all after nothing happens (no href is generated):
`
<a class="@(x == y ? "something" : "")" asp-controller="Some" asp-action="Something" asp-route-id="1">Click me</a>
`
Is this behaviour as design?

VS 2017 15.3.2
.NETCore 2.1.0-preview1-26778
.EFCore 2.1.0-preview1-26778
Windows 10 Insider (slow ring)

This is probably closer to what I did IRL that didn't work, if there is a difference:

`<a @(x == y ? "class=\"something\"" : "")" asp-controller="Some" asp-action="Something" asp-route-id="1">Click me</a>`

**Comment by pranavkm** [comment]
cc @NTaylorMullen

**Comment by Eilon** [comment]
Hi. We're closing this issue as no response or updates have been provided in a timely manner and we have been unable to reproduce it. If you have more details and are encountering this issue please add a new reply and re-open the issue.

**Comment by johanskoldekrans** [comment]
Go ahead. Havent been able to reproduce after downgrading dotnetcore. 👍🏻

> 3 apr. 2018 kl. 18:10 skrev Eilon Lipton <notifications@github.com>:
> 
> Hi. We're closing this issue as no response or updates have been provided in a timely manner and we have been unable to reproduce it. If you have more details and are encountering this issue please add a new reply and re-open the issue.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

-- 

www.penser.se
Disclaimer: www.penser.se/disclaimer
