### ISSUE TITLE
Migrating ASP.NET Core 1.1 apps -> ASP.NET Core 2.0

### ISSUE THREAD

**Issue by Petermarcu** [aspnet/Home#2234]
@richlander opened this here: https://github.com/dotnet/core/issues/726

We need docs for this.

See: https://github.com/dotnet/core/issues/711#issuecomment-312377310

**Comment by Tratcher** [comment]
They exist: https://docs.microsoft.com/en-us/aspnet/core/migration/1x-to-2x/
Are they missing something you need?

**Comment by Petermarcu** [comment]
@richlander will have to answer that. I am just making sure tracking bugs are in the right place.
