### ISSUE TITLE
VS 2017 Debugger Hangs on start

### ISSUE THREAD

**Issue by JulienM28** [aspnet/Home#2235]
Hi,

I use Visual studio 2017 x64 on Windows 10 x64 with Dot Net core 1.1
My project is using the last 1.1.X dependencies available.

I have a starnge issue with an ASP.Net Core projetct.

Since recently everything worked fine. The dubugger took a while to start but was ok.

Now when I launch the debugger, the webSite is starting fine, but VS Hangs on a message telling the web server took too long time to start.

I tried to make an application console instead of using IIS Express, The debugger is starting nicely.

I have another issue in this case: I'm using custom url to test subdomains rooting, and brakpoints doesn't hit in this case.

So I can't debug anymore.

Finaly I created a fresh project and the debugger worked fine.

I assume there's something in my code that doesn't please to Visual Studio or .Net Core, But I didn't fint out what for now.

Any Idea?

Thanks.

**Comment by Tratcher** [comment]
@BillHiebert

**Comment by JulienM28** [comment]
It's a weird story: after a good night, everything is working fine.

I don't understand what happened. I restarted the computer several times, but nothing to do, and the next morning everything is fine.

Sorry for  the inconvenience.

**Comment by Eilon** [comment]
BTW for issues with VS, we recommend using VS's built-in "Report a Problem" feature.
