### ISSUE TITLE
Kestrel "ignores" listenOptions.UseHttps on asp.net Core 2.0 on Ubuntu - uses http instead - but works on Windows

### ISSUE THREAD

**Issue by netsfx** [aspnet/Home#2239]
I want to run an asp.net core 2.0 site with Kestrel on Ubuntu with https and do:

```
public static void Main(string[] args)
		{
			var host = new WebHostBuilder()
				.UseKestrel(options =>
				{
					options.ApplicationSchedulingMode = SchedulingMode.Inline;
					options.Listen(IPAddress.Any, 80);
					options.Listen(IPAddress.Any, 443,
				   listenOptions =>
						{
							try
							{
								listenOptions.NoDelay = true;
								listenOptions.UseHttps("cert.pfx", args[0]);
								listenOptions.UseConnectionLogging();
							}
							catch (Exception) { }
						});
					options.UseSystemd();
				})
				
				.UseContentRoot(Directory.GetCurrentDirectory())
				.UseStartup<Startup>()
				.Build();
			host.Run();
		}
```
On Windows, that works as expected:
Now listening on: http://0.0.0.0:80
*Now listening on: https://0.0.0.0:443*

But the same on Ubuntu yields *http* instead of *https* on port 443:
Now listening on: http://0.0.0.0:80
*Now listening on: http://0.0.0.0:443*

The result is that on Ubuntu port 443 will not serve https but http, which is of course not what I want.

Any ideas?

**Comment by netsfx** [comment]
This is not usable with Linux and pure-Kestrel! anybody care to look/reproduce?

**Comment by jkotalik** [comment]
Why are you catching any exceptions when setting the listenOptions? If there is an error, you probably want the server to not start. See what error you are getting without the try catch. My guess is you don't have the cert.pfx and password correct, as the setting seems to not be set. Also, you may need to open up port 443 in ubuntu (https://askubuntu.com/questions/500175/how-can-i-open-port-443).

**Comment by netsfx** [comment]
@jkotalik you are right, catching that exception (without logging the output) was a very bad idea. The problem can be caused by problems loading the file or passing the password. After fixing both, it works!
