### ISSUE TITLE
Can't install KRE

### ISSUE THREAD

**Issue by charly1811** [aspnet/Home#224]
Hi .
Im trying to install ASP.NET vNext on Windows with KVM  but when I use `kvm upgrade` I get the following output:

Determining latest version
Downloading KRE-CLR-x86.1.0.0-beta1 from https://www.nuget.org/api/v2
Exception calling "DownloadFile" with "2" argument(s): "The underlying connection was closed: An unexpected error occurred on a send."
Type 'kvm help' for help on how to use kvm.

Can you help me ?

**Comment by charly1811** [comment]
I think its working now . After I installed VS 2015 preview and retried its working

**Comment by Praburaj** [comment]
Thanks for confirming.
