### ISSUE TITLE
Two actions with same Http<Method> attributes result in ambiguity on ubuntu

### ISSUE THREAD

**Issue by Petermarcu** [aspnet/Home#2241]
@distomin opened this here: https://github.com/dotnet/core/issues/1026

uname -a
Linux N46JV 4.10.0-37-generic #41-Ubuntu SMP Fri Oct 6 20:20:37 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
dotnet --version
2.0.0
dotnet new webapi

Add 2 actions in a controller with the same attribute (HttpGet for example)
[HttpPost]
public Product Action4([FromForm]Product product)
[HttpPost]
public Product Action5([FromBody]Product product)

build the project, run the project and make http request.

fail: Microsoft.AspNetCore.Mvc.Internal.ActionSelector[1]
      Request matched multiple actions resulting in ambiguity
... Microsoft.AspNetCore.Mvc.Internal.AmbiguousActionException: Multiple actions matched.

They say it works on Windows platform correctly.

**Comment by Tratcher** [comment]
This issue was moved to aspnet/Mvc#6945
