### ISSUE TITLE
[Authorize] on both Controller and Method won't work with ASP.Net Core 2.0

### ISSUE THREAD

**Issue by sadjadbp** [aspnet/Home#2242]
Using ASP.Net Core 1, I had this this controller that had [Authorize] attrib so it would go to default schema which is Cookie in my case and then on some of its methods I would go [Authorize("Bearer")], so those specific ones would have Jwt Authentication enabled.

Now that I upgraded to ASP.Net Core v2, for those JWT enabled methods I'll get 302 even if I pass JWT. So the fix for me is to remove the [Authorize] attrib from class and put it on all methods, but this way it opens my controller to developers mistake that they might forget to add [Authorize] per method.

**Comment by Tratcher** [comment]
This issue was moved to aspnet/Security#1489
