### ISSUE TITLE
Compiling C# aspnet project runs TypeScript compiler for wwwroot what is redundant and error-prone

### ISSUE THREAD

**Issue by evil-shrike** [aspnet/Home#2243]
I have aт aspnet core project where *.ts got deployed into wwwroot. Some of ts files are typings (from DefinetlyTyped). So very unclear reason existence that typescript files in wwwroot force dotnet/VS run TypeScript compiler. 
First of all it's completely redundant. I compile all ts files already and copied them into wwwroot with my client build tools. But moreover it can produce errors. For example if mentined typing targets a newer version of TypeScript compiler than installed globally.
In case compilation of the aspnet project fails with the following error:
Error	TS5023	Build:Unknown compiler option 'strictFunctionTypes'.

![image](https://user-images.githubusercontent.com/1203230/31569951-00c8e34a-b088-11e7-8547-ada309826e81.png)

I'm getting the error in VS and Rider but not in cli (`dotnet build`).

**Comment by evil-shrike** [comment]
I've completely rewrote the initial comment.

**Comment by jkotalik** [comment]
This seems more likely to be a TypeScript error than AspNet. My guess is that your msbuild is using an older version of TypeScript. Try updating type script like:
`npm update -g typescript`. If that doesn't work, you should make an issue in https://github.com/Microsoft/TypeScript

**Comment by evil-shrike** [comment]
@jkotalik that particular error indeed is an error from old TypeScript while tsconfig in wwwroot requires a newer one (2.7).
But the problem is not with that particular error and how to fix it but in the fact that TS compiler is run on build at all. Why? Who does run it? I guess it some aspnet's msbuild task..

**Comment by jkotalik** [comment]
Ahh gotcha. Thanks for the clarification. I think you need to configure a tsconfig.json file. See the section ["Configure the TypeScript complier" ](https://www.typescriptlang.org/docs/handbook/asp-net-core.html) for more details. @moozzyk I know you have been working with TS in SignalR. Is there way to disable building TS on building an application, and if so can you configure it in tsconfig.json?

**Comment by moozzyk** [comment]
@evil-shrike - have you tried setting the `TypeScriptCompileBlocked` property to `true` as described [here](https://stackoverflow.com/questions/39176586/how-to-disable-typescript-compilation-in-net-core-projects). 
I also wonder why you need any *.ts files in wwwroot. You shouldn't need these files at runtime so publishing them feels wasteful. Why not compile your *.ts files elsewhere and copy/target the output *.js files to the wwwroot folder?

**Comment by evil-shrike** [comment]
@moozzyk thanks! `TypeScriptCompileBlocked ` solves the problem.
> I also wonder why you need any *.ts files in wwwroot

I need *.ts in wwwroot to debugging with source maps works. 
I don't need all *.d.ts indeed and now I filter them out on copying.

But running TypeScript compiler by default seems weir for me. I'd suggest introduce a property with the opposite meaning to `TypeScriptCompileBlocked` - e.g. `TypeScriptCompile`. If someone needs to compile *.ts in wwwroot for some reason he/she would enable this explicitly. Why to do it by default??

**Comment by moozzyk** [comment]
> But running TypeScript compiler by default seems weir for me. I'd suggest introduce a property with the opposite meaning to TypeScriptCompileBlocked - e.g. TypeScriptCompile. If someone needs to compile *.ts in wwwroot for some reason he/she would enable this explicitly. Why to do it by default??

I suggest opening an issue in the [TypeScript](https://github.com/microsoft/TypeScript) repo for this.

**Comment by evil-shrike** [comment]
@moozzyk ok, thanks.

**Comment by evil-shrike** [comment]
from https://github.com/Microsoft/TypeScript/issues/19271:
@mhegazy said:
> The ASP.net targets include the TypeScript targets file.. your project includes the ASP.net targets, and transitively include the TypeScript targets.

so, it's not a TS's issue but aspnet.

**Comment by moozzyk** [comment]
@natemcmaster - do you know who own ASP.NET targets files?

**Comment by natemcmaster** [comment]
I'm assuming this problem only happens in Visual Studio, not `dotnet build` on command line, right? If so, the targets causing the issue are probably coming from `C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\VisualStudio\v15.0\TypeScript`, which is owned by a VS team. Not sure which one. @mlorbetske might know.

**Comment by evil-shrike** [comment]
>I'm assuming this problem only happens in Visual Studio, not dotnet build on command line, right?

right

**Comment by mhegazy** [comment]
A relevant change here is https://github.com/Microsoft/TypeScript/issues/18312. The TypeScript targets today run the task regardless if there is input items or not. Fixing https://github.com/Microsoft/TypeScript/issues/18312 should mitigate the issue.
