### ISSUE TITLE
Aborted (core dumped) when running dotnet ProjectName.dll

### ISSUE THREAD

**Issue by deanilvincent** [aspnet/Home#2245]
Specifications:
**Development Environment:** 
Windows 10 with updates
Visual Studio 2017 15.3
.Net Core 2.0 (Latest)

**Project Description:** 
Basic and default MVC project of asp.net core 2.0 and nothing really fancy.

**Server Hosting**
Ubuntu 16.04 with installed:
    .Net Core 2.0
    Nginx

I already published my application inside my ubuntu server but when I'm trying to use the command 

`dotnet ProjectName.dll`

I got this errors. Any help?

![testingcoreerror](https://user-images.githubusercontent.com/10904957/31609711-d533d9f2-b2a7-11e7-8fcc-f6c2d34e0813.PNG)

**Comment by jkotalik** [comment]
I am confused about your setup. Did you publish an application from a windows development environment to an Ubuntu one? Also how did you publish your application(dotnet publish, publish from visual studio, etc). If so, can you first confirm that the app runs in visual studio? If you still have errors, please paste the whole exception from the server failing. 
My guess is there is an issue with the dll referencing IISExpress, and on a linux environment you need to use nginx.

**Comment by deanilvincent** [comment]
@jkotalik I published it on my linux machine. Yes, it's running properly on windows machine. I already fixed it by editing my Startup.cs.

**Comment by jason2li** [comment]
@deanilvincent, what did you do to fix this?

**Comment by deanilvincent** [comment]
@jason2li  Try this:

Specify a specific port by using `.UserUrls("___portNumberHere___")` like this:
 
```
public static IWebHost BuildWebHost(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .UseUrls("http://+:8181") // whatever port you want
                .UseStartup<Startup>()
                .Build();
```

I hope this helps you.

**Comment by zoidhddhdd** [comment]
Develop
