### ISSUE TITLE
Mixing Cookie Auth and JWT auth in same controller (dual auth)

### ISSUE THREAD

**Issue by NicoSymo** [aspnet/Home#2246]
Hi

I'm working on an ASP Core 2.0 project that contains in the same controller both API actions returning JSON and actions returning views for simplicity.

I implemented the dual auth considering the following blog :

https://wildermuth.com/2017/08/19/Two-AuthorizationSchemes-in-ASP-NET-Core-2

It works, but because of my mixing API/actions for views in the same controller, If I have such a controller :

`[Authorize]
public class AccountController : Controller
{

//This action only requires coockie auth (OK)
public IActionResult Index()
{
    return View();
}

[Authorize(AuthenticationSchemes = JwtBearerDefaults.AuthenticationScheme)]
// This action currently requires BOTH cookie auth AND JWT auth ! (KO)
// Here I would like only JWT, not a cumulative auth 
[Authorize(AuthenticationSchemes = JwtBearerDefaults.Aut
public IActionResult Get()
{
return Ok(new[] { "One", "Two", "Three" });
}

}`

and in startup.cs (ConfigureServices)
`// Enable Dual Authentication 
services.AddAuthentication()
.AddCookie(cfg => cfg.SlidingExpiration = true)
.AddJwtBearer(cfg =>
{
cfg.RequireHttpsMetadata = false;
cfg.SaveToken = true;

cfg.TokenValidationParameters = new TokenValidationParameters()
{
ValidIssuer = Configuration["Tokens:Issuer"],
ValidAudience = Configuration["Tokens:Audience"],
IssuerSigningKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(Configuration["Tokens:Key"]))
};

});`

I managed to make it work separately if I don't use the Authorize globally on the Controller, but on each Action instead :

`
public class AccountController : Controller
{

[Authorize]
//This action only requires coockie auth (OK)
public IActionResult Index()
{
    return View();
}

[Authorize(AuthenticationSchemes = JwtBearerDefaults.AuthenticationScheme)]
// This action requires now only JWT auth  (OK)
[Authorize(AuthenticationSchemes = JwtBearerDefaults.Aut
public IActionResult Get()
{
return Ok(new[] { "One", "Two", "Three" });
}

}`

But I would like to find a way to keep my [Authorize] globally and specify for each needed API actions the JWT bearer auth [Authorize(AuthenticationSchemes = JwtBearerDefaults.AuthenticationScheme)] and only it.

Is there a way to do this ?

**Comment by Tratcher** [comment]
@HaoK

**Comment by HaoK** [comment]
@NicoSymo can you try turning off the `DefaultAuthenticateScheme` if you are currently setting it to cookies, and try explicitly setting the `AuthenticationSchemes = CookieDefaults.AuthenticationScheme` instead of using naked `[Authorize]` which relies on the `DefaultAuthenticateScheme`

Basically try a global `[Authorize(AuthenticationSchemes = CookieDefaults.AuthenticationScheme)]` and see if that helps.

**Comment by HaoK** [comment]
Actually never mind this won't work.  If you want either or, you basically just need to specify one scheme and turn off the automatic/default authentication...  

There shouldn't be any reason that you have to use the global `[Authorize]` right?

**Comment by NicoSymo** [comment]
The global `[Authorize]` on the controller is set to avoid me setting it to all other Actions of this controller.
Here is my use case :  I have in the same controller : all CRUD actions for a POCO which all require only the cookie auth (set by my global `[Authorize]`), and some actions that allows to make ajax calls from a CRUD web page (again with the cookie auth required) **AND** some API routes that will allow to be consummed by a third party client (which here requires JWT auth).

With the double auth in the same controller, the easy way will be to set the global `[Authorize]` on the controller, and for few API actions that requires a different auth set the JWT auth only.
But when doing such, the auth seem to be cumulative, not overriding the global one.

I don't know if there is way to handle this problem without having to set all specific Auth on each action of the controller (ie without repeating `[Authorize]` for all my required actions)

**Comment by HaoK** [comment]
So turns out there was indeed a bug where the attributes weren't combining correctly, I'll be fixing this via https://github.com/aspnet/Mvc/issues/6995
