### ISSUE TITLE
Q: How to return views from middlewares

### ISSUE THREAD

**Issue by evil-shrike** [aspnet/Home#2247]
I want to create a middleware such that I could return a view from it. I want to use it like `DeveloperExceptionPageMiddleware` and `StatusCodePagesMiddleware`  but in a single entity.

I realized that `DeveloperExceptionPageMiddleware` does something similar to what I need. But I can't understand how it works even after digging into its sources.

Here is the place where `DeveloperExceptionPageMiddleware` returns a view - https://github.com/aspnet/Diagnostics/blob/dev/src/Microsoft.AspNetCore.Diagnostics/DeveloperExceptionPage/DeveloperExceptionPageMiddleware.cs#L206

But what kind of view it is? It's definitely not a razor page (as it has no `@page` directive). Also it doesn't look like a normal mvc as it has construct in `@functions`. I can't create something similar in a normal aspnetcore project. In the Microsoft.AspNetCore.Diagnostics project there're two files for that view: `ErrorPage.cshtml` and `ErrorPage.Designer.cs`. How that Designer.cs file was created? It looks like a generated file. And thanks to it there's a normal class in the project (`ErrorPage`) which can be used explicitly. It inherits `Microsoft.Extensions.RazorViews.BaseView` class from `Microsoft.Extensions.RazorViews.Sources` package as I can understand.

So the middleware just executes that view:
```
var errorPage = new ErrorPage(model);
return errorPage.ExecuteAsync(context);
```
So, as the bottom line the question is how to achieve the similar logic of returning razor views from middlewares?

P.S. I hope it's appropriate that I repeated my question from [SO](https://stackoverflow.com/questions/46777617) here.

**Comment by pranavkm** [comment]
@evil-shrike we use https://github.com/aspnet/Razor/tree/dev/src/RazorPageGenerator to generate cs files that are written to disk (e.g. https://github.com/aspnet/Diagnostics/blob/dev/src/Microsoft.AspNetCore.Diagnostics/DeveloperExceptionPage/Views/CompilationErrorPage.Designer.cs). There's a shared source project - https://github.com/aspnet/Common/tree/dev/shared/Microsoft.Extensions.RazorViews.Sources - that provides enough boiler plate to allow rendering to an arbitary Stream.

Note: Neither of these packages are something we ship to NuGet (or support), but you may grab them from out CI \ nightly feeds.

**Comment by evil-shrike** [comment]
@pranavkm thank! 
I almost managed to get it working but RazorPageGenerator generates uncompilable codebehind for me.
For view:
```
@using Croc.XFW3.Web
@functions
{
	public ErrorPageModel Model { get; set; }
}
<!DOCTYPE html>
```
I get Designer.cs:
```
#line default
#line hidden
    internal class ErrorPage : Microsoft.Extensions.RazorViews.BaseView
    {
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
#line 2 "ErrorPage.cshtml"
Write(functions);

#line default
#line hidden
            WriteLiteral("\r\n{\r\n/*\r\n\tpublic ErrorPage(ErrorPageModel model)\r\n\t{\r\n\t\tModel = model;\r\n\t}\r\n*/\r\n\r\n\tpublic ErrorPageModel Model { get; set; }\r\n}\r\n<!DOCTYPE html>\r\n<body>\r\n<h1>Ой. Ой-ой-ой-ой! Кажется я застрял.</h1>\r\n</body>");
        }
        #pragma warning restore 1998
    }
```
The line `Write(functions);` is incorrect:
Error	CS0103	The name 'functions' does not exist in the current context	WebServer

And there's no such line in https://github.com/aspnet/Diagnostics/blob/dev/src/Microsoft.AspNetCore.Diagnostics/DeveloperExceptionPage/Views/ErrorPage.Designer.cs

I've used Microsoft.Extensions.RazorViews.Sources.2.1.0-preview1-27020 from https://dotnet.myget.org/feed/aspnetcore-dev/package/nuget/RazorPageGenerator

**Comment by pranavkm** [comment]
@NTaylorMullen any idea why `@functions` wouldn't work with RazorPageGenerator? ViewCompilation shouldn't affect this (it has no knowledge of the other package). Running it via `dotnet` seems fine although I suspect it's meant to work as a CLI tool. @kichalla would know best.

**Comment by NTaylorMullen** [comment]
The RazorPageGenerator [doesn't register the functions directive](https://github.com/aspnet/Razor/blob/dev/src/RazorPageGenerator/Program.cs#L42-L55). Basically  the generator is a super raw version of the Razor syntax. If you want to enable the default directives you can add the following lines to the RazorEngine creation lambda: https://github.com/aspnet/Razor/blob/dev/src/Microsoft.AspNetCore.Mvc.Razor.Extensions/RazorExtensions.cs#L18-L20

**Comment by evil-shrike** [comment]
Ok, I had to copy-paste and created my own RazorPageGenerator with suggested extensions. Everything works fine. I can compile view and create view class in runtime.
Thanks a lot!

Ideally RazorPageGenerator project would allow customizing RazorEngine instance. So in MainCore the call to `RazorEngine.Create` I'd suggest to extract into a method:
```
        public static int Main(string[] args)
        {
...
            var engine = CreateRazor();
            var results = MainCore(rootNamespace, targetProjectDirectory);
...
       }
       IRazorEngine CreateRazor()
       {
            var razorEngine = RazorEngine.Create(builder =>
            {
                builder
                    .SetNamespace(rootNamespace)
                    .SetBaseType("Microsoft.Extensions.RazorViews.BaseView")
                    .ConfigureClass((document, @class) =>
                    {
                        @class.ClassName = Path.GetFileNameWithoutExtension(document.Source.FilePath);
                        @class.Modifiers.Clear();
                        @class.Modifiers.Add("internal");
                    });

                builder.Features.Add(new SuppressChecksumOptionsFeature());
            });
       }

       public static IList<RazorPageGeneratorResult> MainCore(IRazorEngine engine, string rootNamespace, string targetProjectDirectory)
        { ... }
```
Then it could be possible to call MainCore from an own generator and not repeating all other logic.
Do you mind if I create a PR with such a change?

**Comment by pranavkm** [comment]
Sure, that seems reasonable.

**Comment by evil-shrike** [comment]
https://github.com/aspnet/Razor/pull/1727

**Comment by IanKemp** [comment]
For those who are looking for RazorPageGenerator as of 3.0: https://github.com/aspnet/AspNetCore/blob/release/3.0/src/Middleware/Diagnostics/src/README.md
