### ISSUE TITLE
HRESULT for OPTION/GET request

### ISSUE THREAD

**Issue by mgrishkov** [aspnet/Home#2248]
I faced a problem with OPTION/GET requerst to AspNet.Core WebApi service. In some cases (I cannot identify when) client get 500 error with header X-Error-HRESULT:80090321 or X-Error-HRESULT: 80072F8F.

The application is hosted in Service Fabric cluser. My investigation failed. @amanbha recommended me to create an issue for aspnetcore repo. For further information see [issue in service-fabric-aspnetcore repo](https://github.com/Azure/service-fabric-aspnetcore/issues/29).

Request-response example
```
Request URL:https://?????
Request Method:GET
Status Code:500 Internal Server Error
Remote Address:???.???.???.????:443
Referrer Policy:no-referrer-when-downgrade

Response Headers
Content-Length:0
Date:Tue, 05 Sep 2017 15:01:35 GMT
Server:Microsoft-HTTPAPI/2.0
X-Error-HRESULT:80090321
```
P.S. According to the NDA I have to hide some information with ?-symbol

**Comment by Tratcher** [comment]
Asp.Net Core does not send X-Error-HRESULT headers.
Does anything show up in your application logs?
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging?tabs=aspnetcore2x

**Comment by mgrishkov** [comment]
Unfortunately, application log and system log does not contain any mention of the error.

**Comment by mgrishkov** [comment]
Unfortunately, It seems that issue connected with environment. The issue may be closed.
