### ISSUE TITLE
Improve the folder / filename casing situation

### ISSUE THREAD

**Issue by Tragetaschen** [aspnet/Home#225]
There are many places throughout the new stack, where files and folders are used by convention and fetched from the filesystem. On Windows the casing does not matter, but on Linux (I don't know MacOS) every character counts.

Some examples are:
- It's NuGet.Config (not Nuget.config or NuGet.config or nuget.config)
- It's compiler/preprocess/ (not Compiler/Preprocess/ or Compiler/PreProcess/)
- It's _viewstart.cshtml (not _ViewStart.cshtml)

For developers on Windows it's quite easy to fall into the trap of using the wrong casing and not recognizing it until building or running on Linux fails in hard to debug ways:
- Pages are rendered, but the chrome from the _ViewStart.cshtml is missing
- Razor Views are not precompiled as advertised

In addition, it's quite hard with git on Windows to change the casing of commited objects--you have to rename to a different filename first.

I have created [some](https://github.com/aspnet/KRuntime/pull/943) [PRs](https://github.com/aspnet/Mvc/pull/1679) to fix occurences I stumbled uppon, but this is an uphill battle.

I'm not sure, what a right solution is:
- Abstracting away file access to hide either Linux' or Windows' behavior
- Tooling support to give errors when special names have the wrong case
- Runtime errors on Windows?
- etc.

But my gut feeling says, something needs to change.

**Comment by Bartmax** [comment]
I think wrong casing should give errors on windows too. Specially now on projects shared with multiple developers/platforms.

**Comment by Alxandr** [comment]
@Bartmax I sort of agree, but one problem with that is that explorer on windows doesn't really allow you to recaps file-names. If I have a file/dir named `test`, and I try to rename it `Test`, it doesn't work (at least not always). I have to go by another temp name to get it working.
