### ISSUE TITLE
Performance issue with IFormFile

### ISSUE THREAD

**Issue by Petermarcu** [aspnet/Home#2250]
opened by @prashanthi-ediga here: https://github.com/dotnet/core/issues/1031 

# Issue Title

Reading the stream from http posted file using IFormFile is very slow.

# General

We have implemented an ASP.Net application to read very large Excel Files(100 MB).
Our requirements was to not save the file to any temp location or save file at server.

So, we have implemented an API which reads stream data using 'HttpPostedFileBase' and send this stream to openXMLReader. The performance is very good and we were able to achieve good results with 100 MB file for 1000 concurrent users in a ramp up period of 5 minutes.

Recently,we had to move to .net core in which 'HttpPostedFileBase' was not supported.
So I am using IFormFile to read stream data and pass it to excelReader.
But the performance degraded to a great extent.As the number of concurrent users increase the performance is degrading rapidly.

I have seen few blogs stating to use 'MultipartReader' for large files.But this is storing the stream to a temporary path which is not possible in our scenario.

Code Sample:
[HttpPost]
        public string ReadExcel_OpenXML(IFormFile postedFile)
        {
            var inputStream = postedFile.OpenReadStream();
             ....
         }
Can you please suggest any alternative or fix to this.
Please let me know if you need any other details.

Thanks,
Prashanthi.

**Comment by Tratcher** [comment]
@prashanthi-ediga, MultipartReader does not store data in a temp file by default. You control where the content goes, see this sample:
https://github.com/aspnet/Entropy/blob/1a4d2e0607c374b8c2aa2403029d9cb4ad33db20/samples/Mvc.FileUpload/Controllers/FileController.cs#L57

**Comment by prashanthi-ediga** [comment]
Hi @Tratcher,

I need to get the data directly as a stream. In the example that you have mentioned the stream is stored at :
targetFilePath = Path.Combine(_hostingEnvironment.ContentRootPath, Guid.NewGuid().ToString()); 

Can you please provide an example or guide me to directly get the data as stream instead of storing it to temp file. 

Thanks,
Prashanthi.

**Comment by Tratcher** [comment]
fileSection.FileSteam is the name of the raw file upload stream in that sample. Pass that to your Xml reader.

**Comment by Eilon** [comment]
Closing this issue because it isn't clear to me if there is an issue remaining. If you feel there's still an issue, please re-open this issue or log a new issue with complete details of the problem. Thanks!
