### ISSUE TITLE
How to get configure setting  in starup.cs ConfigureServices

### ISSUE THREAD

**Issue by TimRowe** [aspnet/Home#2251]
As we know, we can get setting in starup.cs Configure function with ioc inject. But I want to get setting value in ConfigureServices function wich run before Configure function. How can i get AppSettings value in ConfigureServices  like below?

```c#
    public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }
        public IConfiguration Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            //appsetting
            services.Configure<AppSettings>(Configuration.GetSection("AppSettings"));
            
            //can i get the setting value here? because i want to confiure service with setting.such as sql connection string.
        }
    }
```

**Comment by TimRowe** [comment]
Anyone help? @Tratcher

**Comment by Tratcher** [comment]
Not much to say beyond confirming your observations. Your other components either need to read config for themselves or DI inject AppSettings and read it from there.

**Comment by mariomixtegapach** [comment]
Maybe this could help.
https://blogs.msdn.microsoft.com/warnov/2017/01/16/net-core-cmo-usar-app-settings-en-una-aplicacin-de-consola/
