### ISSUE TITLE
where it sets default implementation of IDistributedCache

### ISSUE THREAD

**Issue by TimRowe** [aspnet/Home#2252]
As we know in https://docs.microsoft.com/en-us/aspnet/core/fundamentals/app-state?tabs=aspnetcore2x.
We need to Adds a default in-memory implementation of IDistributedCache like below.
```c#
public void ConfigureServices(IServiceCollection services)
{
    services.AddMvc();

    // Adds a default in-memory implementation of IDistributedCache.
    services.AddDistributedMemoryCache();

    services.AddSession(options =>
    {
        options.Cookie.Name = ".AdventureWorks.Session";
        options.IdleTimeout = TimeSpan.FromSeconds(10);
    });
}
```

But I found that `services.AddDistributedMemoryCache()` is not necessary，session can work without that. 

```c#
public void ConfigureServices(IServiceCollection services)
{
   services.AddMvc();
   services.AddSession();
}
```
As we know session is depend on IDistributedCache. **So, where it sets default in-memory implementation of IDistributedCache?** I have found `Microsoft.AspNetCore.Session` `Microsoft.AspNetCore.Caching` `Microsoft.AspNetCore.Mvc`, but not result.

Any one help?

**Comment by Tratcher** [comment]
https://github.com/aspnet/Mvc/blob/068c91dbecc4e77165962743d37617344d6c8990/src/Microsoft.AspNetCore.Mvc.TagHelpers/DependencyInjection/TagHelperExtensions.cs#L34

**Comment by TimRowe** [comment]
It is called by `services.AddMvc();` @Tratcher ,  Thanks very much  !!!
