### ISSUE TITLE
System.Web.HttpRequest.UrlReferrer throws exception

### ISSUE THREAD

**Issue by asalih** [aspnet/Home#2255]
Hi, according to the source code below, UrlReferrer catches HttpException. For example if you send the url like "http://localhost" (with quotes), throws System.UriFormatException: 'Invalid URI: The URI scheme is not valid.'

https://github.com/Microsoft/referencesource/blob/master/System.Web/HttpRequest.cs#L1967

**Comment by Tratcher** [comment]
This organization is for ASP.NET Core, not System.Web. @muratg is there a better place to refer this?

**Comment by muratg** [comment]
Perhaps this repo: https://github.com/aspnet/aspnetwebstack? 

cc @Eilon

**Comment by Eilon** [comment]
Nope, this type is part of .NET Framework. I recommend filing an issue using Visual Studio's "Feedback" button and the issue will be directed to the appropriate team.
