### ISSUE TITLE
Using ASP.NET MVC Customed AuthorizeAttribute in ASP.NET Core

### ISSUE THREAD

**Issue by huyjack178** [aspnet/Home#2256]
I have AuthorizeAttribute in my old ASP.NET MVC project like this

```
    public class CustomAuthAttribute : AuthorizeAttribute
    {
            public override void OnAuthorization(AuthorizationContext filterContext)
            {
                base.OnAuthorization(filterContext);
                ...
            
            }
    }
```

I want to use this attribute in new site that uses ASP.NET Core MVC Controller/Action.
I have tried to configure in Startup.cs like this

```
     services.AddMvc(options =>
     {
          options.Filters.Add((new CustomAuthAttribute());
     });
```

But it can not resolve the type IFilterMetadata. 
Moreover, I try to use this Attribute in Controller but nothing happens.

```
    [CustomAuth]
    public class HomeController : Controller
```

Anyone can help me? Thank you

**Comment by damienbod** [comment]
@huyjack178 You should use Policies for this now.

https://docs.microsoft.com/en-us/aspnet/core/security/authorization/policies

Greetings Damien

**Comment by huyjack178** [comment]
How can I reuse the old one. Because there is a lot of code need to be implemented if I use Policies

**Comment by damienbod** [comment]
@huyjack178 you can't. You could also try to use ActionFilters which return 401, 403 if it's too much effort to rewrite, this would be less effect. But the action filters are executed much later in the request pipe.

Greetings Damien

**Comment by Yeganloo** [comment]
> @huyjack178 you can't. You could also try to use ActionFilters which return 401, 403 if it's too much effort to rewrite, this would be less effect. But the action filters are executed much later in the request pipe.
> 
> Greetings Damien

Hi

i'am not using a role base authorization, but this make me using Authorize attribute that has a Role property!
It makes some misunderstanding about my authorization policy!
It should be possible to replace auth attribute with some costume one.
