### ISSUE TITLE
ASP.NET MVC fails with 400 when Chinese characters are in cookies

### ISSUE THREAD

**Issue by Petermarcu** [aspnet/Home#2259]
@netnr opened this here: https://github.com/dotnet/core/issues/1049

# Issue Title
`asp.net core 2.0 mvc` 
Development project, cookies has Chinese, access site return error code: 400

# General

![1.png](https://i.loli.net/2017/10/27/59f27ec08b50f.png)
![2.png](https://i.loli.net/2017/10/27/59f27ec093424.png)
![3.png](https://ooo.0o0.ooo/2017/10/27/59f27ec097fc0.png)

**Comment by Tratcher** [comment]
@JunTaoLuo ?

**Comment by netnr** [comment]
Chinese：
调试过程中，我只是改变 cookie是否含有中文，没中文一切正常，含有中文，页面空白，也没有异常抛出，只看到控制台400错误，或许是内部问题。

English：
In the process of debugging, I just change the cookie whether it contains Chinese, no Chinese is normal, containing Chinese, blank pages, and no exception thrown, only see console 400 error, perhaps internal problems.

**Comment by Tratcher** [comment]
Chinese characters are not allowed in any http header (including cookies) without additional encoding.

**Comment by Tratcher** [comment]
See https://github.com/aspnet/KestrelHttpServer/issues/1144

**Comment by netnr** [comment]
If that's the case, it's unscientific  

![face](https://assets-cdn.github.com/images/icons/emoji/unicode/1f604.png)

**Comment by ingdotrodriguezbarrios** [comment]
This need to be closed?

**Comment by Eilon** [comment]
Yup, closing.
