### ISSUE TITLE
Bootstrap 4 Beta deprecation of Bower

### ISSUE THREAD

**Issue by nixxholas** [aspnet/Home#2261]
https://github.com/twbs/bootstrap/issues/24525#issuecomment-340321193

This issue is linked to bootstrap. Question is, will the templates update as well? This is very unhealthy for newcomers to .NET Core. A viable replacement for the current template should be present.

**Comment by natemcmaster** [comment]
We have been working to remove Bower from our templates. Let us know if your find any more in https://github.com/aspnet/templating.

cref https://github.com/aspnet/templating/issues/161
