### ISSUE TITLE
Streaming IObservable<T> to specific client and not all connected clients.

### ISSUE THREAD

**Issue by Sabdeth** [aspnet/Home#2263]
Hello,

I would like to know if there's a way to Stream an IObservable<T> to a specific client. The StockTickr example shows a way to Stream stocks but it is streaming for all connected clients.  Can we stream different data depending on the connected client's request? 

```
  public IObservable<Stock> StreamStocks()
  {
       return _stockTicker.StreamStocks();       
  }
```

[StockTickr Example](https://github.com/aspnet/SignalR-samples/tree/master/StockTickR/StockTickRApp)

**Comment by BrennanConroy** [comment]
Sure, if you take a look at this sample:
https://github.com/aspnet/SignalR/blob/83bb07d5a4282a7486d5ef426f53633db1f083ae/samples/SocketsSample/Hubs/Streaming.cs#L11-L16
Every time the Hub method is called a new observable is created. The stock ticker just caches its stream for obvious reasons, but you aren't limited to that.

Also, SignalR issues should go to the SiganlR repo https://github.com/aspnet/SignalR/issues
