### ISSUE TITLE
Hi,where can i find the netcore icon and logo

### ISSUE THREAD

**Issue by zuosc** [aspnet/Home#2264]
![qq 20171101122214](https://user-images.githubusercontent.com/8411781/32259957-664d3cb8-beff-11e7-99aa-0f57b0e2802a.png)

as marked in the picture。

And I want some high resolution picture.

Thank you!

**Comment by MaximRouiller** [comment]
Hi @zuosc,

This is a fanmade logo. 

@campusMVP's repository can be found here: https://github.com/campusMVP/dotnetCoreLogoPack

**Comment by zuosc** [comment]
@MaximRouiller   Finally I Use @campusMVP's repository ,  it's very good.

Thank you!
