### ISSUE TITLE
Exception thrown: 'System.ArgumentException' in Microsoft.AspNetCore.Routing.dll

### ISSUE THREAD

**Issue by masaab** [aspnet/Home#2265]
I am writing some Integration Test in asp.net core api using TestServer. My action are not being called in the controller. It is always throwing errors like below. 

Exception thrown: 'System.ArgumentException' in Microsoft.AspNetCore.Routing.dll

Exception thrown: 'Microsoft.AspNetCore.Routing.RouteCreationException' in Microsoft.AspNetCore.Mvc.Core.dll

Exception thrown: 'Microsoft.AspNetCore.Routing.RouteCreationException' in System.Private.CoreLib.dll

**Comment by Tratcher** [comment]
What is the stack trace and message for those exceptions? (e.g. ToString())

**Comment by nixxholas** [comment]
@masaab Any solution?
