### ISSUE TITLE
StartupLoader

### ISSUE THREAD

**Issue by ahmetatar** [aspnet/Home#2269]
When I want to use convention based startup by environment I need to pass the assembly name to the UseStartup method.What is the subtle idea underneath this?Because it could be in another assembly? When I want to use the Generic version of this method, I specify exactly which startup class it should use.But when I was using the convention-based method UseStartup, I would prefer to search in the calling assembly.So I would not have to write a code like this;

```
public static IWebHost BuildWebHost(string[] args) => WebHost.CreateDefaultBuilder(args)
        .UseStartup(typeof(Program).Assembly.FullName)
        .Build();
```

Instead of;

```
public static IWebHost BuildWebHost(string[] args) => WebHost.CreateDefaultBuilder(args)
        .UseStartup()
        .Build();
```

It may be absurd, but I was really curious :)

**Comment by Tratcher** [comment]
Trying to make decisions based on the calling assembly identity has always been problematic for library APIs. It breaks down very quickly when your method gets wrapped by another method one in another assembly. Call stack is not a good indicator of intent.

**Comment by ahmetatar** [comment]
@Tratcher thank you for answer.
