### ISSUE TITLE
I have Console and NETStandard project. Unable to add razor page.

### ISSUE THREAD

**Issue by KalpeshChheda** [aspnet/Home#2270]
Hi,

I am trying to add razor page to NETStandard Project. But i cant find option for that. If I manually add cshtml file it does not generate backing C# file. In Visual Studio I have installed web application feature as well.
I want to generate html form cshtml. Is CSHTML/Razor support on netstandard? 

Thanks.

**Comment by NTaylorMullen** [comment]
Hi @KalpeshChheda did you create a `ASP.NET Core Web Application`? The Razor page item template is not shown for other project types 😄

**Comment by KalpeshChheda** [comment]
Hi @NTaylorMullen 
NETStandard project have one more issue. If we set RazorTemplatePreprocessor property of cshtml file, it wont generate compile version CS file as well. https://github.com/dotnet/project-system/issues/2687

**Comment by NTaylorMullen** [comment]
@KalpeshChheda ya the custom tool bit seems like a Roslyn project system issue. In the web project you're not able to set the tool at all. 

If you're looking to pre-compile your Razor views take a look at the the pre-compilation docs: https://docs.microsoft.com/en-us/aspnet/core/mvc/views/view-compilation?tabs=aspnetcore2x

**Comment by Eilon** [comment]
@NTaylorMullen / @rynowak - where should this bug go?

**Comment by NTaylorMullen** [comment]
> @NTaylorMullen / @rynowak - where should this bug go?

It sounds like this issue was resolved. I'd suggest closing 😄
