### ISSUE TITLE
Will Razor view issues with C# LangVersion be fixed in 2.0.3?

### ISSUE THREAD

**Issue by markrendle** [aspnet/Home#2274]
Right now, Razor Views are a mess in VS2017.4 and Rider 2017.2. None of the contextual actions for creating or navigating to views work, and I've got red squiggles all over the place, although it all builds and runs fine.

It appears to be down to something with the language version, so I'm hoping it will be fixed in the patch, maybe [this issue](https://github.com/aspnet/Mvc/issues/6611)?

**Comment by Tratcher** [comment]
@NTaylorMullen

**Comment by NTaylorMullen** [comment]
I can't respond to it working or not in Rider but for VS2017.4 it should work. @markrendle if you do file => new web application does everything work fine for you?

**Comment by pranavkm** [comment]
@markrendle that's the right issue. By the way, for 2.0.0, you should be able to work around this issue by using `<LangVersion>Latest</LangVersion>`.

**Comment by markrendle** [comment]
I'll try it with the patched bits released today, but with VS2017.4 + ReSharper, and with Rider 2017.2 and 2017.3 EAP, using `<LangVersion>latest</LangVersion>` wasn't working... was the issue with case-sensitivity? If so, _d'oh_.

**Comment by Eilon** [comment]
@NTaylorMullen / @rynowak / @pranavkm - where should this issue go?

**Comment by pranavkm** [comment]
There's nothing to do here. The fix has been available since 2.0.3, so updating the package should resolve the issue.
