### ISSUE TITLE
Question about AspNetCore 2.0 View Precompilation

### ISSUE THREAD

**Issue by valeriob** [aspnet/Home#2275]
I'm trying to deploy an aspnetcore 2.0 application running on .net framework 4.6.1.
I can't precompile views yet, because a missing piece on octopus tooling, so i need to comple views at runtime on the server. 
Right now the server only has Windows Server Hosting, but it fails to compile any view because an assembly missing (Microsoft.CSharp.dll).
What are the requirement to support this workflow on the server ? the full .netcore sdk, the runtime, or what else ?
From the error message it looks for .net framework 461 reference assemblies, why is that (the server already have .net 461 installed)?

Thanks

**Comment by Eilon** [comment]
@pranavkm any ideas?

**Comment by joeaudette** [comment]
I'm pretty sure you can solve this problem by disabling precompilation in your .csproj file like this:

    <PropertyGroup>
        <TargetFramework>netcoreapp2.0</TargetFramework>
        <PreserveCompilationContext>true</PreserveCompilationContext>
        <MvcRazorCompileOnPublish>false</MvcRazorCompileOnPublish>
    </PropertyGroup>

that should disable precompilation and include what is needed to compile the views at runtime

**Comment by valeriob** [comment]
Thanks @joeaudette i was doing that, but it made me discover that Octopack was not picking up the refs folder 😄 !
