### ISSUE TITLE
Please improve all stupid setups - If installations exist than they need "SKIP"

### ISSUE THREAD

**Issue by sourceskyboxer** [aspnet/Home#2277]
Hey everyone, 

I feel mad because your setups are not knowing to "Skip since existed installations"

I am really stupid because if AZURE SDK Installer like Webplatform Installer always throws error like
We are sorry... = What is it meaning?

I think it doesn't understand If I have already installed package than setup need to know for existed installed packages than they need call "your packages already installed = exist than skip because you have installed packages."

Please fix all setups while existed installed packages. Thanks!

**Comment by Tratcher** [comment]
@joeloff

**Comment by joeloff** [comment]
To which installer are you referring?

**Comment by sourceskyboxer** [comment]
just Azure SDK Webinstaller if you don't know if it install and throws 
X "We're sorry ..."
Success any installed packages

@joeloff Why do you ask question?
Why do you not check Web-Installer like IIS 7 Installer or Azure SDK Installer has always throw error if I have installed example Net Core 1.0 - ( Packages ) - Error return 1. Please make sure "skip" if I already installed packages. PS: I hate if Installers throw error if I already installed packages. Why do Microsoft's Setups make shit unknown errors. Please fix and check already-installed packages and will return to "Skipped Net Core 1.0 - ( Packages ) - Already installed!" It means nothing error message just it is already installed.

**Comment by Eilon** [comment]
@joeloff - any idea where this bug should go?

**Comment by joeloff** [comment]
@sourceskyboxer can you please point to the specific installer in question, e.g. provide a URL?

**Comment by Major88** [comment]
Pisz po Polsku albo wcale

08.01.2018 18:04 "Jacques Eloff" <notifications@github.com> napisał(a):

**Comment by joeloff** [comment]
@Eilon  I suspect this is happening on Dev14 as it's the only version of VS currently supported by the Azure SDK install that would potentially bring in .NET Core 1.0, but we probably need either the setup logs and/or the installer URL to confirm.

**Comment by Eilon** [comment]
Hi. We're closing this issue as no response or updates have been provided in a timely manner and we have been unable to reproduce it. If you have more details and are encountering this issue please add a new reply and re-open the issue.
