### ISSUE TITLE
Readme for release branch points to master KVM install

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Home#228]
The Readme.md and KVM install ps1 are customized in each branch to point to different feeds. However, the install command in the release branch readme points to the master branch copy of the ps1 (which points to master feed).

Change this:
`@powershell -NoProfile -ExecutionPolicy unrestricted -Command "iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/aspnet/Home/master/kvminstall.ps1'))"`

to this:
`@powershell -NoProfile -ExecutionPolicy unrestricted -Command "iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/aspnet/Home/release/kvminstall.ps1'))"`

**Comment by Praburaj** [comment]
This seems to be fixed.
