### ISSUE TITLE
Runtime store eula under program files by itself

### ISSUE THREAD

**Issue by Petermarcu** [aspnet/Home#2280]
Was just browsing and noticed that under program files there is a eula for the runtime store"

"C:\Program Files\Microsoft ASP.NET Core Runtime Package Store\2.0\eula.rtf"

I'm pretty sure that was intended to go with all the other files in the runtime store and not in its own place all by itself.

**Comment by natemcmaster** [comment]
@joeloff is this placed on disk by our installers?

cc @Eilon

**Comment by joeloff** [comment]
Yup, that's from the installer. We can move it a different location. Any suggestions? Perhaps in the dotnet folder?

**Comment by Petermarcu** [comment]
At the root of the runtime store? I didn't look at the contents. What does the eula apply to? Is it just the one for the setup about redist rights, etc?

**Comment by joeloff** [comment]
Sure, we can add it there. It's just the plain old .NET Library EULA I beleive

**Comment by Eilon** [comment]
@joeloff what repo should this go to?

**Comment by joeloff** [comment]
SetupSharedframework and if we want to do this retroactively for 2.0.x releases, SetupCrossgen too

**Comment by Eilon** [comment]
Doesn't seem patch-worthy. Which repo(s) track 2.1 work for this?

**Comment by joeloff** [comment]
For 2.1, SetupSharedFramework

**Comment by Eilon** [comment]
Moved to https://github.com/aspnet/SetupSharedFramework/issues/2.
