### ISSUE TITLE
Future of legacy asp.net mvc (QUESTION)

### ISSUE THREAD

**Issue by albertoVieiraNeto** [aspnet/Home#2283]
Hi.

Maybe someone here can help me with this question, I'm working on a fairly large project and we intend to use asp.net MVC but apparently, there is some noise about the future (or I missed something) of this platform because Microsoft is putting all their effort on .Net Core, this causes further confusion due to the strange renaming the took place last year, meaning EF 7 now EF Core, Asp.net MVC 6 now Asp.Net Core.

So will The current Asp.Net continue to be supported and **receive updates.**??

**Comment by Eilon** [comment]
Hi @albertoVieiraNeto , we have been doing some work on ASP.NET MVC 5.x, but not a lot. You are correct that the main focus has been on ASP.NET Core.

We're currently working on the MVC 5.2.4 release, and you can see the bug fixes and features that we've done (or are working on) here: https://github.com/aspnet/AspNetWebStack/issues?utf8=%E2%9C%93&q=is%3Aissue+milestone%3A5.2.4+-label%3Atask

We expect to have a preview out soon, and then a final release shortly after.
