### ISSUE TITLE
Infinite Loopback between asp.net core 2.0 controller and login.microsoft.com inside office addins

### ISSUE THREAD

**Issue by Petermarcu** [aspnet/Home#2287]
@vskeid opened this here: https://github.com/dotnet/core/issues/1075

hi,
    We have migrated our application to asp.net core 2.0  from 1.1.   Before migration the application used to work in the browser and within word office 365 app task pane.

After asp.net core 2.0 migration the oidc flow and the cookie authentication is working fine in chrome and IE,  but it is failing with infinite loop back between login.microsoft.com and the controller.   Seems that cookie is not being set or being deleted inside office app.

 

                        //Cookies is responsible for two things:
                        //Signing the user in (creating the authentication cookie and returning it to the browser)
                        //Authenticating cookies in requests and creating user principals from them
                  
                        //Open Id Connect is responsible for Responding to challenges from[Authorize] or ChallengeResult returned from controllers.

                       
                        services.AddAuthentication(auth => {

                            auth.DefaultScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                            auth.DefaultChallengeScheme = OpenIdConnectDefaults.AuthenticationScheme;
                            auth.DefaultAuthenticateScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                            auth.DefaultSignInScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                        })
                       
                             .AddCookie(options =>
                             {
                                 options.Cookie.SameSite = SameSiteMode.Lax;
                                 options.Cookie.HttpOnly = false; //// If True - Javascript will not be able to read cookie.
                                                                  // options.Cookie.SameSite = SameSiteMode.Lax;
                                 options.Cookie.SecurePolicy = CookieSecurePolicy.Always; // Supports only HTTPS
                                 options.SlidingExpiration = config.AzureAD.AllowCookieSlidingExpiration;
                                 options.ExpireTimeSpan =  TimeSpan.FromMinutes(config.AzureAD.CookieExpireTimeSpanInMinutes);

                                 //options.Events = new CDNGCookieAuthenticationEvents();
           
                             })
                            .AddOpenIdConnect(OpenIdConnectDefaults.AuthenticationScheme, "AAD",options => {
                                options.ClientId = config.AzureAD.ClientId;
                                options.ClientSecret = config.AzureAD.ClientSecret;
                                options.Authority = config.AzureAD.CommonAuthority;
                                options.SignInScheme = CookieAuthenticationDefaults.AuthenticationScheme;

                                options.ResponseType = OpenIdConnectResponseType.CodeIdToken;
                                
                                options.CallbackPath = config.AzureAD.CallBackURL;

                                
                                // GetClaimsFromUserInfoEndpoint = true;
                                options.UseTokenLifetime = false; // if Set to true, id Token expiration will not be used  but auth token (managed by ad) expiration will be used. 
                                                                  // This can create logouts after  one hour since access token is valid only for an hr.
                                                                  // If set to false, cookie expiration will be used using sliding expiration

                                options.TokenValidationParameters = new TokenValidationParameters
                                {
                                    // Instead of using the default validation (validating against
                                    // a single issuer value, as we do in line of business apps), 
                                    // we inject our own multitenant validation logic
                                    ValidateIssuer = true,
                                    ValidateAudience = true,

                                    NameClaimType = "name"
                                };

                                options.SaveTokens = false; // No need to save Access Token in Cookie

                                options.Events = new WebAppOIDCEvents(config);
                                // adding here since scope is read, but scope.add allows set
                                options.Scope.Add(OIDCScope.OpenID);
                                options.Scope.Add(OIDCScope.Profile);
                                options.Scope.Add(OIDCScope.Offline_Access);

Thanks
Suresh

**Comment by Tratcher** [comment]
This issue was moved to aspnet/Security#1554
