### ISSUE TITLE
Invalid Content Disposition Header

### ISSUE THREAD

**Issue by Petermarcu** [aspnet/Home#2288]
@StefanoD opened this here: https://github.com/dotnet/core/issues/1106

According to https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition the parameters of the content disposition header must be quoted. Instead APS.Net Core sends them without quote:

`attachment; filename=latest_bin.txt; filename*=UTF-8''latest_bin.txt`

I'm using .Net Core 2.0

**Comment by Tratcher** [comment]
This issue was moved to aspnet/HttpAbstractions#973
