### ISSUE TITLE
NuGet package naming

### ISSUE THREAD

**Issue by senj** [aspnet/Home#2290]
Hi guys,
you naming concept of ~.primitives, ~.abstraction ... very interesting.
Is there a guide where you describe the naming scheme nuget aspnet core nuget packages?

**Comment by natemcmaster** [comment]
There is no guide AFAIK. Here are some general patterns we follow.

- Microsoft.Extensions.\* - provide infrastructure APIs commonly needed to building .NET apps. Dependency injection, logging, app configuration.
- Microsoft.AspNetCore.\* - APIs specific to building web application.
- Microsoft.EntityFrameworkCore.\* - APIs specific to EF Core (a data access framework) (SQL Server, SQLite)
- \*.Abstractions - Interfaces only. Implementations live in a separate package.

Closing for now. Feel free to continue discussion if you have more questions.
