### ISSUE TITLE
[Discussion] aspnetcore-ci-*, aspnetcore-volatile-* feeds being deprecated

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Home#2292]
As part of some of our infrastructural changes, we're discontinuing the use of the following feeds and may remove them entirely in the future:
* https://dotnet.myget.org/f/aspnetcore-ci-dev 
* https://dotnet.myget.org/f/aspnetcore-ci-release
* https://dotnet.myget.org/f/aspnetcore-volatile-dev
* https://dotnet.myget.org/f/aspnetcore-volatile-release

If you're currently using one of these feeds in your projects to pick up our daily builds, we recommend migrating to https://dotnet.myget.org/f/aspnetcore-dev.

**Comment by natemcmaster** [comment]
Closing as we have condensed even more, and recommend using https://dotnet.myget.org/gallery/dotnet-core for official daily builds.
