### ISSUE TITLE
Unable to write to response using Action filter - OnActionExecuted method

### ISSUE THREAD

**Issue by brightcr** [aspnet/Home#2296]
It is caused by code:
`context.HttpContext.Response.Body.Write(bytes, 0, bytes.Length);`
The bytes contains text converted to bytes using `Encoding.Unicode.GetBytes` method.

Getting below error:
```
System.InvalidOperationException: Headers are read-only, response has already started.
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.FrameHeaders.ThrowHeadersReadOnlyException()
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.FrameHeaders.Microsoft.AspNetCore.Http.IHeaderDictionary.set_Item(String key, StringValues value)
   at Microsoft.AspNetCore.Http.Internal.DefaultHttpResponse.set_ContentType(String value)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.<ExecuteAsync>d__22.MoveNext()
```
More details:
Asp.Net Core: 2.0
Visual Studio: 2017
OS: Windows 10 1607

**Comment by Tratcher** [comment]
Why are you trying to do that? The problem is that MVC tries to render the view from your controller after you've already started the response. Are you trying to replace the view's contents, or augment it?

@rynowak

**Comment by brightcr** [comment]
I am using for quick profiling of time taken in action by augmenting the message at end.
This approach works fine with Previous Asp.Net MVC 5 .Net version.

**Comment by halter73** [comment]
@brightcr It looks like issue is that you are writing to the body *before* the ViewExecuter runs. This flushes the headers preventing the ViewExecuter to modify them. If you were really writing to the end of the body, it would probably work assuming the response is chunked.

**Comment by brightcr** [comment]
Below is code I am using:

```
   public class ProfileAttribute : ActionFilterAttribute
    {
        private Stopwatch sw;

        public override void OnActionExecuting(ActionExecutingContext context) 
            => sw = Stopwatch.StartNew();

        public override void OnActionExecuted(ActionExecutedContext context)
        {
            sw.Stop();
            string message = $"<div>Elapsed: {sw.ElapsedMilliseconds} ms</div>";
            byte[] bytes = Encoding.Unicode.GetBytes(message);
            context.HttpContext.Response.Headers.Add("Perf", new string[] { message });
            context.HttpContext.Response.Body.Write(bytes, 0, bytes.Length);
        }
    }
```
Perf header is added but response gets empty.

**Comment by Eilon** [comment]
This appears to be exactly what @halter73 said. The filter is writing to the response body, which means that the headers cannot be changed. Then, when MVC tries to render a view, it tries to set headers, which causes this exception. It is recommended that filters either not write to the body at all, or if they do, that they end the request there by preventing the result from executing.
