### ISSUE TITLE
Cultures Issue in Dotnet Core 2.0

### ISSUE THREAD

**Issue by dexterhussain** [aspnet/Home#2297]
I have been working with ASP.Net cultures for a long time and also working on Core 1.0 . Deployed many websites on kestrel using Nginx having no issues. This is first time that I added cultures to my website which are working fine on development machine as soon I deploy it on my Ubuntu Server it starts giving these errors
common.js:22 GET http://(IP)/api/culture/SupportedCultures 500 (Internal Server Error)

the server is not sending any of the api calls.
The server starts properly on port 5000.

Content root path: /home/pgc/publish
Now listening on: http://localhost:5000
Application started. Press Ctrl+C to shut down.

Nginx has most basic configuration just forwarding packets to the backend.
I am unable to sort any issues. Please help if anyone knows.

**Comment by Eilon** [comment]
@dexterhussain sorry for the delay getting back to you. Are you still experiencing this issue? Can you provide more details about your app?
