### ISSUE TITLE
Question. Asp net core apps Memory and cpu limits

### ISSUE THREAD

**Issue by oerodriguezn** [aspnet/Home#2300]
How can i configure asp dot net core to have memory and/or cpu usage limits like IIS app pools settings. We would like to use kestrel without IIS but we need to be able to setup that kind of resources usage limits to our applications.

**Comment by Tratcher** [comment]
IIS uses Job Objects for that and so can you. See https://stackoverflow.com/questions/192876/set-windows-process-or-user-memory-limit

**Comment by oerodriguezn** [comment]
Thanks. Do you have any example implementing  ALM with Job Objects?. We want to be able to deploy from VSTS and create a Job Object per app deployed.

**Comment by Eilon** [comment]
Hi. This looks like this is a question about how to use IIS. While we do our best to look through all the issues filed here, to get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the 'iis' tag, or to the IIS forums at https://forums.iis.net/.
