### ISSUE TITLE
Using Angular2's UniversalModule in a ASP.NET Core project causes application to crash

### ISSUE THREAD

**Issue by Albemuth84** [aspnet/Home#2301]
I'm pretty sure this belongs here as the issue seems to be related more to VS/ASP.NET Core setup to work with Angular2 rather than anything else.

So I have set up Visual Studio 2017 to work with Angular2 and I can run the demo application just fine. However, if I try to import UniversalModule in app.module.ts, the application crashes with a *TypeError: Cannot read property 'getDOM' of undefined error*. For some reason, VS doesn't add angular2-universal while building an Angular project from the template, so I add it by command line as such:

    npm install body-parser angular2-universal preboot express --save

After that, the module angular2-universal is available in VS and I change my app.modules.ts file to this: 

    import { NgModule } from '@angular/core';
    import { CommonModule } from '@angular/common';
    import { FormsModule } from '@angular/forms';
    import { HttpModule } from '@angular/http';
    import { RouterModule } from '@angular/router';
    import { UniversalModule } from 'angular2-universal' //Added line

    import { AppComponent } from './components/app/app.component';
    import { NavMenuComponent } from './components/navmenu/navmenu.component';
    import { HomeComponent } from './components/home/home.component';
    import { FetchDataComponent } from    './components/fetchdata/fetchdata.component';
    import { CounterComponent } from './components/counter/counter.component';

    @NgModule({
        declarations: [
            AppComponent,
            NavMenuComponent,
            CounterComponent,
            FetchDataComponent,
            HomeComponent
        ],
        imports: [
            UniversalModule, //Added line
            CommonModule,
            HttpModule,
            FormsModule,
            RouterModule.forRoot([
                { path: '', redirectTo: 'home', pathMatch: 'full' },
                { path: 'home', component: HomeComponent },
                { path: 'counter', component: CounterComponent },
                { path: 'fetch-data', component: FetchDataComponent },
                { path: '**', redirectTo: 'home' }
            ])
        ]
    })
    export class AppModule {
    }

So basically I changed only a couple of things in the template, but I can only think that I'm missing some angular2-universal dependencies. 

Stack trace:

    NodeInvocationException: Prerendering failed because of error: TypeError: Cannot read property 'getDOM' of undefined
    at Object.exports.REPLACEMENT_CHARACTER (D:\Code\C#\Angular\WebApplication1\WebApplication1\ClientApp\dist\main-server.js:19196:62)
    at __webpack_require__ (D:\Code\C#\Angular\WebApplication1\WebApplication1\ClientApp\dist\main-server.js:20:30)
    at Object.<anonymous> (D:\Code\C#\Angular\WebApplication1\WebApplication1\ClientApp\dist\main-server.js:31031:17)
    at __webpack_require__ (D:\Code\C#\Angular\WebApplication1\WebApplication1\ClientApp\dist\main-server.js:20:30)
    at Object.installedModules (D:\Code\C#\Angular\WebApplication1\WebApplication1\ClientApp\dist\main-server.js:22425:10)
    at __webpack_require__ (D:\Code\C#\Angular\WebApplication1\WebApplication1\ClientApp\dist\main-server.js:20:30)
    at Object.<anonymous> (D:\Code\C#\Angular\WebApplication1\WebApplication1\ClientApp\dist\main-server.js:34953:13)
    at __webpack_require__ (D:\Code\C#\Angular\WebApplication1\WebApplication1\ClientApp\dist\main-server.js:20:30)
    at Object.<anonymous> (D:\Code\C#\Angular\WebApplication1\WebApplication1\ClientApp\dist\main-server.js:31016:10)
    at __webpack_require__ (D:\Code\C#\Angular\WebApplication1\WebApplication1\ClientApp\dist\main-server.js:20:30)
    Current directory is: D:\Code\C#\Angular\WebApplication1\WebApplication1

I also get a couple of warnings while installing angular2-universal:

    npm WARN angular2-universal@2.1.0-rc.1 requires a peer of rxjs@~5.0.0-beta.12 but none is installed. You must install peer dependencies yourself.
    npm WARN angular2-universal@2.1.0-rc.1 requires a peer of zone.js@~0.6.21 but none is installed. You must install peer dependencies yourself.

And things go even further downhill from there. Should that be the issue, I did try to install peer dependencies, as such:

    npm install --save-dev --ignore-scripts install-peers

However, it seems to be taking no effect. Just to be sure, I created a new project and installed these dependencies before installing angular2-universal but I still get both warnings while installing the latter.

Not sure what to do next.

**Comment by Eilon** [comment]
@SteveSandersonMS any ideas on this?

**Comment by SteveSandersonMS** [comment]
This is an Angular usage issue, not a bug in ASP.NET, so I'll mark it as closed.

@Albemuth84 Please see up-to-date Angular docs for details on their SSR APIs. I'm pretty sure it doesn't involve `angular2-universal` any more - that package hasn't even been updated in the last year. Also note that the ASP.NET Core Angular template has SSR enabled out of the box, so you don't have to install any other packages manually. Or for the next version of the ASP.NET Core Angular template, see [docs here](https://docs.microsoft.com/en-us/aspnet/core/spa/angular?tabs=visual-studio).
