### ISSUE TITLE
Implementation of GraphQL as a middleware

### ISSUE THREAD

**Issue by aminebizid** [aspnet/Home#2303]
This is not an issue but a question.

GraphQL is great and I believe it will soon replace Legacy REST implementations.

Is there any Microsoft team/project planning to implement GraphQL?

**Comment by Eilon** [comment]
Hi, there is no one on the ASP.NET team working on implementing this, but I agree it's very cool, so I hope there's someone out there working on it.

**Comment by RainingNight** [comment]
+1

**Comment by rafsanulhasan** [comment]
+1

**Comment by Mercurial** [comment]
can we have graphql as a first class middleware for asp core please?

**Comment by vertonghenb** [comment]
You can use https://github.com/JuergenGutsch/graphql-aspnetcore
or ODATA (which is similar) https://blogs.msdn.microsoft.com/odatateam/2018/07/03/asp-net-core-odata-now-available/

**Comment by Mercurial** [comment]
the third party solution are still incomplete and not yet fully documented, I think anyone competent already knows that there are graphql libraries, what we are saying is that make it first class citizen and fully supported/document and with tooling from Microsoft and so all community effort and just be directed towards that instead
