### ISSUE TITLE
Api Call Not Working

### ISSUE THREAD

**Issue by Petermarcu** [aspnet/Home#2304]
@dexterhussain opened this here: https://github.com/dotnet/core/issues/1138

**Development Machines**
Windows
**Production Machines** 
Ubuntu/Windows

**Reproduction link**

https://github.com/hmuhdkamran/Cms
Live Website Working at
sqanetcore.thetowertech.com

**Steps to reproduce**

Just open the website and open chrome console window it will start showing error.
What is expected?

It should run properly and start working as it is working in development server.
**What is actually happening?**

I am making a website on Vue using aspnetcore 2.0 which i am using development there is no bug no issues it is working perfectly fine when I am rolling it out to production it is giving me error
http://192.168.7.14/api/culture/SupportedCultures 500 (Internal Server Error)
192.168.7.14/:1 Uncaught (in promise)
{messageTypeId: "Error", text: "Request failed with status code 500", title: "Code:undefined. Error"}
messageTypeId
:
"Error"
text
:
"Request failed with status code 500"
title
:
"Code:undefined. Error"
proto
:
Object

From @richlander 
I read that there is a problem with your service. An HTTP 500 error is highly suggestive that the focus should be on the service. The act that you can reproduce the same service error outside the website suggests that the issue has nothing to do with website. I'd focus on your service. Have you tried to debug your service to better understand what is causing it to return HTTP 500?

From @hmuhdkamran
If the issue is in service then it should be in developer mode also, but in developer mode the application runs smoothly, while after publishing the application produces service error.
After production the service cant be called from any rest client, you can even check [https://github.com/hmuhdkamran/Cms](url)

**Comment by Eilon** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, to get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the `asp.net-core-mvc` tag.
