### ISSUE TITLE
ASP.NET Core Web Application Visual Basic (VB)

### ISSUE THREAD

**Issue by tb-mtg** [aspnet/Home#2305]
Any idea on when we will be able to create new projects for ASP.NET Core Web Application using Visual Basic?

**Comment by Eilon** [comment]
Hi @tb-mtg , there are no plans to add a VB template for ASP.NET Core, but @DamianEdwards posted a sample on how to achieve this using two projects: https://github.com/DamianEdwards/AspNetCoreVbHybrid
