### ISSUE TITLE
ASP.NET Core Web Application Visual Basic (VB)

### ISSUE THREAD

**Issue by karelz** [aspnet/Home#2306]
_From @tb-mtg on December 12, 2017 3:5_

Any idea on when we will be able to create new projects for ASP.NET Core Web Application using Visual Basic?

_Copied from original issue: dotnet/corefx#25852_

**Comment by karelz** [comment]
_From @danmosemsft on December 12, 2017 5:6_

@davidfowl ?

**Comment by Eilon** [comment]
Dup of https://github.com/aspnet/Home/issues/2305.
