### ISSUE TITLE
Project taking time to load assets(CSS, JS) files in local machine after upgrade to 2.0 but its faster in server!

### ISSUE THREAD

**Issue by supernarwen** [aspnet/Home#2309]
I have been developing a open source CMS on aspnet core. Its a simple web application which has CMS features with authentication, custom role-permission management and other. I had developed it first on aspnet core 1.0. And application performance was similar on local machine and server. But after I have updated it to aspnet core 2.0, application performance has been peaked high in local machine but its faster on server. I just can't figure out the issue. I have minified all my assets but still its taking time. If you have any time then, it would be great if you could look out at my project. Thank You!

https://github.com/supernarwen/lumle

**Comment by Eilon** [comment]
Hi, do you have info on where the performance is slow? Have you tried using your browser's debugging/development tools to see what the problem is?

**Comment by supernarwen** [comment]
Hi, Thanks for looking into it! I have attached my repo! You can access it!! Minifed assets are taking too much time to load in my local whereas its comparatively faster in server. Its the main issue. I have looked into network of chrome and firefox. And it takes more than a minute to load a simple CSS or JS file even if it is present locally and it is minified.

**Comment by Eilon** [comment]
Are you able to tell if it's slow on the server or on the client? You can try enabling detailed ASP.NET Core logs to see what's happening on the server, and you can use your browser's tools to see what is taking long on the client.

**Comment by supernarwen** [comment]
I have went through it but got no clue!! And its awkward for a project to be slower in local machine and faster in server. So, I was hoping if any senior members at dot net core community would look into my issue. So, I have attached my repo here!

**Comment by Eilon** [comment]
Hi @supernarwen , that is indeed odd, but unfortunately we are unable to debug this due to limited resources. I recommend you try enabling and saving more logs from the server to see which specific requests are slow, and perhaps some information about what is happening on those slow requests.

While we do our best to look through all the issues filed here, to get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the `asp.net-core` tag.

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
