### ISSUE TITLE
Can't get ASPNETCORE_ENVIRONMENT

### ISSUE THREAD

**Issue by Boombasteg** [aspnet/Home#2310]
I set ASPNETCORE_ENVIRONMENT via Environment Variables or in code
`Environment.SetEnvironmentVariable("ASPNETCORE_ENVIRONMENT", "dev");`

But when trying to read it:
`var env = Environment.GetEnvironmentVariable("ASPNETCORE_ENVIRONMENT");`
I'm getting null.

Has anyone encountered a similar one?
Thanx.

**Comment by Tratcher** [comment]
Context? Are these back-to-back calls?

**Comment by Eilon** [comment]
Closing because there is not enough information to reproduce this problem.

**Comment by Boombasteg** [comment]
Problem was in VS. It should be restarted after changing "ASPNETCORE_ENVIRONMENT".
