### ISSUE TITLE
Identity as a library

### ISSUE THREAD

**Issue by danroth27** [aspnet/Home#2311]
Enabling ASP.NET Core Identity in an application today requires adding dozens of files and hundreds of lines of code. We provide this code for you in our templates, but if you want to add this code to an existing project you typically have to create a new project with the identity code and copy the code over. The perceived complexity of having so many files in the project is also pretty intimidating. 

The goals of this effort are to:
- Create a pre-built version of the identity code that you can add to your project as a NuGet package
- Update the templates to use the prebuilt identity package by default
- Add identity scaffolders so that you can easily add back all the code if you want full control
- Isolate all of the identity code in a single folder so that it doesn't distract from your application logic.

The prebuilt library will include:
1. Compiled razor pages and page models
1. It's own layout and static resources

**Comment by mkArtakMSFT** [comment]
@javiercn, I believe all the work supporting this feature is done now, is it?

**Comment by javiercn** [comment]
Yes. I’m not sure if this is intended to track feature work towards RTM. There will be a few cleanups left to do here post preview 1, but I won’t expect nothing mayor.

**Comment by mkArtakMSFT** [comment]
Thanks!
