### ISSUE TITLE
EventSource? DiagnosticSource? Both?

### ISSUE THREAD

**Issue by markrendle** [aspnet/Home#2312]
I'm seeing issues opened by @anurse across multiple repos regarding `EventSource` tracing (like https://github.com/aspnet/Security/issues/1518 for example), but no actual activity as yet; no trace of EventSource anywhere in MVC.

I've been writing a bunch of code to consume `DiagnosticSource` tracing with the new `Activity` stuff lately, so I was kinda hoping those same repos would be adding `DiagnosticSource` support.

Is there a long-term plan to support one over the other? They seem to do the same thing. Obviously on Windows `EventSource` writes to ETW, whereas on Linux I guess it's in-proc?

Any guidance would be much appreciated.

**Comment by Eilon** [comment]
@rynowak - do we have guidance on this that we can share?

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
