### ISSUE TITLE
Want to migrate from dotnet core 1.x to 2.0

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/Home#2313]
Originally filed as https://github.com/aspnet/EntityFrameworkCore/issues/10560 by @ankurjasoria
Moving to aspnet/Home at request of @divega

Hi Team,

I am migrating my project from dotnet core 1.x to 2.0  and when I am updating nuget package references so found below issue 

Error : 
**NU1605	Detected package downgrade: Microsoft.VisualStudio.Web.BrowserLink from 2.0.1 to 1.0.1. Reference the package directly from the project to select a different version. 
 CenterManagementSystem.UI (>= 1.0.0) -> CenterManagementSystem.Platform (>= 1.0.0) -> Microsoft.AspNetCore.All (>= 2.0.3) -> Microsoft.VisualStudio.Web.BrowserLink (>= 2.0.1) 
 CenterManagementSystem.UI (>= 1.0.0) -> Microsoft.VisualStudio.Web.BrowserLink (>= 1.0.1)	CenterManagementSystem.UI	C:\My Project\HBI\yoyo-center-management-system\CenterManagementSystem\DEV\src\CenterManagementSystem.UI\CenterManagementSystem.UI.csproj**

and I am sharing you my code screen shot regarding above issue as below 

![image](https://user-images.githubusercontent.com/4157756/34005829-2e35bd06-e122-11e7-8f14-7cd588c67414.png)

Please update me any solution or any other reference url regarding same.

**Comment by Eilon** [comment]
Closing this issue because it isn't clear to me if there is an issue remaining. If you feel there's still an issue, please re-open this issue or log a new issue with complete details of the problem. Thanks!
