### ISSUE TITLE
Reference to type 'Task' claims it is defined in 'System.Runtime', but it could not be found

### ISSUE THREAD

**Issue by haouatmohamed** [aspnet/Home#2315]
Hello, I am using Visual Studio 2017 and I get this error whenever I try to debug my app:

Reference to type 'Task' claims it is defined in 'System.Runtime', but it could not be found

Any idea please ?
Thanks

**Comment by Eilon** [comment]
Hi @haouatmohamed , can you share more info about this error? Can you upload your app to GitHub, and also show a screenshot of the error(s)?

**Comment by ycrakx** [comment]
Have you found a resolution? I am facing the same issue.

**Comment by Eilon** [comment]
@ycrakx can you please share more info about this error? Can you upload your app to GitHub, and also show a screenshot of the error(s)?

**Comment by Eilon** [comment]
Hi. We're closing this issue as no response or updates have been provided in a timely manner and we have been unable to reproduce it. If you have more details and are encountering this issue please add a new reply and re-open the issue.

**Comment by mani5219** [comment]
hi

**Comment by sunnydaleDoby** [comment]
I am having the same problem.  Was it ever resolved?

**Comment by sunnydaleDoby** [comment]
The problem was solved (for me) by this post:
https://forums.xamarin.com/discussion/146467/reference-to-type-assembly-claims-it-is-defined-in-system-runtime-but-it-could-not-be-found
