### ISSUE TITLE
asp.net core mvc application on windows server 2008 r2 is very slow

### ISSUE THREAD

**Issue by Elias-Heydarpour** [aspnet/Home#2316]
hi ,
when i host my asp.net core 1.0.1 mvc application (api controller)on IIS in windows server 2008r2
,responses to http requests are very slow,and application performance is very slow
but same application's publish when host on iis in windows server2012 R2 ,every thing will be good
and we have no slow performance,
any one has this problem or
any idea for this ?

**Comment by Eilon** [comment]
Hi, do you have more information, such as ETW traces, or log info, to show where the slow-down is? Is it on the web server? Or the database? Or a proxy?

**Comment by Eilon** [comment]
Hi. We're closing this issue as no response or updates have been provided in a timely manner and we have been unable to reproduce it. If you have more details and are encountering this issue please add a new reply and re-open the issue.
