### ISSUE TITLE
Remove duplicate header names and method constants

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/Home#2319]
_From @Tratcher on Monday, October 9, 2017 12:13:16 PM_

https://github.com/aspnet/CORS/blob/df571655acafb39703935a71a977feec023977d0/src/Microsoft.AspNetCore.Cors/Infrastructure/CorsConstants.cs contains header and method string constants that are duplicated with constants in HttpAbstractions.

See
https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.Net.Http.Headers/HeaderNames.cs
https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.AspNetCore.Http.Abstractions/HttpMethods.cs

The public constants can redirect for now. E.g. `public static readonly string AccessControlMaxAge = HeaderNames.AccessControlMaxAge;`

The internal lists can also be updated to use the HttpAbstractions constants.
https://github.com/aspnet/CORS/blob/df571655acafb39703935a71a977feec023977d0/src/Microsoft.AspNetCore.Cors/Infrastructure/CorsConstants.cs#L66-L89

_Copied from original issue: aspnet/CORS#130_

**Comment by priyanshu92** [comment]
Can I take this up?

**Comment by priyanshu92** [comment]
Could you please have a look [here](https://github.com/aspnet/CORS/compare/dev...priyanshu92:fix-duplicate-header-names)?

**Comment by Tratcher** [comment]
That's a start. Please submit a PR.

**Comment by Tratcher** [comment]
@mkArtakMSFT this is only half fixed. CORS no longer uses the duplicate values, but they are public and could not be removed in 2.1. Re-opening to follow up in 3.0.

**Comment by mkArtakMSFT** [comment]
Closing this issue as the important work has been done.
