### ISSUE TITLE
BuildServiceProvider should return IServiceProvider instead of ServiceProvider

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/Home#2329]
_From @cknaap on Monday, November 27, 2017 6:26:06 AM_

Method Microsoft.Extensions.DependencyInjection.ServiceCollectionContainerBuilderExtensions.BuildServiceProvider returns a ServiceProvider instead of the associated interface IServiceProvider.

The latter allows for better mocking in unit tests.

Plus, the documentation on the method also says it returns *I*ServiceProvider.

_Copied from original issue: aspnet/DependencyInjection#614_

**Comment by aspnet-hello** [comment]
_From @davidfowl on Monday, November 27, 2017 7:53:29 AM_

No, it shouldn't. How can you mock an extension method? This method is about building a concrete implementation of an IServiceProvider.

> Plus, the documentation on the method also says it returns IServiceProvider.

It was changed in 2.0 and needs to be updated /cc @Rick-Anderson

**Comment by Rick-Anderson** [comment]
@davidfowl  I fixed this in https://github.com/aspnet/DependencyInjection/pull/615

**Comment by muratg** [comment]
Documentation is fixed (Thanks @Rick-Anderson!).  

Closing the bug as we do not plan to make the requested change.
