### ISSUE TITLE
Provide a way to pass in context from hosting to the ServiceCollection being used when configuring services

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/Home#2340]
_From @javiercn on Thursday, July 20, 2017 11:04:04 AM_

This can be done through an additional interface implemented by service collection (IServiceConfigurationContext) that just defines an IDictionary<object,object>.

Libraries can downcast IServiceCollection to that interface and get or set context from hosting or from other libraries that have been configured before.

_Copied from original issue: aspnet/DependencyInjection#549_

**Comment by Eilon** [comment]
@javiercn / @muratg - did this go through triage? Do we need/want this in preview1?

**Comment by mkArtakMSFT** [comment]
Closing as we have not seen much need for this.
