### ISSUE TITLE
Inverse OSSkipCondition

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/Home#2358]
_From @moozzyk on Tuesday, April 11, 2017 4:09:10 PM_

I would like to run some tests only on Win7 and Win2008R2. OSSkipCondition is only skipping specific OS/versions and doing the opposite will be hard because it would require specifying all OSes and all non-Win7/2008R2 Windows versions and it is hard to get a full list of versions. 

_Copied from original issue: aspnet/Testing#267_

**Comment by aspnet-hello** [comment]
_From @Eilon on Tuesday, April 11, 2017 7:16:38 PM_

Seems like it would be easy enough to write such an attribute. Want to take a stab at it?

**Comment by aspnet-hello** [comment]
_From @moozzyk on Tuesday, April 11, 2017 8:04:09 PM_

sure

**Comment by aspnet-hello** [comment]
_From @Eilon on Wednesday, June 14, 2017 3:08:08 PM_

Moving to 2.1.0.

**Comment by mkArtakMSFT** [comment]
Closing this issue as we never really needed it.

**Comment by moozzyk** [comment]
https://github.com/aspnet/SignalR/issues/1568
