### ISSUE TITLE
ObjectPool.Return could give back success status

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/Home#2359]
_From @sebastienros on Friday, November 17, 2017 3:18:39 PM_

When we return an object, the object might not be returned in the queue. It would be useful to know about it by returning a bool. The caller could then decide to dispose any resource associated with this object as we can't reuse it.

_Copied from original issue: aspnet/Common#296_

**Comment by aspnet-hello** [comment]
_From @Eilon on Wednesday, November 22, 2017 2:33:24 PM_

Wouldn't you always want to clean up the resources associated with the object? In your case, what are the "other resources"?

**Comment by aspnet-hello** [comment]
_From @pranavkm on Wednesday, November 22, 2017 2:55:44 PM_

@Eilon things like DbConnection \ HttpClient where you might want to keep the instance around until the pool goes out of scope.

**Comment by aspnet-hello** [comment]
_From @Eilon on Wednesday, November 22, 2017 3:50:06 PM_

Got it, chatted with @rynowak and @sebastienros in person. We'll hold onto it in the backlog to see if there's more demand for this.

**Comment by gfoidl** [comment]
If there will be more demand, I see two possibilities to solve this. For me the second variant would be the one to go with.

### New Method on `ObjectPool`

```c#
public abstract class ObjectPool<T> where T : class
{
    // ...
    public abstract void Return(T obj, out bool isReturnedToPool);
}
```

So the "normal" return-method can remain untouched, and its perf-optimized behavior can be used for most cases.
For the special cases, where the info about returning to the pool is needed, the new method can be used.

This is a breaking change to the interface of `ObjectPool`!

So maybe
```c#
public virtual void Return(T obj, out bool? isReturnedToPool)
{
    Return(obj);
    isReturnedToPool = null;
}
```
to make it less breaking :wink:


### New derived class from `ObjectPool`

The interface of `ObjectPool` and all concrete implementations can be untouched, when there will be a new class like `InformationalObjectPool` (that might derive from `DefaultObjectPool`). This _informational_ version can extend the interface with methods like:
```c#
public T Get(out bool gotObjectFromPool);    // maybe??
public void Return(T obj, out bool isReturnedToPool);
```

**Comment by mkArtakMSFT** [comment]
Talked to @sebastienros regarding this. Changing the `Return` method as follows would be the preference:
`public bool Return (T obj);`

Moving this to 3.0 for now, as it should be small change.
