### ISSUE TITLE
Add ConsoleReporter

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/Home#2360]
_From @ryanbrandenburg on Wednesday, October 25, 2017 3:07:28 PM_

Add the `ConsoleReporter` as seen in [BuildTools](https://github.com/aspnet/DotNetTools/blob/8c327312824457b4dd1fccd814380894edf36eab/shared/ConsoleReporter.cs) to `Microsoft.Extensions.CommandLineUtils.Sources`.

_Copied from original issue: aspnet/Common#276_

**Comment by aspnet-hello** [comment]
_From @ryanbrandenburg on Wednesday, October 25, 2017 3:08:10 PM_

After adding it here, remove any copies that have popped up in repos like Infrastructure.

**Comment by aspnet-hello** [comment]
_From @Eilon on Tuesday, November 7, 2017 10:06:21 AM_

Go for it 😄

**Comment by Eilon** [comment]
Naah.
