### ISSUE TITLE
Base64Url encoding duplicated with HttpAbstraction repository

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/Home#2362]
_From @ycrumeyrolle on Wednesday, June 7, 2017 5:42:43 AM_

https://github.com/aspnet/Common/blob/dev/shared/Microsoft.Extensions.WebEncoders.Sources/WebEncoders.cs
https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.AspNetCore.WebUtilities/Base64UrlTextEncoder.cs

Related #93 

In addition, can we consider to optimize the encoder by avoiding to first convert to Base64 then replace to url-safe character. instead, convert directly to Base64Url, simply by changing the Base64 character map and by removing the padding?

_Copied from original issue: aspnet/Common#237_

**Comment by muratg** [comment]
@Tratcher thoughts?

**Comment by Tratcher** [comment]
Looks like this was fixed back in https://github.com/aspnet/HttpAbstractions/commit/ce68ec23c05739af52f2e59649dd94b66bc30f13#diff-835c72281a3d18a5d4075376a0bb8a8d
