### ISSUE TITLE
Review and Update BaseView

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/Home#2363]
_From @rynowak on Tuesday, June 6, 2017 11:34:06 PM_

We made some changes to Razor codegen that could impact this class. We need to review this and determine what should be adjusted.

/cc @ajaybhargavb 

_Copied from original issue: aspnet/Common#236_

**Comment by aspnet-hello** [comment]
_From @rynowak on Friday, June 30, 2017 10:05:57 AM_

This could happen at any time since it's not broken, moving this out.

**Comment by ajaybhargavb** [comment]
ac68db3695abacb0c2f08103ee38eafbef15fe21 and 77200410d6a68025b047a613c636cf3d856e7e6c
