### ISSUE TITLE
Correctly handle arrays in TypeNameHelper

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/Home#2366]
_From @jdom on Thursday, April 13, 2017 3:12:44 PM_

Browsing and running the code in [TypeNameHelper](https://github.com/aspnet/Common/blob/5b88e0f5dc15f9dc80625db3698dbbc3f2fd3da9/shared/Microsoft.Extensions.TypeNameHelper.Sources/TypeNameHelper.cs), it doesn't look like it handle array types correctly.

The following: 
```
TypeNameHelper.GetTypeDisplayName(typeof(List<int[]>[]))
```
Results in:
```
System.Collections.Generic.List`1[[System.Int32[], mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]][]
```

But my expected result would be:
```
System.Collections.Generic.List<int[]>[]
```
or alternatively even:
```
[System.Collections.Generic.List<[int]>]
```

_Copied from original issue: aspnet/Common#216_

**Comment by aspnet-hello** [comment]
_From @jdom on Thursday, April 13, 2017 3:15:35 PM_

BTW, even the simpler:
```
TypeNameHelper.GetTypeDisplayName(typeof(int[]))
```
just returns `typeof(int[]).FullName` without accounting for any of the aliases and so on, and returns `System.Int32[]` instead of `int[]` or something of that sort.

**Comment by aspnet-hello** [comment]
_From @Eilon on Thursday, May 11, 2017 2:00:01 PM_

Hi @jdom , this does indeed appear to be a bug. This looks like it could affect the rendering of stack trace in the ASP.NET Core developer exception page. But, given that the bug is so limited, and only affects the display (nothing is functionally broken), I'm marking as up-for-grabs, and putting this on the backlog. We would gladly review a PR for it.

**Comment by priyanshu92** [comment]
I think this is already fixed

**Comment by mkArtakMSFT** [comment]
Closing as this seems to be fixed as part of https://github.com/aspnet/Common/pull/269
