### ISSUE TITLE
Investigate using ConcurrentBag for DefaultObject pool (post corefx merge) 

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/Home#2368]
_From @benaadams on Wednesday, November 30, 2016 1:14:10 PM_

When this is merged to corefx dotnet/corefx#14126 it will be worth (re)visiting ConcurrentBag for object pooling.

/cc @rynowak @davidfowl 

_Copied from original issue: aspnet/Common#174_

**Comment by aspnet-hello** [comment]
_From @rynowak on Monday, December 5, 2016 1:05:41 PM_

Is there some data to go with this? or just a feeeeeeeeeeeeeeeeeeeeeeeeeeeling?

**Comment by aspnet-hello** [comment]
_From @benaadams on Monday, December 5, 2016 2:04:15 PM_

Had data to show why you shouldn't use ConcurrentBag or ConcurrentStack but ConcurrentQueue, which is why Kestrel uses the Queue for its pool.

Corefx change invalidates this data - so needs revisiting; don't have data yet...

**Comment by mkArtakMSFT** [comment]
@rynowak, what are your thoughts about this? Should we do this? Is this still relevant? /cc: @davidfowl

**Comment by benaadams** [comment]
`ConcurrentQueue` is probably better in case people uncap the threadpool and end up with lots of objects sitting in threadlocals from `ConcurrentBag`

**Comment by rynowak** [comment]
@benaadams - why do you think this is important? What does this get us?

**Comment by benaadams** [comment]
Lower contention - `Get` and `Return` wouldn't contend as they operate on different ends
Better throughput - `Get` and `Return` only operate on a single item; rather that iterating the whole array
Mainline data structure - its performance is continually worked on; whereas `DefaultObjectPool` doesn't get a lot of attention

**Comment by benaadams** [comment]
Although... this might be better https://github.com/dotnet/corefx/issues/24365

**Comment by rynowak** [comment]
I'm open to ideas, but if the bounded queue is a new API, it's pretty much impossible for us to adopt unless it's also netstandard2.0 library.

-- 

Also concurrent bag doesn't have a bounded capactity, so we'd still have to implement something 😆 

I don't really find this compelling unless the BCL can provide us with a bounded concurrent queue.

**Comment by benaadams** [comment]
> I don't really find this compelling unless the BCL can provide us with a bounded concurrent queue.

`BoundedConcurrentQueue<T>` should be .NET Standard 1.3 https://www.nuget.org/packages/System.Collections.Concurrent/ will see how the api review in Feb goes

**Comment by rynowak** [comment]
@mkArtakMSFT - I suggest we revisit this pending the outcome of the API review for `BoundedConcurrentQueue`- it would be nice cleanup to replace our custom implementation with that. However you want to track that is fine with me.

/cc @stephentoub

**Comment by mkArtakMSFT** [comment]
Thanks from bringing this up, @benaadams.
We're closing this issue as the value is not clear.
If you feel it's really important and you have more data supporting it, we'll reconsider.
