### ISSUE TITLE
Add CommonTasks

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/Home#2372]
_From @justinvp on Wednesday, July 8, 2015 10:06:37 AM_

There are a lot of [uses of `Task.FromResult(0)` in the aspnet repos](https://github.com/search?q=Task.FromResult+language%3Acsharp+user%3Aaspnet+-repo%3Aaspnet%2FTesting+-repo%3Aaspnet%2FMusicStore+-repo%3Aaspnet%2FDocs+-path%3Asamples+-path%3Atest&type=Code) for returning a completed `Task`.

There are also a bunch of uses of `Task.FromResult(true)` and `Task.FromResult(false)`, along with some uses of `Task.FromResult<T>(null)`.

Instead of calling `Task.FromResult` in these cases, which allocates a new `Task` instance each time, these can be created once and cached and reused, to reduce allocations.

The SignalR-Server repo already does this with its [`TaskAsyncHelper`](https://github.com/aspnet/SignalR-Server/blob/af86f52a1b9a90f66f38512f5d6172e203c017ea/src/Microsoft.AspNet.SignalR.Sources/TaskAsyncHelper.cs#L26-L51).

Other projects do this as well:
- [Roslyn](https://github.com/dotnet/roslyn/blob/master/src/Workspaces/Core/Portable/Utilities/SpecializedTasks.cs)
- [Xunit](https://github.com/xunit/xunit/blob/master/src/xunit.execution/Sdk/Utility/CommonTasks.cs)
- CoreCLR/CoreFx uses the built-in [`Task.CompletedTask`](https://github.com/dotnet/coreclr/blob/f1c0c7d95164abbbc4dfbd5bc312ef543256b0e0/src/mscorlib/src/System/Threading/Tasks/Task.cs#L1642) (new in .NET 4.6)

I was going to submit PRs in each repo to use one-off cached instances, but this looks like a cross-repo concern that might fit better as a common build-time package (like `NotNullAttribute`, `PropertyHelper`, etc.)

Something like `Microsoft.Framework.CommonTasks.Sources` with the following:

``` c#
namespace Microsoft.Framework.Internal
{
    internal static class CommonTasks
    {
        public static readonly Task Completed = Empty<object>.Default;
        public static readonly Task<bool> True = Task.FromResult<bool>(true);
        public static readonly Task<bool> False = Task.FromResult<bool>(false);

        public static Task<T> Default<T>()
        {
            return Empty<T>.Default;
        }

        private static class Empty<T>
        {
            public static readonly Task<T> Default = Task.FromResult<T>(default(T));
        }
    }
}
```

_Copied from original issue: aspnet/Common#26_

**Comment by justinvp** [comment]
I assume this issue is no longer relevant and can be closed.
