### ISSUE TITLE
 DefaultIsOriginAllowed should StringComparer.Ordinal be changed to StringComparer.OrdinalIgnoreCase?

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/Home#2373]
_From @benhysell on Friday, August 11, 2017 11:58:50 AM_

https://github.com/aspnet/CORS/blob/8214954d5b0dafe191890da9a3de86f5b607ea69/src/Microsoft.AspNetCore.Cors/Infrastructure/CorsPolicy.cs#L161

Is the only place where string comparison is cased...should it ignore case?

Ran into an issue today where I built my own policy:

```
services.AddCors(options =>
                {
                    options.AddPolicy("AllowRequestFromWeb",
                        builder =>
                        {
                            builder.WithOrigins(Configuration["ServerOptions:AllowedCorsOrigins"])
                                .AllowAnyHeader()
                                .AllowAnyMethod()
                                .AllowCredentials();
                        });
                });
```
And I'm reading the configuration in from ```appsettings.json```.
```
"ServerOptions": {    
    "AllowedCorsOrigins": "http://localhost"
  }
```

All worked great, but I was having an odd failure with my production ```appsettings.json```.  From ```appsettings.json.Production```

```
"ServerOptions": {    
    "AllowedCorsOrigins": "http://MyCoolProductionServer"
  }
```
My CORS were failing.

The second I changed ```"http://MyCoolProductionServer"``` to lowercase everything worked as expected.

I realize that I cased my server name in my ```appsettings.json.Production```, my mistake...but should that comparison be case sensitive? 

_Copied from original issue: aspnet/CORS#124_

**Comment by aspnet-hello** [comment]
_From @blowdart on Friday, August 11, 2017 12:20:11 PM_

It's complicated. So complicated there's an RFC - https://tools.ietf.org/html/rfc4343

Basically for ASCII domains it's case insensitive, but punycode (what Internationalised domain names convert into) kinda, sorta, messed it up.

However, we ought to normalise in our checks, and then allow case sensitivity as an option.

**Comment by pranavkm** [comment]
This was addressed as part of https://github.com/aspnet/CORS/commit/feceb3ddeaf0a0ca7e895eb83674d78fee53515c. We still don't punycode i8n names, but this issue can be closed.
