### ISSUE TITLE
Asp.net core web api that returns File is throwing No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is therefore not allowed access

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/Home#2374]
_From @Eilon on Thursday, August 10, 2017 3:12:27 PM_

_From @adriangh83 on August 10, 2017 16:37_

Hello,
I have a problem when trying to return a File on an .net core (1.1) rest service.  I get "XMLHttpRequest cannot load http://localhost:83/api/attachment/content/22?_=1502382297330. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is therefore not allowed access. The response had HTTP status code 500."
If I change the controller code so I return Ok and not File I do not get this error anymore. 
Can you help me? 
Thanks.

**Startup code:**

```c#
services.AddCors(options =>
            {
                options.AddPolicy("AllowAllHeaders",
                      builder =>
                      {
                          builder.AllowAnyOrigin()
                                 .AllowAnyHeader()
                                 .AllowAnyMethod()
                                 .AllowCredentials();
                      });
            });

app.UseCors("AllowAllHeaders");
app.UseMvc();
```

**Controller code**: 

```c#
var contentType = MimeMapping.GetMimeMapping(Path.GetExtension(attachmentPath));
using (var stream = new FileStream(attachment.CaleAtasament, FileMode.Open))
{
           return File(stream, contentType, attachmentName);                        
}
```

**Client Code:**

```c#
var getUrl = baseUrl + 'attachment/content/' + $('#tbAttachmentId').val();
                jQuery.ajax({
                    url: getUrl,
                    cache: false,
                    crossDomain: true,
                    type: 'GET',
                    beforeSend: function (xhr) {   //Include the bearer token in header
                        xhr.setRequestHeader("Authorization", 'Bearer ' + jwt);
                    },                   
                });
```

---

Formatting for style only by @Eilon.

_Copied from original issue: aspnet/Security#1357_

_Copied from original issue: aspnet/CORS#123_

**Comment by aspnet-hello** [comment]
_From @Eilon on Thursday, August 10, 2017 3:12:28 PM_

_From @dallancarr on August 10, 2017 20:54_

Can we see the full controller action code snippet? Also check exception it's returning 500 so hence not returning CORS headers.
So possibly not a security issue.

**Comment by aspnet-hello** [comment]
_From @adriangh83 on Thursday, August 10, 2017 9:15:56 PM_

For some reason the previewer doesn't format the code so I've attached some screenshots. I'm sorry that some variable names are not written in English.

![image](https://user-images.githubusercontent.com/5945984/29201080-c2e249fa-7e63-11e7-9c89-e849e69a58bb.png)
![image](https://user-images.githubusercontent.com/5945984/29201087-d31c80f6-7e63-11e7-99e9-a0ae7e8488cd.png)

I should mention that on the client side I've used an ajax request so that I can send a JWT token in header. 
After creating the issue I've tried using anonymous on the server side and windows.location.href on the client side and I didn't get the same CORS error. But using this approach I cannot attach the JWT token in header.

**Comment by aspnet-hello** [comment]
_From @adriangh83 on Thursday, August 10, 2017 9:36:04 PM_

Trying to use another approach I find out that the error appears because I closed the stream. 
If I use the following code I no longer get that CORS error:
![image](https://user-images.githubusercontent.com/5945984/29201494-6139143c-7e67-11e7-9b6f-d30f1f6fb52e.png)
Still don't know why I get CORS error on server error. 
Sorry about wasting your time and keep up the good work. :)

**Comment by pranavkm** [comment]
Closing since the issue was resolved.
