### ISSUE TITLE
Allow a more flexible AllowOrigin response

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/Home#2379]
_From @mharthoorn on Wednesday, October 5, 2016 12:43:56 PM_

Instead of the CorsService peeking into the CorsPolicy

``` csharp
   policy.Origins.Contains(origin)
```

A method `OriginAllowed(string origin)` would allow for a much more flexible lookup policy. The service would then call:

``` csharp
  policy.OriginAllowed(origin)
```

This allows the policy to respond with a more ad hoc response like a (database) lookup.
The default would simply be:

``` csharp
        public virtual bool OriginAllowed(string origin)
        {
            return this.Origins.Contains(origin);
        }
```

But an override policy could become something like: 

``` csharp
        public override bool OriginAllowed(string origin)
        {
            return repository.Exists<Sites>(s => s.Origin == origin);
        }
```

_Copied from original issue: aspnet/CORS#89_

**Comment by aspnet-hello** [comment]
_From @Choc13 on Sunday, October 30, 2016 9:57:37 AM_

See issue #75

**Comment by aspnet-hello** [comment]
_From @Eilon on Wednesday, November 23, 2016 2:35:06 PM_

We will consider this for the next version.

**Comment by pranavkm** [comment]
This is true today - `CorsService` uses [`CorsPolicy.IsOriginAllowed`](https://github.com/aspnet/CORS/blob/master/src/Microsoft.AspNetCore.Cors/Infrastructure/CorsService.cs#L276-L279) to determine if an origin is allowed. `CorsPolicy` has a settable delegate that lets you configure it - https://github.com/aspnet/CORS/blob/master/src/Microsoft.AspNetCore.Cors/Infrastructure/CorsPolicy.cs#L77
