### ISSUE TITLE
CodeGenerator.AddFolder Method

### ISSUE THREAD

**Issue by SzymonSel** [aspnet/Home#238]
### Title

AddFolder method does not include an existing folder to the project.
### Functional impact

> "[...] If there is already a folder on the disk but that is not part of the project, the folder is added to the project."
> This isn't true. Instead an exception is thrown, that a folder with this name already exists.
### Minimal repro steps

1.Create a folder in the project
2.Exclude the folder from the project
3.Call AddFolder with the name of the excluded folder
### Expected result

The folder should be added to the project
### Actual result

COMException is thrown:

> "A file or folder with the name 'Models' already exists on disk at this location. Please choose another name."

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
