### ISSUE TITLE
IOptionsSnapshot not working in docker container using bind mount

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/Home#2382]
_From @tgropper on Friday, December 1, 2017 6:53:58 AM_

I'm hosting my app in docker and i'm having problems using bind mount to have my config files binded with the host. This works running on the host.

The files change correctly inside the running container but dotnet doesn't recognize those changes.
The config files are in a `/config` folder (including `appsettings.json`) so i don't have to put extra files inside my container (and also the bind mount in docker-compose doesn't work for specific files when they are modified in a Windows host).

I've also tried using `IOptionsSnapshot` inside a controller or any scoped type (the filter i'm posting here for example) but it didn't work either.

My setup:

**Program.cs**
 ```c#
...
public static IWebHost BuildWebHost(string[] args)
{
    return new WebHostBuilder()
        .UseKestrel()
        .UseContentRoot(Directory.GetCurrentDirectory())
        .ConfigureAppConfiguration((hostingContext, config) =>
        {
            config
                .SetBasePath(Path.Combine(Directory.GetCurrentDirectory(), "config"))
                .AddJsonFile("appsettings.json", optional: false, reloadOnChange: true)
                .AddJsonFile($"appsettings.{hostingContext.HostingEnvironment.EnvironmentName}.json", optional: false, reloadOnChange: true)
                .AddEnvironmentVariables()
                .AddCommandLine(args);
        })
        .ConfigureServices(services =>
        {
                services.AddOptions();
                services.AddAutofac();
        })
        .UseStartup<Startup>()
        .Build();
}
```

**Startup.cs**
 ```c#
public Startup(IHostingEnvironment env)
{
    EnvironmentName = env.EnvironmentName;
    Path = System.IO.Path.Combine(env.ContentRootPath, "config");

    var builder = new ConfigurationBuilder()
        .SetBasePath(Path)
        .AddJsonFile("appsettings.json", optional: false, reloadOnChange: true)
        .AddJsonFile($"appsettings.{EnvironmentName}.json", optional: true, reloadOnChange: true)
        .AddJsonFile($"channels.{EnvironmentName}.json", optional: true, reloadOnChange: true)
        .AddEnvironmentVariables();
        this.Configuration = builder.Build();
}

public IServiceProvider ConfigureServices(IServiceCollection services)
{
    services.Configure<MyValueConfig>(Configuration.GetSection("MyValue"));
    ...
}
...
```

**SarasaActionFilterAttribute**
```c#
public class SarasaActionFilterAttribute : TypeFilterAttribute
{
    public SarasaActionFilterAttribute()
        : base(typeof(SarasaActionFilterAttributeImp))
    { }
}

public class SarasaActionFilterAttribute : ActionFilterAttribute
{
    private readonly bool someValue;

    public SarasaActionFilterAttribute(IOptionsSnapshot<MyValueConfig> myValue) => this.someValue = myValue.Value.SomeValue;
    
    public override async Task OnActionExecutionAsync(ActionExecutingContext context, ActionExecutionDelegate next)
    {
        // do something with someValue
        await next();
    }
}
```

**Dockerfile**
```
FROM microsoft/aspnetcore-build:2.0 AS build-env
WORKDIR /app

COPY . ./
RUN dotnet restore
RUN dotnet publish /app/src/Website -o out

FROM microsoft/aspnetcore:2.0
WORKDIR /app
COPY --from=build-env /app/src/Website/out .
ENTRYPOINT ["dotnet", "Website.dll"]
```

I've also commented the ENTRYPOINT line so I've could attach to the running container to see if files were actually being modified (they were).

**Docker**
`docker build -t sarasa .`
`docker run -it -v ${PWD}/src/Website/config/:/app/config/ -p 8000:80 sarasa`

_Copied from original issue: aspnet/Options#244_

**Comment by aspnet-hello** [comment]
_From @tgropper on Friday, December 1, 2017 10:17:30 AM_

I've just tried changing the file using vim in centOS and it worked, so i guess the problem is with windows hosts and linux containers.

**Comment by ajcvickers** [comment]
@tgropper Sorry for taking so long to respond. We believe this is an issue with the underlying file system, rather than an issue in the options mechanisms themselves. If you are still hitting this, then consider filing an issue on the https://github.com/dotnet/corefx repo for the underlying issue.

**Comment by jehof** [comment]
Indeed. Tried this from Visual Studio (through docker-compose, linux-container,etc.) an the configuration is not reloaded.

When I start the application through IISExpress the configuration is reloaded with the new values. Took me some hours to find this out (Thanks for posting the issue)
