### ISSUE TITLE
[Annoucement][Draft] IOptionsSnapshot is now a scoped service

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/Home#2390]
_From @Tratcher on Tuesday, July 18, 2017 3:35:23 PM_

In 1.x IOptionsSnapshot would only reload based on notified changes to its data source (e.g. config). In 2.0 the service is now scoped and reloaded per request instead.

IOptionsMonitor is the replacement.

_Copied from original issue: aspnet/Options#217_

**Comment by aspnet-hello** [comment]
_From @Tratcher on Wednesday, July 19, 2017 9:50:16 AM_

Note the docs also need to be updated. https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration

**Comment by HaoK** [comment]
Docs have been updated for options 2.0 changes here: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options
