### ISSUE TITLE
Add a comment that the session cookie is considered non-essential

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/Home#2393]
_From @Tratcher on Wednesday, December 27, 2017 1:35:17 PM_

RE: https://github.com/aspnet/Security/issues/1561

When this new policy is applied all non-essential cookies will be suppressed. We need to determine if session is considered essential by default. I expect not as it's designed for ephemeral data.

@blowdart 

_Copied from original issue: aspnet/Session#204_

**Comment by muratg** [comment]
@Tratcher's following-up with folks to close on this.

**Comment by Tratcher** [comment]
Offline discussion with @Eilon and @glennc: Session is non-essential, it's designed for ephemeral data. I will add a comment to that effect in the code, but that change does not need to go into preview1. Moving to preview2.
