### ISSUE TITLE
Use MachineKey in ASP.NET vNext

### ISSUE THREAD

**Issue by daverupp** [aspnet/Home#240]
Hey all
I am using a OWIN based IdentityServer and there I have a MachineKey for Token generation. What are the plans to use the MachineKey functionality as well within a ASP.NET vnext MVC 6 Application? There is now way to reference the MachineKey's System.Web dll (Of course that makes totally sense, but what is the alternative?) 

My Target:
I want to create access Tokens based on the same key for further usage on the ResourceServer. 
(Kind of authorization workflow decoupled from the resource server)

thanks for any help or ideas how to solve that.
Kind regards
Dave

**Comment by rjhernandez** [comment]
Did any samples ever get published?

**Comment by GrabYourPitchforks** [comment]
@rjhernandez yup! See https://docs.asp.net/en/latest/security/data-protection/.

**Comment by Red6Porkins** [comment]
Can DataProtection be used in place of static machine key that one would put into a web.config to sign auth cookies?

**Comment by blowdart** [comment]
@Red6Porkins Yes, that's what it's designed for, as pointed out above. 

The documentation is also pointed to above.
