### ISSUE TITLE
Make Session loading (Deserialize) faster

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/Home#2403]
_From @sdrapkin on Wednesday, May 10, 2017 8:43:05 AM_

[DistributedSession.cs](https://github.com/aspnet/Session/blob/02b975c59776722c0cc47542599a59bef9445440/src/Microsoft.AspNetCore.Session/DistributedSession.cs#L294) adds deserialized property values in a loop to a `Dictionary<EncodedKey, byte[]> _store`.

This causes continuous dictionary resizing (which uses prime-number capacities). However, this resizing is wasteful, since `Deserialize()` already knows the required capacity (`expectedEntries`).

`_store` should be initialised with a known capacity inside `Deserialize()`, instead if being initialised with an unknown capacity inside ctor.

_Copied from original issue: aspnet/Session#163_

**Comment by aspnet-hello** [comment]
_From @muratg on Tuesday, September 26, 2017 3:49:35 PM_

@sdrapkin Would you be interested in sending a PR?

**Comment by aspnet-hello** [comment]
_From @sdrapkin on Tuesday, September 26, 2017 7:15:21 PM_

@muratg No (didn't sign CLA, and the change is trivial).

**Comment by muratg** [comment]
We won't be fixing this.
