### ISSUE TITLE
Determine if the antiforgery cookie is considered essential

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/Home#2408]
_From @Tratcher on Wednesday, December 27, 2017 1:48:50 PM_

RE: aspnet/Security#1561

When this new policy is applied all non-essential cookies will be suppressed. We need to determine if anti-forgery is considered essential by default. I expect yes as it's a security feature.

@blowdart

_Copied from original issue: aspnet/Antiforgery#175_

**Comment by aspnet-hello** [comment]
_From @rynowak on Wednesday, December 27, 2017 2:38:46 PM_

I also expect yes.

**Comment by aspnet-hello** [comment]
_From @blowdart on Wednesday, December 27, 2017 4:39:35 PM_

Yup, essential

**Comment by aspnet-hello** [comment]
_From @mkArtakMSFT on Thursday, December 28, 2017 11:18:29 AM_

Thanks guys. Agree, this should be marked as essential. I'm updating the title and assigning to someone to make the actual change.

**Comment by aspnet-hello** [comment]
_From @mkArtakMSFT on Thursday, December 28, 2017 11:23:47 AM_

Hi @kichalla. Can you please mark the antiforgery cookie as "essential"?

**Comment by aspnet-hello** [comment]
_From @Tratcher on Thursday, December 28, 2017 11:56:00 AM_

Preview2? @blowdart isn't the rest of this feature going into preview1?

**Comment by aspnet-hello** [comment]
_From @blowdart on Thursday, December 28, 2017 2:59:40 PM_

I believe so, but it's a question for @DamianEdwards though

**Comment by DamianEdwards** [comment]
This should be in preview1 if it can be

**Comment by kichalla** [comment]
Oops. Closed by mistake

**Comment by kichalla** [comment]
https://github.com/aspnet/Antiforgery/commit/e5de4e672cbe879d598529c257539b6a7d1a7bf9
