### ISSUE TITLE
An exception was thrown while deserializing the token on Ubuntu

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/Home#2409]
_From @dexterhussain on Wednesday, December 20, 2017 9:25:19 PM_

We are developing a project using anti-forgery in dotnet core 2.0 . We are making this project on windows machine no redis nothing but as soon as I publish this to ubuntu it gives me these errors,

: Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgery[7]
An exception was thrown while deserializing the token.
System.InvalidOperationException: The antiforgery token could not be decrypted. ---> System.Security.Cryptography.CryptographicException: The payload was invalid.

_Copied from original issue: aspnet/Antiforgery#173_

**Comment by aspnet-hello** [comment]
_From @dexterhussain on Wednesday, December 20, 2017 9:25:35 PM_

Gives no errors on Windows Development Machine

**Comment by aspnet-hello** [comment]
_From @mkArtakMSFT on Wednesday, December 27, 2017 9:50:52 AM_

@dexterhussain, can you please share a project with a repro?
@blowdart, any thoughts regarding this?

**Comment by aspnet-hello** [comment]
_From @blowdart on Wednesday, December 27, 2017 11:14:28 AM_

Did you configure data protection yet? On linux there's no safe way for data protection to store keys, unlike on Windows, so you need to make a specific choice on how you want your keys saved.

Start with the file system, then layer an X509 certificate on top if you feel it's needed. https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/configuration/overview?tabs=aspnetcore2x

**Comment by mkArtakMSFT** [comment]
Hi. We're closing this issue as there's been no response and we have been unable to reproduce it. If you have more details and are encountering this issue please add a new reply and re-open the issue.
