### ISSUE TITLE
Tampered antiforgery token should not result in InvalidOperationException

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/Home#2410]
_From @drauch on Tuesday, December 12, 2017 3:13:01 AM_

If the antiforgery token is missing, the antiforgery infrastructure correctly returns BadRequest. However, if the antiforgery token cannot be parsed by the cryptography infrastructure below (e.g., because it has been tampered with by a malicious user) an InvalidOperationException bubbles up.

This is bad style because it returns a 500 HTTP status code instead of 400. It also triggers our operation to look at the exception log because it's marked as an internal server error and not a client error.

Please fix this - or is there a known workaround?

_Copied from original issue: aspnet/Antiforgery#171_

**Comment by aspnet-hello** [comment]
_From @mkArtakMSFT on Tuesday, December 12, 2017 9:50:00 AM_

Hi @drauch, is this happening as part of the default Anti-Forgery feature? Or are you calling to Anti-Forgery directly?

**Comment by aspnet-hello** [comment]
_From @mkArtakMSFT on Tuesday, December 12, 2017 9:51:08 AM_

Chaning the exception type would be a breaking change, but there is an alternative to handle it in the filter.

**Comment by aspnet-hello** [comment]
_From @drauch on Tuesday, December 12, 2017 11:53:39 AM_

As a workaround we are now installing a decorator for the `DefaultAntiforgery` `IAntiforgery` service which translates `InvalidOperationException`s to `AntiForgeryException`s which are then in turn handled by the filter correctly (by returning a 400 BadRequest). It feels really weird to catch an `InvalidOperationException`...I'd still mark it as a bug in the antiforgery infrastructure.

**Comment by kichalla** [comment]
Fixed: https://github.com/aspnet/Antiforgery/commit/d2c27104ddc1761e303fdfe8c8fb5acef67f2107

**Comment by drauch** [comment]
Has this been released with 2.1.0?
