### ISSUE TITLE
SignoutAsync doesn't remove Antiforgery cookie

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/Home#2411]
_From @jchannon on Wednesday, November 1, 2017 9:19:52 AM_

Calling `SignOutAsync("MyCookieMW", authProperties);` only removes the authentication cookie in the app not the antiforgery cookie that is created. 

_Copied from original issue: aspnet/Antiforgery#167_

**Comment by aspnet-hello** [comment]
_From @Eilon on Thursday, November 2, 2017 12:55:33 PM_

@blowdart / @rynowak - this seems reasonable to me in principle, though the two features are not directly related. Thoughts on this?

**Comment by aspnet-hello** [comment]
_From @rynowak on Thursday, November 2, 2017 4:38:56 PM_

It seems like an improvement to me. Your cookie won't be valid after your identity changes.

Not sure off the cuff how we'd accomplish this, but it's worth a look.

-------

However, if we do implement something like it doesn't mean that applications/frameworks can rely on it. It's just a nicety

**Comment by aspnet-hello** [comment]
_From @jchannon on Friday, November 3, 2017 12:03:35 AM_

As a side note when you say your forgery cookie won't be valid when the
identity changes does this apply to sliding auth to? From what I've
experienced this isn't the case ie cookie auth cookie regenerates after X
minutes due to sliding auth but I can still post data successfully.

**Comment by aspnet-hello** [comment]
_From @rynowak on Friday, November 3, 2017 5:41:37 PM_

>  ie cookie auth cookie regenerates after X minutes due to sliding auth but I can still post data successfully

Actually I spoke wrongly before. The cookie token is a unique token that acts like a salt. It's the 'request' (usually form-data) token that contains the claim-related data.

**Comment by aspnet-hello** [comment]
_From @brockallen on Saturday, November 4, 2017 5:56:55 AM_

Perhaps what should happen is the anti-forgery should check if the current forgery token matches the current authenticated user, and if not ignore the cookie for the incoming request, and remove it on the response. That makes it decoupled from any specific authentication mechanism.

**Comment by javiercn** [comment]
Signing in/out only changes the identity of the user for subsequent requests. There is no need to remove the antiforgery token after sign out as a new antiforgery token will be generated on the next get request that renders a form. For SPA scenarios an antiforgery token can be provisioned through an explicit endpoint.

We will be providing a sample on how to do this. Closing this issue and pointing to the other issue for tracking aspnet/samples#2
