### ISSUE TITLE
SetDoNotCacheHeaders overwrites headers that are more restrictive

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/Home#2414]
_From @openidauthority on Friday, August 4, 2017 10:28:30 AM_

If a user has set the Cache-Control header for a page, the form tag helper will overwrite the headers. In some cases this is appropriate, but if the Cache-Control header specifies a restriction such as no-store or must-revalidate, the antiforgery system **wipes this out**. This can open security holes in an application. Here is the relevant code as currently implemented:

        private void SetDoNotCacheHeaders(HttpContext httpContext)
        {
            // Since antifogery token generation is not very obvious to the end users (ex: MVC's form tag generates them
            // by default), log a warning to let users know of the change in behavior to any cache headers they might
            // have set explicitly.
            LogCacheHeaderOverrideWarning(httpContext.Response);

            httpContext.Response.Headers[HeaderNames.CacheControl] = "no-cache";
            httpContext.Response.Headers[HeaderNames.Pragma] = "no-cache";
        }

This should be changed to check the header before overwriting it. If no-cache is already present in the header, the header should be left alone. For more information see https://openidauthority.com/asp-net-core-mvc-anti-forgery-system-opens-security-hole/

_Copied from original issue: aspnet/Antiforgery#156_

**Comment by aspnet-hello** [comment]
_From @blowdart on Friday, August 4, 2017 10:45:17 AM_

@Eilon we should address this in 2.1, by splitting the cache control header apart, checking for no-cache and no-store, and appending them to the existing header (if any) rather than just blowing the header away. Forcing the Pragma header is fine, because it only has one value anyway :)

**Comment by mkArtakMSFT** [comment]
@openidauthority, thanks for reporting this issue. We agree that this seems to be a bug and we've assigned one of our team members to look into this based on its priority.

**Comment by javiercn** [comment]
I do believe this is fixed https://github.com/aspnet/Antiforgery/blob/dev/src/Microsoft.AspNetCore.Antiforgery/Internal/DefaultAntiforgery.cs#L382

**Comment by jjxtra** [comment]
How do we turn this warning off? Seeing it all over in .NET core 2.2 on ubuntu...
