### ISSUE TITLE
Using Antiforgery with ASPNET Core API Login Action

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/Home#2415]
_From @patricknolan on Wednesday, July 26, 2017 8:38:21 PM_

I have an ASPNET Core API \ Angular app. My API needs to support cookies and tokens.

After I login using my service the anti-forgery token returned is not valid as it was created based on a null user. I've tried setting ClaimsPrincipal after my PasswordSignInAsync and regenerating the anti-forgery token (see below) but that still does not work. Any ideas?

```c#
public virtual async Task<IActionResult> Login([FromBody] AccountLoginModel model)
{
        var result = await this.SignInManager.PasswordSignInAsync(model.Email, model.Password, isPersistent: model.RememberMe, lockoutOnFailure: false);
        if (!result.Succeeded)
        {
            return this.BadRequest();
        }
        var user = await this.UserManager.FindByEmailAsync(model.Email);

        // Must manually set the HttpContext user claims to those of the logged
        // in user. Otherwise MVC will still include a XSRF token for the "null"
        // user and token validation will fail. (MVC appends the correct token for
        // all subsequent reponses but this isn't good enough for a single page
        // app.)
        var principal = await this.PrincipalFactory.CreateAsync(user);
        this.HttpContext.User = principal;

        // Update XSRF token
        var tokens = this.Antiforgery.GetAndStoreTokens(this.HttpContext);

        return this.Ok();
}
```

_Copied from original issue: aspnet/Antiforgery#155_

**Comment by aspnet-hello** [comment]
_From @Eilon on Wednesday, July 26, 2017 9:07:55 PM_

@blowdart / @rynowak - this type of question seems to come up fairly often - do we have a doc on exactly how to handle this case?

**Comment by aspnet-hello** [comment]
_From @patricknolan on Wednesday, July 26, 2017 9:16:42 PM_

Thanks @Eilon any doco would be great. I've spent hours trawling forums and posts but there doesn't seem to be a documented solution even though many people seem to have this issue.

**Comment by aspnet-hello** [comment]
_From @blowdart on Wednesday, July 26, 2017 9:40:33 PM_

Strange, re-gening it should work. @NTaylorMullen was looking at this recently. Taylor did you think GetAndStoreToken() didn't create a new one?

**Comment by aspnet-hello** [comment]
_From @patricknolan on Wednesday, July 26, 2017 11:30:02 PM_

The following forces the token to regenerate

```
...
var principal = await this.PrincipalFactory.CreateAsync(user);
this.HttpContext.User = principal;

var antiforgeryFeature = this.HttpContext.Features.Get<IAntiforgeryFeature>();
antiforgeryFeature.CookieToken = null;
antiforgeryFeature.HaveGeneratedNewCookieToken = false;
antiforgeryFeature.HaveDeserializedCookieToken = false;
antiforgeryFeature.NewRequestTokenString = null;
var tokens = this.Antiforgery.GetAndStoreTokens(this.HttpContext);
```
However, I still get the following error

> [16:26:07 INF] Antiforgery token validation failed. The provided antiforgery token was meant for a different claims-based user than the current user.
> Microsoft.AspNetCore.Antiforgery.AntiforgeryValidationException: The provided antiforgery token was meant for a different claims-based user than the current user.
>    at Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgery.ValidateTokens(HttpContext httpContext, AntiforgeryTokenSet antiforgeryTokenSet)
>    at Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgery.<ValidateRequestAsync>d__9.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.ValidateAntiforgeryTokenAuthorizationFilter.<OnAuthorizationAsync>d__3.MoveNext()
>

**Comment by aspnet-hello** [comment]
_From @patricknolan on Wednesday, July 26, 2017 11:36:44 PM_

In follow up... even though the token regenerates, GetAndStoreTokens does not update the existing cookie. To add the new token I have to do the following

```
this.HttpContext.Response.Cookies.Delete("XSRF-TOKEN");
var tokens = this.Antiforgery.GetAndStoreTokens(this.HttpContext);
this.HttpContext.Response.Cookies.Append("XSRF-TOKEN", tokens.RequestToken, new CookieOptions() { HttpOnly = false });
```

_Additional Info..._

**HttpContext Response Cookies on entering the login method**

> {XSRF-TOKEN=CfDJ8PjjbfA5CJ1CsCUTqHzw56Zcm5tedzYcuhdLHfWEUBO0WdBwWR2ouXSODQNbqk9_sJB8PKncPNrtIk-XHkZX8MleLMcbWguW-b-eUyaBk2mHMV7_m9ZgS0a0YwizcTyYmp7MB90o7-I6yzzNw-oLZQE; path=/,.Demo.Identity=CfDJ8LRkjsVQuSxNjvzgi9D1gN6AX2VCaPBI7qhd0snJkAysrAE2poSDp0tBwD1bDD61Z_Lq3d9XxZOY0uV08W0pmYI_E2aCKIYKtDU3EbiKiQKMFsPkYdWLoEIjzYpMAEcwIGbrEKSqKHeq8pC9GPK5leWJJyU_qLKycP4YwuIRdtC2uFewikff-Jzhe9XyYVylrSPXgAGGxcVtG5Q6JYVgXGDLXXeHwh2BQqeB-2VXc3HwUxB_WYyBg8Vaw6ew2GaB9_yoG9Akv7O0_3WawT5NGtBVzAHmuBKuA18auVXK3uCuTbDhCRcu4upvUoHjwt7pCcwZptOx1F_SdKTQarbXsT5ANYP_gfDtiX5WVpJj8FjWsu4ifLGgyA1Yw_er2DEbJ5qvbnPXxqQlIEV9DvpPFimXxoboIrjS7Q6wab8ZpUDuOvHmv0CVg3qeDiUuGvoDTW5F0fA7pQZk011Hrl-gLyezjVFJ_WExKkMVW6NXQJsz66yeO94vlocG_SOGzDq6u8TDvCeYFE_S71j5xz07zUokMF966_0R2clwyaQ4HlVdqrserKnBGLdfXKK70qhA_UphOxK6TY6q2R6yLjI9H0tPjoJmUsvXtcPYZORWA_u9Fv57FRXeIOLM5DUD8Wer3WB68W2LR9cO4uFB-QjLufLQDtmNGitkGXHKvkln95MQoDDO8OQAg6Iddq-2-mhvsJ8T4dm1rW-UssvBzR8hT9WA18jXoSTn_XbyD9GsHDcUam67F2W7enRuW20bPXAEMusVxnQB--wwduEH4CyKZY1FtMYpGnK04aDnBAtII44xyHYmfd9DeXo67rZYJjbq18cJx-HysBKPQ7v1_5qJtba-CEpIN-_JEVIsBpXDVK-pb4mVUvpvdDxMmVi69NHpICEZr81M3UlFc9HFtk73ygOkqZfRrc9Ria1RHeI6X2zRdObQhbmayHpnnI8bMhGoSLUuMHXAIVrx91UQepkgSwtwwUj1Rd3qUaqE71Tu_gOeww-yFuRblUKLRFEiZxI7ldy9VQkZa8uculMAt4NoohOlAtC5LqMBMCdwTB0WHsaj; path=/; httponly}

**HttpContext Response Cookies on exiting the login method**

> {.Demo.Identity=CfDJ8LRkjsVQuSxNjvzgi9D1gN6AX2VCaPBI7qhd0snJkAysrAE2poSDp0tBwD1bDD61Z_Lq3d9XxZOY0uV08W0pmYI_E2aCKIYKtDU3EbiKiQKMFsPkYdWLoEIjzYpMAEcwIGbrEKSqKHeq8pC9GPK5leWJJyU_qLKycP4YwuIRdtC2uFewikff-Jzhe9XyYVylrSPXgAGGxcVtG5Q6JYVgXGDLXXeHwh2BQqeB-2VXc3HwUxB_WYyBg8Vaw6ew2GaB9_yoG9Akv7O0_3WawT5NGtBVzAHmuBKuA18auVXK3uCuTbDhCRcu4upvUoHjwt7pCcwZptOx1F_SdKTQarbXsT5ANYP_gfDtiX5WVpJj8FjWsu4ifLGgyA1Yw_er2DEbJ5qvbnPXxqQlIEV9DvpPFimXxoboIrjS7Q6wab8ZpUDuOvHmv0CVg3qeDiUuGvoDTW5F0fA7pQZk011Hrl-gLyezjVFJ_WExKkMVW6NXQJsz66yeO94vlocG_SOGzDq6u8TDvCeYFE_S71j5xz07zUokMF966_0R2clwyaQ4HlVdqrserKnBGLdfXKK70qhA_UphOxK6TY6q2R6yLjI9H0tPjoJmUsvXtcPYZORWA_u9Fv57FRXeIOLM5DUD8Wer3WB68W2LR9cO4uFB-QjLufLQDtmNGitkGXHKvkln95MQoDDO8OQAg6Iddq-2-mhvsJ8T4dm1rW-UssvBzR8hT9WA18jXoSTn_XbyD9GsHDcUam67F2W7enRuW20bPXAEMusVxnQB--wwduEH4CyKZY1FtMYpGnK04aDnBAtII44xyHYmfd9DeXo67rZYJjbq18cJx-HysBKPQ7v1_5qJtba-CEpIN-_JEVIsBpXDVK-pb4mVUvpvdDxMmVi69NHpICEZr81M3UlFc9HFtk73ygOkqZfRrc9Ria1RHeI6X2zRdObQhbmayHpnnI8bMhGoSLUuMHXAIVrx91UQepkgSwtwwUj1Rd3qUaqE71Tu_gOeww-yFuRblUKLRFEiZxI7ldy9VQkZa8uculMAt4NoohOlAtC5LqMBMCdwTB0WHsaj; path=/; httponly,XSRF-TOKEN=; expires=Thu, 01 Jan 1970 00:00:00 GMT; path=/,XSRF-TOKEN=CfDJ8PjjbfA5CJ1CsCUTqHzw56ayp0IWpADcwr2hawx_7ln2zeW5fqWH-HdC-ulfatVNufGuSaNV4N5dVrCpkBGOwpew5fjyNrI35-xxQng0EFn51G0iN7LfKnXjZw7apnV8tHilaUpV5pLKMDGHlSpwATQ; path=/}

As you can see the Cookie delete method set the original XSRF-TOKEN cookie to expired and a new cookie with a new value was added.

At this point I'm out of ideas!

**Comment by aspnet-hello** [comment]
_From @NTaylorMullen on Thursday, July 27, 2017 12:15:58 AM_

Within the context of a single request tokens are only generated / set once. Therefore, if you `store tokens => login => store tokens` the second storing will be ignored.  I'm not 100% confident as to why we chose this model but I'd bet it's to ensure reliability in subsystems that retrieve the antiforgery token for form data posting. For example imagine:

1. Request a view
2. Token is created/stored
3. View generates form with proper token
4. Some post-rendering logic changes the token

In this scenario your view ends up not working due to the tokens change mid-way through the request.

@patricknolan Would you mind providing a simple repro application? I'd love to dive into it further to offer recommendations on how to proceed.

Also side note: This seems very similar to https://github.com/aspnet/Antiforgery/issues/83

**Comment by aspnet-hello** [comment]
_From @sagoo33 on Thursday, July 27, 2017 7:14:51 PM_

I was also receiving the "Antiforgery token validation failed. The provided antiforgery token was meant for a different claims-based user than the current user." error.

I have a multi page angular and perform the login via an angular call (which worked fine) but any other subsequent POST would fail with the above message.

I needed to set the context with the logged in user prior to adding the token cookie.
I'm not sure if this is the best way to do it but it is working now.

```
var authInfo = await context.Authentication.GetAuthenticateInfoAsync("Auth.Cookies");
context.User = authInfo.Principal;
```


Full snippet:

```
            app.Use(async (context, next) =>
            {
                string path = context.Request.Path.Value;
                if (path != null && !path.ToLower().Contains("/api"))
                {
                    // This is needed to provide the token generator with the logged in context (if any) 
                    var authInfo = await context.Authentication.GetAuthenticateInfoAsync("Auth.Cookies");
                    context.User = authInfo.Principal;

                    // XSRF-TOKEN used by angular in the $http if provided
                    var tokens = antiforgery.GetAndStoreTokens(context);
                    context.Response.Cookies.Append("XSRF-TOKEN",
                        tokens.RequestToken, new CookieOptions
                        {
                            HttpOnly = false,
                            Secure = forceHttps
                        }
                    );
                }
            });

```

**Comment by aspnet-hello** [comment]
_From @patricknolan on Thursday, July 27, 2017 8:02:14 PM_

Hi @sagoo33 this is actually the same code I posted above. This will not work if you're anti-forgery token in being set prior to entering your action (e.g. code below). Once the token is set, as @NTaylorMullen stated above, GetAndStoreTokens will not store a new token.

```
            app.Use(next => context =>
            {
                var antiforgery = context.RequestServices.GetService<IAntiforgery>();
                if (context.Request.Path.Value.ToLower().Equals("/") ||
                    context.Request.Path.Value.ToLower().Contains("/api"))
                {
                    var tokens = antiforgery.GetAndStoreTokens(context);
                    context.Response.Cookies.Append("XSRF-TOKEN", tokens.RequestToken, new CookieOptions() { HttpOnly = false });
                }
                return next(context);
            });
```

At present the only solution I can see is to set the anti-forgery token on exiting the action via an action result filter rather than on entering the action (see sample code below). I cannot see any reason why this would be an issue.

```
// Following code is located in ConfigureServices
services.AddMvc(options =>
{
    options.Filters.Add(new AutoValidateAntiforgeryTokenAttribute());
});
builder.AddMvcOptions(o =>
{
    o.Filters.AddService(typeof(AntiforgeryCookieResultFilter));
});
services.AddTransient<AntiforgeryCookieResultFilter>();


public class AntiforgeryCookieResultFilter : ResultFilterAttribute
{
    protected IAntiforgery Antiforgery { get; set; }
    public AntiforgeryCookieResultFilter(IAntiforgery antiforgery)
    {
        this.Antiforgery = antiforgery;
    }

    public override void OnResultExecuting(ResultExecutingContext context)
    {
        var tokens = this.Antiforgery.GetAndStoreTokens(context.HttpContext);
        context.HttpContext.Response.Cookies.Append("XSRF-TOKEN", tokens.RequestToken, new CookieOptions() { HttpOnly = false });
    }
}

```

Now the only issue is that regardless of whether you add the antiforgery token on entering or exiting an Action, the first time you call your Login Action you will not have a token. If you set the token using the app.Use approach (see above), then the first call will fail and all subsequent calls will succeed. But of course you then have the issue where the token returned as part of the login will be for the null user.

If you set the token using the ResultFilterAttribute approach, then the first call to the login action will fail and no antiforgery token will be returned. In this scenario perhaps the antiforgery check can be disabled for the login action using the IgnoreAntiforgeryTokenAttrbute. Opinions seem to very as to whether this is acceptable. Many people believe that this is ok for the login as a username\password is required anyway. Then once you are logged in, you will receive your first antiforgery token which can be used from then on.

**Comment by aspnet-hello** [comment]
_From @iwollmann on Thursday, August 3, 2017 1:17:51 PM_

I am stuck right now at this same problem, I imagine if we could have the old option to ignore the identity: [SuppressIdentityHeuristicChecks](https://msdn.microsoft.com/en-us/library/system.web.helpers.antiforgeryconfig.suppressidentityheuristicchecks(v=vs.111).aspx)

**Comment by aspnet-hello** [comment]
_From @chintan3100 on Sunday, August 6, 2017 6:17:34 AM_

I am getting the same issue. Any work around instead of calling API to get token after login
https://github.com/aspnet/Antiforgery/issues/157

**Comment by aspnet-hello** [comment]
_From @Eilon on Monday, August 7, 2017 11:02:04 AM_

@javiercn - can you look into this? I think we need to do at least a couple of things:

1. Make sure the default ASP.NET Core templates do "the right stuff" during login and logout.
2. Add any new helper APIs that make this scenario easier (or fix bugs if there are bugs).

I'm hoping that we can make this "so easy" that there's nothing to document.

**Comment by aspnet-hello** [comment]
_From @blowdart on Monday, August 7, 2017 11:21:21 AM_

Once we get to token auth this will go away, as long as you're using tokens of course.

I'd be weary of bringing back  SuppressIdentityHeuristicChecks, it's a nightmare.

**Comment by aspnet-hello** [comment]
_From @jchannon on Wednesday, November 1, 2017 6:59:55 AM_

I'm hitting something similar, I do 

```
                await httpContext.SignInAsync("VQCookieMW", claimsPrincipal, authProperties);
                
                var tokens = this.antiforgery.GetAndStoreTokens(httpContext);
               
                httpContext.Response.Cookies.Append("XSRF-TOKEN", tokens.RequestToken, 
                    new CookieOptions { HttpOnly = false });
                
```

Auth and XSRF and Antiforgery cookies returned. Angular does a POST with a X-XSRF-HEADER and I get `The provided antiforgery token was meant for a different claims-based user than the current user.`

Is the advice to call another endpoint after login which returns the XSRF & Antiforgery cookies?

**UPDATE** :  I have a method that does SignIn, returns a Response.Redirect which then hits a method that returns the XSRF cookies and redirects to the html page. Seems to work but JFC 😄

**Comment by javiercn** [comment]
We will be providing a sample on how to do this. Closing this issue and pointing to the other issue for tracking https://github.com/aspnet/samples/issues/2

**Comment by paulsperanza** [comment]
Any progress on this? I am stuck too. Using it with the new Angular CLI template.
