### ISSUE TITLE
AntiforgeryTokenSet should have a CookieName property

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/Home#2416]
_From @NTaylorMullen on Thursday, July 20, 2017 12:01:57 PM_

It has `HeaderName` which is retrievable; it should also have `CookieName`.

_Copied from original issue: aspnet/Antiforgery#153_

**Comment by aspnet-hello** [comment]
_From @Eilon on Wednesday, July 26, 2017 9:08:29 PM_

@NTaylorMullen - any idea of a scenario where this might matter a lot? Or is it more about consistency and/or theoretical case?

**Comment by aspnet-hello** [comment]
_From @NTaylorMullen on Wednesday, July 26, 2017 11:56:42 PM_

In scenarios where cookies may have been reconstructed prior to sending a request you have to rely on convention (setting a magic string on both the client and server) to get Antiforgery to work. It's uncommon but occurs in JavaScript/custom http clients/other API services that don't maintain cookies across requests.

**Comment by aspnet-hello** [comment]
_From @Eilon on Thursday, July 27, 2017 1:25:12 PM_

> reconstructed prior to sending a request

What exactly does that mean? Wouldn't the client just have to use whatever cookie name the server is expecting?

**Comment by aspnet-hello** [comment]
_From @NTaylorMullen on Thursday, July 27, 2017 3:04:01 PM_

> Wouldn't the client just have to use whatever cookie name the server is expecting?


Yes, that's the "magic string" part of it. For example see this reconstruction of a request:

```
document.cookie="MagicCookieName=@token.CookieToken";
$.ajax({
    url: "...",
    contentType: "application/json",
    data: JSON.stringify({}),
    type: "POST",
    headers: {
        "@token.HeaderName": @token.RequestToken
    }
});
```

Basically, you configure antiforgery in your startup and then you have no way to retrieve what the `CookieName` was configured to.

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was no much community interest in this ask for quite a while now.
