### ISSUE TITLE
GetAndStoreTokens(...).CookieToken seems to always be null

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/Home#2417]
_From @NTaylorMullen on Wednesday, July 19, 2017 4:52:23 PM_

Take the following example:

```C#
app.Run(async (context) =>
{
    var antiforgery = context.RequestServices.GetRequiredService<IAntiforgery>();

    // The token.CookieToken is always null
    await context.Response.WriteAsync("<p>Cookie Token: " + token.CookieToken + "</p><br />");
});
```

I'm not confident as to how many valid scenarios utilize the `token.CookieToken` but it's a blatant issue nevertheless.

_Copied from original issue: aspnet/Antiforgery#152_

**Comment by aspnet-hello** [comment]
_From @NTaylorMullen on Thursday, July 20, 2017 12:25:43 PM_

Did a deep investigation of this and the root cause of the issue Is that we always utilize newly created cookie tokens when creating our AntiforgeryTokenSet… This means that after the first request there’s no “new” cookie token and it therefore returns null.

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was no much community interest in this ask for quite a while now.
