### ISSUE TITLE
Apply JsonPatch when set of properties are different in DTO than Entity

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/Home#2422]
_From @sachinpachori on Wednesday, December 27, 2017 3:19:02 PM_

This is a common scenario where your DTO/viewmodel could be different from the Entities. In this case how to use this JSONPatch with ApplyTo function. If possible, I think you should work on providing this feature.

_Copied from original issue: aspnet/JsonPatch#127_

**Comment by mkArtakMSFT** [comment]
This is not a functionality we provide explicitly, but you can use something like AutoMapper(http://automapper.org/) to handle it.

**Comment by RoboBurned** [comment]
It is almost useless without this feature.
void Patch(JsonPatchDocument<UserEntity> patch)
{
patch.ApplyTo(userEntity);
}
I cannot use it this way because my UserEntity has collection of Roles and anybody can "patch" it.
We need to separate the list of fields in patch from the entity.

**Comment by migpfernandes** [comment]
Hi,
is there any new solution to perform this kind of actions? I've two scenarios for this where I'm getting stuck:
1) I have a gateway that first receives the PatchDocument and then propagates request for proper service through it's SDK. Gateway type is JsonPatchDocument<Gateway.ContactDTO> and service is JsonPatchDocument<Service.ContactDTO>. Any elegant way of converting one to another?
2) In service we want to receive the JsonPatchDocument<Service.ContactDTO> but apply it to Service.Domain.Contact. Is this possible without getting domain object, mapping to DTO, applying Patch and converting to Domain object again?
