### ISSUE TITLE
Add application/manifest+json ( .webmanifest)

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/Home#2440]
_From @RehanSaeed on Monday, October 30, 2017 2:58:49 AM_

Added support fot the `.webmanifest` file extension which returns `application/manifest+json`.

See [sonarwhal documentation](https://sonarwhal.com/docs/user-guide/rules/manifest-file-extension/) and [W3C](https://w3c.github.io/manifest/#media-type-registration) for reference.

_Copied from original issue: aspnet/StaticFiles#221_

**Comment by rickyruiz** [comment]
Any news on when is this PR going live? 

___

If anyone is stuck with this, you can create a custom content type provider like so:

```
  public class PwaContentTypeProvider : FileExtensionContentTypeProvider
  {
    public PwaContentTypeProvider()
    {
      Mappings.Add(".webmanifest", "application/manifest+json");
    }
  }
```

In Startup.cs:

``` 
app.UseStaticFiles(new StaticFileOptions()
{
  ContentTypeProvider = new PwaContentTypeProvider()
});
```
