### ISSUE TITLE
StaticFileContext.ValidateMethod wrongly named

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/Home#2443]
_From @vanillajonathan on Saturday, October 7, 2017 8:34:32 AM_

The `ValidateMethod` in the `StaticFileContext` should probably be named `IsValidMethod`.

_Copied from original issue: aspnet/StaticFiles#217_

**Comment by aspnet-hello** [comment]
_From @Tratcher on Saturday, October 7, 2017 9:32:48 AM_

I don't see why. It's doing more work than the IsXXX properties.
https://github.com/aspnet/StaticFiles/blob/826e89a2d1b325485819040ff41b9948afc91e06/src/Microsoft.AspNetCore.StaticFiles/StaticFileContext.cs#L111-L117

**Comment by aspnet-hello** [comment]
_From @vanillajonathan on Saturday, October 7, 2017 11:03:18 AM_

It does not really do any action, it just checks conditions.

It checks if something **is** valid by checking if the HTTP request method **is** a GET or a HEAD.

**Comment by muratg** [comment]
This wold also be a breaking change.
