### ISSUE TITLE
Need ServiceFileProvider similar to ServiceFilterAttribute

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/Home#2450]
_From @mchender on Thursday, April 6, 2017 8:33:39 AM_

I'd like to be able to retrieve an instance of my file provider from DI similar to how ServiceFilterAttribute works.
https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/filters#servicefilterattribute

```c#
services.Configure<RazorViewEngineOptions>(options =>
{
     options.FileProviders.Clear();
      options.FileProviders.Add(new ServiceFileProvider(typeof(CacheFileProvider)));
});
```

This was discussed in another thread in Entity Framework but since they found a workaround I don't know that anyone followed up submitting the issue here.
https://github.com/aspnet/EntityFramework/issues/4544#issuecomment-184794032

My current workaround was to follow the guidance provided in the following comment which stores a reference to IServiceProvider in a static property. However, they indicate it is a bad practice that should be avoided if possible.
https://github.com/aspnet/DependencyInjection/issues/294#issuecomment-142206501

My true goal was to develop a library that can render a MVC Razor view to a string. There is an example of how to do this in the Entropy repository. However, it requires the view to exist on disk.
https://github.com/aspnet/Entropy/tree/dev/samples/Mvc.RenderViewToString

My templates will come from a database so I need to be able to pass the view as a string and get the rendered output as a string. I updated the sample from Entropy by adding a custom implementation of IFileProvider that will load the the template from the cache. When I pass in the string from the database it adds the template to the cache using a randomly generated guid as the key. When I request the view from the IRazorViewEngine I use that guid as the file name so that later I can use it as the key to retrieve the template from the cache.
https://github.com/mchender/Entropy/tree/dev/samples/Mvc.RenderViewToString

Snippet from https://github.com/mchender/Entropy/blob/dev/samples/Mvc.RenderViewToString/Program.cs
```c#
public static Task<string> RenderViewAsync(RazorViewToStringRenderer helper)
        {

            var model = new EmailViewModel
            {
                UserName = "User",
                SenderName = "Sender",
                UserData1 = 1,
                UserData2 = 2
            };

            string template = $@"
                                    <!DOCTYPE html>

                                    <html>
                                    <body>
                                        <div>
                                            @model Mvc.RenderViewToString.EmailViewModel

                                    `       Hello @Model.UserName,
        
                                            <p>

                                                This is a generic email about something.<br />

                                                It also contains some content that is generated by a partial view.<br />
                                                @inject Mvc.RenderViewToString.EmailReportGenerator ReportGenerator

                                                This is the partial view content.<br />
                                                @ReportGenerator.GenerateReport(Model.UserData1, Model.UserData2).<br />
                                                <br />
                                            </p>
                                        </div>
                                        <footer>
                                            Thanks,<br />
                                            @Model.SenderName
                                        </footer>
                                    </body>
                                    </html>
                                    ";

            return helper.RenderViewToStringAsync(template, model);
}
```

Snippet from https://github.com/mchender/Entropy/blob/dev/samples/Mvc.RenderViewToString/RazorViewToStringRenderer.cs
```c#
public async Task<string> RenderViewToStringAsync<TModel>(string template, TModel model)
{
            var actionContext = GetActionContext();

            //add the template to the cache
            var name = Guid.NewGuid().ToString();
            _cache.Set(name, template);

            var viewEngineResult = _viewEngine.FindView(actionContext, name, false);
```
Snippet from https://github.com/mchender/Entropy/blob/dev/samples/Mvc.RenderViewToString/CacheFileInfo.cs
```c#
private void GetView(string viewName)
{
            string fileNameWithoutExtension = Path.GetFileNameWithoutExtension(_viewPath);
            if (fileNameWithoutExtension == "_ViewImports")
                _viewContent = null;
            else
            {
                _lastModified = DateTime.UtcNow;
                _exists = true;
                IMemoryCache cache = ServiceProviderProvider.ServiceProvider.GetRequiredService<IMemoryCache>();
                var template = cache.Get(fileNameWithoutExtension);
                _viewContent = Encoding.UTF8.GetBytes(template.ToString());
            }
}
```
It would be much cleaner if IMemoryCache could be loaded using DI instead of having to use a static property to access IServiceProvider to request the service myself.

_Copied from original issue: aspnet/StaticFiles#184_

**Comment by aspnet-hello** [comment]
_From @muratg on Tuesday, September 26, 2017 3:38:15 PM_

@danroth27 @DamianEdwards thoughts?

**Comment by aspnet-hello** [comment]
_From @danroth27 on Wednesday, September 27, 2017 7:56:08 AM_

@Eilon @pranavkm @rynowak

**Comment by aspnet-hello** [comment]
_From @pranavkm on Wednesday, September 27, 2017 8:06:07 AM_

For the issue that @mchender is running in to, `IConfigureOptions` would be a better way to get to it rather than using the static field:

```C#
public class CustomFileProviderOptions : IConfigureOptions<RazorViewEngineOptions>
{
    private IFileProvider _fileProvider;
    
    public CustomFileProviderOptions(IMyApplicationFileProvider fileProvider)
    {
        _fileProvider = fileProvider;
    }
    
    public void Configure(RazorViewEngineOptions options)
    {
        options.FileProviders.Clear();
        options.FileProviders.Add(_fileProvider);
    }
}

services.AddMvc();
services.AddTransient<IConfigureOptions<RazorViewEngineOptions>, CustomFileProviderOptions>();
services.AddSingleton<IMyApplicationFileProvider, CacheFileProvider>(); // Use a custom marker interface so you aren't conflating it with random IFileProvider instances in the DI
```

If we do make this a first class feature (and I'm not entirely convinced we should), it would be consistent to ensure Hosting `IHostingEnvironment.ContentRootFileProvider \ WebRootFileProvider` and StaticFiles also support this.

**Comment by aspnet-hello** [comment]
_From @rynowak on Wednesday, September 27, 2017 12:29:32 PM_

It would be amazing to have `Configure<TOptions, TArg1>(Action<TOptions, TArg1>)` where `TArg1` is resolved from services. Basically the code that @pranavkm provided except the `Configure` method calls your delegate and is provided by the options system.

We have to write these classes like this all of the time in MVC and it's tedious. 

/cc @davidfowl  is this something that was discuussed?

**Comment by aspnet-hello** [comment]
_From @davidfowl on Friday, September 29, 2017 2:33:03 AM_

It's not a bad idea but its noisy because you have to specify all generic arguments. @HaoK recently made registering `IConfigureOptions` a bit nicer in 2.1. You can do this now:


Old:
```
services.AddTransient<IConfigureOptions<RazorViewEngineOptions>, CustomFileProviderOptions>();
```

New:

```
services. ConfigureOptions<CustomFileProviderOptions>();
```

**Comment by aspnet-hello** [comment]
_From @mchender on Friday, September 29, 2017 9:09:57 AM_

@pranavkm that provides a workaround for the question in this post. Is there some equivalent workaround which would allow me to get around having to pass an instance of my file provider when configuring the hosting environment?

```c#
IFileProvider fileProvider = new CacheFileProvider();
services.AddSingleton<IHostingEnvironment>(new HostingEnvironment
{
       ApplicationName =  applicationEnvironment.ApplicationName,
       WebRootFileProvider = fileProvider,
});
```

**Comment by aspnet-hello** [comment]
_From @rynowak on Friday, September 29, 2017 9:16:08 AM_

> It's not a bad idea but its noisy because you have to specify all generic arguments.

But you still have to write the class:
```
public class CustomFileProviderOptions : IConfigureOptions<RazorViewEngineOptions>
{
    private IFileProvider _fileProvider;
    
    public CustomFileProviderOptions(IMyApplicationFileProvider fileProvider)
    {
        _fileProvider = fileProvider;
    }
    
    public void Configure(RazorViewEngineOptions options)
    {
        options.FileProviders.Clear();
        options.FileProviders.Add(_fileProvider);
    }
}
```

5/7 loc of that are boilerplate. Feels bad man

```
services.Configure<RazorViewEngineOptions, IMyApplicationFileProvider>((options, provider) =>
{
        options.FileProviders.Clear();
        options.FileProviders.Add(_fileProvider);
});
```

VS

```
services.ConfigureOptions<CustomFileProviderOptions>();
...
public class CustomFileProviderOptions : IConfigureOptions<RazorViewEngineOptions>
{
    private IFileProvider _fileProvider;
    
    public CustomFileProviderOptions(IMyApplicationFileProvider fileProvider)
    {
        _fileProvider = fileProvider;
    }
    
    public void Configure(RazorViewEngineOptions options)
    {
        options.FileProviders.Clear();
        options.FileProviders.Add(_fileProvider);
    }
}
```

**Comment by aspnet-hello** [comment]
_From @Tratcher on Friday, September 29, 2017 9:26:41 AM_

Still not sure why this discussion is in this repo...

**Comment by aspnet-hello** [comment]
_From @mchender on Friday, September 29, 2017 9:28:00 AM_

@Tratcher based on this comment 
https://github.com/aspnet/EntityFrameworkCore/issues/4544#issuecomment-184794032

**Comment by aspnet-hello** [comment]
_From @mchender on Friday, September 29, 2017 10:22:13 AM_

@pranavkm  you can ignore my follow up question. It looks like I don't have to set WebRootFileProvider on the HostingEnvironment for the application to work properly. I made the changes you suggested and I was able to get DI to resolve the services I need in CacheFileInfo. Here's the commit.
https://github.com/mchender/Entropy/commit/7405b5965d86c793f81b05c44908a611a4813b6a

My issues are resolved. Feel free to close this issue if needed. Otherwise I am interested in the result of the conversation between @rynowak and @davidfowl and how to either make this a first class feature or at least make how it's configured as intuitive as possible.

**Comment by aspnet-hello** [comment]
_From @HaoK on Friday, September 29, 2017 11:34:06 AM_

Ok, we could add a new generic base configure, maybe something like:

`services.ConfigureFromDI<TOptions, TDependency>(Action<TOptions> configure)`

which would register as transient something like:
```
class ConfigureFromDI<TOptions, TDependency> : IConfigureOptions<TOptions> {
    ConfigureWithDI(TDependency dep) => Dep = dep;
    TDependency Dep { get; }
}
```

If the configure options needs more than one dependency, to use this sugar you'd have to wrap them and register it and get them out as properties?

```
services.AddScoped<MyOptionsDep>();
class MyOptionsDep {
   MyOptionsDep(MyService1 s, MyService2, s2);

  MyService1 Service1 { get; }
  MyService2 Service1 { get; }
}
```

**Comment by aspnet-hello** [comment]
_From @davidfowl on Friday, September 29, 2017 12:07:47 PM_

Leave out the FromDI part it would just be configure with a bunch of overloads for dependencies. We can start with 5 dependencies 😄

**Comment by aspnet-hello** [comment]
_From @HaoK on Friday, September 29, 2017 12:10:06 PM_

Ok so just have 5 overloads, with 1 to 5 extra args, and they will just roll their own otherwise.  I'll file an issue

**Comment by aspnet-hello** [comment]
_From @HaoK on Friday, September 29, 2017 12:12:23 PM_

https://github.com/aspnet/Options/issues/236

**Comment by poke** [comment]
This thread seems to have spiraled away into a `Configure<TOptions, TDep>` direction (which we have now in 2.1) but the original issue remains (at least for me):

I would like to serve the static files middleware with a custom file provider, and that file provider needs access to DI to retrieve a database context. Since the file provider is set statically with the `UseStaticFiles()` call, I am not able to use a non-singleton file provider that would get its dependencies directly injected.

I am currently doing something like this:

```c#
public void Configure(IApplicationBuilder app, CustomFileProvider photoFileProvider)
{
    // …
    app.UseStaticFiles(new StaticFileOptions
    {
        RequestPath = "/files",
        FileProvider = customFileProvider,
    });
    // …
}

public class PhotoFileProvider : IFileProvider
{
    private readonly IServiceScopeFactory _serviceScopeFactory;
    public PhotoFileProvider(IServiceScopeFactory serviceScopeFactory)
    {
        _serviceScopeFactory = serviceScopeFactory;
    }

    public IFileInfo GetFileInfo(string subpath)
    {
        using (var scope = _serviceScopeFactory.CreateScope())
        {
            var dataContext = scope.ServiceProvider.GetService<DataContext>();
            // …
        }
    }
    // …
}
```

But having to create a new (nested) service scope on every request seems to be a waste. Now that I think about it, I could probably also inject the `IHttpContextAccessor` and retrieve the current context and resolve the services through that. Since the `GetFileInfo` is called from within the StaticFilesMiddleware, this should be safe.

I would appreciate if there was a better way though. A nicer way to plug services into the file provider; or a nicer way to plug into StaticFilesMiddleware itself. With its huge _internal_ `StaticFileContext` which appears to do *everything*, the middleware is somewhat difficult to customize (especially when you are used to the well composed MVC).

**Comment by khellang** [comment]
Couldn't you just implement an `IPostConfigureOptions<StaticFileOptions>`, inject your `IFileProvider` and set it on the options instance?

**Comment by khellang** [comment]
This is a recurring problem, though. 

It would be much better if the framework had factory options instead of instance options, i.e.

```csharp
public Func<IServiceProvider, IFileProvider> FileProviderFactory { get; set; }
```

Instead of

```csharp
public IFileProvider FileProvider { get; set; }
```

**Comment by poke** [comment]
Huh, does using PostConfigure work here? I was thinking not because [the options object is directly passed](https://github.com/aspnet/StaticFiles/blob/rel/2.0.0/src/Microsoft.AspNetCore.StaticFiles/StaticFileExtensions.cs#L67) to the middleware, so the options DI stuff never actually runs.

Yeah, such a factory pattern would be nice, but I think we would already be fine (and probably more flexible) if we used named options for the static files middleware; named so that we can have multiple static files middlewares with different configurations.

**Comment by mchender** [comment]
@poke In the [original thread](https://github.com/aspnet/StaticFiles/issues/184) I posted a commit where I was able to leverage their recommendation to resolve the dependencies from the configured options.
https://github.com/mchender/Entropy/commit/7405b5965d86c793f81b05c44908a611a4813b6a

My example is resolving the dependencies from the cache instead of a database but the application I built from that example retrieves the view from the database following the same logic. Here's the full example.
https://github.com/mchender/Entropy/tree/dev/samples/Mvc.RenderViewToString

I'm not sure I understand why you'd still have the need to resolve the dependencies from the container.

**Comment by poke** [comment]
@mchender The StaticFilesMiddleware is not set up using the options pattern through DI. You pass a static options object when you add the middleware, so you cannot resolve dependencies in there, you have to resolve the up front. This is a problem if you want to resolve request scoped dependencies.

**Comment by HaoK** [comment]
@poke so middleware typically support taking options instances or via DI.  Where UseXyz(options) would use the instance, while UseXyz() would use the options from DI.  Its kind of confusing but middleware were taking options instances already, and its better than forcing everyone to always go through ConfigureServices to configure middleware options

**Comment by khellang** [comment]
If only all MW used option delegates and DI, like god intended 😉

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
