### ISSUE TITLE
Update CoreFx Code

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/Home#2459]
_From @anurse on Thursday, December 21, 2017 11:55:02 AM_

We need to either update our CoreFx code in 2.1 **or** get the `CreateFromStream` API OOBed (https://github.com/dotnet/corefx/issues/21537) so we can use it.

Ping @muratg @Eilon : This should go in 2.1. Probably in preview1 if we can squeeze it in (at least updating the code from CoreFx, it's mostly automated via a script)

_Copied from original issue: aspnet/WebSockets#214_

**Comment by aspnet-hello** [comment]
_From @kasper3 on Thursday, December 21, 2017 12:05:33 PM_

Thank you!

If it's just a matter of running the powershell script and making sure CI passes all the tests, I can give it a quick try! Just hoping to get it in this year 💙

**Comment by aspnet-hello** [comment]
_From @anurse on Thursday, December 21, 2017 12:08:27 PM_

It **may** be that simple ;). Feel free to give it a shot. There may have been some new code added to corefx, and the files may have been moved around since we did it last time.

**Comment by aspnet-hello** [comment]
_From @kasper3 on Thursday, December 21, 2017 4:50:50 PM_

Apparently it needs some more digging. The netstandard System.Net.WebSockets package doesn't have methods in WebSocket class that ManagedWebSocket is overriding.

I got to the point, where compiler (with latest KoreBuild) is complaining about `public override ValueTask<ValueWebSocketReceiveResult> ReceiveAsync(Memory<byte> buffer, CancellationToken cancellationToken)`, no method to override..

**Comment by aspnet-hello** [comment]
_From @anurse on Thursday, December 21, 2017 6:54:03 PM_

Ah yeah, they changed some APIs recently. I'll take a look at it and we'll try to get it up to date for preview 1.

**Comment by anurse** [comment]
We can't take the latest changes due to API changes. However, I'm going to bring over just the fix in https://github.com/dotnet/corefx/pull/24055 for Preview 1.

**Comment by mkArtakMSFT** [comment]
@anurse , I've moved this to preview2 milestone. If, however, you strongly believe that this should be done for preview1, let's have a chat.

**Comment by kasper3** [comment]
Fixed by aspnet/WebSockets#222, preview package available at: https://dotnet.myget.org/feed/aspnetcore-dev/package/nuget/Microsoft.AspNetCore.WebSockets. Thanks @anurse! 🎉
