### ISSUE TITLE
CoreCLR 2.0 - TODO for resources in error handling

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/Home#2465]
_From @stephentoub on Thursday, August 17, 2017 7:22:57 AM_

_From @ayende on August 17, 2017 14:7_

When a web socket connection is broken, I'm getting this:

![image](https://user-images.githubusercontent.com/116915/29416327-664801fc-836e-11e7-8f58-7ee462a1a644.png)

I assume that is something that should be fixed :-)

_Copied from original issue: dotnet/coreclr#13425_

_Copied from original issue: aspnet/WebSockets#198_

**Comment by aspnet-hello** [comment]
_From @stephentoub on Thursday, August 17, 2017 7:22:58 AM_

That's coming from here:
https://github.com/aspnet/WebSockets/blob/4e2ecf8a63b9fc78175d1ef62bf2b1918b8b3986/src/Microsoft.AspNetCore.WebSockets/Internal/fx/SR.cs#L22

**Comment by aspnet-hello** [comment]
_From @jkotalik on Tuesday, August 22, 2017 11:47:05 PM_

Looks like we need to update our copy of WebSockets, I'll go ahead and fix that.

**Comment by aspnet-hello** [comment]
_From @jkotalik on Tuesday, August 22, 2017 11:59:38 PM_

@anurse Seems like we need to also be copying https://github.com/dotnet/corefx/blob/master/src/System.Net.WebSockets/src/Resources/Strings.resx for the comments?

**Comment by aspnet-hello** [comment]
_From @anurse on Wednesday, August 23, 2017 12:48:32 PM_

Yep, sounds right

**Comment by aspnet-hello** [comment]
_From @anurse on Wednesday, August 23, 2017 4:31:23 PM_

I'd propose this for a patch release. If not 2.0.1, then the next one. The risk is low and the impact is pretty high: Having these exception messages be completely bogus strings is not a good thing and it's easy for a customer to encounter this.

Note: the PR for this also brings in some behavior changes, we would need to fully understand those before considering taking those in the patch as well, but taking the exception message changes should have no behavioral impact and should be very safe for patching

/ping @muratg @Eilon

**Comment by aspnet-hello** [comment]
_From @davidfowl on Wednesday, August 23, 2017 10:32:29 PM_

Damn I forgot to file this bug in 2.0.0 https://github.com/dotnet/corefx/issues/21509 😞

**Comment by aspnet-hello** [comment]
_From @Eilon on Thursday, August 24, 2017 9:46:03 AM_

Moving out of patch milestone.

**Comment by aspnet-hello** [comment]
_From @jkotalik on Monday, September 18, 2017 11:53:31 AM_

@anurse Do we still want to merge this in or figure out a better solution?

**Comment by aspnet-hello** [comment]
_From @Tratcher on Monday, September 18, 2017 1:44:28 PM_

We need to find an non-manual solution.

**Comment by aspnet-hello** [comment]
_From @anurse on Monday, September 18, 2017 3:34:01 PM_

We need https://github.com/dotnet/corefx/issues/21537, which is still on the queue for 2.1

Then we can just remove the copying altogether

**Comment by aspnet-hello** [comment]
_From @jkotalik on Monday, September 18, 2017 3:52:01 PM_

Closed my PR as we will wait for corefx to expose their implementation in 2.1.

**Comment by aspnet-hello** [comment]
_From @davidfowl on Wednesday, September 20, 2017 1:48:43 AM_

Will that package be netstandard?

**Comment by aspnet-hello** [comment]
_From @anurse on Wednesday, September 20, 2017 8:36:39 AM_

My understanding is yes. It will support the managed implementation on all platforms with non-managed light-ups

**Comment by aspnet-hello** [comment]
_From @jkotalik on Thursday, September 28, 2017 2:49:30 PM_

Awaiting response from https://github.com/dotnet/corefx/issues/21537 for next action.

**Comment by aspnet-hello** [comment]
_From @anurse on Thursday, September 28, 2017 3:49:13 PM_

Well, it sounds like we're going to keep copy-🍝 for now, so I guess we should just update our code with the latest. Note that https://github.com/dotnet/corefx/pull/24288 is pending and we may as well wait until that's in to pull it as well.

**Comment by aspnet-hello** [comment]
_From @anurse on Friday, September 29, 2017 9:35:04 AM_

The PR I referenced has been merged. @jkotalik , we might as well do another code sync from the latest corefx master using the script. It's relatively harmless even if we end up moving away from code sharing and it makes sure we don't accidentally ship another release with this problem ;)

**Comment by aspnet-hello** [comment]
_From @jkotalik on Friday, September 29, 2017 9:58:50 AM_

I mean the whole problem before was we weren't pulling the resx file for websockets. We will need to add that to the script.

**Comment by aspnet-hello** [comment]
_From @anurse on Friday, September 29, 2017 12:09:41 PM_

Yeah, I'm not happy about expanding our code-copying, but if they're not going to release an OOB we're going to have to do it eventually. We don't have to rush in to fixing this, but by 2.1 RTM we have to do one of: fix the script and copy the resx, or drop the source copying and switch to an OOBed package.

**Comment by aspnet-hello** [comment]
_From @stephentoub on Friday, September 29, 2017 12:22:43 PM_

> We don't have to rush in to fixing this

Yeah, I suggest you hold off.  I'm still hopeful they'll be an OOB here.

**Comment by jkotalik** [comment]
This will be handled by https://github.com/aspnet/WebSockets/pull/220. cc/ @anurse

**Comment by anurse** [comment]
We're now using the corefx package as a binary rather than copying code, so this shouldn't be an issue any more!
