### ISSUE TITLE
Autobahn Test suite CI failures

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/Home#2474]
_From @jbagga on Wednesday, March 22, 2017 12:23:57 PM_

[AutobahnTestSuite](https://github.com/aspnet/WebSockets/blob/dev/test/Microsoft.AspNetCore.WebSockets.ConformanceTest/AutobahnTests.cs#L22) is consistently flaky on OSX and occasionally on Win8, 10, 2012.

http://aspnetci/project.html?projectId=XPlat&testNameId=-7856782943084166959&tab=testDetails

_Copied from original issue: aspnet/WebSockets#157_

**Comment by aspnet-hello** [comment]
_From @jbagga on Wednesday, March 22, 2017 12:43:13 PM_

cc @anurse

**Comment by aspnet-hello** [comment]
_From @anurse on Wednesday, March 22, 2017 3:26:55 PM_

The Windows failures are because IIS appears to be flaky at forwarding WebSocket connections (see https://github.com/aspnet/AspNetCoreModule/issues/80). I'll disable IIS testing to get rid of that bit of flakiness.

The OSX failure seems very odd, so I'm getting a bit more information on it.

I'm really hesitant to skip these tests because they are the only way we ensure our WebSockets implementation conforms to the spec.

**Comment by Eilon** [comment]
@anurse / @muratg - is this the same as https://github.com/aspnet/Home/issues/2471 ?

**Comment by muratg** [comment]
@Eilon Looks like different failures. I'm putting this in 2.2.0-mq. @anurse if you have any thoughts, let me know.

**Comment by natemcmaster** [comment]
We believe this is resolved.
