### ISSUE TITLE
Pack Exclude does not work on sub folders

### ISSUE THREAD

**Issue by devmondo** [aspnet/Home#248]
i am using the following pattern
```
"packExclude": [
		"node_modules",
		"bower_components",
		"**.kproj",
		"**.user",
		"**.vspscc",
		"wwwroot/lib",
		"!wwwroot/lib/angular"
	]
```
everything works fine except for "lib" folder, which still get copied to publish folder with all its content, the way i want it is same as grunt or gulp, so i want to exclude all folders and files inside "lib" folder and only include "angular  folder or js files that start with "angular"

**Comment by danroth27** [comment]
Tracking this request with https://github.com/aspnet/XRE/issues/1352.
