### ISSUE TITLE
Install through Nuget

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/Home#2484]
_From @jnapier on Friday, December 1, 2017 10:09:49 AM_

I cannot find this package through Nuget. The only available version I see is 0.2.0 from Nov 15, 2016.  I am looking at the Microsoft.AspNetCore.Proxy package. Is this project under a different name? Can spmeone help me on locating the most recent version? Thank you.

_Copied from original issue: aspnet/Proxy#80_

**Comment by aspnet-hello** [comment]
_From @anorborg on Saturday, December 2, 2017 7:59:33 AM_

I'm also curious about this. It seems 0.3.0 has a decent amount of changes (including some used in the samples, i.e. `IServiceCollection` extensions). I see a reference to rtm in the myget for aspnetcore-dev thats a few months old. Maybe just not published to nuget? https://dotnet.myget.org/feed/aspnetcore-dev/package/nuget/Microsoft.AspNetCore.Proxy

**Comment by aspnet-hello** [comment]
_From @stijnvanbossuyt on Thursday, December 7, 2017 4:59:33 AM_

Error CS1061: 'HttpContext' does not contain a definition for 'ProxyRequest' and no extension method 'ProxyRequest' accepting a first argument of type 'HttpContext' could be found (are you missing a using directive or an assembly reference?). When using 0.3.0-rtm-26423

**Comment by bbaumann** [comment]
I confirm nuget still contains only the old 0.2.0 version.
Several bugs are fixed in the 0.3.0 . Is it planned to update the version present on nuget?

**Comment by Tratcher** [comment]
No, the Proxy package is not currently being developed or shipped.
