### ISSUE TITLE
Added PrepareWebSocketClient option

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/Home#2488]
_From @saithis on Tuesday, November 28, 2017 12:23:10 AM_

There was already a PrepareRequest for HttpRequests and with this we have the same for websockets. This PR replaces #75 as the rest of #75 is already possible in a better way, as described by @mkosieradzki .

_Copied from original issue: aspnet/Proxy#76_

**Comment by saithis** [comment]
Why was this closed? (@aspnet-hello ?)

**Comment by aspnet-hello** [comment]
This was an accidental issue created from this PR: https://github.com/aspnet/Proxy/pull/76

So this issue isn't needed - just use the original PR at https://github.com/aspnet/Proxy/pull/76.
