### ISSUE TITLE
Validate Redis extension for shipping

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/Home#2509]
_From @natemcmaster on Monday, July 3, 2017 3:34:48 PM_

Microsoft.AspNetCore.DataProtection.Redis ships as a 0.x version (which means it's pseudo-unsupported.) It also does not ship in the runtime store.

Verification items to complete before we ship a "supported" version:

 - Add functional tests that actually use a real Redis server to pull keys
 - Update version number
 - Add to ASP.NET Core runtime store
 - Add API baselines ( #232 )

_Copied from original issue: aspnet/DataProtection#254_

**Comment by aspnet-hello** [comment]
_From @Vlaaaaaaad on Wednesday, December 6, 2017 11:41:12 PM_

Hi, is this still planned? Is there an ETA for it?

**Comment by aspnet-hello** [comment]
_From @natemcmaster on Thursday, December 7, 2017 8:33:05 AM_

It's not high on our priority list and we haven't assigned this a milestone yet. But I would welcome PRs to add functional tests and improve the quality of the extension.

**Comment by natemcmaster** [comment]
Done. See also https://github.com/aspnet/Home/issues/3379
