### ISSUE TITLE
[1.x] KeyRingProvider initialization causes thread pool starvation when server starts under load

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/Home#2510]
_From @natemcmaster on Friday, June 2, 2017 6:08:19 PM_

Consider back-porting https://github.com/aspnet/DataProtection/pull/241 to 1.x.

cref original issue #233 (fixed for 2.0)

_Copied from original issue: aspnet/DataProtection#242_

**Comment by aspnet-hello** [comment]
_From @brockallen on Friday, June 2, 2017 6:12:43 PM_

Sorry, repeating from the PR:

> Ok, thanks. One my my customers was on the original issue/thread here, and from their perspective data protection is in essence broken and unusable until this fix makes it into a release (as I'd imagine anyone else trying to use data protection, especially in azure). They aren't really in a position to move to 2.0 anytime soon.

**Comment by aspnet-hello** [comment]
_From @Tratcher on Friday, June 2, 2017 6:28:03 PM_

Looks like there's a trivial workaround, does it have any catches?

**Comment by aspnet-hello** [comment]
_From @brockallen on Friday, June 2, 2017 6:34:32 PM_

> Looks like there's a trivial workaround, does it have any catches?

Well, I can only say that my customer was close to dropping ASP.NET Core support (and going back to the ancient days of Katana even!) given that this felt like a critical issue "out of the box". Perhaps fixing perception is more important?

**Comment by blowdart** [comment]
@Eilon says back porting is not going to happen
