### ISSUE TITLE
 An exception was thrown while deserializing the token. 

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/Home#2513]
_From @Tratcher on Saturday, April 29, 2017 6:54:00 AM_

_From @1amirjalai on April 29, 2017 13:30_

 System.Security.Cryptography.CryptographicException: The key {xxxxxxxx} was not found in the key ring. 

Im running asp.net core on a webfarm using redis as dataprotection.
after getting error like this from redis
 Timeout performing EVAL, inst: 9, queue: 1448, qu: 0, qs: 1448, qc: 0, wr: 0, wq: 0, in: 65536, ar: 0, clientName: xxxx
 i opt in to make redis thread safe using this code 

```
   private static readonly Lazy<ConnectionMultiplexer> LazyConnection = new Lazy<ConnectionMultiplexer>(() =>
        {
        
           return ConnectionMultiplexer.Connect("xxxxxx,abortConnect=false,syncTimeout=3000");
        });

        public static ConnectionMultiplexer SafeCoonect
        {
            get
            {
                return LazyConnection.Value;
            }
        }
```
and initialize it in startup like : 

```
      var redis = RedisConnectionManager.SafeCoonect;
         
                services
            .AddDataProtection()
          .PersistKeysToRedis(redis, "Key");
```
but now i get new error 

The antiforgery token could not be decrypted. ---> System.Security.Cryptography.CryptographicException: The key {xxxxxxx} was not found in the key ring. 

I'm also getting this warning : 

>  Error unprotecting the session cookie.

what should i do?

_Copied from original issue: aspnet/IISIntegration#363_

_Copied from original issue: aspnet/DataProtection#228_

**Comment by aspnet-hello** [comment]
_From @1amirjalai on Saturday, April 29, 2017 7:21:51 PM_

i also have opened an issue on [stackoveflow here](http://stackoverflow.com/questions/43702297/asp-net-core-data-protection-an-exception-was-thrown-while-deserializing-the-t)

**Comment by aspnet-hello** [comment]
_From @blowdart on Monday, May 1, 2017 6:18:23 AM_

Have you set the application name to be static? 

       services.AddDataProtection()
           .SetApplicationName("my application")
           .PersistKeysToRedis(redis, "Key");

**Comment by aspnet-hello** [comment]
_From @1amirjalai on Monday, May 1, 2017 6:54:36 PM_

@blowdart  No i haven't set application name to be static.

**does setting application name to be static will affect my current users?**

i have more info on what's happened that cause this error. redis connection string has been changed accidentally for some minutes to another redis instance and again changed back to correct one.

here redis connection string was changed for some minutes under heavy website traffic
` return ConnectionMultiplexer.Connect("xxxxxx,abortConnect=false,syncTimeout=3000"); `

i need a way to handle and prevent this error.

i was thinking about  setting
` .SetDefaultKeyLifetime(TimeSpan.FromDays(1)); `
for one day and again set it back to 90 days after two or three days if that could help prevent the errors.

but i'm affraid that it causes more error under current situation

**Comment by aspnet-hello** [comment]
_From @1amirjalai on Monday, May 1, 2017 6:58:11 PM_

Here are a  list of errors and warnings that i'm getting constantly

`The antiforgery token could not be decrypted. ---> System.Security.Cryptography.CryptographicException: The key {xxxxxxx} was not found in the key ring.`
or
the most exception i get:
`An exception was thrown while deserializing the token.`
or
**which  i get the most warning is :**
`Error unprotecting the session cookie.`

**Comment by aspnet-hello** [comment]
_From @blowdart on Tuesday, May 2, 2017 10:42:22 AM_

You're going to find that 1 day is too little.

In your situation I'd start again. I'd set a static application name, because you do need that - keys are isolated by default based on app name. Redeploy and point everything to the same redis instance, and just take the hit of people being logged out. Remember unless you have redis configured for persistence the logout is going to happen whenever redis restarts too, because without persistence it'll throw the keys away.

**Comment by aspnet-hello** [comment]
_From @1amirjalai on Thursday, May 11, 2017 6:59:39 AM_

@blowdart after setting the name i have new errors

An exception was thrown while deserializing the token.

![antiforgery](https://cloud.githubusercontent.com/assets/2786675/25953337/461e8b1e-3678-11e7-812c-6ebfef41025a.PNG)

**Comment by aspnet-hello** [comment]
_From @blowdart on Thursday, May 11, 2017 7:19:38 AM_

Hmm. Is there a full stack trace anywhere, because that's not coming from data protection any more

**Comment by aspnet-hello** [comment]
_From @blowdart on Thursday, May 11, 2017 10:19:39 AM_

OK, throwing to a dev now to see if he can reproduce this. Hey @natemcmaster have a present :D

**Comment by aspnet-hello** [comment]
_From @1amirjalai on Sunday, May 14, 2017 7:31:20 AM_

@blowdart @natemcmaster 

Antiforgery is configured at startup  like :


can it be the reason of 
 **System.Security.Cryptography.CryptographicException: The payload was invalid**

any progress on the issue?

is there anything i can do to help this issue be solved?

```
   services.AddAntiforgery(
                options =>
                {
                    // Rename the Anti-Forgery cookie from "__RequestVerificationToken" to "f". This adds a little
                    // security through obscurity and also saves sending a few characters over the wire.
                    options.CookieName = "f";

                    // Rename the form input name from "__RequestVerificationToken" to "f" for the same reason above
                    // e.g. <input name="__RequestVerificationToken" type="hidden" value="..." />
                    options.FormFieldName = "f";

                    // Rename the Anti-Forgery HTTP header from RequestVerificationToken to X-XSRF-TOKEN. X-XSRF-TOKEN
                    // is not a standard but a common name given to this HTTP header popularized by Angular.
                    options.HeaderName = "X-XSRF-TOKEN";
                });
```

**Comment by aspnet-hello** [comment]
_From @1amirjalai on Monday, May 15, 2017 11:27:15 AM_

weirdest thing happened as soon as i changed configed antiforgery token to just

` services.AddAntiforgery()`

all errors went away.

there are just  **unprotecting the session cookie** warning that remained and no error

```
System.Security.Cryptography.CryptographicException: The payload was invalid. 
at Microsoft.AspNetCore.DataProtection.Cng.CbcAuthenticatedEncryptor.DecryptImpl(Byte* pbCiphertext, UInt32 cbCiphertext, Byte* pbAdditionalAuthenticatedData, UInt32 cbAdditionalAuthenticatedData) 
at Microsoft.AspNetCore.DataProtection.Cng.Internal.CngAuthenticatedEncryptorBase.Decrypt(ArraySegment1 ciphertext, ArraySegment1 additionalAuthenticatedData) 
at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status) 
at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.DangerousUnprotect(Byte[] protectedData, Boolean ignoreRevocationErrors, Boolean& requiresMigration, Boolean& wasRevoked) 
at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData) at Microsoft.AspNetCore.Session.CookieProtection.Unprotect(IDataProtector protector, String protectedText, ILogger logger)
```

**Comment by aspnet-hello** [comment]
_From @1amirjalai on Friday, August 11, 2017 2:30:27 AM_

The issue has come back once again after upgrading servers.
again i'm having a lot of
Error unprotecting the session cookie.

![image](https://user-images.githubusercontent.com/2786675/29207767-9a56b532-7e9c-11e7-8433-347da4821190.png)


`System.Security.Cryptography.CryptographicException: The key {xxxxx-xxxx-xxxxx-xxxxx-xxxxxx} was not found in the key ring. at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status) at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.DangerousUnprotect(Byte[] protectedData, Boolean ignoreRevocationErrors, Boolean& requiresMigration, Boolean& wasRevoked) at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData) at Microsoft.AspNetCore.Session.CookieProtection.Unprotect(IDataProtector protector, String protectedText, ILogger logger)
`


**is there any solution or workaround for this issue?**

i have changed antiforgery cookie name and also changed application cookie name but no success

```
services.AddAntiforgery(
                options =>
                {
            
                    options.CookieName = "n";
                }
                );
```
`    services.AddDataProtection().SetApplicationName("xxxx").PersistKeysToRedis(redis, "zzzz");`



```
   services.Configure<IdentityOptions>(options =>
            {
           
                options.Cookies.ApplicationCookie.CookieName = ".mmmm";
});
```

**Comment by aspnet-hello** [comment]
_From @nickalbrecht on Thursday, August 17, 2017 12:42:42 PM_

I ran into this today after publishing an update to a site running ASPNET Core 1.1 targeting .NET Framework 4.6.x. No redis involved. I get an error in my logs every 1-7 min, I'm assuming the interval is tied to user activity. None of the users have reported any problems using the app yet, though oddly enough, none of these error seem to be captured in Application Insights.

```
2017-08-17 13:27:08.800 -06:00 [Error] An exception was thrown while deserializing the token.
System.InvalidOperationException: The antiforgery token could not be decrypted. ---> System.Security.Cryptography.CryptographicException: The key {XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX} was not found in the key ring.
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.DangerousUnprotect(Byte[] protectedData, Boolean ignoreRevocationErrors, Boolean& requiresMigration, Boolean& wasRevoked)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
   at Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)
   at Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgery.GetCookieTokenDoesNotThrow(HttpContext httpContext)
```

I'm just using very basic Cookie Authentication

```
//ConfigureServices()
services.AddAuthentication(options=>
{
    options.SignInScheme = "MyAppCookie";
});
```

```
//Configure()
app.UseCookieAuthentication(new CookieAuthenticationOptions()
{
    CookieName = "MyApp", //Default is ".AspNetCore.Cookie"
    AuthenticationScheme = "MyAppCookie",
    LoginPath = new PathString("/Login/"),
    LogoutPath = new PathString("/Logout/"),
    AccessDeniedPath = new PathString("/Forbidden/"),
    AutomaticAuthenticate = true,
    AutomaticChallenge = true,
    SlidingExpiration = true,
    ExpireTimeSpan = TimeSpan.FromMinutes(30),
    Events = new CookieAuthenticationEvents()
    {
        OnValidatePrincipal = LoginStatusValidator.ValidateAsync //Just some code to allow deactivated accounts to cause active cookies to be revoked/signed-out
    }
});
```

**Comment by aspnet-hello** [comment]
_From @eriksendc on Friday, December 8, 2017 12:50:53 PM_

Hi @Tratcher , 

For a while now (most of this year) we've been seeing the following in our logs.

NLog logs:
```
2017-12-08 05:11:55.8053|ERROR|Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgery|An exception was thrown while deserializing the token.
```
stdout logs:
```
fail: Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgery[7]
      An exception was thrown while deserializing the token.
System.InvalidOperationException: The antiforgery token could not be decrypted. ---> System.Security.Cryptography.CryptographicException: The payload was invalid.
   at Microsoft.AspNetCore.DataProtection.Cng.CbcAuthenticatedEncryptor.DecryptImpl(Byte* pbCiphertext, UInt32 cbCiphertext, Byte* pbAdditionalAuthenticatedData, UInt32 cbAdditionalAuthenticatedData)
   at Microsoft.AspNetCore.DataProtection.Cng.Internal.CngAuthenticatedEncryptorBase.Decrypt(ArraySegment`1 ciphertext, ArraySegment`1 additionalAuthenticatedData)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.DangerousUnprotect(Byte[] protectedData, Boolean ignoreRevocationErrors, Boolean& requiresMigration, Boolean& wasRevoked)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
   at Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)
   at Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgery.GetCookieTokenDoesNotThrow(HttpContext httpContext)
```
I believe these are related, but I never know because the stdout logs don't have a timestamp. Anyways, we get anywhere between 200 and 400 of these a day. getyourpet.com has about 7000-8000 sessions a day (Google Analytics sessions). We haven't received any support requests that seem to tie to not being able to submit a particular form.

We've been wondering if these are related to some kind of authentication time out (like if people have stale browsers and then click on something) or if there are specific forms on our site that have issues. We know that we have _way_ more total form posts than the 200-400 errors observed per day.

Any suggestion on how to get started digging in to this? If this is sort of a normal thing, then I'll continue to ignore them.

Thanks in advance for any pointers. I put this here because I Googled around a lot and this seemed to be the closest matching issue. Let me know if I should open a different issue.

Thanks,
-Brian Eriksen

**Comment by aspnet-hello** [comment]
_From @Tratcher on Friday, December 8, 2017 1:37:37 PM_

The encryption is based solely on server state, there's no user login involved. If the tokens can't be decrypted then either one of two things is happening:
1) Your encryption keys aren't being persisted across app restarts and the client is sending you a token from the prior instance of your app. You should get warnings about this in your logs when the application starts.
2) You have your app running on two or more nodes that aren't sharing the same encryption keys. See https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/configuration/overview?tabs=aspnetcore2x for configuring multiple nodes.

**Comment by aspnet-hello** [comment]
_From @eriksendc on Saturday, December 9, 2017 7:15:32 AM_

Hi @Tratcher ,

As always, thanks for your quick response! 

Re 1, we ran the powershell script as per https://docs.microsoft.com/en-us/aspnet/core/publishing/iis?tabs=aspnetcore2x#data-protection

Re 2, we are only running on a single web server (but some day we will run on multiple servers, so thanks for that link).

I guess it's zebras not horses. What's the next thing to try?

Again, thanks so much in advance!!

-Brian

**Comment by aspnet-hello** [comment]
_From @Tratcher on Monday, December 11, 2017 9:35:18 AM_

If you have a repro you can set your log level to Trace to get more information about what DataProtection thinks is wrong. You should be able to create a repro by capturing the headers from a failing request.

**Comment by aspnet-hello** [comment]
_From @GrabYourPitchforks on Monday, December 11, 2017 11:59:33 AM_

BTW, it's completely fine for you to disclose the GUID that's in the error message "The key {xxxxx-xxxx-xxxxx-xxxxx-xxxxxx} was not found in the key ring." That GUID is the key _identifier_, not the actual key itself. Do one or two GUIDs keep popping up over and over in these error messages? If so, and if you recently changed your crypto system config (e.g., by switching to a new key repository), then this suggests that the clients are sending old cookies, and those cookies should be automatically replaced on next login. If you're seeing a lot of different GUIDs in these error messages, this suggests a misconfiguration, as it's possible that your server's key repository keeps getting cleared somehow. (Perhaps the directory the server is trying to use isn't stable?)

**Comment by blowdart** [comment]
We're closing this issue as no response or updates have been provided in a timely manner. If you have more details and are encountering this issue please add a new reply and re-open the issue.

**Comment by neman** [comment]
I got the same issue with simple Asp.Net Core app, which is published out in the wild.
Almost all logs contains the following error. Nothing fancy in  `Startup.cs`
Target framework is net461
AspNetCore 2.0.1
```
System.InvalidOperationException: The antiforgery token could not be decrypted. ---> System.Security.Cryptography.CryptographicException: The key {e8e2d081-0630-4bbc-9829-595567fc9d92} was not found in the key ring.
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.DangerousUnprotect(Byte[] protectedData, Boolean ignoreRevocationErrors, Boolean& requiresMigration, Boolean& wasRevoked)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
   at Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)
   at Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgery.GetCookieTokenDoesNotThrow(HttpContext httpContext)
```
