### ISSUE TITLE
[Question] Why is Protect(string) and Unprotect(string) not part of IDataProtector?

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/Home#2518]
_From @Legogris on Friday, February 17, 2017 1:01:04 AM_

When writing unit tests, it helps a lot being able to mock the results of these functions depending on the input.

Right now it is a big hassle doing this since we have to mock the byte-array versions and then mimic the internal implementations of the extension methods in `DataProtectionCommonExtensions`. I can't even get it to work properly for a particular use case. It would be very beneficial to have the directly on the interface.

_Copied from original issue: aspnet/DataProtection#202_

**Comment by aspnet-hello** [comment]
_From @blowdart on Friday, April 28, 2017 12:53:01 PM_

What are you unit testing here? Your own data protection implementation?

**Comment by blowdart** [comment]
Closing due to lack of response.

Please reopen if you have further comments or questions on this issue.
