### ISSUE TITLE
Is there a way to dynamicaly load dependencies?(For plugin system)

### ISSUE THREAD

**Issue by aanufriyev** [aspnet/Home#252]
Cant find a way to load dependency after project is compiled to binaries. Is it possible on CoreClr? Or any plans to support some kind of dynamic plugin systems?

**Comment by runxc1** [comment]
With things like the Managed Extensibility Framework you should be able to create a dynamic plugin system already.

**Comment by aanufriyev** [comment]
Im talking about something like scanning folders and loading assemblies with Assembly.Load, which is not available when I target CoreClr. So I assume there will be some hooks or api for loading dependencies from other folders and locations from code. 

Btw is MEF ported to CoreClr?

**Comment by devmondo** [comment]
@aanufriyev  i suggest checking Autofac, it does what you need and have support in VNext

**Comment by aanufriyev** [comment]
@devmondo CoreClr or Clr support? If I use full Clr I have no problems, because there is Assembly.Load. Question was about CoreClr. I have seen some stuff in DependencyLoadingContext but it was changed recently and dunno whre it is going to.

**Comment by devmondo** [comment]
@aanufriyev i  you maybe right about coreclr but i read this article 
http://blogs.msdn.com/b/webdev/archive/2014/06/17/dependency-injection-in-asp-net-vnext.aspx

and it seams the solution works for both full and core by using #if statement in the code.

**Comment by aanufriyev** [comment]
@devmondo this article states that Autofac is not available for core dotnet) Code dependencies are not a problem. I can't find a way to load k dependencies. 
For example: 
Pluggable ICacheProvider. I have default in memory implementation. Someone wants to use Memcached, so he creates package with some libraries and dependencies, puts it in Plugins folder and... How can I load it from my code on demand?

**Comment by devmondo** [comment]
@aanufriyev maybe you are right, but this article is old, and there has been many changes to VNext dependency of injection, and there will be more i think, so i suggest you upgrade latest Packages and KRE and try the example above, it may work.

and i have same case as yours, and as i mentioned before AutoFac and many other IOC do that easily for you just check their docs.

last let us not forget that VNext is still way early, so you would see many changes, and you always have to upgrade and test and fix things, that is the price of working with Beta stuff :)

**Comment by aanufriyev** [comment]
@devmondo IoC containers generally are not responsible for loading assemblies into appdomain. Autofac can scan assembly for registrations AFAIK, but not load it from file system or database. 

Latest dev builds suggest that it is going to rc in foreseeable future. I is interesting at least to hear dev ideas on these, because in CoreClr I cant reference assembly. Only packaged dependencies are allowed.

**Comment by devmondo** [comment]
@aanufriyev  you are absolutely right, that is MEF fraemwork job.

about CoreCLR, i have been to frustrated with it, because thee whole point of it is to be able to run your app cross platform, yet the .NET packages them selves are not all compatible with it

**Comment by aanufriyev** [comment]
@devmondo I have found a way to load dependencies. Here is a project: https://github.com/OrchardCMS/Brochard
Dynamic compilation is broken, but main idea should be working. Look at DefaultExtensionLoader.Load methods.

**Comment by devmondo** [comment]
@aanufriyev  awesome man, thanks for the hint :+1:
