### ISSUE TITLE
Asp.Net MVC Core: “Error unprotecting the session cookie” exception

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/Home#2520]
_From @skorunka on Tuesday, November 29, 2016 6:02:13 AM_

I have an Asp.NET MVC application with this Authentication setup:

ConfigureServices():

    services.AddSession()
    services.AddAuthentication(sharedOptions => sharedOptions.SignInScheme = CookieAuthenticationDefaults.AuthenticationScheme);

Configure():

			app.UseCookieAuthentication(new CookieAuthenticationOptions());
			app.UseOpenIdConnectAuthentication(new OpenIdConnectOptions
			{
				ClientId = "xx",
				Authority = "xx",
				Events = new OpenIdConnectEvents { OnRemoteFailure = this.OnAuthenticationFailed }
			});

			app.UseSession();

When hosted in IIS, some users get this exception:

    Microsoft.AspNetCore.Session.SessionMiddleware, 
          Error unprotecting the session cookie.
    System.Security.Cryptography.CryptographicException: The key {9ec59def-874e-45df-9bac-d629f5716a04} was not found in the key ring.
       at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
       at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.DangerousUnprotect(Byte[] protectedData, Boolean ignoreRevocationErrors, Boolean& requiresMigration, Boolean& wasRevoked)
       at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
       at Microsoft.AspNetCore.Session.CookieProtection.Unprotect(IDataProtector protector, String protectedText, ILogger logger)

I have run this on the hosting server https://github.com/aspnet/DataProtection/blob/dev/Provision-AutoGenKeys.ps1

Web has only HTTPS binding, SSL certificate is ok and signed. What might cause this issue? What actually is that "key" value?

_Copied from original issue: aspnet/DataProtection#189_

**Comment by aspnet-hello** [comment]
_From @skorunka on Thursday, December 1, 2016 1:51:57 AM_

I can also see a lot of these:
11/30/2016 18:10:28:warn: Microsoft.AspNetCore.Session.DistributedSession[2]
      Accessing expired session, Key:21d8f9ed-4013-2e65-d884-651a6f0060a0

**Comment by aspnet-hello** [comment]
_From @kalluri-nb on Wednesday, December 14, 2016 7:22:31 PM_

Any update on this. This is happening in cluster a lot. A session cookie value created on one instance is unable able to be unprotected by a different instance. Is there any basic setup for DataProtectionOptions for session management in cluster.

**Comment by aspnet-hello** [comment]
_From @skorunka on Saturday, December 17, 2016 5:32:11 AM_

The machine is not in a cluster or farm. Each requested is server by the same machine, by the same IIS site.

**Comment by aspnet-hello** [comment]
_From @kalluri-nb on Saturday, December 17, 2016 3:00:44 PM_

We resolved it by adding the redis as persistence store using DataProtectionBuilder.

**Comment by aspnet-hello** [comment]
_From @skorunka on Sunday, December 18, 2016 3:54:36 AM_

@kalluri-nb Nice, how can I resolve it? What should I change in the Setup.cs?

**Comment by aspnet-hello** [comment]
_From @warrenfp on Tuesday, April 25, 2017 5:07:06 AM_

@kalluri-nb: Can you share your implementation?

**Comment by aspnet-hello** [comment]
_From @blowdart on Friday, April 28, 2017 12:36:41 PM_

@skorunka Where are your keys being persisted? This is strange, it looks like the keyring can't get created at all. Have you tried, as a stop gap, persisting the keyring to the file system anywhere?

**Comment by aspnet-hello** [comment]
_From @skorunka on Tuesday, May 2, 2017 1:34:17 AM_

@blowdart Hi, I'm using defaults. How can I setup where the keys are persisted? Or how can I know where they are actually persisted?

**Comment by aspnet-hello** [comment]
_From @blowdart on Tuesday, May 2, 2017 10:43:04 AM_

It tries to figure out the right place depending on machine configuration. The log files will tell you, if you're logging at informational.

**Comment by aspnet-hello** [comment]
_From @1amirjalai on Thursday, May 11, 2017 10:12:58 AM_

@kalluri-nb what do you mean by 

> We resolved it by adding the redis as persistence store using DataProtectionBuilder.

could you please show an example?

**Comment by aspnet-hello** [comment]
_From @1amirjalai on Thursday, May 11, 2017 10:16:37 AM_

@blowdart may this issue an issue #228 are related

**Comment by blowdart** [comment]
Closing due to lack of response.

Please reopen if you have further comments or questions on this issue.

**Comment by verydarkmagic** [comment]
This error started happening to me as well after my app was deployed in a docker container.
Running from VisualStudio17 was fine but my container is throwing these errors:


```
System.Security.Cryptography.CryptographicException: The key {416a607b-290f-44ef-83b3-2a9914859fb4} was not found in the key ring.
--
  | at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
  | at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.DangerousUnprotect(Byte[] protectedData, Boolean ignoreRevocationErrors, Boolean& requiresMigration, Boolean& wasRevoked)
  | at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
  | at Microsoft.AspNetCore.Session.CookieProtection.Unprotect(IDataProtector protector, String protectedText, ILogger logger)
  | warn: Microsoft.AspNetCore.Session.SessionMiddleware[7]
  | Error unprotecting the session cookie.
```



Startup.cs
```
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddMvc();
            services.AddMemoryCache();
            services.AddSession();
            services.AddTransient(provider => new RestClient(AppConfig.ApiGatewayUrl));
        }
        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            app.UseDefaultFiles();
            app.UseStaticFiles();
            app.UseSession();
            app.UseMvc(routes =>
            {
                routes.MapRoute(
                    name: "default",
                    template: "{controller=Home}/{action=Index}/{id?}");
            });
        }
```

**Comment by fashaikh** [comment]
+1 I see it too in random AppInisight traces. The app is similar to the one above, uses Session variables (no authentication though) and runs on mulitple VMs in Azure App Service.  Seems like some configuration needs to be fixed ? 

```

System.Security.Cryptography.CryptographicException: The key {09794bfd-5325-487e-a7b0-3cc6c51fd40b} was not found in the key ring.  at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)  at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.DangerousUnprotect(Byte[] protectedData, Boolean ignoreRevocationErrors, Boolean& requiresMigration, Boolean& wasRevoked)  at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)  at Microsoft.AspNetCore.Session.CookieProtection.Unprotect(IDataProtector protector, String protectedText, ILogger logger) |  
-- | --



```

**Comment by Tratcher** [comment]
Your nodes need to share the same data protection settings. See https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/configuration/overview?tabs=aspnetcore2x

**Comment by fashaikh** [comment]
Thanks. Will try out the changes

**Comment by verydarkmagic** [comment]
I only have one node and still get this error

**Comment by mfronczyk** [comment]
We also see exceptions like this in Application Insights. I'm not able to replicate the issue, but we see it happening in the logs. We only have 1 instance and we use in memory sessions. Might it be because we swap staging with prod during releasing? Would moving session data out of the web process help? (Redis for example)

System.Security.Cryptography.CryptographicException: The key {e02033c0-d797-47ae-b6e6-958e54a5bb10} was not found in the key ring.
 at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
 at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.DangerousUnprotect(Byte[] protectedData, Boolean ignoreRevocationErrors, Boolean& requiresMigration, Boolean& wasRevoked)
 at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
 at Microsoft.AspNetCore.Session.CookieProtection.Unprotect(IDataProtector protector, String protectedText, ILogger logger)

**Comment by blowdart** [comment]
Well it can still indicate a problem, like an attacker trying to highjack a session, so it's not unreasonable for it to get logged.

**Comment by mfronczyk** [comment]
Yes, but we can't do much about it and it generates noise. Logging as a warning is fine, but I think that Application Insights shouldn't treat it as an exception.

Just wondering, is that warning reported when the user tries to make a request with a stale session id? For example, session expiration is 2h, but the user makes another request after 3h of inactivity, but without closing the browser? Such cases shouldn't be reported at all I think.

**Comment by Tratcher** [comment]
@mfronczyk A) we don't track closed issues, please open a new issue.
B) This error is not caused by session storage or expiration issues, it's caused by Data Protection mis-configuration or cross site cookie contamination. E.g. If your staging and production sites do not share encryption keys, or if you encryption keys aren't being persisted across application restarts / redeploys.

**Comment by kusey** [comment]
@verydarkmagic Hi, I meet the same error when I deployed my application in a linux docker container, do you have any workaround on this issue?

**Comment by jrad87** [comment]
@kusey @verydarkmagic 
I haven't had this problem in a container, but FWIW when this error popped up running on localhost, my startup.cs looked very similar to what @verydarkmagic posted, particularly this method 

>public void ConfigureServices(IServiceCollection services) {
            services.AddMvc();
            services.AddMemoryCache();
            services.AddSession();
            services.AddTransient(provider => new RestClient(AppConfig.ApiGatewayUrl));
        }

However I looked in some other projects that I did have working and found that .NET Core MVC template provides options for services.AddSession like so: 

> services.AddSession(options =>
            {
                // Set a short timeout for easy testing.
                options.IdleTimeout = TimeSpan.FromHours(1);
                options.Cookie.HttpOnly = true;
                // Make the session cookie essential
                options.Cookie.IsEssential = true;
            });

These specific options may not fix your problem but there may be some explicit configuring you can do there that works

**Comment by ysris** [comment]
I fixed these exceptions by following the @jrad87 advice. Thanks !

**Comment by vitali-karmanov** [comment]
If you are using a SSL add options.Cookie.SecurePolicy = CookieSecurePolicy.Always; to the Session options.
