### ISSUE TITLE
SALT Generation

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/Home#2527]
_From @alexjusti on Thursday, July 2, 2015 11:59:45 AM_

The KeyDerivation takes a byte[] salt, but as of now I don't believe that there is a public method to generate a secure SALT value.  Am I missing something, or is this yet to be implemented?

_Copied from original issue: aspnet/DataProtection#88_

**Comment by aspnet-hello** [comment]
_From @blowdart on Thursday, July 2, 2015 12:03:09 PM_

You're not missing anything, it's up to you to provide it, because you need to store it somewhere anyway.

**Comment by aspnet-hello** [comment]
_From @GrabYourPitchforks on Saturday, July 4, 2015 11:48:48 AM_

The easiest way to generate a salt is to use the RandomNumberGenerator class. Is the proposal for the KeyDerivation package to add a simple wrapper API that calls this on your behalf and returns a byte[]?

**Comment by aspnet-hello** [comment]
_From @alexjusti on Saturday, July 4, 2015 9:33:11 PM_

Yes, that's what I'm looking for.

**Comment by aspnet-hello** [comment]
_From @blowdart on Tuesday, July 7, 2015 9:17:16 AM_

How would you expect the salt to be returned to you? Hidden in the byte array? (At which point we're no longer following the public PBKDF2 spec)

**Comment by aspnet-hello** [comment]
_From @GrabYourPitchforks on Tuesday, July 7, 2015 9:28:27 AM_

I interpreted this request as a separate API that just returns a random byte[], and that byte[] can then be fed in as the salt parameter to the PBKDF2 operation.

**Comment by aspnet-hello** [comment]
_From @blowdart on Tuesday, July 7, 2015 10:30:43 AM_

@mw2nukeboy is a function to return a suitable salt what you want, or a way to just not pass one in at all?

**Comment by blowdart** [comment]
Closing due to lack of response.

Please reopen if you have further comments or questions on this issue.
