### ISSUE TITLE
Compiler warning (level 2) CS0108 in HelloMVC based projects

### ISSUE THREAD

**Issue by peterblazejewicz** [aspnet/Home#253]
Running `kpm build` in `HelloMvc` based projects results in the following warning:
```
/Users/piotrblazejewicz/projects/RetrogamesWeb/Controllers/HomeController.cs(13,21):
warning   CS0108: 'HomeController.User()' hides inherited member 'Controller.User'. 
Use the new keyword if hiding was intended.
[...]
Build succeeded.
    1 Warnings(s)
    0 Error(s)
```
The culprit line:
https://github.com/aspnet/Home/blob/master/samples/HelloMvc/Controllers/HomeController.cs#L13

I think it would be better to refactor this particular method to use other established C# convention removing that error along the lines:
https://github.com/aspnet/Mvc/blob/dev/samples/MvcSample.Web/HomeController.cs#L129-L150
that is:

```
public IActionResult Index()
{
    return View(CreateUser());
}

public User CreateUser()
{
    User user = new User()
    {
        Name = "My name",
        Address = "My address"
    };

    return user;
}
```

**Comment by Praburaj** [comment]
Fixed
