### ISSUE TITLE
CompositeFileProvider should implement IDisposable

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/Home#2532]
_From @jiatao99 on Wednesday, December 13, 2017 8:20:12 AM_

1. I implement my own IFileProvider (like Zip)  and implement IDisposable
2. I add my provider into CompositeFileProvider
3. I add CompositeFileProvider into ServiceCollection 

Result:  my provider will not be disposed properly

CompositeFileProvider should implement IDisposable and dispose inner providers.

_Copied from original issue: aspnet/FileSystem#307_

**Comment by muratg** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.
