### ISSUE TITLE
PhysicalDirectoryInfo.PhysicalPath should return relative path

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/Home#2533]
_From @jiatao99 on Wednesday, December 13, 2017 7:55:14 AM_

Call provider.GetDirectoryContents("") might return a PhysicalDirectoryInfo. From there, I should be able to call the provider.GetDirectoryContents(dir.PhysicalPath) to retrieve the directory content from sub folder. However, the PhysicalDirectoryInfo.PhysicalPath returns the absolute path.

Since PhysicalFileProvider only take relative path, I have no easy way to recursively list all the directory contents in the file system. 

In my opinion, both PhysicalDirectoryInfo and PhysicalFileInfo should always return relative path (to provider) to follow the design pattern

_Copied from original issue: aspnet/FileSystem#306_

**Comment by muratg** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.
