### ISSUE TITLE
Can we defer creation of the PhysicalFileWatcher in PhysicalFileProvider

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/Home#2552]
_From @rynowak on Wednesday, August 3, 2016 3:10:32 PM_

`PhysicalFileProvider` always creates a file watcher when it's created. I'm wondering if we need this or if we could just defer the work until it's needed.

This happens on the hosting startup path so it's critical path for startup. I don't have any evidence yet that it's a significant perf factor, it just seems like work we could avoid.

_Copied from original issue: aspnet/FileSystem#223_

**Comment by aspnet-hello** [comment]
_From @muratg on Friday, September 23, 2016 10:36:13 AM_

@rynowak did you end up having any measurements for this code path?

**Comment by aspnet-hello** [comment]
_From @rynowak on Friday, September 23, 2016 3:31:56 PM_

no update on this from me, I haven't looked at it again

**Comment by aspnet-hello** [comment]
_From @pranavkm on Friday, September 23, 2016 3:47:59 PM_

Not entirely relevant since this was done in a non-hosted application, but here's a profile from when I was working on MvcPrecompilation:

![image](https://cloud.githubusercontent.com/assets/174281/18803422/bc513590-81a4-11e6-9be3-ad8edc9bd8ba.png)

That said, it should be a pretty small change to make the instantiation deferred.

**Comment by aspnet-hello** [comment]
_From @muratg on Monday, September 26, 2016 8:48:53 AM_

Impact seems to be low enough. Even if the change is small, it would still be churn with potential issues we haven't thought of. 

Backlogging for now, but let me know if you guys feel like this is important enough and we should bring it back in 1.2.

**Comment by aspnet-hello** [comment]
_From @dazinator on Wednesday, June 28, 2017 11:32:51 AM_

@muratg2 - here is seemingly a knock on effect of this issue - please see #282

**Comment by muratg** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.
