### ISSUE TITLE
Consider adding tags on the healthcheck

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/Home#2575]
_From @ycrumeyrolle on Friday, October 27, 2017 2:26:30 PM_

Every healthchecks may be related to different components or features of the application. 
For example we could have tags like "database", "certificate", "critical", "authentication", "payment", ...

Tagging the healthcheck allow to request a subset of the configured healthchecks : 
/health expose all the health check results
/health/critical expose only the critical healthchecks
/health/authentication expose only the authentication related healthchecks
...

_Copied from original issue: aspnet/Diagnostics#420_

**Comment by rynowak** [comment]
We did this. It will be in 2.2.0-preview3
