### ISSUE TITLE
Consider adding performance timing on healtcheck

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/Home#2576]
_From @ycrumeyrolle on Friday, October 27, 2017 2:16:22 PM_

On our applications monitoring console, we are tracking the performance of each component of the applications. We are analysing the variation of the response time. Unexpected increasing or decreasing response time may underlie an problem before a failure could occur. 

The healthcheck may include the elapsed time as a result.

_Copied from original issue: aspnet/Diagnostics#419_

**Comment by mkArtakMSFT** [comment]
Resolved as part of https://github.com/aspnet/Diagnostics/issues/491
