### ISSUE TITLE
Add support for binding HealthChecks middleware to a port

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/Home#2579]
_From @anurse on Thursday, October 12, 2017 7:46:43 PM_

This is useful for ensuring that the health checks are only visible to infrastructure components and not available on the public internet. Using a different port for health checks makes that easier to configure.

_Copied from original issue: aspnet/Diagnostics#414_

**Comment by aspnet-hello** [comment]
_From @Tratcher on Thursday, October 12, 2017 8:31:13 PM_

This won't work for ANCM scenarios, right?

**Comment by aspnet-hello** [comment]
_From @anurse on Thursday, October 12, 2017 9:12:14 PM_

Correct. But it's implementation is simply to have the middleware able to be conditional on a port number. It's still up to the user to configure the endpoint binding in the server.

**Comment by aspnet-hello** [comment]
_From @Tratcher on Thursday, October 12, 2017 10:31:30 PM_

This seems like a very specific subset of the more general "Should I run health checks?" / Auth. The more general version is likely a service where port checking is a specific implementation.

**Comment by aspnet-hello** [comment]
_From @anurse on Friday, October 13, 2017 8:49:22 AM_

A service used by a Middleware to determine if it should run? Seems a little overkill. Maybe if we end up with a service driving the whole middleware behavior, but I'm not yet convinced that it's worth it yet.

**Comment by aspnet-hello** [comment]
_From @Tratcher on Friday, October 13, 2017 8:55:31 AM_

Auth / policy is too varied to build directly into the middleware, it should be abstracted because dev's needs and preferences on this will vary greatly. Some examples:
- local IP or port checks
- remote IP checks
- Specific header / query token
- Actual auth via basic / cookies / windows / etc..

**Comment by aspnet-hello** [comment]
_From @anurse on Friday, October 13, 2017 8:59:20 AM_

It should definitely be abstracted, I'm not sure that we want to establish a whole new service for it rather than just options/events.

**Comment by rynowak** [comment]
This was done for preview1. `UseHealthChecks` accepts a port. See samples in the aspnet/Diagnostics repo
