### ISSUE TITLE
Update wiki with case sensitive Nuget path and filename

### ISSUE THREAD

**Issue by ryan1234** [aspnet/Home#258]
On https://github.com/aspnet/Home/wiki/Configuring-the-feed-used-by-kpm-to-restore-packages at the bottom ... under the "Updating feed on *Nix machines" section ...

The ~/.config/Nuget/Nuget.config path and filename are actually case sensitive. 

It should be ~/.config/NuGet/NuGet.Config. 

The three capital letters made the difference for me between restoring packages and not.

**Comment by davidfowl** [comment]
Fixed

**Comment by ryan1234** [comment]
I know it seems silly, but Config is capitalized too. =(
