### ISSUE TITLE
Reconsider approach for running Health Checks while they are already running

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/Home#2580]
_From @anurse on Wednesday, October 11, 2017 10:38:06 AM_

Right now, if someone calls `IHealthCheckService.CheckHealthAsync` while `CheckHealthAsync` is already running, nothing will be done to control or check that situation. The method is thread-safe due to it's use of a read-only dictionary ("A Dictionary<TKey, TValue> can support multiple readers concurrently, as long as the collection is not modified." [Source](https://msdn.microsoft.com/en-us/library/xfhwa508(v=vs.110).aspx)). However, generally only one caller should be doing health checks at a time. We could do some tricks like bind the second call to return the same results as the first call, or we could block the second call until the first call completes. Alternatively, we could just leave the behavior as-is.

_Copied from original issue: aspnet/Diagnostics#413_

**Comment by aspnet-hello** [comment]
_From @Drawaes on Thursday, October 12, 2017 5:56:44 PM_

Careful on this one, you can have unintended consequences. Lets say a healthcheck stalls for whatever reason.

You block subsequent calls that would have passed through quickly (say the first one checked the DB connection and it got stuck for whatever reason). 

Now all subsequent checks are failing because of the first check, but also you have health checks banking up. 

Now you have 2 problems, the server is "offline" due to the rapid health checks that are failing, and you have a convoy of healthchecks... yuck

Now I am not saying that the idea is a busted flush, it just needs careful consideration. The worst situation you can get into with healthchecks.... the checks takeout healthy systems.... :(

**Comment by aspnet-hello** [comment]
_From @anurse on Thursday, October 12, 2017 7:50:58 PM_

You've hit on exactly the reasons why I didn't do anything special here in the first pass :). I'm hesitant to do anything here to be honest. I expect we'd most likely do this kind of thing in the middleware, by having the middleware configured with a configurable timeout after which it will consider the health check `Failed`. In most systems, the health check can be given a timeout value with confidence because if the check is taking longer than the timeout, then it follows that the system is unhealthy.

**Comment by aspnet-hello** [comment]
_From @Drawaes on Thursday, October 12, 2017 7:56:57 PM_

And health checks can be often run by multiple systems, say Consul and a BigIP F5 at the same time for some services... blocking one because of the other is bad news :) this is a mine field that I would let applications try to sort of themselves if they have a need...:)

**Comment by rynowak** [comment]
Closing this since it just generally doesn't seem like a good idea. Generally when a system is health checking, they want fresh data. If your health checks take a significant amount of time then you already have a problem.
