### ISSUE TITLE
HealthChecks middleware should be configurable as to when the details are shown

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/Home#2583]
_From @anurse on Tuesday, October 10, 2017 4:16:24 PM_

* May have sensitive info and want to expose the non-sensitive (Up, Down) status to a public endpoint, so authorization might be needed around the details
* May want to only expose data if the status is Unhealthy, since systems like consul don't like Healthy health checks returning different data.

/cc @Drawaes 

_Copied from original issue: aspnet/Diagnostics#410_

**Comment by aspnet-hello** [comment]
_From @Drawaes on Tuesday, October 10, 2017 4:39:24 PM_

FYI the effect of changing the content while healthy. Every agent will be updated with every check. 100's of services × 1 second health check ends up with a lot of gossip.

**Comment by aspnet-hello** [comment]
_From @anurse on Tuesday, October 10, 2017 4:46:30 PM_

Yep. Pretty much as soon as @glennc came out from talking with you he was like "Hey, make sure our Health Checks can support disabling detailed status when healthy so we don't overload Tim's consul nodes" ;)

**Comment by aspnet-hello** [comment]
_From @Drawaes on Wednesday, October 11, 2017 10:06:34 AM_

The auth is an interesting issue. It's often difficult or impossible for many tools to have any auth at all. In this case I usually see people say limit the health check to loopback....

**Comment by aspnet-hello** [comment]
_From @Tratcher on Wednesday, October 11, 2017 10:20:23 AM_

Note the Security (Auth) repo depends on Diagnostics, but only for samples and tests. There would need to be some restructuring to avoid a repo circular dependency.

**Comment by aspnet-hello** [comment]
_From @anurse on Wednesday, October 11, 2017 10:32:37 AM_

@Drawaes Yeah, but we've also seen systems where they do use auth to protect health check details, so making it possible to plug that in is useful. Spring, for example, does that.

@Tratcher Which means we may not actually provide an Auth check, we may just provide an event to hook in to and people can use auth if they want.

**Comment by aspnet-hello** [comment]
_From @Drawaes on Wednesday, October 11, 2017 10:36:10 AM_

I think every time you mention spring in a conversation I am having I will make a note  that you owe me a beer if we ever meet

**Comment by aspnet-hello** [comment]
_From @anurse on Wednesday, October 11, 2017 10:44:51 AM_

Spring is one of the many platforms we compare with. It doesn't mean we have to emulate everything :). Like I said, we just want to provide options.

**Comment by aspnet-hello** [comment]
_From @anurse on Wednesday, October 11, 2017 10:45:21 AM_

And I'd already buy you a beer for helping us out with Health Check scenarios anyway ;P

**Comment by aspnet-hello** [comment]
_From @Drawaes on Wednesday, October 11, 2017 10:45:42 AM_

That's another beer... this game is easy.

**Comment by aspnet-hello** [comment]
_From @Drawaes on Thursday, October 12, 2017 5:51:40 PM_

I can't remember if I raised the point. But often health check "auth" is done via ip address or interface. Eg if I run a webserver that faces the internet, then I might only allow a healthcheck from say the local consul agent and with no auth. But if an internet user tries to hit the address they will get a 404.

**Comment by aspnet-hello** [comment]
_From @anurse on Thursday, October 12, 2017 7:46:50 PM_

Yep, the original sample also included a way to attach the middleware only to requests to a specific port. The idea being that you only expose the health checks on a port that only the monitoring logic (Consul, Kube, Docker) can access and isn't exposed to the internet. We'd probably want something like that here as well. https://github.com/aspnet/Diagnostics/issues/414

**Comment by aspnet-hello** [comment]
_From @Drawaes on Thursday, October 12, 2017 7:58:11 PM_

I feel we are agreeing too much and instead should be arguing and making disparaging comments....

**Comment by rynowak** [comment]
The health checks middleware will output something really simple as `text/plain` by default. This is fully customizable.
