### ISSUE TITLE
Reconsider Status Codes for HealthChecks middleware

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/Home#2584]
_From @anurse on Tuesday, October 10, 2017 4:14:41 PM_

@Drawaes suggested using 429 instead of 503 for our `Unhealthy` status in the health checks middleware. At the very least, we should consider making it configurable. I've seen systems that use 503, but consul uses 429 (and they are a major use-case for this component).

We should re-examine this before release.

_Copied from original issue: aspnet/Diagnostics#409_

**Comment by aspnet-hello** [comment]
_From @Tratcher on Tuesday, October 10, 2017 4:20:41 PM_

`429 Too Many Requests`? That's an odd choice. That implies a client problem rather than a server failure.

**Comment by aspnet-hello** [comment]
_From @anurse on Tuesday, October 10, 2017 4:25:20 PM_

To clarify, Consul uses that for a "degraded" status, so it would map to our `Degraded` status code. I misinterpreted @Drawaes a little.

@Tratcher Consul expects this status code to be used to indicate `Degraded` status (i.e. not unhealthy but in a bad way): https://www.consul.io/docs/agent/checks.html

**Comment by aspnet-hello** [comment]
_From @Drawaes on Tuesday, October 10, 2017 4:33:20 PM_

So in a real world large use, we say hit "Healthly" instances, and will only hit the "degraded" instances if there are no healthly left, it gives you basic adaptive load balancing.

**Comment by aspnet-hello** [comment]
_From @Tratcher on Wednesday, October 11, 2017 8:52:30 AM_

My point stands, 429 puts the blame on the client. That said I don't see any defined 5xx codes for degraded service. Nothing stops us from creating one though. E.g. 512 Degraded Service.

**Comment by aspnet-hello** [comment]
_From @anurse on Wednesday, October 11, 2017 9:25:50 AM_

Sure, but we have to provide the option to use it in order to allow existing systems to work.

**Comment by aspnet-hello** [comment]
_From @Drawaes on Wednesday, October 11, 2017 9:55:55 AM_

Okay so how do you normally get to a degraded service? If you have stuff broken normally it is just broken as well. If it's degraded? 

It usually means it's going to respond outside of some sla. So it's slow.  Why are things normally slow? Too much load..  where does load come from Clients. So yeah I am blaming the client for a degraded service.

Let's look at it another way. When you get a too many requests as a client. What's the expected behaviour on an API? Well a good client will back off and then rate limit to stop hitting the server rate limit. Which is exactly the behaviour you want towards a degraded.

Eitherway seems a bit crazy to have the out of the box experience for say consul... and now you need to map your own http codes. I would just write a map statement myself in that case ....

**Comment by aspnet-hello** [comment]
_From @anurse on Wednesday, October 11, 2017 10:00:11 AM_

> Eitherway seems a bit crazy to have the out of the box experience for say consul... and now you need to map your own http codes. I would just write a map statement myself in that case ....

Yeah, this is definitely something we're considering. We may make `429` the default for exactly this reason. Either way, we'll provide the options to allow it to be customized for users that need that level of customization. There are also health check systems that don't represent Degraded as a separate status (Docker, Kube) and some users may want to map Degraded to `200` in those cases (i.e. don't affect load balancing, but perhaps some other component will be monitoring for degraded status), whereas others will want to make Degraded to `503`. So we'll need to pick defaults based on our target scenarios and provide customization where needed.

**Comment by aspnet-hello** [comment]
_From @Drawaes on Wednesday, October 11, 2017 10:03:50 AM_

I mean you can provide a bunch of defaulted options to be helpful... or an OSS package could. E.g. AddConsulHealthCheck() AddDockerHealthCheck ()

**Comment by rynowak** [comment]
The set of status codes for health checks are customizable now 👍
