### ISSUE TITLE
please support a better status code page by default 

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/Home#2588]
_From @John0King on Sunday, July 16, 2017 8:19:33 PM_

Current default status code page is too simple, No one should use that in production environment.
please make the default status code page more useful

_Copied from original issue: aspnet/Diagnostics#395_

**Comment by aspnet-hello** [comment]
_From @davidfowl on Sunday, July 16, 2017 9:26:56 PM_

Do you have any suggestions about how it could be improved?

**Comment by aspnet-hello** [comment]
_From @John0King on Sunday, July 16, 2017 10:15:33 PM_

Embed a few html file about `403`，`404` and `500` (and other) state code, those are very common status code , like you did for IIS .  The key point  is  about the description of status code .

**Comment by aspnet-hello** [comment]
_From @Tratcher on Sunday, July 16, 2017 11:36:01 PM_

Yes, it's very much a placeholder that provides non-empty content for otherwise empty responses. The main problem with enriching the content is that you have to make more assumptions about your client. E.g. is it a browser, mobile app, etc.? Without introducing user agent or accept header sniffing it would be hard to provide generally applicable content.

Have you tried the UseStatusCodePagesWithReExecute and using MVC to render a more site integrated view?

**Comment by aspnet-hello** [comment]
_From @John0King on Monday, July 17, 2017 1:21:40 AM_

> Have you tried the UseStatusCodePagesWithReExecute and using MVC to render a more site integrated view.

Yes, I do it all the time for now,but I do it only for the users can understand there is an error on the page.

> Without introducing user agent or accept header sniffing it would be hard to provide generally applicable content

I think the content is irrelevant for client when `404`,`500` happend,  and even it does, we can get the `HttpContext` from the pipeline, I really hope this middleware can do more than show the statuscode for developer

```html
<h1 style="color: darkred;">{status code} - { status code summary }</h1>
<p>{statuscode description}</p>
```
A simple html like this  is much better than  now

**Comment by aspnet-hello** [comment]
_From @John0King on Tuesday, November 28, 2017 7:55:10 PM_

@davidfowl  I debug a webapi mehod for almost 3h today , ture out it's a problem with `UseStatusCodePageWithReExecute`  , not sure it's a bug or by design .
Here's the story:
My Filter return 401 if request 's `Accept` not contains "html" , and return 302 redirect when it does,
but my "ReExecute path" is not define in the application (mvc action) , so everytime it return 401 ,this middleware ReExcute the pipeline and get a 404 response. 

I think the middleware should find a way that do not ovewrrite the statuscode and thow a exception when the statuscode change

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @John0King. We have no plans to change the default status code page at the moment. But you can customize the status code pages however you like.
