### ISSUE TITLE
Batch support

### ISSUE THREAD

**Issue by rosieks** [aspnet/Home#262]
ASP.NET WebAPI 2 introduced support for batching. There was issue for batch implementation in Mvc but it was closed: https://github.com/aspnet/Mvc/issues/508

Despite that it would be great to have this usefull feature.

**Comment by damienbod** [comment]
How will this be supported? 
Greetings Damien

**Comment by OneCyrus** [comment]
+1 
batch support is essential for modern web apps. any progress or new information?

**Comment by rdefreitas** [comment]
the original issue suggested doing this through Middleware. It might not be too difficult to implement.

**Comment by brianoconnell** [comment]
Has there been any further plans made to support batching either via middleware or otherwise?

**Comment by gilmishal** [comment]
This shouldn't be too difficult, Would have done it my self if it wasn't for my lack of time... It seems like it requires a router implementation mapping `/batch` to multiple `RouteContext`s by formatting the text input (json, http format text) each with their own Handler based on the default configuration (i.e MVC).

**Comment by josh-sachs** [comment]
+1 important.

**Comment by khushalpatel1981** [comment]
+2 Very Important, it's stopped us to migrate from .net 4.5 to core 1.1 and
move to production

**Comment by danroth27** [comment]
This issue was moved to aspnet/BasicMiddleware#246
