### ISSUE TITLE
Should I write all "ErrorMessage" for all "RequiredAttritue"?

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/Home#2631]
_From @717009629 on Sunday, December 10, 2017 7:38:17 PM_

![111](https://user-images.githubusercontent.com/16289643/33814721-332c7e0c-de67-11e7-946e-1f65d22e5214.png)
![112](https://user-images.githubusercontent.com/16289643/33814733-40373fba-de67-11e7-9de7-ec6b48ca0b85.png)

If I have 100 [Required], should I write  100 "ErrorMessage"?

_Copied from original issue: aspnet/Localization#432_

**Comment by aspnet-hello** [comment]
_From @mkArtakMSFT on Friday, December 29, 2017 10:27:49 AM_

@ryanbrandenburg, is there a way to simplify this?

**Comment by aspnet-hello** [comment]
_From @ryanbrandenburg on Friday, December 29, 2017 10:55:43 AM_

I believe this is a dup of https://github.com/aspnet/Localization/issues/286#issuecomment-249046258. Specifically you can find our recommendation for this scenario [here](https://github.com/aspnet/Localization/issues/286#issuecomment-249632215). A more comprehensive solution would have to come from the corefx team.

Do those resources answer your question?

**Comment by hishamco** [comment]
@mkArtakMSFT seems this need to be closed

**Comment by ryanbrandenburg** [comment]
This seems to have been addressed, @717009629 if you're still having trouble let us know.
