### ISSUE TITLE
StringLocalizer doesn't find resources in base class

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/Home#2632]
_From @nd-srogers on Wednesday, December 6, 2017 5:28:27 PM_

I am using the [Identity Server 4 Quickstart UI](https://github.com/IdentityServer/IdentityServer4.Quickstart.UI) for identity in my application and I'm in the processing of adding localization support for error messages and other strings.

The quickstart UI contains several view models, some of which inherit others. For example, the `LoginViewModel` inherits the `LoginInputModel` to allow reuse of some properties:

    public class LoginInputModel
    {
        [Required(ErrorMessage = "NoEmail")]
        public string Username { get; set; }

        [Required(ErrorMessage = "NoPassword")]
        public string Password { get; set; }

        public bool RememberLogin { get; set; }
        public string ReturnUrl { get; set; }
    }

    public class LoginViewModel : LoginInputModel
    {
        public string ClientName { get; set; }
        public string ClientLogoUri { get; set; }

        public bool AllowRememberLogin { get; set; }
        public bool EnableLocalLogin { get; set; }

        public IEnumerable<ExternalProvider> ExternalProviders { get; set; }
        public IEnumerable<ExternalProvider> VisibleExternalProviders => ExternalProviders?.Where(x => !String.IsNullOrWhiteSpace(x.DisplayName));

        public bool IsExternalLoginOnly => EnableLocalLogin == false && ExternalProviders?.Count() == 1;
        public string ExternalLoginScheme => ExternalProviders?.SingleOrDefault()?.AuthenticationScheme;
    }

As you can see 'LoginInputModel' has some 'Required' attributes containing keys to pull from a resource file.

I have named my resource file `LoginInputModel.resx` and placed it in my `Resources` folder. However, when I run my app and trigger the error message, all that is returned is 'NoEmail' and 'NoPassword'.

Digging into the `aspnet.mvc` code I found that because my Razor Page is using the `LoginViewModel`, this is the resource name that is being used to find the appropriate resource file.

![image](https://user-images.githubusercontent.com/33408863/33693990-7f70b356-db41-11e7-84d3-8ed4343dc892.png)

You can see that there are 2 items in the `_missingManifestCache` which are the `NoEmail` and `NoPassword` keys.

Is there any way to get the string localizer to be able to pull resources from inherited base classes?

I don't want to change the resource file name to `LoginViewModel` because I am using `LoginInputModel` in other places and don't want to duplicate resources.

_Copied from original issue: aspnet/Localization#430_

**Comment by aspnet-hello** [comment]
_From @mkArtakMSFT on Friday, December 29, 2017 10:30:23 AM_

Hey @ryanbrandenburg, can you help with this?

**Comment by aspnet-hello** [comment]
_From @ryanbrandenburg on Friday, December 29, 2017 2:44:06 PM_

If you want a behavior other than the default you can set the `DataAnnotationsLocalizerProvider` as we've suggested [here](https://github.com/aspnet/Localization/issues/286#issuecomment-249632215) to have any behavior you want based on the type.

**Comment by hishamco** [comment]
@mkArtakMSFT I think this should be closed while it's already answers, and there's no respond from awhile

**Comment by ryanbrandenburg** [comment]
Yeah, closing this out, reopen if you feel there's something we didn't address.
