### ISSUE TITLE
FallBackToParentCultures does not respect zh-CN and zh-Hans

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/Home#2634]
_From @yufeih on Wednesday, September 13, 2017 9:00:23 PM_

When `FallBackToParentCultures` is set, *zh-CN* will not be fallback to *zh-Hans*.

Locale fallback simply trim the last section after dash, this is incorrect:

https://github.com/aspnet/Localization/blob/dev/src/Microsoft.AspNetCore.Localization/RequestLocalizationMiddleware.cs#L206

*zh-Hans* should be a parent locale of *zh-CN*

_Copied from original issue: aspnet/Localization#415_

**Comment by aspnet-hello** [comment]
_From @hishamco on Wednesday, September 13, 2017 10:43:12 PM_

Could you please refer to issue #273, seems `zh-{cultures}` are more complicated than I knew 😄

**Comment by hishamco** [comment]
@ryanbrandenburg is your comment [here](https://github.com/aspnet/Localization/issues/273#issuecomment-237983479) enough to close this bug, or is there anything else that we can do

**Comment by ryanbrandenburg** [comment]
I think so. @yufeih if you think that doesn't apply reopen, otherwise I'm closing it out.
