### ISSUE TITLE
ASP.NET 5 and the debugger

### ISSUE THREAD

**Issue by JamesNK** [aspnet/Home#264]
Talking with @davidfowl, today it sounds like if you make a code change to a ASP.NET website, and the debugger is attached, the ASP.NET website won't recycle and reflect your changes until you detach the debugger.

This is a pain when you want to debug your new changes to a website immediately. You will have to detach, (possibly save the cs file again), then ctrl+alt+p to bring up the processes list and then find and select the website process, then click attach. This 1+ minute overhead is annoying.

Ideally what I'd like to happen is on save of a cs file is the website is automatically recycled, and the debugger is reattached, so you can make changes and keep debugging without breaking your flow of having to manually attach and detach the debugger. (I know that it isn't E&C and you'll lose your current request if you've hit a breakpoint, that's fine)

One idea is VS displays a prompt when you save a ASP.NET 5 cs project file while debugging, asking whether you want to recycle the website and keep debugging. Your changes will automatically be reflected in the website and the VS debugger will still be attached. Developer productivity++

**Comment by Eilon** [comment]
@mayurid @barrytang for tooling.

**Comment by barrytang** [comment]
Opened a VS bug for this.

**Comment by sayedihashimi** [comment]
@Eilon if we have edit-and-continue support do we need this?

**Comment by Eilon** [comment]
Hmm not sure. Personally I've never trusted Edit and Continue because it seemed too magical to me. I prefer restarting my app so I know the exact state it's in.

Do customers use Edit and Continue in ASP.NET apps? (Or has it ever worked?)

**Comment by JamesNK** [comment]
I have been using ASP.NET since 2003 and I have never once seen edit and continue work with it.

**Comment by danroth27** [comment]
I opened https://github.com/aspnet/Tooling/issues/14 in our new Tooling repo to track this request.

**Comment by tommck** [comment]
I used edit and continue a lot, but it became a LOT less useful once LINQ came around and it couldn't handle that.
