### ISSUE TITLE
Track Assembly and Resource issues

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/Home#2648]
_From @ryanbrandenburg on Tuesday, July 5, 2016 11:56:48 AM_

This is a tracking issue for dotnet/corefx#9766 and dotnet/coreclr#6123 which were found due to #257 and had work arounds in aspnet/Localization#262.

_Copied from original issue: aspnet/Localization#263_

**Comment by aspnet-hello** [comment]
_From @Eilon on Tuesday, July 5, 2016 1:32:15 PM_

@ryanbrandenburg , parking this on your plate. No action required at this time.

**Comment by aspnet-hello** [comment]
_From @hishamco on Sunday, February 5, 2017 12:55:37 AM_

@ryanbrandenburg if I'm not wrong the issues that you mentioned before are closed, so i'm not sure if we need this open anymore

**Comment by aspnet-hello** [comment]
_From @ryanbrandenburg on Tuesday, February 7, 2017 4:04:57 PM_

You're correct that those issues are closed, but I'm leaving this open to track the fact that we need to go back and undo the workarounds we had in place for them.

**Comment by aspnet-hello** [comment]
_From @hishamco on Friday, March 3, 2017 4:01:12 PM_

Are we still need this, seems all the mentioned issues got fixed?!!

**Comment by aspnet-hello** [comment]
_From @hishamco on Saturday, March 4, 2017 11:15:13 AM_

/cc @Eilon

**Comment by aspnet-hello** [comment]
_From @rynowak on Friday, June 30, 2017 10:07:43 AM_

Nothing is broken here so moving this out

**Comment by aspnet-hello** [comment]
_From @hishamco on Friday, June 30, 2017 10:43:16 AM_

@rynowak the permenant fix that I made in PR #384 may has a breaking-change

**Comment by ryanbrandenburg** [comment]
@hishamco was correct, both issues were already resolved (I thought one of them was still around). This can be closed now.
