### ISSUE TITLE
Pull requests for documentation?

### ISSUE THREAD

**Issue by Shazwazza** [aspnet/Home#265]
I'm wondering where the best place would be to create pull request for documentation? 

I know there's a teeny bit of documentation on the github wiki here: https://github.com/aspnet/Home/wiki but unfortunately we cannot create PRs for wiki's on GitHub. 

I think I remember someone at the MVP summit mentioning that there would be a markdown repository  created for documentation for AspNet5. IMO this would probably be the most ideal way to accept PRs for docs. Does something like this already exist?

In the meantime would it be worthwhile creating PRs to update some docs on readme's on the various repositories?

**Comment by Shazwazza** [comment]
Another question would be if it is worthwhile to create PRs for adding code documentation to classes/methods since I'm not really sure if these would end up in MSDN docs anyways?

**Comment by yishaigalatzer** [comment]
@Shazwazza you can definitely create PR for adding documentation for classes/methods.

When it comes to the markdown style repository, we are making progress investigating this, @danroth27 might be able to shed more light

**Comment by danroth27** [comment]
The docs repo isn't available yet, but we are working on it.

**Comment by danroth27** [comment]
The new Docs repo is here: https://github.com/aspnet/docs. We still need to formalize the contribution process. Also, API reference docs are still a work in progress.

**Comment by muratg** [comment]
Closing this one.  Thanks @Shazwazza!

**Comment by Shazwazza** [comment]
Great will have a look :+1:  Watched some details about the docs story on the ASP.Net standup the other week, definitely interested to see how this progresses!
