### ISSUE TITLE
Add a builder API for configuring UseRequestLocalization

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/Home#2650]
_From @rynowak on Friday, October 23, 2015 10:49:48 AM_

This would be more inline with what we do in other places in the framework. The use the current experience you need to add 2 usings that you may not likely have in your startup code.

**Suggested**

```
app.UseRequestLocalization(options => options.AddCultures("en-US", "en-GB", "fr").SetDefault("en-US"));
```

**Current**

```
using System.Collections.Generic;
using System.Globalization;
using Microsoft.AspNet.Localization;

            var localizationOptions = new RequestLocalizationOptions()
            {
                SupportedCultures = new List<CultureInfo>()
                {
                    new CultureInfo("en-US"),
                    new CultureInfo("en-GB"),
                    new CultureInfo("fr"),
                },
                SupportedUICultures = new List<CultureInfo>()
                {
                    new CultureInfo("en-US"),
                    new CultureInfo("en-GB"),
                    new CultureInfo("fr"),
                },
            };

            app.UseRequestLocalization(options, new RequestCulture(new CultureInfo("en-US")));
```

_Copied from original issue: aspnet/Localization#127_

**Comment by aspnet-hello** [comment]
_From @hishamco on Friday, October 23, 2015 1:00:08 PM_

Great, that is what i wanna suggest but with little modification

``` csharp
app.UseRequestLocalization(options => {
    options.SupportedCultures("en-US", "en-GB", "fr")
           .SupportedUICultures("en-US")
           .Default("en-US")
});
```

IMHO Fluent API in such case is a proper option

**Comment by aspnet-hello** [comment]
_From @Eilon on Thursday, October 29, 2015 8:35:10 PM_

The builder APIs need to have verbs in them, so `AddSupportedCultures` works, but not just `SupportedCultures`.

**Comment by aspnet-hello** [comment]
_From @hishamco on Friday, October 30, 2015 3:08:57 AM_

So something like this will be fine

``` csharp
app.UseRequestLocalization(options => {
    options.AddSupportedCultures("en-US", "en-GB", "fr")
           .AddSupportedUICultures("en-US")
           .SetDefault("en-US")
});
```

also may we need an option to add `CustomRequestCultureProvider`

**Comment by aspnet-hello** [comment]
_From @Eilon on Friday, October 30, 2015 9:32:07 AM_

@kirthik @rynowak I'd like to spend a few minutes designing this next week so we agree on the pattern.

**Comment by aspnet-hello** [comment]
_From @DamianEdwards on Tuesday, December 22, 2015 10:06:39 PM_

Just going to change this to use the options setter delegate pattern instead, e.g.:

``` C#
app.UseRequestLocalization(options =>
    options.DefaultRequestCulture = new RequestCulture("en-US");
    options.SupportedCultures = new [] { "en-US", "fr" };
    options.SuppoertedUICultures = options.SupportedCultures;
);
```

**Comment by aspnet-hello** [comment]
_From @hishamco on Tuesday, December 22, 2015 10:14:32 PM_

Sound fine too, but how we can pass the cultures as list of string while the `SupportedCultures` is of type `IList<CultureInfo>` in https://github.com/aspnet/Localization/blob/b041a07652e17baa335970499ffe721454090837/src/Microsoft.AspNet.Localization/RequestLocalizationOptions.cs#L91

**Comment by aspnet-hello** [comment]
_From @DamianEdwards on Tuesday, December 22, 2015 10:17:06 PM_

You'll just write the correct code :smile:

``` C#
app.UseRequestLocalization(options =>
    options.DefaultRequestCulture = new RequestCulture("en-US");
    options.SupportedCultures = new [] { new CultureInfo("en-US"), new CultureInfo("fr") };
    options.SuppoertedUICultures = options.SupportedCultures;
);
```

**Comment by aspnet-hello** [comment]
_From @hishamco on Tuesday, December 22, 2015 10:20:59 PM_

I though the idea is to rid off `CultureInfo` and `RequestCulture` as the idea began in this issue :smile: and seems is a PR #189 is made to fix this

**Comment by aspnet-hello** [comment]
_From @DamianEdwards on Tuesday, December 22, 2015 10:39:37 PM_

Yeah we made a decision to standardize on the options setter delegate pattern throughout the code base.

I don't think we have an example of a builder API anywhere else for middleware options, but we certainly have it for services options. I can see why this would be nice in order to avoid the namespace imports.

Some examples to consider:

``` C#
public void Configure(IApplicationBuilder app)
{
    // UseRequestLocalization(params string[] cultures)
    // All params passed are supported format & UI cultures, first param is also the default culture
    // No extra namespace imports required
    app.UseRequestLocalization("en-US", "fr");

    // UseRequestLocalization(string defaultCulture, IList<string> supportedCultures, IList<string> supportedUICultures)
    // Explicit params for each option property
    // No extra namespace imports required
    app.UseRequestLocalization(
        defaultCulture: "en-US",
        supportedCultures: new [] { "en-US", "fr" },
        supportedUICultures: new [] { "en-US", "fr" });

    // UseRequestLocalization(Action<RequestLocalizationOptions> options)
    // Standard options delegate
    // Need to import the localization and globalization namespaces
    app.UseRequestLocalization(options =>
    {
        options.DefaultRequestCulture = new RequestCulture("en-US");
        options.SupportedCultures = new [] { new CultureInfo("en-US", new CultureInfo("fr") };
        options.SuppoertedUICultures = options.SupportedCultures;
    });

    // UseRequestLocalization(Action<RequestLocalizationOptions> options)
    // Options builder API that hangs off of RequestLocalizationOptions
    // No extra namespace imports required
    app.UseRequestLocalization(options =>
        options
            .SetDefaultCulture("en-US")
            .AddSupportedCultures("en-US", "fr")
            .AddSupportedUICultures("en-US", "fr")
    );
}
```

**Comment by aspnet-hello** [comment]
_From @hishamco on Tuesday, December 22, 2015 10:46:14 PM_

Thanks a lot

**Comment by aspnet-hello** [comment]
_From @hishamco on Saturday, December 26, 2015 9:57:17 PM_

This should be closed after the commit d9fc39953143367a2fc3dab650859dc1a06b328e

**Comment by aspnet-hello** [comment]
_From @hishamco on Friday, March 3, 2017 3:59:26 PM_

@ryanbrandenburg I already implemented this few weeks back on my repo https://github.com/hishamco/localization/tree/useRequestLocalization, if the issue still active I will submit a PR, if it's not I think we should close it

/cc @Eilon

**Comment by aspnet-hello** [comment]
_From @Eilon on Saturday, March 4, 2017 10:18:44 AM_

Bringing this out of Backlog for discussion.

**Comment by aspnet-hello** [comment]
_From @DamianEdwards on Saturday, March 4, 2017 10:43:41 AM_

Ooo I forgot about this one. This would be a nice one to do if we have the capacity.

**Comment by mkArtakMSFT** [comment]
Hi @hishamco.
Are you still interested in sending out a PR with a fix for this issue?

**Comment by hishamco** [comment]
@mkArtakMSFT I already did that long time ago https://github.com/aspnet/Localization/pull/369, I review it again if there's any feedback or conflict I should fix

**Comment by mkArtakMSFT** [comment]
@ryanbrandenburg, can you please review the PR from @hishamco? Please also include anyone who you think should review that.

**Comment by hishamco** [comment]
One note to @Elion, I notice in the comment https://github.com/aspnet/Home/issues/2650#issuecomment-354692586 that the links it's no longer point to the original repo after migrating the issues, I'm not sure if someone else notice that?!!

**Comment by Eilon** [comment]
@hishamco thanks yeah that's a challenge for the bug porting script. Unless a full URL was used, the links to related issues can be broken. It's something I'm considering addressing in the future.

**Comment by hishamco** [comment]
Good Luck ..
