### ISSUE TITLE
Json formatters do not respect the RequestLocalization middleware's culture

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/Home#2651]
_From @Martijn-Sharp on Tuesday, September 15, 2015 11:55:37 PM_

When using the RequestLocalization middleware one would expect that the JsonInputFormatter will use the culture as it's defined in the options.
To give you an example, I have the following options defined:

``` c#
var dutchCulture = new CultureInfo("nl-NL");
app.UseRequestLocalization(new RequestLocalizationOptions
{
    DefaultRequestCulture = new RequestCulture(dutchCulture, dutchCulture),
    SupportedCultures = new List<CultureInfo> { dutchCulture },
    SupportedUICultures = new List<CultureInfo> { dutchCulture }
});
```

When HTTP POSTing to a controller action with JSON it might bind a datetimestring of '10-05-2015' as the 5th day of the 10th month of 2015. While actually with the Dutch dateformat (dd-MM-yyyy) it should've been the 10th day of the 5th month of 2015.
This happens because the JSON serializer isn't aware that I set dutch culture in the request localization middleware. Or at least that's what it seems, the 'problem' might simply be a too-early check of CultureInfo.Current(UI)Culture by the serializer?
Whatever it is, I think it'd make more sense if the JSON serializer used the correct culture.

To fix it in my context I use `services.AddMvc().AddJsonOptions(json => json.SerializerSettings.Culture = new CultureInfo("nl-NL"));` for now. But that won't work if you support multiple cultures, unlike me.

_Copied from original issue: aspnet/Localization#78_

**Comment by aspnet-hello** [comment]
_From @hishamco on Friday, March 3, 2017 4:02:30 PM_

@Martijn-Sharp is this still happening?

**Comment by aspnet-hello** [comment]
_From @hishamco on Friday, March 24, 2017 1:17:15 AM_

@Eilon shall we close this for now, while there's no respond, @Martijn-Sharp is free to open this if there's a straightforward scenario to reproduce this issue

**Comment by hishamco** [comment]
While we didn't hear any respond from @Martijn-Sharp around year ago, this should be closed

/cc @Eilon

**Comment by Eilon** [comment]
@hishamco agreed, closing. THanks!
