### ISSUE TITLE
Unusual route values appearing when using `Url.Action`

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/Home#2654]
_From @mkArtakMSFT on Wednesday, December 27, 2017 10:29:04 AM_

_From @MorayM on December 6, 2017 9:31_

I'm trying to create a link to the following GET:

    public class FooController : Controller
    {
        [HttpGet]
        [Route("Foo/Apply/BarDetails/Part/{id}")]
        public IActionResult BarDetails(int id)
        {
        }
    }

In my view I'm creating a URL with

    Url.Action("BarDetails", "Foo", new {id = 1})

I was expecting this to generate `Foo/Apply/BarDetails/Part/1` however I actually get `Foo/Apply/BarDetails/Part/10?id=1` and I'm struggling to understand why. The page this link is on has no `id` parameter in its route (or indeed any parameters in its route) so there shouldn't be any ambient values. Removing the `values` parameter simply removes the query string part of the URL. The only route I have registered at startup is the default:

    app.UseMvc(routes =>
    {
        routes.MapRoute(
            name: "default",
            template: "{controller=Home}/{action=Index}/{id?}");
    });

I suspect that the `10` is coming from a `"1" + "0"` operation happening somewhere but I haven't found it yet in the source! Does anyone know why this might be happening?

_Copied from original issue: aspnet/Mvc#7112_

_Copied from original issue: aspnet/Routing#504_

**Comment by aspnet-hello** [comment]
_From @mkArtakMSFT on Wednesday, December 27, 2017 10:29:05 AM_

_From @MorayM on December 6, 2017 14:55_

OK, I've figured it out. It's mostly a quirk in the the way I've written my `FooController` but as `FooController` originally came from an MVC5 project where the routing worked I thought I'd log it and leave it to the team to decide if the current MVC Core behaviour is a bug or a feature!

My `FooController` is responsible for a form that consists of ~250 views organised in sections and looks a bit like this:

    public class FooController : Controller
    {
		[HttpGet]
		[Route("Foo/Apply/Section1/Part/{id}")]
		public IActionResult Section1(int id)
		{
			var model = GetModelForSection1(id);//get the model for the requested section
			var viewPath = GetViewPathForSection1(id);//Calculate the path to the viewPath
			return View(viewPath, model);
		}
		
		[HttpPost]
		[Route("Foo/Apply/Section1/Part/1")]
		public IActionResult Section1(Part1Model model)
		{
			// Do whatever with the model
			return RedirectToAction("Section1", 2);
		}
		
		[HttpPost]
		[Route("Foo/Apply/Section1/Part/2")]
		public IActionResult Section1(Part1Model model)
		{
			// Do whatever with the model
			return RedirectToAction("Section1", 3);
		}
		
		// etc for 10 more views in Section 1...
		// etc for 6 more sections...
    }

The `POST` actions are all named the same for each section so we didn't have to manually specify actions for the forms in each of the 250 different views!

The problem in generating routes with `Url.Action` comes when the [Routing](https://github.com/aspnet/Routing) module tries to find a match for the controller name/action name combination. When given a controller name `Foo` and an action name `Section1`, `LinkGenerationDecisionTree.GetMatches` finds a list of matches like this:

	"Foo/Apply/Section1/Part/{id}"
	"Foo/Apply/Section1/Part/1"
	"Foo/Apply/Section1/Part/2"
	etc...
	
Which is fine until [line 30](https://github.com/aspnet/Routing/blob/dev/src/Microsoft.AspNetCore.Routing/Internal/LinkGenerationDecisionTree.cs#L30) where `GetMatches` sorts the list of matches by precedence, which sends `Foo/Apply/Section1/Part/{id}` (with precedence 5.5553) to the bottom, and then by the route template text, and as the rest of the matches have the same precedence (5.555) this sends `Foo/Apply/Section1/Part/10` to the top of the list. This is the first match for controller name `Foo` and action name `Section1`, hence why `Foo/Apply/Section1/Part/10` always appears:

	"Foo/Apply/Section1/Part/10"
	"Foo/Apply/Section1/Part/11"
	"Foo/Apply/Section1/Part/12"
	"Foo/Apply/Section1/Part/1"
	"Foo/Apply/Section1/Part/2"
	etc...
	"Foo/Apply/Section1/Part/{id}"

As I said, I'll leave it up to the team to decide whether this is the intended behaviour or not but I thought it was worth flagging up as the end result is different from the behaviour in MVC5. And also because I've had such a fun time this morning hunting it down I thought I'd share the joy :wink:

In the meantime I'll reorganise my controller to give my `POST` actions unique names...

**Comment by aspnet-hello** [comment]
_From @mkArtakMSFT on Wednesday, December 27, 2017 10:29:05 AM_

_From @MorayM on December 6, 2017 14:57_

Hmm, looking at the eventual source I guess this should probably be moved to the [Routing](https://github.com/aspnet/Routing) module?

**Comment by aspnet-hello** [comment]
_From @mkArtakMSFT on Wednesday, December 27, 2017 10:29:06 AM_

_From @davidliang2008 on December 19, 2017 19:40_

I have the exact same issue! `@Url.Action()` and even the tag helper `asp-controller` and `asp-action` would have the route value appended at the end of the URL.

And that route value looks like the id of the current request URL.

For example, if I have an edit page /product/edit/10 but I want to display edit links for other products on that page, those links would look like

/product/edit/10?id=1
/product/edit/10?id=2,
....
/product/edit/10?id=10000

**Comment by aspnet-hello** [comment]
_From @mkArtakMSFT on Wednesday, December 27, 2017 10:31:01 AM_

@pranavkm, can you please handle this? /cc FYI @rynowak, this might be an actual routing bug

**Comment by aspnet-hello** [comment]
_From @rynowak on Wednesday, December 27, 2017 3:13:02 PM_

This definitely intended, whether or not it's ideal is another question. We might be able to improve this.

You can also configure the order in which routes are processed by setting an order on the route attribute. Setting a lower order will cause that route to be processed first for both matching and link generation

**Comment by mkArtakMSFT** [comment]
@MarayM, @davidliang2008 looks like you can solve the problem you both are facing using Order and Name attributes of the RouteAttribute. Just define the Name and pass it in when calling Url.Action.

**Comment by davidliang2008** [comment]
@mkArtakMSFT : or simply reset the parameter when using Url.Action or the tag helper

`@Url.Action("edit", "product", new { area = "", id = "" });`

`<a asp-area="" asp-controller="product" asp-action="edit" asp-route-id="">edit</a>`

I was hoping there is some kind of configuration settings we can do on Startup to disable that, rather than override the id value on each action link, or putting Order and Name attributes everywhere.
