### ISSUE TITLE
Contribution documentation does not specify target/parent branch

### ISSUE THREAD

**Issue by peterblazejewicz** [aspnet/Home#266]
The Contributing.md for this project does not mention which branch should be used to make PR. See comments on my PR:
https://github.com/aspnet/Home/pull/260#issuecomment-69607237

https://github.com/aspnet/Home/blob/master/CONTRIBUTING.md

The topic is not covered in [wiki](https://github.com/aspnet/home/wiki)

Can we update Contributing.md to show people which branch should be used as parent of PR (here `dev` branch).

Thanks!

**Comment by Eilon** [comment]
Yes, a good point to clarify. We did have some text in https://github.com/aspnet/Home/wiki/Engineering-guidelines#branch-strategy, but I just updated that to make it clearer.

Per your suggestion I also added a small note to https://github.com/aspnet/Home/blob/master/CONTRIBUTING.md to clarify.

**Comment by peterblazejewicz** [comment]
@Eilon Thanks! Appreciated!
