### ISSUE TITLE
Optimize RVD for common case (action, controller, id, area)

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/Home#2671]
_From @rynowak on Wednesday, June 22, 2016 5:34:07 PM_

We want to produce an optimized implementation of `RouteValueDictionary+Storage` for the common case, this will save a lot of allocations in link generation

_Copied from original issue: aspnet/Routing#330_

**Comment by mkArtakMSFT** [comment]
Never heard a complain about this, so closing.
