### ISSUE TITLE
Revive ifdef-ed TemplateRouteTest

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/Home#2673]
_From @pranavkm on Tuesday, December 1, 2015 10:51:50 AM_

There's a bunch of tests in `TemplateRouteTest` https://github.com/aspnet/Routing/blob/dev/test/Microsoft.AspNet.Routing.Tests/Template/TemplateRouteTest.cs#L633 that are ifdef out.

_Copied from original issue: aspnet/Routing#242_

**Comment by aspnet-hello** [comment]
_From @Eilon on Wednesday, December 9, 2015 9:25:52 AM_

A bunch of `#ifdef`ed stuff in https://github.com/aspnet/Routing/blob/d4b96b27c0a7ab051b6b90a72a131e5042e141be/test/Microsoft.AspNet.Routing.Tests/Template/TemplateBinderTests.cs as well.

**Comment by aspnet-hello** [comment]
_From @Eilon on Wednesday, December 9, 2015 9:27:52 AM_

@javiercn please sync with @pranavkm / @rynowak to assess what the expectations are here.

**Comment by aspnet-hello** [comment]
_From @pranavkm on Monday, February 29, 2016 1:01:55 PM_

`TaskCache` is just code (and that looks ok). Presumably `TemplateRouteTest` got renamed to `TemplateBInderTests` at some point.

**Comment by aspnet-hello** [comment]
_From @Eilon on Friday, April 1, 2016 2:01:57 PM_

Moving to 1.0.0.

**Comment by aspnet-hello** [comment]
_From @rynowak on Thursday, June 29, 2017 2:52:59 PM_

Not happening for 2.0.0

**Comment by mkArtakMSFT** [comment]
Closing this as we have the `Dispatcher` work which may be covering this. Also, the existing tests are already covering this most probably.
