### ISSUE TITLE
Could not AOT the assembly build failure with version 2.0.1 in Xamarin.iOS projects

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/Home#2676]
_From @therealjohn on Wednesday, November 29, 2017 2:08:10 PM_

### Functional impact
Adding the latest versions of this NuGet, or any NuGet that has it as a valid dependency that would pull in the latest version will cause a build failure for device builds in Xamarin.iOS projects. 

### Minimal repro steps
1. Create a File > New Solution > Single View iOS Application. You can do these steps in VSMac or VS on Windows. 
2. Install-Package Microsoft.Net.Http.Headers -Version 2.0.1 for the iOS project in VS or use the Add Packages menu in VSMac to add this NuGet. 
3. Open the AppDelegate.cs file and add this line of code in the `FinishedLaunching` method.
```
// Arbitrary type used from the package so it's included in the build
new Microsoft.Net.Http.Headers.CacheControlHeaderValue();
```
4. Change the build configuration to Debug | iPhone (Generic Device)
5. Build the iOS project

### Expected result
Build Success

### Actual result
Build fails. 

```
/Users/johnmiller/Projects/TestingSA/TestingSA/MTOUCH: Error MT3001: Could not AOT the assembly '/Users/johnmiller/Projects/TestingSA/TestingSA/obj/iPhone/Debug/mtouch-cache/Build/Microsoft.Net.Http.Headers.dll' (MT3001) (TestingSA)
```

### Further technical details
Attached is the full build output. 
[fullbuildoutput.txt](https://github.com/aspnet/HttpAbstractions/files/1515728/fullbuildoutput.txt)
Downgrading to version 2.0.0 of the package works around this issue. 

If this is not the correct place to file the issue, please let me know!

_Copied from original issue: aspnet/HttpAbstractions#974_

**Comment by aspnet-hello** [comment]
_From @nbsoftware on Sunday, December 10, 2017 9:42:10 AM_

​I can confirm the issue. And I also confirm that downgrading to Microsoft.Net.Http.Headers package to 2.0.0 does work around it.

**Comment by aspnet-hello** [comment]
_From @michelmoorlag on Monday, December 18, 2017 1:18:35 AM_

Same issue here when I try to build a XF IOS  adhoc app. Downgrading Microsoft.Net.Http.Headers package to version 2.0.0 fixed the issue for me.

**Comment by LuigiMaestrelli** [comment]
Same problem here. 
Any news?

**Comment by danielmeza** [comment]
I solve the problem, you need to change the linker behavior to Link Framework SDKs Only and disabe the Enalble device-specific build on your proyect configuration. 
your configuration may look like this 
![image](https://user-images.githubusercontent.com/16217470/35001176-3aa8b8e4-fab4-11e7-9576-84db37ef6b54.png)

**Comment by muratg** [comment]
Closing per @danielmeza's last comment.

**Comment by muratg** [comment]
@therealjohn if you still have issues, please ping me. Thanks.

**Comment by jorisvergeer** [comment]
Still an issue when building on microsoft appcenter, even with suggested settings.
Downgrade to 2.0.0 is still the workaround
