### ISSUE TITLE
Invalid Content Disposition Header

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/Home#2677]
_From @Tratcher on Sunday, November 26, 2017 10:22:12 PM_

_From @Petermarcu on November 27, 2017 5:1_

@StefanoD opened this here: https://github.com/dotnet/core/issues/1106

According to https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition the parameters of the content disposition header must be quoted. Instead APS.Net Core sends them without quote:

`attachment; filename=latest_bin.txt; filename*=UTF-8''latest_bin.txt`

I'm using .Net Core 2.0

_Copied from original issue: aspnet/Home#2288_

_Copied from original issue: aspnet/HttpAbstractions#973_

**Comment by aspnet-hello** [comment]
_From @Tratcher on Sunday, November 26, 2017 10:22:48 PM_

What API are you using to send the file? an MVC FileResult?

**Comment by aspnet-hello** [comment]
_From @StefanoD on Sunday, November 26, 2017 11:29:56 PM_

```C#
// GET: api/values
[HttpGet]
public async Task<IActionResult> Get()
{
        // ...
	var memory = new MemoryStream();
	using (var stream = new FileStream(path, FileMode.Open))
	{
		await stream.CopyToAsync(memory);
	}
	memory.Position = 0;

	return File(memory, "application/octet-stream", lastetUpdate.Name);
}
```

**Comment by aspnet-hello** [comment]
_From @Tratcher on Monday, November 27, 2017 10:02:39 AM_

(Unrelated) Why isn't that just?
```
	return PhysicalFile(path, "application/octet-stream", lastetUpdate.Name);
```

**Comment by aspnet-hello** [comment]
_From @Tratcher on Monday, November 27, 2017 10:42:08 AM_

See https://tools.ietf.org/html/rfc6266#section-4.1. filename may either be a token or a quoted string. filename*'s format does not use quotes.

     filename-parm       = "filename" "=" value
                         | "filename*" "=" ext-value
     token         = <token, defined in [RFC2616], Section 2.2>
     quoted-string = <quoted-string, defined in [RFC2616], Section 2.2>
     value         = <value, defined in [RFC2616], Section 3.6>
                   ; token | quoted-string
     ext-value     = charset  "'" [ language ] "'" value-chars
                   ; like RFC 2231's <extended-initial-value>
                   ; (see [RFC2231], Section 7)

**Comment by aspnet-hello** [comment]
_From @StefanoD on Monday, November 27, 2017 10:58:07 AM_

Ok, thx. Then in this case this is not a bug? Sorry for the noise!

**Comment by aspnet-hello** [comment]
_From @StefanoD on Monday, November 27, 2017 10:59:22 AM_

Qt 4.8 had issues to parse this, This is why I came to this conclusion and the mozilla reference, of course.

**Comment by muratg** [comment]
👍
