### ISSUE TITLE
Flaky test: CreateAggregate_works_when_exception_during_step

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/Home#2680]
_From @ryanbrandenburg on Wednesday, November 15, 2017 4:35:49 PM_

http://aspnetci/viewLog.html?tab=buildLog&logTab=tree&filter=debug&expand=all&buildId=355973&_focus=53774

_Copied from original issue: aspnet/HttpAbstractions#967_

**Comment by muratg** [comment]
@Tratcher could you take a quick look? Let's either disable, or decide it needs proper investigation now.

**Comment by ryanbrandenburg** [comment]
Unfortunately the build I linked is gone now and the test history on the ci shows 0 [failures](http://aspnetci/project.html?tab=testDetails&projectId=XPlat&testNameId=-4295766413256505083&page=1). Let's close this as not enough info. I'm including the actual error message text in all new issues to avoid this happening.

**Comment by muratg** [comment]
Closing this per last comment
