### ISSUE TITLE
Make `BufferingHelper` public

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/Home#2684]
_From @dougbu on Thursday, November 9, 2017 4:27:35 PM_

This class is currently pub-internal. An implementation is necessary when reading the request body multiple times. For example, ASP.NET Core WebHooks includes resource filters that calculate hashes of body content. They use the following helper to ensure this is safe:
https://github.com/aspnet/WebHooks/blob/be8571953a0124c0877f777e8fb5bb17329204ab/src/Microsoft.AspNetCore.WebHooks.Receivers/Filters/WebHookVerifyBodyContentFilter.cs#L94-L106

For reference: https://github.com/aspnet/HttpAbstractions/blob/3e3772eecd4cc57399c28a3f899e6b0406ef2e1b/src/Microsoft.AspNetCore.Http/Internal/BufferingHelper.cs

_Copied from original issue: aspnet/HttpAbstractions#963_

**Comment by aspnet-hello** [comment]
_From @dougbu on Thursday, November 9, 2017 4:31:16 PM_

Hmm, MVC used this class in a few places long before the ASP.NET Core WebHooks implementation was a thing.

**Comment by dougbu** [comment]
@Eilon @danroth27 @muratg any chance this can happen in 2.1.0-preview1? Doing it now will avoid breaking Mvc and WebHooks later.

I can do it if triaged into the milestone. (Yeah, I lost track of this issue.)

**Comment by dougbu** [comment]
Main change in aspnet/HttpAbstractions@7b9da556fb. Will close this issue once MVC and WebHooks reactions are done.

**Comment by dougbu** [comment]
- aspnet/Mvc@50af871396
- aspnet/WebHooks@a05a07c420
