### ISSUE TITLE
Adding MultipartWriter

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/Home#2685]
_From @daniel-white on Thursday, November 9, 2017 8:01:26 AM_

Would the community like a `MultipartWriter` to compliment `MultipartReader`? It looks like `MultipartSection` could be used as is.

_Copied from original issue: aspnet/HttpAbstractions#962_

**Comment by aspnet-hello** [comment]
_From @Tratcher on Friday, November 10, 2017 9:32:03 AM_

System.Net.Http.MultipartContent fulfills this need for most of our scenarios.

**Comment by muratg** [comment]
Closing per the last comment.
