### ISSUE TITLE
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Framework.ConfigurationModel.IConfiguration

### ISSUE THREAD

**Issue by jcreamer898** [aspnet/Home#269]
I just did a brand new install of all things `k`.

```shell
brew install kvm
npm install -g generator-aspnet
yo aspnet # chose web application
kvm restore
kvm build 
k web
```

After running `k web` I get this error...

![](http://d.pr/i/1bFn5+)

This is on OSX Yosemite.

**Comment by suhasj** [comment]
what version of kre was installed ? Also do have any custom feed registered for nuget ?

**Comment by jcreamer898** [comment]
![](http://d.pr/i/81yM+)

**Comment by jcreamer898** [comment]
![](http://d.pr/i/17aM5+)

**Comment by jcreamer898** [comment]
So, I tried `kvm upgrade` again, and now I get another error... lol

![](http://d.pr/i/11Dok+)

**Comment by Praburaj** [comment]
`k web` does not work on OSX. Try `k kestrel`

**Comment by suhasj** [comment]
so doing `kvm upgrade` changed the KRE to beta1 while your packages might be rc1. Do `kvm use 1.0.0-rc1-10883` to switch to latest kvm

**Comment by suhasj** [comment]
Ah sorry I overlooked that. yeah you should be doing `k kestrel`

**Comment by jcreamer898** [comment]
@Praburaj O_O

That worked...

**Comment by emersonsoares** [comment]
This solution not worked for me, I have the same problem and I tried the same options but the problem still exists. Any another options?
