### ISSUE TITLE
Please make BufferedReadStream public

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/Home#2691]
_From @Tornhoof on Thursday, August 31, 2017 11:50:58 PM_

Hi,
I'm currently building a Batch Handler (see https://github.com/aspnet/BasicMiddleware/issues/246) and I need to parse Headers and the Request line from a Multipart request, the parsing itself is basically just copy/paste of the existing Multipart parser part (it already has header support, I just need to add Request Line support, which is trivial). To properly do that I need to (efficiently) read lines from the request. The class ''BufferedReadStream'' in https://github.com/aspnet/HttpAbstractions/blob/master/src/Microsoft.AspNetCore.WebUtilities/BufferedReadStream.cs solves that. It would be great if you could make the class public so I don't need copy it.

_Copied from original issue: aspnet/HttpAbstractions#932_

**Comment by Tornhoof** [comment]
@tratcher Do you accept a pull request for that? Is anything more required than just changing the source from internal to public? Changes to docs?
(I stumbled across this bug again, because there are bugfixes in the above stream since the last time I copied the source around).

**Comment by Tratcher** [comment]
Yes it would need doc comments. Otherwise making it public would be harmless, go ahead and prep a PR.

**Comment by Tornhoof** [comment]
Added pull request https://github.com/aspnet/HttpAbstractions/pull/1011 to make it public and add doc comments.
