### ISSUE TITLE
Flaky Test: FileBufferingReadStreamTests

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/Home#2703]
_From @halter73 on Friday, May 12, 2017 3:51:51 PM_

FileBufferingReadStreamTests.FileBufferingReadStream_AsyncReadWithOnDiskLimit_EnforcesLimit failed the Win10-Universe build.

http://aspnetci/viewLog.html?buildId=219344&tab=buildResultsDiv&buildTypeId=XPlat_Windows_Win10Universe

_Copied from original issue: aspnet/HttpAbstractions#836_

**Comment by aspnet-hello** [comment]
_From @ryanbrandenburg on Wednesday, July 12, 2017 3:01:26 PM_

http://aspnetci/viewLog.html?tab=buildLog&logTab=tree&filter=debug&expand=all&buildId=271026#_focus=15393 and http://aspnetci/viewLog.html?tab=buildLog&buildTypeId=Lite_UniverseTest&buildId=264823#_focus=17975 follow this pattern. Other tests on that component are likely to run into this as well.

**Comment by Eilon** [comment]
@muratg / @Tratcher - is this something worth investigating in 2.1.0-rc1 (i.e. possibly a product bug??), or move to 2.2.0-mq?

**Comment by muratg** [comment]
@Tratcher how bad do you think this is?

I'm leaning towards moving it to mq.

**Comment by Tratcher** [comment]
Move to MQ. This component hasn't changed since 1.0 so it's unlikely to be a product issue.

**Comment by halter73** [comment]
It also looks like it only failed twice in July 2017 and hasn't failed since. http://aspnetci/project.html?projectId=XPlat&buildTypeId=&tab=testDetails&testNameId=-7558878844871849032&order=TEST_STATUS_DESC&branch_XPlat=__all_branches__&itemsCount=50

**Comment by muratg** [comment]
Should we just close?

**Comment by muratg** [comment]
Closing. Looks like it was a temporary flakiness?
