### ISSUE TITLE
Consolidate all header parsing code 

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/Home#2705]
_From @muratg on Monday, April 24, 2017 3:17:12 PM_

Header parsing logic is used in

- MVC
- StaticFiles
- ResponseCaching

We should investigate the usages across the board and consolidate the code here.

_Copied from original issue: aspnet/HttpAbstractions#825_

**Comment by aspnet-hello** [comment]
_From @muratg on Monday, May 15, 2017 9:37:24 AM_

Tracking issues:

- [x] HttpAbstractions #758 
- [ ] ...

**Comment by aspnet-hello** [comment]
_From @Tratcher on Tuesday, May 23, 2017 2:56:24 PM_

@Eilon #758 is complete, next we need to investigate having MVC replace their implementation with this one.

**Comment by aspnet-hello** [comment]
_From @muratg on Thursday, May 25, 2017 3:53:44 PM_

@Eilon Moving the rest of the work to preview3.

**Comment by aspnet-hello** [comment]
_From @muratg on Tuesday, August 8, 2017 2:47:17 PM_

@Eilon could we do this in 2.1?

**Comment by aspnet-hello** [comment]
_From @Eilon on Tuesday, August 8, 2017 3:26:24 PM_

Yessss... @jkotalik is actually already working on some of this, starting with the toughest of them all: MediaType header value.

**Comment by aspnet-hello** [comment]
_From @jkotalik on Monday, October 16, 2017 12:13:17 AM_

@muratg @Eilon We added structured suffixes and facets to MediaTypeHeaderValue (MTHV) in HttpAbstractions. I was trying to modify MediaType in MVC to wrap MTHV, though it seemed non trivial and wouldn't have much benefit until we either remove MediaType or can deprecate it. What other header logic can be moved from StaticFiles/ResponseCaching to HttpAbstractions?

**Comment by aspnet-hello** [comment]
_From @muratg on Monday, October 16, 2017 9:41:56 AM_

I think we can deprecate MediaType. @Eilon thoughts?

**Comment by aspnet-hello** [comment]
_From @Tratcher on Monday, October 16, 2017 9:42:37 AM_

@jkotalik the idea is to at least remove the duplicate code and have MediaType refer to MTHV. MediaType's code has already been the source of multiple critical bugs.

As for StaticFiles and ResponseCaching you'll have to investigate yourself. Those components process lots of headers but they mostly use HttpAbstractions types to do it.

**Comment by aspnet-hello** [comment]
_From @rynowak on Monday, October 16, 2017 12:30:20 PM_

@javiercn did some research on obsoleting `MediaType` and I think his findings were promising. @javiercn do you remember what the conclusions were?

**Comment by aspnet-hello** [comment]
_From @rynowak on Monday, October 16, 2017 1:07:05 PM_

@javiercn just came by to express to me just how excited he is to share his wealth of knowledge and extensive notes in this area; alas, he had to go to an important meeting first.

**Comment by aspnet-hello** [comment]
_From @Eilon on Monday, October 16, 2017 8:31:00 PM_

I would only obsolete `MediaType` if we actually plan to get rid of it, say, in MVC 3.0. Would that be the plan?

**Comment by aspnet-hello** [comment]
_From @javiercn on Tuesday, October 17, 2017 9:55:18 AM_

We should have a design we are all happy with for 3.0 (one that allows efficient header non allocating iteration as a basic API and a richer strongly typed allocating API for convenience)

**Comment by aspnet-hello** [comment]
_From @Eilon on Tuesday, October 17, 2017 10:52:38 AM_

I set up a mtg for this for tomorrow. I invited @javiercn @muratg @jkotalik @rynowak @Tratcher .

**Comment by aspnet-hello** [comment]
_From @Eilon on Wednesday, October 18, 2017 2:20:44 PM_

Plan from the mtg:

* [ ] Change MediaType into a facade that just calls into MediaTypeHeaderValue
* [ ] Mark MediaType as obsolete
* [ ] Find all public exposure of MediaType in MVC, obsolete them, and make sure that there are non-obsolete alternatives
* [ ] Do basic before/after perf tests on MVC scenarios for conneg to assess whether there is a regression, and, if so, how much

**Comment by muratg** [comment]
Closing per @davidfowl's recommendation
