### ISSUE TITLE
SignOutAsync should take [] of AuthenticationSchemes

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/Home#2721]
_From @Tratcher on Monday, March 14, 2016 3:28:57 PM_

_From @rustd on March 14, 2016 22:22_

A user has to specify SignOut per authentication scheme as follows https://github.com/aspnet/Templates/blob/dev/src/Rules/StarterWeb/OrganizationalAuth/Single/Controllers/AccountController.cs#L24
With this change we will have the same code as in Katana

_Copied from original issue: aspnet/Security#742_

_Copied from original issue: aspnet/HttpAbstractions#585_

**Comment by aspnet-hello** [comment]
_From @Tratcher on Monday, March 14, 2016 3:31:32 PM_

I don't think we need this, we had considered it as an intermediate design that didn't provide AuthProperties but opted for https://github.com/aspnet/Security/issues/743 instead.

**Comment by aspnet-hello** [comment]
_From @PinpointTownes on Monday, March 14, 2016 6:03:24 PM_

The syntax in MVC would be much better if https://github.com/aspnet/Mvc/pull/4259 was merged.

/cc @danroth27

**Comment by aspnet-hello** [comment]
_From @Tratcher on Saturday, July 8, 2017 9:14:53 PM_

@haok is this still relevant or can we close it? It looks like MVC is doing most of the work for us.

**Comment by HaoK** [comment]
Yeah we can close, MVC has a SignOut result that takes a list of schemes.  Its not very common to sign out multiple schemes at once anyways...
