### ISSUE TITLE
Support for shared projects in vNext projects

### ISSUE THREAD

**Issue by djanosik** [aspnet/Home#274]
Are there any plans to support shared project references in vNext projects?

**Comment by Eilon** [comment]
Hi, can you clarify what exactly you mean by shared project references? You can use `global.json` to share projects amongst different solutions, and you can use features of `project.json` to include source code from arbitrary locations into your project as well. Are you looking for something else?

**Comment by djanosik** [comment]
Hi, I am talking about [shared projects](http://www.c-sharpcorner.com/UploadFile/7ca517/shared-project-an-impressive-features-of-visual-studio-201/) introduced in VS 2015. As of now, they can't be referenced from vNext projects.

**Comment by Eilon** [comment]
Oh those look cool :smile:

I'm not sure exactly how these would interact with ASP.NET 5 projects because they are quite separate from MSBuild and have to exist outside of VS.

Adding @barrytang and @mayurid from the web tooling team, and @davidfowl from the runtime team.

**Comment by barrytang** [comment]
This is on our backlog.

**Comment by borgdylan** [comment]
If I am not mistaken you can already mark code as shared and have that included in all referencing projects.

**Comment by djanosik** [comment]
I sees it's now possible to reference *.csproj from *.kproj. That's all I need right now :) Thank you!
