### ISSUE TITLE
Remove code not shipping in 2.1 release

### ISSUE THREAD

**Issue by mkArtakMSFT** [aspnet/Home#2741]
There was some Dispatcher related code introduced to the routing repo, as part of a feature which was pushed out. So that code needs to be taken out.
@rynowak, can you please provide details about exactly should be removed?

**Comment by natemcmaster** [comment]
Just FYI - as an alternative to deleting the code altogether, you can just prevent it from ending up in a NuGet package by setting this property in the csproj file.
```xml
<IsPackable>false</IsPackable>
```
We've done this in other repos where half-baked coded wasn't finished in time for a release.

**Comment by jbagga** [comment]
@rynowak Since some Routing APIs now depend on stuff in the Dispatcher projects, will it be safe to just add <IsPackable>false</IsPackable> to Dispatcher projects?

@natemcmaster Is there a way to test if things will be broken or not if some projects are NuGet packages and others aren't?

**Comment by natemcmaster** [comment]
You would need to remove these packages from this list:
https://github.com/aspnet/Universe/blob/dev/build/artifacts.props#L63-L64

You can verify this works in universe by doing the following:

1. `git clone --recursive https://github.com/aspnet/Universe`
2. Edit modules/Routing to remove the dispatcher packages)
3. Run `build.cmd /t:ComputeGraph` in universe. This will examine all projects to ensure the graph of package dependencies is correctly defined.

**Comment by rynowak** [comment]
> Just FYI - as an alternative to deleting the code altogether, you can just prevent it from ending up in a NuGet package by setting this property in the csproj file.

This is not going to work. Routing now has a dependency on Dispatcher, that part needs to be reverted.
