### ISSUE TITLE
The remote party closed the WebSocket connection without completing the close handshake

### ISSUE THREAD

**Issue by hscanlan** [aspnet/Home#2742]
I have a WebSocket middleware in a .NET CORE 2.0.1 WebAPI project. 

I have a separate "FrontEnd" project, which connects fine and allows messages to be passed back and forth easily.

I want to be able to send messages from my Controller to my site, so I extended my WebSocketHandler and created an abstract RecieveAsync method to override and then call via my controller.

Everything works as expected, UNTIL the page is refreshed or the client leaves and comes back.

The error comes from the await SendMessageAsync(value, message) function. The website says the connection is successful on refresh / return, but the API Middleware throws the below error.

{System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake. ---> System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'FrameResponseStream'.
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.FrameResponseStream.ValidateState(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.FrameResponseStream.WriteAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.FrameDuplexStream.WriteAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at System.Net.WebSockets.ManagedWebSocket.SendFrameLockAcquiredNonCancelableAsync(MessageOpcode opcode, Boolean endOfMessage, ArraySegment`1 payloadBuffer)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at API.WebSocketHandler.<SendMessageAsync>d__7.MoveNext() in C:\Projects\API\API\WebSocketManager\WebSocketHandler.cs:line 35
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at API.WebSocketHandler.<SendMessageToAllAsync>d__9.MoveNext() in C:\Projects\API\API\WebSocketManager\WebSocketHandler.cs:line 62}

WebSocketHandler:
`using CryptoGameAPI.Models.Game;
using Newtonsoft.Json;
using System;
using System.Net.WebSockets;
using System.Text;
using System.Threading;
using System.Threading.Tasks;

namespace CryptoGameAPI
{
    public abstract class WebSocketHandler
    {
        protected WebSocketConnectionManager WebSocketConnectionManager { get; set; }

        public WebSocketHandler(WebSocketConnectionManager webSocketConnectionManager)
        {
            WebSocketConnectionManager = webSocketConnectionManager;
        }

        public virtual async Task OnConnected(WebSocket socket)
        {
            WebSocketConnectionManager.AddSocket(socket);
        }

        public virtual async Task OnDisconnected(WebSocket socket)
        {
            await WebSocketConnectionManager.RemoveSocket(WebSocketConnectionManager.GetId(socket));
        }

        public async Task SendMessageAsync(WebSocket socket, string message)
        {
            if (socket.State != WebSocketState.Open)
                return;

            await socket.SendAsync(buffer: new ArraySegment<byte>(array: Encoding.ASCII.GetBytes(message),
                                                                  offset: 0,
                                                                  count: message.Length),
                                   messageType: WebSocketMessageType.Text,
                                   endOfMessage: true,
                                   cancellationToken: CancellationToken.None);
        }

        public async Task SendMessageAsync(string socketId, string message)
        {
            try
            {
                await SendMessageAsync(WebSocketConnectionManager.GetSocketById(socketId), message);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        public async Task SendMessageToAllAsync(string message)
        {
            try
            {

                foreach (var pair in WebSocketConnectionManager.GetAll())
                {
                    if (pair.Value.State == WebSocketState.Open)
                        await SendMessageAsync(pair.Value, message);
                }

            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        public abstract Task ReceiveAsync(WebSocket socket, WebSocketReceiveResult result, byte[] buffer);
    }
}`

The override:
`using API.Models.Game;
using Newtonsoft.Json;
using System.Net.WebSockets;
using System.Text;
using System.Threading.Tasks;

namespace API
{
    public class MessageHandler : WebSocketHandler
    {
        public MessageHandler(WebSocketConnectionManager webSocketConnectionManager) : base(webSocketConnectionManager)
        {
        }

        public override async Task OnConnected(WebSocket socket)
        {
            await base.OnConnected(socket);

            var socketId = WebSocketConnectionManager.GetId(socket);
            await SendMessageToAllAsync($"{socketId} is now connected");
        }

        public override async Task ReceiveAsync(WebSocket socket, WebSocketReceiveResult result, byte[] buffer)
        {
            var socketId = WebSocketConnectionManager.GetId(socket);
            
            var message = $": {Encoding.UTF8.GetString(buffer, 0, result.Count)}";

            var cmhm = new MessageHandlerModel();
            cmhm.MessageType = "Chat";
            cmhm.Message = message;

            string json = await Task.Run(() => JsonConvert.SerializeObject(cmhm));
            await SendMessageToAllAsync(json);
        }
    }
}`

How I'm sending the message from the controller:

`
        [HttpGet]
        public async Task SendMessage([FromQueryAttribute]CryptoMessageHandlerModel cmhm)
        {
            string json = await Task.Run(() => JsonConvert.SerializeObject(cmhm));
            await _cryptoMessageHandler.SendMessageToAllAsync(json);
        }
`

**Comment by hscanlan** [comment]
Any help here would be appreciated. It's really causing an issue in one of my web projects

**Comment by davidfowl** [comment]
@hscanlan any info on this?

**Comment by moshegutman** [comment]
Is there an update on this?

**Comment by anurse** [comment]
We didn't get any more information after my earlier request for more context. I'm going to close this as we haven't been able to reproduce the issue or get enough information to help identify the problem.

@moshegutman If you're seeing a similar issue, can you file a new bug, include a reproducible code sample and tag me in it? As I requested above, please make sure to include the code where you're accepting the WebSocket.

You have to keep the request running while the WebSocket is open, so if you pass the WebSocket off to a background process, it's essential to make sure you block the request task from completing until you're finished with the WebSocket.
