### ISSUE TITLE
DataProtection version issue: The provided payload cannot be decrypted because it was not protected with this protection provider.

### ISSUE THREAD

**Issue by johnrutherford** [aspnet/Home#2744]
I'm having an issue that appears to be similar to this one: 
https://github.com/aspnet/DataProtection/issues/187

We recently upgraded an ASP.NET Core 1.1 application (targeting the .NET Framework 4.6.1) to ASP.NET Core 2. 

We have started getting this error message in our logs:

```
The provided payload cannot be decrypted because it was not protected with this protection provider.
```

I've looked at the keys our application is using and they contain this, which I think may be the problem:

``` xml
<descriptor deserializerType="Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel.AuthenticatedEncryptorDescriptorDeserializer, Microsoft.AspNetCore.DataProtection, Version=1.1.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60">
```

**Comment by BrennanConroy** [comment]
If you follow the links in the issue you linked, it eventually leads to https://github.com/aspnet/DataProtection/issues/265#issuecomment-325438923
Where we back-ported a fix from 2.0 to 1.1.3 version of DataProtection.
Not sure what the best practice here is, can you upgrade to 1.1.3 before upgrading to 2.0, and try to encrypt everything?

**Comment by johnrutherford** [comment]
We have already completed the upgrade to 2.0. We would not be able to downgrade to 1.1.3 and then upgrade again to 2.0.

At this point, the existing keys are not working anyway.... So maybe just clearing them out and restarting the applications is the simplest way to go forward. Or could I just edit the key files and change the version number?

**Comment by blowdart** [comment]
If you're not concerned you could just delete the entire keyring. Editing would probably work unless someone changed the class names or structures.

@natemcmaster that patch should work though shouldn't it? It should have pulled 1.x up to 2.x, or at least that's what I'd hoped.

**Comment by BrennanConroy** [comment]
@blowdart They were using 1.1.2, the patch with the fix was 1.1.3

**Comment by blowdart** [comment]
Yes but @johnrutherford says they moved to 2.0, which had the patch, right? So it should have not thrown an error.

**Comment by natemcmaster** [comment]
https://github.com/aspnet/DataProtection/issues/187 was included in 2.0.0. @johnrutherford can you provide a repro? Here is the minimal repro I used to validate this fix when we backported the fix to 1.1.3. https://gist.github.com/natemcmaster/7dfb37813a3024f228971ea89188dfde

**Comment by johnrutherford** [comment]
I have been unable to reproduce this issue in isolation, so I'm thinking the problem isn't with the version. Unfortunately, the full exception is not being logged. Just the exception message, so I don't have much to go on.

**Comment by blowdart** [comment]
If we can't get a repo, there's not much we can do unfortunately. If it repos again please reopen this issue.
