### ISSUE TITLE
Why Cors AddPolicy doesn't allow *.example.com ?

### ISSUE THREAD

**Issue by jkotas** [aspnet/Home#2745]
_From @AhmedRagheb on January 5, 2018 13:58_

Hello,

Is there a reason (security may be) that prevent Cors AddPolicy from adding all subdomains of my domain in Origins list. As I think it doesn't make sense to add all my subdomains to the Origins list.

Thanks.

_Copied from original issue: dotnet/coreclr#15753_

**Comment by jkotas** [comment]
This belongs to https://github.com/aspnet/CORS repo

**Comment by jkotas** [comment]
This issue was moved to aspnet/CORS#140

**Comment by AhmedRagheb** [comment]
Any updates or explanation regarding this?

**Comment by JulijaRamoskiene** [comment]
Try prefixing with schema -"http://*.example.com"

**Comment by blowdart** [comment]
See https://github.com/aspnet/CORS/issues/75 and https://github.com/aspnet/CORS/pull/94 for why we ended up not supporting wildcards and instead gave you a function you can use.

**Comment by pranavkm** [comment]
Closing since this question has been answered.
