### ISSUE TITLE
Add support for CancellationTokens in AuthorizationHandler

### ISSUE THREAD

**Issue by symlynk** [aspnet/Home#2746]
The following methods are missing CancellationToken parameters in Microsoft.AspNetCore.Authorization.AuthorizationHandler:

```
public virtual Task HandleAsync( AuthorizationHandlerContext context );
protected abstract Task HandleRequirementAsync( AuthorizationHandlerContext context, TRequirement requirement );
```
Microsoft.AspNetCore.Authorization Version 2.0.1.0

**Comment by Eilon** [comment]
This issue was moved to aspnet/Security#1598

**Comment by yngndrw-sage** [comment]
Should this issue be re-opened now that Security has come back to this repository ?
