### ISSUE TITLE
Review naming of ITrackingConsentFeature and CanTrack

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Home#2750]
@blowdart @DamianEdwards 
https://github.com/aspnet/HttpAbstractions/blob/6558c2bd07dc3e40c477a33ee0ec4663a8ff81a7/src/Microsoft.AspNetCore.Http.Features/ITrackingConsentFeature.cs
https://github.com/aspnet/templating/pull/213/files

**Comment by muratg** [comment]
@blowdart Did you get a chance to look at the API naming here?  This one good to close?

**Comment by blowdart** [comment]
Pretty sure we discussed this in triage a couple of months back, yes, consent is what the GDPR calls it, so it's fine.

**Comment by Tratcher** [comment]
It was the words track/ing you were concerned about, not consent.

**Comment by khellang** [comment]
> Indicates either if consent has been given or if consent is not required.

Based on the documentation, it seems like the `CanTrack` property is redundant. `IsConsentNeeded` and `HasConsent` [already covers this](https://github.com/aspnet/Security/blob/9839799645a1110990a5fa5fb8ce060566a0e39e/src/Microsoft.AspNetCore.CookiePolicy/ResponseCookiesWrapper.cs#L65):

> IsConsentNeeded - Indicates if consent is required for the given request.

> HasConsent - Indicates if consent was given.

If the name is problematic, you could consider removing the property and implement it as a pubternal extension method instead?

**Comment by Tratcher** [comment]
Yes and no. CanTrack is the field most applications need, rather than having to check both HasConsent and IsConsentNeeded every time.
https://github.com/aspnet/templating/blob/eabde9fe9e0efb71fd8eb6ff1cc709743d06320d/src/Microsoft.DotNet.Web.ProjectTemplates/content/StarterWeb-CSharp/Views/Shared/_CookieConsentPartial.cshtml#L5

**Comment by blowdart** [comment]
I can't think of anything better unfortunately. 

CanDropIdentifyingCookie would be accurate, but stupidly long.

**Comment by muratg** [comment]
Let's make a decision and move on. What are the "OKish" options? We can run those with @DamianEdwards et al and get a decision quick.

**Comment by Eilon** [comment]
Time is running out to make a decision for preview2. Do we plan to change this in preview2, or wait for rc1?

**Comment by DamianEdwards** [comment]
Haven't heard any better suggestions, thus we stay with what we have.

**Comment by Eilon** [comment]
@muratg / @DamianEdwards / @Tratcher - so do we close this bug? Or move to RC1?

**Comment by muratg** [comment]
Closing per Damian's latest comment. If anyone strongly thinks that we should rename anything here, file a bug for RC1.
