### ISSUE TITLE
Question: Providing fallback for options factory

### ISSUE THREAD

**Issue by arishlabroo** [aspnet/Home#2752]
PS: This is a question, not a bug. Please close if not appropriate to ask here.

I have many configurations, and I end up doing this a lot
`services.Configure<FooBoo>(configuration.GetSection("FooBoo"));`

where `configuration` is always the root, and section name always matches the class name .

To try to automate this I looked here https://github.com/aspnet/Options/blob/dev/src/Microsoft.Extensions.Options/OptionsFactory.cs
and implemented a decorator for the options factory like below
```
public class OptionsFactoryDecorator<TOptions> : IOptionsFactory<TOptions> where TOptions : class, new()
{
    private readonly IEnumerable<IConfigureOptions<TOptions>> _setups;
    private readonly IEnumerable<IPostConfigureOptions<TOptions>> _postConfigures;
    private readonly IOptionsFactory<TOptions> _optionsFactory;
    private readonly IConfiguration _configuration;

    public OptionsFactoryDecorator(
        IOptionsFactory<TOptions> optionsFactory,
        IEnumerable<IConfigureOptions<TOptions>> setups,
        IEnumerable<IPostConfigureOptions<TOptions>> postConfigures,
        IConfiguration configuration)
    {
        _optionsFactory = optionsFactory;
        _setups = setups;
        _postConfigures = postConfigures;
        _configuration = configuration;
    }

    public TOptions Create(string name)
    {
        if (name != Options.DefaultName || _setups.Any() || _postConfigures.Any())
        {
            return _optionsFactory.Create(name);
        }
        var options = new TOptions();
        _configuration.GetSection(typeof(TOptions).Name).Bind(options);
        return options;
    }
}
```
And just using structuremap as an example, i can simply do
`registry.For(typeof(IOptionsFactory<>)).DecorateAllWith(typeof(OptionsFactoryDecorator<>));
`

And everything works 😱 . I dont need any 
`services.Configure<FooBoo>(configuration.GetSection("FooBoo"));`

Is there a reason why I should absolutely not do it?

**Comment by Eilon** [comment]
@ajcvickers - triage.

**Comment by ajcvickers** [comment]
@HaoK Can you take a look at this question?

**Comment by HaoK** [comment]
@arishlabroo this looks reasonable to me, glad to see the new extensibility point is useful :)
