### ISSUE TITLE
Unable to start Asp.Net Core 2.0 app in Debug Mode

### ISSUE THREAD

**Issue by ajayak** [aspnet/Home#2754]
On running the Asp.Net Core 2.0 app in Visual Studio 2017, I get the following error in the Output window:

>The program '[10088] dotnet.exe: Program Trace' has exited with code 0 (0x0).
The program '[10088] dotnet.exe' has exited with code -42 (0xffffffd6).
The program '[4636] chrome.exe: WebKit' has exited with code -1 (0xffffffff).

Output from `dotnet --info`
```
.NET Command Line Tools (2.1.3)

Product Information:
 Version:            2.1.3
 Commit SHA-1 hash:  a0ca411ca5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.3\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.4
  Build    : 7f262f453d8c8479b9af91d34c013b3aa05bc1ff
```

I am able to run the application using `Ctrl+F5` without any issue.

**Comment by Eilon** [comment]
Hi @ajayak , can you set VS to catch all CLR exceptions and run with <kbd>F5</kbd> again?
![image](https://user-images.githubusercontent.com/202643/34731566-874b03de-f517-11e7-82f8-0d60de55ae39.png)

**Comment by ajayak** [comment]
Hi @Eilon,
I realized that the error I have is not a CLR error. Thanks for the suggestion 👍
