### ISSUE TITLE
Why services.AddTransient<ISessionStore, DistributedSessionStore>() ?

### ISSUE THREAD

**Issue by rjamesnw** [aspnet/Home#2755]
Why is this code in the source (`SessionServiceCollectionExtensions.cs`):

`services.AddTransient<ISessionStore, DistributedSessionStore>();`

and not this instead?

`services.TryAddTransient<ISessionStore, DistributedSessionStore>();`

I have to use a minor work-around to inject my own 'ISessionStore', so this seems inconsistent to how other items get registered.  Typically I've been seeing the later used throughout the Asp.Net Core libraries (using "Try" to better allow others to inject their own types). Is this an oversight? It makes no sense, since I can simple call `AddSession()`, then register my type immediately after to override instead of before it (which forces types to get added, and not good if I want others to be able to easily inject as well).

**Comment by Eilon** [comment]
@muratg - triage.

**Comment by muratg** [comment]
@Tratcher Any thoughts here?

**Comment by Tratcher** [comment]
We haven't been consistent about using Try to add services across the stack. If Try is the recommendation then we'd want to scrub the whole org.

**Comment by muratg** [comment]
This would be a breaking change, so putting this in 3.0.0.

**Comment by Eilon** [comment]
How is this a breaking change? It'll just throw exceptions less often, no?

**Comment by muratg** [comment]
It's about about changing the extension method's name (and behavior around exceptions). Unfortunately we're not consistent around these extension methods across our components.

**Comment by Eilon** [comment]
This isn't about changing any method's name... it's about changing the code to call a different already-existing method.

**Comment by muratg** [comment]
My bad, you're right. @Tratcher can you please take a look to see if this was just an oversight and not by-design?

**Comment by Tratcher** [comment]
It's an oversight. We didn't have any fixed guidance when this component was written.

**Comment by rjamesnw** [comment]
I figured as much.  I've been reviewing the other sources while working on a web app (injected some of my own types) and this is the first time (so far) I saw it forced. ;)
