### ISSUE TITLE
csrf antiforgery token not refreshed automatically on logout\login

### ISSUE THREAD

**Issue by guylando** [aspnet/Home#2757]
I noticed that the net core csrf token is not refreshed automatically on logout\login. Is it the correct behaviour?
Are we supposed to refresh the csrf token manually on login? on logout? What is the correct way to refresh it? Just clear the cookie and thats it? Should do it in ConfigureApplicationCookie events OnSigningIn, OnSigningOut?

**Comment by blowdart** [comment]
@HaoK @Tratcher @rynowak this appears to span both cookie security and anti-forgery. Unsure where to put it.

**Comment by Tratcher** [comment]
Start with Templating?

**Comment by Eilon** [comment]
@blowdart - did you want to schedule a meeting for this? Or maybe we can discuss in Security triage?

**Comment by Eilon** [comment]
@blowdart - thoughts on what we should do with this issue?

**Comment by blowdart** [comment]
Honestly this should work otherwise lots of people would be broken. Unless it's in a SPA, in which case, we've documented that. As no-one else has reported it, close?

**Comment by Eilon** [comment]
Closing. Here's the doc if anyone is looking for it: https://docs.microsoft.com/en-us/aspnet/core/security/anti-request-forgery?view=aspnetcore-2.1#javascript-ajax-and-spas

**Comment by collinsauve** [comment]
Came across this as we were auditing our CSRF implementation and found that the antiforgery token is not regenerated on logout/login. 

> Honestly this should work otherwise lots of people would be broken. Unless it's in a SPA, in which case, we've documented that. As no-one else has reported it, close?

They wouldn't be "broken" they would just have a suboptimal security configuration.  Many teams would not know to look for this and wouldn't report it.

(re: SPA we use antiforgery on our authorization server but not in our SPA clients)

**Comment by collinsauve** [comment]
Seems like this was an inappropriate closure with just "should work".

Should I create a new issue for this to get some traction on it?

**Comment by mtinnes** [comment]
Please re-open, we have a requirement to regen the token which is still not happening on logout. The existing token needs to be expired on logout.

**Comment by Tratcher** [comment]
Comments on closed issues are not tracked, please open a new issue with the details for your scenario.
