### ISSUE TITLE
The CLI SDK installer fails to properly generate the ASP.NET HTTPS certificate

### ISSUE THREAD

**Issue by javiercn** [aspnet/Home#2758]
This is mostly likely due to the installer running with a different scope.

This is a tracking issue for our HTTPS work.

**Comment by Eilon** [comment]
@javiercn what repo is this work in?

**Comment by javiercn** [comment]
The CLI, there's a PR already out for it

**Comment by javiercn** [comment]
https://github.com/dotnet/cli/pull/8356

**Comment by Eilon** [comment]
Ok... wondering why we need a bug here to track it?

**Comment by javiercn** [comment]
Fix got checked-in https://github.com/dotnet/cli/commit/a212d5a0176f85e5aba9b117b1b408c5b60ee525
