### ISSUE TITLE
PowerShell scripts should never use command aliases

### ISSUE THREAD

**Issue by bradwilson** [aspnet/Home#276]
It is common for users to override command aliases like "cd" or "md". All PowerShell scripts which are for general distribution should use the built-in command names.

For example, kvm.ps1 uses `md SomeFolder | out-null` a lot, but this will conflict with anybody overriding this alias. Instead, it should be doing `New-Item -type Directory SomeFolder | out-null`.

**Comment by Eilon** [comment]
@anurse our resident PowerShell expert. An alternative would be to switch to BAT files and then `cd` and `md` are "perfectly safe" :wink:

**Comment by jbrinkman** [comment]
That is a little like suggesting that DOS is an alternative to Windows 10. :wink:

**Comment by anurse** [comment]
I agree with @bradwilson here. The only reason I haven't sent a PR to do this yet is that I haven't had time :). @Eilon, feel free to put this on my RC queue

**Comment by jbrinkman** [comment]
I'll see about submitting a PR tonight for this (at least one or two .ps1 files).

**Comment by anurse** [comment]
:+1: - FYI, kvm actually lives at [aspnet/kvm](https://github.com/aspnet/kvm). So you should probably send the PR there.

**Comment by jbrinkman** [comment]
Will do.

**Comment by anurse** [comment]
@jbrinkman - I'm doing some fairly major overhauling to kvm in order make it a little easier to manage (right now, for example, adding a new command requires a lot of work). I can just do this while I go through that process :).

**Comment by jbrinkman** [comment]
That is fine.  I got distracted by some last minute issues that had to be resolved before our DNN release today.  It’s like some of these bugs wait until you are packaging up the final release before they become visible ☹

Thanks,
Joe Brinkman
Co-Founder, VP of Technology and Community Relations
DNN Corp. | www.dnnsoftware.com<http://www.dnnsoftware.com/>
o 650.288.3154 | m 330.242.7742
Twitter <https://twitter.com/jbrinkman> | Facebook <https://www.facebook.com/joe.brinkman> |  LinkedIn  <http://www.linkedin.com/in/joebrinkman/> | Google+<https://plus.google.com/u/0/102047675986512918810/posts> | DNN<http://www.dnnsoftware.com/Activity-Feed/userId/8129>
