### ISSUE TITLE
Release notes on 2.0.5 as well as azure deployment timeline

### ISSUE THREAD

**Issue by niemyjski** [aspnet/Home#2763]
I noticed the release notes for 2.0.5 are still not out. Also can you please give some guidance on release time frames for the run times / meta packages to get onto azure? That's not really known each release and pretty annoying considering we choose the meta package but get penalized for it.

**Comment by Tratcher** [comment]
Azure rollout and corefx release notes: https://github.com/Azure/app-service-announcements/issues/72

**Comment by Tratcher** [comment]
@danroth Asp.Net release notes? Or is it constrained to https://github.com/aspnet/Announcements/issues/284 and https://github.com/aspnet/Announcements/issues/285?

**Comment by niemyjski** [comment]
But generally speaking, wish there was a level of expectation documented
like, we released these details on CVES but you Gotta wait X period of time
before they are deployed. Seems bad the changes aren't live when the
announcement takes place. You are left wide open and can't deploy because
the runtime is out of date.

Thanks
-Blake Niemyjski

**Comment by Eilon** [comment]
BTW I heard that the Azure deployments should be complete in all regions by tomorrow morning. Not sure *which* morning, but presumably somewhere on Earth 😄 

I forwarded your concerns to our release experts so that we can aim to be more transparent in the future. Sorry you ran into issues with this!

**Comment by Eilon** [comment]
This should all be live now, so closing.
