### ISSUE TITLE
Asp.Net Core 2.0.5 performance issue

### ISSUE THREAD

**Issue by masums** [aspnet/Home#2768]
I had developed a website using Asp.Net Core 2.0.0 with pomelo MySql driver. That takes 300 - 500 ms for rendering home page. Whenever I have upgraded Asp.Net Core 2.0.0 to 2.0.3 then it has taken average 450 ms to 750 ms to render the same page. Now, whenever I have upgraded to Asp.net core 2.0.5 then it is taking 800 ms to 1.3 seconds to render the same page with same database and data in the same environment. The interesting thing is again whenever I revert back to asp.net core 2.0.0 then again same page at same environment takes 300-500 ms to render the page. So is there have any known issues or I am missing something?

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, could you please provide us with a minimalistic repro project that illustrates the problem?

**Comment by masums** [comment]
Now waiting for version 2.1.0 if we still fetch this performance issue at version 2.1.0 then we will let you know that.

**Comment by sebastienros** [comment]
When you upgrade versions, I assume you only reference different ASP.NET packages? Are you using the .All metapackage? If not can you provide the list of packages and their versions for each of your tests?
