### ISSUE TITLE
Complete example of the correct order of middleware

### ISSUE THREAD

**Issue by guylando** [aspnet/Home#2769]
I can't find an example which shows what is the correct order for all the following middleware when used together. It would be nice if there would be a maintained startup.cs containing ALL possible middleware.

UseStatusCodePagesWithRedirects
UseStaticFiles
UseAuthentication
UseResponseCaching
UseWebSockets
UseSignalR
UseResponseCompression
UseMvc

Would save a lot of time and errors having it. 
Thanks!

**Comment by Tratcher** [comment]
There is no definitive order, only some relative dependencies between individual components. E.g. StatusCodes should come before components that generate responses without bodies. StaticFiles are often early in the pipeline for efficiency, there can be a lot of them. Auth should come before components that require auth, like MVC. Caching should come before components that generate cacheable responses like MVC. WebSockets should come before components that use them like SignalR. Compression should come before components that generate compressable responses, and after caching if you want to cache the compressed version.

Maybe what we need to explain is if a middleware handles requests as they arrive, or if it inserts itself to react to responses as they're generated. E.g. caching and compression attach to a request as it comes in and monitor the response to see if they need to react.

**Comment by guylando** [comment]
Thanks, Maybe a dependency tree\graph can be built\maintained instead of one startup.cs because the possibilities are better described in a tree\graph than in a linear code?

**Comment by Tratcher** [comment]
Even a table might help as a quick reference:

Middleware | Ordering
---------------|----------
UseStatusCodePagesWithRedirects | Before components that set status codes
UseStaticFiles | Terminal if a request matches files
UseAuthentication | Before HttpContext.User is needed. Terminal for OAuth callbacks.
UseResponseCaching | Before components that want caching
UseWebSockets | Before components that want to use WebSockets
UseSignalR | Terminal for matching routes / hubs
UseResponseCompression | Before components that want to use compression
UseMvc | Terminal if a request matches routes / controllers & actions

**Comment by Tratcher** [comment]
This issue was moved to aspnet/Docs#5172
