### ISSUE TITLE
Route not matched for specific route variable value

### ISSUE THREAD

**Issue by jamieide** [aspnet/Home#2772]
My ASP.NET Core 2 app is not matching a route for a specific variable in the path. I have been unable to reproduce this outside of the project it occurs in, or with any other values for the variable.

The route below is not matched when the tenant is "evt".
```
 routes.MapRoute(
    name: "tenant",
    template: "{tenant}/{controller}/{action}/{id?}");
```
Log entries for the failed and successful matches:
Request starting HTTP/1.1 GET http://localhost:44314/evt/projects/index  
The request path  does not match a supported file type
Request did not match any routes.

Request starting HTTP/1.1 GET http://localhost:44314/es/projects/index  
The request path /es/projects/index does not match a supported file type
Request successfully matched the route with name 'tenant' and template '{tenant}/{controller}/{action}/{id?}'.

Request starting HTTP/1.1 GET http://localhost:44314/wtfwtf/projects/index  
The request path /wtfwtf/projects/index does not match a supported file type
Request successfully matched the route with name 'tenant' and template '{tenant}/{controller}/{action}/{id?}'.

I set up an IRouter implementation that simply wraps routes.DefaultHandler and the RouteAsync method is not hit for the failing URL, it is for all others. The log message from the StaticFileMiddleware
The request path  does not match a supported file type 
for the failing request is missing the path, which I'm sure is a clue but I don't know how to troubleshoot further.

**Comment by Eilon** [comment]
@jamieide sorry you're running into this issue. Can you share some more of your code, such as your full route configuration, and your custom `IRouter` implementation?

**Comment by jamieide** [comment]
I now know what's causing it but I don't know how to fix it. In the web project's properties page on the Debug tab, there is an entry for App URL. If I change that to a URL that should match my route, for example https://localhost:44314/abc/projects/index and run the app, that URL returns 404. Even when I change it back to https://localhost:44314/, any URL that I had previously entered and run continues to return 404. The corresponding entry in launchSettings.json changes as expected and there's nothing unusual there. I've searched the project, file system, and registry but I can't locate where that entry is being stored. Note that I do have SSL enabled for this project.

I assumed that the App URL entry was to allow me to start debugging at any URL so that I don't have to navigate to it every time but maybe I'm misusing it.

@Eilon That is my full route configuration. The custom IRouter I mentioned was a temporary troubleshooting step that simple wrapped the default IRouter to allow me to hit breakpoints. I have commented out everything except services.AddMvc and app.UseMvc for troubleshooting.

**Comment by jamieide** [comment]
I can easily repro this issue on my machine with VS 15.5.3.

1. Create a new empty .NET Core web project
2. Modify Startup.cs to 

        public void ConfigureServices(IServiceCollection services)
        {
            services.AddMvc();
        }
        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            app.UseMvc(routes =>
                routes.MapRoute(
                    name: "tenant",
                    template: "{tenant}/{controller}/{action}/{id?}")
            );
        }

3. Create a Controller and Index action
4. Run app and verify that you can access routes such as http://localhost:56808/abc/mycontroller/index
5. Stop app, open the project properties > Debug tab, and change App URL to the URL you just visited (http://localhost:56808/abc/mycontroller/index)
6. Run app and verify that URL now returns 404
7. Stop app and change App URL back to http://localhost:56808/
8. Run app and verify that URL continues to return 404

**Comment by jamieide** [comment]
Deleting the .vs folder fixes the issue but that's a "sledgehammer" solution. I assume this is a bug and I'm interested to learn the root cause.

**Comment by Eilon** [comment]
@mkArtakMSFT - please triage.

**Comment by Eilon** [comment]
@jamieide thanks for the extra details, we will investigate (BTW sorry for the delay - 3 day holiday weekend in the US!).

**Comment by mkArtakMSFT** [comment]
@rynowak, can you please look into this? Thanks!

**Comment by rynowak** [comment]
I can confirm that this is an issue in the latest internal VS I have as well as 15.5.X.

**Comment by rynowak** [comment]
@mkArtakMSFT @Eilon - this is a VS tooling issue and unrelated to routing.

The applicationhostconfig has the wrong base path value after completing step 7 of the repro steps.

**Comment by Eilon** [comment]
@rynowak would it make sense to log a bug in TFS for this?

**Comment by rynowak** [comment]
Yeah I think that makes the most sense, I've already vetted these repro steps and talked to @BillHiebert - we just need an actual follow up

**Comment by rynowak** [comment]
Opened TFS bug 585940 to track this

**Comment by jamieide** [comment]
@rynowak There appears to be a regression because this happened to me again in v15.8.5. Let me know if you need any additional info, the steps listed above still repro it. Or perhaps it was never resolved, I obviously don't have visibility to the TFS for this.

**Comment by rynowak** [comment]
@BillHiebert - is there any update on this?

**Comment by jamieide** [comment]
@BillHiebert Thank you. I'm not sure why that didn't occur to me, the field is empty by default and I guess I just gravitated to the URL I saw.
