### ISSUE TITLE
Mvc.UseStaticFiles() will not serve files that are symbolic links; yielding empty files instead.

### ISSUE THREAD

**Issue by jhudsoncedaron** [aspnet/Home#2774]
Mvc.UseStaticFiles() will not serve files that are symbolic links; yielding empty files instead.

Reason: (new FileInfo(path)).Length does the wrong thing for what we are trying to do.

https://github.com/aspnet/FileSystem/blob/dev/src/FS.Physical/PhysicalFileInfo.cs:

    System.IO.FileInfo _info;

    public long Length => _info.Length;

Nope. That's not going to work.

Due to lack of an appropriate API, the only way to get the length is to open the file, seek to the end, and read the position.

**Comment by Tratcher** [comment]
Are there attributes that tell you if it's a symbolic link?

**Comment by jhudsoncedaron** [comment]
@Tratcher : Nope!

**Comment by Tratcher** [comment]
https://stackoverflow.com/questions/1485155/check-if-a-file-is-real-or-a-symbolic-link

**Comment by jhudsoncedaron** [comment]
Very good @Tratcher you made my point. Note that those are P/Invokes to Windows specific APIs. I am already preparing to write up a relatively large item describing a proposed interface for dealing with this design omission in System.IO.

**Comment by natemcmaster** [comment]
p/invoke isn't necessary on *nix machines. FileAttributes.ReparsePoint will be set on FileInfo.Attributes.

**Comment by muratg** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.
