### ISSUE TITLE
Broken symlinks return HTTP 500 instead of HTTP 404

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/Home#2775]
Repro:
```
dotnet new mvc
ln -s doesnotexists.txt wwwroot/test.txt
dotnet run
```
http://localhost:5000/test.txt

**Expected**
HTTP 404. This file does not exist

**Actual**
HTTP 500
```
FileNotFoundException: Could not find file '/private/tmp/symlink/wwwroot/test.txt'.
Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, string path, bool isDirectory, Func<ErrorInfo, ErrorInfo> errorRewriter)
Microsoft.Win32.SafeHandles.SafeFileHandle.Open(string path, OpenFlags flags, int mode)
System.IO.FileStream..ctor(string path, FileMode mode, FileAccess access, FileShare share, int bufferSize, FileOptions options)
Microsoft.Extensions.FileProviders.Physical.PhysicalFileInfo.CreateReadStream()
```

**details**
macOS
```
<PackageReference Include="Microsoft.AspNetCore.All" Version="2.1.0-preview1-28042" />
```

**Comment by glennc** [comment]
The idea here would be to catch the FileNotFound on open and do the same as if File.Exists was false (calling next).

**Comment by muratg** [comment]
@stephentoub Any thoughts on this?

**Comment by stephentoub** [comment]
> Any thoughts on this?

I'm not clear on what the problem is.  What's the question?

**Comment by muratg** [comment]
@stephentoub `FileStream` throwing `FileNotFoundException` for a symbolic link instead of opening it. I was wonderingif this is by design, compatible across OSes, etc.

**Comment by stephentoub** [comment]
The symlink is broken, meaning it points to something that doesn't exist?  If so getting a FileNotFoundException for it is by design; that's true across OSes, is the behavior for .NET Framework on Windows, etc.

**Comment by muratg** [comment]
@stephentoub thanks for verifying!

@natemcmaster I think catching FileNotFound and ignoring it (with a trace?) should fix this.

**Comment by Tratcher** [comment]
Ignoring it would take a little more work than catching the exception. This happens long after File.Exists checks so components have already acted on it. E.g. StaticFiles has set response headers and is ready to write the body. PhysicalFileProvider can't catch the exception, StaticFiles and other consumers must. They'll have to be reorganized to react to a late failure.

**Comment by muratg** [comment]
Is there an API to check if a file is a symbolic link? If so, perhaps that must be called when `File.Exists` check is done?

**Comment by Tratcher** [comment]
Being a symlink isn't enough, you have to open it to know if it will succeed.

**Comment by muratg** [comment]
Sure, which can be done at the same spot right? Just trying to see how we can localize the fix as much as possible.

**Comment by natemcmaster** [comment]
@Tratcher has a better understanding on how to fix this. Apparently #232 was not sufficient.
