### ISSUE TITLE
.NET Core is missing suitable APIs for dealing with filesystems that contain symbolic links

### ISSUE THREAD

**Issue by jhudsoncedaron** [aspnet/Home#2776]
Ref: https://github.com/aspnet/Home/issues/2774 for discovery point

.NET Core is missing suitable APIs for dealing with filesystems that contain symbolic links

FileInfo does not resolve symbolic links, leading to subtle bugs. There's no API that gives information about the link target. There's other problems with the existing APIs causing them to have trouble when you call Directory.EnumerateFileSystemEntries involving having to do not one but two stat calls for each node. Might as well resolve them all at once.

Proposed API surface:

    // These are deliberately set to the *nix constant values where possible.
    public enum FileTypes {
          Missing = 0,
          Fifo = 0010000,
          CharacterDevice = 0020000,
          Directory = 0040000,
          BlockDevice = 0060000,
          File = 010000,
          SymbolicLink = 0120000,
          Socket = 0140000,
          ReparsePoint = 0200000, // ReparsePoint attribute set but not a symbolic link
    }

    public struct FileNode {
        public string Path { get; private set; }
        public string FileName { get => System.IO.Path.GetFileName(Path); }
        public DateTime LastAccessTime { get; private set; }
        public DateTime LastAccessTimeUTC { get; private set; }
        public DateTime LastWriteTime { get; private set; }
        public DateTime LastWriteTimeUTC { get; private set; }
        public DateTime LastChangeTime { get; private set; }
        public DateTime LastChangeTimeUTC { get; private set; }
        public FileAttributes Attributes { get; private set; }
        public FileTypes FileNodeType { get; private set; }
        public string ReadLink(); /* call the appropriate API */
        public bool Exists { get => FileNodeType != 0 }
        FileNode(string path, bool resolvesymboliclink)
        {
                /* The general idea of this API is it doesn't throw; just gives the appropriate information You could probably put Cer.Success on it. */
                Path = path;
                bool statpermissiondenied;
                if (resolvesymboliclink)
                {
                    /* This code path would call CreateFile with only FILE_READ_ATTRIBUTES and then call GetFileInformationByHandle; on AccessDenied or PermissionDenied fall through below */
                    /* on unix this would be a stat() call */
                }
                /* This code path would call FindFirstFileEx to get the file information by name from the node attribute */
                if (resolvesymboliclink && FileNodeType == FileTypes.SymbolicLink)
                   FileNodeType = 0;
        }
        /* Deserialization constructor */
        FileNode(string path, FileTypes fileNodeType, FileAttributes Attributes, DateTime lastAccessTimeUTC, DateTime lastChangeTimeUTC, DateTime lastWriteTimeUTC);
    }

    public partial class File {
         public static void CreateSymbolicLink(string target, string link, bool targetisdirectory = false);
    }

    public partial class Directory {
         // This one exists only code readability
         // The idea is the programmer would normally only pass the third parameter if it was indirection from another layer of indirection, and otherwise would call File.CreateSymbolicLink to create a symbolic link to a file and Directory.CreateSymbolicLink to create a symbolic link to a directory
         public static void CreateSymbolicLink(string target, string link, bool targetisdirectory = true)
                => File.CreateSymbolicLink(target, link, targetisdirectory);
    }

**Comment by Tratcher** [comment]
Was this meant for https://github.com/dotnet/corefx ?

**Comment by jhudsoncedaron** [comment]
Yeah oops.

**Comment by muratg** [comment]
Hi @jhudsoncedaron, could you file the bug over there, and close this one? Thanks.

**Comment by natemcmaster** [comment]
This has been discussed before, but I suppose it doesn't hurt to ask again.

https://github.com/dotnet/corefx/issues/3186
https://github.com/dotnet/corefx/issues/25385

**Comment by Eilon** [comment]
Indeed, closing this bug. @jhudsoncedaron  - please log a new bug in CoreFX or use one of the existing bugs that @natemcmaster has mentioned. Thanks!
