### ISSUE TITLE
Add Razor Page code gen errors specific to generator v2.0.2

### ISSUE THREAD

**Issue by MV10** [aspnet/Home#2778]
VS2017 v15.5.3 and ASP.NET Core 2.

I am converting a small Core 2 MVC site to Razor Pages. When I tried to add a new Razor Page the null-reference error shown below was thrown. I restarted VS, and it began throwing the second sequencing error every time, even after restarts. It didn't matter what options I choose in the first dialog and the null-reference error didn't happen again.

Then I noticed a second project in the same solution can add new pages without errors. I compared their csproj files. The non-working one references `Microsoft.VisualStudio.Web.CodeGeneration.Design` version 2.0.2, whereas the working one is using version 2.0.1. As soon as I downgraded the first project to 2.0.1 it started working normally.

![image](https://user-images.githubusercontent.com/794270/34920525-37b62342-f942-11e7-9075-91db2c863113.png)

![image](https://user-images.githubusercontent.com/794270/34920518-1a7ac29c-f942-11e7-85c7-03fcdfb56477.png)

![image](https://user-images.githubusercontent.com/794270/34920571-c893b5e6-f942-11e7-9dfe-5f89e645462c.png)

**Comment by Eilon** [comment]
This issue was moved to aspnet/Scaffolding#674
