### ISSUE TITLE
What will happen if a singleton service depends on a scoped service?

### ISSUE THREAD

**Issue by HongyanShen** [aspnet/Home#2779]
I am faced with a memory lead problem in my web api project,when i review the code,i find some singleton services depend on non-singleton service.Is it the key for the problem?

**Comment by davidfowl** [comment]
Singleton services that depend on scoped services turn those scoped services into singletons. In ASP.NET Core 2.0 this would throw an exception in development telling you there's a scope violation. See http://blog.ploeh.dk/2014/06/02/captive-dependency/ for more data on this type of problem.

You can look at a memory dump to see what's taking up the memory.

**Comment by HongyanShen** [comment]
@davidfowl got it,thks!

**Comment by Zoxive** [comment]
I think what @davidfowl is refering to is the ValidateScopes property on ServiceProviderOptions.

Typically a Web project would use something like

```csharp
webHostBuilder.UseDefaultServiceProvider((context, options) =>
{
    options.ValidateScopes = context.HostingEnvironment.IsDevelopment();
})
```

In my non-web projects i just use #if DEBUG

```csharp
    public ServiceProvider BuildServiceProviderDebugValidate(IServiceCollection services)
    {
        var options = new ServiceProviderOptions
        {
            #if DEBUG
                ValidateScopes = true
            #else
                ValidateScopes = false
            #endif
        };
        return services.BuildServiceProvider(options);
    }
```

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
