### ISSUE TITLE
Why is AspNet.Loader.dll in the bin directory?

### ISSUE THREAD

**Issue by atrauzzi** [aspnet/Home#278]
I've been watching "What's new with ASP.NET 5" at MVA and noticed that while the claim is made that no internals are in the public directory, AspNet.Loader.dll shows up in there!

Any chance that can be relocated so that the directory is truly clean? Why wouldn't it just be another nuget dependency?

**Comment by davidfowl** [comment]
It has to be there because of how the code in .NET 4.5.1 was written to load it. We don't have a time machine so it's something we'll have to live with forever more :smile:

**Comment by atrauzzi** [comment]
Perfect. I guess we can consider it like the index.php that's required for most PHP frameworks. ;)
