### ISSUE TITLE
project keeps looks for unreferenced EFcore assembly

### ISSUE THREAD

**Issue by JipingWang** [aspnet/Home#2781]
I had a small asp.net core 2.0 project using ASP.NET Core Identity, it worked fine.

Then, I tried .net core 2.1 preview, then removed it.

Now, my old project can not run, keeps saying:

> FileLoadException: Could not load file or assembly 'Microsoft.EntityFrameworkCore, Version=2.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

**Comment by Eilon** [comment]
@JipingWang can you show more info about when/where you get that error? How are you running the app? Did anything else in the app change, such as the csproj file?

**Comment by Eilon** [comment]
Hi. We're closing this issue as no response or updates have been provided in a timely manner and we have been unable to reproduce it. If you have more details and are encountering this issue please add a new reply and re-open the issue.
