### ISSUE TITLE
Breaking change in 2.0 version of Microsoft.Extensions.DependencyInjection

### ISSUE THREAD

**Issue by rsvaidya** [aspnet/Home#2788]
Hi,

We are using the `Microsoft.AspNet.WebHooks.Custom.AzureStorage.dll` which has a dependency to `Microsoft.Extensions.DependencyInjection` version 2.0. We get the following exception

`System.MissingMethodException: Method not found: 'System.IServiceProvider Microsoft.Extensions.DependencyInjection.ServiceCollectionContainerBuilderExtensions.BuildServiceProvider(Microsoft.Extensions.DependencyInjection.IServiceCollection)'.
   at Microsoft.AspNet.WebHooks.DataSecurity.GetDataProtector()
   at System.Web.Http.HttpConfigurationExtensions.InitializeCustomWebHooksAzureStorage(HttpConfiguration config, Boolean encryptData)`

We suspect that this is because of `Microsoft.Extensions.DependencyInjection.ServiceCollectionContainerBuilderExtensions.BuildServiceProvider()` returning a concrete type instead of `IServiceProvider`. Other frameworks also seem to have similar issues. See https://github.com/dotnet/orleans/issues/3325. They seem to be telling people not to upgrade to 2.0.  In our case, we have a hard dependency on version 2.0. Is there a way around this problem ?

Thanks,

Raghavendra

**Comment by davidfowl** [comment]
You have another library that's calling into the 1.0 version. Which one is it?

**Comment by rsvaidya** [comment]
The `Microsoft.AspNet.WebHooks.Custom.AzureStorage.dll` depends on 1.0 version of `Microsoft.Extensions.DependencyInjection`

**Comment by davidfowl** [comment]
It needs to be recompiled.
