### ISSUE TITLE
area routing with url segment as parameter 

### ISSUE THREAD

**Issue by grahamehorner** [aspnet/Home#2789]
I'm trying to create a route for a RESTful API using ASP.NET Core that describes the area/dataset and partition the resource resides in eg. {area}/{partition}/{controller}/{action}/{id?}

I also need to support the fall back for  {area}/{controller}/{action}/{id?} and {controller}/{action}/{id?}
when a {partition} or area/dataset is not supplied is this possible?

**Comment by mkArtakMSFT** [comment]
Hi @grahamehorner. It seems you just need to define your routes in an order you want them to be handled. If a request can't be matched with a route, it'll be evaluated against the next one - in the order those have been defined in the Startup class.
