### ISSUE TITLE
Web.Config overridden when using publish 

### ISSUE THREAD

**Issue by urigolani** [aspnet/Home#279]
Repro:
1. Create a new ASP VNext project using the template
2. Add a web.config to wwwroot
3. Modify the web.config as you like
4. right click the project and hit Publish 
5. In the Publish Web window that comes up go to Settings and set
5.1. Configuration:Release
5.2. Target Kre Version: KRE-CLR-amd641.0.0-beta1
5.3. File Publish Options: Unmark both options

Hit Publish
choose To FIle System.
go to the deployment folder you have set under the Connection tab in the Publish Web window.
go to wwwroot and open the web.config. 
You will find that it now contains configurations for the kre instead of using your web.config.

**Comment by djanosik** [comment]
Yeap, Web.config is not transformed, but replaced. It is not good, I need to specify rewrite rules for IIS. Are `web.Debug.config` nad `web.Release.config` added automatically to your project?

**Comment by ChengTian** [comment]
Just verified with latest version of DNX (1.0.0-beta6-12170), couldn't reproduce.
