### ISSUE TITLE
Xamarin.Mac: Could not find System.Runtime.CompilerServices.Unsafe

### ISSUE THREAD

**Issue by lsvhome** [aspnet/Home#2790]
Xamarin.Mac can't load System.Runtime.CompilerServices.Unsafe.dll which used within Microsoft.Extensions.Primitives.

Microsoft.Extensions.Primitives used within lot of base libraries e.g 
Microsoft.Extensions.Options,
Microsoft.Extensions.Caching.Abstractions,
Microsoft.Extensions.Configuration.Abstractions etc.

They are used within Microsoft.EntityFrameworkCore

So, Microsoft.EntityFrameworkCore unusable with Xamarin.Mac

Example project with bug appearing available [here](https://github.com/lsvhome/RuntimeBugAppearance). Project is compilable, but it crashes at runtime. More details described [here](https://github.com/aspnet/Common/pull/308)

[Suggested bugfix #1](https://github.com/aspnet/Common/pull/308)
[Suggested bugfix #2](https://github.com/aspnet/Common/pull/309)

**Comment by natemcmaster** [comment]
Have you tried reporting this error to https://github.com/dotnet/corefx (the home for System.Runtime.CompilerServices.Unsafe) or to Xamarin? We use System.Runtime.CompilerServices.Unsafe in a variety of places in our stack, and removing our dependency on it is not likely a solution we're going to take.
