### ISSUE TITLE
Sanitize user input for ResourceLocation, RootNamespace, etc

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/Home#2792]
Localization should check/sanitize input from sources like "ResourceLocationAttribute", "RootNamespaceAttribute", etc. to make sure that they A) fail early if they're illegal for some reason B) get trimmed of "extra" characters like `/` or `.` on the beginning/end.

**Comment by hishamco** [comment]
This is a good improvement to avoid illegal characters that makes the attributes fail. I will handle this if it's possible

**Comment by mkArtakMSFT** [comment]
We're closing this as we don't want to have validation logic which is applicable to one scenario and applies to all the cases.
