### ISSUE TITLE
Please update nuget for Microsoft.AspNetCore.Proxy

### ISSUE THREAD

**Issue by oliverjanik** [aspnet/Home#2794]

**Comment by anorborg** [comment]
This seems related to  #2484 which was moved over. Not sure whats up here? Can someone just provide a quick answer to understand why? Should we not expect a nuget update until 2.1 or something?

**Comment by Tratcher** [comment]
This package was a prototype that was never completed. We've stopped releasing prototype packages. If we ever finish it then we'll release real packages.

**Comment by anorborg** [comment]
Thank you so much for responding! Good to know! Might I suggest updating the README on the repo (and any other that is similar) that makes that clearer? I'd be happy to submit the appropriate pull-request if that would be helpful

**Comment by Tratcher** [comment]
By all means send a PR.

**Comment by jbuschke** [comment]
@Tratcher are there any plans for the proxy package? For me it seems a kind of basic feature that is often needed in microservices / api-gateways etc...

**Comment by Tratcher** [comment]
@DamianEdwards

**Comment by glucaci** [comment]
Do you have some updates for us? Will be this package supported / updated / released? @Tratcher @DamianEdwards

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
