### ISSUE TITLE
Stop the magic method names pattern

### ISSUE THREAD

**Issue by oliverjanik** [aspnet/Home#2795]
This is the official way how you set up WebHost:
```csharp
            WebHost.CreateDefaultBuilder(args)
                .UseStartup<Startup>()
                .Build();
```

This then looks up the Startup class, magically instantiates it and looks for methods with magic names like `ConfigureServices` or `Configure`. Now I have solution analysis complaining these methods are not used anywhere. 

To mitigate this issue the template generates a comment for these methods:
![image](https://user-images.githubusercontent.com/2280140/35077146-b98c6ed4-fc4f-11e7-96b6-49b3351631cf.png)

That just adds salt to the wound. This is a bad pattern.  Anders invented interfaces for a reason. I know this pattern has been around for ages (old ASP.NET, EF and many many other MS libraries) but that does not make it acceptable.

Gentlemen, let's end this atrocity!

To be constructive, here's a suggestion:
```csharp
.UseStartup(c => new Startup(c))
```

**Comment by oliverjanik** [comment]
Another case in point is 
```
app.UseMiddleware<MyMiddleware>()
```

Magic constructor, magic method names 👎 and instead of compile-time type errors we get Runtime erros if the constructor does not conform.

**Comment by Eilon** [comment]
Unfortunately interfaces can't work for `UseStartup` or `UseMiddleware` because there is no specific requirement about the number or types of the parameters. For example, the `ConfigureServices` method has many different allowed signatures, so we can't restrict it to only one.

The lambda syntax you propose could probably work. I'm not sure if that's come up before as an idea.

**Comment by Eilon** [comment]
@Tratcher which repo would this bug go to? Hosting?

**Comment by davidfowl** [comment]
> @Tratcher which repo would this bug go to? Hosting?

Yes Hosting.

> Magic constructor, magic method names 👎 and instead of compile-time type errors we get Runtime erros if the constructor does not conform.

There are actually interfaces for both of the things you suggest. There's an IMiddleware and an IMiddlewareFactory, and there's also an IStartup. We've received similar feedback in the past so we did introduce these interfaces. 

It does mean you lose the ability to use environment specific Configure and ConfigureServices via method names, you also lose the ability to get dependencies injected via method arguments but maybe that's ok in your scenario.

**Comment by Tratcher** [comment]
We actually do have IStartup and IMiddleware, but nobody has ever shown much interest in them. Want to give them a try?

This can go in Hosting.

**Comment by Eilon** [comment]
This issue was moved to aspnet/Hosting#1311

**Comment by oliverjanik** [comment]
@davidfowl c was referring to IConfiguration which is a param to Startup class as generated by the VS template.

**Comment by oliverjanik** [comment]
@Eilon overloads? That's how every decent lib works.

Shouldn't reflection be a last resort? This project should be a shining example of best practices.

**Comment by cogitaria-admin** [comment]
>> Anders invented interfaces for a reason.

Was this before or after Al Gore invented the Internet?  It would not have taken much to check yourself on this false attribution and save yourself some embarrassment,

**Comment by oliverjanik** [comment]
No need to be condescending. Anders Hejlsberg is the creator of C# so yes he is the inventor of C# interfaces.

**Comment by athinboy** [comment]
`It does mean you lose the ability to use environment specific Configure and ConfigureServices via method names, you also lose the ability to get dependencies injected via method arguments but maybe that's ok in your scenario.`

@Tratcher @davidcsa  I think Attribute is better than method name and method argument!
