### ISSUE TITLE
[2.0.x patch] Use StartWith with StringComparison.Ordinal to properly detect hidden files on Linux

### ISSUE THREAD

**Issue by Eilon** [aspnet/Home#2796]
Port this PR to 2.0.6: https://github.com/aspnet/FileSystem/pull/311

**Comment by Eilon** [comment]
This patch is **approved** for the Feb 2018 patch. Please send a PR to the appropriate branch, get it reviewed, and merge.

Please consider adding a [quirks-mode switch](https://github.com/aspnet/Home/wiki/Quirks-mode-switches-in-patches) for this change.

**Comment by natemcmaster** [comment]
Fixed in https://github.com/aspnet/FileSystem/pull/311
