### ISSUE TITLE
Environment Variable not working publishing dotnet core 2.0 project

### ISSUE THREAD

**Issue by bardi15** [aspnet/Home#2797]
I am having an Issue similar to this issue:
https://github.com/aspnet/Home/issues/2019

**Prerequisites:**
- Ubuntu 16.04
- .NET Core CLI

I added into the "~/.bash_profile" the following:

`export ASPNETCORE_ENVIRONMENT=Staging`

I have also tried adding the line to "~/.bashrc"

**Note: When running the project (using dotnet run) it works perfectly.** It finds the correct environment variable. However when i use **dotnet publish**, and run the app using:
`nohup dotnet API.dll --urls "http://*:1337" &> /var/log/dotnetlogs`

It does not seem to detect the environment variable. It defaults to using the "Production" environment.

**Code:**

Startup.cs:

```
public Startup(IHostingEnvironment env)
    {
        var builder = new ConfigurationBuilder()
            .SetBasePath(env.ContentRootPath)
            .AddJsonFile("appsettings.json", optional: true, reloadOnChange: true)
            .AddJsonFile($"appsettings.{env.EnvironmentName}.json", optional: true)
            .AddEnvironmentVariables();
        Configuration = builder.Build();
     }
```

Program.cs:

```
	       public static void Main(string[] args)
		{
			
			var config = new ConfigurationBuilder()
				.AddCommandLine(args)
				.Build();
			var host = new WebHostBuilder()
				.UseKestrel()
				.UseContentRoot(Directory.GetCurrentDirectory())
				.UseConfiguration(config)
				.UseStartup<Startup>()
				.Build();
			host.Run();
		}
		public static IWebHost BuildWebHost(string[] args) =>
			WebHost.CreateDefaultBuilder(args)
				.UseStartup<Startup>()
				.Build();
```

Some clarification:

1. The variable is not being overwritten by "launchSettings.json" because that file is only created with Visual Studio, and not with .NET Core CLI.
2. The problem does not have to do with case-sensitivity or anything of that kind. The actual contents of: IHostingEnvironment.EnvironmentName is always "Production" no matter what the ASPNETCORE_ENVIRONMENT is set to in the bash_profile.
`	    public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
	    {
	        var envName = env.EnvironmentName; // IS ALWAYS "Production"
	    }
`

After a few days of debugging and looking at multiple similar posts, I am still completely unable to get this working. 
Help would be greatly appreciated.

**Comment by Eilon** [comment]
@bardi15 that indeed sounds quite odd. Can you try printing out all the env vars from within your app's `Program.Main` to help narrow down where the issue is?

Just add a few lines like this to the top of the `Main(...)` method:

```c#
foreach (var de in Environment.GetEnvironmentVariables())
{
    Console.WriteLine($"  {de.Key} = {de.Value}");
}
```

**Comment by Eilon** [comment]
Hi. We're closing this issue as no response or updates have been provided in a timely manner and we have been unable to reproduce it. If you have more details and are encountering this issue please add a new reply and re-open the issue.

**Comment by andy65007** [comment]
1. check your OS Environment variables, make sure ASPNETCORE_ENVIRONMENT  exist.
2. add "@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers" in file "_ViewImports.cshtml" under Page root folder.

**Comment by NicoAleC** [comment]
I have the same problem, even in the web.config file it is the ASPNETCORE_ENVIRONMENT variable set but is not recognized

**Comment by paultechguy** [comment]
Same issue here on Ubuntu 18.04.  I added this to /etc/profile and have rebooted:

    export ASPNETCORE_ENVIRONMENT=Development

In terminal windows, I can "printenv" and verify the value is "Development", but when I started my website locally:

sudo dotnet mywebsite.dll

It runs, but indicates the environment is Production.

    Hosting environment: Production
    Content root path: /var/www/mywebsite
    Now listening on: http://localhost:5000
    Application started. Press Ctrl+C to shut down.

**Comment by rhacir** [comment]
> Same issue here on Ubuntu 18.04. I added this to /etc/profile and have rebooted:
> 
> ```
> export ASPNETCORE_ENVIRONMENT=Development
> ```
> 
> In terminal windows, I can "printenv" and verify the value is "Development", but when I started my website locally:
> 
> sudo dotnet mywebsite.dll
> 
> It runs, but indicates the environment is Production.
> 
> ```
> Hosting environment: Production
> Content root path: /var/www/mywebsite
> Now listening on: http://localhost:5000
> Application started. Press Ctrl+C to shut down.
> ```

Same issue here on Ubuntu 18.04 LTS. The difference is I am using self-contained deployment.

**Comment by paultechguy** [comment]
This is a closed issue so not sure if we'll get any help/response on this issue. :-(

**Comment by rhacir** [comment]
> This is a closed issue so not sure if we'll get any help/response on this issue. :-(

I just resolve the issue.
[Code]
 public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
            .UseEnvironment("Development")      
            .UseStartup<Startup>();

**Comment by rhacir** [comment]
> > This is a closed issue so not sure if we'll get any help/response on this issue. :-(
> 
> I just resolve the issue.
> [Code]
> public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
> WebHost.CreateDefaultBuilder(args)
> .UseEnvironment("Development")
> .UseStartup();

Or set IHostingEnviroment env.EnviromentName
