### ISSUE TITLE
dotnet.exe is crashing while running the tests

### ISSUE THREAD

**Issue by jaydeept** [aspnet/Home#2798]
Hello,

I am using .Net Core 2 for my project. I need to support Oracle hence for that I am using 3rd party library as provided [here](https://github.com/ericmend/oracleClientCore-2.0). 
When I try to run tests from test explorer, I get error that dotnet.exe has stopped working. And if I click on debug, it shows "coreclr.pds" not loaded.
But if I debug the test, test case is passing properly.
I am using Visual Studio 2017 version: 15.5.4.
The Dotnet SDK version is 2.1.4.
I have tried with all dotnet SDK version (both *86 and *64) but faced the same issue.

**Comment by Eilon** [comment]
@jaydeept can you show a screenshot of the exact error you're getting? Was it `coreclr.pds` or `coreclr.pds`?

**Comment by jaydeept** [comment]
Hello @Eilon ,

Yes it's related to `coreclr.pdb` file.
I got below exception on running test:
![error](https://user-images.githubusercontent.com/18435588/35138124-02725492-fd13-11e7-8d09-1245cbaba45d.PNG)

And on clicking debug below information came:

![coreclr](https://user-images.githubusercontent.com/18435588/35138132-0e81a684-fd13-11e7-9e7e-e4f24703b7b5.PNG)

**Comment by Eilon** [comment]
Thanks for the info @jaydeept . I think that https://github.com/dotnet/core/issues/1230 is a better place for this issue because it doesn't look related to ASP.NET Core.

**Comment by jaydeept** [comment]
Ok @Eilon ,

I thought when you asked is it related to coreclr.pdb, it's known issue and related to aspnet.
