### ISSUE TITLE
DI: Container does not dispose existing services when encountering exception in ConfigureServices()

### ISSUE THREAD

**Issue by helgemahrt** [aspnet/Home#2800]
I first encountered this issue in the context of Service Fabric and reported it here: [https://github.com/Azure/service-fabric-aspnetcore/issues/42](https://github.com/Azure/service-fabric-aspnetcore/issues/42) Please view this items for details. In a nutshell: When there's an exception in `ConfigureServices()` and we've added an IDisposable to the services collection, which has already been instantiated, the container doesn't dispose it correctly. 
The issue is amplified by Service Fabric, because it retries starting the web app/API without starting a new process, so the leak becomes more apparent. In our case, this lead to a high CPU hang which disabled some production level machines. However, the issue also reproduces in a standalone ASP.NET Core 2.0 web API. 
It doesn't matter whether I add an instance of my service manually to the container or whether I let the container create it, the Dispose() function is never called and the timer continues to fire after exiting ConfigureServices(), when the web app already failed to start. E.g. this also fails:
```
            services.AddSingleton<MyServiceImpl>();

            services.AddMvc();

            services.BuildServiceProvider().GetService<MyServiceImpl>();

            throw new Exception("Asdf");
```

**Comment by Tratcher** [comment]
This issue was moved to aspnet/Hosting#1313
