### ISSUE TITLE
High Latency seen in IIS Logs

### ISSUE THREAD

**Issue by Shannaxchen** [aspnet/Home#2802]
Hey folks,

For some background: we are seeing a lot of latency when talking to Azure Storage. They've asked us to collect IIS_FailureTrace Logs to see a better picture of what might be happening.

We looked into the logs and see that there is a lot of latency during this event:

```
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
<System>
  <Provider Name="ASPNET" Guid="{AFF081FE-0247-4275-9C4E-021F3DC1DA35}"/>
  <EventID>0</EventID>
  <Version>0</Version>
  <Level>4</Level>
  <Opcode>18</Opcode>
  <Keywords>0x4</Keywords>
  <TimeCreated SystemTime="2018-01-12T10:08:32.469Z"/>
  <Correlation ActivityID="{80000189-0403-D800-B63F-84710C7967BB}"/>
  <Execution ProcessID="5980" ThreadID="3232"/>
  <Computer>RD0003FF271C0B</Computer>
</System>
<EventData>
  <Data Name="ConnID">0</Data>
  <Data Name="Context ID">{80000189-0403-D800-B63F-84710C7967BB}</Data>
</EventData>
<RenderingInfo Culture="en-US">
  <Opcode>AspNetHttpHandlerEnter</Opcode>
  <Keywords>
   <Keyword>Page</Keyword>
  </Keywords>
</RenderingInfo>
<ExtendedTracingInfo xmlns="http://schemas.microsoft.com/win/2004/08/events/trace">
  <EventGuid>{06A01367-79D3-4594-8EB3-C721603C4679}</EventGuid>
</ExtendedTracingInfo>
</Event>
```

The next thing that happens shows a timestamp where it’s created 3 seconds after the previous event which is why we believe the latency is stemming from AspNetHttpHandlerEnter:

```
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
<System>
  <Provider Name="WWW Server" Guid="{3A2A4E84-4C21-4981-AE10-3FDA0D9B0F83}"/>
  <EventID>0</EventID>
  <Version>1</Version>
  <Level>4</Level>
  <Opcode>56</Opcode>
  <Keywords>0x0</Keywords>
  <TimeCreated SystemTime="2018-01-12T10:08:35.438Z"/>
  <Correlation ActivityID="{80000189-0403-D800-B63F-84710C7967BB}"/>
  <Execution ProcessID="5980" ThreadID="3232"/>
  <Computer>RD0003FF271C0B</Computer>
</System>
<EventData>
  <Data Name="ContextId">{80000189-0403-D800-B63F-84710C7967BB}</Data>
  <Data Name="HeaderName">X-CorrelationId</Data>
  <Data Name="HeaderValue">c420c068-246b-4e89-970e-8c2d4e684d23</Data>
  <Data Name="Replace">false</Data>
</EventData>
<RenderingInfo Culture="en-US">
  <Opcode>GENERAL_SET_RESPONSE_HEADER</Opcode>
</RenderingInfo>
<ExtendedTracingInfo xmlns="http://schemas.microsoft.com/win/2004/08/events/trace">
  <EventGuid>{D42CF7EF-DE92-473E-8B6C-621EA663113A}</EventGuid>
</ExtendedTracingInfo>
</Event>
```

We’ve tried searching what that event is but we’re not able to find anything – we were wondering if you were able to help us dig into this anymore or had any thoughts on what this could be?

Attaching an example of the IIS_FailureTrace log.
[MSOSP443_FE1.zip](https://github.com/aspnet/Home/files/1644453/MSOSP443_FE1.zip)

**Comment by Eilon** [comment]
@jkotalik / @shirhatti / @Tratcher - any idea where this bug should go? Is this ANCM?

**Comment by shirhatti** [comment]
@Eilon I just quickly looked at the FREB logs. Doesn't look this has anything to with Core

**Comment by Eilon** [comment]
@shirhatti got it. Any idea where this bug should go to? Looks like @Shannaxchen is in Microsoft, so maybe there's some TFS repo somewhere?

**Comment by shirhatti** [comment]
Honestly, there's not much to go off in the logs. Bulk of the time is spent in the AspNetHttpHandler. There's nothing in the FREB logs as to why that's happening.
@Shannaxchen You're probably better served by collecting a profile, but I'd ask @honggit or @jinhuafei for next steps.

**Comment by Shannaxchen** [comment]
We suspect it might be due to queuing, but don't know what might be causing it.
Could the machine's SKU size have any affect? Too many threads/processes are running?

Some more information:
Each one of our front end machines in our datacenter has a CPU set up of: 4 Cores, 14GB GB Memory, 200GB Disk
We have 424 front end machines in one datacenter and during peak hours (when we experience this high latency, we can see up 100k ASP.NET requests/sec.

**Comment by Shannaxchen** [comment]
@hongGit @jinhuafei do you have any ideas?

**Comment by mattfjh** [comment]
Your wcf service code took most of the time.


123. | NOTIFY_MODULE_START | ModuleName="ManagedPipelineHandler", Notification="EXECUTE_REQUEST_HANDLER", fIsPostNotification="false" | 10:08:07.745
-- | -- | -- | --
124. | AspNetPipelineEnter | Data1="System.Web.ImplicitAsyncPreloadModule" | 10:08:07.745
**_125. | AspNetPipelineLeave | Data1="System.Web.ImplicitAsyncPreloadModule" | 10:08:07.745
126. | AspNetHttpHandlerEnter |   | 10:08:07.745
127. | GENERAL_SET_RESPONSE_HEADER | HeaderName="X-CorrelationId", HeaderValue="b3957907-6888-47f9-a90b-fc975e158a12", Replace="false" | 10:08:50.041_**
128. | GENERAL_SET_RESPONSE_HEADER | HeaderName="Content-Length", HeaderValue="712", Replace="false" | 10:08:50.041
129. | GENERAL_SET_RESPONSE_HEADER | HeaderName="Cache-Control", HeaderValue="private", Replace="true" | 10:08:50.041
130. | AspNetHttpHandlerLeave |   | 10:08:50.041

**Comment by Jinhuafei** [comment]
The wcf handler took most of the time. You need to profile your WCF code.


123. NOTIFY_MODULE_START ModuleName="ManagedPipelineHandler", Notification="EXECUTE_REQUEST_HANDLER", fIsPostNotification="false" 10:08:07.745 
124. AspNetPipelineEnter Data1="System.Web.ImplicitAsyncPreloadModule" 10:08:07.745 
125. AspNetPipelineLeave Data1="System.Web.ImplicitAsyncPreloadModule" 10:08:07.745 
126. AspNetHttpHandlerEnter  10:08:07.745 
127. GENERAL_SET_RESPONSE_HEADER HeaderName="X-CorrelationId", HeaderValue="b3957907-6888-47f9-a90b-fc975e158a12", Replace="false" 10:08:50.041 
128. GENERAL_SET_RESPONSE_HEADER HeaderName="Content-Length", HeaderValue="712", Replace="false" 10:08:50.041 
129. GENERAL_SET_RESPONSE_HEADER HeaderName="Cache-Control", HeaderValue="private", Replace="true" 10:08:50.041 
130. AspNetHttpHandlerLeave  10:08:50.041 
131. GENERAL_SET_RESPONSE_HEADER HeaderName="Content-Type", HeaderValue="text/xml; charset=utf-8", Replace="true" 10:08:50.041 
132. NOTIFY_MODULE_COMPLETION ModuleName="ManagedPipelineHandler", Notification="EXECUTE_REQUEST_HANDLER", fIsPostNotificationEvent="false", CompletionBytes="0", ErrorCode="The operation completed successfully.
 (0x0)" 10:08:50.041 
133. NOTIFY_MODULE_END ModuleName="ManagedPipelineHandler", Notification="EXECUTE_REQUEST_HANDLER", fIsPostNotificationEvent="false", NotificationStatus="NOTIFICATION_CONTINUE" 10:08:50.041

**Comment by Eilon** [comment]
Hi. We're closing this issue as no response or updates have been provided in a timely manner and we have been unable to reproduce it. If you have more details and are encountering this issue please add a new reply and re-open the issue.
