### ISSUE TITLE
Assignable JsonSettings

### ISSUE THREAD

**Issue by oliverjanik** [aspnet/Home#2805]
Let me prefix this by saying, that every single project of mine needs to have Json settings adjusted because defaults are outright broken.

Hi, if I'm not mistaken this is the official way to setup Newtonsoft.Json in AspNetCore 2
```csharp
            services.AddMvc().AddJsonOptions(o =>
            {
                o.SerializerSettings.ContractResolver = new CamelCasePropertyNamesContractResolver();
                o.SerializerSettings.Converters = new JsonConverter[] { new StringEnumConverter() };
                o.SerializerSettings.DateParseHandling = DateParseHandling.None;
            });
```

There are 2 oddities here.

1) Why can't I assign my settings from somewhere? Why do I have to do each property individually? Lots of projects have this as well
```csharp
            JsonConvert.DefaultSettings = () => new JsonSerializerSettings
            {
                ContractResolver = new CamelCasePropertyNamesContractResolver(),
                Converters = new JsonConverter[] { new StringEnumConverter() },
                DateParseHandling = DateParseHandling.None
            };
```

I want to be able to just take my existing settings and assign them to AspNetCore. Don't make the world revolve around you.

2) I can't for the love of god find documentation for this. Every MVC project needs this.

**Comment by Eilon** [comment]
Hi @oliverjanik , we have previously considered this suggestion and for the reasons described in https://github.com/aspnet/Mvc/issues/6816#issuecomment-329221624, we kept the current design.

**Comment by oliverjanik** [comment]
Hi @Eilon 
You have not addressed my point 2 ;-)

> Hi @evil-shrike the reason we don't have it settable is that options in ASP.NET Core in general are "composable," meaning that different components and parts of an app can each contribute various settings. If it were settable, that means that a component would be able to (perhaps inadvertently) overwrite important settings provided by another component.

Please. What stops a component from overriding each property if they want to and act maliciously?

On top that why would you want composable json settings? What is the use-case? If one component says PascalCase and next one says camelCase, how is that composable? The first component gets a nasty surprise anyway.

**What you want in reality is one consistent json settings for your app and additional smaller scope overrides (say per controller)**

Also to merge with default setting can't you just do `settings = Merge(default, userSupplied)` somewhere internally?

Stop making engineers' life miserable. Don't make me jump through hoops to get even the basic things done. Have you not learnt from previous generations of MS frameworks? Let me assign the goddamn json settings.

Who's the architecture astronaut in charge of the configuration bit of AspNetCore?

The fact is, I like NetCore and most of AspNetCore, but you are a small fish in the pond of backend frameworks. MS and .NET does not have the best reputation to begin with. And with an attitude like this your lunch will be eaten by Go, Node, and others..

So get your head out of MS bubble and give us an awesome framework. 👍

**Comment by Eilon** [comment]
Hi @oliverjanik sorry for the delay, this got lost in a sea of browser tabs!

This isn't about components acting maliciously - it's all your own app, so there's no security boundary being crossed here. But it does enable components to act *cooperatively* to configure the application. Various components can each contribute their own interesting JsonSerializerSettings, such as registering additional binders, wrapping various handlers to inject their own logic, etc.

**Comment by oliverjanik** [comment]
In other words you're sacrificing API usability to cater for 5% use-case?

How about making 95% use-case easy and provide hooks for your fancy hypotheticals  to cover the rest?

**Comment by Eilon** [comment]
@oliverjanik this hasn't been a common source of pain that we've observed so far, so we haven't been inclined to make changes to it.

But, to give a concrete example of why this design is important to us:

The default `JsonSerializerSettings` in ASP.NET Core MVC applications are not simply an empty `new JsonSerializerSettings()` - they have been customized to enable some important security settings and functional behavior that we think are important to be defaults.

This is where the main settings get initialized in MVC's options: https://github.com/aspnet/Mvc/blob/d342ebf8c8c54f575fb2ebdd6ebf027ce4a50904/src/Microsoft.AspNetCore.Mvc.Formatters.Json/MvcJsonOptions.cs#L72

And this is where the default JsonSerializerSettings are configured: https://github.com/aspnet/Mvc/blob/32e21e2a5c63e20bd62b9c1699932207b962fc50/src/Microsoft.AspNetCore.Mvc.Formatters.Json/JsonSerializerSettingsProvider.cs#L31-L41

If the entire settings object was publicly settable, it would be trivial to accidentally disable the security critical `TypeNameHandling` feature away from the safest setting of `TypeNameHandling.None`.

In fact, in the example provided at the start of this issue, this important non-default value would be reset, potentially exposing the application to security threats.

**Comment by oliverjanik** [comment]
I'm not sure I follow. Are you saying that you can't think of any other way how to prevent TypenameHandling changes? This was the only design option? 

Because doing `settings.TypeNameHandling  = TypeNameHandling.None` after all the components are loaded seems a surefire way to do it.

On a related note, maybe AspNetCore team should be looking into shipping JSON seriliazer that is not broken out of the box 👍

**Comment by Eilon** [comment]
@oliverjanik we don't want ASP.NET Core to *force* that option by setting it last because there are legitimate scenarios where it is safe to use. For example, if the application is an internal web API that is accessible by only trusted clients, using other `TypeNameHandling` options is perfectly fine. It's just not a safe default for *most* applications.

It's difficult (or impossible?) to create some APIs that are perfect for every scenario. We chose an option that we felt was best for most applications.
