### ISSUE TITLE
Move the basic functionality of file streaming to a lower level API

### ISSUE THREAD

**Issue by jbagga** [aspnet/Home#2807]
_From @jbagga on January 18, 2018 23:51_

See https://github.com/aspnet/Mvc/issues/7208#issuecomment-356588707

@Tratcher @dustinmoris

_Copied from original issue: aspnet/Mvc#7259_

**Comment by jbagga** [comment]
_From @rynowak on January 19, 2018 0:53_

This isn't an MVC issue 😆 - *a lower level* implies non-MVC

**Comment by jbagga** [comment]
I'll move it to Home and @Eilon can decide which label. Thanks!

**Comment by dustinmoris** [comment]
Thanks, sounds like this is the right place, however I remember @DamianEdwards and @Eilon  saying on one of the recent stand ups that issues in aspnet/Home are getting forgotten.

**Comment by rynowak** [comment]
This is the right place. We're doing a trial of consolidating issues from lower-traffic repos in aspnet/Home.

**Comment by khellang** [comment]
With the advent of `IActionResultExecutor<TResult>`, it's pretty easy to knock out a helper extension method to execute `FileStreamResult` in any middleware: http://kristian.hellang.com/using-mvc-result-executors-in-middleware/. You still need a dependency on `Microsoft.AspNetCore.Mvc.Core` (and the formatters you need), but it's a nice start.

**Comment by Eilon** [comment]
Closing because there are no plans to implement this at this time.
