### ISSUE TITLE
Port to 2.0.x: FileSystemGlobbing passes invalid path upon upgrade to Core 2.0

### ISSUE THREAD

**Issue by Eilon** [aspnet/Home#2808]
Port the fix for https://github.com/aspnet/Home/issues/2536 to 2.0.x.

PR for 2.1.0: https://github.com/aspnet/FileSystem/pull/314

**Comment by Eilon** [comment]
This patch is **approved** for the Feb 2018 patch. Please send a PR to the appropriate branch, get it reviewed, and merge.

Please consider adding a [quirks-mode switch](https://github.com/aspnet/Home/wiki/Quirks-mode-switches-in-patches) for this change.

**Comment by Eilon** [comment]
@muratg - can you assign someone to port? Or, @natemcmaster , feel free to grab 'n go.

**Comment by natemcmaster** [comment]
I can port it. Its like a 4 line change. Do you think this one deserves a quirks mode switch?

**Comment by Eilon** [comment]
Good question. It seems so trivial. But the cost/harm of adding a quirk mode is close to zero, so I'd recommend adding it anyway.

**Comment by Eilon** [comment]
(Who knows, maybe an empty string *is* valid in some crazy case.)

**Comment by natemcmaster** [comment]
ok, i'll make that part of porting it.

**Comment by natemcmaster** [comment]
Fixed in https://github.com/aspnet/FileSystem/pull/315
