### ISSUE TITLE
ASP.NET 5 class library project

### ISSUE THREAD

**Issue by yishaigalatzer** [aspnet/Home#281]
Is the name ASP.NET 5 class library correct, or is this should be called a cross platform class library?

See SO thread: http://stackoverflow.com/questions/28034174/why-create-an-asp-net-5-class-library-project

**Comment by Eilon** [comment]
It's being renamed.

**Comment by Eilon** [comment]
Expect to see something like:

* .NET Console Application (Cross-platform)
* .NET Class Library (Cross-platform)
