### ISSUE TITLE
ResponseCaching  Repository  QueryString created a cache key with a bug.

### ISSUE THREAD

**Issue by tangdf** [aspnet/Home#2810]
https://github.com/aspnet/ResponseCaching/blob/5b239d44c0d749600a60ccd2951e0a67edd11a10/src/Microsoft.AspNetCore.ResponseCaching/Internal/ResponseCachingKeyProvider.cs#L142-L152

Query String| Cache Key
---|---
?key=12&key=34 | key=1234
?key=1&key=234 | key=1234

The cache key of query string **?key=12&key=34** and **?key=1&key=234** is the same , both **key=1234**.

**Comment by Tratcher** [comment]
@JunTaoLuo

**Comment by JunTaoLuo** [comment]
Looks like the underlying HttpContext is consolidating the values of the query keys. I wonder if we should use the raw query string and whether that would lead to too many duplicated entries clogging up the cache.

**Comment by Tratcher** [comment]
You get multiple entries in the StringValues, it only needs a separator.
