### ISSUE TITLE
Fix websockets tests broken by switching Kestrel back to libuv by default

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/Home#2813]
Some tests started failing after https://github.com/aspnet/KestrelHttpServer/pull/2257

 - Microsoft.AspNetCore.WebSockets.Test
 - Microsoft.AspNetCore.Proxy.Test.WebSocketsTest

http://aspnetci/viewLog.html?buildId=390091&tab=buildResultsDiv&buildTypeId=Lite_UniverseTest

cc @ryanbrandenburg 

@halter73 can you take a look?

**Comment by natemcmaster** [comment]
Failure:
```
System.IO.IOException : Failed to bind to address http://localhost:4001.
---- System.AggregateException : One or more errors occurred.
-------- System.DllNotFoundException : Unable to load DLL 'libuv': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
```

**Comment by halter73** [comment]
Fixed by https://github.com/aspnet/WebSockets/commit/ec442c3d80ea1ab800350cc401dfebf54291d19e

**Comment by anurse** [comment]
FYI, there are other tests (in Proxy) which have similar issues. And I'd imagine the various server/functional tests may have this issue to (depending on if they have the necessary MSBuild config applied). Perhaps we should try to put something in our common targets to enable this for all test projects. /cc @ryanbrandenburg @natemcmaster @halter73

**Comment by halter73** [comment]
:+1: It doesn't hurt to add the HasRuntimeOutput to all the test projects until the vstest issue is fixed, right?

**Comment by anurse** [comment]
Yeah, that's what I suggested to @ryanbrandenburg earlier.
