### ISSUE TITLE
How do I resolve HttpRequest into an arbitrary dependency?

### ISSUE THREAD

**Issue by cottsak** [aspnet/Home#2817]
My dependency needs access to the cookies collection from the Request but I can't simply resolve `HttpRequest` via the constructor in Core 2.0.

I need to `services.TryAddSingleton<IHttpContextAccessor, HttpContextAccessor>();` as it turns out and then use `_httpContextAccessor.HttpContext.Request` in my service. This seems dirty and given the decision to [avoid registering `HttpContextAccessor` by default](https://github.com/aspnet/Hosting/issues/793), I'm led to think that `HttpRequest` should be supplied more easily. I suspect I just don't to where to find it. Can someone help me out?

**Comment by Tratcher** [comment]
No, IHttpContextAccessor is the API for this.

**Comment by cottsak** [comment]
@Tratcher Doesn't it seem weird that I can't just ask for `HttpRequest` directly to you?

Perhaps I've been spoilt by Autofac for too long. // @tillig @nblumhardt

**Comment by Tratcher** [comment]
Not really, HttpRequest/HttpContext are not services, they are request processing artifacts. To even pretend to be services they'd have to be scoped services, only resolvable within the context of a request. It wouldn't make any sense to try to resolve one in Startup.

**Comment by cottsak** [comment]
"services" seems ambiguous to me. They are dependancies. We should be able to agree on that. As primary concerns of a HTTP-based system I find it strange that they aren't easily resolved (compare with having to go through `IHttpContextAccessor` all the time). 

Sure they need to be scoped to the request, they have no meaning outside of the request. I'm not asking to resolve one in Startup.

I simply want to create services/dependancies who can constructor-resolve the Request and Response types easily and I'm suggesting having to use `IHttpContextAccessor` to get them is not easy.

**Comment by davidfowl** [comment]
The IHttpContextAccessor is the way you'd enable that regardless. The HttpContext can't be added as a service, it needs to be resolved from another existing service and set per request. This is what the IHttpContextAccessor gives you and it is more flexible since it is a singleton.

If you want to inject the HttpContext directly into your services then you can add this to Startup.ConfigureServices:

```C#
services.TryAddSingleton<IHttpContextAccessor, HttpContextAccessor>();
services.AddScoped(sp => sp.GetRequiredService<IHttpContextAccessor>().HttpContext);
```

> Perhaps I've been spoilt by Autofac for too long. 

The only way this could have ever worked in the past (non core ASP.NET) was via HttpContext.Current which IHttpContextAccessor is the moral equivalent.

**Comment by tillig** [comment]
By way of additional information, the [`AutofacWebTypesModule`, which had typically been responsible for this in Autofac](https://github.com/autofac/Autofac.Mvc/blob/e26ce3fe9ccc639f1349bcd8aee8e6e4ee066346/src/Autofac.Integration.Mvc/AutofacWebTypesModule.cs#L127) is doing exactly what @davidfowl mentions:

```csharp
builder.Register(c => new HttpContextWrapper(HttpContext.Current))
  .As<HttpContextBase>()
  .InstancePerRequest();
```

We had just wrapped it up so you didn't know it.

**Comment by cottsak** [comment]
Thanks @davidfowl and @tillig 

By your example then, can I also do this?

``` c#
services.AddScoped(sp => sp.GetRequiredService<IHttpContextAccessor>().HttpContext.Request);
services.AddScoped(sp => sp.GetRequiredService<IHttpContextAccessor>().HttpContext.Response);
```

which allows me this?

``` c#
public ArbitaryConstructor(HttpRequest request, HttpResponse response) {
...
}
```

**Comment by davidfowl** [comment]
Yes. Once you can get the HttpContext, then you can just do:

```C#
services.AddScoped(sp => sp.GetRequiredService<HttpContext>().Request);
services.AddScoped(sp => sp.GetRequiredService<HttpContext>().Response);
```

etc.

**Comment by khellang** [comment]
> having to use IHttpContextAccessor to get them is not easy.

This is a Good Thing™ IMO. Injecting request-scoped state is a big foot-gun. Why not pass the state through method calls?

**Comment by cottsak** [comment]
@khellang Because this particular "service" is used to indicate to the consumer whether the "request" has a particular feature flag/toggle - it might start as a header, cookie or query string param but it's certainly "request scoped" as you say. 

I'm trying to port this https://github.com/cottsak/devcookie to .NET Core MVC, etc.

I'll want to inject said service anywhere in the web application and know that it can answer my question (based on the request scope) so in this case request-scoped state is entirely appropriate.

**Comment by tobyhei** [comment]
I don't see how registering the HttpContext as a scoped dependency is a footgun and IHttpContextAccessor as a singleton isn't.

When using the IHttpContextAccessor directly it's easy to hold onto the current request in a singleton for too long, with no protections offered by the framework to prevent this.

Whereas it is quite hard to misuse a scoped HttpContext now that the microsoft.extensions.dependencyinjection rejects captive dependencies.

It seems to me that users should be encouraged to depend on HttpContext directly if they need to access it unless they have to use it within a singleton. What's the rationale for offering a helping to register the IHttpContextAccessor appropriately but not the HttpContext itself?

**Comment by davidfowl** [comment]
I actually don't see a problem adding a helper to do that, it wouldn't be on by default just like the HttpContextAccessor isn't on by default. As also previously mentioned in this threadm one depends on the other so it would need to register both things regardless.
