### ISSUE TITLE
TagHelperOutput AppendHtml method serialize the html string array value as differently

### ISSUE THREAD

**Issue by manikandan05** [aspnet/Home#2818]
Hi All,

In my application i have dynamically form the input elements like as below mentioned code block. In my Process method, i have append the html string to the  **TagHelperOutput.*

> public override void Process(TagHelperContext context, TagHelperOutput output) {    
>   
>        string inputTag = "<input data-val-requiredif-values="["ValueData1","ValueData2"]" style="width: 100%;" type="text" data-val="true" data-val-requiredif="txtbox" data-val-requiredif-field="txtbox"   id="TextSF" name="TextSF" value="" />";
> 
>       //append the html string value into the TagHelperOutput
> 
>        output.Content.AppendHtml(inputTag);
> 
>    }

But the resultant data is slightly different from my input data. The array values are automatically converted into lowercase, also extra one space added in first string array value. This issue only raised in string array value data types.

![88a4243](https://user-images.githubusercontent.com/5366630/35281608-498780e6-0079-11e8-866e-beb6096ab5c0.PNG)

How i can overcome from this array value serialized as lowercase issue! is really appreciated.

Thanks.

**Comment by Eilon** [comment]
This issue was moved to aspnet/Razor#1965
