### ISSUE TITLE
Dependency Injection beta-2 is throws internal server error

### ISSUE THREAD

**Issue by urigolani** [aspnet/Home#282]
I didnt make a repro but this is what I have for now
2 days ago my project worked fine. today I've built it, got new packages and got an error (see image1).
The only difference was in the project.json I had a dependency on:
"Microsoft.AspNet.StaticFiles": "1.0.0-*", and got
"Microsoft.AspNet.StaticFiles": "1.0.0-beta2", instead of my older "Microsoft.AspNet.StaticFiles": "1.0.0-beta1", which fetched "Microsoft.Framework.DependencyInjection": "1.0.0-beta2",

Please contact me to get the working and non working global.json and the project.json
here or at urig@microsoft.com

![image](https://cloud.githubusercontent.com/assets/1035022/5816063/c81c1d00-a0a4-11e4-9623-a44242dceffa.png)

**Comment by davidfowl** [comment]
Did you update the KRE to match?

**Comment by urigolani** [comment]
Can't say that I have.
Haven't dug too much into it, and I'm not too familiar yet with KRE,
I've overcame this by using staticfiles-beta1.
I'm not sure the beta2 versions should have been pulled given that I don't have the right KRE.

**Comment by danroth27** [comment]
@urigolani Let us know if you're still having issues with this.
