### ISSUE TITLE
Url length

### ISSUE THREAD

**Issue by rajurh** [aspnet/Home#2823]
Is there a way to set a maxUrlLength configuration value in Asp.Net Core? I see how this is done in web.config in earlier versions of the framework.

I am trying to incorporate the url encryption due to which its exceeding 260 charc and in that case it give bad request for url length greater than 260.

Help on this will be much appreciated.

**Comment by Tratcher** [comment]
That's a server specific feature. Which server(s) are you using? HttpSys, Kestrle, or IIS+Kestrel?

**Comment by halter73** [comment]
This somewhat depends on browsers too. Both Chrome and Edge have a 2083 character max URL length.

I doubt you're running into any Kestrel limits. The closest related thing in Kestrel is [MaxRequestLineSize](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.server.kestrel.kestrelserverlimits.maxrequestlinesize?view=aspnetcore-1.1#Microsoft_AspNetCore_Server_Kestrel_KestrelServerLimits_MaxRequestLineSize) which is 8KB. I'm pretty sure [IIS defaults to a 4KB]. So you must be running into some limit I don't know about.

The 260 character limit matches the [MAX_PATH](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247(v=vs.85).aspx) used by some Windows API's, so maybe it's related to that.

**Comment by rajurh** [comment]
I tried with MaxRequestLineSize no luck I have attached sample application. Once the application runs please click on Example 1 demo link that leads to error what has been described above.

[AspNetCoreMvcCryptoValueProvider-master.zip](https://github.com/aspnet/Home/files/1666444/AspNetCoreMvcCryptoValueProvider-master.zip)

**Comment by Tratcher** [comment]
Example URL: 
```
http://localhost:12207/demo/example1/CfDJ8PKsL61YGFVIun36yEQJfKNS7LYiSTMWhirW91FPsqWobvuI4EO_6i7hMaZe4Sh-iTQMfG1PhI26CB1U16MUBxhozll_2PAfuFaOo9p4Mu_tnRQPgjMu4yoSK-2RGlupl-gAki_jiwu4U54DLiShv4oofL-mMfg9Tz_DobM8vz99ew2DQRbeY0Vlq-BxBl3fxFAaO_g9CPtX9G9nZHumfZb2lv1Wr_YBTrTtRoYJc64zMamRnUAW6R1e2nwASDoIyQ
```

This works fine in Kestrel, but fails for IIS/Express + Kestrel.  Note the single long path segment blob. The limit you're hitting is UrlSegmentMaxLength (260). This is all the way down in Http.Sys and only configurable in the registry.
https://support.microsoft.com/en-us/help/820129/http-sys-registry-settings-for-windows

Workaround: break it up into multiple path segments, or move it to the query or body. Or use Kestrel without IIS.

**Comment by rajurh** [comment]
In case of cloud based application like if its hosted in Azure how are we going to set the value?

**Comment by Tratcher** [comment]
@rajurh only Azure admins can modify that, and it would affect everybody. You'll need to change your design.

**Comment by glennc** [comment]
Closing this as I think the question has been answered. @rajurh you will need to contact people that work on the Azure service you are using to talk about how to change the setting, now that you know which setting you need. Probably via one of the Azure support options. Whether or not it is possible really depends on what you are doing and which Azure service you are talking about, and we are not really the right people to help with that part of this question.

**Comment by mgolois** [comment]
@Tratcher, which server features do I need to update to increase the url max length? Im running IIS with Kestrel

**Comment by Tratcher** [comment]
Comments on closed issues are not tracked, please open a new issue with the details for your scenario.
