### ISSUE TITLE
xplat Integrated Windows Authentication (ntlm/Kerberos)

### ISSUE THREAD

**Issue by evil-shrike** [aspnet/Home#2824]
I haven't found any ticket for tracking the xplat Windows-auth support in aspnet/dotnet core. 
I understand that currently we have only out-of-the-box Windows auth support in IIS/IISExpress and http.sys and only on Windows.

There's a decent article in docs https://docs.microsoft.com/en-us/aspnet/core/security/authentication/windowsauth?branch=pr-en-us-3622&tabs=aspnetcore2x on how to configure Windows auth. But it says nothing about non-Windows use-cases. 

There're many issues here on Github and questions around on sites like SO on "how to implement Windows authentication in aspnet core on Linux". But all issues are closed with reasoning like "Kestrel doesn't implement Windows auth currenly, use IIS or https.sys". This is understandable but it's unclear what to do if we need to host an app on Linux and support integrated Windows auth (in intranet networks).

So there are several points which need to be addressed:
* what options do exist currently (at the time of 2.0/2.1) for getting integrated Windows authentication on Linux and other *nix OSes?
* what are plans (if any) for improving/adding such functionality?

I understand that strictly speaking this issue is related to Kestrel project probably, but it's more easily to find it here though. Moreover it's implementation details where Windows-auth support should live. 

Anyway it should be some source of information describing what to do with aspnet core apps on Linux for adding Windows auth.

Some additional info:
* middleware for ntlm support - https://github.com/OneBitSoftware/Microsoft.AspNetCore.Authentication.ActiveDirectory (ntlm only, Windows only - "Achieving server-side NTLM handshaking depends the Windows platform due to interop, dependency on domain-joined machines and secur32.dll")
* it's possible to authenticate via Kerberos on Linux - https://technet.microsoft.com/en-us/library/2008.12.linux.aspx
* there's Application Proxy with Kerberos Constrained Delegation in Windows Server and Azure AD which seems to solve such problems - https://blogs.technet.microsoft.com/applicationproxyblog/2015/09/21/all-you-want-to-know-about-kerberos-constrained-delegation-kcd/ but it's complex
* there're modules for Nginx (http://nginx.org/en/docs/http/ngx_http_upstream_module.html#ntlm) (requires commercial license) and Apache httpd (http://adldap.sourceforge.net/wiki/doku.php?id=mod_auth_ntlm_winbind) (it's unclear how stable it is) to add ntlm support
* It seems that Java has Kerberos support out-of-the-box - https://docs.oracle.com/javase/8/docs/technotes/guides/security/jgss/single-signon.html
* Java implementation for app servers - http://spnego.sourceforge.net/  (not sure how it relates to the previous point)

**Comment by davidfowl** [comment]
We don't have any plans AFAIK to support windows authentication when running on linux. There were discussions we had early on about how windows authentication could be supported in Kestrel, but that was by calling back into windows, not writing a fully managed implementation of ntlm, kerberos etc.

/cc @blowdart @DamianEdwards

**Comment by evil-shrike** [comment]
>We don't have any plans AFAIK to support windows authentication when running on linux.

This is a very pity, especially in contract with the support of Kerberos in Java... May I ask what are reasonings for such a decision?

**Comment by blowdart** [comment]
Because it would be too risky and too hard to secure. We're not about to take a dependency on Samba.

**Comment by khellang** [comment]
According to https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-active-directory-authentication, it looks like RHEL, SUSE and Ubuntu already have clients for Kerberos, though?

**Comment by Tratcher** [comment]
It's not impossible, but it's an extremely large and high risk work item. We're still working on Kestrel's fundamentals such as protocol correctness, stability and performance. Large, high risk features will need to wait.

**Comment by evil-shrike** [comment]
Well, ok, it's too early to expect Windows-auth in Kestrel, but we need some guidance on how to support Windows-auth on Linux in general in the meantime. 

I can see two approaches: 
* "reverse proxy" - all unauthenticated requests will be redirected to a Windows-IIS machine and then back - it can be achieved via some middleware I guess (on Linux side) and some simple app on Windows-side. But it would be nice to have some working and tested solution and not invent a wheel
* authenticate in web-server (hosting the aspnetcore app) - probably in Nginx/Apache modules  - again it'd иу nice to have a list of good and working modules for every common server

So any recommendations (or any other piece of advice) are highly desirable.

**Comment by Tratcher** [comment]
Your first scenario could be accomplished using OpenIdConnect and an auth server like [IdentityServer4](http://docs.identityserver.io/en/release/).

**Comment by Eilon** [comment]
This issue was moved to aspnet/Security#1622
