### ISSUE TITLE
Case-insensitive authentication schemes

### ISSUE THREAD

**Issue by khellang** [aspnet/Home#2827]
Why are authentication schemes case-sensitive?

This means the following code (taken from [the ASP.NET Core 2.0 templates](https://github.com/aspnet/Templates/blob/4fc52aa79ec17511ccd8c1c14b2118797d4045a3/template_feed/Microsoft.DotNet.Web.ProjectTemplates.2.0/content/StarterWeb-CSharp/Controllers/AccountController.cs#L307-L313)) doesn't work:

```csharp
public IActionResult ExternalLogin(string provider, string returnUrl = null)
{
    // Request a redirect to the external login provider.
    var redirectUrl = Url.Action(nameof(ExternalLoginCallback), "Account", new { returnUrl });
    var properties = _signInManager.ConfigureExternalAuthenticationProperties(provider, redirectUrl);
    return Challenge(properties, provider); // <-- Will blow up because of case-sensitive matching.
}
```

The code above works for `/login/GitHub`, but not `/login/github`, which is pretty trippy.

Would you be willing to make this configurable?

**Comment by khellang** [comment]
It might be harder than I'd hoped for since the auth options themselves [are hard-coded to `StringComparer.Ordinal`](https://github.com/aspnet/HttpAbstractions/blob/2326783a04d4532fce57a5799957a6c5e86291f1/src/Microsoft.AspNetCore.Authentication.Abstractions/AuthenticationOptions.cs#L22) 😢

**Comment by Eilon** [comment]
Ultimately, URLs are case-sensitive. And, of course, filenames on many OSes are case-sensitive. We usually try to obey the "rules" of whatever the physical entity is (though we're undoubtedly inconsistent about that anyway).

So, really all I can say is that my guess is that the answer to "why is it that way" is that we flipped a coin, wrote it some way, no one complained for a long time, so it stayed 😄

**Comment by khellang** [comment]
> Ultimately, URLs are case-sensitive.

Except... they're not? At least not according to [the routing docs](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/routing):

> Literal text other than route parameters (for example, `{id}`) and the path separator `/` must match the text in the URL. Text matching is case-insensitive and based on the decoded representation of the URLs path.

Anyway, the problem isn't case-sensitive routes, it's that the `AuthenticationSchemeProvider` and `AuthenticationOptions` uses `StringComparer.Ordinal` by default and there's no way to change it.

**Comment by rynowak** [comment]
> Ultimately, URLs are case-sensitive.

URLs **are** case-sensitive. Routing makes as an opinionated choice to be case-insensitive so that things like `/home/about` can map to `HomeController::About()`

**Comment by khellang** [comment]
So, in practice they're not? Just like HTTP methods are also case-sensitive, but isn't treated as such anywhere in the ASP.NET Core code base? 😊

Anyway, that's not my point. I wonder if there's a reason why schemes are case sensitive. Is it more secure? Was it just an oversight?

**Comment by BlueMarmalade** [comment]
The way it is written with comparing string keys in dictionaries is that in using StringComparer.Ordinal instead of allowing case-insensitive string keys with something like StringComparer.OrdinalIgnoreCase, you could have a situation where two keys would be compared to be the same. I'm just a noob, so this is just speculation with no knowledge of url and dns and routing etc;  could it be that because urls are not case sensitive, a hacker could create a similar url that would actually not be correct if it was not case sensitive? Or/and that this dictionary is used for other things also than urls?

**Comment by khellang** [comment]
This issue isn't about URLs 😝 I just linked the code from the official ASP.NET Core templates to showcase the problem.

The issue is about the case-sensitive default when storing and looking up authentication schemes and whether we can make it configurable or move to a case-insensitive default (perhaps in 3.0, as it would be a breaking change).

**Comment by khellang** [comment]
At the very least, I'd love to see a protected ctor in `AuthenticationSchemeProvider` that takes a `StringComparer` (where the public ctor just passes `StringComparer.Ordinal`), that way I can swap the provider without having to reimplement everything.

**Comment by davidfowl** [comment]
@HaoK and @Tratcher are there any good reasons for scheme names to be case sensitive or was this just an oversight? It's a breaking change to make them case-insensitive but I'm not sure we care that "cookies" and "COOKIES" are different authentication schemes.

**Comment by Tratcher** [comment]
It was an arbitrary but conscious decision about 5 years ago.

@khellang your example seems a bit contrived. Those values are enumerate from available schemes directly into the HTML on the login page, then the user clicks on one and it returns to the ExternalLogin. At no point in this flow is anybody typing these values, nor is their casing expected to be changed by any intermediaries and browsers and transports treat them as case sensitive. Do you have a real world repro where the casing is a problem?

The only place I've seen this be a problem is when developers are typing in raw strings in their Startup or  controller code, and those are things they catch before deployment because it never works otherwise. We haven't had any complaints of intermittent failures due to casing.

**Comment by khellang** [comment]
> Those values are enumerate from available schemes directly into the HTML on the login page

Is that always a valid assumption though?

> Do you have a real world repro where the casing is a problem?

Yes, I have an identity API that doesn't have any UI. A customer tried to hit the endpoint using a lowercase URI. All our routes are attribute-based and lowercase, so it was naturally expected that the social auth endpoint was lowercase as well. Instead of being redirected to the proper provider, the customer got back a 500 response because the parameter didn't match a scheme name. I've since done the normalization myself, but that's not what I was expecting.

Again, this isn't about case-sensitive URIs. It just happened to be how I found out that the schemes were case-sensitive. As I mentioned; not even HTTP methods are treated as case-sensitive, even though the RFC states that they are, so why would auth schemes be treated that way?

Of course, there could be a good reason. That's why I'm asking 😄 

If not, I can't see a good reason why it couldn't be made configurable somehow. Either by exposing a property on `AuthenticationOptions` or having a ctor on `AuthenticationSchemeProvider` that accepts a `StringComparer`.

**Comment by Tratcher** [comment]
The reason is that we had to pick one, so we picked one that would be simplest for middleware implementors. Changing it doesn't just affect our components, it affects the whole ASP.NET & ASP.NET Core auth ecosystems. 

This isn't the sort of thing that could be configurable either, it's baked into the overall auth contract. The infrastructure, 1st and 3rd party auth handlers, and consuming applications all need to behave consistently.

I don't expect this to change until a major version, and even then we'd need a compelling reason.

**Comment by khellang** [comment]
> This isn't the sort of thing that could be configurable either, it's baked into the overall auth contract. The infrastructure, 1st and 3rd party auth handlers, and consuming applications all need to behave consistently.

Can you expand on that? Why can't I just change `StringComparer.Ordinal` to `StringComparer.OrdinalIgnoreCase` [in `AuthenticationSchemeProvider`](https://github.com/aspnet/HttpAbstractions/blob/9f64c69a2a1005aed3b044209bbb228210d9a510/src/Microsoft.AspNetCore.Authentication.Core/AuthenticationSchemeProvider.cs#L35) (as I've already done locally)? it works fine with 6-7 different schemes. I'm not sure how this affects anything but my application?

Do you mean people are relying on this to differentiate their auth schemes? I.e. they have different auth handlers for `Cookies` and `CookieS`?

**Comment by Tratcher** [comment]
I mean that the same comparison likely exists in other places, such as in 3rd party application or middleware code. All implementors need to use the same type of comparison or you'll get subtle case mismatch bugs.

**Comment by khellang** [comment]
> I mean that the same comparison likely exists in other places, such as in 3rd party application or middleware code. All implementors need to use the same type of comparison or you'll get subtle case mismatch bugs.

I think I'm terribly slow, or I'm missing something here. Do you have an example? How can a 3rd party application or middleware access the configured schemes without using `AuthenticationOptions` or `IAuthenticationSchemeProvider`?

**Comment by HaoK** [comment]
Well for example, we use named options to lookup the AuthenticationSchemeOptions per scheme, named options are also case sensitive.  

So a specific example of a subtle breaking change here would be ConfigureApplicationCookie is explicitly configuring the "Identity.Application" scheme.  So if you only are normalizing the scheme provider on the auth side to be "identity.application", the options lookup will now be wrong.  So you probably also at a minimum need to implement your own IOptionsMonitor which also normalizes.

**Comment by khellang** [comment]
No, nothing is registered using lowercase. Everything is still stored just like before, but lookup is done using lowercase.

**Comment by khellang** [comment]
I'll send a PR adding a protected ctor to `AuthenticationSchemeProvider` and we can use that as a discussion point. That will give me what I need without having to reimplement the entire class. I feel like we're talking past each other here...

**Comment by Eilon** [comment]
I'm more of a bystander here, but is there enough value here to warrant a change, regardless of any breaking change concerns?

We might all be able to agree that case-insensitive would have been a better choice, but given that a choice was made, why would we change it?

**Comment by HaoK** [comment]
That's sort of my opinion as well, but I think @khellang is just asking for us to make it slightly easier for him to tweak this behavior.  I think his PR idea is a good place to start for the discussion

**Comment by khellang** [comment]
> We might all be able to agree that case-insensitive would have been a better choice, but given that a choice was made, why would we change it?

It's unfortunate that the choice was made, but as long as I'm the only one complaining and I can get a way to tweak the behavior without having to maintain a non-trivial amount of code, I'm happy! 😊

**Comment by HaoK** [comment]
@khellang we didn't haven't much time at all to spend on making it easy to extend the default implementations of the core auth stack in 2.0, so I'm hopefully some minor tweaks should do the trick for you...

It would be a bigger deal if we are missing an extensibility point/interface
