### ISSUE TITLE
Initial install of kvm, kpm and k breaks

### ISSUE THREAD

**Issue by ppumkin** [aspnet/Home#283]
I just did a fresh Ubutnu 14.10 and followed the Home section to install Mono and then KVM using

```curl -sSL https://raw.githubusercontent.com/aspnet/Home/master/kvminstall.sh | sh && source ~/.kre/kvm/kvm.sh```

I did a **kvm upgrade** and it came back saying I need **unzip** - So I installed unzip via apt but then the next time I ran kvm upgrade it came back saying

```
root@vnext:~# kvm upgrade
Determining latest version
Latest version is 1.0.0-beta2
KRE-Mono.1.0.0-beta2 already installed.
Cannot find KRE-Mono.1.0.0-beta2, do you need to run 'kvm install 1.0.0-beta2'?
````

I cannot use `k` or `kpm`

I had to fix this manually, I just took a lucky shot and deleted the directory KRE-Mono... under ~/.kre/packages rerun kvm upgrade and this time it installed properly.

Now I have `k` and `kpm`

**Comment by jpinho** [comment]
I had the same issue on a linux machine (Ubuntu 14.04 x64 vmlinuz-3.13.0-36-generic).

Your workaround worked! Your are awesome ;) !!!

**Comment by sixlighthouses** [comment]
Thanks this helped me out, would never have thought of that
