### ISSUE TITLE
What is the mean of the Side-by-side app versioning when targeting .NET Core. and does not Full .net support side by side?

### ISSUE THREAD

**Issue by WaedSaleh** [aspnet/Home#2832]
Hi All, 
I want to know what they main when they said What is the mean of the Side-by-side app versioning when targeting .NET Core. and does not Full .net support side by side?

**Comment by davidfowl** [comment]
I can install multiple versions of .NET Core on the same machine and have various applications target those versions of .NET Core. If I have 2 applications A and B, A can target .NET Core 1.1 and B can target .NET Core 2.0.

This isn’t possible with .NET Framework today. It’s a Windows component and only one version can exist on the machine at a time. This means that you can run one application with .NET Framework 4.6 and 4.7 on the same machine. Every version of .NET Framework replaces the previous one. As a result it’s hard to make changes without breaking existing running applications.

**Comment by glennc** [comment]
Closing this as I think it was answered. You can re-open it, make another issue, or post here again if you need more help.

**Comment by a-patel** [comment]
As per your explanation, 
We cannot host two different applications,  A (NET Framework 4.6) and B (NET Framework 4.7) in IIS same time.

**Comment by kolexinfos** [comment]
@davidfowl If you ask me, I think that your statement sounds contradictory, would you mind given another scenario for your .Net Framework explanation, you mentioned in the first sentence that it was not possible, then you went ahead to say it is possible but I think with one application?

**Comment by davidfowl** [comment]
I’m not sure what you mean? Which part was unclear?

**Comment by kolexinfos** [comment]
**This isn’t possible with .NET Framework today.**  Negative

**This means that you can run one application with .NET Framework 4.6 and 4.7 on the same machine** Postive

**Comment by davidfowl** [comment]
Ah that’s a typo, it should be can’t.
