### ISSUE TITLE
Error deploy site in server

### ISSUE THREAD

**Issue by MansoorJafari** [aspnet/Home#2833]
Hi
after publish  site and put to server  give me this error.

<img width="980" alt="screen shot 1396-11-08 at 23 15 56" src="https://user-images.githubusercontent.com/15822698/35500970-a0b763c2-04ed-11e8-8f8b-d15093233daa.png">
 please help me.

**Comment by Tratcher** [comment]
Did you have trouble with the instructions on the error page?

**Comment by MansoorJafari** [comment]
@Tratcher 
Thanks for your answer. I have trouble after publish site and put to server.
Works well on my device locally, just have error in win server.
my Startup.cs is this
`if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
                app.UseWebpackDevMiddleware(new WebpackDevMiddlewareOptions
                {
                    HotModuleReplacement = true
                });
            }
            else
            {
                app.UseExceptionHandler("/Home/Error");
            }`

after delete else statement page not loaded and gives me 403.1 error.

**Comment by Tratcher** [comment]
What server are you using? Here are the troubleshooting instructions for IIS https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/troubleshoot

**Comment by MansoorJafari** [comment]
I'm using windows server 2012

**Comment by MansoorJafari** [comment]
An error occurred while starting the application.
AggregateException: One or more errors occurred. (Webpack dev middleware failed because of an error while loading 'aspnet-webpack'. Error was: Error: Cannot find module 'aspnet-webpack'
at Function.Module._resolveFilename (module.js:538:15)
at Function.Module._load (module.js:468:25)
at Module.require (module.js:587:17)
at require (internal/module.js:11:18)
at Object.<anonymous> (C:\WINDOWS\TEMP\vt0hiogs.umy:83:19)
at __webpack_require__ (C:\WINDOWS\TEMP\vt0hiogs.umy:20:30)
at createWebpackDevServer (C:\WINDOWS\TEMP\vt0hiogs.umy:62:26)
at C:\WINDOWS\TEMP\5et1uyuh.c1b:114:19
at IncomingMessage.<anonymous> (C:\WINDOWS\TEMP\5et1uyuh.c1b:133:38)
at emitNone (events.js:106:13)


give me this error

**Comment by Eilon** [comment]
This issue was moved to aspnet/JavaScriptServices#1504
