### ISSUE TITLE
DependencyInjection - Add Feature  for multiple registrations of service - named service

### ISSUE THREAD

**Issue by luizfbicalho** [aspnet/Home#2834]
It would be useful to have multiple service registrations for the same interface, many DependencyInjection containers implement this feature, so it woudn't be hard to implement.

Here are some examples where this feature would be useful

1) I have one property in my customer database that stores the name of the service that I use to validate the customer order, each customer has it's own validation ( by value, by quantity, for example) and this way I can configure it by customer.

2) I have some logwriter Services, (E-Mail, Event Viewer, file, Database) and I want to pass them all in a constructor of the controller, to log the services to all services.

My idea of implementation is to have this Methods:

`IEnumerable<T> GetServices<T>();`
`IEnumerable<T> GetService<T>(string name);`
`IDictionary<string,T> GetServiceRegistrations<T>(); // this should return the service and the registration name`

In addition to this, I have some extensions that I use in unity that I think would be useful, for example 

If I have a base class Animal, and two subclasses Dog and Cat, I could register many validation services using the interface IValidator<in T>, for example

`AnimalRegistrationComplete:IValidator<Animal>`

`DogRegistrationComplete:IValidator<Dog>`
`CatRegistrationComplete:IValidator<Cat>`

and It would be useful to have another version of GetServices<T> that instead of using the equal operator, could use the isSubClassOf operator, this way if I call  GetServices<IValidator<Dog>>, I should receive two services, the DogRegistrationComplete and the AnimalRegistrationComplete

**Comment by Zoxive** [comment]
You can register multiple of the same interface, then you can use IEnumerable<IInterface> as your dependancy

I typically then have an Enum type on that interface for the name/type.

Heres a quick example of the factory that then returns the specific type

```csharp
services.AddSingleton<IExportService, CsvExportService>();
services.AddSingleton<IExportService, XmlExportService>();
services.AddSingleton<IExportService, JsonExportService>();
///

public class ExportServiceFactory : IExportServiceFactory
{
    private readonly Dictionary<ExportType, IExportService> _exportServices;

    public ExportServiceFactory(IEnumerable<IExportService> exportServices)
    {
        _exportServices = exportServices.ToDictionary(x => x.Type);
    }

    public IExportService Get(ExportType tpe)
    {
        if (_exportServices.TryGetValue(type, out var exportService))
        {
            return exportService;
        }

        throw new NotSupportedException($"Unsupported export service type \"{type}\".");
    }
}
```

Its typically not a good idea to pull in IServiceProvider as a direct dependency and then inside your classes call GetRequiredService<>() manually, you want your dependencies as constructor parameters.

**Comment by DamianEdwards** [comment]
As pointed out, this has been discussed before and the underlying reasons for not doing it have not changed. If you wish to have DI features like this (and others) we recommend you use a 3rd-party IoC container that supports these features.
