### ISSUE TITLE
ASP.NET Core 2 app created using VS 2017 "Empty" template fails to run on .NET Core runtime 2.0.5

### ISSUE THREAD

**Issue by sandersaares** [aspnet/Home#2839]
1. Create a new ASP.NET Core 2 Web Application project in Visual Studio 2017 using the "Empty" template.
1. Execute `dotnet publish`
1. In a Windows Server 2016 container with the .NET Core runtime (version `microsoft/dotnet:2.0-runtime-nanoserver-sac2016`) execute `dotnet WebApplication2.dll`

Expected result: the created empty web app starts.

Actual result: 

```
Error:
  An assembly specified in the application dependencies manifest (WebApplication2.deps.json) was not found:
    package: 'Microsoft.ApplicationInsights.AspNetCore', version: '2.1.1'
    path: 'lib/netstandard1.6/Microsoft.ApplicationInsights.AspNetCore.dll'
  This assembly was expected to be in the local runtime store as the application was published using the following target manifest files:
    aspnetcore-store-2.0.0-linux-x64.xml;aspnetcore-store-2.0.0-osx-x64.xml;aspnetcore-store-2.0.0-win7-x64.xml;aspnetcore-store-2.0.0-win7-x86.xml
```

The same command (`dotnet WebApplication2.dll`) works on my development PC.

Development environment versions:

```
.NET Command Line Tools (2.1.4)

Product Information:
 Version:            2.1.4
 Commit SHA-1 hash:  5e8add2190

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.4\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.5
  Build    : 17373eb129b3b05aa18ece963f8795d65ef8ea54
```

Runtime environment versions:

```
Microsoft .NET Core Shared Framework Host

  Version  : 2.0.5
  Build    : 17373eb129b3b05aa18ece963f8795d65ef8ea54
```

**Comment by natemcmaster** [comment]
This looks like a duplicate of https://github.com/dotnet/designs/issues/10. ` microsoft/dotnet:2.0-runtime-nanoserver-sac2016` does not include the ASP.NET Core shared runtime store, which is why the error says...

> This assembly was expected to be in the local runtime store 

To solve this:

Option 1 - disable runtime store publishing (see https://github.com/dotnet/designs/issues/10.) This assembly was expected to be in the local runtime store as the application
Option 2 - use `microsoft/aspnetcore:2.0-nanoserver-sac2016`

**Comment by sandersaares** [comment]
Thank you for the hint! I had no idea there was an entirely separate image for ASP.NET Core but in hindsight it makes perfect sense.

I wonder if this could somehow be more discoverable? No good idea how to make it so, though.
