### ISSUE TITLE
FileInfo.Length returns always 0

### ISSUE THREAD

**Issue by ThatDeveloper** [aspnet/Home#2840]
# FileInfo.Length return always 0

FileInfo.Length return always 0. I tried it with a MVC Web App and a console application.
FileInfo is not null and the path is correct too. I tried to stream a video but if I don't get the range I can't stream it.

# General

.NET Core 2.0 & 2.0.5
Mac & Windows

# Sample

```
var fi = new FileInfo(Path.Combine("Videos/sample.mp4"));
Console.WriteLine(fi.Length);
Console.ReadLine();
```

**Comment by pranavkm** [comment]
Does the file exist? `fi.Exists`

**Comment by Eilon** [comment]
This bug probably belongs in https://github.com/dotnet/corefx.

@ThatDeveloper - please check what the "current directory" is - that is probably throwing off the check. You can check `fi.DirectoryName` to see what directory it thinks the file is in.

**Comment by ThatDeveloper** [comment]
@pranavkm As I mentioned the file exists and .Exists return true.
@Eilon The directory is right. I checked it multiple times. (In visual studio on Windows and on Mac with Rider) Both show the right directory. (Once a /Users/, and once a D:)

**Comment by Eilon** [comment]
Ok closing this issue then.
