### ISSUE TITLE
 Need two Http requests to set cookies

### ISSUE THREAD

**Issue by tanyado** [aspnet/Home#2841]
In .NET Core, I have to send a two http requests manually – only the second post request will succeed.

    HttpClientHandler handler = new HttpClientHandler();
    handler.Credentials = new NetworkCredential(userName, userPass);

    HttpClient client = new HttpClient(handler);
    client.BaseAddress = new Uri(baseUri);
 
    // PROBLEM HERE: 
    await client.PostAsync(requestUri, null); // The extra post request to set cookie
    var response = await client.PostAsync(requestUri, new StringContent(Body(), Encoding.UTF8, "application/json"));

The server sets a cookie on the initial 401 challenge and rejects the subsequent credentialed request if it lacks this cookie.

Fiddler Traces are in this folder: https://microsoft-my.sharepoint.com/:f:/p/tad/Ehuec61zdD9Fp1Vlf6QI718BynEnS-HF3tL4w9FXGgH7Eg?e=tsH1fU

**Comment by Eilon** [comment]
Hi @tanyado , is this an issue with HttpClient or with ASP.NET Core?

cc @Tratcher in case you have any idea on this?

**Comment by Tratcher** [comment]
This issue was moved to dotnet/corefx#26722
