### ISSUE TITLE
Loading list from appsettings.xml fails

### ISSUE THREAD

**Issue by sandersaares** [aspnet/Home#2842]
I haven an appsettings.xml file with the following structure:

```
<config>
    <aaa>value1</aaa>
    <aaa>value2</aaa>
</config>
```

I wish to load this using the XML configuration loading pattern documented at https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?tabs=basicconfiguration

Expected behavior: a list is loaded, accessible as `aaa:0` and `aaa:1`

Actual behavior: System.FormatException occurred, Message=A duplicate key 'aaa' was found.

**Comment by Eilon** [comment]
This issue was moved to aspnet/Configuration#770
