### ISSUE TITLE
Asp.Net Core template not working for project name with spaces

### ISSUE THREAD

**Issue by HappyNomad** [aspnet/Home#2845]
I'm running the latest official releases (as of today) of Visual Studio and the packages.  The exception message says:

Assets file 'C:\Users\Me\Documents\Visual Studio 2017\Projects\My Solution\WebAPI (some thing)\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.

When I remove the ` (some thing)` from the project name then it works.

**Comment by natemcmaster** [comment]
This appears to be an issue with [NuGet](https://github.com/nuget/home/issues), not ASP.NET Core.

**Comment by Eilon** [comment]
Closing as external.
