### ISSUE TITLE
Discussion for ASP.NET Core 2.1 high-level planning

### ISSUE THREAD

**Issue by danroth27** [aspnet/Home#2846]
https://github.com/aspnet/Announcements/issues/288

**Comment by John0King** [comment]
Can you guys design an  official  Module System for Asp.Net Core ?   without that , anyone just need to  create their own module system

**Comment by davidfowl** [comment]
We have no plans to do so. Look at orchard.core, it’s has a well designed module system and also has a bunch of modules.

**Comment by Eilon** [comment]
You can find OrchardCore here: https://github.com/OrchardCMS/OrchardCore

**Comment by John0King** [comment]
@davidfowl  @Eilon   OrchardCore is a great project, and It is really big, and it's under beta I think. (I like their module system) but there are **no Document** tell me how the module system work ( currently  I don't understand how they control the DI ) .

If there an "official Module System" , I think that can make many component can  be use in  anywhere. and  will help spread .net as well .

**Comment by davidfowl** [comment]
> @davidfowl @Eilon OrchardCore is a great project, and It is really big, and it's under beta I think. (I like their module system) but there are no Document tell me how the module system work ( currently I don't understand how they control the DI ) .

@sebastienros can you comment on this?

**Comment by bruce-willis** [comment]
I've asked already at [roadmap](https://blogs.msdn.microsoft.com/webdev/2018/02/02/asp-net-core-2-1-roadmap/) post, however no response has been received.

> Hello! Just want to ask — maybe it’s better to improve the standard behaviour of simple Controller instead of adding a new attribute [ApiController]? Or it all about backward compatibility?

**Comment by danroth27** [comment]
@bruce-willis Correct, this is partly for compatibility reasons and also to provide an explicit indication that you are building a web API.

**Comment by khellang** [comment]
@danroth27 Is there a way to globally enable those conventions without using attributes? If not, I'd like to request it 😝 I only ever build APIs with MVC (there's never a V 😉) and would ❤ to avoid more attributes.

**Comment by danroth27** [comment]
I believe you could define your own controller base class that has the attribute and then derive all your controllers from that. Would that be sufficient?

**Comment by ChristopherRobinSuperStar** [comment]
Will be there sqldependency cache in core 2.1?

**Comment by sebastienros** [comment]
@John0King You are right, there is no document that explains how we control the DI.
You can find samples on how to use it in this samples repository https://github.com/OrchardCMS/OrchardCore.Samples. The idea is that your projects all have a `Startup` class that will behave exactly as any ASP.NET application in terms of services and middleware. It's just that you can have many of them, in separate modules.

I would not recommend anyone to create a modular framework. We have made it very simple and reusable in the Orchard Core Framework, and you just need to reference a single package to get the feature.

**Comment by danroth27** [comment]
@myrup One of the goals of the `[ApiController]` conventions is to make your web APIs more descriptive and predictable. With attribute routes it is immediately clear what requests can be routed to the web API. Convention-based routes can easily introduce a lot of ambiguity, where you unintentionally support requests to routes that you never intended. This restriction is setting us up to have better experiences around producing clean web API descriptions (like [OpenAPI specifications](https://github.com/OAI/OpenAPI-Specification/blob/master//versions/3.0.1.md)).

**Comment by myrup** [comment]
@danroth27 Usually I just assume whatever is marked public on my Controllers is published (unsafe) whether or not a route matches. I also see why it is easier (but certainly not required) with explicit routing to generate docs like swagger. 

It's a matter of taste, but I probably won't be using the [ApiController] attribute on my next api if I am forced to spell out identical routing patterns for my controllers (possibly creating inconsistencies). I hope you will consider a middleground!

**Comment by khellang** [comment]
I'm curious why you feel forced to "spell out identical routing patterns" in your controllers. Could you share an example of what you mean? Are you not using a `RouteAttribute` on your controller?

**Comment by myrup** [comment]
@khellang `RouteAttribute` is required with `[ApiController]`, so I meant explicitly declaring the sub routes as attributes. I'm just brainstorming how to keep it DRY without unintentionally exposing routes. The standard example becomes something like:
```c#
public class ValuesController : ControllerBase
{
    public IEnumerable<string> Index() // only GET /values
    {
        return new string[] { "value1", "value2" };
    }

    public string Get(int id) // only GET /values/42
    {
        return "value";
    }

    public void Post([FromBody] string value) // only POST /values
    {
    }

    public void Put(int id, [FromBody] string value) // only PUT /values/42
    {
    }

    public void Delete(int id) // only DELETE /values/42
    {
    }

    [HttpPost]
    public void DoSomeCustomStuff(int id) //only POST /values/42/dosomecustomstuff
    {
    }
}
```
I'm generally against magic words, but if it were up to me I'd go with it here for readability and consistency across controllers (unused actions are simply not declared). After trying to set routing for this up I realize it would be a lot prettier if `IRouteBuilder.MapRoute` allowed http method constraints. 

If I were to use the `[ApiController]` attribute, I see myself sprinkling `Route("[controller]")` on all controllers (super-classable) and `[HttpMethod("[action]")]` on actions. I don't know if its possible to somehow default to those.

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
