### ISSUE TITLE
DataProtection - small optimization

### ISSUE THREAD

**Issue by sdrapkin** [aspnet/Home#2847]
[DataProtection - Extensions - TimeLimitedDataProtector.cs](https://github.com/aspnet/DataProtection/blob/d0dea3ca5fb605b8d6f22f410e1baf3917e55aa6/src/Microsoft.AspNetCore.DataProtection.Extensions/TimeLimitedDataProtector.cs#L103)

Change to

```csharp
expiration = embeddedExpiration;
```

**Comment by davidfowl** [comment]
Send a pull request please 😄
