### ISSUE TITLE
Support for .NET Native?

### ISSUE THREAD

**Issue by hyperlight** [aspnet/Home#285]
Can you provide insight into the plans for .NET Native support for ASP.NET and ASP.NET vNext? Will .NET Native be available for vNext and future versions, or will it support previous generations of ASP.NET?

Is there any timing information you can provide on this support? We're very eager to try .NET Native on our large production ASP.NET clusters.

**Comment by davidfowl** [comment]
There are no short term plans to bring .NET native to ASP.NET.

**Comment by aleks-sidorenko** [comment]
.NET Native was designed with speeding up WinRT application in mind. Hopefully some day it will be used with .NET Core as well.
But .NET Core has many goals now: make it really xplat is much more valuable for now IMHO.

**Comment by gaevoy** [comment]
+1 voting for .NET Native + ASP.NET

**Comment by davidfowl** [comment]
This is not going to happen in the short term. We can revisit when it's a more viable solution

**Comment by nawfalhasan** [comment]
This should be possible once [LLIC](https://www.dotnetfoundation.org/blog/announcing-llilc-llvm-for-dotnet) is out. It targets CoreCLR which is what ASP.NET 5 runs on.
