### ISSUE TITLE
Vue CLI SPA Template

### ISSUE THREAD

**Issue by jarrodldavis** [aspnet/Home#2850]
Hello ASP.NET Team,

I'd like to work on updating the [existing Vue SPA template] to use the new `3.0` version of [`@vue/cli`]. 

Before I just jumped in, I had some questions:

- Does updating this template align with your roadmap? If so, what release should I target for/when should I start? I would assume at the very least once `@vue/cli` releases a stable version (it's currently at `3.0.0-alpha.8`), but if I can (or should) start earlier, that's fine as well.
- As I understand, getting the Vue template to work with `@vue/cli` like the Angular and React templates do with their respective CLIs will require changes to both the [aspnet/Templating] and [aspnet/JavaScriptServices] repos. Is there any preferred way to coordinate these contributions? Should I send PRs to both repositories at the same time, or should I wait for one to be merged before sending the other?
- Currently, it appears the Angular and React templates have a `ClientApp` folder consisting of pre-generated output from their respective CLIs. Is this how other SPA CLI-based templates should be created moving forward, or should I look into invoking Vue's CLI `create` command as part of template generation? This would give users more control over the output since `@vue/cli` already has [quite a few substantial choices users can make].
- The Contributing Guide directs me to https://cla2.dotnetfoundation.org to sign the CLA, but that site appears to be down. Is that still the correct place for CLAs?

[existing Vue SPA template]: https://github.com/aspnet/templating/tree/a4427f5263c78ce7203e727a0bae106f530f22bd/src/Microsoft.AspNetCore.SpaTemplates/content/Vue-CSharp
[`@vue/cli`]: https://github.com/vuejs/vue-cli
[aspnet/Templating]: https://github.com/aspnet/templating
[aspnet/JavaScriptServices]: https://github.com/aspnet/JavaScriptServices
[quite a few substantial choices users can make]: https://github.com/vuejs/vue-cli#creating-a-new-project

**Comment by muratg** [comment]
cc @SteveSandersonMS

**Comment by muratg** [comment]
This issue was moved to aspnet/templating#302
