### ISSUE TITLE
"ng2-radio-group" import { Validator, ControlValueAccessor, Control } from "@angular/common";

### ISSUE THREAD

**Issue by prakashkaruppiah** [aspnet/Home#2859]
We used to ng2-radio-group, but we got the following error,

ERROR in node_modules/ng2-radio-group/CheckboxGroup.d.ts(1,10): error TS2305: Module '"D:/Angular-Workspace/code/node_modules/@angular/common/common"' has no exported member 'Validator'.
node_modules/ng2-radio-group/CheckboxGroup.d.ts(1,21): error TS2305: Module '"D:/Angular-Workspace/code/node_modules/@angular/common/common"' has no exported member 'ControlValueAccessor'.
node_modules/ng2-radio-group/CheckboxGroup.d.ts(1,43): error TS2305: Module '"D:/Angular-Workspace/code/node_modules/@angular/common/common"' has no exported member 'Control'.
node_modules/ng2-radio-group/RadioGroup.d.ts(2,10): error TS2305: Module '"D:/Angular-Workspace/code/node_modules/@angular/common/common"' has no exported member 'Validator'.
node_modules/ng2-radio-group/RadioGroup.d.ts(2,21): error TS2305: Module '"D:/Angular-Workspace/code/node_modules/@angular/common/common"' has no exported member 'ControlValueAccessor'.
node_modules/ng2-radio-group/RadioGroup.d.ts(2,43): error TS2305: Module '"D:/Angular-Workspace/code/node_modules/@angular/common/common"' has no exported member 'Control'.

how can i solve this problem? Please help us

**Comment by Eilon** [comment]
Hi @prakashkaruppiah , can you share more info about what you're trying to do? Is this using the ASP.NET Core JavaScriptServices feature?

cc @SteveSandersonMS in case you have thoughts.

**Comment by SteveSandersonMS** [comment]
@prakashkaruppiah This sounds like an Angular and/or TypeScript usage question, rather than anything specific to ASP.NET. Would you be able to review the Angular/TypeScript docs, and if needed, raise your question with one of those groups?

I'll close this because it doesn't sound related to ASP.NET, but if you have reason to believe it is ASP.NET-specific, could you please more details? Thanks!

**Comment by prakashkaruppiah** [comment]
We refer this website 
https://www.npmjs.com/package/ng2-radio-group

and we used ng2-radio-group angular 4 application.

i got following error

ERROR in node_modules/ng2-radio-group/CheckboxGroup.d.ts(1,10): error TS2305: Module '"D:/Angular-Workspace/code/node_modules//common"' has no exported member 'Validator'.
node_modules/ng2-radio-group/CheckboxGroup.d.ts(1,21): error TS2305: Module '"D:/Angular-Workspace/code/node_modules//common"' has no exported member 'ControlValueAccessor'.
node_modules/ng2-radio-group/CheckboxGroup.d.ts(1,43): error TS2305: Module '"D:/Angular-Workspace/code/node_modules//common"' has no exported member 'Control'.
node_modules/ng2-radio-group/RadioGroup.d.ts(2,10): error TS2305: Module '"D:/Angular-Workspace/code/node_modules//common"' has no exported member 'Validator'.
node_modules/ng2-radio-group/RadioGroup.d.ts(2,21): error TS2305: Module '"D:/Angular-Workspace/code/node_modules//common"' has no exported member 'ControlValueAccessor'.
node_modules/ng2-radio-group/RadioGroup.d.ts(2,43): error TS2305: Module '"D:/Angular-Workspace/code/node_modules//common"' has no exported member 'Control'.
