### ISSUE TITLE
Nuget package restore failed for version 1.0.0

### ISSUE THREAD

**Issue by mostafaasad** [aspnet/Home#286]
I am unable to to compile the bookstore project as it does restore the nuget package successfully.

Could you please advise how to get it work?
![image](https://cloud.githubusercontent.com/assets/7625530/5847824/b5344ece-a225-11e4-843d-239be97a1a1f.png)

Regards,
Mostafa

**Comment by Eilon** [comment]
In Visual Studio's Output Window can you select the Package Manager Log and see if there's anything there about what the error might be?

BTW what's the "bookstore" project? Do you mean Music Store?

**Comment by davidfowl** [comment]
This looks like NuGet v2, not ASP.NET 5

**Comment by mostafaasad** [comment]
Hi Eilon,
Yes it is musicstore project. I will send the error log later. A lot of compile errors due to the nuget restore failure.

Regards,
Mostafa

**Comment by mostafaasad** [comment]
The following errors are shown in the output window while restoring the packages.
![image](https://cloud.githubusercontent.com/assets/7625530/5865579/a7e6af32-a2de-11e4-8356-edf864fa0624.png)

**Comment by suhasj** [comment]
Can you show the Nuget feed enabled for your project something like below ?

![error](https://cloud.githubusercontent.com/assets/1919946/5868413/c198a5ce-a25d-11e4-9f7b-6edc745b5ffb.png)

**Comment by danroth27** [comment]
@mostafaasad  Closing for now. Please provide the requested info and we will take another look. Thanks.
