### ISSUE TITLE
StatusCodePagesExtensions.UseStatusCodePages causes a white screen of death for internal server errors

### ISSUE THREAD

**Issue by Matthew-Bonner** [aspnet/Home#2862]
StatusCodePagesExtensions.UseStatusCodePages causes a white screen of death for internal server errors which is not what I expected given:
https://github.com/aspnet/Diagnostics/blob/dev/src/Microsoft.AspNetCore.Diagnostics/StatusCodePage/StatusCodePagesExtensions.cs#L17

```
public class HomeController : Controller
{
    public IActionResult Index()
    {
        throw new Exception();
    }
}

public void Configure(IApplicationBuilder app, IHostingEnvironment env)
{
    app.UseStatusCodePages();
    app.UseMvc();
}
```

When visiting / using IIS Express.

ASP.NET Core 2.

**Comment by Tratcher** [comment]
UseStatusCodePages does not handle exceptions, you want UseExceptionHandler for that. The 500 you see is generated by the server after it catches the exception.

**Comment by Matthew-Bonner** [comment]
That seems odd given the amount of references to error 500 whenever this method is mentioned.

https://docs.microsoft.com/en-us/aspnet/core/fundamentals/error-handling#configuring-status-code-pages

The comment linked to in the repo should be updated then if it isn't handling the 500 error as the comment implies that it will.

**Comment by Tratcher** [comment]
Yeah, I can see the confusion. If the app code generates a 500 it will be handled, but your app is generating an exception, not a 500. The 500 you see is a last ditch effort from the server to handle the exception.

**Comment by Matthew-Bonner** [comment]
I'll lob this over to the docs repo and raise an issue and create a PR to include this information. Thanks for your help.
