### ISSUE TITLE
Just a word about incessant confusion

### ISSUE THREAD

**Issue by Korporal** [aspnet/Home#2868]
I read [this article](http://no-kill-switch.ghost.io/current-state-of-net-through-not-so-rose-colored-glasses/) recently and found that it mirrors my own experiences, yes I know it's a year old.

It hit home so well that I emailed the blog author, here's a copy of my email to him - a cry for help I guess!

_I'm a very experienced developer and just beginning to open the Pandora's box of the whole "ASP.NET Core" thing, I found your article after I became disillusioned._

_I have been frustrated to hell with the "documentation" Microsoft have for this, in particular the ASP.NET Core stuff. It is almost impossible to follow any of the examples or tutorials, just a glance at the comments at the bottom of any documentation page tells me right away that others are struggling - and many of them know more than I about this area!_

_Then I read about how ASP.NET Core will [no longer be able to use .Net Framework](https://www.theregister.co.uk/2017/05/09/dot_net_compatibility/) and then I read about how actually it will and frankly I have no idea what to believe anymore!_

_Almost every article I dig up on the subject of ASP.NET Core emphasizes something different, points out different "issues" contains different advice, suggest different updates, workarounds._

_The entire eco-system is full of ifs and buts and updates and versions of this or that and service packs, cryptic **just-type-what-I-say** command lines and so on._

_I have truly struggled for several days to actually find a solid example of how to create a new ASP.NET Core web application using VS 2017, every one I find has either numerous comments posted about issues or is so out of date that I know I'll have problems._

_I'd really love to see a follow up to your original article, its almost a year later now so an "anniversary update" would be fascinating!_

Documentation never used to be interactive like it is now, every week something documented changes and the documentation no longer applies or contains incorrect version of this or that and so on.

Only a few months ago I began to follow some Microsoft tutorial, the app would not build, I had to check version info for umpteen different things, ensure I had the "latest" .Net Core or VS 2017 update and so on.

I'm looking at a pretty simple private project, the issues are far more daunting when it comes to trying to adopt these technologies at work, right now there's no way we can even consider this.

UPDATE:

By way of an example, I just [stumbled upon this](https://docs.microsoft.com/en-us/aspnet/core/spa/angular?tabs=visual-studio) while I was exploring Angular and ASP.NET Core.

I can see the callout "This documentation is about the release candidate of the Angular template." yet I am not (it seems or am I ?) using a RC but a released template (VS 2017 15.5.6). So right away I am asking myself "which parts of the walkthru are required and which parts are purely associated with the fact that it's describing the RC?".

I created a new app using the Angular template, it built and ran fine but is that correct? does the RC documentation contain any steps that I must perform? For example the RC documentation shows several command line examples but it is far from obvious which are specific to the RC template and which are naturally associated with this kind if project in general.

Has nobody at MS considered that documentation be considered a _deliverable_? a deliverable to be included _with_ the released item? rather than an afterthought to be hastily tweaked when people "have time"?

Why not house RC documentation in a distinct docs.draft.documentation.com site and then move and update documents to docs.microsoft.com site at a time that coincides with the item being officially released?

This could be a huge help to developers who are trying to keep up with the changes.

UPDATE:

See also:

https://github.com/aspnet/JavaScriptServices/issues/1527

**Comment by Matthew-Bonner** [comment]
The code is open source, it is the best documentation there is.

**Comment by DrSensor** [comment]
I think what he mean is to make documentation and user guide as part of the release cycle. It's best to update all docs,  user guide, and example before doing major release so any code example in the docs can be reproduce without error. 
Also some suggestion, maybe at each (or each 2~3) minor release there will be community review&discussion about state of art of the current web technology. I'm bit surprised there is no *Use Webpack* section in [here](https://docs.microsoft.com/id-id/aspnet/core/tutorials/#client-side-development).

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
