### ISSUE TITLE
Naming Convention Issue

### ISSUE THREAD

**Issue by livarcocc** [aspnet/Home#2869]
_From @abhaldar on February 11, 2018 18:56_

## Minor Naming Fix for AntiForgery package
Currently -> AutoValidateAnti**f**orgeryTokenAttribute
ShouldBe -> AutoValidateAnti**F**orgeryTokenAttribute

_Copied from original issue: dotnet/cli#8590_

**Comment by Eilon** [comment]
Hi, the naming scheme we prefer is with the lower-case `f` because we consider `antiforgery` to be a single term. Some attributes in MVC use a capital `F` for historical reasons.

cc @rynowak @mkArtakMSFT
