### ISSUE TITLE
is order of httpresponse matter?

### ISSUE THREAD

**Issue by mhamri** [aspnet/Home#2870]
vs2017, asp.net core 2. I was scratching my head about why this doesn't work, turned out the order matters and status code should placed before the writeAsync.  is it correct? it shouldn't build the response before it write to it?

this works 
```C#
app.UseExceptionHandler(builder =>
{
    builder.Run(async context =>
    {
        context.Response.StatusCode = 500;
        await context.Response.WriteAsync("some error happend");
    });
});
```
![image](https://user-images.githubusercontent.com/8991783/36104698-b31a3704-104d-11e8-8969-1f170024b45c.png)

this doesn't works 

```C#
app.UseExceptionHandler(builder =>
{
    builder.Run(async context =>
    {
        await context.Response.WriteAsync("some error happend");
        context.Response.StatusCode = 500;
    });
});
```

![image](https://user-images.githubusercontent.com/8991783/36104740-c6b8c514-104d-11e8-873c-a02292a3ba97.png)

**Comment by Tratcher** [comment]
This is correct. The response body is not buffered by default so the status code and all headers must be set first. If generating your response body is likely to fail then consider doing it in memory and then writing it to the body.
