### ISSUE TITLE
Error: Missing Method SetHeadersAndLog in FileResultExecutorBase

### ISSUE THREAD

**Issue by shripathi-kamath** [aspnet/Home#2874]
I had software implemented for streaming files using the [technique described here](http://bit.ly/2BpClDz), and it worked fine with ASP.NET Core 1.0

It worked fine with ASP.NET Core 2.0 when first released.  I had to modify the SetHeadersAndLog method to include a null for the third argument that became necessary.

Upgrading to VS2017 15.5.6  (SDK 2.1.4, Runtime 2.0.5) seems to have broken it.  The source still compiles but yields a runtime exception that indicates that the method is missing.

I am attaching a VS project that I created from the standard template and used the .NET Standard option instead of .NET Core.

Any pointers would be appreciated.  I verified that the binaries are what I expect them to be.

[SetHeadersAndLog.zip](https://github.com/aspnet/Home/files/1718074/SetHeadersAndLog.zip)

**Comment by Eilon** [comment]
@shripathi-kamath can you show what error + stack trace you got?

**Comment by shripathi-kamath** [comment]
If you run the supplied application, it should appear.

(Un)fortunately, I unzipped and ran the same .ZIP I sent you, and it no longer appears.  That is weird, given that it was reproduced unfailingly on two different machines

Sorry to have wasted your time.  You may close this issue.  Should it recur, I'll update accordingly

**Comment by Eilon** [comment]
Sorry you ran into the issue, but hopefully it's fixed! Please do re-open or log a new issue if you see this again, and include the error/stack trace - it'll be easier for us to investigate more quickly that way. Thanks!

**Comment by GKNetaphor** [comment]
I am seeing the exception.  Here are the exception details -

An unhandled exception occurred while processing the request.
MissingMethodException: Method not found: 'System.ValueTuple`3<Microsoft.Net.Http.Headers.RangeItemHeaderValue,Int64,Boolean> Microsoft.AspNetCore.Mvc.Internal.FileResultExecutorBase.SetHeadersAndLog(Microsoft.AspNetCore.Mvc.ActionContext, Microsoft.AspNetCore.Mvc.FileResult, System.Nullable`1<Int64>, System.Nullable`1<System.DateTimeOffset>, Microsoft.Net.Http.Headers.EntityTagHeaderValue, Boolean)'.
WebApplication4.FileCallbackResult+FileCallbackResultExecutor.ExecuteAsync(ActionContext context, FileCallbackResult result)

Stack Query Cookies Headers
MissingMethodException: Method not found: 'System.ValueTuple`3<Microsoft.Net.Http.Headers.RangeItemHeaderValue,Int64,Boolean> Microsoft.AspNetCore.Mvc.Internal.FileResultExecutorBase.SetHeadersAndLog(Microsoft.AspNetCore.Mvc.ActionContext, Microsoft.AspNetCore.Mvc.FileResult, System.Nullable`1<Int64>, System.Nullable`1<System.DateTimeOffset>, Microsoft.Net.Http.Headers.EntityTagHeaderValue, Boolean)'.
WebApplication4.FileCallbackResult+FileCallbackResultExecutor.ExecuteAsync(ActionContext context, FileCallbackResult result)
WebApplication4.FileCallbackResult.ExecuteResultAsync(ActionContext context) in FileCallbackResult.cs
+
            return executor.ExecuteAsync(context, this);
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeResultAsync>d__19.MoveNext()
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeNextResultFilterAsync>d__24.MoveNext()
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResultExecutedContext context)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeNextResourceFilter>d__22.MoveNext()
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeFilterPipelineAsync>d__17.MoveNext()
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeAsync>d__15.MoveNext()
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Builder.RouterMiddleware+<Invoke>d__4.MoveNext()
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware+<Invoke>d__7.MoveNext()

Show raw exception details
System.MissingMethodException: Method not found: 'System.ValueTuple`3<Microsoft.Net.Http.Headers.RangeItemHeaderValue,Int64,Boolean> Microsoft.AspNetCore.Mvc.Internal.FileResultExecutorBase.SetHeadersAndLog(Microsoft.AspNetCore.Mvc.ActionContext, Microsoft.AspNetCore.Mvc.FileResult, System.Nullable`1<Int64>, System.Nullable`1<System.DateTimeOffset>, Microsoft.Net.Http.Headers.EntityTagHeaderValue, Boolean)'.
   at WebApplication4.FileCallbackResult.FileCallbackResultExecutor.ExecuteAsync(ActionContext context, FileCallbackResult result)
   at WebApplication4.FileCallbackResult.ExecuteResultAsync(ActionContext context) in C:\SetHeadersAndLog\WebApplication4\WebApplication4\FileCallbackResult.cs:line 77
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeResultAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResultFilterAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResultExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()

**Comment by davidfowl** [comment]
@GKNetaphor can you show your project file? Method missing usually results in mixing and matching the wrong versions.

**Comment by GKNetaphor** [comment]
C:\SetHeadersAndLog\WebApplication4>dotnet --info
.NET Command Line Tools (2.1.4)

Product Information:
 Version:            2.1.4
 Commit SHA-1 hash:  5e8add2190

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.4\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.5
  Build    : 17373eb129b3b05aa18ece963f8795d65ef8ea54

**Comment by GKNetaphor** [comment]
Here is the project file -
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net461</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="wwwroot\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore" Version="2.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.0.2" />
  </ItemGroup>

  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="2.0.2" />
  </ItemGroup>

</Project>

**Comment by GKNetaphor** [comment]
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net461</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="wwwroot\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore" Version="2.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.0.2" />
  </ItemGroup>

  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="2.0.2" />
  </ItemGroup>

</Project>

**Comment by GKNetaphor** [comment]
@davidfowl I posted the project file above.

**Comment by davidfowl** [comment]
@GKNetaphor what are the repro steps? What code causes the exception to happen? If you have a minimal repro that would be great as well. Are you running from the command line or using visual studio? What version of .NET Framework do you have installed (.NET  4.6.1/4.6.2/4.7 etc)

**Comment by GKNetaphor** [comment]
@davidfowl download the zip file attached by @shripathi-kamath.  Compile the solution and run it.

**Comment by davidfowl** [comment]
>  @davidfowl download the zip file attached by @shripathi-kamath. Compile the solution and run it.

I can reproduce it.

> I am using .NET 4.6.1. I also show the dotnet --info results above so you know the dotnet environment on my machine.

That information unfortunately isn't relevant to the .NET Framework version.

**Comment by pranavkm** [comment]
The exception message 

> MissingMethodException: Method not found: 'System.ValueTuple`3<Microsoft.Net.Http.Headers.RangeItemHeaderValue,Int64,Boolean> Microsoft.AspNetCore.Mvc.Internal.FileResultExecutorBase.SetHeadersAndLog(Microsoft.AspNetCore.Mvc.ActionContext, Microsoft.AspNetCore.Mvc.FileResult, System.Nullable`1<Int64>, System.Nullable`1<System.DateTimeOffset>, Microsoft.Net.Http.Headers.EntityTagHeaderValue, Boolean)'.
WebApplication4.FileCallbackResult+FileCallbackResultExecutor.ExecuteAsync(ActionContext context, FileCallbackResult result)

Likely indicates https://github.com/dotnet/standard/issues/567 i.e you are targeting .NET 461, but running against .NET 471. The issue has some workarounds to fix this. I think an EAP version of .NET 4.7.2 is also available that should address this.

**Comment by shripathi-kamath** [comment]
That does not appear to be the case, since I am targeting 4.6.1 and running 4.7.1 @pranavkm

**Comment by pranavkm** [comment]
> That does not appear to be the case, since I am targeting 4.6.1 and running 4.7.1

Isn't this exactly the issue reported in the linked item?

> Applications that target the .NET Framework 4.6.1 and use .NET Standard libraries may experience System.TypeLoadException exceptions when running on the .NET Framework 4.7.1

**Comment by shripathi-kamath** [comment]
Except, I have no problem running in that combination.

I started this issue, and created the sample app.  A couple days later, when I tried it again, during which a couple of Microsoft updates and reboots occurred,

I did not see the issue thereafter.

My SDK, .NET Core runtime are 2.1.4 and 2.0.5 resp.

And Get-ChildItem "HKLM:SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full\" | Get-ItemPropertyValue -Name Release | ForEach-Object { $_ -ge 461308 }

yields true, indicating 4.7.1 for the .NET runtime

**Comment by Eilon** [comment]
@shripathi-kamath right, we think that's the problem. There's a bug that if you app **targets** 4.6.1 but the machine has 4.7.1 **installed**, it doesn't work.

**Comment by shripathi-kamath** [comment]
Perhaps I am not communicating that, or I am misunderstanding the nuance.

I was targeting 4.6.1 and running on a machine that had an unknown version (suspected to be 4.7.0)
That one had a problem.

I upgraded, moved to 4.7.1.

I am now targeting 4.6.1. and running on a machine that has 4.7.1 (see PS script), and **I no longer see the problem**

But, if that is strictly an accident, I understand.

**Comment by GKNetaphor** [comment]
I am targeting 4.6.1. and running on a machine that has 4.7.1.  Rebooted my VM several times and this combination did not work for me.  That is when I posted the exception to the issue in GitHub.

Later I installed a few pending windows updates.  And rebooted after that.  Now things seem to be working just fine.  I am not getting the exception.

Thanks,
GK

**Comment by pranavkm** [comment]
Sweet. Sorry for the confusion!
