### ISSUE TITLE
[JsonPatch]: PathHelpers.NormalizePath should allow spaces and \\ characters

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Home#2876]
Consider
```
public class Person
{
    [JsonProperty("Person Name")]
    public string Name { get; set; }
}
```

A patch can be sucessfully applied to this property as 
```C#
var doc = new JsonPatchDocument
{
    Operations = 
    {
        new Operation("add", "/Person Name", null, "New Name"),
    },
};

doc.ApplyTo(person); // This works correctly.
doc.Add("Person Name", "New Name") fails
```

Same deal with back slashes. The invalid char check in that method is kinda unncecessary.

**Comment by mkArtakMSFT** [comment]
@ajaybhargavb, can you please look into this? Thanks!

**Comment by ajaybhargavb** [comment]
Yup. The spec https://tools.ietf.org/html/rfc6901 does not disallow whitespace or backslashes. I'll send a PR.

**Comment by ajaybhargavb** [comment]
aspnet/JsonPatch@63f03228106c61b6af2965c874f09758f7a5439e
