### ISSUE TITLE
Default Model Name

### ISSUE THREAD

**Issue by hishamco** [aspnet/Home#2877]
What I see quite often in almost if it's in all the Razor Pages, that we need to specify the model using the `@model`
```html
@page
@model ProductModel
```
for Product.cshtml, and
```html
@page
@model CustomerModel
```
for Customer.cshtml

Can we introduce a new option that allow us to set the model by convention `{PageName}Model` unless we need to use a different name

**Comment by mkArtakMSFT** [comment]
Thanks @hishamco for your proposal. @rynowak this can eliminate the need for the explicit `@model` type definition. Will anything prevent us from supporting this?

**Comment by mkArtakMSFT** [comment]
@DamianEdwards FYI

**Comment by Eilon** [comment]
@mkArtakMSFT can you move to the appropriate repo? Not sure if this is MVC or Razor.

**Comment by DamianEdwards** [comment]
This should be in MVC.

**Comment by hishamco** [comment]
@Eilon can I move this to MVC, or @mkArtakMSFT has a suitable way to move it

**Comment by Eilon** [comment]
This issue was moved to aspnet/Mvc#7386
