### ISSUE TITLE
Self referencing loop error

### ISSUE THREAD

**Issue by Phylum123** [aspnet/Home#2883]
Hey guys, I found an issue with JSON, Razor Pages (Core 2) and EF (Core 2). I know all about self referencing loops and usually it can be solved with configuration. I added configuration and it did not work, I am still getting the error. Below you can see my configuration in "Startup.cs":

```
`        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {

            services.AddMvc().AddJsonOptions(options =>
            {
                options.SerializerSettings.ContractResolver = new Newtonsoft.Json.Serialization.DefaultContractResolver();
                options.SerializerSettings.ReferenceLoopHandling = ReferenceLoopHandling.Serialize;
                options.SerializerSettings.PreserveReferencesHandling = PreserveReferencesHandling.Objects;
            });

            services.AddDbContext<CapitalMarketsRMBSContext>(options =>
                options.UseSqlServer(Configuration.GetConnectionString("CapitalMarketsRMBSContext")));

            //services.AddDbContext<CapitalMarketsReportsContext>(options =>
            //    options.UseSqlServer(Configuration.GetConnectionString("CapitalMarketsReportsContext")));

        }`
```
and when I make this simple call, I get the error:

`        public void OnGet()
        {
            Pool = _context.Rmbspool.Include(p => p.RmbsCertificateRates).First();
        }`

Here are both entities involved in the call:

```
`    public partial class RmbsPool: EntityBase
    {
        //*** Omitted other properties for clarity ***

                /// <summary>
        /// Child RmbsCertificateRates where [RMBSCertificateRate].[PoolId] point to this entity (FK_RMBSCertificateRate_RMBSPool)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<RmbsCertificateRate> RmbsCertificateRates { get; set; } // RMBSCertificateRate.FK_RMBSCertificateRate_RMBSPool

    }
`
```
And the "Many" class:

```
` [Serializable]  
public partial class RmbsCertificateRate: EntityBase
    {
        //*** Omitted other properties for clarity ***
               [Required]
        [Display(Name = "Pool ID")]
		public int PoolId
		{
			get { return _poolId; }
			set { SetProperty(ref _poolId, value); }
		}

        /// <summary>
        /// Parent RmbsPool pointed by [RMBSCertificateRate].([PoolId]) FK_RMBSCertificateRate_RMBSPool)
        /// </summary>
        public virtual RmbsPool RmbsPool { get; set; } // FK_RMBSCertificateRate_RMBSPool
    }`
```

**Comment by Eilon** [comment]
Can you show the error that you're getting? Please show the exception message and stack trace.

**Comment by Phylum123** [comment]
An unhandled exception occurred while processing the request.

JsonSerializationException: Self referencing loop detected with type 'System.Collections.Generic.List`1[RMBSWeb.Main.Models.RmbsCertificateRate]'. Path 'data[0].RmbsPool'.
Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CheckForCircularReference(JsonWriter writer, object value, JsonProperty property, JsonContract contract, JsonContainerContract containerContract, JsonProperty containerProperty)

Stack Query Cookies Headers
JsonSerializationException: Self referencing loop detected with type 'System.Collections.Generic.List`1[RMBSWeb.Main.Models.RmbsCertificateRate]'. Path 'data[0].RmbsPool'.
Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CheckForCircularReference(JsonWriter writer, object value, JsonProperty property, JsonContract contract, JsonContainerContract containerContract, JsonProperty containerProperty)
Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeISerializable(JsonWriter writer, ISerializable value, JsonISerializableContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeISerializable(JsonWriter writer, ISerializable value, JsonISerializableContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeDictionary(JsonWriter writer, IDictionary values, JsonDictionaryContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, object value, Type objectType)
Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, object value, Type objectType)
Newtonsoft.Json.JsonConvert.SerializeObjectInternal(object value, Type type, JsonSerializer jsonSerializer)
Newtonsoft.Json.JsonConvert.SerializeObject(object value, Formatting formatting, JsonConverter[] converters)
DevExtreme.AspNet.Mvc.Builders.DataSources.StoreDataSourceBuilder.GetStoreDefinition()
DevExtreme.AspNet.Mvc.Builders.DataSources.StoreDataSourceBuilder.AttachNestedOptionsToParent(IDictionary<string, object> parentOptions)
DevExtreme.AspNet.Mvc.Builders.DataGridBuilder.DataSource(IEnumerable data, String[] key)
RMBSWeb.Main.Pages.PoolEditor_Page+<<ExecuteAsync>b__0_6>d.MoveNext() in PoolEditor.cshtml
+
                        @(Html.DevExtreme().DataGrid<RmbsCertificateRate>()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Mvc.Razor.HelperResult.WriteTo(TextWriter writer, HtmlEncoder encoder)
DevExtreme.AspNet.Mvc.Builders.OptionsOwnerBuilder.RunWithSingleWriter(Action<TextWriter> action)
DevExtreme.AspNet.Mvc.Builders.OptionsOwnerBuilder.AssignTemplate(string optionName, RazorBlock block)
DevExtreme.AspNet.Mvc.Builders.FormSimpleItemBuilder.Template(RazorBlock templateContent)
RMBSWeb.Main.Pages.PoolEditor_Page.<ExecuteAsync>b__0_0(FormItemsFactory<RmbsPool> items) in PoolEditor.cshtml
+
                items.AddSimple()
DevExtreme.AspNet.Mvc.Builders.OptionsOwnerBuilder.CustomCollection<F>(string optionName, Action<F> configurator)
DevExtreme.AspNet.Mvc.Builders.FormBuilder.Items(Action<FormItemsFactory<T>> configurator)
RMBSWeb.Main.Pages.PoolEditor_Page+<ExecuteAsync>d__0.MoveNext() in PoolEditor.cshtml
+
    @(Html.DevExtreme().Form<RmbsPool>()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Mvc.Razor.RazorView+<RenderPageCoreAsync>d__16.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Mvc.Razor.RazorView+<RenderPageAsync>d__15.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter.GetResult()
Microsoft.AspNetCore.Mvc.Razor.RazorView+<RenderAsync>d__14.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor+<ExecuteAsync>d__22.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeResultAsync>d__19.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeNextResultFilterAsync>d__24.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResultExecutedContext context)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeNextResourceFilter>d__22.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeFilterPipelineAsync>d__17.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeAsync>d__15.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Builder.RouterMiddleware+<Invoke>d__4.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware+<Invoke>d__7.MoveNext()

**Comment by davidfowl** [comment]
MvcOptions for JSON settings won't affect your DevExtreme component (unless they read those options which it seems like they don't). It looks like that exception is coming from the `@Html.DevExtreme().Form()` or DataGrid component which is using JSON.NET directly.

**Comment by Eilon** [comment]
Hi. We're closing this issue as no response or updates have been provided in a timely manner and we have been unable to reproduce it. If you have more details and are encountering this issue please add a new reply and re-open the issue.
