### ISSUE TITLE
Support multiple key decryption certificates without X509Store

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/Home#2884]
When using the X509Store, you can decrypt an old key encrypted XML key with multiple certificates. 

In https://github.com/aspnet/DataProtection/pull/299, we added support for decrypting without using the X509Store for one certificate (the one passed to .ProtectKeysWithCertificate()). This doesn't yet support multiple certs though. It wouldn't be too hard to support this.

Usage:
```c#
.AddDataProtection()
.ProtectKeysWithCertificate(certificate)
.UseKeyDecryptionCertificates(oldCert1, oldCert2, oldCert3)
```

**Comment by blowdart** [comment]
```c#
.AddDataProtection()
    .ProtectKeysWithCertificate(certificate)
    .UnprotectKeysWith(oldCert1, oldCert2, oldCert3)
```

For consistency? And obviously the protection key would automatically be part of the internal unprotect list

@GrabYourPitchforks  ?

**Comment by blowdart** [comment]
Yup, arrays are good.
