### ISSUE TITLE
Segmentation Fault on Raspbian for Benchmarks

### ISSUE THREAD

**Issue by UncleSamSwiss** [aspnet/Home#2886]
Running the ASP.NET Core Benchmarks on Raspbian causes a segmentation fault for some URLs.

### How to reproduce
1. Get the latest source from https://github.com/aspnet/benchmarks
2. Compile the src/Benchmarks project with `dotnet publish -c Release -r ubuntu.16.04-arm` (tested on Windows only)
3. Set up the Raspberry Pi with the latest Raspbian
4. Install .NET Core (and dependencies) on Raspberry Pi:
 `sudo apt-get install -yq curl libunwind8 gettext`
 `curl -sSL -o dotnet.tar.gz https://dotnetcli.blob.core.windows.net/dotnet/Runtime/release/2.0.0/dotnet-runtime-latest-linux-arm.tar.gz`
 `sudo mkdir -p /opt/dotnet`
 `sudo tar zxf dotnet.tar.gz -C /opt/dotnet`
 `sudo ln -s /opt/dotnet/dotnet /usr/local/bin`
5. Copy the "published" files from step 2 (./Release/netcoreapp2.0/ubuntu.16.04-arm/publish) to the Raspberry Pi
6. Run the benchmarks with: `dotnet Benchmarks.dll /KestrelTransport=Sockets /Scenarios=StaticFiles /urls=http://*:8080`
7. Open a browser (tested with Chrome on Windows) and navigate to http://[raspi-address]:8080/1MB.txt
8. The browser will (in most cases) report that the server wasn't responding (`ERR_CONNECTION_REFUSED`) and on the Raspberry Pi the application crashes with a single line output: `Segmentation fault`

The same also happens for some other URLs, but sometimes the bug is not as reproducible as with the 1MB.txt.

A quick debug with gdb revealed not much (except that it may be in memcmp and/or the stack is corrupt):
`Thread 10 "dotnet" received signal SIGSEGV, Segmentation fault.`
`[Switching to Thread 0x58971450 (LWP 1285)]`
`0x76fba404 in memcmp () from /usr/lib/arm-linux-gnueabihf/libarmmem.so`
`(gdb) bt`
`#0  0x76fba404 in memcmp () from /usr/lib/arm-linux-gnueabihf/libarmmem.so`
`#1  0x00000000 in ?? ()`
`Backtrace stopped: previous frame identical to this frame (corrupt stack?)`

Not sure where the bug comes from; it could be the runtime, Kestrel or ASP.NET Core - I'm posting it here, feel free to move the issue if another repository is more accurate.

**Comment by Eilon** [comment]
@muratg / @halter73 - any ideas on this? Or how to get more info?

**Comment by muratg** [comment]
Any chance of getting a process dump from the Pi? Also curious, does it reproduce **less often** with 5MB.txt file?

cc @anurse any thoughts?

**Comment by anurse** [comment]
Nothing comes to mind.

**Comment by UncleSamSwiss** [comment]
@muratg no, it happens also for 5MB all the time when benchmarking (sometimes the first request goes through but then it crashes, but most of the time it is already the first request that crashes the application).

If you tell me how exactly to create the dump, I'll try to provide you with the details. From what I can tell it is completely reproducible - if you happen to have a Raspberry Pi lying around somewhere in your offices you should see it immediately.

**Comment by halter73** [comment]
The good news is that capturing a memory dump on a segfault is pretty trivial. If you're using bash to start the benchmarks, you should just be able to run `ulimit -c unlimited` beforehand to tell bash to dump cores of any size to a core.PID file.

This should allow us to examine the faulting callstack at the moment it crashes using lldb/libsosplugin.

**Comment by Eilon** [comment]
Hi. We're closing this issue as no response or updates have been provided in a timely manner and we have been unable to reproduce it. If you have more details and are encountering this issue please add a new reply and re-open the issue.
