### ISSUE TITLE
Increase MicrosoftNETCore to 2.1.0-preview1-02411+

### ISSUE THREAD

**Issue by benaadams** [aspnet/Home#2889]
Currently it looks like its `2.1.0-preview1-26213` which means you'll get bitten by this bug "Fix GC reproting for by-ref-like structs" https://github.com/dotnet/coreclr/pull/16231 and have errors which make no sense.

Looking at the merge train that's the version it was fixed at https://github.com/dotnet/coreclr/commits/release/2.1

/cc @davidfowl @pakrym @halter73

**Comment by Eilon** [comment]
I think this happens automatically in the build every week, but adding @natemcmaster and @ryanbrandenburg who know how this stuff flows through the system.

**Comment by natemcmaster** [comment]
@benaadams which package are you referring to? We don't consume dotnet/coreclr packages directly. We get new coreclr builds via builds of the Microsoft.NETCore.App shared framework. On dev, we are currently pulling in `Microsoft.NETCore.App/2.1.0-preview2-26130-04`

**Comment by benaadams** [comment]
Trying to workout which version this PR is in https://github.com/dotnet/coreclr/pull/16231

**Comment by benaadams** [comment]
On preview 2 it looks like nearest versioning commit is: [2.1.0-preview2-26207-11](https://github.com/dotnet/coreclr/commit/2138b3d7a31e13d6ca9d610a64fb258227371458)

```
<MicrosoftNETCoreRuntimeCoreCLRPackageVersion>
    2.1.0-preview2-26207-11
</MicrosoftNETCoreRuntimeCoreCLRPackageVersion>
```
Whereas Kestrel et al; as you say, are on
```
<MicrosoftNETCoreApp21PackageVersion>
    2.1.0-preview2-26130-04
</MicrosoftNETCoreApp21PackageVersion>
```
If that's the right reference, version number?

**Comment by benaadams** [comment]
The motivation is I have some very strange errors coming out of the aspnet code under high stress and not sure its this bug or the aspnet code; but they are non-deterministic and make not a lot of sense (changing where a struct is declared in outside code can get the HttpParser to fail internally with a parsing error or null ref by tweaking the declaration point; however only after several hundred requests). 

So I'd like to see if this resolves it before trying to dig too much deeper.

**Comment by pakrym** [comment]
I'll do this as part of the entire Pipeline move.

**Comment by pakrym** [comment]
Oops, this is for preview1. I think we can safely update to the latest PCP version of corefx we were built against. But I'm not sure that we are willing at this point.

**Comment by benaadams** [comment]
> Oops, this is for preview1. 

Either's fine; current dev is better for me :)

**Comment by benaadams** [comment]
e.g. PR was added to preview1 and preview2 after the current one aspnet is using

**Comment by natemcmaster** [comment]
cref https://github.com/dotnet/versions/tree/master/build-info/dotnet/product/cli/release/2.1-preview1

**Comment by benaadams** [comment]
Was added just before so should be ok for preview1

**Comment by benaadams** [comment]
![image](https://user-images.githubusercontent.com/1142958/36506588-fcf887e2-174e-11e8-8113-59e1a496ff12.png)

**Comment by Eilon** [comment]
Anything further required on this issue?

**Comment by natemcmaster** [comment]
I don't believ so. This was a point-in-time issue in the early previews.
