### ISSUE TITLE
Add AsMemory and AsSpan to StringSegment

### ISSUE THREAD

**Issue by davidfowl** [aspnet/Home#2890]
With Span and Memory on the rise we should look at bridging our existing types over to those types.

**Comment by gfoidl** [comment]
@davidfowl do you mean something like

```c#
public ReadOnlySpan<char> AsSpan() => Buffer.AsReadOnlySpan(Offset, Length);
public ReadOnlyMemory<char> AsMemory() => Buffer.AsReadOnlyMemory(Offset, Length);
```

and maybe Ctor-overloads that accept `Span<char>` to create a `StringSegment` of an existing span?

For methods like `StringSegment.IndexOf` a Span-based version could be faster -- would need some tests therefore (this should be a separate PR anyway).
