### ISSUE TITLE
Specify sub protocol for WebSocket Client

### ISSUE THREAD

**Issue by andylyonette** [aspnet/Home#2892]
Hi,

I can't work out how to specify the sub protocol when creating a client connect to a websocket endpoint. Is this possible like it is with this JavaScript client? (https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API/Writing_WebSocket_client_applications)

Thanks,
Andy

**Comment by davidfowl** [comment]
This should be moved to corefx. It's trivial to do so with the ClientWebSocket api:

```C#
var client = new ClientWebSocket();
client.Options.AddSubProtocol("protocol1");
client.Options.AddSubProtocol("protocol2");
```

**Comment by Eilon** [comment]
This issue was moved to dotnet/corefx#27364
