### ISSUE TITLE
EmailAddressAttribute.IsValid Method (Object) cannot validate hyphen at the beginning of domain name

### ISSUE THREAD

**Issue by ahmetbombaci-united** [aspnet/Home#2893]
Domain names cannot start with hyphen (ref: https://tools.ietf.org/html/rfc952)

However; IsValid method does not respect to this rule

Test case:

var checkMail = new System.ComponentModel.DataAnnotations.EmailAddressAttribute().IsValid("ahmet.bombaci@yahoo.-united.COM");

**Comment by Eilon** [comment]
This issue was moved to dotnet/corefx#27346
