### ISSUE TITLE
change default .net core web app template wwwroot folder name to static

### ISSUE THREAD

**Issue by vairamsvsjdo** [aspnet/Home#2896]
Regarding: https://github.com/aspnet/Home/issues/1636  #1636 
change default .net core web app template deploy wwwroot code to wwwroot
Is this backward compatibility needed as asp.net 5 is dead and asp.net core is what being developed.?
 Or change the name wwwroot to staticfiles as the default folder name

To address your issues more quickly, please open the issue in the most appropriate repository. These are some of the most common repos:

**Comment by Eilon** [comment]
Hi @vairamsvsjdo can you provide more info about your question?

Here are some points that might help clarify things:
* ASP.NET 5 was a pre-release product that that was renamed to ASP.NET Core 1.0, and then shipped (after several major changes)
* The `wwwroot` folder is a folder used in ASP.NET Core applications for static assets that are servable by the web server. This typically includes files such as JS, CSS, and image files

**Comment by vairamsvsjdo** [comment]
@Eilon The issue is with the wwwroot folder. web_deploy deploys wwwroot folder to a wwwroot folder within wwwroot folder  when published to app services.
One of the following should happen ideally:
1. It must be called as static files or something else other than wwwroot.
or
2. web deploy must move those static files to wwwroot folder.

**Comment by Eilon** [comment]
What is the actual issue? It's ok to have a `wwwroot\wwwroot` folder as long as everything is configured correctly. Are you having a specific problem? Can you share info on that?

**Comment by vairamsvsjdo** [comment]
Issue is in the default name used for "static files" folder. 
It is ok! It is quiet weird to have a wwwroot folder inside a wwwroot folder. There should be only one wwwroot folder. Can it be named "staticfiles" or "assets" instead of wwwroot like webpack or other bundling tools conventions use?

https://stackoverflow.com/questions/27639005/how-to-copy-static-files-to-build-directory-with-webpack

**Comment by Eilon** [comment]
@vairamsvsjdo I agree it's a bit weird, but it just happens to be that two different features each use that name. You can certainly rename the `wwwroot` folder in your app to anything you want, but once you move away from the default values, you have to start configuring more things.

I would recommend sticking with the current naming - I think you'll find it easier in the long run.

**Comment by vairamsvsjdo** [comment]
@Eilon 
What are the two different features that use it?
Thanks

**Comment by Eilon** [comment]
Web Deploy uses it for the entire web app, and also ASP.NET Core uses it for its static files.
