### ISSUE TITLE
Build and pack symbols for libuv

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/Home#2898]
The libuv packages we build do not have any corresponding debug symbols. We should explore how we can produce and pack debug symbols in a libuv symbols package and publish this to the symbols server.

cc @davidfowl @halter73 for libuv expertise
cc @Eilon @muratg for triage
cc @natemcmaster for including additional symbols packages in our build.

**Comment by halter73** [comment]
Are we going to include the symbols in the main nuget package or on a myget symbol server?

The [last time we discussed this](https://github.com/aspnet/Coherence-Signed/issues/152#issuecomment-171815651), I was told we were saving the old symbols so we could upload them to a symbol server retroactively.

**Comment by JunTaoLuo** [comment]
Apparently we produce these in the libuv-build-windows builds, e.g. $DROPSHARE\libuv-build-windows\dev\10077\build\symbols. We should package these into symbols nupkgs and publish these along with our other symbols.

**Comment by davidfowl** [comment]
@JunTaoLuo did we ever look at this?

**Comment by JunTaoLuo** [comment]
Nope we never triaged this. cc @muratg

**Comment by Eilon** [comment]
Should this bug go to one of our libuv repos?

**Comment by JunTaoLuo** [comment]
Yes, and we should do this the next time we build libuv

**Comment by muratg** [comment]
This issue was moved to aspnet/libuv-build#35
