### ISSUE TITLE
Problem with Install the K Version Manager (KVM) on FreeBSD 9.3

### ISSUE THREAD

**Issue by neyromant** [aspnet/Home#290]
I have a FreeBSD 9.3-RELEASE. I have installed mono version 3.10.0.
I tried to execute the command "curl -sSL https://raw.githubusercontent.com/aspnet/Home/master/kvminstall.sh | sh && source ~/.kre/kvm/kvm.sh" and I received an error "Badly placed ()'s."

**Comment by monoman** [comment]
Which shell are you using? Bash is well supported but others may have
incompatible script syntaxes.

Rafael Teixeira
O..:.)oooo

**Comment by neyromant** [comment]
I used sh. I try to run in bash and it works! Sorry, thank you!
