### ISSUE TITLE
Application startup exception: System.IO.FileLoadException: Could not load file or assembly 'Microsoft.Extensions.DependencyInjection.Abstractions

### ISSUE THREAD

**Issue by valeriob** [aspnet/Home#2900]
Hi,
i'm compiling an asp.net core application running on net461, if i compile it on a CI machine with just  vs2017 15.5.4 build tools installed, the output fails with that exception. When i compile that project on any other machine (dev, with the whole vs2017 installed) the output works correctly.  I think the assembly in the error is just one of many failing.

It tries to load version 1.1.0 of the assembly while the build process output the correct 2.0 version, i have no idea where to look!
the .deps.json file does not mention that version, nor does the app.config fiile.

[exception.txt](https://github.com/aspnet/websdk/files/1663184/exception.txt)

[OnTmsTrasportatori.Web.deps.json.txt](https://github.com/aspnet/websdk/files/1663188/OnTmsTrasportatori.Web.deps.json.txt)

**Comment by dallancarr** [comment]
This is problem with the autofac library targeting netstandard1.0

**Comment by valeriob** [comment]
Why it works on some machines and does not no a clean one with just build tools ?

**Comment by dallancarr** [comment]
Sorry my mistake, But you need a minimum of net461

**Comment by valeriob** [comment]
I would really like to learn how to diagnose this problems, can you point me to the point where you see the problem in the exception or dep.json file pls ?

Yes the sdk is there
![image](https://user-images.githubusercontent.com/1522516/36629970-96b1f286-195e-11e8-826e-e16da10b4b1b.png)

**Comment by dallancarr** [comment]
The buildtools don't package the sdk if I remember rightly so you must have installed the sdk manually on the build agent.

**Comment by valeriob** [comment]
As you can see it's all there

![image](https://user-images.githubusercontent.com/1522516/36630130-da60446c-1961-11e8-9bdb-7b73aecf9e0c.png)

**Comment by dallancarr** [comment]
THANKS. OnTmsTrasportatori.Web is attempting bind to 1.1.0 and fighting major version mismatch.Im still interested the autofac lib is the culprit which I mentioned earlier and you say it runs the most from vs, Can you test on the published output. also check references locally.

**Comment by dallancarr** [comment]
Looks like someone has hit this:
https://github.com/autofac/Autofac.Extensions.DependencyInjection/issues/24

**Comment by dallancarr** [comment]
https://github.com/autofac/Autofac.Extensions.DependencyInjection/blob/65352f4a5ad1b29386cfccb39944ce566e5a0e79/src/Autofac.Extensions.DependencyInjection/AutofacServiceProviderFactory.cs#L72

**Comment by dallancarr** [comment]
Are you using with or without ConfigureContainer?

http://autofac.readthedocs.io/en/latest/integration/aspnetcore.html#quick-start-without-configurecontainer

**Comment by dallancarr** [comment]
Maybe you can stop it autounifying...im interested you haven't hit any runtime issues in VS.

**Comment by valeriob** [comment]
I don't know if it's the same issue, i tried that repro and it gives a different exception : 

> Unhandled Exception: System.MissingMethodException: Method not found: 'System.IServiceProvider Microsoft.Extensions.DependencyInjection.ServiceCollectionContainerBuilderExtensions.BuildServiceProvider(Microsoft.Extensions.DependencyInjection.IServiceCollection)'.
   at Library.Startup.Build(IServiceCollection services)
   at ConsoleApp2.Program.Main(String[] args) in c:\Users\vborioni\Desktop\Repros-BuildServiceProvider\ConsoleApp2\Program.cs:line 13

I'm using it without ConfigureContainer.
Thanks for helping @dallancarr  but i do not unrestand what you meant by :  

> THANKS. OnTmsTrasportatori.Web is attempting bind to 1.1.0 and fighting major version mismatch.Im still interested the autofac lib is the culprit which I mentioned earlier and you say it runs the host from vs, Can you test on the published output. also check references locally.

In my folder Microsoft.Extensions.DependencyInjection.Abstractions is correctly 2.0, but looks like autofac wants 1.1, why does it happen ? shouldn't deps.json file avoid this ?

**Comment by dallancarr** [comment]
Just wanted you to assure me it running correctly outside vs on your local and not quirk of vs with the problem you are hitti g.

**Comment by dallancarr** [comment]
Could you run this workaround https://github.com/dazinator/Repros/tree/BuildServiceProvider-Workaround. Changing the app to target net461. Could you then take a dependency on Autofac.Extensions.DependencyInjection and configure a simple builder from the library package. Also see if this simple repo runs on the build agent.

**Comment by valeriob** [comment]
I'm sorry i do not yet have a repro i can share, but i would really like to learn a process to diagnose this, not going trial and error, i would like to read something, understand what's wrong and then act 😄

**Comment by valeriob** [comment]
Fixed by updating signalr from   
<PackageReference Include="Microsoft.AspNetCore.SignalR.Http" Version="1.0.0-alpha1-26873" />
to
<PackageReference Include="Microsoft.AspNetCore.SignalR" Version="1.0.0-preview1-final" />
Microsoft.AspNetCore.SignalR
 i just kept pealing out pieces of application until it worked... i wish i was able to diagnose what the problem was 😞

**Comment by valeriob** [comment]
And i have a repro, i know the problem is solved, the package was preview etc...
but i would like to learn how to diagnose those problems 😄 maybe @davidfowl can point me in the right path
[Autofac_dependency.zip](https://github.com/aspnet/Home/files/1761927/Autofac_dependency.zip)
