### ISSUE TITLE
Calls to WebHost.CreateDefaultBuilder override the ASPNETCORE_CONTENTROOT environment variable

### ISSUE THREAD

**Issue by Matthew-Bonner** [aspnet/Home#2901]
See javiercn's comments:

@Eilon This might be an integration bug. You should be able to change the content root by doing setting the ASPNETCORE_CONTENTROOT environment variable, but I believe that calling UseContentRoot override that.

Hosting just reads the content root from a setting in the host configuration. By default, hosting adds environment variables to the configuration and the call to UseContentRoot adds an in memory collection to the configuration after the environment variables, which I believe it means that value overrides the environment variable.

Given those two things together I think using CreateDefaultBuilder prevents you from using an environment variable to configure the content root, and that can be considered a bug, but I'll leave it to @Tratcher.

Copied from:
https://github.com/aspnet/Home/issues/2897#issuecomment-368148258

**Comment by Matthew-Bonner** [comment]
After testing it looks like you don't even need to call UseContentRoot in CreateDefaultBuilder. Can someone confirm this for *nix and mac?

**Comment by Eilon** [comment]
This issue was moved to aspnet/Hosting#1335

**Comment by Tratcher** [comment]
See https://github.com/aspnet/MetaPackages/issues/267
