### ISSUE TITLE
ConfigureAppConfiguration not taken into account.

### ISSUE THREAD

**Issue by whizkidwwe1217** [aspnet/Home#2903]
I tried to put kestrel urls into a separate json file so I don't have to recompile the project every time I change urls but the problem is that the ConfigureAppConfiguration doesn't work. I don't want to use the UseConfigurationMethod because I can't find a way to get the IHostingEnvironment to set up different settings for different environment. Putting these configurations in the Startup class doesn't seem to work either.

hosting.json
![image](https://user-images.githubusercontent.com/1977391/36637248-0796e97a-1a13-11e8-93ae-794d086bdb4c.png)

Doing it this way works:
![image](https://user-images.githubusercontent.com/1977391/36637237-d316ce72-1a12-11e8-8a8e-cfb20162c2d5.png)
dotnet run:
```
Now listening on: http://[::]:4000
Now listening on: http://[::]:5000
Now listening on: http://[::]:5001
Now listening on: http://[::]:5002
Now listening on: http://[::]:5003
```

But doing this will not:
![image](https://user-images.githubusercontent.com/1977391/36637239-e357b08a-1a12-11e8-8406-a597252d0d6e.png)
dotnet run:
```
Now listening on: http://localhost:5000
```

If I do the first method, how do I get the Hosting Environment?
![image](https://user-images.githubusercontent.com/1977391/36637396-f79e7602-1a15-11e8-8bfc-5f29c1036f2a.png)

**Comment by Eilon** [comment]
This issue was moved to aspnet/Hosting#1334
