### ISSUE TITLE
Memory Leak 

### ISSUE THREAD

**Issue by bluedog13** [aspnet/Home#2904]
I have two similar methods in a class that return null. Only difference is the method arguments they accept.

In both cases, the class that contains the below method implementation is added to the services collection in StartUp class using services.AddScope. The container is responsible to create the instance of the class and also dispose the object accordingly.

App starts with 90MB without any initial request (Diagnostics tool to monitor).

**Method-1 : No memory leak for 150 calls/minute**

public Task<MyObject> DoNothing()
{
   return null;
}

**Method-2 : Memory creeps up and reaches 800 MB for 150 calls/minute. Even after waiting for long, the memory usage is still around 750MB.**

public Task<MyObject> DoSomething(string args1,.....,string args10)
{
    return null;
}

**Based on my analysis, it seems to be the arguments that are passed to Method-2 that are not getting disposed and hence the memory leak**. I cannot change the signature of Method-2 due to existing interface restrictions. The total size of the arguments being passed to Method-2 is around 1.25MB for each request.

So my question and the help I am looking for is, how do I make sure the HttpRequest that contains the list of arguments to Method-2 are disposed and prevent this memory leak issue?

**Comment by Eilon** [comment]
@bluedog13 can you show a bit more about what your code looks like? Are you using MVC? What does your controller/action look like?

**Comment by Eilon** [comment]
Hi. We're closing this issue as no response or updates have been provided in a timely manner and we have been unable to reproduce it. If you have more details and are encountering this issue please add a new reply and re-open the issue.
