### ISSUE TITLE
How do I write a middleware ?

### ISSUE THREAD

**Issue by John0King** [aspnet/Home#2907]
in [this document](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/?tabs=aspnetcore2x) ,  it use `public async Task Invoke(HttpContext httpContext, IMyScopedService svc)`, 

in [this document](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/extensibility) it use `public async Task InvokeAsync(HttpContext context, AppDbContext db)` 

What's the different between `Invoke` and `InvokeAsync` ?
 I see `StaticFileMiddleware` and `RoutingMiddleware` use `Invoke` instead `InvokeAsync`

**Comment by Eilon** [comment]
Both `Invoke` and `InvokeAsync` method names are allowed, and do exactly the same thing. You can use one or the other, but not neither, and not both.

It's just a matter of convenience because some people like the `Async` suffix and some don't.

**Comment by John0King** [comment]
@Eilon   after a search on github , I find out that  `InvokeAsync` convention is add after  *[2.0.0-preview1](https://github.com/aspnet/HttpAbstractions/releases/tag/rel%2F2.0.0-preview1)*

Please update the document about this change

**Comment by Eilon** [comment]
@John0King you can file documentation issues at https://github.com/aspnet/Docs/issues and we will prioritize the suggestion for making documentation improvements.
