### ISSUE TITLE
Routes question

### ISSUE THREAD

**Issue by Montigomo** [aspnet/Home#2908]
Hello, why when i define routes like this:

```
public class Startup
	{
		public void ConfigureServices(IServiceCollection services)
		{
			services.AddMvc();
		}
		public void Configure(IApplicationBuilder app, IHostingEnvironment env)
		{
			if (env.IsDevelopment())
			{
				app.UseDeveloperExceptionPage();
			}

			app.UseMvc(routes =>
			{
				routes.MapRoute(
					name: null,
					template: "{category}",
					defaults: new { controller = "Home", action = "Index" }
					);

				routes.MapRoute(
					name: null,
					template: "",
					defaults: new { controller = "Home", action = "Index" }
					);

			});
		}
	}
```

```
	public class HomeController : Controller
	{
		static private int _calls = 0;

		public string Index()
		{
			return $"{++_calls}";
		}
	}
```

Home.Index() called two times per request?
project -> https://github.com/Montigomo/AcTest1

**Comment by Eilon** [comment]
@Montigomo the repo you point to is empty - did you forget to push?

One common cause for this is that the view being rendered has an img/CSS/JS link such as `<img src="" />`, which causes the browser's URL to be accessed again. Can you use your browser's dev tools to see what's causing the 2nd request?

**Comment by Montigomo** [comment]
>  the repo you point to is empty - did you forget to push?
corrected
there is no any <img src="" /> in example.
I thought than when asp/net route middleware found a (any one) route search are stopped and route invoked (if request). Try to run the sample project and when you run debug and refresh the page counter will show 3 instead 2. Why?
when rewrite like:
...
app.UseMvc(routes =>
			{
				routes.MapRoute(
					name: null,
					template: "",
					defaults: new { controller = "Home", action = "Index" }
					);

				routes.MapRoute(
					name: null,
					template: "",
					defaults: new { controller = "Home", action = "Index" }
					);

			});
...

page (controller) invoked one time.
But any random not bound to existing controller and action word in the template will cause double invoking the controller. Any like {mom} {god} or {dollar}. Why?

**Comment by Eilon** [comment]
Hi. We're closing this issue as no response or updates have been provided in a timely manner and we have been unable to reproduce it. If you have more details and are encountering this issue please add a new reply and re-open the issue.
