### ISSUE TITLE
Setting ASPNETCORE_ENVIRONMENT from cmd

### ISSUE THREAD

**Issue by Boombasteg** [aspnet/Home#2909]
Hello!

I need to change ASPNETCORE_ENVIRONMENT from cmd (by running bat file).
I have bat file like this:
```
...
SETX ASPNETCORE_ENVIRONMENT "tests"
SET ASPNETCORE_ENVIRONMENT "tests"
dotnet ef database drop -v --force --startup-project ../startProjectWebApi/
dotnet ef database update -v --startup-project ../startProjectWebApi/
...
```
I assume that it will:

-  change ASPNETCORE_ENVIRONMENT
-  recreate DB for tests (ConnectionString depends on ASPNETCORE_ENVIRONMENT and getting from appsettings.tests.json from startProjectWebApi)
-  run tests

But instead it recreate wrong DB specified for example in appsettings.dev.json.
I can see right ASPNETCORE_ENVIRONMENT  only after restart script/cmd.

How can I get real ASPNETCORE_ENVIRONMENT in same session of script after setting it?

Thanx.

**Comment by Eilon** [comment]
Hi @Boombasteg can you show what your Program.cs and Startup.cs look like?

**Comment by Boombasteg** [comment]
Hi @Eilon!

I think problem is not in these files..
Problem is in setting ASPNETCORE_ENVIRONMENT.
You can reproduce it in the following way: 
-  open cmd
-  run 'set'
-  remember value ASPNETCORE_ENVIRONMENT 
-  run SETX ASPNETCORE_ENVIRONMENT "some_new_value"
-  run 'set' one more time (in this cmd)
-  compare old and new ASPNETCORE_ENVIRONMENT.

I expect to see "some_new_value" but see old value.

-  open new cmd
-  run 'set'
-  you will see "some_new_value"

How can I see new value of ASPNETCORE_ENVIRONMENT in first instance of cmd?


P.S. If you still need to see my Program.cs and Startup.cs I will show you.

**Comment by Eilon** [comment]
Sorry I may have misunderstood. Is this just a question about how to set environment variables?

**Comment by Eilon** [comment]
I found this post on how SET and SETX work: https://superuser.com/questions/916649/what-is-the-difference-between-setx-and-set-in-environment-variables-in-windows

**Comment by Eilon** [comment]
In particular, the syntax `SET ASPNETCORE_ENVIRONMENT "tests"` doesn't look correct to me. It should be `SET ASPNETCORE_ENVIRONMENT=tests`

**Comment by Boombasteg** [comment]
Yes!

The problem was in syntax!

Globally it sets in this way:
`SETX ASPNETCORE_ENVIRONMENT new_value`

But for local using only this:
`SET ASPNETCORE_ENVIRONMENT=new_value`

:|

Thank you!

**Comment by Eilon** [comment]
Great!
