### ISSUE TITLE
ActivatorUtilities.CreateInstance no selecting the longest matching constructor

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Home#2915]
Consider:
```        
        public CookiePolicyMiddleware(RequestDelegate next, IOptions<CookiePolicyOptions> options)
        {
            Options = options.Value;
            _next = next;
            _logger = NullLogger.Instance;
        }
        
        public CookiePolicyMiddleware(RequestDelegate next, IOptions<CookiePolicyOptions> options, ILoggerFactory factory)
        {
            Options = options.Value;
            _next = next ?? throw new ArgumentNullException(nameof(next));
            _logger = factory.CreateLogger<CookiePolicyMiddleware>();
        }
```
This class is activated by UseMiddleware which calls Activator.CreateInstance.
https://github.com/aspnet/HttpAbstractions/blob/9119433ab778d7adf04c4601917809f2f4582a93/src/Microsoft.AspNetCore.Http.Abstractions/Extensions/UseMiddlewareExtensions.cs#L92

The shorter constructor is being used by default and logging doesn't work. Either constructor works if I comment out the other.

Our breaking change policy requires adding new constructors when adding new parameters.

**Comment by pranavkm** [comment]
Likely a dup of https://github.com/aspnet/Home/issues/2871.
