### ISSUE TITLE
The link to contributor license agreement is not working

### ISSUE THREAD

**Issue by skleanthous** [aspnet/Home#2917]
The link to sign the contributor license agreement in https://github.com/aspnet/Home/blob/dev/CONTRIBUTING.md is not working.

**Comment by Tratcher** [comment]
@eilon Should https://cla2.dotnetfoundation.org/ be https://cla.dotnetfoundation.org/ ?

**Comment by Eilon** [comment]
I will take a look and fix, thanks for the report!

**Comment by Eilon** [comment]
Fixed, thanks!
