### ISSUE TITLE
HTTP client - API error c# (A task was canceled.)

### ISSUE THREAD

**Issue by rajurh** [aspnet/Home#2918]
We are calling multiple API's in foreach loop and all API are of Async call. Now in the foreach loop due to some reason 1 API call has returned internal error and we are skipping that record and progressing with other requests in for loop. When the next loop continues the first API call we are getting error with "System.Threading.Tasks.TaskCanceledException: A task was canceled" and "Aggregation exception".

Code Snippet:
We are making Httpclient initialization per loop and object used multiple times in the loop.
using (var httpClientHelper = new HttpClientHelper(tokenService))

API call snippet:
var response = await httpClientHelper.GetAsync("http://xyz");

Help or thoughts on this will be much appreciated.

**Comment by Eilon** [comment]
This issue was moved to dotnet/corefx#27747
