### ISSUE TITLE
Additional information needed in building from source docs

### ISSUE THREAD

**Issue by JamesNK** [aspnet/Home#2919]
https://github.com/aspnet/Home/wiki/Building-from-source

A couple of things I found when getting setup:

1. `build.cmd` is a-ok, but...
2. VS expects the correct version of the .NET Core SDK to be installed on your computer before it will allow solutions to be build.
3. Running tests in VS will also error because you don't have the right version of .NET Core.

> [5/03/2018 8:35:50 PM Error] Microsoft.VisualStudio.TestPlatform.ObjectModel.TestPlatformException: Testhost process exited with error: It was not possible to find any compatible framework version
> The specified framework 'Microsoft.NETCore.App', version '2.1.0-preview2-26225-03' was not found.
>   - Check application dependencies and target a framework version installed at:
>       C:\Program Files\dotnet\
>   - The .NET framework can be installed from:
>       https://aka.ms/dotnet-download-runtime
>   - The .NET framework and SDK can be installed from:
>       http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
>   - The following versions are installed:
>       1.0.5 at [C:\Program Files\dotnet\shared]
>       1.1.2 at [C:\Program Files\dotnet\shared]
>       2.0.0 at [C:\Program Files\dotnet\shared]
>       2.0.3 at [C:\Program Files\dotnet\shared]
>       2.0.5 at [C:\Program Files\dotnet\shared]
>       2.1.0-preview1-26216-03 at [C:\Program Files\dotnet\shared]
> 
>    at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.SetupChannel(IEnumerable`1 sources, CancellationToken cancellationToken)
>    at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyExecutionManager.StartTestRun(TestRunCriteria testRunCriteria, ITestRunEventsHandler eventHandler)

For developers wishing to use VS the building from source page needs to include information on finding what the used version of .NET Core is and also how to download it. The [download link in the error](https://aka.ms/dotnet-download-runtime) only has official releases. Instructions to get the installer for custom versions are needed.

**Comment by Tratcher** [comment]
Did you follow the "edit your PATH" instructions? Those should be sufficient for getting VS working (if you've run build.cmd at least once).

**Comment by JamesNK** [comment]
I had added the new path *but* I hadn't removed `c:\Program Files\dotnet`. Fixed.
