### ISSUE TITLE
React to MemoryPool<T> changes

### ISSUE THREAD

**Issue by davidfowl** [aspnet/Home#2923]
When we pull in a new CoreFX (https://github.com/dotnet/corefx/pull/27615), we need to update the SlabMemoryPool react to the following changes and fix the following bugs:

- The default reference count needs to be set to 1 when referencing counting
- We need to change our very simple Interlocked.Increment/Decrement to a loop https://github.com/dotnet/corefx/pull/27615#discussion_r171680369

/cc @pakrym

**Comment by pakrym** [comment]
Done in https://github.com/aspnet/Common/pull/326
