### ISSUE TITLE
Where is System.Web.Http?

### ISSUE THREAD

**Issue by tarekgh** [aspnet/Home#2928]
_From @shaulbehr on March 6, 2018 10:19_

Hi,
I'm trying to convert an ASP.NET project from .NET Framework 4.7.1 to .NET Core 2.1 (preview).
My methodology was to rename the folder from `MyAspProj` to `MyAspProj.Old`, then in the solution I created a new .NET Core ASP.NET project called `MyAspProj`, then copied over all the files from `MyAspProj.Old`. I added a reference to `Microsoft.AspNetCore.All`, which I hoped would bring through all the necessary types. but alas, everywhere that I have references to objects from the `System.Web.Http` namespace, my code is broken, with no obvious contenders to redirect the references.
For example, `HttpConfiguration`, which is used for Owin configuration.
And, while we're there, the Owin package itself is targeting .NET Framework. Is there a successor that targets .NET Core?

_Copied from original issue: dotnet/corefx#27764_

**Comment by tarekgh** [comment]
_From @davidfowl on March 6, 2018 10:49_

There's a doc that describes how to convert from WebAPI to ASP.NET Core https://docs.microsoft.com/en-us/aspnet/core/migration/webapi.

**Comment by tarekgh** [comment]
_From @shaulbehr on March 6, 2018 12:16_

@davidfowl Thanks for the link, that had quite a few useful tips.
Maybe you can point me further in the right direction. We are a company with a very successful product and a user base in the hundreds of thousands We're strongly considering migrating our whole codebase to .NET Core, mostly because we're really frustrated with SignalR not working as expected, and we hear that .NET Core has finally got SignalR fixed up. Plus of course all the other improvements, like way improved build times and EF being able to handle Group By queries.
BUT...
I've put a couple of days' work now into attempting to migrate our code, and I'm drowning. There are just so many things where the cheese got moved, and with such a new technology, there's almost no help on the Internet that deals with anything beyond the happy path, so every time I hit an edge case, I get frustrated.
I think our company could be an excellent test case for Microsoft to demonstrate how to migrate a real world project from .NET Framework to .NET Core. Are there any engineers on your team who could give us a few hours of time to coach us through migrating our code?
TIA,
Shaul

**Comment by tarekgh** [comment]
_From @karelz on March 6, 2018 19:1_

I think it would be best to move the discussion to ASP.NET Core repo https://github.com/aspnet as it is unrelated to CoreFX. @shaulbehr are you ok if I close it here?

**Comment by Eilon** [comment]
@shaulbehr , it's important to think of ASP.NET (System.Web) as a different framework/library than ASP.NET Core, so certainly many things have changed.

One thing I'd recommend is to start out by creating a NEW ASP.NET Core project and then start bringing in controllers, views, NuGet package references, and other logic one by one (or in chunks), as that should make migration a lot easier.

**Comment by shaulbehr** [comment]
@Eilon OK, I'll keep that in mind.
So let's say I start again with the basic infrastructure. In our current project we have a custom `Startup` class, which we declare in the `appSettings` section of `web.config` as
```
<add key="owin:AppStartup" value="FooLib.Startup, FooLib" />
```
I understand `web.config` is no longer operative, so then where do I declare this?

**Comment by davidfowl** [comment]
This is no longer configuration based. In your Startup.cs you specify the Startup class via the WebHostBuilder. If you make a new ASP.NET Core project you should see a call to UseStartup.

**Comment by shaulbehr** [comment]
@davidfowl Ouch. We're using the "[Onion Architecture](http://jeffreypalermo.com/blog/the-onion-architecture-part-1/)", which, among other things, means our dependency injection layer sits *above* the API project, so that the project logic can be data-layer agnostic. The `Startup.cs` file is in the DI project. Using the web.config we could set the startup to point at the DI library, even though the API project doesn't have a reference to it; we just rely on our build & deployment scripts to ensure that the DLL is available.
How can we do this now?

**Comment by davidfowl** [comment]
> we just rely on our build & deployment scripts to ensure that the DLL is available.

If you don't add a reference things won't work well. 

There's an overload of UseStartup that takes a string that roughly maps to what `owin:AppStartup` provided. The problem is that the way assembly loading works on .NET Core currently, you can't just copy dlls to the output folder and have them be loadable. That's mostly because the dependencies need to be calculated at restore time and put into a .deps file (it's in your output folder).

It isn't impossible though, if you do want to support loading loose dlls in the output folder then you need to load them into the current context before executing the Startup code.

**Comment by davidfowl** [comment]
Are you using .NET Core or .NET Framework?

**Comment by shaulbehr** [comment]
Right now: .NET Framework. But this is all in the context of migrating to .NET Core.

**Comment by davidfowl** [comment]
If you're running on .NET Framework then you don't really have to do anything. The assembly will Load just fine once it's in the output folder. On .NET Core you'll need to load it (and it's dependencies) into the default AssemblyLoadContext.

```
System.Runtime.Loader.AssemblyLoadContext.Default.LoadFromAssemblyPath
```

**Comment by shaulbehr** [comment]
Cool, thanks.
> There's an overload of UseStartup that takes a string that roughly maps to what owin:AppStartup provided. 
Where do we invoke this overload?

**Comment by davidfowl** [comment]
@shaulbehr have you made a new ASP.NET Core project as yet?

**Comment by shaulbehr** [comment]
Yes

**Comment by davidfowl** [comment]
You should be able to replace UseStartup<TStartup> with UseStartup("string")

**Comment by shaulbehr** [comment]
Pardon my ignorance, but where is `UseStartup` supposed to be? I searched through the new .NET Core web project and I don't see that string anywhere...

**Comment by davidfowl** [comment]
Did you create a new ASP.NET Core 2.0 project? If yes, there should be a Program.cs file that has the call to UseStartup.

![image](https://user-images.githubusercontent.com/95136/37089018-112a0b36-21b4-11e8-82d0-8643bcdeefdd.png)

I chose Web API. This is what Program.cs looks like:

![image](https://user-images.githubusercontent.com/95136/37089087-480395dc-21b4-11e8-86b7-ba48ed5140ac.png)

You can change that call to be something like:

![image](https://user-images.githubusercontent.com/95136/37089133-6e52dc70-21b4-11e8-8cfa-23bafd3a6ada.png)

**Comment by shaulbehr** [comment]
Aha. I created the project, but I deleted the classes that were generated with it, thinking they were just like `Class1.cs` sample code, then copied over the files from my .NET Framework project. That was an important piece I was missing, it seems...

**Comment by shaulbehr** [comment]
So, in your example, I presume `MyMagicAssemblyName` is the name of your referenced library. How, then, do we specify the class name? Does it have to be called "Startup"?

**Comment by shaulbehr** [comment]
Another question: in our old implementation of `OAuthAuthorizationServerProvider` we had access to `context.OwinContext.Environment`, a dictionary of values stored in the Owin context.
If I've understood correctly, I need to convert our auth provider to inherit `OpenIdConnectServerProvider`, which seems to parallel most of the functionality, but I'm not sure what is analogous to the `Environment` mentioned above?

**Comment by shaulbehr** [comment]
Ah, I think it's replaced by the `HttpContext.Items` collection. But that doesn't appear to be accessible within the `OpenIdConnectServerProvider`? How do I get to it?

**Comment by Tratcher** [comment]
You'll need to ask over at https://github.com/aspnet-contrib/ for OpenIdConnectServerProvider.

**Comment by shaulbehr** [comment]
@davidfowl - regarding your code sample:
I presume `MyMagicAssemblyName` is the name of your referenced library. How, then, do we specify the class name? Does it have to be called "Startup"?

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
