### ISSUE TITLE
ASP.NET Core 1.1 - Look for an app in the store ???

### ISSUE THREAD

**Issue by Legends** [aspnet/Home#2929]
I want to run an ASP.NET Core MVC Project, but I get the following:

![image](https://user-images.githubusercontent.com/966368/37056038-86d97370-2183-11e8-8086-5560d3743dcb.png)

**Startup.cs**
  ```
app.UseMvc(routes =>
            {
                routes.MapRoute(
                    name: "default",
                    template: "{controller=Home}/{action=Index}/{id?}");
            });
```

**Controller:**

```
 public IActionResult Testing()
        {
            return View("Testing", new DummyObject() { Age = 23, Name = "Ben" });
        }
```

**And why is it hitting the index action and not the testing action ????** 

Upgrading doesn't work too...

![image](https://user-images.githubusercontent.com/966368/37057533-fb48d440-2187-11e8-895f-8446b5e2027a.png)

**Woooow ASP.NET Core, I am impressed...**

**Task Manager is your friend .....**

**Close, reopen, Upgrade packages ---> Task Manager is my friend again....**

I wouldn't be annoyed if VS2017 would be freeware....

**Comment by Eilon** [comment]
@Legends sorry you're running into this. Can you upload your app to a GitHub repo so that we can take a look?

**Comment by blowdart** [comment]
The filter might be affecting the returned MIME type, then windows takes over and prompts for an app in which to open it.

**Comment by Legends** [comment]
I've deleted this project, sorry...  Changed to a fresh Core 2.0 project... now it's much better..
