### ISSUE TITLE
Typo in VS HTML designer intelli-sense

### ISSUE THREAD

**Issue by JamesNK** [aspnet/Home#293]
I have no idea where this bug should go so I'm putting it here and someone can move it to the correct place.

I noticed this typo for the HTML underline tag: http://i.imgur.com/3mKpE9c.png

**Comment by Eilon** [comment]
@mayurid @barrytang

**Comment by barrytang** [comment]
I opened a VS bug to track.

**Comment by danroth27** [comment]
Note that we now have a public [Tooling](https://github.com/aspnet/tooling) repo that you can open issues in.

**Comment by barrytang** [comment]
@madskristensen's comment - This is a ReSharper issue, not VSs.
