### ISSUE TITLE
Multiple file and object posting using javascript

### ISSUE THREAD

**Issue by fsfj** [aspnet/Home#2934]
How to post multiple file and an object to my action?

Here's the sample code

//ViewModel

```c#
 public class ViewModel 
{
       public IList<IFormFile> Files { get; set; }
       public OutgoingLetter OutgoingLetter { get; set; }
    
}
```

//Action

```c#
[HttpPost]
 public IActionResult Add(ViewModel vm)
{
            return Json(vm);
}
```

I have already tried posting single object(OutgoingLetter) and IFormFile.
How can i get this two in a single post using javascript, not submitting the form. I just want to post it using javascript. 

Thanks you!

**Comment by Eilon** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, to get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the `asp.net-core-mvc` tag.
