### ISSUE TITLE
Entity framework replacement messes everything up!

### ISSUE THREAD

**Issue by ppumkin** [aspnet/Home#294]
I started a vNext WebMVC project with User Authentication. That all went great, it created the database transparently suing the contexts. No problem.

I was following a tutorial on how to add my own Context, using the same connection string, since the tutorial was boasting the the latest EF now handles mulitple contexts, migrations, and all that fancy stuff.

I typed in 

**Enable-Migration**

Error: Entity Framework is NOT installed..

OK......? using Microsoft.AspNet.Identity.EntityFramework; is not Entity framework then I suppose just the Identity stuff.

I went to Nuget and isntalled the latest stable version, i started downlaoding all sorts of stuff, npm going nuts with downloads (not sure why now?)  It all installed fine I can see EF 6.1.2

My package looks like this
````
   "dependencies": {
        "EntityFramework.SqlServer": "7.0.0-beta1",
        "EntityFramework.Commands": "7.0.0-beta1",
        "Microsoft.AspNet.Mvc": "6.0.0-beta1",
        //"Microsoft.AspNet.Mvc.WebApiCompatShim": "6.0.0-beta1",
        "Microsoft.AspNet.Diagnostics": "1.0.0-beta1",
        "Microsoft.AspNet.Diagnostics.Entity": "7.0.0-beta1",
        "Microsoft.AspNet.Identity.EntityFramework": "3.0.0-beta1",
        "Microsoft.AspNet.Security.Cookies": "1.0.0-beta1",
        "Microsoft.AspNet.Server.IIS": "1.0.0-beta1",
        "Microsoft.AspNet.Server.WebListener": "1.0.0-beta1",
        "Microsoft.AspNet.StaticFiles": "1.0.0-beta1",
        "Microsoft.Framework.ConfigurationModel.Json": "1.0.0-beta1",
        "Microsoft.Framework.CodeGenerators.Mvc": "1.0.0-beta1",
        "Microsoft.Framework.Logging": "1.0.0-beta1",
        "Microsoft.Framework.Logging.Console": "1.0.0-beta1",
        "Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.0.0-beta1",
        "EntityFramework": "6.1.2.0"
    },
```

I did not add anything manually. This is all following a tutorial based on MVC4. Nuget Added the last line in and triggered the downloads.

I now have 61 Errors.

````

Show Details	Severity	Code	Description	Project	File	Line
	Error	CS0012	The type 'DbContext' is defined in an assembly that is not referenced. You must add a reference to assembly 'EntityFramework, Version=7.0.0.0, Culture=neutral, PublicKeyToken=null'.	```

Show Details	Severity	Code	Description	Project	File	Line
	Error	CS0246	The type or namespace name 'DbContext' could not be found (are you missing a using directive or an assembly reference?)	.ASP.NET 5.0	***.cs	6

Show Details	Severity	Code	Description	Project	File	Line
	Error	CS0246	The type or namespace name 'ModelBuilder' could not be found (are you missing a using directive or an assembly reference?)	.ASP.NET Core 5.0	***.cs	33

Show Details	Severity	Code	Description	Project	File	Line
	Error	CS0311	The type '***.DataContexts.IdentityDB' cannot be used as type parameter 'TContext' in the generic type or method 'IdentityEntityFrameworkServiceCollectionExtensions.AddDefaultIdentity<TContext, TUser, TRole>(IServiceCollection, IConfiguration, Action<IdentityOptions>)'. There is no implicit reference conversion from '***.DataContexts.IdentityDB' to 'Microsoft.Data.Entity.DbContext'.	Timesheep.ASP.NET Core 5.0	Startup.cs	41

Show Details	Severity	Code	Description	Project	File	Line
	Error	CS0234	The type or namespace name 'Metadata' does not exist in the namespace 'Microsoft.Data.Entity' (are you missing an assembly reference?)	.ASP.NET Core 5.0	IdentityModels.cs	5
```

Particularly in the UserDBCOntext (Which I moved into another file called IdentityDb) it has these using direcrectives. I suppose something is clashing or the the wrong version of EF was installed?

````
using System;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.Data.Entity;
//using Microsoft.Data.Entity.Metadata;
using Microsoft.Framework.OptionsModel;
using Timesheep.Models;
using System.Data.Entity;
```


:(

**Comment by ppumkin** [comment]
OK. I rolled everything back and tried to take is slowly. The first thing I noticed.

```
  public class IdentityDB : IdentityDbContext<ApplicationUser>
    {
        private static bool _created = false;

        public IdentityDB()
        {
            // Create the database and schema if it doesn't exist
            // This is a temporary workaround to create database until Entity Framework database migrations 
            // are supported in ASP.NET 5
            if (!_created)
            {
                Database.AsRelational().ApplyMigrations();
                _created = true;
            }
        }
```


The comments, until EF migrations are supported in ASP.NET5 . Is this still the case or should I be using beta2 packages instead?

**Comment by ppumkin** [comment]
I am using the wrong version. Why does nuget let me install that if its not compatible :(

**Comment by Eilon** [comment]
@divega @rowanmiller

**Comment by rowanmiller** [comment]
Hey,

Looks like there are a couple of things going on here:
* Because everything is pre-release there are a lot of breaking changes between versions and that means you have to get the right version of each package. This is just a side effect of pre-release builds and will not be an issue once we get to a stable release (since we will only break things in major versions).
* The lack of Package Manager Console integration in ASP.NET 5 projects. From the EF side we do want to allow the usual migrations commands to be used from Package Manager Console (in addition to the `k ef migration ...` experience you found. We're tracking the item as https://github.com/aspnet/EntityFramework/issues/978 - but it's also requires some general Package Manager Console integration at the ASP.NET 5 project system layer (tracked by https://github.com/aspnet/Tooling/issues/166). On other project types (WPF, WinForms, Console, etc.) the usual Package Manager Console commands work with EF7. Though we have removed the need for Enable-Migrations in EF7.

**Comment by ppumkin** [comment]
Thanks @rowanmiller that makes sense. I first thought it was some kind of bug with enable-migration, but since you said you are removing that it makes sense. I am really enjoying the whole new way of doing things. Its really great work.
Thanks and keep it up! :+1:

**Comment by rowanmiller** [comment]
Good to hear, feel free to re-open if you have further questions.
