### ISSUE TITLE
[Feature request] websocket support for proxy 

### ISSUE THREAD

**Issue by JanEggers** [aspnet/Home#2940]
https://github.com/aspnet/Proxy should support websockets

as a starter something like this:

https://github.com/aspnet/JavaScriptServices/blob/dev/src/Microsoft.AspNetCore.SpaServices.Extensions/Proxying/SpaProxy.cs

**Comment by Tratcher** [comment]
It already does...
https://github.com/aspnet/Proxy/blob/816f65429b29d98e3ca98dd6b4d5e990f5cc7c02/src/Microsoft.AspNetCore.Proxy/ProxyAdvancedExtensions.cs#L72

Also, Proxy is an abandon experiment,  we recommend you fork it if want to do any further development.

**Comment by michaelm2** [comment]
I was excited to see what proxy would turn into. Is there a recommended alternative?

**Comment by Tratcher** [comment]
Fork it? It's a useful sample at the very least.
