### ISSUE TITLE
How to get the Request Uri inside an IAuthorizationHandler?

### ISSUE THREAD

**Issue by shaulbehr** [aspnet/Home#2944]
I'm implementing claims-based security referencing [this article](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/policies). My API endpoint is of the form: `api/Things/{thingId}`, and the authorization handler must parse the request URI to get the `thingId` and verify that the current user has rights to the `Thing` in question.

I don't see any way to get the `Request` object from the `AuthorizationHandlerContext`, though. Am I missing something? Or is there some other way I can get at the request Uri?

**Comment by Tratcher** [comment]
@HaoK

**Comment by shaulbehr** [comment]
I think I found it right at the bottom of the article I referenced.
```
if (context.Resource is AuthorizationFilterContext mvcContext)
{
    // Examine MVC-specific things like routing data.
}
```
