### ISSUE TITLE
dotnet core web api exception handling - unhandled exceptions

### ISSUE THREAD

**Issue by gitfortee** [aspnet/Home#2950]
The Main method in Program.cs in my dotnet core web api project has the following code.

```
public static void Main(string[] args)
{
    var logger = LogManager.LoadConfiguration("nlog.config").GetCurrentClassLogger();
    try
    {
        BuildWebHost(args).Run();
    }
    catch (Exception ex)
    {
        //NLog: catch setup errors
        logger.Error(ex, "An exception occurred during application start.");
        throw;
    }
}  
```  
I also setup an exception handling middleware like this:

```
public void Configure(IApplicationBuilder app, IHostingEnvironment env)
{
    app.UseResponseCompression();
    app.UseMiddleware(typeof(HandleExceptionMiddleware));
    app.UseMvc();
}
```
Should i also add a `AppDomain.CurrentDomain.UnhandledException` ? to the` Main` method - since dotnet core web api is a console application?. Do I loose/gain any chances of trapping exceptions without this?

**Comment by gitfortee** [comment]
Also submitted an issue here: https://github.com/dotnet/core/issues/1338

**Comment by Tratcher** [comment]
You have request threads and the Main thread covered, but UnhandledExceptions would cover background threads.

**Comment by gitfortee** [comment]
@Tratcher could you please help me understand how does this affect an asp.net core Web Api application - i mean covering for UnhandledExceptions or not doing that - for example if I use pinvoke in my Web Api project.. Should i use `AppDomain.CurrentDomain.UnhandledException` in such cases..?

thanks!

**Comment by Tratcher** [comment]
It's not what you do, it's what thread you do it on that matters. E.g. exceptions in Startup happen on the main thread and would exit out via Program.Main. Exceptions in middleware / MVC are on the request thread and are caught by exception middleware or the server. You would have to force an operation off onto the thread pool via Task.Run or similar before you could have a problem that UnhandledException would notice.

**Comment by Eilon** [comment]
@gitfortee what exactly are you trying to achieve?

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
