### ISSUE TITLE
SlabMemoryPool page size

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/Home#2955]
_From @muratg on Tuesday, March 6, 2018 3:34:30 PM_

_From @tmds on March 6, 2018 10:0_

SlabMemoryPool is using PageSize.

```C#
private static readonly int _pageSize = Environment.SystemPageSize;
private const int _blockCount = 32;
```

Suppose page size is large, e.g. 2MB. Now our application is using 2MB buffers and a slab is 64MB.
Perhaps it is desired to still use 4KB buffers and have a slab of 2MB?

CC @davidfowl @benaadams 

_Copied from original issue: aspnet/KestrelHttpServer#2365_

_Copied from original issue: aspnet/Common#325_

**Comment by aspnet-hello** [comment]
_From @muratg on Tuesday, March 6, 2018 3:34:30 PM_

_From @davidfowl on March 6, 2018 10:29_

Yea, that change is dubious @benaadams. We might be better off going with a fixed value here.

**Comment by aspnet-hello** [comment]
_From @muratg on Tuesday, March 6, 2018 3:34:31 PM_

_From @benaadams on March 6, 2018 19:48_

https://github.com/dotnet/corefxlab/pull/2099#discussion_r167065489

**Comment by davidfowl** [comment]
Fixed
