### ISSUE TITLE
Service Scoped but need force new

### ISSUE THREAD

**Issue by FabioMorcillo** [aspnet/Home#2959]
In application .NET Core with Dependency Injection after some problems, i need service created Scoped, dispose the current injected instance object with new, how i can do it ?

**Comment by Eilon** [comment]
@FabioMorcillo can you provide a bit more info about what your requirements are and what you've tried?

**Comment by FabioMorcillo** [comment]
In Startup:

public void ConfigureServices(IServiceCollection services)
{
    .....
    // Register application services.
    services.AddScoped<IService, Service>();
}

In Application:

public void Process() 
{
    .....
    <Here i need dispose the Service registered in scope and register new instance of Service in this scope to continue execution>
    .....
}

**Comment by Eilon** [comment]
What calls the `Process` method? If the service is registered in DI it will be disposed when its scope has ended. If you dispose it yourself manually then that will cause unexpected behavior in the app, won't it?

**Comment by Antaris** [comment]
@FabioMorcillo  Additionally, I think one of the core designs around the stock DI is it doesn't support recomposition - you can't replace services on an already constructed container. Try and keep the moving parts to a minimum.

What I think would be better if you delegated the lifetime of the object around a scoped object acting as a container of sorts:

```
public interface IObjectScope<T> : IDisposable
   where T : IDisposable
{
  T Service { get; }
  
  void ReplaceService(T service);
}
```

This would allow you to manage the lifetime of an instance yourself within the scope of the container. BUT, this does come with a glaring issue- how do you construct your service instance? Unless you're going to hang on to the `IServiceProvider` and perhaps use `ActivatorUtilities` to construct the type, this is possible.

**Comment by Eilon** [comment]
Yeah it's unclear to me exactly what is being asked here, but I agree with what @Antaris is saying about managing lifetime on your own.

**Comment by FabioMorcillo** [comment]
I will do it :)

Thank you so much @Elion and @Antaris

**Comment by khellang** [comment]
If you have a scoped lifetime, there's nothing stopping you from creating a scope yourself, like

```
public class Blah
{
    public Blah(IServiceProvider provider)
    {
        Provider = provider;
    }

    private IServiceProvider Provider { get; }

    public void Process()
    {
        using (var scope = Provider.CreateScope())
        {
            var service = scope.ServiceProvider.GetService<IService>();

            // Do whatever you need with the service...
        }
    }
}
```
