### ISSUE TITLE
kvm upgrade not working in latest KoreBuild package

### ISSUE THREAD

**Issue by kevinkuszyk** [aspnet/Home#296]
I am trying to setup a [CI build](https://ci.appveyor.com/project/kevinkuszyk/r4mvc/build/1.0.14) using the `build.cmd` and `KoreBuild` pattern used in the aspnet projects.

I have `KoreBuild 0.2.1-beta4-10089` from `https://www.myget.org/F/aspnetvnext/api/v2`, and get this error when invoking `kvm upgrade`:

````
Console-Write-Error : There are no runtimes for platform 'clr', architecture 'x86' in the feed 'https://www.myget.org/F/aspnetvnext/api/v2'
At C:\Projects\R4MVC\packages\KoreBuild\build\kvm.ps1:776 char:3
````

The `build.cmd` is [here](https://github.com/T4MVC/R4MVC/blob/master/build.cmd) for reference.

Can you advise if I need to do something differently, or if it's broken at the moment?

**Comment by Praburaj** [comment]
Can you try this again. This should go away now as the `kre` packages are now available in the feed.

**Comment by kevinkuszyk** [comment]
Thanks @Praburaj, that part of the build script is working now.
