### ISSUE TITLE
ASP.Net Core Web API with Full Framework does not deploy as FDD

### ISSUE THREAD

**Issue by Vatsi** [aspnet/Home#2960]
Hi,
I recently created ASP.Net Core Web API with the full framework as I wanted to use my existing .net Framework binaries and SAML 2.0 authentication.

My project file looks like following.

`<PropertyGroup>`
`<TargetFramework>net462</TargetFramework>`
`</PropertyGroup>`

`<PropertyGroup>`
`<AssemblySearchPaths>$(AssemblySearchPaths);{GAC}</AssemblySearchPaths>`
`</PropertyGroup>`

`<ItemGroup>`
`<Compile Include="..\..\..\..\..\ProductAssemblyInfo\ProductAssemblyInfo.cs" Link="Properties\ProductAssemblyInfo.cs" />`
`</ItemGroup>`

`<ItemGroup>`
`<Content Include="obj\project.assets.json" />`
`</ItemGroup>`

`<ItemGroup>`
`<DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="2.0.0" />`
`</ItemGroup>`

`<ItemGroup Condition=" '$(TargetFramework)' == 'net462' ">`
`<Reference Include="System" />`
`<Reference Include="System.ServiceModel" />`
`<Reference Include="System.Core" />`
`<Reference Include="Microsoft.CSharp" />`
`<Reference Include="System.Data" />`
`<Reference Include="System.Web" />`
`<Reference Include="System.Xml" />`
`<Reference Include="System.Configuration" />`
`<Reference Include="System.IdentityModel" />`
`<Reference Include="Microsoft.CSharp" />`
`</ItemGroup>`

`<ItemGroup>`
`<PackageReference Include="Libuv" Version="1.10.0" />`
`<PackageReference Include="Microsoft.AspNetCore" Version="2.0.1" />`
`<PackageReference Include="Microsoft.AspNetCore.Authentication.Abstractions" Version="2.0.1" />`
`<PackageReference Include="Microsoft.AspNetCore.ApplicationInsights.HostingStartup" Version="2.0.1" />`
`<PackageReference Include="Microsoft.AspNetCore.Http" Version="2.0.1" />`
`<PackageReference Include="Microsoft.AspNetCore.Http.Extensions" Version="2.0.1" />`
`<PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.0.2" />`
`<PackageReference Include="Microsoft.AspNetCore.Mvc.Versioning" Version="2.1.0" />`
`<PackageReference Include="Microsoft.AspNetCore.Routing" Version="2.0.1" />`
`<PackageReference Include="Microsoft.AspNetCore.Server.IISIntegration" Version="2.0.1" />`
`<PackageReference Include="Microsoft.AspNetCore.Server.Kestrel" Version="2.0.1" />`
`<PackageReference Include="Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv" Version="2.0.1" />`
`<PackageReference Include="Microsoft.Extensions.Configuration.CommandLine" Version="2.0.0" />`
`<PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="2.0.0" />`
`<PackageReference Include="Microsoft.Extensions.Configuration.FileExtensions" Version="2.0.0" />`
`<PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="2.0.0" />`
`<PackageReference Include="Microsoft.Extensions.Logging" Version="2.0.0" />`
`<PackageReference Include="Microsoft.Extensions.Logging.Console" Version="2.0.0" />`
`<PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="2.0.0" />`
`<PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="2.0.0" />`
`</ItemGroup>`

This works fine but when we deploy such Web API, it requires to have all package binaries and dependencies in the bin folder instead of grabbing it from Runtime Store.

My guess is that while deploying it follows SCD deployment instead of FDD.

Can you please help me on how I can achieve it to refer package binaries and depdnecies from Runtime store instead of from bin?

I'm using ASP.Net Core 2.0.5 and .Net Framework 4.6.2.

Please let me know if you need more information on this. 

Since I wanted to use runtime store for nuget packages I opened a case with dotnet runtime project as well and have been redirected here. #16932

**Comment by Eilon** [comment]
@JunTaoLuo can correct me if I'm wrong, but the Runtime Store as well as Self-Contained Deployment apply only when running on .NET Core. When running on .NET Framework the GAC is used.
