### ISSUE TITLE
Issue in Microsoft.Net.Http.Headers 2.0.2

### ISSUE THREAD

**Issue by TonyValenti** [aspnet/Home#2962]
Hi All,
I'm not sure if this was intended or not, but it looks like the constructor signature of EntityTagHeaderValue changed.  It used to accept a string and now it accepts a StringSegment.  This is causing MissingMethodExceptions in third party libraries such as Swashbuckle and such:

System.MissingMethodException: 'Method not found: 'Void Microsoft.Net.Http.Headers.EntityTagHeaderValue..ctor(System.String)'.'

**Comment by Eilon** [comment]
@TonyValenti in what version did it previously work?

**Comment by Tratcher** [comment]
This is an intentional breaking change between 1.x and 2.x.
