### ISSUE TITLE
CommandLineApplication does not share its Out and Error writers with its list of Commands

### ISSUE THREAD

**Issue by ajaybhargavb** [aspnet/Home#2963]
Consider an application with a command,
```c#
var app = new MyCommandLineApplication()
{
  Out = CustomWriter,
  Error = CustomWriter,
};
app.Commands.Add(new MyCommand());

app.Execute("InvokeMyCommand");
```

I would expect any `Out.WriteLine()` or `Error.WriteLine()` calls within `MyCommand` to use my CustomWriter. But it uses Console.Out and Console.Error.

**Comment by mkArtakMSFT** [comment]
@ajaybhargavb, was this also fixed by the PR?

**Comment by ajaybhargavb** [comment]
@mkArtakMSFT no. My PR was in Razor and only works around the problem. This fix for this should go in Common.

**Comment by mkArtakMSFT** [comment]
I'm closing this as we've heard no community interest for this.
