### ISSUE TITLE
.net Core web application using DataProtection with redis as storage provider

### ISSUE THREAD

**Issue by jasondaicoder** [aspnet/Home#2965]
Hi guys,

I have a .net core 2.0 web api project which is deployed as AWS Lambda using data protection with redis as storage provider. I followed the article https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/configuration/overview?tabs=aspnetcore2x to set up. I also use x.509 certificate for the key encryption. However I always get the below errors during the startup.

Some code for the set up
```c#
X509Certificate2 cert = new X509Certificate2(Convert.FromBase64String(certificate), certPassword);
var redis = ConnectionMultiplexer.Connect(dpRedisConStr);
services.AddDataProtection()
             .PersistKeysToRedis(redis)
             .ProtectKeysWithCertificate(cert);
```
[Error] Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager: An exception occurred while processing the key element '<key id="a0604cb3-8f04-43f0-a9eb-a2ed5138a486" version="1" />'. 

[Warning] Microsoft.AspNetCore.DataProtection.KeyManagement.DefaultKeyResolver: Key {a0604cb3-8f04-43f0-a9eb-a2ed5138a486} is ineligible to be the default key because its CreateEncryptor method failed. 

Can anyone give some advice?

Cheers

Jason

**Comment by natemcmaster** [comment]
@jasondaicoder can you shared some code snippets? Which APIs are you using to configure redis and x.509 key encryption? This might be a duplicate of an issue I recently fixed, but can't tell for sure...

**Comment by jasondaicoder** [comment]
@natemcmaster , I have updated the original post to include some code snippets.

**Comment by natemcmaster** [comment]
I suspect you've run into this: https://github.com/aspnet/Home/issues/2321. Can you see if this workaround fixes the issue?

----
Add the X509Certificate object to the X509Store.
```c#

X509Certificate2 cert = new X509Certificate2(Convert.FromBase64String(certificate), certPassword);

var store = new X509Store(StoreName.My, StoreLocation.CurrentUser);
store.Open(OpenFlags.ReadWrite);
store.Add(cert);
store.Close();

var redis = ConnectionMultiplexer.Connect(dpRedisConStr);
services.AddDataProtection()
             .PersistKeysToRedis(redis)
             .ProtectKeysWithCertificate(cert);
```
---

If it does, then this workaround won't be necessary once 2.1.0-preview2 is out (see https://github.com/aspnet/DataProtection/pull/299 and https://github.com/aspnet/DataProtection/pull/300)

**Comment by jasondaicoder** [comment]
@natemcmaster , thanks for you solution. My service is deployed as Lambda on AWS, wonder if the My Store is still available as the host would not be windows.

**Comment by natemcmaster** [comment]
It should still work. It's how our automated tests on Linux/macOS worked around the issue. In .NET Core 2.0, the BCL team added an X509Store shim for Linux.

**Comment by jasondaicoder** [comment]
@natemcmaster , with the code you provided, I'm getting the below new exceptions

at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor)
at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
at System.Activator.CreateInstance(Type type, Boolean nonPublic)
at System.Activator.CreateInstance(Type type)
Read-only file system: IOException
at System.IO.UnixFileSystem.CreateDirectory(String fullPath)
at System.IO.Directory.CreateDirectory(String path)
at Internal.Cryptography.Pal.DirectoryBasedStoreProvider.Add(ICertificatePal certPal)
at System.Security.Cryptography.X509Certificates.X509Store.Add(X509Certificate2 certificate)

**Comment by natemcmaster** [comment]
> Read-only file system: IOException

Is your container running on a read-only filesystem?

**Comment by jasondaicoder** [comment]
> Is your container running on a read-only filesystem?

It's deployed and run on AWS Lambda as a serverless application. Not sure if it's related. Maybe Lambda doesn't allow the application to access certain directory like certificate store as the service is deployed to the shared host. I will ask AWS team to get more info.

**Comment by natemcmaster** [comment]
@bartonjs do you happen to know if there is a way to control where the X509Store puts certs on your path on Linux?

@jasondaicoder another option (if you're feeling brave) is to try a nightly build of DataProtection. You can get those from this NuGet feed: https://dotnet.myget.org/F/aspnetcore-dev/api/v3/index.json. For example, https://dotnet.myget.org/feed/aspnetcore-dev/package/nuget/Microsoft.AspNetCore.DataProtection/2.1.0-preview2-30349 has the fix for #2321

**Comment by jasondaicoder** [comment]
> @jasondaicoder another option (if you're feeling brave) is to try a nightly build of DataProtection. You can get those from this NuGet feed: https://dotnet.myget.org/F/aspnetcore-dev/api/v3/index.json. For example, https://dotnet.myget.org/feed/aspnetcore-dev/package/nuget/Microsoft.AspNetCore.DataProtection/2.1.0-preview2-30349 has the fix for #2321

@natemcmaster , sorry I can't try the nightly build at the moment. Also I don't think AWS will allow the Lambda application to access the certificate store as the Lambda applications are launched on shared host, accessing especially writing would cause security issues. Are there any other way to solve the problem?

**Comment by raban33** [comment]
@jasondaicoder - Another option is to store these certs organized in s3 so it reads on startup and stores it in Os.temp folder path. That way you wont run into issues accessing cert store. Lambda allows you to only write to temp folder.

**Comment by jasondaicoder** [comment]
> - Another option is to store these certs organized in s3 so it reads on startup and stores it in Os.temp folder path. That way you wont run into issues accessing cert store. Lambda allows you to only write to temp folder.
@raban33, I don't need to store the cert on the AWS host. I was suggested by @natemcmaster  to use the workaround which opens and tries to write the cert store. This is the issue where AWS doesn't allow the Lambda function to write the store.

**Comment by raban33** [comment]
@jasondaicoder, well looking at your code snippet, you need a cert to persistkeys to redis and when working with distribute computing, its better to store on s3 bucket and read it as its one time per lambda initialization, what stops you from accessing from s3?

**Comment by jasondaicoder** [comment]
@raban33 , we store the certificate content in application.json file. The problem is not about where we store the cert, it's the code which opens and writes the cert store on AWS Lambda host.

**Comment by raban33** [comment]
AFAIK,AWS Lambda has Write access to temp folders only. If you already have the read capability, why do we have to write to cert store? I am bit confused on what are you trying to achieve.

**Comment by bartonjs** [comment]
@natemcmaster It will be built under $HOME.  Or it'll ask the system where HOME should be (if the env variable isn't set).  Redirecting that one environment variable is the only customization allowed

**Comment by natemcmaster** [comment]
> why do we have to write to cert store? I am bit confused on what are you trying to achieve.

I was trying to suggest a workaround for #2321. In 2.0 when using `. ProtectKeysWithCertificate()`, DataProtection cannot decrypt the keys unless the certificate is in the X509Store. This will be fixed in 2.1.

Thanks @bartonjs. @jasondaicoder - if you can set $HOME to Lambda's temp dir, you might be able to make this work. 

But if that doesn't work, then I'm out of ideas on simple workarounds. You can always implement `IXmlDecryptor` yourself. See [this sample](https://github.com/aspnet/DataProtection/blob/dev/samples/CustomEncryptorSample). Also, see [our implementation](https://github.com/aspnet/DataProtection/pull/299) which added support for decrypting with an X509Cert not in the store.

**Comment by jasondaicoder** [comment]
@natemcmaster , looks like setting the HOME directory to /tmp resolved the problem. 

Thanks guys.

**Comment by jasondaicoder** [comment]
@natemcmaster , one more question with regarding to the data protection. Is it possible to use redis as key storage to share cookies between asp.net full and core applications? I followed the article at https://docs.microsoft.com/en-us/aspnet/core/security/cookie-sharing?tabs=aspnetcore2x, however it always use a directory based data protection provider. Can we use redis instead?

**Comment by natemcmaster** [comment]
@jasondaicoder yes. The docs you referenced show you how to create an `IDataProtectionProvider` using `DataProtectionProvider.Create` static method. This method is just [api sugar](https://github.com/aspnet/DataProtection/blob/2.0.2/src/Microsoft.AspNetCore.DataProtection.Extensions/DataProtectionProvider.cs#L153-L176) for creating a service colleciton. You should be able to use redis like this:
```c#
void ConfigureServices(IServiceCollection services)
{
  var redis = ConnectionMultiplexer.Connect(Configuration["RedisConnStr"]);
  var protectionProvider = CreateRedisProvider(redis);
  services.AddAuthentication(CookieAuthenticationDefaults.AuthenticationScheme)
    .AddCookie(options => {
      options.Cookie.Name = ".AspNet.SharedCookie";
      options.DataProtectionProvider = protectionProvider;
  });
}

IDataProtectionProvider CreateRedisProvider(IConnectionMultiplexer connection)
{ 
   return new ServiceCollection()
      .AddDataProtection()
      .PersistKeysToRedis(connection)
      .Services
      .BuildServiceProvider()
      .GetRequiredService<IDataProtectionProvider>();
}
```

**Comment by jasondaicoder** [comment]
@natemcmaster , would the data protection provider you manually created in CreateRedisProvider function be used by the application wide? I noticed you create a new service collection apart from the original one.

**Comment by natemcmaster** [comment]
It would be scoped to just the cookie options. If you don't set it manually, the cookie protector defaults to the application-wide protection provider.

**Comment by jasondaicoder** [comment]
> It would be scoped to just the cookie options. If you don't set it manually, the cookie protector defaults to the application-wide protection provider.

Yep, noticed. And the solution you gave actually works. Thanks.
