### ISSUE TITLE
Culture info ru-BY missed in .NET core 2.0.6 on Windows Server 2012 R2

### ISSUE THREAD

**Issue by NGancevich** [aspnet/Home#2967]
I have Localization on my asp.net core 2.0.6 and it's working on local machine. But when I publish to IIS on server 2012 r2 it's throwing an exception
Application startup exception: System.Globalization.CultureNotFoundException: Culture is not supported.
Parameter name: name
ru-by is an invalid culture identifier.
   at System.Globalization.CultureInfo.InitializeFromName(String name, Boolean useUserOverride)

According to the link https://msdn.microsoft.com/en-us/library/cc233982.aspx it's valid culture info.

Event microsoft has this localization on site https://www.microsoft.com/ru-by

**Comment by natemcmaster** [comment]
This issue was moved to dotnet/corefx#28145
