### ISSUE TITLE
Announcements repository

### ISSUE THREAD

**Issue by MattJeanes** [aspnet/Home#2968]
There's been a couple of cases the past few weeks where people have been commenting on or raising issues within the https://github.com/aspnet/Announcements repository, annoying everyone who subscribes to the issues for legitimate announcements

E.g:

* https://github.com/aspnet/Announcements/issues/297
* https://github.com/aspnet/Announcements/issues/290

Is it not possible to make issues read-only for non-members? I know that issues can be locked to collaborators but not sure about raising them entirely

**Comment by Tratcher** [comment]
No, that's a GitHub limitation.

**Comment by Eilon** [comment]
I updated the issue template at https://github.com/aspnet/Announcements/blob/master/.github/ISSUE_TEMPLATE to have a bigger warning not to post there. Aside from that, there's unfortunately not much we can do.

**Comment by MattJeanes** [comment]
Ah okay, that sucks. Might be a good idea to lock the issues to collaborators as soon as they are raised too to stop people commenting on them. Thanks though!

**Comment by Eilon** [comment]
@MattJeanes yup we already lock all issues there (though we might forget sometimes), but sometimes even a collaborator inadvertently comments on things there. If we can only remove all humans from the equation, the problem would be solved! 😄
