### ISSUE TITLE
Unable to use KVM on OSX Yosemite

### ISSUE THREAD

**Issue by imperugo** [aspnet/Home#297]
Hi, 
I'm trying to install aspnet vnext on Yosemite but it seems something is going wrong.
I tried to follows the steps explained in the README.MD but, when I write ```source kvm.sh```, I got this message

```terminal
imperugo@Imperugos-MacBook-Pro:~$ source kvm.sh
-bash: kvm.sh: No such file or directory
```

of course any KVM command doesn't work.

Any hint?

**Comment by Praburaj** [comment]
Can you check if `kvm.sh` is in `~/.k/bin/kvm.sh`?

**Comment by jpinho** [comment]
How did you installed Mono? HomeBrew, Mono Website? You must use one of this methods before using that command source kvm.sh.

João Pinho

m: +351 961 905 059
p: pinho.icodebox.net

**Comment by imperugo** [comment]
@Praburaj 
```cd ~/.k/bin/``` gets No such file or directory

@jpinho 
installed using Homebrew.
running ```mono --version```I got this message

```terminal
imperugo@Imperugos-MacBook-Pro:~$ mono --version
Mono JIT compiler version 3.12.0 ((detached/a813491 Thu Dec 11 12:24:44 EST 2014)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           normal
	SIGSEGV:       altstack
	Notification:  kqueue
	Architecture:  x86
	Disabled:      none
	Misc:          softdebug 
	LLVM:          yes(3.6.0svn-mono-(detached/5486eb2)
	GC:            sgen

```

**Comment by jpinho** [comment]
Can you follow this post? It worked for me yesterday: https://www.jeremymorgan.com/tutorials/vnext/how-to-build-c-sharp-on-mac-osx/

I think you forgot to run brew install kvm.

João Pinho

m: +351 961 905 059
p: pinho.icodebox.net

**Comment by imperugo** [comment]
@jpinho 
I run ```brew install kvm```, same for your post. Still getting kvm: command not found

**Comment by jpinho** [comment]
Can you restart your machine and confirm the command again, please?

João Pinho

m: +351 961 905 059
p: pinho.icodebox.net

**Comment by litan1106** [comment]
I followed the tutorial and got a project to run with localhost:5004.
I got "command not found" after I relaunched the terminal.
-bash: k: command not found

![k](https://cloud.githubusercontent.com/assets/1310539/6015834/8bdec772-ab2e-11e4-9879-169f9fcb0dee.png)

**Comment by Praburaj** [comment]
Can you run `source kvm.sh` again and see if `k` works? I can see this in the OS X instructions in home repo. Alternatively put this command in the bash profile? 

```
Run command source kvm.sh on your terminal if your terminal cannot understand kvm.
```

**Comment by imperugo** [comment]
@jpinho just rebooted my Mac but the problem still here.

@Praburaj ```source kvm.sh``` I get ```-bash: kvm.sh: No such file or directory ```

**Comment by suhasj** [comment]
@imperugo I presume you installed kvm using homebrew right ? Can you check the location `/usr/local/Cellar/kvm` and reply with the contents ?

**Comment by imperugo** [comment]
Finally I fix the problem running ```brew update``` and installing again kvm.

Thanks to all for the support

**Comment by jsmithnoble** [comment]
I realize this thread is more than 2 years old, but I'm having the same issue and not getting the same result.
I was able to use brew to install mono
`$ mono --version`
Produced this output
`
Mono JIT compiler version 4.6.2 (Stable 4.6.2.7/08fd525 Tue Nov 22 22:06:40 GMT 2016)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           normal
	SIGSEGV:       altstack
	Notification:  kqueue
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	LLVM:          supported, not enabled.
	GC:            sgen
`
When I run brew update I get the following error
`
touch: /usr/local/Homebrew/.git/FETCH_HEAD: Permission denied
error: cannot open .git/FETCH_HEAD: Permission denied
/usr/local/Homebrew/Library/Homebrew/cmd/update.sh: line 522: /usr/local/Homebrew/.git/UPDATE_FAILED: Permission denied
error: cannot open .git/FETCH_HEAD: Permission denied
/usr/local/Homebrew/Library/Homebrew/cmd/update.sh: line 522: /usr/local/Homebrew/.git/UPDATE_FAILED: Permission denied
fatal: Unable to create '/usr/local/Homebrew/.git/index.lock': Permission denied
error: could not lock config file .git/config: Permission denied
Already up-to-date.
`
I then ran 
`brew install kvm`
and got 
`touch: /usr/local/Homebrew/.git/FETCH_HEAD: Permission denied
fatal: Unable to create '/usr/local/Homebrew/.git/index.lock': Permission denied
error: could not lock config file .git/config: Permission denied
Error: No available formula with the name "kvm" 
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
Error: No formulae found in taps.
`
Any ideas are appreciated
