### ISSUE TITLE
Merch available?

### ISSUE THREAD

**Issue by SneezeWeeze** [aspnet/Home#2970]
Is there any .net core merch specifically for the 2.1 release? Perhaps a T-shirt?

**Comment by Eilon** [comment]
@DamianEdwards @shanselman @richlander - is there?

**Comment by SneezeWeeze** [comment]
Chiming in here because I would like seriously to buy multiple pieces. I figure the sooner this is discussed the higher the chances of it getting made if not already in progress.

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
