### ISSUE TITLE
Model is not binding with the values in WEB API GET method when data is Json

### ISSUE THREAD

**Issue by onlyanup** [aspnet/Home#2971]
I have a GET method where I'm passing a JSON object. The object is the stringified value of a List of a POCO. The Model Binder fails to bind to the object in this method. 

        [HttpGet("Test2")]
        public object Check(List<SearchModel> data)
        {
            //var d = Newtonsoft.Json.JsonConvert.DeserializeObject<List<SearchModel>>(data);
            if (data != null)
            {
                return data;
            }
            return Request.QueryString.Value;
        }

   public class SearchModel
    {
        public string Column { get; set; }
        public object Value { get; set; }
        public Matcher Matcher { get; set; }
    }

    public enum Matcher
    {
        Equals,
        Contains,
        GreaterThan,
        LessThan
    }

Here the data is not exactly null either. It's just an empty object
![image](https://user-images.githubusercontent.com/37064591/37557489-408f3ad4-2a2b-11e8-85cf-eed974e2937a.png)

I tried it with FromQuery as well. Still no luck
![image](https://user-images.githubusercontent.com/37064591/37557660-f338b82a-2a2d-11e8-8ad8-d5c087f6f402.png)

When the same method is changed as POST then the binder works perfectly and binds the data to the JSON sent in the body. So Model Binder is not broken but just not working in the case of the GET.

![image](https://user-images.githubusercontent.com/37064591/37557629-6d994568-2a2d-11e8-86b1-4fd6d362b632.png)

When I try with string type, it does come as a JSON and then the DeserializeObject method deserializes it to the required object

![image](https://user-images.githubusercontent.com/37064591/37557551-34d774ee-2a2c-11e8-8d74-86fd56d3d318.png)

**Comment by louislewis2** [comment]
@onlyanup Could you try this

[HttpGet("check2")]
public object Check([FromQuery]List<SearchModel> data)
.....

For your POST method, you have added the FromBody attribute, perhaps adding 
the FromQuery attribute would work for you on the GET method.

**Comment by onlyanup** [comment]
@louislewis2 I had tried that. Please see the 2nd Image in the report.

**Comment by Eilon** [comment]
This issue was moved to aspnet/Mvc#7500
