### ISSUE TITLE
Environment Variables Options Reloading Azure Hosted

### ISSUE THREAD

**Issue by louislewis2** [aspnet/Home#2974]
Hi,

Based on the documentation, working with reloading options when the underlying 
data source changes is really great.

However could this be implemented when we are updating settings under the Application Settings
for an App in Azure?

We use a json file, for default values and so on. When we deploy to Azure we switch to using Application Settings, which get pulled in by the call AddEnvironmentVariables();

We would like to not expect from our production environment team to have to understand, that if a change request is made for setting a, then would need to login in to Azure, navigate to the App Service Editor, make a change to that file (by someone who is not a developer), then save the changes and verify that setting was changed correctly. We prefer this file is not touched or edited at runtime.

The Application Settings in Azure, is a great way for that team to manage settings against change control requests. The issue currently is that when a change is made here, the application must be restarted so that the change can take affect. On a production system this is not ideal.

I am aware that there are many other ways to handle application settings, I did however want to make use of the Application Settings specifically within Azure, as it is a "standard" way of handling this kind of operation across different applications, different teams. Basically as long as we hosted in an Azure Application Service, we could use this single method.

**Comment by davidfowl** [comment]
Azure app service restarts the site when configuration (app settings) are changed. Are you seeing something different?

**Comment by louislewis2** [comment]
Thanks for the reply David, I honestly was not aware that saving changes, causes a restart.
Well I never heard that in those words before.

I guess, the chances of that changing is less than zero, and I will use it as it is, and make sure everyone understands that changing them will cause a restart, a bit sad but one of those things. 

Feel free to close this issue, if there is nothing you would like to add.

**Comment by Eilon** [comment]
There are some Azure support options if you wish to pursue this further on the Azure side: https://azure.microsoft.com/en-us/support/options/

Thanks,
Eilon
