### ISSUE TITLE
Move AspNetCoreBenchmarkAttribute to shared BenchmarkRunner.Sources

### ISSUE THREAD

**Issue by gfoidl** [aspnet/Home#2975]
# Background / Motivation

[BenchmarkRunner.Sources](https://github.com/aspnet/Common/tree/75b76ebb8129b2080bca88eb456675abf63ddab3/shared/Microsoft.AspNetCore.BenchmarkRunner.Sources) contains common code for easily setting up benchmarks:
 ```xml
<ItemGroup>
  <Compile Include="..\..\shared\Microsoft.AspNetCore.BenchmarkRunner.Sources\**\*.cs">
    <Link>Shared\%(FileName)%(Extension)</Link>
  </Compile>
</ItemGroup>
```
So the benchmark-project just needs to add the intrinsically benchmark-code, for instance [Microsoft.Extensions.Primitives.Performance](https://github.com/aspnet/Common/tree/75b76ebb8129b2080bca88eb456675abf63ddab3/benchmarks/Microsoft.Extensions.Primitives.Performance).

Quite easy -- one may think...
When running the benchmarks I always get trapped by `No loggers defined, you will not see any progress!`.
It's because there needs to be added the `AspNetCoreBenchmark` at assembly-level (via AssemblyInfo.cs). 

# Proposal

To make the "setup" for benchmark-projects consistent with e.g. `Program.cs` this attribute should be moved to the shared sources, so no manual adding / copying of AssemblyInfo.cs is needed.

In https://github.com/aspnet/SignalR/pull/1251#discussion_r158564943 something similar was mentioned.

# Affected projects

* [Microsoft.Extensions.Primitives.Performance](https://github.com/aspnet/Common/blob/a344c4f677f777e6788ac67a0a44f134edb991c3/benchmarks/Microsoft.Extensions.Primitives.Performance/Properties/AssemblyInfo.cs#L4)
* [Microsoft.Extensions.ObjectPool.Performance](https://github.com/aspnet/Common/blob/36b7064bbfc7954ecaf7a423ac11e699ba836c6b/benchmarks/Microsoft.Extensions.ObjectPool.Performance/Properties/AssemblyInfo.cs#L4)
* [Kestrel.Performance](https://github.com/aspnet/KestrelHttpServer/blob/e7cc0d33af55c60ca386f774ab30dfdab2305c73/benchmarks/Kestrel.Performance/AssemblyInfo.cs#L1)
* [Microsoft.AspNetCore.SignalR.Microbenchmarks](https://github.com/aspnet/SignalR/blob/f08311f33707a5528b8b35576620a9953ca1e13b/benchmarks/Microsoft.AspNetCore.SignalR.Microbenchmarks/AssemblyInfo.cs#L1)
* [Microsoft.AspNetCore.Razor.Performance](https://github.com/aspnet/Razor/blob/98e74b9a69b7b277fc9a78c068de967185104d69/benchmarks/Microsoft.AspNetCore.Razor.Performance/AssemblyInfo.cs#L1)
* [DI.Performance](https://github.com/aspnet/DependencyInjection/blob/8e1f92f95c885a4b046f50f085d47c539e6f6792/benchmarks/DI.Performance/AssemblyInfo.cs#L1)
* [Microsoft.AspNetCore.Mvc.Performance](https://github.com/aspnet/Mvc/blob/997544077a0ed6535c2eac9f0590f8d7afe0677d/benchmarks/Microsoft.AspNetCore.Mvc.Performance/AssemblyInfo.cs#L1)

**Comment by Eilon** [comment]
@sebastienros / @mikeharder / @davidfowl - thoughts on this? Worth the effort?

**Comment by gfoidl** [comment]
I can submit a PR when this proposal is accepted

**Comment by pakrym** [comment]
@Eilon this one is about microbenchmarks.

The reason we don't bring assembly attribute by default is that it would be impossible to override it globally with different configuration type.
I don't think adding an attribute when creating a project is too much of a hassle especially considering this package is not intended to be used outside ASP.NET Core repositories.

**Comment by gfoidl** [comment]
> to override it globally with different configuration type.

This makes sense. But so far there is the same setup in all benchmark repos within ASP.NET Core.
That's why I would add the attribute to the "default-setup".
In case of a different configuration one can "opt-out" (i.e. don't include the linked file).

> is too much of a hassle

Of course not, but it's very easy to forget (because all other stuff for running benchmarks is included by default) and seems strange that this attribute is missing.

**Comment by pakrym** [comment]
> In case of a different configuration one can "opt-out" (i.e. don't include the linked file).

How do you opt-out of a single file out of multiple brought by a nuget package?

**Comment by gfoidl** [comment]
Ups, I didn't realize that this is shipped by nuget to the other repos. So the opt-out is bullshit.

So your point 
> to override it globally with different configuration type.

is a strong argument for not changing this behavior. I'm closing this issue. Thanks for clarification!
