### ISSUE TITLE
Bind event on injected object (PropertyChanged is always null)

### ISSUE THREAD

**Issue by Eilon** [aspnet/Home#2976]
_From @LeonidasFettikus on March 1, 2018 8:55_

In an .Net Core WebAPI, I am injecting an custom `IWritableOptions `object (derived from `IOptionsSnapshot`) through the constructor of a service that I configured via the `ConfigureServices `method. This object has an even receiver that fires every time a property is changed on that object. Inside my service, I subscribe to the event of the object passed through the constructor. 

Then, I have a controller that also gets an `IWritableOptions `object passed through the constructor via DI. I use this controller to change the value of the property for which I configured an event receiver. 

So far so good. When I use the controller to change the values of my object, however, the event isn't triggered. I suspect that the runtime is instantiating multiple instances of my `IWritableOptions ` class and that the event isn't triggered because of that.

Can anybody clarify if this is possible?

Links:

Repository that demonstrates what I am trying to do: [Link](https://github.com/LeonidasFettikus/EventDI)
Implementation of my service class: [Link](https://www.stevejgordon.co.uk/asp-net-core-2-ihostedservice)
Implementation of my `IWritableOptions` class: [Link](https://stackoverflow.com/questions/40970944/how-to-update-values-into-appsetting-json)

In the repository, the relevant code is in ClientService.cs. `PropertyChanged `is never triggered here.

_Copied from original issue: dotnet/core#1317_

**Comment by Eilon** [comment]
_From @Petermarcu on March 17, 2018 17:36_

@Eilon

**Comment by pakrym** [comment]
>. I suspect that the runtime is instantiating multiple instances of my IWritableOptions class and that the event isn't triggered because of that.

Yes, because it is registered as Transient, if you want a single instance register it is as a singleton.

https://github.com/LeonidasFettikus/EventDI/blob/55b776bc7b7f61e0b15d702fbbee1515ced1e2a5/Extensions.cs#L21

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
