### ISSUE TITLE
Should the default StatusCodePageOptions body result be cached?

### ISSUE THREAD

**Issue by PureKrome** [aspnet/Home#2977]
👋 G'Day!

I noticed that the [StatusCodePageOptions ](https://github.com/aspnet/Diagnostics/blob/4e044a1e30454b87edbc316f40ba608d1160cb28/src/Microsoft.AspNetCore.Diagnostics/StatusCodePage/StatusCodePagesOptions.cs) class has a default way of generating the the appropriate statuscode response to the client. Right now, it's just some standard text (and no, this issue is not about the CONTENT of the StatusCodePageOptions response). Great!

[So right now, it basically does this](https://github.com/aspnet/Diagnostics/blob/4e044a1e30454b87edbc316f40ba608d1160cb28/src/Microsoft.AspNetCore.Diagnostics/StatusCodePage/StatusCodePagesOptions.cs#L25):

```
 var body = BuildResponseBody(statusCode);
...
return context.HttpContext.Response.WriteAsync(body);
```

- Generate body (based on status code).
- Write to response.

The body is always the same per StatusCode, right? If so, why not just cache this in say a `ConcurrentDictionary` ? Am I missing something?

**Comment by Tratcher** [comment]
Yes, that would be possible for the default content. It's a trade off. E.g how often are you sending blank status codes? Would there be dictionary contention. Would you be holding onto unneeded memory? In a normal mvc app I don't expect the default implementation to be invoked often, it's there more as a diagnostic fallback.

**Comment by PureKrome** [comment]
> how often are you sending blank status codes?

?? Blank status codes? I thought every response *has* to have an HttpStatusCode?

>Would there be dictionary contention.

This is the biggest worry out of all of this. I was thinking of a `ConcurrentDictionary` only because I was hoping to 'generate' the response once (think -> 2+ requests that arrive at the same time / racing each other). I'm not an expert in concurrency and high-throughput code, so this was my naive thoughts on this.

> Would you be holding onto unneeded memory?

We talking about a small number of status codes here, though, right?
The other issue here is also copying the string output from the Dictionary to the Response. Again, I'm crap with all of this low level memory stuff, but I'm under the impression that if a string-response is cached in a Dictionary/Hashset, etc it will be _copied_ to the response ... and needs to be GC'd so if a website is slammed with 404 routes, this will slowly grow memory. Right now, I think this is still the case with the current code => generate output, send to response, wait for GC to clean up later.

For me, this is mainly about people creating static but rich response pages (think, nice html pages or for me, json results conforming to a standard api error schema/model).

>  In a normal mvc app I don't expect the default implementation to be invoked often, it's there more as a diagnostic fallback.

Sorry @Tratcher I don't understand what you mean there 😊  Are you saying "under a normal MVC app with just a standard `.UseStatusCodes()` middleware, routes that end with a 404 or 400 or some common status code that's not 500 and not 200, don't really get hit, much?

**Comment by Tratcher** [comment]
By blank status code I meant a response with no body.

> We talking about a small number of status codes here, though, right?

In theory it could be all the status codes between between 200 and 999, but in practice it would only be about 20.

> routes that end with a 404 or 400 or some common status code that's not 500 and not 200, don't really get hit, much?

404 and 400 are error cases that the user shouldn't see in the average browsing session. In my subjective experience as a client I hit 404s maybe once per day. Your app logs would give you a better frequency analysis.

As for caching custom content, no way, the content generator should take care of that or utilize the response caching middleware. The caching of content on the server has a lot of hazards and rules around cross user contamination.

**Comment by Eilon** [comment]
If the concern here is performance, we would need to see data that demonstrates that it's a problem. In the several years that we've had this logic, it's never come up as a concern from anyone. As @Tratcher said, these just aren't very common, so optimizing their performance isn't a big need. And, there's risk of breaking things when caching is introduced. I think in this risk vs. reward equation, it doesn't add up.

**Comment by PureKrome** [comment]
Totally no probs at all. Thanks for your input folks :)
