### ISSUE TITLE
Visual Studio tooling for windows authentication

### ISSUE THREAD

**Issue by zivkan** [aspnet/Home#298]
Using the "old" ASP.NET web applications, the project properties has options to enable windows authentication, and if using OWIN self hosting, you can get the HttpListener and configure the authentication programatically.

My understanding is that I can pack and deploy a ASP.NET 5 app to IIS, and configure IIS for Windows Authentication. However, I don't know how to debug (or if it's possible to debug). Therefore, it's much harder to develop the application in the first place.

When I create a ASP.NET 5 starter web project, I see that when it runs, it runs in IIS Express. Therefore, it would be great if there was a way to configure the project so that IIS Express disables anonymous authentication, and enables Windows authentication.

**Comment by davidfowl** [comment]
You should be able to use web.config like you have in the past.

**Comment by zivkan** [comment]
I tried creating a Web.config file in the wwwroot folder like this: 

```xml
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
  <system.web>
    <authentication mode="Windows"/>
    <authorization>
      <deny users="?"/>
      <allow users="*"/>
    </authorization>
  </system.web>
</configuration>
```
But using `@User.Identity.IsAuthenticated` in a razor view just shows false. I tried adding this:
```xml
  <system.webServer>
    <security>
      <authentication>
        <anonymousAuthentication enabled="false"/>
      </authentication>
    </security>
  </system.webServer>
```
But IIS Express would serve up an error page saying:
> This configuration section cannot be used at this path. This happens when the section is locked at a parent level. Locking is either by default (overrideModeDefault="Deny"), or set explicitly by a location tag with overrideMode="Deny" or the legacy allowOverride="false".

Before today, my only experience with disabling anonymous authentication and enabling Windows authentication is using the IIS Manager GUI, or setting the project properties in Visual Studio. I've never done it in web.config before, but from my searching, I can't find out how to do it, other than what I tried above.

**Comment by Praburaj** [comment]
Setting up windows auth on weblistener is similar to that of owinhost. Here is an example: 
https://github.com/aspnet/MusicStore/blob/master/src/MusicStore/StartupNtlmAuthentication.cs#L47

Can you try setting the location like in here - I think tooling does some of these for you. I can also see this work item which is not directly related to this but makes me feel tooling does some of these for you : https://github.com/aspnet/Helios/issues/78

https://github.com/aspnet/MusicStore/blob/dev/test/E2ETests/NtlmAuthentation.config#L1028

```
<location path="MusicStoreNtlmAuthentication">
    <system.webServer>
      <security>
        <authentication>
          <anonymousAuthentication enabled="false" />
          <windowsAuthentication enabled="true" />
        </authentication>
      </security>
    </system.webServer>
  </location>
```

**Comment by zivkan** [comment]
I cloned the MusicStore repo, but nuget package restore fails for me, so I can't test that solution myself. The first error it reports is "Unable to locate Kestrel >= 1.0.0", which I also can't find in a working solution. There's many other packages it was unable to locate as well.

However, setting ServerInforation's Listener.AuthenticationManager.AuthenticationTypes works when I run using WebListener.  IIS Express still fails, even if I put anonymousAuthentication in a location element, as you suggested. But, WebListener is enough to get me started learning ASP.NET 5. 

By the way, I don't have access to the Helios repo, so I can't check the issue you linked. But since I have a way to progress, it's not an issue.

I don't know if you want to close this issue, or keep it open, as I still think tooling could be improved. After hours of googling with bing on the weekend, I didn't find this solution of "app.Server as ServerInformation". But I guess the doco on asp.net will improve as ASP.NET 5 gets closer to release. Plus, it doesn't appear possible to disable anonymous authentication for IIS Express for ASP.NET 5 projects on VS CTP5. Sorry if I sound too negative. I think it's an awesome improvement, and I really like how wwwroot is split out. I think it makes the projects a lot cleaner. Thanks for all your work!

**Comment by GrabYourPitchforks** [comment]
This is a tooling issue.  The VS IDE needs to create the appropriate &lt;authentication&gt; entries in the file (MY_DOCUMENTS)\IISExpress\config\applicationhost.config.  This cannot be done in local Web.config due to the locking mechanisms used.  Basically, tooling needs to do for ASP.NET 5 what it already does for ASP.NET 4.x.

**Comment by davidfowl** [comment]
Ah hah! Good to know.

**Comment by sayedihashimi** [comment]
Thanks for the feedback. On the VS side we have this on our backlog as two items that we are tracking. The features we will be working on that impact this are listed below.

 - Support IIS Express settings and apply them to applicationHost.config
 - Store the applicationHost.config file with the solution or project (_most likely we will store it at the solution level in the ```.vs``` folder_)

We are going to work hard to get these features in for the next release but we have not yet fully committed to that, but it's likely to happen.

**Comment by sayedihashimi** [comment]
In VS2015 CTP6 we shipped the feature where we store the ```applicationHost.config``` file as a part of the solution. The file is stored in the .vs folder and is not designed to be shared with others (_we may enable that in a future release_).

In the *next release* we should have the ability to enable ssl/auth options from the properties grid.

I think we can close this item now.

**Comment by zivkan** [comment]
Thanks Sayed.  Is there a sample, or some documentation on how to use the applicationHost.config file, from the .vs folder? Presumably the applicationHost.config file needs to specify the folder path, since the solution could contain more than 1 project, and each could have different settings.

With a ASP.NET 4 project, I can click the project, and in the Properties panel change the Windows authentication and Anonymous authentication options. So, I hope it gets a bit easier to use before RTM, but if I can learn how to write the config file myself, that would be great.

**Comment by sayedihashimi** [comment]
>Thanks Sayed. Is there a sample, or some documentation on how to use the applicationHost.config file, from the .vs folder? Presumably the applicationHost.config file needs to specify the folder path, since the solution could contain more than 1 project, and each could have different settings.

@zivkan when you create an ASP.NET 5 web project in VS2015 CTP6 you should find the applicationHost.config file in the .vs folder after you run the project once. If you have multiple web projects in that solution then they will be included in the applicationHost.config as well.
When running from Visual Studio you don't need to interact with that file directly. Visual Studio will take care of it.

>With a ASP.NET 4 project, I can click the project, and in the Properties panel change the Windows authentication and Anonymous authentication options. So, I hope it gets a bit easier to use before RTM, but if I can learn how to write the config file myself, that would be great.

This is the feature I mentioned would be coming in a future release of Visual Studio 2015. We recently checked it in.

**Comment by zivkan** [comment]
I tried creating new ASP.NET5 projects and clicking the debug in IIS express button on a machine with VS2015 that I upgraded to CTP6, and also a new VM where I installed CTP6 from MSDN downloads. In both cases, I get a .vs folder, but it doesn't contain an applicationHost.config file anywhere. When I check the IIS Express icon in the systray, it tells the the config is c:\users\accountname\Documents\IISExpress\config\applicationhost.config.  Maybe that change didn't make CTP6?  In any case, it will be great once done. I'm fine with this issue being closed, since it sounds like it should be a Visual Studio issue, not an ASP.NET issue.  thanks.

**Comment by davidfowl** [comment]
This is coming.

**Comment by zivkan** [comment]
Thanks David. I've been busy with other things, so I haven't tried, but I think with everyone's help I know how to edit my (MY_DOCUMENTS)\IISExpress\config\applicationhost.config manually for now. Still looking forward to the next VS2015 update and build conference

**Comment by zivkan** [comment]
VS2015 RC now allows this setting to be changed in the IDE. Thank you to everyone involved.
