### ISSUE TITLE
IE浏览器无法保存身份验证信息

### ISSUE THREAD

**Issue by Hsinky** [aspnet/Home#2985]
asp.net core 2.0.6存储身份验证信息时无效，但是谷歌或火狐是正常的，如下是我的代码
IN IE，“HttpContext.SignInAsync” can't save cookie,bug,chrome or firefox is normal,please me,thanks，code:
![image](https://user-images.githubusercontent.com/10111222/37713246-3d2abd5e-2d51-11e8-864d-4f746427ac96.png)

**Comment by Tratcher** [comment]
Translation: Browser failed to save authentication information

Can you provide a trace using a tool like Fiddler?

**Comment by Hsinky** [comment]
hi，thanks for your help,the red line is my cookie, but , Browser IE haven't got the cookie
![image](https://user-images.githubusercontent.com/10111222/37718421-994ee4aa-2d5d-11e8-88bc-ce20ce25d759.png)

**Comment by Hsinky** [comment]
@Tratcher browser ie no cookie
![image](https://user-images.githubusercontent.com/10111222/37719155-53f771b8-2d5f-11e8-91b1-f3444d4ebbd8.png)

**Comment by Tratcher** [comment]
If only IE is failing to save the cookie then it's unlikely an issue with ASP.NET. I suggest asking this question on https://stackoverflow.com/.

**Comment by John0King** [comment]
你的代码里面有个 bug,   
~await~ `HttpContext.SignInAsync(...);`

没有 await ,  能不能在请求完成之前写入 cookie 是无法确定的， 你的请求可能提前结束

**Comment by Eilon** [comment]
Translation:

> There's a bug in your code,
>
> Await Httpcontext.signinasync (...);
>
> Without await, it is not possible to write cookies before the request is complete, and your request may end prematurely
