### ISSUE TITLE
Using IDataProtector to decrypt jwt/bearer tokens

### ISSUE THREAD

**Issue by qfcolin** [aspnet/Home#2987]
Hi,
I have a question relating to aspnet core 2.1.
I use the same key to encrypt the data between services  as I do to encrypt my auth bearer tokens. I'm hoping to wire up jwt authentication to use dataprotector to decrypt the tokens automatically so I can access the claims and User.Identity. Something like the code sample below :

```c#
services.AddDataProtection()
                    .SetApplicationName("MyProtector")
                    .PersistKeysToAzureBlobStorage(new Uri(blobStorageUrl));

var **protector** = provider.CreateProtector("MyProtector");
services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
        .AddJwtBearer(options =>
        {
          options.TokenValidationParameters = new TokenValidationParameters
          {
            ValidateIssuer = true,
            ValidateAudience = true,
            ValidateLifetime = true,
            ValidateIssuerSigningKey = true,
            ValidIssuer = Configuration["Jwt:Issuer"],
            ValidAudience = Configuration["Jwt:Issuer"],
            IssuerSigningKey = **protector**
          };
        });
```

Is there any way to do this? If not what would be the alternative recommendation? Create a middleware and decrypt the tokens manually?
Any advice appreciated,
Thanks,
Colin

**Comment by Eilon** [comment]
@blowdart / @Tratcher - thoughts on this?

**Comment by blowdart** [comment]
No there's no way, this isn't what data protection is meant for. The design for data protection involves never exposing the key material, and to always encrypt and sign, rather than just sign like JWT usually needs.

**Comment by Tratcher** [comment]
You'd probobly have to implement a ISecurityTokenValidator that wrapped JwtSecurityTokenHandler:
https://github.com/aspnet/Security/blob/3fae140900fa837094c052b15a132816e0caa477/src/Microsoft.AspNetCore.Authentication.JwtBearer/JwtBearerOptions.cs#L92

**Comment by dazinator** [comment]
Where I found `DataProtection` fits well into the equation, is when you need to persist a generated signing key. You can use IDataProtector to protect the key itself, when you write it to disk, and unprotect the key when you load it from disk. It's still a seperate key that you have to generate for the purposes of signing JWT's, but atleast that key is protected by DataProtection at rest.
