### ISSUE TITLE
Why is explicit registering of IHttpContextAccessor not required when running in VisualStudio ?

### ISSUE THREAD

**Issue by prmces** [aspnet/Home#2989]
Hello All!!

I am running an application in .net core 2 and the application runs well when running from Visual Studio.

I can choose IISExpress or My Project to run and works without any issue.

![image](https://user-images.githubusercontent.com/20740261/37775179-03451ee8-2dc1-11e8-8023-a61fe8c7f4a0.png)

When I try to Run with dotnet -run (outside VS) or directly in IIS (not the express one), the controllers calls fails with a 500 error message.

`InvalidOperationException: No service for type 'Microsoft.AspNetCore.Http.IHttpContextAccessor' has been registered.`

Adding the code below inside the startup class made my application works.

`services.AddSingleton<IHttpContextAccessor, HttpContextAccessor>();`

So my question is: Why is explicit registering of IHttpContextAccessor not required when running in Visual Studio??

Thanks in Advance

**Comment by Tratcher** [comment]
Application Insights will register it for you, and this is enabled by default in VS. In more recent versions of VS you can opt out of AI.

**Comment by prmces** [comment]
Thank you some much @Tratcher !!

**Comment by davidfowl** [comment]
It’s fixed in 2.1 and the latest VS.

**Comment by freerider7777** [comment]
How is it fixed? I see the same behavior now with .Net Core 2.1

**Comment by Eilon** [comment]
@freerider7777 can you log a new issue with details on exactly how to reproduce the issue you're seeing?
