### ISSUE TITLE
Add support for blocking WebSocket requests from particular origins

### ISSUE THREAD

**Issue by anurse** [aspnet/Home#2992]
This can be done with extra middleware, but it would be nice if the WebSocket middleware had this ability.

**Comment by Tratcher** [comment]
What would this look like?

**Comment by anurse** [comment]
@davidfowl claims there's something like this in System.Web.

**Comment by davidfowl** [comment]
https://msdn.microsoft.com/en-us/library/system.web.websockets.aspnetwebsocketoptions.requiresameorigin(v=vs.110).aspx

**Comment by Tratcher** [comment]
I can understand why they did it that way back in the monolith, but in core we've always tried to separate policy from function. E.g. AuthN vs AuthZ.   The WS middleware provides the functionality, but the policy would be applied at the call site like with a CORS attribute on your hub. That's the same place you'd specify your AuthZ, correct? The websocket middleware doesn't have it's own  AuthZ policy.

**Comment by anurse** [comment]
I can see the case for why we might require the caller of `AcceptWebSocketAsync` to have done the work here.

**Comment by davidfowl** [comment]
We basically have to decide if this is something that people using websockets want to do. If the answer is yes then we should add it here. I don't really see a line where SignalR should add this and websockets doesn't have it.

**Comment by davidfowl** [comment]
See also https://www.tpeczek.com/2017/07/preventing-cross-site-websocket.html

**Comment by davidfowl** [comment]
This is relevant as well https://tools.ietf.org/html/rfc6455#section-10

**Comment by anurse** [comment]
I still kinda think that it's up to the caller of `AcceptWebSocketAsync` to handle this. The WebSocket middleware isn't a standard middleware, it doesn't handle any request, it just provides a feature for other middleware to handle the request as a WebSocket.

**Comment by Tratcher** [comment]
How well does this play with our existing CORS middleware? Do we have a sample of how to combine them?

**Comment by davidfowl** [comment]
It’s really up to @blowdart to decide if we need this feature as part of the websocket middleware or not. We haven’t had it for 3 versions.

**Comment by brockallen** [comment]
Why is Origin the thing you want t block on? Outside of the browser that can be spoofed. So why not rely upon normal authN/authZ techniques, as that's how you really know if the caller is legit.

**Comment by davidfowl** [comment]
> Why is Origin the thing you want to block on? Outside of the browser that can be spoofed. So why not rely upon normal authN/authZ techniques, as that's how you really know if the caller is legit.

I posted like 2 links describing the "security considerations" when using websockets. If we don't care to do anything then it's fine but that's @blowdart's choice.

**Comment by blowdart** [comment]
Well if it's in the spec we might as well do it, but yea, adding auth is a better approach.

**Comment by brockallen** [comment]
Relying on same-origin policy for ajax calls is also not a substitute for authentication. And the link you provided says that Origin is not really a guarantee. But I do admit that blocking on non-allowed Origins won't really hurt things. 

Sounds like an authorization policy is is in order.

**Comment by anurse** [comment]
And auth is already fully supported. This is a defense-in-depth thing based on spec guidance

**Comment by BrennanConroy** [comment]
The current plan is to add a CORS reference to WebSockets and have a cors options delegate in UseWebSockets, then apply CORS in Invoke after verifying that the connection is a websockets request.

**Comment by BrennanConroy** [comment]
There are two API possibilities I'm considering.
The first one adds `AddWebSockets` that will allow you to configure which CORS policy to use for WebSockets requests.

The second one adds 2 properties to `WebSocketOptions` on `UseWebSockets` to configure CORS.

```c#
public void ConfigureServices(IServiceCollection services)
{
    services.AddCors(o =>
    {
        o.AddPolicy("something", p =>
        {
            p.WithOrigins("example.com");
        });
    });

    // New API
    services.AddWebSockets(o =>
    {
        o.EnforceCors = true;
        o.CorsPolicyName = "something";
    });
}

public void Configure(IApplicationBuilder app, IHostingEnvironment env)
{
    app.UseWebSockets();
}
```

```c#
public void ConfigureServices(IServiceCollection services)
{
    services.AddCors(o =>
    {
        o.AddPolicy("something", p =>
        {
            p.WithOrigins("example.com");
        });
    });
}

public void Configure(IApplicationBuilder app, IHostingEnvironment env)
{
    app.UseWebSockets(new WebSocketOptions()
    {
        // New options
        EnforceCors = true,
        CorsPolicyName = "something"
    });
}
```

**Comment by anurse** [comment]
If `EnforceCors` == `true` and `CorsPolicyName` == `null` what happens? Apply the default CORS policy?

In general it sounds good, as long as we're OK with the dependency from WebSockets to CORS.

**Comment by BrennanConroy** [comment]
Done https://github.com/aspnet/WebSockets/commit/768d2a023e32c8530a4cda6a5a3c41fc5136b9a4
