### ISSUE TITLE
Porting AppDomain to AssemblyLoadContext issue with ApplicationBase and PrivateBinPath

### ISSUE THREAD

**Issue by DomZZ** [aspnet/Home#2996]
I'm aware that AppDomain is deprecated and replaced partially by AssemblyLoadContext.
But I'm facing to a new problem that I'm not able to resolve  :

I have this code in .Net Framework 4.6.2 :
```
            var childDomain = AppDomain.CreateDomain("app", null, new AppDomainSetup() { ApplicationBase = Path.Combine(adminPath, "bin"), PrivateBinPath = Path.Combine(adminPath, "bin"), LoaderOptimization = LoaderOptimization.SingleDomain });
            AppDomainHelper.RunInAppDomain(childDomain, "Alcuin.Admin.Configuration.Services", "Alcuin.Admin.Configuration.Services.Application.HttpHandlerService", "CreateOrUpdateAppConfig", new object[] { tenantName, publicDbConnectionString, adminDbConnectionString, provider, dialect, driver, true });
```

I've replaced this by that :
```
            var assemblyFile = Path.Combine(versionDir, "admin", "bin", "Alcuin.Admin.Configuration.Services.dll");
            (string status, string log) = _runner.RunInThread<Tuple<string, string>>(assemblyFile, "Alcuin.Admin.Configuration.Services", "Alcuin.Admin.Configuration.Services.Application.HttpHandlerService", "CreateOrUpdateAppConfig", data);
```

RunInThread method call an override of AssemblyLoadContext and proper instanciate method and load dependencies, this is working well.

But the invoked code use AppDomain.CurrentDomain.BaseDirectory internally to load some files (related to the assembly we load), this is why we used :
```
new AppDomainSetup() 
{ 
ApplicationBase = Path.Combine(adminPath, "bin"), 
PrivateBinPath = Path.Combine(adminPath, "bin"), 
LoaderOptimization = LoaderOptimization.SingleDomain
}
```

to make sure invoked code can work without any change.

Do you know how can I port that into .NET Core with AssemblyLoadContext ?

Thanks

**Comment by natemcmaster** [comment]
Hey @DomZZ, it looks like this issue belongs on https://github.com/dotnet/corefx. I don't see anything specific in this about ASP.NET Core. We can move the issue for you, or you can re-open it yourself it you'd like.

**Comment by Eilon** [comment]
This issue was moved to dotnet/corefx#28419
