### ISSUE TITLE
Use the up-for-grabs label

### ISSUE THREAD

**Issue by jbrinkman** [aspnet/Home#300]
It would be good to see the ASPNET team adopt the use of the up-for-grabs label.  It would make it easier to help the community get involved and knock off some low hanging fruit so ASPNET team could focus on the more difficult issues.

**Comment by Eilon** [comment]
I'm in favor of it - I'm asking a few others to get an idea on where people stand.

**Comment by tugberkugurlu** [comment]
:+1:

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
