### ISSUE TITLE
Bug in Razor Page Modal

### ISSUE THREAD

**Issue by rishabhack** [aspnet/Home#3003]
```C#
public  JsonResult GetResult(){
    return Json();
}
```

Will  give error the name 'Json' does not exist in current context in razor page modal while working fine when page is drives from controller
I can't use razor page model due to this serious issue and need to move to MVC approach instead of page modal. Please Resolve this Bug.

**Comment by Eilon** [comment]
This issue was moved to aspnet/Mvc#7554
