### ISSUE TITLE
embedded power bi results in microsoft login box

### ISSUE THREAD

**Issue by Eilon** [aspnet/Home#3004]
_From @toy-opensource on March 27, 2018 0:19_

there is an excellent example for how to embed powerbi **App Owns Data** here:
https://powerbi.microsoft.com/en-us/documentation/powerbi-developer-embed-sample-app-owns-data/

however this example is for running on the .net platform
and some of the routines used in the example dont exist for aspnetcore

there is another excellent post about someone attempting to do the same thing:
https://community.powerbi.com/t5/Developer/Embed-Power-BI-dashboard-in-ASP-Net-core/td-p/273279

so first i built the standard .net version according to the first example
and then i tried to migrate to aspnetcore incorporating fixes from the second link

here are the urls im using:
    private static readonly string AuthorityUrl = "https://login.windows.net/common/oauth2/authorize/";
    private static readonly string ResourceUrl = "https://analysis.windows.net/powerbi/api";
    private static readonly string ApiUrl = "https://api.powerbi.com/";
    private static readonly string EmbedUrl = "https://app.powerbi.com/";

and the result is - 
the microsoft login box - not cool
can anyone tell me if they have actually embedded powerbi into aspnetcore?
if you have - can you give me a coupla hints on how to get real data back?

_Copied from original issue: aspnet/Mvc#7555_

**Comment by Eilon** [comment]
Hi @toy-opensource 
It looks like this is a question about how to use ASP.NET Core with Power BI. While we do our best to look through all the issues filed here, to get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the `asp.net-core` tag and the `powerbi` tag.

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
