### ISSUE TITLE
Will Kestrel  cancel the request immediately

### ISSUE THREAD

**Issue by John0King** [aspnet/Home#3007]
when there are many requrest in the queue, and some user may refresh or stop in the browse when website is slow, if kestrel not cancel the request immediately, that will make site much slower,
I know there is `CancelationToken` I can use to cancel the action immediately ,  but I may not use `CancelationToken` everywhere,  I know `Thread` can `Abort()` , but in asp.net core  seems there are `Task`s , and I don't know how to cancel a `Task`  immediately.

so my question is will "kestrel" or "asp.net core's HttpContext"  abort the request immediately  when connection reset

**Comment by Tratcher** [comment]
No, Kestrel has no way to abort user code. Cancellation is cooperative. If you have long, expensive operations then they should listen to the HttpContext.RequestAborted CancelationToken and terminate themselves.

**Comment by Eilon** [comment]
Yes the system is fundamentally cooperative. Aborting a thread is an extremely dangerous operation and can leave an app unstable. You can safely kill an entire process, but that of course has its own issues.

**Comment by John0King** [comment]
May I ask , How Node or PHP or  Classic ASP , WebForm handel connection reset ?
> Aborting a thread is an extremely dangerous operation and can leave an app unstable

 dangerous only when you are sending data to database or complex business logic. and if the page only contains query data and send html data, it's safe to abort immediately.

so here's what I'm thinking:
```C#
// default is false
HttpContext.IgnoreUserAbort = true; // force the thread running even when browse abort.
```

**Comment by Eilon** [comment]
How other systems handle connection resets is not particularly relevant because ASP.NET Core is not any of those systems (and shares almost nothing with any of them).

The idea is that if you already know your code is "safe" for Thread.Abort, you might as well write your code cooperatively anyway (such as by using cancellation tokens).

I found a few links discussing Thread.Abort and how to safely stop code from running:
* https://blogs.msmvps.com/senthil/2008/12/17/the-dangers-of-thread-abort/
* https://stackoverflow.com/questions/1559255/whats-wrong-with-using-thread-abort
* https://haacked.com/archive/2004/11/12/how-to-stop-a-thread.aspx/
* http://www.windowsdevcenter.com/pub/a/dotnet/2003/02/18/threadabort.html

**Comment by John0King** [comment]
@Eilon I see your point from this blog https://blogs.msmvps.com/senthil/2008/12/17/the-dangers-of-thread-abort/  
and May I ask , Should/Will MVC or RazorView RazorPage those frameworks  check `HttpContext.RequestAborted`  when context switch , I mean  when switch filter pipeline in MVC  ,  render partial view in RazorView or RazorPage,  I think at those point , thow a `TaskCancelationException` is safe.

**Comment by Eilon** [comment]
@John0King - I'm not aware of any plans to make such a change. @davidfowl / @rynowak - any thoughts on checking `HttpContext.RequestAborted` from more places?

**Comment by davidfowl** [comment]
We shouldn't, it's already caused issues in identity, session and static files automagically using the token so no. You should use the token where appropriate in your API where you explicitly want to cancel work based on the connection lifetime.

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
