### ISSUE TITLE
.EnterpriseLibrary.Data.Database  error when running mvc core application 

### ISSUE THREAD

**Issue by WaedSaleh** [aspnet/Home#3008]
Hi, 
I get the following error when I use EnterpriseLibrary.Data.Database library in the class library that called for MVC core application, the logic worked fine with the old web project. 
AN EXCEPTION HAS OCCURRED  WITH ERRORCODE: Resolution of the dependency failed, type = "Microsoft.Practices.EnterpriseLibrary.Data.Database", name = "Configuration".
Exception occurred while: while resolving.
Exception is: InvalidOperationException - The type Database cannot be constructed. You must configure the container to supply this value.

**Comment by blowdart** [comment]
EnterpriseLibary is deprecated and was never written with Core in mine. I don't believe it's maintained anymore, so there's not much Core can do.
