### ISSUE TITLE
Add support for configuring the websocket keep alive interval

### ISSUE THREAD

**Issue by davidfowl** [aspnet/Home#3012]
The WebSocketProtocol allows setting the keep alive interval, we should expose this in our WebSocketMiddleware

https://github.com/dotnet/corefx/blob/031e40a64bd7a148f43e5a49055abbf5743b4543/src/System.Net.WebSockets.WebSocketProtocol/src/System/Net/WebSockets/WebSocketProtocol.cs#L12

**Comment by Tratcher** [comment]
Umm? https://github.com/aspnet/WebSockets/blob/fb6bc86be5354a5d1976a8e919ca3739a05fb0f8/src/Microsoft.AspNetCore.WebSockets/WebSocketMiddleware.cs#L97

**Comment by davidfowl** [comment]
Woops. 😄
