### ISSUE TITLE
Error! After Installation of AspNetCore and dotnet core the IIS Handler Mappings - aspNetCore is not installed 

### ISSUE THREAD

**Issue by dennisaubrey** [aspnet/Home#3015]
Error! After Installation of AspNetCore and dotnet core the IIS Handler Mappings - aspNetCore is not installed 

Windows 10 Pro 
AspNetCore.2.0.5.RuntimePackageStore_x64 
dotnet-runtime-2.0.5-win-x64
I also tried AspNetCore.2.0.6.RuntimePackageStore_x64
dotnet-runtime-2.0.6-win-x64 
![image](https://user-images.githubusercontent.com/36566794/38177309-4543984c-35cd-11e8-99d6-5df0a460196b.png)

Worked on another Windows 10 computer, but had the same issue. I installed, repaired, uninstalled, rebooted.  

There were other similar posts on this back in December 2017. The issue was the installer did not correctly register the aspNetCore dll. 

Thank you
Dennis Aubrey

**Comment by dennisaubrey** [comment]
![image](https://user-images.githubusercontent.com/36566794/38177411-0855833a-35cf-11e8-8f75-a35fc2e00ed6.png)

**Comment by dennisaubrey** [comment]
![image](https://user-images.githubusercontent.com/36566794/38177441-87721b7e-35cf-11e8-80ff-f6199262c147.png)

**Comment by dennisaubrey** [comment]
![image](https://user-images.githubusercontent.com/36566794/38177473-4acaacee-35d0-11e8-8316-67d56496301e.png)

When it works correctly. See above.

**Comment by dennisaubrey** [comment]
Note: The following is NOT installed on the Computer. 
Microsoft .NET Core 1.0.4 Runtime (x64) 
Microsoft .NET Core 1.0.4 & 1.1.1 - Windows Server Hosting 
Microsoft .NET Core 1.1.1 - Runtime (x64) 
Microsoft .NET Core Runtime (x64) 
![image](https://user-images.githubusercontent.com/36566794/38177822-72d6cd40-35d4-11e8-807f-f337d6bef29e.png)

**Comment by dennisaubrey** [comment]
Note: Important. This Windows 10 Computer works.. See installed Packages.
![image](https://user-images.githubusercontent.com/36566794/38177863-37f6c558-35d5-11e8-882f-e56851601c3b.png)

**Comment by dennisaubrey** [comment]
Where to download 
AspNetCore v1.1.1 and AspNetCore.Hosting.WindowsServices v1.1.2

**Comment by dennisaubrey** [comment]
https://docs.microsoft.com/en-us/dynamics-nav/troubleshooting-http-error-500.21-internal-server-error-aspnetcore-handler

**Comment by dennisaubrey** [comment]
If it is not installed, download and install Microsoft .NET Core - Windows Server Hosting bundle.

**Comment by dennisaubrey** [comment]
![image](https://user-images.githubusercontent.com/36566794/38179110-25c706c8-35ed-11e8-991a-9bf5519ae39c.png)

**Comment by dennisaubrey** [comment]
Installed
![image](https://user-images.githubusercontent.com/36566794/38179163-ce57d542-35ed-11e8-81c4-57600242acc7.png)

**Comment by dennisaubrey** [comment]
![image](https://user-images.githubusercontent.com/36566794/38179181-12b1f420-35ee-11e8-8928-a840b583cf95.png)

**Comment by dennisaubrey** [comment]
Web site is now working.

**Comment by Eilon** [comment]
Hi @dennisaubrey - I'm not sure I quite follow the posts above. Do you think there's a bug in the installer? Or somewhere? If so, can you provide more details? Thanks!

**Comment by dennisaubrey** [comment]
Hi Thank you,

After installing the AspNetCore and Donet - My Web API on IIS would not run and displayed an general Error.

It was not clear that I must install "Server Hosting Install" for AspNetCore on IIS. 

Through debugging, on two computers, I came to the conclusion that the only difference between the two Windows 10 Computers, one worked and the other did not,  is one had the Server Hosting and the other did not. It was also not clear on where to download the Server Hosting Install from reading the Windows docs on installation requirements. 

I installed the Server Hosting Install and everything is now working.

"Error! After Installation of AspNetCore and dotnet core the IIS Handler Mappings - aspNetCore is not installed" 

The Error Messaged displayed while running the My Web Site with AspNetCore - should have displayed that the AspNetCore Hosting  was not installed on IIS. I did install AspNetCore.  
![image](https://user-images.githubusercontent.com/36566794/38203449-41edd194-366d-11e8-97c1-b1af16c881af.png)

**Comment by Eilon** [comment]
@dennisaubrey thanks for the details.

@shirhatti - is there something we can do to make our installation instructions clearer in this space?

**Comment by dennisaubrey** [comment]
Note: Error Message on My Web Site. Before I started. 

![image](https://user-images.githubusercontent.com/36566794/38204578-7e8e6a42-3671-11e8-86ce-1d5fd8c7f00e.png)

**Comment by Tratcher** [comment]
@dennisaubrey the docs for this are at https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/troubleshoot and you can suggest doc improvements at https://github.com/aspnet/docs

**Comment by shirhatti** [comment]
Closing this issue as I've created a docs bug to track what @dennisaubrey complained about
