### ISSUE TITLE
Is there a way to add two resource folders to aspnet core localization?

### ISSUE THREAD

**Issue by eestein** [aspnet/Home#3018]
I'm currently developing the SDK for one project and as a requirement I need to add two resources locations. One will be provided with the SDK lib and another to be provided by the consumer app.

Currently, according to docs, this is how to add localization:

`services.AddLocalization(options => options.ResourcesPath = "Resources");`

I'm calling this method from my `BaseStartup` class that will be inherited by the consumer app's `Startup` class. So I need to be able to setup the location of the SDK's resources folder and the consumer app's one as well.

Maybe something like:

```csharp
    services.AddLocalization(options => 
    {
        options.ResourcesPath = "SDKResources";
        options.FromAssembly = sdkResourcesAssembly;
    });
    services.AddLocalization(options => 
    {
        options.ResourcesPath = "AppResources";
        options.FromAssembly = appResourcesAssembly;
    });
```
Is this possible? If so, how? If not, is there a workaround?

Checking online and even the source code (https://github.com/aspnet/Localization) wasn't of much help. The only thing I can think of is using `IStringLocalizerFactory` which accepts an assembly and the name of the file. Would it work? For instance, adding `services.AddLocalization()` and then just creating a wrapper class that would provide the consumer app with the strings using the factories created using `IStringLocalizerFactory`?

Thanks!

**Comment by eestein** [comment]
This is what I came up with, but haven't tested it yet:

```csharp
public abstract class BaseResource<T>
    where T : class
{
    private readonly IStringLocalizer _localizer;
    private readonly IStringLocalizer _sdkLocalizer;

    protected BaseResource(IStringLocalizerFactory factory)
    {
        var sdkAssembly = typeof(BaseResource<>).Assembly;
        var sdkAssemblyName = new AssemblyName(sdkAssembly.FullName);

        _localizer = factory.Create(typeof(T));
        _sdkLocalizer = factory.Create("Resources", sdkAssemblyName.Name);
    }

    protected string GetValue(string propertyName)
    {
        return _localizer[propertyName].ToString().NullIfEmpty() ?? _sdkLocalizer[propertyName];
    }
}
```

My idea is child classes on the consumer app would implement this `BaseResource` like:

```csharp
public class MyMessages : BaseResource<MyMessages>
{
    public string TranslationProperty => GetValue("TranslationProperty");

    public MyMessages(IStringLocalizerFactory factory) : base(factory)
    {
    }
}
```

Anyway, if you have any ideas...

**Comment by hishamco** [comment]
I hope this may help you https://github.com/aspnet/Entropy/blob/dev/samples/Localization.CustomResourceManager/Startup.cs#L30-L36

**Comment by eestein** [comment]
Hey thanks I'll take a look, but I ended up coming up with my own solution. I created a base startup class to handle all source assemblies containing my resource classes and then I load them.

```csharp

serviceCollection.AddLocalization();

var resourceTypes = typeof(BaseResource<>).Assembly.GetDerivedGenericTypes(typeof(BaseResource<>));

if (typeFromResourceAssembly != null)
    resourceTypes.AddRange(typeFromResourceAssembly.Assembly.GetDerivedGenericTypes(typeof(BaseResource<>)));

foreach (var resourceType in resourceTypes)
{
    serviceCollection.AddScoped(resourceType, resourceType);
}

return serviceCollection;

```
