### ISSUE TITLE
how to share cookies among apps with asp.net core 2.0+?

### ISSUE THREAD

**Issue by Hsinky** [aspnet/Home#3019]
I have two app,the one is web app,the other one is api app,  web request api，in api , I want to try get cookies from web, both Startup, i write the same code:
![qq 20180404001103](https://user-images.githubusercontent.com/10111222/38261428-bf2d3598-379c-11e8-90f5-dbebb75af925.jpg)

and the web app ,i use "HttpContext.SignInAsync" write cookies,but it can't get in the api app,

**Comment by Tratcher** [comment]
The docs have recently been updated for this scenario, let us know if they help: https://docs.microsoft.com/en-us/aspnet/core/security/cookie-sharing?tabs=aspnetcore2x

**Comment by Hsinky** [comment]
@Tratcher It doesn't seem to be useful ，could u tell me where is wrong in my code? please，the doc is too difficult for me，

**Comment by Hsinky** [comment]
@Tratcher eg: it cant tell us how to save and  get cookies，i want to get a full demo ,if u could help me，Be deeply grateful！

**Comment by Hsinky** [comment]
@Tratcher waitting for your answer online

**Comment by Tratcher** [comment]
I don't see anything obviously wrong with your app. You shouldn't need to set the DataProtectionProvider on your CookieAuthOptions but it shouldn't hurt anything.

You have one of two issues:
1) the client declines to send the cookies from one app to the other. A network trace or F12 browser tools should tell you if this is happening.
2) the apps can't read eachother's cookies. This would likely be a data protection configuration issue.

**Comment by Hsinky** [comment]
@Tratcher both the app started from vs 2017，not iis，or other.can u give me a simple demo？please

**Comment by Tratcher** [comment]
You appear to need more help than we can provide on short notice. I suggest asking on https://stackoverflow.com/questions/tagged/asp.net-core instead. The community is pretty responsive.

**Comment by Hsinky** [comment]
I think I am giving up，I am tired，the doc is not perfect

**Comment by Hsinky** [comment]
thans for your help again

**Comment by tastyeggs** [comment]
I had a similar issue, in my second application, then realized I had forgotten `app.UseAuthentication()` in the `Startup.Configure(..) ` method.
