### ISSUE TITLE
asp.net core 2.0 Assembly.Load   FileNotFoundException: Could not load file or assembly

### ISSUE THREAD

**Issue by laosandegudai** [aspnet/Home#3020]
in asp.net core 2.0
I use  'Assembly.Load' load dll,but it dose'nt work.
when i reference dll,then i load ,it works well.
when i no reference dll,it does'nt work.
I don't know what happend!  I checkd file name and namespace name.

**Comment by Eilon** [comment]
Thank you for filing this issue. In order for us to investigate this issue, could you please provide us with a minimal repro project that illustrates the problem?

**Comment by Eilon** [comment]
@davidfowl - is this by design because without an actual reference, the deps file doesn't know about the DLL, so Assembly.Load can't load it?

**Comment by laosandegudai** [comment]
I use 'LoadFrom'  replace it,Then it works well.
