### ISSUE TITLE
DI lifetime not validated when having a Scoped -> Singleton -> Scoped dependency chain.

### ISSUE THREAD

**Issue by joostvz** [aspnet/Home#3021]
I've had the following wrong DI configuration:
```
public void ConfigureServices(IServiceCollection services)
{
   services.AddScoped<Facade>();
   services.AddSingleton<Service>();
   services.AddScoped<DataAccess>();

   services.AddMvc();
}
```

Where `Facade` depends on `Service`, and `Service `depends on `DataAccess`. Note that I've introduced a _Captive Dependency_ here: a singleton which uses a scoped dependency. 

ASP.NET Core 2.0 should throw an exception to tell me this configuration is not valid. But it doesn't do that. Instead, I can normally run my project and the `DataAccess` becomes a singleton.

When I replace `services.AddScoped<Facade>();` with `services.AddSingleton<Facade>();` the exception is thrown: 
_Cannot consume scoped service 'WebApplication1.DataAccess' from singleton 'WebApplication1.Service'._

Is this a bug in ASP.NET? Does it stop the validation after it finds a scoped service which depends on a singleton service?

**Comment by joostvz** [comment]
Thanks for fixing @pakrym! Will this be available in ASP.NET Core 2.1?

**Comment by pakrym** [comment]
Yes

**Comment by Zoxive** [comment]
This needs to be in release notes somewhere. I just came across this issue. I had no idea we had broken lifetimes on some of our services because we had validation on for developers.
