### ISSUE TITLE
mvc core 2 StaticFiles midleware internal error

### ISSUE THREAD

**Issue by huhobocot** [aspnet/Home#3028]
I try to use nanoscroller js from https://jamesflorentino.github.io/nanoScrollerJS/
I install package from bower and link script to _Layout.cshtml file

`<script src="~/lib/nanoscroller/bin/javascripts/jquery.nanoscroller.js"></script>`

start my web app ang got error

```
GET https://localhost:44323/lib/nanoscroller/bin/javascripts/jquery.nanoscroller.js net::ERR_ABORTED
Event:500 
GET https://localhost:44323/lib/nanoscroller/bin/javascripts/jquery.nanoscroller.js 404 (Not Found)
```

I rename subfolder bin to dist and change link to 

`<script src="~/lib/nanoscroller/dist/javascripts/jquery.nanoscroller.js"></script>`

i update page and all fine

**Comment by Eilon** [comment]
@huhobocot what is the client making this request? This doesn't look like an ASP.NET Core log to me. Can you provide further trace details on the request/response?

@Tratcher any idea on this?

**Comment by huhobocot** [comment]
Hi, yes it is a web app. I want to show that happend if path contains "bin" folder. 
Of course i have a global error filter on server side, and nothing errors catched.

now i use workaround: 
`app.UseStaticFiles(new StaticFileOptions
            {
                FileProvider = new PhysicalFileProvider(
                    Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "lib", "nanoscroller", "bin")),
                RequestPath = "/lib/nanoscroller"
            });`

if you need more details, tell me how i can collect more info

**Comment by Eilon** [comment]
This doesn't appear to be an issue with ASP.NET Core. From various searches online, it looks to be a Chrome-specific issue that might be affected by some anti-virus products or other issues.
