### ISSUE TITLE
Behavior with multiple classes with main methods in directory

### ISSUE THREAD

**Issue by chriskinsman** [aspnet/Home#303]
If I create a project with two files:

Program.cs

```c#
using System;

public class Program
{
    public static void Main()
    {
        Console.WriteLine("Hello World");
    }
}
```

Program2.cs

```c#
using System;

public class Program2
{
    public static void Main()
    {
        Console.WriteLine("Hello World2");
    }
}
```

How does klr determine which Main to use?   Where I am really headed with this is a world where I could have multiple command line utils in a single folder  each of which have their own main and depend on other classes/modules in the directory.  This would allow me to build command line tooling using k that fits in with the platform.

**Comment by davidfowl** [comment]
It'll use the first one it finds with reflection order. In short, do it. We're building a global install experience that might fit what you want to do. You'll be able to take a nuget package, install it into the global packages folder and run it from the command line.

**Comment by Eilon** [comment]
@davidfowl you mean *don't* do it?

**Comment by davidfowl** [comment]
@Eilon fixed
