### ISSUE TITLE
One or more compilation failures occurred: error CS0041: Unexpected error writing debug information -- 'The version of Windows PDB writer is older than required: diasymreader.dll

### ISSUE THREAD

**Issue by reicher001** [aspnet/Home#3038]
We are getting this error randomly in various environments.  There does not seem to be a repeatable pattern for when this error will be thrown and a simple bouncing of the IIS AppPool/.NET Core application resolves the issue.  The source of the error seems to be "Source: Microsoft.AspNetCore.Mvc.Razor".  We are currently not precompiling our razor views in our MSBuild process.  Looking at [https://developercommunity.visualstudio.com/content/problem/196579/views-causing-pdb-writer-errors-when-built-on-vsts.html](https://developercommunity.visualstudio.com/content/problem/196579/views-causing-pdb-writer-errors-when-built-on-vsts.html) indicates that I am not the only one that has seen this.  

I am running on premise builds on these machines:
- Windows 2012 R2
- .NET Core SDK Version 2.1.101
- .NET Core Runtime Versions 1.0.4, 1.1.1, 2.0.0, 2.0.5, 2.0.6 
- .NET Core Framework Host Version 2.0.6
- .NET Framework Version 4.7.1

The environment web servers are:
- Windows 2012
- .NET Core Runtime Versions 2.0.0, 2.0.5
- .NET Core Framework Host version 2.0.5
- .NET Framework Version 4.7.1

At this point I am not sure if this is a build issue or an environment issue.  What do I need to do to get the correct version of this file in place?  Or is there a better place for me to report this issue?

Thanks,
Rick

**Comment by Eilon** [comment]
@NTaylorMullen / @rynowak / @pranavkm - any ideas on this?

**Comment by pranavkm** [comment]
Might be the same issue as - https://github.com/aspnet/Razor/issues/1955. We couldn't actually figure out why it was happening sporadically, but the guidance was to reference https://www.nuget.org/packages/Microsoft.DiaSymReader.Native/ in the application. We've addressed the package reference in 2.1.0.

**Comment by pranavkm** [comment]
@reicher001 feel free to reopen if you continue seeing the issue after you've added a reference to the DiaSymReader package.

**Comment by Eilon** [comment]
@pranavkm - should this issue be closed?
