### ISSUE TITLE
FormCollection does not seem to work

### ISSUE THREAD

**Issue by vncastanheira** [aspnet/Home#304]
Trying to use `FormCollection` on Post actions throws a `KeyNotFoundException`.
I made a [sample](https://onedrive.live.com/redir?resid=4893074DE3888A1B!67191&authkey=!ABhL2NrpCjG2B18&ithint=file%2czip) showing the error.

**Comment by Eilon** [comment]
@vncastanheira can you log this bug in https://github.com/aspnet/HttpAbstractions/issues ? That's where `FormCollection` lives.

**Comment by vncastanheira** [comment]
Ok.
