### ISSUE TITLE
Visual Studio 2017 max-width:fit-content CSS Validation

### ISSUE THREAD

**Issue by jaygriggs** [aspnet/Home#3045]
While creating a asp.net web application I noticed that this css is being marked as an invalid value.

```
 .LongevityTable {
        max-width: fit-content;
    }
```

It is certainly valid css as documented here
https://developer.mozilla.org/en-US/docs/Web/CSS/max-width

I'm using Visual Studio 2017 Community

**Comment by Eilon** [comment]
@jaygriggs - where is that CSS located? Is it a custom style that is part of your app, or part of the default templates?

**Comment by Eilon** [comment]
Just to make sure I understand, this is custom CSS that you added to a project, and VS is incorrectly flagging it as invalid? If that's the case, the best way to report these issues is directly within VS by clicking the "Send feedback" button in the upper-right corner of the VS window.

**Comment by jaygriggs** [comment]
Done. Thank you for your assistance Eilon.

**Comment by stephenstroud** [comment]
@jaygriggs I'm having the same issue in VS 2019 Preview.

**Comment by jaygriggs** [comment]
No not at all. Many conversations with the VS team has shown me that the reason for these types of issues is they follow EDGE/Internet explorer guidelines. If the code is invalid in EDGE(shows in VS) Funny that the whole tool has issues because they follow Edge guidelines. I have no clue what their thoughts are now that they announced they are giving up on Edge and moving to the Chromium core.
