### ISSUE TITLE
Http response JSON gets truncated

### ISSUE THREAD

**Issue by Eilon** [aspnet/Home#3047]
_From @ayazaliuk101 on January 25, 2018 10:55_

Hi we are getting a strange behavior with ASP.net core 2. We have created a simple web API that returns a large amount of JSON data (3.7MB) read from a static JSON file asynchronously. We have found that when we apply load on this application hosted in Azure web apps (> 50 requests) some of the responses contains JSON that is truncated. i.e. we get a status of 200 however the JSON is malformed and truncated. Our original hypothesis we thought was due to the size of the data and and have implemented compression to dis/prove this, however this issue still persists. We have found that this issue does not occur when the size of the Json is less than 1.5 MB and can handle requests > 250.We have also found that when the server resources are increased, i.e. we scale up or out on Azure (from basic) it reduces the frequency it occurs but does not remove it altogether.

To add to the above, we have carried out a similar exercise using ASP.net MVC and we do not get this behavior. The MVC application was also hosted on the same web app.

_Copied from original issue: dotnet/core#1240_

**Comment by Eilon** [comment]
_From @Petermarcu on March 18, 2018 17:51_

@Eilon

**Comment by Eilon** [comment]
_From @davidfowl on March 18, 2018 18:3_

Can you reproduce this locally?

**Comment by Eilon** [comment]
_From @ayazaliuk101 on March 18, 2018 21:9_

@Davidfowl yes. Also sent the details to MS  support with the source code and they can reproduce on their side as well. Need to run more logs for them to escalate to .net core team.

**Comment by Eilon** [comment]
_From @ayazaliuk101 on March 18, 2018 21:14_

Apologies when you say locally i.e. on my local machine then no, but I can reproduce on a Azure web app.

**Comment by Eilon** [comment]
_From @Petermarcu on March 23, 2018 15:55_

@Eilon @davidfowl should this issue get moved to an ASP.NET repo?

**Comment by Eilon** [comment]
@Petermarcu I think that isn't yet clear at this time. Could be an Azure issue.

@ayazaliuk101 - have you been able to find any more info on this?

**Comment by Eilon** [comment]
_From @tharmachandran on April 11, 2018 5:38_

the similar issue , it is generating while debugging ..

![screenshot_7](https://user-images.githubusercontent.com/31304719/38598075-9045a63e-3d78-11e8-8cad-98be192ea1aa.png)

**Comment by Eilon** [comment]
_From @tharmachandran on April 11, 2018 5:50_

Resolved by this ref .

```c#
public void ConfigureServices(IServiceCollection services)
{
    services.AddMvc()
        .AddJsonOptions(
            options => options.SerializerSettings.ReferenceLoopHandling = Newtonsoft.Json.ReferenceLoopHandling.Ignore
        );
}
```

**Comment by Eilon** [comment]
@tharmachandran - are you able to see if an exception is getting thrown during serialization because of a reference loop? That's the only thing I can think of that could cause this.

**Comment by SegueTechnologies** [comment]
Ah, I discovered that there was something in an IDisposable implementation in one of the injected constructor parameters which was throwing an exception.  This was aborting the response before it completed writing the output.  Don't see why that should happen, though!

**Comment by Eilon** [comment]
Closing because no further action is planned for this issue. If you're still having a problem, please log a new issue with details. Thanks!

**Comment by ershadnozari** [comment]
I'm encountering the same problem. Using fiddler I'm receiving the following error:

_[Fiddler] ReadResponse() failed: The server did not return a complete response for this request. Server returned 46,247 bytes._

I have the following JSON configuration already added:
```
services.AddMvc()
          .AddJsonOptions(options => options.SerializerSettings.ReferenceLoopHandling = Newtonsoft.Json.ReferenceLoopHandling.Ignore);
```
Setting accept: application/xml the response is returned just fine.

Stackoverflow question here: https://stackoverflow.com/questions/53037579/unable-to-retreive-entire-response-from-asp-net-core-web-api

**Comment by Tratcher** [comment]
@ershadnozari Comments on closed issues are not tracked, please open a new issue with the details for your scenario.

Other helpful things to include:
- The Fiddler trace
- A runnable repro project

**Comment by IanMercer** [comment]
For anyone else landing here from a search on this issue:

One reason this can happen is if an error happens while serializing the object to JSON. For example a field marked as required that is null in the data can cause this. The output simply stops and no exception is reported in this case.

Check that you can serialize the json object using `JSonConvert.SerializeObject()` before returning it and fix up any issues you find.
