### ISSUE TITLE
NullRefException in UnresolvedDependencyProvider

### ISSUE THREAD

**Issue by mlacouture** [aspnet/Home#305]
XRE\src\Microsoft.Framework.Runtime\DependencyManagement\UnresolvedDependencyProvider.cs

public LibraryDescription GetDescription(LibraryRange libraryRange, FrameworkName targetFramework) {
 ...
Version = libraryRange.VersionRange.MinVersion; // libraryRange.VersionRange can be null ...

**Comment by davidfowl** [comment]
Was fixed.
