### ISSUE TITLE
2.1 preview 2 Fedora packaging issue

### ISSUE THREAD

**Issue by AerisG222** [aspnet/Home#3050]
I just upgraded from preview1 to preview2, and am getting the following error when running my application:

```
It was not possible to find any compatible framework version
The specified framework 'Microsoft.AspNetCore.App', version '2.1.0-preview2-final' was notfound.
  - Check application dependencies and target a framework version installed at:
      /usr/share/dotnet/
  - Installing .NET Core prerequisites might help resolve this problem:
      http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
  - The .NET Core framework and SDK can be installed from:
      https://aka.ms/dotnet-download
  - The following versions are installed:
      2.1.0-preview1-final at [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
```

Here are the dotnet related packages I've installed (`dnf list --installed dotnet* aspnet*`) - in particular, note that aspnetcore-runtime-2.1.0-preview2-final is installed:

```
Installed Packages
aspnetcore-runtime-2.1.0-preview1-final.x86_64     2.1.0_preview1_final-1    @packages-microsoft-com-prod
aspnetcore-runtime-2.1.0-preview2-final.x86_64     2.1.0_preview2_final-1    @packages-microsoft-com-prod
aspnetcore-store-2.0.0.x86_64                      2.0.0-1                   @packages-microsoft-com-prod
aspnetcore-store-2.0.3.x86_64                      2.0.3-1                   @packages-microsoft-com-prod
aspnetcore-store-2.0.5.x86_64                      2.0.5-1                   @packages-microsoft-com-prod
dotnet-host.x86_64                                 2.1.0_preview2_26406_04-1 @packages-microsoft-com-prod
dotnet-hostfxr-2.0.3.x86_64                        2.0.3-1                   @packages-microsoft-com-prod
dotnet-hostfxr-2.0.5.x86_64                        2.0.5-1                   @packages-microsoft-com-prod
dotnet-hostfxr-2.1.0-preview1-26216-03.x86_64      2.1.0_preview1_26216_03-1 @packages-microsoft-com-prod
dotnet-hostfxr-2.1.0-preview2-26406-04.x86_64      2.1.0_preview2_26406_04-1 @packages-microsoft-com-prod
dotnet-runtime-2.0.3.x86_64                        2.0.3-1                   @packages-microsoft-com-prod
dotnet-runtime-2.0.5.x86_64                        2.0.5-1                   @packages-microsoft-com-prod
dotnet-runtime-2.1.0-preview1-26216-03.x86_64      2.1.0_preview1_26216_03-1 @packages-microsoft-com-prod
dotnet-runtime-2.1.0-preview2-26406-04.x86_64      2.1.0_preview2_26406_04-1 @packages-microsoft-com-prod
dotnet-runtime-deps-2.1.0-preview2-26406-04.x86_64 2.1.0_preview2_26406_04-1 @packages-microsoft-com-prod
dotnet-sdk-2.0.3.x86_64                            2.0.3-1                   @packages-microsoft-com-prod
dotnet-sdk-2.1.2.x86_64                            2.1.2-1                   @packages-microsoft-com-prod
dotnet-sdk-2.1.300-preview1-008174.x86_64          2.1.300_preview1_008174-1 @packages-microsoft-com-prod
dotnet-sdk-2.1.300-preview2-008530.x86_64          2.1.300_preview2_008530-1 @packages-microsoft-com-prod
dotnet-sdk-2.1.4.x86_64                            2.1.4-1                   @packages-microsoft-com-prod
```

Looking at the contents of aspnetcore-runtime-2.1.0-preview2-final (`dnf repoquery -l aspnetcore-runtime-2.1.0-preview2-final`), I noticed the Microsoft.AspNetCore.All and Microsoft.AspNetCore.App were listed as being in `/opt/rh/rh-dotnet20/root/usr/lib64/dotnet/shared/` rather than `/usr/share/dotnet/shared/`.

I then copied the contents from /opt/rh.. to the expected location in /usr/share and then the application worked again.

**Comment by Eilon** [comment]
@leecow / @JunTaoLuo / @muratg - any ideas on this?

**Comment by leecow** [comment]
Sounds like an issue with the aspnetcore-runtime authoring. @JunTaoLuo would need to have a look.

**Comment by JunTaoLuo** [comment]
Looks like the redhat specific rpm was uploaded instead of the generic one. I'm taking a look to see if this is an authoring issue or an upload issue.

**Comment by JunTaoLuo** [comment]
Looks like the packages were authored correctly and the wrong one was uploaded to the rpm feed.

**Comment by leecow** [comment]
Thanks John - will upload the correct package as soon as we finish working through the host installer issues.

**Comment by AerisG222** [comment]
I just tried to update to RC1 and could not find it in the list of available packages.  I then followed the steps at https://www.microsoft.com/net/download/linux-package-manager/fedora26/sdk-current, and replaced my prior repo with the one above.  I was then able to install RC1 just fine.

As such, this was probably just a configuration issue on my side, consuming an incorrect package (though this had worked with prior releases w/o an issue).

Sorry for any time wasted, please close as you see fit.
