### ISSUE TITLE
Problems with default key store on Pro Windows

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Home#3051]
_From @ShadowDancer on April 12, 2018 14:14_

### Problems with default key store on Pro Windows
*Because of differences between pro and server windows editions key store will work incorrectly on Windows 10 pro machines ootb.*  

### Functional impact
*Because of default fallback to in-memory store, encryption keys will be discarded after each restart, logging users out, etc.*  

### Minimal repro steps
1. Deploy AspNetCore applications with auth on IIS on Server and Pro machines
2. Set `loadUserProfile` in AppPool configuration to true
3. Login on both applications (in browser)
4. Restart application in IIS
5. Refresh both applications (in browser)

### Expected result
Both apps should be logged in, because after setting `loadUserProfile="true"` one expects keys to be stored in ` %LOCALAPPDATA%\ASP.NET\DataProtection-Keys` directory, following the doc:
https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/configuration/default-settings?view=aspnetcore-2.1
OR it should be mentioned in doc and/or in logs that `applicationHost.config` needs to be altered manually. 

### Actual result
*User is logged out in application hosted on Windows 10 Pro machine, and logged in on Windows Server machine*

### Further technical details
The problem lies in difference between default `applicationHost.config` (`C:\Windows\System32\inetsrv\Config\app\applicationHost.config`):
windows 7/10 pro applicationPoolDefaults :
```
            <applicationPoolDefaults managedRuntimeVersion="v4.0">
                <processModel identityType="ApplicationPoolIdentity" />
            </applicationPoolDefaults>
```
windows server 2012 R2 applicationPoolDefaults 
```
            <applicationPoolDefaults managedRuntimeVersion="v4.0">
                <processModel identityType="ApplicationPoolIdentity" loadUserProfile="true" setProfileEnvironment="false" />
            </applicationPoolDefaults>
```
there is `setProfileEnvironment` attribute set to false on Pro machines. This setting cannot be altered in advanced appPool configuration and is not set to true when `loadUserProfile` is set to true.
 Because of this environment variable
 `%LOCALAPPDATA%` is set to `C:\WINDOWS\system32\config\systemprofile` and not `C:\Users\myapppool\AppData\Local`, and keys cannot be stored there because there is no write permission.
I would expect that it is either correctly configured by default, or it is stated in documentation (or found in google), that I need to manually configure appPool. I've lost lots of time debugging it. I think it is important, because developers are generally working on Pro, not Server machines (are they?).

_Copied from original issue: aspnet/Hosting#1375_

**Comment by Tratcher** [comment]
@pan-wang @shirhatti @jkotalik

**Comment by pan-wang** [comment]
I believe this is by design. IIS setup code does detect client and server and set different value. This KB has details about this setProfileEnvironment setting, https://support.microsoft.com/en-us/help/2547655/windows-7-sp1-causes-intellitrace-collection-to-fail-on-iis.
