### ISSUE TITLE
Routing tests broken on Mac

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/Home#3052]
https://travis-ci.org/aspnet/Routing/jobs/365869435

```
[xUnit.net 00:00:03.2304060]     Microsoft.AspNetCore.Routing.RouteTest.GetVirtualPath_AlwaysUsesDefaultUrlEncoder [FAIL]
Failed   Microsoft.AspNetCore.Routing.RouteTest.GetVirtualPath_AlwaysUsesDefaultUrlEncoder
Error Message:
 Assert.Equal() Failure
                                 ↓ (pos 62)
Expected: ···20%23characters%20J%C3%B6rn
Actual:   ···20%23characters%20J%EF%BF%BDrn
                                 ↑ (pos 62)
Stack Trace:
   at Microsoft.AspNetCore.Routing.RouteTest.GetVirtualPath_AlwaysUsesDefaultUrlEncoder() in /_/test/Microsoft.AspNetCore.Routing.Tests/RouteTest.cs:line 675
```

cc @kichalla @jbagga @NTaylorMullen ?

**Comment by JunTaoLuo** [comment]
Looks like it's caused by https://github.com/aspnet/Routing/commit/4184b2406d8c65dda7f7fb4faf365f79a2b45f02

**Comment by kichalla** [comment]
I will take a look

**Comment by kichalla** [comment]
@dougbu any ideas why would the encoding for text `Jörn` would be different in Mac?

**Comment by dougbu** [comment]
@kichalla I'm wondering if the original character is missing on a Mac. "%EF%BF%BD" is the (a?) Unicode replacement character. See https://apps.timwhitlock.info/unicode/inspect?s=%EF%BF%BD

Suggest searching .NET documentation for cases where it will substitute the replacement character. Then, choose a different character (not 'ö') for this test.

Separately, please react to aspnet/Routing@4184b24 in aspnet/Mvc. Failures there look like some results were generated with the test `UrlEncoder` in DI.

**Comment by kichalla** [comment]
Fixed with https://github.com/aspnet/Routing/commit/39f7420c4d34c73bc7c58d8bcd8a382af4e71492
