### ISSUE TITLE
Could not install package 'System.IO.FileSystem 4.3.0'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile259', but the package does not contain any assembly references or content files that are compatible with that framework. 

### ISSUE THREAD

**Issue by pkpaul5** [aspnet/Home#3053]
Working on Xamarin Cross Platform project(PCL) in Visual Studio 2017. Need to do some file IO operations but not able to add reference to System.IO.FileSystem nugget. Getting this error Could not install package 'System.IO.FileSystem 4.3.0'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile259', but the package does not contain any assembly references or content files that are compatible with that framework.

**Comment by blowdart** [comment]
This isn't an ASP.NET question, it appears to be one for Xamarin. So I'd suggest finding the right place in their org, https://github.com/xamarin but I don't know what you'd choose, so I can't move the issue for you.

**Comment by pkpaul5** [comment]
I have raised it under Xamarin.Thanks
