### ISSUE TITLE
Propagate handled exceptions from exception handler middleware

### ISSUE THREAD

**Issue by henkmollema** [aspnet/Home#3056]
Currently the exception handler middleware doesn't propagate the exception after it's handled successfully. This means earlier middleware in the pipeline have no chance to log the exception to other logging systems. For example, Google Cloud error reporting middleware is registered before the exception handler middleware which consists of a simple `try/catch` mechanism. However, the `catch` is never hit as the exception is not being re-thrown.

There has been a `TODO` about this in the code for quite some time:
https://github.com/aspnet/Diagnostics/blob/9734338a55b5fbd47c7662a3c159a255938595be/src/Microsoft.AspNetCore.Diagnostics/ExceptionHandler/ExceptionHandlerMiddleware.cs#L89-L90

Are there any plans to implement this? Perhaps controllable via an option? I could send a PR if this feature is desired.

**Comment by henkmollema** [comment]
One way to get around this is using the `IExceptionHandlerFeature` and read the error from it in other middleware or the exception handler path after the exception handler middleware has been executed. This looks roughly like this:

```cs
public async Task OnGetAsync([FromServices]IExceptionLogger exceptionLogger)
{
    var exception = HttpContext.Features.Get<IExceptionHandlerFeature>()?.Error;
    if (exception != null)
    {
        // Log the error to Google Error Reporting service
        await exceptionLogger.LogAsync(exception, HttpContext);
    }
}
```

**Comment by Tratcher** [comment]
No, there are no plans to change this at the moment. Rethrowing may destablaize the response. The best place to get the exception from is the log system.

**Comment by henkmollema** [comment]
I see, that was my concern as well. I'll find another way. Thanks!
