### ISSUE TITLE
Be able to get back from IServiceProvider to IServiceCollection

### ISSUE THREAD

**Issue by tugberkugurlu** [aspnet/Home#3057]
I am looking for a sane way to get back from an instance of `IServiceProvider` which is built from `IServiceCollection` to a fresh instance of `IServiceCollection`. This is basically why I need this: https://github.com/tugberkugurlu/AspNetCoreSamples/blob/4655f7520b6a0cbec65c949a480e35448268b578/AppBuilderTests/WebApp.Tests/ApplicationBuilderTests.cs#L39-L52 If this is possible, I could go from `webHost.Services ` to an instance of `IServiceCollection` w/o that unreliable reflection magic.

Is there a sane way to do this today?

**Comment by davidfowl** [comment]
That’s not a thing. What are you trying to do with the TrackingApplicationBuilder?

**Comment by tugberkugurlu** [comment]
> What are you trying to do with the TrackingApplicationBuilder?

Trying to test the registration order of fhe middlewares: https://github.com/tugberkugurlu/AspNetCoreSamples/blob/4655f7520b6a0cbec65c949a480e35448268b578/AppBuilderTests/WebApp.Tests/ApplicationBuilderTests.cs#L156 I would love to have a better way to do this but this is the best I could have come up with.

**Comment by Eilon** [comment]
Hi, there are no plans to make this work in ASP.NET Core. I suggest posting this question to [StackOverflow](https://www.stackoverflow.com) using the `asp.net-core` tag.
