### ISSUE TITLE
SetDoNotCacheHeaders overwrites cache headers

### ISSUE THREAD

**Issue by garymacpherson** [aspnet/Home#3058]
Following on from https://github.com/aspnet/Home/issues/2414

I do not believe this issue is considered closed as I have situations that require "Cache-Control: private, no-cache, no-store, max-age = 0, must-revalidate"  and it is being overridden by the default CSRF token implementation.

Is there any desire to update this for 2.1 to allow control over this?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @garymacpherson.
@javiercn, can you please look into this? Thanks.

**Comment by javiercn** [comment]
Hi,

There is no point in specifying either

> max-age = 0, must-revalidate

if you already specify no-cache, no-store as they prevent anything from being cached.
max-age only applies to cached responses
must-revalidate only applies to cached responses.

Do you have an actual functional issue around this?

**Comment by garymacpherson** [comment]
Thanks for the clarification, you are correct.

Cheers for looking into it anyway.

**Comment by javiercn** [comment]
I don't see anywhere in that page where it mentions that no-cache, no-store is not enough. @blowdart might have an opinion.

**Comment by javiercn** [comment]
I don't think we need this, but I would be open to us adding an option to AntiforgeryOptions to allow you control of these values. Provided that @blowdart is ok with it. We would probably accept a PR for this.

**Comment by blowdart** [comment]
I'd go a little further. If the headers already set contain, at a minimum, the values we want, then we shouldn't bother changing them. That way we don't override choice. Does that make sense?
