### ISSUE TITLE
Has BuildServiceProvider been called?

### ISSUE THREAD

**Issue by generik0** [aspnet/Home#3059]
Hi

Regarding Microsoft.Extensions.DependencyInjection

I know this might seam like a strange question, but trust me i have a reason.
But can you tell me if i can determine if
`serviceCollection.BuildServiceProvider()`
has been called / built?
And/Or if anything in the serviceCollection has been resolved/GetRequiredService?

Thanks :-)

**Comment by davidfowl** [comment]
Noope.
