### ISSUE TITLE
Usability: Whitelisting a hostname through a policy doesn't work, if the hostname has an ending `/`

### ISSUE THREAD

**Issue by mkArtakMSFT** [aspnet/Home#3060]
This was what I was trying for some time and couldn't figure out why it didn't work.

```csharp
services.AddCors(options => {
                options.AddPolicy("blazor", policy => policy.WithOrigins("http://localhost:59239/"));
            });
```

After removing the ending `\` things worked just fine:
```csharp
services.AddCors(options => {
                options.AddPolicy("blazor", policy => policy.WithOrigins("http://localhost:59239"));
            });
```
This just indicates that it's not easy use this - need to come up with a way to improve dev experience with this APIs.

**Comment by blowdart** [comment]
To be fair that's not a host name at that point, it's a host name plus a path.
