### ISSUE TITLE
DataProtectionProvider.Create() throws an exception during certificate protected key encryption when Fips is enabled

### ISSUE THREAD

**Issue by bszarko** [aspnet/Home#3066]
### Title
DataProtectionProvider.Create() throws an exception during certificate protected key encryption when Fips is enabled.

### Functional impact
Shared cookie authentication does not work on systems with Fips enabled

### Minimal repro steps
1. Enable Fips compliant algorithms on the system running the MVC app
2. Download and compile the following MVC solution at https://github.com/bszarko/Study/
3. Deploy to IIS 7.5
4. Import Dev.SharedCookieTest.Cert02.pfx into cert store localmachine, my
5. Give AppPool identity permissions to the certificate's private key
6. Open a desktop browser and navigate to the application

### Expected result
A key should be generated and encrypted (protected by certificate) using a Fips compliant algorithm. 

### Actual result
Exception
"This implementation is not part of the Windows Platform FIPS validated cryptographic algorithms"

### Further technical details
Whens Fips is disabled this setup works but throws an exception when Fips is enabled.

// Test project
https://github.com/bszarko/Study/

Tests:
OS: Windows & & Windows 2008 R2 SP1
IIS 7.5.7600, AppPool using a Service Account
Frameworks: 4.6.1, 4.6.2, 4.7.1, netstandard 2.0
Visual Studio 2015 Enterprise & Visual Studio 2017 Community

I also tried adding crypto mappings to the machine.config in hopes that something other than RijndaelManaged was used.

"This implementation is not part of the Windows Platform FIPS validated cryptographic algorithms"

[InvalidOperationException: This implementation is not part of the Windows Platform FIPS validated cryptographic algorithms.]
   System.Security.Cryptography.RijndaelManaged..ctor() +5256144
   System.Security.Cryptography.Xml.EncryptedXml.Encrypt(XmlElement inputElement, X509Certificate2 certificate) +477
   Microsoft.AspNetCore.DataProtection.XmlEncryption.CertificateXmlEncryptor.Microsoft.AspNetCore.DataProtection.XmlEncryption.IInternalCertificateXmlEncryptor.PerformEncryption(EncryptedXml encryptedXml, XmlElement elementToEncrypt) +200
   Microsoft.AspNetCore.DataProtection.XmlEncryption.CertificateXmlEncryptor.EncryptElement(XElement plaintextElement) +394
   Microsoft.AspNetCore.DataProtection.XmlEncryption.CertificateXmlEncryptor.Encrypt(XElement plaintextElement) +47
   Microsoft.AspNetCore.DataProtection.XmlEncryption.XmlEncryptionExtensions.EncryptIfNecessary(IXmlEncryptor encryptor, XElement element) +407
   Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager.Microsoft.AspNetCore.DataProtection.KeyManagement.Internal.IInternalXmlKeyManager.CreateNewKey(Guid keyId, DateTimeOffset creationDate, DateTimeOffset activationDate, DateTimeOffset expirationDate) +1402
   Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager.CreateNewKey(DateTimeOffset activationDate, DateTimeOffset expirationDate) +136
   Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.CreateCacheableKeyRingCore(DateTimeOffset now, IKey keyJustAdded) +599
   Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.Microsoft.AspNetCore.DataProtection.KeyManagement.Internal.ICacheableKeyRingProvider.GetCacheableKeyRing(DateTimeOffset now) +12
   Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.GetCurrentKeyRingCore(DateTime utcNow) +513
   Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Protect(Byte[] plaintext) +84

[CryptographicException: An error occurred while trying to encrypt the provided data. Refer to the inner exception for more information.]
   Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Protect(Byte[] plaintext) +821
   Microsoft.Owin.Security.DataHandler.SecureDataFormat`1.Protect(TData data) +92
   Microsoft.Owin.Security.Cookies.<ApplyResponseGrantAsync>d__b.MoveNext() +1334
   System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() +31
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +60
   Microsoft.Owin.Security.Infrastructure.<ApplyResponseCoreAsync>d__b.MoveNext() +218
   System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() +31
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +60
   Microsoft.Owin.Security.Infrastructure.<ApplyResponseAsync>d__8.MoveNext() +475
   System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() +31
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +60
   Microsoft.Owin.Security.Infrastructure.<TeardownAsync>d__5.MoveNext() +215
   System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() +31
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +60
   Microsoft.Owin.Security.Infrastructure.<Invoke>d__0.MoveNext() +968
   System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() +31
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +60
   Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.<RunApp>d__5.MoveNext() +194
   System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() +31
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +60
   Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.<DoFinalWork>d__2.MoveNext() +184
   System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() +31
   Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.StageAsyncResult.End(IAsyncResult ar) +117
   System.Web.AsyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +365
   System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step) +195
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +128

Owin Startup

public void ConfigureAuth(IAppBuilder app)
		{
			// these don't seem to change the behavior
			if (CryptoConfig.AllowOnlyFipsAlgorithms)
			{
				CryptoConfig.AddAlgorithm(
					typeof(AesCryptoServiceProvider),
					"AES",
					"AesCryptoServiceProvider",
					"System.Security.Cryptography.AesCryptoServiceProvider",
					"System.Security.Cryptography.AES"
				);

				CryptoConfig.AddAlgorithm(
					typeof(SHA256CryptoServiceProvider),
					"SHA256",
					"SHA256CryptoServiceProvider",
					"System.Security.Cryptography.SHA256CryptoServiceProvider",
					"System.Security.Cryptography.SHA256"
				);

				CryptoConfig.AddAlgorithm(
					typeof(SHA256CryptoServiceProvider),
					"SHA512",
					"SHA512CryptoServiceProvider",
					"System.Security.Cryptography.SHA512CryptoServiceProvider",
					"System.Security.Cryptography.SHA512"
				);
			}

			var encryptionSettings = new AuthenticatedEncryptorConfiguration()
			{
				EncryptionAlgorithm = EncryptionAlgorithm.AES_256_CBC,
				ValidationAlgorithm = ValidationAlgorithm.HMACSHA256
			};

			// apply AppPool identity or service account permissions to registry path
			var regPath = @"SOFTWARE\SharedCookieTest\Keys";
			Registry.LocalMachine.CreateSubKey(regPath, true);

			/*
			 * Certificate Thumbprints
			 * 6bee3f190055703c0dcd01e7c433462069549762 - dev.sharedcookietest.cert02
			 * d74e3a5413047996a10bda4661d296ca7f741ff8 - Dev.SharedCookieTest.Cert01
			*/

			var store = new X509Store(StoreName.My, StoreLocation.LocalMachine);
			store.Open(OpenFlags.OpenExistingOnly);
			var cert = store.Certificates
				.OfType<X509Certificate2>()
				.FirstOrDefault(c => c.Thumbprint.Equals("6bee3f190055703c0dcd01e7c433462069549762", StringComparison.CurrentCultureIgnoreCase));

			var protectionProvider = DataProtectionProvider.Create(
				new DirectoryInfo($@"{HostingEnvironment.MapPath("~")}\keys"),
				options =>
				{
					options.SetDefaultKeyLifetime(TimeSpan.FromDays(365));
					options.UseCryptographicAlgorithms(encryptionSettings);

					//options.UseCustomCryptographicAlgorithms(
					//	new CngCbcAuthenticatedEncryptorConfiguration()
					//	{
					//		EncryptionAlgorithm = "AES",
					//		//EncryptionAlgorithmProvider = WhatShouldThisBe?,//"Advanced Encryption Standard",//"ECDiffieHellmanCng",//"BCryptCloseAlgorithmProvider",//"MS_ENH_RSA_AES_PROV",
					//		EncryptionAlgorithmKeySize = 256,
					//		HashAlgorithm = "SHA256"
					//		//HashAlgorithmProvider = WhatShouldThisBe?//null//"SHA256CryptoServiceProvider"//"Microsoft Enhanced RSA and AES Cryptographic Provider"
					//	});

					options.PersistKeysToRegistry(Registry.LocalMachine.OpenSubKey(regPath, true));
					options.ProtectKeysWithCertificate(cert);
				});

			var dataProtector = protectionProvider.CreateProtector(
				"CookieAuthenticationMiddleware",
				"Cookie",
				"v2");

			// Enable the application to use a cookie to store information for the signed in user
			// and to use a cookie to temporarily store information about a user logging in with a third party login provider
			// Configure the sign in cookie
			app.UseCookieAuthentication(new CookieAuthenticationOptions
			{
				TicketDataFormat = new AspNetTicketDataFormat(new DataProtectorShim(dataProtector)),
				AuthenticationType = DefaultAuthenticationTypes.ApplicationCookie,
				AuthenticationMode = Microsoft.Owin.Security.AuthenticationMode.Active,
				CookieDomain = "localhost",
				CookieName = ".AspNet.SharedCookie",
				CookiePath = "/",
				CookieSecure = CookieSecureOption.SameAsRequest
			});
		}

**Comment by blowdart** [comment]
@bartonjs this appears to be a bug in *full* framework, where it's using a managed implementation when under FIPS. Thus it's in your bailiwick. Can you log this wherever this needs logging, and then close this issue?

**Comment by bszarko** [comment]
Any workarounds?  I am working on a solution that will require shared cookies so any suggestions would be appreciated.  Maybe a custom xml repo. or key manager?

Should I close this issue then or will it be taken care of?

**Comment by bartonjs** [comment]
There's no workaround in the EncryptedXml layer.  It just straight-up instantiates RIjnadelManaged when it wants AES.

https://referencesource.microsoft.com/#System.Security/system/security/cryptography/xml/encryptedxml.cs,511

If what your host is after is **FIPS Approved algorithms** vs **FIPS Certified implementations** then you can just disable the FIPS enforcement in the .NET Framework for your application:  https://blogs.msdn.microsoft.com/shawnfa/2008/03/14/disabling-the-fips-algorithm-check/

**Comment by bszarko** [comment]
Thanks.  Looks like it may have been partially addressed by FipsAwareEncryptedXml but only on the decrypt.

**FipsAwareEncryptedXml**
https://referencesource.microsoft.com/#System.Configuration/System/Configuration/FipsAwareEncryptedXml.cs,18

**RsaProtectedConfigurationProvider**
https://referencesource.microsoft.com/#System.Configuration/System/Configuration/RSAProtectedConfigurationProvider.cs,35

If this issue has been bubbled up, go ahead and close it.

**Comment by blowdart** [comment]
It's logged in the internal bug database for full framework now, so I'll close it. Sorry there's no real public way for you to track it.
