### ISSUE TITLE
Request: Use DI for the IOptionsCache internal to OptionsManager<T> 

### ISSUE THREAD

**Issue by achandlerwhite** [aspnet/Home#3067]
I am using a derived implementation of IOptionsCache to for certain multitenant situations. OptionsMonitor<T> uses DI to get the cache, but OptionsManager<T> does not. This means that using IOption<T> or IOptionsSnapshot<T> (which both resolve to OptionsManager<T>) I can't use my own IOptionsCache implementation.

Is this something that could please be considered?

Update: edited to correctly refer to OptionsManager as the root cause.

**Comment by HaoK** [comment]
The options manager is pretty simple, you can just drop in your own OptionsManager implementation that uses whatever cache you want.

**Comment by achandlerwhite** [comment]
@HaoK, thanks for the reply. Yeah that’s what I ended up doing with the benefit of letting the programmer having a choice between the default or my implementation.
