### ISSUE TITLE
Enhancement proposal: Dependency injection support using an attribute

### ISSUE THREAD

**Issue by orobert91** [aspnet/Home#3068]
Instead of having to assign the instance to a field in the constructor manually:

```
public class MyClass
{
	private ClassToInject _classToInject;

	public MyClass(ClassToInject _classToInject) {
		_classToInject = classToInject;
	}
}
```

Allow this kind of syntax for dependency injection, like most DI frameworks:

```
public class MyClass
{
	[Inject]
	private ClassToInject _classToInject;
}
```

This would save a lot of code, much easier to maintain and much more readable when there is a lot of dependencies.

**Comment by salem84** [comment]
Similar to BlazorComponent injection: https://blazor.net/docs/dependency-injection.html#request-a-service-in-a-component

For base classes is very useful

**Comment by Eilon** [comment]
Closing because while this is an interesting suggestion, we have no plans to support this pattern. There are some 3rd party DI containers that can be used with ASP.NET Core that support similar patterns.
