### ISSUE TITLE
Allow HTTPS in Development without localhost

### ISSUE THREAD

**Issue by hadiidbouk** [aspnet/Home#3069]
Hello, 

I am trying to test my apis using a Mobile device, i am working locally, my computer is the server.

Is there anyway to allow Https not just for localhost? also for my computer host name or IP ?

ex : 
https://localhost:5000  -> working fine
https://My-Pc:5000 -> Not working

The problem that the certificate is created only for localhost.

**Comment by Tratcher** [comment]
Any reason you can't provide your own certificate?
