### ISSUE TITLE
'grunt' missing when using build.cmd

### ISSUE THREAD

**Issue by kevinkuszyk** [aspnet/Home#307]
I have a default MVC 6 project which I created from VS 2015 CTP 5.

I'm trying to build it on a [build server](https://ci.appveyor.com/project/kevinkuszyk/r4mvc/build/1.0.18#L968) (see issue #296), using the `build.cmd` and `KoreBuild` pattern used in the aspnet projects, but I get the following error:

````
'grunt' is not recognized as an internal or external command
````

The solution is [here](https://github.com/T4MVC/R4MVC) for reference.

**Comment by dougbu** [comment]
@kevinkuszyk am I correct `build.cmd` fails when attempting to compile the test project?

if so, either install `grunt` globally (`npm install --global --quiet grunt`) or remove the scripts section from the test project.json file.  If going the install route, might need to install `bower` globally as well (`npm install --global --quiet bower`).

FYI the scripts section tends to work better from VS or when everything is globally installed.

**Comment by kevinkuszyk** [comment]
Thanks @dougbu - removing the `scripts` section from the `project.json` has done the trick.
