### ISSUE TITLE
WebSocket Server does not receive Close Frame from Chrome

### ISSUE THREAD

**Issue by ndreisg** [aspnet/Home#3070]
I have an ASP.net Core WebSocket Server, and a WebClient that is connecting to that Server with Javascript.

Chrome seems to be the only browser that doesn't (always) send a Close Frame when I close the tab/browser where the client is running. (Works when Server is running on localhost but not when it's running in Azure App Service, see the chromium issue below for more info)

Some days ago I created an Issue: https://bugs.chromium.org/p/chromium/issues/detail?id=832582

Unfortunately the Chromium Team isn't going to fix this issue.

**Question:**

When no Close Frame is sent to the Server but the socket is closed anyway, shouldn't the Server throw an Exception or something?

Here my code:

```
try
{
  WebSocketReceiveResult message = await webSocket.ReceiveAsync(new ArraySegment<byte>(buffer), CancellationToken.None);
  while (!message.CloseStatus.HasValue)
  {
    // do something with the message here...
    message = await webSocket.ReceiveAsync(new ArraySegment<byte>(buffer), CancellationToken.None);
  }
  Close(); // Function with some cleanup code
}
catch (Exception e)
{
  Close(); // <-- I expect this to be called when the socket is closed without a Close Frame. But it is not :(
}
```
Unfortunately when Chrome closes the Socket without a Close Frame, the ReceiveAsync keeps waiting forever. No exception is thrown.

Is there any other way to find out if a socket has died without getting a Close Frame?

**Comment by Tratcher** [comment]
Which server? IIS + Kestrel?

**Comment by ndreisg** [comment]
The problem is occurring on Azure App Service. I didn't try IIS. 
When I debug it on localhost, everything is working fine (Server is receiving all Close Frames from Chrome, I guess because of faster communication)

**Comment by ndreisg** [comment]
Any news on this?

**Comment by ndreisg** [comment]
This problem seems to be fixed.
I republished my app and now the exceptions get thrown as expected.
