### ISSUE TITLE
Cannot get light-up technique of assembly load to work for ASP.NET Core 2.0

### ISSUE THREAD

**Issue by bobuva** [aspnet/Home#3071]
I recently learned about the light-up technique that Application Insights uses to get their assemblies loaded into any ASP.NET app. [Here](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/platform-specific-configuration?view=aspnetcore-2.1) is a link to it.

I've implemented an IHostingStartup class in an assembly.  I'm using a target of `netcoreapp2.0`. One thing I'm not sure if it could be an issue is that I had installed the .NET Core 2.1 preview (first and the second one), and the SDK that comes with it. So my .NET Core SDK is 2.1.

I followed exactly the same process of making sure my assembly, symbols and deps.json are put in the right place in the my user profile tree under the `.dotnet` subdirectory paths. In fact I used the nice Powershell script that I think Luke Latham wrote and referred to [here](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/platform-specific-configuration?view=aspnetcore-2.1). 

I verified that the files are copied correctly, and that my deps.json file has the necessary entries.

When I run a hosting app like the `HostingStartupSample` that Luke used (all of the source is [here](https://github.com/aspnet/Docs/tree/master/aspnetcore/host-and-deploy/platform-specific-configuration/sample), I get this exception as it starts up:

```
System.InvalidOperationException: Startup assembly ShiftLeft.NetCore.Agent failed to execute. See the inner exception for more details. ---> System.IO.FileNotFoundException: Could not load file or assembly 'ShiftLeft.NetCore.Agent, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks, IntPtr ptrLoadContextBinder)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, IntPtr ptrLoadContextBinder)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.BuildCommonServices(AggregateException& hostingStartupErrors)
   --- End of inner exception stack trace ---
```

I have no idea why it cannot find it. I set the COREHOST_TRACE=1 environment  variable but didn't see anything more than what I already knew. 

Here is the code:

```
using Microsoft.AspNetCore.Hosting;
using ShiftLeft.Agent;

// Use a Hosting Startup Attribute to identify the IHostingStartup implementation.
[assembly: HostingStartup(typeof(ShiftLeft.NetCore.Agent.AgentHostingStartup))]

namespace ShiftLeft.NetCore.Agent
{
    public class AgentHostingStartup : IHostingStartup
    {
        public static void Main(string[] args)
        { }

        public void Configure(IWebHostBuilder builder)
        {
            Logger.Instance.Log("AgentHostingStartup.Configure...");
        }
    }
}
```

The Main() entrypoint is to make the compiler happy -- apparently I cannot use that interface without having a Main entrypoint? All I do for my configuration is simply use a logger class to tell me if it gets loaded.

I could use some additional tips on troubleshooting this or if you think there's a bug. Thanks, Bob

**Comment by bobuva** [comment]
I have a little more information on this:

1. I set the environment variable COREHOST_TRACE =1.
2. In the output of `dotnet run` I see my environment variables set for IHostingStartup to work:
```ASPNETCORE_HOSTINGSTARTUPASSEMBLIES: AgentInHost
DOTNET_ADDITIONAL_DEPS: "c:\Users\Robert Uva\.dotnet\x64\additionalDeps\AgentInHost\"
```
Note that the class library assembly I'm trying to get loaded is now called `AgentInHost` (I had used a different one in my original post of this issue).

3. I also see this in the output:
```probe_config_t: probe=[C:\Users\Robert Uva\.dotnet\store\x64\netcoreapp2.0]  deps-json=[0000000000000000] deps-dir-probe=[0]
``` which seems to confirm that it is using that location for configuration probing. One of the directories in that location is `AgentInHost` . 
4.  When I manually look at the ` C:\Users\Robert Uva\.dotnet\store\x64\netcoreapp2.0\AgentInHost\1.0.0\lib\netcoreapp2.0` path, I see my `AgentInHost.dll` as expected.

Is there anything else I should be looking for in the output?

**Comment by Tratcher** [comment]
@pakrym

**Comment by bobuva** [comment]
It's location under `c:\Users\Robert Uva\.dotnet\x64\additionalDeps\AgentInHost` is `shared\Microsoft.NETCore.App\2.0.0\AgentInHost.deps.json`.

My app's `runtimeconfig.json` contains:

```
{
  "runtimeOptions": {
    "tfm": "netcoreapp2.0",
    "framework": {
      "name": "Microsoft.NETCore.App",
      "version": "2.0.0"
    },
    "configProperties": {
      "System.GC.Server": true
    }
  }
}
```

**Comment by pakrym** [comment]
Hm, looks correct, what's the contents of `AgentInHost.deps.json`?

**Comment by bobuva** [comment]
I had originally tried to get `ShiftLeft.NetCore.Agent` to be loaded using the IHostingStartup technique, but I wasn't sure if the failure was related to the my assembly's dependencies. So I built a brain-dead simple class library, `AgentInHost`, to see if that can be loaded. And it did not. So you can ignore the `ShiftLeft.NetCore.Agent` since I'm focusing now on trying to get `AgentInHost` loaded.

**Comment by Eilon** [comment]
Hi @bobuva , were you able to get this figured out?
