### ISSUE TITLE
ASP.NET Core Runtime extensions not in 2.1.0-preview2 on Azure

### ISSUE THREAD

**Issue by ssougnez** [aspnet/Home#3072]
Hi,

when 2.1.0-preview1 has been officially released, it also has been announced that it was possible to use it via the site extensions. I followed the article "https://blogs.msdn.microsoft.com/webdev/2018/02/27/asp-net-core-2-1-0-preview1-using-asp-net-core-previews-on-azure-app-service/" and it worked.

I just tried it for preview2, however, the extension "ASP.NET Core Runtime Extensions" are still in preview1 version (while "ASP.NET Core Runtime" is in preview2).

Is it normal? If so, when is "preview2" supposed to be available on Azure ?

**Comment by blowdart** [comment]
@glennc

**Comment by ssougnez** [comment]
Hi, any news on this ? I have a web site down for 3 days now, it would be nice to know if it's going to be fixed soon or if I have to revert the code until then.

Thanks

**Comment by pakrym** [comment]
Site extension was renamed to preview2, we also released x86 and x64 versions of it:
https://www.nuget.org/packages/AspNetCoreRuntime.2.1.x64/2.1.0-preview2-final
https://www.nuget.org/packages/AspNetCoreRuntime.2.1.x86/2.1.0-preview2-final
