### ISSUE TITLE
Microsoft.Web.Xdt

### ISSUE THREAD

**Issue by chucklu** [aspnet/Home#3077]
Hi team,
   I find a library on nuget https://www.nuget.org/packages/Microsoft.Web.Xdt/2.1.2
   The project site is https://xdt.codeplex.com.

> Source Code
> You can browse the source code via the web or use git to clone the source repository.
> git clone https://git01.codeplex.com/xdt

   when I try to clone it, but failed with following info:
>  fatal: unable to update url base from redirection:
>   asked for: https://git01.codeplex.com/xdt/info/refs?service=git-upload-pack
>    redirect: https://archive.codeplex.com/?p=git01

   Could you tell me the correct url?

I find a fork on github https://github.com/davidalpert/xdt. but it's not the latest version released two months ago.
 Is it possible for you to publish this project on github https://github.com/aspnet

**Comment by Tratcher** [comment]
@glennc @vijayrkn

**Comment by chucklu** [comment]
@glennc  @vijayrkn 
You can check the detail info [here ](https://github.com/CameronWills/FatAntelope/issues/6)

**Comment by chucklu** [comment]
Hi,
   @Tratcher @glennc @vijayrkn   Anyone knows something about this issue?

**Comment by vijayrkn** [comment]
@chucklu - I will take a look at the issue you mentioned and will get back.

**Comment by chucklu** [comment]
Hi @vijayrkn , any progress?
    Can you reproduce this issue reported on https://github.com/CameronWills/FatAntelope/issues/6?
    I guess when the patch file contains remove namespace, you remove it first. 
    Then   XmlNodeList siblings = TargetNode.SelectNodes(xpath);  can not find the node cause the namespace already removed.

**Comment by chucklu** [comment]
@vijayrkn  any update? 
I have found bug in AttributeTransform class
```csharp
private XmlNodeList GetAttributesFrom(XmlNode node, IList<string> arguments, bool warnIfEmpty) {
            string[] array = new string[arguments.Count];
            arguments.CopyTo(array, 0);
            string xpath = String.Concat("@", String.Join("|@", array));
            
            XmlNodeList attributes = node.SelectNodes(xpath);
            if (attributes.Count == 0 && warnIfEmpty) {
                Debug.Assert(arguments.Count == 1, "Should only call warnIfEmpty==true with one argument");
                if (arguments.Count == 1) {
                    Log.LogWarning(SR.XMLTRANSFORMATION_TransformArgumentFoundNoAttributes, arguments[0]);
                }
            }

            return attributes;
        }
```
 XmlNodeList attributes = node.SelectNodes(xpath);
The SelectNodes did not consider the node could have xmlnamespace.

**Comment by chucklu** [comment]
The node above is a target node, however when you record the log,  
The CurrentReferenceNode is a transform node
 Log.LogWarning(SR.XMLTRANSFORMATION_TransformArgumentFoundNoAttributes, arguments[0]);
```csharp
public void LogWarning(string message, params object[] messageArgs) {
            if (SupressWarnings)
            {
                // SupressWarnings downgrade the Warning to LogMessage
                LogMessage(message, messageArgs);
            }
            else
            {
                if (CurrentReferenceNode != null)
                {
                    LogWarning(CurrentReferenceNode, message, messageArgs);
                }
                else if (externalLogger != null)
                {
                    externalLogger.LogWarning(message, messageArgs);
                }
            }
        }
```

**Comment by Eilon** [comment]
Closing this issue because this is not part of ASP.NET Core.

**Comment by chucklu** [comment]
Hi @Eilon,  who I supposed to contact?

**Comment by Eilon** [comment]
@vijayrkn - what is the recommended place to report issues with XDT?

**Comment by vijayrkn** [comment]
At this point, aspnet/websdk would be the best place.

**Comment by Eilon** [comment]
Here's the full link: https://github.com/aspnet/websdk/issues
