### ISSUE TITLE
Proxy setting issue while installing K run time cmd Command

### ISSUE THREAD

**Issue by MaheshSiri** [aspnet/Home#308]
Would Any one guide me in setting proxy credentials  settings for this command? I get an error for Proxy Authentication Required. I don't know how to set system wide proxy credentials for Windows.

The command I was trying to execute:
@powershell -NoProfile -ExecutionPolicy unrestricted -Command "iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/aspnet/Home/master/kvminstall.ps1'))"

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
