### ISSUE TITLE
Xamarin Forms app is using AspNetCore.Signal.Client but it doesnot connect with AspNetCore.Signal Server 

### ISSUE THREAD

**Issue by fatihyenidunya** [aspnet/Home#3083]
I am trying to develop a project with Angular5, AspNetCore 2 and Xamarin and I need to use AspNetCore.Signalr to make a chat app ( the app isnot chat app, chat will be a modul ) so First , I downloaded **Microsoft.AspNetCore.SignalR -Version 1.0.0-preview1-final** for Signalr Server Second I downloaded **Microsoft.AspNetCore.SignalR.Client -Version 1.0.0-preview1-final** for Xamarin.Forms application to build a client app. I could connected to Signalr Server with Angular app but I couldnot connect with Xamarin Client app . I am using ngrok to access my localhost in Xamarin app and I always got **101 switching protocol**  error  however, when I use same ngrok link in Angular app there is no problem I could access to Signalr  server. Also I watched Visual Studio Output section it seems try to connect to Server because I am seeing same connectionid in Server and Client app at VS output section  anyway I am using this code to connect to server from Xamarin app
               
                              _hub = new HubConnectionBuilder()
                                          .WithUrl("http://.../getchat")                 
                                          .WithConsoleLogger(LogLevel.Debug)
                                          .Build();

                                await _hub.StartAsync();

I havenot listened any method in SignalR server because when app connect to server, I want to see accessing **OnConnectedAsync** method at my hub class

What should I do?

**Comment by Tratcher** [comment]
@BrennanConroy

**Comment by BrennanConroy** [comment]
You've already posted this issue https://github.com/aspnet/SignalR/issues/2119

**Comment by fatihyenidunya** [comment]
Sorry I thought home and signalr they are seperated
