### ISSUE TITLE
Single HttpClient instance in Proxy

### ISSUE THREAD

**Issue by jtheisen** [aspnet/Home#3084]
This is about [aspnet / Proxy](https://github.com/aspnet/Proxy), for which the issue tracker says I should post here.

The sources use a single instance of `HttpClient` for all requests, <s>which I believe is wrong because of the associated [connection starvation](https://aspnetmonsters.com/2016/08/2016-08-27-httpclientwrong/) issue. (Since 2.1 it lives in a service.)</s>

...which is problematic because of [this issue](https://github.com/dotnet/corefx/issues/11224).

**Comment by jtheisen** [comment]
@Tratcher I'm very sorry I have recalled this incorrectly: I just remembered that both approaches (singleton and multiple instances) both have series issues - but the issue with the singleton is [this one](https://github.com/dotnet/corefx/issues/11224).

I suppose Proxy should then use `HttpClientFactory` in 2.1?

**Comment by Tratcher** [comment]
Ah, yes, HttpClientFactory makes some improvements here. However, Proxy is not under active development and will not be updated or shipped for 2.1.

**Comment by jtheisen** [comment]
Oh, ok. Is it deprecated entirely?

**Comment by Tratcher** [comment]
It's a prototype that was never released, it's hard to even call it deprecated. We don't know yet if we'll come back to it.

**Comment by jtheisen** [comment]
I see. Well, there's another proxy project, seems like I should take another look at that then.

Thanks for the info. Feel free to close this then.
