### ISSUE TITLE
RequireHttpsAttribute causes ERR_TOO_MANY_REDIRECTS on Ubuntu with Apache2

### ISSUE THREAD

**Issue by robinwilson16** [aspnet/Home#3086]
Using .NET Core 2.0 if I follow the official documentation to enforce HTTPS the website fails to load with the error ERR_TOO_MANY_REDIRECTS.

Steps to reproduce:
1. Create new .NET Razor App: 
dotnet new razor -o aspnetcoreapp
2. Add the two snippits of code from documentation detailed here:
[https://docs.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-2.0](https://docs.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-2.0)
3. Deploy to Apache2 running on Ubuntu 17.10 (not tested on older versions) where conf passes connection to Kestrel server using this code:
`
ProxyPreserveHost On
ProxyPass /.well-known !
ProxyPass / http://127.0.0.1:5004/
ProxyPassReverse / http://127.0.0.1:5004/
`
If code from step 2 is removed then the website works fine over HTTP or HTTPS (but obviously does not redirect) but if this code is added the sitefails to load with ERR_TOO_MANY_REDIRECTS over either HTTP or HTTPS.

It seems the methods have changed with .NET Core 2.1 but this has not yet been released.

**Comment by robinwilson16** [comment]
Hello Tratcher
I tried adding the middleware commands before or after the redirect command but I still either get the error or the redirection to HTTPS no longer occurs.
I tried a few different variations and setting the proxy value to 127.0.0.1 but it does seem it is something like with it getting into a redirect loop but I can't work out what to do to stop it.
Let me know if there is anything else I can try.

Thanks
Robin

**Comment by Tratcher** [comment]
There isn't enough information here for us to help you. Please take this issue to stackoveflow.com and provide your full apache config and startup.cs.

**Comment by Rick-Anderson** [comment]
@robinwilson16  once you sort this out, add the instructions to https://github.com/aspnet/Docs/issues/6061

@Tratcher you can close this now.

**Comment by robinwilson16** [comment]
@Rick-Anderson I can set up a new vanilla Ubuntu/Apache2 server installed using the LAMP command without touching the conf file and still hit this error and my startup.cs file was generated fresh using dotnet new razor -o aspnetcoreapp so doesn't have anything in it except the code given to enable HTTPS which causes the issue so it just doesn't work.

The only code I have added for Apache2 is the proxying commands above to redirect the requests and I have a feeling it is here where the issue is occurring. Microsoft only supply information on getting it working with NGNIX and not Apache2 so it took some trial and error but I worked it out:
ProxyPass / http://127.0.0.1:5001/ 
ProxyPassReverse / http://127.0.0.1:5001/

Is this the way it is supposed to be done?
It works fine until I enforce HTTPS - example [https://www.rwsservices.net](https://www.rwsservices.net)

It seems to work ok on Windows but just doesn't on Apache2 (I haven't tried NGNIX).

**Comment by Tratcher** [comment]
The incomplete docs are here: https://github.com/aspnet/Docs/issues/5806

**Comment by Tratcher** [comment]
The redirect can happen after the proxy if X-Forwarded-Proto is set correctly.

**Comment by robinwilson16** [comment]
Ok thanks, so my options are to either add those 4 lines above to the Apache2 http conf making no changes to the .NET Core app so the redirection happens before the proxy or alternatively add X-Forwarded-Proto to the Apache2 http and https configs and then amend the .NET Core code as per the documentation so the redirection occurs after the proxy.

Is one approach more secure than the other or is it down to personal perference? Presumably the earlier the redirection happens the better although the proxy is just running on localhost?
Actually thinking about it the ProxyPass commands are redirecting to HTTP not HTTPS so presumably they should be HTTPS instead - i.e. https://127.0.0.1:5001 not http://127.0.0.1:5001. It seems to work either way.

Thanks
Robin
