### ISSUE TITLE
Allowing special characters in request url

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/Home#3094]
_From @joetherod on April 25, 2018 19:6_

In MVC 4.5, there are web.config params to allow special characters in the url request.

<httpRuntime targetFramework="4.5" maxUrlLength="1024" maxQueryStringLength="4096" requestPathInvalidCharacters="" relaxedUrlToFileSystemMapping="true" />

Currently, in MVC Core app that runs locally in Linux via Docker for Windows, fails on HTTP 400 when the url contains a accented character. This application was originally written in MVC 4 and was ported to MVC core. So, the request works in MVC 4 on Windows. Now it doesnt locally and when hosted in Linux via Docker.

eg Request: www.contoso.com/search/Paris%2C%20%C3%8Ele-de-France%20Region

Original string was encoded in javascript before sending request, "Paris, Île-de-France Region"

The request doenst even make it to the app or any middleware that I have.
And the application breaks the website, it doenst come up at all. It is like stuck once I request this url.

_Copied from original issue: aspnet/aspnet-docker#414_

**Comment by Tratcher** [comment]
Likely a duplicate of https://github.com/aspnet/KestrelHttpServer/issues/1144

**Comment by Tratcher** [comment]
Can you share a Fiddler or Wireshark trace to confirm?

**Comment by mchenx** [comment]
in which version will this issue get fixed? any plan?

**Comment by Eilon** [comment]
Hi. We're closing this issue as no response or updates have been provided in a timely manner and we have been unable to reproduce it. If you have more details and are encountering this issue please add a new reply and re-open the issue.
