### ISSUE TITLE
Scafolding Models with bool Type Results in Error in CreateModel

### ISSUE THREAD

**Issue by robinwilson16** [aspnet/Home#3095]
I have found if I add a bool field to a data model - i.e.:
`public class Customer`
    `{`
        `...`
        `public bool CanBeContacted { get; set; }`
        `...`
    `}`

Then generate the model:
`dotnet aspnet-codegenerator razorpage -m Customer -dc ApplicationDbContext -udl -outDir Pages\Customers --referenceScriptLibraries`

The reference is incorrectly generated as:
`<input asp-for="Customer.CanBeContacted" /> @Html.DisplayNameFor(model => model.CanBeContacted))`

When it misses out the model reference and also adds a superfluous closing bracket so it should be:
`<input asp-for="Customer.CanBeContacted" /> @Html.DisplayNameFor(model => model.Customer.CanBeContacted)`

This happens every time I try to add a bool field and run code generator so would seem to be a bug?

The fix is to add the model reference manually (the code is underlined as an error) then it works.

The same is true for the update page except the extra bracket is not also added.

**Comment by Eilon** [comment]
This issue was moved to aspnet/Scaffolding#830
