### ISSUE TITLE
FileSystem Publish sometimes it does includes "Views" folder and sometimes it doesn't

### ISSUE THREAD

**Issue by deanilvincent** [aspnet/Home#3096]
Good day,

I'm publishing some of my apps using FileSystem. These apps are written using ASP.NET Core MVC. They are some instances that the publish output does include the "Views" folder from MVC and sometimes it doesn't include. I'm wondering, is it normal?

I'd prefer the publish that doesn't include "Views" every time. Any help?

.Net Core Version: 2.0
IDE: Visual Studio 2017 Community

**Comment by Tratcher** [comment]
@mkArtakMSFT

**Comment by pranavkm** [comment]
Are the publish settings different? Precompilation, which is likely what's trimming the Views directory, does not do any work if you're publishing for a rid.

**Comment by deanilvincent** [comment]
It's default publish settings @pranavkm

**Comment by pranavkm** [comment]
Do you have a repro app that you could share?

**Comment by Eilon** [comment]
Hi. We're closing this issue as no response or updates have been provided in a timely manner and we have been unable to reproduce it. If you have more details and are encountering this issue please add a new reply and re-open the issue.
