### ISSUE TITLE
Make Microsoft.Extensions.* CLS compliant

### ISSUE THREAD

**Issue by fubar-coder** [aspnet/Home#3097]
This is a new issue, because #1716 was closed by a bot.

**Comment by Eilon** [comment]
For the reasons mentioned in https://github.com/aspnet/Home/issues/2689#issuecomment-354693946, we are not planning to make this change.

**Comment by AroglDarthu** [comment]
@Eilon I don't understand why the reasoning in the following comments appears to be ignored: 

- https://github.com/aspnet/AspNetCore/issues/2689#issuecomment-354693947
- https://github.com/aspnet/AspNetCore/issues/2689#issuecomment-354693954

The purpose is not to get the circular reasoning closed... it is to ensure code runs in all the different languages.

**Comment by hardhub** [comment]
If am writing something for VB.Net I have to mark my lib as CLS compliant.

But I cannot because used from MS libs classes are not CLS-compliant (at least it is what VS tells due to missing attribute).

And MS says - all is OK ))

Nice guys! (no)
