### ISSUE TITLE
No line numbers in Exceptions

### ISSUE THREAD

**Issue by Krangth** [aspnet/Home#3098]
I am trying to log exceptions and wrote a very simple middleware to catch all of the exceptions. I am debugging locally and the middleware works fine, but there are no line numbers in the exception which is really what I was hoping to capture. The weird part is that when the request passes through to the developer exception page the line number is displayed there. 

How can I get the line numbers in my exception handling middleware?

You can recreate this behavior in a new project.

                app.UseDeveloperExceptionPage();
                app.UseMiddleware<ExceptionLoggingMiddleware>();

    public class ExceptionLoggingMiddleware
    {
        private readonly RequestDelegate _next;

        public ExceptionLoggingMiddleware(RequestDelegate next)
        {
            _next = next;
        }

        public async Task Invoke(HttpContext context)
        {
            try
            {
                await _next.Invoke(context);
            }
            catch (Exception e)
            {
                TryLogException(context, e);
                throw;
            }
        }
    }

**Comment by khellang** [comment]
You need to parse the stack trace from the exception. Take a look at the source for Microsoft.Extensions.StackTrace.Sources. It's probably best to start with the [`ExceptionDetailsProvider`](https://github.com/aspnet/Common/blob/dev/shared/Microsoft.Extensions.StackTrace.Sources/ExceptionDetails/ExceptionDetailsProvider.cs). You can pull the package from MyGet if you want the source.

**Comment by Krangth** [comment]
I did see this, and I looked into using it or mimicking what it does, but I haven't had any success yet. It seems like I would have to include much of the AspNet.Common project in my solution. If that's what must be done then I suppose I must do it. I am just wondering why is the barrier to this information so large when it is readily available in other .net applications? If it is related to performance then I would like to have the choice to call this code for the exceptions I want to know more about.

**Comment by pranavkm** [comment]
@Krangth is this a desktop (`net4x`) targeting application.

**Comment by Krangth** [comment]
Asp.Net Core Web Application on .Net Framework 4.6.2

![Image of NewProject1](https://puu.sh/AaYbG/96cbc6c204.png)
![Image of NewProject2](https://puu.sh/AaYcW/283d53a302.png)

**Comment by pranavkm** [comment]
Desktop projects produced from templates default to producing portable pdbs which don't work super well on desktop (like you observed). Have it produce full pdbs on desktop and you should get better line mappings.
Add `<DebugType>full</DebugType>` to your csproj.
