### ISSUE TITLE
The default location for storing mdf local database files

### ISSUE THREAD

**Issue by ws4u** [aspnet/Home#3101]
In ASP.NET Core, the default location for storing mdf files is C:/users/username. But in ASP.NET, the mdf file is located in the App_Data folder under the project directory. I like this behaviour, because we can copy the entire project folder to another computer, and the project can still run. This is especially convenient when we ask students to submit their ASP.NET projects for marking. We just ask them to zip their entire project folders for submission. Then, we can then download their zip files and unzip and run. 

However, with the new location at c:/users/username, the above method of asking students to submit their projects and then marking their projects will no longer work. So I strongly suggest to restore the default location to the App_Data under the project directory. This will provide great convenience to educators in teaching ASP.NET Core. Moreover, this maintains the consistency with previous ASP.NET.  Please advise. Thanks.

**Comment by KevinGrieveDesign** [comment]
+1 for this issue. We also teach students ASP.NET Core at my organisation and require them to submit their work to a grading website with a ZIP of their website folder. This will be far easier if all files are located in the same directory for local websites. So far this has been a limiting factor in effectively and efficiently teaching the students using this method.

**Comment by natemcmaster** [comment]
The .mdf files are part of LocalDB, which is is a SQL Server feature, not ASP.NET Core specifically. The Entity Framework team may know how to change the default location SQL Server uses (cc @divega @ajcvickers), but I'm not sure such an option is easy to find.

@ws4u @KevinGrieveDesign  your scenarios actually seems like a really good candidate for using SQLite instead of SQL Server. SQLite is a serverless database provider which works on macOS, Linux, and Windows unlike SQL Server which is Windows only. SQLite databases are stored in a file, and unlike LocalDB, it's easy to control the file location of the SQLite database files. See https://docs.microsoft.com/en-us/ef/core/get-started/netcore/new-db-sqlite for samples on using SQLite.

**Comment by divega** [comment]
As far as I remember the way this worked in past versions of ASP.NET relied on connection strings with AttachDbFileName and |DataDirectory|. I can’t remember right now if |DataDirectory| is used in SqlClient for .NET Core, of if ASP.NET Core sets it.

Cc @bricelam who may remember.

Anyway, that caused a number of issues related to expectation that LocalDB would work as an embedded database, when it actually isn’t one. For example, directly deleting the files would cause errors hard to recover from.

Using a real embedded database like SQLite as @natemcmaster suggest might be a better solution for this scenarios.

PS: SQL Server isn’t for Windows-only anymore (and Nate knows it very well :smile:).

**Comment by davidfowl** [comment]
> As far as I remember the way this worked in past versions of ASP.NET relied on connection strings with AttachDbFileName and |DataDirectory|. I can’t remember right now if |DataDirectory| is used in SqlClient for .NET Core, of if ASP.NET Core sets it.

#throwback https://referencesource.microsoft.com/#System.Web/HttpRuntime.cs,346

ASP.NET Core *does not* set this.

**Comment by natemcmaster** [comment]
> PS: SQL Server isn’t for Windows-only anymore

@divega good point, I should have been clearer. **Microsoft SQL Server** runs on Linux and Windows, but **LocalDB** is a feature of SQL Server which only runs on Windows. For educators that want to teach students to use a "real" database server, Docker is a good way to run SQL Server on Linux. But for the purposes of submitting assignments with an embedded database, SQLite is seems like the most viable option here.

**Comment by ws4u** [comment]
Thanks for pointing out SQLite.

For educators, we really need convenience. Otherwise, the passion of
students will decrease.

In the current Visual Studio 2017, when we create a database, the
default is an Express LocalDB. Also, when we teach ASP.NET Identity,
it also uses an Express LocalDB by default. Do we have an easy way to
modify these default behaviour to use SQLite instead?

I actually prefer that we can have a simple way to specify that the
location of the mdf file is App_Data. Is this achievable in VS 2017?

This is really a headache when we switch to teach ASP.NET Core. Please
do help fix this problem.

-- 

---
Best regards,
Weisheng

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
