### ISSUE TITLE
AspNetCore 2.1-preview2: Identity & VS2017 - No Option to Use Active Directory

### ISSUE THREAD

**Issue by robertparis** [aspnet/Home#3107]
Please explain: Why is no option to use our existing active directory directory service?

Reference:
https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity?view=aspnetcore-2.1&tabs=visual-studio%2Caspnetcore2x

VS 2017:
![image](https://user-images.githubusercontent.com/25458098/39439070-5f1d7e1e-4c74-11e8-9510-6ccfda1cf859.png)

Microsoft Visual Studio Community 2017 Version 15.6.7
VisualStudio.15.Release/15.6.7+27428.2043
Microsoft .NET Framework Version 4.7.02053
Installed Version: Community

Microsoft Visual Studio Tools for Applications 2017   00369-60000-00001-AA213
ASP.NET and Web Tools 2017   15.0.40314.0
ASP.NET Core Razor Language Services   1.0
ASP.NET Web Frameworks and Tools 2017   5.2.51214.0

**Comment by Tratcher** [comment]
This has never been available for ASP.NET Core. You're asking for the WsFederation template from .NET's ASP.NET (System.Web).

WsFederation support was only recently ported to ASP.NET Core, so we could consider porting this template now. @blowdart
