### ISSUE TITLE
Error -13 EACCES permission denied Kestrel. Ubuntu 14.04 LTS

### ISSUE THREAD

**Issue by nicolocodev** [aspnet/Home#311]
In my ubuntu server 14 LTS (Azure VM). I've installed the KVM following the instructions at aspnet home page and I've configured the libuv... but when I run k kestrel command I got the following error:
```
nicolocodev@nicolocoubt:~/dev/tesa$ k kestrel
System.Exception: Error -13 EACCES permission denied
  at Microsoft.AspNet.Server.Kestrel.Networking.Libuv.Check (Int32 statusCode) [0x00000] in <filename unknown>:0
  at Microsoft.AspNet.Server.Kestrel.Networking.Libuv.tcp_bind (Microsoft.AspNet.Server.Kestrel.Networking.UvTcpHandle handle, Microsoft.AspNet.Server.Kestrel.Networking.sockaddr& addr, Int32 flags) [0x00000] in <filename unknown>:0
  at Microsoft.AspNet.Server.Kestrel.Networking.UvTcpHandle.Bind (System.Net.IPEndPoint endpoint) [0x00000] in <filename unknown>:0
  at Microsoft.AspNet.Server.Kestrel.Http.Listener+<>c__DisplayClass0.<StartAsync>b__1 (System.Object _) [0x00000] in <filename unknown>:0
```
If i try using ```sudo``` I get the message: ```sudo: k: command not found```

**Comment by nicolocodev** [comment]
Oh! I'm so sorry :( Was my mistake. My problem was with Azure VM's Endpoints (Public/private ports) I changed that configs and everithing works well

Again, sorry :'(

**Comment by nicolasr75** [comment]
I get the exact same error when running the HelloMvc example on normal Ubuntu 14.04 LTS, but only when I use port 80 in project.json. With port 5004 it works as expected. I'm not an expert in Linux and new to Asp.Net5. Any hint on what I'm doing wrong here?

**Comment by Tragetaschen** [comment]
A normal user is not allowed to bind sockets to TCP ports < 1024, you need more permissions than the normal user has (read: 'root'-access). The easiest and quickest solution probably is using sudo to start the process, but that's also the most frowned upon solution. The reason is that the process then has *every* access right on the system.

The cleanest solution and the one that for which Kestrel is developed is using a front-end server / load balancer on port 80 (for example nginx, or endpoints in Azure) that forwards the requests to an unprivileged Kestrel on a private port.

**Comment by nicolasr75** [comment]
Thanks for the quick reply and the great explanation!

**Comment by nicolocodev** [comment]
Yep! that was my way... defined a public port (80) and a private port for the application

Thanx @Tragetaschen for your great Explanation!

**Comment by JanSichula** [comment]
Hello,

it is possible to sudo dnx but sudo expects full path to dnx which can be obtained by running "which dnx" on Linux. It is not that I am saying that sudoing dnx is best practice from the security point of view but it is certainly possible in the way described above.

P. S. So happy that after much trial and error I was finally able to get Beta 6 bits running on Ubuntu 14 LTS on AWS.
