### ISSUE TITLE
Rate limit, quota or distributed concurrency policy middlewares

### ISSUE THREAD

**Issue by Yves57** [aspnet/Home#3118]
I think it could be interesting to have middleware(s) that support policies similar to *Apache mod_qos* or these [middlewares](https://github.com/Yves57/AspNetCoreExt-Qos).

**Comment by Eilon** [comment]
Given that it looks like you've already written such middleware, we currently have no plans to add this as built-in to ASP.NET Core. Thank you for the suggestion!
