### ISSUE TITLE
Memory growing on Ubuntu and Redhat

### ISSUE THREAD

**Issue by amigin** [aspnet/Home#3119]
We have the same issue of growing memory. On Microsoft azure Ubuntu 16.04 VM - memory consumption grows up to 8GB during the day. Same app on Windows Server 2016 - memory does not grow at all. I have both servers via load balancer. So requests hit both servers with 50% probability.

Linux version we've tried on docker and directly on VM. Same result...

https://hub.docker.com/r/lykkex/lykke-job-candleshistorywriter/tags/
-nano tags - same build copied to Nano Server Docker..

https://github.com/LykkeCity/Lykke.Job.CandlesHistoryWriter

Any additional Info - I'm very happy to provide...

**Comment by Eilon** [comment]
Hi @amigin were you able to figure this out? Are you able to run a memory profiler to see where the memory is being used?

**Comment by Eilon** [comment]
Hi. We're closing this issue as no response or updates have been provided in a timely manner and we have been unable to reproduce it. If you have more details and are encountering this issue please add a new reply and re-open the issue.
