### ISSUE TITLE
NuGet Package Sources and Target KRE

### ISSUE THREAD

**Issue by WillBaldwin** [aspnet/Home#312]
I and my team have been testing and evaluating vNext for awhile now and one issue keeps coming back to bite us over and over again: NuGet Package Sources and Target KRE.

Our Visual Studio 2015 environments now have four distinct NuGet package sources and we switch what source we need based on the project or solution we have open. Do I need nightly builds, or do I need beta1, perhaps beta 2, bleeding beta 4, nuget.org or myget.org. Consider I might have two instances of Visual Studio 2015 open at the same time and I need one package source for one and different one for the other. 

**Side Note:** There are a few blogs that say never ever enable more than a single NuGet source at a time and almost all of the samples show multiple NuGet sources selected.  A single NuGet source at a time seems to help a lot!  

Would there not be an advantage to being able to specify the NuGet source and target KRE in the project.json?

**Example:** You might have a theoretical MusicStore solution distribution on GitHub and one project requires the production NuGet source and another project demonstrating new libraries requires a different beta package source. There is no standard place to specify the required package source for the users of the distribution.

It would seem to be a big time saver for people who will in the future regularly bounce between production release NuGet sources and nightly build NuGet sources.  I acknowledge that NuGet.config can help but that isn't the whole story (thank you @Eilon for that solution).

Here is the thing... If the packages are incompatible with the selected KRE the IDE does not handle the incompatibility well i.e. the developer has very few (almost none) clues as to why Roselyn is unhappy with references. Packages are specified in the project.json, Nuget source in NuGet.config,  and the target KRE is specified in the project properties. There seems to be a disconnect between the very interdependent configuration settings and if set wrong the behavior is undesirable.

**Comment by muratg** [comment]
## Some low hanging fruit from the design meeting:

 - DNX Min version: If any of your packages in project.json depend on a particular DNX and this is not the version we're currently using, we can detect and throw on the app start
 - Nuget.config:  VS tooling can add a nuget.config to each new ASP.NET 5 project using clear.

We'll file bugs in other repos to get these going.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
