### ISSUE TITLE
After `dotnet run` I get "The system cannot open the device or file specified"

### ISSUE THREAD

**Issue by sshaginyan** [aspnet/Home#3120]
Hello,

I'm running Ubuntu 16.04.4. dotnet new console runs fine but, when running dotnet run I get his following error messages.

No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.4 LTS
Release:	16.04
Codename:	xenial

/app/sdk/2.1.105/Roslyn/Microsoft.CSharp.Core.targets(84,5): error MSB3883: Unexpected exception: [/app/myapp/myapp.csproj]
/app/sdk/2.1.105/Roslyn/Microsoft.CSharp.Core.targets(84,5): error : System.AggregateException: One or more errors occurred. (The system cannot open the device or file specified. [/app/myapp/myapp.csproj]
/app/sdk/2.1.105/Roslyn/Microsoft.CSharp.Core.targets(84,5): error : ) ---> System.IO.IOException: The system cannot open the device or file specified. [/app/myapp/myapp.csproj]
/app/sdk/2.1.105/Roslyn/Microsoft.CSharp.Core.targets(84,5): error : at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath) [/app/myapp/myapp.csproj]
/app/sdk/2.1.105/Roslyn/Microsoft.CSharp.Core.targets(84,5): error : at System.Threading.Mutex.MutexTryCodeHelper.MutexTryCode(Object userData) [/app/myapp/myapp.csproj]
/app/sdk/2.1.105/Roslyn/Microsoft.CSharp.Core.targets(84,5): error : at System.Runtime.CompilerServices.RuntimeHelpers.ExecuteCodeWithGuaranteedCleanup(TryCode code, CleanupCode backoutCode, Object userData) [/app/myapp/myapp.csproj]
/app/sdk/2.1.105/Roslyn/Microsoft.CSharp.Core.targets(84,5): error : at System.Threading.Mutex.CreateMutexWithGuaranteedCleanup(Boolean initiallyOwned, String name, Boolean& createdNew, SECURITY_ATTRIBUTES secAttrs) [/app/myapp/myapp.csproj]
/app/sdk/2.1.105/Roslyn/Microsoft.CSharp.Core.targets(84,5): error : at Microsoft.CodeAnalysis.CommandLine.BuildServerConnection.d__7.MoveNext() [/app/myapp/myapp.csproj]
/app/sdk/2.1.105/Roslyn/Microsoft.CSharp.Core.targets(84,5): error : --- End of inner exception stack trace --- [/app/myapp/myapp.csproj]
/app/sdk/2.1.105/Roslyn/Microsoft.CSharp.Core.targets(84,5): error : at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions) [/app/myapp/myapp.csproj]
/app/sdk/2.1.105/Roslyn/Microsoft.CSharp.Core.targets(84,5): error : at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken) [/app/myapp/myapp.csproj]
/app/sdk/2.1.105/Roslyn/Microsoft.CSharp.Core.targets(84,5): error : at System.Threading.Tasks.Task.Wait(CancellationToken cancellationToken) [/app/myapp/myapp.csproj]
/app/sdk/2.1.105/Roslyn/Microsoft.CSharp.Core.targets(84,5): error : at Microsoft.CodeAnalysis.BuildTasks.ManagedCompiler.ExecuteTool(String pathToTool, String responseFileCommands, String commandLineCommands) [/app/myapp/myapp.csproj]
/app/sdk/2.1.105/Roslyn/Microsoft.CSharp.Core.targets(84,5): error : ---> (Inner Exception #0) System.IO.IOException: The system cannot open the device or file specified. [/app/myapp/myapp.csproj]
/app/sdk/2.1.105/Roslyn/Microsoft.CSharp.Core.targets(84,5): error : at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath) [/app/myapp/myapp.csproj]
/app/sdk/2.1.105/Roslyn/Microsoft.CSharp.Core.targets(84,5): error : at System.Threading.Mutex.MutexTryCodeHelper.MutexTryCode(Object userData) [/app/myapp/myapp.csproj]
/app/sdk/2.1.105/Roslyn/Microsoft.CSharp.Core.targets(84,5): error : at System.Runtime.CompilerServices.RuntimeHelpers.ExecuteCodeWithGuaranteedCleanup(TryCode code, CleanupCode backoutCode, Object userData) [/app/myapp/myapp.csproj]
/app/sdk/2.1.105/Roslyn/Microsoft.CSharp.Core.targets(84,5): error : at System.Threading.Mutex.CreateMutexWithGuaranteedCleanup(Boolean initiallyOwned, String name, Boolean& createdNew, SECURITY_ATTRIBUTES secAttrs) [/app/myapp/myapp.csproj]
/app/sdk/2.1.105/Roslyn/Microsoft.CSharp.Core.targets(84,5): error : at Microsoft.CodeAnalysis.CommandLine.BuildServerConnection.d__7.MoveNext()<--- [/app/myapp/myapp.csproj]

The build failed. Please fix the build errors and run again.

**Comment by Eilon** [comment]
This issue was moved to dotnet/roslyn#28529
