### ISSUE TITLE
CORS not working with OPTIONS

### ISSUE THREAD

**Issue by titanix** [aspnet/Home#3121]
I have an ASP.NET service running on localhost:5001. It exposes a POST method on route /dict/consult that use JSON RPC.

A webpage at localhost:5000 try to access the resource at localhost:5001/dict/consult with Chrome. It fails because ```Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:5000' is therefore not allowed access.```

Manual test with curl shows that using the OPTIONS verb, no ```Access-Control-Allow-Origin``` is returned:
```
> curl -i -X OPTIONS -H "Origin: http://localhost:5000" \
-H 'Access-Control-Request-Method: POST'\
-H 'Access-Control-Request-Headers: Content-Type'\"
http://localhost:5001/dict/consult"

HTTP/1.1 204 No Content
Date: Sun, 06 May 2018 16:49:24 GMT
Server: Kestrel
```

However, when doing a POST request directly with POSTMAN the header _access-control-allow-origin_ is returned correctly. Using the browser, the Post nor the Options methods are even fired by the framework.

Code in Startup.cs is in the good order:

```
app.UseCors(builder => builder
                .AllowAnyOrigin()
                .AllowAnyHeader()
                .AllowAnyOrigin());
app.UseMvc();
```
and
```
services.AddCors();
services.AddMvc();
```

[This Stack reply](https://stackoverflow.com/a/45844400) can solve the problem in my case it seems that the ```UseCors``` infrastructure is no working as expected.

**Comment by JulijaRamoskiene** [comment]
Have you tried enabling .AllowAnyMethod () on policy? You can see better messages if you enable debug logging.

**Comment by kekedk** [comment]
@titanix 
.SetPreflightMaxAge(TimeSpan.FromMinutes(666)) // This enables automatic preflight reponses

**Comment by nixa333** [comment]
@titanix try @JulijaRamoskiene solution. In your code you specify .AllowAnyOrigin() twice.
You should have your code like this:

```
builder
    .AllowAnyOrigin()
    .AllowAnyHeader()
    .AllowAnyMethod();
...
```

**Comment by mkArtakMSFT** [comment]
Hi. We're closing this issue as there's been no response and we have been unable to reproduce it. If you have more details and are encountering this issue please add a new reply and re-open the issue.

**Comment by schneiderpat** [comment]
Hello,
I am facing the same issue.
I configured cors like that in my startup
```
app.UseCors(builder =>
    builder.AllowAnyOrigin()
          .AllowAnyMethod()
          .AllowAnyHeader()
          .AllowCredentials()
);
```

When my frontend, an angular spa, sends a put request, chrome sends a preflight with an options method. this one does not get handled by the cors middleware. 
in the end my controller gets the request and returns unauthorized.

Any suggestions?

.net sdk: 2.1.500

**Comment by pranavkm** [comment]
@schneiderpat see https://docs.microsoft.com/en-us/aspnet/core/migration/21-to-22?view=aspnetcore-2.2&tabs=visual-studio#update-cors-policy. For further discussion, please open a new issue.

**Comment by prsujoy** [comment]
CORS is working when profile is IISExpress but its not working when profile is project in asp.net core 2.2 web api. See below in red highlighted
![image](https://user-images.githubusercontent.com/12905439/55138993-b65d8700-515a-11e9-9eea-aaeb5c32f042.png)
