### ISSUE TITLE
Difference between dotnet core OK(IQueryable) and regular .NET OK(IQueryable) with EF Core SQL Server

### ISSUE THREAD

**Issue by rodofatos** [aspnet/Home#3127]
Hello,
I had this strange behavior that i cannot understand if it is related to EF Core or to how the OK() works in the Core Version of ASP.

Basically when i have an IQueryable with an issue (say Invalid column name) to return from Controller thru OK the issue is not thrown and the return in the page is blank where in the old .NET it is returning the issue as expected.
To reproduce it is enough to just run from controller where _context is a :+1: 
`var data = _context.Set<TDomain>().AsQueryable();
return Ok(data);`
where _context is a DbContext.

.NET Core SDK version is 2.1.105

Can you please help me and point toward a solution ? Ideally i would like to have the same behavior as in the old .NET and handle the errors (maybe a need a different middleware or maybe I dont define correctly the global exception handler )

Best regards,

**Comment by Tratcher** [comment]
When you use the F12 browser tools or Fiddler, what does it say the status code is?

**Comment by rodofatos** [comment]
After further investigating the difference the 2 projects I had I found that actually the Queryable was getting converted in a DelegatingHandler in order to login request/response and so after adding respective middlewares and an global exception middleware i managed to get the same behavior.

Will close the issue.
