### ISSUE TITLE
Is there any pretty errors package for k kestrel ?

### ISSUE THREAD

**Issue by molekilla** [aspnet/Home#313]
Just wondering if there is any package to make life easier for linux based developers. Or any idea how it could be parsed.

Thanks

**Comment by Eilon** [comment]
Not familiar with this - do you have an example of what you mean by "pretty errors"? Are you talking about showing user-friendly (or developer-friednly) errors for non-success HTTP status codes?

**Comment by molekilla** [comment]
Right now, the Roslyn engine throws out a lot of error or warning debug data in the console. E.g. coming from a nodejs experience, errors are more concise and you can add loggers to output to the console. I know there is the browser error page, but trying to find parallels with a Console / Shell first approach

**Comment by Eilon** [comment]
Hmm, by default I didn't think Kestrel dumped much output at all. Do you have the ConsoleLogger enabled? If so, by default the ConsoleLogger will send some color-coded output for various debug levels. You can toggle the logger's default output with various switches.

If it's something else you're seeing, can you post a screenshot or copy/paste the output you're seeing?

**Comment by molekilla** [comment]
Excuse my ignorance, how do     I enable ConsoleLogger ?

**Comment by Eilon** [comment]
With DI have your app's `Startup` class's `ConfigureServices` method take in an `ILoggerFactory`, and then call `AddConsole` on that (you'll have to import the appropriate NuGet package and namespace).

**Comment by molekilla** [comment]
Already there, so that console  is strictly web  ? or does it output to
bash shell

using System;
using Microsoft.AspNet.Builder;
using Microsoft.AspNet.Diagnostics;
// using Microsoft.AspNet.Diagnostics.Entity;
using Microsoft.AspNet.Hosting;
using Microsoft.AspNet.Http;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Routing;
using Microsoft.AspNet.Security.Cookies;
//using Microsoft.Data.Entity;
using Microsoft.Framework.ConfigurationModel;
using Microsoft.Framework.DependencyInjection;
using Microsoft.Framework.Logging;
using Microsoft.Framework.Logging.Console;
using Rutha.Models;

namespace Rutha.Mvc
{
    public class Startup
    {
        private IConfiguration Configuration { get; set; }

        public Startup()
        {
            Configuration = Rutha.Shared.ConfigManager.Create();
        }

        public void ConfigureServices(IServiceCollection services)
        {
          services.AddMvc();
          // services.AddSingleton<ITodoRepository, TodoRepository>();
          services.AddSingleton<IUserRepository, UserRepository>();
        }

        public void Configure(IApplicationBuilder app, IHostingEnvironment
env, ILoggerFactory loggerfactory)
        {
            loggerfactory.AddConsole();
            // Add the following to the request pipeline only in
development environment.
            if (string.Equals(Configuration.Get("ASPNET_ENV"),
"Development", StringComparison.OrdinalIgnoreCase))
            {
                app.UseErrorPage(ErrorPageOptions.ShowAll);
                //
app.UseDatabaseErrorPage(DatabaseErrorPageOptions.ShowAll);
            }
            else
            {
                // Add Error handling middleware which catches all
application specific errors and
                // send the request to the following path or controller
action.
                app.UseErrorHandler("/home/error");
            }

            // Add cookie-based authentication to the request pipeline.
            //app.UseIdentity();

            app.UseMvc();
            app.UseStaticFiles();
            app.UseWelcomePage();
        }
    }
}

**Comment by molekilla** [comment]
I think it works...

[nodemon] v1.3.7
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `k kestrel`
Running "watch" task
Waiting...
Missing method
Microsoft.Framework.DependencyInjection.ServiceCollectionExtensions::AddContextAccessor(IServiceCollection,IConfiguration)
in assembly
/home/vagrant/.kpm/packages/Microsoft.Framework.DependencyInjection/1.0.0-beta3/lib/aspnet50/Microsoft.Framework.DependencyInjection.dll,
referenced in assembly
/home/vagrant/.kpm/packages/Microsoft.AspNet.Mvc/6.0.0-beta2/lib/aspnet50/Microsoft.AspNet.Mvc.dll
System.MissingMethodException: Method not found:
'Microsoft.Framework.DependencyInjection.ServiceCollectionExtensions.AddContextAccessor'.
  at
Microsoft.Framework.DependencyInjection.MvcServiceCollectionExtensions.AddMvc
(IServiceCollection services, IConfiguration configuration) [0x00000] in
<filename unknown>:0
  at Rutha.Mvc.Startup.ConfigureServices (IServiceCollection services)
[0x00000] in <filename unknown>:0
  at (wrapper managed-to-native)
System.Reflection.MonoMethod:InternalInvoke
(System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags
invokeAttr, System.Reflection.Binder binder, System.Object[] parameters,
System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:0
[nodemon] app crashed - waiting for file changes before starting...


Thanks

**Comment by Eilon** [comment]
The console logger works in any scenario where there's a console. So, for example, on Windows, it doesn't work in IIS because IIS is a Windows Service, so there's no UI (not even a console). But running from the command line it'll work in any scenario (web, console, etc.).
