### ISSUE TITLE
ActionResult<int?> is returning 204 instead of 200

### ISSUE THREAD

**Issue by joshmouch** [aspnet/Home#3131]
I just upgraded to the latest preview version so that I could try out the new `ActionResult<>` class.

However, I'm finding that when I have the following code, it returns a 204 response rather than a 200 response as I would expect.  Is this expected behavior?

```
public class SomeController
   public async Task<ActionResult<int?>> GetId() {
      return null;
   }
}
```

**Comment by Tratcher** [comment]
@mkArtakMSFT

**Comment by pranavkm** [comment]
That's the NoContent formatter kicking in - https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Core/Formatters/HttpNoContentOutputFormatter.cs. It returns 204 if the content, as in your case, is `null`.

**Comment by joshmouch** [comment]
OK, I'll remove that formatter for now, as it breaks current Swashbuckle/Swagger/AutoRest generated client functionality.
