### ISSUE TITLE
ASP.net core 2.1 rc1: System error in view when exporting to a file

### ISSUE THREAD

**Issue by under3415** [aspnet/Home#3139]
When exporting a view to a file an error message appears:
System.Collections.Generic.List`1[MyApp.Models.MyModel] IEnumerable<MyModel>

See this SO article for more details: 
https://stackoverflow.com/questions/50320946/how-to-let-user-download-data-to-a-file

You can use this project to replicate the issue: 
https://github.com/under3415/ExportError/

Run the project, click download link, examine the file for above error message.

**Comment by pranavkm** [comment]
Haven't actually tried your application, but the casing for the `@model` directive is incorrect (it's case sensitive). It needs to be

* `@model IEnumerable<MyModel>`
* Also needs to appear before any code blocks (i.e. at the first line of the file)

**Comment by under3415** [comment]
Thanks. My mistake. closing this
