### ISSUE TITLE
Asp.Net Core 2.1: Issues with HTTP GET on Task<T> controller actions

### ISSUE THREAD

**Issue by HappyNomad** [aspnet/Home#3143]
I upgraded my Asp.Net Core 2.0 WebAPI project to the 2.1 release candidate, and encountered two issues that it introduces with GET controller actions that return `Task<T>`.

Client-server communication initially broke in my local debug environment.  My UWP client app's attempts to use `HttpClient.GetAsync` to GET from the WebAPI were failing with this exception:

> System.Net.Http.HttpRequestException
  HResult=0x80131620
  Message=Error while copying content to a stream.
  Source=System.Net.Http
  StackTrace:
   at System.Net.Http.HttpContent.<LoadIntoBufferAsyncCore>d__43.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
...
Inner Exception 1:
IOException: Exception from HRESULT: 0x80072EFF
Inner Exception 2:
Exception: Exception from HRESULT: 0x80072EFF

I didn't immediately realize the problem is server-side since this exception differs from what was thrown client-side in Asp.Net Core 2.0.  Things seem to be going awry server-side beyond the original exception thrown by the `Task<T>` controller action.  The server's output includes this:

> Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware:Warning: The response has already started, the error page middleware will not be executed.
Microsoft.AspNetCore.Server.Kestrel:Error: Connection id "0HLDQ5D5GTG3Q", Request id "0HLDQ5D5GTG3Q:00000001": An unhandled exception was thrown by the application.

The issue disappears if I change the controller's GET action to return `T` instead of `Task<T>`.  Not only does the unusual client-side exception disappear, but the original server-side exception disappears too!

That original server-side exception is caused by the other issue that Asp.Net Core 2.1 seems to introduce with `Task<T>` controller actions.  That is, it passes `typeof( Task<T> )` to `OutputFormatter.CanWriteType` instead of just `typeof( T )`.  This difference from Asp.Net Core 2.0 causes the wrong output formatter to be used by my GET controller action.  It's probably best to stay consistent with 2.0 and supply `OutputFormatter.CanWriteType` with the `T` type rather than `Task<T>` type.

**Comment by Tratcher** [comment]
Can you include a code sample of your MVC action?

What was the server side exception?

**Comment by pranavkm** [comment]
Likely a dup of https://github.com/aspnet/Mvc/issues/7782. We're addressing the issue in our upcoming 2.1.1 patch. There's a possible workaround provided here - https://github.com/aspnet/Mvc/issues/7782#issuecomment-389300695.

Could you include more details about what you were trying to do that resulted in this error? Doesn't seem like you're attempting to do xml serialization and I'd like to make sure we've covered all scenarios.

**Comment by WashingtonARamos** [comment]
Hello, I'd like to add to this problem since it's occuring to me too.

I have:

```
[HttpGet("[action]"), Authorize(AuthenticationSchemes = "Bearer")]
        public IActionResult List() {
            if (!IsAdmin && !IsManager) return Forbid();

            if (IsAdmin) {
                var res = _data.Users.Select(s => new { s.Id, s.Name, s.Surname, s.Username, s.Admin, s.Manager }).ToList();
                return Ok(res);
            } else {
                // [uninportant stuff]
                return Ok(res);
            }
        }
```

The model for `Manager` is:

```
namespace my.project.Models {
    public class Manager {

        public int Id { get; set; }
        public User User { get; set; }
        public int UserId { get; set; }
        public Shop Shop { get; set; }
        public int ShopId { get; set; }

    }
}
```
And the model for `User` is:

```
namespace SOSAlergia.WebAPI.Models {
    public class User {

        public int Id { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public virtual Admin Admin { get; set; }
        public virtual Manager Manager { get; set; }

    }
}
```


The method works fine, but if I happen to add Shop to the select statement, like so:

`var res = _data.Users.Select(s => new { s.Id, s.Name, s.Surname, s.Username, s.Admin, s.Manager, s.Manager.Shop }).ToList();
`

It then throws me the same error.
