### ISSUE TITLE
Asp.Net Core signalR is not working if publishing inside virtual directory

### ISSUE THREAD

**Issue by kailashp** [aspnet/Home#3144]
I have developed an application in asp.net core and used signalR. When i publish it in root directory it works fine, but if i publish it inside virtual directory it doesn't work. My signalR hub is always pointing to the root directory.

Startup.cs

```
public void Configure(IApplicationBuilder app, IHostingEnvironment env)
{
    // ... other middleware ...
    app.UseSignalR(routes =>
    {
        routes.MapHub<ChatHub>("/chat");
    });
}
```
And i have initialized it in client side like this,

chat.js

`var connection = new signalR.HubConnection("/chat");`

After publishing it inside virtual directory(/development/chatapp/source) it points like this, 
http://localhost:100/chat?userId=1

But actually it has to point like this, so that it will work,
http://localhost:100/development/chatapp/source/chat?userId=1

I have used asp.net core 2.0 and this signalR version(1.0.0-preview1-final).

Someone please suggest me to resolve this issue.

**Comment by Tratcher** [comment]
Virtual Directory or Sub Application? AspNetCore doesn't support VDirs.

**Comment by kailashp** [comment]
Hi @Tratcher,

Actually it hosted as sub application. And I have fixed it by getting the base path of my application and prepend it with the actual js initialization like below, it works !!!

`var connection = new signalR.HubConnection("/development/chatapp/source/chat");`
