### ISSUE TITLE
Asp.Net Core 2.1: SSL from UWP app

### ISSUE THREAD

**Issue by HappyNomad** [aspnet/Home#3145]
I ported my WebAPI from Asp.Net Core 2.0 to release candidate 2.1.  The default template enables SSL, but I couldn't get it working.  This exception is thrown:

> System.Net.Http.HttpRequestException
  HResult=0x80072F0D
  Message=An error occurred while sending the request.
  Source=System.Net.Http
  StackTrace:
   at System.Net.Http.HttpClientHandler.<SendAsync>d__111.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
Inner Exception 1:
COMException: The text associated with this error code could not be found.
The certificate authority is invalid or incorrect

How can I get SSL to work in my projects?  I'm new to working with SSL in .NET so hopefully it's easy to answer for someone familiar with it.

I thought the certificate stuff was handled by VS when I ran the project.  Since I keep getting the exception, I manually ran the following commands:

> Microsoft Windows [Version 10.0.17134.48]
(c) 2018 Microsoft Corporation. All rights reserved.
> 
> C:\...\WebAPI_NoAuth>dotnet install tool dotnet-dev-certs -g --version 2.1.0-rc1-final
> 
> Welcome to .NET Core!
> ---------------------
> Learn more about .NET Core: https://aka.ms/dotnet-docs
Use 'dotnet --help' to see available commands or visit: https://aka.ms/dotnet-cli-docs
> 
> Telemetry
> ---------
> The .NET Core tools collect usage data in order to help us improve your experience. The data is anonymous and doesn't include command-line arguments. The data is collected by Microsoft and shared with the community. You can opt-out of telemetry by setting the DOTNET_CLI_TELEMETRY_OPTOUT environment variable to '1' or 'true' using your favorite shell.
> 
> Read more about .NET Core CLI Tools telemetry: https://aka.ms/dotnet-cli-telemetry
> 
> ASP.NET Core
> ------------
> Successfully installed the ASP.NET Core HTTPS Development Certificate.
To trust the certificate run 'dotnet dev-certs https --trust' (Windows and macOS only). For establishing trust on other platforms please refer to the platform specific documentation.
For more information on configuring HTTPS see https://go.microsoft.com/fwlink/?linkid=848054.
No executable found matching command "dotnet-install"
> 
> C:\...\WebAPI_NoAuth>dotnet dev-certs https --trust
> Trusting the HTTPS development certificate was requested. A confirmation prompt will be displayed if the certificate was not previously trusted. Click yes on the prompt to trust the certificate.
A valid HTTPS certificate is already present.

The security warning popped up and I clicked 'yes'.  Why is the same exception still thereafter thrown?  I've tried passing `new HttpClientHandler { ClientCertificateOptions = ClientCertificateOption.Automatic }` to `HttpClient`'s constructor, but alas it's always the same exception.

**Comment by Tratcher** [comment]
@javiercn

**Comment by javiercn** [comment]
@HappyNomad Are you trying to host asp.net core inside a UWP application or do you have a UWP application that talks to an asp.net core application.

Best regards,
Javier Calvarro Nelson

**Comment by HappyNomad** [comment]
@javiercn I have a UWP application that talks to an asp.net core application.

**Comment by chekmx** [comment]
I am also encountering this issue.  any resolution found?

**Comment by javiercn** [comment]
I think this is more of a question about trusting self-signed certificates in UWP. My recommendation would be to ask about it on Windows specific channels or on a site like stackoverflow.

From what I can see taking a quick look at it, there is an HttpBaseProtocolFilter class that can be passed as an instance to the HttpClient instance in order to disable the validations

```csharp
ilter.IgnorableServerCertificateErrors.Add(
    ChainValidationResult.Untrusted |
    ChainValidationResult.InvalidName);
```

If not, try passing a custom certificate validation callback as in regular .NET with 
https://msdn.microsoft.com/en-us/library/system.net.http.httpclienthandler.servercertificatecustomvalidationcallback(v=vs.110).aspx

https://msdn.microsoft.com/en-us/library/system.net.http.httpclienthandler.dangerousacceptanyservercertificatevalidator(v=vs.110).aspx

Whatever you do, **DO NOT USE THIS CODE IN PRODUCTION** as it will invalidate any validation on the certificates.

**Comment by javiercn** [comment]
Closing this issue as there's no more action to take here.

**Comment by javiercn** [comment]
@HappyNomad Certificate pinning has nothing to do with this. To make it work in the most similar way as how it would work in production, you would need to find a way for the UWP app to trust the local HTTPS development certificate during development.

I don't have any clue on how to do this if UWP doesn't look at the trust root on the certificate store. I would suggest contacting someone on the UWP forums.

Sorry I can't be of much help.

**Comment by javiercn** [comment]
@HappyNomad Maybe we are talking different things. I understand HTTP public key pinning for certificate pinning, but I believe it has a different meaning for you/in the UWP platform. I'm no expert on UWP so maybe doing certificate pinning on UWP is a way to solve this in development.

Trusting the developer certificate during development (whatever form that takes) is the correct approach for it. Just remember that if you require custom code in your app to achieve that you don't include it in your production setup.

I would also not rely on '#DEBUG' to pivot the code but introduce a local symbol for the environment '#LOCALHOST' or '#DEVELOPMENT' and turn it on if not explicitly specified on the DEBUG configuration option. That way you can produce DEBUG and RELEASE builds that work with localhost if you need to do testing.

Hope this helps.

**Comment by HappyNomad** [comment]
@javiercn Thanks for you help.

Regarding certificate pinning, my nascent understanding leads me to believe it's achievable in UWP using [this feature](https://docs.microsoft.com/en-us/previous-versions/windows/apps/hh465002(v%3dwin.10)).  According to [this](https://docs.microsoft.com/en-us/windows/uwp/security/certificates), a UWP app container can have its own certificate store.  According to [this](https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-trustflags), the certificate therein can be trusted to the exclusion of the system store.

I got my UWP app to trust the developer certificate by means of `certlm`.  The solution didn't require extra code.  In the local machine's certificate store, I copied the `localhost` certificate from `Personal` and pasted it into `Trusted Root Certification Authorities`.  The same certificate was already in the user certificate store's `Trusted Root Certification Authorities`, but a UWP app can't access there.

The certificate I needed to copy over, that my Asp.Net Core web API uses, was "IIS Express Development Certificate" rather than "ASP.NET Core HTTPS development certificate".  The latter was already in the user's MY store so for others reading this thread, according to [this](https://docs.microsoft.com/en-us/windows/uwp/security/certificates), if that's the one your web API uses then you can specify "the sharedUserCertificates capability in the manifest" to grant "an app container read access to the certificates and keys contained in the user MY store".

**Comment by rafsanulhasan** [comment]
@HappyNomad you solution is probably the best among others

**Comment by mchasemd** [comment]
.Agreed. Had to copy the certificate from Personal  to Trusted Root Certification Authorities using mmc's Copy/Paste.  That was lots of hours to find this gem.
