### ISSUE TITLE
ASP.NET CORE 2.0 FileSystem Watch callback has no information about what caused the event

### ISSUE THREAD

**Issue by RPaetau** [aspnet/Home#3146]
Hello ASP.NET CORE team (: 
Im pretty new to creating Github issues, so i hope you will be patient with any formatting errors and customs i might break. 

I am trying to make a system that can watch my user folder and all subdirectories and their files, so i can know when a file / directory changes and can act accordingly by adding/removing/renaming my in memory representation of the file structure.

However, i have an issue where all my watch events on all the folders fire at once(but only the first time), and i have no way of seeing what caused it. 

Wouldent it be better if the callback function also had a parameter with the file info and an enum telling what is different about it?

**Comment by Eilon** [comment]
Hi @RPaetau , I recommend using the FileSystemWatcher class to get more detailed information in callbacks: https://docs.microsoft.com/en-us/dotnet/api/system.io.filesystemwatcher?view=netstandard-2.0
