### ISSUE TITLE
SetCookieHeaderValue fails with dashes on expires attribute

### ISSUE THREAD

**Issue by epignosisx** [aspnet/Home#3148]
SetCookieHeaderValue fails with dashes on the **expires** date:

```cs
SetCookieHeaderValue.Parse("SomeCookie=; domain=example.com; expires=Mon, 14-May-2018 19:05:34 GMT; path=/");
```

Stacktrace:
```
System.FormatException: The header contains invalid values at index 0: 'SomeCookie=; domain=example.com; expires=Mon, 14-May-2018 19:05:34 GMT; path=/'
   at Microsoft.Net.Http.Headers.HttpHeaderParser`1.ParseValue(StringSegment value, Int32& index)
   at Microsoft.Net.Http.Headers.SetCookieHeaderValue.Parse(StringSegment input)
   at SampleApp.Program.Main(String[] args) in C:\Projects\SampleApp\Program.cs:line 24
```

csproj:
```xml
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.8" />
  </ItemGroup>

</Project>

```

**Comment by Tratcher** [comment]
Where did you get that value from? 

That format looks like it should be handled by https://github.com/aspnet/HttpAbstractions/blob/a06355a7137df34f3d6403707ee4cbdd4b2b8690/src/Microsoft.Net.Http.Headers/HttpRuleParser.cs#L29

**Comment by Tratcher** [comment]
This looks like it's fixed in 2.1.0-preview1
https://github.com/aspnet/HttpAbstractions/commit/b41d8656d5c6c522f9966793214b67753b24331a

**Comment by epignosisx** [comment]
> Where did you get that value from?

The Set-Cookie header is coming from an ASP.NET MVC app (not ASP.NET Core).

> That format looks like it should be handled by https://github.com/aspnet/HttpAbstractions/blob/a06355a7137df34f3d6403707ee4cbdd4b2b8690/src/Microsoft.Net.Http.Headers/HttpRuleParser.cs#L29

Yup, I agree. I tried passing the date string to the DateTimeOffset.ParseExact using the same params used here and it worked:
https://github.com/aspnet/HttpAbstractions/blob/a06355a7137df34f3d6403707ee4cbdd4b2b8690/src/Microsoft.Net.Http.Headers/HttpRuleParser.cs#L242

Unfortunately I couldn't get SourceLink to work so I couldn't debug into the ASP.NET Core code.

**Comment by Tratcher** [comment]
Give it a try in 2.1 and let us know if it works for you.

**Comment by epignosisx** [comment]
It works!
