### ISSUE TITLE
KVM fails to install KRE-Mono due to casing issues

### ISSUE THREAD

**Issue by colemickens** [aspnet/Home#315]
```shell
root@faee6d10d905:/# kvm install latest
Determining latest version
Latest version is 1.0.0-beta4-11037
Downloading KRE-Mono.1.0.0-beta4-11037 from https://www.myget.org/F/aspnetvnext/api/v2
KRE-Mono.1.0.0-beta4-11037 was not found in repository https://www.myget.org/F/aspnetvnext/api/v2
```

It attempts to download a package named "KRE-Mono", when in fact, the beta4 packages being uploaded to myget are named "kre-mono".

You can patch kvm.sh to fix the casing, but that doesn't seem like the proper fix.

Additionally, due to the packages available currently from the myget feed, and this bug, Linux users are currently forced to use the published versions on NuGet (limited to beta1, beta2). I can not get anything working currently whilst pointed at the aspnetvnext myget feed.

**Comment by suhasj** [comment]
@colemickens Did you update the kvm.sh from the home repo ? We made significant changes to it in the last couple of weeks

**Comment by colemickens** [comment]
This is the exact Dockerfile I'm using:
https://raw.githubusercontent.com/colemickens/polykube/46acde69ce3f161bcded17278705ebb2dd16de20/Dockerfile-aspnetbase

Which is using kvm.sh from `master`, and tries to get `latest` of KRE.

`docker build -f Dockerfile-aspnetbase`
```shell
Step 8 : RUN curl -sSL https://raw.githubusercontent.com/aspnet/Home/$KVM_TAG/kvminstall.sh | sh
 ---> Running in fa73291696d9
Downloading kvm as script to '/opt/kre/kvm'

Appending source string to /root/.bashrc
Type 'source /opt/kre/kvm/kvm.sh' to start using kvm
 ---> ce23635ab506
Removing intermediate container fa73291696d9

Step 9 : RUN bash -c "source $KRE_USER_HOME/kvm/kvm.sh     && kvm install $KRE_VERSION -a default     && kvm alias default | xargs -i ln -s $KRE_USER_HOME/packages/{} $KRE_USER_HOME/packages/default"
 ---> Running in 589f9610e44e
Determining latest version
Latest version is 1.0.0-beta4-11037
Downloading KRE-Mono.1.0.0-beta4-11037 from https://www.myget.org/F/aspnetvnext/api/v2
KRE-Mono.1.0.0-beta4-11037 was not found in repository https://www.myget.org/F/aspnetvnext/api/v2
INFO[0084] The command [/bin/sh -c bash -c "source $KRE_USER_HOME/kvm/kvm.sh     && kvm install $KRE_VERSION -a default     && kvm alias default | xargs -i ln -s $KRE_USER_HOME/packages/{} $KRE_USER_HOME/packages/default"] returned a non-zero code: 1 
Makefile:78: recipe for target 'docker-aspnetbase' failed
```

**Comment by colemickens** [comment]
Ping, can someone tell me where the nuspec files are for the packages in question? I want to take a crack at fixing this so I can track 'dev' from Linux.

**Comment by anurse** [comment]
The 'v1.0.0-beta3' tag and the 'master' branch on aspnet/Home should have the updated kvm.sh, which should be set up to use lower-cased package names. Let us know if you still have issues.

**Comment by colemickens** [comment]
LGTM
