### ISSUE TITLE
File Provider - deprecate PhysicalPath

### ISSUE THREAD

**Issue by dazinator** [aspnet/Home#3150]
The IFileProvider / IFileInfo abstraction seems broken:

Look at this: https://github.com/aspnet/FileSystem/blob/dev/src/FS.Embedded/EmbeddedResourceFileInfo.cs#L65

PhysicalPath seems only relevant for the `PhysicalFileProvider`.
Also why is it necessary to leak the physical path? Why not keep it encapsulated. 

Please consider deprecating this property - it's causing confusion: https://github.com/dazinator/Dazinator.AspNet.Extensions.FileProviders/issues/30

**Comment by dazinator** [comment]
At that location, could check if FileInfo derives from IPhysicalFileInfo, and move the PhysicalPath property to there.

**Comment by Tratcher** [comment]
It's a breaking change to remove it, so it won't happen any time soon. The benefit is pretty minimal too, it has a defined behavior of returning null if no physical path is available.

**Comment by dazinator** [comment]
Ok, closing
