### ISSUE TITLE
Antiforgery not found on Ubuntu 18.04 TLS

### ISSUE THREAD

**Issue by Memnarch** [aspnet/Home#3152]
Just stumbled uppon this issue, that it won't find Antiforgery. I published a selfcontained app for Ubuntu(Windows works fine).
using this cli:
`dotnet publish -c Release -r ubuntu.14.04-x64`
or
`dotnet publish -c Release -r ubuntu-x64`
grafik
![grafik](https://user-images.githubusercontent.com/1398184/40144395-c3997d4c-595e-11e8-9ace-3b76251a15ed.png)

And i don't understand why it tries to look in `/lib/*`
All files seem to be in the publish subfolder. As of now i even tried installing the sdk on my Ubuntu using
`sudo apt-get install dotnet-sdk-2.1.200`
Installation went fine. But still no success :/

This is how my project looks like:
```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
	<PublishWithAspNetCoreTargetManifest>false</PublishWithAspNetCoreTargetManifest>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <PlatformTarget>AnyCPU</PlatformTarget>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Properties\PublishProfiles\FolderProfile1.pubxml" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore" Version="2.0.3" />
    <PackageReference Include="Microsoft.AspNetCore.Antiforgery" Version="2.0.3" />
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics" Version="2.0.3" />
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.Abstractions" Version="2.0.3" />
    <PackageReference Include="Microsoft.AspNetCore.Hosting" Version="2.0.3" />
    <PackageReference Include="Microsoft.AspNetCore.Hosting.Abstractions" Version="2.0.3" />
    <PackageReference Include="Microsoft.AspNetCore.Hosting.Server.Abstractions" Version="2.0.3" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.0.3" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.0.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="2.0.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="2.0.3" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="2.0.4" />
  </ItemGroup>

  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="2.0.2" />
  </ItemGroup>

</Project>


```

**Comment by Memnarch** [comment]
Currently i want to disappear in pure darkness and shame. All along this was an absolute terrible mistake made by me. When publishing for i.e. linux-x64, it places the binaries and a publish folder. I missunderstodd that and thought i need to run the binaries above publish. But those are only the ones builds not packaged! The packaged ones are in the publish folder. Really sorry for adding to the issue counter -.-

**Comment by pranavkm** [comment]
Always happy to close an issue without having to do any work 👍
