### ISSUE TITLE
Razor Pages do not have simple build-in ajax partial pages, it is enough to do not switch to Razor Pages

### ISSUE THREAD

**Issue by TadeuszSobol** [aspnet/Home#3154]
Razor Pages do not have simple build-in ajax partial pages reload, it is enough to do not switch to Razor Pages

**Comment by pranavkm** [comment]
cc @mkArtakMSFT

**Comment by psijkof** [comment]
What is the status of Microsoft.jQuery.Unobtrusive.Ajax? Any guidance here, as we're not all switching to React/Angular/Vue etc. :)

**Comment by pranavkm** [comment]
I recently added a sample here - https://github.com/aspnet/Entropy/commit/fb40862a3b48545948bbb2f3ef787f44b57345e0 - showing partial page updates using Razor Pages and Unobtrusive.Ajax. One of the missing pieces to remove some of the boiler plate is to add a first class `Partial` action result helper to Razor Page \ Page Model - https://github.com/aspnet/Mvc/issues/7885. We'd be happy to consider a PR for this.
