### ISSUE TITLE
.Net Core 2.1 Angular SPA + Service Worker?

### ISSUE THREAD

**Issue by Ro3A** [aspnet/Home#3155]
What is the correct implementation for using service workers in a .Net Core 2.1 Angular SPA?

I'm hung up on not being able to successfully run ng build --prod and thus only able to run the site in development mode. 

My question is, should I be following documentation on adding service worker to an Angular App, or should I be using the WebEssentials extension by Mads Kristensen? 

https://github.com/madskristensen/WebEssentials.AspNetCore.ServiceWorker

**Comment by dasMulli** [comment]
You should be able to follow the Angular documentation if your Angular app is already running.
When you run & debug, you'll need to remove the part of the Startup code that launches the Angular CLI as a development server.
At least that's how I have been able to make it work a few weeks ago..

**Comment by Ro3A** [comment]
@dasMulli Thanks for the direction - that was at least part of what I needed. I hadn't made the connection between running ng build --prod and also changing environment name in the app properties to Production. 

I've not yet had a chance to try implementing service worker. Should be able to try tomorrow
