### ISSUE TITLE
Either update xplat Getting started guide or remove it entirely

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/Home#3157]
[This](https://github.com/aspnet/Home/wiki/Getting-Started-Prerequisites-for-Debian,-Ubuntu-and-derivitives) getting started guide for Ubuntu style linux distros is VERY out of date. We should either update it to match the new world or remove it entirely.

**Comment by Eilon** [comment]
I updated that wiki page to delete all the content and just link to other docs.
