### ISSUE TITLE
AuthorizationContext Filter - HttpContext.Request.IsAjaxRequest() Returning True when X-Requested-With POSTed as Form Parameter

### ISSUE THREAD

**Issue by own3mall** [aspnet/Home#3158]
In one of my ASP.NET MVC projects, I am using an authorization filter which is applied to all controllers.  The filter checks to see if a request has been made with AJAX.  If the request is not an AJAX request, we check the normal anti-CSRF token if the request method is POST.  If the request is an AJAX request, we check the ORIGIN header to authorize whether or not our application should complete the request.

It is easy to trick ASP.NET into thinking that a request is an AJAX request when it's not.  From my custom filter, HttpContext.Request.IsAjaxRequest() returns true if the form data contains the X-Requested-With parameter.

For example, the following posted form will return true for HttpContext.Request.IsAjaxRequest() when the X-Requested-With header is missing from the HttpContext.Request.Headers (because it was submitted using a POST form request, not an AJAX POST request):

```
<form method="post" action="/Home/Index">
    <input type="hidden" name="X&#45;Requested&#45;With" value="XMLHttpRequest">
    <input type="submit">
</form>
```

When the above form is submitted, HttpContext.Request.IsAjaxRequest() should return false because the HttpContext.Request.Headers["X-Requested-With"] header is null and wasn't supplied by the browser.  However, it currently returns true because it found X-Requested-With in the posted data which is incorrect.

**Comment by pranavkm** [comment]
@mkArtakMSFT this goes to https://github.com/aspnet/AspNetWebStack. That said `IsAjaxRequest` has always looked at things other than the header, going back all the way to Mvc 1.0, so it's be very unlikely this would change now.
