### ISSUE TITLE
Generalization of the ModelState error messages

### ISSUE THREAD

**Issue by TheAifam5** [aspnet/Home#3159]
Hey everyone,
I am making a school project where I want to use localization in the SPA project, not in API.
For this project I am using dotnet core 2.0.

The problem what I actually have is, how to generalize error messages like:
 - for invalid input returns 'invalid_input'
 - for missing data returns 'required'

Example JSON:
```
{
  'login': 'required',
  'password': 'too_short'
}
```

Regards,
TheAifam5

**Comment by pranavkm** [comment]
@dougbu \ @kichalla any suggestons on how you could do this?

**Comment by dougbu** [comment]
With ASP.NET Core 2.0, the weapon of choice would be `DefaultModelBindingMessageProvider`. Use methods such as `SetValueIsInvalidAccessor(...)` to set the MVC-generated error messages to whatever you want. Can make those changes generally using `MvcOptions.ModelBindingMessageProvider` or can implement `IBindingMetadataProvider` (and use `BindingMetadata.ModelBindingMessageProvider`) to make changes on a per-metadata basis.

**Comment by TheAifam5** [comment]
Thank you. That's kind a useful information for me. I'm gonna check this out today.

**Comment by pranavkm** [comment]
@TheAifam5 feel free to reopen this issue if you have further questions.
