### ISSUE TITLE
Horrible Branding - Don't Call it ASP.NET 5 MVC 6

### ISSUE THREAD

**Issue by flashtopia** [aspnet/Home#316]
First we had ASP classic, then asp.net which soon became web forms.  After that came MVC and Web Pages.  Web pages had the dumbest branding of all, try searching for ASP.net Web Pages and you will know what I mean.  Impossible to find any resources with the exception of W3schools and mikesdot netting.  Web Pages should have been callled "Razor Pages" or something less vauge.

Now we have ASP.net 5 (VNext) running MVC 6? WTF?
Can you imagine how difficult it will be a new comer from Python, JS or Ruby stack to even understand the hornets nest Microsoft Has Created.

Please take this opportunity to re-brand the whole MS Server side stack since we this is a as big of a change as going from ASP classic (vbscript /jscript) to ASP.net.  I cannot tell you how many developers I run into (who are not on the microsft stack who cant get their heads around ASP because of the mess microsoft has made with their branding.

Something like this would be optimal. 

- ASP Classic (3.0 Pages Retired)
- ASP.NET  (WebPages, Webforms, MVC - Soon to be retired)
- Microsoft Blaze (Better name than ASP.net 5)
   - Blaze MVC ( what you now call MVC 6)
   - Blaze Razor Pages (Web Pages 4)
   - Blaze Services (Web API)
   - Blaze RichClient Templates ( SPA templates Knockout, Angular, whatever)
   - Blaze Live (SignalR / WebSockets)
   - Blaze Streaming (IIS Media Services)

It would also be killer if Microsoft Finally started created Roadmaps to go from current language to new .net Stack.   For Example.

Going from ASP Classic > ASP.NET 6 (what I called blaze above)
Going from PHP > ....
Going from ColdFusion > ....
Going from JSP to >
Going from Rails >
Going from DJango >

Microsoft has the better stack.  Azure rocks specially with the awesome BizSpark deal.  IIS runs almost anything.  Visual Studio is technically free if you are not a 1m company.  Yet MSFT gets a horrible reputation with developers because of complexity.   Im sick of seeing Ruby, Python, Php developers on their MacBooks thinking MSFT stack is too complex, too weak, too top heavy, and too confusing to get started with. 

Please Rebrand. 
Or hire someone from Apple who understands branding more than anything else to help you guys out.

**Comment by emersonsoares** [comment]
Although not like the suggestion "Blaze", I agree with @flashtopia. With so many changes in the stack, imagine the difficulty in researching solutions on the internet. Things will blend between the new version and old version with similar names.

**Comment by andrebaltieri** [comment]
I think we have 2 things here... one is ASP.NET 5 (The core), other is the MVC implementation that ASP.NET does, which is called MVC 6 (Version 6).

I do not agree to call everything as ASP.NET MVC, IMHO I liked to use WebAPI name.
Call it "Blaze"? No! We have a history behind ASP.NET name, can't simply change it now. And where does this "Blaze" came from?

**Comment by edrohler** [comment]
I think what you are looking for is :

http://www.microsoftvirtualacademy.com/training-courses/what-s-new-with-asp-net-5
http://www.tugberkugurlu.com/archive/exciting-things-about-asp-net-vnext-series-the-ultimate-guide
http://forums.asp.net/1255.aspx/1?ASP+NET+vNext

There is plenty of information regarding the latest ASP.NET stack. But it should be noted that your post reads, ASP.NET 6 MVC 5, which the version numbers are backwards. Technically, and what you'll find once you dig deeper into the latest information on ASP.NET is that, ASP.NET 5 includes (or will include) everything from front to back and reverse of the web stack.. HTH

**Comment by yanjustino** [comment]
I prefer the name "katana". Furthermore, this justifies 'k' command

**Comment by flashtopia** [comment]
@yanjustino Katana sounds even better.  Blaze was just a stupid name I came up with off the top of my head.  My point was that the whole thing needs a re-brand.   MSFT made a dumb mistake by branding ASP.NET Web Pages, which if you google search for you will have a very difficult time finding material on ASP.NET web Pages versus how to create pages with ASP.NET. 

With the version numbers getting confusing as @andrebaltieri pointed out, naming it something like:
- Microsoft Katana
- Katana MVC v6
- Katana API (web api)
- Katana Razor Pages (web pages)
- .... 

Would make so much sense. 
I spent around an hour looking on Amazon.com for ASP.NET books for the new Stack.  I found ASP.NET 5 books which dont cover MVC6.   Its just too confusing, specially with the version numbers being all over the place.   I am sure someone here, or someone at MSFT could come up with a much better job at branding these things. 

Couple that with Migration Paths for existing developers:
ASP.NET MVC 4 --->  KATANA MVC 6
RubyRails ----> KATANA MVC 6
ASP 3.0 ---->  KATANA Razor Pages
Php ------> Katana Razor Pages
and so on and MSFT could really convert some developers over to the MSFT Stack.

**Comment by villanus** [comment]
Watching this issue from my 2nd account.

**Comment by andrebaltieri** [comment]
Guys. katana is a codename. It was being used since they introduced Owin.
The "K" command is also changing to "dotnetsdk"

Thanks

**Comment by EduardoPires** [comment]
I agree with the confusion, we have a many versions but they have a long history. I can't call this things from another name, the numbers are sequential, You'll need keep it in mind.

I don't think is so hard to search ASP.NET 5, MVC 6 (now we have MVC, WebAPI and WebPages) in a single framework called MVC 6 (that is awesome). I think it is sufficient, we need exercise the new names. That's the way.

**Comment by villanus** [comment]
@EduardoPires .  Maybe if MSFT would have called it just MVC 6 instead of ASP.net 5, MVC 6 we would be okay.  Still that would not be smart branding since as you stated MVC 6 is not only MVC but also Web API / WebPages and MVC.

I try to look at this from a new comer perspective.
If you are searching for books on amazon for ASP.NET 5, the results are going to give you MVC 5 books.  You have to spend too much time researching what your options are before starting learning.  

To put it simply. IT SUCKS!

**Comment by EduardoPires** [comment]
Giving the name MVC 6 to entire ASP.NET is a mistake, ASP.NET is much more than MVC 6... Despite the confusion that can happen I still think this set of names is the better choice.

**Comment by Bartmax** [comment]
I think it's pretty simple, but maybe I'm mistaken (?)

1. .NET
    1. ASP.NET 5
        1. MVC
        2. WebApi
        3. WebForms
        4. EF
        5. SignalR
    2. WPF
    3. etc...

**Comment by villanus** [comment]
@Bartmax   ASP.NET 5 is not regular dot net anymore, so its not correct to put WPF under it.  It can run on .NET, or it can run without it (al a carte).    Also i dont think web forms are supported.  



In the old days, when I was learning Classic ASP 3, you had a clear understanding of Microsoft technologies and a learning path.  Now its a spiders nest at best.  the ASP.net website is a good resource, but the branding is HORRIBLE.

My Suggestion was something like this:

Microsoft KATANA 1.0
    Katana MVC 1 (just start with 1 instead of 6)
    Katana Web Pages 1
    Katana WEB API 1
  
Each of the above could have templates to get you started:
   Katana MVC 1
        - Template: SPA - Angular
        - Template: SPA - Knockout breeze
        - Template: SPA - Some other JS framework
    Katana Web API 1
       - Template: Entity Framework API

I dont care what they call it.  Just start with a new brand name.  And from now on lets just keep the version numbers in sync.  So if we go to Katana 2 everything gets upgraded to 2 also.  Some can be major changes, some minor.    Just makes things so much smoother from a manager perspective.

I also suggested that once microsoft makes the branding approachable that they invest a few thousand dollars hiring experts to write guides on migrating languages. 

PHP > Katana Web Pages 1
Cake PHP > Katana MVC 1
Cold Fusion > Katana Web Pages 1
Ruby on Rails > Katana MVC 1
JSP >>
DJANGO >>

and finally
AWS >> AZURE

Microsoft gets a bad reputation of being a money hungry business, but I dont see others giving out BizSpark memberships.   Its time microsoft demanded market share from inferior products with have at best SublimeText as their only tooling.  I am sure with the right branding, tactics, training and so on MSFT could get a strong majority of PHP developers to jump ship and get on the MSFT train. 

We deserve better

**Comment by Bartmax** [comment]
@villanus ASP.NET != .NET

**Comment by villanus** [comment]
@bartmax exactly.  Now more than ever since ASP.NET doesnt require the full .net framework.  Thus is why the naming is stupid, and the version numbers dont make sense.

**Comment by vanluke** [comment]
K is sucks! Now you will spend many many more time to deploy, build your asp application. Furthermore it currently not working. Generally Gents from ms in vs 2015 ctp 6 fails with this release. So many things now not woking there...

**Comment by villanus** [comment]
@vanluke its still in beta.   The one thing I love about the idea of the new Katana stack is the ability to ditch IIS and build self hosted applications.   This opens up a world of opportunities where you could build applications which include their own Web Server, and then wrap CEF or Webkit and you have your own desktop applicaiton written in ASP, HTML and JS.  That is cool!

**Comment by maxtoroq** [comment]
The naming is confusing even to experienced ASP.NET developers:
http://stackoverflow.com/questions/29829333/asp-net-5-name-confusion

**Comment by villanus** [comment]
its never too late to rebrand

**Comment by Eilon** [comment]
Hi everyone, we appreciate the feedback and understand there are cases with confusion, but we have no plans to change the branding. Remember that if we completely change the branding to something entirely different, that will also cause a lot of confusion.

@coolcsh @DamianEdwards @shanselman

**Comment by iamsoorya** [comment]
I totally agree that these version numbers are really confusing. The ASP.NET Identity version 2.x, 3.0 and so on.. I think the confusion is not only for new comers and even for developers. I was developing enterprise application since last 3 years. I am using VS2010 and ASP.NET MVC 4. Things have changed so much now like it is confusing a lot.

**Comment by JimiC** [comment]
Why am I under the impression that ASP.NET 5 has already an underlying brand? DNX!?

**Comment by jimior2** [comment]
be come more confusion.

**Comment by villanus** [comment]
as usual apple ears msfts lunch because they understand branding.
asp.net mvc 6 would have been the perfect point to rebrand
could have called it asp.next and that would have worked.

and then could have suffixed it based on the framework it runs on.

lastly all this gulp, bower, docker, nonsense is a real step backwards.

**Comment by rdefreitas** [comment]
how is gulp, grunt, bower, npm, etc. a step backwards? Finally asp.net developers are using many of the tools that have become standard throughout the rest of the web industry.

**Comment by simonmurdock** [comment]
Microsoft didn't call them that. That's just what they're called.

**Comment by jimior2** [comment]
Have a question here, ASP.NET 5 will contain MVC 6, Razor, Web Forms and Single Page Application?

![image](https://cloud.githubusercontent.com/assets/654999/11432467/07120256-94ea-11e5-9fc4-d5c8b49da455.png)

**Comment by davidfowl** [comment]
ASP.NET 5 will not contain WebForms. I'm not sure if we're making a single page application template right now /cc @DamianEdwards @SteveSandersonMS

**Comment by Eilon** [comment]
@SteveSandersonMS is working on some of the future of SPA. You can see some of the prototype work here: https://github.com/aspnet/NodeServices

**Comment by villanus** [comment]
@rdefreitas  Just because everyone is using them doesnt make it a smart move.   
Docker = Extra overhead.  Great if you are a cloud hosting provider, not much benefit outside of it.  Google Docker sucks and you will find a nice site dedicated to showing you how wasteful docker is.

Bower = JUNK!   Equivilent of doing a git pull with a shell script.  Worst part about bower is it uses github repos.  Meaning you are depending on the managers of the GitHub repo.   It sounds great, but having the latest / greatest of a library is not always the best practice. 

Grunt / Gulp - These are usually going to be run for tasks such as bundling and minification.  Didnt we have this with the Bundling and Minification framework which was FAR MORE ELEGANT!   They should have built on that with official SASS, LESS and JSX support.   Bundling Server Side has huge advantages.   Just deploy your project, and let it bundle on first use.  

Also, for this Compile on refresh.  YAY!  Too bad we have had that already.  Just need to code on an IIS directly and it will compile on first run (meaning dont use the Visual Studio Web server). 

The only positive development of VNEXT is that MVC, Web Pages, and Web API all run under a single unified system.  The rest about the multiple .Net frameworks and coding on a mac sounds like a waste of time.

**Comment by villanus** [comment]
WHen is the ETA on Web Pages?
For those of us who work on Single Man Teams / Small Teams MVC is just too much structure.   
I cannot believe Web Pages (Razor) has already become a step child.  

If Microsoft really wants to sell ASP.net they need to support Web Pages heavily and also have the option to use Server Side Javascript (without node) and Python as official languages of ASP.net.   C# has a huge learning curve.     Also throw PHP syntax in the bag too!  That would be great to have PHP running through Native ASP.net without the need for ISAPI.

**Comment by villanus** [comment]
VICTORY!!!!!!!
You guys rock.  Thanks for renaming.
.NET CORE !!!!!!!!!!!

sounds so lean and sexy!

**Comment by EduardoPires** [comment]
So now its time to think about logo / branding. The ASP.NET need some logo.

**Comment by joelercoaster** [comment]
I would be happy with being able to develop the ASP.NET 5 WebAPI and have it run on IIS 10 without spending half a day searching workarounds... Jesus!!!

**Comment by MaximRouiller** [comment]
@joelercoaster If you are using ASP.NET 5/Core, you are currently living on the bleeding edge. That's what betas,RCs are for. Yes you can use them in production but it's still a moving target.
