### ISSUE TITLE
[Dependency Injection] Constraints about constructor injection?

### ISSUE THREAD

**Issue by yhvicey** [aspnet/Home#3160]
From [the doc](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-2.0#constructor-injection-behavior) it says:

> Constructor injection requires that only one applicable constructor exist. Constructor overloads are supported, but only one overload can exist whose arguments can all be fulfilled by dependency injection. If more than one exists, your app will throw an `InvalidOperationException`

I wrote a class like this:

```csharp
class Entity : IEntity
{
    ...
    public Entity() { }
    public Entity(IService service) { this.service = service; }
    private readonly IService service;
    ...
}
```

And register it like this:

```csharp
...
var factory = new DefaultServiceProviderFactory();
var builder1 = factory.CreateBuilder(new ServiceCollection());
var builder2 = factory.CreateBuilder(new ServiceCollection());

builder1.AddTransient<IEntity, Entity>();
var provider1 = builder1.BuildServiceProvider();

builder2.AddTransient<IEntity, Entity>();
builder2.AddTransient<IService, Service>();
var provider2 = builder2.BuildServiceProvider();

var entity1 = provider1.GetService<IEntity>();
var entity2 = provider2.GetService<IEntity>();
...
```

But there is no exception. So is the constraint still exist?

**Comment by yhvicey** [comment]
@khellang In fact I did another test and there is still no error:

```csharp
class Entity : IEntity
{
    ...
    public Entity() { }
    public Entity(IService service) { this.service = service; }
    public Entity(IService service, IService1 service1) { this.service = service; this.service1 = service1; }
    private readonly IService service;
    private readonly IService1 service1;
    ...
}
```

```csharp
...
var factory = new DefaultServiceProviderFactory();
var builder1 = factory.CreateBuilder(new ServiceCollection());
var builder2 = factory.CreateBuilder(new ServiceCollection());
var builder3 = factory.CreateBuilder(new ServiceCollection());

builder1.AddTransient<IEntity, Entity>();
var provider1 = builder1.BuildServiceProvider();

builder2.AddTransient<IEntity, Entity>();
builder2.AddTransient<IService, Service>();
var provider2 = builder2.BuildServiceProvider();

builder3.AddTransient<IEntity, Entity>();
builder3.AddTransient<IService, Service>();
builder3.AddTransient<IService1, Service1>();
var provider3 = builder3.BuildServiceProvider();

var entity1 = provider1.GetService<IEntity>(); // This will use default constructor
var entity2 = provider2.GetService<IEntity>(); // This will use constructor with 1 arg
var entity3 = provider3.GetService<IEntity>(); // Like above
...
```
And change constructors' order didn't change the behavior. Maybe I can find the answer in code later.

**Comment by khellang** [comment]
Try two with the same amount of arguments, but with different types. One with `IService` and one with `IService1`

**Comment by yhvicey** [comment]
@khellang This time it throws an exception. The doc is a little confusing. BTW, is there any way to force DI use one of its constructor, like an attribute?

**Comment by pakrym** [comment]
> Not AFAIK. It'll always pick the most greedy ctor based on the registered services. @pakrym?

Right. No way to select ctor in M.E.DI implementation. Other containers might support it though.

**Comment by yhvicey** [comment]
Thanks for your information.
