### ISSUE TITLE
BuildWebHost Errs on Internal IDictionary

### ISSUE THREAD

**Issue by livarcocc** [aspnet/Home#3161]
_From @rchrismon on May 11, 2018 5:51_

Not sure where to post this, perhaps you can tell me. 

Core 2.1 Web MVC App, Program.cs is stock out of the box. When I debug the app, it errs at 

`public static IWebHost BuildWebHost(string[] args) =>
			WebHost.CreateDefaultBuilder(args)
				   .UseStartup<Startup>()
				   .Build();`
The error is:

> Method not found: 'System.Collections.IDictionary Internal.Runtime.Augments.EnvironmentAugments.GetEnvironmentVariables()'.

FWIW, poking into the error details, I saw many errors around System.Reflection. One in particular caught my eye. 

> ((System.Reflection.RuntimeAssembly)((System.RuntimeType)((System.RuntimeType)((System.Reflection.RuntimeMethodInfo)($exception).TargetSite).DeclaringType).BaseType).Assembly).CodeBase

Any insight, or a better place to ask, I'd greatly appreciate.

Thanks,
Randy Chrismon

_Copied from original issue: dotnet/sdk#2236_

**Comment by livarcocc** [comment]
What version of the .NET Core SDK you are using? What are you using to debug it? If you are not debugging it, does the app run normally?

**Comment by livarcocc** [comment]
_From @rchrismon on May 11, 2018 19:54_

dotnet is 2.1.200 (haven't been able to get my project to use 2.1.4 -- but that's another problem).
SDK is 2.0.7

I was thinking there might be something in my code, but it literally breaks in Main(). Oh, one more thing, I'm using msbuild, NOT JetBrains build. ;-)

**Comment by livarcocc** [comment]
what do you mean by dotnet is 2.1.200 and the SDK is 2.0.7? They should be the same.

Also, I assume this is VS and msbuild vs. jetbrains build, you mean the setting to switch those?

@muratg is the stack above in ASP.NET?

What version of VS are you using?

**Comment by livarcocc** [comment]
_From @muratg on May 12, 2018 0:23_

That stack does not look familiar. 

I'm curious about your exact runtime you're using which caused this `MissingMethodException`.

**Comment by livarcocc** [comment]
_From @muratg on May 12, 2018 0:24_

@rchrismon also, if you haven't done already, I recommend asking over at stackoverflow.com as well.

**Comment by livarcocc** [comment]
_From @rchrismon on May 13, 2018 20:53_

Hi,

The dotnet runtime is 2.1.200. I meant to say the Windows runtime is 2.0.7 (probably doesn't have anything to do with this problem). 

To reiterate, the project builds without error, whether from within VS 2017 (15.8.1.1), or from the command line using dotnet or msbuilid. When starting the app with debug, it breaks on the second method in Program.cs. Several of my colleagues also tried to run the app without success. I have not, however, tried to run the app without debugging. I'll do that first thing tomorrow. I can't run the app from a web-server because I don't have an available non-production server available right now.

Also, I haven't asked the question on StackOverflow. I'll do that later this afternoon.

As always, thank you for your help.

Randy

**Comment by livarcocc** [comment]
_From @rchrismon on May 13, 2018 20:55_

I forgot to mention, my teammates run from their branches without problem, but they can't run my branch (same error). So, I'm guessing it has to be something in my code, or something in the additional dll packages I included with my build. I'm going to explore tomorrow what packages I have that they don't, or vise versa. 

Thanks!
Randy

**Comment by livarcocc** [comment]
_From @rchrismon on May 21, 2018 14:59_

Tried running the app from the command line -- dotnet run, so no debugging, but get the same error as running in VS. JetBrains Ultimate is latest version (2018.1) and VS is VS 2017 v15.8.0 Preview 1.1 professional. (I also get the error on my other computer when running from latest VS 2017 commercial release. 

I have removed every NuGet package not essential to the operation of the app, and the same with VS tools and extensions. Finally, for grins and giggles, I tried opening the solution in JetBrains Rider. Same error, same place, except the stack trace says the error originated in the Main method with BuildWebHost(args).Run().

Is it at all possible that this is a NullReferenceException without yielding that message? There are no command-line arguments so "args" is null on application startup. OTOH, I don't know why this app would bork here when so many others do not. 

Thanks.

**Comment by livarcocc** [comment]
I am moving this issue to asp.net, where it may get better traction. This is not looking like an SDK issue right now.

**Comment by Tratcher** [comment]
Do you have a minimal project you can share that reproduces this error?

**Comment by rchrismon** [comment]
I created a minimal .netcore 2.1 project, adding only the latest MySQL dlls, since that's a required part of the project. That project runs just fine. So, no help there. 

FWIW, I can't run _any_ branch of the application, including those done by my team members. All the same error.

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
