### ISSUE TITLE
Confusing/misleading download links for the latest asp.net core runtime for windows

### ISSUE THREAD

**Issue by joeaudette** [aspnet/Home#3163]
I wanted to comment here but the issue is locked:
https://github.com/aspnet/Docs/issues/6281

ran into the error mentioned in that issue after deployment of latest bits of an asp.net core 2.0.x app.

My feedback is the download links are very confusing. If you look here:
https://www.microsoft.com/net/download/Windows/run

you see a download for the latest ASP.NET Core Runtime which you would guess is all you need to "Run Apps". I installed that and still had the error from the linked issue.

Really for windows you need to dig into the full list of downloads for the current version ie here:
https://www.microsoft.com/net/download/dotnet-core/runtime-2.0.7

to get the Hosting Bundle Binaries

even more confusing is that the Hosting Bundle Binaries download is listed under Linux not under Windows where it should be

**Comment by joeaudette** [comment]
I think the IIS hosting package should be front and center on the main download page "Run Apps" section

**Comment by guardrex** [comment]
> I wanted to comment here but the issue is locked:

Yes, I locked that as not actionable for docs. Just trying to reduce the pings that that docs cats couldn't address. 😅

> which you would guess is all you need to "Run Apps".

There is an internal issue to address this aptly titled: *Consider adding an info bubble for the Hosting Bundle Installer*. I ask in the issue to add an info bubble next to the **Hosting Bundle Installer** link with text along the lines of ...

> The .NET Core Hosting Bundle installs the .NET Core Runtime, .NET Core Library, and the ASP.NET Core Module. The module creates a reverse proxy between IIS and the Kestrel server on Windows platforms.

I don't have an ETA on when the issue will be worked. I will add a note to that issue that links to your remarks so that they'll see this when they work it.

btw - The binaries you mentioned are specifically for Linux.

**Comment by rowanmiller** [comment]
Agreed, we are working on a set of updates to the page at the moment and the Hosting Bundle will be what you get for the main "Runtime" button.

**Comment by rowanmiller** [comment]
We'll have a table below the main download section that has other downloads, like the separate runtime installers

**Comment by joeaudette** [comment]
also confusing is this page which one clicks to get to all downloads:
https://www.microsoft.com/net/download/all which I clicked to look for the hosting bundle.

looking at the list there my first thought is that those links are for individual downloads and clicking one will start a download, but that is not the case, I have to click the link for the runtime I want and it goes to a page with the actual downloads including the hosting bundle. It would be more clear if those links indicated that they are not file downloads but links to lists of files. It took me a while to realize I should click the link to see more files because I thought the links I was looking at were for actual file downloads and I was reluctant to click because it wasn't what I was looking for.

**Comment by joeaudette** [comment]
Good grief, to make things even worse, when you install the download for hosting bundle 2.0.7 it does not install the 2.0.8 runtime store, which caused me 4 hours of trouble where my updated app won't run and trying to figure out what is wrong. 

Why the heck do I have go here to get the 2.0.8 runtime store installer and it isn't on the main downloads? I only found this from [someone helping me on stackoverflow](https://stackoverflow.com/questions/50567448/asp-net-core-deployment-persistent-errorcode-0x80004005-8000808c-on-win-20?noredirect=1#comment88147613_50567448).
https://github.com/dotnet/core/blob/master/release-notes/download-archives/2.1.200-sdk-download.md

really difficult getting the right files for windows server, not exactly falling into the pit of success

Also would be much better if versions could be consistent across sdk/runtime/frameworks
very confusing to have 2.1.x sdk, 2.0.8 runtime store 2.0.7 hosting bundle and know which ones go together. It should not be this hard to upgrade an app to the newer version of asp.net and the missing and confusing downloads is a major factor.

**Comment by rowanmiller** [comment]
Hopefully things are a bit more intuitive now. 

- The big "give me the latest runtime" button on the downloads page now gives you the hosting bundle.
- We've surfaced all of the vCurrent files on the main downloads page, so a lot less folks should need to delve into the complexity of the All Downloads section.
- Our plan is to always release the entire runtime as a single version, but that didn't happen with 2.0.8. We've created a 2.0.8 release on the site, and it gives you 2.0.7 files for the ones that weren't released (with a big orange banner explaining that you're getting a 2.0.7 file when you download the affected ones).
- Added the word "downloads" to the end of the .NET Core links on the All Downloads page. I know that doesn't completely solve the issue with expecting to get the actual download, but hopefully it helps. There isn't really a feasible way to list all the actual downloads for all versions on a single page.

We're very open to more feedback if there are things you think could still be improved.

**Comment by guardrex** [comment]
@rowanmiller

> The big "give me the latest runtime" button on the downloads page now gives you the hosting bundle.

I'm working out what our new IIS doc instruction can say based on the links/buttons present.

You're saying that the button doesn't download what the first runtime link downloads? ... or do they both download the runtime with the ANCM? 

<img width="593" alt="capture" src="https://user-images.githubusercontent.com/1622880/40757854-2240656c-6450-11e8-96fb-c3eb05eec853.PNG">

**Comment by rowanmiller** [comment]
@guardrex the big button gives you the hosting bundle, not just the .NET Core runtime. I agree there should be some way to identify this based on the text in the button. I'll put some thought into how to solve this.

**Comment by joeaudette** [comment]
Definitely much better now, thanks for the improvements!

**Comment by Eilon** [comment]
Closing because it appears that the main issue has been resolved. If there are remaining issues, please log new issues with details. Thanks!
