### ISSUE TITLE
Errors in Visual Studio startup tutorial for C#

### ISSUE THREAD

**Issue by eddye0** [aspnet/Home#3164]
To address your issues more quickly, please open the issue in the most appropriate repository. These are some of the most common repos:

Common ASP.NET and Entity Framework repos and projects:

 - Documentation: https://github.com/aspnet/Docs
 - MVC: https://github.com/aspnet/Mvc
 - Entity Framework Core: https://github.com/aspnet/EntityFrameworkCore
 - Entity Framework 6: https://github.com/aspnet/EntityFramework6
 - SignalR: https://github.com/aspnet/SignalR
 - Docker with ASP.NET Core: https://github.com/aspnet/aspnet-docker
 - Microsoft.NET.Sdk.Web: https://github.com/aspnet/websdk
 - Kestrel HTTP Server: https://github.com/aspnet/KestrelHttpServer
 - ASP.NET Katana: https://github.com/aspnet/AspNetKatana
 - and more! See a full list here: https://github.com/aspnet
 - note: several repositories have migrated their issues tracker to this repo here

Other common projects:

 - .NET Core CLI and SDK: https://github.com/dotnet/core
 - .NET Core runtime: https://github.com/dotnet/coreclr
 - .NET Core libraries: https://github.com/dotnet/corefx
 - NuGet: https://github.com/NuGet/home
 - Visual Studio: https://developercommunity.visualstudio.com
 - Visual Studio Code: https://github.com/microsoft/vscode
 - Omnisharp (C# support for VS Code): https://github.com/omnisharp/omnisharp-vscode

If you believe you have an issue that affects the security of the platform please do not create an issue, instead email your issue details to secure@microsoft.com. Your report may be eligible for our [bug bounty](https://technet.microsoft.com/en-us/mt764065.aspx).

**Comment by eddye0** [comment]
I'm new to MVC and Visual Studio 2017 so I've been doing the startup tutorial. Near the end of the Work with SQL Server LocalDB section when I was instructed to test the app I got the following errors in the output:
Build FAILED.
1>
1>Program.cs(12,7,12,13): warning CS0105: The using directive for 'System' appeared previously in this namespace
1>Models\SeedData.cs(17,52,17,85): error CS0246: The type or namespace name 'DbContextOptions<>' could not be found (are you missing a using directive or an assembly reference?)
1>Models\SeedData.cs(20,29,20,34): error CS1061: 'MvcMovieContext' does not contain a definition for 'Movie' and no extension method 'Movie' accepting a first argument of type 'MvcMovieContext' could be found (are you missing a using directive or an assembly reference?)
1>Models\SeedData.cs(25,25,25,30): error CS1061: 'MvcMovieContext' does not contain a definition for 'Movie' and no extension method 'Movie' accepting a first argument of type 'MvcMovieContext' could be found (are you missing a using directive or an assembly reference?)
1>Models\SeedData.cs(26,26,26,31): error CS0246: The type or namespace name 'Movie' could not be found (are you missing a using directive or an assembly reference?)
1>Models\SeedData.cs(34,26,34,31): error CS0246: The type or namespace name 'Movie' could not be found (are you missing a using directive or an assembly reference?)
1>Models\SeedData.cs(42,26,42,31): error CS0246: The type or namespace name 'Movie' could not be found (are you missing a using directive or an assembly reference?)
1>Models\SeedData.cs(50,24,50,29): error CS0246: The type or namespace name 'Movie' could not be found (are you missing a using directive or an assembly reference?)
1>    1 Warning(s)
1>    7 Error(s)

Can anyone help me with what the problem is?

**Comment by eddye0** [comment]
I would be happy to post this issue in another repository if I had any idea what repository it belonged in. This is an issue with the tutorial on C# in Visual Studio. Can someone please tell me which repository this belongs in.

**Comment by eddye0** [comment]
https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/start-mvc?tabs=aspnetcore2x&view=aspnetcore-2.1. That's where it starts. The section where the problem occurs is called "Work with SQL Server LocalDB.

**Comment by Tratcher** [comment]
There's a button at the bottom where it says "Sign in to give documentation feedback" to file an issue against that doc.
