### ISSUE TITLE
HTTP POST Request loosing cookies when sent from Linux

### ISSUE THREAD

**Issue by FasettoAndrew** [aspnet/Home#3166]
We have two ASP NET Core websites running in a Linux environment which communicate using HTTP requests.

On one server we are manually creating the new HTTP request and adding a provided cookie collection to the request like so:

`CookieCollection cookies` is passed to the method

```
// Create the request
var request = WebRequest.CreateHttp(OtherServerUrl);
request.Method = "POST";
request.ContentType = "application/json;charset=UTF-8";

// Add cookies if we have specified.
if (cookies != null)
{
    // Create new cookie container if one does not exist.
    if (request.CookieContainer == null)
    request.CookieContainer = new CookieContainer();

    // Add our cookies to the container.
    request.CookieContainer.Add(cookies);
}

if (content != null)
{
    // Serialize the model
    var JSONBody = JsonConvert.SerializeObject(content);

    // Write the json into the request stream
    using (var requestStream = await request.GetRequestStreamAsync())
    using (var sw = new StreamWriter(requestStream))
        await sw.WriteAsync(JSONBody);
}

// Get the request response as a HttpWebResponse
var response = (await request.GetResponseAsync()) as HttpWebResponse;
.....
```

In our use case, currently only a single cookie is being added, but we can see this if we output the request's cookie container; the cookie is in the request before it is sent. But when the request reaches the endpoint on the other server, the cookie container in the request contains 0 cookies.

The exact same code runs fine on Windows with the cookies being passed correctly, it only appears to occur on Linux.

**Comment by Tratcher** [comment]
This issue was moved to dotnet/corefx#29894
