### ISSUE TITLE
.Net core 2.0 runs using dotnet command, but not through IIS

### ISSUE THREAD

**Issue by AdamRiddick** [aspnet/Home#3167]
Hi,

I'm looking for more details debugging steps for the following issue, as I'm unable to find them;

**An error occurred while starting the application.
.NET Core 4.6.26328.01 X64 v4.0.0.0    |   Microsoft.AspNetCore.Hosting version 2.0.1-rtm-125    |    Microsoft Windows 10.0.14393    |   Need help?**

I'm able to run the application in question using `dotnet my.project.dll` and I don't get any errors;

Hosting environment: Production
Content root path: C:\MyProject\
Now listening on: http://localhost:5000
Application started. Press Ctrl+C to shut down.

and I can then access it fine on http://localhost:5000, but as soon as I attempt through IIS it fails.

I've enabled stdout logging (and created the relevant folder), but nothing is created in the logs. We do use serilog from the application, and can see the request starting but get no further information;

Request starting HTTP/1.1 GET http://mywebsite.com 0
From the source:  SourceContext Microsoft.AspNetCore.Hosting.Internal.WebHost

There is nothing in any IIS logs, event viewer and nothing appears in failed request tracing ... The application pool is configured correctly (Integrated, No managed code) and uses an application pool identity, which has the correct permissions to the folder in question.

Is there any documentation I've missed on debugging the error where the application runs fine through the `dotnet` command but not through IIS, when no information is logged ?

Thanks,

**Comment by AdamRiddick** [comment]
After doing so and re-publishing, I'm not getting any more information, still the same error message.

If there anything that would be preventing this coming through?

**Comment by Tratcher** [comment]
How did you enable it?

**Comment by AdamRiddick** [comment]
By enabling it after the default builder is created;

```
WebHost.CreateDefaultBuilder(args)
    .UseSetting(WebHostDefaults.DetailedErrorsKey, "true")
```


The environment is Production, if that helps.

**Comment by AdamRiddick** [comment]
@Tratcher Are you able help any further with this?

**Comment by Tratcher** [comment]
My only other suggestion is to launch the site with the VS debugger attached.
https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/development-time-iis-support?view=aspnetcore-2.1

**Comment by AdamRiddick** [comment]
I'll give that a go, thanks.

**Comment by Eilon** [comment]
Closing because no further action is planned for this issue. If you are still having a problem, please log a new issue with details for us to investigate.

**Comment by dewelloper** [comment]
Why did you closing the issure without finding a solution?

**Comment by umar-ulabs** [comment]
It is due to Microsoft Visual C++ redistributable 2015(not installed) in the case of .net core hosting bundle 2.0.5
