### ISSUE TITLE
context.Database.EnsureCreated() - Doesn't create __EFMigrationsHistory table

### ISSUE THREAD

**Issue by Udesh90** [aspnet/Home#3168]
When I used context.Database.EnsureCreated() method to create my database, it doesn't create __EFMigrationsHistory in my DB. So next time I run my DB updates EF core give me a tables are already exist. But I use to create my DB using "update-databse" in Package manger  console it will create __EFMigrationsHistory table & my DB updates will run smoothly. Why their is a conflict with context.Database.EnsureCreated() & "update-databse" ? 

Sorry for the inconveniences, or am in a wrong path.

**Comment by khellang** [comment]
This is by design. See https://thedatafarm.com/data-access/ef7-ensurecreated-vs-migrate-methods/

**Comment by Udesh90** [comment]
Thanks for sharing the post. 👍 👍
