### ISSUE TITLE
Request.EnableRewind() and UseStatusCodePagesWithReExecute disposes request body early

### ISSUE THREAD

**Issue by shinpou** [aspnet/Home#3169]
# General

.NET Core 2.0, AspNetCore 2.0.2

- Enable Request.EnableRewind()
- Configure app.UseStatusCodePagesWithReExecute()

Add custom middleware that reads the request.Body stream and logs it into the console.

Whenever a request gets re-executed (so in cases where a non-ok status code is returned), request.Body will appear as disposed inside the request logging middleware and cause an exception.

It would appear that ReExecute disposes the request.Body as a side effect, or the wrong instance of it is passed forward when re-executing.

**Comment by Tratcher** [comment]
As this is very order sensitive, please include some sample Startup code.

**Comment by shinpou** [comment]
Ok, after stripping down the code to the bare minimum, it seems that app.UseMVC registration point is the one that causes this issue specifically. Here's the code that will repro it:

> System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'FileBufferingReadStream'.
   at Microsoft.AspNetCore.WebUtilities.FileBufferingReadStream.ThrowIfDisposed()

https://gist.github.com/shinpou/f82943d9f45315e172f79e3a81999b43

However, swapping app.UseMvc() to be before the middleware that tries to read the request body fixes the problem.

So indeed, MVC related middlewares seem to be disposing the FileBufferingReadStream prematurely, or maybe this is intended?

**Comment by Tratcher** [comment]
Your StreamReader is disposing of the Body after the first read. You have to tell it to leave the stream open. See https://msdn.microsoft.com/en-us/library/gg712952(v=vs.110).aspx.

Also, use ReadToEndAsync().

**Comment by shinpou** [comment]
That was it, thanks!

**Comment by DamianEdwards** [comment]
Seems this can be closed now.

**Comment by dapeng-HB** [comment]
Get request body from ActionExecutingContext ActionFilter
[https://stackoverflow.com/questions/41850397/asp-net-core-get-request-body-from-actionexecutedcontext-actionfilter?rq=1](https://stackoverflow.com/questions/41850397/asp-net-core-get-request-body-from-actionexecutedcontext-actionfilter?rq=1)
