### ISSUE TITLE
Is https://github.com/aspnet/DataCommon Removed?

### ISSUE THREAD

**Issue by cuiliang** [aspnet/Home#317]
Got 404 error when open this url.

And got the following error when reference DbConnection class in my project. 

 Error	CS0246	The type or namespace name 'DbConnection' could not be found (are you missing a using directive or an assembly reference?)	

I'v already added 
        "System.Data.SqlClient": "4.0.0-beta-*",
        "System.Data.Common": "4.0.0-beta-*"
in dependencies section of project.json, and the assembly seems loaded ok.

**Comment by Eilon** [comment]
@rowanmiller @divega 

@cuiliang we made the rep private because everything should be resolved from MyGet now. That repo was meant to be temporary until we had an official DataCommon build.

**Comment by rowanmiller** [comment]
For a little more context, that repo was a temporary code base while the SQL Client team here at Microsoft worked on what is going to be the "real" System.Data.Common. We are now switched over to the proper version of that package, so the code base is no longer needed. The code base that the SQL Client team is using for the package may be available as open source later on, but at this stage it is not.

Perhaps a silly question... but do you have `using System.Data.Common;` in the file where you are trying to use `DbConnection`?

**Comment by cuiliang** [comment]
@Eilon thanks for your information
@rowanmiller yes I have using statements, Here is my sample code screen capture:

![Image of build error](http://urtracker.cn/datacommon.PNG)

Thank you

**Comment by cuiliang** [comment]
Resolved after update everything to beta4.
