### ISSUE TITLE
Remove UseExceptionHandler() extension

### ISSUE THREAD

**Issue by fragilerus** [aspnet/Home#3174]
The ExcptionHanlerMiddleware no longer supports empty options. Either ExceptionHandler or ExceptionHandlingPath has to be set. Therefore, the ExceptionHandlerExtensions.UseExceptionHandler() overload that takes no arguments can't be used. Either remove this or set a default for the options.

**Comment by Tratcher** [comment]
This overload can be used with `services.Configure<ExceptionHandlingOptions>(options => ...);`

**Comment by fragilerus** [comment]
Thank you, I did not think of that.
