### ISSUE TITLE
Serious slow asp.net web api

### ISSUE THREAD

**Issue by andrew-vandenbrink** [aspnet/Home#3175]
https://github.com/aspnet/AspNetCoreModule/issues/87

Running load test on my localhost with visual studio, debug or release barely have any difference

Api which barely do anything, from the template
/api/values

![image](https://user-images.githubusercontent.com/12871379/40767089-c0821f70-64b1-11e8-8c44-8ebced92233e.png)

![image](https://user-images.githubusercontent.com/12871379/40766936-5bead48a-64b1-11e8-9fff-5d3e17ec1e74.png)

In azure app service S1 Small, only 150-200 requests per sec?

![image](https://user-images.githubusercontent.com/12871379/40767299-6c2cc884-64b2-11e8-971a-4db60a053559.png)

**Comment by andrew-vandenbrink** [comment]
Api which doing connection to sql server express, localhost

![image](https://user-images.githubusercontent.com/12871379/40767637-5e540884-64b3-11e8-812c-622ef918524c.png)

azure app service, azure sql S3
![image](https://user-images.githubusercontent.com/12871379/40767748-b6138838-64b3-11e8-8263-98ac70b24067.png)


![image](https://user-images.githubusercontent.com/12871379/40767776-c78ba190-64b3-11e8-829c-3c8bc4927225.png)

**Comment by Tratcher** [comment]
@sebastienros

**Comment by sebastienros** [comment]
Can you share the application you are testing, I could verify that there is nothing obviously slowing down your requests. Maybe your SQL query is slow, maybe you are using Console logging, maybe something else, but if I can see the code you are stress testing that would be better understand where your issue is.

We are doing extensive perf test on many difference scenarios, see https://aka.ms/aspnet/benchmarks, including database access, and we are confident that it can be very fast. Seeing your code would help excluding some mistakes.

**Comment by andrew-vandenbrink** [comment]
Its ValuesController from web api template
I suspect company network + antivirus slowing down the load test above.

![image](https://user-images.githubusercontent.com/12871379/40803951-3dc800a4-651a-11e8-9802-737f0f081e19.png)

Here I test from home network to azure S1 Small

![image](https://user-images.githubusercontent.com/12871379/40803074-dccd1dae-6517-11e8-922a-c29d4b6f871f.png)

WebSurge 2 threads
70 requests/sec for ValuesController
WebSurge 4 threads
140 requests/sec for ValuesController

Make a test with database connection
WebSurge 4 threads
40 requests/sec

its no where close TechEmpower benchmark

**Comment by andrew-vandenbrink** [comment]
Can you run your benchmark in azure app service S1 Small?

**Comment by sebastienros** [comment]
> Can you run your benchmark in azure app service S1 Small?

Are you asking us? We already measure on Azure VMs D3v2. It's not surprising to have such numbers on S1 Small in App Service, it's the smallest machine available, and App Service has some perf impact compared to VMs.

**Comment by andrew-vandenbrink** [comment]
Yes

Is it too much to ask?

**Comment by Eilon** [comment]
Closing because there is no further action planned for this issue.
