### ISSUE TITLE
Shared namespace in Razor Page broke 'dotnet build' and VS2017

### ISSUE THREAD

**Issue by fe-c** [aspnet/Home#3178]
Using this at Razor Page markup **@using Shared.Helpers**
resolves as "App.Shared.Helpers" in Visual Studio and as "App.Pages.Shared.Helpers" with "dotnet build".
This causes such effects:
(some of them I can reproduce only on real project)
1. Sometimes VS can build and run application, sometimes not.
2. Sometimes VS shows error, sometimes not.
3. Sometimes VS can run app with showing error, sometimes it can't run without error.
4. Sometimes VS can build project, but can not launch it.
5. "dotnet build" always show error.

Error is "The type or namespace name 'Helpers' does not exist in the namespace 'App.Pages.Shared' "
May be I use wrong using directive and it's VS issue.

.Net Core SDK: dotnet-sdk-2.1.300-win-x64
VisualStudio 15.7.2
[TestApp.zip](https://github.com/aspnet/Home/files/2059693/TestApp.zip)

**Comment by pranavkm** [comment]
@fe-c looks like an oddity with how we generate code in Razor and namespace lookups. 

When editing `Index.cshtml` in VS, the generated code is the only file being compiled and it looks like so:

```C#
namespace TestApp.Pages
{

    using TestApp;
    using Helpers;
    using Shared.Helpers;
    
    public class Pages_Index : global::Microsoft.AspNetCore.Mvc.RazorPages.Page { }
}
```

When you build (both in VS or on the command line), the Razor Sdk compiles all cshtml files in your application in to a single assembly. The Layout page at this point gets generated as 

```C#
namespace TestApp.Pages.Shared
{
    public class Pages_Shared__Layout : global::Microsoft.AspNetCore.Mvc.Razor.RazorPage<dynamic> { }
}
```

The C# compiler assumes `using Shared.Helpers;` translates to `using TestApp.Pages.Shared.Helpers` and you get the warning you see here. In fact, you should see the same error if you open up a file in the Shared directory while you have Index.cshtml open. 

The fix would be to use a fully qualified namespace `@using TestApp.Shared.Helpers`

**Comment by fe-c** [comment]
But **using Helpers** from the same page works fine and translates into "TestApp.Helpers"?

In addition, these usings were generated by the VisualStudio, so I did not inadvertently duplicate this problem with the VS team? [Issue](https://developercommunity.visualstudio.com/content/problem/264729/shared-namespace-in-razor-page-broke-dotnet-build.html)

To use fully qualified namespace it is workaround or the final recommendation for such a case?

**Comment by fe-c** [comment]
As I find out, that ReSharper generates this usings, it's one more [report](https://youtrack.jetbrains.net/issue/RSRP-469969) to them.

**Comment by pranavkm** [comment]
> To use fully qualified namespace it is workaround or the final recommendation for such a case?

I'd chalk it up as recommendation. There's other possible workarounds (e.g. changing the namespace of views inside the `Shared` directory), but using fully qualified namespaces is least likely to get you ambiguous namespaces.
