### ISSUE TITLE
kpm misses versioning commands

### ISSUE THREAD

**Issue by Mpdreamz** [aspnet/Home#318]
`npm` exposes a version subcommand that allows you bump version numbers of your `package.json` on the commandline. 

https://docs.npmjs.com/cli/version

It would be nice if `kpm` was capable of the same for `project.json` files.

**Comment by davidfowl** [comment]
What are you trying to do exactly? Change the number from build to build or is it a one time thing?

**Comment by Bartmax** [comment]
I think he is talking about a bump versions command.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
