### ISSUE TITLE
Use the same data protection encryption settings in registry on every server in a webfarm

### ISSUE THREAD

**Issue by vincentkeizer** [aspnet/Home#3182]
The out-of-the-box solution for using data protection keys in a webfarm is storing them on a unc path and share this over all servers in the webfarm.

This feels like a single point of failure, because all servers use the same share, what if this share goes offline or becomes unavailable for some reason? 
I know it is possible to create my own mechanism, but it is about security, so it is a risk. Something you rather not customize.

It would be a better solution if all servers do not have to depend on other servers for their keys and just share the same encryption settings in registry.

**Comment by Tratcher** [comment]
A primary reason to share a location is so that keys can be rolled easily. Trying to keep them in sync manually across a farm sounds like a pain.

**Comment by vincentkeizer** [comment]
That sounds to me like something you could manage/automate by using a continuous delivery strategy.

**Comment by blowdart** [comment]
Remember keys get created by the servers, not centrally. You could of course use a database, but you'd have to write that yourself, and Windows can do mirroring of shares.

And a registry approach isn't cross platform :)

**Comment by vincentkeizer** [comment]
I understand the registry is not a cross platform approach. 
So the onjly cross platform approach without custom implemations is a unc path? Because I think creating custom code for dataprotection is a risk.

**Comment by blowdart** [comment]
Well there's also azure blob storage, which is an option.
