### ISSUE TITLE
UseDefaultFiles does not work in conjunction with ManifestEmbeddedFileProvider

### ISSUE THREAD

**Issue by onionhammer** [aspnet/Home#3183]
I have an 'index.html' in my razor class library project, and no wwwroot at all in my aspnet core app which references it;

Initialization code (snip)
```C#

            app.UseDefaultFiles();

            // var staticProvider   = new PhysicalFileProvider(Path.Combine(Directory.GetCurrentDirectory(), "wwwroot"));
            var manifestProvider = new ManifestEmbeddedFileProvider(typeof(SetupProvider).Assembly, "wwwroot");
            app.UseStaticFiles(new StaticFileOptions
            {
                FileProvider = manifestProvider //new CompositeFileProvider(staticProvider, manifestProvider)
            });
```

If I go to `/index.html` it works, but if i go to root `/` I get a 404.

**Comment by Tratcher** [comment]
UseDefaultFiles and UseStaticFiles need to reference the same FileProvider. UseFileServer combines the two more conveniently.

**Comment by onionhammer** [comment]
@Tratcher Ahh thank you. That makes sense
