### ISSUE TITLE
ASP.Net Core 2.1 Web project crashes when running in debug mode

### ISSUE THREAD

**Issue by francipvb** [aspnet/Home#3184]
Hello,

I don't know where I need to post this, but here are my issue.

Some minutes ago I started playing with aspnetcore 2.1 stable release and I have a big problem: when I run the project in debug mode with visual studio, after the second request to the server it crashes without any information, exception, anithing about the cause of the problem.

I've tested running inside IIS Express and the console application too and got the same problem.

I added this line to the end of the Main entrypoint in Program.cs:

```csharp
            Console.ReadKey();
```

And like with IIS the server closes without any pause nor crash reports.

Note that this occurs only when running in debug mode in Visual studio 15.7.

Cheers,

**Comment by jcasale** [comment]
If an unhandled exception occurs above the call to `ReadKey()`, how would that line ever get executed?

In `Main()`, wrap the call to `Run()` within a try/catch block and put a break point inside the catch block.

**Comment by francipvb** [comment]
Something strange happens with this.

The breakpoint is never reached.

I missed this information. The exit code is -1 (0xffffffff).

See this log chunk from the output window (I have a spanish locale):

~~~
Microsoft.AspNetCore.Hosting.Internal.WebHost:Information: Request starting HTTP/1.1 GET http://localhost:44355/lib/bootstrap/dist/css/bootstrap.css  
Microsoft.AspNetCore.Hosting.Internal.WebHost:Information: Request starting HTTP/1.1 GET http://localhost:44355/js/site.js?v=dLGP40S79Xnx6GqUthRF6NWvjvhQ1nOvdVSwaNcgG18  
Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware:Information: The file /lib/bootstrap/dist/css/bootstrap.css was not modified
Microsoft.AspNetCore.Hosting.Internal.WebHost:Information: Request starting HTTP/1.1 GET http://localhost:44355/css/site.css  
Microsoft.AspNetCore.Hosting.Internal.WebHost:Information: Request finished in 12.1026ms 304 text/css
Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware:Information: The file /css/site.css was not modified
Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware:Information: The file /js/site.js was not modified
Microsoft.AspNetCore.Hosting.Internal.WebHost:Information: Request finished in 35.2285ms 304 application/javascript
Microsoft.AspNetCore.Hosting.Internal.WebHost:Information: Request finished in 33.8867ms 304 text/css
El programa '[1492] dotnet.exe' terminó con código -1 (0xffffffff).
~~~

I hope that this can help.

I notized that there is an update. I'll check if this fixes my problem.

**Comment by francipvb** [comment]
Hello,

I've tested with ASP.Net core 2.0 with same results.

P.D: I'm using firefox as my web browser because of it's support for screen readers and I've read about a feature that terminates the debugging session when you close the browser.

Cheers,

**Comment by francipvb** [comment]
Ah, well, I've found that option.

Cheers,

**Comment by francipvb** [comment]
I'm closing this because this is a valid feature of Visual Studio and it is not integrated with Firefox.

Sorry for that.

Cheers,
