### ISSUE TITLE
Kestrel works very slow when it is operating under IIS

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Home#3188]
_From @san-sei on June 3, 2018 11:6_

We are facing a strange problem with using Kestrel under IIS in which some operations (e.g. getting access CA- [CertEnrolllib ](https://msdn.microsoft.com/en-us/library/windows/desktop/aa374850(v=vs.85).aspx)) take about 100 sec processing time to be complete.
Please note that everything works well with using IIS Express and also [http.sys](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/httpsys?view=aspnetcore-2.1) (instead of IIS) where every operation takes maximum 5 seconds to be complete.

_Copied from original issue: aspnet/KestrelHttpServer#2642_

**Comment by Tratcher** [comment]
_From @san-sei on June 3, 2018 12:8_

Here is the code for an action that works on the aforementioned library CertEnrolllib for certificate enrollment purpose.
```
    public class TestController : Controller
    {
        [HttpGet]
        public IActionResult Index()
        {
            var s = Stopwatch.StartNew();
            var type = Type.GetTypeFromProgID("X509Enrollment.CX509CertificateRequestPkcs10");
            var instance = Activator.CreateInstance(type);
            type.InvokeMember("InitializeFromTemplateName",
                BindingFlags.InvokeMethod,
                null,
                instance,
                new object[] { 1, "CertEnrollment" });

            s.Stop();
            return Content(s.ElapsedMilliseconds.ToString());
        }
    }
```

**Comment by Tratcher** [comment]
What does that API do? Does it make requests to a second machine or the internet? When in IIS your application is running as a different user with different permissions and settings like web proxies.

**Comment by san-sei** [comment]
This a request for making a certificate on the Microsoft CA. Yes, this request is going to process on the CA Server.
The client application/code, for our test, is running now inside the VM and I'm not sure about the proxy setting on the host machine. I will update you on this. 
As I said before, the IIS Express or http.sys works very well and fast on the same settings. Have you any thoughts about something that may make differences between IIS and IIS Express on the way of accessing remotely to a server machine (on the local network).

**Comment by Tratcher** [comment]
IIS Express and Http.Sys both run using the developer's credentials and settings. IIS runs using the application pool identity.

**Comment by san-sei** [comment]
Hey Tratcher, I see the problem will be solved if we change the Application pool identity with the [Built-in account -> LocalSystem] instead of using a [Custom account like Administrator]. But this is not a solution for us since our requests/actions are going to be processed by the Microsoft CA where it just knows the AD users, not 'LocalSytem'. 
Have you any idea what is going wrong here when we use the Administrator of the root domain as Pool Identity?

**Comment by Eilon** [comment]
Closing because this appears to be an application-specific issue.

**Comment by Xorcist77** [comment]
I actually resolved my issue, I'm going to post here just for reference in case anyone runs into HttpClient slowness when Kestrel is hosted through IIS. Turns out the reason it was slow for the AppPool user and not the Local System, was the difference in the ability of the account to resolve the default proxy. The solution was to simply set the HttpClient to not proxy, via a HttpClientHandler as such:

```
HttpClientHandler clientHandler = new HttpClientHandler() { UseProxy = false };
using (HttpClient client= new HttpClient(clientHandler)) {
  .
  .
  .
}
```

**Comment by hueidou** [comment]
Same issue. `UseProxy = false` solves the problem, but why? It will take us a lot of time if we modify it like this. It already took me two days to find this problem. 

At the same machine, .net framework iis web application and asp.net core standalone command works well

**Comment by Tratcher** [comment]
@davidsh any thoughts on why it takes the proxy detection so long to time out on core?

**Comment by hueidou** [comment]
Problem solved. I deleted all user's proxy settings by regedit.exe, and it works.

Regedit location(delete all userId's):
HKEY_USERS\{userId}\Software\Microsoft\Windows\CurrentVersion\Internet Settings

Be careful in production environment!!!
This is not offical method!!!

**Comment by davidsh** [comment]
>@davidsh any thoughts on why it takes the proxy detection so long to time out on core?

Proxy detection is a network activity. I'm assuming that the IE settings were set to "Automatically discover a proxy". We use WinHTTP APIs to do that work which involved WPAD protocol on the network. It's possible that waiting for that activity which uses both DNS record lookup and DHCP protocol could be time consuming on certain networks.
