### ISSUE TITLE
Download prerequisite from local path is not working

### ISSUE THREAD

**Issue by NandhiniKaruppusamy** [aspnet/Home#3189]
![image](https://user-images.githubusercontent.com/39897016/40900162-dcd524e0-67e7-11e8-8c12-e860dbf8c346.png)

![image](https://user-images.githubusercontent.com/39897016/40900188-fd4b085c-67e7-11e8-86a7-70515d3c06e8.png)

**Comment by Tratcher** [comment]
Please report this issue directly through the Visual Studio feedback tool.
