### ISSUE TITLE
If a class exists that has the word `Redis` in it, the app fails to run

### ISSUE THREAD

**Issue by 0xdeafcafe** [aspnet/Home#319]
This is probably one of the weirdest bugs I've encountered in aspvnext. If you create a class that contains the word `Redis` and execute the app, it hangs on page loading, and sometimes ends up displaying a 403 forbidden error page from iis, as displayed below:
![swag](http://i.imgur.com/MQi9nJU.png)

As you can see, the class has no references and no code, so my only assumption is that it's because of the name. My only thought of what the issue could be is EntityFramework as it is going to have redis providers. But I haven't tested it without the EF nuget packages installed.

**Comment by davidfowl** [comment]
I'm guessing it has nothing to do with the fact that the class is named Redis and that just happens to be a coincidence. Make sure you're default KRE and your packages are beta2.

**Comment by 0xdeafcafe** [comment]
Literally renamed the class from Redis to something else and it started to work again. Tried in multiple folders too. Here is my project.json:

``` json
{
	"webroot": "wwwroot",
	"version": "1.0-bae-*",
	"exclude": [
		"wwwroot"
	],
	"packExclude": [
		"**.kproj",
		"**.user",
		"**.vspscc"
	],
	"dependencies": {
		"Microsoft.AspNet.Mvc": "6.0.0-beta1",
		"Microsoft.AspNet.Server.IIS": "1.0.0-beta1",
		"Microsoft.AspNet.Diagnostics": "1.0.0-beta1",
		"Microsoft.AspNet.Mvc.WebApiCompatShim": "6.0.0-beta1",
		"Microsoft.Framework.ConfigurationModel.Json": "1.0.0-beta1",
		"Microsoft.Framework.Logging": "1.0.0-beta1",
		"Microsoft.Framework.Logging.Console": "1.0.0-beta1",

		"System.Security.Cryptography.Hashing": "4.0.0-beta",
		"System.Security.Cryptography.Hashing.Algorithms": "4.0.0-beta",
		"System.Security.Cryptography.Encoding": "4.0.0-beta",
		"System.Security.Cryptography.Encryption": "4.0.0-beta",
		"System.Security.Cryptography.DeriveBytes": "4.0.0-beta",
		"System.Security.Cryptography.Encryption.Aes": "4.0.0-beta",
		"System.Security.Cryptography.Encryption.RSA": "4.0.0-beta",
		"System.Security.Cryptography.X509Certificates": "4.0.0-beta",
		"System.Security.Cryptography.RandomNumberGenerator": "4.0.0-beta",

		"EntityFramework": "7.0.0-beta1",
		"EntityFramework.SqlServer": "7.0.0-beta1",
		"EntityFramework.Commands": "7.0.0-beta1",

		"StackExchange.Redis": "1.0.394"
	},
	"commands": {
		"ef": "EntityFramework.Commands"
	},
	"frameworks": {
		"aspnet50": { }
		//"aspnetcore50": { }
	}
}
```

If I move the packages to beta2, I get the following exception:
![](http://i.imgur.com/rcyeZbQ.png)

**Comment by davidfowl** [comment]
It doesn't have anything to do with redis.

**Comment by 0xdeafcafe** [comment]
I made a new web project, this is my project.json:

``` json
{
	"webroot": "wwwroot",
	"version": "1.0.0-*",
	"exclude": [
		"wwwroot"
	],
	"packExclude": [
		"node_modules",
		"bower_components",
		"**.kproj",
		"**.user",
		"**.vspscc"
	],
	"dependencies": {
		"Microsoft.AspNet.Server.IIS": "1.0.0-beta2"
	},
	"frameworks": {
		"aspnet50": { },
		"aspnetcore50": { }
	}
}
```

I added a file called `Redis.cs`, and same issue again, 503 error's every time. Literally haven't touch any code other than adding `Redis.cs`.

**Comment by gulbanana** [comment]
i tried to reproduce this using vs+beta2 and didn't experience the same error, so there must be more factors to it

**Comment by 0xdeafcafe** [comment]
Try adding the following to the project.json, and trying again:
```
"EntityFramework": "7.0.0-beta1",
"EntityFramework.SqlServer": "7.0.0-beta1",
"EntityFramework.Commands": "7.0.0-beta1",
```

**Comment by danroth27** [comment]
We are not able to reproduce this issue with the latest bits. If you can send us a sample project we will take another look.
