### ISSUE TITLE
Razor class library referencing another razor class library can't publish

### ISSUE THREAD

**Issue by svallis** [aspnet/Home#3190]
I'm experiencing issues publishing applications from Visual Studio where one razor class library references another razor class library. Everything works perfectly from the command line, the issue is just with VS, so apologies if this is the wrong place for it.

I've created a reproduction repo for the issue below:

https://github.com/svallis/PublishTest.git

This demonstrates a solution with two class libraries, one of which (`Shared`) references another (`Framework`). Publishing this solution from the command line works exactly as expected:

```
PS C:\Development\PublishTest\Website> dotnet publish -c Release
Microsoft (R) Build Engine version 15.7.179.6572 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 76.59 ms for C:\Development\PublishTest\Website\Website.csproj.
  Restore completed in 76.59 ms for C:\Development\PublishTest\Framework\Framework.csproj.
  Restore completed in 76.59 ms for C:\Development\PublishTest\Shared\Shared.csproj.
  Framework -> C:\Development\PublishTest\Framework\bin\Release\netcoreapp2.1\Framework.dll
  Framework -> C:\Development\PublishTest\Framework\bin\Release\netcoreapp2.1\Framework.Views.dll
  Shared -> C:\Development\PublishTest\Shared\bin\Release\netcoreapp2.1\Shared.dll
  Shared -> C:\Development\PublishTest\Shared\bin\Release\netcoreapp2.1\Shared.Views.dll
  Website -> C:\Development\PublishTest\Website\bin\Release\netcoreapp2.1\Website.dll
  Website -> C:\Development\PublishTest\Website\bin\Release\netcoreapp2.1\Website.Views.dll
  Website -> C:\Development\PublishTest\Website\bin\Release\netcoreapp2.1\publish\
```

But publishing from within Visual Studio acts as if `Shared` has no knowledge of `Framework`, despite an explicit project reference:

```
SharedClass.cs(9,13): Error CS0103: The name 'Framework' does not exist in the current context
SharedClass.cs(11,28): Error CS0246: The type or namespace name 'Framework' could not be found (are you missing a using directive or an assembly reference?)
```

The repository has a file system publish profile set up which demonstrates the failure. Building and running the solution works as you would expect it to.

This seems to be related to the new `Microsoft.NET.Sdk.Razor` project SDK, as reverting `Shared` and `Framework` to the old `Microsoft.NET.Sdk` SDK resolves the publishing issue, but obviously breaks the embedded razor views. Am I missing something obvious?

**Comment by pranavkm** [comment]
Dup of https://github.com/aspnet/Razor/issues/2363.

We're addressing this in our upcoming 2.1.1 release. In the meanwhile, doing `dotnet publish` is one option. The other workaround is listed here - https://github.com/aspnet/Razor/issues/2363#issuecomment-391535844
