### ISSUE TITLE
ASP.Net core 2.x IIS Hosted VS Self-hosted performance issues

### ISSUE THREAD

**Issue by primenum** [aspnet/Home#3191]
Hi guys.
We are developing ASP.NET core application and having performance issues hosting application under IIS. Application hosted under IIS working 14 times **slower** than self-hosted using IIS as reverse proxy with URL rewrite module
Asp.net core 2.1

Load test performed with VS 2017
AspNetCoreModule - aspnetcore.dll  file version  -  8.2.1991.0
The result are: 
IIS hosted AVG Response Time:  0.06 sec
Self-Hosted with IIS as reverse proxy: 0.0042

## **Code:**

**Program.cs**

```
public class Program
    {
        public static void Main(string[] args)
        {
            CreateWebHostBuilder(args).Build().Run();
        }

        public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
            .UseKestrel()
            .UseIISIntegration()
            .ConfigureAppConfiguration((hostingContext, config) =>
            {
                ConfigureApplicationSettings(hostingContext, config);
            })
            .ConfigureLogging((context, logging) =>
            {
                //logging controlled from config file

                logging.AddConfiguration(context.Configuration.GetSection("Logging"));
                logging.SetMinimumLevel(LogLevel.None);

            })
                .UseStartup<Startup>();

        private static void ConfigureApplicationSettings(WebHostBuilderContext hostingContext, IConfigurationBuilder config)
        {
            var env = hostingContext.HostingEnvironment;

            //set base path
            config.SetBasePath(Directory.GetCurrentDirectory());

            //set configuration files
            config.AddJsonFile("appsettings.json", optional: false, reloadOnChange: true)
                  .AddJsonFile($"appsettings.{env.EnvironmentName}.json", optional: false, reloadOnChange: true);

            config.AddEnvironmentVariables();
            config.Build();
        }
    }

```
**Startup**
```
public class Startup
    {
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddMvc();
        }

        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UseMvc();
        }
    }
```

**API** 
```
[Route("core/plain")]
    [ApiController]
    public class PlainController : ControllerBase
    {
        [HttpGet]
        public IActionResult GetServerTime()
        {
            string sHtml = $"Asp.Net core 2.1,  server time: {DateTime.Now.ToString("yyyy-MM-dd, HH:mm:ss")}";
            return Ok(sHtml);
        }
    }

```

What are we doing wrong? 
We found out this issue in 2.0 and waited for 2.1 in hope this well be solved, but....

**Comment by Tratcher** [comment]
@shirhatti @sebastienros

**Comment by shirhatti** [comment]
Not sure I entirely follow. URL Rewrite is not a reverse proxy module. Were you merely redirecting requests to the endpoint where Kestrel is hosted or were you reverse proxying using ARR?

If it's the former, your observed results make total sense. If it's the latter, we need to investigate.

**Comment by primenum** [comment]
I have 2 scenarios.
**First one - IIS hosted.** 
The asp.net core application running under iis, configuration as described here
[https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/?view=aspnetcore-2.1&tabs=aspnetcore2x#iis-configuration](url)

**Second scenario.**
I created an web site in IIS with this web.config

```
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
    <system.webServer>
        <rewrite>
            <rules>
                <rule name="ReverseProxyInboundRule1" stopProcessing="true">
                    <match url="(.*)" />
                    <action type="Rewrite" url="http://localhost:5000/{R:1}" appendQueryString="false" logRewrittenUrl="true" />
                    <serverVariables>
                    </serverVariables>
                </rule>
               
            </rules>
            <outboundRules>
                <rule name="ReverseProxyOutboundRule1" preCondition="ResponseIsHtml1" stopProcessing="true">
                    <match filterByTags="A, Form, Img" pattern="http://localhost:5000/(.*)" />
                    <action type="Rewrite" value="http://int.loadtestCore2.vcloud/{R:1}" />
                </rule>
               
                <preConditions>
                    <preCondition name="ResponseIsHtml1">
                        <add input="{RESPONSE_CONTENT_TYPE}" pattern="^text/html" />
                    </preCondition>
                    <preCondition name="NeedsRestoringAcceptEncoding">
                        <add input="{HTTP_X_ORIGINAL_ACCEPT_ENCODING}" pattern=".+" />
                    </preCondition>
                </preConditions>
            </outboundRules>
        </rewrite>
        
    </system.webServer>
</configuration>

```

**Asp.Net core executed from command line like this:
![2018-06-04_200524](https://user-images.githubusercontent.com/7868048/40931142-a289e910-6832-11e8-9afe-ccce21180db3.png)

**ARR configuration:**

![2018-06-04_200219](https://user-images.githubusercontent.com/7868048/40931070-5166bc16-6832-11e8-8aaa-682606a73e11.png)
![2018-06-04_200234](https://user-images.githubusercontent.com/7868048/40931071-51c7ec2a-6832-11e8-9b7e-2f7a3d84e77d.png)

**The results are, scenario 2 14 times better then 1.**
You can provide me with instruction if you need more data, I'll glad to cooperate. 
Thanks in advance.

**Comment by shirhatti** [comment]
Adding @jkotalik and @pan-wang for visibility

**Comment by primenum** [comment]
Hi guys, any news?

**Comment by pan-wang** [comment]
Just looked at your ARR settings,  you had cache enabled at ARR.  Some responses were cached and then served from cache, while ANCM did not have such caching mechanism. This is why you saw higher throuput for ARR.  You should compare the performance by disabling ARR caching.

**Comment by primenum** [comment]
The request are not cached, also I disabled caching here is 
ARR cache statistics:
![2018-06-07_174343](https://user-images.githubusercontent.com/7868048/41107890-e9a4de86-6a7b-11e8-835f-b3becdc40c8e.png)

**Test result after disabling ARR cache**

ASP.Net core using **ANCM**
![2018-06-07_180156](https://user-images.githubusercontent.com/7868048/41108335-e9af58a6-6a7c-11e8-8e32-7e1f345162fa.png)

ASP.NET core **Not** using **ANCM** (self-hosted)
![2018-06-07_174516](https://user-images.githubusercontent.com/7868048/41108048-3fbfbd04-6a7c-11e8-97d7-012d0d2d0803.png)

**Comment by pan-wang** [comment]
couple points: 1) for ANCM scenario, the kestrel process was created on demand. Process start time should be excluded. You need set some warm-up duration for the test
2) ANCM scenario, couple http headers were added at ANCM and were validated at the backend which should hurt the perf
3) the CPU and memory usage. for ANCM scenario, kestrel process is a child process which could impact the throughput
4) some potential improvement in ANCM, e.g., reuse objects to avoid memory fragments.
Will try to run the same test in house
________________________________

**Comment by primenum** [comment]
Hello @pan-wang .

1. Warm-up process performed before test is executed, so it's not an issue.
2. Adding and validating a couple of header reduce performance 10 times? In Self-Hosted scenario, no headers added? Can I control those headers, or can I add those headers in Self-Hosted scenario to eliminate this reason of possible performance penalty?  
3. In Self-hosted scenario kestrel is also a child process.
ANCM scenario CPU, at max load 50 users, overall server CPU is around 25% dotnet process is less then 8%, see the screen shout of CPU utilization at max load
![2018-06-10_095059](https://user-images.githubusercontent.com/7868048/41199059-eafbe2ce-6c93-11e8-9628-7c76caf7a661.png)

The IO that U see, i need to find out where it come from, logger should be disabled, but if it not in both scenarios it's a same code that running.

**Comment by karthicksundararajan** [comment]
I have exactly the same issue. In self-hosted asp.net core 2.1 works faster than the app hosted in IIS with ANCM. Even after warm-up, the application performance is significantly slow.

**Comment by Tratcher** [comment]
@karthicksundararajan IIS is expected to be slower due to the reverse proxy configuration. Do you have metrics for each scenario?

**Comment by karthicksundararajan** [comment]
@Tratcher 

I ran load test on both self-hosted and IIS, here are the result. 

Self-hosted runnding on localhost (published version) result
![image](https://user-images.githubusercontent.com/7643036/42157403-ee15ae16-7ded-11e8-9503-5b8aa60e1bba.png)

On IIS hosted on Azure Windows 2016 VM (Size B2s - 4GB ram, 2vcpus)
![image](https://user-images.githubusercontent.com/7643036/42157524-33dc469e-7dee-11e8-93bf-10f571ef40fc.png)

Browser results for the app runnsing IIS
![image](https://user-images.githubusercontent.com/7643036/42157635-8701ce98-7dee-11e8-99b5-f4e4000dee00.png)

Which takes 14.19s to respond, excluding warmup. However, in self-hosted average response time is around 200ms.

**Comment by Tratcher** [comment]
Localhost is not a valid comparison with a remote VM. Also, your response sizes are different. Why are any requests cached?

Overall though, when your throughput is so low the server differences should not be related at all. We know IIS can handle thousands of requests per second on minimal hardware even in the reverse proxy configuration. I suggest profiling your application code directly to see what's taking so long to execute.

**Comment by Eilon** [comment]
Hi. We're closing this issue as no response or updates have been provided in a timely manner and we have been unable to reproduce it. If you have more details and are encountering this issue please add a new reply and re-open the issue.
