### ISSUE TITLE
Razor Class Library is not routed properly when referenced from a WebForms project

### ISSUE THREAD

**Issue by TPIvan** [aspnet/Home#3196]
When I create a _Razor Class Library_ (Visual Studio 2017 + Core 2.1 Template) and reference it from an _ASP.NET Core Web Application_ Project the `Page1 `created by the template is available on the address `/MyFeature/Page1` .  When I do the same with an _ASP.NET Web Application (.NET Framework)_ the page is not available on the address (HTTP 404).

**Comment by pranavkm** [comment]
@TPIvan are you attempting to reference the class library from a Mvc 5 \ WebForms project? That wouldn't work. Razor Class Library requires ASP.NET Core to run.

**Comment by TPIvan** [comment]
@pranavkm 
 Yes this is exactly what I am doing. It seems to be possible to work with classes defined in the Razor Pages project, but not the pages.  
The ability to work with Rasor Page library would easify a  step by step transition from Net/Webforms to core. So the only way of connection both technologies is to have two separate processes (virtual directories)?

**Comment by pranavkm** [comment]
> So the only way of connection both technologies is to have two separate processes (virtual directories)?

Yes, that would likely be the model to go with. cc @davidfowl in case you have anything further to add.

**Comment by davidfowl** [comment]
That’s right. There’s no way to host one in the other. It needs to be run side by side in different processes
