### ISSUE TITLE
WebSocket requests with high response time trigger recycle too frequently

### ISSUE THREAD

**Issue by ndreisg** [aspnet/Home#3197]
Hi there,

I have an ASP.net Core WebSocket Server hosted as Azure Web App.
In Azure Portal I have very high response times. It seems like the complete time a WebSocket connection is opened, counts as response time.

Due to these high request times, the Web App is recycled more frequently.
Today I got three events with ID 2299 (Worker Process requested recycle due to 'Percent Slow Requests' limit.) in "Application Events".

Is it possible to tell Azure, that it shouldn't count the response times of WebSocket requests to these limits?
Or is it possible to deactivate this limit completely?

Best regards.
Alex

**Comment by Tratcher** [comment]
@shirhatti , where should an app service specific issue like this go?

**Comment by shirhatti** [comment]
@davidebbo ?

**Comment by davidebbo** [comment]
I'm not familiar with this process recycle mechanism. @ndreisg can you start a thread in either the MSDN Web App forum or Stackoverflow to reach the right crowd? Thanks.

**Comment by ndreisg** [comment]
Thread in MSDN Web App Forum: https://social.msdn.microsoft.com/Forums/en-US/e3bcdb69-a28f-482e-a89a-49b1a7e00ecf/websocket-requests-are-leading-to-high-response-times-in-azure-monitoring

**Comment by Eilon** [comment]
Closing because it appears there is an accepted answer at https://social.msdn.microsoft.com/Forums/en-US/e3bcdb69-a28f-482e-a89a-49b1a7e00ecf/websocket-requests-are-leading-to-high-response-times-in-azure-monitoring.
