### ISSUE TITLE
Binding GUID to query string does not work when adding ApiController attribute

### ISSUE THREAD

**Issue by seroche** [aspnet/Home#3202]
After adding the `[ApiController]` attribute to my controller, parameters passed through the query string cannot be bound to `GUIDs`.

For example:  
`public async Task<IActionResult> Get(Guid id, CancellationToken token) { (...) }` always returns:
```
{
    "": [
        "The input was not valid."
    ]
}
```

Any idea why? Did I miss something obvious?

**Comment by pranavkm** [comment]
@seroche looks like a dup of https://github.com/aspnet/Mvc/issues/7546 \ https://github.com/aspnet/Mvc/issues/7982. You're likely missing specifying the compat version in your Startup:

```C#
var mvcBuilder = services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_1);
```

Feel free to use the other open issue for further discussions
