### ISSUE TITLE
Add HttpRequest.GetUri method

### ISSUE THREAD

**Issue by evil-shrike** [aspnet/Home#3203]
There's a helpful extension method: `Microsoft.ApplicationInsights.AspNetCore.Extensions.HttpRequestExtensions.GetUri` that returns full uri for a given HttpRequest. For some reason these's no such a method in base classes. 

But the method is in Microsoft.ApplicationInsights.AspNetCore which starting 2.1 isn't included in metapackage anymore. So usage of the method became not very convenient.

It'd be nice to have such a method somewhere in "Microsoft.AspNetCore.App".

**Comment by Tratcher** [comment]
You're looking for GetEncodedUrl or GetDisplayUrl.
https://github.com/aspnet/HttpAbstractions/blob/ab0185a0b8d0b7a80a6169fd78a45f00a28e057d/src/Microsoft.AspNetCore.Http.Extensions/UriHelper.cs#L176

Out of curiosity what do you need it for? It's not much good outside of logging.

**Comment by evil-shrike** [comment]
Thanks, but GetEncodedUrl or GetDisplayUrl return strings not Uri.
Besides logging (and putting uri into exceptions) I use `Uri.IsLoopback()` to detect local requests.

**Comment by Tratcher** [comment]
See https://github.com/aspnet/HttpAbstractions/issues/536
