### ISSUE TITLE
ASP.NET Core 2.1 UseHttpsRedirection on macOS/kestrel not working 

### ISSUE THREAD

**Issue by anorborg** [aspnet/Home#3205]
I was working on a fairly empty project (made from the dotnet new webapi template. Attempted to use app.UseHttpsRedirection. While the page loads with https, if I use an http://localhost:5001 directly, I don't get redirected, just no response. Am I configuring something incorrectly?

I attempted to configure per docs here:
https://docs.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-2.1&tabs=visual-studio#http-strict-transport-security-protocol-hsts

adding:

```
services.AddHttpsRedirection(options =>
{
      options.RedirectStatusCode = StatusCodes.Status301MovedPermanently;
      options.HttpsPort = 5001;
})
```

and

```
app.UseHttpsRedirection();
```

curl output is:
```
curl -I http://localhost:5001
curl: (52) Empty reply from server
```

Any thoughts on my config?

**Comment by anorborg** [comment]
I think I may be mistaken on expected behavior perhaps. if you explicitly use the protocol, `http` and the port, perhaps redirecting doesn't work. I just tried running on http on port 5000 and it correctly redirected to https://localhost:5001

**Comment by Tratcher** [comment]
http and https must be on different ports. You can't send an http request to an https port, it can't be parsed.

**Comment by anorborg** [comment]
Yeah, makes sense in retrospect. Thanks for clarifying. I wonder if there is a better way to handle or throw for an invalid request like that? perhaps that doesn't align with HTTP protocol.

**Comment by Tratcher** [comment]
It's a pretty fundamental error at the protocol level, you're speaking entirely the wrong language. We considered some mitigations for Kestrel but it wouldn't help any of the other servers (IIS, Http.Sys, Nginx, etc.).

**Comment by anorborg** [comment]
Understood. Thanks again for the explanation!
