### ISSUE TITLE
Core 2.0 WebSocket ReceiveBufferSize being ignored.

### ISSUE THREAD

**Issue by EldinZenderink** [aspnet/Home#3206]
I am not exactly sure if this is an issue or that I am doing something wrong, but I can't seem to find a solution for something that should be quit easy.

[https://stackoverflow.com/questions/50739391/asp-net-core-2-0-websocketoptions-ignores-receive-buffer-size](https://stackoverflow.com/questions/50739391/asp-net-core-2-0-websocketoptions-ignores-receive-buffer-size)

**Comment by khellang** [comment]
Are you sure you're not using 2.1?

**Comment by EldinZenderink** [comment]
Yep, I'm sure of it. 

![](https://i.imgur.com/mYEEv3B.png)

But I did update the library recently, but before I had the need to change the buffersize, maybe thats the cause. Going to test that. Thanks for your response.

**Comment by khellang** [comment]
Yeah, that's the runtime. I'm talking about the version of your ASP.NET Core packages 😊

**Comment by EldinZenderink** [comment]
Ah sorry: 

![](https://i.imgur.com/jm0SZWV.png)

I downgraded the websocket package down to version 1.0.2 but still didn't work. So I guess it's something else.

**Comment by khellang** [comment]
I think we need to ask @davidfowl 😝

**Comment by EldinZenderink** [comment]
I possibly found the issue... it has nothing to do with my back-end. Just testing it out with a websocket tester (Simple Websocket Client chrome plugin) I could send  over exactly 7998 characters before Computer Says No. Meaning my issue lies with the client, I suppose, I have been looking at it the wrong way.  So, not sure why I can't make full use of the 8192 bytes(maybe some header stuff or something added to the send message) but it's better than nothing at least... Sorry for the confusion.
