### ISSUE TITLE
Cannot Upgrade Package Microsoft.AspNetCore.All to version 2.1.0

### ISSUE THREAD

**Issue by groogiam** [aspnet/Home#3208]
When creating a new Asp.Net core app in visual studio it is impossible to update the Microsoft.AspNetCore.All package to version 2.1.0.

The project was created referencing 2.0.8 of this package. When attempting to upgrade I get the following error.

Severity	Code	Description	Project	File	Line	Suppression State
Error		Package Microsoft.AspNetCore.All 2.1.0 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0) / win7-x64. Package Microsoft.AspNetCore.All 2.1.0 supports: netcoreapp2.1 (.NETCoreApp,Version=v2.1)			0	

I have the latest version of visual studio installed 15.7.3 and Nuget 4.6

There is no option in Visual studio to select netcoreapp2.1.

**Comment by Tratcher** [comment]
Have you installed the new SDK?

**Comment by Tratcher** [comment]
https://docs.microsoft.com/en-us/aspnet/core/migration/20_21?view=aspnetcore-2.1

**Comment by groogiam** [comment]
That's what I was missing. I was expecting to have this installed as part of Visual Studio.
