### ISSUE TITLE
This is killing me

### ISSUE THREAD

**Issue by Korporal** [aspnet/Home#3209]
I'm reading that I can create an ASP.NET Core wb app project that targets .Net Framework. However there have been numerous articles published over the past year that are either out of date or simply flat wrong.

One article said to edit the project.json file - then a little later I discover this is no longer used and we're back to good old *.csproj.

Anyway when I create a new ASP.NET Core web app I get no option to select a target framework (I've installed 2.1 too by the way).

Even after the project is created if I go to project properties then the Application pane the only options in Target framework dropdown list are .Net Core 1.0, 1.1, 2.0 and 2.1 - No sign anywhere of .Net Framework.

So perhaps one must manually edit the *.csproj file which is inexcusably sloppy if true.

I've said this before and so have others - this is a mess...

**Comment by davidfowl** [comment]
New Project -> Web -> ASP.NET Core Application:

![image](https://user-images.githubusercontent.com/95136/41114187-87f12534-6a38-11e8-81ef-94bee869850d.png)

.NET Framework:

![image](https://user-images.githubusercontent.com/95136/41114212-9e2c599a-6a38-11e8-98b8-9348b4b0cd2b.png)

Done

**Comment by davidfowl** [comment]
What options did you select when you installed VS 2017?

/cc @Andrew-MSFT @BillHiebert 

Any ideas?

**Comment by Korporal** [comment]
@davidfowl - I really can't recall, it was a year ago. Almost all work I do on this particular machine is conventional .NET Framework stuff MVC, desktop apps, console apps etc.

**Comment by Andrew-MSFT** [comment]
The Target Framework dropdown will be locked to .NET Core if you enter through the ".NET Core" node in the new project dialog.  If you enter through the "Web" entry point as shown in @davidfowl's screenshot, you will be able to choose between the two.

**Comment by narendra2605** [comment]
@Korporal: But if you select ".Net Framework" from the 1st dropdown, you are creating a .Net Framework Web App and not a .Net Core WebApp targeting .Net Framework. Hope you get it.

**Comment by Plasma** [comment]
Thank you @davidfowl and @Korporal -- I had the exact same experience trying to get started porting a large ASP.NET MVC app to .NET Core, targeting .NET Framework (to assist with porting).

Would really like to see a more thorough guide, including things like how to upgrade old controllers, utilize existing route code, etc, as I think each person/team is struggling independently and it would be good to have a central location to document a good bunch of the steps.

Thank you

**Comment by davidfowl** [comment]
> Would really like to see a more thorough guide, including things like how to upgrade old controllers, utilize existing route code, etc, as I think each person/team is struggling independently and it would be good to have a central location to document a good bunch of the steps.

https://docs.microsoft.com/en-us/aspnet/core/migration/proper-to-2x/?view=aspnetcore-2.1

Provide feedback on that document.
