### ISSUE TITLE
How to determine the corresponding Action to a route in a middleware

### ISSUE THREAD

**Issue by erlimar** [aspnet/Home#321]
I am writing a middleware, and accurate routing of services. I need to run this middleware before running the MVC, for the corresponding Action the route of HttpContext.

Something like:

```csharp
public async Task Invoke(HttpContext context, IServiceProvider services)
{
    var routes = services.GetService<IRouteCollection>();
    // ???
    await _next (context);
}
````
But this example does not work, how can I solve this problem?

**Comment by davidfowl** [comment]
You can't you need to run the in mvc pipeline to figure that out. Write an action filter instead

**Comment by erlimar** [comment]
Okay. That's what I feared. I was trying another alternative to filters. But at least now I know that there is no other way "official" to do this. Thank you very much.
