### ISSUE TITLE
Upgrading to .net core 2.1 breaks routing

### ISSUE THREAD

**Issue by hvaidya1** [aspnet/Home#3211]
We recently upgraded from .net core 2.0 to .net core 2.1 and mvc routing stopped working for all my projects. The error says "route not matched". The same code works with .net core 2.0
All my projects are console application. Self-hosted.
What is the breaking change and the reason behind this?

**Comment by nbalu** [comment]
I've experienced the same routing issue.

Fun fact:
My project files were self hosted all the time: Migrating to
 <Project Sdk="Microsoft.NET.Sdk"> made the routing error, while
<Project Sdk="Microsoft.NET.Sdk.Web"> fixed it

I'm curious what's the difference. I don't think that should cause any errors. As making my pipeline is exactly the same. { and a fileserver simple fileprovider middleware worked with a .Map(new PS("/files")) as a charm} Building the code should be as well. I'm not deploing my app so I'm not using publish or any other targets. Though Web is making something that console does not...

Some explanation guys?

Thanks,
Bálint

**Comment by pranavkm** [comment]
Following up on this issue here - https://github.com/aspnet/Mvc/issues/7882

**Comment by zoidhddhdd** [comment]
Following
