### ISSUE TITLE
Implicit dependencies VS explicit dependencies

### ISSUE THREAD

**Issue by Hippocrate** [aspnet/Home#322]
Hi people,

I started a vNext project and had some trouble to build my project. The problem was that for a strange reason, I had this error: 
>The type 'IConfiguration' exists in both 'Microsoft.Framework.ConfigurationModel.IConfiguration, ...' and 'Microsoft.Framework.ConfigurationModel.Interfaces ...l'.

Of course there is no duplication and the interface IConfiguration is declared once in Microsoft.Framework.ConfigurationModel.Interfaces.

I finally found out that it was because i hadn't referenced Microsoft.Framework.ConfigurationModel in my project.json. But the package was already implicitly referenced by another package. 
So I wonder how packages are referenced inside a vNext project. Is it normal that I have to explicitly declare all my required packages even if they are bring and referenced by another ones? And is it normal to have that kind of error ?

Thank's

**Comment by davidfowl** [comment]
That particular bug has nothing to do with dependencies declared in project.json. It's to do with the assembly neutral interface feature (which is going away).

As for dependencies, no, you don't have to declare dependencies that come transitively through referenced packages. That is, mvc -> mvc.core, if you depend on mvc then you don't have to explicitly reference mvc.core

**Comment by Hippocrate** [comment]
Ok, thank's for your answer
