### ISSUE TITLE
"dotnet new mvc" now ignores "--auth Individual" option, so does visual studio too

### ISSUE THREAD

**Issue by alexk8** [aspnet/Home#3223]
After some latest updates, it is impossible to create new project with individual authentication.
In the project gererated, there is nothing related to user accounts (no such things as: AccountController,ManageController, logon/sing-in functionality).

**Comment by SIkebe** [comment]
@alexk8 It's by design.
This might help you .
https://blogs.msdn.microsoft.com/webdev/2018/03/02/aspnetcore-2-1-identity-ui/

**Comment by SIkebe** [comment]
You have to scaffold necessary parts if you want to customize identity logic.

**Comment by alexk8** [comment]
ok, thanks, understood.
I think in that case, tools mentioned above should be updated to show a warning with that article...
thanks

**Comment by alexk8** [comment]
sorry, default functionanity is still there, but was hidden under "cookie use policy" bar, so I couldn see it and  messed up, sorry. The issue probably may be closed
