### ISSUE TITLE
Plan to develop a management tool similar to IIS on Linux?

### ISSUE THREAD

**Issue by muratg** [aspnet/Home#3226]
[This issue is moved from dotnet/core repo.  Original issue https://github.com/dotnet/core/issues/1672]

@JaneConan 
We can see that IIS on window has been able to host dotnetcore applications, but Linux can only rely on Kestrel. Do you have a development plan for Web service management tools of Linux?

@leecow 
Adding a few ASP folks that may have insight - cc @danroth27 @glennc

@Petermarcu 
@muratg can you move this to ASP.NET's repo for the conversation?

**Comment by muratg** [comment]
cc @DamianEdwards

**Comment by davidfowl** [comment]
We have no plans to do this. There are a variety of tools (some open source) that you could use to fill this gap when deploying to your own Linux machines:

- pivotal cloud foundry
- rancher
- open shift
- kubernetes

Or you could try using using docker.

**Comment by JaneConan** [comment]
Thx!We try to use it, thanks for sharing. Of course, it is still expected that Kestrel is becoming more and more perfect.

**Comment by JaneConan** [comment]
In fact, I would like to ask if I can consult if dotnetcore runs across a platform on Linux and can use Kestrel to mount some virtual applications and virtual directories like IIS to share session and more.

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
