### ISSUE TITLE
How to configure the max number of concurrent connections using WebListener?

### ISSUE THREAD

**Issue by nehmebilal** [aspnet/Home#3227]
I am using WebListener in ASP.Net Core as described [here](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/weblistener?view=aspnetcore-2.1). 

How can I configure the maximum number of concurrent WebSocket connections? 

It seems that the server starts dropping connections when I have more than a hundred connections.

**Comment by nehmebilal** [comment]
I think I found it:

```csharp
            var builder = new WebHostBuilder()
                .UseWebListener(options =>
                {
                    options.MaxAccepts = 1000;   
                }
```

**Comment by Tratcher** [comment]
No, you want MaxConnections.
https://github.com/aspnet/HttpSysServer/blob/1bbe161b4e5bc6d077b4862b2d3a7d3f2f42061d/src/Microsoft.AspNetCore.Server.HttpSys/HttpSysOptions.cs#L71
This was added in 2.0.0.

**Comment by Tratcher** [comment]
That said, there is no limit by default. If your system is dropping connections then it must be for another reason like resource limitations.

**Comment by nehmebilal** [comment]
So not available for WebListener? (1.2)

**Comment by Tratcher** [comment]
No, and it sounds like it wouldn't help you anyways.

**Comment by nehmebilal** [comment]
Yes, was just curious. Thanks.

**Comment by nehmebilal** [comment]
The connections we dropping because I was connecting too many connections at the same time (Task.WhenAll) during a load test. If I gradually ramp up the number of connections, it works fine.

**Comment by jjxtra** [comment]
I had the same problem. Why is Kestrel unable to accept a bunch of connections at the same time? Surely it can put some in the queue instead of just rejecting them...?
