### ISSUE TITLE
Session does not seem to be persisted across Http Requests

### ISSUE THREAD

**Issue by Etchelon** [aspnet/Home#3228]
Hello.
I've enabled Session in my aspnet core 2.1 app. To do this I followed the documentation, and have added
```
services.AddDistributedMemoryCache();
services.AddSession(options =>
{
	options.IdleTimeout = TimeSpan.FromHours(1);
	options.Cookie.HttpOnly = true;
	options.Cookie.Name = ".Nuvyta.Session";
});
```
and
```
app.UseSession();
```
Problem: at every REQUEST, <controller>.HttpContext.Session.Id is different and the session storage is reset.
What is wrong? The documentation isn't that complex and doesn't say much more...

p.s.: my colleague just found out that the Session is persisted from the moment that something is actually set into it. Otherwise if it's empty it's reset every time... ok you should at least say this in the docs...

**Comment by SIkebe** [comment]
Which documentation?

**Comment by Etchelon** [comment]
https://docs.microsoft.com/en-US/aspnet/core/fundamentals/app-state?view=aspnetcore-2.1&tabs=aspnetcore2x

**Comment by Tratcher** [comment]
Anything in the logs?

You only have one server instance, correct?

**Comment by Etchelon** [comment]
I searched the MessageTemplate property of the logs via this regex: /session/gi and couldn't find anything.
Anyway yeah, simple ASP.NET Core app from the VS2017 template. Add those 3 lines of code to enable the session and you'll see that in HomeController.Index, at every refresh of the webpage, HttpContext.Session.Id is different.
Unless in that method you do:
HttpContext.Session.Set("anything", new byte[0]);
In that case, the Session will persist.

**Comment by Tratcher** [comment]
Ah, that's expected. Empty sessions are not persisted.

**Comment by Tratcher** [comment]
@guardrex another note for https://github.com/aspnet/Docs/pull/7029

**Comment by Etchelon** [comment]
Ok I expected exactly that.
If it's in the docs sorry, otherwise it should be added imo. Took us a while to figure out the problem.
Regards.
