### ISSUE TITLE
Build error after upgrading to ASP.NET Core 2.1

### ISSUE THREAD

**Issue by jansokoly** [aspnet/Home#3229]
I have an existing ASP.NET Core project targeting .NET Core 2.0 and NuGet packages Microsoft.AspNetCore.All 2.0.8 and Microsoft.VisualStudio.Web.CodeGeneration.Design 2.0.8.

Now, when trying to upgrade to .NET Core 2.1, I do the following:

1. Upgrade target framework to .NET Core 2.1.
Rebuild OK.
1. Update NuGet package Microsoft.VisualStudio.Web.CodeGeneration.Design to 2.1.0.
Rebuild OK.
1. Update NuGet package Microsoft.AspNetCore.All to 2.1.0.
Rebuild fails with:
    > error MSB6006: "csc.exe" exited with code -1073741571.

There are no further details in Output window. How to track down what's wrong?

**Comment by SIkebe** [comment]
@jansokoly Did you check this?
https://docs.microsoft.com/en-us/aspnet/core/migration/20_21?view=aspnetcore-2.1#update-the-project-file-to-use-21-versions

>Replace the version specified "Microsoft.AspNetCore.All" package reference with the versionless "Microsoft.AspNetCore.App" package reference. You may need to add dependencies that were removed from "Microsoft.AspNetCore.All". See Migrating from Microsoft.AspNetCore.All to Microsoft.AspNetCore.App and Microsoft.AspNetCore.App metapackage. If you're targetting the .NET Framework:

**Comment by jansokoly** [comment]
Thanks for the link @SIkebe. I followed the migration guide, but problem still persists.

**Comment by SIkebe** [comment]
@jansokoly Is there any small repro app available?

**Comment by Eilon** [comment]
Hi. We're closing this issue as no response or updates have been provided in a timely manner and we have been unable to reproduce it. If you have more details and are encountering this issue please add a new reply and re-open the issue.
