### ISSUE TITLE
Invalidate existing authorization cookies

### ISSUE THREAD

**Issue by cbrianball** [aspnet/Home#3230]
I have a web application (ASP.NET Core MVC 1.1.6) hosted as an App Service in Azure. I have configured cookie authentication as follows:

In ConfigureServices(...): `services.AddAuthentication(
                SharedOptions => SharedOptions.SignInScheme = CookieAuthenticationDefaults.AuthenticationScheme);`

In Configure(...): `application.UseCookieAuthentication();`

This causes a session cookie to be issued to the browser once the user has authenticated (I'm using AAD for my authentication). It has recently come to my attention that some browsers will persist session cookies, even after the browser is closed. I will need to deploy code to require users to re-authenticate from time-to-time, but for right now, I'm hoping there's a way I can invalidate all auth cookies that have been previously issued without deploying new code (I'm not looking to delete them, I just want them to no longer be valid). Years ago with ASP.NET, I would have recycled the app pool, or changed the machine key in the web.config file to accomplish this. Is there anything similar I can do in ASP.NET Core?

**Comment by Tratcher** [comment]
Cookie auth has an event called OnValidatePrincipal which can be used to inspect the identity and decide to reject or re-issue it. You can put a security stamp claim into your identities and then rotate that claim as needed via config.

**Comment by Tratcher** [comment]
Worst case you can reset Data Protection (the new version of machine key). I'd have to track down where these are stored in azure.. https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/?view=aspnetcore-2.1

**Comment by Tratcher** [comment]
Ah, here:
https://github.com/aspnet/DataProtection/blob/fb2f89ed5194fac3ed2bfa1e816d310347cb462c/src/Microsoft.AspNetCore.DataProtection/Repositories/DefaultKeyStorageDirectories.cs#L86-L99

**Comment by cbrianball** [comment]
@Tratcher So, in theory, if I were to delete the folder used in Azure to store the keys, it will invalidate all existing cookies -- correct? Also, thanks for the info about `OnValidatePrincipal`, that sounds like exactly where I need to add my code to re-validate users from time-to-time.

**Comment by cbrianball** [comment]
@Tratcher I verified that deleting the XML files located at %HOME%\ASP.NET\DataProtection-Keys, then restarting the app service caused existing auth cookies to no longer be valid. In my cause, users will automatically get redirected to login. Thanks!
