### ISSUE TITLE
CORS issue whe sending only a file from Js.

### ISSUE THREAD

**Issue by ManuelDev1810** [aspnet/Home#3236]
Have one of you guys have problem about sending files with asp.net core 2.0 or 2.1, I mean i did it great with razor and all were fine, but now I am sending a file with js,   and I don't why throw that is not allowed CORS... I don't know why because all the other actions works fine with the  cors defined.

Configure Services

```c#
    services.AddCors(options => {
                options.AddPolicy("AllowAllOrigin", builder =>
                builder.WithOrigins("http://localhost:3000")
                    .AllowAnyHeader()
                    .AllowAnyMethod()
                    .AllowCredentials()
                );
            });
```

Configure

`app.UseCors("AllowAllOrigin");`

Action

```c#
        [EnableCors("AllowAllOrigin")]
        [Route("img")]
        [HttpPost]
        public async Task<IActionResult> CreateImg(IFormFile file)
        {
            if (file.Length != 0)
            {
                var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/Img", file.FileName);

                using (var stream = new FileStream(path, FileMode.Create))
                {
                    await file.CopyToAsync(stream);
                }
                return Ok(file);
            }
            return BadRequest();
        }

```
I get the file, but when goes to use the  

```c#
 using (var stream = new FileStream(path, FileMode.Create))
      {
                    await file.CopyToAsync(stream);
     }
```

 throw not allowed CORS
Sorry it is kind of big
All the others action works fine with the cors defined, but i dont get why with the file throw me not allowed by CORS

`
No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access. The response had HTTP status code 500.
`

JS

```js
 let file = this.logo.files[0]
        let data = new FormData()
        data.append('file', file)
        let img = {
            method: 'POST',
            body: data
        }
        await fetch('https://localhost:44365//api/home', img);
```

How i told you, i get the file in the action, but when goes to
```c#
 using (var stream = new FileStream(path, FileMode.Create))
      {
                    await file.CopyToAsync(stream);
     }
```
Throw the exception.

--------------

I really don't why because all the other actions works fine with the  cors defined.

**Comment by pranavkm** [comment]
@ManuelDev1810 can you try setting the log level to the most verbose level (https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging) and see what the `CorsService` spits out?

**Comment by mkArtakMSFT** [comment]
Hi. We're closing this issue as there's been no response and we have been unable to reproduce it. If you have more details and are encountering this issue please add a new reply and re-open the issue.
