### ISSUE TITLE
There was a problem when I linked to the page in area

### ISSUE THREAD

**Issue by chukaifeng** [aspnet/Home#3237]
I am leaning to use .net core, i created a MVC project based on .net core2.1。

I created a new area called “BaseSetting”， then created a new Controller called “Prov” and linked a page to Home/Index with codes: @Url.Action("Index","Prov",new{area="BaseSetting"})

But，when i click this link，link jump to url：http://localhost/TestSite/Prov?area=BaseSetting，and site can't find this page。
The Problem is “Why ‘BaseSetting’ didn't appear in front of ’/Prov‘”，but appears in query string parameters？Can anyone help me？

**Comment by smokedog2** [comment]
see: https://www.codeproject.com/Articles/1182253/Areas-in-ASP-NET-Core

**Comment by chukaifeng** [comment]
@smokedog2 thanks, i have found the problem, the area route setting must write before the default route setting, when i write it behind the default setting, area link can't work.
