### ISSUE TITLE
Does the IServiceProvider is singleton in asp net core?

### ISSUE THREAD

**Issue by rocketRobin** [aspnet/Home#3240]
when I write a service, I need to dynamic create a "Handler" and in this scene, should I can write like this?

    public class WorkflowService : IWorkflowService
    {
        private readonly IServiceProvider _provider;
        public WorkflowService( IServiceProvider provider)
        {
            _provider = provider;
        }

Workflow service will be singleton 

thanks very much!

**Comment by davidfowl** [comment]
Yep. That's fine.

**Comment by rocketRobin** [comment]
thank you very much!
