### ISSUE TITLE
.NET Core 2.1.1 released to nuget but no SDK/Runtime so error on run in VS.net

### ISSUE THREAD

**Issue by JohnGalt1717** [aspnet/Home#3241]
Where is the SDK for .NET Core 2.1.1?  You guys shouldn't be releasing packages to nuget until updates are ready on dot.net.

**Comment by RichardD2** [comment]
Exactly the same problem here. Why are the 2.1.1 packages even being offered to a site that's targeting 2.1.0 if they're just going to break it?

At least the new project file format makes it easier to downgrade, since you can't even do that from the package manager within Visual Studio.

**Comment by emasyakin-softheme** [comment]
Following steps allowed me to get going on Win x64 platform:
- Remove previous 2.1 sdk installation
- Install early access SDK from here: https://github.com/dotnet/versions/tree/7a833dddfddc27f2074b755b94234a25b9757637/build-info/dotnet/product/cli/release/2.1

**Comment by emasyakin-softheme** [comment]
Following steps allowed me to get going on Win x64 platform:

- Remove previous 2.1 sdk installation

- Install early access SDK from here: https://github.com/dotnet/versions/tree/7a833dddfddc27f2074b755b94234a25b9757637/build-info/dotnet/product/cli/release/2.1

- Changed version of docker images to explicitly reference 2.1.301 version
e.g. FROM microsoft/dotnet:2.1.301-sdk AS build

**Comment by garethrampton** [comment]
@emasyakin-softheme Thanks.

I ended up using the version from here https://github.com/dotnet/versions/tree/master/build-info/dotnet/product/cli/release/2.1 which appears to be the RTM version anyway.

No need to uninstall previous SDK versions.

Just wish the ASP.NET Core team would get their act together with this kind of stuff.... and don't even get me started on the messed up versioning thats floating around the entire ecosystem.

**Comment by JohnGalt1717** [comment]
That's still the preview release.  If you install it you'll have to do the purge.

**Comment by garethrampton** [comment]
Pretty sure that isn't the preview. The version certainly doesn't indicate it is: 2.1.301. I'm up and running with no purge required.

**Comment by JohnGalt1717** [comment]
Look at the file name you posted and tell me if it's the preview....  You WILL need a purge when the real final version is released.

**Comment by garethrampton** [comment]
Assuming nothing changes, then that build will indeed be the final build. (see notes here: https://github.com/aspnet/Home/wiki/.NET-Core-2.1.1-Early-Access-Downloads)

The final SDK version does appear to be available to download - just not published on the front-facing websites. For example, VSTS will happily download and use the full SDK if asked from here: https://dotnetcli.azureedge.net/dotnet/Sdk/2.1.301/dotnet-sdk-2.1.301-win-x64.zip

**Comment by FlorianRainer** [comment]
Is there a new date for the release of 2.1.1 related SDK / Runtime?

The last announcement with date is this: https://github.com/aspnet/Home/wiki/.NET-Core-2.1.1-Early-Access-Downloads (June 19th)

**Comment by JohnGalt1717** [comment]
Still the same preview.

**Comment by Tratcher** [comment]
The 2.1.1 deployment is still in progress, please use 2.1.0 in the meantime.

**Comment by FlorianRainer** [comment]
Any predictions? Today, Tomorrow, in a Week?
It's because i'm on the way to port 2.0 to 2.1 and the plan was to wait and to use 2.1.1, now it depend on the estimated release date

**Comment by RichardD2** [comment]
Looks like it's out now:

> **Damian Edwards:**
> #dotnetcore 2.1.1 SDK download is now live!! Thanks everyone for your patience as we worked through the deployment issues the last few days
> https://twitter.com/DamianEdwards/status/1009932641460580352

**Comment by JohnGalt1717** [comment]
Woot!
