### ISSUE TITLE
ASP.NET Core 2.1 Web API wont start with Microsoft.AspNetCore.All 2.1.1

### ISSUE THREAD

**Issue by leecow** [aspnet/Home#3245]
Issue moved from https://github.com/dotnet/core/issues/1712. Opened by @poteb

ASP.NET Core 2.1 Web API wont start with Microsoft.AspNetCore.All 2.1.1

I'm debugging my Web API from VS 2017 (15.7.1) and it's working with Microsoft.AspNetCore.All 2.1.0.
But if I update Microsoft.AspNetCore.All to 2.1.1 it wont start up. It doesn't even give me an exception, the console window flashes briefly and then the debugger detaches. Downgrading to 2.1.0 fixes this. No help in Windows event log.

dotnet --info
.NET Core SDK (reflecting any global.json):
Version: 2.1.300
Commit: adab45bf0c

Runtime Environment:
OS Name: Windows
OS Version: 10.0.15063
OS Platform: Windows
RID: win10-x64
Base Path: C:\Program Files\dotnet\sdk\2.1.300\

Host (useful for support):
Version: 2.1.0
Commit: caa7b7e2ba

.NET Core SDKs installed:
1.1.0 [C:\Program Files\dotnet\sdk]
2.0.0 [C:\Program Files\dotnet\sdk]
2.0.2 [C:\Program Files\dotnet\sdk]
2.1.200 [C:\Program Files\dotnet\sdk]
2.1.300 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
Microsoft.AspNetCore.All 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
Microsoft.AspNetCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.NETCore.App 1.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 1.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 2.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

**Comment by WieserSoftware** [comment]
I'm seeing a similar thing.

I manually installed the runtime for 2.1.1
  Microsoft.NETCore.App 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
but now I'm seeing this:
MPC> It was not possible to find any compatible framework version
MPC> The specified framework 'Microsoft.AspNetCore.All', version '2.1.1' was not found.
MPC>   - Check application dependencies and target a framework version installed at:
MPC>       C:\Program Files\dotnet\
MPC>   - Installing .NET Core prerequisites might help resolve this problem:
MPC>       http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
MPC>   - The .NET Core framework and SDK can be installed from:
MPC>       https://aka.ms/dotnet-download
MPC>   - The following versions are installed:
MPC>       2.1.0 at [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]

**Comment by neridonk** [comment]
The runtime seems to be only in the Microsoft.NETCore.App folder but not in Microsoft.AspNetCore.All

**Comment by WieserSoftware** [comment]
A similar error occurs when using the nuget package for Microsoft.ASPNetCore.App instead of .All

**Comment by Tratcher** [comment]
Release 2.1.1 is still being deployed, please use 2.1.0 instead.

**Comment by poteb** [comment]
The newest SDK (2.1.301) released today fixed my issue.

**Comment by phillijw** [comment]
I'm encountering this issue with 2.1.1 and 2.1.2

**Comment by Eilon** [comment]
Closing this because it appears people have gotten this working. If anyone is still having a problem, please log a new issue with details and we will investigate. Thanks!
