### ISSUE TITLE
ModelBinding error with boolean values

### ISSUE THREAD

**Issue by leecow** [aspnet/Home#3246]
Issue moved from https://github.com/dotnet/core/issues/1711, opened by @WinthorpeCross

I have a potential problem with the ModelBinder in my ASP.NET Core  2.0 project.  I have the following 'Index' controller action:
```
[HttpGet]
public async Task<IActionResult> Index(SortFilterIndexOptions options) { ... }
```
The SortFilterIndexOptions are four parameters defined in the following class:

```
public class SortFilterIndexOptions
{
    public int SelectedBirdId { get; set; }
    public bool ShowAll { get; set; }
    public bool ShowInTable { get; set; }
    public int page { get; set; }
}
```
These enable the user to filter a paged index page using checkbox toggle buttons.

Everything works until I change 'ShowAll' bool member to TRUE and then try to navigate to a different page. The 'ShowAll' parameter part of the url then contains two bool values ('ShowAll=true, false'):

![screeshot](https://user-images.githubusercontent.com/35421339/41627649-0a0b992a-7419-11e8-8a51-082a1dcbfa1c.jpg)

which of course results in a parse error ('FormatException: String was not recognised as a valid Boolean').

My understanding that the ModelBinder in ordinary MVC automatically parses the TRUE from the true,false.

It only happens when the 'ShowAll' parameter is toggled to TRUE.

**Comment by Eilon** [comment]
This issue was moved to aspnet/Mvc#8043
