### ISSUE TITLE
System.TypeLoadException: 'Could not load type 'System.Runtime.Remoting.Messaging.ILogicalThreadAffinative' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.'

### ISSUE THREAD

**Issue by leecow** [aspnet/Home#3247]
Issue moved from https://github.com/dotnet/core/issues/1702, opened by @periyasamyt

I have created a web API project in .Net core. when I included some assemblies developed in .Net Framework 4.0, I am getting following error. Please help me with this.

System.TypeLoadException: 'Could not load type 'System.Runtime.Remoting.Messaging.ILogicalThreadAffinative' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.'

**Comment by hishamco** [comment]
This is duplicate for #3235
