### ISSUE TITLE
.net core 2.0 angular default app IIS deploy to server failing with 502.3 error

### ISSUE THREAD

**Issue by leecow** [aspnet/Home#3248]
Issue moved from https://github.com/dotnet/core/issues/1694, opened by @jagindia

I am using Visual studio 2017  default angular app.
I have also installed DotNetCore.2.0.8-WindowsHosting.exe on local machine as well as remote server.

Information at https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/?view=aspnetcore-2.1&tabs=aspnetcore2x is really not clear enough for beginners. Am I supposed to change BuildWebHost methos? 

My BuildWebhost code  - 

```c#
  public static IWebHost BuildWebHost(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .UseStartup<Startup>()
                .Build();
```

I was able to deploy the default app (as is) to IIS on local machine, but when I copy Publish Profile (from bin\release\PublishOutput folder) to the remote server and connect it to IIS with No Managed code app pool setting, it throws below error (captured in Failed Request tracing)

```xml
 <EventData>
  <Data Name="ContextId">{80000004-0002-E300-B63F-84710C7967BB}</Data>
  <Data Name="ModuleName">AspNetCoreModule</Data>
  <Data Name="Notification">128</Data>
  <Data Name="HttpStatus">502</Data>
  <Data Name="HttpReason">Bad Gateway</Data>
  <Data Name="HttpSubStatus">3</Data>
  <Data Name="ErrorCode">2147942413</Data>
  <Data Name="ConfigExceptionInfo"></Data>
 </EventData>
```

In fiddler Response Header is -

```
HTTP/1.1 502 Bad Gateway
Content-Type: text/html
Server: Microsoft-IIS/8.5
X-Powered-By: ASP.NET
Date: Thu, 14 Jun 2018 17:33:23 GMT
Content-Length: 1477
```

And error is - 

```html
<h2>502 - Web server received an invalid response while acting as a gateway or proxy server.</h2>
  <h3>There is a problem with the page you are looking for, and it cannot be displayed. When the Web server (while acting as a gateway or proxy) contacted the upstream content server, it received an invalid response from the content server.</h3>
```

There are no errors found in Event Viewer. It says
Application 'MACHINE/WEBROOT/APPHOST/TEST' started process '6844' successfully and is listening on port '13118'.

Also, I am not able to capture the stdoutlogs, somehow it's not registering. I have enabled it on web.config file stdoutLogEnabled="true"  and given the permission to the logs folder at root directory to the specific apppool. 

Please help. 
Thanks.

**Comment by Eilon** [comment]
Hi @jagindia, were you able to get this figured out? Do you have any additional information you can share?

**Comment by Eilon** [comment]
Hi. We're closing this issue as no response or updates have been provided in a timely manner and we have been unable to reproduce it. If you have more details and are encountering this issue please add a new reply and re-open the issue.
