### ISSUE TITLE
Remotion.Linq is missing from myget feed.

### ISSUE THREAD

**Issue by Dopare** [aspnet/Home#325]
Entitity Framework packages of version beta4-* depend on Remotion.Linq package but this package does not exist in myget feed. Please add this package to the feed.

'Unable to locate Remotion.Linq >= 2.0.0-alpha-002' kpm restore error

**Comment by Praburaj** [comment]
This package exists in nuget.org. Please enable your nuget feed and try `kpm restore`. 

http://www.nuget.org/packages/Remotion.Linq/2.0.0-alpha-002

**Comment by Eilon** [comment]
According to https://github.com/aspnet/Home/issues/325 this might indicate that you're missing a NuGet feed. Check that you have the nuget.org feed enabled.
