### ISSUE TITLE
Which version do I use ?

### ISSUE THREAD

**Issue by karelz** [aspnet/Home#3251]
_From @Bridgeway on June 21, 2018 12:32_

Given the potential problems with nuget dependencies and IIS Express not always working properly with Kestrel, is there a rule of thumb regarding which version of AspNetCore2.1.x versions to install ?

For example if I install Microsoft.NETCore.App (2.1.0-preview1-26216-03 should I also only install the exact same version of the entity framework core packages, e.g:

Microsoft.EntityFrameworkCore.SqlServer(2.1.0-preview1-final).

_Copied from original issue: dotnet/corefx#30576_

**Comment by Tratcher** [comment]
Release 2.1.1 is still being deployed, please use 2.1.0 instead.
