### ISSUE TITLE
IHttpContextAccessor.HttpContext.Session - Not Persisting for User

### ISSUE THREAD

**Issue by DanJ210** [aspnet/Home#3252]
I originally posted for help with this thread here, https://github.com/aspnet/Docs/issues/7182. 'cc/ @guardex' Was helping me initially and suggested I post here with a repo.

I created a repo. https://github.com/DanJ210/APIAuthSessionState/tree/master/sky-api-sample-application. The main thing missing from this code is the appsettings.Development.json which has my sensitive keys to authenticate with the API I'm eventually trying to use. So it would be hard for someone to run the application entirely. The code is simple and small thought and it's using Session in a way that many docs and samples show to use it.

Basically the AuthenticationController I have starts calling on the Auth API Enpoint and uses the ISessionService to store the token keys and then retrieve those keys from the Auth API responses. Well storing works fine but when I try to retrieve those tokens, the session ID is different and the token keys are not there, the store is empty. Somehow the session is being renewed or something when the application isn't starting or stopping. From everything I've read, the session is supposed to be different but persist for each user using the application.

There is a ITestService that I was using just to test out session persistence and I'm able to store and retrieve values but somewhere for some reason a new session is being created and I cannot figure out why because the session should be the same, from what I understand.

Any help is much appreciated.

**Comment by Tratcher** [comment]
Your overall design is convoluted enough that it's hard to say what's going on just looking at code. Here are a few notes:

A) Do not store auth data in Session, Session is not strongly associated with login and logout events.
B) It's not clear why you depend so heavily on IHttpContextAccessor. Most places you use it the HttpContext could be passed in as a parameter. Aoid IHttpContextAccessor whenever possible.
C) Use shared HttpClient instances, not single use (https://github.com/DanJ210/APIAuthSessionState/blob/5e58f7ec44d13e783ece218b9ddcfd84134a4ab5/sky-api-sample-application/Services/AuthenticationService.cs#L33).
D) The auth tokens you're storing in session do not appear to be user/session specific. Why store them in session? https://github.com/DanJ210/APIAuthSessionState/blob/5e58f7ec44d13e783ece218b9ddcfd84134a4ab5/sky-api-sample-application/Services/AuthenticationService.cs#L33-L52 MemoryCache may be more appropriate.

**Comment by DanJ210** [comment]
The Auth tokens are user specific. We want session only tokens. Each user is granted different tokens so MemoryCache would persist too long and globally, not good. The Login and Logout events aren't the normal user credential login/logout events that it may seem like. Just what events the procedures are associated with. Session is perfect in this case.

The overall design of the code is suggested by engineers above me so I can pass along the remarks but to me it looks pretty clean and well done. I figured out how it was all working by looking at the code and it is rather straight forward. There's not a lot going on. Storing and getting from Session is in the `SessionService`.

Sure I could try passing in `HttpContext` as a parameter but from what I understand is that I shouldn't have to and I'm supposed to avoid that as much as possible to adhere to best practices. I don't see why the session isn't persisting. The `AuthenticationController` will use the `AuthenticationService` which uses the `SessionService`. The `ConstituentsController` or the `ConstituentsService` won't work without the tokens from the session store. The `TestService` can be ignored as well. I'll even clean the repo up, my apologies.

That leaves a few main pages with only a few methods to follow. `Startup`, `AuthenticationController`, `AuthenticationService` and `SessionService`. So four files. Startup just shows the proper setup of using Session. The `AuthenticationService` and `SessionService` are the main ones using, storing and getting from the Session. But what's being stored is not there when the request to get is called.

**Comment by Eilon** [comment]
@DanJ210 were you able to make any further progress on this? Could it be that the user sessions are expiring or being purged due to their size?

Also, as far as passing around `HttpContext`, that is absolutely considered the best practice. `IHttpContextAccessor` is more for scenarios where that just isn't an option due to other design constraints of a system (e.g. legacy code). But for new code, passing around the context itself is highly recommended.

**Comment by Eilon** [comment]
Hi. We're closing this issue as no response or updates have been provided in a timely manner and we have been unable to reproduce it. If you have more details and are encountering this issue please add a new reply and re-open the issue.

**Comment by Eilon** [comment]
@DanJ210 got it. If you do figure out what was up or have more info on how to reproduce this please log a new issue so we can investigate.

**Comment by DanJ210** [comment]
@Eilon Ok I will. I did upload the project to a repo so it's showing exactly everything I was doing and it wasn't anything major. That project could reproduce the issue I was running into. Somehow it seems like the store was getting disposed of and recreated when I didn't think it should be and the engineers who designed it felt like it shouldn't have either. But idk.

**Comment by DanJ210** [comment]
Thanks for all the help.
