### ISSUE TITLE
Ammending the request pipeline with WebApplicationFactory

### ISSUE THREAD

**Issue by chris-brown** [aspnet/Home#3254]
> https://github.com/aspnet/Docs/issues/7203

Im trying to create a integration test for my Exception handling middleware  How do you add to the existing `ApplicationBuilder` with WebApplicationFactory?

Im using `WebApplicationFactory<T>` with my `Startup.cs` and I want to add an additional middleware to the request pipeline so I can mimic a error response. 

The example below completely overrides my Startup which is not the desired result. I noticed builder has the following extension methods `ConfigureTestServices()` and `ConfigureTestContainer()` but there doesnt appear to be an equivilant to configure the request pipeline thats under test.

```cs
_client = fixture.WithWebHostBuilder(builder =>
{
   builder.Configure(app =>
   {
      app.Map("/error", a => a.Run(c => throw new Exception("My error message")));
   });
}).CreateDefaultClient();
```

Perhaps I could use a `IStartupFilter` which throws at the end of the request pipeline. But im not sure how I could get that to invoke after my middleware.

This seems to do it but its alot of boiler plate. I'm hoping im missing something obvious.

```cs
    public class ErrorsController : Controller
    {
        [Route("Error")]
        public IActionResult Error() => throw new Exception();
    }

    public class ExceptionMiddlewareTests : IClassFixture<WebApplicationFactory<Startup>>
    {
        private readonly HttpClient _client;

        public ExceptionMiddlewareTests(WebApplicationFactory<Startup> fixture)
        {
            _client = fixture.WithWebHostBuilder(builder =>
            {
                builder.ConfigureTestServices(collection =>
                {
                    var mvc = collection.AddMvc();
                    var parts = mvc.PartManager.ApplicationParts;
                    parts.Clear();
                    parts.Add(new AssemblyPart(typeof(Startup).GetTypeInfo().Assembly));
                    parts.Add(new AssemblyPart(GetType().Assembly));
                });
            }).CreateDefaultClient();
        }
        // ...
```

**Comment by chris-brown** [comment]
@ardalis @javiercn @guardrex hoping either of you can point me in the right direction?

**Comment by ardalis** [comment]
You have to subclass `WebApplicationFactory<T>` so that you can override its protected method `ConfigureWebHost` as shown here: https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-2.1#customize-webapplicationfactory

**Comment by chris-brown** [comment]
Can you provide an example @ardalis as the following doesnt work.

```cs
   public class MiddlewareTestFixture : WebApplicationFactory<Startup>
    {
        protected override void ConfigureWebHost(IWebHostBuilder builder)
        {
            // this line prevents Startup.Configure from firing
            builder.Configure(app =>
            {
                app.Map("/error", applicationBuilder => { applicationBuilder.Run(_ => throw new Exception()); });
            });
            base.ConfigureWebHost(builder);
        }
    }

    public class Test : IClassFixture<MiddlewareTestFixture>
    {
        private readonly HttpClient _client;

        public Test(MiddlewareTestFixture fixture)
        {
            _client = fixture.CreateClient();
        }

        [Fact]
        public async Task Me()
        {
            var result = await _client.GetAsync("/error");
            result.StatusCode.ShouldBe(HttpStatusCode.InternalServerError);
        }
    }
```

As soon as I use `builder.Configure(app => ... ` then `Configure` in my `Startup.cs` does get executed. Im trying to add to the existing request pipeline that was defined in my startup.

**Comment by ardalis** [comment]
You're correct that any call to builder.Configure will override Startup.Configure.  I think you might want to try a different approach, such as specifying an environment (e.g. Testing) and in Startup checking that environment and modifying the request pipeline accordingly. Alternately, just create a controller action that you know throws an exception and hit that in your test.

**Comment by javiercn** [comment]
The controller action or the custom environment are the ways to go. Getting in the middle of the pipeline through the use of services is not possible.
