### ISSUE TITLE
ASP.NET Core Service Starting and then Stopping Immediately

### ISSUE THREAD

**Issue by anantkgoyal** [aspnet/Home#3256]
The ASP.NET Core Windows Service is starting and then stopping immediately.

I've developed an ASP.NET Core Application with full framework (my target framework is net461).

This works as a standalone application when I use the Run() function on the WebHost. However, when I use the RunAsService(), the service starts but then immediately shuts down with the error -

> The service on Local Computer started and then stopped. Some services stop automatically if they are not in use by other services or programs.

I even tried to to implement override the OnStarting, OnStarted and OnStopping functions given by the documentation here. I added in try-catch blocks around all of the base calls and logging on each of the functions. Only the OnStarting function is called. No exceptions are thrown.

I have tried adding in the RuntimeIdentifier corresponding to the server on which I am running this service. I have even added in the RuntimeIdentifiers tag with all the possible identifiers for windows.

Nothing is logged in the event viewer currently.

**Comment by parthakbari** [comment]
@anantkgoyal  Got the solution : ) MicroSoft use by Default 5000 port and same port is in using for different purpose in my IIS so, service not keeping in started state. Check at your end

**Comment by parthakbari** [comment]
I think, They need to give error message if port is using or not. hope, there are consider this as feature request and improve in next version. Wastage by 1.5 Day.

![capture](https://user-images.githubusercontent.com/3718529/41907145-9a6b098a-795d-11e8-9977-095d02842d89.PNG)

**Comment by anantkgoyal** [comment]
I don't seem to have code similar to that. However in the program.cs file, I am specifying the RunOnUrl value which specifies the port I want to run it on.

**Comment by parthakbari** [comment]
@anantkgoyal  i don't think it will help you because they have provided static. See above image. if its work then let me know mate.

**Comment by parthakbari** [comment]
@anantkgoyal  did you find the issue? if yes then, can you please share

**Comment by Eilon** [comment]
Closing because it is not clear that any further action is required on this issue.
