### ISSUE TITLE
Dependency Injection - Same service type are able to be registered into Service Collection multiple times 

### ISSUE THREAD

**Issue by rthm93** [aspnet/Home#3258]
### Title
Dependency Injection - Same service type are able to be registered into Service Collection multiple times 

### Functional impact
Multiple instance of the same service type will be instantiated when we call service provider GetServices<ServiceType> when the same service type was registered multiple times.

### Minimal repro steps
Please refer to this [gist](https://gist.github.com/rthm93/f41624231b11615d1f3b798db6cb2cbc)

### Expected result
I should have only 1 instance of SomeManager since it is the same type.

### Actual result
service will contain 2 instances of SomeManager.

**Comment by Tratcher** [comment]
What makes you think you get more than one instance? It should only use the last registration.

Also, there's a mechanic for resolving `IEnumerable<SomeManager>` to get all possible instances.

**Comment by Tratcher** [comment]
Ah, I just realized you were calling GetServices and not GetService. If you call GetService you get the last instance. GetServices returns all instances.

**Comment by rthm93** [comment]
If returning multiple instances of the same type is the correct behaviour, are there any reason to allow multiple registration for the same type?

**Comment by Tratcher** [comment]
Here's an example:
https://github.com/aspnet/Hosting/blob/3b488c470a0612382d7ca85bac2678a44c5c7ae4/src/Microsoft.AspNetCore.Hosting/Internal/HostedServiceExecutor.cs#L18
All instances of IHostedService are resolved and each are executed. This allows you augment functionality by adding another instance without replacing all prior functionality.

**Comment by DotNetSparky** [comment]
I think it's the fact that he registered the same *implementation* type multiple times and expected it would be filtering out those dupes.  IHostedService is a good example of why it doesn't do such filtering, there are times where you might want to instantiate the same class multiple times (I've done this before, I believe, each one was an additional consumer/processor of a task queue).

**Comment by rthm93** [comment]
I see... So this is not an issue then.
Thanks for explaining.
