### ISSUE TITLE
Controller cache attribute in asp net core?

### ISSUE THREAD

**Issue by ChristopherRobinSuperStar** [aspnet/Home#3259]
Is it possible to use [ResponseCache()] attribute with SqlDependency and ServiceBroker in asp net core 2.1?
If it's not, please add this feature. It was very useful in asp net mvc earlier:
```
[OutputCache(Duration = Int32.MaxValue, SqlDependency = "DBNAME:DEPENDENCY_TABLE_NAME", Location = System.Web.UI.OutputCacheLocation.Server)]
public ActionResult Index()
{
}
```

**Comment by pranavkm** [comment]
@JunTaoLuo \ @Tratcher is this something you could do with the response cache middleware?

**Comment by Tratcher** [comment]
Certainly not at the moment. I'm not even quite sure how you'd implement that.

**Comment by Eilon** [comment]
This issue was moved to aspnet/Mvc#8042
