### ISSUE TITLE
My grunt-bower-task can't read bower.json when created from VS2015

### ISSUE THREAD

**Issue by sebastianbk** [aspnet/Home#326]
When I create the bower.json file from VS2015 Preview then my grunt-bower-task is unable to read the file. When I create the file from outside of VS, everything works fine.

I recorded the issue here. You can find the screencast here (2m 30s): http://youtu.be/x4QLXgGQUJo

**Comment by madskristensen** [comment]
This has been fixed and the fix will be in the next update to VS2015. The issue is caused by VS automatically adding a BOM to the file. Bower doesn't support that.

**Comment by sebastianbk** [comment]
Cool! Thanks a lot for the quick reply! :-)
