### ISSUE TITLE
Dependency Injection - Different projects have different registered services

### ISSUE THREAD

**Issue by Haythem** [aspnet/Home#3260]
### Title
Dependency resolution has different services depending on the project from which the `IServiceProvider.GetRequiredService` is called.

### Functional impact
Registered services in the startup project cannot be resolved in a dependent project inside the same solution.

### Minimal repro steps
- WebProject
  - Type                : AspNet Core Web Project
  - Dependencies : Project A, Project B
- Project A
  - Type                : Net Standard Class Library
- Project B
  - Type                : Net Standard Class Library
  - Dependencies : Project A

The **Project A** has a `AddProjectA(this IServiceCollection services)` in which I scan assemblies and register dynamically (using reflection) found services as **Transient** (The resolutions can potentially be found in **Project B** referenced in the **WebProject**).

In the **Web Project**'s `Startup`, I call `AddProjectA()`, and when debugging I saw that the service collection has the dynamically found dependencies. Now, in **Project A**, I inject the `IServiceProvider` and try to resolve (`IServiceProvider.GetRequiredService`) one of those **Transient** services (registered previously dynamically) in order to invoke the methods inside of it. The problem is that I can't see any of those dependencies when debugging **Project A** but I was able to resolve them in the **WebProject** 

### Expected result
`DependencyInjection` container should be able to resolve registered services from any project in the solution.

### Further technical details
`dotnet --info`
```
Version:   2.1.301

Runtime Environment:
OS Name:     Windows
OS Version:  10.0.17134
OS Platform: Windows
RID:         win10-x64
Base Path:   C:\Program Files\dotnet\sdk\2.1.301\
```

Thanks in advance.

**Comment by davidfowl** [comment]
It sounds like it could be an issue with how you are loading the assemblies. Can you show that logic?

**Comment by Haythem** [comment]
@davidfowl, Thank you for your reactivity.

> It sounds like it could be an issue with how you are loading the assemblies. Can you show that logic?

Yeah, sure. I'll try to push to a repository today.

**Comment by Haythem** [comment]
After some more digging, it appeared that the problem was that the resolution was done using concrete types (not interfaces) due to a flaw in the reflection algorithm. My bad, sorry for the inconvenience.

I'm closing this down.
