### ISSUE TITLE
Extension methods for DI

### ISSUE THREAD

**Issue by petterek** [aspnet/Home#3262]
Suggestion for extrension methods.. :) 

To ease the use of factory methods I suggst the following extension methods to be added

```
public static IServiceCollection AddTransient<TService, TDep1>(this IServiceCollection services, Func<TDep1, TService> implementationFactory) where TService : class
        {
            return services.AddTransient<TService>((serviceProvider) =>
            {
                var dep1 = serviceProvider.GetRequiredService<TDep1>();
                return implementationFactory(dep1);
            });
        }
public static IServiceCollection AddTransient<TService, TDep1, TDep2>(this IServiceCollection services, Func<TDep1, TDep2, TService> implementationFactory) where TService : class
        {
            return services.AddTransient<TService>((serviceProvider) =>
            {
                var dep1 = serviceProvider.GetRequiredService<TDep1>();
                var dep2 = serviceProvider.GetRequiredService<TDep2>();
                return implementationFactory(dep1, dep2);
            });
        }
```

Could be extended to as many needed dependencies as you want

**Comment by petterek** [comment]
## Usage
```
services.AddSingleton<Microsoft.AspNetCore.Http.IHttpContextAccessor,Microsoft.AspNetCore.Http.HttpContextAccessor>();

services.AddTransient<ClientContext, IHttpContextAccessor>(httpContext => {})
            
```

**Comment by khellang** [comment]
I don't see how those could be added without being ambiguous? There's already [extension methods](https://github.com/aspnet/DependencyInjection/blob/9732ad87e590401a8005c378d94723cfa522c11c/src/DI.Abstractions/ServiceCollectionServiceExtensions.cs#L173-L202) taking two generic arguments, `TService` and `TImplementation` and a `Func<IServiceProvider, TImplementation>` factory method?

**Comment by petterek** [comment]
Possible.. It's working in my soulution :)

**Comment by khellang** [comment]
I guess that's because [Closer is better](https://ericlippert.com/2013/12/23/closer-is-better). Have you tried putting it in the `Microsoft.Extensions.DependencyInjection` namespace?

**Comment by petterek** [comment]
```
namespace Microsoft.Extensions.DependencyInjection
{
    public static class Ext
    {
        public static IServiceCollection AddTransient<TService, TDep1>(this IServiceCollection services, Func<TDep1, TService> implementationFactory) where TService : class
        {
            return services.AddTransient<TService>((serviceProvider) =>
            {
                var dep1 = serviceProvider.GetRequiredService<TDep1>();
                return implementationFactory(dep1);
            });
        }

        public static IServiceCollection AddTransient<TService, TDep1, TDep2>(this IServiceCollection services, Func<TDep1, TDep2, TService> implementationFactory) where TService : class
        {
            return services.AddTransient<TService>((serviceProvider) =>
            {
                var dep1 = serviceProvider.GetRequiredService<TDep1>();
                var dep2 = serviceProvider.GetRequiredService<TDep2>();
                return implementationFactory(dep1, dep2);
            });
        }
    }
}
```

Works on my machine :) 
It is hiding some complexity, and maybe that is not a good thing, but on the other hand makes getting dependencies easier :)

**Comment by khellang** [comment]
Hmm. It might be able to figure out the overload because of the return type of the lambda. Anyway, I think this is a bad idea. Those extension methods assume that you always want to register a concrete service as itself, which is rarely the case. I think it's far more common to register against an interface or something. It's easy enough to add these extension methods to your own app if you really need them. Or ship a separate library with these extension methods 😄

**Comment by petterek** [comment]
Last option is probably the best, there is use cases where this approach is ok, but maybe not allways.

I'm not regestring the service as it self.. Should probably be named like this..
``` 
  public static IServiceCollection AddTransient<TInterface, TDep1>(this IServiceCollection services, Func<TDep1, TInterface> implementationFactory) where TService : class
 ```

**Comment by pakrym** [comment]
I agree with @khellang. Not only it adds ambiguity to existing methods it also promotes the pattern we don't recommend. 

Factories with `GetRequiredService` have performance (container cannot build and optimize entire resolution tree) and diagnosability (makes it easier to get stackoverflow because of circular dependencies) downsides and should be used sparingly.

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
