### ISSUE TITLE
Disabling Cookie Encryption

### ISSUE THREAD

**Issue by drewchau** [aspnet/Home#3263]
Is there any way to opt out of certain functionalities from the DataProtection stack?

In my case, I'm looking to opt-out of cookie encryption for my web app since it runs in a server farm. I understand there are readily available instructions for handling this scenario, e.g. storing the Data Protection key in a centralized location. In addition to that, disabling data protection is a security concern. However I can handle cookie encryption through my load balancer, which allows my app to not worry about the location and handling of the data protection keyring,

Based on previous discussions, i.e. https://github.com/aspnet/DataProtection/issues/192, it doesn't look like there's any simple way of opting out other than re-implementing the Data Protection stack myself.

**Comment by Tratcher** [comment]
DataProtection is used for a lot more than just cookies. E.g. AntiForgery tokens.

Even if this were possible, it would be too dangerous for us to even provide samples for. It would almost certainly be used incorrectly and compromise one or more applications. If you figure out how to do it, please don't advertise it.

**Comment by drewchau** [comment]
@Tratcher I don't disagree. I asked about disabling DataProtection in general since there didn't seem to be an opt-out option for certain features, namely cookie encryption.

**Comment by davidfowl** [comment]
We don't need to write a sample but here's the extensibility point to providing your own format.

https://github.com/aspnet/Security/blob/f8b4f4c620e2faaeec262d302df143068c8d0b33/src/Microsoft.AspNetCore.Authentication.Cookies/CookieAuthenticationOptions.cs#L123

**Comment by drewchau** [comment]
I got it work. Thanks @davidfowl for the direction.
