### ISSUE TITLE
Shared framework package introduces invisible dependencies through namespace pollution

### ISSUE THREAD

**Issue by poke** [aspnet/Home#3264]
I was just upgrading a project to use the `.App` shared framework instead of individual package references when I noticed a problem there. In my code, I have been using a `ClaimsPrincipal.FindFirstValue` extension method which I added to my project. The same extension method is also part of Identity in `Microsoft.Extensions.Identity.Core`.

By switching to the shared framework, this caused my project to throw ambigous call compiler errors since both (identical) extension methods are in the same namespace. Not a big problem as I can just remove my own implementation. However, doing so will make me use the one in `Identity.Core` and as such add an unwanted hard reference to that assembly that previously did not exist.

Now, you could argue that the shared framework will make this a non-issue since the package is available on the machine anyway. And in a way I agree with that. It’s also not that the package itself has a lot of other stuff that would cause additional problems. But it’s still another dependency my project has, and I dislike this outcome on principle. It’s not an uncommon practice within ASP.NET Core that packages have extension methods for types outside of their own namespaces. So this is really a kind of namespace pollution that has the bad side effect of introducing dependencies invisibly through the shared framework.

I do realize that there isn’t much we can do about this now, but I am really unhappy that this is another complication the shared framework causes me. I’m currently considering to completely pass on the shared framework in all my projects because of all the issues (or at least questions) its magic raises (e.g. [this](https://github.com/aspnet/Home/issues/3156)). And I think that’s a real shame since the intention was really good.

I don’t know how I would ideally like to see this issue get resolved. I guess I would be happy if this problem (among those others) would be considered for future iterations of the shared framework so using it becomes less problematic. Maybe there could be some opt-out mechanism for packages or something.

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
