### ISSUE TITLE
HttpContext and RequestDelegate does not exist in packege anymore, what to do?

### ISSUE THREAD

**Issue by PavelMekhnin** [aspnet/Home#3266]
After I updated all packeges to 2.1.1 I fund that HttpContext and RequestDelegate does not exist in packege anymore, what to do?
![image](https://user-images.githubusercontent.com/5836560/41892942-3944ad64-7944-11e8-986b-e1362032f2da.png)

**Comment by davidfowl** [comment]
Maybe a re-sharper problem? None of the types moved. Can you reproduce this in general? What does your project file look like?

**Comment by PavelMekhnin** [comment]
@davidfowl I dont think that is ReSharper, Build Faild. I tried create a new project, but same problem. But all works fine with 2.1.0...

**Comment by PavelMekhnin** [comment]
Thanks, that all my pc, restore helped
