### ISSUE TITLE
Add support for interpolation within appsettings

### ISSUE THREAD

**Issue by jkotas** [aspnet/Home#3271]
_From @BlacKCaT27 on June 26, 2018 14:13_

Currently, any app configuration entries in your appsettings.json file must be a direct value type, ex:

    "TargetDirectories": {
        "RootDir": "/path/to/rootdir/",
        "SubDir1": "subdir1",
        "SubDir2": "subdir2"
    }

If I, as a developer, want to concatenate or otherwise combine configuration parameters, I have to wire all of it up manually within my code:

    public class TargetDirectories
    {
        public string RootDir { get; set; }
        public string SubDir1 { get; set; }
        public string SubDir2 { get; set; }
        public string FullDirectoryPath => $"{RootDir}/{SubDir1}/{SubDir2}";
    }

This is more error prone and verbose than it could be, especially since a proper implementation would likely want to check to ensure configuration values were parsed properly and exist on the model object prior to accessing them.

My hope is that support could be added to interpolate values within the config file such that combinations like the above example could be defined solely within the configuration file itself:

    "TargetDirectories": {
        "RootDir": "/path/to/rootdir/",
        "SubDir1": "subdir1",
        "SubDir2": "subdir2",
        "FullDirectoryPath": "${RootDir}/${SubDir1}/${SubDir2}"
    }

(note: I'm using the same syntax used by [the python configparser library](https://docs.python.org/3.4/library/configparser.html#interpolation-of-values) just for the sake of example. Whatever syntax is most appropriate for .net core could be chosen.)

This would follow the same expected behavior as the rest of the existing configuration tools, such that we could still map our configuration entries to a configuration model class:

    public class TargetDirectories
    {
        public string RootDir { get; set; }
        public string SubDir1 { get; set; }
        public string SubDir2 { get; set; }
        public string FullDirectoryPath { get; set };
    }
```

// Startup.cs

public void ConfigureServices(IServiceCollection services)
{
...

    services.Configure<TargetDirectories>(Configuration.GetSection("TargetDirectories"));

...
}
```

Thoughts?

_Copied from original issue: dotnet/corefx#30666_

**Comment by Eilon** [comment]
This issue was moved to aspnet/Configuration#859
