### ISSUE TITLE
Simplifying default VS Dockerfile

### ISSUE THREAD

**Issue by svick** [aspnet/Home#3273]
I have created a new .Net Core-based ASP.NET Core project and chose Linux-based support for Docker:

![](https://user-images.githubusercontent.com/287848/41993984-4777f954-7a4d-11e8-97cd-15f221a2489b.png)

When I did that, the Dockerfile that was generated was:

```dockerfile
FROM microsoft/dotnet:2.1-aspnetcore-runtime AS base
WORKDIR /app
EXPOSE 49357
EXPOSE 44389

FROM microsoft/dotnet:2.1-sdk AS build
WORKDIR /src
COPY WebApplication1/WebApplication1.csproj WebApplication1/
RUN dotnet restore WebApplication1/WebApplication1.csproj
COPY . .
WORKDIR /src/WebApplication1
RUN dotnet build WebApplication1.csproj -c Release -o /app

FROM build AS publish
RUN dotnet publish WebApplication1.csproj -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "WebApplication1.dll"]
```

It seems to me that this is unnecessarily complicated. What is the reason for having having separate `base` and `build` layers? And why run `dotnet build` explicitly, when `dotnet publish` runs it implicitly?

Put differently, couldn't the Dockerfile be simplified to the following?

```dockerfile
FROM microsoft/dotnet:2.1-sdk AS publish
WORKDIR /src
COPY WebApplication1/WebApplication1.csproj WebApplication1/
RUN dotnet restore WebApplication1/WebApplication1.csproj
COPY . .
WORKDIR /src/WebApplication1
RUN dotnet publish WebApplication1.csproj -c Release -o /app

FROM microsoft/dotnet:2.1-aspnetcore-runtime
WORKDIR /app
EXPOSE 49357
EXPOSE 44389
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "WebApplication1.dll"]
```

**Comment by Eilon** [comment]
@natemcmaster should this bug move to https://github.com/aspnet/aspnet-docker ?

**Comment by natemcmaster** [comment]
It should move to https://developercommunity.visualstudio.com. This file is generated by the VS [Docker Tooling](https://github.com/microsoft/dockertools) Team, but they don't really check their GitHub issue tracker.

**Comment by Eilon** [comment]
Thansk @natemcmaster .

@svick - can you please log a new issue using the [Report a Problem](https://developercommunity.visualstudio.com/) tool?

If you encounter a problem with Visual Studio, we want to know about it so that we can diagnose and fix it. By using the Report a Problem tool, you can collect detailed information about the problem, and send it to Microsoft with just a few button clicks. See [here](https://docs.microsoft.com/en-us/visualstudio/ide/talk-to-us) for more details.
