### ISSUE TITLE
Deployement does not work when I choose Add Application or Add Virtual Directory in IIS

### ISSUE THREAD

**Issue by viveknuna** [aspnet/Home#3275]
I am trying to deploy an Asp.NEt Core 2.1 application with IIS. It works fine when I choose Add Web Site on port 80, But when I deploy using option Add Application or Add Virtual Directory under Default Web Site in IIS on port 80, it gives 404 error when I browse the application.

Why is it not allowing me to deploy under default web site? Am I missing any configuration?

I have tried the work around mentioned [here](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/troubleshoot?view=aspnetcore-2.1#run-the-app-at-a-command-prompt), below is my observation.

**Observation:**
app is responding well. So the problem is more likely related to the reverse proxy configuration and less likely within the app, **But I have no clue what is the cause**

**Logs:**

> info: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[0]
>       User profile not available. Using 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\ASP.NET\4.0.30319.0\AutoGenKeys\S-1-5-82-3006700770-424185619-1745488364-794895919-4004696415\DataProtection' as key repository and Windows DPAPI to encrypt keys at rest.
> Hosting environment: Production
> Content root path: C:\Published\PublishOutput
> Now listening on: http://localhost:14942
> Application started. Press Ctrl+C to shut down.
> info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
>       Request starting HTTP/1.1 GET http://localhost/swaggar  
> info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
>       Executing action method Nec.Spar.Web.Host.Controllers.HomeController.Index (Nec.Spar.Web.Host) with arguments ((null)) - ModelState is Valid
> info: Microsoft.AspNetCore.Mvc.Internal.RedirectResultExecutor[1]
>       Executing RedirectResult, redirecting to /swagger.
> info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
>       Executed action Nec.Spar.Web.Host.Controllers.HomeController.Index (Nec.Spar.Web.Host) in 697.616ms
> info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
>       Request finished in 2127.3839ms 302

**Comment by Tratcher** [comment]
https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/index?view=aspnetcore-2.1&tabs=aspnetcore2x#sub-application-configuration
Virtual Directories aren't supported, but sub applications work if you're careful about your web.config inheritance.

**Comment by viveknuna** [comment]
I tried the web.config, It gave HTTP Error 403.14 - Forbidden error. So I enabled Directory browsing. Now when I browse the application, its just list all the files like dlls and config etc.

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <system.webServer>
    <aspNetCore processPath="dotnet" 
      arguments=".\<assembly_name>.dll" 
      stdoutLogEnabled="false" 
      stdoutLogFile=".\logs\stdout" />
  </system.webServer>
</configuration>
```

**Comment by Tratcher** [comment]
Is it a virtual directory or sub application?

**Comment by viveknuna** [comment]
I am adding as sub-application

**Comment by viveknuna** [comment]
@Tratcher Do you have any updates?

**Comment by Eilon** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, to get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the `asp.net-core` tag.
