### ISSUE TITLE
How to use DI in ICompileModule

### ISSUE THREAD

**Issue by wwwlicious** [aspnet/Home#328]
Looking for guidance in using IServiceProvider within the context of an ICompileModule.

I am creating a new appbuilder, passing in the existing IServiceProvider passed from the host app but was wondering if this is considered improper use. Example code can be found at the links

https://github.com/wwwlicious/R4MVC/blob/master/src/R4Mvc/R4MVCCompilerModule.cs#L38
https://github.com/wwwlicious/R4MVC/blob/master/src/R4Mvc/Ioc/IocConfig.cs

**Comment by davidfowl** [comment]
Why are you trying to extend what seems like the application via an ICompileModule?

**Comment by wwwlicious** [comment]
It was a suggestion by yourself [here](https://github.com/aspnet/Home/issues/272#issuecomment-70889627) I may have misunderstood..?

**Comment by davidfowl** [comment]
Ah is this the T4MVC replacement?

**Comment by wwwlicious** [comment]
yes, so was just looking at the razorprecompiler and it makes a bit more sense now I'm a bit more familiar with a few bits.

So should I be creating a service collection just for the compiler module to use, that seems to be what razorprecompiler is doing?

**Comment by davidfowl** [comment]
Yes but currently, things generated by ICompileModules don't show up for intellisense in visual studio or omnisharp right now.

**Comment by wwwlicious** [comment]
ok, I am writing the r4mvc gen'd file out to disk which avoids that issue as it gets picked up by the compiler second time around, again probably a horrible thing to do but I just don't know any better at the moment :)
