### ISSUE TITLE
[question] angular project should be in same project or separate

### ISSUE THREAD

**Issue by mhamri** [aspnet/Home#3280]
I was reading how the angular template is implemented, I am seeing that the frontend is sitting in the same project, I wonder if it's the recommended way of architecting the angular project with asp.net core or not? 

in cloud architecture, it's good to separate part of an application to scale separately, but since the frontend really doesn't cost much to server files it usually end up to host on same server. 
what are the benefits that i should expect from keeping the angular and .net together?

**Comment by Eilon** [comment]
Hi, while we do our best to look through all the issues filed here, to get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the `asp.net-core` and `angularjs` tags.

There are of course many ways to build apps, each with their unique advantages, and it is up to you decide whether for your application it makes sense to keep everything in one project or to split it up into multiple projects representing various tiers.
