### ISSUE TITLE
HttpContext.Request.Path - The path in 'value' must start with '/'.

### ISSUE THREAD

**Issue by kanadaj** [aspnet/Home#3282]
In some cases, when someone tries to access a page which relies on `HttpContext.Request.Path`, the following error is thrown:
```
The path in 'value' must start with '/'.
```
The URL looks something like this:
```
https://www.domain.com/fiction/18594/cultivating-civilization/chapter/228753/151-traitors
```
This seems to work for most users, but with rare exceptions. I'm not sure what exact conditions trigger this, as I see no headers or such that could justify this.

**Comment by Tratcher** [comment]
You're going to need to collect more information before we can help here. Server logs, Fiddler traces, repro code, etc..

**Comment by kanadaj** [comment]
@Tratcher I have a capture in Sentry as well as a pageview history in ElasticSearch, but neither the request logs nor the capture have anything indicative at all, and I cannot reliably reproduce the error. Do you have any good way to serialize HttpRequest? I've tried running `JsonConvert.SerializeObject` against it with `ReferenceLoopHandling.Ignore` and `MaxDepth = 1` but it still wouldn't work. If I wasn't having severe issues with App Insights I'd use the Snapshot Debugger, but somehow App Insights makes the web app lock up over time (it looks like as if saturated the sockets over time or something), so that's a no-go.

**Comment by kanadaj** [comment]
I'll grab the data directly from `HttpRequestFeature` with reflection, I guess

**Comment by Tratcher** [comment]
That shouldn't require reflection. See `HttpContext.Features.Get<IHttpRequestFeature>()`.

**Comment by kanadaj** [comment]
Ah, same source?
