### ISSUE TITLE
Cannot debug client-side code in VS Code with out-of-the-box SPA project.

### ISSUE THREAD

**Issue by casperOne** [aspnet/Home#3287]
I've created a new React SPA for ASP.NET Core 2.1.

Out of the box, if I open the `ClientApp` directory in VS Code I can then hit F5 to launch Chrome (using the Chrome debugger extension).

However, when I set breakpoints, each breakpoint is greyed out with the following message:

````
Unverified breakpoint, Breakpoints set but not yet bound
````

I'm fairly certain this is an issue with the `launch.json` configuration, specifically the `webRoot` (and possibly the `sourceMapPathOverrides`) property.

Here's the standard `launch.json` that I'm using:

````
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "chrome",
            "request": "launch",
            "name": "Launch Chrome against localhost",
            "url": "https://localhost:44311",
            "webRoot": "${workspaceFolder}",
            "sourceMapPathOverrides": {
                "webpack:///./*": "${webRoot}/*",
                "webpack:///src/*": "${webRoot}/*",
                "webpack:///*": "*",
                "webpack:///./~/*": "${webRoot}/node_modules/*",
                "meteor://💻app/*": "${webRoot}/*"
            }
        }
    ]
}
````

And the output of calling `.scripts` in a debug session is:

````
› https://localhost:44311/static/js/bundle.js
````

Is the assumption that it's an issue with `launch.json` correct?  If so, what is the correct configuration out of the box?

**Comment by Eilon** [comment]
@SteveSandersonMS - any ideas on this?

**Comment by SteveSandersonMS** [comment]
We have notes about configuring VS Code debugging at https://github.com/aspnet/JavaScriptServices/tree/master/src/Microsoft.AspNetCore.SpaServices#using-visual-studio-codes-debugger-for-chrome-extension

It's possible that VS code has changed something in the meantime, but those instructions did work before.
