### ISSUE TITLE
Has Html.RenderAction become depreciated?

### ISSUE THREAD

**Issue by WillBaldwin** [aspnet/Home#329]
GIVEN: KRE beta2 and All beta2 packages
  
I am attempting to perform a Html.RenderPartial using a specific ActionName and Controller that returns a PartialView("mypartialView", myModel) if I call the action from the url it works fine but I can't seem to find a way to get Html.RenderPartial to work for this purpose.  So I attempted to use Html.RenderAction() but it appears to be missing. Has Html.RenderAction become depreciated or am I missing a library?

**Comment by Eilon** [comment]
@WillBaldwin can you log this in the MVC repo https://github.com/aspnet/Mvc/issues ?

BTW View Components are the replacement for the previous Child Actions feature.
