### ISSUE TITLE
Ajax CDN is missing a bundled version of the core client library used in ASP.NET 

### ISSUE THREAD

**Issue by peterblazejewicz** [aspnet/Home#3290]
This one is similar to: #3285 

The Bootstrap 4.* authors added version of the JavaScript Bootstrap library bundled with its core dependency for tooltips/pop-overs/etc: 'popper.js':
https://getbootstrap.com/docs/4.1/getting-started/contents/#js-files

The published version of the Bootstrap on the MS Ajax CDN seems to be missing the `bundle` version:
https://ajax.aspnetcdn.com/ajax/bootstrap/4.0.0/bootstrap.js
https://ajax.aspnetcdn.com/ajax/bootstrap/4.0.0/bootstrap.bundle.js

Thanks!

**Comment by blowdart** [comment]
cc @ChrisSfanos 

None of the bootstrap directories have any .bundle.js files, only the .js and the minified version. So this doesn't appear to be a version we support or host, as you can see from the listed files at https://docs.microsoft.com/en-us/aspnet/ajax/cdn/overview

**Comment by JustCallMeAD** [comment]
I REALLY think that "bootstrap.bundle.js" must be included in the new templates by default.

I understand that the core devs do not run the Microsoft CDN but surely they can contact the Microsoft CDN guys to make sure this is added to their CDN urgently as it is needed before the updates to the new templates happen.

I did add a comment on the Microsoft CDN docs page (https://docs.microsoft.com/en-us/aspnet/ajax/cdn/overview#Bootstrap_Releases_on_the_CDN_14) but really think that we might have to do something more to make sure this happens before the new templates are released.

**Here is my comment on the CDN docs site:**

Please add another CDN link for Bootstrap 4. 

The new CDN link is for "bootstrap.bundle.js" (this includes both bootstrap.js & popper.js in 1 js file). Please note that popper.js it is now a requirement of Bootstrap & is used in Dropdowns & Tooltips.

See the links below for more information:
https://www.bootstrapcdn.com/
https://getbootstrap.com/docs/4.1/getting-started/introduction/#js
https://getbootstrap.com/docs/4.1/getting-started/download/#bootstrapcdn
https://getbootstrap.com/docs/4.1/getting-started/contents/

I am also going to send an email to AjaxCDNSubmission@Microsoft.com but I think it would be helpful if one of the Asp.Net team members can also contact them directly to make sure this happens before the new templates are released.

**Comment by JustCallMeAD** [comment]
Unfortunately I tried emailing them but my message did not go though.. Not sure why it is advertised on a public page if it does not work - https://docs.microsoft.com/en-us/aspnet/ajax/cdn/overview

**Can 1 of the Asp.net team members email them a request to add "bootstrap.bundle.js"?**

_Your message to AjaxCDNSubmission@microsoft.com couldn't be delivered.
The group AjaxCDNSubmission only accepts messages from people in its organization or on its allowed senders list, and your email address isn't on the list._

**Comment by Eilon** [comment]
@blowdart - putting this on your plate.

**Comment by blowdart** [comment]
Nope, I'm putting it on @ChrisSfanos

**Comment by Eilon** [comment]
@blowdart send email?

**Comment by ChrisSfanos** [comment]
I published the 4.0 version of the bundle for Bootstrap

https://ajax.aspnetcdn.com/ajax/bootstrap/4.0.0/bootstrap.bundle.js

**Comment by Eilon** [comment]
Thanks @ChrisSfanos !

**Comment by JustCallMeAD** [comment]
Thanks @ChrisSfanos !!

Looks like we still also need the 4.1.1 version of the bundle (as this is the latest version).. plus the docs need to be updated with links to the bootstrap bundles - https://docs.microsoft.com/en-us/aspnet/ajax/cdn/overview#Bootstrap_Releases_on_the_CDN_14

Thanks again!

**Comment by ChrisSfanos** [comment]
Posted 4.1.1: https://ajax.aspnetcdn.com/ajax/bootstrap/4.1.1/bootstrap.bundle.js

I've submitted the PR for the docs site

**Comment by JustCallMeAD** [comment]
Awesome thanks :)
