### ISSUE TITLE
Question : Disable HTTPS for development 

### ISSUE THREAD

**Issue by blowdart** [aspnet/Home#3293]
_From @orassr on July 3, 2018 18:43_

I set the baseUrl to http://localhost:5000  - NO HTTPS
but the request at the browser shows :  
Request URL: https://localhost:5001/api/auth/login
how can avoid HTTPS at development time temporary?

_Copied from original issue: dotnet/core#1750_

**Comment by orassr** [comment]
Its more like a quick fix but it works for me at this point 
At the launchSettings.json file,  I commented this : 

`    "DatingApp": {
      "commandName": "Project",
      "launchBrowser": true,
      "launchUrl": "api/values",
      "applicationUrl": "http://localhost:5000",
      //"applicationUrl": "https://localhost:5001;http://localhost:5000",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }`

And took off the 5001 port.

**Comment by Tratcher** [comment]
That's the best fix for this.

**Comment by Eilon** [comment]
Closing because we are not planning any changes in this area.

**Comment by nickenchev** [comment]
What if I only want http for dev env, and https for prod, do we have to keep editing the launch settings config?
