### ISSUE TITLE
Dependence can not load 'Microsoft.AspNetCore.App'

### ISSUE THREAD

**Issue by rubi** [aspnet/Home#3295]
I am using '.net core', i come across a wired problem, my project can not load 'Microsoft.AspNetCore.App', configuration as below.

---------- start -----
\<ItemGroup\>
    \<PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.7.0" />
    \<PackageReference Include="xunit" Version="2.3.1" /\>
    \<PackageReference Include="xunit.runner.visualstudio" Version="2.3.1" /\>
    \<DotNetCliToolReference Include="dotnet-xunit" Version="2.3.1" /\>
    \<PackageReference Include="Microsoft.AspNetCore.App" /\>
\</ItemGroup\>

-----dotnet --info-----

.NET Core SDK (reflecting any global.json):
 Version:   2.1.301
 Commit:    59524873d6

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.13
 OS Platform: Darwin
 RID:         osx.10.13-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.1.301/

Host (useful for support):
  Version: 2.1.1
  Commit:  6985b9f684

.NET Core SDKs installed:
  1.0.4 [/usr/local/share/dotnet/sdk]
  2.0.0 [/usr/local/share/dotnet/sdk]
  2.1.301 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

------Os environment -------
MAC OS high sierra 10.13.5

**Comment by natemcmaster** [comment]
Can you share more details about the error message your are getting, or the steps you are taking which fail?

**Comment by Eilon** [comment]
Hi. We're closing this issue as no response or updates have been provided in a timely manner and we have been unable to reproduce it. If you have more details and are encountering this issue please add a new reply and re-open the issue.
