### ISSUE TITLE
Missing "controllers" folder

### ISSUE THREAD

**Issue by Florian2880** [aspnet/Home#3296]
I followed the instructions of the tutorial, but when I had to make a controller class, there wasn't a folder "controllers" where I had to put it in. I made one myself, but when I append HelloWorld/ in the adressbar, it doesn't work. Can anyone help me with this?

**Comment by Florian2880** [comment]
https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-2.1

**Comment by SIkebe** [comment]
@Florian2880 You're using Razor Pages. Not MVC.

**Comment by Florian2880** [comment]
but I followed the tutorial, what did i do wrong then?

**Comment by Florian2880** [comment]
@SIkebe sorry, I copied the wrong link, this is the right one: https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-controller?view=aspnetcore-2.1

**Comment by SIkebe** [comment]
How did you create the app? You should have `controllers` directory when you follow this tutorial.
https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/start-mvc?view=aspnetcore-2.1&tabs=aspnetcore2x

**Comment by Florian2880** [comment]
Just like there's written in the tutorial and thanks I'll give it a try

**Comment by SIkebe** [comment]
Did you select Web Application(Model-View-Controller)?

**Comment by Florian2880** [comment]
I selected ASP.NET Core Web Application (Visual C#)

**Comment by SIkebe** [comment]
>I selected ASP.NET Core Web Application (Visual C#)

After that, you have to choose Web Application(Model-View-Controller) as the tutorial says.
https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/start-mvc/_static/new_project22-21.png?view=aspnetcore-2.1

**Comment by Florian2880** [comment]
Thx, I did choose Web Application but not the MVC one, now it works

**Comment by SIkebe** [comment]
@Florian2880 Great! Could you close this issue?
