### ISSUE TITLE
Separate MVC Controllers and View to different assemblies 

### ISSUE THREAD

**Issue by AndrosovIgor** [aspnet/Home#3297]
Hi there!
I try separate Core MVC controllers and view to different assemblies [(sample)](https://github.com/AndrosovIgor/AspNet-Core).

Issue with running application, I attach log file with ASP.NET web server logs([web_server_log.txt](https://github.com/aspnet/Home/files/2167170/web_server_log.txt))

Have any idea?
Thanks

**Comment by pranavkm** [comment]
MVC uses the entry assembly to discover application parts and compilation references. Hosting defaults to using the `Startup` assembly in case a value isn't explicitly specified. Setting `.UseSetting(WebHostDefaults.ApplicationKey, "Web")` in your `Program.Main` should set it up to use the Web as the startup assembly and discover the compiled views and compilation references correctly.
