### ISSUE TITLE
Generic Host Builder and HostingEnvironment.IsDevelopment

### ISSUE THREAD

**Issue by dazinator** [aspnet/Home#3298]
I am using the new generic host in 2.1.0 as documented here: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/generic-host?view=aspnetcore-2.1

When the hosting environment is development, I'd like to add user secrets:

```
  .ConfigureAppConfiguration((hostContext, configApp) =>
                   {
                       configApp.AddJsonFile("appsettings.json", optional: true);                   
                       if (hostContext.HostingEnvironment.IsDevelopment())
                       {
                           configApp.AddUserSecrets<Program>();
                       }
                       configApp.AddEnvironmentVariables(prefix: "FOO_");
                       configApp.AddCommandLine(args);
                   })
```

However `IsDevelopment` always returns false.
Yet I have set the `ASPNETCORE_ENVIRONMENT` enironment variable. Here is my launch settings:

```
{
  "profiles": {
    "Foo": {
      "commandName": "Project",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    }
  }
}
```

It would make sense if `ASPNETCORE_ENVIRONMENT` was no longer used to control this for a generic host as we are not in asp.net core land - but in that case is there now a different environment variable name for this, or do we set the Environment name ourselves in code?

**Comment by dazinator** [comment]
This seems like a sensible workaround, but it would be better if this behaviour was automatic to be consistent with asp.net core scenarios?

```

.ConfigureAppConfiguration((hostContext, configApp) =>
                   {
                       hostContext.HostingEnvironment.EnvironmentName = System.Environment.GetEnvironmentVariable("NETCORE_ENVIRONMENT");

```

**Comment by Eilon** [comment]
This issue was moved to aspnet/Hosting#1485
