### ISSUE TITLE
Instability the path of @Html.Partial("path") method according to Os version

### ISSUE THREAD

**Issue by camelkyhn** [aspnet/Home#3300]
Hi,

    Me and my friend just joined a team recently. Everyone have same dotnet sdk with the latest version and projects are being developing with c#. Somewhere in our web project, we have 

> @Html.Partial("Layout/javascript")

 method in the _Layout.cshtml file that is in the default directory. Path is right, there is a Layout folder and it includes "Javascript.cshtml" file. Me and my friend are using Ubuntu 16.04.4 with latest version. When we fetched the repository and tried to run this project, it gave us an error that is saying there is no "Layout/javascript" file, we thought its case sensitive and changed the method to @Html.Partial("Layout/Javascript") and it worked. 
    But the problem is that former developers had no problem on their codes. @Html.Partial("Layout/javascript") method was working on their computers. One of them is using MacOs version: 10.13.5, Kernel version: Darwin 17.6.0 and one of them is using Ubuntu version: 16.04.(1 or 2, not sure) in their computers. When one of them has updated his Ubuntu from "16.04.(1 or 2, not sure)" to "16.04.4" the latest version, he got the same error that is saying couldn't find the "Layout/javascript" file. Also another developer with the latest version of linux mint "18.03 slvia" gets the same case sensivity error. This instability makes us curious. Please tell us what causes this and let us know that we need to take precautions. Thank you.

**Comment by pranavkm** [comment]
Lookup for build-time \ precompiled views is case insensitive - https://github.com/aspnet/MvcPrecompilation/issues/37 (applies to views compiled using Razor Sdk too). It might be that your colleagues happened to be working with build-time compiled views. That said, the guidance is to match the exact case of to guarantee lookups consistently work regardless of the OS.
