### ISSUE TITLE
Difference between UseDefaultFiles & UseStaticFiles vs UseServerFiles

### ISSUE THREAD

**Issue by PredragG** [aspnet/Home#3302]
I have a index.html file in the root of my project that ought to be the entry point for my application. When I try to set it as default entry point in the Configure method of Startup using
```
var fileProvider = new PhysicalFileProvider(Directory.GetCurrentDirectory());
app.UseDefaultFiles();
app.UseStaticFiles(new StaticFileOptions { FileProvider = fileProvider, ServeUnknownFileTypes = true });
```
I get a 404. Whereas using just
```
app.UseFileServer(new FileServerOptions { FileProvider = fileProvider });
```
gives accesses that file. Looking at GitHub, those two approaches should be similar (except UseFileServer has an option for directory browsing). What's the catch?

**Comment by Tratcher** [comment]
UseDefaultFiles needs to use the same file provider as UseStaticFiles. UseFileServer consolidates that setup code.

**Comment by PredragG** [comment]
@Tratcher : Right, that was it! Thank you!
