### ISSUE TITLE
System.BadImageFormatException when use `TestServer.CreateClient()`

### ISSUE THREAD

**Issue by John0King** [aspnet/Home#3305]
Today all my test fall with this Exception
here's the exception code 

```C#
public class TestFixture
    {

        private static TestServer _server;
        private static HttpClient _client;

        private readonly static object _lock = new object();
        public static TestServer Server
        {
            get
            {
                lock (_lock)
                {
                    if (_server == null)
                    {
                        var builder = WebHostBuilderFactory.CreateFromAssemblyEntryPoint(typeof(Startup).Assembly, null);
                        builder.UseSolutionRelativeContentRoot("src/<my-api-project-directory>");
                        _server = new TestServer(builder); // no exception here
                    }
                    return _server;
                }
            }
        }

        public static HttpClient Client
        {
            get
            {
                if(_client == null)
                {
                    _client = Server.CreateClient();  // throw System.BadImageFormatException
                }
                return _client;
            }
        }
    }
```

the excption says could not load file or assembly : < my  api project assembly >  or one of it's dependency

## environment
sdk: 2.1.301
asp.net core : 2.1.1
test sdk: 15.7.2
xunit:2.3.1

api-project :  `<TargetFramework>net461</TargetFramework>` `<RuntimeIdenitifier>win7-x64</RuntimeIdenitifier>`
test-project:  `<TargetFramework>net461</TargetFramework>`

**Comment by John0King** [comment]
I also try specify `<RuntimeIdenitifier />` in my test project , but after change to x64, not test will execute.

**Comment by Eilon** [comment]
Can you provide a full repro for this? Ideally upload the app to GitHub so we can try to reproduce the issue.

**Comment by John0King** [comment]
@Eilon  this is my test repo https://github.com/John0King/TestFailx101

**Comment by Eilon** [comment]
Thanks @John0King .

Can you show the full stack trace of the error? The `BadImageFormatException` is commonly caused when trying to load a DLL with the wrong bitness (32 vs. 64bit).

@javiercn - have you seen this type of issue while working on the Testing feature?

**Comment by John0King** [comment]
@Eilon my api project is `win7-x64` , and test project default is `AnyCpu`  , and both are running on `.net461` ,  if I switch my test project to `win7-x64`, it will not excute any test.

```
   在 ApiUnitTest.TestFixture.get_Server()
   在 ApiUnitTest.TestFixture.get_Client() 位置 <MySolutionFolder>\test\ApiUnitTest\TestFixture.cs:行号 46
   在 ApiUnitTest.CourseApiTest..ctor() 位置 <MySolutionFolder>\test\ApiUnitTest\CourseApiTest.cs:行号 19
```

I get the stack trace from debug model in VS.

Do I must use x86 so it can use xunit to test ?

**Comment by Eilon** [comment]
Also tagging @bradwilson in case he is familiar with this type of problem.

**Comment by John0King** [comment]
when debug the test,  VS show me testhost.x86.exe . How do I test a x64 app ?

**Comment by bradwilson** [comment]
In Visual Studio: Test > Test Settings > Default Processor Architecture

**Comment by bradwilson** [comment]
You can also set bitness in a .testsettings file.

**Comment by John0King** [comment]
@bradwilson  Can I set this in `.cspro`j file ?  and what can work with `dotnet test`

**Comment by bradwilson** [comment]
AFAIK, you cannot set anything in the .csproj file. You have to use a .testsettings file, which you pass to `dotnet test` with the `--settings` switch.

**Comment by John0King** [comment]
@bradwilson I try a few setting with `dotnet test` and `visual studio` .
when I  set `<PlatformTarget>x64</PlatformTarget>` , It will work with `dotnet test`  but not work in `visual studio`

use `dotnet test /p:PlatformTarget=x64`  also work , 
So Is this a bug in Visual Studio ?
