### ISSUE TITLE
cannot use beta 3 after installing ctp 6

### ISSUE THREAD

**Issue by lucamorelli** [aspnet/Home#331]
I just installed ctp 6. No  problem, but when I go to run kvm list I see that the current version is still beta 2.
![kre](https://cloud.githubusercontent.com/assets/127777/6339167/5810deb2-bbb4-11e4-95c1-04f6b6ba7fe4.png)
Run the kvminstall script from this repo, install kvm in the bin directory, but if I try to run kvm upgrade I see that the latest version is beta 2.
If I look to the .k* folders, I see that beta 3 has been installed in .k directory, but all paths and kvm install points to old directories.
![kre2](https://cloud.githubusercontent.com/assets/127777/6339249/ddd90574-bbb4-11e4-9934-3c80b76c7c6d.png)
Am I missing something?

**Comment by davidfowl** [comment]
Delete your existing kvm and get a new one.

**Comment by lucamorelli** [comment]
ok, thanks, looks like it's working now
