### ISSUE TITLE
Anti forgery token with angular SPA (CSRF)

### ISSUE THREAD

**Issue by vejandla** [aspnet/Home#3312]
I have implemented `Anti forgery token with angular SPA` in the following way, 

did this in the web api middle ware, for setting a cookie on clients browser, 
This will set the cookie for every api call.

```c#
var tokens = antiforgery.GetAndStoreTokens(context);
                   context.Response.Cookies.Append("XSRF-TOKEN", tokens.RequestToken,
                        new CookieOptions {HttpOnly = false, Secure = context.Request.IsHttps});

services.AddAntiforgery(options => options.HeaderName = "X-XSRF-TOKEN");
```

In spa, I am currently adding the cookie value to header manually in the request interceptor, as both are in different domains. 

```c#
if (Cookies.get('XSRF-TOKEN')) {
        config.headers['X-XSRF-TOKEN'] = Cookies.get('XSRF-TOKEN');
 }
```

This seems to be working fine without any issues. 

But, I was trying to understand this whole concept. So I have tried the following.

1) Since the API sets cookie on every call, on display of login screen, the cookie exists on browser, So I manually grabbed the cookie value and kept it in notepad.
2) Hard coded the cookie value in the request interceptor instead of getting it from cookie. 
3) Refreshed the entire webpage. api sets a new cookie with a different value.
4) Now made a post call, Value in the header and cookie is different, I can see in the request headers in the browsers, but api treated that as valid antiforgery token.

**at least, before I did this test, I assumed the header value and cookie value should be same and only so validateantiforgerytoken attribute treats it as right post request.**

If this assumption is wrong, 
1) what is this preventing here? 
2) why do i have to do this implementation in the first place.?
3) what if anyone just access our login page and grabs cookie value and make a call from post man or any other place by adding this cookie value in the header?

_Totally lost in different thoughts !! Hope someone ran into these thoughts or problems already and provide some help._ 

Thanks

**Comment by Eilon** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, to get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the `asp.net-core` tag.

**Comment by peterblazejewicz** [comment]
@vejandla Aslesh, there is a section on the docs about the very topic discussing high level overview and some details:
https://docs.microsoft.com/en-us/aspnet/core/security/anti-request-forgery?view=aspnetcore-2.1
If you find it lacking some additional information add a comment to the doc page and/or request update on the: https://github.com/aspnet/Docs

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
