### ISSUE TITLE
Move MVC content formatters to http abstraction level

### ISSUE THREAD

**Issue by h0useRus** [aspnet/Home#3313]
Hi guys,

Is any plans to make content formatters as http shared part of Asp.Net Core. Very common situation when formatters used by MVC API also should be used for simple realization of HttpClient. 

Currently for client side used System.Net.Http.Formatting from MVC5 which is not follow new architecture with splitting Input and Output formatters and  many other staff which I found very useful for clients. Using MVC packages required to download at least full MVC stack just to make request, which is also not good.

Also, it makes harder using Routing styled simple APIs to control content without adding MVC libraries.

It was very good benefit of old MVC5 where you using same libraries for server and client, why it was stopped in AspNet Core?

**Comment by Eilon** [comment]
Tagging @davidfowl and @rynowak re: Houdini

**Comment by davidfowl** [comment]
> Is any plans to make content formatters as http shared part of Asp.Net Core. 

I would love to do this but realistically speaking they would have to remain in the same Mvc namespace. Either that or we would create a new type with a similar name lower in the stack and I'm not convinced that's it's worth the incompatibility.

> Very common situation when formatters used by MVC API also should be used for simple realization of HttpClient.

We'd need to design something decoupled from the http object model as they are no longer shared between the client and server (e.g. something that worked on Streams and the headers). 

> Currently for client side used System.Net.Http.Formatting from MVC5 which is not follow new architecture with splitting Input and Output formatters and many other staff which I found very useful for clients. 

Have you written any new formatters? What benefits are you looking to get exactly?

> Using MVC packages required to download at least full MVC stack just to make request, which is also not good.

For the client you mean?

> Also, it makes harder using Routing styled simple APIs to control content without adding MVC libraries.

Why is that a problem? If you're using the shared framework in your application MVC is always referenced anyways. It's part of the shared framework.

> It was very good benefit of old MVC5 where you using same libraries for server and client, why it was stopped in AspNet Core?

We didn't find the HttpRequestMessage and HttpResponseMessage appropriate as an extensible server abstraction. They were OK as a pure data representation of the HttpRequest and response but it gets awkward when you want to augment them with arbitrary features and behavior that middleware or servers expose (for e.g. websockets).

**Comment by h0useRus** [comment]
In general what I see from AspNetCore stack architecture we mostly need some bridge with processing content between server and client to utilize same configuration options (ex. Json.Net parameters, Encoding settings etc.) in most simplest way. 

Yes, in our company we are not developing a lot of formatters, just some specific like image/jpeg, text/csv and other very specific to our company sites features.  That's why we really enjoy on your guys work to cover most of general scenario.

We also like to minimize references in our projects to decrease building time and other looks minor bits, but sometimes this affects to developer's performances and CI/CD time.  Also we distribute our .Net clients to our partners or for legacy MVC5 services and tried to do it as smaller as we can.  That's why downloading for simple client full MVC stack is personal pain :)

I've got you point about HttpRequestMessage / HttpResponseMessage but if formatters will be abstract enough it is just extensions level to use em for reading HttpContent from HttpResponseMessage  or use exactly the same for middlewares, or websokets, or even for MVC.

I hope I correctly conveyed my thoughts.

**Comment by rynowak** [comment]
There are multiple aspects to formatters. Briefly:
- content negotiation (which formatter should read/write) 
- setting headers 
- determining the text encoding
- buffering (in the System.Net.Http world, formatters in Core don't deal with buffering directly)
- actually doing serialization

What of these do you find meaningful for your scenario?

> I've got you point about HttpRequestMessage / HttpResponseMessage but if formatters will be abstract enough it is just extensions level to use em for reading HttpContent from HttpResponseMessage or use exactly the same for middlewares, or websokets, or even for MVC.

It sounds like the part of 'formatters' that you really find valuable is the actual serialization/deserialization no? Since you're writing your own formatters I assume that's where you're spending most of your time.

I'd suggest factoring the bulk of your code into a serializer/deserializer and then plugging that in to the relevant interfaces in the simplest way possible. Apologies if this seems overly simplisted, or if this is something you've already thought of 😆 

---

**IF** we were to move formatters down to the `Microsoft.AspNetCore.Http` level or similar, they would still be responsible for all of the concerns I listed above. All of these concerns are handled differently in the `System.Net.Http` world as well, and so this wouldn't really solve your problem. 

It's conceivable that we might create a new formatter abstraction *lower* in the ASP.NET Core stack in the future, but it would still be tied to ASP.NET Core.

**Comment by h0useRus** [comment]
All aspects metter, and as I see from your list only buffering support different. Yes I expecting that .Net and Asp.Net teams having own approaches to archive their platforms best results. Your are different with even same feature approaches, like DNS shift solved in HttpClientFactory and in SocketsMessageHandler.

I also not asking about Microsoft.AspNetCore.Http it could be Microsoft.Extensions.Http or something like this. Just need some smart bridge to make .Net Core and Asp.Net Core closer and easier entrance level for inexperienced people, decrease amount of coding.

**Comment by h0useRus** [comment]
It is not really simple, we are public company and all our code base is not open. In general we are using many teams across the World who developing microservices and provide clients for other teams or our partners.

We are using mixed solutions old is MVC5 and new Asp.Net Core, we also have WCF and even asmx services. Once we used native Framework problem with many packages was not so critical, but since we start using .Net Core clients for MVC5 it downloads a lot of extra libraries or you need to update a lot of AWS or Azure services for that. It began to be a bit messy and also decrease CI/CD performance. So we started huge optimization and removing all unnecessary libraries. 

We even migrate Systems.Net.Http.Formatters before Microsoft did it, only for this purpose, but once I did it I found many things that very improved in Asp,Net Core and still looks old in source library. For example BSON, we integrated with many 3rd parties, but never found companies who using BSON, but it included and now required extra reference it is minor, but those minors collected enough for me to ask you for unification or optimization.

We also developed CSV, Excel, PDF, Image formatters for our internal projects.

**Comment by khellang** [comment]
I'm not really interested in the client-side of this (we do what @rynowak outlined earlier), but (as I've mentioned in several other threads (and [blogged about](https://kristian.hellang.com/using-mvc-result-executors-in-middleware/))) it would be really nice to leverage MVC's formatter pipeline server-side without dragging MVC along. TBH, I'd be fine with keeping the namespace and type-forwarding if that would be possible.

**Comment by davidfowl** [comment]
> TBH, I'd be fine with keeping the namespace and type-forwarding if that would be possible.

That would be really be the only viable solution.

**Comment by khellang** [comment]
> Is it because you have to call something called AddMvcCore?

Yes, basically. It feels weird that people have to call that even if they don't use MVC. Couldn't there just be a first-class `AddFormatters` method or something that `AddMvcCore` calls internally? I guess I could add that extension method myself as well, but it would be nice if it was provided out of the box.

**Comment by rynowak** [comment]
Another viable solution would be to create a secondary abstraction in the HTTP layer and plug these into MVC.

Input formatters are related to concepts like `ModelMetadata` and `ModelState in MVC. They have a really super-duper opinionated idea about how to treat errors when deserializing something.

https://github.com/aspnet/Mvc/blob/release/2.2/src/Microsoft.AspNetCore.Mvc.Abstractions/Formatters/InputFormatterContext.cs#L37

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
