### ISSUE TITLE
Ship with deployment installer script for Linux, and web publish profiles

### ISSUE THREAD

**Issue by weedkiller** [aspnet/Home#3315]
Hello,

Even after 3 yrs of ASP-on-Linux, **Linux Webhosts support for ASP sites is non-existant/minimal**, For e.g.[ digital ocean has removed their .NET runtime scripts](https://www.digitalocean.com/community/questions/is-net-core-still-supported-in-do-or-was-it-deprecated), as a result the adoption is very low. 

1. In the release package a link to an installer for a develop to publish and run ASP sites on Linux hosts is desperately needed, in the pic. below you can see D.O. dropped support
2. Enhance documentation on support/configuration for linux
________________________________________________
![image](https://user-images.githubusercontent.com/21086190/42587171-ebb9887e-8507-11e8-9bcb-ae5828fbedb6.png)

Thanks

**Comment by Eilon** [comment]
Ping @DamianEdwards - any thoughts on this?

**Comment by Eilon** [comment]
I asked around and we have some detailed docs on Linux installation scenarios here: https://docs.microsoft.com/en-us/dotnet/core/linux-prerequisites?tabs=netcore2x#supported-linux-versions

This includes lists of pre-reqs, as well as download links.

**Comment by weedkiller** [comment]
hi, after spending more than a weekend with digital ocean, host manits and site grund, on trying to see if these templates would work with any of them. They ran into new issues, the support guys were hesistant and not keen, since this was not widely supported and lacked more support articles around it. 

Bigger issue was both a well tested secure image that was easy to deploy ASP core apps. I also noticed powershell was not their forte, but bash is not supported and they still had trouble.

End result its still not supported, microsoft's support for Linux is just half baked!!

Please ensure it runs on other native Linux clients easily.
