### ISSUE TITLE
Microsoft.AspNet.WebApi.Core (5.2.6) is not compatible with .NET Core 2.1

### ISSUE THREAD

**Issue by NN---** [aspnet/Home#3319]
After installing nuget Microsoft.AspNet.WebApi.Core I get the following message:
 
```
Package 'Microsoft.AspNet.WebApi.Core 5.2.6' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.1'. This package may not be fully compatible with your project.
```

**Comment by blowdart** [comment]
Ah, wrong package, but I can see why you're confused.

Packages targeting asp.net core being with Microsoft.AspNet*Core*. What you're adding is a package for previous versions of WebApi, and whilst it has Core in its name it's not for the Core platform.

There's no specific WebApi package for ASP.NET Core any more, it's all built into MVC and the .App or .All package.

**Comment by Eilon** [comment]
This issue was moved to aspnet/AspNetWebStack#179
