### ISSUE TITLE
Is there a way to add a default page convention that looks at the folder name

### ISSUE THREAD

**Issue by JohnGoldsmith** [aspnet/Home#3320]
Hi,

Is there a way to add a routing convention for Razor Pages that allows you to use the parent folder name as a default route?

For example, if I have `Pages/Products`, folder structure I'd prefer to have a default page named `Products.cshtml` and for `Pages/Services`, `Services.cshtml` (as opposed to having to use `Index.cshtml` in both cases).

This is just to make things clearer in code ie the model would then be name ProductsModel and all open tabs in Visual Studio wouldn't have to say "Index.."

Thanks

John

**Comment by Eilon** [comment]
This issue was moved to aspnet/Mvc#8060

**Comment by JohnGoldsmith** [comment]
Hello @Eilon,  Thanks for moving my issue and sorry posting in the wrong place.  Can I suggest a modification to the default text on the New Issue button.  (I scanned for Razor Pages and didn't see it so posted here).

> To address your issues more quickly, please open the issue in the most appropriate repository. These are some of the most common repos:
> 
> Common ASP.NET and Entity Framework repos and projects:
> 
>  - Documentation: https://github.com/aspnet/Docs
>  - MVC **(and Razor Pages)**: https://github.com/aspnet/Mvc
>  - Entity Framework Core: https://github.com/aspnet/EntityFrameworkCore

Thanks again.

John

**Comment by Eilon** [comment]
@JohnGoldsmith - thanks for the feedback, I updated the issue template here to include this info:  https://github.com/aspnet/Home/blob/master/.github/ISSUE_TEMPLATE.md
