### ISSUE TITLE
CORs in webapi not returning valid response

### ISSUE THREAD

**Issue by karelz** [aspnet/Home#3323]
_From @FlyingWraptor on July 12, 2018 15:18_

Hello there, so I've been migrating all API's to .net core but it's denying me from doing so with this issue.
So I've enabled CORs to provide access from `www.domain.tld` to my api at `api.domain.tld` using only specific methods. Angular requires the `Access-Control-Allow-Methods`  header to be returned but the build in CORs doesn't do that at all.

.NET Core SDK: 2.1.301

The request contains the following:
```
OPTIONS /someuri HTTP/1.1
Origin: https://www.domain.tld
Host: api.domain.tld
Access-Control-Request-Method: GET
Access-Control-Request-Headers: content-type
Cache-Control: no-cache
Postman-Token: abdb2984-e399-44d1-8048-777c65dcec5e
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
```

The response in postman:
```
Access-Control-Allow-Headers →content-type
Access-Control-Allow-Origin →https://www.domain.tld
Date →Thu, 12 Jul 2018 15:14:45 GMT
Server →Kestrel
Vary →Origin
```

My CORs configuration:
```csharp
public void ConfigureServices(IServiceCollection services)
{
	services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_1);
	services.AddCors();
}
public void Configure(IApplicationBuilder app, IHostingEnvironment env)
{
	...


	app.UseCors(builder => {
		builder.WithOrigins("http://localhost:4200", "https://www.domain.tld")
			.WithMethods("POST", "GET", "OPTIONS")
			.AllowAnyHeader();
	});

	app.UseMvc();
}
```

I've worked around this issue using the following code and commenting out `AddCors()` and `UseCors()`:
```csharp
[HttpOptions]
public void Options()
{
	Response.Headers.Add("Access-Control-Allow-Headers", "content-type");
	Response.Headers.Add("Access-Control-Allow-Origin", "https://www.domain.tld");
	Response.Headers.Add("Access-Control-Allow-Methods", "GET");
}
```

This worked perfectly for now:
```
Access-Control-Allow-Headers →content-type
Access-Control-Allow-Methods →GET
Access-Control-Allow-Origin →https://www.domain.tld
Content-Length →0
Date →Thu, 12 Jul 2018 15:16:11 GMT
Server →Kestrel
```

Is this a bug or something I'm not known with yet?

_Copied from original issue: dotnet/corefx#31024_

**Comment by FlyingWraptor** [comment]
Enabling AddCors() and UseCors() Works for the `Access-Control-Allow-Headers` and `Access-Control-Allow-Origin` but not the `Access-Control-Allow-Methods` headers. When manually adding Methods header in Options having the build-in Cors enabled will result in the header not being returned. Possibly being removed?

**Comment by FlyingWraptor** [comment]
> Some requests don’t trigger a CORS preflight. Those are called “simple requests” in this article, though the Fetch spec (which defines CORS) doesn’t use that term. A request that doesn’t trigger a CORS preflight—a so-called “simple request”—is one that meets all the following conditions:
> 
>     The only allowed methods are:
>         GET
>         HEAD
>         POST
Source: [Mozilla dev documentation](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS)

Meaning this isn't a CORs issue but Angular not being compliant with the [Fetch spec](https://fetch.spec.whatwg.org/).

**Comment by mkArtakMSFT** [comment]
Thanks for filing this issue, @FlyingWraptor. And for your PR also.
@javiercn, can you please review the referenced PR? Thanks.

**Comment by FlyingWraptor** [comment]
@mkArtakMSFT Please keep in mind the comment @pranavkm made:

> We were discussing possibly not doing the filtering at all. Like you said, the spec doesn't require it. I have some reservations about doing this by default (with no "flag" to opt out 2.1). Let me get back to you by early next week once we've had a chance to discuss this.

So please postpone this issue untill further notice from @pranavkm.

**Comment by pranavkm** [comment]
Fixed in https://github.com/aspnet/CORS/commit/a080301b89fb65f82cde7184468c6100c113847d.
