### ISSUE TITLE
problems with [NotNull] attribute

### ISSUE THREAD

**Issue by lucamorelli** [aspnet/Home#333]
I'm trying to write some scaffolders, starting from the mvc scaffolder, and I'm having problem compiling one of them.
In this project https://github.com/lucamorelli/scaffolder I can use [NotNull] in my own scaffolder, and works fine, in this one https://github.com/lucamorelli/RunSources I have this error message. 
**'NotNullAttribute' is inaccessible due to its protection level**
Why is working with one project and one not? Seems to me I'm using the same package configuration

**Comment by Eilon** [comment]
Each project needs to define its own `NotNullAttribute` class. They are found at compile time based on *name* and processed (though they are currently not implemented to do anything). You can certainly use regular `if(x==null)throw ArgNull("x")` too.

**Comment by lucamorelli** [comment]
ah, ok. thanks for the info.
