### ISSUE TITLE
Controllers declared in class library, returning 404 with AWS Lambda C#2.1

### ISSUE THREAD

**Issue by thammadi** [aspnet/Home#3330]
I created an AWS Serverless solution with a Web API and Class Library projects (2.1.0). Class Library is referenced by the Web API project.

Controller in Web API:
```
[Route("api/[controller]")]
public class ValuesController : Controller
{
        [HttpGet]
        public IEnumerable<string> Get()
        {
            return new string[] { "value1", "value2" };
        }
}
```
References: Microsoft.AspNetCore.App (2.1.0) and Microsoft.NETCore.App (2.1.0)
Compatability version set in Startup.cs:
```
public void ConfigureServices(IServiceCollection services)
{
    services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_1);
}
```

Controller in Class Library: 
```
[Route("api/[controller]")]
public class ClassesController : Controller
{
        [HttpGet]
        public IEnumerable<string> Get()
        {
            return new string[] { "class1", "class2" };
        }
}
```
References: Microsoft.AspNetCore.App (2.1.0) and Microsoft.NETCore.App (2.1.0)
SDK reference in Class Library project file is updated from Microsoft.NET.Sdk to Microsoft.NET.Sdk.Web

Deployed the above to AWS lambda (dotnet lambda package -c "Release")

When tested, '/api/values' works as expected but '/api/classes' returns 404
This used to work with 2.0 version.

Did I miss anything?

**Comment by Eilon** [comment]
This issue was moved to aspnet/Mvc#8095
