### ISSUE TITLE
NET 2.1: Breaking Change in TestServer?

### ISSUE THREAD

**Issue by moogle001** [aspnet/Home#3334]
I have a website built on NET Core 2.0 with unit tests that confirm routing using the RestEase library. A unit test looks like this:

        [Fact]
        public async Task GetAll()
        {
            var webHostBuilder = CreateWebHostBuilder();
            using (var server = new TestServer(webHostBuilder))
            {
                var client = CreateClient(server);
                var objs = await client.GetAll();

                Assert.NotNull(objs);
                Assert.True(objs.Count > 0);
            }
        }

        public IWebHostBuilder CreateWebHostBuilder()
        {
            var config = new ConfigurationBuilder()
                .AddJsonFile("appsettings.json", optional: false, reloadOnChange: true)
                .Build();

            var host = new WebHostBuilder()
                .UseConfiguration(config)
                .UseStartup<TestStartup>();

            return host;
        }

        public ITransactionsApi CreateClient(TestServer server)
        {
            HttpClient client = server.CreateClient();
            ITransactionsApi toReturn = RestClient.For<ITransactionsApi>(client);
            return toReturn;
        }
 

Everything runs and passes under 2.0. However, upon upgrading to 2.1, all tests fail with 404. Aside from the introduction of WebApplicationFactory, I don't see anything in the notes about changes to unit testing. It should also be noted that when debugging the routes work under both versions, which is why I'm suspect of TestServer. I can provide diffs for the main project and test project if needed. I appreciate any insight anyone can provide.

**Comment by Tratcher** [comment]
I'm not aware of any direct changes to TestServer that would affect routing.  Can you share a minimal project that reproduce the issue?

How does RestEase discover routes? I know of a similar issue with MVC that broke discovering routes in separate assemblies.

**Comment by moogle001** [comment]
Thanks for the suggestion @Tratcher, that narrowed it down, and now your last comment makes sense. As you can see above, I am using a TestStartup class for my unit tests. This extends the main Startup class used by my website, but overrides some methods to disable logging, use mocked data layer, etc. TestStartup is in my test project, not in the main website project with the controllers.

In the tiny project I made to recreate this issue, the RestEase client works fine so long as I start the TestServer with the actual Startup class. As soon as I try to use a Startup class from the unit test project, the routes no longer function. So is this expected behavior?

**Comment by Tratcher** [comment]
You'll have to ask RestEase how they discover routes. It sounds similar to how MVC does it.

The difference here is likely that UseStartup sets the app name to the assembly name where your Startup class is located. You can override that.
https://github.com/aspnet/Hosting/blob/f9d145887773e0c650e66165e0c61886153bcc0b/src/Microsoft.AspNetCore.Hosting/WebHostBuilderExtensions.cs#L52-L55

**Comment by moogle001** [comment]
To clarify, RestEase doesn't do any discovery on its own. It allows you to define an interface with attributes dictating the route. Like so:

```
public interface IApi
    {
        [Get("api/values/")]
        Task<List<string>> GetValues();
    }
```

I as the web creator know what the route is supposed to be, and can share this interface with client applications. I just also use it for my unit tests in order to check for routing problems. Using an HttpClient manually against the TestServer still results in 404.

So it's not that RestEase is having problems finding the routes, it's that the routes do not seem to exist when the Startup class is not in the same project. I tried the UseSettings like so:

```
var host = new WebHostBuilder()
                .UseConfiguration(config)
                .UseSetting(WebHostDefaults.ApplicationKey, typeof(Startup).GetTypeInfo().Assembly.GetName().Name)
                .UseStartup<TestStartup>();

```

But still get 404s. However, if I move TestStartup class into the main website project, the routes work correctly. So I have a workaround, but it seems like a bug to me since this was not the behavior in 2.0.

**Comment by Tratcher** [comment]
@pranavkm any suggestions?

**Comment by moogle001** [comment]
Yes @pranavkm, I tried to follow the upgrade guide, and everything seems to work when I debug. I can provide before and after of my csproj to show the differences. For now I will try to upload a sample solution demonstrating the problem after only minimal changes to the API template.
[NetCoreUnitTesting.zip](https://github.com/aspnet/Home/files/2203510/NetCoreUnitTesting.zip)

**Comment by pranavkm** [comment]
Re-arranging the last two lines of code from your `Test.CreateWebHostBuilder` fixes the issue:

```C#
public IWebHostBuilder CreateWebHostBuilder()
        {
            var config = new ConfigurationBuilder()
                //.AddJsonFile("appsettings.json", optional: false, reloadOnChange: true)
                .Build();

            var host = new WebHostBuilder()
                .UseConfiguration(config)
                .UseStartup<TestStartup>() // Point to the test startup first
                .UseSetting(WebHostDefaults.ApplicationKey, typeof(Startup).GetTypeInfo().Assembly.GetName().Name); // Set the "right" application after the startup's been registerted

            return host;
        }
```

Background:  `UseStartup` overwrites the `ApplicationKey` - https://github.com/aspnet/Hosting/blob/master/src/Microsoft.AspNetCore.Hosting/WebHostBuilderExtensions.cs#L55 effectively negating `.UseSetting(WebHostDefaults.ApplicationKey, typeof(Startup).GetTypeInfo().Assembly.GetName().Name)`. MVC uses the application assembly as the root of discovery for other assemblies that reference MVC to then search for controllers in. This likely happened in 2.0 too but worked because MVC could infer that NetCoreUnitTesting.Tests references NetCoreUnitTesting which in turn references MVC (transitively).

The AspNetCore shared runtimes make querying this difficult - transitive dependencies that also reference the runtime show up as not referencing the runtime. When MVC queries `NetCoreUnitTesting` when the root of the graph is NetCoreUnitTesting.Tests, it comes back as saying it does not reference Microsoft.AspNetCore.App. Correcting the app name corrects the root of the graph fixing the issue.
