### ISSUE TITLE
Way to configure IIS reverse proxy without aspnetcore module

### ISSUE THREAD

**Issue by yashwanthreddyg** [aspnet/Home#3337]
I have Kestrel running as a Windows service using dotnet core portal runtime and a DLL.
Can I make IIS run as a reverse proxy for my application?
I want to avoid installing the dotnethostingbundle as I already have a portable runtime.

**Comment by Tratcher** [comment]
Have you tried ARR? https://www.iis.net/downloads/microsoft/application-request-routing

**Comment by yashwanthreddyg** [comment]
That helped. Closing the issue. Thanks.
