### ISSUE TITLE
How To Bind Model Value From Body by Custom Binder

### ISSUE THREAD

**Issue by Edward-Zhou** [aspnet/Home#3338]
I am trying this document [Custom Model Binding in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/advanced/custom-model-binding?view=aspnetcore-2.1), I could get the model value when passing by `Query String`.
But, I want to bind the model to Request Body, how could I fetch value from Request body when I sending request with `application/json`.

**Comment by Eilon** [comment]
This issue was moved to aspnet/Mvc#8110
