### ISSUE TITLE
cannot run web starter application from sources

### ISSUE THREAD

**Issue by lucamorelli** [aspnet/Home#334]
Hi,
  I created a web starter application, cloned the mvc repo locally, added the mvc/src directory to global.json "source". Checked out the beta 3 tag.
  Opening I see a few things:
![untitled](https://cloud.githubusercontent.com/assets/127777/6350009/637e32c8-bc30-11e4-92c9-4e38e01b9c6c.png)
1. Microsoft.AspNet.mvc seems loaded locally looking at the icon, but the repo solutions are not added to the solution itself.
2.Error List gives me a lot of errors, but in the status bar I see Build succeded
3. If I try to run I obtain an error message

**Comment by Eilon** [comment]
Can you clarify what "the repo solutions are not added to the solution itself." means?

Also, have you tried re-opening VS to see if the error persists?

BTW we have a blog post on this topic here: http://blogs.msdn.com/b/webdev/archive/2015/02/06/debugging-asp-net-5-framework-code-using-visual-studio-2015.aspx - check it out to see if any of the instructions there are helpful.

**Comment by lucamorelli** [comment]
In previous ctp adding other projects this way, working with the global.json file, the projects are automatically to the solution.
I was trying to follow the instruction in the article, but the solution isn't compiling. I'm using the beta3 kre, the package references seems correct pointing to beta3, I checked out the beta 3 tag of the mvc sources,   but I have a lot of errors.
The other strange thing, as seen in the picture, is that error list gives a lot of errors, but status bar tells **build successfull**.

**Comment by davidfowl** [comment]
This is a tooling bug. VS isn't adding the projects to the solution and doesn't notify DTH about these projects. The reason it's still compiling is because compilation can see the project references.

/cc @BillHiebert @PradeepKadubandi @mayurid @abpiskunov

**Comment by davidfowl** [comment]
@lucamorelli If you clone the repository outside of the solution root, it should work. I've filed a bug on the VS side to make sure this gets fixed.

**Comment by lucamorelli** [comment]
yes, thanks. I seen. If you're interested I have done a more test loading packages from source. I added them using global.json, adding the sources directories and rebuilding.
If I look to the icons in the solution explorer to understand if the source or nuget package I seen this:
1. first I added mvc, rebuilt it, checked in solution explorer, and  all looks fine.
2. second I added entity framework, rebuilt it, checked in solution explorer, and all looks fine
3. after this I added Identity,rebuilt it, checked in solution explorer, and  found that in the web starter app the EntityFramework.SqlServer is loaded from sources, but in the project Microsoft.AspNet.Identity.EntityFramework is nuget package of EntityFramework.SqlServer is used.
4. After this I added the Microsoft.Framework.DependencyInjection package: the project is loaded in the solution, but in all the projects in the solution with the above packages looks like the nuget version is used.

**Comment by lucamorelli** [comment]
I'm using ctp 6 and the release main feed

**Comment by lucamorelli** [comment]
This problem with the packages that aren't show correctly happens adding the projects directly the projects in the solution: I added manually all of them, removing all those Vs automatically added, but I have the same problem,
I tried to run the kpm list from the project directory and seems fine: I find a reference for the version 0.0.0 of the package and is used in all the projects

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
