### ISSUE TITLE
aspnet/FileSystem Polling broken?

### ISSUE THREAD

**Issue by tmds** [aspnet/Home#3341]
I set DOTNET_USE_POLLING_FILE_WATCHER to see how it affects aspnet/Configuration refresh.
I saw no polling of the configuration files.

Looking at the implementation, it seems events are triggered by FileSystemWatcher, even when polling: https://github.com/aspnet/FileSystem/blob/faf1f007208001988d30618eca934481ea61dcda/src/FS.Physical/PhysicalFileProvider.cs#L78

My understanding is DOTNET_USE_POLLING_FILE_WATCHER is meant for filesystems like NFS where FileSystemWatcher does not work.
So, the configuration reload is probably broken on such filesystems, even when setting DOTNET_USE_POLLING_FILE_WATCHER.

CC @natemcmaster @pranavkm

**Comment by pranavkm** [comment]
@tmds prior to 2.2.0-preview2, `DOTNET_USE_POLLING_FILE_WATCHER` was a bit of a misnomer. A PhysicalFileProvider with polling enabled would return a `IChangeToken` that would only go to disk if you inspected the `HasChanged` property (i.e. it was passive). This worked really well with one scenario - `IMemoryCache` which always looked at HasChanged, but missed several other scenarios like configuration that expected the change token to actively inform when a file had changed.

We addressed this as part of 2.2.0 by making the change token actively poll the disk. Here's the issue that was used to address this behavior - https://github.com/aspnet/Mvc/issues/8173.

**Comment by tmds** [comment]
Great, thanks!
