### ISSUE TITLE
Add Enabled flag to Microsoft.AspNetCore.Diagnostics.ExceptionHandlerFeature

### ISSUE THREAD

**Issue by DanFTRX** [aspnet/Home#3342]
It would be nice to be able to enable/disable the exception handler pages on the fly in [Microsoft.AspNetCore.Diagnostics.ExceptionHandlerFeature](https://github.com/aspnet/Diagnostics/blob/master/src/Microsoft.AspNetCore.Diagnostics/ExceptionHandler/ExceptionHandlerFeature.cs) similar to how:  [Microsoft.AspNetCore.Diagnostics.StatusCodePagesFeature](https://github.com/aspnet/Diagnostics/blob/master/src/Microsoft.AspNetCore.Diagnostics/StatusCodePage/StatusCodePagesFeature.cs#L11) allows.

**Comment by Tratcher** [comment]
How do you plan to handle the exception when the exception handler is disabled?

**Comment by Tratcher** [comment]
Ah, so you still want it to handle the exception, but to conditionally produce a different result. That makes some sense. 

Enabling/disabling the exception handler in ever API controller would also be tedious. Have you considered customizing the error endpoint you're redirected to? E.g. it could check the Accept header and decide if HTML is appropriate.

**Comment by DanFTRX** [comment]
I guess that that would be an option I hadn't considered.  But it seems a bit odd to still be doing the redirect just to return the same status code from somewhere else though.

**Comment by Tratcher** [comment]
Depending on how you're using the middleware, it's not a full redirect, it's an internal re-route (See WithReExecute).

**Comment by DanFTRX** [comment]
Right, I meant it was odd to reroute the request and walk its way back down the pipeline to my error endpoint just for it to return a 500 status code, when it could just immediately return within the ErrorHandlerMiddleware where it had already set a 500.

**Comment by Tratcher** [comment]
Sure, but conditionally signaling it to do so is the hard part. You don't want to add code to all of your WebAPI endpoints to suppress it.

**Comment by Tratcher** [comment]
Also, this overlaps the discussion from https://github.com/aspnet/Home/issues/2573

**Comment by pranavkm** [comment]
> There are certain cases(Specifically on my API routes) in which I would rather have the raw 500 returned

Might not be super relevant here - but there are some plans to address this experience as part of 2.2.0. See https://github.com/aspnet/Mvc/issues/7756

**Comment by DanFTRX** [comment]
I was thinking along the lines of an attribute that just runs 

`context.HttpContext.Features.Get<IExceptionHandlerFeature>().Enabled = false;`


Which I could then add onto entire controller classes to blanket apply across them.

**Comment by DanFTRX** [comment]
@pranavkm Actually that is pretty much exactly my issue.

**Comment by DanFTRX** [comment]
Well I guess since there are plans to address this experience moving forward, and since I have a viable workaround in the meantime, this ticket is no longer needed.
