### ISSUE TITLE
InvalidOperationException: Unable to resolve service for type

### ISSUE THREAD

**Issue by ArifKuttayi** [aspnet/Home#3343]
I'm using Core 2.1 razor pages with repository. Showing error while opening register page even I have registered Email sender in Startup.cs. Please see below error log.
![error log](https://user-images.githubusercontent.com/17797408/42969720-c8cbbaa4-8baf-11e8-89a3-f0c74cfaa137.JPG)

**Comment by Eilon** [comment]
Hi @ArifKuttayi , can you show more of your application's code? Which services are being registered in Startup.cs?

**Comment by ArifKuttayi** [comment]
Hi @Eilon ,thanks for reply. Please see below my startup file.

using System;
using ProjectsManager.Core.Interfaces;
using ProjectsManager.Core.Services;
using ProjectsManager.Infrastructure.Data;
using ProjectsManager.Infrastructure.Identity;
using ProjectsManager.Infrastructure.Logging;
using ProjectsManager.Infrastructure.Services;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using System.Text;

namespace ProjectsManager.Web
{
    public class Startup
    {
        private IServiceCollection _services;

        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }


        public void ConfigureProductionServices(IServiceCollection services)
        {
            // Add Project DbContext
            services.AddDbContext<ProjectContext>(c =>
                c.UseSqlServer(Configuration.GetConnectionString("ProjectConnection")));

            // Add Identity DbContext
            services.AddDbContext<IdentityContext>(options =>
                options.UseSqlServer(Configuration.GetConnectionString("IdentityConnection")));

            ConfigureServices(services);
        }

        public void ConfigureServices(IServiceCollection services)
        {
            services.AddIdentity<ApplicationUser, IdentityRole>()
                    .AddEntityFrameworkStores<IdentityContext>()
                    .AddDefaultTokenProviders();

            services.ConfigureApplicationCookie(options =>
            {
                options.Cookie.HttpOnly = true;
                options.ExpireTimeSpan = TimeSpan.FromHours(1);
            });

            services.AddScoped(typeof(IRepository<>), typeof(EfRepository<>));
            services.AddScoped(typeof(IAsyncRepository<>), typeof(EfRepository<>));

            services.AddScoped<IProjectService, ProjectService>();
            services.AddScoped<IProjectRepository, ProjectRepository>();

            services.AddScoped(typeof(IAppLogger<>), typeof(LoggerAdapter<>));
            services.AddTransient<IEmailSender, EmailSender>();

            // Add memory cache services
            services.AddMemoryCache();

            services.AddMvc()
                .SetCompatibilityVersion(Microsoft.AspNetCore.Mvc.CompatibilityVersion.Version_2_1)
                .AddRazorPagesOptions(options => {});

            _services = services;
        }


        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
                app.UseDatabaseErrorPage();
            }
            else
            {
                app.UseExceptionHandler("/Error");
                app.UseHsts();
            }

            app.UseHttpsRedirection();
            app.UseStaticFiles();
            app.UseCookiePolicy();

            app.UseAuthentication();

            app.UseMvc();
        }
    }
}

**Comment by Eilon** [comment]
Thanks @ArifKuttayi . Can you show what `ProjectsManager.Web.Areas.Identity.Pages.Account.RegisterModel` and `ProjectsManager.Infrastructure.Services.EmailSender` look like?

I only see an `IEmailSender` *interface* being registered in `services.AddTransient<IEmailSender, EmailSender>();`, but no `EmailSender` *class*. I'm guessing that either `RegisterModel`'s constructor is incorrectly using EmailSender instead of IEmailSender, or that the EmailSender class itself has some issues.

**Comment by ArifKuttayi** [comment]
@Eilon, here it is below RegisterModel

using System.ComponentModel.DataAnnotations;
using System.Text.Encodings.Web;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using ProjectsManager.Infrastructure.Identity;
using ProjectsManager.Infrastructure.Services;

namespace ProjectsManager.Web.Areas.Identity.Pages.Account
{
    [AllowAnonymous]
    public class RegisterModel : PageModel
    {
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly ILogger<RegisterModel> _logger;
        private readonly EmailSender _emailSender;

        public RegisterModel(
            UserManager<ApplicationUser> userManager,
            SignInManager<ApplicationUser> signInManager,
            ILogger<RegisterModel> logger,
            EmailSender emailSender)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _logger = logger;
            _emailSender = emailSender;
        }

        [BindProperty]
        public InputModel Input { get; set; }

        public string ReturnUrl { get; set; }

        public class InputModel
        {
            [Required]
            [EmailAddress]
            [Display(Name = "Email")]
            public string Email { get; set; }

            [Required]
            [StringLength(100, ErrorMessage = "The {0} must be at least {2} and at max {1} characters long.", MinimumLength = 6)]
            [DataType(DataType.Password)]
            [Display(Name = "Password")]
            public string Password { get; set; }

            [DataType(DataType.Password)]
            [Display(Name = "Confirm password")]
            [Compare("Password", ErrorMessage = "The password and confirmation password do not match.")]
            public string ConfirmPassword { get; set; }
        }

        public void OnGet(string returnUrl = null)
        {
            ReturnUrl = returnUrl;
        }

        public async Task<IActionResult> OnPostAsync(string returnUrl = null)
        {
            returnUrl = returnUrl ?? Url.Content("~/");
            if (ModelState.IsValid)
            {
                var user = new ApplicationUser { UserName = Input.Email, Email = Input.Email };
                var result = await _userManager.CreateAsync(user, Input.Password);
                if (result.Succeeded)
                {
                    _logger.LogInformation("User created a new account with password.");

                    var code = await _userManager.GenerateEmailConfirmationTokenAsync(user);
                    var callbackUrl = Url.Page(
                        "/Account/ConfirmEmail",
                        pageHandler: null,
                        values: new { userId = user.Id, code = code },
                        protocol: Request.Scheme);

                    await _emailSender.SendEmailAsync(Input.Email, "Confirm your email",
                        $"Please confirm your account by <a href='{HtmlEncoder.Default.Encode(callbackUrl)}'>clicking here</a>.");

                    await _signInManager.SignInAsync(user, isPersistent: false);
                    return LocalRedirect(returnUrl);
                }
                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError(string.Empty, error.Description);
                }
            }

            // If we got this far, something failed, redisplay form
            return Page();
        }
    }
}

And below is EmailSender:
using ProjectsManager.Core.Interfaces;
using System.Threading.Tasks;

namespace ProjectsManager.Infrastructure.Services
{
    public class EmailSender : IEmailSender
    {
        public Task SendEmailAsync(string email, string subject, string message)
        {
            return Task.CompletedTask;
        }
    }
}

**Comment by Eilon** [comment]
It looks like the problem is as I suggested. This code:

```c#
        EmailSender emailSender)
```

Should be:

```c#
        IEmailSender emailSender)
```

**Comment by ArifKuttayi** [comment]
Many thanks Eilon, it's worked.

**Comment by trapias** [comment]
Hello,
I'm writing here since I have a similar problem: I'm trying to customize Identity within my AspNetCore 2.2 webapp (slightly modified the login page and disabled registration), but customizations only work locally - if I publish to a staging server, I still see the default pages.

If I remove the call to .AddDefaultUI(UIFramework.Bootstrap4) in order to avoid this, I get the same exception for example at /Identity/Account/Manage:

```
InvalidOperationException: Unable to resolve service for type 'Microsoft.AspNetCore.Identity.UI.Services.IEmailSender' while attempting to activate 'MyWebApp.Areas.Identity.Pages.Account.Manage.IndexModel'.
```

I scaffolded all Identity pages, and did not modify this page - IEmailSender is there:

```
 public partial class IndexModel : PageModel
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly IEmailSender _emailSender;

        public IndexModel(
            UserManager<ApplicationUser> userManager,
            SignInManager<ApplicationUser> signInManager,
            IEmailSender emailSender)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _emailSender = emailSender;
        }
[...]
```

In my startup.cs I do add the service:

```
services.AddIdentity<ApplicationUser, IdentityRole>()
                //.AddDefaultUI(UIFramework.Bootstrap4)
                .AddEntityFrameworkStores<ApplicationDbContext>()
                .AddDefaultTokenProviders();
[...]

 services.AddTransient<IEmailSender, EmailSender>();
[...]
```

.. and I have my EmailSender class:

```
  public class EmailSender : IEmailSender
    {
        public Task SendEmailAsync(string email, string subject, string message)
        {
            Logger _logger = LogManager.GetCurrentClassLogger();
            _logger.Debug("SendEmailAsync to " + email);
[...]
```

Can anybody tell what am I missing?
Thanks,
al.

**Comment by trapias** [comment]
Solved, I just add to reference my IEmailSender in scaffolded pages instead of the one from Identity.
