### ISSUE TITLE
Dependency injection interceptor/wrapper/chain

### ISSUE THREAD

**Issue by jacobslusser** [aspnet/Home#3347]
Apologies if this has been asked and/or answers already...

I want to be able to register a service in the traditional way:
```cs
services.AddSingleton<IRepository, Repository>();
```
but when I call for the service I want to get a wrapped/intercepted version that does caching. i.e. the caching service would implement the same service and wrap the original service:

```cs
public class CachingRepository : IRepository
{
    private readonly IRepository originalRepository;
    public CachingRepository(IRepository originalRepository)
    {
        this.originalRepository = originalRepository; // Would be instance of Repository
    }
}
```
It might help to think of this in the way that middleware calls the next middleware in the chain...

Is there a good way to do this? Maybe with a factory? I can't quite put my finger on it and the approach I'm currently using feels kludge-y.

**Comment by Eilon** [comment]
The built-in DI container does not support this. However, there are some 3rd party containers that work with ASP.NET Core and might support this. I recommend checking out Autofac and see what features they have.

**Comment by jacobslusser** [comment]
Thanks I've used Autofac in the past and it appears to do what I want.

However, in the course of researching it I came across Scrutor, [https://github.com/khellang/Scrutor](https://github.com/khellang/Scrutor), which also appears to do exactly what I want with an easier to follow API/configuration. Going to give that a try.

Thanks.

**Comment by Eilon** [comment]
@jacobslusser sounds good, thanks!

**Comment by jacobslusser** [comment]
Follow up:

I had an even more complicated DI story than I first alluded to and Scrutor choked a bit. It seems good for simple decorators, but gave me problems when I needed more complicated factories and such.

However, I found this basic approach to be the essence of what I needed (in a more complicated form):
```cs
public static IServiceCollection ReplaceSingleton<TService>(this IServiceCollection collection, Func<IServiceProvider, TService> implementationFactory) where TService : class
{
    var descriptor = new ServiceDescriptor(typeof(TService), implementationFactory, ServiceLifetime.Singleton);

    var original = collection.FirstOrDefault(s => s.ServiceType == typeof(TService));
    if (original != null)
    {
        var index = collection.IndexOf(original);
        collection.Insert(index, descriptor);
        collection.Remove(original);
    }
    else
    {
        collection.Add(descriptor);
    }

    return collection;
}
```
```cs
// Root services
services.AddSingleton<IRepository, Repository>();
services.AddSingleton<CachingRepository>();

// Decorator services
var snapshot = services.BuildServiceProvider();
services.ReplaceSingleton<IRepository>(_ => snapshot.GetRequiredService<CachingRepository>());
```
The extension method just simplifies replacing an already registered service (Singleton). Adapt as necessary. 

The key to making a decorator service work is taking a "snapshot" of the current service container. Replace the services you want to decorate. Then when creating the decorator service, use the snapshot/clone of the container. This way, the decorator service is constructed using the services first registered rather than the one just replaced and preventing a circular dependency. Not sure if that makes sense, but if you study where/when the `snapshot` container is created and used in the sample above it should be clear.

Hopefully that will help anyone else wanting to do the same.

**Comment by khellang** [comment]
> Scrutor choked a bit

I'd be interested in more details. I'm used to bumping into limitations (which is kinda why Scrutor exists in the first place), but there might be something that can be done about it?
