### ISSUE TITLE
How to get used InputFormatter and OutputFormatter in ActionFilter?

### ISSUE THREAD

**Issue by MhAllan** [aspnet/Home#3349]
Hi,

So I have added Message Pack formatter beside Json. now in an action filter I want to get that formatter to deserialize some request header. how can I get access to the current formatter?

**Comment by khellang** [comment]
I don't think there's an easy way to get a specific formatter. A formatter does quite a few more things than just serializing an object, like setting headers, determining encoding, writing to the response body etc.

I would recommend just serializing the header yourself. If you need some kind of conneg, you could look at the `ObjectResultExecutor` and maybe copy some code.

**Comment by Eilon** [comment]
This issue was moved to aspnet/Mvc#8128
