### ISSUE TITLE
Strange behavior while getting method parameter from body in ApiController

### ISSUE THREAD

**Issue by Abarbz** [aspnet/Home#3350]
Hello,
While testing one of the methods in my Asp.Net Core Web API, I witnessed a strange behavior.
The method, sitting in an `[ApiController]`, has the following signature:
```
[HttpPost("myPath")]
[ProducesResponseType(200)]
public IActionResult MyMethod(MyObject obj)
```

And the `MyObject` looks like this:
```
public struct MyObject
{
	    public readonly bool MyBoolean;
	    public MyObject(bool myBoolean)
	    {
		    MyBoolean= myBoolean;
	    }
}
```

I was manually testing some behaviors using Postman, and when posting the following objects, I was surprised by the results:
* `{ afdqgdqgdsgqdgdg: false }` : yields a proper MyObject instance, with its MyBoolean field set to `false`
* `{ afdqgdqgdsgqdgdg: false, myBoolean: true }` yields a proper MyObject instance, with its MyBoolean field set to `true`
* `{ afdqgdqgdsgqdgdg: false, jfghdfhfdhf: true }` yields a proper MyObject instance, with its MyBoolean field set to `false`
* `{ afdqgdqgdsgqdgdg: 3 }`: yields a proper MyObject instance, with its MyBoolean field set to `false`

In those 5 cases, I was actually expecting an error due to model mismatch (except maybe in the second case, where at least one of the properties was matching).
What is happening here? Is this behavior expected?

**Comment by khellang** [comment]
Yes, this is expected. If you post JSON properties that doesn't match the POCO, they're just ignored. You can configure Newtonsoft to throw on these properties by setting the `MissingMemberHandling` setting to `Error` instead of `Ignore`.

I probably wouldn't use a struct for this, or at least I'd make it nullable in the parameter so you'd be able to tell if it was bound properly. It's also important to check `ModelState` for errors in all your actions.

**Comment by Abarbz** [comment]
Thanks for the quick answer.
I can understand invalid properties being ignored, but what about no property matching the model (case 1, 3 & 4)? Shouldn't they fail? Case 4 does not even contain any boolean value.

I also tried with a class, and the behavior is similar in all 4 scenarios.
When you say "check  `ModelState` for error", do you mean checking `ModelState.IsValid`?  I though it was checked implicitly when using the `[ApiController]` attribute?

**Comment by khellang** [comment]
> I though it was checked implicitly when using the `[ApiController]` attribute?

Ah, yes it should. Assuming you've also set the compatibility version to 2.1 in your startup.

What happens to case 1, 3 & 4 if you change it to a class, or make the parameter nullable?

**Comment by Abarbz** [comment]
> What happens to case 1, 3 & 4 if you change it to a class, or make the parameter nullable?

Just tried, and the behavior is actually exactly the same, no matter if I use `struct`, `struct?` or `class` for MyObject.

**Comment by Eilon** [comment]
This issue was moved to aspnet/Mvc#8127
