### ISSUE TITLE
memory leak during the use of reloadOnChange: true with ConfigurationBuilder

### ISSUE THREAD

**Issue by jkotas** [aspnet/Home#3351]
_From @abelpalaty on July 23, 2018 7:39_

  Hi,
We have dotnet core driver which connects to our product (CICS TG).
In the driver we create a connection and closes it after each transaction.
While creating the connection we have the following code.

```c#
     var  builder = new ConfigurationBuilder()
           .SetBasePath(Directory.GetCurrentDirectory())
           .AddJsonFile("appsettings.json", optional: false, reloadOnChange: true);
```

With the setting reloadOnChange: true we see the memory leak with time eventhough the connection is closed after each request.

We tried with the following code

```c#
     var  builder = new ConfigurationBuilder()
           .SetBasePath(Directory.GetCurrentDirectory())
           .AddJsonFile("appsettings.json", optional: false, reloadOnChange: false);
```

with the setting reloadOnChange: false we see the memory usage is constant with time.

The sample we ran runs same application in a loop of like 2500 times where each time new object is created and closed.
Our customer reported this issue and its recreating every time. Its high priority .
Is there any fix available already or is it a known issue?
Is there a way we can make sure memory usage is constant (maybe additional  code to release FileSystemWatcher after the connection is closed.)

We created a memory profiling report and we see that the function which allocated the most memory is System.IO.FileSystemWatcher.AllocateBuffer().
I am attaching the screenshots of the observation we did during our testing.
![70910eb8a8b6afd3](https://user-images.githubusercontent.com/41566819/43063074-769bc604-8e78-11e8-8e85-89b2e4abe863.jpg)
![748aa0170f472bc9](https://user-images.githubusercontent.com/41566819/43063075-76d0beb8-8e78-11e8-9892-9bff9e5c5ba8.jpg)
![7e81d48d0df38b32](https://user-images.githubusercontent.com/41566819/43063076-770d7a56-8e78-11e8-8e69-16700d9bddba.jpg)

_Copied from original issue: dotnet/coreclr#19080_

**Comment by Eilon** [comment]
This issue was moved to aspnet/Configuration#861
