### ISSUE TITLE
[CORS] Normalize internationalized domain names when adding to CORS

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Home#3353]
Follow up to https://github.com/aspnet/CORS/pull/170. `CorsPolicyBuilder` should normalize IDNs to use punycode. This would match the format browsers send for IDN urls.

**Comment by pranavkm** [comment]
cc @mkArtakMSFT for triage

**Comment by mkArtakMSFT** [comment]
@blowdart, what are your thoughts regarding this? Do you think this is something we should try and take in 2.2 or is this something we can postpone?

**Comment by blowdart** [comment]
It's a good idea, where would you normalize though? Would you allow people to add unicode domains when configuring cors server side, then change it internally on add?

**Comment by mkArtakMSFT** [comment]
I'll let @javiercn and/or @pranavkm to answer that question.

**Comment by pranavkm** [comment]
> Would you allow people to add unicode domains when configuring cors server side, then change it internally on add?

Yup. We got a PR to do some normalization \ lower case the input URI as part of the policy builder. Presumably we would do something similar here.

**Comment by blowdart** [comment]
Seems like a good idea to me. I have no preference for 2.2 or later.

**Comment by javiercn** [comment]
@pranavkm We should be careful here. URIs are case sensitive and we shouldn't normalize them or treat them in a case insensitive way.
When the URI is puny code, don't we "un puny code it " before it gets to us?

**Comment by Tratcher** [comment]
Domains are not case sensitive. 

In this case the value comes from the origin header, not the host header, so it's still encoded.
