### ISSUE TITLE
Flaky test: ReturnsCorrectCursor

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/Home#3355]
This test [fails](http://aspnetci/viewLog.html?buildId=513995&buildTypeId=XPlat_Windows_Win8_Universe) occasionally with the following error:
```
System.IO.FileLoadException : Could not load file or assembly 'System.Runtime.CompilerServices.Unsafe, Version=4.0.4.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at System.Memory`1.op_Implicit(Memory`1 memory)
   at System.Buffers.ReadOnlySequenceFactory.CreateSegments(Byte[][] inputs)
   at System.Buffers.ReadOnlySequenceFactory.SingleSegmentTestSequenceFactory.CreateWithContent(Byte[] data)
   at System.Buffers.Tests.ReadableBufferReaderFacts.ReturnsCorrectCursor(Int32 takes, Boolean end)
```

**Comment by ryanbrandenburg** [comment]
ReturnsCorrectCursor [failed again](http://aspnetci/viewLog.html?buildId=513995&buildTypeId=XPlat_Windows_Win8_Universe).

**Comment by Eilon** [comment]
@pakrym any idea about this?

**Comment by pakrym** [comment]
Seems like flaky infrastructure.

**Comment by Eilon** [comment]
Which infrastructure?

**Comment by pakrym** [comment]
Testing infrastructure/ `System.Runtime.CompilerServices.Unsafe` being randomly found/not found on win7/win8 machines is not a test issue. Especially considering hundreds of tests fail/not fail depending on a run.

http://aspnetci/viewLog.html?buildId=515833&tab=buildResultsDiv&buildTypeId=XPlat_Windows_Win7_Universe
http://aspnetci/viewLog.html?buildId=513995&buildTypeId=XPlat_Windows_Win8_Universe

**Comment by Eilon** [comment]
So is there a product bug here? (Not necessarily ASP.NET Core product, but maybe a lower level?)

**Comment by pakrym** [comment]
There might be. We had a similar issue in IISIntegration where api set dlls were not found and retrying helped.

**Comment by Eilon** [comment]
@pakrym that sounds super suspicious. I wouldn't have guessed that there could be any non-determinism in that kind of case. Is there another person we can consult? Or have we accidentally created a race condition? (E.g. installing .NET Core in the background while running some other tests?)

**Comment by pakrym** [comment]
It's hard to tell, I need to look at what happens there more.

**Comment by pakrym** [comment]
I looked around and it seems mass failures stopped on all agents after we updated to `3.0.0-preview1-26727-03` on Jul  26

**Comment by pakrym** [comment]
Closing this seems like an infrastructure issue that went away.
