### ISSUE TITLE
Flaky test: GetMemoryTryGetArrayOfDisposedPoolThrows

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/Home#3356]
This test [fails](http://aspnetci/viewLog.html?buildId=513995&buildTypeId=XPlat_Windows_Win8_Universe) occasionally with the following error:
```
Assert.Throws() Failure
Expected: typeof(System.InvalidOperationException)
Actual:   typeof(System.IO.FileLoadException): Could not load file or assembly 'System.Runtime.CompilerServices.Unsafe, Version=4.0.4.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at System.Memory`1.op_Implicit(Memory`1 memory)
   at Microsoft.Extensions.Internal.Test.DiagnosticMemoryPoolTests.<>c__DisplayClass7_0.<GetMemoryTryGetArrayOfDisposedPoolThrows>b__0()
```

**Comment by ryanbrandenburg** [comment]
CanWriteWithOffsetAndLenght [failed again](http://aspnetci/viewLog.html?buildId=513995&buildTypeId=XPlat_Windows_Win8_Universe).

**Comment by ryanbrandenburg** [comment]
ReturnsCorrectCursor [failed again](http://aspnetci/viewLog.html?buildId=514165&buildTypeId=XPlat_Windows_Win8_Universe).

**Comment by ryanbrandenburg** [comment]
CtorFindsFirstNonEmptySegment [failed again](http://aspnetci/viewLog.html?buildId=514179&buildTypeId=XPlat_Windows_Win2008r2_Universe).

**Comment by ryanbrandenburg** [comment]
AdvanceToEndThenPeekReturnsMinusOne [failed again](http://aspnetci/viewLog.html?buildId=514319&buildTypeId=XPlat_Windows_Win2008r2_Universe).

**Comment by ryanbrandenburg** [comment]
PeekWorkesWithEmptySegments [failed again](http://aspnetci/viewLog.html?buildId=514309&buildTypeId=XPlat_Windows_Win10Universe).

**Comment by ryanbrandenburg** [comment]
ReturnsCorrectCursor [failed again](http://aspnetci/viewLog.html?buildId=514782&buildTypeId=XPlat_Windows_Win2008r2_Universe).

**Comment by ryanbrandenburg** [comment]
ReturnsCorrectCursor [failed again](http://aspnetci/viewLog.html?buildId=514945&buildTypeId=XPlat_Windows_Win8_Universe).

**Comment by ryanbrandenburg** [comment]
CanWriteNothingToBuffer [failed again](http://aspnetci/viewLog.html?buildId=515138&buildTypeId=XPlat_Windows_Win8_Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
CtorFindsFirstNonEmptySegment [failed again](http://aspnetci/viewLog.html?buildId=514949&buildTypeId=XPlat_Windows_Win10Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
ReturnsCorrectCursor [failed again](http://aspnetci/viewLog.html?buildId=515280&buildTypeId=XPlat_Windows_Win7_Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
EmptyWriteDoesNotThrow [failed again](http://aspnetci/viewLog.html?buildId=515142&buildTypeId=XPlat_Windows_Win10Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
PeekReturnsByteWithoutMoving [failed again](http://aspnetci/viewLog.html?buildId=515152&buildTypeId=XPlat_Windows_Win2008r2_Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
AdvancingPastLengthThrows [failed again](http://aspnetci/viewLog.html?buildId=515586&buildTypeId=Lite_UniverseTest).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
CtorFindsFirstNonEmptySegment [failed again](http://aspnetci/viewLog.html?buildId=515393&buildTypeId=XPlat_Windows_Win10Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
ThrowsForInvalidParameters [failed again](http://aspnetci/viewLog.html?buildId=515652&buildTypeId=XPlat_Windows_Win10Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
ReturnsCorrectCursor [failed again](http://aspnetci/viewLog.html?buildId=515716&buildTypeId=XPlat_Windows_Win7_Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
ReturnsCorrectCursor [failed again](http://aspnetci/viewLog.html?buildId=515714&buildTypeId=XPlat_Windows_Win10Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
PeekReturnsByteWithoutMoving [failed again](http://aspnetci/viewLog.html?buildId=515800&buildTypeId=XPlat_Windows_Win2008r2_Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
PeekGoesToEndIfAllEmptySegments [failed again](http://aspnetci/viewLog.html?buildId=515837&buildTypeId=XPlat_Windows_Win2008r2_Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
AdvanceSingleBufferSkipsBytes [failed again](http://aspnetci/viewLog.html?buildId=515992&buildTypeId=Lite_UniverseTest).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
ReturnsCorrectCursor [failed again](http://aspnetci/viewLog.html?buildId=515833&buildTypeId=XPlat_Windows_Win7_Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
AdvanceSingleBufferSkipsBytes [failed again](http://aspnetci/viewLog.html?buildId=516078&buildTypeId=XPlat_Windows_Win2008r2_Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
ReaderIndexIsCorrect [failed again](http://aspnetci/viewLog.html?buildId=516074&buildTypeId=XPlat_Windows_Win7_Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
WorkesWithEmptyBuffer [failed again](http://aspnetci/viewLog.html?buildId=516180&buildTypeId=Lite_UniverseTest).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by Eilon** [comment]
@pakrym maybe the same as https://github.com/aspnet/Home/issues/3355? This seems to be exploding all over the place.

**Comment by pakrym** [comment]
Closing this seems like an infrastructure issue that went away.
