### ISSUE TITLE
AddResponseCaching unnecessarily adds IMemoryCache to the DI

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/Home#3360]
The response caching middleware used to rely on the memory cache from the DI until we decided to use a private instance of memory cache: https://github.com/aspnet/ResponseCaching/pull/132. As such we no longer need to add IMemoryCache to the DI services as part of AddResponseCaching.

**Comment by Eilon** [comment]
Marking as breaking-change, even though no one should have relied on this behavior anyway. No need for an announcement at this time.
