### ISSUE TITLE
MeidaType's subtype with suffix should be a subset of a subtype without suffix

### ISSUE THREAD

**Issue by kichalla** [aspnet/Home#3362]
According to https://tools.ietf.org/html/rfc6839#section-2, content like `application/problem+json` should be able to be processed as though its `application\json` too, but currently we don't consider `application/problem+json` as a subtype of `application\json`.

Related issue: https://github.com/aspnet/Mvc/issues/8156

**Comment by kichalla** [comment]
cc @Tratcher

**Comment by Eilon** [comment]
Tagging @dougbu and @jkotalik who I think both have a great deal of knowledge on this matter.

**Comment by dougbu** [comment]
@kichalla and I discussed this, reviewed the spec(s), and I agree it's a bug.
