### ISSUE TITLE
ASP.NET Core 2.1 - Identity Pages Override

### ISSUE THREAD

**Issue by NabinR** [aspnet/Home#3363]
While overwriting Identity Pages on Visual Studio via Add > New Scaffolded Items > Identity, if the "Overwrite all files" is ticked, all Identity Pages (Accounts, Manage) are overwritten. This is the intended behaviour. 

In addition to that, the default CSS, JS and image files (site.css, site.js, banner*.svg) also gets overwritten. That surely doesn't look like the intended behaviour.

**Comment by Eilon** [comment]
@javiercn / @vijayrkn  - any thoughts on this?

**Comment by javiercn** [comment]
@seancpeters As he's the owner of the scaffolders. It sounds like a bug to me

**Comment by seancpeters** [comment]
The identity scaffolder is designed to check for a wwwroot directory, and only put content there if the directory does not exist or is empty. Overwriting the css, js, etc. in the wwwroot directory is not intended, so yes, this is a bug.

**Comment by Eilon** [comment]
This issue was moved to aspnet/Scaffolding#844
