### ISSUE TITLE
ASP .Net Core 2.1 targetting .Net Framework?

### ISSUE THREAD

**Issue by nickball-granta** [aspnet/Home#3364]
Hi, 

Is it possible to target the .Net Framework with ASP .Net Core 2.1? I can target 4.6.2 with ASP .Net Core 2.0, but all attempts up to 4.7.2 with .Net Core 2.1 don't work. I get Nuget errors restoring AspNetCore:

Package Microsoft.AspNetCore.App 2.1.0 is not compatible with net472 … supports netcoreapp2.1 (.NETCoreApp, Version=2.1)

This page:

https://docs.microsoft.com/en-us/aspnet/core/?view=aspnetcore-2.1#aspnet-core-targeting-net-framework

Suggest I should be able to target the .Net Framework with ASP Net Core 2.1. If so, how? 

-Nick

**Comment by nickball-granta** [comment]
I've found a workaround. As detailed in this stackoverflow:
https://stackoverflow.com/a/51073516/1838604

"The metapackages Microsoft.AspNetCore.App and Microsoft.AspNetCore.All require netcoreapp, but the they are just a collection of other packages to install." 

So if you nuget the individual packages, you are good to go.

**Comment by Eilon** [comment]
@natemcmaster / @JunTaoLuo - can you help out?

**Comment by JunTaoLuo** [comment]
Correct, the metapackages `Microsoft.AspNetCore.App` and `Microsoft.AspNetCore.All` can only be used on ASP.NET Core. Apps targeting .NET Framework will need to reference individual packages.
