### ISSUE TITLE
Help: ASP.NET Core 2.1 on Ubuntu 18.04 - COnfigure SSL Certificate

### ISSUE THREAD

**Issue by bhaidar** [aspnet/Home#3368]
Hello,
I am trying to run an ASP.NET Core 2.1 app on Ubuntu 18.04.
When I use the development self-signed certificate, the browsers Chrome and Firefox need me to add an exception to allow the App to run.

What is the proper way to trust a development self-signed certificate on Ubuntu 18.04? 

Something related to the above. Where is the development self-signed certificate located on hard disk?

On the other hand, if I want to create my own self-signed certificate. Then, how to tell Kestrel about it?

Thanks

**Comment by Tratcher** [comment]
@javiercn

**Comment by Tratcher** [comment]
See https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel?view=aspnetcore-2.1&tabs=aspnetcore2x for providing your own cert.

**Comment by javiercn** [comment]
@bhaidar There is no centralized trust store in Linux, its on a per distro basis. You can use `dotnet dev-certs https -ep <<aspnetcert.crt>>` to get the public part of the certificate and from there, use the instructions specific to your distro to trust the certificate.

**Comment by ehouarn-perret** [comment]
@javiercn, I think it would be nice to give a tutorial or the steps to achieve that with Ubuntu.

**Comment by gulando** [comment]
I have the same problem. 
I am trying to run standart asp.net core mvc application on my Ubuntu 18.04 machine and but I can't do it because browser gives me "Your connection is not private" (certificate is not valid), but when I am typing in terminal  "dotnet dev-certs https" it returns me "A valid HTTPS certificate is already present."

**Comment by blurpis** [comment]
No real help here. Surprise, surprise.

**Comment by dmitry-pavlov** [comment]
https://devblogs.microsoft.com/aspnet/configuring-https-in-asp-net-core-across-different-platforms/
