### ISSUE TITLE
How to update bootstap 4

### ISSUE THREAD

**Issue by chamaraonline** [aspnet/Home#3369]
HI 
how to update defult  Bootstrap v3.3.5 to BS4 without Node/ Gulp

**Comment by Tratcher** [comment]
See https://github.com/aspnet/Templating/pull/595

**Comment by Eilon** [comment]
@chamaraonline there's no simple way because Bootstrap 3 to Bootstrap 4 contains a lot of changes. You can follow the same pattern that we're following in the Templating repo.
