### ISSUE TITLE
Where is the "Task.CompletedTask"

### ISSUE THREAD

**Issue by djanosik** [aspnet/Home#337]
Hi,

I've updated to VS 2015 CPT6 and latest versions of `System.Runtime` and other packages. Now all my projects fail on the `Task.CompletedTask`. It is available in .NET 4.5.2, ASP.NET 5 Core, but it is not available in ASP.NET 5 Full.

Am I doing something wrong?

Thank you!

**Comment by Tragetaschen** [comment]
`Task.CompletedTask` is only available on .NET 4.6 (not 4.5.2).

For compatibility reasons (for example Mono), ASP.NET 5 was recently (from beta2 to beta3) changed to be based off of 4.5.* instead of 4.6, so the member isn't available anymore.

ASP.NET 5 Core will have this member from the beginning.

**Comment by djanosik** [comment]
Ok, it's good to know. Thank you!

**Comment by Eilon** [comment]
BTW we're working on a feature where when you're using "full .NET" (also known as Desktop .NET, which is what's used in `aspnet50`), you'll be able to choose between .NET 4.5.2 and .NET 4.6.

**Comment by ZOXEXIVO** [comment]
Why it dissapear in netcoreapp1.0 ?

**Comment by davidfowl** [comment]
It should be in netcoreapp1.0.

**Comment by ZOXEXIVO** [comment]
Yes, but simple netcoreapp1.0 class library detects as dnx451 in migrated project.
In newly created solution everything is ok

**Comment by davidfowl** [comment]
I'm not sure what you mean by it "detects as dnx451", what steps did you take to migrate?

**Comment by ZOXEXIVO** [comment]
https://github.com/aspnet/Home/issues/1625

**Comment by khaledannajar** [comment]
I am running VS on Mac OS X with runtime: mono v 5.4.1.7. And I can't find Task.CompletedTask. I had to use this work around [on stack over flow](https://stackoverflow.com/questions/14244114/create-a-completed-task#14244239)
