### ISSUE TITLE
Asp.net core Self Contained Application Exe Getting deletedon the windows Server

### ISSUE THREAD

**Issue by abhinavgalodha** [aspnet/Home#3373]
### Application Environment Details:
Windows Server: 2012 R2
.Net Core Version : 2.1.0
Application Deployment Model : Self Contained Deployment

### Problem
We have an Asp.net core web API developed using .net core 2.1.0 and deployed as a Self contained Deployment. The Application is hosted in IIS. IIS acts as an Reverse Proxy to the Kestrel Server.
The first time we deployed our application into production, we encountered an issue with the Symantec Antivirus. The Symantec Endpoint protection didn't like the exe on the Server and flagged it as virus and quarantined it. 

We asked Symantec to whitelist the exe and after the Antivirus update, the Exe was working fine.
Few weeks later, we noticed that few of the Production Servers was reporting 502.5 Process failure issue. We noticed that the exe was missing on the servers. We raised a ticket with Symantec and they confirmed that the Antivirus is not removing the exe using the Antivirus Diagnostics logs. This is a restricted environment and no user has access to directly delete an exe. Additionally, event viewer also didn't provide any useful details.

What can be the other possibilities of the exe being removed? Can IISAspnetCore module be doing anything which can cause file to be deleted? 

We are exploring the option to add file auditing to see who deleted the file. 

### Output of dotnet --info Command
```
dotnet --info

Host (useful for support):
  Version: 2.1.0
  Commit:  caa7b7e2ba

.NET Core SDKs installed:
  No SDKs were found.

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0 [C:\Program Files (x86)\dotnet\shared\Microsoft
.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0 [C:\Program Files (x86)\dotnet\shared\Microsoft
.AspNetCore.App]
  Microsoft.NETCore.App 2.1.0 [C:\Program Files (x86)\dotnet\shared\Microsoft.NE
TCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by Eilon** [comment]
I'm pretty sure nothing in ASP.NET Core is deleting your app's EXE file.

Is someone else using web publish to try to update the app, and maybe that is deleting the EXE? Or maybe there's another antivirus app running?

I think your idea of auditing the file system would be a logical next step. If you can narrow it down to which process it is, that would help immensely.

**Comment by abhinavgalodha** [comment]
Thanks Eilon for the prompt response.

This is a production system. So, a break-glass account is required and without a Change Request process, nothing can be done on the server. There is only 1 Antivirus which is running. 

Can Windows Defender or other native windows features can delete the exe from intepub.

**Comment by Eilon** [comment]
I believe Windows Defender can delete files if it detects a virus and will then quarantine the file. I found some info here: https://answers.microsoft.com/en-us/windows/forum/windows_8-security/how-to-stop-windows-defender-from-deleting-a/f4e3641a-5598-495d-b2a5-bd6ead226071

**Comment by abhinavgalodha** [comment]
Thanks @Eilon for the link.

Just checked that windows defender is disabled as the antivirus is running on the production server. So, the possibility of the Windows defender, causing the issue can be ruled out. We are trying to setup a File Audit Policy and see what is causing the issue.

**Comment by Eilon** [comment]
@abhinavgalodha great, please let us know.

**Comment by abhinavgalodha** [comment]
It has been a week since we added the file auditing, but the exe file hasn't been deleted. Since we are not able to reproduce the issue at this time, i will close the defect.
