### ISSUE TITLE
XmlSerializer does not support ulong enums

### ISSUE THREAD

**Issue by jack0x539** [aspnet/Home#3375]
```c#
public enum MessageDestination : ulong 
{
    None = 0,
    /* ... */
    All = ulong.MaxValue
}

...

public class Message
{
    public MessageDestination Destination { get; set; }
    /* ... */
}

...

XmlSerializer serialiser = new XmlSerializer(typeof(Message));
```

Exception thrown "Value was either too large or too small for an Int64.". I'm not sure why enum reflection for XML serialisation assumes that all enum values will be convertable to int64, when it's perfectly legit to have an enum extend uint64.

**Comment by Eilon** [comment]
This issue was moved to dotnet/corefx#31542
