### ISSUE TITLE
I try to install aspnet by brew on mac os, but it try to fetch branch "dev"

### ISSUE THREAD

**Issue by Oldmoooon** [aspnet/Home#3377]
```bash
➜ brew install dnvm
==> Installing dnvm from aspnet/k
==> Cloning https://github.com/aspnet/Home.git
Cloning into '/Users/***/Library/Caches/Homebrew/dnvm--git'...
warning: Could not find remote branch dev to clone.
fatal: Remote branch dev not found in upstream origin
Error: Failed to download resource "dnvm"
Failure while executing; `git clone --depth 1 --branch dev https://github.com/aspnet/Home.git /Users/***/Library/Caches/Homebrew/dnvm--git` exited with 128.
```

**Comment by BrennanConroy** [comment]
https://github.com/aspnet/dnvm#this-repository-is-obsolete-and-no-longer-used-or-maintained

**Comment by Oldmoooon** [comment]
but brew try to clone this repository. something wrong?

**Comment by BrennanConroy** [comment]
> DNX and DNVM have been replaced by the new .NET CLI. See:
- http://dotnet.github.io/getting-started/
- http://github.com/dotnet/cli

**Comment by Oldmoooon** [comment]
thanks  I had install it by [this](http://dotnet.today/en/aspnet5-vnext/getting-started/installing-on-mac.html).

**Comment by daveyostcom** [comment]
Perhaps when one tries to `brew install dnvm` it could fail emit a useful message?
