### ISSUE TITLE
Self contained ASP.NET Core deployment to win7-x64 (Server2008R2) fails to run

### ISSUE THREAD

**Issue by gkinsman** [aspnet/Home#3378]
I'm testing a scenario in which we want to deploy a self contained ASP.NET Core app to a Windows Server 2008R2 server that doesn't have any .NET Core artefacts at all installed on it, and it needs to use HTTPS.

I created an app using the dotnet CLI, with version 2.1.2
`.NET Command Line Tools (2.1.302)`, running 
`dotnet new webapi --no-https false`.

The project references Microsoft.AspNetCore.App 2.1.2:
`<PackageReference Include="Microsoft.AspNetCore.App" Version="2.1.2" />`.

I then changed the csproj file to add a runtime identifier for the target environment, adding:
`<RuntimeIdentifiers>win7-x64</RuntimeIdentifiers>`. 
The version of windows on the target machine is `Version    6.1.7601 Service Pack 1 Build 7601`.

I then added this to the csproj file to ensure that the published artefacts had no dependencies on the runtime store:
`<PublishWithAspNetCoreTargetManifest>false<PublishWithAspNetCoreTargetManifest>`.

The project source is here: https://github.com/gkinsman/kestrel-sample

I ran `dotnet restore`, and then `dotnet publish -c Debug -r win7-x64 --self-contained`. I zipped up the win-x64 folder in the debug output folder, and copied it over to the target machine.

I then opened up a powershell prompt, and tried to execute the executable generated by dotnet publish. I received the following error:

```
c:\temp\fooo\f>kestrel-sample.exe
Error:
 An assembly specified in the application dependencies manifest (kestrel-sample
.deps.json) was not found:
   package: 'Microsoft.AspNet.WebApi.Client', version: '5.2.6'
   path: 'lib/netstandard2.0/System.Net.Http.Formatting.dll'
```

Indeed, there is no `Microsoft.AspNet.WebApi.Client` assembly in the output publish directory, despite my efforts to remove the dependency on the runtime store during publish. I don't think there's any problems with the target machine here, as the error is directly related to the missing assembly referenced in the deps.json file.

Is there anything I'm missing here?

Thanks,
George

**Comment by Tratcher** [comment]
@JunTaoLuo @dougbu

**Comment by JunTaoLuo** [comment]
@gkinsman, I am unable to reproduce your issue. Using your sample and the command `dotnet publish -c Debug -r win7-x64 --self-contained` I'm able to run the app. Note that I removed `<PublishWithAspNetCoreTargetManifest>false<PublishWithAspNetCoreTargetManifest>` since that no longer applies to 2.1 apps.

The Microsoft.AspNet.WebApi.Client package includes the System.Net.Http.Formatting.dll assembly and it does show up in the published output. Are you running the exe from the published output? By default this should be in the bin/Debug/netcoreapp2.1/win7-x64/publish/ directory.

**Comment by gkinsman** [comment]
Hi,

Thanks for getting back to me so soon - the executable was being run from the parent directory and not the published output, which worked when tried. Apologies for the false alarm!

Thanks!
