### ISSUE TITLE
Move Microsoft.AspNetCore.DataProtection.Redis to production status

### ISSUE THREAD

**Issue by blowdart** [aspnet/Home#3379]
The Redis store is still pre-release, but people are using it. We should move it to production status if we feel it's ready.

@Eilon

**Comment by Eilon** [comment]
We'll need to discuss with @DamianEdwards . Maybe start with a mail thread?

**Comment by natemcmaster** [comment]
Work items:

- [ ] Enable some actual functional tests which connect to Redis (should be easy to do with Docker and VSTS)
- [ ] Update branding to version as 2.2
- [ ] Update deploy configs to move the package into the 'ship' group

**Comment by Tratcher** [comment]
Related: https://github.com/aspnet/Caching/issues/24
