### ISSUE TITLE
IApplicationLifetime.StopApplication have no influence on IHostedService cancellation tokens

### ISSUE THREAD

**Issue by v-zubritsky** [aspnet/Home#3384]
I've encountered an unexpected behavior with `IHostedService` implementation, cancellation tokens passed to it and `IApplicationLifetime` interface.

I have two hosted services, both of which perform some initialization on start, and if it succeeds, they do their work in background. But if initialization fails, I'd like to stop the application at all, as far as this background work is critical.

I inject `IApplicationLifetime` into services and call `StopApplication` on it in case of initialization failure. Application does stop, but cancellation tokens, passed to my `IHostedServices` and provided further for graceful shutdown handling, are not cancelled for some reason. 

I have to link those tokens with `IApplicationLifetime.ApplicationStopping` to handle this issue, but this behavior doesn't seem too obvious.

```
public Task StartAsync(CancellationToken cancellationToken)
{
    var stoppingTokenSource = 
        CancellationTokenSource.CreateLinkedTokenSource(
            cancellationToken, 		 
            this.applicationLifetime.ApplicationStopping);
    ...
}
```

Repo to see this behavior reproduced is available by [link](https://github.com/v-zubritsky/CancellationTokenSample).

`Microsoft.AspNetCore.App 2.1.1` is used

`dotnet --info` outputs
```
.NET Core SDK (reflecting any global.json):
 Version:   2.1.302
 Commit:    9048955601

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.302\

Host (useful for support):
  Version: 2.1.2
  Commit:  811c3ce6c0

.NET Core SDKs installed:
  2.1.201 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.302 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
```

**Comment by Eilon** [comment]
This issue was moved to aspnet/Hosting#1513
