### ISSUE TITLE
Using custom ILoggerProvider and IServiceFactoryProvider breaks logging scopes of WebHost

### ISSUE THREAD

**Issue by schuettecarsten** [aspnet/Home#3395]
Create a sample AspNetCore application. Add a custom logging Framework that implements ILoggerProvider. Observe the behaviour of logging scopes, for each request you get several scopes that contain details about the connection and the request.

Now add a custom DI container framework that implements IServiceFactoryProvider and a observe again. The logging scopes are lost.

You can see that your LoggerProvider implementation is initialized twice. One time immediately after the start of the application, when the WebHost is initialized. After that, the custom DI container is registered and the logger is initialized again. Also, a new IExternalScopeProvider is registered at the LoggerProvider.

The problem seems to be that the WebHost still uses the old, orphaned scope provider.

**Comment by davidfowl** [comment]
This might be related to these changes https://github.com/aspnet/Hosting/commit/6b095cf533950e7fc93ebc475093bafac70058cb

cc @pakrym

**Comment by muratg** [comment]
This issue was moved to aspnet/Hosting#1536
