### ISSUE TITLE
Does the API always stay as version 1?

### ISSUE THREAD

**Issue by DanJ210** [aspnet/Home#3397]
I was brought here from the OpenAPI Swagger doc when clicking product feedback. Fantastic presentation and well updated by the way.

My only issue is about the version. How does the version work? Why leave a version at all if it's only going to be a V1? Or is there another parameter that increments this?

**Comment by pranavkm** [comment]
Is this the version in the swagger.json? 

```js
   "info": {
       "version": "v1",
       "title": "API V1"
   },
```

**Comment by DanJ210** [comment]
Yes that's the version. Do we manually change this as we go?

**Comment by pranavkm** [comment]
@dougbu do you know if either of the Swagger tools have any guidance on versioning? Do they do anything clever to infer it?

**Comment by Eilon** [comment]
This issue was moved to aspnet/Mvc#8333

**Comment by Eilon** [comment]
This issue was moved to aspnet/Mvc#8334
