### ISSUE TITLE
Where is @(EfMigrations) sourced from?

### ISSUE THREAD

**Issue by neilmulhy** [aspnet/Home#3399]
**Background**
I have 2 websites:
- One I created using the web application core 2.1 template which is not processing the migrations when I publish to staging, using web deploy.
- Another I created using the web application core 2.0 template which does process migration when I publish to staging, using web deploy.

For info, a difference between the 2 website solutions apart from the template version is that the working website solution only has one database context whilst the one that doesn't work has separate identity and application db contexts.

**Investigation**
I've increased the logging level around the build task (Tools -> Options -> Projects and Solutions -> Build and Run -> MSBuild project build output verbosity) in VS2017 and I've tracked it down to the following line on the solution that doesn't call the GenerateEFSQLScripts task:

`Task "GenerateEFSQLScripts" skipped, due to false condition; ('$(_IsAspNetCoreProject)' == 'true' And '$(IsGenerateEFSQLScriptsDisabled)' != 'true' And @(EfMigrations) != '') was evaluated as ('true' == 'true' And '' != 'true' And  != '').`

**Question / Issue**
It looks as though the issue is to do with @(EfMigrations) being null or empty. Can anyone let me know where this gets picked up from and how I can get migrations back to being processed as part of publishing to staging in my v2.1 website?

**Comment by ajcvickers** [comment]
@Eilon @bricelam This looks like a publishing issue; either of you know which repo it should go to?

**Comment by neilmulhy** [comment]
@ajcvickers thanks for trying to get this issue rolling. It is a publish issue.

I've continued trying to investigate this and found a couple of similar issues in earlier releases but would like to know what the official recommendation is for this issue I'm encountering in asp.net core 2.1.

Find section in following page: Publishing project with Entity Framework migration fails
[VS2017 known issues](https://github.com/aspnet/Tooling/blob/master/known-issues-vs2017.md)

Find section in following page: Sample MsDeploy Profile With Destination Connection String & EF Migrations
[Publish profile customisation](https://github.com/aspnet/websdk)

@Eilon @bricelam - can you please assist @ajcvickers on where to put this so I can start to get a resolution for it?

**Comment by neilmulhy** [comment]
Another bit of information, running dotnet ef dbcontext list --json from the command line picks up the correct database contexts configured in both websites and I can process migrations (add-migation / update-database) locally which shows this to be a publish issue.

**Comment by bricelam** [comment]
@vijayrkn

**Comment by vijayrkn** [comment]
@neilmulhy 

Can you check your profilename.pubxml.user file (Under Properties\PublishProfiles) and see if there is an entry similar to this

```
  <ItemGroup>
    <DestinationConnectionStrings Include="ShoppingCartConnection">
      <Value>Data Source=tcp:dbserver.database.windows.net,1433;Initial Catalog=shoppingcartdbdb_db;User Id=appUser@dbserver;Password=password</Value>
    </DestinationConnectionStrings>
  </ItemGroup>
  <ItemGroup>
    <EFMigrations Include="ShoppingCartContext">
      <Value>Data Source=tcp:dbserver.database.windows.net,1433;Initial Catalog=shoppingcartdbdb_db;User Id=efMigrationUser@dbserver;Password=password</Value>
    </EFMigrations>
  </ItemGroup>
```

If not, it means that EF migrations is not configured from the publish dialog. You can right click project -> Publish -> Click Configure.

![image](https://user-images.githubusercontent.com/3981619/44105316-2931fd2c-9fa6-11e8-8d70-bdf528110bc8.png)

In the settings page, please make sure both these checkboxes are checked.

**Comment by neilmulhy** [comment]
Hi @vijayrkn thanks for coming back to me.

Neither the XML you've described above (Under Properties\PublishProfiles) nor the last two options are available in my publish profile. Below is what I see when I create a new profile. Tbh, I don't recall seeing this option when I developed my first website using asp.net core 2.0? Also, The other strange thing is, that this option isn't available in my solution that processes migrations. If it helps, I'm using VS2017 15.7.4.

![image](https://user-images.githubusercontent.com/33902835/44105980-3ced7fc2-9feb-11e8-9991-2e3ab072c5e5.png)

**Comment by vijayrkn** [comment]
Do you have a similar entry in the appsettings.json? 

```
  "ConnectionStrings": {
    "DefaultConnection": "Server=(localdb)\\mssqllocaldb;Database=aspnet-WebApplication11-53bc9b9d-9d6a-45d4-8429-2a2761773502;Trusted_Connection=True;MultipleActiveResultSets=true"
  },
```

Also what do you get when you run `dotnet ef dbcontext list --json` from this project?

**Comment by vijayrkn** [comment]
I just tried adding the above 2 connection strings and the dialog seems to be handling it well.

![image](https://user-images.githubusercontent.com/3981619/44108104-3fa1b93c-9fae-11e8-9bf6-c7d2c624b399.png)

Is there any chance you can give us a sample project?

As a work-around,  you can manually add this to the pubxml or pubxml.user file and it would work 

```
  <ItemGroup>
    <DestinationConnectionStrings Include="ShoppingCartConnection">
      <Value>Data Source=tcp:dbserver.database.windows.net,1433;Initial Catalog=shoppingcartdbdb_db;User Id=appUser@dbserver;Password=password</Value>
    </DestinationConnectionStrings>
  </ItemGroup>
  <ItemGroup>
    <EFMigrations Include="ShoppingCartContext">
      <Value>Data Source=tcp:dbserver.database.windows.net,1433;Initial Catalog=shoppingcartdbdb_db;User Id=efMigrationUser@dbserver;Password=password</Value>
    </EFMigrations>
  </ItemGroup>
```

**Comment by vijayrkn** [comment]
you can use Send Feedback -> Report a problem from VS and attach the sample project there. 
Once it is done, please share a link and I will take a look. 

![image](https://user-images.githubusercontent.com/3981619/44110594-fe240210-9fb4-11e8-81e7-64d31e610df6.png)

**Comment by neilmulhy** [comment]
Thanks @vijayrkn 

I've managed to re-create the issue creating a new sample solution called WebPublishTest. I've uploaded it to a new problem I've raised called "Migrations are not being processed when publishing solution in VS2017".

It's currently under consideration. When I get a link through, I'll add it to this issue.

For info, when I try to publish with the sample solution, the end of the logs looks as below:

```
    Using "GenerateRuntimeConfigurationFiles" task from assembly "C:\Program Files\dotnet\sdk\2.1.301\Sdks\Microsoft.NET.Sdk\targets\..\tools\net46/Microsoft.NET.Build.Tasks.dll".
    Target "_PublishNoBuildAlternative" skipped, due to false condition; ('$(NoBuild)' == 'true') was evaluated as ('' == 'true').
    WebPublishTest -> D:\Dev\dotnet\WebPublishTest\WebPublishTest\obj\Release\netcoreapp2.1\win-x64\PubTmp\Out\
    Target "_DotNetCLIPostPublish" skipped, due to false condition; ('$(DeployOnBuild)' != 'true') was evaluated as ('true' != 'true').
    Target "_CopyWebJobFilesToIntermediateOutputPath" skipped, due to false condition; ('$(_PublishProjectType)' == 'WebJob') was evaluated as ('AspNetCore' == 'WebJob').
    Using "TransformWebConfig" task from assembly "C:\Program Files\dotnet\sdk\2.1.301\Sdks\Microsoft.NET.Sdk.Publish\build\netstandard1.0\..\..\tools\net46\Microsoft.NET.Sdk.Publish.Tasks.dll".
    Configuring the following project for use with IIS: 'D:\Dev\dotnet\WebPublishTest\WebPublishTest\obj\Release\netcoreapp2.1\win-x64\PubTmp\Out\'
    No web.config found. Creating 'D:\Dev\dotnet\WebPublishTest\WebPublishTest\obj\Release\netcoreapp2.1\win-x64\PubTmp\Out\web.config'
    Configuring project completed successfully
    Task "TransformAppSettings" skipped, due to false condition; ('$(_IsAspNetCoreProject)' == 'true' And '$(IsTransformAppSettingsDisabled)' != 'true' And @(DestinationConnectionStrings) != '') was evaluated as ('true' == 'true' And '' != 'true' And  != '').
'----- BIT THAT SKIPS THE EF SCRIPTS -----
    Task "GenerateEFSQLScripts" skipped, due to false condition; ('$(_IsAspNetCoreProject)' == 'true' And '$(IsGenerateEFSQLScriptsDisabled)' != 'true' And @(EfMigrations) != '') was evaluated as ('true' == 'true' And '' != 'true' And  != '').
'----------------------------------------------
    Task "GenerateRunCommandFile" skipped, due to false condition; ('$(_IsWebJobProject)' == 'true' And '$(IsGenerateRunCommandFileDisabled)' != 'true') was evaluated as ('' == 'true' And '' != 'true').
    Task "MakeDir" skipped, due to false condition; (!Exists('$(PublishIntermediateTempPath)')) was evaluated as (!Exists('D:\Dev\dotnet\WebPublishTest\WebPublishTest\obj\Release\netcoreapp2.1\win-x64\PubTmp\')).
    Deleting file "D:\Dev\dotnet\WebPublishTest\WebPublishTest\obj\Release\netcoreapp2.1\win-x64\PubTmp\WebPublishTest.SourceManifest.xml".
    Deleting file "D:\Dev\dotnet\WebPublishTest\WebPublishTest\obj\Release\netcoreapp2.1\win-x64\PubTmp\WebPublishTest.Parameters.xml".
    Creating "D:\Dev\dotnet\WebPublishTest\WebPublishTest\obj\Release\netcoreapp2.1\win-x64\PubTmp\WebPublishTest.SourceManifest.xml" because "AlwaysCreate" was specified.
    Creating "D:\Dev\dotnet\WebPublishTest\WebPublishTest\obj\Release\netcoreapp2.1\win-x64\PubTmp\WebPublishTest.Parameters.xml" because "AlwaysCreate" was specified.
    Using "CreateManifestFile" task from assembly "C:\Program Files\dotnet\sdk\2.1.301\Sdks\Microsoft.NET.Sdk.Publish\build\netstandard1.0\..\..\tools\net46\Microsoft.NET.Sdk.Publish.Tasks.dll".
    Using "CreateParameterFile" task from assembly "C:\Program Files\dotnet\sdk\2.1.301\Sdks\Microsoft.NET.Sdk.Publish\build\netstandard1.0\..\..\tools\net46\Microsoft.NET.Sdk.Publish.Tasks.dll".
    Using "ValidateParameter" task from assembly "C:\Program Files\dotnet\sdk\2.1.301\Sdks\Microsoft.NET.Sdk.Publish\build\netstandard1.0\..\..\tools\net46\Microsoft.NET.Sdk.Publish.Tasks.dll".
    Task "CreateProperty" skipped, due to false condition; (!$(_UseWMSVC) And $(NormalizePublishSettings)) was evaluated as (!true And true).
    Using "NormalizeServiceUrl" task from assembly "C:\Program Files\dotnet\sdk\2.1.301\Sdks\Microsoft.NET.Sdk.Publish\build\netstandard1.0\..\..\tools\net46\Microsoft.NET.Sdk.Publish.Tasks.dll".
    Task "GetPassword" skipped, due to false condition; ('$(Password)' == '' And '$(IsGetPasswordEnabled)' == 'true') was evaluated as ('' == '' And '' == 'true').
    Using "VSMSDeploy" task from assembly "C:\Program Files\dotnet\sdk\2.1.301\Sdks\Microsoft.NET.Sdk.Publish\build\netstandard1.0\..\..\tools\net46\Microsoft.NET.Sdk.Publish.Tasks.dll".
    Package/Publish task Microsoft.NET.Sdk.Publish.Tasks.MsDeploy.VSMSDeploy load assembly Microsoft.Web.Deployment, Version=9.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
    Package/Publish task Microsoft.NET.Sdk.Publish.Tasks.MsDeploy.VSMSDeploy load assembly Microsoft.Web.Delegation, Version=7.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
    Starting Web deployment task from source: manifest(D:\Dev\dotnet\WebPublishTest\WebPublishTest\obj\Release\netcoreapp2.1\win-x64\PubTmp\WebPublishTest.SourceManifest.xml) to Destination: auto().
    Using ID '140133aa-e0d4-423d-a2c6-4e7b40056a55' for connections to the remote server.
    Using ID 'd78c6cce-f30f-4f90-8c03-39fc4dc42cb4' for connections to the remote server.
    Updating file (com.foo.staging\web.config).
    Updating file (com.foo.staging\WebPublishTest.deps.json).
    Updating file (com.foo.staging\WebPublishTest.dll).
    Updating file (com.foo.staging\WebPublishTest.pdb).
    Updating file (com.foo.staging\WebPublishTest.runtimeconfig.json).
    Updating file (com.foo.staging\WebPublishTest.Views.dll).
    Updating file (com.foo.staging\WebPublishTest.Views.pdb).
    Successfully executed Web deployment task.
    Publish Succeeded.
    Task "MSdeploy" skipped, due to false condition; ('$(UseMsdeployExe)' == 'true') was evaluated as ('' == 'true').
Done building project "WebPublishTest.csproj".
Web App was published successfully http://staging.foo.com/
========== Build: 3 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
========== Publish: 1 succeeded, 0 failed, 0 skipped ==========
```

**Comment by vijayrkn** [comment]
@neilmulhy - Thank you for providing the repro project. The reason the db section and EF section is not showing up is because tooling works on the assumption that the appsettings.json is in the root of the project.  In the sample project, the file is in the config folder. If you move the config file to the root of the project and  update the Program.cs to reflect the updated location, then it works.

```
                        config.AddJsonFile("appsettings.json", optional: false, reloadOnChange: true);
                        config.AddJsonFile($"appsettings.{builderContext.HostingEnvironment.EnvironmentName}.json", optional: true, reloadOnChange: true);
```

![image](https://user-images.githubusercontent.com/3981619/44162820-4fc9a400-a076-11e8-9ea7-2dd8f5af30a3.png)

We will look at the possibility of providing a way to sepecify where the config file resides so that this does not always have to be at the root of the project. Since this is a VS issue, you can continue to track the progress of this issue in the develper community site - https://developercommunity.visualstudio.com/content/problem/310975/migrations-are-not-being-processed-when-publishing.html

Since this is not a runtime issue, can we close this issue here in github?

**Comment by neilmulhy** [comment]
Thanks for highlighting that for me.

Before closing this off, the thing I don't understand is my other solution with one db context and appsettings also in the config folder (not root) processes the migrations without the Entity Framework Migrations section displaying in the publish profile.

Are you or any one on the dev team able to shed light on what @(EfMigrations) is in the build / publish process? 

Task "GenerateEFSQLScripts" skipped, due to false condition; ('$(_IsAspNetCoreProject)' == 'true' And '$(IsGenerateEFSQLScriptsDisabled)' != 'true' And **@(EfMigrations)** != '') was evaluated as ('true' == 'true' And '' != 'true' And  != '').

Is this set to true if any of the dbcontext checkboxes are ticked?

One difference could be that I originally had the appsettings.json in the root and may have done a publish with the file there but then moved it to the config folder at a later stage. Having said that though, the publish profile xml file doesn't have anything in there to do with entity framework.

**Comment by vijayrkn** [comment]
@neilmulhy - Can you look at the profilename.pubxml.user file? This should have that info. Once a project is configured to run migrations, it will continue to run it until it is disabled.

**Comment by neilmulhy** [comment]
That's the badger! Thanks @vijayrkn for your help getting my head around what's been going on here! This issue can be closed.
