### ISSUE TITLE
The specified CGI application encountered an error and the server terminated the process.

### ISSUE THREAD

**Issue by kontacthimanshu** [aspnet/Home#3400]
Hi,
I am hosting an ASP.Net Core 2.1.2 based application in Azure App Service I am getting this error intermittently:

"The specified CGI application encountered an error and the server terminated the process."

I read about others facing this problem and applied the fixes suggested SO. But none seem to work. Below is how my Program.cs code looks like. 

```c#
public class Program
    {
        public static void Main(string[] args)
        {
            CreateWebHostBuilder(args).Build().Run();
        }

        public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                    .CaptureStartupErrors(true)
                    .UseSetting("detailedErrors", "true")
                    .UseKestrel()
                    .ConfigureServices(services => services.AddAutofac())
                    .UseIISIntegration()
                    .UseStartup<Startup>();
    }
```

Here is how my appsettings.json looks like:

```json
{
  "ConnectionStrings": {
    "DefaultConnection": "Server=(localdb)\\mssqllocaldb;Database=aspnet-iBank.Web-73825CB2-410E-4498-BC7F-8123B49099A1;Trusted_Connection=True;MultipleActiveResultSets=true"
  },
  "DocumentDbClient": {
    "EndpointUri": "https://ibank.documents.azure.com:443/",
    "AuthorizationKey": ""
  },
  "FacebookAuthSettings": {
    "AppId": "457472338022113",
    "AppSecret": ""
  },
  "Logging": {
    "IncludeScopes": false,
    "LogLevel": {
      "Default": "Warning"
    },
    "Console": {
      "LogLevel": {
        "Default": "Warning"
      }
    }
  },
  "JwtIssuerOptions": {
    "Issuer": "webApi",
    "Audience": "https://secure.ibank.com/"
  },
  "appuserscollection": "ibankcoll",
  "dbname": "ibankdb",
  "defaultcollectionname": "ibankcoll",
  "endpoint": "https://ibank.documents.azure.com:443/",
  "authkey": "",
  "friendcollection": "friends",
  "inviteFromEmail": "noreply@ibank.com",
  "inviteFromName": "iBank",
  "cancelFromEmail": "noreply@ibank.com",
  "cancelFromName": "iBank",
  "inviteEmailHTMLTemplate": "FriendRequestEMail_HTML.txt",
  "inviteEmailPlainTemplate": "FriendRequestEMail_PlainText.txt",
  "registrationEmailHTMLTemplate": "RegistrationEMail_HTML.txt",
  "registrationEmailPlainTemplate": "RegistrationEMail_PlainText.txt",
  "activationConfirmHTMLTemplate": "ActivationConfirm_HTML.txt",
  "forgotPasswordHTMLTemplate": "ForgotPassword_HTML.txt",
  "inviteEmailSubject": "Hello!",
  "ApplicationInsights": {
    "InstrumentationKey": ""
  },
  "blobStorageConnString":"",
  "blobStorageContainer": "ibankimages",
  "YodleeBaseUrl": "https://usyichannel.api.yodlee.com/ysl/",
  "cobrandLogin": "",
  "cobrandPassword": "",
  "ibankbaseurl": "https://secure.ibank.com/",
  "fromEmail": "noreply@secure.ibank.com",
  "StripeKey": "",
  "StripePlanId": "",
  "cobrandName": "",
  "redisConnString": "",
  "supportEMail": "noreply@secure.ibank.com",
  "SENDGRID_API_KEY": "",
  "SendGridApiKey": "",
  "CssVersion": "14"
}
```

Can anyone please suggest what could be the issue and how to fix it?

Many thanks,
Himanshu.

**Comment by halkor** [comment]
I'm getting the same error. In my case it seems to be a problem with the data protection keys. I see _a lot_ of these lines in the log, followed by a StackOverflowException.

[Trace] Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector: Performing unprotect operation to key {ce776988-3741-4b5e-bb2a-150a7473f4ea} with purposes ('D:\home\site\wwwroot', 'Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationMiddleware', 'Cookies', 'v2').

Deleting the keys from disk seems to help, however the problem happens again after a while.

**Comment by Tratcher** [comment]
@halkor did the StackOverflowException give you a stack trace?

**Comment by halkor** [comment]
@Tratcher No, there was no stack trace.
I'm now suspecting that the StackOverflowException actually happens elsewhere and that the DataProtector has nothing to do with it. I have done some changes to the code and our web site has been running fine since then. I will monitor it closely the next couple of days.

**Comment by Eilon** [comment]
Hi. We're closing this issue as no response or updates have been provided in a timely manner and we have been unable to reproduce it. If you have more details and are encountering this issue please add a new reply and re-open the issue.

**Comment by kontacthimanshu** [comment]
We are constantly getting this error in two of our App services.
