### ISSUE TITLE
Unable to use IFormFile with ApiController in 2.1

### ISSUE THREAD

**Issue by mitchellj** [aspnet/Home#3403]
When we are trying to use `IFormFile` it works perfectly when we are not using `[ApiController]`, as soon as we introduce `ApiController` one of two things happens 

1) If we do not prefix with `[FromForm]` we get a `Serialization` exception which generates a `Bad Request` response. 
2) If we do prefix `FromForm` to the IFormFile then it becomes `null` 

In order to get IFormFile to work we need to remove `ApiController` completely in which case the IFormFile becomes completely propagated correctly.

**Comment by Eilon** [comment]
This issue was moved to aspnet/Mvc#8311
