### ISSUE TITLE
Better Way to Prevent UseStatusCodePagesWithRedirects to ignore StaticFiles?

### ISSUE THREAD

**Issue by shawnwildermuth** [aspnet/Home#3404]
While debugging file mapping in static files I realized my use of UseStatusCodePages API was redirecting for StaticFiles that were missing or mis-mapped. 

For example:

```
    public void Configure(IApplicationBuilder app, IHostingEnvironment env)
    {
      // Standard Way to handle this makes 
      // Static Files return 302 then a 200 on the redirect
      app.UseStatusCodePagesWithRedirects("/Error");
      app.UseStaticFiles();
      app.UseMvc();
    }
```

This way, the Static Files will return a 302 that turns into a 200 on a redirect. But I'd prefer to have the actual 404 so I can more easily find the missing files. This is what I came up with but it feels too hacky. Either there is a better way that I missed or I'd like to propose a new feature.

```
    public void Configure(IApplicationBuilder app, IHostingEnvironment env)
    {

      const string IGNORE = "Ignore";

      // Standard Way to handle this makes 
      // Static Files return 302 then a 200 on the redirect
      //app.UseStatusCodePagesWithRedirects("/Error");
      //app.UseStaticFiles();

      // Only way I can see how to return real 404's
      app.UseStatusCodePages(new StatusCodePagesOptions()
      {
        HandleAsync = ctx =>
        {
          // Ignore if from Static Files
          if (ctx.HttpContext.Response.StatusCode != 404 &&
          ctx.HttpContext.Items.ContainsKey(IGNORE) &&
          ((bool)ctx.HttpContext.Items[IGNORE]))
          {
            // Do Nothing
          }
          else
          {
            ctx.HttpContext.Response.Redirect("/error/404");
          }

          return ctx.Next.Invoke(ctx.HttpContext);
        }
      });

      app.UseStaticFiles(new StaticFileOptions()
      {
        OnPrepareResponse = ctx =>
        {
          if (ctx.Context.Response.StatusCode == 404)
          {
            // Mark this as ignore
            ctx.Context.Items.Add(IGNORE, true);
          }
        }
      });


      app.UseMvc();
    }
```

Here's a working Example:

https://github.com/shawnwildermuth/wilderexamples/tree/master/NoStatusCodeStaticFiles

**Comment by Tratcher** [comment]
Rather than using WithRedirects, have you tried WithReExectue?

**Comment by Tratcher** [comment]
That example doesn't actually work does it? OnPrepareResponse is not called if it can't find the file, the request falls through to the next middleware. There's an implicit 404 middleware at the end of the pipeline.

**Comment by shawnwildermuth** [comment]
It does. I'll try with execute

**Comment by parentelement** [comment]
I believe adding the static files middleware first will remedy the issue, or does it pass through to the next() delegate on a 404?

**Comment by shawnwildermuth** [comment]
No, putting it first has no effect for some reason. I thought so too. But @Tratcher was correct, this works exactly the way I wanted:

      app.UseStatusCodePagesWithReExecute("/Error");
      app.UseStaticFiles();
