### ISSUE TITLE
'kvm use -p' on Windows 10 doesn't persist across different prompts

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/Home#341]
@shanselman and I are both seeing strange behavior on Windows 10 machines when trying to run `kvm use -p`. If you open a VS dev cmd prompt, a standard cmd prompt, and a PowerShell prompt, and try `kvm use -p` in each one and then reopening the other prompts, you'll see that it doesn't stick properly.

On @shanselman's machine, the VS dev cmd prompt never gets an active session to stick across prompts. On mine, the PS prompt always had a different active KRE to the other two prompts.

Trying the same thing on my Windows 8.1 machine worked as expected.

**Comment by davidfowl** [comment]
File this bug on the kvm repository (dotnetsdk)
