### ISSUE TITLE
Suggestion: Change log message "Policy execution successful" to "CORS policy execution successful"

### ISSUE THREAD

**Issue by cmeeren** [aspnet/Home#3419]
I spent a while trying to figure out why I had so many mysterious "Policy execution successful" log messages in my app. After [a good while](https://github.com/App-vNext/Polly/issues/491#issuecomment-411490473) I tracked it down to `Microsoft.AspNetCore.Cors.Infrastructure.CorsService`. I suggest changing the message to "CORS policy execution successful" (other similar messages from CORS might be changed similarly). This will make it clear just by looking at the logs what this message means.

**Comment by natemcmaster** [comment]
This is a very low priority for our team so we're not likely to spend time on this, but if you want to send a PR, the code for the logging messages is here https://github.com/aspnet/CORS/blob/8e4d3aacb3153f2a1338e228f0ea096e242d746a/src/Microsoft.AspNetCore.Cors/Internal/CORSLoggerExtensions.cs#L38-L41. Feel free to tag me and I can help get it merged.

**Comment by cmeeren** [comment]
Great, which branch would you like a PR against?

**Comment by natemcmaster** [comment]
release/2.2. Thanks in advance!
