### ISSUE TITLE
Localizable string resource support.

### ISSUE THREAD

**Issue by ebickle** [aspnet/Home#342]
Please consider adding support for localizable string resources into asp.net 5 / k runtime.

I have a few large existing sites that use resx based resource files for localization extensively, and they're currently impossible to port to the latest CTP. While I understand its possible to create a system that brings up views based on the current culture or language, it leads to a duplication of markup. Its also inappropriate when localization is required for strings that aren't located in views - validation error messages, authentication email and sms content, etc.

Please bring back resx support or an alternate comparable solution. In previous releases localization was treated with a lower priority, which puts international customers and users at a significant disadvantage.

**Comment by Eilon** [comment]
This is being worked on. You can use resx files already (we do it in lots of repos here).

@DamianEdwards did you have a chance to post a speclet of your prototype stuff somewhere?

**Comment by Tragetaschen** [comment]
https://github.com/DamianEdwards/i18nStarterWeb

**Comment by ebickle** [comment]
Thanks. There's lot a lot of info about this on the web, just quite a few people having the same issue as me.

There's no ability to create resx files in the IDE, it doesn't show up in the Add New Item dialog. There also doesn't appear to be any way to turn on code generation when a resx file saves. I'm assuming the later part is by design, but it creates challenges when trying to access static resources from code files - for example, when throwing exceptions.

Am I missing something obvious, or are all resources accessed via dependency injection now?

**Comment by davidfowl** [comment]
> There's no ability to create resx files in the IDE, it doesn't show up in the Add New Item dialog. There also doesn't appear to be any way to turn on code generation when a resx file saves. I'm assuming the later part is by design, but it creates challenges when trying to access static resources from code files - for example, when throwing exceptions.

This will come back in a later version of visual studio.

> Am I missing something obvious, or are all resources accessed via dependency injection now?

See https://github.com/aspnet/Localization
