### ISSUE TITLE
ASP.Net Core 2.1 Upgrade Error

### ISSUE THREAD

**Issue by eguzelkucuk** [aspnet/Home#3423]
When we upgraded our .Net core 1.x application to version 2.1 we got this error

**Cannot find reference assembly 'Microsoft.Win32.Primitives.dll'**

Can you help us with this?

**Comment by Eilon** [comment]
@eguzelkucuk sorry for the delay getting back to you. Do you have any more info about the app that you can share? Do you have the app on GitHub?
