### ISSUE TITLE
.Netcore SDK 2.1.302 not being used, resolves to older version

### ISSUE THREAD

**Issue by yadavvineet** [aspnet/Home#3424]
I have installed the 2.1.302 version of SDK from downloads page. when i run the dotnet --version it shows "2.1.302" as correct.
When i try to run the Visual Studio or create  a new project (even from cli) the project refers to the SDK version 2.1.0. In the project i get the references in Dependencies as 
Dependencies
--Nuget
----Microsoft.AspNetCore.App(2.1.1)
--SDK
----Microsoft.AspNetCoew.App(2.1.1.)
----Microsoft.NETCore.App (2.1.0)

I am not able to use or target version 2.1.2 any how. i tried new SDK on new machine, and it worked correctly, but for somehow not updating older system.
Here is my version 
-----------------------

C:\temp\22312\494>dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.1.302
 Commit:    9048955601

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.302\

Host (useful for support):
  Version: 2.1.2
  Commit:  811c3ce6c0

.NET Core SDKs installed:
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.302 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by yadavvineet** [comment]
@rafsanulhasan Thanks for your response. 
My hosting server has 2.1.2 runtime installed. With current setup, when i try to deploy the application, it says Microsoft.Aspnetcore.app 2.1.1 is not found. They have the runtime and windows hosting package installed. Do they need to install any other package (like: ASP.NET Core Installer) as well on their server to run it. 

Also, please correct if get it wrong. If the version 2.1.2 of runtime is installed and i deploy a build with 2.1.1, it will automatically find the patch version and should be Ok. ??

**Comment by rafsanulhasan** [comment]
What VS version are you using? Mine is 15.7.6 (VS2017).
Besides check the project file 
```<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    **<TargetFramework>netcoreapp2.1</TargetFramework>**
    <UserSecretsId>API-20161122013547</UserSecretsId>
    <AssetTargetFallback>$(AssetTargetFallback);portable-net45+win8+wp8+wpa81;</AssetTargetFallback>
  </PropertyGroup>```

```

  <ItemGroup>
    <PackageReference Include="Autofac.Extensions.DependencyInjection" Version="4.2.2" />
    <PackageReference Include="Dapper" Version="1.50.4" />
    <PackageReference Include="FluentValidation.AspNetCore" Version="7.5.0" />
    <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.4.0" />
    <PackageReference Include="Microsoft.ApplicationInsights.DependencyCollector" Version="2.7.1" />
    <PackageReference Include="Microsoft.ApplicationInsights.Kubernetes" Version="1.0.0-beta8" />
    <PackageReference Include="Microsoft.ApplicationInsights.ServiceFabric" Version="2.1.1" />
    <PackageReference Include="Microsoft.Extensions.Logging.AzureAppServices" Version="2.1.1" />
    **<PackageReference Include="Microsoft.AspNetCore.App" />**
    <PackageReference Include="MediatR" Version="4.1.0" />
    <PackageReference Include="MediatR.Extensions.Microsoft.DependencyInjection" Version="4.1.0" />
    <PackageReference Include="Polly" Version="6.0.1" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="2.4.0" />
    <PackageReference Include="System.Reflection" Version="4.3.0" />
    <PackageReference Include="System.ValueTuple" Version="4.5.0" />
  </ItemGroup>```

your project file should the two lines marked bold:
1. netcoreapp21
2. In the package reference you should not specify the version.

After doing so, take a look at you Dependencies->SDK inside solution explorer, you'll find that there are two SDKs installed: **Microsoft.NETCore.App _2.1.0_** and **Microsoft.AspNetCore.App _2.1.1_**.

If you are okay with these changes try to redeploy it and check whether it is working.
I used ASP.NET Core 2.1 in this way and deployed it to Docker Container, it works. I didn't try to run it in any standalone Windows/Linux Servers or VM. You can also deploy it to Azure App Services to test Whether its running. If you successfully ran the code into Azure, you might have to check whether your hosting provider has the correct runtime installed on the server or VM.

**Comment by rafsanulhasan** [comment]
maybe 2.1.2 indicated release version whereas 2.1.1 in the releasing assembly version. This question is trickier to answer and I'm afraid, I don't know much about this.

**Comment by yadavvineet** [comment]
actually i was thinking how it makes different if i use the old sdk or runtime vs new. Since the older sdk/packages are being referred only the improvements in the runtime will be applied (at runtime) but new things might be limited at dev time. 

Thanks for you time and help @rafsanulhasan
