### ISSUE TITLE
Localization — Localization and Inheritance not working

### ISSUE THREAD

**Issue by ckams** [aspnet/Home#3426]
I am working on a pretty big project, with a lot of inheritance, where I have to target multiple locales.
Seems that Localization does not support inheritance?
Do I have to override every properties in every class to get these translated? At the same time, defeating the main concept of OOP???

**Comment by hishamco** [comment]
@ckams can you provide a minimal repo to reproduce the issue

**Comment by ckams** [comment]
@hishamco 
Not enough time, but you can easily try with MS samples on github.

**Comment by Eilon** [comment]
@ckams can you provide more info on what you mean? Even a small code sample that shows what you're trying to do.

**Comment by ckams** [comment]
I will try to provide more info as soon as I can, but for now I am too busy.

Moreover, seems that for this problem, it will be hard to me to understand what happens, therefore, to provide more informations easily…

After the last update on the Debian host,(packages `(dotnet-sdk-2.1:amd64 (2.1.400-1, 2.1.401-1), dotnet-host:amd64 (2.1.2-1, 2.1.3-1), dotnet-hostfxr-2.1:amd64 (2.1.2-1, 2.1.3-1), dotnet-runtime-deps-2.1:amd64 (2.1.2-1, 2.1.3-1), aspnetcore-runtime-2.1:amd64 (2.1.2-1, 2.1.3-1), dotnet-runtime-2.1:amd64 (2.1.2-1, 2.1.3-1))`), seems that, **almost** all properties that were not translated—from inherited classes—are now behaving "as expected"—for the first time. **But few of them still not, and for now, I do not see why…**

I close this issue for now—I can reopen it later, add new reply…
