### ISSUE TITLE
How to deploy an unpublished dotnet-core project on iis like a dotnet project

### ISSUE THREAD

**Issue by pikadun** [aspnet/Home#3429]
我可以直接在iis上部署一个未发布的.net web项目，只要将项目目录指向工程目录就可以了；
但是我用同样的方法无法正确部署.net core项目，当我访问某个URL时，会得到404的页面。
![image](https://user-images.githubusercontent.com/32519715/44066243-e4819484-9fa1-11e8-8e75-5dd56ec49cd2.png)
![image](https://user-images.githubusercontent.com/32519715/44066247-e8c8274c-9fa1-11e8-818f-2012dc0a8d1e.png)
![image](https://user-images.githubusercontent.com/32519715/44066252-ee705200-9fa1-11e8-8e52-28fbc0ec1e0c.png)

**Comment by Tratcher** [comment]
Unpublished applications are not supported in IIS unless you use Visual Studio to run it directly.
https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/development-time-iis-support?view=aspnetcore-2.1
