### ISSUE TITLE
OptionsMonitorWrapper implementation backed by dictionary: interested in contribution?

### ISSUE THREAD

**Issue by chwarr** [aspnet/Home#3431]
In https://github.com/aspnet/Home/issues/2391, it looks like it was decided that a wrapper implementation of `IOptionsMonitor` would be useful if it properly handled named options. I have an implementation of a map-based `OptionsMonitorWrapper<T>` that I could contribute. Would you be interested in this still?

* Handles named options via a map.
* Does not have support for triggering listeners registered to `OnChanged`. `OnChanged` returns a dummy `IDisposable`.
    * I'd be open to adding this functionality iteratively.
* Not reader/writer thread-safe, but could be made so.

Excerpting from that issue, @HaoK said:

> Its not a perfect fit, since the wrapper today only takes 1 specific options instance. We could have it implement IOptionsMonitor and return that single instance for all named options as well as the default I guess. But this looks mostly like a test improvement/usage scenario...
>
> A 'real' wrapper for the monitor should take a `Dictionary<string, TOptions>` to use as the map...

**Comment by Eilon** [comment]
Tagging @HaoK @ajcvickers

**Comment by chwarr** [comment]
Tickle. Would such a contribution be welcome?

**Comment by chwarr** [comment]
I'm sorry, but I'm not following what you mean by "we no longer encourage any UseXyz() methods to take options instances". Can you clarify?

In our app, we're have our long-lived singletons consume `IOptionsMonitor` instances. The options are bound to config via calls to `OptionsConfigurationServiceCollectionExtensions.Configure<TOptions>(this IServiceCollection services, IConfiguration config)`. They use `IOptionsMonitor.CurrentValue` so that they will get up-to-date values when the underlying config file is changed. (I don't currently need to register for change callbacks.)

In order to unit test these classes, I found it useful to have a `OptionsMonitorWrapper` so that I can directly construct my singletons via new instead of having to create a service collection, add options to it, build a service provider, and then get the singleton.

E.g., I find this code simpler when testing:

```
var s = new Singleton(
    OptionsMonitorWrapper.For(new SingletonOptions { EnableFeatureA = true }));
Assert.True(s.DoSomething("hello"));
```

than

```
var sc = new ServiceCollection();
sc.Configure<SingletonOptions>(so => so.EnableFeatureA = true);
sc.AddSingleton<Singleton>();
var sp = sc.BuildServiceProvider();
var singleton = sp.GetRequiredService<Singleton>();
Assert.True(s.DoSomething("hello");
```

If I'm using options incorrectly, I'd be glad to hear your advice.

**Comment by HaoK** [comment]
That's fine (for testing), but we typically don't ship test only infrastructure in the main product assemblies which mostly is what OptionsWrapper is these days.  Back in the 2.0 timeframe we used OptionsWrapper in various UseXyz() methods which is why it was created in the first place.  But we have no plans on doing that for IOptionsMonitor which is why I don't think we should be making changes in this area.

I think your usage of a test wrapper is fine.  That said, many of our tests do just use options normally via a service collection.

**Comment by chwarr** [comment]
Understood. Thanks for clarifying.

**Comment by HaoK** [comment]
Thanks for your offer regardless!
