### ISSUE TITLE
httpCookies requireSSL in .net core mvc

### ISSUE THREAD

**Issue by mgolois** [aspnet/Home#3432]
I just wanted to confirm regarding the following web config setting in .net framework 4.5 mvc:
`<httpCookies requireSSL="true" />`

so in .net core mvc, should it be this:
`services.ConfigureApplicationCookie(o => o.Cookie.SecurePolicy = Microsoft.AspNetCore.Http.CookieSecurePolicy.Always);`

**Comment by Tratcher** [comment]
ConfigureApplicationCookie only affects one of the authentication cookies, not every cookie. You need to use the CookiePolicy middleware to affect all cookies: https://github.com/aspnet/Security/blob/f084067d6a255fde3d12c07988157311ba52c51a/samples/CookiePolicySample/Startup.cs#L22-L32

**Comment by mgolois** [comment]
Thank you, @Tratcher
