### ISSUE TITLE
SecurityProtocol Restriction

### ISSUE THREAD

**Issue by mgolois** [aspnet/Home#3433]
Currently migrating code from asp.net mvc 4 to asp.net mvc core, where is the best place to restrict Security Protocol?
Is it in Startup file in the Confgure method? or  in Program.cs in the Main() method()?
Or creating a middleware is recommended?

//example of code:
ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;

**Comment by mgolois** [comment]
Yes @Tratcher , I saw that documentation, thanks for confirming.
What if it is a hard requirement to support a specific version, I just wanted to know, where you will put the tls restriction? Thanks

**Comment by Eilon** [comment]
@Tratcher / @blowdart - do we have any further guidance on this?

**Comment by Tratcher** [comment]
@mgolois you still didn't clarify if you're trying to set this for outbound connections (HttpClient) or inbound for one of the servers (HttpSys, IIS&Kestrel, Kestrel on the edge).

**Comment by mgolois** [comment]
Sorry @Tratcher  this is inbound for IIS/Kestrel

**Comment by Tratcher** [comment]
Ah. When using IIS + Kestrel TLS is primarily controlled by the OS (SChannel). @shirhatti IIS doesn't give you any TLS options right? There are no options available within your ASP.NET Core application.

**Comment by shirhatti** [comment]
Yes, what @Tratcher said is true. Http.Sys doesn't allow us(IIS) to control TLS 1.2 on a per binding basis. It can only be performed machine-wide by setting a reg key. Look at this [doc](https://docs.microsoft.com/en-us/windows-server/security/tls/tls-registry-settings#ssl-30) on how to disable SSL 3.0, TLS 1.0, and TLS 1.1.

**Comment by mgolois** [comment]
Thank you for clarifying and providing guidance!
