### ISSUE TITLE
Per response cache duration

### ISSUE THREAD

**Issue by JonasSamuelsson** [aspnet/Home#3436]
I'm using response caching and need to set the cache duration based on the content of the response.  
It would be nice if the caching middleware didn't overwrite the cache control header if it exists, I could then do something like thing

``` cs
[HttpGet, ResponseCache(Duration = 10)] // default cache duration 10 seconds
public object Get()
{
   Response.Headers[HeaderNames.CacheControl] = "public,max-age=60"; // override cache duration
   return new { message = "hello" };
}
```

**Comment by Tratcher** [comment]
This issue was moved to aspnet/Mvc#8285
