### ISSUE TITLE
Net Core SDK 2.1.400 ignore _ViewStart on Areas views on publish

### ISSUE THREAD

**Issue by alca259** [aspnet/Home#3438]
After upgrade to VS 15.8.1 and Net Core SDK 2.1.400, the _ViewStart on Areas views are ignored, only then publish to folder.

Steps: 
- Create a project with one Area
- Setup a dummy controller with a file _ViewStart.cshtml in the root of Views folder
- Load a layout or write something in the log
- Publish to local folder
- Copy to a IIS Site with native code and the same SDK installed.
- Access to dummy controller inside of the area

Sample log:
- Users controller have specified layout on Index view
- Roles controller not have specified layout on Index view, it take Layout from _ViewStart.cshtml

[AttachedLog.txt](https://github.com/aspnet/Home/files/2299811/AttachedLog.txt)
[LogFirstCall.txt](https://github.com/aspnet/Home/files/2299812/LogFirstCall.txt)

**Comment by pranavkm** [comment]
This issue was moved to aspnet/Mvc#8293
