### ISSUE TITLE
Website issues (//asp.net)

### ISSUE THREAD

**Issue by blubbll** [aspnet/Home#3445]
Reporting bug link broken:
1st
@https://www.asp.net/contact-us ("Report a Bug")
leads to
https://github.com/aspnet/Home/blob/dev/CONTRIBUTING.md#bugs-and-feature-requests

2nd:
@https://www.asp.net/mvc
pluralsight link broken
(http://pluralsight.com/microsoft/?utm_source=microsoft&utm_medium=sponsored-page&utm_content=aspdotnet-mvc5-fundamentals&utm_campaign=microsoft-sponsored-course)

**Comment by Eilon** [comment]
@blubbll thanks for the feedback, I will forward to the appropriate people.

**Comment by Eilon** [comment]
The first link should be https://github.com/aspnet/Home/blob/master/CONTRIBUTING.md#bugs-and-feature-requests.

Not sure what the second link should be.

**Comment by terrimorton** [comment]
Both of these links have now been updated. Thanks for the report!

**Comment by Eilon** [comment]
Thanks @terrimorton !
