### ISSUE TITLE
Add/New Scaffolded Item... missing from 2.2 projects Preview

### ISSUE THREAD

**Issue by damienbod** [aspnet/Home#3447]
When I create a new 2.2 ASP.NET Core MVC project with Identity, I cannot scaffold in the Identity Pages because the menu is missing in Visual Studio 

ASP.NET Core Preview 2.2:
 - MVC and Razor Pages: https://github.com/aspnet/Mvc

**Comment by Eilon** [comment]
This issue was moved to aspnet/Scaffolding#860
