### ISSUE TITLE
HttpClient HTTP 2.0 compatibility

### ISSUE THREAD

**Issue by callumelgrant** [aspnet/Home#345]
There's been a lot of news about HTTP 2.0 recently when the standard was finalised, and it's going to be supported in the next IIS but is there a general timeline to update HttpClient to work with HTTP 2.0 yet? I appreciate there's much bigger fish to fry at the moment, just curious about when this might happen.

**Comment by garora** [comment]
@callumelgrant - I agreed with you. Can you please provide me some link which provides documentation about HTTP2.0?

**Comment by aguacongas** [comment]
@garora https://http2.github.io/, and the katana implementation can help : https://github.com/MSOpenTech/http2-katana

**Comment by garora** [comment]
Thanks I will take a look

**Comment by SidharthNabar** [comment]
@callumelgrant  - Thanks for your interest in HttpClient and ASP.NET 5. HTTP/2 support in HttpClient (by adding it into the WinHttpHandler implementation) is on our roadmap but we don't have a set timeline yet.

Till then - The architecture of HttpClient allows you plugin a custom HttpMessageHandler object that handles the request-response transactions. So you could implement your own Handler that implements HTTP/2  and plug it in to the client. (See https://msdn.microsoft.com/en-us/library/hh193664(v=vs.118).aspx )

Hope this helps.

**Comment by callumelgrant** [comment]
@SidharthNabar Perfect, thanks!

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
