### ISSUE TITLE
Finally block in main() never executes?

### ISSUE THREAD

**Issue by MV10** [aspnet/Home#3451]
The _Serilog.AspNetCore_ repository's [README](https://github.com/serilog/serilog-aspnetcore) page demonstrates how to add Serilog support with a basic implementation of `main()` that uses a `finally` block to flush any remaining log entries, clean up connections, etc. I was troubleshooting an issue reported for the Serilog SQL Server sink by users with ASP.NET Core projects, so I set up a quick test based on that README. 

Like many of the slower sinks, the SQL sink writes in batches. I was running in debug, and for one test I closed the browser quickly and realized a few log entries were missing (I was using the default MVC template and had added log entries to `index.cshtml.cs` and the page had loaded). So I added a log entry to the `finally` block (as shown below) and _that_ was never output. 

I then put a breakpoint on that log call, and the breakpoint was never hit.

I don't see this problem in a regular console program (the `finally` block does run as I'd expect). I'm guessing there is a "by design" explanation, but I can't figure out what it is. Does it maybe use the Nuclear Option and terminate with `Environment.Exit`? I think I read that's an instantaneous shutdown, maybe `finally` wouldn't run there?

```csharp
public static void Main(string[] args)
{
    // loading appsettings.json and logger setup omitted

    try
    {
        Log.Information("Starting web host");
        BuildWebHost(args).Run();
    }
    catch (Exception ex)
    {
        Log.Fatal(ex, "Host terminated unexpectedly");
    }
    finally
    {
        Log.Information("Exiting web host");
        Log.CloseAndFlush();
    }
}
```

**Comment by Eilon** [comment]
Hmm do you know how the dotnet.exe process was terminated? That might give a hint to this. So you ran it from VS with <kbd>F5</kbd>, the browser opened, you did stuff, and then closed the browser? And then presumably VS killed the dotnet.exe process? If VS really does kill the process, that would explain why the `finally` didn't run.

**Comment by Eilon** [comment]
OK I just talked to @BillHiebert and he confirms that the VS debugger essentially kills the process when the user appears to be "done" running the app (in this case, that's when the browser window/tab closes). Given that a kill is rather violent, it is unsurprising that the `finally` block does not execute.
