### ISSUE TITLE
Parameter default value is invalid

### ISSUE THREAD

**Issue by netnr** [aspnet/Home#3458]
ASP.NET Core

![图片说明](https://uploadbeta.com/share-image/fU4)

Parameter "sort" default value is invalid

**Comment by Eilon** [comment]
@netnr can you provide more info about this issue and how to reproduce it? What routes does the app have, and what is the request URL?

**Comment by netnr** [comment]
Perhaps my idea is that the weight of the variable default should be higher than "NULL"

**Comment by netnr** [comment]
https://github.com/netnr/test

**Comment by Eilon** [comment]
This issue was moved to aspnet/Mvc#8357
