### ISSUE TITLE
kvm.sh does not run correctly on Ubuntu/Linux Mint

### ISSUE THREAD

**Issue by juzzbott** [aspnet/Home#346]
Hi there, 

I discovered today that the kvm.sh file does not execute correctly on debian based distros (i.e. Ubuntu/Mint). This is because the default shell for these systems is _dash_ instead of bash. 

I was able to get it running by removing the requirement for dash and revert to bash by following this guide: http://www.bloovis.com/wordpress/?p=163

It would be good to see this mentioned under the install notes for Linux, as I spent quite some time before I figured this out, and it was actually breaking my desktop session with the command added to the .profile file running on login, which was failing. 

Cheers, 
Justin

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
