### ISSUE TITLE
Asp.net Core does not send header when request is sent by a subdomain

### ISSUE THREAD

**Issue by PSausM** [aspnet/Home#3463]
I run an Angular application under app.domain.com and a backend under server.domain.com
I have configured CORS correctly. It is working locally.
On the server I get an exception saying, that the CORS header is not present.
Even all origins are allowed, all headers are allowed and all methods are allowed.
It just happens, when the call is from a subdomain to a subdomain. It seems that Asp.Net Core is thinking that it is not a cross domain call. But subdomains are considered to be different origins and therefore the browser is complaining.
<img width="657" alt="fehlermeldung" src="https://user-images.githubusercontent.com/11995352/44629614-336d1780-a952-11e8-849b-2d9e0b60b80c.PNG">

**Comment by pranavkm** [comment]
@PSausM  can you try setting the log level to the most verbose level (https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging) and see why `CorsService` decided not to respond with CORS headers?

**Comment by mkArtakMSFT** [comment]
Hi. We're closing this issue as there's been no response and we have been unable to reproduce it. If you have more details and are encountering this issue please add a new reply and re-open the issue.
