### ISSUE TITLE
XmlSerializerInputFormatter with iso-8859-1 encoding

### ISSUE THREAD

**Issue by rackriili** [aspnet/Home#3467]
Hi,
I am implementing an external interface with WebApi Core 2.0 and I must create a service that receives an XML by a Post action.

If the XML has the default encoding (UTF-8) it parse correctly to my class.
If the encoding is "iso-8859-1" the class is set to null. Unfortunatly this is the encoding.

_My controller:_
```
[HttpPost("[action]")]
public async Task<IActionResult> Notify([FromBody] Person person)
{
...
}
```

_In the startup I add the iso-8859-1 encoding to the formatter_
```
public void ConfigureServices(IServiceCollection services)
{
...
XmlSerializerInputFormatter xmlSerializerInputFormatter = new XmlSerializerInputFormatter();
xmlSerializerInputFormatter.SupportedEncodings.Add(Encoding.GetEncoding("iso-8859-1"));
services.AddMvc(options => options.InputFormatters.Add(xmlSerializerInputFormatter));
}
```

_This XML parse correctly:_
```
<?xml version="1.0" ?>
<person>
	<name>Robert</name>
	<age>30</age>
</person>
```

_This XML parse correctly too:_
```
<?xml version="1.0" encoding="utf-8" ?>
<person>
	<name>Robert</name>
	<age>30</age>
</person>
```

_But this one doesn't work:_
```
<?xml version="1.0" encoding="iso-8859-1" ?>
<person>
	<name>Robert</name>
	<age>30</age>
</person>
```
Any ideas?
Thanks

**Comment by Eilon** [comment]
This issue was moved to aspnet/Mvc#8346
