### ISSUE TITLE
DbContext from EF 2.1.2 violates type contstraint of AddDbContext but 2.1.1 does not

### ISSUE THREAD

**Issue by benm-eras** [aspnet/Home#3469]
I am not sure where to log this issue as it could be a problem with any one of 3 packages:

1. Microsoft.Extensions.DependencyInjection
2. Microsoft.EntityFrameworkCore.SqlServer
3. Microsoft.NET.Sdk.Functions

I am working on a web application using ASP.NET Core MVC and Azure Functions (v2), and recently ran into an issue with injecting my DbContext in my function app after updating the Entity Framework packages (specifically `Microsoft.EntityFrameworkCore.SqlServer` from **2.1.1** to **2.1.2**).

I have put together a minimal reproduction of the problem [here](https://github.com/benm-eras/IssueDemo) where the [final commit](https://github.com/benm-eras/IssueDemo/commit/645a884dc1a2c4cfef8f7abd066e40ccc44ea0da) is using **2.1.2** and is broken, and the [one before](https://github.com/benm-eras/IssueDemo/commit/d23ab554dcdafea235cc932b892592be2545b357) is working fine with **2.1.1**.

With **2.1.2** I get the following exception from my function app when my function is triggered:

> System.Private.CoreLib: Exception while executing function: Function1. Functions: The type initializer for 'Functions.Function1' threw an exception. Functions: Method Microsoft.Extensions.DependencyInjection.EntityFrameworkServiceCollectionExtensions.AddDbContext: type argument 'DAL.DataContext' violates the constraint of type parameter 'TContext'.

I am using the same overload for `AddDbContext` in both my MVC and my function apps, but upgrading to 2.1.2 is only a problem in the function app, the MVC one continues to work as expected. And as far as I can tell I am not violating the type constraint (`where TContext : DbContext`) because:

- `DataContext : IdentityDbContext`
- `IdentityDbContext : IdentityUserContext`
- `IdentityUserContext : DbContext`

**Comment by Eilon** [comment]
This issue was moved to aspnet/EntityFrameworkCore#13145
