### ISSUE TITLE
Getting a endless HttpMessageHandler cleanup cycle

### ISSUE THREAD

**Issue by masterjs** [aspnet/Home#3470]
Hello,
I'm using the HTTP Client factory for ASPNETCORE 2.1. But now, after my second http request, I'm starting to get some logs that are getting me worried.

`HttpMessageHandler expired after 120000ms for client 'default'`
`Starting HttpMessageHandler cleanup cycle with 1 items`
`BDC.ClientPortal.ApiManager> [10:11:49 DBG] Ending HttpMessageHandler cleanup cycle after 0.0342ms - processed: 0 items - remaining: 1 items`
`BDC.ClientPortal.ApiManager> [10:11:59 DBG] Starting HttpMessageHandler cleanup cycle with 1 items`
`BDC.ClientPortal.ApiManager> [10:11:59 DBG] Ending HttpMessageHandler cleanup cycle after 0.0149ms - processed: 0 items - remaining: 1 items`
`BDC.ClientPortal.ApiManager> [10:12:09 DBG] Starting HttpMessageHandler cleanup cycle with 1 items`
`BDC.ClientPortal.ApiManager> [10:12:09 DBG] Ending HttpMessageHandler cleanup cycle after 0.0025ms - processed: 0 items - remaining: 1 items`
`BDC.ClientPortal.ApiManager> [10:12:19 DBG] Starting HttpMessageHandler cleanup cycle with 1 items`
`BDC.ClientPortal.ApiManager> [10:12:19 DBG] Ending HttpMessageHandler cleanup cycle after 0.0017ms - processed: 0 items - remaining: 1 items
...`

These logs are endless. Is that normal? (doesn't look normal)

thank you,
JS

***** dotnet --info *****
.NET Core SDK (reflecting any global.json):
 Version:   2.1.400
 Commit:    8642e60a0f

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.400\

Host (useful for support):
  Version: 2.1.2
  Commit:  811c3ce6c0

.NET Core SDKs installed:
  1.1.0 [C:\Program Files\dotnet\sdk]
  1.1.4 [C:\Program Files\dotnet\sdk]
...
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.400 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
 ....
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

**Comment by rynowak** [comment]
This means that there's a client/message handler that's been expired, but someone is still holding a reference to it. You can analyze what's keeping it alive by capturing a memory dump.

**Comment by Eilon** [comment]
This issue was moved to aspnet/HttpClientFactory#165

**Comment by acds** [comment]
Hi 

Per the link back to aspnet/HttpClientFactory#165, and that repository is now archived and one gets pointed back to hear. I updated to .Net core 2.2 and still get this issue.

What will cause these clean up issues ?

Each API Call gets a specific named HTTPClient within the scope of a function. 

```C#
private async Task<System.Net.HttpStatusCode> MyOperation(MyPoco poco, ILogger logger)
{
    HttpClient client = _httpClientFactory.CreateClient("namedA");
    logger.LogDebug($"***APIRequestTo:{client.BaseAddress}");

    HttpContent content = new StringContent(SerializeCredentials.ToJson(poco), Encoding.UTF8, "application/json");

    using (var httpResponse = await client.PatchAsync("", content))
    {
        httpResponse.EnsureSuccessStatusCode();

        return httpResponse.StatusCode;
    }
}
```

My impression was that I did not need to `dispose` the `HttpClient` each time (by wrapping it in a `using`)?

however I get continuous
```log
 Microsoft.Extensions.Http.DefaultHttpClientFactory[101]
      Ending HttpMessageHandler cleanup cycle after 0.0048ms - processed: 0 items - remaining: 3 items
```

I have 2x named HttpClients each registers as follows:

```C#
.ConfigureServices((context, services) =>
{
    services.AddSingleton<IJobActivator, ServiceJobActivator>();
    services.AddTransient<ScheduledJobs, ScheduledJobs>();
    services.AddSingleton(context.Configuration);

    services.AddTransient<GraphAuthenticationHandler>();
    services.AddHttpClient("namedA", c =>
    {
        c.BaseAddress = new Uri(...);
    }).AddHttpMessageHandler<HandlerA().SetHandlerLifetime(TimeSpan.FromSeconds(10));

    services.AddTransient<VaultAuthenticationHandler>();
    services.AddHttpClient("namedB", c =>
    {
        c.BaseAddress = new Uri(...);
    }).AddHttpMessageHandler<HandlerB().SetHandlerLifetime(TimeSpan.FromSeconds(10));
```

The Handlers add the requisite Authentication headers into each HttpClient Request.

The additional HttpClinet is likely coming from an API call to `AzureServiceTokenProvider.GetAccessTokenAsync`

with additional looped runs I get this
```log
Ending HttpMessageHandler cleanup cycle after 0.0349ms - processed: 6 items - remaining: 0 items
dbug: Microsoft.Extensions.Http.DefaultHttpClientFactory[103]
      HttpMessageHandler expired after 10000ms for client 'graph'
dbug: Microsoft.Extensions.Http.DefaultHttpClientFactory[103]
      HttpMessageHandler expired after 10000ms for client 'vault'
dbug: Microsoft.Extensions.Http.DefaultHttpClientFactory[100]
      Starting HttpMessageHandler cleanup cycle with 2 items
dbug: Microsoft.Extensions.Http.DefaultHttpClientFactory[101]
      Ending HttpMessageHandler cleanup cycle after 0.004ms - processed: 0 items - remaining: 2 items
```

**Comment by rynowak** [comment]
We can only clean up the handlers after everything that refers to them is GCed. If a GC hasn't happened yet, then we have to wait for one to occur. 

Is this causing a problem for you? I'm not very worried based on the logs you showed me. if you have hundreds of handlers hanging around then that is a cause for concern.

**Comment by acds** [comment]
Thanks for replying.

The issues is it’s in a Triggered Azure WebJob that fails with a timeout as it has not completed that clean up after the requisite 120 seconds. This can be extended but it seems that switched to a continuous job it continues to clean up for the hour to the next scheduled trigger.

Burning up resources for nothing than letting the Job sleep.
