### ISSUE TITLE
ASP.NET Core Identity in MVC pattern

### ISSUE THREAD

**Issue by TanvirArjel** [aspnet/Home#3480]
ASP.NET Core 2.1 and later provides ASP.NET Core Identity as a Razor Class Library. Actually I don't want to use Razor Pages in my MVC application. So how can I generate identity related codes in MVC pattern as previous versions.

Thank you.

**Comment by Tratcher** [comment]
@HaoK @javiercn

**Comment by A51UK** [comment]
I think the same, identity was more easily to control and manage with MVC. This main reason for me to not upgrade to Identity 2.1

**Comment by Eilon** [comment]
Closing as dup of https://github.com/aspnet/Identity/issues/1949.
