### ISSUE TITLE
License update to project

### ISSUE THREAD

**Issue by retslig** [aspnet/Home#3483]
I was hoping the project owner would consider updating the project license to use spdx identifier for the "Apache License, Version 2.0" license. Your license in the github api only shows as "Other". 
See https://api.github.com/repos/aspnet/Home/license for your current license.
Also note your current license committed in the repo is already "Apache License, Version 2.0" https://github.com/aspnet/Home/blob/master/LICENSE.txt.
This is no change to the license at all, but then allows anyone using the github license API to get an exact match of the licensed used and not have to use any string magic to come up with your license.

If your unfamiliar with SPDX see spdx.org. 

Pretty sure this can be done in your settings somewhere. Here is an example of your API json and your
spdx_id is null.
```json
{
  "name": "LICENSE.txt",
  "path": "LICENSE.txt",
  "sha": "a275bdeab78db1ee28e357d86c2b3ac9d6e00773",
  "size": 593,
  "url": "https://api.github.com/repos/aspnet/Home/contents/LICENSE.txt?ref=master",
  "html_url": "https://github.com/aspnet/Home/blob/master/LICENSE.txt",
  "git_url": "https://api.github.com/repos/aspnet/Home/git/blobs/a275bdeab78db1ee28e357d86c2b3ac9d6e00773",
  "download_url": "https://raw.githubusercontent.com/aspnet/Home/master/LICENSE.txt",
"type": "file",
  "content": "Q29weXJpZ2h0IChjKSAuTkVUIEZvdW5kYXRpb24gYW5kIENvbnRyaWJ1dG9y\ncwoKQWxsIHJpZ2h0cyByZXNlcnZlZC4KCkxpY2Vuc2VkIHVuZGVyIHRoZSBB\ncGFjaGUgTGljZW5zZSwgVmVyc2lvbiAyLjAgKHRoZSAiTGljZW5zZSIpOyB5\nb3UgbWF5IG5vdCB1c2UKdGhpcyBmaWxlIGV4Y2VwdCBpbiBjb21wbGlhbmNl\nIHdpdGggdGhlIExpY2Vuc2UuIFlvdSBtYXkgb2J0YWluIGEgY29weSBvZiB0\naGUKTGljZW5zZSBhdAoKICAgIGh0dHA6Ly93d3cuYXBhY2hlLm9yZy9saWNl\nbnNlcy9MSUNFTlNFLTIuMAoKVW5sZXNzIHJlcXVpcmVkIGJ5IGFwcGxpY2Fi\nbGUgbGF3IG9yIGFncmVlZCB0byBpbiB3cml0aW5nLCBzb2Z0d2FyZSBkaXN0\ncmlidXRlZAp1bmRlciB0aGUgTGljZW5zZSBpcyBkaXN0cmlidXRlZCBvbiBh\nbiAiQVMgSVMiIEJBU0lTLCBXSVRIT1VUIFdBUlJBTlRJRVMgT1IKQ09ORElU\nSU9OUyBPRiBBTlkgS0lORCwgZWl0aGVyIGV4cHJlc3Mgb3IgaW1wbGllZC4g\nU2VlIHRoZSBMaWNlbnNlIGZvciB0aGUKc3BlY2lmaWMgbGFuZ3VhZ2UgZ292\nZXJuaW5nIHBlcm1pc3Npb25zIGFuZCBsaW1pdGF0aW9ucyB1bmRlciB0aGUg\nTGljZW5zZS4=\n",
  "encoding": "base64",
  "_links": {
    "self": "https://api.github.com/repos/aspnet/Home/contents/LICENSE.txt?ref=master",
    "git": "https://api.github.com/repos/aspnet/Home/git/blobs/a275bdeab78db1ee28e357d86c2b3ac9d6e00773",
    "html": "https://github.com/aspnet/Home/blob/master/LICENSE.txt"
  },
  "license": {
    "key": "other",
    "name": "Other",
    "spdx_id": null,
    "url": null,
    "node_id": "MDc6TGljZW5zZTA="
  }
}
```

**Comment by retslig** [comment]
This can be completed by updating you License.txt file to match Githubs known list licenses.
See here for exact details of how the license API works. https://developer.github.com/v3/licenses/
Brief snippet:

The Licenses API uses the open source Ruby Gem Licensee to attempt to identify the project's license. Licensee matches the contents of a project's LICENSE file (if it exists) against a short list of known licenses. As a result, the API does not take into account the licenses of project dependencies or other means of documenting a project's license such as references to the license name in the documentation.
If a license is matched, the license key and name returned conforms to the SPDX specification.

Another article that explains this well. https://blog.github.com/2016-09-21-license-now-displayed-on-repository-overview/

I tested this on one of my own repos and this did indeed work.
Only concern I have is that your license is in the known list.

**Comment by Eilon** [comment]
Thanks @retslig , this was also reported to us in https://github.com/aspnet/EntityFrameworkCore/issues/13117, so I'm looking into this. Hopefully we can get this updated so that the GitHub License API shows the correct data.

**Comment by Eilon** [comment]
OK I sent out a request to our license experts to see what we can do here.

**Comment by Eilon** [comment]
OK this should be done for all the ASP.NET/EF Core repos in this org. If you think I missed something, please let me know!

**Comment by retslig** [comment]
Just verified the license and looks good thanks!
