### ISSUE TITLE
Validate model attribute is no longer called since upgraded to dotnet core 2.1

### ISSUE THREAD

**Issue by sorcer1** [aspnet/Home#3485]
Hello,

In some of my api controllers if put my custom attribute [ValidateModel], it works to send a specific error message when the model is invalid.
Since my upgrade to dotnet core 2.1 the attribute is no longer called and now i have a generic error message like :

```
{
    "lastname": [
        "The field Name is required"
    ]
}
```

My custom attribute :
```
    public class ValidateModelAttribute : ActionFilterAttribute
    {
        public override void OnActionExecuting(ActionExecutingContext context)
        {
            if (!context.ModelState.IsValid)
            {
                // Send my specific error message
            }
        }
    }
```

Can some one explain me why my attribute is no more working ?

**Comment by rafsanulhasan** [comment]
In ASP.NET Core 2.1 controllers, an internal Model Validator is implemented internally thus your custom validator would not work.

You can add the line in the _ConfigureServices_ method of **Startup class** to suppress the default behavior:
`services.Configure<ApiBehaviorOptions>(opts => opts.SuppressModelStateInvalidFilter = true);`

**Comment by sorcer1** [comment]
Thank you very much
