### ISSUE TITLE
Timestamp passed via RedirectToAction loses precision in target action

### ISSUE THREAD

**Issue by martinmikulka** [aspnet/Home#3488]
Hello, I am facing a problem when calling RedirectToAction() method and passing a timestamp via parameter:

```
public IActionResult ActionOne()
{
   var timestamp = new DateTimeOffset(2018,7,25,14,16,18,120,new TimeSpan());
   return RedirectToAction("ActionTwo", new { Timestamp = timestamp });
}

public IActionResult ActionTwo(DateTimeOffset timestamp)
{
   ...
}
```

When I dump the timestamp variable inside the ActionOne:
Millisecond [int]: 120
Ticks [long]: 636681249781200000

When I dump the timestamp variable inside the ActionTwo:
Millisecond [int]: 0
Ticks [long]: 636681249780000000

The target variable has lost miliseconds precision.
Do I have to pass the timestamp in some different way or is it a bug?

Thanks, Martin

**Comment by martinmikulka** [comment]
I solved this problem by passing the value in milliseconds [long] instead of DateTimeOffset.

```
public IActionResult ActionOne()
{
   var timestamp = new DateTimeOffset(2018,7,25,14,16,18,120,new TimeSpan());
   return RedirectToAction("ActionTwo", new { Timestamp = timestamp.ToUnixTimeMilliseconds() });
}

public IActionResult ActionTwo(long timestamp)
{
   var ts = DateTimeOffset.FromUnixTimeMilliseconds(timestamp);
   ...
}
```

**Comment by Eilon** [comment]
This issue was moved to aspnet/Mvc#8383
