### ISSUE TITLE
How to Scaffold Identity UI in ASP.NET Core 2.2 preview1 

### ISSUE THREAD

**Issue by Amine-Smahi** [aspnet/Home#3489]
In ASP.NET Core 2.1 we had the chance to use scaffold using visual studio like this

![image](https://user-images.githubusercontent.com/24621701/45003154-48dbe480-afd7-11e8-9085-a67371374fb1.png)

But now in ASP.NET Core 2.2 preview1 the new scaffold item is missing in visual studio 

![image](https://user-images.githubusercontent.com/24621701/45003175-88a2cc00-afd7-11e8-8892-995109ee7ae8.png)

**Comment by damienbod** [comment]
You can't at the moment, will be implemented soon.

see: 

https://github.com/aspnet/Scaffolding/issues/860

**Comment by Eilon** [comment]
This issue was moved to aspnet/Scaffolding#868
