### ISSUE TITLE
VB.Net and vNext

### ISSUE THREAD

**Issue by seascan** [aspnet/Home#349]
Does anyone now how the VB community can help with vNext?  

Would really like to see VB and Webforms native in ASP.Net 5.

I'm not sure how to help on the technical level -- if anyone can suggest a starting point, please respond.

Perhaps 'we' (VB Users) can help with documentation or examples?

**Comment by Eilon** [comment]
Dup of https://github.com/aspnet/Home/issues/236

There are some project extensibility features in ASP.NET 5 around custom project loaders, which in theory could support loading projects written using VB, F#, or other languages. You could try rooting around the source code, such as these files:

* https://github.com/aspnet/XRE/blob/c3da353174e4c686d01bfd57eb9c4775cfb55648/src/Microsoft.Framework.Runtime.Roslyn/RoslynProjectReferenceProvider.cs
* https://github.com/aspnet/XRE/blob/c3da353174e4c686d01bfd57eb9c4775cfb55648/src/Microsoft.Framework.Runtime.Roslyn/RoslynProjectReference.cs
* https://github.com/aspnet/XRE/blob/c3da353174e4c686d01bfd57eb9c4775cfb55648/src/Microsoft.Framework.Runtime/Loader/ProjectAssemblyLoader.cs

And these might provide some hints as to how one could implement a custom loader for other project types.

As far as supporting WebForms, that would be a monumental task and there are no plans to enable that in any way.

**Comment by davidfowl** [comment]
Here's an example of plugging in https://github.com/davidfowl/vNextLanguageSupport.

This won't help you get intellisense in VS though. That's not extensible today

**Comment by seascan** [comment]
Eilon.  Yes, I did see #236 but, don't think it's a duplicate.  236 just says that they don't see VB support.  My intention with this post is to find out how the VB community can work with vNext and be a part of all of this -- as opposed to being BASICally dropped out of the future of ASP.Net.

I am really shocked that there isn't more wailing and gnashing of teeth over VB and webforms.  We (VBers) are used to being treated like second class citizens but, exclusion of two huge components of ASP.Net (that have been fundamental for the last decade plus) is a bit much.  

Perhaps as RTM approaches and more people download VS2015 and don't see the VB templates that the torches and pitch forks will come out...

**Comment by Eilon** [comment]
Ah you're right it's not a dup of #236.

For WebForms users there are still ongoing improvements in ASP.NET 4.x. Here's just a few posts I found that go into what's new over the last couple of releases:

* ASP.NET 4.5: http://www.asp.net/aspnet/overview/aspnet-and-visual-studio-2012/whats-new
* ASP.NET 4.5.1 Preview: http://blogs.msdn.com/b/dotnet/archive/2013/06/26/announcing-the-net-framework-4-5-1-preview.aspx
 * More details: http://blogs.msdn.com/b/dotnet/archive/2013/10/09/asp-net-app-suspend-responsive-shared-net-web-hosting.aspx
* ASP.NET 4.6 / WebForms: http://blogs.msdn.com/b/webdev/archive/2014/11/12/announcing-asp-net-features-in-visual-studio-2015-preview-and-vs2013-update-4.aspx (scroll down)

But ultimately our data shows that most web developers on .NET are using C#, so while we certainly haven't forgotten about anyone, our key investments are targeted at where most of our developers are. As you saw from the link @davidfowl pointed, project extensibility exists (though it has limitations), so embracing the broader community is also a goal, even if we haven't built the features all the way through.

**Comment by craigajohnson** [comment]
@seascan, I'm not worried and let me explain why - my sense is that the gang are heads down in re-architecting the world to increase the relevance of .NET and to reach out to the market/mind share lost to Linux. All of the abstractions are new (modularization of CLR, project.json, etc.) - it's a ground-up rewrite heavily dependent on the marvel that is Roslyn. VB is a first-class citizen in Roslyn and there is nothing magical about the C# Roslyn layer that isn't fully extended to the VB side. It's wise to have at least 2 independent implementations of an abstraction so co-developing VB & C# makes sense, not to mention that VB.NET is a beautiful language and has a long history. If you look at the latest TIOBE, for every 4 lines of .NET code written, 3 lines are in C# and 1 line is in VB.NET. Both VB.NET and F# are on the rise. Whenever I consider .NET's adoption rate, I always combine VB and C# together. Anyone who attempts to malign or downplay VB.NET is speaking from a position of ignorance.

VB/C# at this point yield fundamentally identical IL so it's really simply a question of preference.

With that said, though, the ASP.NET team is attempting to gain credibility in the Linux/OSS community which doesn't really care about VB and no doubt the ASP.NET team themselves strongly prefer C#. At this point they're sprinting to the finish line to release a stable drop to the world but in the process they've moved to a true CI/CD process so any "release" is just a brief point-in-time. No doubt when the RTM dust settles and there is a measure of architectural stability, there will be greater opportunities to provide and support such extensions.

Keep in mind, though, that cross-platform support may only ever be a C# story.

**Comment by seascan** [comment]
Thanks everyone for your great input.  I'm going to explore the links and see where I can contribute.

Craig,   I really appreciate your thoughtful response.  To read "VB.NET is a beautiful language" made my day.  

I think all the MS technologies are miraculous.  It's not that I can't write C# or have anything against it, it's just that I prefer the readability of VB.  People (clients) without a technical background who I show code to 'get it' while curly brackets and symbols (instead of words) seem to throw them off.

The combination of VB.Net, ASP.Net (webforms) and SQL Server have given me a wonderful career as an independent developer for the last decade so, I'm keenly interested in the future of all these components and would like to payback by contributing where I can.

If you can think of any more trails I can follow, please post.

Thanks again,
Terry

**Comment by davidfowl** [comment]
As Eilon said, we're still investing in WebForms on .NET 4.6 and have no plans to bring any of it to ASP.NET 5. 

@seascan If you personally want to undergo porting webforms to ASP.NET 5 (which would be a huge under taking). You can start by porting this code over to the new stack https://github.com/Microsoft/referencesource/tree/master/System.Web/UI (in another repository of course). Then:

- You need to make it compile on CoreCLR
- You need to remove the System.Web dependency
- You won't get any tooling support (no drag drop designer)
- Any controls you bought/wrote won't work and would need to be recompiled

**Comment by seascan** [comment]
Thanks, @davidfowl.  Will look into that but, at first glance looks a bit daunting.  Though, I know I would learn a lot by trying that out!

Perhaps I don't fully understand the plan for ASP.Net....  Will the ASP.Net 4.X continue to be upgraded and supported or will 5.X eventually take over.  Is there an end-of-life date set for 4.X?  Just by the numbering convention I get the feeling that 5.X is 'the new stuff' and anything else will wither.  

I guess I am looking for a definitive answers to:  
Are VB and Webforms dead in the long run? 
And, should we  all (as Stephen Walther has implied) just accept the C#/MVC paradigm?

**Comment by Eilon** [comment]
.NET 4.x will continue to be supported by Microsoft for the foreseeable future (.NET versions have quite long support lifecycles). But ultimately most investments are in the newest platforms because they have the most room to grow. The articles I linked to earlier demonstrate that there are ongoing investments to ensure that Web Forms and .NET 4.x gain some of the newest, coolest features (e.g. Roslyn, C# 6, etc.).

**Comment by coolcsh** [comment]
@seascan right now I think the best way to think of ASP.NET 5 is the bold new thing. At this point it does not do all of the things that ASP.NET 4.5.x - 4.6 does but it does a few things different and or better:

- Fully side by side
- Cross platform
- No compile step required
- You can opt in/out for what you want in framework
- tag helpers, try to keep your markup looking like markup and not C#/VB

That said our first version will not have 100% feature parity and it will take us some time to mature it. But we want to get it out there for the folks to try the features above.

We are also investing in the 4.5.x/4.6 stack. We have support for Rosyln, Async Model Binding for Web Forms, Identity 2.x, EF 7, HTTP 2.0 and more coming. This also includes minor updates to the MVC 5, Web API 2, etc that run on the 4.5.x stack.

So for now think of the this as two stacks. The mature 4.5.x.- 4.6 stack continuing to get incremental improvements and the new 5.x stack which has some awesome new features that we can't provide on 4.5.x but also a stack that is not as mature and will need time to bake.

**Comment by seascan** [comment]
This blog entry on Scott Guthrie's Blog : http://weblogs.asp.net/scottgu/introducing-asp-net-5?__r=8d22e3188409343 has many comments that are in support of ensuring VB.Net is part of ASP.Net's future.  I particularly liked the idea of re-branding VB to "B#".  

Speaking of branding, perhaps the version numbers and forking of ASP.Net is causing confusion and concern.  Instead of the 4.X and 5.X paths, does anyone know why there can't just be ASP.Net?  And have the needed/desired functions scaffolded in?  Or, is this the intended course over time?

**Comment by davidfowl** [comment]
Sure we can call it whatever we wanted to but the Core of the new stack is completely different from the Core of the current stack.

**Comment by habakuk007** [comment]
"But ultimately our data shows that most web developers on .NET are using C#" 

May be, but probably the random sample ("web developers that use .Net") is too small. VB today is the more advanced language (e.g. try to read an c# code out)

**Comment by Eilon** [comment]
Hey everyone, good news! We've announced plans to support VB in ASP.NET 5 / DNX!

Read more on the official blog post: http://blogs.msdn.com/b/webdev/archive/2015/04/23/making-it-better-asp-net-with-visual-basic-14.aspx

Closing this thread for now. Stay tuned for updates.

**Comment by craigajohnson** [comment]
Fantastic news.

**Comment by GuardRex** [comment]
:+1: This is great news if for no other reason than VB is more accessible to very young developers. It also bridges for people coming into .NET from VBA. I started in biz dev as an Access developer, so going from VBA -> VB.NET -> C# was good for me.

Thanks MS for keeping VB in the mix!

**Comment by seascan** [comment]
My jaw dropped when I saw this update -- had to reread it a few times to let it sink in... Thank you!!

**Comment by jrmoreno1** [comment]
@seascan looks like starting with https://github.com/aspnet/dnx/issues/1706 would be the thing to do...

**Comment by xdvarpunen** [comment]
> But ultimately our data shows that most web developers on .NET are using C#, so while we certainly haven't forgotten about anyone, our key investments are targeted at where most of our developers are. 

Please tell all schools that are using VB.NET in order to teach students to learn programming to stop using then. It is used even this year, 2016, as first programming language in college. VBA is taught for Access even in this year, 2016, for Office development. What's the future of Visual Basic? If it is not shown in statistics, dropped? Statistics don't take into account offline development. If Visual Basic is not useful, it is better to state it clearly so young developers or students don't stay confused and jobless due to this fact. I want to know should I drop it from use it has no future except as "extra" language :smile:
