### ISSUE TITLE
DefaultObjectPool is not threadsafe

### ISSUE THREAD

**Issue by mkArtakMSFT** [aspnet/Home#3493]
_From @fofewyoung on September 3, 2018 10:18_

i found DefaultObjectPool is not thread safe in 2.1, 
the test result is:

2.0.0   ----  pass
2.1.0-preview1-final  -- pass
2.1.0-preview2-final  -- failed
2.1.0                          -- failed
2.2.0-preview1-35029  --failed

my test code is below:

        class AClass
        {
            public int i = 0;

            public void Reset()
            {
                i = 0;
            }
        }

        static DefaultObjectPool<AClass> PoolInstance;
        void TestDOP() // call this function in Main
        {
            PoolInstance = new DefaultObjectPool<AClass>(new DefaultPooledObjectPolicy<AClass>(), 10);
            for (int i = 0; i < 8; i++)
            {
                var t = new Thread(OnTest1);
                t.Start();
            }
        }
        void OnTest1()
        {
            while (true)
            {
                var obj = PoolInstance.Get();
                if (obj.i != 0)
                    Console.WriteLine("bug");
                obj.i = 123;

                var obj2 = PoolInstance.Get();
                if (obj2.i != 0)
                    Console.WriteLine("bug");
                obj2.i = 321;

                obj.Reset();
                PoolInstance.Return(obj);
                obj2.Reset();
                PoolInstance.Return(obj2);
            }
        }

_Copied from original issue: aspnet/Common#394_

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @fofewyoung.
@rynowak can you please look into this? Thanks!

**Comment by rynowak** [comment]
@gfoidl - this is the original report

**Comment by rynowak** [comment]
PR for release/2.2 https://github.com/aspnet/Common/pull/398
PR for release/2.1 https://github.com/aspnet/Common/pull/399
