### ISSUE TITLE
ASP.Net Core 2.1 not releasing memory

### ISSUE THREAD

**Issue by danmosemsft** [aspnet/Home#3494]
_From @BinaryPatrick on September 4, 2018 18:4_

An application running under a 15-25 requests per second load exhibits an endlessly growing memory footprint.

At first I thought I must have a memory leak, but when I run `dotnet new webapi`, compile the code using the release flag, and run it using `dotnet webapi.dll`, I get the same result.

I generated a load of ~20 GET requests a second to https://localhost:5001/api/values and after 10 minutes, the memory usage is up to 800Mb and growing.

This is with the stock asp.net webapi template. Is this the expected memory usage?

_Copied from original issue: dotnet/corefx#32100_

**Comment by danmosemsft** [comment]
@BinaryPatrick hello, I don't know, let's move this to the ASP.NET repo.  If you want to investigate yourself, you'll want to look at https://github.com/Microsoft/perfview

**Comment by davidfowl** [comment]
cc @sebastienros

**Comment by BinaryPatrick** [comment]
Also, I have tested this with `<ServerGarbageCollection>false</ServerGarbageCollection>` and it does not affect the memory consumption. Even after I stop the requests, the memory usage remains until I kill the webhost.

**Comment by sebastienros** [comment]
@BinaryPatrick We do it all day long, with much more complex applications, and we don't see this behavior. I even made a web app and article to show how everything works _fine) https://github.com/sebastienros/memoryleak

- Have you recompiled the application when you switched to Workstation GC?
- How much memory do you have on your system? I have 32GB and it never goes above 500MB. With Workstation it should stay at 70MB max.

Can you check Console logging is disabled, or set the `appsettings.json` to Error only? It's missing in the current empty templates.

**Comment by Eilon** [comment]
Closing for now. If new info comes up, please let us know.

**Comment by PrefabPanda** [comment]
I get this particular problem too. Happens when using containers - in dotnet core 2.1 or 2.2.

2.0 doesn't seem to have the problem.

**Comment by danmosemsft** [comment]
@prefabpanda I suggest opening a new issue with a link back,so this isn't overlooked. You might also try 3.0 preview 5.

**Comment by kakins** [comment]
I'm seeing this problem in aspnet core 2.2.0.  I look at the Diagnostic Tools in VS2019 and GC never gets called throughout the lifetime of the application.  However, I do see GC being called in an ASP.NET 4.5 project.
