### ISSUE TITLE
when run at server throw Cannot find compilation library location for package error

### ISSUE THREAD

**Issue by kugarliyifan** [aspnet/Home#3499]
i create the project by asp.net core 2.1 ,Microsoft.AspNetCore.App version is 2.1.3,,my server is windows 2012 64x,.net core runtime is 2.1.3,,i use the publish the website ,configuation is 
![image](https://user-images.githubusercontent.com/18448413/45108437-2c72b000-b16f-11e8-9748-e63fdf7a18f5.png) ,,,but when i request the site,it throw the error like this 
![image](https://user-images.githubusercontent.com/18448413/45108552-82dfee80-b16f-11e8-9432-bbbb4f436942.png)
 but i never references this package....how can i solve this ,,,please help me

**Comment by kugarliyifan** [comment]
this application run  in vs2017 mode is no problem

**Comment by Eilon** [comment]
@dougbu / @pranavkm / @mkArtakMSFT - any ideas on this?

**Comment by pranavkm** [comment]
Try setting `<CopyRefAssembliesToPublishDirectory>true</CopyRefAssembliesToPublishDirectory>` in your project file.. https://docs.microsoft.com/en-us/aspnet/core/razor-pages/sdk?view=aspnetcore-2.1 has some documentation about the setting.

That said, I'd recommend not trying to compile views as part of a published application. The most common case for this is using an `EmbeddedFileProvider` as a source for views. Have a look at Razor Class Libraries - https://docs.microsoft.com/en-us/aspnet/core/razor-pages/ui-class?view=aspnetcore-2.1&tabs=visual-studio - instead.
