### ISSUE TITLE
Tried to run "HelloWeb" on Debian and got "Could not load file or assembly 'Microsoft.Framework.ConfigurationModel.IConfiguration"

### ISSUE THREAD

**Issue by brewerof** [aspnet/Home#350]
I tried to run demo app "HelloWeb" on Debian, but got 
"System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Framework.ConfigurationModel.IConfiguration, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
File name: 'Microsoft.Framework.ConfigurationModel.IConfiguration, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'
  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:0 "

I already trying to reinstall KVM and demo examples, ConsoleApp working fine, but HelloWeb and HelloMvc throws this exception.

******************************************************************************************************************
mono --version
Mono JIT compiler version 3.12.0 (tarball Sat Feb  7 19:12:57 UTC 2015)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	LLVM:          supported, not enabled.
	GC:            sgen

******************************************************************************************************************
kvm list

Active Version              Runtime Location             Alias

1.0.0-beta4-11169    mono    ~/.k/runtimes        default

**Comment by suhasj** [comment]
After package restore, are the packages restored from myget/vnext or nuget ?

**Comment by dstaley** [comment]
@suhasj Looks like I'm getting packages from nuget.

```bash
$ cd ~/Desktop/Home/samples/HelloMvc/
$ source kvm.sh
$ kpm restore
Restoring packages for /Users/dstaley/Desktop/Home/samples/HelloMvc/project.json
  GET https://www.nuget.org/api/v2/FindPackagesById()?Id='System.Reflection'.
  GET https://www.nuget.org/api/v2/FindPackagesById()?Id='System.Text.Encoding'.
  GET https://www.nuget.org/api/v2/FindPackagesById()?Id='System.Xml.ReaderWriter'.
  GET https://www.nuget.org/api/v2/FindPackagesById()?Id='System.Globalization'.
  GET https://www.nuget.org/api/v2/FindPackagesById()?Id='System.Threading.Tasks'.
  GET https://www.nuget.org/api/v2/FindPackagesById()?Id='System.Runtime'.
  GET https://www.nuget.org/api/v2/FindPackagesById()?Id='System.IO'.
  GET https://www.nuget.org/api/v2/FindPackagesById()?Id='System.Collections'.
  GET https://www.nuget.org/api/v2/FindPackagesById()?Id='System.ObjectModel'.
  OK https://www.nuget.org/api/v2/FindPackagesById()?Id='System.ObjectModel' 1053ms
  OK https://www.nuget.org/api/v2/FindPackagesById()?Id='System.Runtime' 1112ms
  OK https://www.nuget.org/api/v2/FindPackagesById()?Id='System.Xml.ReaderWriter' 1465ms
  OK https://www.nuget.org/api/v2/FindPackagesById()?Id='System.Globalization' 1967ms
  OK https://www.nuget.org/api/v2/FindPackagesById()?Id='System.Reflection' 8164ms
  OK https://www.nuget.org/api/v2/FindPackagesById()?Id='System.IO' 8504ms
  OK https://www.nuget.org/api/v2/FindPackagesById()?Id='System.Text.Encoding' 9052ms
  OK https://www.nuget.org/api/v2/FindPackagesById()?Id='System.Collections' 9472ms
  OK https://www.nuget.org/api/v2/FindPackagesById()?Id='System.Threading.Tasks' 15579ms
Resolving complete, 23368ms elapsed
Restore complete, 23372ms elapsed
$ k kestrel
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Framework.ConfigurationModel.IConfiguration, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
File name: 'Microsoft.Framework.ConfigurationModel.IConfiguration, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'
  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:0
```

**Comment by davidfowl** [comment]
@suhasj the samples on Home have been broken for 2 releases now :smile:

**Comment by MattKunze** [comment]
I have the same versions (mint instead of debian), but can't get restore to work:

```
matt@sushi ~/code/Home/samples/ConsoleApp $ kpm restore
Restoring packages for /home/matt/code/Home/samples/ConsoleApp/project.json
----------
System.IO.FileNotFoundException: Could not load file or assembly 'System.Net.Http, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.
File name: 'System.Net.Http, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
  at Microsoft.Framework.PackageManager.PackageSourceUtils.CreatePackageFeed (NuGet.PackageSource source, Boolean noCache, Boolean ignoreFailedSources, Microsoft.Framework.PackageManager.Reports reports) [0x00000] in <filename unknown>:0 
  at Microsoft.Framework.PackageManager.RestoreCommand.AddRemoteProvidersFromSources (System.Collections.Generic.List`1 remoteProviders, System.Collections.Generic.List`1 effectiveSources) [0x00000] in <filename unknown>:0 
  at Microsoft.Framework.PackageManager.RestoreCommand+<RestoreForProject>d__79.MoveNext () [0x00000] in <filename unknown>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x00000] in <filename unknown>:0 
  at System.Runtime.CompilerServices.TaskAwaiter`1[System.Boolean].GetResult () [0x00000] in <filename unknown>:0 
  at Microsoft.Framework.PackageManager.RestoreCommand+<>c__DisplayClass77_0+<<ExecuteCommand>b__0>d.MoveNext () [0x00000] in <filename unknown>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x00000] in <filename unknown>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <filename unknown>:0 
  at Microsoft.Framework.PackageManager.RestoreCommand+<ExecuteCommand>d__77.MoveNext () [0x00000] in <filename unknown>:0 
----------
Restore failed
Could not load file or assembly 'System.Net.Http, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.
```

**Comment by davidfowl** [comment]
@MattKunze  Looks like you need to update your mono build

**Comment by MattKunze** [comment]
Yeah, just did. I'll uninstall and reinstall and see if that helps

**Comment by davidfowl** [comment]
`mono --version`

**Comment by MattKunze** [comment]
3.12, same as @brewerof 

```
matt@sushi ~/code/Home/samples/ConsoleApp $ mono --version
Mono JIT compiler version 3.12.0 (tarball Sat Feb  7 19:12:57 UTC 2015)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	LLVM:          supported, not enabled.
	GC:            sgen```

**Comment by MattKunze** [comment]
nm, `apt-get install mono-complete` seems to have done the trick. I had added the Xamarin package sources and ran `upgrade`, but that doesn't include everything on Linux Mint

**Comment by nilscant** [comment]
I'm seeing the same behaviour as brewerof on Ubuntu 14.04.
On an older installation it still works, but when I delete my ~/.k/packages directory and run kpm restore again, the application won't run anymore.

Restoring ~/.k/packages solves the problem, so I'm guessing something on a nuget package broke.

**Comment by brewerof** [comment]
I tried solution from here: aspnet/Home#310, that @andrebaltieri suggested. 

Added NuGet.config to the HelloWeb root and changed project.json, but problem still remains

**Comment by davidfowl** [comment]
The samples point to beta1, change the project.json to beta3

**Comment by andrebaltieri** [comment]
@brewerof I think people are confusing packages and versions... 

If you're running beta-* from dev branch, you should point to the correct nuget package, by including the NuGet.config on your app root folder or change the main config file, poiting to the correct dev package source.

If you're running beta-* from master branch, than you just use the default package source.

In additional, if you are running beta-x (Run "kvm list" to see yout current version), than your project.json should point to beta-x too!

**Comment by dstaley** [comment]
Replacing `beta1` with `beta3` in the `project.json` file seems to have done the trick! I was able to run `k kestrel` and get the welcome to ASP.NET vNext message. Can I submit a PR to update the dependencies to beta3?

**Comment by davidfowl** [comment]
https://github.com/aspnet/Home/pull/348

**Comment by dstaley** [comment]
@davidfowl :+1:

**Comment by brewerof** [comment]
@andrebaltieri, kvm list gave me

Active Version              Runtime Location             Alias
------ -------              ------- --------             -----
  *    1.0.0-beta4-11169    mono    ~/.k/runtimes        default

but beta-value in project.json must point to ver.3

As I understood I should install kre beta3 also?

**Comment by danroth27** [comment]
@brewerof Because things are still churning quite a bit it's generally a good idea to run the same version of everything. Once things have stabilized a bit more it should be possible to upgrade your KRE without breaking everything, but we just aren't there yet.
