### ISSUE TITLE
Is there anyway to replace file and auto restart asp.net core website

### ISSUE THREAD

**Issue by kugarliyifan** [aspnet/Home#3501]
Is there anyway to replace file and auto restart website on iis 8 like asp.net mvc.....I publish use win-64x mode,,I want to like asp.net ,,,upload new dll file use ftp and website can auto restart....Is that Anyway to make this???

**Comment by Tratcher** [comment]
See app_offline.htm: https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/aspnet-core-module?view=aspnetcore-2.1#app_offlinehtm

**Comment by kugarliyifan** [comment]
@Tratcher   thank you !!!!!
