### ISSUE TITLE
WebApplicationFactory WithWebHostBuilder configuration priority seems wrong

### ISSUE THREAD

**Issue by jdmichel** [aspnet/Home#3502]
I'm trying to upgrade an integration test and related app from aspnetcore 2.0 to 2.1, and running into problems with configuration settings and WebApplicationFactory. 

If I use the following code, then the existing setting in appsetting.json takes precedence over the setting for the test.

```c#
// From the integration test constructor...
var client = factory.WithWebHostBuilder(builder =>
            {
                builder.UseSetting("Foo:Bar", "True");
            }).CreateClient();
```

If I remove the setting from appsettings.json then I get the value from the setting above. 
It seems that WithWebHostBuilder() is adding a new provider at the head of the list instead of the tail. I think you would always want the programmatic UseSetting to take precedence over all the other configuration providers. 

My workaround is to keep using the previous code which used TestServer explicitly like so:

```c#
_server = new TestServer(WebHost.CreateDefaultBuilder().UseStartup<Startup>());
var client = _server.CreateClient();
```

This reads settings from a local copy of the appsettings.json file from the integration test directory, but at least it works.

Since switching to 2.1 these tests all get BadRequest for every client call (the controller isn't even called) and I'm not sure why. Which is why I tried to update the tests to use the WebApplicationFactory. 

Something here seems to be an undocumented breaking change.

**Comment by Eilon** [comment]
This issue was moved to aspnet/Mvc#8406
