### ISSUE TITLE
DependencyInjection stackoverflow test failure

### ISSUE THREAD

**Issue by pakrym** [aspnet/Home#3504]
The test that is failing is `CompilesInLimitedStackSpace` test that is using availible to the max.

But somehow between `2.2.0-preview-26820-02` and `2.2.0-preview2-26903-02` amount of available stack space went down on OSX and Ubuntu.

**Comment by pakrym** [comment]
This test failure is caused by https://github.com/dotnet/coreclr/pull/19525. My speculation is that first version of bytecode that tiered JIT generates is less optimized and takes more stack space causing our test to fail. 

Disabling tiered JIT using `export COMPlus_TieredCompilation=0` fixes the test.

@kouvel  is this behaviour expected?

**Comment by kouvel** [comment]
Sorry for the delay, yes stack usage for a method with tiered compilation enabled can be higher (fewer optimizations at tier 0) or lower (less inlining at tier 0)
