### ISSUE TITLE
How to set asp.net core http port number  manual in IIS 8?

### ISSUE THREAD

**Issue by kugarliyifan** [aspnet/Home#3507]
How can I set asp.net core 2.1.3 http port number in IIS8,,,is there anyway to set the port in web.config? the asp.net core http port, not the iis http port

**Comment by nil4** [comment]
@kugarliyifan if you're referring to configuring ASP.NET Core Module for IIS to listen on a specific port, you can set the `ASPNETCORE_PORT` environment variable to the desired value. See https://github.com/aspnet/AspNetCoreModule/issues/64#issuecomment-365518588, and be aware you might run into this bug https://github.com/aspnet/IISIntegration/issues/1119

**Comment by Eilon** [comment]
@shirhatti / @Tratcher - anything to add?

**Comment by Tratcher** [comment]
No
