### ISSUE TITLE
DotNetCoreWindowsHosting install corrupt after sysprep

### ISSUE THREAD

**Issue by elangelo** [aspnet/Home#3508]
As part of our offering on Azure we have an API service that is running in dotnetcore 2.0 
We use packer to create a custom image and install the dotnetcore windows hosting module.
The version we install is DotNetCore.2.0.0-WindowsHosting.exe

At the end of the packer process a sysprep gets run: 
				"& $env:SystemRoot\\System32\\Sysprep\\Sysprep.exe /oobe /generalize /quiet /quit",

When i spin up a machine from this image and install our dotnet core service on it we always get 500s externally. browsing localhost we get: 
![image](https://user-images.githubusercontent.com/1935881/45164852-c4b27880-b1f3-11e8-965a-3ac743103d67.png)

The only way to fix this is to go to the control panel and find the dotnetcore hosting program and click on repair:
![image](https://user-images.githubusercontent.com/1935881/45164947-f9becb00-b1f3-11e8-9149-0a556fc81967.png)

I have no idea why this even helps or why the installation wouldn't survive a sysprep in the first place. I would like to know 
1. why does the installation not survive a sysprep
2. how can i figure out what the repair actually fixes and what is actually broken (so i can perhaps fix it manually with some powershell script instead of just having to manually run the 'repair' step.

**Comment by Tratcher** [comment]
This issue was moved to aspnet/IISIntegration#1375
