### ISSUE TITLE
How to read Automatic Proxy Detection (WPAD) in Asp.net core 

### ISSUE THREAD

**Issue by xinlongli2018** [aspnet/Home#3509]
in asp.net we can use the following setting in web.config to point to a wpad.dat file to read all the proxy setting, is there a way we can achieve the same thing in asp.net core?

<system.net>
      <defaultProxy enabled="true" useDefaultCredentials="true">
        <proxy autoDetect="True" scriptLocation="http://wpad.dat" />
      </defaultProxy>
    </system.net>

**Comment by Tratcher** [comment]
This issue was moved to dotnet/corefx#32135
