### ISSUE TITLE
System.NotSupportedException: 'Unable to determine the provider name for provider factory of type 'System.Data.SqlClient.SqlClientFactory'. Make sure that the ADO.NET provider is installed or registered in the application config

### ISSUE THREAD

**Issue by maddy027** [aspnet/Home#3511]
https://github.com/aspnet/EntityFramework6/issues/623 

Code is available here https://github.com/maddy027/IssueWithEF6WithCore.git
when I tried to use EDMX with Asp.net core , getting the below error
System.NotSupportedException: 'Unable to determine the provider name for provider factory of type 'System.Data.SqlClient.SqlClientFactory'. Make sure that the ADO.NET provider is installed or registered in the application config

VS: 2017 15.8
EF: 6.2

**Comment by ajcvickers** [comment]
@maddy027 This project file: https://github.com/maddy027/IssueWithEF6WithCore/blob/master/CoreWithEF/CoreWithEF.csproj

targets `.NET Core` and references the EntityFramework package. This is not  supported. If the documentation you are using results in this kind of project structure, then the documentation needs to be changed. As I said on the other issue, this should be reported as a "content feedback". See here:
![image](https://user-images.githubusercontent.com/1430078/45175732-fd862980-b1c2-11e8-81f0-17a1b1896754.png)

**Comment by maddy027** [comment]
@ajcvickers  Yes , in the doc you can find the below instructions:
![image](https://user-images.githubusercontent.com/14070328/45176216-f1cf4d00-b22c-11e8-9fa3-1215bbb53c08.png):


Create a solution.

Add New Project > Web > ASP.NET Core Web Application (.NET Framework)

Add New Project > Windows Classic Desktop > Class Library (.NET Framework)

In Package Manager Console (PMC) for both projects, run the command Install-Package Entityframework.

**Comment by sirol81** [comment]
I'm experimenting starting from the same Microsoft Docs example and facing this same error, why the sample is it even there if it's not supported?
