### ISSUE TITLE
Unable to use client certificate authentication with WebApplicationFactory

### ISSUE THREAD

**Issue by karelz** [aspnet/Home#3518]
_From @vdachev on September 7, 2018 13:1_

Hello,

I'm trying to set up an integration test for a web application that uses certificate authentication. I use the following code fragment to instantiate the `HttpClient`:
```csharp
var factory = new WebApplicationFactory<Startup>();
HttpClient client = factory.CreateClient();
```
However, I want to pass a client certificate when requesting a resource. The problem is, the client certificate collection is stored in the `HttpClientHandler` but I could not find a way to provide the `WebApplicationFactory` constructor with an instance to the `HttpClientHandler`, neither I found a way to access it through the `HttpClient` or `WebApplicationFactory` instances.

Could you please hint me of a way to achieve that?

_Copied from original issue: dotnet/corefx#32159_

**Comment by Tratcher** [comment]
Client certificates are a TLS transport feature and WebApplicationFactory only uses an in-memory transport so there's no TLS involved, this isn't going to work out of the box.

WebApplicationFactory.TestServer does give you another way to do this though. Rather than using CreateClient, you can instead use CreateRequest and directly populate any server side fields you need for the test like the HttpContext.Connection.ClientCertificate.

**Comment by vdachev** [comment]
Okay, that makes sense.

However, the `Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory<TEntryPoint>` has `Server` property that provides a `Microsoft.AspNetCore.TestHost.TestServer.CreateRequest` method returns a `Microsoft.AspNetCore.TestHost.RequestBuilder` instance. The latter holds references to the test server itself and an `System.Net.Http.HttpRequestMessage`, both of which don't seem to provide an (obvious) access neither to the HTTP connection, nor the HTTP context.

P.S. Meanwhile, I found that the `Microsoft.AspNetCore.TestHost.TestServer` class provides a `SendAsync` method with a `configureContext` parameter.

**Comment by Tratcher** [comment]
Ah you're right, SendAsync(configureContext...) is the method you want.

**Comment by Eilon** [comment]
This issue was moved to aspnet/Mvc#8439
