### ISSUE TITLE
No way to get the request client HTTP version

### ISSUE THREAD

**Issue by TechnikEmpire** [aspnet/Home#3519]
There is no way that I can find anywhere in ASP.NET Core or Kestrel to simply get the HTTP client version for a request/connection. I see in Kestrel that the server does a great deal of work to accurately determine this, and then the result is hidden in internals not available to the end user. Plus, the http context consumes the raw protocol packets and then they're irreversibly disposed, so there's just no way for the user to re-perform this work, even if we felt like doing the same work twice that Kestrel and friends are unnecessarily hiding from us.

Slightly on to another barely related topic, imo the raw header strings should be preserved also since the parser does irreversible transformations on keys and values, but I think that suggestion should go to kestrel server.

Anyway yeah, forgive me if the HTTP version is available (should exist at context or connection scope), but I can't find it and it really ought to be available.

**Comment by Tratcher** [comment]
HttpContext.Request.Protocol?

**Comment by TechnikEmpire** [comment]
@Tratcher What little documentation and reference I could find states that this will simply be `http` but I have not run tests to confirm, I simply took those references at their word.

**Comment by Tratcher** [comment]
Any references? We can get those fixed. "http" should be the Scheme, not the Protocol.

**Comment by TechnikEmpire** [comment]
@Tratcher I'll try to find them, but I'll invest first in doing some actual tests. Hopefully I'm just wrong and can close this out.

**Comment by TechnikEmpire** [comment]
Yeah you're right, and the info was wrong, and I was wrong for not testing it before spamming here with a false issue! Sorry about that. :)
