### ISSUE TITLE
Scaffold identity into an MVC project with authorization using SDK 2.1.4 fail

### ISSUE THREAD

**Issue by lblima** [aspnet/Home#3532]
Hi, after install SDK 2.1.4 I cannot run scafolding identity (instructions here: https://docs.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-2.1&tabs=visual-studio)

After run: dotnet tool install -g dotnet-aspnet-codegenerator

And: 
dotnet add package Microsoft.VisualStudio.Web.CodeGeneration.Design
dotnet restore

I've tried to run this: 

dotnet aspnet-codegenerator identity -dc MyWeb.Data.ApplicationDbContext --files "Account.Register;Account.Login;Account.Logout"

But it doesn't work, I got this message:

It was not possible to find any compatible framework version
The specified framework 'Microsoft.NETCore.App', version '2.1.4' was not found.
  - Check application dependencies and target a framework version installed at:
      C:\Program Files\dotnet
  - Installing .NET Core prerequisites might help resolve this problem:
      http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
  - The .NET Core framework and SDK can be installed from:
      https://aka.ms/dotnet-download
  - The following versions are installed:
      1.0.5 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      1.1.2 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      2.0.9 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      2.1.3 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

----------------------------------------

**dotnet --info:**

SDK do .NET Core (refletindo qualquer global.json):
 Version:   2.1.401
 Commit:    91b1c13032

Ambiente de tempo de execução:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.401\

Host (useful for support):
  Version: 2.1.3
  Commit:  124038c13e

.NET Core SDKs installed:
  1.0.4 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.401 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by cguldogan** [comment]
Hi, 
Does your .csproj file contains the following line ? 

`<PackageReference Include="Microsoft.AspNetCore.App" Version="2.1.4" />`

**Comment by lblima** [comment]
Hi, thanks for answering.

No, I didn’t add the version, I assume it’ll use the latest.

Regards,

Outlook<https://aka.ms/qtex0l> para iOS

________________________________

**Comment by Eilon** [comment]
This issue was moved to aspnet/Scaffolding#875
