### ISSUE TITLE
IFormFile is always null when using [ApiController] Attribute in .Net Core 2.1

### ISSUE THREAD

**Issue by karelz** [aspnet/Home#3533]
_From @skamal-dev on September 12, 2018 13:36_

Not sure why this has not been documented or its a bug but whenever we use ApiController attribute in .Net Core 2.1 version, and use the api method signature as ;
```c#
[Route("api/[controller]")]
 [ApiController]
 public class UploadFileController : ControllerBase
 {
    [HttpPost]
    public async Task<IActionResult> Post([FromForm] IFormFile file)
    {
    }
}
```

Whenever we send request from client the parameter "file" is always null, though the Request.Form.Files do contain the parameter details.

Moment I removed [ApiControlller] and send request from the client, I can see the "file" parameter having values.

_Copied from original issue: dotnet/corefx#32256_

**Comment by Eilon** [comment]
This issue was moved to aspnet/Mvc#8450
