### ISSUE TITLE
Test failure: Factory_CleanupCycle_DisposesEligibleHandler

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/Home#3534]
This test [fails](http://aspnetci/viewLog.html?buildId=553687&buildTypeId=Releases_22xPublic_UbuntuUniverse) occasionally with the following error:
```
Cleanup entry disposable
Expected: True
Actual:   False
   at Microsoft.Extensions.Http.DefaultHttpClientFactoryTest.Factory_CleanupCycle_DisposesEligibleHandler() in /_/test/Microsoft.Extensions.Http.Test/DefaultHttpClientFactoryTest.cs:line 382
--- End of stack trace from previous location where exception was thrown ---
```
Other tests within that build may have failed with a similar message, but they are not listed here. Check the link above for more info.

This test failed on 2.2.

CC @Eilon (because the bot doesn't know who else to pick)

This issue was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by rynowak** [comment]
Yeah I was planning to! this isn't new though.

**Comment by rynowak** [comment]
This is fixed.
