### ISSUE TITLE
DateTime.Now.UTC Bug

### ISSUE THREAD

**Issue by muzzammilhussain** [aspnet/Home#3535]
On Windows Based Machine , When i am using DateTime.Now.UTC it gives me UTC time as soon as I use this on Ubuntu Machine it gives Ubuntu Time instead of UTC time.

On ubuntu the behavior of DateTime.Now= DateTime.UtcNow

Int32 unixTimestamp = (Int32)(DateTime.UtcNow.Subtract(new DateTime(1970, 1, 1))).TotalSeconds;

**Comment by muzzammilhussain** [comment]
I am using .Net Core 2.0 along with Production Machine is Ubuntu 16 Server

**Comment by muzzammilhussain** [comment]
When I use Console Application on Core. It works Fine

alliedschools@allieschools:~/utc$ dotnet UCTTEST.dll 
Hello World!
My Computer Time Is :
9/14/18 2:49:34 PM
UTC TIME IS:
9/14/18 9:49:34 AM


As soon as I run it into web Project it starts doing the same behavior

**Comment by Eilon** [comment]
This issue was moved to dotnet/corefx#32310
