### ISSUE TITLE
ClientId is used by default instead of Audience Id in file AzureAdAuthenticationBuilderExtensions.cs in .Net core 2.0

### ISSUE THREAD

**Issue by jatingandhi28** [aspnet/Home#3538]
File name - AzureAdAuthenticationBuilderExtensions.cs

            public void Configure(string name, JwtBearerOptions options)
            {
                options.Audience = _azureOptions.ClientId;
                options.Authority = $"{_azureOptions.Instance}{_azureOptions.TenantId}";
            }

However It should be 

            public void Configure(string name, JwtBearerOptions options)
            {
                options.Audience = _azureOptions.AudienceId;
                options.Authority = $"{_azureOptions.Instance}{_azureOptions.TenantId}";
            }

**Comment by blowdart** [comment]
This issue was moved to aspnet/Security#1859
