### ISSUE TITLE
Async DataProtection

### ISSUE THREAD

**Issue by sandorfr** [aspnet/Home#3548]
@davidfowl [gave me the courage](https://twitter.com/davidfowl/status/1042620776585748480) to 
Re-request : https://github.com/aspnet/DataProtection/issues/124

> *from @sunsided*
> Apart from the documentation being a bit thin on IXmlRepository, the methods really should be async.
> 
> Considering it's a repository that very likely has something to do with physical storage - which usually blocks - there should be a "native" way to use await within the implementation. I'm currently working on a MongoDB storage and have to resort to use blocking calls just to be able to use it as a repo.
I'm pretty sure other implementations would benefit from that as well.

And

> *from @niemyjski*
> This should be revisited. The only data store that isn't async is an in memory implementation...

And also this excellent feedback (also from @niemyjski)

> I'm thinking the underlying implementation should take care of it and it should be really easy to implement. I've looked at many implementations while implementing a Foundatio IFileStorage version... They all do crazy things and are not uniform on how they:
> 
> Are executed (sync, async, configureawait(false) / Blocking with .Result, or even exponential backoffs...).
> Should XElements be stored in a single file or multiple on disk.
> Should the friendlyName be the file path (when isn't it set to a unique value..)
> Should the element be loaded from a stream or string and with what validation methods or apis.
> Should Gets and Saves be retried.
> Concurrency options, should I be locking?
> How are saved files cleaned up in case of disk storage..
> It's really not intuitive.

So I implore you to revisit it :). I'd be happy to actually contribute if it has any chances to go through.

**Comment by sandorfr** [comment]
> This change likely ripples all the way up the stack to the interface itself (e.g. ProtectAsync)

It will, but every call to it currently to involves a bloody .GetAwaiter().GetResult() when using the most interesting providers like azure key vault https://github.com/aspnet/DataProtection/blob/a9f42e182e529f324fbdf34c417de1d8c0fd9879/src/Microsoft.AspNetCore.DataProtection.AzureKeyVault/AzureKeyVaultXmlDecryptor.cs#L24

**Comment by sandorfr** [comment]
We could keep the synchronous API as a deprecated API on top of the Async one.

**Comment by blowdart** [comment]
It's synchronous **by design**. Both reads and writes are meant to be rare, and both actions need to block, the keyring read so no requests get actioned whilst the keyring hasn't been populated, and write so requests don't get completed with a new key until it's written to the key store. 

This won't change.
