### ISSUE TITLE
CORS issue 

### ISSUE THREAD

**Issue by liricy** [aspnet/Home#3549]
1. Description of the problem:

Getting CORs issue when calling APIs:

![inkedupload a submission 403 error_li](https://user-images.githubusercontent.com/6519992/45947735-30ddfc00-bfaa-11e8-8661-1a0434ac799f.jpg)

   2. Steps to reproduce (preferrably a link to a GitHub repo with a repro project)

https://microsoftit.visualstudio.com/OneITVSO/OneITVSO%20Team/_git/EUS-Col-ColPub-PublishAppsService

On running webpart with 'gulp serve --nobrowser', all api calls fail with CORS error.

   3. The version of `Microsoft.AspNetCore.App` or `Microsoft.AspNetCore.All`
.NET Core 2.1.402

   4. The output of `dotnet --info`

.NET Core SDK (reflecting any global.json):
 Version:   2.1.402
 Commit:    3599f217f4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.402\

Host (useful for support):
  Version: 2.1.4
  Commit:  85255dde3e

.NET Core SDKs installed:
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.302 [C:\Program Files\dotnet\sdk]
  2.1.401 [C:\Program Files\dotnet\sdk]
  2.1.402 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

cc: @guardrex

**Comment by Eilon** [comment]
The app you pointed to seems very large. Can you point to the specific folder that contains the web app that is refusing the CORS connection?

**Comment by licypal** [comment]
Here is the path to file in Service code where I set up the origin:
https://microsoftit.visualstudio.com/OneITVSO/OneITVSO%20Team/_git/EUS-Col-ColPub-PublishAppsService?path=%2FService%2FWebApi%2FService%2FHosts.WebApi%2FStartup.cs&version=GBmaster

Here is the path to file in Webpart code where API calls are failing because of the CORS issue mentioned above:
https://microsoftit.visualstudio.com/OneITVSO/OneITVSO%20Team/_git/EUS-Col-ColPub-PublishApps?path=%2FPublishApps%2Fsrc%2Fwebparts%2FpublishApps%2FComponents%2FSubmitAppForm%2Factions%2FActions.ts&version=GBmaster

Please let me know if you need any other details. Thanks!

**Comment by pranavkm** [comment]
@ManuelDev1810 can you try setting the log level to the most verbose level (https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging) and see what `CorsService` spits out? Might give some hints as to why the service decided a request did not qualify for CORS.

**Comment by mkArtakMSFT** [comment]
Hi. We're closing this issue as we have heard no response from you for some time now. If you have more details and are encountering this issue please add a new reply and re-open the issue.
