### ISSUE TITLE
Improve documentation and process for Linux installation

### ISSUE THREAD

**Issue by atrauzzi** [aspnet/Home#355]
Just going over the instructions and it looks there's a lot of effort made to ensure that someone has a working .NET runtime on OSX, but in Linux the instructions are simply to obtain a copy of the k tools.

Any chance this could be improved upon and maybe some pointers to Mono (which eventually could be updated to Microsoft's own official distributions of .NET for Linux once they become available)?

Definitely related to #154

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
