### ISSUE TITLE
System.FormatException on every Request

### ISSUE THREAD

**Issue by JackSteel97** [aspnet/Home#3550]
### Problem
This exception occurs, as far as I can tell, every time the server receives a request to any of the endpoints. It does not fall out to any of my `catch`s and the program does not crash, the only way I know it happens is the Event log in visual studio shows the below:
![1](https://user-images.githubusercontent.com/13905557/45960957-548a5c00-c015-11e8-8240-c35370e00ad0.png)

Clicking through to Historical Debugging does not provide much useful info either:
![2](https://user-images.githubusercontent.com/13905557/45961001-72f05780-c015-11e8-8237-46fc2f2edc34.png)

The only thing resembling a call stack I can find is in the debug output:
![3](https://user-images.githubusercontent.com/13905557/45961031-83a0cd80-c015-11e8-8718-f43e00fa5f6a.png)

Since it is not breaking anything in my program it isn't a major issue, but it would be nice to know why it's happening; if it's something obscure I've done wrong or a bug in ASP.NET.

If anyone has any troubleshooting suggestions please let me know, if not I will try and get a repo with a repro project up at some point.

### `dotnet --info` output

>.NET Core SDK (reflecting any global.json):
 Version:   2.1.402
 Commit:    3599f217f4

>Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.402\

>Host (useful for support):
  Version: 2.1.4
  Commit:  85255dde3e

>.NET Core SDKs installed:
  1.1.10 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.400 [C:\Program Files\dotnet\sdk]
  2.1.401 [C:\Program Files\dotnet\sdk]
  2.1.402 [C:\Program Files\dotnet\sdk]

>.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.3-servicing-26724-03 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

**Comment by Tratcher** [comment]
Looks like a problem with your session cookie. Have you tried clearing your browser cookies?

If you capture the value first we can see what might be wrong with it.

**Comment by Tratcher** [comment]
No, it's your browser session cookie that looks broken, not your user auth cookie.

**Comment by DM2489** [comment]
Thanks for confirming :)

**Comment by JackSteel97** [comment]
I have cleared all browser cookies and tried again. I noticed that the error is only thrown on requests when I am signed in, and on the request to sign in. From the looks of it, the only cookie available after the error is thrown is the one used for authentication. I am not using any session storage so that would make sense.

**Comment by Tratcher** [comment]
Please share the request headers.

**Comment by JackSteel97** [comment]
@Tratcher 
![image](https://user-images.githubusercontent.com/13905557/46011175-f6b14f00-c0bc-11e8-9a51-56ddb568723e.png)

**Comment by Tratcher** [comment]
Please don't use screen shots for textual data... Copying the text makes it much easier to examine.

**Comment by JackSteel97** [comment]
see edit

**Comment by Tratcher** [comment]
So navigateme.lincoln.ac.uk is the name of your auth cookie? What did you name your session cookie?

**Comment by JackSteel97** [comment]
`...
"Application": {
    "ActiveEnvironment": "development",
    "Session": {
      "IdleTimeout": 20,
      "Cookie": {
        "Name": "navigateme.lincoln.ac.uk"
      }
    },
...`

**Comment by Tratcher** [comment]
Wait, did you set the name of your auth cookie and your session cookie to the same thing? That's not going to work (though I don't know why it would give this error).

**Comment by JackSteel97** [comment]
Thanks, that fixed it. Although those cookies have the same name in some other project and this error has never shown up
