### ISSUE TITLE
Using hubs inside Hostedservice with kestrel on prod environment

### ISSUE THREAD

**Issue by hrnsky** [aspnet/Home#3551]
Hello all, I don't know where to open this issue weather is an issue or not, hope you will help me. I have a background service, running good, I'm running a project with asp.net core 2.1.4 on ubuntu 18 with nginx 1.14 as proxy with kestrel. Inside this background service, I'm using SignalR hub to send some messages to clients. In this background service, some action happens and pushes the json response to the client with clientID. This scenario runs good while debugging on windows 10 with vs 2017, but doesn't work on prod environment. I'm publishing the project with linux-64 option, then run on ubuntu with systemd service. What should i do ? Is it a good practice to use Hubs inside IHostedService ? Also I'm using this hub inside controllers, nothing going bad. How can i log this situation and how to get the log ? I'm tracking with journalctl, there is no exception and also logging my "hub sent" log message. Thanks

**Comment by Tratcher** [comment]
This issue was moved to aspnet/SignalR#3001
