### ISSUE TITLE
kvm.sh with Windows line endings

### ISSUE THREAD

**Issue by ryan1234** [aspnet/Home#356]
I am trying to run the following on Ubuntu 14:

```
# curl -sSL https://raw.githubusercontent.com/aspnet/Home/release/kvminstall.sh | KRE_USER_HOME=$KVM_USER_HOME KVM_BRANCH=dev sh
```
It installs kvm.sh to /opt/k/kvm, which is great.  When I try to source the shell script, I get complaints about line endings:
```
# bash -c "source $KVM_USER_HOME/kvm/kvm.sh"
/opt/k/kvm/kvm.sh: line 3: $'\r': command not found
/opt/k/kvm/kvm.sh: line 15: $'\r': command not found
/opt/k/kvm/kvm.sh: line 17: $'\r': command not found
/opt/k/kvm/kvm.sh: line 18: syntax error near unexpected token `$'{\r''
'opt/k/kvm/kvm.sh: line 18: `__kvm_has() {
```
Were Windows CRLF endings accidentally checked in on https://github.com/aspnet/Home/blob/master/kvm.sh?

I temporarily installed dos2unix and that of course cleaned the file and it's ok now. But maybe something can be introduced to check for this in the future? (Sorry if this is premature considering I'm looking at the dev branch).

**Comment by davidfowl** [comment]
Does this still repro?

**Comment by ryan1234** [comment]
Oh man, it's been a long time. I've since moved on from kvm land to dnx. Is it ok to just close this because kvm is too old? =)
