### ISSUE TITLE
Private Bytes on Azure Web App grows until web app fails to respond to request

### ISSUE THREAD

**Issue by foconnor-DS** [aspnet/Home#3562]
A few weeks back we deployed a new version of a Web API. The API was originally built on .Net Core 1.1, we upgraded it to 2.0. After the upgrade deployed we noticed an unusual pattern in our memory usage. The application at "idle" was using a lot more working set bytes.  Previously it idled around 50MB, and now it was crossing over into 200MB. We also noticed ( after the application stopped responding ) that the private bytes were constantly increasing and never freeing. We got warnings from Azure that we were running out of memory. We had to restart the web app service to free the bytes. We went through a number of changes to try to 'fix' this. We also went ahead and upgraded to 2.1 in hopes it was a .Net core bug that got fixed. We also tried to disable server side GC. Nothing made a noticeable difference. Eventually, the private bytes will reach about 1.8GB, and the application will start to fail ( connection refused). Increasing our app instances delays this somewhat, and we've since configured a workbook to monitor and restart the app automatically. Not the best solution. 

Below you can see the line where we updated to .Net core 2.0 from 1.1. Private bytes are in Orange, the blue is the avg memory working set. Anytime the private bytes go down is during a restart of the web app:
![avgmemworkingset](https://user-images.githubusercontent.com/21093705/46170683-b2a88080-c25b-11e8-97e0-e6f888a381b4.PNG)

I've taken two memory dumps when the application was at it's peak private byte usage. I ran it through Debug Diag Analysis, and used the Memory Pressure Analyzers.  In both cases the warning was the same:
![debugdiaganalysis1](https://user-images.githubusercontent.com/21093705/46171333-77a74c80-c25d-11e8-92bc-fdb0bc1755fc.PNG)

I'm guessing that is a high number of objects waiting for finalization (406,420)

![image](https://user-images.githubusercontent.com/21093705/46171397-9c9bbf80-c25d-11e8-8d77-10425cc1eae4.png)

I've attached the full .mht report that the DebugDiag produces as a zip. 

[dotnet-6d9b27-09-27-18-18-40_MultipleRules.zip](https://github.com/aspnet/Home/files/2425717/dotnet-6d9b27-09-27-18-18-40_MultipleRules.zip)

Please let me know if there's any other debug/analysis I can provide. I've researched past issues that seem to touch on similar problems, but everyone seems to have fixed it in different ways. I did read where one group switched their DAL to full async, and saw this problem go away. We're looking into that. It's something we need to do anyways, and if it magically fixes the memory problem great.

Versions:

> <PackageReference Include="Microsoft.AspNetCore.App" Version="2.1.4" />

> dotnet --info
> .NET Core SDK (reflecting any global.json):
>  Version:   2.1.500-preview-009297
>  Commit:    e5ca1c25d9
> 
> Runtime Environment:
>  OS Name:     Windows
>  OS Version:  10.0.17134
>  OS Platform: Windows
>  RID:         win10-x64
>  Base Path:   C:\Program Files\dotnet\sdk\2.1.500-preview-009297\
> 
> Host (useful for support):
>   Version: 2.1.4
>   Commit:  85255dde3e
> 
> .NET Core SDKs installed:
>   1.0.0-preview2-003131 [C:\Program Files\dotnet\sdk]
>   2.0.2 [C:\Program Files\dotnet\sdk]
>   2.1.4 [C:\Program Files\dotnet\sdk]
>   2.1.100 [C:\Program Files\dotnet\sdk]
>   2.1.102 [C:\Program Files\dotnet\sdk]
>   2.1.103 [C:\Program Files\dotnet\sdk]
>   2.1.104 [C:\Program Files\dotnet\sdk]
>   2.1.201 [C:\Program Files\dotnet\sdk]
>   2.1.202 [C:\Program Files\dotnet\sdk]
>   2.1.400-preview-009063 [C:\Program Files\dotnet\sdk]
>   2.1.400-preview-009171 [C:\Program Files\dotnet\sdk]
>   2.1.400 [C:\Program Files\dotnet\sdk]
>   2.1.402 [C:\Program Files\dotnet\sdk]
>   2.1.500-preview-009297 [C:\Program Files\dotnet\sdk]
> 
> .NET Core runtimes installed:
>   Microsoft.AspNetCore.All 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.All 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.App 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.NETCore.App 1.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>

**Comment by Eilon** [comment]
@sebastienros can you offer any advice here?

**Comment by sebastienros** [comment]
> I'm guessing that is a high number of objects waiting for finalization (406,420)

It the most obvious reason from what I see. So one of the objects is either blocking the finalizers thread, or many objects have a slow finalizer implementation (like a Sleep in it or some IO calls). Could you get a trace of what all threads are doing? I know Perfview can do that if you are running on Windows. Or get a full memory dump, and then open it in Visual Studio.

**Comment by foconnor-DS** [comment]
I'll try.  I have full memory dumps. It's on azure and I'm not sure I can do the trace from Azure web app land.
________________________________

**Comment by foconnor-DS** [comment]
> It's the most obvious reason from what I see. So one of the objects is either blocking the finalizers thread, or many objects have a slow finalizer implementation (like a Sleep in it or some IO calls). Could you get a trace of what all threads are doing? I know Perfview can do that if you are running on Windows. Or get a full memory dump, and then open it in Visual Studio.

@sebastienros I'm not sure how to get what you want from my full memory dump. I'm not sure how to use VS to get you a trace of all threads. I assume you want a stack dump for each thread. I tried to use WinDBG and !eestack but kept getting an error. I saw that Azure can collection .NET profile traces (.diagsession files). I'm not sure if that will help.

If you would like, I can give you access to the full memory dump (~1.3gb).

**Comment by foconnor-DS** [comment]
@sebastienros I think I got the traces you need. I used .Net Profiler Trace from the Azure web app. I'm also seeing a lot of calls stall after: wow64cpu!CpupSyscallStub. That call tree is below:

![image](https://user-images.githubusercontent.com/21093705/46489025-93f93b00-c7c1-11e8-940f-f60973ba0890.png)

I have .diagsessions for these, with thread/stack details. Perhaps they can show you what's blocking the finalizer thread? Let me know how to send them to you.

**Comment by sebastienros** [comment]
Can you give me a link to the file, or share it with me on skype (by splitting in many zips), I'd like to be able to share it with other people. My skype alias is the same.

**Comment by sebastienros** [comment]
@foconnor-DS  found the solution of this issue which can be summarized to the big red warning on this EF documentation: https://docs.microsoft.com/en-us/ef/core/miscellaneous/logging
