### ISSUE TITLE
Upgrading Visual Studio KRE

### ISSUE THREAD

**Issue by OzieGamma** [aspnet/Home#357]
Hi,

I can't seem to upgrade visual studio 2015 preview to use KRE-CLR beta3.

When I hit F5 everything works fine but IntelliSense does not work anymore. Switching to beta1 packages seems to work fine.

**Comment by victorhurdugaci** [comment]
VS 2015 preview doesn't support beta3 KRE because the folder structure changed. Please update to CTP6
