### ISSUE TITLE
Substituting Get for Bind in Configure throws NRE

### ISSUE THREAD

**Issue by jcasale** [aspnet/Home#3570]
In my `Startup.Configure`, when I substitute `ConfigurationBinder.Get` for `ConfigurationBinder.Bind` as follows:

```cs
public void Configure(IApplicationBuilder app, IHostingEnvironment env)
{
    // ...

    // RuntimeSettings runtimeSettings = new RuntimeSettings();
    // this.Configuration.GetSection(nameof(RuntimeSettings)).Bind(runtimeSettings);
    RuntimeSettings runtimeSettings = this.Configuration.GetSection(nameof(RuntimeSettings)).Get<RuntimeSettings>();

    // ...
}
```
In some environments (Win 10 / Server 2016), this works reliably, whereas one of my environments (Server 2012 R2) always throws the following:
```
dotnet .\MyApp.Web.dll
Application startup exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at DataCollectionService.Web.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env) in C:\scm\...\Startup.cs:line 42
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.Internal.AutoRequestServicesStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
```
What causes the difference between environments and why is `Get` any different than `Bind` here?

Both my server environments use `dotnet-hosting-2.1.4-win.exe`, my Win 10 dev host has the following:

```
dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.1.402
 Commit:    3599f217f4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.402\

Host (useful for support):
  Version: 2.1.4
  Commit:  85255dde3e

.NET Core SDKs installed:
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.402 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
```

**Comment by Eilon** [comment]
@HaoK any thoughts on this?

**Comment by Eilon** [comment]
@jcasale which line is line 12 in Startup.cs? Ultimately it's a NullRef in your app's code. You might consider splitting the line into multiple lines or running it in a debugger to isolate the source of the error.

**Comment by HaoK** [comment]
Yeah Bind is a no-op if binding fails (the object passed in is just unchanged) while `Get<T>` returns null if it fails to find anything

**Comment by jcasale** [comment]
Naturally, this only manifests in prod and I don't have the luxury of attaching a debugger to it. Line 42 is somewhat ambiguous, I have `WriteLine`s after each line and the class that is retrieved from configuration is correctly populated. If it matters, my `Main` looks like:

```
public static async Task Main(string[] args)
{
    var logger = NLogBuilder.ConfigureNLog("nlog.config").GetCurrentClassLogger();

    try
    {
        logger.Debug("...");

        var host = CreateWebHostBuilder(args).Build().RunAsync();

        // ...

        await host;

        logger.Debug("...");
    }
    catch (Exception e)
    {
        logger.Error(e, "...");

        throw;
    }
    finally
    {
        NLog.LogManager.Shutdown();
    }
}
```

The commented out call in between `RunAsync` and `await` is where I initialize some code that needs the host up. That is commented out at the moment but the failing environment works fine once `Get` is reverted back to `Bind`. Is this a timing issue resulting from my async main that is environment sensitive?

**Comment by Eilon** [comment]
@jcasale prod-only errors are the best kind 😄 

The pattern shown there is not a common one - getting the `Task` back, doing some work, and then doing the `await`. So, yes, it's possible that there's some code in the commented-out section that is dependent on the builder having run. What code is in there?

**Comment by HaoK** [comment]
If its prod specific, you probably have something that only exists in your debug config that makes the runtime settings return something.  Look at the inputs into your configuration builder and likely there's some config that only exists in the debug that is the main difference

**Comment by jcasale** [comment]
@Eilon, The code in between the task and the await is some Hangfire work, that and all the internally related Hangfire code remains commented out though and the issue persists. Regarding @HaoK's comment about the difference between `Get` and `Bind`, I threw a console write under the `Get` against one of the objects properties and it was populated?

@HaoK, I will check that and try to repro this tonight or tomorrow, thanks for the suggestion.

**Comment by Eilon** [comment]
Can you put the code into Startup.cs instead? That's generally where most initialization logic goes.

**Comment by jcasale** [comment]
@Eilon In this case, I am submitting a one-off job to Hangfire and it must be running. This is the only time I have ever had to modify `Main` from the template to be honest. I think @HaoK nailed it though:) I am just waiting to jump in and test.

**Comment by Eilon** [comment]
@jcasale got it, let us know!

**Comment by jcasale** [comment]
@HaoK you're assumption was correct, and there was a missing configuration parameter. The exception shown wasn't immediately evident to me as a result of the issue (although now it makes sense). I'll add some validation, thank you both for the instant attention and guidance!
