### ISSUE TITLE
[proposal] Pbkdf2 support byte array as password

### ISSUE THREAD

**Issue by Norgerman** [aspnet/Home#3576]
The `KeyDerivation.Pbkdf2` now takes string as password. But in my case, I need the method to take byte[] as password. `Encoding.UTF8.GetBytes` will failed when read invalid bytes.

**Comment by Tratcher** [comment]
@blowdart

**Comment by blowdart** [comment]
Data protection isn't meant for general purpose use, the API surface is limited to the scenarios data protection needs. So, no, I'm afraid not.
