### ISSUE TITLE
Debugging Razor Class library VS 2017

### ISSUE THREAD

**Issue by olegsavelos** [aspnet/Home#3579]
I am trying to debug a razor class library hosted by external process.
I have set the configuration to a Launch: Executable this indeed start the executable but it don't seem that Visual Studio attaches to the process as i don't see no modules to be loaded and cant break.

In contradiction with a normal .NET class library when using the same approach Visual Studio attaches correctly to the launched process and debugging/breaking is possible.

Here is example of launchSettings.json

  "profiles": {
    "SampleModule": {
      "commandName": "Executable",
      "executablePath": "C:\\Programs\\executable.exe",
      "workingDirectory": "C:\\Programs\\"
    },

**Comment by Eilon** [comment]
This issue was moved to aspnet/Razor#2628
