### ISSUE TITLE
After installing VS2015 CTP 6, I can no longer publish.

### ISSUE THREAD

**Issue by developer1998** [aspnet/Home#358]
Hi there.
After installing VS2015 CTP 6, I can no longer publish.
I get this message Unable to locate runtime 'kre-clr-win-x86.1.0.0-beta3'
Locations probed:
kre-clr-win-x86.1.0.0-beta3
C:\Program Files\KRE\runtimes\kre-clr-win-x86.1.0.0-beta3
C:\Users\User\.kre\runtimes\kre-clr-win-x86.1.0.0-beta3

What is interesting though that nowhere in the project it says that I am using kre-clr-win-x86.1.0.0-beta3

I have specific KRE version set to kre-clr-win-x64.1.0.0-beta3 
and under publishing target KRE is also set to kre-clr-win-x64.1.0.0-beta3 

KVM list does not even list beta 3...

Also looking in the directory structure I find the runtime at 
C:\Users\User\.k\runtimes
kre-clr-win-x64.1.0.0-beta3
kre-clr-win-x86.1.0.0-beta3
kre-coreclr-win-x64.1.0.0-beta3
kre-coreclr-win-x86.1.0.0-beta3

How can I resolve this situation so publishing will work again? Thank you so much, you guys are doing great, I am excited about this ground breaking .NET Framework.

**Comment by aguacongas** [comment]
I got the same issue and fixed like that:
Reinstal kvm and reboot after reinstalation if you use Win 10, don't know why, but KRE_HOME env var is not recognized by Win 10 before reboot !

**Comment by matthewhancock** [comment]
I ran into this issue publishing to Azure Websites in VS2015 CTP6. All I needed to do was create a new publish profile. When creating the new profile beta3 was the option in the drop down list and everything worked. Hopefully this applies to your scenario too.

Another note if publishing to Azure Websites, delete everything in the /site/approot/packages/ directory (which requires stopping the application first). Otherwise there will be other conflicts when publishing. Then subsequent publishes will work without requiring stopping. There seems to be a publishing flaw where it will overwrite existing files but won't delete files that no longer exist in the project. For instance if you move a class file to another folder you'll get errors because on the server it will exist in two places after publishing.

**Comment by developer1998** [comment]
I've resolved the issue as follows, but this still should be corrected:
The C:\Users\User\.k directory has a folder called runtimes.
I simply copied that entire folder to C:\Users\User\.kre

Matthew that issue you are facing I also face. C:\Users\User\AppData\Local\Temp\AspNetPublish retains a copy of the initial code, and that is used regardless of what I publish, unless I change the version. How I can counter that is delete everything in AspNetPublish folder and it works. This issue probably deserves it's own issue thread.

**Comment by garora** [comment]
I am getting same problem, I tried all above solutions, unfortunately issue still exists.

**Comment by danroth27** [comment]
@sayedihashimi @barrytang Could you guys please take a look at this?

**Comment by sayedihashimi** [comment]
If you are having publishing issues I would recommend the following.

 - Deleting the ```Properties\PublishProfiles``` folder and re-creating the publish profiles using the VS dialog

I opened a project that was using ```beta3``` and received the same error as above "Unable to locate runtime 'kre-clr-win-x86.1.0.0-beta3'". When I went to the command line and executed ```kvm install 1.0.0-beta3``` I got a 404 stating the package didn't exist. I chatted with @glennc and he let me know there is a bug in the VS installer that ```kvm.cmd``` from ```C:\Program Files\Microsoft ASP.NET 5\Kvm```. To fix this you can do either of the following.

 1 Rename the ```C:\Program Files\Microsoft ASP.NET 5\Kvm``` to something else like ```C:\Program Files\Microsoft ASP.NET 5\Kvm-moved```
 1. Add ```'%USERPROFILE%\.k\bin``` to your machine path

Then run ```kvm install 1.0.0-beta3``` optionally you can pass ```-p``` to remember that. After that you should restart Visual Studio.

@garora can you tell me if that helped you or not?

**Comment by bdelaney** [comment]
Wow. I expected some breaking changes moving from CTP5 to 6, but not like this.
I took an asp.net 5 project from CTP 5 and opened it after upgrading to CTP 6. Ok, some references broken, and I updated packages in project.json to beta 3 from beta 2. That got me building and running locally with IISexpress. But now the publish nightmare begins.

@sayedihashimi  I did like you said and deleted the publish profile folder and started over. Prior to that I had done some changes to the default KRE for the project, and tried rummaging around but no dice. And before I attempted to republish with new profile, I completely deleted the website on Azure.
Build says succeeds but lists missing KRE beta 3. And publish output says failed, with this:
```
Inside GatherAllFilesToPublish
Environment variables:
Path=C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\\Extensions\Microsoft\Web Tools\External;%PATH%;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\\Extensions\Microsoft\Web Tools\External\git
C:\Users\Bill\.k\runtimes\kre-clr-win-x86.1.0.0-beta3\bin\kpm.cmd bundle "C:\Users\Bill\Source\Repos\WIPsiteCombo\WipOpenSite\src\WipOpenSite" --out "C:\Users\Bill\AppData\Local\Temp\AspNetPublish\WipOpenSite-67" --configuration Release --runtime kre-clr-win-x64.1.0.0-beta3 --wwwroot-out "wwwroot" --quiet
[4mRunning "bower:install" (bower) task[24m
[32m>> [39mInstalled bower packages
[32m>> [39mCopied packages to [90mC:\Users\Bill\Source\Repos\WIPsiteCombo\WipOpenSite\src\WipOpenSite\wwwroot\lib[39m
[32mDone, without errors.[39m
Unable to locate runtime 'kre-clr-win-x64.1.0.0-beta3'
Locations probed:
kre-clr-win-x64.1.0.0-beta3
C:\Program Files\KRE\runtimes\kre-clr-win-x64.1.0.0-beta3
C:\Users\Bill\.kre\runtimes\kre-clr-win-x64.1.0.0-beta3
```
I'll try other things listed above, but this is the single most frustrating part of the upgrade to ASP.NET 5. I have read till I'm blue, watched numerous videos, and still it seems like a very difficult process to get the KRE aligned with actual work within Visual Studio. I realize this is one very gutsy change to support other development environments with command line. But the pain points for Visual Studio devs that have been using ASP.NET for years are overwhelming. And I don't find much support in the change logs as new CTPs hit the streets. I've been working on new ASP.NET 5 projects now for the last several CTPs, and I can log dozens of mysterious problems that seem related to component version proliferation.

**Comment by sayedihashimi** [comment]
@bdelaney I'm really sorry to hear that you are running into issues. This is the first that I'm hearing of this. I'd like to help you out and understand your issue better. Perhaps we can have a screensharing session? Can you email me at sayedha@microsoft.com?

With the info provided above here are some initial thoughts

What about new projects? Do those publish fine or do you get similar issues?

If you get similar issues than I think there may be an issue with the default kvm. Try ```kvm list``` and verify that ```1.0.0-beta3``` has a ```*``` next to it and ```default```. If not then execute ```kvm install 1.0.0-beta3 -p``` and restart Visual Studio.

If new projects publish fine then there are a few things you can try. Check the KRE specified for the project in the properties page. Are they the same or different? If different and you didn't expect that update it to match the new project. You should probably delete the publish profiles again if you modified this to be on the safe side. In addition to this you can try and compare the contents of the new .kproj and CTP5 .kproj for any significant difference.

Once again, I'm really sorry you are having issues.

**Comment by bdelaney** [comment]
C:\Program Files\Microsoft ASP.NET 5\Kvm 
I find no such folder under program files or program files x86. I added the environment variable to my system path: %USERPROFILE%\.k\bin and rebooted. But the KVM install command fails with 404 error still.
KVM List shows the following:
```
Active Version           Runtime Architecture Location                    Alias
------ -------           ------- ------------ --------                    -----
       1.0.0-beta1       CLR     amd64        C:\Users\Bill\.kre\packages
       1.0.0-beta1       CLR     x86          C:\Users\Bill\.kre\packages
       1.0.0-beta1       CoreCLR amd64        C:\Users\Bill\.kre\packages
       1.0.0-beta1       CoreCLR x86          C:\Users\Bill\.kre\packages
       1.0.0-beta2       CLR     amd64        C:\Users\Bill\.kre\packages
       1.0.0-beta2       CLR     x86          C:\Users\Bill\.kre\packages default
       1.0.0-beta2       CoreCLR amd64        C:\Users\Bill\.kre\packages
       1.0.0-beta2       CoreCLR x86          C:\Users\Bill\.kre\packages
       1.0.0-beta3-10914 CLR     x86          C:\Users\Bill\.kre\packages
  *    1.0.0-beta3-10921 CLR     x86          C:\Users\Bill\.kre\packages
```
And of course Publish still fails with the unable to find KRE error.

**Comment by bdelaney** [comment]
Thanks Sayed. Well, I'm trying to run the KVM install, but still getting 404 error:
```
C:\Users\Bill\Documents\Visual Studio 2015\Projects\WebApplication3\src\WebApplication3>kvm install
1.0.0-beta3 -p
Downloading KRE-CLR-x86.1.0.0-beta3 from https://www.myget.org/F/aspnetvnext/api/v2
Console-Write-Error : Exception calling "DownloadFile" with "2" argument(s): "The remote server ret
urned an error: (404) Not Found."
At C:\Users\Bill\.kre\bin\kvm.ps1:830 char:3
+   Console-Write-Error $_
+   ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Console-Write-Erro
   r
```

**Comment by aguacongas** [comment]
reinstall kvm with:

    @powershell -NoProfile -ExecutionPolicy unrestricted -Command "iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/aspnet/Home/master/kvminstall.ps1'))"

check your KRE_HOME it must be %USERPROFILE%\\.k

     echo %KRE_HOME%

if not:

     set KRE_HOME=%USERPROFILE%\.k 
     kvm install

**Comment by sayedihashimi** [comment]
FYI we found out what the issue was in @bdelaney project. In CTP5 ```project.json``` had ```packExclude``` which has been changed to ```bundleExclude``` once that was updated he was able to publish.

**Comment by kant2002** [comment]
I have similar issue and suggestion by @aguacongas helps me. I do have missing `kvm` in the %USERPROFILE%\.k folder.
After I reinstall KVM and restart VS I was able to publish project

**Comment by garora** [comment]
@sayedihashimi - great to hear from you. I also sent you an email from g_arora@hotmail.com, I am still having the same issue.
