### ISSUE TITLE
Specified initialization vector (IV) does not match the block size for this algorithm using TripleDesImplementation in asp.net core

### ISSUE THREAD

**Issue by Ashvini2004** [aspnet/Home#3596]
Hi
We have normal asp.net website where we used encryption/decryption of passwords using TripleDesImplementation  algorithm.Now we are converting our site to asp.net core and just moved old encrypted passwords in new database user table. To login users in new site we need to decrypt old passwords so used same decrypt method which we were using earlier TripleDesImplementation  algorithm but throwing exception as below,

Specified initialization vector (IV) does not match the block size for this algorithm.
Parameter name: rgbIV

At line
CryptoStream cs = new CryptoStream(ms, cryptoProvider.CreateDecryptor(KEY_192, IV_192), CryptoStreamMode.Read);

It's still working in our old site.

The encrypt and decryption code is as below:

```c#

public static string Encrypt(string p_szStrValue)
{
    string vszEncryptedString = string.Empty;

     private static byte[] KEY_192 = { XX, XX, XX, XX, XX, XX, XX, XX, XX, XX, XX, XX, XX, XX, XX, XX, XX, XX, XX, XX, XX, XX, XX, XX };
     private static byte[] IV_192 =  { XX, XX, XX, XX, XX, XX, XX, XX, XX, XX, XX, XX, XX, XX, XX, XX, XX, XX, XX, XX, XX, XX, XX, XX };

    if (!p_szStrValue.Trim().Equals(string.Empty))
    {
        TripleDESCryptoServiceProvider cryptoProvider = new TripleDESCryptoServiceProvider();
        MemoryStream ms = new MemoryStream();
        CryptoStream cs = new CryptoStream(ms, cryptoProvider.CreateEncryptor(KEY_192, IV_192), CryptoStreamMode.Write);
        StreamWriter sw = new StreamWriter(cs);
        sw.Write(p_szStrValue);
        sw.Flush();
        cs.FlushFinalBlock();
        ms.Flush();
        vszEncryptedString = Convert.ToBase64String(ms.GetBuffer(), 0, (int)ms.Length);
    }
    return vszEncryptedString;
}

public static string Decrypt(string p_szStrValue)
{
    string vszDecryptedString = string.Empty;
    if (!p_szStrValue.Trim().Equals(string.Empty))
    {
        try
        {
            TripleDESCryptoServiceProvider cryptoProvider = new TripleDESCryptoServiceProvider();
            byte[] v_Buffer = Convert.FromBase64String(p_szStrValue);
            MemoryStream ms = new MemoryStream(v_Buffer);
            CryptoStream cs = new CryptoStream(ms, cryptoProvider.CreateDecryptor(KEY_192, IV_192), CryptoStreamMode.Read);
            StreamReader sr = new StreamReader(cs);
            vszDecryptedString = sr.ReadToEnd();
        }
        catch (Exception e)
        {
            return e.Message;
        }
    }
    return vszDecryptedString;
}

```

**Comment by Tratcher** [comment]
@HaoK @blowdart

**Comment by blowdart** [comment]
@Ashvini2004 I have deleted the key information you provided, on the assumption that might be your "live" encryption key and IV. If you can confirm that those are sample keys and IVs you can add them back, otherwise you have done something rather bad from a security POV and need to examine how to change your encryption keys ASAP.

**Comment by blowdart** [comment]
Also as this isn't an ASP.NET issue, I'm moving this to corefx

**Comment by blowdart** [comment]
This issue was moved to dotnet/corefx#32694
