### ISSUE TITLE
Disable "Automatic HTTP 400 responses" for an individual action

### ISSUE THREAD

**Issue by simonvane** [aspnet/Home#3600]
The "Automatic HTTP 400 responses" functionality added in ASP.NET Core 2.1 is working out really well in most cases. However, I have one action where I need to do some pre-processing before the validation run.

I don't want to lose the functionality for all actions by setting SuppressModelStateInvalidFilter = true. I'd like to be able to say "don't validate" for this action, perhaps with a SuppressModelStateInvalidFilterAttribute on the action.

That way I could retain the benefit but handle special cases myself.

Is there a way to achieve this at the moment?

Thank you.

**Comment by Eilon** [comment]
This issue was moved to aspnet/Mvc#8575
