### ISSUE TITLE
Web API in MVC 6 'IServiceCollection' error

### ISSUE THREAD

**Issue by chowlouise** [aspnet/Home#361]
In my start up class for Web API in MVC 6, i have the following 

```c#
public void ConfigureServices(IServiceCollection services)
{
services.AddMvc();
}
```

And I have this error :

```
The type 'IServiceCollection' exists in both 'Microsoft.Framework.DependencyInjection.IServiceCollection, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' and 'Microsoft.Framework.DependencyInjection.Interfaces, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
```

May i know how can resolve this?

**Comment by davidfowl** [comment]
What version of the KRE and MVC are you using?

**Comment by chowlouise** [comment]
'KRE-CLR-x86.1.0.0-beta2' and "Microsoft.AspNet.Mvc": "6.0.0-beta2"

**Comment by davidfowl** [comment]
Put a repro somewhere.

**Comment by chowlouise** [comment]
sorry may i know what is put a repro?

**Comment by chowlouise** [comment]
you want me to upload my code right?

**Comment by Eilon** [comment]
Yep. If you can put your app up in a GitHub repo or something we can take a look.

**Comment by chowlouise** [comment]
hi , the problem happened after i upgraded to Visual Studio 2015 CTP 6. This error only exists in my project created in previous version. i have a quick check just now and when i change the following inside project.json 
from "Microsoft.AspNet.Server.IIS": "1.0.0-beta2" to "Microsoft.AspNet.Server.IIS": "1.0.0-beta3", and now my error gone. thank you everyone for the replies.

**Comment by Eilon** [comment]
Yup, gotta keep all the versions consistent. It's a bit of a pain during pre-release but once 1.0.0 RTM is out the pain should go away :smile:
