### ISSUE TITLE
SQL SSRS WebForm Control in future ASP.NET

### ISSUE THREAD

**Issue by lywyn** [aspnet/Home#362]
Due to the lack of a supported Sql Server Reporting Services (SSRS) report viewer for MVC we currently have to use a WebForm hosting the WebForm control in an MVC project.  Moving forward how do we use the SSRS Report VIewer without WebForms support?

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.

**Comment by lywyn** [comment]
Our dev team has accepted that SSRS report viewer is no longer useable in new ASP MVC apps and we have sourced an alternative reporting tool instead
