### ISSUE TITLE
Documentation for Upgrading from 4.5

### ISSUE THREAD

**Issue by hbarrington** [aspnet/Home#364]
Hi, 

I've been searching around (both in the documentation here as well as online generally) and have found no information on what it would take or whether it's even possible to upgrade an existing application to asp.net 5 from 4.5

I understand the framework is still under active development and there's a long way to go, I just find it surprising there is no reference at all. Maybe I just missed it? Would it be possible to start even a cursory document on the topic in the wiki?

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
