### ISSUE TITLE
Accepting files in MVC on Linux (kre beta3) corrupts those files

### ISSUE THREAD

**Issue by sinni800** [aspnet/Home#366]
Here's an example project which returns the same file back to you:

https://natori.aspbooru.de/Files/public/thisbreaks.zip

On my CentOs box, KRE beta3, everything else beta3, this should return the same file but it actually returns a corrupted version, a little larger. On Windows this works with any server (Kestrel, IIS, Listener...), it only breaks on Linux/Mono.

I just realized: Sorry for putting this issue up in home, I should have put it somewhere else, though I am actually not sure where.

This is the controller action summing the error up:

        [HttpPost]
		public Task<ActionResult> Add(IFormFile file) 
		{
			return new FileStreamResult(file.OpenReadStream(), "application/octet-stream"); 
		}

The form's encoding is multipart/form-data.

**Comment by sinni800** [comment]
I uploaded an image and posted the result here:
![example](https://cloud.githubusercontent.com/assets/2879097/6574866/6b29f198-c729-11e4-892d-214570a1ab3e.jpg)
![example-returned](https://cloud.githubusercontent.com/assets/2879097/6574868/6e18a318-c729-11e4-9015-4b728fecf3b5.jpg)

**Comment by davidfowl** [comment]
@sinni800 Can you upload your repro project as a github repository instead?

**Comment by sinni800** [comment]
@davidfowl https://github.com/sinni800/aspnet_errordemonstration
You will need to set the $TEMP variable (to /tmp for example) for it to work. Otherwise it will throw a DirectoryNotFoundException.

**Comment by sinni800** [comment]
Additional info: I tried using a bleeding edge version of Mono (mono-20150311171222) instead of the 3.12 release and it seems to work...

**Comment by davidfowl** [comment]
Mono bug then?

**Comment by sinni800** [comment]
@davidfowl I am unsure. Could be in this case but it would have to be tested with old ASP.NET probably. Maybe this bug only creeps up in vNext though.

**Comment by davidfowl** [comment]
If you can repro with the latest bits reopen this bug
