### ISSUE TITLE
Could not load file or assembly Microsoft.Framework.Runtime.IAssemblyLoaderEngine

### ISSUE THREAD

**Issue by aguacongas** [aspnet/Home#367]
Hi, 

using the beta3 I've this issue on a web project:

    klr Information: 0 : [LoaderContainer]: Load name=Microsoft.Framework.Runtime.IAssemblyLoaderEngine
    System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Framework.Runtime.IAssemblyLoaderEngine, Ver
    sion=0.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specifie
    d.
    File name: 'Microsoft.Framework.Runtime.IAssemblyLoaderEngine, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'
       at Microsoft.VisualStudio.Web.BrowserLink.Loader.RegisteredBrowserLinkModule.LoadRuntimeAssembly(IApplicationBuilder
    app, Assembly& runtimeAssembly)
       at Microsoft.VisualStudio.Web.BrowserLink.Loader.RegisteredBrowserLinkModule.GetExtensionType(IApplicationBuilder app
    , Type& extensionType)
       at Microsoft.VisualStudio.Web.BrowserLink.Loader.RegisteredBrowserLinkModule.GetExtensionMethod(IApplicationBuilder a
    pp, String methodName, Type[] parameterTypes, MethodInfo& method)
       at Microsoft.VisualStudio.Web.BrowserLink.Loader.RegisteredBrowserLinkModule.InvokeUseBrowserLink(IApplicationBuilder
     app)
       at Microsoft.AspNet.Builder.BrowserLinkLoaderExtensions.UseBrowserLink(IApplicationBuilder app)
       at ChatLe.Startup.ConfigureErrors(IApplicationBuilder app) in C:\Users\Olivier\Source\Repos\chatle\src\chatle\Startup
    .cs:line 159
       at ChatLe.Startup.Configure(IApplicationBuilder app) in C:\Users\Olivier\Source\Repos\chatle\src\chatle\Startup.cs:li
    ne 138
    
    === Pre-bind state information ===
    LOG: DisplayName = Microsoft.Framework.Runtime.IAssemblyLoaderEngine, Version=0.0.0.0, Culture=neutral, PublicKeyToken=n
    ull
     (Fully-specified)
    LOG: Appbase = file:///C:/Users/Olivier/Source/Repos/chatle/src/chatle
    LOG: Initial PrivatePath = NULL
    Calling assembly : (Unknown).
    ===
    LOG: This bind starts in default load context.
    LOG: No application configuration file found.
    LOG: Using host configuration file: C:\Users\Olivier\.k\runtimes\kre-clr-win-x86.1.0.0-beta3\bin\kre.clr.config
    LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework\v4.0.30319\config\machine.config.
    LOG: Policy not being applied to reference at this time (private, custom, partial, or location-based assembly bind).
    LOG: Attempting download of new URL file:///C:/Users/Olivier/Source/Repos/chatle/src/chatle/Microsoft.Framework.Runtime.
    IAssemblyLoaderEngine.DLL.
    LOG: Attempting download of new URL file:///C:/Users/Olivier/Source/Repos/chatle/src/chatle/Microsoft.Framework.Runtime.
    IAssemblyLoaderEngine/Microsoft.Framework.Runtime.IAssemblyLoaderEngine.DLL.
    LOG: Attempting download of new URL file:///C:/Users/Olivier/Source/Repos/chatle/src/chatle/Microsoft.Framework.Runtime.
    IAssemblyLoaderEngine.EXE.
    LOG: Attempting download of new URL file:///C:/Users/Olivier/Source/Repos/chatle/src/chatle/Microsoft.Framework.Runtime.
    IAssemblyLoaderEngine/Microsoft.Framework.Runtime.IAssemblyLoaderEngine.EXE.
    
        
    C:\Users\Olivier\Source\Repos\chatle\src\chatle>kvm list
    
    Active Version           Runtime Architecture Location                     Alias
    ------ -------           ------- ------------ --------                     -----
           1.0.0-beta3       clr     x64          C:\Users\Olivier\.k\runtimes
      *    1.0.0-beta3       clr     x86          C:\Users\Olivier\.k\runtimes default
           1.0.0-beta3       coreclr x64          C:\Users\Olivier\.k\runtimes
           1.0.0-beta3       coreclr x86          C:\Users\Olivier\.k\runtimes
           1.0.0-beta3-11030 clr     x86          C:\Users\Olivier\.k\runtimes
           1.0.0-beta3-11030 coreclr x86          C:\Users\Olivier\.k\runtimes
    
the project is on [github] (https://github.com/aguacongas/chatle)

**Comment by davidfowl** [comment]
IAssemblyLoaderEngine is gone. Use IAssemblyLoadContextAccesor and IAssemblyLoadContext instead:

https://github.com/aspnet/DNX/blob/1.0.0-beta3/src/Microsoft.Framework.Runtime.Interfaces/IAssemblyLoadContextAccessor.cs
https://github.com/aspnet/DNX/blob/1.0.0-beta3/src/Microsoft.Framework.Runtime.Interfaces/IAssemblyLoadContext.cs

**Comment by aguacongas** [comment]
Ok, it was the dependency to "Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.0.0-beta1"] I upgrade it to beta3 and it works, thx @davidfowl
