### ISSUE TITLE
kvmsetup.cmd fails due to restricted execution policy

### ISSUE THREAD

**Issue by bricelam** [aspnet/Home#38]
When the `Kvm-Global-Setup` function elevates, the execution policy set in `kvm.cmd` is lost. This results in the elevated PowerShell instance using the machine's default execution policy which, by default, is *Restricted*. This results in the following error that is silently swallowed.
```
File Home\kvm.ps1 cannot be loaded because running scripts is disabled on this
system.
```

**Comment by Praburaj** [comment]
Our default installation instruction for kvm in home repo now passes in an unrestricted execution policy. So this issue should be gone now. 

```
@powershell -NoProfile -ExecutionPolicy unrestricted -Command "iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/aspnet/Home/master/kvminstall.ps1'))"
```
