### ISSUE TITLE
Bug or Issue with manual installation of NPM packages in a VS 2015 CTP 6 project folder : Bower is ignored

### ISSUE THREAD

**Issue by xtianus79** [aspnet/Home#380]
perhaps I am in the total wrong place for this. I have an installation i do via NPM... 
When I do these steps in a VS 2015 CTP 6 project folder whether it is on the root or otherwise... Something from Bower is not correct. it won't allow bower to inject libraries in the project. not from a VS point of view but from a CLI point of view which always works. I am trying to get my projected loaded correctly into VS.

here are the steps

NPM install -g yo 
NPM install -g generator -g generator-zf5
yo zf5

upon performing the "grunt" command... the watch takes place and the browser is loaded with the index.html page but the bower libraries are never injected. i.e. jquery isn't loaded and thus doesn't work. A real head scratcher...

I can take the same folder move it one directory up out of the project folder and like magic it works.

I have tried to delete every file and folder... even the hidden .vs folder and nothing works. it is the oddest thing.

**Comment by sayedihashimi** [comment]
Adding @madskristensen

**Comment by xtianus79** [comment]
I have an update on what this is.... It doesn't like the spacing in my folder structure name ie visual studio 2015

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
