### ISSUE TITLE
Custom Exclusion - bower_components and Node_modules are excluded - how to exclude more?

### ISSUE THREAD

**Issue by xtianus79** [aspnet/Home#381]
1) How is bower_components excluded exactly? I tried renaming it in project.json but didn't change the behavior
2) How to exclude myfolder in src/project_name/
3) Why don't we have Exclude option when we right click in solution explorer

**Comment by developer1998** [comment]
I think you need to go to the bower.json file, and removing it from there. I am still learning about it, but I found that this is the place where you decide what gets moved over from downloaded bower components and what is not.

**Comment by xtianus79** [comment]
No the bower.json file is the description of bower dependencies coming in and where those files go into the project.  So, this is not where this should start... it should be in the project.json file but it doesn't seem to work there.  It has to be somewhere in the project solution.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
