### ISSUE TITLE
Nuget Package manager won't install or adhere to References... 

### ISSUE THREAD

**Issue by xtianus79** [aspnet/Home#382]
This is the errors that occur open a new MVC starter web installation.

1>------ Rebuild All started: Project: test11, Configuration: Debug Any CPU ------
1>  C:\Users\<user>\.k\runtimes\kre-clr-win-x86.1.0.0-beta3\bin\klr.exe --appbase "c:\Users\<user>\SkyDrive\Documents\Visual Studio 2015\Projects\test11\src\test11" "C:\Users\<user>\.k\runtimes\kre-clr-win-x86.1.0.0-beta3\bin\lib\Microsoft.Framework.PackageManager\Microsoft.Framework.PackageManager.dll" pack "c:\Users\<user>\SkyDrive\Documents\Visual Studio 2015\Projects\test11\src\test11" --configuration Debug --out "..\..\artifacts\bin\test11"
1>  Failed to initalize runtime (80070002)
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========

and when I try to run the project I get an error the Microsoft.AspNet.Loader isn't installed

**Comment by davidfowl** [comment]
@xtianus79 Can you reproduce this consistently?

**Comment by xtianus79** [comment]
I had my onedrive baked into my document folder. I think that was the main issue. I've done a fresh install of the OS and everything is working fine. But the  issue was happening no matter how many times I reinstalled vs.

Sent from my Windows Phone
________________________________

**Comment by davidfowl** [comment]
If you can create a repro then let me know.
