### ISSUE TITLE
  MusicStore/src/MvcMusicStore/Models/MusicStoreEntities.cs Question

### ISSUE THREAD

**Issue by danofa** [aspnet/Home#383]
Just a small question pertaining to MusicStore/src/MvcMusicStore/Models/MusicStoreEntities.cs
on line 8 you have : base("name=MusicStoreEntities") 

now as i understand it, this is not necessary as the derived context is already named "MusicStoreEntities", am i correct or have i misunderstood its use?
thanks.

**Comment by Eilon** [comment]
@divega @rowanmiller thoughts on this?

**Comment by Eilon** [comment]
Oh actually sorry that's the old MVC Music Store. The original MVC Music Store in that repo (MvcMusicStore) it pretty much an as-is copy of the original, so we deliberately didn't change almost anything in it. The new music store with ASP.NET 5, MVC 6, and EF 7 is called just MusicStore and doesn't have that code.

**Comment by rowanmiller** [comment]
@danofa it's not required but it does force the context to get the connection from the config file. Without that line, if the context didn't load the string from config it would pick another database by convention. I personally also think including it makes it more explicit where the string is coming from.
