### ISSUE TITLE
Preventing script cashing on updates

### ISSUE THREAD

**Issue by developer1998** [aspnet/Home#384]
Now we have all this great functionality to pull down client side packages, like bootstrap.js, etc..
Problem arises on updates, and the issue is script caching.
One wants the script to be cached, until on update.
One way to deal with this is put the version number as a parameter
src="~/lib/bootstrap/js/bootstrap.js?v=3.3.2

So I am wondering could there be a class library which will automatically get updated based on the package downloaded, so I can do a call 
src="~/lib/bootstrap/js/bootstrap.js?v=@(Packages.BoostrapJS.Version)

Another issue is the site itself, version-ing of the local scripts. If my site is packaged as MySite1.0.0. In MVC3 this was achieved aka
@typeof(YourApplicationNamespace.MvcApplication).Assembly.GetName().Version
How can I get the version in  VNEXT

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
