### ISSUE TITLE
bower.json issue with jquery

### ISSUE THREAD

**Issue by developer1998** [aspnet/Home#385]
Current setting does not work

```json
"jquery": {
      "": "jquery.{js,min.js,min.map}"
```

however if I add dist/ it works

```json
"jquery": {
      "": "dist/jquery.{js,min.js,min.map}"
```

I found that all the bower packages that are missing dist/ do not update when you run grunt task bower.

Also I found the hammer entry had additional problems.
It is missing dist directory, which I created and the name referenced hammer should be hammer.js 

```json
		"hammer": {
			"": "hammer.{js,min.js,min.map}"
		}
```

This works

```json
		"hammer.js": {
			"": "dist/hammer.{js,min.js,min.map}"
		}
```

**Comment by Eilon** [comment]
@madskristensen

**Comment by developer1998** [comment]
I guess one has to keep on eye on both dist/ and without dist/
