### ISSUE TITLE
_references.js should have ignore flag

### ISSUE THREAD

**Issue by developer1998** [aspnet/Home#386]
_references.js should have ignore flag autosync enabled="true".
Reason for this is the following. Since it is auto synching, it is grabbing all the files. So I have an older version of a native.js, but I am currently working on new one, and I am removing methods. Since the old native.js still has intellisense therefore the methods that I've removed are still visible. 

If there was ignore="true" then this issue would be gone, because the script references that come over as a result of the autosync enabled set to true, will be ignored.

**Comment by Eilon** [comment]
@madskristensen

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
