### ISSUE TITLE
Error occurred while restoring NuGet packages: the method or operation is not implemented.

### ISSUE THREAD

**Issue by developer1998** [aspnet/Home#391]
I get this when I build and see the web site, or publish, on CTP 6.
Problem happens, even on new project that utilize the ASP.NET Framework 5 web.

One way to counter this is to go to NuGet Package Manager settings and uncheck:
Automatically check for missing packages during built in Visual Studio
but that is not a real solution, just masks an existing problem.

**Comment by davidfowl** [comment]
Can you give a repro project (on github) and also a call stack?

**Comment by developer1998** [comment]
Here it is the repo, https://github.com/developer1998/LewJudy
Where would I get the call stack information? It says on publishing:
Error occurred while restoring NuGet packages: The method or operation is not implemented.

Btw, you motivated me to post my first repo on github. I lost the battle with github for windows, path names were too long, but command line came to the rescue. Thanks.

**Comment by davidfowl** [comment]
Heh, does this still happen?

**Comment by developer1998** [comment]
Yes it is still happening. I will test it again in CTP7, I think I check for it almost every day:)

**Comment by muratg** [comment]
@developer1998 this doesn't repro for me with Beta4 or Beta5 bits.  Could you upgrade your DNX and see if ```dnu restore``` works for you?  I'm getting some npm restore issues in your "prepare" script but nupgks seem to restore just fine.

**Comment by developer1998** [comment]
@davidfowl VC 2015 RC resolved the issue, thank you guys

**Comment by MILL5** [comment]
I am getting this with the RTM bits
