### ISSUE TITLE
Default fingerprinting solution for CSS/JS assets in MVC6 File...New Project

### ISSUE THREAD

**Issue by jhigh2000** [aspnet/Home#394]
As of today, 2015-03-18, there is not a out-of-the-box fingerprinting solution for client side assets in MVC6 projects.  In the interest of feature parity with what was available in web optimization, I'm wondering what the recommended solution will be in this regard.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
