### ISSUE TITLE
Allow overriding the KRE/DNX install path.

### ISSUE THREAD

**Issue by jakeswenson** [aspnet/Home#395]
I'm trying to setup a build server job for one of my projects and i don't want to install KRE/DNX on the build machine (or visual studio for that mater.) 

Currently, I have included the VsTools folder in my build directory, overriden the `VSToolsPath` to be correct and then when I try to build a `.krpoj` it is complaining that KRE is not installed. This is because the Tasks are only looking in the UserProfile directory and the ProgramFiles directory. :disappointed:

If you can provide a override property for the KRE/DNX install path in the `Microsoft.Web.AspNet.props/targets` and allow the msbuild tasks to take that override value in, I can use nuget to pull down the runtime version I need on my build machine and supply its path.

I looked through the decompiled sources of the `Microsoft.Web.AspNet.Tasks.dll` and there is no way to do that right now. (As an aside it's unfortunate the tasks sources aren't publicly available on github...)

**Comment by davidfowl** [comment]
Why don't you want to install it on the build machine?

**Comment by jakeswenson** [comment]
It's not impossible to do, but its an involved process to get something installed on our build farm. Is there any downside with using nuget to pull in the runtime?

**Comment by jakeswenson** [comment]
My goal is to be able to run `kpm bundle` and then do deploy those artifacts as a part of our builds.

**Comment by aguacongas** [comment]
why don't you use kpm build and set KRE_HOME to your KRE path you want tu use ?

**Comment by jakeswenson** [comment]
When I looked, the msbuild tasks weren't looking at KRE_HOME... did i miss something?

**Comment by jakeswenson** [comment]
Fyi, as a work around i have used nuget.exe to download the runtime, and then run kpm.cmd after. We were able to use the --runtime arg with kpm bundle and it's working quite nice!

**Comment by davidfowl** [comment]
@jakeswenson interesting hack :smile:

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
