### ISSUE TITLE
Samples do not work on Windows when using beta 4 and dnvm

### ISSUE THREAD

**Issue by ChrisKlug** [aspnet/Home#396]
Following the steps to run the samples does not work using dnvm instead of kvm, making it hard to get started.

The documentation does not mention that when using the bleeding edge things, you should be cloning the dev branch's samples to get a project.json that has the correct frameworks specified. It also does not mention that you need to add an extra NuGet feed (https://www.myget.org/F/aspnetvnext/api/v2/) to get the packages needed. And finally, the code in the startup.cs files use the UseServices extension method instead of the ConfigureServices() method.

Updating the documentation and samples would make it so much easier for people who wants to get started playing around with ASP.NET 5. And most devs who want to play with this code will probably go for the dnvm.

Steps to get it to work is available at http://bit.ly/1Gy5WUG. It is fairly simple to do, but still a hurdle for someone whos just wants to try it out. I would be more than happy to fix it and do a pull request if that would help.

**Comment by davidfowl** [comment]
You're talking about the dev branch right?

**Comment by ChrisKlug** [comment]
Actually the problems is in both dev and master. The dev branch seem to have gotten some work done on the samples, but they still seem broken. The startup.cs file is using app.UseServices() instead of ConfigureServices(). And the "Running the samples" info in the readme is still focused only around using kvm and beta 3. The steps don't work if you use dnvm

**Comment by davidfowl** [comment]
Master always points to the stable version and isn't expected to work. Dev on the other hand should be updated

**Comment by ChrisKlug** [comment]
Well, https://github.com/aspnet/Home/blob/dev/samples/HelloMvc/Startup.cs still says app.UseServices() which doesn't work...

**Comment by davidfowl** [comment]
Yes like I just said, it needs to be updated. That method was removed last night

**Comment by ChrisKlug** [comment]
Ahh...ok. Sorry. I read "should be updated" as in that is should have been updated by now. 

That explains why it worked for me yesterday, but not today...

Is it something you want to handle internally, or should I fix it and do a pull request?

**Comment by davidfowl** [comment]
Pull request would be great!

**Comment by Praburaj** [comment]
Looks like this is fixed : https://github.com/aspnet/Home/commit/8373764c613f3a2b6e6ec9482010966bbffd77a4
