### ISSUE TITLE
FTP deploy to Azure wiki link redirects to Home

### ISSUE THREAD

**Issue by david-peden-q2** [aspnet/Home#399]
https://github.com/aspnet/Home/wiki/FTP-deploy-an-AspNet-vNext-application-to-Microsoft-Azure-websites

->

https://github.com/aspnet/Home/wiki

**Comment by david-peden-q2** [comment]
Looks like the correct URI is:

https://github.com/aspnet/Home/wiki/Deploy-an-AspNet-vNext-application-to-Microsoft-Azure-websites

**Comment by brucecallen** [comment]
David,

What do you think of VNext?

I played with it for a little bit I decided to wait until some the beta
issues were worked out.


Bruce Callen
bruce.p.callen@gmail.com
(512) 827-8232
Skype:bruce.callen
http://www.linkedin.com/in/brucecallen

**Comment by luisrudge** [comment]
:+1:  please fix this :)

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
