### ISSUE TITLE
Retag beta3 with correct samples

### ISSUE THREAD

**Issue by ahmetalpbalkan** [aspnet/Home#403]
As addressed in #348, samples were not updated before tagging beta3 and **this BLOCKS the release of aspnet:1.0.0-beta3 Docker image**. https://github.com/aspnet/aspnet-docker/pull/38

In order to unblock you need to advance the tag pointer by 1 commit and choose b1b5cbb558587a0822d318605dba401f56787cda as beta3 tag 

I probably brought this up several times now on GitHub/Jabbr. 
I hope I can get your attention this time. @Eilon @davidfowl @danroth27

**Comment by Eilon** [comment]
@Praburaj can you update the beta3 tag to include the commit from #348?

**Comment by Praburaj** [comment]
@ahmetalpbalkan - beta3 now points to the right tag https://github.com/aspnet/Home/commit/8ec209d022c38c9f83324375b98caf54be12d659 (this is one ahead of https://github.com/aspnet/Home/commit/b1b5cbb558587a0822d318605dba401f56787cda). Can you check if it works for you?

**Comment by ahmetalpbalkan** [comment]
@Praburaj seems fixed thanks.

**Comment by Praburaj** [comment]
@ahmetalpbalkan thanks for responding.
