### ISSUE TITLE
How do you get current physical path inside Startup.cs?

### ISSUE THREAD

**Issue by developer1998** [aspnet/Home#405]
How do you get current physical path inside Startup.cs? 
I tried so many things and it does not work. On top of that I am experiencing a very very strange behavior.
When I am debugging and type AppDomain.CurrentDomain.BaseDirectory I get the current path.
However I cannot even compile the code as I get this error on run time if I include AppDomain.CurrentDomain.BaseDirectory directly.
The name 'AppDomain' does not exist in the current context

Thanks.

**Comment by davidfowl** [comment]
Don't use that API. Use the one provided by the framework. In your Startup.cs you can take `IApplicationEnvironment` in the Configure method:

```
public void Configure(IApplicationBuilder app, IApplicationEnvironment env)
{
   var path  = env.ApplicationBasePath;
}
```

**Comment by developer1998** [comment]
Thanks for your response David. Where does IApplicationEnvironment live?

my Configure looks like this, I am using beta3 btw:
public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerfactory) and I get this error

Error	CS1061	'IHostingEnvironment' does not contain a definition for 'ApplicationBasePath' and no extension method 'ApplicationBasePath' accepting a first argument of type 'IHostingEnvironment' could be found (are you missing a using directive or an assembly reference?)

Thanks.

**Comment by davidfowl** [comment]
Close, IApplicaitonEnvironment lives in the Microsoft.Framework.Runtime.Interfaces package (which you already reference transitively)

**Comment by developer1998** [comment]
Thank you.
