### ISSUE TITLE
Binding redirects are still needed

### ISSUE THREAD

**Issue by tommck** [aspnet/Home#407]
When using Autofac.Extras.Attributed version 3.2.1 and Autofac 3.5.2, I get this problem:

Assuming assembly reference 'Autofac, Version=3.4.0.0, Culture=neutral, PublicKeyToken=17863af14b0044da' used by 'Autofac.Extras.Attributed' matches identity 'Autofac, Version=3.5.0.0, Culture=neutral, PublicKeyToken=17863af14b0044da' of 'Autofac', you may need to supply runtime policy

Since redirects are not supported at this point, there's no way to get rid of this warning in our solution.

**Comment by davidfowl** [comment]
Binding redirects aren't needed and aren't coming back. That's just a warning and I agree it's annoying, but it runs right? We may just need to ask Roslyn for a tweak here to allow disabling that warning completely.

/cc @tomat

**Comment by tommck** [comment]
OK. Yes, it's just a warning, but many dev shops don't allow checkins with compiler warnings, so it's a problem in those situations.

**Comment by davidfowl** [comment]
I get it, but asking for binding redirects is the wrong thing. Asking to get rid of the warning is the right thing.

**Comment by tommck** [comment]
Absolutely agree that the warning needs to go away. Just wasn't sure if we wanted to hide what was happening from developers.

**Comment by davidfowl** [comment]
Yes, we absolutely do because the only control developers have is specifying versions in the project.json file.

**Comment by tommck** [comment]
Ah, that's very true.  Good point.  I'll close this then

**Comment by davidfowl** [comment]
Ask and you shall receive https://github.com/aspnet/dnx/commit/649eb7b5a5283d0450c46c08fb8fd8ea4acceabb

**Comment by tommck** [comment]
Thank you!
