### ISSUE TITLE
Using dependency injection which as great Scott says: "is available in a consistent way throughout the entire web stack"

### ISSUE THREAD

**Issue by developer1998** [aspnet/Home#408]
So I enable it inside Startup.cs as so:

```c#
services.AddSingleton < IClientPackagesRepository, ClientPackagesRepository > () ;
```

I can do the injection on Controller level using

```c#
private readonly IClientPackagesRepository _repository;
public HomeController(IClientPackagesRepository repository)
```

I can do the injection as well on View level using 

```c#
@inject IClientPackagesRepository repository;
```

What about if I want to do the injection right in Startup.cs?
I cannot figure out how to do it, and according to great Scott says in 
https://weblogs.asp.net/scottgu/introducing-asp-net-5
I should be able.
I am thinking along the lines

```c#
app.UseServices...
```
Thanks for your help.

**Comment by danieltharris** [comment]
Another way is to use the [Activate] attribute if you want to do property injection too, I believe. 

When you pass your dependency into the constructor for your controller, the Dependency Resolver is resolving and passing in your dependency when the controller is constructed. 

Can you give an example of what you mean by doing the injection in Startup.cs and what the context is for what you're wanting to do?

**Comment by Eilon** [comment]
What do you mean by "doing the injection right in Startup.cs"? What type of code are you imagining?

**Comment by developer1998** [comment]
I need to populate this singleton with data right in Startup.cs. Is that even possible is the question? Reason for this because I need to access that data in many places, and Startup.cs is the best place that I can think off.

**Comment by davidfowl** [comment]
Configure is injected.

```C#
public class Startup
{
    public void Configure(IApplicationBuilder app, IClientPackagesRepository repo)
    {
    }
}
```

Anything you add as a service is available in the Configure method. So yes, "is available in a consistent way throughout the entire web stack"

**Comment by developer1998** [comment]
David it works!!! Thank you so much, and I've learned also that Configure accepts dynamic parameters, which is amazing... You guys are doing great job.

public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerfactory, IClientPackagesRepository repo)

**Comment by davidfowl** [comment]
Yep, any service provided by the host or by services you added are accessible.
