### ISSUE TITLE
ASP.NET Crashes on a complex gruntfile.js save in VS CTP 6

### ISSUE THREAD

**Issue by xtianus79** [aspnet/Home#409]
https://github.com/xtianus79/generator-aspnet/blob/master/templates/projects/christian/_gruntfile.js

here is file in question.  As you can see the last grunt task is commented out // because upon un-commenting it and saving it VS will Crash... This is for VS 2015 CTP 6

**Comment by madskristensen** [comment]
We're taking a look

**Comment by xtianus79** [comment]
It seems like it is something with the javascript environment.  I don't know the relation of the grunt file but my memory and cpu usage goes through the roof when doing the process.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
