### ISSUE TITLE
InvalidOperationException upon accessing AccountsController from default yeoman generator

### ISSUE THREAD

**Issue by russjr08** [aspnet/Home#410]
The full error: "InvalidOperationException: Unable to resolve service for type 'WebApplication.Models.ApplicationDbContext' while attempting to activate 'Microsoft.AspNet.Identity.EntityFramework.UserStore`3[WebApplication.Models.ApplicationUser,Microsoft.AspNet.Identity.IdentityRole,WebApplication.Models.ApplicationDbContext]'."

I'm on OS X 10.10, trying to setup a default ASP.NET Web Application using Yeoman (generator-aspnet). Upon trying to access /Accounts/Login, or /Accounts/Register, the error above is displayed.

Does EF work on OS X? If not, what methods can I go about to persisting data. (While avoiding writing manual SQL statements everywhere...) My apologies if it is felt that this issue doesn't belong here. Wasn't sure where exactly it'd belong. It does however somewhat match Issue #359, but no one ever got to it.

**Comment by russjr08** [comment]
So what I've been able to gather is, that EF does not work on OS X / unix based operating systems just yet. Something like this http://tattoocoder.com/building-vnext-web-api-using-mvc-6-mongodb-azure/ is recommended for the time being.

**Comment by Eilon** [comment]
@divega can you take a look?

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
