### ISSUE TITLE
README.md lists 'kpm restore' - where is kpm?

### ISSUE THREAD

**Issue by WalterHub** [aspnet/Home#412]
In the README section for running the samples, it mentions running 'kpm restore'. kpm does not resolve to a command. Where do I get kpm, or is kpm a typo?

**Comment by 0xdeafcafe** [comment]
Are you using DNX or KVM? If you're using KVM, kpm is an `cmd` file inside the bin folder of the selected runtime, for me it's at `C:\Users\Alex\.k\runtimes\kre-coreclr-win-x64.1.0.0-beta3\bin\kpm.cmd`. It might be the same for DNX, but I don't know for sure.

**Comment by kalluri-nb** [comment]
If you are using DNX use dnu restore

**Comment by WalterHub** [comment]
Got it. I'm using DNX, and I see dnu.cmd in the .dnx\runtimes\... path. Thanks!

**Comment by davidfowl** [comment]
don't feel bad, our docs suck big time.
