### ISSUE TITLE
Install script (falsely) claims to modify process environment

### ISSUE THREAD

**Issue by Jaykul** [aspnet/Home#413]
When running the install script the `dnvm setup` command outputs text indicating that it has set the process environment variables so I can use DNVM:

```
Adding C:\Users\Jaykul\.dnx\bin to Process PATH
Adding C:\Users\Jaykul\.dnx\bin to User PATH
Adding C:\Users\Jaykul\.dnx to Process DNX_HOME
Adding C:\Users\Jaykul\.dnx to User DNX_HOME
```

In fact, after the install finishes, the environment is not set, because the install script is (needlessly) running multiple nested processes.

If you just use the PowerShell portion of the install script (the contents of the &{...} block), it _could_ work, but it still doesn't, because in the `dnvminstall.ps1` when you call `dnvm setup` you are running the CMD version (starting a new process) which _then_ calls the PowerShell version (starting another new process), so when the process environment is set, it's on a process which immediately terminates.

If the `dnvminstall.ps1` script just called the `dnvm.ps1` script directly instead, my environment would be set, and I wouldn't need to exit PowerShell and start a new process to pick up the changes to my PATH.

My suggestion would be to have the home README specify a PowerShell-friendly version of the install command, and just tell people to run it there -- and **also** alter the `dnvminstall.ps1` script so that you're not calling CMD from PowerShell just to get you back into Powershell...

The alternative might be to put a -quiet switch on the setup command so you're not printing messages that aren't true ;-)

FWIW, the PowerShell 3+ version of the install command could be as simple as:

```
$Branch='dev'; iex (irm https://github.com/aspnet/Home/raw/dev/dnvminstall.ps1)
```

**Comment by davidfowl** [comment]
File this on https://github.com/aspnet/dnvm

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
