### ISSUE TITLE
Custom Helper method in scope of all the views

### ISSUE THREAD

**Issue by developer1998** [aspnet/Home#415]
In previous versions of MVC.NET to put the custom helper method in the scope of all the views, one utilized ~/Views/web.config
as per below
```XML
< system.web.webPages.razor >
...
            <namespaces>
                < add namespace="System.Web.Mvc" / >
...
                < add namespace="CustomHelperNamespace" / >
```
How to achieve the same effect in .NET 5? Thank you.

**Comment by NTaylorMullen** [comment]
Create a `_GlobalImport.cshtml` in the same folder or one above it and add an `@using mynamespace` statement to it.

`_GlobalImport.cshtml` enables inheriting Razor directives to your corresponding views.

For referrence: http://stackoverflow.com/questions/28719298/add-namespace-to-all-views-in-asp-net-mvc-6/28729828#28729828

**Comment by developer1998** [comment]
Thank you very much.

**Comment by developer1998** [comment]
@NTaylorMullen 
It is not working.
Inside _GlobalImport.cshtml I've put the reference @using LewJudy.Helpers;

Then inside _Layout.cshtml I type @ ( Html. and I do not see my custom helper on the list.

**Comment by davidfowl** [comment]
@developer1998 What version are you using?

**Comment by developer1998** [comment]
I am at 1.0.0 beta3 clr x64

**Comment by davidfowl** [comment]
Then you didn;t read @NTaylorMullen 's advice correctly. There are specific beta3 instructions. GlobalImport is a beta4 feature.

**Comment by davidfowl** [comment]
See http://stackoverflow.com/questions/28719298/add-namespace-to-all-views-in-asp-net-mvc-6/28729828#28729828

**Comment by developer1998** [comment]
There was a typo there For >= beta3. Cool, I will try it out on beta4, thank you.
