### ISSUE TITLE
How to use dnx-clr-win-x64.1.0.0-beta5-11394 with CTP6?

### ISSUE THREAD

**Issue by developer1998** [aspnet/Home#417]
The CTP6 still shows kre packages of beta3.

**Comment by davidfowl** [comment]
Read this https://github.com/aspnet/Home/issues/368

TL;DR you can't do it

**Comment by developer1998** [comment]
@davidfowl 
I see that you listed Safe Packages before rename
kre-clr-win-x64.1.0.0-beta4-11203
kre-clr-win-x86.1.0.0-beta4-11203
kre-coreclr-win-x64.1.0.0-beta4-11203
kre-coreclr-win-x86.1.0.0-beta4-11203
kre-mono.1.0.0-beta4-11203

How can I grab them of the nuget feed?
When I type kvm install latest
It tells me Determining latest version 
kre-clr-win-x86.1.0.0-beta3 already installed.

**Comment by davidfowl** [comment]
To get beta4 KRE then you need to set the KRE_FEED environment variable to "https://www.myget.org/F/aspnetlastkre/api/v2"

**Comment by developer1998** [comment]
Thanks it works.

**Comment by developer1998** [comment]
@davidfowl 
Now I have to figure out how to get the latest packages, what is the command to pull for example
Microsoft.Framework.Runtime.Interfaces 1.0.0-beta4-11203 
When I do Get-Package -ListAvailable I don't see it. I assume I am missing the correct package source. What is the URL, thanks?
.
Failed to resolve the following dependencies for target framework 'Asp.Net,Version=v5.0':
  EntityFramework.Commands 7.0.0-beta3
  EntityFramework.SqlServer 7.0.0-beta3
  kre-clr-win-x86 1.0.0-beta3
  Microsoft.AspNet.Diagnostics 1.0.0-beta3
  Microsoft.AspNet.Diagnostics.Entity 7.0.0-beta3
  Microsoft.AspNet.Identity.EntityFramework 3.0.0-beta3
  Microsoft.AspNet.Mvc 6.0.0-beta3
  Microsoft.AspNet.Security.Cookies 1.0.0-beta3
  Microsoft.AspNet.Server.IIS 1.0.0-beta3
  Microsoft.AspNet.Server.WebListener 1.0.0-beta3
  Microsoft.AspNet.StaticFiles 1.0.0-beta3
  Microsoft.Framework.CodeGenerators.Mvc 1.0.0-beta3
  Microsoft.Framework.ConfigurationModel.Json 1.0.0-beta3
  Microsoft.Framework.Logging 1.0.0-beta3
  Microsoft.Framework.Logging.Console 1.0.0-beta3
  Microsoft.VisualStudio.Web.BrowserLink.Loader 14.0.0-beta3

**Comment by davidfowl** [comment]
It's the same package source as what you specified for KRE_FEED. That and you have to change the versions in your project.json

**Comment by developer1998** [comment]
@davidfowl I was able to get all those updated to beta 4
by running Install-Package [PackageName] -Pre except 		"Microsoft.AspNet.Security.Cookies": "1.0.0-beta3", and Visual Studio gave me 330+ error count. I got on all packages yellow warning exclamation points, so something I am probably missing. I think maybe it is better I wait for CTP7, since CTP6 is going away...

	"dependencies": {
		"EntityFramework.SqlServer": "7.0.0-beta3",
		"EntityFramework.Commands": "7.0.0-beta3",
		"Microsoft.AspNet.Mvc": "6.0.0-beta3",
		/* "Microsoft.AspNet.Mvc.WebApiCompatShim": "6.0.0-beta3", */
		"Microsoft.AspNet.Diagnostics": "1.0.0-beta3",
		"Microsoft.AspNet.Diagnostics.Entity": "7.0.0-beta3",
		"Microsoft.AspNet.Identity.EntityFramework": "3.0.0-beta3",
		"Microsoft.AspNet.Security.Cookies": "1.0.0-beta3",
		"Microsoft.AspNet.Server.IIS": "1.0.0-beta3",
		"Microsoft.AspNet.Server.WebListener": "1.0.0-beta3",
		"Microsoft.AspNet.StaticFiles": "1.0.0-beta3",
		"Microsoft.Framework.ConfigurationModel.Json": "1.0.0-beta3",
		"Microsoft.Framework.CodeGenerators.Mvc": "1.0.0-beta3",
		"Microsoft.Framework.Logging": "1.0.0-beta3",
		"Microsoft.Framework.Logging.Console": "1.0.0-beta3",
		"Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.0.0-beta3",
		"kre-clr-win-x86": "1.0.0-beta3"
	},

**Comment by jkyadav** [comment]
I am also getting same error..

Failed to resolve the following dependencies for target framework 'Asp.Net,Version=v5.0':
  EntityFramework.Commands 7.0.0-beta3
  EntityFramework.SqlServer 7.0.0-beta3
  Microsoft.AspNet.Mvc 6.0.0-beta3

But I am getting for these 3 only. What am doing worng? have used kpm restore command on command prompt.
