### ISSUE TITLE
kpm failing on Mac OSX Yosmite

### ISSUE THREAD

**Issue by plkumar** [aspnet/Home#418]
kpm failing on Mac OSX Yosmite

```
Lakshmans-Mac-mini:bin lakshman$ kvm upgrade
Determining latest version
Latest version is 1.0.0-beta3
kre-mono.1.0.0-beta3 already installed.
Adding /Users/lakshman/.k/runtimes/kre-mono.1.0.0-beta3/bin to process PATH
Updating alias 'default' to 'kre-mono.1.0.0-beta3'
Lakshmans-Mac-mini:bin lakshman$ kpm
Missing method System.Threading.Tasks.Task::FromResult<[1]>(!!0) in assembly /opt/local/lib/mono/4.0/mscorlib.dll, referenced in assembly /Users/lakshman/.k/runtimes/kre-mono.1.0.0-beta3/bin/kre.mono.managed.dll
System.MissingMethodException: Method not found: 'System.Threading.Tasks.Task.FromResult'.
  at kre.hosting.RuntimeBootstrapper.Execute (System.String[] args) [0x00000] in <filename unknown>:0 
```

**Comment by davidfowl** [comment]
Looks like you need to update your mono version.

**Comment by plkumar** [comment]
i tried upgrading the mono version with brew, my current mono version is below, but still the same issue.

Mono JIT compiler version 2.10.9 (tarball Sat Nov 10 17:22:29 IST 2012)
Copyright (C) 2002-2011 Novell, Inc, Xamarin, Inc and Contributors. www.mono-project.com
	TLS:           normal
	SIGSEGV:       normal
	Notification:  kqueue
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	LLVM:          supported, not enabled.
	GC:            Included Boehm (with typed GC)

**Comment by davidfowl** [comment]
Yea that's beause it's still a super old version of mono. I'd suggest trolling through the many threads on aspnet/Home or search for how you update mono to the correct version.
