### ISSUE TITLE
Nothing happen when run sample console app (Windows 7 HOME edition)

### ISSUE THREAD

**Issue by raviprajapat** [aspnet/Home#421]
I follow the all procedural regarding installing DNX and it shows me successfully installed the .net execution environment.
When I going to run the sample console app using command nothing is happen. see the screenshots.

![aspnet5](https://cloud.githubusercontent.com/assets/3158005/6885183/82ff9c02-d631-11e4-9270-3953d7729cae.png)

**Comment by davidfowl** [comment]
Try setting `DNX_TRACE=1` and re-running. That will print more diagnostic information.

**Comment by davidfowl** [comment]
Also, what OS are you running on?

**Comment by raviprajapat** [comment]
I'm using windows 7 SP1 Home.
Can you let me know how can I enable DNX_TRACE=1 in setting?

**Comment by davidfowl** [comment]
in the command prompt `set DNX_TRACE=1`. You're running .NET 4.5 right?

**Comment by raviprajapat** [comment]
Yes I'm running .NET 4.5.
After enable trace setting it shows me "failed to load dnx.clr.dll"

**Comment by raviprajapat** [comment]
Please tell me the possible way there I can able to resolve this issue.

**Comment by davidfowl** [comment]
It might just be a bug you can't work around. Post the results of running with tracing on:

/cc @troydai @victorhurdugaci @muratg

**Comment by victorhurdugaci** [comment]
1. Do you have .NET 4.5.1 installed?
1. What is the exit code from the app?
1. What happens if you run on CoreCLR?

**Comment by victorhurdugaci** [comment]
One more question: what DNX version are you using?

**Comment by raviprajapat** [comment]
1 Yes I have installed .NET 4.5.1
2 This is my simple console app code
```
using System;
public class Program
{
    public static void Main()
    {
        Console.WriteLine("Hello World");
		Console.ReadLine();
    }
}
```
3 I didn’t tried with CoreCLR. Can you assist me how I can do with this?
4 DNX version is `dnx-clr-win-x86.1.0.0-beta5-11427`.

**Comment by victorhurdugaci** [comment]
Sure, here is how to get the app running on CoreCLR:

1. Run `dnvm upgrade -r CoreClr`
2. Run `dnvm list`. Make sure the CoreCLR runtime is active (should have a star in front of it)
3. Run the app again

But, before you do that, what is the exit code from the app? In command prompt, you can get it with `echo %errorlevel%` and in PowerShell with `$lastexitcode`

**Comment by raviprajapat** [comment]
It showing me `Faild to load: dnx.CoreClr.dll `.
When I using `echo %errorlevel%` it display `0'.

**Comment by troydai** [comment]
@raviprajapat Do you have all the Windows Update installed? And also do you have VC++ redistribution installed?

**Comment by raviprajapat** [comment]
@troydai Yes I have installed VC++ redistribution 2012 in my PC. My pc also has Visual Studio 2013 ultimate version which means all recently frameworks 4.5.1 is installed as well. Today I also installed the framework 4.5.2.
My system running on Win 7 SP1.

**Comment by troydai** [comment]
@raviprajapat can you check your event log?

**Comment by victorhurdugaci** [comment]
Ravi, can you please do this:

1. Start the application with the debug flag: `dnx --debug . run`
2. Attach the VS debugger (native + managed 4.5) to the process
3. See if you can get more info.

**Comment by raviprajapat** [comment]
@troydai  which event log? Are you talking about system event log?

**Comment by troydai** [comment]
Yes, I am. Looking for error/warning registered under dnx.

**Comment by raviprajapat** [comment]
@victorhurdugaci On attached debugger
![debuginfo](https://cloud.githubusercontent.com/assets/3158005/6946617/4a80d1ee-d8bf-11e4-82bc-7de885fa8686.png)
 
VS debug output message
`'dnx.exe' (Win32): Loaded 'C:\Users\user\.dnx\runtimes\dnx-coreclr-win-x86.1.0.0-beta5-11427\bin\dnx.exe'. Cannot find or open the PDB file.
'dnx.exe' (Win32): Loaded 'C:\Windows\SysWOW64\ntdll.dll'. Cannot find or open the PDB file.
'dnx.exe' (Win32): Loaded 'C:\Windows\SysWOW64\kernel32.dll'. Cannot find or open the PDB file.
'dnx.exe' (Win32): Loaded 'C:\Windows\SysWOW64\KernelBase.dll'. Cannot find or open the PDB file.
'dnx.exe' (Win32): Loaded 'C:\Users\user\.dnx\runtimes\dnx-coreclr-win-x86.1.0.0-beta5-11427\bin\api-ms-win-core-synch-l1-2-0.dll'. Cannot find or open the PDB file.
'dnx.exe' (Win32): Loaded 'C:\Windows\SysWOW64\msvcrt.dll'. Cannot find or open the PDB file.
The thread 0x3590 has exited with code 0 (0x0).
The program '[13932] dnx.exe' has exited with code 0 (0x0).`

**Comment by raviprajapat** [comment]
Nothing I found regarding dnx event logs.

**Comment by raviprajapat** [comment]
It strange for my when I did same thing on Win7 Professional SP1 which has installed framework 4.5.1 with VS 2013 it successfully run sample Console App using Aspnet 5.
Is there any restriction for Win 7 Home edition to use Aspnet 5?

**Comment by troydai** [comment]
/cc @victorhurdugaci @davidfowl @danroth27 

@raviprajapat Thank you for letting us know. We indeed are not aware of this particular issue on Windows 7 Home.
