### ISSUE TITLE
What is the equivalent WebApp.Start<TStartup> in ASP.NET 5

### ISSUE THREAD

**Issue by tugberkugurlu** [aspnet/Home#422]
In katana, there was an easy way to host an application in console through `WebApp.Start<TStartup>` API. Is there an equivalent in ASP.NET 5? I wasn't able to find it.

**Comment by Praburaj** [comment]
There is no equivalent yet. This is what hosting does : 

https://github.com/aspnet/MusicStore/blob/master/src/MusicStore/Program.cs#L46

If you are using dev: 
https://github.com/aspnet/MusicStore/blob/dev/src/MusicStore/Program.cs#L20

**Comment by davidfowl** [comment]
It's coming in the latest builds @HaoK just committed new hosting changes for this

**Comment by tugberkugurlu** [comment]
@davidfowl you mean the `WebHost.Create` stuff?

**Comment by davidfowl** [comment]
Yep
