### ISSUE TITLE
Unable to locate runtime 'KRE-CLR-x86.1.0.0-beta1'

### ISSUE THREAD

**Issue by ghostdlr** [aspnet/Home#423]
I get this error when i try to publish :
Unable to locate runtime 'KRE-CLR-x86.1.0.0-beta1'

I tried everything i found on this issue , with no luck . Even reinstalling visual studio didn't help .

**Comment by muratg** [comment]
What version of VS are you using?  Latest CTP is CTP6, which contains ASP.NET 5 Beta 3 bits.
