### ISSUE TITLE
wwwroot and source control

### ISSUE THREAD

**Issue by flipchart** [aspnet/Home#428]
Originally posted on aspnet/Mvc#2300

It has been recommended that static assets (e.g. css files) should be directly placed in the wwwroot folder, whereas "code" files (e.g. less files) should be placed outside the directory and a build processes (e.g. Grunt) should be used to place the generated files into the wwwroot folder (i.e. assets/foo.less -> wwwroot/foo.css). 

This means that the output of e.g. less files are mixed in with "static" e.g. css files manually placed in the wwwroot folder. This makes source control difficult, as the developer needs to now do one or more of the following:

1. check in the whole of the wwwroot folder (excluding the bin folder) which includes the generated files
2. set up ignore filters for the generated files (either on a file by file basis, or by placing them into special folders and ignoring those folders)
3. don't put any static assets into wwwroot, and instead copy those assets to wwwroot when building the other assets

1 is not ideal as these are generated files, and although we've probably been doing it for a while (due to Web Essentials auto compiling less files) it's not correct
2 is not ideal as the manual work involved can become onerous, or assets can become split up
3 works, but seems to defeat the purpose of wwwroot slightly

What is the recommendation?

**Comment by davidfowl** [comment]
Why do you think 3 defeats the purpose of the wwwroot? The purpose is to separate code from static assets so that the web server doesn't have to have a special black list of extensions to block.

**Comment by flipchart** [comment]
Ok, after re-reading your comment a few times, I now get it. Maybe it's just me, but it felt very much like the purpose was to separate resource files (images, css, js) from code files (less, ts, c#), i.e. the primary benefit was for the developer while working in VS, rather than for the web server as you pointed out. Either I'm missing that bit of information from the blog posts on the topic, or it's not being brought through clearly.

Anyway, thanks very much for the time to answer!
