### ISSUE TITLE
"dnu restore" throwing up error when working with coreclr

### ISSUE THREAD

**Issue by prashantadepu** [aspnet/Home#430]
I am trying to run HelloMvc sample app from dev branch in command prompt. I am running into two issues

1) When I run "dnu restore " command it's throwing up an error below

![dnurestore-error](https://cloud.githubusercontent.com/assets/3866396/6935132/bb4215a6-d805-11e4-941f-d3832beb98be.jpg)

Restore failed
Unable to find an entry point named 'CreateSemaphore' in DLL 'api-ms-win-core-kernel32-legacy-l1-1-0.dll'.

Its working fine with full clr and also with other core clr I have on my machine (dnx-coreclr-win-x86.1.0.0-beta5-11378)

2) When I try running application in browser with full desktop clr, it throws up an error

![mvcerror-fullclr](https://cloud.githubusercontent.com/assets/3866396/6935208/ff4175b6-d806-11e4-9907-0646569f714e.jpg)

Am I missing something here?

**Comment by davidfowl** [comment]
What OS?

**Comment by prashantadepu** [comment]
I am working on Windows 7

**Comment by victorhurdugaci** [comment]
@prashantadepu bug confirmed. Working with the CLR team to figure out what's wrong and find a fix.

**Comment by jasonwilliams200OK** [comment]
@victorhurdugaci, any updates/workarounds for this?

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
