### ISSUE TITLE
Unit testing, mocks and Context/Response

### ISSUE THREAD

**Issue by CuriousCain** [aspnet/Home#433]
Hi guys, I'm applying TDD to a web API and when mocking a repository for DI, I will always get a null object exception due to Context not being instantiated.

This happens when a response is set in a controller.
How do we go about setting this? As ControllerContext doesn't appear to be available in this version of mvc.

Forgive me if I'm just majorly dropping the ball here.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
