### ISSUE TITLE
Provide Unix Build Instructions + Scripts

### ISSUE THREAD

**Issue by migueldeicaza** [aspnet/Home#437]
Currently the mechanism to install KVM requires me to run some commands that download bits and pieces from the internet.    

ASP.NET needs to have a Unix build setup that would:
- Configure a source checkout for build and installation
- Build the required bits from a pure source checkout
- Install the required bits into the system and any auxiliary scripts

This is the way that most Unix packages are distributed nowadays.   And they have been turned into a set of well established idioms, that go like this:

```
 ./configure [options]
 make
 make install
```

Bonus points if you use GNU autoconf/automake, as it would give you:
- Makefiles with standard targets (https://www.gnu.org/prep/standards/html_node/Makefile-Conventions.html)
- Packaging of the source code suitable for bundling on Unix distributions
- Build scripts suitable for clean reproducible builds, required by both Debian and RPM package managers

**Comment by davidfowl** [comment]
I think we should look into packaging dnvm (Debian and RPM). I'm not convinced me need to do the  

```
./configure
make
make install
```
Pattern for our managed projects. We use a build.sh instead.

**Comment by wholroyd** [comment]
If you're thinking of doing .deb and .rpm files, it would make sense to change how DNX does it's installations today. For example in both Windows and Linux, it's stored in a .dnx folder under the current user's home path.

I don't know of a .deb or .rpm package that has ever installed on a per-user basis, they are all instead installed system wide.

I would imagine that things should get installed to a system wide directory (like the dnvm script and the runtimes), but the choice of active/default should be stored in a home path configuration directory?

**Comment by wholroyd** [comment]
How about something like this? The Docker image builds the .rpm and .deb packages using the current version of the DNVM script as of this posting.

https://github.com/wholroyd/dnvm

**Comment by Daniel15** [comment]
> Both packages install DNVM at a system level into /usr/local/bin/dnx/

That seems wrong... By definition `/usr/local/` is only for things that were **not** installed via packages. A package should install executables into `/usr/bin/` and architecture-independent files into `/usr/share/`, or everything into a subdirectory of `/opt/`.

**Comment by wholroyd** [comment]
You're right, I'll change it.

**Comment by wholroyd** [comment]
Updated my repo

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
