### ISSUE TITLE
Structure of project.json

### ISSUE THREAD

**Issue by ggrnd0** [aspnet/Home#439]
What is `sources`? https://github.com/aspnet/Home/wiki/Project.json-file#sources

It missed in [project.json ile schema](http://json.schemastore.org/project)

**Comment by davidfowl** [comment]
There's no sources property. Sources is the title of the section in the wiki article.

**Comment by ggrnd0** [comment]
ok, what is it? https://github.com/aspnet/Home/wiki/Project.json-file#list-of-supported-properties-for-sources

I got warning "Deprecated, replaced by content" for "resources" in my project.json

But there is nothing exists about `deprecated resources` and `correct resource` in http://json.schemastore.org/project 

So, there is most correct schema of project.json?

**Comment by davidfowl** [comment]
http://json.schemastore.org/project-1.0.0-beta4

**Comment by ggrnd0** [comment]
Thanks.
