### ISSUE TITLE
Wiki link to project.json schema doesn't reference current schema

### ISSUE THREAD

**Issue by GuardRex** [aspnet/Home#440]
http://json.schemastore.org/project

Line #79: "description": "List of files to exclude from publish output (kpm bundle).",

**Comment by davidfowl** [comment]
http://json.schemastore.org/project-1.0.0-beta4 has the latest changes

**Comment by GuardRex** [comment]
Ah! ... then it's just the link to the schema at:

https://github.com/aspnet/Home/wiki/Project.json-file

... that should be updated.

**Comment by davidfowl** [comment]
Will do. We kept them separate for now just so we don't break older consumers.

**Comment by GuardRex** [comment]
Gosh ... lots of significant deltas between the two files. I know keeping that Wiki link to the schema up-to-date might be a problem for next few months, but I wonder if it isn't a larger problem having newbies (like me) looking at such an old schema when we're jumping in for the first time. I can see that messing folks up.

The Wiki link is under the "Schema" heading at: https://github.com/aspnet/Home/wiki/Project.json-file

Actually, I'll leave this open and let you decide if you want to update the link or not and close this at your discretion. Thx, Luke

**Comment by davidfowl** [comment]
That all depends, if you're using beta3 then it makes sense. The dnx changes aren't even done yet so the question is, what should the wiki represent? Bleeding edge or released? Or should it just point to both schemas.

**Comment by GuardRex** [comment]
Good point ... and there is no way to provide a directory of all stored schema files with schemastore.org? ... then people could look and know (or guess) by filename which one they should be looking at (and it would also save your team having to keep that one link updated)

**Comment by davidfowl** [comment]
Is it easier to read the schema or the wiki?

**Comment by GuardRex** [comment]
Yeah, easier to read the wiki for sure. However, that schema link being the first thing on that page ... and my being newbie ... I clicked to open that schema file and started reading it carefully. That's really not a good idea given the deltas to the latest version for a newbie about to jump in at CTP7.

I guess what you're implying is that the Wiki (or parts of it) might be 'last CTP beta' ... beta3 right now ... and not 'bleeding edge (dev branch) beta' or 'trying to learn for the next CTPx beta' ... beta4 right now.

Maybe the way to go is just to add a note below that link that points to the schemastore JSON page:
```
Visit the <a href="http://schemastore.org/json/">JSON Schema Store</a> and open the latest project-*.json file shown for the latest (dev branch) project.json file schema.
```
That gets bleeding edge folks to the right one and saves your team ever having to think about where that link goes as the dev branch rolls forward. Things are probably going to get out-of-sync again after CTP7 when beta5 changes to that schema occur, and having such a note there would solve this.
