### ISSUE TITLE
samples Home-dev Console works but not finding HelloMvc and HelloWeb. CTP 6

### ISSUE THREAD

**Issue by hubert-associates** [aspnet/Home#442]
Hi,

I recently downloaded everything (few days ago). Compiles fine, and Console Hello runs fine. The HelloMvc is driving me batty, since I compile and run from 2015 CTP 6 and even the debugger starts, and then, tada, chrome starts and brings not HelloMVC but some standard vNext page "Welcome, your vNext application has been successfully started". Well maybe, but not the one in my Visual Studio :-) And the same happens when I do a dnx . web and enter http://localhost:5001/. Where is my HelloMVC? My Vistual Studio thinks everything is fine...

The project.json file contains references to all sorts of versions, and then I have lots of (different) variants now installed with dnvm (four in all now). This is great flexibility perhaps, but how do I get the matching pieces together? I am not getting any errors, it just doesn't start my HelloMvc no matter which "dnvm use" version I switch to. 

Thanks for  a tip, since I would love to figure out how to make the correct parts find each other :-)

**Comment by magohl** [comment]
I suspect you are not seeing anything from MVC because the sample is missing a route.

Look at the sample in the dev branch or try by adding a simple attribute-route to the controller such as [Route("/")]

**Comment by hubert-associates** [comment]
Well this is a lesson not ever to take something for granted :-) even if it has been around since MVC 1.0! I was trying all the default-routes and checked the controller about 10 times but never came across the idea than maybe there are no more default routes at all! I think this may be something that should be added to the demo or at least the documentation. Thanks again!
