### ISSUE TITLE
vNext hosted on Ubuntu can't fetch data from SQL database on Azure

### ISSUE THREAD

**Issue by Junsui** [aspnet/Home#443]
I'm not sure if this is possible at the moment and if I need some additional steps to make this work. 

My vNext app works on both, Windows and Ubuntu. The difference is when I host it on Ubuntu, it doesn't get any data from   SQL database in Azure. My Ubuntu virtual machine is also in Azure. 

I've checked many tutorials and found nothing about accessing SQL db in Azure from vNext apps , but since it works when I host app in IIS, I thought it'll work on Ubuntu too . I'm  quite new to Ubuntu so I'm only guessing what can go wrong. And tinkering with it proved to be dangerous so I don't want to poke things without knowing what I'm aiming at.

Any ideas, suggestions on what can be done or checked or if there are any constraints?

**Comment by jrock2004** [comment]
I believe this is due to mono not supporting SQL clients.

**Comment by Junsui** [comment]
Can that information be checked somehow ? Also, thanks for the input.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
