### ISSUE TITLE
Using Grunt watch with k start

### ISSUE THREAD

**Issue by cwoolum** [aspnet/Home#445]
I am using Grunt to process all of my Typescript and Less files and it would be nice if I could us that in conjunction with watch and livereload while still using k start to serve the site. Has anyone gotten this to work?

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
