### ISSUE TITLE
Support for background services

### ISSUE THREAD

**Issue by Kukkimonsuta** [aspnet/Home#448]
Moved from [dnx#1638](https://github.com/aspnet/dnx/issues/1638)

I'd like to ask whether there will be supoort for background services, meaning an application that doesn't have to run within web server and runs on background without anyone logging into the computer while utilizing the .net core and libraries written as "asp.net vnext class library"?

If there won't be explicit support, what is the recommended approach to run continuous tasks in background?

Thanks

**Comment by Eilon** [comment]
Sure, just write a console app. It won't be able to interact directly with the Windows Service Control Manager (you'd have to PInvoke stuff, presumably), but for just running code, sure.

I recommend trying it to see whether you run into any issues, and report back.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
