### ISSUE TITLE
How to override the compiler with a custom compiler shipped in a NuGet package

### ISSUE THREAD

**Issue by gfraiteur** [aspnet/Home#449]
I would like to integrate PostSharp with DNX. PostSharp needs to post-process the output of the Roslyn compiler.

I'm trying to override the default project compiler by adding this to `project.json`:

```json
 "compiler" : {
        "name" : "C#-PostSharp", 
        "compilerAssembly" : "PostSharp.Dnx",
        "compilerType" : "PostSharp.Dnx.PostSharpProjectCompiler"
    }
```

where PostSharp.Dnx is a NuGet package.

The problem is that the PostSharp.Dnx assembly cannot be found. The LoadContext into which the assembly is loaded is empty, so only the `dnx\bin` directory is being scanned.

How can I use a custom compiler shipped in a NuGet package?

Thank you.

**Comment by davidfowl** [comment]
Just an FYI, this part of the stack is changing heavily right now so expect anything I say in this thread to potentially change.

> The problem is that the PostSharp.Dnx assembly cannot be found. The LoadContext into which the assembly is loaded is empty, so only the dnx\bin directory is being scanned.

Did you add a reference to the nuget package?

Replacing the compiler isn't the right way to go here (somebody using post sharp shouldn't be forced to replace the compiler). 

The closest thing we have that might be what you want is an ICompileModule:

https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc/RazorPreCompileModule.cs#L17

This project has some better examples:

https://github.com/davidfowl/CompileModules

Currently, you need to have code in your project under a special folder to turn this on (and that's what users would do for post sharp). To precompile your razor views, it's a similar process:

https://github.com/aspnet/Entropy/tree/dev/samples/Mvc.Razor.PreCompilation

**Comment by gfraiteur** [comment]
Thank you for your reply. Yes, I added a reference to the NuGet package but I see in the debugger that the LoadContext is empty at that point. I didn't diagnose further.

I will give priority to ICompileModule and report issues.

I hope there will be a way to add compiler modules without having source code in a special directory. It would be great if the NuGet package could self-contain this information. It's our experience that any friction in design-time deployment/installation causes much frustration and results in many support tickets. Yet for an early release it's just fine :)

**Comment by davidfowl** [comment]
@gfraiteur We're looking at that, having them be in nuget packages purely. Though questions like order of operations always come up. It'll be interesting to see if we end with letting you override that with source.

**Comment by gfraiteur** [comment]
For ordering you may find inspiration in PostSharp: http://doc.postsharp.net/aspect-dependencies. It is based on Boolean networks (partial order relationships) and topological sort. We could contribute the code of the dependency resolver.

**Comment by gfraiteur** [comment]
@davidfowl The loading issue was due to a mismatch between platform names (aspnet50 vs dnx451). This is solved. I'm opening other thread for questions/issues with ICompileModule.
