### ISSUE TITLE
What about bundling and minification?

### ISSUE THREAD

**Issue by lucamorelli** [aspnet/Home#45]
Hi,
 I looked around the code, but I don't see a module that handles bundling and minification as in the actual mvc.
 Will be includede in the mvc project?

**Comment by obrienluk** [comment]
Hi.
I currently use bundling to bundle XML files as JSON, I also have a project in my solution that bundles Javascript files extracted from a DLL using assembly.GetManifestResourceNames() and assembly.GetManifestResourceStream().
In both case I have extended the Bundle class (or ScriptBundle) and implemented the IBundleBuilder interface.
I don't think either of these tasks would be possible with OSS like Grunt or Gulp.

I'm also not so sure about the idea of replacing the web.config XML file with JSON, but that's another topic.

**Comment by danroth27** [comment]
See resolution and discussion on https://github.com/aspnet/XRE/issues/238.
