### ISSUE TITLE
ICompileModule: how to resolve project references

### ISSUE THREAD

**Issue by gfraiteur** [aspnet/Home#453]
I'm implementing an `AfterCompile` filter (to run PostSharp after the Roslyn compiler) and I need to pass a list of all incoming assembly references - I need to know their location on disk or in memory.

It seems I can get this information by overriding the compiler (`IProjectCompiler`), but I did not find a way to resolve it with the information I get from `ICompileModule`. Following `context.Compilation.References` does not seem to result in anything useful.

How can I get the list of resolved incoming references in a `ICompileModule`?

**Comment by gfraiteur** [comment]
I can confirm that I was able to integrate PostSharp with ASP.NET v5 by patching DNX. I had to expose the list of `IMetadataReference` to `IAfterCompileContext`:

```
  public interface IAfterCompileContext
    {
        IProjectContext ProjectContext { get; }

        CSharpCompilation Compilation { get; set; }

        Stream AssemblyStream { get; set; }

        Stream SymbolStream { get; set; }

        Stream XmlDocStream { get; set; }

        IList<Diagnostic> Diagnostics { get; }

        IEnumerable<IMetadataReference> References { get; }
    }
```

I'm not sure it respects the intended design. Would it be an acceptable pull request? Or what would be a preferred strategy?

**Comment by tugberkugurlu** [comment]
> How can I get the list of resolved incoming references in a ICompileModule?

As a person who has never tried this and has no idea if this works, you may try to get `ILibraryManager` injected into your `ICompileModule` implementation. Not relevant to your case but here is a sample: https://github.com/aspnet/Mvc/blob/9dc8ecac8af8ed1c97e99d23797c1062a9047793/src/Microsoft.AspNet.Mvc.Razor/Compilation/RoslynCompilationService.cs#L51

I am just guessing that this would work.

**Comment by davidfowl** [comment]
@gfraiteur That would be a great pull request. We're also going to make that not an interface but instaed make it a poco context. class.

**Comment by gfraiteur** [comment]
Solved with pull request https://github.com/aspnet/dnx/pull/1656
