### ISSUE TITLE
Will package versions be specified in global.json?

### ISSUE THREAD

**Issue by ggrnd0** [aspnet/Home#456]
Will package versions be specified in global.json?

**Comment by ggrnd0** [comment]
It is very important feature.

When you set empty version constraint on project dependency it will get top latest version of package of all package sources.
    But global.json can specify solution-wide constraint of package version which will use instead of latest package version.

**Comment by davidfowl** [comment]
We can think about something like this for v2. We aren't quite there yet. Maven has this with parent POMs. It might be good to understand what other package managers do in this space

**Comment by ggrnd0** [comment]
Yes, maven!
I want it all. And variables, and parent/module specification. And <groupId> too!

maven can specify global variables.
    I want it too.

But, global.json package varsion constraints must work implicitly, with out explicit variable definition!!!!!!!!!!!!!!!!!!!!
    It must be one-to-one, project.json package varsion constraints and global.json package varsion constraints! It will be better and simpler than maven (i know maven too bad...).
    Variables can be used to specify all package version to the similar value with glob project selection.
    Dots recognized like path separators: 

* `*` like `\w+`
* `**` like `[\w\.]+`
* `Dnx.Mvc.**` can match "Dnx.Mvc" too.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
