### ISSUE TITLE
Way to stop X.cmd & X file from reaching the bin>output folder on a dnu publish?

### ISSUE THREAD

**Issue by GuardRex** [aspnet/Home#457]
`dnu publish` produces the command files indicated in `project.json`.

Is there a way to instruct the framework to **not** include commands that we setup in `project.json` in the `bin > output` folder? ... perhaps using one of the "exclude" options in the `sources` section of `project.json`?

Attempted using `bundleExclude` and `publishExclude` with `"*.cmd"` and neither works.

I'd like to keep these command files out of that folder because I don't want the commands published (via Web Deploy or manually moved) to the VM where the app will be hosted.

**Comment by davidfowl** [comment]
@GuardRex you can't today but why does that matter? Is it just to keep things clean because it's an iis only site?

**Comment by GuardRex** [comment]
"Yes" on keeping things tidy ... and there might be a security or general risk in the future under some scenario where it might be a good idea not to have these .cmd files in the project on a production server if they are only intended to be run on the dev's local box or on a dev server.

It might be a decent feature if the `dnu publish` could have:

1. a switch like `--nocommand(s)` or `--nocmd(s)`, perhaps with a named list, or
2. if there was a `sources` setting like `publishCommandExclude` with an array of commands, or
3. if something like "COMMAND_NAME.cmd" added to `publishExclude` that the `dnu publish` would recognize means to not let that command go out

...  could keep those files out of `bin > output` and, by extension, keep Web Deploy from kicking them up to the server, too.
