### ISSUE TITLE
ICompileModule: how to know that the build is fully done

### ISSUE THREAD

**Issue by gfraiteur** [aspnet/Home#458]
PostSharp needs to perform its job in a separate process or AppDomain. The best option from a performance point of view is for PostSharp to use a single AppDomain to build all projects in the current application. Then, to save memory, the AppDomain must be unloaded.

How can I know that DNX is done building all assemblies and that the AppDomain can be unloaded?
Is there even a concept of "being done"? It seems that projects are built on demand when assemblies are loaded.

**Comment by davidfowl** [comment]
Unfortunately, that;s just not a scenario we support. AppDomains don't even work on CoreCLR so you might want to change your approach completely here.

**Comment by gfraiteur** [comment]
We use this approach for the same reason that you're using the "preprocess" compilation step: the project contains code that can modify the compilation. The difference is that *any* code can run at build time. So we need to load the output of the compiler in a standalone process/AppDomain, execute transformations, compile back the assembly and unload the process/AppDomain.

At short term the only other option we have is to run PostSharp out-of-process, which is fine feature-wise but will be slower. 

Note that we won't support CoreCLR for a while.
