### ISSUE TITLE
ICompileModule: need all assembly dependencies materialized on disk

### ISSUE THREAD

**Issue by gfraiteur** [aspnet/Home#459]
If PostSharp must run as an external process, it needs all incoming assembly references to be materialized on disk. Actually, the real requirement is to load the dependencies in the external process, so shared memory is also acceptable.

I don't see a good way to do that currently, because a RoslynProjectReference no longer contains the MemoryStream from which the assembly was loaded. It is of course a reasonable choice to dispose the MemoryStream after the assembly has been loaded, to lower the memory footage. However this creates issues for us and I'm looking for a workaround.

One possibility is to look for the Assembly in the AppDomain, take the HMODULE, which is the memory address of the Module, and copy it to disk. However this is cumbersome because the PE module is already mapped, so we would need to parse some PE headers and do some strange things. Even if this would eventually work, it would not be portable.

Another option would be to have some kind of global option level to force materializing assemblies on disk. When this option would be defined, all dependent assemblies (and recursively) would be materialized on disk.

It is not possible to implement this as an ICompileModule because the materialization needs to be done for every dependent project, even those who don't have the ICompileModule. Therefore the solution needs to be implemented at DNX level.

What do you think?

**Comment by davidfowl** [comment]
The dnx isn't going to write anything on disk. However post sharp can definitely do that if it needs to. With the change you're sending to the DNX (adding the ability to get the list of references in the compile module), you'll be able to take that collection and persist it to disk.

This sample is a bit out of date but it shows the idea:

https://github.com/davidfowl/vNextLanguageSupport/blob/ef58972cb99cbe36c902ff9fa8154b63b05a7f60/src/CscSupport/CscProjectReference.cs#L173

**Comment by gfraiteur** [comment]
Than you for your reply.

You're suggesting to call EmitAssembly (EmitReferenceAssembly would not work for PostSharp). This is a viable solution but the performance would be terrible because projects would need to be compiled (emitted) twice or more - once by DNX, once by PostSharp, once by Code Contracts, ... and once by any tool in the chain that still works as an external process.

I definitively agree that intermediate assemblies should not be written to disk during the process of building a project, but once the project is built, having the *option* to materialize the final assembly to disk would help integrating tools that have been designed before ASP.NET v5.

**Comment by davidfowl** [comment]
We're just not going to do that at runtime. Today compile modules run both during runtime compilation and when you produce packages. Having the closure appear on disk when building packages is ok but I would rather the process that needs it trigger it. Implementations of IMetadataProjectReference can be smart and cache what was emitted so subsequent calls are fast (or something to that effect). 

I'd also love to see the actual performance hit before deciding that it's not viable before coming up with another solution that potentially complicates our current design

**Comment by davidfowl** [comment]
BTW I totally get the problem and the reason why you need the closure. We ran into this ourselves when trying to run fxcop (it needs the full closure as well).

**Comment by gfraiteur** [comment]
Okay I implemented EmitAssembly and performance seems good compared to the cost of running PostSharp. We'll have to judge on a real project.

We need to solve the caching of EmitAssembly, as you mentioned, otherwise the cost is O(n^2) on the number of projects.  

However I don't see how caching can be done with the current API without consuming memory. Instead of having `void EmitAssembly(string)` what about having `string EmitAssembly()`, and it would return the full path of the written assembly. This seems easier to cache. The consumer would copy/hardlink the assembly as needed.

**Comment by davidfowl** [comment]
@gfraiteur Agreed. We're still prerelease and we can change stuff :smile: Having use cases like this makes it easier for us to design something that gets used by real people

**Comment by gfraiteur** [comment]
@davidfowl I would like to clean the closure directory when DNX exists. Is there a better way than AppDomain.DomainUnload?

**Comment by gfraiteur** [comment]
I created issue #462 for the clean-up story.
Regarding the `EmitAssembly` optimization, I think it can be solved later when the problem will arise, i.e. when there will be several compiler modules requiring disk images of assemblies.

In the mean time I just want to inform that we are successfully closing our research project that aimed at integrating PostSharp with ASP.NET v5. We'll be waiting for our pull request to be accepted and released before working on the production version of our integration. Special thanks to @davidfowl for his assistance.
