### ISSUE TITLE
ICompileModule: perform custom cleanup when DNX exits

### ISSUE THREAD

**Issue by gfraiteur** [aspnet/Home#462]
What is the best way an `ICompileModule` should perform custom cleanup actions before DNX exits? The use case is to clean the temporary directory containing the disk images of assemblies required by PostSharp.

Currently we can use `AppDomain.Unload` but it is platform-specific.

**Comment by davidfowl** [comment]
AfterCompile not good enough?

**Comment by davidfowl** [comment]
Or is this across several modules instances?

**Comment by gfraiteur** [comment]
Yes, this crosses several modules.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
