### ISSUE TITLE
ASP.NET 5 Worker Application

### ISSUE THREAD

**Issue by tugberkugurlu** [aspnet/Home#465]
What's the recommended story for deploying a worker application written in ASP.NET 5? I am considering:
- A Windows Service which would invoke dnx to run the ASP.NET 5 console application. Not sure how the deployment story would be here.
- Azure Worker Role which again incokes the dnx to run the ASP.NEt 5 console application. Not sure again how the packing and deploying would look like.

**Comment by muratg** [comment]
ASP.NET 5 console applications is the way to go for things like worker type of apps and Azure WebJobs (http://azure.microsoft.com/en-us/documentation/articles/web-sites-create-web-jobs/)  Deployment to WebJobs should be straightforward, though there's no direct solution for Worker Role deployments.

**Comment by easyt** [comment]
Here is a write up of how you can run ASP.NET 5 with static files and MVC 6 in a Windows service: http://taskmatics.com/blog/host-asp-net-in-a-windows-service/

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
