### ISSUE TITLE
Azure Web App and ASP.NET 5 Data Protection keys

### ISSUE THREAD

**Issue by tugberkugurlu** [aspnet/Home#466]
When I run an ASP.NET 5 project under Azure Web Apps, I see this log: 

> Azure Web Sites environment detected. Using 'D:\home\ASP.NET\DataProtection-Keys' as key repository; keys will not be encrypted at rest.”

A few questions:
- It says “keys will not be encrypted at rest”. What does this mean?
- If my Azure Web App runs on multiple instances, are the same keys going to be synced between my instances?
- I can see an ASP.NET folder and a file for data protection keys when I FTP into my Azure Web App. Does this mean that I can deploy here and ASP.NET 5 would pick up automagically?

**Comment by blowdart** [comment]
A few answers.

* Outside of Azure Web Apps, on a Windows OS, we encrypt any keys at rest via DPAPI. Azure Web Apps doesn’t support DPAPI so we can’t encrypt files at rest.

* Keys will be synced between web app instances in this directory.

* You can upload key files into that directory and (as long as they're decryptable) they'll be used, but of course you should be keeping development keys off production machines and vice versa. No crossing the streams.

If you are concerned about at rest encryption on Antares we provide an X509Certificate file for you. Which you can find in the data protection repository, which is where this message came from.

**Comment by tugberkugurlu** [comment]
@blowdart thanks, really helpful!

This is the first time I heard about at rest encryption :smile: So, I don't have enough knowledge to be concerned about it.

> Keys will be synced between web app instances in this directory.

This is really good! However, is it ensured that the keys will not be changed at all? I would be worried if the keys are changed and the application suddenly starts not being able to read the cookies, tokens, etc. generated by the old keys.

> You can upload key files into that directory and (as long as they're decryptable) they'll be used.

How do we generate this keys file? Is there a sample?

**Comment by blowdart** [comment]
You don't generate it yourself, Data Protection does it for you. In fact it's individual files per key, which means no changes, unless you go in and edit them yourself. We don't protect against that.

**Comment by naziml** [comment]
You can read more about this on http://blogs.msdn.com/b/webdev/archive/2012/10/23/cryptographic-improvements-in-asp-net-4-5-pt-2.aspx. Look at the DataProtector section. Long story short, DPAPI will protect your keys now … but DPAPI specific to an account on a local machine. So if you have a web farm, then this won’t work. In that case you can change your configuration back to using the crypto stack in ASP.NET 4 and lower *or* you can override the Protect/UnProtect methods and use something else completely, eg: key from a cert. Azure WebApps support you uploading a cert and using it to do crypto work: http://azure.microsoft.com/blog/2014/10/27/using-certificates-in-azure-websites-applications/

**Comment by tugberkugurlu** [comment]
> You don't generate it yourself, Data Protection does it for you.

I guess I am misunderstand this new concept. I was thinking this as something which is similar to machine key we have in old/current ASP.NET and a similar approach explained [here](http://blogs.technet.com/b/pstips/archive/2014/08/07/get-and-set-the-machinekeys-in-machine-config.aspx) would allow us to generate a key and use it in a web farm scenario. Hence my "How do we generate this keys file?" question (maybe I worded it wrongly).

**Comment by tugberkugurlu** [comment]
@naziml very helpful, thanks!

**Comment by blowdart** [comment]
OK so firstly the articles that Nazim points to no longer apply. 

Originally data protection was meant for ephemeral data, viewstate and the like, but everyone decided to use it for persisted data and we got into a horrible mess. So we rewrote the data protection stack to provide cross platform, easily balanced, web farm happy, key rotating goodness. machine key and dpapi are too limited for modern cloud apps. 

It's just we haven't, like most of v5, documented it yet.

When you initialise data protection for the first time it will create its own key, and will rotate this key for you. Depending on your hosting configuration we will persist the keys in locations we know are safe, and try to protect them the best way we can for the platform 

So, for IIS on Windows, DPAPI to protect keys and registry for storage. For Azure Web Apps the special key directory, but no DPAPI as it doesn't roam.

We then give you the ability to override. You can protect the generated keys with an X509 cert you put on every machine. You can have your key store in blob storage. We don't care, it's all overridable. There are interfaces for everything, although I'd strongly suggest not overriding the actual protectors.

I suggest ploughing through the DataProtection repository for now.

**Comment by GrabYourPitchforks** [comment]
FWIW, the team has all of the documentation written. It just needs to be converted to a web-appropriate form and posted.

**Comment by blowdart** [comment]
In the one note?I'll push Dan next week

Sent from my mobile telephonic communications system. Please excuse any terseness or spelling mistakes.
________________________________

**Comment by blowdart** [comment]
I'll push for web documentation over the next couple of weeks, and try to move them up the importance order :)

**Comment by tugberkugurlu** [comment]
docs would be awesome!

**Comment by GrabYourPitchforks** [comment]
@tugberkugurlu To your earlier question re: encryption at rest, consider ASP.NET 4's system where &lt;machineKey&gt; is stored in Web.config. If there's a bug in your application or in the ASP.NET framework itself that permits an attacker to read arbitrary files off the hard drive, then he could read Web.config and get at your cryptographic key material. [Protected config](https://msdn.microsoft.com/en-us/library/dtkwfdky%28v=vs.140%29.aspx) offers a good mitigation for this, but the unfortunate truth is that very few web developers bother to encrypt sensitive parts of the config files.

To address this, the ASP.NET 5 DataProtection system tries to encrypt keys automatically before persisting them on the hard drive. As @blowdart mentioned, when you own your own machine and you're running IIS we use [Windows DPAPI](https://msdn.microsoft.com/en-us/library/ms995355.aspx), so if somebody does get a hold of the files containing your encryption keys the data will be scrambled and unusable. Azure Web Sites doesn't yet offer such a facility, so the key files exist on the filesystem unencrypted. This isn't a truly terrible thing - it's no worse than ASP.NET 4's &lt;machineKey&gt; sitting around unencrypted. But it's certainly a practice we're trying to get away from, and we're brainstorming ways we can make this scenario just work automatically in Azure Web Sites environments.

In the meantime, if you create and deploy an X.509 certificate to your environment, you can configure the system to encrypt keys using that certificate. Once published the documentation will contain instructions for enabling this. I've also separately been working on a sample which uses Azure Key Vault to protect these keys, so expect that to be available at some point.

Hope this helps!

**Comment by SimonOrdo** [comment]
So, if I'm understanding correctly, for a scenario where a web farm is deployed with multiple app servers, in order for something like "anti forgery tokens" to match across instances, I need to install the same X.509 cert on all machines?  

This replaces the process we used to perform with matching machinekey elements in web.config?  Or is there a different mechanism for that?

**Comment by blowdart** [comment]
No. You need to first set a constant application name, then configure the data protection key ring to live on a shared location such as a network share, then, optionally (but a very good idea) protect the keyring with a certificate that is on every server. Or, if the servers are in AD you can use DPAPI-NG and let the keys protecting the keyring flow via AD. 

https://docs.asp.net/en/latest/security/data-protection/configuration/overview.html has examples of how to configure shared keyrings.

**Comment by SimonOrdo** [comment]
(thanks for the reply!)

I see.  So...

configure.SetApplicationName("Appname");
configure.PersistKeysToFileSystem("network share directory");

And it should basically work?  Does that mean the app functioning properly is then tied to a network share being available?

**Comment by GrabYourPitchforks** [comment]
@SimonOrdo - those two lines are pretty much all you need. If you additionally want to encrypt the keys at rest per Barry's suggestion, then you'll need to install some common X.509 cert across all machines in your cluster and call `ProtectKeysWithCertificate` (or use DPAPI-NG, etc.).

The network share should be available for the app to function correctly, but the DataProtection framework can tolerate intermittent outages. For starters, the DataProtection APIs only query the network share at first API call and then once every 24 hours or so thereafter. If the network happens to be unavailable during one of these queries, you may see exceptions thrown by the `Protect` and `Unprotect` APIs. (Whether an exception is thrown depends on a few factors, including the state of the local in-memory key cache and the amount of load the server is under.) These errors should disappear when the network share comes back up.

**Comment by SimonOrdo** [comment]
@GrabYourPitchforks @blowdart 
Thank you for the info and taking the time!

**Comment by ealsur** [comment]
Sorry to get in this thread but for Azure Web Apps, do I have to explicit the FileSystem route like:

    services.AddDataProtection();
    services.ConfigureDataProtection(configure =>
    {
    	configure.SetApplicationName("myApp");
    	configure.PersistKeysToFileSystem(new System.IO.DirectoryInfo(@"%HOME%\ASP.NET\DataProtection-Keys"));
    });

Or is it detected by default and I just need to define the Application Name?

**Comment by TheRubble** [comment]
Hi, so what's best practice for cross platform when deploying into a docker container? A shared location isn't available as the application is cross platform. Should I create an X509 certificate and access it from the disk of each install?

**Comment by roly445** [comment]
I second @TheRubble.

What happens if a network share isn't a viable option, like running a web app in multiple different providers, we used to just set the machine key and it would work.  What do we do now?

**Comment by SimonOrdo** [comment]
@roly445 , @TheRubble   This thread may have some additional information that might help you along:  http://stackoverflow.com/questions/34319802/mvc-6-webfarm-the-antiforgery-token-could-not-be-decrypted

Of particular interest may be the discussion in the comments of the accepted answer.

**Comment by roly445** [comment]
@SimonOrdo Thanks for that, not sure if I like the solution though as it seems a bit of a hack around the system.  By that I mean creating the key every X days and uploading it to the machines.

**Comment by SimonOrdo** [comment]
@roly445 Yea, definitely.  But if you make the expiration 1 hojillion days, then it seems to effectively be the same as specifying a static key in a machine key.

**Comment by roly445** [comment]
@SimonOrdo I get that and it's the right that I'm probably going to do it for now, it just doesn't feel right.

**Comment by SimonOrdo** [comment]
@roly445 Yeah, it's definitely stinky.  To me it feels like this feature redesign was over-engineered and failed to take into account this simple non-connected scenario.

**Comment by GuardRex** [comment]
Before you do anything tooooo scary :skull: ("make the expiration 1 hojillion days"), check out these DP repo links. You'll find some nice options there, such as how to use Azure Blob Storage to persist the key ring.

I personally use replacement `IXmlRepository`, `IXmlEncryptor`, and `IXmlDecryptor` so I can use Azure Table Storage to persist the key ring across servers and use Azure Key Vault without certificates on individual machines. These are definitely **NOT** recommended approaches, as they are dangerous, but you can implement your own logic if you don't like what's in the box.

https://github.com/aspnet/DataProtection/issues/92
https://github.com/aspnet/DataProtection/issues/107
https://github.com/aspnet/DataProtection/issues/115

**Comment by roly445** [comment]
Thanks @GuardRex but we not hosted on azure right now. Just on a couple of VMs.

**Comment by TheRubble** [comment]
Hi, I've implemented an IXMLRespository and backed it into SQL Server with obvious encryption etc. taken into account. This is working across four containers.

**Comment by smbecker** [comment]
@TheRubble, can to share that implementation? That would basically cover [aspnet/DataProtection#37](https://github.com/aspnet/DataProtection/issues/37).

**Comment by joplaal** [comment]
For those running an Azure Web Site, it seems there is an important issue if you are using Deployment slots. In that scenario, the folder where the keys are stored, is not shared between the slots, so every time you swap the slots, the keys are different. You'll end with two set of keys, which is not suitable for "persistent" uses of DatapPotection, such email tokens, etc.. The folder seems to be shared between several instances, but not between slots.

So it seems a we need to use something like https://github.com/GrabYourPitchforks/DataProtection.Azure/tree/dev as described at this issue https://github.com/aspnet/DataProtection/issues/92

It seems to me that this is a quite common scenario, so a more "official/out of the box" solution would be needed.

**Comment by sevenzsu** [comment]
The old machinekey approach is much easier for deployment automation and not subject to single point failure(comparing to network drive). Is it possible to add an option to use a pre-generated key in local config file?

**Comment by blowdart** [comment]
We aren't planning to add a static option due to massive security concerns.

**Comment by SimonOrdo** [comment]
A "static" pre-generated option is already functionally available.  You can generate the file in the development environment and just copy it across the machines.  i'm sure it's unsupported, but it works.  We have a multi-machine on-premise deployment scenario with no shared disks.

I guess one decent option for our situation would be a custom IXMLRespository using SQL server as a store, as mentioned by @TheRubble , but we haven't gone the route of implementing it yet (more pressing dev priorities).  

It does seem like SQL server store might be a good candidate for a core API feature or at least a public example as per #37.  We have a supported SQL store for identity, so perhaps it's reasonable to have it for this feature as well.

**Comment by sevenzsu** [comment]
@SimonOrdo, so you basically create a keyring with an active key that has a very long expiration date and deploy it to all VMs? I agreed that a custom IXMLRepository use db as storage store is a better solution.
Questions: What core features in asp.net core/.net core use DPApi internally? I believe CSRF is one of those. How about Identity 3.0?

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.

**Comment by AbishekMahesh** [comment]
@TheRubble  Hey I know it has been a while, but did you ever share that implementation, that is exactly what I'm trying to do and finding much difficulty.
