### ISSUE TITLE
E-mail (SMTP) API for CoreCLR yet? If not, options??

### ISSUE THREAD

**Issue by GuardRex** [aspnet/Home#467]
Back in January, @Eilon [commented](http://stackoverflow.com/questions/28036820/sending-mail-with-asp-net-vnext/28046980#28046980) that CoreCLR didn't expose any E-mail capabilities (e.g., I don't see `System.Net.Mail` at [MyGet](https://www.myget.org/gallery/aspnetvnext))? Take home message: `dnx50` can take on `System.Net.Mail`, but `dnxcore50` can't.

Is there **any** way to coerce `System.Net.Mail` into a CoreCLR app?
If not, that also means that I couldn't do something like add in `Interop.CDO`, correct?
How about using [TcpClient](http://stackoverflow.com/a/4094351) (or something like that) to an SMTP relay server?
Is there anything built-in to WS2012 that I can hook that would forward the mail to my relay server?
Could I hook into an install of hMailServer across an Azure VNET to send mail (i.e., the mail server would be on another VM)?
If these would all be dead ends, is the only option to consume some kind of external E-mail service?

**Comment by danieltharris** [comment]
Did you get your answer in the end?

**Comment by GuardRex** [comment]
Not from the team, but after looking around the Net, it seems the way to do this is via `TcpClient`. It's in the `System.Net.Sockets` namespace and available in CoreCLR. There are a ton of references online about how to code SMTP communication directly with mail servers at a low, command level using `TcpClient`. For example, [this one on SO](http://stackoverflow.com/questions/6270028/connecting-to-smtp-live-com-with-the-tcpclient-class).

I'm planning on asking the guys today on the Community Standup for any info on `System.Net.Mail` for CoreCLR. I just have a gut feeling that they don't know when they'll get around to it ... they seem very, very busy frying bigger fish right now.

When I get a working code sample, I'll add it to this issue. I hope to get into it this afternoon.

**Comment by Eilon** [comment]
Please file a bug on https://github.com/dotnet/corefx - that's where the CoreFX libraries are. This type of library API wouldn't be ASP.NET-specific anyway.

**Comment by GuardRex** [comment]
Thanks @Eilon. I've posted a UserVoice request for this: [Please vote for it here](https://aspnet.uservoice.com/forums/252111-asp-net-vnext/suggestions/7648077-corefx-should-include-system-net-mail) if you are in favor of having System.Net.Mail in CoreFX.

**Comment by GuardRex** [comment]
I put a little sample SMTP port 25 code for talking to a mail server on the network over at https://github.com/dotnet/corefx/issues/1006.

**Comment by jstedfast** [comment]
Another option for those needing System.Net.Mail functionality is to use [MailKit](https://github.com/jstedfast/MailKit) instead.

One thing that developers may be interested in is that because the MimeKit library that MailKit uses supports generating DKIM signatures, it's possible to start sending mail with DKIM-Signatures which is becoming more and more important for getting past spam filters.

If you run into any issues, feel free to report problems to the [MimeKit](https://github.com/jstedfast/MimeKit) and [MailKit](https://github.com/jstedfast/MailKit) issue trackers and I will do my best to fix them as quickly as possible.
