### ISSUE TITLE
IDE on Macs

### ISSUE THREAD

**Issue by jrock2004** [aspnet/Home#471]
Sorry I know this is not an issue, but on my mac and being new to the MVC6 world, is there an IDE that works on mac? I was looking at xamarin studio but it does not support the new project types yet. Thanks

**Comment by david-martyn-ford** [comment]
The closest thing you can get to an IDE on Mac at the moment is Omnisharp.
http://www.omnisharp.net/

**Comment by Eilon** [comment]
Yup, OmniSharp is the way to go. Works great on Windows too.

**Comment by jrock2004** [comment]
Thanks
