### ISSUE TITLE
Memory/EventHandler leak

### ISSUE THREAD

**Issue by yvesgoeleven** [aspnet/Home#472]
Hi,

I am seeing a memory leak in aspnet 5, which is most likely due to an eventhandler not being unsubscribed, it is easy to reproduce:

File new project & start from 'ASP.NET 5 Preview Starter web'. Hit F5 to load the site in IISExpress and then start refreshing the home page. You will see the memory increase until it hits an out of memory exception.

I took a little bit of time to analyze a memory dump using windbg, There seem to be far to many objects of these types: 

6f9303ec   464152      5569824 System.Threading.Overlapped
6f910870   464157      5569884 System.Threading.Tasks.TaskCompletionSource`1[[System.Int32, mscorlib]]
6ecdf970   464150      9283000 System.Net.SafeNativeOverlapped
6f913008   462994     11111856 System.Collections.Generic.List`1[[System.ArraySegment`1[[System.Byte, mscorlib]], mscorlib]]
6f950d2c   464012     13205596 System.Object[]
6f954a2c   481553     13651086 System.Byte[]
6eac9fe8   464150     14852800 System.EventHandler`1[[System.Net.Sockets.SocketAsyncEventArgs, System]]
6f92fe5c   464152     14852864 System.Threading.IOCompletionCallback
6f92f364   464170     14853440 System.Threading.ContextCallback
6ecfe4f0   462992     20373296 System.Net.WSABuffer[]
6f8fd980   464937     20457228 System.Threading.Tasks.Task`1[[System.Int32, mscorlib]]
6f9132a0   462996     27817776 System.ArraySegment`1[[System.Byte, mscorlib]][]
6f51aab4   467510     29920640 System.Threading.OverlappedData
6f92ecec   928389     33422004 System.Runtime.Remoting.Messaging.LogicalCallContext
6f94ea40   928399     40849556 System.Threading.ExecutionContext
6f9536c8   928523     48283196 System.Collections.Hashtable
6f9537b8   928527     83209584 System.Collections.Hashtable+bucket[]
6ed086bc   464151    120679260 System.Net.Sockets.SocketAsyncEventArgs

My gutfeeling says it is related to the eventhandler<System.Net.Sockets.SocketAsyncEventArgs> not being unsubscribed, most likely related to an async task not completing as the gcroot of these instances point to an 'async pinned handle', but I haven't taken the time to investigate much further.

!gcroot 4bb61678
HandleTable:
    04dd607c (async pinned handle)
    -> 4a9b002c System.Threading.OverlappedData
    -> 410a1618 System.Threading.IOCompletionCallback
    -> 410a14a0 System.Net.Sockets.SocketAsyncEventArgs
    -> 4bb61678 System.EventHandler`1[[System.Net.Sockets.SocketAsyncEventArgs, System]]

If you can't reproduce it, and would like to have the memory dump, let me know we can figure out a way to get it to you (1GB in size)

**Comment by eqbalsajadi** [comment]
Hi yvesgoeleven,

I have exactly same problem do you know how to solve it?

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
