### ISSUE TITLE
Community Standup 4/21 10am PST rescheduled?

### ISSUE THREAD

**Issue by GuardRex** [aspnet/Home#473]
I guess the Community Standup was cancelled today???? According to http://www.asp.net/vnext, it was going down at 4/21 10am PST. No one is responding to Tweets, and there are no posts anywhere that it was cancelled. I don't care if you move it or whatever, but sitting here for 30 minutes trying to figure out what's going on is frustrating and a waste of my time.

**Comment by Eilon** [comment]
Sorry about that!

@DamianEdwards is like 50 time zones away right now, maybe it was supposed to be cancelled? jongalloway?

**Comment by Eilon** [comment]
Eh, @jongalloway

**Comment by jongalloway** [comment]
Right, @DamianEdwards is in NZ and I'm booked with Build demos and @shanselman is saving the world from mutant zombie invasion.
