### ISSUE TITLE
Has path handling to a config file changed?

### ISSUE THREAD

**Issue by GuardRex** [aspnet/Home#474]
This was working a while back for the path to a config file in `Startup.cs`:
```
config = new Configuration().AddJsonFile("config.json");
```
I think referencing the path that way stopped working at some point, so I hard-coded a path there. Now that I'm publishing to the server, going back-and-forth between two hard-coded paths isn't going to be cool.

What's the proper way to set that path so that it will work locally and on the server?

**Comment by MikeSchlichting** [comment]
This line of code will work when you are running locally or on the server:

Configuration = new Configuration().AddJsonFile("config.json").AddEnvironmentVariables();

When running locally config.json will be used, when running on the server AddEnvironmentVariables() will override any config.json values with matching entries from Azure.  From where in Azure do these variables come from? You set them in your Web App settings in the azure portal under Settings\Application Settings\App settings and Connection strings.  

![untitled](https://cloud.githubusercontent.com/assets/5239042/7266174/7ebad9be-e85a-11e4-8b22-bc03ed721dee.png)

**Comment by GuardRex** [comment]
This is running in IIS 8 on a WS2012 VM.

**Comment by GuardRex** [comment]
There is an Application Settings area in IIS, but I was wondering if the path itself could be set so that the `config.json` is found locally. Since it's in the same folder as `Startup.cs`, I would have thought that a relative path would work there ... and I think it used to work that way a week or so ago. Otherwise, I will use the App Settings in IIS as you recommend.

**Comment by GuardRex** [comment]
The config filepath was causing the app to fail on the server. If I can't reference a project-based `config.json` file with a relative path, i.e.,
```
config = new Configuration().AddJsonFile("config.json");
```
How should that be done?
