### ISSUE TITLE
what is timeline to officially support package signing

### ISSUE THREAD

**Issue by GitHubSachin** [aspnet/Home#475]
Hi team,
What is anticipated release timeline when nugget package signature feature will be supported? Is that work still in progress?

**Comment by yishaigalatzer** [comment]
The work is still in progress, we expect it to become public on nuget.org after Visual Studio 2015 RTM ships. There is no committed timeline yet, we will reassess priorities after RTM.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
