### ISSUE TITLE
Can I rely on Thread.CurrentPricipal under ASP.NET 5

### ISSUE THREAD

**Issue by tugberkugurlu** [aspnet/Home#481]
I have a case where I want to rely on Thread.CurrentPrincipal ([Autofac tenant identification](http://docs.autofac.org/en/latest/advanced/multitenant.html#tenant-identification)). Not ideal but can I rely on Thread.CurrentPrincipal under ASP.NET 5?

**Comment by rhires** [comment]
I'm wondering this myself, since it doesn't seem to be in there anymore. So I would like to know what to use instead...

**Comment by pranavkm** [comment]
cc @Tratcher

**Comment by Tratcher** [comment]
@blowdart

**Comment by blowdart** [comment]
In theory you couldn't rely on it in previous versions, especially with async. So nope. You can't.

**Comment by PinpointTownes** [comment]
Related ticket: https://github.com/aspnet/Security/issues/322

**Comment by GiffenGood** [comment]
@blowdart We have a domain layer that is 9+ years old that we want to use under asp.net 5.  This layer makes use of Thread.CurrentPrincipal.   In version 4.5 we used the approach outlined here:

http://www.asp.net/web-api/overview/security/authentication-and-authorization-in-aspnet-web-api

Is there a strategy you recommend for ensuring the Thread.CurrentPrincipal is set for every request?

**Comment by blowdart** [comment]
@GiffenGood We abandoned this pattern. Whilst you could write some middleware to populate it it may not make it over context switches or async. Instead pass the current identity into your layer as a parameter.

**Comment by GiffenGood** [comment]
@blowdart That is what I thought you would say.  However it is a costly task for us to refactor a large code base,  and especially smarts since setting of Thread.CurrentPrincipal has been done by ASP.Net  for years.  

As to the middleware approach, can you please explain how a context switch or asynch will "loose" the Thread.CurrentPrincipal.  It would seem pretty basic, that for security reasons, this would need to be preserved.

**Comment by blowdart** [comment]
I wouldn't like to speak on behalf of the language designers. However, consider what happens if you mutate the principle in an async thread - those changes would get thrown away. As we're not supporting using Thread.CurrentPrincipal for security decisions the point is moot.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
