### ISSUE TITLE
VS 2015 CTP 6 not resolving references after upgrading to dnvm

### ISSUE THREAD

**Issue by eduaglz** [aspnet/Home#483]
I have a project that used to work well with KRE and the aspnet and aspcore frameworks, but then, after moving to DNVM and the new framework names: "dnx451" & "dnxcore50", my visual studio is not able to resolve most of the references related to ASP.NET:
![image](https://cloud.githubusercontent.com/assets/5376927/7330443/4a51627c-eab4-11e4-98b4-c066b938c191.png)

I can start the website with the "dnx . web" command, but now all of my source files are filled with errors.

Even the provided samples have the same errors.

**Comment by karl-sjogren** [comment]
This was the case with running beta3 on CTP 5 as well, you need to wait for a new CTP of Visual Studio to use the new dnx/dnvm stuff. We can just hope that a new one isn't too far away.
