### ISSUE TITLE
Consider cleaning up stale branches

### ISSUE THREAD

**Issue by Tragetaschen** [aspnet/Home#488]
There are currently a lot of stale branches in each of the aspnet projects that clutter the list on the Github page or when listing with `git branch -a`. It would be great if the merged/closed/forgotten ones would vanish.

**Comment by Eilon** [comment]
I've asked folks to clear out their stale branches, so it should get a bit better today. Thanks!

**Comment by Eilon** [comment]
Cleared out a lot of branches so far, still some more to go.

**Comment by Eilon** [comment]
Closing this issue for now because we've removed most of the dead branches. I'm still working on getting folks to delete any other unneeded branches.

**Comment by Tragetaschen** [comment]
Indeed, it's starting to look well. Thanks!
