### ISSUE TITLE
Authentication error when attempting install via brew on Mac OSX

### ISSUE THREAD

**Issue by petemounce** [aspnet/Home#493]
### Functional impact
Cannot install via home brew

### Minimal repro steps

I have homebrew 0.9.5.
I am following setup instructions [here](https://github.com/aspnet/Home/blob/dev/README.md#os-x)
```shell
brew update
brew tap aspnet/dnvm --verbose
==> Tapping aspnet/dnvm
git clone https://github.com/aspnet/homebrew-dnvm /usr/local/Library/Taps/aspnet/homebrew-dnvm
Cloning into '/usr/local/Library/Taps/aspnet/homebrew-dnvm'...
Username for 'https://github.com': ^C
```

### Expected result
I do not expect the authentication prompt.

### Actual result
I get prompted to authenticate. If I authenticate, this results in
```shell
$ brew tap aspnet/dnvm
==> Tapping aspnet/dnvm
Cloning into '/usr/local/Library/Taps/aspnet/homebrew-dnvm'...
Username for 'https://github.com': petemounce
Password for 'https://petemounce@github.com':
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/aspnet/homebrew-dnvm/'
```

### Further technical details
If I browse to the repo that is being cloned, I get a `404`. Is it private?

Note: I have 2FA turned on for my github.com account.

**Comment by Eilon** [comment]
Use `homebrew-dnx` - we just fixed a bunch of typos in the instructions on https://github.com/aspnet/Home and https://github.com/aspnet/homebrew-dnx.

**Comment by petemounce** [comment]
Thank you, that resolves it.

(Bloody hell, the days of Connect are well and truly dead, aren't they!  :) )
