### ISSUE TITLE
Common dnu restore issue: Unable to locate PROJECT_NAME.dll >= 1.0.0

### ISSUE THREAD

**Issue by GuardRex** [aspnet/Home#494]
I commonly get exceptions reporting that the `PROJECT_NAME.dll` file cannot be found and must delete the contents of the `bin` folder to get `dnu restore` to work properly. Here is the end of output showing the exception.
```json
Writing lock file C:\PATH\PROJECT_NAME\project.lock.json
Restore complete, 1131ms elapsed
Restoring packages for C:\PATH\PROJECT_NAME\bin\Debug\app\project.json
  CACHE https://www.nuget.org/api/v2/FindPackagesById()?Id='PROJECT_NAME'
  CACHE https://www.myget.org/F/aspnetvnext/api/v2/FindPackagesById()?Id='PROJECT_NAME'
  CACHE https://nuget.org/api/v2/FindPackagesById()?Id='PROJECT_NAME'
Unable to locate PROJECT_NAME>= 1.0.0
Writing lock file C:\PATH\PROJECT_NAME\bin\Debug\app\project.lock.json
Restore complete, 6ms elapsed
Restoring packages for C:\PATH\paccharter\bin\output\approot\packages\paccharter\1.0.0\app\project.json
  CACHE https://www.nuget.org/api/v2/FindPackagesById()?Id='PROJECT_NAME'
  CACHE https://www.myget.org/F/aspnetvnext/api/v2/FindPackagesById()?Id='PROJECT_NAME'
  CACHE https://nuget.org/api/v2/FindPackagesById()?Id='PROJECT_NAME'
Unable to locate PROJECT_NAME>= 1.0.0
Writing lock file C:\PATH\PROJECT_NAME\bin\output\approot\packages\PROJECT_NAME\1.0.0\app\project.lock.json
Restore complete, 5ms elapsed
Restoring packages for C:\PATH\PROJECT_NAME\bin\output\approot\packages\PROJECT_NAME\1.0.0\root\project.json
  CACHE https://www.nuget.org/api/v2/FindPackagesById()?Id='PROJECT_NAME'
  CACHE https://www.myget.org/F/aspnetvnext/api/v2/FindPackagesById()?Id='PROJECT_NAME'
  CACHE https://nuget.org/api/v2/FindPackagesById()?Id='PROJECT_NAME'
Unable to locate PROJECT_NAME>= 1.0.0
Writing lock file C:\PATH\PROJECT_NAME\bin\output\approot\packages\PROJECT_NAME\1.0.0\root\project.lock.json
Restore complete, 3ms elapsed
Total time 1434ms
Errors in C:\PATH\PROJECT_NAME\bin\Debug\app\project.json
    Unable to locate PROJECT_NAME>= 1.0.0
Errors in C:\PATH\PROJECT_NAME\bin\output\approot\packages\PROJECT_NAME\1.0.0\app\project.json
    Unable to locate PROJECT_NAME>= 1.0.0
Errors in C:\PATH\PROJECT_NAME\bin\output\approot\packages\PROJECT_NAME\1.0.0\root\project.json
    Unable to locate PROJECT_NAME>= 1.0.0
```

**Comment by GuardRex** [comment]
This is still occurring for VS 2015 RC (of course, since that's just running the command lines behind the scenes) ...
```
Writing lock file C:\MY_PATH\project.lock.json
Restore complete, 6915ms elapsed
Restoring packages for C:\MY_PATH\bin\Debug\app\project.json
  GET https://www.nuget.org/api/v2/FindPackagesById()?Id='PROJECT_NAME'.
  GET https://www.myget.org/F/aspnetvnext/api/v2/FindPackagesById()?Id='PROJECT_NAME'.
  GET https://nuget.org/api/v2/FindPackagesById()?Id='PROJECT_NAME'.
  OK https://www.nuget.org/api/v2/FindPackagesById()?Id='PROJECT_NAME' 299ms
  OK https://nuget.org/api/v2/FindPackagesById()?Id='PROJECT_NAME' 456ms
  OK https://www.myget.org/F/aspnetvnext/api/v2/FindPackagesById()?Id='PROJECT_NAME' 522ms
Unable to locate PROJECT_NAME>= 1.0.0
Writing lock file C:\MY_PATH\bin\Debug\app\project.lock.json
Restore complete, 549ms elapsed
Restoring packages for C:\MY_PATH\bin\output\approot\packages\PROJECT_NAME\1.0.0\app\project.json
  CACHE https://www.nuget.org/api/v2/FindPackagesById()?Id='PROJECT_NAME'
  CACHE https://www.myget.org/F/aspnetvnext/api/v2/FindPackagesById()?Id='PROJECT_NAME'
  CACHE https://nuget.org/api/v2/FindPackagesById()?Id='PROJECT_NAME'
Unable to locate PROJECT_NAME>= 1.0.0
Writing lock file C:\MY_PATH\bin\output\approot\packages\PROJECT_NAME\1.0.0\app\project.lock.json
Restore complete, 25ms elapsed
Restoring packages for C:\MY_PATH\bin\output\approot\packages\PROJECT_NAME\1.0.0\root\project.json
  CACHE https://www.nuget.org/api/v2/FindPackagesById()?Id='PROJECT_NAME'
  CACHE https://www.myget.org/F/aspnetvnext/api/v2/FindPackagesById()?Id='PROJECT_NAME'
  CACHE https://nuget.org/api/v2/FindPackagesById()?Id='PROJECT_NAME'
Unable to locate PROJECT_NAME>= 1.0.0
Writing lock file C:\MY_PATH\bin\output\approot\packages\PROJECT_NAME\1.0.0\root\project.lock.json
Restore complete, 28ms elapsed
Restoring packages for C:\MY_PATH\bin\Release\app\project.json
  CACHE https://www.nuget.org/api/v2/FindPackagesById()?Id='PROJECT_NAME'
  CACHE https://www.myget.org/F/aspnetvnext/api/v2/FindPackagesById()?Id='PROJECT_NAME'
  CACHE https://nuget.org/api/v2/FindPackagesById()?Id='PROJECT_NAME'
Unable to locate PROJECT_NAME>= 1.0.0
Writing lock file C:\MY_PATH\bin\Release\app\project.lock.json
Restore complete, 24ms elapsed
Total time 7850ms
Errors in C:\MY_PATH\bin\Debug\app\project.json
    Unable to locate PROJECT_NAME>= 1.0.0
Errors in C:\MY_PATH\bin\output\approot\packages\PROJECT_NAME\1.0.0\app\project.json
    Unable to locate PROJECT_NAME>= 1.0.0
Errors in C:\MY_PATH\bin\output\approot\packages\PROJECT_NAME\1.0.0\root\project.json
    Unable to locate PROJECT_NAME>= 1.0.0
Errors in C:\MY_PATH\bin\Release\app\project.json
    Unable to locate PROJECT_NAME>= 1.0.0
```

**Comment by davidfowl** [comment]
This looks extremely specific to something bogus in your project. Can you create give us some reproducible steps in a new project?

**Comment by GuardRex** [comment]
I think I see why `dnu restore` is choking. Is `dnu publish` [and probably VS build (debug and/or release)] supposed to be adding a dependency for the project name itself and adding a folder to the packages in the name of the application?
```
C:\PATH_TO_PROJECT\bin\output\approot\packages
```
I see this package folder in the name of my project name with a `1.0.0` folder inside.
![Path to packages in approot](https://az285314.vo.msecnd.net/screenshot/capture4.png)

That folder gets put there during a `dnu publsh`, and there are generated `project.json` and `project.lock.json` files with dependency entries in the `Release` folder (and `Debug` when I do a VS build) that I think are choking ...
![Path to packages in approot](https://az285314.vo.msecnd.net/screenshot/capture5.png)
I look inside one of the generated `project.json` files and I see ...
```
{
  "webroot": "wwwroot",
  "version": "1.0.0",
  "dependencies": {
    "paccharter": "1.0.0"
  },
  "commands": {
... continued ...
```
... so you see a dependency section there with the project name and version, and I think it can't restore that.

There is also a generated `project.lock.json` ...
```
{
  "locked": false,
  "version": -9997,
  "targets": {
    "DNXCore,Version=v5.0": {}
  },
  "libraries": {},
  "projectFileDependencyGroups": {
    "": [
      "paccharter >= 1.0.0"
    ],
    "DNXCore,Version=v5.0": []
  }
}
```
... with another reference to a dependency on the project name itself.

When I manually delete the packages folder in the name of the project, manually kill the dependency  lines for the project in these dependency sections of these files, the `dnu restore` goes through normally.

So ... questions are ... is it supposed to be putting a package in there with the project name ... is it supposed to be generating these project-named dependencies in these `project.json`/`project.lock.json` files. If so, shouldn't `dnu restore` be ignoring any dependency that matches the name of the project?

**Comment by dazinator** [comment]
Perhaps worth mentioning but you also hit this problem in the following circumstance:

Suppose your directory structure looks like this:

```
/Src/ProjectA/project.json
/Src/ProjectB/project.json
/Src/ProjectC/project.json
/Src/Solution.sln
```

Then suppose you `cd` into the `Src` directory and do a `dnu restore` - things work as expected.

Now suppose, you are using Visual Studio to build your solution.. it creates an artifacts folder at the same level as the solution file - i.e in the `Src` directory:

```
/Src/ProjectA/project.json
/Src/ProjectB/project.json
/Src/ProjectC/project.json
/Src/Solution.sln
/Src/artifacts/bin/ProjectA/Debug/project.json
/Src/artifacts/bin/ProjectB/Debug/project.json
```

I have noticed that in that artifacts folder, it's placing project.json files. 

Now when you `cd` into the `Src` directory and do a `dnu restore` - this error occurs, because dnu is recursing through all sub directories, and encountering these project.json files in the artifacts folder - and this exception in thrown.

**Comment by codematrix** [comment]
It works when you delete the artifacts folder at the root of the solution. I have a "src", "samples" and "test" folders at the solution folder so I to do dnu restore at the level. I wish there's a way to filter out which directories to restore or better  yet, which ones...

**Comment by GuardRex** [comment]
Does listing the folder in the `exclude` section of `project.json` stop this behavior?

**Comment by codematrix** [comment]
@GuardRex - Just tried, it doesn't work. - This is definitely a work in progress. At least there's a workaround - deleting the artifacts folder does the trick.

**Comment by GuardRex** [comment]
@codematrix There is something for RTM that might solve this if it's still a prob for you when you get to RC2. https://github.com/dotnet/cli/issues/1588
