### ISSUE TITLE
sample HellwMvc & HelloWeb can't executing.

### ISSUE THREAD

**Issue by yanghongjie** [aspnet/Home#497]
![image](https://cloud.githubusercontent.com/assets/2987484/7383990/016f3e52-ee5c-11e4-8df1-83aa18b4cc5b.png)

<code>dnvm upgrade</code>dnvm already executed.

![image](https://cloud.githubusercontent.com/assets/2987484/7383994/1b559550-ee5c-11e4-8341-28d5ec270505.png)

<code>k web</code> can work
![image](https://cloud.githubusercontent.com/assets/2987484/7384345/7ce481a8-ee63-11e4-973c-d0c35a2c295a.png)

**Comment by yanghongjie** [comment]
but ConsoleApp . run success.

**Comment by NTaylorMullen** [comment]
You need to run `dnu restore`

**Comment by yanghongjie** [comment]
hi NTaylorMullen ,I'm already executed dnu restore .
if execut    <code>k web</code>   sample can work ,but k already rename dnx?
so execut <code>dnx . web</code> can't work.

**Comment by NTaylorMullen** [comment]
Ahhh. So it looks like you're utilizing beta3 packages. Problem is dnx is beta4. Therefore your `k web` command is running the old kre runtime. 

Update your `project.json` referrences to utilize beta4 packages. If you don't already have a feed available for the beta4 packages (they aren't on nuget.org) you can add: `https://www.myget.org/F/aspnetrelease/api/v2`

**Comment by yanghongjie** [comment]
Yes, so that really it. At the same time I find an article
http://chris.59north.com/post/Getting-the-ASPNET-5-samples-to-work-on-Windows-with-the-new-dnvm
