### ISSUE TITLE
System.IO.EndOfStreamException when building with latest DNVM and Mono 4.0.1

### ISSUE THREAD

**Issue by miguellira** [aspnet/Home#498]
Running into a `System.IO.EndOfStreamException` when building the latest sample ConsoleApp using the latest `DNVM` and the recently released `Mono 4.0.1`.

```shell
Miguels-MBP:~ miguellira$ dnvm list

Active Version              Runtime Arch Location             Alias
------ -------              ------- ---- --------             -----
  *    1.0.0-beta5-11649    mono         ~/.dnx/runtimes      default
```
```shell
Mono JIT compiler version 4.0.1 (tarball Mon Apr 27 01:00:48 PDT 2015)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           normal
	SIGSEGV:       altstack
	Notification:  kqueue
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	LLVM:          supported, not enabled.
	GC:            sgen
```
```shell
Miguels-MBP:ConsoleApp miguellira$ dnu build

Building ConsoleApp for DNX,Version=v4.5.1
  Using Project dependency ConsoleApp 1.0.0
    Source: /Users/miguellira/Downloads/Home-dev/samples/latest/ConsoleApp/project.json

  Using Assembly dependency framework/mscorlib 4.0.0.0
    Source: /usr/local/Cellar/mono/4.0.1/lib/mono/4.5/mscorlib.dll

  Using Assembly dependency framework/System 4.0.0.0
    Source: /usr/local/Cellar/mono/4.0.1/lib/mono/4.5/System.dll

  Using Assembly dependency framework/System.Core 4.0.0.0
    Source: /usr/local/Cellar/mono/4.0.1/lib/mono/4.5/System.Core.dll

  Using Assembly dependency framework/Microsoft.CSharp 4.0.0.0
    Source: /usr/local/Cellar/mono/4.0.1/lib/mono/4.5/Microsoft.CSharp.dll

System.IO.EndOfStreamException: Failed to read past end of stream.
  at System.IO.BinaryReader.ReadChar () [0x00000] in <filename unknown>:0 
  at Microsoft.CodeAnalysis.CvtResFile.ReadStringOrID (System.IO.BinaryReader fhIn) [0x00000] in <filename unknown>:0 
  at Microsoft.CodeAnalysis.CvtResFile.ReadResFile (System.IO.Stream stream) [0x00000] in <filename unknown>:0 
  at Microsoft.CodeAnalysis.Compilation.MakeWin32ResourceList (System.IO.Stream win32Resources, Microsoft.CodeAnalysis.DiagnosticBag diagnostics) [0x00000] in <filename unknown>:0 
  at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.SetupWin32Resources (Microsoft.CodeAnalysis.CSharp.Emit.PEModuleBuilder moduleBeingBuilt, System.IO.Stream win32Resources, Microsoft.CodeAnalysis.DiagnosticBag diagnostics) [0x00000] in <filename unknown>:0 
  at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.CompileImpl (Microsoft.CodeAnalysis.Emit.CommonPEModuleBuilder moduleBuilder, System.IO.Stream win32Resources, System.IO.Stream xmlDocStream, Boolean generateDebugInfo, Microsoft.CodeAnalysis.DiagnosticBag diagnostics, System.Predicate`1 filterOpt, CancellationToken cancellationToken) [0x00000] in <filename unknown>:0 
  at Microsoft.CodeAnalysis.Compilation.Compile (Microsoft.CodeAnalysis.Emit.CommonPEModuleBuilder moduleBuilder, System.IO.Stream win32Resources, System.IO.Stream xmlDocStream, Boolean generateDebugInfo, Microsoft.CodeAnalysis.DiagnosticBag diagnostics, System.Predicate`1 filterOpt, CancellationToken cancellationToken) [0x00000] in <filename unknown>:0 
  at Microsoft.CodeAnalysis.Compilation.Emit (Microsoft.CodeAnalysis.EmitStreamProvider peStreamProvider, Microsoft.CodeAnalysis.EmitStreamProvider pdbStreamProvider, Microsoft.CodeAnalysis.EmitStreamProvider xmlDocumentationStreamProvider, Microsoft.CodeAnalysis.EmitStreamProvider win32ResourcesStreamProvider, IEnumerable`1 manifestResources, Microsoft.CodeAnalysis.Emit.EmitOptions options, Microsoft.CodeAnalysis.CodeGen.CompilationTestData testData, System.Func`1 getHostDiagnostics, CancellationToken cancellationToken) [0x00000] in <filename unknown>:0 
  at Microsoft.CodeAnalysis.Compilation.Emit (System.IO.Stream peStream, System.IO.Stream pdbStream, System.IO.Stream xmlDocumentationStream, System.IO.Stream win32Resources, IEnumerable`1 manifestResources, Microsoft.CodeAnalysis.Emit.EmitOptions options, Microsoft.CodeAnalysis.CodeGen.CompilationTestData testData, System.Func`1 getHostDiagnostics, CancellationToken cancellationToken) [0x00000] in <filename unknown>:0 
  at Microsoft.CodeAnalysis.Compilation.Emit (System.IO.Stream peStream, System.IO.Stream pdbStream, System.IO.Stream xmlDocumentationStream, System.IO.Stream win32Resources, IEnumerable`1 manifestResources, Microsoft.CodeAnalysis.Emit.EmitOptions options, CancellationToken cancellationToken) [0x00000] in <filename unknown>:0 
  at Microsoft.Framework.Runtime.Roslyn.RoslynProjectReference.EmitAssembly (System.String outputPath) [0x00000] in <filename unknown>:0 
  at Microsoft.Framework.PackageManager.ProjectBuilder.Build (System.String name, System.String outputPath) [0x00000] in <filename unknown>:0 
  at Microsoft.Framework.PackageManager.BuildContext.Build (System.Collections.Generic.List`1 diagnostics) [0x00000] in <filename unknown>:0 
  at Microsoft.Framework.PackageManager.BuildManager.Build () [0x00000] in <filename unknown>:0 
  at Microsoft.Framework.PackageManager.Program+<>c__DisplayClass3_4.<Main>b__8 () [0x00000] in <filename unknown>:0 
  at Microsoft.Framework.Runtime.Common.CommandLine.CommandLineApplication.Execute (System.String[] args) [0x00000] in <filename unknown>:0 
  at Microsoft.Framework.PackageManager.Program.Main (System.String[] args) [0x00000] in <filename unknown>:0 
  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x00000] in <filename unknown>:0 
  at Microsoft.Framework.Runtime.Common.EntryPointExecutor.Execute (System.Reflection.Assembly assembly, System.String[] args, IServiceProvider serviceProvider) [0x00000] in <filename unknown>:0 
  at dnx.host.Bootstrapper.RunAsync (System.Collections.Generic.List`1 args) [0x00000] in <filename unknown>:0 
```

**Comment by suhasj** [comment]
This is known issue and we have notified the Mono team
https://bugzilla.xamarin.com/show_bug.cgi?id=29499

**Comment by miguellira** [comment]
Thanks @suhasj.

Is there a preferred DNVM/Mono combination at the moment? Since the mono Homebrew formula has been updated to 4.0.1 is there a recommended way to get a stable environment to build/run the samples?

**Comment by suhasj** [comment]
/cc @glennc 

I am not sure of this since I have hit issues with both 4.0.1 and 4.1.0

**Comment by javi830810** [comment]
Same issue here, mono 4.0.1 and dnx 4.5.1, please advice

**Comment by davidfowl** [comment]
beta4 + mono 4.0.1 and 4.1 have this issue and there's no known workaround.

**Comment by ThorstenHans** [comment]
Issue also appears in the following combination 
Mono `4.0.1`
dnx and dnu  `1.0.0-beta5-11649`
dnvm `1.0.0-beta5-10371`

**Comment by Jabe** [comment]
:cry:

**Comment by miguellira** [comment]
FWIW...

If you, like me, decided to uninstall Mono 3.x after installing 4.x and will like to get back to a _somewhat_ stable state. You can unlink Mono 4.x and reinstall 3.x by doing the following:

```
brew unlink mono
brew install https://raw.githubusercontent.com/Homebrew/homebrew/68a18ac660515e313cd175c550e3065320dfadec/Library/Formula/mono.rb
```
Unfortunately, all of the issues that exist with running Mono 3.x and the latest DNX will continue, but at least you'll be able to play around with Visual Studio Code on Mac :-)

**Comment by jpack61108** [comment]
Possible workaround? (This is what I did)
1.  clone mono repository, compile and install following the directions here http://www.mono-project.com/docs/compiling-mono/
2.  brew tap aspnet/dnx
3.  brew upgrade
4.  brew install dnvm --without-mono

I had to uninstall everything mono-related that brew installed. But after doing this I was able to run dnu build, dnx . kestrel, etc

**Comment by miguellira** [comment]
@jpack61108 I haven't gone as far as building/running Mono from the latest repo. Curious... Did you have Mono installed prior to this, whether via brew or otherwise? Also, where/how did you discover the --without-mono switch? I haven't seen that documented anywhere. Thanks.

**Comment by jpack61108** [comment]
Yes I did, from brew. I had to remove all of the brew stuff because of all the symlinking that it does. So far it is working as advertised.
James
Sent from Outlook




On Mon, May 4, 2015 at 9:03 PM -0700, "Miguel Lira" <notifications@github.com> wrote:












@jpack61108 I haven't gone as far as building/running Mono from the latest repo. Curious... Did you have Mono installed prior to this, whether via brew or otherwise? Also, where/how did you discover the --without-mono switch? I haven't seen that documented anywhere. Thanks.

**Comment by jpack61108** [comment]
Sorry brew options $FORMULA_NAME will show you the available options for install. I believe it is on the brew wiki.
James

Sent from Outlook




On Mon, May 4, 2015 at 9:06 PM -0700, "Jimmy Pack" <jpack61108@gmail.com> wrote:










Yes I did, from brew. I had to remove all of the brew stuff because of all the symlinking that it does. So far it is working as advertised.
James
Sent from Outlook




On Mon, May 4, 2015 at 9:03 PM -0700, "Miguel Lira" <notifications@github.com> wrote:












@jpack61108 I haven't gone as far as building/running Mono from the latest repo. Curious... Did you have Mono installed prior to this, whether via brew or otherwise? Also, where/how did you discover the --without-mono switch? I haven't seen that documented anywhere. Thanks.

**Comment by miguellira** [comment]
@jpack61108 Thanks for the tip. I'm ready to give this a shot. Quick question, where did you install Mono? The docs suggest /mono but I'd assume you'd run into all sort of permission issues.

**Comment by miguellira** [comment]
@jpack61108 Decided to pull the trigger and installed mono from source at `/Users/miguellira/mono`. Grabbed the latest HelloMvc sample and both beta4 and the latest _(beta5-11682 as of this post)_ have fully functional builds **without** any errors!

I would like to point out, however, that _(as indicated in the [Compiling Mono on Mac OS X](http://www.mono-project.com/docs/compiling-mono/mac/) article)_ in order to install Mono from source you need Mono installed. Also, in order to ensure the new mono is used I added the path to my `~/.bash_profile`:

```
PATH=/Users/miguellira/mono/bin:$PATH
```

**Comment by jpack61108** [comment]
Nice!! I put mine in the same place that brew does. Never really thought about putting it elsewhere

Sent from Outlook




On Mon, May 4, 2015 at 11:08 PM -0700, "Miguel Lira" <notifications@github.com> wrote:












@jpack61108 Decided to pull the trigger and installed mono from source at /Users/miguellira/mono. Grabbed the latest HelloMvc sample and both beta4 and the latest (beta5-11682 as of this post) have fully functional builds without any errors!



I would like to point out, however, that (as indicated in the Compiling Mono on Mac OS X article) in order to install Mono from source you need Mono installed. Also, in order to ensure the new mono is used I added the path to my ~/.bash_profile:

PATH=/Users/miguellira/mono/bin:$PATH

**Comment by jpack61108** [comment]
To work around having to have mono installed to compile mono, before running make, I ran make get-monolite-latest, then make.
James

Sent from Outlook




On Tue, May 5, 2015 at 3:52 AM -0700, "Jimmy Pack" <jpack61108@gmail.com> wrote:










Nice!! I put mine in the same place that brew does. Never really thought about putting it elsewhere

Sent from Outlook




On Mon, May 4, 2015 at 11:08 PM -0700, "Miguel Lira" <notifications@github.com> wrote:












@jpack61108 Decided to pull the trigger and installed mono from source at /Users/miguellira/mono. Grabbed the latest HelloMvc sample and both beta4 and the latest (beta5-11682 as of this post) have fully functional builds without any errors!



I would like to point out, however, that (as indicated in the Compiling Mono on Mac OS X article) in order to install Mono from source you need Mono installed. Also, in order to ensure the new mono is used I added the path to my ~/.bash_profile:

PATH=/Users/miguellira/mono/bin:$PATH

**Comment by jpack61108** [comment]
@miguellira

I am not sure but I thin the way I did it breaks the intellisense for c# in VS Code.

Are you still getting Intellisense for c#?

**Comment by miguellira** [comment]
@jpack61108 Yep, same here. Statement completion only works if I remove the PATH to my 4.1.0 version of Mono and use the 4.0.1 version installed via brew.

I'm guessing this has to do with how Omnisharp within VSCode looks for Mono. My Atom/Omnisharp setup works just fine against Mono 4.1.0. Going to dig around if I come up with a fix I'll post, please do the same.

**Comment by jpack61108** [comment]
@miguellira Will do.

**Comment by jpack61108** [comment]
@miguellira 
Super-Hack but what I am doing until they patch everything is leaving the 4.0.1 on the path and when I want to run the build commands that require the 4.1.0 just enter PATH=/Path/to/mono/4.1.0/:$PATH

Then I can build when I want and still get the awesome intellisense that Omnisharp offers.
Im sure that could probably be automated in some way, I am not that clever yet.

**Comment by miguellira** [comment]
@jpack61108 Yes. That's what I settled into on my Mac. But I've also been playing with vNext on my surface pro will stick with that until another build of VSCode.

**Comment by deevus** [comment]
Here's what did in the interim until this is resolved. I have mono 4.0.1 and 4.1.0 (compiled from git master) both installed in Homebrew.

## `~/.bash_profile`
```
source dnvm.sh
alias dnu="brew switch mono 4.1.0 && dnu"

code () {
  brew switch mono 4.0.1
  if [[ $# = 0 ]]
  then
    open -a "Visual Studio Code"
  else
    [[ $1 = /* ]] && F="$1" || F="$PWD/${1#./}"
    open -a "Visual Studio Code" --args "$F"
  fi
}
```

It's not perfect but it's quick and easy for my use case. You could go further and make sure it resets the brew version after each command but I haven't found I needed to.

**Comment by miguellira** [comment]
@deevus Great tip! Aliasing the dnu command so it first does a brew switch to a custom build of mono takes cares of cleaning up mono and linking up the desired version.

I moved the contents of my mono folder to `/usr/local/Cellar/mono/4.1.0`, updated my `~/.bash_profile` per your suggestion and everything worked as expected!

I then went ahead and upgraded my dnx to the latest (1.0.0-beta5-11722 as of this post) and attempted to do a `dnu restore` and it failed with the following exception:
```
System.DllNotFoundException: /Users/miguellira/mono/lib/libMonoPosixHelper.dylib
```
I grep'ed the contents of my 4.1.0 mono build (compiled from git master) and there are tons of references to it's original build location (`/Users/miguellira/mono`). I think my best bet is to blow it away and rebuild it.

Thanks again for the tip!

**Comment by borgdylan** [comment]
@miguellira Currently mono master has generics issues in the VM.

**Comment by miguellira** [comment]
Thanks @borgdylan. I'm sure I'll run into a lot of issues with Mono as simply getting the samples project to restore/build/run without errors was a challenge.

In fact, the current git master of Mono was not compiling so I had to pull down the last successful tarbal ([d105620](https://jenkins.mono-project.com/view/Packaging-Mono/job/build-source-tarball-mono/1977/)) from their [Jenkins CI server](https://jenkins.mono-project.com/view/Packaging-Mono/job/build-source-tarball-mono/).

Fortunately, at the moment I am able to restore/build/run the samples against the most recent DNX (1.0.0-beta5-11735) and continue to use Visual Studio Code with @deevus `brew switch` tip.

**Comment by javi830810** [comment]
Hey guys just wanted to add, that despite the fact that 'dnu build' doesnt work on Mono. You can move forward only with 'dnu restore' and 'dnx . run', you're loosing the verbose output of dnu build, but at least you can run and play.

**Comment by jensg** [comment]
I have 2 versions of mono compiled from git source mono 4.0.1 and mono 4.1.0; after `Visual Studio Code` is started I  set mono to version 4.1.0 and can execute `dnu build`
Disadvantage: You need a new window of terminal. Whenever PATH had mono version 4.1.0 referenced, code autocompletion does not work. When you set PATH to include mono 4.1.0 after it is started everything is fine.

This is my **~/.bash_profile**

    source dnvm.sh
    MONO401="/Users/jensg/mono/build"
    MONO410="/Users/jensg/mono/git-build"
    PREPATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"

    function code {
      PATH="$MONO401/bin:$PREPATH"
      open -a "Visual Studio Code"
      PATH="$MONO410/bin:$PREPATH"
    }

**Comment by peterblazejewicz** [comment]
> Hey guys just wanted to add, that despite the fact that 'dnu build' doesnt work on Mono. You can move forward only with 'dnu restore' and 'dnx . run', you're loosing the verbose output of dnu build, but at least you can run and play.

This could not apply in all cases, I (and other people) are stuck after `dnx . kestrel`:
https://github.com/aspnet/Home/issues/515

**Comment by borgdylan** [comment]
The latest mono master fixes all issues experienced here.

**Comment by brucerchapman** [comment]
@borgdylan I've got my setup in a mess.  I just tried getting the latest mono with https://homebrew.bintray.com/bottles/mono-4.0.1.yosemite.bottle using homebrew - still no joy.  How do I get the mono master then?

**Comment by jamespack** [comment]
clone the repo.
`git clone https://github.com/mono/mono.git`
Then follow the instructions provided [here](http://www.mono-project.com/docs/compiling-mono/)

**Comment by miguellira** [comment]
@brucerchapman I haven't tried to build from master in awhile but as @jamespack mentions it's pretty straightforward. I did, however, run into issues with earlier mono masters so I grabbed a tarball from their Jenkins server that build successfully. The following details the setup I wound up with: https://github.com/aspnet/Home/issues/508#issuecomment-100231894

Both Mono and vNext are moving targets though, so if you wanna to play with the new bits stick to beta4 but subscribe to the Announcements issues repo. Good luck.

**Comment by brucerchapman** [comment]
@miguellira thanks I did try building but made things worse I think.  This time I'll try in a different path - `/usrs/local/{user}/mono' seems to be the recommended?

**Comment by miguellira** [comment]
@brucerchapman The recommendation is not to place it in `/usr` but you can put in anywhere. I've chosen to place it where the official homebrew version will live. I'll simply delete it and brew install when 4.1 is made official. This is how my setup looks like:

```
Miguels-MBP:mono miguellira$ pwd
/usr/local/Cellar/mono
Miguels-MBP:mono miguellira$ ls
4.0.1	4.1.0
```

**Comment by akoeplinger** [comment]
FYI, the fix to this problem was commited to the mono 4.0 branch, so it should turn up in the next service release: https://github.com/mono/mono/commit/ed1d3ec5260b613849b9af27c9dbcb6566c1637c. If you don't want to jump straight to master, you can just build and install the 4.0 branch instead.

**Comment by miguellira** [comment]
@akoeplinger Do you know if building and running the 4.0 branch of mono will play nice with Visual Studio Code? When I switch to my mono 4.1 build OmniSharp does not start in VSC.

**Comment by akoeplinger** [comment]
@miguellira don't know that sorry, but the 4.0 branch only contains fixes on top of the released 4.0, so if VSCode works with that then I don't see why it wouldn't work with the latest from 4.0 branch.

**Comment by Yantrio** [comment]
@miguellira If you could post an issue over on github.com/omnisharp/omnisharp-roslyn with any details about it not booting on 4.1 then that would be much appreciated :D

**Comment by jamespack** [comment]
@Yantrio I believe it is related to the version of Omnisharp that is used within VSCode.

**Comment by miguellira** [comment]
@Yantrio VSCode always booted, but the OmniSharp Server would not start.

FWIW, I just cloned and built mono from master (currently reading as 4.3.0)
```
Miguels-MBP:MiguelLira.Web miguellira$ mono --version
Mono JIT compiler version 4.3.0 (master/65f9215 Wed May 27 13:17:54 EDT 2015)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           normal
	SIGSEGV:       altstack
	Notification:  kqueue
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	LLVM:          supported, not enabled.
	GC:            sgen
```
Visual Studio Code/OmniSharp works fine, `dnu build` runs without errors. Unfortunately, `CTRL-C` to kill kestrel hangs and throws a `System.NullReferenceException` but apparently that's a known issue and definitely something I can live with.

**Comment by Yantrio** [comment]
There are ways around that  which are quite simple :) we can discuss it on the correct repo :) I'm grabbing git from source to test it now.

**Comment by miguellira** [comment]
@Yantrio I already commented on the Announcements thread when this bug appeared on my end https://github.com/aspnet/Announcements/issues/23#issuecomment-101397426

This bug has been logged several times over, both here and in the KestrelHttpServer repo. I'm sure they're tackling bigger fish right now.

**Comment by salerth** [comment]
For those who already have DNVM/mono installed via Homebrew you can use the 4.0.1-44 release manually without messing about with builds and symlinks (until the main mono brew is upgrade to a fixed version)

`brew edit mono`

Change line 4 & 5 to the following
```
    url "http://download.mono-project.com/sources/mono/mono-4.0.1.44.tar.bz2"
    sha256 "eaf5bd9d19818cb89483b3c9cae2ee3569643fd621560da036f6a49f6b3e3a6f"
```

`brew update mono`

**Comment by jamespack** [comment]
@salerth This is actually the easiest solution. Thanks. Works like a champ!

**Comment by cmattson** [comment]
I submitted a pull request this morning to update Homebrew. It's merged now, so `brew update` away!

Thanks for @salerth for the tip that .44 was working. I'd last tried .43, which still didn't.

**Comment by paullyvenne** [comment]
As far as I know, this bug still exists. I've followed jamespack's instructions many times but it just doesn't resolve the issue (System.IO.EndOfStreamException: Failed to read past end of stream.). I'm thinking there is some issue with that build of mono but I can't be sure, it might also be ASPNET. This issue has been around for along time, so I haven't been able to try out the latest ASPNET and I hear many other users are stuck with this issue (OSX and Linux) as well. Help anyone?

**Comment by paullyvenne** [comment]
Thanks salerth, it worked, I did almost the same thing

* sudo nano /usr/local/Library/Formula/mono.rb
* changed line 4 and 5 to
url "http://download.mono-project.com/sources/mono/mono-4.0.1.44.tar.bz2"
    sha256 "eaf5bd9d19818cb89483b3c9cae2ee3569643fd621560da036f6a49f6b3e3a6f"
* sudo brew upgrade mono

**Comment by andrenventer** [comment]
paullyvenne: I used your method above, but still got the error below:

I removed the node_modules folder
I removed the files bower installed

Then it worked


dnx kestrel
Application started. Press Ctrl+C to shut down.
error   : [Microsoft.AspNet.Diagnostics.ErrorHandlerMiddleware] An unhandled exception has occurred: kqueue() FileSystemWatcher has reached the maximum nunmber of files to watch.
System.IO.IOException: kqueue() FileSystemWatcher has reached the maximum nunmber of files to watch.
  at System.IO.KqueueMonitor.Add (System.String path, Boolean postEvents, System.Collections.Generic.List`1& fds) [0x00000] in <filename unknown>:0 
  at System.IO.KqueueMonitor.Scan (System.String path, Boolean postEvents, System.Collections.Generic.List`1& fds) [0x00000] in <filename unknown>:0 
  at System.IO.KqueueMonitor.Setup () [0x00000] in <filename unknown>:0 
  at System.IO.KqueueMonitor.DoMonitor () [0x00000] in <filename unknown>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x00000] in <filename unknown>:0 ...

**Comment by dougbu** [comment]
Looks like Mono is hitting issues similar to what we've seen when running with Core CLR on Linux (fyi: aspnet/Mvc#3066). Try bumping up the limits `FileSystemWatcher` has likely hit:
```
sudo sh -c "echo 2048 > /proc/sys/fs/inotify/max_user_instances"
sudo sh -c "echo 131072 > /proc/sys/fs/inotify/max_user_watches"
```
Note the above numbers are extreme 16x the defaults.
