### ISSUE TITLE
Installing DVNM on Mac OS X without Homebrew

### ISSUE THREAD

**Issue by weegeekps** [aspnet/Home#500]
Is it possible to install DVNM on Mac OS X without Homebrew?  I ask because since I run Macports on my Mac instead of Homebrew (because Homebrew simply doesn't have the packages I need) I am unable to safely install Homebrew to actually install DVNM.  Installing Homebrew alongside Macports can cause all sorts of major issues that I'd like to avoid.

**Comment by ardacetinkaya** [comment]
I think you can just copy dnvm.sh to /usr/local/dnvm/ and run dnvm.sh from that path. I quess it will work as it is installed with Homebrew.

**Comment by miguellira** [comment]
@ardacetinkaya Looks like @weegeekps actually asked how to install `DNVM` _without_ installing Homebrew.

@weegeekps `DNVM` is the version manager portion of `DNX` so you actually want to install `DNX`: https://github.com/aspnet/dnx. Good luck.

**Comment by breiter** [comment]
I want this too. I think it is basically the same as the Linux instructions. Maybe the documentation just needs to be updated:

`curl -sSL https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.sh | DNX_BRANCH=dev sh && source ~/.dnx/dnvm/dnvm.sh`

That `source` will only affect the current bash session. You then need to modify `~/.bashrc` to include `source ~/.dnx/dnvm/dnvm.sh`. I think this will only work with bash and zsh.

**Comment by lukka** [comment]
@breiter It is not needed to add anything to .bashrc, as the dnvminstall.sh script already appends the source string to your .bash_profile in your home.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
