### ISSUE TITLE
Visual Studio Code uncompatible with frameworks dnx451, dnxcore50

### ISSUE THREAD

**Issue by eduaglz** [aspnet/Home#501]
This might be way too soon since they just released it a couple hours ago, but is the new Visual Studio Code ready to support the new framework naming?

So far this is what I'm getting on my project:
![image](https://cloud.githubusercontent.com/assets/5376927/7399387/345409d2-ee7b-11e4-8814-271e90f8a3d9.png)

**Comment by miguellira** [comment]
@eduaglz You still need to do a `dnu restore` to get those dependencies.

**Comment by eduaglz** [comment]
yeah I already did that and I can run the site with the `dnx . web` command, but the problem is that the editor is not able to resolve the dependencies.

**Comment by miguellira** [comment]
Interesting. I haven't tried the editor on my Windows machine but on the Mac it works just fine. The red squiggles go away as soon as I run `dnu restore`.

**Comment by Eilon** [comment]
I'm like 99% sure it's supposed to work with the "DNX" naming because every demo I've seen used that...

**Comment by eduaglz** [comment]
I just realized that when I try so use `dnu restore` from the editor command palette the only option that I get is `kpm restore` (same problem with `dnx . web` -> `k web`) so I guess the problem is on my machine that is still stuck to the previous naming

**Comment by jrock2004** [comment]
I thought we needed to wait to CTP7 before we can use dnx in VS. Amy I wrong?

**Comment by Eilon** [comment]
@jrock2004 VS2015 RC was just released today.

Info: https://www.visualstudio.com/news/vs2015-vs
Download: https://www.visualstudio.com/en-us/downloads/visual-studio-2015-downloads-vs

**Comment by eduaglz** [comment]
I found the problem, I still had the `.k` folder at `c:\Users\<user>\.k`, plus, my global.json sdk property was pointing to the beta3. Once the folder was removed and the sdk changed to beta4, I restarted the editor and everything started working :)

**Comment by abizden** [comment]
Hey,

I'm having the same problem. When I run the console application with Visual Studio code going consistently underlined the library system. Can you help please?

**Comment by eduaglz** [comment]
@abizden When did you install the new framework? Check if you sitll have the .k folder as I said on the last comment, that solved the error for me

**Comment by abizden** [comment]
.k folder What is it exactly? Can you write in detail please?

**Comment by abizden** [comment]
@eduaglz  thanks.
