### ISSUE TITLE
dnvm upgrade fails

### ISSUE THREAD

**Issue by barranger** [aspnet/Home#502]
If I try and run dnvm upgrade it's failing like so:

```
~$ dnvm upgrade
Determining latest version
Error: Could not find latest version from feed https://nuget.org/api/v2
```

however if I run it with the -u for the unstable feed, it seems to work (although I'm having completely different issues with kestrel).  Is this an known issue?

**Comment by miguellira** [comment]
@barranger the `-u` argument updates the NuGet.config packageSources to include the latest dev builds namely `https://www.myget.org/F/aspnetvnext/api/v2`

What issues are you running into with Kestrel? There is a known issue running the latest dnvm and Mono 4.0.1. See https://github.com/aspnet/Home/issues/498

**Comment by barranger** [comment]
actually I found out what the issue was/is for dnvm upgrade:

it looks like it's not following the redirect that http://nuget.org sends to go to http://www.nuget.org I added the DNX_FEED enviroment variable and was able to get it working.

The issue I was getting with the dev builds was:

TypeLoadException: Could not load type 'Microsoft.Framework.Runtime.ILibraryExport' from assembly 'Microsoft.Framework.Runtime.Interfaces, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'

Hope that helps, I'm just happy to have it working with the non-dev builds

**Comment by darthdeus** [comment]
@barranger What did you change your `DNX_FEED` to? I've just tried the same thing and it doesn't seem to be working

**Comment by barranger** [comment]
@darthdeus changed it to:

export DNX_FEED=https://www.nuget.org/api/v2

**Comment by makenova** [comment]
@barranger thanks, that worked for me.

**Comment by muratg** [comment]
Tracked in: https://github.com/aspnet/dnvm/issues/235
