### ISSUE TITLE
cURL Follow Redirect 301

### ISSUE THREAD

**Issue by YarGnawh** [aspnet/Home#503]
should add ```-L``` it to ```xml="$(curl $url 2>/dev/null)"```

    __dnvm_find_latest() {
        local platform=$1
        local arch=$2

        if [ -z $platform ]; then
            local platform="mono"
        fi

        if ! __dnvm_has "curl"; then
            printf "%b\n" "${Red}$_DNVM_COMMAND_NAME needs curl to proceed. ${RCol}" >&2;
            return 1
        fi
        
        if [[ $platform == "mono" ]]; then
            #dnx-mono
            local packageId="$_DNVM_RUNTIME_PACKAGE_NAME-$platform"
        else
            #dnx-coreclr-linux-x64
            local packageId="$_DNVM_RUNTIME_PACKAGE_NAME-$platform-$(__dnvm_current_os)-$arch"
        fi
        local url="$DNX_ACTIVE_FEED/GetUpdates()?packageIds=%27$packageId%27&versions=%270.0%27&includePrerelease=true&includeAllVersions=false"
        xml="$(curl -L $url 2>/dev/null)"
        echo $xml | grep \<[a-zA-Z]:Version\>* >> /dev/null || return 1
        version="$(echo $xml | sed 's/.*<[a-zA-Z]:Version>\([^<]*\).*/\1/')"
        echo $version
    }

**Comment by YarGnawh** [comment]
The 301 HTTP status is because ```_DNVM_DEFAULT_FEED="https://nuget.org/api/v2"``` gets redirected to ```https://www.nuget.org/api/v2```. Should probably just add in the ```www```

**Comment by darthdeus** [comment]
Adding www in the URL doesn't seem to help

```
$ dnvm install stable
Default stable feed (https://nuget.org/api/v2) is being overridden by the value of the DNX_FEED variable (https://www.nuget.org/api/v2/package/dnx-mono/stable).
Downloading dnx-mono.stable from https://www.nuget.org/api/v2/package/dnx-mono/stable
Download: https://www.nuget.org/api/v2/package/dnx-mono/stable/package/dnx-mono/stable
######################################################################## 100.0%
dnx-mono.stable was not found in repository https://www.nuget.org/api/v2/package/dnx-mono/stable
This is most likely caused by the feed not having the version that you typed. Check that you typed the right version and try again. Other possible causes are the feed doesn't have a DNX of the right name format or some other error caused a 404 on the server.
```

**Comment by YarGnawh** [comment]
try version ```1.0.0-beta4```. 

    ~ dnvm upgrade -f
    Determining latest version
    Latest version is 1.0.0-beta4
    Forcing download by deleting /Users/rayhwang/.dnx/runtimes/dnx-mono.1.0.0-beta4 directory
    Downloading dnx-mono.1.0.0-beta4 from https://www.nuget.org/api/v2
    Download: https://www.nuget.org/api/v2/package/dnx-mono/1.0.0-beta4
    ######################################################################## 100.0%
    Installing to /Users/rayhwang/.dnx/runtimes/dnx-mono.1.0.0-beta4
    Adding /Users/rayhwang/.dnx/runtimes/dnx-mono.1.0.0-beta4/bin to process PATH
    Updating alias 'default' to 'dnx-mono.1.0.0-beta4'```

**Comment by muratg** [comment]
Tracked in https://github.com/aspnet/dnvm/issues/235
