### ISSUE TITLE
Installing DNVM in Windows 7 fails if username contains special characters

### ISSUE THREAD

**Issue by nordbergmikael** [aspnet/Home#509]
On my home PC I use the user account "Yours & Mine". DNVM install fails with:
```
Downloading DNVM.cmd to
Installing DNVM
The string starting:
At line:1 char:139
+ [System.Threading.Thread]::CurrentThread.CurrentCulture = ''; [System.Threadi
ng.Thread]::CurrentThread.CurrentUICulture = '';$CmdPathFile= <<<< 'C:\Users\Yo
urs
is missing the terminator: '.
At line:1 char:153
+ [System.Threading.Thread]::CurrentThread.CurrentCulture = ''; [System.Threadi
ng.Thread]::CurrentThread.CurrentUICulture = '';$CmdPathFile='C:\Users\Yours <<<
<
    + CategoryInfo          : ParserError: (C:\Users\Yours:String) [], ParentCo
   ntainsErrorRecordException
    + FullyQualifiedErrorId : TerminatorExpectedAtEndOfString
```

**Comment by flykoh** [comment]
i have the same issue

**Comment by muratg** [comment]
@flykoh What's the version of dnvm?

**Comment by glennc** [comment]
Closing this one, without more information about what version of dnvm and what the username is it is hard to diagnose. We have had problems with spaces in usernames, and we did some work to fix that. So it is possible if you have an older DNVM that you haven't got that fix. Otherwise if it is still happening on the latest DNVM then you should post back and tell us what the username that is breaking is, see if it is a special character or something that causes the Powershell script to break.

**Comment by glennc** [comment]
We will re-open if we get more info :)

**Comment by darrelo** [comment]
I am experiencing the same issue. My username contains an apostrophe.

@powershell -NoProfile -ExecutionPolicy unrestricted -Command "&{$Branch='dev';iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.ps1'))}"

Using temporary directory: C:\Users\DARREL~1.O'N\AppData\Local\Temp\dnvminstall
Downloading DNVM.ps1 to C:\Users\DARREL~1.O'N\AppData\Local\Temp\dnvminstall\dnvm.ps1
Downloading DNVM.cmd to C:\Users\DARREL~1.O'N\AppData\Local\Temp\dnvminstall\dnvm.cmd
Installing DNVM
Unexpected token 'neil\AppData\Local\Temp\tmp1023.tmp.cmd';& 'C:\Users\DARREL~1
.O'N\AppData\Local\Temp\dnvminstall\dnvm.ps1'' in expression or statement.
At line:1 char:264
+ [System.Threading.Thread]::CurrentThread.CurrentCulture = ''; [System.Threadi
ng.Thread]::CurrentThread.CurrentUICulture = '';$CmdPathFile='C:\Users\Darrel.o
'neil\AppData\Local\Temp\tmp1023.tmp.cmd';& 'C:\Users\DARREL~1.O'N\AppData\Loca
l\Temp\dnvminstall\dnvm.ps1' <<<<  setup
    + CategoryInfo          : ParserError: (neil\AppData\Lo...stall\dnvm.ps1': 
   String) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : UnexpectedToken
