### ISSUE TITLE
Create a separate command for packages

### ISSUE THREAD

**Issue by MikaelSoderstrom** [aspnet/Home#51]
We can use kvm install/upgrade for installing newer versions of KRE, and kpm restore to install packages.

For packages, I would rather see something like this (pm as in "package manager"):

> kpm install
> kpm update
> kpm uninstall
> etc...

This is more like how Node.js works with npm. You have nvm for installing newer versions of node, and npm for installing packages.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
