### ISSUE TITLE
Razor views error help

### ISSUE THREAD

**Issue by Ademord** [aspnet/Home#510]
![error](https://cloud.githubusercontent.com/assets/4501464/7403977/6f683910-eeaa-11e4-8e39-55c9513c6e03.png)

**Comment by mindcrash** [comment]
Check your current dnx environment using `dnvm list`. If there's a beta5 environment being used, upgrade (or actually downgrade) using `dnvm upgrade` to the latest beta4 bits from the feed. Apparently beta5 releases were recently shipped which made Roslyn crash.

**Comment by Ademord** [comment]
I've got beta4 x86 on a windows10 x64.

**Comment by davidfowl** [comment]
Show your project.json and your dnx version.

**Comment by Ademord** [comment]
dnx version:   1.0.0-beta4 clr     x86
project.json:
{
  "dependencies": {
    "Kestrel": "1.0.0-*",
    "Microsoft.AspNet.Mvc": "6.0.0-*",
    "Microsoft.AspNet.Diagnostics": "1.0.0-*",
    "Microsoft.AspNet.StaticFiles": "1.0.0-*",
    "Microsoft.Framework.ConfigurationModel.Json": "1.0.0-*",
    "EntityFramework": "6.1.3",
    "Npgsql": "2.2.5",
    "Npgsql.EntityFramework": "2.2.5",
    "EF6.Commands": "1.1.0-*"
  },
  "commands": {
    "kestrel": "Microsoft.AspNet.Hosting --server Kestrel --server.urls http://localhost:5000",
    "ef": "EF6.Commands"
  },
  "frameworks": {
    "dnx451": {}
  },
  "scripts": {
    "postrestore": "npm install"
  },
  "webroot": "wwwroot"
}

**Comment by davidfowl** [comment]
There's your problem. Look at your `project.lock.json` file. Do not mix beta5 packages with the beta4 dnx

**Comment by Ademord** [comment]
Ok it worked :] Thanks!

**Comment by mykebates** [comment]
Ademord, any chance you could share what exactly you changed? I am having a similar issue and am apparently too dense to catch what exactly should be altered in the project.json. Thanks!

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
