### ISSUE TITLE
VS 2015 RC bugs with .NET 5 projects: My bad or theirs?

### ISSUE THREAD

**Issue by GuardRex** [aspnet/Home#512]
I reported both of these issues through VS's Help > Customer Feedback Options > More Options ... > Submit Bug. I'm merely asking here if I've done anything wrong on my side to cause these problems?

When I opened one of my existing vNext projects (that I had been working on in Brackets), I immediately hit an exception message about not having xxx-clr-xxx-x86-xxx installed. This is a Core x64 app, and I only have Core x64 runtimes in my .dnx folder. When build the project, it does find my Core x64 active runtime and the app compiles just fine. The version info is correct in its search (beta5-11631) ... the -clr- and -x86- are not. 
![Immediate exception on opening a Core CLR project](https://az285314.vo.msecnd.net/screenshot/capture.png)
Next, when I right-click the project name for Properties, I get exceptions in loading on the Application and Debug panels.
![Properties for a vNext app fail to load (if they are supposed to load)](https://az285314.vo.msecnd.net/screenshot/capture2.png)

**Comment by victorhurdugaci** [comment]
I believe this is a known issue. You need to install the CLR runtime even if your project doesn't use it.

**Comment by davidfowl** [comment]
That's right. Tooling depends on it /cc @mayurid @BillHiebert @sayedihashimi

**Comment by GuardRex** [comment]
For the tooling requirement for the CLR runtime, that's cool. I'll roll with it. However, when I installed VS, it installed the beta4 runtimes itself that I didn't have:
```
dnx-clr-win-x64.1.0.0-beta4
dnx-clr-win-x86.1.0.0-beta4
dnx-coreclr-win-x64.1.0.0-beta4
dnx-coreclr-win-x86.1.0.0-beta4
```
I'm only using
```
dnx-coreclr-win-x64-beta5-11631
```
and that's all I had in there when I installed VS.

... but I'm still getting that error when I open VS. I sort of wonder if this is because I installed VS on a non-OS drive on my system. That might explain why it can't find the CLR runtime. If so, I guess that it should be a little smarter about where it looks. Shouldn't it search other drives on the system after it doesn't find the .dnx folder on the drive where VS is installed? [I'll add this comment to my VS bug report.]

As for the 2nd issue, VS support doesn't seem to understand that one. They asked me to merely run `devenv /resetuserdata`, which did nothing. I told them the outcome.

**Comment by GuardRex** [comment]
Gotta back away from my prior comment about not finding the .dnx folder: How could it know that I'm using -beta5-11631 if it didn't find the folder? No, it found the folder. It is assembling the path to look for CLR x86 version of the actual Core CLR x64 beta that's "active."

>You need to install the CLR runtime even if your project doesn't use it.

Which means that every time I get a new Core CLR x64 runtime, I also need to get a new CLR x86 runtime of the same version. Annoying ... but do-able.

Just note though that when the VS team gets around to tooling for getting new runtimes that the user may only specify Core CLR x64 (because that might be all they care to use) and the tooling should automatically get CLR x86, too, if VS needs it.
