### ISSUE TITLE
kmp restore fails on Linux VM

### ISSUE THREAD

**Issue by wisien92** [aspnet/Home#513]
Hi,

I have problem with starting empty MVC vNext project on Linux VM with docker installed - all steps from tutorial how to run sample on docker were finished and I got sample up & running. But right now I am having difficult time in building image for new MVC project.

All I altered in project.json was I changed and added some in "commands":

    "commands": {
        "web": "Microsoft.AspNet.Hosting --server Microsoft.AspNet.Server.WebListener --server.urls http://localhost:5001",
        "kestrel": "Microsoft.AspNet.Hosting --server Kestrel --server.urls http://localhost:5003",
        "gen": "Microsoft.Framework.CodeGeneration",
        "ef":  "EntityFramework.Commands"
    },

And this is my Dockerfile : 

     FROM microsoft/aspnet 
     COPY . /app
     WORKDIR /app
     RUN ["kpm", "restore"] 
     EXPOSE 5003
     ENTRYPOINT ["k", "kestrel"]

And this is what I get when I try to run docker build -t name . 

>apps@ubuntuapp:~/VersaWeb/src/VersaWeb$ docker build -t versa_web .
Sending build context to Docker daemon 24.53 MB
Sending build context to Docker daemon
Step 0 : FROM microsoft/aspnet
 ---> 98b0320569c3
Step 1 : COPY . /app
 ---> a0440643698d
Removing intermediate container 7387a6d93a4b
Step 2 : WORKDIR /app
 ---> Running in 76ab338a5730
 ---> f84961a1f2ae
Removing intermediate container 76ab338a5730
Step 3 : RUN kpm restore
 ---> Running in 5f407a148149
Restoring packages for /app/project.json
  GET https://www.nuget.org/api/v2/FindPackagesById()?Id='EntityFramework.SqlServer'.
  GET https://www.nuget.org/api/v2/FindPackagesById()?Id='EntityFramework.Commands'.
  GET https://www.nuget.org/api/v2/FindPackagesById()?Id='Microsoft.AspNet.Mvc'.
  GET https://www.nuget.org/api/v2/FindPackagesById()?Id='Microsoft.AspNet.Diagnostics'.
  GET https://www.nuget.org/api/v2/FindPackagesById()?Id='Microsoft.AspNet.Diagnostics.Entity'.
  GET https://www.nuget.org/api/v2/FindPackagesById()?Id='Microsoft.AspNet.Identity.EntityFramework'.
  GET https://www.nuget.org/api/v2/FindPackagesById()?Id='Microsoft.AspNet.Security.Cookies'.
  GET https://www.nuget.org/api/v2/FindPackagesById()?Id='Microsoft.AspNet.Server.IIS'.
  GET https://www.nuget.org/api/v2/FindPackagesById()?Id='Microsoft.AspNet.Server.WebListener'.
  GET https://www.nuget.org/api/v2/FindPackagesById()?Id='Microsoft.AspNet.StaticFiles'.
  GET https://www.nuget.org/api/v2/FindPackagesById()?Id='Microsoft.Framework.ConfigurationModel.Json'.
  GET https://www.nuget.org/api/v2/FindPackagesById()?Id='Microsoft.Framework.CodeGenerators.Mvc'.
  GET https://www.nuget.org/api/v2/FindPackagesById()?Id='Microsoft.Framework.Logging'.
  GET https://www.nuget.org/api/v2/FindPackagesById()?Id='Microsoft.Framework.Logging.Console'.
  GET https://www.nuget.org/api/v2/FindPackagesById()?Id='Microsoft.VisualStudio.Web.BrowserLink.Loader'.
Warning: FindPackagesById: EntityFramework.SqlServer
  Error: NameResolutionFailure
  GET https://www.nuget.org/api/v2/FindPackagesById()?Id='EntityFramework.SqlServer'.
Warning: FindPackagesById: EntityFramework.SqlServer
  Error: NameResolutionFailure
  GET https://www.nuget.org/api/v2/FindPackagesById()?Id='EntityFramework.SqlServer'.
Error: FindPackagesById: EntityFramework.SqlServer
  Error: NameResolutionFailure
----------
System.Net.WebException: Error: NameResolutionFailure
  at System.Net.HttpWebRequest.EndGetResponse (IAsyncResult asyncResult) [0x00000] in <filename unknown>:0
  at System.Threading.Tasks.TaskFactory`1[System.Net.WebResponse].InnerInvoke (System.Threading.Tasks.TaskCompletionSource`1 tcs, System.Func`2 endMethod, IAsyncResult l) [0x00000] in <filename unknown>:0
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x00000] in <filename unknown>:0
  at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[System.Net.WebResponse].GetResult () [0x00000] in <filename unknown>:0
  at System.Net.Http.HttpClientHandler+<SendAsync>c__async0.MoveNext () [0x00000] in <filename unknown>:0
(........)
INFO[0007] The command [kpm restore] returned a non-zero code: 1

**Comment by davidfowl** [comment]
nuget.org is currently down.

**Comment by wisien92** [comment]
Ok, thanks for quick response - any ETA on nuget.org be up ?

**Comment by davidfowl** [comment]
Follow them on twitter https://twitter.com/nuget

**Comment by wisien92** [comment]
Again thanks :)

**Comment by stefanrahnev** [comment]
I experience the same issue with the restoration of the following NuGet packages when building a docker image on a Linux VM:

GET https://www.nuget.org/api/v3/index.json
Restoring packages for /app/project.json

GET https://www.nuget.org/api/v3/FindPackagesById()?Id='Microsoft.AspNet.Mvc'.
GET https://www.nuget.org/api/v3/FindPackagesById()?Id='Microsoft.AspNet.Server.Kestrel'.
GET https://www.nuget.org/api/v3/FindPackagesById()?Id='Microsoft.AspNet.IISPlatformHandler'.
GET https://www.nuget.org/api/v3/FindPackagesById()?Id='Microsoft.AspNet.StaticFiles'.
Warning: FindPackagesById: Microsoft.Aspnet.Mvc
Error: NameResolutionFailure
Warning: FindPackagesById: Microsoft.Aspnet.Server.Kestrel
Error: NameResolutionFailure
Warning: FindPackagesById: Microsoft.Aspnet.IISPlatformHandler
Error: NameResolutionFailure
Warning: FindPackagesById: Microsoft.Aspnet.StaticFiles
Error: NameResolutionFailure

Restore failed.
A task was cancelled.

Feed used: 
   https://www.nuget.org/api/v3/index.json
The command 'dnu restore' returned a non-zero code: 1

nuget.org seems to be up and running. Can you advise, @davidfowl? Thanks

**Comment by stefanrahnev** [comment]
I actually made a mistake when pasting the urls. Actually I use the endpoint you specified when getting these errors, i.e.:

GET https://api.nuget.org/v3/index.json
Restoring packages for /app/project.json

GET https://api.nuget.org/v3/index.FindPackagesById()?Id='Microsoft.AspNet.Mvc'.
GET https://api.nuget.org/v3/index.FindPackagesById()?Id='Microsoft.AspNet.Server.Kestrel'.
GET https://api.nuget.org/v3/index.FindPackagesById()?Id='Microsoft.AspNet.IISPlatformHandler'.
GET https://api.nuget.org/v3/index.FindPackagesById()?Id='Microsoft.AspNet.StaticFiles'.
Warning: FindPackagesById: Microsoft.Aspnet.Mvc
Error: NameResolutionFailure
Warning: FindPackagesById: Microsoft.Aspnet.Server.Kestrel
Error: NameResolutionFailure
Warning: FindPackagesById: Microsoft.Aspnet.IISPlatformHandler
Error: NameResolutionFailure
Warning: FindPackagesById: Microsoft.Aspnet.StaticFiles
Error: NameResolutionFailure

Restore failed.
A task was cancelled.

Feed used:
https://api.nuget.org/v3/index.json
The command 'dnu restore' returned a non-zero code: 1

Please advise, @davidfowl
