### ISSUE TITLE
Error: SHA1 mismatch after brew install dnvm on Mac OSX Yosemite

### ISSUE THREAD

**Issue by pellicus** [aspnet/Home#514]
Hi There,
I do  (after tap and brew update)
brew install dnvm

and I get

==> Installing dnvm dependency: mono
==> Downloading http://download.mono-project.com/sources/mono/mono-3.2.8.tar.bz2
###### ################################################################## 100,0%

==> Downloading https://bugzilla.xamarin.com/attachment.cgi?id=6399
###### ################################################################## 100,0%

==> Patching
patching file data/config.in
==> Downloading http://storage.bos.xamarin.com/mono-dist-master/latest/monolite-111-latest.tar.gz
###### ################################################################## 100,0%

Error: SHA1 mismatch
Expected: 7f6715b8e569b6e7ad85c207311f145f688b3cf5
Actual: 41e32ea8c756049be34d317391618b8bc7864c16
Archive: /Library/Caches/Homebrew/mono--monolite-111.tar.gz
To retry an incomplete download, remove the file above.

I'm trying to install it to be able to test the Visual Studio Code IDE node.js debugging feature.

Thanks in advance!

**Comment by freimer** [comment]
That is odd, because I get:
freimermac:projects freimer$ brew install dnvm
==> Installing dnvm from aspnet/homebrew-dnx
==> Installing dnvm dependency: mono
==> Downloading https://homebrew.bintray.com/bottles/mono-4.0.1.yosemite.bottle.tar.gz
######################################################################## 100.0%
==> Pouring mono-4.0.1.yosemite.bottle.tar.gz

Why would you be loading mono-3.2.8?  It should be mono-4.0.1.  I suspect your tap did not go right, because you don't list the "Installing dmvm from aspnet/homebrew-dnx" as shown in my log...

HTH,

**Comment by pellicus** [comment]
I really dunno what to say :(

here my logs, I tried to retap again:

XRETINA:~ pellicus$ brew tap aspnet/dnx
Warning: Already tapped!
XRETINA:~ pellicus$ brew untap aspnet/dnx
Untapped 2 formula
XRETINA:~ pellicus$ brew tap aspnet/dnx
Cloning into '/usr/local/Library/Taps/aspnet-dnx'...
remote: Counting objects: 103, done.
remote: Total 103 (delta 0), reused 0 (delta 0), pack-reused 103
Receiving objects: 100% (103/103), 16.83 KiB | 0 bytes/s, done.
Resolving deltas: 100% (52/52), done.
Checking connectivity... done.
Tapped 2 formula
XRETINA:~ pellicus$ brew install dnvm
==> Installing dnvm dependency: mono
==> Downloading http://download.mono-project.com/sources/mono/mono-3.2.8.tar.bz2
Already downloaded: /Library/Caches/Homebrew/mono-3.2.8.tar.bz2
==> Downloading https://bugzilla.xamarin.com/attachment.cgi?id=6399
Already downloaded: /Library/Caches/Homebrew/mono--patch-d011dc55f341feea0bdb8aa645688b815910b734.cgi
==> Patching
patching file data/config.in
==> Downloading http://storage.bos.xamarin.com/mono-dist-master/latest/monolite-111-latest.tar.gz
Already downloaded: /Library/Caches/Homebrew/mono--monolite-111.tar.gz
Error: SHA1 mismatch
Expected: 7f6715b8e569b6e7ad85c207311f145f688b3cf5
Actual: 41e32ea8c756049be34d317391618b8bc7864c16
Archive: /Library/Caches/Homebrew/mono--monolite-111.tar.gz
To retry an incomplete download, remove the file above.
XRETINA:~ pellicus$ 

still trying to load 3.2.8!

anyway Thank you for your answer :D 

Dax.

**Comment by davidfowl** [comment]
Did you try brew update after tapping

**Comment by freimer** [comment]
Your brew formulas are probably out of date.  mono is not in the aspnet/dnx tap, it's in its own formulae.  Do a brew update and see if mono is listed as an updated formulae.  I just did an update, and mono was not listed, but a bunch of other formulae were...

**Comment by freimer** [comment]
You can do a brew info mono also:

$ brew info mono
mono: stable 4.0.1 (bottled)
http://www.mono-project.com/
/usr/local/Cellar/mono/4.0.1 (1004 files, 178M) *
  Poured from bottle
From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/mono.rb
==> Caveats
To use the assemblies from other formulae you need to set:
  export MONO_GAC_PREFIX="/usr/local"

**Comment by csksm** [comment]
I have the same issue also. And it goes away after I run "brew update".

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
