### ISSUE TITLE
.NET Execution Environment is not installed?

### ISSUE THREAD

**Issue by nxion** [aspnet/Home#519]
Follow the first tutorial "Building ASP.NET 5 Applications with Visual Studio Code” the step after you use `yo aspnet` to create the webapp it has you `cd` to the app and run `dnu restore`. My output is as follows:
`zsh: command not found: dnu`

So also if you run `dnvm list`:
`.NET Execution Environment is not installed.`

Not sure what happend. I did use the install instruction from this [Github] (https://github.com/aspnet/home#os-x) it install what was required.

My system is OS X 10.10.3

**Comment by muratg** [comment]
@nxion Try the following:
```
dnvm upgrade
dnvm list
```

**Comment by nxion** [comment]
@muratg. Thanks for the suggestion, this is the output.
`Determining latest version
Error: Could not find latest version from feed https://www.nuget.org/api/v2`

**Comment by nxion** [comment]
I sincerely apologize. It turns out that it is  a proxy issue. All my issue and not aspnet. So sorry to bother with this. That should have been the first thing I checked.
