### ISSUE TITLE
Add "k list"

### ISSUE THREAD

**Issue by MikaelSoderstrom** [aspnet/Home#52]
There should be a way to list all commands in project.json by using something like:
> k list

If I write for example:
> k something

I get:
> Unable to load application or execute command 'something'. Available commands: web.

Apparently, a list of available commands exists, and I would prefer to get that list by using the list command.

**Comment by danroth27** [comment]
@MikaelSoderstrom Let us know if the new built-in support for grunt in VS meets your needs.
