### ISSUE TITLE
dnvm-beta5 to dnvm-beta4

### ISSUE THREAD

**Issue by jrock2004** [aspnet/Home#525]
I thought I read somewhere that we should downgrade dnu from beta5 to dnu beta4. I cannot find this issue. Could you please link to those instructions?

**Comment by davidfowl** [comment]
Nobody said to downgrade, they said you should use consistent versions. Beta5 packages and beta5 dnx etc. DNVM versions don't matter at all as they span multiple versions

**Comment by jrock2004** [comment]
ok, so maybe I need to word this better. So it seems beta5 is dev branch. I want beta4 not 5.

**Comment by davidfowl** [comment]
beta4 of what?

**Comment by jrock2004** [comment]
dnx. I do not want to go to beta5 just yet.

**Comment by davidfowl** [comment]
What does `dnvm list` show?

**Comment by jrock2004** [comment]
dnx-beta5

**Comment by davidfowl** [comment]
can you show the output

**Comment by jrock2004** [comment]
This is because I did dnvm -u which used myget which I assume is the dev branch

**Comment by davidfowl** [comment]
Then just run without -u

**Comment by jrock2004** [comment]
I figured out how to get dnv upgrade to work so now it shows

``` bash
➜  ~  dnvm list

Active Version              Runtime Arch Location             Alias
------ -------              ------- ---- --------             -----
  *    1.0.0-beta4          mono         ~/.dnx/runtimes      default
```
