### ISSUE TITLE
nuget.org feed not updated with beta4 packages

### ISSUE THREAD

**Issue by conniey** [aspnet/Home#526]
Hi,

I was looking through the stable release of ASP.NET 5 on nuget.org and noticed that the following packages were still on beta3 even though other packages were on beta4.  Is this something intentional?  The beta4 packages were available on your myget feed though, so I am a little confused.
* http://www.nuget.org/packages/Microsoft.AspNet.Security.Cookies/1.0.0-beta3
* http://www.nuget.org/packages/Microsoft.AspNet.Security.OpenIdConnect/1.0.0-beta3

**Comment by davidfowl** [comment]
Those got renamed  `Microsoft.AspNet.Authentication.*`

**Comment by Eilon** [comment]
Added an announcement: https://github.com/aspnet/Announcements/issues/12
