### ISSUE TITLE
Is .resx (xml format) still going to be the format for resource files. 

### ISSUE THREAD

**Issue by govin** [aspnet/Home#527]
Noticed that the configuration system changed from XML to any pluggable system (JSON, XML etc.). Is the resource file format for i18n and l10n still going to remain .resx (XML based) or is it going to change/become configurable too?

**Comment by davidfowl** [comment]
Yes they will work as they always did. We'll provide an abstraction on top as well to allow plugging in other formats like po files.

**Comment by govin** [comment]
sounds good, thanks!

**Comment by evil-shrike** [comment]
@davidfowl But VS 2015 RC doesn't support resx files anymore. Could you share any thoughts on this? Why and when (if ever) VS will support resx files again. It believe "RC" should be pretty serious stage to have so base feature.
