### ISSUE TITLE
Question - Visual Studio 2015 RC Package Restore

### ISSUE THREAD

**Issue by jsacapdev** [aspnet/Home#529]
Please mark as a question.

I have the default starter application in 2015 RC. It works fine. So, I change the project.json to use the latest packages:

Heres the project.json file:

```JSON
{
  "version": "1.0.0-*",
  "description": "",
  "authors": [ "" ],
  "tags": [ "" ],
  "projectUrl": "",
  "licenseUrl": "",

  "dependencies": {
  },

  "commands": {
    "ConsoleApp1" : "ConsoleApp1"
  },

  "frameworks" : {
    "dnx451": { },
    "dnxcore50" : {
      "dependencies": {
        "System.Console": "4.0.0-*",
        "System.Collections": "4.0.10-*",
        "System.Linq": "4.0.0-*",
        "System.Threading": "4.0.10-*",
        "Microsoft.CSharp": "4.0.0-*"
      }
    }
  }
}
```

This is what my package sources look like in a fresh Visual Studio install:

![image](https://cloud.githubusercontent.com/assets/10151920/7428924/3078654c-efe8-11e4-81a5-79f3f46729e8.png)

I upgrade my dnx at the command line, so I have the latest version of clr and core clr:

```
Active Version           Runtime Architecture Location                   Alias

1.0.0-beta4       clr     x64          C:\Users\tdu\.dnx\runtimes

1.0.0-beta4       clr     x86          C:\Users\tdu\.dnx\runtimes

1.0.0-beta4       coreclr x64          C:\Users\tdu\.dnx\runtimes

1.0.0-beta4       coreclr x86          C:\Users\tdu\.dnx\runtimes

*    1.0.0-beta5-11672 clr     x86          C:\Users\tdu\.dnx\runtimes default

1.0.0-beta5-11672 coreclr x86          C:\Users\tdu\.dnx\runtimes

```
	   
In my project setting, I tell it to use the latest version of the dnx (see screenshot below):

![image](https://cloud.githubusercontent.com/assets/10151920/7428937/514df6c4-efe8-11e4-974c-6fb518a3d6cf.png)

When I then try and build in Visual Studio, it comes back with errors, and its because the references are missing for Core (see screen shot below):

![image](https://cloud.githubusercontent.com/assets/10151920/7428949/6454bd8e-efe8-11e4-92f3-09836d9934af.png)

I am wondering why Visual Studio cant resolve them. I try and resolve them at the command line:

dnu restore --no-cache

But, it does work at the command line:

dnx . ConsoleApp1

If I switch back to beta-4:

***

Active Version           Runtime Architecture Location                   Alias

1.0.0-beta4       clr     x64          C:\Users\tdu\.dnx\runtimes

*    1.0.0-beta4       clr     x86          C:\Users\tdu\.dnx\runtimes default

1.0.0-beta4       coreclr x64          C:\Users\tdu\.dnx\runtimes

1.0.0-beta4       coreclr x86          C:\Users\tdu\.dnx\runtimes

1.0.0-beta5-11672 clr     x86          C:\Users\tdu\.dnx\runtimes

1.0.0-beta5-11672 coreclr x86          C:\Users\tdu\.dnx\runtimes

***
	   
...run a restore --no-cache, Visual Studio starts to build and run OK.

Please can you explain why this wont build (and run) in Visual Studio? What am I dong incorrectly? Thanks in advance, its just for my understanding.

**Comment by davidfowl** [comment]
Check nuget.org

**Comment by davidfowl** [comment]
Another tip,  there's an SDK version burned into your global.json. It can either be a version number or an alias.
