### ISSUE TITLE
<environment> tags emitted to markup

### ISSUE THREAD

**Issue by GuardRex** [aspnet/Home#534]
Testing out [The Lesser Scotts Build demo](http://channel9.msdn.com/Events/Build/2015/2-687) @shanselman @coolcsh of &lt;environment&gt; tags ... but they are getting emitted into my markup ...
```
<environment names="Development">
    <link rel="stylesheet" href="/style.css">
</environment>
<environment names="Production">
    <link rel="stylesheet" href="http://XXXXX.vo.msecnd.net/YYYYY/style.css">
</environment>
```
I know that the env var `ASPNET_ENV` has a valid value ...
```
_config.Get("ASPNET_ENV");
```
returns `Development`. What am I missing to make this work?

**Comment by developer1998** [comment]
I have the same problem. Whether I run in debug or release mode. It still shows up the same reference.
I have for development href set as bootstrap.css
and
for Staging, Production href set as bootstrap.min.css
But I always get bootstrap.css regardless. 
What are we doing wrong?

**Comment by GuardRex** [comment]
I just sent a tweet directly to @shanselman to see if he would chime in ... after all ... he showed us this!! lol

**Comment by shanselman** [comment]
very likely you haven't imported the taghelper at the top of the layout.

**Comment by shanselman** [comment]
The layout page does two things. Imports the helpers and DI s the configuration object in.

**Comment by GuardRex** [comment]
I tried it like this:
```
@addTagHelper "*, Microsoft.AspNet.Mvc.TagHelpers"
```
... at the top of my `_Layout.cshtml`, but that didn't work. I'm still getting ...
```
<environment names="Development">
    <link rel="stylesheet" href="/style.css">
</environment>
<environment names="Production">
    <link rel="stylesheet" href="http://XXXXX.vo.msecnd.net/YYYYY/stylesheets/style.css">
</environment>
```
... in the emitted markup.

When you say "DI s the configuration object in", am I missing that `@inject` line that you had in your demo app?

**Comment by shanselman** [comment]
@damianedwards

**Comment by GuardRex** [comment]
If it's the `@inject` that I need there and not the `@addTagHelpler` line (you didn't have that in your app), it's claiming that I'm missing a dependency for that injection statement.

**Comment by dougbu** [comment]
@GuardRex could you please include the full content of the nearest-to-working main file (containing the `<environment/>` elements), layout file(s), and any other .cshtml (e.g. _GlobalImport.cshtml or _ViewStart.cshtml) involved in this scenario?  might also help if we could see the action method calling this view.

**Comment by GuardRex** [comment]
Sure ... I'm running out on errands now, but I'll get that posted in a few hours.

**Comment by developer1998** [comment]
@shanselman I have them imported:
My _GlobalImport has @addTagHelper "*, Microsoft.AspNet.Mvc.TagHelpers"

Then in _Layout I have
```
        <environment names="Development">
            <link rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.css" />
        </environment>
```
```
        <environment names="Staging,Production">
            <link rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.min.css"
                  asp-fallback-href="~/lib/bootstrap/css/bootstrap.css"
                  asp-fallback-test-class="" asp-fallback-test-property="" asp-fallback-test-value="" />
</environment>
```
And regardless if I am in debug or release mode I always get bootstrap.css. I am building on top of the ASP.NET 5 Site

**Comment by GuardRex** [comment]
@dougbu Ok, I figured out the problem (but it's different than @developer1998). It had to do with minfication. Consider this markup:
```
@addTagHelper "*, Microsoft.AspNet.Mvc.TagHelpers"
<!DOCTYPE html>
    <html lang="en-us">
        <head>
            <title>Environment Tag Issue Demo</title>
            <meta http-equiv="Content-type" content="text/html;charset=UTF-8">
            <environment names="Development">
                <link rel="stylesheet" href="/style.css">
            </environment>
            <environment names="Production">
                <link rel="stylesheet" href="http://azXXXXXX.vo.msecnd.net/stylesheets/style.css">
            </environment>
        </head>
    <body>
        @RenderBody()
    </body>
</html>
```
When that gets minified (I'm using `gulp-minify-html`), you get this ...
```
@addTagHelper "*, Microsoft.AspNet.Mvc.TagHelpers"<!DOCTYPE html><html lang= ...continued...
```
... which hoses the tag helper. I've learned that this is a general issue with all Razor directives ... there is no statement termination. If we're going to be using gulp/grunt to minify views (e.g., I have a Views_debug folder and I have a gulp watch on that to minify into my Views folder), then we're gonna be hosed whenever Razor directives are used. I was going to suggest that Razor directives get a statement terminator. That way, when a view is minfied, the Razor interpreter won't choke. [If I'm saying this right ... I'm new to MVC.]

When I put a carriage return after that tag helper and leave the rest of the view minified on the 2nd line, my `<environment>` tags work just fine. I'm cool on understanding the reason this happened. I'm just left wondering if you can give me a tip: How can I minify a view with gulp without minifying the Razor directives?

**Comment by GuardRex** [comment]
Yes, unlike @developer1998, my `<environment>` tags work fine when I set the environment variable `ASPNET_ENV` to either `Development` or `Production` ... I do get the correct markup emitted.

**Comment by danroth27** [comment]
@DamianEdwards @NTaylorMullen Adding some more folks to help investigate.

**Comment by NTaylorMullen** [comment]
Looks like @GuardRex figured it out. Directives as it stands today need to be on their own line.

**Comment by GuardRex** [comment]
So what are folks doing to minify views prior to deployment? Are they minifying and then injecting the directives back into the top of the view?

**Comment by GuardRex** [comment]
... or is there a way I can post-process view minification after the Razor engine has done its bit and taken out the directives but before I `dnu publish`?

**Comment by developer1998** [comment]
@GuardRex thanks, setting ASPNET_ENV: "Staging" solved the problem.
However, I would like to control this dynamically. If I am in debug mode, I want ASPNET_ENV to be Development, when I am in Release I would like it to be Staging, when I am publishing I would like it to be Production. I don't want to do this manually. Please advise.

**Comment by GuardRex** [comment]
@developer1998 I solved in Startup.cs taking advantage of the fact that my Azure VM's have the same prefix ("VM") ...
```
public void ConfigureServices(IServiceCollection services) {
            config = new Configuration().AddEnvironmentVariables();
            string machineName = System.Environment.GetEnvironmentVariable("COMPUTERNAME");
            if (machineName.StartsWith("VM")) {
                config.Set("ASPNET_ENV", "Production");
            } else {
                config.Set("ASPNET_ENV", "Development");
            }
            services.AddSingleton<IConfiguration>(_ => config);
            services.AddMvc();
        }
```
Once that is set, the `ASPNET_ENV` environment var will get picked up and you shouldn't have to do anything else.

There might be a more elegant way to handle the `machineName` here, but when I tried to read the `config` value for `MachineName`, it failed. Doing it this way works. If anyone has a suggestion on how that "should be done," please let me know.

**Comment by GuardRex** [comment]
@developer1998 ... oh, and I wasn't too worried for my own needs on debug vs. release. My dev box is "debug" and my VM's are "release".

**Comment by developer1998** [comment]
@GuardRex well you are limiting yourself because you are relying that the machineName starts with VM. However what happens if it runs of someone's memory stick, or any other location. It should know that this is Production as well.
So there have to be some triggers that surely will identify debug, staging, and production. 
This is how I want it, regardless of machine name, etc...

Debug = Development
Release = Staging
Published = Production

**Comment by GuardRex** [comment]
@developer1998 It's not a limitation for me just because these are private apps owned by my corp. Using the MachineName like this definitely isn't a general solution, but it will work well for my needs.

On the other hand, any logic could be put there. Try hooking the enviroment var `DNX_CONFIGURATION` and see if that will at least get you a value of `debug` or `release`.

**Comment by GuardRex** [comment]
@developer1998 btw- If you wanted to inspect all of the env vars, toss this line in there with a breakpoint and you can see what's there:
```
System.Collections.IDictionary de = System.Environment.GetEnvironmentVariables();
```

**Comment by dpaquette** [comment]
@developer1998 - I initially also thought that solution configuration in Visual Studio to map to the value you have specified for ASPNET_ENV. However after playing around with this, I think a better solution might be to define a new debug profile for your project.

1. Open the Properties page for your xproj file and select the Debug tab.
2. Click New... and enter 'IIS Express - Prod" for the name.
3. For Launch, select IIS Express
4. Add a new Environment Variable with name ASPNET_ENV and value Production
Save your project.

Now in the Debug dropdown, choosing IIS Express will launch in Development mode. Choosing IIS Express - Prod will launch in Production mode. You can add as many different profiles as you want here.
![prod](https://cloud.githubusercontent.com/assets/2531875/7446029/d4750e5e-f18f-11e4-8930-359945876622.png)

I think this is a little more clear because Visual Studio solution configurations (debug/release) are not really the same thing as environment variables. It might be better to keep these separate.

**Comment by DamianEdwards** [comment]
+1 to @dpaquette, that's the intended way to do this. Build configurations are indeed different to environment names and the launch profiles are the way to correlate those for the purposes of development. By default, the environment is Production, so if you publish and run from somewhere else it'll be that. On other target machines, just set the actual environment variable ASPNET_ENV to the desired name.

**Comment by developer1998** [comment]
@dpaquette @DamianEdwards  I was thinking along the same lines, to create two separate profiles, one for Development, and one for Production. 

Question, what about publishing? What decides which ASPNET_ENV is utilized, when you publish, or maybe there is a default setting on profile to use those settings when one publishes.

**Comment by GuardRex** [comment]
For starters, I tried placing the Tag Helper directive into a `_ViewStart.cshtml` file, but that didn't work. I have a gulp solution now:

Consider the unminifed markup ...
```
<!DOCTYPE html>
<html lang="en-us">
    ...
</html>
```
Install `gulp-inject-string` ...
```
npm install gulp-inject-string --save-dev
```
I'm using `gulp-minify-html` with `quotes: true` to maintain XML spec. I process shared views by minifying then injecting the `addTagHelper` directive. Because the shared views are watched, this runs automatically when a shared view is modified+saved. Because the Tag Helper directive will be on its own line in the final markup, my `<environment>` tags work.
```
gulp.task('processSharedViews', function () {
    gulp.src('Views_debug/Shared/*.cshtml')
        .pipe(minifyHTML({ quotes: true }))
        .pipe(inject.prepend('@addTagHelper "*, Microsoft.AspNet.Mvc.TagHelpers"\n'))
        .pipe(gulp.dest('Views/Shared'));
});

gulp.task('watch', function () {
    gulp.watch('Views_debug/Shared/*.cshtml', ['processSharedViews']);
});
```
The result ...
```
@addTagHelper "*, Microsoft.AspNet.Mvc.TagHelpers"
<!DOCTYPE html><html lang="en-us">...</html>
```
If this is a **smelly** :poop: approach, please let me know. I'm new to MVC.

The only obvious problem is that when I need to provide directives for models, etc. ... I'll be setting up special gulp processing for individual views to get their directives in place. I really wish Razor directives had been designed with directive terminators (e.g., with a semicolon: `@directive "...";`) so that you hand Razor completely minified markup and it wouldn't choke.

I'm still open to post-processing my minification (i.e., minify after Razor has done its bit but before I publish). if anyone knows how that can be done, I'm all :ear:'s.

**Comment by DamianEdwards** [comment]
Put the directives in the _GlobalImport.cshtml file instead.

**Comment by GuardRex** [comment]
@DamianEdwards Thanks! That got it. I guess that string injection can still help me with Razor directives that are specific to particular views.

**Comment by rjamesnw** [comment]
Just to confirm, is is still necessary to put `@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
` at the top of the `_Layout.cshtml` file? I tried putting it at the top of `_ViewImports.cshtml` and it doesn't work.  It only works in the `Layout.cshtml` file.
