### ISSUE TITLE
Improved instructions on how to use the ASP.NET Docker image

### ISSUE THREAD

**Issue by tlk** [aspnet/Home#536]
https://github.com/aspnet/Home/blob/dev/GettingStartedDeb.md#docker refers to http://blogs.msdn.com/b/webdev/archive/2015/01/14/running-asp-net-5-applications-in-linux-containers-with-docker.aspx for instructions on how to get started with docker.

However that article has become slightly outdated since `aspnet-Home/samples/HelloWeb` has been moved to `aspnet-Home/samples/latest/HelloWeb` and the `kpm` and `k` tools have been renamed to `dnu` and `dnx`. If you follow the instructions given in the blog you will get an error:

```
5k:HelloWeb tlk$ docker build -t myapp .
Sending build context to Docker daemon   320 kB
Sending build context to Docker daemon
Step 0 : FROM microsoft/aspnet
 ---> 92ff6c713c71
Step 1 : COPY . /app
 ---> Using cache
 ---> 49ad6e01fac2
Step 2 : WORKDIR /app
 ---> Using cache
 ---> 46729f4810d1
Step 3 : RUN kpm restore
 ---> Running in 2fb18c850d20
exec: "kpm": executable file not found in $PATH
INFO[0000] [8] System error: exec: "kpm": executable file not found in $PATH
5k:HelloWeb tlk$
```

Readers have already provided an updated Dockerfile in the comments section on the blog.

I suggest that updated Dockerfiles are added to the HelloMvc and HelloWeb sample apps and that the GettingStartedDeb.md file is updated with concise instructions on how the get started with the docker image.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
