### ISSUE TITLE
dnvm use not working with aliases

### ISSUE THREAD

**Issue by luisrudge** [aspnet/Home#538]
![image](https://cloud.githubusercontent.com/assets/941075/7443644/20e0f6fc-f133-11e4-924c-2c0f5ee64cbd.png)

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
