### ISSUE TITLE
Kestrel always seems to hang on exiting (Mac OSX)

### ISSUE THREAD

**Issue by govin** [aspnet/Home#539]
Pressing Cmd + K to exit kestrel causes it to hang forever. It will be useful to print to console on how to exit the kestrel web server after it starts. Also, it will be helpful to console print the port kestrel starts in instead of printing just a "started" message

**Comment by jensg** [comment]
Look here for the port number:  [https://github.com/aspnet/Home/blob/dev/samples/latest/HelloMvc/project.json](https://github.com/aspnet/Home/blob/dev/samples/latest/HelloMvc/project.json)
and find the PID here:

    lsof -i :5004

kill it:

    kill -9 {PID}

**Comment by Tragetaschen** [comment]
aspnet/KestrelHttpServer#9

**Comment by vsimonian** [comment]
To tack on to @jengsg's comment, if you want to do everything in one go, try:

```
kill `lsof -t -i:5000`
```

where 5000 is the port your project uses. (Those are backticks in the code sample, not apostrophes)

**Comment by davidfowl** [comment]
Closing this as it's already filed on Kestrel
