### ISSUE TITLE
Vs 2015 RC DNX.exe has stopped working

### ISSUE THREAD

**Issue by yashveersingh83** [aspnet/Home#543]
Hi , 
I installed  vs 2015 rc and i am getting the error when I launch vs 2015 . 
Please tell me how to fixt it. I have windows 7 sp1 .

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
