### ISSUE TITLE
Wiki: DNX Secret Configuration: Typo

### ISSUE THREAD

**Issue by vsimonian** [aspnet/Home#544]
This is perhaps the most asinine issue posted yet, but seeing as GitHub doesn't support it (yet) I can't submit a pull request for anything in the wiki. :stuck_out_tongue_winking_eye: 

On the [DNX Secret Configuration wiki entry](https://github.com/aspnet/Home/wiki/DNX-Secret-Configuration), the third sentence of the first paragraph (Today when developing applications...) "accidentally" is misspelled as "accidentilly."

**Comment by Eilon** [comment]
Fixed!

**Comment by vsimonian** [comment]
Sweet! :+1:
