### ISSUE TITLE
Is this by design, VS 2015 RC Rebuild deletes the lib folder

### ISSUE THREAD

**Issue by developer1998** [aspnet/Home#546]
I've noticed that every time I Rebuild, the lib folder is deleted. The same thing happens when I run Clean. Then I have to run gulp commands to re-create the structure. Is this by design?

**Comment by theWalli** [comment]
I'm facing the same issue and I am new to gulp. Could you please list the commands one needs to run to get the lib folder back?

**Comment by developer1998** [comment]
@theWalli Go to task manager and run gulp copy command, right click and play or double click, this gets is back.

**Comment by iecompattest** [comment]
kokoko

**Comment by developer1998** [comment]
Tweaking gulpfile.js, resolved it
