### ISSUE TITLE
Wrong link in ps1 script to the bleeding-edge kvm on release branch

### ISSUE THREAD

**Issue by mateusz-dobrowolny** [aspnet/Home#549]
URL: https://github.com/aspnet/home/tree/release
In *Windows* section:

_If you want to run on the bleeding edge and install the latest development version of KVM, run the following command:_

`@powershell -NoProfile -ExecutionPolicy unrestricted -Command "&{$Branch='dev';iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/aspnet/Home/release/kvminstall.ps1'))}"`

There is no 'kvminstall.ps1' script in dev branch. So I guess this should be replaced with dnvm... or maybe the intention was to take kvm from master branch?

**Comment by davidfowl** [comment]
We have some cleanup to do but only look at the dev branch. We're going to be deleting all over branches from the Home repository:

https://github.com/aspnet/Home

**Comment by mateusz-dobrowolny** [comment]
Thanks for comment. Actually I am trying to "publish" pre-configured (upgraded) instances of all "variations" of aspnet-vnext
At the moment they are:
master-stableish
master-bleeding-edge
release
release-bleeding-edge
dev

Do you know how this will look once it si cleaned up?
What will be the naming pattern for future releases?
Will aspnet-vnext project still be the proper place to look for a ASP.NET 6 (six), or 'vNext' is only for ASP.NET 5 (five)?

Thank

**Comment by davidfowl** [comment]
> Do you know how this will look once it si cleaned up?

The loose branches on the Home repository? Soon. /cc @glennc 

> What will be the naming pattern for future releases?

Same as the one we have right now.

> Will aspnet-vnext project still be the proper place to look for a ASP.NET 6 (six), or 'vNext' is only for ASP.NET 5 (five)?

ASP.NET 5 is the official name of the stack.

**Comment by mateusz-dobrowolny** [comment]
Thx, but that's still not clear for me.
Release branch after installation shows (with <dnvm list> command): 1.0.0-beta3-11030
dev: 1.0.0-beta4
master: 1.0.0-beta3

So there are some small differences between release and master branch.

**Comment by davidfowl** [comment]
@mateusz-dobrowolny I know it's hard because the branches exist. Use the dev branch only. Pretend like the release and master branches don't exist on the Home repository. We changed it and forgot to delete the other branches. 

https://github.com/aspnet/Home#getting-started-with-aspnet-5-and-dnx

**Comment by mateusz-dobrowolny** [comment]
Let me summarize:
The only proper branch for 'vNext' project on GitHub is 'dev'.
In that case: is there any way to download and install 'the last released stable version' of ASP.NET 5 standalone, not included within VS?

**Comment by davidfowl** [comment]
@mateusz-dobrowolny Yes there is! Please follow the dev branch instructions. It won't lead you astray. dnvm has been updated to account for this.

**Comment by mateusz-dobrowolny** [comment]
I am not sure, but 'dev' branch suggests to look at http://www.asp.net/vnext.
All I can see there is Visual Studio 2015 RC, about 5 GB.
Or is there any other way to download "ASP.NET 5 only"?

**Comment by davidfowl** [comment]
http://docs.asp.net/en/latest/

**Comment by mateusz-dobrowolny** [comment]
http://docs.asp.net/en/latest/getting-started/installing-on-windows.html#install-asp-net-standalone

It leads exactly to the dev branch! :-)
Is that OK?

Could you also clarify if there are 'daily' builds?
https://www.myget.org/gallery/aspnetvnext
It looks like version numbers are outdated... Is it proper source of nightly builds mentioned at http://www.asp.net/vnext?
_ASP.NET 5 daily builds are hosted by MyGet, a "NuGet as a service" service provider. Host your own private NuGet feeds at http://myget.org._

**Comment by davidfowl** [comment]
> It leads exactly to the dev branch! :-)
Is that OK?

I think I mentioned that more than once on this thread. When you install the latest dnvm, all of the questions will be answered.

> Could you also clarify if there are 'daily' builds?
https://www.myget.org/gallery/aspnetvnext
It looks like version numbers are outdated... Is it proper source of nightly builds mentioned at

Outdated? How so?

**Comment by mateusz-dobrowolny** [comment]
So: there is not stable version of vNext at the moment except the dev branch, because the information on 'dev' about stable release loops back to dev branch again.

Daily/nightly builds:
https://www.myget.org/gallery/aspnetvnext
From what I see:
Latest dev version: v.1.0.0-beta3-10921
Latest master version: v.1.0.0-beta1

But dev branch is already on 1.0.0-beta4..., and last week was even beta5 for a moment.

To make it short:
I am lookig for installation links for "all ASP.NET 5 versions" meant to be used by developers. One is 'dev' branch on GitHub with one powershell command.
I guess this branch is also a good source of daily/nighlty builds.

Is there anything else at the moment?

**Comment by davidfowl** [comment]
I don't know how else to explain this:

1.0.0-beta4 is the latest stable (nuget.org)
1.0.0-beta5-* is unstable (myget)

The dnvm version does not matter since its just a bootstrapper.

I don't know what you're looking at to draw your conclusions but those are the facts.

**Comment by henkmollema** [comment]
Looks like @mateusz-dobrowolny is looking at the version badges (shields) in the description which is just pointing to an old (`KRE-CLR`) package:
![http://img.shields.io/myget/aspnetvnext/v/KRE-CLR-x86.svg?style=flat](http://img.shields.io/myget/aspnetvnext/v/KRE-CLR-x86.svg?style=flat).

Perhaps they should be changed to `CoreCLR`:
![http://img.shields.io/myget/aspnetvnext/v/CoreCLR.svg?style=flat](http://img.shields.io/myget/aspnetvnext/v/CoreCLR.svg?style=flat)
![http://img.shields.io/myget/aspnetmaster/v/CoreCLR.svg?style=flat](http://img.shields.io/myget/aspnetmaster/v/CoreCLR.svg?style=flat)

**Comment by davidfowl** [comment]
Ah I see now. We'll fix that. Sorry for the confusion.

**Comment by mateusz-dobrowolny** [comment]
@henkmollema - thx!
@davidfowl - yes, I would like to confirm somewhere I have the latest proper version installed, and those labels are confusing.

What is a proper way to check for the installed version?
Last Friday I installed all possible versions from GitHub directly, and used 
kvm list
dnvm list 
commands to determine the installed versions.

**Comment by davidfowl** [comment]
I'm not sure why it matters that you have all versions but what you did seems fine.

kvm is pre beta4
dnvm is beta4 and onwards.

**Comment by mateusz-dobrowolny** [comment]
I am still confused how to install both versions mentioned by Henk:
aspnetvnext v1.0.0-beta5-10391
aspnetmaster v1.0.0-beta4

From GitHub? <- What are proper Powershell commands then? Why there is mentioned 'master' branch? You said only 'dev' is valid.
From Nuget / Myget? <- Could you provide links?

_I'm not sure why it matters that you have all versions but what you did seems fine._
We are hosting current versions on our website, pre-configured, and we would like to have both stable and nightly builds available.

**Comment by mateusz-dobrowolny** [comment]
OK, I guess
 CoreCLR 	v1.0.0-beta5-10391 
at https://www.myget.org/gallery/aspnetvnext
is the proper link to "dev" branch and is equivalent of installing it via CMD, right?

Where can I find aspnetmaster v1.0.0-beta4?

**Comment by henkmollema** [comment]
Install beta4:
```
dnvm upgrade
```

Install the latest beta5:
```
dnvm upgrade -u
```

**Comment by mateusz-dobrowolny** [comment]
Everything clear now. Many thanks for help.
Summarizing:
install dnvm command with powershell script.
dnvm upgrade - for stable release
dnvm upgrade -u  - for latest nightly builds.
