### ISSUE TITLE
Update MyGet description

### ISSUE THREAD

**Issue by henkmollema** [aspnet/Home#550]
The badges in the MyGet description point to an old `KRE-CLR` package. Perhaps they should be updated to the new `CoreCLR` package as it might cause confusion: #549.

![http://img.shields.io/myget/aspnetvnext/v/CoreCLR.svg?style=flat](http://img.shields.io/myget/aspnetvnext/v/CoreCLR.svg?style=flat)
![http://img.shields.io/myget/aspnetmaster/v/CoreCLR.svg?style=flat](http://img.shields.io/myget/aspnetmaster/v/CoreCLR.svg?style=flat)

**Comment by henkmollema** [comment]
cc @Eilon

**Comment by Eilon** [comment]
Fixed! I also changed it to say ASP.NET 5 instead of vNext :smile: 

![image](https://cloud.githubusercontent.com/assets/202643/7456665/1af7c69a-f23b-11e4-9e1a-3066c7cdd809.png)

**Comment by henkmollema** [comment]
Cool! :smile:
