### ISSUE TITLE
Error in usage of k commands

### ISSUE THREAD

**Issue by WizardOfMenlo** [aspnet/Home#551]
When I'm executing any of "k web", "k gen" or "k ef" i get the following errors
![screenshot_mon_may_04_14 38 56](https://cloud.githubusercontent.com/assets/9511741/7453636/96432724-f26b-11e4-9c00-79b6cddaaaac.png)
I can't figure out what the problem could be, I'm executing the commands on a fresh new Web Site Asp.Net 5 template.
Not being able to use these command is greatly reducing my developement speed, especially for the inabilty of applying migrations.
Thank you
Giacomo

**Comment by henkmollema** [comment]
All the `k` commands are renamed: https://github.com/aspnet/Announcements/issues/4.

**Comment by WizardOfMenlo** [comment]
So in order to use command line scaffolding what should I do?

**Comment by henkmollema** [comment]
```
dnx . ef
```
You need the new runtime as well. See [the readme](https://github.com/aspnet/Home#what-you-need).

**Comment by WizardOfMenlo** [comment]
thank you very much @henkmollema , really appreciate, keep up the good work and have a wonderful day!

**Comment by henkmollema** [comment]
Welcome! :+1:
