### ISSUE TITLE
Update wiki repo list

### ISSUE THREAD

**Issue by henkmollema** [aspnet/Home#553]
https://github.com/aspnet/Home/wiki/Repo-List

- homebrew-k -> [homebrew-dnx](https://github.com/aspnet/homebrew-dnx)
- KRuntime -> [DNX](https://github.com/aspnet/dnx) - "The DNX (a .NET Execution Environment) contains the code required to bootstrap and run an application, including the compilation system, SDK tools, and the native CLR hosts."
- kvm -> [dnvm](https://github.com/aspnet/dnvm) - "The .NET SDK Manager, a set of command line utilities to update and configure which runtime (KRE) to use."

**Comment by Eilon** [comment]
You know, I think I'll just delete that list. At the time I made that list we just didn't have descriptions on each of our repos, and now we do. (There might be some missing, but I can fill those in.)

**Comment by henkmollema** [comment]
That works too! :+1:

**Comment by Eilon** [comment]
OK replaced the link and removed the old repo list page. Thanks!
