### ISSUE TITLE
The 'postrestore' script failed with status code 1.

### ISSUE THREAD

**Issue by developer1998** [aspnet/Home#558]
The postrestore is failing for me.
  "scripts": {
    "postrestore": [ "npm install", "bower install" ],
    "prepare": [ "gulp copy" ]
  }

This is the message I get when I save project.json
bower                           ENOENT No bower.json present
The 'postrestore' script failed with status code 1.
This is strange because there is bower.json is present under root along with the other configurations, and it's contents is:
{
  "name": "ASP.NET",
  "private": true,
  "dependencies": {
    "bootstrap": "3.0.0",
    "jquery": "1.10.2",
    "jquery-validation": "1.11.1",
    "jquery-validation-unobtrusive": "3.2.2",
    "hammer.js": "2.0.4",
    "bootstrap-touch-carousel": "0.8.0"
  }
}

**Comment by Bartmax** [comment]
I see this also when updating today to beta5-11722, same project that restore fine before.

**Comment by mikecario** [comment]
I had this same issue and It appears I resolved it by solving the line:
"Error: EACCES, permission denied '/Users/{my comp name}/.config/configstore/bower-github.yml'  You dont have access to this file."

A quick:
"sudo chmod 777 /Users/{insert your computer name here}/.config/configstore/bower-github.yml"

And now I can run gnu restore without fail.

**Comment by developer1998** [comment]
@mikecario I don't think this is related what you are describing. My solution does not inerfeace with git-hub. Problem surfaces when I save the project.json. I will double check if this is happening in a brand new solution...

**Comment by AGusty** [comment]
It happens every time I publish the site. The workaround is very simple... -> Show All Files -> delete bin folder -> restore again.

**Comment by Bartmax** [comment]
I can confirm this. dnu restore does restore packages in root and then in bin folder (last one is the one that fails).

**Comment by riyadshauk** [comment]
Worked the second time for me:

I typed "sudo dnu restore" and got the error mentioned in this thread about postrestore. I then had to "sudo chmod 777 project.lock.json" (or some other chmod prob would be fine). Then I ran "dnu restore", allowing bower to do its stuff and finishing the restore successfully: "Done, without errors. Restore complete, 47537ms elapsed".

**Comment by developer1998** [comment]
after I got my libraries sorted out with the help of David and ran dnu restore, all is well. Make sure this:
global.json uses the run time of your libraries "version": "1.0.0-beta5-11855"
and your C:\Users\[user name]\AppData\Roaming\NuGet\NuGet.Config has this configuration, then run dnu restore
'''
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <clear />
    <add key="AspNetVNext" value="https://www.myget.org/F/aspnetvnext/api/v2" />
    <add key="NuGetorg" value="https://nuget.org/api/v2/" />
  </packageSources>
</configuration>
'''

**Comment by patoncrispy** [comment]
+1 for @riyadshauk's solution. Worked fine for me.

**Comment by cataquil** [comment]
Can confirm this is still happening running the yeoman asp.net template on omnisharp-atom on windows 8

**Comment by cataquil** [comment]
I got this error runing yeoman aspnet in Omnisharp-atom on windows 8, just had to install bower.  Will try beta5 on vs2015 first.
