### ISSUE TITLE
Dependency resolution failure running VS 2015 RC1 using beta5

### ISSUE THREAD

**Issue by jsacapdev** [aspnet/Home#560]
Visual Studio 2015 RC1 Installed (Azure Visual Studio RC template).

A simple web application, fails to run when attempting to debug or run (using web command or in IIS) with the following error:

***

System.InvalidOperationException: Failed to resolve the following dependencies for target framework 'DNX,Version=v4.5.1':
   Microsoft.AspNet.Diagnostics 1.0.0
   Microsoft.AspNet.Server.IIS 1.0.0
   Microsoft.AspNet.Server.WebListener 1.0.0

Searched Locations:
  C:\Tmp\Sample\src\{name}\project.json
  C:\Tmp\Sample\test\{name}\project.json
  C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.1\{name}.dll
  C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.1\Facades\{name}.dll
  C:\Windows\Microsoft.NET\assembly\GAC_32\{name}\{version}\{name}.dll
  C:\Windows\Microsoft.NET\assembly\GAC_64\{name}\{version}\{name}.dll
  C:\Windows\Microsoft.NET\assembly\GAC_MSIL\{name}\{version}\{name}.dll

Try running 'dnu restore'.

   at Microsoft.Framework.Runtime.DefaultHost.GetEntryPoint(String applicationName)
   at Microsoft.Framework.ApplicationHost.Program.ExecuteMain(DefaultHost host, String applicationName, String[] args)
   at Microsoft.Framework.ApplicationHost.Program.Main(String[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Framework.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider serviceProv
ider)
   at dnx.host.Bootstrapper.RunAsync(List`1 args)
   at dnx.host.RuntimeBootstrapper.ExecuteAsync(String[] args)
   at dnx.host.RuntimeBootstrapper.Execute(String[] args)
Press any key to continue . . .

***

The screenshot below shows that Visual Studio is able to resolve the dependencies OK:

![image](https://cloud.githubusercontent.com/assets/10151920/7471966/e4dc9526-f31c-11e4-936c-40308a82d3f5.png)

Also, when attempting to run this  application at the command line:

dnx . web

...runs OK. The following DNX versions are installed:

***
C:\Tmp\Sample\src\Sample>dnvm list

Active Version           Runtime Architecture Location                   Alias
       1.0.0-beta4       clr     x64          C:\Users\tdu\.dnx\runtimes
       1.0.0-beta4       clr     x86          C:\Users\tdu\.dnx\runtimes
       1.0.0-beta4       coreclr x64          C:\Users\tdu\.dnx\runtimes
       1.0.0-beta4       coreclr x86          C:\Users\tdu\.dnx\runtimes
       1.0.0-beta4-11566 clr     x86          C:\Users\tdu\.dnx\runtimes u
       1.0.0-beta5-11672 clr     x86          C:\Users\tdu\.dnx\runtimes
       1.0.0-beta5-11672 coreclr x86          C:\Users\tdu\.dnx\runtimes
  *    1.0.0-beta5-11682 clr     x86          C:\Users\tdu\.dnx\runtimes default
       1.0.0-beta5-11682 coreclr x86          C:\Users\tdu\.dnx\runtimes

***
	   
Here are the package sources:

![image](https://cloud.githubusercontent.com/assets/10151920/7471981/0788614a-f31d-11e4-9c70-e72b55f302b0.png)

Heres my project.json:

{
  "webroot": "wwwroot",
  "version": "1.0.0-*",

  "dependencies": {

    "Microsoft.AspNet.Server.IIS": "1.0.0-*",
    "Microsoft.AspNet.Server.WebListener": "1.0.0-*",
    "Microsoft.AspNet.Diagnostics": "1.0.0-*"
  },

  "commands": {
      "web": "Microsoft.AspNet.Hosting --server Microsoft.AspNet.Server.WebListener --server.urls http://localhost:5000"
  },

  "frameworks": {
    "dnx451": { },
    "dnxcore50": { }
  },

  "publishExclude": [
    "node_modules",
    "bower_components",
    "**.xproj",
    "**.user",
    "**.vspscc"
  ],
  "exclude": [
    "wwwroot",
    "node_modules",
    "bower_components"
  ]
}

***

Let me know if you need the project.json.lock.

**Comment by Kukkimonsuta** [comment]
I think VS might be running wrong version of runtime and/or searching in the frong feed. I noticed that VS is installing dnvm in different folder (somewhere in program files) and doesn't contain the -Unstable switch, so I installed the one from github, removed original files in program files and created weak links to the ones in user profile and beta5 seem to be working fine for me. Let me know whether this helps, I might post better guide of how I got things working later when I get home from work.

**Comment by jsacapdev** [comment]
I encountered the same problem with with -u switch (see https://github.com/aspnet/dnvm/issues/256).

Can you elborate on what you mean by "created weak links to the ones in user profile"? How would I create the weak links? I am already referencing the latest DNX:

C:\Tmp\Sample\src\Sample>where dnx.exe
C:\Users\tdu\.dnx\runtimes\dnx-clr-win-x86.1.0.0-beta5-11682\bin\dnx.exe

I am guessing thats what VS uses:

![image](https://cloud.githubusercontent.com/assets/10151920/7473055/f6eb5ca8-f32f-11e4-9a64-2ee582cdbc2c.png)

![image](https://cloud.githubusercontent.com/assets/10151920/7473076/105036aa-f330-11e4-8b40-58373bc1ae12.png)

Here's another question across the community. Can anyone confirm they are using beta5 packages and it is running OK in the context of Visual Studio 2015 RC? (It might be a no brainier, but I am just trying to understand if it is something to do with my environment).

**Comment by Kukkimonsuta** [comment]
Sorry, symbolic link `mklink <link> <target>`

And yes, I'm working with VS 2015 RC and beta5 runtime and packages.

**Comment by jsacapdev** [comment]
If possible, please can you provide me with some more info:

a. the complete command when you created the symbolic link
b. where the symbolic link was created
