### ISSUE TITLE
Serving legacy ASP.NET Websites

### ISSUE THREAD

**Issue by piccaso** [aspnet/Home#561]
Is it possible to run websites that currently work on IIS 7.5 or mono/xsp4 on dnx/kestrel.
From what i understand it could be as easy as having the right `{"commands":{ ? }}` in Project.json.

I want to keep my existing workflow (using Visual Studio 2013 Community) for now but want to test the websites with different servers/databases (docker makes that easy...).

Can someone please put me on the right track?

Thanks!

**Comment by Eilon** [comment]
There is no support for ASP.NET 4.x projects (e.g. MVC 5.x and earlier, Web API 2.x and earlier, Web Forms) on DNX. Is that what you're asking for?

**Comment by piccaso** [comment]
Yes... i'm trying to get away without migrating to VS2015... looks like this wont happen :)

Thanks!

**Comment by Eilon** [comment]
Yeah the version numbers are a bit confusing, sorry about that!

Fortunately there's lots of choice these days for editors: VS2015 (Windows only, fully featured), or [Visual Studio Code](https://code.visualstudio.com/) (Windows, Mac, Linux), or [OmniSharp](http://www.omnisharp.net/) (lots of platforms, lots of editors) all serve as terrific experiences for working on ASP.NET 5 applications.
