### ISSUE TITLE
Suppress compiler warnings

### ISSUE THREAD

**Issue by smudge202** [aspnet/Home#564]
Is there a way (if not, should/can there be a way) to surpress certain compiler issues akin Build tab in old project properties?

http://puu.sh/hCNDe/6314b5a5ef.png

I don't believe anything in the project.json schema currently supports this?

**Comment by davidfowl** [comment]
We need to add support for this

**Comment by smudge202** [comment]
Workaround for time being would be to `#pragma warning disable ###` / `#pragma warning restore ###`.

Not sure if easier/better workarounds available?

**Comment by davidfowl** [comment]
@smudge202 Can you file an issue for this on dnx

**Comment by smudge202** [comment]
Issue raised here: aspnet/dnx#2042
