### ISSUE TITLE
Output path

### ISSUE THREAD

**Issue by smudge202** [aspnet/Home#565]
Is there a way (should/can there be a way) to define output paths (by configuration), akin build tab in old project properties.

http://puu.sh/hCOkz/89e14a2e43.png

I don't believe anything in the project.json schema currently supports this?

**Comment by davidfowl** [comment]
What for?

**Comment by smudge202** [comment]
I stumbled across the issue trying to port FluentAssertions. It currently uses a slightly convoluted nuget packaging process (though not particular uncommon approach) which drops the dll's into certain folders and uses the directory template nuget packaging process (not sure if that's the correct name), whereby you drop the correct dll's into lib/net40, lib/dnxcore, etc, then run a nuget package.

**Comment by davidfowl** [comment]
This sorta stuff doesn't belong in the project.json. Right now you can set it in the xproj file. Or it can be passed to the command line when you `dnu build` and `dnu pack`

**Comment by smudge202** [comment]
Yup, happy with that. Bit tedious editing the xproj but hopefully it's an edge case.

**Comment by davidfowl** [comment]
We'll have UI for it eventually /cc @BillHiebert @sayedihashimi

**Comment by stefan505** [comment]
Are there any plans to add this soon? Its possible to set in the xproj file off course, but it would be nice to set it via the properties GUI as well. We intend to create many DNX-based class libs and I envisage a shared output folder for them all that can added as a NuGet package path.

**Comment by sayedihashimi** [comment]
Moved to https://github.com/aspnet/Tooling/issues/314 closing this issue, we can continue in the tooling repo.
