### ISSUE TITLE
dnvm - help should only come up if I ask for it

### ISSUE THREAD

**Issue by richlander** [aspnet/Home#566]
I only want to see the help spew if I want it. Otherwise, I just want errors.

dotnet-mbp:ConsoleApp richlander$ dnvm use
    ___  _  ___   ____  ___
   / _ \/ |/ / | / /  |/  /
  / // /    /| |/ / /|_/ / 
 /____/_/|_/ |___/_/  /_/  

.NET Version Manager - Version 1.0.0-beta5-10373
By Microsoft Open Technologies, Inc.

DNVM can be used to download versions of the .NET Execution Environment and manage which version you are using.
You can control the URL of the stable and unstable channel by setting the DNX_FEED and DNX_UNSTABLE_FEED variables.

Current feed settings:
Default Stable: https://www.nuget.org/api/v2
Default Unstable: https://www.myget.org/F/aspnetvnext/api/v2
Current Stable Override: <none>
Current Unstable Override: <none>

USAGE: dnvm <command> [options] 

dnvm upgrade [-f|-force] [-u|-unstable] 
  install latest DNX from feed
  adds DNX bin to path of current command line
  set installed version as default
  -f|forces         force upgrade. Overwrite existing version of DNX if already installed
  -u|unstable       use unstable feed. Installs the DNX from the unstable unstable feed
  -r|runtime        The runtime flavor to install [clr or coreclr](default: clr)

dnvm install <semver>|<alias>|<nupkg>|latest [-a|-alias <alias>] [-p|-persistent] [-f|-force] [-u|-unstable] 
  <semver>|<alias>  install requested DNX from feed
  <nupkg>           install requested DNX from local package on filesystem
  latest            install latest version of DNX from feed
  -a|-alias <alias> set alias <alias> for requested DNX on install
  -p|-persistent    set installed version as default
  -f|force          force install. Overwrite existing version of DNX if already installed
  -u|unstable       use unstable feed. Installs the DNX from the unstable unstable feed
  -r|runtime        The runtime flavor to install [mono or coreclr](default: mono)

  adds DNX bin to path of current command line

dnvm use <semver>|<alias>|<package>|none [-p|-persistent] [-r|-runtime <runtime>] [-a|-arch <architecture>] 
  <semver>|<alias>|<package>  add DNX bin to path of current command line  
  none                        remove DNX bin from path of current command line
  -p|-persistent              set selected version as default
  -r|-runtime                 runtime to use (mono, coreclr)
  -a|-arch                    architecture to use (x64)

dnvm run <semver>|<alias> <args...> 
  <semver>|<alias>            the version or alias to run
  <args...>                   arguments to be passed to DNX

  runs the DNX command from the specified version of the runtime without affecting the current PATH

dnvm exec <semver>|<alias> <command> <args...> 
  <semver>|<alias>            the version or alias to execute in
  <command>                   the command to run
  <args...>                   arguments to be passed to the command

  runs the specified command in the context of the specified version of the runtime without affecting the current PATH
  example: dnvm exec 1.0.0-beta4 dnu build

dnvm list 
  list DNX versions installed 

dnvm alias 
  list DNX aliases which have been defined

dnvm alias <alias> 
  display value of the specified alias

dnvm alias <alias> <semver>|<alias>|<package> 
  <alias>                      the name of the alias to set
  <semver>|<alias>|<package>   the DNX version to set the alias to. Alternatively use the version of the specified alias

dnvm unalias <alias> 
  remove the specified alias

dnvm [help|-h|-help|--help] 
  displays this help text.

dnvm update-self 
  updates dnvm itself.
dotnet-mbp:ConsoleApp richlander$

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
