### ISSUE TITLE
When is it safe to upgrade Node.js and npm so it won't break Visual Studio.

### ISSUE THREAD

**Issue by developer1998** [aspnet/Home#567]
I am currently running Node.js 0.10.33 but there is a newer version 0.12.2
I am also currently running npm 1.4.28 but there is a newer version 2.9.0
So how would I know what are the recommended versions of Node.js and npm, or whether it is safe to upgrade them to the latest?

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
