### ISSUE TITLE
Running an application created in VS2015 on a mac with vscode

### ISSUE THREAD

**Issue by shaneprice** [aspnet/Home#568]
I started writing an application using the rc6 bits within windows running vs2015. With the release of 2015 RC I updated the project and have it running through IIS express without an issue.

I have installed VS code on my mac and I am trying to get the same app to run on my mac.

When I run dnvm list I get

Active Version Runtime Arch Location Alias

   1.0.0-beta5-11657    coreclr x64  ~/.dnx/runtimes      
1.0.0-beta5-11657 mono ~/.dnx/runtimes default
When opening vscode I get a warning

here are unresolved dependencies from '/MyGreatApp/Web/src/App1/project.json'. Please execute the restore command and restart Visual Studio Code.

So I run dnu restore and terminal displays

Restoring packages for /Users/me/MyGreatApp/Web/src/Project.Model/project.json
CACHE https://www.nuget.org/api/v2/FindPackagesById()?Id='dnx.coreclr.managed'
Unable to locate dnx.coreclr.managed >= 1.0.0-beta5-11657
Writing lock file /Users/me/MyGreatApp/Web/src/Project.Model/project.lock.json
Restore complete, 111ms elapsed
Errors in /Users/me/MyGreatApp/Web/src/Project.Model/project.json
Unable to locate dnx.coreclr.managed >= 1.0.0-beta5-11657

What does this mean?

The projects project.son fle looks like

{
"description": "go vnext",
"version": "1.0.0.0",
"dependencies": {
},

"frameworks": {
    "dnx451": { },
    "dnxcore50": {
         "dependencies": {"dnx.coreclr.managed": "1.0.0-beta5-11657"}
    }
}
}

The global.json looks like
{
"sources": [ "src", "test", "grunt" ],
"projects": [""],
"sdk": {
"version": "1.0.0-beta5-11657"
}
}

Is there something I am missing here?

**Comment by davidfowl** [comment]
Remove this:

`"dependencies": {"dnx.coreclr.managed": "1.0.0-beta5-11657"}`

I'm sure you never saw that in any tutorial or any project.json that exists. Try following one of the tutorials or maybe copy an existing working project from somewhere.
