### ISSUE TITLE
Should project.json be renamed?

### ISSUE THREAD

**Issue by nil4** [aspnet/Home#569]
The file name `project.json` is very generic, with no indication of the actual technology stack
it applies to. It shares this generic-naming problem with NPM's `package.json` file, and it's also easy to confuse one with the other. In contrast, [`bower.json`](https://github.com/bower/bower.json-spec) has a specific name that immediately identifies the applicable tool and provides an obvious search-engine keyword to find relevant documentation.

Since the `project.json` file now applies to more than just ASP.NET 5, and is becoming the recommended way to describe .NET projects going forward, I would suggest renaming it to something more relevant, perhaps `dnx.json` or `dnxproject.json`. 

I realize this would be a breaking change that would affect many tools besides Visual Studio. Looking back at the fallout of the K rename, I think it's fair to say that this rename would be much harder (or even impossible) to pull off after the final VS 2015 release, so I thought I should ask for feedback sooner rather than later.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
