### ISSUE TITLE
Question - Visual Studio 2015 RC set DNX_TRACE=1 to display dnx.exe log

### ISSUE THREAD

**Issue by jsacapdev** [aspnet/Home#570]
The following link:

http://davidfowl.com/diagnosing-dependency-issues-with-asp-net-5/

...provides some information around viewing dnx.exe log in the output windows in VS. Following these instructions, there is no dnx.exe log to choose from:

![image](https://cloud.githubusercontent.com/assets/10151920/7492103/4815c39e-f3e8-11e4-980c-d5a4ea1d9122.png)

I ask as I was looking into an issue with dependencies recently (difference between command line and VS), and it would have been useful to have this feature.

How can I enable Visual Studio to show the dnx.exe log output?

**Comment by kfwls** [comment]
What was your solution?

**Comment by jsacapdev** [comment]
NOTE: this does not apply to the output window, but as a workaround you can view output from the console:

Project Properties -> Debug Tab -> Environment Variables -> Name: DNX_TRACE / Value: 1

![image](https://cloud.githubusercontent.com/assets/10151920/8129463/49bcb8d4-1101-11e5-9abf-9130baf04f2b.png)

Either Run (or Debug) and the trace output is presented in the console window:

![image](https://cloud.githubusercontent.com/assets/10151920/8129488/8ec6e0d0-1101-11e5-9be1-53a3bf30c506.png)

**Comment by kfwls** [comment]
Ah, gotcha thanks. Better than nothing
