### ISSUE TITLE
Create .gitignore reference

### ISSUE THREAD

**Issue by diegobfernandez** [aspnet/Home#571]
It would be nice to have a base .gitignore for ASP.NET 5.
Maybe publish it on https://github.com/github/gitignore.
Something IDE independent.

**Comment by Kukkimonsuta** [comment]
+1

Right now I don't even know whether `project.lock.json` should be in repo or not.

**Comment by RehanSaeed** [comment]
@sayedihashimi already added ASP.NET 5 ignores to the [VS](https://github.com/github/gitignore/blob/master/VisualStudio.gitignore) .gitignores.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
