### ISSUE TITLE
Can I create a metapackage with no code?

### ISSUE THREAD

**Issue by rynowak** [aspnet/Home#573]
Forwarded question from a user:

Is there a way to create a metapackage using project.json that doesn't have a dll? If I have no code in my metapackage project, it still creates a dll in the package that's produced.

**Comment by davidfowl** [comment]
Not yet. There's a bug on dnx to allow this.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
