### ISSUE TITLE
Assetss from wwwroot cannot be found on Docker Image

### ISSUE THREAD

**Issue by wisien92** [aspnet/Home#575]
I have got Linux VM Docker Image up and running but I have encountered one problem (and wasn't able).

All assetss that were in my wwwroot folder cannot be found

> Failed to load resource: the server responded with a status of 404 (Not Found)

I have included

```
 "webroot": "wwwroot"
```

In project.json file but that doesn't fix the problem. One more thing is that running from VS 2015 (on ISS Express) everything works - is there something that I should include in Dockerfile as well?.

I added VOLUME to docker file but I probably did it wrong because it did not help (to be honest I am not sure how to use it) Dockerfile:

```
FROM microsoft/aspnet

COPY . /app
WORKDIR /app
RUN ["kpm", "restore"]

VOLUME ["/wwwroot"]

EXPOSE 5004
ENTRYPOINT ["k", "kestrel"]
```

I am not sure if it's docker issue or asp.

**Comment by tlk** [comment]
Are you sure that your Dockerfile works at all? The `k` and `kpm` commands have been renamed.

It works for me with the latest HelloWeb sample code and the #536 related pull request (see https://github.com/aspnet/Home/pull/537/files). I tested it on MacOSX/boot2docker and opening http://192.168.59.103:5004/image.jpg works fine. Note that the ip address depends on your setup, of course.

The HelloMvc sample however, does not serve static files from wwwroot. If you want to adjust the HelloWeb sample into serving static files like the HelloMvc sample, then take a look at https://github.com/aspnet/Home/blob/dev/samples/latest/HelloWeb/Startup.cs#L9. You also need to adjust dependencies in project.json to include Microsoft.AspNet.StaticFiles and perhaps also Microsoft.AspNet.Hosting. Not sure about that last one.

**Comment by wisien92** [comment]
I deleted VOLUME ["/wwwroot"] from Dockerfile and instead i try to add Volume usin -v flag in docker run command like so:

    docker run -t -v $(pwd)/wwwroot:/wwwroot-d -p 8080:5004 app

but it still gave me nothing. And I am preety sure that Dockerfile works because when I build Image the restore command works.

I did have StaticFiles dependencie but I don't have Hosting - I will add it build, run and tell you if it worked.

**Comment by tlk** [comment]
Did you manage to load image.jpg from the HelloWeb sample without using docker volumes?

**Comment by wisien92** [comment]
I'm gonna do that first thing tomorrow morning and edit this post to let you know how it went.

**Comment by wisien92** [comment]
Yes, I managed to open image.jpg from HelloWeb sample

**Comment by tlk** [comment]
Okay that's great, so it seems that what you are dealing with is a docker issue.

I assume that your Dockerfile looks like this:
```
FROM microsoft/aspnet
COPY . /app
WORKDIR /app
RUN ["dnu", "restore"]
EXPOSE 5004
ENTRYPOINT ["dnx", "project.json", "kestrel"]
```

Build the docker image:
```
cd samples/latest/HelloWeb
docker build -t aspnet-home-helloweb .
```

Create a new `mywwwroot` directory with a new `hello.jpg` file and start the docker container:
```
mkdir mywwwroot
cp wwwroot/image.jpg mywwwroot/hello.jpg
docker run -it -v $(pwd)/mywwwroot:/app/wwwroot -p 5004:5004 aspnet-home-helloweb
```

Now run this is another terminal window to open the `hello.jpg` in a browser:
```
open http://$(boot2docker ip):5004/hello.jpg
```
or just open [http://localhost:5004/hello.jpg](http://localhost:5004/hello.jpg) if you do not use macosx/boot2docker.

While the docker container is still running you can add a text file to `mywwwroot` and open it in a browser:
```
echo "Hello World!" > mywwwroot/foobar.txt
open http://$(boot2docker ip):5004/foobar.txt
```

You can now add/remove/change files in `mywwwroot` without having to restart the docker container.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
