### ISSUE TITLE
dnvm upgrade -Proxy issue

### ISSUE THREAD

**Issue by wbw** [aspnet/Home#576]
The supplied proxy is not used.

Looking at the dnvm.ps1 script reveals that on line 1088 (`$VersionNuPkgOrAlias = Find-Latest $Runtime $Architecture -Feed:$selectedFeed`) the proxy is not supplied to the Find-Latest command. The line should actually read `$VersionNuPkgOrAlias = Find-Latest $Runtime $Architecture -Feed:$selectedFeed -Proxy:$Proxy` so the proxy value is supplied.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
