### ISSUE TITLE
Stuck on the CLA process

### ISSUE THREAD

**Issue by Tragetaschen** [aspnet/Home#577]
@Eilon 

I didn't want to use the PR discussion for that. I used https://cla.dotnetfoundation.org/, selected ASP.NET 5 and filled in my information. I didn't receive any DocuSign mail.

**Comment by Eilon** [comment]
@Tragetaschen the URL should be https://cla2.dotnetfoundation.org/ (not sure why it's cla2 instead of cla, but that's what it is). I'll ask the CLA people why there are two different ones.

**Comment by Tragetaschen** [comment]
I got there by clicking on "Get Involved" at the top of .NET foundation's home page and then on the "contributor license agreement" link in the second paragraph.

**Comment by Eilon** [comment]
Yup, I saw that link and let the CLA folks know. Apparently the two exist because some projects don't have the CLA bot, so they use the "old" CLA page, but projects that *do* use the CLA bot use the "new" CLA2 page. I'm talking to the people who run that site to have them clarify it.

**Comment by Tragetaschen** [comment]
The CONTRIBUTING.md needs updating, too.

**Comment by Eilon** [comment]
Sorry, this was on my TODO list, so I updated it now! https://github.com/aspnet/Home/commit/69ad72371dd1be4e5fc773ec2f79e1b6f79ae7e7#diff-6a3371457528722a734f3c51d9238c13
