### ISSUE TITLE
ASP.NET Core should have an awesome logo

### ISSUE THREAD

**Issue by akamud** [aspnet/Home#579]
Being a .NET developer you might feel a little left out when all the current web frameworks and tools have cool logos and ASP.NET doesn't. When your developers friends come with a notebook full of dev stickers you might feel a little jealous.

But we can change that! 

ASP.NET needs an awesome logo so that we can show our love and respect for the framework, we _must_ have at least one good designer willing to contribute with this.
I know the team has a lot on its plate right now, but maybe we could design a logo with the help of the community?

**Comment by Eilon** [comment]
@coolcsh @shanselman @DamianEdwards - this is in your territory.

**Comment by simonmurdock** [comment]
I would totally have a asp.net sticker on my laptop.

**Comment by akamud** [comment]
Yep @simonmurdock, but ASP.NET itself doesn't have one yet (not that I know of)

**Comment by shanselman** [comment]
ASP.NET probably shouldn't have a logo that is separate from the .NET brand.

On Fri, May 8, 2015 at 4:06 AM, Mahmoud Ali <notifications@github.com>
wrote:

> Yep @simonmurdock <https://github.com/simonmurdock>, but ASP.NET itself
> doesn't have one yet (not that I know of)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aspnet/Home/issues/579#issuecomment-100196029>.
>



-- 
Scott Hanselman
Donate to fight diabetes: http://hnsl.mn/fightdiabetes

**Comment by akamud** [comment]
Agreed @shanselman, but is that old logo still considered to be the .NET logo for *\~~the modern web\~~*?

**Comment by shanselman** [comment]
Good question. @richlander?

On Fri, May 8, 2015 at 10:11 AM, Mahmoud Ali <notifications@github.com>
wrote:

> Agreed @shanselman <https://github.com/shanselman>, but is that old logo
> still considered to be the .NET logo for *~~the modern web~~*?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aspnet/Home/issues/579#issuecomment-100301371>.
>



-- 
Scott Hanselman
Donate to fight diabetes: http://hnsl.mn/fightdiabetes

**Comment by akamud** [comment]
Now that we have an estimate on RC, do we have any update on this?

**Comment by spboyer** [comment]
fsharp.org has an awesome logo, not sure the route that they went; approvals etc to go through but this discussion has surfaced again on twitter by some community members. 

As many of you, i proudly support the frameworks, companies and orgs via t-shirts and stickers on my person and machines.  In the words of my high school art teacher "...words are not art" and unfortunately I do not have a .net or ASP.NET hipster sticker on my MBP.  

If we are looking to get into the places where .NET is not, being the kids in school using bash, zsh, node, php etc., then let's be sure to have to cool swag to go along with the effort being made so far.

Seems silly I know, but it matters.

@shanselman @DamianEdwards @richlander @coolcsh

**Comment by imranbaloch** [comment]
When I started ASP.NET for the first time(in 2006) I used to see this logo, 

![](http://exonya.azurewebsites.net/wp-content/uploads/2012/02/logo_asp.net_201.png)


and ASP.NET team have this logo in forums,

![](http://web.archive.org/web/20130609080915/http://forums.asp.net/Themes/fan/images/roleicons/dff6f773-6732-4cd8-addf-42a8ab367d22.gif)

**Comment by khellang** [comment]
I think .NET is (mostly) covered (see [stickermule](https://www.stickermule.com/user/1070667147/stickers)), though I wouldn't consider any of them _actual logos_.

I agree that it would be nice, even though the name stuck, to disentangle ASP.NET from the .NET brand a bit more. Having a designer come up with alternatives and allow the community to vote, like the F# community did, would be really cool :grin:

**Comment by Eilon** [comment]
@DamianEdwards

**Comment by davidfowl** [comment]
More of a @shanselman issue

**Comment by GuardRex** [comment]
I hope you allow community contributions as well. We could narrow down dozens of community contributions to three or so ... then let those three go head-to-head against Microsoft's art dept. and marketing concepts.

**Comment by stevedesmond-ca** [comment]
Perhaps given the direction of things, it could be a broader .NET Core logo?

**Comment by izhangzhihao** [comment]
# **We DO need an awesome ASP.NET Core logo **

**Comment by jmalarcon** [comment]
Hi everyone:

We've created an [Open Source awesome logo for .NET Core](https://github.com/campusMVP/dotnetCoreLogoPack) and related technologies.

![.NET Core Logo](https://github.com/campusMVP/dotnetCoreLogoPack/raw/master/.NET%20Core/Bitmap%20RGB/NET-Core-Logo_2colors_Boxed_RGB_bitmap_BIG.png)

You should check it out :-)

Hope you like it.

**Comment by Eilon** [comment]
cc @richlander @shanselman @coolcsh regarding logos.

## Note to all: These are not official logos and are not affiliated with Microsoft or the .NET Foundation.

**Comment by jmalarcon** [comment]
Yes, that's the thing and that's what is reflected in the readme.ms file of the repo. Do you want us to put it bigger?

**Comment by Eilon** [comment]
@jmalarcon I just wanted to make sure that folks that saw the logo here saw the same disclaimer. Up to you what to do on your own site 😄

**Comment by IEvangelist** [comment]
# ASP.NET Core (logo worthy)
I can't believe this is an issue. **ASP.NET Core** deserves its own branding. Who originally crafted the .NET Foundation logos - can't someone be like, "hey, we have some more work for you"? I would absolutely love to see an official logo that represents **ASP.NET Core**.

**Comment by vaindil** [comment]
Any chance this has been looked at? An ASP.NET Core logo would be fantastic.

**Comment by leo9223** [comment]
need .net core logo guys :S

**Comment by leo9223** [comment]
So here is the official logos I guess https://docs.microsoft.com/en-us/dotnet/#pivot=docs&panel=getstarted

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.

**Comment by gruth151** [comment]
@akamud me too

**Comment by stamminator** [comment]
How am I supposed to refer to .NET Core in Slack without a recognizable .NET Core logo? By spelling it out, like a barbarian? We're better than this. #justiceForDotNetCore

**Comment by FabriceMk** [comment]
More than 3 years since tis issue was opened but I reiterate the demand of having an official logo.

Especially since .NET Core 2.x, the framework got a lot of traction: 

- The Framework is awesome
- modular
-  cross-platform
- you can run it into containers
- is not associated with the old ASP limitations
- recently MS did an awesome job at giving a new open image towards developers (VSCode, Typescript, Github, Azure DevOps etc...)
- Can be written with awesome C#, one of the few "modern", strongly, statically typed language

It may seem as a detail but when you go to tech conferences, meetup, it's easy to spread my love for VSCode and Typescript with their recognizable logos that stick on my laptop but I am also proud to be an ASP.NET Core developer.
ExpressJS, Rails, Spring, Laravel are not the only one that should get the love on the backend web framework world.
