### ISSUE TITLE
Change default dnx version for VSCode

### ISSUE THREAD

**Issue by ardacetinkaya** [aspnet/Home#581]
First of all this is for Mac OS X; When I run dnx:run command from VSCode the default dnx runtime version is mono(dnx-mono.1.0.0-beta5-11735). The execution command is like;

cd /Users/Arda/HelloVSCode ; /Users/Arda/.dnx/runtimes/**dnx-mono.1.0.0-beta5-11735**/bin/dnx . run

How can I change default behavior of VSCode so that my dnx version can be like;

cd /Users/Arda/HelloVSCode ; /Users/Arda/.dnx/runtimes/**dnx-coreclr-darwin-x64.1.0.0-beta5-11735**/bin/dnx . run

I think there should be some VSCode setting for that. I tried global.json, but can not manage to do what I want. Any solution for that? Or am I just thinking wrong way?

**Comment by tugberkugurlu** [comment]
As far as I know, VS Code looks for the active dnx runtime on the machine.

Try switching the active runtime with `dmvm use <runtime-id> -p`.

**Comment by tugberkugurlu** [comment]
Sorry, `dnvm` not `dmvm` :smile:

**Comment by ardacetinkaya** [comment]
@tugberkugurlu I just tried that. Even I set dnvm version as persistent, when running from VSCode it does not use that runtime. I think somehow "dnx/runtimes/dnx-mono.1.0.0-beta5-11735"(latest mono version) is default for VSCode

**Comment by tugberkugurlu** [comment]
Weird. Did you restart the VS Code after you switch the runtime? It should pick up the active installation.

**Comment by ardacetinkaya** [comment]
No, it did not help. I think this is a bug. And also there is strange issue; when my active runtime is **coreclr** and I restart the VSCode, dnx commands does not appear in Command Pallette. If **mono** is active runtime, dnx commnads appear in Commands.

cc: @davidfowl

**Comment by davidfowl** [comment]
Yea this doesn't work as yet. We're still getting this all up and running.

**Comment by rodfraga** [comment]
Hello, I fix that problem following the next steps on OS X:
1.- after dnvm upgrade, set to dnx 1.0.0-beta4 as default and active by using dnvm use 1.0.0-beta4 -p 
2.- then open vscode, change dependencies to beta4 and test intellisense recognition (works)
2.1- was required to press: cmd + p >reload 
3.- repeat step 1 but to set beta5 as active and default
4.- repete step 2 to beta5 and test
5.- happy coding using vscode with beta5

@rodfraga

**Comment by rhires** [comment]
I submitted this elsewhere I think, but I think that VSCode should keep whatever runtime it's using, unless you explicitly tell it to use another runtime. If the versions don't match the right way, then OmniSharp fails.

**Comment by davidfowl** [comment]
What?

**Comment by davidfowl** [comment]
What omnisharp uses doesn't matter
