### ISSUE TITLE
Override desired environment during publish?

### ISSUE THREAD

**Issue by vsimonian** [aspnet/Home#582]
The new environment feature of the new runtime is fantastic; definitely a huge improvement over the config transforms of before.

However, I've run into a situation where I'm having trouble figuring out a solution. My setup is as follows:
- There are two computers on the same network: a development workstation running Windows 8.1 Pro and a web server running Windows Server 2008 R2 Standard.
- On the server, there are two websites configured in IIS: one for production, and one for staging.
- On the development machine, publish profiles for this particular ASP .NET 5 project are configured to deploy to the server using a mapped network drive.

What I want to do is publish the site to the web server with a "Staging" environment, much like the "Development" environment used when I debug the project locally. I have been able to publish the website over the network to the server, and that works just fine. However, none of the screens in the publish wizard allow me to set a specific environment for a publish profile.

The closest I get is being able to choose between Debug and Release configurations, neither of which has any effect on the environment. If I were to set an environment variable on the server, it would also affect the production website, which naturally wouldn't be desirable. Neither am I aware of a way to set the environment variable per website in IIS, and that I feel would also undermine the independence of the new runtime by making it reliant on an IIS setting. And, as I understand it, the debug profiles under the project settings are strictly for local debugging. 

So, essentially what I'm looking for is a way to set the environment for a particular publish profile, similar to setting environment variables in debug profiles. However, I don't see any way in the Visual Studio GUI to automate this process. Is there a task I should create? Is there an option hidden away somewhere that I've missed? Perhaps another way around all this that I'm unaware of?

I apologize in the case there is a well-documented solution: my google-fu isn't top notch, but I did spend roughly an hour trying to find the solution, so the effort was there. :smile: The closest I got was [this comment on issue #534](534#issuecomment-98514050), which, if it was answered, my dumb head wasn't able to understand.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
