### ISSUE TITLE
Cannot resolve IServiceCollection.  It exists in both packages

### ISSUE THREAD

**Issue by Chiliyago** [aspnet/Home#584]
I cannot seem to resolve this.  Hoping for some advice.

**project.json**

```json
  "dependencies": {
    "Microsoft.AspNet.Server.IIS":"1.0.0-beta5-11747",
    "Microsoft.AspNet.Server.WebListener":"1.0.0-beta5-12133",
    "Microsoft.AspNet.Mvc":"6.0.0-beta5-13822",
    "ServiceLibrary": "",
    "System.Threading":"4.0.10-beta-22907",
    "System.Threading.Thread":"4.0.0-beta-22907",
    "System.Globalization": "4.0.10-beta-22907",
    "Microsoft.Framework.DependencyInjection.Interfaces":"1.0.0-beta5-11289",
     "Microsoft.Framework.DependencyInjection.Abstractions":"1.0.0-beta5-11345",
    "Microsoft.AspNet.Http":"1.0.0-beta5-11475"
  },
```

```
Severity	Code	Description	Project	File	Line
Error	CS0433	The type 'IServiceCollection' exists in both 'Microsoft.Framework.DependencyInjection.Abstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' and 'Microsoft.Framework.DependencyInjection.Interfaces, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'	AspNetMVC.DNX 4.5.1	C:\_Git\Mvc\WebApplication1\src\WebApplication1\Startup.cs	15
```

**Comment by Eilon** [comment]
Sounds like you might be using an old runtime (DNX) with newer NuGet packages. Please update to the latest runtime, or switch back to beta4 NuGet packages.

**Comment by davidfowl** [comment]
Your project.json has both:

```
 "Microsoft.Framework.DependencyInjection.Interfaces":"1.0.0-beta5-11289",
     "Microsoft.Framework.DependencyInjection.Abstractions":"1.0.0-beta5-11345",
```

**Comment by Eilon** [comment]
Oh yeah, or that :smile:

**Comment by Eilon** [comment]
`.Abstractions` is the newer one BTW.

**Comment by Chiliyago** [comment]
I updated the DNX and cleared out my packages and finally got it to compile. Now when I start the web server I get this error:
System.InvalidOperationException: No service for type 'Microsoft.Framework.Runtime.IApplicationEnvironment' has been registered.
   at Microsoft.Framework.DependencyInjection.ServiceProviderExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Framework.DependencyInjection.ServiceProviderExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.AspNet.Hosting.WebHostBuilder.Build()
   at Microsoft.AspNet.Hosting.Program.Main(String[] args)

**Comment by Eilon** [comment]
Can you share a repro project (put it up on GitHub or something).

**Comment by davidfowl** [comment]
@Chiliyago did you update the DNX while VS was open? What's in the global.json?

**Comment by Chiliyago** [comment]
Posted my project here.  Thanks for the help.  Be kind :)
https://github.com/Chiliyago/LearnDNX.git

**Comment by Chiliyago** [comment]
I am not sure about updating DNX while VS was open. What are the consequences if I did?

**Comment by Eilon** [comment]
Hmm that solution seems rather complex: there are several projects with the same name, copies of the MVC source code, and lots of global.json files. In particular, the global.json files seem to mention `beta4` yet the project.json files seem to be pointing to `beta5` packages. Because there are so many projects in there it's not clear to me which one you're trying to run. Can you simplify the solution to a simple repro?

**Comment by weitzhandler** [comment]
I'm experiencing the same issue.
And I'm reading @Eilon's [post](https://github.com/aspnet/Home/issues/584#issuecomment-100659990):
>Sounds like you might be using an old runtime (DNX) with newer NuGet packages. Please update to the latest runtime, or switch back to beta4 NuGet packages.

And I feel it might be the solution to my issue as well, but how do I update the DNX version? Here's the `frameworks` snippet from my *project.json* file:

    "frameworks": {
        "dnx451": { },
        "dnxcore50": { }
    },

**Comment by weitzhandler** [comment]
In reference to @Eilon's [post](https://github.com/aspnet/Home/issues/584#issuecomment-100659990):
>Sounds like you might be using an old runtime (DNX) with newer NuGet packages. Please update to the latest runtime, or switch back to beta4 NuGet packages.

I'm experiencing the same issue.
I've updated all the NuGet packages on a fresh ASP.NET 5 WebAPI project, and I see a couple of the following warnings in the errors list:

>
Warning	MissingPackage
Type Microsoft.Framework.DependencyInjection.IServiceCollection exists in the package: Microsoft.Framework.DependencyInjection.Interfaces 1.0.0-beta4, Supported frameworks: DNX 4.5.1;DNXCore 5.0;.NETFramework 4.5;.NETPortable-net451+win81+wpa81	[project name].DNX Core 5.0
D:\Users\\[username]\OneDrive\Documents\Visual Studio 2015\Projects\\[project name]\src\\[project name]\Startup.cs	21

I believe updating the DNX version could be a solution, but how do I do this?

Here the `frameworks` snippet from my *project.json* file:

    "frameworks": {
        "dnx451": { },
        "dnxcore50": { }
    },

**Comment by kanaifu** [comment]
Exactly the same mistake. I installed the latest final Visual Studio 2015 Professional and all the libraries are still beta?
EntityFramework 7-beta, Identity, etc. 
Are these and when these are going RTM? We need these for a project that we have (obviously mistakenly) tagged as AngularJS + Web Api 2 on VS 2015. We should have worked with VS 2013.

But apart from that, is there any guideline or workaround of getting these libraries working together?

**Comment by davidfowl** [comment]
> Exactly the same mistake. I installed the latest final Visual Studio 2015 Professional and all the libraries are still beta?
EntityFramework 7-beta, Identity, etc. 
Are these and when these are going RTM? 

Take a look at the roadmap here https://github.com/aspnet/Home/wiki/Roadmap.

> But apart from that, is there any guideline or workaround of getting these libraries working together?

The general guidance for making things work together is to use versions from the same release e.g. beta5. Make sure the dnx version in global.json matches the packages.

**Comment by weitzhandler** [comment]
@kanaifu 

You can use VS2015 but with ASP.NET 4 MVC 5.
VS RTM has nothing to do with vNext and EF 7 release dates. And this was clarified in the various announcement blogs and discussions.
