### ISSUE TITLE
Changing default password requirements?

### ISSUE THREAD

**Issue by russjr08** [aspnet/Home#586]
I can't seem to figure out how to change the default password requirements in ASP.NET 5... I'm sure they're somewhere, but I'm lost.

Are the defaults defined in the library now, or are they in a hidden project file somewhere?

**Comment by matt-podsiadlo** [comment]
I assume you are talking about ASP.NET Identity membership. If so, you can change the default password options by configuring the Identity service options inside ConfigureServices of Startup.cs, e.g.:

```
services.Configure<IdentityOptions>(options => options.Password = new PasswordOptions()
{
   RequireUppercase = false,
   RequireDigit = false,
   RequireNonLetterOrDigit = false,
   RequiredLength = 6
});
```

Check out the PasswordOptions implementation to see what the default values are:https://github.com/aspnet/Identity/blob/ab43154577fe126ef531bb7a11b5eaa03add7bbf/src/Microsoft.AspNet.Identity/PasswordOptions.cs

**Comment by russjr08** [comment]
Thanks Matt! This is perfect.
