### ISSUE TITLE
Generating a binary for a console application

### ISSUE THREAD

**Issue by deevus** [aspnet/Home#590]
How do I generate a binary for a console application?

`dnu build` generates a dll. I would like an executable.

project.json:
```json
{
    "dependencies": {
        "xunit": "2.1.0-*",
        "xunit.runner.dnx" : "2.1.0-*"

    },
    "commands": {
        "ConsoleApplication": "ConsoleApplication",
        "test": "xunit.runner.dnx"
    },
    "frameworks": {
        "dnx451": { },
        "dnxcore50": {
            "dependencies": {
                "System.Console": "4.0.0-beta-22816",
                "System.Collections": "4.0.10-beta-22816",
                "System.Linq": "4.0.0-beta-22816"
            }
        }
    }
}
```

Program.cs:
```csharp
// A Hello World! program in C#. 
using System;
using System.Linq;

public class Program 
{
    static void Main() 
    {
        Console.WriteLine("Hello World!");
        
        var array = new [] {1, 2, 3, 4, 5, 6, 7, 8, 9, 10};
        foreach (int i in array.Where(i => i > 5)) {
            Console.WriteLine(i);
        }
    }
}
```

**Comment by mudnug** [comment]
I'm not sure if this will help you much, but it looks like a DLL is produced, because this improved the opportunity for it to be executed across platforms. Then dnx.exe can be used to "launch" the DLL on Windows.

**Comment by davidfowl** [comment]
@mudnug is on the mark. There's no more managed exe that you double click. There's always a native host. Check out these presentations:

- http://channel9.msdn.com/Events/Build/2015/2-687
- http://channel9.msdn.com/Events/Build/2015/2-726

**Comment by davidfowl** [comment]
Also http://channel9.msdn.com/Events/Ignite/2015/BRK4703 - This talk actually will show you what you want to do.

**Comment by deevus** [comment]
@davidfowl @mudnug I'll watch the talk but for future users and because I can't watch it now, what command do I run to execute the dll? :)

**Comment by davidfowl** [comment]
run `dnu publish --no-source --out somepath`. It'll give you a runnable cmd file.

**Comment by deevus** [comment]
Thank you @davidfowl
