### ISSUE TITLE
How should one account for demands for Properties.Settings.Default?

### ISSUE THREAD

**Issue by mudnug** [aspnet/Home#591]
I'm referencing a third-party DLL that reads configuration from Properties.Settings.Default.DefaultHostName. How do I configure this in my ASP.NET 5 application so that their call to Properties.Settings.Default.DefaultHostName doesn't return null to their DLL?

Essentially, I haven't found any way to set the configuration, like
    `Configuration.Set( "DllName:Properties:Settings:setting:DefaultHostName:value", "Sample" );`
and have even wondered about dropping an XML file somewhere that might be read in, but can't think of where I would put that. In the nuget?

The application has to make the values available so that the third-party dll doesn't crash when it is looking for them. The DLL is using the traditional settings files as described at https://msdn.microsoft.com/en-us/library/aa730869(v=vs.80).aspx

**Comment by davidfowl** [comment]
That's a tricky one and I don't think it'll just work unfortunately (even in dnx451).
