### ISSUE TITLE
Using IDbConnection

### ISSUE THREAD

**Issue by dgee2** [aspnet/Home#593]
Hi,
I'm needing to include support for Sybase ASE in an ASP.Net 5 project. The driver returns a System.Data.DbConnection. Will it still be possible to use this driver with the new dnx way of doing things?

**Comment by Eilon** [comment]
@divega @rowanmiller

**Comment by rowanmiller** [comment]
If you are targeting the full .NET Framework (net451) in your application then yes, you can use any existing .NET components. If you want to target .NET Core (dnxcore50) then the provider would need to be compiled against .NET Core (including System.Data.Common which contains DbConnection etc.).

BTW you didn't mention Entity Framework in the question, so I was assuming you don't want to use Sybase with EF. If you do, then that would require an EF7 provider for Sybase.

**Comment by dgee2** [comment]
Yes we're using Dapper as it was significantly faster than EF5/6 when we were testing (has this changed in 7?)

To confirm my understanding of what you're saying, if you need to include a library that isn't built against

**Comment by dgee2** [comment]
(sorry a phone, github and a train don't work well...)
... .net core, you can only reference  dnx451 and must include the relevant framework Dependency in the dnx451 section of the project.json

**Comment by rowanmiller** [comment]
@dgee2 that is correct. If a version of Dapper and the Sybase provider became available that targets .NET Core then you would be able to target dnxcore50, but in the meantime you would only be able to use those components when targeting net451 (or other version of .NET that they support).

**Comment by davidfowl** [comment]
Dapper does indeed work on .NET Core now

**Comment by dgee2** [comment]
Just in case anyone else bumps into this, we ended up wrapping the ASE driver in a nuget package targetting dnx451 and adding a dependency in our project.

Yes Dapper worked on .net Core straight out of the box. The issue is very much with the Sybase provider

**Comment by gsainagendraprasad** [comment]
Can you please provide more details on what you have done to support sybase Ase  (Sybase.AdoNet4.AseClient). How did you wrap ASE driver in a nuget package and targeting dot net framework 4.X ??

**Comment by senseibaka** [comment]
Hi guys, if you're still looking for a .net core ASE driver, we've recently developed one: https://github.com/DataAction/AdoNetCore.
