### ISSUE TITLE
.net40 Target Framework- which moniker to use?

### ISSUE THREAD

**Issue by patrickjamesbarry** [aspnet/Home#594]
I am creating a c# library that needs to support .net40. What moniker should I use in the project.json?

**Comment by smudge202** [comment]
Have you tried `net40`?

**Comment by patrickjamesbarry** [comment]
I have and was able to build the library, but when I tried to consume the library in a console app, and run it, I got an error. The weird thing is that everything built without errors.  Full details can be found here: http://stackoverflow.com/questions/30176432/c-sharp-class-library-using-dnx-will-not-run-without-dnx451

It made me wonder if .net40 is not supported?  Maybe i can still create nuget packages that support .net40, but I just cannot run them on DNVM without the dnx451 being included in the frameworks section?

**Comment by davidfowl** [comment]
There's a difference between what you can run on and what you can compile for. The dnx is both a project system and a runtime environment. The project system lets you build class libraries for other target frameworks including net40, net45, some PCL profiles etc and it can produce a nuget package. The runtime only lets you run on dnx4* or dnxcore50 depending on what dnx you ran.
