### ISSUE TITLE
Dnu wrap fails to wrap .csproj file, when references are not found.

### ISSUE THREAD

**Issue by patrickjamesbarry** [aspnet/Home#595]
I can understand why this happens, but was hoping there a was a flag I could use to ignore unresolved references in the csproj file.  This feature doesn't look like it exists.

**Comment by davidfowl** [comment]
Why would you want to ignore unresolved things? Are you not using the reference?

**Comment by patrickjamesbarry** [comment]
Fair enough question. Its easy to just clean up the references in a csproj. However, I have inherited a code base in which the build process actually generates the the csproj files.  Instead of troubleshooting and changing the way the build script currently works, I was hoping to just work around it.

**Comment by davidfowl** [comment]
Delete the reference to the csproj because it isn't working anyways?

**Comment by patrickjamesbarry** [comment]
The reference only comes back during next build, due to build script.

**Comment by davidfowl** [comment]
Turns out this is pretty common :smile:

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
