### ISSUE TITLE
CLA link in Home/Contributing points to outdated MSOpenTech site

### ISSUE THREAD

**Issue by nblumhardt** [aspnet/Home#597]
Howdy all,

I followed the CLA link in:

https://github.com/aspnet/Home/blob/release/CONTRIBUTING.md#contributing-code-and-content

...but this landed me at the _MSOpenTech CLA_, **not** the _.NET Foundation_ one. (The DNF Bot caught me, and someone from Microsoft kindly pointed out my mistake :-))

Cheers,
Nick

**Comment by Tragetaschen** [comment]
That's already fixed in dev (69ad723), which is also Home's default branch since recently.

**Comment by nblumhardt** [comment]
@Tragetaschen ah I see: the problem is actually in https://github.com/aspnet/Home/blob/dev/README.md (note this is on the `dev` branch).

The `contributing` link is pointing into the `release` branch directly, rather than using GitHub wiki links:

```markdown
Check out the [contributing](https://github.com/aspnet/Home/blob/release/CONTRIBUTING.md) page
```

should probably be:

```markdown
Check out the [[contributing|CONTRIBUTING]] page
```

**Comment by Eilon** [comment]
I fixed https://github.com/aspnet/Home/blob/dev/README.md. I'm not going to fix the actual `release` branch in the Home repo because we plan on getting rid of that anyway. Hopefully all the "visible" information on contributions all points to correct CLAs now. Sorry for the confusion!
