### ISSUE TITLE
Managing Versions across projects

### ISSUE THREAD

**Issue by patrickjamesbarry** [aspnet/Home#599]
What are the guidelines around versioning a group of projects. I see the project.json file has the version attribute in it.  However, if I want to change the version id once, across a group of projects, how can I do this?  
The docs reference Shared Files... "To share code, like shared assembly info, you would create a common project with the shared code files referenced in the shared section. After that any project that references your common project will have the files compiled into it as if it was source in their project." 

So I was thinking I would create a shared project and add a AssemblyInfo.cs to manage version ids.  However, the group of projects would only share <Major>.<Minor> part of the version and the .<Build#> would differ through out.  How is this accomplished with DNX?  Basically, externalize the version id and maybe just reference it as a variable in the project.json. Nuget does this with <version>$version$</version>.   Is the AssemblyInfo.cs totally gone now and represented in the project.json?

**Comment by davidfowl** [comment]
There's a current issue open on the dnx for adding the ability to inherit `project.json` versions (https://github.com/aspnet/dnx/issues/1100). Today there's no automatic way to do this other than having your build script update the `project.json` file manually. That said, you can still use a shared assembly info and opt out of auto versioning via the `project.json` version attribute. You're packages will be out of sync with your assembly version in that case but it'll be no worse than it is today.

We'll need to bring back the versioning ability likely in `global.json` and giving you the ability to override tokens in project.json via flags passed to `dnu`. This isn't planned right now.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
