### ISSUE TITLE
can I use sql server from an app using ef 7 from non windows os?

### ISSUE THREAD

**Issue by lucamorelli** [aspnet/Home#603]
If I remeber well, the actual sql server driver is not part of ef, but for non windows platform is part of the mono runtime.
It is working fine? A rock solid sql server driver is required to move apps that already use sql server.

**Comment by Eilon** [comment]
@divega @rowanmiller

**Comment by rowanmiller** [comment]
You can use SQL Server when running on Mono at the moment. There are some bugs/limitations in the SQL Client implementation in Mono (e.g. you can't use secure connections).

Long term, the System.Data.SqlClient NuGet package running on cross platform .NET Core will be the best answer for a good stable provider. That's not quite ready to use though.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
