### ISSUE TITLE
dnu restore fails to complete with an node eacces error 3

### ISSUE THREAD

**Issue by joeizang** [aspnet/Home#604]
installed aspnet mono and everything on my ubuntu destop with no issues. I used yo-aspnet to scaffold a project whic worked as well. when I tried to do dnu restore it fails with the following error: 

59 silly install resolved     _resolved: 'https://registry.npmjs.org/grunt-bower-task/-/grunt-bower-task-0.4.0.tgz',
59 silly install resolved     readme: 'ERROR: No README data found!' } ]
60 info install grunt@0.4.5 into /home/joe/Projects/ProdigeeCMS
61 info install grunt-bower-task@0.4.0 into /home/joe/Projects/ProdigeeCMS
62 info installOne grunt@0.4.5
63 verbose installOne of grunt to /home/joe/Projects/ProdigeeCMS not in flight; installing
64 info installOne grunt-bower-task@0.4.0
65 verbose installOne of grunt-bower-task to /home/joe/Projects/ProdigeeCMS not in flight; installing
66 warn locking Error: EACCES, open '/home/joe/.npm/_locks/grunt-90747978a1075711.lock'
66 warn locking  /home/joe/.npm/_locks/grunt-90747978a1075711.lock failed { [Error: EACCES, open '/home/joe/.npm/_locks/grunt-90747978a1075711.lock']
66 warn locking   errno: 3,
66 warn locking   code: 'EACCES',
66 warn locking   path: '/home/joe/.npm/_locks/grunt-90747978a1075711.lock' }
67 verbose stack Error: Attempt to unlock /home/joe/Projects/ProdigeeCMS/node_modules/grunt, which hasn't been locked
67 verbose stack     at unlock (/usr/lib/node_modules/npm/lib/utils/locker.js:66:11)
67 verbose stack     at cb (/usr/lib/node_modules/npm/lib/install.js:1015:5)
67 verbose stack     at /usr/lib/node_modules/npm/lib/install.js:1019:20
67 verbose stack     at /usr/lib/node_modules/npm/lib/utils/locker.js:40:9
67 verbose stack     at cb (/usr/lib/node_modules/npm/node_modules/lockfile/lockfile.js:149:38)
67 verbose stack     at /usr/lib/node_modules/npm/node_modules/lockfile/lockfile.js:177:38
67 verbose stack     at Object.oncomplete (fs.js:108:15)
68 verbose cwd /home/joe/Projects/ProdigeeCMS
69 error Linux 3.13.0-32-generic
70 error argv "node" "/usr/bin/npm" "install"
71 error node v0.10.38
72 error npm  v2.9.1
73 error Attempt to unlock /home/joe/Projects/ProdigeeCMS/node_modules/grunt, which hasn't been locked
74 error If you need help, you may report this error at:
74 error     https://github.com/npm/npm/issues
75 verbose exit [ 1, true ]

copied this from the error log. I did dnu restore without sudo so could that be the issue. When I try sudo I get that dnu is not recognized which is understandable being that dnu is not setup for the admin account.

**Comment by imkheong** [comment]
@joeizang I had similar problem which I got the solution from this [link](https://aralbalkan.com/scribbles/npm-install-g-please-try-running-this-command-again-as-root-administrator/).

<code>sudo chown -R $USER {path to your code folder}</code>

Also make sure that grunt, npm and bower is running correctly. <code>dnu restore</code> is calling each of the 'tasks' defined in scripts property of project.json. It appear that grunt is having an issue to run the task. Try running <code>grunt default</code> to check if grunt is working.

If not, make sure you install grunt with <code>npm install -g grunt-cli</code> and <code>npm install grunt</code>.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
