### ISSUE TITLE
dnvm upgrade exception: Access to path \temp denied

### ISSUE THREAD

**Issue by GuardRex** [aspnet/Home#605]
I work in CoreCLR x64, but I keep the CLR x86 runtime to make VS happy. When upgrading, I upgrade the CLR x86 first, then I upgrade CoreCLR x64, which leaves CoreCLR x64 DNX as my active DNX. I started with ...
```
dnx-clr-win-x86.1.0.0-beta5-11744
dnx-coreclr-win-x64.1.0.0-beta5-11744
```
I'm attempting to run `dnvm upgrade -r clr -arch x86 -u` to get CLR x86 done first (in this case going to 11760). The exception forces me to run `dnvm upgrade` twice in order to get past a path access exception to the temp folder. Then, I use `dnvm upgrade -r coreclr -arch x64 -u`, which works fine.

Should the upgrade command run on the first shot? ... or should I be using a `dnvm install` command as the exception indicates.
dnvm version: 1.0.0-beta4-10356
![capture7](https://cloud.githubusercontent.com/assets/1622880/7641808/cbb8ef2c-fa51-11e4-83d7-faec08d1e788.png)

**Comment by softgandhi** [comment]
+1. I am also facing the same issue

**Comment by GuardRex** [comment]
@softgandhi With DNX going away in just a few weeks, we won't have this particular issue cropping up again. I think I fixed it with a newer `dnvm` at the time.
