### ISSUE TITLE
Richer support for cookie handling in IResponseCookies

### ISSUE THREAD

**Issue by mahdi-ninja** [aspnet/Home#606]
IResponseCookies has only "add" and "delete" support which is not enough. I believe there should be support for reading current response cookies and modifying them.
For example in my case, I need to develop a Middleware which encrypts cookies and decrypts them back on server but I couldn't find any way around it.

**Comment by Tratcher** [comment]
Parsing, editing, and re-writing cookies is a dubious business. There is a standard cookie format, but it is not well followed. This can lead to round-tripping errors that corrupt the data.

Where is this cookie data coming from?

If the data is coming from your own application code you should deal with the encryption at that layer. The CookieAuthenticationMiddleware for example issues and reads encrypted cookies. However, it encrypts the cookie data before adding it to the response, and decrypts after reading it from the request. It does not attempt to modify any existing values in the request or response.

If instead you're trying to augment someone else's cookies, consider having your middleware replace/wrap the `IRequestCookiesFeature` and `IResponseCookiesFeature`. On the response you would intercept calls to `Add` and do the encryption before the cookie components are assembled into a full header value. This avoids problematic re-parsing later. On the request you could wait to do the decryption until the value was requested without trying to re-write the underlying header.

**Comment by davidfowl** [comment]
> If instead you're trying to augment someone else's cookies, consider having your middleware replace/wrap the IRequestCookiesFeature and IResponseCookiesFeature. On the response you would intercept calls to Add and do the encryption before the cookie components are assembled into a full header value.

Maybe an entropy sample?

**Comment by mahdi-ninja** [comment]
Thanks. 
Replacing IRequestCookiesFeature and IResponseCookiesFeature sounds great. I couldn't find a way to do that, so I thought that's off limits.
Could you please point out how I can replace? An entropy sample is great but a hint would work too!

**Comment by mahdi-ninja** [comment]
Thanks. Second option (replacing IRequestCookiesFeature and IResponseCookiesFeature) is exactly what I need.
The problem is that I'm not sure how I should do that and I couldn't find any sample.
Here's what I tried:
```csharp
    public class MyMiddleware
    {
        RequestDelegate _next;
        public MyMiddleware(RequestDelegate next) { _next = next; }

        public async Task Invoke(HttpContext context)
        {
            context.SetFeature<IRequestCookiesFeature>(new MyRequestCookiesFeature());
            context.SetFeature<IResponseCookiesFeature>(new MyResponseCookiesFeature(context.Response.Headers));

            await _next(context);
        }
    }
```
This works fine for response cookies but I can't access request cookies. In fact my Reparse method for my custom implementation of IRequestCookiesFeature.Cookies is never being called.

It seems that at this point it's too late to set IRequestCookiesFeature of the HttpContext and I should hook it somewhere else.

**Comment by Tratcher** [comment]
SetFeature should be correct.  Make sure you have the pipeline ordering correct, i.e. you want to put this early in the application before anybody works with cookies.

Here's the normal code for reference:
https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.AspNet.Http/Features/RequestCookiesFeature.cs (Ignore the first two constructors, those are for unit testing)
https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.AspNet.Http/Features/ResponseCookiesFeature.cs

**Comment by mahdi-ninja** [comment]
Thanks Tratcher. I thought that Reparse should be called automatically but according to your code, I should've called it myself. Now it works like a charm.

The only issue is that I can't reference  `FeatureReference<IHttpRequestFeature>` in my code (in 1.0.0-beta4 this struct seems to be internal), so I can't access request headers like you did (using `_request.Fetch(_features).Headers`).
My workaround was passing request headers to my custom `IRequestCookiesFeature` constructor.

Now my question is that in your implementation, you get request headers every time getter of `Cookies` is called. Why is this necessary? Do the reference to request headers collection change during pipeline processing?

**Comment by Tratcher** [comment]
FeatureReference is public in Beta5, but it's just an optimization, you can access the IFeatureCollection directly.

We try not to cache any data across operations because we want the app to be able to update anything in the request, even the header collection. Where we do cache, we validate that nothing has changed underneath us before using the cached data.  That's exactly what FeatureReference is for actually.  In that spirit, consider wrapping the existing IRequest/ResponseCookiesFeature (or the default Request/ResponseCookieFeature if none) rather than just replacing it.  There's no reason you should re-implement / copy redundant functionality, you just need to wrap it and add your own behavior on top. E.g. if we implement #42 using the same strategy, we'd want our features to layer.

**Comment by mahdi-ninja** [comment]
The reference to `RequestCookiesCollection` class is hard coded in `RequestCookiesFeature`, so if I wrap RequestCookiesFeature, I still can't change its underlying `IRequestCookiesCollection` and of course I can't use DI to change it either.
Moreover there's no virtual method or protected field in either of these classes, so I can't change their behavior by inheriting from them.
What am I missing here? How should I reuse existing behavior?

**Comment by Tratcher** [comment]
Look at IRequestCookiesFeature:
```C#
    public interface IRequestCookiesFeature
    {
        IReadableStringCollection Cookies { get; set; }
    }
```
If you're wrapping an existing implementation of IRequestCookiesFeature you don't need to deal with RequestCookieCollection directly, you just need to wrap the returned IRedableStringCollection. Most of the operations would be pass-through, but for Get you would decrypt the result before returning it.

**Comment by mahdi-ninja** [comment]
Thanks Tratcher.

I know this probably won't change anything, so just out of curiosity, why don't you implement methods as virtual?
Isn't it a better solution to just inherit from the default classes to change their behaviors with a simple override method?
Writing a wrapper class with a whole lot of pass-through operations to change a minor feature seems like an overkill anyway.

**Comment by Tratcher** [comment]
Composition. If two or more middleware want to augment the same feature they can't just derive from the default implementation, they have to wrap whatever came before them.  Yes it's a little more work, but it's a lot more powerful.

**Comment by mahdi-ninja** [comment]
Thanks, it makes sense and probably means that my current implementation (wrapping default classes) is not the right way.
So, I assume that I should get current `IRequestCookiesFeature` and `IResponseCookiesFeature` using `HttpContext.GetFeature<T>` and wrap those features. right?
I tried following code and `currentRequestCookieFeature` and `currentResponseCookiesFeature` are always `null`.

```csharp
    public class MyMiddleware
    {
        private readonly RequestDelegate _next;
        public MyMiddleware(RequestDelegate next) { _next = next; }

        public async Task Invoke(HttpContext context)
        {
            var currentRequestCookieFeature = context.GetFeature<IRequestCookiesFeature>();
            var currentResponseCookiesFeature = context.GetFeature<IResponseCookiesFeature>();

            await _next(context);
        }
    }
```

What am I missing here?

**Comment by Tratcher** [comment]
Yes, get the current one and wrap it. If the current one is null, only then do you new up the default and wrap it.  HttpRequest/Response only create the defaults when you first access the cookies properties. See: https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.AspNet.Http/DefaultHttpRequest.cs#L48
