### ISSUE TITLE
Error installing the dnx 1.0.0-beta4

### ISSUE THREAD

**Issue by Miguel-ezh** [aspnet/Home#609]
I currently have the dnx version 1.0.0-beta5-11781 and when I try to install the beta4 version I get this error:

    dnvm install 1.0.0-beta4
    Downloading dnx-mono.1.0.0-beta4 from https://www.myget.org/F/aspnetvnext/api/v2
    dnx-mono.1.0.0-beta4 was not found in repository https://www.myget.org/F/aspnetvnext/api/v2

I think that its because my NuGet feed is pointing to the new version of the dnx, I read the Wiki article https://github.com/aspnet/Home/wiki/Configuring-the-feed-used-by-dnu-to-restore-packages, but this is for the dnu packages, I need to do something else?

**Comment by davidfowl** [comment]
Did you set the DNX_FEED environment variable?

**Comment by Miguel-ezh** [comment]
Perfect!!!! that was the problem, thanks @davidfowl
