### ISSUE TITLE
Add system requirements checking to kvm script.

### ISSUE THREAD

**Issue by xplicit** [aspnet/Home#61]
kvm has a minimal requirements for .net version and powershell version. It should check these versions at start of the script, and if the version requirement is not met stop executing and write error message which says that user must install proper software. (For example, "you must install Powershell v4.0 or later")

Without these checks script halts with an error message (see #20) which is difficult to diagnose and find a way to resolve it.

System checks, that must be done:
windows platform:  .NET 4.5.1, Powershell 4.0
linux platform: mono version 3.4.1

**Comment by danroth27** [comment]
Closing for now. Please file any additional feedback on KVM on the [KVM](https://github.com/aspnet/kvm) repo.
