### ISSUE TITLE
What's equivalent of ThreadPool.SetMinThreads on dnxcore50?

### ISSUE THREAD

**Issue by tugberkugurlu** [aspnet/Home#614]
[`ThreadPool.SetMinThreads`](https://msdn.microsoft.com/en-us/library/system.threading.threadpool.setminthreads%28v=vs.110%29.aspx?f=255&MSPPError=-2147217396) API is not available on dnxcore50. What is equivalent of this on dnxcore50?

**Comment by Daniel15** [comment]
Core CLR still has SetMinThreads: https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Threading/ThreadPool.cs#L1375

**Comment by davidfowl** [comment]
@Daniel15 Just because it's in CoreCLR doesn't mean it's exposed in the contract packages.

**Comment by davidfowl** [comment]
This belongs on https://github.com/dotnet/corefx
