### ISSUE TITLE
Cannot find dnx-mono.1.0.0-beta4

### ISSUE THREAD

**Issue by onatm** [aspnet/Home#616]
I have an Ubuntu 14.04x64 box in DigitalOcean. I installed everything by following [Getting Started](https://github.com/aspnet/Home/blob/dev/GettingStartedDeb.md) wiki page.

You can see the result of "**dnvm list**" command here:

![capture](https://cloud.githubusercontent.com/assets/802299/7672354/52554b68-fcf8-11e4-9a27-585243800509.PNG)

When i run "**dnvm use 1.0.0-beta4**", i get the following error message:

**Cannot find dnx-mono.1.0.0-beta4, do you need to run 'dnvm install 1.0.0-beta4'?**

PS: Mono version is 4.0.1

**Comment by ryan-developer** [comment]
The problem is that the nuget package containing the runtime is never unpacked (without unzip installed first). I ran into the same issue on a vultr instance with the same Ubuntu distro installed.

The following works for me:

install unzip - sudo apt-get install unzip - then run dnvm upgrade

**Comment by onatm** [comment]
@ryan-developer thank you! :dancer:
