### ISSUE TITLE
.xporj files can't be found

### ISSUE THREAD

**Issue by Juddling** [aspnet/Home#617]
I couldn't open the solution in VS 2015 RC:

C:\git\Home\samples\ConsoleApp\ConsoleApp.xproj : error  : The project file cannot be found.
C:\git\Home\samples\HelloMvc\HelloMvc.xproj : error  : The project file cannot be found.
C:\git\Home\samples\HelloWeb\HelloWeb.xproj : error  : The project file cannot be found.

**Comment by Eilon** [comment]
You can just open the `project.json` file and VS will create the xproj file. These "getting started" samples are meant to demonstrate the simplest possible projects and can be used from both the command line and VS.

**Comment by Juddling** [comment]
Okay, thanks. Shouldn't the .sln file be fixed or removed if opening the `project.json` files are the intended way to open/edit is VS?

**Comment by Eilon** [comment]
Oh duh my bad! A while back we didn't have an SLN/xproj at all, then we added them, but then they all got broken! I'll try to fix it this afternoon. Sorry about that!

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
