### ISSUE TITLE
Getting started with VS 2015 RC and docker deploynment

### ISSUE THREAD

**Issue by pgrm** [aspnet/Home#619]
Hi, I've spent yesterday many hours checking how hard it would be to move my current  ASP.NET MVC 4 application to MVC 6. The application is already running inside a docker container, with mono, so I've figured, moving to something new cross-platform wouldn't be that hard. Turned out it was.
1. Creating a project with the yeoman generator, I could easily run it in VS 2015. But when I started adding code, VS was suggesting me to reference libraries from the GAC (which I've later found in some GitHub issue, it shouldn't) In order to stop using the GAC, I removed dnx451 from the project.json and now, everything was broken. I was getting over 2,000 errors saying, that I'm missing `System.Object`, `System.Void` and other simple types. I guess, from there on, when I tried adding random nuget packages, like `Microsoft.NETCore` I just made it worse.
2. This time I created a project from VS 2015, I couldn't choose as my framework .Net Core, just 4.5.x or 4.6. I went with 4.6 (was that a mistake?) and everything worked at first. I've afterwards set up a docker image, based on asp.net's docker image, to build my test application, but was getting ultimately the error that `Kestrel` was missing. I've added `Kestrel` as a dependency from nuget and I got again the same 2,000 errors about simple types missing. On top of those errors, is btw written that `Kestrel` couldn't be found.

The version I was using was `beta4`. I've tried changing it also to `beta5`, but probably screwed up something so that didn't work either. I've installed Visual Studio 2015 RC only yesterday and didn't have any K-runtime, DNVM or anything else installed before. I'm using Windows 8.1 with all updates installed.

Ultimately I started to believe, it's just not  supposed to work yet. Maybe it's a bug or yet missing support in Visual Studio 2015 RC? Or I've missed a big blog post shouting at me - This is how you do it! - and because of that, did something terribly wrong.

Anybody any thoughts for me?

**Comment by davidfowl** [comment]
Big learning curve here. Porting an ASP.NET 4x application to ASP.NET 5 isn't trivial and there are several things that will bite you when trying to port. Let me recommend a 2 stage approach (assuming you want to go through with this):

1. Convert your application to use `project.json` and remove `dnxcore50`
2. Once you port your application to ASP.NET, then port it to `dnxcore50`.

The errors you get about missing System.Void and System.Object are coming from the `dnxcore50` target framework. If you look closely at the errors inside visual studio within the project column, you'll see this. The reason you get so many errors is because you're missing package dependencies. The BCL that used to be in the GAC are now all inside of NuGet packages and if those fundamental packages are missing then you'll get tons of errors.

**Comment by pgrm** [comment]
Hi @davidfowl, thanks for confirming my suspicions. Although I didn't try to  convert it actually, I rather wanted to create a new project and take over the code, as much as possible (all the business logic, services, models), the actual puzzling thing was the 2nd point I mentioned.

I wasn't able to create an ASP.NET 5 project in Visual Studio 2015 with .Net 4.6 and afterwards run it with docker. Because maybe `Kestrel` depends on dnxcore50 and I was missing the nuget packages?

The question from my side was rather - what could have been the reason it didn't work?

- Isn't it supposed to work (yet)? - In which case, will it work with the next beta or RC or only the final version?
- Am I just missing some references to nuget packages or nuget repositories?
- Would it work better in Windows 10 preview?

I think, when I'd figure out, why the simple project isn't doing, what I want it to do, and what I need to change, it would help me a lot understanding how ASP.NET 5 is working and how I can start porting my application.

If it will help, I can create a sample repository where you could (hopefully) reproduce the issues.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
