### ISSUE TITLE
project.json script 'postpublish' not running after VS publish

### ISSUE THREAD

**Issue by GuardRex** [aspnet/Home#622]
Win10 (Build 10074) x64
dnx-coreclr-win-x64-beta5-11781

As we [discussed previously](https://github.com/aspnet/Hosting/issues/141) for Web Deploy, I have commands that will publish to an Azure VM. I moved my MSDeploy commands into a batch file and added a `postpublish` trigger to execute the file in `project.json`:
```json
"scripts": {
  "postpublish": "%project:Directory%/msdeploy.bat"
},
```
In VS 2015 RC, I went for a `Build > Publish MyApp`. The expected behavior was that the VS publish command would do a package restore, build the app into `.../bin/output`, then run my batch file to deploy to the VM. Didn't happen ... it actually did the package restore, ran the batch file next, **then** it compiled the app.

The easy workaround was to tick the publish settings for `Publish using PowerShell script` and add
```
& .\msdeploy.bat
```
after the `Publish-AspNet` command. Of course, the MSDeploy commands could be injected there, too. 

... but was it the team's intention to have the script execute for `postpublish` occur before the publish step (to the file system) for the VS Publish command?

**Comment by janpieterz** [comment]
@GuardRex did you ever get an answer anywhere to why postpublish actually runs before the publish? I do a local file system publish and literally have these lines:

```
Executing script 'postpublish' in project.json
Time elapsed 00:00:16.7422679
Publishing with publish method [FileSystem]
Publishing files to C:\Development\Enterprise Net2 Manager\artifacts\bin\Intreba.Enm.Web\Release\PublishOutput

**Comment by GuardRex** [comment]
@janpieterz No, I didn't. The team didn't respond to my question, so I thought it was just a problem of my understanding at what point a `postpublish` script was supposed to run. Then, I solved my problem of how to run my PowerShell script by directly adding to the generated `Publish to Filesystem` PowerShell script and ended up never really needing an answer. I'll re-open this.

**Comment by vijayrkn** [comment]
@sayedihashimi 

Currently, the VS publish tooling does not handle the project.json postpublish script as last step in the VS publish process. Will create a tooling bug to track this. I think it is currently running as the last step in the "dnu publish command" and not the entire publish process.

**Comment by vijayrkn** [comment]
These are the steps in the VS publish process:
1. VS publish invokes dnu publish command with the right parameters. Prepublish and PostPublish scripts are just part of the dnu publish command. 

2. After the deployable output is created by dnu publish command, VS passed the output location and publish properties to powershell to execute msdeploy and push the output to destination.

For customizing the pre-msdeploy and post-msdeploy behavior we are thinking about  adding hooks in the powershell process (step 2). May be adding an option for running a prepublish powershell script and postpublish powershell script. 

Would this work for you? To understand the requirement better, can you let us know what kind of postpublish script are you trying to run?

**Comment by GuardRex** [comment]
@vijayrkn Works for me ... that's pretty much what I did. I just edited the script and hooked my script right after the `Publish-AspNet` command. It would be nice to have that in `project.json` and not have to muck around with the PS script manually.

**Comment by GuardRex** [comment]
Here it is ... https://github.com/aspnet/Docs/issues/105#issuecomment-113716606

**Comment by GuardRex** [comment]
Actually, it looks like either type of script is run via PS without regard to the extension.
```
& .\myscript.bat
& .\myscript.ps1
```
... just works! :sparkles: :sparkles: :sparkles:

**Comment by janpieterz** [comment]
Same here, I'm trying to run a powershell script that prepares the msdeployed stuff for the automatic deployment tool (Octopus) and pushes it.

**Comment by GuardRex** [comment]
@janpieterz If you haven't tried it already, I can confirm that if you place your PS script call right after the `Publish-AspNet` command in the VS-generated 
```
Properties > PublishProfiles > Filesystem-publish.ps1
```
 script, it will run your script at the very end of a VS publish. Call it as I show above if the script is sitting in your project; otherwise, provide the path.

**Comment by janpieterz** [comment]
@GuardRex thanks! I did see your comment about this already but didn't try it out yet.
Will for now use this, got it working (or at least giving a hello message, so the rest should be easy as well).

**Comment by sayedihashimi** [comment]
The part of the script that is interesting to you is

```powershell
Publish-AspNet -publishProperties $publishProperties -packOutput $packOutput -pubProfilePath $pubProfilePath
```

You can pretty much ignore the rest, it's all about loading dependencies.

The call to `Publish-AspNet` will take the results of `dnu publish` (from the `$packOutput` variable) and publish it to the destination using the specified transport.

So if you want to modify the contents of the files being published, modify the `$packOutput` folder before the call to `Publish-AspNet`. 

And if you want to do something after it's been published to the destination then just do that after the call to `Publish-AspNet`.

If you need to modify ***how*** the contents are published then that would be by modifying the `$publishProperties` object. You can use `get-help Publish-AspNet` for info on the structure of `$publishProperties`. You can also refer to the inline comments [in the source](https://github.com/aspnet/vsweb-publish/blob/master/publish-module.psm1#L230).

FYI if you need to do something custom you can replace the contents of the publish script. VS just calls the .ps1 file and passes in the contents of the `.pubxml` file into `$publishProperties`. If you add extra properties, they will be passed through to the `.ps1` file. To keep Visual Studio happy the defined parameters should remain.

About the idea of automatically calling pre/post publish scripts. I like the idea. I've opened an issue with some initial thoughts at https://github.com/aspnet/Tooling/issues/195. We can continue the discussion there.

@GuardRex is there any further follow up needed here? If not, can we close this?

**Comment by sayedihashimi** [comment]
@GuardRex if you need to publish to IIS I think this should work. 

 1. Create a publish profile with your IIS settings
 1. In the `.ps1` file created update the version of the publish module to `1.0.2-beta1`

If you have any clarifying questions or followup it would be better to create a new issue in the [tooling](https://github.com/aspnet/Tooling) repo and mention me. You can also feel free to email me sayedha@microsoft.com

**Comment by GuardRex** [comment]
I'm good. I'll track Tooling #195
