### ISSUE TITLE
Paid subscription for AppVeyor account aspnetci

### ISSUE THREAD

**Issue by jasonwilliams200OK** [aspnet/Home#629]
AppVeyor offers $29.5 per month for open-source projects: http://www.appveyor.com/pricing.
It would be really cool if aspnetci account gets the paid subscription, so contributors don't have to wait [for hours/days](https://ci.appveyor.com/project/aspnetci/mvc/history) to get back the job results.

Also note that even with paid subscription, AppVeyor runs one job at a time per account. Meaning if aspnetci account is setup for multiple projects, 'one job at a time' rule applies globally, but it is blazing fast compared to free subscription. If you have a sponsorship, you better setup different accounts for each project. :)

More details can be gathered from @FeodorFitsner via https://github.com/appveyor/ci/issues.

**Comment by davidfowl** [comment]
I believe we do have that plan /cc @Eilon

**Comment by Eilon** [comment]
We use the Pro FOSS plan from AppVeyor. We have a whole lot of repos, though, so even having our own queue sometimes means that builds have to wait a while.
