### ISSUE TITLE
Dnu wrap and Visual Studio 2015 RC

### ISSUE THREAD

**Issue by dodyg** [aspnet/Home#630]
I am working on a mixed project environment. The web site is aspnet 5 but I have two library project (without source) that runs on .net 4.5.

We did dnu wrap on the 4.5 library projects which result in two entries under /wrap folder. 

The problem is that the aspnet 5 is having terrible time in getting reference right to the wrapped projects. The compilation works fine but the editor shows the red line errors. 

We included the .csproj files in the solution and did not include the wrapped projects. Does this matter (the project compiles fine) ? What's the guideline on this situation?

**Comment by tareq-s** [comment]
+1

**Comment by shelakel** [comment]
Just a hunch, but I guess your project compiles fine against DNX451. It's the compilation against DNXCORE50 that fails. If you remove the dnxcore50 section from your frameworks section inside the project.json, the red line errors should disappear - but this also means you will only be compiling against DNX451.

**Comment by davidfowl** [comment]
There's also a bug in beta4 where dnu wrap doesn't put things in the right place when there's no `global.json` before performing the action.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
