### ISSUE TITLE
1067 errors: dnvm upgrade, update project.json from beta4 to beta5-11855 and re-build

### ISSUE THREAD

**Issue by developer1998** [aspnet/Home#631]
So looks like it is not referencing correctly. Can this even work through visual studio RC? What is the workflow when getting the latest build.
Error	CS0234	The type or namespace name 'AspNet' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?)	Project1.DNX 4.5.1	C:\Users\SomeUser\Project1\preprocess\RazorPreCompilation.cs	4

**Comment by davidfowl** [comment]
I can't make sense of this issue. Can you give proper repro steps?

**Comment by developer1998** [comment]
Sure. 
1) I've updated the clr runtime from dnx-clr-win-x64.1.0.0-beta4 to dnx-clr-win-x64.1.0.0-beta5-11855
2) I've referenced that new runtime in my project
3) I went into the project.json file and changed the dependencies from -beta4 to -beta4-* so it downloaded for me the latest dependencies
4) This broke my solution.

So the issue is: how to update dependencies, so they will work with the latest beta5-11855, or any latest built for that matter. For the record I only had success in Visual Studio only with the dependencies and run-times that came packaged with the IDE. 

Thanks.

**Comment by davidfowl** [comment]
`beta4-*` why not `beta5-*`?

**Comment by developer1998** [comment]
there was nothing found for beta5-*, I've used this source: https://www.myget.org/F/aspnetlastkre/api/v2

**Comment by davidfowl** [comment]
Yea, that source is pretty wrong. See how it says lastkre? We renamed the kre to dnx in beta4. Why are you still using that package source

**Comment by developer1998** [comment]
Thanks. Changing the source to https://www.myget.org/F/aspnetvnext/ helped. I am down to 15 errors:
Severity	Code	Description	Project	File	Line
Error	CS0115	'CreateIdentitySchema.Target': no suitable method found to override	Project1.DNX 4.5.1	Migrations\00000000000000_CreateIdentitySchema.cs	159
Error	CS0246	The type or namespace name 'BasicModelBuilder' could not be found (are you missing a using directive or an assembly reference?)	Project1.DNX 4.5.1	Migrations\00000000000000_CreateIdentitySchema.cs	163
Error	CS0534	'ApplicationDbContextModelSnapshot' does not implement inherited abstract member 'ModelSnapshot.BuildModel(ModelBuilder)'	Project1.DNX 4.5.1	Migrations\ApplicationDbContextModelSnapshot.cs	13
Error	CS0115	'ApplicationDbContextModelSnapshot.Model': no suitable method found to override	Project1.DNX 4.5.1	Migrations\ApplicationDbContextModelSnapshot.cs	15
Error	CS0246	The type or namespace name 'BasicModelBuilder' could not be found (are you missing a using directive or an assembly reference?)	Project1.DNX 4.5.1	Migrations\ApplicationDbContextModelSnapshot.cs	19
Error	CS0115	'CreateIdentitySchema.Target': no suitable method found to override	Project1.DNX Core 5.0	Migrations\00000000000000_CreateIdentitySchema.cs	159
Error	CS0246	The type or namespace name 'BasicModelBuilder' could not be found (are you missing a using directive or an assembly reference?)	Project1.DNX Core 5.0	Migrations\00000000000000_CreateIdentitySchema.cs	163
Error	CS0534	'ApplicationDbContextModelSnapshot' does not implement inherited abstract member 'ModelSnapshot.BuildModel(ModelBuilder)'	Project1.DNX Core 5.0	Migrations\ApplicationDbContextModelSnapshot.cs	13
Error	CS0115	'ApplicationDbContextModelSnapshot.Model': no suitable method found to override	Project1.DNX Core 5.0	Migrations\ApplicationDbContextModelSnapshot.cs	15
Error	CS0246	The type or namespace name 'BasicModelBuilder' could not be found (are you missing a using directive or an assembly reference?)	Project1.DNX Core 5.0	Migrations\ApplicationDbContextModelSnapshot.cs	19
Error	CS1503	Argument 2: cannot convert from 'Microsoft.Framework.ConfigurationModel.IConfiguration' to 'System.Action<Project1.AppSettings>'	Project1.DNX 4.5.1	Startup.cs	56
Error	CS1061	'IApplicationBuilder' does not contain a definition for 'UseBrowserLink' and no extension method 'UseBrowserLink' accepting a first argument of type 'IApplicationBuilder' could be found (are you missing a using directive or an assembly reference?)	Project1.DNX 4.5.1	Startup.cs	108
Error	CS1503	Argument 2: cannot convert from 'Microsoft.Framework.ConfigurationModel.IConfiguration' to 'System.Action<Project1.AppSettings>'	Project1.DNX Core 5.0	Startup.cs	56
Error	CS1061	'IApplicationBuilder' does not contain a definition for 'UseBrowserLink' and no extension method 'UseBrowserLink' accepting a first argument of type 'IApplicationBuilder' could be found (are you missing a using directive or an assembly reference?)	Project1.DNX Core 5.0	Startup.cs	108
Error		NuGet Package Restore failed for one or more packages. See details in the Output window.	Project1	project.json	0

**Comment by developer1998** [comment]
Also this reference failed to updated Microsoft.VisualStudio.Web.BrowserLink.Loader, did you guys change the name?

**Comment by davidfowl** [comment]
There's no nightly build of Microsoft.VisualStudio.Web.BrowserLink.Loader, so I'd suggest removing it completely.

**Comment by developer1998** [comment]
Done, but Startup.cs was using it, got an error on app.UseBrowserLink().
Do you guys have a new version of Startup.cs that is complaint with the latest changes, if so can I have it. Thanks
                app.UseBrowserLink();
                app.UseErrorPage(ErrorPageOptions.ShowAll);
                app.UseDatabaseErrorPage(DatabaseErrorPageOptions.ShowAll);

**Comment by developer1998** [comment]
This is the latest error list, down to 14. I've noticed something which seems strange too, sometimes DNX 4.5.1 is used and other time DNX Core 5.0
Error	CS0246	The type or namespace name 'BasicModelBuilder' could not be found (are you missing a using directive or an assembly reference?)	Project1.DNX 4.5.1	\Migrations\00000000000000_CreateIdentitySchema.cs	164
Error	CS0115	'CreateIdentitySchema.Target': no suitable method found to override	Project1.DNX 4.5.1	\Migrations\00000000000000_CreateIdentitySchema.cs	160
Error	CS0534	'ApplicationDbContextModelSnapshot' does not implement inherited abstract member 'ModelSnapshot.BuildModel(ModelBuilder)'	Project1.DNX 4.5.1	\Migrations\ApplicationDbContextModelSnapshot.cs	14
Error	CS0115	'ApplicationDbContextModelSnapshot.Model': no suitable method found to override	Project1.DNX 4.5.1	\Migrations\ApplicationDbContextModelSnapshot.cs	16
Error	CS0115	'CreateIdentitySchema.Target': no suitable method found to override	Project1.DNX Core 5.0	\Migrations\00000000000000_CreateIdentitySchema.cs	160
Error	CS0534	'ApplicationDbContextModelSnapshot' does not implement inherited abstract member 'ModelSnapshot.BuildModel(ModelBuilder)'	Project1.DNX Core 5.0	\Migrations\ApplicationDbContextModelSnapshot.cs	14
Error	CS0115	'ApplicationDbContextModelSnapshot.Model': no suitable method found to override	Project1.DNX Core 5.0	\Migrations\ApplicationDbContextModelSnapshot.cs	16
Error	CS0246	The type or namespace name 'BasicModelBuilder' could not be found (are you missing a using directive or an assembly reference?)	Project1.DNX 4.5.1	\Migrations\ApplicationDbContextModelSnapshot.cs	20
Error	CS1503	Argument 2: cannot convert from 'Microsoft.Framework.ConfigurationModel.IConfiguration' to 'System.Action<Project1.AppSettings>'	Project1.DNX 4.5.1	\Startup.cs	56
Error	CS1061	'IApplicationBuilder' does not contain a definition for 'UseBrowserLink' and no extension method 'UseBrowserLink' accepting a first argument of type 'IApplicationBuilder' could be found (are you missing a using directive or an assembly reference?)	Project1.DNX 4.5.1	\Startup.cs	108
Error	CS0246	The type or namespace name 'BasicModelBuilder' could not be found (are you missing a using directive or an assembly reference?)	Project1.DNX Core 5.0	\Migrations\00000000000000_CreateIdentitySchema.cs	164
Error	CS0246	The type or namespace name 'BasicModelBuilder' could not be found (are you missing a using directive or an assembly reference?)	Project1.DNX Core 5.0	\Migrations\ApplicationDbContextModelSnapshot.cs	20
Error	CS1503	Argument 2: cannot convert from 'Microsoft.Framework.ConfigurationModel.IConfiguration' to 'System.Action<Project1.AppSettings>'	Project1.DNX Core 5.0	\Startup.cs	56
Error	CS1061	'IApplicationBuilder' does not contain a definition for 'UseBrowserLink' and no extension method 'UseBrowserLink' accepting a first argument of type 'IApplicationBuilder' could be found (are you missing a using directive or an assembly reference?)	Project1.DNX Core 5.0	\Startup.cs	108

**Comment by developer1998** [comment]
All the errors are resolved, simply commented out the lines. There are no warning either, and no references problems, it builds fine. However when I run my web site I get this. How should I proceed?:
Failed to resolve the following dependencies for target framework 'DNX,Version=v4.5.1':
  EntityFramework.Commands 7.0.0-beta5
  EntityFramework.SqlServer 7.0.0-beta5
  Microsoft.AspNet.Authentication.Cookies 1.0.0-beta5
  Microsoft.AspNet.Authentication.Facebook 1.0.0-beta5
  Microsoft.AspNet.Authentication.Google 1.0.0-beta5
  Microsoft.AspNet.Authentication.MicrosoftAccount 1.0.0-beta5
  Microsoft.AspNet.Authentication.Twitter 1.0.0-beta5
  Microsoft.AspNet.Diagnostics 1.0.0-beta5
  Microsoft.AspNet.Diagnostics.Entity 7.0.0-beta5
  Microsoft.AspNet.Identity.EntityFramework 3.0.0-beta5
  Microsoft.AspNet.Mvc 6.0.0-beta5
  Microsoft.AspNet.Mvc.TagHelpers 6.0.0-beta5
  Microsoft.AspNet.Server.IIS 1.0.0-beta5
  Microsoft.AspNet.Server.WebListener 1.0.0-beta5
  Microsoft.AspNet.StaticFiles 1.0.0-beta5
  Microsoft.AspNet.Tooling.Razor 1.0.0-beta5
  Microsoft.Framework.CodeGenerators.Mvc 1.0.0-beta5
  Microsoft.Framework.ConfigurationModel.Json 1.0.0-beta5
  Microsoft.Framework.ConfigurationModel.UserSecrets 1.0.0-beta5
  Microsoft.Framework.Logging 1.0.0-beta5
  Microsoft.Framework.Logging.Console 1.0.0-beta5

**Comment by developer1998** [comment]
I will close this because the initial problem is fixed... Thank you
