### ISSUE TITLE
Failed to resolve the following dependencies for target framework 'DNX,Version=v4.5.1':

### ISSUE THREAD

**Issue by developer1998** [aspnet/Home#633]
I am running dnx-clr-win-x86.1.0.0-beta5-11855
I have no errors of any kind and all the references are ok, and I can build fine.
When I run from withing Visual Studio RC Enterprise I get, the following error in the browser (I spend a while trying to resolve this to no avail, thank you for your help):

Server Error in '/' Application.

Failed to resolve the following dependencies for target framework 'DNX,Version=v4.5.1':
  EntityFramework.Commands 7.0.0-beta5
  EntityFramework.SqlServer 7.0.0-beta5
  Microsoft.AspNet.Authentication.Cookies 1.0.0-beta5
  Microsoft.AspNet.Authentication.Facebook 1.0.0-beta5
  Microsoft.AspNet.Authentication.Google 1.0.0-beta5
  Microsoft.AspNet.Authentication.MicrosoftAccount 1.0.0-beta5
  Microsoft.AspNet.Authentication.Twitter 1.0.0-beta5
  Microsoft.AspNet.Diagnostics 1.0.0-beta5
  Microsoft.AspNet.Diagnostics.Entity 7.0.0-beta5
  Microsoft.AspNet.Identity.EntityFramework 3.0.0-beta5
  Microsoft.AspNet.Mvc 6.0.0-beta5
  Microsoft.AspNet.Mvc.TagHelpers 6.0.0-beta5
  Microsoft.AspNet.Server.IIS 1.0.0-beta5
  Microsoft.AspNet.Server.WebListener 1.0.0-beta5
  Microsoft.AspNet.StaticFiles 1.0.0-beta5
  Microsoft.AspNet.Tooling.Razor 1.0.0-beta5
  Microsoft.Framework.CodeGenerators.Mvc 1.0.0-beta5
  Microsoft.Framework.ConfigurationModel.Json 1.0.0-beta5
  Microsoft.Framework.ConfigurationModel.UserSecrets 1.0.0-beta5
  Microsoft.Framework.Logging 1.0.0-beta5
  Microsoft.Framework.Logging.Console 1.0.0-beta5

Searched Locations:
 C:\Users\User1\Source\Repos\Project1\Project1\src\{name}\project.json
 C:\Users\User1\Source\Repos\Project1\Project1\test\{name}\project.json
 C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.1\{name}.dll
 C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.1\Facades\{name}.dll
 C:\Windows\Microsoft.NET\assembly\GAC_32\{name}\{version}\{name}.dll
 C:\Windows\Microsoft.NET\assembly\GAC_64\{name}\{version}\{name}.dll
 C:\Windows\Microsoft.NET\assembly\GAC_MSIL\{name}\{version}\{name}.dll

Try running 'dnu restore'.

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.InvalidOperationException: Failed to resolve the following dependencies for target framework 'DNX,Version=v4.5.1':
  EntityFramework.Commands 7.0.0-beta5
  EntityFramework.SqlServer 7.0.0-beta5
  Microsoft.AspNet.Authentication.Cookies 1.0.0-beta5
  Microsoft.AspNet.Authentication.Facebook 1.0.0-beta5
  Microsoft.AspNet.Authentication.Google 1.0.0-beta5
  Microsoft.AspNet.Authentication.MicrosoftAccount 1.0.0-beta5
  Microsoft.AspNet.Authentication.Twitter 1.0.0-beta5
  Microsoft.AspNet.Diagnostics 1.0.0-beta5
  Microsoft.AspNet.Diagnostics.Entity 7.0.0-beta5
  Microsoft.AspNet.Identity.EntityFramework 3.0.0-beta5
  Microsoft.AspNet.Mvc 6.0.0-beta5
  Microsoft.AspNet.Mvc.TagHelpers 6.0.0-beta5
  Microsoft.AspNet.Server.IIS 1.0.0-beta5
  Microsoft.AspNet.Server.WebListener 1.0.0-beta5
  Microsoft.AspNet.StaticFiles 1.0.0-beta5
  Microsoft.AspNet.Tooling.Razor 1.0.0-beta5
  Microsoft.Framework.CodeGenerators.Mvc 1.0.0-beta5
  Microsoft.Framework.ConfigurationModel.Json 1.0.0-beta5
  Microsoft.Framework.ConfigurationModel.UserSecrets 1.0.0-beta5
  Microsoft.Framework.Logging 1.0.0-beta5
  Microsoft.Framework.Logging.Console 1.0.0-beta5

Searched Locations:
 C:\Users\User1\Source\Repos\Project1\Project1\src\{name}\project.json
 C:\Users\User1\Source\Repos\Project1\Project1\test\{name}\project.json
 C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.1\{name}.dll
 C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.1\Facades\{name}.dll
 C:\Windows\Microsoft.NET\assembly\GAC_32\{name}\{version}\{name}.dll
 C:\Windows\Microsoft.NET\assembly\GAC_64\{name}\{version}\{name}.dll
 C:\Windows\Microsoft.NET\assembly\GAC_MSIL\{name}\{version}\{name}.dll

Try running 'dnu restore'.

Source Error: 

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.

Stack Trace: 

[InvalidOperationException: Failed to resolve the following dependencies for target framework 'DNX,Version=v4.5.1':
   EntityFramework.Commands 7.0.0-beta5
   EntityFramework.SqlServer 7.0.0-beta5
   Microsoft.AspNet.Authentication.Cookies 1.0.0-beta5
   Microsoft.AspNet.Authentication.Facebook 1.0.0-beta5
   Microsoft.AspNet.Authentication.Google 1.0.0-beta5
   Microsoft.AspNet.Authentication.MicrosoftAccount 1.0.0-beta5
   Microsoft.AspNet.Authentication.Twitter 1.0.0-beta5
   Microsoft.AspNet.Diagnostics 1.0.0-beta5
   Microsoft.AspNet.Diagnostics.Entity 7.0.0-beta5
   Microsoft.AspNet.Identity.EntityFramework 3.0.0-beta5
   Microsoft.AspNet.Mvc 6.0.0-beta5
   Microsoft.AspNet.Mvc.TagHelpers 6.0.0-beta5
   Microsoft.AspNet.Server.IIS 1.0.0-beta5
   Microsoft.AspNet.Server.WebListener 1.0.0-beta5
   Microsoft.AspNet.StaticFiles 1.0.0-beta5
   Microsoft.AspNet.Tooling.Razor 1.0.0-beta5
   Microsoft.Framework.CodeGenerators.Mvc 1.0.0-beta5
   Microsoft.Framework.ConfigurationModel.Json 1.0.0-beta5
   Microsoft.Framework.ConfigurationModel.UserSecrets 1.0.0-beta5
   Microsoft.Framework.Logging 1.0.0-beta5
   Microsoft.Framework.Logging.Console 1.0.0-beta5

Searched Locations:
  C:\Users\User1\Source\Repos\Project1\Project1\src\{name}\project.json
  C:\Users\User1\Source\Repos\Project1\Project1\test\{name}\project.json
  C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.1\{name}.dll
  C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.1\Facades\{name}.dll
  C:\Windows\Microsoft.NET\assembly\GAC_32\{name}\{version}\{name}.dll
  C:\Windows\Microsoft.NET\assembly\GAC_64\{name}\{version}\{name}.dll
  C:\Windows\Microsoft.NET\assembly\GAC_MSIL\{name}\{version}\{name}.dll

Try running 'dnu restore'.
]
   System.Web.HttpRuntime.HostingInit(HostingEnvironmentFlags hostingFlags, PolicyLevel policyLevel, Exception appDomainCreationException) +303

[HttpException (0x80004005): Failed to resolve the following dependencies for target framework 'DNX,Version=v4.5.1':
   EntityFramework.Commands 7.0.0-beta5
   EntityFramework.SqlServer 7.0.0-beta5
   Microsoft.AspNet.Authentication.Cookies 1.0.0-beta5
   Microsoft.AspNet.Authentication.Facebook 1.0.0-beta5
   Microsoft.AspNet.Authentication.Google 1.0.0-beta5
   Microsoft.AspNet.Authentication.MicrosoftAccount 1.0.0-beta5
   Microsoft.AspNet.Authentication.Twitter 1.0.0-beta5
   Microsoft.AspNet.Diagnostics 1.0.0-beta5
   Microsoft.AspNet.Diagnostics.Entity 7.0.0-beta5
   Microsoft.AspNet.Identity.EntityFramework 3.0.0-beta5
   Microsoft.AspNet.Mvc 6.0.0-beta5
   Microsoft.AspNet.Mvc.TagHelpers 6.0.0-beta5
   Microsoft.AspNet.Server.IIS 1.0.0-beta5
   Microsoft.AspNet.Server.WebListener 1.0.0-beta5
   Microsoft.AspNet.StaticFiles 1.0.0-beta5
   Microsoft.AspNet.Tooling.Razor 1.0.0-beta5
   Microsoft.Framework.CodeGenerators.Mvc 1.0.0-beta5
   Microsoft.Framework.ConfigurationModel.Json 1.0.0-beta5
   Microsoft.Framework.ConfigurationModel.UserSecrets 1.0.0-beta5
   Microsoft.Framework.Logging 1.0.0-beta5
   Microsoft.Framework.Logging.Console 1.0.0-beta5

Searched Locations:
  C:\Users\User1\Source\Repos\Project1\Project1\src\{name}\project.json
  C:\Users\User1\Source\Repos\Project1\Project1\test\{name}\project.json
  C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.1\{name}.dll
  C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.1\Facades\{name}.dll
  C:\Windows\Microsoft.NET\assembly\GAC_32\{name}\{version}\{name}.dll
  C:\Windows\Microsoft.NET\assembly\GAC_64\{name}\{version}\{name}.dll
  C:\Windows\Microsoft.NET\assembly\GAC_MSIL\{name}\{version}\{name}.dll

Try running 'dnu restore'.
]
   System.Web.HttpRuntime.FirstRequestInit(HttpContext context) +9940016
   System.Web.HttpRuntime.EnsureFirstRequestInit(HttpContext context) +101
   System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest wr, HttpContext context) +261

Version Information: Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.6.57.0

**Comment by Samvrie** [comment]
ConfigurationModel doesn't exist anymore, it has been replace by Configuration a look a the Repro to see the different packages.
And the [Annoucement here](https://github.com/aspnet/Announcements/issues/25)

**Comment by davidfowl** [comment]
What did you run dnu restore with? What version is in project.lock.json?

**Comment by developer1998** [comment]
@Samvrie Thanks for that, but it did not help.

**Comment by developer1998** [comment]
@davidfowl 
The version in project.lock.json is -9998.

Something is wrong with the dnu restore, because it restores me to a point that I get 2000+ errors, and the version in prokect.lock.json after running is -9996. How can I make it restore to get me packages for dnx-clr-win-x86.1.0.0-beta5-11855?

**Comment by davidfowl** [comment]
You should be restoring with the same version that you're running. If you're in visual studio, make sure the version in `global.json` is what you expect.

**Comment by developer1998** [comment]
@davidfowl thanks. Looks like we are progressing, my global.json was
{
    "projects": [ "src", "test" ],
    "sdk": {
        "version": "1.0.0-beta5-11394"
    }
}

when I changed it to 
{
    "projects": [ "src", "test" ],
    "sdk": {
        "version": "1.0.0-beta5-11855"
    }
}
I started to get get reference errors.

**Comment by davidfowl** [comment]
Close and reopen the solution once you change the version.

**Comment by developer1998** [comment]
@davidfowl it works:) Thanks for your help on this one. One strange thing I've noticed in that NuGet.Config although packages were disabled, dnu restore was still grabbing them. I had to remove them from that xml alltogether.

**Comment by Eugene9999** [comment]
dnu restore --packages C:\Users\Eugene\.dnx\runtimes\dnx-clr-win-x86.1.0.0-beta6\bin
I did that to restore to the latest version

before that did
dnvm upgrade
dnvm install 1.0.0-beta6
