### ISSUE TITLE
Why does Helios have a default error handler?

### ISSUE THREAD

**Issue by tugberkugurlu** [aspnet/Home#639]
When I host my ASP.NET 5 application (beta4) on Helios (Microsoft.AspNet.Server.IIS), I can see that it has a default error handler and gives back error pages as below:

![image](https://cloud.githubusercontent.com/assets/328122/7846657/f4dda5cc-04b6-11e5-85ff-946a5eeb8f57.png)

However, if I host the app on Microsoft.AspNet.Server.WebListener, I see a white screen. As I didn’t add the middleware to show error pages, this is OK. I am just wondering the reason behind why we have this for Helios. One of the good things about ASP.NET 5 is the fact that we are in charge of building the pipeline and there is no magic. But it seems to me that this behavior is proving the opposite.

**Comment by Tratcher** [comment]
It's useful and comes at little or no cost. Middleware is free to add to the experience, but there are some errors that only the server can catch. I've got a work item filed to port this page to WebListener as well.

**Comment by tugberkugurlu** [comment]
Thx!

> It's useful and comes at little or no cost.

So, I can understand from that statement that any middleware which is useful and comes at little cost can end up inside the server? 

I really don't like this as I cannot anymore assume that server is not doing any processing on my message beyond what it needs to. It also violates the "pay for play" thing which has been pushed from the very beginning.

I can understand that there are some errors which can be only caught by the server. However, clarification on what the standard server should really be would be nice.

**Comment by davidfowl** [comment]
Helios is a bit of a special case as well since compilation errors can show up there. Helios is both a runtime bootstrapper and a server so the error page serves both purposes.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
