### ISSUE TITLE
mono: not found

### ISSUE THREAD

**Issue by sjmueller** [aspnet/Home#641]
As of a new install today, mono is suddenly not being found. Using these commands:

```
brew update
brew tap aspnet/dnx
brew install dnvm
dnvm upgrade -unstable
```

I get error message: `It appears you don't have Mono available. Remember to get Mono before trying to run  application.`

using `dnvm list`
![image](https://cloud.githubusercontent.com/assets/29085/7867676/57e4bf8c-052c-11e5-8311-bf0c3b7d622e.png)

Running `dnu restore` on a project yields:
![image](https://cloud.githubusercontent.com/assets/29085/7867709/8437753e-052c-11e5-9561-d460d788aa6e.png)

What could be the problem?

**Comment by BrennanConroy** [comment]
Just to make sure, do you have mono installed?

**Comment by sjmueller** [comment]
@BrennanConroy, I have not run any other commands besides the ones I listed above. I was under the impression that running `brew install dnvm` will install the right version of mono.  From the aspnet/home readme:

> on OS X the brew formula uses a particular version of Mono that we know works with ASP.NET 5

Is there another command that must be run in order to get the right version of mono?

**Comment by BrennanConroy** [comment]
It should get mono for you. Try ```brew list``` and see if mono is in the list. There could have been a glitch in the matrix and you might need to try again. You could check to see if there are any linkage errors and try to resolve them.

**Comment by sjmueller** [comment]
Thanks for the suggestion @BrennanConroy.  Here's `brew list`
![image](https://cloud.githubusercontent.com/assets/29085/7872395/a1a92624-054c-11e5-92de-fcea8845cdb9.png)

It shows that mono is installed, although I'm not sure if it is the right version.  Also, could it be related to the above caveat `export MONO_GAC_PREFIX="/usr/local`?

**Comment by sjmueller** [comment]
Pinging back here.  Is there a specific course of action you recommend in order to get up and running?

**Comment by BrennanConroy** [comment]
I don't have any specific ideas, you could try to uninstall dnvm/mono and retry.

**Comment by sjmueller** [comment]
Ok, figured it out.  I ran `brew doctor` and got a warning that there were unlinked installs because of permission problems on certain directories: `/usr/local/share/man/man5 is not writable`

So I chmod the ones it listed, and then ran `brew link mono` and it worked like a charm.  I think because mono is installed on behalf of the user through brew install dnvm, this particular error got swallowed and I had no warning that brew link failed.

Thanks for your help!

**Comment by BrennanConroy** [comment]
Cool :)
I was going to suggest brew doctor next, but it is a scary doctor :P
