### ISSUE TITLE
SignalR Cpp without websocket transport

### ISSUE THREAD

**Issue by nicolasr75** [aspnet/Home#642]
I have successfully used the new SignalR-Cpp client library to connect some C++ applications with an ASP.NET web application. That's a really great innovation. The problem is that I would like to use it with several IIS 7.5 installations which don't support web sockets.
The source code of SignalR-Cpp seems to be fully prepared for non web socket transports but currently there is only web sockets implemented.
Are there any plans to implement at least one transport that will allow us to connect IIS 7.5 ?

**Comment by BrennanConroy** [comment]
Please move this issue to https://github.com/aspnet/SignalR-Client-Cpp
