### ISSUE TITLE
Implicit references

### ISSUE THREAD

**Issue by sujitdmello** [aspnet/Home#645]
If an app makes an explicit reference to some assembly in some package, you would expect it to have that package listed in the *project.json* file. 

However what happens if there is an implicit reference? The one use-case we have is that the **Hosting:Application** environment variable *may* be set and this allows an alternative Startup class to be executed when the app starts up. This has nothing to do with the app itself (the environment variable applies to *all* apps) so the app would not have an entry in the *project.json* file. However when you try to run the app, it fails because the runtime is trying to find the global Startup class and since there is no entry in the *project.json* file for the appropriate package the load fails even if the package is available in the *packages* folder. 

This begs the question on how such corner cases for implicit references should be handled. Ideally there should be a way (env variable etc.) to specify which package contains the assembly containing the global startup. Or am I doing something wrong with my setup?

**Comment by Tratcher** [comment]
Yeah, that’s not supposed to work. The package directory is not searched by Assembly.Load, packages must be directly or transitively referenced from the project.json. I think it would work if the assembly were in the GAC or in the root application directory.

**Comment by sujitdmello** [comment]
GAC is not a viable options since we are targeting CoreCLR.  And asking each app to package an assembly in their root folder is a bit odd.

I think the Hosting:Application value should contain both the package and assembly name and get resolved by the runtime as a complete unit.

Sujit

**Comment by davidfowl** [comment]
We don't have first class support for adding to the dependency closure outside of the project.json file. It's doable with a custom assembly loader, it's also possible to do it if you launch dnx manually and pass in search paths. At that point tho the version resolution has already happened so if your hosting:application and its dependency closure use anything that conflicts with the application, it may fail (but that's no different to what happens today in regular .NET apps). 

The DNX resolves the dependency graph upfront based on your `project.json` (it doesn't load the assemblies, it just resolves them), so for any assemblies you load outside of that, you're on your own.

**Comment by sujitdmello** [comment]
Thanks @Tratcher  @davidfowl  for the explanation. The only issue is that this negates the usage of the Hosting:Application feature. I am not sure how this was intended to be used but if an application has to have a reference to an assembly that it does not actually use, but may get called implicitly by the StartupLoader based on the environment variable, then that design is a bit flawed IMHO.

**Comment by davidfowl** [comment]
> I am not sure how this was intended to be used but if an application has to have a reference to an assembly that it does not actually use.

Just because you don't use the API doesn't mean you aren't "using" the package. Applications never call Hosting directly but reference it because it loads within the scope of the user's dependencies.

**Comment by sujitdmello** [comment]
That's fair. Thanks.
