### ISSUE TITLE
Unable to run secret manager

### ISSUE THREAD

**Issue by abhijain369** [aspnet/Home#646]
I am not able to use this.
i) If I run dnu commands install SecretManager I get error saying: "dnu is not recognized as an internal or external command"

ii) If I run "user-secret -h" I get "user-secret is not recognized as an internal or external command"

I am using Visual Studio 2015 RC on Windows 8.1 machine. Can anyone help?

**Comment by tsnyder9** [comment]
(i) The tip about editing the version number in the SecretManager project json in other threads resolved the installation issue for me.
(ii) Running cmd as administrator resolved 'user-secret' not recognized once I got it installed.

**Comment by Eilon** [comment]
@abhijain369 make sure you have an active DNX in the current command window. Run `dnvm list` to see which DNX's are installed, and then run `dnvm use 1.0.0-beta4` (or whatever) to activate a particular DNX. Then you can run the `dnu` command to install the `user-secrets` command.

**Comment by ricklove** [comment]
I had to run the command prompt under Administrator and then user-secret worked

**Comment by Eilon** [comment]
Can you log an issue on https://github.com/aspnet/UserSecrets/issues with full details? Exact version of DNX, the version of SecretManager, and the stack trace of the exception would be helpful.

**Comment by ricklove** [comment]
Ok, I will log an issue there

**Comment by Eilon** [comment]
Filed as https://github.com/aspnet/UserSecrets/issues/34

Thanks!
