### ISSUE TITLE
How to get v.1.0.0-beta6-11923, dnvm upgrade gets 1.0.0-beta5-11911

### ISSUE THREAD

**Issue by developer1998** [aspnet/Home#647]
Just came out, maybe I am accessing it too fast, and it is not yet available.

**Comment by developer1998** [comment]
@Eilon Is this a typo of beta6 on https://www.myget.org/gallery/aspnetvnext because the libraries seem to work fine with 1.0.0.-beta5-11911

**Comment by vsimonian** [comment]
`dnvm upgrade -u` worked for me - it grabbed `beta6`:

```
Vartans-MBP:fsgf-portal vartan$ dnvm list

Active Version              Runtime Arch Location             Alias
------ -------              ------- ---- --------             -----
  *    1.0.0-beta6-11938    coreclr x64  ~/.dnx/runtimes      coreclr-latest, default
       1.0.0-beta4          mono         ~/.dnx/runtimes      
       1.0.0-beta6-11938    mono         ~/.dnx/runtimes      mono-latest
       beta-5               mono         ~/.dnx/runtimes      
       beta5-10407          mono         ~/.dnx/runtimes      
       beta5-11672          mono         ~/.dnx/runtimes   
```

**Comment by developer1998** [comment]
I don't know I can never get the -u parameter to work for me, I get this error:

```
C:\Program Files\Microsoft DNX\Dnvm\dnvm.ps1 : A parameter cannot be found that
 matches parameter name 'u'.
At line:1 char:183
+ ... t-envvars.cmd';& 'C:\Program Files\Microsoft DNX\Dnvm\dnvm.ps1' upgrade -
u
+                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorExcep
   tion
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorExceptio
   n,dnvm.ps1
```

**Comment by vsimonian** [comment]
Perhaps it's different on Windows: try `-Unstable` or `-Unstable:true`?

**Comment by davidfowl** [comment]
it's not different on windows. @developer1998 You need to update your dnvm, the one installed with the VS RC doesn't have the -u feature.

**Comment by vsimonian** [comment]
Thanks, @davidfowl! :+1: Updating dnvm fixed the lack of `-u` on my PC.

**Comment by developer1998** [comment]
I did run
```
&{$Branch='dev';iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.ps1'))}
```
However when I run
```
dnvm where
```
I get
C:\Program Files\Microsoft DNX\Dnvm\dnvm.cmd
C:\Users\User1\.dnx\bin\dnvm.cmd
So according to this article, it is not picking up the one from my path
'''
If the output of where dnvm shows a program files location before the user profile, or doesn't show an entry in user profile, then the install has either failed or your PATH is incorrect. After installing dnvm you should have the dnvm script in %USERPROFILE%\.dnx\bin and that path needs to be on your PATH.
'''
How can I resolve this?

**Comment by developer1998** [comment]
Actually it does not matter, I've deleted the C:\Program Files\Microsoft DNX\Dnvm\dnvm.cmd and the problem perists

**Comment by developer1998** [comment]
@davidfowl 
It works now. What happen with the poweshell script, if it detects the dnvm.cmd it aborts the installation. So I've renamed the bin, then run the shell again and it installed. But it still did not work. I had to delete C:\Program Files\Microsoft DNX\Dnvm\dnvm.cmd then I run dnvm upgrade -u and it got me beta6, thank you for your patience:)
