### ISSUE TITLE
No service for type 'Microsoft.Framework.Runtime.ILibraryManager' has been registered

### ISSUE THREAD

**Issue by JakeRyu** [aspnet/Home#650]
I am using VS 2015 RC.

Projects with ASP.NET 5 template stopped working after running "dnvm upgrade". There used to be 4 runtimes but this upgrade has added the latest runtime and made it default. 

![image](https://cloud.githubusercontent.com/assets/2795453/7909771/c8e166c8-0846-11e5-8c24-9cb57842a71b.png)

When I create a new project with one of ASP.NET 5 templates VS complains object reference is not set. 

![image](https://cloud.githubusercontent.com/assets/2795453/7909755/ae1ec128-0846-11e5-9de8-89cc526b7505.png)

Running the application fails as below.

>  No service for type 'Microsoft.Framework.Runtime.ILibraryManager' has been registered.

>  Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

>  Exception Details: System.InvalidOperationException: No service for type 'Microsoft.Framework.Runtime.ILibraryManager' has been registered.

>  Source Error: 

>  An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.

>  Stack Trace: 

>  [InvalidOperationException: No service for type 'Microsoft.Framework.Runtime.ILibraryManager' has been registered.]
   System.Web.HttpRuntime.HostingInit(HostingEnvironmentFlags hostingFlags, PolicyLevel policyLevel, Exception appDomainCreationException) +303

>  [HttpException (0x80004005): No service for type 'Microsoft.Framework.Runtime.ILibraryManager' has been registered.]
   System.Web.HttpRuntime.FirstRequestInit(HttpContext context) +9940016
   System.Web.HttpRuntime.EnsureFirstRequestInit(HttpContext context) +101
   System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest wr, HttpContext context) +261

>  Version Information: Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.6.57.0

Frameworks specified in project.json is as follows.

  "frameworks": {
    "dnx451": { },
    "dnxcore50": { }
  } 

Please advise.

**Comment by Samvrie** [comment]
What does your project.json looks like?
Did you update your references to use Beta5?

**Comment by JakeRyu** [comment]
[project.json]

{
  "webroot": "wwwroot",
  "version": "1.0.0-*",

  "dependencies": {
    "Microsoft.AspNet.Server.IIS": "1.0.0-beta4",
    "Microsoft.AspNet.Server.WebListener": "1.0.0-beta4"
  },

  "commands": {
      "web": "Microsoft.AspNet.Hosting --server Microsoft.AspNet.Server.WebListener --server.urls http://localhost:5000"
  },

  "frameworks": {
    "dnx451": { },
    "dnxcore50": { }
  },

  "publishExclude": [
    "node_modules",
    "bower_components",
    "**.xproj",
    "**.user",
    "**.vspscc"
  ],
  "exclude": [
    "wwwroot",
    "node_modules",
    "bower_components"
  ]
}

The project references to beta 4 but I found that global.json references to beta 5.

[global.json]

{
    "projects": [ "src", "test" ],
    "sdk": {
        "version" :  "1.0.0-beta5-11911"
    }
}


However, changing the version in the global.json to beta 4 doesn't fix and cause another issue. Please see below.


> Failed to resolve the following dependencies for target framework 'DNX,Version=v4.5.1':
  Microsoft.AspNet.Server.IIS 1.0.0-beta4
  Microsoft.AspNet.Server.WebListener 1.0.0-beta4


I feel something is mismatching but don't figure out how to configure.

**Comment by Samvrie** [comment]
You can't run with a beta5 dnx if you have beta4 references.
Either use beta5 dnx and beta5 AspNet packages, or beta4, but you can't mix them..

**Comment by JakeRyu** [comment]
@Samvrie , thank you for the quick response.

I see your point and agree.

What I found was, VS takes active dnx, in this case beta5 while AspNet is being packed with beta4 packages. Once I make betar4 active and creating a new project is working fine. 

Back to the original issue, if global.json has version, beta5, changing it to beta4 doesn't address depite of the fact that dnx referenced is beta4. That was what I couldn't figure out.

**Comment by davidfowl** [comment]
Closing this out as it's a version mismatch.
