### ISSUE TITLE
Dependency Resolution

### ISSUE THREAD

**Issue by patrickjamesbarry** [aspnet/Home#652]
I have a legacy project that I am trying to get building with the new Dnx framework.  The net40 and dnx452 build successfully. Now I am trying to get core50 working.  From my understanding, not all nuget packages exists for libraries that the .net framework currently include.  This is where I am stuck.  What are people supposed to do to overcome this?  Am I supposed to find these System.* libraries and create my own nuget packages, just to get past this issue?  Or are there equivalents somewhere?  My project.json looks like this:

"
"dependencies": {
    "Grub.Common-w64": "15.2.1.36",
    "Newtonsoft.Json": "6.0.8",
    "Grub.Tracing-w64": "2.1.1.4"
  },

  "frameworks": {
    "net40": {
      "frameworkAssemblies": {
        "System.Data": "4.0.0.0",
        "System.ServiceModel.Web": "4.0.0.0",
        "System.Xml": "4.0.0.0",
        "System.ServiceModel": "4.0.0.0",
        "System.Runtime.Serialization": "4.0.0.0"
      }
    },
    "dnx452": {
      "frameworkAssemblies": {
        "System.Data": "4.0.0.0",
        "System.ServiceModel.Web": "4.0.0.0",
        "System.Xml": "4.0.0.0",
        "System.ServiceModel": "4.0.0.0",
        "System.Runtime.Serialization": "4.0.0.0"
      }
    },
    "dnxcore50": {
      "dependencies": {
        "System.Collections": "4.0.10-beta-22816",
        "System.Linq": "4.0.0-beta-22816",
        "System.Threading": "4.0.10-beta-22816",
        "Microsoft.CSharp": "4.0.0-beta-22816",
        "System.IO.FileSystem": "4.0.0-beta-22816",
        "System.Runtime": "4.0.20-beta-22816",
        "System.Runtime.Extensions": "4.0.10-beta-22816",
        "System.Text.RegularExpressions": "4.0.10-beta-22816",
        "System.Data.Common": "4.0.0-beta-22816",
        "System.ServiceModel.Primitives": "4.0.0-beta-22816"
      }
    }
"

I need things like System.ServiceModel.Web, System.ServiceModel, System.Serializable, System.Timer, System.XmlRoot, etc.

**Comment by davidfowl** [comment]
Are you stuck figuring out which packages contain which types?

**Comment by patrickjamesbarry** [comment]
Yes.  Trying to resolve build issues, however I fear it is due to nuget packages that do not exists, so just trying to weigh my options.

C:\repos\One-common\src\Burp.One.Common\IntegrationsPackageManager\IPackageManagerService.cs(4,27): error CS0234: The type or namespace na
me 'Web' does not exist in the namespace 'System.ServiceModel' (are you missing an assembly reference?)
C:\repos\One-common\src\Burp.One.Common\IntegrationsPackageManager\PackageManagerService.cs(2,27): error CS0234: The type or namespace nam
e 'Web' does not exist in the namespace 'System.ServiceModel' (are you missing an assembly reference?)
C:\repos\One-common\src\Burp.One.Common\MessageProcessor\MessageProcessorWriter.cs(2,22): error CS0234: The type or namespace name 'Remoti
ng' does not exist in the namespace 'System.Runtime' (are you missing an assembly reference?)

**Comment by davidfowl** [comment]
Yes those don't exist.

**Comment by patrickjamesbarry** [comment]
Is there a site I could go to, to see a list of .net libraries and which
one's are slotted to be moved into nuget packages vs are just going to die
on the vine?  Is it up to the open source community to migrate these into
Nuget packages/Core50 or is it on the asp.net team's plate?

**Comment by davidfowl** [comment]
> Is there a site I could go to, to see a list of .net libraries and which
one's are slotted to be moved into nuget packages vs are just going to die
on the vine?
- https://github.com/dotnet/corefx-progress
- https://github.com/dotnet/corefx

> Is it up to the open source community to migrate these into
Nuget packages/Core50 or is it on the asp.net team's plate?

The BCL team ports these not us.

**Comment by patrickjamesbarry** [comment]
Thank you!
