### ISSUE TITLE
HttpModule for query string encryption

### ISSUE THREAD

**Issue by developer1998** [aspnet/Home#653]
@madskristensen you wrote a piece of code for query string encryption at http://madskristensen.net/post/httpmodule-for-query-string-encryption#comments
By any chance are you planning to write something for .NET 5 or perhaps this will be already part of the framework. Please advise, thanks.

**Comment by davidfowl** [comment]
It's not currently part of any plans to provide this in the box. You can port this module to a middleware though.

**Comment by developer1998** [comment]
Thank you.
