### ISSUE TITLE
A Tale of Two DNVM's: Can we delete one in Users?

### ISSUE THREAD

**Issue by GuardRex** [aspnet/Home#655]
My PATH defaults to the DNVM in
```
C:\Program Files\Microsoft DNX\Dnvm
```
not to the one I was using prior to installing VS 2015 RC in
```
C:\Users\<user>\.dnx\bin
```
Is it ok to delete the one in Users?

**Comment by aguacongas** [comment]
rename it and try !

**Comment by GuardRex** [comment]
Answered on today's [vNext Community Standup 6/9](http://www.youtube.com/watch?v=1aDLYFBuWc8&t=32m13s).
