### ISSUE TITLE
asp-fallback-href tag helper not working

### ISSUE THREAD

**Issue by developer1998** [aspnet/Home#656]
I have missing library at href so technically asp-fallback-href should kick in, but it does not. bootstrap-touch-carousel.min.css is missing, and it won't pick up bootstrap-touch-carousel.css
```
        <link rel="stylesheet" href="~/lib/bootstrap-touch-carousel/css/bootstrap-touch-carousel.min.css"
              asp-fallback-href="~/lib/bootstrap-touch-carousel/css/bootstrap-touch-carousel.css" />
```

**Comment by Eilon** [comment]
Moved to https://github.com/aspnet/Mvc/issues/2707
