### ISSUE TITLE
Make it possible for dnvm to install the SDK version defined in global.json

### ISSUE THREAD

**Issue by maartenba** [aspnet/Home#659]
In `global.json`, it is possible to specify the runtime version to use:

```
{
    "sdk": {
        "version": "1.0.0-beta2",
        "runtime": "coreclr",
        "architecture": "x64"
    }
}
```

That's awesome, as it tells the user opening a solution that the specific SDK is not installed.

It would be great to have a `dnvm` command, e.g. `dnvm prepare .` that makes sure the specified runtime is installed and is used for the current process.

Bonus points for also providing an msbuild option so that `msbuild mysolution.sln` installs and selects the correct runtime and then magically does its thing.

My ramblings, more structured:

**Run:** `msbuild Foo.sln`

**Expected:** The build process fetches the correct dnvm version to run against, then builds.

**Actual:** error : The Dnx Runtime package needs to be installed. See output window for more details.

**Comment by davidfowl** [comment]
> It would be great to have a dnvm command, e.g. dnvm prepare . that makes sure the specified runtime is installed and is used for the current process.

Yep, we're looking at doing this.

**Comment by maartenba** [comment]
:thumbsup:

**Comment by Bartmax** [comment]
:+1:

**Comment by maxmalmgren** [comment]
Any news on this?

**Comment by leak** [comment]
:+1:

**Comment by tinchou** [comment]
+1, would be useful for CI configuration

**Comment by maartenba** [comment]
I believe this was fixed in newer tooling.
