### ISSUE TITLE
How to configure Vs to run webapplication using local sources?

### ISSUE THREAD

**Issue by lucamorelli** [aspnet/Home#66]
Hi, I would like to configure a vs solution so I can run a web application running not the compiled packages, but the sources in a cloned repositories.
I would like to run and debug mvc and ef starting from the app and entering in the sources.
Actually is this possible?
I already tried to add to the solution the mvc packages, but seems are ignored.

**Comment by Praburaj** [comment]
Question is answered. Closing the bug.
