### ISSUE TITLE
Typo in text for Mac instrucitons

### ISSUE THREAD

**Issue by RichBorek** [aspnet/Home#660]
Change instructions for Mac OS X Terminal Autoload

Reference doc
http://hayne.net/MacDev/Notes/unixFAQ.html#shellStartup

On Terminal Load in OS X 10.10 .bashrc file was not loaded when using script

``` shell
echo "source dnvm.sh" >> ~/.bashrc
```

instead using .profile allows it to load as intended

``` shell
echo "source dnvm.sh" >> ~/.profile
```

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
