### ISSUE TITLE
dnu restore fails at OSX yosemite

### ISSUE THREAD

**Issue by dodyg** [aspnet/Home#661]
I followed the instruction in the following link
https://code.visualstudio.com/Docs/ASPnet5

and executed 

```
yo aspnet
```

then

```
dnu restore
```

It ran for a while and ended with the following failure

```
Could not find Zip file Directory at the end of the file. File may be corrupted
```

**Comment by salerth** [comment]
Looks like this SO question will help : http://stackoverflow.com/questions/29996556/dnu-restore-fails-on-mac/30016197#30016197

**Comment by dodyg** [comment]
Unfortunately no. 

```
dnu restore --no-cache.
```
simply generates another set of error

```
Argument cannot be null
Parameter name: stream
```

This is also the first time installation of dnvm.

**Comment by dodyg** [comment]
I only have one dnvm

```
1.0.0-beta4 mono 
```

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
