### ISSUE TITLE
How to retrieve the current response body length?

### ISSUE THREAD

**Issue by ycrumeyrolle** [aspnet/Home#664]
Following the StackOverflow question at http://stackoverflow.com/questions/30652138/how-to-retrieve-the-current-response-body-length

I am making a component for throttling requests. 
One of the throttling policy is to track the consumed bandwidth.
I would like to use the content length of the response for this scenario.
My code is something like that :
```C#
var decrementValue = httpContext.Response.Body.Length;
await _store.DecrementAsync(key, decrementValue);
```

The `Length` property is not useful because the undelying Stream is not readable. 
(Is is a bug ? https://github.com/aspnet/HttpAbstractions/wiki/Rolling-Notes-Response-Stream-Contract) 

@kichalla advise me to try with the OnSendingHeaders callback

```C#
long? length;
context.Response.OnResponseCompleted(s =>
{
    length = ((HttpContext)s).Response.ContentLength;
}, state: context);

context.Response.OnSendingHeaders(s =>
{
    length = ((HttpContext)s).Response.ContentLength;
}, state: context);
```

But it does not work in my case with a very simple test, length is `null`. 
Tried with the `Microsoft.AspNet.TestHost` & the `Microsoft.AspNet.Server.WebListener`, but I assume that my component could be used on any host. In my company it could be either on Kestrel or IIS.

For now the response body stream is wrapped by another stream capable of counting the content length at each write. 
I am not sure it is the best idea...

**Comment by davidfowl** [comment]
> For now the response body stream is wrapped by another stream capable of counting the content length at each write. 

You can't assume that the server is bufffering by default. If you want to do something like this then you need to put a piece of middleware in the pipeline that wraps the stream and counts the calls to Write or just replace it with a memory stream. Something like this https://github.com/darrelmiller/Mvc6Sandbox/blob/master/src/Mvc6Sandbox/Startup.cs, although it's not good to buffer the entire response into memory (unless you don't care about memory :smile: )

**Comment by ycrumeyrolle** [comment]
So my initial thought of a delegating stream seems to be correct.
Thanks !
