### ISSUE TITLE
Invalid IHostingEnvironment.EnvironmentName without debug

### ISSUE THREAD

**Issue by anfomin** [aspnet/Home#665]
If I run website without debugging in IIS express, `IHostingEnvironment.EnvironmentName` returns `Development` as expected. But if I change any source code file and just refresh page it returns `Production`.

I expect this property value should not change after automatic rebuild.

**Comment by BillHiebert** [comment]
I see the bug. On restart we aren't re-applying the last set of environment variables. It is passed a flag to do so, but it doesn't do it. TFS 1188573

**Comment by BillHiebert** [comment]
Checked in a fix for this.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
