### ISSUE TITLE
Restore pulling in wrong version of EF

### ISSUE THREAD

**Issue by Conrad2134** [aspnet/Home#667]
I have two projects in my solution - Web and BLL.

BLL references Entity Framework 6.1.3 and Web references BLL. This is fine, but when I do a restore on Web, it pulls in BLL with Entity Framework 7.0.0-beta4. I get that the version you specify in the project.json file is a minimum version, but should we really be going up major versions? The 6.1.3 and 7.0.0-beta4 are incompatible with each other. 

Is there a way around this or am I possibly doing something wrong? Also, if there's a better place for this issue, let me know.

BLL:
![image](https://cloud.githubusercontent.com/assets/3484188/8115961/b31c7d18-1044-11e5-9bc8-97372a5e089f.png)

Web:
![image](https://cloud.githubusercontent.com/assets/3484188/8115972/d105fd18-1044-11e5-8af4-4869698f611f.png)

**Comment by davidfowl** [comment]
Why is the version being pulled up to 7.0.0-beta4? What other package in your dependency graph depends on EF? BTW we're working on making this experience better in tooling so we show why a version was selected.

**Comment by Conrad2134** [comment]
Ahh, the "Microsoft.Framework.CodeGenerators.Mvc" package has a couple dependencies that use 7.0.0-beta4. Removed it, and it worked just fine. Now, if we're pulling in dependency A's version of EF, and I can't update dependency B's version of EF, what's the recommended solution for that issue? I see that version ranges might be introduced per [the dependency resolution docs](https://github.com/aspnet/Home/wiki/Dependency-Resolution). Will there ever be the ability to support two packages using their own, separate versions of the same dependency?

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
