### ISSUE TITLE
'dnvm use' breaks

### ISSUE THREAD

**Issue by markentingh** [aspnet/Home#668]
my user folder contains a space since I use my first & last name, which breaks the 'dnvm use' command.

error says system cannot find the path specified. "C:\Users\Mark"

running Windows 7 Pro x64

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
