### ISSUE TITLE
Restoring packages from relative path as a local package source fails

### ISSUE THREAD

**Issue by yishaigalatzer** [aspnet/Home#669]
Reported on stackoverflow - http://stackoverflow.com/questions/30243447/package-manager-in-vs2015-rc-fails-on-installing-restoring-some-packages

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
