### ISSUE TITLE
Different version in nuget.org and visual studio

### ISSUE THREAD

**Issue by yishaigalatzer** [aspnet/Home#670]
If I search for "Glass.Mapper.Sc" from within Visual Studio I do not see the same version as searching from nuget.org. Nuget.org is correctly showing the latest version where Visual Studio's seems to be behind.

Moved from https://github.com/NuGet/NuGetGallery/issues/2541

**Comment by cardinal252** [comment]
I am using Visual Studio 2013 with all updates installed

**Comment by yishaigalatzer** [comment]
Do you still see the difference?

**Comment by davidfowl** [comment]
@yishaigalatzer should this be on NuGet/Home

**Comment by cardinal252** [comment]
Yes - the issue is still occurring.

**Comment by yishaigalatzer** [comment]
@davidfowl yes my bad
