### ISSUE TITLE
dnvm upgrade fails with Unable to find any runtime package on the feed!

### ISSUE THREAD

**Issue by marcos2** [aspnet/Home#672]
I am trying to run command dnvm upgrade and getting this:

```
C:\Program Files\Microsoft DNX\Dnvm\dnvm.ps1 : Unable to find any runtime packa
ges on the feed!
At line:1 char:189
+ ... t-envvars.cmd';& 'C:\Program Files\Microsoft DNX\Dnvm\dnvm.ps1' upgrade
+                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorExcep
   tion
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorExceptio
   n,dnvm.ps1
```

here is my output from dnvm list: 

```
c:\Users\user1>dnvm list

Active Version     Runtime Architecture Location                            Ali
                                                                            as
------ -------     ------- ------------ --------                            ---
       1.0.0-beta4 clr     x64          C:\Users\user1\.dnx\runtimes
       1.0.0-beta4 clr     x86          C:\Users\user1\.dnx\runtimes def
       1.0.0-beta4 coreclr x64          C:\Users\user1\.dnx\runtimes
       1.0.0-beta4 coreclr x86          C:\Users\user1\.dnx\runtimes
```

Output from dnvm name: 

```
C:\Program Files\Microsoft DNX\Dnvm\dnvm.ps1 : Cannot bind argument to parameter 'Version' because it
 is an empty string.
At line:1 char:189
+ ... t-envv
```

Any idea how to fix this?

**Comment by RehanSaeed** [comment]
Are you running behind a proxy? I am having the same problem. You have to set an environment variable in your system properties named http_proxy with the value:

http://DOMAIN\USERNAME:PASSWORD@PROXY:PORT

Special characters have to be escaped e.g. %40 for @ in your password. I've followed this and it still does not work on my work machine. Works fine at home with no proxy.

**Comment by tlk** [comment]
Perhaps #729 could be useful?

**Comment by sirhcybe** [comment]
I was getting the same error as marcos2 and I am behind a proxy so I set the http_proxy variable as described above. Now I get this error: 
C:\Program Files (x86)\Microsoft Visual Studio 14.0>dnvm upgrade
Determining latest version
C:\Program Files\Microsoft DNX\Dnvm\dnvm.ps1 : Exception calling ".ctor" with "1" argument(s): "Invalid URI: The hostname could not be parsed."
At line:1 char:182
+ ... t-envvars.cmd';& 'C:\Program Files\Microsoft DNX\Dnvm\dnvm.ps1' upgrade
+                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,dnvm.ps1

The same steps worked fine on a PC outside of the proxy, Any suggestions? Is there a way to manually download an update?

**Comment by sirhcybe** [comment]
Stepping through the dnvm.ps1 file helped me figure this out. The http_proxy variable only needs to be set to PROXY:PORT, the script handles authentication. Setting something like this in command prompt should work: "set http_proxy=127.0.0.1:8080" or "$env:http_proxy='127.0.0.1:8080'" in PowerShell

Also, I found the IP and port of my proxy with this PowerShell command: "(get-itemproperty 'HKCU:\Software\Microsoft\Windows\CurrentVersion\Internet Settings').ProxyServer"

**Comment by roblom** [comment]
I had the same problem as marcos2.
In my case it was the environment variable DNX_FEED having quotes around its value.
Wrong: set DNX_FEED="https://www.nuget.org/api/v2"
Correct: set DNX_FEED=https://www.nuget.org/api/v2

**Comment by stajs** [comment]
There seems to be a bug with upgrading behind a proxy server. I'm on dnvm v1.0.0-beta8-15506 (latest at time of writing). Specifying a proxy server argument to upgrade:

```
dnvm upgrade -Proxy <server>:<port>
```

... produces:

```
Determining latest version
Unable to find any runtime packages on the feed!
At C:\Users\<user>\.dnx\bin\dnvm.ps1:584 char:9
+         throw "Unable to find any runtime packages on the feed!"
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Unable to find ...es on the feed!:String) [], RuntimeException
    + FullyQualifiedErrorId : Unable to find any runtime packages on the feed!
```

The `-Proxy` parameter is not being passed to the method calls `Find-Latest` and `Invoke-NuGetWebRequest`. Editing `C:\Users\<user>\.dnx\bin\dnvm.ps1` line 1335 from:

```
$findPackageResult = Find-Latest -runtimeInfo:$runtimeInfo -Feed:$selectedFeed
```

... to:

```
$findPackageResult = Find-Latest -runtimeInfo:$runtimeInfo -Feed:$selectedFeed -Proxy:$Proxy
```

... produces a much more pleasing:

```
Determining latest version
'dnx-clr-win-x86.1.0.0-beta7' is already installed in C:\Users\<user>\.dnx\runtimes\dnx-clr-win-x86.1.0.0-beta7.
Adding C:\Users\<user>\.dnx\runtimes\dnx-clr-win-x86.1.0.0-beta7\bin to process PATH
Adding C:\Users\<user>\.dnx\runtimes\dnx-clr-win-x86.1.0.0-beta7\bin to user PATH
Updating alias 'default' to 'dnx-clr-win-x86.1.0.0-beta7'
```

Also, you might as well also add the proxy on line 1338, from:

```
$findPackageResult = Find-Package -runtimeInfo:$runtimeInfo -Feed:$selectedFeed
```

...to:

```
$findPackageResult = Find-Package -runtimeInfo:$runtimeInfo -Feed:$selectedFeed -Proxy:$Proxy
```

**Comment by simonfanz** [comment]
It looks like the line referenced by @stajs to fixed this has changed slightly, but the idea is still the same:

line 1084 needs the proxy parameter added:

$VersionNuPkgOrAlias = Find-Latest $Runtime $Architecture -Feed:$selectedFeed -Proxy:$Proxy

**Comment by stajs** [comment]
@simonfanz My suggestions got merged in here: https://github.com/aspnet/dnvm/pull/454

If you have found another area where the proxy needs to be passed along, you should submit a PR.

**Comment by simonfanz** [comment]
@stajs Ah thanks, indeed you are right.  No, I suspect I've just come across an old version of dnvm.ps1 (which  currently installs as part of the vnext beta8 preview linked from http://www.asp.net/vnext)

**Comment by stajs** [comment]
@simonfanz Sorry, I should have clarified. Yes beta8 is still the current version (at time of writing) and yes, will require you to manually hack to work around proxies. That merge is linked to the RC1 milestone, so expect it to land with that.

**Comment by SonizciTR** [comment]
Hi guys;

My company uses proxy and I have the same problem. I tried adding environment variable and -Proxy argument but nothing work.
At last i found the solution:
At "dnvm.ps1" file there is "Apply-Proxy" function. when no pass if check; i delete the line and added 2 new default proxy setting. I works like charm. 
I modified it like this:

function Apply-Proxy {
param(
  [System.Net.WebClient] $wc,
  [string]$Proxy
)
  if (!$Proxy) {
    $Proxy = $env:http_proxy
  }
  if ($Proxy) {
    $wp = New-Object System.Net.WebProxy($Proxy)
    $pb = New-Object UriBuilder($Proxy)
    if (!$pb.UserName) {
        $wp = [System.Net.WebRequest]::DefaultWebProxy
        $wp.Credentials = [System.Net.CredentialCache]::DefaultNetworkCredentials
    } else {
        $wp.Credentials = New-Object System.Net.NetworkCredential($pb.UserName, $pb.Password)
    }
    $wc.Proxy = $wp
  }
}

Hope this will help.

**Comment by AlecTheGreat** [comment]
@SonizciTR Your Apply-Proxy fix worked for me. Thanks!

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
