### ISSUE TITLE
Add dll to Vnext project

### ISSUE THREAD

**Issue by VnextIsNotFriendlyAtAll** [aspnet/Home#674]
I am trying to add dll to vnext project like this ("MapSuiteCore.DLL"):

``` JSON
"frameworks": {
    "dnx451": {
      "bin": {
        "assembly": "C:\\Program Files (x86)\\ThinkGeo\\Map Suite 8.0\\Map Suite MVC\\Current Version\\Managed Assemblies\\MapSuiteCore.DLL"
      },
      "dependencies": {
      },
      "frameworkAssemblies": {
        "System.ServiceModel": "4.0.0.0"
      }
    }
  },
```

But having such error:
![capture](https://cloud.githubusercontent.com/assets/12902262/8171382/332b330e-13c0-11e5-81c5-716b49f9be24.JPG)

Is it possible to solve this errors somehow? I tried many techniques to add dll, but still no success...

**Comment by davidfowl** [comment]
The error message is saying that there's not Startup class. I don't think it has anything to do with the assembly, although in this case that's not defined properly either. If you want to reference an assembly you can use `dnu wrap {path to assembly}`

**Comment by VnextIsNotFriendlyAtAll** [comment]
Project has Startup class. Project was created from template: ASP.NET Web Application -> Web Site (ASP.NET 5 Preview Templates). So Project includes Startup class by default.

Also if I comment this line like so:
```JSON
      "bin": {
        //"assembly": "C:\\Program Files (x86)\\ThinkGeo\\Map Suite 8.0\\Map Suite MVC\\Current Version\\Managed Assemblies\\MapSuiteCore.DLL"
      },
```
Error disappears.

More information about "dnu wrap" usage would be useful. Thanks.

**Comment by davidfowl** [comment]
@VnextIsNotFriendlyAtAll Start off with the help on the command itself. 

```
dnu help wrap
Microsoft .NET Development Utility Mono-x86-1.0.0-beta6-12032

Usage: dnu wrap [arguments] [options]

Arguments:
  [path]  Path to csproj/assembly to be wrapped

Options:
  --configuration <CONFIGURATION>  Configuration of wrapped project, default is 'debug'
  --msbuild <PATH>                 Path to MSBuild, default is '%ProgramFiles%\MSBuild\14.0\Bin\MSBuild.exe'
  -i|--in-place                    Generate or update project.json files in project directories of csprojs
  -f|--framework                   Target framework of assembly to be wrapped
  -?|-h|--help                     Show help information
```

We don't have full documentation for `dnu wrap yet`. The flow is you run `dnu wrap {path to assembly}` so in your case 

`dnu wrap "C:\Program Files (x86)\ThinkGeo\Map Suite 8.0\Map Suite MVC\Current Version\Managed Assemblies\MapSuiteCore.DLL"`

**Comment by VnextIsNotFriendlyAtAll** [comment]
I executed command (also needed to set framework):
```
C:\Users\James\Documents\Visual Studio 2015\Projects\WebApplication3>"C:\Progra
m Files (x86)\Microsoft Web Tools\DNX\dnx-clr-win-x86.1.0.0-beta4\bin\dnu.cmd" w
rap "C:\Program Files (x86)\ThinkGeo\Map Suite 8.0\Map Suite MVC\Current Version
\Managed Assemblies\MapSuiteCore.DLL" -f 4.5


Wrapping project 'MapSuiteCore' for '.NETFramework,Version=v4.5'
  Source C:\Program Files (x86)\ThinkGeo\Map Suite 8.0\Map Suite MVC\Current Ver
sion\Managed Assemblies\MapSuiteCore.DLL
  Target C:\Users\James\Documents\Visual Studio 2015\Projects\WebApplication3\w
rap\MapSuiteCore\project.json
Wrapping project 'CSScriptLibrary' for '.NETFramework,Version=v4.5'
  Source C:\Program Files (x86)\ThinkGeo\Map Suite 8.0\Map Suite MVC\Current Ver
sion\Managed Assemblies\CSScriptLibrary.dll
  Target C:\Users\James\Documents\Visual Studio 2015\Projects\WebApplication3\w
rap\CSScriptLibrary\project.json
Wrapping project 'GeoAPI' for '.NETFramework,Version=v4.5'
  Source C:\Program Files (x86)\ThinkGeo\Map Suite 8.0\Map Suite MVC\Current Ver
sion\Managed Assemblies\GeoAPI.dll
  Target C:\Users\James\Documents\Visual Studio 2015\Projects\WebApplication3\w
rap\GeoAPI\project.json
Wrapping project 'Microsoft.SqlServer.Types' for '.NETFramework,Version=v4.5'
  Source C:\Program Files (x86)\ThinkGeo\Map Suite 8.0\Map Suite MVC\Current Ver
sion\Managed Assemblies\Microsoft.SqlServer.Types.dll
  Target C:\Users\James\Documents\Visual Studio 2015\Projects\WebApplication3\w
rap\Microsoft.SqlServer.Types\project.json
Wrapping project 'NetTopologySuite' for '.NETFramework,Version=v4.5'
  Source C:\Program Files (x86)\ThinkGeo\Map Suite 8.0\Map Suite MVC\Current Ver
sion\Managed Assemblies\NetTopologySuite.dll
  Target C:\Users\James\Documents\Visual Studio 2015\Projects\WebApplication3\w
rap\NetTopologySuite\project.json
Wrapping project 'GeoAPI' for '.NETFramework,Version=v4.5'
  Source C:\Program Files (x86)\ThinkGeo\Map Suite 8.0\Map Suite MVC\Current Ver
sion\Managed Assemblies\GeoAPI.dll
  Target C:\Users\James\Documents\Visual Studio 2015\Projects\WebApplication3\w
rap\GeoAPI\project.json
```

Wrapping seems to be ok, but when I try to add "MapSuiteCore" : "1.0.0-*" in to "project.json" I get error:
![capture1](https://cloud.githubusercontent.com/assets/12902262/8178015/2ff4c544-1413-11e5-8e22-693637441e76.JPG)
This error appears in all projects. I guess reinstall of visual studio might help...

When I try to compile I get error:
NuGet Package Restore failed for one or more packages. See details in the Output window.
Dependency MapSuiteCore >= 1.0.0-* could not be resolved
Will this error disappear if I will fix the one above with visual studio reinstall?

**Comment by davidfowl** [comment]
There's currently a bug in the beta4 version of wrap where it creates the wrap folder in the wrong location. You might be running into that. Make sure you have a global.json next to your solution root before running wrap on the assembly then try again.

**Comment by GuardRex** [comment]
@davidfowl Tried to follow you on this, but it's not working.

I upgraded my runtimes. I'm working with `dnx-coreclr-win-x64.1.0.0-beta6-12081` for this project (Win10 preview build 10130; VS 2015 RC).

I want to work with ADAL and the `Microsoft.IdentityModel.ActiveDirectory.Client` namespace in the `azure-activedirectory-library-for-dotnet-3.3.205061641` package. I pull that down locally and open the project for `ADAL.NET`. I unload `ADAL.NET.WindowsForms` and the `tests` ... not needed for what I'm doing. I build and get `C:\azure-activedirectory-library-for-dotnet-3.3.205061641\bin\Release\Microsoft.IdentityModel.Clients.ActiveDirectory.dll` and see it's associated pdb file is there, too.

I run `dnu wrap C:\azure-activedirectory-library-for-dotnet-3.3.205061641\bin\Release\Microsoft.IdentityModel.Clients.ActiveDirectory.dll --framework 4.5`

I have the wrap folder with its `project.json` file, and I get a `"wrap"` entry in the `projects` of `global.json` in my project.

I go into my project's `project.json` and add `"Microsoft.IdentityModel.Clients.ActiveDirectory": ""`. VS does a package restore, but the references show that the namespace is not found.

What did I miss?

**Comment by davidfowl** [comment]
@GuardRex My first question is why not use the ADAL package? Second is, can you push a repro to github so I can take a look?

/cc @ChengTian

**Comment by GuardRex** [comment]
@davidfowl I'm not using the ADAL NuGet package due to an [apparent bug](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/issues/206) in a dependency inside of `System.Runtime.Serialization.Json`. I was going to simply swap out the serialization mechanism in ADAL for `Newtonsoft.Json` to bypass the issue until that team fixes the NuGet package.

https://github.com/GuardRex/AzureADTest50git

I added the ADAL DLL+PDB files ... they are in ADAL.zip

It also occurred to me that if the DLL I was trying to hook required some of the other DDL's from ADAL, such as `Microsoft.Owin.dll`, `System.IdentityModel.Tokens.Jwt.dll`, etc. that I would need to `dnu wrap` those as well. I did that ... I wrapped everything in the ADAL `bin` folder, but the reference to ADAL still failed. I ended up just going back to only having the ADAL DLL wrapped.

**Comment by davidfowl** [comment]
The bug in your project is that the wrapped assembly is targeting net45 and your project is targeting dnxcore50 (our error messages suck :smile: )

**Comment by GuardRex** [comment]
@vibronet Ok. I didn't think that would be an issue, because their sample project [project.json](https://github.com/AzureADSamples/WebApp-WebAPI-OpenIdConnect-AspNet5/blob/master/TodoListWebApp/project.json) targets Core CLR (naming the old `aspcorenet50`; put up in early March, which explains the old naming). That project calls for 
```
"Microsoft.IdentityModel.Clients.ActiveDirectory": "3.1.203031538-alpha"
```
I wonder if they ever attempted to run their own project with the Core CLR runtime ... I guess not or they would have hit this.

I'll see if I can incorporate ADAL into my project directly from their source. Thanks for your help.
