### ISSUE TITLE
I had to use the old v2 NuGet source in order to get the latest version of a package I needed.

### ISSUE THREAD

**Issue by GuardRex** [aspnet/Home#675]
I'm waiting for some help with [AAD/ADAL/Graph API](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/issues/206); but in the meantime, I noticed that my request for
```
"Microsoft.IdentityModel.Clients.ActiveDirectory": "3.1.203031538-alpha"
```
isn't for the latest ActiveDirectory NuGet package. There is a [`3.3.205061641-alpha` package available](https://www.nuget.org/packages/Microsoft.IdentityModel.Clients.ActiveDirectory/3.3.205061641-alpha).

My initial package sources were
```
https://www.myget.org/F/aspnetrelease/
https://api.nuget.org/v3/index.json
```
When I used
```
"Microsoft.IdentityModel.Clients.ActiveDirectory": "3.3.205061641-alpha"
```
package restore resulted in
```
Unable to locate Microsoft.IdentityModel.Clients.ActiveDirectory >= 3.3.205061641-alpha
```
It wasn't until I reactivated the package source for 
```
https://www.nuget.org/api/v2/
```
that I was able to get that latest package.

My questions are: Is there any harm in using that v2 source as my last package source in the list? Why isn't that latest ActiveDirectory package available via my original package sources?

**Comment by davidfowl** [comment]
NuGet v3 was implemented in dnu only a few days ago. You need to enable the V2 source until you get the latest update.
