### ISSUE TITLE
MusicStore database in memory?

### ISSUE THREAD

**Issue by tempdata** [aspnet/Home#677]
Couple of questions. We started looking at MusicStore for our new website.
1. I am trying to find out where the database for MusicStore is. Is it created in memory?
2. What are other projects? MusicStore, MvcMusicStore, MusicStore.spa, MvcMusic,spa? Do any of these need a datbase on local sql server?

Thanks

**Comment by davidfowl** [comment]
Why not file this on the MusicStore repository?

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
