### ISSUE TITLE
fresh dnvm install windows 7 has difficulty doing it's job because of folder permissions

### ISSUE THREAD

**Issue by fir3pho3nixx** [aspnet/Home#680]
Hi 

I tried installing this on windows(without Visual Studio) using the following powershell script: 

    @powershell -NoProfile -ExecutionPolicy unrestricted -Command "&{$Branch='dev';iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.ps1'))}"

My paths all appeared to come out fine. I could run

    dnvm help 

and it would return the help screen. However when I ran 

    dnvm list

The list was always empty. So then I tried 

    dnvm upgrade

and this appeared to download the beta binary `dnx-clr-win-x86.1.0.0-beta4` to `temp` folder in my users profile but failed because of folder permissions. See below:

    Move-Item : Access to the path 'C:\Users\Gavin\.dnx\runtimes\temp\dnx-clr-win-x86.1.0.0-beta4' is denied.

Once I correct permissions to the `temp` folder everything started working again. I made sure I ran the scripts in shell windows with admin privileges. You guys getting this on later versions of windows?

**Comment by Eilon** [comment]
Can you log the issue in https://github.com/aspnet/dnvm/issues/ ? That's the best place to log dnvm issues.

**Comment by fir3pho3nixx** [comment]
Sorry, my bad :)

Moved to:
https://github.com/aspnet/dnvm/issues/336
