### ISSUE TITLE
DNVM text output hard to read when using custom PowerShell color settings

### ISSUE THREAD

**Issue by erikojebo** [aspnet/Home#683]
### DNVM shoud use standard output colors 
Currently the dnvm command uses different text colors for the PowerShell output when invoked without arguments or with the help argument. This is a problem for users who have customized the colors of their PowerShell console, for example using a Microsoft.PowerShell_profile.ps1 file.

### Minimal repro steps
Invoke the following PowerShell commands in a PowerShell console:

    $console = $host.UI.RawUI
    $console.ForegroundColor = "black"
    $console.BackgroundColor = "white"
    cls
    dnvm

### Expected result
All text output from the dnvm command should be easily readable, no matter the color preferences of the user's console.

### Actual result
Portions of the text output is more or less unreadable when using a white background and black foreground in the PowerShell console.

![dnvm_color_output](https://cloud.githubusercontent.com/assets/256015/8260856/915c310e-16c6-11e5-8bb9-46ede8606865.PNG)

**Comment by Eilon** [comment]
Thanks, my eyes burned out when I looked at the screenshot :smile: 

Can you log the bug in https://github.com/aspnet/dnvm/issues/ ? That's the best place to log dnvm issues.

**Comment by erikojebo** [comment]
Thanks for the pointer to the appropriate repo! I'll add the issue there.
