### ISSUE TITLE
Type 'TextWriter' is defined in an assembly that is not referenced error after upgrading to beta4

### ISSUE THREAD

**Issue by kevinkuszyk** [aspnet/Home#690]
I have recently upgraded [R4MVC](https://github.com/T4MVC/R4MVC) to the `beta4` bits.  It [was building](https://ci.appveyor.com/project/T4MVC/r4mvc/build/99), but now we get the [following error](https://ci.appveyor.com/project/T4MVC/r4mvc/build/104) on `dnx451` as well as many others on `dnxcore50`:

```
error CS0012: The type 'TextWriter' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.IO, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
```

I have updated to the new TFMs as per [the announcement](https://github.com/aspnet/Announcements/issues/3).  I suspect we have some packages which are not compatble with `beta4`, but I don't know where to look to find out which ones. 

This is the [project.json](https://github.com/T4MVC/R4MVC/blob/7d2b5a8642f44608091e8ae8738e00f2a21afccd/src/R4Mvc/project.json):

``` json
{
  "version": "1.0.0-*",
  "dependencies": {
    "Microsoft.CodeAnalysis.CSharp": "1.0.0-rc2",
    "System.Text.Encoding": "4.0.10-beta-*",
    "System.IO": "4.0.10-beta-*",
    "Microsoft.AspNet.Mvc": "6.0.0-beta4",
    "Microsoft.Framework.Runtime.Roslyn": "1.0.0-beta4",
    "Microsoft.Framework.ConfigurationModel.Json": "1.0.0-beta4"
  },
  "frameworks": {
    "dnx451": {
      "dependencies": {
      }
    },
    "dnxcore50": {
      "dependencies": {
        "System.Runtime": "4.0.20-beta-*"
      }
    }
  }
}
```

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
