### ISSUE TITLE
Enh Req: Create a Chocolatey package for DNVM

### ISSUE THREAD

**Issue by rkeithhill** [aspnet/Home#693]
OK so it is a one liner to install DNVM from PowerShell but don't ask anybody to remember that one liner. They'll have to look it up each time.  

What I would like to tell people is to bring up PowerShell V5 (if you don't have V5 go get it) and execute `Install-Package dnvm`.  Now wouldn't that be much nicer?

**Comment by Bartmax** [comment]
:+1:

**Comment by RehanSaeed** [comment]
+1

**Comment by Jeffiy** [comment]
+1

**Comment by RehanSaeed** [comment]
This needs to be updated for .NET Core.

**Comment by natemcmaster** [comment]
dnvm is obsolete. If you still feel this is important, I recommend you request this here: https://github.com/dotnet/cli
