### ISSUE TITLE
Checklist to track aspnet org-wide FreeBSD compatible shell scripts

### ISSUE THREAD

**Issue by jasonwilliams200OK** [aspnet/Home#695]
- [x] Antiforgery
- [x] aspnet-docker  *(this was already done the right way)*
- [x] BugTracker
- [x] Caching
- [x] Common
- [x] Configuration
- [x] CORS
- [x] DataProtection
- [x] DependencyInjection
- [x] Diagnostics
- [x] dnvm
- [x] dnx
- [x] EntityFramework
- [x] Entropy
- [x] EventNotification
- [x] FileSystem
- [x] Home
- [x] Hosting
- [x] HttpAbstractions
- [x] HttpClient
- [x] Identity
- [x] KestrelHttpServer
- [x] Localization
- [x] Logging
- [x] Microsoft.Data.Sqlite
- [x] MusicStore
- [x] Mvc
- [x] Options
- [x] Razor
- [x] Routing
- [x] Scaffolding
- [x] Security
- [x] ServerTests
- [x] Session
- [x] SignalR-Redis
- [x] SignalR-Server
- [x] SignalR-ServiceBus
- [x] SignalR-SqlServer
- [x] Signing
- [x] StaticFiles
- [x] Testing
- [x] Tooling
- [x] Universe
- [x] UserSecrets
- [x] WebSockets

Based on @dougbu's comment https://github.com/aspnet/dnx/pull/2066#issuecomment-112654094, this issues tracks changes needs to be made in all the aspnet repositories which have `*.sh` files (for building and executing tests on Linux), in order to make the scripts BSD-compatible.

The idea is to replace this shebang `#!/bin/bash`, which appears at the beginning of each `.sh` file, with cross-Unix compatible `#!/usr/bin/env bash`.

For that matter, I fetched the following list form https://github.com/aspnet/repositories (using javascript in firebug :smile:) and removed those which do not have bash scripts (yet?):

*(tried using `curl -u "jasonwilliams200OK" https://api.github.com/orgs/aspnet/repos?type=all `, but it only returns 30 repos at a time :disappointed:)*

Also inviting: @josteink, @saper, @janhenke, @ghuntley and @ajensenwaud. Feel free to send similar PRs to the remaining repos guys. :trollface:

**Comment by dougbu** [comment]
I checked off a large number tentatively. All Universe sub-directories be handled using bit of scripting. Much easier for me than dealing with than individual PRs.

**Comment by dougbu** [comment]
(Unfortunately would have to copy and paste the checkbox list or convert somehow to make the tentative status clear.)

**Comment by jasonwilliams200OK** [comment]
@dougbu, as an owner, you can uncheck / uncheck the list by clicking on checkbox?
Also opened a PR at nuget: https://github.com/NuGet/NuGet3/pull/61 :smile:

**Comment by dougbu** [comment]
Specific commits:
- aspnet/AntiForgery@e8ac98a
- aspnet/Caching@69c46c5
- aspnet/Common@4ecfbd7
- aspnet/Configuration@0b2a030
- aspnet/CORS@88fa7fb
- aspnet/DataProtection@5aaae8b
- aspnet/DependencyInjection@de80186
- aspnet/Diagnostics@4aa1d4b
- aspnet/EntityFramework@f019bdb
- aspnet/Entropy@82f2aaf
- aspnet/FileSystem@a676c9c
- aspnet/Helios@f297bf7
- aspnet/Hosting@0013d44
- aspnet/HttpAbstractions@c83ff60
- aspnet/Identity@d5c9599
- aspnet/KestrelHttpServer@14c4f46
- aspnet/Logging@5c5008a
- aspnet/MusicStore@30b7c31
- aspnet/Mvc@a291884
- aspnet/Options@7292c3e
- aspnet/Razor@a73867e
- aspnet/RazorTooling@f7a1717
- aspnet/Routing@864d5e0
- aspnet/Scaffolding@0543fc6
- aspnet/Security@43b4289
- aspnet/Session@c858e3b
- aspnet/SignalR-Redis@da4441f
- aspnet/SignalR-Server@b3433b0
- aspnet/SignalR-SQLServer@7da7fe2
- aspnet/StaticFiles@445e046
- aspnet/Testing@8515aa3
- aspnet/UserSecrets@fb28c04
- aspnet/WebListener@41dba1f
- aspnet/WebSockets@210c732

> you can uncheck / uncheck the list by clicking on checkbox?

Yup.

**Comment by dougbu** [comment]
Three more checked off:
- BugTracker doesn't contain any `*.sh` scripts
- aspnet/EventNotification@19f7250
- aspnet/Localization@a710c55

@muratg I know aspnet/HttpClient and aspnet/Microsoft.Data.Sqlite are or were temporary repos. Are they already unused? What is the status of aspnet/ServerTests, aspnet/SignalR-ServiceBus, aspnet/Signing and aspnet/Tooling?

**Comment by josteink** [comment]
Just want to applaud the amazing effort in this otherwise "trivial" issue. Good job, guys :)

**Comment by muratg** [comment]
@dougbu We do not have a cross-plat httpclient yet so that repo is still required.  Microsoft.Data.Sqlite repo is for the EF Sqlite provider so that's also still required.  ServerTests contains functional tests that are shared across Helios, WebListener and Kestrel.  SignalR-ServiceBus is for the scale-out provider, but no ongoing work there at the moment. Signing I'm not sure. Tooling is for tracking WTE bugs only.

**Comment by NTaylorMullen** [comment]
Done, `HttpClient`, `Signing` and `Tooling` didn't need to be done. I recommend removing them from the list :smile:

**Comment by dougbu** [comment]
FYI last few commits (thanx @NTaylorMullen) were:
- aspnet/Microsoft.Data.Sqlite@c2747fe6
- aspnet/ServerTests@c77f397
- aspnet/SignalR-ServiceBus@ee3752d

**Comment by jasonwilliams200OK** [comment]
Thanks a million @dougbu and team! :+1: :100:
