### ISSUE TITLE
Docker HelloWeb doesn't work

### ISSUE THREAD

**Issue by luebken** [aspnet/Home#696]
I've tried to follow this guide http://blogs.msdn.com/b/webdev/archive/2015/01/14/running-asp-net-5-applications-in-linux-containers-with-docker.aspx

And get the error:
``` 
But I get the error: ○ → docker run -P asp-docker
System.InvalidOperationException: Failed to resolve the following dependencies for target framework 'DNX,Version=v4.5.1':
Kestrel 1.0.0-beta3
Microsoft.AspNet.Diagnostics 1.0.0-beta3
Microsoft.AspNet.Hosting 1.0.0-beta3
Microsoft.AspNet.Server.WebListener 1.0.0-beta3
Microsoft.AspNet.StaticFiles 1.0.0-beta3

Searched Locations:
/{name}/project.json
/root/.dnx/packages/{name}/{version}/{name}.nuspec
/usr/lib/mono/4.5/{name}.dll
/usr/lib/mono/4.5/Facades/{name}.dll
```

Full code can be found here: https://github.com/luebken/asp-docker

**Comment by tlk** [comment]
Go for the dev branch rather than master. Also, see #537 (shameless plug).

**Comment by Eilon** [comment]
@ahmetalpbalkan any ideas?

**Comment by ahmetalpbalkan** [comment]
Issue moved to https://github.com/aspnet/aspnet-docker/issues/67 we can close this one.
