### ISSUE TITLE
Images and WebAPI using MVC 6

### ISSUE THREAD

**Issue by ducalai** [aspnet/Home#697]
As HttpResponseMessage does not exist anymore in vNext, what is the recommended way to return an image stored as a byte array in WebAPI ? Setting Response Header ContentType seems to be ignored and overrided by JsonOutputFormatter

Thanks for your help
Alain

**Comment by rynowak** [comment]
Use `FileContentResult`

https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.Extensions/FileContentResult.cs#L28

**Comment by ducalai** [comment]
Great!. Thanks!
