### ISSUE TITLE
Raspberry Pi clean install with lock.json access denied issues.

### ISSUE THREAD

**Issue by ppumkin** [aspnet/Home#698]
Clean Pi with everything updated and upgraded. Using default Pi user.
Installed MONO v4 from xamarin branch and compiled libuv with make and make install

When I clone into the sample repository with `sudo git clone -b dev http://` and then do a `dnu restore`

```
Writing lock file /Home/samples/1.0.0-beta4/HelloMvc/project.lock.json

Restore failed
Access to the path "/Home/samples/1.0.0-beta4/HelloMvc/project.lock.json" is denied.
```

So I tried the dangerous give all access, cause it says access to the path is denied.. pretty obvious.

```
 sudo chmod -R 0777 /Home/
```

The console now lights up in neon green, I assume it means something after applying 0777 and... that fixed it. 

I tried `chmod` for user Pi group Pi that didn't help. Not sure what to use. 

It is obvious issue because  I did a git clone as user Pi with `sudo git clone`, which created everything as root. 

But this was not a problem before, I mean like last month I tried and it was still OK. Only the latest DNU from like today (or most recent publish) has this issue. 

But we cant run `sudo dnu restore`

**Comment by ppumkin** [comment]
I think the correct fix is to do a 

     chown -R pi /Home

This is not reflected in the help pages and caused me a bit of head scratching. Linux newb here.

**Comment by Tratcher** [comment]
@DamianEdwards @moozzyk

**Comment by mmillican** [comment]
For what it's worth, I was having lots of issues restoring packages on OSX.  doing `chown` on the dnx packages folder fixed it.

```
sudo chown -R [user]  /Users/[user]/.dnx/packages
```

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
