### ISSUE TITLE
dnx : The term 'dnx' is not recognized as the name of a cmdlet

### ISSUE THREAD

**Issue by KalpeshChheda** [aspnet/Home#700]
Hi team,

I have install Visual Studio 2015 RC but while running any dnx command i am seeing below logs.
My dnvm command is working fine.

>PM> dnx . ef migration add test
dnx : The term 'dnx' is not recognized as the name of a cmdlet, function, script file, or operable program.

**Comment by darrenscrine** [comment]
Hi, how did you resolve this?

**Comment by KalpeshChheda** [comment]
Its not working. But as a workaround I am using powershell to run dnx commands.
