### ISSUE TITLE
Is the Model Binders collection static in VNEXT?

### ISSUE THREAD

**Issue by isabgol** [aspnet/Home#701]
Model binders is a static collection in current ASP.NET MVC -- does it continue to be static?

**Comment by davidfowl** [comment]
No, it is not static

**Comment by rynowak** [comment]
You can configure model binders for the whole app in options (startup code): https://github.com/aspnet/Mvc/blob/dev/test/WebSites/ModelBindingWebSite/Startup.cs#L22

Or you can configure it as part of a resource filter if you just want to affect a set of actions. Is there anything in particular that you're trying to accomplish?
