### ISSUE TITLE
New script variable for the artifact directory of a project

### ISSUE THREAD

**Issue by jpoehls** [aspnet/Home#704]
I'm writing a project.json postbuild script that needs to copy the DLLs out of the artifacts directory for the project. It would be very nice if there were a `%project:ArtifactDirectory%` variable that pointed to that folder.

In addition to that I'm also missing the SolutionDirectory and Configuration being available as variables.

**Comment by davidfowl** [comment]
SolutionDirectory would have to be the global.json directory, as you may not have a solution. The artifacts directory is a pure convention at the moment so I'm not 100% on that one, though it would be nice. We have a bug to look at adding configuration https://github.com/aspnet/dnx/issues/887

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
