### ISSUE TITLE
Custom route with extension

### ISSUE THREAD

**Issue by robertsundstrom** [aspnet/Home#705]
I try to achieve something like this, a route with an extension (.js):

```
[HttpGet]
[Route("~/signalr/hubs.js")]
public IActionResult Path()
{
    return Redirect("~/signalr/js");
}
```

This is for SystemJS, that adds .js to the paths of imported modules.

It worked by default in previous versions. How do I enable it now?

**Comment by Eilon** [comment]
@robertsundstrom is the action getting hit, but it's not working? Or is the action not even getting hit?

Also, which web server/platform are you using? And which build of the packages?

**Comment by robertsundstrom** [comment]
I'm using beta4. Have been trying both IIS and Kestrel. How do I enable such routes?

Btw. I solved my main problem by configuring SystemJS.

**Comment by Eilon** [comment]
I got it to work using beta5, but the same should work in beta4 as well. I didn't try Kestrel but I did try WebListener and those two servers work in a very similar manner. Neither of those servers should require any special configuration with the MVC action you showed.

In IIS the tricky thing is that IIS by default handles all requests that have "known" file extensions, and `*.js` is a known extension. You have to enable `runAllManagedModulesForAllRequests` to ensure that IIS allows ASP.NET a chance at every request.

Go to `wwwroot/web.config` and add this setting in the `<system.webServer>` section:

```xml
        <modules runAllManagedModulesForAllRequests="true"></modules>
```

And then it should work.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
