### ISSUE TITLE
`Configure` vs `ConfigureServices`

### ISSUE THREAD

**Issue by adamvoss** [aspnet/Home#706]
I think some guidance, guidelines, or intentions on what belongs in `ConfigureServices` versus `Configure` could be useful.  The answer may be really simple, but I am struggling to see the right division myself at the moment.

For example with the MVC middleware, configuration is done in `ConfigureServices` and cannot be specified via a `UseMvc` overload.

```
services.Configure<MvcOptions>(
    options =>
        {
            //  ...
        } );
```

However, the Diagnostics middleware requires configuration happen in `Configure`:

```
app.UseErrorPage( new ErrorPageOptions { ShowCookies = true, ShowSourceCode = false } );
```

On the surface this seems inconsistent.  While I am sure consistency cannot be forced, an accepted convention would make it easier for users (developers) to know where or whether to do configuration when working with a new component.

I do think that overall the distinction between the two can be useful (current multi-tenancy issues aside), I just have not fully grokked what goes where.  I first mentioned this in aspnet/Docs#57, help in the docs,  been resolved and I did not find help in the docs, I am raising this here for viability.

**Comment by jakeymvc** [comment]
The ConfigureServices method defines the services used by your application and the Configure method is used to define what middleware makes up your request pipeline.

**Comment by vossad01** [comment]
@jakeymvc That seems logical.  In practice how does that apply to the distinction between `MvcOptions` and `ErrorPageOptions`?

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
