### ISSUE TITLE
dnu utilities explained.

### ISSUE THREAD

**Issue by Bartmax** [aspnet/Home#707]
Is there anywhere too look up for usage/documentation of `dnu commands` and `dnu packages` and what it does exactly ?

**Comment by frialex** [comment]
You might be able to find the answer to what it does here: https://github.com/aspnet/dnx/tree/dev/src/Microsoft.Framework.PackageManager/ConsoleCommands

**Comment by Bartmax** [comment]
not exactly what I was looking for but I'll take a look. Thanks!

**Comment by glennc** [comment]
Eventually this guidance will be on http://docs.asp.net/

There is an issue tracking creating such a doc here: https://github.com/aspnet/Docs/issues/311

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
