### ISSUE TITLE
How to supply arguments to dnx . run on mono linux?

### ISSUE THREAD

**Issue by broersa** [aspnet/Home#708]
I have the following code but args keeps null
Anyone have an idea?

	public class Program 
	{
		public async Task<int> Main(string[] args)
		{
		}
	}

**Comment by victorhurdugaci** [comment]
How do you invoke the program? It should work by just passing the arguments like you do it for any other application

**Comment by broersa** [comment]
I use dnx . run myarg

**Comment by victorhurdugaci** [comment]
- Does it work without async/task?
- What mono version are you using?

**Comment by broersa** [comment]
Sorry, now that I know that it should work I overlooked my code again thoroughly and it was the statement just before the args that threw the null pointer. Maybe I miss the debugger :-) 
Everything works as expected also the async way.
