### ISSUE TITLE
The best way to keep .dnx versions synchronised with Visual Studio?

### ISSUE THREAD

**Issue by PericlesSouza** [aspnet/Home#709]
I realize that neither the whole dnvm, dnx, etc and Visual Studio 2015 are released yet.

But, is there a recommended way to ensure that the runtimes, sdks, etc are up to date and working together?

For example, I have so far been unable to use the SecretManager, with a default install of Visual Studio 2015 RC, or though the command line utilities. When trying to install it via dnx, it either wants a version of a dependency that is later than that which is available to Visual Studio, or after trying upgrades to dnvm and dnx, when eventually it was able to be installed by forcing the using of the myget feed, it just failed at its constructor. And it is out of synch with the .Net version available in Visual Studio 2015 RC. I give up on SecretManager.

But the point is, there are many places where version, paths, sdks etc have to be entered to both dnx and Visual Studio. It is not a good experience for Visual Studio at all.  Visual Studio is due to be released in 20 days, but there will be lots of work to be able to use ASP.Net 5. Any advice on how will that be rolled out?

**Comment by PericlesSouza** [comment]
To give more information, in case it helps:

Try to follow the process said here:

https://github.com/aspnet/Home/wiki/DNX-Secret-Configuration

Clean install Visual Studio 2015 RC, you have DNVM 1.0.0-beta4 appear in Programs and Features on Windows 8.1 - it is installed with Visual Studio 2015 RC.

You can run DNVM - that is fine - version 1.0.0-beta4.

You can check installed versions of dnx using dnvm list:

All is fine, 1.0.0-beta4 is 'active', and aliased as 'default'.

Visual Studio advice is to use Secrets Manager through command line - ok, we try. No, it does not work, as it is not installed.

Ok, try dnu commands install SecretManager

The result:

Unable to locate the package SecretManager.
The name of the package to be installed was not specified.

Ok, it was specified, it was copied and pasted, it was written by hand. It was just not found.

Next try, upgrade DNX. ok, we get another version 1.0.0-beta6, from a myget site that is apparently temporary. Try dnu commands install SecretManager:

Cannot find Microsoft.Framework.Abstractions.Logging >=1.0.0-beta5

Ok, try something else from web, setting new default dnx version to 1.0.0-beta5, try something else from comments, here on Github, get message commands installed - user-secret. Maybe it works!!

Try to use user-secret -h, response is Error in constructor.

It does not work and It seems you do not really work with Visual Studio team. Difficult to believe it at all. People are trying this and it has good intentions, but it is just not working. Maybe it works on a Mac but not Windows, I dont know.

**Comment by davidfowl** [comment]
> For example, I have so far been unable to use the SecretManager, with a default install of Visual Studio 2015 RC, or though the command line utilities. When trying to install it via dnx, it either wants a version of a dependency that is later than that which is available to Visual Studio, or after trying upgrades to dnvm and dnx, when eventually it was able to be installed by forcing the using of the myget feed, it just failed at its constructor. And it is out of synch with the .Net version available in Visual Studio 2015 RC. I give up on SecretManager.

Yep that's likely because the dnx version and package version is incompatible.

> But the point is, there are many places where version, paths, sdks etc have to be entered to both dnx and Visual Studio. It is not a good experience for Visual Studio at all. Visual Studio is due to be released in 20 days, but there will be lots of work to be able to use ASP.Net 5. Any advice on how will that be rolled out?

> But, is there a recommended way to ensure that the runtimes, sdks, etc are up to date and working together?

There are a few questions you need to answer before getting advice:
- Do you want to used fixed betas or do you want to use ci builds?

Versions exist in a few places:
- The dnvm version (mostly irrelevant)
- The dnx version
- The various package versions

Fixed betas are the happy path. Those betas are tested together and should work well. 

If you want to use nightlies then you need to be aware of the places where versions can appear:

global.json tells visual studio what version of the dnx to use for the solution. The package versions should be in the sync with them. When running from the command line look at the active version (using `dnvm list`). If you want to use nightly packages, then use -* on your dependencies. It's nearly impossible to choose a set of packages from a single ci build that were designed work together (we're working to make this better). That's because its still early beta and we're making breaking changes.

**Comment by PericlesSouza** [comment]
@davidfowl 

Hi, and thanks for the answer.

I am preferring beta builds, of course, to get as much chance of compatibility as is currently available.

So, to clarify, I should try the following:

a) Upgrade the dnvm version (although this is not critical)

b) I should upgrade dnx version, and specify that as the active, and default version (dnx use -p for example).

c) I should also update global.json to list this same version.

d) Update my project.json to specify the versions of packages, and then Visual Studio should attempt to locate the packages.

One point though, dnvm specifies a myget package source. Should I also be using that in Visual Studio? As Visual Studio has a different nuget package source.

Thanks.

**Comment by davidfowl** [comment]
> I am preferring beta builds, of course, to get as much chance of compatibility as is currently available.

beta builds meaning the ones that are on NuGet.org right? Not our ci builds that are on myget.

> b) I should upgrade dnx version, and specify that as the active, and default version (dnx use -p for example).

Yes, set the default and active version to the specific beta you are using.

> c) I should also update global.json to list this same version.

Yes, otherwise visual studio will use the wrong version of the SDK.

> d) Update my project.json to specify the versions of packages, and then Visual Studio should attempt to locate the packages.

Yes.

> One point though, dnvm specifies a myget package source. Should I also be using that in Visual Studio? As Visual Studio has a different nuget package source.

If you're using the RC of VS it has a busted installation of dnvm. You can uninstall it and use dnvm from ASP.NET Home.

**Comment by victorhurdugaci** [comment]
For SecretManager (and global commands in general) we have a bug tracking that. We might add support to keep dnx and the app in sync: https://github.com/aspnet/dnx/issues/1326

**Comment by PericlesSouza** [comment]
@davidfowl 

"If you're using the RC of VS it has a busted installation of dnvm. You can uninstall it and use dnvm from ASP.NET Home."

I had no idea that was the case, will try that.

@victorhurdugaci 

Interesting - I will keep an eye on this. In project properties I can specify a dnx version (this is the same list as is specified in DNVM) - does that not achieve what you need?

**Comment by davidfowl** [comment]
BTW don't uninstall the VS RC, uninstall the DNVM that came with the RC. You should have an entry in the Add/Remove programs for it  `Microsoft .NET Version Manager`

**Comment by leus** [comment]
Question from a complete newbie here - I blindlessly followed some instructions to create some scaffolding and now my project doesn't build on VS2015, but it run beautiful with `dnx . web`. 

I get some grim looking errors like *CS0234	The type or namespace name 'Data' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?)*.

I'm still not clear what dnvm nor dnx means, but it sounded correctly, it worked, it busted my VS2015 - is there a magic incantation to bring it back?
