### ISSUE TITLE
Inconsistent samples/ dir structure between tags

### ISSUE THREAD

**Issue by ahmetalpbalkan** [aspnet/Home#713]
The dir structure for `samples/` has changed in beta5 tag, that breaks `aspnet/aspnet-docker` CI.

Looks like this structure is from the beta3 era, this was changed to `samples/{version}/{Project}` in beta4, not sure why beta5 doesn't carry on the same convention.

![image](https://cloud.githubusercontent.com/assets/159209/8460917/6133cf58-1fdd-11e5-8b71-0abdeec72a27.png)

![image](https://cloud.githubusercontent.com/assets/159209/8460918/63095a00-1fdd-11e5-9d6b-237637417be7.png)

I'll add a special case in the CI scripts to handle that, but please keep in mind that next time you edit the `samples/` dir there's an automated system using that. :smile:

**Comment by ahmetalpbalkan** [comment]
Interesting: 
beta4: https://github.com/aspnet/Home/tree/v1.0.0-beta4/samples (last commit April)
beta5: https://github.com/aspnet/Home/tree/v1.0.0-beta5/samples (last commit March)

looks like the tag is set incorrectly on beta5? @glennc

**Comment by glennc** [comment]
Yeah, something strange happened there. Given the new structure, samples/{version}/{app} do you need to point to the tag? Just point to the right directory in Dev.

I've added the beta5 directory now.

**Comment by ahmetalpbalkan** [comment]
@glennc can you also integrate the commit into beta5 tag? Or readjust the tag?

We currently test all versions of docker images (beta1, beta2, beta3) by checking out to those tags. And dev branch simply doesnt have those versions.

And the dir structure adopted in beta4 is not integrated to beta5. I can enable a workaround but I think the correct thing to do it re-tagging beta5 correctly here.

**Comment by glennc** [comment]
You are using 'latest' in each tag?

**Comment by ahmetalpbalkan** [comment]
@glennc `latest/` directory is something new introduced in `beta4` and disappeared in `beta5` (because of mistagging or not integrated commit)

prior to beta4:
* https://github.com/aspnet/Home/tree/v1.0.0-beta1/samples
* https://github.com/aspnet/Home/tree/v1.0.0-beta2/samples
* https://github.com/aspnet/Home/tree/v1.0.0-beta3/samples

we were directly using `./HelloWeb` (I just realized we don't run tests for beta1-2-3 images...) Then after beta4 we started to rely on path `./{version}/HelloWeb`. Then beta5 broke this: https://github.com/aspnet/Home/tree/v1.0.0-beta5/samples and the directory structure started to look like beta1-2-3.

Here's the code we use to locate the image: https://github.com/aspnet/aspnet-docker/blob/9fb0f020001b8640ecdcdb4ae77d95fbb4498351/.ci/build-app-image.sh#L15-L19

**Comment by glennc** [comment]
Yes, I understand the problem and have updated the tag. However. Tags don't seem necessary anymore. They aren't providing you with anything and given that the tags don't actually give any value to this repo are only here because we tagged everything. Maybe to tie to release notes as well I suppose.

Seems like you get the same effect just by matching samples/{version}/{app} without worrying about tags at all.
