### ISSUE TITLE
dnu kestrel run error : unrecognized argument 'Kestrel'

### ISSUE THREAD

**Issue by LadyNaggaga** [aspnet/Home#715]
Hello, 
I am having issue running dnu Kestrel on Windows. I am using VsCode to build an aspnet.template and I get the error below every time I run dnu kestrel command. 
Could really appreciate some insight to why this might be happening.
![kestrel](https://cloud.githubusercontent.com/assets/2546640/8469268/b69787f6-2045-11e5-89f7-2ae65945f903.PNG)
Thank you

**Comment by davidfowl** [comment]
Is kestrel installed in the project.json?

**Comment by LadyNaggaga** [comment]
Yes it is

**Comment by BrennanConroy** [comment]
dnx <path to project.json> kestrel
not dnu

**Comment by LadyNaggaga** [comment]
Perfect thank you.  I have tried dnx . kestrel and I get this error instead(please see IMG).  Any clue why this could be happening 
![kestrel](https://cloud.githubusercontent.com/assets/2546640/8469444/cd5fb262-2048-11e5-8848-7e2c44aba690.PNG)

**Comment by davidfowl** [comment]
Yes! You are using an older DNX version than you are packages.

**Comment by LadyNaggaga** [comment]
Thank you !
