### ISSUE TITLE
TagHelpers not working on beta6

### ISSUE THREAD

**Issue by IonRobu** [aspnet/Home#717]
Hello,

I used Beta4 since today, and everything worked fine. I upgraded dnx to dnx-clr-win-x86.1.0.0-beta6-12161 (with -unstable parameter), and all my packages, including Microsoft.AspNet.Mvc.TagHelpers from "1.0.0-beta4" to "1.0.0-beta6-*". And tag helpers does not work anymore. For example, i have login link: <a class="k-link" asp-action="login" asp-controller="user">login</a>, which now is rendering on client just like is defined in cshtml (with asp-action="login" asp-controller="user"). Please help!

**Comment by davidfowl** [comment]
You're likely running into this https://github.com/aspnet/Announcements/issues/27

**Comment by IonRobu** [comment]
Hi David,
Is working now, thanks!
