### ISSUE TITLE
Missing interop binary ! 

### ISSUE THREAD

**Issue by angelcalvasp** [aspnet/Home#721]
Created a new WebApplication with Web API

all I did was upgrade to Beta 6 and I get 

```
Missing interop binary ! 
  Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

 Exception Details: System.IO.FileNotFoundException: Missing interop binary !

Source Error: 


 An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.  

Stack Trace: 



[FileNotFoundException: Missing interop binary !]
   System.Web.HttpRuntime.HostingInit(HostingEnvironmentFlags hostingFlags, PolicyLevel policyLevel, Exception appDomainCreationException) +303

[HttpException (0x80004005): Missing interop binary !]
   System.Web.HttpRuntime.FirstRequestInit(HttpContext context) +9940016
   System.Web.HttpRuntime.EnsureFirstRequestInit(HttpContext context) +101
   System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest wr, HttpContext context) +261
```

**Comment by angelcalvasp** [comment]
Changed to Beta 5 still nothing

**Comment by Eilon** [comment]
@moozzyk can you take a look?

**Comment by davidfowl** [comment]
Sounds like a possible bitness mismatch or bad package or something.

**Comment by tom-cognify** [comment]
I'm having the same issue trying to upgrade a project from Beta4 to Beta5

**Comment by moozzyk** [comment]
@angelcalvasp can you provide more details? I just tried creating a new WebAPI project (dependencies in project.json were x.0.0-beta5) and then changed dependencies in the project.json to include x.0.0-* which effectively made it refer to beta6 - dnu list shows:

```
...
* Microsoft.AspNet.Mvc 6.0.0-beta6-14251
...
* Microsoft.AspNet.Server.IIS 1.0.0-beta6-12028
* Microsoft.AspNet.Server.WebListener 1.0.0-beta6-12413
* Microsoft.AspNet.StaticFiles 1.0.0-beta6-12153
...
```
and I can't repro this issue.

**Comment by tom-cognify** [comment]
I resolved this error by adding the Microsoft.AspNet.Loader.IIS.Interop package

not sure why, but I did not have this when running beta 4 and it was working fine.

**Comment by angelcalvasp** [comment]
As soon as I get home I will try this out

**Comment by angelcalvasp** [comment]
my project json is as follows

{
  "webroot": "wwwroot",
  "version": "1.0.0-*",

  "dependencies": {
    "Microsoft.AspNet.Mvc": "6.0.0-beta6-14251",
    "Microsoft.AspNet.Loader.IIS": "1.0.0-beta6-12036",
    "Microsoft.AspNet.Loader.IIS.Interop": "1.0.0-beta6-12036",
    "Microsoft.AspNet.Server.WebListener": "1.0.0-beta6-12413",
    "Microsoft.AspNet.Diagnostics": "1.0.0-beta6-13372",
    "Microsoft.AspNet.StaticFiles": "1.0.0-beta6-12161",
    "Microsoft.Framework.ConfigurationModel.Json": "1.0.0-beta4"
  },

  "commands": {
    "web": "Microsoft.AspNet.Hosting --server Microsoft.AspNet.Server.WebListener --server.urls http://localhost:5000"
  },

  "frameworks": {
    "dnx451": { },
    "dnxcore50": { }
  },

  "exclude": [
    "wwwroot",
    "node_modules",
    "bower_components"
  ],
  "publishExclude": [
    "node_modules",
    "bower_components",
    "**.xproj",
    "**.user",
    "**.vspscc"
  ]
}

after I added the 
"Microsoft.AspNet.Loader.IIS.Interop": "1.0.0-beta6-12036",

when I start my app at the startup on the services.AddMvc(); line I am getting an exception

An exception of type 'System.MissingMethodException' occurred in Microsoft.AspNet.Mvc.Core.dll but was not handled in user code

Additional information: Method not found: 'Boolean Microsoft.Framework.DependencyInjection.ServiceCollectionExtensions.TryAddEnumerable(Microsoft.Framework.DependencyInjection.IServiceCollection,

**Comment by davidfowl** [comment]
Seems you're running into all sorts of versioning problems because you're using a random set of packages from random builds. It's best to avoid that. Try this:

```JSON
{
  "webroot": "wwwroot",
  "version": "1.0.0-*",

  "dependencies": {
    "Microsoft.AspNet.Mvc": "6.0.0-*",
    "Microsoft.AspNet.Server.IIS": "1.0.0-*",
    "Microsoft.AspNet.Server.WebListener": "1.0.0-*",
    "Microsoft.AspNet.Diagnostics": "1.0.0-*",
    "Microsoft.AspNet.StaticFiles": "1.0.0-*",
    "Microsoft.Framework.Configuration.Json": "1.0.0-*"
  },

  "commands": {
    "web": "Microsoft.AspNet.Hosting --server Microsoft.AspNet.Server.WebListener --server.urls http://localhost:5000"
  },

  "frameworks": {
    "dnx451": { },
    "dnxcore50": { }
  },

  "exclude": [
    "wwwroot",
    "node_modules",
    "bower_components"
  ],
  "publishExclude": [
    "node_modules",
    "bower_components",
    "**.xproj",
    "**.user",
    "**.vspscc"
  ]
}
```

**Comment by angelcalvasp** [comment]
Sir... that made it work AWESOME!!!

but... I dont know if I should ask this here or on another issue but If I call

http://localhost:64996/api/values I get the Welcome page in fact if I try to call any api I get in return the Welcome page is there an extra step to be made?

**Comment by davidfowl** [comment]
Make a new issue, it's unrelated

**Comment by moozzyk** [comment]
(I am still curious where the `Missing interop binary !` message came from because I could not find it in our sources...)
