### ISSUE TITLE
Interface(s) or Abstract Class(s) for Startup Class

### ISSUE THREAD

**Issue by brent-russell** [aspnet/Home#722]
If certain methods and signatures are required for the Startup class, why are there no interfaces or base classes to define those contracts?

When starting a new from scratch project, the methodology to create the Startup class requires consulting documentation, copying method signatures from an existing Startup class, or the most time consuming method - reading through source code to find out how the application is executed in order to learn what methods should be created and what their signatures are.

Templating a project is not really sufficient, because that creates a dependency on using a specific tool in order to set up a new project. It's just a class after all. It shouldn't be that difficult.

**Comment by davidfowl** [comment]
Read this, it explains why it would be restricting to have an interface:

https://gist.github.com/davidfowl/700097cca459c1e78c86

**Comment by brent-russell** [comment]
Thanks. That makes sense. It wasn't obvious that those parameter values were provided by dependency injection. Especially since the built-in IoC only does constructor injection. It also wasn't obvious that those parameters were optional, and that one was required. So maybe this really is a job for (much) better documentation and templating / scaffolding.

**Comment by davidfowl** [comment]
@brent-russell The next version of visual studio has project templates for these things.
