### ISSUE TITLE
Update README.md with additional install commands

### ISSUE THREAD

**Issue by cataquil** [aspnet/Home#723]
On Windows 8 installing from command line, so I can test out VSCode, Atom, etc.

After the powershell command line.

You must close your command prompt and reopen it, 
then type : where dnvm

then type: dnvm install latest
or dnvm install 1.0.0-beta4

I think its better that this info is here for people starting out, rather than having to check miscellaneous blogs.

**Comment by Eilon** [comment]
@glennc

**Comment by glennc** [comment]
You shouldn't have to reopen the shell, if that is still happening then it is a bug somewhere. Is it?

The instructions tell you to type dnvm upgrade, which is the same as DNVM install latest but also setting a user path to the installed DNX. Was there a problem that made that not good enough?

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
