### ISSUE TITLE
Two references ? 

### ISSUE THREAD

**Issue by lokinfey** [aspnet/Home#727]
I update asp.net beta 5 . But When I using dnx . web  it give me this ,
The type 'IServiceCo
llection' exists in both 'Microsoft.Framework.DependencyInjection.Abstractions,
Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' and 'Microsoft.Framework.
DependencyInjection.Interfaces, Version=1.0.0.0, Culture=neutral, PublicKeyToken
=null'

I try to add Microsoft.Framework.DependencyInjection.Interfaces

this is my project.json file setting 

```
    "Microsoft.AspNet.Server.IIS":"1.0.0-beta5",
    "Microsoft.AspNet.Diagnostics": "1.0.0-beta5",
    "EntityFramework": "7.0.0-beta4",
    "EntityFramework.SqlServer": "7.0.0-beta4",
    "EntityFramework.Relational" : "7.0.0-beta4",
    "EntityFramework.Commands": "7.0.0-beta4",
    "EntityFramework.Migrations": "7.0.0-beta2",
    "Microsoft.AspNet.Mvc": "6.0.0-beta5",
    "Microsoft.Framework.ConfigurationModel.Json": "1.0.0-beta4",
    "Microsoft.Framework.Logging.Console": "1.0.0-beta5",
    "Microsoft.AspNet.Server.WebListener": "1.0.0-beta5",
    "Microsoft.AspNet.Security.Cookies": "1.0.0-beta3",
    "Microsoft.AspNet.StaticFiles": "1.0.0-beta5",
    "Microsoft.Framework.DependencyInjection": "1.0.0-beta5",
    "Microsoft.Net.Http": "2.2.29",
    "Newtonsoft.Json": "7.0.1",
    "Kestrel": "1.0.0-beta5"
```

this is my Startup.cs

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNet.Builder;
using Microsoft.AspNet.Hosting;
using Microsoft.AspNet.Http;
using Microsoft.AspNet.StaticFiles;
using Microsoft.AspNet.Routing;
using Microsoft.Data.Entity;
using Microsoft.Framework.DependencyInjection;
using Microsoft.Framework.ConfigurationModel;
using Microsoft.AspNet.Diagnostics;
using GdouWechat.Domain;
using GdouWechat.Data;
using GdouWechat.Services;
using GdouWechat.Data.Infrastructure;
using Microsoft.Framework.Logging;
namespace GdouWechat.Web
{
    public class Startup
    {
        public Startup(IHostingEnvironment env)
        {
            Configuration = new Configuration()
                .AddJsonFile("config.json")
                .AddEnvironmentVariables();
        }

```
    public IConfiguration Configuration { get; set; }

    // This method gets called by a runtime.
    // Use this method to add services to the container
    public void ConfigureServices(Microsoft.Framework.DependencyInjection.IServiceCollection services)
    {
        services.AddMvc();
        // Uncomment the following line to add Web API services which makes it easier to port Web API 2 controllers.
        // You will also need to add the Microsoft.AspNet.Mvc.WebApiCompatShim package to the 'dependencies' section of project.json.
        // services.AddWebApiConventions();
        services.AddEntityFramework()
                .AddSqlServer()
                .AddDbContext<GdouWechatDataContext>(options =>
                {
                     options.UseSqlServer(Configuration.Get("Data:DefaultConnection:ConnectionString"));
                });

        services.AddScoped<IDatabaseFactory, DatabaseFactory>();
        services.AddScoped<GdouWechatDataContext, GdouWechatDataContext>();
        services.AddScoped<IUnitOfWork, UnitOfWork>();
        services.AddScoped<IExamRepository,ExamRepository>();
        services.AddScoped<IGetExamService,GetExamService>();
        services.AddScoped<ILocRepository,LocRepository>();
        services.AddScoped<IGetLocService,GetLocService>();
        services.AddScoped<IRegRepository,RegRepository>();
        services.AddScoped<IRegService,RegService>();
    }

    // Configure is called after ConfigureServices is called.
    public void Configure(IApplicationBuilder app,IHostingEnvironment env, ILoggerFactory loggerFactory)
    {
        // Configure the HTTP request pipeline.
        //app.UseMvc();
        app.UseStaticFiles();
        //app.UseErrorPage();
        //app.UseErrorPage(ErrorPageOptions.ShowAll);
        // app.UseErrorPage();
        // Add MVC to the request pipeline.
        app.UseMvc(routes =>
        {
            routes.MapRoute(
                name: "default",
                template: "{controller}/{action}/{id?}",
                defaults: new { controller = "Home", action = "Index" });
        });
        // Add the following route for porting Web API 2 controllers.
        // routes.MapWebApiRoute("DefaultApi", "api/{controller}/{id?}");
    }
}
```

}

Can you help me ?

**Comment by davidfowl** [comment]
Your dependencies are a mishmash of incompatible versions. If you're trying to use beta5 then you should follow the instructions here http://blogs.msdn.com/b/webdev/archive/2015/06/30/asp-net-5-beta5-now-available.aspx.

> To update to ASP.NET 5 Beta5 use the following steps:
- Install the .NET Version Manager (DNVM) if you don’t already have it (it comes preinstalled with Visual Studio 2015 RC, or you can get the latest version)
- From a command prompt set the DNX_FEED environment variable to https://www.nuget.org/api/v2
- Run “dnvm upgrade”
- In your app update your global.json to point to eta5 version of the .NET Execution Environment (DNX)
- Also your project.json to point to the beta5 ackage versions
- Run “dnu restore”
- Run “dnu build” and migrate your code to beta5 s needed

> There have been quite a few API changes in this release as part of a broad API review. In the process we refactored many of our packages to reduce dependencies and to improve the layering. To help you update your Beta4 code you can find a list of the most impactful changes on our Announcements repo along with details for each change. You can also find docs and samples for ASP.NET 5 at http://docs.asp.net.

https://github.com/aspnet/Announcements/issues?q=is%3Aopen+is%3Aissue+milestone%3A1.0.0-beta5

**Comment by lokinfey** [comment]
sir I try it but it can't run anyway .The type 'IServiceCo
llection' exists in both 'Microsoft.Framework.DependencyInjection.Abstractions,
Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' and 'Microsoft.Framework.
DependencyInjection.Interfaces, Version=1.0.0.0, Culture=neutral, PublicKeyToken
=null'

**Comment by davidfowl** [comment]
Are you still using random versions? Did you update all of your packages to beta5? Did you update your global.json to beta5? Did you check your `project.lock.json` to make sure it has beta5 references?

**Comment by lokinfey** [comment]
i think this is not my random version . I update all in beta 5 . how to update global.json , I can't find it

**Comment by davidfowl** [comment]
You should use your `project.lock.json` to verify that. What version of Microsoft.Framework.ConfigurationModel.Json got resolved in `project.lock.json`?

**Comment by lokinfey** [comment]
this. is my Microsoft.Framework.ConfigurationModel.Json  in project.lock.json
      "Microsoft.Framework.ConfigurationModel.Json/1.0.0-beta4": {
        "dependencies": {
          "Newtonsoft.Json": "6.0.6",
          "Microsoft.Framework.ConfigurationModel": "1.0.0-beta4"
        },
        "frameworkAssemblies": [
          "mscorlib",
          "System",
          "System.Core",
          "Microsoft.CSharp"
        ],
        "compile": {
          "lib/dnx451/Microsoft.Framework.ConfigurationModel.Json.dll": {}
        },
        "runtime": {
          "lib/dnx451/Microsoft.Framework.ConfigurationModel.Json.dll": {}
        }
      },

**Comment by davidfowl** [comment]
Yep, its beta4 and your other references are beta5 or beta6. That will cause problems. Random versions of packages from previous releases mixed with newer ones. If you read the announcements repository for beta5 changs, you'll see this https://github.com/aspnet/Announcements/issues/25

**Comment by lokinfey** [comment]
this is my code can you help me to see that ?
I think I upgrade all 
http://course.gdou.com/blog/image/luk/app.zip

**Comment by davidfowl** [comment]
I don't do zips from the interwebz.

Change Microsoft.Framework.ConfigurationModel.Json to Microsoft.Framework.Configuration.Json

**Comment by lokinfey** [comment]
I change it , it tells me 
![2015-07-09 6 03 13](https://cloud.githubusercontent.com/assets/4607663/8592793/c061af8a-2664-11e5-8e1b-d383cec7679a.png)
but I rewrite my project.json
![2015-07-09 6 03 35](https://cloud.githubusercontent.com/assets/4607663/8592800/cde87c9c-2664-11e5-8e30-456478b19151.png)
this is my Startup.cs

  public class Startup
    {
        
        
    public Startup(IHostingEnvironment env, IApplicationEnvironment appEnv)
    {
var path = appEnv.ApplicationBasePath;
            Configuration = new ConfigurationBuilder()
            .AddJsonFile($"{path}/config.json")
            .AddEnvironmentVariables()
            .Build();
    }
        //  public Startup(IHostingEnvironment env)
        //  {
        //      Configuration = new Configuration()
        //          .AddJsonFile("config.json")
        //          .AddEnvironmentVariables();
        //  }
        
        
        public IConfiguration Configuration { get; set; }

        // This method gets called by a runtime.
        // Use this method to add services to the container
        public void ConfigureServices(Microsoft.Framework.DependencyInjection.IServiceCollection services)
        {
            services.AddMvc();
            // Uncomment the following line to add Web API services which makes it easier to port Web API 2 controllers.
            // You will also need to add the Microsoft.AspNet.Mvc.WebApiCompatShim package to the 'dependencies' section of project.json.
            // services.AddWebApiConventions();
            services.AddEntityFramework()
                    .AddSqlServer()
                    .AddDbContext<GdouWechatDataContext>(options =>
                    {
                         options.UseSqlServer(Configuration.Get("Data:DefaultConnection:ConnectionString"));
                    });

            services.AddScoped<IDatabaseFactory, DatabaseFactory>();
            services.AddScoped<GdouWechatDataContext, GdouWechatDataContext>();
            services.AddScoped<IUnitOfWork, UnitOfWork>();
            services.AddScoped<IExamRepository,ExamRepository>();
            services.AddScoped<IGetExamService,GetExamService>();
            services.AddScoped<ILocRepository,LocRepository>();
            services.AddScoped<IGetLocService,GetLocService>();
            services.AddScoped<IRegRepository,RegRepository>();
            services.AddScoped<IRegService,RegService>();
        }

        // Configure is called after ConfigureServices is called.
        public void Configure(IApplicationBuilder app,IHostingEnvironment env)
        {
            // Configure the HTTP request pipeline.
            //app.UseMvc();
            app.UseStaticFiles();
            //app.UseErrorPage();
            //app.UseErrorPage(ErrorPageOptions.ShowAll);
            // app.UseErrorPage();
            // Add MVC to the request pipeline.
            app.UseMvc(routes =>
            {
                routes.MapRoute(
                    name: "default",
                    template: "{controller}/{action}/{id?}",
                    defaults: new { controller = "Home", action = "Index" });
            });
            // Add the following route for porting Web API 2 controllers.
            // routes.MapWebApiRoute("DefaultApi", "api/{controller}/{id?}");
        }
    }

**Comment by davidfowl** [comment]
Change `Microsoft.AspNet.Security.Cookies` -> `Microsoft.AspNet.Authentication.Cookies`

**Comment by lokinfey** [comment]
I delete it 
  "dependencies": {
    "Microsoft.AspNet.Mvc": "6.0.0-*",
    "Microsoft.AspNet.Server.IIS": "1.0.0-*",
    "Kestrel": "1.0.0-*",
    "Microsoft.AspNet.Server.WebListener": "1.0.0-*",
    "Microsoft.AspNet.StaticFiles": "1.0.0-*",
    "Microsoft.Framework.Configuration.Json": "1.0.0-beta5",
    "Microsoft.Framework.DependencyInjection": "1.0.0-*",
    "Microsoft.Net.Http": "2.2.29",
    "Newtonsoft.Json": "7.0.1",
    "System.Net.Http": "4.0.0-*",
    "EntityFramework": "7.0.0-beta4",
    "EntityFramework.SqlServer": "7.0.0-beta4",
    "EntityFramework.Relational" : "7.0.0-beta4",
    "EntityFramework.Commands": "7.0.0-beta4",
    "GdouWechat.Domain":"",
    "GdouWechat.Data":"",
    "GdouWechat.Services":""
  },

but the problem is the same too

**Comment by davidfowl** [comment]
Why are you still using beta4 versions and -* in the same project. You have to stop mixing random versions of packages. It will not work.

**Comment by vmural** [comment]
update "Microsoft.Framework.ConfigurationModel.Json": "1.0.0-beta4",
to  "Microsoft.Framework.Configuration.Json": "1.0.0-beta5"

**Comment by tlk** [comment]
@lokinfey Perhaps #729 could be useful for you.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
