### ISSUE TITLE
Missing section in Readme on how to upgrade from Beta X to Beta Y

### ISSUE THREAD

**Issue by patlac** [aspnet/Home#729]
While you provide easy doc for getting started ([Getting Started Guide](https://github.com/aspnet/Home#getting-started-with-aspnet-5-and-dnx)), the steps to follow when one wants to upgrade a **Beta X** based app to **Beta Y** aren't quite obvious, from the Readme.

You could add a section on how to upgrade, since the steps are quite easy:
1. `> dnvm upgrade`
2. Read about breaking changes in [Announcements](https://github.com/aspnet/Announcements)
3. Fix source code and `dependencies` in `project.json`
4. `> dnu restore`
5. `> dnu build`
6. Repeat  steps 2-5. until everything works again

This would save us on-boarders some time googling.

**Comment by davidfowl** [comment]
I'm not sure this makes sense to put in docs, it's a point in time release. Having a place to put that information would be great though.

**Comment by tlk** [comment]
@patlac +1

@davidfowl Do you not think it makes sense to keep the documentation in sync with the current state of the software?

**Comment by davidfowl** [comment]
I think docs should be versioned and reflect the latest shipped build. It's too early to maintain a list of beta to beta upgrade instructions on official docs. Especially since the breaks are only as big because we're in beta. 

The announcements repository is good enough for now and people just need to read it.

**Comment by tlk** [comment]
Alright then.

**Comment by codeclash** [comment]
@davidfowl I really meant  just *hinting* (in the Readme) at the 6 steps I described above, not the actual  details on how to fix (that's described in the Accouncements repo).

**Comment by peterblazejewicz** [comment]
Maybe just a hint as link to a short page in project wiki:
https://github.com/aspnet/Home/wiki
?
