### ISSUE TITLE
Consider renaming ViewLocationExpander

### ISSUE THREAD

**Issue by grahamehorner** [aspnet/Home#732]
Please consider renaming the ViewLocationExpander and supporting interfaces/classes to ViewPathProvider or similar.

The reason for this is that the implementation may not result in an expanded location; secondly the location is in fact part of a UNC/URI (minus protocol host port document) path and therefore using naming conversion of ViewPathProvider seems more akin to the actual function performed; namely providing a path for a given View.

**Comment by Eilon** [comment]
Can you log the issue in https://github.com/aspnet/Mvc/issues? Thanks!

**Comment by grahamehorner** [comment]
done
