### ISSUE TITLE
Question: Visual studio 2015 and DNX Runtime

### ISSUE THREAD

**Issue by mbharodia** [aspnet/Home#736]
Not sure if this is the correct place to ask this question. My apology if I offend anyone. I am not able to find answer of the following question anywhere else.

Visual studio 2015 will come with .NET Framework 4.6. 

What's about DNX runtime? Will there be any DNX runtime released at that time? Right now what I can install with DNVM is Beta 5 as latest version of DNX. Will this be the closest to the runtime released on 20 July 2015?

Thanks a lot in advance for your help.

**Comment by Eilon** [comment]
VS2015 RTM will ship with ASP.NET 5 beta 5. There will later be updates to add future previews of ASP.NET to VS, all the way until ASP.NET 5 reaches RTM.
