### ISSUE TITLE
Support for OData

### ISSUE THREAD

**Issue by grahamehorner** [aspnet/Home#741]
please consider OData support for ASP.NET v5 coreclr or provide reference on how to implement odata services in ASP.NET v5

**Comment by bmonsterman** [comment]
Agreed, please consider OData supprot with ASP.NET 5

**Comment by ikhwanhayat** [comment]
+1

**Comment by DenisBiondic** [comment]
+1

**Comment by andygjp** [comment]
+1

**Comment by wingnut808** [comment]
+1

**Comment by javierjim** [comment]
+1

**Comment by jerry2007** [comment]
+1

**Comment by victorantos** [comment]
+2

**Comment by mfcar** [comment]
+3

**Comment by apiweb** [comment]
Please, add native support to odata

**Comment by grahamehorner** [comment]
The odata library & framework should target the .NetStandard1.0 this would as understand it allow odata to the be used by CoreCLR AspNetCore and full framework .NET it may also be good to consider at this time including greater extensibility and dependency injection in the framework.

**Comment by grahamehorner** [comment]
@apiweb what do you mean by native support ?

**Comment by Luigie** [comment]
+3 (3 dev's in our team) :)

**Comment by GuardRex** [comment]
See https://github.com/OData/odata.net/issues/568#issuecomment-230068541

**Comment by zfkingth** [comment]
+10

**Comment by rakeshrohan** [comment]
+1

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
