### ISSUE TITLE
Migrating content packages from Nuget to bower

### ISSUE THREAD

**Issue by Eonasdan** [aspnet/Home#742]
I am the author of a Bootstrap DateTime picker plugin. ([LESS](https://www.nuget.org/packages/Bootstrap.v3.Datetimepicker/), [CSS](https://www.nuget.org/packages/Bootstrap.v3.Datetimepicker.CSS/)). I have (combined) 70,000 downloads with 6,000 of those being in the last month alone.

Many of my users are not aware of the upcoming changes. With Nuget/MVC/Asp.Net moving away from delivering frontend packages like this and expecting people to use bower, it will be a shocking revelation to them when this happens. As such, I'm afraid that I will lose part of my user base--those who may not realize that there's a new/different way to get frontend packages like mine. I think that it is important for Microsoft to make this transition smoother, not only for package managers like myself, but especially for my users.

I propose that an XML node be added to the spec that would allow me as an author to point Nuget to my package on bower. This should also cause Nuget to pull down a bower package instead, for new projects (MVC 6). Perhaps some indication to the user that this happened for them in the background: "Hey you downloaded this fontend package but you should really get it from bower".

This wouldn't need to be a permanent addition; just one that would allow the bandage to fall off rather than being ripped off.

Thanks to @csharpfritz for suggesting that I make this issue.

([Cross posting](https://github.com/NuGet/Home/issues/930))

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
