### ISSUE TITLE
Hostname based configuration and accessing AppId under IIS

### ISSUE THREAD

**Issue by CoskunSunali** [aspnet/Home#743]
I did my best to figure it out by myself but with no luck.

The scenario is;
- There is only one application code base
- An unknown number of websites share the same code - and they can be created dynamically
- All websites are located under separate IIS application pools
- As expected, all websites share the same Startup class, however, some of the middlewares expect the host URL to be configured correctly.

Since "host" value is the key here, how can we reach it within the Startup.Configure method?

An example of middlewares that requires the knowledge of "host" parameter is `OAuthBearerAuthentication`. Please see the configuration below:

```
            app.UseOAuthBearerAuthentication(options =>
            {
                options.AutomaticAuthentication = true;
                options.Authority = "http://localhost:50000/";
                options.Audience = "localhost";
            });
```

`OAuthBearerAuthentication` is not the only middleware if you wonder. I can think of tens of cases where one could need the hostname at "Configure" time.

I understand the approach to solve similar issues is to use hosting environments, e.g.: Development, Staging, Production, etc. However, that does not really reflect the use case I am trying to solve here as I might have 50 websites sharing the same code base but are located in separate IIS application pools and that has nothing to do with the concept of Development, Staging, etc.

On top of all the things I mentioned, there is also the ApplicationId issue. In previous versions of ASP.NET, we were able to access the ApplicationId using HostingEnvironment class and that really helped solve some of the use cases. For instance, trying to solve the above issue using hostname is sometimes of no help since a website might have more than one IIS binding. Then we would use ApplicationId to see if the binding actually matches another website.

I can see that Helios does not provide any information about the ApplicationId even though I can see the value being internally used. Please see: `Microsoft.AspNet.Loader.IIS.IHttpApplication`. Why the need to hide that information?

I would really appreciate any idea, comment, workaround.

**Comment by ldefreitas-syselio** [comment]
Hello,

I have the same need : on source code, multiple IIS application.
I have had the same issue to get the ApplicationId.

Well, by going deeply inside souce code, I saw the `Microsoft.AspNet.Loader.IIS.IHttpApplication` too.

Here is the way I found to get it:

        public Startup(IHostingEnvironment env, IApplicationEnvironment appEnv, IServiceProvider provider) {
            // Adding IServiceProvider in argument of Startup to get the Dependency injection provider.

            // Get IApplicationDiscriminator, containing a field _application that is the IHttpApplication
            var appDiscriminator = provider.GetService<Microsoft.AspNet.DataProtection.Infrastructure.IApplicationDiscriminator>();

            // Check if we have something
            if (appDiscriminator != null && appDiscriminator.GetType().Name == "HeliosApplicationDiscriminator") {
                // Get value of the field '_application'.
                var iisHttpApplication = appDiscriminator
                    .GetType()
                    .GetField("_application", BindingFlags.Instance | BindingFlags.NonPublic)
                    .GetValue(appDiscriminator) as Microsoft.AspNet.Loader.IIS.IHttpApplication;

                // You have it !
                var appId = iisHttpApplication.AppId;
                var appPhysicalPath = iisHttpApplication.AppPhysicalPath;
                var appVirtualPath = iisHttpApplication.AppVirtualPath;

                // Configure your application with it
                // ...
            }

            // ... //
        }

It is like hacking, but I cannot find another way to get it.
I agree with csunali, why hide the information?

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
