### ISSUE TITLE
Package Resolution Explanation

### ISSUE THREAD

**Issue by cloudmark** [aspnet/Home#746]
I was trying out the new beta6 packages (on a Mac) using the following dependencies in my `project.json`

```json
    {
        "version": "1.0.0-*",
        "webroot": "wwwroot",
        "dependencies": {
            "Kestrel": "1.0.0-beta6",
            "Microsoft.AspNet.Diagnostics": "1.0.0-beta6",
            "Microsoft.AspNet.Mvc": "6.0.0-beta6",
            "Microsoft.AspNet.Server.IIS": "1.0.0-beta6",
            "Microsoft.AspNet.Server.WebListener": "1.0.0-beta6",
            "Microsoft.Framework.Logging.Console": "1.0.0-beta6", 
        },
        "frameworks": {
            "dnx451": {},
            "dnxcore50": {}
        }
    }
```

and I was getting the following error

    Unable to locate Microsoft.CodeAnalysis.CSharp >= 1.0.0-rc3-20150619-01
    Writing lock file /Users/C#/Beta6/project.lock.json
    Restore complete, 6802ms elapsed

When I modified the dependencies as follows

```json
    {
        "version": "1.0.0-*",
        "webroot": "wwwroot",
        "dependencies": {
            "Kestrel": "1.0.0-*",
            "Microsoft.AspNet.Diagnostics": "1.0.0-*",
            "Microsoft.AspNet.Mvc": "6.0.0-*",
            "Microsoft.AspNet.Server.IIS": "1.0.0-*",
            "Microsoft.AspNet.Server.WebListener": "1.0.0-*",
            "Microsoft.Framework.Logging.Console": "1.0.0-*", 
        },
        "frameworks": {
            "dnx451": {},
            "dnxcore50": {}
        }
    }
```
everything worked fine.  

Looking into the dependency tree between the two dependency variants (`project.lock.json`) I can see that the latter (`1.0.0-*` version) is pulling `"Microsoft.CodeAnalysis.CSharp": "1.0.0-rc3-20150618-03",`
because of the `"Microsoft.Framework.Runtime.Roslyn.Abstractions/1.0.0-beta6-12216"` dependency

```json
      "Microsoft.Framework.Runtime.Roslyn.Abstractions/1.0.0-beta6-12216": {
        "dependencies": {
          "Microsoft.CodeAnalysis.CSharp": "1.0.0-rc3-20150618-03",
          "Microsoft.Framework.Runtime.Abstractions": "1.0.0-beta6-12216"
        },
        "frameworkAssemblies": [
          "Microsoft.CSharp",
          "mscorlib",
          "System",
          "System.Core"
        ],
        "compile": {
          "lib/dnx451/Microsoft.Framework.Runtime.Roslyn.Abstractions.dll": {}
        },
        "runtime": {
          "lib/dnx451/Microsoft.Framework.Runtime.Roslyn.Abstractions.dll": {}
        }
      },
```

while the former (`1.0.0-beta6` version) pulls in a different version (**1.0.0-rc3-20150619-01** vs **1.0.0-rc3-20150618-03**)

```json
      "Microsoft.Framework.Runtime.Roslyn.Abstractions/1.0.0-beta6-12114": {
        "dependencies": {
          "Microsoft.CodeAnalysis.CSharp": "1.0.0-rc3-20150619-01",
          "Microsoft.Framework.Runtime.Abstractions": "1.0.0-beta6-12114"
        },
        "frameworkAssemblies": [
          "Microsoft.CSharp",
          "mscorlib",
          "System",
          "System.Core"
        ],
        "compile": {
          "lib/dnx451/Microsoft.Framework.Runtime.Roslyn.Abstractions.dll": {}
        },
        "runtime": {
          "lib/dnx451/Microsoft.Framework.Runtime.Roslyn.Abstractions.dll": {}
        }
      }, 
```

So my question is, why are the two resolutions different? What is happening? 

Note that when the dependencies are setup as follows: 

```json
    {
        "version": "1.0.0-*",
        "webroot": "wwwroot",
        "dependencies": {
            "Kestrel": "1.0.0-beta6-*",
            "Microsoft.AspNet.Diagnostics": "1.0.0-beta6-*",
            "Microsoft.AspNet.Mvc": "6.0.0-beta6-*",
            "Microsoft.AspNet.Server.IIS": "1.0.0-beta6-*",
            "Microsoft.AspNet.Server.WebListener": "1.0.0-beta6-*",
            "Microsoft.Framework.Logging.Console": "1.0.0-beta6-*", 
        },
        "frameworks": {
            "dnx451": {},
            "dnxcore50": {}
        }
    }
```

I get the same exact resolution as the `1.0.0-beta6` version

```json
      "Microsoft.Framework.Runtime.Roslyn.Abstractions/1.0.0-beta6-12114": {
        "dependencies": {
          "Microsoft.CodeAnalysis.CSharp": "1.0.0-rc3-20150619-01",
          "Microsoft.Framework.Runtime.Abstractions": "1.0.0-beta6-12114"
        },
        "frameworkAssemblies": [
          "Microsoft.CSharp",
          "mscorlib",
          "System",
          "System.Core"
        ],
        "compile": {
          "lib/dnx451/Microsoft.Framework.Runtime.Roslyn.Abstractions.dll": {}
        },
        "runtime": {
          "lib/dnx451/Microsoft.Framework.Runtime.Roslyn.Abstractions.dll": {}
        }
      },
```

Could someone please explain the difference between `1.0.0-beta6-*`, `1.0.0-beta6`, `1.0.0-*`, given that the latest version at this point is `beta6`.

**Comment by davidfowl** [comment]
Versions are always a minimum so 1.0.0 means >= 1.0.0. By default nuget and dnu always prefer the lowest version that satisfies the condition. Wildcards break that last rule and instead try to give you the highest.

`1.0.0-beta6` - lowest version >= 1.0.0-beta6
`1.0.0-beta6-*` - highest version matching the prefix 1.0.0-beta6, if none match that prefix then treat it like lowest >= 1.0.0-beta6
`1.0.0-*` - highest version matching the prefix 1.0.0 prefix, if none match that prefix then treat it like >= 1.0.0

You also need to understand general semver rules so that the sort order of prerelease packages makes sense. http://semver.org/spec/v1.0.0.html

**Comment by cloudmark** [comment]
Hey, thanks for the reply, given that `beta6` is currently the latest version (hence the highest prefix is beta6) my understanding is that the dependency variants `1.0.0-*` and `1.0.0-beta6-*` should have resolved to the same version package?  

Hence  `"Microsoft.Framework.Runtime.Roslyn.Abstractions"` for both dependency versions should have been resolved to 

```
1.0.0-*`:  "Microsoft.Framework.Runtime.Roslyn.Abstractions/1.0.0-beta6-12216"
1.0.0-beta6-*:  "Microsoft.Framework.Runtime.Roslyn.Abstractions/1.0.0-beta6-12116"
```

Instead of 

```
1.0.0-* :  "Microsoft.Framework.Runtime.Roslyn.Abstractions/1.0.0-beta6-12216"
1.0.0-beta6-*: "Microsoft.Framework.Runtime.Roslyn.Abstractions/1.0.0-beta6-12114"
```

Isn't `1.0.0-beta6-12214` < `1.0.0-beta6-12216` in SemVer?  Only the `1.0.0-beta6` version should have selected `"Microsoft.Framework.Runtime.Roslyn.Abstractions/1.0.0-beta6-12114"`.

**Comment by davidfowl** [comment]
@cloudmark Did you directly depend on that package? The "highest matching the prefix" logic only applies for things that are directly referenced, not the entire graph. 


Here's what I got:

Microsoft.Framework.Runtime.Roslyn.Abstractions: "1.0.0-*" ->  1.0.0-beta6-12216
Microsoft.Framework.Runtime.Roslyn.Abstractions: "1.0.0-beta6-*" -> 1.0.0-beta6-12216

**Comment by cloudmark** [comment]
@davidfowl got it! No I did not depend on that prefix directly.  Thanks for you help.
