### ISSUE TITLE
OS X: Fresh install of Beta 5 does not work

### ISSUE THREAD

**Issue by gingters** [aspnet/Home#747]
Hello,

I followed the instructions on the Home repo and used Homebrew to install Beta5.
Brew installed a new copy of Mono, and then the DN* Beta 5 stuff.

Dnvm works, but as soon as I want to start dnx or dnu, I get this message:

    The assembly mscorlib.dll was not found or could not be loaded.
    It should have been installed in the `/usr/local/lib/mono/4.5/mscorlib.dll` directory.

In the mean time I also completely uninstalled a previous mono installation as well as dnx and re-installed, again fresh, with brew, but to no avail.

dnvm lists the runtime for mono correctly:

    smartAir:WebApplicationSimple Sebastian$ dnvm list
    
    Active Version              Runtime Arch Location             Alias
    ------ -------              ------- ---- --------             -----
      *    1.0.0-beta5          mono         ~/.dnx/runtimes      default

What can I do to get Beta 5 running on OS X?
I had Beta3 running fine, as well as beta 4 with a self-compiled version of mono as there was a bug in mono that was already fixed but not yet released.

Now with Beta5 I'm stuck and on JabbR I get no additional info if I need different steps or a different Mono version.

**Comment by davidfowl** [comment]
@gingters Does your mono even work on its own? Can you compile and run a simple mono hello world? It looks like your mono install is borked.

**Comment by gingters** [comment]
Yes, Mono definetly works.
I can create, compile and run a mono hello world app. Also Xamarin Studio works fine.

**Comment by davidfowl** [comment]
Very odd. I'm not sure what could cause that. Where is mono installed?

**Comment by gingters** [comment]
From the look of it, the Brew formula for dnx installed mono to /usr/local/Cellar/mono/4.0.2.5/lib/mono

**Comment by gingters** [comment]
Strange, somehow brew indeed screwed up my mono installation. Even after uninstalling all traces of mono with brew, and uninstalling all traces of an official mono with the scripts provided by the mono project, an older brew-installed mono installation was still there and half-working

**Comment by gingters** [comment]
Okay, a complete, manual re-install from an older version of mono installed by Homebrew did the trick.
After removing all old traces of Mono, after removing an original install of Mono, uninstalling all of dnx and a clean install of the latest Mono version together with installing dnx with the linux install script, not using brew, it seems that beta 5 now works. Please consider a different suggested method of installation than brew, as this really screws things up big time.
