### ISSUE TITLE
Reference error

### ISSUE THREAD

**Issue by TomGroeneboer** [aspnet/Home#748]
Hi guys,

I've found something weird. If I add the nuget package CsvHelper, latest stable release, it says `Cannot find part of the path <path to dnx>\.dnx\packages\CsvHelper\2.13.2.0\CsvHelper.2.13.2.0.nupkg.sha512 `

Is it something related to CsvHelper? Or is it a NuGet/VS thing?

Thanks

**Comment by davidfowl** [comment]
It's a bug in the beta5 dnx. You can work around it by going to your NuGet feed settings that configuring the nuget v2 feed (it should be unchecked by default) and by unchecking the v3 feed. It will be fixed in beta6

**Comment by TomGroeneboer** [comment]
Alright thanks! I solved it :D
