### ISSUE TITLE
Defect with POST and DELETE/PUT with the same path

### ISSUE THREAD

**Issue by taddeini** [aspnet/Home#749]
We've noticed `DELETE` and `PUT` endpoints _sometimes_ return 404s when they have the same routing configuration as a `POST` (e.g. `POST /controller/operation` and `DELETE /controller/operation`). 

It turns out the 404s only happen if the `DELETE/PUT` is invoked _before_ the `POST` when the application starts--after that all subsequent `DELETE/PUT` actions return 404s and `POST` actions are fine. If the application is then restarted and a `POST` is invoked first, then all actions are fine for the lifetime of the process.

I've verified this behavior for a `POST` and `DELETE` using MVC beta6 / IIS Express / Visual Studio 2015 RC.

**Comment by Eilon** [comment]
https://github.com/aspnet/Routing/issues

**Comment by Eilon** [comment]
Oops, I meant please log the issue here: https://github.com/aspnet/Routing/issues

**Comment by taddeini** [comment]
Will do
