### ISSUE TITLE
Could not find latest version from feed

### ISSUE THREAD

**Issue by etsit** [aspnet/Home#753]
I could not install dnx using dvnm.sh sourced in bash on OS X, neither using a version on Homebrew (1.0.0 stable) nor the current dev branch cloned here.

Console output
```
$ dnvm upgrade
Determining latest version
usage: grep [-abcDEFGHhIiJLlmnOoqRSsUVvwxZ] [-A num] [-B num] [-C[num]]
	[-e pattern] [-f file] [--binary-files=value] [--color=when]
	[--context[=num]] [--directories=action] [--label] [--line-buffered]
	[--null] [pattern] [file ...]
Error: Could not find latest version from feed https://www.nuget.org/api/v2
```

I'm running OS X Yosemite 10.10.4 and GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin14)

### Solution
However, I resolved the issue by editing two lines in dvnm.sh in function __dnvm_find_latest()
The latest version of dnx was not extracted due to wrong placements of quotes and an erraneous regex call to grep.

Before
```
91 -    xml="$(curl $url 2>/dev/null)"
92 -    echo $xml | grep \<[a-zA-Z]:Version\>* >> /dev/null || return 1
```
After
```
91 +    xml=$(curl "$url" 2>/dev/null)
92 +    echo "$xml" | egrep "(\<[a-zA-Z]:Version\>)*" >> /dev/null || return 1
```

**Comment by etsit** [comment]
Pull request: https://github.com/aspnet/Home/pull/754

**Comment by Eilon** [comment]
Please move to https://github.com/aspnet/dnvm/

**Comment by etsit** [comment]
Thank you. This issue is now transferred to:
https://github.com/aspnet/dnvm/issues/359
