### ISSUE TITLE
Error changing dnx port

### ISSUE THREAD

**Issue by cgarciae** [aspnet/Home#755]
The actual code is `dnx --port 5050 . web` and yields (in spanish.. sorry)
> System.Net.Sockets.SocketException (0x80004005): No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión 127.0.0.1:5050
   en System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   en System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
   en Microsoft.Framework.Runtime.DesignTimeHostProjectCompiler..ctor(IApplicationShutdown shutdown, IFileWatcher watcher, IRuntimeOptions runtimeOptions)

It runs ok on port 5000 without the `--port` option, strange enough it fails on the same port using `--port`.

**Comment by davidfowl** [comment]
Unfortunately, thats the wrong flag. That's actually the compilation server port, not the webserver port. We'll need to rename that in the future to avoid confusion.

**Comment by cgarciae** [comment]
@davidfowl Thanks!

How can I set the port?

**Comment by cgarciae** [comment]
Found it on the `project.json`, I had already checked there but didn't see it since it looks like a link. Consider making "web" and object so you can express it more naturally as json
```json
"commands": {
      "web": {
          "host": "localhost",
          "port": 5050,
          ....
      }
  }
```

**Comment by davidfowl** [comment]
I'm not sure we have a doc on how commands works ( @danroth27 ), but web is not a special command. Look at the value of it. The name can be anything, the value is what's important.
