### ISSUE TITLE
dnu ignores aspnetvnext feed on OS X

### ISSUE THREAD

**Issue by dopare** [aspnet/Home#757]
I have update Nuget config file with aspnetvnext feed but dnu still ignores it.
I can see aspnetvnext feed in `dnu feeds list`.

EDITED:
I have updated config in user folder but on `sudo dnu restore` it's says :
`NuGet Config files used: /var/root/.config/NuGet/NuGet.Config`

Manually setting `dnu restore -s https://www.myget.org/F/aspnetvnext/api/v2/ -f https://www.nuget.org/api/v2/` works

**Comment by davidfowl** [comment]
Where did you run `dnu feeds list` from?

**Comment by dopare** [comment]
Nice question, forgot to mention that I'm running `sudo dnu restore`, because of exception: `System.UnauthorizedAccessException: Access to the path '...' is denied.`
