### ISSUE TITLE
Please add support for System.ServiceModel.Syndication in .NET Core

### ISSUE THREAD

**Issue by RehanSaeed** [aspnet/Home#758]
Original post here https://github.com/dotnet/wcf/issues/76 on the WCF GitHub project. I thought I'd post this here also for visibility.

The gist of it is that we need System.ServiceModel.Syndication.SyndicationFeed to build Atom/RSS feeds but it does not exist in .NET Core.

**Comment by Eilon** [comment]
@RehanSaeed I don't think there's anything for ASP.NET or DNX to do for this. It's just a matter of the code in that repo being made available to such projects. As such, I'll close this issue.
