### ISSUE TITLE
VS 2015 with beta7: PackageManager

### ISSUE THREAD

**Issue by Aveline67** [aspnet/Home#759]
Hi all

I did install VS2015 (release version 14.0.23107) , then I did upgrade dnvm to beta7

    >dnvm list
         *     1.0.0-beta7-12264    clr    x86      C:\Users\naveline\.dnx\runtimes  default

but now I can not use VS anymore for intelisence/debug/launch etc..

###### I have this error:
    Could not load file or assembly 'Microsoft.DNX.PackageManager'

###### now if I look in my runtime folder I have:
.dnx\runtimes\dnx-clr-win-x86.1.0.0-beta7-12264\bin\lib\Microsoft.**Framework**.PackageManager\Microsoft.**Framework**.PackageManager.dll
###### but VS is looking for:
.dnx\runtimes\dnx-clr-win-x86.1.0.0-beta7-12264\bin\lib\Microsoft.**DNX**.PackageManager\Microsoft.**DNX**.PackageManager.dll

How I could amend the path in visual studio ?

**Comment by Brostin** [comment]
It has been announced here: https://github.com/aspnet/Announcements/issues/44

**Comment by Eilon** [comment]
@anurse

**Comment by anurse** [comment]
Yep, you're seeing the issue from aspnet/Announcements#44. Try the workaround there, and we'll update that issue when there's a fixed version of the VS tooling!
