### ISSUE TITLE
The requested feature is not implemented error

### ISSUE THREAD

**Issue by archasek** [aspnet/Home#762]
Hej, I have this error:

```
System.NotImplementedException: The requested feature is not implemented.
 Microsoft.Framework.PackageManager.Restore.NuGet.PackageUtilities.EnsureValidPackageContents (System.IO.Stream stream, Microsoft.Framework.PackageManager.PackageInfo package) [0x00000] in <filename unknown>:0
 Microsoft.Framework.PackageManager.Restore.NuGet.PackageUtilities+<>c__DisplayClass1_0.<OpenNupkgStreamAsync>b__0 (System.IO.Stream stream) [0x00000] in <filename unknown>:0
 Microsoft.Framework.PackageManager.Restore.NuGet.HttpSource+<GetAsync>d__8.MoveNext () [0x00000] in <filename unknown>:0
```

stacktrace: http://wklej.org/hash/5360fc51211/

**Comment by Eilon** [comment]
@anurse @ChengTian ?

**Comment by ChengTian** [comment]
@archasek , could you please share the version information of mono used here?

**Comment by archasek** [comment]
@ChengTian 
`
archas@archas-work:~$ mono --version
Mono JIT compiler version 3.2.8 (Debian 3.2.8+dfsg-4ubuntu4)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	LLVM:          supported, not enabled.
	GC:            sgen
`

**Comment by davidfowl** [comment]
@archasek Your mono is hella old. You need to update it to the latest.

**Comment by WolfgangFahl** [comment]
What? hella old ? This is still the mono-complete package which you get in a docker container as of 2017. How about some backward compatibility?

**Comment by davidfowl** [comment]
This issue was updated in 2015, that's 2 years ago. Mono is at version 5 now. I have no idea who maintains the mono docker container but that *very old* version doesn't work with ASP.NET Core. Backwards compatibility assumes we were ever compatible with a mono version that old which was never the case.

**Comment by WolfgangFahl** [comment]
So is there a docker version of a newer mono?

**Comment by davidfowl** [comment]
This is the wrong place to ask that. This would be the place to ask that question https://github.com/mono/docker

**Comment by WolfgangFahl** [comment]
I am only asking to theck the version number ... 5.0.1.1

**Comment by davidfowl** [comment]
The repository has all the information on docker containers for mono.

**Comment by frankxiongzz** [comment]
I got same error in unity3d
