### ISSUE TITLE
Can't run dnu restore on ubuntu

### ISSUE THREAD

**Issue by chenxizhang** [aspnet/Home#763]
![capture](https://cloud.githubusercontent.com/assets/1996954/8863428/32dc99b4-31cb-11e5-8faf-890925290579.PNG)

I want run the sample in a virtual machine which ubuntu installed,but got the error

thanks

**Comment by cnblogs-dudu** [comment]
Try `mozroots --import --sync`.

**Comment by chenxizhang** [comment]
Thank you very much
