### ISSUE TITLE
System.Xml.Serialization

### ISSUE THREAD

**Issue by TrygveSkogsholm** [aspnet/Home#764]
I am trying to reuse some code from the old web api. Created brand new ASP Web Application. System.Xml.Serialization Available in 4.5.1 but not Core 5.0.

What's going on here? I thought the core was well, the core about which 4.5.1 and 4.6 could orbit.

But looking at the project.json it's like a whole new environment. Can I get things like System.Xml.Serialization or Gibraltar to work? Can I drop Core 5 and still have a MVC 6 application?

Please someone set me straight.

**Comment by davidfowl** [comment]
How much have you read up about ASP.NET 5 and .NET Core? If not, I'd recommend some of the videos here https://channel9.msdn.com/Search?term=asp.net%205#ch9Search&lang-en=en.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
