### ISSUE TITLE
How to implement an async controller in MVC 6?

### ISSUE THREAD

**Issue by tinganho** [aspnet/Home#767]
I have searched for 2 hours and couldn't find an async example of how to implement an async controller in MVC 6. All examples seem to sync controllers.

What I want to achieve is something like below. But it doesn't work:

``` C#
[Route("api/[controller]")]
    public class MediaController
    {
         [HttpGet]
         public async Task<MediaList> Get()
         {
             Media media1 = new Media(DbContext) { Id = 1, Title = "Hello world" };
             DbContext.Medias.Add(media1);
             Media media2 = new Media(DbContext) { Id = 2, Title = "Hello world" };
             DbContext.Medias.Add(media2);

             var mediaList = await DbContext.Medias
                 .OrderByDescending(m => m.Id)
                 .Take(10)
                 .ToListAsync();

            return mediaList;
        }
```

**Comment by davidfowl** [comment]
What doesn't work? Looks fine.

**Comment by tinganho** [comment]
The response is empty. Also if I console write line after the query it never get executed:
```C#
          var mediaList = await DbContext.Medias
                 .OrderByDescending(m => m.Id)
                 .Take(10)
                 .ToListAsync();
          Console.WriteLine("Hello"); // Don't get executed
```

**Comment by tinganho** [comment]
@davidfowl just a follow question is it suppose to Json serialise the medialist automatically when I return it?

**Comment by Eilon** [comment]
I'm not sure if you can immediately query data that you just added to the DbContext but haven't yet persisted to the database. Ultimately the call to query the Media items will do a SQL query and of course the SQL database doesn't have these new items.

**Comment by tinganho** [comment]
what is the right implementation?

**Comment by Eilon** [comment]
Insert the data into the database in some other operation. Presumably you don't really want the `Get()` method of your controller to insert data into the database. Then in the `Get()` method just do the query and see if that works.

**Comment by tinganho** [comment]
@Eilon still same empty response. I first goto `/api/values/5` and then to `/api/values`:
```
// GET api/values
[HttpGet]
public async Task<Media[]> Get()
{

    var mediaList = await DbContext.Medias
        .OrderByDescending(m => m.Id)
        .Take(10)
        .ToArrayAsync();

    Console.WriteLine("Helloworld");

    return mediaList;
}

// GET api/values/5
[HttpGet("{id}")]
public string Get(int id)
{
    Media media1 = new Media(DbContext) { Title = "Hello world" };
    DbContext.Medias.Add(media1);
    Media media2 = new Media(DbContext) { Title = "Hello world" };
    DbContext.Medias.Add(media2);
    Media media3 = new Media(DbContext) { Title = "Hello world" };
    DbContext.Medias.Add(media3);
    Media media4 = new Media(DbContext) { Title = "Hello world" };
    DbContext.Medias.Add(media4);
    DbContext.SaveChanges();
    return "value";
}
```

**Comment by BruceAtAFG** [comment]
@tinganho can you do some debugging here.
First, open your database and see if there are rows in the Media table
Second, set a break point in both of the Get().  Does the mediaList contain any data?

It would help to see if the problem you are having is in adding/getting data from DbContext or in returning the data from the action

**Comment by tinganho** [comment]
@BruceAtAFG I'm using the in memory storage. I'm on a mac using VSCode, I don't know how to set breakpoints with kestrel?

**Comment by tinganho** [comment]
Btw I know the changes are in the table. Because I accidently created two records with the same id and that crashed the application.

**Comment by BruceAtAFG** [comment]
@tinganho I have not worked with .NET on the Mac yet; although I would like to.  I would look into https://code.visualstudio.com/Docs/debugging it looks like it is available for Mac and you can debug with it.

**Comment by tinganho** [comment]
@BruceAtAFG I probably could but I don't know the exact command for it. I just know If I ran it through pure mono command and not through Kestrel.

**Comment by MhAlan** [comment]
is that even async without Task.Run ??

**Comment by davidfowl** [comment]
@MhAlan yes, you don't need `Task.Run` to make something async. http://blogs.msdn.com/b/pfxteam/archive/2012/03/24/10287244.aspx

**Comment by MhAlan** [comment]
@davidfowl , Thanks for the article, but it is irrelevant to my question. my question is not how to design async methods. my question is that this method there is marked async and returns Task but the code doesn't await any Task which will make it run synchronously.

**Comment by MhAlan** [comment]
@davidfowl , thanks for the article, that is not my question though, I just I didn't notice the await there XD

**Comment by davidfowl** [comment]
I wasn't sure, because you didn't say and you asked specifically about `Task.Run` 😉
