### ISSUE TITLE
Proper way to run dnu build for a ASP.NET solution with multiple projects

### ISSUE THREAD

**Issue by ganeshran** [aspnet/Home#768]
I am trying to run a ASP.NET project with the kestrel web server. The solution has one web project and other class libraries and dependencies. It's a .NET 4.5 app so I am using mono to execute dnu build. 

The command gets all the NuGet packages from the project.json but is not able to detect other projects in the solution. dnu build doesnt work when executed at the solution root.

How can I tell the dnu build that the project dependencies exist in the same solution folder?

**Comment by Eilon** [comment]
Can you share more info about the project/solution structure, and what errors you get?

**Comment by ganeshran** [comment]
@Eilon 

Let's say my default namespace is ABC.

So my project structure is 
>
ABC.sln
ABC.Web\ABC.Web.csproj
ABC.Contracts\ABC.Contracts.csproj
ABC.Data\ABC.Data.csproj
ABC.DependencyResolution\ABC.DependecyResolution.csproj


I am running dnu build from the Web project where it is able to fulfil the dependencies from nuget but not the projects in the solution. Is there any relative path i can give in project.json to tell it to pick up the dependencies from one folder level up? TIA

**Comment by davidfowl** [comment]
Where is the web project in that structure? All I see is csproj

**Comment by ganeshran** [comment]
@davidfowl All the web project files are inside ABC.Web project folder, I had omitted them for brevity. It also has the project.json which points to both internal and external nuget and those are getting resolved correctly. 

The ABC.Web also has dependencies to the remaining class library projects (Data, Contracts and DependencyResolution). I need to tell the project.json to point one level up to build it's project level references but that doesn't work unfortunately.

**Comment by davidfowl** [comment]
If you want to add a reference to a csproj then add it through the VS ui. It should create a global.json and wrap folder as siblings to the solution. If you don't see that then it wont work. It would also be great if you could specify errors you're seeing.

**Comment by ganeshran** [comment]
Thanks @davidfowl  I'll try this. I created the project.json using search/replace from packages.config since I don't have VS 2015 yet. Will use it to create the global.json file. 

The  errors are basically "The type or namespace could not be found (are you missing a directive or assembly reference)". I'm on Windows right now but can post the complete log from Linux some time latter
