### ISSUE TITLE
NuGet3 build failure - missing KoreBuild

### ISSUE THREAD

**Issue by rhires** [aspnet/Home#775]
Hello. Trying to build on Mac OS X. I did a Google search and found this very same issue, and following the link I found that someone said it was fixed, but alas, I'm having the same issue with a freshly cloned repo on my system. KoreBuild is just not there:
./build.sh
Unable to find package 'KoreBuild'.
Installing 'Sake 0.2'.
Successfully installed 'Sake 0.2'.
./build.sh: line 31: packages/KoreBuild/build/dnvm.sh: No such file or directory
./build.sh: line 35: dnvm: command not found

I saw that it's in some older versions...but given they are older versions, I'm not sure that they're appropriate for the latest and greatest. I also did a bit of searching to see about getting KoreBuild separately, but it isn't a separate NuGet package, and I'm not sure where else I could get it.

**Comment by Eilon** [comment]
Which repo are you trying to build?

**Comment by rhires** [comment]
I knew I was missing something. Sorry about that.

Whatever is most currently in NuGet3-dev.zip on GitHub.

I was able to duplicate this behavior using ./build.sh on Mac OS X, running Mavericks. And using the "git clone” command - no difference.

Thanks!

**Comment by Eilon** [comment]
Sorry, exactly where is NuGet3? I don't see that in the `aspnet` org...

**Comment by rhires** [comment]
I was advised to post here, per [#1015](https://github.com/NuGet/Home/issues/1015). I'm not sure why, but just uncritically following directions.

**Comment by Eilon** [comment]
Hmm it looks like maybe the [NuGet feeds used in that repo](https://github.com/NuGet/NuGet3/blob/dev/NuGet.Config) don't have KoreBuild available maybe? I think this is more an issue in the NuGet builds - I doubt this is related to ASP.NET. It's just that NuGet happens to be using the same build system as ASP.NET (KoreBuild).

@emgarten the KoreBuild package isn't on nuget.org and it isn't on the NuGet MyGet volatile feed either. Can you reactivate https://github.com/NuGet/Home/issues/1015 and I can close this bug?

**Comment by emgarten** [comment]
Thanks @Eilon I've reopened https://github.com/NuGet/Home/issues/1015
