### ISSUE TITLE
dnu: Permission denied

### ISSUE THREAD

**Issue by spboyer** [aspnet/Home#779]
*.NET Version Manager - Version 1.0.0-beta7-10402*

Ran upgrade from beta5-* to 1.0.0-beta6 via `dnvm upgrade`

 ```
> dnu <command> 
-bash: /Users/<username>/.dnx/runtimes/dnx-mono.1.0.0-beta6/bin/dnu: Permission denied
```

run `dnvm install -f`

Updates dnvm to 
*.NET Version Manager - Version 1.0.0-beta7-10405*

 ```
> dnu <command> 
-bash: /Users/<username>/.dnx/runtimes/dnx-mono.1.0.0-beta6/bin/dnu: Permission denied
```

Permissions on `dnu`
```
-rw-r--r--   1 shayneboyer  staff      539 Jul 20 14:15 dnu
```

Needs permissions to run dnu commands. dnvm update-self, dnvm install -f, dnvm upgrade -u does not resolve permissions on dnu

```
-rwxrwxr-x
```

run chmod to set permissions correctly.

@glennc

**Comment by BrennanConroy** [comment]
Did you run ```dnvm install 1.0.0-beta6 -f``` before updating dnvm to beta7-10405?

**Comment by spboyer** [comment]
@brennanconroy I ran only `dnvm upgrade -f` not install prior to pulling dnvm off the repo per @glennc suggestion

**Comment by BrennanConroy** [comment]
You need to run it after updating, otherwise you'll get the permission denied still

**Comment by spboyer** [comment]
`dnvm upgrade`
...
`dnvm install -f` 

Is the fix for this issue, seems dnvm upgrade should just do both. But ok.
