### ISSUE TITLE
Shared project resources

### ISSUE THREAD

**Issue by max-vasin** [aspnet/Home#780]
I'am trying to create a solution with shared project. Shared project.json file contains "shared" property for code files, but i can't find such property for resources. Is it possible to share project resources among multiple dependent projects? I'am using 1.0.0-beta6 build.

**Comment by Eilon** [comment]
@max-vasin I don't believe that resources can be shared right now. Can you log a suggestion in the DNX repo?

**Comment by max-vasin** [comment]
@Eilon thx. Registered [suggestion](https://github.com/aspnet/dnx/issues/2383).
