### ISSUE TITLE
Missing CorsMiddleware

### ISSUE THREAD

**Issue by logitron** [aspnet/Home#781]
After upgrading a project to beta6 and installing the Microsoft.AspNet.Cors.Core 1.0.0-beta6 package, there is no longer the 'UseCors' extension for using the 'CorsMiddleware' component. 'ConfigureCors' and 'AddCors' still exist, but not 'UseCors'. I assumed this was removed, but after downloading the CORS beta6 release from GitHub, those components seem to still exist.

Project is just using dnx451.

**Comment by henkmollema** [comment]
Add `Microsoft.AspNet.Mvc.Cors` too.

**Comment by logitron** [comment]
Added `Microsoft.AspNet.Mvc.Cors`, too, but it doesn't seem to have `UseCors` either.  I do see that the package has `AddCors` and `ConfigureCors`.  I was using it fine in beta5.

**Comment by Eilon** [comment]
`UseCors` is defined in `Microsoft.AspNet.Cors` - please make sure you have a reference to that in `project.json`.

**Comment by logitron** [comment]
Thank you.  It looks like NuGet is showing 5.2.3 to be the absolute latest, which was causing confusion for me.  I had to come way down the list to 1.0.0-beta6.  Thanks!

**Comment by Eilon** [comment]
Ah, yes, we will fix the version thing. See https://github.com/aspnet/CORS/issues/24.
