### ISSUE TITLE
Web 5 Project Template: Gulp fails after commit to VSO with gitignore bin

### ISSUE THREAD

**Issue by jderus** [aspnet/Home#782]
Repro:
1) Create ASP.NET 5 App using template in VS2015 (Enterprise RTM).
2) Run it locally as a sanity check
3) Commit to VSO (with a gitignore for bin)
4) Create a new folder and clone repo
5) Open solution.
6) Observe Output below.
7) Attempt to restore packages (at the Dependencies level or via packages.json)
8) Observe Output below

Am I missing something with restoring? My expectation is that it would repopulate the bin folder on the local repo, and that I wouldn't have to commit bin .js files into repos.

```
Failed to run "XXX\Gulpfile.js"...
cmd.exe /c gulp --tasks-simple
module.js:340
    throw err;
          ^
Error: Cannot find module 'XXX\node_modules\gulp\bin\gulp.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3

Failed to run "XXX\Gulpfile.js"...
cmd.exe /c gulp --tasks-simple
module.js:340
    throw err;
          ^
Error: Cannot find module 'XXX\gulp\bin\gulp.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
```

**Comment by Eilon** [comment]
@madskristensen @DamianEdwards

**Comment by jderus** [comment]
Sorry for the delayed response. I think I figured out the problem. 
Throwing this up here in case someone else comes across it.

It seems like NPM doesn't (can't?) detect partially installed packages during restore. (This may not be specific to Visual Studio.)

If your gitignore is set up to ignore bin, but does not ignore node_modules, then your project may get into a state where NPM has partial packages (it is missing the bin\*.js files).

If you encounter the reported behavior, you can quickly check the issue by deleting the node_modules folders in your local repo, and restarting VS. This should allow NPM to fully pull all the right packages. 

The basic fix is to add node_modules to your gitignore.

**Comment by vackup** [comment]
Great answer @jderus !!! Solved my issue. Thanks

**Comment by MaximRouiller** [comment]
When ignoring folder try to avoid

    bin

And try to use this instead

    bin/

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
