### ISSUE TITLE
dnvm upgrade. Determining latest version Error

### ISSUE THREAD

**Issue by franciscojsr** [aspnet/Home#784]
Hello,

I followed the instructions to install dnx on macosx and when I do :   dnvm upgrade 
or other comands available, it doesn't work. What ever I do, shows:

$  dnvm upgrade
Determining latest version
Error: Could not find latest version from feed https://www.nuget.org/api/v2

I followed others solutions that I read in others issues, i tried all, but doesn't work anything.

I tried doing with http feed  --> http://www.nuget.org/api/v2:
 dnvm upgrade DNX_FEED=http://www.nuget.org/api/v2

but shows other error after doing some things: 
HTTP Error  fetching dnx-mono.1.0.0-beta6 from http://www.nuget.org/api/v2

Why it this happen? It can be fixed?

**Comment by Eilon** [comment]
Can you log this in https://github.com/aspnet/dnvm ? Thanks!

**Comment by franciscojsr** [comment]
Ok! Thanks! --> https://github.com/aspnet/dnvm/issues/382
