### ISSUE TITLE
Http listener on non iIs

### ISSUE THREAD

**Issue by gregoryyoung** [aspnet/Home#785]
this can be seen in mono today.

The http listener interface doesn't make much sense without iis. Currently the way you bind to a port is to pass a http prefix eg http://*:4444 this is used for two purposes. The first is to setup accept parameters it will bad host not matching requests this is also used to determine the port to bind to though!

Where this causes problems is in places like aws where I need to accept an elastic ip say 24.112.72.53 but bind locally on 10.114.56.74. As of now the httplistener code in mono does the only "reasonable" thing here and binds all. 

There are quite a few other little things like this around this api. What are the plans if any for supporting http listener cross platform and is this a time this interface could be fixed? I would like to fix monos but prefer to keep api compatibility as opposed to mono specific ways of doing things.

Greg

**Comment by benaadams** [comment]
> The http listener interface doesn't make much sense without iis. 

You mean without http.sys port and path sharing on windows? Don't need iis for httplistener.

**Comment by gregoryyoung** [comment]
sure.

**Comment by Eilon** [comment]
@Tratcher any thoughts on this?

**Comment by Tratcher** [comment]
Yes, there were issues trying to adapt Windows concepts for HttpListener over to Mono. HttpListener is being replaced by WebListener on Windows or Kestrel on cross-plat. Here's how we expect the bindings to work on Kestrel (soon) https://github.com/aspnet/KestrelHttpServer/issues/98#issuecomment-121390683

IIS, HttpListener, and WebListener all build on the native Windows Http.Sys library and it controls the prefix logic.

**Comment by gregoryyoung** [comment]
So leave everyone behind and have a new Api?

On Friday, July 31, 2015, Chris R <notifications@github.com> wrote:

> Yes, there were issues trying to adapt Windows concepts for HttpListener
> over to Mono. HttpListener is being replaced by WebListener on Windows or
> Kestrel on cross-plat. Here's how we expect the bindings to work on Kestrel
> (soon) aspnet/KestrelHttpServer#98 (comment)
> <https://github.com/aspnet/KestrelHttpServer/issues/98#issuecomment-121390683>
>
> IIS, HttpListener, and WebListener all build on the native Windows
> Http.Sys library and it controls the prefix logic.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aspnet/Home/issues/785#issuecomment-126787648>.
>


-- 
Studying for the Turing test

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.

**Comment by davidalpert** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  spinthemoose@gmail.com
    Domain spinthemoose.com has exceeded the max emails per hour (248/200 (124%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o7.sgmail.github.com ([167.89.101.198]:45544)
	by cp1164.blacksun.ca with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89_1)
	(envelope-from <bounces+848413-6f87-david=spinthemoose.com@sgmail.github.com>)
	id 1eVkIb-0001Uk-0J
	for david@spinthemoose.com; Sun, 31 Dec 2017 14:33:37 -0600
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=A94/YX4ElbWLqOUPKHoJplo4Axo=; b=WQlVEpghanyK0LRU
	IbGUOKlTozL2ABl1JacwXbA7oXR4iJCSuUK6uqR6enBoaowoCkNj+8cvU44dnX8o
	n0RGH3hgaA8s/DHW0zOWhxi1OZD3Mdepcw+02aylZaeZkl5xhpyXYvACK1+du7pP
	OqhCJYDIkdbaRabcrvGudnSb4u4=
Received: by filter1259p1mdw1.sendgrid.net with SMTP id filter1259p1mdw1-21768-5A49498C-10
        2017-12-31 20:33:16.418531952 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0010p1iad2.sendgrid.net (SG) with ESMTP id V2thv_AxQqWs6i65_5LnEA
	for <david@spinthemoose.com>; Sun, 31 Dec 2017 20:33:16.475 +0000 (UTC)
Date: Sun, 31 Dec 2017 20:33:16 +0000 (UTC)

**Comment by davidalpert** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  spinthemoose@gmail.com
    Domain spinthemoose.com has exceeded the max emails per hour (249/200 (124%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o3.sgmail.github.com ([192.254.112.98]:39517)
	by cp1164.blacksun.ca with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89_1)
	(envelope-from <bounces+848413-6f87-david=spinthemoose.com@sgmail.github.com>)
	id 1eVkIb-0001Uj-3F
	for david@spinthemoose.com; Sun, 31 Dec 2017 14:33:37 -0600
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=F/yTWj2E4w2QEoz2fHNG1UMSByQ=; b=qISpp9rTXvTKS/cp
	HP+/In8hVQOoj/Uksdu5NJz61rFFHU4j5p6vmbHdrNmLF/fVYh3rzfL0egy19jIU
	0k1hUyKBKVPU24+zijX4R+ve+Xnw4h/A1oKHMkl55VnYDnoF9jXVZktINcEKDjW8
	mzDjiQPOakjHvZDPY+mICtd1wkk=
Received: by filter0113p1las1.sendgrid.net with SMTP id filter0113p1las1-27970-5A49498B-30
        2017-12-31 20:33:15.957719003 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0003p1iad1.sendgrid.net (SG) with ESMTP id 2iQ9oS2FQlCyb4CB--2ezA
	for <david@spinthemoose.com>; Sun, 31 Dec 2017 20:33:15.870 +0000 (UTC)
Date: Sun, 31 Dec 2017 20:33:15 +0000 (UTC)
