### ISSUE TITLE
Web tools 2015 beta6 does not detect VS2015 if it is not running

### ISSUE THREAD

**Issue by sichevmi** [aspnet/Home#786]
subj

**Comment by Eilon** [comment]
@joeloff thoughts?

**Comment by joeloff** [comment]
The installer does check to see if VS is installed, but we don't check to see whether its running. If anything it should not be running. We don't block on running process because a silent install would simply kill the active processes and users can lose unsaved work.

@sichevmi are you saying that unless VS (devenv process) is running, WTE blocks the install from proceeding? That's currently the only check we're doing to see whether you have VS installed that's applicable.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.

**Comment by davidalpert** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  spinthemoose@gmail.com
    Domain spinthemoose.com has exceeded the max emails per hour (246/200 (123%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext1.iad.github.net ([192.30.252.192]:38476 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by cp1164.blacksun.ca with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.89_1)
	(envelope-from <noreply@github.com>)
	id 1eVkIU-0001UG-6i
	for david@spinthemoose.com; Sun, 31 Dec 2017 14:33:30 -0600
Date: Sun, 31 Dec 2017 12:33:09 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1514752389;
	bh=DrWw1FEMxH6/YWGXVkZfjrFxefxrwifWTmOJCbVomQs=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=RuhQmHw5e2RhxVzoGeUVWy3XmNqoUPw9fZoSPTRyOcDDl3PUf/P2+ofOIwbRZmAPK
	 mJAu+NPeIEpdOl5+4c5yHRBo/aYUpTtTuUJROgpLptB7rzGjFeiV4seUyOrhU1L31A
	 tsBvceDThtNoDss7AICmNPEYH+5wbGZOc1W2NsgA=

**Comment by davidalpert** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  spinthemoose@gmail.com
    Domain spinthemoose.com has exceeded the max emails per hour (247/200 (123%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o11.sgmail.github.com ([167.89.101.202]:47592)
	by cp1164.blacksun.ca with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89_1)
	(envelope-from <bounces+848413-6f87-david=spinthemoose.com@sgmail.github.com>)
	id 1eVkIZ-0001Uf-8F
	for david@spinthemoose.com; Sun, 31 Dec 2017 14:33:35 -0600
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=cXSuVWuikSOISf94kAXmYziIu9s=; b=PdHHWzTRDsZLdjk5
	cKJJnXcxQBISHmh9sG95ZLu2nV6dSN2oPvUKQ4rJDCUsdiw74k3VAPe/cSUE1tsT
	kJrkuHk6H2cAtCBF1xIXGRnDAv0ef5xLwUCteVtJu8cG2+GruMD1KJIk9BpBX5OF
	/X4SFOhikj5TYCADPYIpyXQBeaw=
Received: by filter1153p1mdw1.sendgrid.net with SMTP id filter1153p1mdw1-16009-5A494986-2
        2017-12-31 20:33:10.103431875 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0022p1iad2.sendgrid.net (SG) with ESMTP id KVrxGFDMSNqiY1fAj1RRDQ
	for <david@spinthemoose.com>; Sun, 31 Dec 2017 20:33:10.126 +0000 (UTC)
Date: Sun, 31 Dec 2017 20:33:10 +0000 (UTC)
