### ISSUE TITLE
How would one receive a json object, process it, then return Json back via http in asp.vNext?

### ISSUE THREAD

**Issue by govpack** [aspnet/Home#787]
How would one receive a json object +[process with a dynamically loaded method /async task] 
and then return the Json result back via http in asp.vNext?

It's a pretty common use case for an http server to be able to act as a json API... last night i cloned and browsed the source code of glimpse v2, to see how such a thing could be done (but there were way too many files and i didn't know which way was up) i google and i bing but i'm yet to see a small example that demonstrates such a thing in action.

for example here's how it could be done in 50 lines of javascript using dynamically loaded worker methods in •r:Ruby •v:JS •w:Clojure •x:Perl •y:Python •z:PHP

``` javascript
vx=require('vertx')
LOG=require('vertx/console').log
container=require('vertx/container')
DP=container.deployWorkerVerticle
l={a:LOG,j:JSON.stringify}
eb=vx.eventBus;
eb.registerHandler('godo',godo)
NUT={}
toolz={
fix:function(o){/*Ready o.[rx|rv|ry|rn] properties*/
if(typeof o.rx=='number'){o.rx=[o.rx.toString()]}
if(typeof o.rx=='string'){o.rx=o.rx.replace(/[\W\s]+$/,'').split('/');for(var i=0;i<o.rx.length;i++){if(/^-?\d+/.test(o.rx[i])){o.rx[i]=Number(o.rx[i])}}}
if(typeof o.rv=='undefined'){o.rv=''}
if(typeof o.ry=='undefined'){o.ry=[]}
if(typeof o.rn=='undefined'){o.rn=0}
if(o.cb){/*jsonp*/o.rb=-3}
if((''+o.rx[0]).charAt(0)=='~'){o.rb='-'+o.rx[0].substr(1);o.rx.shift()}else if(!o.rb){o.rb=o.all?-2:-1}
}
}
var N=0

function godo(o,cb){/*Run o thru one or more verticles*/
LOG(o.rn+' von.js received: ' + l.j(o));o.rb=++N
NUT[o.rb]=(function(cb){return function(o){cb(o)}})(cb)
toolz.fix(o)
DoNext(o)
} 

function DoNext(o){LOG(o.rn)
if(o.rn!=0){o.e=o.rv}
if(o.rn>=o.rx.length){LOG('returning: ' + l.j(o));NUT[o.rb](o);/*delete NUT[o.rb]*/;return}
var ns=''+o.rx[o.rn];var s=ns.charAt(0);var n=parseInt(ns.substr(1))
LOG(o.rn+'/'+o.rx.length+' ~ '+ns+'['+n+']'+s)
o.rn+=1;
var ext=({r:'rb',v:'js',w:'clj',x:'pl',y:'py',z:'php'})[s]
LOG('EXT:'+ext)
if(!ext){NUT[o.rb](o);delete NUT[o.rb];return}
if(s=='v' && n==3){var RV='fail';try{eval('RV=('+o.e+')')}catch(er){RV=er.message};LOG(RV);o.rv=RV;return DoNext(o);}
if(NUT[ns]){LOG(ns+' already loaded');return eb.send(ns,o,DoNext)}
var fpr='../../../../2/'+s+s+'/Ax/'+n+'/'+s+'.'+ext;LOG('ns:'+ns);LOG('ns:'+fpr)
container.deployVerticle(fpr,null,1,function(){NUT[ns]=true;eb.send(ns,o,DoNext)})
}

web1=vx.createHttpServer()
sox=vx.createSockJSServer(web1)
sox.bridge({prefix:'/eventbus'},[{}],[{}])
web1.listen(1422)
```

this is the same question as: https://github.com/aspnet/Home/issues/770
except that one shows "Powershell Listening on http://127.0.0.1:1416..." 
getting and returning Json via http

**Comment by Eilon** [comment]
@danroth27

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.

**Comment by davidalpert** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  spinthemoose@gmail.com
    Domain spinthemoose.com has exceeded the max emails per hour (245/200 (122%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o9.sgmail.github.com ([167.89.101.2]:50735)
	by cp1164.blacksun.ca with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89_1)
	(envelope-from <bounces+848413-6f87-david=spinthemoose.com@sgmail.github.com>)
	id 1eVkIO-0001TP-M4
	for david@spinthemoose.com; Sun, 31 Dec 2017 14:33:24 -0600
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=n4COun1V0YeOpywiocUvfQU/57g=; b=K0bCsE1DGnSEvpnE
	eMO6DaHMnuXod4D4xowr5Ht0NrDtHFWh2Dk96QoDgwMqsCVxHx64tRUAfxy5eEqF
	8hrhtCDXsZZNbXaUr4vNISnG0pG6QugqUhGwYv7H/Jyc4Ua0svU12KPnpzox3tI/
	XVxIdN8UUPNRZ0Ord/fkKhjvLq0=
Received: by filter0571p1las1.sendgrid.net with SMTP id filter0571p1las1-29931-5A49497F-11
        2017-12-31 20:33:03.710634861 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0020p1iad2.sendgrid.net (SG) with ESMTP id J2PJk1EKTN2PIpT5cR9qRQ
	for <david@spinthemoose.com>; Sun, 31 Dec 2017 20:33:04.033 +0000 (UTC)
Date: Sun, 31 Dec 2017 20:33:03 +0000 (UTC)

**Comment by davidalpert** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  spinthemoose@gmail.com
    Domain spinthemoose.com has exceeded the max emails per hour (244/200 (122%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext4.iad.github.net ([192.30.252.195]:36957 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by cp1164.blacksun.ca with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.89_1)
	(envelope-from <noreply@github.com>)
	id 1eVkIO-0001TN-CD
	for david@spinthemoose.com; Sun, 31 Dec 2017 14:33:24 -0600
Date: Sun, 31 Dec 2017 12:33:03 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1514752383;
	bh=BrfknNwe5b0bs2L53LqGq6TnRmS3v6t/yfhVEdzzEs0=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=nK2zxoKXK8syTz9RbqiIfXJcvltNi3I3pDhwUpjBnGEICgU/v/4ITr3ljwvlf41z1
	 LB9Tt4PnvEiFdIsXDek6ITcHNR1l1Rugpqw2ptfC+3XRKp6rabQh4umOruAFC3Vjhp
	 /RC3c6JpzTNS4FPzUnBqYZ11ienOOCO9Pihj8E0k=
