### ISSUE TITLE
No intellisense comments in VS2015 RTM?

### ISSUE THREAD

**Issue by Daniel15** [aspnet/Home#788]
I'm not seeing any intellisense comments for some ASP.NET 5 classes in Visual Studio 2015 RTM, for example the `IServiceCollection` methods:

![no-intellisense](https://cloud.githubusercontent.com/assets/91933/9020908/bb9de5fc-37dc-11e5-93b0-c815ee1a2ec5.png)

How do I resolve this? Are there just chunks of the framework that don't have code comments yet, or is this a Visual Studio issue?

**Comment by Eilon** [comment]
@Daniel15 indeed it looks like some of these just don't yet have doc comments. We keep adding more and more and we haven't gotten to that type yet. You can see the source code here: https://github.com/aspnet/DependencyInjection/blob/cbd74e57f28da3f4fc90174b4cf91042fa07a323/src/Microsoft.Framework.DependencyInjection.Abstractions/ServiceCollectionExtensions.cs#L270
