### ISSUE TITLE
ErrorPageOptions.ShowAll does now contain definition of ShowAll

### ISSUE THREAD

**Issue by developer1998** [aspnet/Home#789]
I got 1.0.0-beta7-12290 and ErrorPageOptions.ShowAll broke within the Startup.cs
```
            if (env.IsEnvironment("Development"))
            {
                app.UseErrorPage(ErrorPageOptions.ShowAll); //<--error here
                app.UseDatabaseErrorPage(DatabaseErrorPageOptions.ShowAll);
            }
```
Any ideas? Thanks...

**Comment by BrennanConroy** [comment]
Thats because it no longer exists
https://github.com/aspnet/Diagnostics/commit/0da9e2bec5f991f526edc729b8b73c0dbb8b2876

**Comment by Eilon** [comment]
Right, the option isn't needed anymore: it's either totally on or totally off.

**Comment by developer1998** [comment]
Thank you guys:)
