### ISSUE TITLE
How to install MVC 6 template on VS 2014 CTP

### ISSUE THREAD

**Issue by SalihKARAHAN** [aspnet/Home#79]
Hi,

I need a mvc 6 template for look up to new features but i don't it. After I talk about this problem with Imran [on ASP.NET forum. ]
(http://forums.asp.net/t/1992275.aspx?How+to+install+mvc+6+template+on+Visual+Studio+14+CTP)

Why "MVC 5 View Page (Razor)" writes on "add new item" screen of ASP.NET vNext project?

**Comment by Praburaj** [comment]
I think there is no further action item on this bug and there is a connect bug open on vs tooling for this.
