### ISSUE TITLE
ActionFilterAttribute implementation show some error

### ISSUE THREAD

**Issue by Devansh3790** [aspnet/Home#791]
I am working in MVC-5 from last 6 months and there was a scenario when i need to redirect user to home page if user is authenticated and want to access login/registration page. That problem is solved with following code:  

```
public class RedirectAuthenticatedRequests : ActionFilterAttribute
{
    public override void OnActionExecuting(ActionExecutingContext filterContext)
    {
        if(filterContext.HttpContext.Request.IsAuthenticated) {
            filterContext.Result = new RedirectToRouteResult(
                new RouteValueDictionary(new {
                        controller = "Home",
                        action = "Index"
                }
            ));
        }
        base.OnActionExecuting(filterContext);
    }
}
```

But when i am trying to put this code in MVC 6 that shows error :
CS1061 C# '' does not contain a definition for '' and no extension method '' accepting a first argument of type '' could be found (are you missing a using directive or an assembly reference?)

I am new to MVC-6 
Thanks in advance

**Comment by rynowak** [comment]
This is just a compile error in your code.
