### ISSUE TITLE
Rebuilding a solution

### ISSUE THREAD

**Issue by developer1998** [aspnet/Home#792]
When rebuilding a solution, I've noticed it runs the gulp file Gulpfile.js and a clean command.
cmd.exe /c gulp -b ...

1) How can I control this, what if I don't want to run gulp on rebuild, but grunt. Where would I set this?
2) How to change the gulp execution that it runs clean and perhaps another gulp command? 

Thanks.

**Comment by Daniel15** [comment]
View -> Other Windows -> Task Runner Explorer. Right-click a task and select Bindings to make it run on clean or build.
![gulp](https://cloud.githubusercontent.com/assets/91933/9053799/bf677cda-3a2e-11e5-9863-88e40f1c082a.png)

You can remove an existing binding in the same way (or just remove the `/// <binding Clean='clean' />` from the top of the gulpfile)

**Comment by developer1998** [comment]
Thank you so much.

**Comment by developer1998** [comment]
This really makes you appreciate the effort you guys put into the IDE.
I've noticed one though, that the Bindings on selection do not immediately refresh visually, until you for example run ReBuild. No a big thing though.
