### ISSUE TITLE
Setting Last-Modified header

### ISSUE THREAD

**Issue by Daniel15** [aspnet/Home#793]
What is the equivalent to `Response.Cache.SetLastModified` (which sets the `Last-Modified` response header) in ASP.NET MVC 6? Should I just set it through `Response.Headers.Set`?

**Comment by Eilon** [comment]
@Daniel15 yes I believe you would just set the header directly. I was never a big fan of the `Cache` stuff in ASP.NET 4.x (and earlier) because it conflated output cache, client cache, and so many other things.

Adding @Tratcher in case he knows of some other way.

**Comment by Daniel15** [comment]
Also is `VaryByParam` no longer required? I guess that makes sense since `ResponseCache` is only for response caching, and params are always taken into account with response caching anyways.

Is there an easy way to do server-side caching of a response? I used to be able to use `[OutputCache(Location = OutputCacheLocation.Server)]` for that.

**Comment by Eilon** [comment]
There's an empty repo [here](https://github.com/aspnet/ResponseCaching) just begging to be implemented :smile: VaryByParams is needed for server output caching, which isn't yet implemented.

**Comment by Tratcher** [comment]
Yes, the response caching implementation is incomplete. The middleware @Eilon referenced should be a full implementation and support Vary. We'll have to see how complex the VaryBy support gets though.

IIS and WebListener expose Http.Sys's kernel mode cache. Responses that are marked Cache-Control: public and have an expiration will be considered, but nothing with a Vary header can be cached.

**Comment by Daniel15** [comment]
Thank you!
