### ISSUE TITLE
Impossible to access resx files in Class Library

### ISSUE THREAD

**Issue by Chimerique** [aspnet/Home#794]
Hi,
Beta 6 did not resolve my problems with localization.

Resex files are not in the web project (but I did try to put them there) and are in a separated Class Library (wrap).
This project has a simple static method that is working fine when called from a Console application
But when it's called from asp.net Vnext, it always return the default resx value

```
static ResourceManager m_resource = new ResourceManager(typeof(localization));

public static string GetLocalization(string code, CultureInfo culture = null)
		{
            string translation = culture == null ? m_resource.GetString(code) : m_resource.GetString(code,culture);
            return string.IsNullOrEmpty(translation) ? code : translation;
        }

I added the UseRequestLocalization int the Startup.cs it feels that it's more about formatting 
```

Thanks
Cyril

**Comment by victorhurdugaci** [comment]
@kirthik

**Comment by kirthik** [comment]
@Chimerique - dnx does not yet have the ability to read culture specific resources. That work is in progress.

**Comment by Eilon** [comment]
@kirthik do we have a bug in DNX to track this?

**Comment by kirthik** [comment]
filed - https://github.com/aspnet/dnx/issues/2408

**Comment by Chimerique** [comment]
@kirthik thanks, I'll keep an eye on this.
