### ISSUE TITLE
Beta 6 is app.UseSession() the replacement for app.UseInMemorySession()

### ISSUE THREAD

**Issue by rkeithhill** [aspnet/Home#796]
I couldn't find anything about this in the beta 6 announcements but my beta5 web site wouldn't compile on beta6 because UseInMemorySession() wasn't available.  Or possibly I'm missing a NuGet reference.

**Comment by Eilon** [comment]
Essentially, yes.

You can see the change here: https://github.com/aspnet/Session/commit/dab08ba7e90027a3bf1ef69f740427e93a310f09#diff-e4eb518dd0d4eed84905bebee0b5934bL17

**Comment by rkeithhill** [comment]
Thanks!

**Comment by israelito3000** [comment]
So, now how session state is going to be implemented in memory?

**Comment by Eilon** [comment]
@israelito3000 The defaults end up using an in-memory store as the distributed cache store. Alternatively, and to actually scale, there is a SQL Server based implementation of the distributed cache store.
