### ISSUE TITLE
XML content in `gulpfile.js` causes VS 2015 to crash

### ISSUE THREAD

**Issue by llaughlin** [aspnet/Home#802]
I'm not sure how, but a rogue line of (commented) XML got into a MVC6 `gulpfile.js`.

```
///// <binding AfterBuild='copyViews' Clean='clean' />
//'use strict';
//var gulp = require("gulp"),
//  rimraf = require("rimraf"),
...
```

Whenever VS would try to load a project with that file in the directory, VS 2015 (community and RC) would throw an exception. After I used a debugger on it, I got the (unhelpful) message `Data at the root level is invalid at line:1 position:1`.

This led me to believe it was somehow xml related, but I never would have guessed that commented xml in a javascript file would try to be parsed.

After removing the line, VS was able load the project successfully.

**Comment by Eilon** [comment]
@llaughlin can you log this in https://github.com/aspnet/Tooling/issues/ ? Thanks!

**Comment by llaughlin** [comment]
Ah, sure thing. Thanks for directing me!
