### ISSUE TITLE
Update the Project.json "Scripts" events 

### ISSUE THREAD

**Issue by ericis** [aspnet/Home#805]
Beta6 seems to introduce a "scripts" event that isn't documented in the Wiki called "prepublish".
https://github.com/aspnet/Home/wiki/Project.json-file

_*I've also seen "prepare" in previous releases._

Currently, the listed events are:
- prebuild
- postbuild
- prepack
- postpack
- prerestore
- postrestore

*Can descriptions of these dnu events also be added along with the conditions for when they apply?

**Comment by Eilon** [comment]
@danroth27 for docs.

**Comment by robfarmergt** [comment]
This would help out greatly. Currently trying to figure out the best event(s) to use when publishing to Azure web apps.

**Comment by johnnyreilly** [comment]
This would be really helpful.  I'm just picking up ASP.Net 5 now it's hit RC 1 and trying to find some documentation on this.

**Comment by ericis** [comment]
closing, it's been 1.5 years and it's probably different by now
