### ISSUE TITLE
dnvm.sh:  syntax error near unnexpected token `<'

### ISSUE THREAD

**Issue by cgershman** [aspnet/Home#807]
I'm receiving this error when executing dnvm.sh:

line 539: syntax error near unnexpected token '<'
line 539: '                                   read versionOrAlias downloadUrl < <(__dnvm_find_latest "$runtime" "$arch" "$os")'

This is being executed on an arm mx6 running Yocto. 
This had been executed successfully until late last week. (7/30/15).

**Comment by pranavkm** [comment]
Moved to https://github.com/aspnet/dnvm/issues/386
