### ISSUE TITLE
Beta7-12302 System.Reflection.TargetInvocationException was unhandled when run Web Api project

### ISSUE THREAD

**Issue by CarlosFreire** [aspnet/Home#808]
System.Reflection.TargetInvocationException was unhandled
Message: An unhandled exception of type 'System.Reflection.TargetInvocationException' occurred in mscorlib.dll
Additional information: Exception has been thrown by the target of an invocation.

**Comment by davidfowl** [comment]
You need to provide better details than that. Maybe a sample project uploaded to github with exact repro steps and a full stack trace.

**Comment by Asesjix** [comment]
I'm not sure, but I think it is because you the beta7 tooling not installed?
https://github.com/aspnet/Home/releases/tag/v1.0.0-beta7
>To use ASP.NET 5 beta7 with Visual Studio 2015, you will need to download and install the beta7 version (14.0.60831.0) of ASP.NET and Web Tools 2015.
>

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.

**Comment by davidalpert** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  spinthemoose@gmail.com
    Domain spinthemoose.com has exceeded the max emails per hour (238/200 (119%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o7.sgmail.github.com ([167.89.101.198]:55805)
	by cp1164.blacksun.ca with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89_1)
	(envelope-from <bounces+848413-6f87-david=spinthemoose.com@sgmail.github.com>)
	id 1eVkI6-0001RJ-Pg
	for david@spinthemoose.com; Sun, 31 Dec 2017 14:33:06 -0600
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=lmJskx9lPl6vhe0+Ehbet96Ec8A=; b=CHsaSbv6yzuRBtik
	GZDbTZIRZaTuUF8aF157yXSqFc78KrPQMV/B0Regoxt61javgxbtj6oCUrcvoiIo
	H007mD1j/EblHIuKOiRYGRMUTfTWl16a4SSW69hN3IJOogb9CwNi0zaeC2JtijDB
	8Ch37bNfI86GYJ6HzYTsCL7Zhjw=
Received: by filter1089p1mdw1.sendgrid.net with SMTP id filter1089p1mdw1-7109-5A49496E-7
        2017-12-31 20:32:46.189440334 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0005p1iad2.sendgrid.net (SG) with ESMTP id MWCw_ePeRqeI72KP4ZpZtg
	for <david@spinthemoose.com>; Sun, 31 Dec 2017 20:32:46.235 +0000 (UTC)
Date: Sun, 31 Dec 2017 20:32:46 +0000 (UTC)

**Comment by davidalpert** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  spinthemoose@gmail.com
    Domain spinthemoose.com has exceeded the max emails per hour (239/200 (119%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext3.iad.github.net ([192.30.252.194]:45221 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by cp1164.blacksun.ca with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.89_1)
	(envelope-from <noreply@github.com>)
	id 1eVkI6-0001RK-Pw
	for david@spinthemoose.com; Sun, 31 Dec 2017 14:33:06 -0600
Date: Sun, 31 Dec 2017 12:32:46 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1514752366;
	bh=jFWDKZxF79sBJKK2dZpdngK8CpoczFJOI93hRrQ2YQc=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=gRsfjBvvW/F3EFQg0zcNyjDH59Q05DG/A/a3E9GgHQVkaoSagrfTaloCaDVgqrmsY
	 kUnIt7BusxcDEHwfUXOlggaw5hPNXkJmeQuFA4/9Aci2TbadB6Cr3uuoWt9uyBIIqy
	 rFSkKoM4dkt0IvMJPe5E2aYUdWm14dCsMTFhriOk=
