### ISSUE TITLE
K VS "turds" in a central folder

### ISSUE THREAD

**Issue by glennblock** [aspnet/Home#81]
Yes, there is no other word for it. Take a beautifully simple K app like the one below:

![image](https://cloud.githubusercontent.com/assets/141124/3310099/9e5c833e-f6ad-11e3-9d8a-7f1c99c0fc92.png)

Open it up into VS and this happens:

![image](https://cloud.githubusercontent.com/assets/141124/3310100/a45fa0ea-f6ad-11e3-9bc3-dc0ae56c2a8c.png)

I now have 4 things that I really don't care about that I have to manage. It went from simple to ugly all in one simple load into VS. Yes I am spoiled with node bias.

How about we put all these "turds" in a central .vs folder at the solution level (hidden)? That would still allow these files to be present but it will get them out of the way. It will make copy/pasting things much easier as well.

**Comment by danroth27** [comment]
@sayedihashimi @BillHiebert @barrytang 

Note you can now file VS tooling specific issues on the new [Tooling](https://github.com/aspnet/tooling) repo.

**Comment by sayedihashimi** [comment]
The ```.kproj``` and ```.kproj.user``` file have to be in the root of the project. We cannot do this without broad changes to Visual Studio itself. With that said we have made a conscious effort to not include any additional files. For example in that latest release we create an applicationHost.config file for each solution and we place that under the .vs folder.

Since there is nothing left for the VS Web tooling team can we close this?

**Comment by danroth27** [comment]
@glennblock Let us know if you have any more thoughts on this. Closing for now.

**Comment by glennblock** [comment]
Thanks for the updated. To confirm, this means only 2 files appear in the
root, everything else is in .vs?

**Comment by sayedihashimi** [comment]
@glennblock correct for ASP.NET 5 projects in VS2015 CTP6

**Comment by glennblock** [comment]
bin/obj ?

**Comment by sayedihashimi** [comment]
@glennblock they are not present in ASP.NET 5

**Comment by BillHiebert** [comment]
Note that this is controlled by msbuild properties in the .kproj file. If you have an old .Kproj file it won't have these properties and you could still end up with obj & bin under the project.

**Comment by glennblock** [comment]
OK cool. I can accept the 2 files though it would be nice if we could break the VS constraint on this. Thanks for listening, this is an improvement for sure.

**Comment by PureKrome** [comment]
Yeah @glennblock - i feel like it's sooooo close ... but still not there. VS (the editor) still leaks into everything :/ but yes - massive improvement and very very happy :+1:

**Comment by am11** [comment]
As a major step forward, with tons of breaking changes coming across the board, wouldn't it make sense to nail this issue down to one separate directory; `.vc`? BTW, thanks for preferring the .name convention! :+1: 

For that matter, if VS requires some path resolving changes, then it is worth the effort IMHO. Other project systems might also take inspiration from this architecture. For example; the Cordova app project, which works cross platform seamlessly, shouldn't include VS related files all over the place. We can `.gitignore` those files, but would be really neat if those are collected in a separate `.vc` directory.

**Comment by sayedihashimi** [comment]
I agree with all your comments. Since this is a core VS issue the best way to get traction would be to create an item at http://visualstudio.uservoice.com. 

From what I understand to move the project file is a lot of work and very risky.

**Comment by glennblock** [comment]
Done: http://visualstudio.uservoice.com/forums/121579-visual-studio/suggestions/7189874-remove-the-need-for-kproj-and-kproject-user-proj

**Comment by am11** [comment]
Wow! That was some lightning speed! :zap: 

Thanks guys. Hopefully this will get convinced. :smiley:  :+1:

**Comment by sayedihashimi** [comment]
I may be wrong here now that I'm thinking more about it. When @glennblock brought up the item initially (_back in June_) I discussed with @BillHiebert and the understanding at the time was that it would be very difficult.

After that we made a bunch of changes to how the ASP.NET 5 project type, and the underlying project system, behave. I think we made changes that may make this more feasible. I will discuss with him tomorrow.

One question, what would the MSBuild expectation be if there was no .kproj file? Would you want MSBuild to be able to build a .sln file and ASP.NET 5 projects via project.json?

**Comment by glennblock** [comment]
That would be my expectation.

**Comment by sayedihashimi** [comment]
OK I chatted with @BillHiebert today about this. The tough part is the MSBuild support. We can get the in Visual Studio experience without a project file but getting MSBuild support would be difficult.

#### Some more info about the kproj file

Also we leverage the kpoj to support referencing standard C# projects (i.e. non ASP.NET 5 project). In the case where a standard C# project is referenced in the .kproj file you'll find a ```ProjectReference``` element.

The .kproj file is also an integration point for partners (i.e. TypeScript, etc) to enable other scenarios. 

The .kproj file also contains some info for the json editor which is applied while in Visual Studio.

So even if we are able to get rid of the .kproj file we will need to find a home for these other Visual Studio specific items.

**Comment by PureKrome** [comment]
Just a thought:

1) can the `.kproj` file be used as a _plan B_ for the shortish term until those sections find a new home somewhere?

eg. Typescript will look for it's info in some new file (typescript.json) and if that's not there, then try the `.kproj`? Of course - right now - there's no new file .. so it's just falling back to plan b -> the kproj.

2) can this file (which is still required in the shortish term) still be moved into the `vs` directory? Or are all those pain points above, hardcoded to looking for the kproj file _in the root_ directory?

**Comment by glennblock** [comment]
What kind of info for the json editor? Is this preferences or something else? Can that be put in a sep file in the `.vs` folder?

As to project references, why not allow Project.json to let you specific a project references that way? Why does it have to be in the .kproj?

**Comment by sayedihashimi** [comment]
>1) can the .kproj file be used as a plan B for the shortish term until those sections find a new home somewhere?

Sure but if they need to go into a file then what's the point of getting rid of the .kproj? Also that would mean more than 1 file potentially, so we could regress it.

>can this file (which is still required in the shortish term) still be moved into the vs directory? Or are all those pain points above, hardcoded to looking for the kproj file in the root directory?

I don't think the ```.vs``` folder is the right place for this. These should be able to be checked in. Maybe we could move them under ```Properties``` to hid them?

>What kind of info for the json editor? Is this preferences or something else? Can that be put in a sep file in the .vs folder?

Info like the schema that was used for a given file.

>As to project references, why not allow Project.json to let you specific a project references that way? Why does it have to be in the .kproj?

I will let @davidfowl or @glennc comment back as that is a runtime feature.

**Comment by xtianus79** [comment]
perhaps I am in the total wrong place for this.  I have an installation i do via NPM... 
When I do these steps in a VS 2015 CTP 6 project folder whether it is on the root or otherwise... Something from Bower is not correct.  it won't allow bower to inject libraries in the project.  not from a VS point of view but from a CLI point of view which always works.  I am trying to get my projected loaded correctly into VS. 

here are the steps

NPM install -g yo 
NPM install -g generator -g generator-zf5
yo zf5

upon performing the "grunt" command... the watch takes place and the browser is loaded with the index.html page but the bower libraries are never injected.  i.e. jquery isn't loaded and thus doesn't work.  A real head scratcher... 

I can take the same folder move it one directory up out of the project folder and like magic it works.  

I have tried to delete every file and folder... even the hidden .vs folder and nothing works.  it is the oddest thing.

**Comment by sayedihashimi** [comment]
@xtianus79 please open a new issue since it doesn't relate to this thread.

**Comment by xtianus79** [comment]
I did... after I reread it I figured it wasn't this issue. Sorry about that.

**Comment by sayedihashimi** [comment]
@xtianus79 thanks, I'll delete the messages here.

**Comment by glennc** [comment]
The project reference in the msbuild file is really just so that it's built in the correct order isn't it? The runtime uses the wrapped project.json from `kpm wrap`.

**Comment by sayedihashimi** [comment]
>The project reference in the msbuild file is really just so that it's built in the correct order isn't it?

Yes that's correct.
