### ISSUE TITLE
ASP.Net 5 projects will not load/build in VS2015

### ISSUE THREAD

**Issue by rykr** [aspnet/Home#813]
I think there is a current workaround for this but I'm not sure how to apply it.   I create a project in VS2015 based on ASP.Net 5 templates and I get a project where none of the references are resolved and it will not build.

I apologize for the rookie question.  Is there a wiki or post that outlines the easiest way to develop asp.net 5 based projects?

**Comment by rykr** [comment]
ok, I did a dnu restore in my project folder and now all the unresolved assemblies are resolved.  But now when I try to build with vs 2015 RTM I get the error that the parameter is incorrect.  What parameter?

**Comment by rykr** [comment]
Please disregard. installed beta 6 (finally found it) and seems all good.

**Comment by feccruz** [comment]
Estou aprendendo todos os dias algo novo, aplicando as novas ferramentas existentes e lançadas como novidades paa a comunicação social e comercial.
