### ISSUE TITLE
DNX . ef Migration add Unable to load file or assembly Microsoft.Framework.Configuration.Json

### ISSUE THREAD

**Issue by ghiloufi** [aspnet/Home#814]
dnvm version: 1.0.0-beta6 

Global.json:
{
    "projects": [ "src", "test" ],
    "sdk": {
        "version": "1.0.0-beta6",
        "runtime": "clr",
        "architecture": "x86"
    }
}

project.json in the web project whichis the startup project : 
{
  "webroot": "wwwroot",
  "userSecretsId": "aspnet5-MGroup.CRM-b0bd6007-b342-407d-a34d-ad4d2c3ub7et",
  "version": "1.0.0-*",

  "dependencies": {

```
"EntityFramework.Commands": "7.0.0-beta6",
"EntityFramework.Core": "7.0.0-beta6",
"EntityFramework.SqlServer": "7.0.0-beta6",
"Microsoft.AspNet.Authentication.Cookies": "1.0.0-beta6",
"Microsoft.AspNet.Authentication.Facebook": "1.0.0-beta6",
"Microsoft.AspNet.Authentication.Google": "1.0.0-beta6",
"Microsoft.AspNet.Authentication.MicrosoftAccount": "1.0.0-beta6",
"Microsoft.AspNet.Authentication.Twitter": "1.0.0-beta6",
"Microsoft.AspNet.Diagnostics": "1.0.0-beta6",
"Microsoft.AspNet.Diagnostics.Entity": "7.0.0-beta6",
"Microsoft.AspNet.Identity.EntityFramework": "3.0.0-beta6",
"Microsoft.AspNet.Mvc": "6.0.0-beta6",
"Microsoft.AspNet.Mvc.TagHelpers": "6.0.0-beta6",

"Microsoft.AspNet.Server.IIS": "1.0.0-beta6",
"Microsoft.AspNet.Server.WebListener": "1.0.0-beta6",
"Microsoft.AspNet.StaticFiles": "1.0.0-beta6",
"Microsoft.AspNet.Tooling.Razor": "1.0.0-beta6",
"Microsoft.Framework.Configuration.Abstractions": "1.0.0-beta*",
"Microsoft.Framework.Configuration.UserSecrets": "1.0.0-beta6",
"Microsoft.Framework.Logging": "1.0.0-beta6",
"Microsoft.Framework.Logging.Console": "1.0.0-beta6",
"Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.0.0-beta6",
"jQuery.Grid": "0.4.5",
"MGroup.BLL": "1.0.0-*",
"Microsoft.Framework.Runtime.Abstractions": "1.0.0-beta6",
"Microsoft.Framework.Configuration.Json": "1.0.0-beta*"
```

  },

  "commands": {
    "web": "Microsoft.AspNet.Hosting --config hosting.ini",
    "ef": "EntityFramework.Commands"
  },

  "frameworks": {
    "dnx46": { }
  },

  "exclude": [
    "wwwroot",
    "node_modules",
    "bower_components"
  ],
  "publishExclude": [
    "node_modules",
    "bower_components",
    "**.xproj",
    "**.user",
    "**.vspscc"
  ],
  "scripts": {
    "postrestore": [ "npm install", "bower install" ],
    "prepare": [ "gulp copy" ]
  }
}

project.json in the DAL project which is contain the class context :

{
    "authors": [ "" ],
    "dependencies": {
        "EntityFramework.Core": "7.0.0-beta6",
        "EntityFramework.SqlServer": "7.0.0-beta6",
        "EntityFramework.Commands": "7.0.0-beta6",

```
    "MGroup.Data": "1.0.0-*"
},
"commands": {


    "ef": "EntityFramework.Commands"
},
"description": "",
"frameworks": {
    "dnx46": { }
},
"licenseUrl": "",
"projectUrl": "",
"tags": [ "" ],
"version": "1.0.0-*"
```

}

the startup class in the web project:

 public class Startup
    {
        public IConfiguration Configuration { get; set; }
        public Startup(IHostingEnvironment env, IApplicationEnvironment appEnv)
        {
            var builder = new ConfigurationBuilder(appEnv.ApplicationBasePath)
                .AddJsonFile("config.json")
                .AddJsonFile($"config.{env.EnvironmentName}.json", optional: true);

```
        if (env.IsDevelopment())
        {

            builder.AddUserSecrets();
        }
        builder.AddEnvironmentVariables();
        Configuration = builder.Build();

        JsonConvert.DefaultSettings = () => new JsonSerializerSettings
        {
            Formatting = Newtonsoft.Json.Formatting.Indented,
            ReferenceLoopHandling = Newtonsoft.Json.ReferenceLoopHandling.Ignore
        };
    }

         public void ConfigureServices(IServiceCollection services)
    {

        services.Configure<AppSettings>(Configuration.GetConfigurationSection("AppSettings"));

        services.AddEntityFramework()
            .AddSqlServer()
            .AddDbContext<MGroupDB>(options =>
                options.UseSqlServer(Configuration["Data:MGroupDB:ConnectionString"]));

        services.AddIdentity<ApplicationUser, IdentityRole>()
            .AddEntityFrameworkStores<MGroupDB>()
            .AddDefaultTokenProviders();

        services.AddMvc();

    }

    public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerfactory)
    {
        loggerfactory.AddConsole(minLevel: LogLevel.Warning);
        if (env.IsEnvironment("Development"))
        {
            app.UseBrowserLink();
            app.UseDatabaseErrorPage(DatabaseErrorPageOptions.ShowAll);
        }
        else
        {
            app.UseErrorHandler("/Home/Error");
        }

        app.UseStaticFiles();

        app.UseIdentity();

        app.UseMvc(routes =>
        {
            routes.MapRoute(
                name: "default",
                template: "{controller}/{action}/{id?}",
                defaults: new { controller = "Account", action = "Login" });

        });

        JsonConvert.DefaultSettings = () => new JsonSerializerSettings
        {
            Formatting = Newtonsoft.Json.Formatting.Indented,
            ReferenceLoopHandling = Newtonsoft.Json.ReferenceLoopHandling.Ignore
        };
    }
}
```

}

everything seem ok but always this problem appear after running 
dnu restore ==>ok
cd src\DAL ==> ok 
but
dnx . ef migration add mymigration -c context  -s Web 

dnx : System.IO.FileNotFoundException: Impossible de charger le fichier ou l'assembly 'Microsoft.Framework.Configuration.Json, Version=1.0.0.0, Culture=neutral, 
PublicKeyToken=null' ou une de ses d‚pendances. Le fichier sp‚cifi‚ est introuvable.
At line:1 char:1
- dnx . ef migration add MGZIED -s Web
- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : NotSpecified: (System.IO.FileN...st introuvable.:String) [], RemoteException
  - FullyQualifiedErrorId : NativeCommandError

Nom de fichierÿ
: 'Microsoft.Framework.Configuration.Json, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
   … Web.Startup..ctor(IHostingEnvironment env, IApplicationEnvironment appEnv)
--- Fin de la trace de la pile … partir de l'emplacement pr‚c‚dent au niveau duquel l'exception a ‚t‚ lev‚e ---
   … Microsoft.Framework.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   … Microsoft.Framework.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   … Microsoft.Framework.DependencyInjection.ActivatorUtilities.GetServiceOrCreateInstance(IServiceProvider provider, Type type)
   … Microsoft.AspNet.Hosting.Startup.StartupLoader.LoadMethods(Type startupType, IList`1 diagnosticMessages)
   … Microsoft.AspNet.Hosting.Internal.HostingEngine.EnsureStartup()
   … Microsoft.AspNet.Hosting.Internal.HostingEngine.EnsureApplicationServices()
   … Microsoft.AspNet.Hosting.Internal.HostingEngine.get_ApplicationServices()
   … Microsoft.Data.Entity.Commands.ContextTool.TryCreateContextFromStartup(Type type, String startupAssemblyName)
   … Microsoft.Data.Entity.Commands.ContextTool.CreateContext(Type type, String startupAssemblyName)
   … Microsoft.Data.Entity.Commands.MigrationTool.CreateContext(Type type, String startupAssemblyName)
   … Microsoft.Data.Entity.Commands.MigrationTool.AddMigration(String migrationName, String contextTypeName, String startupAssemblyName, String rootNamespace, String 
projectDir)
   … Microsoft.Data.Entity.Commands.Program.<>c__DisplayClass12_0.<AddMigration>b__0()
   … Microsoft.Data.Entity.Commands.Program.Execute(String startupProject, Func`1 invoke)
   … Microsoft.Data.Entity.Commands.Program.AddMigration(String name, String context, String startupProject)
   … Microsoft.Data.Entity.Commands.Program.<>c__DisplayClass10_1.<Main>b__7()
   … Microsoft.Framework.Runtime.Common.CommandLine.CommandLineApplication.Execute(String[] args)
   … Microsoft.Data.Entity.Commands.Program.Main(String[] args)
--- Fin de la trace de la pile … partir de l'emplacement pr‚c‚dent au niveau duquel l'exception a ‚t‚ lev‚e ---
   … System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   … Microsoft.Framework.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider serviceProvider)
   … Microsoft.Framework.ApplicationHost.Program.ExecuteMain(DefaultHost host, String applicationName, String[] args)
   … Microsoft.Framework.ApplicationHost.Program.Main(String[] args)
--- Fin de la trace de la pile … partir de l'emplacement pr‚c‚dent au niveau duquel l'exception a ‚t‚ lev‚e ---
   … System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   … Microsoft.Framework.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider serviceProvider)
   … dnx.host.Bootstrapper.RunAsync(List`1 args, IRuntimeEnvironment env, FrameworkName targetFramework)
   … dnx.host.RuntimeBootstrapper.ExecuteAsync(String[] args, FrameworkName targetFramework)
   … dnx.host.RuntimeBootstrapper.Execute(String[] args, FrameworkName targetFramework)

AVTÿ: la journalisation de liaison d'assembly est d‚sactiv‚e.
Pour activer la journalisation des ‚checs de liaison d'assembly, attribuez la valeur 1 … la valeur de Registre [HKLM\Software\Microsoft\Fusion!EnableLog](DWORD).
Remarqueÿ: une certaine perte de performance est associ‚e … l'enregistrement dans le journal des ‚checs de liaison d'assembly.
Pour d‚sactiver cette fonctionnalit‚, su

thank you for your help.

**Comment by ghiloufi** [comment]
@davidfowl can you help me please!

**Comment by ghiloufi** [comment]
@Nate McMaster

**Comment by ghiloufi** [comment]
@natemcmaster

**Comment by developer1998** [comment]
Your project has to compile for ef to run correctly. I had similar issue, could not get ef to run till I resolved all the errors.

**Comment by ghiloufi** [comment]
i hadn't any error and i resolved in fact the problem was with the command line it self ;)
thnx @developer1998
