### ISSUE TITLE
Problem adding HTML page to the project

### ISSUE THREAD

**Issue by developer1998** [aspnet/Home#816]
When I try to add HTML page to the project, I get the following error, the system cannot find the file specified. I am using Visual Studio 2015 Professional RTM.

![adding_html_page](https://cloud.githubusercontent.com/assets/8602645/9158702/48ae33d0-3ee9-11e5-94a9-b45368db88f4.png)

**Comment by Eilon** [comment]
@barrytang @mayurid can you take a look?

**Comment by mayurid** [comment]
@developer1998: A few questions:-
1) Do you see this issue only for ASP.NET5 projects? Or is it there for Webforms/MVC5 projects as well?
2) Can you check you local folders to see if the file exists at:-
%programfiles%/Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Web Tools\ItemTemplates\Client-side\1033\HTMLPage
3) Also to confirm, you are running 2015 RTM or do you have Beta6 bits installed?

Also looping in @joeloff

**Comment by developer1998** [comment]
@mayurid @joeloff regarding your questions
1) Yes WebForms and MVC5 Add HTML page worked fine.
2) Under Web I have MVC there is no Tools take a look at the image
![missing folders](https://cloud.githubusercontent.com/assets/8602645/9186822/9bd86ea0-3f97-11e5-8c37-bb37f7409bb1.png)
3) I've installed 2015 RTM and on top of it ASP.NET 5 preview (Beta6) as per the instructions in the Announcement community.

Thank you for looking into it.

**Comment by joeloff** [comment]
Hi @developer1998 

It should be "Extensions\Web Tools" not "Extensions\Web"

Thanks,
Jacques

**Comment by developer1998** [comment]
They are there, sorry for splitting the path
![files are there](https://cloud.githubusercontent.com/assets/8602645/9186947/0d676872-3f99-11e5-911c-d65eadf02c20.png)

Also I don't know if this is related but also I am getting this when I open the project
![jsextension](https://cloud.githubusercontent.com/assets/8602645/9186952/1cce015e-3f99-11e5-8900-e637086fbdd7.png)

**Comment by joeloff** [comment]
Ok, is there an ~IC folder: C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Web Tools\~IC\ItemTemplates\Client-side\1033\HTMLPage 

The item templates are placed locally within the extension, so VS typically builds a new local cache, hence the ~IC\ITemTemplates folder.

As for the other error, can you attach the ActivityLog.xml? You can also open it in your browser and it should show more detailed errors.

**Comment by developer1998** [comment]
The ActivityLog.xml says
```
  <entry>
    <record>633</record>
    <time>2015/08/10 23:46:44.391</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>End package load [JavaScriptWebExtensionsPackage]</description>
    <guid>{30DB8F9B-EC9F-44D6-B377-83C7C27A1A8B}</guid>
    <hr>80131500</hr>
    <errorinfo>Expected 1 export(s) with contract name "Microsoft.VisualStudio.JavaScript.Web.Extensions.ReferenceAutoSync.IReferencesFilePathProvider" but found 0 after applying applicable constraints.</errorinfo>
  </entry>
```

**Comment by joeloff** [comment]
That almost looks like a problem with the MEF cache.

Could you try the following first:

1. Close all instances of VS
2. Open a VS 2015 Developer command prompt (as Administrator). You can open a normal prompt as Admin too, but devenv.exe isn't typically on your default path.
3. Run devenv.exe /setup

One other question: Was VS by any chance open when you installed the Beta 6 update? That can corrupt the VS cache sometimes. The installation doesn't stop you from doing this because when you run the installer quietly, process blocks will simply kill any running processes and then developers risk losing data.

**Comment by developer1998** [comment]
I do have have the ~IC, should I delete it's contents?
C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Web Tools\~IC\ItemTemplates\Client-side\1033\HTMLPage

**Comment by joeloff** [comment]
You could do that before running /setup. /setup will rebuild that cache as well

**Comment by developer1998** [comment]
It was closed during the setup. I'm going to delete ~IC and run /setup

**Comment by developer1998** [comment]
I did that, and the HTML error persists and javascript extension package warning is there as well.

**Comment by developer1998** [comment]
I've just tried to add a Controller, also does not work. Looks like the template link is broken, maybe it is trying to get them from a location that does not exist...

**Comment by developer1998** [comment]
@joeloff @mayurid @barrytang @Eilon

**Comment by developer1998** [comment]
Thanks for your help guys.
