### ISSUE TITLE
Intellisense broken for css in ASP.NET 5 Project

### ISSUE THREAD

**Issue by developer1998** [aspnet/Home#817]
It does not work on sample project, and it does not work for my older project. This makes things extremely hard, especially when you dealing with all the bootstrap classes, and other libraries.

I am using Visual Studio Professional 2015 RTM. This used to work in previous releases...

I also tried to run, but it did not help
C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE>devenv.exe /ResetUserData

**Comment by Eilon** [comment]
@barrytang @mayurid can you take a look?

**Comment by developer1998** [comment]
This actually could be related to the JavaScript warning, which based on this case looks like indicates a broken CSS and JavaScript InteliSense
https://connect.microsoft.com/VisualStudio/feedback/details/1288784/javascript-and-css-intellisense-not-working

That warning is as follows
![jsextension](https://cloud.githubusercontent.com/assets/8602645/9187569/3b74085e-3fa0-11e5-9294-454f68242b2d.png)

```
  <entry>
    <record>633</record>
    <time>2015/08/10 23:46:44.391</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>End package load [JavaScriptWebExtensionsPackage]</description>
    <guid>{30DB8F9B-EC9F-44D6-B377-83C7C27A1A8B}</guid>
    <hr>80131500</hr>
    <errorinfo>Expected 1 export(s) with contract name "Microsoft.VisualStudio.JavaScript.Web.Extensions.ReferenceAutoSync.IReferencesFilePathProvider" but found 0 after applying applicable constraints.</errorinfo>
  </entry>
```

**Comment by developer1998** [comment]
Got it resolved it as well, 
closing Visual Studio,
deleting
C:\Users\MyUserName\AppData\Local\Microsoft\VisualStudio\14.0\ComponentModelCache

before that I've installed 
x:\packages\JavaScript_LanguageService\JavaScript_LanguageService.msi but I don't think that mattered

thank you
