### ISSUE TITLE
Hello http+json->object->load[method]-call[method+object]->stringify[object]->goodbye json->http

### ISSUE THREAD

**Issue by govpack** [aspnet/Home#818]
hi, 
how's it all going?
i was wondering how the following can be done using asp .NET 5?
1. Hello http
2. Hello json
3. Hello dynamic object (are inferred classes possible from json? or do i need to provide a generic one?)
4. Hello dynamically loaded method -- retrieved from memory||disc||dll||cs
5. asyncMethod(object) --> result
6. ReturnViaHttp(JSON.stringify(result)) // goodbye json

any links/docs/samples that could 
help me implement this would be great

thanks

i don't know or particularly like python, but i'm working thru the various languages, and doing the same task (as above) it took me half a day to write the following in python, and in powershell ~ https://github.com/aspnet/Home/issues/770 and vert.x https://github.com/aspnet/Home/issues/787 these three posts are all the same issue just stated in different ways
# http+json->object->load[method]-call[method+object]->stringify[object]->goodbye json->http

``` python
import json
import urllib
import cgi
import time
from os import curdir
from os.path import join as pjoin
from importlib import import_module
from http.server import BaseHTTPRequestHandler, HTTPServer
import imp
import urllib.request
import sys
hd=__file__.replace("2/1/Ax/250/run.py","")

NUT={}


def getf(rx):
    if rx in NUT.keys():return NUT[rx]
    mod = imp.load_source('bar',hd+'2/yy/Ax/'+(rx[1:])+'/y.py')
    NUT[rx]=mod.task
    return NUT[rx]

def next(o):
    rn=o.get('rn',-1)
    rn+=1
    o['rn']=rn
    if rn>0:o['e']=o.get('rv','')
    print('####'+str(rn))
    if type(o.get('rx')) is not list: return o
    RX=o.get('rx')
    if rn>=len(RX):return o
    try:rx=RX[rn]
    except Exception:return o


    if rx:
        if rx[0]!='y':return o

        f=getf(rx)
        f(o)
        return next(o)
    return o




class web1(BaseHTTPRequestHandler):
    def do_GET(self):
            self.request.sendall((json.dumps({'path':self.path,'d':int(time.time()*1000),'a':1,'b':2,'c':[1,2,3]}).encode("utf-8")))
    def do_POST(self):
        try:
            if 'content-length' in self.headers:
                length= int(self.headers['content-length'])
                data = self.rfile.read(length).decode("utf-8")
                o2 = json.loads(data)
                rc=o2.get('rc',0)
                if rc:
                    self.request.sendall(json.dumps(o2).encode("utf-8"));
                    pass
                rx=o2.get('rx',0)
                if rx:
                    next(o2)
                    self.request.sendall(json.dumps(o2).encode("utf-8"));
                    pass
            else:
                print("No data")
                self.send_response(200)
                self.send_header("Content-Type", "text/json; charset=UTF-8")
                self.end_headers();
                self.wfile.write("No data");
        except Exception as excp:
            print(excp)
            self.send_response(200)
            self.send_header("Content-Type", "text/json; charset=UTF-8")
            self.end_headers();
            self.wfile.write(str(excp));



http = HTTPServer(('localhost',1425), web1)
print('Python listening on http://127.0.0.1:1425/ \n'+sys.version)
http.serve_forever()
```

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.

**Comment by davidalpert** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  spinthemoose@gmail.com
    Domain spinthemoose.com has exceeded the max emails per hour (235/200 (117%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o10.sgmail.github.com ([167.89.101.201]:28561)
	by cp1164.blacksun.ca with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89_1)
	(envelope-from <bounces+848413-6f87-david=spinthemoose.com@sgmail.github.com>)
	id 1eVkHv-0001Q5-V7
	for david@spinthemoose.com; Sun, 31 Dec 2017 14:32:56 -0600
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=1RUU43qW1UnajpBUIRQfhGDyvPI=; b=mLwp6aTD+wjge/RL
	448fXr0IG8IUbJx5Ajc9qj3MlHM4DPXr8lRmhQRh7WecVpDi3NYSxY/COmNg7DtP
	hooC3g5tR0PrI835vUUdnDn80UIKt48O3c6xe4d6mROg5s+tndaeRwhN6KUhjpF+
	L5PeXdFvrazD7nwuHRJ/0qEQj8c=
Received: by filter0349p1las1.sendgrid.net with SMTP id filter0349p1las1-17898-5A494962-25
        2017-12-31 20:32:34.597679505 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0013p1iad2.sendgrid.net (SG) with ESMTP id Vusix2orSoywfmXgmE4Daw
	for <david@spinthemoose.com>; Sun, 31 Dec 2017 20:32:34.609 +0000 (UTC)
Date: Sun, 31 Dec 2017 20:32:34 +0000 (UTC)

**Comment by davidalpert** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  spinthemoose@gmail.com
    Domain spinthemoose.com has exceeded the max emails per hour (234/200 (117%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o5.sgmail.github.com ([192.254.113.10]:12598)
	by cp1164.blacksun.ca with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89_1)
	(envelope-from <bounces+848413-6f87-david=spinthemoose.com@sgmail.github.com>)
	id 1eVkHv-0001Q3-E9
	for david@spinthemoose.com; Sun, 31 Dec 2017 14:32:55 -0600
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=cWdkoBKQIH03BtBOW4I7Z2rB/9E=; b=jSJcdAP8QfsHAtAh
	tkR+sROgBrjwv4CK/PowNM+K4pJIcG99Brtpt3MhLDbfGohElGs+zvl6R9LSqfN0
	FFjo3ikR8yus4JZNfTRjSBHuuN7btTL2PRW/MZtr1CgCsYM7OWllVGSW2DqNDNaX
	Gdgbl7xdikMjbi4qKBgvcHbchA8=
Received: by filter0105p1las1.sendgrid.net with SMTP id filter0105p1las1-22905-5A494961-18
        2017-12-31 20:32:33.769272198 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0015p1iad2.sendgrid.net (SG) with ESMTP id AgtDbn3qRcCNmNqO-4GjaA
	for <david@spinthemoose.com>; Sun, 31 Dec 2017 20:32:33.677 +0000 (UTC)
Date: Sun, 31 Dec 2017 20:32:33 +0000 (UTC)
