### ISSUE TITLE
Where is HttpContext.Server.HtmlEncode

### ISSUE THREAD

**Issue by PrimeObjects** [aspnet/Home#820]
How can I do HtmlEncode now in ASP.NET 5?

Thank you
Gary

**Comment by Eilon** [comment]
There's an HTML encoder that you can acquire through DI.

However, depending on where you are in the system, there are often easier ways to get to it. From where do you want to do HTML encoding? An MVC controller? Middleware? A POCO class?

**Comment by PrimeObjects** [comment]
Eilon,

Thank you for the reply.
I'm doing it in controller for now. please let me know how to do the DI (e.g what should I do in startup.cs and what should I pass in constructor).

****
May I have a suggestion here? Could you guys provide a table to show how to do some poplar functions between ASP.NET 4 and 5. It will lower the learning curse and improve the adoption of ASP.NET 5.

For example,

HTMLEncoding
ASP.NET 4: HttpContext.Server.
ASP.NET 5: DI, how to ...

CultureInfo
ASP.NET 4: ....
ASP.NET 5: not supported yet (?)  Any workaround?

Cache:
ASP.NET 4: HttpContext.Cache
ASP.NET 5: DI, how to ...

Thanks lot
Gary

**Comment by holajan** [comment]
There is Microsoft.Framework.WebEncoders.HtmlEncoder.Default.HtmlEncode(). But where is HtmlDecode?

**Comment by Eilon** [comment]
@blowdart thoughts on having matching encode/decode APIs for all the encoder stuff? This is all in the BCL now, but we can provide input (and perhaps implementations, if desired).

There are currently HTML, JavaScript, and URL encoders here: https://github.com/dotnet/corefx/tree/master/src/System.Text.Encodings.Web/src/System/Text/Encodings/Web. But no decoders.

**Comment by blowdart** [comment]
We is core duplicating work we have already done? (https://github.com/aspnet/HttpAbstractions/tree/dev/src/Microsoft.Extensions.WebEncoders.Core)

There needs to be a sole implementation, and ours, we generate from the specs, so it's up to date.

(but yea, there should be decodes too).

**Comment by Eilon** [comment]
@blowdart we're removing ours and will call into the ones in CoreFx (we moved the code there).

Do you want to log a bug for CoreFx on decoders with any relevant info?

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.

**Comment by davidalpert** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  spinthemoose@gmail.com
    Domain spinthemoose.com has exceeded the max emails per hour (233/200 (116%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o3.sgmail.github.com ([192.254.112.98]:1674)
	by cp1164.blacksun.ca with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89_1)
	(envelope-from <bounces+848413-6f87-david=spinthemoose.com@sgmail.github.com>)
	id 1eVkHp-0001Ob-GQ
	for david@spinthemoose.com; Sun, 31 Dec 2017 14:32:49 -0600
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=6ZK68B9CENuA146XFeCunUWbSQg=; b=XrO14GHYoNwdpsU3
	N9y8ku+UBUcD74xO6lrkJjuBRQ40Jb8uAN0nxEd3UMjjj05YfEtyBWgsHV0Lv5mE
	trNqoB6jl63tjvSWSNwyVQ+hPmSz9Ahw5dwL+ZwFDeb+APDfda6f6Gnxhes6AfIN
	OBobGKupnANCA/ZXz8+A9yGDR2c=
Received: by filter0628p1mdw1.sendgrid.net with SMTP id filter0628p1mdw1-4808-5A49495B-F
        2017-12-31 20:32:27.868918835 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0010p1iad1.sendgrid.net (SG) with ESMTP id 5MUlApySSNqpXLG52m0d8Q
	for <david@spinthemoose.com>; Sun, 31 Dec 2017 20:32:27.865 +0000 (UTC)
Date: Sun, 31 Dec 2017 20:32:27 +0000 (UTC)

**Comment by davidalpert** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  spinthemoose@gmail.com
    Domain spinthemoose.com has exceeded the max emails per hour (232/200 (115%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext7.iad.github.net ([192.30.252.198]:53810 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by cp1164.blacksun.ca with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.89_1)
	(envelope-from <noreply@github.com>)
	id 1eVkHn-0001Oa-WC
	for david@spinthemoose.com; Sun, 31 Dec 2017 14:32:48 -0600
Date: Sun, 31 Dec 2017 12:32:27 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1514752347;
	bh=oMHe7G1NxbM/c+seFtwF8eC7ZTknQgboTcWMpR+HMiI=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=OFNZc1xfTqxJ4eVOVdzNT+lTx+gP7QPEcclqytyZ0k2ivkRMWQLTL4ezzO7dSJdBH
	 +dFJH+bn4a5ZQe3bcnct0l6blLY5uKqN/azHbi7p7wtx6FKjzUYCCoAIp1tYyk4DHN
	 6ilHYx+/DrBbBbCR3GY5rPEJnjvqeJCLIVYpLCaE=
