### ISSUE TITLE
Where is Session.SessionID? Thank you.

### ISSUE THREAD

**Issue by PrimeObjects** [aspnet/Home#821]

**Comment by Eilon** [comment]
I don't think there's such a thing anymore. Is there a reason you need it? Ultimately it's just an opaque number that doesn't really mean anything. With the new session state you could certainly just store a `Guid` in session state and have that be the id.

**Comment by PrimeObjects** [comment]
We are kind of using it for single sign on. I will see what I can do to avoid using it. 

I will close this issue for now.
