### ISSUE TITLE
How to do Response.BinaryWrite in ASP.NET 5, Thank you.

### ISSUE THREAD

**Issue by PrimeObjects** [aspnet/Home#822]

**Comment by kant2002** [comment]
Is something like this will work for you?
https://github.com/aspnet/KestrelHttpServer/blob/dev/samples/LargeResponseApp/Startup.cs

**Comment by PrimeObjects** [comment]
not sure it will work, I am talking about content in zip, pdf, jpeg format. from dynamically generated binary content byte[].

**Comment by Eilon** [comment]
`WriteAsync` takes a `byte[]`.

**Comment by PrimeObjects** [comment]
does it? how come vs2015 only show string as the first parameter? I will double check, sorry about this issue.

**Comment by davidfowl** [comment]
Response.Body is a Stream, Streams have Write(byte[], offset, length)

**Comment by PrimeObjects** [comment]
Body is not like a action, i did not even look at it. so if i gave stream to Body, i do not need to call any function? it will automatically write?

Thank you,
Gary

**Comment by davidfowl** [comment]
I'm not sure what you mean.

```
context.Response.Body.Write(buffer, 0, buffer.Length);
```

**Comment by PrimeObjects** [comment]
lol. sorry i am not in front of computer, i am in bed. i thought it is something like Body = steam. it is all good after seeing ur code. Are u guys in Redmond? it is late night now. ty for the hardwork.

Good night.
Gary

**Comment by davidfowl** [comment]
Sleep when you're dead :smile:
