### ISSUE TITLE
message when compilation breaks for mismatch between packages and runtime

### ISSUE THREAD

**Issue by lucamorelli** [aspnet/Home#823]
Hi,
  It's a know fact that during compilation if there is a big mismatch between project packages and tools/runtime build fails sending tons of errors, but looking around I see that a lot of people is not aware of it.
  I think that is not to be sure that is  the reason of a build fail, but I think that when you have errors as "cannot find system.object" or system.string there are not so many other possible reasons.
  Why don't add a simple message suggesting check this giving an eventual url to download the latest version? just to avoid if possible  that this kind of issues are opened over and over

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.

**Comment by davidalpert** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  spinthemoose@gmail.com
    Domain spinthemoose.com has exceeded the max emails per hour (231/200 (115%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext7.iad.github.net ([192.30.252.198]:51874 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by cp1164.blacksun.ca with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.89_1)
	(envelope-from <noreply@github.com>)
	id 1eVkHi-0001Na-3Z
	for david@spinthemoose.com; Sun, 31 Dec 2017 14:32:42 -0600
Date: Sun, 31 Dec 2017 12:32:21 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1514752341;
	bh=wqk2pmTHpLYUytM5eRJlkprRhVFNmtHWibZNFmJUhZI=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=JKTpFJ1aYk7vrF3LAqRc6mZq7QGGFVmcsar+CsKSMdUR2eW+06BOTiMMh2E4rpaw7
	 FfuO9w8WLWy8+Gvr29zmz+9bWOdKp8+T8W5zP7kEzpxkDpuTW6XIByypCRLfouADWH
	 nFFU9LFro0jWqZO9QHHmJ/cEHaGaykga3nZ9VyC4=

**Comment by davidalpert** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  spinthemoose@gmail.com
    Domain spinthemoose.com has exceeded the max emails per hour (230/200 (114%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext6.iad.github.net ([192.30.252.197]:39920 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by cp1164.blacksun.ca with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.89_1)
	(envelope-from <noreply@github.com>)
	id 1eVkHh-0001NU-Vf
	for david@spinthemoose.com; Sun, 31 Dec 2017 14:32:42 -0600
Date: Sun, 31 Dec 2017 12:32:21 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1514752341;
	bh=jDQsj91j+FxP3aoRUzQliEtIfXaxg6kdvWyRoSHdrAg=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=Kd0HKfRcJVIc0P4Ce4D5dR5kXM2qaJU7cKReo+R68h5Kyi8cYrtNdtbmoduTLz7k0
	 8F8cJI/EDR6Ied5/SIUteYiCplX5/tWigsfYtbQa8NMjkj5C4J4YC/of5QF3CHYf4/
	 Q5QgCaItWzhaL0pYo2gLUaeh3mpUITOgcG0JyOF0=
