### ISSUE TITLE
Visual studio 2015 locking onto beta 5 when pointing at beta 7

### ISSUE THREAD

**Issue by stephenstroud** [aspnet/Home#828]
i'm having a version issue with floating point dependencies, I'm using the nightly feeds, i've downloaded and installed dnx-clr-win-x86.1.0.0-beta7-12340 however visual studio seems to download beta 5 runtime and put a lock on it. The Global is using { "sources": [ "src" ] } and project properties point to 7. I used { "sources": [ "src" ] } as it couldn't detect that I had the beta 7 package installed. Any ideas how I can break the lock on 5?  Would be good to stop the downloads of beta 5 coming too.

**Comment by davidfowl** [comment]
Did you update the web tools extensions?  http://www.microsoft.com/en-us/download/details.aspx?id=48222

Changing `global.json` after installing beta6 will update the dnx in realtime. In VS RTM it requires a solution close and open.
