### ISSUE TITLE
Hiding folders from the solution explorer

### ISSUE THREAD

**Issue by JeroenVinke** [aspnet/Home#829]
I am using the JSPM package manager, which creates a `jspm_packages` containing many files. This is slowing down visual studio 2015 RTM a lot. I am using the vNext empty project template.

I haven't found a way to hide a folder from the solution explorer, even though node_modules is hidden by default. Also see this stackoverflow answer: http://stackoverflow.com/a/31036858/3922366

How can we hide folders? If it's not possible at the moment, when will this be possible?

**Comment by KarlDirck** [comment]
I have the same problem.  In addition to the jspm_packages, I have a build output directory that VS attempts to add to the project and source control (TFS) which cause VS to stop responding during my build, I assuming it is watching file changes, which is not necessary or wanted.  Please provide a means to "exclude" a directory from the file watch and/or the project.json, and/or source control  which may be an issue with TFS, but it seems that TFS should ignore all directories "excluded" from the project.

**Comment by cmichaelgraham** [comment]
:+1:

**Comment by ghurlman** [comment]
:+1:

This is an issue for [EmberCLI](http://www.ember-cli.com/) projects as well, the 'tmp' folder in the project root gets thousands of files that are churned with every build, and safely ignored... when the VS solution explorer tries to load these files, it either freezes for minutes at a time or crashes completely.

Visual Studio Code has this feature already... it seems backwards that the uplevel version, VS 2015, wouldn't have a feature to match.

**Comment by Eilon** [comment]
@sayedihashimi @barrytang thoughts?

**Comment by Souldrinker** [comment]
:+1:

**Comment by JeroenVinke** [comment]
can we get an update? is there perhaps a workaround we can use?

**Comment by Eilon** [comment]
@sayedihashimi @barrytang ping.

**Comment by sayedihashimi** [comment]
Sorry for the delay. We added a feature to hide files in beta8 which we just released. More info at http://blogs.msdn.com/b/webdev/archive/2015/10/15/announcing-availability-of-asp-net-5-beta8.aspx. Can you try it and let me know if it resolves the issue for you?

**Comment by Eilon** [comment]
Closing for now. Please re-open if there's still an issue, or log a new issue in the https://github.com/aspnet/Tooling/issues/ issue tracker. Thanks!

**Comment by JeroenVinke** [comment]
Thanks! I will try this out today and will open an issue if I encounter any problems.

**Comment by Serjster** [comment]
You can find files but not folders? Like, I want to hide the entire node_modules from solution explorer and cant?

**Comment by Eilon** [comment]
@Serjster I would recommend filing a new issue in https://github.com/aspnet/Tooling/issues/
