### ISSUE TITLE
Rearrange the debian/linux instructions, better guidance

### ISSUE THREAD

**Issue by atrauzzi** [aspnet/Home#832]
Looking at the current [debian/linux instructions](https://github.com/aspnet/Home/blob/dev/GettingStartedDeb.md), I still get the sense that people will get a second-rate outcome compared to OSX and Windows.

Some of this might be because the instructions start with the suggestion to use Docker, which adds a pile of complexity to just try things out.  Another aspect is that people are required to build libuv.  Also, rather than starting their own projects, people are encouraged to clone the home repository to see some demos.

What might be nicer is:
- Show the flow to install to the local system
- Add sources to NuGet.config automatically, not manually
- Expand on what to do with DNVM once it's installed
- Show how to initialize a new, empty MVC project command-line
- Encourage people to install Visual Studio Code for extra convenience
- Link to an exact starting point in documentation (once available?) for people to continue their learning path

We should try to not get stuck in the flow of thinking that Linux == Docker and move all those instructions to a different page.
Unless Visual Studio Code is planning on integrating support for running all the tooling through a container and managing the filesystem mounts.  Most people are going to need working copies of everything, local on their path.

**Comment by tlk** [comment]
Sounds very reasonable to me. From #774 it appears that you can submit suggestions and PR's to https://github.com/aspnet/Docs/ and I guess the instructions in this project are to be replaced eventually.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.

**Comment by davidalpert** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  spinthemoose@gmail.com
    Domain spinthemoose.com has exceeded the max emails per hour (228/200 (113%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext8.iad.github.net ([192.30.252.199]:50206 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by cp1164.blacksun.ca with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.89_1)
	(envelope-from <noreply@github.com>)
	id 1eVkHc-0001Md-Um
	for david@spinthemoose.com; Sun, 31 Dec 2017 14:32:37 -0600
Date: Sun, 31 Dec 2017 12:32:16 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1514752336;
	bh=dWugifOe9TQIOfugjRnEtBpzv/i849cT0tjz+YcyIQU=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=V7UUf2F2sSOLre9hj/8B0PEEGbedt3gOMHOoFfMGQemHJsVAvQweW4eIUSwBw2+Gq
	 xb1OQHM4w5sGsIleRpXSB9hrSOSfalSY0qzRQBzXKDsXBSvTgXhe2ByaIkwLooBBcw
	 3CuN/xYi+QQatx0FLYHdNhy7N94uhmTdEVtuS5LI=

**Comment by davidalpert** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  spinthemoose@gmail.com
    Domain spinthemoose.com has exceeded the max emails per hour (229/200 (114%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o4.sgmail.github.com ([192.254.112.99]:57710)
	by cp1164.blacksun.ca with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89_1)
	(envelope-from <bounces+848413-6f87-david=spinthemoose.com@sgmail.github.com>)
	id 1eVkHd-0001Me-Cf
	for david@spinthemoose.com; Sun, 31 Dec 2017 14:32:37 -0600
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=YrHQbYAWdrXSb76YrSfP+kwrOE0=; b=NdOucZLzRk17z8th
	4XbBfozU8hYghePPtPCqTpsJwL5cQEG7CHzFZIs0JMXR/PTWbLD6emAWSmxInT2D
	DvVixXyvawO++P55f/xRMVZRtdgSB/I0qcYqC0SSMAl4ksZZAjoIN9d/azmJAJ0j
	D38c/AqOQTi514WgqpAdpJiY+h8=
Received: by filter0242p1las1.sendgrid.net with SMTP id filter0242p1las1-24548-5A494950-12
        2017-12-31 20:32:16.338483014 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0009p1iad1.sendgrid.net (SG) with ESMTP id vZlEkqgmSPC6uRejjNbm4g
	for <david@spinthemoose.com>; Sun, 31 Dec 2017 20:32:16.162 +0000 (UTC)
Date: Sun, 31 Dec 2017 20:32:16 +0000 (UTC)
