### ISSUE TITLE
DNX: dealing with non-NuGet repositories?

### ISSUE THREAD

**Issue by ghost** [aspnet/Home#834]
Hello.

While CoreCLR and DNX now is not just for aspnet - I have question about high-level design or concept for this parts (I.e. DNX), which are touched to nuget.

In short form it is can sounds as - it is possible to replace nuget with some other package manager? I'm understand that short answer is no (without improve something). But... for technologies it is not looks as answer.

Nuget initially do lot of implications, which are not now fit. Nuget become popular and it is used now even for deployment, but during development - it is used for binary distributions of native libraries. Lack of pivot points, all-in-one package, and complete ignorance of social aspects (different authors versioning models, fork support, correct dealing with multiple sources). Try maintain fork, package it, and publish? And it is still should be distinguish, but it is incorrect to give other id. All-in-one targets gives another issues. Etc...

Technically now .dnx/packages folder did not ready to get deal with anything other. Version references in projects probably too.

Even while almost everything addressed to nuget, this problems /probably/ will be solved sometime, issue adressed to DNX and it's nuget relation.

Something similar happens with project.json. It is great, but oversimplied and did not work for simple cases. Default compileBuiltins it is something strange. Lot of peoples always explicitly define files. Possible? Yes. After looking in source, and reset all builtins in project.json. I mean that it is common case. Easier specify standard patterns, but not reset some implict variables (who know what else will be added?). So while it is used as build system - it is easy to replace, but while them can be 'runned' - it is no more clear. Output folder, BTW, configures partially, what did not allow get desired final layout. And default 'artifacts' name is good, but 'out' and 'build' is very common too.

So generally, to be universal tool:
1. Will be nice to have ability to support parallel package managers. Better if manager installed via nuget itself, I.e. not part of DNX distribution.
2. Way to switch to other build system, but keep common flavor (everything is package, ability to run directories, source running).

Any chances in long-term to achieve this? Or high-level vision is locked to described things, and no have sense even think about?

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.

**Comment by davidalpert** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  spinthemoose@gmail.com
    Domain spinthemoose.com has exceeded the max emails per hour (224/200 (112%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext1.iad.github.net ([192.30.252.192]:46236 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by cp1164.blacksun.ca with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.89_1)
	(envelope-from <noreply@github.com>)
	id 1eVkHQ-0001LC-NF
	for david@spinthemoose.com; Sun, 31 Dec 2017 14:32:24 -0600
Date: Sun, 31 Dec 2017 12:32:04 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1514752324;
	bh=CPoGVnORcdcTnNMJw4aT1ulFtmJHGZFkj8AokMebcZo=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=Wm6sU6On1bDnc2UF6QVnLNEnNCu1+lCHSj4/npeAaa24482lxhwKDxdvXRuCtbiVh
	 rmuJRd3siXOEc9Wf5EzRXCkDn6n53O3lqnxMV9dRHaEFDM4q7E9t453XKRqPHt+4PQ
	 a6n2Uywc2SFK3edk5nq4u/2spNqX7Y2myjLNYYCI=

**Comment by davidalpert** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  spinthemoose@gmail.com
    Domain spinthemoose.com has exceeded the max emails per hour (225/200 (112%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o1.sgmail.github.com ([192.254.114.176]:6170)
	by cp1164.blacksun.ca with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89_1)
	(envelope-from <bounces+848413-6f87-david=spinthemoose.com@sgmail.github.com>)
	id 1eVkHR-0001LD-4C
	for david@spinthemoose.com; Sun, 31 Dec 2017 14:32:25 -0600
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=vkDon7uux5WorgfvDeaB/U9F7po=; b=voXj5JQ5Ney/N2to
	mFAAjHhOmMFSH8tA7+nhQtvzNyErS93SOR5alxtecZy3dtt4uoZQ769UKcq1zGa/
	gUM9h2knGV775xlXn+QXQ7xpTelRmyBxB+VRldEf82F8fZ+bqIDXTREw/8HxTcIr
	0IkxAB/YzewIXurHYzNDoMN9RTI=
Received: by filter0468p1mdw1.sendgrid.net with SMTP id filter0468p1mdw1-5127-5A494944-5
        2017-12-31 20:32:04.11462038 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0024p1iad2.sendgrid.net (SG) with ESMTP id EyNxcPb5TFSdVDOBYexhiQ
	for <david@spinthemoose.com>; Sun, 31 Dec 2017 20:32:04.174 +0000 (UTC)
Date: Sun, 31 Dec 2017 20:32:04 +0000 (UTC)
