### ISSUE TITLE
Logging test fails if console background is not black.

### ISSUE THREAD

**Issue by BillKrat** [aspnet/Home#835]
Microsoft.Framework.Logging.Test fails if default console background is not black.  I was thrown for a loop because I discovered it in git shell but it passed when running from Visual Studio.

1. Open console 
2. Right click on caption bar and select properties
3. Select colors tab 
4. Select dark blue (second color next to black)
5. Execute "dnx . test" 

![dnxtest](https://cloud.githubusercontent.com/assets/10552946/9288811/4ee025ac-4320-11e5-8122-e3bda41377fa.png)

**Comment by BrennanConroy** [comment]
Could you log this in the Logging repo

**Comment by Tratcher** [comment]
This issue was moved to aspnet/Logging#235
