### ISSUE TITLE
Publishing two projects to same directory?

### ISSUE THREAD

**Issue by Daniel15** [aspnet/Home#836]
I have one ASP.NET 5 website and one console application, and am publishing both of them using `dnu publish`. This results in two directories with two different `packages` subdirectories, which feels like a waste of space as the two projects reuse a lot of the same NuGet packages. Is it possible to publish both into the same directory and have them reuse the same `packages` directory? I imagine a structure like this:

```
|- packages
|- Site
 \
  |- kestrel.cmd
  |- approot
  |- wwwroot
|- ConsoleApp
 \
  |- ConsoleApp.cmd
  |- approot
```

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.

**Comment by davidalpert** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  spinthemoose@gmail.com
    Domain spinthemoose.com has exceeded the max emails per hour (222/200 (111%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o6.sgmail.github.com ([192.254.113.101]:45756)
	by cp1164.blacksun.ca with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89_1)
	(envelope-from <bounces+848413-6f87-david=spinthemoose.com@sgmail.github.com>)
	id 1eVkHK-0001KQ-4R
	for david@spinthemoose.com; Sun, 31 Dec 2017 14:32:18 -0600
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=VDuNhNZoINf1UT2nHp2yEVTw55s=; b=I/ptm2Tz/GOrztTJ
	CcTEqs8HAkAkIPkCzux1N6T2QN1mTtqInVa2Qv6KC447AwZZmEO9YzXcrnYdGBKs
	1ANiHexa9dLZbgG5Cp70VTyiN7hiDTKA6mMgyRLF5mzrZzw5tPz80/VBPQi/ioX3
	bbMVFnyFscuE16kRSnKePLR6HZo=
Received: by filter1256p1mdw1.sendgrid.net with SMTP id filter1256p1mdw1-18288-5A49493D-15
        2017-12-31 20:31:57.649272405 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0006p1iad2.sendgrid.net (SG) with ESMTP id eFQguMjHSNCE0Y8vpWmu2g
	for <david@spinthemoose.com>; Sun, 31 Dec 2017 20:31:57.753 +0000 (UTC)
Date: Sun, 31 Dec 2017 20:31:57 +0000 (UTC)

**Comment by davidalpert** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  spinthemoose@gmail.com
    Domain spinthemoose.com has exceeded the max emails per hour (223/200 (111%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o11.sgmail.github.com ([167.89.101.202]:23977)
	by cp1164.blacksun.ca with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89_1)
	(envelope-from <bounces+848413-6f87-david=spinthemoose.com@sgmail.github.com>)
	id 1eVkHL-0001KT-09
	for david@spinthemoose.com; Sun, 31 Dec 2017 14:32:19 -0600
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=g8yz/4KtpsSJmbbaPYmD2fENTvA=; b=RlmjszaYdoY4rDQP
	P55E7g2IjbzkbNnjylgsJe5bvCMQ7FwGgL/myQH57/P6Tn/ixc2cTssx78YiLs40
	x2x35ErHFk6VNsdjkyCC5XHHGe2K3nuMuJBGNb/2y0Dh4HZJJ+sCdMhwsHH7Jgoz
	VbHtSnuL790G7l1z7rxMBVaQXwc=
Received: by filter0627p1mdw1.sendgrid.net with SMTP id filter0627p1mdw1-5620-5A49493D-1E
        2017-12-31 20:31:57.994921499 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0011p1iad2.sendgrid.net (SG) with ESMTP id PS9T69ZARC6V6tS9JZf4dA
	for <david@spinthemoose.com>; Sun, 31 Dec 2017 20:31:58.059 +0000 (UTC)
Date: Sun, 31 Dec 2017 20:31:58 +0000 (UTC)
