### ISSUE TITLE
HostingEnvironment.MapPath doesn't work correctly

### ISSUE THREAD

**Issue by axefrog** [aspnet/Home#838]
I'm observing strange behaviour from the HostingEnvironment argument in the Configure method of my Startup class.

``` cs
public void Configure(IApplicationBuilder app, IHostingEnvironment env)
{
    app.Run(async (context) =>
    {
        var str = "Testing\r\n";
        str += $"env.MapPath(\"~{context.Request.Path.ToString()}\") ===> {env.MapPath("~" + context.Request.Path.ToString())}\r\n";
        str += $"env.MapPath(\"{context.Request.Path.ToString()}\") ===> {env.MapPath(context.Request.Path.ToString())}";
        await context.Response.WriteAsync(str);
    });
}
```

The output I'm getting for a request to the root of the website  is as follows:
1. `env.MapPath("~/a/b/c");` becomes: `"D:\Dropbox\Work\Projects\...etc....\wwwroot\~\a\b\c"`
2. `env.MapPath("/a/b/c");` becomes: `"\a\b\c"`

In other words, if I don't include a tilde, the path is not "mapped" at all; it simply twiddles the slash direction. If I _do_ include a tilde, the full mapping occurs, but the tilde is not dropped.

For now, the workaround is to just use `env.WebRootPath`.

**Comment by rubenprins** [comment]
What you're seeing is, I've been told, intentional: `IHostingEnvironment.MapPath` is not, and will not be a replacement for `Server.MapPath`. It merely has an unfortunate name leading existing developers to think it is.

I've had a rather heated discussion about this in aspnet/Hosting/issues/222, but the short of it is: `IHostingEnvironment.MapPath` basically does a `Path.Combine(env.WebRootPath, yourPath)`, and that's it. It has no notion of `~` paths, true (mapped) virtual paths or paths outside of your application path if you're running child applications under IIS.

What you need call is `env.MapPath("a/b/c")`, so no leading `/` or `~/`. Which doesn't do anything you didn't already do yourself by appending your path to `env.WebRootPath`; it only takes care of the OS-specific directory separator translation.

**Comment by axefrog** [comment]
Hmm, sounds redundant. Why have this method at all instead of just using `Path.Combine(env.WebRootPath, yourPath)`?

**Comment by stijnherreman** [comment]
@axefrog For convenience, I assume.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.

**Comment by davidalpert** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  spinthemoose@gmail.com
    Domain spinthemoose.com has exceeded the max emails per hour (221/200 (110%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext4.iad.github.net ([192.30.252.195]:42418 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by cp1164.blacksun.ca with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.89_1)
	(envelope-from <noreply@github.com>)
	id 1eVkHF-0001Jv-2M
	for david@spinthemoose.com; Sun, 31 Dec 2017 14:32:13 -0600
Date: Sun, 31 Dec 2017 12:31:52 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1514752312;
	bh=3KWwZyJgCHRzrMM0GbsPPa8d6aQaYdEdVFbUBkL/Hog=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=X9dQQAKt8c0lYwHpFq2vPNXfzf/VDPBCkoIANdSyDv40rs8/jCmTGtjSZifi+RlDP
	 Df2xz5oA18pUIGvfhxf7cVL0Aqf/xOHjOk3lhHjZlnLDznoEO48lAu6yFZwDhIyH5N
	 yyOEczWO2bKQ5BuB1lykrUtTqqDFcnFbtCM0jYVc=

**Comment by davidalpert** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  spinthemoose@gmail.com
    Domain spinthemoose.com has exceeded the max emails per hour (220/200 (110%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext2.iad.github.net ([192.30.252.193]:59620 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by cp1164.blacksun.ca with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.89_1)
	(envelope-from <noreply@github.com>)
	id 1eVkHD-0001Jt-Sh
	for david@spinthemoose.com; Sun, 31 Dec 2017 14:32:12 -0600
Date: Sun, 31 Dec 2017 12:31:51 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1514752311;
	bh=tKWGQ576W5SuuZX8/WII5MUQMjvZiuFiho/gZMLEZa0=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=uzfw7H3Y/zaVhFT6Ts0qW1gZBj0uAAaUsDARIQ1M/WT5zm4AqMGFqtRu8TsqR9qtP
	 WsFzh7i/4/wVrtzF8GNy7fCok+3Fz8Iu7Q8yPpZPDXDeuyd55NHBDXEJAv7dpM3KDQ
	 Bw1RPyySWnwGZHuJ9xjugav4j+C1i7MJ9aNgdG6A=
