### ISSUE TITLE
Publishing Problems

### ISSUE THREAD

**Issue by developer1998** [aspnet/Home#839]
There are two publishing issues that I've encountered:
1) The runtime does not get updated to the one of the project, unless I delete the runtimes directory in the location where it gets published

2) I have a mapped driver to another machine, and when I am publishing to that drive, I don't get any errors, and it simply does not get copied

**Comment by prakashkaruppiah** [comment]
the 'prepublish' script  failed with status  code 8 .  how can i solve this problem?

**Comment by developer1998** [comment]
I'm glad to report that both issue are resolved. I've downloaded the beta7...
1) Run-times now get updated when I publish.
2) To publish to another computer you need to add it to Server Explorer, you will be prompted to enter user name and password. If that does not work map that computer in your Windows Explorer and enter credentials. Cheers!!!
