### ISSUE TITLE
Tooling building inside visual studio with .NET 4.0 assemblies

### ISSUE THREAD

**Issue by Mpdreamz** [aspnet/Home#84]
Im trying out the VS 2014 CTP and noticed something odd. 

I have a solution with 2 projects 

* Project 1 sets up a static client configuration object that takes a `Uri` as constructor argument.
* Project 2 references Project 1 and instantiates a client using the static configuration from Project 1. 

`k run` `k build` all still work.

If however I try to build from visual studio i am seeing this:

Error	1	The type 'System.Uri' is defined in an assembly that is not referenced. You must add a reference to assembly 'System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.	<redacted>.cs	12	70	<project 1>
Error	2	The command ""C:\Users\<redacted>\.kre\packages\kre-svr50-x86.0.1-alpha-build-0535\bin\klr.exe" "C:\Users\<redacted>\.kre\packages\kre-svr50-x86.0.1-alpha-build-0535\bin\lib\Microsoft.Framework.Project\Microsoft.Framework.Project.dll" build  "<path to project1>"" exited with code -1.	C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\AspNet\Microsoft.Web.AspNet.targets	124	5	<project 1>

Both projects are configured to use `.NET Framework 4` 

I'm running on the Azure VM that was provided for the VS2014 CTP and upgraded to the latest runtime using `kvm upgrade`

Debugging from within visual studio also still works correctly.

**Comment by davidfowl** [comment]
@Mpdreamz any updates?

**Comment by Mpdreamz** [comment]
No this was more then likely an error on my part.
