### ISSUE TITLE
System-wide DNVM

### ISSUE THREAD

**Issue by Daniel15** [aspnet/Home#840]
On Linux, is it possible to install DNVM and DNX system-wide rather than installing it in the user's root directory? I run most of my sites under a different user (www-data) and it's annoying having to ensure the DNX version is installed for both my account and the www-data account. Will there be regular Linux packages coming in the future?

**Comment by wholroyd** [comment]
This is covered in https://github.com/aspnet/Home/issues/437 and (more recently in the DNVM repo) https://github.com/aspnet/dnvm/issues/417

**Comment by Daniel15** [comment]
Oh cool, I'll close this out then. Thanks @wholroyd
