### ISSUE TITLE
the 'prepublish' script  failed with status  code 8 

### ISSUE THREAD

**Issue by prakashkaruppiah** [aspnet/Home#841]
How can i solve this pbm?

**Comment by shaunluttin** [comment]
I am having the same problem, using Git Deploy to an Azure Web App with ASP.NET 5.

**Comment by prakashkaruppiah** [comment]
Thanks @shaunluttin, I removed prepublish script  from project.json file. Now its working fine.

**Comment by shaunluttin** [comment]
@prakashkaruppiah Good stuff. :)
