### ISSUE TITLE
WSDL?

### ISSUE THREAD

**Issue by leus** [aspnet/Home#842]
I've been looking for a good way to consume WSDL using asp.net 5 (I'm using the dnx451 framework in my project.json file; I'm still not sure what means what there.)

Are there any plans on supporting WSDL in any form?

**Comment by jamesgaunt** [comment]
The tooling isn't there in VS dnx projects yet. But I got this working quite easily in beta-6 using svcutil.exe directly following this guide: http://stackoverflow.com/questions/28413756/asp-net-5-add-wcf-service-reference

**Comment by leus** [comment]
Well, I finally got this working by the not-so-nice method of creating a 4.5 project, add a service reference, and then copying the generated file into my aspnet5 project. Not convenient nor pretty but got the work done.

I see that there is a very official-looking [WCF](https://github.com/dotnet/wcf) project going on. You guys feel free to ignore this as it probably belongs there.

**Comment by weitzhandler** [comment]
@jamesgaunt  @leus 
Will the generated file work in an ASP.NET 5 project under `dnx451` and `dnxcore50`?

**Comment by jamesgaunt** [comment]
@weitzhandler it works fine on dnx451. I didn't try dnxcore50 but it should be easy to check if you can resolve the dependencies.  I found the code generated by svcutil.exe to be bit cleaner with less dependencies than the visual studio service reference generated code.
