### ISSUE TITLE
DNX 4.6 and Azure Web Apps

### ISSUE THREAD

**Issue by djanosik** [aspnet/Home#844]
Hi,

my web application is targeting DNX 4.6 (Beta 6). It runs perfectly on IIS Express, but when I publish to Windows Azure, it crashes. 

![error](https://cloud.githubusercontent.com/assets/858180/9308719/df1f2b68-4505-11e5-8242-c2653cbdcb48.png)

I am not able to find more error details. Can you help?

Url: http://playe.azurewebsites.net/
Repo: https://github.com/djanosik/Playe.it/

Dusan

**Comment by nguyenquyhy** [comment]
I met this problem several times before. Usually I turn on the option "Remove additional files at destination" when publishing, and that solve the problem for me.

**Comment by djanosik** [comment]
Thank you, but I always turn on this option. It will not help this time :/

**Comment by djanosik** [comment]
It was caused by an incorrect connection string. The error message was not very helpful.
