### ISSUE TITLE
Dnx sdk failed to install due to quote in my username

### ISSUE THREAD

**Issue by cveld** [aspnet/Home#845]
When opening a beta6 based new asp.net web project a dialog appears that tells me that the dnx sdk failed to install and I should review the dnvm output.

dnvm reports the following among others:
At line:1 char:158
- ... hread.CurrentUICulture = '';$CmdPathFile='C:\Users\Carl in 't Veld.d ...
-                                                                 ~
  Unexpected token 't' in expression or statement.

So it surely looks like the quote in my username does not get escaped correctly.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.

**Comment by davidalpert** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  spinthemoose@gmail.com
    Domain spinthemoose.com has exceeded the max emails per hour (219/200 (109%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o6.sgmail.github.com ([192.254.113.101]:7333)
	by cp1164.blacksun.ca with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89_1)
	(envelope-from <bounces+848413-6f87-david=spinthemoose.com@sgmail.github.com>)
	id 1eVkH9-0001JD-Sg
	for david@spinthemoose.com; Sun, 31 Dec 2017 14:32:08 -0600
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=9biYWi7HU6PzzvK2xqrHLmZc414=; b=XZOf96bcIsVEPGYk
	8JbLFVqFH7bfzI1uCVJqQPbJuZblR/qfK3CwAdVzIp7B6hLuoOmLgAxzwIYsMrnk
	h6w6dSYcdwXUbZ1dM3a4V7meNjSRiQwyDiPjkNH/r5DlVWzKZfVe6TIEK93FqwPr
	zvbqdg7J31kh1x2a4AdpVB5ivHU=
Received: by filter0501p1las1.sendgrid.net with SMTP id filter0501p1las1-18538-5A494931-C
        2017-12-31 20:31:45.995885175 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0019p1iad2.sendgrid.net (SG) with ESMTP id PzwyHR14QseQuiol7BFVCg
	for <david@spinthemoose.com>; Sun, 31 Dec 2017 20:31:45.972 +0000 (UTC)
Date: Sun, 31 Dec 2017 20:31:46 +0000 (UTC)

**Comment by davidalpert** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  spinthemoose@gmail.com
    Domain spinthemoose.com has exceeded the max emails per hour (218/200 (109%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o8.sgmail.github.com ([167.89.101.199]:8763)
	by cp1164.blacksun.ca with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89_1)
	(envelope-from <bounces+848413-6f87-david=spinthemoose.com@sgmail.github.com>)
	id 1eVkH9-0001JH-PQ
	for david@spinthemoose.com; Sun, 31 Dec 2017 14:32:07 -0600
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=K6BbohgqebiyfpIEicKNxrsP7Qc=; b=Uap0PbrFUSXG9WaD
	scOjA2OJIu+jiLyDyg9rGdwPJtQFViXtBBeFkE1wwABqKyyUCN4uWrdf/agd+7YF
	6r72bbXZRKAqwaCFS6TaQZJPWfh2nq/TwqR3vX6qrHNi/sGHTWGCKhW2eBdYNGZl
	dvZRV9hiLyzZrsD67RbEFQSMa78=
Received: by filter0808p1mdw1.sendgrid.net with SMTP id filter0808p1mdw1-2484-5A494932-F
        2017-12-31 20:31:46.282619529 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0017p1iad2.sendgrid.net (SG) with ESMTP id mV32DnerSHu_LYpBf652hw
	for <david@spinthemoose.com>; Sun, 31 Dec 2017 20:31:46.298 +0000 (UTC)
Date: Sun, 31 Dec 2017 20:31:46 +0000 (UTC)
