### ISSUE TITLE
SQLite Interop Error

### ISSUE THREAD

**Issue by cemremengu** [aspnet/Home#847]
I am doing an MVC6 project with .NET Framework 4.6. The ORM is NHibernate and I am trying to setup SQLite as the test database. I have installed System.Data.SQLite from nuget however I am getting the error

{"Unable to load DLL 'SQLite.Interop.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)"}

Tried also with DNX451 and I am getting the same error. Some sources say  I need to set the copy local property of the sqlite reference to true but there is no way to set it in this new project layout.

**Comment by Serjster** [comment]
I am also getting this error trying to run Hangfire in my MVC 5 DNX 4.6 app.

**Comment by Eilon** [comment]
@divega @rowanmiller

**Comment by divega** [comment]
System.Data.SQLite is not our provider. I am not sure but this could be a known DNX issue. Cc @moozzyk and @anurse in case it rings a bell. 

In the meanwhile @cemremengu what OS are you getting the error on?

**Comment by divega** [comment]
Just noticed @cemremengu posted this originally a long time ago. @Serjster could you provide more details of what are you doing and the error you are getting?

**Comment by Serjster** [comment]
I am trying to use Hangfire in my app with SQLite and it gave me this error in an MVC 6 app with DNX 4.6 chosen (Hangfire is not available yet for 5.0) I did end up getting past this issue by manually copying the SQLite Interop dll from the build folder down to the bin folder with the SQLite Core dll. Not sure what needs to be fixed or configured so that this manual copying would not be required.

**Comment by cemremengu** [comment]
Hello @divega I am using Windows 7. I didnt try recently but seems like the issue is on going. I couldnt find any solution at that time so I switched to sql server express which works fine.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.

**Comment by davidalpert** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  spinthemoose@gmail.com
    Domain spinthemoose.com has exceeded the max emails per hour (217/200 (108%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o4.sgmail.github.com ([192.254.112.99]:2771)
	by cp1164.blacksun.ca with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89_1)
	(envelope-from <bounces+848413-6f87-david=spinthemoose.com@sgmail.github.com>)
	id 1eVkH3-0001Ia-5x
	for david@spinthemoose.com; Sun, 31 Dec 2017 14:32:01 -0600
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=4FXvZLN18NtnkB3W95NkBFuFvgA=; b=dvSf3/tClErbBkIb
	iU/TsJ1GWOgBc7OL275ltAF664iNDgKfw82NXUK7devdjBZ8LHFtNeQuuQzIjeIU
	Fg67PkP4wV+XEvjPNQcPWIsEYL86CelhhtObAbpb4B6DYJdCzHwzyca6pUHsThfJ
	PeNTax3z7akw5rx69ooh4ecSzus=
Received: by filter0256p1las1.sendgrid.net with SMTP id filter0256p1las1-29556-5A49492B-2C
        2017-12-31 20:31:40.05522918 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0002p1iad1.sendgrid.net (SG) with ESMTP id VYMhk_8tQamr2EzDf95Q1w
	for <david@spinthemoose.com>; Sun, 31 Dec 2017 20:31:39.938 +0000 (UTC)
Date: Sun, 31 Dec 2017 20:31:40 +0000 (UTC)

**Comment by davidalpert** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  spinthemoose@gmail.com
    Domain spinthemoose.com has exceeded the max emails per hour (216/200 (108%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o5.sgmail.github.com ([192.254.113.10]:15370)
	by cp1164.blacksun.ca with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89_1)
	(envelope-from <bounces+848413-6f87-david=spinthemoose.com@sgmail.github.com>)
	id 1eVkH3-0001IZ-25
	for david@spinthemoose.com; Sun, 31 Dec 2017 14:32:01 -0600
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=AWjgxNKLDX++B8SA3gGWpZ7F5Hg=; b=qNqpBKDQ8iKF95le
	z+UknemCxAF5tA8Cl1zKGUttxwB5T+AUydN+E3109yLf9fOFISNIkHThUhy58TmI
	kUfO151KZx0vODYRSJuqVaUzp+ak/zlLJLNJCZhWm7WM/e8zckhgWI3wiwtGmsPC
	heGPb5o+3sIrVCKkQ6Z72tjBn18=
Received: by filter0183p1las1.sendgrid.net with SMTP id filter0183p1las1-15228-5A49492B-21
        2017-12-31 20:31:39.77541304 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0008p1iad1.sendgrid.net (SG) with ESMTP id _7P1ntp4SCuXk2hQ0vu5bw
	for <david@spinthemoose.com>; Sun, 31 Dec 2017 20:31:39.777 +0000 (UTC)
Date: Sun, 31 Dec 2017 20:31:39 +0000 (UTC)
