### ISSUE TITLE
Assembly load issue

### ISSUE THREAD

**Issue by girish-a** [aspnet/Home#848]
I have a class library(Package) in which I have some RazorEngine 3.7.0 code which parses a template.

When I invoke the Parse() method on the library from a unit test, it works, but when I call it from a web API, I get the error "Could not load file or assembly 'System.Web.Razor, Version=3.0.0.0."

Not sure why this is happening.

I saw this StackOverflow discussion and thought it might be a similar issue:

http://stackoverflow.com/questions/29007962/how-can-i-diagnose-missing-dependencies-or-other-loader-failures-in-dnx/29161703#29161703

But even when I cleaned up all the packages and runtime folders, reinstalled dnvm and ran a restore, the issue persists.

I have uploaded the code sample to this repo - you should be able to replicate the problem with this code sample:
https://github.com/girish-a/try

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.

**Comment by davidalpert** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  spinthemoose@gmail.com
    Domain spinthemoose.com has exceeded the max emails per hour (214/200 (107%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext8.iad.github.net ([192.30.252.199]:36528 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by cp1164.blacksun.ca with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.89_1)
	(envelope-from <noreply@github.com>)
	id 1eVkGw-0001Hc-Nt
	for david@spinthemoose.com; Sun, 31 Dec 2017 14:31:54 -0600
Date: Sun, 31 Dec 2017 12:31:34 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1514752294;
	bh=gwEOTfaleDPKXCkWTo8LPID3JoSJOvPHW7vFYSzCEq0=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=UhQk2M9jZGrlE0p1KWHE/PkENwcFW60Ooi62acWVtlqpDjgrG34miUxMPT3T5Tx3w
	 ga1h6lA38bizJIH2cEK7RY1dBQ5kF3LwLqZDcqxwRWX0fbBY6SxnWiZLXfhNiauIPZ
	 VIjQ5nxs5lAr663aZwU0c6YOVE/IdQ48zh5fAQZ4=

**Comment by davidalpert** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  spinthemoose@gmail.com
    Domain spinthemoose.com has exceeded the max emails per hour (215/200 (107%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o11.sgmail.github.com ([167.89.101.202]:24611)
	by cp1164.blacksun.ca with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89_1)
	(envelope-from <bounces+848413-6f87-david=spinthemoose.com@sgmail.github.com>)
	id 1eVkGx-0001Hi-I6
	for david@spinthemoose.com; Sun, 31 Dec 2017 14:31:55 -0600
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=p7nb3SBsjSN7yWgA9zvxD5vdJGk=; b=sANxzp31kmjCz3jr
	mniXfUB+WK8Sa289qWP+MZwoBGSWJgqkvP8pwLAWcvP7NibxYlCQ5jA2Vfxx784O
	jmm4RrsvpmHYMUMnvA0TfsLn8UGlqiOO/xK4QQ15LILOH9RhZ8WV73fOZUhwUurv
	9pxjQTCSDUBM3Si3c68HOSbeW9Y=
Received: by filter0855p1mdw1.sendgrid.net with SMTP id filter0855p1mdw1-30371-5A494926-2
        2017-12-31 20:31:34.048732057 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0016p1iad2.sendgrid.net (SG) with ESMTP id 0UI-Rv_aQJaZtb-bBf-I9w
	for <david@spinthemoose.com>; Sun, 31 Dec 2017 20:31:34.019 +0000 (UTC)
Date: Sun, 31 Dec 2017 20:31:34 +0000 (UTC)
