### ISSUE TITLE
Console Application example with DI

### ISSUE THREAD

**Issue by ngonzalezromero** [aspnet/Home#849]
Hi
I have this code

```
 public class Program    {
    public IConfiguration Configuration { get; set; }
    public IServiceCollection Collection { get; set; }

    public Program(IApplicationEnvironment app)
    {
        Configuration = new ConfigurationBuilder()
        .AddJsonFile($"{app.ApplicationBasePath}/config.json")
        .AddEnvironmentVariables()
        .Build();

    }

    public void Main(string[] args)
    {

        var service = new ServiceCollection();
        service.AddTransient<IVirtualScreen, VirtualScreen>();
        Console.WriteLine("Test");

        Console.ReadKey();
    }
      }
```

}

But, i don't how i should implement DI in another class

Regards

**Comment by davidfowl** [comment]
> But, i don't how i should implement DI in another class
What does that mean.

**Comment by BillKrat** [comment]
Perhaps the following is what you are looking for?  It displays "Hello World" to console.

    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.Framework.DependencyInjection;

    namespace ConsolePrototype
    {
        public class Program
        {
            public void Main(string[] args)
            {
                var services = new ServiceCollection();
            
                // Add our interfaces/implementation to collection
                services
                    .AddTransient<IFoo, Foo>()
                    .AddSingleton<INoFoo, NoFooHere>();

                // Build our service provider from collection
                var serviceProvider = services.BuildServiceProvider();

                // Resolve our interface - uses constructor injection
                var foo = serviceProvider.GetService<INoFoo>();

                Console.WriteLine(foo.Content);
            }

            public interface INoFoo {  string Content { get; set; } }
            public class NoFooHere : INoFoo
            {
                public string Content { get; set; }
                public NoFooHere(IFoo foo)
                {
                    Content = foo.GetFoo();
                }
            }

            public interface IFoo  {  string GetFoo(); }
            public class Foo : IFoo
            {
                public string GetFoo()
                {
                    return "Hello World";
                }                
            }
        }
    }

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.

**Comment by davidalpert** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  spinthemoose@gmail.com
    Domain spinthemoose.com has exceeded the max emails per hour (213/200 (106%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o11.sgmail.github.com ([167.89.101.202]:13679)
	by cp1164.blacksun.ca with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89_1)
	(envelope-from <bounces+848413-6f87-david=spinthemoose.com@sgmail.github.com>)
	id 1eVkGr-0001Gi-Ao
	for david@spinthemoose.com; Sun, 31 Dec 2017 14:31:49 -0600
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=lGoIn6lDkpadTYulynILn+p7t0c=; b=OT83xjLHGd76A1GY
	X89t21Pnvd6X2mEy15t6OZzHDKGKIlEsH5Vnl/xKG1gWxzUKI83N/ibsvisHbrX1
	ADfzoB0w2pZfGz5pi47lZ7ohL+aRWEYQKUvFb3QdIGo1kye32J8YIgU61GLOENbg
	J0wMxz4YrZcE2iZq9YreFMsHMIQ=
Received: by filter1247p1mdw1.sendgrid.net with SMTP id filter1247p1mdw1-28909-5A49491F-25
        2017-12-31 20:31:28.002286855 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0006p1iad2.sendgrid.net (SG) with ESMTP id csKqvg5bS8y2FOlsgta__w
	for <david@spinthemoose.com>; Sun, 31 Dec 2017 20:31:28.117 +0000 (UTC)
Date: Sun, 31 Dec 2017 20:31:28 +0000 (UTC)

**Comment by davidalpert** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  spinthemoose@gmail.com
    Domain spinthemoose.com has exceeded the max emails per hour (212/200 (106%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext1.iad.github.net ([192.30.252.192]:34658 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by cp1164.blacksun.ca with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.89_1)
	(envelope-from <noreply@github.com>)
	id 1eVkGq-0001Gh-Be
	for david@spinthemoose.com; Sun, 31 Dec 2017 14:31:48 -0600
Date: Sun, 31 Dec 2017 12:31:28 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1514752288;
	bh=Vp7NAkVU1HFRKhgDRJLd6lEn3Nl7TsdP/t+pR6x1ABs=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=zCSob5COTY5PWTqND9TxP8v55AMf1/uy4sWuzHQCqDVdlbG+0a16rG9gwFuVjgusq
	 VIftQtA9utRb8I9vZ+tLFFVS8uabjiYsK7NcygYLdyu8LhnPUw3zyNLLl3UTNtnxwU
	 7kKGsKlNHZktKp/WJXa8e8+CeFoDkeR6SN1GFhXk=
