### ISSUE TITLE
Unable to locate Microsoft.CodeAnalysis.CSharp during dnu restore on Mac OS X

### ISSUE THREAD

**Issue by miguellira** [aspnet/Home#851]
Upgraded to the latest unstable build `1.0.0-beta7-15019` and attempted to `dnu restore` the `HelloMvc` app in `samples\Home`. Followed suggestions made here https://github.com/aspnet/Home/issues/810 but I'm still unable to dnu restore on Mac OS X.

On the myget feed, `Microsoft.CodeAnalysis.CSharp` currently points to a later version, namely `v1.1.0-beta1-20150817-04`.

Below is the error summary from a `dnu restore` call:

```
Errors in /Users/miguellira/Documents/Github/Home/samples/latest/HelloMvc/project.json
    Unable to locate Microsoft.CodeAnalysis.CSharp >= 2.0.0-beta1-20150806-01

NuGet Config files used:
    /Users/miguellira/.config/NuGet/NuGet.Config
    /Users/miguellira/Documents/Github/Home/samples/latest/NuGet.Config

Feeds used:
    https://www.myget.org/F/aspnetvnext/api/v2/
    https://nuget.org/api/v2/
    https://www.myget.org/F/roslyn-nightly/
    https://www.myget.org/F/dotnet-corefx/
```

**Comment by causer** [comment]
Try to change you nuget.config like in this commit: https://github.com/aspnet/dnx/commit/f3de70abcf1c455a3a6723aba680a37091c0f0cf

Also i think you don't need this two feeds:
https://www.myget.org/F/roslyn-nightly/
https://www.myget.org/F/dotnet-corefx/

**Comment by miguellira** [comment]
@causer Thanks. I'm able to restore/build/run `HelloMvc`. Running into a runtime issue, but I'll dig through the recent Announcements and see what's changed.

For the record, the issue I referenced (https://github.com/aspnet/Home/issues/810) suggested the addition of those two feeds which is why I added them. However, after updating my vNext feed to "aspnetlitedev" as the link you provided suggested I was able to restore.

My `NuGet.config` is currently set to the following:

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <!--add key="AspNetVNext" value="https://www.myget.org/F/aspnetvnext/api/v2" /-->
    <add key="AspNetVNext" value="https://www.myget.org/F/aspnetlitedev/api/v2" />
    <add key="NuGet" value="https://nuget.org/api/v2/" />
    <!--
    <add key="Roslyn" value="https://www.myget.org/F/roslyn-nightly/" />
    <add key="DotNet" value="https://www.myget.org/F/dotnet-corefx/" />
    -->
  </packageSources>
</configuration>
```

**Comment by miguellira** [comment]
For the record, looks like beta8 just dropped and it addresses all of the restore/build/run issues I encountered with beta7.

Curiously, at the moment running `dnvm upgrade` states:
```
Latest version is 1.0.0-beta6 
```
yet running `dnvm upgrade -u` brings down `1.0.0-beta8-15120` and with this DNX version I am able to restore/build/run `Home/samples/latest/HelloMvc` without any issues.

In fact, the restore process only uses the two well known/documented feeds:
```
Feeds used:
    https://www.myget.org/F/aspnetvnext/api/v2/
    https://nuget.org/api/v2/
```
No need to add the "aspnetlitedev" feed previously discussed. I'll keep this open for a day in case others stumble upon this scenario.
