### ISSUE TITLE
InvalidOperationException - No service for type 'Microsoft.Framework.Runtime.ILibraryManager' has been registered.

### ISSUE THREAD

**Issue by paranoid-android** [aspnet/Home#852]
Hello,

I have been working on a ASP.NET 5 (vNext) app. This app is supposed to get continuously deployed as an Azure Web App. The deployment is successful. However, when I visit the url, I get a runtime error that says:

```
Server Error in '/' Application.

Runtime Error

Description: An application error occurred on the server. The current custom error settings for this application prevent the details of the application error from being viewed remotely (for security reasons). It could, however, be viewed by browsers running on the local server machine. 

Details: To enable the details of this specific error message to be viewable on remote machines, please create a <customErrors> tag within a "web.config" configuration file located in the root directory of the current web application. This <customErrors> tag should then have its "mode" attribute set to "Off".

<!-- Web.Config Configuration File -->

<configuration>
    <system.web>
        <customErrors mode="Off"/>
    </system.web>
</configuration>

Notes: The current error page you are seeing can be replaced by a custom error page by modifying the "defaultRedirect" attribute of the application's <customErrors> configuration tag to point to a custom error page URL.


<!-- Web.Config Configuration File -->

<configuration>
    <system.web>
        <customErrors mode="RemoteOnly" defaultRedirect="mycustompage.htm"/>
    </system.web>
</configuration>
```

When I look in the eventlog.xml file from the server, I see the following:

```
HostName=ConsoleHost
    HostVersion=4.0
    HostId=[hostId]
    EngineVersion=4.0
    RunspaceId=[RunspaceId]
    PipelineId=
    CommandName=
    CommandType=
    ScriptName=
    CommandPath=
    CommandLine=</Data></EventData></Event><Event><System><Provider Name="ASP.NET 4.0.30319.0"/><EventID>1309</EventID><Level>2</Level><Task>0</Task><Keywords>Keywords</Keywords><TimeCreated SystemTime="2015-08-19T17:28:39Z"/><EventRecordID>1276999796</EventRecordID><Channel>Application</Channel><Computer>RD000D3A10B97C</Computer><Security/></System><EventData><Data>3005</Data><Data>An unhandled exception has occurred.</Data><Data>8/19/2015 4:13:38 PM</Data><Data>8/19/2015 5:28:38 PM</Data><Data>[someId]</Data><Data>1</Data><Data>1</Data><Data>0</Data><Data>[somePath]</Data><Data></Data><Data>/</Data><Data>D:\home\site\wwwroot\</Data><Data>[SomeId]</Data><Data></Data><Data>[AnotherId]</Data><Data>w3wp.exe</Data><Data>IIS APPPOOL\MyApp-Name</Data><Data>InvalidOperationException</Data><Data>No service for type 'Microsoft.Framework.Runtime.ILibraryManager' has been registered.
   at Microsoft.Framework.DependencyInjection.ServiceProviderExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Framework.DependencyInjection.ServiceProviderExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.AspNet.Loader.IIS.HeliosRuntimeManager..ctor(String appId, String appConfigPath, String appBaseDirectory, IServiceProvider serviceProvider, IProcessHostSupportFunctions supportFunctions, LoadApplicationData* pLoadAppData)
   at Microsoft.AspNet.Loader.IIS.HeliosCustomLoader.LoadApplication(String appId, String appConfigPath, String appBaseDirectory, IProcessHostSupportFunctions supportFunctions, LoadApplicationData* pLoadAppData)
   at AspNet.Loader.Interop.IHeliosLoader.LoadApplication(String appId, String appConfigPath, String appBaseDirectory, IProcessHostSupportFunctions supportFunctions, LoadApplicationData* pLoadAppData)
   at AspNet.Loader.Bootstrapper.LoadApplicationNet45(String appId, String appConfigPath, IProcessHostSupportFunctions supportFunctions, LoadApplicationData* pLoadAppData, Int32 loadAppDataSize, String runtimePackagePath, String appBasePath)
   at AspNet.Loader.Bootstrapper.LoadApplication(String appId, String appConfigPath, IProcessHostSupportFunctions supportFunctions, LoadApplicationData* pLoadAppData, Int32 loadAppDataSize)
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at System.Web.Hosting.ProcessHost.System.Web.Hosting.IProcessHostLite.ReportCustomLoaderError(String appId, Int32 hr, AppDomain newlyCreatedAppDomain)
--- End of stack trace from previous location where exception was thrown ---
   at System.Web.Hosting.ApplicationManager.CreateAppDomainWithHostingEnvironment(String appId, IApplicationHost appHost, HostingEnvironmentParameters hostingParameters)   at System.Web.HttpRuntime.HostingInit(HostingEnvironmentFlags hostingFlags, PolicyLevel policyLevel, Exception appDomainCreationException)
```

The first thing that jumped out at me was `<Provider Name="ASP.NET 4.0.30319.0"/>`. It seems like this should be something 5. When I look at the file in GitHub (https://www.github.com/<userName>/<repoName>/src/Website/project.json), I see the following:

```
{
    "webroot": "wwwroot",
    "version": "1.0.0-*",
    "dependencies": {
        "Dapper":"1.42.0-*",
        "EntityFramework.SqlServer": "7.0.0-*",
        "Kestrel": "1.0.0-*",
        "Microsoft.AspNet.Authentication.Facebook": "1.0.0-*",        
        "Microsoft.AspNet.DataProtection": "1.0.0-*",
        "Microsoft.AspNet.Diagnostics": "1.0.0-*",
        "Microsoft.AspNet.Http": "1.0.0-*",
        "Microsoft.AspNet.Mvc": "6.0.0-*",
        "Microsoft.AspNet.Mvc.TagHelpers": "6.0.0-*",
        "Microsoft.AspNet.Server.IIS":"1.0.0-*",
        "Microsoft.AspNet.Server.WebListener": "1.0.0-*",
        "Microsoft.AspNet.StaticFiles": "1.0.0-*",
        "Microsoft.AspNet.WebApi.Client": "5.2.3",
        "Microsoft.Framework.Caching.Memory": "1.0.0-*",
        "Microsoft.Framework.Configuration": "1.0.0-*",
        "Microsoft.Framework.Configuration.Json": "1.0.0-*"
    },

  "commands": {
      "run": "Microsoft.AspNet.Hosting --server Kestrel --server.urls http://localhost:5004",    
      "web": "Microsoft.AspNet.Hosting --server Microsoft.AspNet.Server.WebListener --server.urls http://localhost:5000"
  },

  "frameworks": {
    "dnx451": { },
    "dnxcore50": { }
  },

  "publishExclude": [
    "node_modules",
    "bower_components",
    "**.xproj",
    "**.user",
    "**.vspscc"
  ],
  "exclude": [
    "wwwroot",
    "node_modules",
    "bower_components"
  ],
  "scripts" : {
    "postrestore": ["npm install", "bower install"],
    "prepare" : ["gulp copy"]
  }
}
```

Oddly, everything works fine locally. Its just the deployment that does not work. I've seen other issues about this, for instance, [this one](https://github.com/aspnet/Home/issues/728). However, it did not resolve my issue. What am I doing wrong?

**Comment by davidfowl** [comment]
You have a version mismatch. Look at the dnx versions and the package version. Make sure they are in sync.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.

**Comment by davidalpert** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  spinthemoose@gmail.com
    Domain spinthemoose.com has exceeded the max emails per hour (210/200 (105%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext4.iad.github.net ([192.30.252.195]:33125 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by cp1164.blacksun.ca with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.89_1)
	(envelope-from <noreply@github.com>)
	id 1eVkGj-0001G9-W7
	for david@spinthemoose.com; Sun, 31 Dec 2017 14:31:42 -0600
Date: Sun, 31 Dec 2017 12:31:21 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1514752281;
	bh=2o+M1opyuGgrdeQh+Onvfg6QdvLnV8tmz14GJyZTeKc=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=Ljz6EpoIMIwmmhryTG7z1XMy1HV1RJy4R7TnjA3gxK8ij5Rj3nTmkuJWv5B6D1W5J
	 +pZT2bMsiV7kOpAxf+0VXOUCmQKoiFZKTnqkjkbFfJRNUswr7q9FqyOopcWB67tJcO
	 ionwnmq5Hsv9lwn3XrL9+78eTTpeKY9nH3XPbmeA=

**Comment by davidalpert** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  spinthemoose@gmail.com
    Domain spinthemoose.com has exceeded the max emails per hour (211/200 (105%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o5.sgmail.github.com ([192.254.113.10]:19492)
	by cp1164.blacksun.ca with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89_1)
	(envelope-from <bounces+848413-6f87-david=spinthemoose.com@sgmail.github.com>)
	id 1eVkGl-0001GP-8R
	for david@spinthemoose.com; Sun, 31 Dec 2017 14:31:43 -0600
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=mCg6z5/Cr6aJ1UNnJrvHw5AVLjI=; b=kXSIUa5KR7ic+DX2
	o7tzdzFGdAmiN/+ig/lqz3HPDqrj8qvLvhLjPsjMQkXUmrKxD8cSseJ5mU8hGJqG
	e3KUgPtPCZbLISN1tVFYBuJaFvMmrowr12Lcr9ZaUM3Zgy1OYY3G/oDWz6AZVByz
	ATXDoSMbW+wAVl5+L+Th4E31KhI=
Received: by filter0023p1las1.sendgrid.net with SMTP id filter0023p1las1-28569-5A49491A-11
        2017-12-31 20:31:22.393686405 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0003p1iad1.sendgrid.net (SG) with ESMTP id r7iOnwIrSBOgvhYMwGshQA
	for <david@spinthemoose.com>; Sun, 31 Dec 2017 20:31:22.320 +0000 (UTC)
Date: Sun, 31 Dec 2017 20:31:22 +0000 (UTC)
