### ISSUE TITLE
project.json metadata to DLL version information

### ISSUE THREAD

**Issue by nicolasr75** [aspnet/Home#856]
When I have "version: " "X.Y.Z" in the project.json file this seems to get inserted into the version information of my main assembly (DLL) which is great. What about other metadata? Intellisense gives me for my project.json things like title, copyright, description, summary, authors but none of these are mapped to version information strings in the DLL. 

Would be great if we could handle these informations centrally in project.json, at least CompanyName, ProductName and LegalCopyright (in addition to the already working ProductVersion) and have them appear in the DLL version information.

**Comment by leak** [comment]
Is there any news on this subject?

**Comment by Eilon** [comment]
This used to be done by DNX, but that has been replaced with dotnet-cli (https://github.com/dotnet/cli/), so I recommend trying this out using the new system. If you don't see the behavior you want, please log a new issue in that repo for the folks there to consider. Thanks!
