### ISSUE TITLE
How to run ASP.NET 5 application in IIS

### ISSUE THREAD

**Issue by developer1998** [aspnet/Home#857]
This is on Windows 10 Pro.
Inside IIS navigate to web site, create Application and point the path to your published directory and then choose the wwwroot folder.
Use ASP.NET NEXT Application Pool, and if you are deploying a x64 runtime, make sure 32-bit support is unchecked.
That is it, and it should work.
I wanted to do this for a long time and now it works:)

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.

**Comment by davidalpert** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  spinthemoose@gmail.com
    Domain spinthemoose.com has exceeded the max emails per hour (206/200 (103%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext2.iad.github.net ([192.30.252.193]:52596 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by cp1164.blacksun.ca with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.89_1)
	(envelope-from <noreply@github.com>)
	id 1eVkGY-0001Eh-FS
	for david@spinthemoose.com; Sun, 31 Dec 2017 14:31:30 -0600
Date: Sun, 31 Dec 2017 12:31:09 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1514752269;
	bh=cGU0iUwi9w431zwgYZk75oIz33bxuYHilU8YINxEqI4=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=gGobPILYGuODl5NWkGDIEh/6SDAHNTr4/IDt7LurRSN8zMgInLhhDsrTEer8W0IFX
	 QCBxLDWPUs75HTd7lBkYkIXsrDOlHv7LMe+HYMQKZp3hY1HEXJ7qsG2oQrwCWfkhAP
	 Ve83lx/snXIO7WdOVINZk0Q58NhDwyp2+AFoDGCY=

**Comment by davidalpert** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  spinthemoose@gmail.com
    Domain spinthemoose.com has exceeded the max emails per hour (207/200 (103%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o5.sgmail.github.com ([192.254.113.10]:13444)
	by cp1164.blacksun.ca with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89_1)
	(envelope-from <bounces+848413-6f87-david=spinthemoose.com@sgmail.github.com>)
	id 1eVkGZ-0001Ej-Eh
	for david@spinthemoose.com; Sun, 31 Dec 2017 14:31:31 -0600
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=byoX4D86qFp7fkzMEAhARwSCdaM=; b=TmE0UyOqDUmzAgXb
	OU3O3OjkvHSMFsgYmr7UAEPhtXkK1SjyvG4sYSnVhJvQj3gga3mJ18BYfDkoDpGT
	n2fQdo6LYQ1SmrfV7lb6TJKwNOeh22CfnKBiQ4IO3VHdLFIt7iQgdpIoyvB7Zfrk
	SaoLwk7FnznO91LbOrQI0f4ablc=
Received: by filter0247p1las1.sendgrid.net with SMTP id filter0247p1las1-17948-5A49490E-1D
        2017-12-31 20:31:10.505872658 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0021p1iad2.sendgrid.net (SG) with ESMTP id C3XPnjlRSGauGS57fNbexg
	for <david@spinthemoose.com>; Sun, 31 Dec 2017 20:31:10.617 +0000 (UTC)
Date: Sun, 31 Dec 2017 20:31:10 +0000 (UTC)
