### ISSUE TITLE
Unable to install DNVM while behind a corporate proxy

### ISSUE THREAD

**Issue by FabienDehopre** [aspnet/Home#858]
It is impossible to install the DNVM tool from the command line (without VS2015) while being behind a corporate proxy.

I ran the following command

```
@powershell -NoProfile -ExecutionPolicy unrestricted -Command "&{$Branch='dev';iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.ps1'))}"
```

I always receive the following message:

```
Exception calling "DownloadString" with "1" argument(s): "The remote server returned an error: (407) Proxy Authentication Required."
At line:1 char:17
+ &{$Branch='dev';iex ((new-object net.webclient).DownloadString('https://raw.gith ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException
```

Yet I add the environment variables HTTP_PROXY, HTTPS_PROXY and NO_PROXY.

**Comment by FabienDehopre** [comment]
There is the same problem once you have downloaded (manually) the dnvminstall.ps1 script.

A solution is proposed [here](http://stackoverflow.com/questions/14263359/access-web-using-powershell-and-proxy)

**Comment by FabienDehopre** [comment]
The pull request https://github.com/aspnet/Home/pull/859 should fix this issue

**Comment by SonizciTR** [comment]
Hi;

My company uses proxy and I have the same problem. I tried adding environment variable and -Proxy argument but nothing work.
At last i found the solution:
At "dnvm.ps1" file there is "Apply-Proxy" function. At "if (!$pb.UserName)" if paranthesis; i delete the line and added 2 new default proxy setting. I works like charm. 
I modified it like this:

function Apply-Proxy {
param(
[System.Net.WebClient] $wc,
[string]$Proxy
)
if (!$Proxy) {
$Proxy = $env:http_proxy
}
if ($Proxy) {
$wp = New-Object System.Net.WebProxy($Proxy)
$pb = New-Object UriBuilder($Proxy)
if (!$pb.UserName) {
$wp = [System.Net.WebRequest]::DefaultWebProxy
$wp.Credentials = [System.Net.CredentialCache]::DefaultNetworkCredentials
} else {
$wp.Credentials = New-Object System.Net.NetworkCredential($pb.UserName, $pb.Password)
}
$wc.Proxy = $wp
}
}

Hope this will help.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.

**Comment by davidalpert** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  spinthemoose@gmail.com
    Domain spinthemoose.com has exceeded the max emails per hour (204/200 (102%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o7.sgmail.github.com ([167.89.101.198]:16551)
	by cp1164.blacksun.ca with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89_1)
	(envelope-from <bounces+848413-6f87-david=spinthemoose.com@sgmail.github.com>)
	id 1eVkGU-0001EG-C4
	for david@spinthemoose.com; Sun, 31 Dec 2017 14:31:26 -0600
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=ISsQGniJ1QmoslRDKEqxOHHymf0=; b=q44JaANdWgDre8h4
	PTVF7uIEdZtwSECWCwSBAg9DvKhF6cVDOMcZS/dDIc8uJ6yHozIQcmbBvwTSzwaN
	yirViwP1ayjW15p3hmYP8afJdv5QFVEtryvBn/BfBD30GFrIIMyYlTlKxEibsjMi
	8nekSRUNs5LXyjjPJ/0SFb7Ty6g=
Received: by filter0039p1las1.sendgrid.net with SMTP id filter0039p1las1-26231-5A494908-12
        2017-12-31 20:31:04.593981475 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0001p1iad2.sendgrid.net (SG) with ESMTP id NVR0DKe1QhiDg-iE8uozCA
	for <david@spinthemoose.com>; Sun, 31 Dec 2017 20:31:04.593 +0000 (UTC)
Date: Sun, 31 Dec 2017 20:31:04 +0000 (UTC)

**Comment by davidalpert** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  spinthemoose@gmail.com
    Domain spinthemoose.com has exceeded the max emails per hour (205/200 (102%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o11.sgmail.github.com ([167.89.101.202]:60965)
	by cp1164.blacksun.ca with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89_1)
	(envelope-from <bounces+848413-6f87-david=spinthemoose.com@sgmail.github.com>)
	id 1eVkGX-0001EQ-Gp
	for david@spinthemoose.com; Sun, 31 Dec 2017 14:31:29 -0600
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=+Hn/C57uDUJ8WcOMaF+0uPoKJ70=; b=X2yar2xBmGiO+c+Q
	lrX4MHuC9tqdKYhoMMX8NgwIDzQG9QAbANsmlFrRvDm5t0EXzG9hgGrxGvwmKbl8
	xTbZHX6GYmqlLl7+xna+UgH6moYEQsb2weoJX+pK0GrNj/CIkfCuqVb/z/c3g6t7
	bCClHz5kJ/P6SQwpME47WnsQDt0=
Received: by filter0026p1las1.sendgrid.net with SMTP id filter0026p1las1-19366-5A494907-40
        2017-12-31 20:31:04.064175879 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0002p1iad2.sendgrid.net (SG) with ESMTP id OAlQkOH0R1WpWsO020YdGg
	for <david@spinthemoose.com>; Sun, 31 Dec 2017 20:31:04.278 +0000 (UTC)
Date: Sun, 31 Dec 2017 20:31:04 +0000 (UTC)
