### ISSUE TITLE
Concurrency in vNext

### ISSUE THREAD

**Issue by cgarciae** [aspnet/Home#860]
Hi, I am investigating different technologies for a project and have a few questions about vNext.

How is concurrency handled in vNext? I take it there is an event loop that handles `Task`s (sadly there are no [Streams](https://www.dartlang.org/articles/beyond-async/#asynchronous-generators-async) in c#) which does asynchronous IO in a single thread, but are there plans for an Actor-based library/system to do concurrent computations?

Thanks!

**Comment by benaadams** [comment]
There's been those kind of streams in c# since 2010: https://github.com/Reactive-Extensions/Rx.NET

**Comment by cgarciae** [comment]
@benaadams Nice! This is useful for another project in Unity3D. It would be even nicer if the proper Stream/Observable generator syntax is implemented.

The main question remains.

**Comment by Tratcher** [comment]
Async IO is not single threaded (except for some scenarios in the Kestrel server). Most operations are performed concurrently on normal threadpool or IOCP threads.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.

**Comment by davidalpert** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  spinthemoose@gmail.com
    Domain spinthemoose.com has exceeded the max emails per hour (202/200 (101%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o1.sgmail.github.com ([192.254.114.176]:5916)
	by cp1164.blacksun.ca with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89_1)
	(envelope-from <bounces+848413-6f87-david=spinthemoose.com@sgmail.github.com>)
	id 1eVkGN-0001Dc-Pl
	for david@spinthemoose.com; Sun, 31 Dec 2017 14:31:19 -0600
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=kgfW6zQsqB51K8Xw2+cW+yD7EKo=; b=OPNdX7LzWTvTe7zT
	Lx7dHPqJXVbYqBuvrQDKlC6uM3SyVrOKFHQGGTopZfMcbXTh6H3TyWB+UsfcoV+f
	sKhY1oJZQId75VoevnTSo7bdYLejfLs3uZm1YjZTo6oa1cFTw5Trsjyr4M3BBjqn
	H2I7+9jg2oeU+5ow1TGAfLABkYQ=
Received: by filter0199p1las1.sendgrid.net with SMTP id filter0199p1las1-31274-5A494901-22
        2017-12-31 20:30:57.972242741 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0002p1iad1.sendgrid.net (SG) with ESMTP id KRNigbJrSgWOMaxz1yy8cg
	for <david@spinthemoose.com>; Sun, 31 Dec 2017 20:30:57.928 +0000 (UTC)
Date: Sun, 31 Dec 2017 20:30:57 +0000 (UTC)

**Comment by davidalpert** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  spinthemoose@gmail.com
    Domain spinthemoose.com has exceeded the max emails per hour (203/200 (101%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o6.sgmail.github.com ([192.254.113.101]:43341)
	by cp1164.blacksun.ca with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89_1)
	(envelope-from <bounces+848413-6f87-david=spinthemoose.com@sgmail.github.com>)
	id 1eVkGO-0001Dd-Pu
	for david@spinthemoose.com; Sun, 31 Dec 2017 14:31:21 -0600
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=11HCd2PLVg2WHXYz+fMA20A/nRc=; b=h4lerQfZhJPg0lPI
	AlcamfyCK3yiuJbDUUO6my4/+BKnoeWHpSNBpkIanWivt9Mo4QPhuJuE1qzbuTCi
	g67PkPkmKNF3ndtFr19kLstWDp1y3JPaCpNS//XdC9v+jrAwamZ/J6rMzswKgoBb
	Qmj4tYnOb/CynNw9pDBwzsgVvWA=
Received: by filter0357p1las1.sendgrid.net with SMTP id filter0357p1las1-19365-5A494901-2F
        2017-12-31 20:30:58.066747472 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0008p1iad1.sendgrid.net (SG) with ESMTP id 0rAR2syPQPS1pV0dPbZSHQ
	for <david@spinthemoose.com>; Sun, 31 Dec 2017 20:30:58.029 +0000 (UTC)
Date: Sun, 31 Dec 2017 20:30:58 +0000 (UTC)
