### ISSUE TITLE
ErrorPageOptions in beta6

### ISSUE THREAD

**Issue by manfredk** [aspnet/Home#861]
After updating the ASP.Net5 WebApp project template to beta6 I have the following issue in Startup.cs:

    app.UseErrorPage(ErrorPageOptions.ShowAll);

This line throws _'ErrorPageOptions' does not contain a definition for 'ShowAll'._ Any idea, how this is handled in beta6?

**Comment by manfredk** [comment]
ErrorPageOptions still live in Diagnostics, so I checked it in Object Viewer but couldn't find "ShowAll".

After reading the intellisense description I solved the the problem with:

   app.Properties["host.AppMode"] = "development";
   app.UseErrorPage();

This worked and seems to be the way to show all errors in beta6.

**Comment by Tratcher** [comment]
Correct, most of the configuration was removed from EPO. Note you don't need the `app.Properties["host.AppMode"] = "development";` line either, that looks like legacy from Katana.  To conditionally include the middleware do something like this:
```c#
        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            // Add the following to the request pipeline only in development environment.
            if (env.IsDevelopment())
            {
                app.UseErrorPage();
            }
            else
            {
                // Add Error handling middleware which catches all application specific errors and
                // sends the request to the following path or controller action.
                app.UseErrorHandler("/Home/Error");
            }
// ...
```

**Comment by henkmollema** [comment]
You used to be able to configure which parts of the error page you wanted to show with `ErrorPageOptions`. That has been removed since beta6 and we just show everything by default. The only thing can configure now is the amount of lines of source code before and after the line of code in the exception's stack frame. You can remove the `ErrorPageOptions.ShowAll` as stated above.

**Comment by manfredk** [comment]
thx for the clarification, very helpful.
