### ISSUE TITLE
The type or namespaceame 'Runtime' does not exist in the namespace 'Microsoft.Framework' (are you missing an assembly reference?)...

### ISSUE THREAD

**Issue by ramsees** [aspnet/Home#862]
I'm using beta8 (1.0.0-beta8-15120 clr x86) and I'm getting his error.

My Project.json looks like this:

{
	"version": "1.0.0",
	
	"webroot": "wwwroot",
	
	"sources": ["src"],
	
	"frameworks": {
		"dnx451":{
			"frameworkAssemblies": {
				"System.Data": "",
				"System.Collections": ""
			}
		}
	},
	
	"dependencies": {
		"Microsoft.AspNet.Server.IIS": "1.0.0-*",
		"Microsoft.AspNet.Server.WebListener": "1.0.0-*",
		"Microsoft.AspNet.Diagnostics": "1.0.0-*",
		"Microsoft.AspNet.Mvc": "6.0.0-*",
		"FirebirdSql.Data.FirebirdClient": "4.7.0.0",
		"Microsoft.Framework.Configuration.Json": "1.0.0-*"
	},
	
	"commands": {
		"web": "Microsoft.AspNet.Hosting --server Microsoft.AspNet.Server.WebListener --server.urls http://localhost:5003"
	}
}

and my nuget.config like the attached image.
![nuget](https://cloud.githubusercontent.com/assets/26675/9456882/513cca86-4a9a-11e5-8beb-a3e220f11ffa.png)

 
Any Ideas?

**Comment by pranavkm** [comment]
`Microsoft.Framework.Runtime` was renamed to `Microsoft.Dnx.Runtime`. Perhaps your startup references the namespace?

**Comment by ramsees** [comment]
@pranavkm Thank you, I was using yo generators, I guess I need to update it.
