### ISSUE TITLE
Deploying DNXCore5 project to a Linux VM

### ISSUE THREAD

**Issue by npateman** [aspnet/Home#863]
Hi there,

I thought I had resolved this in a previous issue that I had open in the past but am still having issues.  I have a DNX Core 5 project, I'm using the publish feature of Visual Studio to deploy it to the file system.  I then zip that up and copy it to my VM.

In the zip is a bash script called "kestrel" this has an issue in the last line where it attempts to use the Windows binaries for the runtime, so I modify the line slightly so that it just calls

    dnx --appbase "$DNX_APPBASE" "Microsoft.Framework.ApplicationHost kestrel "$@"

This still doesn't work and results in the following error,

  The current runtime target framework is not compatible with "MyProject"
  Current runtime Target Framework: 'DNX,Version=v4.5.1 (dnx451)'

Now I'm pretty sure I'm only targeting DNXCore5 but several obvious questions here,

1.  Why does the bash script reference windows binaries in it?  Surely that's meant for Linux?
2.  Why does Visual Studio always build the x86 version even when I tell it I want x64?  I thought that might have been the issue and have just built an x86 server to discover it isn't.
3.  Why is it telling me I'm targeting dnx451 when that framework has been explicitly removed from both of my projects, they only target dnxcore5.

Any help with this would be greatly appreciated, I've tried stackexchange too and the official asp.net 5 forum but am not getting much luck with help and my project is pretty blocked now.  I was hoping to be able to demo this being deployed to Linux but really need assistance for this last bit.

I even removed Newtonsoft.JSON from my project thinking it might have been that but it wasn't, so I have very few dependencies now.  One of them is mine, the rest are Microsofts.

My project,json documents are as follows, according to the error this is what's wrong but I can't for the life of me work out what exactly?

My Web App

	{
	  "webroot": "wwwroot",
	  "version": "1.0.0-*",

	  "dependencies": {
		"Microsoft.Framework.ConfigurationModel": "1.0.0-beta5",
		"Microsoft.Framework.ConfigurationModel.Json": "1.0.0-beta5",
		"Microsoft.AspNet.Mvc": "6.0.0-beta5",
		"Microsoft.AspNet.Mvc.TagHelpers": "6.0.0-beta5",
		"Microsoft.AspNet.StaticFiles": "1.0.0-beta5",
		"Microsoft.AspNet.Tooling.Razor": "1.0.0-beta5",
		"Microsoft.Framework.Configuration.Json": "1.0.0-beta5",
		"Microsoft.Framework.Logging": "1.0.0-beta5",
		"Microsoft.Framework.Logging.Console": "1.0.0-beta5",
		"Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.0.0-beta5",
		"Microsoft.AspNet.Mvc.WebApiCompatShim": "6.0.0-beta5",
		"System.Security.Cryptography.DeriveBytes": "4.0.0-beta-23019",
		"MyLib": "1.0.0-*",
		"Kestrel": "1.0.0-beta5"
	  },

	  "commands": {
		"kestrel": "Microsoft.AspNet.Hosting --server Kestrel --server.urls http://localhost:5000"
	  },

	  "frameworks": {
		"dnxcore5": {
		  "dependencies": {
			"System.Runtime.Serialization.Json": "4.0.0-beta-23109",
			"System.Runtime.Extensions": "4.0.10-beta-23019",
			"System.Collections": "4.0.10-beta-23019",
			"System.Runtime": "4.0.20-beta-23019",
			"Microsoft.CSharp": "4.0.0-beta-23019",
			"System.Private.Networking": "4.0.0-beta-23109",
			"System.Net.Security": "4.0.0-beta-23109"
		  }
		}
	  },

	  "exclude": [
		"wwwroot",
		"node_modules",
		"bower_components"
	  ],
	  "publishExclude": [
		"node_modules",
		"bower_components",
		"**.xproj",
		"**.user",
		"**.vspscc"
	  ],
	  "scripts": {
		"prepublish": [ "npm install", "bower install", "gulp clean", "gulp min" ]
	  }
	}
	
My Lib

	{
	  "version": "1.0.0-*",
	  "description": "Description goes here...",
	  "authors": [ "Joe Bloggs" ],
	  "tags": [ "" ],
	  "projectUrl": "",
	  "licenseUrl": "",

	  "dependencies": {
	  },

	  "frameworks": {
		"dnxcore5": {
		  "dependencies": {
			"System.Collections": "4.0.10-beta-23019",
			"System.Runtime": "4.0.20-beta-23019",
			"Microsoft.CSharp": "4.0.0-beta-23019"
		  }
		}
	  }
	}

Nick.

**Comment by npateman** [comment]
also

kestrel script created by publish process was

	#!/bin/bash

	SOURCE="${BASH_SOURCE[0]}"
	while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
	  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
	  SOURCE="$(readlink "$SOURCE")"
	  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
	done
	DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

	export SET DNX_APPBASE="$DIR/approot/src/MyProject"

	exec "$DIR/approot/runtimes/dnx-coreclr-win-x86.1.0.0-beta5/bin/dnx" --appbase "$DNX_APPBASE" Microsoft.Framework.ApplicationHost kestrel "$@"

Changed to
	
	!/bin/bash

	SOURCE="${BASH_SOURCE[0]}"
	while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
	  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
	  SOURCE="$(readlink "$SOURCE")"
	  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
	done
	DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

	export SET DNX_APPBASE="$DIR/approot/src/MyProject"

	dnx --appbase "$DNX_APPBASE" Microsoft.Framework.ApplicationHost kestrel "$@"

**Comment by BrennanConroy** [comment]
On your Linux machine I'm assuming you have the mono dnx runtime installed and set as active dnx, so when you run the bash script it is going to be using mono which is dnx451.

In beta7 we now have a way of installing other operating systems dnx's and then you can publish with --runtime set to the specific dnx you want.

**Comment by npateman** [comment]
Hi Brennan,

Would you recommend I update from beta 5 to the latest? Also is there any chance you could outline the steps I need to perform to get it from visual studio, into Linux as dnxcore? I'm desperate to get something working and would really appreciate the help / advice.

-----Original Message-----

**Comment by BrennanConroy** [comment]
If you want to host with dnxcore50 on a non-windows OS then you will need to use beta7 or later. I don't know if VS supports publishing with a non-windows runtime yet. I would just run publish from the command line.
Go to folder with project.json
Restore packages
```dnu publish --runtime <path to dnx folder> --out <folder to publish to>```

**Comment by npateman** [comment]
that's i'll try but have literally just updated to beta 5 as i was told i would need that lol  I'm not expecting going up to 7 to be easy as going to 5 wasn't.

**Comment by BrennanConroy** [comment]
Good luck! :)

**Comment by npateman** [comment]
Sorry for posting back in here again, but it's just a quick question (i hope), regarding actually locating the beta 7 install, i'm using dnvm and typing,

---

PS C:\WINDOWS\system32> dnvm install 1.0.0-beta7 -u

There are no runtimes matching the name dnx-clr-win-x86 on feed https://www.myget.org/F/aspnetvnext/api/v2.
At C:\Users\nickp\.dnx\bin\dnvm.ps1:563 char:9
+         throw "There are no runtimes matching the name $RuntimeId on  ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (There are no ru...etvnext/api/v2.:String) [], RuntimeException
    + FullyQualifiedErrorId : There are no runtimes matching the name dnx-clr-win-x86 on feed https://www.myget.org/F/
   aspnetvnext/api/v2.

---

my dnvm version is beta8, would that need to be beta7 maybe?

**Comment by BrennanConroy** [comment]
Beta7 dnx should be released sometime today on NuGet.org

**Comment by npateman** [comment]
Oh okay... so how have people been testing with it?  Sorry I'm confused (not difficult), is there some kind of place where you can get information of published frameworks etc?  Half the time dnvm won't find packages for me if I omit a build number on the end, so seeing a list of ones I can use would be really helpful.

**Comment by BrennanConroy** [comment]
We publish release bits to NuGet, see http://www.nuget.org/packages/dnx-clr-win-x64/1.0.0-beta6 these are the ones with no build number at the end
We have the dev feed for unstable bits, see https://www.myget.org/gallery/aspnetvnext this is where the build numbers are

Getting a list of builds is tricky but there is some way with fiddler and reading the json from MyGet

**Comment by npateman** [comment]
Thanks for the info :) I'm giving beta 7 a shot now.
