### ISSUE TITLE
Delete master and release branches

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Home#865]
The Home repo has dev, master, and release, but the contents do not version like that. Reduce it to one branch (dev?) to eliminate maintenance overhead and user confusion.

Dev is the most up to date branch.

Update the DNVM push-bot that publishes to dev and release.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.

**Comment by davidalpert** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  spinthemoose@gmail.com
    Domain spinthemoose.com has exceeded the max emails per hour (200/200 (100%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext2.iad.github.net ([192.30.252.193]:49231 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by cp1164.blacksun.ca with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.89_1)
	(envelope-from <noreply@github.com>)
	id 1eVkGG-0001DE-OT
	for david@spinthemoose.com; Sun, 31 Dec 2017 14:31:12 -0600
Date: Sun, 31 Dec 2017 12:30:52 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1514752252;
	bh=fZjuAxluoPmVuUKqcQkwepR/lKGXbhbPLqay6a75Wxc=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=AaxHSv39MFIqkS31rGABQJ7BNN5GJvE3UrJhlzXkQCUCkeNQqdo8S5gFCUHUl1Zey
	 jze3vv0c9EI1E0zSt8HfPN4/GwbuRlk6sZTponG5OhZ+LmT6tQQc94MjS0ToKTCvZD
	 E0+euf8fxkIi2i49w7DHHfsnBJQGTBYVJKP3z9dI=

**Comment by davidalpert** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  spinthemoose@gmail.com
    Domain spinthemoose.com has exceeded the max emails per hour (201/200 (100%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o8.sgmail.github.com ([167.89.101.199]:52624)
	by cp1164.blacksun.ca with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89_1)
	(envelope-from <bounces+848413-6f87-david=spinthemoose.com@sgmail.github.com>)
	id 1eVkGH-0001DF-DO
	for david@spinthemoose.com; Sun, 31 Dec 2017 14:31:13 -0600
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=F8sjfLPfsucSL52drejtHpZ9lFI=; b=ldlj0Ac+9kwRGpce
	ExtKWY0jhfZfkR3b2eTDVuFE9YRmhdK4DSa3IpH+q3SvL8Zyo0xvi6kENloAM082
	aRyNViRGWmoM7BfNrpaTDL1Ud8hgW6EZVgEeUasuTS9xXNV7t6V1bt4xfqA7yvxa
	PwSjH6qXu7bnMtw3HzuvkK/DdvQ=
Received: by filter0478p1las1.sendgrid.net with SMTP id filter0478p1las1-21442-5A4948FC-11
        2017-12-31 20:30:52.263366841 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0003p1iad1.sendgrid.net (SG) with ESMTP id v3Lc4Z7YQrueRTmABaNrCg
	for <david@spinthemoose.com>; Sun, 31 Dec 2017 20:30:52.229 +0000 (UTC)
Date: Sun, 31 Dec 2017 20:30:52 +0000 (UTC)
