### ISSUE TITLE
Detect changes for project on network drive without recompile

### ISSUE THREAD

**Issue by anfomin** [aspnet/Home#866]
I'm developing on virtual machine running in Parallels Desktop. My project is located on the Mac drive and VS 2015 opens it via mapped network drive.

There is a feature that projects changes recompiled automatically on browser refresh. But this does not work to project located on the network drive. I've to build project each time I change C# file or Razor view.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
