### ISSUE TITLE
Reference another local library in a project.json file

### ISSUE THREAD

**Issue by lukemurray** [aspnet/Home#867]
Maybe not an issue, but I have been trying to figure out if I can do this.

I have an asp.net app and in it's project.json file I want to reference a package that I am also developing locally (in another path) as I have not published it to nuget yet, no want to while developing it.

Anyway to do this? Or any ideas?

Thanks

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
