### ISSUE TITLE
Add a --version option.

### ISSUE THREAD

**Issue by ajduncan** [aspnet/Home#868]
Like other command line tools, it's sometimes useful to have a version option, so you can do:

vagrant@vagrant-ubuntu-trusty-32:~$ dnvm --version
.NET Version Manager - Version 1.0.0-beta8-15502

**Comment by BrennanConroy** [comment]
Move to dnvm repo: https://github.com/aspnet/dnvm

**Comment by ajduncan** [comment]
My bad!
