### ISSUE TITLE
Error DNU Restore on Mac trying out Visual Studio Code

### ISSUE THREAD

**Issue by theiwaz** [aspnet/Home#870]
Tried different nuget sources but still getting errors. On version of mono (3.12.0)

```
GET https://www.nuget.org/api/v2/package/System.Threading.Tasks.Parallel/4.0.0-beta-23109
----------
System.NotSupportedException: Unknown header: 1631029967
  at SharpCompress.Common.Zip.ZipHeaderFactory.ReadHeader (UInt32 headerBytes, System.IO.BinaryReader reader) [0x00000] in <filename unknown>:0
  at SharpCompress.Common.Zip.SeekableZipHeaderFactory+<ReadSeekableHeader>c__Iterator0.MoveNext () [0x00000] in <filename unknown>:0
  at SharpCompress.Archive.Zip.ZipArchive+<LoadEntries>c__Iterator0.MoveNext () [0x00000] in <filename unknown>:0
  at SharpCompress.LazyReadOnlyCollection`1+LazyLoader[SharpCompress.Archive.Zip.ZipArchiveEntry].MoveNext () [0x00000] in <filename unknown>:0
```

I think it's strange the restore is picking and choosing from different sources,see `aspnetmaster` and default sources below including another `unknown header` error

```
  GET https://www.myget.org/F/aspnetmaster/api/v2/FindPackagesById()?id='System.Runtime.Serialization.Primitives'
  CACHE https://www.nuget.org/api/v2/FindPackagesById()?id='System.Runtime.Serialization.Primitives'
Warning: DownloadPackageAsync: https://www.nuget.org/__api/v2/__package/Microsoft.Win32.Registry/4.0.0-beta-23109
  Unknown header: 1680767346
```

**Comment by BrennanConroy** [comment]
You are using an old version of mono. Upgrade it and you wont see this error

**Comment by theiwaz** [comment]
Mmm feel like a pretty big n00b here. Mono --version still says 

```
Mono JIT compiler version 3.12.0 (tarball Wed Jan 28 15:32:29 GMT 2015)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
```

after downloading and updating mono. Somebody care to enlighten this old windows programmer ;)

**Comment by wholroyd** [comment]
The DNX platform requires Mono 4.0.1 or higher if I'm not mistaken. This should fix you up...

http://download.mono-project.com/archive/4.0.3/macos-10-x86/MonoFramework-MDK-4.0.3.20.macos10.xamarin.x86.pkg

**Comment by theiwaz** [comment]
Done that twice already, didn't help but I figured out the problem with that. Initially I installed Mono with home-brew and after that followed a different walkthrough and installed the package you supplied in the link. Apparently not interchangeable. After running `brew upgrade $mono` I am on the right version. Now for uninstalling the other one taking up space ;)

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
