### ISSUE TITLE
Diagnostics are not against preprocessed code

### ISSUE THREAD

**Issue by jedahu** [aspnet/Home#871]
Not sure if this is the correct place to raise this. Apologies if it isn't.

I have an ICompileModule subclass that transforms certain methods declarations from `Foo(A a)` to `Foo(A a = default(A))`. Calling code can therefore look like `Foo()`. This works fine.

However, Visual Studio 2015 continues to show red squiggle under the calling code, complaining about a missing required argument. The code builds without error, so this is a little off-putting.

Is there any way to ensure that red-squiggly kind of static analysis is performed on the preprocessed code instead of the original code?

**Comment by davidfowl** [comment]
Visual studio won't work with compile modules. Squiggles will show up and there's no real way to turn that off. I'd recommend using the compile modules for things that won't affect the IDE experience or it could get rocky pretty quickly. 

As the C# team explore meta programming, there may be a more end to end solution that will work in the IDE (for very constrained scenarios).

**Comment by jedahu** [comment]
OK. I'll lower expectations accordingly!
