### ISSUE TITLE
Async in ASP.NET vs Node.js

### ISSUE THREAD

**Issue by PrimeObjects** [aspnet/Home#872]
Hi friends,

I think ASP.NET is facing a critical moment. More and more developers are moving to node.js. The key selling point of node.js is performance and scalability. I overheard that async in .NET can provide similar performance node.js has. Did anyone finish any performance benchmark between ASP.NET and node.js, if yes, can you provide a link? If not, what's the plan to beat node.js?

Thanks
Gary

**Comment by davidfowl** [comment]
https://github.com/aspnet/benchmarks/blob/master/README.md

Also:

https://www.youtube.com/watch?v=1aDLYFBuWc8&list=PL0M0zPgJ3HSftTAAHttA3JQU4vOjXFquF&index=10

https://www.youtube.com/watch?v=7O81CAjmOXk&list=PL0M0zPgJ3HSftTAAHttA3JQU4vOjXFquF&index=4

**Comment by PrimeObjects** [comment]
Thank you for the info!
