### ISSUE TITLE
Where is this package naming exception coming from?

### ISSUE THREAD

**Issue by GuardRex** [aspnet/Home#874]
```c#
System.ArgumentException: The package ID 'company_public' contains invalid characters.
Examples of valid package IDs include 'MyPackage' and 'MyPackage.Sample'.
   at NuGet.PackageIdValidator.ValidatePackageId(String packageId)
```
Looks like I can't use an underscore, but where is that coming from? I've changed the solution name, the root namespace, removed all references to that name (except for filepaths), deleted the `bin` folder, and tried publishing with `Delete all existing files prior to publish` ... and it's still throwing.

**Comment by GuardRex** [comment]
Looks like it was coming from a filepath. Changing folder names and updating filepaths silenced it.

**Comment by FredyWenger** [comment]
I had exactly the same problem from one day to another...
Note: I have stored the project on a mapped network-drive and load it in VS2015 (Update1) from there.
All to the project (directory on the network-drive, solution and project was named "MG_Test1" and have worked until Nov. 18 2015, but strange wise has stopped to work at Nov. 19 2015 (without any change from my side).
Yesterday, I have worked with the project without problems..
Today, I had the problem abruptly - very strange!
I then also first have tried to rename the project in VS without success and then found this message.
The solution (for now - hope this remains stable) was, to create a new project-directory without the underline (_) and then copy the content of the "old" directory (\MG_test1\) to the new directory 
(\MGTest1\) and the reopen project from the new directory (note: the solution- and the project-name is still MG_Test1).
I cannot comprehend this behavior (maybe it's a VS2015 problem that will reappear).

**Comment by GuardRex** [comment]
I looked it up ... https://docs.nuget.org/create/package-conventions ... and it states:

> Namespace-like names: Package IDs should follow a pattern similar to namespaces in .NET. For example, Ninject.Mvc3 instead of Ninject-Mvc3.

Unfortunately, https://msdn.microsoft.com/library/ms229026(v=vs.100).aspx and https://msdn.microsoft.com/en-us/library/ms229026.aspx don't talk about the actual allowed characters.

In General Naming Conventions at https://msdn.microsoft.com/en-us/library/ms229045.aspx, it states ...

> X DO NOT use underscores, hyphens, or any other nonalphanumeric characters.

I guess that's the deal.

**Comment by damon-e-drake** [comment]
"dependencies": {
    "Google.Apis.Admin.Reports.reports_v1": "1.11.1.316",
    "Google.Apis.Admin.Directory.directory_v1": "1.11.1.341",
    "Newtonsoft.Json": "8.0.3"
  }

These 2 are blowing up my attempt at .Net Core. I actually need these two libraries and I am sure the same thing is happening here.
