### ISSUE TITLE
X64 WebApi consumes 3GB+ memory, however,128M for x86 version.

### ISSUE THREAD

**Issue by NetGH** [aspnet/Home#875]
Repro:
Create a WebApi project in vs 2015 and run "web" for both x64-beta6 and x86-beta6
Post /api/values in 32 concurrent HttpClients continuously.

Actual results:
For both arches, 6000+ requests per seconds.
However, for X64 DNX it takes 3GB+ memory.

**Comment by singlewind** [comment]
I think this may relate to GC. Possibly leave cool down for a while to decide whether it is bug or just moment things or behavior things for GC. It is unlikely asp.net issue. More likely issue of runtime. Good to know, let the asp.net team report this to the clr team.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
