### ISSUE TITLE
Adding new Controller while running does not get picked up by Asp.net

### ISSUE THREAD

**Issue by nwayve** [aspnet/Home#876]
Repro:  
Create a basic MVC application  
`app.UseMvcWithDefaultRoute();`  
Run app (F5 or Ctrl+F5)  
Navigate to invalid url: `/foo`
Error, page doesn't exist (expected)  
Create `FooController.cs` with Index action  
`return Content("Foo Controller");`  
Refresh page  
Page not found.

**Comment by Bartmax** [comment]
Confirmed same behavior here.

Controllers are not picked up if they were created AFTER server is started. (at least not in IIS Express running on non-debug mode).
restarting IIS Express and the route is found.

**Comment by wholroyd** [comment]
I don't think this has ever been supported. Only changes to configuration files would make IIS pick up new files.

**Comment by nwayve** [comment]
This was a dynamic compilation feature I saw demonstrated in Scott Allen's ASP.NET 5: First Look course on Pluralsight (Files and Compilation section).  This was the CTP version so I'm sure a lot has changed but I remember trying this out and seeing it work.

**Comment by wholroyd** [comment]
If that's something they hope to support in the future, then that's awesome.

![The more you know](http://ak-hdl.buzzfed.com/static/2015-02/1/20/enhanced/webdr08/enhanced-32005-1422840611-40.jpg)

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
