### ISSUE TITLE
beta7, beta7, beta7!

### ISSUE THREAD

**Issue by ForkBug** [aspnet/Home#877]
beta7, beta7, beta7!

**Comment by davidfowl** [comment]
beta7

**Comment by singlewind** [comment]
when?

**Comment by stebet** [comment]
+1 for excitement!

**Comment by StanislavPrusac** [comment]
+1 for beta7

**Comment by singlewind** [comment]
+1 every teams catch up progress

**Comment by nwayve** [comment]
+1 am I doing this right?

**Comment by wholroyd** [comment]
![1649884](https://cloud.githubusercontent.com/assets/147990/9612784/808747d2-50b5-11e5-8c19-a29a5d82e0ae.jpg)

**Comment by ymind** [comment]
+1

**Comment by sandorfr** [comment]
+1
We are like children waiting for the next toy :d.

**Comment by Benjiiim** [comment]
Should be there in less than 12 hours according to @DamianEdwards on Twitter: https://twitter.com/DamianEdwards/status/638943636047028224

**Comment by wholroyd** [comment]
And it's now live!

**Comment by fmoliveira** [comment]
beta7! :smiley:
