### ISSUE TITLE
Provide RPM install instructions

### ISSUE THREAD

**Issue by nguyenm100** [aspnet/Home#878]
Please provide install instructions for rpm-type systems.  We use rhel at work and I'd like to push adoption of .net here. 

Thanks!

**Comment by wholroyd** [comment]
There aren't any at this time, but I've started some work on getting DNVM packaged into DEB and RPM packages over in #437.

**Comment by nguyenm100** [comment]
Not RPM but got b7 coreclr installed via:

sudo yum -y install libunwind gettext libcurl-devel openssl-devel zlib unzip
curl -sSL https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.sh | DNX_BRANCH=dev sh && source ~/.dnx/dnvm/dnvm.sh
dnvm upgrade -r coreclr

**Comment by pruiz** [comment]
I dont think this is nearly a real solution to people asking for rpm build instructions. More so, if/when the proposed solutions installs to a user's home directory.

Being able to package vNext in a standar format for linux distros is (IMHO) a must. Obviously, packaging and releasing such packages is not an asp.net's team responsability. But giving some advice and/or support for those who may need/want to provide ready-made packages, would be something really appreciated by community.
