### ISSUE TITLE
Beta 7 references cannot be restored

### ISSUE THREAD

**Issue by Kagamine** [aspnet/Home#880]
The references is empty, and there is no respond when I clicked the restore packages.

**Comment by Kagamine** [comment]
<img width="318" alt="qq20150903-1 2x" src="https://cloud.githubusercontent.com/assets/2216750/9650246/ef7f2c94-5232-11e5-8aa6-beeaf76f2b90.png">

**Comment by Kagamine** [comment]
<img width="318" alt="qq20150903-1 2x" src="https://cloud.githubusercontent.com/assets/2216750/9650246/ef7f2c94-5232-11e5-8aa6-beeaf76f2b90.png">

**Comment by Kagamine** [comment]
<img width="698" alt="qq20150903-2 2x" src="https://cloud.githubusercontent.com/assets/2216750/9650364/6f213d24-5234-11e5-91c3-c65cfc4596c0.png">

**Comment by singlewind** [comment]
Could you post your project.json file?
