### ISSUE TITLE
Project with b7 is not able to publish

### ISSUE THREAD

**Issue by Kagamine** [aspnet/Home#881]
<img width="449" alt="qq20150903-9 2x" src="https://cloud.githubusercontent.com/assets/2216750/9650938/490cda14-523c-11e5-8b89-084233e77711.png">

The publish button is gray.

**Comment by Kagamine** [comment]
How to publish a class library into a nuget package?

**Comment by singlewind** [comment]
I reckon your project.json file is missing

**Comment by Kagamine** [comment]
Create a Class Library (package), and it cannot be published.

**Comment by Kagamine** [comment]
@signlewind 你装了beta7试试，反正我这是不行，类库类型的项目不能发布了，beta6是可以的，我发布类库是为了把他打成nuget包。

**Comment by singlewind** [comment]
@Kagamine  I think you have updated the tools as I did. the tools haven't registered its template properly. That is why visual studio could not detect it is nuget package project. You still can use command to package any way.
