### ISSUE TITLE
DNX beta6/beta8 vs VSCode on Mac OS X Yosemite

### ISSUE THREAD

**Issue by Ribeiro** [aspnet/Home#882]
Hi, guys !

I'm experiencing some issues while trying to use VSCode and DNVM/DNX generated using yeoman (Basic Asp.NET MVC):

1) If I use the beta6 then VSCode Intellisense works flawlessly, but when I run dnx . kestrel it fails:

"System.InvalidOperationException: No service for type 'Microsoft.Dnx.Runtime.IApplicationEnvironment' has been registered."

2) If i Use the beta8 VSCode Intellisense doesn't work (It seems it fails recognizing the project) but runs flawlessly when i run dnx . kestrel.

Suggestions? Solutions? Please, help me out!

**Comment by davidfowl** [comment]
> 1) If I use the beta6 then VSCode Intellisense works flawlessly, but when I run dnx . kestrel it fails:

If it fails with that error then you have a package and dnx mismatch. Make sure you're active/default dnx is beta6 and that your packages are all beta6. Problems like that only show up when things mismatch. If you want to see what package versions got resolved, look at the `project.lock.json` file.

> 2) If i Use the beta8 VSCode Intellisense doesn't work (It seems it fails recognizing the project) but runs flawlessly when i run dnx . kestrel.

You likely need to wait for an update?

**Comment by rhires** [comment]
2) It's something to do with OmniSharp. [According to their website](http://www.omnisharp.net/), OmniSharp is started by VSCode, but it seems that OmniSharp is linked against the libraries wrong? Perhaps do what @davidfowl suggests in item 1 and see if that fixes it. (BTW, the OmniSharp site doesn't have a way to link to the item I'm referencing, so you would have to click on the VSCode icon on the front page to see what I'm saying it says.)
