### ISSUE TITLE
Microsoft.Framework.ConfigurationModel stuck on beta 5?

### ISSUE THREAD

**Issue by npateman** [aspnet/Home#883]
Hi there,

I don't seem to be able to update my Microsoft.Framework.ConfigurationModel reference to beta 7, is this now under a different name or something?  I need it for the Configuration class.

Nick.

**Comment by henkmollema** [comment]
It's been moved to another package: `Microsoft.Framework.OptionsModel`.

**Comment by davidfowl** [comment]
@henkmollema not quite. It was renamed to Microsoft.Framework.Configuration

**Comment by davidfowl** [comment]
@npateman Follow https://github.com/aspnet/Announcements/issues for breaking changes like these

**Comment by npateman** [comment]
Great thanks!

**Comment by henkmollema** [comment]
Oh duh, copied the wrong package name haha. :dizzy_face:

**Comment by shreedevishete** [comment]
Can anyone share , how to read config file  in Beta7

**Comment by Eilon** [comment]
@shreedevishete you can see an example in the MusicStore sample app

https://github.com/aspnet/MusicStore/blob/dev/src/MusicStore/Startup.cs#L24-L33
