### ISSUE TITLE
VS2015 Build fails after Microsoft.AspNet.Server.(component) beta7 upgrade

### ISSUE THREAD

**Issue by eatgit** [aspnet/Home#886]
Win 8.1 (fully patched) / VS2015 ("Tools->Extenstion and.." Updated, including NuGet) 

Start->New Project->ASP.NET Web Application->Empty

Rebuild All (OK)

Right-Click WebApplication1->Manage NuGet Packages->Filter Upgrade

Microsoft.AspNet.Server.IIS Version 1.0.0-beta7 - Press Upgrade
Microsoft.AspNet.Server.WebListener 1.0.0-beta7 - Press Upgrade

Right-Click WebApplication1->Rebuild:

Severity	Code	Description	Project	File	Line
Error	CS0246	The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)	WebApplication1		1
Error	CS0518	Predefined type 'System.String' is not defined or imported	WebApplication1		1
Error	CS0246	The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)	WebApplication1		2
Error	CS0518	Predefined type 'System.String' is not defined or imported	WebApplication1		2
Error	CS0246	The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)	WebApplication1		3
Error	CS0518	Predefined type 'System.String' is not defined or imported	WebApplication1		3
Warning		Dependency specified was Microsoft.AspNet.Server.IIS >= 1.0.0-beta7 but ended up with Microsoft.AspNet.Server.IIS 1.0.0-beta5.	WebApplication1	C:\dev\src\dotnet-core\WebApplication1\project.json	6
Warning		Dependency specified was Microsoft.AspNet.Server.WebListener >= 1.0.0-beta7 but ended up with Microsoft.AspNet.Server.WebListener 1.0.0-beta5.	WebApplication1	C:\dev\src\dotnet-core\WebApplication1\project.json	7

project.json
{
    "webroot": "wwwroot",
    "version": "1.0.0-*",

    "dependencies": {
        "Microsoft.AspNet.Server.IIS": "1.0.0-beta7",
        "Microsoft.AspNet.Server.WebListener": "1.0.0-beta7"
    },

    "commands": {
        "web": "Microsoft.AspNet.Hosting --config hosting.ini"
    },

    "frameworks": {
        "dnx451": { },
        "dnxcore50": { }
    },

    "publishExclude": [
        "node_modules",
        "bower_components",
        "**.xproj",
        "**.user",
        "**.vspscc"
    ],
    "exclude": [
        "wwwroot",
        "node_modules",
        "bower_components"
    ]
}

**Comment by npateman** [comment]
Not sure if this is relevant, but every time I get those "The type or namespace name 'System'", errors, I close all open files, close visual studio.  Open it up again and then restore packages on the project, and then build it, assuming the package restore worked.

**Comment by eatgit** [comment]
Tried it, still the same problem.

**Comment by clivingston2** [comment]
What typically works for me is to:
1. Ensure that the beta7 runtime installed by running 'dnvm list'.  If it beta7 is not listed run 'dnvm upgrade'.
2. In 'global.json', ensure that the sdk is referencing the beta7 runtime.
3. Run 'dnu restore'.
4. Build the project.
You may need to close Visual Studio and reopen the project to resolve the errors.

**Comment by eatgit** [comment]
dnvm upgrade - seemed to complete successfully
dnu restore - failed 

C:\Program Files (x86)\Microsoft Visual Studio 14.0>dnu restore
Microsoft .NET Development Utility CLR-x86-1.0.0-beta7-15532

  CACHE https://www.nuget.org/api/v2/
Restoring packages for C:\Program Files (x86)\Microsoft Visual Studio 14.0\Commo
n7\IDE\AspNetProjectTemplates\1033\ClassLibrary\project.json
Writing lock file C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\ID
E\AspNetProjectTemplates\1033\ClassLibrary\project.lock.json
----------
System.UnauthorizedAccessException: Access to the path 'C:\Program Files (x86)\M
icrosoft Visual Studio 14.0\Common7\IDE\AspNetProjectTemplates\1033\ClassLibrary
\project.lock.json' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, I
nt32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions o
ptions, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolea
n useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access,
FileShare share)
   at Microsoft.Dnx.Tooling.LockFileFormat.Write(String filePath, LockFile lockF
ile)
   at Microsoft.Dnx.Tooling.RestoreCommand.WriteLockFile(LockFile previousLockFi
le, String projectLockFilePath, Project project, List`1 graphItems, PackageRepos
itory repository, IProjectResolver projectResolver, IEnumerable`1 contexts)
   at Microsoft.Dnx.Tooling.RestoreCommand.<RestoreForProject>d__61.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at Microsoft.Dnx.Tooling.RestoreCommand.<>c__DisplayClass60_0.<<Execute>b__2>
d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Dnx.Tooling.RestoreCommand.<Execute>d__60.MoveNext()
----------
Restore failed
Access to the path 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\
IDE\AspNetProjectTemplates\1033\ClassLibrary\project.lock.json' is denied.


and under Administrator:


C:\Windows\system32>dnu restore
Microsoft .NET Development Utility CLR-x86-1.0.0-beta7-15532

----------
System.UnauthorizedAccessException: Access to the path 'C:\Windows\system32\LogF
iles\WMI\RtBackup' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.AddSearchableDirsToStack(SearchDa
ta localSearchData)
   at System.IO.FileSystemEnumerableIterator`1.MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 c
ollection)
   at Microsoft.Dnx.Tooling.RestoreCommand.<Execute>d__60.MoveNext()
----------
Restore failed
Access to the path 'C:\Windows\system32\LogFiles\WMI\RtBackup' is denied.



As I recall this an ETW dir owned by system.

Now all the updated Assemblies are with Yellow warning signs - References (Errors - see error list)


(restarted windows and VS)

**Comment by clivingston2** [comment]
Ensure that you have navigated to the directory that contains the project.json file before running 'dnu restore'.
Otherwise, once in a while when that happens to me, I can get around it by deleting the project.json.lock file in Visual Studio and then building and letting Visual Studio restore the packages that way.  
You can also try running 'dnvm setup', then 'dnvm update-self', then finally run 'dnu restore'.

**Comment by eatgit** [comment]
Ye'p running dnu restore from project.json dir fixed it.

Build now  passes OK

Thanks!

**Comment by dazinator** [comment]
+1 this worked for me too - thank you.

**Comment by SirwanAfifi** [comment]
+1 It worked for me :) Thanks

**Comment by AlexOldest** [comment]
You helped me too. Thanks.
I wonder how to link my own StyleSheet ti Layout.cshtml in ASP.NET 5 MVC6.
Usual approach refused to work.
