### ISSUE TITLE
vNext/XmlSerializers

### ISSUE THREAD

**Issue by veccsolutions** [aspnet/Home#887]
In the original .net we had the option to create xmlserializers on build. This way when we had a large number of models initial service calls were nice and fast.

In vNext, I can't find anything on how to create the xmlserializers, because of that the first call to one of my 3rd party services is taking about a minute (it's a huge service) with about a thousand models.

I generate my client using a prebuild script that generates the service client using svcutil. The resulting cs file is then automatically compiled by roslyn into my vNext class package and I can then reference the project like normal.

I had originally wrapped an older compiled .net library and the xmlserializers into separate packages, referenced both of them and that worked as I had expected, sort of. The issue I ran into is that IISExpress was complaining that it couldn't find the wrapped libraries, in order for wrapped libraries to work I had to publish the entire application and host it with IIS which makes debugging a nightmare.

The overall current solution layout is attached as an image.
![arch](https://cloud.githubusercontent.com/assets/4001449/9667944/03b825ae-523c-11e5-9a66-97da467d6311.png)

Is there a way to build the xmlserializers library like we used to be able to?

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
