### ISSUE TITLE
Command Palette only showing 2 git commands?

### ISSUE THREAD

**Issue by rhires** [aspnet/Home#889]
I have VSCode 0.8.0 with beta 6 runtime on OSX Mavericks - when I want to run git commands, I hit the icon for git, and then I open the command palette, type "git", click "Execute Git Commands" and the only two commands I get are branch and checkout...why would that be? And how do I get the rest of the Git Commands to appear and work? If I try to enter the command I want (git push) I get an error "No Git Commands Matching". Git works perfectly fine from the command line in the project directory...

**Comment by Daniel15** [comment]
You should probably report this over at https://code.visualstudio.com/Issues/List instead :+1:

**Comment by rhires** [comment]
All done. Thank you.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
