### ISSUE TITLE
Proposal: Change semantic version for release to -betaX-final

### ISSUE THREAD

**Issue by tillig** [aspnet/Home#890]
In trying to support [Autofac](http://autofac.org) and release an updated build roughly corresponding with each released beta, I'm running into semantic versioning challenges that I think can be fairly easily fixed.

We'd like to make sure that Autofac gets built with only dependencies that come from NuGet.org so we don't make people add any MyGet pre-pre-release locations to their package sources. (Maybe that's already a flaw in logic.)

However, the challenge we have is that the pre-pre-release packages for the next beta are in the form `1.0.0-beta7-12345` and the "final" pre-release on NuGet.org ends up being `1.0.0-beta7`. From a semantic version perspective, `1.0.0-beta7-12345` comes _after_ `1.0.0-beta7`. So when we, say, try to use a version of XUnit that requires a pre-pre-release of [Microsoft.Framework.TestAdapter](https://www.nuget.org/packages/Microsoft.Framework.TestAdapter/) (say 1.0.0-beta7-12345) we get stuck because the actual released version doesn't satisfy the minimum requirements... even though it should.

**My proposal is to change the way "final" beta releases are semantically versioned so they're `1.0.0-beta7-final`** - which would semantically (alphabetically) come _after_ any of the pre-pre-releases and would allow things that are built against those earlier releases to more easily work with the official pre-releases on NuGet.org.

Note I'm not glued to `-final` - as long as it comes semantically/alphabetically _after_ any of the pre-pre-releases, the update to the official pre-release would be a lot smoother and faster.

**Comment by pranavkm** [comment]
cc @davidfowl.

**Comment by Eilon** [comment]
Ah, we've discussed this exact approach before. I'm personally a fan of it because it far more closely matches SemVer's semantics for... ummm... versioning!

**Comment by pranavkm** [comment]
We decided to go with this approach for RC1. The packages we'll release will be of the format `1.0.0-rc1-final`.

**Comment by victorhurdugaci** [comment]
*final*ly! :clap:
