### ISSUE TITLE
Linux runtime looking in /usr/local/lib

### ISSUE THREAD

**Issue by jrock2004** [aspnet/Home#893]
Just followed the instructions for linux but now everytime I open my terminal I am getting the message

```
find: `/usr/local/lib/dnx/runtimes': No such file or directory
```

My runtimes are in my home directory

```
jcostanzo at surfacepro in ~/.dnx 
$ pwd
/home/jcostanzo/.dnx

jcostanzo at surfacepro in ~/.dnx 
$ ls
alias  dnvm  runtimes
```

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
