### ISSUE TITLE
Beta7: System.InvalidOperationException: No service for type 'Microsoft.Framework.Runtime.IApplicationEnvironment' has been registered.

### ISSUE THREAD

**Issue by martinalderson** [aspnet/Home#894]
After upgrading to beta7 the web [without membership provider] same doesn't work when I run dnx kestrel on OS X. Switching back to beta6 does work. The console app example does work under beta7.

**Comment by martinalderson** [comment]
Same with the membership provider too.

**Comment by davidfowl** [comment]
Look at your `project.lock.json` to see what versions are being used. Look at what version of the dnx is being used.

**Comment by martinalderson** [comment]
"DNX,Version=v4.5.1": {
      "Kestrel/1.0.0-beta6": {

**Comment by davidfowl** [comment]
There ya go. So you're running Kestrel beta7 with beta7 dnx right? I'll help you out:

https://github.com/aspnet/Announcements/issues/53

**Comment by martinalderson** [comment]
Sure. Does this mean the yo aspnet generator needs updated too? Should I raise the issue there?

**Comment by davidfowl** [comment]
Sure cc @sayedihashimi

**Comment by martinalderson** [comment]
Cool. It may be worth adding a notice on the aspnet site because people are going to be confused when it doesn't work when they follow the docs until yo aspnet is upgraded.

**Comment by davidfowl** [comment]
@martinalderson It's stated in the beta7 blog post. There's a direct link to all announcements and breaking changes for beta7.

**Comment by sayedihashimi** [comment]
yo aspnet has already been updated for beta7. Update the generator-aspnet npm package.
