### ISSUE TITLE
Readme talks about DNX, but doesn't say what it is

### ISSUE THREAD

**Issue by TWolverson** [aspnet/Home#896]
_This guide is designed to get you started building applications with the latest development versions ASP.NET 5 and DNX_

OK. What is DNX? This is not explained anywhere.

_In order to be able to get new builds of the DNX, and switch between them, you need to get the .NET Version Manager (DNVM) command line tool._

OK. Why would I want to do that, given that I don't know what DNX is?

Readme should define the terms it uses within the document.

**Comment by GuardRex** [comment]
It fell to https://github.com/aspnet/Home/wiki

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
