### ISSUE TITLE
Beta 7: Publish is always in "Debug" Configuration

### ISSUE THREAD

**Issue by Sharpiro** [aspnet/Home#898]
When I publish an ASP.Net 5 web application using all the defaults to either IIS local or Azure, the configuration is always set to DEBUG, regardless of whether "Release" is specified in the Publish options.

The confusing part is that according to the "Output", the configuration did successfully build in "Release".  But for some reason IIS/Azure is still assuming that it should execute in a Debug Configuration.

The way I discovered this was through the following :

```
#if !DEBUG
            ///code NEVER executes in IIS/Azure!
#endif

#if DEBUG
            ///code ALWAYS executes in IIS/Azure!
#endif
```
Thanks

**Comment by davidfowl** [comment]
Are you using beta7?

**Comment by davidfowl** [comment]
Side note, I was looking at your sample application and you should separate Debug/Release from environments Development, Staging, Production. You might want to use an environment setting to switch on ForceSSL versus doing it during Development. That's not the same as *compiling* in debug or release mode.

**Comment by Sharpiro** [comment]
I am using Beta7 and that is definitely what is being used.

I'm not familiar with doing things that way, do you have an example I could see to understand how to set that up and to see what the benefits are?

**Comment by vncastanheira** [comment]
+1

**Comment by Sharpiro** [comment]
This seems to be working now in Azure and IIS 10.
