### ISSUE TITLE
Any way to ignore certain build warnings in project.json?

### ISSUE THREAD

**Issue by Daniel15** [aspnet/Home#900]
Is there any way to specify individual build warnings to ignore in package.json's `compilationOptions`? In csproj files this can be done with the `<NoWarn>` element (labelled as "Suppress warnings" in Visual Studio)

**Comment by dougbu** [comment]
@Daniel15 yes...
``` json
{
    "compilationOptions": {
        "warningsAsErrors": true
    }
}
```

**Comment by dougbu** [comment]
... or `false` of course.

**Comment by Daniel15** [comment]
@dougbu - I did know about that option and usually use it, but I just want to totally ignore specific build warnings (more specifically, CS7035). With csproj files, you can either add `<NoWarn>7035</NoWarn>` to the csproj or pass it to MSBuild via `/p:NoWarn=7035`.

**Comment by dougbu** [comment]
@Daniel15 sorry I misinterpreted your request. Nothing exists at the moment. This would be a straight-up enhancement to the `ICompilerOptions` properties DNX supports.

**Comment by Eilon** [comment]
Looking at the [sources codes](https://github.com/aspnet/dnx/blob/16bb23bf107d961c1a47e94173ed153b4fc11108/src/Microsoft.Dnx.Runtime/Compilation/CompilerOptions.cs) this indeed seems unsupported.

Can you log a new feature request in the DNX repo?

**Comment by Daniel15** [comment]
Thanks, cross-posted to https://github.com/aspnet/dnx/issues/2693

**Comment by Eilon** [comment]
Thanks!
