### ISSUE TITLE
dnu publish fails with System.IO.PathTooLongException

### ISSUE THREAD

**Issue by sameerkattel** [aspnet/Home#902]
I created a asp.net 5 mvc application project with the template that comes with Visual Studio 2015. 
But when trying to run dnu publish getting below exception. 

> Using Package dependency
> Microsoft.AspNet.PageExecutionInstrumentation.Interfaces 1.0.0-beta5
> Adding NuGet package
> C:\Users\sam.dnx\packages\Microsoft.AspNet.PageExecutionInstrumentation.Interfaces\1.0.0-beta5\Microsoft.AspNet.PageExecutionInstrumentation.Interfaces.1.0.0-beta5.nupkg
> to C:\Users\sam\Documents\Visual Studio
> 2015\Projects\WebApplication\src\WebApplication\bin\output\approot\packages
> Installing
> Microsoft.AspNet.PageExecutionInstrumentation.Interfaces.1.0.0-beta5
> System.IO.PathTooLongException: The specified path, file name, or both
> are too long. The fully qualified file name must be less than 260
> characters, and the directory name must be less than 248 characters.  
> at System.IO.PathHelper.GetFullPathName()    at
> System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32
> maxPathLength, Boolean expandShortPaths)    at
> System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32
> maxPathLength)    at System.IO.FileStream.Init(String path, FileMode
> mode, FileAccess access, Int32 rights, Boolean useRights, FileShare
> share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES
> secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath,
> Boolean checkHost)    at System.IO.FileStream..ctor(String path,
> FileMode mode, FileAccess access, FileShare share, Int32 bufferSize,
> FileOptions options, String msgPath, Boolean bFromProxy, Boolean
> useLongPath, Boolean checkHost)    at
> System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean
> checkHost)    at System.IO.StreamWriter..ctor(String path, Boolean
> append, Encoding encoding, Int32 bufferSize, Boolean checkHost)    at
> System.IO.File.InternalWriteAllText(String path, String contents,
> Encoding encoding, Boolean checkHost)    at
> System.IO.File.WriteAllText(String path, String contents)    at
> Microsoft.Framework.PackageManager.NuGetPackageUtils.<>c__DisplayClass0_0.<<InstallFromStream>b__0>d.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---    at
> System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task
> task)    at
> System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
> task)    at
> Microsoft.Framework.Runtime.Internal.ConcurrencyUtilities.<ExecuteWithFileLocked>d__2`1.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---    at
> System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task
> task)    at
> System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
> task)    at
> Microsoft.Framework.PackageManager.NuGetPackageUtils.<InstallFromStream>d__0.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---    at
> System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task
> task)    at
> System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
> task)    at
> Microsoft.Framework.PackageManager.Packages.AddCommand.<Execute>d__1.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---    at
> System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task
> task)    at
> System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
> task)    at
> Microsoft.Framework.PackageManager.Publish.PublishPackage.Emit(PublishRoot
> root)    at
> Microsoft.Framework.PackageManager.Publish.PublishRoot.Emit()    at
> Microsoft.Framework.PackageManager.Publish.PublishManager.Publish()   
> at
> Microsoft.Framework.PackageManager.PublishConsoleCommand.<>c__DisplayClass0_0.<Register>b__1()
> at
> Microsoft.Framework.Runtime.Common.CommandLine.CommandLineApplication.Execute(String[]
> args)    at Microsoft.Framework.PackageManager.Program.Main(String[]
> args)
> --- End of stack trace from previous location where exception was thrown ---    at
> System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()    at
> Microsoft.Framework.Runtime.Common.EntryPointExecutor.Execute(Assembly
> assembly, String[] args, IServiceProvider serviceProvider)    at
> dnx.host.Bootstrapper.RunAsync(List`1 args, IRuntimeEnvironment env)  
> at dnx.host.RuntimeBootstrapper.ExecuteAsync(String[] args)

**Comment by Asesjix** [comment]
Hi @mokchhya, The problem here is with Windows, there's a restrictions at the length of file names.
https://en.Wikipedia.org/wiki/filename#Length_restrictions

You can easily solve the problem in which you move your project E.g. to "C:\Repos\MyProjekt".

**Comment by benaadams** [comment]
Publish with an ```--out``` parameter pointing at a shorter path rather than publishing to the project's ```bin\output``` folder which is the default

**Comment by mqueirozcorreia** [comment]
You can edit the file *.pubxml and add this tag:
<PublishTempFolderName>pubtmp</PublishTempFolderName>

Solution reference:
https://github.com/Microsoft/dotnet/issues/234

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
