### ISSUE TITLE
Possibility to add dependency using git repository URI

### ISSUE THREAD

**Issue by Alber70g** [aspnet/Home#905]
Is it, or would it be possible in the future, to reference dependencies using a git URI instead of a nuget package? 

For example `project.json`:

``` json
{
    "dependencies": {
        "Company.Service.Framework": {
            "version": "1.0.0-*",
            "sources": "git+http://company.visualstudio.com/DefaultCollection/_git/ServiceFramework#<version>"
        }
    }
}
```

**Comment by Tratcher** [comment]
`dnu sources` enables something like this. https://github.com/aspnet/Announcements/issues/46

**Comment by Alber70g** [comment]
This is not really what we need. What I mean is It more like a replacement for NuGet so that we don't need to setup our private NuGet-server. 

`dnu sources` still needs a dependency to be resolved using a NuGet package + server, and then (when it contains the `repository`) you can do `dnu sources`. We're looking for a dependency resolver in a 'git only' way.

This is a great example of how to do this: https://docs.npmjs.com/files/package.json#git-urls-as-dependencies

**Comment by Tratcher** [comment]
Your other supported alternative is to just clone the dependent repo and then add a reference to it in your global.json file.

**Comment by Eilon** [comment]
This is something that Paket supports, though NuGet (and thus DNX/DNU) does not.

There are no plans to support this at this time.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
