### ISSUE TITLE
Publish *.pdb files for each repository

### ISSUE THREAD

**Issue by vncastanheira** [aspnet/Home#906]
Because changes in beta packages usually breaks your app, it's hard to fix without proper debugging information.
If possible, it would be great to download the *.pdb files of each Asp.Net repo.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
