### ISSUE TITLE
Installation of KRE fails on Linux due to missing "unzip" but appears as succeeded

### ISSUE THREAD

**Issue by ahmetalpbalkan** [aspnet/Home#91]
I'm running on an Ubuntu Linux where `unzip` package is not installed. `kvm upgrade` **silently fails** (does not actually return a non-zero exit code, therefore appears as success) with error saying `unzip` is not installed, however it appears on `kvm list` result and when I try to `kvm use default` it, fails with a weird error:

```sh
root@0c1aec165d3b:/tmp/aspnet-home# ./kvminstall.sh && kvm upgrade && echo Success
Downloading kvm as script to '//.kre/kvm'

=> Source string already in //.bash_profile
Type 'source //.kre/kvm/kvm.sh' to start using kvm
Determining latest version
1.0.0-alpha3-10040
Downloading KRE-mono45-x86.1.0.0-alpha3-10040 from https://www.myget.org/F/aspnetvnext/api/v2
Installing to //.kre/packages/KRE-mono45-x86.1.0.0-alpha3-10040
KVM Needs unzip to proceed.
Cannot find KRE-mono45-x86.1.0.0-alpha3-10040, do you need to run 'kvm install 1.0.0-alpha3-10040'?
Setting alias 'default' to 'KRE-mono45-x86.1.0.0-alpha3-10040'
Success
```

So as you see, there's an error but it still prints success. Now if I run `kvm list` it shows:

```sh
root@0c1aec165d3b:/tmp/aspnet-home# kvm list
KRE-mono45-x86.1.0.0-alpha3-10040 *
```

and `kvm use default` fails although the so-called installed KRE is default according to the listing above (the asterisk?), error message here is a bit weird:

```sh
root@0c1aec165d3b:/tmp/aspnet-home# kvm use default
Cannot find KRE-mono45-x86.1.0.0-alpha3-10040, do you need to run 'kvm install default'?
```

Anyway, it took me a while to see the error, because the error was not the last message in `kvm upgrade`. So when I have `unzip` package on the system, things worked fine.

```sh
root@0c1aec165d3b:/tmp/aspnet-home# apt-get -qqy install unzip && ./kvminstall.sh && kvm upgrade && kvm use default && echo Success
Downloading kvm as script to '//.kre/kvm'

=> Source string already in //.bash_profile
Type 'source //.kre/kvm/kvm.sh' to start using kvm
Determining latest version
1.0.0-alpha3-10040
Downloading KRE-mono45-x86.1.0.0-alpha3-10040 from https://www.myget.org/F/aspnetvnext/api/v2
Installing to //.kre/packages/KRE-mono45-x86.1.0.0-alpha3-10040
Adding //.kre/packages/KRE-mono45-x86.1.0.0-alpha3-10040/bin to process PATH
Setting alias 'default' to 'KRE-mono45-x86.1.0.0-alpha3-10040'
Adding //.kre/packages/KRE-mono45-x86.1.0.0-alpha3-10040/bin to process PATH
Success
```

The bug here is, even while `unzip` is missing the KRE appears as installed and is listed in `kvm list`.

**Comment by Praburaj** [comment]
`kvm` scripts are updated in the home repo. Check for `unzip` was added to `kvm.sh` already. This should be fixed with the latest `kvm.sh`.
