### ISSUE TITLE
CORS error when doing a jQuery POST on ASP.NET 5 API

### ISSUE THREAD

**Issue by rzachariah** [aspnet/Home#910]
Hi,

I have an ASP.NET 5 Web API running in a docker container and deployed here.

http://turbine.ezecloud.net/api
http://turbine.ezecloud.net/api/orders

I can hit the API directly from CURL or the Swagger help page, but I'm not able to do a jquery POST from my web app, like so.

            var payload = { Symbol: "UBER", Side: "BUY", Amount: 200 }; 
            var resultDiv = $("#resultDivContainer");
            $.ajax({
                url: "http://turbine.ezecloud.net/api/orders",
                type: "POST",
                data: JSON.stringify(payload),
                contentType: "application/json",
                dataType: "json",
                success: function (result) {
                    switch (result) {
                        case true:
                            console.log("Success!!! " + result);
                            break;
                        default:
                            resultDiv.html(result);
                    }
                },
                error: function (xhr, ajaxOptions, thrownError) {
                console.error("ERROR status: " + xhr.status);
                console.error("thrown error: " + thrownError);
                    }
                 });

Here's the error I see in the console.log:

OPTIONS http://turbine.ezecloud.net/api/orders n.ajaxTransport.k.cors.a.crossDomain.send @ jquery.min.js:4n.extend.ajax @ jquery.min.js:4ticketWidget.controller.$scope.placeStagedOrder @ ticketWidget.js:203fn @ VM10441:4ngEventDirectives.(anonymous function).$rootScope.compile.element.on.callback @ angular.js:23090parent.$get.Scope.$eval @ angular.js:15719parent.$get.Scope.$apply @ angular.js:15818(anonymous function) @ angular.js:23095n.event.dispatch @ jquery.min.js:3n.event.add.r.handle @ jquery.min.js:3
(index):1 XMLHttpRequest cannot load http://turbine.ezecloud.net/api/orders. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:4000' is therefore not allowed access. The response had HTTP status code 400.

What is the proper way to enable an asp.net vnext Web API for wide open CORS access?

I tried adding the following to my Startup .Configure method, but no dice.

            app.Use(async (context, next) =>
            {
                context.Response.Headers.Add("Access-Control-Allow-Origin", new[] { "*" });
                context.Response.Headers.Add("Access-Control-Allow-Headers", new[] { "*" });
                context.Response.Headers.Add("Access-Control-Allow-Methods", new[] { "*" });
                await next();
            });

This is my complete Startup class:

    public class Startup
    {
        // For more information on how to configure your application, visit http://go.microsoft.com/fwlink/?LinkID=398940
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddMvc();
            services.AddSingleton<IOrdersRepository, OrdersRepository>();
            services.AddSwagger(c =>
           {
               c.SwaggerGeneratorOptions.SingleApiVersion(new Info
               {
                   Version = "v1",
                   Title = "Turbine",
                   Description = "An orders posting service. Post orders like a boss.",
                   TermsOfService = "Some carefully considered terms ..."
               });
           });
        }

        public void Configure(IApplicationBuilder app)
        {
            app.UseMvc();
            app.Use(async (context, next) =>
            {
                context.Response.Headers.Add("Access-Control-Allow-Origin", new[] { "*" });
                context.Response.Headers.Add("Access-Control-Allow-Headers", new[] { "*" });
                context.Response.Headers.Add("Access-Control-Allow-Methods", new[] { "*" });
                await next();
            });
            app.UseSwaggerUi("api");
            app.UseSwagger("{apiVersion}");
            app.UseWelcomePage();
        }
    }

Thanks.

**Comment by GuardRex** [comment]
I didn't see those headers in the response. Try moving the headers `app.Use(...)` above the `app.UseMvc()`?

**Comment by rzachariah** [comment]
I resolved my issue following this guidance:
http://stackoverflow.com/questions/31942037/how-to-enable-cors-in-asp-net-5

Here's what my Startup class looks like now.

        public void ConfigureServices(IServiceCollection services)
        {
            services.AddCors();
            services.ConfigureCors(options =>
                                    options.AddPolicy("AllowAll", p => p.AllowAnyOrigin()
                                                                        .AllowAnyMethod()
                                                                        .AllowAnyHeader()));
            services.AddMvc();
            services.AddSingleton<IOrdersRepository, OrdersRepository>();
            services.AddSwagger(c =>
           {
               c.SwaggerGeneratorOptions.SingleApiVersion(new Info
               {
                   Version = "v1",
                   Title = "Turbine",
                   Description = "An orders posting service. Post orders like a boss.",
                   TermsOfService = "Some carefully considered terms ..."
               });
           });
        }

        public void Configure(IApplicationBuilder app)
        {
            app.UseCors("AllowAll");
            app.UseMvc();
            app.UseSwaggerUi("api");
            app.UseSwagger("{apiVersion}");
            app.UseWelcomePage();
        }
    }

**Comment by NeelBhatt** [comment]
This may help you:

https://neelbhatt40.wordpress.com/2015/09/10/what-is-cors-and-how-to-enable-it-in-asp-net-5vnext/

**Comment by Eilon** [comment]
@kichalla any thoughts on this?

**Comment by Eilon** [comment]
Looks like this issue is resolved.
