### ISSUE TITLE
Microsoft.AspNet.Authentication.OAuthBearer Error on Use

### ISSUE THREAD

**Issue by Sharpiro** [aspnet/Home#911]
```
app.UseOAuthBearerAuthentication();
Microsoft.AspNet.Authentication.OAuthBearer
```
When using the method above from the assembly above, I get the following error: 
```
Method not found: 'Void Microsoft.Framework.OptionsModel.ConfigureOptions`1.set_Name(System.String)'.
```

It seems to occur if any of the following are referenced, regardless of whether it is being "added" or "used" in startup.

```
"Microsoft.AspNet.Mvc": "6.0.0-beta8-15649"
"Microsoft.AspNet.Authentication": "1.0.0-beta8-15595"
and more...
```

**Comment by davidfowl** [comment]
You simply have a dependency mismatch. Picking individual versions is a recepie for disaster as you'd have to know what build they all came from. Unless you have a good strategy for picking I'd recommend using *

**Comment by Sharpiro** [comment]
I installed the latest CLR build to "1.0.0-beta8-15594".

From an empty project my only dependencies are:

```
"Microsoft.AspNet.Mvc": "6.0.0-beta8*",
"Microsoft.AspNet.Server.IIS": "1.0.0-beta8*"
```

Microsoft.AspNet.Mvc still seems to be breaking something:

```
Method 'get_ServerFeatures' in type 'Microsoft.AspNet.Builder.Internal.ApplicationBuilder' from assembly 'Microsoft.AspNet.Http, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
```

**Comment by Tratcher** [comment]
You should only be seeing mismatches like that if you're restoring from the volatile feed during a breaking change. That said, that change was made two weeks ago. Try `dnu restore --no-cache`.

**Comment by Sharpiro** [comment]
I found a way to go happily back to Beta 7, so I'll take your guys' word for it.

**Comment by kirk-marple** [comment]
After the beta 8 release, Microsoft.AspNet.Authentication.OAuthBearer still appears only as beta7 on nuget.org package source.  All the other related packages are marked as beta8.

Was there an issue with this package not being publically released for beta8?

**Comment by Tratcher** [comment]
It was renamed to JwtBearer.

**Comment by kirk-marple** [comment]
Great thanks, I didn't see that listed in the announcements.

https://github.com/aspnet/announcements/issues?q=is%3Aissue+milestone%3A1.0.0-beta8
