### ISSUE TITLE
Sample latest error (1.0.0-beta7 does not occur)

### ISSUE THREAD

**Issue by darioajr** [aspnet/Home#912]
The below error occurs when running the command dnx kestrel 

Error:
An unhandled exception occurred while processing the request.

MissingMethodException: Method 'Compilation.Emit' not found.
Microsoft.AspNet.Mvc.Razor.Compilation.RazorCompilationService.Compile (Microsoft.AspNet.Mvc.Razor.Compilation.RelativeFileInfo file) [0x00000] in <filename unknown>, line 0

Stack Query Cookies Headers
MissingMethodException: Method 'Compilation.Emit' not found.
Microsoft.AspNet.Mvc.Razor.Compilation.RazorCompilationService.Compile (Microsoft.AspNet.Mvc.Razor.Compilation.RelativeFileInfo file) [0x00000] in <filename unknown>
Microsoft.AspNet.Mvc.Razor.Compilation.CompilerCache.GetOrAdd (System.String relativePath, System.Func`2 compile) [0x00000] in <filename unknown>
Microsoft.AspNet.Mvc.Razor.VirtualPathRazorPageFactory.CreateInstance (System.String relativePath) [0x00000] in <filename unknown>
Microsoft.AspNet.Mvc.Razor.RazorViewEngine.LocatePageFromViewLocations (Microsoft.AspNet.Mvc.ActionContext context, System.String pageName, Boolean isPartial) [0x00000] in <filename unknown>
Microsoft.AspNet.Mvc.Razor.RazorViewEngine.GetRazorPageResult (Microsoft.AspNet.Mvc.ActionContext context, System.String pageName, Boolean isPartial) [0x00000] in <filename unknown>
Microsoft.AspNet.Mvc.Razor.RazorViewEngine.FindView (Microsoft.AspNet.Mvc.ActionContext context, System.String viewName) [0x00000] in <filename unknown>
Microsoft.AspNet.Mvc.Rendering.CompositeViewEngine.FindView (Microsoft.AspNet.Mvc.ActionContext context, System.String viewName, Boolean partial) [0x00000] in <filename unknown>
Microsoft.AspNet.Mvc.Rendering.CompositeViewEngine.FindView (Microsoft.AspNet.Mvc.ActionContext context, System.String viewName) [0x00000] in <filename unknown>
Microsoft.AspNet.Mvc.ActionResults.ViewResult+<ExecuteResultAsync>d__24.MoveNext () [0x00000] in <filename unknown>
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x00000] in <filename unknown>
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00000] in <filename unknown>
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00000] in <filename unknown>
System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00000] in <filename unknown>
System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <filename unknown>
Microsoft.AspNet.Mvc.Actions.FilterActionInvoker+<InvokeResultAsync>d__53.MoveNext () [0x00000] in <filename unknown>
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x00000] in <filename unknown>
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00000] in <filename unknown>
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00000] in <filename unknown>
System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00000] in <filename unknown>
System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <filename unknown>
Microsoft.AspNet.Mvc.Actions.FilterActionInvoker+<InvokeResultFilterAsync>d__52.MoveNext () [0x00000] in <filename unknown>
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x00000] in <filename unknown>
Microsoft.AspNet.Mvc.Actions.FilterActionInvoker+<InvokeAllResultFiltersAsync>d__51.MoveNext () [0x00000] in <filename unknown>
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x00000] in <filename unknown>
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00000] in <filename unknown>
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00000] in <filename unknown>
System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00000] in <filename unknown>
System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <filename unknown>
Microsoft.AspNet.Mvc.Actions.FilterActionInvoker+<InvokeResourceFilterAsync>d__46.MoveNext () [0x00000] in <filename unknown>
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x00000] in <filename unknown>
Microsoft.AspNet.Mvc.Actions.FilterActionInvoker+<InvokeAsync>d__41.MoveNext () [0x00000] in <filename unknown>
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x00000] in <filename unknown>
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00000] in <filename unknown>
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00000] in <filename unknown>
System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00000] in <filename unknown>
System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <filename unknown>
Microsoft.AspNet.Mvc.Actions.MvcRouteHandler+<RouteAsync>d__6.MoveNext () [0x00000] in <filename unknown>
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x00000] in <filename unknown>
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00000] in <filename unknown>
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00000] in <filename unknown>
System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00000] in <filename unknown>
System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <filename unknown>
Microsoft.AspNet.Routing.Template.TemplateRoute+<RouteAsync>d__25.MoveNext () [0x00000] in <filename unknown>
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x00000] in <filename unknown>
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00000] in <filename unknown>
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00000] in <filename unknown>
System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00000] in <filename unknown>
System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <filename unknown>
Microsoft.AspNet.Routing.RouteCollection+<RouteAsync>d__9.MoveNext () [0x00000] in <filename unknown>
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x00000] in <filename unknown>
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00000] in <filename unknown>
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00000] in <filename unknown>
System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00000] in <filename unknown>
System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <filename unknown>
Microsoft.AspNet.Builder.RouterMiddleware+<Invoke>d__4.MoveNext () [0x00000] in <filename unknown>
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x00000] in <filename unknown>
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00000] in <filename unknown>
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00000] in <filename unknown>
System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00000] in <filename unknown>
System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <filename unknown>
Microsoft.AspNet.Diagnostics.DeveloperExceptionPageMiddleware+<Invoke>d__6.MoveNext () [0x00000] in <filename unknown>

**Comment by henkmollema** [comment]
I'm running into the same error:

> MissingMethodException: Method not found: `Microsoft.CodeAnalysis.Emit.EmitResult Microsoft.CodeAnalysis.Compilation.Emit(System.IO.Stream, System.IO.Stream, System.IO.Stream, System.IO.Stream, System.Collections.Generic.IEnumerable<Microsoft.CodeAnalysis.ResourceDescription>, Microsoft.CodeAnalysis.Emit.EmitOptions, Microsoft.CodeAnalysis.IMethodSymbol, System.Threading.CancellationToken)`.

at 

```
Microsoft.AspNet.Mvc.Razor.Compilation.RoslynCompilationService.Compile(RelativeFileInfo fileInfo, String compilationContent)
```

```
Microsoft.AspNet.Mvc.Razor.Compilation.CompilerCache.GetOrAdd(String relativePath, Func`2 compile)
Microsoft.AspNet.Mvc.Razor.VirtualPathRazorPageFactory.CreateInstance(String relativePath)
Microsoft.AspNet.Mvc.Razor.RazorViewEngine.LocatePageFromViewLocations(ActionContext context, String pageName, Boolean isPartial)
Microsoft.AspNet.Mvc.Razor.RazorViewEngine.FindView(ActionContext context, String viewName)
Microsoft.AspNet.Mvc.Rendering.CompositeViewEngine.FindView(ActionContext context, String viewName, Boolean partial)
Microsoft.AspNet.Mvc.ActionResults.ViewResult.<ExecuteResultAsync>d__24.MoveNext()
```

**Comment by bjornsallarp** [comment]
I get the exact same error. Running on OSX with mono-clr. Razor views don't work.

**Comment by christiandpena** [comment]
Same here on Ubuntu 14.04. It's a fresh install so no other mono versions are listed by dnvm. I am attempting to run the HelloMvc sample project with no changes. The project builds and runs, but give the error when attempting to view the site.

**Comment by myshark** [comment]
same error with beta8

**Comment by mwijnands** [comment]
HelloMvc gives me the same error when running in a Docker container. While HelloWeb runs without problems in a Docker container.

**Comment by Niranjan89** [comment]
same issue here, found any solution?

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
