### ISSUE TITLE
dnx coreclr/windows universal class library & AllJoyn

### ISSUE THREAD

**Issue by grahamehorner** [aspnet/Home#913]
are there any plans to support hosting/consuming Windows Universal class libraries under the dnx coreclr ? eg. sharing the generated AllJoyn libraries in both Windows Universal applications and dnx coreclr web/console applications?

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
