### ISSUE TITLE
Why the creeping objects and heap with my MvcCore test app?

### ISSUE THREAD

**Issue by GuardRex** [aspnet/Home#915]
Background: I'm choosing which way to go (Middleware vs. MvcCore) with a data processing app that would run fine using either approach, so I'm interested in speed and resource footprint.

Note: For the following examples, there was more "stuff" after the `Stopwatch` is started, which I've pulled for the issue question (not relevant to the question).

Consider this simple middleware (there is only one middleware, so the `RequestDelegate` is ignored) :
```
"dependencies": {
  "Microsoft.AspNet.Server.IIS": "1.0.0-beta6"
},
```
```c#
public class MyMiddleware 
{
    public MyMiddleware(RequestDelegate next) { }

    public async Task Invoke(HttpContext context) 
    {
        var sw = new Stopwatch();
        sw.Start();
        await context.Response.WriteAsync($"Middleware: {sw.ElapsedTicks.ToString()} ticks");
    }
}
```
I make batches of 10 requests to the middleware, and object count and heap are stable:

![middleware](https://cloud.githubusercontent.com/assets/1622880/9797940/acf99454-57c3-11e5-97cd-56390b73fb4e.png)

Consider the following MvcCore version:
```
"dependencies": {
  "Microsoft.AspNet.Mvc.Core": "6.0.0-beta6",
  "Microsoft.AspNet.Server.IIS": "1.0.0-beta6",
  "System.Runtime.Serialization.Primitives": "4.0.10-beta-*"
},
```
```c#
public class MyController 
{
    [HttpGet("/")]
    public string Get() 
    {
        var sw = new Stopwatch();
        sw.Start();
        return $"MvcCore: {sw.ElapsedTicks.ToString()} ticks";
    }
}
```
I make batches of 10 requests to the MvcCore version, and I'm getting building objects and heap:

![mvccore1](https://cloud.githubusercontent.com/assets/1622880/9798290/a3969b12-57c5-11e5-8f8f-119a1b003312.png)
![mvccore2](https://cloud.githubusercontent.com/assets/1622880/9798293/a5c58628-57c5-11e5-856a-6476664cd97a.png)

- Just My Code is enabled for these tests
- These are "Release" configs
- Running IIS Express
- dnx-coreclr-win-x64.1.0.0-beta6
- Win10 & VS 2015
- dnxcore50 only apps

~900 objects and ~36K are no big deal, but how about after a million requests ... not good if that keeps going. What's the story on this?

**Comment by pranavkm** [comment]
cc @rynowak

**Comment by GuardRex** [comment]
It occurs to me that maybe this is just a garbage collection thing, but it'll be cool to have some feedback to that effect if that's the case.

**Comment by rynowak** [comment]
If you're using the VS tool to display this, you will see garbage collection shown on the timeline. 

Example:
https://i-msdn.sec.s-msft.com/dynimg/IC724175.png

I would **not** expect a GC to occur after only 20 requests. If you want to be sure, try adding an other action that triggers a GC manually.

**Comment by GuardRex** [comment]
@rynowak Thanks. Will do.

It's interesting that the middleware approach is so object and heap stable. It'll be cool if that turns out to be the case with the full app. I'll build it both ways and load test properly to determine which way I want to go with it.

Thanks again.
