### ISSUE TITLE
Does Microsoft.AspNet.Server.WebListener (WebListener) works also on Linux.

### ISSUE THREAD

**Issue by paulvanbladel** [aspnet/Home#919]
I have a demo aspnet5 beta 7 project running both on windows and linux and I'm quite excited about this.
* On windows, i can use both iis express as well as self hosting via "Microsoft.AspNet.Server.WebListener". 
So I have a command called web
"web": "Microsoft.AspNet.Hosting --config hosting.ini",

* On  linux, Kestrel is working as well, but I want now to use on linux also that web command.

Is that possible anyhow ? Or will it be supported later ?

**Comment by davidfowl** [comment]
Nope, it's windows specific. Kestrel is the main server. Watch the latest community stand up for more information. https://www.youtube.com/watch?v=tQC7P6n3pqk&list=PL0M0zPgJ3HSftTAAHttA3JQU4vOjXFquF&index=0 

We're going to be dropping WebListener and Helios in favor of Kestrel.

**Comment by paulvanbladel** [comment]
Ok. That's very clear. Thanks David.
