### ISSUE TITLE
Any chance that KVM Setup (or something else) edits Nuget Package Sources?

### ISSUE THREAD

**Issue by julielerman** [aspnet/Home#92]
I had some wierd dependency issues that turned out to be because nuget.org was unchecked in my NuGet Package Source settings. I don't recall turning that off and I know that until very recently, I've been getting current packages (for non vnext projects) from NuGet.

At the same time I noticed something else odd. I had added a source for the nightly builds myself. But in addition to nuget.org being unchecked, i noticed that there is now an AspNetVNext source which duplicates the one I created. Here's a screenshot (after I re-checked nuget.org.)
![image](https://cloud.githubusercontent.com/assets/5007120/3399675/42200194-fd3e-11e3-9256-aa07f5341fe6.png)

Is there some scenario (kvm install, grabbing repositories from github, etc) that adds that package source and might also have unchecked nuget.org? If so, it's just been in the last few days that this happened on my machine as I've been fiddling with EF7. :)

**Comment by Praburaj** [comment]
This is a known tooling issue. http://nuget.codeplex.com/workitem/4397

Work around is to add a feed with url `https://nuget.org/api/v2/` in your %appdata%\nuget\nuget.config (I think you will have to edit your %appdata%\nuget\nuget.config directly as tooling may stop you adding a duplicate feed url) and key (something != `Nuget.org`).
