### ISSUE TITLE
Browser Link - Browse With - not honouring launch url of project

### ISSUE THREAD

**Issue by dazinator** [aspnet/Home#920]
I believe this is a bug - I originally raised it on stackoverflow [here](http://stackoverflow.com/questions/32414082/browse-with-not-using-launch-url) but yet to receive a response.

The issue is, when the asp.net project is configured with a "Launch URL" - if you then use the "Browse With" option in VS  to start multiple browsers - those browsers all open up but don't use the Launch Url configured..

**Comment by Eilon** [comment]
@sayedihashimi ?

**Comment by sayedihashimi** [comment]
@billhiebert any thoughts?

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
