### ISSUE TITLE
When removing certain unused dependencies, project is unable to build and find AspNet namespace

### ISSUE THREAD

**Issue by janpieterz** [aspnet/Home#924]
When removing certain dependencies I don't need anymore, the whole project starts missing out on all the other dependencies (it can't find AspNet, Data, Authorize, Controller etc).

This gist shows my project.json
https://gist.github.com/janpieterz/e6970d143ae757eb7806

I currently removed the Microsoft.AspNet.Authentication.Twitter package, but it goes for all packages basically. I don't use Facebook, Google, MicrosoftAccount or Twitter so I thought it nice to remove them all!

As soon as I remove one of them (either through nuget directly, or through removing the line in project.json) the project fails finding any dependencies. As soon as I put it back in, it works again. Nothing in the error list can be found about those specific packages after removal.

Perhaps related (if not I'll open another issue) is exactly the same behavior while installing Microsoft.AspNet.Authentication.OAuthBearer (1.0.0-beta7), basically rendering usage of this package impossible. This does show something else in the references, and in the error list it pops up with:

```
The dependency Microsoft.AspNet.Authentication.OAuthBearer >= 1.0.0-beta7 could not be resolved.
```

and nuget output:

```
Installing NuGet package Microsoft.AspNet.Authentication.OAuthBearer.1.0.0-beta7.
Successfully installed 'Microsoft.AspNet.Authentication.OAuthBearer.1.0.0-beta7' to Intreba.Enm.Web
```

Hopefully I'm not missing something simple but crucial here!

**Comment by davidfowl** [comment]
@janpieterz Does it stay broken? or does it recover?

**Comment by janpieterz** [comment]
@davidfowl it stays broken unless I undo the action that broke it (so removing twitter breaks it, putting it back in solves it, adding OAuthBearer breaks it, removing it solves it).

**Comment by clivingston2** [comment]
With `Microsoft.AspNet.Authentication.Twitter` and similar packages, you need to ensure that those configuration lines are either removed, or commented out in the `startup.cs`.  Then you also will most likely need to run `dnu restore` to resolve the dependencies and recreate the `project.lock.json` file that the application is expecting with the dependencies in the list.

**Comment by janpieterz** [comment]
@clivingston2 thanks, I have found the culprit. Nothing in the startup mentioned those packages.
I have a nuget feed that is accessible only when connected to a VPN (different network, local file share there).
The 'automatic' restore that happened within Visual Studio was unable to handle this, although normal nuget has no problem.

So the issue is a different one, not sure where to file it and how to exactly describe it.
