### ISSUE TITLE
Large bower dependency chain breaks IDE.

### ISSUE THREAD

**Issue by jvrobert** [aspnet/Home#927]
Overall there seem to be a lot of things that hang the IDE briefly, sometimes causing a window redraw "blip" but I've found one way that just kills VS2015 and it won't start at all when loading this solution.
1. Create a new ASP.NET web app (no login/auth) with 'yo aspnet'
2. Do a restore
3. Edit bower.json to contain the below contents
4. Do a bower install (takes a min, but works fine eventually)
5. Open VS2015, load project - won't load, just hangs, offers to send error report, etc...

``` json
{
  "name": "Test1",
  "private": true,
  "dependencies": {
    "bootstrap": "^3.3.5",
    "jquery": "^2.1.4",
    "jquery-validation": "^1.14.0",
    "jquery-validation-unobtrusive": "^3.2.3",
    "jquery-ui": "^1.11.4",
    "underscore": "^1.8.3",
    "alpaca": "1.5.13"
  },
  "resolutions": {
    "jquery": "^2.1.4",
    "bootstrap": "^3.3.5",
    "jquery-ui": "^1.11.4"
  }
}
```

**Comment by Eilon** [comment]
@sayedihashimi @barrytang

**Comment by barrytang** [comment]
@vkichline, can you see if you can repro locally?

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
