### ISSUE TITLE
dnx command line weblistener/kestrel

### ISSUE THREAD

**Issue by grahamehorner** [aspnet/Home#928]
I'm not sure if I'm missing something or if it's possible to even do this; but how would you pass command line parameters to the startup method of a web application? does dnx pass the command line parameters to weblistner/kestrel which then get forwarded to the startup? or are they encapsulated in an object that is accessible like IHostingEnvironment, IApplicationEnvironment or IRuntimeEnvironment?

**Comment by miguellira** [comment]
If you follow the source, it looks like arguments get merged and added to `ConfigurationBuilder`. 

https://github.com/aspnet/KestrelHttpServer/blob/dev/src/Microsoft.AspNet.Server.Kestrel/Program.cs#L21
https://github.com/aspnet/Hosting/blob/dev/src/Microsoft.AspNet.Hosting/Program.cs#L28

In which case, wouldn't it be preferable to use your own `config.json` and add that in `Startup.cs`.

**Comment by grahamehorner** [comment]
The issue I have is that I want to be able to pass to Startup.cs via dnx kestrel host additional command line args at runtime these args are configuration elements supplied by the users and in my case are sensitive information used during initial deployment; which the startup.cs will verify, secures and in an external .json configuration; is ConfigurationBuilder accessible to the DI at application startup? if so how can I get the ConfigurationBuilder injected into the constructor of the Startup.cs?

**Comment by Eilon** [comment]
@grahamehorner sorry I'm not exactly following. There's a CommandLine configuration provider that you can use: https://github.com/aspnet/Configuration/tree/dev/src/Microsoft.Framework.Configuration.CommandLine

Syntax and usage examples are seen in the unit tests: https://github.com/aspnet/Configuration/blob/dev/test/Microsoft.Framework.Configuration.CommandLine.Test/CommandLineTest.cs

And if you create a ConfigurationBuilder that has that, plus any other config sources, they'll all be merged together (so one can override another).

Would that work for you?

**Comment by miguellira** [comment]
Forgive me, but I don't quite follow. We are talking about `kestrel` here right? Who are the users? Aren't you just configuring the startup of a web server?

There are plenty of built-in configuration providers and you can even create your own - though I'd stick with JSON. If these are deployment concerns maybe setting Environment Variables and loading them up in `Startup.cs` is preferable.

In any event, I'd give this read a once over: http://docs.asp.net/en/latest/fundamentals/configuration.html and see if sets you in the right direction. Good luck.

**Comment by grahamehorner** [comment]
@miguellira I'm looking for a way I can supply a asp.net vnext web application with command line args when the web application is hosted via dnx running inside of kestrel.  The users are however is deploying my application in this instance; and yes these are initially startup configuration settings that need to come via the command line args. environment are not an option; these aren't secure.  I want to  be able to read values from the command line args and process these in my web application startup.cs

@Eilon I'm aware of the CommandLine configuration provider, but can't see how I can hook this into the DNX kestrel dependency change to allow the startup.cs to read the commandline args; or if that is even possible? I would have expected DNX -> kestrel -> to pass the commandline args up the callstack in something like IRuntimeEnvironment or IHostingEnvironment

so I started looking at the CommandLine provider; but this looks to require that you need to pass it string[] args? so were do these exist? and where can the startup.cs web application hosted via dnx -> kestrel get access to these commandline args?

**Comment by Eilon** [comment]
@grahamehorner yes you can definitely use the CommandLine config provider, just like all the other config providers that are probably already in your Startup.cs. It looks like on `dnx451` you can do this:

```c#
                .AddCommandLine(Environment.GetCommandLineArgs());
```

But on `dnxcore50` I'm not sure how to get the command line args.

**Comment by grahamehorner** [comment]
@Eilon thanks and what dnx50 -> coreclr ?

**Comment by Eilon** [comment]
@grahamehorner unfortunately I don't think there's a way outside of `Program.Main()` to get the command line args on .NET Core (`dnxcore50`). I recommend logging a bug on https://github.com/dotnet/corefx/issues/ to get it added (I think many people would find it useful).

**Comment by grahamehorner** [comment]
@Eilon given DNX is the host for dnxcore50 and kestrel is called by DNX and supplied the commandline args isn't this an issue with the dnx hosting component (kestrel) implementation not feeding the command line args up the stack in a manner that is platform independent and consistent? not the corefx?

**Comment by grahamehorner** [comment]
@Eilon BTW https://github.com/dotnet/corefx/issues/2413

**Comment by miguellira** [comment]
To some extent, I agree with @grahamehorner. The arguments passed to `kestrel` are currently merged and passed along as an `IConfiguration` down to the `WebHostBuilder` ([see use of _config in this file](https://github.com/aspnet/Hosting/blob/a9e7948d726c1d66dd5a7865ebcb4f60a6ec6c0d/src/Microsoft.AspNet.Hosting/WebHostBuilder.cs#L126-L136)) but never exposed.

However, IMHO exposing an `IConfiguration` by default would result in a more confusing API. Especially, since `.AddCommandLine(Environment.GetCommandLineArgs());` already works in one framework.

**Comment by grahamehorner** [comment]
@mariusGundersen and of course dnx . ef works getting commandline args passed in from the host of the ef code (dnx) on any platform

**Comment by miguellira** [comment]
@grahamehorner Sorry, I'm not sure how your `dnx ef` comment is relevant here. The EntityFramework commands are built around the `CommandLineApplication` API ([see code](https://github.com/aspnet/EntityFramework/blob/dev/src/EntityFramework.Commands/Commands/Program.cs#L44)).

Your requirement - as I understand it - is to allow kestrel to be started with custom arguments and have those arguments exposed in your web application. @Eilon has indicated how this can be accomplished under `dnx451`, but there is no `dnxcore50` option at the moment.

BTW, I know your impetus for this is the security around those configuration values. In case you're not aware, the current recommended approach to secure configuration values is to use [SecretManager](https://github.com/aspnet/Home/wiki/DNX-Secret-Configuration). And @blowdart has already

**Comment by grahamehorner** [comment]
@miguellira the dnx ef comment was about the end user experience; of passing the commandline args  to ef running under coreclr; with regards to SecretManager I understand this is for a deployment use case where we tooling provides secures the sensitive information; I don't know these upfront and the use case is for the end user to use commandline args to supply some configuration element on initial run of the dnx web application that will be persisted in location and secured; basically the web application does the work to initially configure its self; no other tooling should be required or editing of config.json etc.

**Comment by Eilon** [comment]
Ah, I think I did miss one big thing: calling `Environment.GetCommandLineArgs()` isn't quite correct because presumably those are all the arguments passed into `dnx.exe`. But `dnx.exe` presumably "consumed" many of those argument already (e.g. the command name, project path, various other things). And so for your *app's* configuration you only want whatever command line `dnx.exe` *didn't* consume.

That is, say you ran `dnx.exe --project C:\SomePath --debug web p1:Foo p2:Bar p3:Baz`, the config system should see only the `p1:Foo p2:Bar p3:Baz` part (or whatever the syntax is).

So, this is a bit trickier than merely having access to the actual command line args.

@Tratcher any idea if the "remainder" command line args from the true command line are somehow flowed through and could be accessible to a config source?

**Comment by grahamehorner** [comment]
@Eilon I would suggest that given Environment.GetCommandLineArgs() is not a dnxcore50 supported function; that the os native dnx executable passes ALL commandline args to the  Microsoft.AspNet.Hosting which in turn constructs the IHostingEnvironment with the args as this is then available to the startup.cs via dependency injection and therefore can be used by the web app

**Comment by grahamehorner** [comment]
I believe the  Microsoft.Dnx.Host/BootstrapperContext.cs should be changed to hold a list of commandargs; this would allow the RuntimeEnvironment to receive the commandline args with minimal change to the signature of the IRuntimeEnvironment adding a property IList<String> CommandLineArguments { get; }

**Comment by grahamehorner** [comment]
I'll do the change and testing and then issue a PR for review; if you have no objections/observations?

**Comment by davidfowl** [comment]
Yes it shouldn't be DNX specific. It should be added to .net core

**Comment by Tratcher** [comment]
@Eilon The hosting program main args are not directly or indirectly exposed to Startup, just to the servers. Environment variables and config files are the only way to do this at the moment.

**Comment by grahamehorner** [comment]
@davidfowl not sure why it should be in .net core as the entry point is dnx and it's the dnx host that creates the BootstrapperContext; can you explain why the .net should know about the dnx host.clr host.coreclr host.mono its BootstrapperContext

**Comment by davidfowl** [comment]
Because a well know API exists to get command line arguments and it should be brought back. It really isn't DNX specific. Actually a much better way to go about this would be to write your own program.main entry point that uses the hosting API to boot the web app and handle your extra arguments

**Comment by grahamehorner** [comment]
@davidfowl 
> write *your own* program.main entry point that uses the hosting API to boot the web app and handle > your extra arguments 

which is exactly what DNX is; is it not? but it doesn't pass the string args[] to the web app in anyway, but could by simply adding them to the IRuntimeEnvironment with minimum change?

**Comment by Tratcher** [comment]
This issue was moved to aspnet/Hosting#388
