### ISSUE TITLE
Dependency Injection causing circular reference exception with a default constructor defined

### ISSUE THREAD

**Issue by gustyn** [aspnet/Home#929]
When you have a class defined as such:

```
public class Login 
{
     public Login() {}
     public Login(Login login){....}
{
```

a circular reference exception is thrown when you add **services.AddScoped<Login>();** to Startup.cs.  

I got around this by converting to public Login(ILogin login){} but I think the DI should be able to handle this situation.  

Just my 2 cents.

Update:  I did not have this problem until I updated to beta7.

**Comment by davidfowl** [comment]
@gustyn Why do you have circular references? You can also inject IServiceProvider to break cycles but that's a little less nice.

**Comment by gustyn** [comment]
When I have used DI in the past (NInject, Unity) it only kicked in when you had a class without a default constructor such as the Login() {} constructor above.  With the way the new DI injects it will inject for The service injector is using the Login(Login login) instead, so it keeps trying to inject a Login into that constructor which again tries to inject another Login into Login(Login) as well.  Shouldn't the injector use the default constructor instead of the others unless there is a specific request to use the other constructors.

.

**Comment by pranavkm** [comment]
We changed the behavior of how constructor injection works in https://github.com/aspnet/DependencyInjection/issues/69. The fact that it worked in the past was untested \ buggy behavior; we always attempted to initialize the default constructor when a type had more than one public constructor - regardless if it had one.

@gustyn you could register a factory in the DI container instead and new up the type:
`serviceProvider.AddScoped<Login>(provider => new Login());`. This should keep things working as before.

@loudej, is this a pattern we want to support viz. skip constructors where the service type is injecting itself. Seems like it shouldn't be a ser

**Comment by gustyn** [comment]
@pranavkm I like the factory idea.  I just did not realize the issue, and it was driving me batty until I reasoned the problem.  Using the ILogin in this instance, however, is more true to DI since I have control over the code.  The use case of a type with a constructor injecting another instance of the same class is probably fairly small.

Part of me seems like if you have a default constructor, though, you should still default to that.  Is this not how a paramterless Controller is generated?.  I will leave the architecture decisions to the experts, though.  I could easily see the factory approach as an acceptable solution (although less intuitive approach IMHO).

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
