### ISSUE TITLE
HttpConfiguration replacement/use with older libraries

### ISSUE THREAD

**Issue by damienpontifex** [aspnet/Home#930]
Some older libraries utilise `HttpConfiguration` from System.Web and from my research so far, this has been dropped in asp.net 5. 

Just wondering if there is any guidance with how to use older libraries that still depend on `HttpConfiguration` in ASP.NET 5? An example is the Azure Mobile Apps server SDK as can be seen here http://azure.microsoft.com/en-us/blog/updates-to-the-mobile-apps-server-sdk/

Or is it a matter of these libraries being updated and forked to work with the new services/middleware model of ASP.NET 5?

My apologies if this is already documented, but I haven't found any insights from a search so far. Thanks in advance.

**Comment by davidfowl** [comment]
Libraries that worked with ASP.NET need to be updated (potentially forked) for ASP.NET 5. The stack is a group up rewrite. Once ASP.NET 5 ships, libraries will start making ASP.NET 5 versions of their existing libraries (including the mobile apps sdk).

**Comment by damienpontifex** [comment]
Thanks @davidfowl about what I thought. Just wanted to check there wasn't something I was missing, or anything that I could.
