### ISSUE TITLE
missing string constraint

### ISSUE THREAD

**Issue by slofurno** [aspnet/Home#932]
there is no string constraint on the route constraint resolver, and neither the error it produces nor the provided samples make this clear

InvalidOperationException: The constraint entry 'name' - 'string' on the route 'playground/{name:string}' could not be resolved by the constraint resolver of type 'DefaultInlineConstraintResolver'.

**Comment by Eilon** [comment]
Can you log this bug in https://github.com/aspnet/Routing/issues ? That's the place for routing bugs.

Also, please provide at least a minimal code sample of how/when you encounter this error.
