### ISSUE TITLE
docker build fails on Ubuntu 15.04

### ISSUE THREAD

**Issue by davidwincent** [aspnet/Home#933]
Following the instructions at https://github.com/aspnet/Home/blob/dev/GettingStartedDeb.md does not work.

My working copy of HelloWeb is: https://github.com/aspnet/Home/tree/1d06f1f9352e6ce75f0602f19bbcb04b01dc9ccb/samples/latest/HelloWeb
My docker version is: 1.5.0, build a8a31ef
```
sudo docker build -t aspnet-home-helloweb .
```
=>
```
Sending build context to Docker daemon   320 kB
Sending build context to Docker daemon 
Step 0 : FROM microsoft/aspnet
Pulling repository microsoft/aspnet
5d7513d98c09: Error pulling image (latest) from microsoft/aspnet, HTTP code 400 
ba249489d0b6: Download complete 
19de96c112fc: Download complete 
b92a854a78d0: Download complete 
63e9265ef57c: Error pulling dependent layers 
INFO[0011] Error pulling image (latest) from microsoft/aspnet, HTTP code 400
```

**Comment by Eilon** [comment]
Can you log this in https://github.com/aspnet/aspnet-docker/?

**Comment by davidwincent** [comment]
Related: https://github.com/aspnet/aspnet-docker/issues/92

**Comment by Eilon** [comment]
Closing this one, thanks!
