### ISSUE TITLE
Method 'Start' in type 'Microsoft.AspNet.Loader.IIS.RuntimeHttpApplication' from assembly 'Microsoft.AspNet.Loader.IIS, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.

### ISSUE THREAD

**Issue by RavindraMicrosoft** [aspnet/Home#934]
Getting the below error when I installed Entity Framework version 7.0.0-beta7.

Method 'Start' in type 'Microsoft.AspNet.Loader.IIS.RuntimeHttpApplication' from assembly 'Microsoft.AspNet.Loader.IIS, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.

I am using the below versions -
NET Framework version 4.0.30319.42000   |   Microsoft.AspNet.Loader.IIS version 1.0.0-beta5-11951   |   IIS version 10.0.10117.0 (fbl_srv2_iis_dev(sujitn).150512-1839)

**Comment by Asesjix** [comment]
You try that EntityFramework beta 7 in the environment beta 5 to start?
If Yes, have you performed a tooling update for beta7?
https://github.com/aspnet/Home/releases/tag/v1.0.0-beta7

**Comment by Tratcher** [comment]
FYI Microsoft.AspNet.Loader.IIS is obsolete in beta8. See https://github.com/aspnet/Announcements/issues/69
