### ISSUE TITLE
Problems when working with Portable Class Library

### ISSUE THREAD

**Issue by balivo** [aspnet/Home#935]
I'm having some problems when working with Portable Class Library at ASP.NET 5 project using 6.0.0-beta7 release.

When I add a PCL reference to my project, NuGet package is trying to download and don't recognize my PCL project a solution project reference.

I put my PCL project reference at project.json file at "dependencies" node like this:

```
{
    "webroot": "wwwroot",
    "version": "1.0.0-*",

    "dependencies": {
        "Microsoft.AspNet.Diagnostics": "1.0.0-beta7",
        "Microsoft.AspNet.Mvc": "6.0.0-beta7",
        "Microsoft.AspNet.Mvc.TagHelpers": "6.0.0-beta7",
        "Microsoft.AspNet.Server.IIS": "1.0.0-beta7",
        "Microsoft.AspNet.Server.WebListener": "1.0.0-beta7",
        "Microsoft.AspNet.StaticFiles": "1.0.0-beta7",
        "Microsoft.AspNet.Tooling.Razor": "1.0.0-beta7",
        "Microsoft.Framework.Configuration.Json": "1.0.0-beta7",
        "Microsoft.Framework.Logging": "1.0.0-beta7",
        "Microsoft.Framework.Logging.Console": "1.0.0-beta7",
        "Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.0.0-beta7",
        "Microsoft.AspNet.Mvc.WebApiCompatShim": "6.0.0-beta7",
        "<MyPCLProjectNameGoesHere>": "1.0.0-*"
    },
(rest of project.json file)
}
```

Some help?

Tks

**Comment by YZahringer** [comment]
Same problem. Is it possible to reference a PCL assembly in a ASP.NET 5 project?

**Comment by davidfowl** [comment]
What kind of PCL project? What does it target? Also how did you add the reference? Using the VS UI or some other way?

**Comment by balivo** [comment]
I solve the problem including when updating to Beta8...
