### ISSUE TITLE
samples/latest is not really the latest

### ISSUE THREAD

**Issue by ahmetalpbalkan** [aspnet/Home#936]
https://github.com/aspnet/Home/tree/dev/samples/latest

this is not the latest one... the ENTRYPOINT in the dockerfile is simply wrong (pre-beta7).

Please use symlinks to point to the latest and update them in each release... someone already got confused by this mistake: https://github.com/aspnet/aspnet-docker/issues/92

I would like to also remind you that you should have a release document with well defined steps. The human errors around the `samples/` directory is just very frequent. @glennc @danroth27 @Eilon

**Comment by glennc** [comment]
Latest isn't a copy of one of the existing Betas, it is supposed to update as we make breaking changes and then be effectively snapshotted as we do a release, so I'm not sure I understand where symlinks come in. Am I missing something?

**Comment by ahmetalpbalkan** [comment]
@glennc so instead of copying all the contents of `samples/1.0.0-betaN` into `samples/latest` in each release, you can make a symlink and at each release change the symlink to the latest version's directory.

So the current snapshot of `samples/latest` is this: https://github.com/aspnet/Home/tree/615efcc78e813d52b513adb412d8757e9bf011a4/samples/latest It is older than beta7 (hence does not work in beta7 due to breaking changes) and the user at #92 practically got confused by the instructions in the documentation saying "use samples/latest"... If the `samples/latest` directory was indeed "latest" this wouldn't be happening.

**Comment by tlk** [comment]
Have you considered using git branches?

**Comment by ahmetalpbalkan** [comment]
I think folders are easier to navigate and we already have tags for snapshotting purposes. I feel -1 for multile branches as discovering them and navigation is pretty difficult.

**Comment by glennc** [comment]
The copy is supposed to be the other way around. Latest is copied to beta8 when beta8 is released.

Latest is supposed to be maintained as we make breaking changes. So it always works with * dependencies. It doesn't appear that it has been in this release which is really the problem here.

We had branches in the past and it was too confusing for people to navigate. They didn't know what to do. However, latest might be a bad name as well. dev or nightly or something might give more of an idea of its intent.

**Comment by ahmetalpbalkan** [comment]
:+1: also the instructions are saying users should use latest folder to build the docker image, but the base image Dockerfile uses is a stable image (ie previous version) so if there's a breaking change it is very likely users will hit problems if they use "latest" samples. Calling them "nightly" and not sending users there from the documentation is a good idea.

**Comment by glennc** [comment]
I looked at what is required of the Dockerfile for latest and sent a PR with changes I think will work. Can you guys have a look and tell me if I'm crazy?

I can't see how the old Dockerfile would've ever been ok for what latest is.

**Comment by ahmetalpbalkan** [comment]
@glennc looks neat, if you have verified it works, then it should be fine :+1:

**Comment by glennc** [comment]
I run it on my machine. Not sure why we ever did the copy of the project.json then copy the rest and run. That seems less than optimal. I will update the other sample and it should be good.

**Comment by glennc** [comment]
Merged. Closing. Thanks for reporting and talking about this one all :)
