### ISSUE TITLE
Environment variables not set after DNVM installation on Windows Server Core Docker image

### ISSUE THREAD

**Issue by michaldudak** [aspnet/Home#938]
I tried to install DNVM in the windowsservercore-based container (on Windows Server 2016 TP3) using the `https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.ps1` script. The installation completed without errors, however the PATH and DNX_HOME environment variables were not updated.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
