### ISSUE TITLE
Increase workerThreads and completionPortThreads defaults for Helios

### ISSUE THREAD

**Issue by PinpointTownes** [aspnet/Home#94]
The default values for the thread pool seem really low under Helios. I personally get `workerThreads = completionPortThreads = 16` on a _Core i7_ machine with 4 cores and hyper-threading enabled (= 8 cores).

An ASP.NET Web Forms app running IIS Express on the same machine comes with far higher default values: `workerThreads = 4096` and `completionPortThreads = 1000`.

You should consider increasing these values to get rid of these weird exceptions:

> InvalidOperationException: There were not enough free threads in the ThreadPool to complete the operation.

In the meantime, manually calling `ThreadPool.SetMaxThreads` with higher values will do the trick.

**Comment by danroth27** [comment]
See https://github.com/aspnet/Helios/commit/c9be2ee17fd53d81ae75147046306d20cd1aea39 for the new defaults.

**Comment by PinpointTownes** [comment]
@danroth27 this repository is not public yet. That would be cool if you could directly share some of the details here.

**Comment by danroth27** [comment]
```csharp
// When webengine4.dll first starts, it sets the max thread pool size to an artificially low number, and it depends 
// on System.Web.dll to set it back. Since we're replacing System.Web.dll, we need to perform this fixup manually. 
// For now we'll use 100 * numCPUs. 
int newLimits = 100 * Environment.ProcessorCount; // this is actually # cores (including hyperthreaded cores) 
int existingMaxWorkerThreads; 
int existingMaxIocpThreads; 
ThreadPool.GetMaxThreads(out existingMaxWorkerThreads, out existingMaxIocpThreads); 
ThreadPool.SetMaxThreads(Math.Max(newLimits, existingMaxWorkerThreads), Math.Max(newLimits, existingMaxIocpThreads)); 
```
