### ISSUE TITLE
Editing a JSON file results in an exception Visual Studio 2015 RTM

### ISSUE THREAD

**Issue by cveld** [aspnet/Home#941]
Don't know if it has anything to do with the ASP.NET beta stack; currently using beta7 -

I am experiencing an issue when opening / editing JSON files in Visual Studio 2015 RTM. Syntax highlighting is not working. How can I troubleshoot any further?

See below the exception I am getting. Copied from:
C:\Users<my username>\AppData\Roaming\Microsoft\VisualStudio\14.0
Filename: ActivityLog.xml

``` xml
  <entry>
    <record>619</record>
    <time>2015/09/20 12:04:12.299</time>
    <type>Error</type>
    <source>Editor or Editor Extension</source>
    <description>System.NullReferenceException: Object reference not set to an instance of an object.&#x000D;&#x000A;   at Microsoft.JSON.Editor.Validation.JSONErrorTagger..ctor(ITextBuffer textBuffer)&#x000D;&#x000A;   at Microsoft.JSON.Editor.Validation.JSONErrorTagger.Attach(ITextBuffer textBuffer)&#x000D;&#x000A;   at Microsoft.JSON.Editor.Validation.JSONErrorTaggerProvider.CreateTagger[T](ITextBuffer textBuffer)&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.GatherTaggers(ITextBuffer textBuffer)</description>
  </entry>
```

**Comment by Eilon** [comment]
@barrytang @madskristensen can you guys take a look?

**Comment by Asesjix** [comment]
Did you try to start Visual Studio in SafeMode "devenv /SafeMode".
Maybe comes the error by an addon?

**Comment by cveld** [comment]
Yes with /SafeMode the json syntax highlighting works again!

**Comment by Thomassg** [comment]
@cveld I ran into the same issue. Updating the Azure SDK did it for me.

**Comment by cveld** [comment]
@thomassg Currently I have already installed version 2.7.1 of the Azure SDK for .NET (Visual Studio 2015). Still no json syntax completion and the mentioned exceptions.

**Comment by cveld** [comment]
@madskristensen Somehow json syntax completion suddenly started working again. Now I was able to start experimenting with switching on the extensions. I came to the discovery that enabling one of the following two extensions lead to the exception:
* ASP.NET 5 Scripts Task Runner (version 1.0.2);
* NPM Scripts Task Runner (version 1.0.21).

**Comment by gulbanana** [comment]
i have this problem too, and it began when i installed NPM Scripts Task Runner.

**Comment by cabarney** [comment]
Same issue here, though for me it started after installing the "Search in Velocity" extension (https://visualstudiogallery.msdn.microsoft.com/2f45a9f6-e26a-4888-899f-5ed3ef24b37f).  I've uninstalled it, but am still getting the error.

Where are extensions physically installed? Is there something I could look for to ensure a complete removal of the extension?

**Comment by cabarney** [comment]
Yay! I got it working again.

The extension directory is here: C:\Users\{username}\AppData\Local\Microsoft\VisualStudio\14.0\Extensions

I deleted the *.cache files in that directory and everything started working again.  Hope it helps.

**Comment by barrytang** [comment]
Another MEF cache issue it looks like. I will forward this along to the VS MEF team.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
