### ISSUE TITLE
Class library for .Net Core?

### ISSUE THREAD

**Issue by angelsix** [aspnet/Home#942]
I am creating a dnxcore50 ASP.Net project so its totally cross platform.

I now need class libraries.. how do I make dnxcore50 class libraries?

**Comment by Eilon** [comment]
It already *is* a class library, wrapped in a NuGet package. Look inside the NuGet package and you'll see a file `lib/dnxcore50/Some.Project.dll`.

**Comment by angelsix** [comment]
Yes but I need more than one project. I need say a Core, Data, Web, and others. Then the Web project needs to referenc the Core and Data.

So I just created 3 ASP.Net website projects to act as class libraries then reference them somehow? Seems the wrong approach to me. Is there not just a class library for dnxcore?

**Comment by jmlothian** [comment]
The DNXCore 5 friendly class libraries are called "Class Library (Package)" in Visual Studio - not the same as the class library projects you've used before.  You can reference them from DNXCore 5 sites the same way you would reference an old-style class library in a .Net 4.5 site.  In VS, one method to add them is right-click the site, add ->  reference, and select it from the list or browse.  

If it isn't the solution, you may also have to take the additional step of setting up the project to "produce outputs on build" to find it while browsing (someone correct me if I'm wrong here).

**Comment by Eilon** [comment]
Indeed, as @jmlothian said, there is a "Class Library (Package)" project type in VS that you can use. It's the same basic model: project.json + ProjectName.xproj

![vs-new-class-package](https://cloud.githubusercontent.com/assets/202643/10025042/fde0d63a-610e-11e5-81f0-dd351658b4b9.PNG)

Then from the web app you can reference the class library packages either using VS's Add Reference dialog, or by editing the project.json file.

**Comment by angelsix** [comment]
Perfect. I saw that but wasnt sure if that was the way to go. Thanks for confirming.
