### ISSUE TITLE
IServiceCollection AddCaching() is missing

### ISSUE THREAD

**Issue by markentingh** [aspnet/Home#943]
I upgraded from beta5 to beta7, and the only error I'm recieving now is with `services.AddCaching()` here in `Startup.cs`:

    public void ConfigureServices(IServiceCollection services)
        {
            services.AddCaching();
            services.AddSession();
        }

Update: I figured out how to fix this. I had to add a dependency:

`"Microsoft.Framework.Caching.Memory" :  "1.0.0-beta7",`

**Comment by Eilon** [comment]
Yup, gotta add dependencies. It might not have been needed in beta5 if some other package at the time brought in the Caching package as a transitive dependency.

**Comment by kshyju** [comment]
Where did `services.AddSession()` go ? Is it now enabled by default in a web app ? I am sure i had to manually enable it in a previous version ( don't remember which one :( ) 

Looks like the Session samples project still has the code to call `AddSession` method. https://github.com/aspnet/Session/blob/dev/samples/SessionSample/Startup.cs#L37

**Comment by Jeffiy** [comment]
@kshyju You should add `"Microsoft.AspNet.Session": "1.0.0-*"` dependency.

**Comment by smbecker** [comment]
@kshyju, do you have a dependency on Microsoft.AspNet.Session? The extension methods are defined there.

**Comment by kshyju** [comment]
My bad ! I had those and removing those from dependency section  and re-adding fixed it. Stupid VS !
