### ISSUE TITLE
vnext .xproj support for ReSharper Command Line Tools

### ISSUE THREAD

**Issue by leak** [aspnet/Home#944]
This is not an actually issue and rather a pointer for people running into the same question.

https://www.jetbrains.com/resharper/features/command-line.html

Currently ReSharper Command Line Tools do not support .xproj projects and everything behind it. If you are interested in having support for future ASP vnext projects you can upvote the implementation here:

https://youtrack.jetbrains.com/issue/RSRP-448115

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
