### ISSUE TITLE
How to compile unsafe code

### ISSUE THREAD

**Issue by GuardRex** [aspnet/Home#945]
.NET 4.x has the "Allow unsafe code" checkbox in Build properties. I guess it adds "/unsafe" to the compile arguments.

For a dnxcore50 project, I see "Application Arguments" in properties, but it doesn't seem to respect "/unsafe" there.

How do we (can we) allow unsafe code?

**Comment by davidfowl** [comment]
http://docs.asp.net/en/latest/dnx/projects.html#compilation-settings

**Comment by GuardRex** [comment]
Awesome ... thanks!
