### ISSUE TITLE
The `project.json` file is nameless (`a project with no name`) and it could be documented

### ISSUE THREAD

**Issue by peterblazejewicz** [aspnet/Home#946]
At the very moment there is an effort to add a feature for `generator-aspnet` to support namespace generation for ad-hoc content added to pre-existing scaffolded applications (like adding a view to scaffolded MVC application - think 'add new item` in VS):
https://github.com/OmniSharp/generator-aspnet/pull/366

I think there is an omission in `project.json` - or otherwise it should be documented - as `project.json` has no key to denote its own name/namespace. The very basic pattern for similar files is to have some key/identifier that allows to read a project name from configuration file. 
Let me use NPM as an example:

```
npm init
```

The very first question it asks is a project `name`:

> The most important things in your package.json are the name and version fields.

https://docs.npmjs.com/files/package.json

In case of ASP.NET 5 projects one has to guess the implementation pattern based on %project:name% variable:
https://github.com/aspnet/dnx/blob/a9e12d2ff1837bff36384402345ba8f74d8cfacb/src/Microsoft.Dnx.Tooling/ProjectResolver.cs
or by looking how NuGet package ID gets generated by `dnu pack` (I haven't checked source code for DNX tools yet).

I could be missing something but at least I think the pattern to regenerate project name should be documented somehow:
https://github.com/aspnet/Home/wiki/Project.json-file

Thanks!

**Comment by peterblazejewicz** [comment]
I've missed a line that is very important. The NPM docs states exactly why one needs to provide a name:

> The name is what your thing is called.

https://docs.npmjs.com/files/package.json
If `project.json` does not require a name thing (while still following other patterns), we need documentation for this.
Thanks!

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
