### ISSUE TITLE
Visual Studio Code does not report missing Mono

### ISSUE THREAD

**Issue by YEVHENO** [aspnet/Home#947]
@victorhurdugaci 

I run Visual Studio Code on OS X machine without mono installed. I open folder with source code. Then I pick project. Project icon starts blinking. Intellisense in Visual Studio Code does not work.

Probably, Visual Studio Code should should notify that Mono has not been installed.

**Comment by Eilon** [comment]
I sent mail to the VS Code team to take a look.

**Comment by davidfowl** [comment]
@YEVHENO VS code requires mono for now. By the time ASP.NET 5 goes RTM, it won't. Stay tuned for more details.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
