### ISSUE TITLE
Helios does not use configSource on connectionStrings in web.config

### ISSUE THREAD

**Issue by jchannon** [aspnet/Home#95]
If you have something like

    <connectionStrings configSource="connectionStringSource.config"></connectionStrings>

It fails using the Helios host

**Comment by GrabYourPitchforks** [comment]
This issue is now resolved in the Katana-based version pending the next release.

**Comment by PinpointTownes** [comment]
@GrabYourPitchforks out of curiosity, how did you fix this issue? :astonished:

**Comment by GrabYourPitchforks** [comment]
@PinpointTownes IIS's configuration system uses Windows long paths ("\\?\C:\directory\web.config"), but System.Configuration only supports normalized paths and UNC paths when looking at the 'configSource' attribute.  I implemented a small fixup routine to convert back and forth between the two formats.

**Comment by PinpointTownes** [comment]
@GrabYourPitchforks thanks for the details :innocent:

**Comment by dongkaifei** [comment]
111
