### ISSUE TITLE
How to profile CPU usage for my dnxcore50 console app?

### ISSUE THREAD

**Issue by GuardRex** [aspnet/Home#950]
VS2015 RTM, dnx-coreclr-win-x64.1.0.0-beta7
Console App

Debug > Start Diagnostic Tools Without Debugging...
Analysis Target > Performance Wizard checked > Start
CPU sampling profiling method selected

... leads to "No launchable projects available to profile in the current application" and there is no .exe (other than dnx.exe perhaps)

How do I set the application to profile?

**Comment by yellowsix** [comment]
Even though this is closed, I'm having some trouble with it as well. I was able to get profiling to run by browsing to the dnx.exe executable directly and providing the proper arguments to start my DNX console application. Profiling only partly works... it is missing the Function Code View, which I find very helpful.
