### ISSUE TITLE
The aspnetvnext feed not updates for 2 days. Is it depreciated?

### ISSUE THREAD

**Issue by mikeandersun** [aspnet/Home#952]
I change my feeds to https://www.myget.org/gallery/aspnetcidev . But there is many issues.

**Comment by NTaylorMullen** [comment]
Hah, nope. Not deprecated, we've just been doing a lot of work to get new good packages pushed out to it. Stay tuned! :smile:

**Comment by Eilon** [comment]
Indeed, we recently did a lot of renames and big changes that cause signed builds to be delayed, but it's on top of our priority list to get the builds out. `aspnetvnext` is definitely the right feed to use.
