### ISSUE TITLE
Problem in restoring the package asp.net on raspbian linux

### ISSUE THREAD

**Issue by rootonecz** [aspnet/Home#953]
Hello!
I have a problem during the restore of of the package inside the file project.json to Rapsberry Pi.
After entering an order dnu restore ~/www/wifigate/. I get the console voice message - Segmentation Fault.
I am sending the code, which is in the file -

``` json
{
  "dependencies": {
      "Kestrel": "1.0.0-beta7",
      "Microsoft.AspNet.Diagnostics": "1.0.0-beta7",
      "Microsoft.AspNet.Hosting": "1.0.0-beta7",
      "Microsoft.AspNet.Server.WebListener": "1.0.0-beta7",
      "Microsoft.AspNet.StaticFiles": "1.0.0-beta7"
  },
  "frameworks": {
      "dnx451": { },
      "dnxcore50": { },
  },
  "commands": {
      "kestrel": "Microsoft.AspNet.Hosting --server Kestrel --server.urls http://localhost:5004"
  }
}
```

Do you know where could be the problem? Thx

**Comment by Eilon** [comment]
@moozzyk @BrennanConroy thoughts?

**Comment by moozzyk** [comment]
We don't have arm version of runtime for Linux. I was able to build dnx once but could not find a working  version of CoreClr. I couldn't use Mono either as the runtime since the newest version of Mono available was 3.* and we need 4.*. 
@rootonecz - out of curiosity - is it Raspberry Pi or Raspberry Pi 2

**Comment by rootonecz** [comment]
@moozzyk it is a model of the first generation

**Comment by moozzyk** [comment]
@rootonecz - yeah. When I tried I used the first generation too. I even thought about compiling CoreClr myself but the latest version of the compiler available was lower that the min version required by CoreClr. Anyways, for now you unfortunately won't be able to run ASPNet 5 on Raspberry Pi.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
