### ISSUE TITLE
Deploy only for .NET framework, not .NET Core,

### ISSUE THREAD

**Issue by miker1423** [aspnet/Home#954]
I'm writing an API using ASP.NET 5, the problem here is that locally I can just ignore the errors that the compiler throws when compiling some third party libraries that aren't available for .NET Core, how can I ignore those errors? because when trying to deploy to Azure, it just stops after the compiling errors appear.

thanks for your help!

**Comment by Eilon** [comment]
You can remove `dnxcore50` (and everything in it) from your `project.json` to avoid compiling for .NET Core.

**Comment by miker1423** [comment]
thank you so much! haha I'm a noob with ASP.NET 5
