### ISSUE TITLE
How to isolate controllers from other assemblies

### ISSUE THREAD

**Issue by erickgirard** [aspnet/Home#956]
I'm trying to create an autonomous MVC middleware (say an admin area for example) that will be mounted on a route (something like [portable areas](http://elegantcode.com/2012/04/06/mvc-portable-areas/)).

Is there currently a way that the main assembly will not auto-discover controllers from dependent assemblies ?

**Comment by Eilon** [comment]
@rynowak any ideas on this?

**Comment by pranavkm** [comment]
You could look at using `https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.Core/Infrastructure/StaticAssemblyProvider.cs`. We use it in Mvc's functional tests to do limit the scope of assemblies Mvc scans for controller types:

https://github.com/aspnet/Mvc/blob/dev/test/Microsoft.AspNet.Mvc.FunctionalTests/MvcTestFixture.cs#L120-L122

**Comment by rynowak** [comment]
The suggestion from @pranavkm will let you setup an MVC instance that only looks in specified assemblies for controllers.

There's currently no supported way to host two or more separate instances of MVC in the same app.

**Comment by erickgirard** [comment]
Hum, maybe not ideal for the moment but I'll work around that factor. I hope it could be considered for future releases :smile:

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
