### ISSUE TITLE
How to

### ISSUE THREAD

**Issue by gvx111** [aspnet/Home#958]
How to setting the DNX_NO_MIN_VERSION_CHECK environment variable to 1

**Comment by davidfowl** [comment]
On Windows?

**Comment by gvx111** [comment]
Yes

**Comment by davidfowl** [comment]
There's tons of ways to set it. Did you search online for how to set environment variables on windows?

**Comment by gvx111** [comment]
I must add from Advanced System settings -> Environment Variables after i must add in System Variable? Is it correct way?

**Comment by davidfowl** [comment]
It's a way, I don't recommend disabling the check machine wide unless you actually know what you're doing. If you want to disable it on the command line you can type set `DNX_NO_MIN_VERSION_CHECK=1`. Assuming you understand the consequences.

**Comment by gvx111** [comment]
How set from command line?

**Comment by davidfowl** [comment]
> If you want to disable it on the command line you can type `set DNX_NO_MIN_VERSION_CHECK=1`

**Comment by gvx111** [comment]
oh sorry thank you man :)
