### ISSUE TITLE
Missing CDN file(s)  glyphicons-halflings-regular.woff2

### ISSUE THREAD

**Issue by Anderman** [aspnet/Home#959]
```
http://ajax.aspnetcdn.com/ajax/bootstrap/3.3.3/fonts/glyphicons-halflings-regular.woff2
http://ajax.aspnetcdn.com/ajax/bootstrap/3.3.4/fonts/glyphicons-halflings-regular.woff2
http://ajax.aspnetcdn.com/ajax/bootstrap/3.3.5/fonts/glyphicons-halflings-regular.woff2
```

**Comment by NeelBhatt** [comment]
I guess this is not Asp .Net issue. It is a Bootstrap issue.

https://github.com/twbs/bootstrap/issues/9925

Some solutions:

http://stackoverflow.com/questions/18369036/bootstrap-3-glyphicons-are-not-working

http://stackoverflow.com/questions/29747963/how-to-get-glyphicons-working-in-twitter-bootstrap

http://stackoverflow.com/questions/18245575/bootstrap-3-unable-to-display-glyphicon-properly

**Comment by Anderman** [comment]
I don't think so. 

The CDN of (`https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css`) has no problem downloading this file 

and also bootstrap version 3.3.2 on microsoft cdn `http://ajax.aspnetcdn.com/ajax/bootstrap/3.3.3/fonts/glyphicons-halflings-regular.woff2` 
is available

**Comment by Eilon** [comment]
@rustd can you take a look?

**Comment by Eilon** [comment]
Turns out this issue was already reported and is being investigated. Thanks for the reports!

**Comment by awong1900** [comment]
the cdn link still not work。

**Comment by sheetalPixeluprisin** [comment]
I had the same issue, I added the 

> glyphicons-halflings-regular.woff2

to the root 'fonts' folder, and that just fixed the error. =D
