### ISSUE TITLE
DNU - How do you search for packages?

### ISSUE THREAD

**Issue by sjdixon** [aspnet/Home#960]
Is there a way to search for available packages with DNU/DNX, without having to install them?

Ideally, the search would support some kind of fuzzy matching.
examples:

dnu search xunit
dnu search nunit*
dnu search resharper* (for any packages containing "resharper" in the name)
dnu search MyMadeUpPackage* (which would match MyMadeUpPackage as well as MyMadeUpPackage.ExtraFeatures)

**Comment by Eilon** [comment]
`dnu` doesn't have this built in. But you could go to www.nuget.org to search :smile:

**Comment by Banashek** [comment]
Is there possibly some way to leverage the nuget List command specifying a feed to search?

http://docs.nuget.org/consume/Command-Line-Reference

Looks like the last fallback is using the default nuget feed.

https://github.com/NuGet/NuGet.PackageManagement/blob/b1319fd70ce472c5ba91920a0cc00206205b1369/src/NuGet.CommandLine/Commands/ListCommand.cs

Also if you go to the packages directory in a browser it looks like there might be some way to get a paginated listing

https://www.nuget.org/api/v2/Packages

At the end of that page:

`<link rel="next" href="https://www.nuget.org/api/v2/Packages?$skiptoken='2a486e82.Mega','1.0.0-beta5'" /></feed>`

Just some thoughts.

**Comment by Eilon** [comment]
@yishaigalatzer this is presumably more for your team than mine.

**Comment by yishaigalatzer** [comment]
We do have an API for that already, should be too hard to add to the command line. Please refile on github.com/nuget/home/issues

**Comment by Eilon** [comment]
Closing out this issue.
