### ISSUE TITLE
There is no way to exclude generated files from being auto added to pending changes in TFS

### ISSUE THREAD

**Issue by bab5139** [aspnet/Home#962]
I am using Visual Studio 2015 RTM with ASP.NET 5 Beta 7 and TFS 2015 - TFVC.  I would like to exclude files in wwwroot and typescript generated .js files from being automatically added to the TFS pending changes list.  From the documentation, I should be able to add a .tfignore file into the project folder that will exclude these.  It doesn't seem to matter what rule I add to the file, all files touched will automatically get added to the solution explorer and will be included in the pending changes list ready for commit.  Can anyone confirm that this is an open issue or what can be done to get this working.

**Comment by muratg** [comment]
@bab5139 This doesn't seem to be an ASP.NET 5 issue.   I recommend checking StackOverflow.

**Comment by bab5139** [comment]
I did find one issue on StackOverflow regarding this, but it didn't have a real answer.  Is the automatic addition of files to the project when added to the file system an ASP.NET 5 project template mechanism?  Because a normal c# project does not automatically add files to the project when they are dropped into the directory.  Is it possible that the project template code isn't checking whether the file should be excluded from TFS when it's adding it to the project file tree?  Is the ASP.NET project template code available on GitHub?

**Comment by bab5139** [comment]
I found the issue opened back in march.  https://github.com/aspnet/Tooling/issues/18.  I added a comment there.  Hopefully it will get addressed.  I'm surprised that there isn't more people complaining about this.  I guess at this stage most are using git and gitignore is being respected.

**Comment by bluemmc** [comment]
I also have this error - Can it be a tooling issue with Visual Studio with ASP.NET 5 ?

**Comment by muratg** [comment]
@bluemmc I recommend putting in your repro steps in aspnet/Tooling#18
