### ISSUE TITLE
Bug adding VNext Class Library (Package) to Universal Windows app

### ISSUE THREAD

**Issue by Sharpiro** [aspnet/Home#965]
While testing the ability to use a VNext Class Library (Package) in a Windows 10 (Universal Windows) Application, I encountered a bug.

I created a new Universal Windows App for testing.  I was able to successfully add my VNext class library via Nuget package after providing an  additional dependency for ```"net451"```.

However, despite being successfully added to the universal application, none of the code in the library is accessible, and I am unable to successfully add a ```using``` reference to the library.  I.e., Even though the Nuget package is installed, it seems like it is not.

I tested adding the same VNext library to an "old" style console application and a VNext Console App (Package) via nuget packge and it was able to function correctly.

**Comment by Eilon** [comment]
@Pilchie @ericstj do you guys know the right contact for this?

**Comment by ericstj** [comment]
Looks like an issue with the package layout.  Can you share the folders you have in your nuget package?

**Comment by Sharpiro** [comment]
Nuget package Folder Layout:
```
Lib
    dnx451
    dnxcore50
    net451
_rels
```

Detailed layout:
```
Lib
    dnx451
        VNextTools.Core.dll
        VNextTools.Core.xml
    dnxcore50
        VNextTools.Core.dll
        VNextTools.Core.xml
    net451
        VNextTools.Core.dll
        VNextTools.Core.xml
_rels
    .rels
VNextTools.Core.nuspec
[Content_Types].xml
```

**Comment by ericstj** [comment]
None of those folders apply for Windows 10 (Universal Windows) Application, for that you need uap10.0 (or netcore50 if you don't depend on WinRT surface area).  net451 and dnx451 are redundant if that's the same DLL.  DNX451 will also use NET451 assets.

If those are all the same DLL you could use a single dotnet folder.  

Perhaps reading through my walkthrough (1.1 and 1.2) will help: https://github.com/ericstj/NuGetDocs/blob/ericstj/nuget3samples/NuGet.Docs/Create/nuget3-packages-walkthrough.md.  Sample here: https://github.com/ericstj/Samples/tree/ericstj/nuget3/NuGet3

**Comment by Sharpiro** [comment]
* ```net451``` and ```dnx451``` are not redundant for me.  ```net451``` was necessary in order to add the library as a nuget package to a legacy console application.
* I have added ```netcore50``` to my library's project.json and generated a nuget package. (```uap10.0``` was invalid).  The same issue is still occuring where no code in my library is accessible despite being successfully added.

New Nuget Package Structure:
```
Lib
    dnx451
        VNextTools.Core.dll
        VNextTools.Core.xml
    dnxcore50
        VNextTools.Core.dll
        VNextTools.Core.xml
    net451
        VNextTools.Core.dll
        VNextTools.Core.xml
    win50
        VNextTools.Core.dll
        VNextTools.Core.xml
_rels
    .rels
VNextTools.Core.nuspec
[Content_Types].xml
```
