### ISSUE TITLE
ASP.NET 5 - DNX46 - EF6 - Identity 2.3

### ISSUE THREAD

**Issue by Casimodo72** [aspnet/Home#966]
Hi,
is there any example of how to setup an ASP.NET 5 web project, which operates on DNX46 and uses EF6 + identity 2.3?
Could a project template be added to target this scenario?

I've read that ASP.NET 5 should be able to use existing .NET 4.6 stuff, so I made an experiment and wrapped my existing .NET 4.6 assemblies using "dnu wrap", removed references to EF7 and things compile fine.
Now I'm looking at Startup.ConfigureServices and scratch my head: how do I plug EF6 + Identity 2.3 into this machinery?
The only information I found is a confirmation that it can be done, but we all need to find the light for ourselves (see http://stackoverflow.com/questions/29289731/example-of-using-asp-net-5-mvc-6-with-identity-and-ef-6). Which is nice to know, but doesn't help community-wise. 
Edit: I just realized that the mentioned stackoverflow answer talks about Identity 3, so I'm not sure anymore, that Identity 2.3 can be used at all.

My identity setup is custom. I.e. I have GUIDs for keys and multi-tenant support. I'm ready to adjust it when needed for ASP.NET 5.

I would love to move to ASP.NET 5 already now. I'm aware that it's beta. I think ASP.NET 5 would gain a lot of more testers if there was a visible story for using EF6 + Identity 2.3 out there.

Regards,
Kasimier Buchcik

**Comment by Eilon** [comment]
@HaoK this is in your territory, I believe.

**Comment by HaoK** [comment]
@rustd @divega I don't believe this is going to be a supported scenario (old EF/Identity + new MVC)

**Comment by divega** [comment]
That is correct. ASP.NET 5 + Identity 2.x is not going to work. ASP.NET 5 + Identity 3 + EF6 in the other hand, should be a matter of having an Identity 3 storage provider for EF6. We currently don't have guidance on that but it shoukdn't be hard to get the basics working and I am aware that @cherrydev built a very complete one.

**Comment by Casimodo72** [comment]
I didn't find bridging code in @cherrydev's repos, so I tried this on my own. Actually everything in Microsoft.AspNet.Identity.EntityFramework needs to be re-implemented, which is not much fortunately, because one can copy much of the existing code.
Unfortunately I now have trouble with compilation wrt the wrapped assemblies - not related to this topic. I will report back on weekend when I'll have time again for this experiment.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
