### ISSUE TITLE
The linux link "GettingStartedDeb.md"

### ISSUE THREAD

**Issue by TarekSamirJedi** [aspnet/Home#969]
After following all instructions I couldn't find the file " NuGet.config ".There is nothing like ~/.config/NuGet/NuGet.config to be edited. What is the problem?

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
