### ISSUE TITLE
multiple projects and global.json

### ISSUE THREAD

**Issue by rhires** [aspnet/Home#974]
I followed [this link](http://gavindraper.com/2015/05/20/asp-net-5-multiple-projects-and-global-json/), except that with my project I'm not using ["Src","Test"] as my two project folders. What's interesting is the problem that it creates when I reference one via the dependencies section of the project.json file for either project: it kills all the references for everything. VSCode tells me it can't find the definition of simple things like void. On the other hand, maybe I'm doing the referencing wrong, but I don't know what would be the right way. 

A related note is that the folder structure in the example seems a bit off: I don't see why the Test project is at a higher folder level than the Web project. Shouldn't they be at the same level? Is this only an example from April, and things have changed now? The way this is structured it creates another folder level, which gets in the way.

**Comment by Eilon** [comment]
@rhires can you provide more info on what you've tried and what doesn't work? It would be best if you can upload your project to a GitHub repo so we can take a look.

Though some things have certainly changed since April, the basic concept of having `global.json` point to additional folders hasn't changed in quite a while...

**Comment by rhires** [comment]
I think I may have figured it out. Liberal helpings of "dnu restore" worked a lot of the kinks out. It seems that when it picks up the new dependency, it freaks out, rather than suggesting that I run dnu restore. VSCode recognizes Microsoft related changes, but not custom/local ones...I'll have to test more to be sure of that, though.
