### ISSUE TITLE
Error during publish MVC web app

### ISSUE THREAD

**Issue by ankitvijay** [aspnet/Home#976]
Hi, while trying to publish MVC web app with publish target as "File System", I'm getting a weird error as shown below:
![image](https://cloud.githubusercontent.com/assets/5988564/10337848/16a9eb9e-6d20-11e5-9dee-da6784941c2c.png)
Target DNX version: dnx-clr-win-x86.1.0.0-beta7

Any idea what the issue can be?

**Comment by Eilon** [comment]
Are you sure your DNX matches the versions of the packages you're using? E.g. using beta7 for everything and not some beta8 or rc1 packages or DNXes?

**Comment by ankitvijay** [comment]
I'm sure I was using beta7. I did an upgrade from beta5 to beta7. I feel it was machine specific issue. I was trying to this on Azure VM.
Later I re-provisioned (removed the VM and spawn another VM) machine again and followed exactly same steps and it worked without any issues.

**Comment by Eilon** [comment]
Ok, closing this out. If you do see this again you could try pushing your app to a public GitHub repo and we can try to reproduce this.
