### ISSUE TITLE
Publish to Azure via VS works, but GitHub deploy fails

### ISSUE THREAD

**Issue by mattdwen** [aspnet/Home#977]
I have a [project](https://github.com/group6tech/diva-focus) which I've been publishing from VS2015 to Azure with no issues for a while.

I've just switched it over to deploy via GitHub from the master branch. This has deployed okay according to Azure, but accessing the site gives the following error:

> Message: [RoslynCompilationException: D:\home\site\approot\src\FocusLogic\MessageService.cs(87,24): DNX,Version=v4.5.1 error CS0246: The type or namespace name 'Twilio' could not be found (are you missing a using directive or an assembly reference?)]

The solution has a couple of different projects. **Focus** is the main site, and is configured to be deployed with a `.deployment` file at the root of the solution with the following:

```
[config]
project = src/Focus
```

**FocusLogic** is a separate project in the same solution and repo, which has the NuGet reference to **Twilio**, which is the reference which is failing.
Manually inspecting `approot\packages` on the Azure site, I can see that `Twilio\4.0.0` exists, with the correct files.

The output log from the GitHub deployment is in [this gist](https://gist.github.com/mattdwen/92fd74d576a7450e50bb).

Manually deploying from VS again works correctly.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
