### ISSUE TITLE
Strong name signing for output assemblies

### ISSUE THREAD

**Issue by Tasteful** [aspnet/Home#979]
I know that there are two different camps of asseblies be signed with SNK or not.

At my company, we use SNK to ensure (together with authenticode signing) that the results are distributed to the users come from us.

Will the results of all projects included in ASPNET5 be signed with SNK (and maybe even authenticode signed)? 

When will this happen in such cases (before RC I hope)? 
if not, then all components that use ASPNET5 not be signed with SNK. How are we to ensure that the components come from us?

**Comment by Eilon** [comment]
Strong naming is already supported: https://github.com/aspnet/dnx/pull/2004

However, the packages published for ASP.NET and EF are themselves not yet strong-named, but that's tracked here: https://github.com/aspnet/dnx/issues/2615

So, this should be resolved in the near future. For further discussion on that, feel free to comment on the linked issue. Thanks!
