### ISSUE TITLE
Helios OWIN environment dictionary cannot be enumerated

### ISSUE THREAD

**Issue by jchannon** [aspnet/Home#98]
When using Helios with OWIN, any middleware that does any enumeration/LINQ on the OWIN environment eg/`env.First()` results in an exception with the message `This API can only be called if the request is being served over HTTPS.`

This can be got around by accessing items via the index/specific key and/or using `ContainsKey` but does seem a bit odd that you get a SSL message when trying to do enumeration.

It also means I can't log out all the items in the OWIN dictionary:

```
foreach (var item in env)
{
  Debug.WriteLine(item.Key + " : " + item.Value);
}
```

UPDATE : I'm referring to this ``` <package id="Microsoft.Owin.Host.IIS" version="1.0.0-alpha1" targetFramework="net45" />```

**Comment by GrabYourPitchforks** [comment]
This issue is now resolved in the Katana-based version pending the next release.
