### ISSUE TITLE
FromJsonUri attribute possible ?

### ISSUE THREAD

**Issue by ZOXEXIVO** [aspnet/Home#980]
In past version of ASP.NET MVC, I use FromJsonAttribute for my query objects, that use stateless queries from queryString
When I start writing this in vnext version i confused. How to do it ?

```c#
[HttpGet]
public async Task<IActionResult> List([FromJsonUri]QueryObject query)
{
}
```

**Comment by Eilon** [comment]
@ZOXEXIVO can you log this issue in the MVC repo? https://github.com/aspnet/Mvc/issues/

**Comment by ZOXEXIVO** [comment]
Ok. https://github.com/aspnet/Mvc/issues/3302
