### ISSUE TITLE
Can't run dnx commands from a solution root

### ISSUE THREAD

**Issue by dotboris** [aspnet/Home#981]
Every time I try to run a command from a project using `dnx -p SomeProject some-command` it complains about `project.lock.json` being missing even tho it's present. When I run the command by going to the directory of the project with `dnx some-command` it works.

Here's an example: https://gist.github.com/beraboris/6c1437de9d0ffbbc5355

In this case I have a `global.json` file pointing to the `test/` directory. I also have a test project with xunit called `SomeTest`. This project depends on xunit and its dnx runner. You should notice that I don't have a `test/SomeTest/project.lock.json` file.

I try to run `dnx -p SomeTest test` it complains about `test/SomeTest/project.lock.json` being missing. This is perfectly normal since the file is not there. The error also tells me to run `dnu restore`.

Following the advice from the error, I run `dnu restore` which creates `test/SomeTest/project.lock.json`. This is illustrated in the following command.

I try to run `dnx -p SomeTest test` again and I get the same error. This time it's not expected behaviour because the required file does exist.

I then try to go to the `test/SomeTest` directory and run the test command directly (`dnx test`) and the command runs fine.

I should note that I'm running Arch Linux 64 bit with dnx v1.0.0-beta7, and mono v4.0.3.

**Comment by victorhurdugaci** [comment]
@moozzyk might be able to help

**Comment by dotboris** [comment]
Considering that dnx is dead now and that I don't need this anymore I'm just going to close this
