### ISSUE TITLE
Complete F# support ?

### ISSUE THREAD

**Issue by bluemmc** [aspnet/Home#982]
Will ASP.NET 5 have complete F# support (old postings like "http://blog.alxandr.me/2014/11/23/f-in-asp-net-5-the-good-the-bad-and-the-really-ugly/" seems to indicate problems) ?

**Comment by Eilon** [comment]
@bluemmc there are no plans for the initial release to support any languages aside from C#. However, after the initial release we do plan to invest in support for other languages. In the meantime we're certainly not trying to explicitly block any other languages from working, but we're also not doing any work to make it any easier.

**Comment by dustinmoris** [comment]
That's a real shame. Where is the upvote button?

**Comment by Eilon** [comment]
I would recommend using the issue at https://github.com/dotnet/cli/issues/586 to track this, and it looks like maybe there's some stuff available to play around with. This issue here is no longer relevant because DNX is going away and we use .NET CLI for compilation.
