### ISSUE TITLE
TagHelpers not working Beta 7

### ISSUE THREAD

**Issue by Sm1le291** [aspnet/Home#985]
Hi! I use Asp.Net beta 7 now.
I follow this steps: 1) Create empty Asp.Net mvc 6 project, then add many needed dependencies with dependency Microsoft.AspNet.Mvc.TagHelpers too and add @addTagHelper directive in _ViewImports.cshtml
And this not working for me. A try to add AnchorTagHelper to .cshtml page, but this not transformed to valid element and in client looks like this _server tag with attrs_ (GitHub cuts tag=(

**Comment by oshalygin** [comment]
So you have the following in your _ViewImports?
> @addTagHelper "*, Microsoft.AspNet.Mvc.TagHelpers"

You're also including it in your package.json?

> "Microsoft.AspNet.Mvc.TagHelpers": "6.0.0-beta7"

Here is an example of some of the tag helper syntax
>  asp-controller="Home" asp-action="Index"...

It seems like you're doing everything correctly, maybe double check the addTagHelper syntax?

**Comment by Sm1le291** [comment]
Ok. I check at morning again)

**Comment by Sm1le291** [comment]
I checked. All Right. I noticed one detail. When a dublicate  addTagHelper in view that I needed, all works fine.

**Comment by Sm1le291** [comment]
You may see issue in this  project http://1drv.ms/1QqEmgW

**Comment by Sm1le291** [comment]
Ooh. I found problem. I place _Viewimports in /Views/Shared not in /Views . All works fine, exclude Intellisense - this does not work on Empty or StarterKit project

**Comment by NTaylorMullen** [comment]
@Sm1le291 for IntelliSense ensure that you have the `Microsoft.AspNet.Tooling.Razor` package in your project and are at least targeting `dnx451`.

**Comment by rhires** [comment]
Hmmm...yeah, I'm not getting Intellisense for Razor in VSCode, even though I have that package installed in my project. On the other hand, VSCode doesn't explicitly say that it supports Intellisense for VSCode. I sure wish it did!

**Comment by NTaylorMullen** [comment]
Ahh, in VSCode you will not get Razor IntelliSense sadly. Hopefully one day :smile:

**Comment by Sm1le291** [comment]
@NTaylorMullen I mean that autocomplete not works in .config files for bower or npm(for NuGet works well) - works only for version, not for package name! You may try this in my attached project above. 
But in some screenshots  on docs.asp.net I see that works for package name too

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
