### ISSUE TITLE
Referencing issue or bug as defined in Contributing.md and Git comment default char

### ISSUE THREAD

**Issue by peterblazejewicz** [aspnet/Home#986]
I've encountered a problem contributing one of the project when strictly following guides from Contributing.md referenced in all projects under aspnet organization:
```
Commit/Pull Request Format
Summary of the changes (Less than 80 chars)
 - Detail 1
 - Detail 2

#bugnumber (in this specific format)
```
The hash used on the line start works as comment char by default in git:
https://git-scm.com/search/results?search=core.commentchar

Technically I was able to enter the issue number to the commit but it was always ignored. The Google used better referencing schema for the last line for Git:
https://docs.google.com/document/d/1QrDFcIiPjSLDn3EL15IJygNPiHORgU1_OOAqWjiDU5Y/edit
In their notation:
```
Commit/Pull Request Format
Summary of the changes (Less than 80 chars)
 - Detail 1
 - Detail 2

Closes #bugnumber
```
Thanks!

**Comment by Eilon** [comment]
@peterblazejewicz in the Git tools I've used (TortoiseGit, GitHub for Windows, etc.) you can enter in any text and they process it. It could be that other tools treat `#` as a comment char.

But, either way, feel free to say `Fixes #123` or `Addresses #123` or whatever, as long as it's clear what issue the PR is addressing.

**Comment by peterblazejewicz** [comment]
@Eilon 
Thanks!
I should reword my issue to be strict, after second though. The commands like:
```
rebase -i 
```
or:
```
commit --amend
```
that is ones that fires up editor to edit commit message will simply remove the last:
```
#bugnumber
```
That's not big deail, but some peoople could miss that change in commit message.

**Comment by Eilon** [comment]
I updated the text on https://github.com/aspnet/Home/blob/dev/CONTRIBUTING.md to say:

> Summary of the changes (Less than 80 chars)
>  - Detail 1
>  - Detail 2
> 
> Addresses #bugnumber (in this specific format)

Thanks for the feedback!
