### ISSUE TITLE
ContentDispositionHeaderValue doesnt parse FileName and Name correctly

### ISSUE THREAD

**Issue by Gillardo** [aspnet/Home#987]
In order to upload a file, i have seen the example code here
https://github.com/aspnet/Mvc/commit/437eb93bdec0d9238d672711ebd7bd3097b6537d

To get the name of the file that is uploaded, i am using the ContentDispositionHeaderValue class, using the TryParse method, as used in the example, which is like so

        public async Task<IActionResult> PostAsync(IFormFile file)
        {
            ContentDispositionHeaderValue parsedContentDisposition;
            ContentDispositionHeaderValue.TryParse(file.ContentDisposition, out parsedContentDisposition);
            ....
        }

But it seems to include \" around the FileName and Name properties.

My Content-Disposition is the same as it was in MVC5, like so
    Content-Disposition: form-data; name="file"; filename="Key.png"

Since these properties are strings anyway, it doesnt need to wrap the values in quotes.

Fix is very simple

    parsedContentDisposition.FileName = parsedContentDisposition.FileName.TrimStart('\"').TrimEnd('\"');
    parsedContentDisposition.Name = parsedContentDisposition.Name.TrimStart('\"').TrimEnd('\"');

**Comment by Eilon** [comment]
I believe the value is supposed to be a quoted string, per the RFCs. See Section 4.1 of RFC 6266: http://tools.ietf.org/html/rfc6266#section-4.1

And `quoted-string` is defined here: http://tools.ietf.org/html/rfc2616#section-2.2

>        quoted-string  = ( <"> *(qdtext | quoted-pair ) <"> )
>        qdtext         = <any TEXT except <">>

So, while it is perhaps allowed to omit the quotes, it is certainly permitted.

The examples section in RFC 6266 makes this clear: http://tools.ietf.org/html/rfc6266#section-5

> 5.  Examples
> 
> 
>    Direct the UA to show "save as" dialog, with a filename of
>    "example.html":
> 
>      Content-Disposition: Attachment; filename=example.html
> 
>    Direct the UA to behave as if the Content-Disposition header field
>    wasn't present, but to remember the filename "an example.html" for a
>    subsequent save operation:
> 
>      Content-Disposition: INLINE; FILENAME= "an example.html"
> 
>    Note: This uses the quoted-string form so that the space character
>    can be included.

**Comment by rynowak** [comment]
Interestingly enough we wrote code to deal with this case specially in MVC for binding files: https://github.com/aspnet/Mvc/blob/eef6c3883a7e27b8387b0925f0b6a88df0a484c5/src/Microsoft.AspNet.Mvc.Core/ModelBinding/FormFileModelBinder.cs#L108

But not for sending them (when the CD contains a space):  https://github.com/aspnet/Mvc/blob/9342cb0ab78add8c527edcbc4c0988edc96f01e3/src/Microsoft.AspNet.Mvc.Core/FileResult.cs

This is exactly the kind of detail that I would hope using the strongly typed header classes would shield us from.

**Comment by Eilon** [comment]
@rynowak interesting. Would you say the code in https://github.com/aspnet/Mvc/blob/eef6c3883a7e27b8387b0925f0b6a88df0a484c5/src/Microsoft.AspNet.Mvc.Core/ModelBinding/FormFileModelBinder.cs#L108 is simply wrong, then? (At least *theoretically* wrong?)

**Comment by rynowak** [comment]
The code in `FormFileModelBinder` is *correct* according to my definition of correct - from the POV of the user's code, it matters not whether `example.html` or `"example.html"` was supplied as the CD. I can't find any specific language in the spec for quoted and non-quoted tokens being interchangeable but it seems heavily implied. 

It really seems like a gotcha if you're using our model binder and then suddenly a client supplies a quoted string and you have to write more codes to handle both cases. So I'd say what we have in this code is the correct behavior, but that it should be moved down a layer into the header class.

On the other hand, `FileResult` would seem to have an obvious bug when a filename has a space... except the header type handles this for us: https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.Net.Http.Headers/ContentDispositionHeaderValue.cs#L74

**Comment by Tratcher** [comment]
This issue was moved to aspnet/HttpAbstractions#446

**Comment by Shilpav44** [comment]
Hi Guys ,
I see you guys are saying the issue is fixed since am a new developer and trying to use the above functionality and it is not giving me the exact file name it give me the whole path of the file like
"C:\Users\25602\Desktop\Sathya.txt" where as I want Sathya.txt and even the Trim  function does not takes any parameter it says "No overloaded method Trim takes 1 argument" can you guys please help me

**Comment by Tratcher** [comment]
@Shilpav44 You can use Path.GetFileName to separate the path from the file.
