### ISSUE TITLE
System.IO and System.Threading don't support framework DNX,Version=v4.5.1?

### ISSUE THREAD

**Issue by timothy-shields** [aspnet/Home#990]
I have been successfully using beta7 with Windows and Linux on a large project for a while now.  I got a new Windows laptop, went through the Visual Studio 2015 and dnvm installations, and then tried to build my solution.  I now get these two errors for every project in my solution:

```
{projectpath}\project.json(0,0): error: The dependency System.IO 4.0.0.0 in project {project} does not support framework DNX,Version=v4.5.1.
{projectpath}\project.json(0,0): error: The dependency System.Threading 4.0.0.0 in project {project} does not support framework DNX,Version=v4.5.1.
```

I have fiddled with this for hours and been unable to get the solution building.  (Reinstalled dnvm from scratch, deleted local package caches, etc.)

How can I fix this problem?

I have provided what I think are relevant details below.

`dnvm list` prints this:

```
Active Version     Runtime Architecture OperatingSystem Alias
------ -------     ------- ------------ --------------- -----
  *    1.0.0-beta7 clr     x64          win
       1.0.0-beta7 clr     x86          win
```

`global.json` contains this:

```
{
  "sdk": {
    "architecture": "x64",
    "runtime": "clr",
    "version": "1.0.0-beta7"
  }
}
```

`nuget.config` contains this:

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="AspNetMaster" value="https://www.myget.org/F/aspnetmaster/api/v2" />
    <add key="NuGet" value="https://nuget.org/api/v2/" />
  </packageSources>
</configuration>
```

`project.json` for the simplest class library in my solution contains this:

```
{
  "compilationOptions": {
    "allowUnsafe": true
  },
  "dependencies": {
    "Ix-Main": "1.2.3",
    "MathNet.Numerics": "3.7.0",
    "Microsoft.AspNet.Mvc": "6.0.0-beta7",
    "Microsoft.AspNet.SignalR.Server": "3.0.0-beta7",
    "Microsoft.AspNet.WebApi.Client": "5.2.3",
    "Microsoft.Framework.Configuration.Json": "1.0.0-beta7",
    "MsgPack.Cli": "0.5.11",
    "Nito.AsyncEx": "3.0.0",
    "Rx-Main": "2.2.5",
    "System.Collections.Immutable": "1.1.36"
  },
  "frameworks": {
    "dnx451": {
      "frameworkAssemblies": { }
    },
    "dnxcore50": {
      "dependencies": {
        "Microsoft.CSharp": "4.0.1-beta-23225",
        "System.Collections": "4.0.11-beta-23225",
        "System.Console": "4.0.0-beta-23225",
        "System.Linq": "4.0.1-beta-23225",
        "System.Threading": "4.0.11-beta-23225"
      }
    }
  },
  "version": "1.0.0-*"
}
```

**Comment by Eilon** [comment]
@anurse @ericstj can one of you take a look?

**Comment by ericstj** [comment]
Both of those support DNX451 via Net45 assets, from the packages:
```
ref\net45\_._
lib\net45\_._
```

The placeholders are there to ensure an applicable asset group, they are placeholders to indicate that the actual reference comes from the targeting pack and the implementation comes from the inbox framework.

Looks like an issue with DNX's compat check.

**Comment by timothy-shields** [comment]
@ericstj I too suspected that the build error was erroneous. Let me know if there's anything diagnostic that you want me to try.

An additional point I left out is that `dnu list` complains about those two assemblies as well.

**Comment by timothy-shields** [comment]
@ericstj Can you think of any temporary workarounds I could try?

**Comment by anurse** [comment]
The four-digit version number (`4.0.0.0`) worries me slightly. The Packages all have three-digit numbers, only the framework reference assemblies have four-digit numbers. I'll try to see if I can take a look.

@timothy-shields You could try adding a direct dependency on the `System.IO` package. That would eclipse any dependencies below and might resolve the issue. We do have some logic to prefer framework references though so it might not work.

**Comment by ericstj** [comment]
Good point, @timothy-shields can you share your project.lock.json so I can determine which package was referencing 4-part versions?

**Comment by timothy-shields** [comment]
@anurse Good point. Now that you point that out, I see those are the only two assemblies out of hundreds which have that four-digit version number.  I have tried adding direct dependencies to `System.IO` and `System.Threading` but got lots of conflicts - it started complaining about basic types like `object` and `string` and there were thousands of exceptions.  But maybe I was doing that incorrectly.  Could you describe where and how you would add those direct dependencies in the `project.json` I provided?

@ericstj I have uploaded the `project.lock.json` to this public gist: https://gist.github.com/timothy-shields/1db35be7c0beffe0e511

**Comment by anurse** [comment]
Oof, you've got a really old version of `System.IO` in there. Can you clear out your `C:\Users\[username]\.dnx\packages` folder and re-restore? Also, remove the AspNetMaster feed from your NuGet.Config, the latest released versions of packages should be on `nuget.org` now.

**Comment by timothy-shields** [comment]
@anurse I cleared the local packages cache, removed AspNetMaster from my NuGet config, and then ran `dnu restore`.  There are two packages it is unable to locate:

- `Microsoft.AspNet.SignalR.Server >= 3.0.0-beta7`
- `xunit.runner.aspnet >= 2.0.0-aspnet-beta7-*`

I then readded AspNetMaster _after_ `nuget.org` and did `dnu restore`.

New `nuget.config` contents:

    <?xml version="1.0" encoding="utf-8"?>
    <configuration>
      <packageSources>
        <add key="NuGet" value="https://nuget.org/api/v2/" />
    	<add key="AspNetMaster" value="https://www.myget.org/F/aspnetmaster/api/v2" />
      </packageSources>
    </configuration>

Now my entire project is building and working.

**Comment by anurse** [comment]
A few notes on those remaining packages:
* `Microsoft.AspNet.SignalR.Server` is no longer supported, it was unfortunately dropped from the RTM plans: https://github.com/aspnet/Home/wiki/Roadmap#future-work - If you really need SignalR you can use it but remember that it is unsupported and may not be updated to match RTM. SignalR 3.0 is **not** gone, but just postponed until after ASP.NET 5 RTM.
* `xunit.runner.aspnet` was a temporary hack we produced and is now deprecated, you should be able to just replace it with `xunit.runner.dnx` which is produced by the xUnit.Net team and is published on nuget.org

**Comment by timothy-shields** [comment]
@anurse Thanks for the info.

**Comment by anurse** [comment]
Minor clarification: `Microsoft.AspNet.SignalR.Server` **3.0.0-*** is no longer supported. SignalR 2.0 remains fully supported, though I believe it is not compatible with ASP.NET 5 (but since it was OWIN-based, it might be possible to hack it :))

**Comment by HenryGarle** [comment]
Thanks for the info, managed to get my solution back up and running. A little distraught with the news SignalR is being pushed back given my entire project relies on it, serves me right I guess!

**Comment by anurse** [comment]
@HenryGarle We certainly aren't forgetting about it, we just had to prioritize to get a stable release :(.

**Comment by HenryGarle** [comment]
@anurse Thanks for the reply and I am glad to hear its still on the roadmap, I do fully understand and accept responsibility for going against the advice of not building anything on vNext until release, its entirely my fault. I've been beavering away for around 6 months building it with vNext because of  just how much of an advancement it is (And cross platform is important for the project). Taken this issue a little off topic so I apologize but thank you very much for bringing it up I would have missed it otherwise and keep up the great work!

**Comment by garora** [comment]
Thanks guy. I was wondering to resolve my issues and this thread give a
solution. I too had old packages and I cleared cache.

**Comment by jvsshinde** [comment]
Hello,
I am facing this issue in vs2017.
Can any one help me?

![issue](https://user-images.githubusercontent.com/25817836/27588468-d9a85c5e-5b65-11e7-8f16-2300972946f1.png)

**Comment by Tratcher** [comment]
dnx was depreciated more than a year ago. You'll need to update your project.

**Comment by davidfowl** [comment]
https://docs.microsoft.com/en-us/dotnet/core/migration/

**Comment by jvsshinde** [comment]
Hello Tratcher and Davidfowl,
Thanks for giving reply.
After your suggestion i migrate my project from **project.json to cspro**j successfully.
After migration one back folder automatically created and project.json and project.lock.json is moved to this folder.

Here is my project.json and project.lock.json file
![project_json](https://user-images.githubusercontent.com/25817836/27622211-4713cc82-5bf3-11e7-87f1-30330d8585bc.png)

![project_lock_json](https://user-images.githubusercontent.com/25817836/27622213-4c190b02-5bf3-11e7-8248-13bfe58163f3.png)

For migration, i followed this link
[https://dotnetcore.gaprogman.com/2017/03/09/converting-from-project-json-to-csproj/#migrate](url)
but after successfully migration i hit **dotnet restore** on window power shell command prompt. 
Then i got following error

![issue](https://user-images.githubusercontent.com/25817836/27621945-dc9971a0-5bf1-11e7-8153-c952a4a745df.png)

**Comment by moozzyk** [comment]
https://github.com/aspnet/SignalR-Server/blob/dev/README.md the new version of SignalR for ASP.NET Core is being worked on here: https://github.com/aspnet/SignalR. Note that currently there are only nightly builds available.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
