### ISSUE TITLE
Error Message/Sound when closing/stopping IIS Express application

### ISSUE THREAD

**Issue by Sharpiro** [aspnet/Home#994]
I get an error message and sound in Win10/VS 2015/Beta 8 whenever I close out an application.  For instance, I just created a web application from the asp.net 5 template.  If I run it with IIS Express, and then close internet explorer, the error occurs (usually too fast to see), but it plays the god awful error message sound 90+% of the time.  This also happens when I click "Stop Debugging".

Can confirm there is no issue when going back to my beta7 branch. likely relevant to ```Microsoft.AspNet.IISPlatformHandler``` replacing ```Microsoft.Aspnet.Server.IIS``` in beta 8

**Comment by GuardRex** [comment]
@Sharpiro Check my steps and notes ... see if any of that helps:  https://github.com/aspnet/Hosting/issues/364#issuecomment-148567294

**Comment by Eilon** [comment]
@sayedihashimi do you know a contact for IIS Express?

**Comment by Eilon** [comment]
Or is this a debugger issue? Sorry I may have misunderstood...

**Comment by sayedihashimi** [comment]
It's a known issue it requires an "in band" change to Visual Studio so the first time we can prevent the sound is in the first VS update. This is an unfortunate result of moving to HttpPlatfornHandler.
