### ISSUE TITLE
Add Existing Item dialog is missing "add as link" option

### ISSUE THREAD

**Issue by robertlevy** [aspnet/Home#996]
When going through the "Add Existing Item" dialog in prior versions, the "Add" button is actually a combobox that you can open to choose "Add as link".  For ASP.NET 5 projects, the "add as link" option is not present.

This feature was useful for having projects reference files that live elsewhere in the filesystem, not just beneath the same directory as the project itself.  The primary use case is sharing code between multiple projects.

**Comment by muratg** [comment]
@sayedihashimi

**Comment by sayedihashimi** [comment]
Thanks, its a feature that is on our backlog. We are planning to work on that as a part of a larger shared files feature. We have not yet started on that work yet. I'm not exactly sure when we will start at this time.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
