### ISSUE TITLE
Beta8 issue with IIS Express after upgrade

### ISSUE THREAD

**Issue by EgyTechnology** [aspnet/Home#997]
Hi
I was using beta7 and I upgrade project version to beta8.
After I upgrade project I can't debug project using IIS Express
I get message saying:
Could not load type 'Microsoft.Dnx.Host.Clr.EntryPoint' from assembly 'Microsoft.Dnx.Host.Clr, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. 

Error Source:
An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below. 

Stack Trace:
[TypeLoadException: Could not load type 'Microsoft.Dnx.Host.Clr.EntryPoint' from assembly 'Microsoft.Dnx.Host.Clr, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.]
   System.Web.HttpRuntime.HostingInit(HostingEnvironmentFlags hostingFlags, PolicyLevel policyLevel, Exception appDomainCreationException) +303

[HttpException (0x80004005): Could not load type 'Microsoft.Dnx.Host.Clr.EntryPoint' from assembly 'Microsoft.Dnx.Host.Clr, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.]
   System.Web.HttpRuntime.FirstRequestInit(HttpContext context) +9922864
   System.Web.HttpRuntime.EnsureFirstRequestInit(HttpContext context) +90
   System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest wr, HttpContext context) +261

Please tell me if there are any way to using project with beta8 on Windows with debugging because my client need project version to be Beta8

**Comment by moliveto** [comment]
Recreate a new proyect and copy your files into the new site

**Comment by EgyTechnology** [comment]
There are no way except create new project.

**Comment by damienbod** [comment]
I had the same problem, you need to update the IIS Express (Visual Studio web tools update) and then update the web.config in your project. 

Here's a blog explaining: 
http://damienbod.com/2015/10/16/asp-net-5-updating-to-beta8-from-older-beta-versions/

Greetings Damien
